### ISSUE TITLE
objc-tests: InteropTestsRemoteWithCronet test4MBResponsesAreAccepted failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10003]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/3190/consoleText

```
/jenkins/workspace/gRPC_pull_requests_macos/workspace_objc_macos_dbg_native/src/objective-c/tests/InteropTests.m:164: error: -[InteropTestsRemoteWithCronet test4MBResponsesAreAccepted] : ((error) == nil) failed: "Error Domain=io.grpc Code=3 "Received message larger than max (4194316 vs. 4194304)" UserInfo={io.grpc.TrailersKey={
}}" - Finished with unexpected error: Error Domain=io.grpc Code=3 "Received message larger than max (4194316 vs. 4194304)" UserInfo={io.grpc.TrailersKey={
Test Case '-[InteropTestsRemoteWithCronet test4MBResponsesAreAccepted]' failed (2.314 seconds).
```

**Comment by dgquintas** [comment]
This is keeping the macos master build red. Is the fix complex?

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/3314/testReport/junit/(root)/objc_macos_opt_native/objc_tests/

pr: https://github.com/grpc/grpc/pull/10076 against v1.2.x

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/3333/testReport/junit/(root)/objc_macos_dbg_native/objc_tests/

pr https://github.com/grpc/grpc/pull/9986 against v1.2.x

**Comment by y-zeng** [comment]
Seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/3346/testReport/junit/(root)/objc_macos_dbg_native/objc_tests/

pr #10087 against v1.2.x
