### ISSUE TITLE
installing google-cloud-speech breaks with broken grpcio-1.1.3

### ISSUE THREAD

**Issue by liudude123** [grpc/grpc#10006]
Tried to install google cloud speech apis and it broke at grpc:

> C:\_Dev\git\python-docs-samples\speech\cloud-client>pip install -r requirements.txt
Collecting google-cloud-speech==0.22.0 (from -r requirements.txt (line 1))
  Using cached google_cloud_speech-0.22.0-py2.py3-none-any.whl
Collecting gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0 (from google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached gapic-google-cloud-speech-v1beta1-0.14.1.tar.gz
Collecting google-cloud-core<0.23dev,>=0.22.1 (from google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached google_cloud_core-0.22.1-py2.py3-none-any.whl
Collecting grpcio<2.0dev,>=1.0.2 (from google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached grpcio-1.1.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): googleapis-common-protos<2.0dev,>=1.5.0 in c:\python27\lib\site-packages (from gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Collecting google-gax<0.16dev,>=0.15.0 (from gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached google-gax-0.15.8.tar.gz
Collecting grpc-google-cloud-speech-v1beta1<0.15.0dev,>=0.14.0 (from gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached grpc-google-cloud-speech-v1beta1-0.14.0.tar.gz
Collecting oauth2client<4.0dev,>=2.0.0 (from gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached oauth2client-3.0.0.tar.gz
Collecting google-auth<2.0.0dev,>=0.4.0 (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached google_auth-0.8.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0 in c:\python27\lib\site-packages (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Collecting httplib2>=0.9.1 (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached httplib2-0.10.3.tar.gz
Collecting google-auth-httplib2 (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached google_auth_httplib2-0.0.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in c:\python27\lib\site-packages (from grpcio<2.0dev,>=1.0.2->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in c:\python27\lib\site-packages (from grpcio<2.0dev,>=1.0.2->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): dill<0.3dev,>=0.2.5 in c:\python27\lib\site-packages (from google-gax<0.16dev,>=0.15.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): future<0.17dev,>=0.16.0 in c:\python27\lib\site-packages (from google-gax<0.16dev,>=0.15.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Collecting ply==3.8 (from google-gax<0.16dev,>=0.15.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached ply-3.8.tar.gz
Collecting pyasn1>=0.1.7 (from oauth2client<4.0dev,>=2.0.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client<4.0dev,>=2.0.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client<4.0dev,>=2.0.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf>=3.0.0->google-cloud-core<0.23dev,>=0.22.1->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pyreadline>=1.7.1 in c:\python27\lib\site-packages (from dill<0.3dev,>=0.2.5->google-gax<0.16dev,>=0.15.0->gapic-google-cloud-speech-v1beta1<0.15dev,>=0.14.0->google-cloud-speech==0.22.0->-r requirements.txt (line 1))
Installing collected packages: grpcio, httplib2, pyasn1, pyasn1-modules, rsa, oauth2client, ply, google-gax, grpc-google-cloud-speech-v1beta1, gapic-google-cloud-speech-v1beta1, google-auth, google-auth-httplib2, google-cloud-core, google-cloud-speech
  Running setup.py install for grpcio
    Complete output from command c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\steve\\appdata\\local\\temp\\pip-build-twfwkp\\grpcio\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\steve\appdata\local\temp\pip-qy3oz6-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_project_metadata
    creating python_build
    creating python_build\lib.win32-2.7
    creating python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_common.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_credential_composition.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_server.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win32-2.7\grpc
    copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win32-2.7\grpc
    creating python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_connectivity_channel.py -> python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win32-2.7\grpc\beta
    copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win32-2.7\grpc\beta
    creating python_build\lib.win32-2.7\grpc\framework
    copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win32-2.7\grpc\framework
    creating python_build\lib.win32-2.7\grpc\_cython
    copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win32-2.7\grpc\_cython
    creating python_build\lib.win32-2.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win32-2.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win32-2.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win32-2.7\grpc\framework\common
    creating python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win32-2.7\grpc\framework\foundation
    creating python_build\lib.win32-2.7\grpc\framework\interfaces
    copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win32-2.7\grpc\framework\interfaces
    creating python_build\lib.win32-2.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win32-2.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win32-2.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win32-2.7\grpc\framework\interfaces\base
    creating python_build\lib.win32-2.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win32-2.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win32-2.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win32-2.7\grpc\framework\interfaces\face
    creating python_build\lib.win32-2.7\grpc\_cython\_cygrpc
    copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win32-2.7\grpc\_cython\_cygrpc
    creating python_build\lib.win32-2.7\grpc\_cython\_credentials
    copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win32-2.7\grpc\_cython\_credentials
    running build_ext
    building 'grpc._cython.cygrpc' extension
    creating python_build\temp.win32-2.7
    creating python_build\temp.win32-2.7\Release
    creating python_build\temp.win32-2.7\Release\src
    creating python_build\temp.win32-2.7\Release\src\python
    creating python_build\temp.win32-2.7\Release\src\python\grpcio
    creating python_build\temp.win32-2.7\Release\src\python\grpcio\grpc
    creating python_build\temp.win32-2.7\Release\src\python\grpcio\grpc\_cython
    creating python_build\temp.win32-2.7\Release\src\core
    creating python_build\temp.win32-2.7\Release\src\core\lib
    creating python_build\temp.win32-2.7\Release\src\core\lib\profiling
    creating python_build\temp.win32-2.7\Release\src\core\lib\support
    creating python_build\temp.win32-2.7\Release\src\core\lib\surface
    creating python_build\temp.win32-2.7\Release\src\core\lib\channel
    creating python_build\temp.win32-2.7\Release\src\core\lib\compression
    creating python_build\temp.win32-2.7\Release\src\core\lib\debug
    creating python_build\temp.win32-2.7\Release\src\core\lib\http
    creating python_build\temp.win32-2.7\Release\src\core\lib\iomgr
    creating python_build\temp.win32-2.7\Release\src\core\lib\json
    creating python_build\temp.win32-2.7\Release\src\core\lib\slice
    creating python_build\temp.win32-2.7\Release\src\core\lib\transport
    creating python_build\temp.win32-2.7\Release\src\core\ext
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\server
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\server\secure
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\transport
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\alpn
    creating python_build\temp.win32-2.7\Release\src\core\lib\security
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\context
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\composite
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\fake
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\google_default
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\iam
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\jwt
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\oauth2
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\plugin
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\credentials\ssl
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\transport
    creating python_build\temp.win32-2.7\Release\src\core\lib\security\util
    creating python_build\temp.win32-2.7\Release\src\core\lib\tsi
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\client
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\client\secure
    creating python_build\temp.win32-2.7\Release\src\core\ext\client_channel
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\server\insecure
    creating python_build\temp.win32-2.7\Release\src\core\ext\transport\chttp2\client\insecure
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\grpclb
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\grpclb\proto
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\grpclb\proto\grpc
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\grpclb\proto\grpc\lb
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\grpclb\proto\grpc\lb\v1
    creating python_build\temp.win32-2.7\Release\third_party
    creating python_build\temp.win32-2.7\Release\third_party\nanopb
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\pick_first
    creating python_build\temp.win32-2.7\Release\src\core\ext\lb_policy\round_robin
    creating python_build\temp.win32-2.7\Release\src\core\ext\resolver
    creating python_build\temp.win32-2.7\Release\src\core\ext\resolver\dns
    creating python_build\temp.win32-2.7\Release\src\core\ext\resolver\dns\native
    creating python_build\temp.win32-2.7\Release\src\core\ext\resolver\sockaddr
    creating python_build\temp.win32-2.7\Release\src\core\ext\load_reporting
    creating python_build\temp.win32-2.7\Release\src\core\ext\census
    creating python_build\temp.win32-2.7\Release\src\core\ext\census\gen
    creating python_build\temp.win32-2.7\Release\src\core\plugin_registry
    creating python_build\temp.win32-2.7\Release\src\boringssl
    creating python_build\temp.win32-2.7\Release\third_party\boringssl
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\aes
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\asn1
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\base64
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\bio
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\bn
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\bn\asm
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\buf
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\bytestring
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\chacha
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\cipher
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\cmac
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\conf
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\curve25519
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\des
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\dh
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\digest
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\dsa
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\ec
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\ecdh
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\ecdsa
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\engine
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\err
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\evp
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\hkdf
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\hmac
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\lhash
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\md4
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\md5
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\modes
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\newhope
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\obj
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\pem
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\pkcs8
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\poly1305
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\rand
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\rc4
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\rsa
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\sha
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\stack
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\x509
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\crypto\x509v3
    creating python_build\temp.win32-2.7\Release\third_party\boringssl\ssl
    creating python_build\temp.win32-2.7\Release\third_party\zlib
    C:\Users\Steve\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DWIN32_LEAN_AND_MEAN=1 -Isrc\python\grpcio -Iinclude -I. -Ithird_party\boringssl\include -Ithird_party\zlib -Ic:\python27\include -Ic:\python27\PC /Tcsrc\python\grpcio\grpc/_cython/cygrpc.c /Fopython_build\temp.win32-2.7\Release\src\python\grpcio\grpc/_cython/cygrpc.obj -D_ftime=_ftime32 -D_timeb=__timeb32 -D_ftime_s=_ftime32_s
    cygrpc.c
    include\grpc/impl/codegen/compression_types.h(37) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
    creating users
    creating users\steve
    creating users\steve\appdata
    creating users\steve\appdata\local
    creating users\steve\appdata\local\temp
    creating users\steve\appdata\local\temp\tmp5jmnfr
    C:\Users\Steve\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC /Tcc:\users\steve\appdata\local\temp\tmp5jmnfr\a.c /Fousers\steve\appdata\local\temp\tmp5jmnfr\a.obj
    a.c
    Found cython-generated files...
    Found cython-generated files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\steve\appdata\local\temp\pip-build-twfwkp\grpcio\setup.py", line 276, in <module>
        cmdclass=COMMAND_CLASS,
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
        _build_ext.run(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\users\steve\appdata\local\temp\pip-build-twfwkp\grpcio\src\python\grpcio\commands.py", line 286, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "c:\users\steve\appdata\local\temp\pip-build-twfwkp\grpcio\src\python\grpcio\commands.py", line 281, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\python27\lib\distutils\command\build_ext.py", line 498, in build_extension
        depends=ext.depends)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 548, in compile
        raise CompileError(msg)
    CompileError: command 'C:\\Users\\Steve\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by kpayson64** [comment]
Have you tried updating pip?  It looks like you are trying to build from source on windows, which shouldn't happen if you have the latest version of pip.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; please let us know if you encounter problems installing `grpcio` using `pip` 9.0 or later.
