### ISSUE TITLE
TypeError: grpc.buildServer is not a function

### ISSUE THREAD

**Issue by FullTS** [grpc/grpc#10011]
**env**
NodeJS 6.10

It seems no `buildServer` on `grpc`, so whether the document is too old?
And what is the latest way to build server?

[http://www.grpc.io/docs/tutorials/basic/node.html]()

**Comment by murgatroid99** [comment]
The document is old. I didn't even realize it was so out of date. I suggest looking at the [current examples](https://github.com/grpc/grpc/tree/master/examples/node) to see what that code looks like now.

**Comment by murgatroid99** [comment]
The linked documentation has now been updated with the correct API usage.
