### ISSUE TITLE
C++ Asynchronous Streaming RPC example

### ISSUE THREAD

**Issue by eduherminio** [grpc/grpc#10013]
Hi everybody,

Could anyone add/post a (simple) example which uses a both streaming and asynchronous RPC?
There are async examples (`greeter_async_client` & `greeter_async_server` in helloworld) without streaming; and streaming examples (in routeguide) but synchronous.

I'm having a hard time implementing a simple Server streaming, asynchronous RPC using C++.

Thanks in advance,

Eduardo

**Edit**:
What I am really seeking is to do something else in the server appart from attending its clients, while keeping an open stream with them (so that I can decide to send them new info when necessary); and that's why I thought a Asynchronous Streaming RPC could solve my problem.

- With a synchronous, streaming RPC (routeguide example) I'm not being able to keep the connection opened in the server so that a new data stream can eventually be sent to the client (I need to send them data when received from somewhere else).

- With an asyncrhonous, non streaming RPC (helloworld example) I'm being unable to do anything else in the server appart from attending its clients (for example, generating new data to be sent). Here is the `HandleRpcs()` function included in `greeter_async_server` example and the `while(true)` loop with `GPR_ASSERT()` that stops me from doing anything else
```
  void HandleRpcs() {
    new CallData(&service_, cq_.get());
    void* tag;  // uniquely identifies a request.
    bool ok;
    while (true) {
      GPR_ASSERT(cq_->Next(&tag, &ok));
      GPR_ASSERT(ok);
      static_cast<CallData*>(tag)->Proceed();
    }
  }
```

#
https://github.com/grpc/grpc/issues/6504

**Comment by makdharma** [comment]
#8934 Please take a look at this PR and add your comments there.

**Comment by AspirinSJL** [comment]
Assigning to @vjpai because he has been doing the code review for #8934.

**Comment by vjpai** [comment]
There are more examples now along with a lot more documentation.

**Comment by lucifercr07** [comment]
> There are more examples now along with a lot more documentation.

Can you please point out the examples?

**Comment by andygikling** [comment]
Bump,

@vjpai What examples are you talking about?  The latest grpc tag 1.15 does not provide a c++ async bidi example.  #8934 is the only good example I've seen but it's not done.
