### ISSUE TITLE
Document when each op completes

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1002]
It would be nice to have documentation specifying what exactly causes a completion for each op type (especially the `SEND` op types). Does the channel need to be connected to get a completion for `GRPC_OP_SEND_INITIAL_METADATA`? Can `GRPC_OP_SEND_CLOSE_FROM_CLIENT` complete before the server requests a call? etc.

**Comment by murgatroid99** [comment]
It would also be good to know when exactly I am allowed to send an op of any given type.

**Comment by ctiller** [comment]
Documentation only PR.
