### ISSUE TITLE
Security handeshake fails with FD shutdown in forked child

### ISSUE THREAD

**Issue by damleak** [grpc/grpc#10025]
I am trying to make c++ grpc server a daemon process by forking a child and making parent exit. But after that the client handshake starts to fail.

E0307 01:15:58.221786152   27094 handshake.c:128]            Security handshake failed: {"created":"@1488878158.221756436","description":"Handshake read failed","file":"src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1488878158.221740996","description":"FD shutdown","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":948}]}

This happens when fork() is called after the call to BuildAndStart(). If the same fork is done before BuildAndStart() everything works fine.
Wondering if this a bug or not ?

**Comment by dgquintas** [comment]
See http://stackoverflow.com/questions/42867461/ssl-handshake-fails-in-grpc-server-after-calling-fork/
