### ISSUE TITLE
How to compile gRPC++ without a C++11 compiler

### ISSUE THREAD

**Issue by ruben11291** [grpc/grpc#10036]
Hello everybody,
I tried to cross-compile GRPC (head commit d1287b580e9a4dff160d61bb5766c2fd95fe4c79) for the ARMv7 architecture. 
The compilation was normal according to #9719, but there are some incompatibilities regarding the compiler version and the std=c++11 flag.
The error is the following:

```
arm-linux-gnueabi-g++ -march=armv7-a -mthumb-interwork -mfloat-abi=softfp -mfpu=neon --sysroot=/opt/eldk-5.3-vybrid/armv7a/sysroots/armv7a-vfp-neon-linux-gnueabi -Ithird_party/protobuf/src -Ithird_party/googletest/include -Ithird_party/boringssl/include  -I/home/anybody/cifpecom2/release/linux-vf6-1.14.0/target/root/usr/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -O2 -fPIC -I. -Iinclude -I/home/anybody/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\"    -O2 -pipe -g -feliminate-unused-debug-types -fpermissive -I/home/anybody/anybody/release/linux-vf6-1.14.0/target/root/usr/include -std=c++11   -MMD -MF /home/anybody/grpc/objs/opt/src/cpp/server/health/default_health_check_service.dep -c -o /home/anybody/grpc/objs/opt/src/cpp/server/health/default_health_check_service.o src/cpp/server/health/default_health_check_service.cc
src/cpp/server/health/default_health_check_service.cc: In constructor 'grpc::DefaultHealthCheckService::DefaultHealthCheckService()':
src/cpp/server/health/default_health_check_service.cc:134:17: error: 'class std::map<std::basic_string<char>, bool>' has no member named 'emplace'
Makefile:2363: recipe for target '/home/anybody/grpc/objs/opt/src/cpp/server/health/default_health_check_service.o' failed
```

The version of the compiler is the following:
```
arm-linux-gnueabi-g++ (GCC) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I've read from several sources ( http://stackoverflow.com/questions/15812276/stdset-has-no-member-emplace[)](http://stackoverflow.com/questions/15812276/stdset-has-no-member-emplace) that my compiler current version does not support c++11, so 
the emplace operation from std::map is also not supported sorrowfully.

I'm researching about how modifing these line, but could you upgrade a new patch?

Thanks in advance, 
Rubén.

**Comment by nicolasnoble** [comment]
The C++ part of gRPC uses C++11 heavily, not just here. That error is the first one in the slew of problems you'd encounter.

I would recommend grabbing a more recent toolchain if you want to proceed any further.

**Comment by vjpai** [comment]
Hi there, if you really need to build gRPC C++ API for a pre-4.8 version of gcc, you can consider pulling from the release 1.0 branch and then let me know if that works for you. We used to support the limited subset of C++11 in gcc 4.4-4.7 until the 1.0 release but [since then have only supported compilers that support most/all C++11 features](https://github.com/grpc/grpc/pull/8602).

**Comment by ruben11291** [comment]
OK @vjpai  I'll try it as soon as possible and I'll report any feedback that results.

**Comment by vjpai** [comment]
Hi @ruben11291 , is there any follow-up or should we close this issue?
Thanks!

**Comment by ruben11291** [comment]
Yes, the version 1.0 is supported by gcc 4.7 without any issue.
Thanks @vjpai !
