### ISSUE TITLE
(Async non-blocking)how to check request comes, and not block current thread.

### ISSUE THREAD

**Issue by w359405949** [grpc/grpc#1004]
it is useful in client-update mode.

there seems no exist example use async-non-block-mode. 
async-mode test code is one-ask-one-answer, which is useless.

**Comment by vjpai** [comment]
Just to clarify, are you interested in a non-blocking check API or some sort of active notification to the current thread?

**Comment by w359405949** [comment]
yeah, if i run an loop for my app(like game, both server&&client), i may not want to be blocked.

**Comment by ctiller** [comment]
It's probably worth exposing the deadline from the C api up into
CompletionQueue::Next. It's there to solve this problem.

**Comment by vjpai** [comment]
Yup, seems like it should be a change with very few lines of code... will address.

**Comment by ctiller** [comment]
It'll need some small amount of thought as to what the return value should
be (how do you distinguish shutdown from timeout?)

**Comment by vjpai** [comment]
It will also require writing a test for this.

**Comment by vjpai** [comment]
As for return value, I would suggest that the return value should be true (not shutdown) but the tag should be set to NULL. That way it's clear that we're not shutting down but at the same time we have nothing available for us.

**Comment by ctiller** [comment]
NULL tag values are legal.

It almost needs to be a tri-state return value: {OK, SHUTDOWN, TIMEOUT}.

**Comment by vjpai** [comment]
Oops, wasn't aware that NULL was a valid tag. Ok, we need a tri-state return then.

**Comment by ctiller** [comment]
The use case is for casting an integer index into an array into a void* as
a tag value.

**Comment by vjpai** [comment]
I have created a pull request with the relevant diff, but there is no test yet for the nonblocking next case. That still needs to be written before any merge.

**Comment by w359405949** [comment]
ok, i think i forgot something, "does non-blocking can also work in sync-mode?"

**Comment by vjpai** [comment]
Pull request #1023 addresses this issue and hopefully will merge soon. But I'm not sure that I understand your last followup: "does non-blocking can also work in sync-mode?" I am assuming that you're referring to making client side stream read operations nonblocking - is that correct? In which cases would you like to see a nonblocking check in sync mode?

**Comment by vjpai** [comment]
Pull request #1023 has been merged.

**Comment by w359405949** [comment]
a nonblocking check in sync mode

**Comment by vjpai** [comment]
For which sync operations would you like to use this check?

**Comment by w359405949** [comment]
example:

 while (reader->Read(&point)) {
      point_count++;
      if (!GetFeatureName(point, feature_list_).empty()) {
        feature_count++;
      }
      if (point_count != 1) {
        distance += GetDistance(previous, point);
      }
      previous = point;
    }
==============
i do not know how many point may read,  blocked. if all cpu_core_nums threads blocked. nothing can work now.

if a sync reader/writer can stored in a std::map/vector/set, it is more easy to understand and use for me.

a chatroom example like this:
class ChatRoom
{
public:
    Status EnterRoom(request, writer) //Subscripe, rpc method from .proto
    {
        // check request.username, request.token.

        peer_writers.push_back(writer);
        return OK;
    }

    Status PeerSay(reader, response)  // rpc method from .proto
    {
         std::string message;

        while(reader.Read(message)) { // more than one message.
            foreach(peer_writer : peer_writers) {
                 peer_writer.Write(message);
            }
        }
         return OK;
    }

private:
    std::vector<wrtier> peer_writers;
};

**Comment by w359405949** [comment]
and i also confused the way to use async-non-blocking.

example:
```
  void AsyncBidiCallback(server_stream)
{
    std::string message;
    server_stream.Read(message);
    server_stream.Write(message);
}

service_.RequestBidiStream(&srv_ctx, &srv_stream, &srv_cq_, AsyncBidiCallback);
/*
 * after a while. does it work like below?
 */
AsyncBidiCallback* callback_tag;
srv_cq_->Next(&callback_tag, &ok) 
callback_tag(srv_stream); 
```

**Comment by vjpai** [comment]
Thanks for the detailed example! I'll follow up with you on making that work in sync mode with some nonblocking checks

**Comment by vjpai** [comment]
The tag is just a value that you can use however you want to. You can use it as a function pointer if you like, but you can also use it for any other purpose (as it is just used in async_end2end_test.cc as an integer to check the message sequence). But the basic idea is as you described it; you call the Request for each supported RPC method with context, the reader/writer structure that you use for managing the stream, the completion queue, and the tag, and then in the future you call Next (or now AsyncNext) with a pointer for the tag and the boolean ok. You should also check the return value of Next to see if it's a shutdown situation (or timeout in the case of AsyncNext).

**Comment by w359405949** [comment]
so.....it's weird.

first, server_cq_, it may mixed variable tags(callbacks), i do not know the diffrences of tags(define a Closure and call Run, like protobuf2 did?).

second, before i recieve an async call, i must "register" a tag after call Next at evertime? i should never know when and how many times the method  will be called, and i think it should be auto finished by the protobuf(like protobuf2) or grpc.

**Comment by vjpai** [comment]
You can use the tags for callbacks or closures if you like, but there is no requirement to do so; they are a value associated with each event for you to use as you please.

I'm going to create a new issue for the 2nd paragraph of your last request, as it's a different API feature request and likely to get forgotten if not separated.

**Comment by vjpai** [comment]
Status report since this issue hasn't been touched in a week: the desired feature is fully in place in the async case but we have not yet decided an API for the sync case. Hope to move forward on this in the near future.

**Comment by vjpai** [comment]
I'd like to close out this issue since it was originally about the async API. I will open up a new issue for the sync API.
