### ISSUE TITLE
Bump PHP Protobuf Version to 3.2.0

### ISSUE THREAD

**Issue by mcos** [grpc/grpc#10069]
Protobuf v3.2.0 has been released for some time (https://github.com/google/protobuf/releases/tag/v3.2.0), yet the `php` dependency is still tied to  `Protobuf v3.1.0`, even though `Protobuf 3.2.0` added a lot of `php` support. Can these be upgraded to align? There's an issue with downstream projects that have a composer dependency on `Protobuf 3.2.0` that wish to use this library.

**Comment by stanley-cheung** [comment]
I changed the `composer.json` file to use `^3.1.0` so it should pull in 3.2.0 (or any newer minor version). This change is going to the gRPC PHP 1.2.0 that should happen soon.

**Comment by mcos** [comment]
Okay, excellent @stanley-cheung, thanks. I saw that was the case in the master branch, I was originally looking at the `v1.1.0` release. We updated our composer reference to use a commit hash from master while we wait for the new version and it worked. Thanks. Closing this issue as fixed.
