### ISSUE TITLE
TLS Golang Server not working with Node-js and Python Client

### ISSUE THREAD

**Issue by uguessmyid** [grpc/grpc#10062]
We are running a go-grpc server with TLS enabled.
When we use the go-grpc-client it works perfectly fine with the Server.
But when we try python and node js grpc clients with go-grpc server it is throwing exceptions

Client-Side-Exceptions(Python):

grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

Server-Side-Exceptions(Go):

transport: http2Server.HandleStreams failed to receive the preface from client: EOF

**Comment by uguessmyid** [comment]
The Issue has been Resolved.

**Comment by jimthematrix** [comment]
@uguessmyid can I ask how your resolve this issue? we are seeing exactly the same error trying to connect from a node.js program to golang via grpcs. also the same situation as yours where a golang client to the same golang server works fine.

**Comment by jimthematrix** [comment]
turns out it's a hostname mismatch problem, the server cert has CN=<name1> but the grpcs endpoint url is localhost:7050. once I set the client ssl option with hostnameoverride to match the <name1> I was able to get past this error

**Comment by joshadambell** [comment]
I am running in to the same issue as you. What do you mean by `once I set the client ssl option with hostnameoverride to match the I was able to get past this error`?

**Comment by jimthematrix** [comment]
@joshadambell let's say my target server has a certificate with CN=peer0.example.com, but the server is running on localhost. I need to pass "ssl-target-name-override": "peer0.example.com" to the grpc client constructor so the client's certificate validation during TLS handshake will pass successfully.

**Comment by aakarshit-batchu** [comment]
@joshadambell , As @jimthematrix has mentioned, when you are generating the Certificate it takes a value called "CN" which is a server hostoverride name. So the Server cert has CN but not the endpoint url. So try using server-hostname-override field on your client side to connect with your server.

//Example in Nodejs
for example: If your CN = joshadambell.server
`  var options = {
  'grpc.ssl_target_name_override' : 'joshadambell.server', 
  'grpc.default_authority': 'joshadambell.server'
  };`

And you will pass this options field to your client function along with your endpoint url and certfile.

**Comment by zhuhw** [comment]
I'm still getting handshake failure after following your step:

```
E0823 14:12:41.501713000 140736657433536 ssl_transport_security.c:192] ssl_info_callback: error occured.

E0823 14:12:41.501875000 140736657433536 ssl_transport_security.c:940] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.
```

My sanitized code snippet:

```
const grpc = require('grpc');
const fs = require('fs');

const serviceProto = grpc.load('../proto/service.proto');
const credential = grpc.credentials.createSsl(
  fs.readFileSync('ca.pem'),
  fs.readFileSync('client.key'),
  fs.readFileSync('client.pem')
);
const options = {
  'grpc.ssl_target_name_override' : '{CAname}',
  'grpc.default_authority': '{CAname}'
};
const client = new serviceProto.packageName.ServiceName('{ip:port}', credential, options);

client.getUserById(
  {id: '123'},
  function (error, response) {
    if (error) {
      console.log('Error: ', error);
    } else {
      console.log(response);
    }
  }
);
```

**Comment by jimthematrix** [comment]
@zhuhw another relevant setting is process.env.GRPC_SSL_CIPHER_SUITES, here's the values I'm using "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384"

**Comment by zhuhw** [comment]
@jimthematrix Thank you very much! Add this solves my problem.

**Comment by feulf** [comment]
@jimthematrix thank you so much! This fixed my issue. 

I spent 3 days trying to make a Node client communicate via RPC with LND, the Golang implementation of lightning-network.

Can you please explain what is the GRPC_SSL_CIPHER_SUITES and where did you get that string? Thanks!

**Comment by neogeno** [comment]
@feulf It would seem that the GRPC_SSL_CIPHER_SUITES is an environment variable used by GRPC to determine what cipher suites / encryption algorithms to use when connecting over TLS. It is explained here https://github.com/grpc/grpc/blob/master/doc/environment_variables.md.

LND allows one any one of 4 cipher suites mentioned here https://github.com/lightningnetwork/lnd/blob/master/lnd.go#L77 and so what @jimthematrix asked you to do was include a string which covers all the major cipher suites so one of them would work when connecting. Hope this helps.

**Comment by shotahino** [comment]
@aakarshit-batchu  @jimthematrix 
What about a certificate does not have `CN` but it has `SAN` set?
Can I use `SAN` and pass it to `grpc.ssl_target_name_override` ?
