### ISSUE TITLE
MacOS build currently doesn't properly work.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1007]
Many tests are currently failing under MacOS. A git bisect revealed that 64d0a87d98783be9eba8fcad184f9a7399144add is what's causing the issues.

**Comment by ctiller** [comment]
Oh joy.

This could be tricky to fix properly.
MacOS seems to be a little hesitant to perform some of the writes we want
immediately, and so we get frequent EAGAINs.
Many of the tests are written single threaded to make them easier to reason
about, and so they're not necessarily polling on the thing that needs to be
polled on (whereas a real app would be).

Thoughts:
- turn down the backup poller delay for Mac (or for tests)
- increase socket buffer sizes
- rewrite all tests

**Comment by vjpai** [comment]
The mac build is stil currently failing because I believe it has not been touched in some time. We need to revisit the commit in question ASAP.

**Comment by vjpai** [comment]
I want to add the following. Although this particular commit has gotten the blame, it does not seem to be responsible for the failing tests. I manually reverted that commit in my branch, and it does not change the fact that dozens of C tests and several C++ tests fail on Mac. It is something else going on.

**Comment by vjpai** [comment]
Backing out my previous comment of a few minutes ago. I manually reverted the suspect commit in my fork to see what would happen on my Mac. Reverting it does seem to reduce the number of test failures, though I cannot yet guarantee that it solves them all.

**Comment by vjpai** [comment]
One more issue is that the recent transport_security_test.c update is no longer consistent with the Mac INSTALL instructions. Need to update the INSTALL.

**Comment by vjpai** [comment]
So the current status is that the mac test for grpc_credentials_test is consistently broken, but some other tests are flaky. I'll report the flakes separately.

**Comment by vjpai** [comment]
SUCCESS: All tests passed

I believe that the Mac build is now just as functional as the Linux build - there are flakes, but only the same flakes that are already known on the Linux build. As such, I would like to suggest closing this issue. Any objections?
