### ISSUE TITLE
Retrieve SSL certificate on call at grpc server side

### ISSUE THREAD

**Issue by valorcurse** [grpc/grpc#10088]
I have a gRPC client/server combination which uses the SSLCredentials method for encrypting the communication. 
I'm trying to retrieve the client's SSL certificate on the server' side (which is written in C++) so I can distinguish between different clients calling the server.

So far I've only been able to find [an example for Go](https://github.com/grpc/grpc-go/issues/111) which seems to do roughly that, but on the C++ side I was only able to find the [AuthMetadataProcessor overloading](http://stackoverflow.com/questions/41051041/intercept-grpc-c-calls-in-server-and-client?rq=1) which only provides the information below, which isn't what I need.

    :authority  =  localhost:50051
    :path  =  /API.GameDatabase/saveData
    grpc-accept-encoding  =  identity,deflate,gzip
    grpc-encoding  =  identity
    user-agent  =  grpc-csharp/1.0.1 grpc-c/1.0.1 (linux; chttp2)
    Dispatch value:  "/API.GameDatabase/saveData"

Would this be possible or would I have to send this kind of metadata myself?

**Comment by jboeuf** [comment]
CCing @jiangtaoli2016 FYI.

You can get this information from the [auth_context](
https://grpc.io/grpc/cpp/classgrpc_1_1_server_context.html#a2a8657d382cee53d670208d640383e8e)
[GetPeerIdentity](https://grpc.io/grpc/cpp/classgrpc_1_1_auth_context.html#a56a84468c1c3814a185cb6a2a3badf99) will give you the list of SANs or the CN if the SANs are not available. You can find the complete PEM cert by looking up the [PEM cert property `GRPC_X509_PEM_CERT_PROPERTY_NAME`](https://grpc.io/grpc/cpp/grpc__security__constants_8h.html#ad46c3fd565d6a24eeb25d1fdc342cb28) [by name](https://grpc.io/grpc/cpp/classgrpc_1_1_auth_context.html#ac32b53377f8b7e44328f791f44bd6732) on the auth context.
