### ISSUE TITLE
Windows workers need Python's six library installed

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#10118]
[six](https://pythonhosted.org/six/) is the library we use to help with compatibility between Python 2 and Python 3.

This should just be a small chore but it looks like [it is blocking](https://grpc-testing.appspot.com/job/gRPC_pr_win/3382/console) @thunderboltsid's [work](https://github.com/grpc/grpc/pull/10115). @matt-kwong: grab me in the office tomorrow and let's work through it together?

**Comment by ctiller** [comment]
Any reason we can't stick to 2.7 for our build environment?

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: this issue is about making our Windows workers compatible with our scripts' becoming source-compatible-with-both-versions even if we choose to keep our own test infrastructure 2.7-only.

As to the separate question of whether our scripts should be source-compatible-with-both-versions: only to the extent that we want to make contributing to the codebase smooth for developers who are working in a Python-3-only or Python-3-first environment (so my answer is an emphatic "yes!", because there are more and more such developers and environments every day). It's already the case that developers can _use_ gRPC Python with Python 3; I think it's worth the little work it would take to make it the case for developers to fix, modify, and extend gRPC with Python 3.

Now as to the also-separate question of whether or not we should _drop_ our use of 2.7 in our testing infrastructure: [the clock is only ticking](https://pythonclock.org/) and the maintainers have pushed back on all but the most high-priority security fixes. Our Jenkins installation is nearly two years old; what are the odds that it will still be around after another three years?

**Comment by jtattermusch** [comment]
adding six to all our windows workers (and adding a note about that in the jenkins config document) pretty trivial, but I don't have cycles for that at all. Unassigning myself. Please ask @matt-kwong for help.

**Comment by matt-kwong** [comment]
Closing because six in installed on the Windows workers. 

As for the question of whether we should drop 2.7 from our testing infrastructure, I would say that the priority for this is pretty low and should be opened in another issue if we want to continue the discussion on that.
