### ISSUE TITLE
C++ TSAN cpp_protobuf_async_streaming_qps_unconstrained_insecure_500kib_resource_quota FLAKY

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10129]
Happened in https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/2736/consoleFull

**Comment by apolcyn** [comment]
seen again from pr: https://github.com/grpc/grpc/pull/10306

log in https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/10409/testReport/junit/(root)/benchmarks/qps_json_driver_cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota/

**Comment by makdharma** [comment]
Seen slightly different variation in pr #9810  - cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure

Log here: 
https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/3185/

**Comment by dgquintas** [comment]
Not seen in quite a while, closing.
