### ISSUE TITLE
Error: Cancelled, when I use the cancel method in the node client

### ISSUE THREAD

**Issue by lucifercha** [grpc/grpc#10121]
when i use `call.cancel()` in my node client, it throw a error : 
![image](https://cloud.githubusercontent.com/assets/3349701/23840905/0f878c26-07e4-11e7-8886-e71f438a619c.png),but it really can stop the connection from server.And I try `grpc.getClientChannel(clientObj.client).close()` it does not work

**Comment by muxi** [comment]
ping.

**Comment by murgatroid99** [comment]
With streaming calls, you should be listening for the `error` event to handle to handle call failures.

**Comment by shanshanzhu** [comment]
@murgatroid99 the `error` event can also be triggered by grpc server as well. In that case, there is no way for grpc client to tell the difference. Is it possible to fix it? I asked under this issue:
https://github.com/grpc/grpc/issues/8023

**Comment by murgatroid99** [comment]
The error event gives you an error object, which has a `code` property, which is a member of `grpc.status`. So for example, if you want to handle cancellations differently from other errors, you can check whether the code is equal to `grpc.status.CANCELLED`.
