### ISSUE TITLE
Generated code should append something unique rather than "Raw"

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#10132]
Hi,

I ran into a C++ build issue because generated code uses "Raw" literal to decorate the code (example - `"Async$Method$Raw(context, request, cq));\n"`). I have pre-existing rpcs that are called (RpcName) and (RpcName)Raw. This results in a build conflict. 

Is it possible to change the code generator to use something more unique like (gRPCRaw) that is less likely to collide?

Thanks.

**Comment by nicolasnoble** [comment]
Using any prefix like gRPCRaw might still end up colliding later, albeit I'll agree this would be less likely. Maybe the best course of action would be some sort of collision detection within the code to generate unique and predictable names by adding something to the suffix.

**Comment by abaldeva** [comment]
I am not entirely clear about what you mean by 
>>collision detection within the code to generate unique and predictable names by adding something to the suffix
Are you suggesting that code generator look at all the rpc names etc. in advance and then figure out a potentially unique suffix? And that could change from service to service?

**Comment by abaldeva** [comment]
Hi,

Any updates here?

Thanks.

**Comment by abaldeva** [comment]
Today, I found a similar issue in C# code generation. It generates <rpc name>+Async methods internally. So if you already have <rpc name> and <rpc name>Async rpcs (so for example, getGame and getGameAsync), the code generation creates files that fail to build.
