### ISSUE TITLE
Ruby server ActiveCall#cancelled? never returns true.

### ISSUE THREAD

**Issue by newtonapple** [grpc/grpc#10144]
Here is a simple demo to reproduce the problem: 

### say.proto:
```protobuf
syntax = "proto3";

service Say {
  rpc Hi(HiRequest) returns (HiResponse);
}

message HiRequest {}
message HiResponse {
  string message = 1;
}
```
Generate the standard ruby files using `protoc` + `grpc_ruby_plugin`... 

### say_client.rb
```ruby
require 'grpc'
require 'say_services_pb'

stub = Say::Stub.new("0.0.0.0:50051", :this_channel_is_insecure)
op = stub.hi(HiRequest.new, return_op: true)
t = Thread.new { op.execute }  # async request
sleep(2)  # sleeps for 2 seconds then cancels the operation
op.cancel
puts "cancelled..."
t.join  # throws a GRPC::Cancelled exception then exists
```

### say.rb
```ruby
require 'grpc'
require 'say_services_pb'

module Say
  class Server < Service
    def hi(request, call)
      until call.cancelled? do # server will wait for the client to cancel and check the cancelled? status every second
        puts "running hi..."  # this will run forever even after client cancels the call
        sleep(1)
      end
      puts "cancelled..."
      HiResponse.new(message: 'hi')
    end
  end
end

if __FILE__ == $0
  s = GRPC::RpcServer.new
  server_uri = "0.0.0.0:50051"
  s.add_http2_port(server_uri, :this_port_is_insecure)
  s.handle(Say::Server)
  puts server_uri
  s.run_till_terminated
end
```

Start the server first by running `say.rb`, then run `say_client.rb`.  The client will cancel the request in 2 seconds.  After that, the server will keep on running and keep outputting "running hi..."

**Comment by apolcyn** [comment]
Thanks for the repro here. 

So the `cancelled?` method is non-blocking and returns immediately - it doesn't call in to the core library to potentially block waiting for a status - or cancelled, so it looks like that's why it doesn't pick up on the cancelled call. 

Changing this looks a bit tricky without changing the current non-blocking behavior of `cancelled` - cc @murgatroid99 

As is, the best way to pick up on a cancelled call it on the server side is probably to try to read or write from a stream - perhaps in a separate thread.

**Comment by murgatroid99** [comment]
This `cancelled?` method actually does something very different than what you expect. It's actually a check, on the client side, to see whether a call that has completed was cancelled.

**Comment by newtonapple** [comment]
I think the problem is that in Ruby you don't really write straight to the stream.  The output stream is represented as an `Enumerator` instance, and all you can do is basically `yield` back the result.  If there were an exception thrown, it would happen after you had yielded the block back.  As far as I can tell, there isn't a clean way to detect if stream has been cancelled by the client on the server side.  I run into this problem because I was building a chat demo and wanted to garbage collect some of the lingering enumerators / queues that have been disconnected: https://github.com/newtonapple/Ruby-gRPC-Chatroom-Demo/blob/master/lib/chat/server.rb#L22.  

It'd be nice to have an explicit API to check on that server that a client's request has been cancelled instead relying on implicit writes to detect this condition.  What are your thoughts?

**Comment by murgatroid99** [comment]
Do you want to know if the client has cancelled the stream, or do you just want to know if the client stream has stopped for whatever reason. If the server-side read enumerator terminates, that means that the client has closed its side of the connection for writing. For a chat app, this may be enough to assume that the client has disconnected.

**Comment by newtonapple** [comment]
Basically, I want to know if a write connection has been disconnected (canceled, timeout, or closed). For the chat app, I actually have a Listen rpc that takes an empty request and returns a server-side stream, so there is no read stream I can pull from.  The client uses different rpc for sending messages. The server will then broadcast these messages to all the listening streams.  I want to know if a listen connection is down so I can GC all its lingering message queue.  

I think the fundamental problem is that, as far as I can tell, there isn't a clear way to detect a client disconnection on server-side.  I can imagine a scenario where a simple unary rpc, like the example shown, where the sever could run for a long time and client disconnects before the server finishes.  The server might want to know that and be able to cancel all future work.

**Comment by murgatroid99** [comment]
Why use two different streams? Why not just use a single bidirectional streaming RPC for both sending and receiving messages?

**Comment by newtonapple** [comment]
This is app is really a toy project for me to test out gRPC.  The spec was to require a session_id in order to post messages, but anyone can listen in. Here is the protobuf file if you're interested: https://github.com/newtonapple/Ruby-gRPC-Chatroom-Demo/blob/master/protos/chat.proto. But, like I said, I could imagine other scenarios where a being able to detect the disconnection would be important.

**Comment by apolcyn** [comment]
Without actively reading or writing on the call (enqueuing responses into a response stream enumerable achieves this), it doesn't look like the c-core provides any means of checking the state of a call in the way that's desired here.

But as is, even if actively making reads or writes on the call, the current `is_cancelled?` method looks broken.

One proposal: 

We could treat failed core batches (reads or writes) as indication that the call has been cancelled, 
This appears to be effectively done on the sync c++ server in it's server-side-context `IsCancelled` method (https://github.com/grpc/grpc/blob/master/src/cpp/server/server_context.cc#L180).
This wouldn't fix the example here, but I think it would make `is_cancelled?` more useful.

**Comment by muxi** [comment]
Any update?
