### ISSUE TITLE
Tests fail due to failed RPC with "UNAVAILABLE" code and "Endpoint read failed" details

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#10142]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/3481/testReport/junit/(root)/python_linux_dbg_native/py34_test_unit__metadata_code_details_test_MetadataCodeDetailsTest/

**Comment by nathanielmanistaatgoogle** [comment]
@dgquintas: from where does the text "Endpoint read failed" come? What might this test be doing wrong (with a simple request-unary response-streaming RPC) that could cause it to fail with status `UNAVAILABLE, Endpoint read failed`?

**Comment by dgquintas** [comment]
That'd happen if the peer went away during a read. What is the peer endpoint for this test? Is it running in-process or somewhere where we can guarantee its lifetime and good health?

**Comment by nathanielmanistaatgoogle** [comment]
@dgquintas: the peer endpoint for this test is [an in-process server and its lifetime and good health are guaranteed](https://github.com/grpc/grpc/blob/37bbbd770f3131cf5edbc1201d343320440897af/src/python/grpcio_tests/tests/unit/_metadata_code_details_test.py#L190).

**Comment by dgquintas** [comment]
Still happening: https://grpc-testing.appspot.com/job/gRPC_master_linux/2222/testReport/junit/(root)/python_linux_opt_native/py34_test_unit__metadata_code_details_test_MetadataCodeDetailsTest/

@ctiller any other ideas about @nathanielmanistaatgoogle 's question?

**Comment by nathanielmanistaatgoogle** [comment]
[Seen with the newly-introduced `_reconnect_test.ReconnectTest`. :-(](https://grpc-testing.appspot.com/job/gRPC_master_linux/2548/testReport/junit/(root)/python_linux_opt_native/py34_test_unit__reconnect_test_ReconnectTest/)

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [gRPC_master_linux #2540](https://grpc-testing.appspot.com/job/gRPC_master_linux/2540/testReport/junit/(root)/python_linux_dbg_native/py27_test_protoc_plugin_beta_python_plugin_test_PythonPluginTest/).

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller, @sreecha: any insights into the questions @dgquintas and I discussed here?

**Comment by ctiller** [comment]
GRPC_TRACE call_error would be tremendously useful here I expect.

If it actually is we should file a bug to expose that data in the status.

**Comment by dgquintas** [comment]
No failures since 2017-09-18. Closing.
