### ISSUE TITLE
AddPort is a Windows reserved name.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1015]
We can't compile grpc++ for Windows at the moment, because ServerBuilder::AddPort is causing an interesting issue. As it is the custom with Microsoft's API, any Windows API that takes a string as a parameter has two variants: one for Unicode, with the W suffix, and one for Ansi, with the A suffix. And the main name is a #define to the proper function.

AddPort is an API for Windows, and takes a string as an argument:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183342%28v=vs.85%29.aspx

So right now, the method name AddPort is being silently renamed to AddPortW by the preprocessor, which creates obvious compilation issues.

Now, there are several solutions for this, none of which pleases me. The least worse option in my opinion is to rename AddPort in grpc to something else. Suggestions ?

**Comment by ctiller** [comment]
Why do we need windows.h included by public headers?

Renaming our APIs whenever they conflict with Windows means we will forever
be doing so whenever ms adds an api, and I'd prefer to not even start down
that route.

**Comment by nicolasnoble** [comment]
That's the trick: we don't need windows.h included in public headers. So right now, it's not included in server_builder.h meaning that ServerBuilder::AddPort in that file is still called AddPort. But in server_builder.cc, we eventually end up including it because we need various types to be defined for tcp sockets or dns resolutions.

Long story short, the compilation error is this:

2>c:\work\grpc\src\cpp\server\server_builder.cc(54): error C2039: 'AddPortW' : is not a member of 'grpc::ServerBuilder'
2>          c:\work\grpc\include\grpc++\server_builder.h(52) : see declaration of 'grpc::ServerBuilder'

as server_builder.h declares AddPort, and server_builder.cc implements AddPortW.

**Comment by nicolasnoble** [comment]
Oh and, it also means that one of the solutions is to #include <windows.h> in the server_builder.h public header. Which is probably my least preferred option.

**Comment by nicolasnoble** [comment]
Last thing: we actually need to include windows.h in some public headers in grpc. See atm_win32.h for example.

**Comment by ctiller** [comment]
What if we made a header with:

#ifdef AddPort
#error
#endif

And provide an explanation of why its incredibly poor practice to #define
common names in public headers.

Or is there some argument for why Microsoft will never add another
conflicting api in a future api revision that will force all of our clients
on every platform to update their code?

**Comment by nicolasnoble** [comment]
I fail to see what that would actually solve ? Unless you haven't quite got what the issue is - but I'll discuss that below.

I mean, sure, it's a well known fact that Microsoft took on the wrong side of the Force when designing their API switch using #defines in their public headers, but if we want a Windows port, we have to live with that. Doing #include of Windows.h drags with it a plethora of #defines with very public names. But using public shaming here wouldn't actually suddenly make grpc++ compile under Windows, although it might improve my mood on the subject. Or maybe you didn't understand what the problem is: the crux of the issue is that server_builder.cc eventually ends up including windows.h because reasons, and is the one affected by the #define from windows.h. So it's not a matter of people including server_builder.h and suddenly having a polluted environment. It's the other way around: server_builder.cc is the one which eventually gets polluted.


Now, here's the list of things that happens exactly:

-) grpc and grpc++ public headers almost never include windows.h, except for atm_win32.h, for the interlocked functions definitions.
-) the implementation code however will very definitely end up including windows.h to implement windows things

And here's a list of potential solutions, classified in the order of worst to best in my opinion:

-) include windows.h everywhere so that any and all #define will be propagated everywhere, mitigating the issue. This is by far the worst solution of all.
-) doing #undef AddPort in server_builder.cc - bleargh.
-) using WIN32_LEAN_AND_MEAN - this might seem the best option, as it tells windows.h to not include the universe, and will reduce the potential number of conflicts, but this presents us with the new problem that if someone uses grpc++ as a public API and hasn't WIN32_LEAN_AND_MEAN and includes windows.h before including server_builder.h, he'll get the reversed issue: ServerBuilder in our .h file with be declared with AddPortW, but our implementation will go with AddPort. This is where your suggestion might work, where we can explain to people why they need to include server_builder.h before windows.h in their code, or use WIN32_LEAN_AND_MEAN, but is still not optimal, because they might not be able to if grpc is a dependency of a dependency. Also, WIN32_LEAN_AND_MEAN still means you'll get #defines, just fewer, so this isn't a silver bullet either.
-) renaming AddPort to something else.


In all cases, I don't think there's any guarantee that Microsoft will never add another conflicting API in the future, but unless I am missing your point, I don't see how this is something that could ever be dodged. We need to include windows.h in our implementations in order to get windows API in, and that means dragging with us unwanted #defines.

**Comment by ctiller** [comment]
So I understand the problem and the proposed potential solutions.

My main point is that we effectively have a binary choice:
- adapt our API's so that they never conflict with Windows API's
OR
- avoid the pitfalls in our code and provide clear explanations when code is used in an incompatible way

The first option I see as a recipe for disaster: I expect the majority of our users to be on Linux or Mac, and I don't want to introduce a policy of breaking their code if Microsoft adds to their API's in the future.

The second (my preferred) would mean some combination of your other proposed solutions:
- I think avoiding atm_win32.h is completely possible in the C++ code is plausible, so I don't see this as a blocker
- Our C namespacing ought to avoid conflicts with windows API's forever, so I think windows.h in a file that's only included from C code should be ok (but not great)
- WIN32_LEAN_AND_MEAN defined in a .cc file should be kosher for the few times we'll have problems

Providing a header explaining the problem and providing a clear reason for what's going on helps us catch problems early without opaque link time errors - it's not about public shaming.

I don't think it's unreasonable to take the stance that our portable API's defined in C++ can't be mixed with Windows system headers due to hygiene issues in the latter.

**Comment by nicolasnoble** [comment]
And I have an opposite opinion: I DO think it's unreasonable to request that the C++ API can't be mixed with Windows system headers. This makes for really poor integration experience for people. More specifically, what does that actually mean for people trying to use our C++ interface in a Windows piece of code ? Best-case scenario, they'll have to change their software to add WIN32_LEAN_AND_MEAN. We might be able to guide them towards that direction using your proposal, but that wouldn't cover all cases. Worst-case scenario they'll have to create an interface to our interface.

Imagine for example that in a single source file, people want to use grpc++ and another third party library. That other third party library might require to have windows.h without WIN32_LEAN_AND_MEAN, because it wasn't designed the same way as ours. Granted, that hypothetical third party library wouldn't be designed in a nice way, but that's not something either we or the people trying to integrate both libraries can control. At that point, this is integration hell because of our policy, and we'll prevent people from using grpc together with something else.

Here is a real world example to expose what that hypothetical third party library would be: somebody writes a software under Linux. He uses grpc++. He also uses pthreads, because he didn't notice that we implement gpr_threads, or because he wants to use something we don't currently provide, such as pthread_key. Now having done his software under Linux, and being successful at it, he wishes to port it under Windows. He doesn't want to change his threads layer, and simply chooses to use pthreads-win32. Now pthread.h from the pthreads-win32 project includes windows.h. Integration hell right there. And I found this one on my first try - I'm sure more win32 ports of gnu software would do the same thing. And this is a worse example, because this would be the scenario of someone who wrote a candid Linux software, simply willing to try to compile it for Windows; he wouldn't even be a Windows expert. Yet solving grpc "no windows headers" policy vs pthreads-win32's pthread.h would require some understanding of what's going on with Windows.

My point here being that this policy means that people trying to integrate grpc inside their Windows software using our windows-specific visual studio projects and implementation (aka, something that has been explicitly designed for it) will have a harder time than Linux or Mac people.


Now, I completely agree with you that future collisions with Microsoft new API is indeed a risk, and that'll fill me with rage if it ever happens. And for this I'd be more than happy to provide workarounds to Windows users such as what you suggested until such time we can benefit from a grpc version bump that'd do other API breakage. But I do believe this a risk worth taking if we want to ensure a smooth integration experience for our Windows users, or people trying to create cross platform softwares.

**Comment by nicolasnoble** [comment]
And I just realized, even without talking about third party APIs, and keep things strictly within grpc world, that still doesn't work. This code would fail the "don't mix windows headers with grpc++" test, if somebody wanted to use our public atm.h header:

```
#include <grpc++/server_builder.h>
#include <grpc/support/atm.h>
```

**Comment by ctiller** [comment]
Use the c++ atomics for c++ code.

Can I summarize our positions as:

You think Windows integration trumps all, and if something doesn't fit
perfectly in that world we must change it.

I think Windows will be a marginal enough platform for us that, while we
should support it, having a few restrictions will be OK - especially if it
gives a more stable API for other platforms.

**Comment by ctiller** [comment]
Or more succinctly:

When porting, should we prefer public API stability or ease of integration
with the target platform?

**Comment by vjpai** [comment]
I'm siding with Nico here as a one-off measure while we're still in Alpha stage to enable a quicker path to a Windows port and to increase the number of gRPC Windows users. I think it's worthwhile.

**Comment by nicolasnoble** [comment]
Re the summarize of positions: I really do not believe that what you're talking about is "a few restrictions". It's basically "yes, grpc can compile under Windows, but you can't use it in conjunction with any other windows project, even our own public GPR API", which is just crazy.

**Comment by nicolasnoble** [comment]
And to precise my position, what I am advocating for is that, right now, as we're still doing API-breaking changes, we should take the chance to do that one too. If, when we're stable, Microsoft commits a new API such that would add a similar conflict with our API, I'd be more than happy to create a #error that would go along the lines of "We tried, but Microsoft broke our API, and we're not going to affect everyone because of this, so, sorry but you can't have nice things.".

But as of today, it feels really like a poor decision to prevent people to have nice things just because we didn't want to rename one API function while other [API-breaking changes](https://github.com/grpc/grpc/pull/835) are still hot from the press.

**Comment by vjpai** [comment]
Yes, and getting Windows users to adopt now will also decrease the likelihood of the error situation that Nico references coming down the pipe. It's a win-win situation.
