### ISSUE TITLE
Cannot compile grpc v1.0.0 in ubuntu 14.04

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#10167]
I am trying to compile grpc 1.0 in a machine which installed grpc 1.0 before. But finally failed as following.

[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTCXX] Compiling src/compiler/csharp_plugin.cc
[HOSTCXX] Compiling src/compiler/node_plugin.cc
[HOSTCXX] Compiling src/compiler/objective_c_plugin.cc
[HOSTCXX] Compiling src/compiler/python_plugin.cc
[HOSTCXX] Compiling src/compiler/ruby_plugin.cc
[LD]      Linking grpc-release-v1.0.0/libs/opt/libgrpc.so.1.0.0
[LD]      Linking grpc-release-v1.0.0/libs/opt/libgrpc_cronet.so.1.0.0
[AR]      Creating grpc-release-v1.0.0/libs/opt/libgrpc.a
[AR]      Creating grpc-release-v1.0.0/libs/opt/libgrpc_cronet.a
[HOSTLD]  Linking grpc-release-v1.0.0/bins/opt/grpc_csharp_plugin
/usr/bin/ld: cannot find -lprotobuf
collect2: error: ld returned 1 exit status
[HOSTLD]  Linking grpc-release-v1.0.0/bins/opt/grpc_node_plugin
make: *** [grpc-release-v1.0.0/bins/opt/grpc_csharp_plugin] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lprotobuf
collect2: error: ld returned 1 exit status

I want to ask: how to uninstall the previous grpc and how can I make my new compiling work?

**Comment by aaronjheng** [comment]
For now, You can only do it manually.

**Comment by aaronjheng** [comment]
#10089
