### ISSUE TITLE
Large RPCs broken

### ISSUE THREAD

**Issue by jhseu** [grpc/grpc#10161]
Leaving as a tracking issue for us on TensorFlow. Currently blocking our upgrade.

See:
https://github.com/grpc/grpc/pull/9826
https://github.com/tensorflow/tensorflow/pull/7466

**Comment by vjpai** [comment]
@nicolasnoble  can you advise on how to debug this? This issue is blocking TF's upgrade from a 1.0.x version to master . It is only arising on Windows - Linux and Mac work fine there.

**Comment by vjpai** [comment]
@jhseu - can you give a specific test or command line that helps us repro this?  I understand that this issue is only on Windows at this point but that it's still critical and user-facing.

**Comment by jhseu** [comment]
@vjpai Getting TensorFlow compiling on Windows is actually a pretty significant effort. Perhaps a better starting point is to try your large RPC test on Windows? Let me know if you have trouble reproducing it and we can make a VM somewhere to share.

**Comment by vjpai** [comment]
Here's a few things that I'd like to suggest pursuing based on discussions with @jhseu, @nicolasnoble, and own debugging ideas:

* Windows issues are likely to come from 32-bit platform ; likely that there is some int that should be a size_t that other platforms paper over for us
* Questionable whether this is coming from core or C++ layer, so we should at least have tests of 2 GB messages at both layers. In this case #9826 may not be enough to go on.
* We should try this with progressively larger message sizes until we find the spot where the Windows test fails but the Mac and Linux continue to pass

**Comment by byronyi** [comment]
Any updates?

**Comment by vjpai** [comment]
Hi there, expect an update on this next week. We'll let you know.

**Comment by vrv** [comment]
Friendly ping since this is blocking https://github.com/tensorflow/tensorflow/pull/7466

**Comment by vjpai** [comment]
Hi there, I am waiting for a response on this from @jhseu - I believe that the Windows large message bug no longer exists (and was never Windows-specific) and have asked for confirmation. tensorflow/tensorflow#11490 included a bug fix that had been at gRPC master for months but was not pulled into the TensorFlow customized SerializationTraits.

**Comment by jtattermusch** [comment]
Fine to close this?

**Comment by vjpai** [comment]
Yes, this was fixed.
