### ISSUE TITLE
WORKSPACE bind conflicts

### ISSUE THREAD

**Issue by zoukyle** [grpc/grpc#10162]
My project depends on grpc_git and it has its own WORKSPACE file. Here is the dependency:
```
git_repository(
    name = "grpc_git",
    remote = "https://github.com/grpc/grpc.git",
    commit = "ff007575de26334b2b3a110bafeef64ac5477944",
    init_submodules = 1,
)
```

I got the error: 
```
ERROR: /home/liangzou/.cache/bazel/_bazel_liangzou/766790ddbe8cf965fa78098dbd133c63/external/grpc_git/BUILD:1280:1: no such target '//external:protobuf': target 'protobuf' not declared in package 'external' (did you mean 'protobuf_js'?) defined by /home/liangzou/gitreview/deepmap/WORKSPACE and referenced by '@grpc_git//:grpc++_config_proto'.
ERROR: Analysis of target '//experimental/examples/grpc:greeter_async_server' failed; build aborted.
```
This is caused by the WORKSPACE conflicts between my project and the WORKSPACE in grpc git.

**Comment by zoukyle** [comment]
It seems bazel can only use the WORKSPACE file from the root directory, so there should be no WORKSPACE bind conflicts. I need to add the missing binds to my own project's WORKSPACE file.

**Comment by nicolasnoble** [comment]
Closing, per OP comment - each project working with Bazel indeed needs its own WORKSPACE.
