### ISSUE TITLE
GRPC supresses errors when binding server ports

### ISSUE THREAD

**Issue by mrapavy** [grpc/grpc#10168]
I am using GRPC/C# wrapper and whenever there's a problem with port binding or SSL certificates the C# wrapper (and also the C core library) doesn't propagate the error (https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.c#L96) to the client code. It only logs the error.

It's very difficult to react on grpc-related errors in my application. Is there a plan to fix this?

**Comment by jtattermusch** [comment]
It looks like this is a general C core issue rather than C# specific.

**Comment by muxi** [comment]
Any update?

**Comment by juanjoDiaz** [comment]
Having the same issue on C++.

**Comment by luomavaltteri** [comment]
Yup, C++ here also. Doesn't throw error if port is already taken when building server.

**Comment by cuadue** [comment]
This is just a documentation problem. The port is indeed populated, just after the call to e.g. BuildAndStart().

My suggestion is that the documentation could change from:

    selected_port[out]	If not nullptr, gets populated with the port number bound to the grpc::Server for the corresponding endpoint after it is successfully bound, 0 otherwise.

to

    selected_port[out]	If not nullptr, gets populated with the port number bound to the grpc::Server for the corresponding endpoint after it is successfully bound *by BuildAndStart()*, 0 otherwise. AddListeningPort does not modify this pointer.

**Comment by hcaseyal** [comment]
@cuadue Thanks for the documentation suggestion. #15740 will fix the documentation.

@mrapavy @juanjoDiaz @luomavaltteri As demonstrated in cuadue's code snippet, you can check for the port-binding error after calling BuildAndStart(). I'm closing the issue for now, please re-open if anything is still unclear.

**Comment by juanjoDiaz** [comment]
Thanks for the follow-up!

@hcaseyal I actually switch to C# recently and it has the same problem. How could I do the check on C#?

**Comment by hcaseyal** [comment]
@juanjoDiaz Adding in someone who is more familiar with C# into the conversation, @jtattermusch
