### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xunonxyz** [grpc/grpc#10178]
1>------ 已启动生成: 项目: grpc_dll, 配置: Release Win32 ------
1>grpc.def : error LNK2001: 无法解析的外部符号 census_set_trace_mask
1>grpc.def : error LNK2001: 无法解析的外部符号 census_trace_mask
1>grpc.def : error LNK2001: 无法解析的外部符号 census_trace_print
1>grpc.def : error LNK2001: 无法解析的外部符号 grpc_slice_buf_cmp
1>F:\grpc\vsprojects\Release\grpc_dll.lib : fatal error LNK1120: 4 个无法解析的外部命令
========== 生成: 成功 0 个，失败 1 个，最新 2 个，跳过 0 个 ==========

**Comment by baibaichen** [comment]
@nicolasnoble  where are those 4 methods? Are they generated on the fly?

Thanks

**Comment by fjcalzado** [comment]
Have the same link errors, tested in 1.2.3 and also 1.2.0. There is no definition for those methods. just declaration with no implementation.

**Comment by fjcalzado** [comment]
It seems that those 4 methods aren't called anywhere, so I just commented their export declaration in `grpc.def`file:
```
;census_trace_mask
;census_set_trace_mask
;census_trace_print
;grpc_slice_buf_cmp
```

**Comment by nicolasnoble** [comment]
This one was fixed a long while ago.
