### ISSUE TITLE
FLAKE: c++_linux_dbg_native.bins/dbg/end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.HugeResponse/0 GRPC_POLL_STRATEGY=epoll

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#10198]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/3641/testReport/junit/(root)/c++_linux_dbg_native/bins_dbg_end2end_test___gtest_filter_ProxyEnd2end_ProxyEnd2endTest_HugeResponse_0__GRPC_POLL_STRATEGY_epoll/

Error Message

Failure
Standard Output

D0316 20:00:42.254658120     731 test_config.c:393]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0316 20:00:42.254875608     731 ev_epoll_linux.c:93]        epoll engine will be using signal: 40
D0316 20:00:42.254895095     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255019435     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255093122     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255159198     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255221989     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255295280     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255360230     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255422244     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255484242     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255549592     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255645376     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255722686     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255794115     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255860289     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255923434     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.255986918     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256048939     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256136612     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256212888     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256298833     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256365034     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256427747     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256491405     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256592038     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256663919     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256751439     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256830804     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256898171     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.256961624     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257026145     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257132855     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257250727     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257380909     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257508941     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257632535     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257762478     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.257899438     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.258038294     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.258169038     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.258301442     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.258425627     731 ev_posix.c:107]             Using polling engine: epoll
D0316 20:00:42.258680684     731 ev_posix.c:107]             Using polling engine: epoll
Note: Google Test filter = ProxyEnd2end/ProxyEnd2endTest.HugeResponse/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.HugeResponse/0
D0316 20:00:42.259135982     731 end2end_test.cc:230]        TestScenario{use_proxy=false, credentials='ssl'}
D0316 20:00:42.259193283     731 ev_posix.c:107]             Using polling engine: epoll
I0316 20:00:42.261837994     731 server_builder.cc:247]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 10
D0316 20:00:42.261908225     731 ev_posix.c:107]             Using polling engine: epoll
E0316 20:00:42.379348382     731 sync_posix.c:66]            assertion failed: pthread_mutex_unlock(mu) == 0

**Comment by dgquintas** [comment]
Not seen in quite a while, closing.
