### ISSUE TITLE
cloud_to_prod tests failing

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#10192]
Most `cloud_to_prod` and `cloud_to_prod_auth` interop tests are currently failing: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/12318/#showFailuresLink and https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/12317/#showFailuresLink. 

They also fail when run locally from a clean client.

**Comment by ncteisen** [comment]
The server went back down (twice...). It's back now.

I am going to look into why it crashed after I restarted it the first time.

**Comment by ncteisen** [comment]
And it has crashed again. Going to reopen.

**Comment by adelez** [comment]
There was crash in grpc. I suspect it was due to a non-clean build of ESF. The job seems stable now. Will check the next build.

**Comment by adelez** [comment]
The issue's gone.
