### ISSUE TITLE
ubuntu 12.04系统运行grpc-common/python/helloworld的run_client.sh报错

### ISSUE THREAD

**Issue by namilantu** [grpc/grpc#1020]
I run the python example in grpc-common/helloword. While I run run_client.sh, a mistace happended.
details are seen below.
sunlu@sunlu-HP-Pro-3085-Microtower-PC:~/grpc-common/python/helloworld$ ./run_client.sh
Traceback (most recent call last):
  File "greeter_client.py", line 44, in <module>
    run()
  File "greeter_client.py", line 39, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/home/sunlu/github/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/early_adopter/_reexport.py", line 158, in __call__
    self._underlying, request, timeout)
  File "/home/sunlu/github/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/early_adopter/_reexport.py", line 113, in _call_reexporting_errors
    raise _reexport_error(e)
grpc.early_adopter.exceptions.ExpirationError
D0312 16:21:21.411179408    2550 iomgr.c:107] Waiting for 1 iomgr objects to be destroyed
E0312 16:21:21.431823160    2551 tcp_client_posix.c:145] socket error: connection refused
D0312 16:21:21.531838928    2550 iomgr.c:107] Waiting for 0 iomgr objects to be destroyed and executing final callbacks

**Comment by namilantu** [comment]
Maybe , the server is actually not running although I run ./run_server.sh, how I can judge whether the server is running in ubuntu 12.04.05

**Comment by namilantu** [comment]
who can help me?

**Comment by nathanielmanistaatgoogle** [comment]
What is the output of your run_server.sh command?

**Comment by namilantu** [comment]
have no output , just a cursor

**Comment by vnitinv** [comment]
@namilantu you will find _TIMEOUT_SECONDS = 10 in greeter_client.py. Increase the value to some higher limit. This will solve the issue. 
Hope that helps!!
