### ISSUE TITLE
Cannot build grpc for C++ on MacOS from HEAD

### ISSUE THREAD

**Issue by realenginerd** [grpc/grpc#10209]
Note: This is the same problem as #8759, though with different causes.

I'm trying to install grpc for C++ on MacOS following instructions on https://github.com/grpc/grpc/blob/master/INSTALL.md, but I keep getting stuck at the `make` step:

```
 $ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init
 $ make
 $ [sudo] make install
```

Every time I run `make`, I get an Error 1 with the following message:
```
mkemac-oscar:grpc oscar_g$ make 
[MAKE]    Generating /Users/oscar_g/git/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /Users/oscar_g/git/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
[C]       Compiling third_party/zlib/crc32.c
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzclose.c
[C]       Compiling third_party/zlib/gzlib.c
[C]       Compiling third_party/zlib/gzread.c
[C]       Compiling third_party/zlib/gzwrite.c
[C]       Compiling third_party/zlib/infback.c
[C]       Compiling third_party/zlib/inffast.c
[C]       Compiling third_party/zlib/inflate.c
[C]       Compiling third_party/zlib/inftrees.c
[C]       Compiling third_party/zlib/trees.c
[C]       Compiling third_party/zlib/uncompr.c
[C]       Compiling third_party/zlib/zutil.c
[AR]      Creating /Users/oscar_g/git/grpc/libs/opt/libz.a
libtool: unrecognized option `-o_warning_for_no_symbols'
libtool: Try `libtool --help' for more information.
make: *** [/Users/oscar_g/git/grpc/libs/opt/libz.a] Error 1
```

I'm not sure if grpc has a minimum version requirement for libtool for MacOS; if there is one, I didn't see it. I have 2.4.2 installed:
```
mkemac-oscar:grpc oscar_g$ which libtool
/usr/local/bin/libtool
mkemac-oscar:grpc oscar_g$ libtool --version
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Any ideas? Am I missing anything?

**Comment by mehrdada** [comment]
The build instructions have since been updated (specifically try installing `libtool` from `brew` and use `LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make` on a clean clone). Let us know if you are still experiencing the issues.

**Comment by mehrdada** [comment]
@DimitarQlik  I just started from a clean clone of gRPC master on High Sierra and ran it without issues, with the same `libtool` version (from `brew`):

```
cd `mktemp -d`
git clone https://github.com/grpc/grpc --recursive
cd grpc
LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make -j10
```

**Comment by realenginerd** [comment]
@mehrdada I started from a clean clone of gRPC master on Sierra (10.12), but unfortunately I still get the same error message, just like @DimitarQlik : 
```
[AR]      Creating /Users/oscar_g/git/grpc/libs/opt/libares.a
libtool: unrecognized option `-o_warning_for_no_symbols'
libtool: Try `libtool --help' for more information.
make: *** [/Users/oscar_g/git/grpc/libs/opt/libares.a] Error 1
make: *** Waiting for unfinished jobs....
Can't exec "glibtoolize": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN2> line 6.
autoreconf: failed to run glibtoolize: No such file or directory
autoreconf: libtoolize is needed because this package uses Libtool
make: *** [third_party/protobuf/configure] Error 1
```

I've satisfied pretty much all prerequisites listed on the Install page, so I'm not sure what I'm missing. How can I help pin down the issue? Let me know if I can help; I would really love to use gRPC but this is still a blocker.

**Comment by mehrdada** [comment]
@realenginerd can you invoke `glibtoolize` manually? I.e. it in your `PATH`?

**Comment by realenginerd** [comment]
@mehrdada it wasn't at that time, but I've since done `brew install libtool`. However, I am still stuck at the same spot, albeit with a different message now:
```
libtool: unrecognized option `-o_warning_for_no_symbols'
libtool: Try `libtool --help' for more information.
make: *** [/Users/oscar_g/git/grpc/libs/opt/libares.a] Error 1
make: *** Waiting for unfinished jobs....
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:66: installing './ar-lib'
configure.ac:61: installing './compile'
configure.ac:46: installing './config.guess'
configure.ac:46: installing './config.sub'
configure.ac:48: installing './install-sh'
configure.ac:48: installing './missing'
benchmarks/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
mkemac-oscar:grpc oscar_g$ echo $?
2
```

Ideas?

**Comment by mehrdada** [comment]
Can you clean it before retrying?

**Comment by realenginerd** [comment]
OK, running `make clean` has got me past this specific error. (I still can't get `grpc` to build successfully, but I think that's a different issue.) Suggest adding `clean` to the instructions?

**Comment by mehrdada** [comment]
@realenginerd I believe `clean` was only necessary because Apple's `libtool` was used prior to `glibtool` on the same tree and that left some artifacts around polluting the tree. I don't believe `make clean` is necessary if you are checking out the repo from scratch, so it probably does not make sense to add it to instructions.

**Comment by mattieruth** [comment]
I am running on Mac OS X 10.13.4 and am also getting these errors. I have tried all the tricks above with `make clean` and using the LIBTOOL/LIBTOOLIZE environment variables. I even tried removing the clone and starting fresh, but still after running:

```
$ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
$ cd grpc/
$ git submodule update --init
$ LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make
```

I get:
```
libtool: unrecognized option `-o_warning_for_no_symbols'
libtool: Try `libtool --help' for more information.
```

I have also tried updating all my brew.  `glibtoolize --version` and `glibtool --version` report 2.4.6 and `which glibtool` / `which glibtoolize` give me `/usr/local/bin` which in turn point to brew's Cellar location.

Anything else I should be trying?

**Comment by DemarestTech** [comment]
Hi -- in the Makefile I changed the line assigning the archiver `AR = libtool blah...` to the standard `ar -r` so now my line 272 reads 
`AR = ar -r`
I was able to successfully build that way

**Comment by mattieruth** [comment]
Thanks. I'll try that next time. I finally figured out that I had an unrelated set of packages installed with their own libtool which was getting in the way even after exporting libtool variables and forcefully setting PATH. I'm still unclear as to how it was inserting itself back in at compile time but moving it aside fixed the issue.
