### ISSUE TITLE
php: annotations.proto and `\GPBMetadata\Google\Protobuf\Descriptor` path

### ISSUE THREAD

**Issue by flisky** [grpc/grpc#10217]
`protoc -I../vendor/github.com/googleapis/googleapis/ --php_out=. --grpc_out=. --plugin=protoc-gen-grpc=.../grpc_php_plugin ../vendor/github.com/googleapis/googleapis/google/api/annotations.proto`

It throws `PHP Fatal error:  Uncaught Error: Class 'GPBMetadata\Google\Protobuf\Descriptor' not found`

Should use "GPBMetadata\Google\Protobuf\ **Internal\\** Descriptor" instead.

**Comment by stanley-cheung** [comment]
Is this actually a protobuf question? Why do you need `--grpc_out=. --plugin=protoc-gen-grpc=.../grpc_php_plugin` for `annotations.proto` with no service definition? What version of protoc are you using?

**Comment by flisky** [comment]
protoc: libprotoc 3.2.0
grpc_php_plugin: v1.1.3-1425-g40a947ef9

My backend is grpc-go based, and I'm using grpc-gateway to proxy http request.
The grpc-gateway needs `annotations.proto`, but I don't know where to get a predefined one for php, so I try to generate it by myself.

Any suggestion? Thanks,

**Comment by stanley-cheung** [comment]
You shouldn't need the `--grpc_out=. --plugin=protoc-gen-grpc=.../grpc_php_plugin` part to generate messages for `annotations.proto`.

**Comment by flisky** [comment]
Sorry, I don't get it. I have tried `protoc -I... annotations.proto`, and still get the same result.

In `\GPBMetadata\Google\Api\Annotations::initOnce();`, it calls `\GPBMetadata\Google\Protobuf\Descriptor::initOnce();`

I try to generate message for `google/protobuf/descriptor.proto`, and it fails with `Can only generate PHP code for proto3 .proto files.`

I find that `GPBMetadata\Google\Protobuf\Internal\Descriptor` is generated from `google/protobuf/descriptor.proto`, so I think it may be a namespace inconsistent.

Am I misunderstanding anythings? Thanks,

**Comment by stanley-cheung** [comment]
Then this is a google/protobuf issue. Please log an issue there.
