### ISSUE TITLE
Ruby - https without certificates

### ISSUE THREAD

**Issue by davissp14** [grpc/grpc#10226]
Having trouble trying to figure out how we would use an https url without specifying certificates.  We are using letsencrypt and outside of needing to specify the TLS ServerName, there's no need for certificates on the client side.  

Is there a way to achieve this, and how would I go about specifying the ServerName?

**Comment by apolcyn** [comment]
cc @murgatroid99

**Comment by apolcyn** [comment]
It looks like what you want here is just to use default ssl credentials upon creating the stub, using default certs? (see http://www.grpc.io/docs/guides/auth.html#ruby for example code - to load the default credentials, without supplying a roots file, you could instantiate `GRPC::Core::Credentials.new` without any arguments)

**Comment by davissp14** [comment]
How would I specify the TLS ServerName along with this?

**Comment by apolcyn** [comment]
I think what's needed here is the "server_host_override" param. Is this for testing?

You could specify the override server name as a "channel arg", passed to the stub.

E.g.:

`YourStub.new("target", creds, <channel arg hash>`, where the channel arg hash has the key-value pair of `GRPC::Core::Channel::SSL_TARGET => <host_override>`

there's some example usage of this in the interop tests (https://github.com/grpc/grpc/blob/master/src/ruby/pb/test/client.rb#L130)

**Comment by apolcyn** [comment]
btw there's more documentation on this and other channel args (which can be specified in ruby through a the optional channel arg hash to stubs and channels) in https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L230

**Comment by davissp14** [comment]
Oh perfect!  There's currently no etcd v3 driver, so I am in the process of writing one up.  I've been able to work against a local etcd just fine, but once I started trying connecting to a remote db using https, all of my requests have just been hanging indefinitely.  My assumption was that it was SNI related. I'll give this a shot in the morning and give an update. 

Thanks!

**Comment by murgatroid99** [comment]
I would like to emphasize that the server host override should rarely be used for anything other than testing. Normally, it will just verify against the name you tried to connect to (the channel target), and this should usually be the correct thing to do.

**Comment by jboeuf** [comment]
@murgatroid99 
+1 Please don't use the override in a production system.

**Comment by davissp14** [comment]
Sounds good, looks like I won't need to do this anyways.  I appreciate the
help!

**Comment by davissp14** [comment]
It appears the issue actually revolves around the following: 

> D0328 14:11:08.061345337   26751 security_handshaker.c:126]  Security handshake failed: {"created":"@1490728268.061305678","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/transport/security_connector.c","file_line":590}
> I0328 14:11:08.061624974   26751 subchannel.c:705]           Connect failed: {"created":"@1490728268.061305678","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/transport/security_connector.c","file_line":590}
> I0328 14:11:08.061688623   26751 subchannel.c:503]           Retry in 19.800812520 seconds

**Comment by jboeuf** [comment]
What is your server? It looks like it does not support http2.

**Comment by davissp14** [comment]
It's a Etcd v3 (gRPC) cluster fronted with an Haproxy.  
https://github.com/coreos/etcd

I am able run commands against the cluster just fine using the etcdctl command line utility.

**Comment by jboeuf** [comment]
Is Haproxy terminating the TLS session?

**Comment by davissp14** [comment]
That is correct

**Comment by jboeuf** [comment]
Looks like you're not the only one who has this problem:
http://serverfault.com/questions/823416/haproxy-not-working-with-alpn/823420

I'm not an haproxy specialist but basically, you have somehow to configure
haproxy so that it will advertise "h2" as a list of protocols supported in
alpn during the TLS handshake.

**Comment by davissp14** [comment]
We figured it out! 

We needed to update our OpenSSL version from 1.0.1X to 1.0.2g and rebuild Haproxy.  After this we were able to successfully enable the TLS extensions. 

Thanks for your help!  This can be closed!

**Comment by jboeuf** [comment]
Excellent. Thanks for letting us know!

**Comment by cdelguercio** [comment]
Hmmm @apolcyn, your solution doesn't seem to be working for me.

My Ruby code fails:
```
stub_opts = {
      channel_args: {
        GRPC::Core::Channel::SSL_TARGET => "something.com"
      }
    }
    stub = A17::Api::AuthService::AuthService::Stub.new("something.com:80", GRPC::Core::ChannelCredentials.new(), **stub_opts)
```

While my Go code succeeds:
```
opts = append(opts, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")))
conn, err := grpc.Dial("something.com:80", opts...)
```

I am terminating TLS using Envoy in front proxy mode.

**Comment by apolcyn** [comment]
@cdelguercio can you please add more details about how your snippet is failing? Also, I'm not sure if the server's roots are getting provided anywhere. I might take a look at https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_channel_credentials.c#L128 and https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L145 for some documentation on ruby channel credentials, and  https://github.com/grpc/grpc/blob/master/src/ruby/pb/test/client.rb#L112 for an example. But also please keep in mind the warnings about using the `SSL_TARGET` override option as noted above.

**Comment by cdelguercio** [comment]
I'm using TLS a little differently that a lot of the TLS examples, because on the server side, I'm not terminating at the gRPC layer, instead I'm terminating at a proxy load balancer similar to how a REST application might go over HTTPS. What's notable in the Go example is that I'm not supplying any certificate information to the gRPC client. I'm not sure what this does internally, but I do know that the goal is to find the Ruby analogue.

I get this error:
```
/var/lib/gems/2.3.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Connect Failed (GRPC::Unavailable)
```

**Comment by muxi** [comment]
@apolcyn any update?
