### ISSUE TITLE
PHP grpc extension fails to make grpc-1.2.0

### ISSUE THREAD

**Issue by yzaptx** [grpc/grpc#10233]
/bin/sh /home/yangzheng/grpc-1.1.0/libtool --mode=compile gcc -Wall -Werror     -Wno-parentheses-equality -Wno-unused-value -std=c11     -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/home/yangzheng/grpc-1.1.0 -DPHP_ATOM_INC -I/home/yangzheng/grpc-1.1.0/include -I/home/yangzheng/grpc-1.1.0/main -I/home/yangzheng/grpc-1.1.0 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -I/home/yangzheng/grpc-1.1.0/include -I/home/yangzheng/grpc-1.1.0/src/php/ext/grpc -I/home/yangzheng/grpc-1.1.0/third_party/boringssl/include  -DHAVE_CONFIG_H  -g -O2   -c /home/yangzheng/grpc-1.1.0/src/php/ext/grpc/byte_buffer.c -o src/php/ext/grpc/byte_buffer.lo 
mkdir src/php/ext/grpc/.libs
 gcc -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/home/yangzheng/grpc-1.1.0 -DPHP_ATOM_INC -I/home/yangzheng/grpc-1.1.0/include -I/home/yangzheng/grpc-1.1.0/main -I/home/yangzheng/grpc-1.1.0 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -I/home/yangzheng/grpc-1.1.0/include -I/home/yangzheng/grpc-1.1.0/src/php/ext/grpc -I/home/yangzheng/grpc-1.1.0/third_party/boringssl/include -DHAVE_CONFIG_H -g -O2 -c /home/yangzheng/grpc-1.1.0/src/php/ext/grpc/byte_buffer.c  -fPIC -DPIC -o src/php/ext/grpc/.libs/byte_buffer.o
cc1: error: unrecognized command line option "-Wno-parentheses-equality"
cc1: error: unrecognized command line option "-std=c11"
make: *** [src/php/ext/grpc/byte_buffer.lo] Error 1

**Comment by stanley-cheung** [comment]
Can you give us more information on the version of your OS, gcc, etc?

**Comment by yzaptx** [comment]
@stanley-cheung ok os: CentOS release 5.5 (Final)
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)

**Comment by stanley-cheung** [comment]
For CentOS 6 or before, you might have to follow the instructions [here](https://github.com/grpc/grpc/tree/master/src/php#quick-install) to compile the PHP gRPC Extension from source at the moment. And even that, you might have to upgrade your gcc version before you will be able to do that.

**Comment by yzaptx** [comment]
THX

**Comment by chensunny** [comment]
https://github.com/grpc/grpc/issues/10250

**Comment by stanley-cheung** [comment]
Folding this into #10580
