### ISSUE TITLE
Client sends its own initiated stream ID in GOAWAY last-stream-id

### ISSUE THREAD

**Issue by tatsuhiro-t** [grpc/grpc#1024]
last-stream-id of GOAWAY frame should be the peer-initiated stream ID, not its own.
But currently gRPC client, at least built from grpc-common hello world cpp sample, sends GOAWAY with last-stream-id=1, which is client-initiated stream.

https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.8 says
 ```
  There is an inherent race condition between an endpoint starting new
   streams and the remote sending a GOAWAY frame.  To deal with this
   case, the GOAWAY contains the stream identifier of the last peer-
   initiated stream which was or might be processed on the sending
   endpoint in this connection.  For instance, if the server sends a
   GOAWAY frame, the identified stream is the highest numbered stream
   initiated by the client.
```

So, since we don't have server pushed streams, client should send GOAWAY last-stream-id=0 in this case.

**Comment by murgatroid99** [comment]
It looks like that pull request fixed this problem.
