### ISSUE TITLE
"Can't define which status to set" Jenkins configuration problem

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#10266]
Seen since yesterday for me for at least [`gRPC_portability_pull_requests_linux`](https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/3875/) and [`gRPC_pull_requests_asan_c`](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/3042/).

**Comment by matt-kwong** [comment]
In #10255, I see the this at the top of the console log in the jobs with issues:   
```
GitHub pull request #10255 of commit 2f390dbb026b2e8a3b64e9273b2ade3f8af66585, has merge conflicts.
!!! PR mergeability status has changed !!!  
PR now has NO merge conflicts
Setting status of 2f390dbb026b2e8a3b64e9273b2ade3f8af66585 to PENDING with url https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/3875/ and message: 'Build started sha1 is original commit.'
```

**Comment by jtattermusch** [comment]
Haven't seen this since Mar 23, closing.
