### ISSUE TITLE
source compilation error related to boringssl?

### ISSUE THREAD

**Issue by glloydNAT** [grpc/grpc#10274]
I am having an issue compiling from source (either git clone or tarball download from repository). I caught dependency warnings related to zlib so installed zlib separately from source, only to find gcc then erroring out with a warning in the third_party/boringssl/crypto/directory_posix.c file (that the readdir_r function is deprecated).  Running "make -i" leads to recipe failure in the boringssl target, and what appear to be downstream (cascading) failure in the libgrpc_cronet.so.1.0.0 and libgrpc++.so.1.0.0 files, and then various cpp errors in the cpp reflection object files, finally appearing to complete, albeit with significant errors. 

Running "make run_dep_checks" errors out in the compilation of test/build/perftools.c ("gperftools/profiler.h: No such file or directory"), then goes on to pass the remaining pkg-config tests.

get gperftools from source, /.autogen.sh, /.configure, make, sudo make install...

rerun "make run_dep_checks"... now passes all tests.

"make" still errors out on the boringssl compilation, "make -i" the same behavior as above.

 "make install" fails out on the boringssl warnings, and "make -i install" completes, but with numerous errors... i don't know if it's usable, but I have doubts.

the boringssl module requires cmake... which, having now installed and having attempted to compile using the instructions contained in the boringssl/build.md file.  Following the "cmake .." operation, the "make" still errors out on the "readdir_r is deprecated" warning.  Ignoring warnings, make still results in boringssl/crypto/directory_posix.o recipe failure.

downloading the canonical boringssl source and repeating the process completes the make operation without warnings.  Extracting the canonical source to the grpc/third_party/boringssl directory doesn't resolve the problem... flagging new errors in the crypto directory... maybe because cmake isn't being invoked during the grpc make processes' compilation of boringssl?

Any solutions to this boringssl compilation issue?  Can I just "cut" boringssl out of the compilation process?

**Comment by jtattermusch** [comment]
is this issue still useful or should it be closed?

**Comment by jtattermusch** [comment]
Feel free to reopen if still an issue.
