### ISSUE TITLE
Benchmark single channel qps with multiple threads-per-cq

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10279]
- [x] expand qps suite with multiple thread-per-cq capability
- [x] build scenario with 1 client, 1 server, 1 channel, {1,2,4,8}-threads/cq {unary,streaming} ping pong
- [ ] ensure they're dashboarded at https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5632763172487168

**Comment by vjpai** [comment]
@kpayson64 : I know that you've been dealing with this issue recently so I've reassigned it to you. AFAIK, there are appropriate scenarios and tests, but no dashboarding. Can you fill in the details and close if possible?

**Comment by kpayson64** [comment]
Since switching to epollex, I think multiple threads/cq is not longer an optimization target.
