### ISSUE TITLE
Offer grpc_cli builds

### ISSUE THREAD

**Issue by ahmetb** [grpc/grpc#10273]
I am planning to bundle grpc_cli with my container image to use reflection to invoke RPCs in runtime. to provide health checks.

It does not appear like grpc_cli is offered as a binary as part of the releases. If it was something that is easily downloadable, I would much prefer to just `wget` it while building my application image rather than building it from source with `make grpc_cli`.

Is it feasible to offer grpc_cli binary as part of the release?

**Comment by jtattermusch** [comment]
We could build grpc_cli automatically as part of our build artifact workflow.

**Comment by hsaliak** [comment]
Update: this has come up again in the context of (a) using it to implement health check probes (b) difficulty of compilation and use. In general if we do not provide a build, other tools with better distribution story will take its place and fragment.

@jadekler is reviewing this whole space. which should help substantiate if we should offer distributions of `grpc_cli` or do something else.

**Comment by jtattermusch** [comment]
@hsaliak I think a relatively straightforward way to offer grpc_cli builds for multiple platforms is to generate them as part of our artifact build (in a similar way we generate protoc artifacts).
This is not hard to do, but I'm not sure I'll have cycles for that any time soon. I can provide guidance on how to do this if someone wants to take over.

**Comment by ahmetb** [comment]
I think it's still relevant.

**Comment by raboof** [comment]
> Adding an artifact build is not hard to do, but I'm not sure I'll have cycles for that any time soon. I can provide guidance on how to do this if someone wants to take over.

Is the published build created with cmake or bazel? I guess we'd want to:
* move the code out of `test` 
* (assuming a cmake build) introducing a separate flag for it instead of putting it under `gRPC_BUILD_TESTS`
* (assuming a cmake build) making sure it gets installed as part of the cmake install phase just like the plugins

?

**Comment by gnossen** [comment]
We've actually started encouraging people to use [`grpcurl`](https://github.com/fullstorydev/grpcurl). It's well-maintained, has [published binaries](https://github.com/fullstorydev/grpcurl/releases/tag/v1.5.0), and has a pretty complete feature set.

**Comment by raboof** [comment]
Makes sense, I'll put my energy there then ;) :+1:

**Comment by gnossen** [comment]
Going ahead and closing this issue as obsolete. If anyone has a compelling argument for it, feel free to revive the thread.
