### ISSUE TITLE
Measure C++ overhead of call creation

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10280]
We need an isolated micro benchmark (or set of benchmarks) that measures how much overhead the C++ wrapping layer adds to call creation cost:

- [ ] cpu overhead
- [ ] allocation count overhead
- [ ] locking overhead
- [ ] memory footprint overhead

**Comment by lyuxuan** [comment]
#10622 Client side cpu, allocation count and locking overhead.

**Comment by srini100** [comment]
closing this as other performance measurement effort is underway.
