### ISSUE TITLE
Reduce CPU cost of grpc_call creation

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10281]
Benchmark: bm_call_create.cc BM_IsolatedCall_NoOp
Dashboard: https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5740240702537728

cpu_time at bug creation: 681ns
target: 300ns

Ideas:
- reduce call size
- eliminate mutex initialization

**Comment by hcaseyal** [comment]
Just ran BM_IsolatedCall_NoOp, and it's showing a CPU time of **349ns**

**Comment by hcaseyal** [comment]
Closing because BM_IsolatedCall_NoOp currently shows CPU time is ~349ns (plus or minus some noise) and that seems close enough to 300ns. Moreover, the target of 300ns seems to have been chosen arbitrarily.
