### ISSUE TITLE
Reduce cost of a streaming send through grpc_call

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10288]
Benchmark: bm_call_create.cc BM_IsolatedCall_StreamingSend
Dashboard: https://performanceedit-dot-grpc-testing.appspot.com/explore?dashboard=5740240702537728

CPU time at bug creation: 223ns
Target: 50ns

**Comment by ncteisen** [comment]
Initial work: #10565

**Comment by ncteisen** [comment]
We track this effort in other places now
