### ISSUE TITLE
Reduce HPACK encode time for typical client metadata

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10291]
Benchmark: bm_chttp2_hpack.cc BM_HpackEncoderEncodeHeader<RepresentativeClientInitialMetadata>
Dashboard: https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5732910535540736&widget=757874064&container=2067035704

CPU time at writing: 259ns
Target: 75ns

**Comment by ncteisen** [comment]
We track this effort in other places now
