### ISSUE TITLE
the status of grpc php client

### ISSUE THREAD

**Issue by chensunny** [grpc/grpc#10301]
hi
i want to ask is any companies use in online env? and standard 
usage in distributed system。

**Comment by flisky** [comment]
I think the most important feature it lacks as a RPC client is **persistent connection**.

I have a golang-backend service, which is ~20k qps under benchmark.
However,  the php client has 0.5% chance to  connect **unavailable** when  qps > 1k, through ELB 4 layer loadbalancer.

I tried to use client-side round-robin LB without ELB using 1.2.0.
However, it doesn't work perfect.
It connects to all endpoints every times, and has a great chance to choose same server.

Php is supposed to be in a stateless mode. We cannot save state in application-level, and only extension can do it, just like [yar does](https://github.com/laruence/yar/blob/0ff9df3b90076dae1b03ea35bb6e21d6f5f69039/transports/curl.c#L145).

The grpc generated client has third option to pass `channel`,  but it only works to do multi RPCs during **a request**.

Is my understanding correct? I'll be surprised and happy to embrace it if you could tell me a way, @stanley-cheung & @nathanielmanistaatgoogle . Thanks!

**Comment by flisky** [comment]
By the way, HTTP2 direct connection has much more overhead than HTTP/1.1.
It starts with a connection preface, two settings frame, and two settings ACK.

I think [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) may help to go with the old-good HTTP/1.1, which is on my todo list.

**Comment by tmatsuo** [comment]
FWIW, for simpler APIs like logging, I'm trying to solve the similar problem by running an external daemon.
The source code is available at:
https://github.com/GoogleCloudPlatform/google-cloud-php/tree/batch/src/Core/Batch

You can run PHP daemon program that creates a client object at startup, and in your client code, just pass operations to the daemon.

Just an idea.

**Comment by dwsupplee** [comment]
Just a heads up the code linked above has since been merged and can now be found here:
https://github.com/GoogleCloudPlatform/google-cloud-php/tree/v0.34.1/src/Core/Batch

**Comment by stanley-cheung** [comment]
Closing this issue. The `grpc` extension by default creates persistent connections since `1.6.0` release.
