### ISSUE TITLE
Objc rpc request when network is unavailable calls handler but still completes request when network returns

### ISSUE THREAD

**Issue by chuckhays** [grpc/grpc#10302]
If an rpc request is created/started when the network is unavailable (airplane mode) it immediately calls the handler with error code GRPCErrorCodeUnavailable.

Expected: Once the handler is called we assume the request is completed and won't do any further work. 
Actual: When the network returns (turn off airplane mode), the request completes in the background and never calls the handler again

Repro steps:
1. Turn on airplane mode
2. Make an rpc request
3. Observe that handler is called with error: GRPCErrorCodeUnavailable
4. Turn off airplane mode
5. Observe that request is still made and handler is not called

The line that creates the error and calls finishWithError:
https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/GRPCCall.m#L404

It appears that the code may need to call [self cancelCall] like is done here:
https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/GRPCCall.m#L240

**Comment by royfourson** [comment]
Hi everyone,

I've been seen this error as well. I tried using the Cache-Control headers to expire the cache life but that didn't work at all. In the end, I cancelled the RPC upon any error coming back:

`__block GRPCProtoCall *rpc;
  CompletionBlock connectionErrorCallback =
      ^(id _Nullable response, NSError * _Nullable error) {
        if (error) {
          [rpc cancel];
        }
        responseHandler(response, error);
      };
  // Generate and start the RPC call.
  rpc = [self.myService RPCWithRequest:request handler:connectionErrorCallback];
  [self startRPC:rpc];`

Hope this helps.
Thanks,

**Comment by muxi** [comment]
Tried with both WiFi and cellular and this problem did not reproduce. After turning airplane mode off (tried turning on/off Wifi as well), both peers remained idle without receiving anything for at least 30s.

Any further information (platform, iOS version, stream/unary call, etc.) that is helpful on debugging/reproducing this would be appreciated.

**Comment by royfourson** [comment]
Hi Muxi,

This issue was reproducible on WiFi, never tried on other networks. The
phone (an iPhone7) was always on airplane mode. To reproduce it we would:

-Turn off the wifi.
-Start the request and receive the no connectivity error.
-Turn on the wifi again.

If I remember correctly, we were able of getting the same error on iOS
simulators. Then again, the error wouldn't occur depending on the timing of
the connectivity switching (perhaps a race condition?).

Thanks,
