### ISSUE TITLE
interop go docker image failure

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#10317]
From: 
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12572/console
Error :
../../transport/http2_client.go:130: undefined: dialContext

**Comment by makdharma** [comment]
Perhaps a dup of [grpc/grpc-go#1146](https://github.com/grpc/grpc-go/issues/1146)

**Comment by ncteisen** [comment]
Closing as duplicate of grpc/grpc-go#1146
