### ISSUE TITLE
C# CompletionRegistry.dict should use custom IEqualityComparer

### ISSUE THREAD

**Issue by neuecc** [grpc/grpc#10320]
CompletionRegistry.dict is initialized by default ConcurrentDictionary constructor.
`readonly ConcurrentDictionary<IntPtr, OpCompletionDelegate> dict = new ConcurrentDictionary<IntPtr, OpCompletionDelegate>();`
https://github.com/grpc/grpc/blob/1445c479013a997a2fa41bfd09a5219298c4c3d8/src/csharp/Grpc.Core/Internal/CompletionRegistry.cs#L54

But `IntPtr` is not impelments `IEquatable<IntPtr>` so which is used ObjectEqualityComparer in ConurrentDictionary.
https://referencesource.microsoft.com/#mscorlib/system/intptr.cs,29

ObjectEqualityComparer calls `Equals(objct)` it causes boxing.
https://referencesource.microsoft.com/#mscorlib/system/collections/generic/equalitycomparer.cs,137

If make the custom `IEqualityComparer<IntPtr>` and use in ConccurentDictionary constructor, it will improve performance.

**Comment by jtattermusch** [comment]
Interesting, do you have any measurements to get a sense of how big the performance impact is? (to be honest, I expect it to be quite small).

**Comment by neuecc** [comment]
Yes, I think that impact is small.
I have no data but when I've built serializer, boxing had large impact.
https://github.com/neuecc/ZeroFormatter/#performance
Graph of Single Integer(1) compare is boxed vs no boxed compare.
