### ISSUE TITLE
Improve C++ documentation for Server::Shutdown

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#10324]
It's hard for users to understand the implications of Server::Shutdown with a deadline

**Comment by vjpai** [comment]
I posted this explanation of the comment on [ServerInterface::Shutdown](https://github.com/grpc/grpc/blob/bc81eee4d4384cb461b587400c3f534be2503e5c/include/grpc%2B%2B/impl/codegen/server_interface.h#L50) on another forum:

"Shutdown the server" : deactivate all listening ports, mark it in "shutdown mode" so that further call Request's or incoming RPC matches are no longer allowed. Also return all Request'ed-but-not-yet-active calls as failed (!ok): note that this would even include default calls added automatically by the C++ API without the user's input.

"blocking until all rpc processing finishes" : this applies to the RPC functions invoked automatically by the server in the case of the Sync API. It does not apply to anything about the async API.

"Forcefully terminate pending calls after \a deadline expires" : Any calls that are associated with the server will be canceled after the deadline. Note that this just does a cancel. In the case of the sync API, if the RPC function for a streaming call has already been started and takes a week to complete, the RPC function won't be forcefully terminated (which is probably a good thing since otherwise it could leave state corrupted and incomplete)

If the last Next of an active RPC happens before the deadline expires, then you'd expect the Shutdown to return soon after that. But keep in mind that you need to Shutdown the server CQ after the server Shutdown finishes, and you need to drain that server CQ (by repeated Next) after it is Shutdown.

**Comment by sivabudh** [comment]
@vjpai suppose `ServerInterface::Shutdown` has been called already, how do the services `while(true)` processing streaming writes know that it's supposed to quit?

For example, here's one of my server-side streaming service. It's oblivious to the fact that the server is done because of the `while(true)`.

```
Status StreamServiceImpl::GetCurrentTemperature(ServerContext *context_,
                                                const UpdateInterval *request_,
                                                ServerWriter<Temperature> *stream_)
{
  auto currentTemp = 100.0f;
  while (!context_->IsCancelled())
  {
    qDebug() << QThread::currentThreadId() << currentTemp << "farenheit.";

    Temperature message;
    message.set_temperature(currentTemp);
    stream_->Write(message);

    QThread::sleep(2);

    currentTemp += 1.0f;
  }

  return Status::OK;
}
```
