### ISSUE TITLE
Node.js: process seems to hang indefinitely when offline

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#10322]
I noticed this while investigating [this google-cloud-node issue](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2137).

The scenario goes, **while offline**:

1) Set the deadline for an API request to "right now" (Date.now())
2) The request fails with the "Deadline exceeded" error
3) The node process exits

When you try the same with a deadline that's more reasonable:

1) Set the deadline for an API request to "right now" + 10 or more ms
2) The request fails with the "Deadline exceeded" error
3) The node process does not exit
4) Re-connect network
5) The node process exits

I've put this into code here: https://github.com/stephenplusplus/grpc-open-process

Is there possibly a retry strategy at work?

Thanks!

**Comment by murgatroid99** [comment]
We don't have retries yet, so it's not that. I suspect this is some weird interaction between Node internals and the way gRPC does network connection attempts.

One thing worth trying is explicitly closing the gRPC client when you're done with it, by calling `grpc.closeClient(service)`. Those clients do create network resources, and it's not always possible to guarantee that those resources will be released by the garbage collector in a reasonable amount of time.

**Comment by murgatroid99** [comment]
It turns out that there was a bug in some DNS request retry code that I added to fix #9605.

**Comment by murgatroid99** [comment]
I have published grpc@1.2.3, which includes a fix for this bug.

**Comment by stephenplusplus** [comment]
The test repo works as expected now, so I'd consider this resolved. Thanks!
