### ISSUE TITLE
Reduce single event wakeup time for epoll

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10330]
Benchmarks: BM_SingleThreadPollOneFd, BM_SingleThreadPollOneFd_SpeedOfLight

Currently this is 726ns vs 483ns, meaning ~300ns are spent in our polling abstraction.

**Comment by ncteisen** [comment]
cc @kpayson64 @sreecha. Is this issue a specific enough goal? Feel free to close if this work is being handled elsewhere
