### ISSUE TITLE
c-ares not built from third_party

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10332]
On my mac and on the performance workers, head currently fails as c-ares is not installed. If it's not installed, we should be using the third_party/c-ares version.

Supercedes #10328

**Comment by ctiller** [comment]
This seems to be user error

**Comment by Croydon** [comment]
What was the error? What is the solution? I'm getting stuck here as well.

**Comment by MrMage** [comment]
In case anyone else encounters this, I was able to fix it by running `git submodule update --init` in the main `grpc` directory.
