### ISSUE TITLE
Go interop tests are failing to build

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#10359]
As examples:

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12681/console
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12680/console

It seems the rootcause is systematically

```
../../transport/http2_client.go:130: undefined: dialContext
```

**Comment by ncteisen** [comment]
Closing as duplicate of grpc/grpc-go#1146, seems to be fixed by #10309.
