### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by vnitinv** [grpc/grpc#1035]
Hi,

I am trying to compile on FreeBSD but the makefile give error. Do we have support for FreeBSD?

grpc-master]$ mk
bmake.amd64: "grpc-master/Makefile" line 37: Missing dependency operator
bmake.amd64: "grpc-master/Makefile" line 39: Need an operator

**Comment by vjpai** [comment]
FreeBSD is not a supported platform for gRPC and it has not been built or tested on this platform. That said, I think that it is likely to work with just some build process changes, since gRPC does work on Mac. Please let us know if you try to do so!
Thanks for your interest.

**Comment by vnitinv** [comment]
I started with mac only. But there too faced some issue. Please have a look at below issues:

https://github.com/grpc/grpc/issues/994

https://github.com/grpc/grpc/issues/995

also it was told to me in response to #995  "Mac support for Python gRPC will happen somewhere in the alpha or beta timeline."

**Comment by nicolasnoble** [comment]
The Makefile will probably only work with GNU Make at the moment.

**Comment by nicolasnoble** [comment]
Also, to continue on @vjpai's replay, we had positive results for grpc under Mac, when compiling the C and C++ cores. The other wrapped languages will still require more work however.

**Comment by nicolasnoble** [comment]
FreeBSD support is indeed lacking:

![freebsd](https://cloud.githubusercontent.com/assets/7281574/6658850/94f342b4-cb33-11e4-85f5-c6e63126ec80.png)

**Comment by jevonearth** [comment]
Just a quick note, I tried to build grpc `master` and `v1.0.0` on FreeBSD 11.0-RELEASE-p1 today, and I can confirm that this is still broken on FreeBSD.

The build fail logs are: 

```
[C]       Compiling src/core/lib/iomgr/socket_utils_common_posix.c
src/core/lib/iomgr/socket_utils_common_posix.c:101:39: error: use of undeclared identifier 'IP_PKTINFO'
  if (0 != setsockopt(fd, IPPROTO_IP, IP_PKTINFO, &get_local_ip,
                                      ^
1 error generated.
gmake: *** [Makefile:2186: /usr/home/jev/grpc/objs/opt/src/core/lib/iomgr/socket_utils_common_posix.o] Error 1
```

**Comment by leodesigner** [comment]
I was trying to build Tensorflow under FreeBSD.
Got the same error regarding: 
`
if (0 != setsockopt(fd, IPPROTO_IP, IP_PKTINFO, &get_local_ip,
`

**Comment by blodan** [comment]
I too ended up in the same place with IP_PKTINFO being undeclared trying to build Tensorflow on FreeBSD

@jevonearth you didn't manage to get this compiled? :)

**Comment by blodan** [comment]
If anyone else is stumbling on this issue, all you have to do is to remove the define of GPR_HAVE_IP_PKTINFO in include/grpc/impl/codegen/port_platform.h as freebsd does not have it.

It compiles fine after that.

**Comment by No9** [comment]
Thanks @blodan I just ran into this too
Are you going to PR this?

**Comment by xorander00** [comment]
I commented on a thread in regards to this over at GitLab:
https://gitlab.com/gitlab-org/gitaly/issues/154

Figured I'd link it here too, as I'd like to get this fixed and working on FreeBSD.  Any suggestions would be greatly appreciated, thanks! :)
