### ISSUE TITLE
objc testRPCAfterClosingOpenConnections failed

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#10368]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/3984/testReport/junit/(root)/aggregate_tests/run_tests_objc_macos_opt_native/

InteropTestsLocalCleartext
  testRPCAfterClosingOpenConnections, ((error) == nil) failed: "Error Domain=io.grpc Code=14 "Endpoint read failed" UserInfo={NSLocalizedDescription=Endpoint read failed, io.grpc.TrailersKey={
  /jenkins/workspace/gRPC_pull_requests_macos/workspace_objc_macos_opt_native/src/objective-c/tests/InteropTests.m:444
  ```
  [_service emptyCallWithRequest:request handler:^(GPBEmpty *response, NSError *error) {
    XCTAssertNil(error, @"First RPC finished with unexpected error: %@", error);

  ```

**Comment by dgquintas** [comment]
Not seen in quite a while, closing.
