### ISSUE TITLE
API/ABI changes review for gRPC

### ISSUE THREAD

**Issue by lvc** [grpc/grpc#10379]
The review of API/ABI changes for gRPC since 1.0.1 version: https://abi-laboratory.pro/tracker/timeline/grpc/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

The tool checks _all_ API symbols declared in header files, so there may be some false positives.

Thank you.

![grpc-1](https://cloud.githubusercontent.com/assets/1517837/24498876/f6a0e7a0-1550-11e7-8c3a-5789b39507a1.png)

![grpc-2](https://cloud.githubusercontent.com/assets/1517837/24498891/01fcbd0e-1551-11e7-809f-2d1ce8f4451e.png)

## Environment
* Linux x86_64
* GCC 4.9
* gRPC 1.0.1 and higher

**Comment by mehrdada** [comment]
Thanks for the interesting report.  Since there is no actionable step on this report as an issue, I will leave this closed on the issue tracker.
