### ISSUE TITLE
Python-tests-on-Travis sometimes fail with "error: can't start new thread"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1037]
The problem seems probabilistic and reattempting the test is usually enough to get a green result but it's annoying, time-consuming, probably something to do with how Travis constrains the tests run within it, and something that should be fixed at some point.

**Comment by ctiller** [comment]
Who is working on this?
Can we disable faulty tests until such time as we believe we have this fixed?

**Comment by ctiller** [comment]
(IOW: nearly 2 months after the initial report, I think the point this needs to be fixed is now)

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for assigning a priority.

A fix to this is going to come out of the work I'm doing now, so it's fair to say that I'm working on this.

**Comment by ctiller** [comment]
Is there an ETA for this work?

**Comment by nathanielmanistaatgoogle** [comment]
~1 week?

Has this problem become more severe recently? At the time of original reporting it was only one out of every twenty test runs or so.

**Comment by ctiller** [comment]
I've seen it a bunch in the last day or so. I've also been watching closely
in the last day or so.

I'd really like us to break the mind set of 'it's ok to just retry the
tests a few times', and get us into the mindset of freaking out if there's
a test failure. The only way to do so is if we have no broken windows, and
this particular window has been broken for a very long time.

**Comment by ctiller** [comment]
I'm ok with a week for a full fix. If there's something we can do to
stabilize (even shoddily) in the interim, I think it'll help overall build
stability however.

**Comment by ctiller** [comment]
Just saw this again.

**Comment by vjpai** [comment]
Just saw this now.

This was on Travis test 62445251, associated with PR #1575 
The full log is really really big (bigger than pasting into the issue will support)
The URL is https://s3.amazonaws.com/archive.travis-ci.org/jobs/62445251/log.txt

**Comment by nathanielmanistaatgoogle** [comment]
Has anyone seen this since @soltanmm merged #1598?

**Comment by jtattermusch** [comment]
Seen this in https://travis-ci.org/grpc/grpc/jobs/63097623 with PR #1646

**Comment by jtattermusch** [comment]
Seen again on https://travis-ci.org/grpc/grpc/jobs/63352452 with PR #1675

**Comment by nathanielmanistaatgoogle** [comment]
Just saw this in #1686.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle We never merged that - there were other strange issues that cropped up. Also, _it keeps happening_ (w.r.t. #1686 :-( ).

**Comment by ctiller** [comment]
I can reproduce this on my desktop.

**Comment by dgquintas** [comment]
Ditto. Easy to repro by increasing the factor for self.maxjobs at https://github.com/grpc/grpc/blob/master/tools/run_tests/run_tests.py#L59. s/2/20 makes it happen for me every time.

Also, @ctiller has added extra tracing debug info that may also come in handy in figuring it out.

**Comment by nicolasnoble** [comment]
I'm guessing this one can be closed ?

**Comment by dgquintas** [comment]
Yes. Travis' ulimit for processes/threads was the "culprit" (rather, what made the issue surface).
