### ISSUE TITLE
Code generator should run as part of interop tests

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1038]
Currently the Python interop tests don't use generated code. Not only should they but the generated code should be generated as part of the test (rather than checked in as is the case with some of the other languages).

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: While you're in the neighborhood, if this looks doable, please feel invited to take it on. :-)

**Comment by kpayson64** [comment]
I believe this work has been completed:

We are already using an auto-generated stub,
https://github.com/grpc/grpc/blob/master/src/python/grpcio/tests/interop/client.py#L104

As of #6229, all generated generated python code gets built out of the shared src/proto/... as part of the test.

Feel free to reopen if I'm missing something.
