### ISSUE TITLE
Jenkins MacOS tests are being run concurrently

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10400]
Even though there is only one Jenkins executer on MacOS Jenkins worker, I just discovered that Multiple tests in ObjC are running at the same time. This might be causing ObjC's build and test failures as these tests are not contained by Docker and may conflict with each other.

**Comment by jtattermusch** [comment]
Possible reasons:
-- the processes are leftovers from previously running tests. You need to doublecheck that the test suites don't leave running processes behind (e.g. when a test fails).
-- run_tests_matrix.py  actually runs more test suites at once (and that is the intended behavior even though it can be set to run one test at a time).
-- run_tests.py  suites may also run more test cases at a time (depends on language specific settings).

In general, assuming that tests have exclusivity when running is wrong - and I am not sure what gave you the idea that you can rely on that. Also, it should be possible to run the tests in a way that parallel test runs don't collide with each other (in all other languages it works so I don't see why objc should be different).

There might be reasons why exclusivity is needed when running objc tests, but let's try not to rely on that.  Let's sync up on what are the assumptions when running objc tests (@matt-kwong, @jtattermusch @nicolasnoble are the right people you can talk to).

**Comment by matt-kwong** [comment]
The `run_tests_objc_macos_dbg_native` and `run_tests_objc_macos_opt_native` test suites are executed in parallel. And within those suites, tests within the suites are run in parallel. 

I reconfigured the master MacOS job to run test suites individually to test if running suites together is causing conflict with ObjC. If the results look greener on master, I'll apply the changes to pull requests.

**Comment by muxi** [comment]
@matt-kwong It might be too aggressive that MacOS master takes more than 5 hours to run now...

@jtattermusch You are right that usually we should not rely on that. I am suspecting this is that `run_tests_objc_macos_dbg_native` and `run_tests_objc_macos_opt_native` use the same output directory. When they run concurrently without Docker they could be overwritting each other. We might be able to separate them though... looking for a solution.

**Comment by matt-kwong** [comment]
The MacOS jobs taking over 4 hours was an issue related to Ruby. Regardless, running suites sequentially increased the time to run all tests and didn't yield greener results, so I reverted the change.

**Comment by muxi** [comment]
Yep that seems like it...

**Comment by muxi** [comment]
Problem solved...with a reboot.

**Comment by matt-kwong** [comment]
Did you reboot all of the workers? If so, that's a problem on my end since the Macs are supposed to reboot after every job because there have been issues in the past related to this and I set up Jenkins to reboot the Macs. I'll take a look to see if Jenkins has stopped rebooting them.

**Comment by muxi** [comment]
I rebooted mac workers 3-5, those used for MacOS Master and PR.

I saw the 'downstream job' attempt to reboot macs and I was not sure if it worked. All of those tasks were red, which could either be a failure or be due to the reboot itself.

Maybe it's gonna be easy to figure out if we ask whoever possess those machines whether they hear that mac booting sound all the time? ;-)

**Comment by matt-kwong** [comment]
https://grpc-testing.appspot.com/job/Reboot_MacOS_Worker/ - all the jobs should be red because the Macs reboot in the middle of the job. It looks fine to me; it seems Macs 3-5 reboot at least every few hours. 
```
+ nohup sh -c 'sleep 2; killall java; sudo reboot; sleep 10'
Agent went offline during the build
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2332)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2801)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
```
The logs also show they are rebooting. Strange...
