### ISSUE TITLE
Make grpc node work with node's cluster support.

### ISSUE THREAD

**Issue by tracker1** [grpc/grpc#10417]
Right now, node's handling of requests is limited to a single process, and grpc won't work with node's cluster module... in the end, I mostly feel it should be possible to run multiple processes to handle more requests on a single server on a single port coming in.

Would it be better to just have a round-robin load balancer to route tcp connections to multiple instances on the same server, or would it be better to change grpc to allow for more processor/workers with grpc?

As it is, it's not *really* an issue... I'm able to handle around 3500 requests/second on my mid2014 rmbp (I7-4770HQ), which is plenty... I guess I'm just surprised to be so far short of hitting the 10K mark.

**Comment by amitripshtos** [comment]
There are few load balancers that support http2 already (normal TCP balancer won't work since http2 has "streams")

You can see an example here:
https://github.com/amitripshtos/grpc-docker-lb

**Comment by murgatroid99** [comment]
See #6976. I would like to do this, but it's complicated.

**Comment by tracker1** [comment]
@amitripshtos I understand that... however, then I'd need to configure the load balancer on the machine and several instances of my node grpc service... where with cluster, the semantics are built in already, so I can just fork for the number of processes/workers I want in place.

**Comment by i5ting** [comment]
@tracker1 great! there's no need to support it, if someone need cluster, it will be built on framework,not on grpc

**Comment by murgatroid99** [comment]
Closing this. Follow along on #6976.
