### ISSUE TITLE
RPC get DEADLINE exceed even when server already shutdown.

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#10418]
I have a c++ test case will do the server_->Shutdown() and then send an RPC to the shut downed server. But rarely, I will get DEADLINE EXCEED even when the server_'s Shutdown method is returned.
Is there anything I miss? Is calling shutdown the right thing to do to shut down a server?

**Comment by yashykt** [comment]
No more RPCs will be serviced after the server is shut down.

**Comment by yashykt** [comment]
Yes, calling shutdown is the right thing to do. If the server is asynchronous, then the completion queues should continue processing till it receives shutdown.

**Comment by yashykt** [comment]
https://groups.google.com/a/google.com/forum/#!forum/grpc.io would be a better place for further questions
