### ISSUE TITLE
ruby client error during interop

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#1041]
/var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:60:in `<main>': uninitialized constant Google::Auth::ServiceAccountCredentials::ENV_VAR (NameError)

**Comment by tbetbetbe** [comment]
@donnadionne:  This should be fixed.  Can you please confirm and close this bug?

**Comment by tbetbetbe** [comment]
Closed by #1077
