### ISSUE TITLE
nuget & grpc-auth 1.2.0

### ISSUE THREAD

**Issue by tasoss** [grpc/grpc#10429]
Hello
I'm trying to install grpc 1.2.0 from nuget and i get errors.
I'm using visual studio 2017 and i have pasted [here](https://pastebin.com/b282i5zL) some results.
I can install 1.2.0-pre1 but not 1.2.0 and that's why i can't install google speech api.
Any ideas please?
Thanks!

**Comment by workday366** [comment]
Hey:
I have the same question when trying to install grpc 1.2.0 using nuget and then I can't install google speech api. Any help?
Thank you!

**Comment by workday366** [comment]
If you can't install grpc 1.2.0, you can use the following command to install the former version. Install-Package Google.Cloud.Speech.V1Beta1 -Version 1.0.0-alpha06 -Pre. Then you will be able to use Google Speech Api.

**Comment by tasoss** [comment]
Thanks.A solution i have found in order to install 1.2.0 is to go [here](https://www.nuget.org/packages/Grpc/)  and press download which links to [here](https://www.nuget.org/api/v2/package/Grpc/1.2.0) .This will download the .nupkg file.You then can install it via visual studio.This is how i managed to install the latest version.Of course someone has to correct it.Anyway thanks again!
