### ISSUE TITLE
You should have a look at Cap’n Proto

### ISSUE THREAD

**Issue by slopjong** [grpc/grpc#1042]
[Cap’n Proto](https://capnproto.org) is the successor of Protocol BuffersProto Buf, and it's much faster.

**Comment by nicolasnoble** [comment]
grpc technically doesn't rely on a specific marshalling protocol. You could use whichever you want here.

**Comment by louiscryan** [comment]
We chatted with Kenton Varda about it and for the moment he wan't too interested in using GRPC as the wire-transport mechanism for Cap'N'Proto RPC. If someone wants to write a binding over the GRPC transport layer we would welcome it as a contrib.

I don't think it's quite accurate to describe CapNProto as the successor to Protobuf. There's a great deal to like about it as well as other formats like Flatbuffers so it's an area we keep a very close eye on.

Closing as an issue here as it's something probably more suited for discussing on the mailing list.

https://groups.google.com/forum/#!forum/grpc-io
