### ISSUE TITLE
Pass error type during cq->next

### ISSUE THREAD

**Issue by zhimingxie** [grpc/grpc#10425]
Considering the async server example:
`GPR_ASSERT(cq_->Next(&tag, &ok));`
`GPR_ASSERT(ok);`
Here, the ok is not always true in practice and user hardly to detect which error happens.  
I saw the source code, it appears that  ok comes from `grpc_cq_end_op`, `(uintptr_t)(error == GRPC_ERROR_NONE)` ultimately. 
So can grpc pass the detail error value by api, or provide other mechanism to find this error when ok is  false ?

Another question,  as far as async server example concerned, how to deal with `ServerContext ctx_` safely when ok is safe ? I'm afraid it will cause other assert if call it's destructor simplely

**Comment by sreecha** [comment]
If `ok` is not true, the idea is that you can get the error from the RPC status. 

Previously there were some cases where on the server we returned `ok = false` for some incoming RPCs..this is fixed now (i.e now when ok == false, it means either that the RPC failed - in which case you can get the status from the specific call...or the completion queue was shutdown..in which case even `cq_->Next` would return false)
