### ISSUE TITLE
Health Checking documentation is very confusing

### ISSUE THREAD

**Issue by ahmetb** [grpc/grpc#10428]
I am using gRPC and I read the [health-checking.md](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) and I must say I only understood about 10% of it. The documentation is not using a language that is friendly to an average gRPC user.

I highly recommend supplementing this with an example code/implementation in one of the grpc-$LANG repos.

Here are some vague things:

- If I copy paste the specified .proto automatically and generate code, do I need to write the server implementation myself or does gRPC magically understands it and registers a health server automatically? This is not crystal clear.

- Are the gRPC clients actually supporting these magic names `HealthCheckResponse`  `HealthCheckRequest` `Health.Check`  and doing health checks under the covers and making health checks automatically? Or is client-side health check is something you expect programmer to implement? I get the impression that gRPC understands these names out of the box. (`string service = 1;` makes me think this is something gRPC understands.) (Otherwise, why do you even have a doc for this? I can roll my own health check format and solve the problem myself. I don't understand what this doc provides here.)

- > _A client can query the server’s health status by calling the Check method, and a deadline should be set on the rpc._
  > ...
  > _A client can declare the server as unhealthy if the rpc is not finished after some amount of time. The client should be able to handle the case where server does not have the Health service._
  
  I can't tell if this doc is talking to me (a user) or talking to a grpc-$LANG implementer by saying can/should etc.

**Comment by hsaliak** [comment]
@ahmetb there should be examples in all languages eg: https://github.com/grpc/grpc-go/tree/master/health and https://github.com/grpc/grpc-node/tree/master/packages/grpc-health-check etc.. Some of the test https://github.com/grpc/grpc-node/blob/master/packages/grpc-health-check/test/health_test.js#L40 might also be useful.
