### ISSUE TITLE
build_docker_xxx fails

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10443]
A number of build_docker_xxx jobs failed in Jenkins:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12851/console

```
FAILED: build_docker_go [ret=1, pid=31428]
FAILED: build_docker_http2 [ret=1, pid=25143]
FAILED: build_docker_java [ret=1, pid=25145]
FAILED: build_docker_python [ret=1, pid=25229]
FAILED: build_docker_http2 [ret=1, pid=25231]
```

**Comment by muxi** [comment]
build_docker_python still failing in master:
https://grpc-testing.appspot.com/job/gRPC_interop_master/12938/console
@adelez could you help triage? 😃

**Comment by muxi** [comment]
@adelez actually never mind as it is for python...

**Comment by nathanielmanistaatgoogle** [comment]
This seems to be behind the failures of gRPC_interop_master [#13313](https://grpc-testing.appspot.com/job/gRPC_interop_master/13313/) through [#13331](https://grpc-testing.appspot.com/job/gRPC_interop_master/13331/). It is almost certainly a test infrastructure issue; it is definitely not a gRPC Python issue.
