### ISSUE TITLE
Kill stress tests & perform cleanup

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10442]
Currently stress tests are not providing any added value (and some of them are also failing).

-- remove code for running stress tests (deleted code is good code).
-- shutdown the cluster used for running stress tests (significant resource savings).

CC @sreecha

**Comment by jtattermusch** [comment]
@sreecha   cool, that's the best of course.

**Comment by sreecha** [comment]
#11027 addresses this

**Comment by sreecha** [comment]
This is done. The issue can be closed.
