### ISSUE TITLE
Node.js: Potential memory leak

### ISSUE THREAD

**Issue by ofrobots** [grpc/grpc#10445]
Ref: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2135

See the above customer reported issue of a memory leak with the `@google-cloud/logging` library. I can reproduce the leak (sample code below). Looking a memory usage, JS heap and Node.js external memory is constant but RSS increases. This suggest that this is memory leaking from a native module. Since gRPC is the only native module involved, this is possibly a leak in gRPC?

```
❯ node index.js
myapp listening at http://[::]:8080
rss 66093056 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 66101248 heap 59740160 external 153861
rss 143564800 heap 86478848 external 835128
rss 149528576 heap 77041664 external 794091
rss 161824768 heap 75993088 external 515467
rss 177254400 heap 75993088 external 438475
rss 195915776 heap 76517376 external 543307
rss 210944000 heap 75993088 external 712427
rss 225538048 heap 75993088 external 732971
rss 241627136 heap 75993088 external 523787
rss 256933888 heap 76517376 external 430443
rss 275152896 heap 75993088 external 712395
rss 291975168 heap 75993088 external 438635
rss 303693824 heap 75468800 external 724875
rss 321449984 heap 76517376 external 523979
rss 338817024 heap 77041664 external 724587
rss 354705408 heap 77041664 external 540107
rss 372436992 heap 76517376 external 438667
rss 385081344 heap 75993088 external 741227
rss 403259392 heap 75468800 external 729419
rss 420491264 heap 76517376 external 749227
rss 436707328 heap 76517376 external 523147
rss 452116480 heap 76517376 external 404203
rss 468451328 heap 75468800 external 633995
rss 485847040 heap 75468800 external 734251
rss 501522432 heap 75993088 external 741291
rss 516468736 heap 75468800 external 514923
rss 537968640 heap 75993088 external 683531
....
```

Testcase
```js
const logging = require('@google-cloud/logging')();
const plugins = require('restify-plugins');
const restify = require('restify');
const util = require('util');

const log = logging.log('logging-log');
const metadata = {
  resource: {
    type: 'global'
  }
};

const server = restify.createServer({
  name: 'myapp'
});

server.use(plugins.acceptParser(server.acceptable));
server.use(plugins.queryParser());
server.use(plugins.bodyParser());

server.get('/echo/:name', function (req, res, next) {
  const entry = log.entry(metadata, `got /echo request: ${req.params.name}`);
  log.info(entry, {}, function() {});
  res.send(req.params);
  return next();
});

server.listen(8080, function () {
  console.log('%s listening at %s', server.name, server.url);
});

setInterval(() => {
  const m = process.memoryUsage();
  console.log(`rss ${m.rss} heap ${m.heapTotal} external ${m.external}`);
}, 5 * 1000);
```

Even with mild load, the above leaks memory fairly rapidly.

This does require $GCLOUD_PROJECT to be set and valid credentials to be available.

/cc @murgatroid99

**Comment by murgatroid99** [comment]
I have found a couple of memory leaks in the C++ glue code caused by calls to `CreateSliceFromString` that are not followed by `grpc_slice_unref`. There also appears to be a memory leak in the core code for handing metadata from call credentials (which is used to connect `google-auth-library` with gRPC), but so far, I have been unable to track down the root cause.

**Comment by mattheworiordan** [comment]
We too have a confirmed memory leak when upgrading from 1.1 to 1.2. We tried to deploy 1.2.1 as well a few hours ago, and the leak persists.  See the graphs below:

![image](https://cloud.githubusercontent.com/assets/43789/24653054/1d32d444-192c-11e7-8468-8f645de0406a.png)

We too took heap dumps, and found that the memory was not registered in the Node.js heap dump, so is definitely a native memory leak.

**Comment by mattheworiordan** [comment]
FYI. It is very easy for us to reproduce this issue and we have hundreds of nodes we can deploy this on. If anyone has any suspected SHAs that they think may have introduced the bug, I'd be happy to run a few different version for a few hours and post the results.

**Comment by mattheworiordan** [comment]
@murgatroid99 I have created a [repo which detects this leak by using a git bisect](https://github.com/ably/grpc-memory-leak-test).  

The memory leak, according to my tests which can reproduce the problem, first started with [your commit that disabled `GRPC_UV`](https://github.com/grpc/grpc/commit/6f62c0adca4921c8d0e75ec5b9886280ead5b7f1).

Whilst I can see that `GRPC_UV` appears to have been reintroduced later, running my tests against `v1.2.1` results in the memory climbing rapidly and an assertion crash:

```
E0405 02:34:16.121913000 140736711590848 sync_posix.c:60]              assertion failed: pthread_mutex_lock(mu) == 0
./install_and_test_leak.sh: line 33: 99610 Abort trap: 6           node ./test_grpc_leak.js
~/code/Ably/forks/grpc_test
```

Are there any node specific tests where a memory leak test could be added to prevent future regressions? Our platform relies extensively on gRPC, and whilst we will now add our own tests to prevent this type of regression, I am sure it would benefit everyone to have something similar.

Shout if I can do anything further to help.

**Comment by mattheworiordan** [comment]
@murgatroid99 please see my PR at https://github.com/grpc/grpc/pull/10476 which fixes this issue in the `1.1.*` branch

**Comment by murgatroid99** [comment]
I'm not comfortable enabling `GRPC_UV` in 1.1.x. There have been changes since then that make `GRPC_UV` work properly. Plus, that clearly can't be the root cause of the leak.

**Comment by mattheworiordan** [comment]
> Plus, that clearly can't be the root cause of the leak.

Well that's the commit that introduced the leak, and 8f60965 fixes the leak, so what do you suggest?

**Comment by mattheworiordan** [comment]
> I'm not comfortable enabling GRPC_UV in 1.1.x. There have been changes since then that make GRPC_UV work properly. Plus, that clearly can't be the root cause of the leak.

Understood, but surely it's more uncomfortable having a known memory leak?

**Comment by murgatroid99** [comment]
I've created PR #10503, which fixes this problem, at least using the repro case provided above. It might be possible to backport those changes to 1.1.x, but you'd probably be better off updating to 1.2.x after that change is published.

**Comment by murgatroid99** [comment]
I have published grpc@1.2.3, which includes fixes for this leak.

**Comment by ofrobots** [comment]
Awesome! I can confirm that the memory leak I was observing with the test-case above is fixed.

**Comment by ofrobots** [comment]
I believe this can be closed from my point view.
