### ISSUE TITLE
server_builder.cc and env_windows.c memory leak 

### ISSUE THREAD

**Issue by mck0225** [grpc/grpc#10453]
- leak 1 (env_windows.c) -
char *gpr_getenv(const char *name) {
  char *result = NULL;
  DWORD size;
  LPTSTR tresult = NULL;
  LPTSTR tname = gpr_char_to_tchar(name);
  DWORD ret;

  ret = GetEnvironmentVariable(tname, NULL, 0);
  if (ret == 0) return NULL;    // <---- forgot gpr_free(tname);
  size = ret * (DWORD)sizeof(TCHAR);
  tresult = gpr_malloc(size);
  ret = GetEnvironmentVariable(tname, tresult, size);
  gpr_free(tname);
  if (ret == 0) {
    gpr_free(tresult);
    return NULL;
  }
  result = gpr_tchar_to_char(tresult);
  gpr_free(tresult);
  return result;
}

- leak 2 (server_builder.cc) -
g_plugin_factory_list pointer is not deleted

A memory leak occurs for both of the above cases.

**Comment by kkm000** [comment]
@mck0225: Item 1 is certainly a bug, thanks! Can you please elaborate on the second one?
