### ISSUE TITLE
Half duplex test fails at stream->Write(request) when the message size is very large

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#10485]
I tried 20MB and the client fails to write. Attached is the full log:
[client_log.txt](https://github.com/grpc/grpc/files/900554/client_log.txt)

Tested in cloud-to-cloud scenario.

@fengli79

**Comment by yang-g** [comment]
The interop server needs to increase the max recv message size (default to 4MB).

**Comment by adelez** [comment]
After setting both server side send and receive message size to INT_MAX, server throws error about handshake failure.
E0405 14:25:45.715066   94651 chttp2_server.c:83] Handshaking failed: {"created":"@1491427545.714862658","description":"Socket closed","fd":42,"file":"third_party/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":253,"target_address":"ipv6:[::1]:60737"}

**Comment by adelez** [comment]
I tried adding the following to the client
channel_args.SetMaxReceiveMessageSize(INT32_MAX);
  channel_args.SetMaxSendMessageSize(INT32_MAX);

But it still failed.

**Comment by yang-g** [comment]
I could not reproduce.
I noticed that there are multiple CreateTestChannel used in the interop test. Did you update the channel_args on all of them?

**Comment by adelez** [comment]
It's working now. I didn't propagate the channel_args properly in the last try.
