### ISSUE TITLE
Latest tagged versions not released as ruby gem

### ISSUE THREAD

**Issue by Op3n4M3** [grpc/grpc#10487]
The v1.2.1 and v1.2.2 tags do not have corresponding gems released in rubygems.org.

https://rubygems.org/gems/grpc

Changes provided in theses gems provide compatibility with native compilation of the grpc gem on architectures without pre-compiled binaries.

**Comment by apolcyn** [comment]
the 1.2.2 release was just published with those fixes (we skipped from 1.2.1-pre2 to 1.2.2)

**Comment by Op3n4M3** [comment]
Thank you!
