### ISSUE TITLE
Installing gRPC from source will not work in China

### ISSUE THREAD

**Issue by pavelsimo** [grpc/grpc#10499]
After running the command:
git submodule update --init

The script attempt to pull the following repository:
'third_party/boringssl-with-bazel' (https://boringssl.googlesource.com/boringssl) 

The domain googlesource.com is blocked for the GFW, so the process can't complete. I am not sure if it's anything that can be done since this is a external repository.

Thanks,
Pavel

**Comment by ctiller** [comment]
@agl: there's a github based mirror we can point at right?

**Comment by agl** [comment]
https://github.com/google/boringssl

**Comment by mehrdada** [comment]
The git submodule is currently pointing to github, so this should be resolved. Please re-open if you are still experiencing problems.
