### ISSUE TITLE
windows server 2012 r2 grpc_csharp_ext.x64.dll loading issues

### ISSUE THREAD

**Issue by tasoss** [grpc/grpc#10502]
Hello.
I have installed a web app on windows 2012 r2 and i get the following error
`  
System.IO.IOException: Error loading native library "C:\foobar\bin\grpc_csharp_ext.x64.dll"
 at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable'1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Google.Cloud.Speech.V1Beta1.SpeechClient.Create(ServiceEndpoint endpoint, SpeechSettings settings)
   at foobar.FileUploadController.<UploadSingleFile>d__1.MoveNext() in 
D:\barfoo`
Is there any way to make it work on 2012 r2?
Thanks!

**Comment by maiorfi-at-innovactive** [comment]
Same here. I'm using a brand new Windows 10 1703 (aka creators update) machine.
Looking at exception content, it seems that despite working inside a x64 platform it tries loading x86 version. BTW, swapping dll names doesn't work as well.

**Comment by vadimi** [comment]
Which version of gRPC nuget package do you use? I'm using `1.2.2` on windows server 2012 R2 and everything works fine, both x86 and x64 versions. There was a problem with `1.2.0`, but it got resolved in `1.2.2`

**Comment by jtattermusch** [comment]
As @vadimi suggests, can you try upgrading to `1.2.2`?

**Comment by tasoss** [comment]
Hello and thanks for replying.
I was using 1.2.0 but i cannot test 1.2.2 on windows 2012 r2 because i had to remove the virtual machine on which it was installed and install it again on windows 7 in order to get it up and running(i knew it was working on 1.2.0 on windows 7)
Sorry.

**Comment by jtattermusch** [comment]
Ok, I will close this for now as it is likely that the 1.2.2 change is the fix you are looking for. Please reopen if you see the issue again.

**Comment by maiorfi-at-innovactive** [comment]
Upgrading to 1.2.2 solved this issue.

Thanks.

**Comment by tasoss** [comment]
Thanks!

**Comment by searope** [comment]
Hi, I'm having the same issue on Windows 10 x64 machine with VS2017 and GRPC v1.4.1

**Comment by tomerpeled** [comment]
Same over here...

**Comment by armand1m** [comment]
I'm having this same issue on Windows 10 x64 machine with VS2017 and VS2015 using GRPC v1.4.0

**Comment by armand1m** [comment]
Tried almost everything, even used Dependency Walker to verify if there are implicit or forwarded dependencies missing, and my system showed a lot of them but I have noones to compare to

**Comment by jtattermusch** [comment]
@armand1m   first of all, I'd recommend trying with a newer version of gRPC than 1.4.x (we now have v1.9.0)
If that still doesn't work, I'd recommend trying to install https://www.microsoft.com/en-us/download/details.aspx?id=48145 (it shouldn't be necessary, but it's worth trying).  If none of that helps, I can't really help without more details, as the nugets seems to work fine for many Win 10 users (and it also works on my Windows machine).
