### ISSUE TITLE
Slicer support

### ISSUE THREAD

**Issue by therc** [grpc/grpc#10504]
> Stubby typically directs RPCs round-robin from each client to a subset of tasks in a job. We extended Stubby to accept an additional slice key argument with each RPC, causing the task to be selected using Slicer’s assignment.

https://www.usenix.org/system/files/conference/osdi16/osdi16-adya.pdf

When will this be open sourced? If not the full implementation (unrealistic), at least the right hooks and interfaces.

**Comment by hsaliak** [comment]
There are currently no plans to implement this, could you please elaborate on this use case?

**Comment by markdroth** [comment]
We have discussed this use-case in the past as part of various load balancing designs, but we don't currently have any concrete plans to provide an OSS slicer implementation.  However, that could happen at some point in the future, so let's keep this open to track the request.
