### ISSUE TITLE
C# Server side authentication

### ISSUE THREAD

**Issue by AhmadChaker** [grpc/grpc#10513]
I'm attempting to perform server authentication using gRPC however I'm unsure of how to proceed.
My current setup is that I have a server running on one machine and a client on another (both windows machines).
For testing purposes I've generated a certificate authority and a private certificate (from this certificate authority) using the windows makecert.exe.
This generates .cer file. 

The documentation for SslServerCredentials does not have any provisions for a .cer file. What would be my KeyCertificatePair in this case ?  The documentation is unclear on this.
http://www.grpc.io/grpc/csharp/html/T_Grpc_Core_SslServerCredentials.htm

Also, I only want the server to authenticate itself, do I need any special provision on the client gRPC call?

**Comment by jtattermusch** [comment]
I understand you want to generate a self signed certificate.  There should be enough examples on how to do that with openssl, but I agree we should improve our documentation as users tend to have trouble with that.

Would this example (from a grpc demo) be helpful?
https://github.com/grpc-ecosystem/grpc-exchange-o-gram/tree/master/certs

**Comment by jtattermusch** [comment]
Btw, under "server-side authentication" we usually understand that you want to authenticate the client on the server-side (e.g. check that the client has the right private cert). What you're doing is a more basic use case where you only check if the client is talking to the right server.

**Comment by AhmadChaker** [comment]
Thanks for that ! I ended up figuring out how to get it done using openSSL certificates.
I followed primarily this link:
http://stackoverflow.com/questions/37714558/how-to-enable-server-side-ssl-for-grpc
