### ISSUE TITLE
grpc_cpp_generator error

### ISSUE THREAD

**Issue by vnitinv** [grpc/grpc#1052]
[LD]      Linking libs/opt/libgrpc++_unsecure.so.0.5.0.0
[HOSTCXX] Compiling src/compiler/cpp_generator.cc
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::NoStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:54:19: error: ‘const MethodDescriptor’ has no member named ‘client_streaming’
   return !method->client_streaming() && !method->server_streaming();
                   ^
src/compiler/cpp_generator.cc:54:50: error: ‘const MethodDescriptor’ has no member named ‘server_streaming’
   return !method->client_streaming() && !method->server_streaming();
                                                  ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::ClientOnlyStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:58:18: error: ‘const MethodDescriptor’ has no member named ‘client_streaming’
   return method->client_streaming() && !method->server_streaming();
                  ^
src/compiler/cpp_generator.cc:58:49: error: ‘const MethodDescriptor’ has no member named ‘server_streaming’
   return method->client_streaming() && !method->server_streaming();
                                                 ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::ServerOnlyStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:62:19: error: ‘const MethodDescriptor’ has no member named ‘client_streaming’
   return !method->client_streaming() && method->server_streaming();
                   ^
src/compiler/cpp_generator.cc:62:49: error: ‘const MethodDescriptor’ has no member named ‘server_streaming’
   return !method->client_streaming() && method->server_streaming();
                                                 ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::BidiStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:66:18: error: ‘const MethodDescriptor’ has no member named ‘client_streaming’
   return method->client_streaming() && method->server_streaming();
                  ^
src/compiler/cpp_generator.cc:66:48: error: ‘const MethodDescriptor’ has no member named ‘server_streaming’
   return method->client_streaming() && method->server_streaming();
                                                ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::NoStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:55:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::ClientOnlyStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:59:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::ServerOnlyStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:63:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
src/compiler/cpp_generator.cc: In function ‘bool grpc_cpp_generator::{anonymous}::BidiStreaming(const MethodDescriptor*)’:
src/compiler/cpp_generator.cc:67:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
make: *** [objs/opt/src/compiler/cpp_generator.o] Error 1

gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

nitin@nitin-VirtualBox:~/grpc$ uname -a
Linux nitin-VirtualBox 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

nitin@nitin-VirtualBox:~/grpc$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2

i tried mac os, freebsd, centos, now ubuntu. Where will grpc compile properly???

**Comment by vnitinv** [comment]
step followed:
 $ git clone https://github.com/grpc/grpc.git
 $ cd grpc
 $ git submodule update --init
 $ make 
 $ sudo make install

You don't need anything else than GNU Make, gcc and autotools. Under a Debian
or Ubuntu system, this should boil down to the following packages:

**Comment by nicolasnoble** [comment]
That one looks like there's a mixup between protobuf libraries. Make sure you haven't two copies of the libprotobuf installed. Most probably hand-installed 3.0.0 and the typical 2.5.0-9ubuntu1.

**Comment by vnitinv** [comment]
with correct protobuf libraries, compilation succeed.
