### ISSUE TITLE
cloud_to_cloud:java interop tests fail on Master 

### ISSUE THREAD

**Issue by y-zeng** [grpc/grpc#10525]
cloud_to_cloud:java interop tests fail on Master since [12193](https://grpc-testing.appspot.com/job/gRPC_interop_master/12193/)

**Comment by apolcyn** [comment]
seen again https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13083/#showFailuresLink, looks like all cloud-cloud failed
