### ISSUE TITLE
Pure JavaScript version for Node.js.

### ISSUE THREAD

**Issue by alexfernandez** [grpc/grpc#10536]
Requiring compiling C or C++ code is not a great fit for a Node.js package. It makes using nvm a pain in the neck, for instance. Is there a pure JavaScript version planned? I know there are some third-party versions but they are not so great.

**Comment by tunatoksoz** [comment]
It will also make grpc on react native possible and easier.

**Comment by murgatroid99** [comment]
A pure JavaScript implementation of the Node.js library is now in development in the [grpc-node](https://github.com/grpc/grpc-node) repository.
