### ISSUE TITLE
"address family not supported" error from grpc v1.2.0

### ISSUE THREAD

**Issue by zefelise** [grpc/grpc#10532]
I'm running a simple grpc server with Nodejs on ubuntu:  docker image. My codes worked fine on grpc 1.1.2. Later I upgrade the grpc to 1.2.0+, the server fail to start then.

My server binding like bellow:
```
const address = '0.0.0.0:' + config.port;// port 50001
grpcServer.bind(address, grpc.ServerCredentials.createInsecure());
grpcServer.start();
```
Get failure on starting start from grpc v 1.2.0:
```
admin@15e9b95efcba:~/AnvilSolarAnalysisService$ node server.js
2017-04-08T03:17:24.719Z - info: Starting quantum/SolarAnalysis grpc on port: 50001
E0408 03:17:24.752963753     913 server_chttp2.c:53]         {"created":"@1491621444.752902712","description":"No address added out of total 1 resolved","file":"../src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":259,"referenced_errors":[{"created":"@1491621444.752895100","description":"Failed to add port to server","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":358,"referenced_errors":[{"created":"@1491621444.752846281","description":"Failed to bind to port","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":247,"os_error":"address family not supported"}]}]}
```

**Comment by explicitcall** [comment]
I am able to get exact same error with Python grpc 1.2.0

**Comment by JackmanGo** [comment]
I am able to get exact same error with Node grpc 1.2.0
E0420 16:35:26.462981842   10494 server_chttp2.c:53]         {"created":"@1492677326.462912917","description":"No address added out of total 1 resolved","file":"../src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":259,"referenced_errors":[{"created":"@1492677326.462906570","description":"Failed to add port to server","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":358,"referenced_errors":[{"created":"@1492677326.462851010","description":"Failed to bind to port","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":247,"os_error":"address family not supported"}]}]}

**Comment by leonlau** [comment]
I am able to get exact same error with Node grpc 1.2.x grpc 1.3.x

**Comment by leonlau** [comment]
any plans？

**Comment by sturadnidge** [comment]
Still happening with node 6.x and grpc 1.4.1... in case it makes a difference, I am trying to run the process up in a container.

```
ERR E0711 04:24:24.492460029      14 server_chttp2.c:53]         {"created":"@1499747064.492426241","description":"No address added out of total 1 resolved","file":"../src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":260,"referenced_errors":[{"created":"@1499747064.492420561","description":"Failed to add port to server","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":385,"referenced_errors":[{"created":"@1499747064.492415033","description":"Failed to bind to port","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":268,"os_error":"address family not supported"}]}]}
```

**Comment by mvollrath** [comment]
This message appears when I call `add_insecure_port('localhost:N')` presumably because `localhost` can resolve to ipv6 which Docker port forwarding is not friendly to.  Switching to a specifically ipv4 address like `127.0.0.1` prevents this error (but may or may not actually work).  A workaround would be to run your container with `--net=host` while developing locally.

If failure to bind the ipv6 address causes ipv4 binding to fail as well, that might be a GRPC bug, but it hasn't been proven here yet.

**Comment by thomas-lee** [comment]
I have similar error using node8.4 docker image & grpc 1.6

```
E0903 17:46:46.761521671      39 server_chttp2.c:38]         {"created":"@1504432006.761467804","description":"No address added out of total 1 resolved","file":"../src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":245,"referenced_errors":[{"created":"@1504432006.761452037","description":"Failed to add port to server","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":418,"referenced_errors":[{"created":"@1504432006.761437175","description":"Failed to bind to port","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":275,"os_error":"address not available"}]}]}

```
