### ISSUE TITLE
Python does not complain if wrong message type is used when fields match

### ISSUE THREAD

**Issue by JelteF** [grpc/grpc#10547]
The easiest example is to modify the helloworld example and add the following message:

```proto
// A clone of HelloRequest with an extra field
message HelloRequestUnused {
  string name = 1;
  string extra_field = 2;
}
```

Then modify `examples/python/helloworld/greeter_client.py` to send `HelloRequestUnused` instead of `HelloRequest`:
```python
response = stub.SayHello(helloworld_pb2.HelloRequestUnused(name='you'))
```

Running `greeter_client.py` will not result in a `ValueError`, but will instead just work as if a `HelloRequest` had been passed. This can be very confusing as unexpected behaviour will happen when passing a wrong type to the RPC by accident.

**Comment by JelteF** [comment]
A simple `isinstance` check on the passed value would probably be enough to fix this issue.

**Comment by nathanielmanistaatgoogle** [comment]
I think this is more of a Protocol Buffers issue than a gRPC issue, but without rerouting you to [the other issue tracker](https://github.com/google/protobuf/issues): I'm pretty sure this is as it is intended to be. While a little extra code here and there to detect and diagnose defects is in general a good thing, in this case the detection would take place on the super-optimized "hot path" of message serialization. I think it's likely the case that a dynamic check on the type of the message to be serialized has been considered and decided against.

@haberman or another member of the Protocol Buffers team might know more.

I think I'd be also against dynamic type-checking. Cases like these seems like the kind of problem that static type systems like [mypy](http://mypy-lang.org) or [pytype](https://github.com/google/pytype) should be solving.

**Comment by JelteF** [comment]
I really think it makes sense to check this. It's not as if types don't
exist in Python. It's quite common to throw a TypeError when the type does
not match the expected type. Passing the wrong message type to an rpc
really doesn't make any sense at all and can cause really weird bugs
especially if the field encoding is different. That it is in the hot path
doesn't make it any difference in my opinion, it's only a single isinstance
check not something complicated.

**Comment by nathanielmanistaatgoogle** [comment]
@JelteF: we have users that really care about everything that happens on the hot path, so adding something there would have to be really, really justified by some run-time need. [mypy](http://mypy-lang.org/) and [pytype](https://github.com/google/pytype) are still young and growing but aren't they the proper solution to this problem?

Also, if run-time type-checking were to be added, it would be added in Protocol Buffers Python (I think your "simple `isinstance` check on the passed value" would be inserted in the class-scope `SerializeToString` method), not gRPC Python. Have you filed a feature request in [the Protocol Buffers issue tracker](https://github.com/google/protobuf/issues)? What has the reaction there been?

**Comment by nathanielmanistaatgoogle** [comment]
Closing; I still believe that we're not going to take any action in this area and I am still almost certain that Protocol Buffers Python also will not. Too many users like their hot paths super-optimized and not executing any behavior that they needn't execute.
