### ISSUE TITLE
Using gRPC C++ with MFC in a shared DLL gives memory leaks

### ISSUE THREAD

**Issue by stefanopiovesan** [grpc/grpc#10546]
I am integrating gRPC in an Windows application that already uses third party libraries that need MFC in a shared DLL with VS2015. I cloned this version:

`git clone -b v1.1.x https://github.com/grpc/grpc
`

Then I build a Multi-threaded DLL (/MD) version of libprotobuf.lib and grpc++.lib and the helloworld example.
When I set Use standard Windows libraries the helloworld server gRPC example works fine.
When I set Use MFC in a shared DLL the helloworld server gRPC example works, but it exits with a lot of memory leaks (about 350 lines).

```
Dumping objects ->
{1475} normal block at 0x00000259F0CB9070, 22 bytes long.
Data: <G R P C _ T R A > 47 00 52 00 50 00 43 00 5F 00 54 00 52 00 41 00 
{1398} normal block at 0x00000259F0CB7D70, 30 bytes long.
Data: <G R P C _ V E R > 47 00 52 00 50 00 43 00 5F 00 56 00 45 00 52 00 
...
```
Also if I do not even start the server, I got all those memory leaks.
Is this gRPC+MFC combination possible?

**Comment by ctiller** [comment]
It's possible with some work... That we haven't done yet. We'd need a
configuration that's linking the same c runtime DLL that your mfc code
pulls in.

**Comment by stefanopiovesan** [comment]
I planned to use gRPC for our next 'mission critical' application. The prototype looks working, except for the memory leaks at the exit. And the memory looks stable when testing with many calls.
Should I give up gRPC, that looks great...? Have you any plan to fix it or could you give me some hint how to fix it by myself?

**Comment by Joev-** [comment]
We're also experiencing this issue with an MFC + gRPC C++ application. We are however using static linking and runtime. We've found that the bare minimum to get some memory leaks to show up is having the following line in our code:

```auto channel = grpc::CreateChannel(HostPort, grpc::InsecureChannelCredentials());```

This gives us leaks which include some gRPC strings (VER, TRA, etc). There are also some other leaks which are introduced by including the gRPC/Protobuf generated files in our compilation set. 

This isn't an immediate issue for us, but memory leaks are still concerning to see reported.

**Comment by kkm000** [comment]
Probable Xref: #10453

**Comment by kkm000** [comment]
This is certainly the same error as #10453. The leaked allocations are Unicode strings for environment variables GRPC_VERBOSITY and GRPC_TRACE, queried by gRPC. 14 and 10 characters respectively, plus one for the null terminator, two bytes per character = respective 30 and 22.
