### ISSUE TITLE
objc_macos_opt_native.objc-tests fail on MacOS while linking tests

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10554]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/4396/testReport/junit/(root)/objc_macos_opt_native/objc_tests/

```
> Linking AllTests
[!] ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
```

**Comment by adelez** [comment]
Found again in today's build. Then InteropTestsRemote testLargeUnaryRPC failed with timeout. Not sure if it's caused by the link error.
https://grpc-testing.appspot.com/job/gRPC_master_macos/2151/testReport/junit/(root)/objc_macos_opt_native/objc_tests/

> Linking AllTests
[!] ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
> Generating 'AllTests.xctest.dSYM'
> Copying TestCertificates.bundle
> Running script '[CP] Copy Pods Resources'
> Running script '[CP] Embed Pods Frameworks'
> Touching AllTests.xctest
** TEST FAILED **

Selected tests
Test Suite AllTests.xctest started
GRPCClientTests
    . testAlternateDispatchQueue (0.199 seconds)
    . testConnectionToRemoteServer (0.002 seconds)
    . testEmptyRPC (0.001 seconds)
    . testExceptions (0.001 seconds)
    . testIdempotentProtoRPC (0.002 seconds)
    . testMetadata (0.568 seconds)
    . testResponseMetadataKVO (0.002 seconds)
    . testSimpleProtoRPC (0.002 seconds)
    . testUserAgentPrefix (0.002 seconds)
InteropTestsLocalCleartext
    . test4MBResponsesAreAccepted (0.023 seconds)
    . testCancelAfterBeginRPC (0.002 seconds)
    . testCancelAfterFirstResponseRPC (0.003 seconds)
    . testClientStreamingRPC (0.003 seconds)
    . testEmptyStreamRPC (0.003 seconds)
    . testEmptyUnaryRPC (0.003 seconds)
    . testLargeUnaryRPC (0.005 seconds)
    . testPacketCoalescing (0.003 seconds)
    . testPingPongRPC (0.005 seconds)
    . testResponsesOver4MBAreAcceptedIfOptedIn (0.026 seconds)
    . testResponsesOverMaxSizeFailWithActionableMessage (0.007 seconds)
    . testRPCAfterClosingOpenConnections (0.005 seconds)
    . testServerStreamingRPC (0.004 seconds)
InteropTestsLocalSSL
    . test4MBResponsesAreAccepted (0.314 seconds)
    . testCancelAfterBeginRPC (0.002 seconds)
    . testCancelAfterFirstResponseRPC (0.012 seconds)
    . testClientStreamingRPC (0.015 seconds)
    . testEmptyStreamRPC (0.009 seconds)
    . testEmptyUnaryRPC (0.010 seconds)
    . testExceptions (0.002 seconds)
    . testLargeUnaryRPC (0.041 seconds)
    . testPacketCoalescing (0.010 seconds)
    . testPingPongRPC (0.021 seconds)
    . testResponsesOver4MBAreAcceptedIfOptedIn (0.666 seconds)
    . testResponsesOverMaxSizeFailWithActionableMessage (0.017 seconds)
    . testRPCAfterClosingOpenConnections (0.018 seconds)
    . testServerStreamingRPC (0.012 seconds)
InteropTestsRemote
    . test4MBResponsesAreAccepted (1.154 seconds)
    . testCancelAfterBeginRPC (0.033 seconds)
    . testCancelAfterFirstResponseRPC (0.633 seconds)
    . testClientStreamingRPC (0.646 seconds)
    . testEmptyStreamRPC (0.942 seconds)
    . testEmptyUnaryRPC (0.462 seconds)
    x testLargeUnaryRPC, Asynchronous wait failed: Exceeded timeout of 32 seconds, with unfulfilled expectations: "LargeUnary".
    . testPacketCoalescing (0.446 seconds)
    . testPingPongRPC (1.081 seconds)
    . testResponsesOver4MBAreAcceptedIfOptedIn (1.193 seconds)
    . testResponsesOverMaxSizeFailWithActionableMessage (0.562 seconds)
    . testRPCAfterClosingOpenConnections (0.913 seconds)
    . testServerStreamingRPC (0.624 seconds)
RxLibraryUnitTests
    . testBufferedPipeFinishWriteWhilePaused (0.000 seconds)
    . testBufferedPipePropagatesError (0.000 seconds)
    . testBufferedPipePropagatesValue (0.000 seconds)
    . testWriteableSingleHandlerFailsOnEmptyWriter (0.000 seconds)
    . testWriteableSingleHandlerIsCalledForError (0.000 seconds)
    . testWriteableSingleHandlerIsCalledForValue (0.000 seconds)
    . testWriteableSingleHandlerIsCalledOnlyOnce_ValueThenError (0.000 seconds)
    . testWriteableSingleHandlerIsCalledOnlyOnce_ValueThenValue (0.001 seconds)


InteropTestsRemote
  testLargeUnaryRPC, Asynchronous wait failed: Exceeded timeout of 32 seconds, with unfulfilled expectations: "LargeUnary".
  /jenkins/workspace/gRPC_master_macos/workspace_objc_macos_opt_native/src/objective-c/tests/InteropTests.m:158
  ```

  [self waitForExpectationsWithTimeout:TEST_TIMEOUT handler:nil];
}
  ```


	 Executed 57 tests, with 1 failure (0 unexpected) in 42.774 (43.016) seconds
kill -9 `jobs -p` ; echo "EXIT TIME:  $(date)"
jobs -p
date
EXIT TIME:  Fri Apr 21 14:26:24 PDT 2017

**Comment by apolcyn** [comment]
same link error appears in latest macos master runs:

from the bottom of the log:

```
> Building Tests/AllTests [Test]
> Check Dependencies
> Running script '[CP] Check Pods Manifest.lock'
> Linking AllTests
[!] ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
> Generating 'AllTests.xctest.dSYM'
> Copying TestCertificates.bundle
> Running script '[CP] Copy Pods Resources'
> Running script '[CP] Embed Pods Frameworks'
> Touching AllTests.xctest
** TEST FAILED **

kill -9 `jobs -p` ; echo "EXIT TIME:  $(date)"
jobs -p
date
EXIT TIME:  Mon Apr 24 03:58:30 PDT 2017
```

log in https://grpc-testing.appspot.com/job/gRPC_master_macos/2176/testReport/junit/(root)/objc_macos_dbg_native/objc_tests/

**Comment by dgquintas** [comment]
Not seen for a month, closing.
