### ISSUE TITLE
Binary Compatible gRPC for Alpine Linux

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#10560]
https://github.com/grpc/grpc/pull/10407
Allowed gRPC to compile on Alpine Linux (musl libc).

It would be nice if gRPC was cross compatible when built against glibc.  This would require getting around sched_getcpu and swapping memcpy with memmove.

**Comment by kpayson64** [comment]
This is fundamentally impossible, GRPC_MSG_IOVLEN_TYPE is incompatible.

On musl (and mac), it conforms to the posix standard as being an int.  But for glibc, it is a size_t.

**Comment by ctiller** [comment]
What if we used writev in tcp_posix.c?

**Comment by kpayson64** [comment]
@ctiller 
Scanning the linux/posix documentation, it looks like that might work.

**Comment by jtattermusch** [comment]
I think this works now, feel free to reopen if more work needs to be done.
