### ISSUE TITLE
Node grpc getConnectivityState value check

### ISSUE THREAD

**Issue by zhihanhe** [grpc/grpc#10569]
I'm using grpc in node.But when I want to check connect state, using client.$channel.getConnectivityState(true). but can not get value to check state.
I have to log src/node/src/client.js's code: grpc.connectivityState.
got:
IDLE : 0
CONNECTING : 1
READY : 2
TRANSIENT_FAILURE : 3
FATAL_FAILURE : 4

so use :

const state = client.$channel.getConnectivityState(true);
if (state >= 3) // try reconnect

I can not use  grpc.connectivityState outside src code.Is this a right way to check grpc's connect state?

**Comment by robertwpowell** [comment]
Have you tried client.getChannel().getConnectivityState(true); 
getChannel() is the accessor for getting channel. I'm inspecting it when waitforReady times out to see the connection state

**Comment by murgatroid99** [comment]
Can you explain why you you are trying to check the connectivity state? Normally, handling disconnections and reconnecting are handled by the gRPC internals. Are you having a connectivity issue that isn't being handled properly?

**Comment by robertwpowell** [comment]
I'm checking the connectivity state of service A for a heartbeat service that provides the state of service A so that clients will know if they should continue to call the service or its truly down and to stop calling the service and disable the feature/s that the service supports.
