### ISSUE TITLE
Enabling gRPC traces needs two env vars to be set

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10575]
Two environment variables (GRPC_TRACE and GRPC_VERBOSITY) need to be set to see traces. 

No one external has ever gotten this right when trying for the first time - I've helped quite a few users already. We need to make GRPC_TRACE easier to use.

**Comment by ncteisen** [comment]
Trace allows users to toggle which systems to examine, and verbosity sets the level. How do you see these being merged into one?

I understand the problem that this can be complex for someone starting out with gRPC, but once it is understood, the granularity of configuration should allow quicker debugging.

How about this proposal. setting GRPC_VERBOSITY to `ALL` will have the same effect as setting GRPC_TRACE to `all` and GRPC_VERBOSITY to `DEBUG`. I.e. maximum log dumping. That way if we want logs from a user, they only have to set one env var.

**Comment by jtattermusch** [comment]
I don't have any hard opinions on this, but it could be as simple as printing a warning if GRPC_TRACE is set and GRPC_VERBOSITY is not set.
Can there be traces of different verbosities or all traces are at the debug level?

**Comment by ncteisen** [comment]
The core supports DEBUG, INFO, and ERROR, with all being used just about equally (444, 518, 470 respectively)

**Comment by jtattermusch** [comment]
It doesn't look like there are any plans to do anything about this.
