### ISSUE TITLE
failed to build grpc++_reflection as external target in bazel

### ISSUE THREAD

**Issue by lightyang** [grpc/grpc#10596]
When using grpc as an external repository (com_github_grpc_grpc), bazel failed to build grpc++_reflection:
```
bazel-out/local-fastbuild/genfiles/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc:5:91: fatal error: external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/reflection.pb.h: No such file or directory
 #include "external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/reflection.pb.h"
```

The generated code has an include path relative to `bazel-out/local-fastbuild/genfiles` while bazel uses `-iquote bazel-out/local-fastbuild/genfiles/external/com_github_grpc_grpc` when compiling the code.

For now I work around this by adding `bazel-out/local-fastbuild/genfiles` to my include paths.

**Comment by pcj** [comment]
@lightyang How did you implement the workaround?

**Comment by lightyang** [comment]
@pcj well, I just added `build --copt -Ibazel-out/local-fastbuild/genfiles` in my bazelrc

**Comment by gkelly** [comment]
The issue appears to be that when `generate_cc` constructs the `-I` mappings for the proto files that it includes the repository path.  If you look at [ProtoCompileActionBuilder.java:344](https://github.com/bazelbuild/bazel/blob/fd1140bf699eebcd1bb520e28a427e62d3540f76/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCompileActionBuilder.java#L344) from bazel (which is how it invokes `protoc` for `proto_library` rules) you'll see that it maps the path to the artifact less the respository path to the actual source file.  I'll prepare a change here that replicates that behavior.

**Comment by minorhacks** [comment]
@gkelly - you mentioned in #11351 you have a fix/workaround for this issue? Unfortunately the bazelrc fix won't work for me because it won't work for debug/opt/cross-compiled builds.

**Comment by kerrick-lyft** [comment]
Was this fixed?
