### ISSUE TITLE
Cross compile with gcc-linaro-arm-linux-gnueabihf-4.8-2013.12_linux

### ISSUE THREAD

**Issue by cybersquib** [grpc/grpc#10603]
make HAS_PKG_CONFIG=false PROTOBUF_CONFIG_OPTS="--host=arm-linux-gnueabihf --with-protoc=/usr/bin/protoc" CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ RANLIB=arm-linux-gnueabihf-gcc-ranlib LD=arm-linux-gnueabihf-ld static

delivers:
...
libtool: link: arm-linux-gnueabihf-ar cru .libs/libprotobuf-lite.a  google/protobuf/stubs/atomicops_internals_x86_gcc.o google/protobuf/stubs/atomicops_internals_x86_msvc.o google/protobuf/stubs/bytestream.o google/protobuf/stubs/common.o google/protobuf/stubs/int128.o google/protobuf/stubs/once.o google/protobuf/stubs/status.o google/protobuf/stubs/statusor.o google/protobuf/stubs/stringpiece.o google/protobuf/stubs/stringprintf.o google/protobuf/stubs/structurally_valid.o google/protobuf/stubs/strutil.o google/protobuf/stubs/time.o google/protobuf/arena.o google/protobuf/arenastring.o google/protobuf/extension_set.o google/protobuf/generated_message_util.o google/protobuf/message_lite.o google/protobuf/repeated_field.o google/protobuf/wire_format_lite.o google/protobuf/io/coded_stream.o google/protobuf/io/zero_copy_stream.o google/protobuf/io/zero_copy_stream_impl_lite.o
libtool: link: arm-linux-gnueabihf-gcc-ranlib .libs/libprotobuf-lite.a
sorry - this program has been built without plugin support
Makefile:2173: recipe for target 'libprotobuf-lite.la' failed
make[4]: *** [libprotobuf-lite.la] Error 1
make[4]: Leaving directory '/home/pf/Projects/OpenSource/grpc_cross_compile/grpc/third_party/protobuf/src'
Makefile:2023: recipe for target 'all' failed
m

**Comment by cybersquib** [comment]
Before, make plugins delivered:
pf@lbfb:~/Projects/OpenSource/grpc_cross_compile/grpc$ make plugins
[HOSTLD]  Linking /home/pf/Projects/OpenSource/grpc_cross_compile/grpc/bins/opt/grpc_cpp_plugin
/usr/bin/ld: skipping incompatible libs/opt/libz.a when searching for -lz
/home/pf/Projects/OpenSource/grpc_cross_compile/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `std::vector<int, std::allocator<int> >::push_back(int const&)':
/usr/include/c++/4.9/bits/stl_vector.h:923: undefined reference to `google::protobuf::FileDescriptorProto::kSyntaxFieldNumber'
/usr/include/c++/4.9/bits/stl_vector.h:923: undefined reference to `google::protobuf::FileDescriptorProto::kSyntaxFieldNumber'
/home/pf/Projects/OpenSource/grpc_cross_compile/grpc/objs/opt/src/compiler/cpp_plugin.o:(.data.rel.ro._ZTV16CppGrpcGenerator[_ZTV16CppGrpcGenerator]+0x14): undefined reference to `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::string const&, google::protobuf::compiler::GeneratorContext*, std::string*) const'
collect2: error: ld returned 1 exit status
Makefile:13812: recipe for target '/home/pf/Projects/OpenSource/grpc_cross_compile/grpc/bins/opt/grpc_cpp_plugin' failed

**Comment by nicolasnoble** [comment]
That seems to be more of a protobuf issue than a grpc issue. Another better way is to cross-compile protobuf and provide it externally instead of relying on the built-in build system we have. You may have better luck that way, and maybe even more insights of what the actual issue is.
