### ISSUE TITLE
build_docker_csharpcoreclr fail to build

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10608]
Happened in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13186/console

Looks like a dependency is broken:
```
error: Unable to resolve 'System.Collections.Specialized (>= 4.0.1)' for '.NETCoreApp,Version=v1.0'.
```

**Comment by jtattermusch** [comment]
Looks like a transient issue, on recent interop PR build, the docker image is building without problems.

**Comment by jtattermusch** [comment]
Please reopen if seen again.
