### ISSUE TITLE
run_tests_csharp_macos_opt_native fails after all tests passed

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10610]
Happened in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/4493/testReport/junit/(root)/aggregate_tests/run_tests_csharp_macos_opt_native/
```
2017-04-12 00:51:32,859 SUCCESS: All tests passed
tools/run_tests/helper_scripts/run_tests_in_workspace.sh: line 47: 67916 Alarm clock: 14         python "${WORKSPACE_NAME}/tools/run_tests/run_tests.py" $@
```

**Comment by jtattermusch** [comment]
Should be fixed by https://github.com/grpc/grpc/pull/11520.
