### ISSUE TITLE
(php)can't run ./bin/interop_client.sh

### ISSUE THREAD

**Issue by haphy** [grpc/grpc#1062]
./bin/interop_client.sh --server_host 127.0.0.1 --server_port 9000 --test_case large_unary
D0317 12:04:27.795528470   18090 channel.c:167] Initialized secure channel
Connecting to 127.0.0.1:9000
Running test case large_unary
E0317 12:04:27.890322617   18091 tcp_client_posix.c:145] socket error: connection refused
E0317 12:04:28.990354110   18091 tcp_client_posix.c:145] socket error: connection refused

**Comment by nicolasnoble** [comment]
I know it may sounds like "did you try to turn it on and off", but can you confirm you're running an interop server on your machine on port 9000 ?

**Comment by haphy** [comment]
how to run an interop server？I didn't find in directory ‘src/php’

**Comment by nicolasnoble** [comment]
As the name implies, the interop test means testing grpc across multiple languages or implementations. You can compile the C++ interop server by doing `make interop_server`. This will give you a C++ interop server in bins/opt/interop_server.

You can run it with the following:

```
$ ./bins/opt/interop_server -port 9000 -enable_ssl
```

And then you can run the interop php client.

**Comment by haphy** [comment]
:+1: .Thanks.I want to ask another question.How to use PHP to run server for testing?The example is only for grpc client.

**Comment by nicolasnoble** [comment]
I don't think we have that option at the moment, but @murgatroid99 will answer that for you better than I can.

**Comment by murgatroid99** [comment]
So, there are two issues here: first, the PHP implementation of gRPC does not currently work. There is an open pull request (#1014) to fix most of it, but even then, there are still a couple of issues. Second, there is no high-level server implementation for PHP, and I don't know if there are plans to write one. So, there isn't any easy way to run a PHP interop server.

**Comment by murgatroid99** [comment]
Update: The PHP implementation of gRPC now works, but there is still no PHP server, and there is currently no plan to make one. The PHP interop tests are generally run against the servers written in other langauges.

**Comment by stanley-cheung** [comment]
As we are approaching Beta, this should have been working for a while now.
