### ISSUE TITLE
Error handling on Server sync streaming

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#10635]
I'm trying to use server-side streaming. But I have questions about how to handle the error.
1.  In server-side, I want to know how to handle when ServerWriter::Write returns false.
2. In client-side, I want to know if there is required error handling to do.
Can anyone give me some error handling examples or real world projects that using grpc streaming?

**Comment by yang-g** [comment]
1. If your ServerWriter returns false on Write, consider the stream failed and return from the server handler.
2. At the client side if the rpc status is not ok, then you need to decide according to application logic. Maybe you want to re-issue the rpc or do something else.

**Comment by yyh-graphsql** [comment]
Thanks. Very interesting to meet the stupid questions posted more than half years ago.
