### ISSUE TITLE
Deepcopy of RepeatedCompositeContainer

### ISSUE THREAD

**Issue by bradmwalker** [grpc/grpc#10632]
Can RepeatedCompositeContainer support `__deepcopy__`? (Python 3.6 and grpcio-1.2.1)

I want to write unit tests against gRPC response snapshots persisted as bytes via ParseToString(). For the sake of more readable tests and clean gRPC client APIs (e.g. unwrapping responses), a protobuf message document should be deep-copyable at any level.

Some unit tests mutate a deepcopy of a gRPC deserialized response to simulate state transitions over multiple gRPCs with changing responses. Non-repeated protobuf messages can be deep copied, but a reference to a "repeated" proto (RepeatedCompositeContainer) cannot. A TypeError ("can't pickle google.protobuf.pyext._message.RepeatedCompositeContainer") occurs when deepcopy tries to pickle the object.

**Comment by nathanielmanistaatgoogle** [comment]
This sounds like a very valid feature request... in the wrong issue tracker. While you encountered the need for this while using gRPC, this appears to be more about Protocol Buffers. Please refile your request [over there](https://github.com/google/protobuf/issues)?

I apologize for the reroute. Also consider including sample code in your report?
