### ISSUE TITLE
Bad directory name choice for "core"

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#1064]
May want to reconsider using the name "core" as a directory name in src/grpc since Linux coredumps have the same name.... Looking for the filename "*core*" points down this path.

**Comment by nicolasnoble** [comment]
So we talked about this at some point, but since it's not in the root folder, or nearby the location of the binaries, where the actual cores would get generated, is it really an issue other than potential confusion when running `find . -name core` ?

**Comment by vjpai** [comment]
That's the only time that I can think of. Just did it myself while looking for a core.

**Comment by vjpai** [comment]
This does not seem that important. I'll close it.
