### ISSUE TITLE
Java and Go custom_metadata interop tests failing against core-based languages

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#10640]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13267

Many of the failure messages mention NUL bytes in metadata.

**Comment by ejona86** [comment]
Yeah, seems like C's fault. Removing everyone but @ctiller from assignees.
```
Caused by: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0x0
```

**Comment by markdroth** [comment]
I'm guessing that this is obsolete.  Please re-open if that's not the case.

**Comment by ejona86** [comment]
Yes. I think this was a bug with the binary metadata implementation in C, which has long been fixed.
