### ISSUE TITLE
C# Received message larger than max 4194304

### ISSUE THREAD

**Issue by yjpgfwxf** [grpc/grpc#10657]
I am using grpc for message passing and am testing a simple server and client. When my message size goes over the limit, I get this error

Status(StatusCode=InvalidArgument, Detail="Received message larger than max (4450581 vs. 4194304)")

Client 
     var channel = new Channel(target, ChannelCredentials.Insecure, new List<ChannelOption> {
                                new ChannelOption(ChannelOptions.MaxMessageLength,int.MaxValue) });
Server 
    Grpc.Core.Server server = new Grpc.Core.Server(new List<ChannelOption> {
                                new ChannelOption(ChannelOptions.MaxMessageLength,int.MaxValue) })

grpc version 1.1

**Comment by jtattermusch** [comment]
The channel option name has been changed in C core recently. 
C# has been fixed by https://github.com/grpc/grpc/pull/10124 

Try upgrading to gRPC C# 1.2.2 which has this fix.
