### ISSUE TITLE
Collect data on test times

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10666]
Each time run_tests.py is run, for each test:
- collect the test name, start time, stop time, success/failure/timeout status, cpu cost (estimated and measured), jenkins job (and build number), configuration, language, etc...
- batch together as a csv, and at the end of the run, upload to bigquery

This should quickly give us a (dashboardable) data set on which tests are fragile, which tests are configured to consume way more cpu than they need, etc...

**Comment by matt-kwong** [comment]
So most of this data is already available in the Jenkins UI (e.g. https://grpc-testing.appspot.com/job/gRPC_master_linux/2108/testReport/(root)/c++_linux_dbg_native/). It's missing the CPU cost/estimated but that might be easy to add to the JUnit XML? 

I think a dashboard could easily be built by running a continuous Jenkins job that scrapes master jobs' results and stores in BQ. We already did something similar to this, so I could put some time to make this.

**Comment by matt-kwong** [comment]
Actually I reread your post, and I think adding a flag to run_tests.py to upload results to BQ would be better.

**Comment by ctiller** [comment]
Yeah it could re-use a bunch of machinery, but it'd be great to have it
somewhere that's queryable... I've found it to be hugely beneficial for
general performance work.

**Comment by matt-kwong** [comment]
This has been done and works on Kokoro as well :)
