### ISSUE TITLE
[c#] [test] Mocking ServerCallContext

### ISSUE THREAD

**Issue by olivif** [grpc/grpc#10675]
I am trying to unit test my server class and having trouble mocking  `ServerCallContext`. 

Here's the method I am trying to unit test.

```cs
public override Task<KeyValueMessage> GetValue(KeyMessage request, ServerCallContext context)
{
    // some implementation
}
```

I tried creating the context myself but there is no public constructor. 

I also tried mocking it using `Moq` and `Mock<ServerCallContext>` but that fails for the same reason. 

Any ideas?

**Comment by jtattermusch** [comment]
Currently, there is no way to mock ServerCallContext (and some other classes as well). We might expose the constructors at some point (the worry is not to break the public API), but until then you can setup your tests in a way that doesn't involve ServerCallContext (you should be testing your application logic, not emulating gRPC's behavior).

**Comment by juanjoDiaz** [comment]
Any news on this?

It is a real problem since my application logic might depend on headers passed in the context and there is no way to write reliable tests.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/15214 should address this, it will be on the next release (v1.13.x)
