### ISSUE TITLE
pre_build_csharp failed

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#10685]
https://grpc-testing.appspot.com/job/gRPC_pr_win/4535/

The failure seems to be associated with messages like this:

```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 

  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by jtattermusch** [comment]
Duplicate of https://github.com/grpc/grpc/issues/10667.
