### ISSUE TITLE
Error building gRPC on alpine

### ISSUE THREAD

**Issue by ekarlso** [grpc/grpc#10680]
https://github.com/ekarlso/alpine-grpc is the code and when I run it either for armhf or the alpine:3.5 I get:
[C]       Compiling src/core/lib/security/transport/client_auth_filter.c
[C]       Compiling src/core/lib/security/transport/lb_targets_info.c
[C]       Compiling src/core/lib/security/transport/secure_endpoint.c
[C]       Compiling src/core/lib/security/transport/security_connector.c
[C]       Compiling src/core/lib/security/transport/security_handshaker.c
[C]       Compiling src/core/lib/security/transport/server_auth_filter.c
[C]       Compiling src/core/lib/security/transport/tsi_error.c
[C]       Compiling src/core/lib/security/util/b64.c
[C]       Compiling src/core/lib/security/util/json_util.c
[C]       Compiling src/core/lib/surface/init_secure.c
[C]       Compiling src/core/lib/tsi/fake_transport_security.c
In file included from ./src/core/lib/tsi/transport_security_interface.h:38:0,
                 from ./src/core/lib/security/transport/security_connector.h:42,
                 from ./src/core/lib/security/credentials/credentials.h:45,
                 from src/core/lib/surface/init_secure.c:40:
/usr/include/fortify/stdlib.h: In function 'realpath':
/usr/include/fortify/stdlib.h:42:2: error: #error PATH_MAX unset. A fortified realpath will not work.
 #error PATH_MAX unset. A fortified realpath will not work.
  ^~~~~
make: *** [Makefile:2366: /home/builder/package/src/grpc-1.2.3/objs/opt/src/core/lib/surface/init_secure.o] Error 1
make: *** Waiting for unfinished jobs....
>>> ERROR: grpc: all failed
>>> grpc: Uninstalling dependencies...

**Comment by kpayson64** [comment]
Do you mind trying to build from HEAD? (without the patch)

https://github.com/grpc/grpc/pull/10407 should have fixed these issues.

**Comment by ekarlso** [comment]
[C]       Compiling src/core/lib/support/time_windows.c
[C]       Compiling src/core/lib/support/tmpfile_msys.c
[C]       Compiling src/core/lib/support/tls_pthread.c
[C]       Compiling src/core/lib/support/tmpfile_posix.c
[C]       Compiling src/core/lib/support/tmpfile_windows.c
[C]       Compiling src/core/lib/support/wrap_memcpy.c
[C]       Compiling src/core/lib/surface/init.c
[C]       Compiling src/core/lib/channel/channel_args.c
[C]       Compiling src/core/lib/channel/channel_stack.c
In file included from include/grpc/compression.h:39:0,
                 from src/core/lib/channel/channel_args.c:37:
/usr/include/fortify/stdlib.h: In function 'realpath':
/usr/include/fortify/stdlib.h:42:2: error: #error PATH_MAX unset. A fortified realpath will not work.
 #error PATH_MAX unset. A fortified realpath will not work.
  ^~~~~
make: *** [Makefile:2489: /home/builder/package/src/grpc/objs/opt/src/core/lib/channel/channel_args.o] Error 1
make: *** Waiting for unfinished jobs....
>>> ERROR: grpc: all failed
>>> grpc: Uninstalling dependencies...


At least now it's a new place by the looks :)

**Comment by ekarlso** [comment]
@kpayson64 any ideas on what it is failing on now?

**Comment by kpayson64** [comment]
@ekarlso 
I confirmed the issue on alpine:edge.

I think we will explicitly define #PATH_MAX when building on Alpine, I tried including limits.h to no avail.

**Comment by ekarlso** [comment]
Ok, ETA on a fix ? :)

**Comment by kpayson64** [comment]
The fix for master is here: https://github.com/grpc/grpc/pull/10800

The v1.3.x branch should already work.  The protobuf dependency won't compile until they release 3.3.0.
