### ISSUE TITLE
The master performance tests appear to not be working

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#10690]
The dashboard that is supposed to have data from that test is empty: http://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

**Comment by matt-kwong** [comment]
I just fixed an issue with gRPC-Go not being able to be built on the performance VM. It looks like data is starting to populate the graphs, but I'll keep this issue open until the graphs start to look normal.

**Comment by matt-kwong** [comment]
The graphs each have a week of data, so I'm closing this issue.
