### ISSUE TITLE
Python support for custom TLS verification options

### ISSUE THREAD

**Issue by wisotzky** [grpc/grpc#10701]
I am to write a gNMI Telemetry receiver in Python. Due to gNMI authentication guidelines, this is using TLS auth and encryption.

OpenConfig provides an example in GO using the older openconfig specs:
https://github.com/openconfig/reference/blob/master/telemetry/collector/cli/main.go

Just wondering, how to do the following in Python:
1) Set "InsecureSkipVerify" option to not validate the server certificate against root certificate.
2) Set "ServerHostOverride" attribute, for example in cases where struggling with aliases or DNS
3) Set cipher-list from python (only found how to do this using environment)
4) Set logging/debug options from python (only found how to do this using environment)

Any help on this one?

**Comment by wisotzky** [comment]
Items 2) and 3) are fixed now:
2. Using channel option "grpc.ssl_target_name_override"
3. Use os.environ["GRPC_SSL_CIPHER_SUITES"] = "xxxxx"

Anyhow, I did not yet found a solution for 1) and 4). Interesting enough, even if I change the environment using "os.environ" gRPC logging is not getting enabled. Python code:
        os.environ["GRPC_TRACE"] = "all"
        os.environ["GRPC_VERBOSITY"] = "DEBUG"

**Comment by wisotzky** [comment]
What I am actually looking for, is an equivalent for the following python code:

```
import ssl
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.options |= ssl.OP_NO_SSLv2
context.options |= ssl.OP_NO_SSLv3
context.options |= ssl.OP_NO_COMPRESSION
context.set_ciphers("AES128")

if secure:
  context.verify_mode = ssl.CERT_REQUIRED
  context.check_hostname = True
else:
  context.verify_mode = ssl.CERT_NONE
  context.check_hostname = False
```

For me it seems, we don't have native access to those SSL/TLS related objects from python, as the python module for grpc is using the native C library as backend. Therefore potentially the answer is, to use the "grpc.socket_mutator" for this. Anyhow, I haven't found any example on how to use the socket_mutator - and even unclear on how to provide GRPC_ARG_POINTER from python.

**Comment by wisotzky** [comment]
Beside of the "GO" example mentioned in my original description, the GRPC documentation contains a reference on [how to do this in JAVA](http://www.grpc.io/docs/guides/auth.html#with-server-authentication-ssltls-4):

> If the issuing certificate authority is not known to the client then a properly configured SslContext or SSLSocketFactory should be provided to the NettyChannelBuilder or OkHttpChannelBuilder, respectively.

**Comment by wisotzky** [comment]
In consequence, if there is no ability to provide those SSL options using python today, I would ask to add the following to the next GRPC maintenance release:

1. Extend [Environment Options](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) for GRPC Clients:
```
GRPC_SSL_CERT_REQUIRED = True | False
GRPC_SSL_CHECK_HOSTNAME = True | False
```

2. Extend [GRPC Channel Options](http://www.grpc.io/grpc/core/group__grpc__arg__keys.html):
```
grpc.cert_required = 0 | 1
grpc.check_hostname = 0 | 1
grpc.cipher_suite = "<string>"
````

3. Extend [GRPC Auth Guide](https://github.com/grpc/grpc.github.io/blob/master/docs/guides/auth.md):
Add info, how to set TLS options in python.

4. Add API to enable GRPC logging from python

5. Improve logging and error codes
For example if cipher suites do not match between server and client

**Comment by nathanielmanistaatgoogle** [comment]
Setting `GRPC_TRACE` and `GRPC_VERBOSITY` should certainly work. Have you tried rather than setting them from inside your python code, setting them when you invoke the Python interpreter?

@jboeuf: what do you think of the security feature requests here?

**Comment by jboeuf** [comment]
Sorry @wisotzky but I'm very much not in favor of adding these features which degrade security and provide our users more ways to shoot themselves in the foot. In particular, I will not approve of an option that does "InsecureSkipVerify" as experience has shown me that these types of features are triggered in test environments because it's practical and then shipped to prod because everyone forgets about them.

On the cipher suite bit, gRPC/HTTP2/TLS stack must support the TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite as per http://httpwg.org/specs/rfc7540.html#rfc.section.9.2.2.
The env var trick is mostly for users who want better cipher suites which would be preferred than that one but I understand the potential abuse for this which is unfortunate.

Regarding debugging, this is more of a gRPC request than a security one. It looks like the core `grpc_tracer_set_enabled` function would make it easier to be controllable directly with python (or any wrapped languages). @ctiller do you agree with that?

**Comment by wisotzky** [comment]
@jboeuf, you've indicated - having the options (1) not to validate the server certificate against the CA root certificate and (2) not to validate the subjectAltName/CN against the server hostname/ip-address should only be used lab/testing. But I would add "during development" and "for trouble-shooting purposes" as other potential applications.

Saying this, I am NOT convinced that gRPC should dictate how application MUST implement security features, while I am okay, that gRPC enforces security by default. If you want to write an application which enforces security - developers should just use default settings, and they are done. If you want to write a validation/troubleshooting tool or provide those options to a more sophisticated application, I want to have all the options. Please remind, that most web-browser allow you to accept self-signed certificates - so unclear, why this should not be possible for web-applications.

**Comment by wisotzky** [comment]
@jboeuf, about tweaking cipher suites - I would not consider this as "abuse". Depending on the server implementation, there are some HTTP/2 over TLS 1.2 stacks - which simply do not support the TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite. Even this is violating rfc7540 there are some environments where this cannot easily be changed (for example: java8 does not support ECDHE cipher suites).

**Comment by wisotzky** [comment]
@nathanielmanistaatgoogle @jboeuf @ctiller 
I do not like change environment variables from python to manipulate parameters like client cipher-suites and logging/debugging. Even if I change the environment from python it is unclear, if those changes make it to become active. In my early testing, I've had sometimes the feeling that environment variables must be set before importing grpc - else those changes are simply ignored.

The preferred solution is clearly to use the environment to define/overwrite defaults - but allow the actual process to overwrite any of this as needed. Also keep in mind, that sometimes processes run over hours/days and you might want to increase/decrease log-levels or change other settings during run time. This is basically impossible, if those values need to be set before the library is imported.

Also I would prefer if grpc/tls logging would use a wrapper, to use the standard python logger for this. Some people including me prefer to write debug logs into files and influence the log-format. It is rather unclear how to do this with grpc, as everything is just dumped to the terminal session in its predefined format.
