### ISSUE TITLE
Add support for SSL credentials validation callback

### ISSUE THREAD

**Issue by JackOfMostTrades** [grpc/grpc#10721]
The node.js https library exposes [checkServerIdentity()](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) callback so that developers can apply custom validation logic to the server's presented certificate. The python requests library has a similar [cert_verify](http://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter.cert_verify) method that can be overridden to apply custom validation. I'm sure examples exist for other languages, but those are the ones I know of off the top of my head.

The most common use case I've heard described is to do cert pinning. In our case, we need to be able to do custom host name validation because our server certificates encode multiple dimensions of data in proprietary x509 extensions that some clients want to inspect.

OpenSSL provides a callback interface to which grpc-core is [currently](https://github.com/grpc/grpc/blob/master/src/core/tsi/ssl_transport_security.c#L1346) just passing a hardcoded NULL. It would be nice if this was exposed as an option all the way up to the sslcredentials libraries.

**Comment by jboeuf** [comment]
Please see the discussion in #7834 on this topic. 
I thought more about this and we could indeed add a plugin for **extra** validation of the server cert. What I don't want to do though is to allow clients to use this mechanism to bypass the normal HTTPS checks.

**Comment by JackOfMostTrades** [comment]
This sounds reasonable to me. The intent here is to be able to perform checks against additional certificate fields, not to bypass any existing checks.
