### ISSUE TITLE
Ruby Segfault

### ISSUE THREAD

**Issue by tonobo** [grpc/grpc#10726]
```
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

E0419 11:51:45.377944567 1635252 ev_epoll_linux.c:1444]      pollset_kick: {"created":"@1492595505.377841581","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"created":"@1492595505.377832056","description":"OS Error","errno":3,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1357,"os_error":"No such process","syscall":"pthread_kill"}]}
E0419 11:51:45.378002078 1635252 completion_queue.c:267]     Kick failed: {"created":"@1492595505.377841581","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"created":"@1492595505.377832056","description":"OS Error","errno":3,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1357,"os_error":"No such process","syscall":"pthread_kill"}]}
/var/lib/gems/2.3.0/gems/grpc-1.2.2-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:337: [BUG] Segmentation fault at 0x007f140d7225f0
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0036 p:---- s:0169 e:000168 CFUNC  :run_batch
c:0035 p:0084 s:0165 e:000164 METHOD /var/lib/gems/2.3.0/gems/grpc-1.2.2-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:337
c:0034 p:0048 s:0157 e:000156 METHOD /var/lib/gems/2.3.0/gems/grpc-1.2.2-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167
c:0033 p:0051 s:0142 e:000141 LAMBDA /var/lib/gems/2.3.0/gems/grpc-1.2.2-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:185 [FINISH]
```

**Comment by apolcyn** [comment]
what version of grpc is this? I take it this is not running into https://github.com/grpc/grpc/issues/10479? 
Is there any sort of repro or scenario to make this happen?

**Comment by dopykuh** [comment]
No ist 1.2.2

**Comment by dopykuh** [comment]
Its reproducable, but i currently dont know how ;)

**Comment by apolcyn** [comment]
we can take a look if there's anything making this happen that can be shared or linked to

**Comment by s3rvac** [comment]
I got the same error when using Python bindings (`grpcio` version 1.2.1 on 64b Debian Jessie with Python 3.4.2):

```
E0427 11:29:30.158104513  140458 ev_epoll_linux.c:1444]      pollset_kick: {"created":"@1493285370.158035760","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"created":"@1493285370.158007134","description":"OS Error","errno":3,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1357,"os_error":"No such process","syscall":"pthread_kill"}]}
E0427 11:29:30.158121490  140458 completion_queue.c:267]     Kick failed: {"created":"@1493285370.158035760","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"created":"@1493285370.158007134","description":"OS Error","errno":3,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1357,"os_error":"No such process","syscall":"pthread_kill"}]}
```

Unfortunately, I am unable to reproduce it. It appears sporadicly.

**Comment by apolcyn** [comment]
just a guess: is there forking going on here?
though there is ongoing work to support forking in grpc, it's not supported in grpc right now and could cause a lot of sporadic issues

**Comment by s3rvac** [comment]
Yes, I use `grpcio` in child processes created by `fork()`. Nevertheless, I create channels, stubs, etc. directly in child processes and I do not share them with other processes, so I thought this should work fine. Or is there some magic going on in the initialization part of `grpcio` (when I import it for the first time)?

**Comment by apolcyn** [comment]
> Yes, I use grpcio in child processes created by fork(). Nevertheless, I create channels, stubs, etc. directly in child processes and I do not share them with other processes, so I thought this should work fine. Or is there some magic going on in the initialization part of grpcio (when I import it for the first time)?

cc @nathanielmanistaatgoogle since for this comment on python

**Comment by luxflux** [comment]
I run into the same issue, but on version 1.3.4. Running in forked processes (puma app server).

**Comment by dopykuh** [comment]
I'll got the same error messages but now it causes a deadlocking behavior

**Comment by nathanielmanistaatgoogle** [comment]
@s3rvac: there was some magic going on in the import-time initialization of (Python) `grpcio` in earlier versions of `grpcio`, but that's not the case in more recent versions (post-1.1.0?). Forking is not yet something that (Python) `grpcio` supports to work, but if what you're doing is working for you that's fine for the moment...

**Comment by tonobo** [comment]
I've discovered another non reproducible issue. It happend once out of hundreds of tests.
Also latest grpc version.

```ruby
E0719 14:27:23.937851541    6318 rb_channel.c:144]           assertion failed: bg_watched_channel_list_lookup(bg)
/bin/bash: line 73:  3584 Aborted                 (core dumped) bundle exec rspec --color --tty -t ~ssl
```

**Comment by stiak** [comment]
I get similar errors in a rails app running in App Engine flex when stackdriver logging is being used.  If I try to exit a rails console, this error happens:

```
E0908 20:31:02.126244701    1493 ev_epollsig_linux.c:1069]   pollset_kick: {"created":"@1504902662.126199986","desc
ription":"Kick Failure","file":"src/core/lib/iomgr/ev_epollsig_linux.c","file_line":244,"referenced_errors":[{"crea
ted":"@1504902662.126197568","description":"OS Error","errno":3,"file":"src/core/lib/iomgr/ev_epollsig_linux.c","fi
le_line":982,"os_error":"No such process","syscall":"pthread_kill"}]}
E0908 20:31:02.126305590    1493 completion_queue.c:653]     Kick failed: {"created":"@1504902662.126199986","descr
iption":"Kick Failure","file":"src/core/lib/iomgr/ev_epollsig_linux.c","file_line":244,"referenced_errors":[{"creat
ed":"@1504902662.126197568","description":"OS Error","errno":3,"file":"src/core/lib/iomgr/ev_epollsig_linux.c","fil
e_line":982,"os_error":"No such process","syscall":"pthread_kill"}]}
```

 My docker image is based on `gcr.io/google_appengine/ruby`.

**Comment by dblessing** [comment]
Is anyone running in to this also running Cylance? GitLab have had a small handful of reports with segmentation faults like this and Cylance on RHEL/CentOS seemed to be the common factor.
