### ISSUE TITLE
[Build] [Windows] Build Error:  Warning treated as error

### ISSUE THREAD

**Issue by fjcalzado** [grpc/grpc#10725]
There is a build error due to **Warning treated as Errors** policy when building from Visual Studio in `src\cpp\server\server_builder.cc` line `273`: __conversion from 'size_t' to 'int', possible loss of data__.

Fix sould be something like:
```diff
- int num_frequently_polled_cqs = sync_server_cqs->size();
+ size_t num_frequently_polled_cqs = sync_server_cqs->size();
```

**Comment by nicolasnoble** [comment]
Which version of the compiler and which platform?

**Comment by fjcalzado** [comment]
Sure:
- Visual Studio 2015 Community, version 14.0.25425.01 Update 3. 
- Target: Release, x64.
- Win 7 x64 Enterprise
