### ISSUE TITLE
Handle grpc.RpcError exceptions specially in request iterators

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#10745]
If a streaming request iterator throws an exception:
1) the exception text is not recorded in the grpc.RpcError result of the request
2) if the exception itself was already a grpc.RpcError, the `code()` accessor is not called and thus all codes get converted to `UNKNOWN`

**Comment by Capstan** [comment]
By the way, the status returned seems nondeterministic here, in that sometimes you'll get `CANCELLED` because there appears to be a race between `_channel.py`'s `consume_request_iterator()`'s call of `call.cancel()` and `_abort(state, grpc.StatusCode.UNKNOWN, …)`. It would be nice if it were always the generated exception rather than cancelled.

**Comment by nathanielmanistaatgoogle** [comment]
Are you talking about the application-provided request iterator on the invocation-side of the RPC or the gRPC Python-provided request iterator on the service-side of the RPC? Might I trouble you for a code sample? I'm having trouble understanding what opportunity for enhancement you're describing.

**Comment by alanctgardner** [comment]
@nathanielmanistaatgoogle I'm not the original reporter, but I think I've run into the same issue: when you provide an iterator to the invocation side of the RPC, any exceptions in the iterator are swallowed and the caller sees a generic error (either `UNKNOWN` or `CANCELLED`). The offending code is here: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L178

It would be awesome if `_consume_request_iterator` somehow exposed the original exception thrown by the iterator. A clearer, more consistent error would be great too - it's hard at first glance to figure out whether the problem originates in the client or server.

**Comment by nathanielmanistaatgoogle** [comment]
[Actually `grpcio` 1.12 is out now.](https://pypi.org/project/grpcio/1.12.0)

**Comment by nathanielmanistaatgoogle** [comment]
Closing; I believe this is resolved as of 1.12.
