### ISSUE TITLE
python server os error

### ISSUE THREAD

**Issue by lmeroc** [grpc/grpc#10754]
The following error occurs when i run server ,but server can handle request successfully.
Failed to add :: listener: {"created":"@1492678017.064686347","description":"OS Error","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.c","file_line":270,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50041"}
`
     
     def serve():
           server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
           route_transfer_pb2.add_RouteTransferServicer_to_server(
              TransferServicer(), server)
           add_insecure_port('[::]:50041')
           server.start()
          try:
            while True:
                time.sleep(5)
         except KeyboardInterrupt:
            server.stop(0)
`

**Comment by nathanielmanistaatgoogle** [comment]
@lmeroc: on what platform are you working? With what version of Python are you working? When you say "but server can handle request successfully", are you saying that the only indication of a problem is the emission of the logged message?

@dgquintas: I think I've now seen more than a few "Address family not supported by protocol" - what are users doing wrong and what should they be doing to avoid the message?

**Comment by ncteisen** [comment]
No reported clarification in about a year. Closing.

Feel free to reopen if still relevant
