### ISSUE TITLE
Server port autoselect doesn't work reliably with SO_REUSEPORT on.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10755]
**Context**
When creating a grpc server it is possible let grpc pick an unused port automatically by selecting ":0" (wildcard port).

**Problem**
When `grpc.so_reuseport` is enabled (currently the default) and there's a lot of grpc servers being spun up concurrently (e.g. in tests), there is a race and clients occasionally connect to a wrong server (which ends up listening on the same port).
Crosstalk between different client & server pairs (that are supposed to be hermetic) has been shown to cause flakiness of some of our tests (e.g. in C#).  In real-life scenarios this is not likely to be a problem, unless there is a lot of servers and client being created & shutdown concurrently.

**Workaround**
Setting `grpc.so_reuseport`  channel argument to 0 for the servers will mitigate the problem (that's not usable in general because it SO_REUSEPORT is important for performance, but it's good enough for tests).

**Comment by hexinw** [comment]
Hi,

@kpayson64 
Is SO_REUSEPORT disabled by default in grpc? I am seeing an issue when trying to bringup multiple grpc servers.

[root@tuns-deployment-2602672641-089j6 tuns]# python /var/tmp/test_grpc.py &
[1] 3484
[root@tuns-deployment-2602672641-089j6 tuns]#
[root@tuns-deployment-2602672641-089j6 tuns]#
[root@tuns-deployment-2602672641-089j6 tuns]# netstat -an |grep 3333
tcp6       0      0 :::3333                 :::*                    LISTEN
[root@tuns-deployment-2602672641-089j6 tuns]# python /var/tmp/test_grpc.py &
[2] 3491
[root@tuns-deployment-2602672641-089j6 tuns]# E0607 21:59:24.669550425    3491 server_chttp2.cc:40]        {"created":"@1528408764.669478381","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1528408764.669472752","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":345,"referenced_errors":[{"created":"@1528408764.669452377","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1528408764.669444826","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1528408764.669471667","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1528408764.669467475","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]}]}]}

**Comment by kpayson64** [comment]
@hexinw 
In the manylinux binary distribution, yes it is disabled.  ```SO_REUSEPORT``` isn't part of the manylinux standard, so we can't distribute binaries with it enabled.

If you want to use ```SO_REUSEPORT``` with Python, you will need to install from source.

**Comment by hexinw** [comment]
Great. Works now after re-install from source. Thanks @kpayson64.

[root@tuns-deployment-2602672641-s06qd grpc]# python /var/tmp/test_grpc.py&
[1] 2772
[root@tuns-deployment-2602672641-s06qd grpc]# netstat -an |grep 3333
tcp6       0      0 :::3333                 :::*                    LISTEN
[root@tuns-deployment-2602672641-s06qd grpc]# python /var/tmp/test_grpc.py&
[2] 2779
[root@tuns-deployment-2602672641-s06qd grpc]# ps axww
  PID TTY      STAT   TIME COMMAND
  241 ?        Ss     0:00 bash
 2772 ?        Rl     0:09 python /var/tmp/test_grpc.py
 2779 ?        Rl     0:03 python /var/tmp/test_grpc.py
 2786 ?        R+     0:00 ps axww
[root@tuns-deployment-2602672641-s06qd grpc]# cat /var/tmp/test_grpc.py
from concurrent import futures
import grpc

server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
port = server.add_insecure_port("[::]:%s" % 3333)
server.start()
while True:
  pass
