### ISSUE TITLE
[Ruby] Custom error handler for RPC Server?

### ISSUE THREAD

**Issue by nguyenquangminh0711** [grpc/grpc#10769]
Based on the current [implementation](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_desc.rb#L117), it seems like the GRPC wrapper for Ruby doesn't support a custom error handler for RPC Server. When the call meets a runtime error, the print the backtrace to the logger and return UNKNOWN status back to the requester. There is no way to add my own error handling logic such as attaching some more useful information to the response meta data, or delegating the error to SaaS services like Airbrake or Sentry. In my opinion, we should allow to inject the customer handlers as an option of RpcServer. 

What you do think about this? Hope to hear your opinions about this problem.

**Comment by apolcyn** [comment]
as far as throwing custom errors goes, the server can actually return custom errors (with custom status code, message and details), by raising the appropriate `BadStatus` exception.

There are some examples of doing this in https://github.com/grpc/grpc/tree/master/examples/ruby/errors_and_cancellation, does that help for the issue here?

FYI if an exception is raised by a server handler that isn't a `GRPC::BadStatus` exception, then by default the server returns an 'UNKNOWN' status, as seen here.

**Comment by nguyenquangminh0711** [comment]
Hi @apolcyn, thanks for your response. It is true that the client side receives UNKNOWN status and some information when the server raises exception. IMO, it doesn't help in tracing and debugging the problem at server side since GRPC doesn't allow us to touch the exception to send to our exception tracking service. Our current solution is to monkey-patch the gRPC handlers:

```ruby
handler_methods = %i(
      handle_request_response
      handle_client_streamer
      handle_server_streamer
      handle_bidi_streamer
)

error_handlers = [
  proc do |exception|
    Raven.catch_exception(exception)
  end
]

SomeServer::RpcServer::Service.rpc_descs.each do |rpc_desc|
      rpc_desc.error_handlers = error_handlers
      handler_methods.each do |method|
        rpc_desc.singleton_class.class_eval <<-RUBY, __FILE__, __LINE__ + 1
          def __wrapped_#{method}(*args)
            __old_#{method}(*args)
          rescue => e
            error_handlers.each { |handler| handler.call(e) }
            fail e
          end

          alias __old_#{method} #{method}
          alias #{method} __wrapped_#{method}
        RUBY
    end
end
```
We know that patching the RPC Descriptor is not good. But we don't have other choices. Since our use case is quite common. I don't know whether we could add some middlewares to handle the exception here:  https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_desc.rb#L117 . If it is okay, I'll open a pull request for this issue

**Comment by apolcyn** [comment]
I'm not sure yet about such a change to the server code. I think there are some complications here. For example, note that such a change wouldn't capture all "bad status's" sent from the grpc server. For example, in some cases, `ResourceExhausted` and `Unimplemented` status codes can be sent by the server without ever invoking the rpc service handlers at all.

As an alternate idea: is it doable to wrap the service handler methods with exception handlers, in the application code above grpc?

**Comment by nguyenquangminh0711** [comment]
@apolcyn Yeah you are right. Perhaps putting the error handler into GRPC layer is not a good idea since not everyone needs that and it adds up a lot of complication into the GRPC layer itself. Then I'll move the error handler into application code. Thanks for your helps 💯

**Comment by shiroyasha** [comment]
@apolcyn @nguyenquangminh0711 I am trying to solve the same issues in my service. I would like to catch all unhanded errors and capture them via Raven.

What is the current best solution for this?

**Comment by nguyenquangminh0711** [comment]
@shiroyasha Hi, we already solved this problem in our company. Instead of working directly with gRPC clients, we implement a wrapper on top of the gRPC client (in our case, Ruby and Golang), the application code interacts to the abstraction layer so that the error handling and retrying complexity is hidden.  
- The gRPC-level errors (like missing handlers, connection error, etc.) are indicated via RPC call status, it is easy to catch them. The wrapper automatically retries a few time to increase the high-availability.
- The application errors are handled in two ways, depending on the error type.
  + The business-related errors are reflected directly in the protocol buffer. The standard for each protocol buffer includes errorCode, errorDetail, and the actual data. This kind of error forces us to handle case by case since it is business logic. 
  + The exceptions are handled differently, we inject the exception information like service, location, file, backtraces, etc. in the metadata that attached to each call. Thanks to the wrapper, the exception handler is centralized.
It works for our company, not sure about others'. Hope that this will help you 👍

**Comment by shiroyasha** [comment]
@nguyenquangminh0711 thanks for the quick reply, this definitely helps with our research. 🙇
