### ISSUE TITLE
Redeploy problematic for ASP.NET apps running on IIS (cannot overwrite native .dll)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10784]
Re-posting an issue reported by @ivannaranjo from e-mail thread.

_I am trying to re-deploy apps that contain gRPC API clients on them, such as the StackDriver logging, I am seeing problems where the native .dll is in use and cannot be deleted. Because the deployment of an ASP.NET 4.x app (https://www.asp.net/) to a Windows VM requires the replacement of all files, if a file cannot be deleted that blocks the deployment.
The user can unblock themselves by shutting IIS down and deleting the files by hand, but that seems a bit too drastic. Have you seen anything like this previously? Any ideas here? Is it just something that comes from having a native (i.e. non C#) .dll loaded in the AppDomain?
Here's the interesting tidbit from the deployment log that shows the failure, the error is a bit misleading because it shows insufficient privileges, really is that file is in use._

```
msdeploy.exe -verb:sync -source:contentPath="C:\Users\ivann\AppData\Local\Temp\2\5ml0urec.0w2" -dest:contentPath="Default Web Site",publishSettings="C:\Users\ivann\AppData\Local\Temp\2\tmp2A6B.tmp" -allowUntrusted
Info: Using ID 'b64e9ea2-383a-4483-97e1-d3cb82dc98e4' for connections to the remote server.
Info: Deleting file (Default Web Site\bin\grpc_csharp_ext.x64.dll).
Error Code: ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER
More Information: Unable to perform the operation ("Delete File")  for the specified directory ("C:\inetpub\wwwroot\bin\grpc_csharp_ext.x64.dll"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.
Error: The error code was 0x80070005.
Error: Access to the path 'C:\inetpub\wwwroot\bin\grpc_csharp_ext.x64.dll' is denied.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileEx.Delete(String path)
   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)
Error count: 1.
Failed to publish project AspNetClassic.
```

**Comment by jtattermusch** [comment]
CC @ivannaranjo @jskeet @chrisdunelm

**Comment by DavidKuennen** [comment]
Having the same issue. It's unusable for us like that.

**Comment by DavidKuennen** [comment]
@jtattermusch Did you find any solution yet?

**Comment by jtattermusch** [comment]
@DavidKuennen   this unfortunately boils down to the fact that on Windows you cannot delete a dll that's loaded (and deleting the directory with grpc_csharp_ext.dll is required to redeploy), and that's something we can't really change.
To avoid this for managed dlls, shadowing is used, but that's something that's not supported for native dlls.

Btw, this issues seems to be legacy ASP.NET specific and on ASP.NET core things should work fine.
Could you maybe use ASP.NET core for your app?

**Comment by shubhamranjan** [comment]
Happened for me as well. Any resolutions / workarounds yet.Can't migrate to ASP .NET core.

**Comment by shubhamranjan** [comment]
Found a workaround  - Use parameter `-useChecksum` with msdeploy to avoid deleting the file.Note : this will still fail if you are removing the file from the project or `grpc_csharp_ext` gets updated in the nuget package.

**Comment by splebel** [comment]
Another workaround for those not using msdeploy is to deploy to another folder then to recycle the application pool. After you can delete the dll.

**Comment by Eleanor68** [comment]
Having the same issue. Is it planned to be fixed? Or at least advice us how to avoid it.
System.UnauthorizedAccessException: (5) Access is denied: [grpc_csharp_ext.x64.dll]
GRPC Version 1.20.1
