### ISSUE TITLE
Generated client fails in Node on latest version

### ISSUE THREAD

**Issue by relwell** [grpc/grpc#10786]
Given the same generated code for a service and its client, using the latest grpc (1.2.4), instantiating a client with `grpc.credentials.createInsecure()` as the second argument results in the following error:

```
TypeError: Channel's second argument must be a ChannelCredentials
```

Downgrading the grpc package to 1.1.2 results in the expected behavior of a client instance being created.

**Comment by murgatroid99** [comment]
Can you provide a simple reproduction case for this failure?

**Comment by vertiman** [comment]
If you generate any client, even on a simple service, it will fail when doing 

var client = new services.ServiceClient("localhost:50051", grpc.credentials.createInsecure());

with the TypeError in the original bug.

**Comment by murgatroid99** [comment]
Can you provide a complete reproduction case? If I don't see what you're doing that's different from what the tests do, I won't be able to figure out why it's not working for you.

**Comment by raghavchandra** [comment]
@vertiman 
I was getting the same error. The problem was that I was two different instances of require('grpc'). Eg – the dynamic proto-gen was created in one module, and I was using another module to create the client.

Answer was to make sure one instance of require() (require instantiates a singleton – as long as its the same absolute file path), it should work fine.

**Comment by adamcohen** [comment]
I've run into the same issue when attempting to use `npm link`.

I have the following setup:

```js
// in mynodeapp/server.js 
const grpc = require('grpc');

const grpcCredentials = grpc.credentials.createInsecure();

const myClient = new myService.serviceName(
  process.env.ADDRESS,
  grpcCredentials
);
```

And then I have a module that I created with my protobuf definitions, and in the module I have:

```js
// in my-protobuf-module/index.js
const grpc = require('grpc');

module.exports.load_proto = function(path) {
    return grpc.load({root: __dirname, file: path});
}
```

I then tried using `npm link` with my module so that I can develop against the protobuf locally without publishing the module, however, when my project attempts the following:

```js
const myClient = new myService.serviceName(
  process.env.ADDRESS,
  grpcCredentials
);
```

I receive the error:

```
/Users/myname/golang/src/github.com/somerepo/protobuf/npm-module-staging-directory/npm-publish/node_modules/grpc/src/node/src/client.js:749
    this.$channel = new grpc.Channel(address, credentials, options);
                    ^

TypeError: Channel's second argument must be a ChannelCredentials
    at new Client (/Users/myname/golang/src/github.com/somerepo/protobuf/npm-module-staging-directory/npm-publish/node_modules/grpc/src/node/src/client.js:749:21)
```

If I change the require in my service to use the same `grpc` as is being used by my module, it works:

```js
// in mynodeapp/server.js - this works fine
const grpc = require('./node_modules/@somerepo/my-protobuf-module/node_modules/grpc');
```

So it looks like both of my `require` statements must reference the same `grpc` instance, but I'm not sure how to do this when using `npm link`, since I now have two different copies of `grpc`:

1. One instance of `grpc` in `node_modules/grpc`
2. One instance of `grpc` in `node_modules/@somerepo/my-protobuf-module/node_modules/grpc`

**Comment by adamcohen** [comment]
I've managed to find a workaround for this issue:

**my-protobuf-module/index.js**
```
modulejs.exports.load_proto = function(path) {
  return grpc.load({root: __dirname, file: path});
}

// this is needed because the grpc module instanciate a singleton,
// which means we must only ever have one reference to a single
// grpc module. 
module.exports.grpc = grpc;
```

**mynodeapp/server.js**
```js
const grpc = require('@somerepo/my-protobuf-module').grpc;
```

This way, we use the `grpc` module in `my-protobuf-module` both in my node app as well as in the module itself.

**Comment by mattolson** [comment]
We are affected by this bug as well. We have two modules that both require grpc. I was able to work around this by upgrading to npm 5.5.1 which performs deduping of modules that share the same version. Migrating to yarn should have the same effect.

**Comment by moander** [comment]
`yarn upgrade` in project folder did the trick for me :)

<pre>
TypeError: Channel's second argument must be a ChannelCredentials
    at ServiceClient.Client (node_modules\grpc\src\node\src\client.js:472:19)
    at new ServiceClient (node_modules\grpc\src\node\src\client.js:881:12)
    at node_modules\@google-cloud\pubsub\src\connection-pool.js:401:19
    at node_modules\@google-cloud\pubsub\src\connection-pool.js:439:5
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
</pre>

**Comment by zyf0330** [comment]
Is there any schedule to fix this?

**Comment by murgatroid99** [comment]
We do not have plans to support interactions between two different version of that gRPC library.

**Comment by elado** [comment]
This state requires the containing project to match the same `grpc` version in the generated code (that is usually a different node module).

The solution would be to not require `grpc` on the host project, and expose `grpc` from the generated code.

`new UsersClient('path', UsersClient.grpc.credentials.createInsecure())`

this will guarantee usage of the version the client expects.

**Comment by bacthosan** [comment]
> This state requires the containing project to match the same `grpc` version in the generated code (that is usually a different node module).
> 
> The solution would be to not require `grpc` on the host project, and expose `grpc` from the generated code.
> 
> `new UsersClient('path', UsersClient.grpc.credentials.createInsecure())`
> 
> this will guarantee usage of the version the client expects.

could you explain more for me how to fix

**Comment by bacthosan** [comment]
I have solved this problem. Firstly, you should uninstall your current version grpc. Then, install older version grpc. In my case, now i install grpc@1.10.1
