### ISSUE TITLE
Getting Trailer Metadata from Java server to Node Client

### ISSUE THREAD

**Issue by vedant15** [grpc/grpc#10782]
Hello,

According to the documentation , it is possible to send trailer metadata using `onError` method on a java server; something like this 
```
responseObserver.onError(Status.fromCodeValue(100).withDescription("Request for service failed").asException(trailers));
```

However, I have not been able to access that data on a node client(I am making a unary request), the Error object which is passed to the callback has an empty Metadata object.

Upon going through the source code, I found the following block in `client.js`
```
      emitter.emit('metadata', Metadata._fromCoreRepresentation(
          response.metadata));
      if (status.code === grpc.status.OK) {
        if (err) {
          // Got a batch error, but OK status. Something went wrong
          args.callback(err);
          return;
        } else {
          try {
            deserialized = deserialize(response.read);
          } catch (e) {
            /* Change status to indicate bad server response. This will result
             * in passing an error to the callback */
            status = {
              code: grpc.status.INTERNAL,
              details: 'Failed to parse server response'
            };
          }
        }
      }
      if (status.code !== grpc.status.OK) {
        error = new Error(status.details);
        error.code = status.code;
        error.metadata = status.metadata;
        args.callback(error);
      } else {
        args.callback(null, deserialized);
      }
```

It seems that the trailer metadata sent from the server is in `response.metadata` . However, the node js module sends the metadata present in the `status` object which is empty and the data from `response.metadata` is emitted with a `metadata` event. 

Is there a way to pass the trailer metadata to the callback ?
Thank you for your help !

**Comment by murgatroid99** [comment]
The trailing metadata is in `response.status.metadata`, which goes into `error.metadata` in the error that is passed to the callback.

**Comment by vedant15** [comment]
@murgatroid99 thanks a lot for the reply.

The behavior I am observing in my case is that the metadata in `response.status.metadata` is empty which in turn makes `error.metadata` empty. 

First I thought that maybe my server wasn't passing the metadata back. However on debugging further, I saw that the data was being populated in  `response.metadata` instead of `response.status.metadata`.

Do I need to change the way I am reporting error from my Java Server , right now I am using the following:
```
responseObserver.onError(Status.fromCodeValue(100).withDescription("Request for service failed").asException(trailers));
```

**Comment by murgatroid99** [comment]
CC @ejona86 Can you weigh in on the Java side of this?

**Comment by ericgribkoff** [comment]
The Java code posted will add `trailers` to the metadata returned with the error. Since it's showing up on the client in `response.metadata`, it seems like Java is propagating it as intended. 

What is the criteria for Node putting metadata into `response.status.metadata` rather than `response.metadata`?

**Comment by ejona86** [comment]
The Java code looks correct, and it does seem that `ServerCalls` [propagates the `Metadata` from the `StatusException`](https://github.com/grpc/grpc-java/blob/v1.2.0/stub/src/main/java/io/grpc/stub/ServerCalls.java#L290).

I wouldn't be surprised if there was a problem with headers vs trailers. If no message was sent before the error (common), then grpc-java won't have sent headers and will only send trailers.

**Comment by vedant15** [comment]
I printed out the `response` object from https://github.com/murgatroid99/grpc/blob/master/src/node/src/client.js#L407 and the output was ```
{ 
  send_metadata: true,
  send_message: true,
  client_close: true,
  metadata: { test_exception_key: [ 'test exception value' ] },
  read: null,
  status: { code: 2, details: 'Request for service failed', metadata: {} } 
}
```
the `read` is set to `null`, I would assume that this means that Server didn't send any message back except for the error.

**Comment by ejona86** [comment]
Ah, now I understand the "status" part of the discussion. Yeah, that looks highly-likely to me to be caused by headers vs trailers mixup.

**Comment by vedant15** [comment]
@ejona86 any pointers on how I can overcome this ?

I only face this issue on a node client; on a Java client the error handling works as intended. I tried it with the following snippet
```
     try {
       response = blockingStub.getSampleResponse(request);
     } catch (StatusRuntimeException e) {
        System.out.println(e.getTrailers().get(Metadata.Key.of("test_exception_key",Metadata.ASCII_STRING_MARSHALLER)));
       logger.log(Level.WARNING, "RPC failed: {0}", e.getStatus());
       return;
     }
```

Thanks a lot guys for your help with this !

**Comment by murgatroid99** [comment]
It looks like there may be some difference in how Java and the C core handle trailers when there are no messages. Maybe we need an interop test for this.

**Comment by vedant15** [comment]
@murgatroid99 if I am not misunderstanding, this is a limitation or an issue with the Node GRPC library, correct ?

**Comment by murgatroid99** [comment]
It's a disagreement on spec implementation. If for identical responses the C core is putting the metadata into the headers and Java is putting it into the trailers, either one of them is wrong or the spec is incomplete.

CC @ctiller Do you know what the deal is with this?

**Comment by shanshanzhu** [comment]
Our Go service send the header in trailer as well, I found that the header is emitted from the status event.

```
    const call = client.helloworld(request, meta,{}, () => {}); // pseudocode.
    call.on('status', status => {
      if (status.code === StatusCode.OK) {
        console.log('status.metadata.get('<HEADER KEY SET IN TRAILER'));
      }
    });
```
