### ISSUE TITLE
Problem with C++ failing to use stub in multiple places

### ISSUE THREAD

**Issue by mastergberry** [grpc/grpc#10783]
I believe this is related to https://github.com/grpc/grpc-go/pull/505

We have a bi-directional stream setup in C++ on a server as per usual. No issues on this.
We then have the following C++ client code:

```
this->m_pChannel = CreateChannel(clientAddr, grpc::InsecureChannelCredentials());
this->m_pStub = clientcommunicatorstream::CommunicatorService::NewStub(this->m_pChannel);
```

We then start off our bi-directional stream with the server and leave it running forever in a loop.
We then use the same stub to send different messages on a regular RPC call (no streams).

After exactly 1 minute the RPC single calls begin to fail. This seems to be an issue with the C++ client code. The error is as follows:

```
[ERROR] [GRPCClient::ProcessCommunication] GRPC Failed: 14 - {"created":"@1492762861.182000000","description":"Endpoint read failed","file":"C:\path\to\code\thirdparty\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.c","file_line":1851,"grpc_status":14,"occurred_during_write":0,"referenced_errors":[{"created":"@1492762861.182000000","description":"The I/O operation has been aborted because of either a thread exit or an application request.\r\n","file":"C:\path\to\code\thirdparty\grpc\src\core\lib\iomgr\tcp_windows.c","file_line":176}]}
```

I tested the same setup with a Python client (using a single stub for both) and had 0 issues. This seems to be a specific issue once again with the C++ client in GRPC. Making two different stubs providers a workaround, leaving the stream one to just handle the stream and then doing one time requests on the second stub.

I believe we are on 1.12 for the GRPC version. This is also a Windows application.

Not sure if this was already resolved or not.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
