### ISSUE TITLE
Installing Python library on Raspbian

### ISSUE THREAD

**Issue by aazimh** [grpc/grpc#10793]
Hi guys,

I'm trying to install the Google Speech Recognition Python client on my Raspberry Pi, but have been unable to do so as one of the dependencies is the GRPC library which does not seem to build on the Pi. It gets stuck on the following line:

`Running setup.py bdist_wheel for grpcio...`

and doesn't move forward until I cancel. Have the same issue when I try to `pip install grpcio` separately.

Is there any way around this?

Thanks,
Aazim.

**Comment by ProLoDs** [comment]
Hi,
compiling on the PI can be very slow, so be patient, dont cancle and wait.

As long as there is no error everything should be fine.

**Comment by aazimh** [comment]
@ProLoDs Oh okay, I've started it again and will wait for it to complete and report back - thanks!

**Comment by lukesneeringer** [comment]
@ProLoDs Would it be possible to provide wheels for this?

**Comment by aazimh** [comment]
It worked! Took a while, but it did :) thank you @ProLoDs for the help!

**Comment by lukesneeringer** [comment]
@kpayson64 This customer installed successfully, but there is still an issue here. Would it be possible to provide ARM wheels?

GRPC installation can represent a significant usability issue for our customers; if possible, it would be nice to make this smoother, and we have the ability to do so.

**Comment by kpayson64** [comment]
@lukesneeringer 
I've opened #10890.

**Comment by lukesneeringer** [comment]
Thanks!
