### ISSUE TITLE
How Completion Queue Shutdown works, in Client

### ISSUE THREAD

**Issue by pfooter** [grpc/grpc#10818]
hello, 
  I have a sync Client, but meet a problem when I try to drain the CompletionQueue.
  cq_.Next() can't return. 
  I search the problem, but still confused! 
  https://github.com/grpc/grpc/issues/8610            // How Completion Queue Shutdown works
  http://www.grpc.io/grpc/cpp/classgrpc_1_1_completion_queue.html

  part of code: 
      std::unique_ptr<ClientAsyncResponseReader<EchoResponse>> response_reader(
          stub_->AsyncEcho(&cli_ctx, send_request, cq_));
      response_reader->Finish(&recv_response, &recv_status, tag(4));

      void *tag;  bool ok;
      auto deadline = std::chrono::system_clock::now() + std::chrono::seconds(3);
      auto r = cq_.AsyncNext(&tag, &ok, deadline);

      if (r == CompletionQueue::TIMEOUT) {
          cq_.Shutdown();
          cq_.Next(&tag, &ok);        // XXX block here
      }

  in client, after Shutdown(), NO Next() to drain the cq_ ? WHY ?
  , thanks~

**Comment by pfooter** [comment]
If the server sleep(100); when recvice the send_request,  the client will wait until 97s in  cq_.Next(&tag, &ok);

**Comment by ncteisen** [comment]
Can you specify the question please?
