### ISSUE TITLE
grpc vs2013 project can not build for x64 arch

### ISSUE THREAD

**Issue by xsmart** [grpc/grpc#1082]

**Comment by nicolasnoble** [comment]
Yep, there is some work needed there - 32 bits should work though.

**Comment by xsmart** [comment]
Thanks nicolasnoble ! When i can got the windows x64 version of the grpc

**Comment by nicolasnoble** [comment]
We don't exactly have immediate plans for that, as the Windows port is still to be considered pre-alpha status. We don't have continuous integration tests for it yet, so before committing time to the 64 bits architecture, we'd want that first.

**Comment by chai2010** [comment]
@xsmart You try my fork https://github.com/chai2010/grpc-windows
It use cmake, support all static link (use `/MT /MTd` as default) on win32/win64.

**Comment by jtattermusch** [comment]
building on x64 on windows should work now: https://github.com/grpc/grpc/pull/4286
