### ISSUE TITLE
Register an async tag after each call to Next?

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#1083]
w359405949 commented in issue #1004 : "Before i recieve an async call, i must 'register' a tag after call Next evertimes? i should never know when and how many times the method will be called, and i think it should be auto finished by the protobuf(like protobuf2) or grpc."

**Comment by vjpai** [comment]
I wanted to followup on this separately. The registration should not be automatic, IMO, because we don't know if this RPC will still be desired. I like to think of registration as establishing a credit system. For example, in the qps server, you'll see that there are 100 Requests made ahead of time for later use. More get added later because this server needs a lot, but that wouldn't always be the case.

**Comment by vjpai** [comment]
I've put a wontfix on this, but I'll leave it open for a day to see if anyone else has a different opinion

**Comment by ctiller** [comment]
Just as a further comment (I agree with the wontfix), by forcing the application to re-register, we allow the application to apply push back against being overloaded by clients, giving a form of flow control. We plan to use this more in the future to push back on clients and allow them to choose less loaded targets for RPCs (see, for instance #205)

**Comment by vjpai** [comment]
I'll close this issue out. It's straightfoward to register a call if you want one, but dangerous to do so automatically.
