### ISSUE TITLE
[php ext] bad reported version

### ISSUE THREAD

**Issue by remicollet** [grpc/grpc#10842]
From pecl package

```
$ php  --re grpc | head -1
Extension [ <persistent> extension #15 grpc version 0.1.0 ] {
```

Should be **1.2.0** (or whatever next version will be)

**Comment by thinkerou** [comment]
we should also update `PHP_GRPC_VERSION` in php_grpc.h file.

**Comment by remicollet** [comment]
Notice, things are better, but not perfect ;)

Version 1.4.0RC1 reports as 1.4.0...

**Comment by stanley-cheung** [comment]
I see. Will fix.
