### ISSUE TITLE
[php ext] build failure with recent GCC

### ISSUE THREAD

**Issue by remicollet** [grpc/grpc#10843]
ON Fedora 26, using GCC 7.0

```
In file included from /usr/include/string.h:639:0,
                 from /builddir/build/BUILD/php-pecl-grpc-1.2.0/NTS/third_party/boringssl/crypto/asn1/a_bitstr.c:59:
In function 'memcpy',
    inlined from 'i2c_ASN1_BIT_STRING' at /builddir/build/BUILD/php-pecl-grpc-1.2.0/NTS/third_party/boringssl/crypto/asn1/a_bitstr.c:118:5:
/usr/include/bits/string3.h:53:10: error: '__builtin_memcpy': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-grpc-1.2.0/NTS/third_party/boringssl/crypto/asn1/a_bitstr.c: At top level:
cc1: error: unrecognized command line option '-Wno-parentheses-equality' [-Werror]
cc1: all warnings being treated as errors
```

**Comment by nicolasnoble** [comment]
Adding @jboeuf on behalf of @agl - that seems there's an interesting memcpy happening there.

**Comment by jboeuf** [comment]
This looks like a compilation error, right? I'm a bit confused by these numbers and where they're coming from. Do we have more context?
+ @murgatroid99 @stanley-cheung for gRPC PHP.

**Comment by remicollet** [comment]
> This looks like a compilation error, right?

Yes.

> Do we have more context?

Sorry, no, simple build (on Fedora 26)

**Comment by jboeuf** [comment]
Thanks @remicollet 

@nicolasnoble did you try to compile just our version of boringssl on fedora 26 with gcc 7.0? It doesn't look like a gRPC bug to me. Note that our version of boring doesn't include this fix https://github.com/google/boringssl/commit/17cf2cb1d226b0ba2401304242df7ddd3b6f1ff2 which may address the problem.

**Comment by stanley-cheung** [comment]
I am trying to reproduce this. Trying to find whether there's an easier way to run Fedora 26 Alpha. There don't seem to be a docker image.

**Comment by choleraehyq** [comment]
Hi all, I also met this error when building TiKV.
```
/home/cholerae/rustcode/tikv/target/release/build/grpc-sys-08652de717d3e248/out/grpc/third_party/boringssl/crypto/asn1/a_bitstr.c: In function ‘i2c_ASN1_BIT_STRING’:
/home/cholerae/rustcode/tikv/target/release/build/grpc-sys-08652de717d3e248/out/grpc/third_party/boringssl/crypto/asn1/a_bitstr.c:118:5: error: ‘memcpy’: specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
     memcpy(p, d, len);
     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Fedora 26, gcc 7.1.1.

**Comment by remicollet** [comment]
@choleraehyq on Fedora, try my repository ;)
https://rpms.remirepo.net/

Everything about PHP should be there (including this project)

**Comment by jiangtaoli2016** [comment]
Is this still a problem? @remicollet

**Comment by remicollet** [comment]
fixed for some time now
