### ISSUE TITLE
Build failed on MacOS 10.12.4

### ISSUE THREAD

**Issue by TigerLau1985** [grpc/grpc#10857]
I follow the guid to build grpc on MacOS 10.12.4 ,and the Xcode version is 8.3.2, xcode-select is 2347. 

When run the 'make' command, libtool report such error:

> [MAKE]    Generating /Users/tigerlau/Documents/repos/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /Users/tigerlau/Documents/repos/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling src/core/lib/profiling/basic_timers.c
[C]       Compiling src/core/lib/profiling/stap_timers.c
[C]       Compiling src/core/lib/support/alloc.c
[C]       Compiling src/core/lib/support/avl.c
[C]       Compiling src/core/lib/support/backoff.c
[C]       Compiling src/core/lib/support/cmdline.c
[C]       Compiling src/core/lib/support/cpu_iphone.c
[C]       Compiling src/core/lib/support/cpu_linux.c
[C]       Compiling src/core/lib/support/cpu_posix.c
[C]       Compiling src/core/lib/support/cpu_windows.c
[C]       Compiling src/core/lib/support/env_linux.c
[C]       Compiling src/core/lib/support/env_posix.c
[C]       Compiling src/core/lib/support/env_windows.c
[C]       Compiling src/core/lib/support/histogram.c
[C]       Compiling src/core/lib/support/host_port.c
[C]       Compiling src/core/lib/support/log.c
[C]       Compiling src/core/lib/support/log_android.c
[C]       Compiling src/core/lib/support/log_linux.c
[C]       Compiling src/core/lib/support/log_posix.c
[C]       Compiling src/core/lib/support/log_windows.c
[C]       Compiling src/core/lib/support/mpscq.c
[C]       Compiling src/core/lib/support/murmur_hash.c
[C]       Compiling src/core/lib/support/stack_lockfree.c
[C]       Compiling src/core/lib/support/string.c
[C]       Compiling src/core/lib/support/string_posix.c
[C]       Compiling src/core/lib/support/string_util_windows.c
[C]       Compiling src/core/lib/support/string_windows.c
[C]       Compiling src/core/lib/support/subprocess_posix.c
[C]       Compiling src/core/lib/support/subprocess_windows.c
[C]       Compiling src/core/lib/support/sync.c
[C]       Compiling src/core/lib/support/sync_posix.c
[C]       Compiling src/core/lib/support/sync_windows.c
[C]       Compiling src/core/lib/support/thd.c
[C]       Compiling src/core/lib/support/thd_posix.c
[C]       Compiling src/core/lib/support/thd_windows.c
[C]       Compiling src/core/lib/support/time.c
[C]       Compiling src/core/lib/support/time_posix.c
[C]       Compiling src/core/lib/support/time_precise.c
[C]       Compiling src/core/lib/support/time_windows.c
[C]       Compiling src/core/lib/support/tls_pthread.c
[C]       Compiling src/core/lib/support/tmpfile_msys.c
[C]       Compiling src/core/lib/support/tmpfile_posix.c
[C]       Compiling src/core/lib/support/tmpfile_windows.c
[C]       Compiling src/core/lib/support/wrap_memcpy.c
[AR]      Creating /Users/tigerlau/Documents/repos/grpc/libs/opt/libgpr.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/profiling/basic_timers.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/profiling/stap_timers.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/alloc.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/avl.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/backoff.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/cmdline.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/cpu_iphone.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/cpu_linux.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/cpu_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/cpu_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/env_linux.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/env_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/env_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/histogram.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/host_port.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/log.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/log_android.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/log_linux.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/log_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/log_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/mpscq.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/murmur_hash.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/stack_lockfree.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/string.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/string_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/string_util_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/string_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/subprocess_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/subprocess_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/sync.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/sync_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/sync_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/thd.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/thd_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/thd_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/time.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/time_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/time_precise.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/time_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/tls_pthread.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/tmpfile_msys.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/tmpfile_posix.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/tmpfile_windows.o is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tigerlau/Documents/repos/grpc/objs/opt/src/core/lib/support/wrap_memcpy.o is not an object file (not allowed in a library)
make: *** [/Users/tigerlau/Documents/repos/grpc/libs/opt/libgpr.a] Error 1

**Comment by TigerLau1985** [comment]
I have checked these '.o' files is exist.

**Comment by mehrdada** [comment]
I just started from a new macOS 10.12.4 install. I installed Xcode 8.3.2, ran it and agreed to the license. I also installed `brew` and

```sh
brew install libtool shtool autoconf automake
```

Then following the instructions on the website (or the following) worked fine:

```sh
git clone --recursive -b v1.2.x https://github.com/grpc/grpc
cd grpc
make
```

Let me know if they don't work for you. Also, I figured that if you don't have the brew packages installed *before* you run `make` the first time, you need to clean up and start over from scratch as `make` gets confused.

**Comment by TigerLau1985** [comment]
@mehrdada I have retry, but the problem not resolved. I have installed libtool , but it named glibtool.

As you said, grpc used gnu-libtools ,but in the Makefile, this section
"ifeq ($(SYSTEM),Darwin)
ifeq ($(origin AR), default)
AR = libtool -no_warning_for_no_symbols -o"
means use libtool with Xcode?

**Comment by mehrdada** [comment]
Yes, I literally ran the exact commands above and it worked on a newly installed macOS. Installing it as `glibtool` is fine. Can you try the following on a fresh clone (and don't forget `--recursive`) and let me know if it works please?

```sh
LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make
```

**Comment by TigerLau1985** [comment]
@makdharma Thx, as follow your steps, it's worked. Maybe should update the document.
