### ISSUE TITLE
Some machines do not have a 4.5+ kernel

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10851]
- [x] grpc-jenkins-linux53

**Comment by matt-kwong** [comment]
linux53 has been updated. linux52 is the last one that needs to be updated, but that is disconnected from Jenkins until I update it, so feel free to push the new tests.

**Comment by matt-kwong** [comment]
Linux52 has been updated. All VMs that run Linux basictests should have kernel 4.5+.
