### ISSUE TITLE
node flake "Call propagation Cancellation With a unary call" timeout.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10878]
```
Call propagation Cancellation With a unary call:
     Error: Timeout of 8000ms exceeded.
```

https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/5004/testReport/junit/(root)/node_linux_opt_native/tools_run_tests_helper_scripts_run_node_sh/

**Comment by murgatroid99** [comment]
Similar error in "Call propagation Deadline With a bidi stream call": https://grpc-testing.appspot.com/job/gRPC_master_windows/2523/testReport/junit/(root)/node_windows_dbg_native/tools_run_tests_helper_scripts_run_node_bat/

**Comment by murgatroid99** [comment]
Same failure, different test: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux_opt/562/testReport/junit/(root)/node_linux_opt_native/tools_run_tests_helper_scripts_run_node_sh/
