### ISSUE TITLE
cmake: CARES_ROOT_DIR is not configurable

### ISSUE THREAD

**Issue by andelf** [grpc/grpc#10907]
（in cmake）
Since CARES_ROOT_DIR points to `third_party/cares`.
The git submodule path is `third_party/cares/cares`.

This is strange. zlib, boringssl can all be customized by `*_ROOT_DIR` vars.

**Comment by nicolasnoble** [comment]
That's an oversight. Thanks for reporting this.

**Comment by jtattermusch** [comment]
Even though I think the usefulness of this setting is very limited, CARES_ROOT_DIR now seems to be configurable:
https://github.com/grpc/grpc/blob/31bdbbeacf84d3a1e867e50b312c9cf46afc20db/cmake/cares.cmake

Why I think it's not useful:
if you are building with gRPC_CARES_PROVIDER=module, you can easily use the c-ares source code from the git submodule and you don't need to reconfigure CARES_ROOT_DIR.

If you are building with gRPC_CARES_PROVIDER=package (and c-ares is preinstalled somewhere on your system via cmake install), you need to use c-ares_DIR variable to configure cmake's find_package( ) to correctly locate c-ares instead.
