### ISSUE TITLE
Issue implementing async streaming client in C++

### ISSUE THREAD

**Issue by lcdupree** [grpc/grpc#10914]
I'm implementing a C++ client that interacts with a Python server that offers a set of bidirectional streaming RPCs. The current test method on the server sends back a set of responses that contain an incrementing integer.

The C++ client uses a completion queue and there is a dispatch loop that is called on an interval that does a CompletionQueue.AsyncNext, looks up the handler for a tag, dispatches a callback, and if the handler hasn't been marked as canceled, submits another Read call against the AsyncReaderWriter. The tag is just an incrementing integer.

If I call the server test Rpc once this seems to work and I get a flurry of responses, each associated with an enqueued Read/Tag pair. On the second call to the same server test Rpc the code crashes inside of CompletionQueue::AsynNextInternal on the call to cq_tag->FinalizeResult. The tag value associated with the ev struct is nonsensical -- something like 0x000000002c4a3eb0, a number I never used or enqueued.

I'm exhausting the things to try to get to the bottom of this. The documentation on behavior is a bit sparse on the async pattern stuff, but I believe I'm implementing it correct and have looked at as many examples as I could find. Any assistance would be appreciated.

**Comment by vjpai** [comment]
When you say flurry, can you clarify one thing? Are you ever initiating
more than one read at a time concurrently for a single stream? Because that
would not be allowed. There can only be one read and one write at a time
concurrently for each stream.

As for general debugging bits, which version of grpc are you working with?
Some specific release or at head? Also, what is your platform?

**Comment by lcdupree** [comment]
Amazon Linux server, Windows 7 client.
Client GRPC version is v1.0.1, I believe the same for the server but have to double-check.

And yes, definitely respecting the one outstanding read per stream (rpc?). Once a tag is retrieved, if the handle we are storing that is mapped to that tag has not been marked as canceled only then will we enqueue another read.

**Comment by lcdupree** [comment]
Finally got to the bottom of this... looks like message associated with the last Read() on a previously canceled rpc was freed ahead of call to cq.AsyncNext.

**Comment by vjpai** [comment]
Glad that you were able to solve this!
