### ISSUE TITLE
Question: Where are the release notes?

### ISSUE THREAD

**Issue by relwell** [grpc/grpc#10910]
It would be fantastic if we had clear release notes linked to the README for each specific language. This will help us reason over library compatibility problems.

It seems that releases are revealed as metadata in the annotated tags as well, but it's worth noting that this information will not be available in resources that are not Git-aware. It would be preferable to have this information in a flat text file at the root of each individual project directory.

**Comment by murgatroid99** [comment]
The release notes can be found at https://github.com/grpc/grpc/releases

**Comment by relwell** [comment]
@murgatroid99 I've added some additional detail to my issue -- we can't assume everything that uses this library as a dependency will do so through Git. Doesn't it make sense to maintain these notes as an artifact that can be referred to in the source?

**Comment by nicolasnoble** [comment]
I'm not against the idea of flattening the release notes into a text file. However, we've typically done the notes so far after the release has been done. Making sure everything is in sync with a changelog file would significantly slow down our release process, which is already a tad bit too slow for our taste.

**Comment by relwell** [comment]
@nicolasnoble that's a fair point, but it's important to note that there are many dependency management systems that don't do a good job of accommodating version pinning (e.g. npm without shrinkwrap, golang).

Without having release notes to guide backwards-incompatible updates, we're often blindly updating to the latest version and hoping nothing breaks, and then not knowing why it's broken when it does.

**Comment by nicolasnoble** [comment]
So, define backwards-incompatible updates ? We've been really hard at work to make sure we're following semver in every aspect of the release process of gRPC. Meaning that if you upgrade to a 1.x version and something breaks, that would be an actual bug we'd need to hurry to fix.

I'm kind of trying to say we're trying to do one better: you shouldn't care about reading the release notes if all you're doing is blindly updating to the latest version.

**Comment by relwell** [comment]
That's certainly a fair point in theory, but a very hard aspiration to live up to in practice -- particular when trying to support such a large number of languages simultaneously. I would encourage you to take advantage of your community in the course of identifying these very scenarios by better empowering them to help identify the sources of bugs as they are introduced. I think I'll leave it at that.
