### ISSUE TITLE
Grpc server stacking authentication calls

### ISSUE THREAD

**Issue by AhmadChaker** [grpc/grpc#10926]
I'm using C# with client and server authentication. 
I am launching 200 clients simultaneously on my machine and connecting to a server on another machine.
I've noticed that the first call to the server from each client (so authentication needs to occur) seems to cause the first call to "stack".
i.e. Since the clients are essentially executing their first call simultaneously, assuming SSL authentication takes 50 ms, the first client will take 50ms to authenticate, the second client takes 100 ms, third client takes 150ms, so it seems as though the clients wait their turn to authenticate.
There seems to be separate streams for subsequent server calls as I can see that clients can make calls to other RPCs with very quick response times, all the while other clients are still authenticating.

Is there a way to enable some sort of SSL multithreading on the server end ?

Edit: This behavior has been replicated using C++ servers and clients.
![image](https://cloud.githubusercontent.com/assets/20714770/25644781/034006a2-2fec-11e7-8ddb-687f79cd2706.png)

**Comment by jboeuf** [comment]
@ctiller @markdroth @vjpai 

Is there a way to replicate that and track which mutex is being hit hard in this scenario?

**Comment by jtattermusch** [comment]
@AhmadChaker  can you provide a snippet to reproduce?
Is this happening on windows or linux?
What gRPC version?

**Comment by jtattermusch** [comment]
@AhmadChaker  are you still experiencing this behavior? Is it windows, linux or macos?
