### ISSUE TITLE
API to fetch peer certificate

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc#10927]
Hi, I am looking for an API to examine the client's certificate on the server. The closest thing I found so far is `grpc.ServicerContext.peer()` which returns the client's ip/port. Is there something I'm missing? I'm looking for a Python equivalent to this go code

```
import (
	"crypto/x509"

	"golang.org/x/net/context"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/peer"
)

// Extract client id from tls client cert.  If the client id is unavailable,
// this returns UnauthenticatedClient.
func FromContext(ctx context.Context) string {
	p, ok := peer.FromContext(ctx)
	if !ok || p == nil {
		return UnauthenticatedClient
	}
	certs := []*x509.Certificate{}

	switch info := p.AuthInfo.(type) {
	case credentials.TLSInfo:
		certs = info.State.PeerCertificates
	default:
		return UnauthenticatedClient
	}

	// Always use the first peer certificate's id.
	return certs[0].Subject.CommonName
}
```

**Comment by kpayson64** [comment]
This is currently not supported in Python

**Comment by dzbarsky** [comment]
I hope you assigning this to yourself means this will get exposed? :)

**Comment by nathanielmanistaatgoogle** [comment]
@dzbarsky: this smells like a duplicate of [issue 7710](https://github.com/grpc/grpc/issues/7710); do you agree?

**Comment by dzbarsky** [comment]
Yes, that's a dupe. Thanks!
