### ISSUE TITLE
Certificates test handshake

### ISSUE THREAD

**Issue by patricia93sousa** [grpc/grpc#10928]
I need a program to test the certificates pem/key of a server-client peer-to-peer.

I saw that [here](
https://github.com/grpc/grpc/tree/b81fb794a397b053df0d4bed7b1525a0ff51535f/test/core/handshake), I can make this test of handshake. But how can I run this example? 
I tried to make 
```
 gcc client_ssl.c -o client
client_ssl.c:34:37: fatal error: src/core/lib/iomgr/port.h: No such file or directory
compilation terminated.

```

Any help? If you have a suggestion of another client to my goal, please say me. I need something like an OpenSSL client - server that communicates, but I need a client that verificates in CA the certificates (in the network), and not locally self-signed. I already have the certificates generated by [easypki](https://github.com/google/easypki), I only need a program to put them and verify in order to establish a secure connection.

**Comment by jayantkolhe** [comment]
Please use bazel with BUILD file in the directory to compile and run.

**Comment by jayantkolhe** [comment]
Please reopen if that does not work.
