### ISSUE TITLE
Compatibility with LITE_RUNTIME

### ISSUE THREAD

**Issue by pruthvikar** [grpc/grpc#10939]
Currently, the grpc generated files will fail to compile  when the proto files are generated with life runtime.

This would be a great addition for setting up a grpc server on iOS and android without including the large libprotobuf libraries.

**Comment by hsaliak** [comment]
Assigning to @srini100 to triage, this also applies to java.

**Comment by pruthvikar** [comment]
Turns out this already exists for c++. You need to compile using GRPC_USE_PROTO_LITE as a flag. :)

Unsure about java

**Comment by srini100** [comment]
If any further questions please post on [grpc.io](https://groups.google.com/forum/#!forum/grpc-io) or [protobuf](https://github.com/google/protobuf)
