### ISSUE TITLE
PHP: Unable to upload 1.3.0 release to pecl

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#10940]
This is starting to worry me so I am logging an issue to track.

I was unable to upload the `1.3.0` release for PHP to [PECL](pecl.php.net). 

Here's my usual routine:
- Run `pear package` on the root directory of this repo. This will generate the pecl package `grpc-1.3.0RC1.tgz`.
- Go to pecl.php.net. Login. There's a link to "Upload Release". I choose the .tgz file above and click Upload.

But now, I am getting an error
```
ERROR:
No file has been uploaded.
```
after I click the Upload button.  I have been doing this for over a year and there was no error before this release. There are other packages out there that has uploaded new release since I got this error so the error does not seem to appear to affect everybody.

**Comment by mcos** [comment]
Piggybacking on this issue: Can we get the `v1.3.0` tagged release uploaded to PECL?

**Comment by stanley-cheung** [comment]
We are working on version `v1.3.2RC1` right now with a couple of important bug fixes. So please stay tuned.

**Comment by mcos** [comment]
Thanks @stanley-cheung, I appreciate that, I'm just concerned that the versions made available through `composer` are not aligned with those available via `PECL`. How should we handle this?

**Comment by stanley-cheung** [comment]
When we release `v1.3.2`, both pecl and composer will be of version `v1.3.2`. But in any case, the API didn't change so `v1.3.2` pecl will work with `v1.3.0` composer.
