### ISSUE TITLE
GRXBufferedPipe suffers from race condition in writeValue

### ISSUE THREAD

**Issue by jdimond** [grpc/grpc#10957]
Using `GRXBufferedPipe` triggers a crash: "Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'A precondition for calling grpc_call_start_batch wasn't met. Error 8'". This can be reproduced by calling `writeValue:` on `GRXBufferedPipe` in a loop. 

The underlying issue is that while all changes to the `state` property synchronized, they are synchronized on the `GRXWriter` instance the caller was passed in, rather than a common shared object. For example, `GRPCCall` synchronizes on it's `requestWriter` which is a `GRXForwardingWriter`, while the actual update of the `state` property is forwarded to the underlying `GRXBufferedPipe`. This makes it impossible to synchronize calls to `writeValue:` from the user of `GRXBufferedPipe`.

The `state` property is then accessed in `writeValue:` (https://github.com/grpc/grpc/blob/master/src/objective-c/RxLibrary/GRXBufferedPipe.m#L81) through `shouldFastForward`. However, that access is unsynchronized and races with updates from `writeBufferUntilPausedOrStopped` which is called on the `GRPCCompletionQueue` and is outside of the user of `GRXBufferedPipe`.

What happens in sequence is after being in the paused state, the state is changed to started and `writeBufferUntilPausedOrStopped` is called. That code takes the write and passed it to the layer below but before the state is updated to paused, it can happen that `writeValue:` is called on a different thread and `shouldFastForward` still returns true because the state is still started. `writeValue:` then also proceeds to pass the write on to the layer below. Because both writes were passed to the layer below, it causes a state violation in the C layer triggering the crash.

**Comment by jcanizales** [comment]
That must have been a heck of a thing to figure out. Thanks for the details, and sorry for the trouble! I think we have a super nice solution that @muxi is gonna try.

**Comment by muxi** [comment]
Resolved by #11070.
