### ISSUE TITLE
Performance tests timing out

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#10962]
Here are the last few lines from the log:

"""
09:46:15 {u'locks_per_iteration': u'15.0274', u'cpu_scaling_enabled': False, 'fixture': u'MinInProcessCHTTP2', 'request_size': 0.0, u'bytes_per_second': 544428321, u'date': u'2017-05-02 15:30:19', 'server_mutator': u'NoOpMutator', u'time_unit': u'ns', u'iterations': 13360, u'atm_add_per_iteration': u'198.281', 'client_mutator': u'NoOpMutator', u'library_build_type': u'release', u'allocs_per_iteration': u'12.0445', u'mhz_per_cpu': 2300, u'cpu_time': 52298, u'name': u'BM_UnaryPingPong', u'atm_cas_per_iteration': u'36.5201', u'nows_per_iteration': u'6.01272', u'num_cpus': 32, u'label': u'locks/iter:15.0274 atm_cas/iter:36.5201 atm_add/iter:198.281 nows/iter:6.01272 allocs/iter:12.0445 writes/iter:2.01214', 'cpp_name': u'BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/32k', 'response_size': 32768.0, 'jenkins_job': 'gRPC_performance_pull_requests', u'writes_per_iteration': u'2.01214', u'real_time': 52301, 'jenkins_build': '11697'}
10:07:00 {u'locks_per_iteration': u'15.0412', u'cpu_scaling_enabled': False, 'fixture': u'MinInProcessCHTTP2', 'request_size': 32768.0, u'bytes_per_second': 853150090, u'date': u'2017-05-02 15:30:19', 'server_mutator': u'NoOpMutator', u'time_unit': u'ns', u'iterations': 9347, u'atm_add_per_iteration': u'210.443', 'client_mutator': u'NoOpMutator', u'library_build_type': u'release', u'allocs_per_iteration': u'14.0682', u'mhz_per_cpu': 2300, u'cpu_time': 77311, u'name': u'BM_UnaryPingPong', u'atm_cas_per_iteration': u'37.7933', u'nows_per_iteration': u'6.01914', u'num_cpus': 32, u'label': u'locks/iter:15.0412 atm_cas/iter:37.7933 atm_add/iter:210.443 nows/iter:6.01914 allocs/iter:14.0682 writes/iter:2.01827', 'cpp_name': u'BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, N[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
10:07:00 Finished: FAILURE
"""

For the full log, see:

https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/11697/console

**Comment by vjpai** [comment]
Is this happening at master also?

**Comment by jtattermusch** [comment]
Also seen here: https://github.com/grpc/grpc/pull/10985

**Comment by jtattermusch** [comment]
I've seen this one: `19:10:04 Build timed out (after 90 minutes). Marking the build as failed.`

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/11768/

**Comment by jtattermusch** [comment]
I set the timeout for gRPC_performance_pull_requests to 120 min (was 90), but we really should have performance smoketest taking that long.

**Comment by ncteisen** [comment]
I have a hunch that bm_diff.py hangs in certain scenarios and causes this. Haven't been able to consistently reproduce yet.
