### ISSUE TITLE
Method to terminate python client

### ISSUE THREAD

**Issue by wisotzky** [grpc/grpc#10974]
While implementing a gRPC client, I was just wondering if there are any ways to terminate a gRPC call.

Example from my gNMI client:
```
    try:
        responses = stub.Subscribe(req_iterator, options.timeout, metadata=metadata)
        for response in responses:
            if response.HasField('sync_response'):
                log.debug('Sync Response received\n'+str(response))
            elif response.HasField('error'):
                log.error('gNMI Error '+str(response.error.code)+' received\n'+str(response.error.message))
            elif response.HasField('update'):
                log.info('Update received\n'+str(response))
            else:
                log.error('Unknown response received:\n'+str(response))
```
The gNMI API is defined [here](https://raw.githubusercontent.com/openconfig/reference/master/rpc/gnmi/gnmi.proto).

The return value of the `Subscribe()` RPC is a stream. Using the implementation above, the loop is executed until the connection is terminated by the server, connection problems between server/client occur or if any other exception is raised (CTRL-C causing `KeyboardInterrupt` exception).

To change the subscription (modify the `req_iterator`) it is required to terminate the current subscription and to request a new subscription with the updated `req_iterator`.

I am a bit confused, how to terminate the current subscription. Potentially I could just exit the loop after the next update has been received. This would allow you to run a new subscription from the same thread - but it would neither terminate the first `Subscription()` nor release related resources. Also it requires to wait for the next update message, which could be hours later - while users might want changes to get accepted immediately.

Is there any API to terminate the `Subscribe()` call? Is there any form of subscription identifier needed, to tell gRPC, which session to terminate (part of meta-data)?

**Comment by nathanielmanistaatgoogle** [comment]
Your `responses` object has a `cancel` method.

But reading your question as a whole, I'm not certain that cancelling your RPC is the best thing to do. You are able to pass _any iterator of request messages_ as your `req_iterator` object - so why not pass an instance of some class completely under your control that is able to respond and change as it needs to respond and change over the course of your RPC? In particular, your statement "To change the subscription (modify the `req_iterator`) it is required to terminate the current subscription and to request a new subscription with the updated `req_iterator`" is simply not true - your `req_iterator` is always an object completely under your control at all times; the only thing gRPC Python does with it is ask it to emit request messages.
