### ISSUE TITLE
Ubsan doesn't like grpc.

### ISSUE THREAD

**Issue by fengli79** [grpc/grpc#10998]
Gets following errors when start a GRPC server with ubsan.

I0504 14:17:53.823168591  546962 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
third_party/grpc/src/core/lib/support/stack_lockfree.c:140:15: runtime error: left shift of 1 by 63 places cannot be represented in type 'gpr_atm' (aka 'long')
    #0 0x7f3e47d59f5e in gpr_stack_lockfree_push third_party/grpc/src/core/lib/support/stack_lockfree.c:140:15
    #1 0x7f3e4768d18a in grpc_server_start third_party/grpc/src/core/lib/surface/server.c:1104:7
    #2 0x7f3e481dc381 in grpc::Server::Start(grpc::ServerCompletionQueue**, unsigned long) third_party/grpc/src/cpp/server/server_cc.cc:516:3
    #3 0x7f3e481c098a in grpc::ServerBuilder::BuildAndStart() third_party/grpc/src/cpp/server/server_builder.cc:340:16
    #4 0x7f3e491c0248 in grpc::gateway::testing::EchoServer::Start() net/grpc/gateway/testing/interop/grpc/echo_server.cc:22:21
    #5 0x551024 in grpc::gateway::testing::TestEnvironment::SetUp() net/grpc/gateway/testing/interop/grpc/grpc_web_grpc_interop_test.cc:65:13
    #6 0x7f3e485bfbb5 in void (*std::for_each<__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, void (*)(testing::Environment*)>(__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, __gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, void (*)(testing::Environment*)))(testing::Environment*) 
    #7 0x7f3e48580ab4 in testing::internal::UnitTestImpl::RunAllTests() third_party/gtest/src/gtest.cc:4683:7
    #8 0x7f3e48580534 in testing::UnitTest::Run() third_party/gtest/src/gtest.cc:4304:10
    #9 0x53444e in main net/grpc/gateway/testing/interop/grpc/grpc_web_grpc_interop_test.cc:533:10

SUMMARY: UndefinedBehaviorSanitizer: invalid-shift-base third_party/grpc/src/core/lib/support/stack_lockfree.c:140:15

**Comment by ctiller** [comment]
Which version of gRPC?

We haven't enabled ubsan yet, but a few of us have been chipping away at
problems.

**Comment by vjpai** [comment]
This is definitely not an issue at master. This was some old debug code (ironically) removed in #10747

**Comment by fengli79** [comment]
Yes, it's on our internal p4 head. Happy to know it has been resolved on github. We would just wait for next import.
