### ISSUE TITLE
TSI_INTERNAL_ERROR after upgrade to grpc 1.3.0

### ISSUE THREAD

**Issue by alexodus** [grpc/grpc#11011]
After upgrade to server python to grpcio 1.3.0 (and after regenerating proto files)
I have this:
`
E0505 20:13:50.851834103   32645 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
`
`
E0505 20:13:50.851868188   32645 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
`

and often

`
E0505 20:13:33.406171300   32645 chttp2_server.c:83]         Handshaking failed: {"created":"@1494015213.406134120","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.c","file_line":239,"referenced_errors":[{"created":"@1494015213.406130326","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":456,"referenced_errors":[{"created":"@1494015213.406108664","description":"Handshake timed out","file":"src/core/lib/channel/handshaker.c","file_line":241}]}]}
`

The client code is Java (1.2.0 or 1.3.0). The certificate is generate by letsencrypt.

**Comment by Olical** [comment]
Same error from the node client to a Java backend at 1.3.0.

```
E0508 09:30:37.866195781    8902 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0508 09:30:37.866236501    8902 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
```

**Comment by Olical** [comment]
Out of interest, does your error occur on Linux, @alexodus? (mine does, I haven't tried it on OSX etc)

**Comment by maxkondr** [comment]
I have the same error on C++ server. It appears just after client closes connection like
conn.Close()

**Comment by jayantkolhe** [comment]
Julien, any ideas?

**Comment by jboeuf** [comment]
I had a look and the TSI code has basically not changed (except for some refactoring of the handshaker factories which we should probably rule out here). 

The error may be triggered by changes on the upper layers (socket/endpoint) and how they are feeding data to TSI. 
I could see how the `E0505 20:13:50.851834103 32645 ssl_transport_security.c:429] SSL_read returned 0` could get triggered and actually think that we should return OK when we cannot read anything from SSL_read. I'll issue a PR shortly to take care of this one.

For the `file":"src/core/lib/security/transport/security_handshaker.c","file_line":2391` error, it looks like the server is waiting for a client message since the handshake is not done on the server side and not getting anything. Not sure how to repro this one. @yang-g @markdroth any idea here?

**Comment by jboeuf** [comment]
Re `E0505 20:13:50.851834103 32645 ssl_transport_security.c:429] SSL_read returned 0`. It could also be that the semantics of boringssl have changed for SSL_read...

**Comment by maxkondr** [comment]
@jboeuf what info is required from my side to help you with this issue ?

**Comment by jboeuf** [comment]
Can you try to patch https://github.com/jboeuf/grpc/commit/9ffcb8ad39403593459bcd0dd5d8626b67e63094 and run again to see what you get in the logs (if anything)?
Thanks much.

**Comment by maxkondr** [comment]
I have applied this patch and now it prints:
`E0511 11:41:23.059811313    6798 ssl_transport_security.c:459] SSL_read failed with error SSL_ERROR_ZERO_RETURN.`
`E0511 11:41:23.059841972    6798 secure_endpoint.c:185]      Decryption error: TSI_PROTOCOL_FAILURE`

**Comment by jboeuf** [comment]
Thanks @maxkondr 

That makes sense. According to the openSSL doc, this happens when a closure alert is received:
https://www.openssl.org/docs/man1.1.0/ssl/SSL_get_error.html
https://tools.ietf.org/html/rfc5246#section-7.2.1

I agree that the TSI error and subsequent secure_endpoint.c log is misleading and we should probably fix that. Is this the object of this bug or is it something deeper? I believe that at the TSI level, this behavior should be expected when the client closes the connection. Do you agree?

**Comment by maxkondr** [comment]
well, sounds reasonable....

**Comment by jboeuf** [comment]
@maxkondr do you mean the patch that changes the error messages? I will try to have one today but not sure I'll be able to get to it.

@Olical @alexodus does this error also occur when the connection is closed from the peer? Do you agree that the behavior is basically "Working as Intended" except for the error mapping / propagation or is there something more alarming going on in your experience?

**Comment by alexodus** [comment]
mmmh, the error happen when on the client perform a rpc call with error (in server and client side).

**Comment by jboeuf** [comment]
@maxkondr I definitely agree with your statement that if there is no issue with connection closing, there should not be any errors. I'll have a patch out shortly.

@alexodus do you have some logs on the java client side that would indicate what is going on? I recently removed some cipher suites in the core C stack that were not HTTP2 compliant (blacklisted). It may be that your java client cannot handle the compliant ones. 
The PR is https://github.com/grpc/grpc/pull/10772 
Maybe you can try to set the cipher suites manually with the env var: `GRPC_SSL_CIPHER_SUITES`
to the old default ones (which contains the blacklisted ones): `ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384`. Note that I don't recommend using the blacklisted cipher suites in production...

**Comment by jboeuf** [comment]
@alexodus Actually I would be surprised if it were a cipher suite problem as the alert is received after the handshake is done. Anyway, logs on the client would be helpful in any case. Thanks!

**Comment by alexodus** [comment]
ok, this weekend i'll provide you my logs (client in android/java and server in python 2.7).

**Comment by jboeuf** [comment]
@alexodus thanks.
@maxkondr can you try the new patch?
 https://github.com/jboeuf/grpc/commit/ab9bc721304a289632ac1d224724f9174a0f471b

**Comment by maxkondr** [comment]
@jboeuf the latest patch helped.  There are no errors neither on server nor on client side during connection shutdown.
Thanks.

**Comment by alexodus** [comment]
Client: java/android, grpc 1.3.0 (same results with grpc 1.2.0)
```
05-14 20:24:30.070 2033-2144/com.jobba.me D/ProfileProvider: [getProfile] error:io.grpc.StatusRuntimeException: UNAVAILABLE
05-14 20:24:30.070 2033-2033/com.jobba.me D/StartController: [lambda$doGetProfile$5] onError:io.grpc.StatusRuntimeException: UNAVAILABLE
```

the detail of the error is this:
```
io.grpc.StatusRuntimeException: UNAVAILABLE
    	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227) ~[na:0.0]
    	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208) ~[na:0.0]
    	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141) ~[na:0.0]
    	at com.jobba.me.protocol.JobbaServiceGrpc$JobbaServiceBlockingStub.getProfile(JobbaServiceGrpc.java:1518) ~[na:0.0]
    	at com.jobba.me.providers.ProfileProvider.getProfile(ProfileProvider.java:127) ~[na:0.0]
    	at com.jobba.me.ui.controllers.StartController.lambda$doGetProfile$3(StartController.java:158) ~[na:0.0]
    	at com.jobba.me.ui.controllers.StartController$$Lambda$4.call(Unknown Source) ~[na:0.0]
    	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:41) ~[na:0.0]
    	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:29) ~[na:0.0]
    	at rx.Single.subscribe(Single.java:1967) ~[na:0.0]
    	at rx.Single$13$1.call(Single.java:2039) ~[na:0.0]
    	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) ~[na:0.0]
    	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[na:0.0]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) ~[na:0.0]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
    Caused by: java.io.IOException: PROTOCOL_ERROR invalid settings id: -509
    	at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:589) ~[na:0.0]
    	at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:47) ~[na:0.0]
    	at io.grpc.okhttp.internal.framed.Http2$Reader.readSettings(Http2.java:304) ~[na:0.0]
    	at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:162) ~[na:00]
    	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:868) ~[na:0.0]
    	... 3 common frames omitted
```

Server: python 2.7, grpcio 1.3.0
```
E0514 18:25:52.086246800   31522 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0514 18:25:52.086278226   31522 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
E0514 18:25:53.255994191   31522 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0514 18:25:53.256027474   31522 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
E0514 18:25:54.754042667   31522 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0514 18:25:54.754073034   31522 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
E0514 18:25:57.276323568   31522 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0514 18:25:57.276358200   31522 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
E0514 18:26:02.134398336   31522 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0514 18:26:02.134430648   31522 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
E0514 18:26:09.914237780   31522 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
E0514 18:26:09.914269613   31522 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
```

**Comment by jboeuf** [comment]
@maxkondr Thanks for confirming that the patch works.

@alexodus OK, so it looks like when you have an UNAVAILABLE on the client side, the new symptom on the server is that now you have these `Decryption error` popping up on the new 1.3 servers. I actually believe that this is the same issue that should be resolved by the patch: the `Decryption error` is very misleading in this case: it is just the client closing the connection. Does that make sense?

**Comment by alexodus** [comment]
Yes, it make sense! Now I can't test the patch, because I'm working in another project. So I'll wait the next minor release with this patch and I'll give you my feedback.

**Comment by jboeuf** [comment]
Thanks Alessandro.

**Comment by blerest** [comment]
@jboeuf When will you release a fix?

**Comment by jboeuf** [comment]
Sorry, just back from vacation. The PR mentioned above fixes the issue. Let me rebase with master and submit.

**Comment by blerest** [comment]
When do you plan to release a new version?

**Comment by jboeuf** [comment]
@blerest  Not sure, @nicolasnoble or @matt-kwong will probably know.

**Comment by matt-kwong** [comment]
It should be in August.

CCing @dgquintas to confirm.

**Comment by dgquintas** [comment]
Yes. The scheduled release date is the 29th of August
