### ISSUE TITLE
change maximum rpc message size

### ISSUE THREAD

**Issue by mmarkell** [grpc/grpc#11014]
I'm trying to call python grpc stub from golang, passing in a 30mb file, and am getting an error "Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Received message larger than max."

What can I do to increase the maximum message size passed in to the python grpc stub?

We are trying: 
```python
channel = grpc.insecure_channel("localhost:50001",options=[('grpc.max_message_length',1024*1024*1024),
('grpc.max_send_message_length',1024*1024*1024),
('grpc.max_receive_message_length',1024*1024*1024)])
```
But we still receive the same error message.

Thank you for your help,
Michael

**Comment by nathanielmanistaatgoogle** [comment]
Try running with `GRPC_VERBOSITY=DEBUG` and `GRPC_TRACE=ALL` - do you see any output about your message size options being honored (or not being honored)?

**Comment by nathanielmanistaatgoogle** [comment]
Closing; I hope my questions were helpful.

**Comment by yifeikong** [comment]
Maybe you should change it both from the server and client

**Comment by a-urth** [comment]
@yifeikong sorry is it even possible to change receive message max size from client perspective? i've hit same problem recently and it seems like there is no way to override `defaultClientMaxReceiveMessageSize`
