### ISSUE TITLE
"gRPC over HTTP2 protocol" doc does not allow request trailing metadata

### ISSUE THREAD

**Issue by stepancheg** [grpc/grpc#11017]
Request trailing metadata should follow data frames.

http://www.grpc.io/docs/guides/wire.html#outline

Wire format doc specifies streams as:

```
Request → Request-Headers *Delimited-Message EOS
Response → (Response-Headers *Delimited-Message Trailers) / Trailers-Only
```

There are no trailers in request, where trailing metadata should be.

**Comment by murgatroid99** [comment]
The spec is correct. The gRPC protocol simply does not have trailing request metadata, and that document's omission of it in the specification of how gRPC is implemented over HTTP2 accurately reflects that.

**Comment by stepancheg** [comment]
Thanks!
