### ISSUE TITLE
socket leak on nodejs since 1.2.0

### ISSUE THREAD

**Issue by blerest** [grpc/grpc#11015]
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
```
```
node v6.10.3
```
```
cd
git clone https://github.com/grpc/grpc/
cd grpc/examples/node/dynamic_codegen
sudo npm install grpc
node greeter_server.js &
node greeter_client.js
node greeter_client.js
node greeter_client.js
node greeter_client.js
lsof -n | grep 14822
```

```
node      14822 14860          root   11u     IPv6             458991      0t0        TCP *:50051 (LISTEN)
node      14822 14860          root   12u     sock                0,7      0t0     459011 can't identify protocol
node      14822 14860          root   13u     sock                0,7      0t0     459027 can't identify protocol
node      14822 14860          root   14u     sock                0,7      0t0     459043 can't identify protocol
node      14822 14860          root   15u     sock                0,7      0t0     459059 can't identify protocol
```

You can wait x hours -- the sockets never close.

**Comment by murgatroid99** [comment]
Thank you for reporting this. We should have a fix in the next release.

**Comment by rafaelsales** [comment]
@murgatroid99 can you confirm this is happening on other language implementations as well?
I'm getting `tcp_server_posix.c:245]     Failed accept4: Too many open files` very often from a grpc server, and the `lsof` shows hundreds of `can't identify protocol`

**Comment by rafaelsales** [comment]
@murgatroid99 I saw that node had the fix on 1.3.5, but the ruby impl is still on 1.3.5. I saw the PR referenced here had changes on grpc core. Do you think a new release for ruby would fix this?

**Comment by murgatroid99** [comment]
@apolcyn Can you look into this in Ruby?

**Comment by rafaelsales** [comment]
@apolcyn news on this? I'm having socket leak in for grpc-ruby

**Comment by rafaelsales** [comment]
@apolcyn @murgatroid99 I can reproduce the same bug on ruby...

**Comment by apolcyn** [comment]
> @apolcyn @murgatroid99 I can reproduce the same bug/leak in ruby...

The long-opened sockets as seen by `lsof` seems easy to reproduce.

This <i>looks</i> like it's to be due to server-side calls not getting garbage collected timely enough (currently, the non-deterministic garbage collection on server-side calls will release underlying resources... looking into 
 a fix).

**Comment by ravikamaraj** [comment]
My application runs on nodejs (v7.4.0), and I had tried with multiple versions of gRPC (1.4.1, 1.6.0) and socket leak is still occurring

**Comment by murgatroid99** [comment]
@ravikamaraj That looks like a different problem than the one originally described in this issue. Please open a separate issue to handle that problem.
