### ISSUE TITLE
gRPC C++ doxygen audit suggestions/change requests

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#11022]
- `grpc::Server.Wait` says blocks till “all work” is complete. Please consider being more explicit with what is “all work”? pending RPCs? Under what circumstances should the user need to call it?
- `ServerBuilder::SyncServerOption` and `SetSyncServerOption` lacks documentation
- `ServerBuilder::AddCompletionQueue` talks at length about why `is_frequently_polled` should not be set to false, but does not mention an example valid use case for that scenario.
- `CreateChannel`: clarify what a “lame” cannel is.
- `security/auth_metadata_processor.h`: add class description comment
- Comments in `async_generic_service`
- Add documentation for `impl/codegen/{call.h,service.h,rpc_method.h}` even though they are under `impl`?

**Comment by markdroth** [comment]
With regard to that last bullet, I think the main thing to consider for any given API is whether or not that API is used directly by users (i.e., anything that is effectively part of gRPC's public API).  Anything that is in that category (which especially includes the various Reader/Writer class used by the interfaces in the generated code) needs to be thoroughly documented.  Anything that isn't in that category isn't that important to document, at least at this point.

**Comment by mehrdada** [comment]
Right. I specifically picked those three files since I thought they were core to further understanding of the system. I listed it mainly as a suggestion if there are resources to add some documentation. They are by no means essential.

**Comment by hsaliak** [comment]
@makdharma would you be able to help with the PRs needed for this?

**Comment by markdroth** [comment]
I believe that @mehrdada and @apolcyn are already working on this.

**Comment by mehrdada** [comment]
We identified and added where docs were missing. These items are the ones I could not confidently fix myself, so someone from the C++ side needs to take a look and amend the docs as they see fit.

**Comment by hsaliak** [comment]
Referencing #10992  and #10991 pull requests that contain fixes.

**Comment by markdroth** [comment]
@sreecha, can you provide info about this item?

> - `ServerBuilder::AddCompletionQueue` talks at length about why `is_frequently_polled` should not be set to false, but does not mention an example valid use case for that scenario.

It looks like you originally added this option in #6612, but it doesn't appear to be used anywhere except for hybrid_end2end_test.  Is this option still going to be needed after the completion queue API changes you're working on?

**Comment by markdroth** [comment]
@yang-g, can you take care of adding comments in `async_generic_service.h`?  This is probably not high priority, but it shouldn't take long to do the basics here.

**Comment by markdroth** [comment]
With regard to this item:

> - Add documentation for `impl/codegen/{call.h,service.h,rpc_method.h}` even though they are under `impl`?

I don't think anything in those files is part of our public APIs, so I don't think we need Doxygen comments there.

I'll send out a PR with the remaining fixes.

**Comment by markdroth** [comment]
I don't think this is finished yet.  There are still two things that need to happen:

1. @yang-g needs to add comments in `async_generic_service.h`.
2. @sreecha needs to document the `ServerBuilder::AddCompletionQueue` parameter `is_frequently_polled`.
