### ISSUE TITLE
Ruby artifact build broken by converting lame client to C++

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11037]
Ruby and artifacts are not building thanks to https://github.com/grpc/grpc/pull/10427.
(in upstream/master)

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/3391/architecture=x64,language=ruby,platform=linux/console

```
/tmp/objs/opt/src/core/lib/surface/lame_client.o: In function `lame_start_transport_op':
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/src/core/lib/surface/lame_client.cc:135: undefined reference to `__stack_chk_fail'
/tmp/objs/opt/src/core/lib/surface/lame_client.o: In function `fill_metadata':
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/src/core/lib/surface/lame_client.cc:92: undefined reference to `__stack_chk_fail'
/tmp/objs/opt/src/core/lib/surface/lame_client.o: In function `lame_start_transport_stream_op_batch':
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/src/core/lib/surface/lame_client.cc:106: undefined reference to `__stack_chk_fail'
collect2: error: ld returned 1 exit status
make: *** [/tmp/libs/opt/grpc-4.dll] Error 1
```

**Comment by jtattermusch** [comment]
CC @ctiller

**Comment by jtattermusch** [comment]
The bottom line is we need artifacts build to run on every PR because we find ourselves fixing artifact build in almost every release (I have some work in progress to allow doing that - currently there are some artifact build limitations that are blocking it).

**Comment by nicolasnoble** [comment]
This is the Windows dll build by the way. I'm not fully surprised by this, but I'm not sure what's the proper way to fix it.

One acceptable method would be to declare this in a Windows-only source code:
```
void __stack_chk_fail(void) {
    abort();
}
```

**Comment by jtattermusch** [comment]
@apolcyn , any ETA?

**Comment by jtattermusch** [comment]
http://stackoverflow.com/questions/4492799/undefined-reference-to-stack-chk-fail

**Comment by jtattermusch** [comment]
My attempt here https://github.com/grpc/grpc/commit/b28247d00152d62a8b72b06f27cc11006e78649a is not helping.

**Comment by apolcyn** [comment]
thanks for the tips, hadn't gotten started here yet but I'll be taking a look at this today

**Comment by apolcyn** [comment]
right now https://github.com/apolcyn/grpc/commit/fb17b32243b9b38dfe85dec235cf50f9a8bb5e3f I think gets rid of this missing `stack_chk`, and an unrelated compilation failure.

But now there's a new problem:

The 32-bit windows dll target in the Rakefile results in: (though the 64-bit build succeeds)
```
[LD]      Linking /tmp/libs/opt/grpc-4.dll
/tmp/objs/opt/src/core/lib/surface/lame_client.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [/tmp/libs/opt/grpc-4.dll] Error 1
```
