### ISSUE TITLE
Node: Server crashed will cause Client segmentation fault in grpc 1.3.0+

### ISSUE THREAD

**Issue by VegeChou** [grpc/grpc#11036]
I have used gRPC 1.3.0+ in NodeJS.

Server and Client communicate each other by gRPC stream.

If Server crashed, the Client cloud catch 'Endpoint read failed' error ,and then Client was segmentation fault .

After I change gRPC version to 1.0.0, there is not found this problem.

**Comment by lanttu** [comment]
I noticed a minor API change when moving from earlier release to 1.3.x. Previously pushing data to already ended call stream got silently ignored, but now it's causing segfault. That could be the thing you are experiencing.

```js
const inputStream = ....;
const call = grpc.clientStreaming((err, res) => {
  // If this is called before the input stream has ended (e.g. in case of error)
  // you have to unpipe or make sure some otherway that data is no more
  // pushed to call.
  inputStream.unpipe(call);
});
inputStream.pipe(call);
```

**Comment by murgatroid99** [comment]
I am having a little trouble reproducing that failure on version 1.3.2. I wrote a test that explicitly attempts to write to the call in the response callback, and it works fine. Do you think you can put together a complete reproduction case?

**Comment by lanttu** [comment]
Here's an example code which causes segfault https://github.com/lanttu/grpc-segfault-test

I'm using Node 7.4.0 and macOS 10.12

**Comment by murgatroid99** [comment]
Thank you. With that example, I was able to reproduce the failure.
