### ISSUE TITLE
Add test coverage for generating code in local package

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#11041]
A user writes ["_I'm a new python programmer. Currently, we are switching from python2 to python3, and we found out all the python script generated by grpc have code like this._ `import dataPlatform_pb2 as dataPlatform__pb2` _However, python3 do not support this type of relative path import. I need to manually change it to_ `from . import dataPlatform_pb as dataPlatform__pb2` _Is there any better solution for this problem, it seems a bad practice to changing auto generated code all the time._"](http://stackoverflow.com/questions/43864859/no-module-error-for-python-generated-grpc-script)

I'm working on a change that should fix this issue, but we should also expand our test coverage to cover this case as well.

**Comment by tfrench** [comment]
Hi. I was wondering if there is an update on this? Thanks.

**Comment by nathanielmanistaatgoogle** [comment]
No update - it's very much fallen off my radar for now and isn't an active priority. (It may have been fixed - are you able to confirm that it's an active issue in gRPC Python 1.7.0 and later?)

That's not to say that it shouldn't be a priority - how severely are you affected? Can you share with us details about your use case and what you have to do to work around the behavior?

**Comment by tfrench** [comment]
Thanks for the no update. :)

It's still happening with 1.7.0. 

Exactly the same as described above. We're working to make our framework py2/py3 compatible. Currently, we manually edit the files (of which there are only a few), as described above. It works, but clearly it isn't ideal.

**Comment by nathanielmanistaatgoogle** [comment]
So... we have [a test of the code generator](https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/protoc_plugin/_split_definitions_test.py) that runs in both Python 2 and Python 3 with the same generated code, and that test passes, so I'd like to be able to say that there's an easy way through this obstacle. What's the difference between what the test tests and your case? Is it just that the generated module is intended to be used at program top-level (`import my_generated_module_pb2`) rather than from a package (`from my_package.my_subpackage import my_generated_module_pb2`)?

**Comment by tfrench** [comment]
Hi there. 

So... we happy that this is the issue (with solution included): https://github.com/grpc/grpc/issues/9575#issuecomment-293934506

Thanks.

**Comment by tvalentyn** [comment]
See https://github.com/protocolbuffers/protobuf/issues/1491 for a discussion of this issue.
