### ISSUE TITLE
Update the Cocoa README to recommend checking all pods into source control

### ISSUE THREAD

**Issue by macrael** [grpc/grpc#11050]
The instructions here: https://github.com/grpc/grpc/tree/master/src/objective-c recommending using a Podspec's prepare_command to generate proto/gRPC headers for your app.

Crucially, prepare_command is not executed when doing a `pod install` if the `Podfile.lock` already has the correct version in it. This means that if you check out a clean repository that does not commit their Pods directory and run `pod install` the proto compile step will never run and compilation will fail. The system described here will only work if you check your compiled protos into version control. 

I'll also note that this whole system seems somewhat against the design of cocoa pods in general, their maintainers have said repeatedly they are designing a distribution system, not a build system.

**Comment by muxi** [comment]
As to the issue, I tried with a clean repo and the `prepare_command` trick did work. I think you should probably not check in your `Podfile.lock`.

I do agree that this is not an ideal way of doing this. However we do think this fit a lot of people's need. A user may elect to check in their compiled proto if they want to, but using `prepare_command` helps guarantee the sanity (e.g. proto version mismatch issues).
