### ISSUE TITLE
Use GFlags and Benchmark only when tests enabled

### ISSUE THREAD

**Issue by KindDragon** [grpc/grpc#11068]
You can automatically set `gRPC_GFLAGS_PROVIDER=none` and `gRPC_BENCHMARK_PROVIDER=none` if `gRPC_BUILD_TESTS=OFF`
 
### What version of gRPC and what language are you using?
 1.3.1
 
### What operating system (Linux, Windows, …) and version?
 Windows

**Comment by Croydon** [comment]
This would make packaging easier :)

**Comment by Croydon** [comment]
@nicolasnoble Friendly ping 😄 

Since this doesn't seem to be complex, could this please be moved forward?

**Comment by Croydon** [comment]
Still valid AFAIK

**Comment by jtattermusch** [comment]
This actually might not be necessary, see the comment here: https://github.com/grpc/grpc/pull/20976#issuecomment-552509998
