### ISSUE TITLE
bm_fullstack_streaming_pump failure in performance PR Jenkins

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#11078]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 
master, C/C++ benchmarks 

### What operating system (Linux, Windows, …) and version?
 
 Linux on Jenkins

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 gcc-4.9

### What did you do?

Ran Jenkins test
 
### What did you expect to see?
 
All tests pass
 
### What did you see instead?
 
14:24:18 2017-05-10 21:24:18,066 FAILED: bm_fullstack_streaming_pump counters old 20/20 [ret=-15, pid=2390]

https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/11896/console

**Comment by ncteisen** [comment]
I think @ctiller's #11074 will fix this up
