### ISSUE TITLE
What exactly are the semantics of grpc_server_add_[in]secure_http2_port?

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11094]
The documentation of those functions is relatively scant. What patterns are accepted for the `addr` string argument, and how is it processed?

**Comment by nathanielmanistaatgoogle** [comment]
@makdharma and I also had this question arise in our documentation review last week.

**Comment by sreecha** [comment]
@murgatroid99 : I am assuming you probably figured this out on your own (since this bug is over 1 year old). If you did, can you share what you learned here :) and close the bug?
