### ISSUE TITLE
installDist fails to build

### ISSUE THREAD

**Issue by kstenerud** [grpc/grpc#11101]
### Should this be an issue in the gRPC issue tracker?
Yes 
 
### What version of gRPC and what language are you using?
 gRPC 1.3.0
Using java
 
### What operating system (Linux, Windows, …) and version?
 Linux (Ubuntu 17.04)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
openjdk version "1.8.0_121"
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
 
### What did you do?
./gradlew  installDist (as per http://www.grpc.io/docs/quickstart/java.html)

### What did you expect to see?
 A successful build
 
### What did you see instead?
```
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp
/home/karl/tmpo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:49: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
 #include <google/protobuf/io/zero_copy_stream.h>
                                                 ^
compilation terminated.

In file included from /home/karl/tmpo/grpc-java/compiler/src/java_plugin/cpp/java_generator.cpp:1:0:
/home/karl/tmpo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:49: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
 #include <google/protobuf/io/zero_copy_stream.h>
                                                 ^
compilation terminated.

In file included from /home/karl/tmpo/grpc-java/compiler/src/java_plugin/cpp/java_plugin.cpp:8:0:
/home/karl/tmpo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:49: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
 #include <google/protobuf/io/zero_copy_stream.h>
                                                 ^
compilation terminated.

:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp FAILED

FAILURE: Build failed with an exception.
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
It's a pretty fresh install of Ubuntu 17.04. No dev tools have been added to it beyond netbeans.

**Comment by ejona86** [comment]
You weren't in the `examples` directory. Make sure to `cd examples` first.
