### ISSUE TITLE
Can not open include file in grpc++_error_details building from Windows projects

### ISSUE THREAD

**Issue by amarcionek** [grpc/grpc#11136]
Please answer these questions before submitting your issue. 
  
### What version of gRPC and what language are you using?
master and 1.3.0
### What operating system (Linux, Windows, …) and version?
Windows 10 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2015
### What did you do?
Open Visual Studio pre-built projects and build entire solution.
### What did you expect to see?
All projects built correctly.
### What did you see instead?
`------ Build started: Project: grpc++_error_details, Configuration: Release x64 ------
  status.pb.cc
c1xx : fatal error C1083: Cannot open source file: 'E:\Source2\grpc\vsprojects\\..\src\proto\grpc\status\status.pb.cc': No such file or directory
  status.grpc.pb.cc
c1xx : fatal error C1083: Cannot open source file: 'E:\Source2\grpc\vsprojects\\..\src\proto\grpc\status\status.grpc.pb.cc': No such file or directory
  error_details.cc
E:\Source2\grpc\vsprojects\\..\src\cpp\util\error_details.cc(36): fatal error C1083: Cannot open include file: 'src/proto/grpc/status/status.pb.h': No such file or directory`
### Anything else we should know about your project / environment?
As indicated, I tried to build from master and from detached v1.3.0 tag.  
Since its a pb file, it seems that it should be generated by the build, but its not obvious to me which project is responsible. I'm going to guess the regular make works, but I don't have that option.

**Comment by johnco3** [comment]
I'm also encountering this issue

**Comment by mike07026** [comment]
yes, same problem, in version 1.3.2

**Comment by mike07026** [comment]
I meet the same problem,  and finally I found a way to solve it.

1. find src\proto\grpc\status\status.proto
2. use protoc.exe to generate status.pb.h status.pb.cc
3. use protoc.exe and grpc_cpp_plugin.exe to generate status.pb.grpc.h status.grpc.pb.cc
4. copy the files to the right place can fix the problem

**Comment by yang-g** [comment]
I talked with @jtattermusch and it seems this does not work when using the prebuilt projects because there is no hook there to do the auto code-generation. The cmake based way may work or you can use some workaround such as manual generation like @mike07026 did.

**Comment by amarcionek** [comment]
Visual Studio does support pre-build batch scripts. So long as protoc.exe and grpc_cpp_plugin.exe are in the PATH, there should be a way to script running the commands.  I could potentially give it a go and submit a PR (which would include a new batch file and change to the project file(s) at a minimum, IF you think this would be accepted.

Otherwise, if this can't be worked around, then it seems like a note should be added to https://github.com/grpc/grpc/tree/master/vsprojects to address that then?

**Comment by jtattermusch** [comment]
@amarcionek  there are several limitations in terms of pregenerated vsprojects:
1. compiling dependencies is hard (most deps support cmake, but generating a vsproj files for them is tricky). Also our nuget-based C++ deps are known to have issues.
2. protoc generation with visual studio is hard, cmakes provides a much better way.
3. we don't want too support multiple build solutions unless we have to and cmake seems to give us a better & cleaner solution.

I'll try to add a note that /vsprojects are obsolete and cmake (-> visual studio or ninja) is the official way to build on windows.

**Comment by amarcionek** [comment]
@jtattermusch, making the prebuilt projects obsolete seems fair. The very presence of those makes Windows users like myself go to them first. I've used cmake on other projects, to build the visual studio projects for the version using, and it's worked fine.  Thank you.
