### ISSUE TITLE
proxy grpc

### ISSUE THREAD

**Issue by magg** [grpc/grpc#11132]
Hi 

is it possible to proxy GRPC calls? Let's say I want install to a proxy in each microservice that communicates with GRPC. Will the proxy be able to handle GRPC?

**Comment by dopykuh** [comment]
GRPC is built on top of HTTP2, so it should be possible to use nginx or caddy to proxy it.

**Comment by mehrdada** [comment]
gRPC uses HTTP/2 trailers feature, whose support is in the works in nginx, and should land soon. In the meantime, https://github.com/lyft/envoy might be of help in your proxying needs.
