### ISSUE TITLE
Update contributing.md with CNCF CLA

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11130]
If not, CONTRIBUTING.md should be updated.

**Comment by zinuga** [comment]
yes, we need to update to CNCF CLA and point to that in updated contribution guidelines.

**Comment by jtattermusch** [comment]
Fixed:
https://github.com/grpc/grpc/blob/master/CONTRIBUTING.md

Remaining:
https://github.com/grpc/grpc-java/blob/master/CONTRIBUTING.md
https://github.com/grpc/grpc-go/blob/master/CONTRIBUTING.md
