### ISSUE TITLE
Unable to configure SSL credentials in a production environment

### ISSUE THREAD

**Issue by siacomuzzi** [grpc/grpc#11144]
Hi,
I'm trying no run a gRPC server in a production environment but I can't configure the SSL credentials (with `localhost` everything works es expected).

## Environment
* node.js 4.4.4
* grpc 1.3.2 (latest)

## Client

```
const protoDescriptor = grpc.load('./foo.proto').foo;
const clientRpc = new protoDescriptor.Foo(
  'autodiscovery.int.stage.foo.com:50051',
  grpc.credentials.createSsl(fs.readFileSync('foo.ca.pem')));

client.getUsers(function (err, users) {
  console.error('error', err);
  console.log('users', users);
});
```

## Server - Approach 1
Using `autodiscovery.int.stage.foo.com:50051` in `server.bind` method.

```
const creds = grpc.ServerCredentials.createSsl(null, [{
  private_key: fs.readFileSync('/etc/ssl/foo.key'),
  cert_chain: fs.readFileSync('/etc/ssl/foo.pem')  // CN=*.stage.foo.com
}]);

server = new grpc.Server();
server.addService(
  protoDescriptor.Foo.service, {
    getUsers: (call, cb) => { cb(null, { ... }); }
  });

server.bind('autodiscovery.int.stage.foo.com:50051', creds);
server.start();
```

When server starts, I see this warning:

```
832 server_secure_chttp2.c:96]  {"created":"@1494884784.722804820","description":"getaddrinfo failed","file":"../src/core/lib/iomgr/resolve_address_uv.c","file_line":96,"os_error":"unknown node or service"
```
and after a client's call, I don't have new logs server-side, only a client error:

```
{ [Error: Connect Failed] code: 14, metadata: Metadata { _internal_repr: {} } }
```

### Server- Approach 2
Using `'0.0.0.0:50051` in `server.bind` method.

```
const creds = grpc.ServerCredentials.createSsl(null, [{
  private_key: fs.readFileSync('/etc/ssl/foo.key'),
  cert_chain: fs.readFileSync('/etc/ssl/foo.pem')  // CN=*.stage.foo.com
}]);

server = new grpc.Server();
server.addService(
  protoDescriptor.Foo.service, {
    getUsers: (call, cb) => { cb(null, { ... }); }
  });

server.bind('0.0.0.0:50051', creds);
server.start();
```

After a client's call, I see a new log entry server side:

```
\tssl_transport_security.c:1253]\tNo match found for server name: autodiscovery.int.stage.foo.com.
```
and a client error:
```
{ [Error: Connect Failed] code: 14, metadata: Metadata { _internal_repr: {} } }
```

Can anyone please tell me what I'm doing wrong? Thanks!

**Comment by murgatroid99** [comment]
My understanding is that you can't have two levels of wildcards in a certificate name. So, `*.stage.foo.com` works for `int.stage.foo.com` but not `autodiscovery.int.stage.foo.com`.

@jboeuf Is that accurate? Are there any other issues you can see here?

**Comment by jboeuf** [comment]
@murgatroid99 this is correct. https://tools.ietf.org/html/rfc2818#page-5

> Matching is performed using the matching rules specified by
   [RFC2459].  If more than one identity of a given type is present in
   the certificate (e.g., more than one dNSName name, a match in any one
   of the set is considered acceptable.) Names may contain the wildcard
   character * which is considered to match any single domain name
   component or component fragment. E.g., *.a.com matches foo.a.com but
   not bar.foo.a.com. f*.com matches foo.com but not bar.com.

**Comment by siacomuzzi** [comment]
Got it, thanks for the quick response
