### ISSUE TITLE
service config in nodejs

### ISSUE THREAD

**Issue by siacomuzzi** [grpc/grpc#11153]
Hi,

Can anyone please provide me an example of how to set the [service config file](https://github.com/grpc/grpc/blob/master/doc/service_config.md) using the latest version of the [nodejs library](https://www.npmjs.com/package/grpc)?

Is the following correct?

```
var server = new grpc.Server({ "grpc.lb_policy_name": "round_robin" });
```

Thanks!

**Comment by murgatroid99** [comment]
The service config file is not used to configure server objects. It's used to configure how a client should access a particular service when making requests. On production systems, service configs should be obtained dynamically by a mechanism that has not been finalized yet.

The argument to server construction that you're looking at there actually has keys and values defined here: https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L149. One of those arguments is `"grpc.service_config"`, which can be used to pass a service config directly as a stringified JSON object. This should only be used for testing/development, and as mentioned, it will only be used on the client.

**Comment by siacomuzzi** [comment]
Got it. Thanks for the clarification
