### ISSUE TITLE
ServicerContext.is_active() not returning False following network disconnection

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#11157]
See [this StackOverflow question](https://stackoverflow.com/questions/43948975/grpc-unary-streaming-continues-after-disconnect-blocks-on-interrupt), [this `grpc-io` thread](https://groups.google.com/forum/#!topic/grpc-io/45LxvLyYVLk), and [this gist](https://gist.github.com/efritz/1417921e3d646184ee42606c069f7ada).

**Comment by nathanielmanistaatgoogle** [comment]
[This is happening for for `ServicerContext.add_callback` too](https://stackoverflow.com/questions/44243099/python-detect-client-drop-during-grpc-infinite-stream), which makes sense because in the current implementation both `is_active` and `add_callback` use the same underlying mechanism.

**Comment by kgreenek** [comment]
This bug is a show-stopper for us using the python implementation, because we can't tell when a client has disconnected. That means a thread is locked up forever whenever a client disconnects with no way to reclaim it, and we eventually exhaust all the threads in the pool.

Is there a work-around? Or some other way to detect when a client has disconnected? Thanks!

**Comment by ValedL** [comment]
@nathanielmanistaatgoogle 
Any progress/ETA on this?

**Comment by mehrdada** [comment]
@kgreenek @ValedL @efritz Can you observe the problem when building from source and not the `manylinux` binary pip package?

**Comment by mehrdada** [comment]
I just tried v1.6.3 pip package which is just released and am unable to observe the issue. Please reopen or file a new one with reproduction instructions if you continue to see it in 1.6.3 or newer. Thanks!

**Comment by sivabudh** [comment]
I am having this problem too. A server-side streaming `yield` will never unblock on client disconnect.

Server:
```
from concurrent import futures
import time
import grpc
import threading

import phi_pb2
import phi_pb2_grpc
import Messages_pb2


class GdiServicer(phi_pb2_grpc.GdiServicer):
    def GetPumpsStatus(self, request, context):
        print("Got request")
        msg = Messages_pb2.Messages()
        msg.m_port_id = 0
        msg.m_unit_id = 1
        msg.m_poll_id = 1
        msg.m_msgType = Messages_pb2.Messages.TYPE_STATUS

        status = Messages_pb2.Messages.Status()
        status.m_status_type = Messages_pb2.Messages.STATUS_OFF

        msg.m_status.CopyFrom(status)

        while context.is_active():
            print(f"{threading.get_ident()}: waiting..", end='', flush=True)
            time.sleep(3)
            yield msg                                                 # <––– yield never unblocks on client disconnect
            print("sent!")
        print("Done")


def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
    phi_pb2_grpc.add_GdiServicer_to_server(GdiServicer(), server)

    server_address = '0.0.0.0:60000'
    print(f"My server address {server_address}")
    server.add_insecure_port(server_address)
    server.start()
    try:
        while True:
            time.sleep(5)
    except KeyboardInterrupt:
        server.stop(0)

if __name__ == '__main__':
    print("I'm launching!")

    serve()
```

Client:
```
import grpc
import uuid


import Messages_pb2
import phi_pb2
import phi_pb2_grpc

def run():
    server_address = 'localhost:60000'
    with grpc.insecure_channel(server_address) as channel:
        stub = phi_pb2_grpc.GdiStub(channel)
        statusStreams = stub.GetPumpsStatus(phi_pb2.GdiReq())
        for status in statusStreams:
            print(f"{uuid.uuid1()} {status}")

if __name__ == '__main__':
    run()
```

**Comment by sivabudh** [comment]
@mehrdada Kindly see sample application to reproduce the error above.
