### ISSUE TITLE
assertation failed: pthread:_mutex_lock(mu) == 0

### ISSUE THREAD

**Issue by jopedroliveira** [grpc/grpc#11184]
Just got this error while using the grpc lib on C++ program. 
That program compilation went good but failed after run.

As far as I read, the error is quite familiar and some issues reported a solution... But in my case it remains unsolved.

sync posix.c:60] assertion failed: pthread_mutex_lock(mu) == 0

I'm running the master version of grpc on MacOs.

**Comment by ncteisen** [comment]
This is a duplicate of #10909. Closing.
