### ISSUE TITLE
Change the node ssl server credentials API so that a server can have multiple key/cert pairs.

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1121]
This is part of #161.

**Comment by ctiller** [comment]
@jboeuf, @jayantkolhe, @a11r - should this be beta?

**Comment by jboeuf** [comment]
We'll need an API change for the SSL server creds (assigned for beta, see #2527). We should probably fix this issue afterwards.

**Comment by ctiller** [comment]
@jboeuf - after our conversation a few days ago, it seems this should be in?

Should we file bugs against other languages also?

**Comment by jboeuf** [comment]
Sgtm.

On Thursday, July 30, 2015, Craig Tiller <notifications@github.com> wrote:

> @jboeuf <https://github.com/jboeuf> - after our conversation a few days
> ago, it seems this should be in?
>
> Should we file bugs against other languages also?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/issues/1121#issuecomment-126525090>.
>


-- 
Julien.
