### ISSUE TITLE
error with npm install

### ISSUE THREAD

**Issue by isabellewei** [grpc/grpc#11228]
I tried to run `npm install hfc`. I think the problem has something to do with `node-pre-gyp`. I've tried updating node, npm, xcode. I'm running macOS

The debug log won't show me anything above line 8004, not sure why:
https://gist.github.com/isabellewei/a5632a3956353d5b2b0d1130c9b20a81

**Comment by murgatroid99** [comment]
You're right, it does look like the problem is a `node-pre-gyp` failure. Unfortunately, as far as I can tell, that log doesn't contain any additional relevant information.

**Comment by isabellewei** [comment]
Is there any other information I could provide to try and solve this issue?

**Comment by murgatroid99** [comment]
Maybe there is something weird with how `node-pre-gyp` is logging information. What is the console output of running the command?

**Comment by murgatroid99** [comment]
Never mind, I see the problem. You're trying to install gRPC 1.0.0 on Node 7.10.0. That version of gRPC did not support that version of Node. You will either need to upgrade to a more recent version of gRPC or downgrade Node. Node 6 should be compatible.
