### ISSUE TITLE
[Node.js] Pre-built binaries not found for grpc@1.2.4 and node@6.9.5 on Windows

### ISSUE THREAD

**Issue by jmdobry** [grpc/grpc#11239]
Reported on [GoogleCloudPlatform/cloud-functions-emulator#107](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/107)

**Comment by murgatroid99** [comment]
That file definitely exists. And since the error output from trying to download it was "Error: unable to get local issuer certificate", it looks like the problem was on the client side.

**Comment by Grsmto** [comment]
Windows binaries seem fine but Linux binaries seems to be down I think?!
https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.2.4/node-v57-linux-x64.tar.gz

**Comment by murgatroid99** [comment]
We don't have Node 8 binaries because Node 8 just came out. Those will be released soon.

**Comment by murgatroid99** [comment]
gRPC 1.3.8 has been published with support for Node 8.

**Comment by Oted** [comment]
I am also having issues with this but for, is there a complete list of available binaries per node version? I am currently trying 1.7.2 and node@9.2.0

**Comment by murgatroid99** [comment]
We have binaries for Node 9 for grpc 1.7.2. Can you provide the specific error output that you are seeing?

**Comment by nooballday** [comment]
having the same issue while building image in docker.  node version v9.0.0

> grpc@1.7.2 install /app/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.2/node-v59-linux-x64-musl.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.2 and node@9.2.0 (node-v59 ABI, musl) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl"
gyp ERR! cwd /app/node_modules/grpc
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl/grpc_node.node --module_name=grpc_node --module_path=/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.9.49-moby
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /app/node_modules/grpc
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl/grpc_node.node --module_name=grpc_node --module_path=/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl' (1)
npm WARN playing-with-hapijs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.7.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-28T10_38_58_829Z-debug.log
The command '/bin/sh -c npm install --production' returned a non-zero code: 1

**Comment by Oted** [comment]
@murgatroid99 

```
Step 11/11 : RUN cd /app && npm install && npm install --global node-gyp mocha && npm install --unsafe-perm
 ---> Running in fa8b7bc5da04

> grpc@1.7.2 install /app/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.2/node-v57-linux-x64-musl.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.2 and node@8.9.1 (node-v57 ABI, musl) (falling back to source compile with node-gyp)
make: Entering directory '/app/node_modules/grpc/build'
```

**Comment by yoitsro** [comment]
@murgatroid99 Any updates on this? If the file does exist, then it looks like it's just a permissions error on https://storage.googleapis.com. Please can you confirm that the file exists and permissions are set correctly?

**Comment by murgatroid99** [comment]
We do not have binaries for Alpine right now. As you can see it falls back to build from source, as it should, but it fails.

**Comment by murgatroid99** [comment]
We have published grpc@1.8.0-pre2 which includes precompiled binaries for Alpine, so you can try those out now.

**Comment by murgatroid99** [comment]
Since my last comment, we have published regular 1.8.x packages with Alpine precompiled binaries.

**Comment by Maijied** [comment]
uninstall previous node.js and
download load node version 8.4.0
Install and run .Hopefully the problem will be solve.

**Comment by mrpatel15** [comment]
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.4.1 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_args.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack_builder.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/connected_channel.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/handshaker.o

**Comment by murgatroid99** [comment]
You are trying to install gRPC 1.4.1, which is relatively old, and does not work on Node 9. You can solve that by upgrading to a newer version of gRPC.

**Comment by xelra** [comment]
I'm using Node on Windows and I'm also trying to install gRPC 1.4.1. It falls back to build, but the build fails. I've installed all the dependencies, but I just can't get it to compile on Windows in Node 9. Installing a newer version 1.9.1 works, because there are precompiled binaries available, but building the newer version with the `--build-from-source` option also fails.

I need 1.4.1, because the firebase-tools depend on it.

**Comment by murgatroid99** [comment]
The best solution to that would probably be for firebase-tools to update their dependency to a newer version. Failing that, if you want to build the library on Windows, you will have to delete `%USERPROFILE%\.node-gyp\9.5.0\include\node\openssl`, then run the build again. It is unlikely but possible that this could mess up other builds.

**Comment by xelra** [comment]
@murgatroid99 Thanks, that worked. I temporarily removed the openssl directory and the build went through. It would be great if it would compile without this "secret step".

I'm totally ok now, but out of curiosity I'm still wondering where and why I got stuck on trying to compile manually. With YASM.

Thanks a lot.

**Comment by murgatroid99** [comment]
The build script actually echos an instruction to delete that directory on Windows, but unfortunately it does that right before thousands of lines of compilation errors. And I'm not sure what instructions you were following to build on Windows, but I think that there's a good chance that they weren't the instructions for the Node library. I'm not very familiar with them, though, so I'm not sure why they failed.
