### ISSUE TITLE
string representation of proto message incorrectly displays UTF8 chinese chararacters

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#11240]
Hello,

Here is what I see when printing a proto object received through grpc having UTF8 string as one of the fields:
```python
field1: "...'"
oerrmsg: "\345\275\223\345\211\215\347\212\266\346\200\201\347\246\201\346\255\242\346\255\244\351\241\271\346\223\215\344\275\234"
field3: "..."
```
### I'd expect to see that
```python
field1: "...'"
oerrmsg: "当前状态禁止此项操作"
field3: "..."
```

I suppose the ```__print__``` and ```__repr__``` methods should be adjusted...?

Thank you for your help,

note: Ubuntu 16.04, python gRPC@1.3.0

**Comment by nathanielmanistaatgoogle** [comment]
This smells like a Protocol Buffers problem - are you able to reproduce this problem using only Protocol Buffers and without gRPC at all?

**Comment by sulliwane** [comment]
It is indeed a proto related issue: https://github.com/google/protobuf/issues/3125
