### ISSUE TITLE
[FLAKE] c_linux_tsan_native.bins/tsan/h2_http_proxy_nosec_test bad_ping GRPC_POLL_STRATEGY=poll-cv 

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#11252]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_c/4809/testReport/junit/(root)/c_linux_tsan_native/bins_tsan_h2_http_proxy_nosec_test_bad_ping_GRPC_POLL_STRATEGY_poll_cv/

D0519 20:47:45.271222293   21171 test_config.c:403]          test slowdown factor: sanitizer=5, fixture=1, poller=5, total=25
D0519 20:47:45.278393936   21171 ev_posix.c:121]             Using polling engine: poll-cv
D0519 20:47:45.279471533   21171 dns_resolver.c:316]         Using native dns resolver
I0519 20:47:45.386652386   21171 http_proxy_fixture.c:464]   Proxy address: localhost:29813
I0519 20:47:45.448364697   21171 http_connect_handshaker.c:319] Connecting to server localhost:9235 via HTTP proxy ipv6:[::1]:29813
D0519 20:47:45.450956524   21335 http_proxy_fixture.c:331]   on_read_request_done: 0x7d880001c800 "No Error"
D0519 20:47:45.583954844   21171 chttp2_transport.c:1576]    PING strike
E0519 20:47:45.645914819   21171 bad_ping.c:215]             assertion failed: status == GRPC_STATUS_UNAVAILABLE

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [gRPC_master_asanitizer_c #1686](https://grpc-testing.appspot.com/job/gRPC_master_asanitizer_c/1686/#showFailuresLink).

**Comment by apolcyn** [comment]
seen under `msan` build on 1.4.x branch:

```
test/core/end2end/fuzzers/api_fuzzer_corpus/97f7a51a0bb869d09f9f1bd7a4f93c5d859c89eb
2017-06-12 18:27:38,227 D0612 18:27:37.713812377   30787 test_config.c:403]          test slowdown factor: sanitizer=4, fixture=1, poller=5, total=20
D0612 18:27:37.721793789   30787 ev_posix.c:121]             Using polling engine: poll-cv
D0612 18:27:37.722865313   30787 dns_resolver.c:316]         Using native dns resolver
I0612 18:27:37.786745905   30787 http_proxy_fixture.c:464]   Proxy address: localhost:9972
I0612 18:27:37.813602972   30787 http_connect_handshaker.c:319] Connecting to server localhost:20900 via HTTP proxy ipv6:[::1]:9972
D0612 18:27:37.814355347   30861 http_proxy_fixture.c:331]   on_read_request_done: 0x74400001c800 "No Error"
D0612 18:27:37.925942064   30787 chttp2_transport.c:1576]    PING strike
E0612 18:27:37.971916353   30787 bad_ping.c:215]             assertion failed: status == GRPC_STATUS_UNAVAILABLE



*******************************
Caught signal SIGABRT
bins/msan/h2_http_proxy_nosec_test(backtrace+0xa3)[0x7e000004ff13]
bins/msan/h2_http_proxy_nosec_test[0x7e0000d739f1]
bins/msan/h2_http_proxy_nosec_test[0x7e0000040d59]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f9f0e850890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f9f0dfaa067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f9f0dfab448]
bins/msan/h2_http_proxy_nosec_test[0x7e00000cac55]
bins/msan/h2_http_proxy_nosec_test[0x7e00000c66a2]
bins/msan/h2_http_proxy_nosec_test[0x7e00000b3245]
bins/msan/h2_http_proxy_nosec_test[0x7e00000b02e6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f9f0df96b45]
bins/msan/h2_http_proxy_nosec_test[0x7e000002d8ef]

2017-06-12 18:27:38,228 FAILED: bins/msan/h2_http_proxy_nosec_test bad_ping GRPC_POLL_STRATEGY=poll-cv [ret=-6, pid=30787]
```
