### ISSUE TITLE
Segfault when use nullptr as tag.

### ISSUE THREAD

**Issue by fengli-google** [grpc/grpc#1126]
Get a segfault when use nullptr as tag.
In the CompletionQueue::AsyncNext.

User should be able to pass in nullptr if they don't use a tag.

**Comment by vjpai** [comment]
Feng, please try pull request #1127 . Not ready to merge until it's tested throughout, but let me know if it works for you.

**Comment by ctiller** [comment]
Feng: can you provide a use case for where you think it's ok not to use the
tag?
I currently cannot imagine one and I'm intrigued.

**Comment by vjpai** [comment]
Craig, the user may know that there is only 1 RPC outstanding on this cq.

**Comment by fengli-google** [comment]
For example, if I do a blocking read in a proxy. After the Next() method
return, I already get the data in the buffer and will send it to my
backend. What's the tag is supposed to be in this case?

grpc::ByteBuffer buffer;
reader_writer_->Read(&buffer, nullptr);
bool ok = false;
bool ret = completion_queue_->Next(nullptr, &ok);

**Comment by vjpai** [comment]
This is not a good feature to support. If you want to write the code as above, do

grpc::ByteBuffer buffer;
reader_writer_->Read(&buffer, nullptr);
bool ok = false;
void *dummy;
bool ret = completion_queue_->Next(&dummy, &ok);

You can see that the difference is that there is now an explicit dummy tag reference being passed in. It is up to the user to ignore it or pay attention to it.
