### ISSUE TITLE
Transitive dependencies are broken in Grpc C# (new-style csproj projects targeting net45+)

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#11279]
Something about the packaging of gRPC - in particular the native component - looks like it's changed in 1.3.0, which causes the native library to not be found.

Sample csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
  </PropertyGroup>  
  <ItemGroup>
    <PackageReference Include="Grpc.Auth" Version="1.3.0" />
  </ItemGroup>
</Project>
```

And program:

```csharp
public class Program
{
    static void Main()
    {
        // Just force the native methods to get loaded
        var server = new Grpc.Core.Server();
    }
}
```

(It doesn't get much more minimal than that :)

Run `dotnet restore` then `dotnet run`, and you'll get an exception with a failure to find the native DLL. The exception isn't important - but the fact that the native DLL isn't under `bin\Debug\net452` is.

Now, this can be fixed by *either* of:

- Adding a *direct* package dependency to `Grpc.Core` version 1.3.0
- Changing `Grpc.Auth` to version 1.2.0.

Presumably there's some change in the packaging (I suspect of Grpc.Core) between 1.2.0 and 1.3.0 that makes this indirect dependency break.

I'd urge this to be treated as a high-priority bug.

**Comment by nicolasnoble** [comment]
I'm not a C# or .net expert at all, but I'd like to ask if there's any hint of the presence of the native dll anywhere ?

**Comment by iantalarico** [comment]
I was not able to find the dll when repoing the issue.

**Comment by jskeet** [comment]
Nope - whereas if you include the direct dependency, it *is* present after the build.

**Comment by jtattermusch** [comment]
I think I know what's causing this:
Looking at .nuspec files from Grpc.Auth from v1.2.x and v1.3.0, the main difference is:

v1.3.0
```
    <group targetFramework=".NETFramework4.5">
        <dependency id="Grpc.Core" version="1.3.0" exclude="Build,Analyzers" />
        <dependency id="Google.Apis.Auth" version="1.21.0" exclude="Build,Analyzers" />
      </group>
```

v1.2.0
```
    <group targetFramework=".NETFramework4.5">
        <dependency id="Grpc.Core" version="[1.2.2, )" />
        <dependency id="Google.Apis.Auth" version="[1.21.0, )" />
      </group>
```

The exclude="Build,Analyzers" is most likely causing the inclusion of GrpcCore.targets file (responsible for copying native libs to the ouptut directory) being omitted for transitive dependencies

The main difference between 1.2.x and 1.3.x is that we switched to the new csproj projects https://github.com/grpc/grpc/pull/10480. I'll investigate what flags we need to add to the .csproj projects to get rid of the unwanted  `exclude=`

**Comment by jtattermusch** [comment]
https://github.com/NuGet/Home/issues/4521 seems to suggest  adding for the dependency `<PrivateAssets>None</PrivateAssets>` should fix this?

The annoying thing is that while we can fix this for Grpc.Auth (and other packages we own), if someone creates a nuget package that depends on Grpc.Core and uses dotnet SDK for that, she'll need to use the same trick.

**Comment by jskeet** [comment]
Hmm. Yes, I can see that being a problem. Does that mean anyone using Grpc.Auth also needs to put it in their project file, and so on? Ick.

**Comment by jskeet** [comment]
I'm having problems at the moment as `dotnet pack` is complaining when I have a dependency on `Grpc.Core` *whether or not* I use `<PrivateAssets>None</PrivateAssets>`:

> warning : Description: The assembly 'content\grpc_csharp_ext.x86.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project

... and my library ends up being enormous (19MB). That's not what we want.

I haven't seen that before, so I'm not sure what's going on. If we can get this right, we can put it in all the Google API class libraries too, but it would be nice to have a better solution...

**Comment by jskeet** [comment]
Okay, it seems that there's a difference between

```xml
<TargetFrameworks>net45</TargetFrameworks>
```

and

```xml
<TargetFramework>net45</TargetFramework>
```

I don't get the warnings (or the huge size) if I use `<TargetFrameworks>`. This feels like a bug...

**Comment by jskeet** [comment]
Filed https://github.com/dotnet/cli/issues/6679 for the `<TargetFrameworks>` part. Will continue investigating the ramifications of the other parts.

**Comment by jskeet** [comment]
Verified - basically this can be propagated using `<PrivateAssets>None</PrivateAssets>` in the whole chain between `Grpc.Core` and the final application, but that's really fragile.

@onovotny: Is this something you know about? Is there a better way of packaging native binaries these days?

**Comment by onovotny** [comment]
I did know that they are only including targets directly, though I agree that it's a hole. Do you need targets for this or can you use the native folder structure for those libraries? Look at the native section of the UWP packaging doc (applies to NuGet v3, not just UWP). The docs are really light though. https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages

**Comment by jskeet** [comment]
@onovotny: I believe we're already using that folder structure, except just "win" instead of "win10-x64" etc. (I think we used to try the fuller version, but found problems with that. There was a lot of experimentation...) It currently works for netcoreapp1.0 already - it's only fails on the full framework.

**Comment by onovotny** [comment]
I would file an issue (with a repro) on the NuGet site. Dealing with packages that have a native component has always been fragile and poorly documented :/

**Comment by jskeet** [comment]
@jtattermusch: Are you in a suitable position to create that issue? You're closer to the native side than I am...

**Comment by jtattermusch** [comment]
@onovotny  we are using the .targets file for compatibility with older systems (.NET 45, VS 2013 projects etc., nuget v2). On older systems, using a .targets file seems to be the only possible way how to make packages with native depedencies work properly (because those systems have no concepts of native dependencies whatsoever).  We are using the standard folder structure for the native libraries (and that's what gets used when you use gRPC in  .NET core projects).

@jskeet  yes, I'll file an issue with nuget for this.

**Comment by jtattermusch** [comment]
Fix for gRPC owned nugets has been merged in #11282  and v1.3.6 nugets packages have been released with the fix.
For projects using Grpc nugets directly this is now fixed, but consumers of third-party nugets that are depending on Grpc can still be affected unless the third-party nugets apply the same fix. Untimately this will need to be fixed by nuget itself.

**Comment by dadude999** [comment]
This is still an issue as far as I'm aware?

**Comment by jtattermusch** [comment]
@dadude999  can you test that?

**Comment by dadude999** [comment]
I'm currently doing the workaround described by @jskeet above:

> Verified - basically this can be propagated using `<PrivateAssets>None</PrivateAssets>` in the whole chain between `Grpc.Core` and the final application, but that's really fragile.
> 
> @onovotny: Is this something you know about? Is there a better way of packaging native binaries these days?

Without it, the reference to Grpc.Core is missing. My use case is a NuGet that includes Grpc, and for that to be properly consumed, I have to separately include Grpc.Core with the `<PrivateAssets>None</PrivateAssets>` set.

**Comment by dadude999** [comment]
Whoops, let me correct that - it's not Grpc.Core that's the issue, it's the native binaries packaged in there that don't get referenced without the workaround (as described earlier in this ticket).

**Comment by dadude999** [comment]
Actually I'm realizing this ticket doesn't matter because there is a (much) newer version of the Grpc NuGet available - so no need to spend time on this =)

Out of curiosity, how did you end up fixing this?

**Comment by jtattermusch** [comment]
It looks like this is still a problem for third-party project that satisfy all of these:
1. .csproj project (the "new" dotnet SDK style) that has a dependency on Grpc.Core
2. targeting the net45+ target (one of the desktop frameworks - for netstandard/netcoreapp targets things are working fine)
3. they are using `dotnet pack` to create a nuget (which is then used by others)

This is a problem because by default the nuget packages get packed with `exclude="Build,Analyzers"`. The `<PrivateAssets>None</PrivateAssets>` workaround works (and should be used for projects that satisfy the conditions above). 

This is not a gRPC bug but rather a nuget/dotnet SDK issue, so I'm going to close this issue, but the workaround might still need to be used by some users.

**Comment by dadude999** [comment]
In my case, I create a NuGet package targeting .NET Standard 2.0. I do consume it in a .NET Framework project (4.7.x), although soon that will change to be .NET Core. Good to know it will work once I've switched!
