### ISSUE TITLE
[node] options.host is not work

### ISSUE THREAD

**Issue by atian25** [grpc/grpc#11287]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
- nodejs
- `"grpc": "^1.3.2"`
 
### What operating system (Linux, Windows, …) and version?
 mac
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

see https://github.com/atian25/grpc-host

```js
const grpc = require('grpc');
const proto = grpc.load('./test.proto').example;
const host = 'localhost:50052';

const server = new grpc.Server();
server.addService(proto.Test.service, {
  echo(call, callback) {
    callback(null, { msg: 'server_' + call.request.id });
  }
});
server.bind(host, grpc.ServerCredentials.createInsecure());
server.start();
console.log('grpc server start at %s', host);

const client = new proto.Test('localhost:50052', grpc.credentials.createInsecure());

client.echo({ id: 1}, function(err, response) {
  console.log('[client1] 50052 recieved:', response);
});

// it connected!
client.echo({ id: 1 }, undefined, { host: 'localhost:50051', deadline: 10000 }, function (err, response) {
  console.log('[client1] 50051 recieved:', response);
});


const client2 = new proto.Test('localhost:50051', grpc.credentials.createInsecure());
client2.echo({ id: 1 }, function (err, response) {
  console.log('[client2] 50051 recieved:', response, err && err.message);
});

// it connect fail!
client2.echo({ id: 1 }, undefined, { host: 'localhost:50052', deadline: 20000 }, function (err, response) {
  console.log('[client2] 50052 recieved:', response, err && err.message);
});
```
 
### What did you expect to see?
 
`client2.echo({ id: 1 }, undefined, { host: 'localhost:50052' })` should connect to server.
 
### What did you see instead?

custom `options.host` is not work.
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
```bash
➜  grpc-host node "/Users/tz/Workspaces/eggjs/test/grpc-host/index.js"
grpc server start at localhost:50052
### log at client.js makeUnaryRequest`: args.options =  undefined
### log at client.js makeUnaryRequest`: args.options =  { host: 'localhost:50051', deadline: 10000 }
### log at client.js makeUnaryRequest`: args.options =  undefined
### log at client.js makeUnaryRequest`: args.options =  { host: 'localhost:50052', deadline: 20000 }
[client1] 50051 recieved: undefined
[client2] 50052 recieved: undefined Deadline Exceeded
[client2] 50051 recieved: undefined Connect Failed
[client1] 50052 recieved: { msg: 'server_1' }
```

**Comment by murgatroid99** [comment]
That's not what the `host` option is supposed to do. It has the same use as the `Host` header in HTTP/1.1: to route traffic to different request handlers within the same server.

**Comment by atian25** [comment]
oh, sorry. after reading the sourse found the description.(seem github src docs is forward than npm)

so the load balancing is not implement yet?

```
It is worth noting that load-balancing within gRPC happens on a per-call basis, not a per-connection basis. In other words, even if all requests come from a single client, we still want them to be load-balanced across all servers.
```

**Comment by murgatroid99** [comment]
The `host` option is separate from load balancing too. The purpose of the `host` option is to send requests to different service handlers on the same server. The purpose of load balancing is to send requests to the same service handler on different servers.

The Node module does support client-side load balancing, but as that documentation says, it depends on the name resolver returning multiple addresses for a single name. When load balancing does happen, it shouldn't really be noticeable. `call.getPeer()` might return different values for different calls, but that would be the only significant difference.

**Comment by atian25** [comment]
thanks, I will read the src again.

could you please give me some guidance for custom `client-side load balancing` and `name resolver` policy? did I miss some extend point of these?

**Comment by murgatroid99** [comment]
I was just talking about the content of the specific load balancing doc that you referred to.

**Comment by atian25** [comment]
@murgatroid99 so how any example to show how to custom policy?

**Comment by geekdada** [comment]
@murgatroid99 Does this https://github.com/grpc/grpc/blob/master/doc/load-balancing.md#per-call-load-balancing only applies to server-side load balancing?

**Comment by murgatroid99** [comment]
No, that's talking about client-side load balancing. If the client resolves a domain name that it is trying to connect to to multiple IP addresses, it will attempt to connect to all of them and balance calls among them.
