### ISSUE TITLE
[PHP] Suggested remove the require "google/protobuf": "^v3.1.0" from composer.json

### ISSUE THREAD

**Issue by heyanlong** [grpc/grpc#11289]
Suggested remove the require "google/protobuf": "^v3.1.0" from composer.json.
Let users choose to install protobuf c extension or protobuf php code

grpc/grpc v1.3.5

PHP Fatal error:  Cannot redeclare class Google\Protobuf\Internal\Descriptor in /home/devops/nckk/vendor/google/protobuf/php/src/Google/Protobuf/descriptor.php on line 96

Fatal error: Cannot redeclare class Google\Protobuf\Internal\Descriptor in /home/devops/nckk/vendor/google/protobuf/php/src/Google/Protobuf/descriptor.php on line 96

**Comment by stanley-cheung** [comment]
Already done in #11112. Will be in the upcoming `v1.4.0` release

**Comment by stanley-cheung** [comment]
Although, loading both the protobuf C extension and the composer package together should work. The `redeclare class` error you saw is probably https://github.com/google/protobuf/issues/3107#issuecomment-302241118
