### ISSUE TITLE
Setup github bot to check for CNFC CLA

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11294]
We currently have googlebot to check for google CLA, we need to switch that to a bot for CNCF CLA.

Here's what kubernetes has:
https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ

**Comment by jtattermusch** [comment]
CC @zinuga

**Comment by jtattermusch** [comment]
@caniszczyk can you provide some details on kubernetes github CLA bot?

**Comment by jtattermusch** [comment]
A tracking issue for kubernetes might be useful as an additional resource https://github.com/cncf/foundation/issues/1

**Comment by caniszczyk** [comment]
@jtattermusch I can definitely get things going with the CNCF CLA bot, however, I'd love for the gRPC team to consider dropping the CLA requirement and simply use ALv2 + DCO (https://developercertificate.org/). Would people be comfortable discussing this route via a gRFC? It would simply contributions IMHO :)

I'm also heading on vacation today so I won't be able to get moving on this until next week.

**Comment by jtattermusch** [comment]
@zinuga needs to answer that.

**Comment by bgrant0607** [comment]
@caniszczyk 

CLA rationale:
https://opensource.google.com/docs/cla/policy/

**Comment by caniszczyk** [comment]
@jtattermusch after catching up with the Google OSPO and the project leads, we leave the CLA in place for now. To get started in moving to the LF CLA system, can you email "Linux Foundation Helpdesk <helpdesk@rt.linuxfoundation.org>" to start the process as LF IT will need admin access to the grpc org/repos to install the bot.

**Comment by jtattermusch** [comment]
Done.
