### ISSUE TITLE
grpc_cli: Appends 0x0a (newline) to the binary file

### ISSUE THREAD

**Issue by Cloudef** [grpc/grpc#11290]
### What version of gRPC and what language are you using?
 
6fb840b8cd2888ceb5517577dd2c4fd7ec9637df
zsh
 
### What operating system (Linux, Windows, …) and version?
 
Linux 4.9.11
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
zsh 5.3.1, grpc_cli from the git clone
 
### What did you do?
 
`grpc_cli call ip method --protofiles=service.proto -proto_path . -binary_output -outfile foobar.bin`

### What did you expect to see?
 
Clean protobuf output that passes decoder.
 
### What did you see instead?
 
Appends `0x0a` (newline) at the end of the `foobar.bin`
This makes `protoc --decode_raw < foobar.bin` fail with `Failed to parse input.`

Removing `-outfile`and forwarding stdout to file makes no difference.
Removing the trailing `0x0a` makes the file a valid protobuf binary blob.

**Comment by Cloudef** [comment]
Call to stream request seems to output newline after each message.

**Comment by programmablemike** [comment]
This also appears to be happen when using the `tobinary` command.

Here's the hexdump of the resulting binary output from the `grpc_cli tobinary`:
```
$ hexdump -C out-cli.bin
00000000  0a 09 31 32 37 2e 30 2e  30 2e 31 0a              |..127.0.0.1.|
0000000c
```

And from `protoc --encode`:
```
$ hexdump -C out-protoc.bin
00000000  0a 09 31 32 37 2e 30 2e  30 2e 31                 |..127.0.0.1|
0000000b
```

I've also been able to confirm that piping directly from `grpc_cli tobinary` to `grpc_cli totext` results in a decoding failure which is the same as what the @Cloudef reported.

**Comment by jtattermusch** [comment]
I think this is something we should fix.

**Comment by jtattermusch** [comment]
Assigning to @gnossen as he has a plan for grpc_cli vs grpcurl support.

**Comment by jtattermusch** [comment]
Feel free to send a PR with a fix. Otherwise it's recommended to use grpcurl https://github.com/fullstorydev/grpcurl
