### ISSUE TITLE
bazel/... build failure

### ISSUE THREAD

**Issue by mjamaloney** [grpc/grpc#11297]
On a clean branch from the root of the project:
$ bazel build bazel/...                                                                 
ERROR: /home/mike/src/grpc/bazel/BUILD:41:1: missing mandatory positional argument 'well_known_protos' while calling cc_grpc_library(name, srcs, deps, proto_only, well_known_protos, generate_mock, use_external = False, **kwargs).
ERROR: package contains errors: bazel.
ERROR: error loading package 'bazel': Package 'bazel' contains errors.

### What version of gRPC and what language are you using?
Current git HEAD i.e.
$ git log -s -1
commit 814d884770980f36a63de9081ba5469ba7eeaa92
Merge: 9315e91ab0 d6466872c8
Author: Craig Tiller <ctiller@google.com>
Date:   Wed May 24 11:16:12 2017 -0700

 
### What operating system (Linux, Windows, …) and version?
 Ubuntu w/4.11.0-rc8 kernel
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 $ python -V
Python 2.7.13

### What did you do?
$ bazel build bazel/...                                                                 
 
### What did you expect to see?
I expected it to work! 
 
### What did you see instead?
ERROR: /home/mike/src/grpc/bazel/BUILD:41:1: missing mandatory positional argument 'well_known_protos' while calling cc_grpc_library(name, srcs, deps, proto_only, well_known_protos, generate_mock, use_external = False, **kwargs).
ERROR: package contains errors: bazel.
ERROR: error loading package 'bazel': Package 'bazel' contains errors. 

### Anything else we should know about your project / environment?
This fails to build when I check out git alone, or when I attempt to add it as an external reference from another project.

**Comment by nicolasnoble** [comment]
This isn't a proper target to build in the first place, why did you try this ? If you want to build grpc, then use the `:all` target from root.

**Comment by mjamaloney** [comment]
I was  attempting to ensure that I had grpc set up correctly by running 
$ bazel test ...

But I figured I would reduce it to the minimal repro before I filed a bug.  It would be nice if build & test ... worked!

**Comment by ctiller** [comment]
Agree that `bazel build ...` should just work.
