### ISSUE TITLE
NodeJS: Client gets segfault on server disconnect. Started from v1.2.0.

### ISSUE THREAD

**Issue by assaf-xm** [grpc/grpc#11302]
I think we have the same issue or very similar issue as https://github.com/grpc/grpc/pull/11141 and bug https://github.com/grpc/grpc/issues/11036. However the merged fix for these doesn't solve the crash for us.

When upgrading to 1.2.0 or 1.3.2 our node.js (ubuntu 16.04) client gets segfaults when server service stops. The server is running C#. All works with older versions (GRPC v1.1.4)

We tried the v1.3.x branch latest which include this fix (commit 866190f), however this doesn't solve our issue.
Building with --debug shows the following stack trace:

Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007fef62cb918c in gpr_ref_non_zero (r=0x618) at ../src/core/lib/support/sync.c:105
105	gpr_atm prior = gpr_atm_no_barrier_fetch_add(&r->count, 1);
(gdb) info frame
Stack level 0, frame at 0x7ffd38c061c0:
rip = 0x7fef62cb918c in gpr_ref_non_zero (../src/core/lib/support/sync.c:105); saved rip = 0x7fef62c62d92
called by frame at 0x7ffd38c061e0
source language c.
Arglist at 0x7ffd38c061b0, args: r=0x618
Locals at 0x7ffd38c061b0, Previous frame's sp is 0x7ffd38c061c0
Saved registers:
rbp at 0x7ffd38c061b0, rip at 0x7ffd38c061b8
(gdb) bt
#0 0x00007fef62cb918c in gpr_ref_non_zero (r=0x618) at ../src/core/lib/support/sync.c:105
#1 0x00007fef62c62d92 in grpc_stream_ref (refcount=0x618) at ../src/core/lib/transport/transport.c:58
#2 0x00007fef62c50ff4 in grpc_call_internal_ref (c=0x0) at ../src/core/lib/surface/call.c:471
#3 0x00007fef62c5192d in cancel_with_error (exec_ctx=0x7ffd38c06250, c=0x0, source=STATUS_FROM_API_OVERRIDE, error=0x4) at ../src/core/lib/surface/call.c:633
#4 0x00007fef62c51610 in grpc_call_cancel (call=0x0, reserved=0x0) at ../src/core/lib/surface/call.c:570
#5 0x00007fef62c1fb37 in grpc::node::Call::Cancel (info=...) at ../src/node/ext/call.cc:797
#6 0x00007fef62c1cacc in Nan:👿:FunctionCallbackWrapper (info=...) at ../../nan/nan_callbacks_12_inl.h:174
#7 0x0000000000981681 in v8::internal::FunctionCallbackArguments::Call(void ()(v8::FunctionCallbackInfov8::Value const&)) ()
#8 0x00000000009d5b0b in v8::internal::MaybeHandlev8::internal::Object v8::internal::(anonymous namespace)::HandleApiCallHelper(v8::internal::Isolate, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) ()
#9 0x00000000009d60b1 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()

Further debugging shows that 'call.cc' line 797 called:
grpc_call_error error = grpc_call_cancel(call->wrapped_call, NULL);
when 'call->wrapped_call' is NULL.
Protecting null value there solved the crash, but is probably partial solution.

**Comment by murgatroid99** [comment]
I think I fixed it this time. Would you mind taking another look at the head of the 1.3.x branch?

**Comment by assaf-xm** [comment]
Thanks! Looks like this solves our issue!
When do you think we can see it on NPM?

**Comment by murgatroid99** [comment]
The newest version on NPM now has those changes.

**Comment by assaf-xm** [comment]
Thanks!
The issue is solved with the npm v1.3.7
