### ISSUE TITLE
W/ChannelExecutor: Runnable threw exception in ChannelExecutor java.lang.NoSuchMethodError: No virtual method codeAsText()

### ISSUE THREAD

**Issue by tadblack** [grpc/grpc#11314]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
### What version of gRPC and what language are you using?
 Currently i'm running gRPC 1.3.0 on java 1.8
 
### What operating system (Linux, Windows, …) and version?
Android sdk 25
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 I'm using gradle 2.3
 
### What did you do?

Currently i'm developing an app that uses gRPC to communicate between two android devices (server-client). The app compiles and executes as it should, but when the client starts it returns an error  "Runnable threw exception in ChannelExecutor java.lang.NoSuchMethodError: No virtual method codeAsText()Lio/netty/util/AsciiString; in class Lio/netty/handler/codec/http/HttpResponseStatus; or its super classes (declaration of 'io.netty.handler.codec.http.HttpResponseStatus' appears in /data/app/pt.up.fc.dcc.hyrax.generatedreplaysapp-2/split_lib_dependencies_apk.apk:classes31.dex)

My current gradle file is this: 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
    defaultConfig {
        applicationId "foo.bar"
        minSdkVersion 23
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled = true

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dexOptions {
        jumboMode = true
    }

    sourceSets { main { jni.srcDirs = [] } }

    packagingOptions {
        exclude 'META-INF/NOTICE' // will not include NOTICE file
        exclude 'META-INF/LICENSE' // will not include LICENSE file
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'

    }
}

def grpcVersion = '1.3.0'


dependencies {
    compile "io.grpc:grpc-netty:${grpcVersion}"
    compile "io.grpc:grpc-protobuf:${grpcVersion}"
    compile "io.grpc:grpc-stub:${grpcVersion}"
    compile 'com.google.protobuf:protobuf-java:3.1.0'

    compile project(':logic-layer')
    compile fileTree(include: ['*.jar'], dir: 'libs')

    compile project(':face_detection')
    compile 'com.android.support:appcompat-v7:25.1.1'
    compile 'com.android.support:support-v4:25.1.1'
    compile 'com.android.support:recyclerview-v7:25.1.1'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:design:25.2.0'
    compile project(':openCVLibrary320')

}
```

### What did you expect to see?
 I expected to see an answer from the server
 
### What did you see instead?
```
W/ChannelExecutor: Runnable threw exception in ChannelExecutor
java.lang.NoSuchMethodError: No virtual method codeAsText()Lio/netty/util/AsciiString; in class Lio/netty/handler/codec/http/HttpResponseStatus; or its super classes (declaration of 'io.netty.handler.codec.http.HttpResponseStatus' appears in /data/app/pt.up.fc.dcc.hyrax.generatedreplaysapp-2/split_lib_dependencies_apk.apk:classes31.dex)
at io.netty.handler.codec.http2.Http2ConnectionHandler.<clinit>(Http2ConnectionHandler.java:69)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java)
at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:190)
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ejona86** [comment]
ProGuard isn't enabled... that would have been my first guess...

HttpResponseStatus.codeAsText() has always existed in Netty 4.1. Is it possible you're using Netty 4.0 instead? I'd expect Gradle to fail to build, but maybe something is weird. You can check via `gradle dependencies`.

I really don't have any ideas... Is it possible for multidex to fail like that?

**Comment by tadblack** [comment]
I enabled ProGuard and it still gives the same error. I checked the dependencies.
|    +--- io.grpc:grpc-netty:1.3.0
|    |    +--- io.grpc:grpc-core:[1.3.0] -> 1.3.0
|    |    |    +--- com.google.guava:guava:19.0
|    |    |    +--- com.google.errorprone:error_prone_annotations:2.0.19
|    |    |    +--- com.google.code.findbugs:jsr305:3.0.0
|    |    |    +--- io.grpc:grpc-context:1.3.0
|    |    |    \--- com.google.instrumentation:instrumentation-api:0.3.0
|    |    |         \--- com.google.code.findbugs:jsr305:3.0.0
|    |    +--- io.netty:netty-codec-http2:[4.1.8.Final] -> 4.1.8.Final
|    |    |    +--- io.netty:netty-codec-http:4.1.8.Final
|    |    |    |    \--- io.netty:netty-codec:4.1.8.Final
|    |    |    |         \--- io.netty:netty-transport:4.1.8.Final
|    |    |    |              +--- io.netty:netty-buffer:4.1.8.Final
|    |    |    |              |    \--- io.netty:netty-common:4.1.8.Final
|    |    |    |              \--- io.netty:netty-resolver:4.1.8.Final
|    |    |    |                   \--- io.netty:netty-common:4.1.8.Final
|    |    |    \--- io.netty:netty-handler:4.1.8.Final
|    |    |         +--- io.netty:netty-buffer:4.1.8.Final (*)
|    |    |         +--- io.netty:netty-transport:4.1.8.Final (*)
|    |    |         \--- io.netty:netty-codec:4.1.8.Final (*)
|    |    \--- io.netty:netty-handler-proxy:4.1.8.Final
|    |         +--- io.netty:netty-transport:4.1.8.Final (*)
|    |         +--- io.netty:netty-codec-socks:4.1.8.Final
|    |         |    \--- io.netty:netty-codec:4.1.8.Final (*)
|    |         \--- io.netty:netty-codec-http:4.1.8.Final (*)
|    +--- io.grpc:grpc-protobuf:1.3.0
|    |    +--- io.grpc:grpc-core:1.3.0 (*)
|    |    +--- com.google.protobuf:protobuf-java:3.2.0
|    |    +--- com.google.guava:guava:19.0
|    |    +--- com.google.protobuf:protobuf-java-util:3.2.0
|    |    |    +--- com.google.protobuf:protobuf-java:3.2.0
|    |    |    +--- com.google.guava:guava:18.0 -> 19.0
|    |    |    \--- com.google.code.gson:gson:2.7
|    |    +--- com.google.api.grpc:grpc-google-common-protos:0.1.6
|    |    |    \--- com.google.protobuf:protobuf-java:3.0.0 -> 3.2.0
|    |    \--- io.grpc:grpc-protobuf-lite:1.3.0
|    |         +--- io.grpc:grpc-core:1.3.0 (*)
|    |         \--- com.google.guava:guava:19.0
|    +--- io.grpc:grpc-stub:1.3.0
|    |    \--- io.grpc:grpc-core:1.3.0 (*)
|    +--- com.google.protobuf:protobuf-java:3.1.0 -> 3.2.0

Has you can see it's using the Netty 4.1. To help multidex i increased the heap size to no use.
Is it possible the gradle to skip methods when compiling?

**Comment by ejona86** [comment]
I'm completely at a loss. I'd probably use a disassembler (like [JD](http://jd.benow.ca/)) on the ProGuard input/output to see if the method actually exists and then investigate further from there.

**Comment by srini100** [comment]
Closing this issue. Please reopen in grpc/grpc-java repo if the issue still exists.
