### ISSUE TITLE
Visual Studio 2013 error C2220

### ISSUE THREAD

**Issue by ml232528** [grpc/grpc#11343]
### What version of gRPC and what language are you using?
 Release 1.3.4 ， c++
 
### What operating system (Linux, Windows, …) and version?
windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2013
 
### What did you do?
compile grpc++ 
 
### What did you see instead?
18>grpc\include\grpc++/impl/codegen/async_stream.h(419): error C2220: 警告被视为错误 - 没有生成“object”文件
18>grpc\include\grpc++/impl/codegen/async_stream.h(419): warning C4291: “void *operator new(size_t,void *) throw()”: 未找到匹配的删除运算符；如果初始化引发异常，则不会释放内存

**Comment by jtattermusch** [comment]
Does this happen in cmake & VS2015 too?
Also, using vsprojects/  pre-generated projects is now deprecated - please use cmake. https://github.com/grpc/grpc/tree/master/vsprojects

**Comment by mocsharp** [comment]
Tried to build 1.4.1 on Windows 10 with CMAKE, Ninja and VS 2013 U5 and got bunch of C2143, C2054, C2085 errors:

> internal.h(298) : error C2054: expected '(' to follow 'inline'
> internal.h(299) : error C2143: syntax error : missing ';' before '{'

It built find with VS 2015. Any idea?

**Comment by jtattermusch** [comment]
@mocsharp  we'll be dropping official VS2013 support in one of the future releases - as some of our dependencies (boringssl) don't build with VS2013 either. Any particular reason why VS2015 won't be sufficient for you?

**Comment by mocsharp** [comment]
@jtattermusch  we have dependencies that can't yet update to 2015.  
Thanks.

**Comment by jiakuan** [comment]
This post mentioned a fix for this error: https://groups.google.com/forum/#!topic/grpc-io/9XkKF3BJwjw
```
fix the following error reported when building the protobuf project
coded_stream.h(1138): error C2220: warning treated as error - no 'object' file generated
coded_stream.h(1138): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
by changing line 1138 from 'int size = end - target;' to 'int size = static_cast<int>(end - target);'

```
