### ISSUE TITLE
Add a core end2end test to represent client-side streaming

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#11344]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 
C core at master 1.4-dev
 
### What operating system (Linux, Windows, …) and version?

Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 
 
### What did you do?

This is a feature request . There is currently no end2end test that has the same behavior as client-side streaming. Basically, this entails:

Server: recv initial metadata
Client: send initial metadata
Server: send initial metadata, recv trailing metadata
Client: send message
Server: recv message
[repeat the above 0 or more times]
Client: send trailing metadata
Server: recv message

### What did you expect to see?
 
A test with the above characteristics

### What did you see instead?
 
Lots of other awesome tests, but the above test is better captured in test/cpp/end2end/async_end2end_test . It would be nice to have it seen in the core tests itself.
 
### Anything else we should know about your project / environment?

Writing a transport and trying to document the process of writing transports.

**Comment by vjpai** [comment]
This ties in to Nathaniel's suggestions in #7032 . There are a few categories of core end2end tests that could be added.

**Comment by yashykt** [comment]
Thanks for digging this up, Vijay! Should be fixed by https://github.com/grpc/grpc/pull/22668
