### ISSUE TITLE
Ruby deadlock

### ISSUE THREAD

**Issue by tonobo** [grpc/grpc#11345]
### What version of gRPC and what language are you using?

* v1.3.4 
 
### What operating system (Linux, Windows, …) and version?
 
* Linux (Ubuntu)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

* ruby 2.3
 
### What did you do?

GRPC has been used within a unicorn (without preload_app).

```ruby
loop do
  stub = Etcdserverpb::KV::Stub.new(host, :this_channel_is_insecure)
  res = stub.range(Etcdserverpb::RangeRequest.new(key: key)).kvs[0]
  stub.instance_variable_get("@ch").close
  break if res and res.value == "1" # It will take about minutes
  sleep 1
end
```
 
### What did you see instead?
 
```
E0531 09:11:03.277169204 2657243 ev_epoll_linux.c:1757]      add_poll_object: {"created":"@1496214663.277114126","description":"polling_island_create","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":280,"referenced_errors":[{"created":"@1496214663.277110716","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":557,"os_error":"Too many open files","syscall":"epoll_create1"}]}
```

```
E0531 09:12:38.959508831 2657217 ev_epoll_linux.c:1607]      pollset_work: {"created":"@1496214758.959482077","description":"pollset_work_and_unlock","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":280,"referenced_errors":[{"created":"@1496214758.959480505","description":"OS Error","errno":22,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1438,"os_error":"Invalid argument","syscall":"epoll_wait() epoll fd: 20 failed with error: 22 (Invalid argument)"}]}
```

**Comment by dopykuh** [comment]
CPU-Usage is about 100% per process and it will never end.

**Comment by apolcyn** [comment]
Will try to repro this using unicorn, without `preload_app`, to take look. 

Do you have a fuller example repro available that uses involves unicorn?

**Comment by dopykuh** [comment]
Hi, i've written an etcdv3 client, which is currently impossible to release it on github. But thats my unicorn conf.

```
preload_app false
after_fork do |a,b|
  if (require 'etcdv3')
    puts "GRPC loaded"
  else
    puts "GRPC not loaded!"
  end
end
```

Each worker will print this message "GRPC loaded".  
The exception is 100% reproduce able, by starting same code by hand within `pry` everything works fine.

**Comment by dopykuh** [comment]
This does not directly depend on using the plain stubs in unicorn. By directly using the stubs within an grape api is no problem. But when i'm triggering the etcd stubs in multiple layers deeper (tool-chain around grpc stubs) the issue occurs.  Could this issue happen, due to the usage of proc's, i'm asking because the stubs are predefined on multiple procs (during application load) and are only called with arguments.

**Comment by apolcyn** [comment]
Haven't fully reproduced yet, but it looks like forking is still being used here. 

Are you able to know here if it's guaranteed that grpc isn't used until after forking (i.e. it's never used across a fork)? In some cases (requirements are subtle) grpc can work with forking, but in general it's not supported.

**Comment by dopykuh** [comment]
I can guarantee that grpc instances will not used across forks. But grpc has been used within child processes, possibly there are something not correctly released. When will forking support be available?

**Comment by dopykuh** [comment]
I've currently found a possiblity to workaround my issue. Just by calling etcd's grpc instructions through an http rest api.

**Comment by apolcyn** [comment]
Note an object doesn't necessarily have to be used across a fork for things to break, the library just has to have been loaded by the parent previously, at some point.

But also note this is only a guess at the issue here; still haven't reproduced the error at this point.
