### ISSUE TITLE
grpc_interop_csharpcoreclr does not build

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#11357]
```docker build -t test --force-rm=true tools/dockerfile/interoptest/grpc_interop_csharpcoreclr```

Fails with:
The following packages have unmet dependencies:
 mono-devel : Depends: libmono-system-runtime4.0-cil (>= 2.10.1) but it is not going to be installed
              Depends: libmono-system-servicemodel4.0a-cil (>= 3.2.3) but it is not going to be installed
              Depends: libmono-system-web-services4.0-cil (>= 1.0) but it is not going to be installed
              Depends: libmono-cil-dev (= 5.0.1.1-0xamarin5+debian7b1) but it is not going to be installed
              Recommends: msbuild but it is not going to be installed
 nuget : Depends: libnuget-core-cil (= 2.12+mono-0xamarin5+debian7b1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

This causes grpc_interop_macos jenkins job to fail.

**Comment by matt-kwong** [comment]
@jtattermusch @apolcyn Are either of you familiar with this issue? I think this should affect our non-interop C# CoreCLR Dockerfile also, but we haven't noticed any issue with that one yet because it's building from cache. 

https://grpc-testing.appspot.com/job/gRPC_interop_macos/280/console

**Comment by apolcyn** [comment]
I'm a little unsure here just since I think building the interop docker image hasn't been done on a mac before, but `grpc-mac-node1` seems new (that mac seems separate from the rest).

But `tools/dockerfile/interoptest/grpc_interop_csharpcoreclr` works on linux from master.

**Comment by makdharma** [comment]
I just tried on ubuntu and it fails with exact same message (i.e. does not work on linux from master). @apolcyn perhaps try after removing existing containers and images on your linux box?

**Comment by murgatroid99** [comment]
This was seen again: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/14745/console

**Comment by matt-kwong** [comment]
Opened #11537 to fix the issue in v1.4.x
