### ISSUE TITLE
bad uri.scheme. don't know how to resolve.

### ISSUE THREAD

**Issue by zhyq0520** [grpc/grpc#11366]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
client  1.3.0 with c++
server with Golang
 
### What operating system (Linux, Windows, …) and version?
 built On Ubuntu 16.04.2 LTS
 run on centos6.4 with glic-2.14
### What did you do?
std::ostringstream oss;
		oss << ip_ << ":" << port_;
		log4cplus_debug("launch", "[%s:%d]", __FUNCTION__, __LINE__);
		std::shared_ptr<grpc::Channel> ch = grpc::CreateChannel(oss.str(), grpc::InsecureChannelCredentials());
		if (!ch )
		{
			log4cplus_debug("launch", "[%s:%d] CreateChannel failed=%d", __FUNCTION__, __LINE__, ch->GetState(false));
			return false;
		}
		stub_.reset(RelayStatusReport::NewStub(ch).release());
		log4cplus_debug("launch", "[%s:%d] CreateChannel State=%d", __FUNCTION__, __LINE__, ch->GetState(false));
		running_ = true;
		log_in();
 
### What did you expect to see?
 gcc version 5.4.0 20160609
runtime glibc-2.14
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
export GRPC_VERBOSITY=DEBUG;./launch
log4cplus: Just opened file: /tmp/launch.log
I0601 14:26:59.340767230   22028 ev_epoll_linux.c:95]        epoll engine will be using signal: 40
D0601 14:26:59.340813606   22028 ev_posix.c:107]             Using polling engine: epoll
I0601 14:26:59.340852505   22028 init.c:228]                 grpc_init(void)
I0601 14:26:59.340866731   22028 completion_queue.c:119]     grpc_completion_queue_create(reserved=(nil))
I0601 14:26:59.341009329   22028 init.c:228]                 grpc_init(void)
I0601 14:26:59.341035137   22028 channel_create.c:105]       grpc_insecure_channel_create(target=0x2730fe0, args=0x7ffc14517160, reserved=(nil))
E0601 14:26:59.341062536   22028 uri_parser.c:60]            bad uri.scheme: '10.12.23.69:55001'
E0601 14:26:59.341072024   22028 uri_parser.c:66]                             ^ here
E0601 14:26:59.341083069   22028 resolver_registry.c:127]    don't know how to resolve '10.12.23.69:55001' or 'dns:///10.12.23.69:55001'
E0601 14:26:59.341103374   22028 uri_parser.c:60]            bad uri.scheme: '10.12.23.69:55001'
E0601 14:26:59.341111859   22028 uri_parser.c:66]                             ^ here
E0601 14:26:59.341122141   22028 resolver_registry.c:127]    don't know how to resolve '10.12.23.69:55001' or 'dns:///10.12.23.69:55001'
D0601 14:26:59.341142472   22028 combiner.c:146]             C:0x2731930 create
E0601 14:26:59.341163701   22028 resolver_registry.c:127]    don't know how to resolve 'dns:///10.12.23.69:55001' or 'dns:///dns:///10.12.23.69:55001'
D0601 14:26:59.341178479   22028 combiner.c:161]             C:0x2731930 really_destroy old_state=1
D0601 14:26:59.341187088   22028 combiner.c:151]             C:0x2731930 really_destroy
E0601 14:26:59.341209224   22028 channel.c:99]               channel stack builder failed: {"created":"@1496327219.341175855","description":"resolver creation failed","file":"src/core/ext/filters/client_channel/client_channel.c","file_line":677}
I0601 14:26:59.341228385   22028 lame_client.c:181]          grpc_lame_client_channel_create(target=10.12.23.69:55001, error_code=13, error_message=Failed to create client channel)
I0601 14:26:59.341238825   22028 init.c:228]                 grpc_init(void)
I0601 14:26:59.341248077   22028 init.c:233]                 grpc_shutdown(void)
I0601 14:26:59.341262231   22028 channel.c:319]              grpc_channel_register_call(channel=0x27313d0, method=/relayserverstatus.RelayStatusReport/SendStatusReport, host=(null), reserved=(nil))
I0601 14:26:59.341276092   22028 channel.c:319]              grpc_channel_register_call(channel=0x27313d0, method=/relayserverstatus.RelayStatusReport/Login, host=(null), reserved=(nil))
I0601 14:26:59.341288220   22028 channel.c:319]              grpc_channel_register_call(channel=0x27313d0, method=/relayserverstatus.RelayStatusReport/HeartBeat, host=(null), reserved=(nil))
I0601 14:26:59.341300122   22028 channel.c:319]              grpc_channel_register_call(channel=0x27313d0, method=/relayserverstatus.RelayStatusReport/GetChannelConfig, host=(null), reserved=(nil))
I0601 14:26:59.341316964   22028 channel_connectivity.c:53]  grpc_channel_check_connectivity_state(channel=0x27313d0, try_to_connect=0)
E0601 14:26:59.341327284   22028 channel_connectivity.c:60]  grpc_channel_check_connectivity_state called on something that is not a client channel, but 'lame-client'
I0601 14:26:59.341416705   22028 channel.c:353]              grpc_channel_create_registered_call(channel=0x27313d0, parent_call=(nil), propagation_mask=ffff, completion_queue=0x2730780, registered_call_handle=0x2730fe0, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0601 14:26:59.341452235   22028 grpc_context.c:41]          grpc_census_call_set_context(call=0x2732158, census_context=(nil))
I0601 14:26:59.341493404   22028 call.c:1759]                grpc_call_start_batch(call=0x2732158, ops=0x7ffc14516db0, nops=3, tag=0x27316d0, reserved=(nil))
I0601 14:26:59.341506408   22028 call.c:1402]                ops[0]: SEND_INITIAL_METADATA(nil)
I0601 14:26:59.341515720   22028 call.c:1402]                ops[1]: SEND_MESSAGE ptr=0x2732a20
I0601 14:26:59.341523953   22028 call.c:1402]                ops[2]: SEND_CLOSE_FROM_CLIENT
I0601 14:26:59.341549698   22028 lame_client.c:86]           OP[lame-client:0x27327a0]: [COVERED] SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 72 65 6c 61 79 73 65 72 76 65 72 73 74 61 74 75 73 2e 52 65 6c 61 79 53 74 61 74 75 73 52 65 70 6f 72 74 2f 4c 6f 67 69 6e '/relayserverstatus.RelayStatusReport/Login'} SEND_MESSAGE:flags=0x00000000:len=10 SEND_TRAILING_METADATA{}
I0601 14:26:59.341580329   22028 lame_client.c:86]           OP[lame-client:0x27327a0]: [UNCOVERED] CANCEL:{"created":"@1496327219.341563047","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
I0601 14:26:59.341594397   22028 completion_queue.c:224]     grpc_cq_end_op(exec_ctx=0x7ffc14516d20, cc=0x2730780, tag=0x27316d0, error={"created":"@1496327219.341563047","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}, done=0xa812f0, done_arg=0x2732818, storage=0x2732820)
E0601 14:26:59.341606585   22028 completion_queue.c:226]     Operation failed: tag=0x27316d0, error={"created":"@1496327219.341563047","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
I0601 14:26:59.341622277   22028 call.c:1759]                grpc_call_start_batch(call=0x2732158, ops=0x7ffc14516e80, nops=3, tag=0x2731750, reserved=(nil))
I0601 14:26:59.341633100   22028 call.c:1402]                ops[0]: RECV_INITIAL_METADATA ptr=0x2731950
I0601 14:26:59.341642179   22028 call.c:1402]                ops[1]: RECV_MESSAGE ptr=0x2731780
I0601 14:26:59.341652577   22028 call.c:1402]                ops[2]: RECV_STATUS_ON_CLIENT metadata=0x2731998 status=0x27317a0 details=0x27317a8
I0601 14:26:59.341664201   22028 lame_client.c:86]           OP[lame-client:0x27327a0]: [COVERED] RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
I0601 14:26:59.341689179   22028 lame_client.c:86]           OP[lame-client:0x27327a0]: [UNCOVERED] CANCEL:{"created":"@1496327219.341674371","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
D0601 14:26:59.341733765   22028 call.c:690]                 get_final_status CLI
D0601 14:26:59.341745051   22028 call.c:693]                   2: {"created":"@1496327219.341563047","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
D0601 14:26:59.341756089   22028 call.c:693]                   3: {"created":"@1496327219.341674371","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
I0601 14:26:59.341768269   22028 completion_queue.c:224]     grpc_cq_end_op(exec_ctx=0x7ffc14516df0, cc=0x2730780, tag=0x2731750, error="No Error", done=0xa812f0, done_arg=0x27328e8, storage=0x27328f0)
I0601 14:26:59.342055574   22050 completion_queue.c:359]     grpc_completion_queue_next(cc=0x2730780, deadline=gpr_timespec { tv_sec: 1496327219, tv_nsec: 352048991, clock_type: 1 }, reserved=(nil))
I0601 14:26:59.342093860   22050 completion_queue.c:444]     RETURN_EVENT[0x2730780]: OP_COMPLETE: tag:0x27316d0 ERROR
I0601 14:26:59.342112491   22050 completion_queue.c:359]     grpc_completion_queue_next(cc=0x2730780, deadline=gpr_timespec { tv_sec: 1496327219, tv_nsec: 352048991, clock_type: 1 }, reserved=(nil))
I0601 14:26:59.342124762   22050 completion_queue.c:444]     RETURN_EVENT[0x2730780]: OP_COMPLETE: tag:0x2731750 OK
I0601 14:26:59.342203724   22050 call.c:536]                 grpc_call_destroy(c=0x2732158)
D0601 14:26:59.342510292   22050 call.c:690]                 get_final_status CLI
D0601 14:26:59.342521574   22050 call.c:693]                   2: {"created":"@1496327219.341563047","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
D0601 14:26:59.342531916   22050 call.c:693]                   3: {"created":"@1496327219.341674371","description":"lame client channel","file":"src/core/lib/surface/lame_client.c","file_line":96}
I0601 14:26:59.342545581   22050 metadata_array.c:47]        grpc_metadata_array_destroy(array=0x2731998)
I0601 14:26:59.342554262   22050 metadata_array.c:47]        grpc_metadata_array_destroy(array=0x2731950)
I0601 14:26:59.342565393   22050 completion_queue.c:359]     grpc_completion_queue_next(cc=0x2730780, deadline=gpr_timespec { tv_sec: 1496327219, tv_nsec: 352561968, clock_type: 1 }, reserved=(nil))
D0601 14:26:59.342578374   22050 timer_generic.c:534]        TIMER CHECK BEGIN: now=102928.293732755 [1] next=102928.303720312 [11] tls_min=0 glob_min=0
D0601 14:26:59.342832224   22050 timer_generic.c:440]          .. shard[0]->min_deadline = 1

**Comment by dgquintas** [comment]
This is very surprising. It seems the dns resolver is not registering. You should see something like:
```
I0607 14:51:45.015431502   63449 ev_epoll_linux.c:95]        epoll engine will be using signal: 40
D0607 14:51:45.015559300   63449 ev_posix.c:107]             Using polling engine: epoll
D0607 14:51:45.015619338   63449 dns_resolver.c:316]         Using native dns resolver
...
```
Note the "Using native dns resolver" line.

Could you make sure your environment is in a good condition (no conflicting versions left around the environment, `make clean`, etc.)?

**Comment by zhyq0520** [comment]
@dgquintas 
Hi dgquintas,
   thanks for response.
  this issue is gone if I link program against dynamic library.
  I don't know why.

**Comment by dgquintas** [comment]
Excellent! Closing the issue.

**Comment by noonien** [comment]
If anyone is wondering, when loading gRPC as a DLL/SO, `grpc_init()` is called when the library is loaded. When it's statically compiled, you have got to call `grpc_init()` yourself.

**Comment by dubaokun** [comment]
i have same question

**Comment by dubaokun** [comment]
@noonien 打算
