### ISSUE TITLE
Missing configuration file for cmake

### ISSUE THREAD

**Issue by zhengwx11** [grpc/grpc#11378]
gRPC version:
```
core_version = "3.0.0"
version = "1.3.2"
```

I build gRPC from source by `cmake` under Ubuntu 16.04. 
It creates package configure files: `/usr/local/lib/cmake/protobuf/gRPCConfig.cmake` which seems the file cmake needs.
But `gRPCConfig.cmake` is merely a reference to `gRPCTargets.cmake` that is non-existent in the build tree.
It failed of course. 

So the build process  may miss the file `gRPCTargets.cmake`.

**Comment by nicolasnoble** [comment]
@jtattermusch: want to take a look ?

**Comment by jtattermusch** [comment]
@zhengwx11    please include the exact commands you ran.

**Comment by zhengwx11** [comment]
@jtattermusch 
```
$ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make install
```
The `cmake.org` declares that `Findxxx.cmake` won't be provided for projects that is build via `cmake`. So I use `CMakeLists.txt` but not `Makefile` for build.
 And I tried `Makefile` way before. The neccessary file for `find_package(gRPC)` is missing too.

**Comment by zhengwx11** [comment]
I wrote a `FindGRPC.cmake` based on `FindProtobuf.cmake` in  https://github.com/zhengwx11/FindGRPC. But it would be better if there is official support for `cmake`.

**Comment by osDanielLee** [comment]
Have any idea to resolve this issue? I also couldn't find the file gRPCTargets.cmake.

**Comment by zhengwx11** [comment]
@osDanielLee An alternative is here:  https://github.com/zhengwx11/FindGRPC

**Comment by jtattermusch** [comment]
There's been a set of cmake fixes recently, but starting with https://github.com/grpc/grpc/pull/12469, we added a test that once can install gRPC with cmake and then use it from another cmake project, so things should be working well right now. Closing.
