### ISSUE TITLE
Node.js 8 support

### ISSUE THREAD

**Issue by unbornchikken** [grpc/grpc#11377]
### What version of gRPC and what language are you using?

v1.3.7 
 
### What operating system (Linux, Windows, …) and version?

Windows, Mac, Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

VS, gcc, clang 
 
### What did you do?

npm install grpc
 
### What did you expect to see?

npm installs grpc without an issue 

### What did you see instead?
 
Many-many lines of errors.
 
### Anything else we should know about your project / environment?

The issue is of course about that node-pre-gyp image for Node.js 8.x has not been released, so the build fails on an average user's computer because of missing dependencies. 

So please upload a Node.js 8 image into your node-pre-gyp repository, building grpc by hand is a major PITA especially on Windows and on Mac.

**Comment by murgatroid99** [comment]
We're working on it.

**Comment by murgatroid99** [comment]
gRPC 1.3.8 has been published with support for Node 8.

**Comment by unbornchikken** [comment]
It works, thanks.

**Comment by camsjams** [comment]
Are the pre-built binaries going to be included as well - they are extremely useful as we wouldn't have to install Python in a container just to compile them.

Thanks!

**Comment by murgatroid99** [comment]
I don't know what happened there, but that file that it tried to download definitely exists.

**Comment by camsjams** [comment]
Hmm I can confirm that it works in a browser or curl to download that file. Very odd - something about the `npm install` doesn't get handled correctly in Node 8, let me see if there is better info.
