### ISSUE TITLE
All interop tests are failing

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#11386]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/14482/console

2017-06-02 16:15:41,363 FAILED: build_docker_python [ret=1, pid=27530]
2017-06-02 16:15:41,363 ++ dirname tools/run_tests/dockerize/build_interop_image.sh
+ cd tools/run_tests/dockerize/../../..
++ pwd
+ echo 'GRPC_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc'
GRPC_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc
+ MOUNT_ARGS='-v /home/jenkins/workspace/gRPC_interop_pull_requests/grpc:/var/local/jenkins/grpc:ro'
++ cd ../grpc-java
++ pwd
+ echo 'GRPC_JAVA_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java'
GRPC_JAVA_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java
+ '[' -n /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java ']'
+ MOUNT_ARGS+=' -v /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java:/var/local/jenkins/grpc-java:ro'
++ cd ../grpc-go
++ pwd
+ echo 'GRPC_GO_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go'
GRPC_GO_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go
+ '[' -n /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go ']'
+ MOUNT_ARGS+=' -v /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go:/var/local/jenkins/grpc-go:ro'
+ mkdir -p /tmp/ccache
+ '[' -e /home/jenkins/service_account ']'
+ MOUNT_ARGS+=' -v /home/jenkins/service_account:/var/local/jenkins/service_account:ro'
+ which sha1sum
++ sha1sum tools/dockerfile/interoptest/grpc_interop_ruby/Dockerfile
++ cut -f1 '-d '
+ BASE_IMAGE=grpc_interop_ruby_base:b20f3e87261326b3f17436b7b2b8aa706ee02977
+ docker build -t grpc_interop_ruby_base:b20f3e87261326b3f17436b7b2b8aa706ee02977 --force-rm=true tools/dockerfile/interoptest/grpc_interop_ruby
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
+ exit 1

2017-06-02 16:15:41,363 FAILED: build_docker_ruby [ret=1, pid=27516]
2017-06-02 16:15:41,363 ++ dirname tools/run_tests/dockerize/build_interop_image.sh
+ cd tools/run_tests/dockerize/../../..
++ pwd
+ echo 'GRPC_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc'
GRPC_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc
+ MOUNT_ARGS='-v /home/jenkins/workspace/gRPC_interop_pull_requests/grpc:/var/local/jenkins/grpc:ro'
++ cd ../grpc-java
++ pwd
+ echo 'GRPC_JAVA_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java'
GRPC_JAVA_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java
+ '[' -n /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java ']'
+ MOUNT_ARGS+=' -v /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-java:/var/local/jenkins/grpc-java:ro'
++ cd ../grpc-go
++ pwd
+ echo 'GRPC_GO_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go'
GRPC_GO_ROOT: /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go
+ '[' -n /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go ']'
+ MOUNT_ARGS+=' -v /home/jenkins/workspace/gRPC_interop_pull_requests/grpc-go:/var/local/jenkins/grpc-go:ro'
+ mkdir -p /tmp/ccache
+ '[' -e /home/jenkins/service_account ']'
+ MOUNT_ARGS+=' -v /home/jenkins/service_account:/var/local/jenkins/service_account:ro'
+ which sha1sum
++ sha1sum tools/dockerfile/interoptest/grpc_interop_go/Dockerfile
++ cut -f1 '-d '
+ BASE_IMAGE=grpc_interop_go_base:5526c9005ff64548b15bff551cf3e0f792d94fb8
+ docker build -t grpc_interop_go_base:5526c9005ff64548b15bff551cf3e0f792d94fb8 --force-rm=true tools/dockerfile/interoptest/grpc_interop_go
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
+ exit 1

**Comment by matt-kwong** [comment]
Interop master tests have been green for the last 5 builds
