### ISSUE TITLE
Be smarter about port-addition failure

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#11394]
Sometimes adding a port to a server fails. [`add_insecure_port` should either document that a return value of 0 indicates failure](https://github.com/grpc/grpc/blob/01b536c3e74609273ec4042ddb158be32c3fc6c7/src/python/grpcio/grpc/__init__.py#L976-L978) or raise an exception.

(From an [email thread.](https://groups.google.com/d/topic/grpc-io/tWNkRsyiN5U/discussion))

**Comment by spikecurtis** [comment]
Does `add_insecure_port()` attempt to bind immediately, or only when you `start()` the server?

In any case, I would prefer raising an exception to having to check a return value.

**Comment by nathanielmanistaatgoogle** [comment]
@spikecurtis: I believe `add_insecure_port` binds immediately rather than waiting until `start`; please let us know if that's not what you observe.

**Comment by nathanielmanistaatgoogle** [comment]
Action item from [the duplicate issue](https://github.com/grpc/grpc/issues/13096): we should _test_ port addition failure, not just document it.
