### ISSUE TITLE
CSharp: best pattern for raising unsolicited events from server

### ISSUE THREAD

**Issue by maiorfi** [grpc/grpc#11405]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
No.

### What version of gRPC and what language are you using?
1.3.6 
 
### What operating system (Linux, Windows, …) and version?
Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET 4.6.1
 
### What did you do?
N/A 
### What did you expect to see?
N/A
### What did you see instead?
N/A
 
I would like to raise unsolicited (stream) replies from a grpc server, (as for example in a pub/sub messaging system, just to mention a scenario), but, although some programming languages grpc has been ported to make that easy and natural (for example, nodejs, where unsolicited replies are fired by an EventEmitter), it seems that in .NET/CSharp the only way is defining methods with "Subscribe" semantic, having a stream reply signature and, this is the bad thing, never returning! Indeed, returning from such methods would cause response stream to be closed.

Am I wrong? Is there a better way?

**Comment by jtattermusch** [comment]
To question "Should this be an issue in the gRPC issue tracker?" you've answered "no." (which means you shouldn't have filed this as an issue). Please post a question to grpc,io forum.

I believe C# cloud pub sub client library has utility code to turn streaming messages into events. You might want to take a look at their source code. https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1

**Comment by maiorfi** [comment]
...so "Should this be an issue in the gRPC issue tracker?" is actually a trick question...nice 😄 

I'll take a look to Google PubSub cloud service sources, thanks.
