### ISSUE TITLE
grpc + nginx

### ISSUE THREAD

**Issue by siacomuzzi** [grpc/grpc#11427]
Hi,

Does anyone has experience configuring a grpc server (node.js) with nginx? Below you can find my setup and the errors I'm getting: 

# Setup
## nginx config (nginx v1.13.1)

```
server {
    listen 8443 ssl http2;
    listen [::]:8443 ssl http2;
    ssl_certificate /etc/ssl/private/foo.com.pem;
    ssl_certificate_key /etc/ssl/private/foo.com.key;
    # ...
    
    location / {
        proxy_pass http://127.0.0.1:50051;
        proxy_set_header X-Real-IP $remote_addr;
        allow X.X.X.X/XX;
        deny all;
    }
}
```

## grpc server (node.js v4.4.4, grpc v1.3.7)
```
server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());
server.start();
```

## grpc client (node.js v6.10.1, grpc v1.3.7)
```
const creds = grpc.credentials.createSsl();
const clientRpc = new protoDescriptor.Entity('api.foo.com:8443', creds);
clientRpc.getUser(function (err, user) {
    // ...
});
```

# Errors

## grpc server (nginx logs)
```
[error] 1550#1550: *48 upstream sent no valid HTTP/1.0 header while reading response header from upstream,
client: X.X.X.X,
server: api.foo.com,
request: "POST /foo.User/GetUser HTTP/2.0",
upstream: "http://127.0.0.1:50051/foo.User/GetUser",
host: "api.foo.com:8443"
```

## grpc client
```
{
    Error: Received http2 header with status: 000
    at /foo/node_modules/grpc/src/node/src/client.js:442:17 code: 1, 
    metadata: Metadata { _internal_repr: {} }
}
```

Thanks!

**Comment by murgatroid99** [comment]
The message "upstream sent no valid HTTP/1.0 header while reading response header from upstream" indicates that there is a protocol mismatch. As you can see from the headers, gRPC uses HTTP/2 as its transport. Is your nginx set up to handle HTTP/2 traffic?

**Comment by siacomuzzi** [comment]
> Is your nginx set up to handle HTTP/2 traffic?

yes, this is my nginx config:

```
server {
    listen 8443 ssl http2;
    listen [::]:8443 ssl http2;
    ssl_certificate /etc/ssl/private/foo.com.pem;
    ssl_certificate_key /etc/ssl/private/foo.com.key;
    # ...
    
    location / {
        proxy_pass http://127.0.0.1:50051;
        proxy_set_header X-Real-IP $remote_addr;
        allow X.X.X.X/XX;
        deny all;
    }
}
```

do i need anything else?

**Comment by nicolasnoble** [comment]
The question from @murgatroid99 was rather along the lines of "did you actually check that your ngnix was sending http2 traffic to the backend node server ?"

Keep in mind that while we can definitely help with gRPC-related problems, ngnix isn't really part of our expertise. You'd need to do due diligence on your end to debug the traffic between ngnix and the node backend, potentially using tools like tcptrace or wireshark, in order to verify that your ngnix instance is indeed sending http2 traffic. We won't be able to help with ngnix config per-se.

**Comment by wenbozhu** [comment]
@fengli79   @PiotrSikora

**Comment by siacomuzzi** [comment]
> Keep in mind that while we can definitely help with gRPC-related problems, nginx isn't really part of our expertise.

Agree. The main goal of this thread is to find someone that configured succesfully grpc with nginx.

**Comment by PiotrSikora** [comment]
@siacomuzzi NGINX doesn't support HTTP/2 to backends yet, but if you look at nginx-devel@ mailing list, you'll notice that I'm in process of sending patches and working with upstream to add exactly that. Should be available soon.

**Comment by siacomuzzi** [comment]
Excellent news! Thanks PiotrSikora

**Comment by ccl0326** [comment]
@PiotrSikora any progress?

**Comment by PiotrSikora** [comment]
@ccl0326 Nope, still waiting for the code review. Patches are available on the nginx-devel@ mailing list and patched version is temporarily available at https://github.com/PiotrSikora/nginx (branch: h2_proxy).

**Comment by ccl0326** [comment]
@PiotrSikora I have some doubt about proxy of grpc. We use haproxy with L4 as grpc proxy now, But there are some obvious problems exist.

1. application can not graceful shutdown, it's need to coordinate client and server. But L4 proxy can not do it. 
2. load is not balance.  With haproxy, whether round-robin or least-conn or any other policy, we can not make the load balance.if one upstream down, the connections belong to it will reconnect to other upstream and will not reconnect to it any more. So can nginx do it better with http/2 proxy? As my understanding it's seem not.

I have some solutions to make the load balance. e.g. Create a connection pool with proxy or create grpc client with every request. But i want to find the best practice for this.

**Comment by dyadaval** [comment]
@Hello wangming1993, PiotrSikora

Could you please share the working nginx.conf. We are seeing that our nginx h2 proxy(taken from PiotrSikora github) is not forwarding to gRPCServer. our conf file part looks below:
server {
listen 8443 ssl http2;
listen [::]:8443 ssl http2;
ssl_certificate /f0/base/nginx/ssl/certs/server.crt;
ssl_certificate_key /f0/base/nginx/ssl/private/server.key;
# ...

location / {
    proxy_pass http://10.220.73.160:50051;
    proxy_set_header X-Real-IP $remote_addr;
    allow all;
}
10.220.73.160 is the Network element, that has gRPCServer running.

nginx -v

nginx version: nginx/1.13.2

Thanks for help.

Best Regards,
Div

**Comment by PiotrSikora** [comment]
@ccl0326 NGINX is L7 proxy, so your concerns don't apply.

@dyadaval you need to add `proxy_http_version 2.0`.

**Comment by dyadaval** [comment]
Hello Piotr,

We put that still, we got same issue. Could you please paste nginx.conf
server/location block.

Thanks,
Div

**Comment by odino** [comment]
Hi guys, is there any update on nginx's support for grpc?

**Comment by derekmma** [comment]
@odino I found this roadmap which shows that the support for gRPC proxy is coming in this April
https://trac.nginx.org/nginx/roadmap
There is a issue related to this need under another repo: https://github.com/grpc/grpc.github.io/issues/230

**Comment by siacomuzzi** [comment]
FYI https://www.nginx.com/blog/nginx-1-13-10-grpc/

**Comment by ibakirov** [comment]
Issue can be closed

**Comment by n0mer** [comment]
@siacomuzzi since 1.13 : 
```
grpc_pass grpc://localhost:1234;
```

**Comment by arunkjn** [comment]
If I am using nginx as a ingress controller in a kubernetes cluster, what config should I give to ingress to my grpc service?
