### ISSUE TITLE
using grpc with webpack?

### ISSUE THREAD

**Issue by slootzky** [grpc/grpc#11435]
Hey , 
using google's pubsub node client and it depends on grp which depends on node-pre-gyp.
when using webpack (for serverless functions) I get the following runtime error :

> package.json does not exist at...

this comes from pre-bindings.js : 
`if (!existsSync(package_json_path)) {
        throw new Error("package.json does not exist at " + package_json_path);
   }`

and this because in grpc_extensions.js is using  __dirname and then relative path : 

`var binding_path =
    binary.find(path.resolve(path.join(__dirname, '../../../package.json')));`

**Comment by murgatroid99** [comment]
There's a bigger problem with using webpack: gRPC uses a Node C++ addon that interfaces with low-level Node C APIs. It's not going to work except on Node.

**Comment by wenbozhu** [comment]
@slootzky  We haven't yet released grpc-web which uses a different stack than grpc (due to browser limitation). Once grpc-web is available, we should consider making it deployable in Node (webpack etc). 

If you need early access to grpc-web, let me know.

**Comment by slootzky** [comment]
seems like it's also doesn't work on a nodejs Azure function

**Comment by wenbozhu** [comment]
Correct, but a separate issue, i.e. making grpc calls from Azure functions.

**Comment by murgatroid99** [comment]
@slootzky Can you elaborate? What problems did you experience when you tried to use gRPC in a Node.js Azure function?

**Comment by slootzky** [comment]
@murgatroid99 it's because azure functions runs over edgejs
I got the same behaviour as this  [https://stackoverflow.com/questions/42914619/bot-hosted-in-azure-with-google-vision-api-grpc-issue/43767464?noredirect=1#comment76006418_43767464](SO question)

**Comment by raviqqe** [comment]
By the way, the code in `grpc_extensions.js` @slootzky specified should use something like `require("PATH")` so that bundlers and optimizers like webpack, rollup, and prepack can detect loading files in external directories. I believe that bundling and optimization of JS code are getting popular even on server-side nowadays.

**Comment by slootzky** [comment]
totally agree , especially when things like prepack become more stable , I think runtime optimization is always more than welcome.
Think that there shouldn't be boundaries between pure node.js to bundlers like webpack / react-native packager etc.

**Comment by rogerbell82** [comment]
Totally Agree. 
Webpack / React are so popular now. 
Its disappointing that I cannot integrate Google Cloud modules such as Vision into my project.

**Comment by raviqqe** [comment]
It seems to be impossible because of limitation of [node-pre-gyp](https://github.com/mapbox/node-pre-gyp)'s API.

**Comment by bradennapier** [comment]
this sucks....,. you broke my entire app with this bs... there is no way to use any google products with any serverless products now... how do i make these work? ??????????

i dont give two shits about anything but node but this does not work on node either so.... uhh... .yeah......

```
Error: package.json does not exist at /package.json
    at Object.t.find (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-lambda-apex/nodejs/functions/util_firebase/lib/index.js:1451:10748)
    at Object.<anonymous> (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-lambda-apex/nodejs/functions/util_firebase/lib/index.js:154:26)
    at Object.<anonymous> (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-lambda-apex/nodejs/functions/util_firebase/lib/index.js:154:183)
    at t (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-lambda-apex/nodejs/functions/util_firebase/lib/index.js:1:177)
```
