### ISSUE TITLE
Python grpc doesn't handle unicode inside an exception message

### ISSUE THREAD

**Issue by MichaelHills** [grpc/grpc#11442]
### What version of gRPC and what language are you using?
grpc 1.3.5
python 3.5.2
 
### What operating system (Linux, Windows, …) and version?
Mac/Linux, version doesn't matter for this issue
 
### What did you do?
Raised an exception in a grpc service method that contained unicode characters.

e.g.
```
def SomeRpc(req, context):
    raise ValueError('你好')
```
 
### What did you expect to see?
The calling client to receive a message containing the exception info 
 
### What did you see instead?
The grpc server never responds to the client, and the client hangs waiting for a response.
 
I tracked down the issue to this method in `./src/python/grpcio/grpc/_server.py`

```
def _call_behavior(rpc_event, state, behavior, argument, request_deserializer):
    context = _Context(rpc_event, state, request_deserializer)
    try:
        return behavior(argument, context), True
    except Exception as e:  # pylint: disable=broad-except
        with state.condition:
            if e not in state.rpc_errors:
                details = 'Exception calling application: {}'.format(e)
                logging.exception(details)
                _abort(state, rpc_event.operation_call,
                       cygrpc.StatusCode.unknown, _common.encode(details))
        return None, False
```
Specifically the following line produces a unicode string because my exception contains `你好` and I'm using python 3, so strings are unicode.
`details = 'Exception calling application: {}'.format(e)`

Then the call to ` _common.encode(details)` will raise an exception because it's implementation looks like this (from `./src/python/grpcio/grpc/_common.py`):

```
def encode(s):
    if isinstance(s, bytes):
        return s
    else:
        return s.encode('ascii')
```

It tries to encode my unicode as `ascii`, which raises an exception that appears to go uncaught. What I need here is `utf8`, and then it works fine. I'm unsure of the follow-on effects of directly changing this from `ascii` to `utf8` though.

**Comment by nathanielmanistaatgoogle** [comment]
It is not legitimate for server-side application code to raise exceptions into the gRPC Python server-side runtime, and there is no guaranteed behavior of what will happen if server-side application code does fail with an exception. For security reasons we're reluctant to send exception text from server to client.

If you'd like your server-side application code to report a problem to your client-side application code, consider using the trailing metadata, status code, and status details facilities? (Unfortunately there's currently a restriction that the status details string must be ASCII; our apologies about that.)

**Comment by MichaelHills** [comment]
Do you mean that an rpc handler is not allowed to throw an exception? And if it does, then it's undefined behaviour? Such as the gRPC Python server-side runtime never responds back to the client in this scenario? Certainly a rough edge, but thanks for the details on how to handle this properly with metadata/status/details.

You mention the reluctance to send exception text from server to client, but it appears it is currently doing that. It only sends it if its ascii, and raises internally (uncaught) if it's not ascii. This line formats the exception string https://github.com/grpc/grpc/blob/6613f601660e7cf58db2a5dd1e11556378955910/src/python/grpcio/grpc/_server.py#L380
