### ISSUE TITLE
bundle third_party soruces with grpc releases 

### ISSUE THREAD

**Issue by pva** [grpc/grpc#11446]
I've downloaded grpc release 1.3.4. To build python binding with setuptools I need sources in third_party directory. Unfortunately it's not easy (and without git impossible) to find out what versions of third party libs we need. There is no version information inside release tarball as I see. For exampled for boring ssl we need specific commit otherwise it won't work. So, could you, please, bundle all third party sources in release tarballs.

**Comment by nicolasnoble** [comment]
What you're talking about is impossible. The "release tarballs" you're referring to are automatically generated by github, and we have no control over them. You are correct in your assumption that the git submodules with their exact versions or branches are necessary for properly building grpc out of the box for certain target languages such as python, and git cloning with submodules is the only acceptable solution for that.
