### ISSUE TITLE
python grpcio_tools are not buildable with setup.py

### ISSUE THREAD

**Issue by pva** [grpc/grpc#11445]
### What version of gRPC and what language are you using?
 
grpc-1.3.4 release sources.
 
### What operating system (Linux, Windows, …) and version?
 
Gentoo Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc  5.4.0-r2
python 3.5 and 2.7
cython-0.24.1

### What did you do?

After building grcp from Makefile I do
cd tools/distrib/python/grpcio_tools
python setup.py build
 
Build fails. To fix I need:
sed -e "s#'grpc_root', ##" -i setup.py 

IOW grpc_root should not be in setup.py.

**Comment by nicolasnoble** [comment]
This variable should be optionally set from the external world, not forced.

**Comment by kpayson64** [comment]
Building grpcio_tools from github needs to be invoked as tools/distrib/python/make_grpcio_tools.py, due to several specialized build steps.

If you are looking to build grpcio_tools from source, I'd recommend taking a source release of PyPI instead of building from the github repo.

**Comment by pva** [comment]
@kpayson64 but do you mean this package pypi: https://pypi.python.org/pypi/grpc? It looks very outdated.

**Comment by nathanielmanistaatgoogle** [comment]
@pva: we'd like that package to be ours but that's actually a completely unrelated piece of software that happens to have claimed the four-letter name on PyPI before we were able to claim it. Our package for gRPC Python is available at [https://pypi.python.org/pypi/grpcio](https://pypi.python.org/pypi/grpcio) (well, that's our main package; our other packages are [grpcio-tools](https://pypi.python.org/pypi/grpcio-tools), [grpio-health-checking](https://pypi.python.org/pypi/grpcio-health-checking), and [grpcio-reflection](https://pypi.python.org/pypi/grpcio-reflection)... for now).
