### ISSUE TITLE
Many C++ performance test results are failing to upload to bigquery

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11449]
https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/4210

Many of the tests pass, then end with this output:

```
Error inserting rows! Response: {u'kind': u'bigquery#tableDataInsertAllResponse', u'insertErrors': [{u'index': 0, u'errors': [{u'debugInfo': u'generic::not_found: no such field.', u'reason': u'invalid', u'message': u'no such field.', u'location': u'serverstats[0].cqpollcount'}]}]}
```

Sometimes the error's location field is different.

**Comment by adelez** [comment]
Obsolete. I didn't find this error in recent runs. Could be caused by new fields added to result but not db schema.
