### ISSUE TITLE
X509_STORE_add_cert errors need to be decoded and handled

### ISSUE THREAD

**Issue by mastahyeti** [grpc/grpc#11451]
### Should this be an issue in the gRPC issue tracker?

Yes.

### What version of gRPC and what language are you using?
 
```
> GRPC::VERSION
=> "1.2.5"
```
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Ruby

```
> RUBY_VERSION
=> "2.4.0"
```
 
### What did you do?

I pointed GRPC at a CA bundle that included a duplicate certificate and then called a method on my stub:

```ruby
creds = GRPC::Core::ChannelCredentials.new(File.read(ca_file))
stub = MyService::Stub.new(server, creds)
stub.some_method
```

### What did you expect to see?
 
I would expect an exception not to be raised.
 
### What did you see instead?
 
When calling a method on my stub I get a `GRPC::DeadlineExceeded` error, along with the following debugging output:

```
E0609 11:07:14.082544835   29191 ssl_transport_security.c:602] Could not add root certificate to ssl context.
E0609 11:07:14.082587138   29191 ssl_transport_security.c:1348] Cannot load server root certificates.
E0609 11:07:14.082924913   29191 security_connector.c:837]   Handshaker factory creation failed with TSI_INTERNAL_ERROR.
E0609 11:07:14.082939716   29191 secure_channel_create.c:127] Failed to create secure subchannel for secure name 'earthsmoke.service.cp1.consul:8080'
E0609 11:07:14.082947490   29191 secure_channel_create.c:158] Failed to create subchannel arguments during subchannel creation.
E0609 11:07:14.086947973   29191 ssl_transport_security.c:602] Could not add root certificate to ssl context.
E0609 11:07:14.086965201   29191 ssl_transport_security.c:1348] Cannot load server root certificates.
E0609 11:07:14.087280224   29191 security_connector.c:837]   Handshaker factory creation failed with TSI_INTERNAL_ERROR.
E0609 11:07:14.087291073   29191 secure_channel_create.c:127] Failed to create secure subchannel for secure name 'earthsmoke.service.cp1.consul:8080'
E0609 11:07:14.087298127   29191 secure_channel_create.c:158] Failed to create subchannel arguments during subchannel creation.
```

I tracked the issue down to the fact that my CA bundle contains one certificate twice. 
 
### Anything else we should know about your project / environment?

Nope.

**Comment by nicolasnoble** [comment]
What happens if you edit your root certificates to remove the duplicate entry ?

**Comment by nicolasnoble** [comment]
Also, which entry are we talking about ? Which file from our repository, if that's even from our repository ?

**Comment by mastahyeti** [comment]
> What happens if you edit your root certificates to remove the duplicate entry ?

Everything works as expected. My workaround for this issue has been to deduplicate the cert bundle in code before passing them to `GRPC::Core::ChannelCredentials.new`.

> Also, which entry are we talking about ? Which file from our repository, if that's even from our repository ?

The CA bundle is not from this repository. It seems that an error is being returned by OpenSSL [here](https://github.com/grpc/grpc/blob/c7d9c804966d12d852d08f4f132c716846a10ece/src/core/tsi/ssl_transport_security.c#L578), complaining about the duplicate cert in the X509 store.

One possible fix would be to handle that error, since it isn't important that OpenSSL refused to add a duplicate cert to the store. Another option would be to find a way to surface errors from OpenSSL so users can debug them. Currently the only message the user sees is `Could not add root certificate to ssl context`, which isn't helpful for debugging the issue.

**Comment by nicolasnoble** [comment]
Got it. Thanks.

**Comment by mastahyeti** [comment]
We just ran into this on another production server, where the CA bundle had two identical certificates with different line lengths. The workaround in our code is pretty terrible:

```ruby
PEM_REXP = /[-]+BEGIN CERTIFICATE[-]+.+?[-]+END CERTIFICATE[-]+/m

...

# Deduplicate certificates.
certs = certs.scan(PEM_REXP).map do |pem|
  # normalize encoding
  OpenSSL::X509::Certificate.new(pem).to_pem
end.uniq.join("\n")
```

**Comment by jiangtaoli2016** [comment]
It seems that the root pem file provided to gRPC has duplicative entries. Can you run a script to remove those duplicative entries?

**Comment by jiangtaoli2016** [comment]
How come it raise GRPC::DeadlineExceeded? It will fail on SSL handshake.

**Comment by mastahyeti** [comment]
I don't know what it raises DeadlineExceeded. It seems like the library should at least raise a more useful exception.

**Comment by sanjaypujare** [comment]
@jiangtaoli2016 do you have resources to fix this issue now? Your suggested code should work

**Comment by jiangtaoli2016** [comment]
I think this is already fixed in https://github.com/grpc/grpc/pull/17664.
