### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS not an grpc environment variable

### ISSUE THREAD

**Issue by ahmetb** [grpc/grpc#11456]
I was reading https://github.com/grpc/grpc/blob/master/doc/environment_variables.md and `GOOGLE_APPLICATION_CREDENTIALS` is listed there too.

AFAIK, this is not a gRPC specific environment variable and not directly tied to gRPC. It's set by user and is interpreted by Google Cloud client libraries; not by gRPC. Therefore it probably should not be listed in the document.

**Comment by fengli79** [comment]
It's not a Google Cloud client library specific environment variable. Instead, it's defined and interpreted by Google Auth client libraries.
https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/b33b8021117db0d9ef80988cc7bb8ad58ecccf18/google/auth/environment_vars.py#L32

gRPC users may need that information when using a plain gRPC client to access Google APIs. I agree that this is not a gRPC environment variable. As this information is important to anyone who want to use gRPC lib directly, I prefer to keep it in this document, but in a separate section.
