### ISSUE TITLE
Big C# performance regression caused by recent C core changes

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11460]
It looks like C# has taken a huge performance hit by  https://github.com/grpc/grpc/pull/11336 (in throughput benchmarks).
Streaming QPS has gone from 1.2mpps to 0.5mpps, unary is 390kqps to 320kqps. Perhaps C++ has been affected too? 

https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584&widget=952298825&container=846542667

**Comment by ctiller** [comment]
Yeah: it's expected and will be dealt with gradually over the next few
months. Real applications should see a boost however (this primarily hurts
artificial benchmarks).

The big trick to improving performance right now will be having different
threads writing to the same channel at once.

**Comment by jtattermusch** [comment]
I originally filed this to track rootcausing the regression, but I think the issue not useful anymore, so I will just close it.
