### ISSUE TITLE
grpcio 1.3.5 silent exit when used together with multiprocessing and subprocess

### ISSUE THREAD

**Issue by gengyl08** [grpc/grpc#11470]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpcio 1.3.5 python
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 14.04.1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 2.7.6
 
### What did you do?

If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I updated grpcio 1.0.1 to 1.3.5

### What did you expect to see?
 I expected to see my program run the same.
 
### What did you see instead?
 What I do is basically use both subprocess.Popen and  MyProtoStub(grpc.insecure_channel('ip:port')) within a multiprocessing.Process. When I both call Popen and create stubs, the Process will exit silently without any exception or error message. Only calling Popen or creating Stub won't cause this issue. The Process exits when calling Popen.communicate() or creating a new Stub when the two are both already seen in the code.

Before upgrading grpcio to 1.3.5 I was using 1.0.1 which didn't have this issue. I down graded to grpcio 1.0.1 and the issue disappeared.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by nathanielmanistaatgoogle** [comment]
gRPC Python doesn't yet support forking but I can't tell if that's quite the issue here. Are you able to share sample code that demonstrates this behavior?

**Comment by nathanielmanistaatgoogle** [comment]
This seems to have gone stale; closing.
