### ISSUE TITLE
Cannot build ruby gem from source

### ISSUE THREAD

**Issue by volgorean** [grpc/grpc#11481]
### What version of gRPC and what language are you using?
 ruby building from source branch master.
 
### What operating system (Linux, Windows, …) and version?
 Alpine Linux 3.5 (tried 3.2, 3.4, 3.6)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Ruby 2.4.1
 
### What did you do?
 git clone https://github.com/grpc/grpc.git
 cd grpc
 git submodule update --init (also tried without)
 bundle install
 bundle exec rake

 I also tried the following
 * specifying google protobuf dependency 3.3 instead of 3.1 in gemspec
 * building google protobuf dependency from source
 * adding various packages

### What did you see?

```
An error occurred while loading ./src/ruby/spec/pb/health/checker_spec.rb.
Failure/Error: require 'google/protobuf_c'

LoadError:
  Error relocating /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf_c.so: __snprintf_chk: symbol not found - /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf_c.so
# /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf.rb:50:in `require'
# /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
# /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf.rb:47:in `<top (required)>'
# ./src/ruby/pb/grpc/health/v1/health_pb.rb:4:in `require'
# ./src/ruby/pb/grpc/health/v1/health_pb.rb:4:in `<top (required)>'
# ./src/ruby/spec/pb/health/checker_spec.rb:16:in `require'
# ./src/ruby/spec/pb/health/checker_spec.rb:16:in `<top (required)>'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load_spec_file_handling_errors'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1494:in `block in load_spec_files'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `each'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `load_spec_files'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:100:in `setup'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
# /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
# /usr/local/bundle/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
# ------------------
# --- Caused by: ---
# LoadError:
#   Error relocating /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/2.4/protobuf_c.so: __snprintf_chk: symbol not found - /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/2.4/protobuf_c.so
#   /usr/local/bundle/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf.rb:48:in `require'
```

**Comment by apolcyn** [comment]
From `protobuf_c.so: __snprintf_chk: symbol not found`, it looks like the issue here is that the `google-protobuf` gem is failing to load.

I'm not sure if the `google-protobuf` gem supports this platform.

I might try building from source and loading just the `google-protobuf` gem by itself on this platform to verify (https://github.com/google/protobuf/tree/master/ruby).

**Comment by volgorean** [comment]
Thanks @apolcyn
I thought that I had tried installing google-protobuf from source but I must have messed it up somehow.
https://github.com/google/protobuf/issues/2335 shows an easy way to fix the issue by telling bundler to build from source rather than doing it manually (force_ruby_platform true.)
