### ISSUE TITLE
Remove Python's "_junkdrawer" directory of generated code

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1149]
The src/python/src/grpc/_junkdrawer directory should be deleted and the code contained within it generated as part of the set-up of the tests that use it.

**Comment by soltanmm** [comment]
This requires first determining where to put `stock.proto` and `math.proto`. Given that they're mostly duplicated across the source repository, a decision probably needs to be made regarding where to centralize them. An exception to this is C#, which isn't yet at proto3, and therefore must have a different `syntax = "protoN";` line. So, duplication, centralization, or something in between?

**Comment by nathanielmanistaatgoogle** [comment]
That's easy; they'll go wherever they are decided to go in #526. :-)

**Comment by soltanmm** [comment]
Given that #526 was closed with respect to `empty.proto`, `messages.proto`, and `test.proto`, it's still unclear what to do about `stock.proto` and `math.proto`. Should we change our tests to use the other three?

**Comment by nathanielmanistaatgoogle** [comment]
I don't think changing our tests is necessary. Shouldn't stock.proto and math.proto be available alongside the other three?

**Comment by soltanmm** [comment]
With respect to the reorganization in #2698:

Is it kosher to require that `protoc` and its associated Python and GRPC Python plugins are installed at setup-time for `grpcio_test`?

Would it then make sense to move `test/compiler/python_plugin_test.py` (and its associated test proto) to the `grpcio_test` package?

With respect to where the `.proto`s go, It doesn't make sense to both have the test `_pb2.py`s generated at build time (with respect to `setup.py` being the 'build script') if the `.proto`s are not directly included as part of the source distribution (this can *maybe* be messed with via modifying `MANIFEST.in`, but I'm not sure how kosher it is to specify relative file paths for that file's contents).

**Comment by nathanielmanistaatgoogle** [comment]
"Is it kosher to require that `protoc` and its associated Python and GRPC Python plugins are installed at setup-time for `grpcio_test`?": let's avoid it if we can.

"Would it then make sense to move `test/compiler/python_plugin_test.py` (and its associated test proto) to the `grpcio_test` package?": I'd rather see that test stay with the other languages' tests of their generated code. The other languages have tests of their generated code, right?

Maybe the `.proto`s should be in their own low-level "package" and `python_plugin_test` should be in its own high-level "package" that depends upon both `grpcio` and whatever the `.proto` "package" gets called?

I'm open to symlinks. Duplication just feels like punting the problem to another day later in the calendar (and so is a forgivable sin).

**Comment by soltanmm** [comment]
> I'd rather see that test stay with the other languages' tests of their generated code. The other languages have tests of their generated code, right?
[Nope](https://github.com/grpc/grpc/tree/master/test/compiler).

> Maybe the .protos should be in their own low-level "package" and python_plugin_test should be in its own high-level "package" that depends upon both grpcio and whatever the .proto "package" gets called?

Are you suggesting that we make a PyPI package for the compiler plugin...?

**Comment by soltanmm** [comment]
Three separate things:

There's a package for gRPC Python's protoc now (not quite uploaded yet but soon); a subtask of doing this 'right' would be to add a custom command to `grpcio-tools` (providing a `build_proto` thingy) and making it a test-time dependency of `grpcio`.

One of the proto files that generates the `_junkdrawer` code in question doesn't exist in the source tree anymore. 

This is invisible to end users, so I'm changing the milestone to something less urgent.

**Comment by soltanmm** [comment]
This will be automagically solved once beta tests are removed (as they're the only modules with any direct or indirect dependence on the `_junkdrawer` modules).

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information or it might be already fixed. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
