### ISSUE TITLE
gRPC uses too many CPUs

### ISSUE THREAD

**Issue by siddontang** [grpc/grpc#11493]
Hi

We have been wrapping [c gRPC 1.3 in rust](https://github.com/pingcap/grpc-rs) language, and it works well now.

So we decide to use it in our project [TiKV](https://github.com/pingcap/tikv) to replace our origin simple RPC framework. To our surprise, although it can work, the performance is bad. 

In our benchmark, we must use at lease 4 CPUs for gRPC worker, and all CPUs cost 90%+, but we only need 1 CPU for our origin RPC worker. 

[tikv.svg.zip](https://github.com/grpc/grpc/files/1073247/tikv.svg.zip)

We generate a flame graph. Except for the cost of protobuf encoding/decoding, TCP send/recv, and epoll, the large remainder is occupied by gRPC, and we have no way to improve it. 

Is it common that gRPC uses too many CPUs?

**Comment by ofpiyush** [comment]
I've observed this in Python as well. There gRPC often uses 90+% of a single CPU.

**Comment by vjpai** [comment]
Folks, is this still observable in recent versions of gRPC?

**Comment by siddontang** [comment]
@vjpai 

We have not used the recent version because we need the alarm feature but it is deprecated in C core now. 

Do you have any benchmark result to show that the performance increased much?

**Comment by sreecha** [comment]
I am assigning this to @ncteisen who leads the grpc benchmarking infrastructure.

**Comment by sreecha** [comment]
Closing this issue. Please feel free to reopen if you notice similar behavior in the most recent version of gRPC.
