### ISSUE TITLE
Comparison of incoming hostname vs. SSL certificate's SAN/CN should be case-insensitive

### ISSUE THREAD

**Issue by csboling** [grpc/grpc#11498]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?

Yes, this is a bug report.

### What version of gRPC and what language are you using?
 
Tested on 1.3.0 as well as master using a C++ server, C# client, probably affects others
 
### What operating system (Linux, Windows, …) and version?
 
Tested on Windows 10, Linux e.g. Debian Jessie, probably affects others
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Tested with a server compiled with gcc 6.3.0 as well as MSVC 14, probably affects others

### What did you do?

* Configure a gRPC server to listen on an SSL channel using a certificate which names the host's DNS name in its SAN.
* Attempt to connect to this gRPC server using a DNS name which differs from the listening hostname only in case.
 
### What did you expect to see?
 
The comparison of e.g. `mYdOmAiN` vs the cert's SAN of `mydomain` should succeed because DNS is case-insensitive.
 
### What did you see instead?
 
The comparison fails, causing gRPC to refuse the connection. The following message is printed to the console:
```
E0614 13:10:16.440000000  1792 ssl_transport_security.c:1253] No match found for
 server name: mYdOmAin
```
If the cases match exactly then the connection is accepted.

**Comment by jboeuf** [comment]
@justinburke, can you have a look at the issue since you are looking at the TLS stack? I don't really understand why I cannot assign this issue directly to you... oh well...

Here's the relevant of the spec: https://tools.ietf.org/html/rfc5280#section-4.2.1.6

> Note that while uppercase and lowercase letters are allowed in domain names, no significance is attached to the case.

**Comment by sanjaypujare** [comment]
I think this should be fixed

**Comment by jboeuf** [comment]
I agree. @jiangtaoli2016 can you put that one in the queue?

**Comment by jiangtaoli2016** [comment]
Sure, it should be an easy fix. Let me queue for Q3.

**Comment by mKlus** [comment]
Hi @jiangtaoli2016, do you know which future release version this fix would be available in?

**Comment by mKlus** [comment]
@jboeuf or @jiangtaoli2016 any update on this?

**Comment by jiangtaoli2016** [comment]
@mKlus Sorry for delay. I am waiting for grpc absl support, which will be done this month. Once grpc has absl support, it will be one line change :).

**Comment by rdconnelly** [comment]
@jiangtaoli2016 any update?

**Comment by jiangtaoli2016** [comment]
Fixing it.

**Comment by jiangtaoli2016** [comment]
https://github.com/grpc/grpc/pull/22443 
Sorry for delay.
