### ISSUE TITLE
Intermittent errors on pecl install

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc#11492]
I have received errors multiple times when installing gRPC on travis CI. It is intermittent, maybe once every 20 installs or so. When I restart the builds, the error goes away. Sometimes it's this error:

```
$ pecl install grpc
Package "grpc" Version "1.3.2" does not have REST dependency information available
```

It happened for [this build](https://travis-ci.org/GoogleCloudPlatform/php-docs-samples/builds/242628721), which is PHP 7, but the error is gone because I restarted it.

I've also received this error:

```
$ pecl install grpc
Package "grpc" does not have REST info xml available
```

That happened for [this build](https://travis-ci.org/GoogleCloudPlatform/php-docs-samples/jobs/242630069), and I will kick off a new build instead of restarting it so that we can keep the logs.

**Comment by stanley-cheung** [comment]
This appears to be intermittent issue on PECL side. I only found very old articles/bugs about this.

**Comment by stanley-cheung** [comment]
Closing this as this is a PECL availability issue.
