### ISSUE TITLE
I am running into a defect inside of the node version of grcp...

### ISSUE THREAD

**Issue by richtera** [grpc/grpc#11514]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes

Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.3.8
 
### What operating system (Linux, Windows, …) and version?
 Running on Mac but also seeing it on Linux.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 node 6.11
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 After an error happens on a duplex stream then _write function has a bug.
```
function _write(chunk, encoding, callback) {
  /* jshint validthis: true */
  var batch = {};
  var message;
  var self = this;
  if (this.writeFailed) {
    /* Once a write fails, just call the callback immediately to let the caller
       flush any pending writes. */
    setImmediate(callback);
    return; //// <<<< This is missing causing callback to happen twice and killing the process.
  }
  try {
    message = this.serialize(chunk);
  } catch (e) {
    /* Sending this error to the server and emitting it immediately on the
       client may put the call in a slightly weird state on the client side,
       but passing an object that causes a serialization failure is a misuse
       of the API anyway, so that's OK. The primary purpose here is to give the
       programmer a useful error and to stop the stream properly */
    this.call.cancelWithStatus(grpc.status.INTERNAL, 'Serialization failure');
    callback(e);
  }
  if (_.isFinite(encoding)) {
    /* Attach the encoding if it is a finite number. This is the closest we
     * can get to checking that it is valid flags */
    message.grpcWriteFlags = encoding;
  }
  batch[grpc.opType.SEND_MESSAGE] = message;
  this.call.startBatch(batch, function(err, event) {
    if (err) {
      /* Assume that the call is complete and that writing failed because a
         status was received. In that case, set a flag to discard all future
         writes */
      self.writeFailed = true;
    }
    callback();
  });
}
```
### What did you expect to see?
 Normal shutdown of erred connection.
 
### What did you see instead?
 Process dies with cb() is not a function.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 ```
error: speech error Error: Audio data is being streamed too slow. Please stream audio data approximately at real time.
    at ClientDuplexStream._emitStatusIfDone (/Users/andy/Development/ss-admin/node_modules/grpc/src/node/src/client.js:209:19)
    at ClientDuplexStream._readsDone (/Users/andy/Development/ss-admin/node_modules/grpc/src/node/src/client.js:177:8)
    at readCallback (/Users/andy/Development/ss-admin/node_modules/grpc/src/node/src/client.js:250:12)
---------------------------------------------
    at Pumpify.Readable.on (/Users/andy/Development/ss-admin/node_modules/readable-stream/lib/_stream_readable.js:661:33)
    at /Users/andy/Development/ss-admin/www.js:304:24
    at process._tickCallback (internal/process/next_tick.js:109:7)
TypeError: cb is not a function
    at afterWrite (_stream_writable.js:385:3)
    at onwrite (_stream_writable.js:376:7)
    at Immediate.WritableState.onwrite (_stream_writable.js:90:5)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
---------------------------------------------
    at ClientDuplexStream._write (/Users/andy/Development/ss-admin/node_modules/grpc/src/node/src/client.js:107:5)
    at doWrite (_stream_writable.js:331:12)
    at clearBuffer (_stream_writable.js:438:7)
    at onwrite (_stream_writable.js:370:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at /Users/andy/Development/ss-admin/node_modules/grpc/src/node/src/client.js:133:5
```
### Anything else we should know about your project / environment?
After patching client.js with the missing return it's working normally.

**Comment by connor4312** [comment]
Ran across this in my testing. Getting this merged in should be somewhat urgent, as this issue results in a high probability of Node services crashing under poor network conditions.

**Comment by jaumard** [comment]
Is this fix deploy on last version of grpc (v1.4.1) ?

**Comment by richtera** [comment]
Yes as far as I can see it does:
I have version 1.4.1 and the file in question has:
```javascript
function _write(chunk, encoding, callback) {
  /* jshint validthis: true */
  var batch = {};
  var message;
  var self = this;
  if (this.writeFailed) {
    /* Once a write fails, just call the callback immediately to let the caller
       flush any pending writes. */
    setImmediate(callback);
    return; // <<<< There is a return here as required
  }
  try {
    message = this.serialize(chunk);
  } catch (e) {
    /* Sending this error to the server and emitting it immediately on the
       client may put the call in a slightly weird state on the client side,
       but passing an object that causes a serialization failure is a misuse
```

**Comment by jaumard** [comment]
Thanks @richtera, just need to wait that google speech module update his version of grpc now ^^ 
This issue can be close, don't have the crash anymore by patching with same fix.

**Comment by richtera** [comment]
If you add grpc to your package.json speech should not install it's own and use this one. From my npm ls:
```
├─┬ @google-cloud/speech@0.9.4
│ ├─┬ @google-cloud/common-grpc@0.3.6
│ │ └─┬ dot-prop@2.4.0
│ │   └── is-obj@1.0.1
```
and
```
├─┬ grpc@1.4.1
│ ├── arguejs@0.2.3
│ ├── nan@2.6.2
│ ├─┬ node-pre-gyp@0.6.36
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ ├─┬ nopt@4.0.1
│ │ │ ├── abbrev@1.1.0
│ │ │ └─┬ osenv@0.1.4
│ │ │   ├── os-homedir@1.0.2
│ │ │   └── os-tmpdir@1.0.2
│ │ ├─┬ npmlog@4.1.2
│ │ │ ├─┬ are-we-there-yet@1.1.4
│ │ │ │ ├── delegates@1.0.0
.
.
.
```

**Comment by jaumard** [comment]
Ho nice !! I didn't know that as it bump a minor version not a patch one :) I was thinking it will install his own version inside and the last in my project 
Thanks a lot !

**Comment by richtera** [comment]
The new grpc seems to have similar issues where it's again crashing the service with messages after the connection has been closed.
Any exceptions thrown in here cannot be caught:
```javascript
/**
 * If we have both processed all incoming messages and received the status from
 * the server, emit the status. Otherwise, do nothing.
 * @private
 */
function _emitStatusIfDone() {
  /* jshint validthis: true */
  var status;
  if (this.read_status && this.received_status) {
    if (this.read_status.code !== constants.status.OK) {
      status = this.read_status;
    } else {
      status = this.received_status;
    }
    if (status.code === constants.status.OK) {
      this.push(null);
    } else {
      var error = new Error(status.details);
      error.code = status.code;
      error.metadata = status.metadata;
      this.emit('error', error);
    }
    this.emit('status', status);
  }
}

ClientReadableStream.prototype._emitStatusIfDone = _emitStatusIfDone;
```
Any ideas?

**Comment by murgatroid99** [comment]
Can you be more specific? What failure exactly are you seeing? Is there an error message?

**Comment by richtera** [comment]
I will catch it again. It was basically reacting similar to the initial problem on this page where the destroy of the client duplex did not prevent it from trying to emit a pending error which then didn't have a place to go and got thrown as an uncaughtException error and stopped the instance. I tried to create a workaround by assigning _emitStatusIfDone to an empty method. This did solve the problem for now but it should probably be handled better.

**Comment by richtera** [comment]
Basically due to timing the UI shutdown the listen before any samples got sent to the backend. So my websocket got shutdown right after the speech api stream was initiated. So it got stopped right after starting it. Therefore it had a pending error.

**Comment by murgatroid99** [comment]
Have you set an event handler for the call's `error` event?

**Comment by richtera** [comment]
Yes I did, but I think when I call destroy() (since there is no close() or similar method to end the stream (maybe that's my problem)) it seems to be left in a bad state.

**Comment by murgatroid99** [comment]
You should never be calling the `destroy` method. Assuming that you have a writable stream, the method to end the stream is `end`.

**Comment by richtera** [comment]
It's a speech recognizer stream I can try calling end to see if it behaves well. It's a duplex stream and I want it to both finalize the send and prevent any more incoming packets or events.
