### ISSUE TITLE
How to cancel a GRPC Server streaming call from Client in C#?

### ISSUE THREAD

**Issue by varshanbp** [grpc/grpc#11551]
How to cancel a GRPC Server streaming call from Client in C#.

I want to cancel a server streaming call from client.

**Comment by jtattermusch** [comment]
Two things:
- Please use the issue template for new issues.
- According to the issue template text, usage question should go to a grpc.io forum, not filed as "issues". Please respect that.

streaming calls objects in C# have a Cancel() method. Also, disposing the call before the call finishes has the effect of cancelling it.
