### ISSUE TITLE
Please update the version of the ruby gem

### ISSUE THREAD

**Issue by tony612** [grpc/grpc#1156]
The extension can't be compiled in version 0.5.0, but it's fixed in master. And I think it better to separate the ruby source from this repository so that we can just specify the git repo in Gemfile.

**Comment by atombender** [comment]
+1. This probably relates to [this comment](https://github.com/grpc/grpc/commit/b9e15638539f37945ce7e461aedc6891dce904da). Contrary to the commit message, the change to `extconf.rb` is also needed for earlier Ruby versions, which need support for `static inline` (which is disabled by `-std=c89`). Verified to fail to compile for Ruby 2.1.5.

**Comment by tbetbetbe** [comment]
[Ruby 0.6.0](https://rubygems.org/gems/grpc/versions/0.6.0) was released yesterday and fixes this issue.
