### ISSUE TITLE
Problem in using same Channel for multiple RPC concurrently

### ISSUE THREAD

**Issue by varshanbp** [grpc/grpc#11573]
### Should this be an issue in the gRPC issue tracker?
 Yes
 
### What version of gRPC and what language are you using?
 
GRPC 1.3.6
 
### What operating system (Linux, Windows, …) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 VS 2017
 
### What did you do?
I was streaming a call through Channel. Then made another Single RPC using the same channel. There is lot of delay in getting the result of Single RPC. 
 
### What did you expect to see?
 Immediate result of Single RPC.
 
### What did you see instead?
Single RPC took lot of time and only got result when I get Streaming RPC Result.

**Comment by varshanbp** [comment]
If 2 streams are using the channel. Both reply come at same time irrespective of Sent Time

**Comment by varshanbp** [comment]
When streaming is done using a channel, other calls made through that channel gets Delayed.

**Comment by varshanbp** [comment]
This issue occurs only in C#.

**Comment by apolcyn** [comment]
@varshanbp this needs to be qualified a bit more, otherwise it looks hard to say if there's an issue (is this a performance related?). RPC's on the same channel are meant to be concurrent on the same connection.

**Comment by varshanbp** [comment]
This must be Performance related. 

When streaming, if another RPC is made then it takes lot of time. This happens only when using C# as server. This does not happen on Java Server.
