### ISSUE TITLE
C GCC musl h2_* tests failing in Linux Portability Master

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#11592]
Starts failing at this build: https://grpc-testing.appspot.com/job/gRPC_portability_master_linux/1668/

@ncteisen - Can you look at the failures and see if #10833 is responsible for this? Your PR was the major change between that build and the previous.

**Comment by ncteisen** [comment]
Yep I'll take a look at this. Definitely looks to be caused by the tracing overhaul. Are the musl tests running on every PR? Because all the tests looked clean there.

Other things I notice: a lot of them fail with the message:

```
gRPC tests require a helper port server to allocate ports used 
during the test.

This server is not currently running.

To start it, run tools/run_tests/start_port_server.py

Command exited with non-zero status 1
```
Might that be it?

I'll take closer look at this this weekend/Monday

**Comment by ncteisen** [comment]
Ahh from #10879 I see that the PR portability just builds the tests, and then only Master actually runs them. Ok so I am probably missing a PRIxPTR or something somewhere
