### ISSUE TITLE
Statically build gRPC with embedding libprotobuf

### ISSUE THREAD

**Issue by adavoudi** [grpc/grpc#11594]
I need to build a static version of gRPC library so that it can be used in another application without the need of `libprotobuf.so`. I mean, we be able to just include `libgrpc++.so` in our application build command.

Thanks in advance

**Comment by fedemengo** [comment]
I'm interested too

**Comment by jtattermusch** [comment]
You can get a statically link monolith two ways:
1. use bazel
2. use cmake with the right options so that everything is linked statically.
