### ISSUE TITLE
small message size but latency is so high!!

### ISSUE THREAD

**Issue by gaozijuan** [grpc/grpc#11593]
I want to use grpc-v1.4.0-pre1 to implement low latency and high throughput. This was using bidirectional streaming RPC (C++ implementation)

Client side:
One thread generate request then push request to boost lockfree queue.
Other thread: first do cq.AsyncNext(...),  then pop request from queue ,finally stream.Write(request)

In my case: there are two requests, one is 2376-byte, the other one is 176-byte 

An average round trip latency(Machine A sends a request to  Machine  B, then Machine  B sends a response back to  Machine  A) of  2376-byte is 400 us when the throughput is 65K tps.
But the 176-byte request latency is 6.2 ms when the throughput is 65K tps.
and the 176-byte request latency is 8 ms when the throughput is 150K tps.

Why the 176-byte request latency is so high?

**Comment by vjpai** [comment]
I would request not only the information in the standard template
(platform, compiler, etc) but also a code snippet. We can't possibly help
investigate this issue without knowing what the code looks like.
