### ISSUE TITLE
pecl install for grpc 1.4.0 fails on centos7

### ISSUE THREAD

**Issue by dyeshurun** [grpc/grpc#11597]
Trying to install php grpc extension fails (os = centos7)
> pecl install grpc
...
configure: error: in `/var/tmp/pear-build-defaultuserWMUQLd/grpc-1.4.0':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
ERROR: `/var/tmp/grpc/configure --with-php-config=/usr/bin/php-config' failed 

Note that when I explicitly installing 1.3.2 then it works fine.

**Comment by stanley-cheung** [comment]
A c++ dependency was introduced since version 1.4.0. In centos7, you may likely need to install this before install the grpc extension:
```
yum install gcc-c++
```

**Comment by dyeshurun** [comment]
Didn't help :(

**Comment by stanley-cheung** [comment]
Same as #11957
