### ISSUE TITLE
"Endpoint read failed" on helloworld example

### ISSUE THREAD

**Issue by mshiryaev** [grpc/grpc#11603]
Hello,
I am trying to get work python helloworld example on single-node.

I started server: python ./greeter_server.py
and client in other console: python ./greeter_client.py
and got error on client's side:

Traceback (most recent call last):
  File "./greeter_client.py", line 33, in <module>
    run()
  File "./greeter_client.py", line 28, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "...python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "...python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>

configuration:
grpc version: grpcio-1.5.0.dev0, from master branch, commit 9a69478498232b6b42169f8a1a389b51fb4e03ec
language: python
os: linux, RHEL Server release 7.1 (Maipo) Kernel 3.10.0-229.el7.x86_64
python: 2.7.13
gcc: 4.8.3

grpcio-1.0.0 works.

**Comment by wconstab** [comment]
can you confirm if `http_proxy` or similar variables are set in your environment?  If so, try unsetting them?

On a related note, it looks like grpc does not honor the `no_proxy` variable, which could be a way for it to avoid using the proxy specified by `http_proxy` to connect to localhost or other local addresses.

**Comment by mshiryaev** [comment]
Yes, I have these variables and after unsettling of them grpc examples work on single-node. Thanks for support.

**Comment by nathanielmanistaatgoogle** [comment]
Seems like this is resolved; closing.
