### ISSUE TITLE
Metadata key uniqueness

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#1160]
Is there agreement among the wrapping language implementations of GRPC that violation of metadata key uniqueness results in undefined behavior, or that such violation is impossible/checked against?

n.b. there are no guards against it at the C core layer.

e.g. [Here](https://github.com/grpc/grpc/blob/master/include/grpc/grpc.h#L222) there is an array of [`grpc_metadata`](https://github.com/grpc/grpc/blob/master/include/grpc/grpc.h#L185); there are no guarantees made explicit by documentation that the keys _should_ be unique.

**Comment by murgatroid99** [comment]
Metadata keys are not guaranteed or expected to be unique.

**Comment by soltanmm** [comment]
Then there's disagreement among various parties and this should be decided on. :-D

**Comment by nicolasnoble** [comment]
Let's rather say that finding clear documentation on the subject doesn't
seem straightforward. The question is: is it acceptable and deterministic
for the metadata to have duplicated keys?

**Comment by soltanmm** [comment]
The conclusion was that metadata keys aren't necessarily unique.
