### ISSUE TITLE
Node performance benchmark gets stuck

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11612]
https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/4232/console (and several previous builds on master).

The first build that got stuck is https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/4222/ (maybe a red herring, but it has this change: https://github.com/grpc/grpc/pull/11520)

The last thing it prints before getting stuck forever:
```
15:52:21 2017-06-26 22:52:21,827 START: qps_worker_node_1
15:52:21 2017-06-26 22:52:21,829 START: qps_worker_node_2
15:52:21 2017-06-26 22:52:21,834 START: qps_json_driver.node_generic_streaming_ping_pong
```

**Comment by jtattermusch** [comment]
CC @murgatroid99

**Comment by matt-kwong** [comment]
@murgatroid99 Were there any recent changes to Node performance? It looks like it's getting stuck on Node performance testing. 
```
00:49:52.248 2017-06-26 22:52:21,834 START: qps_json_driver.node_generic_streaming_ping_pong
00:49:52.250 2017-06-26 22:52:21,836 WAITING: 1 queued, 1 jobs running, 0 complete, 0 failed
11:26:44.693 Build was aborted
```

**Comment by murgatroid99** [comment]
I haven't made any changes to the Node performance test, and I don't know of any changes that would cause this, but I'll look into it.

**Comment by jtattermusch** [comment]
Have you checked if https://github.com/grpc/grpc/pull/11520 is causing this? It started getting stuck right after it was merged.

**Comment by matt-kwong** [comment]
I'll take a look to see if #11520 is causing this and come up w/ a workaround if it is.
