### ISSUE TITLE
Feature Request: Generate Protocol for Generated Service Interface

### ISSUE THREAD

**Issue by nallohki** [grpc/grpc#11628]
Currently, generated service files have the following pattern:

```objc
@interface MyGeneratedService : NSObject

- (void)myRpcWithRequest1:(MyRpcRequest1 *)request
                  handler:(void(^)(MyRpcResponse1 *_Nullable response, NSError *_Nullable error))handler;

- (void)myRpcWithRequest2:(MyRpcRequest2 *)request
                  handler:(void(^)(MyRpcResponse2 *_Nullable response, NSError *_Nullable error))handler;

...

@end
```

These services work great, but they have the general issue that when we wish to provide an alternate implementation (such as for testing or proxying calls), our only choices are:
(1) Casting through id
(2) Subclassing
(3) Manually creating a category.

Each of these have demerits if the service definition ever changes, as the compiler will not catch various cases.

What would be really helpful is this:

```objc
@protocol MyGeneratedService

- (void)myRpcWithRequest1:(MyRpcRequest1 *)request
                  handler:(void(^)(MyRpcResponse1 *_Nullable response, NSError *_Nullable error))handler;

- (void)myRpcWithRequest2:(MyRpcRequest2 *)request
                  handler:(void(^)(MyRpcResponse2 *_Nullable response, NSError *_Nullable error))handler;

@end

@interface MyGeneratedService : NSObject<MyGeneratedService>

@end
```

This would allow our code to pass objects around as an id<MyGeneratedService>, and be guaranteed at compile time that the contract is fulfilled.

**Comment by muxi** [comment]
This feature is already implemented :)
