### ISSUE TITLE
Follow instructions for building does not build.

### ISSUE THREAD

**Issue by willoch** [grpc/grpc#11631]
### What version of gRPC and what language are you using?
v.1.4.x  C++
 
### What operating system (Linux, Windows, …) and version?
 Linux , Centos 7.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc version 4.8.5 
 
### What did you do?
git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
cd grpc/
git submodule update --init
make

(the instructions from INSTALL.ṁd)
### What did you expect to see?
 Sucessfull build
 
### What did you see instead?
 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c:65:30: error: field ‘dns_server_addr’ has incomplete type
   struct ares_addr_port_node dns_server_addr;
                              ^
src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c: In function ‘grpc_dns_lookup_ares’:
src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c:268:5: error: implicit declaration of function ‘ares_set_servers_ports’ [-Werror=implicit-function-declaration]
     int status = ares_set_servers_ports(*channel, &r->dns_server_addr);
     ^
cc1: all warnings being treated as errors

a 
git checkout master
git submodule update

caused it to compile fine.
It still did not link.
LD_LIBRARY_PATH=/usr/local/lib LD_RUN_PATH=/usr/local/lib make

made it link, and will cause the runtime linker to work also

**Comment by willoch** [comment]
``

**Comment by ncteisen** [comment]
See #11296. This should be fixed. Can you repro on HEAD?

**Comment by willoch** [comment]
It is still so that following the instructions in INSTALL.md : 
```sh
 $ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init
 $ make
 $ [sudo] make install
```

Then it fails.
It is still so that if I do
```
git checkout master
git submodule update
LD_LIBRARY_PATH=/usr/local/lib LD_RUN_PATH=/usr/local/lib make
```

then it will work.

I understand that if I had installed c-ares-devel then this would not happen.
But I did not. And the instructions did not ask me to. And the c-ares that follows v1.4.1.x is clearly broken.

I do not understand what " Can you repro on HEAD?" means.

**Comment by ppg** [comment]
FYI, this also appears to fail on master for node.js with a similar error via `node-gyp`:
```
../src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c:51:30: error: field ‘dns_server_addr’ has incomplete type
   struct ares_addr_port_node dns_server_addr;
                              ^~~~~~~~~~~~~~~
../src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c: In function ‘grpc_dns_lookup_ares_impl’:
../src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c:334:18: error: implicit declaration of function ‘ares_set_servers_ports’ [-Werror=implicit-function-declaration]
     int status = ares_set_servers_ports(*channel, &r->dns_server_addr);
                  ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
grpc.target.mk:386: recipe for target 'Release/obj.target/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.o' failed
make: *** [Release/obj.target/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.o] Error 1
```

I tried both with and without `libc-ares-dev` installed (on Ubuntu 17.04).

Of note, the `binding.gyp` has `GRPC_ARES=0` so I modified that to delete that and `GRPC_UV` to see if I could use cares at all, but got stuck on this compilation.
