### ISSUE TITLE
Memory leak with php extension

### ISSUE THREAD

**Issue by K4ST0R** [grpc/grpc#11632]
Hello,

I have a memory leak with the php extension with this simple code : 
`
$clientRedis = new Serviceredis\ServiceRedisClient('localhost:10000', [
	'credentials' => Grpc\ChannelCredentials::createInsecure(),
]);
`
I think I manage to locate the leak, in `php/lib/Grpc/BaseStub.php` this part in the constructor
` ChannelCredentials::setDefaultRootsPem($ssl_roots);`

Link to this method `PHP_METHOD(ChannelCredentials, setDefaultRootsPem)` in `php/ext/grpc/channel_credentials.c`
There is a malloc there
`default_pem_root_certs = gpr_malloc((pem_roots_length + 1) * sizeof(char));
  memcpy(default_pem_root_certs, pem_roots, pem_roots_length + 1);`
but I can not see free for default_pem_root_certs.

If I comment `ChannelCredentials::setDefaultRootsPem($ssl_roots)` in the constructor i don't have memory leak anymore.

Nginx + php fpm
nginx 1.12.0
php 5.6.30
grpc      1.4.0
protobuf  3.3.2
`
Debian 8.8 / kernel 4.9.0-0.bpo.2-amd64

**Comment by arnaud-lb** [comment]
I confirm the issue.

`setDefaultRootsPem()` is allocating a memory buffer large enough to contain the roots pem. The memory buffer is never freed. Calling `setDefaultRootsPem()` multiple times will allocate the buffer again, and leak more memory: https://github.com/grpc/grpc/blob/7897ae9308a25a064ee2e7386da25d37cc3273fa/src/php/ext/grpc/channel_credentials.c#L99

From looking at the code, it seems that other language bindings may suffer from the same issue.

**Comment by zackangelo** [comment]
@stanley-cheung This is a major issue for us. 

If we don't have a long-term fix in sight, would it be possible to get an official patch that supports disabling TLS behavior altogether?

**Comment by jackwakefield** [comment]
@zackangelo You may have luck with #12706

**Comment by stanley-cheung** [comment]
This should be fixed in 1.8.5
