### ISSUE TITLE
gRPC's Bazel build depends on a WORKSPACE file

### ISSUE THREAD

**Issue by bobobo1618** [grpc/grpc#11630]
gRPC isn't a binary that's distributed to end users, it's a library intended to be embedded in other projects.

To facilitate this, it would be best if it worked without requiring a WORKSPACE file, as this prevents any other Bazel project from embedding it.

**Comment by nicolasnoble** [comment]
That's nonsense. The WORKSPACE file is ignored by Blaze on subprojects.

If you have a WORKSPACE file in your project, which references grpc, or WORKSPACE files will be superseded by yours.

If anything, our WORKSPACE file should be used as a reference for the list of externals you need to bind in yours, since you need to match the names we are using.

**Comment by bobobo1618** [comment]
I wasn't trying to say that it caused a conflict, the problem I'm trying to point out is that gRPC requires a lot of work to integrate as all its dependencies have to be pulled out and put in the parent project.

This could be avoided by (for example) cloning the dependency repositories, adding a BUILD file to them and depending on them using `//third_party/project:target` as if they were any other component of the project.

This does raise the problem that any other project embedding gRPC may have issues if it tries to link a binary with its own version of the library but that should be resolvable by simply using the one already embedded in gRPC and would be worth (to me at least) the simplicity of just adding a single gRPC repository and being done.

Perhaps the title I should have used is "gRPC is difficult to embed in Bazel projects".

**Comment by nicolasnoble** [comment]
So, that's the problem with any Bazel project that uses complex subprojects. If you look at TensorFlow for example, their own WORKSPACE file is split into a myriad of subscripts-scripts that do a lot of work:

https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl

That's... what you get if you want to use Bazel properly :-)

One of the things that Bazel enforces in fact, is a singular version of a library for the whole project. Let's say you have TensorFlow, currently depending on gRPC 1.3. If you want to create a binary using Bazel, that depends on TensorFlow, you WON'T get to use TensorFlow's WORKSPACE file. But you'll have to provide the same names for everything. So while TensorFlow depends on gRPC 1.3 currently through its WORKSPACE, you can override this to point at gRPC 1.4 in your own WORKSPACE that overrides the one from TensorFlow. Yes, this is complex, but this also guarantees that you don't have more than one copy of the code at a given time in a single project.
