### ISSUE TITLE
NodeJS Client builds empty 

### ISSUE THREAD

**Issue by LibertyBeta** [grpc/grpc#11635]
### What version of gRPC and what language are you using?
 
1.4.1 
 
### What operating system (Linux, Windows, …) and version?
 
Various(Mac OS, Ubuntu, Centos)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Node.JS
 
### What did you do?
Updated from Node.js 1.3.9 to 1.4.1.
Buffers were previous creating clients. 
Now they aren't, and they are doing so without bugs. 
 
### What did you expect to see?
A Working Client
 
 
### What did you see instead?
An Empty Client
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by murgatroid99** [comment]
You haven't provided any of the information relevant to understanding, reproducing, or solving the problem. What is the relevant piece of code? What did you expect the code to do? What did it do instead?

**Comment by LibertyBeta** [comment]
Instantiation and Generation of clients(With any buffers) is returning an empty object in Node. 

For example: 

```
const address = 'SOMESERVER';
const creds = grpc.credentials.createInsecure();
const client = new someBuffer.TEST(address, creds);
```

This will return an empty object. No channels, nothing.

**Comment by murgatroid99** [comment]
What is `someBuffer`?

**Comment by LibertyBeta** [comment]
A loaded buffer, gotten via `grpc.load`

**Comment by murgatroid99** [comment]
When you say that you got an "empty object", do you specifically mean that it has no "own properties", or that it generally fails to provide the functionality you expect from a client object?

Can you provide a complete reproduction case? We have a number of tests that follow that general pattern, so you must be encountering a scenario we haven't considered.

**Comment by LibertyBeta** [comment]
The Object has no properties. 

I'll check with engineering to see if we can clear some of the code for the public. Baring that, I'll write up an example of the fail case and post it(I can fail it fairy regularly now).

**Comment by murgatroid99** [comment]
To be clear, you are looking at an instance of a class, which is part of a prototype chain. Some fields and methods may be properties of the prototype, or the prototype's prototype. Fields on the prototype will not be printed if you stringify the object, for example, but that doesn't mean that they don't exist.

**Comment by murgatroid99** [comment]
Due to lack of further comments by the reporter, I think this question has been resolved.
