### ISSUE TITLE
round_robin: periodically retry connecting to failed subchannels

### ISSUE THREAD

**Issue by c-bb** [grpc/grpc#11643]
As [discussed](https://github.com/grpc/grpc/issues/11578#issuecomment-311057963) in #11578, the `round_robin` load-balancer should periodically attempt to reconnect to failed subchannels.

As it stands, if a service lives on _n_ remote servers, all of which eventually undergo downtime/maintenance, then a (long-lived) client will gradually lose connectivity to more and more servers, until only one is left, and only when that one goes down, does it reconnect to all of them. Not especially great for load-balancing.

I'm creating this issue for tracking, as advised by @dgquintas. Hopefully this can get fixed for 1.5.

**Comment by tjb1216** [comment]
I meet this problem too, hope to fix it asap!

**Comment by tjb1216** [comment]
agree!

**Comment by tjb1216** [comment]
@dgquintas, Can this problem fixed in 1.5?

**Comment by dgquintas** [comment]
There's now a PR with the code addressing this issue (#12228). If the review moves quickly enough, I'll try to include the changes into the upcoming (29th of August) 1.6 release (we skipped 1.5).

**Comment by dgquintas** [comment]
Happy new year! And with it, comes what'll hopefully finally take care of this issue. See #13932
