### ISSUE TITLE
If "boringssl" is intended for Google internal use, how do we suppress building it?

### ISSUE THREAD

**Issue by austinpagan** [grpc/grpc#11655]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 latest gRPC, language is C++
 
### What operating system (Linux, Windows, …) and version?
 Linux, Centos 6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.9.4
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I did all the prelim prerequisites, and I then typed "make".
 
### What did you expect to see?
 a bunch of code being built successfully
 
### What did you see instead?
-bash-4.1$ make clean
[CLEAN]   Cleaning build directories.
-bash-4.1$ make > make.out 2>&1
-bash-4.1$ cat make.out
[MAKE]    Generating /home/fossum/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /home/fossum/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
make: Circular /home/fossum/grpc/libs/opt/libares.a <- /home/fossum/grpc/libs/opt/libz.a dependency dropped.
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
[C]       Compiling third_party/cares/cares/ares__get_hostent.c
[C]       Compiling third_party/cares/cares/ares__read_line.c
[C]       Compiling third_party/cares/cares/ares__timeval.c
[C]       Compiling third_party/cares/cares/ares_cancel.c
[C]       Compiling third_party/cares/cares/ares_create_query.c
[C]       Compiling third_party/cares/cares/ares_data.c
[C]       Compiling third_party/cares/cares/ares_destroy.c
[C]       Compiling third_party/cares/cares/ares_expand_name.c
[C]       Compiling third_party/cares/cares/ares_expand_string.c
[C]       Compiling third_party/cares/cares/ares_fds.c
[C]       Compiling third_party/cares/cares/ares_free_hostent.c
[C]       Compiling third_party/cares/cares/ares_free_string.c
[C]       Compiling third_party/cares/cares/ares_getenv.c
[C]       Compiling third_party/cares/cares/ares_gethostbyaddr.c
[C]       Compiling third_party/cares/cares/ares_gethostbyname.c
[C]       Compiling third_party/cares/cares/ares_getnameinfo.c
[C]       Compiling third_party/cares/cares/ares_getopt.c
[C]       Compiling third_party/cares/cares/ares_getsock.c
[C]       Compiling third_party/cares/cares/ares_init.c
[C]       Compiling third_party/cares/cares/ares_library_init.c
[C]       Compiling third_party/cares/cares/ares_llist.c
[C]       Compiling third_party/cares/cares/ares_mkquery.c
[C]       Compiling third_party/cares/cares/ares_nowarn.c
[C]       Compiling third_party/cares/cares/ares_options.c
[C]       Compiling third_party/cares/cares/ares_parse_a_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_aaaa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_mx_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_naptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ns_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_soa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_srv_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_txt_reply.c
[C]       Compiling third_party/cares/cares/ares_platform.c
[C]       Compiling third_party/cares/cares/ares_process.c
[C]       Compiling third_party/cares/cares/ares_query.c
[C]       Compiling third_party/cares/cares/ares_search.c
[C]       Compiling third_party/cares/cares/ares_send.c
[C]       Compiling third_party/cares/cares/ares_strcasecmp.c
[C]       Compiling third_party/cares/cares/ares_strdup.c
[C]       Compiling third_party/cares/cares/ares_strerror.c
[C]       Compiling third_party/cares/cares/ares_timeout.c
[C]       Compiling third_party/cares/cares/ares_version.c
[C]       Compiling third_party/cares/cares/ares_writev.c
[C]       Compiling third_party/cares/cares/bitncmp.c
[C]       Compiling third_party/cares/cares/inet_net_pton.c
[C]       Compiling third_party/cares/cares/inet_ntop.c
[C]       Compiling third_party/cares/cares/windows_port.c
[AR]      Creating /home/fossum/grpc/libs/opt/libares.a
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
[C]       Compiling third_party/zlib/crc32.c
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzclose.c
[C]       Compiling third_party/zlib/gzlib.c
[C]       Compiling third_party/zlib/gzread.c
[C]       Compiling third_party/zlib/gzwrite.c
[C]       Compiling third_party/zlib/infback.c
[C]       Compiling third_party/zlib/inffast.c
[C]       Compiling third_party/zlib/inflate.c
[C]       Compiling third_party/zlib/inftrees.c
[C]       Compiling third_party/zlib/trees.c
[C]       Compiling third_party/zlib/uncompr.c
[C]       Compiling third_party/zlib/zutil.c
[AR]      Creating /home/fossum/grpc/libs/opt/libz.a
[C]       Compiling src/core/lib/profiling/basic_timers.c
[C]       Compiling src/core/lib/profiling/stap_timers.c
[C]       Compiling src/core/lib/support/alloc.c
[C]       Compiling src/core/lib/support/arena.c
[C]       Compiling src/core/lib/support/atm.c
[C]       Compiling src/core/lib/support/avl.c
[C]       Compiling src/core/lib/support/backoff.c
[C]       Compiling src/core/lib/support/cmdline.c
[C]       Compiling src/core/lib/support/cpu_iphone.c
[C]       Compiling src/core/lib/support/cpu_linux.c
[C]       Compiling src/core/lib/support/cpu_posix.c
[C]       Compiling src/core/lib/support/cpu_windows.c
[C]       Compiling src/core/lib/support/env_linux.c
[C]       Compiling src/core/lib/support/env_posix.c
[C]       Compiling src/core/lib/support/env_windows.c
[C]       Compiling src/core/lib/support/histogram.c
[C]       Compiling src/core/lib/support/host_port.c
[C]       Compiling src/core/lib/support/log.c
[C]       Compiling src/core/lib/support/log_android.c
[C]       Compiling src/core/lib/support/log_linux.c
[C]       Compiling src/core/lib/support/log_posix.c
[C]       Compiling src/core/lib/support/log_windows.c
[C]       Compiling src/core/lib/support/mpscq.c
[C]       Compiling src/core/lib/support/murmur_hash.c
[C]       Compiling src/core/lib/support/stack_lockfree.c
[C]       Compiling src/core/lib/support/string.c
[C]       Compiling src/core/lib/support/string_posix.c
[C]       Compiling src/core/lib/support/string_util_windows.c
[C]       Compiling src/core/lib/support/string_windows.c
[C]       Compiling src/core/lib/support/subprocess_posix.c
[C]       Compiling src/core/lib/support/subprocess_windows.c
[C]       Compiling src/core/lib/support/sync.c
[C]       Compiling src/core/lib/support/sync_posix.c
[C]       Compiling src/core/lib/support/sync_windows.c
[C]       Compiling src/core/lib/support/thd.c
[C]       Compiling src/core/lib/support/thd_posix.c
[C]       Compiling src/core/lib/support/thd_windows.c
[C]       Compiling src/core/lib/support/time.c
[C]       Compiling src/core/lib/support/time_posix.c
[C]       Compiling src/core/lib/support/time_precise.c
[C]       Compiling src/core/lib/support/time_windows.c
[C]       Compiling src/core/lib/support/tls_pthread.c
[C]       Compiling src/core/lib/support/tmpfile_msys.c
[C]       Compiling src/core/lib/support/tmpfile_posix.c
[C]       Compiling src/core/lib/support/tmpfile_windows.c
[C]       Compiling src/core/lib/support/wrap_memcpy.c
[AR]      Creating /home/fossum/grpc/libs/opt/libgpr.a
[C]       Compiling src/boringssl/err_data.c
[C]       Compiling third_party/boringssl/crypto/aes/aes.c
[C]       Compiling third_party/boringssl/crypto/aes/mode_wrappers.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_bitstr.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_bool.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_d2i_fp.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_dup.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_enum.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_gentm.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_i2d_fp.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_int.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_mbstr.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_object.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_octet.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_print.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_strnid.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_time.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_type.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_utctm.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_utf8.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn1_lib.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn1_par.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn_pack.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_enum.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_int.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_string.c
[C]       Compiling third_party/boringssl/crypto/asn1/t_bitst.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_dec.c
In file included from third_party/boringssl/crypto/asn1/tasn_dec.c:66:
third_party/boringssl/crypto/asn1/../internal.h:121:22: error: stdalign.h: No such file or directory
make: *** [/home/fossum/grpc/objs/opt/third_party/boringssl/crypto/asn1/tasn_dec.o] Error 1
-bash-4.1$ 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
We're just wanting gRPC, so if "boringssl" is unnecessary to us, is there some environment variable to let us suppress its compilation?

**Comment by austinpagan** [comment]
Oh, I did find that our system has a "stdalign.h" in /usr/lib/clang/3.4.2/include, but all our efforts to point to that directory using a "-I" directive in the Makefile were unsuccessful.

**Comment by nicolasnoble** [comment]
First, let me clarify, but BoringSSL isn't just for internal use at Google. This is an actual, public, official replacement of OpenSSL provided by Google.

That being said, its usage within gRPC is fully optional. In fact, the Makefile will not try to build and use it unless it really have to. Long story short, it means you don't have a suitable replacement for it on your system, aka, OpenSSL 1.0.2+.

If you do `make run_dep_checks`, it'll show you what commands it's running for the various detections. If it detects you have the `pkg-config` tool, it's going to try running `pkg-config --atleast-version=1.0.2`, and will happily use the results of `pkg-config` if it finds something appropriate. If you don't have the `pkg-config` tool, it'll try compiling a dummy executable that'll make use of the necessary APIs we require from OpenSSL. So, on a system that has the development libraries for OpenSSL 1.0.2+, no BoringSSL compilation takes places:

```
:~/sources/grpc (master)$ make -j 8 |& grep -i boringssl
```

If we do not detect an appropriate version of OpenSSL on the system, the Makefile will define `EMBED_OPENSSL` to true, and will build something on the fly. You can override this behavior (and most likely you will get an error later since we didn't detect an appropriate version of OpenSSL) by doing `EMBED_OPENSSL=false make`.

As for `stdalign.h`, if your gcc 4.9.4 doesn't have it, you can't just try using the one from your clang 3.4.2. That's not how standard headers work. You'd need to _use_ your clang 3.4.2 compiler from your system to get that header properly. You can override which compiler the `Makefile` uses by using the very classic `CC` and `CXX` variables.

**Comment by austinpagan** [comment]
Thank you for your quick reply, and your excellent guidance.
I'll be working on this later this evening, and will update soon...

**Comment by austinpagan** [comment]
First, let me say that my comment about "boringssl" being "Google-internal" came from what I saw in the first couple paragraphs of the third_party/boringssl/README.md file. I meant no disrespect.

The machine we are trying to use has OpenSSL at 1.0.1.

We might prefer to build 1.0.2 in a private area, and just "point to it," but that brings up three questions:

(1) from my limited viewing of the large gRPC Makefile, it appears that it won't be easy to convince the build process to find the include and lib files in someplace other than /usr/local/ssl, and since it's not "fully installed" the "pkg-config" tool won't find it anyway, so is this a fool's errand?

(2) Are you requiring version 1.0.2 because gRPC must have ALPN rather than NPN? Or is there some way to actually get gRPC to compile with OpenSSL 1.0.1?

(3) Is it possible that even if we do properly install OpenSSL 1.0.2, something about the basic system may still be stuck at "NPN" and not properly upgrade to "ALPN" so we will find more problems down this path?

**Comment by austinpagan** [comment]
I see comments in the distribution that it should be possible to build without ALPN, and I even tried
"TSI_OPENSSL_ALPN_SUPPORT=0 make" because of some comments I found, but it apparently wasn't the right "incantation" to avoid the attempt to build boringssl.

I think I'm moving towards a desire to convince gRPC to build using OpenSSL 1.0.1 and NPN, as that is what is installed on this system (RHEL 6).

Can you help me with that?

**Comment by nicolasnoble** [comment]
ALPN is the preferred way intended by the HTTP/2 spec, but we do handle a non-standard NPN fallback. In the case you have only OpenSSL 1.0.1, the Makefile should work just as well, detect that it needs to disable ALPN, and enable NPN at all times.

Now what strikes me in your (1) is the "it's not fully installed". Well, as with any other dependency system, if your package isn't properly installed, it's going to be difficult for any build system to detect and use it. But no matter; as I said, you can always override things using variables. Your usage case just became a tiny bit more complicated as your OpenSSL looks mis-installed.

Try

```
make HAS_SYSTEM_OPENSSL_ALPN=false HAS_SYSTEM_OPENSSL_NPN=true
```

**Comment by austinpagan** [comment]
Sorry I was unclear.  OpenSSL 1.0.1 is properly installed.  I was referring to a private build of OpenSSL 1.0.2 that I was *contemplating*...

**Comment by austinpagan** [comment]
I did a "make clean" and then issued the command just as you listed it above.
Sadly, it still started trying to build files within "third_party/boringssl"... and failed.

**Comment by austinpagan** [comment]
Is there some specific branch or tag of gRPC that you would recommend I extract, for this effort?

**Comment by nicolasnoble** [comment]
Yep, okay then.

I've read the logic of the Makefile again, and it's:

```
if HAS_SYSTEM_OPENSSL_ALPN
    use_system_openssl()
elseif HAS_EMBEDDED_OPENSSL_ALPN
    use_boringssl()
elseif HAS_SYSTEM_OPENSSL_NPN
    disable_alpn()
    use_system_openssl()
else
    complain()
```

So you actually need to do:

```
make HAS_SYSTEM_OPENSSL_ALPN=false HAS_SYSTEM_OPENSSL_NPN=true HAS_EMBEDDED_OPENSSL_ALPN=false
```

**Comment by nicolasnoble** [comment]
Or you can also `rm -rf third_party/boringssl` :-)

**Comment by austinpagan** [comment]
I'm now no longer visiting boringssl.  THANK YOU!

Now, I get to try to figure out whether I'm dead in the water on RHEL 6 because "-std=c++11" is an unrecognized build option...  *sigh*

**Comment by nicolasnoble** [comment]
`-std=c++11` is supported since gcc 4.8, and that's the minimum version gRPC requires, due to our C++11 usage in the source code.

**Comment by nicolasnoble** [comment]
Closing this thread as the original boringssl problem has been solved.

**Comment by nicolasnoble** [comment]
Note that the original report said the gcc used here was 4.9.4, otherwise I'd cut this thread much shorter.
