### ISSUE TITLE
tests.cloud_to_cloud:java:http2_server:max_streams flaky

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#11654]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15071/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/

[Stacktrace](https://gist.github.com/dgquintas/ad1cfdd78e8c73f78560602ef616f852)

According to [history](https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15071/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/history/) it's been flaky lately.

**Comment by ejona86** [comment]
This [still appears flaky](https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15684/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/history/).

**Comment by ejona86** [comment]
@ericgribkoff, since you probably have most familiarity with the client, could you see if anything stands out to you?

**Comment by ericgribkoff** [comment]
Dup of #10390
