### ISSUE TITLE
How to modify the build (gRPC Makefile) to use local gcc and g++ compilers?

### ISSUE THREAD

**Issue by austinpagan** [grpc/grpc#11669]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
latest gRPC, and C++
 
 
### What operating system (Linux, Windows, …) and version?
Linux, RHEL 6
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
installed gcc 4.4.7, locally built gcc 4.9.4
 
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I modified the Makefile to 
   replace "gcc" with "<full path to locally built>gcc", and
   replace "g++" with "<full path to locally built>g++".
The affected Makefile lines were 69, 70, 200, 201, 202, 203
These were the definitions for DEFAULT_CC, DEFAULT_CXX, CC_gcov, CXX_gcov, LD_gcof, LDXX_gcov, respectively.
 
### What did you expect to see?
   successful build of c++ files with "-std=c++11"
 
### What did you see instead?
[CXX]     Compiling src/core/lib/surface/lame_client.cc
cc1plus: error: unrecognized command line option "-std=c++11"
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
We also have "clang" and "clang++" installed, but those installed versions can handle "-std=c++11", so I doubt that is the problem...

**Comment by austinpagan** [comment]
Never mind...  I figured it out.  I needed to change TWO MORE makefile lines, and then it builds.

**Comment by aleafboat** [comment]
how to fix?
