### ISSUE TITLE
A clang-diagnostic warning:'int' to 'size_type'  [clang-diagnostic-sign-conversion]

### ISSUE THREAD

**Issue by xiaohaoliang** [grpc/grpc#11664]
I use clang-tidy to check my code :
`grpc-v1.4.0/include/grpc++/impl/codegen/service_type.h:109:40: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [clang-diagnostic-sign-conversion]
    server_->RequestAsyncCall(methods_[index].get(), context, stream, call_cq,`

`grpc-v1.4.0/include/grpc++/impl/codegen/service_type.h:127:40:..`  the same.

`index` is `int` ;  `methods_[?]` need  'size_type'

**Comment by sreecha** [comment]
@vjpai : Is this worth fixing? (i.e `std::vector` indexes are supposed to be `size_t` but we are using `int`)- The code will look messy with too many typecast statements :)
