### ISSUE TITLE
[BUG] generate_cc bazel rule fails when package is an empty string

### ISSUE THREAD

**Issue by zjhzyyk** [grpc/grpc#11672]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes. 

### What version of gRPC and what language are you using?
1.4.0. C++.
 
### What operating system (Linux, Windows, …) and version?
Mac, Sierra
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.10

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0

### What did you do?
https://bitbucket.org/xyyk/grpc-example
clone and bazel build :helloworld
 
### What did you expect to see?
build should succeed.
 
### What did you see instead?
ERROR: /Users/yukang/git-projects/grpc-example/BUILD:31:1: output 'rotos/helloworld.pb.h' was not created.
ERROR: /Users/yukang/git-projects/grpc-example/BUILD:31:1: output 'rotos/helloworld.pb.cc' was not created.
ERROR: /Users/yukang/git-projects/grpc-example/BUILD:31:1: not all outputs were created or valid.
ERROR: /Users/yukang/git-projects/grpc-example/BUILD:31:1: output 'rotos/helloworld.grpc.pb.h' was not created.
ERROR: /Users/yukang/git-projects/grpc-example/BUILD:31:1: output 'rotos/helloworld.grpc.pb.cc' was not created.
Target //:helloworld failed to build

It shows output as 'rotos/.....', while the output should actually be 'protos/.....' (the first letter 'p' is missing).

This is a BUG in grpc/bazel/generate_cc.bzl.

line 13: label_len = len(ctx.label.package) + 1

should actually be

```
label_len = len(ctx.label.package)
if label_len != 0:
  label_len = label_len + 1
```

grpc's example works even with the bug because BUILD file is in a subdirectory and its package is "example". When package is not empty string, it makes sense to add 1 because proto path is examples/protos/helloworld.proto. Plus 1 can remove the / after "examples".

However, this is not the case when package is an empty string. In my example, BUILD file is in topmost directory and package is an empty string. there is no leading / before output path. for example, my proto path is proto/helloworld.proto. there is no need to plus 1 in this case.

Full context: https://groups.google.com/d/msg/grpc-io/mbGvH013Bhc/Hq00jGtZAwAJ

**Comment by hsaliak** [comment]
This should be fixed -  #15625 Should also make it unnecessary to use the use_extenal= True flag, could you give the latest a try?
