### ISSUE TITLE
Does gPRC support proto3 with PHP ？

### ISSUE THREAD

**Issue by motian** [grpc/grpc#11682]
I found that on the doc [grpc_basic_php_doc](http://www.grpc.io/docs/tutorials/basic/php.html)
that was proto2.

Does gPRC support proto3 with PHP now ？

**Comment by stanley-cheung** [comment]
Yes PHP supports Proto3 now. Please see this section in the [README](https://github.com/grpc/grpc/tree/master/src/php#protobuf-compiler)

**Comment by motian** [comment]
I saw that **PHP can only create clients **, and the README demo gives a node server example also.  

I want to know if i can use php to make a gRPC server now ?
If not, will it support recently ?
