### ISSUE TITLE
disposition/* labels should have different colors

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#11689]
Having everything the same purple means that it's difficult to scan a long outstanding PR list for the current state of said PR's:

https://github.com/grpc/grpc/pulls/ctiller

**Comment by hsaliak** [comment]
I see the UX issue, while we optimized for the top level labels, issues can have multiple dispositions and we should vary the colors in such a way that they appear related and at the same time, we can start mentally associating the variations with what we need to do on the issue. I'll see what I can come up with.

**Comment by hsaliak** [comment]
Not important, closing.
