### ISSUE TITLE
Can I use PHP to create a gPRC server ?

### ISSUE THREAD

**Issue by motian** [grpc/grpc#11683]
I saw that "PHP can only create clients" in the doc, and the github readme file also gives a node server example in the PHP quickstart guide.

I want to know if the php server will be supported recently ? What's the plan ?
Thank you!

**Comment by stanley-cheung** [comment]
Currently there is no plan to support PHP as a server. Please see [this discussion](https://groups.google.com/forum/#!topic/grpc-io/F3IyYaI_6S0) over at the mailing list.
