### ISSUE TITLE
Add C++ end2end tests for SerializationTraits

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#11694]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
N/A
 
### What operating system (Linux, Windows, …) and version?

N/A 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 N/A

### What did you do?

Tried to use SerializationTraits
 
### What did you expect to see?
 
That this feature has test coverage in the C++ end2end test suites 

### What did you see instead?
 
This feature only has test coverage in C++ as a unit test, which does not provide any relevant guidance in how to use this advanced feature.

**Comment by ncteisen** [comment]
I have been touching proto_utils lately, and agree that tests are very lacking. The one we do have wasn't even written by us...

I can take this on if you want

**Comment by vjpai** [comment]
Awesome if you take this! Please feel free to self-reassign.

**Comment by ncteisen** [comment]
Fixed in #13315
