### ISSUE TITLE
Interop test protos use "deprecated" fields and types

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#11709]
[messages.proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/messages.proto#L30) has contained comments on a number of message types and fields saying `DEPRECATED, don't use. To be removed shortly.` for over a year. We should figure out a plan for removing these comments.

@dgquintas Is there already an existing plan for handling these deprecated fields? Since the interop tests are designed to be backward compatible with older versions, can we ever remove the deprecated fields outright? Already some elements of the deprecated types have diverged between C and Java/Go. For example, the deprecated `PayloadType` enum in C dropped `UNCOMPRESSABLE` and `RANDOM`, but these persist in Java and Go. I'm updating the `messages.proto` used by gRPC Java to support the compression tests, and want to have some idea what the next step is before just copying the deprecation comments over to another repo.

**Comment by dgquintas** [comment]
There's currently no plan, but one would certainly be welcome.

**Comment by ncteisen** [comment]
Closed by #15711
