### ISSUE TITLE
Failure: aggregate_tests.run_tests_python_linux_dbg_native (from grpc.aggregate_tests)

### ISSUE THREAD

**Issue by yongni** [grpc/grpc#11700]
+ docker rm -f run_tests_319c9e21-e7c0-4af7-821c-a505f44080d8
run_tests_319c9e21-e7c0-4af7-821c-a505f44080d8
+ exit 2
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1345, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 2

See log here:
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/6466/testReport/junit/(root)/aggregate_tests/run_tests_python_linux_dbg_native/

**Comment by matt-kwong** [comment]
This aggregate test failure just means that a Python test failed in the Jenkins build. #11701 covers the failing test.
