### ISSUE TITLE
stream reference bug  when request set deadline

### ISSUE THREAD

**Issue by dothan009** [grpc/grpc#11718]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpc 1.4.1, C++
 
### What operating system (Linux, Windows, …) and version?
 Linux 3.10.0-514.el7.x86_64  Centos 7.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
 
### What did you do?
async mode client send 100 request per second   to a slow server,  each request has 200K Bytes payload and with a random deadline. Then kill the client and start a new one in a infinite loop. 
 
### What did you expect to see?
 the slow server will run normally forevver.
 
### What did you see instead?
 server crashed after some time,  dead at the abort() in destroy_stream_locked(). 
Then I found this stream stay on  WRITING list。

At last I enable GRPC_STREAM_REFCOUNT_DEBUG flag, and found a call with wrong reference lifetime:
D0706 11:58:02.009947074   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 1->2 chttp2
D0706 11:58:02.009954182   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 2->3 completion
D0706 11:58:02.009967722   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 3->4 perform_stream_op
D0706 11:58:02.018805109   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 4->5 deadline_timer
D0706 11:58:02.018813661   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 5->6 completion
D0706 11:58:02.018828381   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 6->7 perform_stream_op
D0706 11:58:02.018831450   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 7->6 completion
D0706 11:58:02.018834099   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 6->5 perform_stream_op
D0706 11:58:02.026508990   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 5->6 chttp2_writing:become
D0706 11:58:02.026514328   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 6->5 perform_stream_op
D0706 11:58:02.031225352   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 5->4 chttp2_writing:no_write
D0706 11:58:02.035506587   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 4->5 chttp2_writing:become
D0706 11:58:02.035540137   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 5->4 chttp2_writing:no_write
D0706 11:58:02.093249715   22712 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 4->5 chttp2_writing:become
D0706 11:58:02.093401657   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 5->4 completion
D0706 11:58:02.098179991   22712 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 4->3 chttp2_writing:no_write
D0706 11:58:02.546656043   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 3->4 completion
D0706 11:58:02.546670976   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 4->5 perform_stream_op
D0706 11:58:02.559991679   22713 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 5->4 perform_stream_op
D0706 11:58:02.604908644   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 4->5 completion
D0706 11:58:02.604942368   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 5->6 perform_stream_op
D0706 11:58:02.604970222   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 6->7 chttp2_writing:become
D0706 11:58:02.604982711   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 7->6 perform_stream_op
D0706 11:58:02.605007364   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 6->7 chttp2_writing:fork
D0706 11:58:02.605023298   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 7->8 chttp2_writing:fork
D0706 11:58:02.605026113   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 8->7 chttp2_writing:already_writing
D0706 11:58:02.605034140   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 7->6 chttp2_writing:already_writing
D0706 11:58:02.605130484   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 6->5 chttp2_writing:end
D0706 11:58:02.605818912   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 5->6 termination
D0706 11:58:02.605868828   22711 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 6->7 perform_stream_op
D0706 11:58:02.605892267   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 7->6 chttp2
D0706 11:58:02.606462605   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 6->5 deadline_timer
D0706 11:58:02.606517303   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 5->4 completion
D0706 11:58:02.606530572   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 4->3 completion
D0706 11:58:02.606543421   22711 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 3->2 destroy
D0706 11:58:02.609995243   22710 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 2->1 termination
D0706 11:58:02.609998113   22710 transport.c:69]             CALL_STACK 0x611cb40:0x611c4d8 UNREF 1->0 perform_stream_op
D0706 11:58:02.610284257   22710 transport.c:52]             CALL_STACK 0x611cb40:0x611c4d8   REF 0->1 chttp2_writing:become

When this stream ref count become 0 （the second from last log）, the destroy_stream_locked() operation  is been scheduled. Then, this stream leave the stalled state and become writting state, inc rease the ref count by 1 (the last log). This seems weird。

So, I think there is a stream ref count bug.

**Comment by dothan009** [comment]
maybe the same with #10516

**Comment by dothan009** [comment]
Update: I found this issue still appear in version 1.6.0.

**Comment by BusyJay** [comment]
I encounter the similar issue here. A quick client send requests to a slow server, and replace the client in a while. Although I didn't set a deadline, but server will abort the call early which is similar with deadline.

**Comment by dothan009** [comment]
Update: This issue disappear in version 1.8.1. I think it was fixed.
