### ISSUE TITLE
Building grpc-1.4.0 from tarball failed

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#11724]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 grpc-1.4.0 c++
 
### What operating system (Linux, Windows, …) and version?
 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
 
### What did you do?
I encountered some grpc problems when I was using grpc-1.0.0. The previous problems are:
1. https://github.com/grpc/grpc/issues/11681
2. https://github.com/grpc/grpc/issues/11725
Since seems no one is working on 1.0.0, so I changed to using a newer version to see if the problem also exists.

I downloaded the grpc-1.4.0 tarball from https://github.com/grpc/grpc/archive/v1.4.0.tar.gz
and then:
```
cd grpc-1.4.0/;
 make
```
 
### What did you expect to see?
 The third_party/cares/cares/ directory didn't contain anything
 
### What did you see instead?
```
Package libcares was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcares.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcares' found
Package libcares was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcares.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcares' found

DEPENDENCY ERROR

You are missing system dependencies that are essential to build grpc,
and the third_party directory doesn't have them:

  cares

Installing the development packages for your system will solve
this issue. Please consult INSTALL to get more information.

If you need information about why these tests failed, run:

  make run_dep_checks

make: *** [stop] Error 1
```

**Comment by nicolasnoble** [comment]
Release tarballs from github don't contain submodules. As the error you've pasted says, you then need to provide cares yourself in your system. Please install libcares somehow, or use git to clone the repository and grab the submodules.

**Comment by yyh-graphsql** [comment]
thanks @nicolasnoble
