### ISSUE TITLE
vsock support 

### ISSUE THREAD

**Issue by jynnantonix** [grpc/grpc#11734]
[virtio-vsock](http://wiki.qemu.org/Features/VirtioVsock) is a paravirtualized socket driver that provides a zero-configuration communication channel between applications that run on the host machine and inside a guest VM.

Chrome OS is planning on using gRPC over vsock to manage VM instances and I have a local patch that adds support for vsock to gRPC.  Is this something that the gRPC developers are interested in maintaining long-term (so I should create a pull request for it) or should we just leave it as a local patch?

**Comment by kpayson64** [comment]
Our testing infrastructure isn't equipped for something like that.  It is probably best to leave it as a local patch.
