### ISSUE TITLE
Add GRPC_OLD_CXX detection.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1174]
We can't rely on GRPC_OLD_CXX being defined by the projects, since this is used in APIs. We have to compute these from the headers.

**Comment by vjpai** [comment]
I'm going to come out swinging for an autoconf-like approach: can we run some simple feature tests and see if they build and run as expected? For example, detect the presence of chrono/nullptr/thread/etc by actually testing for each feature and then using that to produce the config.h header file accordingly.

**Comment by ctiller** [comment]
We have something similar for C++11 vs C++0x currently:
https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L225

**Comment by nicolasnoble** [comment]
So I meant to close that one down :-)

We can't really do that autoconf-like, unless we want to install a system-wide header that has been generated based on that detection. I still believe such thing is an abomination - a system header that mutates per-installation that is. The approach I took on #1185 was to add this:

https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/config.h#L44

**Comment by jayantkolhe** [comment]
done
