### ISSUE TITLE
Please provide channel creation arg to disable http proxying

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc#11751]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
1.4 python
 
### What operating system (Linux, Windows, …) and version?
 
linux
 
### What did you do?

Set http_proxy +no_proxy env vars, run python code. Try to connect to grpc server running on localhost
 
### What did you expect to see?
 
Connect to server
 
### What did you see instead?
 
Connection fails because it gets proxied
 
### Anything else we should know about your project / environment?

This used to work in 1.0 before http_proxy was implemented. We need http_proxy set in our env in order for a lot of other code to correctly proxy connections to the outside world. Even if no_proxy were supported so we could connect to localhost, we still don't want to proxy all other rpcs. Can you please implement a channel creation arg that says to ignore http_proxy?

**Comment by dzbarsky** [comment]
The attached PR does not solve my problem, because no_proxy only lets you specify *.domain.com. we connect to IP/port which does not play nicely with no_proxy, so we'd still like a channel arg to explicitly disable proxy.

**Comment by dzbarsky** [comment]
Ping? This was a breaking change after 1.2 and makes it harder to use grpc client in the same application with other libraries that talk to outside world such as boto (http://boto3.readthedocs.io/en/latest/index.html)

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble, @ctiller: what are your thoughts on this?

**Comment by nicolasnoble** [comment]
Bouncing this one to @markdroth - this was mainly targeted at @ctiller, but wasn't reassigned properly when he left.

**Comment by markdroth** [comment]
Reassigning to @yashykt, who now owns the proxy mapper code.

**Comment by yashykt** [comment]
Given that we have existing ways to disable proxying, I don't see the need for this. 

(I don't see any restriction which says IP addresses cannot be added in no_proxy.)

Feel free to reopen if I'm wrong.

**Comment by dzbarsky** [comment]
@yashykt yes, no_proxy can be used with an IP address, but it cannot be used with IP ranges as far as I know. (See also https://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable). If I am wrong about this point, please show me, I'd love a solution.

Since we have a deployment of 50K+ machines, it is not feasible to specify no_proxy env variable that will whitelist them all.

I don't see a way to reopen this issue from my end, perhaps your permissions are locked down.

**Comment by mehrdada** [comment]
Reopened per reporter's request

**Comment by yashykt** [comment]
Another approach might have been to use separate processes, but it might be a good idea to have explicit channel arguments for http proxy.

**Comment by yashykt** [comment]
channel arg GRPC_ARG_ENABLE_HTTP_PROXY added for this purpose in #15699. Set it to zero to disable http proxy usage.
