### ISSUE TITLE
Remove all usage of std::chrono

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1175]
Visual Studio 2010 doesn't support it.

**Comment by soltanmm** [comment]
From what I can tell, `std::chrono` is now only unconditionally used in a handful of tests, right?

**Comment by nicolasnoble** [comment]
Yes, which is fine. The core and the C++ bindings don't anymore.

**Comment by ctiller** [comment]
Can we close this then?

**Comment by vjpai** [comment]
I suggest closing.

**Comment by jayantkolhe** [comment]
done
