### ISSUE TITLE
Resolver API not exposed in python

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc#11766]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 
1.4, python
 
### What operating system (Linux, Windows, …) and version?
 
linux
 
We would like to hook in a custom resolver like grpc-go. It looks like there is support for this in the C core by registering a global address resolver, but this isn't exposed in python bindings.

**Comment by nathanielmanistaatgoogle** [comment]
@dzbarsky: is this a duplicate of [issue 11685](https://github.com/grpc/grpc/issues/11685)?

**Comment by dzbarsky** [comment]
Yep, basically.

**Comment by nathanielmanistaatgoogle** [comment]
Closing as a duplicate of [issue 11685](https://github.com/grpc/grpc/issues/11685).
