### ISSUE TITLE
OBJC compile error:  " ld: library not found for -lBoringSSL "

### ISSUE THREAD

**Issue by zyg1982527** [grpc/grpc#11769]
### What version of gRPC and what language are you using?
 gRPC  1.4.2

### What operating system (Linux, Windows, …) and version?
 Mac OS Sierra 10.12.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Xcode  Version 8.3.3
 
### What did you do?

I download the Objc example successfully,  Install gRPC plugins and libraries successfully, install pods successfully. When I open the app project with Xcode and run the app in an iOS simulator. There's a compile error : " ld: library not found for -lBoringSSL ".  I don't know how to solve it. I am very anxious because of it

Error log:
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/BoringSSL'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/HelloWorld'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/gRPC'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/gRPC-Core'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/gRPC-ProtoRPC'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/gRPC-RxLibrary'
ld: warning: directory not found for option '-L/Users/didi/Library/Developer/Xcode/DerivedData/HelloWorld-dypfccwepcxilddenmanmcguycmb/Build/Products/Debug-iphonesimulator/nanopb'
ld: library not found for -lBoringSSL
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kpayson64** [comment]
Is this still an issue?
