### ISSUE TITLE
 An error has occurred when build under Windows

### ISSUE THREAD

**Issue by Christophernt** [grpc/grpc#11763]
Using Ninja
> md .build
> cd .build
> call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x64
> cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
 In this step,an error has occurred,like this:
Determining if the C compiler works failed with the following output:
Change Dir: C:/Users/jack/Downloads/grpc/grpc/.build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Users/jack/Downloads/ninja.exe" "cmTC_b9bf3"
ninja: error: build.ninja:30: loading 'rules.ninja': No such file or directory.

include rules.ninja

                   ^ near here

**Comment by updowndown** [comment]
same error, is there any solution?

**Comment by jtattermusch** [comment]
did you try with upstream/master?   Trying with some of the older versions might indicate if there was a recent breakage.

**Comment by updowndown** [comment]
@jtattermusch 

Thanks for reply.

I'm using the master version.

This error disappeared after reboot the computer and install MSYS2。But still exist some other error.

I will try the latest release version.

**Comment by updowndown** [comment]
change to v1.4.x branch.

1. Failed to update module boringssl-boringssl-with-bazel
Relocate it to https://github.com/google/boringssl.git

2. _WIN32_WINNT error
add 'add_definitions(-D_WIN32_WINNT=0x600)' to CMakeLists.txt at the root

3. cc1plus.exe: all warnings being treated as errors
delete '-Werror' in CMakeLists.txt of boringssl

4. E:\Github\grpc2\.build/../third_party/boringssl/crypto/bio/socket_helper.c:109:
undefined reference to `__imp_getsockopt'
change 
give up at this point

**Comment by adakoda** [comment]
Same error occurred.

**Comment by Voskrese** [comment]
CMake 3.9.0 + Ninja failed
work CMake 3.8.x 
_in my opinion the fault of non-English environment \unicode ?_

**Comment by updowndown** [comment]
@adakoda @Voskrese
This error disappeared after i install the MSYS2. You can try this. But  some other error still exist.

**Comment by adakoda** [comment]
After installed CMake 3.8.2, calling "cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release" worked fine !
But calling "cmake --build ." result was failed(Maybe protobuf build was failed).

> ninja: build stopped: subcommand failed.

Here is .ninja_log
> 106128	109836	0	third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wire_format.cc.obj	d0eda3845749e73
> 107420	110047	0	third_party/protobuf/CMakeFiles/js_embed.dir/__/src/google/protobuf/compiler/js/embed.cc.obj	12ad7d1a691cea48
> 106751	110184	0	third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wrappers.pb.cc.obj	689de36fd0154c90

**Comment by adakoda** [comment]
@Voskrese 
All problem hed been occurred by CMake 3.9.0 + Ninja on Windows 7 Japanese,
After changed that environment to CMake 3.8.2 + Ninja on Windows 7 English, 
Problem has been solved.

**Comment by Voskrese** [comment]
@adakoda local consol
`chcp `
`chcp 65001`
`ninja.exe`
build CMake 3.9.0 ok

**Comment by jtattermusch** [comment]
Are there still any issues that need to be addressed or is it fine to close this issue?

**Comment by HaochengLIU** [comment]
It's a CMake bug that it does not encoding MSVC_SHOWINCLUDES_PREFIX properly on a non-english Windows. There is already a CMake [issue](https://gitlab.kitware.com/cmake/cmake/issues/17191) and a fix would come up soon. If you have a cmake build adding` ENCODING AUTO` after `RESULT_VARIABLE res` at [Modules/CMakeDetermineCompilerId.cmake#L712](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CMakeDetermineCompilerId.cmake#L712) would also solve the problem.
