### ISSUE TITLE
metadata plugin should support cancellation

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#11783]
As part of #11733, I am adding support for cancellation for asynchronous calls to `grpc_call_credentials_get_request_metadata()`.  However, if the credentials are plugin credentials, then there is no mechanism to cancel the open request.  For now, my code will handle this by immediately returning an error to the callback and then ensuring that when the plugin returns a result, it knows that the request has been cancelled and will not invoke the callback.  However, it would be much cleaner to be able to tell the plugin to cancel the request, so that we don't have to wait an arbitrarily long time to get the result back.  (This may be a particular problem at shutdown time.)

**Comment by markdroth** [comment]
My comment above was specifically referring to the plugin credentials implementation, defined here:

https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/plugin/plugin_credentials.h

Note that we have the same problem on the server side with the `grpc_auth_metadata_processor` API, which is defined here:

https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L356

Both of these APIs should be extended to support cancellation.

**Comment by markdroth** [comment]
We still need to take care of this at some point.

**Comment by rockspore** [comment]
The API referred to is gone. It's not refactored into returning an `ArenaPromise`.
