### ISSUE TITLE
"make shared_cxx" on MacOS 10.9 fails with undefined symbols

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1179]
$ make shared_cxx  (make grpc_csharp_ext fails with similar error).

[LD]      Linking libs/opt/libgrpc++.dylib
Undefined symbols for architecture x86_64:
  "_ASN1_STRING_to_UTF8", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_BIO_ctrl_pending", referenced from:
      l015 in libgrpc.a(ssl_transport_security.o)
      l016 in libgrpc.a(ssl_transport_security.o)
      l021 in libgrpc.a(ssl_transport_security.o)
      l022 in libgrpc.a(ssl_transport_security.o)
  "_BIO_free", referenced from:
      _grpc_auth_json_key_create_from_string in libgrpc.a(json_token.o)
      l002 in libgrpc.a(ssl_transport_security.o)
      l003 in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
      l013 in libgrpc.a(ssl_transport_security.o)
  "_BIO_new", referenced from:
      _grpc_auth_json_key_create_from_string in libgrpc.a(json_token.o)
      l013 in libgrpc.a(ssl_transport_security.o)
  "_BIO_new_mem_buf", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
      l003 in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_BIO_puts", referenced from:
      _grpc_auth_json_key_create_from_string in libgrpc.a(json_token.o)
  "_BIO_read", referenced from:
      l015 in libgrpc.a(ssl_transport_security.o)
      l021 in libgrpc.a(ssl_transport_security.o)
      l022 in libgrpc.a(ssl_transport_security.o)
  "_BIO_s_mem", referenced from:
      _grpc_auth_json_key_create_from_string in libgrpc.a(json_token.o)
      l013 in libgrpc.a(ssl_transport_security.o)
  "_BIO_test_flags", referenced from:
      l015 in libgrpc.a(ssl_transport_security.o)
  "_BIO_write", referenced from:
      l016 in libgrpc.a(ssl_transport_security.o)
      l023 in libgrpc.a(ssl_transport_security.o)
  "_CRYPTO_free", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_CRYPTO_num_locks", referenced from:
      l001 in libgrpc.a(ssl_transport_security.o)
  "_CRYPTO_set_id_callback", referenced from:
      l001 in libgrpc.a(ssl_transport_security.o)
  "_CRYPTO_set_locking_callback", referenced from:
      l001 in libgrpc.a(ssl_transport_security.o)
  "_EC_KEY_free", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_EC_KEY_new_by_curve_name", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_ERR_clear_error", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
      l003 in libgrpc.a(ssl_transport_security.o)
  "_ERR_error_string_n", referenced from:
      l016 in libgrpc.a(ssl_transport_security.o)
      l025 in libgrpc.a(ssl_transport_security.o)
  "_ERR_get_error", referenced from:
      l016 in libgrpc.a(ssl_transport_security.o)
      l025 in libgrpc.a(ssl_transport_security.o)
  "_EVP_DigestSignFinal", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_DigestSignInit", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_DigestUpdate", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_MD_CTX_create", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_MD_CTX_destroy", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_PKEY_free", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
      l002 in libgrpc.a(ssl_transport_security.o)
  "_EVP_PKEY_new", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_PKEY_set1_RSA", referenced from:
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_EVP_sha256", referenced from:
      _openssl_digest_from_algorithm in libgrpc.a(json_token.o)
      _compute_and_encode_signature in libgrpc.a(json_token.o)
  "_GENERAL_NAME_free", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      l001 in libgrpc.a(ssl_transport_security.o)
  "_PEM_read_bio_PrivateKey", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_PEM_read_bio_RSAPrivateKey", referenced from:
      _grpc_auth_json_key_create_from_string in libgrpc.a(json_token.o)
  "_PEM_read_bio_X509", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_PEM_read_bio_X509_AUX", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
      l003 in libgrpc.a(ssl_transport_security.o)
  "_RSA_free", referenced from:
      _grpc_auth_json_key_create_from_string in libgrpc.a(json_token.o)
      _grpc_auth_json_key_destruct in libgrpc.a(json_token.o)
  "_SSL_CTX_callback_ctrl", referenced from:
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_check_private_key", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_ctrl", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_free", referenced from:
      _tsi_create_ssl_client_handshaker_factory in libgrpc.a(ssl_transport_security.o)
      l006 in libgrpc.a(ssl_transport_security.o)
      l008 in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_get_cert_store", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_new", referenced from:
      _tsi_create_ssl_client_handshaker_factory in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_set_alpn_protos", referenced from:
      _tsi_create_ssl_client_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_set_alpn_select_cb", referenced from:
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_set_cipher_list", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_set_client_CA_list", referenced from:
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_set_verify", referenced from:
      _tsi_create_ssl_client_handshaker_factory in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_use_PrivateKey", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_SSL_CTX_use_certificate", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
  "_SSL_ctrl", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
  "_SSL_do_handshake", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
      l016 in libgrpc.a(ssl_transport_security.o)
  "_SSL_free", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
      l020 in libgrpc.a(ssl_transport_security.o)
      l024 in libgrpc.a(ssl_transport_security.o)
  "_SSL_get0_alpn_selected", referenced from:
      l018 in libgrpc.a(ssl_transport_security.o)
  "_SSL_get_error", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
      l016 in libgrpc.a(ssl_transport_security.o)
      l021 in libgrpc.a(ssl_transport_security.o)
      l022 in libgrpc.a(ssl_transport_security.o)
      l025 in libgrpc.a(ssl_transport_security.o)
  "_SSL_get_peer_certificate", referenced from:
      l018 in libgrpc.a(ssl_transport_security.o)
  "_SSL_get_servername", referenced from:
      l009 in libgrpc.a(ssl_transport_security.o)
  "_SSL_library_init", referenced from:
      l001 in libgrpc.a(ssl_transport_security.o)
  "_SSL_load_error_strings", referenced from:
      l001 in libgrpc.a(ssl_transport_security.o)
  "_SSL_new", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
  "_SSL_read", referenced from:
      l025 in libgrpc.a(ssl_transport_security.o)
  "_SSL_set_SSL_CTX", referenced from:
      l009 in libgrpc.a(ssl_transport_security.o)
  "_SSL_set_accept_state", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
  "_SSL_set_bio", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
  "_SSL_set_connect_state", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
  "_SSL_set_info_callback", referenced from:
      l013 in libgrpc.a(ssl_transport_security.o)
  "_SSL_state", referenced from:
      l017 in libgrpc.a(ssl_transport_security.o)
  "_SSL_state_string", referenced from:
      l014 in libgrpc.a(ssl_transport_security.o)
  "_SSL_state_string_long", referenced from:
      l014 in libgrpc.a(ssl_transport_security.o)
  "_SSL_write", referenced from:
      l021 in libgrpc.a(ssl_transport_security.o)
      l022 in libgrpc.a(ssl_transport_security.o)
  "_TLSv1_2_method", referenced from:
      _tsi_create_ssl_client_handshaker_factory in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
  "_X509_NAME_ENTRY_get_data", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_X509_NAME_dup", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
  "_X509_NAME_free", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
  "_X509_NAME_get_entry", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_X509_NAME_get_index_by_NID", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_X509_STORE_add_cert", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
  "_X509_free", referenced from:
      l002 in libgrpc.a(ssl_transport_security.o)
      l003 in libgrpc.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgrpc.a(ssl_transport_security.o)
      l018 in libgrpc.a(ssl_transport_security.o)
  "_X509_get_ext_d2i", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_X509_get_subject_name", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
      l012 in libgrpc.a(ssl_transport_security.o)
  "_sk_new_null", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
  "_sk_num", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
  "_sk_pop_free", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
      l012 in libgrpc.a(ssl_transport_security.o)
  "_sk_push", referenced from:
      l003 in libgrpc.a(ssl_transport_security.o)
  "_sk_value", referenced from:
      l012 in libgrpc.a(ssl_transport_security.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/opt/libgrpc++.dylib] Error 1

**Comment by soltanmm** [comment]
I don't see this error, rather I get a build error (which I've addressed in #1385). With that PR, `make shared_cxx` executes fine on my MacBook.
