### ISSUE TITLE
Python grpc client causes segfault at interpreter shutdown

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc#11804]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 
1.4 python
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 python 2.7

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
Close a client

### What did you expect to see?
 
Nothing 

### What did you see instead?
 
Exception TypeError: "'NoneType' object is not callable" in <bound method Channel.__del__ of <grpc._channel.Channel object at 0x7fca3c416050>>
and then segfault

**Comment by nathanielmanistaatgoogle** [comment]
Are you able to share with us sample code that demonstrates the problem?

**Comment by dctrwatson** [comment]
Example backtrace from a coredump:
```
#0  new_threadstate (interp=0x0, init=1) at Python/pystate.c:202
#1  0x00007feef8328d7c in PyGILState_Ensure () at Python/pystate.c:600
#2  0x00007feef005ff18 in __pyx_pw_4grpc_7_cython_6cygrpc_15CompletionQueue_3poll () from grpc/_cython/cygrpc.so
```

**Comment by nathanielmanistaatgoogle** [comment]
@dctrwatson: are you able to share with us the code that, when run, causes that backtrace to be produced?

**Comment by dzbarsky** [comment]
@nathanielmanistaatgoogle watson and I haven't been able to get a repro that doesn't involve Dropbox code, I suspect the issue may be that we are actually calling `del` on channel. It seems like somewhere in https://github.com/grpc/grpc/blob/9a69478498232b6b42169f8a1a389b51fb4e03ec/src/python/grpcio/grpc/_channel.py#L964 or lower in the stack you may want to guard against multiple calls (Python does not guarantee __del__ is only called once)

**Comment by dzbarsky** [comment]
Sorry, I misspoke earlier, this is still a segfault.

**Comment by dzbarsky** [comment]
We suspect that this may be due to completion queue polling while connection is partially destroyed.

**Comment by mehrdada** [comment]
Running the problematic binary under `GRPC_TRACE=api GRPC_VERBOSITY=DEBUG`  environment might help you figure out the sequence of calls to gRPC C Core and that help with coming up with a reduced reproduction test case.

**Comment by nathanielmanistaatgoogle** [comment]
I think we now believe that the right solution to this is going to be [implementing explicit object life cycles](https://github.com/grpc/grpc/issues/12531) (we think we can do it without significantly degrading the developer experience).

**Comment by mehrdada** [comment]
For the record, I think this old bug might be related to this issue https://github.com/grpc/grpc/issues/10084

**Comment by dzbarsky** [comment]
Not convinced it's the same as https://github.com/grpc/grpc/issues/10084 - we see this with python client talking to go server over a secure connection...

**Comment by mehrdada** [comment]
@dzbarsky I don't believe the symptom is exactly identical either, but I think the root cause of both might be overreliance of GC to free non-memory resources instead of expecting an explicit close command from user code.

**Comment by dzbarsky** [comment]
That's a very generic problem, but sure, we'd love an explicit Close method.

**Comment by nathanielmanistaatgoogle** [comment]
@dctrwatson: was it you with whom we spoke during the community meeting today? Does @alexbarcelo's [workaround of explicitly deleting the channel (and everything that holds a reference to the channel, which in practice means at least the stub too)](https://github.com/grpc/grpc/issues/11804#issuecomment-331202631) resolve this for you too? Deterministically, or is there still some fuzz (like if you keep a reference to the `response_iterator` of a live RPC - of course the deletion of the channel causes the RPC to be canceled, but does merely holding the `response_iterator` object trigger the segfault?)?

**Comment by dzbarsky** [comment]
@nathanielmanistaatgoogle No, that was me. We ended up implementing refcounting on top of grpc channel to prevent it from getting deleted while there are in-flight RPCs. It's not really practical to `del` every channel because a multi-million line of code application has channels open to lots of different services. Also there's no reason to delete the stub (we wrote custom stubs that don't hold any reference to the channel). It's pretty hard to tell if anything we try helps with the segfault since the probability seems pretty low (think 1 in a million), but at our scale we see it happen very frequently.

I saw some PRs go by that changed the shutdown ordering (sounded like internal google teams were also hitting issues), it's possible those would help or that the ordering needs further tweaks. The ideal scenario from our point of view would be for the refcounting to happen at your layer and when we call Close that just derefs the original ref. Or don't try to clean up so hard during interpreter shutdown :)

**Comment by kpayson64** [comment]
@dzbarsky 
The error is really bizarre, if I had to guess, the _moot() function is getting destroyed as part of Python's cleanup (and set to None).

Would it be possible to try the following patch and see what the output is?
https://github.com/grpc/grpc/commit/238e36c8b5a6376e17bb8dc90b4b7b2ce63eb26e

**Comment by dzbarsky** [comment]
@kpayson64 Nope, we see the same problem with the patch. At this point the cleanest way forward would be to provide an explicit `Close` api on the channel as suggested previously in this issue. Is there an ETA for this?

**Comment by nathanielmanistaatgoogle** [comment]
@dzbarsky: the ETA for [issue 12531](https://github.com/grpc/grpc/issues/12531) is "days". Probably between seven and fourteen of them?

**Comment by nathanielmanistaatgoogle** [comment]
Something slightly head-desky that occurred to me today in the course of working on [issue 12531](https://github.com/grpc/grpc/issues/12531) is that in the current implementation `grpc.ChannelCredentials` and `grpc.CallCredentials` instances maintain references to gRPC Core structures throughout their entire lifetimes (and that means that they do a `grpc_init` when they are instantiated and a `grpc_shutdown` when (or _if_) they are garbage collected).

@dzbarsky and others affected by this issue: take a look at your code and see if you're assigning any `grpc.ChannelCredentials` or `grpc.CallCredentials` instances to any "forever" fields (like module-scope constants or global variables or whatnot). That _could_ be a source of interpreter-shutdown-time shenanigans like what's going on in this issue and would (or at least could) affect code that otherwise responsibly shuts down use of and deletes all instances of all other kinds of gRPC Python code elements (specifically `grpc.Channel` instances).

(Or maybe I'm wrong and this is just me sending y'all on a goose chase, in which case: sorry!)

**Comment by dzbarsky** [comment]
@nathanielmanistaatgoogle ok, it would be great if you could get it in before 1.8 (or backport soon after).

@kpayson64 By the way, I think you're right that the moot function is getting destroyed, that should probably be fixed anyway if this code remains. Interpreter removes vars with _ prefix first. See https://docs.python.org/2/reference/datamodel.html#object.__del__

**Comment by alexmv** [comment]
Any progress on this?  We're getting bitten by this more frequently of late -- certainly more than the 1 in a million estimate above.

Thanks!

**Comment by nathanielmanistaatgoogle** [comment]
@alexmv: progress is happening incrementally and steadily in [issue 12531](https://github.com/grpc/grpc/issues/12531) and we believe that solving [issue 12531](https://github.com/grpc/grpc/issues/12531) will also solve this issue. Look for the solution to land in 1.9.0? Possibly in 1.8.x.

**Comment by alexmv** [comment]
Thanks for the update!  I'll follow along there.

**Comment by aamitdb** [comment]
The specific segfaults we hit ended up being a python issue. When a daemon thread wakes up while main thread is past _PyGILState_Fini and tries to reaccquire the gil (what the completion queue threads do), it was possible to segfault because `autoInterpreterState` was NULL. This issue exists in the 2.7 branch with the general daemon thread shutdown patch (from https://bugs.python.org/issue1856) backported, not tested in 3.x.

**Comment by meawoppl** [comment]
Certainly related to https://github.com/grpc/grpc/issues/12531.  This is the biggest source of flakes in our CI at the moment.

**Comment by kpayson64** [comment]
A ```close()``` API has been included in the 1.12 release.

Feel free to re-open if this doesn't meet the needs of this issue.

**Comment by ericgribkoff** [comment]
@lidizheng @gnossen https://github.com/grpc/grpc/pull/17621 was my ill-fated attempt to fix this. Basically daemon threads that have released the GIL (in our code, polling the completion queue) are prone to segfault when the interpreter is shutting down. There's a much longer discussion on the PR itself, but in short the segfault occurs in CPython, not in our code, so the only reasonable fix seems to be not using daemon threads - which means that applications attempting to exit without shutting down their clients/servers would be unable to exit (as opposed to the current behavior of segfaulting).

**Comment by lidizheng** [comment]
We haven't observe this issue for a while. Lower the priority for now.
