### ISSUE TITLE
Leaking of gRPC threadpool threads can lead to deadlock

### ISSUE THREAD

**Issue by benwulfe** [grpc/grpc#11824]
Please answer these questions before submitting your issue. 
 
C#

GRPC 1.4
Windows.
.Net Framework 4.52
  
 
### What did you do?
deadlock C# grpc

sample code:

   using(new SomeObjectWithDispose() ) {
      await someGRPCMethod().ConfigureAwait(false);
   }

  class SomeObjectWithDispose : IDisposable {
   public void Dispose() {
      someOtherGrpcMethod().Wait();
   }
  }
  
This code deadlocks because the synchronous call to grpc within Dispose locks a grpc threadpool thread.  This thread might be used by someOtherGrpcMethod resuling in a deadlock.

Unfortunately, there are some cases in the .net framework where Dispose and synchronous code are unavoidable (eg TransactionScope.Dispose).  In fact its very likely for developers to have some small nonzero fraction of code that must be synchronous and could pose a deadlock risk.
 
### What did you expect to see?
 
All grpc threadpool threads should never be exposed to end developers.
This ensures they are always available for scheduling internally.  Developers should be running their tasks on threadpool thread.

To enforce that a Task continuation is never executed on a grpc thread (via inlining), I suggest you install a default synchronizationcontext to every grpc thread as in:

GrpcThreadStart() {
 . . .
  SynchronizationContext.SetSynchronizationContext ( new SynchronizationContext() );
. . .

This prevents inlining by the Task infrastructure so it will instead switch to a threadpool thread in the above case and grpc threads will never be exposed.

Setting SynchronizationContext in this way should have no effect on any code.  If you wanted to be thorough, you would create a derived version that implemented Post/Send properly (routing through your grpc event queue).

 ### What did you see instead?
 
a deadlock.
 
### Anything else we should know about your project / environment?

This is for the spanner ado.net library and its not possible to make ado.net completely async I'm afraid.
msg me at benwu@google.com

**Comment by jtattermusch** [comment]
update: I've been experimenting with adding `SynchronizationContext.SetSynchronizationContext ( new SynchronizationContext() );`, but it appears that it is not helping, the server-side handlers are still running on gRPC threadpool threads as before. The problem is likely in the TaskCompletionSource which is used internally (and it seems to always schedule continuations on the current thread). I will continue investigating.
