### ISSUE TITLE
Max message size not exposed for Python server

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc#11839]
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 
1.4 python
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
python 2.7
 
### What did you do?

Looked for server flag to enable bigger messages
 
### What did you expect to see?
 
Find the flag
 
### What did you see instead?
 
Doesn't exist.

**Comment by nathanielmanistaatgoogle** [comment]
How deeply have you looked into the `options` parameter of `grpc.server`? The capability isn't formally supported as a first-class API element, but it is there (for now).
