### ISSUE TITLE
Grpc c++ asynchronous call error

### ISSUE THREAD

**Issue by Christophernt** [grpc/grpc#11845]
### What version of gRPC and what language are you using?
 gRPC 1.4.2 c++
 
### What operating system (Linux, Windows, …) and version?
 Windows 7 sp1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 visual studio 2015 update3
 
### What did you do?
ClientContext context;
void* got_tag = (void*) 1;
bool ok = false;
CompletionQueue cq_;
Status status;
std::shared_ptr<ClientAsyncReaderWriter<SessionRequest, SessionNotify>> stream(
		stub_->AsyncSendSessionRequest(&context, &cq_, got_tag));
stream->Write(request, got_tag);
 
### What did you see instead?
when debug, include\grpc++\impl\call.h at line 671, like:call_hook_->PerformOpsOnCall(ops, this);
It throws exception:E0717 17:23:45.284000000 93172 channel_cc.cc:123] assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), sops, nops, ops, nullptr)
 
### Anything else we should know about your project / environment?
 SessionRequest and SessionNotify are user-defined classes

**Comment by mroland91** [comment]
Hi,

Is there any update on this issue?

I am trying to communicate with etcd on it's official grpc intergace.
etcd's AsyncWatch rpc is failing with the same error as above.

grpc v1.6.1
protobuf 3.4.0
etcd 3.2.7

Thanks,
Best Regards,
Roland

**Comment by yang-g** [comment]
When you start a stream, that is creating the reader/write object with a tag, you need to use CompletionQueue::Next to wait for the tag to come back before you can call Write.
