### ISSUE TITLE
C#: build system does not provide any error message

### ISSUE THREAD

**Issue by pongad** [grpc/grpc#11840]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 C#. I see this in both master and 1.4.x branches.
 
### What operating system (Linux, Windows, …) and version?
 Linux, Ubuntu Trusty
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 dotnet-dev-1.0.4
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

- Check out source
- Run `python tools/run_tests/run_tests.py -c dbg -l csharp --build_only`.
  - This succeeds as expected.
- Go to `grpc/src/csharp/Grpc.IntegrationTesting/BenchmarkServiceImpl.cs`
- Delete one semicolon, creating syntax error.
- Run `python tools/run_tests/run_tests.py -c dbg -l csharp --build_only` again 
 
### What did you expect to see?
 The build fails saying I'm missing the semicolon
 
### What did you see instead?
The build hangs forever producing no output. The output just shows
```
File "tools/run_tests/run_tests.py", line 1597, in <module>
    build_only=args.build_only)
  File "tools/run_tests/run_tests.py", line 1484, in _build_and_run
    newline_on_success=newline_on_success, travis=args.travis)
  File "grpc/tools/run_tests/python_utils/jobset.py", line 525, in run
    if not js.start(cmdline):
  File "grpc/tools/run_tests/python_utils/jobset.py", line 413, in start
    self.reap()
  File "grpc/tools/run_tests/python_utils/jobset.py", line 462, in reap
    signal.pause()
KeyboardInterrupt

```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jtattermusch** [comment]
I've seen the build getting stuck when building using `run_tests.py`  or `src/csharp$ dotnet build Grpc.sln` before. As far as I can tell, the there is a bug in dotnet SDK that sometimes makes the `dotnet build` command get stuck when there's a compilation error. Do you have some evidence that indicates that the actual issue is with gRPC codebase?

**Comment by pongad** [comment]
Oh yikes! I honestly have never seen a compiler getting stuck on a syntax error like this before. So, I assumed the problem must be in gRPC. If you think this is caused by dotnet itself, please feel free to close the issue.
