### ISSUE TITLE
Add more CHANGELOG for Ruby gRPC

### ISSUE THREAD

**Issue by tzwm** [grpc/grpc#11842]
Please add more CHANGELOG for Ruby gRPC. So we can upgrade it more comfortable.

**Comment by apolcyn** [comment]
changes like feature additions and bug fixes normally have gone into the release notes, https://github.com/grpc/grpc/releases. Is this issue about adding more detailed change notes than what is in those release notes?

**Comment by tzwm** [comment]
Thanks for your information. I didn't notice that there are release notes before.
