### ISSUE TITLE
Memory usage of the server increases when running the greeter_server.py example

### ISSUE THREAD

**Issue by atesop** [grpc/grpc#11887]
Hi all,
I am new to grpc. Then I just runned the demo of helloword server, the resident memory usage of server growed and growed. 
I tested it on Linux, installed grpc by pip, `grpcio==1.4.0, grpcio-tools==1.4.0`, both python 2.7.12 and 3.6.1.

I just add one line in [greeter_client.py](https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_client.py), then the codes just like below:
```python
def run():
  channel = grpc.insecure_channel('localhost:50051')
  stub = helloworld_pb2_grpc.GreeterStub(channel)
  for i in range(100000):
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
    print("Greeter client received: " + response.message)
```

the `ps aux` result:

![20170720203115](https://user-images.githubusercontent.com/6399856/28417768-e8171cd4-6d8b-11e7-9cf1-817c33641f63.png)

I would appreciate any further information on this, thanks.

**Comment by atesop** [comment]
@djanku Would you like to tell me what tool you used to detect the memory leak? Thanks.

**Comment by djanku** [comment]
Hello, 
I’ve used “valgrind" (on Linux) and “leaks” on macOS. But we are using GRPC at production with very heavy traffic so we can recognize memory consumption very well :)

**Comment by egoldschmidt** [comment]
FYI we have been seeing the same memory leak. After applying #12249 I can confirm the issue is resolved 👍

**Comment by atesop** [comment]
@djanku Thanks for your brilliant work.

**Comment by yancl** [comment]
yes, we also saw grpc server(grpcio:1.4.X and python:2.7.X) memory leaks on our production env:(

**Comment by atesop** [comment]
Hi @yancl， as the comment of @egoldschmidt above,  #12249 can resolve the issue.

**Comment by yancl** [comment]
@atesop  thank you for your information, we will patch it.  Current we just add a oomkiller to graceful restart the grpc server when it occupy too much memory:)

**Comment by nathanielmanistaatgoogle** [comment]
@atesop: thank you for the report. Since patching in [pull request 12249](https://github.com/grpc/grpc/pull/12249) solved this for you, I expect that [pull request 12466](https://github.com/grpc/grpc/pull/12466) will also solve it for you - please confirm that that is the case?

**Comment by atesop** [comment]
@nathanielmanistaatgoogle Thank you. That works for me.
