### ISSUE TITLE
ASAN leak report: bins/asan/h2_http_proxy_nosec_test resource_quota_server GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#11918]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
master

### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
ASAN
 
### What did you do?

Ran listed test as a result of a pull request that is not related to the test in question.
 
### What did you expect to see?
 
 No leaks

### What did you see instead?
 
Interestingly, the leak reported only consists of indirect leaks. I believe that this means that a linked data structure (like a doubly-linked list) has nodes that are leaking.

https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/6143/

**Comment by vjpai** [comment]
Note that this is not exactly the same as #11055 but looks similar enough that it might be the same root cause

**Comment by markdroth** [comment]
I'm fairly sure this is a duplicate of #11055.
