### ISSUE TITLE
Performance dashboard broken: Error uploading to bigquery

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11919]
data for all languages missing since Jul 18.

http://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/4255/#showFailuresLink

```
+ tools/run_tests/performance/bq_upload_result.py --bq_result_table=performance_test.performance_experiment
Warning: Table performance_experiment already exists
Error inserting rows! Response: {u'kind': u'bigquery#tableDataInsertAllResponse', u'insertErrors': [{u'index': 0, u'errors': [{u'debugInfo': u'generic::not_found: no such field.', u'reason': u'invalid', u'message': u'no such field.', u'location': u'summary.serverqueriespercpusec'}]}]}
```

**Comment by jtattermusch** [comment]
Likely offender: https://github.com/grpc/grpc/pull/11787/files

https://github.com/grpc/grpc/pull/11787/files#diff-f0e14782117870a2fc9c6e2292eee4deR246

**Comment by jtattermusch** [comment]
The bigquery schema can be updated by `updating scenario_result_schema.json`  and using the script added here: https://github.com/grpc/grpc/pull/11615 (which was used to fix a similar issue https://github.com/grpc/grpc/issues/11613)

**Comment by guantaol** [comment]
PR #11926 is merged to update scenario_result_schema.json. Also, I have manually run the script in #11615 to update the bigquery schema.
