### ISSUE TITLE
Ephemeral Server Ports

### ISSUE THREAD

**Issue by llchan** [grpc/grpc#11920]
### Should this be an issue in the gRPC issue tracker?
I believe so. Most likely this is unintended, and a new code path needs to be added to address it. If this is expected behavior, it seems fairly unintuitive, so it'd be helpful to either update documentation or provide a way to achieve this.

### What version of gRPC and what language are you using?
grpc-1.4.2 using c++ interface
 
### What operating system (Linux, Windows, …) and version?
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-4.8.5
 
### What did you do?
I set the port to 0 to have the system choose a free port.
``` c++
int port = 0;
server_builder.AddListeningPort("0.0.0.0:0", grpc::InsecureServerCredentials(), &port);
```

### What did you expect to see?
Single listening port in `lsof` output
 
### What did you see instead?
Dozens of distinct listening ports in `lsof` output
 
### Anything else we should know about your project / environment?
No

**Comment by dgquintas** [comment]
Do the ports you see in `lsof` all correspond to the server process?

**Comment by llchan** [comment]
Yes, I'm checking with `lsof -nP -p $PID`. It seems that each poller binds with the supplied address (with port=0) independently, rather than having one poller bind first and use that port for the remaining pollers.

**Comment by dgquintas** [comment]
CC @sreecha

**Comment by sreecha** [comment]
@llchan - I apologize for dropping the ball on this issue.
Are you still seeing this or is it no longer happening ?

**Comment by llchan** [comment]
I can reproduce the bad behavior with grpc-1.4.2, but it is no longer an issue in grpc-1.11.0 :tada:. No need to bisect unless you want to, feel free to close.

**Comment by sreecha** [comment]
Thank you @llchan for responding very quickly! . I will close the issue (there has been enough code churn since 1.4 that its probably not worth digging deeper)
