### ISSUE TITLE
CMAKE instructions for C++ are not exactly correct

### ISSUE THREAD

**Issue by Zeks** [grpc/grpc#11949]
I've tried building the latest version of grpc/c++ on Windows 7 via CMAKE and run into quite a number of issues. I tried pinging people on freenode:grpc but no one said anything to indicate I've been heard.

I've been following the CMAKE section of this guide:
https://github.com/grpc/grpc/blob/master/INSTALL.md
 
Toolset: 
Windows 7
grpc 1.4.2 from repo, 
Cmake 3.9.1, 
MSVC 2015, 
all dependencies from the guide installed
commands run from shell in conemu2

The issues I've run into:
1) c-ares isnt pulled into repo with other submodules when fetching code from repo with submodule-update. Had to copy files manually.
2) cmake on windows by default treats all warnings as errors and there have been a lot of those. therefore nothing was built and resolving this is not explained in the manual in any way
3) Manual doesnt mention anything about switching between MT_D, MD and MDd. Ideally, the build should generate all of those instead of just one.

Not everyone is familiar with the topics above. For example I come from qtcreator/msvc compiler toolkit and just wanted to create a library I could use. In the end it took me more than 2 hours of googling to resolve all of the above. Not exactly a smooth installation process.

**Comment by Zeks** [comment]
Just to help other people:
1. warnings as errors is solved by removing -Wall and -Werror in generated cmakelists.txt files where they are present
2. the way to switch between MT_D, MD and MDd is to generate the project via cmake gui instead of from command line. in it, you can specify the type of the library to be built.

**Comment by jtattermusch** [comment]
Ad 1: "c-ares isnt pulled into repo with other submodules when fetching code from repo with submodule-update. Had to copy files manually.". It looks like `git submodule update --init` works just fine for me. I certainly didn't ever copy any c-ares files manually to be able to build gRPC on windows. What exactly doesn't work?

Ad 2: (warnings)  CMakeLists.txt disables all necessary warnings to be able to build on windows and we have a continous test running to make sure gRPC builds on windows with cmake. Not sure why you are seeing issues.
https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L134

**Comment by jtattermusch** [comment]
@Zeks  do you want to react to my comments?

**Comment by Zeks** [comment]
I am not sure what I can add. We are seeing two differing behaviours despite me following instructions from github letter by letter.  Maybe some obvious step is omitted that I dont follow because I don't usually use cmake for anything.

Also, if there is anything the build definitely needs it's that "build MTd, MDd" at the same time.

**Comment by jtattermusch** [comment]
I recently tried improving the windows build instructions, hopefully it helps.
https://github.com/grpc/grpc/pull/13548

Beyond that, I think there might be some improvements needed to our actual CMake build (not just the docs). We might be able to address some of the problems in Q1 2018.

**Comment by Zeks** [comment]
I can confirm that the currrent build script for ninja is working on Win10, none of the errors above are present. Either they have fixed that or it was a Win7 thing.
