### ISSUE TITLE
Building grpc-python exits with "library not found for -lrt"

### ISSUE THREAD

**Issue by kaikuehne** [grpc/grpc#1195]
Hi,
I installed grpc [as described here](https://github.com/grpc/grpc/blob/master/INSTALL) and tried to build the python bindings using "pip install src/python/src".

The build fails with:

```
...

ld: library not found for -lrt

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'clang' failed with exit status 1
```

I am on the mac. Can you tell me what I am missing?
I will gladly provide more information if you tell me what you need.

Thanks!

**Comment by nicolasnoble** [comment]
librt doesn't exists under MacOS - nor under certain versions of Linux in fact. This is a bug that needs fixing.

As a note, sometimes librt contains real time clock functions that are needed to compile grpc.

**Comment by soltanmm** [comment]
I believe this has been fixed. Thanks, @atombender! :+1:
