### ISSUE TITLE
grpc c++:  can one channel-writer be used for multiple sending

### ISSUE THREAD

**Issue by Qian-Zhang7** [grpc/grpc#11960]
We have a client-server project, where client (C++) needs to send data to server every a few seconds. I've created one grpc class for client side, opened One channel.  I hope to achieve:

1) do paging, without close/open stream every time
My message often is very large, with 60000 records, I'm thinking to chunk them to small sizes, can I use the same writer to do multiple Write:  and no need to close and reopen the stream for every chunk?  If I calling WritesDone() and Finish() after one chunk, my understanding is: the stream will be closed. That defeats chunking purpose.  

I should be able to keep the stream open: write, write, write....multiple times, then finish

2) keep the channel open forever:
Since the client is sending data as long as it is alive, to the same server/port. is there a way to keep the channel/stream open for sending, for as long as the client process is alive, maybe for a few days/months...

### What version of gRPC and what language are you using?
1.4 
 
### What operating system (Linux, Windows, …) and version?
 centos-7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc, g++

**Comment by yang-g** [comment]
1. It is ok to use the same stream/writer to write multiple message sequentially. And it is preferable for your use case.
2. You can keep the channel alive and keep the stream alive for sending messages for a long time.

It sounds like you should implement some sort of stream between client and server. The client will keep sending messages to server when applicable, using the same channel.

However, you may want to keep an id for client messages so that in the case of a network failure (which can be transient). You can re-issue the rpc and pick up from where it is left.

**Comment by Qian-Zhang7** [comment]
Thanks a lot, Yang!

We are using stream, but we have to close the stream every time we call stream_pages, because we need to call writer->WritesDone and writer->Finish so that the data really are sent; But after we call WritesDone() and Finish(), the channel is closed, so we have to re-open it everytime we re-call stream_pages...

Below is the simplified version of our working code, we are already using it in our product, but hope to get better performance out of grpc send.  Any of your feedback is great appreciated!

---------
int stream_pages(void *rec, char *table_name,
                                unsigned num_records, unsigned record_size, ...)
{
    //error checking for input para
    DataRow row;
    PushResponse response;
    ClientContext ctx;

    auto chan = grpc::CreateChannel(svr_ip + ':' + port_num, grpc::InsecureChannelCredentials());
    auto stub = NamData::NewStub(chan);
    auto writer = stub->Push(&ctx, &response);

    char *cdbrec = (char*)rec;
    for (n = 0; n < num_records; n++) {
            fillDataRow( row, ... );     //simplified, encode data in grpc format              
    }

        if (!writer->Write(row)) {
            // Broken stream, log error
            return 1;
        }

    writer->WritesDone();
    writer->Finish();
    return 0;
}

**Comment by yang-g** [comment]
What you called a channel is actually a stream/rpc, a channel is an
abstract notion of connections to a server address.
You do not need to call WritesDone to sent out the message. You can change
your if to a while loop and keep writing there (until it fails, which means
the server shuts down the stream or there is some error).

**Comment by Qian-Zhang7** [comment]
Thanks Yang! Sorry I was behind my email reply. I Will definitely try your suggestion.

**Comment by Qian-Zhang7** [comment]
Hi Yang,

I think in my last post, due to a mis-align, you may not get the complete flow. The writer->Write(row) is within for loop, and is called for every record.  This api stream_pages is re-entrant unlimited times until server is done, whenever client has some data to send, it will call stream_pages() to send.  

With above info, if we don't call writer->WritesDone and Finish(), I remember at grpc server side we don't see the data at all. Because of adding WritesDone & Finish at end of stream_page(), client has to call grpc::CreateChanne() at beginning ... so client has to reopen & close a new stream for each request (each request has multiple records though).
 
That's why it puzzles me as I thought it is very in-efficient, and definitely I missed something here..

Your input is greatly appreciated!
Qian

-----------
stream_pages(void *rec, char *table_name,
unsigned num_records, unsigned record_size, ...)
{ ...
DataRow row;
PushResponse response;
ClientContext ctx;

auto chan = grpc::CreateChanne(svr_ip + ':' + port_num, grpc::InsecureChannelCredentials());
auto stub = NamData::NewStub(chan);
auto writer = stub->Push(&ctx, &response);

char *cdbrec = (char*)rec;
for (n = 0; n < num_records; n++) {
    fillDataRow( row, ... );     //simplified, encode data in grpc format              
    if (!writer->Write(row)) {
        // Broken stream, log error
        return 1;
    }
} //for
writer->WritesDone();
writer->Finish();
return 0;
} //end of stream_page

**Comment by yang-g** [comment]
Write should send out the data. If you are sure your server does not receive any and want to verify, you can set environment variable GRPC_TRACE=tcp GRPC_VERBOSITY=DEBUG at the client side and watch data being written out after a write.
