### ISSUE TITLE
Translations of docs

### ISSUE THREAD

**Issue by myitcv** [grpc/grpc#11973]
_Following a discussion in the [Gophers grpc slack channel](https://gophers.slack.com/messages/C03RB2KAD)_

### Should this be an issue in the gRPC issue tracker?
 
Yes - it is directly actionable (and does not appear to have been covered in the Google Group or a previous issue)
 
_All other questions n/a for this issue_

---

### The issue/question

Go has a wiki page that links to translations of certain docs:

https://github.com/golang/go/wiki/NonEnglish

Is there an equivalent for the [grpc docs](https://grpc.io/docs/)?

**Comment by hsaliak** [comment]
There is no plans to do this, but it would be a good one for folks to help out!
