### ISSUE TITLE
No way to set :path header in Node.js

### ISSUE THREAD

**Issue by yoitsro** [grpc/grpc#11971]
### What version of gRPC and what language are you using?

Node 8 with grpc version 1.4.1. 
 
### What operating system (Linux, Windows, …) and version?
 
Apple OS X 10.12.5.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Node 8.
 
### What did you do?

Using linkerd in unison with gRPC, I have to set the server as the linkerd gRPC endpoint. I then need to be able to set the `:path` header so linkerd knows where to route the request. By default, gRPC derives the path from the fully qualified name and the method name: https://github.com/grpc/grpc/blob/master/src/node/src/protobuf_js_5_common.js#L114

My service is called "Spaces" and my method is called "ListSpaces", so gRPC creates a path name of `/Spaces/ListSpaces`. However, linkerd doesn't allow for uppercase letters in routes.
 
### What did you expect to see?

A successful gRPC call with data returned from my service.
 
### What did you see instead?
 
```
{ 
  Error: Received RST_STREAM with error code 7
    at /Users/ro/microservice/node_modules/grpc/src/node/src/client.js:570:15 code: 14, metadata: Metadata { _internal_repr: {} } 
}
```

 
### Anything else we should know about your project / environment?

This is all being run in Kubernetes.

**Comment by murgatroid99** [comment]
Using `/Service-Name/Method-Name` as the path is part of the gRPC protocol spec. If you want an all-lowercase path, don't use uppercase letters in those strings. Or use an IDL with case-insensitive service and method names.

**Comment by yoitsro** [comment]
It looks like linkerd does have some sort of a renaming convention so hopefully that'll work: https://github.com/linkerd/linkerd-examples/pull/126/files/431aa28a7c6530014d0264b89569868b502bb83f#diff-b8797241c28b5379b52aeb709e26ae41

Closing this now. Thanks for your speedy response!
