### ISSUE TITLE
node: segfault when invalid arguments are passed to call.startBatch

### ISSUE THREAD

**Issue by pjm0616** [grpc/grpc#11984]
### What version of gRPC and what language are you using?
grpc v1.4.1 and e5cd1765ffbdaf2badff71ecee5f464a2a924f72
nodejs v8.2.4

### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

### What did you do?
1. Apply the following patch to gRPC v1.4.1 or e5cd1765ffbdaf2badff71ecee5f464a2a924f72:
```
diff --git a/examples/node/dynamic_codegen/greeter_server.js b/examples/node/dynamic_codegen/greeter_server.js
index f9cb1b1..9e1844a 100644
--- a/examples/node/dynamic_codegen/greeter_server.js
+++ b/examples/node/dynamic_codegen/greeter_server.js
@@ -25,7 +25,7 @@ var hello_proto = grpc.load(PROTO_PATH).helloworld;
  * Implements the SayHello RPC method.
  */
 function sayHello(call, callback) {
-  callback(null, {message: 'Hello ' + call.request.name});
+  callback({code: 'a', message: 1});
 }
```

2. Run greeter_server.js and greeter_client.js in grpc/examples/node/dynamic_codegen/.

### What did you expect to see?
gRPC throwing TypeError('Incorrectly typed arguments to startBatch')

### What did you see instead?
[1]    20685 segmentation fault (core dumped)  node greeter_server.js

gdb backtrace:
```
Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007ffff48a39c5 in grpc_slice_unref_internal (exec_ctx=0x7fffffff8750, slice=...) at ../src/core/lib/slice/slice.c:74
74	    slice.refcount->vtable->unref(exec_ctx, slice.refcount);
(gdb) bt
#0  0x00007ffff48a39c5 in grpc_slice_unref_internal (exec_ctx=0x7fffffff8750, slice=...) at ../src/core/lib/slice/slice.c:74
#1  0x00007ffff48a3a52 in grpc_slice_unref (slice=...) at ../src/core/lib/slice/slice.c:86
#2  0x00007ffff488d328 in grpc::node::SendServerStatusOp::~SendServerStatusOp (this=0x22872c0, __in_chrg=<optimized out>) at ../src/node/ext/call.cc:280
#3  grpc::node::SendServerStatusOp::~SendServerStatusOp (this=0x22872c0, __in_chrg=<optimized out>) at ../src/node/ext/call.cc:282
#4  0x00007ffff488bb2c in std::default_delete<grpc::node::Op>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/4.9/bits/unique_ptr.h:76
#5  std::unique_ptr<grpc::node::Op, std::default_delete<grpc::node::Op> >::~unique_ptr (this=0x7fffffff8840, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/unique_ptr.h:236
#6  grpc::node::Call::StartBatch (info=...) at ../src/node/ext/call.cc:693
```

In Call::StartBatch(), an instance of SendServerStatusOp is created("op") and op->ParseOp() is called,
but ParseOp fails and returns false due to incorect type(since `code` was set to 'a' in greeter_server.js):
```
grpc/src/node/ext/call.cc:307: if (!maybe_code.ToLocalChecked()->IsUint32()) { return false; }
```
At this time, op->details is not initialized yet and op->details->refcount contains an invalid pointer value.

Again in Call:StartBatch(), it returns TypeError since ParseOp() has failed:
```
grpc/src/node/ext/call.cc:728: return Nan::ThrowTypeError("Incorrectly typed arguments to startBatch");
```
and then the destructor for SendServerStatusOp is called, which tries to call grpc_slice_unref(op->details), where op->details is uninitialized.

Adding `this->details = grpc_empty_slice();` to the constructor seems to fix the problem.

I didn't checked it but a similar issue seems to be also present in ClientStatusOp.

**Comment by murgatroid99** [comment]
Thank you for reporting this. A fix is incoming in pull request #12003. In the meantime, try to avoid passing incorrect types to the API.
