### ISSUE TITLE
Python tests: do our proto-only directories need __init__.py files?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#11993]
They currently do have such files (at least the tree under tests/protoc_plugin/protos), but it doesn't smell like they should have to.

**Comment by mehrdada** [comment]
I'm not well versed in Python package resolution, but wouldn't this break `from tests.protoc_plugin.protos import test_service_pb2` or are the pb2s synthesized in another directory?

**Comment by nathanielmanistaatgoogle** [comment]
For some reason I thought they were synthesized in another directory. I kind of feel like they _should_ be synthesized in another directory, with the exception of the "test that synthesizing in the same directory works" case.

**Comment by mehrdada** [comment]
I think expecting synthesis happens in the same directory is more natural when bazel (or *its variants*) build is used. Perhaps a better model is to expect the code generator to create `__init__.py` if nonexistent.

**Comment by nathanielmanistaatgoogle** [comment]
After working on [pull request 12602](https://github.com/grpc/grpc/pull/12602): it looks like only those tests that use code generation that puts the generated `.py` files into the same tree as the `.proto` files need to have `__init__.py` files among the `.proto` files... and we should think hard about having fewer such tests. I really like the way `_split_definitions_test` puts generated code in an entirely isolated temporary directory.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; the question has been answered "in the moment: yes; in the future: no" and I've filed [issue 15370](https://github.com/grpc/grpc/issues/15370) for a clean-up of the tests.
