### ISSUE TITLE
Ruby - provide an option in extconf.rb to use system grpc

### ISSUE THREAD

**Issue by pravi** [grpc/grpc#12013]
### Should this be an issue in the gRPC issue tracker?
 
yes

### What version of gRPC and what language are you using?
 
1.3.2 with ruby (though it is not specific to any particular version)
 
### What operating system (Linux, Windows, …) and version?
 
Debian GNU/Linux (in all versions, using sid/unstable)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc version 6.4.0 20170704 (Debian 6.4.0-1) 
 
### What did you do?

I'm packaging ruby binding of grpc and it is trying to build libgrpc.a
 
### What did you expect to see?
 
Similar to how OpenSSL or zlib can be used from the system, I should be able to use libgrpc.a from system since grpc is already packaged in debian.
 
### What did you see instead?
 
It is trying to build libgrpc.a but failing to find openssl (may be because bugs in how the build system is setup, but there should be an option to use already built libgrpc.a).
 
### Anything else we should know about your project / environment?

You can see more info about the steps I tried https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867541

**Comment by apolcyn** [comment]
Is there something in particular that is preventing full source compilation, or use of a grpc gem with the core library and ruby-c-extension pre-compiled?

Also by version 1.3.2, I assume this is the version for `libgrpc.a`? Note that newer versions of the ruby wrapper aren't tested with older versions of the c-core library.

**Comment by pravi** [comment]
@apolcyn , there are two reasons for not doing full source compilation 

1. When tried, it could not find openssl because debian already use openssl 1.1 whereas grpc still supports only openssl 1.0. 

2. The already built libgrpc.a or libgrpc.so (since both are available, .so is preferred) is patched to support openssl 1.1. So we really don't need to build it twice (debian already provides libgrpc C and C++ libraries, using them makes it easier to maintain, as we don't have to apply patches twice for example like adding support for openssl 1.1).

3. In debian, we should build every binary from source code as per debian policy, so pre-built binary cannot be used.

The ruby version is also 1.3.2 since I want to use libgrpc.so built from 1.3.2.

I managed to make it work with this patch https://anonscm.debian.org/cgit/pkg-ruby-extras/ruby-grpc.git/tree/debian/patches/no-make-in-extconf.patch but it would be nice if it was supported with a conditional like ENV['EMBED_GRPC'] = 'false'. It also requires a change in LDFLAGS when building libgrpc.so (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867541#89).

**Comment by apolcyn** [comment]
adding @nicolasnoble

**Comment by apolcyn** [comment]
Chatted offline - question on the maintenance of this package: I guess the `libgrpc` debian package is  a little out of date, and we are also seeking maintainers for it. Does maintenance of a `grpc-ruby` debian package entail maintenance of the `libgrpc` package as well?

As for the option of including an `EMBED_GRPC` option in the `extconf.rb`, this seems doable but I'm not sure if it would be more beneficial than a custom patch if this is a one-time use case.

**Comment by pravi** [comment]
@apolcyn I offered to be a co-maintainer, but I was asked to sent patches instead https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867541#27

I'm fine with custom patch, but having it included officially may help people trying to package it for other distros as it took quite a lot of effort for me to figure this out by myself. If it was just setting yes or no, I'd have found this easily like for openssl or zlib.

**Comment by pravi** [comment]
I'd be better if the package was maintained in a git repo for other people to contribute easily as I suggested in the bug above.

**Comment by apolcyn** [comment]
Just note that we don't currently have anything in place for testing this support - ok with putting such options in the main `extconf.rb` file here, but just note their maintenance would likely be best effort.

**Comment by dgquintas** [comment]
@apolcyn is this issue still relevant?

**Comment by apolcyn** [comment]
Rethinking this, perhaps we can let the user pass in a pre-built core library when building the ruby gem.

**Comment by apolcyn** [comment]
Closing since I won't get to this any time soon.  If this is important, please ping this issue, file a new one, or file a patch.
