### ISSUE TITLE
gcc 7 and -Werror=implicit-fallthrough=

### ISSUE THREAD

**Issue by vaurelios** [grpc/grpc#12022]
## What version of gRPC and what language are you using?
 gRPC 1.4.2
 
### What operating system (Linux, Windows, …) and version?
 ArchLinux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc --version
gcc (GCC) 7.1.1 20170528
 
### What did you do?
Just try make the project with `make` command.
 
### What did you expect to see?
 Build complete without any eror
 
### What did you see instead?
Build error on the file `src/core/lib/support/murmur_hash.c` in the switch around line 82.
 
More simple solution (not the better i think) is add ` -Wno-implicit-fallthrough` to `CFLAGS`.

**Comment by nicolasnoble** [comment]
This is fixed by #11796.
