### ISSUE TITLE
FLAKE: interop Kokoro cloud_to_prod:gateway_v4:csharp:large_unary

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#12030]
https://sponge.corp.google.com/target?id=34193a77-65c7-4216-8236-fb0258844b8c&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment]
Dupe of #10763
