### ISSUE TITLE
Invalid/junk characters in AuthMetadataProcessor metadata values at server side

### ISSUE THREAD

**Issue by damleak** [grpc/grpc#12045]
gRPC 1.4 in C++
Ubuntu 14.04 Linux version 4.4.0-78-generic
g++ (GCC) 5.2.0
Attaching both client and server code with this report.

Trying to intercept the calls on both client and server side to send and receive metadata.
At server side the metadata values are appended with invalid characters. Sometimes the service name associate with `:path` key has invalid characters appended. For example,  a key-value pair `("name","James")` set on client side appears as below on server side.

`("name", "James@ttrailers@
                      content-typeapplication/grpc@
user-agentAgrpc-c++/1.4.0-pre1 grpc-c/4.0.0-pre1 (linux; chttp2; gregarious)@grpc-accept-encodingidentity,deflate,gzip)`
[authmd.zip](https://github.com/grpc/grpc/files/1195407/authmd.zip)

**Comment by damleak** [comment]
Is anybody able to reproduce this case? The authentication is failing randomly because of this issue. I wrote the reproducible case to help developers of gRPC and hoping to get faster response. It is actually happening in a real world product under development. Without any help from the developer community for such issues it is difficult for me trust quality of gRPC library.

Thought I can help myself and tried to debug it. But, found out that it is not that easy to attach debugger and dive into core or generated code of the library.

**Comment by dgquintas** [comment]
Hey @damleak I'm afraid this issue slipped through the cracks. Is it still happening?

**Comment by damleak** [comment]
Yes it does happen.

**Comment by dgquintas** [comment]
@damleak sorry, I should have qualified my previous question... is it happening in a recent (eg, 1.7.x) version?

**Comment by damleak** [comment]
I had tested it on versions 1.0 to 1.4 at that time. Not in the recent version. I will try it with new version but, may not be able to do it soon. I think it has something to do with conversion of `grpc::string_ref` prsent in `grpc::AuthMetadataProcessor::InputMetadata` to `grpc::string`.

**Comment by larsonmpdx** [comment]
I had this happen when upgrading from 1.1.x to 1.8.x

same problem, my string_ref looks good but the converted string has the same extra stuff

**Comment by larsonmpdx** [comment]
changing from getting a string by calling string_ref.data() to constructing it like string(string_ref.begin(), string_ref.end()) is a workaround.  a data() call returns const char* and then the string constructor will run to the next null char, something must have changed to make it run too long

see https://github.com/grpc/grpc/blob/master/include/grpc++/impl/codegen/string_ref.h

**Comment by yang-g** [comment]
I think this is working as intended.

A string_ref does not own the string and may not be null terminated. What @larsonmpdx said is correct. In your example code, you will need to change the server side code line 71, 80, 82 to fix that.

I think it worked for some time with very old grpc versions as back then the metadata were null-terminated by default.
