### ISSUE TITLE
Kokoro build TIMEOUT: build_artifact.python_windows_x64_Python34

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#12049]
Happened in https://sponge.corp.google.com/target?id=1a047c9d-0b13-4d0c-9099-78449af2bd52&target=grpc/windows/pull_request/grpc_build_artifacts&searchFor=&show=ALL&sortBy=STATUS

**Comment by adelez** [comment]
Another instance: https://sponge.corp.google.com/target?id=4abdf26e-80e4-48db-95aa-92264e6f84b4&target=grpc/windows/pull_request/grpc_build_artifacts&searchFor=&show=ALL&sortBy=STATUS
