### ISSUE TITLE
Migrate interop test specifications to open source

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1205]
We have a document specifying how our interoperability tests are required to work, but it's imprecise, unversioned, and not yet part of the project's open source content. As our interoperability tests become more and more the metric by which we measure this library's development, the fact that they conform to an invisible specification becomes proportionately more an area of poor communication on our part.

We should migrate that document's content to this repository and flesh it out so that it's a complete specification of all of our interoperability tests. It should be possible for those implementing gRPC in strange languages (Ante, Befunge, and Standard ML of New Jersey) to write their own interoperability test code without having to reverse-engineer the extant implementations in this library, as they would have to do today.

**Comment by nathanielmanistaatgoogle** [comment]
This is a large enough work item that anyone could take it but everyone has a reason not to - anyone have any ideas on who should drive it? I could see it being any one of @donnadionne, @tbetbetbe, @a11r, @ejona86, @nicolasnoble, or myself. Any volunteers?

Anyone dispute the issue itself or have any other pushback?

**Comment by ejona86** [comment]
I can pick it up. But there is the question of where it should live. I would assume grpc/grpc, but the gRPC over HTTP/2 spec is in grpc/grpc-common. I still don't understand the point of grpc-common.

**Comment by nathanielmanistaatgoogle** [comment]
Either destination satisfies the requirements of this issue and is fine by me. Please include me as a reviewer on all pull requests?
