### ISSUE TITLE
Kokoro mac: Failed to activate the given service account.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12056]
I've seen this more than once:
https://github.com/grpc/grpc/blob/9fb4536821da85044339259063e60b95a42d447b/tools/internal_ci/helper_scripts/prepare_build_macos_rc#L34
```
gcloud auth activate-service-account --key-file=/tmpfs/src/gfile/GrpcTesting-d0eeee2db331.json
ERROR: (gcloud.auth.activate-service-account) Failed to activate the given service account. Please ensure provided key file is valid.
```

https://sponge.corp.google.com/target?id=b0dfae30-fb7d-4689-9912-7f88fbb6d7b2&target=grpc%2Fmacos%2Fmaster%2Fgrpc_basictests_dbg&searchFor=

Is the activate-service-account actually needed? I though just setting GOOGLE_APPLICATION_CREDENTIALS might be enough.

**Comment by matt-kwong** [comment]
You're right, good catch.
