### ISSUE TITLE
Bizarre Connect Failed error

### ISSUE THREAD

**Issue by danielwaterworth** [grpc/grpc#12069]
### What version of gRPC and what language are you using?

1.4.0 
 
### What operating system (Linux, Windows, …) and version?
 
Ubuntu 17.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.5.3

### What did you do?

I have a small test case to demonstrate the problem [here](https://github.com/danielwaterworth/grpc-test-case). There are two versions of the server, [`working.py`](https://github.com/danielwaterworth/grpc-test-case/blob/master/working.py) and [`not_working.py`](https://github.com/danielwaterworth/grpc-test-case/blob/master/not_working.py) and there's a client, [`run_client.py`](https://github.com/danielwaterworth/grpc-test-case/blob/master/run_client.py). I start the server first and then the client. If the client succeeds it prints success, otherwise there's an exception. The only difference between working and not_working is that the calls to start the server are put in a function and then called instead of being called directly. With this seemingly innocuous change, the client cannot connect to the server, failing with this error:

    (env) dan@xps:~/b/test_case$ python run_client.py 
    Traceback (most recent call last):
      File "run_client.py", line 3, in <module>
        backend.client.upscale(b'hello')
      File "/home/dan/b/test_case/backend/client.py", line 10, in upscale
        return stub.Upscale(backend_pb2.Image(data=data)).data
      File "/home/dan/b/test_case/env/lib/python3.5/site-packages/grpc/_channel.py", line 507, in __call__
        return _end_unary_response_blocking(state, call, False, deadline)
      File "/home/dan/b/test_case/env/lib/python3.5/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
        raise _Rendezvous(state, None, None, deadline)
    grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

**Comment by nathanielmanistaatgoogle** [comment]
In `not_working.py` it looks like `server` is a function-local field and as such the value that is assigned to it (a `grpc.Server` instance) is garbage-collected when the function terminates (and when a `grpc.Server` gets garbaged-collected, it gets shut down).

In `working.py`, it looks like the thread that is spawned serves to keep the fields a program top-level from being garbage collected (and so your server stays serving).

Is that what's going on?

**Comment by danielwaterworth** [comment]
Ok, that makes sense. Thanks for looking into this. Do you agree that, although each part is doing what it is supposed to, the overall behaviour here is counter intuitive?

Some things that might have helped in this case would have been:

 * Using a blocking version of `Server.start` in the documentation,
 * Logging when an active server is garbage collected,

**Comment by danielwaterworth** [comment]
Also, I don't actually understand why the server _is_ being garbage collected. The server should have a thread, right? And threads are roots. In this program, the thread doesn't stop just because there aren't any references to it.

```python
import threading
import time

def go():
    while True:
        time.sleep(2)
        print("hello")

def start_thread():
    threading.Thread(target=go).start()

start_thread()
```

**Comment by nathanielmanistaatgoogle** [comment]
In the future we'll probably log an error if a serving `grpc.Server` is garbage collected. Offering a blocking version of `grpc.Server.start` is more of a stretch.

Threads prevent the garbage collection of the objects that they can reach, not the garbage collection of objects that can reach them.

**Comment by danielwaterworth** [comment]
> Threads  prevent the garbage collection of the objects that they can reach, not  the garbage collection of objects that can reach them.

Sure, but doesn't starting the server start and thread and doesn't that thread have a reference to the server?

**Comment by danielwaterworth** [comment]
> In the future we'll probably log an error if a serving grpc.Server is garbage collected. Offering a blocking version of grpc.Server.start is more of a stretch.

If you're planning on doing work related to this issue. Can you leave it open until its done?

**Comment by nathanielmanistaatgoogle** [comment]
@danielwaterworth: no, the thread started by the server doesn't have a reference to the server - maybe you have to monolithic a conception of the server? The thread started by the server has references to smaller structures _inside_ the server, but not the server itself.

@danielwaterworth: this issue is about a mysterious failure to connect - we solved the mystery, didn't we?

**Comment by danielwaterworth** [comment]
> this issue is about a mysterious failure to connect - we solved the mystery, didn't we?

We solved the mystery, but we didn't prevent others falling into the same hole.

> no, the thread started by the server doesn't have a reference to the server - maybe you have to monolithic a conception of the server? The thread started by the server has references to smaller structures inside the server, but not the server itself.

This would be fine, but this behaviour is not documented and in the absence of docs that say otherwise, I assumed the `start` method would work similarly to that of  `Thread`. The tutorial says, "Because start() does not block you may need to sleep-loop if there is nothing else for your code to do while serving", but it doesn't say that if don't hold a reference to the server object, it will silently stop serving. The API docs don't talk about this either.

**Comment by nathanielmanistaatgoogle** [comment]
I think "I assumed the `start` method would work similarly to that of `Thread`" is the issue - I don't think that cognitive leap is warranted. There's no logical, syntactic, or semantic relationship between `grpc.Server`s and `threading.Thread`s, right? The fact that `grpc.Server`s (currently) happen to have a `threading.Thread` inaccessibly inside is an internal implementation detail, right?
