### ISSUE TITLE
Anonymous structs and unions can makes FFI bindings difficult

### ISSUE THREAD

**Issue by yallop** [grpc/grpc#12075]
At present the GRPC interface includes several anonymous structs and unions, which can make it difficult for some tools to create bindings to GRPC.

### The problem

Currently, a number of struct and union types in `grpc_types.h` have neither a tag name nor a `typedef` alias.  For example, `grpc_arg` contains a union type that contains a [struct type without a name](https://github.com/grpc/grpc/blob/9fb4536821da85044339259063e60b95a42d447b/include/grpc/impl/codegen/grpc_types.h#L110-L113):

```C
    struct {
      void *p;
      const grpc_arg_pointer_vtable *vtable;
    } pointer;
```

Anonymous struct types like the type above make it difficult or impossible for certain tools to create foreign language bindings to a library.  For example, one binding strategy (used, for instance, in the [OCaml ctypes library](https://github.com/ocamllabs/ocaml-ctypes)) is to generate C code that determines the layout of C objects, then use the layout information to access those objects directly from the foreign language.  The generated C code uses type names to determine layout, like this:

```C
    … sizeof(struct foo) …
    … offsetof (struct foo, field_x) …
    … alignmentof (struct foo) …
```

Clearly this approach won't work if the types involved don't have names.

### The fix

An open PR, #12059, adds tags to the anonymous structs and unions.

**Comment by markdroth** [comment]
I am not sure that we want to commit to avoiding anonymous structs in all public APIs.  We certainly have no test infrastructure to enforce this, so even if this PR goes in, there's no guarantee that parts of it won't be undone later, or that we won't add new anonymous structs in the future.  And it does make the structures a bit bulkier and harder to read.

Those aren't insurmountable problems -- we could live with the bulky structs and could avoid anonymous structs at least on a best-effort basis -- but I think that in order to justify doing this, we need to know that the benefit is worth the hassle.  How many users will ever actually benefit from this?

**Comment by yallop** [comment]
I suppose it'd be possible to add test infrastructure, but I think it'd be overkill to do so.  It wouldn't be disastrous if new anonymous structs appeared in future, since they can always be given tags if needed, without breaking anything.

I think the real question is about cost/benefit.  The cost is pretty small: while there are some extra names to read, the names are useful in themselves, since they make it possible to refer to the struct types in conversation, documentation, etc.  And the benefit is clear and immediate -- for example, I would benefit from named structs right now, since I'm in the middle of building OCaml gRPC bindings.

If the names in #12059 are too long, I've no objection to changing them, and welcome suggestions for better names.

**Comment by markdroth** [comment]
I agree that the real question here is cost/benefit and that the costs aren't huge.  But I am not sure there's much benefit here either, and I am reluctant to take any cost unless there's benefit for more than one user.  This is why I asked how many users will ever actually benefit from this -- if there are other users that will benefit from this, then it may make more sense to do this.  But if it's just one, I'm not sure it's worth it.

**Comment by vjpai** [comment]
Hi there, I'd like to suggest that we can allow this. This will break on a best-effort basis, but language-binding-writers already know that grpc core has no guarantee of a stable API (I think it's already on v 4.x compared to 1.5 at C++). And when it does break, the language-binding community will submit a followon PR to do what they need. If this enables new bindings that we don't have to support anyway, I don't see the downside for us.

**Comment by dgquintas** [comment]
I agree with @vjpai . There's no downside, and in my opinion the code becomes more readable, not less. In addition, we don't know how many users this benefits. It doesn't hurt any one. It feels it's up upsides and no downside.

**Comment by markdroth** [comment]
Okay.  I'm still a little concerned that this will cause problems down the road, but it seems that I'm in the minority on this, so I won't stand in the way.

**Comment by vjpai** [comment]
Well, I don't want to run roughshod over your opinion either; can we summon @a11r for some additional consultation? My understanding is that there's not a huge rush to merge this at master right this second or anything like that.

**Comment by vjpai** [comment]
Also, @markdroth, we could add this to sanity checks:

```sh
grep -Iri '^ *struct *{' include/grpc | diff - /dev/null
```

As long as we're clang-formatted, that should solve the issue of unnamed struct's that aren't typedef'ed in the public headers.

**Comment by markdroth** [comment]
If we can add a reliable sanity check for this, and if we use shorter names for the structs (I'll add some suggestions in the PR), then I'll be okay with this.

@vjpai, I think your suggested check would also need to somehow exclude internal-only structs, like the one discussed in the PR.

**Comment by markdroth** [comment]
Just looked at the PR again.  Given that the struct definitions will have global scope, I guess the proposed names are about as short as we can reasonably use, so I guess I don't have any suggestions on how to improve this. :(

Anyway, I can live with this if we can write a reasonable sanity checker for it.

**Comment by vjpai** [comment]
The problem with excluding internal-only structs is that we can't tell what is internal only at the sanity-checker level. The only clue that we have is its directory, so clearly we won't check anything besides include/grpc and its subdirectories.

**Comment by yallop** [comment]
Here's one possible way to satisfy the sanity check regex:
````C
struct /* internal */ {
```
