### ISSUE TITLE
inject randomness into closure execution order to identify timing bugs

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#12082]
As discussed at today's standup, we should have some mechanism to inject some randomness into the closure execution order to help us identify timing bugs.

One possible idea for doing this is to change `GRPC_CLOSURE_RUN()` to randomly call `GRPC_CLOSURE_SCHED()` to reschedule the closure instead of executing it immediately.  If there are cases where code can safely assume that closures it schedules will be executed in the order scheduled in the same thread (e.g., scheduling a closure on a combiner from within the combiner), then we need to make sure not to break that.  One possible way of addressing this would be to make the change described above only for the exec_ctx scheduler, not for the combiner scheduler, although that has the disadvantage that it would not help identify any timing bugs in code using a combiner.  (Although even with that restriction, this may still be a valuable approach, since the majority of closures use the exec_ctx scheduler.)

There may be other ways of doing this as well.  For example, @a11r suggested an approach where multiple threads are executing and they randomly yield back to the application without completing all of their work.  We should discuss options, pick one, and implement it.

I am assigning to @ncteisen as a placeholder, since he's the last one to make significant changes to the closure interface.

Discussion welcome.

**Comment by ncteisen** [comment]
Quick pass at the aggressive yielding idea: #12084.

We can watch the tests and determine if it is useful

**Comment by vjpai** [comment]
@markdroth : do combiners have a FIFO guarantee as part of their contract; [the combiner explainer](https://github.com/grpc/grpc/blob/master/doc/combiner-explainer.md) doesn't seem to indicate this. Yes, things on the same combiner are run one-at-a-time, but is there a guarantee that that is the same as the order in which SCHED was called?

**Comment by markdroth** [comment]
I think this is a bit of a grey area.  I don't think we document this as a guarantee, but I think @ctiller has mentioned to me that we do have some code that relies on the fact that if it schedules multiple closures in the same thread, that particular set of closures will be executed in the order scheduled.  And I suspect that this is true for both the combiner scheduler and for the default exec_ctx scheduler.

I don't think we make any guarantees about execution order of closures scheduled from different threads (for any scheduler).  I think this issue is only about the order of closures scheduled in a single thread.

The best way to figure this out would be to try implementing the random-reordering idea and see what breaks.  Even if we find some breakage, we can look at the problem and see if there's a reasonable way to fix the code to not make that assumption anymore.

**Comment by ncteisen** [comment]
Do we still want to pursue this?

**Comment by markdroth** [comment]
I still think it would be useful to do this if we can find a way to make it happen.
