### ISSUE TITLE
GRPC apt package

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1208]
@jgeewax recommends that installation of GRPC be possible with `sudo apt-get install grpc`.

**Comment by tbetbetbe** [comment]
Next steps
- [] Attach the 0_6_0 debian package to the 0_6_0 release
- [] Update our instructions for using the 0_6_0 debian package to note the debian experimental is required in their deb sources to install openssl
- [] Update this issue and its instructions as soon as openssl-1.0.2-1 moves out of experimental

**Comment by tbetbetbe** [comment]
I'm closing this issue, @andrewpollock's going to be working on debian packaging and keeping status on #662, it's best to have one reference issue for this work, so I'll mark this as duplicate.
