### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by massoud12345** [grpc/grpc#12094]
### OS
 sw_vers 
Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
pod --version
1.2.0
Hi, I get the following error messages when I build and run gRPC in XCode.
Wuld you guys know how to fix this?
Thanks

![screen shot 2017-08-05 at 17 52 52](https://user-images.githubusercontent.com/11024427/28999711-21d557ba-7a07-11e7-808f-02d49101816f.png)
![screen shot 2017-08-05 at 17 48 10](https://user-images.githubusercontent.com/11024427/28999712-21db6a56-7a07-11e7-8e94-a93d57048700.png)

**Comment by ohtangza** [comment]
I am also experiencing this when running on actual iOS device.

**Comment by muxi** [comment]
Sorry for missing this issue. I am closing the issue since it is so stale, but do let us know if it still happens and we will help.
