### ISSUE TITLE
Improve install docs for Windows users -- suggest vcpkg

### ISSUE THREAD

**Issue by dalebrubaker** [grpc/grpc#12097]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes, change is to INSTALL.md
 
### What version of gRPC and what language are you using?
 V1.42
C++
 
### What operating system (Linux, Windows, …) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 MSVC
 
### What did you do?
Spent a LOT of time trying to build from source, as recommended. There are lots of problems, as many have mentioned. e.g. https://stackoverflow.com/questions/39982065/grpc-c-on-windows/45543748#45543748 and https://github.com/grpc/grpc/issues/11763
 
### What did you expect to see?
 An easy way for a C++ Windows user to install grpc and its dependencies.
 
### What did you see instead?

Various ways to build, all very time-consuming and complex. None successful. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
I'll submit a pull request with a possible doc improvement.
 
### Anything else we should know about your project / environment?
No

**Comment by jtattermusch** [comment]
I think the current documentation is correct (=reflects the current state of build support on Windows), but according to numerous issues, users are still having trouble building gRPC library on Windows (as a part of their project). We'll try to look into this by revisiting our cmake build (hopefully in Q1 2018).
For now, I'll close this issue as there's not much that can be added here.
