### ISSUE TITLE
gRPC yum package

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1209]
@jgeewax recommends that installing gRPC be as simple as `sudo yum install grpc`.

**Comment by ctiller** [comment]
@a11r, @jayantkolhe - should this be Beta?

**Comment by ppg** [comment]
I have a potential first pass at a specfile that can build the rhel packages but I can't figure out how to integrate that into this repo? The readme here https://github.com/grpc/grpc/tree/master/tools says that there should be a folder `distpackages` for building debian packages, which I was going to inspect for patterns, but I don't see that folder there?

**Comment by nicolasnoble** [comment]
That information is widely outdated. The debian package now follows the
typical architecture of residing in its own branch. Look at the branches of
grpc, you'll see the various debian ones.

**Comment by naokato** [comment]
Any updates?
I'd like to know what the situation of the issue is.

**Comment by mehrdada** [comment]
We have carefully considered the general question of shipping packages in system repositories and that is not on our current plans and we are not prioritizing this at the moment. Please do consider filing specific issues if this prevents you from using gRPC or severely impacts such usage.
