### ISSUE TITLE
authority based dns uri's not supported?

### ISSUE THREAD

**Issue by tjb1216** [grpc/grpc#12119]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.4.1 release  c++
 
### What operating system (Linux, Windows, …) and version?
 linux centos 6.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 I want to use load balance via dns:
 ChannelArguments args;
  args.SetLoadBalancingPolicyName("round_robin");
  GreeterClient greeter(grpc::CreateCustomChannel(
      "dns://localhost:8600/sag_test_grpc.service.consul-dev.",                                                                                                        
      grpc::InsecureChannelCredentials(), args));
### What did you expect to see?
 expect to resolve exactly
 
### What did you see instead?
 E0808 16:51:30.685566274   31696 dns_resolver.c:252]         authority based dns uri's not supported
E0808 16:51:30.685591023   31696 channel.c:99]               channel stack builder failed: {"created":"@1502182290.685573354","description":"resolver creation failed","file":"src/core/ext/filters/client_channel/client_channel.c","file_line":719}
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
Authority based dns uri's not supported for now? What's your plan to supports this? Thanks a lot.
@dgquintas @ctiller

**Comment by hubo1016** [comment]
It seems that the currently supported addresses are like: dns:///localhost:8600
Notice there are three /, means authroity == ""

**Comment by markdroth** [comment]
This is supported in the c-ares DNS resolver, but not in the native DNS resolver.  Currently, the default DNS resolver is still the native resolver, because there are some features still missing from the c-ares DNS resolver (mainly CNAME handling and address sorting).  Once we finish implementing those features, we will make the c-ares DNS resolver the default.

For now, if you don't need any of the features that are still missing from the c-ares resolver, you can use it.  You can do this by setting the environment variable `GRPC_DNS_RESOLVER=ares`.
