### ISSUE TITLE
gRPC Windows installer

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1212]
@jgeewax recommends that installing gRPC be as simple as double-clicking a .msi file, then clicking Next, Next, Install, and Done.

**Comment by yinhm** [comment]
+1

I really don't know how to using those exe files from the binary win32 release(clicked without any results other than a cmd terminal).

**Comment by chai2010** [comment]
+10086
I hate build protobuf3/grpc and many unknown depends.

**Comment by ctiller** [comment]
@a11r, @jayantkolhe - should this be Beta?

**Comment by jgeewax** [comment]
Escalating this -- I just tried to find some way to install gRPC for Python on Windows, and... failed.

I tried installing the NuGet package for the C# version (assuming it'd install the core stuff too) and then ran `C:\Python27\Scripts\pip.exe install grpcio` and got an error "Cannot open include file: 'grpc/grpc.h': No such file or directory"

I think an installer would be really nice to have here.

**Comment by jgeewax** [comment]
(Note this is actually a blocker for gcloud-python, gcloud-node, gcloud-ruby, and gcloud-php to use gRPC -- as installing will fail for these.)

gcloud-dotnet shouldn't be blocked (due to NuGet Visual Studio happiness)

I'm not sure gcloud-java and gcloud-golang for this. I suspect they'd be fine, but I'd have to verify myself.

**Comment by jtattermusch** [comment]
I believe this will be covered by our new packaging story (distribution packages will use precompiled binary artifacts to work on linux/mac/windows. There won't be any installation step necessary at the system level (like MSI installer).

@jgeewax Is it fine to close this issue now?

**Comment by jgeewax** [comment]
I think so.

Just for posterity:

- The plan now is to rely on per-language installation rather than per-platform (ie, Windows).
- The issue now becomes N issues: "Installation on Windows for (Python|Ruby|Node.js|etc) doesn't work (yet)"

**Comment by soltanmm** [comment]
What about C/C++? Is this something to be concerned with there?

**Comment by jtattermusch** [comment]
@jgeewax , agreed.

@soltanmm  I think our plan for C++ for windows is:
1. be able to checkout the repository and include the C++ projects in you C++ solution in VS (this is the poor man's solution).
2. provide a native nuget package for gRPC C++. With that one, you will be able to just install the dependency from VS and everything should work as expected. (this is obviously a bit more work).

Installing gRPC C++ using MSI currently doesn't make much sense.

Closing this issue.
