### ISSUE TITLE
Add ability to restrict the number of threads created by C++ ThreadManager (used by Sync server)

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#12147]
Currently [thread_manager.cc](https://github.com/grpc/grpc/blob/master/src/cpp/thread_manager/thread_manager.cc) does not expose a way to control the max number of threads created.

This may be useful to prevent thread exhaustion in cases the server is flooded with a sudden burst of requests (especially streaming rpc requests).

More concretely:
- In addition to `min_pollers_` and `max_pollers_`, add ability to specify a new `max_threads_`  as well
- Do not create a new thread if `num_threads_` is already equal to `max_threads_`

**Comment by vjpai** [comment]
So will you return with status resource exhausted in this case?

**Comment by sreecha** [comment]
Have a proposal here: https://github.com/grpc/proposal/blob/4c8ae7b9a112a34d34958254c2f0f1820f4c72a7/L26-Ability-to-restrict-max-threads-in-C%2B%2BSyncServer.md

**Comment by sreecha** [comment]
Fixed in #16081
