### ISSUE TITLE
C#: grpc_csharp_ext.dll not found when running under xunit

### ISSUE THREAD

**Issue by mamaso** [grpc/grpc#12154]
Repo with project to repro here: https://github.com/mamaso/GrpcDllNotFoundRepro

I'm unable to use Grpc.Core out-of-box in test projects running with xunit.

When I attempt to run a test that spins up a grpc server, I get the following error:

`Message: System.IO.FileNotFoundException : Error loading native library. Not found in any of the possible locations: <repo>\TestProj\bin\Debug\netcoreapp2.0\grpc_csharp_ext.x64.dll,<repo>\TestProj\bin\Debug\netcoreapp2.0\runtimes/win/native\grpc_csharp_ext.x64.dll,<repo>\TestProj\bin\Debug\netcoreapp2.0\../..\runtimes/win/native\grpc_csharp_ext.x64.dll`

I can manually copy the `runtimes` folder from the nuget package to the test output directory, but that's not a good long-term solution.

In contrast to the test project, when starting the grpc server from a console app outside of the vstest context the dll is found without errors.

The console app and the test project have the identical generated `runtimeconfigs`, which is how I think these dlls are normally found:
```
// runtimeconfig.deps.json
{
  "runtimeOptions": {
    "additionalProbingPaths": [
      "C:\\Users\\mamaso\\.dotnet\\store\\|arch|\\|tfm|",
      "C:\\Users\\mamaso\\.nuget\\packages"
    ]
  }
}

// runtimeconfig.json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0-preview2-25407-01"
    }
  }
}
```

similar to https://github.com/grpc/grpc/issues/7230

**Comment by mamaso** [comment]
Actually, this appear to be a dupe of https://github.com/xunit/xunit/issues/1363

**Comment by mamaso** [comment]
Looked a bit more into this:

Grpc is finding runtimes by looking relative to assembly location of grpc.core.dll.
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L106

For most projects, dependencies are not copied to output directory, so grpc.core.dll is found in the nuget cache location of runtimeconfig.dev.json additionalProbingPaths. Xunit test projects set CopyNugetImplementations, which drops all .dlls in output directory https://github.com/xunit/xunit/blob/master/src/xunit.core/build/xunit.core.props#L6

A workaround is to delete grpc.core.dll from the output folder prior to running tests - it will be found via additionalProbingPaths in a location that correctly references runtimes.

**Comment by adamhathcock** [comment]
Looks like this was solved in xunit: https://github.com/xunit/xunit/issues/1363 Hopefully new beta soon

**Comment by jtattermusch** [comment]
ok to close this issue?

**Comment by mamaso** [comment]
Yep!

**Comment by raulAtNines** [comment]
@mamaso I am currently running into this issue under grpc core 1.12.0 with .net 4.5.
Is there something different that needs to be configured in a .net 4.5 project?

Do I need to add post-build steps to copy the runtime/os../ folders?

Thanks,
Rsam.

**Comment by bobuva** [comment]
@raulAtNines I'm also running into this problem with `Grpc.Core` and .NET 4.5. In fact I need to have `Grpc.Core` in the GAC since the dependency chain starts with a dll that was triggered via a profiler. Have you found a way to solve your problem?

**Comment by raulAtNines** [comment]
@bobuva 
I fixed it by adding:
`xcopy /E /Y "$(SolutionDir)packages\Grpc.Core.1.12.0\runtimes\*.*" "$(TargetDir)runtimes\*.*"`
As a post-build step in: _Solution Properties > Build Events > Post-build event command line_.

This copies the entire folder from _packages_ into the generated folder, where the executable has access to them.

**Comment by bobuva** [comment]
Cool. I had done that but the assembly search algorithm was really fussy with the GAC. I had to copy the native `grpc_csharp_ext.x64.dll` into a subfolder in the GAC for it to find it. Still only a short-term solution for me.
