### ISSUE TITLE
objc tests failing due to 'GRPCClient/GRPCCall.h' file not found

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12150]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/7330/testReport/junit/(root)/aggregate_tests/run_tests_objc_macos_dbg_native/

https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/7330/testReport/junit/(root)/aggregate_tests/run_tests_objc_macos_opt_native/

**Comment by muxi** [comment]
Resolved.
