### ISSUE TITLE
Kokoro mac artifact builds flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12161]
Often fails when trying to compile older versions of ruby. All the build failures I've seen have been caused by this.

https://sponge.corp.google.com/target?id=d1d97807-1719-4a59-a047-2bdb8fecb713&target=grpc%2Fmacos%2Fmaster%2Fgrpc_build_artifacts&searchFor=

Error happens when running https://raw.githubusercontent.com/grpc/grpc/master/tools/distrib/build_ruby_environment_macos.sh

```
Updating /Users/kbuilder/.rake-compiler/config.yml
Found Ruby version 2.3.0 for platform x86_64-darwin11 (/Users/kbuilder/.rake-compiler/ruby/x86_64-darwin11/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin11/rbconfig.rb)
Found Ruby version 2.4.0 for platform x86_64-darwin11 (/Users/kbuilder/.rake-compiler/ruby/x86_64-darwin11/ruby-2.4.0/lib/ruby/2.4.0/x86_64-darwin11/rbconfig.rb)
+ for v in 2.4.0 2.3.0 2.2.2 2.1.5 2.0.0-p645

.....

compiling /Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/dln.c
compiling /Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/localeinit.c
compiling /Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:30:2: error: RUBY_EXEC_PREFIX must be defined
#error RUBY_EXEC_PREFIX must be defined
 ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:41:50: error: use of undeclared identifier 'RUBY_LIB_VERSION'
typedef char ruby_lib_version_string[(int)sizeof(RUBY_LIB_VERSION) - 2];
                                                 ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:59:33: error: use of undeclared identifier 'RUBY_EXEC_PREFIX'
const char ruby_exec_prefix[] = RUBY_EXEC_PREFIX;
                                ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:68:5: error: use of undeclared identifier 'RUBY_EXEC_PREFIX'
    RUBY_SITE_LIB2 "\0"
    ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:46:37: note: expanded from macro 'RUBY_SITE_LIB2'
#define RUBY_SITE_LIB2              RUBY_SITE_LIB    "/"RUBY_LIB_VERSION
                                    ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:35:23: note: expanded from macro 'RUBY_SITE_LIB'
#define RUBY_SITE_LIB RUBY_LIB_PREFIX"/site_ruby"
                      ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:32:25: note: expanded from macro 'RUBY_LIB_PREFIX'
#define RUBY_LIB_PREFIX RUBY_EXEC_PREFIX"/lib/ruby"
                        ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:68:5: error: expected ';' after top level declarator
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:46:37: note: expanded from macro 'RUBY_SITE_LIB2'
#define RUBY_SITE_LIB2              RUBY_SITE_LIB    "/"RUBY_LIB_VERSION
                                    ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:35:23: note: expanded from macro 'RUBY_SITE_LIB'
#define RUBY_SITE_LIB RUBY_LIB_PREFIX"/site_ruby"
                      ^
/Users/kbuilder/.rake-compiler/sources/ruby-2.2.2/loadpath.c:32:41: note: expanded from macro 'RUBY_LIB_PREFIX'
#define RUBY_LIB_PREFIX RUBY_EXEC_PREFIX"/lib/ruby"
                                        ^
5 errors generated.
make: *** [loadpath.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/Volumes/BuildData/tmpfs/src/github/grpc/tmpfile.0yF6PHZY:155:in `block (2 levels) in <top (required)>'
/Volumes/BuildData/tmpfs/src/github/grpc/tmpfile.0yF6PHZY:154:in `block in <top (required)>'
/Users/kbuilder/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => cross-ruby => install => /Users/kbuilder/.rake-compiler/ruby/x86_64-darwin11/ruby-2.2.2/bin/ruby.exe => /Users/kbuilder/.rake-compiler/builds/x86_64-darwin11/ruby-2.2.2/ruby.exe
(See full trace by running task with --trace)
I0810 17:54:50.106232  137359 util.py:247] 
```

**Comment by jtattermusch** [comment]
Looks like this happens whevever "verconf.h" is not generated (or not generated on time) before building loadpath.c

Successful build looks like this:
```
creating verconf.h
compiling /Users/kbuilder/.rake-compiler/sources/ruby-2.1.5/loadpath.c
```

**Comment by jtattermusch** [comment]
http://lists.busybox.net/pipermail/buildroot/2014-December/114273.html

**Comment by jtattermusch** [comment]
@apolcyn  @nicolasnoble  ideas how to fix/workaround are welcome. :-)

**Comment by apolcyn** [comment]
I can definitely reproduce this flakiness but I don't have an idea right now... On a sort of related note, is the [fetching the ruby environment script via wget](https://github.com/grpc/grpc/blob/master/tools/internal_ci/macos/grpc_build_artifacts.sh#L30) vs. running straight from the current repo needed?

**Comment by apolcyn** [comment]
@jtattermusch actually related to the link you posted above, there is a workaround for what looks like this issue, posted in https://patchwork.ozlabs.org/patch/418321/.  I have not tested yet but I'm thinking that something like that could be done as a further patch to https://raw.githubusercontent.com/rake-compiler/rake-compiler/v1.0.3/tasks/bin/cross-ruby.rake. .... I could look into that tomorrow.

**Comment by apolcyn** [comment]
https://github.com/apolcyn/grpc/commit/4386f57926aaec21a032ea0f7ce98e3c7ea142ce is a start - this zip file pointed out by @nicolasnoble. There's another failure now though :/ 
```
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/Users/kbuilder/.rvm/gems/ruby-2.4.0/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:515:in `ruby_api_version'
/Users/kbuilder/.rvm/gems/ruby-2.4.0/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:262:in `block in define_native_tasks'
```

**Comment by apolcyn** [comment]
cc @nicolasnoble, it looks like there is a big problem with the use of the pre-built `rake-compilers.zip` files on kokoro because that file isn't portable outside of those jenkins workers (there are lots of references to the jenkins mac worker home directory throughout files/directories in that zip file).

Since it seems like that zip file is worth using though for speed and stability, solutions I can think of:
1. mass-replace `/User/jenkins` to the current home direcotry upon download of that zip file.
2. Continue building this file on kokoro workers but start caching it. Use both the current home directory and the date as keys for this cache.

**Comment by jtattermusch** [comment]
For now, I have a fix here: https://github.com/grpc/grpc/pull/12779.

Once we unflake the build, we can look into using the pre-build zipfile with rake-compilers (but I think that might be  tricky because the pre-built stuff is not necessarily portable - as you pointed out).
