### ISSUE TITLE
Kokoro Windows artifact build failing on protobuf

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#12170]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
Master, head
 
### What operating system (Linux, Windows, …) and version?
 
 Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Kokoro
 
### What did you do?

Tested PR #12166 
 
### What did you expect to see?
 
 Successful Windows build

### What did you see instead?

Repeated failures because of multiply defined function `setmode` : once coming from a C system header and one coming from a C++ `using` declaration in protobuf.

```
third_party\protobuf\src\google\protobuf\compiler\plugin.cc:55:42: error: 'int google::protobuf::internal::win32::setmode(int, int)' conflicts with a previous declaration

 using google::protobuf::internal::win32::setmode;

                                          ^~~~~~~

In file included from C:/tools/msys64/mingw64/x86_64-w64-mingw32/include/fcntl.h:8:0,

                 from third_party\protobuf\src\google\protobuf\compiler\plugin.cc:39:

C:/tools/msys64/mingw64/x86_64-w64-mingw32/include/io.h:340:15: note: previous declaration 'int setmode(int, int)'

   int __cdecl setmode(int _FileHandle,int _Mode) __MINGW_ATTRIB_DEPRECATED_MSVC2005;

               ^~~~~~~

error: command 'C:\\tools\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
```
 
https://sponge.corp.google.com/target?id=63f324b3-9caa-4616-83a4-9435ad7a1d7f&target=grpc/windows/pull_request/grpc_build_artifacts&searchFor=&show=ALL&sortBy=STATUS

**Comment by stanley-cheung** [comment]
https://github.com/google/protobuf/issues/3483
