### ISSUE TITLE
Linker Warning in gRPC-Core in Xcode

### ISSUE THREAD

**Issue by sibinlutoken** [grpc/grpc#12194]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
YES

### What version of gRPC and what language are you using?
 
Using gRPC (1.4.2)
Using gRPC-Core (1.4.2)
Using gRPC-ProtoRPC (1.4.2)
 
### What operating system (Linux, Windows, …) and version?
 
MacOS Sierra 10.12.6 

### What runtime / compiler are you using (e.g. python version or version of gcc)

Apple LLVM version 8.1.0 (clang-802.0.42)
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Im using Xcode 8.3.3, include !ProtoCompiler in cocoapod 

### What did you expect to see?
 
no warning
 
### What did you see instead?
ld: warning: pointer not aligned at address 0xC8882 (_google_census_Resource_fields + 34 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC88BA (_google_census_AggregationDescriptor_fields + 34 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC88F2 (_google_census_Distribution_fields + 34 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC899A (_google_census_View_fields + 48 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC8A0A (_google_census_Aggregation_fields + 76 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC89EE (_google_census_Aggregation_fields + 48 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC8A42 (_google_census_Metric_fields + 34 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/census.pb.o)
ld: warning: pointer not aligned at address 0xC9746 (_grpc_lb_v1_ClientStats_fields + 6 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/load_balancer.pb.o)
ld: warning: pointer not aligned at address 0xC97B6 (_grpc_lb_v1_LoadBalanceRequest_fields + 6 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/load_balancer.pb.o)
ld: warning: pointer not aligned at address 0xC97EE (_grpc_lb_v1_InitialLoadBalanceResponse_fields + 20 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/load_balancer.pb.o)
ld: warning: pointer not aligned at address 0xC980A (_grpc_lb_v1_ServerList_fields + 6 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/load_balancer.pb.o)
ld: warning: pointer not aligned at address 0xC9842 (_grpc_lb_v1_LoadBalanceResponse_fields + 20 from /Users/sibinlu/Library/Developer/Xcode/DerivedData/Token-dditkqeoomvjwmewxesvsblskwye/Build/Intermediates/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/load_balancer.pb.o) 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by combinatorial** [comment]
The same issue exists with Version 9.0 beta 6 (9M214v)
```
Using gRPC (1.6.0)
Using gRPC-Core (1.6.0)
Using gRPC-ProtoRPC (1.6.0)
Using gRPC-RxLibrary (1.6.0)
```

**Comment by combinatorial** [comment]
Firebase had a similar issue that they fixed... https://stackoverflow.com/questions/42268117/how-to-remove-the-xcode-warning-apple-mach-o-linker-warning-pointer-not-aligned

**Comment by combinatorial** [comment]
This can be fixed by uncommenting the line `#define PB_NO_PACKED_STRUCTS 1` in pb.h. It appears cocoapods is setting this preprocessor for the nanopb pod, but users of nanopb, e.g gRPC-Core, are not setting it.

**Comment by combinatorial** [comment]
I have also confirmed that adding `PB_NO_PACKED_STRUCTS=1` to `GCC_PREPROCESSOR_DEFINITIONS` in gRPC-Core.xcconfig fixes this. So, this needs to be added to the preprocessor defines in the podspec.

**Comment by muxi** [comment]
Fixed. To be release in v1.7.0
