### ISSUE TITLE
Feature Request: Add ability to specify trusted IP ranges

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#12190]
### What version of gRPC and what language are you using?
1.4.2 - C++ 
 
It'd be nice to be able to restrict the IP addresses that can access the server. Anything following outside would be rejected at socket connection level.

Thanks.

**Comment by cauthu** [comment]
hmm sounds like you want to set up some firewall rules?

**Comment by abaldeva** [comment]
Would it be possible to instead support it in the software? I'd like to avoid firewall rules if possible.

**Comment by cauthu** [comment]
I am not a grpc dev so I have no influence; it's just my opinion that this
functionality doesn't quite belong in grpc :)

(sent from phone)

**Comment by abaldeva** [comment]
Okay, thanks for the input. Closing the issue.
