### ISSUE TITLE
gRpc in node costs high CPU under high concurrency.

### ISSUE THREAD

**Issue by yunnysunny** [grpc/grpc#12215]
I use the newest version 1.4.1 in node. When I take benchmark , I find grpc cost much CPU time.

![the cpu profile](https://silian.whyun.com/images/profile.png)

**Comment by murgatroid99** [comment]
Can you provide more context for this data? What is the actual performance problem you were experiencing? Can you provide the benchmark you ran to gather this data? Is there a specific reason you have highlighted the `writeUtf8String` function?

**Comment by yunnysunny** [comment]
The reason of `writeUtf8String` is cased by high request of redis server. But the function of `cloneRaw`, which uses the most cpu time,  is cased by `protobufjs 5.0.2`, which is called by grpc. And the function of `Call` `Message` `MessagePrototype.set` is also used by grpc.
The cpu profile file is generated in my company's project, I can supply a benchmark , it may take some time to write a simple project to remove the detail of my company's code.

**Comment by yunnysunny** [comment]
I have written a project with node-grpc, hosted on [bench4grpc](https://github.com/yunnysunny/bench4grpc). For doing benchmark conveniently, I also create a jmeter project , hosted on [jmeter4grpc](https://github.com/yunnysunny/jmeter4grpc) . In fact, the jar file and jmx file, needed for the test, have been uploaded [here](https://silian.whyun.com/download/jmeter4grpc-0.0.1.jar) and [here](https://silian.whyun.com/download/grpc_bench.jmx).
I also uploaded a cpu profile file on [here](https://silian.whyun.com/download/20170911T194842.cpuprofile).

**Comment by yunnysunny** [comment]
I read the c++ addon code of node , and found that the `StartBatch` function of the `Call` class called  grpc's native function `grpc_call_start_batch` in a  synchronized way, which is show [here](https://github.com/grpc/grpc/blob/c3d8237b15322d3b80954349ed027152ce83f3eb/src/node/ext/call.cc#L724). This synchronized call will block the V8's main thread, I think it should be run in libuv's thread pool to reduce the competition of CPU between the main thread.

**Comment by dgquintas** [comment]
@murgatroid99 can this issue be closed or addressed somehow?

**Comment by yunnysunny** [comment]
@dgquintas Have you have changed the way of calling the function of grpc_call_start_batch in an asynchronous way?

**Comment by dgquintas** [comment]
`grpc_call_start_batch` is always asynchronous. See documentation [here](https://github.com/grpc/grpc/blob/de110af820a912ae926a1a9659a385b6a972f84d/include/grpc/grpc.h#L237).

**Comment by yunnysunny** [comment]
Yes, I have made a mistake. `grpc_call_start_batch` is  asynchronous actually. The cpu time is almost costed by protobuf's serialization and deserialization. I think this problem can not been avoided if grpc do encoding protobuf in pure js. 
Maybe parsing protobuf in native code ( such as the package [node-protobuf](https://www.npmjs.com/package/node-protobuf) ) is a better choice for performance,  but it will make project more complex.
