### ISSUE TITLE
The non-grpclb policies should treat balancer addresses as invalid input.

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12220]
The non-grpclb policies (round_robin and pick_first) should only see backend addresses as the input addresses, because grpclb policy will be used if there is any balancer addresses in the resolution. This new semantics is discussed in [#10258](https://github.com/grpc/grpc/pull/10258).

The current code ignores the balancers and keeps silent about that.

**Comment by AspirinSJL** [comment]
@markdroth Should we just remove the checking and filtering, or add assertions that there should not be balancer addresses?

**Comment by markdroth** [comment]
Given the new semantics of LB policy selection, these policies should never be selected if there are any balancer addresses, so I think it's fine to use an assertion.
