### ISSUE TITLE
Unknown constexpr on Visual Studio 2013

### ISSUE THREAD

**Issue by OgreTransporter** [grpc/grpc#12232]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
master(2017-08-20) 
 
### What operating system (Linux, Windows, …) and version?
Windows 7, Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2013 (Win7), Visual Studio 2015 (Win10)
 
### What did you do?
I try to build grpc with both versions of Visual Studio.
 
### What did you expect to see?
Build ok
 
### What did you see instead?
Visual Studio 2015 is working well, but 2013 is not working:

```
1>D:\Build\gRPC\src\include\grpc++/security/credentials.h(136): error C2144: Syntaxfehler: 'long' sollte auf ';' folgen
1>D:\Build\gRPC\src\include\grpc++/security/credentials.h(136): error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.
```
```C++
/// Constant for maximum auth token lifetime.
constexpr long kMaxAuthTokenLifetimeSecs = 3600;
```
And
```
10>D:\Build\gRPC\build\gens\src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h(50): error C2144: Syntaxfehler: 'const char' sollte auf ';' folgen
10>D:\Build\gRPC\build\gens\src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h(50): error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.
```
```C++
  static constexpr char const* service_full_name() {
```
 
### Anything else we should know about your project / environment?
The problem is ``constexpr``, which is unknown on VS below 2015. I've made the following fix:
```patch
diff --git a/include/grpc++/impl/codegen/config.h b/include/grpc++/impl/codegen/config.h
index b5ac9a752e..9e70ed74bd 100644
--- a/include/grpc++/impl/codegen/config.h
+++ b/include/grpc++/impl/codegen/config.h
@@ -38,4 +38,10 @@ using std::to_string;

 }  // namespace grpc

+#if defined(_MSC_VER)
+#if _MSC_VER < 1900 && !defined(constexpr)
+#define constexpr const
+#endif
+#endif
+
 #endif  // GRPCXX_IMPL_CODEGEN_CONFIG_H
```

**Comment by jtattermusch** [comment]
We will be getting rid of the pre-generated VS2013 projects here:
https://github.com/grpc/grpc/pull/11598

**Comment by OgreTransporter** [comment]
Yes, but generating the Visual Studio projects from CMake will not solve this issue, because ``constexpr`` is still missing. This is not a project property!

**Comment by jtattermusch** [comment]
@OgreTransporter along with #11598, we are also dropping official VS2013 support (it's 5 years old now and 2 newer stable versions are available: VS2015 and VS2017). Also, boringssl doesn't build with VS2013 which is making things more complicated.
