### ISSUE TITLE
Segfault in Python secure interop test on Mac

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#1224]
The only relevant output out of `tools/run_tests/run_tests.py -l python` is:
```
+ python2.7 -B -m interop._secure_interop_test
tools/run_tests/run_python.sh: line 39: 44139 Segmentation fault: 11  python2.7 -B $*
FAILED: tools/run_tests/run_python.sh [ret=139]
```

Just noting this here for now; may attempt to dig in later.

**Comment by nathanielmanistaatgoogle** [comment]
Remilestoning - we'd like to support gRPC-Python-on-MacOS shortly after Beta and long before General Availability but aren't considering it a hard Beta requirement.

**Comment by soltanmm** [comment]
I'm pretty sure that if anything like this appears again it'd be a new issue.
