### ISSUE TITLE
Add unit tests for protoc plugins

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1225]
The plugins in `src/compiler` are currently only tested by running the generated code. They should also be tested independently, probably by having golden files to compare with the output.

**Comment by soltanmm** [comment]
#635 ?

**Comment by yang-g** [comment]
From previous experience, I think at least the golden file approach does
not work very well.

**Comment by soltanmm** [comment]
@yang-g +1; I dislike the golden file approach as what we care about is functionality. Admittedly the current scheme Python employs in `src/test/compiler` isn't going to catch undesired _excess_ exposed API surface, but it's closer to what we care for functionally than golden files, IMO.

**Comment by yang-g** [comment]
A c++ golden file test was added.
#635 is closed so I am closing this as well.
