### ISSUE TITLE
Crashes during shutdown

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#12255]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
1.4.2 - C++ 
 
### What operating system (Linux, Windows, …) and version?
 Windows 7.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2015 Update 3 
 
### What did you do?
**Server setup**
One thread dedicated to picking events from the completion queue and another thread processes it. The thread responsible for processing also shuts down the server when required.

Set GRPC_ARG_MAX_CONNECTION_IDLE_MS to 1 hour and set GRPC_ARG_MAX_CONNECTION_AGE_MS to (INT_MAX - 1)

**Client setup**
3 client threads using sync api and infinite timeout (default). Threads repeatedly call a number of rpcs in a never ending loop. 

After letting it run for few minutes, exited client process and then called a graceful shutdown on the server. 
### What did you expect to see?
Server shutdown gracefully. 
 
### What did you see instead?
Server crashed randomly (not always). 2 out of 3 times. 

See the attached screenshot with various relevant variables and callstack.
**Crash 1**
![crash](https://user-images.githubusercontent.com/24324277/29590437-a9745ae6-874e-11e7-945a-b72e2a86108b.jpg)

**Crash 2**
![crash2](https://user-images.githubusercontent.com/24324277/29590789-66f42bb8-8750-11e7-9331-f8a92d64c23a.jpg)

**Comment by abaldeva** [comment]
I have a hunch that the crashes are related to setting up GRPC_ARG_MAX_CONNECTION_IDLE_MS and GRPC_ARG_MAX_CONNECTION_AGE_MS explicitly. If I don't set them, I am unable to repro the issues.

**Comment by abaldeva** [comment]
Hi,

Was wondering if you have had a chance to look at it?

Thanks.

**Comment by abaldeva** [comment]
Hi,

I updated today to 1.7.x. Unfortunately, this issue is still present and much worst. After enabling the  GRPC_ARG_MAX_CONNECTION_IDLE_MS, the server barely runs for few seconds before crashing.

If the resources can't be cleaned up properly, it is a blocker for prod usage of grpc. For such a critical bug to hang on for so long, I am not sure if you are not able to reproduce or I have something different as a set up.

Thanks.

**Comment by thisisnotapril** [comment]
@y-zeng can you see the update here from Arpit and advise? thanks!

**Comment by hsaliak** [comment]
@abaldeva a working repro would definitely help move things along. Would you have something handy?

**Comment by yashykt** [comment]
is this still seen?

**Comment by abaldeva** [comment]
This was fixed in some other bug. Can be closed. Thanks.
