### ISSUE TITLE
Handshake read failed security_handshaker.c:126 (php client)

### ISSUE THREAD

**Issue by yaronsumel** [grpc/grpc#12250]
Hey..
Trying to communicate with my service with php client (same service works for the golang client)
Can't make it work.. already tried exporting the cipher suites 
```
export GRPC_SSL_CIPHER_SUITES=ECDHE-ECDSA-AES256-GCM-SHA384
```

```php
uire dirname(__FILE__).'/vendor/autoload.php';
 $client = new \Productpb\ProductServiceClient('localhost:3051', [
     'credentials' => Grpc\ChannelCredentials::createSsl(file_get_contents(dirname(__FILE__).'/client.com.pem'))
 ]);
$request = new Productpb\GetRequest();
$request->SetId("123");
var_dump($client->Get($request)->wait());
```

```bash
I0822 15:05:47.946677000    2059 ev_epollsig_linux.c:90]     epoll engine will be using signal: 40
D0822 15:05:47.947273600    2059 ev_posix.c:121]             Using polling engine: epollsig
D0822 15:05:47.947675000    2059 dns_resolver.c:316]         Using native dns resolver
I0822 15:05:48.041374600    2061 ssl_transport_security.c:184]      HANDSHAKE START -  before connect initialization  - CINIT
I0822 15:05:48.041807600    2061 ssl_transport_security.c:184]                 LOOP -  before connect initialization  - CINIT
I0822 15:05:48.042218500    2061 ssl_transport_security.c:184]                 LOOP -     SSLv3 write client hello A  - 3WCH_A
I0822 15:05:48.042570400    2061 ssl_transport_security.c:184]                 LOOP -               SSLv3 flush data  - 3FLUSH
D0822 15:06:08.043073400    2060 security_handshaker.c:126]  Security handshake failed: {"created":"@1503403568.042903200","description":"Handshake read failed","file":"/tmp/pear/temp/grpc/src/core/lib/security/transport/security_handshaker.c","file_line":304,"referenced_errors":[{"created":"@1503403568.042655500","description":"FD Shutdown","file":"/tmp/pear/temp/grpc/src/core/lib/iomgr/lockfree_event.c","file_line":197,"referenced_errors":[{"created":"@1503403568.042643600","description":"Handshake timed out","file":"/tmp/pear/temp/grpc/src/core/lib/channel/handshaker.c","file_line":241}]}]}
I0822 15:06:08.050053700    2060 subchannel.c:707]           Connect failed: {"created":"@1503403568.042903200","description":"Handshake read failed","file":"/tmp/pear/temp/grpc/src/core/lib/security/transport/security_handshaker.c","file_line":304,"referenced_errors":[{"created":"@1503403568.042655500","description":"FD Shutdown","file":"/tmp/pear/temp/grpc/src/core/lib/iomgr/lockfree_event.c","file_line":197,"referenced_errors":[{"created":"@1503403568.042643600","description":"Handshake timed out","file":"/tmp/pear/temp/grpc/src/core/lib/channel/handshaker.c","file_line":241}]}]}
I0822 15:06:08.050647900    2060 subchannel.c:501]           Retry immediately
I0822 15:06:08.051041400    2060 subchannel.c:453]           Failed to connect to channel, retrying
I0822 15:06:08.052902600    2060 ssl_transport_security.c:184]      HANDSHAKE START -  before connect initialization  - CINIT
I0822 15:06:08.054668900    2060 ssl_transport_security.c:184]                 LOOP -  before connect initialization  - CINIT
I0822 15:06:08.055249200    2060 ssl_transport_security.c:184]                 LOOP -     SSLv3 write client hello A  - 3WCH_A
I0822 15:06:08.056089100    2060 ssl_transport_security.c:184]                 LOOP -               SSLv3 flush data  - 3FLUSH
array(2) {
  [0]=>
  NULL
  [1]=>
  object(stdClass)#376 (3) {
    ["metadata"]=>
    array(0) {
    }
    ["code"]=>
    int(14)
    ["details"]=>
    string(14) "Connect Failed"
  }
}
D0822 15:06:08.094558300    2059 security_handshaker.c:126]  Security handshake failed: {"created":"@1503403568.094424700","description":"Handshake read failed","file":"/tmp/pear/temp/grpc/src/core/lib/security/transport/security_handshaker.c","file_line":304,"referenced_errors":[{"created":"@1503403568.094149800","description":"FD Shutdown","file":"/tmp/pear/temp/grpc/src/core/lib/iomgr/lockfree_event.c","file_line":197,"referenced_errors":[{"created":"@1503403568.094134800","description":"Subchannel disconnected","file":"/tmp/pear/temp/grpc/src/core/ext/filters/client_channel/subchannel.c","file_line":274}]}]}
```

**Comment by stanley-cheung** [comment]
Which version of the gRPC PHP extension are you using? `php --re grpc | head -1`

Does this work with a previous version of the gRPC PHP extension, for example 1.4.1, or 1.3.2?

**Comment by yaronsumel** [comment]
Version used 1.4.4 
grpc-1.4.1 => same
grpc-1.4.1+GRPC_SSL_CIPHER_SUITES => same
grpc-1.3.2 => same
grpc-1.3.2 +GRPC_SSL_CIPHER_SUITES=> same

**Comment by yaronsumel** [comment]
same with 1.4.6

**Comment by stanley-cheung** [comment]
@jboeuf Can you please take a look at this issue? Thanks

**Comment by jtattermusch** [comment]
@ZhouyihaiDing  do you wanna take a look?

**Comment by ZhouyihaiDing** [comment]
Can you please help me provide more information about how to reproduce it? For the "Handshake read failed", since I haven't reproduce it, I am not sure setting "grpc.initial_reconnect_backoff_ms" will help or not.

I add credential files under src/php/tests/data/ca.pem to the helloworld example with go-server and php-client.  And it works well using the grpc-1.4.1 and grpc-1.4.6 installed by pecl.

Add credentials to example/helloworld/greeter_server/main.go:
```
creds, err := credentials.NewServerTLSFromFile(
	"grpc/src/php/tests/data/server1.pem",
	"grpc/src/php/tests/data/server1.key")
sopts := []grpc.ServerOption{}
sopts = append(sopts, grpc.Creds(creds))
s := grpc.NewServer(sopts...)
```
Add credentials to example/php/greeter_client.php:
```
$client = new Helloworld\GreeterClient('localhost:50051', [
    "credentials" => Grpc\ChannelCredentials::createSsl(
        file_get_contents(dirname(__FILE__).'/../../src/php/tests/data/ca.pem')),
    "grpc.ssl_target_name_override" => "x.test.youtube.com",
]);
```

**Comment by wanderhelen** [comment]
@Yaron Sumel 
                       Is your problem solved? I am facing this problem right now

**Comment by wanderhelen** [comment]
here‘s my code
			public function saveRepairCase($user_addr,$desc,$hash) {
			try {
				$client = new Blockchain\UserClient($this->block_url, [
						'credentials' => Grpc\ChannelCredentials::createSsl($this->ssl_roots)
				]);
				$SetDiagnosticRequest = new Blockchain\SetDiagnosticRequest();
				$SetDiagnosticRequest->setAddr($user_addr);
				$SetDiagnosticRequest->setDesc($desc);
				$SetDiagnosticRequest->setHash($hash);
				list($reply, $status) = $client->SetDiagnostic($SetDiagnosticRequest)->wait();
				return $reply->getResult();
			} catch (Exception $e) {
				return $e->getMessage();
			}
		}

I have also add "grpc.ssl_target_name_override" but it isn't work.

array(2) {
	[0] => NULL[1] => object(stdClass) #391 (3) { ["metadata"]= > array(0) {}["code"] => int(14)["details"] => string(14)
	"Connect Failed"
}

**Comment by wanderhelen** [comment]
it runs well in the terminal by command line and wrong when through the browser with nginx

**Comment by ZhouyihaiDing** [comment]
Hi @wanderhelen ,
Is your issue the same as "TCP handshake failed"? When you do export `GRPC_TRACE=tcp`, can you observe error `subchannel.cc:683]          Connect failed: `?
Can you please provide me a simple code how to reproduce it?
Thanks!

**Comment by wanderhelen** [comment]
Hi @ZhouyihaiDing , thank you for your answer.
I follow in the deep code 
    public function wait()
    {
        $batch = [
            OP_RECV_MESSAGE => true,
            OP_RECV_STATUS_ON_CLIENT => true,
        ];
        if ($this->metadata === null) {
            $batch[OP_RECV_INITIAL_METADATA] = true;
        }
        $event = $this->call->startBatch($batch);
        if ($this->metadata === null) {
            $this->metadata = $event->metadata;
        }
        $status = $event->status;
        $this->trailing_metadata = $status->metadata;

        return [$this->_deserializeResponse($event->message), $status];
    }


$event = $this->call->startBatch($batch);  the error is here , return value $event shows 
object(stdClass) #12 (3) { ["message"]= > NULL["status"] => object(stdClass) #391 (3) { ["metadata"]= > array(0) {}["code"] => int(14)["details"] => string(14)
"Connect Failed"
}["metadata"] => array(0) {}
}

I think you can try to reproduce as beflow:
run you php code through the web browser like firfox or google chrome not in the console

I  add GRPC_TRACE=tcp in the file /etc/profile,but I don't kown where to observe more detail.

**Comment by ZhouyihaiDing** [comment]
It sounds strange php scripts works on terminal but fails on browser. I see you mention that your browser also uses nginx. In you tests in terminal, do you also try to go through nginx? Since gRPC uses HTTP/2 as transport, I think handshake failure happens in nginx, related to issue [#11427](https://github.com/grpc/grpc/issues/11427).

**Comment by wanderhelen** [comment]
Hi @ZhouyihaiDing , Think you for your suggest.
I have read the issue #11427. it suggests to configure nginx to support http2.
I have done that and now the browser shows that the request is under http2, but is still meet "Connect Failed"
Do you know any projects or cases about grpc  which run php or other language through nginx success fully?

**Comment by wanderhelen** [comment]
My problem has  been solved.It is caused by system environment variable which PHP process can't  read it when runs by nginx.

**Comment by aceini** [comment]
I have the same problem, please explain how to solve it, what system environment variable did you change?

**Comment by ZhouyihaiDing** [comment]
Hi @aceini ,

Can you give us more information about in which environment and how you get the handshake error. An example of how to reproduce it will be the best! 

Are you also running it with nginx? If so, you may have the same issue like @ wanderhelen.

Thank you!

**Comment by ndeet** [comment]
Hi,
also had this problem with connecting to Go 1.10 lnd node. I set the env variable. Would be great if those stronger suites are set by default. (grpc version used 1.9.0)
```
// We need to set env variable for GRPC to make ssl work:
putenv('GRPC_SSL_CIPHER_SUITES=ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256');
```
