### ISSUE TITLE
timer thread crash

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#12257]
Same set up as https://github.com/grpc/grpc/issues/12255 .

except this time I set GRPC_ARG_MAX_CONNECTION_IDLE_MS to be 15 seconds.

After few minutes, crashed here.
![crash3](https://user-images.githubusercontent.com/24324277/29593696-c419755e-8760-11e7-8121-6f5f2e446bbc.jpg)

**Comment by yashykt** [comment]
is this still seen?
A simple repro case would go a long way in fixing this.

**Comment by abaldeva** [comment]
Fixed with #13594
