### ISSUE TITLE
Ruby client waits for ready when channel is in TRANSIENT_FAILURE state

### ISSUE THREAD

**Issue by grantr** [grpc/grpc#12272]
The Ruby client seems to be waiting for ready when channels are in a failure state, contrary to the advice given in https://github.com/grpc/grpc/blob/ff83681cbb4296dba3dcd92aaba27cba494a934a/doc/wait-for-ready.md.

### Should this be an issue in the gRPC issue tracker?

Yes, it's a bug.
 
### What version of gRPC and what language are you using?
 
gRPC Ruby 1.4.5
 
### What operating system (Linux, Windows, …) and version?
 
 MacOS 10.12.5

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
  Ruby 2.3.1p112

### What did you do?

Created a stub pointing to an invalid host and attempted several requests. The first request times out, putting the channel in `TRANSIENT_FAILURE` state.
 
### What did you expect to see?
 
I expect requests sent while the channel is in `TRANSIENT_FAILURE` state to fail immediately according to the default wait for ready semantics.
 
### What did you see instead?
 
All requests fail only after the deadline is reached, even those sent while the channel is in `TRANSIENT_FAILURE` state. See https://github.com/grantr/grpc-ruby-wait-for-ready for a test case.

**Comment by apolcyn** [comment]
Indeed it looks like failed <i>name resolution</i> doesn't appear to follow the value of the `wait_for_ready` flag. (name resolution appears to continue to retry queries even though `wait_for_ready` is false).

I'd note that name resolution failures look like a special case here though - if the channel's target <i>has</i> been resolved and the connection sees `TRANSIENT_FAILURE`, then the `wait_for_ready` flag does appear to be respected and the RPC does appear to fail immediately.

How severe is this bug for you?

cc @ejona86, who might have a better idea of proper behavior in this failed-name-resolution case.

**Comment by grantr** [comment]
Good to know @apolcyn, thanks for looking into it!

> How severe is this bug for you?

We can work around it with circuit breakers. We'd use those anyway in hot paths, so it's not a huge deal for us, but it could cause problems for anyone not using circuit breakers and expecting that fail-fast applies to DNS resolution failures.

**Comment by ejona86** [comment]
The name resolution is supposed to be attempted, but if it fails then a wait_for_ready=false RPC should fail. Name resolution can continue retrying in the background, though.

**Comment by markdroth** [comment]
This looks like a dup of #13627, which is fixed, so I suspect this is fixed as well.  Please re-open if you're still seeing this problem.
