### ISSUE TITLE
Permission denied for grpc-precompiled-binaries/node/grpc/v1.2.4/node-v48-linux-arm.tar.gz

### ISSUE THREAD

**Issue by arkandas** [grpc/grpc#12276]
Getting error 403 for https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.2.4/node-v48-linux-arm.tar.gz

```
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.2.4/node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.2.4 and node@6.11.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
```

Querying the file I get the following message:
`Anonymous users does not have storage.objects.get access to grpc-precompiled-binaries/node/grpc/v1.2.4/node-v48-linux-arm.tar.gz
`

It is clearly a permission problem, but I'm sure anonymous users should have permission to download the v1.2.4/node-v48-linux-arm.tar.gz file as it is required by the npm package I'm trying to install.

**Comment by murgatroid99** [comment]
That message is misleading; the file actually doesn't exist at all. The actual issue there is that Node gRPC did not support ARM platforms until version 1.4.1. If you can't upgrade the version yourself, I would recommend asking the maintainer of the package you're trying to install to upgrade their dependency.

**Comment by arkandas** [comment]
Thank you very much, that is what I imagined happened after reading other issues. 
The solution for me was to compile the latest version, modify the package dependencies and install manually, now everything works perfectly.
