### ISSUE TITLE
[ruby] grpc hangs under unicorn

### ISSUE THREAD

**Issue by yancl** [grpc/grpc#1229]
Several days ago, my colleague write a service using ruby with `grpc`,it works well. But, today, when we integrate it with unicorn and make requests, it doesn't work anymore. it just hangs there with no network request.

After a dig of the code,we found unicorn first load ruby gems and then fork several sub processes to process requests.

But this is not compatible with grpc ruby, because the `require grpc` action in unicorn master process do the init job,mainly including create two worker threads, one is for polling i/o and another for completion callback. And the unicorn forked process already have no relation with the master's polling&callback threads, they are in different address space. so when the forked unicorn worker make requests, there is no i/o worker do the job anymore.

```c
void Init_grpc() {
  grpc_init();
  ...
}
//grpc/src/ruby/ext/grpc/rb_grpc.c
```

The above codes executes when we `require grpc`,so what is your suggest for this scene?
supply a `init_grpc` for us to call it directly in the forked subprocesses or lazy require ruby gems?

thanks

**Comment by tbetbetbe** [comment]
> supply a init_gprc for us to call it directly in the forked subprocess or lazy require ruby gems ?

For forking, we recommend you lazily load the grpc ruby gem.
I.e, 'require grpc' should happen after the fork
Is that something that's hard to do on unicorn ?

**Comment by yancl** [comment]
Thanks,tbetbetbe. 
We lazily load the grpc ruby gem after fork now:)

**Comment by tbetbetbe** [comment]
That's good news - I'm glad that's worked for you!
