### ISSUE TITLE
Design gRPC API for C#

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#123]
The API review process is in progress.

go/grpc-csharp-public-api

**Comment by Kavignon** [comment]
Did someone start to work on this ?
If I get it right, I'd need to understand the architecture of grpc and try to make it work for C# ?

**Comment by jtattermusch** [comment]
Hi,

for some reason, I doesn't seem your comment was added to the issue,
strange.

Currently we have a pre-alpha version of C# gRPC API and you can do both
unary and streaming calls using C#. We support both client and server for
C#, but there is still some things that are missing before gRPC C# is fully
usable.

**Comment by jtattermusch** [comment]
#1422

**Comment by jtattermusch** [comment]
Closing this because it turns out to be too high-level. Progress will be tracked by issues with smaller granularity.
