### ISSUE TITLE
compiler error :No syntax specified for the proto file

### ISSUE THREAD

**Issue by xxllp** [grpc/grpc#12302]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpc1.4 +python 
 
### What operating system (Linux, Windows, …) and version?
 linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 python -m grpc_tools.protoc -I . --python_out= . --grpc_python_out=. test.proto

 
### What did you see instead?
 

[libprotobuf WARNING third_party/protobuf/src/google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: . Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING third_party/protobuf/src/google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: test.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
--grpc_python_out: : Invalid proto file name. Proto file must end with .proto

**Comment by nathanielmanistaatgoogle** [comment]
Looks like some spaces have been erroneously entered into your `grpc_tools.protoc` invocation. Does changing
```
python -m grpc_tools.protoc -I . --python_out= . --grpc_python_out=. test.proto
```
to
```
python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. test.proto
```
help at all?
