### ISSUE TITLE
sync server thread count limit

### ISSUE THREAD

**Issue by tjb1216** [grpc/grpc#12317]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
yes
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.4.1  c++
 
### What operating system (Linux, Windows, …) and version?
 linux  centos 6.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I have tested on sync server, when in high load, the number of threads rose sharply, could be more than 4000, it's horrible for a online server when each thread hold some instance.
 
### What did you expect to see?
 The number of threads should be limited strictly.
 
### What did you see instead?
The number of threads exceed NUM_CQS * MAX_POLLERS Very exaggerated！
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
no

**Comment by tjb1216** [comment]
I set the NUM_CQS = the num of cpus, MIN_POLLERS=1 and MAX_POLLERS=2

**Comment by vjpai** [comment]
Variant of #12472. Closing this in favor of that since that's the tracking bug for the feature.
