### ISSUE TITLE
Investigate drop in async streaming qps benchmarks for C++

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#12319]
Please answer these questions before submitting your issue. 
 
## What version of gRPC and what language are you using?
 latest/master
 
### What operating system (Linux, Windows, …) and version?
 Linux - test infra
 
### What did you do?

 https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584
(bigquery can be used to query for a longer time period that will show this problem better)

and 
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5632763172487168&widget=1783526579&container=1012810333&maximized

indicate a drop in streaming qps performance but this is not verifiable locally.
### What did you expect to see?
- Reproducible benchmarks that we can use to pin down root cause. However, we have not been able to isolate this issue to a PR or explain it when running locally, so we need to determine if this is an issue, potentially replicate results from before and after and explain the drop.

@adelez would you be able to look into this?

**Comment by adelez** [comment]
Some update from my experiment:
I tried adhoc test with the latest commit, a commit on 8/21 and a commit on 8/17, all QPS numbers are close to what the dashboard shows in the last couple of days, i.e. between 1M and 1.4M qps. 
Before 8/19, it was around 2M qps. Between 8/19 and 8/22, it dropped to <1M. 

Note that 8core tests also started to show large curves.

**Comment by adelez** [comment]
After talk with @a11r , it's decided not worth further investigation based on the above facts.
