### ISSUE TITLE
grpclb in C core doesn't seem to work as expected.

### ISSUE THREAD

**Issue by wuweiplus** [grpc/grpc#12330]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes

### What version of gRPC and what language are you using? 
 gRPC version: v1.6.0 (I also tested *master*)
 gRPC-go version: v1.5.2
 language: client (C++), server (Go), grpclb (Go)
 
### What operating system (Linux, Windows, …) and version?
 macOS Sierra 10.12
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 C++:
    Apple LLVM version 8.1.0 (clang-802.0.38)
    Target: x86_64-apple-darwin16.0.0
    Thread model: posix
 Go:
    1.9
 Environment variables:
    GRPC_DNS_RESOLVER=ares
    GRPC_VERBOSITY=DEBUG
    GRPC_TRACE=glb

### What did you do?

0. Simply modify [grpc/example/cpp/helloworld/greeter_client.cc](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_client.cc)
```cpp
int main(int argc, char** argv) {
  grpc::ChannelArguments arg;
  arg.SetLoadBalancingPolicyName("grpclb");
  const char *target = "example.52tt.local";
  GreeterClient greeter(grpc::CreateCustomChannel(
    target, grpc::InsecureChannelCredentials(), arg));

  std::mutex m;
  int i = 0;
  auto block = [&] () {
    i++;
    char name[128] = { 0 };
    snprintf(name, sizeof(name), "world %d", i);
    std::string user(name);
    std::string reply = greeter.SayHello(user);

    std::lock_guard<std::mutex> guard(m);
    std::cout << "Greeter received: " << reply << std::endl;
  };

  while (true) {
    std::thread t1(block);
    t1.join();

    sleep(3);
  }

  return 0;
}
```

1. Setup DNS and Load Balancer:

Following the [grpclb in dns proposal](https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md), I setup a DNS service with [SkyDNS](https://github.com/skynetservices/skydns), and a simple service discovery with [etcd](https://github.com/coreos/etcd)

URL for test server and LB are:
a) example.52tt.local, which is a backend server implements [examples/protos/helloworld.proto](https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto)
b) lb.52tt.local, which is a gRPC load balancer implements [grpc/lb/v1/load_balancer.proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/lb/v1/load_balancer.proto).

LB accepts *BalanceLoad* request, resolves name to backend addresses (from etcd, watches the updates, and reply a server list to client (In my testcase, I send server list to client every 15 seconds).

```go
func (b *balancer) BalanceLoad(s lbpb.LoadBalancer_BalanceLoadServer) error {
	req, err := s.Recv()
	if err != nil {
		log.Errorln("[balancer] Unable to recv InitialRequest:", err)
		return err
	}

	initReq := req.GetInitialRequest()
	if initReq == nil {
		log.Errorln("[balancer] Bad stream, first request must be InitialRequest")
		return nil
	}

	target := initReq.GetName()
	resp := &lbpb.LoadBalanceResponse{
		LoadBalanceResponseType: &lbpb.LoadBalanceResponse_InitialResponse{
			InitialResponse: &lbpb.InitialLoadBalanceResponse{
				LoadBalancerDelegate: "",
				ClientStatsReportInterval: &lbpb.Duration{
					Seconds: int64(b.statsDura.Seconds()),
					Nanos:   int32(b.statsDura.Nanoseconds() - int64(b.statsDura.Seconds())*1e9),
				},
			},
		},
	}

	if err = s.Send(resp); err != nil {
		log.Errorf("[balancer] Unable to send InitialResponse: %v, err %v", resp, err)
		return err
	}

	sw, err := b.resolve(target)
	if err != nil {
		log.Errorf("[balancer] Unable to send InitialResponse: %v, err %v", resp, err)
		return err
	}

	// client stats report
	go b.handleClientStatsReports(s)

	if sls := sw.copyServerList(); len(sls) > 0 {
		err := b.sendServerList(s, sls)
		if err != nil {
			log.Errorf("[balancer] Unable to send server list: %v", err)
			return err
		}
		log.Debugf("[balancer] Sent server list, target: %s, sls: %v", target, sls)
	} else {
		log.Warnf("[balancer] target %s, no available endpoints", target)
	}

	ticker := time.NewTicker(time.Second * 15)
Loop:
	for {
		select {
		case <-s.Context().Done():
			log.Debugf("[balancer] Context done: %v", s.Context().Err())
			break Loop
		case <-ticker.C:
			if sls := sw.copyServerList(); len(sls) > 0 {
				err := b.sendServerList(s, sls)
				if err != nil {
					log.Errorf("[balancer] Failed to send server list: %v", err)
					return err
				}
				log.Debugf("[balancer] Sent server list, target %s, sls: %v", target, sls)
			} else {
				log.Warnf("[balancer] target %s, no available endpoints", target)
			}
		}
	}
	return nil
}
```

> Note: the LB always send all registered backend addresses to client.

And refer to the source code in [grpclb.c](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.c), the client will create subchannels to each backends and pickup one from them with *RoundRobin* policy to call each RPC.

Below is the my skydns config and the result of dns lookup:
>  ~/ etcdctl  get --prefix /skydns
```
/skydns/local/52tt/example/_tcp/_grpclb
{"host":"lb.52tt.local","port":9999}
/skydns/local/52tt/lb
{"host": "192.168.8.80", "port": 9999}
```
>  ~/ dig SRV _grpclb._tcp.example.52tt.local
```
; <<>> DiG 9.8.3-P1 <<>> SRV _grpclb._tcp.example.52tt.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53641
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;_grpclb._tcp.example.52tt.local. IN	SRV

;; ANSWER SECTION:
_grpclb._tcp.example.52tt.local. 3600 IN SRV	10 100 9999 lb.52tt.local.

;; ADDITIONAL SECTION:
lb.52tt.local.		3600	IN	A	192.168.8.80
```
2. Start 3 backends;

Then I start 3 *example server*s and register them to etcd.
```
A: 192.168.8.80:50051
B: 192.168.8.80:50052
C: 192.168.8.80:50053
```

>  ~/ etcdctl get --prefix example.52tt.local
```
example.52tt.local/192.168.8.80:50051
{"Op":0,"Addr":"192.168.8.80:50051","Metadata":null}
example.52tt.local/192.168.8.80:50052
{"Op":0,"Addr":"192.168.8.80:50052","Metadata":null}
example.52tt.local/192.168.8.80:50053
{"Op":0,"Addr":"192.168.8.80:50053","Metadata":null}
```

LB is now able to resolve *example.52tt.local* to 3 backend addresses, and send them to client periodically.

3. Run an instance of greeter_client;
In this situation, grpclb and RR work as expected, all the are requests well-distributed to all three backends.

```
I0830 17:23:41.232431000 123145311817728 grpclb.c:1449]                Query for backends (grpclb: 0x7fdad3500980, lb_channel: 0x7fdad3501c00, lb_call: 0x7fdad5000b58)
I0830 17:23:41.232972000 123145311817728 grpclb.c:1560]                received initial LB response message; client load reporting interval = 60.000000000 sec
I0830 17:23:41.233001000 123145311817728 grpclb.c:1585]                Serverlist with 3 servers received
I0830 17:23:41.233008000 123145311817728 grpclb.c:1592]                Serverlist[0]: [::ffff:192.168.8.80]:50051
I0830 17:23:41.233013000 123145311817728 grpclb.c:1592]                Serverlist[1]: [::ffff:192.168.8.80]:50053
I0830 17:23:41.233016000 123145311817728 grpclb.c:1592]                Serverlist[2]: [::ffff:192.168.8.80]:50052
I0830 17:23:41.233093000 123145311817728 grpclb.c:588]                 Setting grpclb's state to IDLE from new RR policy 0x7fdad3600630 state.
```

4. Start a new backend *D*: 192.168.8.80:50054;
5. Restart backend *C*;
6. Restart backend *B*;
7. Restart backend *A*.

### What did you expect to see?
 
4. Start a new backend *D*: 192.168.8.80:50054
New backend will register to LB, and LB send new server list to client.
Client creates new RR policy, and pending 1/4 requets should be sent to backend *D*.

5. Restart backend *C*;
After *C* stops, clients should send requests to A, B, D (1/3 requests to each).
After *C* restarts, clients should send requests to A, B, C, D (1/4 requests to each).

6. Restart backend *B*;
After *B* stops, clients should send requests to A, C, D (1/3 requests to each).
After *B* restarts, clients should send requests to A, B, C, D (1/4 requests to each).

7. Restart backend *A*.
After *A* stops, clients should send requests to B, C, D  (1/3 requests to each).
After *B* restarts, clients should send requests to A, B, C, D (1/4 requests to each).

### What did you see instead?

4. Start a new backend *D*: 192.168.8.80:50054
LB receive the update from etcd, and send new server list (including A,B,C,D) to the client,
BUT **No request is sent to *D*.**
Indeed, [the grpclb policy is expected to keep listening the change of server list.](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.c#L1632)
```C
if (!glb_policy->shutting_down) {
      /* keep listening for serverlist updates */
      op->op = GRPC_OP_RECV_MESSAGE;
      op->data.recv_message.recv_message = &glb_policy->lb_response_payload;
      op->flags = 0;
      op->reserved = NULL;
      op++;
      /* reuse the "lb_on_response_received_locked" weak ref taken in
       * query_for_backends_locked() */
      const grpc_call_error call_error = grpc_call_start_batch_and_execute(
          exec_ctx, glb_policy->lb_call, ops, (size_t)(op - ops),
          &glb_policy->lb_on_response_received); /* loop */
      GPR_ASSERT(GRPC_CALL_OK == call_error);
    }
```
But according the trace logs, I didn't see *glb_policy* receive any server list responses.

5. Restart backend *C*.
Once I stop *C*, one RPC fails with code 14: Endpoint read failed, but all the pending requests are well-distributed to the other *A* and *B*. 
BUT after I restart *C*, **No request is sent to *C*.**

6. Restart backend *B*:
Once I stop *B*, one RPC fails with code 14: Endpoint read failed, but all the pending requests are all sent to *A*.
BUT after I restart *B*, **No request is sent to *B*.**

**By now, there are 4 backends (A, B, C, D) running and well registered, but only backend *A* receives all the requests.**

7. Restart backend *A*:
Once I restart *A*,  one RPC fails with code 14: Endpoint read failed, the RR policy becoming unavailable and client suddenly receives all the *BalanceLoadResponse* with *ServerList* sent from LB server, and then all the 4 backends begin to handle request as expected.
```
D0830 18:01:10.169154000 123145534410752 grpclb.c:1212]                No RR policy in grpclb instance 0x7fc16df00910. Adding to grpclb's pending picks
I0830 18:01:10.169265000 123145534410752 grpclb.c:1585]                Serverlist with 3 servers received
I0830 18:01:10.169274000 123145534410752 grpclb.c:1592]                Serverlist[0]: [::ffff:192.168.8.80]:50051
I0830 18:01:10.169279000 123145534410752 grpclb.c:1592]                Serverlist[1]: [::ffff:192.168.8.80]:50052
I0830 18:01:10.169282000 123145534410752 grpclb.c:1592]                Serverlist[2]: [::ffff:192.168.8.80]:50053
I0830 18:01:10.169286000 123145534410752 grpclb.c:1601]                Incoming server list identical to current, ignoring.
I0830 18:01:10.169298000 123145534410752 grpclb.c:1585]                Serverlist with 4 servers received
I0830 18:01:10.169303000 123145534410752 grpclb.c:1592]                Serverlist[0]: [::ffff:192.168.8.80]:50051
I0830 18:01:10.169309000 123145534410752 grpclb.c:1592]                Serverlist[1]: [::ffff:192.168.8.80]:50052
I0830 18:01:10.169313000 123145534410752 grpclb.c:1592]                Serverlist[2]: [::ffff:192.168.8.80]:50053
I0830 18:01:10.169338000 123145534410752 grpclb.c:1592]                Serverlist[3]: [::ffff:192.168.8.80]:50054
I0830 18:01:10.169458000 123145534410752 grpclb.c:588]                 Setting grpclb's state to IDLE from new RR policy 0x7fc16dd01fb0 state.
I0830 18:01:10.169630000 123145534410752 grpclb.c:753]                 Pending pick about to (async) PICK from 0x7fc16dd01fb0
D0830 18:01:10.169638000 123145534410752 grpclb.c:792]                 Created new Round Robin policy (0x7fc16dd01fb0)
I0830 18:01:10.169650000 123145534410752 grpclb.c:588]                 Setting grpclb's state to CONNECTING from new RR policy 0x7fc16dd01fb0 state.
............
```
 
So, as I have observed, all the new started backends (including restart) can be properly registered to LB, but the client (glb_policy) **can not** get the new server list **UNTIL** I stop the last backend.

**Comment by tjb1216** [comment]
I'm interested in it, MARK!

**Comment by markdroth** [comment]
I'm not sure why it's not behaving properly when you add a new backend.  You say that the balancer sent the new serverlist to the client but that the client did not receive it, but I don't see how both those statements can be true -- I think one of them must be incorrect.  Do you see the client receiving subsequent updates from the balancer in any of the other scenarios?

I believe that the problem with restarting backends is the issue described in #11643, which David is currently working on fixing.

**Comment by wuweiplus** [comment]
Thanks for addressing this.

> You say that the balancer sent the new serverlist to the client but that the client did not receive it, but I don't see how both those statements can be true -- I think one of them must be incorrect.
It's better to say, the balancer wrote the new serverlist to the stream, but I don't know why the client didn't receive the subsequent updates (It's a bit hard for me the read the C code in gRPC core).

I've updated the implementation of the balancer that once a new backend registers, it writes the new servelist to the stream (instead of sending periodically).

I ran a new test, and what I see is that the client do not receive the updates from the balancer until all the subchannels are failed.

Starting with no backend, then a start up a client, it sent LoadBalanceRequest to the balancer.
``` 
WARN[0749] [balancer] target example.52tt.local, no available endpoints
```
Then I started a backend, the balancer sent the new serverlist to client and the client received that, it was behaving as expected.

```balancer
INFO[1206] [watcher] example.52tt.local add new addr 192.168.8.80:50051
DEBU[1206] [balancer] Sent server list, target example.52tt.local, sls: [ip_address:"\000\000\000\000\000\000\000\000\000\000\377\377\300\250\010P" port:50051 load_balance_token:"192.168.8.80:50051_1505356819" ]
```

```client
I0914 10:40:19.193187000 123145436954624 grpclb.c:1585]                Serverlist with 1 servers received
I0914 10:40:19.193206000 123145436954624 grpclb.c:1592]                Serverlist[0]: [::ffff:192.168.8.80]:50051
I0914 10:40:19.193260000 123145436954624 grpclb.c:588]                 Setting grpclb's state to IDLE from new RR policy 0x7f9b2e6000c0 state.
I0914 10:40:19.193327000 123145436954624 grpclb.c:753]                 Pending pick about to (async) PICK from 0x7f9b2e6000c0
D0914 10:40:19.193334000 123145436954624 grpclb.c:792]                 Created new Round Robin policy (0x7f9b2e6000c0)
I0914 10:40:19.193347000 123145436954624 grpclb.c:588]                 Setting grpclb's state to CONNECTING from new RR policy 0x7f9b2e6000c0 state.
I0914 10:40:19.193447000 123145436954624 grpclb.c:213]                 Unreffing RR 0x7f9b2e6000c0
I0914 10:40:19.193455000 123145436954624 grpclb.c:588]                 Setting grpclb's state to READY from new RR policy 0x7f9b2e6000c0 state.
Greeter received: Hello world 1
```

Then, I started a second backend, also, the balancer wrote the new serverlist to stream.
```balancer
INFO[1375] [watcher] example.52tt.local add new addr 192.168.8.80:50052
DEBU[1375] [balancer] Sent server list, target example.52tt.local, sls: [ip_address:"\000\000\000\000\000\000\000\000\000\000\377\377\300\250\010P" port:50051 load_balance_token:"192.168.8.80:50051_1505356819"  ip_address:"\000\000\000\000\000\000\000\000\000\000\377\377\300\250\010P" port:50052 load_balance_token:"192.168.8.80:50052_1505356988" ]
```
You see there are two backends in the serverlist.
But from the view of client, no logs about receiving new serverlist was printed, and the new backend received no requests.

Then I shutdown the first backend.
```balancer
INFO[1545] [watcher] example.52tt.local delete addr ip_address:"\000\000\000\000\000\000\000\000\000\000\377\377\300\250\010P" port:50051 load_balance_token:"192.168.8.80:50051_1505357158"
DEBU[1545] [balancer] Sent server list, target example.52tt.local, sls: [ip_address:"\000\000\000\000\000\000\000\000\000\000\377\377\300\250\010P" port:50052 load_balance_token:"192.168.8.80:50052_1505356988" ]
```

A new serverlist with 1 backend was sent, 
And this time, the client received two serverlists simultaneously (according the logs), the first one with 2 backends and the other with 1 backend.
```
D0914 10:46:01.646745000 123145436954624 grpclb.c:1212]                No RR policy in grpclb instance 0x7f9b2e7005d0. Adding to grpclb's pending picks
I0914 10:46:01.646845000 123145436954624 grpclb.c:1585]                Serverlist with 2 servers received
I0914 10:46:01.646856000 123145436954624 grpclb.c:1592]                Serverlist[0]: [::ffff:192.168.8.80]:50051
I0914 10:46:01.646861000 123145436954624 grpclb.c:1592]                Serverlist[1]: [::ffff:192.168.8.80]:50052
I0914 10:46:01.646916000 123145436954624 grpclb.c:588]                 Setting grpclb's state to IDLE from new RR policy 0x7f9b2e500c50 state.
I0914 10:46:01.681720000 123145436954624 grpclb.c:753]                 Pending pick about to (async) PICK from 0x7f9b2e500c50
D0914 10:46:01.681740000 123145436954624 grpclb.c:792]                 Created new Round Robin policy (0x7f9b2e500c50)
I0914 10:46:01.681778000 123145436954624 grpclb.c:588]                 Setting grpclb's state to CONNECTING from new RR policy 0x7f9b2e500c50 state.
I0914 10:46:01.681795000 123145436954624 grpclb.c:1585]                Serverlist with 1 servers received
I0914 10:46:01.681802000 123145436954624 grpclb.c:1592]                Serverlist[0]: [::ffff:192.168.8.80]:50052
D0914 10:46:01.681809000 123145436954624 grpclb.c:785]                 Updating Round Robin policy (0x7f9b2e500c50)
I0914 10:46:01.681891000 123145436954624 subchannel.c:683]             Connect failed: {"created":"@1505357161.681855000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:192.168.8.80:50051"}
```
All the pending requests were sent to the second backend.

**Comment by markdroth** [comment]
Does your client attempt to send any RPCs between the time that the balancer sends the serverlist containing the second backend and the time that you shut down the first backend?  If not, it's likely that we're not triggering any polling on the client, so it has no opportunity to read the update from the balancer.

In order to allow applications more control over thread usage, gRPC does not have its own dedicated polling thread(s); instead, we do polling opportunistically when the application calls into gRPC to (e.g.) send an RPC.  So if your client did not try to send any RPCs between the time that the balancer sent the serverlist containing the second backend and the time that the first backend was shut down, then it would not see that new serverlist until the next RPC is sent.

If this is the problem, then @y-zeng is working on a change that should fix this.  The idea is to add a timer in our timer thread that wakes up periodically and does an instantaneous poll, just to see if there's any new I/O that needs to be processed.  This would allow it to process the serverlist before the next RPC is sent.

**Comment by y-zeng** [comment]
@wuweiplus Could you please try it again with the head of master? We have enabled a workaround for the polling issue since b6ef6e9ff5701d15a352f38a450de2af49d19657.

**Comment by wuweiplus** [comment]
@markdroth Yes, as I mentioned in the issue, the client sent a RPC every 3 seconds. But all the RPCs were sent to first backend after I start a second one, and it didn't read the update from the balancer until I shut down the first backend. I've run my tests again based on f37dfda1c3f0428995d67cb82c6fbcada7260e84 (when I submit the issue)  and f54af4832e08f317a05de909e88fdb38ace92cb0 (the latest commit before @y-zeng 's work-around). Or do I have some misuses in the test code?

@y-zeng Thanks. I've tried the head of master that the client is now able to read the updates from balancer in a new thread, and the grpclb works as expected. 👍

**Comment by wuweiplus** [comment]
Here is a new issue, `restarting the balancer` leads the grpc timer thread to enter a infinite loop (100% reproductive).

### What version of gRPC and what language are you using? 
 gRPC version: v1.6.0
 language: C++

### What operating system (Linux, Windows, …) and version?
 CentOS 6.5

### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.2 
 Environment variables:
    GRPC_DNS_RESOLVER=ares
    GRPC_VERBOSITY=DEBUG
    GRPC_TRACE=glb,timer

### What did you do?
 I ran a client with `grpclb` policy to communicate with the server, once I restart the balancer, the client starts to occupy 100% CPU load.
 Then I attached the client process with `gdb`, I see the grpc timer thread has entered a infinite loop, the stack is as below.
```
(gdb) bt
#0  0x0000000000477aee in refill_heap (now=23024, shard=0xb07c10 <g_shards+528>) at src/core/lib/iomgr/timer_generic.c:374
#1  pop_one (now=23024, shard=0xb07c10 <g_shards+528>) at src/core/lib/iomgr/timer_generic.c:399
#2  pop_timers (error=0x0, new_min_deadline=<synthetic pointer>, now=23024, shard=0xb07c10 <g_shards+528>, exec_ctx=0x7f311fffeb20) at src/core/lib/iomgr/timer_generic.c:425
#3  run_some_expired_timers (exec_ctx=0x7f311fffeb20, now=23024, next=0x7f311fffea70, error=0x0) at src/core/lib/iomgr/timer_generic.c:464
#4  0x0000000000478683 in grpc_timer_check (exec_ctx=exec_ctx@entry=0x7f311fffeb20, now=..., next=next@entry=0x7f311fffeb10) at src/core/lib/iomgr/timer_generic.c:552
#5  0x0000000000478e1f in timer_main_loop (exec_ctx=0x7f311fffeb20) at src/core/lib/iomgr/timer_manager.c:227
#6  timer_thread (completed_thread_ptr=completed_thread_ptr@entry=0x7f31180009c0) at src/core/lib/iomgr/timer_manager.c:277
#7  0x00000000004954c7 in thread_body (v=<optimized out>) at src/core/lib/support/thd_posix.c:42
#8  0x0000003d96007a51 in start_thread (arg=0x7f311ffff700) at pthread_create.c:301
#9  0x0000003d95ce893d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

(gdb) p timer
$3 = (grpc_timer *) 0x191fb98
(gdb) p *timer
$4 = {deadline = 82597, heap_index = 4294967295, pending = true, next = 0x191fb98, prev = 0x191fb98, closure = 0x191fbc8}
(gdb) p *shard
$5 = {mu = {__data = {__lock = 1, __count = 0, __owner = 16247, __nusers = 1, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}},
    __size = "\001\000\000\000\000\000\000\000w?\000\000\001", '\000' <repeats 26 times>, __align = 1}, stats = {init_avg = 3.0303030303030303, regress_weight = 0.10000000000000001,
    persistence_factor = 0.5, batch_total_value = 0, batch_num_samples = 0, aggregate_total_weight = 1.2000002264976501, aggregate_weighted_avg = 50.505052863146275}, queue_deadline_cap = 24024,
  min_deadline = 23024, shard_queue_index = 0, heap = {timers = 0x0, timer_count = 0, timer_capacity = 0}, list = {deadline = 0, heap_index = 0, pending = false, next = 0x191fb98, prev = 0x191fb98,
    closure = 0x0}}
(gdb) p &(shard->list)
$6 = (grpc_timer *) 0xb07c98 <g_shards+664>
```

The codes around in timer_generic.c are:
```C++
for (timer = shard->list.next; timer != &shard->list; timer = next) {
    next = timer->next;

    if (timer->deadline < shard->queue_deadline_cap) {
      if (GRPC_TRACER_ON(grpc_timer_check_trace)) {
        gpr_log(GPR_DEBUG, "  .. add timer with deadline %" PRIdPTR " to heap",
                timer->deadline);
      }
      list_remove(timer);
      grpc_timer_heap_add(&shard->heap, timer);
    }
}
```

Trace logs:
```
I1020 13:42:06.177925122   16229 grpclb.c:1674]              Status from LB server received. Status = 14, Details = 'Endpoint read failed', (call: 0x1921fb8), error (nil)
D1020 13:42:06.177960813   16229 grpclb.c:1695]              Connection to LB server lost (grpclb: 0x191f930)...
D1020 13:42:06.177972784   16229 grpclb.c:1699]              ... retry_timer_active in 20.000000000 seconds.
D1020 13:42:06.177984308   16229 timer_generic.c:248]        TIMER 0x191fb50: SET 2692154.924458289 [22595] now 2692134.924458289 [2594] call 0x191fa88[0x4bca00]
D1020 13:42:06.178002744   16229 timer_generic.c:281]          .. add to shard 15 with queue_deadline_cap=3002 => is_first_timer=false

...............

D1020 13:42:26.178244128   16231 timer_generic.c:409]        TIMER 0x191fb50: FIRE 0ms late
I1020 13:42:26.178562398   16231 grpclb.c:1658]              Restaring call to LB server (grpclb 0x191f930)
I1020 13:42:26.178619154   16231 grpclb.c:1449]              Query for backends (grpclb: 0x191f930, lb_channel: 0x1920f50, lb_call: 0x7f3118000bb0)
D1020 13:42:26.178792771   16231 timer_generic.c:248]        TIMER 0x7f3118003ea0: SET 2692174.925141862 [42596] now 2692154.925285224 [22595] call 0x7f3118003ec8[0x513410]
D1020 13:42:26.178813748   16231 timer_generic.c:281]          .. add to shard 21 with queue_deadline_cap=23015 => is_first_timer=false
D1020 13:42:26.178827802   16231 timer_generic.c:332]        TIMER 0x7f3118003ea0: CANCEL pending=true
D1020 13:42:26.178866527   16231 timer_generic.c:248]        TIMER 0x7f3118003ee0: SET 2692174.925141862 [42596] now 2692154.925361580 [22595] call 0x7f3118003f08[0x5046a0]
D1020 13:42:26.178883921   16231 timer_generic.c:281]          .. add to shard 17 with queue_deadline_cap=23015 => is_first_timer=false
D1020 13:42:26.178903447   16231 timer_generic.c:332]        TIMER 0x7f3118003ee0: CANCEL pending=true
I1020 13:42:26.179791824   16229 grpclb.c:1559]              received initial LB response message; client load reporting interval = 60.000000000 sec
D1020 13:42:26.179816202   16229 timer_generic.c:248]        TIMER 0x191fb98: SET 2692214.926312245 [82597] now 2692154.926312245 [22596] call 0x191fbc8[0x4bbec0]
D1020 13:42:26.179826693   16229 timer_generic.c:281]          .. add to shard 3 with queue_deadline_cap=23023 => is_first_timer=false
I1020 13:42:26.182283212   16229 grpclb.c:1584]              Serverlist with 1 servers received

```

**Comment by dgquintas** [comment]
The issue seems resolved, closing.
