### ISSUE TITLE
cq.AsyncNext return GOT_EVENT but ok is false

### ISSUE THREAD

**Issue by tjb1216** [grpc/grpc#12346]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 yes
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpc 1.4.1 c++
 
### What operating system (Linux, Windows, …) and version?
 linux centos 6.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 I am using the async client of grpc like grpc/examples/cpp/helloworld/greeter_async_client2.cc.
![image](https://user-images.githubusercontent.com/6902833/29914291-92aab2c4-8e6a-11e7-8c09-8d60a47648e7.png)

### What did you expect to see?
 cq.AsyncNext return GOT_EVENT but ok is true
 
### What did you see instead?
 cq.AsyncNext return GOT_EVENT but ok is false, and the got_tag is perfect, the status and reply of it are all ok, status.ok() return true.  That confused me,  why would this situation happen? 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by tjb1216** [comment]
@dgquintas   @vjpai  @markdroth

**Comment by markdroth** [comment]
This is not a bug; it's a usage question.  Please keep this kind of discussion to the mailing list.

There is currently a thread discussing this here:

https://groups.google.com/d/topic/grpc-io/nNikxnFfTXw/discussion
