### ISSUE TITLE
Build grpc on windows with /MD

### ISSUE THREAD

**Issue by bbernhard** [grpc/grpc#12354]
### What version of gRPC and what language are you using?
C++, Version 1.6.0
 
### What operating system (Linux, Windows, …) and version?
Windows 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Microsoft Visual C++ 2015 
 
### What did you do?
My goal is to build grpc with `/MD` (dynamic linking to msvcrt and the Visual Studio C++ runtime). Therefore I did the following: 

* `md .build`
* `cd .build`
* `cmake .. -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Release`
* grepped through all the *.vcxproj files and replaced 
`<RuntimeLibrary>MultiThreaded</RuntimeLibrary>` with `<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>`

and
 
`<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>` with `<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>`
* `cmake --build .`
 

### What did you expect to see?
A valid `grpc_dll.dll` file
 
### What did you see instead?
After the build process finished I can see that there is a `grpc_dll.dll` file in the build folder, but unfortunately it is 0kb in size. In the build log I see the following line: 

`atomicops_internals_x86_gcc.obj : warning LNK4221: Die Objektdatei definiert
keine zuvor undefinierten ÷ffentlichen Symbole. Sie wird daher von keinem Verkn
³pfungsvorgang verwendet, der diese Bibliothek benutzt. `

**Comment by jtattermusch** [comment]
I don't think "manually" replacing definitions in the cmake-generated vcxproj files is a recommended. If you want to change the compilation options, you should change the https://github.com/grpc/grpc/blob/master/CMakeLists.txt (generated from a template https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template) and let cmake do its job.

Areas of particular interest are https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L133 and BUILD_SHARED_LIBRARIES option.

I'll close this issue for now, but feel free to reopen once you use the right approach to generate libraries with /MD and it still doesn't work.
