### ISSUE TITLE
Add back 53e6b56e32c79ba401a67cb349519c12991539cc

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#12367]
Roll forward https://github.com/grpc/grpc/pull/10864/commits/53e6b56e32c79ba401a67cb349519c12991539cc

This change was rolled back because it caused hangs in the tensorflow RPCBench benchmark.
We would like to eventually add it back because it saves a lot of memory on the server.

**Comment by sreecha** [comment]
Reassigning this to ken since he is doing this..
