### ISSUE TITLE
Clone of 'https://boringssl.googlesource.com/boringssl' into submodule path 'third_party/boringssl-with-bazel' failed

### ISSUE THREAD

**Issue by haolujun** [grpc/grpc#12377]
When I installed grpc, i run "git submodule update --init", then error occured like below:

error: Failed connect to boringssl.googlesource.com:443; Operation now in progress while accessing https://boringssl.googlesource.com/boringssl/info/refs
Clone of 'https://boringssl.googlesource.com/boringssl' into submodule path 'third_party/boringssl-with-bazel' failed 

what should I do?

**Comment by haolujun** [comment]
I know why I got this error，because I am in china。

**Comment by hyellowriver** [comment]
怎么解决的？

**Comment by CHer27** [comment]
同问，求分享解决办法

**Comment by topillar** [comment]
please modify
[submodule "third_party/boringssl-with-bazel"]
	path = third_party/boringssl-with-bazel
	url = https://boringssl.googlesource.com/boringssl

====>
[submodule "third_party/boringssl-with-bazel"]
	path = third_party/boringssl-with-bazel
         url = https://github.com/google/boringssl.git

**Comment by Wasdns** [comment]
Hi, @topillar I have tried your solution but it still did not work. I think one possible solution is to download the old release that does not have this submodule.

**Comment by Wasdns** [comment]
This issue could be resolved by using ss-qt5 to bypass the firewall.

**Comment by YoungyoungX** [comment]
Why am in China, that is not the problem! I am blocked by the wall is the problem. This time, I feel raged!

**Comment by xyyDDD** [comment]
I met this problem again when I tried to use VPN to clone this.Did it also because of the wall?And is anyone have a solution?

**Comment by topillar** [comment]
Actually , we don't need boringssl-with-bazel. I recommend you all down the source tarball, then build it . pls refer to https://github.com/topillar/Build_gRPC_on_Windows/blob/master/Guide.md .

**Comment by helpceo** [comment]
没有人解决这个问题吗

**Comment by jintao-zero** [comment]
1. modify .gitmodule file
   change url of submodule "third_party/boringssl-with-bazel" to https://github.com/google/boringssl.git
2. git submodule sync
2. git submodule update --init

**Comment by AspirinSJL** [comment]
那应该解决了？如果还有问题再开吧！
