### ISSUE TITLE
io.h: No such file or directory

### ISSUE THREAD

**Issue by magick93** [grpc/grpc#12387]
### What version of gRPC and what language are you using?
 Not exactly sure what version. I am trying to compile from source. Assume it is the latest.
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 15.04 *32bit*
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.9.2
 
### What did you do?
In a 32bit docker image I am doing:

```
RUN git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
WORKDIR grpc
RUN git submodule update --init
RUN make
RUN make install
```
 
### What did you expect to see?
 
I expected to see source compile successfully.
 
### What did you see instead?

```
step 7 : RUN make
 ---> Running in 613f8fd2cea3
[MAKE]    Generating /wine/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /wine/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
make: Circular /wine/grpc/libs/opt/libares.a <- /wine/grpc/libs/opt/libz.a dependency dropped.
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
In file included from third_party/cares/cares/ares_setup.h:214:0,
                 from third_party/cares/cares/ares__close_sockets.c:17:
third_party/cares/cares/setup_once.h:71:16: fatal error: io.h: No such file or directory
 #include <io.h>
                ^
compilation terminated.
winegcc: gcc failed
Makefile:2526: recipe for target '/wine/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o' failed
make: *** [/wine/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o] Error 2

```
 

 
### Anything else we should know about your project / environment?
I am am hoping to use gRPC to expose functionality from a dll, running on linux. The dll (being a win shared lib) requires wine. And this requires running on a 32bit arch.

**Comment by magick93** [comment]
My bad - didnt RTFM - need to add required dependencies.

**Comment by mihaitodor** [comment]
@magick93 Which dependencies are those?
