### ISSUE TITLE
Where has example for use the GRPC to transport JSON ?

### ISSUE THREAD

**Issue by pengweichu** [grpc/grpc#12389]
Hi, I would like to use GRPC to send the PUSH notification to APNS, the APNS requires HTTP2 with JSON format data, how could I use JSON in GRPC to instead of the PROTOBUF ? When can I find the example ?

Thanks

**Comment by nicolasnoble** [comment]
You can't use gRPC to communicate with APN services. Even if we'd be to provide an example to use gRPC with JSON payloads instead of protobuf, it'd still wouldn't work. It's not because both APN and gRPC work on top of HTTP/2 that they are compatible protocols. They're not.
