### ISSUE TITLE
Not being able to add CMake's add_subdirectory on this project

### ISSUE THREAD

**Issue by tinganho** [grpc/grpc#12382]
I'm adding gRPC to my project as a git submodule under a folder called `third_party`.

I think it is not possible to just add CMake's `add_subdirectory(third_party/grpc)` call to add it as a dependency on a project. At least, I got some file not found errors.
```
../src/Program/ProtocolBuffers/Build/LyaSync.grpc.pb.h:9:10: fatal error:
      'grpc++/impl/codegen/async_stream.h' file not found
```
I also, tried to specifically include those directories where all the header files are located:
```
include_directories(
    third_party/grpc/include
)
```
But the errors are still occurring? (Though it is able to find "grpc/grpc.h", which is strange, but nothing under the grpc++ directory).

**Comment by jtattermusch** [comment]
For me this actually works out of the box, as demonstrated in the example added in https://github.com/grpc/grpc/pull/14864 (and there's a test that verifies that it works fine).

Please refer to the example and let us know if you could make things work in your project.
I'll close this issue now, we can reopen if issues persist.
