### ISSUE TITLE
bazel macro 'cc_grpc_library' does not document all its arguments

### ISSUE THREAD

**Issue by endobson** [grpc/grpc#12381]
Problematic code:
https://github.com/grpc/grpc/blob/master/bazel/cc_grpc_library.bzl

This macro has the argument `proto_only` but this is not included in the docstring.

**Comment by drigz** [comment]
It appears that `proto_library` makes `cc_grpc_library` behave (slightly) like `cc_proto_library`. It's not clear to me why it duplicates the functionality of `cc_proto_library`.
