### ISSUE TITLE
Wait-for-ready flag default (false) is not respected in C core

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#12392]
Objective C helloworld example gets stuck at the __second__ attempt to connect to a shutdown server. Confirmed wait-for-ready flag was not set and channel was in transient failure mode, likely in a backoff. The expected behavior was a call failing immediately (according to [spec](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md)), while current behavior is a call waits until backoff ends, then fail upon receiving "connection refused" from server.

**Comment by ncteisen** [comment]
I believe this was solved in #13121. Reopen if that is not the case

**Comment by muxi** [comment]
Not resolved by #13121 but this issue is obsolete. Closing.
