### ISSUE TITLE
gRPC C# on Mono needs 32-bit flavor of grpc_csharp_ext.dylib to run.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1239]
Mono on Mac is 32-bit.
after make install_grpc_csharp_ext, mono seems to properly locate the support library, but complains about its bitness (it's compiled as 64 bit).
If we manage to compile grpc_csharp_ext as 32 bit library, gRPC C# should be able to run on Mac (under Mono).

**Comment by nicolasnoble** [comment]
32 bits binaries under MacOS are still a thing ? I'm impressed.

Try compiling with CPPFLAGS=-m32 LDFLAGS=-m32 make maybe ?

**Comment by jtattermusch** [comment]
CPPFLAGS doesn't work, I had more success with setting CFLAGS
It turns out a few other hacks are also needed (changing darwin64-x86_64-cc to darwin-i386-cc, disabling stripping and some other small things).
But I was successful running all the C# unit tests on my Mac after I managed to install the grpc_csharp_ext library. I might add a PR for this later when I have more time.

**Comment by Kavignon** [comment]
What kind of support should be added in order to make 32-bit binaries work ?

**Comment by jtattermusch** [comment]
I've tried this out locally and it is possible to build 32bit version of grpc_csharp_ext.dylib on Mac. It's just a few tweaks would need to be introduced in the Makefile.
Do you depend on gRPC C# on Mac?

**Comment by Kavignon** [comment]
I myself an not a user of MAC. I was wonderin so that I could download a vm and maybe start digging a bit for this issue ! @jtattermusch

**Comment by jtattermusch** [comment]
Yes, that would be great. The goal is to modify the Makefile.template in a way that the makefile would allow building 32-bit version of grpc and installed grpc_csharp_ext.dylib correctly. If you manage to do that, you should be able to open the gRPC C# main solution and run all the unit tests.

**Comment by Kavignon** [comment]
Do you have any leads on how to do that ? Is there some links or
documentation I could read in order to think of something ? Or do I need to
do some magic voodoo ? :p

On Tuesday, April 14, 2015, Jan Tattermusch <notifications@github.com>
wrote:

> Yes, that would be great. The goal is to modify the Makefile.template in a
> way that the makefile would allow building 32-bit version of grpc and
> installed grpc_csharp_ext.dylib correctly. If you manage to do that, you
> should be able to open the gRPC C# main solution and run all the unit tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/issues/1239#issuecomment-92963764>.
>


-- 
Kevin Avignon
Étudiant en génie des technologies de l'information (ETS)

**Comment by soltanmm** [comment]
The `Makefile.template` is a mixture of Python and Makefile declarations. It uses [Mako](http://www.makotemplates.org/). The Makefile itself is then generated from invoking `tools/buildgen/generate_projects.sh`. I'm of the opinion that it's borderline voodoo, though certainly less than magical. :-P

**Comment by jtattermusch** [comment]
Hm, this would be nice to have, but C# currently can run on OS X under 64-bit mono. The user experience is not great, because xamarin studio uses 32-bit, but I'd still say this is not a priority.

**Comment by jtattermusch** [comment]
@jayantkolhe  I don't think this is needed for beta. Mac is not our primary platform, we have higher priorities. This can be fixed later without breaking the API.

**Comment by jtattermusch** [comment]
Building 32bit grpc_csharp_ext on Mac now works.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=lvrKLSm0&invitationId=6208290922371829761&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc6vqm%7Euw








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc6vqm-uw&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEA2aGhFGTu0QAAAVihIFbkXJ8vjKhfmr03DsrRRkeOEx08d4GXy6XZ_Fdrww_udcNBlC9aRYcgFIwhX3uwnl_-9lF5PntGjHht-mVtd3CPFjyEWR9nctp7mdJ-mpGtbR63CYBYWGh7B2I5chLCCIC5M2Ku0Gt_mGaIf_6gmYQJglEnPDY21Un1exb_hgbFi1x8oX7M3N3hnnM6zJX4qTLw-Q&eid=0-ivzc6vqm-uw


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc6vqm-uw&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=lvrKLSm0&invitationId=6208290922371829761&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Ewenjb5%7Eiw6msi7d%7Emt

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=lvrKLSm0&invitationId=6208290922371829761&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Ewenjb5%7Eiw6msi7d%7Emt





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wenjb5-iw6msi7d-mt&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-wenjb5-iw6msi7d-mt&loid=AQEjA-6WHIXPxQAAAVi8M3MlImwJt1HJ7urVFPdm_F_ieK6iq0p1iqxE864-UI3q9YF3wJuKypmjF3bLHsY74PK6Na6FL5BSSk-E3k32Pf7qigEI7fZlhICAL0szhXIUORXheI_nXgUh6g7QCWH4o2eSfHGKMr-En5CJ4CYBNjNj-dkzTBOWtgVVg-eqHiEMYdmZ0VpeJBKbICWw1RfuEmqu_5-v2w

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wenjb5-iw6msi7d-mt&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
