### ISSUE TITLE
cmake: ld: library not found for -llibprotobuf

### ISSUE THREAD

**Issue by tinganho** [grpc/grpc#12393]
I originally reported this on the protobuf repo in https://github.com/google/protobuf/issues/3589#issuecomment-327255720. But @xfxyjwf told me to report it here.

I'm getting this error:
```
ld: library not found for -llibprotobuf
```
Whenever, I try to link with `grpc++` using CMake:

```
target_link_libraries(lya-client grpc++)
```

I seem to have protobuf library installed correctly:

```
ls -la | grep protobuf                                     
-rwxr-xr-x    1 tinganho  admin    385708 Sep  4 00:01 libprotobuf-lite.13.dylib
-rwxr-xr-x    1 tinganho  admin    456576 Sep  3 23:28 libprotobuf-lite.14.dylib
-rw-r--r--    1 tinganho  admin   3142384 Sep  4 00:01 libprotobuf-lite.a
lrwxr-xr-x    1 tinganho  admin        25 Sep  4 00:01 libprotobuf-lite.dylib -> libprotobuf-lite.13.dylib
-rwxr-xr-x    1 tinganho  admin       970 Sep  4 00:01 libprotobuf-lite.la
-rwxr-xr-x    1 tinganho  admin   3060008 Sep  4 00:01 libprotobuf.13.dylib
-rwxr-xr-x    1 tinganho  admin   3207080 Sep  3 23:28 libprotobuf.14.dylib
-rw-r--r--    1 tinganho  admin  44915496 Sep  4 00:01 libprotobuf.a
lrwxr-xr-x    1 tinganho  admin        20 Sep  4 00:01 libprotobuf.dylib -> libprotobuf.13.dylib
-rwxr-xr-x    1 tinganho  admin       940 Sep  4 00:01 libprotobuf.la
```

I followed the install instructions for both `grpc` and `protobuf` and I'm on a Mac.

**Comment by tinganho** [comment]
I'm getting a similar error when I try to link with `grpc`
```
target_link_libraries(lya-client grpc)
```

```
ld: library not found for -lzlibstatic
```

**Comment by tinganho** [comment]
@xfxyjwf commented:
>"-llibprotobuf" is incorrect. It should be "-lprotobuf" (i.e., without lib prefix). Can you create an issue on the grpc project?

**Comment by tinganho** [comment]
Yes, that's correct.

I pushed up the problem here https://github.com/tinganho/LYA/blob/master/CMakeLists.txt#L42

**Comment by jtattermusch** [comment]
Please reopen if this is still an issue. Also please include the exact commands you ran, otherwise the problem is hard for us to reproduce.
