### ISSUE TITLE
grpc_insecure_channel_create_from_fd() hardcodes the default authority to 'test.authority'

### ISSUE THREAD

**Issue by ced5** [grpc/grpc#12401]
gRPC 1.7.0-dev, Linux 4.4 (Ubuntu 14.04)

For reasons unknown to me, the `grpc_insecure_channel_create_from_fd()` function adds a channel argument setting the default `:authority` HTTP/2 header to `test.authority`. This means that any HTTP/2 requests sent by gRPC on a channel created with this function will set the `:authority` field to `test.authority`. If a proxy along the path to the gRPC server relies on the `:authority` field, it may break as a result.

Normally, it's possible to override the default authority by supplying an argument to `grpc_channel_create_call()`. However, the Python bindings provide no way to do such a thing--cf. #12400.

**Comment by ced5** [comment]
Ping.

**Comment by ced5** [comment]
Can we hurry up and fix this? This is now holding up an important internal Google project.

**Comment by hcaseyal** [comment]
Closing due to reporter inaction. Please feel free to re-open if this is still an issue.
