### ISSUE TITLE
Cannot override the default HTTP/2 authority from Python when creating call objects

### ISSUE THREAD

**Issue by ced5** [grpc/grpc#12400]
gRPC 1.7.0-dev, Python 2.7, Linux 4.4 (Ubuntu 14.04)

Once a channel has been created, there is no way to specify an alternative value for the `:authority` HTTP/2 pseudo-header from Python. gRPC categorically rejects any metadatum that specifies an HTTP/2 pseudo-header. In addition, the Python bindings do not provide any way to supply an argument to the `grpc_channel_create_call()` function's authority parameter. As a result, Python users are thus stuck with whatever value was set from the `GRPC_ARG_DEFAULT_AUTHORITY` channel argument. (This is especially irksome using the `grpc_insecure_channel_create_from_fd()` function, which for some reason hardcodes the authority to `test.authority`. I'm aware that no official Python bindings exist for that function; I have some of my own that I'd eventually like to upstream.)

**Comment by nathanielmanistaatgoogle** [comment]
I suspect that if this were a feature we were going to add, we'd add it across all language implementations.

@jboeuf, what are your thoughts on this?

**Comment by jboeuf** [comment]
@ctiller what is the policy for such metadata on the core stack?

**Comment by ctiller** [comment]
Use the argument provided by grpc_channel_create_call to set it: not all transports are http2, and so the correct spelling isn't always :authority, and so this shouldn't be specified as metadata.

**Comment by ced5** [comment]
Uh, yeah. I'm saying that I can't supply a value to that parameter from Python.

**Comment by nathanielmanistaatgoogle** [comment]
@ced5: what is ["the `grpc_channel_create_call()` function's authority parameter"](https://github.com/grpc/grpc/blob/9c15cb9329a8e465529a8a8759b808b15e3df97e/include/grpc/grpc.h#L187-L197)? Sorry if I'm coming across as obtuse; a lot of this part of the code has leapt out of my brain since the last time I worked with it.

**Comment by ced5** [comment]
```c
GRPCAPI grpc_call *grpc_channel_create_call(
    grpc_channel *channel, grpc_call *parent_call, uint32_t propagation_mask,
    grpc_completion_queue *completion_queue, grpc_slice method,
    const grpc_slice *host /* <-- this parameter is the one I'm talking about */,
    gpr_timespec deadline, void *reserved);
```

**Comment by ced5** [comment]
Ping.

**Comment by ced5** [comment]
Can we hurry up and fix this? This is now holding up an important internal Google project.

**Comment by mehrdada** [comment]
@nathanielmanistaatgoogle Please evaluate if there anything actionable here or shall we close this issue?

**Comment by nathanielmanistaatgoogle** [comment]
@ced5: is this still a thing that should happen eventually?

**Comment by hcaseyal** [comment]
Closing due to reporter inaction. Please feel free to re-open if this is still an issue.
