### ISSUE TITLE
Node bindings fail to build on Mavericks due to missing include/library paths

### ISSUE THREAD

**Issue by vgatto** [grpc/grpc#1242]
After following the instructions at the root of the repository for make/sudo make install, the gRPC libraries and headers were installed in /usr/local.

However, when I tried to build the node bindings, it failed to find either the headers or libraries:

```
sleepy:node vgatto$ npm install
npm WARN package.json nan@1.7.0 No README data

> grpc@0.6.0 install /Users/vgatto/dev/springful/grpc/src/node
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
2015-04-09 17:04:24.428 xcodebuild[8593:1007] [MT] PluginLoading: Required plug-in compatibility UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-04-09 17:04:24.430 xcodebuild[8593:1007] Failed to load plugin at: /Users/vgatto/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
```

I made a few local edits to binding.gyp to add /usr/local  and I was able to build.  I'm not sure if my system is somehow misconfigured or if this is a bug. FWIW, I am using Homebrew, not MacPorts.

Specifically:

```
  "targets" : [
    {
      'include_dirs': [
        "<!(node -e \"require('nan')\")",
        "/usr/local/include"
      ],

...

      'link_settings': {
        'libraries': [
          '-lpthread',
          '-lgrpc',
          '-lgpr',
          '-L/usr/local/lib'
        ]
      },
```

**Comment by murgatroid99** [comment]
You seem to have installed the gRPC C library in a path that is not in your default include path or link search path. I think that it should work if you prefix the `npm install` command with `CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib` instead of making that edit to `binding.gyp`.

**Comment by vgatto** [comment]
Thanks for the quick response. I think you may be right, because I don't see the gRPC library depending on anything I have installed to /usr/local. However, it seems that `npm install` is ignoring the environment.
I tried the following two approaches and both failed:

```
CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib npm install
```

```
export CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib
npm install
```

**Comment by murgatroid99** [comment]
I always mess this up. That should be `CXXFLAGS`, not `CPPFLAGS`.

**Comment by vgatto** [comment]
Yep, that was it, thanks!

**Comment by chelsh** [comment]
whwdeMacBook-Pro:grpc whw$ git branch
* (detached from origin/release-0_10)
  master
whwdeMacBook-Pro:grpc whw$ cd examples
whwdeMacBook-Pro:examples whw$ cd node
whwdeMacBook-Pro:node whw$ echo $LDFLAGS
-L/usr/local/lib
whwdeMacBook-Pro:node whw$ echo $CXXFLAGS
-I/usr/local/include
whwdeMacBook-Pro:node whw$ npm install
npm WARN package.json grpc-demo@0.5.0 No repository field.
|
> grpc@0.10.1 install /Users/whw/grpc/examples/node/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/whw/grpc/examples/node/node_modules/grpc
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whw/grpc/examples/node/npm-debug.log
