### ISSUE TITLE
Not supporting null values for other types except protobuf Message.

### ISSUE THREAD

**Issue by nishants93** [grpc/grpc#12444]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes.
 
### What version of gRPC and what language are you using?
 grpc-1.6.0
 
### What operating system (Linux, Windows, …) and version?
 Mac
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 node-6.11.1
 
### What did you do?
When null is passed in any optional field that is not Protobuf message (e.g. string, double etc.) it throws an error.
 
### What did you expect to see?
 Expect to see that field truncated.
 
### What did you see instead?
 
Instead it threw an error "proto3 field without field presence cannot be null".
 
### Anything else we should know about your project / environment?
References:
    As stated [here](https://developers.google.com/protocol-buffers/docs/proto3#json) (If a value is missing in the JSON-encoded data or if its value is null, it will be interpreted as the appropriate default value when parsed into a protocol buffer.) this should not be happening.
    Also this happens since in the protobufjs - 5.0.2 which is being used in grpc node in the file 
    dist/protobuf.js on line 3470, they've explicitly made this check. But they have moved to version 
    6.8.0 now where they've corrected it but grpc is still using the same version only.

**Comment by Badou90** [comment]
Notices this today. With grpc@1.7.2 when i pass data from client to server, all `null` values transformed to their types default values. But when i requesting data from server, and have `null` values in any field, it broking with `proto3 field without field presence cannot be null`

**Comment by murgatroid99** [comment]
The new package `@grpc/proto-loader` uses the latest version of Protobuf.js, so it should not have this problem. Please try that package out.
