### ISSUE TITLE
Message-Type Header in gRPC Requests/Responses

### ISSUE THREAD

**Issue by OFmarting** [grpc/grpc#12468]
Hello,

According to the [wire specification](http://www.grpc.io/docs/guides/wire.html) the request can carry an optional Message-Type in the headers which indicates the fully qualified proto name of the message in the payload. I am using grpc-java and it doesn't seem to send this header. Is there a way to enable it in any gRPC implementation? Also, is it intentional that the response can't carry this header according to the wire specification?

In my opinion both, the request and the response should be able to carry this header. Further, there should be a way to enable this header in the gRPC implementations. The header would be especially useful for debugging purposes.

**Comment by yang-g** [comment]
This is in the wire spec but at least the C stack does not implement it. Assigning to @a11r.

**Comment by matthijskooijman** [comment]
A reason to *not* to include the message type, is to be more flexible in terms of refactoring of rpcs.

Initially some rpcs might share request or response message types (a particular case of this would be to use google.protobuf.Empty when no arguments are needed). When later extending these rpcs, you might want to duplicate these shared messages (e.g. introduce multiple verbatim copies) to allow extending each rpc independently of the others.

With the current implementation of *not* sending the message type as part of the request or response, this evolution is supported. If the message type is sent, then it is no longer possible to replace these messages with another (compatible) message, and thus requires each rpc to have separate request and response messages, even if that means duplicating the same (empty or non-empty) messages with different names.

**Comment by ejona86** [comment]
At the moment no implementation is sending the header.

If you change request/response message types, you're almost guaranteed to break existing clients at the API level. If the message type was included, then that would just allow us to detect the incompatibility at the wire level as well.

I think the added header was mainly to help debugging and introspection. But gRPC wasn't going to use it directly (which is also why it isn't implemented).

**Comment by matthijskooijman** [comment]
> If you change request/response message types, you're almost guaranteed to break existing clients at the API level.

Why? If you replace the message by a new, identical message, things shouldn't break, right? And then you can *modify* the new message (observing the normal rules for modifying messages).

**Comment by ejona86** [comment]
> If you replace the message by a new, identical message, things shouldn't break, right?

We're in the API world. So you're replacing one _type_ with another _type_. That trivially breaks compilation in static languages but can break any strongly-typed language.

Consider this made up Java method with the blocking stub:
```
RequestResponse myRpc(RequestResponse request);
// becoming
Response myRpc(Request request);

// A caller:
RequestResponse resp = myRpc(request);
```

In some languages, the response type is also a passed _in_ parameter, so you can't assume there's no reference to the response type. For example, if you used `google.proto.Empty`, some languages may mention that type when doing the RPC.

Again Java, but now async stub:
```
myRpc(RequestResponse request, StreamObserver<RequestResponse> respObserver);
```

**Comment by matthijskooijman** [comment]
Thanks for clarifying. IIUC you are saying that my suggestion breaks source compatibility. However, it seems to me that only *if* you regenerate the grpc-code from the updated `.proto` file, *then* the compatibility will break. This means that *if* you are changing the generated grpc source code, then you will also need to change the rest of the source code, which are typically tightly coupled anyway. I'm not saying this is not a problem, but it seems like a lighter problem that wire compatibility.

I was mostly talking about wire compatibility. AFAICS, without the type on the wire, it is possible to replace a message type and still talk to others that have been previously compiled using the original message type. In most cases, I would think this is the tougher compatibility hurdle.

Thinking on this more, as you mentioned that the message type is mostly for debugging, I realize that it doesn't hurt to *send* the message type, as long as the receiver does not enforce any checks on the received message type. Perhaps it would make sense to make that explicit in the wire spec?

**Comment by a11r** [comment]
The [Message-Type] is optional in the spec. It would be a waste of CPU and network to send this on 10's of billions of RPC every second, so we will probably never do it by default.
