### ISSUE TITLE
Feature Request - [C++] - Ability to set the maximum connections per server

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#12472]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes. 
### What version of gRPC and what language are you using?
1.4.2 - C++ 
 
### What operating system (Linux, Windows, …) and version?
Linux (CentOS 6), Windows 10 
 
See discussion thread - https://groups.google.com/forum/#!topic/grpc-io/kuT7hwGrBnc 
The grpc java issue - https://github.com/grpc/grpc-java/issues/1886

**Comment by tjb1216** [comment]
I'm interested in it. mark!

**Comment by abaldeva** [comment]
While at it, it'd also be great to be able to query the server for the number of connections it's currently servicing. The code would have to keep the information internally anyway in order to check against the maximum.

Thanks!

**Comment by hsaliak** [comment]
@vjpai would you be able to look into this and triage the request, I know that you are looking at a few API changes as a whole.

**Comment by vjpai** [comment]
The thought within the team was that this should be integrated with resource_quota to make sense. It deserves some discussion headed toward a gRFC for the right way to do this, IMO.

**Comment by hsaliak** [comment]
@vjpai I believe that @abaldeva had some thoughts on doing this also. Perhaps you two can help flesh this into a gRFC?

**Comment by abaldeva** [comment]
I am unfamiliar with resource_quota system but was poking around in the code. IIRC, I ultimately traced it to `grpc_tcp_listener` and my thought was to keep a counter there for current connection and compare it against a maximum. Then, in `on_accept` in tcp_server_windows.c (I think this/similar stuff can be done for posix), close the socket if over the configuration (there is already path for closing if the server is shutting down).
