### ISSUE TITLE
Ability to log client IP for "Secure transport failed with error 2" error

### ISSUE THREAD

**Issue by pavel-odintsov** [grpc/grpc#12470]
Hello!

I use current branch of gRPC from C++.

I see number of errors in my log "Secure transport failed with error 2" but they affect only small subset of my users.

And I want to know IP addresses of users affected by this issue.

Is it possible?

**Comment by markdroth** [comment]
That error message doesn't appear in the gRPC code base, so I'm not sure where it's coming from.

If you're still seeing this problem, please re-open and provide more information about what your code is doing and when this problem occurs.
