### ISSUE TITLE
Error running app with gRPC pod install on actual iOS device

### ISSUE THREAD

**Issue by alhennessey92** [grpc/grpc#12473]
I am using the current branch of gRPC with objective c.

I have integrated the .podspec file successfully and can successfully build and run the ios app in simulator mode, however when i try to build and run the app on my actual iPhone 6s i get the following error

> dyld: Library not loaded: @rpath/gRPC.framework/gRPC
  Referenced from: /var/containers/Bundle/Application/05197094-48B9-4FA9-9D4D-68ED83817C0F/MyApp.app/MyApp
  Reason: image not found
(lldb)

When i remove the pod the app successfully builds and runs on my iPhone, so it is something to do with gRPC, i have tried adding the grpc.framework as an embedded framework, but this does nothing.

Any ideas?

**Comment by muxi** [comment]
Sorry that we missed this issue. If you are still experiencing this issue please let us know and we will be willing to help.
