### ISSUE TITLE
PHP README should link to grpc.io or cloud.google.com for Installation

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc#12481]
The [README at src/php](https://github.com/grpc/grpc/tree/master/src/php) contains installation instructions that are different from those on [grpc.io](https://grpc.io/docs/quickstart/php.html) and on [cloud.google.com](https://cloud.google.com/php/grpc). 

Having two sets of instructions is confusing enough, having three is not acceptable. We should link the README to one of the official pages.

**Comment by ZhouyihaiDing** [comment]
Solved by #13709.
