### ISSUE TITLE
Test suit fails for grpc for languages C,C++,objc,ruby,python,sanity and csharp

### ISSUE THREAD

**Issue by snehlatamohite** [grpc/grpc#12505]
Hi,

We have build grpc from source (master branch) and trying to run test suit for different supported languages but getting below errors while running test suits. Could you please help/guide to resolve the issue?

### What version of gRPC and what language are you using?
We have built grpc from source master branch. 
Languages used C,C++,csharp,node,objc,php,php7,python,ruby. 
 
### What operating system (Linux, Windows, …) and version?
RHEL7.1 on X86 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.

python2.7

ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

node v6.2.1

### What did you do?

Build steps - 
yum update -y
yum install -y autoconf libtool cmake
git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init

mkdir build
cd build
cmake ..
make

#Install test dependencies

yum install python-setuptools
easy_install pip
pip install six
yum install -y cmake
curl -L https://github.com/gflags/gflags/archive/v2.1.2.tar.gz -o gflags.tar.gz && \
        tar xf gflags.tar.gz && \
        cd gflags-2.1.2 && \
        cmake . && \
        make && \
        make install
 git clone https://github.com/nodejs/node.git node && cd node && git checkout v6.2.1 && ./configure && make && make install
tools/run_tests/run_tests.py --help

 
Test Results - 
C - Tests 
Command - tools/run_tests/run_tests.py -l c -c dbg
Result - WAITING: 1 jobs running, 7090 complete, 4 failed
FAILED: bins/dbg/dualstack_socket_test GRPC_POLL_STRATEGY=poll [ret=-6, pid=32340]
FAILED: bins/dbg/concurrent_connectivity_test GRPC_POLL_STRATEGY=poll
FAILED: bins/dbg/dualstack_socket_test GRPC_POLL_STRATEGY=epoll1
FAILED: bins/dbg/dualstack_socket_test GRPC_POLL_STRATEGY=epollsig
FAILED: bins/dbg/dualstack_socket_test GRPC_POLL_STRATEGY=poll
FAILED: bins/dbg/dualstack_socket_test GRPC_POLL_STRATEGY=poll-cv
FAILED: bins/dbg/sequential_connectivity_test GRPC_POLL_STRATEGY=epoll1
FAILED: bins/dbg/sequential_connectivity_test GRPC_POLL_STRATEGY=epollsig
FAILED: bins/dbg/sequential_connectivity_test GRPC_POLL_STRATEGY=poll
FAILED: bins/dbg/sequential_connectivity_test GRPC_POLL_STRATEGY=poll-cv
FAILED: Some tests failed

C++ Tests - 
Command - tools/run_tests/run_tests.py -l c++ -c dbg
test/cpp/qps/client_sync.cc:165:40: error: too many arguments for format [-Werror=format-extra-args]
test/cpp/qps/client_sync.cc: In instantiation of ‘void grpc::testing::SynchronousStreamingClient<StreamType>::FinishStream(grpc::testing::HistogramEntry*, size_t) [with StreamType = grpc::ClientWriter<grpc::testing::SimpleRequest>; size_t = long unsigned int]’:
test/cpp/qps/client_sync.cc:267:5:   required from here
test/cpp/qps/client_sync.cc:165:40: error: spurious trailing ‘%’ in format [-Werror=format=]
test/cpp/qps/client_sync.cc:165:40: error: too many arguments for format [-Werror=format-extra-args]
test/cpp/qps/client_sync.cc: In instantiation of ‘void grpc::testing::SynchronousStreamingClient<StreamType>::FinishStream(grpc::testing::HistogramEntry*, size_t) [with StreamType = grpc::ClientReader<grpc::testing::SimpleResponse>; size_t = long unsigned int]’:
test/cpp/qps/client_sync.cc:298:5:   required from here
test/cpp/qps/client_sync.cc:165:40: error: spurious trailing ‘%’ in format [-Werror=format=]
test/cpp/qps/client_sync.cc:165:40: error: too many arguments for format [-Werror=format-extra-args]
cc1plus: all warnings being treated as errors
make: *** [/root/grpc/objs/dbg/test/cpp/qps/client_sync.o] Error 1
FAILED: make [ret=2, pid=10740]
FAILED: Some tests failed

csharp Tests - 
command - tools/run_tests/run_tests.py -l csharp -c dbg
Test fails with error dotnet: command not founds

objc Tests - 
Command - tools/run_tests/run_tests.py -l objc -c dbg
Cocoapods needs to be installed.
FAILED: src/objective-c/tests/build_tests.sh [ret=1, pid=17329]
FAILED: Some tests failed

python tests - 

command - tools/run_tests/run_tests.py -l python -c dbg

Result - 
/root/grpc/py34/bin/python3.4 -m pip install --upgrade pip
Failed to import the site module
Traceback (most recent call last):
  File "/root/grpc/py34/lib64/python3.4/site.py", line 67, in <module>
    import os
  File "/root/grpc/py34/lib64/python3.4/os.py", line 618, in <module>
    B7 _collections_abc import MutableMapping
ImportError: No module named '_collections_abc'
FAILED: /root/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=22480]
FAILED: Some tests failed

ruby Tests - 
Command - tools/run_tests/run_tests.py -l ruby -c dbg

Result - 
rake aborted!
Don't know how to build task 'third_party/zlib/zconf.h' (see --tasks)
/usr/local/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => compile => compile:x86_64-linux => compile:grpc_c:x86_64-linux => copy:grpc_c:x86_64-linux:2.0.0 => tmp/x86_64-linux/stage/third_party/zlib/zconf.h
(See full trace by running task with --trace)
FAILED: tools/run_tests/helper_scripts/build_ruby.sh [ret=1, pid=22577]
FAILED: Some tests failed

sanity Tests - 
Command -  tools/run_tests/run_tests.py -l sanity -c dbg
Result - 
FAILED: tools/distrib/python/check_grpcio_tools.py [ret=1, pid=32507]
FAILED: tools/buildgen/generate_projects.sh
FAILED: tools/distrib/clang_format_code.sh
FAILED: tools/distrib/pylint_code.sh
FAILED: tools/distrib/python/check_grpcio_tools.py
FAILED: tools/run_tests/sanity/check_cache_mk.sh
FAILED: tools/run_tests/sanity/check_owners.sh
FAILED: Some tests failed

We need further guidance for fixing the test failures. 
Also we have verified above tests suit after building grpc release 1.6.0 but has test failures for C,C++,node, node express, objc, ruby ,python and sanity test failures.  

Thanks,
Snehlata Mohite.

**Comment by snehlatamohite** [comment]
Hi,

Do you have travis CI setup for grpc build ? Can you please provide me link to it so that we can verify the build and test validation steps?

Thanks,
Snehlata Mohite.

**Comment by jtattermusch** [comment]
We are not using travis.

**Comment by jtattermusch** [comment]
No action here for several months, the problem is probably outdated. Closing.
