### ISSUE TITLE
System.Threading.ThreadPool Version 4.0.0 Not Found

### ISSUE THREAD

**Issue by GoldwinLeong** [grpc/grpc#12503]
Grpc.Core 1.6.0 depends on System.Threading.ThreadPool (>= 4.0.0) but System.Threading.ThreadPool 4.0.0 was not found. An approximate best match of System.Threading.ThreadPool 4.0.10 was resolved.

https://www.nuget.org/packages/System.Threading.ThreadPool/

**Comment by jtattermusch** [comment]
Thanks for reporting it, the fix will be in the v1.6.1 version (coming soon)
