### ISSUE TITLE
Raspberry Pi Node Precompiled Binaries Missing (Electron)

### ISSUE THREAD

**Issue by rhclayto** [grpc/grpc#12535]
I'm trying to install grpc for use in an electron project. It won't build for me (or electron-rebuild), but according to several closed issues here (e.g., https://github.com/grpc/grpc/issues/10891), there should now be node binaries for the ARM architecture. However, when I try to install it following the suggestions of @murgatroid99 at https://github.com/grpc/grpc/issues/8260 , I get the following error:

```
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.6.0/electron-v1.7-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.6.0 and electron@1.7.5 (electron-v1.7 ABI) (falling back to source compile with node-gyp)
```

And the source compilation then fails because of the BoringSSL/OpenSSL conflict problems noted in other issues here.

I have:

Electron 1.7.5
Node 8.4.0
Arch Linux 4.9.43-1-ARCH
Raspberry Pi 3 with armv7l architecture

Installation steps:

```
# Electron's version.
export npm_config_target=1.7.5
# The architecture of Electron.
export npm_config_arch=arm
# Download headers for Electron.
export npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
export npm_config_runtime=electron
# Install all dependencies, and store cache to ~/.electron-gyp.
HOME=~/.electron-gyp npm install grpc
```

I have also tried installing grpc 1.4.1 & 1.1.0, but the same problem recurs. It seems that there is no binary available for electron 1.7, or I am doing something wrong.

Any suggestions?

**Comment by rhclayto** [comment]
This still doesn't work for me, but i was wrong about why grpc won't build for me. It's not a conflict between BoringSSL & OpenSSL, it's that BoringSSL has an implicit fallthrough in its code that causes the compiler an error in GCC 7. See this other issue I opened for a solution: https://github.com/grpc/grpc/issues/12536

**Comment by murgatroid99** [comment]
We don't have binaries for Electron 1.7 simply because it was released after we last published a package.

**Comment by murgatroid99** [comment]
This has been fixed in more recent versions.
