### ISSUE TITLE
GRPC Erroneously talks to an HTTP proxy when connecting to a Unix Domain Socket

### ISSUE THREAD

**Issue by grahamc** [grpc/grpc#12543]
### What version of gRPC and what language are you using?

gRPC v1.4.2

Languages in use:

 - Go
 - PHP
 - Ruby
 
### What operating system (Linux, Windows, …) and version?
 
Scientific Linux 7, NixOS 17.03
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 - gcc version 5.4.0 (GCC)
 - ruby 2.3.3.p222
 - php 7.1.x
 
### What did you do?

1. Have an `http_proxy` in your environment:

```
$ echo $http_proxy
http://httpproxy.mydomain:8080

$ echo $no_proxy
.mydomain,localhost,127.0.0.1
```

2. Connect to a GRPC server on a local domain socket:

```ruby
Foo::Bar::Stub.new("unix:/var/run/mydaemon.sock", :this_channel_is_insecure)
```

3. Ouch! GRPC chats up the proxy!

```
$ pry
[1] pry(main)> require 'mything'
=> true

[2] pry(main)> config = {:socket => '/tmp/mydaemon.sock'}
=> {:socket=>"/tmp/mydaemon.sock"}

[3] pry(main)> conn = MyThing::Client.new(config)
=> #<MyThing::Client:0x007f06f413a248
 @mything_stub=
  #<MyThnig::Stub:0x007f06f413a130
   @ch=#<GRPC::Core::Channel:0x007f06f4139ff0>,
   @host="unix:/tmp/mydaemon.sock",
   @propagate_mask=nil,
   @timeout=1969-12-31 18:59:59 -0500>>

[4] pry(main)> conn.mything.a_grpc_call('fizzbuzz')
GRPC::Unavailable: 14:Endpoint read failed
from /opt/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
```
 
### What did you expect to see?
 
GRPC should not talk to an http_proxy when talking to local unix domain sockets.
 
### What did you see instead?

GRPC tried to use the remote HTTP proxy to talk to a local unix domain socket.

**Comment by jacobvosmaer** [comment]
Cross-referencing GitLab issue. https://gitlab.com/gitlab-org/gitlab-ce/issues/38333

**Comment by jacobvosmaer** [comment]
I've been reading a bit.

In [http_proxy.c's proxy_mapper_map_name ](https://github.com/grpc/grpc/blob/v1.6.2/src/core/ext/filters/client_channel/http_proxy.c#L112) we signal that no proxy should be used for the Unix socket by returning `false`. But, in [client_channel.c](https://github.com/grpc/grpc/blob/v1.6.2/src/core/ext/filters/client_channel/client_channel.c#L729-L735) we ignore the return value of proxy_mapper_map_name and use `proxy_name != NULL` as the condition to decide whether to proxy or not.

In http_proxy.c, that string is not freed & nulled on the "unix socket -> false" return path.

**Comment by jacobvosmaer** [comment]
I don't know enough about this code base to say what the solution is: checking the boolean return value of `grpc_proxy_mappers_map_name`, or freeing `name_to_resolve` in the early return of `proxy_mapper_map_name`.

**Comment by markdroth** [comment]
Please try patching in #12739 and let me know if it solves the problem.  Thanks!

**Comment by jacobvosmaer** [comment]
Thanks for the quick response @markdroth ! I hope I can find the time to test this before the next gRPC release.
