### ISSUE TITLE
Stripping call credentials from composite channel credentials should be recursive

### ISSUE THREAD

**Issue by ebf42** [grpc/grpc#12554]
The current implementation of duplicate_without_call_credentials for composite channel credentials appears incorrect; it simply increments the refcount on the inner creds:

https://github.com/grpc/grpc/blob/3bf7b714a5458aadfc1e2761ede1213f69ef7959/src/core/lib/security/credentials/composite/composite_credentials.c#L242-L248

In particular, this seems incorrect if the inner creds are themselves composite. It appears this could be fixed simply by recursively calling duplicate_without_call_credentials on the inner creds.

**Comment by jboeuf** [comment]
CC'ing @justinburke and @dgquintas FYI.

**Comment by ebf42** [comment]
Prompted by the stale bot, I took another look; I see the code in question has changed from C to C++, but the bug still appears to exist:
https://github.com/grpc/grpc/blob/a5d4bc14834b8f10fbe65a818ea7eb6c7a8d6da2/src/core/lib/security/credentials/composite/composite_credentials.h#L41-L44

That is, if 'inner_creds_' is itself composite, it seems to me this won't work as intended.

The fix would seem to be as simple as:
```c++
return inner_creds_->duplicate_without_call_credentials();
```

**Comment by apolcyn** [comment]
friendly ping @jiangtaoli2016 if you have time to take a look?

**Comment by markdroth** [comment]
Fixed in https://github.com/grpc/grpc/pull/34860.
