### ISSUE TITLE
grpc::CompositeCallCredentials() appears to not be defined anywhere

### ISSUE THREAD

**Issue by ebf42** [grpc/grpc#12556]
It's declared here:

https://github.com/grpc/grpc/blob/fc57518ac1999743da3f618193e9d2240a5660c1/include/grpc++/security/credentials.h#L185-L188

But the function doesn't appear to be defined anywhere. Indeed, writing code that calls it results in a linker error when building.

**Comment by jboeuf** [comment]
Good one... Looks like this code gets used a lot... not.
@yang-g FYI.

**Comment by yang-g** [comment]
I can add it :)

**Comment by jboeuf** [comment]
That would be great if you have time. Thanks!
