### ISSUE TITLE
Memory leakage about subchannel_index

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12560]
#12326 fixed the crash problem that is caused by reordering the steps in `grpc_shutdown()`. But it creates a memory leakage issue about `subchannel_index`. 

Instead of relying on the last one unref'ing the resource to destroy it, we should force polling to flush any pending callbacks, then destroy the `subchannel_index` safely during normal shutdown.

**Comment by yang-g** [comment]
Has this been fixed already?

**Comment by AspirinSJL** [comment]
I think this issue still exists. I haven't looked at it for quite a while. @sreecha said this is a hard issue to solve. Given that it happens during shutdown phase, so we lowered its priority.

**Comment by markdroth** [comment]
We may wind up fixing this as part of the plan we talked about last Friday, where we will change the subchannel index to hold strong refs to the subchannels and then have a periodic GC pass via a timer.  Once we have that in place, I think we can simply unref everything in the subchannel index at shutdown time.

**Comment by apolcyn** [comment]
@markdroth is this still relevant?

**Comment by markdroth** [comment]
Yes, still relevant.  At some point, we still need to fix the subchannel ref-counting.

**Comment by markdroth** [comment]
I'm fairly certain this is obsolete.  The code has changed numerous times since this was filed.  We've completely redesigned the subchannel pool APIs, and when we finish migrating to the new CoreConfiguration mechanism, `grpc_shutdown()` will go away completely anyway.
