### ISSUE TITLE
Unable to run app locally with dev_appserver.py due to "ImportError: No module named grpc._cython.cygrpc"

### ISSUE THREAD

**Issue by iros** [grpc/grpc#12579]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes
  
### What version of gRPC and what language are you using?
 
 1.6.0

### What operating system (Linux, Windows, …) and version?

OSX 10.11.6 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Python:
2.7.13 :: Continuum Analytics, Inc.

GCC:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
 
### What did you do?

Running `dev_appserver.py app.yaml`.

Current `app.yaml` file:

```yaml
runtime: python27
entrypoint: gunicorn -b :$PORT main:app
service: data-api-service

threadsafe: false

# [START handlers]
handlers:
- url: /.*
  script: main
# [END handlers]

resources:
  cpu: 1.0
  memory_gb: 2.0
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 3
  max_num_instances: 13
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

env_variables:
    GOOGLE_APPLICATION_CREDENTIALS: "./cred.json"
    API_MODE: 'PROD'
```

Current `appengine_config.py`:
```python
from google.appengine.ext import vendor
# Add any libraries installed in the "lib" folder.
vendor.add('lib')
```

Current `requirements.txt`:
```
Flask==0.11.1
flask-restplus==0.9.2
protobuf==3.0.0
grpcio==1.6.0
gcloud==0.18.3
google-api-python-client==1.6.3
gunicorn==19.6.0
python-dateutil==2.5.3
python-dotenv==0.6.0
universal-analytics-python==0.2.4
googleapis_common_protos==1.5.2
```

### What did you expect to see?

The server does start. The issue occurs when I actually try to visit `localhost:8080`.
 
### What did you see instead?

Console output:
```
/Users/iros/dev/opensource/mlab/mlab-vis-api/lib/dotenv/main.py:24: UserWarning: Not loading  - it doesn't exist.
  warnings.warn("Not loading %s - it doesn't exist." % dotenv_path)
ERROR    2017-09-14 19:03:40,527 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/iros/dev/tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/iros/dev/tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/iros/dev/tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/main.py", line 14, in <module>
    from mlab_api.endpoints.locations import locations_ns
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/mlab_api/endpoints/locations.py", line 10, in <module>
    from mlab_api.data.data import LOCATION_DATA as DATA
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/mlab_api/data/data.py", line 9, in <module>
    from mlab_api.data.location_data import LocationData
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/mlab_api/data/location_data.py", line 5, in <module>
    from mlab_api.data.base_data import Data
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/mlab_api/data/base_data.py", line 10, in <module>
    import mlab_api.data.bigtable_utils as bt
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/mlab_api/data/bigtable_utils.py", line 8, in <module>
    from gcloud import bigtable
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/lib/gcloud/bigtable/__init__.py", line 18, in <module>
    from gcloud.bigtable.client import Client
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/lib/gcloud/bigtable/client.py", line 32, in <module>
    from grpc.beta import implementations
  File "/Users/iros/dev/opensource/mlab/mlab-vis-api/lib/grpc/__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
  File "/Users/iros/dev/tools/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 1091, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named grpc._cython.cygrpc
INFO     2017-09-14 19:03:40,555 module.py:821] data-api: "GET / HTTP/1.1" 500 -
```

### Anything else we should know about your project / environment?

We have been previously running this as a standalone python flask app. We'd like to use the local app engine dev setup to ensure our configuration is correct. Can you assist in debugging this?

Additional things I've tried:

1. Downgrading versions of grpcio. Went as far as 0.13.1
2. Tried to add the flag `GRPC_BUILD_WITH_CYTHON=0|1` and have attempted both builds.

I followed the threads in issue #5280, but wasn't able to identify anything that would be of help. Linking it here since it appears to be related.

Thank you for your help.

**Comment by douglaseck** [comment]
FYI I'm having exactly the same problem.

**Comment by cgwy** [comment]
@iros 
@douglaseck 

What versions of Google Cloud Sdk are you using ?

Would "gcloud components update" solve this issue?

**Comment by cgwy** [comment]
@douglaseck  
Also, the current app.yaml would not work.

Listing grpcio in requirements.txt would not let dev_appserver accept it, because grpc is a [built-in bundled library](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27) with C-extension for python27 runtime. 

See [this doc](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#local_development) for using built-in bundled libraries with the local development server

To use it on local development server, you need to:
Step 1:  pip install grpcio
Step 2:  Add following lines in app.yaml:
```yaml
libraries:
- name: grpcio
  version: latest
```

Also, @douglaseck  you are trying google cloud client library. Although app engine python27 runtime does support grpcio, it does not officially support arbitrary google cloud client library yet. FYI, this [release note](https://cloud.google.com/appengine/docs/standard/python/release-notes#august_28_2017)
