### ISSUE TITLE
Pecl install GRPC fails on certain platforms with zlib error

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc#12597]
Steps to replicate:

```
docker pull php:5.6
docker run -it php:5.6 /bin/bash
# This will put you on the shell of the running docker container. Now run:
pecl install grpc
```

The following error will be thrown:

```
/tmp/pear/temp/grpc/src/core/lib/compression/message_compress.c:41:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
Makefile:310: recipe for target 'src/core/lib/compression/message_compress.lo' failed
make: *** [src/core/lib/compression/message_compress.lo] Error 1
ERROR: `make' failed
```

The fix is to install zlib:

```
apt-get install zlib1g-dev
```

**Comment by stanley-cheung** [comment]
Yea this is somewhat intended. We experimented with whether or not to statically compile zlib into the pecl extension but run into other issues in some other platforms like CentOS. So we decided not to package zlib and instead asks the user to install zlib as a pre-requisite, as documented here: https://grpc.io/docs/quickstart/php.html#install-on-linux

**Comment by jim5359** [comment]
Using PHP 7.2 on Ubuntu 18.04 I had to install zlib dev this way:
`sudo apt-get install zlib1g-dev`

**Comment by jim5359** [comment]
It would be nice to add zlib1g-dev to the documentation for Ubuntu installation.  The documentation only covers this for CentOS/RHEL 7

**Comment by M1ke** [comment]
Had the same issue building this in the `webdevops/php-apache-dev:7.0` docker container. Adding `apt-get install zlib1g-dev` to the Dockerfile solved it.
