### ISSUE TITLE
[c# enhancement] auto-generated in file header

### ISSUE THREAD

**Issue by wazowsk1** [grpc/grpc#12604]
Using grpc 1.4.1 c#

The following header is used in the generated code
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto
```

Can we use the following header? This will tell various analyzers to not analyze the generated code which can result in various error/warnings/messages.
```
//----------------------
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Test.proto
// </auto-generated>
//----------------------
```

**Comment by vinaychandra** [comment]
This is not completely fixed. Only `SomeNameGrpc` contains the header now. `SomeFile` file still uses 
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: somename.proto
```

**Comment by jtattermusch** [comment]
Note: The google/protobuf counterpart relies on https://github.com/google/protobuf/pull/4038 being released.
