### ISSUE TITLE
internal py34.test.* failed

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#12619]
From #12495
https://sponge.corp.google.com/invocation?tab=Kokoro&id=1e3604c5-cf8d-4216-8d4c-5796acc17638&searchFor=

**Comment by ZhouyihaiDing** [comment]
Also in https://kokoro.corp.google.com/job/grpc/job/macos/job/pull_request/job/grpc_basictests_dbg/2159/

**Comment by nathanielmanistaatgoogle** [comment]
Closing as a duplicate of [issue 12620](https://github.com/grpc/grpc/issues/12620).
