### ISSUE TITLE
grpc-php

### ISSUE THREAD

**Issue by songkemail** [grpc/grpc#1266]
hi tbetbetbe，I really appreciate what you have done.But I can't clone the code in accordance with your instructions.I appreciate your helping me.

**Comment by murgatroid99** [comment]
Can you explain what you tried, and what error messages you got, if any?

**Comment by songkemail** [comment]
git clone git@github.com:google/protobuf.git
git clone git@github.com:murgatroid99/Protobuf-PHP.git
I can't clone the code,is php is private?

**Comment by tbetbetbe** [comment]
Hi,
This looks as if you can't clone either github repo.  I think there is an issue with your github SSH setup
Can you try
- reviewing [github's docs on ssh keys](https://help.github.com/articles/generating-ssh-keys/)
- modifying your set-up
- then try again
?
Please let us know if that works or not.

**Comment by songkemail** [comment]
Thanks a lot,it works.I have clone the code from github directly.
