### ISSUE TITLE
py34.test.unit._rpc_test.RPCTest  timeout

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12668]
Seeing this regularly on master.

https://sponge.corp.google.com/target?id=9b58e38b-e748-4d15-b3cb-a46fa3e6b12e&target=github/grpc/python_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```
Timeout
[92mSUCCESS       unit._rpc_test.RPCTest.testFailedUnaryRequestFutureUnaryResponse
[0mRunning       unit._rpc_test.RPCTest.testFailedUnaryRequestStreamResponse
[92mSUCCESS       unit._rpc_test.RPCTest.testFailedUnaryRequestStreamResponse
[0mRunning       unit._rpc_test.RPCTest.testIgnoredStreamRequestFutureUnaryResponse
[92mSUCCESS       unit._rpc_test.RPCTest.testIgnoredStreamRequestFutureUnaryResponse
[0mRunning       unit._rpc_test.RPCTest.testIgnoredStreamRequestStreamResponse
[92mSUCCESS       unit._rpc_test.RPCTest.testIgnoredStreamRequestStreamResponse
[0mRunning       unit._rpc_test.RPCTest.testIgnoredUnaryRequestFutureUnaryResponse
```

**Comment by jtattermusch** [comment]
```
Timeout
++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py27/bin/python
+ PYTHON=/var/local/git/grpc/py27/bin/python2.7
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py27/bin/python2.7 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       unit._rpc_test.RPCTest.testCancelledStreamRequestStreamResponse
[95mTesting gRPC Python...
[0m[92mSUCCESS       unit._rpc_test.RPCTest.testCancelledStreamRequestStreamResponse
[0mRunning       unit._rpc_test.RPCTest.testCancelledStreamRequestUnaryResponse
[92mSUCCESS       unit._rpc_test.RPCTest.testCancelledStreamRequestUnaryResponse
[0mRunning       unit._rpc_test.RPCTest.testCancelledUnaryRequestStreamResponse
[92mSUCCESS       unit._rpc_test.RPCTest.testCancelledUnaryRequestStreamResponse
[0mRunning       unit._rpc_test.RPCTest.testCancelledUnaryRequestUnaryResponse
```

**Comment by dgquintas** [comment]
Ping. This has been happening (about 13% of the time). The latest instance: 
https://sponge.corp.google.com/target?id=7077001e-a89c-46f6-992b-335dbd14a1e0&target=github/grpc/python_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch, @dgquintas: what can we do to discriminate between the test hanging and the test simply being starved of resources by the test infrastructure? If we give it less time to run, does it still mostly pass but time out more often? If we give it more time to run, does it still mostly pass but time out less often? If we give it uncontested, dedicated computational resources, does it always pass or still sometimes time out?

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle, not sure what the test is doing, but for python being out of resources is quite a long shot.

With our current setup, only 2 suites (the `-j 2`) can run at the same time (suite = e.g. "python dbg" or "csharp opt"...), while most wrapped languages have pretty lightweight tests. C and C++ tests (which are the heavyweight ones) are running on a completely different VM so they cannot influence python at all.
All tests are running on a 16core VM, which is relatively beefy.
It's of course hard to know 100%, but I think everything points to this being an actual bug.
https://github.com/grpc/grpc/blob/54e8f37e537794c2d814c1604c1282125f64f093/tools/internal_ci/linux/pull_request/grpc_basictests_multilang.cfg

**Comment by jtattermusch** [comment]
And I'm pretty sure increasing timeout won't help:
The average runtime of the test is between 35-40sec when passing, while the instances that timeout are getting terminated at 300sec.

Here's the bigquery to check that yourself:
```
select * from jenkins_test_results.aggregate_results where test_name like '%py34.test.unit._rpc_test.RPCTest%' and job_name like 'grpc/ubuntu/master/%basictests%' and timestamp > '2017-10-25 00:00'   order by build_id desc limit 10000 
```

**Comment by dgquintas** [comment]
This test is currently [about 20% flaky](https://screenshot.googleplex.com/D4Tu0bQxBG3), ~10% [on windows](https://sponge.corp.google.com/target?id=ff0a62de-188e-4dcf-a32c-08418ba76311&target=github/grpc/python_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS), ~10% [on linux](https://sponge.corp.google.com/target?id=6152cd39-4083-459a-9642-6f0248aa0867&target=github/grpc/python_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS).

**Comment by jtattermusch** [comment]
This is currently one of our top flakes, are there any updates?

**Comment by kpayson64** [comment]
I'll look at this one today.
