### ISSUE TITLE
FLAKE: c_linux_asan_native.bins/asan/h2_proxy_test cancel_after_invoke GRPC_POLL_STRATEGY=epoll1

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#12684]
Happened in https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/7273/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_proxy_test_cancel_after_invoke_GRPC_POLL_STRATEGY_epoll1/

**Comment by dgquintas** [comment]
Duplicate of #12394
