### ISSUE TITLE
PHP: a bug in call flags being reset

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#12697]
This line: https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/call.c#L418 shouldn't have been there because `flags` were just set above:

https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/call.c#L329

**Comment by thinkerou** [comment]
Maybe we should move line 417/418/419 to begin of loop.

**Comment by vjpai** [comment]
@stanley-cheung : please update with the status of this issue. I restarted tests on the PR
