### ISSUE TITLE
gRPC performance PR logs are >300MB

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12693]
Randomly looked at a few builds,
(https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_performance_pull_requests/14928/console
)

I saw huge log sizes, around 380MB per run.

Problems:
1. This has potential to kill jenkins master eventually (disk will become full)
2. Such big logs are useless.
3. Might contribute to builds timing out.

We are working on migrating the performance PR builds to Kokoro, but it will take a while before we're there (and it will only address a few of the concerns noted).

**Comment by jtattermusch** [comment]
CC @matt-kwong, @ctiller

**Comment by ctiller** [comment]
I've definitely used these logs to diagnose bmdiff problems before, and will need to again: they're certainly not useless.

Doesn't Jenkins clean these up anyway after some number of builds? I don't see a problem here.
