### ISSUE TITLE
grpc build fails on ppc64le 

### ISSUE THREAD

**Issue by snehlatamohite** [grpc/grpc#12694]
Hi ,

We are trying to build the grpc build but build fails with below error . We could able to successfully build the package after changing  82 line in file `/grpc/third_party/benchmark/src/cycleclock.h`
`tbl &= -static_cast<int64>(tbu0 == tbu1);` to    `tbl &= -static_cast<**int64_t>(**tbu0 == tbu1);`

We could able to build it successfully after doing the change mentioned above & then also able to validate all tests. 

Also the above mentioned change is already implemented in the benchmark package so grpc needs to rebuild with latest benchmark version.  Please provide your inputs on the same. 

```
In file included from /grpc/third_party/benchmark/src/sysinfo.cc:44:0:
/grpc/third_party/benchmark/src/cycleclock.h: In function 'int64_t benchmark::cycleclock::Now()':
/grpc/third_party/benchmark/src/cycleclock.h:82:23: error: expected type-specifier before 'int64'
   tbl &= -static_cast<int64>(tbu0 == tbu1);
                       ^
/grpc/third_party/benchmark/src/cycleclock.h:82:23: error: expected '>' before 'int64'
/grpc/third_party/benchmark/src/cycleclock.h:82:23: error: expected '(' before 'int64'
/grpc/third_party/benchmark/src/cycleclock.h:82:23: error: 'int64' was not declared in this scope
/grpc/third_party/benchmark/src/cycleclock.h:82:43: error: expected ')' before ';' token
   tbl &= -static_cast<int64>(tbu0 == tbu1);
                                           ^
make[2]: *** [third_party/benchmark/src/CMakeFiles/benchmark.dir/build.make:327: third_party/benchmark/src/CMakeFiles/benchmark.dir/sysinfo.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7414: third_party/benchmark/src/CMakeFiles/benchmark.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Thanks,
Snehlata Mohite.

**Comment by mehrdada** [comment]
Is it related to this issue on the benchmark repo? https://github.com/google/benchmark/issues/449 If so, shouldn't we wait for that to be closed first?

I can see that the line is changed in `fef203bd` on `google/benchmark` in January 2017, but the change is different from your suggestion. Are you positive that simply updating `google/benchmark` submodule to today's `HEAD` will resolve the issue?

**Comment by snehlatamohite** [comment]
@mehrdada - google/benchmark#449 and my issue is same. W should use updated benchmark code in grpc in order to fix the issue.

**Comment by snehlatamohite** [comment]
I have started validating  GRPC build on PPC64le using google/benchmark  submodule to  v1.2 . I could able to build GRPC successfully with google/benchmark  v1.2 .  version. Now will run test suits as well.

**Comment by snehlatamohite** [comment]
I could able to validate C,C++,node,ruby & sanity tests successfully with benchmark version 1.2.0.

**Comment by mehrdada** [comment]
`google/benchmark` submodule is updated on `master`. Closing this issue.
