### ISSUE TITLE
OpenTracing support for grpc c++

### ISSUE THREAD

**Issue by wjywbs** [grpc/grpc#12707]
### What version of gRPC and what language are you using?
 1.6
 
### What did you do?
Is the census code ready to use with OpenTracing / Jaeger? Are there any examples to use the census code in C++?

https://github.com/grpc/grpc/tree/master/src/core/ext/census
 
### What did you expect to see?
 Documentation or status report of the census extension. gRPC, OpenTracing and Jaeger are all CNCF projects, and I expect to see them integrate with each other. Thanks.

**Comment by vjpai** [comment]
Does https://github.com/grpc-ecosystem/grpc-opentracing provide what you need?

**Comment by calder** [comment]
https://github.com/grpc-ecosystem/grpc-opentracing currently has only gRPC, Java, and Python implementations.

**Comment by wjywbs** [comment]
Thanks @calder, grpc-opentracing does not have a c++ implementation yet.

**Comment by wjywbs** [comment]
By the way, I found that all census code were removed in bb7d088ed2ea79bdad2917b7be86bad622d1f790.

**Comment by Falco20019** [comment]
It seems like work on [opentracing-cpp](https://github.com/opentracing/opentracing-cpp) and [opentracing-csharp](https://github.com/opentracing/opentracing-csharp) have finally started :)

**Comment by Falco20019** [comment]
#12613 got merged today. I will look into doing the grpc-opentracing implementation for C# when the next release including this version (v1.10.x) is done.

I think, once #9035 is takled, an grpc-opentracing implementation on grpc-core level would be much appreciated. Until then, it's hard since the C++ implementation doesn't have any interceptor functionality AFAIK. OpenTracing itself has a C++ implementation, so the only thing missing are the interceptors.

**Comment by jxd134** [comment]
Waht a pity.
I think it was useful to add interceptor in grpc-cpp for user.

**Comment by pgn-vole** [comment]
I +1 this feature request.

**Comment by Falco20019** [comment]
https://github.com/opentracing-contrib?tab=repositories is the main account for OpenTracing implementations. So better to look there for packages. Java and Python also made references on grpc-ecosystem but new once won’t appeare there.

The C++ Version is still not possible until #9035 is implemented :) so maybe also track that issue.

**Comment by rnburn** [comment]
I'm looking into adding OpenTracing support for C++.

What's the plan with gRPC's [channel_filter](https://github.com/grpc/grpc/blob/master/src/cpp/common/channel_filter.h) interface?

I believe it would be possible to add OpenTracing support with it, and it's what OpenCensus was [using](https://github.com/census-instrumentation/opencensus-cpp/blob/cd3f7109e5ac046c2c0347c68eeeb7f544714072/opencensus/plugins/grpc/internal/filter.h#L26) before its plugin was moved into gRPC's repository.

It looks like the header is available from gRPC's bazel build, but not installed by gRPC.

Is the intention to make channel_filter part of gRPC's public interface at some point and available from not just bazel?

**Comment by isaachier** [comment]
Maybe add a [filter](https://github.com/grpc/grpc/tree/master/src/cpp/ext/filters) for OpenTracing @rnburn? I imagine this is dynamically load so it won't need to be part of the gRPC source tree.

**Comment by isaachier** [comment]
I guess that is probably based on the channel filter interface anyway. Ya I'd love to see it moved to the public API as well.

**Comment by rnburn** [comment]
@isaachier - that's what I'm considering. But adding such a filter would require you to include the [channel_filter.h](https://github.com/grpc/grpc/blob/master/src/cpp/common/channel_filter.h) header, which seems to be only available if you're using bazel. (I don't see it installed anywhere).

**Comment by rnburn** [comment]
@mehrdada, @Vizerai - could you let us know that the future of the channel filter interface is?
