### ISSUE TITLE
gRPC complains about Kick failed billions of times!!!!!!

### ISSUE THREAD

**Issue by dutor** [grpc/grpc#12704]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 
C++, gRPC 1.4.2
 
### What operating system (Linux, Windows, …) and version?
 Linux 3.10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
GCC 6.2
 
### What did you do?

An async client sent unary requests to a group of async servers at the rate of 20w/s.
 
### What did you expect to see?
 
Without exceptions.
 
### What did you see instead?
 
After a while of running, gRPC at the client side printed billions of  `Kick failed` messages.
 
```
E0925 17:21:42.759336694  106490 ev_epollsig_linux.c:1218]   pollset_kick: {"created":"@1506331302.759324417","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epollsig_linux.c","file_line":275,"referenced_errors":[{"created":"@1506331302.759323926","description":"OS Error","errno":11,"file":"src/core/lib/iomgr/ev_epollsig_linux.c","file_line":1131,"os_error":"Resource temporarily unavailable","syscall":"pthread_kill"}]}
```

**Comment by shao1555** [comment]
me too...

**Comment by sreecha** [comment]
- Is your program doing something with unix signals ? (more specifically with signal 40 ? i.e  `SIGRTMIN+6`  ) like masking signals or registering a custom signal handler ? 

- Can you do `ulimit -a` and paste the outputhere? (I am more interested in seeing the `pending signals` limit)

**Comment by dutor** [comment]
@sreecha Thanks for the reply.

Here are all signals my program explicitly uses: `SIGINT`, `SIGTERM`, `SIGUSR1`, `SIGUSR2`.

Here are `ulimit -a`s outputs:
```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1030587
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655360
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 655360
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by dutor** [comment]
This issue seems more critical now.

Because the rt signal is queued tooo many, epoll_pwait always return immediately, which leads to high CPU usage. And, thanks to the error log, mutex (possible) from inside the vsprintf family is highly contended. All these things make the performance of our application degrades terribly.

**Comment by dutor** [comment]
Here is my questions that you guys maybe enlight me:
 * When `pthread_kill` or `pollset_worker_kick` is invoked, in what kind of context.
 * I saw the `is_kicked` atomic operation, but how could gRPC can guarantee that the queued signals are consumed up in time, at the same pace with `pthread_kill`. AFAK, invoking the signal handler is completely up to the kernel.

**Comment by sreecha** [comment]
Hmm..I am not exactly sure what is going on your application.. it seems like the for some reason, the  signal `SIGMINRT+6` is not getting delivered and getting queued up. In the past the only times I saw such an error was either (a) if the application was explicitly blocking the signal or (b) if it registered a custom signal handler and then re-raising that signal (which is left unhandled)

Now to answer your questions:
- `pollset_worker_kick` (which calls `pthread_kill`) is called when there is an event on the completion queue - and the thread that is interested in that event is potentially blocked in inside `epoll_pwait`.   So we use this signal (`pthread_kill`) to get that thread out of `epoll_pwait`  

- `is_kicked` is used to prevent calling another `pthread_kill` on a thread that already received a signal. 
The signal here is used as a mechanism to interrupt a thread and bring it out of `epoll_pwait` - so when exactly the signal handler is invoked isn't super critical (also I do _not_ think the kernel is delaying delivering this signals so much that it results the errors you are seeing. Moreover, your `ulimit -i` i.e the `pending signals` queue size is over a million which is pretty big).

---
### Solution:
We will be releasing version 1.7 very soon (in the next couple of weeks or so) and that uses a completely different polling engine by default that does not use signals. Once you upgrade to 1.7 you will not be seeing this issue

### Short-term mitigation:
To mitigate this in the **short term**, you can use a different polling engine by setting the environment variable `GRPC_POLL_STRATEGY` to `poll` before launching your application ?
This will use a different polling engine that does not use signals. Please note that this does not scale well for a large number of file descriptors (i.e thousands of concurrent connections)

**Comment by dutor** [comment]
I added some thread local state counters in `ev_epollsig_linux.c` to trace serveral actions. Here are the counters of one specific CQ(thread) out of 32 ones:

 * `pollset_worker_kick` called 1445968 times.
 * `"finally_kick"` from `pollset_kick` called 1445968 times.
 * `pthread_kill` called 600000 times.
 * `pthread_kill` failed with `EAGAIN` 556575 times.
 * `epoll_pwait` called 101149 times.
 * `epoll_pwait` failed with `EINTR` 8610 times.
 * signal handler called 8610 times.

As shown, the signal handler is invoked only if (but not every time) `epoll_pwait` called, which is reasonable due to the sigmask. Although `kick`s or `pthread_kill`s are for to other CQ threads from this specific thread, numbers of every thread are overall the same. The peculiar thing is that `pthread_kill` is invoked way more times than signal handler.

@sreecha

**Comment by sreecha** [comment]
Thanks for the info @dutor 
You are right that the `pthread_kill` counts are from the current thread to the _other_ threads but if the counts are this high for every thread, then this is very peculiar..

Is there a lot of thread-churn in your application ? - i.e are the set of 32 threads polling the cqs changing constantly ? - if so, that might explain this behavior.

**Comment by dutor** [comment]
@sreecha 
 * I wrote a demo application, and it does not use any RT signals.
 * `is_kicked` is for every `poolset_worker`, but not an thread.
 * Although timing of the invoke of signal handler is not critical for the main logics, but the chances that the handler get invoked are tiny.

**Comment by dutor** [comment]
@sreecha I don't quite follow what _thread-churn_ and _changing_ mean. I have 32 threads each of which runs its own CQ. In each thread, they handle requests from remote, and request to remote at the same time, all in a async way.

**Comment by dutor** [comment]
FYR.

Every thread runs this:
```cpp
    auto run = [this] (ServerCompletionQueue *cq, GrpcClient *client) {
        new CallData(&service_, cq, client);
        void *tag = NULL;
        bool ok;
        while (true) {
            cq->Next(&tag, &ok);
            if (!ok) {
                break;
            }
            (*reinterpret_cast<Tag*>(tag))();
        }
    };
```

`Tag` is a `CallData`, whose `operator()` is:
```cpp
CallData::operator()() {
     if (status_ == PROCESS) {
        new CallData(service_, cq_, client_);
        status_ = FINISH;
        if (req_.hop() == 1) {
            resp_.set_msg(req_.msg());
            responder_.Finish(resp_, Status::OK, this);
            return;
        }
        auto cb = [this] (EchoResponse *resp) {
            resp_.set_msg(req_.msg());
            responder_.Finish(resp_, Status::OK, this);
        };
        req_.set_hop(req_.hop() - 1);
        client_->Echo(req_, std::move(cb));
    } else if (status_ == FINISH) {
        delete this;
    } else {
        assert(false);
    }
}

```

The demo is an async echo server. Every echo message has a `hop` field. If the `hop` reaches 0, the server send response directly, or it would redirect the message to another server with `hop` decrease by `.

**Comment by sreecha** [comment]
Do you have two servers ? or is the server sending to itself? - Would you be able to share the whole demo program so that I can try to repro the issue here?

By the way, we are releasing grpc version 1.7 this week and that will fix the issue you are seeing. If you want to try this out, the changes are already at HEAD.

**Comment by dutor** [comment]
Yes, I have one async client, and two async server talking to each other. Later, I could extract the main codes of my demo and paste them here.

I will wait for your release of 1.7.

**Comment by dutor** [comment]
This is the proto definition.
```protobuf
syntax = "proto3";
package echo.proto;

option cc_generic_services = false;
option optimize_for = SPEED;
import "google/protobuf/empty.proto";

message EchoRequest
{
    string msg = 1;
    uint32 hop = 2;
}

message EchoResponse
{
    string msg = 1;
}

service EchoService
{
    rpc Echo(EchoRequest) returns (EchoResponse);
}
```

This is Server.

```cpp
#include <thread>
#include <mutex>
#include <atomic>
#include <grpc++/grpc++.h>
#include "proto/echo_api.pb.h"
#include "proto/echo_api.grpc.pb.h"
namespace echo {

/**
 * GrpcClient, GrpcAsyncServer, etc.
 */
class Tag {
public:
    virtual ~Tag() {}
    virtual void operator()() = 0;
};

class ClosureBase : public Tag {
public:
    ClosureBase() = default;
    virtual ~ClosureBase() = default;
    grpc::ClientContext& context() {
        return context_;
    }

    grpc::Status& status() {
        return status_;
    }

protected:
    grpc::ClientContext         context_;
    grpc::Status                status_;
};
template <typename Resp>
class Closure : public ClosureBase {
public:
    explicit Closure(std::function<void(Resp*)> &&);
    virtual ~Closure() = default;
    using AsyncPtr = std::unique_ptr<grpc::ClientAsyncResponseReader<Resp>>;
    void finish(AsyncPtr ptr);
    void operator()() override;
private:
    AsyncPtr                    asyncPtr_;
    Resp                        resp_;
    std::function<void(Resp*)>  callback_;
};

class GrpcClient {
public:
    using CompletionQueue = grpc::CompletionQueue;
    using EchoService = echo::proto::EchoService;
    using Stub = EchoService::Stub;
    using EchoRequest = echo::proto::EchoRequest;
    using EchoResponse = echo::proto::EchoResponse;

    GrpcClient(std::shared_ptr<CompletionQueue> cq, std::unique_ptr<Stub> stub);
    ~GrpcClient();

    void Echo(const EchoRequest &request, std::function<void(EchoResponse*)> callback);

private:
    std::shared_ptr<CompletionQueue>            cq_;
    std::unique_ptr<Stub>                       stub_;
};

template <typename Resp>
Closure<Resp>::Closure(std::function<void(Resp*)> &&callback)
    : callback_(std::move(callback)) {
}

template <typename Resp>
void Closure<Resp>::finish(AsyncPtr ptr) {
    //asyncPtr_ = std::move(ptr);
    //asyncPtr_->Finish(&resp_, &status_, reinterpret_cast<void*>(this));
    ptr->Finish(&resp_, &status_, reinterpret_cast<void*>(this));
}

template <typename Resp>
void Closure<Resp>::operator()() {
    if (status_.ok()) {
        callback_(&resp_);
    } else {
        callback_(nullptr);
    }
    delete this;
}

GrpcClient::GrpcClient(std::shared_ptr<CompletionQueue> cq, std::unique_ptr<Stub> stub) {
    cq_ = std::move(cq);
    stub_ = std::move(stub);
}

GrpcClient::~GrpcClient() {
}

void GrpcClient::Echo(const EchoRequest &req, std::function<void(EchoResponse*)> callback) {
    auto closure = new Closure<EchoResponse>(std::move(callback));

    closure->finish(stub_->AsyncEcho(&closure->context(), req, cq_.get()));
}


class GrpcAsyncServer {
public:
    GrpcAsyncServer(std::string local, std::string remote, size_t nr_cq);
    void stop();
    void wait();
private:
    using Status = grpc::Status;
    using ServerContext = grpc::ServerContext;
    using Server = grpc::Server;
    using ServerBuilder = grpc::ServerBuilder;
    using ServerCompletionQueue = grpc::ServerCompletionQueue;
    using EchoRequest = echo::proto::EchoRequest;
    using EchoResponse = echo::proto::EchoResponse;

    class CallData : public Tag {
    public:
        using Status = grpc::Status;
        using ServerContext = grpc::ServerContext;
        using ServerCompletionQueue = grpc::ServerCompletionQueue;
        using EchoRequest = echo::proto::EchoRequest;
        using EchoResponse = echo::proto::EchoResponse;

        CallData(proto::EchoService::AsyncService *service,
                ServerCompletionQueue *cq, GrpcClient *client);
        void operator()() override;

    private:
        enum CallStatus {
            PROCESS,
            FINISH,
        };
        CallStatus                                  status_;
        proto::EchoService::AsyncService           *service_;
        ServerCompletionQueue                      *cq_;
        GrpcClient                                 *client_;
        ServerContext                               ctx_;
        EchoRequest                                 req_;
        EchoResponse                                resp_;
        grpc::ServerAsyncResponseWriter<EchoResponse>     responder_;
    };

private:
    std::atomic<bool>                                       stopped_{false};
    ServerBuilder                                           builder_;
    std::vector<std::unique_ptr<std::thread>>               threads_;
    std::vector<std::shared_ptr<ServerCompletionQueue>>     cqs_;
    proto::EchoService::AsyncService                        service_;
    std::unique_ptr<Server>                                 server_;
    std::vector<std::unique_ptr<GrpcClient>>                clients_;
};

GrpcServer::GrpcServer() {
}

GrpcServer::~GrpcServer() {
}

grpc::Status GrpcServer::Echo(ServerContext *ctx, const proto::EchoRequest *req,
                             proto::EchoResponse *result) {
    result->set_msg(req->msg());
    return Status::OK;
}

GrpcAsyncServer::GrpcAsyncServer(std::string local, std::string remote, size_t nr_cq) {
    builder_.AddListeningPort(local, grpc::InsecureServerCredentials());
    builder_.RegisterService(&service_);
    auto run = [this] (ServerCompletionQueue *cq, GrpcClient *client) {
        new CallData(&service_, cq, client);
        void *tag = NULL;
        bool ok;
        while (true) {
            cq->Next(&tag, &ok);
            if (!ok) {
                break;
            }
            (*reinterpret_cast<Tag*>(tag))();
        }
    };
    for (auto i = 0; i < nr_cq; i++) {
        std::shared_ptr<ServerCompletionQueue> cq = builder_.AddCompletionQueue();
        auto channel = std::shared_ptr<grpc::Channel>(
                grpc::CreateChannel(remote, grpc::InsecureChannelCredentials()));
        auto stub = echo::proto::EchoService::NewStub(std::move(channel));
        clients_.emplace_back(std::make_unique<GrpcClient>(cq, std::move(stub)));
        cqs_.emplace_back(cq);
    }
    server_ = builder_.BuildAndStart();

    for (auto i = 0; i < cqs_.size(); i++) {
        threads_.emplace_back(std::make_unique<std::thread>(run, cqs_[i].get(),
                                                            clients_[i].get()));
    }
}

void GrpcAsyncServer::stop() {
    if (!stopped_) {
        stopped_ = true;
        server_->Shutdown();
        for (auto &cq : cqs_) {
            cq->Shutdown();
        }
    }
}

void GrpcAsyncServer::wait() {
    for (auto &th : threads_) {
        th->join();
    }
}

GrpcAsyncServer::CallData::CallData(proto::EchoService::AsyncService *service,
        ServerCompletionQueue *cq, GrpcClient *client)
    : service_(service),
      cq_(cq),
      client_(client),
      responder_(&ctx_) {
    service_->RequestEcho(&ctx_, &req_, &responder_, cq_, cq_, this);
    status_ = PROCESS;
}

void GrpcAsyncServer::CallData::operator()() {
     if (status_ == PROCESS) {
        new CallData(service_, cq_, client_);
        status_ = FINISH;
        if (req_.hop() == 1) {
            resp_.set_msg(req_.msg());
            responder_.Finish(resp_, Status::OK, this);
            return;
        }
        auto cb = [this] (EchoResponse *resp) {
            resp_.set_msg(req_.msg());
            responder_.Finish(resp_, Status::OK, this);
        };
        req_.set_hop(req_.hop() - 1);
        client_->Echo(req_, std::move(cb));
    } else if (status_ == FINISH) {
        delete this;
    } else {
        assert(false);
    }
}

}
```

The client logics is like this:
```cpp
RateLimiter limiter;
GrpcAsyncClient clients[];
auto run = [] () {    // many threads run this
    while (!stopped) {
        limiter.take();    // rate limiter controls rate of request sending
        auto cb = [] (EchoResponse *resp) {
            limiter.release();
            // handle responses
        };
        // prepare requests
        auto client = pickClientRandomly();
        client->Echo(req, cb);
    }
};
```

**Comment by wylazy** [comment]
This problem may be solved by call service_->RequestEcho() many times before while loop to eliminate pthread_kill
```
    auto run = [this] (ServerCompletionQueue *cq, GrpcClient *client) {
        // Add for loop here
        for (int i = 0; i < 1024; i++) {
            new CallData(&service_, cq, client);  // call service_->RequestEcho()
        }
        void *tag = NULL;
        bool ok;
        while (true) {
            cq->Next(&tag, &ok);
            if (!ok) {
                break;
            }
            (*reinterpret_cast<Tag*>(tag))();
        }
    };
```

**Comment by dutor** [comment]
@wylazy Thanks for reply, but what's the rationale?

**Comment by wylazy** [comment]
@dutor Because your server has many CompletionQueues which are waiting at epoll_pwait(). When clients request so many RPC calls at the same time. One CompletionQueue will be awake first and read the requests from clients, but it can process only one request. So it put remainded requests to other CompletionQueues, and then call pthread_kill() many times to notify. 
    When clients send so many requests concurently, and epoll_pwait() returns, a notified worker thread can process many requests, but consume only one signal (other signals are queued). If your clients send requests constantly, pending signals will accumulate. 
    But if you call service_->RequestEcho() many times when init, this requests are queued at the CompletionQueue. When this CompletionQueue receive many RPC call from a client. It can process the RPC call itself. There is no need to call pthread_kill().

**Comment by sreecha** [comment]
@dutor , you should not be seeing this from 1.7 release onwards since 'epollsig' is no longer the default polling engine.

I am closing this issue.
