### ISSUE TITLE
grpc gen proto for php not working, protc-gen-php not found (I installed grpc,protobuf pecl ext)

### ISSUE THREAD

**Issue by netroby** [grpc/grpc#12714]
I am using ubuntu 17.10 + php 7.1 + installed pecl grpc , protobuf extension,
And i also installed protobuf-compiler protobuf-compiler-grpc

```
$ protoc --version
libprotoc 3.0.0

$ php -v
PHP 7.1.8-1ubuntu1 (cli) (built: Aug  8 2017 15:57:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-1ubuntu1, Copyright (c) 1999-2017, by Zend Technologies

$ which protoc
/usr/bin/protoc

$ which grpc_php_plugin
/usr/bin/grpc_php_plugin

protoc  --plugin=protoc-gen-grpc=/usr/bin/grpc_php_plugin  --php_out=src proto/blob.proto
protoc-gen-php: program not found or is not executable
--php_out: protoc-gen-php: Plugin failed with status code 1.


```

I am not using composer, i do not using it .

i just want to compile proto file to php. by your tools. but seems they do not working

**Comment by netroby** [comment]
For comparison, If you using apache thrift, you can compile thrift to php very easy
```
thrift -r --gen php o.thrift 

```

**Comment by stanley-cheung** [comment]
`protoc` version 3.0.0 does not have the `--php_out` plugin. You will need at least 3.3.0.

**Comment by netroby** [comment]
hello. i installed 3.4.1   but the same result




获取 Outlook for Android







On Wed, Sep 27, 2017 at 2:03 AM +0800, "Stanley Cheung" <notifications@github.com> wrote:












protoc version 3.0.0 does not have the --php_out plugin. You will need at least 3.3.0.

**Comment by ZhouyihaiDing** [comment]
I think you are missing grpc_php_plugin file.

If you build grpc from source, `grpc_php_plugin` is installed as part of it under `grpc/bins/opt/`.
If you only want `grpc_php_plugin`, you can clone grpc repo and then
```
cd grpc
git submodule update --init
make grpc_php_plugin
```

**Comment by ZhouyihaiDing** [comment]
Since there was no further update, I'm going to close that issue for now.
