### ISSUE TITLE
Generate is not a function nodejs

### ISSUE THREAD

**Issue by stellanhaglund** [grpc/grpc#12715]
Hi I have a jwt.proto file that looks like this.

```
syntax = "proto3";

service GenerateJwt {
    rpc Generate (UserDetails) returns (Token) {}
}

message UserDetails {
    string uuid = 1;
}

message Token {
    string token = 1;
}
```

And I run a c++ grpc server that use that proto, and connecting to it using a c++ grpc client works fine. but when I do this in node.

```
var PROTO_PATH = './jwt.proto';
var grpc = require('grpc');
var login = grpc.load(PROTO_PATH);

var jwt = new login.GenerateJwt(
    process.env.JWT_SERVICE_HOST + ':50051',
    grpc.credentials.createInsecure()
);

jwt.Generate({uuid: 'uuid'}, function(err, response){

});

```

I get `jwt.Generate is not a function` 
I do it just like this for some other services and it works fine it's just the `Generate` that doesn't work.

I have tried node version 8 and 6, the version of the grpc module in node is `"grpc": "^1.0.0"`

**Comment by stellanhaglund** [comment]
The problem was that the rpc can't start with a capital letter so if I change it to `jwt.generate` it works.
I don't know if this is expected functionality.

**Comment by murgatroid99** [comment]
In more recent versions, the code generated from `.proto` files recognizes both the exact original method name and the `camelCase` variant.
