### ISSUE TITLE
grpclb policy should propagate resolution updates to its pick_first unconditionally

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12727]
Currently, we use `updating_lb_channel` and `pending_update_args` in grpclb to make sure there is no overlapping updates into pick_first and only the latest pending update is used.

But this is unnecessary. We should propagate the resolution updates through the fake resolver unconditionally to pick_first, just like any other real resolver would do.

**Comment by markdroth** [comment]
Fixed via #12736.
