### ISSUE TITLE
GPR_UNREACHABLE_CODE causes error in XCode 9.0 with ios 11

### ISSUE THREAD

**Issue by rsugirthan** [grpc/grpc#12734]
/Users/sramachandran/iosApp/Pods/gRPC-Core/src/core/lib/surface/channel_stack_type.c:39:1: Control may reach end of non-void function

/Users/sramachandran/iosApp/Pods/gRPC-Core/src/core/lib/surface/channel_stack_type.c:57:1: Control may reach end of non-void function

Using MacOS HighSierra

**Comment by rsugirthan** [comment]
@ctiller @jtattermusch @murgatroid99 
Kindly have a look into it...

**Comment by hallwest** [comment]
+1 any update here?
