### ISSUE TITLE
allow LB policies to force DNS re-resolution without shutting down

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12731]
The current implementation causes some problems:

- The pending subchannels may not have a chance to be used (active) before the shutdown.
- (To be added)

As documented internally:

> When the LB policy wants to force a DNS resolution, the only way it can do this is to put itself into SHUTDOWN state.  This causes the client channel to unref the LB policy, call grpc_resolver_channel_saw_error(), and then recreate the LB policy when it gets the next resolver result.
>
> Destroying and recreating the LB policy seems fairly sub-optimal.  Instead, we should provide some sort of callback-based mechanism for the LB policy to request a re-resolution without destroying itself.  When the new resolver result comes in, it can be passed to the LB policy as an update.

**Comment by dgquintas** [comment]
Note that this will come out of the more ambitious change described in https://github.com/grpc/grpc/pull/12427#pullrequestreview-61333418 , whereby LB policies will be able to re-request resolutions without having to go into SHUTDOWN.

**Comment by AspirinSJL** [comment]
My idea is to simply add a channel state called `GRPC_CHANNEL_BAD_SUBCHANNELS` as a signal from the LB policies to ask the client channel to help request a re-resolution. This is very similar to how `GRPC_CHANNEL_SHUTDOWN` is interpreted now.

Please let me know if this method is insufficient.
