### ISSUE TITLE
build grpc on Linux failed for undefined reference?

### ISSUE THREAD

**Issue by jdcrew** [grpc/grpc#12738]
### What version of gRPC and what language are you using?
 grpc 1.4.0    Language: c++ 
 
### What operating system (Linux, Windows, …) and version?
 Linux 4d166a1b8b34 4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux      
on Docker
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc/g++
 
### What did you do?
I have built protobuf 3.3.1 before I building grpc, and protobuf built successfully.
Then I began build grpc with command in grpc director :
make & make install

and error is :

make[6]: Leaving directory `/home/gpadmin/thirdparty/protobuf-3.3.1/src'
make[5]: Leaving directory `/home/gpadmin/thirdparty/protobuf-3.3.1/src'
make[4]: Leaving directory `/home/gpadmin/thirdparty/protobuf-3.3.1'
make[3]: Leaving directory `/home/gpadmin/thirdparty/protobuf-3.3.1'
[CXX]     Compiling src/cpp/client/insecure_credentials.cc
[CXX]     Compiling src/cpp/client/secure_credentials.cc
[CXX]     Compiling src/cpp/common/auth_property_iterator.cc
[CXX]     Compiling src/cpp/common/secure_auth_context.cc
[CXX]     Compiling src/cpp/common/secure_channel_arguments.cc
[CXX]     Compiling src/cpp/common/secure_create_auth_context.cc
[CXX]     Compiling src/cpp/server/insecure_server_credentials.cc
[CXX]     Compiling src/cpp/server/secure_server_credentials.cc
[CXX]     Compiling src/cpp/client/channel_cc.cc
[CXX]     Compiling src/cpp/client/client_context.cc
[CXX]     Compiling src/cpp/client/create_channel.cc
[CXX]     Compiling src/cpp/client/create_channel_internal.cc
[CXX]     Compiling src/cpp/client/create_channel_posix.cc
[CXX]     Compiling src/cpp/client/credentials_cc.cc
[CXX]     Compiling src/cpp/client/generic_stub.cc
[CXX]     Compiling src/cpp/common/channel_arguments.cc
[CXX]     Compiling src/cpp/common/channel_filter.cc
[CXX]     Compiling src/cpp/common/completion_queue_cc.cc
[CXX]     Compiling src/cpp/common/core_codegen.cc
[CXX]     Compiling src/cpp/common/resource_quota_cc.cc
[CXX]     Compiling src/cpp/common/rpc_method.cc
[CXX]     Compiling src/cpp/common/version_cc.cc
[CXX]     Compiling src/cpp/server/async_generic_service.cc
[CXX]     Compiling src/cpp/server/channel_argument_option.cc
[CXX]     Compiling src/cpp/server/create_default_thread_pool.cc
[CXX]     Compiling src/cpp/server/dynamic_thread_pool.cc
[CXX]     Compiling src/cpp/server/health/default_health_check_service.cc
[C]       Compiling src/cpp/server/health/health.pb.c
[CXX]     Compiling src/cpp/server/health/health_check_service.cc
[CXX]     Compiling src/cpp/server/health/health_check_service_server_builder_option.cc
[CXX]     Compiling src/cpp/server/server_builder.cc
[CXX]     Compiling src/cpp/server/server_cc.cc
[CXX]     Compiling src/cpp/server/server_context.cc
[CXX]     Compiling src/cpp/server/server_credentials.cc
[CXX]     Compiling src/cpp/server/server_posix.cc
[CXX]     Compiling src/cpp/thread_manager/thread_manager.cc
[CXX]     Compiling src/cpp/util/byte_buffer_cc.cc
[CXX]     Compiling src/cpp/util/slice_cc.cc
[CXX]     Compiling src/cpp/util/status.cc
[CXX]     Compiling src/cpp/util/string_ref.cc
[CXX]     Compiling src/cpp/util/time_cc.cc
[HOSTCXX] Compiling src/compiler/cpp_generator.cc
[HOSTCXX] Compiling src/compiler/csharp_generator.cc
[HOSTCXX] Compiling src/compiler/node_generator.cc
[HOSTCXX] Compiling src/compiler/objective_c_generator.cc
[HOSTCXX] Compiling src/compiler/php_generator.cc
[HOSTCXX] Compiling src/compiler/python_generator.cc
[HOSTCXX] Compiling src/compiler/ruby_generator.cc
[AR]      Creating /home/gpadmin/thirdparty/grpc-1.4.0/libs/opt/libgrpc_plugin_support.a
[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTLD]  Linking /home/gpadmin/thirdparty/grpc-1.4.0/bins/opt/grpc_cpp_plugin
/home/gpadmin/thirdparty/grpc-1.4.0/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufPrinter':
/home/gpadmin/thirdparty/grpc-1.4.0/./src/compiler/protobuf_plugin.h:151: undefined reference to `google::protobuf::io::StringOutputStream::StringOutputStream(std::string*)'
/home/gpadmin/thirdparty/grpc-1.4.0/objs/opt/src/compiler/cpp_plugin.o: In function `void grpc_generator::GetComment<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, grpc_generator::CommentType, std::vector<std::string, std::allocator<std::string> >*)':
/home/gpadmin/thirdparty/grpc-1.4.0/./src/compiler/generator_helpers.h:236: undefined reference to `google::protobuf::FileDescriptor::GetSourceLocation(std::vector<int, std::allocator<int> > const&, google::protobuf::SourceLocation*) const'
/home/gpadmin/thirdparty/grpc-1.4.0/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufPrinter::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)':
/home/gpadmin/thirdparty/grpc-1.4.0/./src/compiler/protobuf_plugin.h:155: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/home/gpadmin/thirdparty/grpc-1.4.0/objs/opt/src/compiler/cpp_plugin.o:(.data.rel.ro._ZTV16CppGrpcGenerator[_ZTV16CppGrpcGenerator]+0x28): undefined reference to `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::string const&, google::protobuf::compiler::GeneratorContext*, std::string*) const'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/gpadmin/thirdparty/grpc-1.4.0/bins/opt/grpc_cpp_plugin] Error 1
make[2]: Leaving directory `/home/gpadmin/thirdparty/grpc-1.4.0'
make[1]: *** [build-grpc-recursive] Error 2
make[1]: Leaving directory `/home/gpadmin/thirdparty'
make: *** [/opt/dependency/grpc-1.4.0.version] Error 2
 
### What did you expect to see?
 compile without error
 

### Anything else we should know about your project / environment?
I thought this may caused by protobuf version/protobuf path ...
but MacOS can compile successfully with the same steps operations.

**Comment by kpayson64** [comment]
Do you have a version of protobuf installed locally?

**Comment by tankerkiller125** [comment]
I have this same issue, I have removed all version protobuf already installed on my machine. But it still failing with the same error has the person who created this ticket. Is their any solutions?

**Comment by srini100** [comment]
Do you have pkg-config installed?

**Comment by tankerkiller125** [comment]
@srini100 Yes I do, I have everything needed according the the requirments and other issues that I've seen solutions too

**Comment by srini100** [comment]
All I can suggest is to build/install protobuf from src. The Makefile in gRPC will skip this if current version is 3.0 or above. A recent change in Makefile now checks for 3.5. If you are build from HEAD then protobuf should be rebuilt automatically if 3.5+ is not already installed. Otherwise follow these steps:

cd third_party/protobuf
./autogen.sh
./configure
make
sudo make install
sudo ldconfig # refresh shared library cache.
