### ISSUE TITLE
TIMEOUT: run_ruby.sh ruby_linux_opt_native

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12740]
https://sponge.corp.google.com/target?id=695bfc29-0dae-4978-9096-894dc0a904ea&target=github/grpc/ruby_linux_opt_native&searchFor=&show=FAILED&sortBy=STATUS

The failure is a timeout of the overall `tools/run_tests/helper_scripts/run_ruby.sh` script. 

seen in PR https://github.com/grpc/grpc/pull/12721, but looks unrelated to that PR.

This failure can be reproduced on master with `run_tests.py -l ruby --use_docker -n inf -r run_ruby.sh` (flakes about 2%).

**Comment by jtattermusch** [comment]
I checked the historical data and we don't seems to be seeing ruby test timeouts in the last month.
