### ISSUE TITLE
[NodeJS] Promises and async/await

### ISSUE THREAD

**Issue by Tim15** [grpc/grpc#12751]
It would be nice if there was a `grpc-tools` and/or `grpc_node_plugin` option that would generate client and server code that follows the ES6 Promise and ES7 async/await model.

For example, instead of:
https://github.com/grpc/grpc/blob/98f8989a6712118549c432c9f91b6a516250014d/examples/node/static_codegen/greeter_client.js#L35-L37
We could write:
```
  [err, response] = await client.sayHello(request);
```
Or something similar. On the server side, instead of:
https://github.com/grpc/grpc/blob/98f8989a6712118549c432c9f91b6a516250014d/examples/node/static_codegen/greeter_server.js#L27-L31
We could write:
```
async function sayHello(call) {
  var reply = new messages.HelloReply();
  reply.setMessage('Hello ' + call.request.getName());
  return [null, reply]
}
```
Again, just ideas.

This feature would eliminate the need for wrapper code for users wanting to use this pattern. I would love to know if anyone is interested in this feature or planning on adding it. Thanks!

**Comment by murgatroid99** [comment]
Would you mind opening this against https://github.com/grpc/grpc-node? Going forward, that's where gRPC Node development will be, so it would be better to have this discussion there.

**Comment by Tim15** [comment]
Moved to https://github.com/grpc/grpc-node/issues/54
