### ISSUE TITLE
tools/run_tests/helper_scripts/run_grpc-node.sh  failing at high rate on both MacOS and Linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12781]
https://sponge.corp.google.com/target?id=2c167eee-4130-4fef-9969-f37fa53b6783&target=github/grpc/grpc-node_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```
../ext/call_credentials.cc:163:23: error: assigning to 'int (*)(void *, grpc_auth_metadata_context, grpc_credentials_plugin_metadata_cb, void *, grpc_metadata *, size_t *, grpc_status_code *, const char **)' (aka 'int (*)(void *, grpc_auth_metadata_context, void (*)(void *, const grpc_metadata *, unsigned long, grpc_status_code, const char *), void *, grpc_metadata *, unsigned long *, grpc_status_code *, const char **)') from incompatible type 'void (void *, grpc_auth_metadata_context, grpc_credentials_plugin_metadata_cb, void *)' (aka 'void (void *, grpc_auth_metadata_context, void (*)(void *, const grpc_metadata *, unsigned long, grpc_status_code, const char *), void *)'): different number of parameters (8 vs 4)
  plugin.get_metadata = plugin_get_metadata;
                      ^ ~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc_node/ext/call_credentials.o] Error 1
gyp ERR! build error 
```

**Comment by jtattermusch** [comment]
Looks like node changes from https://github.com/grpc/grpc/pull/12374/files#diff-c428f3d1acc730b9b52d6e81a4b42c77 need to be brought over from grpc/grpc.

**Comment by jtattermusch** [comment]
CC @nicolasnoble  this is currently breaking 100% of mac and linux builds.

**Comment by dgquintas** [comment]
It's happening again: https://screenshot.googleplex.com/3VCUayRzH5t

eg https://sponge.corp.google.com/target?id=ff1d2857-55b1-40c0-a4d3-8ad1df972643&target=grpc/macos/master/grpc_basictests_dbg&searchFor=&show=FAILED&sortBy=STATUS

**Comment by dgquintas** [comment]
Bumping up to P0 due to the 100% occurrence rate

**Comment by jtattermusch** [comment]
Not seeing this on a few last builds.
