### ISSUE TITLE
 "google.protobuf.Timestamp" is not defined, compiling from Grpc.Tools 1.6.1

### ISSUE THREAD

**Issue by FDUdannychen** [grpc/grpc#12814]
I'm using Visual Studio 2017 Professional, with the following dependencies:

```
<PackageReference Include="Google.Protobuf" Version="3.4.1" />
<PackageReference Include="Grpc" Version="1.6.1" />
<PackageReference Include="Grpc.Tools" Version="1.6.1" />
```
My proto file looks like:
```
syntax = "proto3";
package foo;
import "google/protobuf/timestamp.proto";

message Response {
	google.protobuf.Timestamp myField = 1;
}
```
And I add a pre-build script to compile proto files:

```
<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="$(NuGetPackageRoot)\Grpc.Tools\1.6.1\tools\windows_x64\protoc.exe --proto_path ..\protos --csharp_out Grpc --grpc_out Grpc ..\protos\test.proto --plugin=protoc-gen-grpc=$(NuGetPackageRoot)\Grpc.Tools\1.6.1\tools\windows_x64\grpc_csharp_plugin.exe" />
</Target>  
```
However VS tells me that the pre-build script exits with code 1, which means failure. When I compile it manually in the command line:
```
C:\Users\xxx\.nuget\packages\\Grpc.Tools\1.6.1\tools\windows_x64\protoc.exe --proto_path ..\protos --csharp_out Grpc --grpc_out Grpc ..\protos\test.proto --plugin=protoc-gen-grpc=C:\Users\xxx\.nuget\packages\\Grpc.Tools\1.6.1\tools\windows_x64\grpc_csharp_plugin.exe
test.proto:30:9: "google.protobuf.Timestamp" is not defined.
```
It seems that the compiler can't find the Timestamp definition. I didn't install [any compilers of protocol buffers](https://github.com/google/protobuf/releases), because I hope my project can be easily setup without any prerequisite, I think the tools in the nuget packages should be enough.

Is this a bug or I have to install the compiler to include the timestamp type? Is there any workaround? Personally I don't like using a "int64" field and convert it back and forth...

**Comment by FDUdannychen** [comment]
Comparing with [Google.Protobuf.Tools](https://www.nuget.org/packages/Google.Protobuf.Tools/), [Grpc.Tools](https://www.nuget.org/packages/Grpc.Tools/) lacks the well known types' folder, where "any.proto" "timestamp.proto" and etc are defined. 

Currently I copy the well known types folder manually into my protocol folder, everything looks fine. But IMO it should be part of the nuget package.

**Comment by r3h0** [comment]
@FDUdannychen I was able to get around this by adding both Google.Protobuf.Tools and Grpc.Tools with NuGet, then including `$(NuGetPackageRoot)\Google.Protobuf.Tools.3.4.0\tools` in the protoc.exe build step.

It's still a bit of a hack, but at least it doesn't require manually copying any files over.

**Comment by rocketraman** [comment]
@r3h0 Thank you for the workaround!

**Comment by RahmanM** [comment]
This is still an issue. I got this error when importing: 
Import "google/protobuf/timestamp.proto" was not found or had errors.

syntax = "proto3";
import "google/protobuf/timestamp.proto";

**Comment by r3h0** [comment]
If more people are having issues with this, here's the full command I put into my MSBuild configuration as a pre-build step:

`$(NuGetPackageRoot)/grpc.tools/1.9.0/tools/linux_x64/protoc            -I'$(NuGetPackageRoot)/google.protobuf.tools/3.5.1/tools/google/protobuf'           --proto_path='$(NuGetPackageRoot)/google.protobuf.tools/3.5.1/tools'           --proto_path='$(ProjectDir)/Grpc'           --csharp_out='$(ProjectDir)/Grpc'           --grpc_out='$(ProjectDir)/Grpc'           --plugin=protoc-gen-grpc=$(NuGetPackageRoot)/grpc.tools/1.9.0/tools/linux_x64/grpc_csharp_plugin           helloworld.proto`

You'll have to change `linux_x64` to another platform if needed. I'm not sure how to make that automatic.
