### ISSUE TITLE
cmake/build/Debug/init_test.exe  is timing out 100% of time

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12819]
```
Timeout

D1004 00:52:12.943000000   868 dns_resolver.c:301] Using native dns resolver
D1004 00:52:12.958000000   868 dns_resolver.c:301] Using native dns resolver
D1004 00:52:12.958000000   868 dns_resolver.c:301] Using native dns resolver
D1004 00:52:12.958000000   868 dns_resolver.c:301] Using native dns resolver
D1004 00:52:12.958000000   868 dns_resolver.c:301] Using native dns resolver
...
```

https://sponge.corp.google.com/target?id=b28ac375-e00e-4510-bf16-c3b3a8b71969&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
I suspect the root cause is this PR: https://github.com/grpc/grpc/pull/12663  (the problem seems to be  only happening on Debug builds).

**Comment by jtattermusch** [comment]
Also, the PR #12663  says "all test failures are known which doesn't seem to be the case". I do see windows "init_test" failing on tests for that PR.

**Comment by jtattermusch** [comment]
100% failure rate & 5 days no update -> raising to P0.

**Comment by jtattermusch** [comment]
Btw, reverting the original pull request seems to fix the test, but there is a conflict in the auto-revert.
https://github.com/grpc/grpc/pull/12862/conflicts.  We either need to take action to fix this or revert ASAP.

**Comment by sreecha** [comment]
Sorry for not updating the status so far

I have spent a lot of time trying to reproduce this the past two working days...From getting a windows machine to trying to get grpc up and running on windows by following instructions at https://github.com/grpc/grpc/blob/master/INSTALL.md

So far, I have been unsuccessful. I will continue working on this.
I created an issue to fix the documentation: https://github.com/grpc/grpc/issues/12906

**Comment by sreecha** [comment]
I was able to finally get grpc setup on windows (with help from @nicolasnoble, @jtattermusch and @matt-kwong) . The `init_test.exe` runs fine in debug mode! (I even added a few log lines in the offending  #12663  to make sure that was enabled).

So going by @ctiller's recommendation, I am increasing the timeout for the test and created an experimental PR (for now) https://github.com/grpc/grpc/pull/12920

**Comment by sreecha** [comment]
https://github.com/grpc/grpc/pull/12920 did fix it but @nicolasnoble and @ctiller had a better fix (see https://github.com/grpc/grpc/pull/12929 which is merged now). 

This issue can be closed.

**Comment by jtattermusch** [comment]
I haven't seen the failure on last few builds on master, closing. Thanks for looking into this!
