### ISSUE TITLE
Allow node library to load file formats besides proto

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1281]
It would be useful to be able to load the JSON files that `pbjs` generates, along with the binary files that `protoc` can generate.

**Comment by murgatroid99** [comment]
This would be made much easier if ProtoBuf.js got features requested in dcodeIO/ProtoBuf.js#250.

**Comment by ctiller** [comment]
Still relevant?

**Comment by murgatroid99** [comment]
No, I don't think so. Loading the JSON format is supported, and I have never seen any demand for loading binary proto definition files.
