### ISSUE TITLE
Changing server configuration options on a running server

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#12823]
Please answer these questions before submitting your issue. 

### What version of gRPC and what language are you using?
1.4.2 - C++ 
 
### What operating system (Linux, Windows, …) and version?
CentOS 6, Windows 10 
 
For operational reasons, many times, we would want to change the configuration options on a server without taking it down. This can not be done currently on a running server.

Discussion thread here - https://groups.google.com/forum/#!topic/grpc-io/VkHRBWx44HE 

Thanks.

**Comment by markdroth** [comment]
We don't currently have any plans to support this.

Can you tell me more about why you need to do this?  It might help us to understand why this is important.

**Comment by abaldeva** [comment]
Hi,

In our current framework, we use reconfiguration for a number of reasons. For example, if your ssl cert is going to expire soon, you can reconfigure the cert without taking down the instance.

It also useful sometimes to adjust the maximum number of connections that a server is permitted to have (grpc currently does not allow limiting the max connections and it's a feature request that is pending - https://github.com/grpc/grpc/issues/12472).

I was looking at the grpc_types.h and some options like enabling census reporting etc. might be useful to toggle. 

Thanks,

**Comment by markdroth** [comment]
Ability to reload SSL certificates was added recently in #12644.

For things that are set via channel args, why do you need to toggle this without a restart?  Does your environment not have a way to restart individual servers without disrupting the service for clients?

**Comment by abaldeva** [comment]
Thanks for the info on the SSL cert reload. That was the big factor. 

Our environment does support restarting individual servers in a non-impacting fashion and there are ways to handle other stuff. The configuration reload stuff predates these newer capabilities by a considerable duration so that stuff is still around.

Anyhow, I don't have a good use case now for reconfiguration support so I'll go ahead and close the issue.

Thanks for your time.
