### ISSUE TITLE
Stop requiring valid response return value when status is not OK?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#12826]
(The possibility of this work depends on the answer to [issue 12824](https://github.com/grpc/grpc/issues/12824).

gRPC Python currently requires that the return value of service-side response-unary RPC method handlers be a legitimate response object (when gRPC is used with Protocol Buffers: this means a valid message instance of the appropriate class rather than `None`). Could applications that have set the RPC's status code to a value other than `grpc.StatusCode.OK` be allowed to return `None`?

**Comment by mehrdada** [comment]
@nathanielmanistaatgoogle Can you please make the call on which path we should go forward *in Python* considering the answer to #12824?  I think the path to least disruption is explicitly allowing `None` for non-OK status codes in documentation and making sure it works as expected, so I am leaning towards that a bit, but I leave it to you.

**Comment by nathanielmanistaatgoogle** [comment]
I'm hesitant to rush to make a call, actually. So far there's at least a little bit of risk of permanent harm with each of the options considered, and the cost of doing nothing isn't too high. The `return my_message_module_pb2.MyMessage()` in

```python
my_servicer_context.set_code(my_desired_code)
return my_message_module_pb2.MyMessage()
```

is cosmetically unattractive, but that's it. Is there some reason to rush ahead on this?

**Comment by mehrdada** [comment]
There was at least one case where the user wants to return a result from an interceptor, not the handler, and there was no generic way to figure out what the type of the correct type to return from the handler was in the interceptor to construct an empty object out of. That is the prime motivator for moving this forward.

**Comment by nathanielmanistaatgoogle** [comment]
D'oh! Thanks for the reminder.

**Comment by amitsaha** [comment]
Yes +1 @mehrdada i think interceptors would definitely need this functionality to be available.

**Comment by mehrdada** [comment]
We debated this issue at length on a number of different occasions over the past few months and explored various designs and considered feedback in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/grpc-io/0hmnCpCKIUk/H7EFeONDCgAJ and settled on the following design:

> Add a `ServicerContext.abort(code, details)` method that the user can call when they want to terminate an RPC with a non-OK status.  This method raises an exception, thereby terminating the execution of the handler immediately without it needing to return anything. The gRPC runtime recognizes this exception value and responds to the client with the specified status code and details.

**Comment by mitar** [comment]
Does this allow also custom status codes?

**Comment by mehrdada** [comment]
This is a Python specific API design decision and allowing custom status codes (via this or set_code) is an orthogonal and cross-language design decision that we did not open up here, but the short answer is no, as discussed on https://github.com/grpc/grpc/issues/13321.

**Comment by mitar** [comment]
Thanks. Still great improvement here.

**Comment by mehrdada** [comment]
Fixed by https://github.com/grpc/grpc/pull/13667
