### ISSUE TITLE
xray will conflict with unicorn stop/restart

### ISSUE THREAD

**Issue by tony612** [grpc/grpc#1283]
We use `QUIT` signal to restart the unicorn, but xray just trap the `QUIT` signal, so we can't restart unicorn normally. It seems we're not able to specify the signal for xray, see https://github.com/ph7/xray/blob/master/lib/xray/thread_dump_signal_handler.rb#L6 .

Is there a good solution to this?

**Comment by tbetbetbe** [comment]
if we remove xray, will resolve this for you?  It has been a useful debugging feature, but I don't think it needs to be there permanently

**Comment by tony612** [comment]
@tbetbetbe Yeah, it helps. btw, I think the `minitest` gem should be moved into development_dependency :D

**Comment by tony612** [comment]
@tbetbetbe It's a useful debugging tool indeed if only it supports custom signal :) But you know, it has not been maintained for some years
