### ISSUE TITLE
CI VM's don't support EPOLLEXCLUSIVE

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#12840]
https://sponge.corp.google.com/target?id=2c4477e6-cbe3-4ce3-b223-16317391ae52&target=github/grpc/c_linux_asan_native&searchFor=&show=ALL&sortBy=STATUS

We need to be running kernel 4.5+ - I know we did some work here, so I expect some misconfiguration somewhere.

If it's useful, the following incantation can verify:
```
make check_epollexclusive -j
bins/opt/check_epollexclusive
```

If the kernel has EPOLLEXCLUSIVE, this program will silently succeed. If not, it will fail with:
```
E1005 08:26:46.442884281    1835 is_epollexclusive_available.c:82] epoll_ctl with EPOLLEXCLUSIVE | EPOLLONESHOT succeeded. This is evidence of no EPOLLEXCLUSIVE support. Not using epollex polling engine.
```

Setting to P0 since we urgently need to land EPOLLEXCLUSIVE to make progress on our performance targets.

**Comment by jtattermusch** [comment]
I think the current situation is we support epollex on our performance workers that are using a custom VM image. @matt-kwong knows more.

**Comment by matt-kwong** [comment]
Switching to using an Ubuntu 17.04 image with kernel 4.10. The following works:
```
make check_epollexclusive -j
bins/opt/check_epollexclusive
```
I'm setting up some stuff, and will test it before enabling it for pull requests. This should be done today, if not within a few hours. 

Is there a PR I can trigger tests for to make sure epollexclusive works on Kokoro?

**Comment by ctiller** [comment]
https://github.com/grpc/grpc/pull/12789

**Comment by matt-kwong** [comment]
The sanitizers and C/C++ Linux tests should all run on an Ubuntu 17.04 image with kernel 4.10 now. 

#12789 is failing because of an unrelated compilation issue.

**Comment by jtattermusch** [comment]
Thanks Matt!
