### ISSUE TITLE
failed: run_tests_c_linux_tsan_native

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#12859]
From #12760 
https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_c_tsan/3929/
#12789 
https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_c_tsan/3938/
```
+ docker rm -f run_tests_098d5ec0-13bb-4e95-943b-6a7455afd1b1
run_tests_098d5ec0-13bb-4e95-943b-6a7455afd1b1
+ exit 2
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1448, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 2

2017-10-05 15:45:46,502 FAILED: run_tests_c_linux_tsan_native [ret=1, pid=8746]
```

**Comment by adelez** [comment]
Please post sponge link instead of Kokoro link as you can see the Kokoro link expires very quickly. Also assign an owner. :)

**Comment by adelez** [comment]
Closing this bug because the links expired and the error is not useful for debugging.
