### ISSUE TITLE
Backoff timing in C does not follow specification

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#12867]
Backoff timing in C is supposed to start with an initial backoff of 1 second and increase by a factor of 1.6 for each failed attempt, according to [this specification](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md).

Current behavior in C based libraries are different from the spec, starting with a 20s initial backoff and keep increasing. Potentially the problem could be a [misuse](https://github.com/grpc/grpc/blob/3640b4084ac8485ef99ab3162cae7b8b079bbf6b/src/core/ext/filters/client_channel/subchannel.cc#L51) of MIN_CONNECT_TIMEOUT as a backoff related parameter (likely INITIAL_BACKOFF).

**Comment by dgquintas** [comment]
@muxi now that #13121 has been merged, can you please verify that it fixes this issue? Reopening until then.

**Comment by muxi** [comment]
Verified the behavior is correct. Thanks for the fix!

**Comment by muxi** [comment]
Note that #12392 from the same thread still exists
