### ISSUE TITLE
Linking fails on OS X  10.9.5

### ISSUE THREAD

**Issue by ronaflx** [grpc/grpc#1287]
The error message is following:

[AR]      Creating libs/opt/libgrpc++.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++.a(internal_stub.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++.a(rpc_method.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++.a(internal_stub.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++.a(rpc_method.o) has no symbols
[AR]      Creating libs/opt/libgrpc++_unsecure.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++_unsecure.a(internal_stub.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++_unsecure.a(rpc_method.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++_unsecure.a(internal_stub.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./libs/opt/libgrpc++_unsecure.a(rpc_method.o) has no symbols
[LD]      Linking libs/opt/libgpr.dylib
[LD]      Linking libs/opt/libgrpc.dylib
Undefined symbols for architecture x86_64:
  "_gpr_slice_buffer_swap", referenced from:
      _unlock in chttp2_transport.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/opt/libgrpc.dylib] Error 1

**Comment by cklawrence** [comment]
I have the same problem. First thought linker was picking up old, installed libs because of the order of linker search paths. But I removed old build and it still didn't work.

Even so, placing ./libs/opt first in linker path does work:

LDFLAGS=-L./libs/opt make

This causes linker to use libgpr.dylib instead of libgrp.a, for some reason.

**Comment by cklawrence** [comment]
I forgot to remove /usr/local/lib/libgpr.a. So gprc will build ok if one completely removes the old, installed build.

Perhaps ./libs/opt should be placed first in the list of linker paths so this won't happen.

**Comment by soltanmm** [comment]
I don't have this issue. What version of XCode are y'all using?

**Comment by ronaflx** [comment]
The approach @cklawrence provide works for me.
I use make tools installed via homebrew to compile. The compiler version is following:
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by cklawrence** [comment]
Xcode 6.3.1

I ran into the problem by trying to compile the latest grpc when I had an
older version installed.
The SHA of the older version is 7a6ecc2.



On Mon, Apr 27, 2015 at 6:17 PM, Masood Malekghassemi <
notifications@github.com> wrote:

> I don't have this issue. What version of XCode are y'all using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/issues/1287#issuecomment-96869605>.
>



-- 

*Charlie Lawrence*
Software Engineer, Engineering

| *phone:* 408.884.2162 | *email:* charlie@retailnext.net
RetailNext, Inc. | 60 S. Market Street, Floor 10 San Jose, CA 95113

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
This e-mail and any attachments may contain confidential information that
is legally privileged. The information is solely for the use of the
intended recipient(s); any disclosure, copying, distribution or other use
of this information is strictly prohibited. If you have received this
e-mail in error, please notify the sender by return e-mail and delete this
message. For more information visit: http://retailnext.net.

**Comment by jcanizales** [comment]
Hi Charlie and Lixin,
sorry that this fell through the cracks. Are you still having problems? I understand you're trying to build the C++ gRPC library on a Mac, correct?

**Comment by ronaflx** [comment]
Hi, Jorge,
it works well for me now while building C++ grpc library on a Mac.
