### ISSUE TITLE
grpc_portability_build_only test fails to build /var/local/git/grpc/objs/dbg/test/core/transport/timeout_encoding_test.o

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12871]
https://sponge.corp.google.com/target?id=35cea8c0-a916-4c3a-b0e4-53bcdc1ce84f&target=grpc%2Fubuntu%2Fpull_request%2Fgrpc_portability_build_only&searchFor=

[C]       Compiling test/core/transport/timeout_encoding_test.c
mkdir -p `dirname /var/local/git/grpc/objs/dbg/test/core/transport/timeout_encoding_test.o`
cc -Ithird_party/protobuf/src -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/cares -Ithird_party/cares/cares -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -O0 -fPIC -I. -Iinclude -I/var/local/git/grpc/gens -D_DEBUG -DDEBUG -DINSTALL_PREFIX=\"/usr/local\" -DGRPC_TEST_SLOWDOWN_MACHINE_FACTOR=1.000000   -Ithird_party/zlib -std=c99 -Wsign-conversion -Wconversion -Wshadow    -MMD -MF /var/local/git/grpc/objs/dbg/test/core/transport/timeout_encoding_test.dep -c -o /var/local/git/grpc/objs/dbg/test/core/transport/timeout_encoding_test.o test/core/transport/timeout_encoding_test.c
test/core/transport/timeout_encoding_test.c: In function 'millis_from_nanos':
test/core/transport/timeout_encoding_test.c:105:3: error: conversion to 'grpc_millis' from 'int64_t' may alter its value [-Werror=conversion]
   return x / GPR_NS_PER_MS + (x % GPR_NS_PER_MS != 0);
   ^
test/core/transport/timeout_encoding_test.c: In function 'millis_from_micros':
test/core/transport/timeout_encoding_test.c:108:3: error: conversion to 'grpc_millis' from 'int64_t' may alter its value [-Werror=conversion]
   return x / GPR_US_PER_MS + (x % GPR_US_PER_MS != 0);
   ^
test/core/transport/timeout_encoding_test.c: In function 'millis_from_millis':
test/core/transport/timeout_encoding_test.c:110:52: error: conversion to 'grpc_millis' from 'int64_t' may alter its value [-Werror=conversion]
 static grpc_millis millis_from_millis(int64_t x) { return x; }
                                                    ^
test/core/transport/timeout_encoding_test.c: In function 'millis_from_seconds':
test/core/transport/timeout_encoding_test.c:111:53: error: conversion to 'grpc_millis' from 'int64_t' may alter its value [-Werror=conversion]
 static grpc_millis millis_from_seconds(int64_t x) { return x * GPR_MS_PER_SEC; }
                                                     ^
test/core/transport/timeout_encoding_test.c: In function 'millis_from_minutes':
test/core/transport/timeout_encoding_test.c:113:3: error: conversion to 'grpc_millis' from 'int64_t' may alter its value [-Werror=conversion]
   return x * 60 * GPR_MS_PER_SEC;
   ^
test/core/transport/timeout_encoding_test.c: In function 'millis_from_hours':
test/core/transport/timeout_encoding_test.c:116:3: error: conversion to 'grpc_millis' from 'int64_t' may alter its value [-Werror=conversion]
   return x * 3600 * GPR_MS_PER_SEC;
   ^
cc1: all warnings being treated as errors
Makefile:2564: recipe for target '/var/local/git/grpc/objs/dbg/test/core/transport/timeout_encoding_test.o' failed
make: *** [/var/local/git/grpc/objs/dbg/test/core/transport/timeout_encoding_test.o] Error 1
make: *** Waiting for unfinished jobs....

2017-10-06 19:10:04,977 FAILED: make [ret=2, pid=1111, time=85.8sec]
2017-10-06 19:10:04,977 FAILED: Some tests failed
  adding: reports/ (stored 0%)
  adding: reports/index.html (deflated 22%)
+ DOCKER_EXIT_CODE=1
++ mktemp
+ TEMP_REPORTS_ZIP=/tmpfs/tmp/tmp.eANAsCbCJV
+ docker cp run_tests_a4dfcb46-ab6b-47c1-a727-52279e90faa4:/var/local/git/grpc/reports.zip /tmpfs/tmp/tmp.eANAsCbCJV
+ unzip -o /tmpfs/tmp/tmp.eANAsCbCJV -d /tmpfs/src/github/grpc
Archive:  /tmpfs/tmp/tmp.eANAsCbCJV
  inflating: /tmpfs/src/github/grpc/reports/index.html  
+ rm -f /tmpfs/tmp/tmp.eANAsCbCJV
+ docker rm -f run_tests_a4dfcb46-ab6b-47c1-a727-52279e90faa4
run_tests_a4dfcb46-ab6b-47c1-a727-52279e90faa4
+ exit 1
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1448, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 1

2017-10-06 12:10:06,996 FAILED: run_tests_c_linux_dbg_native_x86_default_buildonly [ret=1, pid=9942, time=266.0sec]

**Comment by adelez** [comment]
Nico, can you please take an initial look?

**Comment by jtattermusch** [comment]
grpc_portability_build_only has been building fine recently.
