### ISSUE TITLE
Confusing/incorrect behavior of SO_REUSEADDR on OS X (Python)

### ISSUE THREAD

**Issue by amitsaha** [grpc/grpc#12890]
### What version of gRPC and what language are you using?

Python, 1.6.3 
 
### What operating system (Linux, Windows, …) and version?
 
 OS X 10.12.6

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3

```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

``` 
 
### What did you do?

Consider the server below:

```

def serve():
  server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
  users_service.add_UsersServicer_to_server(UsersService(), server)
  res = server.add_insecure_port('127.0.0.1:50051')
  server.start()
  try:
    while True:
      time.sleep(_ONE_DAY_IN_SECONDS)
  except KeyboardInterrupt:
    server.stop(0)
```

 
### What did you expect to see?
 
I expected to not be able to start a second instance of the server. On Linux, I get this:

```
E0907 12:28:57.205046525   16071 server_chttp2.c:53]         {"created":"@1504751337.205028841","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":260,"referenced_errors":[{"created":"@1504751337.205026361","description":"Unable to configure socket","fd":3,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.c","file_line":215,"referenced_errors":[{"created":"@1504751337.205023798","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.c","file_line":188,"os_error":"Address already in use","syscall":"bind"}]}]}
```
 
### What did you see instead?

I can start multiple instances of the server above, but only on OS X:

```
$ sudo lsof -iTCP:50051

COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python  12120 amit    4u  IPv6 0xffbffb1742aa0f0f      0t0  TCP localhost:50051 (LISTEN)
Python  12157 amit    4u  IPv6 0xffbffb1742aa144f      0t0  TCP localhost:50051 (LISTEN)
```

 
### Anything else we should know about your project / environment?

I asked this as a question on [google groups](https://groups.google.com/forum/#!topic/grpc-io/RB69llv2tC4)

**Comment by kpayson64** [comment]
Apologies, I didn't realize there were still lingering questions about this behavior.

I don't think we intend to remove the SO_REUSEADDR flag on servers, and I've attempted to explain the platform discrepancy on the google groups thread.

**Comment by sonvirgo** [comment]
experience same issue MiniDLNA and GmediaRender-Resurect on High Sierra
But I can run multiple instance of gmediarender at same time.
