### ISSUE TITLE
Leak: bins/asan/h2_census_nosec_test resource_quota_server GRPC_POLL_STRATEGY=poll 

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12912]
https://sponge.corp.google.com/target?id=81620dca-bc3c-4559-97a6-07dd85273a69&target=github/grpc/c_linux_asan_native&searchFor=&show=ALL&sortBy=STATUS

Failure
*, void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc:444:11
    #13 0x709c13 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.cc:260:5
    #14 0x61c6b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:93:17
    #15 0x75619b in run_closures(grpc_exec_ctx*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:81:5
    #16 0x755a60 in executor_thread(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:182:22
    #17 0x838394 in thread_body(void*) /var/local/git/grpc/src/core/lib/support/thd_posix.cc:42:3
    #18 0x7f1890f9a063 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8063)

Objects leaked above:
0x60200000dc50 (16 bytes)

[1m[34mIndirect leak of 16 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x824e87 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.cc:56:7
    #2 0x830aa8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.cc:42:17
    #3 0x685ded in grpc_channel_create_with_builder /var/local/git/grpc/src/core/lib/surface/channel.cc:78:18
    #4 0x6890df in grpc_channel_create /var/local/git/grpc/src/core/lib/surface/channel.cc:211:10
    #5 0x821b55 in client_channel_factory_create_channel(grpc_exec_ctx*, grpc_client_channel_factory*, char const*, grpc_client_channel_type, grpc_channel_args const*) /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.cc:64:27
    #6 0x821784 in grpc_insecure_channel_create /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.cc:95:27
    #7 0x4f68f4 in chttp2_init_client_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_census.c:72:15
    #8 0x599c65 in begin_test /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:41:3
    #9 0x5965a4 in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:127:7
    #10 0x4fa97a in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:452:7
    #11 0x4f78c3 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_census.c:123:5
    #12 0x7f18906e7b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60200000ce50 (16 bytes)

[1m[34mIndirect leak of 15 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x824e87 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.cc:56:7
    #2 0x830aa8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.cc:42:17
    #3 0x764afb in grpc_connectivity_state_init /var/local/git/grpc/src/core/lib/transport/connectivity_state.cc:54:19
    #4 0x6d4b6e in cc_init_channel_elem(grpc_exec_ctx*, grpc_channel_element*, grpc_channel_element_args*) /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc:713:3
    #5 0x5eb9a6 in grpc_channel_stack_init /var/local/git/grpc/src/core/lib/channel/channel_stack.cc:122:9
    #6 0x5ef5f1 in grpc_channel_stack_builder_finish /var/local/git/grpc/src/core/lib/channel/channel_stack_builder.cc:286:23
    #7 0x6860c8 in grpc_channel_create_with_builder /var/local/git/grpc/src/core/lib/surface/channel.cc:87:23
    #8 0x6890df in grpc_channel_create /var/local/git/grpc/src/core/lib/surface/channel.cc:211:10
    #9 0x821b55 in client_channel_factory_create_channel(grpc_exec_ctx*, grpc_client_channel_factory*, char const*, grpc_client_channel_type, grpc_channel_args const*) /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.cc:64:27
    #10 0x821784 in grpc_insecure_channel_create /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.cc:95:27
    #11 0x4f68f4 in chttp2_init_client_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_census.c:72:15
    #12 0x599c65 in begin_test /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:41:3
    #13 0x5965a4 in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:127:7
    #14 0x4fa97a in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:452:7
    #15 0x4f78c3 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_census.c:123:5
    #16 0x7f18906e7b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60200000cd90 (15 bytes)

[1m[34mIndirect leak of 11 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x824e87 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.cc:56:7
    #2 0x830aa8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.cc:42:17
    #3 0x764afb in grpc_connectivity_state_init /var/local/git/grpc/src/core/lib/transport/connectivity_state.cc:54:19
    #4 0x6ee090 in grpc_subchannel_create /var/local/git/grpc/src/core/ext/filters/client_channel/subchannel.cc:334:3
    #5 0x821d06 in client_channel_factory_create_subchannel(grpc_exec_ctx*, grpc_client_channel_factory*, grpc_subchannel_args const*) /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.cc:43:24
    #6 0x6e5782 in grpc_client_channel_factory_create_subchannel /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel_factory.cc:34:10
    #7 0x91c063 in pf_update_locked(grpc_exec_ctx*, grpc_lb_policy*, grpc_lb_policy_args const*) /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:410:35
    #8 0x91a6a3 in create_pick_first(grpc_exec_ctx*, grpc_lb_policy_factory*, grpc_lb_policy_args*) /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:688:3
    #9 0x76cc42 in grpc_lb_policy_factory_create_lb_policy /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy_factory.cc:168:10
    #10 0x6e71fa in grpc_lb_policy_create /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:68:7
    #11 0x6df96f in on_resolver_result_changed_locked(grpc_exec_ctx*, void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc:444:11
    #12 0x709c13 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.cc:260:5
    #13 0x61c6b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:93:17
    #14 0x75619b in run_closures(grpc_exec_ctx*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:81:5
    #15 0x755a60 in executor_thread(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:182:22
    #16 0x838394 in thread_body(void*) /var/local/git/grpc/src/core/lib/support/thd_posix.cc:42:3
    #17 0x7f1890f9a063 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8063)

Objects leaked above:
0x60200000da30 (11 bytes)

[1m[34mIndirect leak of 11 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x824e87 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.cc:56:7
    #2 0x830aa8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.cc:42:17
    #3 0x6e0329 in on_resolver_result_changed_locked(grpc_exec_ctx*, void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc:482:26
    #4 0x709c13 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.cc:260:5
    #5 0x61c6b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:93:17
    #6 0x75619b in run_closures(grpc_exec_ctx*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:81:5
    #7 0x755a60 in executor_thread(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:182:22
    #8 0x838394 in thread_body(void*) /var/local/git/grpc/src/core/lib/support/thd_posix.cc:42:3
    #9 0x7f1890f9a063 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8063)

Objects leaked above:
0x60200000d650 (11 bytes)

SUMMARY: AddressSanitizer: 1201438 byte(s) leaked in 183 allocation(s).

**Comment by markdroth** [comment]
This is a duplicate of #11055.
