### ISSUE TITLE
Flake: C++ bins/opt/end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/2

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#12917]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?

Master, C++ 
 
### What operating system (Linux, Windows, …) and version?
 
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Kokoro tests with dbg

### What did you do?

https://sponge.corp.google.com/target?id=6d818e17-384e-409e-aac3-11ce74972ef6&target=github/grpc/c%2B%2B_linux_opt_native&searchFor=&show=ALL&sortBy=STATUS

### What did you expect to see?
 
Tests pass for unrelated PR #12914 
 
### What did you see instead?
 
Possibly a reincarnation of #9086

```
Note: Google Test filter = ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/2
D1009 19:45:19.327866841    5639 end2end_test.cc:215]        TestScenario{use_proxy=false, inproc=false, credentials='INSECURE_CREDENTIALS'}
I1009 19:45:19.327926729    5639 ev_epoll1_linux.cc:93]      grpc epoll fd: 3
D1009 19:45:19.327939789    5639 ev_posix.cc:107]            Using polling engine: epoll1
D1009 19:45:19.327947914    5639 dns_resolver.cc:306]        Using native dns resolver
I1009 19:45:19.329288483    5639 ev_epoll1_linux.cc:93]      grpc epoll fd: 3
D1009 19:45:19.329307190    5639 ev_posix.cc:107]            Using polling engine: epoll1
D1009 19:45:19.329319043    5639 dns_resolver.cc:306]        Using native dns resolver
I1009 19:45:19.329356113    5639 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
test/cpp/end2end/end2end_test.cc:1289: Failure
      Expected: StatusCode::DEADLINE_EXCEEDED
      Which is: 4
To be equal to: s.error_code()
      Which is: 0
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/2, where GetParam() = TestScenario{use_proxy=false, inproc=false, credentials='INSECURE_CREDENTIALS'} (13 ms)
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest (13 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (13 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/2, where GetParam() = TestScenario{use_proxy=false, inproc=false, credentials='INSECURE_CREDENTIALS'}

 1 FAILED TEST
```

**Comment by markdroth** [comment]
Just saw this again in #12767:

https://sponge.corp.google.com/target?id=5107ce5b-26cc-4ef8-b027-39dacba32bf1&target=github/grpc/c%2B%2B_linux_dbg_native&searchFor=&show=ALL&sortBy=STATUS

**Comment by vjpai** [comment]
ASAN version of this seen at https://sponge.corp.google.com/target?id=df98106c-9c52-420f-91c5465c3aaaf531&target=github/grpc/c%2B%2B_linux_asan_native&searchFor=&show=ALL&sortBy=STATUS (PR #13082)

**Comment by dgquintas** [comment]
Duplicate of #11008

**Comment by markdroth** [comment]
I don't think this is actually a duplicate.  The failures are different -- #11008 is a segfault, but this is a test failure.

**Comment by jtattermusch** [comment]
Still seeing this on master in significant number of runs:
https://sponge.corp.google.com/target?id=81bf7287-bdfa-470f-8b0a-7314b1d84ed5&target=github/grpc/c%2B%2B_linux_opt_native&searchFor=&show=FAILED&sortBy=STATUS

```
test/cpp/end2end/end2end_test.cc:1319: Failure
      Expected: StatusCode::DEADLINE_EXCEEDED
      Which is: 4
To be equal to: s.error_code()
      Which is: 0
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/4, where GetParam() = TestScenario{use_proxy=false, inproc=true, credentials='INSECURE_CREDENTIALS'} (2009 ms)
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest (2009 ms total)
```

**Comment by sreecha** [comment]
https://github.com/grpc/grpc/pull/13678 should address this issue.

**Comment by sreecha** [comment]
This is resolved by 13678

**Comment by AspirinSJL** [comment]
Seen again when trying to reproduce #14362 locally using `tools/run_tests/run_tests.py -lc++ -casan -r ".*RpcDeadlineExpires/2" --force_use_pollers epollex -n inf -S`.

**Comment by jtattermusch** [comment]
I am not seeing this on master anymore (with "opt" configuration). I am seeing  failures under asan instead. 
Closing this issue and marking #14362 as P1 instead.
