### ISSUE TITLE
Sanity tests timed out

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12916]
https://sponge.corp.google.com/target?id=c5489b20-8ebf-4a8a-8e88-d625850751c9&target=grpc%2Fubuntu%2Fpull_request%2Fgrpc_sanity&searchFor=

+ tools/run_tests/run_tests_matrix.py -f basictests linux sanity opt --inner_jobs 16 -j 1 --internal_ci --filter_pr_tests --base_branch origin/master
2017-10-06 18:02:26,304 START: Running test matrix.
IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment or into subworkspaces.
Looking for irrelevant tests to skip...
Finding file differences between gRPC origin/master branch and pull request...

  tools/interop_matrix/README.md
  tools/interop_matrix/create_testcases.sh
  tools/interop_matrix/run_interop_matrix_tests.py
  tools/interop_matrix/testcases/cxx__master
  tools/interop_matrix/testcases/go__master
  tools/interop_matrix/testcases/java__master

No tests will be skipped.
Will run these tests:
  run_tests_sanity_linux_opt_native
2017-10-06 18:02:26,304 START: run_tests_sanity_linux_opt_native

ERROR: Aborting VM command due to timeout of 1200 seconds

**Comment by jtattermusch** [comment]
Based on looking at historical data, I suspect this is a one-off occurence. I'll keep an eye on this though.
