### ISSUE TITLE
Windows tests timing out

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#12918]
See #12872 for more context

Since #12677 was merged most Windows tests time out

https://sponge.corp.google.com/invocation?show=FAILED&show=&id=b9a7879d-b02e-419e-a3fb-2f40d7669b0c&searchFor=&sortBy=STATUS&tab=Targets

C: 341/366 tests time out, each at 5 minutes
Ex: `cmake/build/Release/h2_full_test.exe cancel_after_round_trip` 
```
Timeout 
D1009 12:02:42.200000000   252 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1 
D1009 12:02:42.200000000   252 dns_resolver.cc:306] Using native dns resolver 
I1009 12:02:42.200000000   252 cancel_after_round_trip.c:47] Running test: cancel_after_round_trip/chttp2/fullstack/cancel/client_api 
I1009 12:02:43.215000000   252 cancel_after_round_trip.c:47] Running test: cancel_after_round_trip/chttp2/fullstack/deadline/client_api 
I1009 12:02:49.262000000   252 cancel_after_round_trip.c:47] Running test: cancel_after_round_trip/chttp2/fullstack/deadline/service_config
```
C#: About half of the tests are timing out

Python: All tests, except 1, time out

**Comment by jtattermusch** [comment]
Seems fixes. I will file an issue for remaining failing windows tests.
