### ISSUE TITLE
FLAKE: bins/dbg/h2_http_proxy_nosec_test resource_quota_server GRPC_POLL_STRATEGY=epoll1 client stream stalled

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12913]
https://sponge.corp.google.com/target?id=28754ab3-09fe-46ea-aa57-55c172f2a75c&target=github/grpc/c_linux_dbg_native&searchFor=&show=ALL&sortBy=STATUS

Failure
writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 135 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398809157   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 137 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398813127   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 139 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398816984   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 141 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398820301   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 143 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398823587   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 145 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398826977   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 147 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398831066   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 149 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398834621   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 151 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398838181   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 153 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398841806   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 155 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398845312   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 157 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398848621   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 159 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398852037   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 161 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398858342   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 163 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398861953   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 165 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398865329   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 167 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398868638   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 169 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398871987   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 171 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398875343   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 173 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398878652   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 175 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398881944   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 177 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398885390   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 179 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398888947   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 181 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398892327   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 183 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398895755   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 185 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398899203   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 187 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398903169   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 189 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398906541   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 191 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398909884   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 193 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398913341   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 195 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398916995   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 197 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398920293   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 199 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=3137090:s_delta=5]
D1007 01:28:11.398924242   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 7 stalled by transport [fc:pending=0:flowed=0:peer_initwin=4194304:t_win=0:s_win=4055265:s_delta=918180]
D1007 01:28:11.398931077   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 19 stalled by transport [fc:pending=0:flowed=0:peer_initwin=4194304:t_win=0:s_win=2860321:s_delta=-276764]
D1007 01:28:11.398934543   31262 writing.cc:142]             ipv6:[::1]:2627:0x7f442c00b850 stream 31 stalled by transport [fc:pending=0:flowed=0:peer_initwin=4194304:t_win=0:s_win=2364852:s_delta=-772233]
E1007 01:28:11.405875846   31262 chttp2_transport.cc:730]    client stream 139 still included in list 0

**Comment by markdroth** [comment]
I assume this is another epoll1 problem.  Assigning to Sree.

**Comment by sreecha** [comment]
Hmm..not sure if this is epoll1 related. I won't have time to look into this bug this week.  @ncteisen / @vjpai , do you have cycles to look in to this ?

**Comment by ncteisen** [comment]
`client stream n still included in list 0` is an error we have been seeing a lot. I would be hopeful that Craig's refactor of the writepath would resolve this. #12856

**Comment by apolcyn** [comment]
slightly different error log seen in 

(with `E1017 17:59:32.843141097   27813 resource_quota_server.c:258] Unexpected status code: 2` being logged here)

```
D1017 17:59:32.841617382   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 187 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841636016   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 189 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841657468   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 191 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841677241   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 193 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841698815   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 195 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841718878   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 197 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841738828   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 199 stalled by transport [fc:pending=1048580:flowed=0:peer_initwin=4194304:t_win=0:s_win=2974904:s_delta=0]
D1017 17:59:32.841761524   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 11 stalled by transport [fc:pending=0:flowed=0:peer_initwin=4194304:t_win=0:s_win=1954583:s_delta=-1020321]
D1017 17:59:32.841780668   27839 writing.cc:142]             ipv6:[::1]:17689:0x7da400000000 stream 19 stalled by transport [fc:pending=0:flowed=0:peer_initwin=4194304:t_win=0:s_win=2293494:s_delta=-681410]
E1017 17:59:32.843141097   27813 resource_quota_server.c:258] Unexpected status code: 2
```

https://sponge.corp.google.com/target?id=b2801c29-f027-471b-a783-8124e981c539&target=github/grpc/c_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

**Comment by murgatroid99** [comment]
Same failure seen with `bins/opt/h2_fakesec_test resource_quota_server GRPC_POLL_STRATEGY=poll` at https://sponge.corp.google.com/target?id=ef35da33-0c44-4999-af0d-b3cdff16960a&target=grpc/ubuntu/pull_request/grpc_basictests_c_opt&searchFor=&show=ALL&sortBy=STATUS

**Comment by mehrdada** [comment]
Seen in ASAN Linux for #13466 

https://sponge.corp.google.com/target?id=a60a2316-bb71-48d9-a073-8d59ab06f27d&target=github/grpc/c_linux_asan_native&searchFor=&show=ALL&sortBy=STATUS

**Comment by sreecha** [comment]
This is fixed by https://github.com/grpc/grpc/pull/13259 and https://github.com/grpc/grpc/pull/13579
