### ISSUE TITLE
Fix Grpc.Core.targets in Grpc.Core to avoid include dependencies in dependent packages

### ISSUE THREAD

**Issue by FrankGrossmann** [grpc/grpc#12926]
We are using Version 1.4.1 of Grpc.Core on Windows using C#. 
There is an an Solution to create C# code of our proto files and publish them internally as nuget packages for further using.

The problem is that when we create nuget packages from the generated code the native dependencies will be include in our packages because the ContentType is "Content". When the Content type would be "None" the behavior would be the same that the dependencies are copied to the "bin" directory except the issue that it will included in our nuget packages.

So what we want is a Grpc.Core.targets file in the package looking as follows:

`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\win\native\grpc_csharp_ext.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>grpc_csharp_ext.x86.dll</Link>
    </None>
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\win\native\grpc_csharp_ext.x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>grpc_csharp_ext.x64.dll</Link>
    </None>
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\linux\native\libgrpc_csharp_ext.x86.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x86.so</Link>
    </None>
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\linux\native\libgrpc_csharp_ext.x64.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x64.so</Link>
    </None>
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx\native\libgrpc_csharp_ext.x86.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x86.dylib</Link>
    </None>
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx\native\libgrpc_csharp_ext.x64.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x64.dylib</Link>
    </None>
  </ItemGroup>
</Project>`
 
instead of
 
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\win\native\grpc_csharp_ext.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>grpc_csharp_ext.x86.dll</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\win\native\grpc_csharp_ext.x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>grpc_csharp_ext.x64.dll</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\linux\native\libgrpc_csharp_ext.x86.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x86.so</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\linux\native\libgrpc_csharp_ext.x64.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x64.so</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx\native\libgrpc_csharp_ext.x86.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x86.dylib</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx\native\libgrpc_csharp_ext.x64.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libgrpc_csharp_ext.x64.dylib</Link>
    </Content>
  </ItemGroup>
</Project>`

**Comment by FrankGrossmann** [comment]
Do you have any forecast when it will be fixed?

**Comment by jtattermusch** [comment]
@FrankGrossmann  is this still a problem?
