### ISSUE TITLE
Node failure on macos

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#12932]
https://sponge.corp.google.com/target?id=8712989b-35d6-4c02-b2f2-b3b773226412&target=github/grpc/node_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

The specific error is

```
E1006 16:30:37.277871000 140735180103680 resource_quota.cc:779]        assertion failed: old >= amount
```

**Comment by yashykt** [comment]
@ctiller This looks like something that might have been caused by PR #12677
