### ISSUE TITLE
FLAKE: tools/run_tests/helper_scripts/run_grpc-node.sh

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12941]
https://sponge.corp.google.com/target?id=a1d076cd-f8a7-49f1-9bac-32147796f008&target=github/grpc/grpc-node_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by murgatroid99** [comment]
This looks like the same failure I reported in #12932.

**Comment by adelez** [comment]
This looks like the same failure I reported in #12932.
