### ISSUE TITLE
pecl grpc extension can not start with php 7.0

### ISSUE THREAD

**Issue by netroby** [grpc/grpc#12951]
can not enable grpc extension for php
```
[11-Oct-2017 07:30:38 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/grpc.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/grpc.so: undefined symbol: __gxx_personality_v0 in Unknown on line 0

```

**Comment by dej4vu** [comment]
the same in php5

**Comment by stanley-cheung** [comment]
Can you give us more information on how to reproduce this? Which platform/OS?

**Comment by netroby** [comment]
ubuntu 17.10 x64,

**Comment by stanley-cheung** [comment]
@ZhouyihaiDing Can you see if you can reproduce this?

**Comment by civersen** [comment]
Same here:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/grpc.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/grpc.so: undefined symbol: __gxx_personality_v0 in Unknown on line 0`

**Comment by ZhouyihaiDing** [comment]
I haven't reproduced this on ubuntu 14/17 nor php 5/7. it may caused by something else other than platform/OS and the php version.
Can you give us more information about how to reproduce it?

**Comment by ZhouyihaiDing** [comment]
Can you offer me more information about how to reproduce it? 
Are you install the grpc.so using pecl? If so, you can try compile the gRPC PHP extension manualy as "[https://github.com/grpc/grpc/tree/master/src/php#build-from-source](https://github.com/grpc/grpc/tree/master/src/php)".

**Comment by civersen** [comment]
Thanks for your help ZhouyihaiDing, I did install using pecl but after I manually compiled it - it works! If it helps at all, I noticed running code using "php -d extension=grpc.so [...]" did work before manually building it.

**Comment by ZhouyihaiDing** [comment]
I think is the missing dependency if you download 1.6.0 version using pecl.
https://github.com/grpc/grpc/blob/v1.6.0/config.m4#L15 should add -fno-exceptions -fno-rtti

**Comment by stanley-cheung** [comment]
The extension version 1.7.0 is released on PECL, sorry for the delay

**Comment by ZhouyihaiDing** [comment]
Thank you! If there is no error in this package, I can help you to do the
release later after you share the account with me.
One question is about grpc-1.6.0. This one lacks dependencies for sure, do
we need to swap this one with some version like 1.6.1?
Best,
Ding
