### ISSUE TITLE
`set_buffer_hint` for first message will make the other endpoint block forever

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#12975]
Take [route guide](https://github.com/grpc/grpc/blob/v1.6.6/examples/cpp/route_guide/) as an example, if change `ListFeatures` in server to following:

```
Status ListFeatures(ServerContext* context,
                    const routeguide::Rectangle* rectangle,
                    ServerWriter<Feature>* writer) override {
  auto lo = rectangle->lo();
  auto hi = rectangle->hi();
  long left = (std::min)(lo.longitude(), hi.longitude());
  long right = (std::max)(lo.longitude(), hi.longitude());
  long top = (std::max)(lo.latitude(), hi.latitude());
  long bottom = (std::min)(lo.latitude(), hi.latitude());
  WriteOptions opt;
  opt.set_buffer_hint();
  bool sent = false;
  for (const Feature& f : feature_list_) {
    if (f.location().longitude() >= left &&
        f.location().longitude() <= right &&
        f.location().latitude() >= bottom &&
        f.location().latitude() <= top) {
      if (sent) {
        opt.clear_buffer_hint();
      }
      writer->Write(f, opt);
      sent = true;
    }
  }
  return Status::OK;
}
```

client will block forever with outputs:
```
DB parsed, loaded 100 features.
-------------- GetFeature --------------
Found feature called BerkshireValleyManagementAreaTrail,Jefferson,NJ,USA at 40.9146, -74.6189
Found no feature at 0, 0
-------------- ListFeatures --------------
Looking for features between 40, -75 and 42, -73
```

**Comment by vjpai** [comment]
I tried this at master and was not able to reproduce it.

**Comment by BusyJay** [comment]
Updated to master, and reproduce it successfully. The commit I tried is 6bf5f833efe2cb9e2ecc14358dd9699cd5d05263. I also created a branch [here](https://github.com/BusyJay/grpc/tree/test-buffer-hint) with my modification to produce the bug.

My development environment:

```
> cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
> uname -r
4.12.14-200.fc25.x86_64
> gcc --version
gcc (GCC) 6.4.1 20170727 (Red Hat 6.4.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by vjpai** [comment]
I am able to repro the issue after all. I made a mistake in my last repro attempt. Reopening.

**Comment by BusyJay** [comment]
Hi, any updates on this?

**Comment by vjpai** [comment]
Marking as P3 since this is not really a documented feature but rather the back-end for actually documented APIs.

**Comment by vjpai** [comment]
It's been a while, but I think the best reasonable option is to disable the explicit use of set_buffer_hint in the sync API. The reason is that the sync API is based on the idea that a Write is committed (and the next Write can be sent) when this Write finishes. This is not actually true for buffered writes: we could either wait for it to truly be committed (defeating the point of buffering) or force some other synchronization mechanism to exist to prevent the next Write (removing the benefit of the sync API). This is why we've only activated and tested the use of this option on last messages here. I will probably make a PR to do this soon.

**Comment by BusyJay** [comment]
Take it easy bot, the issue is not resolved yet.

**Comment by treehaqr** [comment]
I'm hitting this issue as well and I'm using Async API. If this isn't something that's supported please remove it from your guide https://grpc.io/docs/guides/performance/

**Comment by subbota-a** [comment]
> I'm hitting this issue as well and I'm using Async API. If this isn't something that's supported please remove it from your guide https://grpc.io/docs/guides/performance/

I ran accros the issue using Async API in 1.44 version. 
1.45 works well.

**Comment by CloudBai1769** [comment]
I met this bug again in gRPC 1.55.0 again with AsyncAPI. When I send the first message with buffer_hint the write will never return in CQ.
