### ISSUE TITLE
Request for option to disable IPv6

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#12977]
Observed using C#, but expected to be common across all C-core based languages.

A customer has observed that streaming reads have a large delay (40s or more) on box their home development box and in production. Diagnostics have shown an initial unsuccessful attempt to use IPv6, followed by a successful fallback to IPv4.

Non-streaming reads appear not to cause a problem.

**Comment by jtattermusch** [comment]
@nicolasnoble, any opinions?

**Comment by benwulfe** [comment]
This looks similar to https://github.com/grpc/grpc/issues/6623.

More detail.
Customer determined on their own that IPV6 was to blame by looking at outgoing TCP requests and seeing a failed IPV6 connection.  Upon disabling IPv6 on their home machine, the 40 second initial latency was gone.  Note: (further testing showed this actually affects all APIs including non-streaming reads)

Customer then debugged various machines by running:
ping -6 <X.googleapis.com>
ping -4 <X.googleapis.com>

and found several of their machines in production also had issues.
Being forced to turn off IPV6 on their production machines may be a nonstarter and having a 40 second reconnect delay upon restart is as well.

Having a ChannelOption to resolve a dns to only IPV4 would put us on par with existing frameworks that we may be compared against.

**Comment by jtattermusch** [comment]
Is this Windows or Linux (or both?)

**Comment by benwulfe** [comment]
So far only Windows

**Comment by jtattermusch** [comment]
@dgquintas feel free to reassign.

**Comment by benwulfe** [comment]
Is there an update I can bring back to the user?  Do you think we can add this option?

**Comment by dgquintas** [comment]
@yashykt , given that you've been firing up windows VMs, do you feel comfortable giving this a shot?

**Comment by yashykt** [comment]
not sure how I missed this. I can take this on, but will not be able to work on this anytime soon.

**Comment by yashykt** [comment]
Couldn't spend time on it the past year. Assigning to @apolcyn who has been been working on related stuff

**Comment by apolcyn** [comment]
It sounds like the client's host where this is happening has IPv6 enabled, e.g. it sounds like they have routability for the resolved IPv6 addresses which were problematic, but just that there are somehow problems with IPv6 connectivity the environment? Can we confirm that's the case? If it is, then just disabling IPv6 on that machine, if possible, is tempting. <i>In general</i>, (though it's possible that something else is throwing it off here), gRPC clients will query both ipv4 and ipv6 DNS records, and then the order that it iterates over those answers is defined roughly by RFC 3484/6724.
