### ISSUE TITLE
C++ WriteOptions method `clear_last_messsage` likely a typo for `clear_last_message`

### ISSUE THREAD

**Issue by zhouyan** [grpc/grpc#12972]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.6.6
 
### What operating system (Linux, Windows, …) and version?
 Linux CentOS 7.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Clang 5.0
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 The method `clear_last_messsage` looks like a typo. Likely the intention was `clear_last_message` (2 `s`, instead of 3)
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by thinkerou** [comment]
I think you are right.

**Comment by vjpai** [comment]
Yes, this was a typo. Looks like it was never tested either.
