### ISSUE TITLE
grpc.node support for electron 1.7.x

### ISSUE THREAD

**Issue by Syed-Umair** [grpc/grpc#12985]
Please rebuild grpc.node for electron 1.7.x versions, I depend on this module critically. please help

**Comment by Syed-Umair** [comment]
I need the grpc.node to be compiled for the electron ia32 1.7.9 please help. This is a barrier for my production.

**Comment by Syed-Umair** [comment]
Nice thanks for your effort, I hope will be fixing it soon

**Comment by kamesh-a** [comment]
Hello,

Can we please add support for upcoming electron version 1.8. Electron releases every upgrade to chrome. How we can for upcoming versions in future. 

Or is there any things can be done to try rebuilding from our end.

**Comment by murgatroid99** [comment]
Thank you for your patience. I have uploaded electron 1.7 binaries for grpc@1.6.6. You should be able to install it now.

I will try to add support for new versions of Electron in a more timely manner in the future.

**Comment by Syed-Umair** [comment]
Thank you so much for your work @murgatroid99
