### ISSUE TITLE
Many ubsan test failures

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12982]
https://sponge.corp.google.com/target?id=c597bfd7-227f-4693-be75-0dd4630a2a74&target=github/grpc/c_linux_ubsan_native&searchFor=&show=ALL&sortBy=STATUS

Failure
D1012 00:49:04.538995764    1073 ev_posix.cc:125]            Using polling engine: none
D1012 00:49:04.539643443    1073 dns_resolver.cc:306]        Using native dns resolver
E1012 00:49:04.563860135    1073 ev_posix.cc:67]             Attempted to poll despite declaring non-polling.
E1012 00:49:04.563897923    1073 ev_posix.cc:68]             assertion failed: false

**Comment by adelez** [comment]
Hi Vijay, I'm not sure who's the appropriate owner. Free feel to reassign.

**Comment by vjpai** [comment]
Hi Adele, those tests ran at 5:34 PM. PR #12965 landed around 10:00 PM and should have resolved all of them. Can you rerun tests with the latest master and open this issue again if there are still failures? Thanks!
