### ISSUE TITLE
Support request compression in ObjC

### ISSUE THREAD

**Issue by bfetscher** [grpc/grpc#12988]
Although the core, C++, and Java client libraries all support the ability to enable compression for client requests, there is no way to do this currently with the Objective-C library. This would be useful for clients that have large compressible requests, and would provide better consistency across the gRPC client libraries.

(gRPC-ObjC v. 1.6.5)

**Comment by bfetscher** [comment]
Longshot feature request: it would be great if the pre and post-compression sizes were available so they could be logged for analysis.

**Comment by muxi** [comment]
Fixed by #13865. Closing.
