### ISSUE TITLE
win32 file suffix is confusing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#130]
Windows specific files (for both 64bit and 32bit) have _win32 suffix and are using GPR_WIN32 header guard.
Change this to _windows file suffix and GPR_WINDOWS header.

**Comment by jtattermusch** [comment]
@ctiller , should we polish this for GA or did we effectively got stuck with this forever because we made the API stable?

**Comment by nicolasnoble** [comment]
"win32" is the commonly accepted suffix for anything using the modern (post Windows 3.1) Windows API. It IS in fact the name of the Windows API. Compiling in 64 bits means you have to define both _WIN32 and _WIN64 for it to work.
