### ISSUE TITLE
branch v1.6.x build failed.

### ISSUE THREAD

**Issue by topillar** [grpc/grpc#13012]
Windows7
VS2017 +SDK8.1
GRPC branch v1.6.x

[ninja_log.txt](https://github.com/grpc/grpc/files/1385089/ninja_log.txt)

[537/1904] Generating ../../../third_p.../compiler/js/well_known_types_embed.cc
ninja: build stopped: subcommand failed.

**Comment by topillar** [comment]
a bug of protobuf 3.40

**Comment by apolcyn** [comment]
@topillar do you know if this issue exists with the latest grpc/protobuf versions (on the 1.17 branch)?

**Comment by topillar** [comment]
Sorry, I didn't test it any more.
