### ISSUE TITLE
node.js: It is not possible to define include paths when loading proto files

### ISSUE THREAD

**Issue by jleni** [grpc/grpc#13010]
At the moment, it is not possible to indicate include paths. For this reason, it is likely that import statements fail. Even standard protobuf types such as timestamp do not work:

`import "google/protobuf/timestamp.proto"`

It seems that grpc for node.js does not even deploy these files.

**Comment by jleni** [comment]
@murgatroid99 Is this is known limitation?

**Comment by nishant-chaturvedi** [comment]
We are facing the same issue, for any proto file which has import statement like `import "google/protobuf/timestamp.proto"`, grpc node fails to load it with `file not found` error.

Is there any known workaround?

**Comment by ChromoX** [comment]
This is a problem for me as well. I wish there was a way of specifying multiple "root" directories.

My current workaround is to link the google include path into my protobufs directory, and call ```grpc.load({ file: <filePath>, root: ROOT_PROTO_PATH})```

**Comment by eelkevdbos** [comment]
My problem was solved using the `@grpc/proto-loader` package.

```js
// server.js
import grpc from 'grpc';
import * as protoLoader from '@grpc/proto-loader';

/**
# my_package.proto
package my_package;
service MyService {
    rpc Test() returns (TestResponse);
}
**/

const PROTO_PATH = __dirname + '/protos/my_package.proto';
let protoDefinition = protoLoader.loadSync(PROTO_PATH, {});
let packageDefinition = grpc.loadPackageDefinition(packageDefinition); 

console.log(packageDefinition); // { my_package: { MyService: fn() } }
```

**Comment by nicolasnoble** [comment]
Yes, that was one of the reasons we added this package.

**Comment by Olshansk** [comment]
Is there any way to use "@grpc/proto-loader"'s include paths feature when I don't have a gRPC service defined, but just protobufs importing other nested protobufs?

I find that protoDefinition returns an empty object if there is not gRPC service.

**Comment by nicolasnoble** [comment]
`@grpc/proto-loader` can only be used to load grpc services. It's not designed to do anything else.

**Comment by Olshansk** [comment]
Thanks for the reply @nicolasnoble. I found a workaround for my issue and documented the solution here: https://github.com/grpc/grpc-node/issues/444#event-1743423441
