### ISSUE TITLE
grpc-php server

### ISSUE THREAD

**Issue by songkemail** [grpc/grpc#1304]
hi tbetbetbe，can php implent as grpc server?

**Comment by nicolasnoble** [comment]
Not at the moment, no.

**Comment by tbetbetbe** [comment]
Hi - thanks for the question!  At the moment, we only plan to support PHP clients.

At some point in the future, after gRPC reaches Beta, we'd like to look at the question of PHP servers again; in the meantime we welcome ideas and suggestions about how this will work.

I'll close this issue for now, but please re-open to continue the discussion with any ideas you'd like discuss for running gRPC in a PHP server.

**Comment by kocherovf** [comment]
+1

**Comment by Shumkov** [comment]
[ReactPHP](http://reactphp.org/) or any webserver with http2 support + fpm?

**Comment by Shumkov** [comment]
Guys, please say something :). What is your plan about php server?

**Comment by taojoe** [comment]
maybe swoole is a solution. it's php extension written by Chinese guy. 
https://github.com/swoole/swoole-src

the official site is Chinese, you can see the code show's async io.  http://www.swoole.com/

**Comment by shumkov** [comment]
I've just released "GRPC everywhere". It's not exactly PHP GRPS server. It's NodeJS service which receives GRPC request and passes them to PHP (or something else) by FastCGI (or something else). It's kinda nginx or proxy. You can specify path to proto file and fpm address in config and it works.

Be warned: not all GRPC specification implemented and only FastCGI connector for PHP is present. But I used it in several internal projects in production more than half of year and it solved my problems :).

https://github.com/shumkov/grpc-everywhere
