### ISSUE TITLE
[FLAKE] grpclb_end2end_test --gtest_filter=SingleBalancerTest.BackendsRestart

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13040]
bins/dbg/grpclb_end2end_test --gtest_filter=SingleBalancerTest.BackendsRestart  GRPC_POLL_STRATEGY=epoll1 

017-10-17 01:41:48,049 I1017 01:41:47.631306667   11641 ev_epoll1_linux.cc:93]      grpc epoll fd: 3
D1017 01:41:47.631402244   11641 ev_posix.cc:138]            Using polling engine: epoll1
D1017 01:41:47.631442004   11641 dns_resolver.cc:306]        Using native dns resolver
D1017 01:41:47.631498091   11641 test_config.c:388]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
Note: Google Test filter = SingleBalancerTest.BackendsRestart
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SingleBalancerTest
[ RUN      ] SingleBalancerTest.BackendsRestart
I1017 01:41:47.633060213   11641 grpclb_end2end_test.cc:525] starting backend server on port 1216
I1017 01:41:47.633213851   11773 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1017 01:41:47.635455395   11641 grpclb_end2end_test.cc:530] backend server startup complete
I1017 01:41:47.636823832   11641 grpclb_end2end_test.cc:525] starting backend server on port 23573
I1017 01:41:47.637039869   11802 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1017 01:41:47.640319382   11641 grpclb_end2end_test.cc:530] backend server startup complete
I1017 01:41:47.641749834   11641 grpclb_end2end_test.cc:525] starting backend server on port 32434
I1017 01:41:47.641943453   11824 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1017 01:41:47.644712950   11641 grpclb_end2end_test.cc:530] backend server startup complete
I1017 01:41:47.646006184   11641 grpclb_end2end_test.cc:525] starting backend server on port 16048
I1017 01:41:47.646177492   11850 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1017 01:41:47.648797971   11641 grpclb_end2end_test.cc:530] backend server startup complete
I1017 01:41:47.650491238   11641 grpclb_end2end_test.cc:525] starting balancer server on port 17288
I1017 01:41:47.650670250   11881 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1017 01:41:47.653393404   11641 grpclb_end2end_test.cc:530] balancer server startup complete
I1017 01:41:47.654427094   11920 grpclb_end2end_test.cc:188] LB[0x1500ba0]: BalanceLoad
I1017 01:41:47.654753444   11920 grpclb_end2end_test.cc:192] LB[0x1500ba0]: recv msg 'initial_request {
  name: "servername_not_used"
}
'
I1017 01:41:47.654775829   11920 grpclb_end2end_test.cc:304] LB[0x1500ba0]: sleeping for 0 ms...
I1017 01:41:47.654818307   11920 grpclb_end2end_test.cc:310] LB[0x1500ba0]: Woke up! Sending response 'server_list {
  servers {
    ip_address: "\177\000\000\001"
    port: 1216
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 23573
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 32434
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 16048
  }
}
'
I1017 01:41:47.655047944   11820 grpclb.cc:530]              Missing LB token for backend address 'ipv4:127.0.0.1:1216'. The empty token will be used instead
I1017 01:41:47.655069589   11820 grpclb.cc:530]              Missing LB token for backend address 'ipv4:127.0.0.1:23573'. The empty token will be used instead
I1017 01:41:47.655075595   11820 grpclb.cc:530]              Missing LB token for backend address 'ipv4:127.0.0.1:32434'. The empty token will be used instead
I1017 01:41:47.655080538   11820 grpclb.cc:530]              Missing LB token for backend address 'ipv4:127.0.0.1:16048'. The empty token will be used instead
I1017 01:41:47.801409303   11641 grpclb_end2end_test.cc:141] Backend: shut down
I1017 01:41:47.801419664   11920 grpclb_end2end_test.cc:250] LB[0x1500ba0]: done
I1017 01:41:47.801434383   11641 grpclb_end2end_test.cc:549] backend about to shutdown
I1017 01:41:47.801709454   11641 grpclb_end2end_test.cc:552] backend shutdown completed
I1017 01:41:47.801720375   11641 grpclb_end2end_test.cc:141] Backend: shut down
I1017 01:41:47.801738590   11641 grpclb_end2end_test.cc:549] backend about to shutdown
I1017 01:41:47.801936503   11641 grpclb_end2end_test.cc:552] backend shutdown completed
I1017 01:41:47.801947118   11641 grpclb_end2end_test.cc:141] Backend: shut down
I1017 01:41:47.801950444   11641 grpclb_end2end_test.cc:549] backend about to shutdown
I1017 01:41:47.802278625   11641 grpclb_end2end_test.cc:552] backend shutdown completed
I1017 01:41:47.802289779   11641 grpclb_end2end_test.cc:141] Backend: shut down
I1017 01:41:47.802293243   11641 grpclb_end2end_test.cc:549] backend about to shutdown
I1017 01:41:47.802510464   11641 grpclb_end2end_test.cc:552] backend shutdown completed
E1017 01:41:47.802571563   11926 round_robin.cc:426]         assertion failed: !p->shutdown

**Comment by dgquintas** [comment]
This is a known issue, to be fixed by https://github.com/grpc/grpc/pull/12829.

**Comment by dgquintas** [comment]
Fixed by #12427

**Comment by dgquintas** [comment]
It seems it's not fixed :/ Having a look...

**Comment by dgquintas** [comment]
Actually, fixed, although there's a related one in #13299
