### ISSUE TITLE
Node GRPC dependency painfully large

### ISSUE THREAD

**Issue by relwell** [grpc/grpc#13071]
### What version of gRPC and what language are you using?
 3.4.0
 
### What operating system (Linux, Windows, …) and version?
 Linux and OS X
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 grpc_tools
 
### What did you do?
Added GRPC as a dependency in NodeJS
 
### What did you expect to see?
 A reasonably-sized dependency
 
### What did you see instead?
 `node_modules` folder increases by 64MB
 
### Anything else we should know about your project / environment?
34M of this comes from `boringssl`. It would be great if we could reduce the dependency on this, or make it a peer dependency so we can only optionally include it in size-constrained environments.

**Comment by murgatroid99** [comment]
We are addressing this in the next release, 1.7.0. Prerelease packages for that will be published soon.

**Comment by lewchuk** [comment]
Is there any update on this? And/or should this issue move to https://github.com/grpc/grpc-node?

Using 1.7.1 and 1.7.3 (as dependencies of firebase-admin) I still see node_modules as over 50 MB with boring ssl continuing to take up 34 MB of it.

**Comment by murgatroid99** [comment]
This has been improved in 1.8.4. On my computer, grpc now accounts for about 34MB, and most of the unnecessary files have been omitted.
