### ISSUE TITLE
Windows h2_proxy_test.exe & h2_proxy_nosec_test.exe failing (100% cases)

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13079]
https://sponge.corp.google.com/target?id=8176946b-0c65-41e6-bb71-b9551aa8edcd&target=github/grpc/c_windows_opt_native&searchFor=&show=FAILED&sortBy=STATUS

Multiple test cases failing with high probability (close to 100%)
```
cmake/build/Release/h2_proxy_test.exe high_initial_seqno 
cmake/build/Release/h2_proxy_nosec_test.exe high_initial_seqno 
cmake/build/Release/h2_http_proxy_test.exe graceful_server_shutdown 
cmake/build/Release/h2_ssl_proxy_test.exe max_connection_age 
```

```
Failure
D1024 14:21:22.423000000  4972 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1024 14:21:22.439000000  4972 dns_resolver.cc:306] Using native dns resolver
I1024 14:21:24.533000000  4972 http_proxy_fixture.c:495] Proxy address: localhost:26647
I1024 14:21:24.533000000  1664 http_connect_handshaker.cc:305] Connecting to server localhost:15470 via HTTP proxy ipv6:[::1]:26647
D1024 14:21:24.533000000  1664 http_proxy_fixture.c:341] on_read_request_done: 009C2E88 "No Error"
I1024 14:21:26.080000000  1664 http_proxy_fixture.c:136] HTTP proxy server read: {"created":"@1508880086.080000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.cc","file_line":185}
E1024 14:21:26.080000000  4972 cq_verifier.c:298] unexpected event (expected nothing): OP_COMPLETE: tag:00000001 OK
Abort handler called.
*** 0: 00000000002B40CC  - 0000000000000000
*** 1: 00000000002B3CFD  - 0000000000000000
*** 2: 000000006C704672 abort - 000000006C704640
*** 3: 00000000002717D1 abort - 000000006C704640
*** 4: 0000000000253C83 abort - 000000006C704640
I1024 14:21:26.080000000  1664 http_proxy_fixture.c:136] HTTP proxy client read: {"created":"@1508880086.080000000","description":"TCP stream shutting down","file":"T:\src\github\grpc\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.cc","file_line":184,"referenced_errors":[{"created":"@1508880086.080000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.cc","file_line":185}]}
*** 5: 00000000002538CE abort - 000000006C704640
*** 6: 0000000000242114 abort - 000000006C704640
*** 7: 000000000024122F abort - 000000006C704640
D1024 14:21:26.080000000  1664 http_proxy_fixture.c:108] endpoints: 009109A0 00910A28
*** 8: 00000000002BDDF9 abort - 000000006C704640
*** 9: 0000000074DD336A BaseThreadInitThunk - 0000000074DD3358
*** 10: 00000000770E9902 RtlInitializeExceptionChain - 00000000770E989F
*** 11: 00000000770E98D5 RtlInitializeExceptionChain - 00000000770E989F
Command exited with non-zero status 1
real 3.70
user 0.00
sys 0.00
```

**Comment by jtattermusch** [comment]
~10 tests failing 100% of time -> escalating to P0.

**Comment by jtattermusch** [comment]
@dgquintas, who's the right person to fix?

**Comment by jtattermusch** [comment]
Any updates here? It's failing in 100% runs.

**Comment by dgquintas** [comment]
I talked to @nicolasnoble about this last week. We are lacking Windows expertise for fixing this. We talked about ways to improve this, but nothing short term enough to deal with the failing tests. 

On the other hand, I don't think this is a Windows-specific issue. @yashykt and @sreecha have agreed to look into it.

**Comment by sreecha** [comment]
I won't be able to look into this in the next 2 days (since I already have a p0 on my plate).

**Comment by yashykt** [comment]
I'll take this on.

**Comment by yashykt** [comment]
The history from commits show that these tests have been failing for other fixtures too like h2_ssl_proxy_test and h2_http_proxy_nosec_test.

I tried running these locally on a Windows VM and these pass, which makes me think that the timeout for these tests is too low for Windows.

**Comment by jtattermusch** [comment]
I did some extra analysis on the test result data:

Tests that are *timing out* (the timeout is 5mins, which should really be high enough), both for Release and Debug:
```
h2_ssl_proxy_test.exe high_initial_seqno
h2_proxy_test.exe high_initial_seqno
```

Tests that are failing (after ~15secs), both Release and Debug:
```
*_proxy_test.exe max_connection_age
*_proxy_test.exe graceful_server_shutdown
```

Useful bigquery that shows all the recent failures and timeouts:
```
select * from jenkins_test_results.aggregate_results where test_name like '%proxy_test%' and job_name like '%windows%basictests%' and timestamp > '2017-10-25 00:00' and result != 'PASSED' order by timestamp desc limit 10000 
```

**Comment by jtattermusch** [comment]
I am able to reproduce locally. From tracing logs, it looks like that the `cq_verify_empty` here: https://github.com/grpc/grpc/blob/49e2ce3b78b21909b625c61d088d0c94b04a75fc/test/core/end2end/tests/graceful_server_shutdown.c#L150 doesn't return after 1 second as it should, but instead waits for the whole 10s until the client call times out (it has timeout of 10s) - at which point the unexpected tag of "0x1" is delivered.

```
$  GRPC_VERBOSITY=debug GRPC_TRACE=api Debug/h2_http_proxy_test.exe graceful_server_shutdown
...
I1101 14:46:27.785000000  5588 server.cc:1260] grpc_server_shutdown_and_notify(server=0088A118, cq=0088AE20, tag=0000DEAD)
I1101 14:46:27.785000000  5588 graceful_server_shutdown.c:156] gpr_now(GPR_CLOCK_REALTIME): tv_sec 1509547587 tv_nsec 785000000
I1101 14:46:27.785000000  5588 graceful_server_shutdown.c:157] gpr_now(GPR_CLOCK_MONOTONIC): tv_sec 0 tv_nsec 733949400
I1101 14:46:27.785000000  5588 completion_queue.cc:883] grpc_completion_queue_next(cq=0088AE20, deadline=gpr_timespec { tv_sec: 1509547588, tv_nsec: 785000000, clock_type: 1 }, reserved=00000000)
^ this is the grpc_completion_queue_next called by cq_verify_empty. 
  It has timeout of 1 sec but doesn't wake up until 10 sec later.
I1101 14:46:37.783000000  2164 completion_queue.cc:663] cq_end_op_for_next(exec_ctx=043AF950, cq=0088AE20, tag=00000001, error="No Error", done=00D7DEE0, done_arg=0081125C, storage=00811260)
I1101 14:46:37.783000000  5588 completion_queue.cc:984] RETURN_EVENT[0088AE20]: OP_COMPLETE: tag:00000001 OK
E1101 14:46:37.783000000  5588 cq_verifier.c:298] unexpected event (expected nothing): OP_COMPLETE: tag:00000001 OK
I1101 14:46:37.783000000  6120 completion_queue.cc:663] cq_end_op_for_next(exec_ctx=03FBFE1C, cq=0088AE20, tag=0000DEAD, error="No Error", done=00D6ABF0, done_arg=0088A118, storage=00858820)
Abort handler called.
```

So it looks like we're missing a kick somewhere.Actually, in some runs, we get lucky, and cq_next wakes up sooner then in 10 seconds (I've seen instances with 9.03sec) and then the test passes.

**Comment by jtattermusch** [comment]
My unproven theory:
https://github.com/grpc/grpc/blob/master/src/core/lib/surface/completion_queue.cc#L949 is the place where cq_next should exit in case the deadline is hit and there's still no new event. But inside https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/exec_ctx.cc#L141,  `exec_ctx->now_is_valid` is `true` and  exec_ctx->now contains the timestamp when cq_next has started and it's not getting updated. So it looks like we are missing a call to `grpc_exec_ctx_invalidate_now` somewhere?

**Comment by jtattermusch** [comment]
I can confirm that an ugly hack of updating exec_ctx->now every time  grpc_exec_ctx_now() is inspected fixes at least a subset some of the issues we are seeing.
@ctiller, any tips where we should add `grpc_exec_ctx_invalidate_now` for a proper fix?

**Comment by ctiller** [comment]
Wherever we block for a significant amount of time.

One clever way of finding this: ctrl+c when the application is sleeping,
and ensure that we've got an invalidate after that.

**Comment by yashykt** [comment]
I was able to reproduce the problem with 8vcpus instead of 1. And this issue was seen with both 64 bit and 32 bit builds.

It seems that GPR_CLOCK_MONOTONIC time is being compared to GPR_CLOCK_REALTIME time. This might be the cause.

@ctiller, are we following a standard as to when use what?

**Comment by sreecha** [comment]
We should not be doing this comparison without making both clocktypes the same.
Can you point to the code that is doing this ?

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/blob/66b740a8c60df59d7c82c8f7e122369ee86d62c1/src/core/lib/surface/completion_queue.cc#L950 
Here, for example, we are comparing deadline which might be in realtime to exec_ctx_now which is monotonic.

**Comment by yashykt** [comment]
This code also makes the assumption that grpc_pollset_work calls grpc_invalidate_now so that grpc_exec_ctx_now, but that's not always true.

https://github.com/grpc/grpc/blob/66b740a8c60df59d7c82c8f7e122369ee86d62c1/src/core/lib/iomgr/pollset_windows.cc#L162

This path for example does not call invalidate_now. It is instead called in grpc_iocp_work which is not always called.

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/pull/13234

This PR for example places an invalidate_now at the end of the cq_next loop. Doing this makes all the failing tests succeed atleast locally (on a windows VM)

Also, the reason why it is happening only on proxy related tests is probably because proxy introduces another thread which causes one of the threads to take the path in grpc_pollset_work that does not hit grpc_exec_ctx_invalidate_now

**Comment by dgquintas** [comment]
Great stuff, thanks Yash for looking into this and seemingly root causing
it so quickly.
