### ISSUE TITLE
Windows gRPC C core memory leak

### ISSUE THREAD

**Issue by JakaBac** [grpc/grpc#13088]
### Should this be an issue in the gRPC issue tracker?
Yes, I believe so
 
### What version of gRPC and what language are you using?
C++ master branch and also v1.6.x (current https://grpc.io/release) 
 
### What operating system (Linux, Windows, …) and version?
Windows 10 version 1709 OS Build 16299.19 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 2017 (15.4.1)
 
### What did you do?
Run standard helloworld sample server and client on same machine.
Modified helloworld client so it opens 100 connections and does 100 requests (one per connection), run more instances of modified helloworld client (in order to open and close "large" amount of tcp connections)
 
### What did you expect to see?
helloworld server & client doing their thing.
helloworld server's process ram should not increase constantly 
 
### What did you see instead?
helloworld server process ram was growing slowly with each open tcp connection. When all connections were closed ram was not reclaimed.
Memory was also not freed after calling  `server->Shutdown();` 
 
### Anything else we should know about your project / environment?
When trying find out why this is happening I found out that the memory which is not freed is getting allocated in `grpc_resource_quota_create` called by `grpc_tcp_create`

By tracing the execution of the function and also tracing the related `tcp_free` i noticed that in `grpc_tcp_create` `resource_quota->refs.count` is set to `1` when `resource_quota` is created. This refcount is then increased when `tcp->resource_user = grpc_resource_user_create(resource_quota, peer_string);` is called near the end of the function. Since this looked a bit suspicious I checked how `grpc_tcp_create` is implemented in `tcp_posix.cc` and I saw that `grpc_resource_quota_unref_internal(exec_ctx, resource_quota);` is called before returning. This call is not present in `tcp_windows.cc`

Adding that line fixed the leak problem. I tested it with master and v1.6.x branch
I did not do run any gRPC tests

Then looking at the function as a whole I could see that there is some refcount increasing and decreasing going on if resource_quota is received from `grpc_channel_args *channel_args`, but `tcp_posix.cc` does the same thing.

So the patch is (no Pull request since I just started playing with gRPC today):
```
diff --git a/src/core/lib/iomgr/tcp_windows.cc b/src/core/lib/iomgr/tcp_windows.cc
index dc84e564a9..ad939d3b50 100644
--- a/src/core/lib/iomgr/tcp_windows.cc
+++ b/src/core/lib/iomgr/tcp_windows.cc
@@ -442,6 +442,7 @@ grpc_endpoint *grpc_tcp_create(grpc_exec_ctx *exec_ctx, grpc_winsocket *socket,
   tcp->resource_user = grpc_resource_user_create(resource_quota, peer_string);
   /* Tell network status tracking code about the new endpoint */
   grpc_network_status_register_endpoint(&tcp->base);
+  grpc_resource_quota_unref_internal(exec_ctx, resource_quota);

   return &tcp->base;
 }
```

**Comment by luchunminglu** [comment]
the grpc server and client i write in .net consumes 10mb more momery every day

**Comment by jtattermusch** [comment]
@JakaBac thanks for the detailed analysis. We'll look into that!

**Comment by JakaBac** [comment]
The patch also fixes csharp memory leak on Windows (also uses `grpc_tcp_create`). I built the csharp debug bits and tested with/without the patch and confirmed behaviour using native heap profiling in VS.
This probably affects all gRPC servers on Windows which use the C low level OS abstraction library.

**Comment by kkm000** [comment]
Thanks! 'fraid I am seeing the leak too (64-bit windows C++ server, gRPC built off the tag v1.6.6).

**Comment by JakaBac** [comment]
I believe that everything that is based on C core starting with v1.3.0 is affected (did not test, just had a quick look)

**Comment by luchunminglu** [comment]
Still have memory leak in 1.7.0 both in client and server

**Comment by jtattermusch** [comment]
@luchunminglu, a fix for another leak https://github.com/grpc/grpc/pull/13169 will be in 1.7.1, would that resolve the problem you are seeing? If not, please file an issue with details about what you're experiencing.

**Comment by kkm000** [comment]
@luchunminglu: Could you please do the following test? Set environment variables `GRPC_VERBOSITY` and `GRPC_TRACE` to an empty value (empty value for each won't change the behavior) and then see if you still have the leak you are mentioning in your last comment? The memory leak that @jtattermusch mentions happens only when either of these environment variables does not exist. If setting the variables resolves it for you, then you are seeing the issue that is fixed in the upcoming 1.7.1. If not, then we have more leaks to hunt for. Thanks!

**Comment by JakaBac** [comment]
@luchunminglu,@kkm000  with the patch for this issue and PR #13169 pulled into v1.6.7 I don't see any obvious leaks when running a C++ server and a C++/C# client.

**Comment by kkm000** [comment]
@JakaBac: Thanks for checking. So let's assume this was it!
