### ISSUE TITLE
bins/asan/client_lb_end2end_test --gtest_filter=ClientLbEnd2endTest.RoundRobinReresolve  GRPC_POLL_STRATEGY=epollex

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13080]
I1019 23:59:46.318312072   26063 client_lb_end2end_test.cc:195] server startup complete
test/cpp/end2end/client_lb_end2end_test.cc:169: Failure
Value of: status.ok()
  Actual: false
Expected: true
test/cpp/end2end/client_lb_end2end_test.cc:170: Failure
      Expected: response.message()
      Which is: ""
To be equal to: kRequestMessage_
      Which is: "Live long and prosper."
[  FAILED  ] ClientLbEnd2endTest.RoundRobinReresolve (149 ms)
[----------] 1 test from ClientLbEnd2endTest (149 ms total)

**Comment by dgquintas** [comment]
Duplicate of #13128
