### ISSUE TITLE
No need to package 64-bit protoc and C# codegen for Windows

### ISSUE THREAD

**Issue by kkm000** [grpc/grpc#13098]
~~Minor packaging issue: no point in keeping 64-bit protoc.exe and the C# codegen plugin in the Grps.Tools NuGet packages. There is no 64-bit Windows in the world that would be incapable of running 32-bit executables (in fact, many programs are 32-bit only; Visual Studio and Firefox are just two examples).~~

**NOTE** (2018-12-07):
The issue is now invalid. There *is* a variant of Windows distribution packaging that supports 64-bit executables only: [the nanoserver Docker image (docs)](https://docs.microsoft.com/windows-server/get-started/getting-started-with-nano-server#important-differences-in-nano-server) of Windows Server. From the above link, in case content gets moved:

> Because Nano Server is optimized as a lightweight operating system for running “cloud-native” applications based on containers and micro-services or as an agile and cost-effective datacenter host with a dramatically smaller footprint, there are important differences in Nano Server[...]:  
> * Only 64-bit applications, tools, and agents are supported.

**END NOTE**

IDK about other platforms. It is possible to be missing the 32 bit libc.so on Linux, AFAIK, so a 32-bit binary would not run where a 64-bit would. But the Windows one definitely just takes up space.

**Comment by jtattermusch** [comment]
@kkm000, you're right thanks for filing this. We might get rid of the win64 binary at some point, but because it's not really blocking for anyone, the priority of this issue is pretty low.

**Comment by jtattermusch** [comment]
As pointed out in #17437 the 64bit windows protoc is actually needed in some cases. Closing.
