### ISSUE TITLE
FAILURE: cmake/build/Debug/h2_proxy_test.exe 

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#13091]
```
Timeout
D1011 23:25:40.512000000  6152 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1011 23:25:40.512000000  6152 dns_resolver.cc:306] Using native dns resolver
I1011 23:25:40.512000000  6152 high_initial_seqno.c:42] Running test: test_invoke_requests first_seqno=16777213/chttp2/fullstack+proxy
D1011 23:25:42.950000000  6152 proxy.c:89] PROXY ADDR:localhost:20718 BACKEND:localhost:19691
```

https://sponge.corp.google.com/target?id=5303f474-1c25-487d-81c6-5f801a863693&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

seen in PR: https://github.com/grpc/grpc/pull/13031, this is currently failing on windows master (e.g. on this kokoro windows master test run: https://sponge.corp.google.com/invocation?id=90dedf46-ac15-4f51-93d8-42766aa3d461&searchFor=)

looks like this was failing in older runs (https://github.com/grpc/grpc/issues?q=is%3Aissue+high_initial_seqno+is%3Aclosed), but the Timeout is new

**Comment by jtattermusch** [comment]
I think this is the same as https://github.com/grpc/grpc/issues/13079 (already fixed).
