### ISSUE TITLE
ld: framework not found GRPCClient , 

### ISSUE THREAD

**Issue by jamesTheKid** [grpc/grpc#13095]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes 

Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
gRPC Version 1.6.5, and Swift 4 for the development of the iOS app
 
### What operating system (Linux, Windows, …) and version?
 MacOS Sierra
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Xcode 
 
### What did you do?
I try to compile my project after adding Firestore via cocoapod which has gRPC as dependencie
 
### What did you expect to see?
No error  
 
### What did you see instead?
And error : `ld: framework not found GRPCClient`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
<img width="853" alt="screen shot 2017-10-21 at 03 31 48" src="https://user-images.githubusercontent.com/631062/31846766-6a2f1164-b610-11e7-8e9a-0721ea6c9d58.png">

### Anything else we should know about your project / environment?
Xcode 9, test on iOS 9 , iOS 10 & iOS 11

**Comment by apolcyn** [comment]
@jamesTheKid since this is a Swift issue, in case this is still an issue, I believe it should be moved to the swift repo (https://github.com/grpc/grpc-swift). Closing here, can we please move it there?
