### ISSUE TITLE
Document and test failing to bind a port on a server

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#13096]
I believe that what will happen is that `grpc.Server.add_insecure_port` and `grpc.Server.add_secure_port` return `0` when they fail, but [we don't currently document this](https://github.com/grpc/grpc/blob/c563b583cb9b7fecc33971581368796d2df4759d/src/python/grpcio/grpc/__init__.py#L950-L983) and I don't recall our having a test for it.

**Comment by nathanielmanistaatgoogle** [comment]
(gRPC Python should probably raise an exception when failing to bind a port?)

**Comment by mehrdada** [comment]
I think that is the Python behavior indeed, which is curiously different from C++ ServerBuilder, where the actual binding gets deferred to server initialization, therefore, the integer output argument that gets filled only gets written to later in the server creation step and not immediately after AddPort.

**Comment by nathanielmanistaatgoogle** [comment]
Closing as a duplicate of [issue 11394](https://github.com/grpc/grpc/issues/11394).
