### ISSUE TITLE
bins/tsan/concurrent_connectivity_test 

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13125]
Note that it's a TSAN failure, under `epollex`, which is not the same as other issues for the same test described in #11383

**Comment by dgquintas** [comment]
Also for poll: https://sponge.corp.google.com/target?id=8ac6ad86-ac1e-40ef-b838-d0f37370fcfb&target=github/grpc/c_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

**Comment by sreecha** [comment]
There are about 5 different TSAN failures exposed by this test - all of them may or may not have the same root cause. I have a fix for one of the failures (https://github.com/grpc/grpc/pull/13294) 

Will triage the rest and reassign to folks.

**Comment by sreecha** [comment]
I can no longer repro this issue and this has not happened in a while now. I am closing it.
