### ISSUE TITLE
Fail to compile on Mac OS x

### ISSUE THREAD

**Issue by jamesgua** [grpc/grpc#13136]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes, it fail to compile
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 
 latest, download on 2017-10-16, trying to compile it for c++
### What operating system (Linux, Windows, …) and version?
 Mac OS X version 10.12.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++ -v 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

clang++ -v
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
$ LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make
...
[HOSTCXX] Compiling src/compiler/php_generator.cc
In file included from src/compiler/php_generator.cc:23:
./src/compiler/php_generator_helpers.h:51:23: error: no member named 'has_php_namespace' in 'google::protobuf::FileOptions'
  if (file->options().has_php_namespace()) {
      ~~~~~~~~~~~~~~~ ^
./src/compiler/php_generator_helpers.h:52:39: error: no member named 'php_namespace' in 'google::protobuf::FileOptions'
    oss << ReplaceAll(file->options().php_namespace(), "\\", "/");
                      ~~~~~~~~~~~~~~~ ^
src/compiler/php_generator.cc:47:23: error: no member named 'has_php_namespace' in 'google::protobuf::FileOptions'
  if (file->options().has_php_namespace()) {
      ~~~~~~~~~~~~~~~ ^
src/compiler/php_generator.cc:48:28: error: no member named 'php_namespace' in 'google::protobuf::FileOptions'
    return file->options().php_namespace();
           ~~~~~~~~~~~~~~~ ^
4 errors generated.
### What did you expect to see?
 
source file should be compiled successfully
### What did you see instead?
make: *** [/Users/jamesguan/workspace/grpc-cpp/objs/opt/src/compiler/php_generator.o] Error 1
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

On another s390x-linux-gnu machine I can build gRPC successfully
g++ -v
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
OS: Ubuntu 16.04.1 LTS (Xenial Xerus)
linux version:
Linux version 4.4.0-97-generic (buildd@z13-011) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #120-Ubuntu SMP Tue Sep 19 17:27:01 UTC 2017

**Comment by jamesgua** [comment]
Solved by compiling protocol buffer from source, on Mac I had an previous installed descriptor.pb.h from protobuf which doesn't have method mentioned above.

**Comment by dr-begemot** [comment]
Can you write more in detail how to solve this problem? Thank you.

**Comment by jamesgua** [comment]
Double checked version of graph, it's 1.6.0, git head info:
ref: refs/heads/v1.6.x``
