### ISSUE TITLE
Multiple python tests on Windows timing out (in 100% cases)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13150]
https://sponge.corp.google.com/target?id=3e5a052a-9fb2-46e9-be2f-6425d19036f9&target=github/grpc/python_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

These test cases are Timing out in 100% cases
```
py35.test.unit.beta._face_interface_test.GenericInvokerFutureInvocationAsynchronousEventServiceTest
py35.test.unit._cython._no_messages_server_completion_queue_per_call_test.Test
```

**Comment by jtattermusch** [comment]
Looks like this was fixed by https://github.com/grpc/grpc/pull/13234.

**Comment by yashykt** [comment]
It's always great to hear that multiple bugs were squashed by a fix :)
