### ISSUE TITLE
php client invoke golang server failed

### ISSUE THREAD

**Issue by songkemail** [grpc/grpc#1316]
I implement a grpc server using golang, everything goes right when I use client written in golang but fail ed to invoke when I use php client.Description:The server had accept the php client's invoke, then the server prompts  "transport: http2Server.HanldeStreams found unhandled frame type [FrameHeader GOAWAY len=25]", the php client prompts "connection refused".
Thank you in advance.

**Comment by iamqizhao** [comment]
Please refer to 
https://github.com/grpc/grpc/blob/master/src/php/tests/interop/interop_client.php
and
https://github.com/grpc/grpc-go/blob/master/interop/server/server.go
to see how php client and go server is written from our own interop tests.

Without more information from you, I can only say the connection is refused by your golang server for some reason.

**Comment by kainosnoema** [comment]
@iamqizhao I'm having the same issue using grpc-go with another client. I believe the go implementation is failing to handle the GOAWAY frame from the client properly ([`http2.FrameGoAway`, sent when the client closes the connection](https://github.com/bradfitz/http2/blob/master/frame.go#L46)). Here's the relevant section where I believe this should be handled: https://github.com/grpc/grpc-go/blob/52ad8d73c4e67571ba810b5fcf677725ae038a80/transport/http2_server.go#L284

**Comment by iamqizhao** [comment]
On Tue, Apr 28, 2015 at 7:42 AM, Evan Owen <notifications@github.com> wrote:

> @iamqizhao <https://github.com/iamqizhao> I'm having the same issue using
> grpc-go with another client. I believe the go implementation is failing to
> handle the GOAWAY frame from the client properly (http2.FrameGoAway, sent
> when the client closes the connection
> <https://github.com/bradfitz/http2/blob/master/frame.go#L46>). Here's the
> relevant section where I believe this should be handled:
> https://github.com/grpc/grpc-go/blob/52ad8d73c4e67571ba810b5fcf677725ae038a80/transport/http2_server.go#L284
>
The go server does not handle GOAWAY now but it does not matter. GOWAY is
sent out from the client when the client wants to close connection from the
client side. So the problem you need to figure out is why your client
wanted to close the connection.

**Comment by kainosnoema** [comment]
The client closing the connection should be a valid and normal operation. The other gRPC server implementations handle this frame correctly, as far as I can tell.

**Comment by iamqizhao** [comment]
On Tue, Apr 28, 2015 at 10:57 AM, Evan Owen <notifications@github.com>
wrote:

> The client closing the connection should be a valid and normal operation.
> The other gRPC server implementations handle this frame correctly, as far
> as I can tell.
>
To be clear, for go server, handling GOAWAY is a TODO. But it does NOT
affect the operations of both client and server.

**Comment by iamqizhao** [comment]
On Tue, Apr 28, 2015 at 11:02 AM, Qi Zhao <toqizhao@gmail.com> wrote:

>
>
> On Tue, Apr 28, 2015 at 10:57 AM, Evan Owen <notifications@github.com>
> wrote:
>
>> The client closing the connection should be a valid and normal operation.
>> The other gRPC server implementations handle this frame correctly, as far
>> as I can tell.
>>
> To be clear, for go server, handling GOAWAY is a TODO. But it does NOT
> affect the operations of both client and server.
>
And you can simply ignore this msg printed by go server.

**Comment by kainosnoema** [comment]
Ah, I see. Thanks for the clarification!

**Comment by stanley-cheung** [comment]
We now have a better interop test runner that shows that all PHP client - Go server interop tests are passing now

```
~/grpc$ MOUNT_ARGS="-v $HOME/.composer/auth.json:/root/.composer/auth.json:ro" tools/run_tests/run_interop_tests.py -l php -s go --use_docker -t -j 8
START: Building interop docker images.
PASSED: build_docker_go [time=10.4sec; retries=0;0]
PASSED: build_docker_php [time=111.7sec; retries=0;0]
SUCCESS: All docker images built successfully.
START: interop_server_go
PASSED: cloud_to_cloud:php:go_server:large_unary [time=11.7sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:cancel_after_begin [time=12.0sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:empty_stream [time=15.5sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:client_streaming [time=15.7sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:server_streaming [time=15.8sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:cancel_after_first_response [time=16.0sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:ping_pong [time=17.2sec; retries=0;0]
PASSED: cloud_to_cloud:php:go_server:empty_unary [time=17.3sec; retries=0;0]
SUCCESS: All tests passed
Removing docker image grpc_interop_go:36bc7a4a-c164-4731-9862-d4c9d197665e
Removing docker image grpc_interop_php:7f0aba03-5c9f-472c-92ce-875ba5be6800
```
