### ISSUE TITLE
grpc c++ / go async 

### ISSUE THREAD

**Issue by yoni386** [grpc/grpc#13171]
Hello,

How grpc async is compared in c++ and go? how scalable grpc is in c++?
 Can you add or explain how async call is mapped to os thread? currently I use go to connect to hounders / thousands  machines via grpc is it possible in c++ if yes then will it better or worse?
Mixing the server / client with grpc different languages is recommended?  for example grpc (c++) and clients will written in grpc (go) or server be in swift or rust (experimental projects).

Thank you,

Yoni

**Comment by vjpai** [comment]
Hi there! Can I suggest that a general usage question like this would be better suited for the grpc-io mailing list than for Github issues? I'd prefer to answer it over there.
