### ISSUE TITLE
Request for Public Key Pinning and TOFU support

### ISSUE THREAD

**Issue by capone212** [grpc/grpc#13181]
### What version of gRPC and what language are you using?
 C++ gRPC v1.6.6
 
### What operating system (Linux, Windows, …) and version?
Linux, Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 MSVC, GCC
 
Current C++ grpc API does not allow to implement public key / certificate pinning on client side.  
OpenSSL has **SSL_CTX_set_verify**  which can be used to implement this. Having such callback would be very nice, because it also can be used to implement another popular concept - TOFU
Please see also my question in https://groups.google.com/forum/#!topic/grpc-io/hzIFN-F9MDE for more detail about TOFU use-case.

**Comment by capone212** [comment]
No client does not have server root public key in advance. 
TOFU works like like ssh-ing to random server in network. At first connect ssh client asks whether you trust this server with this key fingerprint, you have option to add that server to trusted and after that ssh client immune to man in the middle attacks. 

Off course TOFU is not fully secure, security issue at first connect is obvious but for many cases, such as restricted local networks with no Internet it is good trade-off.

**Comment by omalashenko** [comment]
Upvote for this one, seems to be quite useful functionality.

As far as I understand nothing has been done yet, but the intended implementation supposed to break the API. GRPC team, do you have a rough idea of how it needs to be implemented to be accepted in upstream? We are thinking of implementing this ourselves.

Cheers.
