### ISSUE TITLE
grpc_microbenchmark_diff jobs take ~100mins for each run.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13184]
Test suites taking that long is incompatible with seeing PR tests results within a reasonable timeframe (#11690).

What can we do to reduce the runtime for microbenchmarks (e.g. so they take <1hr)?

**Comment by vjpai** [comment]
Bouncing this to @ncteisen

**Comment by ncteisen** [comment]
This one is a balance between time per run and variance per run. We currently run the tests 20 times to eliminate noise from CPU shift. We could try tuning that down, but the output (which is already noisy some days, would get noisier)

**Comment by jtattermusch** [comment]
I get that, but there's of course no way we can make all test results available in <90 (or 60 mins which is our more aggressive goal) if one of the test suites takes longer than that. 
Sharding the job into two might also not be a good idea as we already have so many different jobs for each PR.

How many cores are the microbenchmarks utilizing?

**Comment by ctiller** [comment]
All of them. (the microbenchmarks themselves are ~single threaded, and we
run num_cores concurrently)

**Comment by ctiller** [comment]
If you give them more cores, they will go faster.

I've also had some thoughts about curating what we run per-PR. It might be
time to tackle this soon :)

**Comment by jtattermusch** [comment]
As a side note, once we get more quota for our project, we could switch the microbenchmarks to 64core machines (currently we use 32core machines).
