### ISSUE TITLE
cloud_to_cloud:node:python_server:large_unary and cloud_to_cloud:node:ruby_server:large_unary timeouts

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#13186]
https://sponge.corp.google.com/target?id=fd6e1380-681f-444e-ba90-631ddc1909a9&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

The logs don't say anything even remotely interesting for either test -- just "Timeout".

**Comment by adelez** [comment]
Assigning to Node team since both failures involve the Node client.
Can it also output more helpful information?

**Comment by murgatroid99** [comment]
The core trace output is probably the best bet. If the client docker images were run with the "api" trace variable set, that might help.

**Comment by jtattermusch** [comment]
Dupe of https://github.com/grpc/grpc/issues/13253.
