### ISSUE TITLE
Remaining repos under grpc org need to be switched to Apache 2.0

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13187]
These repos are still on BSD, it would be good to switch everything to Apache2.0 for consistency.

https://github.com/grpc/grpc-contrib
https://github.com/grpc/homebrew-grpc
https://github.com/grpc/grpc-haskell  (this repo is contributed by third party)
https://github.com/grpc/grpc-proto

**Comment by jtattermusch** [comment]
@mehrdada, can you take a look please?

CC @hsaliak @varuntalwar

**Comment by mehrdada** [comment]
These are the PRs. For some reason I can't assign or request reviews for some of them, so I just list them here and leave setting the assignee to someone else:
https://github.com/grpc/grpc-contrib/pull/3
https://github.com/grpc/homebrew-grpc/pull/107
https://github.com/grpc/grpc-haskell/pull/19
https://github.com/grpc/grpc-proto/pull/5

**Comment by jtattermusch** [comment]
@mehrdada  thanks a lot!

**Comment by mehrdada** [comment]
Closing this issue as the final open PR can be tracked there anyway: https://github.com/grpc/grpc-contrib/pull/3
