### ISSUE TITLE
[php] Minimum version of protobuf required is 3.4.0

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#13193]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes. See https://groups.google.com/forum/#!topic/grpc-io/XRWm7xiwgtE 

 
### What version of gRPC and what language are you using?
1.7.x and C++ (The code generator has support for php too) 
 
### What operating system (Linux, Windows, …) and version?
Linux/Windows 
 
Protobuf in 3.4.0 version added has_namepsace_php option. As part of php_generator_helpers.h, grpc uses file->options().has_php_namespace() without guarding it with a protobuf version. This means that starting 1.6.0, the minimum version of protobuf is ends up being 3.4.0. It'd be great if a guard can be added here.

Thanks.

**Comment by stanley-cheung** [comment]
#12820

**Comment by abaldeva** [comment]
The referenced bug is asking to upgrade check to 3.4.0. What I am suggesting is to guard the code changes such that grpc continues to work with versions below 3.4.0. 

If this is not the path you want to take, please provide clear guidelines on compatibility between grpc and protobuf or call out the broken compatibility in release notes. In general, it'd be nice to not have to update protobuf unnecessarily though.

**Comment by ZhouyihaiDing** [comment]
Adding a guard to php_generator_helpers.h needs update everytime when protobuf changes API, and can be complicate later to handle different protobuf version.
We can add a table provides the information about the compatibility version between the grpc and protobuf in readme file for now.

**Comment by ZhouyihaiDing** [comment]
I'll update the compatibility in README alone with the solution to the issue #12481.

**Comment by ZhouyihaiDing** [comment]
I haven't finished updating README yet. I listed [the version relationship in my branch](https://github.com/ZhouyihaiDing/grpc/blob/update_readme_draft/src/php/README.md#protobuf-compiler).

**Comment by ZhouyihaiDing** [comment]
We also need to make some changes when grpc uses Protobuf v3.5.0. Thus let plugin handle different protobuf version will make the code complicate in the future. I think this table can be used as guide to check the compatibility. https://github.com/grpc/grpc.github.io/pull/593/files#diff-eb973ca5c5ad5a35f6b2cfa030dbcdffR172

The PR will be merged soon. Close this issue in advance.
