### ISSUE TITLE
Support IDLE_TIMEOUT (client-side)

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#13212]
[IDLE_TIMEOUT](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md) is defined as a way for clients to drop unused connections after inactivity. This is generally useful, but is particularly valuable on mobile as it can be substantially more battery efficient than enabling keepalive on the channel.

I recently came to the understanding that this is not implemented in C-core. Java has [had support](https://grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-) since 1.0. Note that in Java, when the IDLE_TIMEOUT is reached, the NameResolver and LB are shutdown, returning the Channel to the same state as initially created. This does cause a nomenclature problem, because there are two levels of IDLEness; we've been calling the shutting down of all IO (NR and LB) "idle mode."

The server-side equivalent [is MAX_CONNECTION_IDLE](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md). But both are necessary.

**Comment by hsaliak** [comment]
@AspirinSJL could you please take a look, feel free to prioritize down if necessary.

**Comment by AspirinSJL** [comment]
I though this is solved by https://github.com/grpc/grpc/pull/19727? Please reopen if not.
