### ISSUE TITLE
Performance issues caused by expensive exceptions thrown in RunConnectivityWatcherAsync

### ISSUE THREAD

**Issue by soiferj** [grpc/grpc#13227]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 Version: 1.4.1
Language: C#
 
### What operating system (Linux, Windows, …) and version?
 Windows Server 2016
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET 4.5
 
### Issue
I recently switched to Grpc for routing requests among many machines. Immediately after the switch, I noticed a significant performance degradation. After investigating, I noticed that there was an enormous spike in garbage collection activity in .NET. This seemed to be causing the slowdown. Seeing as the only change in the system was the use of Grpc, I investigated further.

This led to the discovery that there are lots of exceptions being thrown in RunConnectivityWatcherAsync in Channel.cs. On line 312 of this file, RunConnectivityWatcherAsync loops forever, waiting for a state change in the connection. It throws an exception if there is a timeout. This means that even if state is _not_ changed, there will still be an exception thrown. In my case, each machine has persistent connections to many other machines. Since their states are not changing, each machine throws many exceptions per second. Exceptions are expensive, and are leading to the increase in garbage collection.

Are connection states expected to change frequently? If so, then throwing an exception makes sense. Otherwise, this seems like an improper use of an exception that's leading to a large performance penalty. Any guidance here would be greatly appreciated!
 
Thanks a lot!
Jon

**Comment by soiferj** [comment]
Has anyone else experienced this issue?

**Comment by jtattermusch** [comment]
The line you are mentioning should throw 1 exception per second per channel.
https://github.com/grpc/grpc/blob/4cd04b3cd0833e97fc6a65ede8653961a0cf52a3/src/csharp/Grpc.Core/Channel.cs#L312

That doesn't really sound something that should result in a significant performance penalty.

Btw, the RunConnectivityWatcherAsync() method is mean as a temporary workaround for  https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/822 and it should eventually go away.

**Comment by soiferj** [comment]
In our case, this means ~1000 exceptions / second per server. In addition to everything else going on, it seems like that can cause a pretty significant hit.

Is there an ETA for removing RunConnectivityWatcherAsync?

**Comment by jtattermusch** [comment]
Currently there's no clear ETA for removing RunConnectivityWatcherAsync. While I agree this is less than ideal, I still don't think 1000exceptions/s that need to be garbage collected represent a significant overhead.
What I think would help: can you try disabling RunConnectivityWatcherAsync for channels and see if you see significant perf. improvements in your setup? (I suspect you won't).

I currently know about several places in gRPC C#  where we could save on allocations in a more significant way than this issue would (a good example would be https://github.com/grpc/grpc/issues/13236) - so unless we establish a clear link between RunConnectivytWatcherAsync and the performance penalty you are seeing, I think it makes more sense to focus our energy there.

**Comment by jtattermusch** [comment]
Fixed by #13957

**Comment by manigandham** [comment]
We're seeing this too, it's not just the number of exceptions but the fact that exceptions cause an entire stack trace to be dumped which is very expensive. If it was just garbage collection then it wouldn't really be an issue, especially with empty catch blocks. 

A single app is showing about 400 exceptions/sec while only using the datastore API (which is only used once on startup):

![image](https://user-images.githubusercontent.com/457226/35493814-0ddab360-046b-11e8-8fd3-34e1d9ed9aab.png)

**Comment by jtattermusch** [comment]
@manigandham   this has been fixed and there are 1.9.0-pre2 prerelease nugets that contain the fix. Would you mind verifying that the problems you were seeing are gone?
