### ISSUE TITLE
MurmurHash does an unaligned read

### ISSUE THREAD

**Issue by skyostil** [grpc/grpc#13221]
### What version of gRPC and what language are you using?
v1.6.7, C++
 
### What operating system (Linux, Windows, …) and version?
Android 8.0 (arm32)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Android clang version 5.0.300080 from android-ndk-r15c-linux-x86_64.

### What did you do?
Built a small hello world server application.
 
### What did you expect to see?
Hello world
 
### What did you see instead?
A SIGBUS (BUS_ADRALN) in gpr_murmur_hash3 ([murmur_hash.c, line 48](https://github.com/grpc/grpc/blob/master/src/core/lib/support/murmur_hash.cc#L48)):

memcpy(&k1, blocks + i, sizeof(uint32_t));

This is because |blocks| (a uint32_t*) was cast from |key| (void*), which is undefined behavior when |key| isn't 32-bit aligned. With optimizations enabled Clang therefore assumes that |key| is always aligned, when running on ARM it happens to be unaligned and the inlined memcpy crashes:

=> 0xaac5e8e8 <+32>:    ldmia   r6!, {r1}

Stack trace:

#0  gpr_murmur_hash3 () at ../../buildtools/grpc/src/core/lib/support/murmur_hash.c:48
#1  0xaac70894 in grpc_slice_default_hash_impl () at
#2  0xaac70d3e in grpc_slice_intern_init () at ../../buildtools/grpc/src/core/lib/slice/slice_intern.c:292
#3  0xaac5ff62 in grpc_init () at ../../buildtools/grpc/src/core/lib/surface/init.c:121
#4  0xaac9bbf8 in grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) () at ../../buildtools/grpc/include/grpc++/impl/codegen/grpc_library.h:44
#5  0xaac9c166 in CompletionQueue () at ../../buildtools/grpc/include/grpc++/impl/codegen/completion_queue.h:175
#6  0xaac9efd6 in grpc::ServerCompletionQueue::ServerCompletionQueue(grpc_cq_polling_type) ()
    at ../../buildtools/grpc/include/grpc++/impl/codegen/completion_queue.h:288
#7  0xaac9f362 in BuildAndStart () at ../../buildtools/grpc/src/cpp/server/server_builder.cc:258
#8  0xaac5d416 in main () at ../../buildtools/grpc_test.cc:89

(Aside: -fsanitize-alignment fails to catch alignment issues in memcpy -- I'm filing a Clang bug for that.)

**Comment by skyostil** [comment]
The fix is to add a cast to the memcpy:

    memcpy(&k1, (const uint8_t*)(blocks + i), sizeof(uint32_t));

I can put together a pull request tomorrow.

**Comment by AspirinSJL** [comment]
Assigning to @skyostil because he/she already has a solution.

**Comment by camillol** [comment]
This was fixed by PR 13448, and can be closed now.
