### ISSUE TITLE
c++-grpc client get stuck, it seems to get a deadlock.   http://pastebin.com/UcRubwWq

### ISSUE THREAD

**Issue by gamorwang** [grpc/grpc#1323]
code and debug info :  http://pastebin.com/UcRubwWq

**Comment by yang-g** [comment]
The information is not sufficient to find out the exact reason but it seems
the client is waiting for the response. If you are sure the server is
sending something back, maybe you can add a deadline to the ClientContext
and see whether it finishes on time.

**Comment by ctiller** [comment]
Assuming thread pool exhaustion

**Comment by vjpai** [comment]
I agree with Yang that there does not seem to be enough info in this case to assess this properly. If it is thread pool exhaustion, it does not seem to be the same issue as in #2423 , as the stack trace here shown has BlockingUnaryCall as a problem point, not streaming.

**Comment by vjpai** [comment]
@gamorwang , are you still interested in the solution to this problem? If so, please add to this issue and we can help with the debugging. If it is thread-pool exhaustion, the recent addition of the dynamic thread-pool should help.

**Comment by vjpai** [comment]
I haven't gotten any additional information to address this issue, so I'd like to close this issue. Please feel free to reopen if you want to add any information for debugging. Thanks!
