### ISSUE TITLE
[Node.js] gRPC Map<string, string> Results in Empty Object

### ISSUE THREAD

**Issue by chrisalexander55** [grpc/grpc#13248]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
 "grpc": "^1.6.6",
 
### What operating system (Linux, Windows, …) and version?
 OSX, Sierra
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
 
### What did you do?
Client reads a Msg protobuf type definition from server. No errors but Msg#map produces an empty {}, not an array of key:value pairs.

```
.proto
message Msg {
  int32 code = 1;
  string text = 2;
  map<string, string> data = 3;
}
```

Client code:
```
const map = new Map<string, string>();
if (addr.addr == undefined) return Utils.buildMsg(-1, "Addr.addr", map.set("", "An email address is required."));
```

Server code:
```
this._client.add(gRpcAddrMsg, (err: any, result: any) => {
          if (err) {
            console.log(err);
            reject(err);
            return;
          }
          else {
            console.log(result);
            resolve(this.addAddr_gRpc_To_Type(result));
          }
        });

private addAddr_gRpc_To_Type(gRpcMsg: any): AddressEntry|Msg {
    if (gRpcMsg.msg != undefined) {
      const msg: Msg = new Msg();
      msg.code = (gRpcMsg.msg.code != undefined) ? gRpcMsg.msg.code : undefined;
      msg.text = (gRpcMsg.msg.text != undefined) ? gRpcMsg.msg.text : undefined;
      msg.data = (gRpcMsg.msg.data != undefined) ? gRpcMsg.msg.data : undefined;
      return msg;
    }
    ...
}
```
### What did you expect to see?
 `gRpcMsg.msg.data` should be `Map` containing `"", "An email address is required."`
 
### What did you see instead?
`gRpcMsg.msg.data = {}` This happens regardless how many key:value pair populate map.
Here is the JSON returned, reflecting the empty map

```
{
    "code": -100,
    "text": "Addr.addr",
    "data": {}
}
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
None
 
### Anything else we should know about your project / environment?
None

**Comment by nicolasnoble** [comment]
Updated formatting.

**Comment by chrisalexander55** [comment]
This is a cryptic response. What do you mean by updated formatting?
