### ISSUE TITLE
Allow passing service name to client stubs for dynamic mapping

### ISSUE THREAD

**Issue by derolf** [grpc/grpc#13245]
Currently, all client stubs statically include the service name, e.g. the c++ stubs generated by protoc.

It would be a simple change to allow passing a service name to a stub.

This way, gRPC would enable pseudo-polymorphism, dynamic capabilities and dependency injection.

**Comment by a11r** [comment]
We already support generic stubs .

**Comment by derolf** [comment]
And you think that is enough? I could also do a raw HTTP/2 call or Morse code.
