### ISSUE TITLE
Error "[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: google/protobuf/descriptor.proto" when I cross compile helloworld

### ISSUE THREAD

**Issue by suhacen** [grpc/grpc#13249]
I add grpc and protobuf to my yocto project, they are compiled fine, and I also add the helloworld demo under examples/cpp/ to the yotcto build, but when I run  greeter_server and greeter_client on my board,  there is an error:

`
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: google/protobuf/descriptor.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1394] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
Aborted (core dumped)
`

I can't really understand what is the meaning of this error.

I google a little bit, people said compile grpc and helloworld  statically would fix this issue, so I add try to build the code statically, but it doesn't solve the problem.

Maybe someone can give me hints so I can move forward. 

Thanks!
J.S.

Here is my recipe for grpc:
`DESCRIPTION = "An RPC library and framework"
AUTHOR = "Google Inc."
HOMEPAGE = "http://www.grpc.io"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"

inherit autotools-brokensep pkgconfig

DEPENDS = "\
	protobuf \
	zlib \
	openssl \
	c-ares \
"

SRC_URI = "gitsm://github.com/grpc/grpc.git;protocol=http;branch=v1.6.x"
SRCREV = "3747ce3803b13fa3273523cf71f51c93239f9363"

PR = "r0"

S = "${WORKDIR}/git"

#Fix static library generation
#AR += "rcs"
CXXFLAGS += " -std=c++11 -static"
OUTDIR = "${S}/libs/opt/"

do_compile () {
    export GRPC_CROSS_COMPILE=true
    export GRPC_CROSS_AROPTS="crs --target=elf32-littlearm"
    export PROTOBUF_CONFIG_OPTS="--host=arm-poky-linux-gnueabi --with-protoc=/usr/local/bin/protoc"
    export HAS_PKG_CONFIG=false
	export HAS_SYSTEM_PROTOBUF=false
    export LDXX="${CXX}"
    export LD="${CC}"
    export AR="${AR}"
    export RANLIB="${RANLIB}"		
    #oe_runmake clean
    oe_runmake plugins
    oe_runmake prefix=${exec_prefix} shared static PROTOC_PLUGINS_DIR="/usr/local/bin"
}

do_install () {
	oe_runmake prefix=${D}${exec_prefix} install-headers

	#oe_libinstall -C ${OUTDIR} -so -a libgpr ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc_cronet ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc_unsecure ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc++ ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc++_cronet ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc++_error_details ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc++_reflection ${D}${libdir}
	#oe_libinstall -C ${OUTDIR} -so -a libgrpc++_unsecure ${D}${libdir}
	
	oe_libinstall -C ${OUTDIR} -a libgpr ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc_cronet ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc_unsecure ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc++ ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc++_cronet ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc++_error_details ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc++_reflection ${D}${libdir}
	oe_libinstall -C ${OUTDIR} -a libgrpc++_unsecure ${D}${libdir}

	install -d ${D}${libdir}/pkgconfig
	install -m 0644 ${OUTDIR}/pkgconfig/*.pc ${D}${libdir}/pkgconfig/
}

INSANE_SKIP_${PN} = "already-stripped rpaths"
`

And here is my Makefile for helloworld:
`
HOST_SYSTEM = $(shell uname | cut -f 1 -d_)
SYSTEM ?= $(HOST_SYSTEM)
#CXX = g++
CPPFLAGS += `pkg-config --cflags protobuf grpc grpc++` -static -pthread
CXXFLAGS += -std=c++11
ifeq ($(SYSTEM),Darwin)
LDFLAGS += -L/usr/local/lib `pkg-config --libs protobuf grpc++ grpc`\
           -lgrpc++_reflection\
           -ldl
else
LDFLAGS += `pkg-config --libs protobuf grpc++ grpc`\
           -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed\
           -ldl -lgrpc -lgrpc++ -lprotobuf -lpthread
endif

PROTOC = protoc
GRPC_CPP_PLUGIN = grpc_cpp_plugin
GRPC_CPP_PLUGIN_PATH ?= `which $(GRPC_CPP_PLUGIN)`

PROTOS_PATH = ./protos

vpath %.proto $(PROTOS_PATH)

all: system-check greeter_client greeter_server greeter_async_client greeter_async_client2 greeter_async_server

greeter_client: helloworld.pb.o helloworld.grpc.pb.o greeter_client.o
	$(CXX) $^ $(LDFLAGS) -o $@

greeter_server: helloworld.pb.o helloworld.grpc.pb.o greeter_server.o
	$(CXX) $^ $(LDFLAGS) -o $@

greeter_async_client: helloworld.pb.o helloworld.grpc.pb.o greeter_async_client.o
	$(CXX) $^ $(LDFLAGS) -o $@

greeter_async_client2: helloworld.pb.o helloworld.grpc.pb.o greeter_async_client2.o
	$(CXX) $^ $(LDFLAGS) -o $@

greeter_async_server: helloworld.pb.o helloworld.grpc.pb.o greeter_async_server.o
	$(CXX) $^ $(LDFLAGS) -o $@

.PRECIOUS: %.grpc.pb.cc
%.grpc.pb.cc: %.proto
	$(PROTOC) -I $(PROTOS_PATH) --grpc_out=. --plugin=protoc-gen-grpc=$(GRPC_CPP_PLUGIN_PATH) $<

.PRECIOUS: %.pb.cc
%.pb.cc: %.proto
	$(PROTOC) -I $(PROTOS_PATH) --cpp_out=. $<

clean:
	rm -f *.o *.pb.cc *.pb.h greeter_client greeter_server greeter_async_client greeter_async_client2 greeter_async_server

#The following is to test your system and ensure a smoother experience.
#They are by no means necessary to actually compile a grpc-enabled software.

PROTOC_CMD = which $(PROTOC)
PROTOC_CHECK_CMD = $(PROTOC) --version | grep -q libprotoc.3
PLUGIN_CHECK_CMD = which $(GRPC_CPP_PLUGIN)
HAS_PROTOC = $(shell $(PROTOC_CMD) > /dev/null && echo true || echo false)
ifeq ($(HAS_PROTOC),true)
HAS_VALID_PROTOC = $(shell $(PROTOC_CHECK_CMD) 2> /dev/null && echo true || echo false)
endif
HAS_PLUGIN = $(shell $(PLUGIN_CHECK_CMD) > /dev/null && echo true || echo false)

SYSTEM_OK = false
ifeq ($(HAS_VALID_PROTOC),true)
ifeq ($(HAS_PLUGIN),true)
SYSTEM_OK = true
endif
endif

system-check:
ifneq ($(HAS_VALID_PROTOC),true)
	@echo " DEPENDENCY ERROR"
	@echo
	@echo "You don't have protoc 3.0.0 installed in your path."
	@echo "Please install Google protocol buffers 3.0.0 and its compiler."
	@echo "You can find it here:"
	@echo
	@echo "   https://github.com/google/protobuf/releases/tag/v3.0.0"
	@echo
	@echo "Here is what I get when trying to evaluate your version of protoc:"
	@echo
	-$(PROTOC) --version
	@echo
	@echo
endif
ifneq ($(HAS_PLUGIN),true)
	@echo " DEPENDENCY ERROR"
	@echo
	@echo "You don't have the grpc c++ protobuf plugin installed in your path."
	@echo "Please install grpc. You can find it here:"
	@echo
	@echo "   https://github.com/grpc/grpc"
	@echo
	@echo "Here is what I get when trying to detect if you have the plugin:"
	@echo
	-which $(GRPC_CPP_PLUGIN)
	@echo
	@echo
endif
ifneq ($(SYSTEM_OK),true)
	@false
endif`

**Comment by suhacen** [comment]
don't know why, but when I remove "-lgrpc++_reflection" from the demo Makefile, it works.

**Comment by huweiBuct** [comment]
["protobuf"]="cd 'BASE_DIR/3rd-party/'; \
tar zxvf 'protobuf-all-3.6.1.tar.gz'; \
cd 'protobuf-3.6.1'; \
./autogen.sh; \
./configure -disable-shared CFLAGS='-fPIC' CXXFLAGS='-fPIC' --host=ARCH_ID CC=ARCH_GCC CXX=ARCH_GXX --prefix='BASE_DIR/3rd-party/OS_ARCH/protobuf' --with-protoc=BASE_DIR/3rd-party/linux-x86_64/protobuf/bin/protoc CPPFLAGS='-D_XOPEN_SOURCE=500'; \
make -jPROCESSOR_NUM; \
make install; \
make clean;"
