### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by adamdaugherty** [grpc/grpc#13241]
I have been trying unsuccessfully to install the node grpc library on CentOS Linux release 7.4.1708 (Core), using node v8.9.0 and npm v5.5.1. Attempting to `npm install grpc` so results in:

```
# npm install grpc

> grpc@1.7.0 install /root/api-testing/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

sh: node-pre-gyp: command not found
npm WARN api-testing No description
npm WARN api-testing No repository field.
npm WARN api-testing No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! grpc@1.7.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the grpc@1.7.0 install script.

```

To attempt to resolve the problem, I've tried both pre-installing `node-pre-gyp` manually, to ensure that it was available in `node_modules/.bin`, and ensuring that npm was finding it by making a script that ran `node-pre-gyp --help` it in my `package.json`, which worked as expected.

I've also tried manually pre-installing `node-pre-gyp` globally, which resulted in:

```
# npm install grpc

> grpc@1.7.0 install /root/api-testing/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.0/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.0 and node@8.9.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/api-testing/node_modules/grpc/.node-gyp/8.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/api-testing/node_modules/grpc/.node-gyp"
```

where the warnings repeat ad infinitum.

In case it is diagnostically relevant, I am able to manually download without issue `https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.0/node-v57-linux-x64.tar.gz` from the machine where I'm having the problem. I've also tried `clean`ing and `verify`ing the npm cache, as well as removing it manually, but nothing seems to make a difference.

I'm not sure how to proceed.

**Comment by murgatroid99** [comment]
This is bizarre. The package `node-pre-gyp` is bundled with grpc specifically to avoid the first problem you're encountering. The download failure indicates to me that something else is going wrong, though. You mention that you can download the file manually, which means that the failure is not network related, so it must be somehow caused by your local machine. Unfortunately, it's not outputting any useful information about the error, which is probably a bug in node-pre-gyp.

**Comment by adamdaugherty** [comment]
The `sh: node-pre-gyp: command not found` makes me suspect that you're right in that the problem is on the `node-pre-gyp` side.

After noodling with it a bit, I was able to get `grpc` to successfully install (I think, anyway - I haven't actually tested anything with it yet, but it's not falling over in an obvious way anymore). **It is a hacky, terrible long-term solution for a variety of reasons that should not be used by anyone.** I'm only including it here in case it's diagnostically useful.

My `package.json` looks like:

```
{
  "dependencies": {
    "grpc": "^1.7.0",
    "node-pre-gyp": "^0.6.39"
  },
  "scripts": {
    "screaming": "cd node_modules/grpc && node-pre-gyp install --fallback-to-build --library=static_library"
  }
}
```

Running `npm install --ignore-scripts` will install `grpc` without executing the problematic `install` lifecycle hook. After the install, `npm run screaming` will fire up `node-pre-gyp` in the expected way, which seems to succeed:

```
# npm run screaming

> @ screaming /root/api-testing
> cd node_modules/grpc && node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/root/api-testing/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64/grpc_node.node" is installed via remote
```

I am assuming that's the expected happy behavior.

**Comment by murgatroid99** [comment]
That is the expected behavior. Have you tried having that script there without having your own explicit dependency on `node-pre-gyp`? I suspect that that script is running the copy of `node-pre-gyp` bundled with grpc anyway. It seems bizarre that that script would work, but the nearly identical install script wouldn't work. That makes me think that npm is doing something weird during the installation.

Also, I want to note that I think the primary issue with `node-pre-gyp` here is missing error information. The original error you reported happened before any `node-pre-gyp` code even started executing.

**Comment by adamdaugherty** [comment]
My mistake, I thought the `sh: ...` line was being emitted by `node-pre-gyp`, not npm. After testing with a local dummy library with a busted post-install script, I see that that's normal output for npm under that condition. The output is different with a broken script in the current module's scripts, which is why I was confused.

If the `node-pre-gyp` dependency is removed and `npm run screaming` is executed, then the install fails and gives the same output as the first case mentioned above. This makes sense, since the `screaming` npm script is running in the npm context of my app (with my app's `node_modules/.bin` in its path), not the context of the `node_modules/grpc` directory (`node_modules/grpc/.bin`), even though it's being used as the cwd.

To do what you suggest, if I remove the `node-pre-gyp` dependency and change `screaming` to be `cd node_modules/grpc && npm run install`, installation succeeds when I run it the same way (first `npm install --ignore-scripts` and then `npm run screaming`).
