### ISSUE TITLE
Fail to build c# interop test docker image

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#13278]
https://sponge.corp.google.com/target?id=cecb8edb-1282-4f8a-a82a-33feb17cf208&target=grpc%2Fubuntu%2Fmaster%2Fgrpc_interop_toprod&searchFor=

"Unable to load the service index for source https://api.nuget.org/v3/index.json"

**Comment by adelez** [comment]
@matt-kwong

**Comment by jtattermusch** [comment]
I think it was a transient issue (looks like https://api.nuget.org/v3/index.json wasn't available, now it works).
In following builds the C# builds has passed without a problem:
https://sponge.corp.google.com/invocation?tab=Kokoro&id=c30e26f0-801e-48e9-aa86-3423d2f2bfc2&searchFor=
https://sponge.corp.google.com/invocation?id=d23213e0-f566-4570-b0cd-3675df77b24a&searchFor=
