### ISSUE TITLE
gprc_php_plugin - Incorrect handling for google.protobuf.Empty

### ISSUE THREAD

**Issue by idcmp** [grpc/grpc#13285]
* libprotoc 3.4.0 (built from master)
* grpc_php_plugin (built from master, using protobuf built above)

My example proto, living in `/project/example.proto`:

```syntax = "proto3";
package example;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

service Example {
  rpc Example(google.protobuf.Empty) returns (ExampleResponse) {
    option (google.api.http) = {
      get: "/testing"
    };
  }
}

message ExampleResponse {
  string body = 1;
}
```

Then run (season -I's and plugin path to taste):

```
protoc --grpc_out="target/src" \
                -I ~/protobuf/src \ 
                -I /project \
                --plugin=protoc-gen-grpc=/usr/bin/grpc_php_plugin \
                --php_out="target/src" \
                /project/example.proto
```

Generates ExampleClient.php:

```
     * @param \Google\Protobuf\Empty $argument input argument
     * @param array $metadata metadata
     * @param array $options call options
     */
    public function Example(\Google\Protobuf\Empty $argument,
```

This should be `\Google\Protobuf\GPBEmpty`, shouldn't it?

**Comment by ZhouyihaiDing** [comment]
I think `\Google\Protobuf\Empty` is supposed to be the right output here, and it's because that Empty hasn't been reserved in protoc v3.4.0.
@stanley-cheung , can this explain it?

**Comment by ZhouyihaiDing** [comment]
#12611

**Comment by fengli79** [comment]
I don't think we should make a copy. Instead, we should be able to reuse the protobuf PHP naming convention.
https://github.com/google/protobuf/blob/a632f0dbac406227fad0951262f3b6160eaabebe/src/google/protobuf/compiler/php/php_generator.cc#L110

@teboring
@pherl

**Comment by ZhouyihaiDing** [comment]
It there an API to check reserved variable names in plugin?
It seems [php_generate.cc](https://github.com/google/protobuf/blob/a632f0dbac406227fad0951262f3b6160eaabebe/src/google/protobuf/compiler/php/php_generator.cc#L52) in protobuf repo is also copying an array of it.

**Comment by TeBoring** [comment]
Currently, there is no public API to tell the correct php proto message name.
I can add a util method to do that in google/protobuf/compiler/php/php_helper.h.
Does that work for grpc?

**Comment by TeBoring** [comment]
One concern is: does grpc link any protobuf library now?

**Comment by ZhouyihaiDing** [comment]
I think plugin link to the protobuf @TeBoring :
```
ldd -v grpc_php_plugin 
	linux-vdso.so.1 =>  (0x00007ffe4f7c2000)
	libprotoc.so.14 => /usr/local/lib/libprotoc.so.14 (0x00007f08f011a000)
	libprotobuf.so.14 => /usr/local/lib/libprotobuf.so.14 (0x00007f08efca2000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f08ef99e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08ef5d5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f08ef3b7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f08ef1a1000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f08eef88000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f08f058e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f08eec82000)
```

**Comment by ZhouyihaiDing** [comment]
Seems in protobuf v3.4.0, there are only [3 reserved names](https://github.com/google/protobuf/blob/v3.4.0/src/google/protobuf/compiler/php/php_generator.cc#L52).
Copy the step processing the class name from it and create a short term solution in PR #13312

There will be new API in [protobuf v3.5.0](https://github.com/google/protobuf/pull/3850). Thanks @TeBoring . We will use it when grpc start using protobuf v3.5.0.

**Comment by wangming1993** [comment]
+1
