### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [grpc/grpc#13291]
Based on https://github.com/grpc/grpc/releases and https://github.com/grpc/grpc/releases/latest I cannot tell if 1.7.0 or 1.7.1 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by apolcyn** [comment]
1.7.1 and 1.7.2 are patch releases only for the C# and Ruby grpc libraries, which contain bug fixes (and one ruby dependency update) for only C# and Ruby.

For all other grpc C-based languages (the libraries that live in this repo), I believe 1.7.0 is the latest stable version (note that the the 1.7.x branch on this repo is at version 1.7.2 only for the latest ruby release).
