### ISSUE TITLE
php: grpc 1.7.0 release not on packagist

### ISSUE THREAD

**Issue by marcelcorso** [grpc/grpc#13292]
The 1.7.0 release is missing from https://packagist.org/packages/grpc/grpc. 

We ran into this issue when we upgraded the go and java implementations but could not update the php one. 

I noticed that on pecl https://pecl.php.net/package/gRPC 1.7.0 is still a release candidate. Maybe we just got confused what version we could use by just looking at the releases page on github.

**Comment by stanley-cheung** [comment]
1.7.0 is released on PECL, sorry for the delay
