### ISSUE TITLE
Artifact Build Linux Fails

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#13302]
I can see the failure at https://github.com/grpc/grpc/pull/13145
Sponge Link to Failure  [https://sponge.corp.google.com/target?id=5dc86063-8fde-48a0-a114-34a2827741e8&target=grpc/ubuntu/pull_request/grpc_build_artifacts&searchFor=&show=ALL&sortBy=STATUS](url)

Build artifacts broken 
build_artifact.csharp_ext_linux_x86
build_artifact.csharp_ext_linux_x64
build_artifact.php_pecl_package_linux_x64

**Comment by ZhouyihaiDing** [comment]
The link above is not working. Here is the failure from a random PR:
https://sponge.corp.google.com/target?id=43bddd79-67d2-4077-80a7-1cf335d1e2ce&target=grpc/ubuntu/pull_request/grpc_build_artifacts&searchFor=&show=ALL&sortBy=STATUS

**Comment by ZhouyihaiDing** [comment]
```
+ DOCKER_IMAGE_NAME=grpctesting/grpc_artifact_linux_x86_
+ docker pull grpctesting/grpc_artifact_linux_x86_
invalid reference format
```
Docker file in grpctesting/grpc_artifact_linux_x86_ is removed by #13145

**Comment by jtattermusch** [comment]
Yes, we should the artifact dockerfiles back, they were probably removed by mistake.
tools/dockerfile/grpc_artifact_linux_x64/Dockerfile
tools/dockerfile/grpc_artifact_linux_x86/Dockerfile
