### ISSUE TITLE
Escape argument/attribute name collides Python reserved keyword

### ISSUE THREAD

**Issue by iwaseyusuke** [grpc/grpc#13318]
Version of gRPC and language: protoc and Python plugin
```
$ protoc --version
libprotoc 3.4.0
$ pip show grpcio
Name: grpcio
Version: 1.7.0
...(snip)...
 $ pip show grpcio-tools
Name: grpcio-tools
Version: 1.7.0
...(snip)...
```

OS: Linux Ubuntu 16.04 LTS
 
Runtime and compiler:
 ```bash
$ python --version
Python 3.5.2
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 ```

I'm trying to send a message from gRPC client written in Python and the message is like:
```protobuf
message TestMessage {
  bool global = 1;
  uint32 as = 2;
}
```

The gRPC server is written in Go, `global` and `as` does not collides the reserved keywords, but on Python, these variable name clash with reserved keywords.
Then, I couldn't create the above message with keyword arguments and couldn't access these attributes:

```python
# couldn't create message with keyword arguments
msg = xxx_pb2.TestMessage(
    global=True,  # Here raises syntax error
    as=100,
)
# required to pass arguments like
kwargs = {
    'global': True,
    'as': 100,
}
msg= xxx_pb2.TestMessage(**kwargs)

# Also couldn't access these attributes
print(msg.global)  # Here raises syntax error
# required to use getattr() like
print(getattr(msg, 'global'))
```

### Request

[pep8](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments) says "If a function argument's name clashes with a reserved keyword, it is generally better to append a single trailing underscore", so I want to pass arguments appending "_" like:
```python
msg = xxx_pb2.TestMessage(
    global_=True,
    as_=100,
)
```
and also access attribute like:
```python
print(msg.global_)
```

What do think about it? Does anyone know better workaround?

**Comment by mehrdada** [comment]
This issue should be resolved in Protocol Buffers compiler first and based on their resolution, we can go ahead and make a corresponding fix to gRPC Python protobuf plugins if needed. If you could please file a bug on `google/protobuf` repo and ping us here when that gets resolved that would be great. Thanks!

**Comment by mehrdada** [comment]
(I am closing this issue at this point, as I am not sure there is anything on gRPC side to be done if `protobuf` makes a fix on its side, but feel free to ping us to reopen if the underlying cause was fixed on `protobuf` and there was still changes needed on gRPC Python plugin side.)

**Comment by nathanielmanistaatgoogle** [comment]
I think this is more of a [Protocol Buffers](https://github.com/google/protobuf) question than a gRPC question.

@xfxyjwf, @anandolee: any thoughts?

**Comment by iwaseyusuke** [comment]
Thank you for your reply!
Sure, I will search if there is the similar issue on protobuf side and create a new one if needed.
