### ISSUE TITLE
thread_stress_test flaky (Linux dbg and opt)

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13330]
```
[ RUN      ] AsyncClientEnd2endTest/0.ThreadStress
D1108 17:22:51.526708000 140735181389824 ev_posix.cc:135]              Using polling engine: poll
D1108 17:22:51.526754000 140735181389824 dns_resolver.cc:307]          Using native dns resolver
I1108 17:22:51.529232000 140735181389824 server_builder.cc:269]        Synchronous server. Num CQs: 8, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
libc++abi.dylib: libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailableterminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailableterminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable


libc++abi.dylib: libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailableterminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailableterminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi.dylib: libc++abi.dylib: 

terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailableterminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
```

**Comment by dgquintas** [comment]
Seen again: https://sponge.corp.google.com/target?id=15cc1ab7-bc2c-46be-a909-e874af69638f&target=github/grpc/c%2B%2B_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

@vjpai any idea how we could deal with this?

**Comment by dgquintas** [comment]
Again: https://sponge.corp.google.com/target?id=96b4507d-db04-4f5f-b150-4284dd51ba57&target=github/grpc/c%2B%2B_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by dgquintas** [comment]
It seems to be happening consistently now: https://sponge.corp.google.com/target?id=3a35381a-015b-4a11-92e3-7f0b590b6a82&target=github/grpc/c%2B%2B_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
Still happening for `bins/opt/thread_stress_test --gtest_filter=AsyncClientEnd2endTest/0.ThreadStress GRPC_POLL_STRATEGY=poll` on Mac.

**Comment by jtattermusch** [comment]
Bumping to P1.   @vjpai  do you have cycles to actively investigate this or should be reassign?

**Comment by vjpai** [comment]
Since we are allergic to exceptions, I propose that we stop using std::thread in the C++ library. We should be using gpr_thread so that we can at least clean it up and return resources_exhausted.

**Comment by vjpai** [comment]
Still working on the sync server refactor that should help here

**Comment by jtattermusch** [comment]
This also seems to be flaky with tsan and asan, as well as on linux dbg and opt.

**Comment by jtattermusch** [comment]
This is now only happening on linux and with much lower frequency:

https://sponge.corp.google.com/target?id=ef6c1968-6021-4e12-beae-4e0d301a4d5c&target=github/grpc/c%2B%2B_linux_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
Duplicate of https://github.com/grpc/grpc/issues/13148.
