### ISSUE TITLE
enum type not serializing

### ISSUE THREAD

**Issue by IDIHTD** [grpc/grpc#13345]
i work with c# ,i want to replace wfc with grpc ,and i wote an demo,there is an questioin,the enum type not serializing,it bother me,code like this:
helloRequest.SingleMaHuiEntity = new MaHuiMessage()
            {
                Ma1 = "ma1",
                Ma2 = 32,
                Single2Enum = MaHuiMessage.Types.ma2Enum.Ma2Item1,
               
                SingleEnum = MaHuiMessage.Types.ma1Enum.Ma1Item1
            };
 var actualText = JsonFormatter.Default.Format(helloRequest);

the Single2Enum and SingleEnum are enum type, the actualText not show,i think they not sucessful serialized

**Comment by jtattermusch** [comment]
This looks like a protobuf issue, not grpc. Also, I'm not sure I understand what the problem is.
