### ISSUE TITLE
Flake: cmake/build/Release/concurrent_connectivity_test.exe times out

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#13352]
```
Timeout
D1108 22:19:32.048000000  3944 test_config.cc:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1108 22:19:32.048000000  3944 dns_resolver.cc:307] Using native dns resolver
D1108 22:19:32.048000000  3944 concurrent_connectivity_test.cc:179] Wave 1
I1108 22:19:33.095000000  5616 subchannel.cc:683] Connect failed: {"created":"@1510208373.095000000","description":"OS Error","file":"T:\src\github\grpc\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.cc","file_line":106,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
D1108 22:19:33.501000000  3944 concurrent_connectivity_test.cc:189] Wave 2
```

https://sponge.corp.google.com/target?id=6e3c6569-a4a5-44a0-a35c-0030fda857f8&target=github/grpc/c_windows_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
I am still seeing this on Windows (both Debug and Release).
There are other concurrent_connnectivity_test failures on other platforms that might be related  but not necessarily the same: https://github.com/grpc/grpc/issues/13125

**Comment by jtattermusch** [comment]
I'm unable to reproduce it on my desktop, but I'm able to reproduce on a Kokoro VM (it doesn't happen very often though). Still looking.

**Comment by jtattermusch** [comment]
Based on historic data, we haven't seen this since Nov 30 2017.
