### ISSUE TITLE
Unexpected end of input in tools/run_tests/helper_scripts/run_grpc-node.sh 

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#13353]
SyntaxError: /var/local/git/grpc-node/packages/grpc-native-core/package.json: Unexpected end of input

https://sponge.corp.google.com/target?id=18279676-46a4-4256-9f8f-6f18d4afdab9&target=github/grpc/grpc-node_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

https://sponge.corp.google.com/target?id=18279676-46a4-4256-9f8f-6f18d4afdab9&target=github/grpc/grpc-node_linux_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by murgatroid99** [comment]
This should be fixed by #13433.
