### ISSUE TITLE
Question: Is there a plan to support qos in grpc?

### ISSUE THREAD

**Issue by ohade** [grpc/grpc#13355]
I previously worked with a system similar to grpc - DDS from rti - and one of their strongest features - for me - is QOS, when a client disconnect for some reason and reconnect he gets the message he missed.
You can control the window of message he lost and other features around that.
Is it something that grpc supports now? or thinking about supporting in the future?
Thanks

**Comment by a11r** [comment]
This would be explicitly out of scope for gRPC.
