### ISSUE TITLE
JWT with nbf = 0 considered as BAD_FORMAT

### ISSUE THREAD

**Issue by lizan** [grpc/grpc#13360]
More context: https://github.com/cloudendpoints/esp/issues/308

The [JWT verifier](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/jwt/jwt_verifier.cc#L270) considers 0 as invalid value, but some JWT issuer (Keycloak) include nbf=0 as claims.

**Comment by tsoontornwutikul** [comment]
This issue is still valid for us; as far as I know, the JSON Web Token standard does not consider the nbf value of 0 to be invalid.
