### ISSUE TITLE
Python generator - Tried to insert into file that doesn't exist.

### ISSUE THREAD

**Issue by magick93** [grpc/grpc#13362]
### Should this be an issue in the gRPC issue tracker?

I assume so - but surely the owners of this issue tracker can answer that better than I can.
 
 
### What version of gRPC and what language are you using?
 I have tried with the following versions:

[NOT WORKING] - 1.6.1 - See https://github.com/hughestech/docker-protobuf/blob/1.6.1/Dockerfile#L4
[NOT WORKING] - 1.6.6 - https://github.com/hughestech/docker-protobuf/blob/1.6.6/Dockerfile#L4 with both  Python 2.7 and  Python 3.6
[WORKING] - 1.7.2 - See https://github.com/hughestech/docker-protobuf/blob/1.7.2/Dockerfile#L4
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 17.10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7 and  Python 3.6
 
### What did you do?
Specifically, I run the following bash script:

```
 declare -a svc=(
 "MyServiceOne.proto"
 "MyServiceTwo.proto"
	)


DP_VERSION=1.6.6
echo "pulling latest version of $DP_VERSION"
docker pull hughestech/docker-protobuf:$DP_VERSION





for i in "${svc[@]}"
do
   echo "generating service for $i"
   docker run --rm -v $(pwd):$(pwd) -w $(pwd) hughestech/docker-protobuf:$DP_VERSION --grpc_out=./src/grpc --plugin=protoc-gen-grpc=/usr/bin/grpc_python_plugin -I./my-protos/ ./my-protos/$i

done
```
 
### What did you expect to see?
 
 I expected the command to complete without errors.

### What did you see instead?
 
```
generating service for MyServiceTwo.proto
MyServiceTwo_pb2.py: Tried to insert into file that doesn't exist.

```

**Comment by mehrdada** [comment]
Do you see the issue if you use the officially supported method for compiling `.proto` files into `_pb2`s for gRPC Python with `grpcio-tools` package (cf. https://grpc.io/docs/tutorials/basic/python.html; the example command line "```python -m grpc_tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/route_guide.proto```")

**Comment by magick93** [comment]
No, when I try that I get `Unknown flag: -m` and nothing is generated.

**Comment by mehrdada** [comment]
That's interesting! `python` seems to have a `-m` flag everywhere. Is your `python` executable wrapped or something?

**Comment by nathanielmanistaatgoogle** [comment]
I _strongly_ suspect that the problem here is the combination of
* an earlier-than-1.7.0 gRPC Python,
* the lack of the `grpc_2_0` flag passed in the `grpc_python_out` value, and
* the lack of passing the --python_out flag.

I think you should upgrade to gRPC Python 1.7.0 or later which by default allows generation of `_pb2_grpc.py` files without also requiring generation of `_pb2.py` files in the same command.

**Comment by muxi** [comment]
To close due to no update
