### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")

### ISSUE THREAD

**Issue by beckjin** [grpc/grpc#13378]
The service does not automatically connect, free after a period of time, the first call will appear the following error, next to normal.

The program is based on.Net Framework, The Grpc.Core version is 1.4.1.

```
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   在 Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   在 Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   在 Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
```

**Comment by beckjin** [comment]
The document says I can try again. Isn't this supposed to be implemented internally in grpc.core?

![image](https://user-images.githubusercontent.com/7261408/32764004-33f4e556-c93e-11e7-8f26-cd2e6b0eee23.png)

**Comment by Leowuqunqun** [comment]
Me too , Can anyone answer that? @hassox @beccca @timburks @haberman

**Comment by yashykt** [comment]
I did not quite understand what you are trying to achieve? Please provide more details on what you did, what you expected to see and what actually happened.

**Comment by jtattermusch** [comment]
This issue looks stale and it is not clear what the intent was. Also 1.4.1 is pretty old, feel free to try with 1.12.0 and if you are still seeing a problem, file this as a new issue.
