### ISSUE TITLE
Not compiled grpc on solaris

### ISSUE THREAD

**Issue by usebaz** [grpc/grpc#13383]
### What version of gRPC and what language are you using?
 
`npm i grpc@1.7.1`
 
### What operating system (Linux, Windows, …) and version?
 
`SunOS hostname 5.11 11.3 i86pc i386 i86pc Solaris`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
`gcc version 4.8.2 (GCC)` 

### What did you do?

Try install grpc v1.7.1 in mys dev system/
 
### What did you expect to see?
 
 Success installed node.js module 

### What did you see instead?
 
```
npm ERR! SunOS 5.11
npm ERR! argv "/usr/node/bin/node" "/usr/node/bin/npm" "i" "grpc"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.7.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.7.1 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/services/billing/npm-debug.log
```
 
### Anything else we should know about your project / environment?

All command logs: http://sprunge.us/PYSY
npm-debug.log: http://sprunge.us/KHSa

**Comment by usebaz** [comment]
Someone can help me?
@murgatroid99

**Comment by murgatroid99** [comment]
We don't officially support SunOS.

I'm not sure why those logs don't show it falling back to compiling from source.

**Comment by usebaz** [comment]
Can I give you some additional logs? Or something else.
We really need this to connect the PubSub to our server.

**Comment by usebaz** [comment]
@murgatroid99 
This question can be solved?

**Comment by usebaz** [comment]
@nicolasnoble

**Comment by olka** [comment]
Same here
