### ISSUE TITLE
how to enable the log from the c/c++ lib

### ISSUE THREAD

**Issue by WandyLau** [grpc/grpc#13380]
I got an issue which needs log from the c/c++ log. I googled a lot and have no idea about how to enable the log.
Please help me with that.

**Comment by yang-g** [comment]
For the most verbose logs, set environment variable GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG and use a debug build.

For more fine-grained control of the trace, please look at https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

**Comment by WandyLau** [comment]
I read the binding.gyp file and found the line .
       ` 'Debug': {
             'cflags': [
                 '-O0',
             ],
             'defines': [
                 '_DEBUG',
                 'DEBUG',
                 'dbg',
             ],
       },`

I think this debug is enabled by default. But when I set the environment variables. I can not get the debug info anyway. I missed something?
