### ISSUE TITLE
Remove src/php/lib in favor of grpc/grpc-php via composer?

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc#13410]
The [`grpc/grpc-php`](https://github.com/grpc/grpc-php) repository no represents the PHP native gRPC library component. So why are those classes still in this repository? The `grpc-php` repo says it's a mirror, but it isn't a true mirror. Wouldn't it make a lot more sense to make this repo pull in the `grpc/grpc-php` package via composer?

Issues can still be tracked in this repo if you'd like but it would be cleaner and more reliable to keep the code in only one place.

**Comment by bshaffer** [comment]
cc @stanley-cheung

**Comment by stanley-cheung** [comment]
Yes this makes a lot of sense
