### ISSUE TITLE
New Failure: json_run_localhost:cpp_protobuf_async_streaming_from_server_ping_pong_secure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13424]
- Test: json_run_localhost:cpp_protobuf_async_streaming_from_server_ping_pong_secure
- Poll Strategy: poll
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_basictests_c_cpp_opt/158

**Comment by jtattermusch** [comment]
https://sponge.corp.google.com/invocation?id=cc270bcf-4878-406e-9558-dc1c17ce3852

**Comment by jtattermusch** [comment]
Not enough data here, closing.
