### ISSUE TITLE
build gRPC has error, How can I fix, I hope to get help

### ISSUE THREAD

**Issue by lylee1981** [grpc/grpc#1342]
i want to build gRPC on my work machine, i refer to "https://github.com/grpc/grpc/blob/master/INSTALL" 's info, at "make" step, i get the following error message, i provided some information for my development machine, i hope to get help, thanks.

build step:
===========================
1. git clone https://github.com/grpc/grpc.git
2. cd grpc
3. git submodule update --init
4. make 

error info:
===========================
src/core/iomgr/pollset_multipoller_with_epoll.c: In function ‘grpc_platform_become_multipoller’:
src/core/iomgr/pollset_multipoller_with_epoll.c:176: warning: implicit declaration of function ‘epoll_create1’
src/core/iomgr/pollset_multipoller_with_epoll.c:176: error: ‘EPOLL_CLOEXEC’ undeclared (first use in this function)
src/core/iomgr/pollset_multipoller_with_epoll.c:176: error: (Each undeclared identifier is reported only once
src/core/iomgr/pollset_multipoller_with_epoll.c:176: error: for each function it appears in.)
make: *** [objs/opt/src/core/iomgr/pollset_multipoller_with_epoll.o] Error 1

env:
=========================

gcc version:
===========================

$gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-51)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by nicolasnoble** [comment]
@dklempner I told you that we'd get people trying grpc on old enough Linux platforms :-)

@lylee1981 your environment is unfortunately too old to support gRPC.

**Comment by lylee1981** [comment]
i modified file "src/core/iomgr/pollset_multipoller_with_epoll.c"
add one include:
#include <linux/fcntl.h>

and add one define:
#define EPOLL_CLOEXEC O_CLOEXEC

then make again, and build libgrpc.a is ok, but has another error:

[MAKE]    Building protobuf
checking whether to enable maintainer-specific portions of Makefiles... no
configure: error: cannot find install-sh or install.sh in . ./.. ./../..
make: *** [libs/opt/protobuf/libprotobuf.a] Error 1

For this error, what advice do？ thanks.

**Comment by lylee1981** [comment]
I solved the problem in the following way：

1. modify source code:
src/core/iomgr/pollset_multipoller_with_epoll.c

add:
#include <linux/fcntl.h>
#define EPOLL_CLOEXEC O_CLOEXEC

2. modify grpc 's Makefile

a). change CPPFLAGS, remove -Werror feature
b). change DEFAULT_CXX to high version of c ++ path

eg：
DEFAULT_CXX = /path/to/your/high/version/c++/path
