### ISSUE TITLE
Cannot drain completion queue for async. client.

### ISSUE THREAD

**Issue by ababo** [grpc/grpc#13456]
There's no problem to shut down a server, as well as to free allocated tasks. But I experience problems while trying to do the same for a client. Since the client can have multiple simultaneous tasks running I need to shut down it gracefully and to free all the allocated tasks. But I can't do that. Calling `Shutdown` on the client's completion queue makes long-running streaming tasks to be finished after a long time period, while still no immediate queue draining happens (neither `AsyncNext` returns cancelled tasks with `!ok`, nor `SHUTDOWN` status is returned).

**Comment by sreecha** [comment]
You could call `ClientContext::TryCancel()` API on the client to cancel all in-flight RPCs. That should help drain the completion queue..
