### ISSUE TITLE
several cloud_to_cloud node_server interop tests failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#13460]
https://sponge.corp.google.com/target?id=586f9e41-c20c-4b5e-871e-2de4a19cc059&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

The following tests are failing:

cloud_to_cloud:ruby:node_server:unimplemented_method 
cloud_to_cloud:ruby:node_server:custom_metadata
cloud_to_cloud:javaokhttp:node_server:unimplemented_service
cloud_to_cloud:ruby:node_server:status_code_and_message
cloud_to_cloud:ruby:node_server:unimplemented_service
cloud_to_cloud:ruby:node_server:timeout_on_sleeping_server 

In all cases, the failure is related to the server returning UNAVAILABLE status.

**Comment by murgatroid99** [comment]
It looks like those tests may have run before #13433 and grpc/grpc-node#95 were merged. They were supposed to fix that problem. I'm going to close this for now, and we'll reopen it if this problem shows up again.
