### ISSUE TITLE
PHP-Client: expected behavior when not calling close() on GRPC-Clients

### ISSUE THREAD

**Issue by fho** [grpc/grpc#13474]
### Should this be an issue in the gRPC issue tracker?
* No
 
### What version of gRPC and what language are you using?
* PHP 7.1.10 with GRPC extension 1.7.0
* Go 1.7.3
 
### What operating system (Linux, Windows, …) and version?
* Alpine Linux
 
---------------------------------------------

We are connecting with the GRPC PHP Client to Go GRPC-Servers.
The PHP-Clients were not calling the `close()` method on the GRPC Client objects after they were used. In netstat I observed that those connections after they became idle for some time went into `CLOSE_WAIT` state.
When the PHP-application then instantiated another Client for the same server, the first GRPC request failed with status `UNAVAILABLE`.  The TCP `CLOSED_WAIT` TCP-Connection vanishes after the failure and the second try with a new GRPC Client object succeeds.

I couldn't find much documentation about the PHP-Client and the `close()` function neither any examples where `close()` is called.

My questions:
Is it expected that `close()` is called on the GRPC-Client objects in PHP?
If it's not called, what is the expected behavior? What should happen with the TCP connection?

**Comment by ZhouyihaiDing** [comment]
Hi. I am looking into it. Client stub has close() method like `clientStub.close()`, which the channel inside the stub calls [grpc_channel_destroy](https://github.com/grpc/grpc/blob/master/include/grpc/grpc.h#L302)
Can you please give me an example reproducing it?
Thanks!

**Comment by fho** [comment]
Hello @ZhouyihaiDing,

thanks for your help!

I build a simple PHP client + Go server to reproduce it (https://github.com/fho/grpc_issue_13474).

The server program does in a loop:
-  starting a GRPC-Server
- waiting 30 seconds
- stopping the GRPCServer

The PHP Client script is issuing a request at the GRPC-Server. The PHP script has to be run in php server mode (`php -S`) to reproduce the issue.

Steps to reproduce: 
1. You do a request to http://localhost:8000/greeter_client.php
2. Wait until the GRPC-Server was restarted in the server.
If you check the output of `netstat -tupen`, you will see that the TCP connection from the Client to the Go-Server hangs in the `CLOSE_WAIT` state.
3. You do another request to http://localhost:8000/greeter_client.php, the request will fail with status Code 14 (Unavailable).


I think there are multiple issues:
1. Same issue than: https://github.com/grpc/grpc/issues/11043. It was fixed in the Python and Ruby Clients but still exist in PHP.
The returned status `Unavailable` is wrong, the server was reachable at the time when the request was done.
2. The issue does not happen when the script is run via `php greeter_client.php`.
 It only happens when the php-script is run in server mode.
If I understand it correctly, the php-plugin only closes the channel (and with that the connection?) when `grpc_destroy()` is called by the zend object free handler. 
The free handler is run as part of the PHP executor shutdown. Therefore channels can persist until the PHP executor terminates, which can be a very long time.
Maybe the connection should be closed in the zend dtor handler of the channel object instead?
3. It causes that in the Go-Server, `grpc.Server.GracefulStop()` hangs forever (or very long until the connection was closed from the php plugin?).
If you change the Go grpc server to call `GracefulStop()` instead of `Stop()` on `grpc.Server`, then issue a request from the PHP Client in PHP  server mode, the Go-Server will hang at the `GracefulStop()` call.

**Comment by sagikazarmark** [comment]
I can confirm this is a problem on PHP 5.6 with gRPC extension 1.6.0 (with the same symptoms).

Closing the connection manually immediately after a call is finished makes things somewhat better, but I haven't don any stress tests, things may go south when there is more than one user.

**Comment by ZhouyihaiDing** [comment]
Sorry for the delay.
Reconnect the disconnected channel is fixed by [backup poller](https://github.com/grpc/grpc/pull/12732). 
You can download grpc-1.8.0RC1 or [buld form source](https://github.com/grpc/grpc/tree/master/src/php#build-from-source) to solve this problem until 1.8.0 is released.

**Comment by fho** [comment]
thank you, @ZhouyihaiDing. I'll give it a try.

**Comment by fho** [comment]
I can confirm that the issue is fixed in version 1.8.0RC1.
I could not reproduce the issue anymore.
