### ISSUE TITLE
Tsan C++ Infrastructure Failures

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#13478]
Example [here](https://sponge.corp.google.com/invocation?id=c7f844df-1277-4592-91ba-9dc8d4c6c05f&searchFor=)

Seems like the problem lies somewhere in here:
```
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1576, in <module>
    build_only=args.build_only)
  File "tools/run_tests/run_tests.py", line 1487, in _build_and_run
    for language in languages
  File "tools/run_tests/run_tests.py", line 1488, in <genexpr>
    for spec in language.test_specs()
  File "tools/run_tests/run_tests.py", line 348, in test_specs
    stderr=fnull)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'bins/tsan/bm_call_create', '--benchmark_list_tests']' returned non-zero exit status 66
```

**Comment by dgquintas** [comment]
This is not Kokoro related, it can be repro'd locally (CC @matt-kwong )

**Comment by ncteisen** [comment]
This was caused by #13109. I will fix

**Comment by dgquintas** [comment]
Also marking P0 because it's happening consistently on kokoro

**Comment by murgatroid99** [comment]
This may still be happening on v1.8.x: https://sponge.corp.google.com/target?id=b85bf6e6-f5b1-47f8-b5e9-e25172288e6c&target=grpc/ubuntu/pull_request/grpc_cpp_tsan&searchFor=&show=ALL&sortBy=STATUS triggered by #13532.

**Comment by ncteisen** [comment]
I will backport my fix, thanks for the heads up

**Comment by ncteisen** [comment]
Actually, I think your branch is just not up to date with 1.8, because the fix is in in 1.8. See [here](https://github.com/grpc/grpc/blob/v1.8.x/src/core/lib/debug/trace.cc)

**Comment by mehrdada** [comment]
@mlumish please make sure the v1.8.x you are working on does not contain
bad merge commit 1e89ef6 which Nico and I were fixing last night and ended
up with a history rewrite.

**Comment by murgatroid99** [comment]
My branch doesn't have that commit. It could just be the timing of when I created my branch vs when the fix was added.

**Comment by mehrdada** [comment]
Yeah, probably.
