### ISSUE TITLE
Eliminate sleeps in route_guide_client.py

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#13487]
These have been there for nearly three years and no one ever mentioned them until this week when in come two reports (one Google-internal and [one on the public Internet](https://stackoverflow.com/questions/47384362/why-do-request-streaming-grpc-clients-have-to-sleep-after-yield)) calling them funny. I always thought they were demonstrations of how the client might do time-consuming work. Apparently they're spurious and not something also implemented in the other languages' implementations of the route guide example. Let's kill them off.

@jtattermusch: [do you remember adding them](https://github.com/grpc/grpc/commit/460a449742d56bfc36c381c350825b73112d20c8), and if so, for what reason?

**Comment by jtattermusch** [comment]
I don't remember adding them, to be honest. I think they were there to show that streaming messages can be delivered separately. I don't know about any reason to keep them.
