### ISSUE TITLE
Rename "SSL" code elements "TLS"?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#13481]
Over in [pull request 13479](https://github.com/grpc/grpc/pull/13479) @mehrdada suggested renaming (well, "introducing new aliases of", because we wouldn't want to break anyone) the "SSL" code elements of the gRPC Python API "TLS" (so that `ssl_server_credentials` becomes `tls_server_credentials` and so forth). What do you think?

**Comment by mehrdada** [comment]
Just to be clear, even if the code element change is infeasible, I am advocating the documentation comments to say TLS instead of SSL.

**Comment by nathanielmanistaatgoogle** [comment]
It's an API; if we wish to do a migration we should be able to do it while also providing aliases under the old names. Help me see where it would be infeasible?

**Comment by mehrdada** [comment]
By "infeasible", I mean unless we plan to deprecate them at some point, which will break some users, it is just a duplication of code elements and feels flawed in nature. Between not breaking users vs. fixing the name, I feel the former would be more justified.

**Comment by mehrdada** [comment]
I wonder what @jboeuf thinks about the first step, i.e. transitioning API documentation from "SSL" to "TLS", which can precede the actual API changes by years?

**Comment by jboeuf** [comment]
CCing @jiangtaoli2016 and @justinburke 

If we are going to rename this code, we should think about using `HTTPS` as opposed to `TLS` since these credentials carry `HTTPS` semantics with domain name validation. This is in contrast with other usages for TLS such as www.spiffe.io which have different trust semantics and will probably have their own type of credentials.

**Comment by mehrdada** [comment]
@jboeuf I see... would HTTPS still be a good name considering we potentially run on non-HTTP2 transports?

**Comment by jboeuf** [comment]
This is a good question. What we want to distinguish is not so much the
transport but the semantics of trust validation in TLS (which is silent
about any given trust model). HTTPS is typically what we refer to for
server host name validation as it references something that the industry
understands.
`TlsWithServerHostNameValidation` would be a bit sad. Another solution
would be to keep TLS and add options for a given trust model where Server
Host Name validation would be the default.

**Comment by justinburke** [comment]
> `TlsWithServerHostNameValidation` would be a bit sad. Another solution
> would be to keep TLS and add options for a given trust model where Server
> Host Name validation would be the default.

+1 to both these comments. The verbose name, while descriptive, is probably too verbose for the common case. I like the idea of adding an option to specify an alternative validation model.
