### ISSUE TITLE
Large amount of memory consumed [C++]

### ISSUE THREAD

**Issue by AngryLemonn** [grpc/grpc#13495]
### What version of gRPC and what language are you using?
 **Language**: C++ (client and server)
**Grpc version**: Current master branch (but this bug comes from the 1.1.0 version)
 
### What operating system (Linux, Windows, …) and version?
 Debian Jessie 8.8
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++ 4.9.2
 
### What did you do?
I created one sync server and one sync client to prove memory consumption with a simply rpc call. The client and server shared one proto with only one function called "login". This function pass two strings from the client to the server, and the server responds with one boolean (a simply login function).
 
### What did you expect to see?
 0.0~0.1 memory consumption.
 
### What did you see instead?
 1K of requests, 0.7 of the entire memory (56M of 8GB). Up to 100K requests, the memory consumption increase exponentially.

After this, I used valgrind to see where the memory leak was. Protobuf and grpc/grpc++ lost a little of memory per call, but the problem is not here.

Using pmap after the memory consumption test suite, I saw that the server process had a lot of **anon blocks** of 4K to 6MB. Depending on the program, you may have up to a few dozen of these, but if you are seeing thousands, it means **you have a problem with threading**. In my test suite, I do not manage any thread. However, my grpc server has a thread pool that I can't manage because grpc does this job for me. Only I can set the max/min pollers. If I set this options to 1, the memory consumption increase less, but does not stop.
 
### Anything else we should know about your project / environment?
Nope, the project is very very simply. If you need to see my test code, just ask me.

**Comment by AngryLemonn** [comment]
#13319

**Comment by sebastianbauer** [comment]
We have the same problem with a gRPC C++ server. Using gRPC 1.10.

After starting the server - without any requests - you already see increasing memory consumption.

With hundrets of requests we have 800MiB of RAM. A night later, without any request, we have 860MiB.

**Comment by srini100** [comment]
@sebastianbauer can you provide your test code?

**Comment by sebastianbauer** [comment]
@srini100 Unfortunately I cannot provide any code. We are investigating more. We did some tests and changes and maybe have some results next week.

**Comment by srini100** [comment]
@AngryLemonn , I don't see anon blocks growing out of bound even with heavy load on the server. Also, pmap shows a large number of anon blocks still held by the process but most are unmapped. Can you provide test code to reproduce this issue?

**Comment by yashykt** [comment]
Also, I let a server run without any requests over the weekend, and there was no noticeable increase in the total memory consumed by the server.

**Comment by srini100** [comment]
@sebastianbauer, do you have any more info on this. Please open a new issue if you are still seeing memory leak.
