### ISSUE TITLE
-Werror in Makefile

### ISSUE THREAD

**Issue by PhoenixMage** [grpc/grpc#13503]
### What version of gRPC and what language are you using?
1.6.x
 
### What operating system (Linux, Windows, …) and version?
Linux - Arm though the issue shouldnt be arm specific
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc-7
 
### What did you do?
gem install grpc -v '1.6.6'
 
### What did you expect to see?
 grpc gem to compile successfully
 
### What did you see instead?
gprc failing to compile due to using -Werror and the zlib source files used generating a fall through warning due to case statements not having a break or return

Is it possible to modify the Makefile so that -Werror is no longer present? There are no compiler errors only warnings. I can compile successfully if I manually remove -Werror (sed -i -e 's|-Werror||') however this doesnt help with bundles as it untars the source everytime overwriting any changes.

I have lodged a bug with zlib to fix the underlying problem.

**Comment by apolcyn** [comment]
Experimented compiling with gcc-7, and I think this can be fixed by compiling with `-Wno-implicit-fallthrough`, as done in https://github.com/apolcyn/grpc/commit/1a4fabc9c758365cbbf27b5ee4af87ce0d9dfc09. Assuming that fixes it, I will probably get time to release that next week.

**Comment by jtattermusch** [comment]
Also see https://github.com/grpc/grpc/issues/13854

**Comment by apolcyn** [comment]
tentatively fixed by https://github.com/grpc/grpc/pull/14136,  please reopen if this is still an issue.
