### ISSUE TITLE
Run performance tests with Python 3.7

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#13505]
Python 3.6 is what our users _should_ be using, so Python 3.6 should be [the interpreter used in measuring how our system behaves](https://github.com/grpc/grpc/blob/de93112a3f70afa39d3e9aa87da165f9f737fdef/tools/run_tests/performance/run_worker_python.sh#L20).

**Comment by nathanielmanistaatgoogle** [comment]
It's been a while, so how about Python 3.7? It's currently in beta but should be released in the next few months.

**Comment by matt-kwong** [comment]
I think it's reasonable to use 3.7, but I also think we should standardize our Python testing versions. I.e. I don't want to run 3.7 for performance tests for 3.4 for unit tests. I think we should run a general sweep through all Python tests to upgrade them to 3.7, and leave 3.4. - 3.6 as build-only portability tests.

**Comment by adelez** [comment]
Have we decided on which version to use?

**Comment by nathanielmanistaatgoogle** [comment]
@adelez: whichever reliably produces the most flattering performance results. I'm only one-quarter kidding. But if that isn't actionable, then... the newest version that is not to much work to incorporate into and maintain in the testing infrastructure.

**Comment by nathanielmanistaatgoogle** [comment]
@lidizheng, @gnossen: is 3.4 still being used anywhere in the project infrastructure?

**Comment by gnossen** [comment]
Some grepping shows that we really only use it to set up explicit tests of 3.4.

**Comment by lidizheng** [comment]
What @gnossen said is correct. Add one more point, the only usage of 3.4 I see in our automations is distribtest.
