### ISSUE TITLE
Using gRPC from a Bazel project is too complex

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#13502]
It takes 1425 lines of boilerplate to integrate gRPC into a project:

https://github.com/google/ced/commit/b55567e0479d7d441da3d5e3a901947bb7ebbc18

Most of this is overhead that users of the library should never need to care about (ex: what is cares? why do *I* care?? why am I copying hundreds of lines of code into my project just to get this thing to compile!!)

Concrete actions we should take:
- host dependent library build configurations in their own repos (if we need to maintain these, so be it, though I'll note that bazel folks have https://github.com/bazelbuild/bazel-packages which might be ripe for populating with the bits that we need)
- follow through with a change like https://github.com/grpc/grpc/pull/13468

**Comment by apolcyn** [comment]
FTR for the second point,

> Follow through with a change like #13468

that is done in https://github.com/grpc/grpc/pull/13561
