### ISSUE TITLE
Windows C# socket leak

### ISSUE THREAD

**Issue by yayaboring** [grpc/grpc#13519]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
   1.7.1 and C#
 
### What operating system (Linux, Windows, …) and version?
  Windows 7 SP1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .Net Framework 4.5.2   
 
### What did you do?
[GrpcSocketLeak.zip](https://github.com/grpc/grpc/files/1509527/GrpcSocketLeak.zip)
 the code trying to connect server which not listen.
 In test code, I set "grpc.testing.fixed_reconnect_backoff_ms" to 1000 and used 100 parallel connections for it appear more quickly.

### What did you expect to see?
 number of handles does not increasing endlessly.
 
### What did you see instead?
 number of handles increasing endlessly and when it stops increasing, (after running about 10 minutes)
 and try to surf internet using web browser, it shows connection refused.
 
### Anything else we should know about your project / environment?
In my project, connectivity is important information.

**Comment by yayaboring** [comment]
below one line of code will slow down this leak.
File: tcp_client_windows.c line:105
``
if (!wsa_success) {
        closesocket(socket->socket);
        error = GRPC_WSA_ERROR(WSAGetLastError(), "ConnectEx");
``

**Comment by luchunminglu** [comment]
#13102 describe a similar bug as this one

**Comment by yayaboring** [comment]
I made pull request
https://github.com/grpc/grpc/pull/13604

**Comment by jtattermusch** [comment]
Fixed by #13604.
