### ISSUE TITLE
Is "an encapsulation of the data required to assert an identity over a channel" the right summary for grpc.CallCredentials?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#13523]
Currently [the summary string of `grpc.CallCredentials` reads "An encapsulation of the data required to assert an identity over a channel."](https://grpc.io/grpc/python/grpc.html#grpc.CallCredentials). Is this correct or should "over a channel" be changed to "for a call"?

**Comment by jboeuf** [comment]
Over a call :).

**Comment by nathanielmanistaatgoogle** [comment]
Closing; this was fixed in [pull request 13533](https://github.com/grpc/grpc/pull/13533).
