### ISSUE TITLE
Make fails with #error "system call number for getrandom is not the expected value"

### ISSUE THREAD

**Issue by A-Mendi** [grpc/grpc#13537]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.6 (current), C++
 
### What operating system (Linux, Windows, …) and version?
 Linux 4.4.0-0 SMP Debian 4.4.16-1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
  g++ --version
g++ (Debian 4.9.2-10) 4.9.2

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Following the installation instructions, the "Make" command fails with error
 
### What did you expect to see?
 Make successful
 
### What did you see instead?
third_party/boringssl/crypto/rand/urandom.c:62:2: error: #error "system call number for getrandom is not the expected value"
 #error "system call number for getrandom is not the expected value"
  ^
In file included from /usr/include/x86_64-linux-gnu/sys/syscall.h:31:0,
                 from third_party/boringssl/crypto/rand/urandom.c:32:
third_party/boringssl/crypto/rand/urandom.c: In function ‘init_once’:
third_party/boringssl/crypto/rand/urandom.c:128:15: error: ‘__NR_getrandom’ undeclared (first use in this function)
       syscall(SYS_getrandom, &dummy, sizeof(dummy), GRND_NONBLOCK);
               ^
third_party/boringssl/crypto/rand/urandom.c:128:15: note: each undeclared identifier is reported only once for each function it appears in
third_party/boringssl/crypto/rand/urandom.c: In function ‘fill_with_entropy’:
third_party/boringssl/crypto/rand/urandom.c:258:21: error: ‘__NR_getrandom’ undeclared (first use in this function)
         r = syscall(SYS_getrandom, out, len, 0 /* no flags */);
                     ^
Makefile:2564: recipe for target '/home/usrnm/grpc/objs/opt/third_party/boringssl/crypto/rand/urandom.o' failed
make: *** [/home/usrnm/grpc/objs/opt/third_party/boringssl/crypto/rand/urandom.o] Error 1

 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by yashykt** [comment]
are you still seeing this?

**Comment by A-Mendi** [comment]
Thanks for checking in. I can’t confirm if the issue is resolved because I haven’t tried it a little after opening this issue. I tried starting from scratch. I might have had faces this  because, earlier I was using the latest version of only the protobuf. Later we decided to use grpc on top of it to manage services. I started seeing this issue when I installed grpc after having a working protobuf already installed (the versions of grpc makefile and protobuf matched). After seeing these errors I removed everything, grpc as well as installed protobuf and reinstalled grpc from scratch along with protobuf shipped with grpc as described in grpc doc. I saw the same issue multiple times and finally gave up (moved on). 

I believe you can close this for now.
