### ISSUE TITLE
Error: RPC that terminated with (StatusCode.UNKNOWN, Exception iterating requests!)

### ISSUE THREAD

**Issue by ravijo2** [grpc/grpc#13544]
I 'm getting follow error message on the client side.
On the server side I do received the message, but gives error when trying to iterate the message received from the client. 

Proto definition:
=============
    service chatServer {
      rpc msgExchange(stream chatMsg) returns (stream chatMsg) { }                                                 
    }               
    message chatMsg {
      int32 id = 1;
      string msg = 2;
    }

Server Snippet:
============
    def msgExchange(self, request_iterator, context):                                                           
        for from_agt in request_iterator:
            print("Collector received from Agent Id {}, message: {}".format(from_agt.id, from_agt.msg))
        i = 0
        for i in range(0, 3):
            yield collBuildChatMsg(i)
            i = i + 1

Client Snippet:
============
            from_coll =chatStub.msgExchange(buildChatMsg())
            for coll_msg in from_coll:
                print("Collector response: Coll-Id={} Msg={}".format(coll_msg.id, coll_msg.msg))

Error messages on the client side:
==========================
    ERROR:root:Exception iterating requests!
    Traceback (most recent call last):
     File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 185, in 
    consume_request_iterator
        request = next(request_iterator)
    TypeError: chatMsg object is not an iterator
    Requested RPC Failed
    Traceback (most recent call last):
      File "client.py", line 97, in <module>
        client.agtRun()
      File "client.py", line 56, in agtRun
        for coll_msg in from_coll:
      File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 351, in next
        return self._next()
      File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 331, in _next
        raise self
    _Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Exception 
    iterating requests!)>

**Comment by nathanielmanistaatgoogle** [comment]
The error seems to be in `from_coll =chatStub.msgExchange(buildChatMsg())`: `chatStub.msgExchange` requires an iterator of zero or more messages, but I suspect that you're passing it a single message rather than an iterator of messages.
