### ISSUE TITLE
PHP: ext-grpc should report its version on phpinfo

### ISSUE THREAD

**Issue by tmatsuo** [grpc/grpc#13556]
`phpinfo()` shows all the information about your PHP runtime, including the extension options and versions.
Now grpc extension only reports that it's enabled. I think it should report its version too.

FYI @chingor13 added it for the opencensus extension
https://github.com/census-instrumentation/opencensus-php/pull/42/files

**Comment by ZhouyihaiDing** [comment]
Done.
