### ISSUE TITLE
ServerBuilder.SetMaxReceiveMessageSize(-1) doesn't set receive size to unlimited

### ISSUE THREAD

**Issue by sKolar42** [grpc/grpc#13553]
On CentOS 7, gRPC/C++ 1.6.6, compiled with gcc 4.8.5

I attempted to use ServerBuilder to construct a server with a max receive size of unlimited, like so:
```
grpc::ServerBuilder builder;
builder.SetMaxReceiveMessageSize(-1);
server = builder.BuildAndStart();
```

Then sent a request to it, and got the following response:
> Received message larger than max (633346913 vs. 4194304)

Digging through the gRPC code, I see that the default receive size is set to 4MiB: 
`#define GRPC_DEFAULT_MAX_RECV_MESSAGE_LENGTH (4 * 1024 * 1024)`

Further, ServerBuilder won't set its max receive size if said value is -1:
```
 if (max_receive_message_size_ >= 0) {
    args.SetInt(GRPC_ARG_MAX_RECEIVE_MESSAGE_LENGTH, max_receive_message_size_);
  }
```
Thus, message_size_filter won't set the receive limit:

```
    if (strcmp(channel_args->args[i].key,
               GRPC_ARG_MAX_RECEIVE_MESSAGE_LENGTH) == 0) {
      const grpc_integer_options options = {lim.max_recv_size, -1, INT_MAX};
      lim.max_recv_size =
          grpc_channel_arg_get_integer(&channel_args->args[i], options);
    }
```

Which ultimately results in the above error.  When I set the max message size to -1, I expect it to be unlimited, not some different default value.

**Comment by yashykt** [comment]
Should be fixed as of #15394
