### ISSUE TITLE
Need more control on when the client side of the stream is closed

### ISSUE THREAD

**Issue by rlubke** [grpc/grpc#13569]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 
Python / gRPC 1.7.1
 
### What operating system (Linux, Windows, …) and version?

MacOS High Sierra
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 3.6
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Currently, on the client side, after the generator completes it sends a close for the client's send channel. This is perfectly legal, however, it seems to cause some issues with with a gRPC server in Java, or perhaps it's how it's been implemented in this particular case. In this case, the server assumes, when it receives a half close from the client, that the client is done and no longer interested in receiving events from the server.

There seems to be no issues using go or node clients with this particular server.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ncteisen** [comment]
Could you provide small code snippits with this particular use case? That would be help us push forward

**Comment by nathanielmanistaatgoogle** [comment]
I agree with @ncteisen about needing to see sample code. I'm also confused about the request - applications should have complete control over when the request stream is closed, although they may have to implement their own iterator object.
