### ISSUE TITLE
grpc_csharp_ext.x86.dll crash some times.

### ISSUE THREAD

**Issue by henry8366** [grpc/grpc#13585]
### What version of gRPC and what language are you using?
 gRPC 1.6 C# for client,nodjs for server. Both use grpc 1.6
 
### What operating system (Linux, Windows, …) and version?
Client: Windows7 x64 ,Windows10 x64
Server:Center os7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 VS2015 .net4.5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 Just Connected the Nodejs GRPC server,and do some ping operation by Ping method what difined via grpc，receive the push data form nodejs grpc server。
### What did you expect to see?
 do not crash my c# App.
 
### What did you see instead?
 Error module name: grpc_csharp_ext.x86.dll, version: 0.0.0.0, timestamp: 0x59bbb7e1
Exception code: 0xc0000409
Error offset: 0x000cdc8f
and this exception can not catch in C# program.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
  Error module name: grpc_csharp_ext.x86.dll, version: 0.0.0.0, timestamp: 0x59bbb7e1
Exception code: 0xc0000409
Error offset: 0x000cdc8f

**Comment by jtattermusch** [comment]
Hi, thanks for filing the issue, but the information you filed is not sufficient for debugging this issue.
(they trace you provided is basically just an info that the native library used by gRPC C# has crashed). 

Also, "just connecting to from C# to node.js and sending a few messages" is not a sufficient way to reproduce - we have tests that are doing basically that and they are passing, so the problem is probably more subtle and needs a bit more diagnosing:
how often does this happen?
can you reproduce C# client to C# server (or other languages) or is just C# to Node?
what's the minimal code snippet that reproduces the problem?
Is this just in version 1.6? Have you tried with v1.7 (stable release) and v1.8 (prerelease)?

**Comment by henry8366** [comment]
I think it 's not a gRPC c# Core problem,becouse this exception can not be  catch in my c# project . It's crash directly.
The frequency of the occurrence is uncertain, sometimes a few times a day sometimes not. Every time my log shows a stop in Ping, I'm not sure whether it's caused by Ping because it can't track the call information. I only use version 1.6. In addition, I also found a problem of crash. When creating a channel but not getting the information flow (without calling the MoveNext of stream), shutdown channel can't quit shutdown method, and shutdown will be crash again. If canceltoken is cancel ahead of time, this is the case.

**Comment by henry8366** [comment]
These exceptions are suggestive of grpc_csharp_ext.x86.dll problems, not C# Core.

**Comment by henry8366** [comment]
I use version is 1.6.1

**Comment by henry8366** [comment]
Can you provide some tools or debug versions for our convenience.
My email is 125200321@qq.com

**Comment by jtattermusch** [comment]
@henry8366 you're right that this is a problem in grpc_csharp_ext.x86.dll library -> hence in the C core code (not C#). Can you try upgrading to 1.7.x (or 1.8.0-pre2) and see if that helps with your problem?

**Comment by jtattermusch** [comment]
Also, it looks like that without you providing a code to reproduce said issues, we can't really help fixing this. Do you have a minimal snippet that triggers the problem (the verbal description is inherently vague so I don't know how to reproduce reliably).

**Comment by henry8366** [comment]
I have upgraded version 1.7.1, but there are still crashes. If the network breaks, the channel will be in Idle state, and the shutdown will cause a crash. I am not sure whether the irregular breakdown is due to network problems, but there must be similar problems in your network communication.

**Comment by jtattermusch** [comment]
@henry8366 I really can't help you unless you provide some logs with useful information or a snippet that reproduces the issue.

**Comment by jtattermusch** [comment]
@henry8366 are you still seeing this?

**Comment by jtattermusch** [comment]
Please reopen if this is still an issue.
