### ISSUE TITLE
compile error INT32_MAX not declared int this scope

### ISSUE THREAD

**Issue by zhipengli0524** [grpc/grpc#13588]
/usr/bin/make64 MAC=64 HAS_SYSTEM_PROTOBUF=false -s -j8 static grpc_cpp_plugin
Package libcares was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcares.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcares' found
Package libcares was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcares.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcares' found
[MAKE]    Generating cache.mk
[CXX]     Compiling src/core/lib/support/time.cc
[CXX]     Compiling src/core/lib/support/time_posix.cc
[CXX]     Compiling src/core/lib/iomgr/error.cc
[CXX]     Compiling src/core/lib/iomgr/ev_epoll1_linux.cc
[CXX]     Compiling src/core/lib/iomgr/ev_epollex_linux.cc
[CXX]     Compiling src/core/lib/iomgr/ev_epollsig_linux.cc
[CXX]     Compiling src/core/lib/iomgr/ev_poll_posix.cc
[CXX]     Compiling src/core/lib/iomgr/ev_windows.cc
In file included from src/core/lib/support/time_posix.cc:30:0:
src/core/lib/support/time_posix.cc: In function ???imespec timespec_from_gpr(gpr_timespec)??:
src/core/lib/support/time_posix.cc:37:30: error: ???NT32_MAX?? was not declared in this scope
     GPR_ASSERT(gts.tv_sec <= INT32_MAX && gts.tv_sec >= INT32_MIN);
                              ^
include/grpc/support/log.h:93:11: note: in definition of macro ???PR_ASSERT??
     if (!(x)) {                                       \
           ^
src/core/lib/support/time_posix.cc:37:57: error: ???NT32_MIN?? was not declared in this scope
     GPR_ASSERT(gts.tv_sec <= INT32_MAX && gts.tv_sec >= INT32_MIN);
                                                         ^
include/grpc/support/log.h:93:11: note: in definition of macro ???PR_ASSERT??
     if (!(x)) {                                       \
           ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/support/time_posix.o] Error 1
make64[3]: *** Waiting for unfinished jobs....
src/core/lib/support/time.cc: In function ???nt gpr_time_cmp(gpr_timespec, gpr_timespec)??:
src/core/lib/support/time.cc:30:31: error: ???NT64_MAX?? was not declared in this scope
   if (cmp == 0 && a.tv_sec != INT64_MAX && a.tv_sec != INT64_MIN) {
                               ^
src/core/lib/support/time.cc:30:56: error: ???NT64_MIN?? was not declared in this scope
   if (cmp == 0 && a.tv_sec != INT64_MAX && a.tv_sec != INT64_MIN) {
                                                        ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_inf_future(gpr_clock_type)??:
src/core/lib/support/time.cc:54:16: error: ???NT64_MAX?? was not declared in this scope
   out.tv_sec = INT64_MAX;
                ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_inf_past(gpr_clock_type)??:
src/core/lib/support/time.cc:62:16: error: ???NT64_MIN?? was not declared in this scope
   out.tv_sec = INT64_MIN;
                ^
src/core/lib/support/time.cc: In function ???pr_timespec to_seconds_from_sub_second_time(int64_t, int64_t, gpr_clock_type)??:
src/core/lib/support/time.cc:72:24: error: ???NT64_MAX?? was not declared in this scope
   if (time_in_units == INT64_MAX) {
                        ^
src/core/lib/support/time.cc:74:31: error: ???NT64_MIN?? was not declared in this scope
   } else if (time_in_units == INT64_MIN) {
                               ^
src/core/lib/support/time.cc: In function ???pr_timespec to_seconds_from_above_second_time(int64_t, int64_t, gpr_clock_type)??:
src/core/lib/support/time.cc:95:24: error: ???NT64_MAX?? was not declared in this scope
   if (time_in_units >= INT64_MAX / secs_per_unit) {
                        ^
src/core/lib/support/time.cc:97:31: error: ???NT64_MIN?? was not declared in this scope
   } else if (time_in_units <= INT64_MIN / secs_per_unit) {
                               ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_time_add(gpr_timespec, gpr_timespec)??:
src/core/lib/support/time.cc:141:19: error: ???NT64_MAX?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                   ^
src/core/lib/support/time.cc:141:44: error: ???NT64_MIN?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                                            ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_time_sub(gpr_timespec, gpr_timespec)??:
src/core/lib/support/time.cc:174:19: error: ???NT64_MAX?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                   ^
src/core/lib/support/time.cc:174:44: error: ???NT64_MIN?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                                            ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_convert_clock_type(gpr_timespec, gpr_clock_type)??:
src/core/lib/support/time.cc:232:19: error: ???NT64_MAX?? was not declared in this scope
   if (t.tv_sec == INT64_MAX || t.tv_sec == INT64_MIN) {
                   ^
src/core/lib/support/time.cc:232:44: error: ???NT64_MIN?? was not declared in this scope
   if (t.tv_sec == INT64_MAX || t.tv_sec == INT64_MIN) {
                                            ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/support/time.o] Error 1
src/core/lib/iomgr/error.cc: In function ???oid unref_errs(grpc_error*)??:
src/core/lib/iomgr/error.cc:150:18: error: ???INT8_MAX?? was not declared in this scope
   while (slot != UINT8_MAX) {
                  ^
src/core/lib/iomgr/error.cc: In function ???oid unref_strs(grpc_error*)??:
src/core/lib/iomgr/error.cc:168:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
In file included from src/core/lib/iomgr/error.cc:29:0:
src/core/lib/iomgr/error.cc: In function ???int8_t get_placement(grpc_error**, size_t)??:
src/core/lib/iomgr/error.cc:208:26: error: ???INT8_MAX?? was not declared in this scope
         (uint8_t)GPR_MIN(UINT8_MAX - 1, (3 * (*err)->arena_capacity / 2));
                          ^
include/grpc/support/useful.h:24:25: note: in definition of macro ???PR_MIN??
 #define GPR_MIN(a, b) ((a) < (b) ? (a) : (b))
                         ^
src/core/lib/iomgr/error.cc: In function ???oid internal_set_int(grpc_error**, grpc_error_ints, intptr_t)??:
src/core/lib/iomgr/error.cc:233:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot == UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid internal_set_str(grpc_error**, grpc_error_strs, grpc_slice)??:
src/core/lib/iomgr/error.cc:248:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot == UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid internal_set_time(grpc_error**, grpc_error_times, gpr_timespec)??:
src/core/lib/iomgr/error.cc:268:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot == UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid internal_add_error(grpc_error**, grpc_error*)??:
src/core/lib/iomgr/error.cc:283:42: error: ???INT8_MAX?? was not declared in this scope
   grpc_linked_error new_last = {new_err, UINT8_MAX};
                                          ^
src/core/lib/iomgr/error.cc: In function ???rpc_error* grpc_error_create(const char*, int, grpc_slice, grpc_error**, size_t)??:
src/core/lib/iomgr/error.cc:338:20: error: ???INT8_MAX?? was not declared in this scope
   err->first_err = UINT8_MAX;
                    ^
src/core/lib/iomgr/error.cc: In function ???oid ref_strs(grpc_error*)??:
src/core/lib/iomgr/error.cc:369:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid ref_errs(grpc_error*)??:
src/core/lib/iomgr/error.cc:377:18: error: ???INT8_MAX?? was not declared in this scope
   while (slot != UINT8_MAX) {
                  ^
src/core/lib/iomgr/error.cc: In function ???ool grpc_error_get_int(grpc_error*, grpc_error_ints, intptr_t*)??:
src/core/lib/iomgr/error.cc:469:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot != UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???ool grpc_error_get_str(grpc_error*, grpc_error_strs, grpc_slice*)??:
src/core/lib/iomgr/error.cc:501:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot != UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid collect_ints_kvs(grpc_error*, kv_pairs*)??:
src/core/lib/iomgr/error.cc:608:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid collect_strs_kvs(grpc_error*, kv_pairs*)??:
src/core/lib/iomgr/error.cc:632:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid collect_times_kvs(grpc_error*, kv_pairs*)??:
src/core/lib/iomgr/error.cc:667:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid add_errs(grpc_error*, char**, size_t*, size_t*)??:
src/core/lib/iomgr/error.cc:677:18: error: ???INT8_MAX?? was not declared in this scope
   while (slot != UINT8_MAX) {
                  ^
src/core/lib/iomgr/error.cc: In function ???onst char* grpc_error_string(grpc_error*)??:
src/core/lib/iomgr/error.cc:746:25: error: ???INT8_MAX?? was not declared in this scope
   if (err->first_err != UINT8_MAX) {
                         ^
src/core/lib/iomgr/error.cc: In function ???ool grpc_error_get_str(grpc_error*, grpc_error_strs, grpc_slice*)??:
src/core/lib/iomgr/error.cc:507:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/error.o] Error 1
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_epoll1_linux.h:22,
                 from src/core/lib/iomgr/ev_epoll1_linux.cc:25:
src/core/lib/iomgr/ev_epoll1_linux.cc: In function ???nt poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)??:
src/core/lib/iomgr/ev_epoll1_linux.cc:570:17: error: ???NTPTR_MAX?? was not declared in this scope
   if (millis == GRPC_MILLIS_INF_FUTURE) return -1;
                 ^
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_poll_posix.h:22,
                 from src/core/lib/iomgr/ev_poll_posix.cc:23:
src/core/lib/iomgr/ev_poll_posix.cc: In function ???nt poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)??:
src/core/lib/iomgr/ev_poll_posix.cc:1127:19: error: ???NTPTR_MAX?? was not declared in this scope
   if (deadline == GRPC_MILLIS_INF_FUTURE) return -1;
                   ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_epoll1_linux.o] Error 1
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_poll_posix.o] Error 1
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_epollex_linux.h:22,
                 from src/core/lib/iomgr/ev_epollex_linux.cc:26:
src/core/lib/iomgr/ev_epollex_linux.cc: In function ???nt poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)??:
src/core/lib/iomgr/ev_epollex_linux.cc:694:17: error: ???NTPTR_MAX?? was not declared in this scope
   if (millis == GRPC_MILLIS_INF_FUTURE) return -1;
                 ^
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_epollsig_linux.h:22,
                 from src/core/lib/iomgr/ev_epollsig_linux.cc:27:
src/core/lib/iomgr/ev_epollsig_linux.cc: In function ???nt poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)??:
src/core/lib/iomgr/ev_epollsig_linux.cc:1101:17: error: ???NTPTR_MAX?? was not declared in this scope
   if (millis == GRPC_MILLIS_INF_FUTURE) return -1;
                 ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_epollex_linux.o] Error 1
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_epollsig_linux.o] Error 1
make64[2]: *** [third_party/grpc/src/extern_grpc-stamp/extern_grpc-build] Error 2
make64[1]: *** [CMakeFiles/extern_grpc.dir/all] Error 2
make64: *** [all] Error 2
(paddle.c_api) [lizhipeng@cp01-lizhipeng02-linux build]$ make
/usr/bin/make64 MAC=64
[  1%] Built target zlib
[  2%] Built target extern_protobuf
[  2%] Performing build step for 'extern_grpc'
/usr/bin/make64 MAC=64 HAS_SYSTEM_PROTOBUF=false -s -j8 static grpc_cpp_plugin
Package libcares was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcares.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcares' found
Package libcares was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcares.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcares' found
[MAKE]    Generating cache.mk
[CXX]     Compiling src/core/lib/support/time.cc
[CXX]     Compiling src/core/lib/support/time_posix.cc
[CXX]     Compiling src/core/lib/iomgr/error.cc
[CXX]     Compiling src/core/lib/iomgr/ev_epoll1_linux.cc
[CXX]     Compiling src/core/lib/iomgr/ev_epollex_linux.cc
[CXX]     Compiling src/core/lib/iomgr/ev_epollsig_linux.cc
[CXX]     Compiling src/core/lib/iomgr/ev_poll_posix.cc
[CXX]     Compiling src/core/lib/iomgr/exec_ctx.cc
In file included from src/core/lib/support/time_posix.cc:29:0:
src/core/lib/support/time_posix.cc: In function ???imespec timespec_from_gpr(gpr_timespec)??:
src/core/lib/support/time_posix.cc:36:30: error: ???NT32_MAX?? was not declared in this scope
     GPR_ASSERT(gts.tv_sec <= INT32_MAX && gts.tv_sec >= INT32_MIN);
                              ^
include/grpc/support/log.h:93:11: note: in definition of macro ???PR_ASSERT??
     if (!(x)) {                                       \
           ^
src/core/lib/support/time_posix.cc:36:57: error: ???NT32_MIN?? was not declared in this scope
     GPR_ASSERT(gts.tv_sec <= INT32_MAX && gts.tv_sec >= INT32_MIN);
                                                         ^
include/grpc/support/log.h:93:11: note: in definition of macro ???PR_ASSERT??
     if (!(x)) {                                       \
           ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/support/time_posix.o] Error 1
make64[3]: *** Waiting for unfinished jobs....
src/core/lib/support/time.cc: In function ???nt gpr_time_cmp(gpr_timespec, gpr_timespec)??:
src/core/lib/support/time.cc:30:31: error: ???NT64_MAX?? was not declared in this scope
   if (cmp == 0 && a.tv_sec != INT64_MAX && a.tv_sec != INT64_MIN) {
                               ^
src/core/lib/support/time.cc:30:56: error: ???NT64_MIN?? was not declared in this scope
   if (cmp == 0 && a.tv_sec != INT64_MAX && a.tv_sec != INT64_MIN) {
                                                        ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_inf_future(gpr_clock_type)??:
src/core/lib/support/time.cc:54:16: error: ???NT64_MAX?? was not declared in this scope
   out.tv_sec = INT64_MAX;
                ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_inf_past(gpr_clock_type)??:
src/core/lib/support/time.cc:62:16: error: ???NT64_MIN?? was not declared in this scope
   out.tv_sec = INT64_MIN;
                ^
src/core/lib/support/time.cc: In function ???pr_timespec to_seconds_from_sub_second_time(int64_t, int64_t, gpr_clock_type)??:
src/core/lib/support/time.cc:72:24: error: ???NT64_MAX?? was not declared in this scope
   if (time_in_units == INT64_MAX) {
                        ^
src/core/lib/support/time.cc:74:31: error: ???NT64_MIN?? was not declared in this scope
   } else if (time_in_units == INT64_MIN) {
                               ^
src/core/lib/support/time.cc: In function ???pr_timespec to_seconds_from_above_second_time(int64_t, int64_t, gpr_clock_type)??:
src/core/lib/support/time.cc:95:24: error: ???NT64_MAX?? was not declared in this scope
   if (time_in_units >= INT64_MAX / secs_per_unit) {
                        ^
src/core/lib/support/time.cc:97:31: error: ???NT64_MIN?? was not declared in this scope
   } else if (time_in_units <= INT64_MIN / secs_per_unit) {
                               ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_time_add(gpr_timespec, gpr_timespec)??:
src/core/lib/support/time.cc:141:19: error: ???NT64_MAX?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                   ^
src/core/lib/support/time.cc:141:44: error: ???NT64_MIN?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                                            ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_time_sub(gpr_timespec, gpr_timespec)??:
src/core/lib/support/time.cc:174:19: error: ???NT64_MAX?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                   ^
src/core/lib/support/time.cc:174:44: error: ???NT64_MIN?? was not declared in this scope
   if (a.tv_sec == INT64_MAX || a.tv_sec == INT64_MIN) {
                                            ^
src/core/lib/support/time.cc: In function ???pr_timespec gpr_convert_clock_type(gpr_timespec, gpr_clock_type)??:
src/core/lib/support/time.cc:232:19: error: ???NT64_MAX?? was not declared in this scope
   if (t.tv_sec == INT64_MAX || t.tv_sec == INT64_MIN) {
                   ^
src/core/lib/support/time.cc:232:44: error: ???NT64_MIN?? was not declared in this scope
   if (t.tv_sec == INT64_MAX || t.tv_sec == INT64_MIN) {
                                            ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/support/time.o] Error 1
src/core/lib/iomgr/error.cc: In function ???oid unref_errs(grpc_error*)??:
src/core/lib/iomgr/error.cc:150:18: error: ???INT8_MAX?? was not declared in this scope
   while (slot != UINT8_MAX) {
                  ^
src/core/lib/iomgr/error.cc: In function ???oid unref_strs(grpc_error*)??:
src/core/lib/iomgr/error.cc:168:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
In file included from src/core/lib/iomgr/error.cc:29:0:
src/core/lib/iomgr/error.cc: In function ???int8_t get_placement(grpc_error**, size_t)??:
src/core/lib/iomgr/error.cc:208:26: error: ???INT8_MAX?? was not declared in this scope
         (uint8_t)GPR_MIN(UINT8_MAX - 1, (3 * (*err)->arena_capacity / 2));
                          ^
include/grpc/support/useful.h:24:25: note: in definition of macro ???PR_MIN??
 #define GPR_MIN(a, b) ((a) < (b) ? (a) : (b))
                         ^
src/core/lib/iomgr/error.cc: In function ???oid internal_set_int(grpc_error**, grpc_error_ints, intptr_t)??:
src/core/lib/iomgr/error.cc:233:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot == UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid internal_set_str(grpc_error**, grpc_error_strs, grpc_slice)??:
src/core/lib/iomgr/error.cc:248:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot == UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid internal_set_time(grpc_error**, grpc_error_times, gpr_timespec)??:
src/core/lib/iomgr/error.cc:268:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot == UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid internal_add_error(grpc_error**, grpc_error*)??:
src/core/lib/iomgr/error.cc:283:42: error: ???INT8_MAX?? was not declared in this scope
   grpc_linked_error new_last = {new_err, UINT8_MAX};
                                          ^
src/core/lib/iomgr/error.cc: In function ???rpc_error* grpc_error_create(const char*, int, grpc_slice, grpc_error**, size_t)??:
src/core/lib/iomgr/error.cc:338:20: error: ???INT8_MAX?? was not declared in this scope
   err->first_err = UINT8_MAX;
                    ^
src/core/lib/iomgr/error.cc: In function ???oid ref_strs(grpc_error*)??:
src/core/lib/iomgr/error.cc:369:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid ref_errs(grpc_error*)??:
src/core/lib/iomgr/error.cc:377:18: error: ???INT8_MAX?? was not declared in this scope
   while (slot != UINT8_MAX) {
                  ^
src/core/lib/iomgr/error.cc: In function ???ool grpc_error_get_int(grpc_error*, grpc_error_ints, intptr_t*)??:
src/core/lib/iomgr/error.cc:469:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot != UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???ool grpc_error_get_str(grpc_error*, grpc_error_strs, grpc_slice*)??:
src/core/lib/iomgr/error.cc:501:15: error: ???INT8_MAX?? was not declared in this scope
   if (slot != UINT8_MAX) {
               ^
src/core/lib/iomgr/error.cc: In function ???oid collect_ints_kvs(grpc_error*, kv_pairs*)??:
src/core/lib/iomgr/error.cc:608:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid collect_strs_kvs(grpc_error*, kv_pairs*)??:
src/core/lib/iomgr/error.cc:632:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid collect_times_kvs(grpc_error*, kv_pairs*)??:
src/core/lib/iomgr/error.cc:667:17: error: ???INT8_MAX?? was not declared in this scope
     if (slot != UINT8_MAX) {
                 ^
src/core/lib/iomgr/error.cc: In function ???oid add_errs(grpc_error*, char**, size_t*, size_t*)??:
src/core/lib/iomgr/error.cc:677:18: error: ???INT8_MAX?? was not declared in this scope
   while (slot != UINT8_MAX) {
                  ^
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_poll_posix.h:22,
                 from src/core/lib/iomgr/ev_poll_posix.cc:23:
src/core/lib/iomgr/ev_poll_posix.cc: In function ???nt poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)??:
src/core/lib/iomgr/ev_poll_posix.cc:1127:19: error: ???NTPTR_MAX?? was not declared in this scope
   if (deadline == GRPC_MILLIS_INF_FUTURE) return -1;
                   ^
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/iomgr/exec_ctx.h:22,
                 from src/core/lib/iomgr/exec_ctx.cc:19:
src/core/lib/iomgr/exec_ctx.cc: In function ???pr_atm timespec_to_atm_round_down(gpr_timespec)??:
src/core/lib/iomgr/exec_ctx.cc:120:11: error: ???NTPTR_MAX?? was not declared in this scope
   if (x > GPR_ATM_MAX) return GPR_ATM_MAX;
           ^
src/core/lib/iomgr/exec_ctx.cc: In function ???pr_atm timespec_to_atm_round_up(gpr_timespec)??:
src/core/lib/iomgr/exec_ctx.cc:130:11: error: ???NTPTR_MAX?? was not declared in this scope
   if (x > GPR_ATM_MAX) return GPR_ATM_MAX;
           ^
src/core/lib/iomgr/exec_ctx.cc: In function ???pr_timespec grpc_millis_to_timespec(grpc_millis, gpr_clock_type)??:
src/core/lib/iomgr/exec_ctx.cc:150:17: error: ???NTPTR_MAX?? was not declared in this scope
   if (millis == GRPC_MILLIS_INF_FUTURE) {
                 ^
src/core/lib/iomgr/exec_ctx.cc:153:17: error: ???NTPTR_MIN?? was not declared in this scope
   if (millis == GRPC_MILLIS_INF_PAST) {
                 ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/exec_ctx.o] Error 1
src/core/lib/iomgr/error.cc: In function ???onst char* grpc_error_string(grpc_error*)??:
src/core/lib/iomgr/error.cc:746:25: error: ???INT8_MAX?? was not declared in this scope
   if (err->first_err != UINT8_MAX) {
                         ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_poll_posix.o] Error 1
src/core/lib/iomgr/error.cc: In function ???ool grpc_error_get_str(grpc_error*, grpc_error_strs, grpc_slice*)??:
src/core/lib/iomgr/error.cc:507:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/error.o] Error 1
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
   if (err->first_err != UINT8_MAX) {
                         ^
src/core/lib/iomgr/error.cc: In function ‘bool grpc_error_get_str(grpc_error*, grpc_error_strs, grpc_slice*)’:
src/core/lib/iomgr/error.cc:507:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/error.o] Error 1
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_epollex_linux.o] Error 1
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_epollsig_linux.h:22,
                 from src/core/lib/iomgr/ev_epollsig_linux.cc:27:
src/core/lib/iomgr/ev_epollsig_linux.cc: In function ‘int poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)’:
src/core/lib/iomgr/ev_epollsig_linux.cc:1101:17: error: ‘INTPTR_MAX’ was not declared in this scope
   if (millis == GRPC_MILLIS_INF_FUTURE) return -1;
                 ^
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_poll_posix.h:22,
                 from src/core/lib/iomgr/ev_poll_posix.cc:23:
src/core/lib/iomgr/ev_poll_posix.cc: In function ‘int poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)’:
src/core/lib/iomgr/ev_poll_posix.cc:1127:19: error: ‘INTPTR_MAX’ was not declared in this scope
   if (deadline == GRPC_MILLIS_INF_FUTURE) return -1;
                   ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_epollsig_linux.o] Error 1
In file included from include/grpc/impl/codegen/atm.h:73:0,
                 from include/grpc/support/atm.h:22,
                 from ./src/core/lib/debug/trace.h:22,
                 from ./src/core/lib/iomgr/ev_posix.h:24,
                 from ./src/core/lib/iomgr/ev_epoll1_linux.h:22,
                 from src/core/lib/iomgr/ev_epoll1_linux.cc:25:
src/core/lib/iomgr/ev_epoll1_linux.cc: In function ‘int poll_deadline_to_millis_timeout(grpc_exec_ctx*, grpc_millis)’:
src/core/lib/iomgr/ev_epoll1_linux.cc:570:17: error: ‘INTPTR_MAX’ was not declared in this scope
   if (millis == GRPC_MILLIS_INF_FUTURE) return -1;
                 ^
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_poll_posix.o] Error 1
make64[3]: *** [/home/lizhipeng/tools/paddle.c_api/Paddle/build/third_party/grpc/src/extern_grpc/objs/opt/src/core/lib/iomgr/ev_epoll1_linux.o] Error 1
make64[2]: *** [third_party/grpc/src/extern_grpc-stamp/extern_grpc-build] Error 2
make64[1]: *** [CMakeFiles/extern_grpc.dir/all] Error 2
make64: *** [all] Error 2

**Comment by ncteisen** [comment]
Please give more information. Machine, Version, OS, etc etc. See our issue template for relevant info

**Comment by AspirinSJL** [comment]
Closing this because of no reporter response.
