### ISSUE TITLE
Official Wireshark gRPC dissector 

### ISSUE THREAD

**Issue by ndandanov** [grpc/grpc#13586]
Dear All,

*This is a repost of a comment in a protobuf issue located here, as requested by @xfxyjwf:
https://github.com/google/protobuf/issues/3303*

I found out, that in the official Wireshark repo on GitHub, there is a gRPC dissector - namely the *wireshark/epan/dissectors/packet-grpc.c* located here: https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-grpc.c

**In this comment, I will try to summarize how I got it to work with actual gRPC packets.**
The following two videos show how I tried to repeat the same steps under Ubuntu 16.04, however with a slightly newer development version of Wireshark. The end result was not as functional as described below, but I think this would be a nice introduction on the topic.

**gRPC Wireshark dissector - Part 1: https://youtu.be/LoGArC58Row**
**gRPC Wireshark dissector - Part 2: https://youtu.be/Wj9VoJQf-qc**

It seems that the gRPC dissector was officially added in the end of September this year:
https://github.com/wireshark/wireshark/commits/master/epan/dissectors/packet-grpc.c

*Note that the original Wireshark repo is located on their website. Please check https://www.wireshark.org/develop.html.*

I opted to see how this dissector is working and cloned the Wireshark repo:
```
git clone https://code.wireshark.org/review/wireshark
```

My system is a 64-bit Arch Linux, so I built Wireshark with the following commands:

```
./autogen.sh 
./configure 
make
```
(using this as a reference: https://www.wireshark.org/docs/wsdg_html_chunked/ChSrcBuildFirstTime.html)

It took around 20-30 minutes to build. The Wireshark version is:
![screenshot_2017-11-30_17-09-00](https://user-images.githubusercontent.com/17270267/33437663-5337f27c-d5f1-11e7-9197-6869b0e6e1b3.png)

I then ran it as `root` (in order to be able to capture any traffic) and started capturing the loopback interface.

I cloned, built and started the official gRPC `hello world` server and client from the grpc-java repo:
https://github.com/grpc/grpc-java/tree/master/examples

The console outputs are, as expected:
![screenshot_2017-11-30_16-38-16](https://user-images.githubusercontent.com/17270267/33437171-c5d39982-d5ef-11e7-8edc-d77c72b72e8f.png)

The captured packets in Wireshark are:
![screenshot_2017-11-30_16-39-16](https://user-images.githubusercontent.com/17270267/33437212-e490d52e-d5ef-11e7-9df5-ef71e814774d.png)

You can download the .pcapng file from my repo:
https://github.com/ndandanov/wireshark-grpc/blob/master/grpc-hello-world.pcapng

Here you can see that they are decoded as TCP packets.

I clicked with the right mouse button on a packet and selected `Decode As...`:
![screenshot_2017-11-30_16-39-39-1](https://user-images.githubusercontent.com/17270267/33437237-fc74da3c-d5ef-11e7-800a-c73dcdf9dc1b.png)

And configured the packets as HTTP2:
![screenshot_2017-11-30_16-40-24](https://user-images.githubusercontent.com/17270267/33437305-2dcb4ada-d5f0-11e7-9493-74ab70197933.png)

And the packets are now correctly recognized as either HTTP2 or gRPC:
![screenshot_2017-11-30_16-40-37](https://user-images.githubusercontent.com/17270267/33437328-40904cb0-d5f0-11e7-8534-e712ef73ac73.png)

Let's take a look at the packet which carries the actual gRPC `hello world` request: 
![screenshot_2017-11-30_16-45-49](https://user-images.githubusercontent.com/17270267/33437346-50059826-d5f0-11e7-981f-9b7b62757d8c.png)

I had also opened the `.proto` file (located here https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/helloworld.proto) for reference.

The actual value of field 1 from the `message HelloRequest`, which is `string name`, is "world" (or 77 6f 72 6c 64 in hex):

![screenshot_2017-11-30_16-49-54](https://user-images.githubusercontent.com/17270267/33437430-8ff506d8-d5f0-11e7-8c1c-e5853acafa0d.png)

And we can verify this:
![screenshot_2017-11-30_16-49-39](https://user-images.githubusercontent.com/17270267/33437477-c1a6f48e-d5f0-11e7-9582-6953704f26ab.png)

The gRPC `hello world` response was of course "Hello world":
![screenshot_2017-11-30_16-50-18](https://user-images.githubusercontent.com/17270267/33437502-d0d1bbf6-d5f0-11e7-94f4-f6bdf06fb4cf.png)

The Wireshark interpretation of fields and their values could definitely be extended. I did not come across any option to specify and input `.proto` file to extract the field names and correct value types. This leads to some `double`s represented as just `uint64` in Wireshark.

Nevertheless, I think this is a significant improvement in the right direction.

Please share your opinion on this dissector. Has anyone else tried it and published some results/improvements?
Is there any public information regarding the release of this dissector?
Kind regards!

**Comment by xfxyjwf** [comment]
@jtattermusch Do we have any place to host user contributed documentation/guideline/tutorials like this? I asked @ndandanov to post it here because it's more about grpc than protobuf. It's neither a feature request nor a bug though.

**Comment by jtattermusch** [comment]
There are multiple places where this could go:
If formed as a a standalone article:
  1). a blogpost on https://grpc.io/blog/
  2). a "guide" on grpc.io site directly

If accompanied by code, code examples, scripts etc. in addition to the text:
  1.) we could host this as one of the projects under https://github.com/grpc-ecosystem organization

IMHO I think hosting on grpc-ecosystem, makes the most sense as there seem to be at least build scripts involved. @ndandanov adding it to grpc-ecosystem would make sense if you wanted to spend time polishing the instructions and perhaps keep improving the tutorial over time.

CC @LisaFC  for grpc.io
CC @zinuga

**Comment by vCloudernBeer** [comment]
With the following install I was able to compile the the lastest dev version of Wireshark on my Ubuntu 16.04 virtaulbox (I was using vagrant):

sudo apt-get install build-essentials
sudo apt-get install libssl-dev libpcap-dev
sudo apt-get install build-essential checkinstall
sudo apt-get install automake libtool
sudo apt-get install pkg-config
sudo apt-get install libtool-bin
sudo apt-get install bison
sudo apt-get install flex
sudo apt-get install libgcrypt11 libgcrypt11-dev
sudo apt-get install -y libgcrypt11-dev
sudo apt-get install libglib2.0-dev
sudo apt-get install libgtk2.0-dev
sudo apt-get install qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools qtmultimedia5-dev libqt5svg5-dev

**Comment by yyh-graphsql** [comment]
@ndandanov I have two questions.

1. For this dissector, it seems it doesn't support large GRPC messages that bigger than the TCP packet limit.
2. In [this](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) link, it says the GRPC response is in the format of "Response → (Response-Headers *Length-Prefixed-Message Trailers) / Trailers-Only". I wonder why the response Wireshark dissected doesn't contain DATA frames.

Thanks,
Yihao

**Comment by jtattermusch** [comment]
@ndandanov   thanks for sharing the guide on how to use wireshark with gRPC, it's very useful material. 
Nevertheless, as an "issue" it is slightly misplaced - an ideal form for this would be to write a blogpost (e.g. we'd be happy to accept an article for https://grpc.io/blog/)

I'll close this item because it's not really about an issue with grpc codebase.
