### ISSUE TITLE
gRPC references old protobuf submodule version

### ISSUE THREAD

**Issue by gwihlidal** [grpc/grpc#13589]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 
v1.7.2 C++
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 gcc7

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Cloned fresh 1.7.2 branch locally, compiled it (using built in protobuf third party submodule), and then attempted to build my app against this version (using pregenerated protobuf headers with the protoc 3.5 compiler).
 
### What did you expect to see?
 
My app to compile :) It would be great to have the .gitmodules file updated to the recent protobuf versions (especially so they match what vcpkg is set to, i.e. gRPC 1.7 and protobuf 3.5)
 
### What did you see instead?

The current outdated third party protobuf submodule causes compile errors because the submodule for protobuf within gRPC is old (i.e. v3.0-3.4 even for branches like 1.7 or 1.8).
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
/app/halcyon/Proto/proto/google/api/annotations.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
In file included from /app/halcyon/Proto/proto/google/api/annotations.pb.h:30:0,
                 from /app/halcyon/Proto/proto/AssetService.pb.h:32,
                 from /app/halcyon/Proto/proto/AssetService.grpc.pb.cc:5:
/app/halcyon/Proto/proto/./google/api/http.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
/app/halcyon/Proto/proto/./google/api/http.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
/app/halcyon/Proto/proto/./google/api/http.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
In file included from /app/halcyon/Proto/proto/google/api/annotations.pb.h:30:0,
                 from /app/halcyon/Proto/proto/AssetService.pb.h:32,
                 from /app/halcyon/Proto/proto/AssetService.grpc.pb.cc:5:
/app/halcyon/Proto/proto/./google/api/http.pb.h: In member function 'google::api::CustomHttpPattern* google::api::HttpRule::release_custom()':
/app/halcyon/Proto/proto/./google/api/http.pb.h:1454:44: error: 'DuplicateIfNonNull' is not a member of 'google::protobuf::internal'
       temp = ::google::protobuf::internal::DuplicateIfNonNull(temp, NULL);
```

**Comment by mehrdada** [comment]
The 1.8.x branch which will be released soon pulls in protobuf 3.5.0. 

However, gRPC and protobuf at runtime are mostly independent at runtime. The submodule mainly influences the gRPC protoc plugin that gets built. If you generate your pb2 files with a newer protoc version, you can simply link your app to a newer protobuf runtime library and it should work. Is there a reason that would not be satisfactory for your use case?
