### ISSUE TITLE
-Wsign-conversion error when building with Clang 6.0

### ISSUE THREAD

**Issue by cmtice** [grpc/grpc#13597]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker? Yes
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Clang 6.0
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

x86_64-pc-linux-gnu-clang -pthread  -Ithird_party/googletest/googletest/include  -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -O2 -fPIC -I. -Iinclude -I/var/tmp/portage/dev-libs/grpc-1.3.0-r1/work/grpc-1.3.0/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr\"     -DTSI_OPENSSL_ALPN_SUPPORT=0 -O2 -pipe -std=c99 -Wsign-conversion -Wconversion -Wshadow -Wextra-semi   -MMD -MF /var/tmp/portage/dev-libs/grpc-1.3.0-r1/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.dep -c -o /var/tmp/portage/dev-libs/grpc-1.3.0-r1/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.o src/core/lib/channel/channel_args.c 

### What did you expect to see?
 
The file compiled.

 
### What did you see instead?

 src/core/lib/channel/channel_args.c:228:23: error: implicit conversion changes signedness:
      'grpc_compression_algorithm' to 'int' [-Werror,-Wsign-conversion]
  tmp.value.integer = algorithm;
                    ~ ^~~~~~~~~
1 error generated.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ncteisen** [comment]
What was your command line for compiling?

**Comment by cmtice** [comment]
x86_64-pc-linux-gnu-clang -pthread
-Ithird_party/googletest/googletest/include  -g -Wall -Wextra -Werror
-Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -O2 -fPIC -I.
-Iinclude -I/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/gens
-DNDEBUG -DINSTALL_PREFIX=\"/usr\"     -DTSI_OPENSSL_ALPN_SUPPORT=0 -O2
-pipe -std=c99 -Wsign-conversion -Wconversion -Wshadow -Wextra-semi   -MMD
-MF
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.dep
-c -o
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.o
src/core/lib/channel/channel_args.c

Applying -v & -save-temps to get the .i file & command line;

 "/usr/bin/clang-6.0" -cc1 -triple x86_64-pc-linux-gnu -emit-llvm-bc
-emit-llvm-uselists -disable-free -main-file-name channel_args.c
-mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno
-masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array
-target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited
-dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -v
-coverage-notes-file
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.gcno
-resource-dir /usr/lib64/clang/6.0.0 -O2 -Wno-tautological-constant-compare
-Wno-unused-local-typedefs -Wno-tautological-unsigned-enum-zero-compare
-Wno-unknown-warning-option -Wno-deprecated-declarations -Wall -Wextra
-Werror -Wno-long-long -Wno-unused-parameter -Wsign-conversion -Wconversion
-Wshadow -Wextra-semi -std=c99 -fdebug-compilation-dir
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0 -ferror-limit 19
-fmessage-length 82 -pthread -fobjc-runtime=gcc -fdiagnostics-show-option
-fcolor-diagnostics -vectorize-loops -vectorize-slp -disable-llvm-passes -o
channel_args.bc -x cpp-output channel_args.i -dwarf-debug-flags
"/usr/bin/clang-6.0 -Qunused-arguments -grecord-gcc-switches
-Wno-tautological-constant-compare -Wno-unused-local-typedefs
-Wno-tautological-unsigned-enum-zero-compare -Wno-unknown-warning-option
-Wno-deprecated-declarations -pthread -I
third_party/googletest/googletest/include -g -Wall -Wextra -Werror
-Wno-long-long -Wno-unused-parameter -D OSATOMIC_USE_INLINED=1 -O2 -fPIC -I
. -I include -I
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/gens -D NDEBUG -D
INSTALL_PREFIX=\"/usr\" -D TSI_OPENSSL_ALPN_SUPPORT=0 -O2 -pipe -std=c99
-Wsign-conversion -Wconversion -Wshadow -Wextra-semi -MMD -MF
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.dep
-c -o
/var/tmp/portage/dev-libs/grpc-1.3.0-r2/work/grpc-1.3.0/objs/opt/src/core/lib/channel/channel_args.o
src/core/lib/channel/channel_args.c -v -save-temps=cwd"

I'll attach the .i file to this email.  Also, fyi, the version of clang we
are using;

 $ /usr/bin/clang-6.0 --version
Chromium OS 6.0_pre316199_p20171105-r1 clang version 6.0.0
(/var/cache/chromeos-cache/distfiles/host/egit-src/clang.git
4d085086c74a8fbce197f61548f488a63f300933)
(/var/cache/chromeos-cache/distfiles/host/egit-src/llvm.git
66af8bde13a515b8d0fa76201f0d5b428187fd13) (based on LLVM 6.0.0svn)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

It's based on r317203.





-- Caroline
cmtice@google.com

**Comment by cmtice** [comment]
[channel_args.i.txt](https://github.com/grpc/grpc/files/1549228/channel_args.i.txt)

Previous attempt to attach channel_args.i failed.  Renamed it to 'channel_args.i.txt' and attached it here.

**Comment by ncteisen** [comment]
Added a cast to fix in #13714

**Comment by ncteisen** [comment]
For what reason are you using v1.3? Can you try HEAD? We have a policy against backporting fixes to such old versions (I just learned this).

Please re open if this occurs against a more current version
