### ISSUE TITLE
Please document disadvantages to unsecurity

### ISSUE THREAD

**Issue by jart** [grpc/grpc#13590]
I noticed TensorFlow depends on `@grpc//:grpc++_unsecure` via `//external:grpc_lib` so I tried to figure out why the build label says we are insecure. It seems a design decision was made to allow the user to swap out the definitions of [init_unsecure.cc](https://github.com/grpc/grpc/blob/44c143c587c219ddae4ec3dbce003c0bd6c6c9e6/src/core/lib/surface/init_unsecure.cc) (see also [init.h](https://github.com/grpc/grpc/blob/44c143c587c219ddae4ec3dbce003c0bd6c6c9e6/src/core/lib/surface/init.h)) at build time. If the gRPC authors consider it insecure to not define those functions, maybe they should be documented.

**Comment by vjpai** [comment]
`unsecure` literally means that there will be no security linked in. I don't know the history of why TF chose `grpc++_unsecure`, but the difference will be that you can't use secure credentials as a result. It's not that the function is insecure; it's that there's simply no security included in the library if you choose this option.

**Comment by jart** [comment]
The docs should ideally communicate why the user would want to go to the effort of defining a security module. For example, do I need a security module if I'm a small business and I have two gRPC endpoints talking to each other over a LAN switch I own, locked down behind a firewall? If my API does authentication, then is the only disadvantage that I can't have TLS encryption over the network?

**Comment by vjpai** [comment]
So there are two separate issues, IMO:

1. whether or not to use security, auth, etc
    - This is clearly application-dependent but I think our de facto recommendation is to always use some form of authentication and encryption to avoid shooting oneself in the foot, although we allow the use of insecure RPCs. Insecure RPCs are probably only justified if the application really needs bleeding edge performance and the environment already provides security in some other fashion. @jtattermusch: Issue for doc fixit?
1. why to build with `_unsecure` version of the library
    - This rules out the chance of using secure RPCs altogether. It seems like the only projects that are building with `_unsecure` in the wild are Tensorflow and Chromium (and their derivatives). Based on (at least) tensorflow/tensorflow#14039, I assume that this decision is motivated largely by portability to platforms that don't support the SSL libraries that gRPC supports. If this isn't a concern, then I can't see a reason to use `_unsecure` versions of the library; even if you only want to use insecure RPCs, there is no performance advantage of the regular version.

I'll assign to @jtattermusch for triage.
