### ISSUE TITLE
Broken bazel test: //test/core/bad_ssl:bad_ssl_alpn_server

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13606]
See https://source.cloud.google.com/results/invocation/05f9065e-93e5-4b35-ad1f-ab6bfa8b383a/targets/%2F%2Ftest%2Fcore%2Fbad_ssl:bad_ssl_alpn_server?page=log

**Comment by jtattermusch** [comment]
-----------------------------------------------------------------------------
E1130 00:36:49.532112844      17 server_common.cc:42]        assertion failed: addr
Aborted (core dumped)

**Comment by adelez** [comment]
I think this is the same as #13607
