### ISSUE TITLE
Pick an end-of-2.7-support date.

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#13602]
After almost ten long years, Python 3 has finally won. Hooray!

[Everyone else is picking dates for when they will drop support for Python 2](https://pythonclock.org); we should as well.

I'm thinking 2020-01-01, which is just over twenty-four months away. 2020 sounds like it's in the future, but it's not nearly as far in the future as once it was.

If you're still using Python 2: **start making your plan to migrate to Python 3 and executing that plan now**.

**Comment by nathanielmanistaatgoogle** [comment]
**Important update:** [upstream Python has chosen 2020-01-01](https://github.com/python/peps/commit/3e781ca99a6c282d481b6d9a71d5b7e3a1aef314). I strongly feel that that's the latest date that we should choose.

... and it's now less than twenty-four months away.

**Comment by nathanielmanistaatgoogle** [comment]
[Today we make it official: 2020-01-01](https://groups.google.com/forum/#!topic/grpc-io/psLfi-li4u8). If you're not already working on upgrading off of Python 2.7, get started yesterday!

**Comment by nicolasnoble** [comment]
Do we want to make this part of some documentation inside of the gRPC repository itself ?

**Comment by nicolasnoble** [comment]
Or even better: should we have a warning or something inside of the gRPC python code that would be displayed once per process that the python2.7 support will fully end at that date and that no further releases will happen past it ?

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble: yes, I think, to both. The documentation can go up any time but my first instinct about a warning in the code itself is for it to go live on 2019-07-01.

**Comment by nicolasnoble** [comment]
Should we make it an awkward `if currentdate > 2019-07-01... ` ? That's a bit timebomby, but harmless.

**Comment by nathanielmanistaatgoogle** [comment]
I'm open to that, sure.
