### ISSUE TITLE
Flake: AsyncEnd2endTest SimpleRpc/8

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13626]
bins/dbg/async_end2end_test --gtest_filter=AsyncEnd2end/AsyncEnd2endTest.SimpleRpc/8  GRPC_POLL_STRATEGY=poll

https://sponge.corp.google.com/target?id=df469c78-44ca-4f98-8637-2169c01137e5&target=grpc/ubuntu/pull_request/grpc_basictests_cpp_dbg&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment]
Not seen since 2017-12-15
