### ISSUE TITLE
Broken bazel test: //test/cpp/naming:resolver_component_tests_runner

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13620]
```
++ echo ''
++ cut -d = -f 2
++ grep '\--test_bin_path='
+ FLAGS_test_bin_path=
++ echo ''
++ cut -d = -f 2
++ grep '\--dns_server_bin_path='
+ FLAGS_dns_server_bin_path=
++ echo ''
++ cut -d = -f 2
++ grep '\--records_config_path='
+ FLAGS_records_config_path=
++ echo ''
++ cut -d = -f 2
++ grep '\--test_dns_server_port='
+ FLAGS_test_dns_server_port=
+ for cmd_arg in '"$FLAGS_test_bin_path"' '"$FLAGS_dns_server_bin_path"' '"$FLAGS_records_config_path"' '"$FLAGS_test_dns_server_port"'
+ [[ '' == '' ]]
+ echo 'Missing a CMD arg'
Missing a CMD arg
+ exit 1
```

https://source.cloud.google.com/results/invocation/05f9065e-93e5-4b35-ad1f-ab6bfa8b383a/targets/%2F%2Ftest%2Fcpp%2Fnaming:resolver_component_tests_runner?page=log

**Comment by adelez** [comment]
resolver_component_tests_runner is a grpc_sh_binary. But grpc_sh_binary was strangely defined as sh_test https://github.com/grpc/grpc/blob/69d3e0984da394d1ea06edbe26de76d124c6eaf3/bazel/grpc_build_system.bzl#L160

Either don't make it an sh_test or create a flag for skipping it.

**Comment by adelez** [comment]
This a grpc_sh_binary but grpc_sh_binary is strangely defined as sh_test: https://github.com/grpc/grpc/blob/69d3e0984da394d1ea06edbe26de76d124c6eaf3/bazel/grpc_build_system.bzl#L161

Should be something else.
