### ISSUE TITLE
npm install grpc error

### ISSUE THREAD

**Issue by yu-pu** [grpc/grpc#13624]
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! grpc@1.7.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.7.2 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

**Comment by mixolydian251** [comment]
Did you find a solution to this? I ran into the same thing while trying to create a docker image with `node:8-alpine` `FROM` image. I noticed that the standard `node` docker image worked fine.

**Comment by StefanStokic** [comment]
Anyone found a solution to this?

**Comment by praveenpds** [comment]
tried set NODE_TLS_REJECT_UNAUTHORIZED=0 and its working fine

**Comment by mixolydian251** [comment]
Ran into the same issue this morning. Looks like the precompiled grpc1.7.2 hasn't been uploaded for musl based distributions (alpine is musl vs glibc)

For the short term, to get your build going again, and until they upload the precompiled versions, try adding this to your dockerfile

    RUN apk update && apk upgrade && \
    apk add --no-cache python make g++
python, make and g++ basically allow node-gyp to compile from source rather than relying on the precompiled versions
