### ISSUE TITLE
gRPC client does not unblock when server becomes unreachable

### ISSUE THREAD

**Issue by csenanda** [grpc/grpc#13656]
I am using grpc v1.0.0
Here is how my code goes

ClientContext context;
std::unique_ptrConsumer::Stub stub_ = Consumer::NewStub(channel);
ThreadEventReader = stub_->GetDataStream(&context, Filter); //streaming rpc call
// blocked read - until stream closed
while (ThreadEventReader->Read(&StreamedData))
{
cout << "UpdateStream: " << StreamedData.displayvalue() << endl;
}

If the connection to the server drops out, the thread gets blocked in Read indefinitely.
Its easy to reproduce consistently if the server is a remote node. Let me know if you need additional info.

**Comment by sreecha** [comment]
Are you using grpc's c++ API ? 
(The `ThreadEventReader` data type and the `GetDataStream` function you used in the code aren't part of the API )

**Comment by csenanda** [comment]
Yes it is C++ api.
ThreadEventReader is a tyoedef of ClientReader.
GetDataStram is a server side streaming RPC call.

**Comment by sreecha** [comment]
The RPC should have a deadlibe. Otherwise, it will block until tcp detects that the connection is broken (which can take a long time) .. especially when all you are doing is a read on that channel (and no writes).

**Comment by sreecha** [comment]
I.e in other words, this behavior is by design
