### ISSUE TITLE
tools/run_tests/helper_scripts/run_grpc-node.sh broken on both macos and linux

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13669]
This has started failing again today. See [this screenshot](https://screenshot.googleplex.com/XXSFzzDPAYm) for the ids of the first builds showing the failure.

Examples:
mac: https://sponge.corp.google.com/target?id=511291bf-4324-493f-b774-ebabd97c3d7d&target=github/grpc/grpc-node_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

linux: https://sponge.corp.google.com/target?id=1da7eccd-d1c8-476d-ab6d-d47185cfb7bf&target=github/grpc/grpc-node_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
seems fixed.
