### ISSUE TITLE
FLAKE: tsan test json_run_localhost:cpp_protobuf_async_unary_75Kqps_600channel_60Krpcs_300Breq_50Bresp_low_thread_count

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#13680]
https://sponge.corp.google.com/target?id=40acf87e-9ef5-4778-b5e0-ae11af5905bc&target=github/grpc/c%2B%2B_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

Failure
48.959486002    3187 report.cc:106]              SERVER[0].http2_initiate_write_due_to_flow_control_unstalled_by_update = 0
D1207 00:53:48.959492834    3187 report.cc:106]              SERVER[0].http2_initiate_write_due_to_application_ping = 0
D1207 00:53:48.959499459    3187 report.cc:106]              SERVER[0].http2_initiate_write_due_to_keepalive_ping = 0
D1207 00:53:48.959506214    3187 report.cc:106]              SERVER[0].http2_initiate_write_due_to_transport_flow_control_unstalled = 0
D1207 00:53:48.959512949    3187 report.cc:106]              SERVER[0].http2_initiate_write_due_to_ping_response = 397
D1207 00:53:48.959519561    3187 report.cc:106]              SERVER[0].http2_initiate_write_due_to_force_rst_stream = 0
D1207 00:53:48.959526165    3187 report.cc:106]              SERVER[0].http2_spurious_writes_begun = 0
D1207 00:53:48.959532776    3187 report.cc:106]              SERVER[0].hpack_recv_indexed = 104760
D1207 00:53:48.959539418    3187 report.cc:106]              SERVER[0].hpack_recv_lithdr_incidx = 0
D1207 00:53:48.959546105    3187 report.cc:106]              SERVER[0].hpack_recv_lithdr_incidx_v = 1152
D1207 00:53:48.959552722    3187 report.cc:106]              SERVER[0].hpack_recv_lithdr_notidx = 0
D1207 00:53:48.959559252    3187 report.cc:106]              SERVER[0].hpack_recv_lithdr_notidx_v = 0
D1207 00:53:48.959565800    3187 report.cc:106]              SERVER[0].hpack_recv_lithdr_nvridx = 0
D1207 00:53:48.959572317    3187 report.cc:106]              SERVER[0].hpack_recv_lithdr_nvridx_v = 0
D1207 00:53:48.959578802    3187 report.cc:106]              SERVER[0].hpack_recv_uncompressed = 2304
D1207 00:53:48.959585102    3187 report.cc:106]              SERVER[0].hpack_recv_huffman = 0
D1207 00:53:48.959591562    3187 report.cc:106]              SERVER[0].hpack_recv_binary = 0
D1207 00:53:48.959597982    3187 report.cc:106]              SERVER[0].hpack_recv_binary_base64 = 0
D1207 00:53:48.959604510    3187 report.cc:106]              SERVER[0].hpack_send_indexed = 58200
D1207 00:53:48.959610903    3187 report.cc:106]              SERVER[0].hpack_send_lithdr_incidx = 0
D1207 00:53:48.959617485    3187 report.cc:106]              SERVER[0].hpack_send_lithdr_incidx_v = 639
D1207 00:53:48.959623887    3187 report.cc:106]              SERVER[0].hpack_send_lithdr_notidx = 0
D1207 00:53:48.959630412    3187 report.cc:106]              SERVER[0].hpack_send_lithdr_notidx_v = 0
D1207 00:53:48.959636789    3187 report.cc:106]              SERVER[0].hpack_send_lithdr_nvridx = 0
D1207 00:53:48.959643159    3187 report.cc:106]              SERVER[0].hpack_send_lithdr_nvridx_v = 0
D1207 00:53:48.959649464    3187 report.cc:106]              SERVER[0].hpack_send_uncompressed = 1278
D1207 00:53:48.959655786    3187 report.cc:106]              SERVER[0].hpack_send_huffman = 0
D1207 00:53:48.959662002    3187 report.cc:106]              SERVER[0].hpack_send_binary = 0
D1207 00:53:48.959668383    3187 report.cc:106]              SERVER[0].hpack_send_binary_base64 = 0
D1207 00:53:48.959675014    3187 report.cc:106]              SERVER[0].combiner_locks_initiated = 58377
D1207 00:53:48.959684817    3187 report.cc:106]              SERVER[0].combiner_locks_scheduled_items = 93069
D1207 00:53:48.959691741    3187 report.cc:106]              SERVER[0].combiner_locks_scheduled_final_items = 13927
D1207 00:53:48.959698569    3187 report.cc:106]              SERVER[0].combiner_locks_offloaded = 0
D1207 00:53:48.959705176    3187 report.cc:106]              SERVER[0].call_combiner_locks_initiated = 94160
D1207 00:53:48.959711909    3187 report.cc:106]              SERVER[0].call_combiner_locks_scheduled_items = 117687
D1207 00:53:48.959718694    3187 report.cc:106]              SERVER[0].call_combiner_set_notify_on_cancel = 11767
D1207 00:53:48.959725309    3187 report.cc:106]              SERVER[0].call_combiner_cancelled = 0
D1207 00:53:48.959731896    3187 report.cc:106]              SERVER[0].executor_scheduled_short_items = 3
D1207 00:53:48.959738478    3187 report.cc:106]              SERVER[0].executor_scheduled_long_items = 0
D1207 00:53:48.959744971    3187 report.cc:106]              SERVER[0].executor_scheduled_to_self = 0
D1207 00:53:48.959751421    3187 report.cc:106]              SERVER[0].executor_wakeup_initiated = 3
D1207 00:53:48.959757883    3187 report.cc:106]              SERVER[0].executor_queue_drained = 3
D1207 00:53:48.959764360    3187 report.cc:106]              SERVER[0].executor_push_retries = 0
D1207 00:53:48.959770940    3187 report.cc:106]              SERVER[0].server_requested_calls = 331789
D1207 00:53:48.959777488    3187 report.cc:106]              SERVER[0].server_slowpath_requests_queued = 0
D1207 00:53:48.959784418    3187 report.cc:106]              SERVER[0].cq_ev_queue_trylock_failures = 0
D1207 00:53:48.959790920    3187 report.cc:106]              SERVER[0].cq_ev_queue_trylock_successes = 28583
D1207 00:53:48.959797442    3187 report.cc:106]              SERVER[0].cq_ev_queue_transient_pop_failures = 0
D1207 00:53:48.959811760    3187 report.cc:110]              SERVER[0].call_initial_size = 17164.6/21150.3/22370.9 (50/95/99%-ile)
D1207 00:53:48.959823120    3187 report.cc:110]              SERVER[0].poll_events_returned = 0.0/0.0/0.0 (50/95/99%-ile)
D1207 00:53:48.959834059    3187 report.cc:110]              SERVER[0].tcp_write_size = 85.0/114.1/200.7 (50/95/99%-ile)
D1207 00:53:48.959844140    3187 report.cc:110]              SERVER[0].tcp_write_iov_size = 4.5/5.0/22.1 (50/95/99%-ile)
D1207 00:53:48.959855395    3187 report.cc:110]              SERVER[0].tcp_read_size = 391.7/6334.6/14790.5 (50/95/99%-ile)
D1207 00:53:48.959866887    3187 report.cc:110]              SERVER[0].tcp_read_offer = 12576.7/36606.0/57061.4 (50/95/99%-ile)
D1207 00:53:48.959876364    3187 report.cc:110]              SERVER[0].tcp_read_offer_iov_size = 2.8/4.3/4.9 (50/95/99%-ile)
D1207 00:53:48.959886813    3187 report.cc:110]              SERVER[0].http2_send_message_size = 50.5/56.4/56.9 (50/95/99%-ile)
D1207 00:53:48.959896336    3187 report.cc:110]              SERVER[0].http2_send_initial_metadata_per_write = 0.0/0.0/0.0 (50/95/99%-ile)
D1207 00:53:48.959905854    3187 report.cc:110]              SERVER[0].http2_send_message_per_write = 0.0/0.0/0.0 (50/95/99%-ile)
D1207 00:53:48.959915238    3187 report.cc:110]              SERVER[0].http2_send_trailing_metadata_per_write = 0.0/0.0/0.0 (50/95/99%-ile)
D1207 00:53:48.959924561    3187 report.cc:110]              SERVER[0].http2_send_flowctl_per_write = 0.0/0.0/0.0 (50/95/99%-ile)
D1207 00:53:48.959939689    3187 report.cc:110]              SERVER[0].server_cqs_checked = 0.5/1.0/1.0 (50/95/99%-ile)
I1207 00:53:48.959955106    3187 report.cc:119]              QPS: 0.0 (0.0/server core)
I1207 00:53:48.959967612    3187 report.cc:124]              Latencies (50/90/95/99/99.9%-ile): 0.0/0.0/0.0/0.0/0.0 us
I1207 00:53:48.959980662    3187 report.cc:134]              Server system time: 11.37%
I1207 00:53:48.959989149    3187 report.cc:136]              Server user time:   621.09%
I1207 00:53:48.959997102    3187 report.cc:138]              Client system time: 31.42%
I1207 00:53:48.960007484    3187 report.cc:140]              Client user time:   176.20%
I1207 00:53:48.960016924    3187 report.cc:145]              Server CPU usage: 79.12%
I1207 00:53:48.960026648    3187 report.cc:150]              Client Polls per Request: -nan
I1207 00:53:48.960034385    3187 report.cc:152]              Server Polls per Request: inf
I1207 00:53:48.960043150    3187 report.cc:157]              Server Queries/CPU-sec: 0.00
I1207 00:53:48.960050901    3187 report.cc:159]              Client Queries/CPU-sec: 0.00
I1207 00:53:48.963919676    3163 json_run_localhost.cc:67]   driver: subprocess exited with status 1
D1207 00:53:53.613550341    3176 ev_posix.cc:128]            Using polling engine: poll
D1207 00:53:53.613625235    3176 dns_resolver.cc:307]        Using native dns resolver
I1207 00:53:53.689633711    3163 json_run_localhost.cc:67]   worker: subprocess exited with status 66
E1207 00:53:53.689677909    3163 json_run_localhost.cc:129]  assertion failed: driver_join_status == 0

**Comment by hcaseyal** [comment]
@adelez Can this be closed? It doesn't look like it's been referenced in a while

**Comment by yashykt** [comment]
Closing this.
