### ISSUE TITLE
New Failure: csharp.Grpc.Core.Tests.ContextPropagationTest

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13690]
- Test: csharp.Grpc.Core.Tests.ContextPropagationTest
- Poll Strategy: None
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_basictests_multilang/691

**Comment by jtattermusch** [comment]
https://sponge.corp.google.com/invocation?id=ca86c237-d2ae-4cb0-89b3-1dd41dd267a0&searchFor=

**Comment by jtattermusch** [comment]
this should also be fixed by https://github.com/grpc/grpc/pull/13675.
