### ISSUE TITLE
New Failure: bm_fullstack_streaming_ping_pong --benchmark_filter=BM_StreamingPingPongMsgs<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>$

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13691]
- Test: bm_fullstack_streaming_ping_pong --benchmark_filter=BM_StreamingPingPongMsgs<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>$
- Poll Strategy: epollex
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/sanitizer/job/grpc_cpp_asan/186

**Comment by jtattermusch** [comment]
I think this is a duplicate of https://github.com/grpc/grpc/issues/13445 (already closed).
