### ISSUE TITLE
c_macos_opt: h2_full+trace_nosec_test invoke_large_request

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13692]
- Test: h2_full+trace_nosec_test invoke_large_request
- Poll Strategy: poll
- URL: https://kokoro2.corp.google.com/job/grpc/job/macos/job/master/job/grpc_basictests_opt/648

**Comment by dgquintas** [comment]
https://sponge.corp.google.com/target?id=d3814d73-d1cf-451d-8fcc-b655fa1325d0&target=github/grpc/c_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
We keep seeing this every few days:
https://source.cloud.google.com/results/invocations/0d5f1182-dee5-4316-853a-fb89c526b884
https://source.cloud.google.com/results/invocations/422d35f2-1648-4c1e-8f1b-6caea03cc63d
https://source.cloud.google.com/results/invocations/97b4e73a-f19a-45bf-9ce2-4ad150cfb1c0

**Comment by jtattermusch** [comment]
I am able to reproduce with `tools/run_tests/run_tests.py -l c -c dbg -r 'h2_full_test invoke_large_request' -j 10 -n 500` (sometimes requires multiple runs)

**Comment by sreecha** [comment]
Its been 2 months since we saw this (last instance was on 6/19).
