### ISSUE TITLE
check_sources_and_headers.py takes ~20 mins to run

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13699]
That's unnecessarily slowing down the basictests suite and the sanity test suite.

**Comment by jtattermusch** [comment]
CPU is at 100% when running.

**Comment by jtattermusch** [comment]
CC @ctiller, @nicolasnoble

**Comment by ctiller** [comment]
Can we use PyPy to get some cheap wins?

**Comment by jtattermusch** [comment]
@ctiller I changed the algorithm in #13700, now it's very fast.
