### ISSUE TITLE
New Failure: json_run_localhost:cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13695]
- Test: json_run_localhost:cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure
- Poll Strategy: epollex
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_basictests_c_cpp_dbg/675

**Comment by jtattermusch** [comment]
Not seen since 2017-12-07.
