### ISSUE TITLE
exposing grpc_stats_collect as public C API

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#13705]
There are a lots of stats we are interested to push to our monitor system. However, it seems that `grpc_stats_collect` and its related APIs are private for now. Do you have any plan to expose those as public C API? Or is there any alternatives?

**Comment by ncteisen** [comment]
Probably not out of fear of [Hyrum's Law](http://www.hyrumslaw.com/)....

If we can find a safe way to do it (and extract a blood oath from all our users they will never ever ever depend on our internal, experimental, volatile stats API), then yes, I agree it would be very helpful to have public.

Will keep this open for now and discuss with team

**Comment by ncteisen** [comment]
We do not plan to support this API
