### ISSUE TITLE
Add missing build files and targets to enable bazel

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#13715]
I scan the c and c++ tests and found the following missing items.
Microbenchmarks, performance, qps, thread_manager: no grpc_cc_test targets
Channel, client_channel, compression, http, memory_usage, security: missing some test targets.

**Comment by adelez** [comment]
Hi, Yash and Vijay, could you please take a look at the following areas based on @markdroth 's doc on test ownership?
Yash: bad_client (I think this is mostly bazel ready, just need to make sure no individual tests got left out), C89 build
Vijay: end-to-end (I think this is also enabled for bazel mostly, except fuzzers? But please audit the coverage.)

**Comment by yashykt** [comment]
bad_client and C89 build are fine. They have BUILD files

**Comment by adelez** [comment]
Sometimes not all tests are included in the BUILD files. Please go over the BUILD files in detail to double check.

**Comment by adelez** [comment]
#14316 and #14326

**Comment by yashykt** [comment]
I think we have coverage for all existing cases?

**Comment by yashykt** [comment]
I guess this can be closed now
