### ISSUE TITLE
bins/opt/dualstack_socket_test is flaky on grpc/macos/master/grpc_basictests_opt

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13727]
https://sponge.corp.google.com/target?id=c2d5ac7f-c5e6-459f-b481-0db2cdda1536&target=github/grpc/c_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

Flakiness rate is pretty high (currently 33%), needs immediate attention.

**Comment by pmarks-net** [comment]
It appears that the "connection refused" errors are intentional.  This is the part that actually fails:

    I1212 05:39:55.872010000 140735125356544 dualstack_socket_test.cc:141] Testing with server=loopback4.unittest.grpc.io:17378 client=loopback6.unittest.grpc.io:17378 (expecting failure)
    E1212 05:39:57.372422000 140735125356544 dualstack_socket_test.cc:239] assertion failed: status == GRPC_STATUS_UNAVAILABLE

So, what I can conclude is:
1) The connection was expected to fail.
2) It returned a status other than `GRPC_STATUS_UNAVAILABLE`, but I can't see the actual value.

This test has changed significantly since I wrote it; the failing assert was last touched by https://github.com/grpc/grpc/commit/8c0d96ff867628dbb3e4fa8562869d53eff45589

Given that this affects platform/macOS; how does one reproduce the failure?

**Comment by y-zeng** [comment]
This possibly is a system issue:
1. The error occurs when setting up the connection. I've verified both the server-side listener fd and the client-side `connect()` fd were in the completion queue's `pollfd` set. But it could take several seconds for `poll()` to wake up and notice that there was a `ECONNREFUSED`, causing deadline exceed errors. 
2. Similar failures can be reproduced in our end2end tests on MacOS, e.g.
   ```
   tools/run_test/run_test.py -lc -r simple_request -n 1000
   ```
   The flaky rate is about 2%
 3. It cannot be reproduced on Linux when using the same iomgr code path (i.e. setting `GPR_APPLE` on Linux to use `accept()`, `wakeup_fd_pipe`, etc)

**Comment by y-zeng** [comment]
@pmarks-net Similar errors were also seen on cases expecting success. I was using my Macbook to reproduce the failure.

**Comment by jtattermusch** [comment]
Still happening on Mac
https://sponge.corp.google.com/invocation?id=8b46dfa1-bbe3-4ef4-83c3-74140a076a45
https://sponge.corp.google.com/invocation?id=ee507710-1ec7-4d94-9a1e-08b1573f3b2c
https://sponge.corp.google.com/invocation?id=80231206-26d3-4c44-850b-005b77fb33ed

and occasionally also on linux (with GRPC_POLLER=epoll1)
https://sponge.corp.google.com/invocation?id=ad495b2d-d673-48da-801d-1f1c76cbd96f

always happening on opt configuration (dbg is unaffected).

**Comment by dgquintas** [comment]
I just saw this again: https://sponge.corp.google.com/target?id=dd02c306-1de7-4d52-ad7b-b6446b39c454&target=github/grpc/c_linux_opt_native&searchFor=&show=ALL&sortBy=STATUS

**Comment by dgquintas** [comment]
Managed to repro after ~5 min via `./tools/run_tests/run_tests.py -l c -c opt -r dualstack_socket_test -a 20 -n inf -S --force_use_pollers=poll`

**Comment by jtattermusch** [comment]
Not sure if we should redesign the test somehow or just increase the deadline for expect_ok = false even further.

**Comment by dgquintas** [comment]
well, increasing the deadline is faster, let's give that a try.

**Comment by jtattermusch** [comment]
Failures over the last week:
https://sponge.corp.google.com/invocation?id=829bf574-c31e-4dc5-be0c-684e4d6fed50
https://sponge.corp.google.com/invocation?id=fce32a68-312e-46ed-b8c1-ba8a3597a59e

**Comment by jtattermusch** [comment]
@yashykt   thanks for the insights. What's the best way to investigate further or verify the theories you've presented?

**Comment by jtattermusch** [comment]
This is still going on Linux (failing about 2% of builds):
https://source.cloud.google.com/results/invocations/4019cade-d9b8-4421-b44e-3591b5ca78d8/targets/github%2Fgrpc%2Fc_linux_opt_native/tests
https://source.cloud.google.com/results/invocations/a1c5efd4-d246-4c56-9cf8-85d41a02d2c7/targets/github%2Fgrpc%2Fc_linux_dbg_native/tests

**Comment by apolcyn** [comment]
Seen on 1.42.x branch in:

https://source.cloud.google.com/results/invocations/1623802c-f643-4779-b951-e1faca3f67d9/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp/log

https://source.cloud.google.com/results/invocations/d4efd5ab-a394-49de-88d9-03a642f012c8/targets/%2F%2Ftest%2Fcore%2Fend2end:dualstack_socket_test/log

From PR: https://github.com/grpc/grpc/pull/28438

**Comment by jtattermusch** [comment]
I think we might need to backport https://github.com/grpc/grpc/pull/28343.

**Comment by yashykt** [comment]
We decided to use buganizer for flakes
