### ISSUE TITLE
C# code gen "file_extension" option is not applied to grpc service files

### ISSUE THREAD

**Issue by Mainian** [grpc/grpc#13726]
When generating C# classes using grpc tools 1.7.1 or 1.7.3 with google protobuf tools 3.4.0 and the grpc_csharp_plugin, I cannot get the csharp option file extension to apply to the grpc service classes, but does get applied to the reflection class.

Below is the command I am running with all the paths removed:

1.7.3\tools\windows_x64 protoc -I.\Proto\;[3.4.0 tools] --csharp_out Proto Proto/myProto.proto --csharp_opt=file_extension=.g.cs --grpc_out=Proto --plugin=protoc-gen-grpc=[1.7.3\tools\windows_x64 \grpc_csharp_plugin.exe]
 
I would expect the .g.cs to be applied to the service files.

**Comment by jtattermusch** [comment]
This basically boils down to the `file_extension` option not being supported by gRPC C# codegen (the C# codegen in protobuf and the gRPC codegen are basically two separate protobuf compiler "plugins" - despite one of them being built-in to protoc directly and they support two distinct sets of options)

protoc C# options:
https://github.com/google/protobuf/blob/c44ca26fe89ed8a81d3ee475a2ccc1797141dbce/src/google/protobuf/compiler/csharp/csharp_generator.cc#L79

gRPC C# plugin options:
https://github.com/grpc/grpc/blob/dd1dbca2c3d4ace6da4eba008c3e279af024c7c6/src/compiler/csharp_plugin.cc#L43

Btw, even if support of `file_extension` is added to gRPC C# plugin, one would still need to provide the option to both --csharp_opt  as well as to the gRPC C# plugin.

**Comment by jtattermusch** [comment]
We don't have any plans to work on this in near future.
