### ISSUE TITLE
Add a warning/info message when completion_queue_destroy was called while there where still pending items

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#13735]
Ideally `grpc_completion_queue_destroy()` should be called after calling `grpc_completion_queue_shutdown()` and after `grpc_completion_queue_next()` returned `false`. 

However, our API's allow `grpc_completion_queue_destroy()` to be called without calling shutdown
While this is legal and does the right thing, it can sometimes give memory leak errors if `grpc_completion_queue_next()` was never called after `grpc_completion_queue_destroy()` to drain the queue

It would be good to log a message in `grpc_completion_queue_destroy()` if there are still some pending items in the queue.

**Comment by slash-lib** [comment]
Any update on this?

**Comment by sreecha** [comment]
Hi @slash-lib , I suspect there is a legimate race in the cq-destroy path..I am trying to investigate it (but got sidetracked by something else). I will get to this next week.

**Comment by sreecha** [comment]
This issue keeps coming up. Changing priority to P2
