### ISSUE TITLE
Python GRPC blocks when connection drops

### ISSUE THREAD

**Issue by vlad7777** [grpc/grpc#13746]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
Python
grpcio 1.7.3
 
### What operating system (Linux, Windows, …) and version?
Linux 4.13.12-1-ARCH
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.14
 
 
### What did you do?
Established stream-stream connection from client to the server, then disabled network for the client and tried to interrupt the client with ctrl+c.
 
### What did you expect to see?
First of all, I expected grpc to throw an exception saying that there's no network. When that didn't  happen, I expected the program to exit because of KeyboardInterrupt.
 
### What did you see instead?
The client blocked, and I couldn't exit with ctrl+c. I had to ctrl+\ instead.
 
To reproduce:
1. docker pull vladocker/grpcclient; docker pull vladocker/grpcserver. These include just the slightly modified code from the RouteGuide examples.
1. docker run -ti --name grpcserver vladocker/grpcserver
2. docker run -ti --link grpcserver:grpcserver --name grpcclient vladocker/grpcclient
3. see the messages appear on the screen
4. docker network disconnect bridge grpcclient
5. Try to do Ctrl+C the client, nothing happens

**Comment by vlad7777** [comment]
Found a workaround - for ctrl+c to work, there must be a separate thread that waits and cancels the rendezvous when ctrl+c is pressed.

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: any insight or analysis on this?

**Comment by srini100** [comment]
For in-flight RPCs, gRPC will wait until TCP connection has a time-out. The socket is not killed just because network went down. If user wants the RPC to fail may be this [will help.](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md)

**Comment by srini100** [comment]
Ctrl+c problem was fixed. If the blocking issue still exists please reopen.
