### ISSUE TITLE
Cant build on Windows grpc_chttp2_huffsyms issue

### ISSUE THREAD

**Issue by dcembala** [grpc/grpc#13748]
### What version of gRPC and what language are you using?
clean master branch 
 
### What operating system (Linux, Windows, …) and version?
 Windows 10/Windows 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2017/ 2015
 
### What did you do?
Try to build grpc.
 
### What did you expect to see?
Projects built 
 
### What did you see instead?
 "D:\Projekty\GRPC\.build\ALL_BUILD.vcxproj" (domyślny element docelowy) (1)->
"D:\Projekty\GRPC\.build\gen_hpack_tables.vcxproj" (domyślny element docelowy) (106)->
(element docelowy Link) ->
  gen_hpack_tables.obj : error LNK2001: unresolved external symbol _grpc_chttp2_huffsyms [D:\Projekty\GRPC\.build\gen_h
pack_tables.vcxproj]
  D:\Projekty\GRPC\.build\Debug\gen_hpack_tables.exe : fatal error LNK1120: 1 unresolved externals [D:\Projekty\GRPC\.b
uild\gen_hpack_tables.vcxproj]

 
### Anything else we should know about your project / environment?

I'm using Visual Studio Express. Tested on two different PC-s one with Windows 7 and Visual Studio 2015 other one with Windows 10 and Visual Studio 2017, also tryied to build with Ninja and it throws the same error.

**Comment by Tuebel** [comment]
I tried building it several times today, too. I used cmake with VS2017 and cmake with Ninja.
The full message from the command prompt using ninja:

[1/1] Linking CXX executable gen_hpack_tables.exe
FAILED: gen_hpack_tables.exe
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\gen_hpack_tables.dir --manifests  -- C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\link.exe /nologo CMakeFiles\gen_hpack_tables.dir\tools\codegen\core\gen_hpack_tables.c.obj  /out:gen_hpack_tables.exe /implib:gen_hpack_tables.lib /pdb:gen_hpack_tables.pdb /version:0.0  /machine:x64 /INCREMENTAL:NO /subsystem:console  gpr.lib grpc.lib gpr.lib wsock32.lib third_party\boringssl\ssl\ssl.lib third_party\boringssl\crypto\crypto.lib third_party\zlib\zlibstatic.lib third_party\cares\cares\lib\cares.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\link.exe /nologo CMakeFiles\gen_hpack_tables.dir\tools\codegen\core\gen_hpack_tables.c.obj /out:gen_hpack_tables.exe /implib:gen_hpack_tables.lib /pdb:gen_hpack_tables.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console gpr.lib grpc.lib gpr.lib wsock32.lib third_party\boringssl\ssl\ssl.lib third_party\boringssl\crypto\crypto.lib third_party\zlib\zlibstatic.lib third_party\cares\cares\lib\cares.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:gen_hpack_tables.exe.manifest" failed (exit code 1120) with the following output:
gen_hpack_tables.c.obj : error LNK2019: Verweis auf nicht aufgel├╖stes externes Symbol "grpc_chttp2_huffsyms" in Funktion "build_dec_tbl".
gen_hpack_tables.exe : fatal error LNK1120: 1 nicht aufgel├╖ste Externe
ninja: build stopped: subcommand failed.

**Comment by ncteisen** [comment]
Fix is in #13756, thanks for the catch
