### ISSUE TITLE
Throwing a TaskCanceledException from WaitForStateChangedAsync is a poor design

### ISSUE THREAD

**Issue by zhulika** [grpc/grpc#13751]
The fact that you have chosen to cancel the task when it times out makes it very hard to use grpc in Windows because the output window floods with TaskCanceledException messages, I understand that so wish to claim that this is a feature specific to Visual Studio (#11328) but, if you want to say that you support Windows, I feel that you should conform to standard development environment for that operating system.

IMO, an "expected" condition, such as expiring code by reaching some sort of deadline should not throw an exception; exceptions are for exceptional (i.e. unexpected) conditions. In this case, I believe that the standard thing to do it to return a `bool` from this function and set it to false to indicate that it timed out. This the way that other similar functions in the .Net framework seem to behave.

**Comment by jtattermusch** [comment]
Also see https://github.com/grpc/grpc/issues/13227
