### ISSUE TITLE
pecl install error

### ISSUE THREAD

**Issue by yanyouth** [grpc/grpc#13797]
[root@WEBAPP_ /tmp/grpc-1.6.0]# sudo pecl install grpc      
downloading grpc-1.8.0.tgz ...
Starting to download grpc-1.8.0.tgz (2,304,860 bytes)
.........done: 2,304,860 bytes
1049 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /data/tmp/pear/temp/pear-build-root8XQo5w/grpc-1.8.0
running: /data/tmp/pear/temp/grpc/configure --with-php-config=/usr/local/php/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable grpc support... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking dlfcn.h usability... no
checking dlfcn.h presence... yes
configure: WARNING: dlfcn.h: present but cannot be compiled
configure: WARNING: dlfcn.h:     check for missing prerequisite headers?
configure: WARNING: dlfcn.h: see the Autoconf documentation
configure: WARNING: dlfcn.h:     section "Present But Cannot Be Compiled"
configure: WARNING: dlfcn.h: proceeding with the preprocessor's result
configure: WARNING: dlfcn.h: in the future, the compiler will take precedence
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... failed
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... no
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... no
checking if we can lock with hard links... yes
checking whether the cc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
libtool.m4: error: problem compiling CXX test program
checking for g++ option to produce PIC...
checking if g++ static flag  works... no
checking if g++ supports -c -o file.o... no
checking if we can lock with hard links... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... unsupported
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /data/tmp/pear/temp/pear-build-root8XQo5w/grpc-1.8.0/libtool --mode=compile cc -fvisibility=hidden     -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -I. -I/data/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/data/tmp/pear/temp/pear-build-root8XQo5w/grpc-1.8.0/include -I/data/tmp/pear/temp/pear-build-root8XQo5w/grpc-1.8.0/main -I/data/tmp/pear/temp/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/data/tmp/pear/temp/grpc/include -I/data/tmp/pear/temp/grpc/src/php/ext/grpc -I/data/tmp/pear/temp/grpc/third_party/boringssl/include  -DHAVE_CONFIG_H  -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11   -c /data/tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c -o src/php/ext/grpc/byte_buffer.lo
mkdir src/php/ext/grpc/.libs
 cc -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -I. -I/data/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/data/tmp/pear/temp/pear-build-root8XQo5w/grpc-1.8.0/include -I/data/tmp/pear/temp/pear-build-root8XQo5w/grpc-1.8.0/main -I/data/tmp/pear/temp/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/data/tmp/pear/temp/grpc/include -I/data/tmp/pear/temp/grpc/src/php/ext/grpc -I/data/tmp/pear/temp/grpc/third_party/boringssl/include -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -c /data/tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c  -DPIC
cc1: error: unrecognized command line option "-std=c11"
cc1: warnings being treated as errors
cc1: error: unrecognized command line option "-Wno-parentheses-equality"
make: *** [src/php/ext/grpc/byte_buffer.lo] Error 1
ERROR: `make' failed
![image](https://user-images.githubusercontent.com/9983916/34026014-2a9bdf42-e18e-11e7-89a9-8e6b05cfb0e2.png)

![image](https://user-images.githubusercontent.com/9983916/34025972-ddc01170-e18d-11e7-8d3c-96057b70ffa7.png)

**Comment by ZhouyihaiDing** [comment]
Sorry install grpc extension by pecl on CentOS/RHEL 6 [doesn't work](https://grpc.io/docs/quickstart/php.html#using-pecl) for now. You can try [build from source](https://grpc.io/docs/quickstart/php.html#build-from-source-with-grpc-c-core-library).
