### ISSUE TITLE
class helloworld::HelloRequestDefaultTypeInternal’ has no member named ‘Shutdown’

### ISSUE THREAD

**Issue by Zomaka** [grpc/grpc#13799]
### What version of gRPC and what language are you using?
 C++ with Protobuf 3.5.0
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
> 
> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

 
### What did you do?
I'm trying to compile the C++ helloworld example in grpc/examples/cpp/helloworld
### What did you expect to see?
 Hello world.
 
### What did you see instead?

$ make

> g++ -std=c++11 `pkg-config --cflags protobuf grpc`  -c -o helloworld.pb.o helloworld.pb.cc
> helloworld.pb.cc: In static member function ‘static void helloworld::protobuf_helloworld_2eproto::TableStruct::Shutdown()’:
> helloworld.pb.cc:82:35: error: ‘class helloworld::HelloRequestDefaultTypeInternal’ has no member named ‘Shutdown’
>    _HelloRequest_default_instance_.Shutdown();
>                                    ^
> helloworld.pb.cc:84:33: error: ‘class helloworld::HelloReplyDefaultTypeInternal’ has no member named ‘Shutdown’
>    _HelloReply_default_instance_.Shutdown();
>                                  ^
> <builtin>: recipe for target 'helloworld.pb.o' failed
> make: *** [helloworld.pb.o] Error 1

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by hcaseyal** [comment]
@Zomaka Are you still seeing this issue with the latest version of gRPC?

**Comment by hcaseyal** [comment]
Closing due to reporter inaction. Please feel free to re-open if this is still an issue.
