### ISSUE TITLE
Installation barfs on fresh Mac OS X High Sierra - ld: warning: directory not found for option '-L/Users/<path>/grpc/libs/opt/c-ares'

### ISSUE THREAD

**Issue by Brahmasmi** [grpc/grpc#13808]
### What operating system (Linux, Windows, …) and version?
Mac OS X High Sierra 10.13.2
 
### What did you do?

1) Installed Xcode and Unix tools
```
sudo xcode-select --install
```
2) Installed via ports
```
sudo port selfupdate
sudo port upgrade outdated
sudo port install autoconf automake libtool
```
3) Cloned gRPC
```
mkdir ~/install
cd ~/install
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make
```

Steps 1 , 2 - Based on https://github.com/google/protobuf/blob/master/src/README.md Note for Mac users, based on guidance in https://github.com/grpc/grpc/tree/master/src/objective-c#install-protoc-and-the-grpc-plugin-without-using-homebrew

Step 3 - The LIBTOOL and LIBTOOLIZE is based on https://github.com/grpc/grpc/blob/master/INSTALL.md#macos.

### What did you expect to see?
 No warnings
 
### What did you see instead?
Warnings for all *_plugin.cc 
```
[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTLD]  Linking /Users/<user>/install/grpc/bins/opt/grpc_cpp_plugin
 ld: warning: directory not found for option '-L/Users/<user>/install/grpc/libs/opt/c-ares'
<output snipped for brevity>
```
Warnings for all lib*.dylib
```
[LD]      Linking /Users/<user>/install/grpc/libs/opt/libgpr.dylib
ld: warning: directory not found for option '-L/Users/<user>/install/grpc/libs/opt/c-ares'
<output snipped for brevity>
```
### Anything else we should know about your project / environment?
Fresh and updated installation of Mac OS X High Sierra 10.13.2. No protoc installed. Protoc being built as part of the gRPC installation. release.dms from grpc.io contains v1.8.x.

### Initial investigation
Based on https://github.com/grpc/grpc/blob/master/templates/Makefile.template, there is no mkdir cp for c-ares. There is one present for protobuf - https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L902-L905
```
  	$(Q)mkdir -p $(LIBDIR)/$(CONFIG)/protobuf
  	$(Q)mkdir -p $(BINDIR)/$(CONFIG)/protobuf
  	$(Q)cp third_party/protobuf/src/.libs/libprotoc.a $(LIBDIR)/$(CONFIG)/protobuf
  	$(Q)cp third_party/protobuf/src/.libs/libprotobuf.a $(LIBDIR)/$(CONFIG)/protobuf
```
The lines which cause the warning to appear - https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L592-L598,
```
ifeq ($(EMBED_CARES),true)
  CARES_DEP = $(LIBDIR)/$(CONFIG)/libares.a
  CARES_MERGE_OBJS = $(LIBARES_OBJS)
  CARES_MERGE_LIBS = $(LIBDIR)/$(CONFIG)/libares.a
  CPPFLAGS := -Ithird_party/cares -Ithird_party/cares/cares $(CPPFLAGS)
  LDFLAGS := -L$(LIBDIR)/$(CONFIG)/c-ares $(LDFLAGS)
  else
```
General searching does not lead to a definitive solution. Installing c-ares externally via ports seems to have been discouraged - https://groups.google.com/forum/#!topic/grpc-io/eVdtmWufE5w.

**Comment by Brahmasmi** [comment]
Tried adopting the "DISABLING ARES" line from @timburks' grpc-swift repository https://github.com/grpc/grpc-swift/blob/master/vendor-grpc.sh#L75-L76 like so

```
mkdir ~/install
cd ~/install
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
perl -pi -e 's/#define GRPC_ARES 1/#define GRPC_ARES 0/' include/grpc/impl/codegen/port_platform.h
LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make
```
No success. The installation continues to barf with the same aforementioned warnings.

Further, running
```
grep -r "GRPC_ARES" .
```
within a freshly cloned gRPC repository suggests that GRPC_ARES seems to be set to 0 everywhere.

```
./config.w32:    "/D_HAS_EXCEPTIONS=0 /DNOMINMAX /DGRPC_ARES=0 /D_WIN32_WINNT=0x600 "+
./include/grpc/impl/codegen/port_platform.h:#ifndef GRPC_ARES
./include/grpc/impl/codegen/port_platform.h:#define GRPC_ARES 0
./include/grpc/impl/codegen/port_platform.h:#define GRPC_ARES 1
./gRPC-Core.podspec:  s.compiler_flags = '-DGRPC_ARES=0'
./config.m4:    -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0)
./grpc.gyp:      'GRPC_ARES=0',
./setup.py:                    ('GRPC_ARES', 0), ('NTDDI_VERSION', 0x06000000),)
./bazel/grpc_build_system.bzl:    defines = select({"//:grpc_no_ares": ["GRPC_ARES=0"],
./templates/gRPC-Core.podspec.template:    s.compiler_flags = '-DGRPC_ARES=0'
./templates/config.w32.template:      "/D_HAS_EXCEPTIONS=0 /DNOMINMAX /DGRPC_ARES=0 /D_WIN32_WINNT=0x600 "+
./templates/grpc.gyp.template:        'GRPC_ARES=0',
./templates/config.m4.template:      -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0)
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc:#if GRPC_ARES == 1 && defined(GRPC_POSIX_SOCKET)
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc:#endif /* GRPC_ARES == 1 && defined(GRPC_POSIX_SOCKET) */
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h:#ifndef GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_WRAPPER_H
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h:#define GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_WRAPPER_H
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h:#endif /* GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_WRAPPER_H \
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:#if GRPC_ARES == 1 && !defined(GRPC_UV)
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:#endif /* GRPC_ARES == 1 && !defined(GRPC_UV) */
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h:#ifndef GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_EV_DRIVER_H
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h:#define GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_EV_DRIVER_H
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h:#endif /* GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_EV_DRIVER_H \
./src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:#if GRPC_ARES == 1 && !defined(GRPC_UV)
./src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:#else /* GRPC_ARES == 1 && !defined(GRPC_UV) */
./src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:#endif /* GRPC_ARES == 1 && !defined(GRPC_UV) */
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_fallback.cc:#if GRPC_ARES != 1 || defined(GRPC_UV)
./src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_fallback.cc:#endif /* GRPC_ARES != 1 || defined(GRPC_UV) */
```

Is there something obvious that I am missing?

**Comment by Brahmasmi** [comment]
Can you please help me understand what could I be doing wrong? I am attempting installation from source on a Mac. This should not feel like a visit to the dentist, except that I am running out of ideas.

@muxi @timburks

**Comment by Brahmasmi** [comment]
@ncteisen @vjpai @ctiller @nathanielmanistaatgoogle @jcanizales 

Apologies for looping you folks in. However, I am unable to get installation from source to work on a Mac for some time now. In case you are not the correct folks for this, could you please share the correct folks/mechanism/channel to communicate this? I am hoping to not post this issue again on the gRPC google group, in order to avoid duplication.

Additionally, I am unable to understand the rationale for c-ares, given that GRPC_ARES seems to be set to 0 for most, if not all, build mechanisms (bazel et al). This is based on my limited knowledge of grepping and absolutely no understanding of the underlying code or what c-ares does. It is purely from a perspective of someone trying to get gRPC to build for the last 2 weeks, albeit unsuccessfully.
```
./gRPC-Core.podspec:  s.compiler_flags = '-DGRPC_ARES=0'
./config.m4:    -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0)
./grpc.gyp:      'GRPC_ARES=0',
./setup.py:                    ('GRPC_ARES', 0), ('NTDDI_VERSION', 0x06000000),)
./bazel/grpc_build_system.bzl:    defines = select({"//:grpc_no_ares": ["GRPC_ARES=0"],
```
The above snippet is from the full output of
```
grep -r "GRPC_ARES"
```
which is present in the comment preceding the previous comment.

**Comment by ncteisen** [comment]
c ares is the async DNS resolver we use.

Can you try installing c ares first? Something like:
```
cd third_party/cares
make
[sudo] make install
```

(or something like that, there may be a `./configure` step somewhere. Can give a more detailed answer next week)

**Comment by vjpai** [comment]
Hi there,
Just to confirm: this is only a warning, correct? I usually use bazel (where we do have a known issue on the mac of getting some warnings), but I can repro this warning on make. But given that it's just a warning, this seems like more of an inconvenience than a "trip to the dentist" . Is the installation actually "barf"ing or just producing some warnings?

**Comment by Brahmasmi** [comment]
Danke @vjpai for your response.

From what I understand, and I may be wrong here - an attempt to install should not produce warnings. Especially, in such numbers. I think it is a good practice to not proceed and to report these warnings. Case in point - https://github.com/projectNe10/Ne10/issues/123 - reporting usually gets them fixed, and might help uncover underlying issues.

May be this may not seem like a "trip to the dentist", and may be this may not qualify as an installation "barf"ing, but I hope you would not consider this to be par for the course - installation from source following canonical instructions on a fresh machine producing a stream of warnings.

As regards to it being more of an inconvenience, I would request you to please refer to this thread - https://groups.google.com/forum/#!topic/grpc-io/eVdtmWufE5w (linked in the original issue).

In case I am missing an obvious solution, I apologize and request you to please share the same.

**Comment by vjpai** [comment]
Oh, I'm not saying that this isn't a problem. I'm just trying to gauge its relative priority. I think we should address this but it may take a bit of time.
