### ISSUE TITLE
Connections fail to server running openssl 1.1.0 on debian stretch

### ISSUE THREAD

**Issue by PlacidBox** [grpc/grpc#13809]
### Should this be an issue in the gRPC issue tracker?

Yes

It seems to be a similar issue to https://github.com/grpc/grpc/issues/11935, but they resolved the issue by switching their code to boringssl, something that is non-trivial for us. We're also running as a server, rather than a client.

### What version of gRPC and what language are you using?

Grpc version v1.8.1, using C++

### What operating system (Linux, Windows, …) and version?

Linux, Debian Stretch,

OpenSSL 1.1.0f

protoc not installed

### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC 6.3.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```
git clone https://github.com/grpc/grpc.git
git checkout v1.8.1
git submodule update --init
EMBED_OPENSSL=false CFLAGS="-Wno-error" CXXFLAGS="-Wno-error" make -j4 install-plugins install-static install-headers prefix=$(pwd)/install
./tools/run_tests/start_port_server.py
EMBED_OPENSSL=false CFLAGS="-Wno-error" CXXFLAGS="-Wno-error" make test
```

### What did you expect to see?

All tests pass

### What did you see instead?

The `handshake_client` test seems to always fail, and `dualstack_socket_test` seems a bit flaky

```
[RUN]     Testing handshake_client
E1218 10:00:13.334619327    7019 client_ssl.cc:308]          assertion failed: client_ssl_test(const_cast<char*>("grpc-exp"))
Aborted
test handshake_client failed
```

```
[RUN]     Testing dualstack_socket_test
D1218 10:03:48.345552112   10284 test_config.cc:388]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
E1218 10:04:03.273825154   10284 dualstack_socket_test.cc:239] assertion failed: status == GRPC_STATUS_UNAVAILABLE



*******************************
Caught signal SIGABRT
/home/chris/grpc/bins/opt/dualstack_socket_test(+0x96ede)[0x560357f80ede]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110c0)[0x7f215d2b90c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7f215c83cfcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f215c83e3fa]
/home/chris/grpc/bins/opt/dualstack_socket_test(+0x11d30)[0x560357efbd30]
/home/chris/grpc/bins/opt/dualstack_socket_test(+0x10abc)[0x560357efaabc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f215c82a2b1]
/home/chris/grpc/bins/opt/dualstack_socket_test(+0x110fa)[0x560357efb0fa]
Aborted
test dualstack_socket_test failed
Makefile:1759: recipe for target 'test_c' failed
make: *** [test_c] Error 1
```

**Comment by bettermanzzy** [comment]
I have met the same problems in grpc-v1.12.0. Could anyone give some advice?
