### ISSUE TITLE
interop tests using java client fail

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#1381]
The following tests are failing: large_unary, empty_unary, ping_pong, client_stream, and server_stream
for the following combinations:
java-> prod
java-> cxx
java-> ruby
java->node
java->python
java->csharp_mono

**Comment by soltanmm** [comment]
Should this be here or in [https://github.com/grpc/grpc-java](grpc-java)?

**Comment by jayantkolhe** [comment]
Closing based on test run. Donna, plz verify and reopen if still failing.
