### ISSUE TITLE
Can't build grpc 1.8.0 ruby gem with --platform ruby

### ISSUE THREAD

**Issue by duelinmarkers** [grpc/grpc#13814]
### What version of gRPC and what language are you using?
 
Trying to install 1.8.0, having previously used 1.6.7 and 1.7.3 successfully. The `--platform ruby` is because our project uses bundler, and our Gemfile.lock only specifies the `ruby` platform.

### What operating system (Linux, Windows, …) and version?

`Linux ... 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64 GNU/Linux`

### What runtime / compiler are you using (e.g. python version or version of gcc)

`g++ (Debian 4.7.2-5) 4.7.2`

### What did you do?

`gem install grpc -v 1.8.0 --platform=ruby`

### What did you expect to see?

Something like this output from installing 1.7.3:

```
% gem install grpc -v 1.7.3 --platform ruby
Fetching: google-protobuf-3.5.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed google-protobuf-3.5.0
Fetching: grpc-1.7.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed grpc-1.7.3
Parsing documentation for google-protobuf-3.5.0
Installing ri documentation for google-protobuf-3.5.0
Parsing documentation for grpc-1.7.3
Installing ri documentation for grpc-1.7.3
Done installing documentation for google-protobuf, grpc after 4 seconds
2 gems installed
``` 
 
### What did you see instead?

Full build output is [available in a gist](https://gist.github.com/duelinmarkers/8117c91adc43b9452faaaa9ee25a09bc). Hopefully useful highlights:

```
...
src/core/lib/iomgr/error.cc:150:18: error: ‘UINT8_MAX’ was not declared in this scope
...
src/core/lib/iomgr/ev_epoll1_linux.cc:570:17: error: ‘INTPTR_MAX’ was not declared in this scope
...
src/core/lib/iomgr/exec_ctx.cc:120:11: error: ‘INTPTR_MAX’ was not declared in this scope
...
```

### Anything else we should know about your project / environment?

Let me know if further information could be helpful.

**Comment by itsprdp** [comment]
+1
