### ISSUE TITLE
h2_ssl_proxy_test times out for several testcases

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13846]
Examples:
- invoke_large_request: #13214 
- cancel_after_round_trip: #13160 
- stream_compression_ping_pong: #13762 

New ones:
- cancel_after_invoke,  http://sponge/b79df207-7faa-4a50-b999-ad999349a14c
- ping_pong_streaming, http://sponge/7e0f2851-8c10-4b60-8a81-257245e45467

**Comment by yashykt** [comment]
Not seen recently.
