### ISSUE TITLE
New Failure: h2_full_nosec_test.exe shutdown_finishes_calls

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13845]
- Test: h2_full_nosec_test.exe shutdown_finishes_calls
- Poll Strategy: None
- URL: https://kokoro2.corp.google.com/job/grpc/job/windows/job/master/job/grpc_basictests_dbg/806

**Comment by dgquintas** [comment]
Probably related to #13149

**Comment by dgquintas** [comment]
https://sponge.corp.google.com/invocation?id=0314cdcb-5694-4417-9380-7a5a83c8c392&searchFor=

**Comment by jtattermusch** [comment]
Not seen since Dec 19.
