### ISSUE TITLE
CMake builds but does not install grpc_cpp_plugin

### ISSUE THREAD

**Issue by gaschler** [grpc/grpc#13841]
CMake *builds but does not install grpc_cpp_plugin* and other files.
I use cmake version 2.8.12 with ninja 1.3.4 on Ubuntu 14 with the current grpc master.

Here is a warning:
CMake Warning at CMakeLists.txt:143 (message):
  gRPC_INSTALL will be forced to FALSE because gRPC_CARES_PROVIDER is
  "module"

The install command does not show any warning, but does not install grpc_cpp_plugin, only the library and headers, and a four executables, including protoc.
grpc_cpp_plugin and related executables are in the build folder.

Perhaps this is related to the bug https://github.com/grpc/grpc/issues/12384 in Windows?

In case it helps, here are my cmake settings.
I set CMAKE_INSTALL_PREFIX, but this should not be the reason.
 CARES_INSTALL                    ON                                                                                        
 CARES_SHARED                     OFF                                                                                       
 CARES_STATIC                     ON                                                                                        
 CARES_STATIC_PIC                 OFF                                                                                       
 CMAKE_BACKWARDS_COMPATIBILITY    2.4                                                                                       
 CMAKE_BUILD_TYPE                                                                                                           
 CMAKE_INSTALL_PREFIX             /usr/local/stow/grpc                                                                      
 EXECUTABLE_OUTPUT_PATH                                                                                                     
 FOUND_LIBRT                      /usr/lib/x86_64-linux-gnu/librt.so                                                        
 GO_EXECUTABLE                    /usr/lib/google-golang/bin/go                                                             
 INSTALL_BIN_DIR                  /usr/local/stow/grpc/bin                                                                  
 INSTALL_INC_DIR                  /usr/local/stow/grpc/include                                                              
 INSTALL_LIB_DIR                  /usr/local/stow/grpc/lib                                                                  
 INSTALL_MAN_DIR                  /usr/local/stow/grpc/share/man                                                            
 INSTALL_PKGCONFIG_DIR            /usr/local/stow/grpc/share/pkgconfig                                                      
 LIBRARY_OUTPUT_PATH                                                                                                        
 LIBRT                            /usr/lib/x86_64-linux-gnu/librt.so                                                        
 gRPC_BENCHMARK_PROVIDER          module                                                                                    
 gRPC_BUILD_TESTS                 OFF                                                                                       
 gRPC_CARES_PROVIDER              module                                                                                    
 gRPC_GFLAGS_PROVIDER             package                                                                                   
 gRPC_INSTALL                     ON                                                                                        
 gRPC_INSTALL_BINDIR              /usr/local/stow/grpc/bin                                                                  
 gRPC_INSTALL_CMAKEDIR            /usr/local/stow/grpc/lib/cmake/grpc                                                       
 gRPC_INSTALL_INCLUDEDIR          /usr/local/stow/grpc/include                                                              
 gRPC_INSTALL_LIBDIR              /usr/local/stow/grpc/lib                                                                  
 gRPC_PROTOBUF_PACKAGE_TYPE                                                                                                 
 gRPC_PROTOBUF_PROVIDER           module                                                                                    
 gRPC_SSL_PROVIDER                module                                                                                    
 gRPC_USE_PROTO_LITE              OFF                                                                                       
 gRPC_ZLIB_PROVIDER               package                                                                                   
 gflags_DIR                       gflags_DIR-NOTFOUND                                                                       
 protobuf_BUILD_EXAMPLES          OFF                                                                                       
 protobuf_BUILD_SHARED_LIBS       OFF                                                                                       
 protobuf_BUILD_TESTS             OFF                                                                                       
 protobuf_INSTALL_EXAMPLES        OFF                                                                                       
 protobuf_MSVC_STATIC_RUNTIME     OFF                                                                                       
 protobuf_WITH_ZLIB               OFF

**Comment by jtattermusch** [comment]
What's happening:
Because of some limitations of our current CMakeLists.txt, the install targets (see gRPC_INSTALL option) will only be generated if you are building using a pre-installed version of our dependencies (gRPC_CARES_PROVIDER in your case needs to be set to `package`).

The warning you saw `gRPC_INSTALL will be forced to FALSE because gRPC_CARES_PROVIDER is
"module"` basically tells you that even though gRPC_INSTALL was set to ON by you, we're setting it back to OFF because your gRPC_CARES_PROVIDER is set to use c-ares from git submodule (which wouldn't work well with the current CMakeLists.txt) - so you shouldn't expect anything to be installed (not even `grpc_cpp_plugin`.

We are working on improving the CMakeLists.txt to get around this limitation, but so far your best bet if you wan't to install gRPC using cmake is to follow the script from our distribtest: 
https://github.com/grpc/grpc/blob/2b0ab320c12cb807cf05b3295b7017d0ccbf66f5/test/distrib/cpp/run_distrib_test_cmake.sh#L56
