### ISSUE TITLE
grpc_cli does not support enums

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#13859]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes.
 
### What version of gRPC and what language are you using?
1.7.2 - C++ 
 
### What operating system (Linux, Windows, …) and version?
Linux, Windows 
 
### What did you do?
Tried to query the type of an enum member in grpc_cli and set an enum value. 
 
### What did you expect to see?
For query of enum type, it should return a list of the possible values. When trying to set it, it should accept the value.
 
### What did you see instead?
None of this worked. So if you want to set an enum value in the request object of grpc_cli, you can't query and even if you know the possible values in advance/through local files, you can't set it. The only workaround is to put the enum as an integer.   
 
### Anything else we should know about your project / environment?
More details here - https://groups.google.com/forum/#!searchin/grpc-io/grpc_cli%7Csort:date/grpc-io/uUwInoVRqSQ/nx9gpOIUDAAJ

**Comment by wataori** [comment]
Any updates? I think I'm also in same trouble. `grpc_cli` skips enum values. I use macOS High Sierra(10.13.6) and gRPC 1.14.2.

```proto
Enum Sex {
  MALE = 0;
  FEMALE = 1;
}

message UserResponse {
  uint32 id = 0;
  string name = 1;
  string email = 2;
  Sex sex = 3;
  uint32 age = 4;
}

message UserRequest {
  uint32 id = 0;
}

service UserService {
  rpc GetUser(UserRequest) return (UserResponse);
}
```

```sh
$ grpc_cli call 0.0.0.0:8080 UserService.GetUser 'id: 1'
connecting to 0.0.0.0:8080
id: 1
name: "Alex"
email: "abc@example.com"
age: 30

Rpc succeeded with OK status
```

**Comment by sanjaypujare** [comment]
I think grpc_cli should support enum values unless there is a technical reason not too.
