### ISSUE TITLE
[NEW] gcc 7 and -Werror=implicit-fallthrough 

### ISSUE THREAD

**Issue by okomarov** [grpc/grpc#13854]
### What version of gRPC and what language are you using?
1.8.2 
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 17.10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.2.0
 
### What did you do?
```
 $ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init
 $ make
```

### What did you expect to see?
 Successful compilation of source
 
### What did you see instead?
```
[C]       Compiling third_party/boringssl/crypto/bio/file.c
third_party/boringssl/crypto/bio/file.c: In function ‘file_ctrl’:
third_party/boringssl/crypto/bio/file.c:186:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
       num = 0;
       ~~~~^~~
third_party/boringssl/crypto/bio/file.c:187:5: note: here
     case BIO_C_FILE_SEEK:
     ^~~~
cc1: all warnings being treated as errors
Makefile:2569: recipe for target '/home/oleg/Downloads/grpc/objs/opt/third_party/boringssl/crypto/bio/file.o' failed
make: *** [/home/oleg/Downloads/grpc/objs/opt/third_party/boringssl/crypto/bio/file.o] Error 1
 ```
### Anything else we should know about your project / environment?
Related to #13640 and to closed #12536 and #12022

### Workaround
`make CFLAGS='-Wno-implicit-fallthrough'`

**Comment by jtattermusch** [comment]
Also related to https://github.com/grpc/grpc/issues/11376
