### ISSUE TITLE
Bazel build fails: 'grpc/fork.h' file not found.

### ISSUE THREAD

**Issue by mbabinski-at-google** [grpc/grpc#13862]
### What version of gRPC and what language are you using?
 1.8.2 C++
 
### What operating system (Linux, Windows, …) and version?
 Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang6
 
### What did you do?

Build with provided BUILD file.

### What did you expect to see?
Build succeeds. 
 
### What did you see instead?

external/grpc_git/src/core/lib/iomgr/fork_posix.cc:25:10: fatal error: 'grpc/fork.h' file not found
 
### Anything else we should know about your project / environment?

Looks like include/grpc/fork.h is missing from GRPC_PUBLIC_HEADERS?

**Comment by vjpai** [comment]
This was fixed as part of https://github.com/grpc/grpc/pull/13575 though I don't know if it's in 1.8.x at all

**Comment by mehrdada** [comment]
Closing as this should be fixed by https://github.com/grpc/grpc/pull/13829. Please ping the issue if it continues to be a problem. Thanks!
