### ISSUE TITLE
gRPC file generated for python gives error

### ISSUE THREAD

**Issue by cw-pratik** [grpc/grpc#13868]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
  Yes.
### What version of gRPC and what language are you using?
gRPC Version: 1.7
 Language: Python
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 2.7
 
### What did you do?
I generated gRPC files for python and the run a client using the generated python file.
 
### What did you expect to see?
 It should run normally
 
### What did you see instead?
The generated python file gave an error even before the start of the execution
 
I tried to find the issue and the issue was with an enum that I used. Here is how this issue can be reproduced.

Here is the proto file

```
syntax = "proto3";
package Service;

service MmvGrpcService
{
    rpc Func1(Details) returns (Details) {} 
}

message Details
{
  StatusEnum Status=1;
}

enum StatusEnum
{
    None = 0;
    Futuristic = 1;
    New = 2;
}

```

Then I generated the python files using the following command

`python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. mmv.proto`

Then when I try to use the mmv_pb2.py file in any code It gives this error:

```
  File "mmv_pb2.py", line 54
    None = 0
SyntaxError: cannot assign to None
```

I think the reason is `None` is a keyword in python used for `Null`

As soon as I replace None with something else like `NA`, It works!!

**Comment by masterX244** [comment]
Seems like a similar thing as https://github.com/grpc/grpc/issues/13810 where the GRPC codegen has no mechanism to use those names. (on some languages a easy workaround would be using fully qualified names for everything)

**Comment by mehrdada** [comment]
gRPC mostly relies on the `protoc` code generator from [google/protobuf](https://github.com/google/protobuf). I encourage you to file a bug on their issue tracker for the most expedient resolution. The `pb2.py` file is entirely generated by `protoc` and gRPC plugin does not have much say in what gets generated there.

**Comment by mehrdada** [comment]
@cw-pratik Since there's now an issue on the protobuf tracker, I will mark this issue as closed here for now as it can be singularly tracked there. Please ping this issue if there is still additional work necessary on the gRPC plugin side after a resolution is reached on `protoc` side.
