### ISSUE TITLE
Feature Request: Add ability to limit plugins available on a Server

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#13860]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes.

### What version of gRPC and what language are you using?
1.7.2 - C++ 
 
### What operating system (Linux, Windows, …) and version?
Linux/Windows 

Details at https://groups.google.com/forum/#!searchin/grpc-io/grpc_cli%7Csort:date/grpc-io/uSl-cC3z6jk/wccDi2EjDAAJ 

Thanks.

**Comment by yashykt** [comment]
There's been a reply on the group.
