### ISSUE TITLE
do_iocp_work() will not exit after one socket connect failed

### ISSUE THREAD

**Issue by boolking** [grpc/grpc#1387]
On Win7:
1. Run grpc-common/cpp/helloworld/greeter_client first
2. After grpc client failed to connect, run greeter_server
3. Client will connect and call SayHello() successfully but will never exit, and main thread wait on grpc_iocp_shutdown() because g_orphans will never be 0

It seems that a socket is added to IOCP incorrectly as orphan socket after ConnectEx failed(with error code 10061).
And what is the g_orphans in iocp_windows.c for?

**Comment by nicolasnoble** [comment]
Oh that's interesting. I think I know how to fix that one.

The reason for g_orphans is kind of tied to what you're experiencing. Kind of. If we are closing a socket, we have to increase that counter, basically. But if the OS does that for us, we shouldn't. And that's the bug you're having.

**Comment by nicolasnoble** [comment]
I believe this one was fixed.
