### ISSUE TITLE
How to use protobuf 3.0.0 with grpc 1.8.2?

### ISSUE THREAD

**Issue by gogo40** [grpc/grpc#13888]
Hi,
 
I`m using gRPC 1.8.2 and I am needing the C++ and python plugins, exclusively. I did a workaround to work with protobuf 3.0.0 (erasing manually the php plugin), but this is ugly, I really need a more correct solution.

My grpc server is being embedded in a separated thread running in a Qt Application (Qt 5.9 from ubuntu repository). As I am using QWebEngine (that uses chromium), I have to use protobuf 3.0.0 due a version conflict between the protobuf from operating system and the one from grpc.
 
 I am using Ubuntu 17.10 and gcc 7.2.0.

To reproduce this error, try to use protobuf 3.0.0. To "fix" the building problem, you have to erase the php plugin.

I`m needing some flag to disable php plugin in CMakeLists.

There are some incompatibility between grpc 1.8.2 and protobuf 3.0.0?

Thank you in advance.

**Comment by Croydon** [comment]
Read the changelog: https://github.com/grpc/grpc/releases/tag/v1.8.0

**Comment by stanley-cheung** [comment]
Is there specific reason you have to use protobuf 3.0.0 but not a more recent version?

**Comment by stanley-cheung** [comment]
The newer version of grpc requires protobuf 3.5.0+. Back at version 1.8.x (and in fact, much earlier than 1.8.x), we should have updated the Makefile to require at least protobuf 3.1.0+ above (that's when protobuf added PHP support).

**Comment by gogo40** [comment]
@stanley-cheung We changed our architecture and the problem is solved. Now we can use a more recent grpc.
