### ISSUE TITLE
GRPC_LINUX_EPOLL is not defined

### ISSUE THREAD

**Issue by bigquant** [grpc/grpc#13885]
when running the helloworld example (python), it shows the error below. How to remove this error message?

python 3.5.2 / Ubuntu 16.04

```
E1229 15:07:06.653634946   11024 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1229 15:07:06.653705753   11024 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1229 15:07:06.653728914   11024 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
```

**Comment by ncteisen** [comment]
This will be addressed in #13882

**Comment by bigquant** [comment]
@ncteisen thanks. Is there some workaround to disable this message now?

**Comment by ncteisen** [comment]
Besides removing those offending `gpr_log(...)` lines, unfortunately no. We will get them removed ASAP

**Comment by mehrdada** [comment]
1.8.3 has been published on PyPI. Closing. Please let me know if the issue persists.
