### ISSUE TITLE
bazel workspace?

### ISSUE THREAD

**Issue by huahang** [grpc/grpc#1389]
Where should I put the grpc folder inside a bazel workspace relative to the WORKSPACE file?

**Comment by nicolasnoble** [comment]
There's no mandatory location to place the grpc folder in. The Bazel BUILD file is self-contained, and is relative to itself.

My personal recommendation however would be to place it in third_party/grpc. Then you can use the target //third_party/grpc:grpc++ as a dependency for your own targets.

**Comment by huahang** [comment]
When I tried to build grpc in a workspace like this, there was some error like the following:

    $ bazel build third_party/grpc:grpc++
    ERROR: /data/users/huahang/Desktop/sample_bazel_workspace/third_party/grpc/BUILD:574:1: no such target '//external:protobuf_clib': target 'protobuf_clib' not declared in package 'external' defined by /data/users/huahang/Desktop/sample_bazel_workspace/WORKSPACE and referenced by '//third_party/grpc:grpc++'.
    ERROR: Loading failed; build aborted.
    INFO: Elapsed time: 0.184s

It seems that grpc's dependencies like protobuf and openssl are missing?

**Comment by nicolasnoble** [comment]
Yes, you need to bind openssl and protobuf to wherever you have them:

http://bazel.io/docs/build-encyclopedia.html#bind

**Comment by huahang** [comment]
Aha! I think bind and external are great!

However, when I was trying to create a BUILD file for openssl, it's a bit difficult since there are files written in assembly language (for hardware acceleration of cryptography algorithms) and it's different depending on the operating system and CPU architecture. Do you have an internal BUILD file in Google that can be open sourced?

**Comment by nicolasnoble** [comment]
Well, I wouldn't suggest going with an actual BUILD file to build OpenSSL from the source, that'd be a bit... overwhelming. What I'd suggest however is to use the trick that you can specify a .a library as a source file.

So what you can do is the following: build OpenSSL from sources using its ./Configure script, with the appropriate install prefix so that it installs somewhere into your project's workspace. From here, your BUILD file is simply something along these lines:

```
cc_library(
    name = "openssl",
    srcs = glob(["lib/*.a"]),
    hdrs = glob(["include/*.h"]),
)
```

**Comment by jcanizales** [comment]
A `BUILD` file for BoringSSL should be trivial to create, given how easy it was to create a Cocoapods spec for it: https://github.com/grpc/grpc/blob/master/src/objective-c/BoringSSL.podspec#L69

**Comment by traviskaufman** [comment]
I don't think grpc should rely on external dependencies unless it explicitly specifies in the documentation what those external dependencies are and how they can be added. For example, I was only able to find information on them within [Tensorflow's workspace file](https://github.com/GPflow/tensorflow/blob/master/tensorflow/workspace.bzl)

**Comment by traviskaufman** [comment]
FYI tensorflow has a [BoringSSL BUILD file](https://github.com/tensorflow/tensorflow/blob/master/boringssl.BUILD) that could be useful. You could theoretically DL the source and add the build file in.
