### ISSUE TITLE
[Question] About push notification from Server to Client

### ISSUE THREAD

**Issue by thincal** [grpc/grpc#13894]
Hi,

Does the gRPC support the push notification from server to client ?
It seems that many people say the bi-directional stream is a way, but I can't understand how does the server call back to client just like the callback ?

Thanks,
Song

**Comment by vjpai** [comment]
It won't be a callback. The client needs to invoke an RPC and then the server will just write on it when it wants to send a notification. This could be a unary RPC if the client just wants to wait for the next push notification, server-side streaming if the client wants to collect a sequence of server messages, or bidirectional streaming if the client will collect a sequence of messages and also send feedback or further information to the server.

**Comment by thincal** [comment]
Thanks vjpai, but how to start a long-lived streaming RPC from the client to server and keep reading on it ? does that mean client should maintain a thread to keep reading ?

Any example in c++ ?

**Comment by vjpai** [comment]
It's your choice of whether to use the synchronous API in C++ or the async API. If you use the sync API, you should probably have a separate thread in the client API to Read for push notifications. If you use the async API, you can just start the `Read` and then do a `CompletionQueue::Next` operation until you get the tag of the `Read`; that works if you don't want to reserve a thread.

We don't have an existing example for this; that could be a feature request for the future.

**Comment by sivabudh** [comment]
@vjpai 
In your opinion, was gRPC built for publish / subscribe or observer pattern (where clients get updates only after every server's write).

**Comment by vjpai** [comment]
A textbook "remote procedure call" is what gRPC calls a unary call: the client sends a request to the server and gets a single response. However, gRPC also supports streaming RPCs. The initial communication must come from the client (though it can just be a method name, not a payload message), but the data after that can flow from client-to-server, from server-to-client, or both directions. The patterns you've described are suited for bidirectional or server-side streaming RPCs. For example, in the observer pattern, the clients register themselves as observers to the server (which plays the role of the observer pattern subject) by invoking a server-streaming RPC on the subject, and the subject will then send its updates back to the clients as message responses on that RPC. You can set up similar communications for pub-sub, though it depends a lot on if you use brokerless or brokered.

**Comment by noamyogev84** [comment]
As @sivabudh describes, it appears to be not trivial to maintain a persistent client connection, and be able to actively push messages to a specific client without looping in a server stream method and keeping a collection of streams to manage the clients.
