### ISSUE TITLE
Published grpc-ruby packages aren't yet pre-built for ruby 2.5

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#13908]
This issue tracks progress for publishing a grpc-ruby package with a pre-built ruby 2.5 library.

Note currently, it should be possible to use grpc on ruby 2.5 by installing the source-only package and building the gem from source.
 

-----------------------------

This is planned for the 1.9 release right now.

Remaining TODO's for this:
* Update Mac workers to be able to build against ruby 2.5 (and 2.1.6).

**Comment by carlpartridge** [comment]
Any idea when 1.9 might be released?  

Currently having this issue: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1913 and installing from source did not work :(

Thanks for your time!

**Comment by apolcyn** [comment]
We plan to cut a pre-release with 2.5 libraries pre-built in the next few days.

**Comment by apolcyn** [comment]
grpc `1.9.0.pre1`  was just pushed to rubygems and should now be useable on ruby 2.5. with `gem install --prerelease`

**Comment by anthraxx** [comment]
@apolcyn can you please just push a 1.8.x one with ruby 2.5? this is really a blocker

**Comment by apolcyn** [comment]
I’d like to publish the ruby gem with 2.5 support soon but with the actual 1.9 release scheduled mid next week the plan is to wait. There shouldn’t be any incompatibilities with 1.9 release but the build system was somewhat changed to add 2.5 support so backporting it as a patch release is not ideal

**Comment by flyfy1** [comment]
It has been 13 days.. any update on this issue? I was trying to install `google-cloud` for ruby v2.5 but was blocked cuz of grpc..

**Comment by apolcyn** [comment]
Currently we are trying to first resolve an issue with the package build changes for ruby 2.5 support that would cause a breakage for at least some projects: https://github.com/google/protobuf/issues/4210. The potential breakage affects a small edge case but I'd like to see if we can fix it before releasing.

**Comment by scriptfans** [comment]
+1 for this.

**Comment by apolcyn** [comment]
`1.9.1` packages were just pushed, which now support ruby 2.5

FTR though, google/protobuf#4210 wasn't fully resolved and there is a known edge case that this release breaks: code that was previously checking, directly or indirectly, the health of all `grpc_c.so` binaries as observed by `ldd` in the `x86_64-linux` platform-specific gem.

**Comment by nicolasnoble** [comment]
Please open a new issue for your specific problems, instead of bumping unrelated, old, and resolved issues.
