### ISSUE TITLE
High CPU usage in Python when client side keepalive is on

### ISSUE THREAD

**Issue by ewang** [grpc/grpc#13924]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
Python gRPC client 1.8.3
Go gRPC server 1.8.2
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04
 
### What did you do?
We turned on the following channel options:
('grpc.keepalive_time_ms', 300000)
('grpc.keepalive_permit_without_calls', 1)

### What did you expect to see?
Normal keepalive calls
 
### What did you see instead?
CPU being hogged by gRPC.

Thread profile seems to show significant CPU spent in _poll_connectivity. But that might not be the real reason since the profile seems to look similar with keepalive turned off (but CPU usage is no longer high).

The ASG cluster's CPU usage went from under 10% to nearly 100% when the above keepalive options were enabled.
 
### Anything else we should know about your project / environment?
gRPC Python client running in a web application via gunicorn sync workers

**Comment by ewang** [comment]
Might be related to #13906. Testing and will report back.

**Comment by kpayson64** [comment]
Can you run your program with the environment variables 
```GRPC_VERBOSITY=debug GRPC_TRACE=api,polling```  That might shed some more light on the issue.

**Comment by ewang** [comment]
@kpayson64 I ran it with the --no-binary workaround in #13906 and the issue is no longer there.
