### ISSUE TITLE
error: cannot find module 'Error: Cannot find module 'test/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-glibc/grpc_node.node''

### ISSUE THREAD

**Issue by MDOpus** [grpc/grpc#13925]
I am trying to use google-cloud/speech. I am able to install the module @google-cloud/speech but when trying to run the program, getting this error.

**Comment by murgatroid99** [comment]
We are aware of this general problem, but without more information about the environment, the output at install time, and the full error output, we can't help solve this specific instance.
