### ISSUE TITLE
php: Missing releases from packagist

### ISSUE THREAD

**Issue by marcelcorso** [grpc/grpc#13944]
The last release of the grpc library for composer (php) is 1.6.0. 
https://packagist.org/packages/grpc/grpc

**Comment by stanley-cheung** [comment]
That's because there's no change in the composer package between 1.6.0 and 1.8.0. I tried to tag the same commit with a newer release name but composer doesn't seem to want to pick that up as a separate release.

**Comment by marcelcorso** [comment]
Got it, thanks.
I fixed the script that was using the same version for the pecl package and
the composer lib.

It would be easier to have everything as the same version but I get that in
this case it's not worth the effort.

Thanks again

**Comment by Matan** [comment]
Isn't this: https://github.com/grpc/grpc/issues/12898 a change since v1.6.0?
