### ISSUE TITLE
Investigate and enable epoll under manylinux for Python binary distributions

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#13949]
[Per @jonparrot](https://github.com/grpc/grpc/issues/13906#issuecomment-356097581), `manylinux1` should support `epoll`. The possibility of compiling `epoll` to Python binary packages should be re-evaluated:

> epoll was introduced in glibc 2.3.2, manylinux1 supports glibc <= 2.5 so it should be possible to enable epoll without breaking manylinux1 compatibility.

**Comment by mehrdada** [comment]
As tried in https://github.com/grpc/grpc/pull/13951, `epoll_create1` which is the syscall used by gRPC is unavailable under `manylinux1`

**Comment by kpayson64** [comment]
Can we use ```epoll_create``` instead?

**Comment by mehrdada** [comment]
@kpayson64 I believe that would be a fundamental change: `epoll_create` has different semantics and does not support the flag we pass to `epoll_create1`, so even if possible to make `epoll_create` work, it would require substantial changes to the polling engine, and we might as well fork it into another polling engine specific to Python.

**Comment by kpayson64** [comment]
https://github.com/grpc/grpc/blob/3ea0e2d80443502c12203dfc5b24112c69ccda59/src/core/lib/iomgr/ev_epollex_linux.cc#L439

It looks like the only flag we pass is EPOLL_CLOEXEC?  We should be able to replicate that exact behavior with an additional call to ```fcntl(FD_CLOEXEC)```

**Comment by mehrdada** [comment]
Yes as far as I know that is the only flag we pass to it. If there is a way to duplicate that exactly it should work, but I am not well-versed on the semantics of the flag.

**Comment by mehrdada** [comment]
@nicolasnoble Is there a catch to replacing `epoll_create1` with `epoll_create` immediately followed by `fcntl`?  Can their non-atomicity be a problem?

**Comment by mehrdada** [comment]
Summary of the offline discussion with @nicolasnoble: we should ifdef on libc version and use epoll_create followed by setting the flag.
