### ISSUE TITLE
Continuous errors in client trace "waiting for connection state change"

### ISSUE THREAD

**Issue by alexvy86** [grpc/grpc#13959]
As long as a client has an open channel, an `Operation failed` error is logged every second when `GRPC_TRACE` contains `op_failure`, but the message doesn't indicate (to me) any real failure, it just pollutes the logs.

This makes me think if a channel should be created and disposed of ASAP (e.g. create it at the start of a web request and shut it down when the request completes), but that goes somewhat against the documentation [here](https://grpc.io/grpc/csharp/api/Grpc.Core.Channel.html):

> Represents a gRPC channel. Channels are an abstraction of long-lived connections to remote servers. More client objects can reuse the same channel. Creating a channel is an expensive operation compared to invoking a remote call so in general you should reuse a single channel for as many calls as possible.

Unless the documentation is not clear, and keeping a single channel alive throughout the whole lifetime of an application is not ideal...?

### What version of gRPC and what language are you using?
1.8.3, C# 
 
### What operating system (Linux, Windows, …) and version?
Windows 10 Pro 1709, and also happens on Docker containers on Ubuntu 16.04.2 LTS.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Using the C# libraries. 
 
### What did you do?
Simplest repro: ran the Greeter sample application with `GRPC_TRACE` set to `op_failure` and added a `Console.ReadKey()` in the client before shutting down the GRPC channel.
Fork of the sample app with the necessary changes ~~[here](https://github.com/alexvy86/grpc/tree/infinite-client-errors/examples/csharp/helloworld-from-cli)~~ (broken after rebase on top of upstream's latest changes, new link in the most recent comment).
 
### What did you expect to see?
No errors.
 
### What did you see instead?
The same error being logged each second:
`E0109 13:29:51.999381 1758658132704 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x64\src\core\lib\surface\completion_queue.cc:659: Operation failed: tag=00000199782E1360, error={"created":"@1515526191.999000000","description":"Timed out waiting for connection state change","file":"C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\channel_connectivity.cc","file_line":133}`

**Comment by alexvy86** [comment]
Still seeing this error after merging upstream changes from this repo, and upgrading the NuGet dependencies as follows:
- `Google.Protobuf` to version 3.5.1
- `Google.Protobuf.Tools` to version 3.5.1
- `Grpc` to version 1.10..1
- `Grpc.Tools` to version 1.10.1

Minor changes in the error message:
`E0408 22:26:20.989636 2289497194416 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\completion_queue.cc:634: Operation failed: tag=000002152A949FA0, error={"created":"@1523244380.989000000","description":"Timed out waiting for connection state change","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\channel_connectivity.cc","file_line":133}`

[Updated reference](https://github.com/alexvy86/grpc/tree/0b612519084cc85bbd9892415311d42c26ce3010/examples/csharp/helloworld-from-cli) to sample repro in my forked repo.

**Comment by jtattermusch** [comment]
I think this was addressed by merging https://github.com/grpc/grpc/pull/14577 (available starting from v1.13.0, but you should upgrade to the newest version anyway).
