### ISSUE TITLE
[question] Does the C# implementation have backpressure for streams?

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [grpc/grpc#13955]
Hello, I have a gRPC service that accepts streaming messages from a client. The client sends a finite sequence messages to the server at a high rate. 

The result is the server buffering a large number of messages (> 1GB) and it's memory usage skyrocketing  and then slowly draining as it handles them.

I find that even if I await all async calls, the client just keeps pushing messages as fast as it can. I would like the client to slow down.

I have implemented an explicit `ack` response that the client waits for before sending the next message, but since http/2 already has flow control semantics built in I feel like I'm reinventing the wheel a bit.

I have two questions actual questions.

1) Does the C# implementation automatically apply backpressure? For example, if the consuming side is slow to call MoveNext on the async stream, will the client side take longer to return from it's calls to WriteAsync?

2) Does the C# implementation of gRPC have any configurable way of limiting the buffering of messages for a streaming rpc call. For example, capping the number of buffered messages or limiting the amount of space in the call's buffer.

**Comment by AlgorithmsAreCool** [comment]
@Falco20019 Thanks for responding, I've been looking around the code trying figure it out but haven't had much luck yet.

**Comment by jtattermusch** [comment]
flow control is expected to work in all gRPC languages as we consider it one of the key features for a scalable RPC system.

More specifically:
1. if one side is slow to request messages (MoveNext()), the sending side will eventually be "blocked" when sending (WriteAsync() will take longer to succeed - and you can only have on WriteAsync() operation in progress per call).
2. I believe such parameters can be configured via C-core channel argument (ChannelOption in c#).
https://github.com/grpc/grpc/blob/69d3e0984da394d1ea06edbe26de76d124c6eaf3/include/grpc/impl/codegen/grpc_types.h#L135

**Comment by jtattermusch** [comment]
Please reopen if what I described doesn't seem to work as expected.
