### ISSUE TITLE
how to use health check?

### ISSUE THREAD

**Issue by YuleiXiao** [grpc/grpc#13962]
I see the health check document, but I am confused. Is there any example code to show how to enable health check?

I call ```EnableDefaultHealthCheckService(true)``` before server start, is it open health check? Do I need something else?

**Comment by YuleiXiao** [comment]
I call EnableDefaultHealthCheckService(true) before server start, is it open health check? Do I need something else?

**Comment by Falco20019** [comment]
See [health_service_end2end_test.cc](https://github.com/grpc/grpc/blob/master/test/cpp/end2end/health_service_end2end_test.cc) for an example. If you have enabled it, you should be fine. [health_service_end2end_test.cc / VerifyHealthCheckService](https://github.com/grpc/grpc/blob/master/test/cpp/end2end/health_service_end2end_test.cc#L192) shows an example verifier code you could try.

**Comment by YuleiXiao** [comment]
@Falco20019 thanks, I saw this file yesterday, but I am still confused. After ```EnableDefaultHealthCheckService```, I saw server had enable health-checking from log, but client do nothing. I do not know client how to do about health-checking.

**Comment by Falco20019** [comment]
```
std::string server_address("0.0.0.0:50051");

// Server code:
EnableDefaultHealthCheckService(true);
ServerBuilder builder;
builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
std::unique_ptr<Server> server(builder.BuildAndStart());

HealthCheckServiceInterface* service = server->GetHealthCheckService();
const grpc::string kHealthyService("healthy_service");
service->SetServingStatus(kHealthyService, true);

// Client code:
HealthCheckRequest request;
request.set_service(kHealthyService);

HealthCheckResponse response;
ClientContext context;
std::shared_ptr<Channel> channel = CreateChannel(server_address, InsecureChannelCredentials());
std::unique_ptr<Health::Stub> hc_stub = grpc::health::v1::Health::NewStub(channel);
Status s = hc_stub->Check(&context, request, &response);
EXPECT_EQ(Status::OK.error_code(), s.error_code());
if (s.ok()) {
	EXPECT_EQ(HealthCheckResponse::SERVING, response.status());
}

server->Shutdown();
```

**Comment by YuleiXiao** [comment]
@Falco20019 Clients must write code to call ```Check``` manually? Not like server only ```EnableDefaultHealthCheckService```? I thought it is only a option.

**Comment by Falco20019** [comment]
This service is meant mostly for load balancers. You can just call a client method even if the client is not there yet or if there are network problems. GRPC will block the call and retry until the client can execute the call or the deadline is defined and reached. For that you don’t have to enable this option at all.

**Comment by yang-g** [comment]
@YuleiXiao what do you want to achieve? Indeed the service makes more sense for load balancers and (centralized) health checkers.

**Comment by YuleiXiao** [comment]
@yang-g I thought health check can be used to check if network connection is OK

**Comment by yang-g** [comment]
@YuleiXiao 
Yes. Probing the health check service can be a way to check the connection but it is a bit heavy weight, as it does not only check the connection is alive but also check whether the server is actively serving the rpcs and it also requires a grpc client.

Assuming you are using C++ API, there are other ways you can monitor the connectivity. You may want to use the C++ channel state API e.g. https://github.com/grpc/grpc/blob/master/include/grpc++/impl/codegen/channel_interface.h#L74

There is also built-in keep-alive style checks that can be tuned with channel arguments here:
https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L217
