### ISSUE TITLE
Eliminate use of Python 3.4 in all tests

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#13978]
@nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
With 3.7 right around the corner it's now time to upgrade all our tests from using Python 3.4. Probably to 3.6, but maybe to 3.7 if we're feeling ambitious?

At this point we probably wouldn't even bother to fix a 3.4-only defect if one were reported.

**Comment by lidizheng** [comment]
Python 3.4 is eliminated from our test automations, no longer serve as default Python 3 version, but still able to build/test with `run_tests.py`. The new default version is Python 3.7. I think this issue is resolved. If any more test cases is still rely on Python3.4, please reopen this issue.
