### ISSUE TITLE
Bazel build fails in Windows for v1.8.4

### ISSUE THREAD

**Issue by f9rocket** [grpc/grpc#13979]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes, this seems to be related to gRPC's bazel build system.

### What version of gRPC and what language are you using?
 
 I'm using v1.8.4 and C++.

### What operating system (Linux, Windows, …) and version?
 
Windows 10.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
VS2017
 
### What did you do?

I created an empty bazel project with the following WORKSPACE file:

```
workspace(name = "grpc_test")

http_archive(
	name = "com_github_grpc_grpc",
	urls = ["https://github.com/grpc/grpc/archive/v1.8.4.zip"],
	strip_prefix = "grpc-1.8.4",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```

I then ran 

```
bazel build @com_github_grpc_grpc//:grpc++_unsecure
```

### What did you expect to see?
 
A successful build.
 
### What did you see instead?
 
```
ERROR: C:/tmp/fmmw2bog/external/com_github_cares_cares/BUILD.bazel:59:1: C++ compilation of rule '@com_github_cares_cares//:ares' failed (Exit 2)
c:\tmp\fmmw2bog\execroot\grpc_test\external\com_github_cares_cares\setup_once.h(60): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
``` 

### Anything else we should know about your project / environment?

Nope.

**Comment by rongjiecomputer** [comment]
Building GRPC with Bazel on Windows does not support C-ARES. You have to build with `bazel build --define grpc_no_ares=true`.

**Comment by f9rocket** [comment]
@rongjiecomputer Unfortunately, that doesn't work either:

```
> build @com_github_grpc_grpc//:grpc++_unsecure --define grpc_no_ares=true

INFO: Analysed target @com_github_grpc_grpc//:grpc++_unsecure (20 packages loaded).
INFO: Found 1 target...
ERROR: C:/tmp/fmmw2bog/external/com_github_cares_cares/BUILD.bazel:59:1: C++ compilation of rule '@com_github_cares_cares//:ares' failed (Exit 2)
c:\tmp\fmmw2bog\execroot\grpc_test\external\com_github_cares_cares\setup_once.h(60): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
Target @com_github_grpc_grpc//:grpc++_unsecure failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.047s, Critical Path: 0.32s
FAILED: Build did NOT complete successfully
```

**Comment by apolcyn** [comment]
@rongjiecomputer this is a guess but if you're able to depend on grpc as a local dependency, are you able to see if this patch fixes the issue?
 https://github.com/apolcyn/grpc/commit/f1b933ce7fe36d150d21f03ad60a88c63a92b350

**Comment by f9rocket** [comment]
@apolcyn grpc++_unsecured builds with your patch!
