### ISSUE TITLE
client channels do not reconnect after server crash

### ISSUE THREAD

**Issue by tainguyennc** [grpc/grpc#14014]
### What version of gRPC and what language are you using?
Version 1.8.3 C++
 
### What operating system (Linux, Windows, …) and version?
Linux 26ee74637e50 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (GCC) 6.4.1 20170727 (Red Hat 6.4.1-1)
 
 
### What did you do?
We have 2 GRPC streaming clients in the same process connecting to a server via unix domain socket. When we shutdown the server and restart, the clients try to reestablish the connection to the server but the client channel never get into CONNECTING state.
If there is only one client then the connection is reestablished successfully
 
### What did you expect to see?
We expect both clients are able to reconnect to the the server. 
 
### What did you see instead?
client_channel remains in IDLE state and never get into CONNECTING or READY state
[grpc_issue.txt](https://github.com/grpc/grpc/files/1627819/grpc_issue.txt)
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
bool GrpcSubscriber::try_connect(const std::chrono::milliseconds &timeout)
{
    bool success = false;
    int cnt = (timeout.count() + 99) / 100;
    auto state = channel_->GetState(false);

    while ((cnt-- > 0) && (state != GRPC_CHANNEL_READY)) {
        xxx::sleep_for(std::chrono::milliseconds(100));
        logging::Logger *logger = logging::getLogger(name_.c_str());
        logger->info() << "Try to connect channel " << (void *) channel_.get();
        state = channel_->GetState(true);
        logger->info() << "channel " << (void *) channel_.get() << " State: "<< state;
    }
    if (state == GRPC_CHANNEL_READY) {
        success = true;
    }
    return success;
}

bool GrpcSubscriber::create_reader()
{
    bool success = false;
    channel_ = grpc::CreateChannel(
                       address_, grpc::InsecureChannelCredentials());
    if (try_connect(std::chrono::milliseconds(1000))) {
        context_ = std::make_unique<grpc::ClientContext>();
        stub_ = SubscribeService::NewStub(channel_);
        reader_ = stub_->Read(context_.get(), request_);
        if (reader_) {
            reader_ready_ = true;
            success = true;
        }
    }
    reader_ready_ = success;
    return success;
}

**Comment by jtattermusch** [comment]
@vjpai   any suggestions here?

**Comment by tainguyennc** [comment]
We moved to 1.9.0-pre1 release and the problem goes away

**Comment by arajeeva** [comment]
@jtattermusch @nathanielmanistaatgoogle This issue seems be resolved in GRPC 1.10.0. Can we have confirmation & closure of issue (if true)?

**Comment by jtattermusch** [comment]
@vjpai  can you seems that this is resolved in gRPC 1.10, can you please link it to the PR that fixed it? (@dgq is OOO).

**Comment by vjpai** [comment]
Reassigning to @dgquintas to see which PR resolved this problem

**Comment by dgquintas** [comment]
@vjpai nicely timed.

Fixed by https://github.com/grpc/grpc/pull/13932 and https://github.com/grpc/grpc/pull/14170
