### ISSUE TITLE
Clearly document the cases where fork() is supported in grpc()

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#14055]
gRPC does not support `fork()` in general - i.e it is not safe for a gRPC application to call `fork()` as it can lead to undefined behavior.

As of release 1.7, we added *very limited* support to `fork()`; where it is safe for an application to call `fork()` as long as the application did not start any gRPC work (beyond calling `grpc_init()) prior to calling `fork()`

We need to do a better job at documenting this clearly - the fact that gRPC does not support fork() in general and the only time it is safe to call fork() is if the application did not start any gRPC work.

We have been noticing several issues caused due to fork()  (and this is mainly due to grpc users not realizing that fork() is not supported)

**Comment by sreecha** [comment]
Reassigning to @kpayson64 .

**Comment by zhanghaohit** [comment]
I noticed a fork.h header. does it provide the support for fork?

void grpc_prefork();
void grpc_postfork_parent();
void grpc_postfork_child();

Thanks.

**Comment by srini100** [comment]
That is the intention but first [this bug](https://github.com/grpc/grpc/issues/14258) needs to be fixed to do fork/exec. 

@zhanghaohit what is your use case?

**Comment by zhanghaohit** [comment]
My use case is:
I have to fork a new process, which will take over the job from the main process. It means, after the forking, the main process will not do anything with grpc.

But after the child process finished its job, it just exists. Then the main process will fork a new child process again.

So I have to fork multiple times from the main process.

Can I achieve this in the current grpc implementation?

Thanks.

**Comment by srini100** [comment]
@zhanghaohit,  forking with an active stub will put you in a situation where parent and child will share the same connection. gRPC currently doesn't cleanup FDs in child process. IMO, recreating the stub in child process should work.

**Comment by zhanghaohit** [comment]
@srini100 Thanks for your reply. 

Yes. I did recreate the stub in the child process. In my case, do I need to call grpc_prefork(), grpc_postfork_parent(), grpc_postfork_child() also?

But anyway, no matter I call grpc_*fork_* or not, it will hang there after second fork.

**Comment by srini100** [comment]
These functions are called internally by gRPC. You shouldn't call these.

**Comment by zhanghaohit** [comment]
Oh. ic. but still cannot get it to work by recreating the stub in the child process. It will hang after the second fork.

**Comment by kpayson64** [comment]
Closed via #14870
