### ISSUE TITLE
C++-ize core transport API

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#14062]
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
Core, C++
 
### What operating system (Linux, Windows, …) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 N/A

### What did you do?

Read the code in `src/core/lib/transport`
 
### What did you expect to see?
 
Idiomatic C++ code 

### What did you see instead?
 
C-style code

**Comment by markdroth** [comment]
We should seriously consider merging the filter and transport APIs -- i.e., the transport would effectively become the bottom filter in the stack.  Let's have some design discussions about the trade-offs here before we invest any time in this.

**Comment by vjpai** [comment]
Agreed; I think that makes the most sense since they have a lot in common already and move the same chunk around. Is there already an issue filed for that?

**Comment by markdroth** [comment]
No issue, just the PR I took over from Craig in #14026.
