### ISSUE TITLE
Fix and Enforce Important clang-tidy Checks

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#14085]
https://clang.llvm.org/extra/clang-tidy/checks/list.html

The more the merrier

**Comment by markdroth** [comment]
Let's make sure we have a check that will catch the undefined behavior warning triggered when #16167 was imported:

```
undefined behavior, destination object type 'grpc_core::LoadBalancingPolicy::PickState' is not TriviallyCopyable
```

See comment in the PR pointing to the affected code.
