### ISSUE TITLE
grpc with ssl can not connect to server on some machine

### ISSUE THREAD

**Issue by bpxeax** [grpc/grpc#14083]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 
 1.8.0
### What operating system (Linux, Windows, …) and version?
 
 client Windows7, server linux
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 client dotnet 4.5, server golang 1.9.2
### What did you do?
Use grpc with tls
 
### What did you expect to see?
 all client can connect to server
 
### What did you see instead?
some client can conenct to, but some others can not. Those error clients can telnet to server port, can pass ssl verify use openssl s_client and can connect to server without ssl. Here is the client grpc log:
 
[log.txt](https://github.com/grpc/grpc/files/1645602/log.txt)

**Comment by jiangtaoli2016** [comment]
@srini100 Looking at the logs, it seems to be connection issue rather than security issue. SSL handshake is not even started.

**Comment by srini100** [comment]
@jiangtaoli2016, thanks for looking into this.
@bpxeax, log is showing the connection is closed without errors. May be the server is closing it for some reason? Please provide more details.
