### ISSUE TITLE
grpc::ChannelArguments::SetSocketMutator() should either be removed or made usable.

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#14103]
### Should this be an issue in the gRPC issue tracker?

Yes.
 
### What version of gRPC and what language are you using?

1.9.0-dev 
 
### What operating system (Linux, Windows, …) and version?

Linux, macOS, Windows, this applies to any OS where gRPC is supported.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

C++. 
 
### What did you do?

Mostly read the documentation, but tried to use `grpc::ChannelArguments::SetSocketMutator()`

### What did you expect to see?

I expected the `grpc_socket_mutator` struct to be fully defined when including (a) ideally the `grpc++/grpc++.h` header, or (b) some other header installed by gRPC.  Alternatively, if the call is not supposed to be used by the application it should not be exposed through one of the public APIs, remove it completely, or move to some `internal` namespace.

### What did you see instead?
 
The `grpc_socket_mutator` is forward declared (in `include/grpc/impl/codegen/grpc_types.h`), the definition is in a header that does not get installed with gRPC (`src/core/lib/iomgr/socket_mutator.h`).

**Comment by vjpai** [comment]
Thanks for the observation; we need to either declare some of these as non-API or actually make them depend only on non-breakable features (which gRPC core structs are not).

**Comment by vjpai** [comment]
This will be resolved as part of #14648
