### ISSUE TITLE
mem leak in http_proxy.cc for no_proxy_str

### ISSUE THREAD

**Issue by vikasvashisht** [grpc/grpc#14119]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
v1.8.x 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 Val grind with a client connection to localhost with no proxy set for local host

### What did you expect to see?
 Clean valgrind run for establishing connection and clean up
 
### What did you see instead?
 Valgrind issue for mem leak in http_proxy.cc:109

You can do a quick code review to confirm the issue.
Local variable no_proxy_str is allocated memory but never freed.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jtattermusch** [comment]
It really looks like no_proxy_str is never freed.

https://github.com/grpc/grpc/blob/20e7074e4101b4fdbae1764caa952301b38957c4/src/core/ext/filters/client_channel/http_proxy.cc#L106

**Comment by jtattermusch** [comment]
Thanks for reporting this!

**Comment by vikasvashisht** [comment]
Thanks Jan.

I have one more issue where I can use some help and its probably fixed in a later version but I can use the help in identifying the patch that addresses this issue.
https://github.com/grpc/grpc/issues/14014

I will appreciate if someone can comment on this.
