### ISSUE TITLE
Failed to run cythonized grpc code: TypeError: Descriptors should not be created directly, but only retrieved from their parent.

### ISSUE THREAD

**Issue by bigquant** [grpc/grpc#14111]
grpc version: 1.8.4

If code files are compiled with cython (always_allow_keywords=True)，it raise error when running:

```
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```

It works well if we do not compile *_pb2.py

**Comment by nathanielmanistaatgoogle** [comment]
How much more can you share with us? On what platform are you working, and with what versions of operating system and Python interpreter? Are you building gRPC Python from source or downloading it from [the Cheese Shop](https://pypi.python.org)? With what attempted command are you seeing the error?

**Comment by bigquant** [comment]
OS: ubuntu 16.04
python: 3.5.2

```
sudo pip3 install cython==0.27.3 grpcio==1.8.4

git clone https://github.com/grpc/grpc.git
cd grpc/examples/python/helloworld

cythonize -i helloworld_pb2*

python3 greeter_server.py

```

and it shows errors

```
Traceback (most recent call last):
  File "greeter_server.py", line 21, in <module>
    import helloworld_pb2
  File "helloworld_pb2.py", line 35, in init helloworld_pb2 (/src/grpc/examples/python/helloworld/helloworld_pb2.c:1917)
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/descriptor.py", line 497, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```

**Comment by nathanielmanistaatgoogle** [comment]
I think I know why this is happening and it's a limitation (likely introduced with the intention that it would be a "guard rail" safety feature) in [Protocol Buffers](https://github.com/google/protobuf). Refile this issue [over there](https://github.com/google/protobuf/issues) and link it back here; I'm curious to see what they make of it.
