### ISSUE TITLE
cloud_to_cloud:go:ruby_server:timeout_on_sleeping_server 

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#14139]
https://sponge.corp.google.com/target?id=c9798eec-1a8a-4b36-8100-f196678ffad1&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

```
Failure
FATAL: 2018/01/22 21:22:17 &{0xc42009be60}.Send(_) = EOF
exit status 1
```

**Comment by matt-kwong** [comment]
Closing this because no PR has referenced this issue since it was opened, and this hasn't failed on master in the last 10 days.
