### ISSUE TITLE
Bazel: cc_grpc_library can't depend on a cc_proto_library

### ISSUE THREAD

**Issue by drigz** [grpc/grpc#14145]
### What version of gRPC and what language are you using?

20e7074e4101b4fdbae1764caa952301b38957c4 

### What operating system (Linux, Windows, …) and version?
 
Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc 4.8.4, bazel 0.9.0
 
### What did you do?

Build a service depending on a cc_proto_library:

```
> cat WORKSPACE
git_repository(
    name = "com_github_grpc_grpc",
    commit = "ac0808b107d73613191b66617a547a201871a845",
    remote = "https://github.com/grpc/grpc.git",
)

load("@com_github_grpc_grpc//:bazel/grpc_deps.bzl", "grpc_deps")

grpc_deps()

bind(
    name = "grpc_cpp_plugin",
    actual = "@com_github_grpc_grpc//:grpc_cpp_plugin",
)

bind(
    name = "grpc++_codegen_proto",
    actual = "@com_github_grpc_grpc//:grpc++_codegen_proto",
)
> cat src/messages.proto 
syntax = "proto3";

package helloworld;

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
> cat src/service.proto 
syntax = "proto3";

import "src/messages.proto";

package helloworld;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
> cat src/BUILD.bazel
load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")

proto_library(
    name = "messages",
    srcs = ["messages.proto"],
)

cc_proto_library(
    name = "messages_cc",
    deps = [":messages"],
)

cc_grpc_library(
    name = "service",
    srcs = ["service.proto"],
    generate_mock = False,
    proto_only = False,
    use_external = True,
    well_known_protos = True,
    deps = [":messages_cc"],
)
> bazel build src:service
```
 
### What did you expect to see?
 
Build succeeds.
 
### What did you see instead?
 
The build fails, because `cc_grpc_library` assumes the presence of a target called `_messages_cc_only`, which would be created by cc_grpc_library, but is not created by cc_proto_library.

```
ERROR: /usr/local/google/home/rodrigoq/git/bazeltest/grpc/src/BUILD.bazel:13:1: in deps attribute of proto_library rule //src:_service_only: rule '//src:_messages_cc_only' does not exist. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/255b0a538ff9ed77f751ada4321e0106/external/com_github_grpc_grpc/bazel/cc_grpc_library.bzl:34:14
ERROR: Analysis of target '//src:service' failed; build aborted: Analysis of target '//src:_service_only' failed; build aborted
INFO: Elapsed time: 0.272s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### Workaround

Create a copy of `:messages` called `:_messages_cc_only` - but this is quite messy. I could probably use `cc_grpc_library(proto_only=True, ...)` instead of `cc_proto_library`, but I don't want to force targets that depend on the `proto_library` target to use `:_messages_cc_only` (which has nothing to do with C++).

**Comment by g-easy** [comment]
This is still a bug. What can I do to help get this fixed?

I tried pursuing this in https://github.com/protocolbuffers/protobuf/pull/4508 but was told to file an issue with gRPC.

**Comment by g-easy** [comment]
Easy repro:

```
git clone https://github.com/g-easy/timestamp-proto.git
cd timestamp-proto
bazel build :foo_grpc
[...]
BUILD:17:1: no such target '@com_google_protobuf//:_timestamp_proto_only': target '_timestamp_proto_only' not declared in package ''
```

**Comment by gavinlinasd** [comment]
I have the same issue for this. Especially when I need to depend on an external dependency @com_google_api to enable RESTful api for my grpc service.

**Comment by peter-edge** [comment]
What is going on with this? This has been around for a year

**Comment by g-easy** [comment]
The `_messages_cc_only` workaround works for messages but not for services. I'm trying to build a `cc_grpc_library` for `@com_google_googleapis//google/devtools/cloudtrace/v2:trace_proto` to get [TraceService](https://github.com/googleapis/googleapis/blob/acb5253cd11cd43cab93eb153d6e48ba0fa5303d/google/devtools/cloudtrace/v2/tracing.proto#L37).

**Comment by g-easy** [comment]
I adapted my example from https://github.com/grpc/grpc/issues/14145#issuecomment-420742510 to follow the BUILD recommendations from https://github.com/grpc/grpc/pull/18955 and it works now!
