### ISSUE TITLE
grpc.core issue, when upgrading from 1.7.0 to 1.8.3

### ISSUE THREAD

**Issue by mwiegant** [grpc/grpc#14141]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes, we have a stacktrace of an error from the grpc.core library.
 
### What version of gRPC and what language are you using?
 
We were previously using version 1.7.0 of gRPC.core, our error now is from using version 1.8.3 of gRPC.core.
 
### What operating system (Linux, Windows, …) and version?
 
The OS is Windows 2012 R2 Standard, x64.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
We are using gRPC.core in a C# project with version 4.7.02046 of .NET.
 
### What did you do?
We have a application that communicates with Google Cloud Storage, then Google BigQuery, and then Google PubSub. The error appears to have occurred when sending a message to Google PubSub.
 
### What did you expect to see?
 
We expected to see no errors, and for messages to be sent to Google PubSub.
 
### What did you see instead?
 
What we actually saw was an error. with the stacktrace below. I can't say exactly if the intended messages were sent to PubSub but I suspect they were not.

System.MissingMethodException: The native method "grpcsharp_batch_context_reset" does not exist
   at Grpc.Core.Internal.UnmanagedLibrary.GetNativeMethodDelegate[T](String methodName)
   at Grpc.Core.Internal.NativeMethods..ctor(UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
 
### Anything else we should know about your project / environment?

Running our exact same code worked on version 1.7.0 but not on version 1.8.3 of gRPC.core

**Comment by jtattermusch** [comment]
I'd try cleaning and rebuilding your project from scratch. 
the `grpcsharp_batch_context_reset` function was added to the native library grpc_csharp_ext.dll  in v1.8.x as it seems that you still have and old version of the dll in your output directory.
Otherwise, I'm pretty sure the function is there as our continuous tests work and no one else had this problem so far (if the issue was real, gRPC C# wouldn't work at all for anyone).
