### ISSUE TITLE
Add an interop test for non-OK status

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1416]
There should be an interop test that requires the server to send a specific status code and details string, and the client to recieve that exact status.

**Comment by iamqizhao** [comment]
+1

**Comment by a11r** [comment]
There is a specification (named status_code_and_message) for getting the server to echo whatever status the client wants. (The spec uses a code of 2 matching unknown. ) This is now ready for implementation. I will get the C++ impl going.

**Comment by a11r** [comment]
The spec is done, and I have addedd a C++ interop test in #2808. This issue will be closed once I file corresponding issues against other languages to implement this interop test.

**Comment by a11r** [comment]
MOving this issue to GA milestone since the spec is done.

**Comment by ctiller** [comment]
Are there bugs for implementing the spec for each language?

**Comment by ctiller** [comment]
ping

**Comment by a11r** [comment]
Interop tests for status codes exist. See InteropClient::DoStatusWithMessage
