### ISSUE TITLE
TIMEOUT json_run_localhost:cpp_protobuf_async_streaming_from_client_qps_unconstrained_secure GRPC_POLL_STRATEGY=epollex 

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#14168]
2018-01-24 17:52:47,972 D0124 17:50:39.153540589   18156 ev_posix.cc:128]            Using polling engine: epollex
D0124 17:50:39.153633181   18156 dns_resolver.cc:294]        Using native dns resolver
D0124 17:50:39.155468907   18156 ev_posix.cc:128]            Using polling engine: epollex
D0124 17:50:39.155490824   18156 dns_resolver.cc:294]        Using native dns resolver
D0124 17:50:39.158323525   18161 ev_posix.cc:128]            Using polling engine: epollex
D0124 17:50:39.158432715   18161 dns_resolver.cc:294]        Using native dns resolver
I0124 17:50:39.158545089   18161 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
RUNNING SCENARIO: cpp_protobuf_async_streaming_from_client_qps_unconstrained_secure
I0124 17:50:39.159576663   18166 driver.cc:271]              Starting server on localhost:7948 (worker #0)
D0124 17:50:39.159798022   18166 ev_posix.cc:128]            Using polling engine: epollex
D0124 17:50:39.159830706   18166 dns_resolver.cc:294]        Using native dns resolver
D0124 17:50:39.160258539   18165 ev_posix.cc:128]            Using polling engine: epollex
D0124 17:50:39.160334159   18165 dns_resolver.cc:294]        Using native dns resolver
I0124 17:50:39.160402846   18165 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0124 17:50:39.160645549   18166 subchannel.cc:603]          New connected subchannel at 0xe2ec00 for subchannel 0x7f76600023a0
I0124 17:50:39.161323467   18169 qps_worker.cc:231]          RunServerBody: about to create server
I0124 17:50:39.161915934   18169 qps_worker.cc:69]           Starting server of type ASYNC_SERVER
I0124 17:50:39.163674923   18169 server_async.cc:94]         Sizing async server to 32 threads
I0124 17:50:40.075116579   18169 qps_worker.cc:239]          RunServerBody: server created
I0124 17:50:40.075270759   18169 qps_worker.cc:246]          RunServerBody: creation status reported
I0124 17:50:40.075426046   18166 driver.cc:327]              Starting client on localhost:25707 (worker #1)
D0124 17:50:40.075513709   18166 driver.cc:349]              Client 0 gets 64 channels
I0124 17:50:40.076023083   18166 subchannel.cc:603]          New connected subchannel at 0xe44c80 for subchannel 0x7f7660003af0
I0124 17:50:40.076412507   18174 qps_worker.cc:188]          RunClientBody: about to create client
I0124 17:50:40.076790767   18174 qps_worker.cc:50]           Starting client of type ASYNC_CLIENT STREAMING_FROM_CLIENT 0
I0124 17:50:40.077087594   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077141390   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077189255   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077229560   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077289030   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077326307   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077359457   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077398290   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077433737   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077476217   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077531979   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077574035   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077607885   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077645760   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077685445   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077724420   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077764300   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077806945   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077859155   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077897257   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077934684   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.077973275   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078006197   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078044167   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078083165   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078122279   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078160357   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078215065   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078256875   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078294187   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078330234   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078362959   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078404554   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078489477   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078531551   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078571773   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078611568   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078650975   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078689693   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078727155   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078763380   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078800193   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078835993   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078868941   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078906648   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078944653   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.078993548   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079038046   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079075438   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079111258   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079146721   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079190628   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079226055   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079272238   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079324198   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079380996   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079424671   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079463675   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079501098   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079537715   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079574223   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079610218   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079644443   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.079718895   18174 client.h:427]               Connecting to localhost:13934
I0124 17:50:40.177650460   19038 subchannel.cc:603]          New connected subchannel at 0x7f5010003480 for subchannel 0x7f5000003f50
I0124 17:50:40.188593687   19086 subchannel.cc:603]          New connected subchannel at 0x7f4f44003480 for subchannel 0x7f4f3c003f20
I0124 17:50:40.189052820   19045 subchannel.cc:603]          New connected subchannel at 0x7f4ff4003480 for subchannel 0x7f4fe4003ee0
I0124 17:50:40.189890228   19064 subchannel.cc:603]          New connected subchannel at 0x7f4fb4003480 for subchannel 0x7f4fac00a1c0
I0124 17:50:40.190289623   19047 subchannel.cc:603]          New connected subchannel at 0x7f4fec006030 for subchannel 0x7f4ffc009d70
I0124 17:50:40.190525456   19092 subchannel.cc:603]          New connected subchannel at 0x7f4f18003480 for subchannel 0x7f4f30009cf0
I0124 17:50:40.191461986   19075 subchannel.cc:603]          New connected subchannel at 0x7f4f84003480 for subchannel 0x7f4ffc021b60
I0124 17:50:40.191480519   19089 subchannel.cc:603]          New connected subchannel at 0x7f4f280035c0 for subchannel 0x7f500000fb40
I0124 17:50:40.191883553   19073 subchannel.cc:603]          New connected subchannel at 0x7f4f800035c0 for subchannel 0x7f5020029a00
I0124 17:50:40.192703387   19071 subchannel.cc:603]          New connected subchannel at 0x7f4f900035c0 for subchannel 0x7f507003a6e0
I0124 17:50:40.192709697   19085 subchannel.cc:603]          New connected subchannel at 0x7f4f400035c0 for subchannel 0x7f4f9c00adc0
I0124 17:50:40.193065590   19051 subchannel.cc:603]          New connected subchannel at 0x7f4fdc003480 for subchannel 0x7f4fe4009c10
I0124 17:50:40.194240375   19068 subchannel.cc:603]          New connected subchannel at 0x7f4fb00035c0 for subchannel 0x7f4fe4017250
I0124 17:50:40.194867328   19030 subchannel.cc:603]          New connected subchannel at 0x7f5034003480 for subchannel 0x7f502c003f20
I0124 17:50:40.195165655   19098 subchannel.cc:603]          New connected subchannel at 0x7f4f140035c0 for subchannel 0x7f5050021520
I0124 17:50:40.195678288   19023 subchannel.cc:603]          New connected subchannel at 0x7f504c003480 for subchannel 0x7f5050003f20
I0124 17:50:40.196688956   19020 subchannel.cc:603]          New connected subchannel at 0x7f5060003480 for subchannel 0x7f507000adc0
I0124 17:50:40.197029968   19080 subchannel.cc:603]          New connected subchannel at 0x7f4f600035c0 for subchannel 0x7f4fe401db00
I0124 17:50:40.198548261   19036 subchannel.cc:603]          New connected subchannel at 0x7f501c0035c0 for subchannel 0x7f502c00fb00
I0124 17:50:40.198998504   19096 subchannel.cc:603]          New connected subchannel at 0x7f4f100035c0 for subchannel 0x7f4fc4019880
I0124 17:50:40.200093458   19081 subchannel.cc:603]          New connected subchannel at 0x7f4f500035c0 for subchannel 0x7f505001aed0
I0124 17:50:40.201354110   19061 subchannel.cc:603]          New connected subchannel at 0x7f4fbc0035c0 for subchannel 0x7f502001bf50
I0124 17:50:40.201543933   19048 subchannel.cc:603]          New connected subchannel at 0x7f4fe80035c0 for subchannel 0x7f4ffc01b9c0
I0124 17:50:40.208775775   19019 subchannel.cc:603]          New connected subchannel at 0x7f506c003480 for subchannel 0x7f5070005420
I0124 17:50:40.208803491   19066 subchannel.cc:603]          New connected subchannel at 0x7f4fa8003480 for subchannel 0x7f4f9c003ee0
I0124 17:50:40.209645294   19090 subchannel.cc:603]          New connected subchannel at 0x7f4f2c0035c0 for subchannel 0x7f502002acd0
I0124 17:50:40.210289577   19040 subchannel.cc:603]          New connected subchannel at 0x7f5008003480 for subchannel 0x7f50000098b0
I0124 17:50:40.210810266   19029 subchannel.cc:603]          New connected subchannel at 0x7f50400035c0 for subchannel 0x7f5070022d80
I0124 17:50:40.211214202   19095 subchannel.cc:603]          New connected subchannel at 0x7f4f1c0035c0 for subchannel 0x7f4f9c0169e0
I0124 17:50:40.212130693   19044 subchannel.cc:603]          New connected subchannel at 0x7f4ff80035c0 for subchannel 0x7f5050014960
I0124 17:50:40.212735905   19052 subchannel.cc:603]          New connected subchannel at 0x7f4fd8003480 for subchannel 0x7f502c01bf20
I0124 17:50:40.214006136   19069 subchannel.cc:603]          New connected subchannel at 0x7f4f94003480 for subchannel 0x7f50200230e0
I0124 17:50:40.214373486   19033 subchannel.cc:603]          New connected subchannel at 0x7f5030003480 for subchannel 0x7f5020003f50
I0124 17:50:40.214733249   19057 subchannel.cc:603]          New connected subchannel at 0x7f4f64003480 for subchannel 0x7f4f9c009d30
I0124 17:50:40.215115253   19025 subchannel.cc:603]          New connected subchannel at 0x7f5044003480 for subchannel 0x7f5050009900
I0124 17:50:40.215604430   19100 subchannel.cc:603]          New connected subchannel at 0x7f4f08003480 for subchannel 0x7f4f6c017640
I0124 17:50:40.216515255   19034 subchannel.cc:603]          New connected subchannel at 0x7f5024003480 for subchannel 0x7f50200094a0
I0124 17:50:40.223530613   19065 subchannel.cc:603]          New connected subchannel at 0x7f4fa40035c0 for subchannel 0x7f4fe40110d0
I0124 17:50:40.224174912   19021 subchannel.cc:603]          New connected subchannel at 0x7f50580035c0 for subchannel 0x7f5070010320
I0124 17:50:40.224723442   19022 subchannel.cc:603]          New connected subchannel at 0x7f5054003480 for subchannel 0x7f5070016dd0
I0124 17:50:40.225349799   19026 subchannel.cc:603]          New connected subchannel at 0x7f50480035c0 for subchannel 0x7f507001d7c0
I0124 17:50:40.226516671   19049 subchannel.cc:603]          New connected subchannel at 0x7f4fd40035c0 for subchannel 0x7f502c015230
I0124 17:50:40.226559644   19054 subchannel.cc:603]          New connected subchannel at 0x7f4fcc0035c0 for subchannel 0x7f5020015990
I0124 17:50:40.227788675   19083 subchannel.cc:603]          New connected subchannel at 0x7f4f48003480 for subchannel 0x7f4f6c0094d0
I0124 17:50:40.227788310   19106 subchannel.cc:603]          New connected subchannel at 0x7f4ef80035c0 for subchannel 0x7f4f9c01c6f0
I0124 17:50:40.232708394   19032 subchannel.cc:603]          New connected subchannel at 0x7f5038003480 for subchannel 0x7f502c009ca0
I0124 17:50:40.233903854   19062 subchannel.cc:603]          New connected subchannel at 0x7f4fc0003480 for subchannel 0x7f4fac003f20
I0124 17:50:40.235123723   19072 subchannel.cc:603]          New connected subchannel at 0x7f4f88003480 for subchannel 0x7f4f8c003f20
I0124 17:50:40.236297340   19078 subchannel.cc:603]          New connected subchannel at 0x7f4f70003480 for subchannel 0x7f4f740151c0
I0124 17:50:40.237527279   19035 subchannel.cc:603]          New connected subchannel at 0x7f50180035c0 for subchannel 0x7f502000edc0
I0124 17:50:40.238878981   19087 subchannel.cc:603]          New connected subchannel at 0x7f4f38003480 for subchannel 0x7f4f30003f20
I0124 17:50:40.238948606   19105 subchannel.cc:603]          New connected subchannel at 0x7f4f240035c0 for subchannel 0x7f4fe401fbe0
I0124 17:50:40.240118124   19103 subchannel.cc:603]          New connected subchannel at 0x7f4f00003480 for subchannel 0x7f4f04003f20
I0124 17:50:40.240202199   19093 subchannel.cc:603]          New connected subchannel at 0x7f4f20003480 for subchannel 0x7f4f6c010910
I0124 17:50:40.241294342   19079 subchannel.cc:603]          New connected subchannel at 0x7f4f68003480 for subchannel 0x7f4f6c003f20
I0124 17:50:40.241423375   19101 subchannel.cc:603]          New connected subchannel at 0x7f4f0c0035c0 for subchannel 0x7f4f6c01cd90
I0124 17:50:40.242498763   19042 subchannel.cc:603]          New connected subchannel at 0x7f5004003480 for subchannel 0x7f4ffc003f20
I0124 17:50:40.243694891   19076 subchannel.cc:603]          New connected subchannel at 0x7f4f78006030 for subchannel 0x7f4f74003f20
I0124 17:50:40.244896499   19058 subchannel.cc:603]          New connected subchannel at 0x7f4f58003480 for subchannel 0x7f4f54003f20
I0124 17:50:40.246085300   19027 subchannel.cc:603]          New connected subchannel at 0x7f503c003480 for subchannel 0x7f505000f2a0
I0124 17:50:40.247241087   19055 subchannel.cc:603]          New connected subchannel at 0x7f4fd0003480 for subchannel 0x7f4fc4003f20
I0124 17:50:40.248384911   19041 subchannel.cc:603]          New connected subchannel at 0x7f500c008a30 for subchannel 0x7f5070028ff0
I0124 17:50:40.249540478   19059 subchannel.cc:603]          New connected subchannel at 0x7f4fc8003480 for subchannel 0x7f4fc400a960
I0124 17:50:40.250699375   19060 subchannel.cc:603]          New connected subchannel at 0x7f4f98003480 for subchannel 0x7f4fc4012900
I0124 17:50:40.251177424   18174 client_async.cc:225]        Sizing async client to 32 threads
I0124 17:50:40.483385352   18174 qps_worker.cc:193]          RunClientBody: client created
I0124 17:50:40.483507798   18174 qps_worker.cc:198]          RunClientBody: creation status reported
I0124 17:50:40.483623488   18166 driver.cc:370]              Initiating
I0124 17:50:40.483780888   18174 qps_worker.cc:200]          RunClientBody: Message read
I0124 17:50:40.527681079   18166 driver.cc:391]              Warming up
I0124 17:50:40.527727163   18166 driver.cc:397]              Starting
I0124 17:50:40.528004971   18174 qps_worker.cc:209]          RunClientBody: Mark response given
I0124 17:50:40.528022026   18169 qps_worker.cc:248]          RunServerBody: Message read
I0124 17:50:40.528045581   18174 qps_worker.cc:200]          RunClientBody: Message read
I0124 17:50:40.552206356   18169 qps_worker.cc:257]          RunServerBody: Mark response given
I0124 17:50:40.601637092   18174 qps_worker.cc:209]          RunClientBody: Mark response given
I0124 17:50:40.602363521   18166 driver.cc:424]              Running
I0124 17:50:41.527840384   18166 driver.cc:438]              Finishing clients
I0124 17:50:41.528058723   18174 qps_worker.cc:200]          RunClientBody: Message read
I0124 17:50:41.529765210   18174 qps_worker.cc:209]          RunClientBody: Mark response given
I0124 17:50:41.529782570   18174 qps_worker.cc:212]          RunClientBody: Awaiting Threads Completion
I0124 17:50:41.530295267   18166 driver.cc:452]              Received final status from client 0

**Comment by jtattermusch** [comment]
I suspect this could have been fixed by https://github.com/grpc/grpc/pull/14177.

**Comment by jtattermusch** [comment]
Haven't seen any occurences after #14177 was merged, closing.
