### ISSUE TITLE
gRPC/HTTP2: malformed RPCs get processed on server when certain parameter combinations are used

### ISSUE THREAD

**Issue by yang-padawan** [grpc/grpc#14176]
#### Should this be an issue in the gRPC issue tracker?
Yes.

#### What version of gRPC and what language are you using?
 Python, gRPC 1.8.4
 
#### What operating system (Linux, Windows, …) and version?
 CentOS release 6.6 (Final)
Linux 2.6.32-504.30.3.el6.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
 
#### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.11, GCC 4.4.7
 
#### What did you do?
When trying various combinations of [Compressed-Flag](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#compressed-flag) and [grpc-encoding](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#message-encoding) in client requests, I observed incorrect server behavior for certain malformed messages. The [gRPC compression doc](https://github.com/grpc/grpc/blob/master/doc/compression.md) states that:
> An ill-constructed message with its [Compressed-Flag](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#compressed-flag) bit set but lacking a [grpc-encoding](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#message-encoding) entry different from _identity_ in its metadata MUST fail with INTERNAL status, its associated description indicating the invalid Compressed-Flag condition.

After combining compressed-flag value of 1 with _grpc-encoding=identity_ or with missing _grpc-encoding_ header, I noticed that **as long as the message payload is not compressed**, the server processes the request without error.
Furthermore, this happens for any case when only one of these two parameters ('_grpc-encoding_' HTTP2 header or '_compressed flag_') is invalid in relation to the fact that no compression is used. I am attaching wireshark capture for each of the four (considering only _deflate_ and _gzip_ are supported) possible cases:

[Uncompressed message, _grpc-encoding_ header is missing, _compressed-flag_ is 1](https://github.com/grpc/grpc/files/1664222/enc_none_cf_1.zip)
[Uncompressed message, _grpc-encoding=identity_, _compressed-flag_ is 1](https://github.com/grpc/grpc/files/1664224/enc_identity_cf_1.zip)
[Uncompressed message, _grpc-encoding=deflate_, _compressed-flag_ is 0](https://github.com/grpc/grpc/files/1664227/enc_deflate_cf_0.zip)
[Uncompressed message, _grpc-encoding=gzip_, _compressed-flag_ is 0](https://github.com/grpc/grpc/files/1664228/enc_gzip_cf_0.zip)

This issue is reproducible (also with older versions of gRPC library).
Server uses Python API.

**Comment by dgquintas** [comment]
Are both the client and server written in Python?

**Comment by yang-padawan** [comment]
> Are both the client and server written in Python?

Yes, although a custom client was used in order to manipulate the request.
