### ISSUE TITLE
HTTP2: sending multiple subsequent HTTP2 'HEADERS' frames causes crash on gRPC server

### ISSUE THREAD

**Issue by yang-padawan** [grpc/grpc#14175]
#### Should this be an issue in the gRPC issue tracker?
Yes.

#### What version of gRPC and what language are you using?
 Python, gRPC 1.8.4
 
#### What operating system (Linux, Windows, …) and version?
 CentOS release 6.6 (Final)
Linux 2.6.32-504.30.3.el6.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
 
#### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.11, GCC 4.4.7
 
#### What did you do?
When checking how a simple Python server handles invalid HTTP2 requests, I observed server crash caused by duplicating HEADERS frame (valid by itself) in client request (i.e. HTTP2 frame sequence HEADERS + HEADERS + DATA). This issue is reproducible and it is present also on older gRPC versions (since 1.0.0). In case the second HEADERS frame is empty (has no payload), the crash does not occur.

I am attaching the server debug log, although it does not provide much information other than the second HEADERS frame is treated as 'trailing metadata' - the only difference when compared to the log of a valid RPC are the extra lines 347-371.

[server_log_dupl_hdrs.txt](https://github.com/grpc/grpc/files/1663712/server_log_dupl_hdrs.txt)

When checking in wireshark, server does not send any frames and closes the TCP connection immediately (FIN).

**Comment by hsaliak** [comment]
@ncteisen would you be able to look into this please?
/cc @kpayson64 in case this is python related, but that's unlikely.

**Comment by hsaliak** [comment]
@yang-padawan are you able to provide steps to reproduce this?
If preferred you can email me at hsaliak at google dot com too.

**Comment by kpayson64** [comment]
@yashykt Could the bad-client framework you are working on help reproduce this issue?

**Comment by yashykt** [comment]
Yes, as discussed, we should be able to reproduce this using the bad-client
framework.

**Comment by ctiller** [comment]
Please consider adding an example of this to the fuzzing corpora

**Comment by nicolasnoble** [comment]
By the way, I don't think sending the duplicated header is actually valid HTTP2. The behavior in the future will be to return a 400 error on these cases.

**Comment by yang-padawan** [comment]
> By the way, I don't think sending the duplicated header is actually valid HTTP2. The behavior in the future will be to return a 400 error on these cases.

[RFC](https://tools.ietf.org/html/rfc7540) does allow the response to consist of two subsequent header frames and I did not find any restrictions (in the RFC, there is a few [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)) that should be applied to trailing headers, but duplicated headers (when both frames are identical) should probably not be valid, as it is basically opening the same stream twice. (that is why I wrote 'When checking how a simple Python server handles **invalid** HTTP2 requests...')

**Comment by kpayson64** [comment]
A patch release 1.8.6 has been pushed that should fix this issue.  Feel free to re-open if it doesn't fix your test case.
