### ISSUE TITLE
Broken bazel test: //test/core/client_channel:lb_policies_test

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#14188]
https://source.cloud.google.com/results/invocations/4fcdc1cb-4e7d-4b65-80a1-50c62a821266/targets

https://source.cloud.google.com/results/invocations/4fcdc1cb-4e7d-4b65-80a1-50c62a821266/targets/%2F%2Ftest%2Fcore%2Fclient_channel:lb_policies_test@poller%3Depoll1/log

**Comment by adelez** [comment]
Friendly ping?

**Comment by dgquintas** [comment]
This test will probably be removed. It has been disabled for about a year: https://github.com/grpc/grpc/pull/14284
