### ISSUE TITLE
interop failure due to some changes in the morning of 4/29/2015.

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc#1418]
Reported by Wes Goodman

C++ helloworld server with non-ok status returned.

// Service snippet

class GreeterServiceImpl final : public Greeter::Service {
  Status SayHello(ServerContext* context, const HelloRequest* request,
                  HelloReply* reply) override {
    return Status(grpc::StatusCode::NOT_FOUND);
  }
};

// Go helloworld client

// Client snippet

package main
import (
    "log"
    "os"
    pb "github.com/grpc/grpc-common/go/helloworld"
    "golang.org/x/net/context"
    "google.golang.org/grpc"
)
const (
    address     = "localhost:50051"
    defaultName = "world"
)
func main() {
    // Set up a connection to the server.
    conn, err := grpc.Dial(address)
    if err != nil {
        log.Fatalf("did not connect: %v", err)
    }
    defer conn.Close()
    c := pb.NewGreeterClient(conn)
    // Contact the server and print out its response.
    name := defaultName
    if len(os.Args) > 1 {
        name = os.Args[1]
    }
    r, err := c.SayHello(context.Background(), &pb.HelloRequest{Name: name})
    if err != nil {
 *       log.Fatalf("could not greet: %v", err)
    }
    log.Printf("Greeting: %s", r.Message)
}
Client output:

$ go run greeter_client/*
2015/04/29 18:22:26 Greeting: 

Go client fails to recognize this rpc error for some reason (I have not got time to drill this down.).

I have verified that this issue exists on github now but does NOT exist for google internal version. The update time of google internal version is 5:11 PM, Apr 28 by yangg. So I think this is due to something changed this morning.

**Comment by iamqizhao** [comment]
+ @gainward who is the reporter.

**Comment by ctiller** [comment]
I'll take a look in the morning.

**Comment by iamqizhao** [comment]
Thanks.

**Comment by iamqizhao** [comment]
My wild guess is that the C++ server sends a data frame with 0 data back to
the client even when the status is not OK so that the client got confused.
