### ISSUE TITLE
Test failure: h2_proxy_nosec_test max_message_length GRPC_POLL_STRATEGY=epollex

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14209]
Test failed on 1.9.x branch at 1.9.x-pre3 tag version bump

https://sponge.corp.google.com/target?id=47e08081-58be-43e5-8e97-15441bcc2b39&target=github/grpc/aggregate_tests&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment]
Similar to https://github.com/grpc/grpc/issues/14470

**Comment by mehrdada** [comment]
Closing this at it's not been seen in a while
