### ISSUE TITLE
Jenkins artifact build is broken due to a docker issue on Linux workers 

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14212]
We have been unable to run artifact builds on Jenkins to make a release since last evening.

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1784/platform=linux/console

**Comment by mehrdada** [comment]
This part of the log might be relevant

```
+ DOCKER_IMAGE_NAME=grpc_artifact_python_manylinux_x64_42a201646662c1c119ca7c5837f85918463e5337
+ '[' quay.io/pypa/manylinux1_x86_64 '!=' '' ']'
+ docker pull quay.io/pypa/manylinux1_x86_64
Using default tag: latest
latest: Pulling from pypa/manylinux1_x86_64
2068b24f564b: Already exists
ec8067baac67: Pulling fs layer
ac5810984e38: Pulling fs layer
ec8067baac67: Verifying Checksum
ec8067baac67: Download complete
ac5810984e38: Download complete
failed to register layer: link /var/lib/docker/overlay/a5f5b4d03cf46a065b282470d1f9b968f37172d5a4f64defdd32f472e92f1c0b/root/var/lib/yum/yumdb/h/561cfee96459ea0fa4aa4c12de9fd3a362a4baeb-hmaccalc-0.9.6-4.el5-x86_64/checksum_type /var/lib/docker/overlay/6d93be49725a5a7181796e2fc69998415d5e961328cbd96e2c810ffccb3791fb/tmproot080781410/var/lib/yum/yumdb/h/561cfee96459ea0fa4aa4c12de9fd3a362a4baeb-hmaccalc-0.9.6-4.el5-x86_64/checksum_type: too many links

```

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by mehrdada** [comment]
looping @nicolasnoble in to have more eyes at this blocking issue

**Comment by matt-kwong** [comment]
I'm working on the issue now, and I'll update when I have a successful rebuild.

**Comment by mehrdada** [comment]
Thanks @matt-kwong

**Comment by matt-kwong** [comment]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1799/ shows the Linux build is now successful. 

CC @kpayson64

**Comment by mehrdada** [comment]
https://grpc-testing.appspot.com/job/gRPC_build_artifacts/platform=linux/1997/console

@matt-kwong the issue has reappeared on Jenkins

**Comment by mehrdada** [comment]
Removing the RELEASE BLOCKER and downgrading to P1 because I am able to fetch the remaining Python packages off of Kokoro but it is a pain. Although if Jenkins is going away soon, further investment may not be justified.

**Comment by matt-kwong** [comment]
I'd like to do use Kokoro exclusively for the next release. Let me know if you're planning on doing the next release or who, so I know who to sync up with to switch to Kokoro.

Also, the way to fix this is to remove the Docker image cache on the Jenkins VM worker, but this breaks the artifacts building process, because our manylinux Dockerfile cannot be built. It currently does a `git clone`, which GitHub blocks because of its outdated TLS. There's a few workarounds I have in mind to fix this, but I think we should try using Kokoro to avoid the problem :)

**Comment by mehrdada** [comment]
Ok, let's not touch Jenkins for this release and wait for Kokoro to come up.
