### ISSUE TITLE
Support encrypted PEM private keys in gRPC c core

### ISSUE THREAD

**Issue by jiangtaoli2016** [grpc/grpc#14216]
In current gRPC c core implementation of SSL transport security, we can only pass unencrypted SSL key. SSL keys are often passphrase encrypted. 

We'd like to expose an option in gRPC for supporting encrypted SSL private key.

**Comment by AngryLemonn** [comment]
This can be done adding something like this to the SSL context:

```c++
int
passphrase_cb (char *buf, int size, int rwflag, void *u)
{
    strncpy ( buf, (char*) u, size );
    buf [size - 1] = '\0';

    return strlen ( buf );
}

// ...

// at SSL context creation
std::string passphrase = user_callback ();
SSL_CTX_set_default_passwd_cb ( grpc_context, passphrase_cb );
SSL_CTX_set_default_passwd_cb_userdata ( grpc_context, (void*) passphrase.c_str () ); 
```

In some cases, the passphrase comes from a derived salt. For that reason, you must give an opportunity to the GRPC user to set the passphrase via callback.

Regards,
J. A.

**Comment by jiangtaoli2016** [comment]
Supporting PEM passphrase in grpc core is something worth doing. But it is not high priority for us and we do not have resource. We could either have interns to implement, or feel free to implement yourself and contribute.

**Comment by abaldeva** [comment]
Okay. Thanks for the info.
