### ISSUE TITLE
OCaml Support

### ISSUE THREAD

**Issue by shinzui** [grpc/grpc#14251]
Hi,

This is a feature request so I didn't follow the issue template since the questions were not applicable. I am wondering if an OCaml binding is on the roadmap.

**Comment by hsaliak** [comment]
@shinzui at this point we do not have language bindings for OCaml. It is also not in the roadmap.

**Comment by shinzui** [comment]
@hsaliak Are you aware of any 3rd party implementation? I tried to google but couldn't find anything.

**Comment by hsaliak** [comment]
@shinzui I tried googling as well before answering you earlier, but unfortunately I could not find anything. What's your use case? It may be worth asking about this in our grpc-io mailing list - https://groups.google.com/forum/#!topic/grpc-io/WvleL0gTeIA

**Comment by shinzui** [comment]
We're moving to GRPC for our microservices and I'm concerned that would make it impossible to write a microservice in OCaml. We're mostly a node shop and we're exploring Go, but there are some domains where I would like to use OCaml for.

**Comment by nathanielmanistaatgoogle** [comment]
@shinzui: the magic of open source (and an open and unencumbered protocol) means that we can't stop you from implementing gRPC for OCaml. In terms of getting gRPC OCaml put onto our roadmap: we think that an implementation's passing [our interop tests](https://github.com/grpc/grpc/blob/a16919e1f0032cf3722f7d21bbd37594e9/doc/interop-test-descriptions.md) is a good point at which to consider integrating it into the main project.

**Comment by nathanielmanistaatgoogle** [comment]
Oh, and my heart will always belong to SML/NJ.

**Comment by nathanielmanistaatgoogle** [comment]
That's more of a guarantee than I meant to indicate. Let's say that when an implementation passes the interop tests that's when we _start_ the conversation about how to get the implementation incorporated into the project.
