### ISSUE TITLE
Bazel test failure: //test/cpp/qps:qps_openloop_test fails with tsan and dbg

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#14257]
https://source.cloud.google.com/results/invocations/58e439f3-e691-4754-9ca2-24afb80fdae8/targets/%2F%2Ftest%2Fcpp%2Fqps:qps_openloop_test@poller%3Depoll1/log

**Comment by adelez** [comment]
https://source.cloud.google.com/results/invocations/4527ecf2-f7b3-434e-9102-b75e1ce1df5c/targets/%2F%2Ftest%2Fcpp%2Fqps:qps_openloop_test@poller%3Depoll1/log

**Comment by jtattermusch** [comment]
This still seems to be happening. @vjpai please take a look (or reassign to someone who can) and update this thread.

**Comment by jtattermusch** [comment]
based on the error log this is an actual data race (not detected by older TSAN version we run on Kokoro) that needs immediate attention.

https://source.cloud.google.com/results/invocations/58e439f3-e691-4754-9ca2-24afb80fdae8/targets/%2F%2Ftest%2Fcpp%2Fqps:qps_openloop_test@poller%3Depoll1/log

@yashykt   @ncteisen   @sreecha   @yang-g  can any of you take over this issue?

**Comment by ncteisen** [comment]
Ok, I just stared digging. Will shoot for regular updates.

The root problem is a race when multiple threads call https://github.com/grpc/grpc/blob/515908ba3196d057a8465a146f667b9e6c2ad9f2/include/grpcpp/impl/codegen/proto_utils.h#L52

That functions actually updates an internal member of the protobuf message under the hood, so it makes sense this would race.

The thing is we have been doing this for a while. The call to that functions was added in #3480, which optimized serialization of small protos directly into one slice. The call must exist if we want to use `SerializeWithCachedSizesToArray`, and the actual value, `byte_size`, is used for another optimization added in #13315.

Questions:
- why is this not being caught by our test sweep of the QPS scenarios? Do we not run them with TSAN? I don't see why this would be specific problem to the unit test versions.

**Comment by jtattermusch** [comment]
@ncteisen  we do run with TSAN on kokoro, but until very recently (see https://github.com/grpc/grpc/pull/15499) we have been using an older clang version (3.8 I think), while remote bazel execution uses clang 7. Another reason is that the timings of different execution environments may be different.

**Comment by ncteisen** [comment]
For remote bazel do we run the sweep of QPS driver scenarios? Or have those not yet been migrated, because I would assume that they would fail in the same way

**Comment by jtattermusch** [comment]
@ncteisen  AFAIK  json_run_localhost scenarios are not running on remote bazel.

**Comment by ncteisen** [comment]
I just did a revert of #3480 and #13315, but then the data race just occurred on this line: https://github.com/grpc/grpc/blob/515908ba3196d057a8465a146f667b9e6c2ad9f2/include/grpcpp/impl/codegen/proto_utils.h#L64

Might need to loop the protobuf team in about this, to see if it is ok to call these functions on the same proto object from multiple threads... It is a strange use case, but it makes sense in the case of a benchmark that is using the same canonical request proto, but serializing each time to get realistic data

**Comment by ncteisen** [comment]
Looks like we have also already seen this in #8174, and fixed it in #8188

**Comment by ncteisen** [comment]
Do the suppressions work differently in bazel? Because we have this suppressed here https://github.com/grpc/grpc/blob/515908ba3196d057a8465a146f667b9e6c2ad9f2/tools/tsan_suppressions.txt#L11

And it did not help to add it here https://github.com/grpc/grpc/blob/515908ba3196d057a8465a146f667b9e6c2ad9f2/build.yaml#L5482

**Comment by adelez** [comment]
Suppression is not applied to bazel builds. If it needs to be suppressed, I'll try it with bazel.

**Comment by jtattermusch** [comment]
to update on what was discussed offline: looks like we are setting  tsan_suppressions.txt   here: https://github.com/grpc/grpc/blob/3fd27cea762fef9d860dd9b0dd4b183ffb1dd245/tools/bazel.rc#L35

we need to investigate if/why that setting are not honored by remote bazel runs.

**Comment by ncteisen** [comment]
I have looked into this a bit further.

running: 
```
make qps_openloop_test
bins/tsan/qps_openloop_test
```

Will fail with the TSAN error. 

But if I run:
```
TSAN_OPTIONS="suppressions=/usr/local/google/home/ncteisen/Desktop/grpc/tools/tsan_suppressions.txt" bins/tsan/qps_openloop_test
```

So this is a problem with the way we feed the binary the suppression file.

Something here:
https://github.com/grpc/grpc/blob/70ce9e21df4f6a18fbcfbb2103d1e89987125f4a/build.yaml#L5580

**Comment by dgquintas** [comment]
I believe we rely on `run_tests.py` to setup the environment from the values in the build.yaml file.

**Comment by ncteisen** [comment]
Ahh yeah, I see that environ var gets passed to the generated tests.json. And this does work when I use run_tests.py to invoke. So this is an issue in how bazel picks up the suppresion file

**Comment by ncteisen** [comment]
```
bazel test //test/cpp/qps:qps_openloop_test
```

Also passes for me. I am running clang 4.0

I can't even figure out how to get clang 7... I don't see it listed on the [download page](http://releases.llvm.org/download.html)

**Comment by adelez** [comment]
Thank you for the investigation. I think I have a fix.
