### ISSUE TITLE
use of dynamic_ssl_server_credentials and forking can result in deadlocks

### ISSUE THREAD

**Issue by cauthu** [grpc/grpc#14258]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
1.8.4 python 
 
### What operating system (Linux, Windows, …) and version?
Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
python 2.7 
 
### What did you do?
we have python servers that use `dynamic_ssl_server_credentials` [1] and do some forking (e.g., use `subprocess`). these servers can get into a deadlock. our finding on the cause is:

* gRPC registers a `pthread_atfork` handler that signals all threads to terminate and then waits for them to terminate before forking.
* If a server uses `dynamic_ssl_server_credentials`, the "certificate_configuration_fetcher" callback that it specifies will be called by `_server_cert_config_fetcher_wrapper()` [2] -- with the Python global interpreter lock (GIL) held -- on every new accepted connection.
* When the server forks, the `pthread_atfork` handler is triggered with the Python GIL held.
* If a connection request comes in while the server is in the middle of handling the fork, C-core / cython layer tries to take the GIL to call `_server_cert_config_fetcher_wrapper()`. However, the GIL is held by the forking thread, which is waiting for all other threads to terminate. The server thread then blocks on the GIL and never exits, causing the `pthread_atfork` handler to never complete while still holding the GIL. This means that all process threads eventually deadlock on the GIL. (see stack trace below.)

one potential work-around is to "disable fork support" (issue #14056)

----
stack trace:
```
(gdb) t 53
[Switching to thread 53 (LWP 113448)]
#3  0x00007fee80b21d98 in PyGILState_Ensure () at Python/pystate.c:611
611 Python/pystate.c: No such file or directory.
(gdb) bt
#0  0x00007fee807f7fd0 in sem_wait () from .../x86_64-linux-gnu/libpthread.so.0
#1  0x00007fee80b346a8 in PyThread_acquire_lock (lock=0x7fee81d4c780, waitflag=<optimized out>) at Python/thread_pthread.h:324
#2  0x00007fee80af51c4 in PyEval_RestoreThread (tstate=0x7fee6c0008c0) at Python/ceval.c:357
#3  0x00007fee80b21d98 in PyGILState_Ensure () at Python/pystate.c:611
#4  0x00007fee7b5ec9f5 in __pyx_f_4grpc_7_cython_6cygrpc__server_cert_config_fetcher_wrapper ()
   from .../grpc/_cython/cygrpc.so
#5  0x00007fee7b65eeef in try_fetch_ssl_server_credentials(grpc_ssl_server_security_connector*) ()
   from .../grpc/_cython/cygrpc.so
#6  0x00007fee7b65f11e in ssl_server_add_handshakers(grpc_exec_ctx*, grpc_server_security_connector*, grpc_handshake_manager*) ()
   from .../grpc/_cython/cygrpc.so
#7  0x00007fee7b601f5a in grpc_handshakers_add ()
   from .../grpc/_cython/cygrpc.so
#8  0x00007fee7b667401 in on_accept(grpc_exec_ctx*, void*, grpc_endpoint*, grpc_pollset*, grpc_tcp_server_acceptor*) ()
   from .../grpc/_cython/cygrpc.so
#9  0x00007fee7b61ceef in on_read ()
   from .../grpc/_cython/cygrpc.so
#10 0x00007fee7b614b14 in grpc_exec_ctx_flush ()
   from .../grpc/_cython/cygrpc.so
#11 0x00007fee7b60b5dd in pollset_work(grpc_exec_ctx*, grpc_pollset*, grpc_pollset_worker**, long) ()
   from .../grpc/_cython/cygrpc.so
#12 0x00007fee7b61bf2c in run_poller(grpc_exec_ctx*, void*, grpc_error*) ()
   from .../grpc/_cython/cygrpc.so
#13 0x00007fee7b614db5 in run_closures(grpc_exec_ctx*, grpc_closure_list) [clone .isra.1] ()
   from .../grpc/_cython/cygrpc.so
#14 0x00007fee7b614ef5 in executor_thread(void*) ()
   from .../grpc/_cython/cygrpc.so
#15 0x00007fee7b5fdea8 in thread_body(void*) ()
   from .../grpc/_cython/cygrpc.so
#16 0x00007fee807f1e9a in start_thread () from .../x86_64-linux-gnu/libpthread.so.0
#17 0x00007fee8051936d in clone () from .../x86_64-linux-gnu/libc.so.6
#18 0x0000000000000000 in ?? ()
```
[1] https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L1509
[2] https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/server.pyx.pxi#L21

**Comment by kpayson64** [comment]
I think this issue should also be mitigated by #14647.

Even without disabling fork support, 14647 will skip the handlers if there are outstanding c-core calls.
