### ISSUE TITLE
crashed on channel_stack.cc:177

### ISSUE THREAD

**Issue by 0oneo** [grpc/grpc#14269]
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 objective-c
 
### What operating system (Linux, Windows, …) and version?
 iOS 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang
 
### What did you do?
Test GRPC stablity online 
 
### What did you expect to see?
 not crash
 
### What did you see instead?
low rate crash

Crashed: com.apple.root.default-qos EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x6e6576650000001a

```
Crashed: com.apple.root.default-qos
0  myapp                          0x100f3d02c grpc_call_stack_init (channel_stack.cc:177)
1  myapp                          0x100f8b46c grpc_connected_subchannel_create_call (subchannel.cc:767)
2  myapp                          0x100f48bcc pick_done_locked(grpc_exec_ctx*, grpc_call_element*, grpc_error*) (client_channel.cc:1014)
3  myapp                          0x100f4b588 grpc_combiner_continue_exec_ctx (combiner.cc:261)
4  myapp                          0x100f56e94 grpc_exec_ctx_flush (exec_ctx.cc:93)
5  myapp                          0x100f5477c pollset_work(grpc_exec_ctx*, grpc_pollset*, grpc_pollset_worker**, long) (ev_poll_posix.cc:1057)
6  myapp                          0x100f4c840 cq_next(grpc_completion_queue*, gpr_timespec, void*) (completion_queue.cc:952)
7  myapp                          0x100f30450 __27-[GRPCCompletionQueue init]_block_invoke_2 (GRPCCompletionQueue.m:56)
8  libdispatch.dylib              0x190cf69e0 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x190cf69a0 _dispatch_client_callout + 16
10 libdispatch.dylib              0x190d050d4 _dispatch_queue_override_invoke + 644
11 libdispatch.dylib              0x190d06a50 _dispatch_root_queue_drain + 540
12 libdispatch.dylib              0x190d067d0 _dispatch_worker_thread3 + 124
13 libsystem_pthread.dylib        0x190eff100 _pthread_wqthread + 1096
14 libsystem_pthread.dylib        0x190efecac start_wqthread + 4
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
no

**Comment by mehrdada** [comment]
Can you please try v1.9.1 and see if you can reproduce anything like this. I suspect all of these issues are related to #13327.

**Comment by 0oneo** [comment]
OK，I will give it a try, later will post the production result

**Comment by srini100** [comment]
Please reopen if #13327 doesn't fix this issue.
