### ISSUE TITLE
Implement SerializationTraits<protobuf::Message> for ByteBuffer rather than grpc_byte_buffer

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#14261]
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
C++
 
### What operating system (Linux, Windows, …) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A
 
### What did you do?

Tried to directly use SerializationTraits
 
### What did you expect to see?
 
A direct serializer between protobuf::Message and grpc::ByteBuffer since this is a supported variant of SerializationTraits

### What did you see instead?
 
The existing serializer for protobuf goes to grpc_byte_buffer , and there is no C++ API-only way to convert between that and grpc::ByteBuffer. There is a path for doing the desired conversion: serialize the proto to a string, build a Slice from that string, and then build a ByteBuffer from that Slice, but that is ugly. It would be better to directly convert.
 
### Anything else we should know about your project / environment?

Cc @htuch

**Comment by vjpai** [comment]
I'm going to add this as part of "De-wrapping of C++" because the machinery for doing this will fall into place naturally (I think) as C++ is de-wrapped.

**Comment by ncteisen** [comment]
This was achieved in #14541. We now have a public API to translate from protobuf::Message to grpc::ByteBuffer
