### ISSUE TITLE
System.AccessViolationException - Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop

### ISSUE THREAD

**Issue by ndglover** [grpc/grpc#14273]
### What version of gRPC and what language are you using?
1.8.0 C# 
 
### What operating system (Linux, Windows, …) and version?
 Windows Server 2012 R2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 4.6.1
 
###
2 different servers had the following error in the log file after which the process crashed immediately. 

```
C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x64\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1147: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings" 
```

Looking in the event viewer at the same time both also had

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(Grpc.Core.Internal.CompletionQueueSafeHandle, Grpc.Core.Profiling.IProfiler)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

Both of these processes have been running without any issues for many months.

Any ideas what could have caused this or anything we can do to further diagnose the issue?

**Comment by smflorentino** [comment]
We are seeing the same thing on Server 2016. Never saw this before 1.8.

**Comment by jtattermusch** [comment]
Is this still happening in v1.9.x and v.1.10.x?

Is there a reproduction I could use?

**Comment by andreasp79** [comment]
Same here, server has been running grpc 1.8.3 for about a month before the exception happened, never seen it before. 

I don't have repro steps but the priority for us is to prevent the entire process going down immediately because of any exception thrown on the grpc threads (even if it's just to do graceful shutdown). Is this possible without manually recompiling grpc?

**Comment by ndglover** [comment]
I haven't seen it crash the process since upgrading to v1.10, although that could be by chance as it was not reproducible it just happened at random. I do still see the error below on the grpc thread. What seems to be happening now is this causes the grpc thread to block or silently die, certainly no more responses are received after this error. We see the connection state go to Idle, calling ConnectAsync again it seems to reconnect, at least the state goes back to Connected but no more data is received.

C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1097: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"

**Comment by smflorentino** [comment]
I've also recently observed this on 1.10, basically the clients started receiving DeadlineExceeded and the server was receiving InvalidOperationExceptions that the client closed the connection, but our RPC listener wasn't being invoked (or it was being invoked with an empty payload)

Killing the server process instantly fixed the problem.

I have a memory dump with a couple of threads in gRPC code, but I can't make much sense of them (I'll file a separate issue regarding missing symbols)

4 threads:
```
ntdll!NtWaitForAlertByThreadId+14
--
ntdll!RtlSleepConditionVariableCS+c9
KERNELBASE!SleepConditionVariableCS+28
grpc_csharp_ext_x64!gprsharp_free+60e42
grpc_csharp_ext_x64!gprsharp_free+9a02
grpc_csharp_ext_x64!gprsharp_free+60bfe
kernel32!BaseThreadInitThunk+14
ntdll!RtlUserThreadStart+21
```

2 threads:
```
ntdll!NtWaitForAlertByThreadId+14
--
ntdll!RtlSleepConditionVariableCS+c9
KERNELBASE!SleepConditionVariableCS+28
grpc_csharp_ext_x64!gprsharp_free+60e42
grpc_csharp_ext_x64!gprsharp_free+ae62
grpc_csharp_ext_x64!gprsharp_free+abc3
grpc_csharp_ext_x64!gprsharp_free+ac61
grpc_csharp_ext_x64!gprsharp_free+60bfe
kernel32!BaseThreadInitThunk+14
ntdll!RtlUserThreadStart+21
```

3 threads
```
ntdll!NtRemoveIoCompletion+14
--
KERNELBASE!GetQueuedCompletionStatus+3f
grpc_csharp_ext_x64!gprsharp_free+30f54
grpc_csharp_ext_x64!gprsharp_free+bdab
grpc_csharp_ext_x64!grpcsharp_version_string+2878
grpc_csharp_ext_x64!grpcsharp_version_string+3b93
grpc_csharp_ext_x64!grpcsharp_completion_queue_next+3c
DomainBoundILStubClass.IL_STUB_PInvoke(Grpc.Core.Internal.CompletionQueueSafeHandle)+cd
[[InlinedCallFrame]]
Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(Grpc.Core.Internal.CompletionQueueSafeHandle, Grpc.Core.Profiling.IProfiler)+4d
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+162
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+14
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+52
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart()+52
clr!CallDescrWorkerInternal+83
clr!CallDescrWorkerWithHandler+4e
clr!MethodDescCallSite::CallTargetWorker+f8
clr!ThreadNative::KickOffThread_Worker+109
[[GCFrame]]
clr!Frame::Push+59
clr!FillInRegTypeMap+198
clr!FillInRegTypeMap+c1
[[DebuggerU2MCatchHandlerFrame]]
clr!FillInRegTypeMap+47
clr!ThreadNative::KickOffThread+db
clr!Thread::intermediateThreadProc+86
kernel32!BaseThreadInitThunk+14
ntdll!RtlUserThreadStart+21

**Comment by jtattermusch** [comment]
is this still an issue?

**Comment by smflorentino** [comment]
The load patterns on my services have changed slightly, but I haven't seen this issue in many months. I think this issue can freely be closed.

**Comment by jtattermusch** [comment]
@smflorentino  Thanks for the update!
