### ISSUE TITLE
`core_stats.h` is getting installed under `$(prefix)/src/cpp/util`

### ISSUE THREAD

**Issue by jjlin** [grpc/grpc#14280]
I just built gRPC 1.8.6 (upgrading from 1.6.0), and it seems a new `core_stats.h` file is getting installed under `$(prefix)/src/cpp/util`, which `rpmbuild` is flagging as an "Installed (but unpackaged) file(s)".
 
Of course, I could adjust my spec file to handle this, but I suspect this location wasn't intentional, and that the file should actually go somewhere under `$(prefix)/include/grpc`? If not, feel free to close the issue. Thanks.

**Comment by vjpai** [comment]
This is being addressed in a PR #14124
