### ISSUE TITLE
grpc_testing on PyPI

### ISSUE THREAD

**Issue by treuherz** [grpc/grpc#14294]
The repo contains some methods for faking out channels in src/python/grpcio_testing, but these don't appear to be published anywhere despite having been commited several months ago. Are there any plans to make these easier for third parties to use without having to copy all the code into our own projects? Some documentation and examples of their use would also be really helpful. Like a lot of the python side of the project they're a little opaque at present!

**Comment by mehrdada** [comment]
Thanks for the feedback. We intend to publish that at some point. We just haven't gotten to integrate it in our package build system, but we will try to prioritize it and get it done. I can't promise a timeline at this point though.

**Comment by mehrdada** [comment]
To add, if the community is super-excited about this, we would love to accept a PR to the artifact build process. I believe around here is where one should start looking to change: https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/build_artifact_python.sh

(Basically need to look into how grpcio_reflection and grpcio_health_checking packages are built and follow the pattern in the repository for those packages).

**Comment by ghostwriternr** [comment]
Hey @nathanielmanistaatgoogle, I'd like to pick up this issue. I tried making the appropriate changes today, but I haven't been successful in getting to build them successfully using [`task_runner.py`](https://github.com/grpc/grpc/blob/master/tools/run_tests/task_runner.py).

It's internally using the Dockerfile [`grpc_artifact_python_manylinux_x64`](https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_artifact_python_manylinux_x64/Dockerfile), but keeps failing at `RUN yum update -y` with:
```
The command '/bin/sh -c bash echo "yolo"' returned a non-zero code: 139
```

Am I missing something?

**Comment by mehrdada** [comment]
A release candidate of v1.13.x of [`grpcio-testing` package is uploaded on PyPI](https://pypi.org/project/grpcio-testing/).
