### ISSUE TITLE
Certain rpc names cause compiler errors  "... cannot be overloaded". Especially ones ending with "Raw"

### ISSUE THREAD

**Issue by rainerschoe** [grpc/grpc#14290]
### Should this be an issue in the gRPC issue tracker?

I think so, as I searched the internet for similar issues (found none), read the manual multiple times and it works perfectly with slightly different RPC names. Only certain RPC names cause the problem.
 
### What version of gRPC and what language are you using?

libprotoc 3.5.0
libgrpc++.so.1.8.4 commit 77ec6c94ad58bedfdf8f28682914e9893e318be0
 
### What operating system (Linux, Windows, …) and version?

 Linux Ubuntu 16.04 kernel 4.10.0-42-generic
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

 g++ --version => g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

 
### What did you do?

1. create file grpc.proto with the following content:
```
syntax = "proto3";

message Arg
{
    int32 data = 1;
}

service Vpd {
    rpc Foo(Arg) returns (Arg);
    rpc FooRaw(Arg) returns (Arg);
}
```

2. generate c++ code from it:
```protoc --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin grpc.proto```

3. compile the generated code (grpc part only):
```g++ -std=c++11 -c grpc.grpc.pb.cc```
 
### What did you expect to see?

 compiled grpc.grpc.pb.o without any error
 
### What did you see instead?

Compiler error message starting with:
 ```
In file included from grpc.grpc.pb.cc:6:0:
grpc.grpc.pb.h:49:65: error: ‘virtual grpc::ClientAsyncResponseReaderInterface<Arg>* Vpd::StubInterface::AsyncFooRaw(grpc::ClientContext*, const Arg&, grpc::CompletionQueue*)’ cannot be overloaded
     virtual ::grpc::ClientAsyncResponseReaderInterface< ::Arg>* AsyncFooRaw(::grpc::ClientContext* context, const ::Arg& request, ::grpc::CompletionQueue* cq) 
                                                                 ^
grpc.grpc.pb.h:42:74: error: with ‘std::unique_ptr<grpc::ClientAsyncResponseReaderInterface<Arg> > Vpd::StubInterface::AsyncFooRaw(grpc::ClientContext*, const Arg&, grpc::CompletionQueue*)’
     std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Arg>> AsyncFooRaw(::grpc::ClientContext* context, const ::Arg& request, ::grpc::CompletionQu
```

Full error message in attached file [error.txt](https://github.com/grpc/grpc/files/1689024/error.txt)

### Anything else we should know about your project / environment?

The following proto code compiles without any problem:
```
syntax = "proto3";

message Arg
{
    int32 data = 1;
}

service Vpd {
    rpc Foo(Arg) returns (Arg);
    rpc FooRaww(Arg) returns (Arg);
}
```

I also tried other RPC names not ending with `Raw` they all worked. something seems to be special with the Raw rpc name ending.

**Comment by vjpai** [comment]
The C++ code generator auto-generates RPC variants with the suffix Raw for any rpc name. So you could currently have Foo and BarRaw but not Foo and FooRaw.

That said, I'm not going to close this issue as we either need to document this or do something about it in the future.

**Comment by sreecha** [comment]
@vjpai : What is a good place to document this? - We should just to that route for now to resolve this issue.
