### ISSUE TITLE
Request for updated src/cpp/README.md

### ISSUE THREAD

**Issue by teganburns** [grpc/grpc#14304]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
yes
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
v1.8.x
 
 
### What operating system (Linux, Windows, …) and version?
Linux 4.14.15-1-ARCH x86_64 GNU/Linux
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (GCC) 7.2.1 20180116
GNU Make 4.2.1
cmake version 3.10.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

1) Followed instruction on the [README.md](https://github.com/grpc/grpc/tree/master/src/cpp#build-from-source)
1.1) git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
1.2) cd grpc
1.3) git submodule update --init
1.4) make
1.5) Tried again with `export CFLAGS="-Wno-error"` and `PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig make` as per https://github.com/grpc/grpc/issues/10589
1.6) sudo make install [gist output](https://gist.github.com/teganburns/4304bb31b57479827b447005f3a69635#file-grpc-output-sudo-make-install)
2) cd examples/cpp/route_guide
3) make [gist output](https://gist.github.com/teganburns/4304bb31b57479827b447005f3a69635#file-make-grpc-examples-cpp-route_guide)

 
### What did you expect to see?
Successful build. Accurate README.md to build from source.
 
 
### What did you see instead?
Unsuccessful build. Time spent searching through issues, and trying different builds.

````
/usr/local/lib//libgrpc.so.5: undefined reference to `EVP_MD_CTX_new'
/usr/local/lib//libgrpc.so.5: undefined reference to `EVP_MD_CTX_free'
/usr/local/lib//libgrpc.so.5: undefined reference to `RSA_set0_key'
````
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

**I'd really just like to see the grpc/src/cpp/README.md updated with valid build instructions.**

My projects that are dependent on gRPC have been broken for over a year. I've invested weeks into trying to build a working version of gRPC. I've opened [other issues](https://github.com/grpc/grpc/issues/11376) that have yet to be resolved coming close to a year on those now. This really limits me when using Google's Cloud APIs. I'm not sure where else to address these concerns given the Google Cloud Support team has no control over any issues with gRPC. If there is a better place to direct these concerns please let me know. I've been really patient with these issues but I need to have **straight-forward build instructions that work**. If there is anything I can do to help with this or to help me understand why I'm ( and seemingly may others ) are having so many issues with this let me know.

**Comment by srini100** [comment]
As a new user I was able to build fine but I followed instructions at https://github.com/grpc/grpc/blob/master/INSTALL.md
Not sure if it makes any difference but I see that instructions at https://github.com/grpc/grpc/blob/master/src/cpp/README.md don't have these steps:
 $ [sudo] apt-get install libgflags-dev libgtest-dev
 $ [sudo] apt-get install clang libc++-dev

**Comment by teganburns** [comment]
@srini100 
- That's a good thing to point out and should probably be updated as well.
- You shouldn't need those packages unless you're running tests too, but I can't confirm that.
- I'm building on a different platform than you and don't have the same package manager ( pacman ).

**Comment by srini100** [comment]
@teganburns Not sure if this is relevant to your case, I run into build errors if pkg-config is not installed. That is also not mentioned in the build instructions. Without pkg-config, I get these errors:

Compiling src/core/tsi/ssl_transport_security.cc
src/core/tsi/ssl_transport_security.cc: In function ‘tsi_result tsi_create_ssl_client_handshaker_factory(const tsi_ssl_pem_key_cert_pair*, const char*, const char*, const char**, uint16_t, tsi_ssl_client_handshaker_factory**)’:
src/core/tsi/ssl_transport_security.cc:1364:29: error: ‘const SSL_METHOD* TLSv1_2_method()’ is deprecated [-Werror=deprecated-declarations]
  ssl_context = SSL_CTX_new(TLSv1_2_method());
