### ISSUE TITLE
BoringSSL -fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by IljaDaderko** [grpc/grpc#14333]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
I believe so
  
### What version of gRPC and what language are you using?
Updated my ios project cocoapods that seem to rely on `gRPC`, these were updated to:

```
gRPC 1.9.0 (was 1.8.6)
gRPC-Core 1.9.0 (was 1.8.6)
gRPC-ProtoRPC 1.9.0 (was 1.8.6)
gRPC-RxLibrary 1.9.0 (was 1.8.6)
BoringSSL 9.2
```
 
 
### What operating system (Linux, Windows, …) and version?
macOS High Sierra
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Not sure, seeing this error within XCode
 
 
### What did you do?
Tried altering XCode build settings to allow this weak thing, but no luck
 
### What did you expect to see?
 No error, clean build
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by muxi** [comment]
Please let us know Xcode and Cocoapods versions you are using.

**Comment by IljaDaderko** [comment]
Issue solved, error was caused by Cocoapods/Xcodeproj, latest update fixes it
