### ISSUE TITLE
Remove extra sleep in ReconnectTest after polling hack is resolved

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14340]
This issue tracks a work item to revert https://github.com/grpc/grpc/pull/14339 when the polling thread hack to track channel connectivity is removed and proper retry mechanisms are in place

**Comment by nathanielmanistaatgoogle** [comment]
@mehrdada or @kpayson64: is this now actionable? It smells now actionable?

**Comment by kpayson64** [comment]
I think we can close this issue now.

With the new "background poller" approach, the channels are only ever polled periodically, so we need the sleep in the test indefinitely.
