### ISSUE TITLE
obj-c: exception when using link-local IPv6 address

### ISSUE THREAD

**Issue by dcow** [grpc/grpc#14369]
`NSURL` does not understand _scope-id_ so `GRPCConnectivityMonitor` raises on line 126 since the host is null (the parameter is marked nonnull but the argument is never checked, too): https://github.com/grpc/grpc/blob/951cf484905d226bdb27087c0368cdfafff8d4e3/src/objective-c/GRPCClient/private/GRPCConnectivityMonitor.m#L124-L128

I've verified this is an issue only with the objective-c layer and that the c++ core correctly handles v6 addresses with a _zone-id_ present e.g. `fe80::ab:cdef%en0`.

> grpc-1.8 iOS

**Comment by dcow** [comment]
There is literature on handling zone-ids in URIs: https://tools.ietf.org/html/rfc6874. Even if apple's URL class did support them, the grpc code still passes the original address (which would need to be url encoded %25) down to lower layers which are not expecting % to be an escape character.

**Comment by dcow** [comment]
@muxi any thoughts on this? Should we address this separately from #14387 ?

**Comment by muxi** [comment]
Hey sorry I have not had a chance to take a look at this issue. If the root cause of this problem is that NSURL not understanding the zone ids then I think we should address this separately from #14387. Given there's quite a few pending issues with higher priority, it would be great if you can make a PR for this too and I'll be able to help with review.

**Comment by dcow** [comment]
No problem! I can certainly do that.

**Comment by dcow** [comment]
@muxi I've started working on this today. It's a little hairier than I initially imagined.

```
  // To provide a default port, we try to interpret the address. If it's just a host name without
  // scheme and without port, we'll use port 443. If it has a scheme, we pass it untouched to the C
  // gRPC library.
```

Is there any case where someone would provide a host address with a scheme? Isn't `https` the only scheme compatible with grpc?

**Comment by dcow** [comment]
@jcanizales question for you. You've put a few `TODO`s in the host handling code in grpc obj-c. Since I'm touching this code, is there a vision you had for how it would all work once the todos are addressed? I'm curious if I can address any of that right now.

For example in grpc call:

```
 // TODO(jcanizales): Extract this logic somewhere common.
  NSString *host = [NSURL URLWithString:[@"https://" stringByAppendingString:_host]].host;

  if (!host) {
    // TODO(jcanizales): Check this on init.
    [NSException raise:NSInvalidArgumentException format:@"host of %@ is nil", _host];
  }
```

I can put logic in the same place easy, but it appears the logic is actually different between grpc call and grpc host. In grpc host, the logic is used not just to get the host part of the address, but also append a port if no scheme and port exists.

**Comment by muxi** [comment]
We do support a few schemes. See https://github.com/grpc/grpc/blob/master/doc/naming.md

Please ignore that particular TODO. Those few lines should have been deprecated by a very recent change (as you can tell `host` is not being used thereafter). I'll remove that TODO with a PR.

**Comment by dcow** [comment]
@muxi this is no longer an issue since the connectivity monitor rework.
