### ISSUE TITLE
How to add user defined modules to Path (C++)

### ISSUE THREAD

**Issue by Prateek0601** [grpc/grpc#14373]
#I am using C++ Programming language.

#Windows 10 1709 (build 16299.192).

#GCC(g++)4.8.0.
 
#I want to use my own Modules to my Program so how could i add that library to sublime text 3.I tried to add the path to the 'Environment variables'but still shows error'.
![check](https://user-images.githubusercontent.com/33068264/35983855-e466169c-0ca7-11e8-9d12-86ca62df7347.png)

**Comment by ncteisen** [comment]
This does not seem related to gRPC.... closing.
