### ISSUE TITLE
gRPC C++ throughput much worse on Windows than on Linux (for empty msgs in a single server streaming RPC)

### ISSUE THREAD

**Issue by d79ima** [grpc/grpc#14378]
I am using gRPC version 1.8.3 C++ build on Linux and Windows and comparing the throughput between the two platforms.

2 server machines, 12 core Intel Xeon CPU, 96 GB RAM
Windows Server 2008 R2 64-bit and Ubuntu 17.04 Desktop 64-bit.
VC++ 2017 compiler on Windows, GCC 6.3.0 2017 on Linux
10Gbps Mellanox Ethernet adapter

My benchmark app is testing a very simple client/server scenario with 1 RPC channel open, streaming call.
I am trying to see if I can saturate or come close to saturating my 10Gbps link with data.
I am testing throughput for two scenarios:

1. Sending a message with a "bytes" field in it which is 2MB in size
2. Sending same message with empty "bytes" field

On Linux I am seeing the following throughput:
Scenario 1) 920 MB/sec
Scenario 2) 125000 Messages/sec

On Windows I am seeing the following throughput:
Scenario 1) 500 MB/sec
Scenario 2) 1000 Messages/sec

I would expect to see comparable performance on Windows, but i am seeing much worse performance, especially in Scenario 2).
Could you please help me explain why is this happening? Can I tweak something on Windows to match the performance I am seeing on Linux?

Both Windows and Linux code samples are attached.
[grpc_perf_LINUX.zip](https://github.com/grpc/grpc/files/1708508/grpc_perf_LINUX.zip)
[grpc_perf_WINDOWS.zip](https://github.com/grpc/grpc/files/1708515/grpc_perf_WINDOWS.zip)

**Comment by hsaliak** [comment]
@jtattermusch @chwarr is this something you folks might be able to dig into?

**Comment by chwarr** [comment]
@Lalo, who's been looking into related issues on Windows.

**Comment by lalo** [comment]
I'll take a look.

**Comment by hsaliak** [comment]
@lalo @chwarr thanks a lot!

**Comment by lalo** [comment]
@d79ima can you explain why scenario 1 is measured in megabytes per second and scenario 2 is measured in messeges per second? From a quick look to your code, the scenario 1 sets a tcp_read_chunk_size of 2 megabytes and in your scenario 2 the chunk size is 0 bytes? Is this correct?

**Comment by d79ima** [comment]
@lalo yes that is correct. In scenario 2 i am sending a small message chunk size zero, so the bytes field is empty, just to see what the throughput for lots of small messages might be.

**Comment by jtattermusch** [comment]
In our "official benchmarks" (http://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584) I actually see around 76Kmessages per sec for unary and 140K sec per sec for streaming between two 8core windows machines when using C# server and client (C# is slower than C++) - so doublechecking what your benchmark is doing might be useful.

**Comment by d79ima** [comment]
My benchmark is just really trivial. All it's doing is sending one message in a loop on the server side and receiving that message in a loop on the client side. I don't know what i can be doing better to reach the kind of numbers you report seeing in your official benchmarks. Perhaps you could look at my samples that I attached and tell me what I am doing wrong? Also, still doesn't explain why i am getting such drastically different results on Linux vs Windows when executing pretty much exactly the same application code.

Would it be possible for you to run my benchmark sample on your test machines and let me know the throughput?

**Comment by d79ima** [comment]
Also, would it be possible for you to share with me more details about your two 8core windows machines?
I am interested in the following:

1) Operating system version
2) Exact model and speed of network adapter cards
3) Any specific performance tuning options that were selected for the network adapters and any registry settings that were modified beyond the defaults

**Comment by jtattermusch** [comment]
@d79ima 
They are Windows 7 machines, hardware is standard GCE virtual machines "n1-standard-8" (8 vCPUs, 30 GB memory), CPU platform Intel Haswell.

**Comment by jtattermusch** [comment]
@d79ima  I looked at your example again and it looks like I previously confused what was doing.
The numbers for C# I posted are for a "QPS throughput" benchmark (i.e. multiple channnels, multiple RPCs per channel), while your benchmark is basically testing "number of messages per second that can be delivered via a server streaming RPC".

Ad your results:
Scenario 1) difference of 1000MB vs 500MB seems "normal" in the sense that so far we've invested more effort into optimizing Linux performance than into Windows performance - so the windows throughput can most likely be improved (help is welcome!), but the numbers are close enough in the sense that they don't indicate a larger problem.

In scenario 2) however, the difference of 125K messages vs 1K messages seems very significant, so there is probably a problem somewhere in the codebase and we should look into it.

**Comment by jtattermusch** [comment]
@d79ima, I put together a simple C#  benchmark for one-way streaming throughput and I'm currently getting >30Kmsgs  per second throughput (with very small messages, running the test locally).  I tried with client streaming so far, but I can test server streaming as well. C++ throughput should be strictly better.
Are you using the release build (as in "not Debug") for testing? What numbers are you getting when you run your benchmarks on localhost?

**Comment by d79ima** [comment]
@jtattermusch With my C# benchmark i am seeing 23K msgs per second using localhost with server doing the streaming.

**Comment by ppLorins** [comment]
@d79ima  I believe I'm currently facing the same issue with yours, to be in short : 
throughput for the async c++ server performing badly poorer on windows than on mac.  My scenario is sort of alike with yours, details are [here](https://mail.google.com/mail/u/0/#sent/KtbxLxgKJJPkwvGplJvRNNrQlPCVDjKDGV).
 @jtattermusch  although It has been past for more than one year, I think this is maybe a serious issue for the window users.  Very appreciated if you can take a look again.
