### ISSUE TITLE
C#: Expose API for grpc_ssl_client_certificate_request_type

### ISSUE THREAD

**Issue by ornatwork** [grpc/grpc#14381]
I have a C# gRpc version 1.8.3 server and a client working over TLS using mutual authentication by creating my own certificates. I now wanted to make sure the client is certified with a specific certificate. I can find the IP address in `ServerCallContext.Peer`, but I'm unable to find the certificate information in the context.

I'm also surprised to see the `ServerCallContext.AuthContext.IsPeerAuthenticated` field return `false`, maybe because I created the certificates myself ?  `PeerIdentity` is empty as well.

**Comment by ornatwork** [comment]
I found out that I was using `false `for `forceClientAuth`, after I set it `true `the information is available.

`SslServerCredentials(IEnumerable<KeyCertificatePair> keyCertificatePairs, string rootCertificates, bool forceClientAuth)`;

However when it's false and I try to connect with a client that is not using a certificate that client can not connect to the server.  It looks like the flag just means, populate the `ServerCallContext.AuthContex`, is that the expected behavior ?

**Comment by jtattermusch** [comment]
@jboeuf   it looks like that client won't get authenticated (and AuthContext populated) unless "forceClientAuth" is `true`. Is the the expected behavior?

**Comment by jboeuf** [comment]
+ @jiangtaoli2016 FYI,

At the core layer, `forceClientAuth=true` translates to `TSI_DONT_REQUEST_CLIENT_CERTIFICATE` at the core `ssl_transport_security.cc` layer. I could see this being changed to `TSI_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_BUT_DONT_VERIFY` but I'm afraid that it could break other clients. 

These flags are explicit at the core layer where we deprecated the `forceClientAuth` usage in favor of a more specific set of behaviors. If not done already, I would encourage gRPC C# to do the same.

**Comment by jtattermusch** [comment]
@jboeuf  thanks for the explanation. We can expose the new "clientCertificateRequest" enum in C#, but I currently don't have an ETA for that.

**Comment by jtattermusch** [comment]
This is currently blocked by https://github.com/grpc/grpc/issues/15588.
