### ISSUE TITLE
Latest version of CocoaPods/Xcodeproj exposes gRPC warnings

### ISSUE THREAD

**Issue by paulb777** [grpc/grpc#14390]
https://github.com/CocoaPods/Xcodeproj/commit/f356891db634b68710b5c78611b84c14371acd7a turned on the Xcode settings CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS and CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF by default.  This causes the following gRPC build warnings:

    - WARN  | [Firebase/Firestore] xcodebuild:  gRPC-RxLibrary/src/objective-c/RxLibrary/GRXConcurrentWriteable.m:70:12: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Firestore] xcodebuild:  gRPC-RxLibrary/src/objective-c/RxLibrary/GRXConcurrentWriteable.m:71:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Firestore] xcodebuild:  gRPC/src/objective-c/GRPCClient/private/GRPCChannel.m:208:22: warning: variable 'host_slice' may be uninitialized when used here [-Wconditional-uninitialized]
    - NOTE  | [Firebase/Firestore] xcodebuild:  gRPC/src/objective-c/GRPCClient/private/GRPCChannel.m:191:3: note: variable 'host_slice' is declared here
    - WARN  | [Firebase/Firestore] xcodebuild:  gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoMethod.m:21:17: warning: Implementing deprecated class [-Wdeprecated-implementations]
    - NOTE  | [Firebase/Firestore] xcodebuild:  gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoMethod.h:26:12: note: class declared here
    - WARN  | [Firebase/Firestore] xcodebuild:  gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoRPC.m:45:17: warning: Implementing deprecated class [-Wdeprecated-implementations]
    - NOTE  | [Firebase/Firestore] xcodebuild:  gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoRPC.h:25:12: note: class declared here
    - WARN  | [Firebase/Firestore] xcodebuild:  gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoService.m:27:17: warning: Implementing deprecated class [-Wdeprecated-implementations]
    - NOTE  | [Firebase/Firestore] xcodebuild:  gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoService.h:27:12: note: class declared here

This will impact anyone who has installed or updated CocoaPods after February 4, 2018 and gets [Xcodeproj 1.5.6](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.5.6). 

Check with

```
 $ gem list Xcodeproj

*** LOCAL GEMS ***

xcodeproj (1.5.6, 1.5.4, 1.5.2, 1.5.0)
```

**Comment by muxi** [comment]
Paul, these warnings have all been fixed (#14314, #14042). Expect them be gone in the next minor version release.
