### ISSUE TITLE
Suggestion: optimize servercalls(C#)

### ISSUE THREAD

**Issue by 893949088** [grpc/grpc#14399]
I think the servercalls Is it possible to be open. let me to custom to defind request middleware like asp.net mvc.

**Comment by ncteisen** [comment]
Feel free to put in a PR for this feature. IF it is big enough, you should create a gRFC for it

**Comment by jtattermusch** [comment]
External contributions are definitely welcome (including those that improve performance, of course), so feel free to contribute. In the meantime, I will close this issue as it is not clear what is the optimization you're suggesting.
