### ISSUE TITLE
Switch to C++ style casts 

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#14392]
C style casts are error prone. Now that the codebase is C++, we should prevent anyone from adding new c style casts, and attempt to switch all existing casts to C++ style.

Clang-tidy can do about half of this work.

**Comment by ncteisen** [comment]
Not pursuing

**Comment by apolcyn** [comment]
@hcaseyal is this still relevant?

**Comment by markdroth** [comment]
Yes, this is something we should do at some point.
