### ISSUE TITLE
Client freezes with round_robin load balancing

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#14408]
### Should this be an issue in the gRPC issue tracker?

Yes.
 
### What version of gRPC and what language are you using?

v1.9.x / C++ 
 
### What operating system (Linux, Windows, …) and version?
 
Linux, Debian, kernel 4.9.0
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

```console 
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18) 
```
 
### What did you do?

Please find a program to reproduce the issue attached.  Basically create a server with multiple ports, a client that uses `round_robin` across them, then make the server close all the ports from time to time, while the client continuously makes (blocking) requests to the server.

[grpc-freeze-standalone.tar.gz](https://github.com/grpc/grpc/files/1718031/grpc-freeze-standalone.tar.gz)

### What did you expect to see?
 
The client should continue to issue RPCs.
 
### What did you see instead?
 
Eventually the client stops making RPCs, all threads become blocked and there is no progress.
 
### Anything else we should know about your project / environment?

I do not think so, but feel free to contact me if you have any questions.

**Comment by markdroth** [comment]
@dgquintas, could this be related to your recent RR changes?

**Comment by dgquintas** [comment]
My changes didn't make it to 1.9.x

**Comment by dgquintas** [comment]
@coryan , any chance you'd be able to try with the version at HEAD? If not, the 1.10 branch will be created soon, as well as release candidate packages. There have been a number of changes around this part of the code recently.

**Comment by coryan** [comment]
@dgquintas I included a tarball with a small (small-ish?) program so you can test it at HEAD or any other version:

[grpc-freeze-standalone.tar.gz](https://github.com/grpc/grpc/files/1718031/grpc-freeze-standalone.tar.gz)

It seems to be fixed at 22f363981a32953f9eee9291a6b46a499df08080 .  It would be good to hear what PR / commit fixed this, and if there is a specific test for it.

**Comment by dgquintas** [comment]
Thanks a lot @coryan , that's a wonderful bug report. Good to hear also that it seems fixed. I'll play with your code and bisect to find where it was fixed. My money is at or around https://github.com/grpc/grpc/pull/14170.

By the way, in your server.cc file, on line 69, you have:
```
std::string address = "0.0.0.0:" + std::string(argv[0]);
```
I'm guessing you meant to write:
```
std::string address = "0.0.0.0:" + std::string(argv[i]);
```
Otherwise, you only use the first port passed in as arg. Is this a typo in the repro code only or have you been testing with this -from the looks of it- buggy line?

**Comment by coryan** [comment]
Well that is embarrassing.  Yes, should have been `argv[i]`.  Which allowed me to narrow this further.  The problem only shows up (even in v1.9.x) if one of the endpoints listed in the client does not exist.

#14170 sounds like a good candidate indeed.  And I see you have modified the tests, presumably to reproduce the issue.  I am going to close this, thanks for the quick turnaround.

I have updated the tarball in case it is helpful in the future.

[grpc-freeze-standalone.tar.gz](https://github.com/grpc/grpc/files/1732046/grpc-freeze-standalone.tar.gz)
