### ISSUE TITLE
TSI_INTERNAL_ERROR with openssl 1.1.0g

### ISSUE THREAD

**Issue by rocketpork** [grpc/grpc#14414]
Please answer these questions before submitting your issue. 
  
### What version of gRPC and what language are you using?
 1.9.1 for C++
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04 LTS
  
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5
 
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Trying to get the GoogleSpeech API samples running. It worked with grpc 1.9.1 and with OpenSSL 1.0.2n. Did just update to OpenSSL 1.1.0g and recompiled/linked all. But now it is not working anymore. 
(I disabled the thirdparty/boringssl stuff and need to use standard OpenSSL)

When starting the speech samples, I am getting this on the console:

./streaming_transcribe -b 16000 audio.flac file: audio.flac
step1
E0213 10:59:50.479743137   23815 ssl_transport_security.cc:837] Sending protected frame to ssl failed with -1
E0213 10:59:50.479861929   23815 secure_endpoint.cc:179]     Decryption error: TSI_INTERNAL_ERROR
Sending 32k bytes.
writesDones
step3
Error in HTTP transport completing operation

 
### What did you expect to see?

That it worked as before with OpenSSL 1.0.2n and provides the transcribed result

 
### What did you see instead?
 
./streaming_transcribe -b 16000 audio.flac file: audio.flac
step1
E0213 10:59:50.479743137   23815 ssl_transport_security.cc:837] Sending protected frame to ssl failed with -1
E0213 10:59:50.479861929   23815 secure_endpoint.cc:179]     Decryption error: TSI_INTERNAL_ERROR
Sending 32k bytes.
writesDones
step3
Error in HTTP transport completing operation
 
### Anything else we should know about your project / environment?
I started also a Wireshark capturing session you'll find attached as jpg.
![googlespeech-openssl](https://user-images.githubusercontent.com/11721761/36156737-387f663c-10d8-11e8-8a5b-59e58cf5be7e.jpg)

**Comment by jiangtaoli2016** [comment]
Do you have a stack trace on the error?

**Comment by rocketpork** [comment]
I retried it also with OpenSSL 1.1.0f, 1.1.0d -> always got the same error
Attached you'll find a grpc trace .. let me know, whether that is sufficient. 
Thanks ..
[grpc-trace.txt](https://github.com/grpc/grpc/files/1726815/grpc-trace.txt)

**Comment by jiangtaoli2016** [comment]
@rocketpork Do you still have problem? Could you try to uninstall libssl-dev (openSSL) to use built-in boringSSL and see whether the problem still exist?

**Comment by rocketpork** [comment]
Thanks ... I could solve this issue meanwhile. uninstalling/installing openSSL resolved the issue ..
