### ISSUE TITLE
Using TLS raw public keys for authentication

### ISSUE THREAD

**Issue by mwisniewski0** [grpc/grpc#14420]
### What version of gRPC and what language are you using?
 
I'm using gRPC 1.9.1 on Python3
 
### What operating system (Linux, Windows, …) and version?
 
Cross-platform project developed on Windows 10 and Ubuntu 14.04 LTS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 3.6.4
 
### What did you do?

My application requires connecting to domain-less gRPC servers. The servers should be accessible from both the internet as well as the local network (therefore there is no unique IP address that can be attached to the certificate). The trust is established by:
- The client having the public key of the server acquired out of band
- The server owning the private key corresponding to the public key

I would like to use TLS raw public key authentication to allow for authentication using just the public key. I could also use self-signed certificates, but since my servers are domain-less, gRPC won't pass the server name check (see https://github.com/grpc/grpc/blob/86d7509c6a1b0da6dc77f2d22a9f2a3aba7895fa/src/core/tsi/ssl_transport_security.cc function: does_entry_match_name()).

If introduction of raw public key authentication is not feasible, what other options do I have?
 
### What did you expect to see?
 
I would like to be able to use TLS raw public key authentication

**Comment by mehrdada** [comment]
@jboeuf Please evaluate the feasibility of this.

**Comment by srini100** [comment]
@jiangtaoli2016 Please see if this is feasible. If we decide to do it it should be a cross-lang feature.

**Comment by jiangtaoli2016** [comment]
@mwisniewski0 Here is what we can do without changing any code. @markdroth correct me if I am wrong.

Server creates SSL certificate with any hostname.
When client connects to server, it passes server's root certificate public key as GRPC_DEFAULT_SSL_ROOTS_FILE_PATH. 
Also set hostname in the server certificate in GRPC_SSL_TARGET_NAME_OVERRIDE_ARG. It should pass tsi_ssl_peer_matches_name() check.

**Comment by ericgribkoff** [comment]
It sounds like this was addressed by the last comment from @jiangtaoli2016. Marking closed. @mwisniewski0, please reply if I have missed anything and we should reopen.
