### ISSUE TITLE
Support session tickets on server, RFC 5077

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc#14431]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpc-core 1.8.4
 
### What operating system (Linux, Windows, …) and version?
 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python-2.7.14
 
### What did you do?
* Create pool of python grpc servers
* Make go client with enabled tls tickets connect to them
* Restart servers from time to time
 
### What did you expect to see?
 Client uses tls tickets to re-establish session and avoid full handshake
 
### What did you see instead?
 Server rejects tls ticket from client and forces full tls handshake. It happens because python grpc servers don't provide any api for controlling tls tickets and therefore boringssl generates unique ticket for every server at start time.

One of possible solutions is to add api to grpc server to set list of steks (session tickets encryption keys), so that one is used for encrypting new tickets and others for decrypting old ones (to enable graceful rotation of steks).

**Comment by nathanielmanistaatgoogle** [comment]
@jboeuf: what do you make of this?

**Comment by euroelessar** [comment]
It's worth to mention that tls ticket support is missing in grpc-core altogether, not just in python.

**Comment by jboeuf** [comment]
Assigning to @jiangtaoli2016 the new gRPC security lead. 

My 2 cents is that yes, it absolutely makes sense to support TLS resumption. It's just a matter of priority.

**Comment by jboeuf** [comment]
@euroelessar Yes, of course, TLS support is in core.

**Comment by euroelessar** [comment]
@jboeuf Does it make sense to add list of steks into `grpc_ssl_server_certificate_config` and pass it as one more argument to `tsi_create_ssl_server_handshaker_factory_ex`?
After that grpc-core can use `SSL_CTX_set_tlsext_ticket_key_cb` to control logic for encrypting/decrypting tickets (boringssl supports only single key by default).

**Comment by euroelessar** [comment]
@jiangtaoli2016 Hi, can you check if this api proposal does make sense, please? It's heavy influenced by existing server-side golang session ticket API.

1. Add one more private field to `grpc_ssl_server_certificate_config` structure: list of session ticket encryption keys (STEKs).
2. First key in the list is used to encrypt new tickets
3. All keys are used for decrypting old tickets (to support graceful ticket rotation)
4. Add function to set STEKs to config after its construction but before giving it to the server.
5. Perform `sha512` on every key, use first 16 bytes as "name", next 16 bytes as "aes key" for encryption, next 16 bytes as "hmac key" for signing.

```
typedef struct {
    uint8_t key[32];
} grpc_ssl_session_ticket_key;
grpc_ssl_server_certificate_config_set_session_ticket_keys(
    grpc_ssl_server_certificate_config* config,
    grpc_ssl_session_ticket_key session_ticket_keys,
    size_t num_session_ticket_keys);
...
auto config = grpc_ssl_server_certificate_config_create(...);
grpc_ssl_server_certificate_config_set_session_ticket_keys(config, keys.data(), keys.size());
auto credentials = grpc_ssl_server_credentials_create_options_using_config(..., config);
```

**Comment by asgoel** [comment]
Wondering if there's been any progress on this? It's nice to have the client side implementation, but it's not too useful if the server side implementation doesn't persist across process restarts (unless I'm mistaken here).
