### ISSUE TITLE
gRPC Python Server Library incompatibility with future.ProcessPoolExecutor

### ISSUE THREAD

**Issue by decebal** [grpc/grpc#14436]
### What version of gRPC and what language are you using?
 grpc 1.9.1 , python 3.6.0
 
### What operating system (Linux, Windows, …) and version?
 under docker with phusion/baseimage , also tried on debian jessie and Kali Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 3.6.0
 
### What did you do?
The issue is really similar to : https://github.com/grpc/grpc/issues/13873 also maybe with https://github.com/grpc/grpc/issues/12455 . This as well: https://github.com/grpc/grpc/issues/13536

 
### What did you expect to see?
 normal server response
 
### What did you see instead?
Got the error: `E0215 12:45:01.090952877      35 tcp_server_posiix.cc:228]    Failed accept4: Invalid argument` in the logs while the server hangs and is made unavailable for future requests.

### How to reproduce
easiest way of reproducing, which might help the other 2 issues referenced above as well, is to change this line:
https://github.com/grpc/grpc/blob/master/examples/python/route_guide/route_guide_server.py#L115
to `server = grpc.server(futures.ProcessPoolExecutor(max_workers=10))`

In order to get the logs I am attached an interceptor using opencensus, like this :
```
from opencensus.trace.samplers import always_on
from opencensus.trace.ext.grpc import server_interceptor
from opencensus.trace.exporters import print_exporter
from opencensus.trace.exporters.transports import background_thread

        sampler = always_on.AlwaysOnSampler()
        exporter = print_exporter.PrintExporter(transport=background_thread.BackgroundThreadTransport)
        tracer_interceptor = server_interceptor.OpenCensusServerInterceptor(sampler, exporter)
        server = grpc.server(
            futures.ProcessPoolExecutor(max_workers=self.max_workers),
            interceptors=(tracer_interceptor,)
        )
```

### Anything else we should know about your project / environment?
At the moment I am considering dabeaz/curio or [an asyncio alternative](https://gist.github.com/decebal/0c56cf9cd8d3dd97cc150ae5b7291aad) as temporary alternatives.
Also read the answers here https://stackoverflow.com/questions/38387443/how-to-implement-a-async-grpc-python-server , which unfortunately do not help a lot in moving the server from being thread based to a process based execution.

The need of using processes instead of threads in my architecture comes from looking to put better practices at work as well as I was looking that this piece of work can replace Gearman for me which was running in different processes. I agree there are alternative solutions, but solving this would be so much cleaner.

**Comment by kpayson64** [comment]
ProcessPoolExecutor uses fork() under the hood, which isn't generally supported.  We would like to support this case, so I'll leave this open as a feature request.

**Comment by decebal** [comment]
since I filled this issue I have come to believe that http://grpclib.readthedocs.io/en/latest/ might be a solution for me as it achieves the same purpose but through another mechanism, the asyncio library.

**Comment by rafalkasa** [comment]
Do you know when you planning to add support for `futures.ProcessPoolExecutor` for gRPC python server?
The python limitation related to GIL (global interpreter lock) is always the issue. Before I started use gRPC server I have good experience with gunicorn where it was possible to start the server with multiprocessing workers https://gunicorn.org/

**Comment by srini100** [comment]
@rafalkasa, there is no immediate plan to support fork on the server side. This is low priority for us. The first step here would be to support pre-forking (possibly revive https://github.com/grpc/grpc/issues/13536).

**Comment by mattdornfeld** [comment]
Could someone explain the motivation for wanting to support ProcessPoolExecutor? Would that allow a grpc server to support more cpu heavy tasks since each request would get its own Python process? What's wrong with ThreadPoolExecutor?

**Comment by srini100** [comment]
@mattdornfeld, what you said is right. Concurrency with threads is limited by GIL in a given python process. For CPU intensive tasks, this won't scale with number of cores. Hence ProcessPoolExecutor is needed.

**Comment by rafalkasa** [comment]
In the past, I worked on the project where the tasks run on threads limited by GIL making the whole process working slower and slower based on the number of threads that we start. The solution was resolved when we switch from ThreadPoolExecutor to ProcessPoolExecutor. As I remember it was better to not use threads and have one process instead of using python Threads. You can read more about GIL here https://www.dabeaz.com/python/UnderstandingGIL.pdf

So maybe this is not your the most important topic, but please to understand that this change will have a significant impact on services run with workers build based gRPC in Python.

We will resolve the multiprocessing run multiple instances of gRPC servers on Docker containers, but I would like to have the possibility to use in the future ProcessPoolExecutor. Thank you for your answers.

**Comment by srini100** [comment]
https://github.com/grpc/grpc/issues/16001 has a couple of suggestions to work around this limitation. It is not an ideal solution as it doesn't scale dynamically (you need to pre-allocate set number of processes) but something to consider if thread pool is not working for you.

**Comment by decebal** [comment]
> Could someone explain the motivation for wanting to support ProcessPoolExecutor? Would that allow a grpc server to support more cpu heavy tasks since each request would get its own Python process? What's wrong with ThreadPoolExecutor?

simple most common problem that I have, you can't start a ProcessPool inside a ThreadPool (ProcessPoolExecutor throws an exception). While you can always do it the other way around.

@rafalkasa has given quite a good explanation for why you would want it as well.

Latest versions of python are walking away from threads or that is my impression due to numerous Syncronizations and tweaks Threads would entice, while processes due to the fact of not having a shared state are simpler to manage.
