### ISSUE TITLE
grpc 1.9.0 memory leak when enabling max idle filter

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#14447]
### What version of gRPC and what language are you using?
1.9.0-C++ 
 
### What operating system (Linux, Windows, …) and version?
Windows, Linux 
 
### What did you do?
Set GRPC_ARG_MAX_CONNECTION_IDLE_MS to 2 minutes
 
### What did you expect to see?
Option to work as expected without causing a memory leak. 
 
### What did you see instead?
 Huge memory leak observed. Log attached.
### Anything else we should know about your project / environment?
On server, one thread to process completion queue and another thread to handle the events. From client, bombard the server with few different rpcs. When the option is not enabled, no memory leak is observed. When the option is enabled, I lose about 4 mb per second. 
[memory_leak.txt](https://github.com/grpc/grpc/files/1732368/memory_leak.txt)

**Comment by y-zeng** [comment]
@abaldeva I've created https://github.com/grpc/grpc/pull/14501 to fix the leak. Could you please also verify the fix with your server. Thanks!
