### ISSUE TITLE
gRPC CocoaPod runs `sed` on its own backup files

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc#14457]
At the very end of https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec there is a line

    find src/core/ -type f -exec sed -E -i'.back' 's;#include "third_party/nanopb/(.*)";#include <nanopb/\\1>;g' {} \\\;

when using this project as a development Pod (i.e. local, with a `:path =>` argument), each invocation of `pod install` after the first causes all the `*.back` files to be edited again by `sed`, creating `*.back.back` files. This should be fixable by inserting a `! -path '*.back*'` like so:

    find src/core/ -type f ! -path '*.back*' -exec sed -E -i'.back' 's;#include "third_party/nanopb/(.*)";#include <nanopb/\\1>;g' {} \\\;

Alternatively, an option like `\( -name "*.h" -or -name "*.c" -or -name "*.cc" \)` (with proper escapes) should work as well and would be even more specific.

**Comment by MrMage** [comment]
Friendly ping @muxi — do you need other information from me, or should I simply file a pull request?

**Comment by muxi** [comment]
Fixed.
