### ISSUE TITLE
Cannot import `grpc` module in Swift files when using CocoaPods

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc#14456]
I am trying to use gRPC-Core 1.9.1 in a vanilla macOS Swift project with CocoaPods.

The pod module compiles just fine, but when I add `import grpc` to one of my Swift files, I get the following error:

    <module-includes>:8:9: note: in file included from <module-includes>:8:
    #import "Headers/support/log.h"
            ^
    /Users/daniel/Library/Developer/Xcode/DerivedData/grpc-import-test-btagazabopubmzbtzlbubflbuxqo/Build/Products/Debug/gRPC-Core/grpc.framework/Headers/support/log.h:22:10: error: include of non-modular header inside framework module 'grpc':     '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/clang/include/inttypes.h'
    #include <inttypes.h>
             ^
    /Users/daniel/Documents/Xcode/Mac/grpc-import-test/grpc-import-test/AppDelegate.swift:10:8: error: could not build Objective-C module 'grpc'
    import grpc
           ^

It appears that this error is specific to `inttypes.h`, as removing that one `include` line fixes the error. I suspect that the problem is that Clang for some reason resolves this to its internal header (which includes an `#include_next` directive), but does not recognize that as a header that does not to be part of the module. Would it be possible to remove the `#include <inttypes.h>` from that file?

FYI, this is my Podfile:

    target 'grpc-import-test' do
      use_frameworks!
    
      pod 'gRPC-Core', '~> 1.9'
      pod 'BoringSSL', '~> 9.1'
    end

The project is a brand-new, otherwise empty Swift project.

**Comment by MrMage** [comment]
Friendly ping @muxi — do you need other information from me, or should I simply file a pull request?

**Comment by muxi** [comment]
Huge apologies; for some reason I did not receive notification email about this issue and the other one. I doubt if can be solved by removing the `#include` directive. This error looks similar to what we were fixing in #12788 and might has something to do with the umbrella header and module map. I'm triggering a CI run and I will be good if that passes. Otherwise I'll take a further look.

**Comment by muxi** [comment]
@MrMage the CI failed. Would you mind share the project you are working on? That would make it easier for me to reproduce and find a resolution. Thanks!

**Comment by muxi** [comment]
Actually never mind I got a reproduction.

**Comment by MrMage** [comment]
Great! Let me know if you need any more help from me in figuring this out :-)
