### ISSUE TITLE
allow gRPC-level proxies to support retries

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#14467]
Currently, a gRPC-level proxy written in C++ (or even directly against C-core) cannot easily support retries, because when it gets a trailers-only response from the backend, it will generate separate send_initial_metadata and send_trailing_metadata ops to return the result to the client.

The proxy code can do some extra work, such as implementing their own delay after seeing initial metadata in order to see if trailing metadata is returned shortly thereafter.  However, most proxy authors will not realize they need to do this, which means they're going to get it wrong, and there are also performance implications.  So it's not a very good solution.

We need to think about better ways to fix this problem.  One possible option is to add a piece of initial metadata that tells the transport that trailing metadata will quickly follow.

CC @dfawley, since the same problem exists in Go.

**Comment by markdroth** [comment]
We still need to figure this out.

**Comment by markdroth** [comment]
@vjpai Does this problem still exist in the C++ callback API?  I'm guessing yes but wanted to verify.

**Comment by vjpai** [comment]
Confirming that the callback API would have the same issue. The interception API would probably also see it the same way as well.

**Comment by markdroth** [comment]
I've discussed this with @vjpai.  It looks like we can make this work in the callback API by invoking the recv_initial_metadata method with ok=false in the case of a Trailers-Only response.  This may require doing something like #13423.  This is now considered a blocker for de-experimentalizing the C++ callback API.

We're also discussing whether we can do something similar in the C++ interception API.
