### ISSUE TITLE
Error in connecting GRPC

### ISSUE THREAD

**Issue by Dhara-Openxcell** [grpc/grpc#14489]
We are getting this error connecting with grpc using node package grpc in mac.

**E0222 13:11:14.727365000 140736589050816 ssl_transport_security.cc:190] ssl_info_callback: error occured.

E0222 13:11:14.727629000 140736589050816 ssl_transport_security.cc:979] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.**

We have 3 lnd nodes running successfully. But while following your guide to send payment using grpc client we are getting that error.

Also here is our code that we are using to connect grpc.

**var async = require('async');
var _ = require('lodash');
var ByteBuffer = require('bytebuffer');

var grpc = require('grpc');
var fs = require("fs");

var lndCert = fs.readFileSync("~/Library/Application Support/Lnd/tls.cert");
var credentials = grpc.credentials.createSsl(lndCert);
var lnrpcDescriptor = grpc.load("rpc.proto");
var lnrpc = lnrpcDescriptor.lnrpc;
var lightning = new lnrpc.Lightning('localhost:10003', credentials);

lightning.getInfo({}, function(err, response) {
  console.log('GetInfo:', response);
});**

Please let us know the solution for that.

Thanks.

**Comment by murgatroid99** [comment]
The argument to `createSsl` should be a certificate authority file corresponding to the certificates that you are using on the server. Is that what you have there?

**Comment by Dhara-Openxcell** [comment]
Yes, we are using the same certificate authority which is generated by LND. Here is the attachment of the file.
[tls.cert.txt](https://github.com/grpc/grpc/files/1750558/tls.cert.txt)

**Comment by Dhara-Openxcell** [comment]
It would be highly appreciable if you can reply back for this issue.

**Comment by xgess** [comment]
@Dhara-Openxcell i saw similar issues doing this from python, and https://github.com/lightninglabs/lightning-coindesk/issues/2#issuecomment-354727899 pointed me to a fix: adding `GRPC_SSL_CIPHER_SUITES = "HIGH+ECDSA"` to the environment. best of luck.

**Comment by srini100** [comment]
@Dhara-Openxcell Can you confirm if adding GRPC_SSL_CIPHER_SUITES = "HIGH+ECDSA" to the environment worked?

**Comment by Dhara-Openxcell** [comment]
@srini100 yes, i have checked this, but i am getting an error GRPC_SSL_CIPHER_SUITES = "HIGH+ECDSA" NOT DEFINED. 

@xgess Thank you for your answer.

**Comment by grunch** [comment]
@Dhara-Openxcell you should do it like this

```
process.env.GRPC_SSL_CIPHER_SUITES = 'HIGH+ECDSA';
```

**Comment by PWKad** [comment]
This worked for me but definitely was not clear until I found this issue.
