### ISSUE TITLE
TIMEOUT: py35.test.unit.beta._face_interface_test.DynamicInvokerFutureInvocationAsynchronousEventServiceTest

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14491]
Timing out on windows (at around 1% rate). Currently the only python flake we're regularly seeing so it's really worth fixing.

The `py35.test.unit.beta._face_interface_test.MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest` is also flaky - I assume the rootcause is the same.

Recent failures of DynamicInvokerFutureInvocationAsynchronousEventServiceTest (mostly failing on dbg)
https://sponge.corp.google.com/invocation?id=5c00d049-71d7-4c8a-b4f4-ecaaa1ba550f
https://sponge.corp.google.com/invocation?id=31cd06e0-0cc1-46d7-900a-e68972623ad2
https://sponge.corp.google.com/invocation?id=76bf2bfd-d7bc-4ceb-b10a-e3b1654ecbfc
https://sponge.corp.google.com/invocation?id=1ae72416-f719-4205-b4bb-8b3bb8d96266
https://sponge.corp.google.com/invocation?id=91bd7820-40e3-4356-85a5-e60979ac04fd

Recent failures of MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest (mostly failing on opt)
https://sponge.corp.google.com/invocation?id=dfa96709-f8ae-486a-ac46-538d484cc1d1
https://sponge.corp.google.com/invocation?id=0d039fac-ca2b-405c-beda-2a7e65853f7b
https://sponge.corp.google.com/invocation?id=a08e34dc-c970-4953-bf82-57d5d5ba8090

**Comment by jtattermusch** [comment]
@mehrdada, can you take a look?

**Comment by mehrdada** [comment]
Looks like this test have been a flaky one since the dawn of times and closed every time without a fully working resolution. There seems to be some history behind it that @nathanielmanistaatgoogle might know better as he has been on some of the threads below. Since this is the beta API and has not been resolved for 2 years, my suggested resolution would be to kill the test entirely as it is not clear further investment in its fix is justified:

https://github.com/grpc/grpc/issues/13848
https://github.com/grpc/grpc/issues/12761
https://github.com/grpc/grpc/issues/5163
https://github.com/grpc/grpc/issues/5779
https://github.com/grpc/grpc/issues/5567
https://github.com/grpc/grpc/issues/3585

**Comment by jtattermusch** [comment]
@mehrdada  I understand these tests might be hard to fix, but your resolution "let's kill the tests in July" basically means we're going to continue have this flakiness for the next 3 months and for those 3 months we are not going to do anything about them - and that approach is problematic for our flake-fighting effort (especially because this is one of our most common flakes currently).
Let's come up with a better plan:
- can we disable the selected few flaky test now (we have enough data about what's flaky) and spend the next 3 months by doing something more useful than monitoring a known flake that's polluting our statistics and cost us time every time we look at them?

**Comment by jtattermusch** [comment]
The data:
over the last month, our biggest offenders were:
(windows) py35.test.unit.beta._face_interface_test.DynamicInvokerFutureInvocationAsynchronousEventServiceTest
(windows) py35.test.unit.beta._face_interface_test.MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest

These two test represent 90% of all our python flakes over the last months. Can they be disabled now? (Disabling on windows is enough).

**Comment by mehrdada** [comment]
@jtattermusch I completely agree with you. I think we should kill the tests *now* and the Beta API in July. I apologize if I did not phrase it clearly. My understanding in the Python meeting was that @nathanielmanistaatgoogle was going to disable the tests.

**Comment by nathanielmanistaatgoogle** [comment]
I confirm that I intend to remove the tests any day now.

**Comment by jtattermusch** [comment]
@mehrdada  @nathanielmanistaatgoogle  thanks!

**Comment by jtattermusch** [comment]
Friendly ping to remove the flaky tests (and thanks!)

**Comment by dgquintas** [comment]
This is accounting for the failure of ~31% of PR tests now: https://performanceedit-dot-grpc-testing.appspot.com/explore?dashboard=5661273836486656&widget=463826361&container=278069897&maximized
