### ISSUE TITLE
Support for specifying a custom ThreadManager implementation

### ISSUE THREAD

**Issue by gwihlidal** [grpc/grpc#14492]
### What version of gRPC and what language are you using?
 
1.7.2 - C++
 
### What operating system (Linux, Windows, …) and version?
 
 Windows 10 , Ubuntu Linux, and MacOS X (High Sierra)

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
VS 2017 MSVC, GCC-7, Clang 5
 
### What did you do?

While profiling Windows performance of gRPC C++ on Windows, constant thread creation and shutdown is expensive and problematic for a number of reasons. Looking over code and interfaces, there are a few sync server options exposed (i.e. min and max pollers), but there doesn't appear to be a way to specify a custom `ThreadManager` implementation.

### What did you expect to see?

I would like a way to specify a custom `ThreadManager` implementation for sync servers, instead of having to use the async approach to try and work around the issues with the built in thread manager.

Some of the issues:

1) Threads are constantly created and destroyed instead of reused, due to the logic in `ThreadManager::MainWorkLoop()`. Even setting both min and max pollers to 64 will still cause rampant thread creation as `num_pollers_--;` will drop the `num_pollers` to 63, so `WORK_FOUND` will create a new thread to bring it back up to 64

2) The spawned threads are just `std::thread` launched from `ThreadManager::WorkerThread::WorkerThread(ThreadManager* thd_mgr)` which means that we can't use existing thread pool implementations (custom or, for example, Intel TBB)

3) The spawned threads aren't named, and we can't name them ourselves from outside the library. It looks like #13559 possibly added support in a later version of gRPC, but it doesn't look like Windows support was implemented here. A custom thread manager would let us manipulate thread properties like names without modifying gRPC itself (though it would be good to push Windows thread name support upstream for the default `ThreadManager`, as well).

4) We cannot instrument gRPC owned threads using our custom in process profiler, as we don't have access to the work loop of the thread to place a scoped counter
 
 
### What did you see instead?

While profiling performance of gRPC C++ on Windows, constant thread creation and shutdown is expensive and problematic for a number of reasons. Looking over code and interfaces, there are a few sync server options exposed (i.e. min and max pollers), but there doesn't appear to be a way to specify a custom `ThreadManager` implementation.

Has this already been discussed somewhere before? And would this be accepted if it came as a pull request?

### Anything else we should know about your project / environment?

Heavy mix of 3d game engine, high end graphics rendering, in-process deep learning inference, and very performance critical :)

Thank you very much!
Graham

**Comment by gwihlidal** [comment]
As a follow up, I implemented an async service version so I could explicitly control the threading, and while this is working, and performance has improved significantly, perf is still quite bad overall. It seems like regardless of the async service, grpc spawns (arbitrarily) timing threads which I can't seem to control. I have seen some pretty bad cases like:

4 explicitly spawned threads, 20 implicitly spawned timing threads:
![image](https://user-images.githubusercontent.com/564042/36852026-0be135ac-1d6b-11e8-9b65-77da7792ccc6.png)

12 explicitly spawned threads, 37 implicitly spawned timing threads:
![image](https://user-images.githubusercontent.com/564042/36852630-7d82320a-1d6c-11e8-8f57-1fe2d2ac9212.png)

It would be great to know if the timing threads can be either reduced, or disabled somehow, and also what they are used for.

Any best practices on writing a high performance c++ async server where an RPC can take a long time to return (heavy calculation) would also be great to know.

Thank you,
Graham

**Comment by vjpai** [comment]
Thanks for this issue, we've gotten a few requests for this and will be taking it up in the near future, though I can't provide an ETA at the current time.

**Comment by vjpai** [comment]
The part about the number of timing threads seems very odd, though. Can you file that as a separate issue so that we can triage it independently of the custom thread pool?

**Comment by gwihlidal** [comment]
Hi @vjpai - I created another issue for the timing thread problem (which is higher priority than this issue).

https://github.com/grpc/grpc/issues/14578

**Comment by sreecha** [comment]
Realistically this is low priority (based on the current backlog) but I welcome contributions from the community. A good place to start is creating a gRFC https://github.com/grpc/proposal and get approval first before making any code changes
