### ISSUE TITLE
Python client subscribed connectivity_callback occasionally does not receive TRANSIENT_FAILURE

### ISSUE THREAD

**Issue by sbconsulting** [grpc/grpc#14498]
### What version of gRPC and what language are you using?

Python, gRPC 1.0.4
 
### What operating system (Linux, Windows, …) and version?

Linux, Ubuntu 14.04
 
 ### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 2.7.6
 
### What did you do?

I have a need in my client to monitor the gRPC connection for connectivity issues, and I have attached a connectivity callback using the channel.subscribe() function. Each time the callback is called, I print the status to a log file.
 
### What did you expect to see?

I expect to see a failure condition (TRANSIENT_FAILURE) in the client's connectivity callback whenever the connection is forcibly closed by the gRPC server. Most of the time, I do see this condition. For example, the following is what I see in my client log as correct behavior:

2018-02-22 01:47:04+0000 [-] 2018-02-22 01:47.04 XXX ChannelConnectivity.IDLE
2018-02-22 01:47:04+0000 [-] 2018-02-22 01:47.04 XXX ChannelConnectivity.READY
# server is killed at 1:47:34
2018-02-22 01:47:34+0000 [-] 2018-02-22 01:48.19 XXX ChannelConnectivity.TRANSIENT_FAILURE
2018-02-22 01:47:34+0000 [-] 2018-02-22 01:47.34 XXX ChannelConnectivity.IDLE

### What did you see instead?

Here is a client log from what I consider incorrect behavior:

2018-02-22 19:48:04+0000 [-] 2018-02-22 01:47.04 XXX ChannelConnectivity.IDLE
2018-02-22 19:48:04+0000 [-] 2018-02-22 01:47.04 XXX ChannelConnectivity.READY
# server is killed at 19:50:22
2018-02-22 19:50:22+0000 [-] 2018-02-22 19:50.22 XXX ChannelConnectivity.IDLE

The connectivity callback reports IDLE, but there is no TRANSIENT_FAILURE received. I allowed the client to sit for approximately 20 minutes, and still did not observe any failure messages.

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: does gRPC Core guarantee the kinds of behaviors on which @sbconsulting is wishing to rely? Do you see any holes in the story here?

**Comment by kpayson64** [comment]
I agree the connection state should be TRANSIENT_FAILURE, but I would consider it to be minor and cosmetic at this point.

A PR fixing this issue would be welcome.
