### ISSUE TITLE
gRPC Python grpcio source packages are too big to upload to PyPI 

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14508]
gRPC Python build system generates a source ".tar.gz" package for PyPI by grafting a bunch of goo from submodules and the git tree indiscriminately, making the package size upwards of 100MB, which is the PyPI limit. 

I had to manually untar the package and remove a bunch of .git directories to reduce the size to ~25MB, but I still think there is a ton of unnecessary files from `third_party` submodules that get grafted into the package by setuptools `sdist`. 

This problem applies to `grpcio` only, not `grpcio-{tools,health_checking,reflection}`.

**Comment by nathanielmanistaatgoogle** [comment]
Wow.

**Comment by mehrdada** [comment]
Fixed by https://github.com/grpc/grpc/pull/14533, though there might be room for a more fundamental fix
