### ISSUE TITLE
New Failure: thread_stress_test --gtest_filter=AsyncClientEnd2endTest.ThreadStress

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#14510]
- Test: thread_stress_test --gtest_filter=AsyncClientEnd2endTest.ThreadStress
- Poll Strategy: poll
- URL: https://kokoro2.corp.google.com/job/grpc/job/macos/job/master/job/grpc_basictests_dbg/1665

**Comment by vjpai** [comment]
Observed recently?
