### ISSUE TITLE
Please provide read access to CI failure details

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc#14519]
### What did you do?

Made pull request to grpc core.
 
### What did you expect to see?
 
Ability to review test failures.
 
### What did you see instead?
 
"Details" link for failed CI tests leads to internal Google resource which is inaccessible for external contributors. This requires manually pinging Google employees in order to figure out which tests did fail and in what way which adds artificial traction (for both sides) and makes it harder to contribute to the project.

**Comment by jtattermusch** [comment]
@euroelessar , I fully agree with you. We've been working on this for a while and I believe we are now pretty close to making the test results externally accessible.

**Comment by jtattermusch** [comment]
@euroelessar, I switched our test results to point to an externally accessible UI. You should now be able to see the test details on all new PR (and on old PRs after re-running the tests).

**Comment by euroelessar** [comment]
great, thanks!
