### ISSUE TITLE
C# How to Mock generated client base?

### ISSUE THREAD

**Issue by Disturbing** [grpc/grpc#14522]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes, related to Csharp grpc. Googled / searched for this, couldnt find anything meaningful.

### What version of gRPC and what language are you using?
 
gRPC C# 1.8.3

### What operating system (Linux, Windows, …) and version?
 
Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
VS 2017 15.3.3

### What am I looking to do?
I'm looking to mock any client generated base. 

The use case is to create a service which speaks to 3rd party grpc clients. I want to test all the logic within it, including the data sent to the 3rd party grpc client along with a mock response.  I'm using NSubstitute for mocking.

The problem is 

_client.CreateUserAsync(Arg.Any<string>()).Returns(.... AsyncUnaryCall<global::KintoHub.AuthBlock.CreateResponse>)....

How Can I go about mocking async unary call for a return with both Metadata and a Response.

Much thanks in advance!

**Comment by Disturbing** [comment]
Hey Guys - this would really be helpful to understand mocking with this library... It's quite a pain not being able to write effective tests when a dependency requires another dependency.  Any help please?

**Comment by jtattermusch** [comment]
Can you specify what are the exact API elements that are preventing you from testing/mocking?
- I know of them is: https://github.com/grpc/grpc/issues/10675 (ServerCallContext doesn't have a public constructor).

**Comment by jtattermusch** [comment]
I added examples how to create test doubles using public gRPC C# API in #15687.
