### ISSUE TITLE
Is there any general metadata processor support

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#14537]
Sometimes we need to enable metadata filters for all RPC, to do some version check for example. What I found most relative is `auth_metadata_processor`. However, this requires a `grpc_server_credentials` which can only be created with SSL credentials. SSL credentials can be redundant if the service is only deployed and accessed internally or there is other mechanism to ensure security. So is there any way to create a general metadata processor?

Maybe client side support is also required too, though I found `grpc_metadata_credentials_create_from_plugin` which doesn't seem to depend on any SSL related component just from the API level.

**Comment by nathanielmanistaatgoogle** [comment]
@BusyJay: with what language(s) are you working with gRPC? Also have you looked at what are called "interceptors"?

**Comment by BusyJay** [comment]
@nathanielmanistaatgoogle Yes, interceptors are exactly what I'm looking for. I'm using pingcap/grpc-rs, which wraps the gRPC c core and is written in rust. If it's supported in the c core, then it's very easy to be supported in the wrapper.

**Comment by mehrdada** [comment]
@BusyJay The first-party high level language APIs available for C#, Python, Go, Java, and Ruby have an explicit interceptor API that let you look into metadata as well as other things.  I don't know about the Rust implementation—but it looks like this is a good feature request for them. The C core has a filter API that operates in Core that's fairly low level by comparison (the language API-level interceptors do not even use the filter API).

**Comment by BusyJay** [comment]
Interesting. Can you point to the sources where both server side and client side interceptors are supported? As far as I can tell, the C# version only has the interceptors for client side.

**Comment by mehrdada** [comment]
This is the C# PR: https://github.com/grpc/grpc/pull/12613/files Python PR: https://github.com/grpc/grpc/pull/13722/files

C# implementation supports both (see the server-side tests here https://github.com/mehrdada/grpc/blob/master/src/csharp/Grpc.Core.Tests/Interceptors/ServerInterceptorTest.cs)

**Comment by BusyJay** [comment]
Thank you, it's very helpful!
