### ISSUE TITLE
Segfault with PyPy5.10 on Ubuntu host (gRPC being used in Docker container)

### ISSUE THREAD

**Issue by initialed85** [grpc/grpc#14559]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?

I think so, but I'm not certain (as it's related to PyPy).
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
grpcio==1.9.1 with PyPy5.10 (also tried PyPy5.9)
grpcio==1.10.0rc2 with PyPy5.10
(also both versions with Python2.7 but the issue doesn't appear with CPython)
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04 Docker container (on Ubuntu 16.04 host)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
PyPy5.10 and PyPy5.9
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I'm not sure I can provide a recipe, this is seen in our production and our dev hosts (all Ubuntu, Docker, PyPy etc). gRPC is being used to provide RPC between a bunch of different processes (about 20 or so) in a very naive way (a single service that permits the calling of remote Python methods- pickles args and kwargs, returns pickled result or exception- pickled information is base64 encoded to ensure no strange bytes).

Code doesn't deviate much from the gRPC Python examples (insecure_channel, etc), just wrapped up in convenience objects.

The environments include both Python2.7 and PyPy5.10/5.9 (briefly tested with 5.9 to ensure issue remained)- Python2.7 is required because some of the libraries we use are only supported/stable in CPython. There are no errors seen for Python or segfaults that we're aware of.
 
### What did you expect to see?
No segfaults in /var/log/syslog of the host (not the container)
 
### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Segfaults in /var/log/syslog of the host (not the container) that I *think* are related to threads (probably from the ThreadPoolExecutor), not processes (as nothing claims to have died according to our logs- the only indication anything is wrong are these message in the syslog; I'm confident of this because all our processes are managed by supervisor and supervisor reports that nothing has died, plus everything is operating correctly as far as we can see).

	saetech@saetech-dev-other:~$ cat /var/log/syslog | grep grpc
	Mar  1 07:53:53 saetech-dev-other kernel: [825597.533326] grpc_global_tim[19250]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 08:55:03 saetech-dev-other kernel: [829268.200064] grpc_global_tim[2202]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:00:46 saetech-dev-other kernel: [829610.589730] grpc_global_tim[11735]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:05:30 saetech-dev-other kernel: [829894.240582] grpc_global_tim[22602]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:45:14 saetech-dev-other kernel: [832279.123927] grpc_global_tim[31015]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:46:51 saetech-dev-other kernel: [832375.260999] grpc_global_tim[1322]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:49:43 saetech-dev-other kernel: [832547.418596] grpc_global_tim[6240]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:50:00 saetech-dev-other kernel: [832564.966688] grpc_global_tim[6728]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 09:52:53 saetech-dev-other kernel: [832737.649599] grpc_global_tim[11524]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 10:16:52 saetech-dev-other kernel: [834176.266758] grpc_global_tim[25552]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 10:23:45 saetech-dev-other kernel: [834589.461982] grpc_global_tim[4874]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 10:24:19 saetech-dev-other kernel: [834623.525647] grpc_global_tim[5812]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 10:41:46 saetech-dev-other kernel: [835670.927948] grpc_global_tim[5796]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 10:53:08 saetech-dev-other kernel: [836352.090519] grpc_global_tim[27986]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 10:55:50 saetech-dev-other kernel: [836514.630537] grpc_global_tim[32587]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 11:32:34 saetech-dev-other kernel: [838718.664372] grpc_global_tim[3096]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 11:34:40 saetech-dev-other kernel: [838844.194013] grpc_global_tim[6469]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 11:50:18 saetech-dev-other kernel: [839782.067845] grpc_global_tim[3408]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 11:55:44 saetech-dev-other kernel: [840107.851967] grpc_global_tim[12852]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 14:05:23 saetech-dev-other kernel: [847886.477569] grpc_global_tim[26386]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 14:05:26 saetech-dev-other kernel: [847890.321630] grpc_global_tim[26485]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 14:15:35 saetech-dev-other kernel: [848498.537456] grpc_global_tim[11078]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 14:21:43 saetech-dev-other kernel: [848867.097584] grpc_global_tim[24464]: segfault at 7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60 error 4 in cygrpc.pypy-41.so[7f2a844ad000+265000]
	Mar  1 14:47:54 saetech-dev-other kernel: [850438.002920] grpc_global_tim[5848]: segfault at 7fd35362ae00 ip 00007fd355df4c37 sp 00007fd331ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 14:54:31 saetech-dev-other kernel: [850835.190685] grpc_global_tim[19139]: segfault at 7fd35362ae00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:00:00 saetech-dev-other kernel: [851163.637940] grpc_global_tim[28754]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:02:30 saetech-dev-other kernel: [851313.835961] grpc_global_tim[825]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:31:29 saetech-dev-other kernel: [853053.054058] grpc_global_tim[25344]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:34:48 saetech-dev-other kernel: [853251.282277] grpc_global_tim[31086]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:42:00 saetech-dev-other kernel: [853683.967581] grpc_global_tim[13999]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:42:41 saetech-dev-other kernel: [853725.079940] grpc_global_tim[15171]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 15:58:28 saetech-dev-other kernel: [854671.372439] grpc_global_tim[13512]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:04:10 saetech-dev-other kernel: [855013.865133] grpc_global_tim[23889]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:08:01 saetech-dev-other kernel: [855244.255952] grpc_global_tim[30540]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:23:49 saetech-dev-other kernel: [856192.320613] grpc_global_tim[28817]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:29:30 saetech-dev-other kernel: [856533.876393] grpc_global_tim[8319]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:35:05 saetech-dev-other kernel: [856868.627339] grpc_global_tim[19259]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:35:31 saetech-dev-other kernel: [856894.414091] grpc_global_tim[20129]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:36:20 saetech-dev-other kernel: [856943.369703] grpc_global_tim[21776]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:38:06 saetech-dev-other kernel: [857049.780592] grpc_global_tim[24939]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:39:35 saetech-dev-other kernel: [857138.682305] grpc_global_tim[27565]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:44:44 saetech-dev-other kernel: [857447.028500] grpc_global_tim[4195]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:49:03 saetech-dev-other kernel: [857706.541817] grpc_global_tim[14537]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 16:57:49 saetech-dev-other kernel: [858232.230517] grpc_global_tim[30241]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 17:30:29 saetech-dev-other kernel: [860191.967895] grpc_global_tim[29111]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:05:54 saetech-dev-other kernel: [865917.470007] grpc_global_tim[20975]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:10:31 saetech-dev-other kernel: [866194.286573] grpc_global_tim[29285]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:19:43 saetech-dev-other kernel: [866745.630905] grpc_global_tim[15828]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:27:04 saetech-dev-other kernel: [867187.395368] grpc_global_tim[29172]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:30:10 saetech-dev-other kernel: [867373.520937] grpc_global_tim[2236]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:40:26 saetech-dev-other kernel: [867989.082213] grpc_global_tim[23267]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:42:50 saetech-dev-other kernel: [868133.461624] grpc_global_tim[27631]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:46:00 saetech-dev-other kernel: [868322.624680] grpc_global_tim[575]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 19:49:47 saetech-dev-other kernel: [868549.973620] grpc_global_tim[8836]: segfault at 7fd35362af00 ip 00007fd355df4c37 sp 00007fd289ffac60 error 4 in cygrpc.pypy-41.so[7fd355d80000+265000]
	Mar  1 20:10:52 saetech-dev-other kernel: [869815.216737] grpc_global_tim[14276]: segfault at 7f9db55aae00 ip 00007f9db7d751df sp 00007f9d41ffac60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:11:16 saetech-dev-other kernel: [869839.077837] grpc_global_tim[15041]: segfault at 7f9db55aae00 ip 00007f9db7d751df sp 00007f9d03feec60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:13:18 saetech-dev-other kernel: [869961.184118] grpc_global_tim[18596]: segfault at 7f9db55aae00 ip 00007f9db7d751df sp 00007f9ce7ff6c60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:20:29 saetech-dev-other kernel: [870391.929361] grpc_global_tim[30996]: segfault at 7f9db55aaf00 ip 00007f9db7d751df sp 00007f9ce7ff6c60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:21:18 saetech-dev-other kernel: [870440.813258] grpc_global_tim[32331]: segfault at 7f9db55aaf00 ip 00007f9db7d751df sp 00007f9ce7ff6c60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:25:34 saetech-dev-other kernel: [870696.595388] grpc_global_tim[7947]: segfault at 7f9db55aaf00 ip 00007f9db7d751df sp 00007f9ce7ff6c60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:30:38 saetech-dev-other kernel: [871000.907260] grpc_global_tim[18328]: segfault at 7f9db55aaf00 ip 00007f9db7d751df sp 00007f9ce7ff6c60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]
	Mar  1 20:39:03 saetech-dev-other kernel: [871505.374787] grpc_global_tim[602]: segfault at 7f9db55aaf00 ip 00007f9db7d751df sp 00007f9ce7ff6c60 error 4 in cygrpc.pypy-41.so[7f9db7d00000+275000]

The `7f2a81d57f20 ip 00007f2a84521c37 sp 00007f29b97f9c60` part seems to stay the same across service restarts and so is perhaps relevant.
	 
### Anything else we should know about your project / environment?

Environment as mentioned- Ubuntu hosts, Docker (varying versions throughout production) and Ubuntu containers, always PyPy5.10, always grpcio==1.91 (and some testing with grpcio==1.10.0rc2 showing the same result).

It's a piece of network monitoring software, lots of threads, lots of network activity- gRPC plays as the glue to permit us to distribute our work across multiple processors; we have a pattern as follows (summarised):

- Manager (thread)
	- PollerManager
		- Poller * n (threads)
			- [gRPC to a worker process]
				- Client (1 per Poller)
					- [gRPC to a worker process]
						- Connector (1 or 2 per Client)
							- [whatever means we interrogate the device]

There is also some information sought via gRPC about what to poll, all the same concept (gRPC carrying Python-pickled objects).

**Comment by nathanielmanistaatgoogle** [comment]
There's a chance that work going on in [issue 12531](https://github.com/grpc/grpc/issues/12531) will alleviate this, but there's also a chance that the problem might be unrelated.

Are you quite certain that you're not able to draft a minimal code sample? I'm slightly concerned about the pickling, but that might also be completely unrelated.

**Comment by initialed85** [comment]
@nathanielmanistaatgoogle I've created a gist (link below) that shows the interactions with gRPC (cut and paste from our codebase).

I apologise for the calls out to some of our internal libraries, but hopefully this will give you an idea of how it's implemented.

Some of the exceptions in common.py won't make sense- there's a whole broker system that we've designed that sits on top of it all that also uses gRPC to communicate (we used to use AMQP for this purpose so we tried to keep the API as similar as possible for the stuff that makes use of it).

**Comment by srini100** [comment]
@initialed85 , while @nathanielmanistaatgoogle  is out of office for next two weeks, please verify if your issue is related to #14523 .  Either you can downgrade to 1.8.4 or set env variable GRPC_POLL_STRATEGY=poll. Please confirm if this make any difference.

**Comment by initialed85** [comment]
@srini100 thanks for the follow-up; we're not seeing "can't start new thread" exceptions anywhere in our logs or stdout/stderr, so I'm not sure if it's related to that one.

I'll change our environment to include GRPC_POLL_STRATEGY=poll and report back, cheers.

**Comment by initialed85** [comment]
@srini100 

Just reporting back- I can confirm that with grpc-io==1.10 and the GRPC_POLL_STRATEGY=poll environment variable we're still seeing the segfaults in the Docker host's /var/syslog.

    saetech@saetech-dev-other:~$ docker exec -it ims_backend /bin/bash
    root@saetech-dev-other:/srv/wireless-manager-back-end# env | grep GRPC
    GRPC_POLL_STRATEGY=poll
    root@saetech-dev-other:/srv/wireless-manager-back-end# exit
    exit
    saetech@saetech-dev-other:~$ sudo tail /var/log/syslog | grep grpc
    Mar 20 15:18:51 saetech-dev-other kernel: [2493820.031257] grpc_global_tim[26473]: segfault at 7f5d77763f20 ip 00007f5d798781df sp 00007f5d33ffec60 error 4 in cygrpc.pypy-41.so[7f5d79803000+275000]
    Mar 20 15:20:26 saetech-dev-other kernel: [2493915.297268] grpc_global_tim[29588]: segfault at 7f5d77763f20 ip 00007f5d798781df sp 00007f5d33ffec60 error 4 in cygrpc.pypy-41.so[7f5d79803000+275000]
    Mar 20 15:22:58 saetech-dev-other kernel: [2494067.224940] grpc_global_tim[2487]: segfault at 7f6d0b2ed0a0 ip 00007f6d0d408f7f sp 00007f6cd27fbc90 error 4 in cygrpc.pypy-41.so[7f6d0d38d000+275000]
    Mar 20 15:26:13 saetech-dev-other kernel: [2494261.852902] grpc_global_tim[8763]: segfault at 7f6d0b2ed0a0 ip 00007f6d0d408f7f sp 00007f6cd27fbc90 error 4 in cygrpc.pypy-41.so[7f6d0d38d000+275000]
    saetech@saetech-dev-other:~$

**Comment by srini100** [comment]
@initialed85 I don't have any other ideas to try. Are you able to get crash stack with symbols?  BTW, Pypy is not supported so it will be hard to spend time on this.

**Comment by initialed85** [comment]
@srini100 It's all good, thanks for looking into things for us- completely understand that PyPy isn't supported; I'm happy for you guys to close this issue.

I'll see if I can get a core dump or something, but nothing actually fails in our system and none of the PIDs match any of the PIDs of our processes (which bore the speculation that maybe it was a TID for a GRPC server instance's thread pool).

**Comment by srini100** [comment]
@initialed85 I am closing this. Keep an eye on #12531 and try it out when it is fixed. grpc_global_tim[xx] does look like timer thread in GRPC C-core implementation (grpc_global_timer). Without symbols for ip/sp addresses we can't see where it crashed.
