### ISSUE TITLE
[WIN32] synchronization facilities

### ISSUE THREAD

**Issue by zeliard** [grpc/grpc#1456]
1. https://github.com/grpc/grpc/blob/master/src/core/support/sync_win32.c#L49
why we need grp_mu.locked?

2. https://github.com/grpc/grpc/blob/master/src/core/support/sync_win32.c#L68-L71
IMHO, I think these lines (68-71) are not necessary. why?

**Comment by nicolasnoble** [comment]
Mutexes in grpc are strictly non-recursive. For the sake of sanity and consistency, we are enforcing that rule with `GPR_ASSERT(!mu->locked)` during `gpr_mu_lock`. So we need to keep track of the status of the mutex.

**Comment by zeliard** [comment]
OK, I see :)
