### ISSUE TITLE
Richer call creation

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#14569]
I'm currently [reworking the Python code that uses the Core API](https://github.com/grpc/grpc/issues/12531) and having some frustration with call creation.

The story today goes something like:

1. I am ready to invoke my RPC. I have a method, credentials, two batches of operations, and all the other good stuff associated with invoking an RPC.
2. I call `grpc_channel_create_call` to create the call. This at least cannot fail.
3. I call `grpc_call_set_credentails` to set the credentials on the call. This can fail and if it does I have to handle it (by cancelling the call and unreffing the call, right?)
4. I call `grpc_call_start_batch` to start the first batch on the call. This can fail (illegal metadata supplied by the application is the only worthwhile failure mode; the others are programming mistakes on my part) and if it does I have to handle it (by cancelling the call and unreffing the call, right?).
5. I call `grpc_call_start_batch` to start the second batch on the call. This can fail (but at least these are all programming mistakes on my part, I think) and if it does I have to handle it (by cancelling the call, unreffing the call, and calling `grpc_completion_queue_next` to get the event associated with the successfully-started first batch, right?).

Why should program control pass from gRPC Python to gRPC Core and back four separate times just to invoke an RPC? How about a more rich call creation method that accepts everything I have to give (including up to six separate batches of operations, if I choose to break them up that way) in one fell swoop and then either fails or doesn't? That would simplify my error handling a great deal.

**Comment by kpayson64** [comment]
A few things:

1. Calls that haven't had any batches started (successfully) don't need to be cancelled.
2. For unary calls, you should be able to make a single call to ```grpc_call_start_batch```.  If we are doing something else in Python, that is an artifact of the Python usage, rather than a limitation of the c-core.

FWIW, C++ ```assert()```s on ```grpc_call_start_batch``` failure.  This indicates that the c-core has been invoked incorrectly, and is not recoverable.

I think it makes the most sense to just do some pre-processing on the application supplied metadata, and throw a Python exception if there is a failure.

As far as a 1-and-done c-core API, at most it would be able to merge ```grpc_channel_create_call``` and ```grpc_call_set_credentials```.  Being able to to batches is needed for streaming.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for considering!

1. Good to know!
2. Yes, for unary-unary calls we do make a single call to `grpc_call_start_batch` at RPC invocation time (and this is also the only `grpc_call_start_batch` call for the entire RPC). For other cardinalities of calls we make as many as two calls to `grpc_call_start_batch` at RPC invocation time (and other `grpc_call_start_batch` calls may follow later). But the API in its current form suggests that we could make as many as six calls if we really wanted to.

Around... Beta, I think (mid-2015?) we did in fact talk about vetting the metadata before starting a batch with it, but the decision at the time was that we didn't want to reimplement or repeat the vetting that is done at batch start time. I'd be open to revisiting that decision... if Core wants to expose a vetting function. I'd be skittish about implementing a separate vetting function in the Python subcodebase.

I'm not sure your last paragraph is on-topic - this feature request is for one-and-call-creation-done, not one-and-RPC-done. Even if implemented as described and one or two or six batches are allowed to be included in a single call creation function that wouldn't preclude starting later batches on the created call. Right?

**Comment by kpayson64** [comment]
There are currently no plans to add rich call creation.  We can re-open this issue if someone plans on re-visiting it.
