### ISSUE TITLE
Large number of timing threads created, regardless of async server threads, low performance

### ISSUE THREAD

**Issue by gwihlidal** [grpc/grpc#14578]
### What version of gRPC and what language are you using?
 
v1.7.2 c++
 
### What operating system (Linux, Windows, …) and version?
 
Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 MSVC 2017

### What did you do?

I implemented an async service so I could explicitly control the threading (to get around dynamic thread pool spawning a large number of threads without limit), and while this is working and performance has improved significantly, perf is still quite bad overall. It seems like regardless of the async service, grpc spawns (arbitrarily) timing threads which I can't seem to control.
 
### What did you expect to see?
 
 Fewer timing threads than async server threads (or at least 1:1 if there's a good reason)

### What did you see instead?
 
Massive number of timing threads compared to the number of async server threads.

Examples:

12 explicitly spawned threads, 113 implicitly spawned timing threads:
![image](https://user-images.githubusercontent.com/564042/36916305-d85ab35e-1e53-11e8-9986-73d9a423980a.png)

4 explicitly spawned threads, 20 implicitly spawned timing threads:
![image](https://user-images.githubusercontent.com/564042/36916326-e24a2c46-1e53-11e8-8eeb-26a565392957.png)

12 explicitly spawned threads, 37 implicitly spawned timing threads:
![image](https://user-images.githubusercontent.com/564042/36916335-e6e4522c-1e53-11e8-84f7-b42deac3c470.png)

It would be great to know if the timing threads can be either reduced, or disabled somehow, and also what they are used for.

Any best practices on writing a high performance c++ async server where an RPC can take a long time to return (heavy calculation) would also be great to know.

### Anything else we should know about your project / environment?

Heavy mix of 3d game engine, high end graphics rendering, in-process deep learning inference, and very performance critical :)

Thank you very much!
Graham

**Comment by sreecha** [comment]
Hi @gwihlidal,
Looks like most of these are not timer thread but '[executor](https://github.com/grpc/grpc/blob/v1.10.0/src/core/lib/iomgr/executor.cc)' threads instead. The max number of threads can be [2x](https://github.com/grpc/grpc/blob/v1.10.0/src/core/lib/iomgr/executor.cc#L94) the number cores and unfortunately its not configurable at the moment.

Broadly speaking, "executor threads" are used to do some background tasks (like address resolution) or to move some tasks off of the application-provided threads (to prevent them from taking too long before returning to the user from completion-queue-next calls). So reducing the max executor threads many not be a good idea.

It would help to know a few more details on your application. I am assuming you are noticing on the server side. SO approx  how many incoming channels ? how many calls ? - are the requests typically short lived or long lived? (do they do a lot of network i/o)?
 etc..

**Comment by sreecha** [comment]
Hi @gwihlidal ,
Wanted to followup once more:
From the screenshots you posted, the threads are 'executor'  threads and not timer threads and unfortunately they cannot be configured. It is a bit surprising that there are 112 executor threads (it should not exceed 2x the number of cores) - Does the machine on which you ran this have >= 56 cores ? If so, this is expected. If not, this is a bug worth that we should investigate in grpc side.

**Comment by sreecha** [comment]
I am closing this issue - since we made a few changes to the executor code and the timer manager code. 

Also, any executor threads and timer-manager you see are by-design; unless the threads are more than 2x the number of cores on your machine in which case it is clearly a bug. Please feel free to reopen the issue if that is what you see (i.e executor threads that are more than 2x the number of cores).
