### ISSUE TITLE
Default thread stack size on Mac OS X

### ISSUE THREAD

**Issue by tomgr** [grpc/grpc#14587]
### What version of gRPC and what language are you using?
1.10.0 C++

### What operating system (Linux, Windows, …) and version?
Mac OS X

### Description
On Mac OS X, the default stack size for non-main threads created using pthread_create is fixed at 512KB and cannot be altered by any calls to, for example, setrlimit. This means that threads created by GRPC to handle requests have a relatively small stack size (the main thread has a 8MB stack by default).

It would be useful to either allow the default stack for GRPC worker threads to be configured, or to set the stack size of the worker threads to the same size as the main thread stack size (i.e. equal to ulimit -s). Chromium does the latter and sets the default stack size of threads to ulimit -s https://chromium.googlesource.com/chromium/src/base/+/master/threading/platform_thread_mac.mm#202.

**Comment by nicolasnoble** [comment]
This is to be done via the `pthread_attr_setstacksize` pthread attribute.
