### ISSUE TITLE
How can i do grpc unit test with python

### ISSUE THREAD

**Issue by ciiiii** [grpc/grpc#14592]
### What version of gRPC and what language are you using?
 1.10.0, python
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python3.6
 
### What did you do?
 unit test

### What did you expect to see?
 how to do grpc unit test 
 
### What did you see instead?
code like this
https://github.com/grpc/grpc/blob/1b4be41a7212fa7ab18f73e1f8cebc12ddeffc0f/src/python/grpcio_tests/tests/unit/_rpc_test.py

**how can i do this with my grpc server code**

**Comment by nathanielmanistaatgoogle** [comment]
My preferred means of locally running the unit tests is `./tools/run_tests/run_tests.py --language=python --compiler=all_the_cpythons --newline_on_success` from repository top-level.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; I'm not sure that there's anything left to say here at the moment. (Our infrastructure is always changing, so the best command with which to run the tests today may not be the same in six months...)
