### ISSUE TITLE
Greater than expected memory use

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#14595]
This issue continues the discussion started [here](https://github.com/grpc/grpc/issues/12383#issuecomment-369960118).

**Comment by nathanielmanistaatgoogle** [comment]
@parachutepy: are you able to share any code with us? Would you be able to share any data with us? Are you able to make statements such as "the attached two megabytes, when deserialized into a `<my_module_pb2.MyMessage>`, takes up three hundred megabytes in the Python interpreter, but I think it should only take up thirty"?

**Comment by parachutepy** [comment]
@nathanielmanistaatgoogle : Unfortunately, will not be able to share code/data. One way out for us(picked up from your earlier statement of storing in file), which kind of helped is, post the streaming return from server, we altered our code to go against only the data that was needed for our application which greatly reduced the memory and time taken to process. 

I feel the issue stemmed from the complex nested structure of the data that needed to be processed. 

Thanks again for the insight and quick responses! Deeply appreciate it.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for following up with us. Closing as it sounds like there's nothing remaining that is actionable for us on the gRPC side at this time (but if in the future you see us wasting memory please let us know!).

**Comment by parachutepy** [comment]
Sure will do ....
