### ISSUE TITLE
Unity: grpc_csharp_ext for Emscripten / WebAssembly

### ISSUE THREAD

**Issue by zaneclaes** [grpc/grpc#14603]
### What version of gRPC and what language are you using?
 1.8.3 / csharp
 
### What operating system (Linux, Windows, …) and version?
 OSX, High Sierra (Latest)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 cmake
 
### Request
Very similar to https://github.com/grpc/grpc/issues/14402 -- I'd also like to compile for emscripten / web assembly for use in a game built in Unity. This [StackOverflow](https://stackoverflow.com/questions/45260216/emscripten-cmake-pass-emscripten-options-in-cmakelist-file) question suggests that it is possible to use cmake for this, just as we did in the above gRPC issue/request.

### What I've Tried
Based upon the above StackOverflow, I installed the `emsdk` and then ran:
```
cmake -DCMAKE_BUILD_TYPE=Release \
  -G "Unix Makefiles" \
  -DCMAKE_TOOLCHAIN_FILE=/Users/zaneclaes/Programming/emsdk/emscripten/incoming/cmake/Modules/Platform/Emscripten.cmake . 
```

The `cmake` succeeds, but when I try to `make grpc_csharp_ext -B EMBED_OPENSSL=true`, I get:
```
[  0%] Building C object third_party/boringssl/crypto/pkcs8/CMakeFiles/pkcs8_lib.dir/pkcs8.c.o
Traceback (most recent call last):
  File "/Users/zaneclaes/Programming/emsdk/emscripten/incoming/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/Users/zaneclaes/Programming/emsdk/emscripten/incoming/tools/python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/Users/zaneclaes/Programming/emsdk/emscripten/incoming/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/Users/zaneclaes/Programming/emsdk/emscripten/incoming/emcc.py", line 639, in run
    options, settings_changes, newargs = parse_args(newargs)
  File "/Users/zaneclaes/Programming/emsdk/emscripten/incoming/emcc.py", line 1992, in parse_args
    options.debug_level = validate_arg_level(requested_level, 4, 'Invalid debug level: ' + newargs[i])
  File "/Users/zaneclaes/Programming/emsdk/emscripten/incoming/emcc.py", line 2790, in validate_arg_level
    raise Exception(err_msg)
Exception: Invalid debug level: -ggdb
make[3]: *** [third_party/boringssl/crypto/pkcs8/CMakeFiles/pkcs8_lib.dir/pkcs8.c.o] Error 1
make[2]: *** [third_party/boringssl/crypto/pkcs8/CMakeFiles/pkcs8_lib.dir/all] Error 2
make[1]: *** [CMakeFiles/grpc_csharp_ext.dir/rule] Error 2
make: *** [grpc_csharp_ext] Error 2
```

I'm guessing I need to make updates to `CMakeLists.txt`, as the StackOverflow suggests, and there are probably a number of flags I need to change, but I don't see `-ggdb` or `gdb` anywhere in the makefiles. *I am opening this issue to sanity-check that this is a sane road to go down*, and maybe ask @jtattermusch for hints as to how to properly modify the file for the `Emscripten` target ;)

**Comment by jtattermusch** [comment]
@zaneclaes  I have no experience with Emscripten, sorry.  It would be great if you shared you experience once you're successful.
