### ISSUE TITLE
Bazel failure on MacOS

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#14627]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
yes
 
### What version of gRPC and what language are you using?
 HEAD, C++
 
### What operating system (Linux, Windows, …) and version?
 MacOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 ```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
 
### What did you do?
```
bazel build test/core/avl:avl_test
bazel-bin/test/core/avl/avl_test
```
 
### What did you expect to see?
 Test passes
 
### What did you see instead?
```
dyld: Symbol not found: _deflate
  Referenced from: /Users/ncteisen/Desktop/grpc/bazel-bin/test/core/avl/../../../_solib_darwin_x86_64//liblibgrpc_Ubase_Uc.so
  Expected in: flat namespace
 in /Users/ncteisen/Desktop/grpc/bazel-bin/test/core/avl/../../../_solib_darwin_x86_64//liblibgrpc_Ubase_Uc.so
Abort trap: 6
```

**Comment by whitlockjc** [comment]
I've run into the same thing, and since there hasn't been any traction I figured I'd give a gentle _"bump"_.
