### ISSUE TITLE
Interceptor API converts blocking calls into using managed call API

### ISSUE THREAD

**Issue by aamitdb** [grpc/grpc#14621]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes I believe so. This is a feature request about changing the current interceptor implementation, with an actionable goal.
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.8.4 
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 2.7.14
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Ran default value interceptor example https://github.com/grpc/grpc/blob/master/examples/python/interceptors/default_value/greeter_client.py#L28.
 
### What did you expect to see?
Blocking unary_unary calls e.g. a RPC call where we directly rely on `__call__` rather then future are not run as managed calls.
 
### What did you see instead?
The client interceptor API makes all unary_unary calls into `future().result` on the `_Rendezvous` which makes them managed calls that bring up a CleanupThread to run spin on.

I believe it should be possible to provide the same interceptor API without falling back to using `future` API everywhere by having the continuation in `__call__` cases call into `_blocking`. This would avoid spawning new cleanup threads so often. 

The PR I see in the original issue (https://github.com/grpc/grpc/issues/8767 on #8767) avoid this behavior without too much boilerplate https://github.com/grpc-ecosystem/grpc-opentracing/pull/32/files#diff-e66d1ba260d8e120205fbd3d71812c22R30.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by mehrdada** [comment]
We decided to opt for the new behavior because the original design required authors to implement two interceptor functions that have a similar design and is basically a performance optimization. I thought we can always add an interface that lets the user special case blocking if their interceptor supports blocking explicitly, but fall back on the future-based operation if that interface is unspecified. Is that something that resolves your issue?

**Comment by aamitdb** [comment]
That would work. 

I don't understand why using the design from [the opentracing PR](https://raw.githubusercontent.com/rnburn/grpc-opentracing-1/23d3f7984ee6b969f947fcba356418432db6a72d/python/grpc_opentracing/grpcext/_interceptor.py ) can't be updated to avoid having 2 interceptor methods for a `xxx_unary` interceptor while also using blocking semantics for a `__call__`.

The problem as I understand it is that with the opentracing PR,  the result of `continuation(call_details, request)` could either be a scalar value or a `_Rendezvous`  and as such if you're actually trying to replace the value it would be unclear if you should return a scalar or `Call/Future` yourself.

Imo it would be nicer if we could push this down into the interaction between channel/interceptor to avoid the two methods for someone using interceptor API. If there was some method from `XXXCallable` that returned a `_Rendezvous` representing the state directly (so not future), without raising (like with_call will on non-OK status), I think we could call into that?

Then people using interceptor API could maintain world where they only are concerned about returning a Call/Future. Imo the Call/Future result APIs are kind of large to maintain anyway if you do plan to replace the result, but it would allow the same operations as current API does without making them more painful imo.

**Comment by mehrdada** [comment]
@aamitdb I agree it's probably better to keep the current API and simply invoke the sync underlying method and adapt the result by wrapping it in a future: https://github.com/grpc/grpc/pull/14639
It still requires one additional allocation for the wrapped object but that's pretty minimal compared to using the underlying async API.
