### ISSUE TITLE
g_core_codegen_interface can be null in metadata_map destructor

### ISSUE THREAD

**Issue by prateekr** [grpc/grpc#14633]
Version: 1.10.0
Language: C++
 
Currently metadata_map requires g_core_codegen_interface to be initialized when destructed, which is not guaranteed by the class itself.
https://github.com/grpc/grpc/blob/474c5950686e3962bd339c93d27e369bf64f568f/include/grpcpp/impl/codegen/metadata_map.h#L31-L33

I'm running into this issue from creating a unit test for a grpc server class.  I.e. when I initialize ::grpc::ServerContext, it segfaults upon destruction of the member field: 
https://github.com/grpc/grpc/blob/474c5950686e3962bd339c93d27e369bf64f568f/include/grpcpp/impl/codegen/server_context.h#L293

I propose we do what's done for ::grpc::ClientContext and initialize GrpcLibraryInitializer as a static variable in either ::grpc::ServerContext or MetadataMap
https://github.com/grpc/grpc/blob/474c5950686e3962bd339c93d27e369bf64f568f/src/cpp/client/client_context.cc#L42

**Comment by vjpai** [comment]
Thanks for the detailed report.
