### ISSUE TITLE
Revisit socket shutdown to avoid the need for workaround from #14560.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14643]
As per discussion in #14560 (which is fixing test flake #14471) we should revisit the socket shutdown logic on Windows (and potentially for posix sockets as well) - the problem is that with the right timing, when a server goes for graceful shutdown the RST_STREAM and GOAWAY frames (which are successfully written by the server) might get lost in a failed read caused by an attempt to send PING frame to the server that is shutting down the socket in the meantime.

**Comment by jtattermusch** [comment]
CC @nicolasnoble

**Comment by yashykt** [comment]
Thanks for filing the bug Jan!

**Comment by yashykt** [comment]
I took a look a bit ago. What I found was that it was more of a kernel level detail. If on receiving a write error, the kernel decides to scrub its read buffers, there isn't much we can do about it.

**Comment by yashykt** [comment]
There doesn't seem to be much to do here, other than not trying to not send the ping at all.
