### ISSUE TITLE
grpc_completion_queue_create_for_pluck(NULL) fail

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#14682]
### What version of gRPC and what language are you using?
 gRPC-v1.10.0
 
### What operating system (Linux, Windows, …) and version?
 2.6.32-042stab127.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 Segment fault.

This issue is split from https://github.com/grpc/grpc/issues/14601. At the beginning of the program, 
```
grpc_init(); 
grpc_completion_queue_create_for_pluck(NULL);
```
will segment fault randomly.

Not all environment can reproduce it. Since the it happens randomly, I guess it's caused by random initial value for some variables.

This bug is introduced after gRPC-v1.7.0.

**Comment by ZhouyihaiDing** [comment]
The way to access the environment is in the comment at the bottom of https://github.com/grpc/grpc/issues/14601

**Comment by yashykt** [comment]
I just verified on that system that it has a faulty sched_getcpu syscall. It ends up returning a value more than the maximum number of cpus which leads to accessing unintended memory. This seems like a linux kernel issue.

**Comment by ZhouyihaiDing** [comment]
gRPC 1.6.0 works fine in such system while 1.7.0 start segment fault randomly. They both has this [syscall](https://github.com/grpc/grpc/blob/v1.6.0/src/core/lib/support/cpu_linux.c), is the usage of this number changes starting from 1.7.0?

**Comment by yashykt** [comment]
gRPC 1.6.0 was probably not using sched_getcpu as much as in 1.7.0.

**Comment by yashykt** [comment]
It definitely looks like a case of CPU hotplugging and sysconf(_SC_NPROCESSORS_CONF) not returning the maximum number of possible CPUs.
Created PR #14712 to fix this issue in gRPC. Manually verified that the fix works on the system. Tracking this separately in #14711. Please use gRPC 1.6 till the pull request gets merged.

**Comment by ZhouyihaiDing** [comment]
Thanks @yashykt . This PR solve the `grpc_completion_queue_create_for_pluck` segment fault in php extension.
Is it possibel that `grpc_completion_queue_shutdown(completion_queue);` is having the same issue? Because I noticed that the segment fault still there in php extension unless comment this function too. As well as `grpc_completion_queue_destroy`
Hi @svycka , it is strange that the syscall returns a wrong value. Maybe it will cause other errors not only in gRPC, but also somewhere else. Maybe you can confirm it with your hosting provide to see if they can fix it?

**Comment by yashykt** [comment]
@ZhouyihaiDing The PR makes it returns a default value of 0 for when the system has cpu hot-plugging, and so the same issue should not be occurring in other parts. As far as the hosting goes, I'm not sure what they can do to solve this issue. It's more of providing a way to determine the maximum number of hot-plugged CPUs at grpc initialization.

**Comment by ZhouyihaiDing** [comment]
Maybe `grpc_completion_queue_shutdown` segment fault is caused by other syscall? Can you please help to test this 3 lines together when you have time? Thank you!
```
grpc_completion_queue_create_for_pluck
grpc_completion_queue_shutdown
grpc_completion_queue_destroy
```
