### ISSUE TITLE
Bazel test failure: //test/core/security:alts_security_connector_test

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#14696]
https://source.cloud.google.com/results/invocations/489be99f-f262-4430-9c96-a69c0f0ae514/targets/%2F%2Ftest%2Fcore%2Fsecurity:alts_security_connector_test@poller%3Depoll1/log

+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/core/security/alts_security_connector_test
E0313 19:04:39.423419240      18 alts_security_connector.cc:109] Invalid arguments to grpc_alts_auth_context_from_tsi_peer()
E0313 19:04:39.423551070      18 alts_security_connector.cc:109] Invalid arguments to grpc_alts_auth_context_from_tsi_peer()
E0313 19:04:39.423562175      18 alts_security_connector.cc:120] Invalid or missing certificate type property.
E0313 19:04:39.423589207      18 alts_security_connector.cc:127] Missing rpc protocol versions property.
E0313 19:04:39.423597477      18 alts_security_connector.cc:127] Missing rpc protocol versions property.
E0313 19:04:39.423603060      18 alts_security_connector.cc:127] Missing rpc protocol versions property.
E0313 19:04:39.423617547      18 transport_security_common_api.cc:68] nanopb error: invalid data_size
E0313 19:04:39.423624934      18 alts_security_connector_test.cc:139] assertion failed: grpc_gcp_rpc_protocol_versions_encode(&peer_versions, &serialized_peer_versions)
Aborted (core dumped)

**Comment by adelez** [comment]
Same failure for 
//test/core/tsi/alts/handshaker:alts_handshaker_client_test
//test/core/tsi/alts/handshaker/alts_handshaker_service_api_test
//test/core/tsi/alts/handshaker:alts_tsi_handshaker_test
//test/core/tsi/alts/handshaker:alts_tsi_utils_test
//test/core/tsi/alts/handshaker:transport_security_common_api_test

Plus, #14695 may be caused by the same problem.

**Comment by adelez** [comment]
@nicolasnoble @dgquintas , Jiangtao suggested possible bugs on nanopb. Can #14697 be related?

**Comment by jtattermusch** [comment]
any progress here? bazel tests are always red on our PR, so this needs to be fixed with high priority.

**Comment by jiangtaoli2016** [comment]
The fix is here https://github.com/grpc/grpc/pull/14716.

**Comment by yihuazhang** [comment]
#14716 has just been merged. @jtattermusch, could you please run bazel tests again to confirm if it works?

**Comment by adelez** [comment]
Master builds are green now! Your fix solved all 40+ failures. Woohoo! Thanks.
