### ISSUE TITLE
Bazel test failure: //test/cpp/end2end:health_service_end2end_test

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#14698]
https://source.cloud.google.com/results/invocations/489be99f-f262-4430-9c96-a69c0f0ae514/targets/%2F%2Ftest%2Fcpp%2Fend2end:health_service_end2end_test@poller%3Depoll1/log

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/cpp/end2end/health_service_end2end_test
D0313 19:04:37.331361163      18 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from HealthServiceEnd2endTest
[ RUN      ] HealthServiceEnd2endTest.DefaultHealthServiceDisabled
[       OK ] HealthServiceEnd2endTest.DefaultHealthServiceDisabled (5 ms)
[ RUN      ] HealthServiceEnd2endTest.DefaultHealthService
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 0
To be equal to: s.error_code()
      Which is: 13
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 0
To be equal to: s.error_code()
      Which is: 3
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 0
To be equal to: s.error_code()
      Which is: 3
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 5
To be equal to: s.error_code()
      Which is: 3
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 0
To be equal to: s.error_code()
      Which is: 13
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 0
To be equal to: s.error_code()
      Which is: 3
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 0
To be equal to: s.error_code()
      Which is: 3
test/cpp/end2end/health_service_end2end_test.cc:186: Failure
      Expected: expected_status.error_code()
      Which is: 5
To be equal to: s.error_code()
      Which is: 3
[  FAILED  ] HealthServiceEnd2endTest.DefaultHealthService (5 ms)
[ RUN      ] HealthServiceEnd2endTest.DefaultHealthServiceAsyncOnly
[       OK ] HealthServiceEnd2endTest.DefaultHealthServiceAsyncOnly (2 ms)
[ RUN      ] HealthServiceEnd2endTest.ExplicitlyDisableViaOverride
[       OK ] HealthServiceEnd2endTest.ExplicitlyDisableViaOverride (1 ms)
[ RUN      ] HealthServiceEnd2endTest.ExplicitlyOverride
[       OK ] HealthServiceEnd2endTest.ExplicitlyOverride (3 ms)
[----------] 5 tests from HealthServiceEnd2endTest (16 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (16 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] HealthServiceEnd2endTest.DefaultHealthService

 1 FAILED TEST

**Comment by jtattermusch** [comment]
@vjpai   any progress here? we need to fix the bazel issues ASAP - the bazel tests are always red on our PRs and that's introducing noise we really don't want to have.

**Comment by adelez** [comment]
Looks like fixed by #14716.
