### ISSUE TITLE
ALTS tests not hooked up in run_tests.py

### ISSUE THREAD

**Issue by jiangtaoli2016** [grpc/grpc#14699]
There are several ALTS unit tests (e.g., alts_handshaker_client_test, alts_tsi_handshaker_test, etc.) When we run `./tools/run_tests/run_tests.py -l c -r alts -t -S` , none of these ALTS tests are running. They are not hooked up properly.

**Comment by yihuazhang** [comment]
Since all ALTS unit tests are C++ tests, I think we should use `-l c++` instead which will trigger all tests.

**Comment by jtattermusch** [comment]
Looks like this can be closed. Please reopen if still an issue.
