### ISSUE TITLE
Bazel test failure: //test/cpp/client:client_channel_stress_test

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#14697]
https://source.cloud.google.com/results/invocations/489be99f-f262-4430-9c96-a69c0f0ae514/targets/%2F%2Ftest%2Fcpp%2Fclient:client_channel_stress_test@poller%3Depoll1/log

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/cpp/client/client_channel_stress_test
E0313 19:04:36.600654079      18 load_balancer_api.cc:146]   assertion failed: pb_encode(&outputstream, grpc_lb_v1_LoadBalanceRequest_fields, request) != 0

*******************************
Caught signal SIGABRT
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/libtest_Score_Sutil_Slibgpr_Utest_Uutil.so(+0x1d93)[0x7f36c8422d93]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f36c7b8b890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f36c6fe3067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f36c6fe4448]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Ulb_Upolicy_Ugrpclb_Usecure.so(_Z26grpc_grpclb_request_encodePK30_grpc_lb_v1_LoadBalanceRequest+0x10d)[0x7f36c83cd56d]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Ulb_Upolicy_Ugrpclb_Usecure.so(+0x879b)[0x7f36c83ca79b]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Ulb_Upolicy_Ugrpclb_Usecure.so(+0x7ef2)[0x7f36c83c9ef2]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Uclient_Uchannel.so(+0x1316f)[0x7f36c832616f]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Uclient_Uchannel.so(+0x13b3d)[0x7f36c8326b3d]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Ubase_Uc.so(_Z31grpc_combiner_continue_exec_ctxv+0x11a)[0x7f36c80a1f8a]
/b/s/w/ir/run/bazel-out/k8-opt/bin/test/cpp/client/client_channel_stress_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/client/../../../_solib_k8/liblibgrpc_Ubase_Uc.so(_ZN9grpc_core7ExecCtx5FlushEv+0x2d)[0x7f36c80afffd]
test/cpp/client/client_channel_stress_test[0x40ca48]
test/cpp/client/client_channel_stress_test[0x40a39f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f36c6fcfb45]
test/cpp/client/client_channel_stress_test[0x40a233]
Aborted (core dumped)

**Comment by adelez** [comment]
David, can you please triage this bug?

**Comment by adelez** [comment]
Other tests with the same failure: 
//test/cpp/end2end:grpclb_end2end_test
https://source.cloud.google.com/results/invocations/489be99f-f262-4430-9c96-a69c0f0ae514/targets/%2F%2Ftest%2Fcpp%2Fend2end:grpclb_end2end_test@poller%3Depoll1/log

**Comment by adelez** [comment]
Jiangtao suggested possible bugs on the nanopb side in #14696. Can this be related? @nicolasnoble

**Comment by jiangtaoli2016** [comment]
All the ALTS related test failures are related to nanopb and only happen on bazel. @yihuazhang is looking into it right now.

**Comment by adelez** [comment]
These failures only happen on bazel as well.

**Comment by jiangtaoli2016** [comment]
@yihuazhang found the root cause. @dgquintas and @yihuazhang are working on a fix.

**Comment by adelez** [comment]
Probably got fixed together by #14716.
