### ISSUE TITLE
Add StatusCodeName function to the C++ API that returns the string name of a status code

### ISSUE THREAD

**Issue by calder** [grpc/grpc#14718]
If this exists, I haven't been able to find it.

**Comment by vjpai** [comment]
Hi there. I think this won't make it to the API because we already provide the enumerated value (through the function Status::error_code() ), and the string representation of the status code does not provide additional meaning to the application (unlike the error_message or error_details)

**Comment by calder** [comment]
For logging, it's nice to be able to log a `Status::error_code()` in a human readable form rather than requiring a human to open up the gPRC source code to decode every enum value they seee.

**Comment by vjpai** [comment]
I totally agree, but that seems like an application/framing issue to me, not a gRPC library API issue.
