### ISSUE TITLE
Flaky Bazel Dbg Tests

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#14729]
There are some flaky Bazel tests. This run shows 4 failures, that I am pretty sure are not related to my change:

```
//test/core/bad_ssl:bad_ssl_cert_test@poller=epollsig                    FAILED in 25.0s
//test/core/end2end:h2_http_proxy_test@hpack_size@poller=epollsig        FAILED in 42.2s
//test/cpp/end2end:end2end_test@poller=epoll1                            FAILED in 22.3s
//test/cpp/naming:resolver_component_tests_runner_invoker@poller=poll-cv FAILED in 65.6s
```

https://source.cloud.google.com/results/invocations/773418ff-b2cd-4422-a389-fe5384bce5c0/targets/grpc%2Fubuntu%2Fpull_request%2Fremote_bazel_tests_dbg/log

**Comment by adelez** [comment]
These are different test failures, not infra bug.
#14240
#14730
#14512
#14732

Closing this bug.
