### ISSUE TITLE
Getting '--grpc_out: protoc-gen-grpc: The system cannot find the file specified.' error on win10

### ISSUE THREAD

**Issue by protector1990** [grpc/grpc#14740]
Hi,
I'm trying to install grpc for c++ from source on windows 10, but after building from source and trying to run it I get following error:

`C:\private\grpc\examples\cpp\helloworld>protoc -I ../../protos/ --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin ../../protos/helloworld.proto

--grpc_out: protoc-gen-grpc: The system cannot find the file specified.`

I tried following directions from INSTALL.md, but I'm consistently getting this same error. I've tried compiling with cmake & visual studio (2017 express), and cmake & ninja (I think it used VS 2015 compiler for that one though), but nevertheless, results are the same. Just to be noted, I added .build folder and protobuffer output folder to my path manually so that cmd could find protoc.exe.

I cloned master branch, and I am building from following commit:
SHA-1: f001d67d4e1e45101b51ca05e5150dc5d75b2575

Can you please help? What is missing on my machine? Is it protoc-gen-grpc? If that should be a file, I cannot seem to find it anywhere in the output folder. On the other hand, I do have grpc_cpp_plugin.exe in the output folder, and the error is also not related to input file (when I tried putting non-existing file as the input I got another type of error).

Please ask for any additional info you need.

Regards,
Marko

**Comment by tushardhoot** [comment]
Can you try --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe (specifying the .exe extension in the path)?

**Comment by yashykt** [comment]
Doesn't windows use backslash in the path?

Please post it on https://groups.google.com/a/google.com/forum/#!forum/grpc.io if this is still an issue
