### ISSUE TITLE
Simplified CMake mode for including as a submodule

### ISSUE THREAD

**Issue by hjmallon** [grpc/grpc#14743]
We are currently using protobuf, without gRPC, as a submodule. This works well and we tend to switch off various targets in the cmake project add with `add_subdirectory(protobuf EXCLUDE_FROM_ALL)`. 

We want to use gRPC. However, the build system is much more complicated. It looks like some requirements (such as Go) could be avoided with an `ENABLE_TESTING=Off` switch. As far as I can tell Go is only used for `boringssl` tests (which we would not want to build when using a submodule).

With the current set up we will probably build dynamic libraries, and distribute them, as adding ~10 submodules and a requirement on Go is probably too much overhead.

### What version of gRPC and what language are you using?
C++ with grpc 1.10.0 on macOS 10.10 to 10.13, Win10 and Linux too.

**Comment by jtattermusch** [comment]
There's some progress in https://github.com/grpc/grpc/pull/14864 (demonstrates that adding grpc via add_subdirectory is easy, but there's still a problem with additional dependencies being required - but the comments in the example also partially explain what can be done about it).
