### ISSUE TITLE
GRPC _cq thread won't exit when there is no ":" between IP and Port(127.0.0.12334  VS 127.0.0.1:2334)). 

### ISSUE THREAD

**Issue by savagecm** [grpc/grpc#14742]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 C++
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 GCC 4.8
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
I happened to use the following code and pass the IP address as "127.0.0.12234", which means I forget to add ":" in the address string.
 ::grpc::CreateChannel(grpc_connection.server_address, ::grpc::InsecureChannelCredentials());
 
I add a thread for the complete queue and found the thread won't exit event I call shutDown().

### What did you see instead?
 
Maybe add some valide check for the IP/port string.

**Comment by jtattermusch** [comment]
@y-zeng can you check if you can reproduce?

**Comment by jtattermusch** [comment]
@savagecm   can you please post a full snippet to reproduce?

**Comment by y-zeng** [comment]
@yashykt Could you please take a look?

**Comment by yashykt** [comment]
The client should not be able to connect to the server and the RPC should fail. On the server side, it will not see anything. 
I suspect the issue has something to do with how you are triggering shutdown. If you can link to your code, then I might be able to point it out.
