### ISSUE TITLE
Document usage of GRPC_SSL_CIPHER_SUITES

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#14754]
There are a number of discussion talking about setting GRPC_SSL_CIPHER_SUITES = "HIGH + ECDSA" to resolve some issues. This doesn't seem to be documented anywhere in gRPC projects. Please provide some documentation around this, perhaps in grpc/doc/environment_variables.md. References found here:
https://github.com/lightninglabs/lightning-coindesk/issues/2#issuecomment-354727899
https://github.com/grpc/grpc/issues/14489
https://github.com/grpc/grpc/issues/12093
https://stackoverflow.com/questions/36871607/grpc-credentials-createssl-cannot-read-property-createssl-of-undefined

**Comment by jiangtaoli2016** [comment]
I think the problem is that gRPC by default does not accept ECDSA. User has to specifically pass GRPC_SSL_CIPHER_SUITES to enable ECDSA cipher. 

https://github.com/grpc/grpc/pull/11699 would resolve this. 

Let me write a simpler version of PR first to enable it.
