### ISSUE TITLE
grpc_completion_queue_shutdown/grpc_completion_queue_destroy segment fault randomly in certain environment

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#14753]
It is the cause for the #14601. The user provided the way to access their environment in the comment.

### What version of gRPC and what language are you using?
 gRPC-v1.10.0
 
### What operating system (Linux, Windows, …) and version?
 2.6.32-042stab127.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 Segment fault.

This issue is split from https://github.com/grpc/grpc/issues/14601. At the beginning of the program, 
```
grpc_init(); 
grpc_completion_queue_create_for_pluck(NULL);
grpc_completion_queue_shutdown();
grpc_completion_queue_destroy();
```
will segment fault randomly.

Not all environment can reproduce it. Since the it happens randomly, I guess it's caused by random initial value for some variables.

This bug is introduced after gRPC-v1.7.0.

**Comment by ZhouyihaiDing** [comment]
The upstream issue was solved. 
gRPC Core after v1.10.0 doesn't have segment fault under RHEL 6 environment.

**Comment by yashykt** [comment]
Was it fixed by the hotplugged CPUs hack?

**Comment by ZhouyihaiDing** [comment]
Seems no. 
In v1.9.0, the hack only solve the `grpc_completion_queue_create_for_pluck(NULL);` segment fault.
But for `grpc_completion_queue_shutdown();` and `grpc_completion_queue_destroy();`, the segment fault still exist.
This segment fault exists in v1.7.0 and disappear in v1.10.0, not sure if it will re-appear later.
For the upstream issue, the static link to gRPC C-core still have the segment fault error. The temporary fix is dynamic link to C-core.

**Comment by cnangel** [comment]
![image](https://user-images.githubusercontent.com/78647/39003387-57986b3a-442d-11e8-8335-b3e1ef61695e.png)
something like grpc_completion_queue_destroy

**Comment by ZhouyihaiDing** [comment]
Hi @cnangel ,
Can you please give us more information about what system and language are you using? How you use the gRPC? It is better if you can provide a simple script to reproduce it.
Thank you for your help!
