### ISSUE TITLE
pecl-gRPC is missing -O2 optimization compile FLAG

### ISSUE THREAD

**Issue by axot** [grpc/grpc#14767]
Take a look of https://pecl.php.net/get/grpc-1.10.0.tgz,

## config.m4
```
CFLAGS="-Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11"
CXXFLAGS="-std=c++11 -fno-exceptions -fno-rtti"
```

By default `-O0` was used, so it will make `grpc.so` really slow as I mentioned in https://github.com/grpc/grpc/issues/14713#issuecomment-373604085.

**Comment by ZhouyihaiDing** [comment]
Thank you!
Can you also run `tools/buildgen/generate_projects.sh`. It will update config.m4. 
Our tests can make sure the new pear package works in different systems.

**Comment by axot** [comment]
The issue was resolved by https://github.com/grpc/grpc/pull/14768.
