### ISSUE TITLE
PHP distribtest php_macos_x64 broken on Kokoro

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14760]
```
Running in workspace workspace_php_macos_x64_None
+ cd workspace_php_macos_x64_None
+ test/distrib/php/run_distrib_test.sh
++ dirname test/distrib/php/run_distrib_test.sh
+ cd test/distrib/php
+ cp -r ../../../../input_artifacts/grpc-1.11.0dev.tgz .
+ find . -regex '.*/grpc-[0-9].*.tgz'
+ cut -b3-
+ xargs pecl install
Cannot install, php_dir for channel "pecl.php.net" is not writeable by the current user
```

https://sponge.corp.google.com/target?id=b7638c1a-fa99-43a4-b95b-ce0a0b26b966&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

I think this is because PHP installation has been installed by a different user. Is there a way for us to workaround this?

Unfortunately, out ability to run ad-hoc experiments is somewhat limited currently, so it might be a bit hard to debug this unless we know what exactly is going on.

**Comment by ZhouyihaiDing** [comment]
Pecl issue seems solved. But the new error looks like the same as `linux_x64_jessie` error, which is introduced by the alts PRs recently.

**Comment by ZhouyihaiDing** [comment]
I guess something added in [Makefile.template](https://github.com/grpc/grpc/blob/3287ceb06773ff3d7463a06c5f2dac742527135c/templates/Makefile.template#L224) should also be added into config.m4.template too. 
@jtattermusch Do you know the easy way to test a PR without merging it on Kokoro? Currently I found that I must merge a PR before Kokoro start testing it.

**Comment by ZhouyihaiDing** [comment]
I can reproduce it locally.
Seems this issue will block the next release of gRPC-PHP extension. I am working on solving it.

**Comment by jtattermusch** [comment]
After #14798`:
- macos distribtest now fails with: 
https://sponge.corp.google.com/target?id=46b07d99-8811-4773-ac86-fb398570af19&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

- the problem is that under linux, the PHP distribtest is now more broken than before: 
```
xargs sudo pecl install
xargs: sudo: No such file or directory
```
The reason is that `sudo` command doesn't exist in our docker images -   some adjustments of the `run_distrib_test.sh` scripts will be necessary.

**Comment by ZhouyihaiDing** [comment]
Thanks, @jtattermusch .
The new error in macOS is the same as in the #14761. I solved conflict in #14760, which should fix it. I can build successful locally in debian/ubuntu/macOS. Can we merge it to test if it works?

We need to revert #14798 . Sounds like we need to figure out how to solve the `Cannot install, php_dir for channel "pecl.php.net" is not writeable by the current user` issue without using `sudo`.
Currently what I can think to solve this issue are:

- Still use sudo, but something like `(xargs sudo pecl install || true) && (xargs pecl install || true)` to make it work on both environment.

- Change the pecl installation destination dir to somewhere writable on both environment. This will involve other changes like let PHP to load the extension from this directory.

**Comment by ZhouyihaiDing** [comment]
Hi @jtattermusch .Can I change [this line](https://github.com/grpc/grpc/blob/3d10d725b5c66179a990d3971a5227d55df7ce56/tools/run_tests/artifacts/distribtest_targets.py#L235) to pass an argument to it. Or create a new file like `run_distrib_test_macOS.sh` only for macOS?

**Comment by jtattermusch** [comment]
The original issue is now fixed. There is now a newly introduced breakage, but it's the same as linux.
