### ISSUE TITLE
grpc 1.8.0 not compatible with ruby 2.5 

### ISSUE THREAD

**Issue by taf2** [grpc/grpc#14772]
What version of gRPC and what language are you using?
1.8.0-x86-linux for ruby

What operating system (Linux, Windows, …) and version?
Linux running Arch Linux on kernel 4.14.11

What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.5
gcc 7.2.1

What did you do?
Trying to install the gem for ruby 2.5

What did you expect to see?
That grpc works with ruby 2.6

What did you see instead?
Gem::RuntimeRequirementNotMetError: grpc requires Ruby version < 2.6, >= 2.0. The current ruby version is 2.6.0preview1
An error occurred while installing grpc (1.10.0), and Bundler cannot continue.
Make sure that `gem install grpc -v '1.10.0'` succeeds before bundling.
Anything else we should know about your project / environment?
nothing special, just ruby 2.6.0preview1

**Comment by apolcyn** [comment]
you might want to try a source package, e.g., `gem fetch grpc --platform ruby`, followed by a `gem install <grpc package that was just fetched>`.

ruby 2.6 pre packages probably won't be supported for a while, unless there is a big push for doing so.

**Comment by taf2** [comment]
For me right now it looks like the issue is actually with Bundler... i was able to gem instlal grpc and compile it just fine in ruby 2.6 however, bundler always tries to download the platform specific gems... i'll try from git repo... Thanks!

**Comment by apolcyn** [comment]
closing since the 1.9.x releases and onwards are have platform specific packages that are pre-built for ruby 2.5 as well as the earlier ones, and there are no plans to backport ruby 2.5 support to older grpc releases. For ruby-2.6.pre packages, the suggestion is to use the grpc source packages and build the extension from source
