### ISSUE TITLE
cpp_linux_dbg_native_x64_gcc7.2: AsyncEnd2end/AsyncEnd2endTest.ReconnectChannel consistently timing out in portability suite (poll-cv)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14775]
Consistently failing for cpp_linux_dbg_native_x64_gcc7.2 portability suite,  all failures are for `poll-cv`

https://sponge.corp.google.com/invocation?id=0a8cce9d-34c8-4e6d-bc96-d73b544a864b
https://sponge.corp.google.com/invocation?id=0c3336e8-0f8d-475c-94c6-d591d4aca246
https://sponge.corp.google.com/invocation?id=149ce060-10bf-43d2-8755-8b6901947779

**Comment by jtattermusch** [comment]
local reproduction `tools/run_tests/run_tests.py -l c++ --compiler gcc7.2 --use_docker -r ReconnectChannel`

**Comment by yashykt** [comment]
Should be fixed as of #14959
