### ISSUE TITLE
Linux network interface disconnection hangs existing/new gRPC requests

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#14779]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 v1.9.0
 
### What operating system (Linux, Windows, …) and version?
 Linux - CentOS amd64, Ubuntu 17.04 amd64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Ubuntu - gcc v7.2
CentOS - gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
 
### What did you do?
 When a session is established from the Linux client, and the interface goes down (either by physically disconnecting the [virtual] network cable or calling `ifdown`), the client's socket doesn't close itself (still `ESTABLISHED` in `netstat`). The server-client response streams remain open (`Read()` keeps blocking) without failing, and the client keeps trying to send requests.
 
### What did you expect to see?
 On interface disconnection, the socket should be closed and all active requests should fail. In addition, new requests should not try to work and return error value immediately.
 
### What did you see instead?
 The client's socket doesn't close itself and the client keeps trying to send requests and wait for responses
 
### Anything else we should know about your project / environment?
 The server is written in C#. There is at least one server-to-client stream, with a `while`-loop in one of the client's threads, that reads messages from the stream. There are also client-to-server non-streaming RPC calls that are being called periodically

**Comment by srini100** [comment]
Is the hang forever or until TCP timeout? Socket is not closed just because interface went down. TCP will detect this with it's own timeout. If you want gRPC to timeout faster use keepalive setting on channel. I am not sure if this is available in C#. May be @jtattermusch  can answer.

**Comment by amitwaisel** [comment]
@srini100 The hang is forever (I've put a mechanism in place to kill the process after 10 minutes of hang, so it is definitely at least for 10 minutes).
The deadline for the gRPC call is forever - under the assumption that network disconnection will throw an error (other than a timeout).
The problematic client code is written in C++ (only the server is C#), and happens only on Linux subsystems.

**Comment by srini100** [comment]
I wouldn't underestimate the time it takes for TCP to timeout in stock linux. It can go on for several hours depending on various settings and activity. Have you tried TCP keepalive to isolate the issue to gRPC?

**Comment by amitwaisel** [comment]
We use stock version of CentOS 7.2 and Ubuntu 17.04. Both suffer from the same issue.
I agree the TCP timeout is a good candidate, but it seems weird we wait for 10 minutes without any timeout. What gRPC channel configuration/option should I use to check the TCP keepalive?

**Comment by amitwaisel** [comment]
@srini100 It appears that the TCP keepalive interval is set to 2+ hours on the Ubuntu and CentOS. So it might be the problem.

**Comment by srini100** [comment]
Try gRPC deadline and keepalive features. Let us know how easy or difficult you find it to use these features. Closing this issue.

**Comment by amitwaisel** [comment]
Thanks @srini100. We already use the `deadline` feature for the 10-minutes timeout. This feature is pretty much straightforward. We will look into the `keepalive` feature. Thanks!
