### ISSUE TITLE
Plans to Authenticode sign NuGet binaries?

### ISSUE THREAD

**Issue by chwarr** [grpc/grpc#14786]
Are there any plans to [Authenticode sign](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380259(v=vs.85).aspx#introduction_to_code_signing) the binaries included in the gRPC C# NuGet packages (and [also the packages themselves](https://github.com/NuGet/Home/wiki/Package-signing))? This would allow consumers of these packages and binaries to determine whether they were tampered with between the time that Google built them and they were downloaded.

I am away of some build and deployment systems that do not permit pre-compiled binaries that aren't signed. For these consumers to use gRPC, they currently need to build gRPC from scratch.

I also *believe* that there is a fast-path/cache for Authenticode binaries when Windows Defender is being used.

(Google, not the CNCF, is the entity that is currently producing the compiled C# NuGet packages, I believe.)

CC: @varada

**Comment by jtattermusch** [comment]
This is something we want to do eventually, but we have no clear timeline for this.
The actual signing of the nuget packages is easy: https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package, most of the work is the process around obtaining the certificate for signing the packages and making sure the signing can work in an automated fashion without compromising the key.

Once we do this, we should probably do the same for Google.Protobuf nugets and https://github.com/GoogleCloudPlatform/google-cloud-dotnet/ nugets.

**Comment by jtattermusch** [comment]
After some changes to the internal infrastructure, I've been able to put package signing in place.
Starting from v1.19.0-pre1 the nuget packages are signed and all the .dlls inside them are also authenticode signed.

https://www.nuget.org/packages/Grpc.Core/1.19.0-pre1
