### ISSUE TITLE
C++ async API does not provide a way to wake up an event loop

### ISSUE THREAD

**Issue by andrewrk** [grpc/grpc#14796]
In order for an API to integrate into a foreign event loop, it needs to provide a polling interface as well as a callback function which can be used to signal a mutex condition to wake up, or activate an eventfd, or put an item on a kqueue, etc.

`CompletionQueue` has `AsyncNext` which provides the polling interface, but it does not provide a way to wake up an event loop, or otherwise run a callback when the queue becomes non-empty.

Because of this missing feature gRPC is useless in an event-driven C++ codebase.

**Comment by vjpai** [comment]
Thanks for raising the issue. Unlike many other network packages, gRPC doesn't commit to doing any work in the async API except when an application thread has yielded time to gRPC by calling Next; there are no background threads doing the work of the RPC at other times.

So, I can give one immediately available suggestion: have your own thread (or threads) that calls Next in a loop and have that thread set condition variables, event FDs, or whatever other mechanism you need to interact with your main event loop.

For a longer term solution, I can share that we have some efforts underway to integrate gRPC core with external event managers. So far, the target has been for Python but it is likely that there will be efforts to enable C++ integrations some time in the next two quarters.

**Comment by andrewrk** [comment]
#20194
