### ISSUE TITLE
Provide bazel BUILD script for objective-c example

### ISSUE THREAD

**Issue by dmho418** [grpc/grpc#14791]
I noticed that there are some objective-c related bazel rules in the codebase (like [here](https://github.com/grpc/grpc/blob/master/grpc.bzl)). 
But it seems the objective-c [examples](https://github.com/grpc/grpc/tree/master/examples/objective-c), [documentation](https://github.com/grpc/grpc/blob/master/src/objective-c/README.md) and [source code](https://github.com/grpc/grpc/tree/master/src/objective-c) still heavily depend on CocoaPods and can't be built with bazel easily.
It would be great to have a bazel example so that it would be easier for people to integrate gRPC in obj-c projects.

**Comment by srini100** [comment]
Sorry, this is not supported currently. There is no future plan as such.
