### ISSUE TITLE
Timeout interop test definitions

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1480]
It came up in the wrapped languages meeting today that we should have timeout-behavior-verifying interop tests. When I look at https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md, I see "Timeout after expire (zhaoq)" and "Timeout but completed before expire (zhaoq)" under "TODO Tests". Does that indicate that test specifications are coming? Or should the task be reassigned?

**Comment by a11r** [comment]
I think this is one of the long tail tests that needs to be implemented but should not block beta. I have filed a separate issue to address all todos in the interopp testing doc before GA. https://github.com/grpc/grpc/issues/2724
