### ISSUE TITLE
Upgrade to pip 10

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#14814]
We're currently pinned to `pip` 9.0.1. It was a great release! It was the lead release for more than a year! But [9.0.3 is now out](https://pypi.python.org/pypi/pip/9.0.3); we should use that if we can (and if we can't we have problems).

**Comment by nathanielmanistaatgoogle** [comment]
Alternatively, [`pip` 10 is right around the corner...](https://mail.python.org/pipermail/distutils-sig/2018-March/032104.html)

**Comment by mehrdada** [comment]
I'd say let's wait for 10. Let's keep the infrastructure stable as is while a release branch is being cut and released.

**Comment by mehrdada** [comment]
Looks like pip 10 is out: https://blog.python.org/2018/04/pip-10-has-been-released.html
