### ISSUE TITLE
gRPC v1.10 not available in composer

### ISSUE THREAD

**Issue by vinceferro** [grpc/grpc#14826]
It looks like grpc/grpc v1.10 isn't available using composer yet. https://packagist.org/packages/grpc/grpc

Is there any issue if I install grpc v1.10 with pecl and use the supporting grpc v1.9 in composer?

Thanks

**Comment by ZhouyihaiDing** [comment]
It doesn't have any issue if you install the grpc-php extension v1.10 by pecl and install grpc-1.9.0 in composer, since there are no changes related to the composer installation grpc.

**Comment by stanley-cheung** [comment]
I just released the composer package grpc/grpc v1.10.0. There's not much change in this release.

**Comment by vinceferro** [comment]
Thanks @ZhouyihaiDing @stanley-cheung 👍
