### ISSUE TITLE
Python documentation builder is broken

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14829]
Python `docgen` script is broken and fails to regenerate Python documentation

**Comment by mehrdada** [comment]
Ideally the fix should try resolving https://github.com/grpc/grpc/issues/13340 as well

**Comment by mehrdada** [comment]
Closing in favor of #16894.

**Comment by lidizheng** [comment]
Fixing the document generation script of Python document generator to properly generate document
https://github.com/grpc/grpc/pull/17229
