### ISSUE TITLE
Allow to use system installed libcares with CMake

### ISSUE THREAD

**Issue by nolange** [grpc/grpc#14839]
Hello,

sofar you support third party libraries either as CMake Module or "in-tree". On debian testing, libcares is built using autotools and therefore not useable.
I would request a third method, using `find_library` and `find_path` to be able to painlessly build on eg. debian.

I made a crude hack (not using those methods) to get it working [here](https://github.com/nolange/deb_grpc_cmake/blob/master/debian/patches/fixbuild.patch).

**Comment by jtattermusch** [comment]
I can see that this could be useful but currently this is not a priority.
- current build works well, you only need to fetch the c-ares submodule (which I'd consider only a minor pain).
- supporting an extra source for c-ares library means more scenarios to test and it is non-trivial to add and maintain those tests
- our submodule is currently at c-ares 1.13, while e.g. in debian stretch is at 1.12 (there might be a regression if allowing a lower c-ares version and that's more things to tests once again).
- can you build on debian using make?

**Comment by KyleFromKitware** [comment]
This will involve writing a [find-module](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) for c-ares. I am working on this now.
