### ISSUE TITLE
set SOVERSION for libraries on the CMake build

### ISSUE THREAD

**Issue by nolange** [grpc/grpc#14840]
Please adopt the CMakeLists.txt (-template) to set the SOVERSION (VERSION ?) to fitting numbers.
I dont know teh scheme grpc uses for ABI compatibility so I could only guess in this [exemplary patch](https://github.com/nolange/deb_grpc_cmake/blob/master/debian/patches/sonames.patch)

**Comment by jtattermusch** [comment]
Let's leave this open.

**Comment by KyleFromKitware** [comment]
From the [libtool documentation](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html):

> ***Never*** try to set the interface numbers so that they correspond to the release number of your package. This is an abuse that only fosters misunderstanding of the purpose of library versions.

It might not be as simple as just setting `VERSION` to `${PACKAGE_VERSION}`. We might need to maintain a separate library version variable for this purpose.

**Comment by jtattermusch** [comment]
@KyleFromKitware 
I think this is only about setting the major version (="current" in libtool terminology) to mark breaking changes.
We already do this in our Makefiles:
https://github.com/grpc/grpc/blob/64fa171b8ba4b1ef0bf8f7163156c6a3b97ccece/templates/Makefile.template#L427
(if you try building grpc with make you'll see that libgrpc.so.X gets a version suffix and libgrpc++.so.Y also gets a version suffix).
