### ISSUE TITLE
Makefile gives "Argument list too long" error

### ISSUE THREAD

**Issue by vikasvashisht** [grpc/grpc#14844]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes we will like to have this addressed as part of the official git repo so as to avoid having the workaround patch on our repo. The workaround patch is attached below.

### What version of gRPC and what language are you using?
 1.10.0 C++
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 
 
### What did you do?
A build and install with the following command
INFO:osbuild:INSTALL: 'cd "/opt/go-agents/lib/go-agent-5/pipelines/novum-os/novum-os/linux/grpc/_build/v2/eve.arm/work/grpc-1.10.0" && GRPC_CROSS_AROPTS=rcs GRPC_CROSS_COMPILE=true HAS_PKG_CONFIG=false HAS_SYSTEM_PROTOBUF=true LD=/tandberg/system/toolchain/arm-a9neon_linux_4.1x-linux-gnueabihf/bin/arm-a9neon_linux_4.1x-linux-gnueabihf-g++ LDXX=/tandberg/system/toolchain/arm-a9neon_linux_4.1x-linux-gnueabihf/bin/arm-a9neon_linux_4.1x-linux-gnueabihf-g++ PATH=/opt/go-agents/lib/go-agent-5/pipelines/novum-os/novum-os/product/novum-eve/root/_build/v2/modexec/protobuf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin STRIP=: make --jobs=8 prefix=/opt/go-agents/lib/go-agent-5/pipelines/novum-os/novum-os/linux/grpc/_build/v2/eve.arm/root install'

It appears that the prefix is large and given the number of cxx headers we exceed the ARG_MAX for the shell command line length
 
### What did you expect to see?
Successful install 
 
### What did you see instead?
 Failure
.
.
.
[INSTALL] Installing libgrpc++_unsecure.so.1.10.0
ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make: execvp: /bin/sh: Argument list too long
Makefile:2680: recipe for target 'install-headers_cxx' failed
 
### Anything else we should know about your project / environment?
I think we need to use xargs or split the list of PUBLIC_HEADERS_CXX as it is a large list and with an increased prefix this exceeds the max arg len.

**Comment by vikasvashisht** [comment]
Attaching a workaround patch to break down the PUBLIC_HEADERS_CXX to smaller chunks to workaround the issue.
[cxx_arg_list_too_long.patch.txt](https://github.com/grpc/grpc/files/1856581/cxx_arg_list_too_long.patch.txt)

**Comment by nicolasnoble** [comment]
@vikasvashisht what is your operating system exactly ? More specifically, shell and version of make.

**Comment by vikasvashisht** [comment]
We are on a linux_x86_64 build machines cross compiling for Arm target.

**Comment by vikasvashisht** [comment]
vivashis@arajeeva-vm-lnx:~/novum-main$ /bin/bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

vivashis@arajeeva-vm-lnx:~/novum-main$ uname -a
Linux arajeeva-vm-lnx 4.4.0-89-generic #112~14.04.1-Ubuntu SMP Tue Aug 1 22:08:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
vivashis@arajeeva-vm-lnx:~/novum-main$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu

**Comment by teo** [comment]
I can reproduce this issue on CentOS 7 when passing a prefix path to `make install`.
```
$ make --version
GNU Make 4.1
Built for x86_64-redhat-linux-gnu
```
```
$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

**Comment by isbjorn** [comment]
@dberzano  thank you very much!
Your patch 0892788776d60d92a0cddcd22078779166b736db helps to build grpc-1.13.0

**Comment by dberzano** [comment]
Credits go to @vikasvashisht 🙂

**Comment by sreecha** [comment]
@vikasvashisht , can you submit your workaround as an official PR in this repo?

**Comment by sreecha** [comment]
Changing the priority since a workaround exists

**Comment by vikasvashisht** [comment]
@dberzano<https://github.com/dberzano>  already seems to have a version in his repo maybe he can push to main.

Thanks
Vikas

**Comment by azat** [comment]
>Attaching a workaround patch to break down the PUBLIC_HEADERS_CXX to smaller chunks to workaround the issue.

Maybe it will be better to use [`define`](https://stackoverflow.com/a/7040400/328260)?

**Comment by azat** [comment]
And FWIW:

[`make`](https://savannah.gnu.org/bugs/?18396) installs `RLIMIT_STACK` to `RLIM64_INFINITY` and because of this new threads will be created with default limit (2mb for `x86_64`, according to `pthread_create`(2)) instead of inheriting limit from the parent (which will be 8mb), and since after this [patch](https://lkml.org/lkml/2017/11/1/1040) linux limits length for argv to 25% of the stack (min), we have only 128K for the length of argv, which is not enough for that `install` target (on my machine it requires ~133KB)

**Comment by toanju** [comment]
I added another proposal to solve this in #17763

**Comment by jengelh** [comment]
The issue persists as of 1.19.1.

**Comment by dankegel** [comment]
I hit this just now on Ubuntu 19.04.

My commandline was 151250 bytes long.
DESTDIR was /home/ubuntu/src/yobuild/recipes/grpc/btmp/yobuild.tmp
and PREFIX was /opt/oblong/deps-64-13
which really don't seem that unreasonable.  I guess I could shorten that DESTDIR, but geez.

**Comment by javyer** [comment]
Thanks Vikasvashisht  for this patch, it works fine. 
But even applying it, I run into same error on some exotic builds, building into extra long paths... So I have push an other solution, using  "for loop", this patch works for me.
This patch also apply the fix on Makefile.template.

[cxx_arg_list_too_long_forloop.patch.txt](https://github.com/grpc/grpc/files/3329651/cxx_arg_list_too_long_forloop.patch.txt)

**Comment by javyer** [comment]
Thanks Vikasvashisht  for this patch, it works fine. 
But even applying it, I run into same error on some exotic builds, building into extra long paths... So I have push an other solution, using  "for loop".

[cxx_arg_list_too_long_forloop.patch.txt](https://github.com/grpc/grpc/files/3330008/cxx_arg_list_too_long_forloop.patch.txt)

**Comment by fedemengo** [comment]
> Thanks Vikasvashisht for this patch, it works fine.
> But even applying it, I run into same error on some exotic builds, building into extra long paths... So I have push an other solution, using "for loop".
> 
> [cxx_arg_list_too_long_forloop.patch.txt](https://github.com/grpc/grpc/files/3330008/cxx_arg_list_too_long_forloop.patch.txt)

Works great. Thanks @javyer
