### ISSUE TITLE
how to use unix://  with php extension 

### ISSUE THREAD

**Issue by wonewer** [grpc/grpc#14865]
how to use unix://  with php extension 
thank you

**Comment by ZhouyihaiDing** [comment]
The support for unix naming is documented [here](https://github.com/grpc/grpc/blob/ca38800d6236835d3907b8c29e6faeebe31ffeb7/src/core/ext/filters/client_channel/README.md) and recently [updated with details](https://github.com/grpc/grpc/pull/15618/files#diff-997a78687eb00e88a55e0832f134277fR35).

 With php extension, you can use unix naming when creating the `\Grpc\Channel` or the self defined client.
