### ISSUE TITLE
C# Grpc.Core.Tests seems very flaky

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1487]
I suspect it's hitting up against our five minute test limit.

Suggest breaking the test into smaller binaries.

**Comment by jtattermusch** [comment]
Did it start to be flaky just recently (= after #1445 was merged)?
It's most likely not the five-minute time limit, the Grpc.Core.Tests test usually passes in 20secs or so.

**Comment by ctiller** [comment]
I haven't sought out historical data, but I have seen it frequently the
last day or so.
