### ISSUE TITLE
grpc-objc: Add protocol for generated service classes so they can be instantiated generically

### ISSUE THREAD

**Issue by dcow** [grpc/grpc#14871]
In Swift you can instantiate generic types if they conform to a protocol describing their constructor interface. As far as I can tell, all generated services have the same constructors. For example:

```
func grpcServiceFactory<S: GRPCProtobufService>(address: String) -> S
{
    let service = S(host: address) // possible if GRPCProtobufService describes a protocol for init
    // configure service e.g. GrpcCall.setTlsParameters(..., ..., ..., address)
    return service
}
```

The call site looks like:

```
let service = grpcServiceFactory<HelloWorld>(address: "my.host:port")
```

Without this, call sites that need to configure services look like:

```
let service = HelloWorld(host: "my.host:port")
GrpcUtil.configureService(service)
// ...
```

The former is definitely nicer. Thoughts?

**Comment by muxi** [comment]
I feel that this is a bit overkill. How about some thing like:
```
func grpcServiceFactory(address: String, type: some_enum) -> GRPCProtoCall
{
  var service : GRPCProtoCall
  switch type {
    ...
  }
  service.setTlsParameters(...)
}
```

**Comment by dcow** [comment]
Why replicate the job of the type system?

**Comment by muxi** [comment]
I see. Thanks for explaining. I totally agree that doing switch in a factory is bad; was just meant to illustrate that returning `GRPCProtoService` might also be an option. But you are right that it needs a downcast which is not good. So that's right we can put generics here and use it in this way and thanks for stabbing into this.

I have not used generics in Swift before, but since every generated service class have a `initWithHost` initializer, can you just get rid of `: GRPCProtobufService` in `<...>` (i.e. just use `<S>`) and let compiler match the initializer? Or in other words, if `S` is a generated service class, it is guaranteed to have an `initWithHost` parameter. Then why does this code not work right now?

**Comment by dcow** [comment]
I got your point about how returning calls instead of services could be an option, but for my case I need something to manage the service (like a view controller) and like I said a call factory would just end up being a bunch of boilerplate with not much benefit. But it wasn't a bad idea.

> I have not used generics in Swift before, but since every generated service class have a initWithHost initializer, can you just get rid of : GRPCProtobufService in <...> (i.e. just use <S>) and let compiler match the initializer? Or in other words, if S is a generated service class, it is guaranteed to have an initWithHost parameter. Then why does this code not work right now?

Because `S` could be anything since it's generic. For the compiler to know it can use the `initWithHost` initializer you have to restrict `S` to conform to some protocol that requires an `initWithHost`.  So if you did `let foo: NotAService = grpcServiceFactory("addr")` the compiler wouldn't be able to guarantee it can initialize NotAService like NotAService("addr"). And so it has to fail to compile unless it allowed a runtime exception to occur when someone calls the serviceFactory with the wrong type. And if it did that it's pretty much back at square 1.

**Comment by muxi** [comment]
Huh I would say that sounds lame of Swift to me... C++ checks whether a method exists after the type-specific function is instantiated; no need to explicitly specify it. But anyway, the work looks like just adding a protocol in `GRPCProtoService.h` having method `- (void)initWithHost` and have all generated service stubs conform to that protocol?

**Comment by dcow** [comment]
> Huh I would say that sounds lame of Swift to me... C++ checks whether a method exists after the type-specific function is instantiated; no need to explicitly specify it.

C++ does this at runtime? What happens if you try to call a method that's not available on the type that the function is called under? Runtime exception? Or does the compiler check all usages of a generic function at compile time and infers any type bounds there? If so, this must only work for non-virtual methods?

> But anyway, the work looks like just adding a protocol in GRPCProtoService.h having method - (void)initWithHost and have all generated service stubs conform to that protocol?

Yep!

**Comment by muxi** [comment]
Not runtime; it is build time instantiation (by preprocessor I guess) of the function. If Swift behaves the same as C++, when you use `grpcServiceFactory<HelloWorld>` somewhere, `func grpcServiceFactory<S: GRPCProtobufService>(address: String) -> S` is instantiated to `grpcServiceFactory(address: String) -> HelloWorld` and the compiler can compile this instance successfully. If you instantiate with some class that does not have `init(host:)`, the compiler fails.

**Comment by dcow** [comment]
I see. Interesting. Yeah I've been reading more about function templates but it's a big topic. I forgot Templates were entirely compile time (and I've even used them before). Since c++ doesn't have a runtime, this is possible (and necessary). The difference is interesting. Swift _is_ a pretty young language (certainly lame at times), and it has to interoperate with obj-c, and it has a reflection runtime. So that would explain why the difference is necessary.

**Comment by muxi** [comment]
OK anyway. Feel free to make a PR any time (@ me if you do). Otherwise I'll find some time for this, likely some day next week.
