### ISSUE TITLE
Can't install grpc-1.10.0 for ruby

### ISSUE THREAD

**Issue by glucn** [grpc/grpc#14881]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes
 
### What version of gRPC and what language are you using?
grpc-1.10.0 for ruby
 
### What operating system (Linux, Windows, …) and version?
FreeBSD 10.3-RELEASE-p24
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.4.3,1 
ruby24-gems-2.6.14
gcc 6
gcc6-6.4.0_3
gmake-4.2.1_1
 
### What did you do?
Install grpc by running `gem install grpc -v '1.10.0'`

### What did you expect to see?
grpc can be installed 
 
### What did you see instead?
 
```
[CXX]     Compiling src/core/lib/gpr/arena.cc
mkdir -p `dirname /usr/local/lib/ruby/gems/2.4/gems/grpc-1.10.0/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/arena.o`
c++ -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -O2 -fPIC -I. -Iinclude -I/usr/local/lib/ruby/gems/2.4/gems/grpc-1.10.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\"   -Ithird_party/zlib -std=c++11   -fno-rtti -fno-exceptions -MMD -MF /usr/local/lib/ruby/gems/2.4/gems/grpc-1.10.0/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/arena.dep -c -o /usr/local/lib/ruby/gems/2.4/gems/grpc-1.10.0/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/arena.o src/core/lib/gpr/arena.cc
src/core/lib/gpr/arena.cc:86:42: error: static_cast from 'nullptr_t' to 'gpr_atm' (aka 'long') is not allowed
      if (!gpr_atm_rel_cas(&z->next_atm, static_cast<gpr_atm>(NULL),
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [Makefile:2650: /usr/local/lib/ruby/gems/2.4/gems/grpc-1.10.0/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/arena.o] Error 1
gmake: *** Waiting for unfinished jobs....
gmake: Leaving directory '/usr/local/lib/ruby/gems/2.4/gems/grpc-1.10.0'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)24

extconf failed, exit code 1
```

Full log please refer to:
[gem_make.log](https://github.com/grpc/grpc/files/1862718/gem_make.log)

### Anything else we should know about your project / environment?
I tried the approach mentioned in #14772 (run `gem fetch grpc --platform ruby` and `gem install <grpc package that was just fetched>`), and it gave me the same error.

**Comment by apolcyn** [comment]
We don't actively test support for this platform FYI (the PR that added support for it - https://github.com/grpc/grpc/pull/12923 - had a sort of <i>experimental</i> status), so I'm not certain how feasible it will be to fix this. 

But what compiler are you using here?

**Comment by madcated** [comment]
The default compiler should be clang, and the version of it is:
```
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.3
Thread model: posix
```

I also tried to run a bash like `CC=gcc gem install grpc -v '1.10.0'`, but still the same error.

**Comment by thomasbuesser** [comment]
any news here?

**Comment by apolcyn** [comment]
Closing as a dup of https://github.com/grpc/grpc/issues/15010, which appears resolved
