### ISSUE TITLE
How to implement username/password authentication. Python client, Java server

### ISSUE THREAD

**Issue by dshylov** [grpc/grpc#14909]
I'm trying to figure out how to authenticate with username/password when I create a connection and nothing found.
So, my questions:

How to create a server with username/password authentication on java server?
How should python client connect to it?

**Comment by ProLoDs** [comment]
Use some kind of transport security (e.g. TLS1.2) and use a normal login, combined with some kind of session cookie (similar to http). Use this session cookie for further requests. 
Or you could use some higher level service like oauth2 in some form. 

Either way I would not recommend a DIY solution.

**Comment by srini100** [comment]
Question seems to be answered. Closing.
