### ISSUE TITLE
Windows build error with CMake, VS2017

### ISSUE THREAD

**Issue by dzlier-gcp** [grpc/grpc#14918]
Trying to follow the build instructions at https://github.com/grpc/grpc/blob/master/INSTALL.md (cmake: Using Visual Studio 2015 or 2017 (can only build with OPENSSL_NO_ASM))., but getting the error when running the `cmake --build .` command.

The only difference is that I am using `cmake .. -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Release` since that is most recent. Below is the error message when I try to run the final command.

```
Build FAILED.

"C:\Users\dzlier\ws\grpc\.build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\tool\bssl.vcxproj" (default target) (17) ->
"C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto\crypto.vcxproj" (default target) (18) ->
"C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto\err\err.vcxproj" (default target) (34) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(17
1,5): error MSB6006: "cmd.exe" exited with code 2. [C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto\err\err
.vcxproj]


"C:\Users\dzlier\ws\grpc\.build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto\crypto_test.vcxproj" (default target) (63) ->
"C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto_test_data.vcxproj" (default target) (64) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(17
1,5): error MSB6006: "cmd.exe" exited with code 2. [C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto_test_da
ta.vcxproj]

    0 Warning(s)
    2 Error(s)
```

**Comment by jtattermusch** [comment]
This is odd because we have a continuous test for VS2017 and it is passing very consistently:
https://source.cloud.google.com/results/invocations/67f24a5e-8823-42b1-85af-a9c639f8ef8e/targets

What grpc version are you trying with?
Also, it looks like the cmake log you provided is incomplete and doesn't contain the actual errors?

**Comment by ara-ayvazyan** [comment]
> compile: version "go1.10" does not match go tool version "go1.9.2"

**Comment by jtattermusch** [comment]
As @ara-ayvazyan  has pointed out you seem to have the wrong version of go installed (please note that go is a requirement to build boringssl, not grpc itself, so we can't do much about it).
```
CustomBuild:
  Generating err_data.c
  # runtime/internal/sys
  compile: version "go1.10" does not match go tool version "go1.9.2"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 2. [C:\Users\dzlier\ws\grpc\.build\third_party\boringssl\crypto\err\err.vcxproj]
```
