### ISSUE TITLE
Upgrade node-pre-gyp to 0.9.0 for gppc-tools to resolve dependency on hoek

### ISSUE THREAD

**Issue by gcarling** [grpc/grpc#14916]
Not a bug report - would like to request that you update your dependency as currently you are depending on a version of hoek with a known security vulnerability.

Vulnerability report is here - https://hackerone.com/reports/310439

Based on the current list of dependencies [here](https://www.npmjs.com/package/node-pre-gyp) I believe that upgrading should fix this issue.

**Comment by gcarling** [comment]
Let me know if this is the wrong place to file this issue, not sure where the `grpc-tools` issues are specifically.

**Comment by RomanMinkin** [comment]
Just curious if there are any updates on thins one?

**Comment by murgatroid99** [comment]
The dependency has been updated in recent releases. See the latest version of the package.json: https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/package.json
