### ISSUE TITLE
portability suite: End2end/End2endTest.ReconnectChannel failing consistently with gcc7.2

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14910]
happening with `poll-cv`, several test cases always fail (and the tests seem to work fine with other pollers).

https://source.cloud.google.com/results/invocations/a44e30a8-58de-4766-b103-38ea472d5f83/targets/github%2Fgrpc%2Fcpp_linux_dbg_native_x64_gcc7.2/tests

https://source.cloud.google.com/results/invocations/ee72e2dc-8e73-44f1-9905-fbc5db2b152b/targets/github%2Fgrpc%2Fcpp_linux_dbg_native_x64_gcc7.2/tests

https://source.cloud.google.com/results/invocations/462a8331-2e80-4ea4-b727-b6caa05a92b8/targets/github%2Fgrpc%2Fcpp_linux_dbg_native_x64_gcc7.2/tests

**Comment by jtattermusch** [comment]
Local reproduction:
`tools/run_tests/run_tests.py -l c++ -c dbg --use_docker -r 'End2end.End2endTest.ReconnectChannel' --compiler gcc7.2`

**Comment by jtattermusch** [comment]
A more concise error message:
```
D0403 12:38:26.889790185   22848 connectivity_state.cc:164]  SET: 0x564696778e70 client_transport: READY --> TRANSIENT_FAILURE [got_goaway] error=0x7fe67c00b500 {"created":"@1522759106.889776427","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1083,"http2_error":0,"raw_bytes":"Server shutdown"}
D0403 12:38:26.889803424   22848 connectivity_state.cc:190]  NOTIFY: 0x564696778e70 client_transport: 0x56469675d2e0
D0403 12:38:26.889810024   22848 connectivity_state.cc:164]  SET: 0x7fe680005fa0 subchannel: READY --> TRANSIENT_FAILURE [reflect_child] error=0x7fe67c00b500 {"created":"@1522759106.889776427","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1083,"http2_error":0,"raw_bytes":"Server shutdown"}
D0403 12:38:26.889814061   22848 connectivity_state.cc:190]  NOTIFY: 0x7fe680005fa0 subchannel: 0x56469676d6a8
D0403 12:38:26.889851209   22848 connectivity_state.cc:164]  SET: 0x7fe680001560 pick_first: READY --> IDLE [selected_changed+reresolve] error=(nil) "No Error"
D0403 12:38:26.889858652   22848 connectivity_state.cc:190]  NOTIFY: 0x7fe680001560 pick_first: 0x56469675d478
D0403 12:38:26.889895526   22848 connectivity_state.cc:164]  SET: 0x5646967593a0 client_channel: READY --> IDLE [lb_changed] error=(nil) "No Error"
D0403 12:38:26.889905882   22848 connectivity_state.cc:116]  CONWATCH: 0x7fe680001560 pick_first: from IDLE [cur=IDLE] notify=0x56469671e438
D0403 12:38:26.889993124   22848 connectivity_state.cc:164]  SET: 0x564696778e70 client_transport: TRANSIENT_FAILURE --> SHUTDOWN [close_transport] error=0x7fe67c001c10 {"created":"@1522759106.889832205","description":"Delayed close due to in-progress write","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":589,"referenced_errors":[{"created":"@1522759106.889825025","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2419,"occurred_during_write":0,"referenced_errors":[{"created":"@1522759106.889823072","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.cc","file_line":156,"referenced_errors":[{"created":"@1522759106.889821637","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":423,"grpc_status":14,"target_address":"ipv4:127.0.0.1:5025"}]},{"created":"@1522759106.889776427","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1083,"http2_error":0,"raw_bytes":"Server shutdown"}]},{"created":"@1522759106.889847878","description":"OS Error","errno":32,"fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":573,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:127.0.0.1:5025"}]}
I0403 12:38:26.890029547   22848 end2end_test.cc:355]        status code: 14
test/cpp/end2end/end2end_test.cc:356: Failure
      Expected: response.message()
      Which is: ""
To be equal to: request.message()
      Which is: "Hello hello hello hello"
test/cpp/end2end/end2end_test.cc:357: Failure
```

**Comment by jtattermusch** [comment]
@yashykt,  @dgquintas  seems to be the owner for channel connectivity, but he's OOO. Can you please take a look?

**Comment by yashykt** [comment]
@jtattermusch My gcc compiler is 7.3.0 and I did not see this error. I tried using the docker command but that did not work.. I probably need some additional setup before I can run that.

**Comment by jtattermusch** [comment]
@yashykt  it's probably related to something about the particular docker image (or the particular linux distro used for the gcc7.2 test), not necessarily about gcc version (it if was about gcc version it would probably fail at build time rather than behave differently at runtime). But it would still be very useful to understand what the problem is and fix it.

**Comment by yashykt** [comment]
From what I understand, this is what is happening -
1) The client performs a RPC to the server which successfully completes. 
2) The server restarts.
3) The client goes to sleep for a duration long enough for the timer on the backup poller to fire.
4) In the normal case, the backup poller detects that the fd is shutdown and starts trying to create a new subchannel to the server. Once the server is up, the subchannel connects.
5) The client performs another RPC which SHOULD succeed in the normal case.

In the failing case, the backup poller does not detect that the fd is shutdown, and is not able to create a new subchannel. Subsequently when the client wakes up and tries to perform another RPC, it now realizes that the fd is shutdown and the RPC fails with a socket closed error.

**Comment by jtattermusch** [comment]
@yashykt  thanks for the analysis!
