### ISSUE TITLE
Assertion failure when destroying unstarted server after binding a port

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#14917]
If you create a server and add an http2 port, then try to destroy the server, you get the following assertion failure:

```
E0402 15:50:47.195617365   31663 server.cc:1247]             assertion failed: gpr_atm_acq_load(&server->shutdown_flag) || !server->listeners
```

This can be avoided by starting the server then shutting it down before destroying it. This seems be because a server that has not yet been started does not count as "shutdown".

I think this is a strange API usage requirement that should be reconsidered.

**Comment by mohamed-moanis** [comment]
Hi @murgatroid99 I looked into this issue as I though it will be straight forward for my GSoC preparation.

I added a simple testcase to reproduce the problem which is referenced in this issue. But what I can see is that when [these two lines ](https://github.com/mohamed-moanis/grpc/commit/f6e3b84633382217006852f913fdb86d2106581c#diff-fe3c48f047feb7518f23b75b5ab22128R114)are commented, the test passes.

In other words, the problem with this assertion is not that a server that has not yet started doesn't count as "shutdown", but in reality, the problem this assertion guard against, is that the attached ports to the server will be leaked if shutdown was not called on the server.  This test case will hit another assertion just after this one you highlight:
```c 
GPR_ASSERT(gpr_atm_acq_load(&server->shutdown_flag) || !server->listeners);
GPR_ASSERT(server->listeners_destroyed == num_listeners(server));
```

The added ports are owned by the server, and the shutdown is expected to close and clean the used resources. So to avoid this assertion, you don't need to start the server and then shut it down; all what you need is to call shutdown to free the attached ports which can be seen in [my commit](https://github.com/mohamed-moanis/grpc/commit/413e0e2adc1a59d8c6ab5381b52925c55b91fdb7) to fix the test case.

Please, let me know if I missed something and work can be done here - I am willing to work on this.

**Comment by srini100** [comment]
Duplicate of #10084. Closing this.
