### ISSUE TITLE
TIMEOUT: node:* interop tests on master and v1.11.x branches

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#14947]
cloud to cloud: https://source.cloud.google.com/results/invocations/5bf0be6b-47c6-452b-ba5c-00309b2687d0/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

same issue with cloud to prod: https://source.cloud.google.com/results/invocations/b9b26b3d-84a3-4433-913b-5ee7c2018b28/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

Noticed when backporting [a PR that should be unrelated](https://github.com/grpc/grpc/pull/14946)

Could be a kokoro issue related to the tests running on a non-master branch?

**Comment by jtattermusch** [comment]
This is not just on v1.11.x, it's also broken on master. The failures are pretty consistent
e.g.:
https://source.cloud.google.com/results/invocations/f1f7fe5c-d5e1-43d8-be9e-d64248ef7dfa/log

This might be the first build where it was broken:
https://source.cloud.google.com/results/invocations/cf8456a0-ad02-46c1-8757-f7154b491df2/log

**Comment by jtattermusch** [comment]
@murgatroid99  any progress here? This issue preventing us from getting any useful signal from interop tests on PRs, so we need to resolve ASAP.

**Comment by jtattermusch** [comment]
@murgatroid99  @nicolasnoble   100% of interop test runs have been failing for the last two weeks. Please post an update.

**Comment by murgatroid99** [comment]
I believe that @kpayson64 is working on a change that should fix this.

**Comment by kpayson64** [comment]
#15048 Should have fixed this.
