### ISSUE TITLE
TIMEOUT: on many cloud_to_prod and cloud_to_cloud tests

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#14969]
Many cloud_to_prod and cloud_to_cloud tests are timing out recently. 

https://source.cloud.google.com/results/invocations/5ba5eb0f-4a1f-4cb3-9f79-8ecc37f2aebb/log
In cloud_to_prod, they're all about `node:gateway_v4`.

https://source.cloud.google.com/results/invocations/92898aa4-8cf5-4214-b99b-abc1c6563c33/log
In cloud_to_cloud, both node and go are involved.

**Comment by jtattermusch** [comment]
Node interop issue also here: https://github.com/grpc/grpc/issues/14947

**Comment by jtattermusch** [comment]
@AspirinSJL , from the failure I'm seeing, it looks like that all the failures are related to Node, Go doesn't seem to be causing any trouble except the interop_to_prod failures mentioned in https://github.com/grpc/grpc/issues/10763 (which is a much older issue).

**Comment by jtattermusch** [comment]
This doesn't seem to be happening anymore?
