### ISSUE TITLE
Could not load file or assembly 'file: /// C: \MyProject\bin\ grpc_csharp_ext.x64.dll' or one of its dependencies. The module should contain an assembly manifest.

### ISSUE THREAD

**Issue by matheusborguete** [grpc/grpc#14972]
Hello!
I'm working with .Net Web Application, .Net Version = 4.5.
Versions: 
![2018-04-06_16-52-35](https://user-images.githubusercontent.com/15863101/38441415-00d8d978-39bb-11e8-94d7-a3f8809089d2.png)
observation: I've already tried to update all the packages and didn't work...

I want to use the Google Cloud Vision package but when I install the component Google Cloud Vision V1 from the NuGet it installs all the required dependences, then when I try to Build my solution, I get the following error: "Could not load file or assembly 'file: /// C: \MyProject\ bin\ grpc_csharp_ext.x64.dll' or one of its dependencies. The module should contain an assembly manifest."

### What operating system (Linux, Windows, …) and version?
 Windows 10 x64
 
Stack Trace:
[BadImageFormatException: Não foi possível carregar arquivo ou assembly 'file:///C: \MyProject\bin\grpc_csharp_ext.x64.dll' ou uma de suas dependências. O módulo deveria conter um manifesto de assembly.]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +225
   System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark) +172
   System.Reflection.Assembly.LoadFrom(String assemblyFile) +52
   WebActivator.ActivationManager.Run() +254

[InvalidOperationException: O método de inicialização Run anterior ao início do aplicativo do tipo WebActivator.ActivationManager emitiu uma exceção com a seguinte mensagem de erro: Não foi possível carregar arquivo ou assembly 'file:///C: \MyProject\bin\grpc_csharp_ext.x64.dll' ou uma de suas dependências. O módulo deveria conter um manifesto de assembly..]
   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +902
   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +169
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +173
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +172
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +912

[HttpException (0x80004005): O método de inicialização Run anterior ao início do aplicativo do tipo WebActivator.ActivationManager emitiu uma exceção com a seguinte mensagem de erro: Não foi possível carregar arquivo ou assembly 'file:///C: \MyProject\bin\grpc_csharp_ext.x64.dll' ou uma de suas dependências. O módulo deveria conter um manifesto de assembly..]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +534
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +718

Thank you in advance!

**Comment by matheusborguete** [comment]
Like I couldn't find any resolution for this problem I decided to create a new solution, only with my API and then I imported the API dll in my main solution.

**Comment by jtattermusch** [comment]
Is this basically a dupe of https://github.com/grpc/grpc/issues/12570?
