### ISSUE TITLE
Objective C example needed: How to call GRPC with ECDSA Eliptic curve cipher suite

### ISSUE THREAD

**Issue by neogeno** [grpc/grpc#14977]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
Pod install shows:
Installing !ProtoCompiler (3.5.0)
Installing !ProtoCompiler-gRPCPlugin (1.8.4)
Installing BoringSSL (9.2)
Installing Protobuf (3.5.0)
Installing gRPC (1.8.4)
Installing gRPC-Core (1.8.4)
Installing gRPC-ProtoRPC (1.8.4)
Installing gRPC-RxLibrary (1.8.4)
Installing lndtest (0.0.1)
Installing nanopb (0.3.8)

 
### What operating system (Linux, Windows, …) and version?
 MacOS 10.13
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Xcode
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
```
[GRPCCall useTestCertsPath:[[NSBundle mainBundle] pathForResource:@"tls" ofType:@"crt"]
                      testName:@"myapp.com"
                       forHost:kHostAddress
     ];
 client = [[Lightning alloc] initWithHost:addressWithPort];
GetInfoRequest *request = [GetInfoRequest message];
    GRPCProtoCall *call2 = [client RPCToGetInfoWithRequest:request handler:^(GetInfoResponse * _Nullable response, NSError * _Nullable error) {
        [self handleLNDResponse:response andError:error];

    }];
    [call2 start];

```
 
 
### What did you expect to see?
 Result from my RPC call
 
### What did you see instead?
 SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by muxi** [comment]
Can you confirm that only ECDSA fails?

**Comment by muxi** [comment]
Closing for no response.
