### ISSUE TITLE
```gem install grpc``` fails

### ISSUE THREAD

**Issue by carlisia** [grpc/grpc#1498]
Background:
Ruby version: 2.1.1
Successfully ran ```gem install google-protobuf -v 3.0.0.alpha.3.1.pre --pre``` prior
OS: Maverick

Entire error stack:
https://gist.github.com/carlisia/f61487e2e180af750a1d

Top of the error stack:
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0.8.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Building native extensions.  This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.
 
    /Users/carlisiacampos/.rubies/ruby-2.1.1/bin/ruby -r ./siteconf20150506-92443-cp9y.rb extconf.rb
checking for grpc_channel_destroy() in -lgrpc... yes
checking for grpc_channel_destroy() in -lgrpc... yes
checking for gpr_now() in -lgpr... yes
creating Makefile
 
make "DESTDIR=" clean
 
make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:128:13: warning: implicit declaration of function 'grpc_call_add_metadata_old' is invalid in C99 [-Wimplicit-function-declaration]
      err = grpc_call_add_metadata_old(call, md, NUM2UINT(flags));

**Comment by carlisia** [comment]
Any work around for this or any plan to update the gem? Thanks.

**Comment by carlisia** [comment]
This seems to be similar to https://github.com/grpc/grpc/issues/1156.

Additional info: I can build the ruby extension from source (mater) just fine on my machine.

**Comment by carlisia** [comment]
I see you updated the gem with the 0.6.1 release (https://rubygems.org/gems/grpc/versions) and it's building now. Thank you so much <3

**Comment by tbetbetbe** [comment]
Hi, sorry about that.
There was some delay in getting out https://rubygems.org/gems/grpc/versions/0.6.1 - it should have been out earlier.
