### ISSUE TITLE
GRPC 1.10.x crashes on windows but 1.9.1 is normal

### ISSUE THREAD

**Issue by yaohanlan** [grpc/grpc#14981]
I compile grpc 1.10.x release , but when I call the function grp::CreateChannel, It crashs.
Instead, I use the grpc version 1.9.1, it runs perfect.
language: c++
protobuf version: 3.5.1 release
operating system: win10 
compile tool : cmake with vs 2015 win64
bellow is the stack:
```
	ucrtbased.dll!00007ffffa28b56d()	未知
 	ucrtbased.dll!00007ffffa28eac5()	未知
 	fsclient.exe!operator delete(void * block) 行 21	C++
 	fsclient.exe!operator delete(void * block, unsigned __int64 __formal) 行 16	C++
 	fsclient.exe!grpc::internal::GrpcLibrary::`vector deleting destructor'(unsigned int)	未知
>	fsclient.exe!grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool call_grpc_init) 行 45	C++
 	[外部代码]	
 	fsclient.exe!bfs::netclient::GrpcNetClient::Init(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & host, int port) 行 448	C++
 	fsclient.exe!bfs::volume::VolumeMaker::MakeNetVolume(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & host, int port, int concur) 行 21	C++
 	fsclient.exe!bfs::volume::VolumeMaker::MakeNetVolume() 行 15	C++
 	fsclient.exe!bfs::client::BfsClientService::_initVolBase() 行 106	C++
```

Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
yes
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpc 1.10.x
c++
protobuf 3.5.1
 
### What operating system (Linux, Windows, …) and version?
 win10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 cmake with vs 2015 win64
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jtattermusch** [comment]
Please provide a minimal snippet that reproduces the issue - otherwise this is very hard to rootcause.
