### ISSUE TITLE
Unity3D package

### ISSUE THREAD

**Issue by Thaina** [grpc/grpc#15013]
I have seen working example here https://github.com/ahakits/unity-grpc-sample

Is it already just worked? Are there anyway we could ensure it perfectly work in everything?

If it already work perfectly fine could you please making package of it for unity?

I want to use grpc for firestore in unity

**Comment by jtattermusch** [comment]
Thanks for the link!

I believe we have enough pieces in place to enable basic operation, but Unity support is definitely still in experimental phase and it is not officially supported.
We are looking into improving the support and external contributions are very welcome.

Things that are currently missing:
- generating the `.unitypackage` (unity doesn't use NuGet packages).
- verify that loading the grpc_csharp_ext native extension works well on most platforms
- more testing
- fixes for potential bugs

**Comment by Thaina** [comment]
@jtattermusch I wish we could have `-experimental.unitypackage` so we would test it immediately and while nothing break we could just use it

**Comment by jsmouret** [comment]
I'm trying to piece together a way to build this package automatically using travis.
https://github.com/jsmouret/grpc-unity-package
Help needed for the iOS part :)

**Comment by jsmouret** [comment]
iOS support is in!

**Comment by jtattermusch** [comment]
@jsmouret   I wanted to try your package as it looks promising, but I'm getting 
`Unloading broken assembly Assets/Plugins/Grpc.Core/lib/net45/Grpc.Core.dll, this assembly can cause crashes in the runtime` error - this might be an instance of https://issuetracker.unity3d.com/issues/unity-fails-to-load-net-4-dot-6-assemblies-with-typeloadexception?page=1#comments.

Have you run into something similar? I'm using Unity for Mac 2018.2.0f2

**Comment by jsmouret** [comment]
I'm testing with the same Unity version. Are you testing with the example project in the repository?

**Comment by jtattermusch** [comment]
@jsmouret  I'm using my own example project after copying contents of the zip under my Assets directory.

**Comment by jtattermusch** [comment]
@jsmouret  I tried with your example project and the zip from  https://github.com/jsmouret/grpc-unity-package/releases/tag/0.0.6 and I'm still getting an error. Are you running on Mac as well?

**Comment by jsmouret** [comment]
Yes, you're right, I have the same error with 0.0.6 (which I just removed).
I have retried with 0.0.5 and it is working.
The first time you press the "Say Hello" button, it will complain about MonoPInvokeCallback (which you fixed), but the second time will be ok.

**Comment by jtattermusch** [comment]
@jsmouret   do you know what the problem was with 0.0.6?

**Comment by jsmouret** [comment]
Sorry for the late reply.
Yes, after trying a few combinations, System.Interactive.Async.3.2.0 was the culprit.

**Comment by drew-512** [comment]
Want to applaud your efforts here, gents!  Way to push on this and your efforts are deeply appreciated.

**Comment by jtattermusch** [comment]
This PR is adding automated builds of a unity package  https://github.com/grpc/grpc/pull/16208. The resulting "package" (inspired by https://github.com/jsmouret/grpc-unity-package) will still be experimental only, but it would be ready for testing.

**Comment by jtattermusch** [comment]
Experimental package for Unity is now available (and it is being built by our continuous CI automatically).

Instructions how to use:
https://github.com/grpc/grpc/tree/master/src/csharp/experimental#unity

Since it is experimental, we expect there can be issues using the package, so please try it and file an issue if it doesn't work for you.

I'm closing this issue now since the experimental package is in place, let's file new issues for items that come up.

**Comment by Thaina** [comment]
@jtattermusch Thank you very much

**Comment by fbernaly** [comment]
Thanks @jtattermusch for this package.

I am getting error when exporting this to Xcode

Undefined symbols for architecture arm64:
  "_deflateInit2_", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _unity_z_deflateInit2_, _il2cpp_z_deflateInit2_ )

do you have any clue?

I am setting my unity project to .net 4.x and unzipping the latest package from daily builds.

**Comment by jtattermusch** [comment]
@fbernaly  I assume the problem you are seeing is for Unity iOS?

**Comment by muroon** [comment]
@fbernaly

I also had a similar error, but it was solved in the following way.

In Xcode
1) Build Phases > Link Binary With Libraries > + 
2) Search "libz"
3) Choose libz.1.2.xx.tbd (ex libz.1.2.11.tbd)
4) Push Add Button

**Comment by fbernaly** [comment]
@gedw99: https://packages.grpc.io/archive/2018/09/07eecd8421314d62e8df33b14a33203864f91bee-fd8f1312-9873-4354-8a5d-613a05b12336/index.xml

**Comment by coolwust** [comment]
Does it support .net standard 2.0?

**Comment by fbernaly** [comment]
@coolwust : they say it is for .net4.x:

https://github.com/grpc/grpc/tree/master/src/csharp/experimental
