### ISSUE TITLE
Python client invoke Java Server using grpc and get an ERROR

### ISSUE THREAD

**Issue by wangyuan292** [grpc/grpc#15012]
I knew this is not issue, but I really need help. THX

Error message is:
`grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found: DemoGrpc.SendMailService/sendMail)>
`
I just using Java server and python client and send a grpc request from python to java server then I got an error like this.And it can works well for python client invoking python server, as well java...

**Comment by wangyuan292** [comment]
I got the reason

**Comment by YafimK** [comment]
Hey just got similar issue - could you please share?

**Comment by ShuyanAzaAzaFighting** [comment]
@wangyuan292 how did you fix that? Same issue here.

**Comment by ayazpasha2434** [comment]
I faced the same issue & managed to fix it by giving same name in `.proto` for both client & server.
**Fix**: Ensure that you have same package name in `.proto` file for both python client & JAVA server or vice-versa.
