### ISSUE TITLE
grpc-node sample code bug: the clients doesn't work.

### ISSUE THREAD

**Issue by GingerMoon** [grpc/grpc#15017]
Hi gurus, 
I am a newbee, so this bug is really confusing me a lot and I really appreciate your help!

The sample code of various clients doesn't work. 
These clients can't connect to the grpc-node server nor grpc-go server. 
However, grpc-go client is able to connect both grpc-node and grpc-go server.
(All of them, grpc-go, grpc-node, clients, servers) are just exactly the sample code without any change.)
The error is 
c:\NodejsWorkspace\grpc\examples\node\static_codegen\greeter_client.js:36
    console.log('Greeting:', response.getMessage());

The code snippet is:
client.sayHello(request, function(err, response) {
    console.log('Greeting:', response.getMessage());
  });

Actually the error the err is:
Error: 14 UNAVAILABLE: EOF

Environment:
windows 10 home edition
node --version v8.11.0
protoc --version libprotoc 3.5.1
npm --version 5.6.0

Reproduce steps:
git clone -b v1.10.x https://github.com/grpc/grpc
cd grpc
cd examples/node
npm install
open two PowerShells:
node .\static_codegen\greeter_server.js
node .\static_codegen\greeter_client.js

No output on server console.
The error on the client console:
node --inspect-brk=6676 static_codegen\greeter_client.js 
Debugger listening on ws://127.0.0.1:6676/4935f954-0679-4801-862b-1df6ce992428
Debugger attached.
c:\NodejsWorkspace\grpc\examples\node\static_codegen\greeter_client.js:36
    console.log('Greeting:', response.getMessage());
                                      ^

TypeError: Cannot read property 'getMessage' of undefined
    at c:\NodejsWorkspace\grpc\examples\node\static_codegen\greeter_client.js:36:39

**Comment by gcarling** [comment]
I'm having this issue only when I try to connect to a remote server. If I run a server locally and connect via localhost it works fine. However, if I ngrok my local port and try to connect to that, it doesn't work. Same if I deploy the server - I get this error 14 unavailable. My guess is its caused by the extra handshake TCP goes through since it's no longer on loopback.
