### ISSUE TITLE
obj-c: RPCs to link-local IPv6 addresses report "Connection lost." errors but actually succeed

### ISSUE THREAD

**Issue by dcow** [grpc/grpc#15014]
When using an ipv6 link-local address as the target for RPCs, the call completes immediately, reporting an error, because SCNetworkReachability reports the host as not reachable. If the host _is_ reachable, the call actually does execute, and the server will observe it, but the caller will never get the response because the call `finishWithError`'d. If you remove the explicit "preflight reachability" error handling, RPCs work as expected and the result is correctly reported instead of a connection issue.

```diff
diff --git a/.../GRPCClient/GRPCCall.m b/.../GRPCClient/GRPCCall.m
index b6309aad2..16f89f7cf 100644
--- a/Pods/gRPC/src/objective-c/GRPCClient/GRPCCall.m
+++ b/Pods/gRPC/src/objective-c/GRPCClient/GRPCCall.m
@@ -446,9 +446,11 @@ - (void)startCallWithWriteable:(id<GRXWriteable>)writeable {
   __weak typeof(self) weakSelf = self;
   void (^handler)(void) = ^{
     typeof(self) strongSelf = weakSelf;
-    [strongSelf finishWithError:[NSError errorWithDomain:kGRPCErrorDomain
-                                                    code:GRPCErrorCodeUnavailable
-                                                userInfo:@{ NSLocalizedDescriptionKey : @"Connectivity lost." }]];
+// SCNetworkReachability does not appear to work for link-local addresses on iOS even though it
+// works fine in a swift playground (both macOS and iOS).
+//    [strongSelf finishWithError:[NSError errorWithDomain:kGRPCErrorDomain
+//                                                    code:GRPCErrorCodeUnavailable
+//                                                userInfo:@{ NSLocalizedDescriptionKey : @"Connectivity lost." }]];
   };
   [_connectivityMonitor handleLossWithHandler:handler
                       wifiStatusChangeHandler:nil];
```

Interestingly, SCNetworkReachability works fine with link-local addresses in a swift playground (targeting both macOS and iOS, iOS shown below). But the same code written in objective-c and run in the simulator fails to report link-local as reachable.

![screen shot 2018-04-10 at 8 35 05 pm](https://user-images.githubusercontent.com/547926/38596032-1b45c04a-3d04-11e8-908e-10e3cc1559c8.png)

[Apple's guidance](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW25) (and arguably general wisdom) suggests not preforming "reachability preflight". There are a few reasons for this, but mainly it's impossible to know if a host will be reachable in the future, so the only way to know for certain is to try and establish the connection and execute the request. Apple's guidance suggests only using SCNetworkReachability in the event that prior connections have failed and you would like to ascertain diagnostic information about network configuration. 

The objective-c layer does make use of SCNetworkReachability in order to flush channels on connectivity change events, which does seem like an arguably appropriate use. But I also wonder if there's a less destructive way to gracefully handle interface transition events such as simply creating a new channel if the current one becomes closed (e.g. the user disabled wifi or cell radios). This also allows the system to gracefully transition connections across interfaces since connection tuples generally don't carry interface information (and if they do in the case of ipv6 link-locals, flushing the channel won't do anything anyway since the target host would not be reachable via the new interface). In any event, connectivity errors should probably only be reported if RPCs actually fail due to loss of connectivity.

> Note: you cannot generally use the objective-c code with link local addresses yet. Use the patch in the referenced PR on https://github.com/grpc/grpc/issues/14369.

**Comment by muxi** [comment]
Thanks for pointing this out. For this particular issue I'll try it out. For reachability, we are not doing any preflight (or I do not think that is preflight). We only care about network transition. The reason why we proactively destroy channels are because the BSD sockets that Apple provides does not error out during some cases of the network transition activities. Destroying channels is a mitigation of this problem to initiate channel destroy from the top in these cases. Once we integrates CFStream it is likely we can get rid of this part of code.

**Comment by muxi** [comment]
1.11.0-pre2 is published if you want to try that :)

**Comment by dcow** [comment]
@muxi your changes to connectivity monitor resolve this!
