### ISSUE TITLE
ServiceDescriptor not included in gRPC service generated C++

### ISSUE THREAD

**Issue by okaymaged** [grpc/grpc#15031]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 v1.10.0
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04.4 LTS
 
### What did you do?
With the input file test.proto

```
syntax = "proto3";

package okaymaged;

service SearchService {
    rpc Search (SearchRequest) returns (SearchResult) {}
}

message SearchRequest {
    string query = 1;
}

message SearchResult {
    int32 num_results = 1;
}
```
 
I ran the command `protoc --plugin=protoc-gen-grpc=grpc_cpp_plugin ./test.proto --cpp_out=./out --grpc_out=./out`

### What did you expect to see?
The generated code to have a static descriptor method as described [here](https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#interface), or an alternative way to access the ServiceDescriptor
 
### What did you see instead?
The generated `test.grpc.pb.h` file has no static descriptor method.

**Comment by okaymaged** [comment]
Setting the option `option cc_generic_services = true;` causes the error: 
```
cpp grpc proto compiler plugin does not work with generic services. To generate cpp grpc APIs, please set "cc_generic_service = false".
```

**Comment by yang-g** [comment]
I think grpc does not need that. Are you working on something related to code generation?

**Comment by okaymaged** [comment]
I'm working on a reverse proxy server for gRPC services. Ideally, the server will know the RPC available for each service, including it's request and response type, without needing each RPC to be manually specified. This is possible using ServiceDescriptors. Is another approach possible?

**Comment by yang-g** [comment]
I assume your proxy server will talk to some real grpc servers exporting
the services? If that is the case, maybe you want to take a look at the
reflection service?
https://github.com/grpc/grpc/blob/master/doc/server-reflection.md
I am not sure whether you will have everything you need but maybe you can.

**Comment by okaymaged** [comment]
This is not ideal as it requires the proxy server to connect with all grpc servers for it to know which methods it can expose. Is there a solution that relies only on the compiled service protobufs?

**Comment by nicolasnoble** [comment]
Unfortunately, you'd need to write your own protoc plugin for this.
