### ISSUE TITLE
Your code is in a US army video

### ISSUE THREAD

**Issue by digininja** [grpc/grpc#15038]
Just thought you'd like to know that the tail end of this file is used in a video by the US Army:

https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_server.cc

https://youtu.be/RoAsyraektY?t=1m18s

**Comment by digininja** [comment]
It is also scrolled in at the start of the video

**Comment by jtattermusch** [comment]
Interesting, thanks for sharing. I'll close this issue now though :-).

https://github.com/grpc/grpc/blob/master/.github/ISSUE_TEMPLATE.md#should-this-be-an-issue-in-the-grpc-issue-tracker
