### ISSUE TITLE
Mapping between generic gRPC error codes and PHP error statuses. 

### ISSUE THREAD

**Issue by clarencejychan** [grpc/grpc#15040]
### Should this be an issue in the gRPC issue tracker?
yes
 
### What version of gRPC and what language are you using?
 gRPC v1.10.0, PHP
 
### What operating system (Linux, Windows, …) and version?
 Mac OS Seirra
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 PHP  7
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Making a unary call 
`$hcApi->Ready(new \Google\Protobuf\GPBEmpty(), [], ["timeout" => 1000])->wait();` 
returns responses 
![image](https://user-images.githubusercontent.com/14989024/38694738-3fae5ff0-3e3f-11e8-859b-deae70abd354.png)

### What did you expect to see?
 Expected to see error messaging more similar to https://grpc.io/docs/guides/error.html. The status code returning `4` is especially not very helpful. 
 
### What did you see instead?
 
See image above
 
### Anything else we should know about your project / environment?
Nothing of great importance.

**Comment by ZhouyihaiDing** [comment]
We can't change the returned value `$status` from code to string directly because it will block uses who are using it. Thus we provide some helper method map those enum value to the string as in #15652.
