### ISSUE TITLE
Why gRPC decodes pb models in main thread (Objective-C)?

### ISSUE THREAD

**Issue by wangjufan** [grpc/grpc#15056]
Decoding in main thread is far away from good design .  
After checks the relationships among GRPCCall, GRXConcurrentWriteable and GRPCCompletionQueue , we think that we just can dispatch callbacks in ProtoRPC  to non main thread , use non-main serial queue or nil (if we don't cancel the rpc from user) in GRXConcurrentWriteable . 
 In my project , i just remove the queue in GRXConcurrentWriteable to decode pb model in the single thread use in GRPCCompletionQueue .  It's just work fine for me .

In my opinion, making use of a serial queue is unnecessary here and somewhat override the system .
Firstly  , the pb models we use are small enough to decode in the the single receiving thread in GRPCCompletionQueue , which can dramatically reduce the system overriding  .
Secondly,  we shouldn't  decode pb models in main thread .
Lastly , making use of some synchronization mechanisms is better than dispatch when cancel is needed  . Even this can not absolutely keep message from sending to main thread , it's still better than decoding on the main thread i believe .  With serial queue , only messages dispatched to main thread before suspend will interrupt the cancel semantics which happens just during the suspend calling process. That's a technique delay which related to semantics too .

Can you help me with this question , why main queue ? 
 Is there any other reasons or series problem i haven't see there ?

**Comment by muxi** [comment]
Does [`setResponseDispatchQueue`](https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/GRPCCall.h#L260) work for you?

**Comment by wangjufan** [comment]
Yes , of course . 
Just dispatch callbacks to main queue in ProtoRPC  
And don't call the cancel in main thread . 
  
      id parsed = [responseClass parseFromData:value error:&error];
        dispatch_async(dispatch_get_main_queue(), ^{
            if (parsed) {
                [responsesWriteable writeValue:parsed];
            } else {
                [weakSelf finishWithError:ErrorForBadProto(value, responseClass, error)];
            }
        });
    } completionHandler:^(NSError *errorOrNil) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [responsesWriteable writesFinishedWithError:errorOrNil];
        });
    }];

**Comment by muxi** [comment]
Sorry I did not quite understand the previous post. Is the code block what you suggests or what you see? The [file in current master branch]((https://github.com/grpc/grpc/blob/082ddc563ea71a6b7a700070ec60095bfb65d88f/src/objective-c/ProtoRPC/ProtoRPC.m#L85)) looks different.

**Comment by wangjufan** [comment]
Just a suggest used in our projects . Performance tests tell us it is the better choice. 
Additionally, i have resolved the cancel in main thread problem . I will submit it in the coming week .
