### ISSUE TITLE
Compilation issues on SLES11SP3

### ISSUE THREAD

**Issue by CJLove** [grpc/grpc#15079]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes, would like to have this handled upstream.  Workarounds exist:

For SLES 11 SP3 (older glibc):
```
sed -i 's/#define GPR_LINUX_PTHREAD_NAME 1//g' include/grpc/impl/codegen/port_platform.h
```
(this could possibly be conditional on __GLIBC_MINOR__ > 11)

*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 grpc 1.11.0 C++
 
### What operating system (Linux, Windows, …) and version?
 Linux - SLES 11 SP3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
glibc on SLES 11 SP3 (2.11.3) doesn't support pthread_setname_np()
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

 
### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by nicolasnoble** [comment]
@CJLove what is the glibc major exactly in this case ? Would `#if __GLIBC_PREREQ(2, 11)` work ? See https://github.com/grpc/grpc/pull/15389

**Comment by CJLove** [comment]
glibc 2.11.3 on SLES11 SP3 doesn't have pthread_setname_np(), so if I changed your diff as follows then it does compile:
```
diff --git a/include/grpc/impl/codegen/port_platform.h b/include/grpc/impl/codegen/port_platform.h
index 819d17ce2a..c9f0f965d7 100644
--- a/include/grpc/impl/codegen/port_platform.h
+++ b/include/grpc/impl/codegen/port_platform.h
@@ -173,7 +173,11 @@
 #endif /* _LP64 */
 #ifdef __GLIBC__
 #define GPR_POSIX_CRASH_HANDLER 1
+#ifdef __GLIBC_PREREQ
+#if __GLIBC_PREREQ(2, 12)
 #define GPR_LINUX_PTHREAD_NAME 1
+#endif
+#endif
 #else /* musl libc */
 #define GPR_MUSL_LIBC_COMPAT 1
 #endif
```
