### ISSUE TITLE
Java support?

### ISSUE THREAD

**Issue by 4ntoine** [grpc/grpc#1507]
I have java server-side and c++ clients. Can i use gRPC in this scenario?

**Comment by jayantkolhe** [comment]
yes. you can.

**Comment by 4ntoine** [comment]
Can i have a brief tutorial on this?

Having .proto with messages and server definition:
1. How to generate C++ server RPC available on port N
2. How to generate Java client to send request to host H port N

**Comment by nicolasnoble** [comment]
There's a few examples over there: https://github.com/grpc/grpc-common

**Comment by tbetbetbe** [comment]
FYI: gRPC Java is in a different repo: https://github.com/grpc-java
