### ISSUE TITLE
Helloworld C++ server crashes in VS2010

### ISSUE THREAD

**Issue by git-torrent** [grpc/grpc#1508]
In Visual Studio 2010 the following method crashes:

```
ThreadPool::ThreadPool(int num_threads) : shutdown_(false) {
  for (int i = 0; i < num_threads; i++) {
	 threads_.push_back( grpc::thread(&ThreadPool::ThreadFunc, this) );
  }
}
```
Since in Visual Studio 2010 there is no std::thread the custom thread is used (thd_no_cxx11.h).
The thread crashes in destruction:
```
   ~thread() {
    if (!joined_) {  
	  std::terminate();  // crashes here
	}
    delete func_;   // even if it wouldn't crash before it would crash probably here
  }
```
It seems that in Visual Studio 2010 default copy constructor is used that copies the object into the std::vector and the original object's destructor is called that ends in a std::terminate.

**Comment by ctiller** [comment]
Visual Studio 2010 is not supported.

**Comment by JulienSiems** [comment]
Are there any plans to support it again?

**Comment by ctiller** [comment]
VS2010 is old enough that we won't be, sorry.

Typically we'll support compilers going back five years, though 2013 is
quirky enough that we won't officially support that either.
