### ISSUE TITLE
An minor compile error occurred after building the generated solution via VS2017.

### ISSUE THREAD

**Issue by GingerMoon** [grpc/grpc#15083]
Please answer these questions before submitting your issue. 

### What version of gRPC and what language are you using?
 https://github.com/grpc/grpc master
C++ VS2017
 
### What operating system (Linux, Windows, …) and version?
 Windows10 Home
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 VS2017
 
### What did you do?
I did the operations according to the document  https://github.com/grpc/grpc/blob/v1.11.x/INSTALL.md
(except that I using VS2017 instead for the step: cmake .. -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Release)
And then built the generated grpc.sln in VS2017, an compile error occurred 

Error	C2001	newline in constant	crypto_test_data	c:\cppworkspace\grpc\.build\third_party\boringssl\crypto_test_data.cc	2612	

 After I fixed the compile error by inserting the " before , at the line, I built the solution again without any compile error.

### What did you expect to see?
No compile error should occur.

**Comment by topillar** [comment]
By default, Visual Studio detects a byte-order mark to determine if the source file is in an encoded Unicode format, for example, UTF-16 or UTF-8. If no byte-order mark is found, it assumes the source file is encoded using the current user code page, unless you have specified a code page by using /utf-8 or the /source-charset option. Visual Studio allows you to save your C++ source code by using any of several character encodings. For information about source and execution character sets, see Character Sets in the language documentation.

but, how to add  "/source-charset:utf-8" option?

**Comment by topillar** [comment]
fix：
1. Download zip version of boringssl-chromium-stable branch from https://github.com/google/boringssl/tree/chromium-stable
 
2. Unzip the tarball: boringssl-chromium-stable.zip and rename the folder from "boringssl-chromium-stable" to "boringssl"

3.  Delete "boringssl" folder from  "gRPC\grpc\third_party", use the new unzipped "boringssl" instead.

4. build 


I tried this way, it works. so I guess the "boringssl" submodule should be updated to latest commit.

**Comment by nicolasnoble** [comment]
We've updated the submodules now. Please re-open a new issue if it's still an issue.
