### ISSUE TITLE
Use Canonical Proto for channelz

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#15081]
Migrate from using https://github.com/grpc/grpc/blob/master/src/proto/grpc/channelz/channelz.proto to https://github.com/grpc/grpc-proto/blob/master/grpc/channelz/channelz.proto

Might be a bit of a headache for google3. Possible middle step option would be to add a linter to ensure that the version this repo stays in line with the version in grpc-proto

cc @carl-mastrangelo

**Comment by ncteisen** [comment]
Needed for #15340

**Comment by carl-mastrangelo** [comment]
@ncteisen I am working on this for Go and Java at the moment, but haven't had a chance to extensively look at this for C.  Recommendations about how to move forward would be great.

**Comment by ncteisen** [comment]
I think the best solution for now is
1) submodule the grpc-proto repo in gRPC
2) write a python sanity check to ensure that the existing protos are textually _identical_ to the protos in grpc-proto

This seems like the best of both worlds. We have a mechanism for staying up to date, and we also have a mechanism for making atomic changes to these protos in c core.

If a proto changes in grpc-protos, it will probably need some code changes in core. This way, those changes can go in as we bump the grpc-proto submodule, and we never have to go through a 30 minute period of breaking sanity

**Comment by carl-mastrangelo** [comment]
@ncteisen for submoduling, @nicolasnoble said he wanted the generated code to still live in the repo.   I think this adds another level of syncing, since grpc_proto needs to be kept in sync with third_party submodules, and the submodule proto kept in sync with generated code.  Right now I think most of the code in core expects the protos to live in src/proto.



Bazel makes the second sync easy, but I don't know about make.

**Comment by ncteisen** [comment]
Core support for channelz will never depend on the generated code directly. Right now, the code is generated on the fly, for test code, to ensure that the JSON exported by core is correctly formatted.

Eventually, once support for channelz is added to C++, then we may need the generated code. But I think my proposal still works for that. 

I still think that the protos should reside in src/proto. The purpose of the submodule is only so we can have a linter that diffs src/proto from third_pary/grpc-proto.
