### ISSUE TITLE
Empty frame followed by valid frame throws "No value received for unary call"

### ISSUE THREAD

**Issue by anilutcs** [grpc/grpc#15091]
Hi,

I am using 0.11.0 grpc client/server and implemented a http2 proxy based on jetty.

Here is the call flow:
(java grpc client ---http2--> jetty http proxy ----http2--> grpc-server ---http2--> jetty http proxy ---> java grpc client) 

I am seeing the following on client side:

**Logging on the java-grpc client (Netty Client):**
1. FINE: [id: 0x25543c09, L:/127.0.0.1:62219 - R:localhost/127.0.0.1:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=22 bytes=00003a012400000001000000000f885f8b1d75d0620d

2. FINE: [id: 0x25543c09, L:/127.0.0.1:62219 - R:localhost/127.0.0.1:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=0 bytes=

3. FINE: [id: 0x25543c09, L:/127.0.0.1:62219 - R:localhost/127.0.0.1:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true

4. WARNING: RPC failed: Status{code=INTERNAL, description=No value received for unary call, cause=null}

Is this a bug as a valid data frame is sent (line 1 above) and the next empty frame (line 2) ?

I have followed this thread https://github.com/grpc/grpc/issues/8010 and the above scenario looks different.

Thanks,
Anil

**Comment by anilutcs** [comment]
@ejona86 I know you have looked into a similar issue in the past, let me know if this is a something on the grpc client.

**Comment by ejona86** [comment]
Were there any more DATA frames before the one in (1)? If not, then that'd mean there should have been a 3,801,380 byte message. So maybe the message was truncated and then we produced the wrong error message?

(2) is interesting, because it does nothing. Typically we see that for `endStream=true`.

**Comment by anilutcs** [comment]
@ejona86 
(1) No there were not, **here is the complete log:**

```FINE: [id: 0x6dacdff5, L:/127.0.0.1:52939 - R:localhost/127.0.0.1:443] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=16 bytes=000000000b0a096c6f63616c686f7374
FINE: [id: 0x6dacdff5, L:/127.0.0.1:52939 - R:localhost/127.0.0.1:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, date: Wed, 18 Apr 2018 00:00:19 GMT, strict-transport-security: max-age=15552000, intuit_tid: d3414242-c8c1-e201-3d49-d3adb704750f, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false
FINE: [id: 0x6dacdff5, L:/127.0.0.1:52939 - R:localhost/127.0.0.1:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=22 bytes=00001600000000000100000000110a0f48656c6c6f20
FINE: [id: 0x6dacdff5, L:/127.0.0.1:52939 - R:localhost/127.0.0.1:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=0 bytes=
FINE: [id: 0x6dacdff5, L:/127.0.0.1:52939 - R:localhost/127.0.0.1:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true```

(2) I do not see that empty frame when I call the java grpc server directly from the client. Below is the trace without jetty http2 proxy in between:

```
FINE: [id: 0xf4d87293, L:/127.0.0.1:53789 - R:localhost/127.0.0.1:50051] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:50051, :path: /helloworld.Greeter/SayHello, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.11.0, grpc-accept-encoding: gzip, grpc-trace-bin: ] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
FINE: [id: 0xf4d87293, L:/127.0.0.1:53789 - R:localhost/127.0.0.1:50051] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=12 bytes=00000000070a05776f726c64
FINE: [id: 0xf4d87293, L:/127.0.0.1:53789 - R:localhost/127.0.0.1:50051] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
FINE: [id: 0xf4d87293, L:/127.0.0.1:53789 - R:localhost/127.0.0.1:50051] INBOUND DATA: streamId=3 padding=0 endStream=false length=18 bytes=000000000d0a0b48656c6c6f20776f726c64
FINE: [id: 0xf4d87293, L:/127.0.0.1:53789 - R:localhost/127.0.0.1:50051] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
```

**Comment by anilutcs** [comment]
@ejona86 
```If not, then that'd mean there should have been a 3,801,380 byte message.```
Where is the number `3,801,380` coming from?

**Comment by ejona86** [comment]
I can't make sense of the "with proxy" response. The "without proxy" makes sense to me.

I got that number by decoding the length-prefixed-message (see [PROTOCOL-HTTP2.md](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)). The hex `00003a0124` is the 5 byte header. The first byte says "no compression". The remaining is the length of the message 0x003a0124 (as network byte order; little endian) is 3,801,380.

I also don't see any Content-Encoding response header that could morph the response, like gzipping it.

**Comment by anilutcs** [comment]
@ejona86 
Thanks for the pointer about the length encoding.

`with proxy`----> java grpc client call to java grpc server over a http2 proxy
`with out proxy`   ---->  java-grpc client call to java-grpc server

**Comment by anilutcs** [comment]
@ejona86 Please close this, the data frame wasn't constructed well.
