### ISSUE TITLE
Grpc.Core Nuget package is missing netstandard1.5 for build directory.

### ISSUE THREAD

**Issue by imback82** [grpc/grpc#15095]
Grpc.Core Nuget is missing netstandard1.5 for the "build" directory and a corresponding targets file. Consequently, the native dll is not copied to the output directory if C# project is targeting .net core. Is there a workaround?

**Comment by jtattermusch** [comment]
Copy pasting the explanation give offline:

I believe things are working as expected. Copying of the native libraries under netstandard1.5 is handled by dotnet directly (the targets file build\net45\Grpc.Core.targets  is only needed for .NET45 as this version doesn't have support for native libraries in nugets) and libraries under runtimes\*\native should be automatically made available.
We have some continuous tests that are verifying this is the case and they are passing consistently, do you have any evidence in the contrary? If so, please file an issue at https://github.com/grpc/grpc/issues and we can follow up from there.
