### ISSUE TITLE
BoringSSL: non-modular header inttypes.h

### ISSUE THREAD

**Issue by dcow** [grpc/grpc#15094]
@muxi I notice you maintain the BoringSSL podspec. I updated today from 9.1 to 10.0[.2]. My builds failed because a non-modular header is exposed. I've configured my modules to allow non-modular headers as a temporary fix, but I wanted to bring this to your attention since I didn't have this issue with 9.1. I don't believe using just gRPC exhibits this issue, but I use BoringSSL for some certificate creation so I'm using the ASN1 and BN types (and thus BoringSSL) directly in parts of my project.

**Comment by muxi** [comment]
This looks like a duplicate of #14456, which was fixed in v1.11.0. But #14456's problem was in grpc module, not boringssl. If you can try v1.11.0 and/or post the line where it fails that would be very helpful.

**Comment by dcow** [comment]
@muxi I did see #14456. I am using `1.11` now. My issue is with a project that includes BoringSSL directly. I have

```
#import <openssl/evp.h>
```
in my code which I believe is what causes the issue. I'm reporting here because I didn't have this issue when using 9.1.

Thinking about this more, I wonder if xcode 9.3 no treats non-modular includes as errors instead of warnings by default. That would also explain the issue.

**Comment by dcow** [comment]
I just built an old revision. xcode 9.3 is not the issue.

**Comment by muxi** [comment]
That still does not make much sense. Even if you import `<openssl/evp.h>` I still do not see where `inttypes.h` is imported. Could you post the related build log?

**Comment by dcow** [comment]
```
While building module 'openssl' imported from file.m:5:
In file included from <module-includes>:1:
In file included from .../Build/Products/Debug-iphonesimulator/BoringSSL/openssl.framework/Headers/umbrella.h:1:
In file included from .../Build/Products/Debug-iphonesimulator/BoringSSL/openssl.framework/Headers/ssl.h:149:
In file included from .../Build/Products/Debug-iphonesimulator/BoringSSL/openssl.framework/Headers/pem.h:66:
In file included from .../Build/Products/Debug-iphonesimulator/BoringSSL/openssl.framework/Headers/x509.h:70:
In file included from .../Build/Products/Debug-iphonesimulator/BoringSSL/openssl.framework/Headers/asn1.h:68:
.../Build/Products/Debug-iphonesimulator/BoringSSL/openssl.framework/Headers/bn.h:129:10: error: include of non-modular header inside framework module 'openssl.bn': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/inttypes.h' [-Werror,-Wnon-modular-include-in-framework-module]
#include <inttypes.h>  // for PRIu64 and friends
         ^
1 error generated.
file.m:5:9: fatal error: could not build module 'openssl'
#import <openssl/evp.h>
 ~~~~~~~^
2 errors generated.
```

**Comment by muxi** [comment]
That makes much more sense.
