### ISSUE TITLE
How to create any type of message in proto?

### ISSUE THREAD

**Issue by hscspring** [grpc/grpc#15098]
i am new to proto, and i have already read the documents.   
i got an issue below.

when i request to a serve, the server give me a response that contains many many messages, for example: `{"name":XXX, "id":XXX........}`, and i do not want to use enum or other type of proto.   

what i need is just return all of them together to the client, and the grpc do not need to know the details of the response data, then how can i do?  

what i know is `json.dumps` to make all massages to string...

**Comment by hscspring** [comment]
sorry for that.  i will try to make it clearer.  

I have a Python server A (Algorithm), and Nodejs server B (Server of the App) need to request to A for a response.  
B's request data like `{"text": "xxxxx", "userinfo": {"userid":"123", "username":"ccc",...}}`, and  
A's response data like `[{"noun":"string", "adj":"string", "location":[int, int], ...}, {...}, ...]`.  

I used zerorpc before, and now want to change it to grpc:) . 

At first my solution is to define all my data structure with `.proto`, but i found it a little redundant.   
The reason is the function of A deal with the request data as a total (that is the function deal with "userinfo" as a dict, it does not need to know the details of the dict).  

So i want to know whether there is a data type can make all given data together, i know it may not a good way, but it's convenient. Then i used `json.dumps` to make **"userinfo" and the response data** to a string respectively, and when i need to use them, i use `json.loads` to recover the information.  
It seems somewhat weird...

This is my question, i am quite not sure that was a good solution or not ...  

btw, thanks a lot for your replay.

**Comment by hscspring** [comment]
i am so sorry to cost your time...  
i've made that quite simple and it works now. but the issue is still. here it is:  

```
# proto
syntax = "proto3";
package spc;
service Spc {
    rpc GetResult(Input) returns (Output);
}

message Input {
    string text = 1;
    string userdict = 2;
}

message Output {
    string result = 1;
}


## Server ##
from concurrent import futures
import time

import grpc
import json

import spc_pb2
import spc_pb2_grpc
import my_module # it's a python file

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

class SpcServicer(spc_pb2_grpc.SpcServicer):
    def __init__(self):
        pass
    
    # i use json.loads and json.dumps to change the data into string
    # but in fact, userdict is a dict and output is a list contains several dicts like the former comment
    @staticmethod
    def GetResult(request, context):
        text = request.text
        userdict = json.loads(request.userdict)
        spc_output = module.function(text, userdict) # my function need two params
        result = spc_pb2.Output(result=json.dumps(spc_output)) 
        return result

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    spc_pb2_grpc.add_SpcServicer_to_server(
            SpcServicer(), server
            )
    server.add_insecure_port('[::]:50055')
    server.start()
    try:
        while True:
            time.sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)

if __name__ == '__main__':
    serve()


## Client # For simple, i use python, it doesn't affect my explain ##
import json
import grpc

import spc_pb2
import spc_pb2_grpc


def get_result(stub, text, userdict):
    input = spc_pb2.Input(text=text, userdict=json.dumps(userdict))
    spc_output = stub.GetResult(spc_input)
    result = json.loads(spc_output.result)
    return result

def run():
    channel = grpc.insecure_channel('localhost:50055')
    stub = spc_pb2_grpc.SpcStub(channel)
    print("----------GetResult----------")
    text = "string..."
    userdict = {"key1": ["value1", "value2"], ...}
    result = get_result(stub, text, userdict)
    print(result)

if __name__ == '__main__':
    run()
```

many thanks to u.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks. That code looks like it works - does it work? If so, what's the problem? Is it that you'd like not to have to do the JSON serialization on both sides?

Have you looked at defining in your .proto other kinds of messages and using them as submessages of your `Input` message?

**Comment by hscspring** [comment]
it works.
the problem is what you said.
and with your opinion i am now sure about it.
thanks ~

2018-04-24 22:10 GMT+08:00 Nathaniel Manista <notifications@github.com>:

**Comment by nathanielmanistaatgoogle** [comment]
You're welcome; I am glad things are resolved for you!
