### ISSUE TITLE
 [third_party/protobuf/configure] Error 127 

### ISSUE THREAD

**Issue by wangjufan** [grpc/grpc#15093]
I fork it , clone it , and update the submodules .
But when i run pod install in grpc/src/objective-c/examples/Sample , error appears:

[!] /bin/bash -c 
set -e
if [ ! -f bin/protoc ]; then
  cd ../..
  # This will build protoc from the Protobuf submodule of gRPC, and put it in
  # ../../bins/opt/protobuf.
  #
  # TODO(jcanizales): Make won't build protoc from sources if one's locally installed, which
  # _we do not want_. Find a way for this to always build from source.
  make grpc_objective_c_plugin
  cd -
else
  mv bin/protoc .
  mv include/google .
fi

[AUTOGEN] Preparing protobuf
/bin/sh: autoreconf: command not found
make: *** [third_party/protobuf/configure] Error 127

**Comment by muxi** [comment]
Seems like you have some tools not installed (like autoconf); try again after you install (there are some instructions [here](https://grpc.io/docs/quickstart/objective-c.html)).
