### ISSUE TITLE
Where can I find c++ example of token authentication?

### ISSUE THREAD

**Issue by igenyar** [grpc/grpc#15105]
I am looking for a C++ helloworld-like server/client example using token based authentication (preferably OAuth2 or JWT). So far my search does not return useful results yet. Thanks for the help.

**Comment by yang-g** [comment]
We have some examples for auth with google APIs: https://grpc.io/docs/guides/auth.html
I am not sure whether this is what you asked for.

**Comment by igenyar** [comment]
Preferably, I would like to have more concrete example with enough details that is ready to build and test, instead of just snippets although they are still very informative. For example, something like this one https://github.com/grpc/grpc/issues/9593, there is one complete code example that tells you everything you need to set up SSL/TLS channels from scratch: the server side, the client side, and even the cert part. I wonder if you have something similar but only with SSL/TLS authentication replaced with token authentication.

**Comment by igenyar** [comment]
Perhaps something like this one? https://github.com/enricofoltran/hello-auth-grpc, only that it is written in Go not C++. Anyway, I think I've made my point clear. Thanks for the help.
