### ISSUE TITLE
Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Name resolution failure

### ISSUE THREAD

**Issue by sreddybr3** [grpc/grpc#15106]
### What version of gRPC and what language are you using?
gRPC 1.11.0 (Python)

### What operating system (Linux, Windows, …) and version?
 Ubuntu 16:04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.5.2
 
### What did you do?
Start a gRPC python server inside container in Kubernetes. Exec inside container 
netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:50051           0.0.0.0:*               LISTEN      1/python

Sending grpc client request using channel = grpc.insecure_channel('127.0.0.1:50051')

### What did you expect to see?
 Json response from the server
 
### What did you see instead?
 
   response = self.stub.SayHello(request)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 487, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 437, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Exception calling application: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Name resolution failure)>)>
 
### Anything else we should know about your project / environment?
Works well with docker compose and having issues in Kubernetes environment

**Comment by nathanielmanistaatgoogle** [comment]
What argument are you passing to `add_insecure_port` in your server code? Do you have any luck if you change `127.0.0.1` in your code to `localhost`?

**Comment by enguerrandgrx** [comment]
Hello, I have the same problem as you when trying 
channel = grpc.insecure_channel('localhost:50051'). Do you have find any way to solve it ? do you use a service in kubernet ? I don't use a service for the moment but kubectl run server --image=path_to_img --port=50051 --replicas=5
Thanks

**Comment by faizalkassamalisc** [comment]
any updates here?

**Comment by nicolasnoble** [comment]
@faizalkassamalisc did you see @nathanielmanistaatgoogle's update and troubleshooting question ?

**Comment by faizalkassamalisc** [comment]
I've tried localhost, 127.0.0.1, ::1, 0.0.0.0, and the container's ip which was 172.0.0.2

the only way I've been able to get this to work is to docker run the grpc client with something like 
`--net=container:$(server_container_id)`

is that expected? I'm admittedly a container n00b but was hoping to use a grpc client running on the host to hit a server running inside a container

**Comment by NathofGod** [comment]
I'm having what I think is the same issue here. I have a REST API that is exposed and calls a gRPC service that isn't exposed. Locally all works and I just can't get it to find the server when running in Kubernetes!!

**Comment by chakradarraju-strings** [comment]
I'm affected by same problem, grpc doesn't resolve service in kubernetes.
Is this expected?

**Comment by ericgribkoff** [comment]
@chakradarraju-strings Can you post details on how you're configuring and deploying your gRPC server on kubernetes?  There is a quickstart at https://cloud.google.com/endpoints/docs/grpc/get-started-kubernetes-engine, so comparing how your backend is setup to the instructions there may prove useful

**Comment by chakradarraju-strings** [comment]
Sorry, the cause was that the service was in a different kubernetes namespace. So name resolution failed. This got fixed after I moved the gRPC service into same namespace.

**Comment by gnossen** [comment]
@sreddybr3 @NathofGod Name resolution is the likely candidate. Can you `kubectl exec` into the container running the grpc client and ensure you can resolve the server name with `nslookup` or `dig`? This may require installing a package within the container.
