### ISSUE TITLE
macos/grpc_basictests_opt failing a lot lately

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#15103]
https://source.cloud.google.com/results/invocations/573d390a-7504-40a6-9315-1a5e61986e1f/targets

Both run_tests_objc_macos_opt_native and run_tests_csharp_macos_opt_native seem to be failing a lot lately, each for what looks like different reasons.

**Comment by matt-kwong** [comment]
Obj-C tests should be fixed. Still working on a fix for C#

cc @jtattermusch

**Comment by matt-kwong** [comment]
C# tests should be fixed by #15138. Waiting for green builds on master before closing this issue.

**Comment by matt-kwong** [comment]
Both dbg and opt have had 2 green builds each, closing issue.
