### ISSUE TITLE
FLAKE cmake/build/Debug/h2_ssl_test.exe call_creds

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#15120]
call_creds.cc:110] server peer:
I0418 22:32:33.466000000  3360 call_creds.cc:111] 	authenticated: NO
I0418 22:32:33.466000000  3360 call_creds.cc:117] 	all properties:
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		transport_security_type: ssl
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		ssl_session_reused: false
I0418 22:32:33.466000000  3360 call_creds.cc:110] client peer:
I0418 22:32:33.466000000  3360 call_creds.cc:111] 	authenticated: YES
I0418 22:32:33.466000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: *.test.google.fr
I0418 22:32:33.466000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: waterzooi.test.google.be
I0418 22:32:33.466000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: *.test.youtube.com
I0418 22:32:33.466000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: 192.168.1.3
I0418 22:32:33.466000000  3360 call_creds.cc:117] 	all properties:
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		transport_security_type: ssl
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		x509_common_name: *.test.google.com
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		x509_pem_cert: -----BEGIN CERTIFICATE-----
MIICnDCCAgWgAwIBAgIBBzANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJBVTET
MBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQ
dHkgTHRkMQ8wDQYDVQQDEwZ0ZXN0Y2EwHhcNMTUxMTA0MDIyMDI0WhcNMjUxMTAx
MDIyMDI0WjBlMQswCQYDVQQGEwJVUzERMA8GA1UECBMISWxsaW5vaXMxEDAOBgNV
BAcTB0NoaWNhZ28xFTATBgNVBAoTDEV4YW1wbGUsIENvLjEaMBgGA1UEAxQRKi50
ZXN0Lmdvb2dsZS5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOHDFSco
LCVJpYDDM4HYtIdV6Ake/sMNaaKdODjDMsux/4tDydlumN+fm+AjPEK5GHhGn1Bg
zkWF+slf3BxhrA/8dNsnunstVA7ZBgA/5qQxMfGAq4wHNVX77fBZOgp9VlSMVfyd
9N8YwbBYAckOeUQadTi2X1S6OgJXgQ0m3MWhAgMBAAGjazBpMAkGA1UdEwQCMAAw
CwYDVR0PBAQDAgXgME8GA1UdEQRIMEaCECoudGVzdC5nb29nbGUuZnKCGHdhdGVy
em9vaS50ZXN0Lmdvb2dsZS5iZYISKi50ZXN0LnlvdXR1YmUuY29thwTAqAEDMA0G
CSqGSIb3DQEBCwUAA4GBAJFXVifQNub1LUP4JlnX5lXNlo8FxZ2a12AFQs+bzoJ6
hM044EDjqyxUqSbVePK0ni3w1fHQB5rY9yYC5f8G7aqqTY1QOhoUk8ZTSTRpnkTh
y4jjdvTZeLDVBlueZUTDRmy2feY5aZIU18vFDK08dTG0A87pppuv1LNIR3loveU8
-----END CERTIFICATE-----
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: *.test.google.fr
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: waterzooi.test.google.be
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: *.test.youtube.com
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: 192.168.1.3
I0418 22:32:33.466000000  3360 call_creds.cc:120] 		ssl_session_reused: false
E0418 22:32:33.466000000  3360 security_context.cc:46] Method is client-side only.
I0418 22:32:33.466000000  3360 call_creds.cc:47] Running test: test_request_response_with_payload_and_deleted_call_creds/chttp2/simple_ssl_fullstack
I0418 22:32:36.076000000  3360 subchannel.cc:608] New connected subchannel at 008FE1C8 for subchannel 008E9A10
I0418 22:32:36.076000000  3360 call_creds.cc:110] server peer:
I0418 22:32:36.076000000  3360 call_creds.cc:111] 	authenticated: NO
I0418 22:32:36.076000000  3360 call_creds.cc:117] 	all properties:
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		transport_security_type: ssl
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		ssl_session_reused: false
I0418 22:32:36.076000000  3360 call_creds.cc:110] client peer:
I0418 22:32:36.076000000  3360 call_creds.cc:111] 	authenticated: YES
I0418 22:32:36.076000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: *.test.google.fr
I0418 22:32:36.076000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: waterzooi.test.google.be
I0418 22:32:36.076000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: *.test.youtube.com
I0418 22:32:36.076000000  3360 call_creds.cc:115] 		x509_subject_alternative_name: 192.168.1.3
I0418 22:32:36.076000000  3360 call_creds.cc:117] 	all properties:
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		transport_security_type: ssl
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		x509_common_name: *.test.google.com
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		x509_pem_cert: -----BEGIN CERTIFICATE-----
MIICnDCCAgWgAwIBAgIBBzANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJBVTET
MBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQ
dHkgTHRkMQ8wDQYDVQQDEwZ0ZXN0Y2EwHhcNMTUxMTA0MDIyMDI0WhcNMjUxMTAx
MDIyMDI0WjBlMQswCQYDVQQGEwJVUzERMA8GA1UECBMISWxsaW5vaXMxEDAOBgNV
BAcTB0NoaWNhZ28xFTATBgNVBAoTDEV4YW1wbGUsIENvLjEaMBgGA1UEAxQRKi50
ZXN0Lmdvb2dsZS5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOHDFSco
LCVJpYDDM4HYtIdV6Ake/sMNaaKdODjDMsux/4tDydlumN+fm+AjPEK5GHhGn1Bg
zkWF+slf3BxhrA/8dNsnunstVA7ZBgA/5qQxMfGAq4wHNVX77fBZOgp9VlSMVfyd
9N8YwbBYAckOeUQadTi2X1S6OgJXgQ0m3MWhAgMBAAGjazBpMAkGA1UdEwQCMAAw
CwYDVR0PBAQDAgXgME8GA1UdEQRIMEaCECoudGVzdC5nb29nbGUuZnKCGHdhdGVy
em9vaS50ZXN0Lmdvb2dsZS5iZYISKi50ZXN0LnlvdXR1YmUuY29thwTAqAEDMA0G
CSqGSIb3DQEBCwUAA4GBAJFXVifQNub1LUP4JlnX5lXNlo8FxZ2a12AFQs+bzoJ6
hM044EDjqyxUqSbVePK0ni3w1fHQB5rY9yYC5f8G7aqqTY1QOhoUk8ZTSTRpnkTh
y4jjdvTZeLDVBlueZUTDRmy2feY5aZIU18vFDK08dTG0A87pppuv1LNIR3loveU8
-----END CERTIFICATE-----
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: *.test.google.fr
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: waterzooi.test.google.be
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: *.test.youtube.com
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		x509_subject_alternative_name: 192.168.1.3
I0418 22:32:36.076000000  3360 call_creds.cc:120] 		ssl_session_reused: false
E0418 22:32:36.076000000  3360 security_context.cc:46] Method is client-side only.
I0418 22:32:36.076000000  3360 call_creds.cc:47] Running test: test_request_with_server_rejecting_client_creds/chttp2/simple_ssl_fullstack
D0418 22:32:38.326000000  3360 port_server_client.cc:139] failed port pick from server: retrying [{"created":"@1524115958.279000000","description":"Failed HTTP requests to all targets","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\src\core\lib\http\httpcli.cc","file_line":202,"referenced_errors":[{"created":"@1524115957.201000000","description":"Failed HTTP/1 client request","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\src\core\lib\http\httpcli.cc","file_line":112,"referenced_errors":[{"created":"@1524115957.201000000","description":"OS Error","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\src\core\lib\iomgr\tcp_client_windows.cc","file_line":106,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061},{"created":"@1524115958.279000000","description":"OS Error","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\src\core\lib\iomgr\tcp_client_windows.cc","file_line":106,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061}]}]}]
E0418 22:32:45.654000000  3360 call_creds.cc:450] assertion failed: status == GRPC_STATUS_UNAUTHENTICATED
Abort handler called.
*** 0: 000000000039BDAF print_current_stack - 000000000039BD10
*** 1: 000000000039C31B abort_handler - 000000000039C2F0
*** 2: 0000000070E5F0CB raise - 0000000070E5ED60
*** 3: 0000000070E60622 abort - 0000000070E605F0
*** 4: 000000000023C3EA test_request_with_server_rejecting_client_creds - 000000000023BDC0
*** 5: 000000000023C674 call_creds - 000000000023C620
*** 6: 0000000000232A3D grpc_end2end_tests - 00000000002323B0
*** 7: 0000000000231F74 main - 0000000000231DF0
*** 8: 00000000004F917E invoke_main - 00000000004F9160
*** 9: 00000000004F8FE0 __scrt_common_main_seh - 00000000004F8E90
*** 10: 00000000004F8E7D __scrt_common_main - 00000000004F8E70
*** 11: 00000000004F9198 mainCRTStartup - 00000000004F9190
*** 12: 00000000754F336A BaseThreadInitThunk - 00000000754F3358
*** 13: 00000000779B9902 RtlInitializeExceptionChain - 00000000779B989F
*** 14: 00000000779B98D5 RtlInitializeExceptionChain - 00000000779B989F

https://source.cloud.google.com/results/invocations/f2078c1f-ff05-4c12-826a-f398c95975f1/targets/github%2Fgrpc%2Fc_windows_dbg_native/tests

**Comment by sreecha** [comment]
Haven't seen this in a while. Closing
