### ISSUE TITLE
Support build with Bazel and Android NDK

### ISSUE THREAD

**Issue by Qining** [grpc/grpc#15148]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 0.12.0
 
### What operating system (Linux, Windows, …) and version?
Linux Debian 4.9.82
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Android NDK r15
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Compile GRPC C++ library for uses on Android native applications. Adding `grpc++` target as a dep in `cc_library`
 
### What did you expect to see?
 Successful build
 
### What did you see instead?
 pthread not found on Android NDK toolchain (libcpp)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

The `pthread` flag is introduced at https://github.com/grpc/grpc/blob/master/bazel/grpc_build_system.bzl#L85
For Android NDK, there is no libpthread.so or libpthread.a, pthread functions are embeded in standard library, we just need to drop this flag here.
 
### Anything else we should know about your project / environment?
I'm working on GAPID: https://github.com/google/gapid/, trying to use grpc to replace our own host <-> android device communication protocol.

**Comment by nicolasnoble** [comment]
@Qining the issue is similar to that of Windows, and there's currently some amount of code to do this. The line you are referring to does exactly this.

I don't know what the Bazel's selector for Android would be, but it'd need to be added there.

**Comment by Qining** [comment]
Hi @nicolasnoble, I found many Google code repos uses this to check if the build target is for Android:
```
config_setting(
    name = "android",
    values = {"crosstool_top": "//external:android/crosstool"}
)
```
One such example can be found at boringssl: https://github.com/google/boringssl/blob/master-with-bazel/BUILD#L49
And there are many other repos using the same thing.
And, I can also find it in Bazel's code: https://source.bazel.build/bazel/+/master:third_party/protobuf/3.4.0/BUILD;l=174
Especially this one, looks like this is sort of builtin.
https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/android/AndroidNdkRepositoryRule.java;l=41

For our project: GAPID: https://github.com/google/gapid, we need more detailed info for the CPU, so we use our more specific version:
https://github.com/google/gapid/blob/master/tools/build/BUILD.bazel#L65

As for Windows, as GAPID need to be run on Win/Mac/Linux, we somehow made it work. The code is still in review, but generally we overwrite the BUILD file and some rules to make it work: https://github.com/google/gapid/pull/1861
I just copy-paste and modified a little bit for Windows and Android. The `grpc_cc_library` is modified in grpc_c++.bzl to do the job.

Hope this helps
