### ISSUE TITLE
[Feature Request] SSL Cert reload API in C++

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#15154]
Reference - https://groups.google.com/forum/#!searchin/grpc-io/ssl$20arpit%7Csort:date/grpc-io/TUsC_MTIv2U/oRhuDxWaBgAJ
 
### What version of gRPC and what language are you using?
 1.10.0/C++
 
I have discussed this issue on the above mailing list thread and brought up in the last community sync up. I am filing this issue here so it is officially in consideration.

Appreciate your time.

Thanks.

**Comment by abaldeva** [comment]
Hi,

Is this on your radar to provide support for?

Thanks.

**Comment by jiangtaoli2016** [comment]
@abaldeva Do you want to write c++ and contribute to the community?

**Comment by abaldeva** [comment]
I don't have any plans. But if it is not on your radar, let me know and I'll see if I can find out someone at my company to do this (I am leaving for a long vacation soon). 

Thanks.

**Comment by HikaruZChen** [comment]
@jiangtaoli2016 is there any update? Has grpc support reload SSL certificate in C++?

**Comment by yihuazhang** [comment]
I do not think gRPC security team has any imminent plan to support the credential reload in C++. However, you can use `TLSCredentials` and `TLSServerCredentials` that currently has support for credential reload.
