### ISSUE TITLE
c-ares localhost resolution on windows appears potentially breaking

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#15158]
While working on #12416 (on a machine running `Windows Server 2016`), I am noticing that attempts to resolve "localhost" are not working. And it appears that when c-ares begins it's hostname resolution and [first checks the hosts files before making a query to a DNS server](https://github.com/c-ares/c-ares/blob/master/ares_gethostbyname.c#L155), it [opens up a hosts file]( https://github.com/c-ares/c-ares/blob/master/ares_gethostbyname.c#L379) (on my machine, this file is `C:\Windows\System32\drivers\etc\hosts`).

The problem is that, <i>at least on my windows server 2016 machine</i>, `C:\Windows\System32\drivers\etc\hosts` has (among more) this:

```
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```

and [apparently this hosts file configuration is relatively common on newer versions of windows](https://serverfault.com/questions/4689/windows-7-localhost-name-resolution-is-handled-within-dns-itself-why).

This seems to indicate that if c-ares was turned on as the default DNS resolver in Windows (after WIP enabling based on https://github.com/grpc/grpc/pull/12416 is checked in), then `localhost` resolution would likely break for users that haven't touched their host file's default config.

Possible fix: perhaps our wrapper over c-ares can detect ipv6 availability and resolve localhost to 127.0.0.1 or ::1 on our own, which could then have the downside of ignoring that entry in the hosts file...

Opening for possible ideas

cc @nicolasnoble @markdroth @jtattermusch

**Comment by dgquintas** [comment]
Why is that host file problematic? Because c-ares will not read that file and claim that localhost is unknown?

**Comment by apolcyn** [comment]
It's problematic because c-ares "reads and only reads" the file, and when these hosts files don't have "localhost" entries (apparently common), c-ares <i>doesn't</i> spoof anything up - thus causing "localhost" resolution to fail.

**Comment by dgquintas** [comment]
Ah, I missed the fact that the lines were commented
