### ISSUE TITLE
Cannot find details in C# status object, when passed from Golang details.

### ISSUE THREAD

**Issue by jchanmeta** [grpc/grpc#15172]
### Should this be an issue in the gRPC issue tracker? 
Yes
 
### What version of gRPC and what language are you using?
 1.9
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04.4 LTS (for proto code generation)and Windows 10 (Client)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 libprotoc 3.5.1, generating to C# code.
 
### What did you do?
The Golang server side code which creates the Status object is:
`s, err := status.New(codes.Code(metadata.GrpcCode), msg).WithDetails(&Foo{foo: 3})`
where `Foo{foo:3}` is a proto.Message.

The relevant bit of proto that this relates to is:
```
message Foo {
 int32 foo = 1
}
```

Note that while debugging, this was verified to contain the metadata (the msg and the grpc_code), as well as the int (3).
 
### What did you expect to see?
 Expect the C# RpcException object (given from the Golang server) to have a Status containing a detail with the given int (in the above example, there should be a 3 contained in the Status details).
 
### What did you see instead?
An RpcException object with the `Detail: "rpc error: code = InvalidArgument desc = messageString" `, which contains the grpc_code and the msg, but not the foo integer.

**Comment by Green7** [comment]
I had the same problem.
You can read details in c# by RpcException.Trailers field.
Details  are serialized as field in Status message defined in:
https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto

Here is sample pseudo-code :
```
catch (RpcException e)
{
   foreach (var entry in e.Trailers)
   {
     if (entry.Key == "grpc-status-details-bin")
     {
        var grpcStatus = Google.Rpc.Status.Parser.ParseFrom(entry.ValueBytes);
        
        // here you should have your Foo message in grpcStatus.Details[0].Value
        // so you can deserialize it: 
        var f = Foo.Parser.ParseFrom(grpcStatus.Details[0].Value);
     }
  }
}
```
Perhaps there is a simpler way but I did not find it :)
