### ISSUE TITLE
build_docker_node failing in interop tests

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#15199]
https://source.cloud.google.com/results/invocations/8f98c203-a9ee-43b1-aa85-cf3f375e6cb8/targets
https://source.cloud.google.com/results/invocations/5d5d5adf-fc93-4e7c-8f95-0a3a3634ebab/targets

**Comment by jtattermusch** [comment]
Similar to #15289, but the error seems to be  `fatal: reference is not a tree: 2068ffe512795d16dc31522c5531075a4f239e7d`
```
Fetching submodule third_party/benchmark
Fetching submodule third_party/boringssl-with-bazel
Fetching submodule third_party/protobuf
fatal: reference is not a tree: 2068ffe512795d16dc31522c5531075a4f239e7d
+ EXITCODE=128
+ docker rm -f build_grpc_interop_node_7595ade7-06fd-4b1c-8a19-7ddf31bdcbe7
build_grpc_interop_node_7595ade7-06fd-4b1c-8a19-7ddf31bdcbe7
+ exit 128
2018-04-25 13:29:43,639 FAILED: build_docker_node [ret=128, pid=9361, time=312.0sec]
```

**Comment by jtattermusch** [comment]
After inspecting logs for some of the PRs referencing this issue, I think the `fatal: reference is not a tree: 2068ffe512795d16dc31522c5531075a4f239e7d` might be a one-off, and most of the failures are actually 
instances of #15289 with error `No rule to make target 'Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/subchannel_list.o'`

**Comment by markdroth** [comment]
Hmm.  I did remove subchannel_list.cc in #14886, but I did update the build files, and it looks like this test was failing even before that.  So I'm not sure if that's related.

**Comment by jtattermusch** [comment]
I'll close this issue at #15289 seems to be the one that's currently ongoing.
