### ISSUE TITLE
Segmentation fault when upgrading to grpc-1.11.0 via PECL

### ISSUE THREAD

**Issue by lashae** [grpc/grpc#15210]
### Should this be an issue in the gRPC issue tracker?
I'm not sure whether this repository is the correct place however this issue is definitely a bug.
 
### What version of gRPC and what language are you using?
```
root@yserver:/# pecl list
Installed packages, channel pecl.php.net:
=========================================
Package  Version State
grpc     1.8.5   stable
protobuf 3.5.1.1 stable
```
 
### What operating system (Linux, Windows, …) and version?
```
root@yserver:/# uname -a
Linux yserver 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
``` 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
```
root@yserver:/# dpkg -l | grep -E "php-pear|php7.1-dev|gcc"
ii  gcc                                   4:6.3.0-4                                                          amd64        GNU C compiler
ii  gcc-6                                 6.3.0-18+deb9u1                                                    amd64        GNU C compiler
ii  gcc-6-base:amd64                      6.3.0-18+deb9u1                                                    amd64        GCC, the GNU Compiler Collection (base package)
ii  libgcc-6-dev:amd64                    6.3.0-18+deb9u1                                                    amd64        GCC support library (development files)
ii  libgcc1:amd64                         1:6.3.0-18+deb9u1                                                  amd64        GCC support library
ii  php-pear                              1:1.10.5+submodules+notgz-1+0~20170904061717.3+stretch~1.gbpe356ca all          PEAR Base System
ii  php7.1-dev                            7.1.16-1+0~20180405085419.16+stretch~1.gbp4937aa                   amd64        Files for PHP7.1 module development

```
 
### What did you do?
I tried to upgrade grpc PECL package by running `pecl upgrade`.
 
### What did you expect to see?
 I expect `grpc` package to be upgraded.
 
### What did you see instead?
It ended with a segmentation fault message.
 
### Anything else we should know about your project / environment?
I'm not sure whether it makes sense but this server is on Google Cloud.

**Comment by ZhouyihaiDing** [comment]
Thanks for reporting the bug!
I can see the same segmentation fault when running `pecl upgrade`.
We add `-O2` to the compile FLAGS [since v1.11.0](https://github.com/grpc/grpc/blob/v1.11.0/config.m4#L15-L16) and I guess `pecl upgrade` leaves some old files which it thinks don't need to compile. 
Can you please try `pecl uninstall grpc && pecl install grpc` instead of `pecl upgrade grpc`?

**Comment by lashae** [comment]
@ZhouyihaiDing Thanks, `pecl uninstall grpc && pecl install grpc` worked.
