### ISSUE TITLE
TIMEOUT: cloud_to_prod:python

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#15231]
TIMEOUT: cloud_to_prod:python:default:cancel_after_begin
```
2018-04-30 10:04:00,501 TIMEOUT: cloud_to_prod:python:default:cancel_after_begin [pid=12843, time=186.6sec]
2018-04-30 10:04:00,685 FAILED: Some tests failed
```
https://source.cloud.google.com/results/invocations/7d96ae3d-aad8-43a3-b9c2-f3f4d65e5229/targets

TIMEOUT: cloud_to_prod:python:gateway_v4:timeout_on_sleeping_server
https://source.cloud.google.com/results/invocations/5f182efa-c951-444f-90f8-0f151e573a1b/targets

**Comment by mehrdada** [comment]
Looks like it has not been seen in a while. Closing.
