### ISSUE TITLE
Interop go:<language>_server:unimplemented_method test failures

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#15244]
Sometime around 10 AM yesterday, a change was merged in grpc-go that broke these tests. They fail with this error:

```
FATAL: 2018/04/30 17:55:45 grpc.Invoke(_, _, _, _, _) = rpc error: code = Unknown desc = Exception was thrown by handler., want error code Unimplemented
exit status 1
```
https://sponge.corp.google.com/target?id=09235fcb-f786-414f-9830-f68808bd6bc7&target=github/grpc

@MakMukhi, I'm assigning you because https://github.com/grpc/grpc-go/pull/1987 was merged around this time, but feel free to reassign this if you don't think this is related to your change.

**Comment by MakMukhi** [comment]
This should be fixed now.

**Comment by matt-kwong** [comment]
Builds are green on master, thanks for fix!
