### ISSUE TITLE
NameError: undefined method `encode' for class `Class' in gem version 0.6.1

### ISSUE THREAD

**Issue by carlisia** [grpc/grpc#1524]
I am getting this error:
```
E0507 17:22:18.647245000 4413489152 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0507 17:22:19.711648000 4413489152 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0507 17:22:21.812144000 4413489152 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
NameError: undefined method `encode' for class `Class'
from /Users/carlisiacampos/dev/omUI/.bundle/gems/grpc-0.6.1/lib/grpc/generic/rpc_desc.rb:50:in `method'
```

**Comment by carlisia** [comment]
Apparently it happens in this ln: https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_desc.rb#L50

**Comment by tbetbetbe** [comment]
Could you post snippet showing the minimal code sample that's being affected this way

**Comment by carlisia** [comment]
It seems to happen when the code is `require`'ing the gem. In about 1 hr I'll be able to try to get more info.

**Comment by carlisia** [comment]
With grpc in my Gemfile and in my Gemfile.lock:

☻  rails c                            ruby-2.1.1p76 master
Loading development environment (Rails 4.2.0)
main » 4.2.0@2.1.1 require 'grpc'
=> false

**Comment by carlisia** [comment]
@tbetbetbe I narrowed down when the error gets triggered.

```
stub = Protobuf::OmRPC::Stub.new('http://www.myuri.com')
nothing = Nothing.new(value: 'test')
res = stub.get_my_widget(nothing)
```
^^ that last line, it triggers a string of warnings/errors, with the initially reported error in the middle, and just keeps on rolling.

E0508 08:41:31.860919000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0508 08:41:32.937688000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0508 08:41:35.039196000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
NameError: undefined method `encode' for class `Class'
from /Users/carlisiacampos/dev/omUI/.bundle/gems/grpc-0.6.1/lib/grpc/generic/rpc_desc.rb:50:in `method'
main » 4.2.0@2.1.1 E0508 08:41:39.137428000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0508 08:41:47.236012000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0508 08:42:03.335144000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0508 08:42:35.435549000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known
E0508 08:43:39.542594000 4382846976 resolve_address_posix.c:120] getaddrinfo: nodename nor servname provided, or not known

**Comment by tbetbetbe** [comment]
What protobuf implementation are using ?

**Comment by tbetbetbe** [comment]
I am interested in the protobuf implementation you are using.

The gRPC service class assumes that there are static methods on the protobuf class for marshalling and unmarshaling the protobuf.
E.g  see [math_services.rb](https://github.com/grpc/grpc/blob/master/src/ruby/bin/math_services.rb)

```ruby
    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode  # <---  needs to be present on the protobuf class
      self.unmarshal_class_method = :decode  # <--- needs to be present on the protobuf class
      self.service_name = 'math.Math'

      rpc :Div, DivArgs, DivReply
      rpc :DivMany, stream(DivArgs), stream(DivReply)
      rpc :Fib, FibArgs, stream(Num)
      rpc :Sum, stream(Num), Num
    end
```

This is always true if the protobuf implementation is [google-protobuf(]https://rubygems.org/gems/google-protobuf).  The error you're reporting suggests that the 'marshal_class_method' and the 'unmarshal_class_method' are not present on the protobuf classes you are using.

Earlier, gRPC ruby used [beefcake](https://rubygems.org/gems/beefcake) as its protobuf library; it did not have the static encode method.   That was resolved that by [adding one](https://github.com/grpc/grpc/blob/6e48a4258ac4958e4392d8091d16267c1c1c2320/src/ruby/lib/grpc/beefcake.rb) via a mixin.

**Comment by carlisia** [comment]
@tbetbetbe I didn't install any specific protobuf library because I saw that the google-protobuf was a dependency of grpc:

```
    grpc (0.6.1)
      google-protobuf (~> 3.0.0alpha.1.1)
```

**Comment by tbetbetbe** [comment]
OK, can I see the proto rpc service definition you are using, or a minimal subset of it?

**Comment by tbetbetbe** [comment]
The error suggests that the class Nothing does not have a static encode method.

**Comment by carlisia** [comment]
@tbetbetbe does this help (there's lots more than what's here)?

```
  add_message "protobuf.Advertiser" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :domain, :string, 3
    optional :version, :string, 4
  end
```

```
  add_message "protobuf.Nothing" do
    optional :value, :string, 1
  end
```

```
  add_message "protobuf.ManyOrders" do
    repeated :orders, :message, 1, "protobuf.Order"
  end
```

```
  add_message "protobuf.Order" do
    optional :id, :int64, 1
    optional :advertiser_id, :int64, 2
    optional :enabled, :enum, 3, "protobuf.Trinary"
    optional :start, :int64, 4
    optional :end, :int64, 5
  end
```

```
module Protobuf
  ManyStrings = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.ManyStrings").msgclass
  String = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.String").msgclass
  Nothing = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Nothing").msgclass
  Advertiser = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Advertiser").msgclass
  ManyOrders = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.ManyOrders").msgclass
  Order = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Order").msgclass
  Trinary = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Trinary").enummodule
end
```

**Comment by tbetbetbe** [comment]
Can you take a look at https://gist.github.com/tbetbetbe/a3a6323f52955ad4fc51 ?
I've created a client based on the generated code you've provided and it seems OK.

**Comment by tbetbetbe** [comment]
Hi, @carlisia, just checking you saw the most recent update.  Do the snippets  at https://gist.github.com/tbetbetbe/a3a6323f52955ad4fc51 work for you?

**Comment by tbetbetbe** [comment]
Closing with 'wontfix' based on the [gist snippet](https://gist.github.com/tbetbetbe/a3a6323f52955ad4fc51) that seems to work.  Please re-open with an example if it continues to be an issue.
