### ISSUE TITLE
Decide where .pyi files go

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#15243]
We believe that gRPC Python Protoc Plug-In is going to need to be changed to support generating `.pyi` files. Where should those files be generated?

I sort of suspect right along the generated `.py` files, but maybe some need will push them to another location.

**Comment by hsaliak** [comment]
https://github.com/python/typing/issues/84 is a related discussion. worth to see what considerations were raised there..

**Comment by nathanielmanistaatgoogle** [comment]
To the best of my knowledge this is still a thing to be done.

**Comment by henribru** [comment]
Alongside the regular files seems like the best option. This is where Mypy looks by default, while putting it somewhere else requires additional configuration: https://mypy.readthedocs.io/en/latest/stubs.html#creating-a-stub

[PEP 561](https://www.python.org/dev/peps/pep-0561/) also states:

> For package maintainers wishing to ship stub files containing all of their type information, it is preferred that the *.pyi stubs are alongside the corresponding *.py files.

**Comment by henribru** [comment]
Any progress on this?

**Comment by lidizheng** [comment]
As I read the issue comments, this issue seems like a feature request for adding type annotations to generated code. This is on the road map of the AsyncIO stack https://github.com/grpc/proposal/pull/155.
