### ISSUE TITLE
Make warns "circular dependency dropped" when building with c-ares from submodule

### ISSUE THREAD

**Issue by ttencate** [grpc/grpc#15259]
### What version of gRPC and what language are you using?

The current `master`, being `1ff2e3878ff6`, C++. The issue is also present in `v1.11.0`.
 
### What operating system (Linux, Windows, …) and version?
 
Arch Linux.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
    gcc (GCC) 7.3.1 20180312
    GNU Make 4.2.1
 
### What did you do?

Trying to build with the bundled c-ares from the submodule, for use on systems that might not have it installed, or might have a too old version.

    $ git clean -fdx
    $ git submodule update --init --depth 1 third_party/cares/cares
    $ make HAS_SYSTEM_CARES=false
 
### What did you expect to see?
 
A clean compile.
 
### What did you see instead?

    make: Circular /home/thomas/grpc/libs/opt/libares.a <- /home/thomas/grpc/libs/opt/libaddress_sorting.a dependency dropped.

Compilation and linking continues and succeeds regardless. It's just annoying because it goes to stderr and my IDE interprets it as an error.

**Comment by ttencate** [comment]
`libares.a` depends explicitly on `libaddress_sorting.a` in the generated `Makefile`:

    $(LIBDIR)/$(CONFIG)/libares.a: $(ZLIB_DEP) $(ADDRESS_SORTING_DEP)  $(LIBARES_OBJS) 

And vice versa:

    $(LIBDIR)/$(CONFIG)/libaddress_sorting.a: $(ZLIB_DEP) $(CARES_DEP)  $(LIBADDRESS_SORTING_OBJS) 

I _think_ this is being generated fairly explicitly [here](https://github.com/grpc/grpc/blob/4e85a3aaf725238640fd59fbdb450cdedd5e47f8/templates/Makefile.template#L1505), which amounts to "for lib in address_sorting, ares, z: lib depends on every other lib except itself". That doesn't seem right to me.

**Comment by jtattermusch** [comment]
@nicolasnoble   can you confirm what @ttencate  is saying?

**Comment by nicolasnoble** [comment]
Yeah that sounds about right.

**Comment by jtattermusch** [comment]
@apolcyn   it looks like this cyclic dependency might have been introduced when adding the libaddress_sorting library?

**Comment by apolcyn** [comment]
Yeah that was added when adding`libaddress_sorting` - it's definitely an extraneous dependency.

Not sure what's a good way to fix right now... maybe special casing `address_sorting` when generating those dependencies.

**Comment by jtattermusch** [comment]
#15422 was merged, can we confirm that this problem was fixed and close?

**Comment by ttencate** [comment]
Confirmed from my end; the warning is gone starting from `80f9c2a00b`.
