### ISSUE TITLE
Certificate verification fails for some clients

### ISSUE THREAD

**Issue by theacodes** [grpc/grpc#15261]
⚠️ This issue is filed on behalf of a user of the client libraries, full context is here https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1284#issuecomment-356008494

### What version of gRPC and what language are you using?
 
Python 2.7.15 with OpenSSL 1.0.2o  27 Mar 2018
 
### What operating system (Linux, Windows, …) and version?
 
macOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Unsure
 
### What did you do?

The user attempted to run the sample [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py), but this does not appear unique to this sample.
 
### What did you expect to see?
 
The sample work. :)
 
### What did you see instead?
 
```
E0503 12:02:25.491373000 140735530255168 ssl_transport_security.cc:1063] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

This appears to happen consistently.

**Comment by nathanielmanistaatgoogle** [comment]
@jiangtaoli2016, @jboeuf: what do we know about the (potential) causes of `Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`?

**Comment by jiangtaoli2016** [comment]
This error occurs during SSL handshake. It looks like SSL library has trouble verifying the certificate. In this scenario, a python gRPC client tries to connect to Google cloud API and the error comes from the client side?

**Comment by tab1293** [comment]
@jiangtaoli2016 yes that is correct

**Comment by jiangtaoli2016** [comment]
When client connects to Google Cloud API, it uses SSL + OAuth. It is not mutual authentication. The failure happens when client has trouble verifying Google API's certificates. It looks that pem root certs are not set correctly. Did you use default pem root certs or provide your own root certs file with environment variable?

**Comment by tab1293** [comment]
So in the original issue that @jonparrott linked to the reporter was trying to run `transcribe_streaming_mic.py` which I'm assuming connects to Google Cloud API with SSL + OAuth. 

In my case, I am using certificates signed by a DigiCert intermediate CA. I am not setting root certs with an environment variable. When I use a golang gRPC client with my service, the TLS authentication works fine. It seems to just be an issue with the Python client. My system verifies the certificate fine as seen below:

```
$ echo QUIT | openssl s_client -showcerts -connect starlord.cloud.vimeo.com:8012 | openssl x509 -noout -text
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = US, ST = New York, L = New York, O = "Vimeo, Inc.", CN = *.cloud.vimeo.com
verify return:1
DONE
```

One strange thing to comment is that I had to stop using LibreSSL on my system to get verification to work. I am not using OpenSSL 1.0.2o. The LibreSSL issue seemed to be related to this: https://github.com/libressl-portable/portable/issues/80

Maybe the gRPC python client is facing similar issues not being able to follow the certificate chain?

**Comment by jiangtaoli2016** [comment]
@tab1293 Can you uninstall openssl (libssl-dev), in this case boringssl will be used. See whether it works again?

Also try to pass your system root cert as environment var. In MacOS, try
`export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR=/etc/ssl/cert.pem`

The error message shows an underlying error from OpenSSL. It could be many reasons: OpenSSL ctx in wrong state, handshake bytes from peer corrupted, or server certificates cannot be verified.

**Comment by mushtaque87** [comment]
Took the latest  
 pod 'SwiftGRPC' 
 pod 'SwiftProtobuf'
version using pod update and it got fixed .

Installing BoringSSL 10.0.6 (was 10.0.5 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing SwiftGRPC 0.5.1 (was 0.4.3 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing gRPC-Core 1.12.0 (was 1.11.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing Realm 3.7.6 (was 3.7.4 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing RealmSwift 3.7.6 (was 3.7.4 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)

Then all i need was create the session/service with my certificate.

let certPath = Bundle.main.url(forResource: "XYZ", withExtension: "pem")!
        let certificate = try! String(contentsOf: certPath)
        service = Pronounce_PronounceServiceClient(address: Constants.ServerApi.grpcBaseUrl, certificates: certificate)
