### ISSUE TITLE
Problem with keep-alive and streaming connection using C++

### ISSUE THREAD

**Issue by pavel-kokolemin** [grpc/grpc#15260]
### What version of gRPC and what language are you using?
1.12.0-dev, latest master branch (commit 1ff2e3878ff629f626b8e21c10a4d22f7c2f1baf) with C++

### What operating system (Linux, Windows, …) and version?
Debian 9 (stretch) amd64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 6.3.0
 
### What did you do?
Start long living streaming connection (from client to server) with enabled keep-alive:

```
channelArguments.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 10000);
channelArguments.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 10000);
channelArguments.SetInt(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 1);
channelArguments.SetInt(GRPC_ARG_HTTP2_BDP_PROBE, 1);
channelArguments.SetInt(GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS, 5000);
channelArguments.SetInt(GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS, 10000);
```

```
builder.AddChannelArgument(GRPC_ARG_KEEPALIVE_TIME_MS, 10000);
builder.AddChannelArgument(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 10000);
builder.AddChannelArgument(GRPC_ARG_HTTP2_BDP_PROBE, 1);
builder.AddChannelArgument(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 1);
builder.AddChannelArgument(GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS, 5000);
builder.AddChannelArgument(GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS, 10000);
```

### What did you expect to see?
Client and server send keep-alive packets and automatically detect peer disconnection in configured time frame.
 
### What did you see instead?
Both server and client do not send keep-alive packets on regular bases and as result unable to detect peer disconnection (waiting in grpc::ServerCompletionQueue::Next).

### Anything else we should know about your project / environment?
I just started playing with gRPC, so maybe I'm doing something wrong here, but still it looks like a bug for me. I looked at #14717 but can't understand why it does not work for me.
The sources and trace logs attached in the ZIP file.
Latest lines in the trace log with something related here:
```
I0503 16:30:08.417471952   19913 chttp2_transport.cc:813]    W:0x56149ac73060 CLIENT state IDLE -> WRITING [KEEPALIVE_PING]
I0503 16:30:08.417473752   19914 timer_manager.cc:190]       wait ended: was_timed:0 kicked:0
I0503 16:30:08.417518110   19914 timer_generic.cc:647]       TIMER CHECK BEGIN: now=30004 next=9223372036854775807 tls_min=30004 glob_min=30031
I0503 16:30:08.417536013   19914 timer_generic.cc:665]       TIMER CHECK END: r=1; next=30031
I0503 16:30:08.417482908   19913 combiner.cc:331]            C:0x56149ac76ec0 grpc_combiner_execute_finally c=0x56149ac73120; ac=0x56149ac76ec0
I0503 16:30:08.417588311   19913 combiner.cc:287]            C:0x56149ac76ec0 finish old_state=5
I0503 16:30:08.417612215   19913 combiner.cc:228]            C:0x56149ac76ec0 grpc_combiner_continue_exec_ctx contended=0 exec_ctx_ready_to_finish=0 time_to_execute_final_list=1
I0503 16:30:08.417547051   19914 timer_manager.cc:175]       sleep for a 27 milliseconds
I0503 16:30:08.417627903   19913 combiner.cc:269]            C:0x56149ac76ec0 execute_final[0] c=0x56149ac73120
D0503 16:30:08.417681226   19913 flow_control.cc:110]        0x56149ac76b60[0][cli] | t updt sent | trw:                       4194309, ttw:                       4194304, taw:                       4194304, srw:                              , slw:                              , saw:                              
I0503 16:30:08.417699714   19913 writing.cc:64]              CLIENT: Ping delayed [0x56149ac6e3f0]: too many recent pings: 0/2
I0503 16:30:08.417716181   19913 chttp2_transport.cc:813]    W:0x56149ac73060 CLIENT state WRITING -> IDLE [begin writing nothing]
I0503 16:30:08.417730865   19913 combiner.cc:287]            C:0x56149ac76ec0 finish old_state=3
I0503 16:30:08.417745518   19913 timer_generic.cc:647]       TIMER CHECK BEGIN: now=30004 next=9223372036854775807 tls_min=30004 glob_min=30031
I0503 16:30:08.417767033   19913 timer_generic.cc:665]       TIMER CHECK END: r=1; next=30031
I0503 16:30:08.417776468   19913 timer_manager.cc:183]       sleep until kicked
```
No more related messages and no more packets captured with tcpdump in the next two minutes.
[problem_with_keepalive.zip](https://github.com/grpc/grpc/files/1971125/problem_with_keepalive.zip)

**Comment by vadimi** [comment]
@pavel-kokolemin try also setting `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` to `0` on the client side.

**Comment by pavel-kokolemin** [comment]
It works! Thank you very much!

**Comment by daudrain** [comment]
@pavel-kokolemin @vadimi 
I do not understand the relationship between `GRPC_ARG_HTTP2_BDP_PROBE` and keep-alive management.
Why is it necessary to set `GRPC_ARG_HTTP2_BDP_PROBE` to 1 to get keep-alive working?

Thank you,
David

**Comment by pavel-kokolemin** [comment]
@daudrain I saw it on #14717 and decided that it won't harm :) It's probably not needed, but I did not tested this.
