### ISSUE TITLE
gRPC Python Introspection

### ISSUE THREAD

**Issue by cuadue** [grpc/grpc#15264]
### What version of gRPC and what language are you using?
 Python 1.11.0
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2

 
### What did you do?
 Exploring the object hierarchy
 
### What did you expect to see?
 Introspection
 
### What did you see instead?
 Not enough introspection
 
### Anything else we should know about your project / environment?

Does Google permit the below use case? I'm working with https://github.com/grpc/grpc/tree/master/examples/python/helloworld

Given a method, determine the appropriate request type.

In other words, this syntax is too verbose to satisfy business requirements:

    channel = grpc.insecure_channel('localhost:50051')
    stub = helloworld_pb2_grpc.GreeterStub(channel)
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))

My business situation requires a syntax such as:

    channel = grpc.insecure_channel('localhost:50051')
    stub = StubWrapper(helloworld_pb2_grpc.GreeterStub, channel)
    response = stub.SayHello(name='you')

Since Python is naturally introspective, I expect it would be possible to write a StubWrapper which queries `helloworld_pb2_grpc.GreeterStub` for the expected argument type.

However `helloworld_pb2_grpc.GreeterStub` does not seem to contain the expected type, but instead, only the serializer method of the type. This seems to be implemented in C++ which does not provide the same Python introspection features.

    >>> import helloworld_pb2
    >>> import grpc
    >>> import helloworld_pb2_grpc
    >>> ch=grpc.insecure_channel('asdf')
    >>> s=helloworld_pb2_grpc.GreeterStub(ch)
    >>> dir(s)
['SayHello', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
    >>> dir(s.SayHello)
['__abstractmethods__', '__call__', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_blocking', '_channel', '_managed_call', '_method', '_prepare', '_request_serializer', '_response_deserializer', 'future', 'with_call']
    >>> dir(s.SayHello._request_serializer)
['__call__', '__class__', '__delattr__', '__doc__', '__format__', '__get__', '__getattribute__', '__hash__', '__init__', '__name__', '__new__', '__objclass__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

As you can see, the method does not appear to provide enough information to call it. Instead, you need to have out-of-band knowledge about what protobuf type is expected.

Can Google meet my business needs?

**Comment by nathanielmanistaatgoogle** [comment]
I think this is related to, but not quite the same as, [issue 5094](https://github.com/grpc/grpc/issues/5094).

This enhancement request has some intriguing ideas but it's not clear that we'd implement it exactly as described. Consider an RPC invocation like
```py
my_response = my_stub.my_method(my_first_field=5, timeout=6)
```
- is `timeout` a field of the request or is `timeout` the timeout (in seconds) of the RPC?

**Comment by cuadue** [comment]
Thanks for referring to that issue. Will close this one and defer to that one.
