### ISSUE TITLE
C# Core Tests hangs

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1526]
This might be my change yet, but noting the failure here in case it happens repeatedly just for that change:

START: make
PASSED: make [time=6.3sec]
START: tools/run_tests/build_csharp.sh
PASSED: tools/run_tests/build_csharp.sh [time=27.4sec]
START: Grpc.Core.Tests
START: Grpc.Examples.Tests
START: Grpc.IntegrationTesting
PASSED: Grpc.Examples.Tests [time=4.9sec]
PASSED: Grpc.IntegrationTesting [time=7.0sec]
TIMEOUT: Grpc.Core.Tests
FAILED: Some tests failed

**Comment by jtattermusch** [comment]
That looks like the one that was solved by #1499

**Comment by ctiller** [comment]
It does look similar... I'm wondering if there's a secondary cause however - since this test run definitely had #1499 included.
