### ISSUE TITLE
CallOptions.Headers initalization for client requests

### ISSUE THREAD

**Issue by zsojma** [grpc/grpc#15272]
**Feature request** 
Language: .NET Core 2.0.7
 Grpc: 1.11.0
 
Hello, I would like to use C# interceptors to perform header forwarding for my gRPC clients. It works well when I manually create instance of `Metadata/Headers` class in `CallOptions` for each request:
```
public async Task<GrpcTestResponse> GetDataAsync(GrpcTestRequest request)
{
    return await Client.GetDataAsync(request, new CallOptions(new Metadata()));
}
```
where `Client` is my generated client's object from `.proto` file.

Then I can easilly forward headers in my interceptor:
```
public void ClientRequest<TRequest, TResponse>(ClientInterceptorContext<TRequest, TResponse> context)
    where TRequest : class
    where TResponse : class
{
    foreach (var httpHeader in _forwardHeadersProvider.GetForwardedHeaders())
    {
        context.Options.Headers.Add(httpHeader.Key, httpHeader.Value);
    }
}
```

Unfortunatelly, when I do not create instance of the `Metadata` class, the `context.Options.Headers` property is `null` and it is also readonly...

Would it be possible to create setter for `Headers` property or to have the property instantialized by default? I would like to fully skip creation of these extra methods (I need to have one per each grpc client's method). Then it would be possible to just call `Client.GetDataAsync` method instead of `this.GetDataAsync` method.

Thank you.

**Comment by Itfly** [comment]
I think you should use the below api in `CallInvokerExtensions` to forward headers:
```
public static CallInvoker Intercept(this CallInvoker invoker, Func<Metadata, Metadata> interceptor)
```
You need to create your `forwardingHeaderFunc`

**Comment by zsojma** [comment]
Thanks @Itfly, it works.
