### ISSUE TITLE
How to add a user provided http header into grpc request

### ISSUE THREAD

**Issue by jli053** [grpc/grpc#15273]
### What version of gRPC and what language are you using?
 gRPC++ 1.2.5, we use c++
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.5
 
### What did you do?
I want to add one http header into grpc request when using anyc api to send grpc request. Could you please help share the interface to add a http header?
 
### What did you expect to see?
 user provided http header can be added.
 
### What did you see instead?
 N/A

**Comment by MrMage** [comment]
You'll need to add the user's custom header in the metadata object that you supply in the metadata object when sending the `GRPC_OP_SEND_INITIAL_METADATA` operation.

See `GRPC_OP_SEND_INITIAL_METADATA`, `grpc_op.grpc_op_data.send_initial_metadata.metadata` and `struct grpc_metadata` in `grpc_types.h`.

**Comment by jli053** [comment]
Hi,

Thanks for your quick help. It is helpful. Now I can add my custom header by calling ClientContext::AddMetadata.

Thanks

**Comment by savagecm** [comment]
Good, 
This API is very useful
` /// Add the (\a meta_key, \a meta_value) pair to the metadata associated with
  /// a client call. These are made available at the server side by the \a
  /// grpc::ServerContext::client_metadata() method.
  ///
  /// \warning This method should only be called before invoking the rpc.
  ///
  /// \param meta_key The metadata key. If \a meta_value is binary data, it must
  /// end in "-bin".
  /// \param meta_value The metadata value. If its value is binary, the key name
  /// must end in "-bin".
  void AddMetadata(const grpc::string& meta_key,
                   const grpc::string& meta_value);
`

**Comment by srini100** [comment]
Question seems to be sufficiently answered. In future, please post questions in [grpcio](https://groups.google.com/forum/#!forum/grpc-io) group.
