### ISSUE TITLE
Error when installing firebase. grpc missing

### ISSUE THREAD

**Issue by virtuecom** [grpc/grpc#15286]
I did a clean create-react-app and after it installing the project all I did was _npm install firebase --save_
I have Node v.10 installed on my winx64 machine.

I would really appreciate it if someone could give me advice on how to fix this

This is the error I get:
`node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-win32-x64-unknown.tar.gz node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) gyp ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. gyp ERR! stack at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19) gyp ERR! stack at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16) gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29 gyp ERR! stack at FSReqWrap.oncomplete (fs.js:149:21) gyp ERR! System Windows_NT 10.0.16299 gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Future\\Desktop\\newapp\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Future\\Desktop\\newapp\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown" gyp ERR! cwd C:\Users\Future\Desktop\newapp\node_modules\grpc gyp ERR! node -v v10.0.0 gyp ERR! node-gyp -v v3.6.2 gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Future\Desktop\newapp\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Future\Desktop\newapp\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1) node-pre-gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Future\Desktop\newapp\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29) node-pre-gyp ERR! stack at ChildProcess.emit (events.js:182:13) node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:947:16) node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5) node-pre-gyp ERR! System Windows_NT 10.0.16299 node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Future\\Desktop\\newapp\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library" node-pre-gyp ERR! cwd C:\Users\Future\Desktop\newapp\node_modules\grpc node-pre-gyp ERR! node -v v10.0.0 node-pre-gyp ERR! node-pre-gyp -v v0.7.0 node-pre-gyp ERR! not ok Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Future\Desktop\newapp\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Future\Desktop\newapp\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1) npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the grpc@1.10.1 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Future\AppData\Roaming\npm-cache\_logs\2018-05-06T01_28_46_657Z-debug.log`

**Comment by apaatsio** [comment]
The error output says `Error: Can't find Python executable "python", you can set the PYTHON env variable.`

Do you have python installed and have you set the PYTHON env var?

**Comment by virtuecom** [comment]
I installed Python 3.6 after I first got the error and I still get it, the env variable was set automatically, now I don't know more about that.

![env](https://user-images.githubusercontent.com/39017271/39717909-f563b828-5234-11e8-96b0-ebc25e2411b4.PNG)

**Comment by virtuecom** [comment]
@apaatsio 
I installed Python 3.6 after I initially got the error and I still keep getting it, the env variable was set automatically, now I don't know more about that. I have node v10 so I don't think that would be the issue and the react-app is a clean install.
![env](https://user-images.githubusercontent.com/39017271/39717955-147ce68a-5235-11e8-8f89-d4aa6131a82d.PNG)

**Comment by virtuecom** [comment]
I have fixed the problem, there was an issue with the Node versions, basically a version over 10 doesn't work. LTS v8.11 would be completely fine.

**Comment by nicolasnoble** [comment]
You need Python because node uses gyp to build native extensions, which is in Python.
