### ISSUE TITLE
Some C++ benchmarks fail to upload results to BQ

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15290]
(this is about the qps_worker benchmarks, not microbenchmarks).
https://source.cloud.google.com/results/invocations/651b512e-8267-4109-9d5e-e4ccd5967448/targets/github%2Fgrpc%2Freports%2F32core/tests

Error messages look like this (the name of nonexistent field varies), the scenario itself seems to be successful.
```
Error inserting rows! Response: {u'kind': u'bigquery#tableDataInsertAllResponse', u'insertErrors': [{u'index': 0, u'errors': [{u'debugInfo': u'', u'reason': u'invalid', u'message': u'no such field.', u'location': u'serverstats[0].core_call_combiner_cancelled'}]}]}
Error uploading result to bigquery.
```

Basically, I think this means that C++ added some serverstats and we didn't update the BQ schema accordingly (and we didn't catch this because we are not running end to end benchmarks on PRs).

**Comment by jtattermusch** [comment]
CC @matt-kwong

**Comment by jtattermusch** [comment]
I tried running `tools/run_tests/performance/patch_scenario_results_schema.py --bq_result_table ` on all datatests mentioned in https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_full_performance_release.sh and https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_full_performance_master.sh. Let's see if that helps.

**Comment by ncteisen** [comment]
I am looking into this today. What is the best repro? Is the a cmdline I can use or should I just restart the job on kokoro, or can I actually get a terminal on the machines to iterate faster

**Comment by jtattermusch** [comment]
Not sure about repro, but the answer probably lies somewhere in massage_qps_stats.py and other benchmark related massaging scripts. It really looks like we are uploading a "stat" that should be stripped away (can you confirm?) and  this stripping for some reason doesn't happen (but it seems to be working works for some other c++  scenarios that are uploading without trouble). This scenario is C++ to C#, which might make it a bit special (maybe the massaging is language specific?).

**Comment by ncteisen** [comment]
Before we dive deeper into this, stats have been disabled in opt builds #15280. We decided as a team that they were not giving very good signal, and they were causing noticeable performance hit. They have been useful for one off runs to gathers counts, but not more than that.

So with that, I will put in a change to remove them from the bigquery bookkeeping

**Comment by jtattermusch** [comment]
This got eventually fixed by https://github.com/grpc/grpc/pull/15446
