### ISSUE TITLE
Compile the gRPC C Core library: Makefile cannot find the file specified (ares__close_sockets)

### ISSUE THREAD

**Issue by COSBap** [grpc/grpc#15307]
### What version of gRPC and what language are you using?
 Last version
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 GitBash
 
### What did you do?
Follow the Build from Source https://github.com/grpc/grpc/blob/master/INSTALL.md for Windows, using Cmake and Ninja,
Then try to compile the gRPC C Core library:
 $ cd grpc
 $ git submodule update --init
 $ make
 
### What did you expect to see?
 make complete
 
### What did you see instead?

 [MAKE]    Generating cache.mk
make: Circular C:/Users/Baptiste/grpc/libs/opt/libares.a <- C:/Users/Baptiste/grpc/libs/opt/libz.a dependency dropped.
make: Circular C:/Users/Baptiste/grpc/libs/opt/libares.a <- C:/Users/Baptiste/grpc/libs/opt/libaddress_sorting.a dependency dropped.
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
process_begin: CreateProcess(NULL, no_c_compiler -Ithird_party/protobuf/src -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/address_sorting/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -O2 -Wframe-larger-than=16384 -I. -Iinclude -IC:/Users/Baptiste/grpc/gens -DPB_FIELD_16BIT -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -fvisibility=hidden -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -std=c99 -Wsign-conversion -Wconversion -Wno-sign-conversion -MMD -MF C:/Users/Baptiste/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.dep -c -o C:/Users/Baptiste/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o third_party/cares/cares/ares__close_sockets.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:2782: C:/Users/Baptiste/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o] Error 2

Makefile:
2779 $(OBJDIR)/$(CONFIG)/%.o : %.c
2780 	$(E) "[C]       Compiling $<"
2781 	$(Q) mkdir -p `dirname $@`
2782 	$(Q) $(CC) $(CPPFLAGS) $(CFLAGS) -MMD -MF $(addsuffix .dep, $(basename $@)) -c -o $@ $<
 
There is nothing in C:/Users/Baptiste/grpc/objs/opt/third_party/cares/cares/ , ares__close_sockets.o must be there? and then it makes ares__close_sockets.dep?
I have just ares__close_sockets.c in C:\Users\Baptiste\grpc\third_party\cares\cares.
How can I get the missing file?

### Anything else we should know about your project / environment?
You will have noticed that I'm not a developer, thank you for your patience :)

**Comment by nicolasnoble** [comment]
Do you have submodules checked out ?

**Comment by COSBap** [comment]
I don't know, the "$ git submodule update --init" command runs correctly if it answers to the question
If not, how can I check out submodules?

**Comment by nicolasnoble** [comment]
Right, that's what I meant. As in, "does the source file exist ?". The output directory is obviously not the issue, but the input is.

@jtattermusch - do we even support this compilation case ?

**Comment by jtattermusch** [comment]
From the description it sounds like you are mixing the use of cmake and the default (non-cmake) Makefile.
You shouldn't run the `make` command on windows (it uses the main `Makefile` which only should be used on Unix systems), instead, run `cmake --build .` or  `ninja` from `.build` directory you previously configured with cmake (see https://github.com/grpc/grpc/blob/master/INSTALL.md#cmake-using-visual-studio-2015-or-2017-can-only-build-with-openssl_no_asm) 

We do have continuous tests that test C core build with cmake on Windows and they are passing very consistently, so I think in your case it's just that you aren't using cmake correctly.

**Comment by COSBap** [comment]
OK, I see, thank you for your details
