### ISSUE TITLE
Error installing BoringSSL

### ISSUE THREAD

**Issue by yifriday** [grpc/grpc#15326]
when i do "pod install" in route_guide,i failed with this.

```
Cloning into '/var/folders/l3/qphn50695f93ysh73ryck2lh0000gn/T/d20180510-8565-1f9r09r'...
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Failed to connect to boringssl.googlesource.com port 443: Operation timed out
```

could anyone help me???

by the way,i'm in china

**Comment by nicolasnoble** [comment]
This URL is indeed blocked by the Chinese firewall. @muxi ? @makdharma ?

**Comment by yifriday** [comment]
so, what should i do now?

**Comment by muxi** [comment]
I think the appropriate solution is to talk to Xi but.... I'll redirect the podspec to BoringSSL's Github mirror (https://github.com/google/boringssl) in the next release.

**Comment by zhaohuang2016** [comment]
中国的朋友有解决了的吗?

**Comment by zhaohuang2016** [comment]
中国的朋友有解决了的吗?能否帮忙说下解决法案

**Comment by muxi** [comment]
Fetch Cocoapods trunk and try again.

**Comment by zhaohuang2016** [comment]
Cloning into '/var/folders/hp/3gx151ys17v8473j92dgsv_w0000gn/T/d20180525-1681-10v6gz9'...
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Could not resolve host: boringssl.googlesource.com

**Comment by zhaohuang2016** [comment]
All used tools, the system, is the latest version.

**Comment by zhaohuang2016** [comment]
Besides the cocopods scheme, do you have a manual configuration scheme? Could you please send me a copy by email? My email is zh_qqtech@163.com. Thank you.

**Comment by muxi** [comment]
We do not have a manual configuration scheme unfortunately. It would be helpful if you can help me test a few things (since I am out of gfw):

* Change the [home page](https://github.com/grpc/grpc/blob/5d83bedb77d14a5d0240bc9f11c86c45704f30f6/src/objective-c/BoringSSL.podspec#L64) of this spec to `https://github.com/google/boringssl`
* Remove the line of [documentation_url](https://github.com/grpc/grpc/blob/5d83bedb77d14a5d0240bc9f11c86c45704f30f6/src/objective-c/BoringSSL.podspec#L65)

then use this podspec instead in your podfile and see if it solves any problem. Thanks!

**Comment by muxi** [comment]
@lesterpang do you still have the same issue?

**Comment by zhaohuang2016** [comment]
I tried it according to what you said, the terminal display is normal.Thank you for the plan.

Downloading dependencies
Installing !ProtoCompiler (3.5.0)
Installing !ProtoCompiler-gRPCPlugin (1.13.0-dev)
Installing BoringSSL (10.0.4)
Installing Protobuf (3.5.2)
Installing RemoteTest (0.0.1)

So how does the demo modify this configuration?(examples/objective-c/helloworld).
'pod install' does not report an error.

**Comment by muxi** [comment]
OK I'll update the podspec accordingly. Thanks for confirming that. This will be published with next gRPC release (1.13.0).

**Comment by zhaohuang2016** [comment]
Thank you for your help. Thank you very much.

**Comment by zhaohuang2016** [comment]
I just saw a new Release, Release v1.13.0, but when I installed pod install, I still reported an error.
My steps are:
$ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ cd examples/objective-c/helloworld
$ pod install
Terminal display results:
[!] Error installing BoringSSL
[!] /usr/bin/git clone https://boringssl.googlesource.com/boringssl /var/folders/zw/3hktq3jx1f926sty5vmbq5180000gn/T/d20180612-896-1vtkc80 --template= --single-branch --depth 1 --branch version_for_cocoapods_8.0

Cloning into '/var/folders/zw/3hktq3jx1f926sty5vmbq5180000gn/T/d20180612-896-1vtkc80'...
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Failed to connect to boringssl.googlesource.com port 443: Operation timed out

**Comment by muxi** [comment]
Your BoringSSL seems to be reeeeally old... can you get a newer one? Like 10.0.4 or 10.0.5?

**Comment by zhaohuang2016** [comment]
I used demo pod install and then reported an error.
How does the file helloworld.podspec set the address to download BoringSSL?

**Comment by muxi** [comment]
I can think of checking two things:
* Check if your pods are up to date - with `pod update` for example
* Check what version of gRPC you are using. The v1.13.x branch is still RC so Cocoapods might not get you the newest version automatically. If you want to force it, try annotate [this line](https://github.com/grpc/grpc/blob/master/examples/objective-c/helloworld/HelloWorld.podspec#L56) with version number: `ss.dependency "gRPC-ProtoRPC", '1.13.0-pre1'`

**Comment by zhaohuang2016** [comment]
I upgraded the pods. It's OK to try again. Thanks for your help.

**Comment by muxi** [comment]
Cool. Glad it worked out.
