### ISSUE TITLE
grpc async client stuck

### ISSUE THREAD

**Issue by chnex** [grpc/grpc#15322]
### What version of gRPC and what language are you using?
 1.10.0
 
### What operating system (Linux, Windows, …) and version?
 Linux (Ubuntu 16.04)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 5.4.0
 
### What did you do?
I have a grpc c++ client code to connect to a server (external to my code). When the server crashes, my code will detect, restart the server process, and re-create a client object to connect. It works for the first crash. but for the second crash, the client object seems stuck in the first call (I looked at grpc log: the call is invoked, but the message never reaches the server), as well as the later calls. This applies to both async (completion queue receives nothing) and sync calls (stuck). any pointers/helps? Thanks a lot! The server process always use a same unix socket for communication. I delete it every time after detecting the crash and before restarting the server process. 

### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by kpayson64** [comment]
Can you post the client-side logs from when your binary goes down with the environment variables ```GRPC_TRACE=tcp GRPC_VERBOSITY=debug```

**Comment by kpayson64** [comment]
This has been pending a reply for a few months.  Closing issue as stale.
