### ISSUE TITLE
grpc c++ addMetadata doesn't supports colon character in key name

### ISSUE THREAD

**Issue by sebastian-garofalo** [grpc/grpc#15321]
I'm working on a Linux C++ service implementing distributed tracing with Jaeger and need to propagate the request id in my gRPC calls.
Jaeger uses the header key "guid:x-request-id" for that purpose, the problem is that the colon character is considered invalid.

`const std::string GUID_X_REQUEST_ID = "guid:x-request-id";`
`context.AddMetadata(GUID_X_REQUEST_ID, xRequestId);`

`followers-srv-web    | E0509 14:15:18.650934960      28 call.cc:935]                validate_metadata: {"created":"@1525875318.650921365","description":"Illegal header key","file":"src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":4,"raw_bytes":"67 75 69 64 3a 78 2d 72 65 71 75 65 73 74 2d 69 64 'guid:x-request-id'"}
followers-srv-web    | E0509 14:15:18.651030842      28 channel_cc.cc:131]          assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)`

Am I missing something? Is there some way to encode the character or validate_metadata.cc should be updated?

Thanks

**Comment by yashykt** [comment]
You could maybe change the key to something that doesn't have a colon. You have full control over what key and value to use.

**Comment by sebastian-garofalo** [comment]
Well, I can set the name I like, that doesn't means it will work with Jaeger, as that key was defined by them. 

Also HTTP/2 now allows the use of colon in pseudo headers so this would be a bug.
Here is the RFC https://http2.github.io/http2-spec/#PseudoHeaderFields

> HTTP/2 uses special pseudo-header fields beginning with ':' character

**Comment by yashykt** [comment]
Those are pseudo-header fields which need the first character to be ':'
