### ISSUE TITLE
gRPC Python Client Side Fork Support

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#15334]
Currently, the core gRPC library is compatible with fork() in only a limited fashion: to avoid potential issues with shared static state across parent and child processes, fork() must be called before any gRPC connections have been established. See additional documentation in https://github.com/grpc/grpc/blob/master/doc/fork_support.md. 

A number of issues have been reported by users with the use of fork() and the gRPC library, including: https://github.com/grpc/grpc/issues/14892, https://github.com/grpc/grpc/issues/13873, https://github.com/grpc/grpc/issues/8798, https://github.com/grpc/grpc/issues/13412. Typically the problems are reported by users of the wrapped languages (especially Python, in which applications frequently rely on fork() due to limitations on multithreading due to the GIL).

This tracking issue is intended to consolidate these various user reports and also track our work towards improving gRPC's compatibility with fork() in future releases.

Our current plan is to support fork() for gRPC clients with the following semantics: it will be valid for a process to fork() with active channels and on-going RPCs. The parent process will be able to continue using these channels and RPCs with no changes. The child process will not have access to the channels and RPCs created in the parent. The child will be able to establish new gRPC channels and initiate its own RPCs. In other words, after fork(), the parent and child process will have access to entirely "separate" instances of the gRPC library which they can each use independently.

This plan is still in the early stages of design, and the semantics we intend to support may change; this issue will be kept updated with progress and any changes as this work moves forward. Please feel free to use this Github issue to share thoughts on the proposed semantics, additional use cases you would like to see supported, or general comments on the design as more details are added.

Server-side support (e.g., a pre-fork model) will require a separate design and is not yet on the roadmap, but feel free to comment on this issue if you have thoughts or use cases that you would like considered.

**Comment by bo0rsh201** [comment]
Does this plan include php extension or python only? 
Sorry, but it's not clear from the description, because you mention php related issues, but labels include only "lang/Python"

**Comment by ericgribkoff** [comment]
The fix should apply to all wrapped languages, including PHP. I updated the issue label. There will likely be some per language configuration necessary to enable the fix (e.g., setting a build flag to tell core to register atfork handlers to properly clean up before and after the fork syscall), but the fix itself will be in the c-core layer and so available to any wrapped language.

**Comment by bo0rsh201** [comment]
sounds great, thank you

**Comment by evanj** [comment]
Re: server support: I need gRPCs servers to be able to fork() and exec() to do work that then gets captured by the original parent process, without gRPC interfering. We've [run into cases where gRPC logging messages get written to the new stdout/stderr in this subprocess](https://github.com/grpc/grpc/issues/13873#issuecomment-372409083), which causes problems when we then try to use that output.

**Comment by arturgontijo** [comment]
Using:
Ubuntu 16.04
python 3.6.5
grpcio 1.14.2       
grpcio-tools 1.14.1

I'm unable to use os.fork() and subprocess.Popen().
Got `tcp_server_posix.cc:210] Failed accept4: Invalid argument`.

But if I use threading.Thread() that calls subprocess.run() it works!

**Comment by srini100** [comment]
Marking this issues closed. To summarize, release 1.15.0 now  has client side fork() support for gRPC-Python. See [release notes](https://github.com/grpc/grpc/releases) for details. Use case mentioned in https://github.com/grpc/grpc/issues/13873 is now supported.

 @bo0rsh201, note that this is only for gRPC-Python. The fix does not apply to PHP extension.

**Comment by jianlirong** [comment]
@ericgribkoff , 

First of all, I am new to gRPC. So, maybe my question is sort of naive. 

I am wondering whether the plan you mentioned above was accomplished:

_Our current plan is to support fork() for gRPC clients with the following semantics: it will be valid for a process to fork() with active channels and on-going RPCs. The parent process will be able to continue using these channels and RPCs with no changes. The child process will not have access to the channels and RPCs created in the parent. The child will be able to establish new gRPC channels and initiate its own RPCs. In other words, after fork(), the parent and child process will have access to entirely "separate" instances of the gRPC library which they can each use independently._

I am going to use the C++/core APIs. Another question is that: if the above plan has been accomplished, is somewhere I find some sample code to achieve: _the parent and child process will have access to entirely "separate" instances of the gRPC library which they can each use independently_ ? 

Many thanks in advance.

Lirong

**Comment by ericgribkoff** [comment]
@jianlirong The plan mentioned above was accomplished for gRPC Python clients in https://github.com/grpc/grpc/pull/16264. The PR description provides details about how that works, copied here:

> ### gRPC Core's API for fork support
> A process may fork after invoking grpc_init() and use gRPC in the child if and only if the child process first destroys all gRPC resources inherited from the parent process and invokes grpc_shutdown().
> Subsequent to this, the child will be able to re-initialize and use gRPC. After fork, the parent process will be able to continue to use existing gRPC resources such as channels and calls without interference
> from the child process.
> 
> ### gRPC Python behavior at fork()
> To facilitate gRPC Python applications meeting the above constraints, gRPC Python will automatically destroy and shutdown all gRPC Core resources in the child's post-fork handler, including cancelling in-flight calls. From the client's perspective, the child process is now free to create new channels and use gRPC.

If you are planning to use core APIs directly, the contract for core's fork support is that the child process must destroy all of its inherited gRPC objects, triggering a complete grpc library shutdown. Core will ensure that, e.g., cancelling calls in the child process does not write to the wire, so this will not interfere with active calls in the parent process. Achieving gRPC core shutdown in the child is accomplished in the gRPC Python layer by explicitly tracked all user-created channels, then `close()`ing them in the child's post-fork Python handler.

**Comment by jianlirong** [comment]
Got it. Thanks for the reply, @ericgribkoff .

Lirong

**Comment by Chaz6Chez** [comment]
> Marking this issues closed. To summarize, release 1.15.0 now has client side fork() support for gRPC-Python. See [release notes](https://github.com/grpc/grpc/releases) for details. Use case mentioned in #13873 is now supported.
> 
> @bo0rsh201, note that this is only for gRPC-Python. The fix does not apply to PHP extension.

PHP can use dl() to introduce grpc extension, which will be called after fork
