### ISSUE TITLE
Python gRPC and HTTP multiplexing

### ISSUE THREAD

**Issue by bluecmd** [grpc/grpc#15338]
### What version of gRPC and what language are you using?
Protobuf `3.5.1`, gRPC `1.11.0`, Python `3.6.5`
 
### What operating system (Linux, Windows, …) and version?
 `FreeBSD` and `Linux`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 `Python 3`
 
### What did you expect to see?
 I want to be able to serve things like Prometheus metrics or a `/status` page on my gRPC services written in Python.
 
### What did you see instead?
I haven't found any indication that this is possible, so I'm opening this feature request.
When I tried to simply GET / on my gRPC service I got this error:
```
E0511 07:28:56.790308641    2082 http_server_filter.cc:241]  GET request without QUERY
```
Maybe that could be a good point to create a fallback handler for anything that doesn't match what gRPC likes?
 
### Anything else we should know about your project / environment?
In Go, the common approach is to use `cockroachdb/cmux` to do this. [Example](https://github.com/gdm85/grpc-go-multiplex/blob/master/greeter_multiplex_server/greeter_multiplex_server.go).

**Comment by mehrdada** [comment]
There are two separate things here:

- Being able to register a **gRPC handler** to get invoked as a fall back: you can already accomplish this via a server-side interceptor or a `generic_rpc_handler` in gRPC Python.
- Being able to multiple
