### ISSUE TITLE
Build errors when compiling with BUILD_SHARED_LIBS=ON on Windows

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#15333]
### What version of gRPC and what language are you using?

gRPC v1.11.x
C++
 
### What operating system (Linux, Windows, …) and version?

Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Microsoft Visual Studio 15 2017 (aka MSVC++ 14.1 
 
### What did you do?

```console
git clone -b v1.11.x https://github.com/grpc/grpc.git
cd grpc
git submodule update --init --recursive
cmake -H. -B.build -DBUILD_SHARED_LIBS=ON > configure.log 2>&1
cmake --build .build -- /m > build.log 2>&1
```

### What did you expect to see?
 
A successful build.

### What did you see instead?

A number of build errors, see [build.log](https://github.com/grpc/grpc/files/1992454/build.log) for details.

Also see [configure.log](https://github.com/grpc/grpc/files/1992427/configure.log) for the configuration step output.

 
### Anything else we should know about your project / environment?

I do not believe so.

**Comment by coryan** [comment]
> So, what you've done here is try building absolutely everything - 

If there is a different configuration that I should be using to build, please do let me know.

> As for the cmake itself, I am absolutely no expert, and I have no idea how to only build specific
> targets. The goal here would be to only build grpc and not the vast majority of tests.

Presumably, and assuming the gRPC team will be supporting this configuration, you will want the tests to pass also.

> Nonetheless, we are officially not supporting building grpc's C++ layer as a DLL, because this is
> something extremely difficult to do properly.

Whether it is difficult to do or not is somewhat irrelevant, but that is a call that your team can make.  I may escalate this internally because I think it is important.

Meanwhile, please consider adding this information to the documentation describing what compilers and operating systems you support.

Thank you for taking the time to describe why you think DLLs and C++ ABIs are a bad idea.  I was familiar with all the issues, but it is good that you wrote them down for future readers.

**Comment by apolcyn** [comment]
Assigning to myself right now to look into the `ws2_32.dll` link issue
