### ISSUE TITLE
Grpc on one port can't maximize the throughput.

### ISSUE THREAD

**Issue by gongweibao** [grpc/grpc#15348]
On 100Gb network, I create a server to listening on 4 ports and grpc client can reach 3GB+/s throughput.
However, when the server listening on one port, client reaches just 1GB/s throughput, even I set 

```
    args.SetInt(GRPC_ARG_HTTP2_STREAM_LOOKAHEAD_BYTES, 1024*1024*1024);
    args.SetInt(GRPC_ARG_MAX_CONCURRENT_STREAMS, 10);
```

It seems that grpc client can use only one connection concurrently to one port service. Am I right? 

What's the correct way of doing it?

My code is here:

client: [https://github.com/gongweibao/tests/blob/develop/grpc_test/client.cc](https://github.com/gongweibao/tests/blob/develop/grpc_test/client.cc)
server: [https://github.com/gongweibao/tests/blob/develop/grpc_test/server.cc](https://github.com/gongweibao/tests/blob/develop/grpc_test/server.cc)

**Comment by yang-g** [comment]
How about setting your g_thread_num to larger than 1? You are using a
single threaded server.

**Comment by gongweibao** [comment]
`g_thread_num` is set https://github.com/gongweibao/tests/blob/develop/grpc_test/server.cc#L228

**Comment by yang-g** [comment]
It could be useful to know the client/server thread count and message size you used. As I recall, using larger message size over the same connection can result in higher throughput. Also, if you want, I think you can set distinct channel argument when creating multiple channels to create different connections to the same endpoint.

**Comment by gongweibao** [comment]
> It could be useful to know the client/server thread count and message size you used.

Actually, I test 1/2/4 threads in client/server.
And the detailed result is [here](https://github.com/gongweibao/Paddle/blob/c1267a948dfb7fb8174c1f6d4802fceb04b7db06/benchmark/cluster/network/README.md#grpc) with different message size.

> Also, if you want, I think you can set distinct channel argument when creating multiple channels to create different connections to the same endpoint.

I set channels arguments [here]  (https://github.com/gongweibao/tests/blob/develop/grpc_test/client.cc#L165) in distinct thread.

What's the meaning of distinct channel arguments? Could you give me an example?

**Comment by gongweibao** [comment]
It seems that if [ I use more `channel` to send](https://github.com/gongweibao/tests/pull/3/files), the throughput gets much worse.

**Comment by gongweibao** [comment]
https://stackoverflow.com/questions/50301690/how-to-maximize-grpc-throughput/50335737#50335737

**Comment by sreecha** [comment]
>It seems that grpc client can use only one connection concurrently to one port service. Am I right?
Not really. If you create multiple channels (and make sure each channel has atleast one different channel arg), then each channel will create a separate connection.

Here is an example of code that creates 5 channels and forces each one to create a different connection (the code creates a dummy channel arg that is unique per channel)

```C++
  for (i = 0; i < 5; i++) {
    ::grpc::ChannelArguments args;

    // Set a dummy (but distinct) channel arg on each channel so that
    // every channel gets its own connection
    args.SetInt("test_key", i);
    std::shared_ptr<::grpc::Channel> channel =
                ::grpc::CreateCustomChannel(server_address,
                                            ::grpc::InsecureChannelCredentials(),
                                            args);
  }
```

Can you try creating multiple channels like the above and see if it improves the situation?
