### ISSUE TITLE
c# generated Name.Protbuf.cs file misspelled?

### ISSUE THREAD

**Issue by AtosNicoS** [grpc/grpc#15358]
### What version of gRPC and what language are you using?
 1.11.0 c# Nuget Package
 
### What operating system (Linux, Windows, …) and version?
 Windows 10 201803
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio
 
### What did you do?
Generate proto files with the c# proto plugin
 
### What did you expect to see?
 If you generate the proto files you get 2 c# autogenerated classes:
```
Name.Grpc.cs
Name.Protobuf.cs
```
 
### What did you see instead?
 It seems `Protobuf` is missspelled `Protbuf`:
```
Name.Grpc.cs
Name.Protbuf.cs
```

I am not sure if this is intended or known, I just wanted to report it in case nobody did yet spot this.

**Comment by jtattermusch** [comment]
What commands did you run?  AFAIK, we the compiler plugin itself is not adding the suffixes `.Grpc` and `.Protobuf` to the generated files (see for example https://github.com/grpc/grpc/blob/master/examples/csharp/route_guide/generate_protos.bat which generates RouteGuide.cs and RouteGuideGrpc.cs).
Did you perhaps configure your protoc or the plugin to add those suffixes and missspelled `Protbuf` in your script?

**Comment by AtosNicoS** [comment]
Nevermind, the error is on our side. Sorry for that false report. :S
