### ISSUE TITLE
GRPC cross compilation will ignore HAS_EMBEDDED_PROTOBUF if protobuf is detected on the system

### ISSUE THREAD

**Issue by maxw** [grpc/grpc#15353]
### What version of gRPC and what language are you using?
grpc v1.11.0 / c++
 
### What operating system (Linux, Windows, …) and version?
 macOS High Sierra (17.5.0), cross-compiling for iOS 11
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple LLVM version 9.1.0 (clang-902.0.39.1)
 
### What did you do?
I'm cross-compiling grpc/grpc++ for iOS. I've followed the built-in instructions that are included in the Makefile that work perfectly except for the bin targets. They can successfully generate all of the grpc/protobuf libs that I need, however, when generating any grpc binaries, they attempt to link against the osx system protobuf libraries instead of the iOS ones.
 
### What did you expect to see?

I expected make to embed the protobuf.a static library that it just generated locally.

### What did you see instead?

The path to the newly created protobuf.a is never passed to the linker. Instead just "-lprotobuf" is passed which causes the linker to search the host library paths. It finds protobuf.a there, but ignores it because it doesn't have an arm64 slice.
 
### Anything else we should know about your project / environment?
Yes! I've found the cause of the issue, and a fix, but it seems too specific to my use-case, so I'm looking for guidance.

In short, when cross-compiling, HAS_EMBEDDED_PROTOBUF is set to true, which /should/ cause PROTOBUF_DEP to be set to "$(LIBDIR)/$(CONFIG)/protobuf/libprotobuf.a" which would cause the linker to link against the protobuf lib it just compiled.

However, if HAS_SYSTEM_PROTOBUF is set to true, (which is set automatically if protobuf is installed on your system), then the check for HAS_EMBEDDED_PROTOBUF is skipped entirely leaving PROTOBUF_DEP to be blank.

I've been able to work around this by adding the following lines at line 487 in Makefile.template.
```
  ifeq ($(GRPC_CROSS_COMPILE),true)
  # override system libraries if the config requires a custom compiled library
  HAS_SYSTEM_OPENSSL_ALPN = false
  HAS_SYSTEM_OPENSSL_NPN = false
  HAS_SYSTEM_ZLIB = true
  HAS_SYSTEM_PROTOBUF = false
  HAS_SYSTEM_CARES = false
  endif
```
With this in place, everything compiles perfectly. However, it's very specific to my system because I know that iOS supplies libz as a dynamic library.

My guess is that grpc should allow me to override these when cross-compiling, but I'm not sure if that's the best approach / where I would put that logic.

Max

**Comment by nicolasnoble** [comment]
The main idea of the project is to have a few submodules to help the mainline compilation in the general case. In the situation where you are trying to cross compile, these submodules will no longer compile cleanly because, as you said, things are too case-specific. So the best course of action is to clone the repository without submodules, and always use all of the system-wide dependencies.

Does this answer your question ?

**Comment by maxw** [comment]
I'll give this a shot. Thank you!

Max

**Comment by maxw** [comment]
One other quick question for you. Is there a way to instruct gRPC to only build grpc.a and grpc++.a and not all of the other libs/binaries? When cross-compiling I only need those two libraries. I use the host system's installed versions of things like grpc_cpp_plugin because I can't run the cross-compiled binaries locally anyway.

**Comment by maxw** [comment]
Hmmm, I don't think checking out gRPC without submodules is correct. If I don't check out the submodules, gRPC expects all dependencies to be installed on my system so it can link against them. Which will not work because I'm cross-compiling for another architecture.

I really do think embedding protobuf/cares/etc is the right call for cross-compiling.

**Comment by maxw** [comment]
So I guess my original question still stands. Where's the best place to add logic so I can override "HAS_SYSTEM_BLAH" to match the platform I'm compiling for when cross-compiling.
