### ISSUE TITLE
Ruby times out on Travis

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1535]

**Comment by tbetbetbe** [comment]
can you provide a log trace? I don't think this happens all the time, it'd be interesting to know what actually timed out.

**Comment by tbetbetbe** [comment]
When there's a log trace, it goes back to P1

**Comment by murgatroid99** [comment]
I can't find another log of the same failure right now, but I'm pretty sure it was a test runner-level timeout. The trace showed that the tests passed, but `run_tests.py` reported that the test suite as a whole timed out.

**Comment by ctiller** [comment]
Any easy way that the tests can be separated into different 'binaries'?

**Comment by tbetbetbe** [comment]
There's no need for that.
There are already 4 test suites.
The default behaviour is run each one after the other, running the fastest first first and only running the later ones if the earlier ones succeed.

**Comment by ctiller** [comment]
The usefulness would be that they'd run in parallel on Travis (maybe
speeding things up), and there'd be a little more data available on which
test got stuck.
It'd probably also be useful to change run_tests.py to try and offer up
logs when we hit the timeout case.

**Comment by ctiller** [comment]
360.21s$ ./tools/run_tests/run_tests.py -l $TEST -t -j 16 -c $CONFIG -s 4.0
START: make
PASSED: make [time=7.5sec]
START: tools/run_tests/build_ruby.sh
PASSED: tools/run_tests/build_ruby.sh [time=49.5sec]
START: tools/run_tests/run_ruby.sh
TIMEOUT: tools/run_tests/run_ruby.sh
FAILED: Some tests failed

**Comment by tbetbetbe** [comment]
This is blocked on getting logs showing what/where tests are timing out, and will best be addressed by adding those the issue.

**Comment by tbetbetbe** [comment]
Closing this as #1568 is the same and includes test output.
