### ISSUE TITLE
Providing cares as package leads to undefined symbols during linking.

### ISSUE THREAD

**Issue by Ozaq** [grpc/grpc#15375]
### What version of gRPC and what language are you using?
 1.11.1 and 1.11.0, tested on both
 
### What operating system (Linux, Windows, …) and version?
Linux, Debian 9.4
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 6.4
 
### What did you do?
Build grpc with cmake and provide c-ares as package, then link against grpc and cares static libs.
 
### What did you expect to see?
Linking to grpc succeeds.
 
### What did you see instead?
Unresolved symbols:
```
In function `grpc_resolver_dns_ares_init()':
dns_resolver_ares.cc:(.text+0x11e1): undefined reference to `address_sorting_init'
...

 In function `grpc_resolver_dns_ares_shutdown()':
dns_resolver_ares.cc:(.text+0x12d9): undefined reference to `address_sorting_shutdown'
...
In function `grpc_cares_wrapper_address_sorting_sort(grpc_lb_addresses*)':
grpc_ares_wrapper.cc:(.text+0x28d): undefined reference to `address_sorting_rfc_6724_sort'
```
I can see those functions are implemented in thrid_party_cares and the actual cares lib is located at third_party/cares/cares/. 

It seems that providing cares as package does exclude the wrapping code from compilation. Unfortunately I cannot simply disable the use of cares with the cmake build (Or am I overlooking an option?) I know I could define GRPC_ARES=0 but I would have to patch the existing cmake files to pass this on.

### Note
I have also tested this on windows and there i can link the same application just fine, I did not look enough into it to understand why this works (most likely the calls are only used on linux)

**Comment by Ozaq** [comment]
Never mind, I was missing a lib :)

**Comment by klase73** [comment]
Same error here -- which lib was missing, please?
