### ISSUE TITLE
client to ruby server has failures

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#1537]
ruby->ruby pingpong gave the following failure; other clients to ruby server also failing

+ gcloud compute --project stoked-keyword-656 ssh --zone asia-east1-a grpc-docker-testclients --command 'sudo docker run grpc/ruby bin/bash -l -c '\''ruby /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb --use_test_ca --use_tls --server_host_override=foo.test.google.fr --server_host=10.240.108.167 --server_port=8060 --test_case=ping_pong'\'''
  PID TTY          TIME CMD
 4102 ?        00:00:00 interop_test_ru
+ sleep 10
Warning: Permanently added '104.155.208.189' (ECDSA) to the list of known hosts.
Using /usr/local/rvm/gems/ruby-2.1.5
+ for x in '{0..5}'
+ ps -p 4102
  PID TTY          TIME CMD
 4102 ?        00:00:00 gcloud
+ sleep 10
stdin: is not a tty
 INFO  Object : ... connecting securely to 10.240.108.167:8060
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:126:in `join': No live threads left. Deadlock? (fatal)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:126:in `each_queued_msg'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:264:in `each'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:264:in `ping_pong'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:371:in `call'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:371:in `main'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:374:in `<main>'
D0508 06:54:48.147966635       1 iomgr.c:107] Waiting for 1 iomgr objects to be destroyed
+ for x in '{0..5}'
+ ps -p 4102
  PID TTY          TIME CMD
 4102 ?        00:00:00 gcloud
+ sleep 10
D0508 06:54:58.147979794       1 iomgr.c:130] Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
+ for x in '{0..5}'
+ ps -p 4102

**Comment by tbetbetbe** [comment]
Closing this after discussing this earlier today.  The failure was a transient issue.
