### ISSUE TITLE
PHP: Autoload failure for 'Grpc\InterceptorChannel'

### ISSUE THREAD

**Issue by chingor13** [grpc/grpc#15387]
### What version of gRPC and what language are you using?
 PHP, dev-master
 
### What operating system (Linux, Windows, …) and version?
Linux (Debian 9) 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
n/a 
 
### What did you do?
I'm implementing an interceptor for PHP:
```php
$channel = new Channel('localhost' . $this->port, [
     'credentials' => ChannelCredentials::createInsecure()
]);
$interceptor = new TraceInterceptor();

// raises class not found error in lib/Grpc/Interceptor.php:81
$channel = Interceptor::intercept($this->channel, $interceptor);
```

The `Grpc\InterceptorChannel` class is defined under `lib/Grpc/Internal/InterceptorChannel.php` but composer autoloading is looking for it under `lib/Grpc/InterceptorChannel.php`. The unit tests pass because the test file explicitly calls `require` on the `lib/Grpc/Internal/InterceptorChannel.php` file.
 
### What did you expect to see?
No error message.
 
### What did you see instead?
`Error: Class 'Grpc\InterceptorChannel' not found`

**Comment by ZhouyihaiDing** [comment]
If keep using `require grpc/grpc` with `composer`, the only solution I know is either move `InterceptorChannel.php` out of `Internal/`, or change the namespace of the `InterceptorChannel` from `Grpc` to `Internal\Grpc`.

**Comment by ZhouyihaiDing** [comment]
PR #15399 is supposed to work. Can you please verify that? Thanks!

**Comment by chingor13** [comment]
@ZhouyihaiDing The fix works. https://circleci.com/gh/census-instrumentation/opencensus-php/1583.

However, it's a bit of a bummer that there's no `ChannelInterface` because we do all supplying a channel instance through `google/gax` and `google/cloud` libraries and to document it, we have to document `Channel|InterceptorChannel` throughout all of the documentation and remove any type hinting for `Channel` arguments.

It's really hard to introduce the `ChannelInterface` with the C extension backwards-compatibility, but WDYT about making `InterceptorChannel` inherit from `Channel` (even though every method is replaced). Then we wouldn't need to make the documentation changes and if users only use the `Interceptor::intercept` factory, the details of the `InterceptorChannel` are hidden. Perhaps it's worth discussing offline with @michaelbausor and @stanley-cheung.

**Comment by chingor13** [comment]
Closing as this issue is fixed in master.

**Comment by ZhouyihaiDing** [comment]
Make `InterceptorChannel extends \Grpc\Channel` in PR #15413.

**Comment by chingor13** [comment]
@ZhouyihaiDing You should also be able to restore the typehint for `Channel` here: https://github.com/grpc/grpc/blob/master/src/php/lib/Grpc/BaseStub.php#L43 and you shouldn't need to document `InterceptorChannel` or need `is_a(InterceptorChannel)`
