### ISSUE TITLE
Bazel test flake: " assertion failed: error == GRPC_ERROR_NONE"

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#15427]
https://source.cloud.google.com/results/invocations/1e6d8a74-2a0a-4be9-8226-0b6f2a6cea16/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_http_proxy_test@no_logging@poller%3Depollex/log

Multiple tests flaked for the same reason.

**Comment by sreecha** [comment]
Haven't seen this issue in a while
