### ISSUE TITLE
Will C# sdk support "grpc.keepalive_time_ms" option?

### ISSUE THREAD

**Issue by goldenbull** [grpc/grpc#15423]
https://github.com/grpc/grpc/blob/6a1bf82ea9ac1b1d36a6d0ee48299a978a8fc964/include/grpc/impl/codegen/grpc_types.h#L222

and other two options:  `"grpc.keepalive_timeout_ms"` and `"grpc.keepalive_permit_without_calls"`

**Comment by jtattermusch** [comment]
All the channel arguments are "supported" in the sense that you can create any channel option by e.g. 
`new ChannelOption("grpc.keepalive_time_ms", yourValue)`  and then pass it to channel constructor.

**Comment by JamesXiao** [comment]
Hi @jtattermusch :
I tried this setting about keep alive, but the connection still get closed after idle for like 30 minutes (should not happen if the keep alive ping have bean properly set), and the disconnect event on channel is not triggered, I can only detect the disconnection till a new request is fired.

What I encountered is very similar to this thread:
https://groups.google.com/forum/#!topic/grpc-io/doa2tBP0HK0

I am not sure if there is already a github issue raised by the original author, so I comment here.

**Comment by JamesXiao** [comment]
yes, it works now, with 
GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS set to 1
and
GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA set to 0
