### ISSUE TITLE
Crash due to grpc clock_type assertion failure: a.clock_type == b.clock_type at src/core/lib/gpr/time.cc:167

### ISSUE THREAD

**Issue by anirbanroy33** [grpc/grpc#15430]
### What version of gRPC and what language are you using?
v1.10.1
 
### What operating system (Linux, Windows, …) and version?
 Linux 4.1.15

### What runtime / compiler are you using (e.g. python version or version of gcc)
 GCC Version 5.2.1
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Process starts GRPC server for messaging. And no issues with grpc initialization.

Happens intermittently, not reproducible at will.  This issue started happening mainly since the grpc 1.9.0.pre1 introduced. The 1.10 release has fixed many issues including memory leak in 1.9.0. Hence it was upgraded to 1.10 grpc to address it but didn't help.

It is likely a random memory corruption issue - since the clock_type assert is comparing two values that are created by the grpc library and should always both be of type MONOTONIC.

### What did you expect to see?
Successful IPC messaging without intermittent crash.
 
### What did you see instead?
2018-04-27 09:08:55.643+00:00 btled[1094]: E0427 09:08:55.620795474    1235 time.cc:167]                assertion failed: a.clock_type == b.clock_type
2018-04-27 09:08:57.144+00:00 systemd[1]: btled.service: Main process exited, code=killed, status=6/ABRT
2018-04-27 09:08:57.147+00:00 systemd[1]: btled.service: Unit entered failed state.
2018-04-27 09:08:57.149+00:00 systemd[1]: btled.service: Failed with result 'signal'.
2018-04-27 09:08:57.496+00:00 systemd[1]: btled.service: Service hold-off time over, scheduling restart.
2018-04-27 09:08:57.498+00:00 systemd[1]: Stopped Btle Service.
2018-04-27 09:08:57.502+00:00 systemd[1]: Started Btle Service.
2018-04-27 09:08:57.503+00:00 systemd[1]: Stopping Bluetooth service...
2018-04-27 09:08:57.657+00:00 systemd[1]: Stopped Bluetooth service.
2018-04-27 09:08:57.675+00:00 systemd[1]: Starting Bluetooth service...
2018-04-27 09:08:57.788+00:00 systemd[1]: Started Bluetooth service.
2018-04-27 09:09:01.380+00:00 btled[1911]: Mailbox Action: Process Message
2018-04-27 09:09:04.649+00:00 btled[1016]: Last message 'Mailbox Action: Proc' repeated 1 times, suppressed by syslog-ng on SS-FCH2142D00V

Operating system: Linux
                  0.0.0 Linux 4.1.15-142-224373-g07934fe-dirty #1 SMP PREEMPT Wed Apr 18 20:54:53 UTC 2018 armv7l
CPU: arm
     ARMv1 ARM Cortex-A9 features: half,thumb,fastmult,vfpv2,edsp,neon,vfpv3,tls
     4 CPUs

GPU: UNKNOWN

Crash reason:  SIGABRT
Crash address: 0x446
Process uptime: not available

Thread 2 (crashed)
 0  libc-2.23.so + 0x2bf10
     r0 = 0x00000000    r1 = 0x000004d3    r2 = 0x00000006    r3 = 0x75b99800
     r4 = 0x00000002    r5 = 0x75b99340    r6 = 0x75b98aa0    r7 = 0x0000010c
     r8 = 0x75b98cd8    r9 = 0x00000000   r10 = 0x0000007d   r12 = 0x00000000
     fp = 0x00000000    sp = 0x75b98a98    lr = 0x764df330    pc = 0x764ddf10
    Found by: given as instruction pointer in context
 1  libgrpc.so.6.0.0 + 0xc9f2a
     sp = 0x75b98b38    pc = 0x76bc8f2c
    Found by: stack scanning
 2  0x76afeffe
     sp = 0x75b98b4c    pc = 0x76aff000
    Found by: stack scanning
 3  ld-2.23.so + 0x1007a
     sp = 0x75b98b6c    pc = 0x76f3407c
    Found by: stack scanning
 4  libc-2.23.so + 0x5c2e
     sp = 0x75b98b84    pc = 0x764b7c30
    Found by: stack scanning
 5  ld-2.23.so + 0x1780a
     sp = 0x75b98b9c    pc = 0x76f3b80c
    Found by: stack scanning
 6  libgrpc.so.6.0.0 + 0xb827e
     sp = 0x75b98bb4    pc = 0x76bb7280
    Found by: stack scanning
 7  libgrpc.so.6.0.0 + 0xd48fa
     sp = 0x75b98bb8    pc = 0x76bd38fc
    Found by: stack scanning
 8  libgrpc.so.6.0.0 + 0x440de
     sp = 0x75b98be4    pc = 0x76b430e0
    Found by: stack scanning
 9  libgrpc.so.6.0.0 + 0x4452a
     sp = 0x75b98c38    pc = 0x76b4352c
    Found by: stack scanning
10  libgrpc.so.6.0.0 + 0x4fc56
     sp = 0x75b98c58    pc = 0x76b4ec58
    Found by: stack scanning
11  libgrpc.so.6.0.0 + 0x50832
     sp = 0x75b98ca0    pc = 0x76b4f834
    Found by: stack scanning
12  libgrpc.so.6.0.0 + 0xc046e
     sp = 0x75b98d08    pc = 0x76bbf470
    Found by: stack scanning
13  libgrpc.so.6.0.0 + 0x50636
     sp = 0x75b98d0c    pc = 0x76b4f638
    Found by: stack scanning
14  libgrpc.so.6.0.0 + 0xb7726
     sp = 0x75b98d28    pc = 0x76bb6728
    Found by: stack scanning
15  libpthread-2.23.so + 0x637a
     sp = 0x75b98d48    pc = 0x765f837c
    Found by: stack scanning

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ncteisen** [comment]
Can you create a simple repro case?

**Comment by anirbanroy33** [comment]
As mentioned earlier, it occurs randomly without any known triggers.

**Comment by ncteisen** [comment]
Without a good repro (even if it is not deterministic), there is very little we can do.

Please reopen if you are able to produce one
