### ISSUE TITLE
C#/Windows: Symbols (PDBs) for native gRPC DLLs are not published

### ISSUE THREAD

**Issue by smflorentino** [grpc/grpc#15437]
### What version of gRPC and what language are you using?
Latest
 
### What operating system (Linux, Windows, …) and version?
Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
C#
 
The native DLLs (`grpc_csharp_ext.x86.dll`,`grpc_cshart_ext.x64.dll`) in the `Grpc.Core` NuGet do not have their symbols packaged in the NuGet.

This makes analyzing memory dumps and performance difficult. Can the PDB files from the builds be packaged alongside the DLLs?

**Comment by jtattermusch** [comment]
FYI I had some work in progress here https://github.com/grpc/grpc/pull/14908/files

**Comment by jtattermusch** [comment]
We just push a pre-release package of Grpc.Core that uses grpc_csharp_ext.dll built with RelWithDebInfo configuration. The corresponding PDB can be found in this nuget package: https://www.nuget.org/packages/Grpc.Core.NativeDebug/1.13.0-pre1
