### ISSUE TITLE
grpc-ruby can drop its googleauth dependency, all in favor?

### ISSUE THREAD

**Issue by ganmacs** [grpc/grpc#15467]
I'd like to drop the googleauth dependency from grpc-ruby in this [PR](https://github.com/grpc/grpc/pull/15356) because grpc-ruby doesn't need to depend on googleauth. but as @apolcyn says (https://github.com/grpc/grpc/pull/15356#discussion_r188033395), This is a breaking change for the people who is relying on googleauth being in there transitive dependencies.

Thanks.
https://github.com/grpc/grpc/pull/15356

**Comment by nicolasnoble** [comment]
Unless grpc-ruby exposes the package's API explicitly somehow, I don't believe transitive dependencies are part of any defined behavior, and that removing or altering them shouldn't be considered a breaking change. We've had similar policies in the past with Python. CC @nathanielmanistaatgoogle to confirm.

If you need a package, you should explicitly depend on it.

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble: agreed and yes, this is how it has worked for gRPC Python.

**Comment by mehrdada** [comment]
I also concur with the above opinions, as long as we make sure to add a warning to release notes to ensure users are aware of the change, [like we did when we dropped `protobuf` dependency from `grpcio` in Python recently](https://github.com/grpc/grpc/releases/tag/v1.12.0).

**Comment by dazuma** [comment]
SGTM from ruby-cloud.

**Comment by ganmacs** [comment]
It's done. Thank you for comments. https://github.com/grpc/grpc/pull/15356
