### ISSUE TITLE
GRPC fails to build on Windows using cmake/Visual Studio

### ISSUE THREAD

**Issue by maxw** [grpc/grpc#15472]
### What version of gRPC and what language are you using?
 v1.11.0 / c++
 
### What operating system (Linux, Windows, …) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 15 2017 (latest install of Visual Studio 2017 Community w/ C++ tools)
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I followed the INSTALL instructions:

```
> md .build
> cd .build
> cmake .. -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Release
// At this point I open Visual Studio and build grpc/grpc++ as these are the only two pieces I need.
```
 
### What did you expect to see?
 Build successful / no errors
 
### What did you see instead?
Lots of errors like this:
`Error C2220 warning treated as error - no 'object' file generated	ssl c:\users\max\documents\grpc\third_party\boringssl\ssl\ssl_lib.cc	3461`

It outputs grpc.lib/grpc++.lib, but my own cmake project bails when building grpc as a dependency because it outputs errors.

I would just disable treating warnings as errors, but I imagine there's a good reason that's turned on for boringssl.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
nope

**Comment by nicolasnoble** [comment]
Try turning off treating warnings as errors. You're building BoringSSL as a dependency, and it doesn't build cleanly without warnings under Windows.

**Comment by jtattermusch** [comment]
there shouldn't be any errors: we are testing VS2017 build continuously and the tests are passing very consistently:
https://source.cloud.google.com/results/invocations/4b8299f2-06e5-4cbb-989e-81e8c54f24ab/targets
Can't there be a problem in your own cmake file? (whether your cmake file can influence the grpc build also depends on the way you are including grpc as a dependency).

btw, the error msg you provided is not that useful without the actual warning (that's also appears in your log, but is not mentioned here).

**Comment by maxw** [comment]
After running into the error in my cmake file, I tried building it by hand using the instructions from INSTALL. I'm using the exact instructions I put into the bug report above in vanilla gRPC checkd out at the v1.11.0 tag with all submodules.

Also, I assume the warning is "no 'object' file generated" meaning that there are a bunch of cc files that don't have corresponding .o files which I assume means that on windows those source file does not produce any symbols.

I'll be back at my Windows PC later this week. I'm curious to see why ssl_lib.cc in boringssl wouldn't produce any symbols when building for Windows.

**Comment by nicolasnoble** [comment]
> Also, I assume the warning is "no 'object' file generated" meaning that there are a bunch of cc files that don't have corresponding .o files which I assume means that on windows those source file does not produce any symbols.

That's not what this means at all. This is the general message from Visual Studio that says something went wrong compiling this one file.

**Comment by maxw** [comment]
I'm on a different computer this week. I did this in a fresh grpc repo and it worked fine... Going to debug more when I get back on my other computer.
