### ISSUE TITLE
SSL/TSI data corruption in native C++ client on Windows

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#15506]
### What version of gRPC and what language are you using?
Client - v1.12.0, C++, on Windows
Server - v1.12.0, C#, on WIndows
 
### What operating system (Linux, Windows, …) and version?
Client - Windows 7 x86, 1-core CPU, 2GB RAM
Server -  Windows 10, version 10.0.17134.48
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Client - built on Windows 10, using `CMAKE_GENERATOR="Visual Studio 14 2015"`
Server - Downloaded from NuGet
 
### What did you do?
General code behavior:
1. The client calls a RPC that opens a server-stream (`stream 1`), and keeps it open.
2. The client initiates a threads that endlessly reads messages from `stream 1`, until `Read()` fails.
3. After a short while, the client calls another server-streaming RPC call (different function) and reads information from `stream 2`.

```C++
if (!stream1->Read(&msg))
{
	throw RpcException("Failed reading from stream");
}
```

Symptoms - On a **specific** Windows 7 x86 machine, running in a remote virtualization environment, there appears to be a race condition where `stream 1` fails shortly after the server begins to send response messages over `stream 2`.
1. When the client calls another RPC (different function) that also opens a server-stream (`stream 2`), it results `stream 1` `Read()` operation to fail (status `false`) after a short while, and `stream 1` closes.
2. `stream 1` fails only after the server begins to send messages over `stream 2`
3. `stream 1` fails even before the client begins to read from `stream 2`

Setting `GRPC_TRACE=all` and `GRPC_VERBOSITY=INFO` solves this issue - what proves this is a race.
Using `GRPC_TRACE=all` and `GRPC_VERBOSITY=ERROR` shows the following error message when `stream 1` fails:
> E0523 00:50:45.243000000  2976 ssl_transport_security.cc:453] Corruption detected.
E0523 00:50:45.243000000  2976 ssl_transport_security.cc:429] error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E0523 00:50:45.243000000  2976 ssl_transport_security.cc:429] error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC
E0523 00:50:45.243000000  2976 secure_endpoint.cc:181] Decryption error: TSI_DATA_CORRUPTED
E0523 00:50:45.243000000  2976 ssl_transport_security.cc:480] SSL_write failed with error SSL_ERROR_SSL.

It doesn't happen on any other machine, and doesn't happen if this VM is launched in the same LAN as the server.

@jtattermusch - May be related to #8673? A mix-up of different `BoringSSL` versions?
 
### What did you expect to see?
This corruption shouldn't have happened. Another clone VM that runs right next to the faulty one,  on the same ESX server and the same VLAN, behaves normally (no corruption)
 
### What did you see instead?
SSL corruption resulting stream failure
 
### Anything else we should know about your project / environment?
This issue appears only on a **specific** Windows 7 x86 machine, running in a remote virtualization environment. It is **reproducible**. It doesn't happen on any other virtual machine, local or remote (even one generated form the same clone and has the same virtual hardware including VLAN and host).

**Comment by jtattermusch** [comment]
As this happen only on a specific VM machine, I'm not sure how to reproduce on my side.
