### ISSUE TITLE
problem with reading meta data from clientcontext

### ISSUE THREAD

**Issue by aureus5** [grpc/grpc#15509]
### What version of gRPC and what language are you using?
 The version from github(2018.May), protobuf 3.5.1, cpp
 
### What operating system (Linux, Windows, …) and version?
 ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.4.1
 
### What did you do?
I tried to set clientcontext meta data and read it from server.

Client side:
```
grpc::ClientContext context;
context.AddMetadata("uuid", uuid);
```

Server side:
```
        std::string uuid;
        std::multimap<grpc::string_ref, grpc::string_ref>::const_iterator data_iter = metadata.find("uuid");
         if(data_iter != metadata.end()) {
             grpc::string_ref uuid_ref = data_iter->second;
             uuid = uuid_ref.data();
             std::cout << "client metadata for foo: " << data_iter->second << std::endl;
             std::cout << "client metadata for foo: " << (data_iter->second).data() << std::endl;
         }
        else {
             std::cout << "RPC in Service-manager: uuid sent from service app not found\n";
         }
        std::cout<<"$$$ debug: uuid="<<uuid<<"\n";
```
 
### What did you expect to see?
 I expect that` (data_iter->second).data()` would return 

> "uuiddiviceID"

, instead it return 

> uuiddiviceID@ttrailers@content-typeapplication/grpc@
> identity,gzip"

 
### What did you see instead?

Here is the output:
```
client metadata for foo: uuiddiviceID
client metadata for foo: uuiddiviceID@ttrailers@content-typeapplication/grpc@
identity,gzip
$$$ debug: uuid=uuiddiviceID@ttrailers@content-typeapplication/grpc@
identity,gzip
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
I tried a few other ways to iterate through the multimap and all have the same issue.

**Comment by amanand** [comment]
Noticing similar issue. Please share any available updates on this.

**Comment by ncteisen** [comment]
It is not safe to print the data() from a string_ref since there is no null
terminator. try convert to string first:

string s((data_iter->second).data(),  (data_iter->second).length());
cout << s;

**Comment by amanand** [comment]
Thanks it worked.
