### ISSUE TITLE
Node RPC server cannot recover from malformed requests

### ISSUE THREAD

**Issue by vgatto** [grpc/grpc#1551]
In testing my Swift client against a node server, I started by sending an empty request (i.e. no serialized proto, NOT just an empty well-formed serialized message) to verify that it hit the server. As expected, the server was unable to deserialize the empty request and failed with an exception thrown from within bytebuffer. This renders the server unresponsive to any further requests.

The stack trace looks like:
```
/Users/vgatto/dev/springful/springful/backend/node_modules/protobufjs/node_modules/bytebuffer/dist/ByteBufferNB.js:322
            throw TypeError("Illegal buffer");
                  ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (/Users/vgatto/dev/springful/springful/backend/node_modules/protobufjs/node_modules/bytebuffer/dist/ByteBufferNB.js:322:19)
    at Function.Message.decode (/Users/vgatto/dev/springful/springful/backend/node_modules/protobufjs/dist/ProtoBuf.js:2223:85)
    at Object.deserialize (/Users/vgatto/dev/springful/springful/backend/node_modules/grpc/src/common.js:53:16)
    at /Users/vgatto/dev/springful/springful/backend/node_modules/grpc/src/server.js:357:31
```

Wrapping the call to `handler.deserialize` in `server.js` and making the appropriate call to `handleError` fixes this, but I'm not certain if this is the best place for such error handling.

**Comment by murgatroid99** [comment]
That probably is the right way to deal with it. It should probably respond with the status INVALID_ARGUMENt (3). I think I'll also want to add similar handling on the client side.

**Comment by mustafamamun** [comment]
Hi, I am having the same problem even though I am pushing protobuf encoded data to kafka. I am having this problem when I am trying to read it from other side. can u guide me  some suggestion.
