### ISSUE TITLE
grpc php client "Connect Failed" code 14

### ISSUE THREAD

**Issue by gertcuykens** [grpc/grpc#15522]
php cli
```docker
FROM php:alpine
WORKDIR /root
RUN apk --no-cache --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add \
  ca-certificates g++ git make autoconf automake curl libtool \
  zlib-dev musl-dev openssl-dev c-ares-dev
COPY ./grpc ./grpc
RUN cd grpc/third_party/protobuf; ./autogen.sh && ./configure && make install
RUN cd grpc; make grpc_php_plugin
RUN cp grpc/bins/opt/grpc_php_plugin /usr/local/bin
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
RUN pecl install grpc
RUN docker-php-ext-enable grpc
RUN cd /usr/local/bin; curl -sS https://getcomposer.org/installer | php
CMD [ "php", "--version" ]
```
composer.json
```json
{
  "name": "grpc/grpc-test",
  "description": "gRPC PHP test",
  "require": {
    "grpc/grpc": "^v1.12.0",
    "google/protobuf": "^v3.5.2"
  },
  "require-dev": {
    "phpunit/phpunit": "^v7.1.5"
  }
}
```
I don't think master is currently working for php?
Please try to use the docker container above that compiles master and try to make a php client work with any go grpc service. 

Example repo https://github.com/fho/grpc_issue_13474 that you can slightly modify to test the docker container above.

No matter what I try only my go clients work. When I try a php client i get "Connect Failed" code 14 from php.

**Comment by ZhouyihaiDing** [comment]
Hi.
I see you install grpc by pecl. That is the release version, which is `1.12.0`
```
bash-4.3# php -d extension=grpc.so --re grpc | head -1
Extension [ <persistent> extension #34 grpc version 1.12.0 ] {
```

I also [build grpc php from source](https://github.com/grpc/grpc/tree/master/src/php#build-from-source), and it runs well.
```
bash-4.3# php -d extension=grpc.so --re grpc | head -1
Extension [ <persistent> extension #34 grpc version 1.13.0dev ] {
bash-4.3# ./run_greeter_client.sh 
Hello world
```

Is it possible you run go server and client outside of the docker container, and run php client inside the docker container, but forget to export the port? 

I didn't see the failure. I run both golang and php inside the container and all steps are shown below if you are interested:
Dockerfile:
```
FROM php:alpine
WORKDIR /root
RUN apk --no-cache --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add \
  ca-certificates g++ git make autoconf automake curl libtool \
  zlib-dev musl-dev openssl-dev c-ares-dev
RUN cd /usr/local/bin; curl -sS https://getcomposer.org/installer | php
```
Install Golang inside docker container and run server:
```
# Before install go, run all commands in https://hub.docker.com/r/frolvlad/alpine-glibc/~/dockerfile/, because golang needs.
glibc in alpine.
$ wget https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz
$ tar -C /usr/local -xzf go1.10.2.linux-amd64.tar.gz 
$ export PATH=$PATH:/usr/local/go/bin
$ mkdir $HOME/go
$ export GOPATH=$HOME/go
$ cd $HOME/go
$ go get -u google.golang.org/grpc
$ cd src/google.golang.org/grpc/examples/helloworld/
$ go run greeter_server/main.go
```
Install gRPC-PHP from the source:
```
$ git clone https://github.com/grpc/grpc
$cd grpc
$ git submodule update --init
# install protobuf
$ cd third_party/protobuf
$ ./autogen.sh
$ ./configure
$ make -j8
$ make install
cd ../..
#install grpc
$ make -j8
$ sudo make install
```
Run gRPC-PHP client
```
$ cd grpc/example/php
$ ./greeter_proto_gen.sh
$ ./run_greeter_client.sh
```

**Comment by gertcuykens** [comment]
Thank you for your reply because I was stuck :) My make file looks something like this, so i assume my ports are ok and published, I also test my grpc service with grpcurl to make sure it's available. Can you try outside the docker container please?

Doh! I was compiling the whole thing for nothing XD now i realise I am using pecl instead of using the compiled grpc.so version...
 
```
update:
	git submodule update --remote --merge

build: TAG=php
build:
	docker build -t grpc-test:$(TAG) .

run1: CMD=php /usr/local/bin/composer.phar install
run1: TAG=php
run1:
	docker run --rm -it -v $(PWD):/root grpc-test:$(TAG) $(CMD)

run2: CMD=protoc -I . grpc.proto --php_out=. --grpc_out=. --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin
run2: TAG=php
run2:
	docker run --rm -it -v $(PWD):/root grpc-test:$(TAG) $(CMD)

run3: TAG=latest
run3:
	docker run --rm -it -p 8080:8080 grpc-test:$(TAG) $(CMD)

run4: CMD=php -S 0.0.0.0:8081
run4: TAG=php
run4:
	docker run --rm -it -v $(PWD):/root -p 8081:8081 grpc-test:$(TAG) $(CMD)	

test:
	grpcurl -plaintext localhost:8080 list

```

**Comment by ZhouyihaiDing** [comment]
By outside of the container, which part do you mean need to be outside? Server or the client?

**Comment by ZhouyihaiDing** [comment]
Oh I get you. I will try to see if I can reproduce it.

**Comment by gertcuykens** [comment]
Once the server and the client each run in their own container and can communicate which each other by publishing their port you can be certain that does containers can be used in let say kubernetes. But right now for me on the php client container publishing a port is not enough?

**Comment by ZhouyihaiDing** [comment]
It sounds like the port issue to me. I am not familiar with docker. For the container with tag `PHP`, should you also publish the port `8080`? Can request from this container send out through `8080`?

I haven't try 2 containers yet. But within the same container, PHP client and golang server works fine, as well as the php with server mode:
`php -d extension=grpc.so -S 0.0.0.0:8081`
`
```
bash-4.3# curl 0.0.0.0:8081/greeter_client.php
Hello world
```

**Comment by gertcuykens** [comment]
Normally not, else you wouldn't be able to do for example get request from inside your app or container for example curl https://google.com

**Comment by gertcuykens** [comment]
Getting closer :)
```
~ # grpcurl -plaintext localhost:8080 list
Failed to dial target host "localhost:8080": dial tcp 127.0.0.1:8080: connect: connection refused
~ # grpcurl -plaintext 0.0.0.0:8080 list
Failed to dial target host "0.0.0.0:8080": dial tcp 0.0.0.0:8080: connect: connection refused
~ # grpcurl -plaintext 127.0.0.1:8080 list
Failed to dial target host "127.0.0.1:8080": dial tcp 127.0.0.1:8080: connect: connection refused
~ # grpcurl -plaintext host.docker.internal:8080 list
grpc.reflection.v1alpha.ServerReflection
grpc_test.Example
~ #
```

**Comment by gertcuykens** [comment]
Alleluia its working! In the php file i needed to connect to host.docker.internal:8080 and start the php server as php -S 0.0.0.0:8081
