### ISSUE TITLE
[ruby] can't build grpc 1.1x with gcc 8.x

### ISSUE THREAD

**Issue by mrohnstock** [grpc/grpc#15520]
### What version of gRPC and what language are you using?
 
gRPC 1.11.x with ruby
 
### What operating system (Linux, Windows, …) and version?

archlinux on armv7l
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc version 8.1.0 (GCC)
ruby 2.3.7p456 (2018-03-28 revision 63024) [armv7l-linux-eabihf]

### What did you do?

gem install grpc -v 1.11.1

and

gem install grpc -v 1.12.0
 
### What did you expect to see?

successful build
 
### What did you see instead?
 
```
third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
third_party/cares/cares/ares_parse_ptr_reply.c:134:11: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
```
 
### Anything else we should know about your project / environment?

nothing

**Comment by toanju** [comment]
https://github.com/grpc/grpc/pull/14452 is open for quite some time and fix at least the core parts

**Comment by patrick-kings** [comment]
do make CXXFLAGS="-Wno-error=class-memaccess -Wno-error=ignored-qualifiers -Wno-error=stringop-truncation" CFLAGS="-Wno-error=class-memaccess -Wno-error=ignored-qualifiers -Wno-error=stringop-truncation"
