### ISSUE TITLE
Node RPC server request lifecycle hooks?

### ISSUE THREAD

**Issue by vgatto** [grpc/grpc#1552]
Is there a way to hook into the request lifecycle?  Currently, I implement logging within my RPC handlers but that has the following limitations:
- If a request is cannot be deserialized, the handler is never called and there is no log entry for it.
- The handler logs success prior to response serialization or ack from the client.
- You cannot handle requests for unexpected services or methods (just to log that they occurred, so that you can try to figure out why).

**Comment by murgatroid99** [comment]
I think a good way to do this would be with events that the server emits and the user can set up handlers for. It seems like, for this issue, we would want events for `"invalidArgument"`, `"callCompleted"`, and `"notFound"`.

**Comment by vgatto** [comment]
We also would very like to be able to measure end-to-end timing, so we might need some kind of request context object.

**Comment by murgatroid99** [comment]
As a minor update, I think that this is a good idea, but I am not exactly sure how to best implement it. For example, I am not sure what the request context object should look like or exactly what events I should expose

**Comment by mehrdada** [comment]
Closing, there is a pending interceptor PR on the node repo side: https://github.com/grpc/grpc-node/pull/59

**Comment by murgatroid99** [comment]
That interceptor PR is solving a different problem from this request.
