### ISSUE TITLE
TIMEOUT: build_docker_python in interop tests

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15540]
https://source.cloud.google.com/results/invocations/298b09ce-1d89-42af-8a7c-0b4fbf977604/log

This has been behind many of the failed interop test that failed recently. We can increase the timeout, but 30mins already seems to be pretty high.

```
2018-05-24 21:31:16,021 WAITING: ETA 1654.3 sec; 0 queued, 1 jobs running, 1 complete, 0 failed (load 1.00)
2018-05-24 21:31:26,022 WAITING: ETA 1664.3 sec; 0 queued, 1 jobs running, 1 complete, 0 failed (load 1.00)
2018-05-24 14:31:29,283 TIMEOUT: build_docker_python [pid=9395, time=1807.7sec]
```

**Comment by jtattermusch** [comment]
CC @mehrdada  @nathanielmanistaatgoogle

**Comment by jtattermusch** [comment]
This still seems to be happening.  30mins just to build python seems like a lot.

**Comment by jtattermusch** [comment]
Idea:

It seems that python interop tests are only running under python27, 

https://github.com/grpc/grpc/blob/70ce9e21df4f6a18fbcfbb2103d1e89987125f4a/tools/run_tests/run_interop_tests.py#L548

but the build script seems to be building python for both 2.x and 3.x  (that's what the build script does by default).
https://github.com/grpc/grpc/blob/70ce9e21df4f6a18fbcfbb2103d1e89987125f4a/tools/dockerfile/interoptest/grpc_interop_python/build_interop.sh#L31

@mehrdada , as python27 is going away, let's switch python interop tests to 3.x  and make sure interop tests docker image only builds python3.x?

**Comment by muxi** [comment]
This is still happening [in one of CI run yesterday](https://source.cloud.google.com/results/invocations/9c8b374f-5b04-4e0a-9e34-0e7c300c8207)

**Comment by muxi** [comment]
Oh 11 hours ago... sorry I think the CI was run before that.
