### ISSUE TITLE
Out-of-bounds access in GPRCHost.m due to non-null-terminated strings

### ISSUE THREAD

**Issue by var-const** [grpc/grpc#15555]
### What version of gRPC and what language are you using?
Objective-C.
 
### What operating system (Linux, Windows, …) and version?
MacOS High Sierra 10.13.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
XCode 9.2

### What did you do?
In [GRPCHost.m](https://github.com/grpc/grpc/blob/3001499c0f68efd1dc0d3ed02bbb1845a1eb7fba/src/objective-c/GRPCClient/private/GRPCHost.m), `NSString`'s `dataWithEncoding:` method is being used to [convert the string to a byte buffer](https://github.com/grpc/grpc/blob/3001499c0f68efd1dc0d3ed02bbb1845a1eb7fba/src/objective-c/GRPCClient/private/GRPCHost.m#L156), which is then passed to [grpc_ssl_credentials_create](https://github.com/grpc/grpc/blob/3001499c0f68efd1dc0d3ed02bbb1845a1eb7fba/src/objective-c/GRPCClient/private/GRPCHost.m#L176) as a C-string. `dataWithEncoding:` does __not__ return a null-terminated buffer ([see docs](https://developer.apple.com/documentation/foundation/nsstring/1408489-cstringusingencoding?language=objc), _"note that the data returned by dataUsingEncoding:allowLossyConversion: is not a strict C-string since it does not have a NULL terminator"_). This results in an out-of-bounds access, because `grpc_ssl_credentials_create` assumes that it receives a null-terminated C string:
* `grpc_ssl_credentials_create` invokes [ssl_build_config](https://github.com/grpc/grpc/blob/356d491245aebd12295c418f4ef1a1451b35203a/src/core/lib/security/credentials/ssl/ssl_credentials.cc#L120);
* `ssl_build_config` invokes [gpr_strdup](https://github.com/grpc/grpc/blob/356d491245aebd12295c418f4ef1a1451b35203a/src/core/lib/security/credentials/ssl/ssl_credentials.cc#L92);
* `grp_strdup` passes the string [to strlen](https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/string.cc#L43), resulting in an out-of-bounds access.

We found this in Firestore running integration tests under ASan.

See #15554 for a fix.

**Comment by muxi** [comment]
Fixed by #15554
