### ISSUE TITLE
Server assertion failed: pthread_mutex_lock(mu) == 0 (observed in various interop tests)

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15557]
C# Interop failure seen merging https://github.com/grpc/grpc/pull/15552

https://source.cloud.google.com/results/invocations/26f6b0ab-3228-4148-b0c8-037a63d115b4/targets/github%2Fgrpc/tests

Looks like happens on C# server side and many languages on the client side.

**Comment by jtattermusch** [comment]
Based on the logs, it looks like the server has died with an assertion which explains all the clients failing afterwards:
```
E0525 19:21:39.785769 140552737650432 src/core/lib/gpr/sync_posix.cc:47: assertion failed: pthread_mutex_lock(mu) == 0
2018-05-25 12:27:47,863 FAILED: interop_server_csharpcoreclr [ret=139, pid=4071, time=441.7sec]
Server "csharpcoreclr" has exited prematurely.
```

**Comment by jtattermusch** [comment]
The problem is most likely in C-core as in a different run, I saw the C++ interop server failing with the same assertion:
```
Warning: Table interop_results already exists
2018-05-26 20:08:44,670 E0527 02:59:19.122847974      10 interop_server.cc:117]      Expected compression but got uncompressed request from client.
E0527 02:59:19.207327038       9 interop_server.cc:117]      Expected compression but got uncompressed request from client.
E0527 02:59:27.625947408       9 interop_server.cc:117]      Expected compression but got uncompressed request from client.
E0527 02:59:27.720316883      11 interop_server.cc:117]      Expected compression but got uncompressed request from client.
```
E0527 02:59:29.016894159      16 sync_posix.cc:47]           assertion failed: pthread_mutex_lock(mu) == 0
2018-05-26 20:08:44,670 FAILED: interop_server_c++ [ret=139, pid=5962, time=665.0sec]
```
https://source.cloud.google.com/results/invocations/35e6b6a2-2637-4502-b2a2-bfc6994221e0/log

**Comment by jtattermusch** [comment]
So far I have trouble reproducing this locally.

**Comment by jtattermusch** [comment]
Also seen for ruby server in build:  https://source.cloud.google.com/results/invocations/54b34501-6eea-405b-ba76-f7c6410891d1/log

```
Warning: Table interop_results already exists
2018-06-04 20:14:39,832 E0605 03:00:55.483970781      86 sync_posix.cc:47]           assertion failed: pthread_mutex_lock(mu) == 0
tools/run_tests/interop/with_rvm.sh: line 19:    72 Aborted                 (core dumped) "$@"
2018-06-04 20:14:39,832 FAILED: interop_server_ruby [ret=134, pid=4190, time=1066.7sec]
```

**Comment by jtattermusch** [comment]
From this test run, it seems that pthread_mutex_lock returned 22, which corresponds to `EINVAL /* Invalid argument */`

Possible meaning from manpage:
```
[EINVAL]
The value specified by mutex does not refer to an initialised mutex object.
```

```
E0606 09:30:34.872590642      96 sync_posix.cc:70]           pthread_mutex_lock returned 22
E0606 09:30:34.872594394      96 sync_posix.cc:71]           assertion failed: res == 0
tools/run_tests/interop/with_rvm.sh: line 19:    72 Aborted                 (core dumped) "$@"
```
https://source.cloud.google.com/results/invocations/ed545dc2-6fd8-49d7-adbc-6d2fba64a51f/log

**Comment by jtattermusch** [comment]
CC @nicolasnoble

**Comment by nicolasnoble** [comment]
CC @sreecha - this may be the same bug you are currently looking at.

**Comment by jtattermusch** [comment]
not seen in a while
