### ISSUE TITLE
grpc accidentally triggered assert

### ISSUE THREAD

**Issue by binbowang1987** [grpc/grpc#15561]
### What version of gRPC and what language are you using?
 language: c++
 version: 1.10.1
 
### What operating system (Linux, Windows, …) and version?
 Linux, CentOS 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
compiler:  g++ 7.2.0
 
### What did you do?
I just do the grpc call once by once. accidentally, this issue arise.
 
 
### What did you see instead?
```#0  0x00007f96624c85f7 in raise () from /lib64/libc.so.6
#1  0x00007f96624c9ce8 in abort () from /lib64/libc.so.6
#2  0x00007f966563545e in ?? () from /usr/local/lib64/libgrpc.so.6
#3  0x00007f9665636d0b in grpc_call_start_batch () from /usr/local/lib64/libgrpc.so.6
#4  0x00007f96653a175c in grpc::Channel::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) () from /usr/local/lib64/libgrpc++.so.1
#5  0x000000000058d6ed in grpc::internal::Call::PerformOps (this=0x7f95c0805a80, ops=0x7f95c0805aa8) at /usr/local/include/grpcpp/impl/codegen/call.h:692
#6  0x00000000005a87a9 in grpc::ClientAsyncResponseReader<scheduler::MapResp>::StartCallInternal (this=0x7f95c0805a70) at /usr/local/include/grpcpp/impl/codegen/async_unary_call.h:171
#7  0x00000000005a8198 in grpc::ClientAsyncResponseReader<scheduler::MapResp>::StartCall (this=0x7f95c0805a70) at /usr/local/include/grpcpp/impl/codegen/async_unary_call.h:116
......
```

by dig into the code, I found that it triggered an assert in **grpc/blob/master/src/core/lib/surface/call.cc line:1912**
![image](https://user-images.githubusercontent.com/8586061/40667170-0c47b826-6394-11e8-8867-d1cea6ada513.png)

**Comment by ncteisen** [comment]
Do you have a simple reproduction case?

**Comment by binbowang1987** [comment]
I've tried to reproduce this issue, but it not arise.
