### ISSUE TITLE
grpc/cross-compile/arm/static link: libares.a and libgrpc++.a generated as a x86_64 package 

### ISSUE THREAD

**Issue by victoryang** [grpc/grpc#15572]
### What version of gRPC and what language are you using?
 latest version
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I am trying to cross-compile grpc to a static and arm library, and test it with your examples.
It can not recognize part of generated library, including the previous two.

Then I run arm-linux-gnueabihf-readelf -h on the wrong format ones, I got:
 Machine:                           Advanced Micro Devices X86-64 

Does this indicate that it is a x86 version static library so it can not link to it?

### What did you expect to see?
 Examples can be built successfully.
All generated library should be static, and arm version
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
No special set on my environment.

Thanks!

**Comment by victoryang** [comment]
To compile grpc, I followed  AngryLemonn suggested on page https://github.com/grpc/grpc/issues/9719#issuecomment-352842244

make HAS_PKG_CONFIG=false \ 
CC=arm-linux-gnueabihf-gcc \
CXX=arm-linux-gnueabihf-g++ \
RANLIB=arm-linux-gnueabihf-ranlib \
LD=arm-linux-gnueabihf-ld \
LDXX=arm-linux-gnueabihf-g++ \
AR=arm-linux-gnueabihf-ar \
PROTOBUF_CONFIG_OPTS="--host=arm-linux-gnueabihf --with-protoc=/usr/local/bin/protoc" static

I can successfully build libraries, but with part of them are not arm package...

Thanks

**Comment by victoryang** [comment]
I can successfully build correct *.o in directory third-party/cares/cares/ from source code

It needs to be configured with --host=arm-linux && CC=arm-linux-gnueabihf-gcc first xxxxxx , which should be done as same as protobuf

Is that because of lacking of "configure" and "make" procedures for cares in Makefile from grpc, that we fail to build a arm static library?

Thanks

**Comment by victoryang** [comment]
I've figured out why those are generated as x86_64 packages,

Before I run `make`, running `make plugins` with gcc compiler, which will prevent the following `make` command to generate correct packages for me.

Thanks

**Comment by lucifercr07** [comment]
@victoryang can you please point out how to generate dynamic libs? I tried removing static from `make` command, but it fails with following error:

[LD]      Linking grpc/libs/opt/libaddress_sorting.so.6.0.0

arm-linux-gnueabihf/bin/ld: unrecognized option '-Wl,-soname,libaddress_sorting.so.6'

arm-linux-gnueabihf/bin/ld: use the --help option for usage information

Makefile:3089: recipe for target 'grpc/libs/opt/libaddress_sorting.so.6.0.0' failed

**Comment by zty18494** [comment]
> @victoryang can you please point out how to generate dynamic libs? I tried removing static from `make` command, but it fails with following error:
> 
> [LD] Linking grpc/libs/opt/libaddress_sorting.so.6.0.0
> 
> arm-linux-gnueabihf/bin/ld: unrecognized option '-Wl,-soname,libaddress_sorting.so.6'
> 
> arm-linux-gnueabihf/bin/ld: use the --help option for usage information
> 
> Makefile:3089: recipe for target 'grpc/libs/opt/libaddress_sorting.so.6.0.0' failed

hi, lucifercr07
I have the same problem as you. Do you have resolved it? And HOW?
thanks~

**Comment by battlesnake** [comment]
> > @victoryang can you please point out how to generate dynamic libs? I tried removing static from `make` command, but it fails with following error:
> > [LD] Linking grpc/libs/opt/libaddress_sorting.so.6.0.0
> > arm-linux-gnueabihf/bin/ld: unrecognized option '-Wl,-soname,libaddress_sorting.so.6'
> > arm-linux-gnueabihf/bin/ld: use the --help option for usage information
> > Makefile:3089: recipe for target 'grpc/libs/opt/libaddress_sorting.so.6.0.0' failed
> 
> hi, lucifercr07
> I have the same problem as you. Do you have resolved it? And HOW?
> thanks~

I don't have this issue, but it looks like linker arguments are being passed directly to LD instead of via GCC/clang.  I guess this from the fact that LD is complaining about the `-Wl,` arguments.  `-Wl,` is normally used to tell the compiler facade to pass the following argument(s) to the linker.

As a guess, I'd suggest you try setting `LD` to `gcc` or `clang` or whatever facade you're using.
