### ISSUE TITLE
gRPC core logs superfluous, unsuppressible "Could not get common name of subject from certificate." messages

### ISSUE THREAD

**Issue by JackOfMostTrades** [grpc/grpc#15579]
When connecting to a server presenting an x509 certificate with SANs but without a subject, or with a subject containing no common name, gRPC writes [log](https://github.com/grpc/grpc/blob/master/src/core/tsi/ssl_transport_security.cc#L263) [lines](https://github.com/grpc/grpc/blob/master/src/core/tsi/ssl_transport_security.cc#L269) complaining about this. However, the code calling `ssl_get_x509_common_name` is perfectly happy with the `TSI_NOT_FOUND` result code and ultimately the code which is looking at the resulting of `peer_from_x509` is happy with a missing common name if there are names in the SAN extension.

In terms of specs, I don't believe the x509 spec requires a subject name at all in leaf certificates, and when present I don't believe the spec requires a common name. The relevant part of the [x509 spec](https://tools.ietf.org/html/rfc5280#section-4.1.2.6) says

>  The subject name MAY be carried in the subject field and/or the subjectAltName extension.
...
> Where it is non-empty, the subject field MUST contain an X.500 distinguished name (DN)

The spec also mentions what attributes must be supported by the implementations receiving an x509 cert, but doesn't specify any required attributes of a subject name (so for example, it should be perfectly acceptable to include a serial number attribute but no common name).

Obviously I bring this up because our ecosystem has certificates without a common name (DNS names or IP addresses are usually available as SANs in such cases). Obviously not the most common practice, but this is actually the first software we've run into which seems to care.

While this isn't causing any functional issues (as I said, calling code is perfectly happy getting the TSI_NOT_FOUND result) our logs are filling up with the titular error message and there doesn't appear to be any way to suppress this error.

**Comment by timbozo** [comment]
Is there any chance we can get an look at this issue (and the suggested fix), and potentially a merge?  As noted, the impact the unnecessary "GRPC_ERROR" is having on our logs is substantial.

**Comment by ncteisen** [comment]
Just put in #15712. Is that sufficient to stop these overly verbose logs?

**Comment by JackOfMostTrades** [comment]
Yep, that should do it. Thanks!
