### ISSUE TITLE
GRPC 1.12.0 arm compiler issues

### ISSUE THREAD

**Issue by arajeeva** [grpc/grpc#15573]
### What version of gRPC and what language are you using?
 1.12.0
 
### What operating system (Linux, Windows, …) and version?
 Linux (Ubuntu 14.04)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
LD=/tandberg/system/toolchain/arm-a9neon_linux_4.1x-linux-gnueabihf/bin/arm-a9neon_linux_4.1x-linux-gnueabihf-g++ LDXX=/tandberg/system/toolchain/arm-a9neon_linux_4.1x-linux-gnueabihf/bin/arm-a9neon_linux_4.1x-linux-gnueabihf-g++
 
### What did you do?
Cross compile 1.12.0 with ARM compiler
 
### What did you expect to see?
 Cross compile 1.12.0 successfully
 
### What did you see instead?
[CXX]     Compiling src/cpp/common/insecure_create_auth_context.cc
[PROTOC]  Generating protobuf CC file from src/proto/grpc/status/status.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/reflection/v1alpha/reflection.proto
[LD]      Linking /localview/novum-os/linux/grpc/_build/v2/walle.arm/work/grpc-1.12.0/libs/opt/libaddress_sorting.so.6.0.0
[LD]      Linking /localview/novum-os/linux/grpc/_build/v2/walle.arm/work/grpc-1.12.0/libs/opt/libgpr.so.6.0.0
/localview/novum-os/linux/grpc/_build/v2/walle.arm/work/grpc-1.12.0/objs/opt/third_party/address_sorting/address_sorting.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:3097: recipe for target '/localview/novum-os/linux/grpc/_build/v2/walle.arm/work/grpc-1.12.0/libs/opt/libaddress_sorting.so.6.0.0' failed
make: *** [/localview/novum-os/linux/grpc/_build/v2/walle.arm/work/grpc-1.12.0/libs/opt/libaddress_sorting.so.6.0.0] Error 1
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "build.py", line 94, in <module>
    go()
  File "/localview/novum-os/make/common/osbuild.py", line 3569, in go
    _build()
  File "/localview/novum-os/make/common/osbuild.py", line 1607, in _build
    _run_cmds("BUILD", _setup.buildcmds)
  File "/localview/novum-os/make/common/osbuild.py", line 1589, in _run_cmds
    raise BuildError("%s[%s]: '%s' failed" % (stage, os.getcwd(), cmd))
osbuild.BuildError: BUILD[/localview/novum-os/linux/grpc/build]: 'cd "/localview/novum-os/linux/grpc/_build/v2/walle.arm/work/grpc-1.12.0" && GRPC_CROSS_AROPTS=rcs GRPC_CROSS_COMPILE=true HAS_PKG_CONFIG=false HAS_SYSTEM_PROTOBUF=true LD=/tandberg/system/toolchain/arm-a9neon_linux_4.1x-linux-gnueabihf/bin/arm-a9neon_linux_4.1x-linux-gnueabihf-g++ LDXX=/tandberg/system/toolchain/arm-a9neon_linux_4.1x-linux-gnueabihf/bin/arm-a9neon_linux_4.1x-linux-gnueabihf-g++ PATH=/localview/novum-os/product/walle-imx/root/_build/v2/modexec/protobuf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin STRIP=: make --jobs=36' failed
Traceback (most recent call last):
  File "./build/build-os.py", line 270, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./build/build-os.py", line 263, in main
    finalize=bool(options.prefix))  # force finalize before install
  File "/localview/novum-os/build/buildos/product.py", line 132, in build
    c.build(module_filter=module_filter)
  File "/localview/novum-os/build/buildos/component.py", line 929, in build
    module.build()
  File "/localview/novum-os/build/buildos/module.py", line 174, in build
    self._run_with_log(cmdline, build_log)
  File "/localview/novum-os/build/buildos/module.py", line 143, in _run_with_log
    raise CalledProcessError(proc.returncode, argv)
subprocess.CalledProcessError: Command '['python2', 'build.py', '--jobs=36']' returned non-zero exit status 1
   ERROR: Failed to build walle-imx-os (failing command: ./build/build-os.py -t walle-imx-os:145 -j36 --prefix=/localview/testos/releases) [140.455]
    INFO: Done in 140.5 seconds! (1 jobs failed) [140.475]

**Comment by arajeeva** [comment]
Is this issue addressed in GRPC 1.13.0 release?

**Comment by arajeeva** [comment]
@apolcyn Any update on the issue?

**Comment by apolcyn** [comment]
@tainguyennc from that problem:

```
make plugins (with host build env)
make (with target build env)
```

it sounds like this problem is not specific to the `ADDRESS_SORTING_DEP`, but it also an issue with the c-ares and zlib dependencies?

**Comment by tainguyennc** [comment]
Possibly, our build approach will have problem if a library is shared in plugins and export libraries. I'm not familiar with the build template, however, if we can clearly identify host and target copies of the shared library then that would be helpful. That is, plugins will use HOST_ADDRESS_SORTING_DEP and static/shared will use ADDRESS_SORTING_DEP

**Comment by apolcyn** [comment]
For one, I'd agree that the plugins shouldn't actually need to depend on c-ares, address sorting, and zlib. I believe those dependencies are added to those plugins somewhere [around here](https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L1503). 

Also, just out of curiosity: 1) building the plugins for the host env, 2) saving the plugin artifacts, 3) cleaning the build, 4) building the grpc library for the target env - is a workaround, correct?
