### ISSUE TITLE
Empty service generates invalid C# code

### ISSUE THREAD

**Issue by frxstrem** [grpc/grpc#15574]
### What version of gRPC and what language are you using?
gRPC 1.12.0, C# 
 
### What operating system (Linux, Windows, …) and version?
MacOS High Sierra 10.13.4
 
### What did you do?
Tried to generate grpc C# code for an empty service:

```protobuf
syntax = "proto3";
service EmptyService { }
``` 
 
### What did you expect to see?
Generated that compiled cleanly.
 
### What did you see instead?

The generated `BindService` method for the empty service is incomplete:

```csharp
    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EmptyServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
    }
```

The compiler complains about a missing semicolon and not being able to convert a `ServerServiceDefinitonBuilder` to a `ServerServiceDefinition`.

**Comment by jtattermusch** [comment]
Thanks for reporting! fix is here #15583
