### ISSUE TITLE
grpc_ssl_client_certificate_request_type  doc comments are not very understandable

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15588]
I'm  trying to add C# support for `grpc_ssl_client_certificate_request_type` options, but I'm struggling to understand the actual meaning of the `grpc_ssl_client_certificate_request_type` enum values. Can we improve them? Having a good understanding of these enums is critical as we cannot afford misunderstandings when it comes to security.

https://github.com/grpc/grpc/blob/614331a50682c74fa8c02dcea674ca2ef5746225/include/grpc/grpc_security_constants.h#L60-L100

Things that are not clear to me:
- what's the difference between GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE   and GRPC_SSL_REQUEST_CLIENT_CERTIFICATE_BUT_DONT_VERIFY? Based on the description they look like they are doing the same thing?
- what does it mean if "client authentication done by grpc framework". What is checked against what? When is the connection accepted/rejected?
- what is the distinction between "authenticate" and "verify" a certificate. I'm not sure what the "*_AND_VERIFY" options actually do. Basically I don't fully understand the concepts of "don't request"/ "request"/ "require" / "verify".
- What exactly does it mean "The key cert pair should still be valid for the SSL connection to be established"?
- what does "skip no certificate" mean here: https://github.com/grpc/grpc/blob/614331a50682c74fa8c02dcea674ca2ef5746225/include/grpc/grpc_security_constants.h#L77 Is that a typo?
- if authentication is left to the application, what do I need to do? what API do I use? (see https://github.com/grpc/grpc/blob/614331a50682c74fa8c02dcea674ca2ef5746225/include/grpc/grpc_security_constants.h#L68)

**Comment by jtattermusch** [comment]
@deepaklukose @jboeuf @jiangtaoli2016  can you help?

**Comment by jtattermusch** [comment]
FTR the options have been added in https://github.com/grpc/grpc/pull/5958

**Comment by deepaklukose** [comment]
Most of the options are relevant only when you are dealing with self-signed certificates. These options essentially give a way to deal with self signed certificates in multiple ways.

There are multiple factors at play here:
    a. Did the server request a client certificate during ssl handshake
    b. Did the client present a client certificate (irrespective of whether the server asked for it)
           - If the  client presented a certificate was the certificate self signed by the client or if the signature can be verified using the ssl protocol.
    c. Is the signature verification done by ssl protocol or independently by the app (for self signed certificates for example by inspecting the certificate hash or other information in metadata).

[Mapping from these option to ssl options](https://github.com/grpc/grpc/blob/614331a50682c74fa8c02dcea674ca2ef5746225/src/core/tsi/ssl_transport_security.cc#L1853-L1873)

1.  With GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE: Server does not request for a client certificate. So the client can choose to present a self-signed or a signed certificate or not present a certificate at all and all of these should be okay.
   With GRPC_SSL_REQUEST_CLIENT_CERTIFICATE_BUT_DONT_VERIFY: Server requests the client for a certificate but the signature enforcement is not done by grpc server framework but left to the app. The app can use metadata like the certificate hash to verify a certificate (essentially provides the server a 
 way to verify self signed certificates, provided they have an out of band mechanism to register the certificate with the app)
2.  By "client authentication done by grpc framework", I meant certificate signature verification is done using the ssl protocol itself by the grpc server framework (SSL_VERIFY_PEER option is being used in ssl options). The client has to provide a signed certificate which can be verified by the server (using the SSL roots file). 
3. "don't request"/ "request"/ "require" / "verify"
         - Server has the option to either request or not-request for client cert.
         - Client can choose to either present a certificate or not.
         - Server can choose to verify the client certificate  or not
    Each of these three options are independent of each other and contribute to multiple options presented. 
      "require" for instance is the case server request for client cert, client has to present a certificate for the ssl handshake to continue but the server will not verify the client certificate using signature but can do so if needed based on certificate metadata.
     "verify" - SSL_VERIFY_PEER option is being used in ssl options and the client signature is verified/trusted by the server using the SSL roots file.
4. All of the above pretty much expected that the private key and the public key files were all in okay and the only question was whether they were self signed or signed by a mutually trusted CA. If the public key and private keys don't match up then the connection fails.
5. It is a typo. It should have been "The client needs to either present a signed cert or not present a
 certificate at all for a successful connection"
6.  grpc_auth_context has various properties of the peer like GRPC_X509_CN_PROPERTY_NAME, GRPC_X509_PEM_CERT_PROPERTY_NAME, GRPC_X509_SAN_PROPERTY_NAME that can be used.

@jtattermusch Hope this helps!
