### ISSUE TITLE
node-static_codegen  --grpc_out

### ISSUE THREAD

**Issue by MoXi2017** [grpc/grpc#15598]
like examples:https://github.com/grpc/grpc/tree/master/examples/node/static_codegen
I running `npm install -g grpc-tools` in WebStorm Terminal  in Windows7

then running

```
E:\nodejs\grpc_demo>grpc_tools_node_protoc --js_out=import_style=commonjs,binary:static_codegen/ --grpc_out=static_codegen --plugin=protoc-gen-grpc=C:/Users/user/AppData/Roaming/npm/grpc_tools_node_protoc_plugin proto/Student.proto
```

I find it print error if add `--grpc_out`, remove it can generate `Student_pb.js`
I Modify the `protoc.js` in `C:/Users/user/AppData/Roaming/npm/node_modules/grpc-tools/bin` for print some infomation

infomation:

```
exe_ext:.exe
protoc:C:\Users\user\AppData\Roaming\npm\node_modules\grpc-tools\bin\protoc.exe
plugin:C:\Users\user\AppData\Roaming\npm\node_modules\grpc-tools\bin\grpc_node_plugin.exe
args:--plugin=protoc-gen-grpc=C:\Users\user\AppData\Roaming\npm\node_modules\grpc-tools\bin\grpc_node_plugin.exe,--js_out=import_style=commonjs,binary:static_codegen/,--grpc_out=static_codegen,--plugin=protoc-gen-g
rpc=C:/Users/user/AppData/Roaming/npm/grpc_tools_node_protoc_plugin,proto/Student.proto

stderr:--grpc_out: protoc-gen-grpc: %1 ������Ч�� Win32 Ӧ�ó���
```

I can't generate  `Student_grpc_pb.js`
I can't solve this problem in this way

I running `npm install grpc-tools` and `npm install grpc` in WebStorm Terminal
then running 

```
E:/nodejs/grpc_demo/node_modules/grpc-tools/bin/protoc --js_out=import_style=commonjs,binary:static_codegen  --plugin=protoc-gen-grpc=E:/nodejs/grpc_demo/node_modules/grpc-tools/bin/grpc_node_plugin.exe --grpc_out=static_codegen  proto/Student.proto
```

It can find `Student_grpc_pb.js` and `Student_pb.js` in static_codegen/proto

I don't know why the `grpc_tools_node_protoc` command has an exception,if you know ,please tell me.

**Comment by nicolasnoble** [comment]
Here's an example of how this can work under Windows:

![image](https://user-images.githubusercontent.com/7281574/40855929-d85a6bbe-658a-11e8-93b9-b74b03ac5258.png)

**Comment by geekeritcom** [comment]
maybe you should use `*/grpc_tools_node_protoc_plugin.cmd` instead of `*/grpc_tools_node_protoc_plugin`,it's work for me.
