### ISSUE TITLE
CPU High grpc-csharp

### ISSUE THREAD

**Issue by mojinxun** [grpc/grpc#15603]
### What version of gRPC and what language are you using?

CSharp
 
### What operating system (Linux, Windows, …) and version?
 
Linux / Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
dotnetcore2.0 / Framework 4.7
 
### What did you do?

Just request, Server / Client may make cpu higher
 
### What did you expect to see?
 
I want get a solution
 
### What did you see instead?
 
![r leoip3 s4q i1u4 r 6](https://user-images.githubusercontent.com/13127383/40837999-e1e6d250-65ce-11e8-8b94-eed49294037f.png)

 Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(CompletionQueueSafeHandle cq, IProfiler optionalProfiler) 
take more cpu percent

**Comment by jtattermusch** [comment]
We need more info to be able to reproduce this:
- what grpc version?
- more details about when it happens & how do we know that this is not just you system being under load.
- how do I reproduce?

**Comment by jtattermusch** [comment]
If this only happens after a the client/server has been running for a long time, this is probably an instance of https://github.com/grpc/grpc/issues/15336 (which has been already fixed and will be in the next release).
Anyway, without more inputs I can't really help you.

**Comment by jtattermusch** [comment]
@mojinxun can you provide more details?

**Comment by mojinxun** [comment]
sorry, So late to give you a reply 

grpc version: 1.10.0

The CPU occupancy ratio of the current process is shown in the picture. 
Other disturbing factors have been excluded.


You only need to start a Grpc service to monitor the occupancy of the Grpc service CPU.

**Comment by jtattermusch** [comment]
I this also happening with newer versions? (please try with v1.13.0)

Also, it seems that just starting a gRPC service wouldn't be enough to get a reproduction of the condition you are describing. can you provide a code snippet that reproduces a problem?
(alternatively, provide as many details as possible:
- what is the bitness? (32bit or 64bit application)
- does this happen right after you start a server and receive the first request? If not, how long does it need to be running / how many requests you need to perform
- what exactly is the request (size, what message type, unary/streaming)
- does it happen always or just occasionally?

**Comment by jtattermusch** [comment]
@mojinxun  without additional info, there's no way we can investigate this (I have a hunch that this could be related to #15336 and thus fixed, but without a reproduction or additional info I don't have a way to verify that).
