### ISSUE TITLE
C++ GRPC with protobuf-lite enabled compiles with codegen errors

### ISSUE THREAD

**Issue by arajeeva** [grpc/grpc#15604]
### What version of gRPC and what language are you using?
 GRPC 1.10.1, C++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (GCC) 6.4.1 20170727
 
### What did you do?
Used libprotobuf-lite after cross-compiling GRPC with protobuf-lite enabled (using GRPC_USE_PROTO_LITE = yes)
 
### What did you expect to see?
Compile fine with protobuf-lite library 
 
### What did you see instead?
Seeing following Errors:
In file included from _build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/async_stream.h:22:0,
                 from _build/walle.imx/rootfs/functional/services/btle/interface/api/btle.grpc.pb.h:9,
                 from _build/walle.imx/rootfs/functional/services/btle/interface/btle.grpc.pb.cc:6:
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/call.h: In instantiation of 'grpc::Status grpc::internal::CallOpSendMessage::SendMessage(const M&, grpc::WriteOptions) [with M = novum::btle::ScanInfo]':
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/call.h:317:45:   required from 'grpc::Status grpc::internal::CallOpSendMessage::SendMessage(const M&) [with M = novum::btle::ScanInfo]'
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/client_unary_call.h:60:13:   required from 'grpc::internal::BlockingUnaryCallImpl<InputMessage, OutputMessage>::BlockingUnaryCallImpl(grpc::ChannelInterface*, const grpc::internal::RpcMethod&, grpc::ClientContext*, const InputMessage&, OutputMessage*) [with InputMessage = novum::btle::ScanInfo; OutputMessage = novum::btle::RequestStatus]'
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/client_unary_call.h:43:15:   required from 'grpc::Status grpc::internal::BlockingUnaryCall(grpc::ChannelInterface*, const grpc::internal::RpcMethod&, grpc::ClientContext*, const InputMessage&, OutputMessage*) [with InputMessage = novum::btle::ScanInfo; OutputMessage = novum::btle::RequestStatus]'
_build/walle.imx/rootfs/functional/services/btle/interface/btle.grpc.pb.cc:56:110:   required from here
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/call.h:307:58: error: incomplete type 'grpc::SerializationTraits<novum::btle::ScanInfo, void>' used in nested name specifier
   Status result = SerializationTraits<M, void>::Serialize(
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/method_handler_impl.h: In instantiation of 'void grpc::internal::RpcMethodHandler<ServiceType, RequestType, ResponseType>::RunHandler(const grpc::internal::MethodHandler::HandlerParameter&) [with ServiceType = novum::btle::Btle::Service; RequestType = novum::btle::BTDeviceAddress; ResponseType = novum::btle::RequestStatus]':
_build/walle.imx/rootfs/functional/services/btle/interface/btle.grpc.pb.cc:351:1:   required from here
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/method_handler_impl.h:63:66: error: incomplete type 'grpc::SerializationTraits<novum::btle::BTDeviceAddress, void>' used in nested name specifier
     Status status = SerializationTraits<RequestType>::Deserialize(
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/method_handler_impl.h:39:8: error: 'grpc::Status grpc::internal::CatchingFunctionHandler(Callable&&) [with Callable = grpc::internal::RpcMethodHandler<ServiceType, RequestType, ResponseType>::RunHandler(const grpc::internal::MethodHandler::HandlerParameter&) [with ServiceType = novum::btle::Btle::Service; RequestType = novum::btle::BTDeviceAddress; ResponseType = novum::btle::RequestStatus]::<lambda()>]', declared using local type 'grpc::internal::RpcMethodHandler<ServiceType, RequestType, ResponseType>::RunHandler(const grpc::internal::MethodHandler::HandlerParameter&) [with ServiceType = novum::btle::Btle::Service; RequestType = novum::btle::BTDeviceAddress; ResponseType = novum::btle::RequestStatus]::<lambda()>', is used but never defined [-fpermissive]
 Status CatchingFunctionHandler(Callable&& handler) {
        ^
_build/walle.imx/rootfs/os/grpc/api/grpcpp/impl/codegen/method_handler_impl.h:39:8: error: 'grpc::Status grpc::internal::CatchingFunctionHandler(Callable&&) [with Callable = grpc::internal::RpcMethodHandler<ServiceType, RequestType, ResponseType>::RunHandler(const grpc::internal::MethodHandler::HandlerParameter&) [with ServiceType = novum::btle::Btle::Service; RequestType = novum::btle::Enabled; ResponseType = novum::btle::RequestStatus]::<lambda()>]', declared using local type 'grpc::internal::RpcMethodHandler<ServiceType, RequestType, ResponseType>::RunHandler(const grpc::internal::MethodHandler::HandlerParameter&) [with ServiceType = novum::btle::Btle::Service; RequestType = novum::btle::Enabled; ResponseType = novum::btle::RequestStatus]::<lambda()>', is used but never defined [-fpermissive]

**Comment by arajeeva** [comment]
Are there any special options for building protobuf and/or grpc to be able to use protobuf-lite in c++?

**Comment by andrew2311** [comment]
Do you have progress with this issue?
I am using c++ grpc in our microservices on embedded device, and of course want to use grpc with protobuf-lite, but failed to compile grpc_cpp_plugin with protobuf-lite (it is required to generate grpc.pb.cc and grpc.pb.h files from proto files)

What I did:
0. Download grpc version (I’ve tried latest master and 1.8.6, result is the same)
1. mkdir -p cmake/build
2. cd cmake/build
3. cmake -DgRPC_USE_PROTO_LITE=ON -DgRPC_USE_PROTO_LITE=ON -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DOPENSSL_LIBRARIES=/usr/lib/x86_64-linux-gnu -DCMAKE_BUILD_TYPE=Release ../..

And I see following error:
grpc-1.8.6/src/compiler/cpp_generator.cc:107:16: error: ‘struct grpc_generator::Printer’ has no member named ‘PrintRaw’
       printer->PrintRaw(leading_comments.c_str());

When I compile with full protobuf, it compiles well.
When I comment this line (generate comments is not mandatory, I see other error)

What I expect: grpc compiles well with protobuf-lite

How I can fix that? May be some additional cmake/make options, may be another grpc branch, etc?

**Comment by awrichar** [comment]
FWIW, it works for me with the following steps:
* build gRPC using CMake with `-DgRPC_USE_PROTO_LITE=ON`
* set `option optimize_for = LITE_RUNTIME;` in my .proto file
* pass `-DGRPC_USE_PROTO_LITE` to g++ when compiling the generated files

I'm using protobuf-3.5.1 and grpc-1.10.1.

**Comment by chandanrr** [comment]
@awrichar these steps worked for me as well. 
In addition to those steps in the top-level CMakeLists.txt of grpc, i made the following change:

~/repos/grpc$ git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3563572..590263e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -73,7 +73,7 @@ set_property(CACHE gRPC_GFLAGS_PROVIDER PROPERTY STRINGS "module" "package")
 set(gRPC_BENCHMARK_PROVIDER "module" CACHE STRING "Provider of benchmark library")
 set_property(CACHE gRPC_BENCHMARK_PROVIDER PROPERTY STRINGS "module" "package")
 
-set(gRPC_USE_PROTO_LITE **OFF** CACHE BOOL "Use the protobuf-lite library")
+set(gRPC_USE_PROTO_LITE **ON** CACHE BOOL "Use the protobuf-lite library")

**Comment by andrew2311** [comment]
Close it please, it successfully compiles
