### ISSUE TITLE
grpc.server() immediately after gevent.subprocess.Popen not working

### ISSUE THREAD

**Issue by hexinw** [grpc/grpc#15620]
Hi,

I am using python gevent with grpc, with grpc release v1.11.0. This is the release that fixed grpc/gevent compatibility issue, #4629. I am seeing a problem that if I call grpc.Server() immediately after I create a gevent thread to do subprocess.Popen, grpc server doesn't seem to function correctly. Meaning "python greeter_client.py" would stuck without seeing response from grpc server. "netstat -an" would show that request is stuck in the kernel tcp receive queue without being drained by greeter_server.py.

My initial debug shows that if I add some delay (or you could do a threading Event wait) to ensure subprocess.Popen is done before cygrpc.CompletionQueue() is invoked. grpc server works without a problem.

The following is the test server program I used, which is pretty much the greeter_server.py from grpc example with a snippet of code to fork a child process inside a gevent thread. 

`greeter_server.py`
```
from gevent import monkey
monkey.patch_all()

import grpc
import grpc.experimental.gevent
grpc.experimental.gevent.init_gevent()

from concurrent import futures
import helloworld_pb2
import helloworld_pb2_grpc
import logging
import thread
import time

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

def test_fork():
   import subprocess
   subprocess.Popen(["sleep", "3600"])
   logging.error("====> Fork done.")

class Greeter(helloworld_pb2_grpc.GreeterServicer):

    def SayHello(self, request, context):
        return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)


def serve():
    thread.start_new_thread(test_fork, ())
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    try:
        while True:
            time.sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)


if __name__ == '__main__':
    serve()
```

**Comment by kpayson64** [comment]
#15411 Is the only other open issue for gevent, but I think it is unrelated.

The 1.12.1 release contained a bug fix for gevent, but it doesn't look similar to what you are describing.

Based on the details you have provided, I would guess what is happening is the server listening file descriptor is getting shared between the two child processes, and that is causing issues.

I'm hoping to look into this next week.

**Comment by hexinw** [comment]
Yeah I went through commit logs on master and didn't find things related before raising this bug. Thanks for the quick response.

**Comment by hexinw** [comment]
Looks like socket_accept_async() in src/python/grpcio/grpc/_cython/_cygrpc/grpc_gevent.pyx is never called after the greenlet is spawned for some reason. Hence s.socket.accept() is not executed and the socket server fd is not added to the loop anfds.

**Comment by hexinw** [comment]
Looks like `socket_accept_async` in `src/python/grpcio/grpc/_cython/_cygrpc/grpc_gevent.pyx` is never called after the greenlet is spawned. Hence `s.socket.accept` is not executed and the socket server fd is not added to the loop anfds.

**Comment by speedplane** [comment]
This looks possibly related to #18980
