### ISSUE TITLE
C# gRPC server gets into a bad state and doesn't recover

### ISSUE THREAD

**Issue by smflorentino** [grpc/grpc#15633]
### What version of gRPC and what language are you using?
 1.10.0
 
### What operating system (Linux, Windows, …) and version?
Windows Server 2016
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET 4.6
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
C# clients making RPC calls to a C# gRPC server start failing with `DeadlineExceeded` after a period of time. Killing the server fixes the issue.

Error on the client:
`Exception: Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")`

Error on the server:
```
[gRPC Warning] Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.ClientStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()
```
 
I took a memory dump, opened it in the [Debug Diagnostic Tool](https://www.microsoft.com/en-us/download/details.aspx?id=49924) on the server and here are the thread stacks. There seems to be a bunch of threads in `gprsharp_free`

```
ntdll!NtWaitForAlertByThreadId+14 
ntdll!RtlSleepConditionVariableCS+c9 
KERNELBASE!SleepConditionVariableCS+28 
grpc_csharp_ext_x64!gprsharp_free+60e42 
grpc_csharp_ext_x64!gprsharp_free+9a02 
grpc_csharp_ext_x64!gprsharp_free+60bfe 
kernel32!BaseThreadInitThunk+14 
ntdll!RtlUserThreadStart+21 
```
```
ntdll!NtWaitForAlertByThreadId+14 
ntdll!RtlSleepConditionVariableCS+c9 
KERNELBASE!SleepConditionVariableCS+28 
grpc_csharp_ext_x64!gprsharp_free+60e42 
grpc_csharp_ext_x64!gprsharp_free+ae62 
grpc_csharp_ext_x64!gprsharp_free+abc3 
grpc_csharp_ext_x64!gprsharp_free+ac61 
grpc_csharp_ext_x64!gprsharp_free+60bfe 
kernel32!BaseThreadInitThunk+14 
ntdll!RtlUserThreadStart+21 
```
```
ntdll!NtWaitForAlertByThreadId+14 
ntdll!RtlSleepConditionVariableCS+c9 
KERNELBASE!SleepConditionVariableCS+28 
grpc_csharp_ext_x64!gprsharp_free+60e42 
grpc_csharp_ext_x64!gprsharp_free+bf1a 
grpc_csharp_ext_x64!grpcsharp_version_string+2878 
grpc_csharp_ext_x64!grpcsharp_version_string+3b93 
grpc_csharp_ext_x64!grpcsharp_completion_queue_next+3c 
DomainBoundILStubClass.IL_STUB_PInvoke(Grpc.Core.Internal.CompletionQueueSafeHandle)+cd 
[[InlinedCallFrame]] 
Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(Grpc.Core.Internal.CompletionQueueSafeHandle, Grpc.Core.Profiling.IProfiler)+4d 
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+162 
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+14 
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+52 
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart()+52 
clr!CallDescrWorkerInternal+83 
clr!CallDescrWorkerWithHandler+4e 
clr!MethodDescCallSite::CallTargetWorker+f8 
clr!ThreadNative::KickOffThread_Worker+109 
[[GCFrame]] 
clr!Frame::Push+59 
clr!FillInRegTypeMap+198 
clr!FillInRegTypeMap+c1 
[[DebuggerU2MCatchHandlerFrame]] 
clr!FillInRegTypeMap+47 
clr!ThreadNative::KickOffThread+db 
clr!Thread::intermediateThreadProc+86 
kernel32!BaseThreadInitThunk+14 
ntdll!RtlUserThreadStart+21 
```
```
ntdll!NtWaitForAlertByThreadId+14 
ntdll!RtlSleepConditionVariableCS+c9 
KERNELBASE!SleepConditionVariableCS+28 
grpc_csharp_ext_x64!gprsharp_free+60efe 
grpc_csharp_ext_x64!gprsharp_free+ae62 
grpc_csharp_ext_x64!gprsharp_free+abc3 
grpc_csharp_ext_x64!gprsharp_free+ac61 
grpc_csharp_ext_x64!gprsharp_free+60bfe 
kernel32!BaseThreadInitThunk+14 
ntdll!RtlUserThreadStart+21 
```
```
ntdll!NtRemoveIoCompletion+14 
KERNELBASE!GetQueuedCompletionStatus+3f 
grpc_csharp_ext_x64!gprsharp_free+30f54 
grpc_csharp_ext_x64!gprsharp_free+bdab 
grpc_csharp_ext_x64!grpcsharp_version_string+2878 
grpc_csharp_ext_x64!grpcsharp_version_string+3b93 
grpc_csharp_ext_x64!grpcsharp_completion_queue_next+3c 
DomainBoundILStubClass.IL_STUB_PInvoke(Grpc.Core.Internal.CompletionQueueSafeHandle)+cd 
[[InlinedCallFrame]] 
Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(Grpc.Core.Internal.CompletionQueueSafeHandle, Grpc.Core.Profiling.IProfiler)+4d 
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+162 
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+14 
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+52 
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart()+52 
clr!CallDescrWorkerInternal+83 
clr!CallDescrWorkerWithHandler+4e 
clr!MethodDescCallSite::CallTargetWorker+f8 
clr!ThreadNative::KickOffThread_Worker+109 
[[GCFrame]] 
clr!Frame::Push+59 
clr!FillInRegTypeMap+198 
clr!FillInRegTypeMap+c1 
[[DebuggerU2MCatchHandlerFrame]] 
clr!FillInRegTypeMap+47 
clr!ThreadNative::KickOffThread+db 
clr!Thread::intermediateThreadProc+86 
kernel32!BaseThreadInitThunk+14 
ntdll!RtlUserThreadStart+21 
```

**Comment by jtattermusch** [comment]
Can you provide a minimal repro?

**Comment by jtattermusch** [comment]
Can you try running with Grpc.Auth.1.13.0-dev.nupkg  and taking the debug symbols from Grpc.Core.NativeDebug.1.13.0-dev.nupkg you can download both from here (see https://github.com/grpc/grpc/pull/14908):
https://pantheon.corp.google.com/storage/browser/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/windows/grpc_build_packages/760/20180607-025835/github/grpc/artifacts

**Comment by smflorentino** [comment]
@jtattermusch I'm re-deploying with that version, and will give it a try.

**Comment by Danprot** [comment]
We have a similar issue, grpc server frees up the port and therefore stops receiving requests. This happens for no apparent reason. I have traces server_channel,call_error,connectivity_state,channel,client_channel and they don't provide any info.
I've also tried restarting server - calling Shutdown(), Kill() and Start() again with no effect.
Now I'm analysing the dumps.
What are other traces that I can try to switch on to find the root cause?

**Comment by jtattermusch** [comment]
@Danprot  any luck with providing a reproduction?

**Comment by jtattermusch** [comment]
@smflorentino  @Danprot  are you still experiencing this problem? As mentioned before, a reproduction of the problem would be very helpful.

**Comment by Danprot** [comment]
Not since latest versions of GRPC for .net, currently we use 1.18 and seems to be fine

**Comment by smflorentino** [comment]
@jtattermusch  I am very sorry for not getting back to you on this. TL;DR, this seemed to be caused by a hang in our gRPC server code. I added more telemetry to track this, and it turns out it started happening exactly at 8000 concurrent connections, which seems related to the setting(s) in #10534.

We weren't using `ServerCallContext.CancellationToken` in our server code, which, once fixed, resolved the issue. My 2 suggestion would be;
- Have a warning or error when connections are queued up due to `Server.RequestCallTokensPerCompletionQueue` or `ChannelOptions.MaxConcurrentStreams` being reached.
- Consider changing the gRPC codegen to include the `CancellationToken` directly in the method signature. I realize this was possibly *not* done for a good reason, but it would be good to call out the usage of `CancellationToken` in the docs and include it in the C# example code.
Example signature change:
`public override async Task<FooResponse> Foo(IAsyncStreamReader<FooRequest> requestStream, ServerCallContext context)`
to
`public override async Task<FooResponse> Foo(IAsyncStreamReader<FooRequest> requestStream, ServerCallContext context, CancellationToken cancellationToken)`

**Comment by jtattermusch** [comment]
> @jtattermusch I am very sorry for not getting back to you on this. TL;DR, this seemed to be caused by a hang in our gRPC server code. I added more telemetry to track this, and it turns out it started happening exactly at 8000 concurrent connections, which seems related to the setting(s) in #10534.
> 
> We weren't using `ServerCallContext.CancellationToken` in our server code, which, once fixed, resolved the issue. My 2 suggestion would be;
> 
> * Have gRPC log a warning or error when connections are queued up due to `Server.RequestCallTokensPerCompletionQueue` or `ChannelOptions.MaxConcurrentStreams` being reached (we didn't see any)

We will consider adding a log message for that (or feel free to start a PR for that).

> * Consider changing the gRPC codegen to include the `CancellationToken` directly in the method signature. I realize this was possibly _not_ done for a good reason, but it would be good to call out the usage of `CancellationToken` in the docs and include it in the C# example code.
>   Example signature change:
>   `public override async Task<FooResponse> Foo(IAsyncStreamReader<FooRequest> requestStream, ServerCallContext context)`
>   to
>   `public override async Task<FooResponse> Foo(IAsyncStreamReader<FooRequest> requestStream, ServerCallContext context, CancellationToken cancellationToken)`

That's not doable without breaking the API backward compatibility so we can't really do it at this point.
