### ISSUE TITLE
Ruby 2.4.4 Alpine 3.7 missing file error

### ISSUE THREAD

**Issue by carlpartridge** [grpc/grpc#15641]
### What version of gRPC and what language are you using?
grpc (1.12.0)
ruby 2.4.4
 
### What operating system (Linux, Windows, …) and version?
 alpine 3.7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 In dockerfile we RUN apk --update ... add ... gcc ...
(full dockerfile below)
 
### What did you do?
Spinning up a kubernetes cluster and the rails app within a pod is crashing on startup:
```
/usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/grpc.rb:20:in `require_relative': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/2.4/grpc_c.so) - /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/2.4/grpc_c.so (LoadError)
from /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
from /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/errors.rb:15:in `require_relative'
from /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/errors.rb:15:in `<top (required)>'
from /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc.rb:17:in `require_relative'
```

There was an old fix I found on google that said to add the libc6-compat to the dockerfile, that ended up throwing a seg fault for protobuff:

```
/usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:15: [BUG] Segmentation fault at 0x0000000000016e16
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-musl]
c:0137 p:---- s:0671 e:000670 CFUNC :msgclass
c:0136 p:0026 s:0667 e:000666 CLASS /usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:15
c:0136 p:0026 s:0667 e:000666 CLASS /usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:14
c:0134 p:0039 s:0661 E:001800 TOP /usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:13 [FINISH]
c:0133 p:---- s:0658 e:000657 CFUNC :require
c:0132 p:0012 s:0653 e:000652 BLOCK /usr/local/bundle/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293
 ```

### What did you expect to see?
 No errors
 
### What did you see instead?
 See above
 
### Anything else we should know about your project / environment?
GRPC is a requirement of google-cloud-pubsub (0.30.2).  As well as a whole bunch of other similar sounding gems.  I assume the issue is in the Alpine build but Im not sure what else to install/try.  We have google-cloud-pubsub working with the same app in production environments on a cloud ubuntu VM and we have the app working in production in a kubernetes cluster with the google-cloud-pubsub gem installed but not called.  Im a lot out of my league with this stuff, any help is appreciated!

Here is the full dockerfile:
```
FROM ruby:2.4.4-alpine3.7

ENV RAILS_ROOT /rails/prism
ENV PAGER=/usr/bin/less
RUN mkdir -p $RAILS_ROOT/tmp/pids
WORKDIR $RAILS_ROOT
ADD Gemfile* ./

RUN apk --update --no-cache add bash mysql-dev mysql-client nodejs libxslt-dev libxml2-dev gcc g++ libcurl curl-dev pdftk poppler-utils
RUN apk --update add --virtual build-dependencies build-base build-dependencies gcc git less \
    && bundle install --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3 --without test development\
    && apk del build-dependencies

COPY . $RAILS_ROOT

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
```

**Comment by nicolasnoble** [comment]
This one seems to be on protobuf, not grpc.

@haberman ?

**Comment by TeBoring** [comment]
Same as #4460
