### ISSUE TITLE
Python dependencies shouldn't be version-pinned

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1564]
@ejona86 has persuaded me that src/python/requirements.txt naming specific versions of dependencies that it should instead support a broad range of possible dependency versions.

**Comment by gbin** [comment]
grpc/src/python/src/setup.py has some too

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm two minor questions about the way we state Python dependencies:
(1) We currently state them twice, in requirements.txt and in setup.py. Can we eliminate that duplication?
(2) Shouldn't requirements.txt be nested in src/python/src, since it is scoped to the "grpcio" package and src/python is a directory that includes both the "grpcio" package and the "interop" package?

**Comment by fta1** [comment]
similarly, the docker file is pinning the deps too:
https://github.com/grpc/grpc-docker-library/blob/master/grpc_python_base/Dockerfile#L46
shouldn't it just clone first, then pip install whatever setup.py asks for so they are always in sync?

**Comment by nathanielmanistaatgoogle** [comment]
@fta1: Yes; thank you for pointing that out.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle 
(1) Yes, there's nothing keeping us from chaining the requirements file to `setup.py` (and where it's used by scripts `cat`-ing it). Though... requirements.txt is not actually *used* by any code in the repository; it is only referenced by `src/python/README.md`.
(2) `requirements.txt` is referenced by the `README.md` in `src/python`, not by anything in `src/python/src`.

I feel like a more fundamental question is, "Why do we have this file?"

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm we provide the file "for easier scripting and updates", according to 53f101a7a9ffc3ee35b5.
