### ISSUE TITLE
csharp server interop test timeout

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#15672]
https://source.cloud.google.com/results/invocations/52a16c0e-2234-4b40-9c89-2f4e8171fbcc/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

Several of the csharp_server interop tests timed out.

**Comment by matt-kwong** [comment]
Closing since this additional failures haven't been referenced this issue in a couple months
