### ISSUE TITLE
c# change  MaxReceiveMessageSize

### ISSUE THREAD

**Issue by IDIHTD** [grpc/grpc#15683]
### What version of gRPC and what language are you using?
 1.4.1
 
### What operating system (Linux, Windows, …) and version?
 windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .net core 2.0
 
### What did you do?

 I am trying to use node.js transmission big file to .net with grcp
### What did you expect to see?
 how to change MaxReceiveMessageSize 
 
### What did you see instead?
 seem like only 4mb can be transmission

**Comment by jtattermusch** [comment]
These params are set as channel arguments/options

https://github.com/grpc/grpc/blob/04c85137e8e2d10f054f1dae2e751e3e06719ef5/include/grpc/impl/codegen/grpc_types.h#L159 and 
https://github.com/grpc/grpc/blob/04c85137e8e2d10f054f1dae2e751e3e06719ef5/include/grpc/impl/codegen/grpc_types.h#L153

In c# the api set these is `ChannelOptions`:
e.g. https://github.com/grpc/grpc/blob/bb85af66bdaca69048fb49c492d00e4ec5f2f3dd/src/csharp/Grpc.IntegrationTesting/ClientRunners.cs#L96

**Comment by IDIHTD** [comment]
@jtattermusch ,thanks
