### ISSUE TITLE
add support in core ssl_transport_security for rfc822Name SANs

### ISSUE THREAD

**Issue by ian-p-cooke** [grpc/grpc#15700]
### What version of gRPC and what language are you using?
SHA fe6bf3ffe64e3a0e086659abec02897a463cede2, C
### What operating system (Linux, Windows, …) and version?
MacOS 10.13.4
### What runtime / compiler are you using (e.g. python version or version of gcc)
clang: Apple LLVM version 9.1.0 (clang-902.0.39.2)
### What did you do?

called grpc_auth_context_peer_identity on the server after a client connected securely with a client certificate that contained an email SAN (rfc822Name).
 
### What did you expect to see?
 
the email address in the SAN.
 
### What did you see instead?

The common name. 

### Anything else we should know about your project / environment?

asked question first in [google groups](https://groups.google.com/d/topic/grpc-io/5BBSIHIO64I/discussion) but received no reply.  I can see grpc core filtering out the email SANs [here](https://github.com/grpc/grpc/blob/8f9445ca9fdb00fec9c76b7d5ed5eafddedc7c7b/src/core/tsi/ssl_transport_security.cc#L349).  Can we also add GEN_EMAIL names to the properties?  Either as members of x509_subject_alternative_name or maybe a new property (e.g. x509_subject_alternative_name_email)?

**Comment by jiangtaoli2016** [comment]
@yihuazhang is working on adding SPIFFE support in gRPC SSL transport security. It may address your issue.
