### ISSUE TITLE
pod `gRPC-C++ 0.0.2` misses proto_utils.h and config_protobuf.h

### ISSUE THREAD

**Issue by cepages** [grpc/grpc#15704]
### What version of gRPC and what language are you using?
Version 1.10.0 
Language: C++
 
### What operating system (Linux, Windows, …) and version?
 MacOS version: 10.13.4
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 XCode with CocoaPods
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I'm trying to run an iOS project using GRPC and proto files both generated in C++.

I'm using the pod `gRPC-C++ 0.0.2`.  
I added my c++ files generated and compiled with `libprotoc 3.5.1` to my main project.
I created and added the static libraries for protobuff: `libprotobuf-lite.a` , `libprotobuf.a`, `libprotoc.a` ( These libraries has been created with https://github.com/sinofool/build-protobuf-ios )
 
### What did you expect to see?
 
 I expect the project to compile without errors.

### What did you see instead?

When I build the XCode workspace it doesn't compile because there are two files missing:

`#include <grpcpp/impl/codegen/config_protobuf.h>`
`#include <grpcpp/impl/codegen/proto_utils.h>`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

I can fix this problem if I add to my local podspec the include line for the missing files.

So I edit `~/.cocoapods/repos/master/Specs/c/8/7/gRPC-C++/0.0.2/gRPC-C++.podspec.json`. 
After the the line 97, I add the following line: `"include/grpcpp/impl/codegen/config_protobuf.h",`
After the line 103, I add in the following line: `"include/grpcpp/impl/codegen/proto_utils.h", `

Compiles and runs!

Unfortunatelly this will only work if I don't update my pods.

Please could you add these include files to the pod specification.

Thanks

**Comment by muxi** [comment]
The `gRPC-C++` podspec is experimental at current state and is only supposed to work without protobuf support. To make it work with protobuf I think it would make sense to add these files as a non-default subspec of `gRPC-C++`.

**Comment by muxi** [comment]
Actually that still dooes not work since we would need to depend on protobuf C++ podspec, which is not there.

**Comment by cepages** [comment]
Hi @muxi 

Thanks for your answer. Yeah it won't work if you don't have the protobuff static libraries in your project.

Would it be wrong if we include this headers in the podspec anyway. Both libraries work so close together that it makes sense to add these files in the grpc pod spec. 

I know that doing this would need to add the protobuff libraries, but as I understand those headers are from the grpc code base so it won't make sense to add them when ( in the future ) we have a protobuff pod spec.

What do you think?

**Comment by muxi** [comment]
I think it makes sense as long as the cocoapods linter is good with that,
and I think these headers should not be in the same pod spec but in a
non-default subspec. I'll give that a try next week (or contribution is
welcome as always :)

**Comment by cepages** [comment]
@muxi the `pod spec lint` finds error with the version just downloaded from master.

Any advise of how to run the lint?. I tried ignoring the warnings with `pod spec lint --allow-warnings` but it's still finding errors

I have a version with the pod spec for the protobuf headers but I can't pass because of this.

**Comment by muxi** [comment]
Could you post what is the linter complaining about? As we missed the branch cut, the version you downloaded from master does not solve the problem; I might make a patch for it. But linter error should be some other issue.
