### ISSUE TITLE
[Server side] is there a way for limit maximum stream in grpc-java?

### ISSUE THREAD

**Issue by hehe717** [grpc/grpc#15722]
now, I want to configure of maximum stream in grpc-java in server side.
is there a way for limit maximum stream in grpc-java?
I saw 2016 year's open issue for this one, but cannot find any answer.

**Comment by hcaseyal** [comment]
@hehe717 Could you provide a link to the 2016 issue?

**Comment by ejona86** [comment]
For completeness, grpc/grpc-java#1886 is the referenced issue on grpc-java. There's not yet anything for this and it would need a cross-language effort.

**Comment by hcaseyal** [comment]
Closing because question is answered and future updates on this topic should be posted to grpc/grpc-java#1886
