### ISSUE TITLE
grpc_status":14,"os_error":"unknown node or service"

### ISSUE THREAD

**Issue by tkssharma** [grpc/grpc#15720]
### What version of gRPC and what language are you using?
 "grpc": "^1.12.2",  *grpc-node*
 
### What operating system (Linux, Windows, …) and version?
 Amazon AMI Node JS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 GCC
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 Grpc server should start 
 
### What did you see instead?
 but i am getting server UNAVAILABL `getting shutdown`
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
` E0611 22:53:10.050183000 140736636994496 server_chttp2.cc:40]          {"created":"@1528737790.049739000","description":"getaddrinfo failed","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":73,"grpc_status":14,"os_error":"unknown node or service"}  where is this coming from don't know !!`

**Comment by tkssharma** [comment]
```
/* eslint camelcase: 0 */

const grpc = require('grpc');

const path = require('path');
const GRPC_SERVER = `${global.configuration.grpc.host}:${global.configuration.grpc.port}`;

const proto = grpc.load(`${__dirname}/protos/site.proto`);

const server = new grpc.Server();

server.addService(proto.siteData.SiteService.service, {
  user(call, callback) {
    callback(null, { site_id: "1" , site_stauts:"Created"});
  }
});

server.bind('GRPC_SERVER', grpc.ServerCredentials.createInsecure());
server.start();
console.log('grpc server running on port:', GRPC_SERVER);

module.exports = server;
```

**Comment by murgatroid99** [comment]
You're binding the server to the string `'GRPC_SERVER'` instead of the value of that variable.
