### ISSUE TITLE
Sync gRPC LB load_balancer.proto with Go and Java

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#15728]
In https://github.com/grpc/grpc-proto/pull/25 I added a canonical version of the load balancer proto that can be shared between all languages.  grpc code should sync with it so that all three grpc implementations can be aligned.  

cc: @ejona86

**Comment by dgquintas** [comment]
We have some special needs in our version of the proto due to the use of nanopb. In particular, see https://github.com/grpc/grpc/blob/master/src/proto/grpc/lb/v1/load_balancer.proto#L19-L31 as well as not not having access to type names such as `google.protobuf.Timestamp` (which is why we define the types ourselves). 

I presume Java and Go could use the [core version's](https://github.com/grpc/grpc/blob/master/src/proto/grpc/lb/v1/load_balancer.proto) of the proto, but we can't use theirs.

**Comment by carl-mastrangelo** [comment]
@dgquintas I had seen this for some of the other protos.  I think a possible way forward is to make copies of the google/protobuf/timestamp.proto file, rather than the message.

**Comment by dgquintas** [comment]
Given how small the types are, why not include them as we do in core instead of having another moving piece?

**Comment by ejona86** [comment]
Because you changed the schema. The packages are now different and the JSON handling is different. Multiple built-in types have special handling by protobuf.

**Comment by dgquintas** [comment]
I see. I'll experiment (read, fight with nanopb) using a copy of the file.

**Comment by carl-mastrangelo** [comment]
@dgquintas also, if you have rapport with nanopb you could file an issue to treat well known types the same as protoc.  (in the future, of course)

**Comment by dgquintas** [comment]
I can, and will, certainly file a feature request with them.

**Comment by dgquintas** [comment]
Actually, here's the real problem:

```
third_party/protobuf/src/google/protobuf/timestamp.pb.h:7:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
```
That is, nanopb is happy to generate code using the `google.protobuf...` types, but when we try to compile the generated code for the "official" types, we run into forbidden includes, such as `<string>`, but I'm sure it's not the only one.

We are, in core, still restricted to a subset of C++, unlike protobuf. 

CC @nicolasnoble

**Comment by dgquintas** [comment]
After talking to @carl-mastrangelo , there may be a way around this. Stay tuned.
