### ISSUE TITLE
Exception: Defect: attempted to invoke already-invoked call!

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1573]
Seen on Travis:

```
START: make
PASSED: make [time=10.1sec]
START: tools/run_tests/build_python.sh
PASSED: tools/run_tests/build_python.sh [time=16.1sec]
START: tools/run_tests/run_python.sh
PASSED: tools/run_tests/run_python.sh [time=0.1sec]
START: tools/run_tests/run_python.sh
PASSED: tools/run_tests/run_python.sh [time=0.6sec]
PASSED: tools/run_tests/run_python.sh [time=1.1sec]
PASSED: tools/run_tests/run_python.sh [time=1.4sec]
PASSED: tools/run_tests/run_python.sh [time=4.3sec]
PASSED: tools/run_tests/run_python.sh [time=9.1sec]
PASSED: tools/run_tests/run_python.sh [time=14.5sec]
PASSED: tools/run_tests/run_python.sh [time=15.3sec]
PASSED: tools/run_tests/run_python.sh [time=15.4sec]
PASSED: tools/run_tests/run_python.sh [time=15.5sec]
PASSED: tools/run_tests/run_python.sh [time=16.0sec]
PASSED: tools/run_tests/run_python.sh [time=19.1sec]
PASSED: tools/run_tests/run_python.sh [time=21.9sec]
PASSED: tools/run_tests/run_python.sh [time=25.3sec]
++dirname tools/run_tests/run_python.sh
+cd tools/run_tests/../..
++pwd
+root=/home/travis/build/grpc/grpc
+export LD_LIBRARY_PATH=/home/travis/build/grpc/grpc/libs/opt
+LD_LIBRARY_PATH=/home/travis/build/grpc/grpc/libs/opt
+source python2.7_virtual_environment/bin/activate
++deactivate nondestructive
++'[' -n '' ']'
++'[' -n '' ']'
++'[' -n /bin/bash -o -n '' ']'
++hash -r
++'[' -n '' ']'
++unset VIRTUAL_ENV
++'[' '!' nondestructive = nondestructive ']'
++VIRTUAL_ENV=/home/travis/build/grpc/grpc/python2.7_virtual_environment
++export VIRTUAL_ENV
++_OLD_VIRTUAL_PATH=/home/travis/.rvm/gems/ruby-2.1.5/bin:/home/travis/.rvm/gems/ruby-2.1.5@global/bin:/home/travis/.rvm/rubies/ruby-2.1.5/bin:/home/travis/.rvm/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++PATH=/home/travis/build/grpc/grpc/python2.7_virtual_environment/bin:/home/travis/.rvm/gems/ruby-2.1.5/bin:/home/travis/.rvm/gems/ruby-2.1.5@global/bin:/home/travis/.rvm/rubies/ruby-2.1.5/bin:/home/travis/.rvm/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++export PATH
++'[' -n '' ']'
++'[' -z '' ']'
++_OLD_VIRTUAL_PS1=
++'[' x '!=' x ']'
+++basename /home/travis/build/grpc/grpc/python2.7_virtual_environment
++'[' python2.7_virtual_environment = __ ']'
+++basename /home/travis/build/grpc/grpc/python2.7_virtual_environment
++PS1='(python2.7_virtual_environment)'
++export PS1
++'[' -n /bin/bash -o -n '' ']'
++hash -r
+python2.7 -B test/compiler/python_plugin_test.py
.ssss..s..ERROR:root:Unexpected exception from task run in logging pool!
Traceback (most recent call last):
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 43, in _wrapping
    return behavior(*args, **kwargs)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/rear.py", line 217, in _spin
    self._on_write_event(operation_id, event, rpc_state)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/rear.py", line 147, in _on_write_event
    rpc_state.common.write.pending.pop(0), operation_id)
Exception: Defect: attempted to invoke already-invoked call!
```

**Comment by murgatroid99** [comment]
I just saw this again

**Comment by nathanielmanistaatgoogle** [comment]
(I am actively working on this code today, so that's nice.)

Twice in one day is surprising - can anyone recall seeing this before this morning's report?

**Comment by nicolasnoble** [comment]
Another one.

**Comment by nicolasnoble** [comment]
In fact, it keeps happening forever on my latest pull request, and won't go away, no matter how many times I'm restarting it.

**Comment by nicolasnoble** [comment]
It worked after probably the 5th retry.

**Comment by yang-g** [comment]
I saw this last night and today on different PRs.

**Comment by nicolasnoble** [comment]
Happened twice today.

**Comment by ctiller** [comment]
I have a reproduction of the equivalent bug in C++. This may be a core issue.

**Comment by jtattermusch** [comment]
Seen again https://travis-ci.org/grpc/grpc/jobs/63098326 with PR #1648

**Comment by ctiller** [comment]
So there's definitely a case whereby this can happen through legal core API usage.

I have a fix in #1625 - commit fd7166d264b4abd9dab4215cdc60a0c9dc635c8e.

That test is waiting on some help from Python folks on figuring out one last (reproducible) failure.



Alternatively, this could be API misuse, in which case ignore all of the above.

**Comment by jtattermusch** [comment]
Seen again https://travis-ci.org/grpc/grpc/jobs/63422591 with PR #1648

**Comment by ctiller** [comment]
Can confirm that at least one cause of this would be fixed with #1625.

I ran:
```
tools/run_tests/run_tests.py -l python -n 100
```

With my changes from #1701 merged in, and saw the following smoking gun:

I0521 12:36:03.128578561   24164 call.c:1190] grpc_call_start_batch(call=0x7f2494002540, ops=0x7f248dff92e0, nops=1, tag=0x7f2494001e30)
I0521 12:36:03.128605296   24164 call.c:1190] ops[0]: SEND_INITIAL_METADATA
I0521 12:36:03.128642509   24164 call.c:1190] grpc_call_start_batch(call=0x7f2494002540, ops=0x7f248dff9310, nops=1, tag=0x7f24940008c0)
I0521 12:36:03.128653970   24164 call.c:1190] ops[0]: RECV_INITIAL_METADATA ptr=0x7f24c439ae20
I0521 12:36:03.128662849   24164 call.c:1190] grpc_call_start_batch(call=0x7f2494002540, ops=0x7f248dff9340, nops=1, tag=0x7f2494001a80)
I0521 12:36:03.128669405   24164 call.c:1190] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7f24c439ae38 status=0x7f24c439ae88 details=0x7f24c439ae90
I0521 12:36:03.128973734   24162 completion_queue.c:223] RETURN_EVENT[0x2394410]: OP_COMPLETE: tag:0x7f2494001e30 OK
I0521 12:36:03.130612652   24172 call.c:1190] grpc_call_start_batch(call=0x7f2494002540, ops=0x7f24c5623330, nops=1, tag=0x7f24500023e0)
I0521 12:36:03.130633264   24172 call.c:1190] ops[0]: SEND_MESSAGE ptr=0x7f2450002400
I0521 12:36:03.228592699   24162 completion_queue.c:223] RETURN_EVENT[0x2394410]: OP_COMPLETE: tag:0x7f24500023e0 OK
I0521 12:36:03.228740303   24162 call.c:1190] grpc_call_start_batch(call=0x7f2494002540, ops=0x7f24afffde50, nops=1, tag=0x7f24b00109f0)
I0521 12:36:03.228758827   24162 call.c:1190] ops[0]: SEND_MESSAGE ptr=0x7f24b0010a10
ERROR:root:Unexpected exception from task run in logging pool!
Traceback (most recent call last):
  File "/usr/local/google/home/ctiller/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 43, in _wrapping
    return behavior(*args, **kwargs)
  File "/usr/local/google/home/ctiller/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/rear.py", line 217, in _spin
    self._on_write_event(operation_id, event, rpc_state)
  File "/usr/local/google/home/ctiller/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/rear.py", line 147, in _on_write_event
    rpc_state.common.write.pending.pop(0), operation_id)

**Comment by ctiller** [comment]
Seen again.

**Comment by nicolasnoble** [comment]
Seen again.

**Comment by ctiller** [comment]
Today's code?

**Comment by nicolasnoble** [comment]
Was there an active fix for that one ? Did we get any more of these since a few days ago ?

**Comment by ctiller** [comment]
There was a fix that hypothetically should have got it... but I didn't
explicitly repro it (I instead saw a similar bug in C++ and fixed that)
