### ISSUE TITLE
What are the five extra bytes before the serialization result of protobuf in H2 body

### ISSUE THREAD

**Issue by zyearn** [grpc/grpc#15734]
Hi,

I am writing a server(not using grpc) that can work with grpc C++client. The HTTP/2 part is working perfectly: header and data can be received correctly. But when I deserialize h2 body from grpc client, I found that the body is in the following format: (it is a simple struct with a string 'world' and a integer 1234)

00 00 00 00 0d 0a 05 77 6f 72 6c 64 12 04 31 32 33 34

which can not be deserialize by protobuf correctly using ParseFromCodedStream.

As a test, I serialize the request by myself, and the result is: 

0a 05 77 6f 72 6c 64 12 04 31 32 33 34.

The diff is that the first 5 characters are missing. And I also find that the fifth character is always the integer indicating the remaining length of the payload. 

Does grpc add some specific custom protocol to the result of serialization protobuf?

Thanks!

**Comment by ericgribkoff** [comment]
> The diff is that the first 5 characters are missing. And I also find that the fifth character is always the integer indicating the remaining length of the payload.

> Does grpc add some specific custom protocol to the result of serialization protobuf?

Yes, gRPC sends length-prefixed messages: see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md, specifically the definition for `Length-Prefixed-Message`. The prefix contains a flag indicating if the message is compressed as well as the message length; keep in mind that a gRPC stream can contain multiple messages.

I'm closing this issue, as there's nothing actionable on the gRPC side here. In the future, our [grpc-io mailing list](https://groups.google.com/forum/#!forum/grpc-io) is better suited for these types of questions; feel free to follow up with a new email thread there if you have any additional questions.
