### ISSUE TITLE
Add functionality to allow dependency injection via ServerCallContext

### ISSUE THREAD

**Issue by dpsenner** [grpc/grpc#15757]
### What version of gRPC and what language are you using?
 
1.12.0 csharp
 
### What operating system (Linux, Windows, …) and version?
 
Linux, Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
msbuild
 
### What did you do?

We wanted to implement a server application that makes some nifty use of dependency injection. To do so we make use of the Inceptor api that was added with 1.10.0. Currently there's however only a hacky way to add context aware objects to the ServerCallContext instance as outlined below:

```csharp
    public interface IServerCallContextAccessor
    {
        ServerCallContext ServerCallContext { get; }
    }

    public interface IServerCallContextProvider
    {
        ServerCallContext ServerCallContext { get; set; }
    }

    public class ServerRequestScope : Interceptor
    {
        public IServiceProvider ServiceProvider { get; }

        public ServerRequestScope(IServiceProvider serviceProvider)
        {
            ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        }

        public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
        {
            using (var serviceScope = ServiceProvider.CreateScope())
            {
                // initialize the server call context to allow future invocations to GetService<IServerCallContextAccessor>() to return the current server call context
                var serviceProvider = serviceScope.ServiceProvider;
                serviceProvider.GetRequiredService<IServerCallContextProvider>().ServerCallContext = context;
                context.RequestHeaders.Add(new ServiceProviderMetadataEntry(serviceProvider));

                return await base.UnaryServerHandler(request, context, continuation);
            }
        }
    }

    public class ServiceProviderMetadataEntry : Metadata.Entry
    {
        public const string MetadataKey = "X-ServiceProvider";

        public IServiceProvider ServiceProvider { get; }

        public ServiceProviderMetadataEntry(IServiceProvider serviceProvider)
            : base(MetadataKey, string.Empty)
        {
            ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        }
    }

        public static IServiceProvider GetServiceProvider(this ServerCallContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            foreach (var requestHeader in context.RequestHeaders)
            {
                if (ServiceProviderMetadataEntry.MetadataKey.Equals(requestHeader.Key, StringComparison.InvariantCultureIgnoreCase))
                {
                    if (requestHeader is ServiceProviderMetadataEntry serviceProviderMetadataEntry)
                    {
                        return serviceProviderMetadataEntry.ServiceProvider;
                    }
                }
            }

            throw new InvalidOperationException($"{ServiceProviderMetadataEntry.MetadataKey} request header metadata not found.");
        }

    class Program
    {
        static void Main(string[] args)
        {
            // configure service collection
            var serviceCollection = new ServiceCollection()
                .AddScoped<IServerCallContextProvider, ServerCallContextProvider>()
                .AddScoped<IServerCallContextAccessor>(t => new ServerCallContextAccessor(t.GetRequiredService<IServerCallContextProvider>().ServerCallContext));

            // build service provider
            var serviceProvider = serviceCollection.BuildServiceProvider();

            // initialize the server along with service controllers
            int port = 50051;
            Server server = new Server
            {
                Services =
                {
                    SecurityService.BindService(new SecurityService()) // inner-most service
                        .Intercept(new GenericExceptionHandler()) // a middlware that gracefully swallows all exceptions that could possibly occur
                        .Intercept(new ServerRequestScope(serviceProvider)) // inject the request scope, providing the service provider request scope from here on
                },
                Ports = { new ServerPort("0.0.0.0", port, ServerCredentials.Insecure), },
            };
            server.Start();

            foreach (var serverPort in server.Ports)
            {
                Console.WriteLine($"Server listening on {serverPort.Host}:{serverPort.BoundPort}");
            }

            Console.WriteLine("Press any key to stop the server...");
            Console.ReadKey();

            server.ShutdownAsync().Wait();
        }
    }
```

Yes, we indeed hack the dependency injection mechanism into the current implementation of the ServerCallContext by means of a custom request header metadata entry.
 
### What did you expect to see?
 
We expected to have a way to inject a scoped System.IServiceProvider into ServerCallContext instances. Having a possibility to deep clone an existing ServerCallContext instance we could pass it on to services via the Interceptor api.

Adding a property with type System.IServiceProvider to ServerCallContext and making the constructor of ServerCallContext public would allow effective dependency injection mechanisms to be implemented. The following is an example of how 

```csharp
    public class ServerRequestScope : Interceptor
    {
        public IServiceProvider ServiceProvider { get; }

        public ServerRequestScope(IServiceProvider serviceProvider)
        {
            ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        }

        public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
        {
            using (var serviceScope = ServiceProvider.CreateScope())
            {
                // initialize the server call context to allow future invocations to GetService<IServerCallContextAccessor>() to return the current server call context
                var serviceProvider = serviceScope.ServiceProvider;
                serviceProvider.GetRequiredService<IServerCallContextProvider>().ServerCallContext = context;

                // clone copy server call context with a customized service provider
                var scopedServerCallContext = new ServerCallContext(context, serviceProvider);
                return await base.UnaryServerHandler(request, scopedServerCallContext, continuation);
            }
        }
    }
```

**Comment by eschgi** [comment]
+1

**Comment by cearny** [comment]
Yeah, either a copy constructor on the ServerCallContext or some sort of "view bag"-like functionality on it would help a lot not just with schlepping the service provider around, but possibly other things like user identity, etc.

Would you accept a PR for this (and by this I'm referring to the copy constructor as it's super-trivial and the least intrusive of the two options, plus it's not going to change the public API)?

By the way, @dpsenner I think it's better to use a trailer + lowercase metadata key (gRPC lowercases everything anyway) as request headers are not guaranteed to be there. You do have to clean the trailers up afterwards, though, so that's not so nice.

**Comment by dpsenner** [comment]
We chose to inject the service provider in the metadata headers because:

1. we prefix the service provider header key with a prefix that should never fly in from a request
1. we would have to clean up the trailers if we did inject the service provider there, creating yet another point of failure
1. if request headers are not present, we create them on the fly

This work around gets the job done for our functional requirements. Despite that, it is a hack that only exists because it works and is the only solution we could come up with.

@cearny I do not grasp how a copy constructor would help if a middleware creates the service provider by calling `ServiceProvider.CreateScope()`. There's no way to override the `ServerCallContext` instance of a request, is there? Would you please explain your thoughts?

**Comment by cearny** [comment]
@dpsenner as I see it, looking at the `ServerCallContext` sources, there is no way to be sure that `RequestHeaders` is null or not -- and I see no way of setting it if it is, as it's getter-only. Am I missing something?

The "trailers" thing is precisely the same hack that works that you made, only since the trailers are instantiated by default, they're never null and what we're using is something like:

```
try
{
    return await base.UnaryServerHandler(request, context, continuation);
}
finally
{
    // Clean up after ourselves, we don't want to send that (empty) trailer to the client
    context.ResponseTrailers.Remove(metadata);
}
```

so they should get cleaned up properly. But, again as you've mentioned, this is just a working hack.

*As for the benefits of having a copy constructor on `ServiceCallContext`*, it would allow us to write something like:

```
public class ScopeAwareServiceCallContext {
    // ...

    public ScopeAwareServiceCallContext(IServiceScope serviceScope, ServiceCallContext originalContext) : base(originalContext) {
        serviceScope = _serviceScope;
    }
}

// and in the interceptor write something like:

var scopeAwareContext = new ScopeAwareServiceCallContext(serviceScope, context);
return await base.UnaryServerHandler(request, scopeAwareContext, continuation);
```

So, a riff on the decorator pattern, really.

Add to this an extension method on `ServiceCallContext` to try and extract the service scope, similarly to what you've written but in this case just trying to cast to `ScopeAwareServiceCallContext` instead of iterating on the headers, and you could have most of what you need.

Ideally I'd like to have some sort of "context metadata" that one could add whatever one needs to (sort of like a view bag, as I've mentioned), but -- having a copy constructor on the (non-sealed!) `ServerCallContext` class -- all this could be solved just with extension methods. No new fields on the original `ServerCallContext` would need to be introduced. Neat & tidy -- I think.

**Comment by dpsenner** [comment]
Now I get your idea of the copy ctor. That could work. I rather thought of replacing `ServerCallContext` with `IServiceProvider` and let the grpc internals look up the original `ServerCallContext` by invocation of `serviceProvider.GetRequiredService<ServerCallContext>()` . A developer could wrap the service provider without even having to know about the `ServerCallContext` existence.

A wrapping interceptor that does nothing would then look like:

```csharp
public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, IServiceProvider serviceProvider, UnaryServerMethod<TRequest, TResponse> continuation)
{
    return await base.UnaryServerHandler(request, serviceProvider, continuation);
}
```

And another one that adds a scope could look like:

```csharp
public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, IServiceProvider serviceProvider, UnaryServerMethod<TRequest, TResponse> continuation)
{
    using (var serviceScope = ServiceProvider.CreateScope())
    {
        return await base.UnaryServerHandler(request, serviceProvider, continuation);
    }
}
```

This means that dependency injection becomes a integrated component of the grpc csharp implementation.

**Comment by cearny** [comment]
That would work neatly, yes.

Though I've had a discussion on this topic with a colleague and the end result of that was that we both agreed this would tie "out-of-the-box" gRPC to Microsoft's own DI container way too much, making it an intrusive change. The point being that some people use Autofac, Ninject, etc.

Until we'll have something like per-scope metadata separated from headers and trailers, which could enable most any sort of customization, I can live with the most minimal change to the gRPC codebase, which would be a copy constructor.

**Comment by dpsenner** [comment]
It's great news that you are considering this addition as a team!

If portability and interopability is a concern, then grpc could come with it's own dependency 
 injection interface. All that interface has to define is a method signature `object GetService(Type t)`. It is straight forward to implement adapters from [microsoft DI, ninject, autofac] to grpc di. I however have to insist that it is a tedious task to reinvent an existing wheel. That's just yet another api to the same requirements.

[This link](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider?view=netframework-4.7.2) points the documentation of the IServiceProvider interface, note the "Applies to" section.

Further [this link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestservices?view=aspnetcore-2.1#Microsoft_AspNetCore_Http_HttpContext_RequestServices) points to a property how the asp net core devs implemented a way to access a request-scoped serviceprovider. Adding this (or something like this) to the ServerCallContext could be an option that's backwards compatible.

**Comment by cearny** [comment]
Hm, the thing is that I don't really want to see gRPC as "just a sort of ASP.NET Core", convenient as that might be. I feel like it should focus on what it does specifically and provide extension endpoints where more is required of it. This may be because I'm coming to it from an Express.js mindset. Just to put my thoughts into context.

By the way, I've taken a look at maybe adding a service provider to the `ServerCallContext` class and it would be quite awkward to do it directly right now, as it is only created via `HandlerUtils.NewContext`, which is called directly in the `HandleCall`s of `ClientStreamingServerCallHandler`, `DuplexStreamingServerCallHandler`, `ServerStreamingServerCallHandler` and `UnaryServerCallHandler`. Shipping a service provider to those would mean either having some sort of static master-class (like the `Logger`, something that I don't really like already) or quite a lot of rework. Not sure _I, at least_ would be able to tackle _that_ task.

I still feel like just being able to swap the server call context with a sub-class that is able to provide a service provider using an interceptor (sort of like the interceptor already does with `InterceptingCallInvoker` on the client side) would be the path of least resistance. Also, maybe adding a "view-bag" of sorts on the server call context :-)

**Comment by dpsenner** [comment]
I like the idea that grpc allows injecting arbitrary data into the methods that process requests and allowing the interceptors to manipulate that arbitrary data. After all that is what dependency injection is about.

This solution is similar to what we hacked with the custom meta data header. It is just bad to abuse request headers for details that matter only to the server side implementation and, as pointed out earlier, there's no functional requirement to make use of any existing dependency injection framework. From this point of view it is better that grpc is standalone, not depending on any other framework but netstandard.

**Comment by chwarr** [comment]
@dpsenner I am currently tunneling the `IServiceProvider` into the call handler with a similar interceptor. Instead of using a header, I use an [`AsyncLocal<IServiceProvider>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netcore-1.0):

```csharp
public static class ServerCallContextExtensions
{
    internal static AsyncLocal<IServiceProvider> ServiceProviderInstance { get; set; } = new AsyncLocal<IServiceProvider>();

    public static IServiceProvider ServiceProvider(this ServerCallContext _)
    {
        return ServiceProviderInstance.Value;
    }
}

// In the same assembly as ServerCallContextExtensions so it can access the internal field
public StartScopeInterceptor : Interceptor
{
    private readonly IServiceProvider _services;

    public StartScopeInterceptor(IServiceProvider services)
    {
        _services = services ?? throw ArgumentNullException(nameof(services));
    }

    public override async Task<TResponse> ClientStreamingServerHandler<TRequest, TResponse>(
        IAsyncStreamReader<TRequest> requestStream,
        ServerCallContext context,
        ClientStreamingServerMethod<TRequest, TResponse> continuation)
    {
        using (var scope = _services.CreateScope())
        {
            ServerCallContextExtensions.ServiceProviderInstance.Value = scope.ServiceProvider;
            try
            {
                return await continuation(requestStream, context);
            }
            finally
            {
                ServerCallContextExtensions.ServiceProviderInstance.Value = null;
            }
        }
    }

    // ...
}

public ServiceImpl : TheService.TheServiceBase
{
    public override async Task<TheResponse> TheMethod(TheRequest request, ServerCallContext context)
    {
        IServiceProvider sp = context.ServiceProvider();
        // ...
    }
}
```

**Comment by cearny** [comment]
@chwarr yeah, `AsyncLocal` and extension methods look like the least-intrusive and "nicest" option ATM and `AsyncLocal` is used for this in a few other places -- the zipkin4net library uses a similar concept, for example, and that's how we added instrumentation for StackExchange.Redis.

Interesting info regarding the team possibly having considered a `Dictionary` at one point, by the way 👍 I guess a `ConcurrentDictionary` could be used instead in case synchronization issues were a thing. But if an object is provided, then any library consumer could decide what they actually need.

I've actually had this lying around for a while now but never got around to actually running the test suite locally (to formally check that it doesn't break anything -- it really shouldn't though): https://github.com/cearny/grpc/commit/91bc5d6272e408372c5465552e452e4316af2cb9

**Comment by jtattermusch** [comment]
Looks like the use case has been sufficiently covered by https://github.com/grpc/grpc/pull/18086?

**Comment by cearny** [comment]
That woks handsomely for me!

**Comment by dpsenner** [comment]
Great news that this issue was fixed, thanks!
