### ISSUE TITLE
pylint all the *.py things! (in tools/, ...)

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15769]
Static analysis has brought us nice things. `pylint` now runs on the gRPC Python codebase and tests (#261).  In addition to [running `shellcheck` on *.sh](https://github.com/grpc/grpc/issues/11601), we should aim to run `pylint` on all `*.py` in the project to catch bugs.

**Comment by nathanielmanistaatgoogle** [comment]
To the best of my knowledge this is still actionable.
