### ISSUE TITLE
Rewrite of core with Better C

### ISSUE THREAD

**Issue by andre2007** [grpc/grpc#15786]
Did you already considered rewriting the core of gRPC with Better C? 

Some benefits of Better C:
- memory safety
- compile time function execution
- functional programming support
- no make file necessary anymore as building is much more easy
- a lot of more ...

Better C is binary compatible to C. Nothing changes for the other language which relies on of the core package. Rewriting is very easy, see the third article.

https://dlang.org/blog/2017/08/23/d-as-a-better-c/
https://dlang.org/blog/2018/02/07/vanquish-forever-these-bugs-that-blasted-your-kingdom/
https://dlang.org/blog/2018/06/11/dasbetterc-converting-make-c-to-d/

**Comment by nicolasnoble** [comment]
That is definitely not going to happen. gRPC needs to build from sources out of the box for Ruby, Python, etc. The only required dependency on native extension packages for these languages is only a C compiler.

Doing this kind of change would make it impossible for these source packages to build properly out of the box on anyone's machine.

**Comment by hsaliak** [comment]
@andre2007 while the core is unlikely to switch to betterC soon, it may be an interesting exercise to wrap core with an idiomatic betterC API or a full D api. 
Something like that can be done out of repo with a view to migrate into grpc-ecosystem if you are interested.
Some points that might be useful to consider if you go down that path.
1) Wrapping core - we do a 6 weekly release cycle, so be sure that you can wrap the latest version of core and it can be a moving target.
2) We have interop tests that you can use to test how your server / client interops in many cases with other gRPC implementations
3) Test suite.. it would be good to look at some wrapped language test suite and give similar coverage.

**Comment by andre2007** [comment]
Thanks a lot for the info @hsaliak . I currently investigate whether I can translate the C++ wrapper to D or someone else from the D community can take over this task.
