### ISSUE TITLE
PHP distribtest broken: distribtest.php_linux_x64_jessie

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15803]
The distribtest php_linux_x64_jessie is broken consistently
```
libtool: compile:  g++ -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuser6dy3Qf/grpc-1.14.0dev/include -I/tmp/pear/temp/pear-build-defaultuser6dy3Qf/grpc-1.14.0dev/main -I/tmp/pear/temp/grpc -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/boringssl/include -I/tmp/pear/temp/grpc/third_party/address_sorting/include -DHAVE_CONFIG_H -std=c++11 -fno-exceptions -fno-rtti -g -O2 -D PB_FIELD_16BIT=1 -c /tmp/pear/temp/grpc/src/core/lib/security/credentials/alts/alts_credentials.cc  -fPIC -DPIC -o src/core/lib/security/credentials/alts/.libs/alts_credentials.o
In file included from /tmp/pear/temp/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26:0,
                 from /tmp/pear/temp/grpc/src/core/lib/security/credentials/alts/alts_credentials.h:26,
                 from /tmp/pear/temp/grpc/src/core/lib/security/credentials/alts/alts_credentials.cc:21:
/tmp/pear/temp/grpc/src/core/tsi/alts/handshaker/transport_security_common_api.h:24:23: fatal error: pb_decode.h: No such file or directory
 #include "pb_decode.h"
                       ^
compilation terminated.
Makefile:644: recipe for target 'src/core/lib/security/credentials/alts/alts_credentials.lo' failed
make: *** [src/core/lib/security/credentials/alts/alts_credentials.lo] Error 1
ERROR: `make' failed
```

https://source.cloud.google.com/results/invocations/787f7c10-1a5e-4b2d-b5ba-8493fa545ea6/targets/github%2Fgrpc/tests

**Comment by jtattermusch** [comment]
@dgquintas   it looks the the problem might have to do with your PR https://github.com/grpc/grpc/pull/15595. Please help with fixing.

**Comment by jtattermusch** [comment]
Also failing on MacOS 
https://source.cloud.google.com/results/invocations/6ed9981e-f2b3-4f47-a4b0-396fbe330d53/targets/github%2Fgrpc/tests

**Comment by dgquintas** [comment]
@ZhouyihaiDing can you show me where are the `CFLAGS` or similar (in particular, the `-I` argument(s) to the compiler) are setup for PHP? We just need to add `-Ithird_party/nanopb` to the compiler args.

**Comment by ZhouyihaiDing** [comment]
Hi @dgquintas , here are the config file for [linux/mac](https://github.com/grpc/grpc/blob/master/config.m4#L10:3) and [windows](https://github.com/grpc/grpc/blob/master/config.w32#L647:75). Should we also add `-D PB_FIELD_32BIT=1`?

**Comment by dgquintas** [comment]
yeah, that PR #15806 looks good. I thought PHP got its build params from cmake, sorry about this.

**Comment by jtattermusch** [comment]
Fix confirmed, thanks!

https://source.cloud.google.com/results/invocations/94c3c25f-dfc1-4a63-ae43-be3010b95820/targets
