### ISSUE TITLE
Unify PyPI grpcio-{reflection,health_checking,status...} under one roof

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15830]
There are an increasing number of helper packages for gRPC that are published, or we want to publish, on PyPI, which are helpers/utilities for conventional use cases of gRPC but not part of the core package, because they make stronger assumptions and have dependencies like `protobuf`. Instead of serving each module as a separate PyPI package, we should combine them under one roof "grpcio-proto-utils" or something and have that package include all of these small modules.

To ensure backward compatibility, the likely plan would be uploading a final version of reflection and health checking that depends on `grpcio-proto-utils` and after that we would stop uploading those packages and instead fall back on the new utils package.

**Comment by mehrdada** [comment]
cc @srini100

**Comment by lidizheng** [comment]
Hi Mehrdad. Separating the extensions into multiple packages is a valid idea, many Python library does that. With proper documentation and examples, developers are fine using those big or small extensions. For example, in `Flask` they have 68 different extension packages [Extension List](http://flask.pocoo.org/extensions/), and it is the same for `Sphinx`, `Requests`, etc..

**Comment by srini100** [comment]
Looks like there are other pkgs like grpcio-{gcp, opentracing} that are not in our control and those can proliferate anyway.

**Comment by mehrdada** [comment]
The problem that you will face is interdependencies across these especially when status comes into play. I strongly discourage you from going this route. I don't think the other packages are a good metaphor here at all, since these things are supposed to be part of main gRPC package and the only reason they are not is that we do not want to add an additional protobuf dependency. However, the examples you mentioned are all third party projects that have completely unrelated things. What users really want is a package that brings in all the bells and whistles necessary to utilize a convention-conforming protobuf service.

But it's ultimately your call whether to cargo culting the existing poor design or use the opportunity to fix it.

**Comment by ericgribkoff** [comment]
Closing this for now. There has not been clear demand from multiple users that would motivate a change in the existing package structure, nor many (any?) reported problems with the status quo.
