### ISSUE TITLE
Node javascript objects of invalid type fails silently

### ISSUE THREAD

**Issue by psaelango** [grpc/grpc#15837]
### What version of gRPC and what language are you using?
 1.12.3
 
### What operating system (Linux, Windows, …) and version?
 WIndows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python version
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
```
// Gateway service 
service Gateway
{
    rpc Example (Cmd) returns (Rsp) {}
}
message Distance    { int64  millimetres = 1; }
message Cmd{
    Distance measurement=1;
}
message Rsp{
     string success = 1
}

// Node Server
var cmd = {
   measurement: {
       millimeters: 5.5
    }
}
var client = new proto.Gateway("localhost:50001",combined_creds);
client.example(cmd,function(err,response){
     if(err){
       console.log(err);// Didn't print anything
     }
     else{
       console.log(response); // Didn't print anything
     }
});
```
### What did you see instead?
Neither error messages & nor response were returned. Even it seems the call didn't even reach the endpoint.
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by murgatroid99** [comment]
There is some missing information here. What is `system_object`? Does the actual code have `console.log(res)` when you called the parameter `response`? Have you verified that the server is running on the local machine and bound to port 50001?

**Comment by psaelango** [comment]
My apologies. system_object and response is from my real code. I've changed the example I've given above. Please refer again.

**Comment by murgatroid99** [comment]
And you've confirmed that the server is definitely running on the same machine, and bound to port 50001?

**Comment by psaelango** [comment]
Yes. If I send millimeters as Integer instead of floats it works fine.
var cmd = {
   measurement: {
       millimeters: 5 //instead of 5.5
    }
}

**Comment by murgatroid99** [comment]
OK, that is a real problem. Are you using `grpc.load` to load your `.proto` files? If so, I would suggest trying out `@grpc/proto-loader`, which is used with the `grpc.loadPackageDefinition` function. It uses a newer version of Protobuf.js that may not have the same problem.

**Comment by nicolasnoble** [comment]
The difference between the two is that the former uses protobufjs 5 and the latter uses protobufjs 6 (currently). They don't have the same APIs and terminology in how they handle data.

I'd refer you to https://github.com/dcodeIO/protobuf.js to understand better protobufjs 6's behavior. I don't think that protobufjs 5 behavior was well documented however.

**Comment by murgatroid99** [comment]
I'm reopening this. Our library appears to be doing something weird here, and the fact that you can avoid the problem entirely by changing the protobuf implementation doesn't fix that.
