### ISSUE TITLE
sequential_connectivity_test gives os error - Too many open files

### ISSUE THREAD

**Issue by sab24** [grpc/grpc#15833]
### What version of gRPC and what language are you using?
grpc 1.12 c++
 
### What operating system (Linux, Windows, …) and version?
Macos 10.13
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple LLVM version 9.1.0 (clang-902.0.39.2)
 
### What did you do?
make
make test
 
### What did you expect to see?
Successful tests
 
### What did you see instead?
Unsuccessful tests

This is what is shown in the console. If there are more logs I can upload those.

E0621 15:50:23.159045000 140735486636928 channel.cc:98]                channel stack builder failed: {"created":"@1529589023.159031000","description":"resolver creation failed","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":695}
[RUN]     Testing secure_endpoint_test
D0621 15:50:23.169159000 140735486636928 test_config.cc:391]           test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
[RUN]     Testing sequential_connectivity_test
D0621 15:50:23.892377000 140735486636928 test_config.cc:391]           test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0621 15:50:23.893037000 140735486636928 sequential_connectivity_test.cc:55] TEST: insecure
E0621 15:50:29.258526000 123145436979200 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0621 15:50:29.258603000 123145436979200 ev_poll_posix.cc:900]         pollset_work: {"created":"@1529589029.258577000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:29.258620000 123145436979200 backup_poller.cc:124]         Run client channel backup poller: {"created":"@1529589029.258577000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:34.259215000 123145435906048 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0621 15:50:34.259298000 123145435906048 ev_poll_posix.cc:900]         pollset_work: {"created":"@1529589034.259270000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:34.259317000 123145435906048 backup_poller.cc:124]         Run client channel backup poller: {"created":"@1529589034.259270000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:39.258853000 123145436979200 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0621 15:50:39.258947000 123145436979200 ev_poll_posix.cc:900]         pollset_work: {"created":"@1529589039.258909000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:39.258977000 123145436979200 backup_poller.cc:124]         Run client channel backup poller: {"created":"@1529589039.258909000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:44.260830000 123145435906048 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0621 15:50:44.260900000 123145435906048 ev_poll_posix.cc:900]         pollset_work: {"created":"@1529589044.260872000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:44.260924000 123145435906048 backup_poller.cc:124]         Run client channel backup poller: {"created":"@1529589044.260872000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:49.261191000 123145436979200 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0621 15:50:49.261268000 123145436979200 ev_poll_posix.cc:900]         pollset_work: {"created":"@1529589049.261244000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:49.261285000 123145436979200 backup_poller.cc:124]         Run client channel backup poller: {"created":"@1529589049.261244000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:54.262129000 123145435906048 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0621 15:50:54.262200000 123145435906048 ev_poll_posix.cc:900]         pollset_work: {"created":"@1529589054.262173000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:54.262217000 123145435906048 backup_poller.cc:124]         Run client channel backup poller: {"created":"@1529589054.262173000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0621 15:50:54.551892000 140735486636928 sequential_connectivity_test.cc:91] assertion failed: ev.success == true

*******************************
Caught signal SIGABRT
  no backtrace
/bin/sh: line 1:  7566 Abort trap: 6           /Users/user/Documents/GRPC/grpc/bins/opt/sequential_connectivity_test
test sequential_connectivity_test failed
make: *** [test_c] Error 1

**Comment by sreecha** [comment]
@sab24 can you do `ulimit -a` .
Maybe the limits are set to low by default. Can you please retry by increasing the max number of open descriptors allowed? (here is an example of how to do it on mac: https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard)

**Comment by sab24** [comment]
Yes, increasing the limit of open files solves that issue :)
