### ISSUE TITLE
Feature request: one protoc plugin for all languages

### ISSUE THREAD

**Issue by anjmao** [grpc/grpc#15842]
Hi, I'm developing React Native mobile app with NodeJs backend and Typescript for both mobile and backend. I also use gRPC for NodeJs, React Native(Swift, Android). In order to generate grpc code for all these languages I need to install grpc-tools(node), grpc-swift, grpc-java. I even needed to compile swift and java plugins because I was not able to find precompiled binaries for osx.

Proposal. Wouldn't it be better to write one extendable plugin which can generate grpc code form proto files to any supported language. Plugin can be written in Go and it should be really easy to do this by using some blueprint templates.

Current workaround: Because I don't want other my team members to spend time searching for all these plugins and compiling them locally, I created https://github.com/anjmao/grpc-plugins and pushed npm package. All I need to do is to install this npm package to my NodeJs project dev dependencies, but this is not ideal because not everyone is using NodeJs.

Sorry if this is a duplicate, I couldn't find similar issue.
BTW, I could help writing such plugin if it make sense at all, maybe there is some important logic behind that I'm missing.

Cheers.

**Comment by nicolasnoble** [comment]
We have a different solution in mind for this that involves docker instead. Stay tuned.
