### ISSUE TITLE
Error updating PHP docker image

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#1585]
```
grpc_update_image php
```
Things run fine until
```
Step 10 : RUN cd /var/local/git/grpc/src/php && ./bin/run_tests.sh
 ---> Running in c7fa3a4362eb
PHP Warning:  PHP Startup: Unable to load dynamic library '../ext/grpc/grpc.so' - ../ext/grpc/grpc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Deprecated option "--strict" used

PHP Fatal error:  Class 'Grpc\Server' not found in /var/local/git/grpc/src/php/tests/unit_tests/CallTest.php on line 39
2015/05/13 22:03:23 The command [/bin/sh -c cd /var/local/git/grpc/src/php && ./bin/run_tests.sh] returned a non-zero code: 255
grpc_dockerfile_install:: build of grpc/php <- /var/local/dockerfile/grpc_php
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
stanleycheung@gummybear:~/grpc$
```
php image build seems to have failed since 2 days ago
```
stanleycheung@grpc-docker-testclients:~$ sudo docker images | grep php
0.0.0.0:5000/grpc/php_base           latest              6edbc3e7448e        2 days ago          1.559 GB
grpc/php_base                        latest              6edbc3e7448e        2 days ago          1.559 GB
0.0.0.0:5000/grpc/php                latest              76ef2c26de8b        2 days ago          1.45 GB
grpc/php                             latest              76ef2c26de8b        2 days ago          1.45 GB
```
Michael said, "I suspect that this is caused by how the run_tests.sh script is written. It currently looks for the file in a different place depending on the version of PHP. The location you mentioned corresponds to PHP 5.6, so my guess is that an update to PHP 5.6 changed where it puts that file."

The last success build of the grpc/php image is running PHP 5.5
```
stanleycheung@grpc-docker-testclients:~$ sudo docker run grpc/php bin/bash -l -c 'cd /var/local/git/grpc/src/php && php --version'
stdin: is not a tty
PHP 5.5.23-1~dotdeb.2 (cli) (built: Mar 26 2015 02:24:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
stanleycheung@grpc-docker-testclients:~$ 
```

But, the last success build of the grpc/php_base image is running PHP 5.6!
```
stanleycheung@grpc-docker-testclients:~$ sudo docker run grpc/php_base bin/bash -l -c 'php --version'
stdin: is not a tty
PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
```

I wonder why, we explicitly have these lines in grpc_php_base/Dockerfile
```
RUN echo "deb http://packages.dotdeb.org wheezy-php55 all" >> /etc/apt/sources.list.d/dotdeb.list
RUN echo "deb-src http://packages.dotdeb.org wheezy-php55 all" >> /etc/apt/sources.list.d/dotdeb.li\
st
RUN wget http://www.dotdeb.org/dotdeb.gpg -O- |apt-key add -
```

I tested that and it only installs PHP 5.5

**Comment by stanley-cheung** [comment]
I can reproduce the error in a fresh PHP 5.6 install. Looks like the grpc.so module is still found in the ext/grpc/modules directory for PHP 5.6

so this line in the Dockerfile may be unnecessary

```
module_dir=`php --version | grep -q 'PHP 5.6' && echo '../ext/grpc' || echo '../ext/grpc/modules'`
```

**Comment by murgatroid99** [comment]
Can you confirm that replacing that line with `module_dir=../ext/grpc/modules` makes the script work under 5.6? If so, I think you should send a pull request with that change in that file and the other test running scripts.

**Comment by stanley-cheung** [comment]
Yes I confirmed that if I do ```module_dir=../ext/grpc/modules``` in PHP 5.6 the run_tests.sh script just works

**Comment by stanley-cheung** [comment]
I run ```grpc_update_image php_base``` but the result is the same. the grpc/php_base image still got PHP 5.6 despite
```
stanleycheung@grpc-docker-testclients:~$ sudo docker run grpc/php_base bin/bash -l -c 'cat /etc/apt/sources.list.d/dotdeb.list'
stdin: is not a tty
deb http://packages.dotdeb.org wheezy-php55 all
deb-src http://packages.dotdeb.org wheezy-php55 all
stanleycheung@grpc-docker-testclients:~$ 
```
```
stanleycheung@grpc-docker-testclients:~$ sudo docker run grpc/php_base bin/bash -l -c 'php --version'
stdin: is not a tty
PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
stanleycheung@grpc-docker-testclients:~$
```

**Comment by stanley-cheung** [comment]
Summary: 2 issues discovered
 1. for some still unknown reason, our grpc/php_base docker image got PHP 5.6 installed despite the dockerfile explicitly asks for PHP 5.5 to be installed. I cannot reproduce this issue, i.e. by following the dockerfile exactly in a fresh VM, I got PHP 5.5 installed.
 2. for some unknown reason, the location where the grpc php extension is built has changed from ```ext/grpc/grpc.so``` to ```ext/grpc/modules/grpc.so```, which is in line with previous PHP version. So we are going to update the run_tests.sh script to reflect that change

**Comment by stanley-cheung** [comment]
For issue 1, I think the mismatch is probably because debian:wheezy vs debian:jessie. The latter by default installs PHP 5.6. 

This is no longer an issue.
