### ISSUE TITLE
Error when using google cloud vision

### ISSUE THREAD

**Issue by antoineChammas** [grpc/grpc#15856]
### What version of gRPC and what language are you using?
 
grpcio version 1.12.1 - Python
 
### What operating system (Linux, Windows, …) and version?
 
Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 3.5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
I simply tried to import google.cloud and google.cloud.vision, making sure they work, and the following error appears every time I try to do so:
 from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc'

### What did you expect to see?

the import being successfull .
 
### What did you see instead?
 
The import failing and the error appearing.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

I don't think so

**Comment by antoineChammas** [comment]
I tried redownloading/updating grpc using pip but it is giving me the following error:

"\AppData\Local\Temp\pip-install-_fq5ra2o\grpc\grpc\rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in \AppData\Local\Temp\pip-install-_fq5ra2o\grpc\

I have downloaded it via grpcio without any problems, but the google cloud vision library has grpc as a requirement, which is causing me issues.

**Comment by antoineChammas** [comment]
problem was fixed after running python -m pip install grcpio --ignore-installed

**Comment by thekev63** [comment]
I think you might have meant python -m pip install grpcio --ignore-installed

**Comment by antoineChammas** [comment]
yes, that's correct, sorry for the typo
