### ISSUE TITLE
PHP distrib tests failing on linux and macos

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#15865]
After https://github.com/grpc/grpc/pull/15840 , distrib tests fail for [linux](https://sponge.corp.google.com/target?id=75b866ea-0b9f-4be6-a2ae-113e3b2bbada&target=grpc/core/master/linux/grpc_distribtests&searchFor=&show=ALL&sortBy=STATUS) and [mac](https://sponge.corp.google.com/target?id=0ba757f3-da4e-4444-8581-84a1640be162&target=grpc/core/master/macos/grpc_distribtests&searchFor=&show=ALL&sortBy=STATUS):

```
In file included from /tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.h:27:0,
                 from /tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc:82:
/tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.h:7:111: fatal error: src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb/v1/google/protobuf/duration.pb.h: No such file or directory
 #include "src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb/v1/google/protobuf/duration.pb.h"
```

However, that file does exist: https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb/v1/google/protobuf/duration.pb.h

Is there anything special about PHP?

**Comment by ZhouyihaiDing** [comment]
`package.xml` should have two `*.h` files, while it doesn't.
I am trying to find out why buildgen doesn't generate those 2 header files from the template.
