### ISSUE TITLE
Test flake: //test/core/end2end:h2_full+workarounds_test@shutdown_finishes_calls@poller=epollex

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#15861]
Seen on #15839 
https://source.cloud.google.com/results/invocations/3baf07a8-6b9d-45de-8701-37f9fd118251/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_full%2Bworkarounds_test@shutdown_finishes_calls@poller%3Depollex/tests

<img width="270" alt="screen shot 2018-06-25 at 10 02 33 am" src="https://user-images.githubusercontent.com/8952658/41864447-e67d4aae-785e-11e8-8a36-5c8a5de1f973.png">

**Comment by dgquintas** [comment]
Log:
```
-----------------------------------------------------------------------------
D0622 22:57:15.492478628      18 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
E0622 22:57:15.494412671      18 cq_verifier.cc:273]         cq returned unexpected event: OP_COMPLETE: tag:0x1 OK
E0622 22:57:15.494447123      18 cq_verifier.cc:280]         expected tags:
tag(101) GRPC_OP_COMPLETE success=1 test/core/end2end/tests/shutdown_finishes_calls.cc:137
```
@hcaseyal , it's best to add the relevant lines from the "target log" tab, even though I don't think we have the issue of test logs expiring, as we used to.

**Comment by jtattermusch** [comment]
This one is likely to have been solved by closing https://github.com/grpc/grpc/issues/14240, but since the test log doesn't have yet GRPC_VERBOSITY set to debug (introduced later) it's hard to tell for sure.
