### ISSUE TITLE
Test flake: bins/dbg/h2_full+workarounds_nosec_test max_connection_age GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#15860]
Seen on PR #15839 

https://source.cloud.google.com/results/invocations/97023f40-71d8-4d2c-8eac-ae75b512780d/targets/github%2Fgrpc%2Fc_macos_dbg_native/tests

<img width="1152" alt="screen shot 2018-06-25 at 9 57 40 am" src="https://user-images.githubusercontent.com/8952658/41864279-3e1e9d0e-785e-11e8-80f8-d1a9de2a15ce.png">

**Comment by dgquintas** [comment]
Also happening on mac: https://sponge.corp.google.com/target?id=253038f5-f30a-4b44-a944-b9cf1d4dbb07&target=github/grpc/c_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS at master.

**Comment by yashykt** [comment]
Is this seen only on MacOS?

**Comment by dgquintas** [comment]
Yes, I've just confirmed that, my previous comment was misleading. Current failure history: https://screenshot.googleplex.com/ia8u3S8oB56

**Comment by yashykt** [comment]
punting to component owner and MacOS user : @AspirinSJL :)

**Comment by AspirinSJL** [comment]
I can't reproduce it locally. Trying a larger `-a`.

I am not very surprised though, since this is macOS + poll :) 

"no event received" sounds like a timeout (might be related to #15027).

**Comment by AspirinSJL** [comment]
Not seen for  > 10 months.
