### ISSUE TITLE
PHP: Persistent channel enhancement

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#15874]
In PHP C extension level, we have a map saving `grpc_channel` with the key `target`, and have an upper bound for the number of the `grpc_channel` can be created. For example, when we do `new Grpc\Channel('localhost:50051', ['‘grpc_target_persist_bound’' => 10])`, we allow that there can be up to 10 `grpc_channel` created for connecting to the `localhost:50051`.

The upper bound is used to keep the memory from growing to infinity, but that 10 `grpc_channel` already created can never be freed too. We may need a better strategy to persist the `grpc_channel`.

**Comment by apolcyn** [comment]
Is this still relevant? If so, nit: can we document the motivation in the bug description?

**Comment by stanley-cheung** [comment]
Unlikely to get to this any time soon. Can close for now. With the labels we can easily find this back.
