### ISSUE TITLE
PHP: move PHP code downloaded by composer into C extension

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#15875]
Currently when we want to install and use gRPC, we need to
```
pecl install grpc # to install the definition of objects like Grpc\Channel, Grpc\Call
composer install grpc # to install the stub and call library
```

Moving gRPC code from PHP to c extension is doable. By doing so, it will be easier the user only need to download gRPC by pecl.

**Comment by stanley-cheung** [comment]
Not going to do this.
