### ISSUE TITLE
Heavy write loads prevent keepalive from working

### ISSUE THREAD

**Issue by forestphoenix** [grpc/grpc#15871]
### What version of gRPC and what language are you using?

C++
Tested with Grpc 1.12.0, 1.12.1, 1.13-pre3

### What operating system (Linux, Windows, …) and version?

Linux: Xubuntu 16.04 and 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7.3.0
 
### What did you do?

Both server and client have a keepalive of 20 seconds set[1].

The client opens a bidirectional stream.
Both server and client do the following:
- Start a thread that reads (and prints) incoming messages
- Loop forever:
  - Write messages with a payload of 100KB
  - Wait 100 milliseconds
 
I disconnect server and client (physically, by pulling the cable out)

Both server and client write one or two messages, then get stuck in the `Write` calls.

### What did you expect to see?

Both server and client abort the `Write` (and ``Read`) calls after 20 seconds because of the keepalive timeout.

### What did you see instead?

Both server and client abort the `Write` (and ``Read`) calls after **15 minutes**.
 
### Anything else we should know about your project / environment?

When I send only one byte as payload,
- the timeout is detected after 20 seconds 
- neither client nor server get stuck in `Write` calls.

[1] The precise Options were:
`GRPC_ARG_KEEPALIVE_TIME_MS = 10000` and
`GRPC_ARG_KEEPALIVE_TIMEOUT_MS 10000`

**Comment by forestphoenix** [comment]
A gist to reproduce this issue:
https://gist.github.com/forestphoenix/c2e141bc3f19ff106617ebca3742432d

@yashykt This issue looks very similar to #14717, could they be related?

**Comment by yashykt** [comment]
With http tracing enabled, do you see pings actually being sent?

I can totally see this happening though. We only start the keepalive timer when the HTTP2 transport layer is ready to send more bytes down to the TCP. If the HTTP2 transport itself is blocked on it's previous write completing (which at a lower level means that the fd is not writable), then we cannot initiate a ping.

**Comment by yashykt** [comment]
The bug in #14717 was a different issue (a ping won't be sent when another ping is in flight).

**Comment by srini100** [comment]
@yashykt This issue is straightforward to reproduce. It doesn't require load. One way to reproduce is to simply hang the server while server is streaming a response (say one byte per second) in a unary-streaming case where client is done sending its request and simply reading the streamed response. At this time the keepalive on client doesn't detect that server has stopped responding.

I can also reproduce this issue with unary-unary but that is very inconsistent. Will try to find a way to consistently reproduce it.

**Comment by yashykt** [comment]
I take back my original hypothesis. I did not notice that the following two channel arguments were not being set. Pleaes set GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS to 10000 and GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA to 0.

@forestphoenix your example did not compile, so I have no way of verifying your case, but @srini100 's example works as intended after setting these two arguments.

**Comment by forestphoenix** [comment]
@yashykt thanks for the tip, but setting the arguments did not seem to change much:

With the suggested arguments set, the `Read` calls do one of the following:
- return after 20 seconds (the desired behavior)
- return after 15 minutes

The `Write` calls always return after 15 minutes. 

With a reduced payload, everything works as expected.

PS: I fixed the gist and added the suggested arguments.

**Comment by yashykt** [comment]
This should have been solved by #16419
