### ISSUE TITLE
grpc client  binding to specific network interface

### ISSUE THREAD

**Issue by choujayyl** [grpc/grpc#15886]
My PC  has multiple network cards, all of them connected to different networks and functioning 
 properly.
 How does grpc client determine which NIC to use ?
 I know how to set socket that bind a specify IP address.So what about grpc?

**Comment by nicolasnoble** [comment]
For these kind of questions, please use the mailing list instead. Issues here are to report bugs, not ask questions.

That being said, simply use the IP address of said interface when binding your server.

**Comment by choujayyl** [comment]
I said client,not server.

**Comment by srini100** [comment]
The NIC used is based on the route the OS picks for the host your client is connecting to.
Please post further questions on https://groups.google.com/forum/#!forum/grpc-io
