### ISSUE TITLE
bazel test flake: //test/core/end2end:h2_full_test@cancel_after_client_done@poller=epollsig

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#15897]
Seen on PR #15879 and I wasn't able to reproduce it locally.

![screenshot from 2018-06-27 12-49-51](https://user-images.githubusercontent.com/8952658/41996089-a301e00e-7a08-11e8-96e2-4442066c52cd.png)

https://source.cloud.google.com/results/invocations/fefbeb32-1417-4da3-9b3a-efd241b08240/log

![screenshot from 2018-06-27 12-51-46](https://user-images.githubusercontent.com/8952658/41996156-e3491f9c-7a08-11e8-93e5-9d64c3042dce.png)

**Comment by jtattermusch** [comment]
Last failure on master is from 2018-08-11. Also, all known instances have happened before GRPC_VERBOSITY=debug was set for foundry test, so we don't have any useful data to diagnose.
