### ISSUE TITLE
PHP: Automate memory leak check during the test

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#15899]
Currently, we are doing the memory check for PHP manually with the PR https://github.com/grpc/grpc/pull/14276, which copies all tests from phpunit to a single PHP script. This is because `phpunit` itself has memory leaks can it is not easy to exclude them.

We need to either find a way to do the check automatically without copying all tests into a PHP script, or fix the leak from the phpunit, so each pull request will check the memory usage automatically.

**Comment by stanley-cheung** [comment]
Fixed by #17862
