### ISSUE TITLE
round robin load balancing on channels sharing sub-channels broken

### ISSUE THREAD

**Issue by tomhostyn** [grpc/grpc#15892]
### What version of gRPC and what language are you using?
```
$ python --version
Python 2.7.13

$ pip freeze  (selected lines)
grpcio==1.12.0
protobuf==3.5.2.post1

```
### What operating system (Linux, Windows, …) and version?
```
$ uname -a
Linux instance-3 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
 
```
### What runtime / compiler are you using (e.g. python version or version of gcc)
```
$ python --version
Python 2.7.13

``` 
### What did you do?

I enable round robin load balancing on my python client.  I setup my channel as follows:

```
 opts = [("grpc.lb_policy_name", "round_robin",)]
 channel = grpc.insecure_channel('localhost:50051' , opts)

```

I updated the hello world example to repoduce this issue: 
https://github.com/tomhostyn/grpc/blob/round_robin_issue/examples/python/helloworld/greeter_client.py

I tried to reproduce the same issue in the cpp client, but that works as expected
https://github.com/tomhostyn/grpc/blob/round_robin_issue/examples/cpp/helloworld/greeter_client.cc

 
### What did you expect to see?

all messages sent 
 
### What did you see instead?

After sending 1 message succesfully, my client blocks.
when the modified example is executed, the output is as expected until :
```
========  with round robin =======
Connection OK
Greeter client received: Hello you
Connection OK
```

execution with verbose output 
```
$ env | grep 
GRPC
GRPC_TRACE=all
GRPC_VERBOSITY=DEBUG
$ python greeter_client.py &> log
^C^C^C

```
log output at https://pastebin.com/rxyp6huv

Closing the channel fixes the problem.  see discussion:
[](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/grpc-io/cN_E2ASt5LA/uPBm6P7RAAAJ)

### Anything else we should know about your project / environment?
No

**Comment by tomhostyn** [comment]
please see also the discussion on [grpc-io]  google groups

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/grpc-io/cN_E2ASt5LA/uPBm6P7RAAAJ

**Comment by srini100** [comment]
This is not a Python specific issue. I can reproduce this issue using C++ client where two threads open channels to same host with RR policy. This is similar to how Python behaves without explicit channel.close() in OP's code. Log is similar to OP's log where pick seems to stall even though sub-channels are ready.

**Comment by srini100** [comment]
[C++ repro code](https://github.com/srini100/repro_code/tree/master/rr_lb_issue)

**Comment by dgquintas** [comment]
@tomhostyn , the issue should be solved now. If you are impatient, please sync against master's HEAD and try again :)
