### ISSUE TITLE
Run gRPC tests on 32-bit binary as well

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#15903]
We currently do not run any tests on 32-bit binaries. This is helpful since gRPC is used in several 32-bit systems.

**Comment by jtattermusch** [comment]
As a side note, it is not entirely true that we are not running 32bit tests. We do run:
- C (but not c++) and tests on a 32bit linux distro  in the portability suite (running daily on master)
https://source.cloud.google.com/results/invocations/6fd1390b-82f4-4f2f-bb6c-fb8e0e4f2ef7/targets/github%2Fgrpc%2Fc_linux_dbg_native_x86_default/tests
- on windows we are running both 32bit and 64bit tests (32 bit tests run even on presubmit).

**Comment by sreecha** [comment]
Hi @jtattermusch , Do you know if there was a reason for not running C++ tests on 32-bit platforms?

**Comment by jtattermusch** [comment]
@sreecha   I think we didn't enable C++ 32bit tests because they aren't all passing.

 I started an ad-hoc run of C++ 32bit tests to see the results and it looks like some of the `qps_json_driver` and `json_run_localhost` tests are failing consistently:
https://source.cloud.google.com/results/invocations/25b9bc7a-4ae3-47ec-9aa5-9d10511705ea/log

This is my experimental branch:
https://github.com/grpc/grpc/compare/master...jtattermusch:x86_adhoc_run

after patching run_tests_matrix.py you can reproduce the issues locally with
`tools/run_tests/run_tests.py -l c++ --arch x86 --use_docker`

**Comment by jtattermusch** [comment]
suspicious error message for some of the tests is  `Starting client on localhost:-1 (worker #1)`
```
2018-08-20 11:18:21,153 RUNNING SCENARIO: cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_insecure
D0820 11:18:20.945134221   20024 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0820 11:18:20.945566588   20024 ev_epollsig_linux.cc:78]    epoll engine will be using signal: 40
D0820 11:18:20.945585694   20024 ev_posix.cc:163]            Using polling engine: epollsig
D0820 11:18:20.945619144   20024 dns_resolver.cc:348]        Using native dns resolver
I0820 11:18:20.945698699   20024 server_builder.cc:270]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0820 11:18:20.945832832   20024 server_builder.cc:270]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0820 11:18:20.945933804   20024 driver.cc:275]              Starting server on localhost:-1 (worker #0)
I0820 11:18:20.946215345   20028 qps_worker.cc:232]          RunServerBody: about to create server
I0820 11:18:20.946269250   20028 qps_worker.cc:70]           Starting server of type SYNC_SERVER
I0820 11:18:20.947902086   20028 server_builder.cc:270]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0820 11:18:20.948272662   20028 qps_worker.cc:240]          RunServerBody: server created
I0820 11:18:20.948345215   20028 qps_worker.cc:247]          RunServerBody: creation status reported
I0820 11:18:20.948412941   20024 driver.cc:331]              Starting client on localhost:-1 (worker #1)
D0820 11:18:20.948481522   20024 driver.cc:353]              Client 0 gets 64 channels
I0820 11:18:20.948669921   20029 qps_worker.cc:189]          RunClientBody: about to create client
I0820 11:18:20.948693709   20029 qps_worker.cc:51]           Starting client of type ASYNC_CLIENT STREAMING 0
I0820 11:18:20.953976718   20029 client_async.cc:226]        Sizing async client to 32 threads
```
