### ISSUE TITLE
Add contracts for codegen and move method BindService into ServiceBinder

### ISSUE THREAD

**Issue by m-andrei** [grpc/grpc#15913]
### What version of gRPC and what language are you using?
 Proto-3, .net core
 
### What operating system (Linux, Windows, …) and version?
 n/m
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 n/m
 
### What did you do?
Hello guys, i tried to create some simple extension for .net developers which should help combine asp.net framework code base with grpc libraries.

For now i have simple project: 
https://github.com/m-andrei/grpc-example-for-.net-core
Which show my purposes, everything perfect except one thing: i can't move it into separate library due to grpc server codegen don't have interface contracts and method BindService stricly tied on codegen implementation. 
I offer to add simple interface for Server and move "BindService" method into separate class like:

`
        
    public interface IGrpcService {}
    public interface IGrpcServiceBinder
    {
        ServerServiceDefinition BindService(IGrpcService serviceImpl);
    }

    //CodeGen then will be like:
    namespace Grpc.Example
    {
        /// <summary>Base class for server-side implementations of Greeter</summary>
        public abstract partial class GreeterBase : IGrpcService
        {
            public virtual Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
            {
                throw new RpcException(new Status(StatusCode.Unimplemented, ""));
            }
        }

        //and:

        public class GreeterBaseBinder : IGrpcServiceBinder
        {
            public ServerServiceDefinition BindService(IGrpcService serviceImpl)
            {
                GreeterBase service = (GreeterBase) serviceImpl;
                return ServerServiceDefinition.CreateBuilder()
                    .AddMethod(__Method_SayHello, service.SayHello).Build();
            }
        }
    }
`
Both IGrpcService IGrpcServiceBinder should be in Grpc.Core library.
This will allow everyone to create they own nuget packages and share it.
I believe almost everyone faced with that issue when tried to share they code with other teams in company.

**Comment by jtattermusch** [comment]
We now have these:
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/ServiceBinderBase.cs
and
https://github.com/grpc/grpc/pull/17778
which together seems to address the issue you're having.

also,  https://github.com/grpc/grpc-dotnet is something you might be interested in.
