### ISSUE TITLE
Proposal: expose grpc_cq_begin_op/grpc_cq_end_op

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#15921]
Currently there seems to be no way to implement complicated asynchronous operation with grpc library. For example, an application may contact database when handling a grpc call, and the protocol between application and database may not be grpc. So if using asynchronous API of grpc, the database query needs to be executed synchronously.

When using C++ API, people can get around this by using the alarm API. As the alarm can be used to wake up the completion queue and continue to handle the request when the database responds. But it doesn't work for people who just want to use grpc c core as alarm APIs have been removed.

I proposes to expose `grpc_cq_begin_op/grpc_cq_end_op` API to users. So they can implement whatever asynchronous operations they want without relying on the tricky way alarm provides.

**Comment by sreecha** [comment]
Hi @BusyJay , I am not opposed to this proposal but this seems a bit lower priority at the moment. 

I welcome contributions from the community on this. A good starting point is to create a gRFC proposal for this (https://github.com/grpc/proposal) *before* creating a code-change PR
