### ISSUE TITLE
How to set the maximum message size in Python and C#?

### ISSUE THREAD

**Issue by mlstudies** [grpc/grpc#15922]
I have the same problem as https://github.com/grpc/grpc/issues/7882 where I need to post a relatively larger byte array exceeding 4MB.

This previous issue has a solution that use ServerBuilder::SetMaxMessageSize() in C++ to change the default limit. Anyone knows how to access this "ServerBuilder" and change the limit in Python and C#? Thanks a lot!

**Comment by mehrdada** [comment]
Have you tried setting the channel arg via the respective APIs in C# and Python?
https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L153

**Comment by mlstudies** [comment]
OK thanks. This can be done by setting the "options" argument when you create the server or client, for example

```
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10), options=[(cygrpc.ChannelArgKey.max_send_message_length, -1),
                                                                              (cygrpc.ChannelArgKey.max_receive_message_length, -1)])
```

**Comment by mehrdada** [comment]
Cool. I'm glad that worked out!

**Comment by yyf1986** [comment]
when I user python2.7 is ok， but user python3.6 is not ok

**Comment by mehrdada** [comment]
@yyf1986 can you please share a code snippet that does not work?
