### ISSUE TITLE
Test flake: grpc/core/pull_request/macos/grpc_build_artifacts

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#15930]
In PR #15879, the Artifact Build MacOS test failed with the following error message:

ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://api.rubygems.org/quick/Marshal.4.8/rake-compiler-1.0.4.gemspec.rz)

The test output is here:
https://source.cloud.google.com/results/invocations/b4be2378-1e8c-443a-9e22-f2a6923eafc6/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log

**Comment by bigfacebear** [comment]
In PR #19579, this test failed with the following error:

```
+ venv/bin/python -m pip install twine
Collecting twine
  ERROR: Could not find a version that satisfies the requirement twine (from versions: none)
ERROR: No matching distribution found for twine
2019-07-08 16:34:37,682 FAILED: build_artifact.python_macos_x64_python3.5 [ret=1, pid=63151, time=1822.3sec]
```
[test output](https://source.cloud.google.com/results/invocations/f98bb154-f2e9-488f-85c9-b400ab8dfb3e/targets)
