### ISSUE TITLE
Implement CMake options for building/not building every plugin

### ISSUE THREAD

**Issue by Croydon** [grpc/grpc#15949]
The upcoming 1.14.0 version will have a CMake option for building/not building the C# plugin for the first time.

https://github.com/grpc/grpc/blob/252d3f3b460cf56db2e30d68e566a00cef0304eb/CMakeLists.txt#L42

This is incredible helpful as it allows selective builds, which is neccessary to integrate gRPC nicely in some package managers. I'm working on a Conan package for gRPC (https://github.com/inexorgame/conan-grpc). (see also #15363)

Right now I need to patch the CMakeLists.txt file manually, which is constantly breaking, not reliable and not flexible.

Adding CMake options for building/not building every plugin would make the handling a lot easier.

**Comment by jtattermusch** [comment]
@Croydon  can you describe exactly what is it you're asking for in this issue?

**Comment by Croydon** [comment]
## Current situation (pre 1.14.0)
In order to NOT build plugins for C#, Node, Objective C, PHP, Ruby and Python the only way (I am aware of) is to manually patching the CMakeList.txt on the fly in order to NOT build some or all plugins.

This might look like https://github.com/inexorgame/conan-grpc/blob/da3e8a1de7bd391fc3649964bc155891c96c188c/conanfile.py#L40

This is constantly breaking with changes in the CMakeList.txt in new gRPC releases.


## Situtation with 1.140
1.14.0 introduces the CMake variable `gRPC_BUILD_CSHARP_EXT` which I can simply set to `OFF` in order to NOT build the C# plugins. This also doesn't require anymore to patch manually the CMakeList.txt file (at least for this single plugin), which makes it a lot more reliable, stable and future-proof.

https://github.com/grpc/grpc/blob/252d3f3b460cf56db2e30d68e566a00cef0304eb/CMakeLists.txt#L42

## What I wish for with this issue
Please introduce variables for all plugins which toggle the building or not building of the individual plugin:
  * grpc_ruby_plugin
  * grpc_node_plugin
  * grpc_objective_c_plugin
  * grpc_python_plugin 
  * ... and all other parts of grpc which aren't necessary required

**Comment by Croydon** [comment]
As a side note I'm a bit confused about the terminology within grpc. 
Do you use the terms plugin and extension interchangeable?

If yes, it might be better to settle down with one term.

**Comment by jtattermusch** [comment]
@Croydon   "plugin" and "extension" are two completely different things.  the "grpc_*_plugin" (there's grpc_csharp_plugin too btw) are executables that are plugins for code generating grpc stubs using protoc (the protocol buffer compiler).

The grpc_csharp_ext is a completely different beast - it's the native library loaded by C# that provides the RPC functionality implemented in gRPC C core. A normal user doesn't need to know about grpc_csharp_ext at all, it's basically an implementation details of gRPC C#.

Btw, the cmake file defines various meta targets to build - you don't necessarily need to build all the targets defined in the file, you can choose which target you want to build (e.g. just `libgrpc++`)
Examples: 
https://github.com/grpc/grpc/blob/a93fdfce84533eeb26461d2d457256df43dd8078/CMakeLists.txt#L2738
https://github.com/grpc/grpc/blob/a93fdfce84533eeb26461d2d457256df43dd8078/CMakeLists.txt#L192
Why is that not sufficient for your needs?

**Comment by Croydon** [comment]
@jtattermusch We desire to have the generated CMake files as well. It seems to be the case that only the install target generates those CMake files. At the same time the install target builds everything.

Do I miss something?

**Comment by Croydon** [comment]
Still valid
