### ISSUE TITLE
Investigate latest Cython issue on Windows and unpin Cython

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15956]
Cython has been pinned to 0.28.3 since it is causing failures on Windows (#15953).

This issue tracks the work item of investigation of the windows failure and unpinning cython when it's resolved.

**Comment by lidizheng** [comment]
Related PR #14222 #15953

**Comment by gnossen** [comment]
Blocking https://github.com/grpc/grpc/issues/19243.

**Comment by lidizheng** [comment]
Not seen after unpin Cython in #18408. Distribution tests for all platform passed.
Closing this issue.
