### ISSUE TITLE
Ship Python ARMv6 binary wheels

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15959]
There are various users who are interested in arm6 binary wheels for gRPC Python. An important subset of which rely on gRPC due to its reverse dependency on `google-assistant-sdk` and they want to run it on Raspberry Pi Zero, etc. Some of those users rely on `pywheels.org` to provide binary wheels for them. Interestingly however, pywheels.org tends to substitute `arm7` wheels, if present, and ship them to `arm6` users unmodified, which results in `Illegal instruction` error at runtime for users. (cf https://github.com/googlesamples/assistant-sdk-python/issues/235, https://github.com/googlesamples/assistant-sdk-python/issues/267).

**Comment by mehrdada** [comment]
@matt-kwong @jtattermusch do we have an ETA from Kokoro to let us hook arbitrary devices like Raspberry Pi? Our QEMU build that we use to ship ARMv7 packages for produces garbage ARMv6 packages for some reason so we need to build on an actual device.

**Comment by nicolasnoble** [comment]
@mehrdada the reason is a bug in the compiler. I've found this one the hard way when doing this for node. I should still file a bug. Long story short: the crt files are for arm7, so even when you target arm6, you get binaries with a `_start` that won't run on arm6.

**Comment by nicolasnoble** [comment]
@mehrdada it also means that using qemu on an *arm6* image should work properly, and would be much more reliable than hooking up a raspberry pi zero.

**Comment by mehrdada** [comment]
@nicolasnoble we should chat about this.

**Comment by jtattermusch** [comment]
@mehrdada  FYI we don't have any ETA or clear plan for devices supports in Kokoro. I think your best bet in the short term would be to try to figure out why the crosscompilation produces garbage.

**Comment by mehrdada** [comment]
@jtattermusch sounds good to me--will try to figure something out with @nicolasnoble
