### ISSUE TITLE
Protobuf 3.0.0+ not automatically built

### ISSUE THREAD

**Issue by rjshade** [grpc/grpc#1595]
The instructions in grpc/INSTALL say:

"However, protobuf 3.0.0 isn't in a debian package yet, but the Makefile will
automatically try and compile the one present in third_party if you cloned the
repository recursively, and that it detects your system is lacking it."
-- https://github.com/grpc/grpc/blob/master/INSTALL#L89

However this doesn't seem to work for me. Running "cd grpc && make && sudo make install" gives the following output:

"We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.

Please download and install protobuf 3.0.0+ from:
   https://github.com/google/protobuf/releases"

Is the INSTALL documentation out of date, or is something not working as intended?

This is on Ubuntu (well, Goobuntu), can provide any further information as needed.

**Comment by larsonmpdx** [comment]
do "make install" inside of /thrirdparty/protobuf/ - you're right that it's not automatically installed from a make install in the base directory

**Comment by rjshade** [comment]
Thanks, that gets protoc 3.0.0 installed, but the grpc make install command is still failing to detect it:

 ~/code/grpc master > protoc --version
libprotoc 3.0.0

 ~/code/grpc master > sudo make install
[INSTALL] Installing public C headers
...
[INSTALL] Installing root certificates
We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.


Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

   make verify-install

 ~/code/grpc master > make verify-install
Your system looks ready to go.

**Comment by rjshade** [comment]
This is because "sudo which protoc" and "which protoc" give different output:

$ sudo which protoc
/usr/bin/protoc
$ /usr/bin/protoc --version
libprotoc 2.5.0

$ which protoc
/usr/local/bin/protoc
$ /usr/local/bin/protoc --version
libprotoc 3.0.0

What's recommended: installing protoc into /usr/bin, or configuring grpc to use the protoc in /usr/local/bin?

**Comment by nicolasnoble** [comment]
The output of `sudo make install` is merely a warning at that point. If running `make verify-install` works fine, as the message says "if you believe this message is in error", then you're good to go.

**Comment by rjshade** [comment]
Got it, thanks for your help.

**Comment by arhuaco** [comment]
I still have this issue.

make verify-install gives:

Warning: it looks like protoc 3.0.0+ isn't installed on your system,
which means that you won't be able to compile .proto files for use
with gRPC.

I have the most recent protoc installed.

$ which protoc
/usr/local/bin/protoc

$ whereis protoc
protoc: /usr/local/bin/protoc

I don't remember having this issue before.

**Comment by arhuaco** [comment]
FYI, after a "git pull" things are working ... Somehow the most recent changes helped? I could install GRPC. Thanks.
