### ISSUE TITLE
"assertion failed: pthread_mutex_destroy(mu)" has happend occasionally

### ISSUE THREAD

**Issue by chenkrun** [grpc/grpc#15970]
### What version of gRPC and what language are you using?
protobuf: 3.5.2
grpcio: 1.10.0
grpcio-tools: 1.9.1
python: 2.7.5 
 
### What operating system (Linux, Windows, …) and version?
 CentOS Linux release 7.2.1511 (Core)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python: 2.7.5
 
### What did you do?
I've modified original helloworld example.

Server:
```
# rpc_server.py

import time
from concurrent import futures

import grpc


class RpcCall(rpccall_pb2_grpc.RpcCallServicer):
    ... ...


def serve():
    grpcserver = grpc.server(futures.ThreadPoolExecutor(max_workers=40))
    rpccall_pb2_grpc.add_RpcCallServicer_to_server(RpcCall(), grpcserver)
    channel_content = "node:6668"
    grpcserver.add_insecure_port(channel_content)
    grpcserver.start()

    try:
        while True:
            time.sleep(60*60*24)
    except KeyboardInterrupt:
        grpcserver.stop(0)

if __name__ == "__main__":
    serve()
```

And I add this python script into a systemd service, like this:
```
# rpcserver.service

[Unit]
... ...

[Service]
ExecStart=/usr/bin/python /path/to/script/rpc_server.py
KillMode=process
Restart=on-failure
RestartSec=1s

[Install]
... ...
```
 
### What did you expect to see?
gRPC Server can function properly.
 
 
### What did you see instead?
I find something in my log in /var/log/messages:
```
... ...
python: E0627 ... sync_posix.cc:40] assertion failed: pthread_mutex_destroy(mu) == 0
systemd: rpcserver.service: main process exited, code=killed, status=6/ABRT
systemd: Unit rpcserver.service entered failed state.
... ...
```
This phenomenon is not very regular, and I cannot reproduce it many times.
 
### Anything else we should know about your project / environment?
I add some print logs in the sync_posix.cc, and I find return code of pthread_mutex_destroy(mu) is 16, meaning EBUSY. But I can't do it later.

**Comment by dgquintas** [comment]
I'd suggest trying with a more recent version.

**Comment by ckr815** [comment]
OK, I will try.

**Comment by sreecha** [comment]
@ckr815 : Did you get a chance to try with a recent version of grpc?

**Comment by chenkrun** [comment]
@sreecha Sorry, I haven't replied this information for such a long time.Yes, I try grpcio: 1.13.0, and this problem didn't happen again. I have a question, is 1.10.0 version use tcp short connection, and 1.13.0 use long connection?
