### ISSUE TITLE
python grpcio-tools installs wrong grpcio version

### ISSUE THREAD

**Issue by alertedsnake** [grpc/grpc#15987]
### What version of gRPC and what language are you using?

1.12.0 
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
3.6
 
### What did you do?

If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
I've got a `setup.py` which installs `grpcio-tools==1.12.0`.

### What did you expect to see?
 
I expected `grpcio==1.12.0` to be installed, as the properly-versioned dependency.
 
### What did you see instead?
 
`grpc==1.13.0` was installed, since the [setup.py](https://github.com/grpc/grpc/blob/master/tools/distrib/python/grpcio_tools/setup.py#L222) for this has `grpc>={version}` .

```
Collecting grpcio>=1.12.0 (from grpcio-tools==1.12.0)
  Using cached https://[my-pip-mirror]/[path]/grpcio-1.13.0-cp36-cp36m-manylinux1_x86_64.whl
```

Sure, it ought to be mostly compatible, but this is breaking other packages I'm trying to pin and I cannot find a way to actually do this nicely, without forcing things.

**Comment by mehrdada** [comment]
I don't understand the issue here: `grpcio-tools` of version X requires `grpcio` of *at least* version X, but can work with higher versions of gRPC library as well, which is declared in the requirements. If you need to pin `grpcio` to a certain version, then why wouldn't you want to pin it directly? Also, if I may ask what the motivation is to pin `grpcio-tools` to an older version?

**Comment by alertedsnake** [comment]
Okay, I found my issue buried in a Makefile.  There's a line here, `pip install 'grpcio-tools==1.12.0'`, which does exactly what I said, you get grpcio-tools 1.12.0 and grpcio-1.13.0.  Later in the makefile, a `setup.py install` was called and it doesn't do a downgrade, so the tests fail down the line.  I guess it helps to be specific.

Now if `setup_requires` would actually work in a useful way..... oh well.

Sorry about that, disregard.
