### ISSUE TITLE
[Ruby] Segmentation Fault with puma

### ISSUE THREAD

**Issue by nownabe** [grpc/grpc#16013]
Hi :sun_with_face: I found segmentation fault maybe caused by grpc with puma.
 
### What version of gRPC and what language are you using?
 
Ruby

```bash
$ bundle exec gem list grpc

*** LOCAL GEMS ***

grpc (1.13.0 x86_64-linux)
grpc-tools (1.13.0)
```
 
### What operating system (Linux, Windows, …) and version?
 
```bash
$ uname -a
Linux mypc 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
```bash
 $ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

### What did you do?

Reproducable code is here.
https://gitlab.com/nownabe/grpc_puma_segmentation_fault

It's a simple rack app with gRPC.
When cluster mode Puma with `preload_app!` runs this app, requests are not finished and segmentation faults occur.

[rackapp](https://gitlab.com/nownabe/grpc_puma_segmentation_fault/blob/master/config.ru)
[puma config](https://gitlab.com/nownabe/grpc_puma_segmentation_fault/blob/master/puma.rb)

Originally, my Rails app tried to send request logs to Stackdriver Logging using google-cloud-logging gem but requests were stacked at [`Google::Cloud::Logging::Project#write_entries`](http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/v1.5.1/google/cloud/logging/project?method=write_entries-instance) 
 
### What did you expect to see?
 
No segmentation fault.
 
### What did you see instead?
 
https://gitlab.com/nownabe/grpc_puma_segmentation_fault/blob/master/log/stderr.log

**Comment by takamario** [comment]
I've faced same issue on grpc (1.23.0) and puma (4.2.0).
I've tried on app engine ruby flexible env with Rails, but `ruby_app_log` and `ruby_health_check_log`were not output, and got segmentation faults.
