### ISSUE TITLE
error 'unable to update checked out version: fatal: reference is not a tree' when updating grpc depend version to v1.13.1 

### ISSUE THREAD

**Issue by quanjielin** [grpc/grpc#16031]
### What version of gRPC and what language are you using?
 Go
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What did you do?
Our repo need a commit that includes in [gRPC v1.13.1](https://github.com/grpc/grpc/releases/tag/v1.13.1), so I updated depend in our repo [here](https://github.com/istio/istio/blob/master/Gopkg.lock#L1232) to be
```
  revision = "befc7220cadb963755de86763a04ab6f9dc14200"
  version = "v1.13.1"
```
 run ```dep ensure -v``` hit below error
```Solving failure: No versions of google.golang.org/grpc met constraints:
	v1.13.1: unable to update checked out version: fatal: reference is not a tree: befc7220cadb963755de86763a04ab6f9dc14200
: command failed: [git checkout befc7220cadb963755de86763a04ab6f9dc14200]: exit status 128
```

**Comment by nicolasnoble** [comment]
Wrong repository. For go, please use https://github.com/grpc/grpc-go.

**Comment by nicolasnoble** [comment]
Also, yes, you referenced a commit from the wrong repo, hence your error.

**Comment by quanjielin** [comment]
I see, looks like v13.1 for go hasn't published yet from https://github.com/grpc/grpc-go/releases. Thanks !
