### ISSUE TITLE
Issue with New/Delete and Virtual Classes

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#16032]
Encountered during implementation of #15980.

There is an issue where if a child class is `New`-ed, and then the parent class is `Delete`-ed, and the two have different values of `alignof()` such that one is greater than `kAlignmentForDefaultAllocationInBytes` and the other is smaller, then ASAN will fail, since the object was newed with `gpr_malloc_aligned` and freed with `gpr_free`.

Simplest repro: #16021

As of now I am fixing this by adding dummy objects to the parent class to ensure that both parent and child have the same alignment.

@yang-g an I discussed another (messy) fix offline, in which any object that ever wants to use New/Delete must define a virtual functions called GetAlignment, that calls `alignof()` on itself. Then Delete can use that to determine the actual size of the object it is about to free.

**Comment by nicolasnoble** [comment]
How about always using aligned allocation?

**Comment by ncteisen** [comment]
Like this: #16037?

**Comment by markdroth** [comment]
Aligned malloc wastes memory.  I don't think we want to use it for all allocations.

As per discussion in #15873, once that PR is merged, we were planning to revert the hack that I added to use aligned malloc (#14432) and always use normal malloc.  Will that address this problem?

**Comment by nicolasnoble** [comment]
Yep.

**Comment by ncteisen** [comment]
Ok, closing the always aligned PR. I will go with the temporary fix in #15980 for now, then once #15873 is merged and #14432 is reverted, I will remove the temporary fix

**Comment by markdroth** [comment]
The problem that originally triggered the ubsan failure should be fixed by #17474.

Next steps:
- Revert #14432.
- Revert Noah's work-around from #15980.

Longer term:
- Consider whether we can revert #14888.

**Comment by markdroth** [comment]
Also, we'll need to address the TODO being added in #17291.

**Comment by markdroth** [comment]
I've reverted #14432 in #17482.  I'm going to let that bake for a few days to make sure that there are no new fuzzer failures reported before I start reverting the other workarounds.

**Comment by markdroth** [comment]
After discussion with @soheilhy, I'm not going to revert #14888, since that's now needed to support the non-polymorphic case.
