### ISSUE TITLE
FR: grpc_cli TLS flags: providing explicit CAs, certs, remote host names

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#16059]
If you `--enable_ssl` in `grpc_cli` you get default [`grpc::SslCredentialsOptions`](https://grpc.io/grpc/cpp/structgrpc_1_1_ssl_credentials_options.html), which causes `grpc_cli` to use the system CAs and no client certificates. Furthermore, if you don't have DNS for your target (e.g., an VM-based service with an ephemeral IP address), you may need to specify [`grpc::ChannelArguments::SetSslTargetNameOverride`](https://grpc.io/grpc/cpp/classgrpc_1_1_channel_arguments.html#af4182e659448184f9618f079a1570328) in order to correctly validate the certificate.

With appropriate flags, this can allow a variety of command-line use cases involving self-signed certificates or private authorities used in testing services.

This correlates to a portion of https://issuetracker.google.com/issues/111599303.

**Comment by Capstan** [comment]
It looks like `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` env variable controls alternative CAs, so that's solved already at least.

**Comment by sreecha** [comment]
@yang-g - Not sure if you know about this. Please feel free to reassign (or unassign yourself) if you are unfamiliar with this.
