### ISSUE TITLE
FR: grpc_cli: channel selection flag

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#16060]
Today, there's an `--enable_ssl` flag to switch between insecure and secure. However, internal-to-Google, there's also a [LOAS](https://twitter.com/jbeda/status/715373975182807040?lang=en) channel, and having mutually incompatible flags of `--enable_ssl` and enabling LOAS is less than ideal.

I'd like to amend `--enable_ssl` to be instead a `--channel` enum that selects from `{ insecure, tls }`, and internal-to-google, there'd be also a `loas`. This also allows us to support [`alts`](https://cloud.google.com/security/encryption-in-transit/application-layer-transport-security/) or other alternatives in the future.

For maintaining existing behavior, the default for `--channel` would be `insecure` unless `--enable_ssl`. I'm not familiar with the deprecation policy for the CLI: would you warn that the flag will be removed at some point, or just never remove it?

**Comment by Capstan** [comment]
This correlates to a portion of https://issuetracker.google.com/issues/111599303.

**Comment by yang-g** [comment]
grpc_cli flags is not considered as our public API, yet I think we would like to support both for a while and maybe warn user first before finally removing it.

Please reference this issue in your future PRs. Thanks.

**Comment by Capstan** [comment]
Fixed in #16204.
