### ISSUE TITLE
Does any one know how could I use grpc ssl calling tensorflow serving , and my client was written by Python.

### ISSUE THREAD

**Issue by elvys-zhang** [grpc/grpc#16079]
### What version of gRPC and what language are you using?
 Version: 1.13.0  
Language: Python, C++
 
### What operating system (Linux, Windows, …) and version?
 Linux CentOS 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python2.7, GCC 4.8.5
 
### What did you do?
First I started a tensorflow serving, by modifying model_server/main.cc like this:  
```
...  
std::shared_ptr<grpc::ServerCredentials> creds;
grpc::SslServerCredentialsOptions sslOps; 
grpc::SslServerCredentialsOptions::PemKeyCertPair keycert = {key, cert};  
sslOps.pem_key_cert_pairs.push_back (keycert);  
creds = grpc::SslServerCredentials(sslOps);
...
ServerBuilder builder;
builder.AddListeningPort(server_address, creds);
```  
"key" is the content in server.key, "cert" is the content in server.crt.  
When I call it by a Python client, it failed.  
My python client was like this:  
```  
with open('./server.crt') as f:  
  root = f.read()  
creds = implementations.ssl_channel_credentials(root, None, None)
channel = implementations.secure_channel(host, int(port), creds)
stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
```  

### What did you expect to see?
 I would like to see the model deployed in tensorflow serving be called successfully.
 
### What did you see instead?
```  
E0720 18:57:02.647300035   38664 ssl_transport_security.cc:1228] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")
```  
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jiangtaoli2016** [comment]
Looks like some errors on SSL certificate. @elvys-zhang Could you specify which version of OpenSSL are you using?

@mehrdada Could you reproduce?

**Comment by elvys-zhang** [comment]
@jiangtaoli2016 "OpenSSL 1.0.1e-fips" for python and "/usr/lib64/libevent_openssl-2.0.so.5.1.9" for c++.

**Comment by jiangtaoli2016** [comment]
@elvys-zhang Your openssl versions are too old. I am not familiar with libevent_openssl. if you can remove openssl dev library from your system (so that boringssl kicks in), it probably will work. At least it worths a try.

**Comment by srini100** [comment]
Please reopen if issue still exists with BoringSSL.
