### ISSUE TITLE
Issue With RefCountedPts and Polymorphism

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#16086]
See #16085 for repro.

RefCountedPtrs do not support polymorphism in the correct way. If I have a ptr to a child, I cannot pass it to a function that takes the parent.

**Comment by ncteisen** [comment]
Another issue is that you can't pass around the children of an object, since the RefCounted is only friends with RefCountedPtr<Parent>. This causes errors in the constructor. See #16087 for the repro.

**Comment by markdroth** [comment]
In general, can't this be addressed by explicit casting of the `RefCountedPtr<>` from child to parent?

**Comment by markdroth** [comment]
No, what I mean is this:

```
RefCountedPtr<Parent> obj(New<Child>(...));
```

In general, the purpose of polymorphism is that you have some code that will deal with any object of a given parent class, even if the specific instances are different subclasses.  So all the common code deals with the parent type, and the places where you instantiate the individual subclasses can up-cast to the parent.

We already do this for the resolver and LB policy code, and it works fine.  For example:

https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc#L604

To be clear, I'm not saying that it wouldn't be better if this worked a little more smoothly, and I'm not sure offhand why it doesn't.  But until I have time to look into this, you should be able to avoid this problem.

**Comment by ncteisen** [comment]
I am using that pattern for [ClientChannelNode](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/client_channel_channelz.cc#L108). But that pattern breaks down a little for my current use case;

ChannelzRegistry and ChannelTrace want to deal with the channelz entities as `BaseNode`, because the only functionality they need is `type()` and `uuid()`, both of which are available on `BaseNode`. However, channel.cc and subchannel.cc want to deal with ChannelNode and SubchannelNode respectively so that they have access to thinks like `RecordCallStarted()` or `MarkChannelDestroyed`.

So when some code in channel.cc wants to add a new ChannelTrace, that references a different ChannelNode, it cannot do that, because the ChannelNode* can't be passed to ChannelTrace that expects BaseNode. This should be possible, since ChannelNode is-a BaseNode
