### ISSUE TITLE
How to make grpc server to listen to every address with the specified port, esp. the C# version?

### ISSUE THREAD

**Issue by mlstudies** [grpc/grpc#16095]
I use the latest python3 and c# version of grpc.

In the python code, you can see something like "[::]", does this mean listening to every address with the specified port?

```
def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10), options=[(cygrpc.ChannelArgKey.max_send_message_length, -1),
                                                                              (cygrpc.ChannelArgKey.max_receive_message_length, -1)])
    byte_transfer_test_pb2_grpc.add_DataServiceServicer_to_server(DataService(), server)
    server.add_insecure_port('[::]:' + argv[1])
    print("listening on port " + argv[1])
    server.start()
    try:
        while True:
            sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)
```

Then actual problem is how to do the same thing in C#. Using the same "[::]" does not work on my machine, the client cannot find the server

```
  Console.WriteLine(@"Test server started ...");
                        Server server = new Server(new[] { new ChannelOption("grpc.max_send_message_length", -1), new ChannelOption("grpc.max_receive_message_length", -1) })
                        {
                            Services = { FrameInfoQueue.BindService(new GreeterImpl()) },
                            Ports = { new ServerPort("[::]", port, ServerCredentials.Insecure) }

                        };
                        server.Start();

                        Console.WriteLine($@"Server listening on port {port}");
                        Console.WriteLine(@"Press any key to stop the server...");
                        Console.ReadKey();

                        server.ShutdownAsync().Wait();
```

**Comment by jtattermusch** [comment]
"[::]" does mean listen on every networks interface (with given port) in the IPv6 notation.  "0.0.0.0" is the equivalent for it in IPv4 (have you tried with "0.0.0.0"?)
Both examples you're presenting should work fine (and btw are implemented by the same piece of code in gRPC C core, so the two examples behaving differently seems very odd - perhaps there's some more differences or a some other problem in the code). What exactly behavior are you getting with C#? (have you tried adding extra logging & tracing as described inhttps://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md?)

I'm going to close this question for now, until we have a proof that there is an actual bug.
