### ISSUE TITLE
Change the php and node ssl server credentials API so that a server can have multiple key/cert pairs. 

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#161]

**Comment by murgatroid99** [comment]
I think this is covered by #730 and number #921

**Comment by jboeuf** [comment]
Thanks for making this change with respect to add_sercure_port vs. server
but I'm not sure that this issue is actually fixed (but I may be wrong).

The issue here is that a server may have multiple key/cert pairs for (now)
the same port in order to support SNI (see
http://en.wikipedia.org/wiki/Server_Name_Indication)

The change should be done on the server credentials to accept multiple key
pairs and I don't see that here:
https://github.com/ctiller/grpc/pull/2/files

Am I missing something?

**Comment by murgatroid99** [comment]
No, I just misunderstood.

**Comment by ctiller** [comment]
Should this be beta?

**Comment by ctiller** [comment]
@jboeuf, @nathanielmanistaatgoogle - should this be Beta?

**Comment by jboeuf** [comment]
I should probably fix #2527 before (assigned for beta).

**Comment by jayantkolhe** [comment]
Now Split into two issues #1121 and #1122 

Closing this since those two cover all things covered in this issue.
