### ISSUE TITLE
gRPC Python doesn't handle utf-8 error messages.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#16102]
When gRPC python connects to a server that sends back an error with a details string that contains utf-8 characters, the Python client will choke on it:

```
Invalid encoding on b'\xc3'
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/grpc_string.pyx.pxi", line 51, in grpc._cython.cygrpc._decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: unexpected end of data
Traceback (most recent call last):
  File "greeter_client.py", line 32, in <module>
    run()
  File "greeter_client.py", line 27, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/pixel/sources/python3/venv/lib/python3.5/site-packages/grpc/_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/pixel/sources/python3/venv/lib/python3.5/site-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Ã"
        debug_error_string = "{"created":"@1532368813.278306147","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"\u00c3","grpc_status":2}"
>
```

This above is done by modifying the hello world nodejs server the following way:

```
function sayHello(call, callback) {
  var error = {
    code: grpc.status.UNKNOWN,
    details: 'é',
  };
  callback(error, {});
}
```

Yes, this is odd, yes, the file snippet is a utf-8 file, and yes, 'é' is supposed to be an utf-8 string in JavaScript, so I'm not sure why the python client is complaining that the utf-8 decoder can't work on this string, nor why it is using "Ã" as an output. More digging is needed, I guess. Other languages seems to get this one properly.

Additionally, the Python server itself can't send utf-8 encoded strings. Modifying the hello world example the following way:

```
    def SayHello(self, request, context):
        context.set_code(grpc.StatusCode.UNKNOWN)
        context.set_details(u'é')
        return helloworld_pb2.HelloReply()
```

yields the following error when this handler is being called:

```
Exception calling application: 'ascii' codec can't encode character '\xe9' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/pixel/sources/python3/venv/lib/python3.5/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "greeter_server.py", line 31, in SayHello
    context.set_details(u'é')
  File "/home/pixel/sources/python3/venv/lib/python3.5/site-packages/grpc/_server.py", line 300, in set_details
    self._state.details = _common.encode(details)
  File "/home/pixel/sources/python3/venv/lib/python3.5/site-packages/grpc/_common.py", line 68, in encode
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 0: ordinal not in range(128)
```

**Comment by mehrdada** [comment]
This is the same issue as https://github.com/grpc/grpc/issues/16078, right?

**Comment by mehrdada** [comment]
[gRPC Specification](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) actually disallows *sending* non-ASCII-encodable headers so the error is justified on the send side. The behavior in receiving non-ASCII-encodable metadata is up to the implementation, so we are not supposed to guarantee we will return the same value sent on the other side:

> ASCII-Value should not have leading or trailing whitespace. If it contains leading or trailing whitespace, it may be stripped. The ASCII-Value character range defined is more strict than HTTP. Implementations must not error due to receiving an invalid ASCII-Value that's a valid field-value in HTTP, but the precise behavior is not strictly defined: they may throw the value away or accept the value. If accepted, care must be taken to make sure that the application is permitted to echo the value back as metadata. For example, if the metadata is provided to the application as a list in a request, the application should not trigger an error by providing that same list as the metadata in the response.

**Comment by mehrdada** [comment]
I see... So Message header is supposed to receive special treatment. I don't believe gRPC Python had ever made that assumption.

**Comment by murgatroid99** [comment]
Note that from a wire protocol point of view, the header is still ASCII, because it's percent encoded. But the C core just accepts a UTF-8 encoded string for the status message.

**Comment by lidizheng** [comment]
@nicolasnoble I fixed the server-side encoding problem.

But found client-side problem can't be reproduced. I'm using code from master branch. The exception of RPCError is as expected. I am using a Python client receiving an "utf-8" encoded error message from a node server.

PS. Exception log of Python2/3
```
lidiz-macbookpro:helloworld lidiz$ python3 greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 35, in <module>
    run()
  File "greeter_client.py", line 30, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Ã"
	debug_error_string = "{"created":"@1539988223.114949000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"\u00c3\u0083","grpc_status":2}"
```
```
lidiz-macbookpro:helloworld lidiz$ python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 35, in <module>
    run()
  File "greeter_client.py", line 30, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/Users/lidiz/Library/Python/2.7/lib/python/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/lidiz/Library/Python/2.7/lib/python/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Ã"
	debug_error_string = "{"created":"@1539988244.164052000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"\u00c3\u0083","grpc_status":2}"
```
