### ISSUE TITLE
List of server arguments?

### ISSUE THREAD

**Issue by saward** [grpc/grpc#16108]
Hi,

I haven't had any luck finding this.  Various language libraries for grpc allow setting of certain server settings, such as 'grpc.max_message_length'.

I've been trying, unsuccessfully, to find a list of all the various possible server arguments that can be set.  Is there a list somewhere, either in source code or documentation?

Thanks

**Comment by nicolasnoble** [comment]
Please don't use github issues to ask questions.

That being said, here you go:

https://github.com/grpc/grpc/blob/9a5a3883f59d8d3d5d25ffd4337ca150d97e2e38/include/grpc/impl/codegen/grpc_types.h#L141
