### ISSUE TITLE
Need an interop test for UTF8 error message

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#16113]
This is the protect against #16102. We should add an interop test for all languages.

**Comment by ejona86** [comment]
Should also include a newline, and leading and trailing whitespace.

**Comment by ejona86** [comment]
I've created a proposal at #16129

**Comment by ejona86** [comment]
Created issues for implementation:
grpc/grpc#16149
grpc/grpc-java#4682 (yes... I created a PR instead of an issue. So sue me.)
grpc/grpc-go#2240
grpc/grpc-node#461
grpc/grpc-dart#105
grpc/grpc-swift#276
