### ISSUE TITLE
Add C# support for server SSL certificate reloading.

### ISSUE THREAD

**Issue by Kabutak** [grpc/grpc#16118]
### What version of gRPC and what language are you using?
 gRPC v1.13.1 NuGet package (Latest Stable) in C#
 
### What operating system (Linux, Windows, …) and version?
 Windows 8.1 and 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2015 and 2017
 
### What did you do?
 Attempt to use dynamic server SSL certificates as per #12644
 
### What did you expect to see?
 API integration for facilitating this feature in C#, similar to #13188 in Python
 
### What did you see instead?
 There does not seem to be any integration for this feature in C#. I searched through the existing and resolved issues, and the open/closed pull requests and have not found mention of this so far. If I have missed something, then simply point me in the right direction and I will close this right away.
 
### Anything else we should know about your project / environment?
 We are currently leveraging gRPC for a number of interprocess and local network communications. Due to the nature of our product, we need to be able to rotate certificates to ensure that they are kept up to date and to be able to revoke certificates as needed. This is not as important on the client level, as those processes are generally short-lived. The server however tends to be long-running, so restarting it to refresh the SSL certificates is less than ideal.

I found that the ability to refresh certificates was added to the core in a previous set of pull requests, and support has been added to Python as well as others (Go, I think). I cannot find any information regarding this feature being added to C# or it being planned, and it would be of great benefit.

**Comment by jtattermusch** [comment]
Thanks for reporting this. Currently we don't have plans to work on this, but we'd be happy to accept a PR that adds this feature.

**Comment by roy-xu709** [comment]
How about with c++? Is it supported now or not ?  Hope your reply.

**Comment by roy-xu709** [comment]
> Thanks for reporting this. Currently we don't have plans to work on this, but we'd be happy to accept a PR that adds this feature.

How about with c++? Is it supported now or not ? Hope your reply.

**Comment by Kabutak** [comment]
> How about with c++? Is it supported now or not ? Hope your reply.

I believe it should be supported in c++, as per https://github.com/grpc/grpc/pull/12644

I haven't personally tested it, but that was the base upon which the support in python was added, so it should work.

**Comment by roy-xu709** [comment]
> > How about with c++? Is it supported now or not ? Hope your reply.
> 
> I believe it should be supported in c++, as per #12644
> 
> I haven't personally tested it, but that was the base upon which the support in python was added, so it should work.

I search some functions mentioned with that ticket, but got nothing.
Hope you give relative function interface for grpc_server if possible.

**Comment by yihuazhang** [comment]
We currently do not support credential reload in C++ (it is only supported in C-core #12644).

**Comment by ak800i** [comment]
+1 to this.
Have any plans formed to work on this, since?

**Comment by ak800i** [comment]
@jtattermusch I would like to implement the API integration for this feature. Would you be so kind as to give me some code pointers. I would be especially glad for a previous pull request which added C# API integration for some other feature. I am sorry if this is not the proper forum for this discussion. I have also posed the same question over at google groups: [https://groups.google.com/forum/#!topic/grpc-io/C0Xt4qFQdm4](https://groups.google.com/forum/#!topic/grpc-io/C0Xt4qFQdm4)

**Comment by jtattermusch** [comment]
Let's keep this open.

**Comment by jtattermusch** [comment]
Since Grpc.Core is now in maintenance mode (see https://grpc.io/blog/grpc-csharp-future/), we don't plan to add any new features.
