### ISSUE TITLE
grpc_cli doesn't include the `content-type` header in its requests

### ISSUE THREAD

**Issue by achew22** [grpc/grpc#16143]
### What version of gRPC and what language are you using?

```
commit 2cfc216cfd58dc247249da87dbefa8bb949c8b9c
Merge: dbc1e27 d4c9867
Author: Nicolas Noble <nicolasnoble@users.noreply.github.com>
Date:   Sat Jul 21 00:23:18 2018 -0700 
```

### What operating system (Linux, Windows, …) and version?
 
Ubuntu Linux 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

```
achew22@lappy:~/Projects/grpc (master)$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
```
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I attempted to use the `grpc_cli` tool per the [instructions](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md) but was unable to get it to send a request to a service that handled both http and grpc traffic. The server filters based on the `content-type` header and has GRPC handle if `contentType == "application/grpc"`, HTTP otherwise.
 
### What did you expect to see?
 
I expected the grpc_cli to set the `content-type` header to "application/grpc" 
 
### What did you see instead?

It didn't set the content-type header
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

Thank you so much!

**Comment by yang-g** [comment]
Do you have any evidence that grpc_cli did not set the header? I think it should and just verified it does.

You can print out the headers with GRPC_TRACE=http and you should see the header.

I suspect you have other issues with grpc_cli.
