### ISSUE TITLE
Implement special_status_message interop test

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#16149]
https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#special_status_message

This needs to be done in C++ and all the wrapped languages.

**Comment by ejona86** [comment]
This should remain open until it is implemented.

**Comment by yashykt** [comment]
cc @apolcyn for Ruby and @stanley-cheung for PHP

**Comment by yashykt** [comment]
C++ implementation - #24173
Python implementation - #16946
C# implementation - #18448
