### ISSUE TITLE
Several objc tests failing to build because "No space left on device"

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#16156]
See failures in https://source.cloud.google.com/results/invocations/6285633f-e131-4d25-be8d-dcfd45aed97d/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests

and https://source.cloud.google.com/results/invocations/e4b083e8-7052-4ba5-98d4-95cda1b32492/targets/github%2Fgrpc%2Fobjc_macos_opt_native/tests

**Comment by muxi** [comment]
Should be fixed by #16165

**Comment by muxi** [comment]
Master still failing; reopening
