### ISSUE TITLE
grpc_build_packages on Kokoro: race when creating the artifacts/ directory

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#16155]
https://sponge.corp.google.com/invocation?tab=Build+Log&id=f1b7168a-c8df-450d-a126-e4e900917d50&searchFor=

```
+ docker cp build_and_run_docker_d1c40699-bbad-4197-b6f1-44abf5a88a23:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
mkdir /tmpfs/src/github/grpc/artifacts: file exists
+ FAILED=true
+ docker rm -f build_and_run_docker_d1c40699-bbad-4197-b6f1-44abf5a88a23
```

Seen in multiple contexts, on manual builds, master, and nightlies, Seems like an infrastructure/script flake. The `mkdir` command fails sometimes (probably because something else created that directory beforehand and there might be a race condition that causes it to pass sometimes and fail other times?).

**Comment by mehrdada** [comment]
Haven't seen in a while. Closing.

**Comment by mehrdada** [comment]
Happened again last night: https://sponge.corp.google.com/invocation?tab=Build+Log&id=a86d6c36-fb6e-409c-940b-65a990ae0cce&searchFor= 

Reopening.

**Comment by jtattermusch** [comment]
Seen similar issue for PHP twice
```
+ cp -r /var/local/jenkins/grpc/input_artifacts/php_pecl_package_linux_x64/grpc-1.15.0dev.tgz /var/local/jenkins/grpc/input_artifacts/php_pecl_package_macos_x64/grpc-1.15.0dev.tgz artifacts/
cp: will not overwrite just-created 'artifacts/grpc-1.15.0dev.tgz' with '/var/local/jenkins/grpc/input_artifacts/php_pecl_package_macos_x64/grpc-1.15.0dev.tgz'
+ true
+ '[' artifacts '!=' '' ']'
+ docker cp build_and_run_docker_0266e022-7d36-430a-a20b-748c8be4d4a3:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
mkdir /tmpfs/src/github/grpc/artifacts: file exists
```
https://source.cloud.google.com/results/invocations/6efc0b89-6c48-4e5b-a727-30d9fd89053d/targets/github%2Fgrpc/tests
https://source.cloud.google.com/results/invocations/2c8f9e11-113a-4621-b754-381184a5d34d/targets/github%2Fgrpc/tests

**Comment by jtattermusch** [comment]
What's also odd is this message:
`cp -r /var/local/jenkins/grpc/input_artifacts/php_pecl_package_linux_x64/grpc-1.15.0dev.tgz /var/local/jenkins/grpc/input_artifacts/php_pecl_package_macos_x64/grpc-1.15.0dev.tgz artifacts/
cp: will not overwrite just-created 'artifacts/grpc-1.15.0dev.tgz' with '/var/local/jenkins/grpc/input_artifacts/php_pecl_package_macos_x64/grpc-1.15.0dev.tgz'`  -> looks like the macos and linux PHP packages have the same name and they are trying to overwrite each other? Perhaps  https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/build_package_php.sh needs updating?

**Comment by jtattermusch** [comment]
The `docker cp` (which fails with `mkdir /tmpfs/src/github/grpc/artifacts: file exists`) is from here https://github.com/grpc/grpc/blob/f30db9db2320e533c1ffed9bc9b80ca7b2a457be/tools/run_tests/dockerize/build_and_run_docker.sh#L76
