### ISSUE TITLE
npm ci fails to install grpc

### ISSUE THREAD

**Issue by plchampigny** [grpc/grpc#16164]
### What version of gRPC and what language are you using?
version: v1.13.1 
language: nodejs (v8.11.3) + npm (v6.2.0)
### What operating system (Linux, Windows, …) and version?
os: windows 10 pro v1803

I am also experimenting this issue on my build server which is a Windows Server 2012 Datacenter.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
VS2015 
 
### What did you do?

How to setup the environment to reproduce this:
1. npm init            (setup a new package.json into a folder)
2. npm i --save grpc
3. npm ci

### What did you expect to see?
No errors during npm ci and libs installs as normal
 
### What did you see instead?

```
PS C:\test> npm ci
npm WARN prepare removing existing node_modules/ before installation

> grpc@1.13.1 install C:\test\node_modules\grpc
> ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.13.1 install: `./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\###\AppData\Roaming\npm-cache\_logs\2018-07-27T14_23_30_513Z-debug.log
```

Here's what in the debug.log:

```
552 verbose lifecycle grpc@1.13.1~install: CWD: C:\test\node_modules\grpc
553 silly lifecycle grpc@1.13.1~install: Args: [ '/d /s /c',
553 silly lifecycle   './node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library' ]
554 silly lifecycle grpc@1.13.1~install: Returned: code: 1  signal: null
555 info lifecycle grpc@1.13.1~install: Failed to exec install script
556 verbose teardown shutting down workers.
557 info teardown Done in 0.001s
558 verbose stack Error: grpc@1.13.1 install: `./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library`
558 verbose stack Exit status 1
558 verbose stack     at EventEmitter.<anonymous> (C:\Users\###\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
558 verbose stack     at emitTwo (events.js:126:13)
558 verbose stack     at EventEmitter.emit (events.js:214:7)
558 verbose stack     at ChildProcess.<anonymous> (C:\Users\###\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
558 verbose stack     at emitTwo (events.js:126:13)
558 verbose stack     at ChildProcess.emit (events.js:214:7)
558 verbose stack     at maybeClose (internal/child_process.js:925:16)
558 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
559 verbose pkgid grpc@1.13.1
```

 
### Anything else we should know about your project / environment?
Nope

**Comment by nicolasnoble** [comment]
This seems to be Windows-specific, and I think I know why.

**Comment by nicolasnoble** [comment]
Actually, no, I don't know why...

**Comment by nicolasnoble** [comment]
Attaching the full debug log that I managed to reproduce locally.

[2018-07-27T16_58_12_741Z-debug.log](https://github.com/grpc/grpc/files/2236611/2018-07-27T16_58_12_741Z-debug.log)

**Comment by nicolasnoble** [comment]
Wait, this actually never worked under Windows... Just tried with grpc@1.10.0, and the same thing happens.

@murgatroid99: after some manual digging, node-pre-gyp isn't even spawned. The problem is what I suspected originally: you can't do `./node_modules` under Windows. Or rather, use slashes when the command is fed into CMD directly.

![image](https://user-images.githubusercontent.com/7281574/43344376-5951d9fc-919e-11e8-81bc-471bf12c3099.png)

Something tells me this is an `npm` bug. If it changes command lines properly when doing anything BUT `npm ci`, something's wrong.

**Comment by plchampigny** [comment]
Just to be clear, `npm i` does work, but `npm ci` isnt working. In my case, i need to run npm ci for my continuous integration server. I currently worked around this issue by deleting the node_modules folder on every build and doing npm i --no-save --force, but would really like this to be solved.

Thanks!

**Comment by nicolasnoble** [comment]
The problem seems a bit more... weird. Something somewhere is stripping the leading path of our script command, but not for `npm ci`. I can't figure out where the stripping happens however.

Oh well, grpc/grpc-node#466 should fix this anyway.

**Comment by plchampigny** [comment]
Happy to see fast bugfixes! Looking at your PR, I sure hope it's going to
fix it!
