### ISSUE TITLE
Bidirectional Stream on C++ Client Hangs When ClientContex Destructor Called

### ISSUE THREAD

**Issue by jeffd** [grpc/grpc#16160]
### What version of gRPC and what language are you using?
 
C++ on v1.12.0

### What operating system (Linux, Windows, …) and version?
 
MacOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
 
### What did you do?

I have a class that handles a bidirectional stream to communicate with a server written in Go. This class is apart of a plugin that is used in a Unity project. It uses `AsyncNext` for the context queue so it does not block the main thread / game loop.

Everything works fine until I call out to a function that calls `delete` on the object managing the gRPC stream. Calling `delete` blocks and takes more than 5 seconds to return.

By the time `delete` is called on the object. I have shut down the stream with `Finish(` or the client context with `TryCancel()` and completion queue with `Shutdown()`

### What did you expect to see?
 
I would expect the class and its instance variable destructors to be deallocated fairly quickly.
 
### What did you see instead?
 
The program hangs for a few seconds until the object is finally deleted. Some profiling in Unity and Instruments have pointed me towards `~ClientContext()` and subsequently `~Channel()` for being the possible blocking methods.

I have run a test program with `export GRPC_VERBOSITY=DEBUG` but did not see any logs printed during the deletion of my object.

I've attached two profiles done. One from Unity that shows the delete function hanging:
```
    void UNITY_INTERFACE_EXPORT UNITY_INTERFACE_API MatcherDelete(void *matcher) {
        delete reinterpret_cast<Matcher *>(matcher);
    }
```

<img width="1412" alt="screen shot 2018-07-25 at 9 11 26 am" src="https://user-images.githubusercontent.com/2890/43289948-57573592-90e1-11e8-8f08-07cfc01102e8.png">

The second is from attaching Instruments to Unity.

<img width="936" alt="screen shot 2018-07-25 at 2 42 41 pm" src="https://user-images.githubusercontent.com/2890/43289970-6d80ab82-90e1-11e8-801b-620ae1db85c7.png">

My test program all in C++ that calls delete does not freeze as it does when run from Unity.

**Comment by sreecha** [comment]
Can you clarify the following  ?
>By the time delete is called on the object. I have shut down the stream with Finish( or the client context with TryCancel() and completion queue with Shutdown()

I am assuming you finished the bidi stream (from client side) by calling `Finish()`,  called `Shutdown()` on the completion queue and `TryCancel()` on the `ClientContext` object . Is that correct?

- Did the `ClientAsyncReaderWriter::Finish(Status* status, void *tag)` operation complete ? (i.e did the `tag` you passed return out of the completion queue? also, what is the returned `status` value ?) . 
- After you called `CompletionQueue::Shutdown()`, did you wait until `CompletionQueue::Next()` returned `false`? (to make sure that the queue was actually shutdown?)
- Approximately how many seconds is it taking for the `ClientContext` destruction to fully complete?

---

I do agree that It is a bit strange that it is taking several seconds but from the traces you posted, it seems like this is also calling `grpc_shutdown` (i.e you no longer have any active grpc calls or channels open. Hence the grpc library is 'shutting down') and this can sometimes take a few seconds to do a clean-shutdown.

In addition to doing `export GRPC_VERBOSITY=DEBUG`, if you also turn on tracing as mentioned [here](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)  
Perhaps `export GRPC_TRACE=all,-tcp`  (all traces except `tcp` which tend to be very verbose)
