### ISSUE TITLE
expose client ip address server side in python

### ISSUE THREAD

**Issue by fta1** [grpc/grpc#1616]
when the server receives an RPC call, it has no way of knowing anything about the client, such as its IP address, at least when the server is using the Python API.
It would be very useful to have that, at least for monitoring and troubleshooting purposes, maybe even to add extra security.

it could probably be exposed via the context parameter (interfaces.RpcContext), which doesn't seem to do much as of now.
https://github.com/grpc/grpc-common/blob/master/python/route_guide/route_guide_server.py#L74

**Comment by soltanmm** [comment]
I don't believe this is a Python-specific issue; the GRPC C core doesn't provide this information through the surface given in `grpc/grpc.h`.

@ctiller Thoughts?

**Comment by nathanielmanistaatgoogle** [comment]
I think that I've heard rumblings somewhere about doing something like this in the future. I'm fine leaving this issue open and perhaps blocked on a feature request in the underlying core library.

**Comment by ctiller** [comment]
+Julien Boeuf <jboeuf@google.com> is putting together the basic API's right
now. Once they're in place, I expect it'll be relatively painless to
reflect this in Python.

**Comment by jboeuf** [comment]
I'm indeed working on an authentication context that would be surfaced to
the core API. I didn't have plans to surface the IP address initially but
since it looks like a popular feature, I may include it sooner. Will keep
you posted.

     Julien.

**Comment by jboeuf** [comment]
After some discussions, we think that exposing the IP address in the auth
context is not a good idea since it is not trusted. However Craig has
agreed to add this feature separately in the coming weeks.

Cheers,

    Julien.

**Comment by fta1** [comment]
@jboeuf: I didn't ask for it to be in the auth context specifically (wherever that ends-up being). I just proposed to store it in the (unfortunately undocumented) 'context' param, which doesn't seem to do much as of now. I see is_active() and time_remaining() and some other cryptic methods in there, so I thought providing client infos in there too was a possibility without disturbing the method signature. Anyway, you undoubtedly have a broader view of all this as I do.

**Comment by jboeuf** [comment]
Sure, understood. I was just replying to myself (I indicated in a previous
email that this could be part of auth).

Cheers,

    Julien.

**Comment by vanbrandwijk** [comment]
Hello, did anything come of exposing the client ip address in the server context?

**Comment by jboeuf** [comment]
I'm aware of some work on the context. @ctiller, @a11r, can you expend on the IP address specifically?

**Comment by ctiller** [comment]
It's on the list, and it'll be done Soon.

**Comment by ctiller** [comment]
Will be doing this this week. Once done, I'll assign per-language bugs to get it exposed.

**Comment by ctiller** [comment]
#2542 implements the C core part of this. Turning the bug over for the Python specific parts. (bugs have been filed for all other languages)

**Comment by soltanmm** [comment]
(taking this as it isn't yet exposed to Python; will pass back to @nathanielmanistaatgoogle after it's been exposed)

**Comment by nathanielmanistaatgoogle** [comment]
This was completed in 41abb052b8ed180ca14b9ff1.
