### ISSUE TITLE
Python example hangs on server.start() under docker-compose up

### ISSUE THREAD

**Issue by igorgatis** [grpc/grpc#16185]
### What version of gRPC and what language are you using?

grpc branch as of commit 682d093868a2b7ba7b139d22eb7096cec78a9979
 
### What operating system (Linux, Windows, …) and version?
 
Linux 7347e25bd83a 4.9.93-boot2docker #1 SMP Thu Jul 19 18:29:50 UTC 2018 x86_64 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 3.6.5
 
### What did you do?

1. cloned github.com/grpc/grpc
2. cd into examples/python/helloworld
3. Added prints as below:
```
    server.add_insecure_port('[::]:50051')
    print("starting...")
    server.start()
    print("done")
``` 
4. created `server.Dockerfile`
```
FROM grpc/python:1.4
COPY . /app
WORKDIR /app
CMD ["python", "-u", "greeter_server.py"]
```
5. Created `docker-compose.yml`
```
version: "3.4"

services:

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 50051:50051
```
6. issued `docker-compose up --build server`
 
### What did you expect to see?
Logs:
```
starting...
done.
```
 
### What did you see instead?
Logs:
```
starting...
```

It never leaves `server.start()` 
 
### Anything else we should know about your project / environment?

When I run `docker container run -it --rm -p 50051:50051 helloworld_server`, it prints `done.` as expected.

This seems to be an issue with docker-compose only.

**Comment by mehrdada** [comment]
`grpc/python:1.4` in the Docker image is considered a very old gRPC release.  I just uploaded https://github.com/grpc/grpc-docker-library/blob/master/1.13.0/python/Dockerfile under the image name `grpc/python:1.13`. Please test with that and let us know if the problem remains. I'll close the issue for now. Please feel free to comment and ask to reopen if it persists.
