### ISSUE TITLE
Error with grpc_tools installation with sudo

### ISSUE THREAD

**Issue by zhehangd** [grpc/grpc#16182]
I am using kubuntu 16.04 and compiling gRPC 1.13.1. I followed the instruction in this [page](https://github.com/grpc/grpc/tree/master/tools/distrib/python/grpcio_tools).
When I executed the following line in `tools/distrib/python/grpcio_tools`
`GRPC_PYTHON_BUILD_WITH_CYTHON=1 sudo pip install .`
I got the following error:
`x86_64-linux-gnu-gcc: error: grpc_tools/_protoc_compiler.cpp: No such file or directory`

My workaround is to not use sudo, but to install to the user directory instead of the system one.
i.e. `GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip --user install .`

I saw pip also complain at the beginning
> The directory '/home/myname/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

so I guess (I know little of what's inside the installation) the reason is that either cython is not generating the cpp file in the correct directory or the compiler is trying to access the file from a wrong location.

**Comment by mehrdada** [comment]
Have you tried `sudo pip install cython`? That might help. Although I am not fully sure if the system `pip` exhibits other behavioral discrepancies, but that's the first thing I'd try.

**Comment by mehrdada** [comment]
Another point: I just recalled `sudo` might not pass the environment variable unchecked; try `sudo -E`

**Comment by zhehangd** [comment]
Hi, I tried `GRPC_PYTHON_BUILD_WITH_CYTHON=1 sudo -E pip install .` and it worked.
I wonder whether this should be added to the [installation guide/troubleshooting](https://github.com/grpc/grpc/tree/master/tools/distrib/python/grpcio_tools#from-source)?

**Comment by mehrdada** [comment]
I don't think we want to recommend installation as root, so unless more people fall into this trap, I am inclined to not add it there.

I'm glad your problem is resolved.
