### ISSUE TITLE
Anyway of forcing OpenSSL on C++ Compile

### ISSUE THREAD

**Issue by Daemoneyes** [grpc/grpc#16195]
### What version of gRPC and what language are you using?
 C++ with 15e95b30e962178cf8ea7c16662bd104fce0b29d
 
### What operating system (Linux, Windows, …) and version?
 REHL 6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 devtoolset-7 gcc 7.4
 
### What did you do?

Currently we are trying to build grpc on rehl6, the rehl6 is using OpenSSL 1.01, so gRPC itself is using boringSSL. However BoringSSL has slightly difference compare to OpenSSL which cause a bug on using gRPC to communicate with Google Speech.
When called BIO_new() in BoringSSL it would not create a ex_data structure compared to OpenSSL, which later on when reading the same private key from google cloud, boring SSL would return null on PEM_read_bio_RSAPrivateKey in json_token.cc:105,makes grpc crash on segment fault.
This crash force us to use OpenSSL, the docs does not include how to turn on forcing OpenSSL, i tried the EMBED_OPENSSL option to true it does not work.

**Comment by nicolasnoble** [comment]
gRPC requires OpenSSL 1.0.2, so you can't use OpenSSL 1.0.1 to build it. Sorry.

**Comment by nicolasnoble** [comment]
Also, the boringssl crash you are describing warrants its own bug report, is you want to extract it as an independent bug report.

**Comment by Daemoneyes** [comment]
Sure, if that api difference is a bug i will report to Boring SSL issue board. Thx for help.
