### ISSUE TITLE
Change the ruby ssl server credentials so that a server can have multiple cert/key pairs.

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#162]

**Comment by tbetbetbe** [comment]
#135 addresses this
- the credentials are now associated with the port
- it's possible to have multiple ports

**Comment by jboeuf** [comment]
You should be able to have multiple SSL key/cert pairs on the same port (see http://en.wikipedia.org/wiki/Server_Name_Indication). #135 does not address this part.
Can you check:
https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L171
and see if you can call this function from ruby with multiple key pairs?
Thanks much.

**Comment by ctiller** [comment]
@jboeuf, @nathanielmanistaatgoogle - should this be Beta?

**Comment by jboeuf** [comment]
I should probably fix #2527 before (assigned for beta).
