### ISSUE TITLE
Check whether the subchannel should still connect when backoff timer fires

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#16218]
As mentioned here https://github.com/grpc/grpc/pull/16176#pullrequestreview-141630225, we should have a way to withdraw the interest of a subchannel being connected. Otherwise, the subchannel may be connecting without any external users. For example, during the backoff timer countdown the LB policy that started the timer may longer want to connect to the subchannel (due to a subchannel list shutdown), so the subchannel shouldn't start connecting when the backoff finishes.

Note that this unnecessary connection won't happen when we are trying the next subchannel in the subchannel list. The reason is that if we want to try the next subchannel, we should have received a connectivity change notification to `TRANSIENT_FAILURE` for the current subchannel first. We will only receive such a notification if the subchannel started to connect and failed. If it started to connect, it's not in backoff state.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
