### ISSUE TITLE
Possible test flake: bins/tsan/channelz_service_test --gtest_filter=ChannelzServerTest.ManyRequestsManyChannels  GRPC_POLL_STRATEGY=epoll1

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#16211]
https://source.cloud.google.com/results/invocations/b66aac71-9ce6-4286-800f-6d7ebc63ee24/targets

WARNING: ThreadSanitizer: data race (pid=2112)
  Write of size 8 at 0x7b08000071b8 by thread T10:
    #0 operator delete(void*) /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_new_delete.cc:119:3 (channelz_service_test+0x6d10cd)
    #1 grpc::Status::~Status() /var/local/git/grpc/include/grpcpp/impl/codegen/status.h:31:7 (channelz_service_test+0x6d87d6)
    #2 grpc::internal::RpcMethodHandler<grpc::testing::EchoTestService::Service, grpc::testing::EchoRequest, grpc::testing::EchoResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) /var/local/git/grpc/include/grpcpp/impl/codegen/method_handler_impl.h:87:3 (channelz_service_test+0x7be165)
    #3 grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks> const&) /var/local/git/grpc/src/cpp/server/server_cc.cc:225:27 (channelz_service_test+0x8a3c1d)
    #4 grpc::Server::SyncRequestThreadManager::DoWork(void*, bool) /var/local/git/grpc/src/cpp/server/server_cc.cc:317:10 (channelz_service_test+0x8a24e0)
    #5 grpc::ThreadManager::MainWorkLoop() /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:155:9 (channelz_service_test+0x8b1b30)

**Comment by yashykt** [comment]
looks like this is being hit more often. raising the priority

**Comment by jtattermusch** [comment]
This is now failing in 100% of test runs. It started happening again on at commit 92fd2620,
this is the diff compared to to the previous build (which was green) - one of the commits is probably at fault.
https://github.com/grpc/grpc/compare/6975fe484cf17bf056b1f8e2daf23899a0378083...92fd2620ab03c438fdeab23400cb6f31f5ba7816

**Comment by jtattermusch** [comment]
Can this be closed?

**Comment by srini100** [comment]
https://github.com/grpc/grpc/pull/16243 reverts the fix that introduced this failure. Closing.
