### ISSUE TITLE
gRPC core keepalive doesn't throttle when receiving GOAWAY with "too many pings"

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#16210]
According to https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md, a client should double the KEEPALIVE_TIME value when it receives a GOAWAY from the server. gRPC core currently ignores it.

**Comment by dfawley** [comment]
cc @RahulMitra

**Comment by nicolasnoble** [comment]
The word "scale" might be misinterpreted in this issue's title ;-)

**Comment by RahulMitra** [comment]
@dfawley and @yashykt - please let me know if there's anything I can do to help.

**Comment by yashykt** [comment]
Yes, we do have a solution in mind. Just haven't gotten to implementing it yet.

**Comment by ejona86** [comment]
:-/ Keepalive should not have been exposed to users without this... This would have been a blocker for exposing the feature.

**Comment by ZhiqinYang** [comment]
I wonder why not set atomic.StoreUint32(&t.resetPingStrikes, 1) in HandleStreams,  except handlePing!
I saw atomic.StoreUint32(&t.resetPingStrikes, 1) this call in Write function ? 
when I Concurrent invocations grpc client  with keepalive , I saw many  http2: Framer 0xc000319180: read GOAWAY len=22 LastStreamID=13 ErrCode=ENHANCE_YOUR_CALM Debug="too_many_pings"

**Comment by dfawley** [comment]
@ZhiqinYang this issue is for a C core bug, not Go.  If you think there is a problem with the go implementation, please file an issue there (https://github.com/grpc/grpc-go/issues/new).  Thanks!

**Comment by yashykt** [comment]
@carl-mastrangelo

**Comment by dfawley** [comment]
Is P2 correct here?  This is a correctness issue for something meant to protect servers from excessive load in the event of misconfiguration.

**Comment by yashykt** [comment]
@dfawley you are right. This has gone ignored for quite some time. I'll raise the priority on this.

**Comment by AspirinSJL** [comment]
This will be an OKR for this quarter.

**Comment by jtattermusch** [comment]
@yashykt  is this still an issue? The priority is set as P1, so I'd rather let you decided what to do about this issue.

**Comment by ejona86** [comment]
To my knowledge this is still an issue.

**Comment by yashykt** [comment]
Sorry for the delay. I have a proposed solution for this. I'll create a PR for this soon.
