### ISSUE TITLE
Early testing of gRPC C# Nuget Packages on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1623]
The alpha release of C# is coming very soon and I already have a set of NuGet packages that should make using C# on Windows very straightforward (by pulling in all the necessary dependencies including the native ones). The packages are not published yet, but I can make them available for early testing - I'd like to collect some feedback on how using the NuGet packages feels and what are the biggest painpoints.

Let me know if you are interested in playing with gRPC C# on Windows, I can provide some guidance.

**Comment by madhon** [comment]
Hi,

I wouldnt mind testing them as lm looking to replace WCF with it

**Comment by jtattermusch** [comment]
I uploaded the prerelease packages here:

http://storage.googleapis.com/grpc-public/experimental/nuget_release_test/Grpc.0.5.0.nupkg
http://storage.googleapis.com/grpc-public/experimental/nuget_release_test/Grpc.Auth.0.5.0.nupkg
http://storage.googleapis.com/grpc-public/experimental/nuget_release_test/Grpc.Core.0.5.0.nupkg
http://storage.googleapis.com/grpc-public/experimental/nuget_release_test/grpc.native.csharp_ext.0.9.0.0.nupkg

In order to use them, download them to a local directory and setup NuGet on your machine to pick up packages from there.

After that, you should be able to go though the tutorial posted on
https://github.com/grpc/grpc-common/tree/master/csharp

You should also be able to create your own projects based on these packages (I'll post a tutorial on how to generate code for your own service stubs soon).

After the packages get officially released and uploaded to nuget.org, you should just delete any local versions you might have to prevent problems.

**Comment by madhon** [comment]
Thanks,

All looking good so far, only sugestion would be adding the Google.ProtocolBuffers as a dependency (to GRPC.nuspec) so it dosnt need to be manually installed seperately.

**Comment by jtattermusch** [comment]
Thanks for feedback! Can you please shortly describe what's the configuration of your system and what exactly you managed to do?

**Comment by madhon** [comment]
Its a Windows Service on a server, plus winforms clients on multiple workstatiosn. Have currently put the greeter sample into the service and have it in a long running task.

Working on the proto definitions for the wcf service been replacedd at the moment.

**Comment by jtattermusch** [comment]
Sounds good. Is your code opensource by any chance? I'd be interested in seeing the resulting code.

**Comment by madhon** [comment]
It's not open at the moment no, I will look at extracting just the relevant bits though

Sent via mobile

**Comment by jtattermusch** [comment]
I just published the gRPC packages to NuGet.org. You should be able to pull the packages using Visual Studio shortly.
Please throw away any local copies of the testing packages you might have.

**Comment by lotosbin** [comment]
open http://storage.googleapis.com/grpc-public/experimental/nuget_release_test/Grpc.0.5.0.nupkg 

![image](https://cloud.githubusercontent.com/assets/221294/7851850/2806b210-0528-11e5-8dbe-713de3dbb98f.png)

**Comment by jtattermusch** [comment]
@lotosbin NuGet packages for gRPC have been published on nuget.org
http://www.nuget.org/packages/Grpc/

Therefore, you should not need the testing package files that used to be published through links in this issue.

**Comment by lotosbin** [comment]
@jtattermusch Thanks!
