### ISSUE TITLE
Need iOS (ObjC or Swift) example using SSL and self-signed certificates

### ISSUE THREAD

**Issue by robcecil** [grpc/grpc#16258]
Current Objective-C examples for Grpc do not include SSL/TLS. I would like to see an example that demonstrates all the necessary parts for someone who downloads an iOS app distributed in the App Store and uses self-signed certificates for the server (mutual TLS is not required).

Thanks

**Comment by muxi** [comment]
We likely will not have the resource for making such an example for now, but a good resource for this is the [local SSL interop test](https://github.com/grpc/grpc/blob/master/src/objective-c/tests/InteropTestsLocalSSL.m#L54) which does exactly that. The server side for this test is at https://github.com/grpc/grpc/tree/master/test/cpp/interop.

I'll close the issue for now until an example is indeed needed.
