### ISSUE TITLE
Make Grpc.Core nuget work in Xamarin.Forms projects

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16250]
The nuget seems to work well with Xamarin Native projects, but for Xamarin.Forms project it fails to locate the grpc_csharp_ext library.

The main difference between Xamarin.Native and Xamarin.Forms is that Xamarin.Forms is targeting netstandard and uses the new-style .csproj projects (which means the Grpc.Core.targets file is probably not getting picked up)

Context: https://github.com/grpc/grpc/issues/1620#issuecomment-409916143

**Comment by jtattermusch** [comment]
I've done some experiments and it actually seems that the Grpc.Core nuget package works fine with Xamarin.Forms project, but one needs to add the `Grpc.Core` nuget as a dependency also to the `YourProject.Android` and `YourProject.iOS`, not just to the shared `netstandard2.0` library.
Can anyone try that an see if that helped?

**Comment by jtattermusch** [comment]
This is another problem one might run into: https://github.com/grpc/grpc/issues/16310 (but it's not a gRPC bug and it has a workaround).

**Comment by jtattermusch** [comment]
Looks like if Grpc.Core is added as a dependency to the .Android and .iOS Xamarin.Forms project, everything works. Closing the issue.

**Comment by vbisbest** [comment]
Could not get around the Xamarin bug by installing Grpc.Core.  I had to use the workaround and now it works.  Thank you!

**Comment by BlackFrog1** [comment]
@jtattermusch did you get gRPC to work on ARM7?

**Comment by jtattermusch** [comment]
@BlackFrog1   yes, see instructions here:
https://github.com/grpc/grpc/tree/master/src/csharp/experimental

Depending on your situation, you might need to use the workaround mentioned here:
https://github.com/grpc/grpc/issues/16310
