### ISSUE TITLE
Can grpc++_reflection be used with grpc++_unsecure?

### ISSUE THREAD

**Issue by ttencate** [grpc/grpc#16282]
### What version of gRPC and what language are you using?

gRPC 1.11.0, C++.
 
### What operating system (Linux, Windows, …) and version?
 
Arch Linux.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
g++ 8.2.0, CMake 3.11.4.
 
### What did you do?

I'm building an application that uses the `grpc++_unsecure` version of the gRPC library, because this will run mostly on a single machine and otherwise on a local, trusted network. Using `_unsecure` helps me avoid versioning hell for OpenSSL, making it easier to distribute binaries.

However, I also want to use `grpc++_reflection`, because `grpc_cli` won't talk to the server without it. But as it stands, `grpc++_reflection` depends on `grpc++`, which is the secure version, with the OpenSSL dependency.
 
### What did you expect to see?
 
I would expect reflection not to depend on security.
 
### What did you see instead?
 
Building `grpc++_reflection` builds and links with `grpc++`. This is true for Bazel as can be seen in the `BUILD` file, and also for CMake as can be seen in the build output:

```
$ make grpc++_reflection
[  0%] Built target address_sorting
[  7%] Built target c-ares
[ 14%] Built target gpr
[ 61%] Built target grpc
[ 73%] Built target libprotobuf
[ 73%] Built target js_embed
[ 88%] Built target libprotoc
[ 90%] Built target protoc
[ 97%] Built target grpc++                <<< HERE
[ 97%] Built target grpc_plugin_support
[100%] Built target grpc_cpp_plugin
[100%] Built target grpc++_reflection
```

Maybe there's a good reason for this, in which case I'll shut up. But I'm hoping this is just an oversight and the dependencies can be trimmed.

**Comment by nicolasnoble** [comment]
That's kind of a difficult problem. The two libraries (grpc++ and grpc++_unsecure) are mutually exclusive. Yet the reflection library has to depend on one of them. Maybe the solution would be to create a grpc++_reflection_unsecure target... ? But that's kind of weird, I guess.

**Comment by ttencate** [comment]
Ah, I see.

Maybe _unsecure shouldn't exist in the first place; there could just be grpc(++), which does or does not have SSL support, configurable through a build flag. But that's a rather big hammer that would break half the world just to fix this minor annoyance.

I wonder if the reflection library does indeed have to depend on one of them? Can it be left up to the user to build and link either grpc++ or grpc++_unsecure if they use grpc++_reflection? This might not even break so much, because it seems unlikely that anyone links solely with grpc++_reflection and relies on its dependencies to be pulled in automatically.

But with the broad spectrum of build systems and platforms supported by gRPC, such a change is probably far more difficult than I imagine. So I'll just close this. Thank you for your consideration!

**Comment by nicolasnoble** [comment]
In terms of symbol resolution, this would be a fairly fragile solution to not have an explicit dependency. It's definitely doable, but...
