### ISSUE TITLE
[cpp] Greeter example doesn't work anymore

### ISSUE THREAD

**Issue by edmBernard** [grpc/grpc#16292]
I recently got an error when running greeter example. This issue appear after I have to reinstall grpc. (between june and now). As `c-ares` as not been update between this period, I think the change have been made on grpc side.

### What version of gRPC and what language are you using?
In C++, installed with vcpkg
```
c-ares:x64-linux                                 1.14
grpc:x64-linux                                   1.13.1           
protobuf:x64-linux                               3.6.1-2
```

### What operating system (Linux, Windows, …) and version?
Linux 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-8
 
### What did you do?
I just build greeter example [here](https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld) and run the greeter_client
 
### What did you see instead?
I got this error, it came from dns resolver issues. I got the same error with `127.0.0.1`, `google.fr`, or everything else
```bash
E0809 10:44:25.034452207    9221 resolver_registry.cc:80]    don't know how to resolve 'localhost:50051' or 'dns:///localhost:50051'
E0809 10:44:25.034522680    9221 resolver_registry.cc:80]    don't know how to resolve 'dns:///localhost:50051' or 'dns:///dns:///localhost:50051'
E0809 10:44:25.034546389    9221 channel.cc:94]              channel stack builder failed: {"created":"@1533804265.034530436","description":"resolver creation failed","file":"/home/ebernard/Documents/tools/vcpkg/buildtrees/grpc/src/v1.13.1-db9510abcf/src/core/ext/filters/client_channel/client_channel.cc","file_line":695}
2: lame client channel
Greeter received: RPC failed
```

**Comment by edmBernard** [comment]
The issue come with my `CMakeLists.txt`. I use all libraries list in vcpkg usage. But It seem there is an issu with grpc_cronet component:

* This line create client with the previous issue: 
`target_link_libraries(greeter_client PRIVATE c-ares::cares protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite gRPC::gpr gRPC::grpc++ gRPC::grpc_cronet -pthread)`
* This line create working client:
`target_link_libraries(greeter_client PRIVATE c-ares::cares protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite gRPC::gpr gRPC::grpc++ -pthread)`

**Comment by apolcyn** [comment]
I'm not super familiar with cronet, but I believe that cronet actualy [does not register a DNS resolver](https://github.com/grpc/grpc/blob/master/src/core/plugin_registry/grpc_cronet_plugin_registry.cc#L34) - cc @muxi is it the intention that the plugins specified in `grpc_cronet_plugin_registry.cc` are the <i>only</i> plugins used when building gRPC with the cronet library?

```
This issue appear after I have to reinstall grpc. (between june and now). As c-ares as not been update between this period, I think the change have been made on grpc side.
```

@edmBernard did this used to work for you when building with cronet as you are describing here?

**Comment by muxi** [comment]
@apolcyn yes the cronet-specific plugin is supposed to register the cronet related plugins. For cpp builds the grpc_cronet target is not supposed to be in the list of targets.

**Comment by apolcyn** [comment]
> For cpp builds the grpc_cronet target is not supposed to be in the list of targets.

@muxi thanks, to verify, this means that:

```
target_link_libraries(greeter_client PRIVATE c-ares::cares protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite gRPC::gpr gRPC::grpc++ gRPC::grpc_cronet -pthread)
```

is invalid usage, correct?

**Comment by muxi** [comment]
yea

**Comment by apolcyn** [comment]
@edmBernard based off of this, indeed, as you suspected, it looks like the fact that your linking `grpc_cronet` is the problem... C++ is not meant to be built with `grpc_cronet` as @muxi pointed out.

**Comment by apolcyn** [comment]
> Should we fix it rather than closing the issue?

you're call :) I know very little about cronet

However, if fixing it, I'd prefer to open a new issue that is more clearly a feature request and not a bug in the c++ example.

**Comment by muxi** [comment]
I am fairly sure it was a bug rather than a feature request. But from the issue description and looks like it is gone? If so I'm fine with it.
