### ISSUE TITLE
The cmake target name of gflags is `gflags`  instead of `gflags::gflags`. 

### ISSUE THREAD

**Issue by hhggit** [grpc/grpc#16291]
`_gRPC_GFLAGS_LIBRARIES` would be wrongly configured if the `gRPC_GFLAGS_PROVIDER` option were configured as "package".

The cmake  target name of gflags is `gflags`  instead of `gflags::glags`. 

The following patch should be applied to [cmake/gflags.cmake](https://github.com/grpc/grpc/blob/master/cmake/gflags.cmake)
```patch
31,32c31,32
<   if(TARGET gflags::gflags)
<     set(_gRPC_GFLAGS_LIBRARIES gflags::gflags)
---
>   if(TARGET gflags)
>     set(_gRPC_GFLAGS_LIBRARIES gflags)
```

**Comment by jtattermusch** [comment]
Can you elaborate what do you mean by "wrongly configured". The original line actually seems correct to me and we are using the same xxx::yyy format for other dependencies as well - e.g. https://github.com/grpc/grpc/blob/cb87dd9fef97d1e1fb2559be68188c0792a3ecd8/cmake/gflags.cmake#L31 and https://github.com/grpc/grpc/blob/cb87dd9fef97d1e1fb2559be68188c0792a3ecd8/cmake/benchmark.cmake#L31
and we have continuous tests for this that seem to work. 
E.g. here: https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.sh

**Comment by hhggit** [comment]
I compiled and installed the gflags 2.2.1 using the general steps `mkdir build; cd build ; cmake .. ; make ; sudo make install`,  the target gflags::gflags did't exist. 

The continuous tests worked well because helloworld example didn't need to link the gflags.

Here is the error ouput of `make grpc_cli`:

```
[100%] Linking CXX executable grpc_cli
/usr/bin/cmake -E cmake_link_script CMakeFiles/grpc_cli.dir/link.txt --verbose=1
/usr/local/bin/c++   -std=c++11  -rdynamic CMakeFiles/grpc_cli.dir/test/cpp/util/grpc_cli.cc.o CMakeFiles/grpc_cli.dir/third_party/googletest/googletest/src/gtest-all.cc.o CMakeFiles/grpc_cli.dir/third_party/googletest/googlemock/src/gmock-all.cc.o  -o grpc_cli -Wl,-rpath,/usr/local/lib /usr/local/lib/libprotobuf.so -ldl -lrt -lm -lpthread libgrpc_cli_libs.a libgrpc++_proto_reflection_desc_db.a libgrpc++.a libgrpc.a libgpr.a libgrpc++_test_config.a /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libz.so /usr/local/lib/libcares.so.2.2.0 -lnsl libaddress_sorting.a /usr/local/lib/libprotobuf.so -ldl -lrt -lm -lpthread 
CMakeFiles/grpc_cli.dir/test/cpp/util/grpc_cli.cc.o: In function `__static_initialization_and_destruction_0(int, int)':
grpc_cli.cc:(.text+0x2ee): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
libgrpc_cli_libs.a(cli_credentials.cc.o): In function `__static_initialization_and_destruction_0(int, int)':

```

**Comment by jtattermusch** [comment]
@hhggit  you're right, thanks for detailed analysis.

The PR with fix is here: https://github.com/grpc/grpc/pull/16343
