### ISSUE TITLE
Python grpcio-1.14.1 Segmentation Faults caused by Channel.close() when used with connectivity-state subscriptions

### ISSUE THREAD

**Issue by e-heller** [grpc/grpc#16290]
### Questions

- **What version of gRPC and what language are you using?**

  Language: **Python** `2.7.15`, `3.6.6`
  
  gRPC:  **`grpcio-1.14.1`** &nbsp; &nbsp; (same issue in `1.14.0`, `1.13.1`, `1.13.0`)

- **What operating system and version?**

  Linux: Fedora 28,  Ubuntu 16.04
    
- **What runtime / compiler are you using**

  Python `2.7.15` and `3.6.6`, using the `grpcio` package straight from [pypi.org](https://pypi.org)

 
### What did you do?

We upgraded from gRPC `1.11.1` to `1.14.1` and tried to use the new ``Channel.close()`` method.

Now gRPC is causing **Segmentation Faults**.  

This seems to be correlated to an interaction between *subscriptions* to Channel 
connectivity-state and the Channel's *`close()` method.* 

This is issue is not present in grpc `1.11.1` (there is no `close()` method after all).

As fas as I understand, this is the **correct** procedure:
1. Create a channel
2. Add a subscription callback
3. Invoke some RPCs
4. Unsubscribe the callback
5. Close the channel

Yet even doing the *correct* thing, we are getting occasional segfaults.

Worse yet, if your code misses a step or gets anything out of order -- you don't
get an Exception -- you get **segfaults**. For example:

1. Call `subscribe()` *after* the channel is closed --> *segfault every time*
2. Call `unsubscribe()` *after* the channel is closed --> frequent segfaults
3. Forget to unsubscribe the callback and close the channel --> frequent segfaults

### What did you expect to see?

- In all cases, I expect gRPC **will not segfault**

- In the case where all events are done with correct procedure, I expect no
  Exceptions, no noisy and misleading log messages.
  
- If `subscribe` or `unsubscribe` are called *after* the channel is closed,
  I would expect to get a python Exception that I can handle.

- If `unsubscribe` is *not called* before the channel is closed, I expect to
  see no error, or at most a logged error. gRPC should close the channel and
  discard the subscribed callback function.

 
### What did you see instead?

1. **Segmentation faults**
2. Lots of noisy logged exceptions. The message accompanying these log errors
   is misleading as well.

----

### Example code

These examples use the `helloworld` protos and run against the `greeter_server.py`
from the `examples` directory of this repo.

### Example 1: call subscribe() *after* the channel is closed

This will immediately result in a segfault every time:

```python
from __future__ import print_function
import grpc
import helloworld_pb2
import helloworld_pb2_grpc

def run():
    channel = grpc.insecure_channel('localhost:50051')
    stub = helloworld_pb2_grpc.GreeterStub(channel)
    
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='Stranger'))
    print('Response: {}'.format(response.message))
    
    channel.close()
    # Don't subscribe to a closed channel. This is no exception, it's a segfault!
    channel.subscribe(connectivity_callback, try_to_connect=True)

def connectivity_callback(state):
    pass  # no-op

if __name__ == '__main__':
    run()
```

#### Output: Example 1 

- **1.1**
  ```
  $ python subscribe_after_close.py
  
  Response 0: Hello, Stranger!
  Segmentation fault
  ```

----

### Example 2: call unsubscribe() after the channel is closed

This randomly (but frequently) results in a segfault:

```python
from __future__ import print_function
import grpc
import helloworld_pb2
import helloworld_pb2_grpc

def run():
    for count in range(50):
        run_once(count)

def run_once(count):
    channel = grpc.insecure_channel('localhost:50051')
    stub = helloworld_pb2_grpc.GreeterStub(channel)

    channel.subscribe(connectivity_callback, try_to_connect=True)

    response = stub.SayHello(helloworld_pb2.HelloRequest(name='Stranger'))
    print('Response {}: {}'.format(count, response.message))

    channel.close()                                         #  <-----
    # Yikes! Don't unsubscribe after closing the channel!
    channel.unsubscribe(connectivity_callback)              #  <-----

def connectivity_callback(state):
    pass  # no-op

if __name__ == '__main__':
    run()
```

#### Output: Example 2 

- **2.1**
  ```
  $ python unsubscribe_after_close.py
  
  Response 0: Hello, Stranger!
  Response 1: Hello, Stranger!
  Segmentation fault
  ```
  
- **2.2**
  ```
  $ python unsubscribe_after_close.py
  
  Response 0: Hello, Stranger!
  Response 1: Hello, Stranger!
  Exception in thread Thread-1:
  Traceback (most recent call last):
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 754, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/home/eheller/pew_envs/grpc-seg14/lib/python2.7/site-packages/grpc/_channel.py", line 801, in _poll_connectivity
      time.time() + 0.2)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 451, in grpc._cython.cygrpc.Channel.watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc._watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 344, in grpc._cython.cygrpc._watch_connectivity_state
  ValueError: Cannot invoke RPC on closed channel!
  
  ****  Cut for brevity  ****
  
  Response 2: Hello, Stranger!
  Response 3: Hello, Stranger!
  Exception in thread Thread-8:
  Traceback (most recent call last):
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 754, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/home/eheller/pew_envs/grpc-seg14/lib/python2.7/site-packages/grpc/_channel.py", line 801, in _poll_connectivity
      time.time() + 0.2)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 451, in grpc._cython.cygrpc.Channel.watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc._watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 344, in grpc._cython.cygrpc._watch_connectivity_state
  ValueError: Cannot invoke RPC on closed channel!
  
  Response 4: Hello, Stranger!
  Segmentation fault
  ```

----

### Example 3: forget to call unsubscribe() before closing the channel

This randomly (but frequently) results in a segfault:

```python
from __future__ import print_function
import grpc
import helloworld_pb2
import helloworld_pb2_grpc

def run():
    for count in range(50):
        run_once(count)

def run_once(count):
    channel = grpc.insecure_channel('localhost:50051')
    stub = helloworld_pb2_grpc.GreeterStub(channel)

    channel.subscribe(connectivity_callback, try_to_connect=True)

    response = stub.SayHello(helloworld_pb2.HelloRequest(name='Stranger'))
    print('Response {}: {}'.format(count, response.message))

    # Danger! Don't forget to unsubscribe your callback!
    ## channel.unsubscribe(connectivity_callback)           #  <-----
    channel.close()                                         #  <-----

def connectivity_callback(state):
    pass  # no-op

if __name__ == '__main__':
    run()
```

#### Output: Example 3 

- **3.1**
  ```
  $ python forget_to_unsubscribe.py
  
  Response 0: Hello, Stranger!
  Response 1: Hello, Stranger!
  Exception in thread Thread-1:
  Traceback (most recent call last):
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 754, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/home/eheller/pew_envs/grpc-seg14/lib/python2.7/site-packages/grpc/_channel.py", line 801, in _poll_connectivity
      time.time() + 0.2)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 451, in grpc._cython.cygrpc.Channel.watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc._watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 344, in grpc._cython.cygrpc._watch_connectivity_state
  ValueError: Cannot invoke RPC on closed channel!
  
  ****  Cut for brevity  ****
  
  Response 4: Hello, Stranger!
  Exception in thread Thread-10:
  Traceback (most recent call last):
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 754, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/home/eheller/pew_envs/grpc-seg14/lib/python2.7/site-packages/grpc/_channel.py", line 801, in _poll_connectivity
      time.time() + 0.2)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 451, in grpc._cython.cygrpc.Channel.watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc._watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 344, in grpc._cython.cygrpc._watch_connectivity_state
  ValueError: Cannot invoke RPC on closed channel!
  
  Segmentation fault
  ```

----

### Example 4: Do everything right and still get segfaults

As far as I know, this example does everything correctly.
It does not segfault *very often*, but it still happens. Maybe worth mentioning
that we have not observed this to segfault in Python 3.

```python
from __future__ import print_function
import grpc
import helloworld_pb2
import helloworld_pb2_grpc

def run():
    for count in range(50):
        run_once(count)

def run_once(count):
    # This is how it's supposed to work right?
    channel = grpc.insecure_channel('localhost:50051')
    stub = helloworld_pb2_grpc.GreeterStub(channel)

    channel.subscribe(connectivity_callback, try_to_connect=True)

    response = stub.SayHello(helloworld_pb2.HelloRequest(name='Stranger'))
    print('Response {}: {}'.format(count, response.message))

    channel.unsubscribe(connectivity_callback)
    channel.close()

def connectivity_callback(state):
    pass  # no-op

if __name__ == '__main__':
    run()
```

#### Output: Example 4

- **4.1**
  ```
  $ python the_right_way.py
  
  Response 0: Hello, Stranger!
  Response 1: Hello, Stranger!
  Response 2: Hello, Stranger!
  Response 3: Hello, Stranger!
  Segmentation fault
  ```

- **4.2**
  ```
  $ python the_right_way.py
  
  Response 0: Hello, Stranger!
  Response 1: Hello, Stranger!
  Response 2: Hello, Stranger!
  Response 3: Hello, Stranger!
  Exception in thread Thread-10:
  Traceback (most recent call last):
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 754, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/home/eheller/pew_envs/grpc-seg14/lib/python2.7/site-packages/grpc/_channel.py", line 801, in _poll_connectivity
      time.time() + 0.2)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 451, in grpc._cython.cygrpc.Channel.watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc._watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 344, in grpc._cython.cygrpc._watch_connectivity_state
  ValueError: Cannot invoke RPC on closed channel!
  Response 4: Hello, Stranger!
  
  Response 5: Hello, Stranger!
  Response 6: Hello, Stranger!
  Response 7: Hello, Stranger!
  Response 8: Hello, Stranger!
  Response 9: Hello, Stranger!
  Response 10: Hello, Stranger!
  Response 11: Hello, Stranger!
  Segmentation fault
  ```

----

### Example 5: If Example 4 didn't segfault, try it with a bunch of threads!

If the "correct" code seems like its working, try running the same thing with 
with a small threadpool.

```python
from __future__ import print_function
from concurrent import futures
import grpc
import helloworld_pb2
import helloworld_pb2_grpc

def run():
    executor = futures.ThreadPoolExecutor(max_workers=8)
    calls = [executor.submit(run_once, count) for count in range(128)]
    futures.wait(calls)

def run_once(count):
    channel = grpc.insecure_channel('localhost:50051')
    stub = helloworld_pb2_grpc.GreeterStub(channel)

    channel.subscribe(connectivity_callback, try_to_connect=True)

    response = stub.SayHello(helloworld_pb2.HelloRequest(name='Stranger'))
    print('Response {}: {}'.format(count, response.message))

    channel.unsubscribe(connectivity_callback)
    channel.close()

def connectivity_callback(state):
    pass  # no-op
    
if __name__ == '__main__':
    run()
```

#### Output: Example 5

- **5.1**
  ```
  $ python the_right_way_threaded.py 
  
  Response 0: Hello, Stranger!
  Response 2: Hello, Stranger!
  Response 1: Hello, Stranger!
  Response 4: Hello, Stranger!
  Response 3: Hello, Stranger!
  Response 5: Hello, Stranger!
  Segmentation fault
  ```

- **5.2**
  ```
  $ python the_right_way_threaded.py 
  
  Response 0: Hello, Stranger!
  Response 1: Hello, Stranger!
  Response 3: Hello, Stranger!Response 2: Hello, Stranger!
  
  Response 6: Hello, Stranger!
  Response 4: Hello, Stranger!
  Exception in thread Thread-3:
  Traceback (most recent call last):
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/home/eheller/.pythonz/pythons/CPython-2.7.15/lib/python2.7/threading.py", line 754, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/home/eheller/pew_envs/grpc-seg14/lib/python2.7/site-packages/grpc/_channel.py", line 801, in _poll_connectivity
      time.time() + 0.2)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 451, in grpc._cython.cygrpc.Channel.watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc._watch_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 344, in grpc._cython.cygrpc._watch_connectivity_state
  ValueError: Cannot invoke RPC on closed channel!
  
  Segmentation fault
  ```

----

### Anything else we should know about your project / environment?

We are trying to upgrade from grpcio `1.11.1` to `1.14.x`. These issues have
been a complete show-stopper for us.

I anticipate that only a small fraction of users make use of these Channel
connectivity-state subscriptions. However, they are quite important to our
implementation and our growing gRPC-based platform.

Thanks!

**Comment by mehrdada** [comment]
Thanks for the elaborate bug report. Unfortunately `Channel.close` which should have been available since v1.0 has been a bolt-on thing in 1.12 and we should define and document the behavior (raise an Exception on any operations using a closed channel) for usability. I am particularly worried about the segfaults on the "right" scenario. Let me investigate further. In the meantime, if you can try `GRPC_TRACE=api GRPC_VERBOSITY=debug` and see if that gives you a clue when the segfault happens it'd be great.

**Comment by ericgribkoff** [comment]
Thanks for reporting this, especially with such great steps for reproduction. The segfaults for the "correct" usage (unsubscribe before closing) are fixed by the changes in https://github.com/grpc/grpc/pull/16264 (we will be calling close() on channels as part of the fork handling, which surfaced some of these issues during testing).

**Comment by mehrdada** [comment]
@e-heller Do you face any issues if you update to 1.14.1 and **not** call `Channel.close`?

**Comment by e-heller** [comment]
@mehrdada - _Do you face any issues if you update to 1.14.1 and not call Channel.close? (which I assume you weren't calling before because it is nonexistent)_

No, if we don't call `close()` there are no issues. I think @ericgribkoff explains the issue, in the Cython code (`channel.pyx.pxi`) the `_close` function sets the `c_channel` pointer to `NULL`, and later no null-check is performed (or checking for `_ChannelState.open`)

**Comment by mehrdada** [comment]
@e-heller If that's the case, I recommend upgrading to 1.14.1 in the meantime without utilizing `close` as a workaround while we fix the bug, as the behavior would be no worse than 1.11.x without `Channel.close` (despite the warnings in release notes, that change was made very judiciously to make minimal impact to existing users who don't call `Channel.close` for now but we plan to fully and only rely on `Channel.close` to free channel resources.)

**Comment by e-heller** [comment]
@ericgribkoff - I may be wrong, but it looks like there's a possible race condition in `channel.pyx.pxi` starting at [line 345][1].  The `state.condition` is first acquired and an [exception is thrown][2] if not `state.open`.  But it's possible the channel is closed in another thread before the `state.condition` is again reacquired in [line 347][3]. This may be harmless, I just happened to notice.

(_much less important_, but the message on that [exception][2] is a bit misleading (and very noisy), `'Cannot invoke RPC on closed channel!'` since we're not invoking any RPC here.)

[1]: https://github.com/grpc/grpc/blob/v1.14.1/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi#L345
[2]: https://github.com/grpc/grpc/blob/v1.14.1/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi#L344
[3]: https://github.com/grpc/grpc/blob/v1.14.1/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi#L347

**Comment by e-heller** [comment]
@mehrdada - _I recommend upgrading to 1.14.1 in the meantime without utilizing close_

I expect there would be some repercussions to this, no?

In `1.11.x` when the channel is finally GC'ed, it triggers the [`__dealloc__`][1] method in the Cython Channel, calling `grpc_channel_destroy` and `grpc_shutdown` 

In `1.14.x`, if we omit the call to `close()`, the underlying C channel will never be destroyed right? We have a lot of long-running processes that create/"close" _a lot_ of channels, so that concerns me.

[1]: https://github.com/grpc/grpc/blob/v1.11.x/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi#L92

**Comment by ericgribkoff** [comment]
> @ericgribkoff - I may be wrong, but it looks like there's a possible race condition in channel.pyx.pxi starting at line 345. The state.condition is first acquired and an exception is thrown if not state.open. But it's possible the channel is closed in another thread before the state.condition is again reacquired in line 347. This may be harmless, I just happened to notice.

You're correct. The call into `_latent_event` can segfault if the channel has been closed. I'll set aside some time to audit all of the channel ops with regards to `channel.close()`, as there may well be other race conditions we haven't noticed yet...

> (much less important, but the message on that exception is a bit misleading (and very noisy), 'Cannot invoke RPC on closed channel!' since we're not invoking any RPC here.)

Agreed, but was unsure about flexibility/Python API semantics here: @mehrdada, is changing the message string considered API-breaking? Would we be able to return a custom exception type here altogether rather than just `ValueError`?

**Comment by mehrdada** [comment]
@ericgribkoff Feel free to change the message. Let's keep going with `ValueError`.

In fact, I'd change a message to say something to the effect of invoking the **Python method** on the closed channel has been erratic, even if the operation is a no-op. The only valid thing you can call repeatedly on a closed channel is `close()` (I have to think more deeply about this; maybe `unsubscribe_callback` too).

If someone is using the channel after `close`, they are making a programming error. It's really more analogous to an assertion failure, not supposed to be caught and handled.

**Comment by mehrdada** [comment]
> In 1.14.x, if we omit the call to close(), the underlying C channel will never be destroyed right? We have a lot of long-running processes that create/"close" a lot of channels, so that concerns me.

I don't know for sure about the extent of it, but my understanding is @nathanielmanistaatgoogle took care of it to behave at least fairly rationally in a transition period for a couple releases even if you do not explicitly call `close` so as to not break existing users. We have yet to change that, but are increasing the volume on warnings that it'll happen soon.

**Comment by e-heller** [comment]
@ericgribkoff - _Would we be able to return a custom exception type here altogether rather than just ValueError?_

I like this idea. The Exception type could b a subclass of `ValueError` to maintain API consistency there.

**Comment by mehrdada** [comment]
gRPC Python has gone from a beta phase of having many many exception type to consolidating them. Please do not add an additional exception type. I can't imagine someone breaking because of this. `ValueError` is fine with the new error message. We never documented the error message to be a certain thing so it is not part of the API.

**Comment by e-heller** [comment]
@mehrdada - _If someone is using the channel after close, they are making a programming error. It's really more analogous to an assertion failure_

For sure, it's a programming error in the client application code, _my code_. But I slightly disagree that it's like an assertion not meant to be caught and handled.

The difficultly is there's no way to ascertain if a channel _is already closed_ before I invoke, say `Channel.unsubscribe()`.  A catchable exception here is very useful so I know that the channel is _invalid_.

**Comment by mehrdada** [comment]
I'd like to zoom out and hear more about the high level goal of the code that will invoke this. In the particular case of `unsubscribe`, a valid (and potentially better) resolution might be to allow it be a no-op instead.

**Comment by e-heller** [comment]
@mehrdada 
>  In the particular case of unsubscribe, a valid (and potentially better) resolution might be to allow it be a no-op instead.

I'm OK with that as well. I was considering that the rest of the `Channel` interface raises an exception upon invoking methods on a closed Channel and thinking `unsubscribe` might act likewise. 

Re: determining if a channel is closed.
> In any case, I can see that being an additional feature request. We can amend the functionality and do as you say, to raise a different exception type (or alternatively decide to expose an API to communicate the channel closed state),

I should have made the disclaimer that I did not intend to suggest exposing another method on the `Channel` interface (definitely understand the implication/costs of such decisions).
My point was just that: *if* I do not know the channel is disposed, I may not know to *not* to invoke some method. So if I do invoke a method on a closed channel I would prefer a predictable result, like an exception I can catch.  `unsubscribe` is perhaps a bit different, as even with a valid channel there is no return value or indication of success. So a no-op here probably makes the most sense.

**Comment by e-heller** [comment]
@ericgribkoff, @mehrdada - When do you expect these [fixes](https://github.com/grpc/grpc/pull/16296) to be rolled into a gRPC release?

**Comment by e-heller** [comment]
@srini100 - Thanks!

**Comment by srini100** [comment]
@e-heller, https://github.com/grpc/grpc/pull/16296 is now available in v1.14.2 RC in case you want to try it out. 1.15.0 RC is still on track for Aug 26.

**Comment by e-heller** [comment]
@srini100 - Thanks for the notice. Will begin testing.

**Comment by srini100** [comment]
@ericgribkoff, assigning this to you to see if there are any more corner cases left in this area.

**Comment by ericgribkoff** [comment]
Marking this closed. Our tests are now using `channel.close()`, and there do not appear to be any remaining seg fault issues with operations on a closed channel (rather, we seem to have remaining issues with garbage collection on channels that have *not* been closed, but that is a separate issue and under investigation elsewhere.
