### ISSUE TITLE
Failed to install grpc@1.7.3

### ISSUE THREAD

**Issue by nschirmer** [grpc/grpc#16300]
### What version of gRPC and what language are you using?
`grpc@1.7.3` with `node -v 10.6.0`, `npm -v 6.1.0`, `node-gyp -v 3.6.2`
 
### What operating system (Linux, Windows, …) and version?
macOS High Sierra
 
### What did you do?
Just trying to `npm install` my project dependencies and it's failing on grpc step 
 
### What did you see instead?
 
Here's my output log: https://gist.github.com/nschirmer/7d289d4597ee78e8b4d57a27643fd3dd

Here's a "quick fix" I tried that did not help: https://gist.github.com/djnetherton/783b0cb8e5b437c5b66001e3e6551993

Thanks.

**Comment by nschirmer** [comment]
I'm attempting an `npm rebuild` right now as a potential solution.

**Comment by murgatroid99** [comment]
Is that output log the console output from running the command, or the contents of the log file that it generates?

**Comment by nschirmer** [comment]
Log file it generates

**Comment by murgatroid99** [comment]
Can you share the console output too? Sometimes information shows up there but not in the log file.

**Comment by nschirmer** [comment]
Sure thing @murgatroid99 -- here you go: https://gist.github.com/nschirmer/f11f9ccc7f659c015d18bd2d789c5625

This is from my most recent `npm install` attempt after completing an `npm rebuild` (so that didn't help :()

**Comment by murgatroid99** [comment]
OK, the main problem (which I should have noticed earlier) is that you're trying to install a kind of old version of grpc (1.7) on a very new version of Node (10), and they are not compatible. I don't recognize that compilation error, but we have probably fixed it in a more recent version. Unfortunately, your only viable choices are probably to use a newer version of grpc or an older version of Node.

**Comment by nschirmer** [comment]
Thank you @murgatroid99, that makes sense! First real time working within a node project and I forgot to double check with the other contributors to find out which node version they were running locally.

I've switched down to node@6.11.5 and npm@6.3.0 now to match someone else. `npm install` now works without error!

Thanks again.
