### ISSUE TITLE
C++ ServerAsyncWriter::Write/Finish input parameters life-time requirements are undocumented.

### ISSUE THREAD

**Issue by rainer-ibm** [grpc/grpc#16313]
### What version of gRPC and what language are you using?
 v1.13.0 using C++
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
 
### What did you do?
I want to send messages to an asynchronous streaming RPC (reply stream) using the `ServerAsyncWriter`.
The `Write` method is documented as follows (also see [here](https://grpc.io/grpc/cpp/classgrpc_1_1_server_async_writer.html#a467f70c7460ceb7738fb938b3bf93c85)):

    /// Request the writing of \a msg with identifying tag \a tag.
    ///
    /// Only one write may be outstanding at any given time. This means that
    /// after calling Write, one must wait to receive \a tag from the completion
    /// queue BEFORE calling Write again.
    /// This is thread-safe with respect to \a AsyncReaderInterface::Read
    ///
    /// \param[in] msg The message to be written.
    /// \param[in] tag The tag identifying the operation.
    virtual void Write(const W& msg, void* tag) = 0;

The `Finish` method has a similar documentation.

From this it is not clear for me how the life-time of the input parameter `msg` (or `status` in case of `Finish` method) should be. As a developer I need to know when the passed object is allowed to be de-allocated.

Will the following code be reliable?

    // allocate a new message
    MyMessage * p_message= new MyMessage();

    // starts an async write operation sending the
    // message to the stream
    myWriter.Write(*p_message, 0);

    // free message memory
    delete p_message;

Or do i have to wait until the tag is returned from the CQ? something like this:

    // allocate a new message
    MyMessage * p_message = new MyMessage();

    // starts an async write operation sending the
    // message to the stream
    myWriter.Write(*p_message, 0);

    // wait for async write operation to complete
    int tag = 1;
    while(tag != 0)
    {
        bool success;
        // ignores errors for this pseudo-example
        myCq.Next(tag, success);
    }

    // free message memory
    delete p_message;
 
### What did you expect to see?
 Documented life-time requirements for all input parameters passed by reference.
 
### What did you see instead?
No documentation found in the API reference.
 
### Anything else we should know about your project / environment?
I did some tests in which I modified the message datastructure immediately after calling `Write`. The receiver always received the un-modified message. However this does proof nothing, as due to thread scheduling effects the message could already have been sent before modifying it.

**Comment by yashykt** [comment]
Should be done after #16384

**Comment by rainer-ibm** [comment]
Thanks for documenting this :-)

**Comment by yashykt** [comment]
Merged #16384
