### ISSUE TITLE
Set Default deadline to Infinity 

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1632]
When starting a new call:

C++ sets default deadline to infinity.
Ruby sets it to 5 seconds.
I've not investigated others.

**Comment by murgatroid99** [comment]
Node and PHP both use infinity.

Though, I haven't actually plumbed deadline handling all the way through the PHP library, so you can't change it.

**Comment by soltanmm** [comment]
Python defaults to ∞.

**Comment by ctiller** [comment]
Suggest changing ruby to infinity then?
@a11r - your call I think.

**Comment by a11r** [comment]
Everyone should default to infinity. I will try to discuss separately if
such decision about defaults should just be delegated down to the C-core.

**Comment by soltanmm** [comment]
Putting my hat in for not pushing defaults to the core; that sounds like changing/adding function signatures at the most and adding a trivial (arguably spurious) constant alias to `gpr_inf_future` at the least.
