### ISSUE TITLE
ObjC: Support for tvOS

### ISSUE THREAD

**Issue by samsidd** [grpc/grpc#16338]
Need to integrate grpc in a tvOS project. (objective-C)

**Comment by jtattermusch** [comment]
Please add a description. Are you looking for Unity or Xamarin support for tvOS?

**Comment by samsidd** [comment]
@jtattermusch thanks for your reply, no I am looking to integrate it in native Apple TV project.

**Comment by jtattermusch** [comment]
@samsidd  so i assume this request is for Obj-C language?

**Comment by jtattermusch** [comment]
CC @muxi

**Comment by samsidd** [comment]
@jtattermusch Yes, it's for Objective-C

**Comment by muxi** [comment]
tvOS is not officially supported for now, but feel free to try adding tvOS as supported platform in your local podspec and test it out. If things not working out, we can discuss the issue here.

**Comment by muxi** [comment]
`gRPC-ProtoRPC` depends on 3 other pods. You'll need to update `gRPC-ProtoRPC`, `gRPC`, `gRPC-Core` and `gRPC-RxLibrary`.

**Comment by srini100** [comment]
@samsidd, another user is also interested: https://github.com/grpc/grpc/issues/14173. See if you can leverage that work or collaborate.

**Comment by jlaws** [comment]
Ping

**Comment by muxi** [comment]
This issue was addressed in #19787. Please open bug specific issues if there's bug found. Closing this issue.
