### ISSUE TITLE
grpc node server failed to bind to port 

### ISSUE THREAD

**Issue by Reasno** [grpc/grpc#16363]
### What version of gRPC and what language are you using?
 1.14.1 nodejs
 
### What operating system (Linux, Windows, …) and version?
 Linux 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
start grpc server
### What did you expect to see?
 server bind to port
 
### What did you see instead?
 server could not bind to port.

Without GRPC_VERBOSITY=DEBUG
```
E0816 16:42:01.733381380   16045 server_chttp2.cc:40]        {"created":"@1534408921.733338610","description":"No address added out of total 1 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1534408921.733333730","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_custom.cc","file_line":402,"referenced_errors":[{"created":"@1534408921.733332167","description":"Failed to bind to port","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":73,"grpc_status":14,"os_error":"invalid argument"}]}]}
```
With GRPC_VERBOSITY=DEBUG
```
D0816 16:39:10.144184522   14303 dns_resolver.cc:339]        Using native dns resolver
I0816 16:39:10.144395423   14303 init.cc:155]                grpc_init(void)
I0816 16:39:10.145084936   14303 completion_queue.cc:433]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0816 16:39:10.183374758   14303 server.cc:944]              grpc_server_create((nil), (nil))
I0816 16:39:10.183416437   14303 server.cc:930]              grpc_server_register_completion_queue(server=0x41bdf40, cq=0x4117c20, reserved=(nil))
is development enveloment ?  false
I0816 16:39:10.641768520   14303 server_chttp2.cc:34]        grpc_server_add_insecure_http2_port(server=0x41bdf40, addr=127.0.0.1:25)
I0816 16:39:10.641876142   14303 tcp_server_custom.cc:380]   SERVER 0x4269e70 add_port [::ffff:127.0.0.1]:25 error="No Error"
Segmentation fault
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

The code runs fine in testing and developing environment but only fails on this production machine.

**Comment by nicolasnoble** [comment]
Would it be possible to run node in gdb in order to get a stacktrace of the segmentation fault? Or a core dump?

**Comment by Reasno** [comment]
1) This error happens across all grpc-node versions. 
2)  docker container that runs fine elsewhere would run into this error on this perticular machine

I will try to grab a stacktrace tomorrow.

**Comment by Reasno** [comment]
Managed to solve this. After I turned on ipv6 module in modprobe everything worked.
