### ISSUE TITLE
Should route_guide use sint or float for lat/long?

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#1638]
People use the examples as a view into best practices. Since lat/long would commonly be negative, we should probably use the efficient proto encoding for negative numbers (sint).

Since most people would expect lat/long to be fractional, using float/double may be more clear. But it is also a sample and meant to be simple to a point, so just sticking with an integer could be reasonable.

This was brought to my attention by Kanalia on IRC.

@tbetbetbe

**Comment by wkubiak** [comment]
Thanks for putting this to attention @ejona86 
Kanalia on IRC = me :)
I'm interested as to what other developers think about this issue.

**Comment by yang-g** [comment]
I guess from the quietness on this thread, that people do not feel strongly about it. Closing.
