### ISSUE TITLE
C# tutorial documentation seems to be stale

### ISSUE THREAD

**Issue by Petermarcu** [grpc/grpc#16397]
The examples in the repo (https://github.com/grpc/grpc/tree/master/examples/csharp/Helloworld) have been updated and instructions are pretty simple but the more detailed tutorial doesn't seem to be keeping pace. https://grpc.io/docs/tutorials/basic/csharp.html

One concrete example is that the updated samples say to use the .NET Core 2.0 SDK or higher for the best experience but the tutorial talks about how to use the pre-release 1.0 version of .NET Core.

Opening this to track getting that updated.

**Comment by shadowmint** [comment]
It's worth noting all the commentary about the `packages` folder in the C# tutorial is also out of date; `dotnet restore` does not create this folder, even on windows, and the binaries are not made available for direct use; since `Grpc.Tools` has no c# files, it is not copied into the local folder at all.

**Comment by jtattermusch** [comment]
note to self: 
https://github.com/grpc/grpc.github.io/blame/8c2270f8e08bd2ddb3787d319ca64d0f8e215ace/docs/tutorials/basic/csharp.md#L52  hardcodes `v1.12.x` instead of using `{{ site.data.config.grpc_release_tag }}` - that should also be fixed.

**Comment by jtattermusch** [comment]
A created a PR to fix the issues mentioned: https://github.com/grpc/grpc.github.io/pull/728
It will be merged once the recent changes to the C# examples get propagated to the release branch (that should happen in about two weeks from now).

**Comment by Petermarcu** [comment]
Awesome! One other question. I see everything is netcoreapp1.0 while the current stable version that everyone is using is netcoreapp2.1. Should everything be updated to that?

**Comment by jtattermusch** [comment]
@Petermarcu, I think we should consider have both netcoreapp1.0 and netcoreapp2.0, as having netcoreapp1.0 is a good way to make sure that things work with older .NET core as well. Is there any problem with only having netcoreapp1.0 for now? (it is buildable with .NET Core SDK 2.x just as well).

**Comment by Petermarcu** [comment]
If this is for testing, it makes sense. You definitely want the libraries to work well across a wide spectrum of .NET Core versions. When it comes to examples and templates for people starting fresh, ideally, they would be starting with 2.1. There really isn't much benefit that I can see for people starting with anything less. In fact, 1.0 and 1.1 are going out of support in less than a year while 2.1 has many years left. Thats my primary reason for suggesting that the examples move forward.

**Comment by Falco20019** [comment]
Just wanted to add as a notice, that by default, .NET Core 1.0/1.1 runtimes are not installed with VS2017 anymore. We ran into this when trying to use the examples a month ago before Jan updated them. So I would also propose to have examples always targeting latest runtime and tests oldest supported.
