### ISSUE TITLE
grpc connection failure with bytes instead string field type

### ISSUE THREAD

**Issue by nartes** [grpc/grpc#16400]
### What version of gRPC and what language are you using?
grpc 1.14.1 C++ 
 
 
### What operating system (Linux, Windows, …) and version?
 GNU/Linux (ArchLinux distro), aarch64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Setting ```bytes``` here:
- https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto#L32
- https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto#L37
instead ```string``` gives errors in greeter_client.

When I set ```proto2``` here:
- https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto#L15
as well as set ```required``` for the fields above:
- https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto#L32
- https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto#L37
 It works again.
 
### What did you see instead?

At this line
https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/client_unary_call.h#L73
status contains "Connection failed" as a reason, and it's not ok.
The server side GreeterServiceImpl::SayHello isn't entered at all.
The program `greeter_client` writes to console "Connection failed".

**Comment by sreecha** [comment]
Can you clarify what you mean by 
>> "gives errors in greeter_client." 

What kind of errors?
