### ISSUE TITLE
Long running service timer test fails on 32-bit systems only

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#16417]
The long_running_service_cleanup_test() for timers added in PR #16170 fails only on Windows with no clear cause. It has been disabled from running on Windows until we can figure out why.

**Comment by hcaseyal** [comment]
Seems like it failed on our Windows tests because our windows machines are 32-bit. So this is actually a 32-bit system issue.

**Comment by mhaidrygoog** [comment]
Issue has been address with pull #15813
