### ISSUE TITLE
Python : No address added out of total 1 resolved (grpc)

### ISSUE THREAD

**Issue by mshaheerm** [grpc/grpc#16422]
I am trying to start the server but getting this error..

E0820 15:39:02.561000000 17224 src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc:40] {"created":"@1534772342.561000000","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1534772342.561000000","description":"Failed to add port to server","file":"src/core/lib/iomgr/tcp_server_windows.cc","file_line":509,"referenced_errors":[{"created":"@1534772342.561000000","description":"OS Error","file":"src/core/lib/iomgr/tcp_server_windows.cc","file_line":201,"os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}

What shall i do?

**Comment by mehrdada** [comment]
Can you please share the code snippet causing the trouble?

**Comment by srini100** [comment]
What language are you using?

**Comment by nicolasnoble** [comment]
@srini100: the "Python" part is is the title ;-)

**Comment by nicolasnoble** [comment]
Also, the error is `WSAEADDRINUSE`. Meaning there's already an existing process that's listening on the port you're trying to bind. Please select another port, or stop whichever process is already listening on the port you're trying to bind to.
