### ISSUE TITLE
Build issue: code not portable

### ISSUE THREAD

**Issue by joelfrederico** [grpc/grpc#16428]
### What version of gRPC and what language are you using?
 
Using head, but this issue exists since #15570. This is a build issue, so the language used is not relevant.
 
### What operating system (Linux, Windows, …) and version?

macOS Sierra (10.12.6)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
As far as I can tell, clang.
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Built using Bazel.
 
### What did you expect to see?
 
Successful build.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
An error. This appears to stem from the usage of platform-specific __in6_u. addr6->sin6_addr has type struct in6_addr. This type does not have __in6_u specified on the macOS platform, and actually, isn't part of the IP6 spec of netinet/in.h (see http://pubs.opengroup.org/onlinepubs/000095399/basedefs/netinet/in.h.html). The fix probably involves a memcpy to the types expected, or a cast to the types expected, rather than using platform-specific members that are unions.

ERROR: (redacted)/BUILD:1303:1: C++ compilation of rule '//:lb_server_load_reporting_filter' failed (Exit 1)
src/core/ext/filters/load_reporting/server_load_reporting_filter.cc:167:33: error: no member named '__in6_u' in 'in6_addr'
               addr6->sin6_addr.__in6_u.__u6_addr8[i]);
               ~~~~~~~~~~~~~~~~ ^
1 error generated.

### Anything else we should know about your project / environment?

Not that I can think of.

**Comment by sreecha** [comment]
Making this P1 since its a compilation failure

**Comment by AspirinSJL** [comment]
I'm looking at it.

**Comment by AspirinSJL** [comment]
I'm still installing the tools to reproduce and fix this issue.

This issue is imaginable because currently the server load reporting feature is only built and tested by Bazel, and we only run Bazel tests on Linux.

**Comment by nicolasnoble** [comment]
We could start running Bazel tests on MacOS... @jtattermusch ?

**Comment by jtattermusch** [comment]
@nicolasnoble   sure, we could add a job  that tests bazel C/C++ build on macos. Feel free to send a PR, I will review.
One of the problems is that the kokoro mac workers currently have only  these bazel versions installed:
:0.4.1 0.4.5 0.5.0 0.5.4 0.7.0.  We'd probably need something newer.

**Comment by nicolasnoble** [comment]
Yeah we definitely need something newer...
