### ISSUE TITLE
SSL: Handshake read failed. End of TCP stream

### ISSUE THREAD

**Issue by svishalm** [grpc/grpc#16436]
My grpc client fails to connect to grpc server with handshake read failed error.

Security handshake failed: {"created":"@1533085202.848000000","description":"Handshake read failed","file":"C:\workspace\grpc-1.0.0\vsprojects\..\src\core\lib\security\transport\handshake.c","file_line":237,"referenced_errors":[{"created":"@1533085202.848000000","description":"End of TCP stream","file":"C:\workspace\grpc-1.0.0\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":180}]}

Environment:
gRPC client: 1.0.0 (Cent OS) (C++)
gRPC server: 1.0.0 (Windows 2008R2) (C++)

Tried setting "grpc.initial_reconnect_backoff_ms" to 10000 ms (#8382) but still getting same error. This is happening only with Windows based server. I have servers running RHEL, Ubuntu without any issue.

Any help would be highly appreciated.

**Comment by svishalm** [comment]
@nicolasnoble, won't be able to upgrade in near future.

**Comment by nicolasnoble** [comment]
It's going to be very difficult to diagnose anything in such an old codebase, really. The Windows support especially got rewritten several times.

**Comment by svishalm** [comment]
@nicolasnoble, I can understand that. Do you have any suggestion for me to diagnose this issue?

**Comment by sreecha** [comment]
Unfortunately there isn't enough information from the errors pasted to see what the issue is. Clearly, the 'read' operation from the socket failed on the client side (perhaps the connection was explicitly closed by server or some other error - can't say).

Try turning on grpc traces (flags are here: https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)
set the following env variables

`GRPC_VERBOSITY = DEBUG`
`GRPC_TRACE=all`

**Comment by svishalm** [comment]
@sreecha, I enabled grpc traces and below is the trace from the handshake:

I0823 17:25:16.708373169  148095 grpc_context.c:41]          grpc_census_call_set_context(call=0x325db00, census_context=(nil))
I0823 17:25:16.708468013  148095 call.c:1690]                grpc_call_start_batch(call=0x325db00, ops=0x3277190, nops=3, tag=0x32a82d0, reserved=(nil))
I0823 17:25:16.708485027  148095 call.c:1366]                ops[0]: SEND_INITIAL_METADATA
I0823 17:25:16.708505056  148095 call.c:1366]                ops[1]: SEND_MESSAGE ptr=0x31d6a00
I0823 17:25:16.708523758  148095 call.c:1366]                ops[2]: SEND_CLOSE_FROM_CLIENT
I0823 17:25:16.708582297  148095 client_channel.c:109]       OP[client-channel:0x325e108]: SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 63 6f 68 65 73 69 74 79 2e 6d 61 67 6e 65 74 6f 2e 61 67 65 6e 74 73 2e 73 74 75 62 2e 41 67 65 6e 74 52 70 63 53 65 72 76 69 63 65 2f 47 65 74 41 67 65 6e 74 49 6e 66 6f '/agents.stub.AgentRpcService/GetAgentInfo', key=3a 61 75 74 68 6f 72 69 74 79 ':authority' value=41 67 65 6e 74 20 28 67 52 50 43 20 73 65 72 76 65 72 29 'Agent (gRPC server)', key=67 72 70 63 2d 65 6e 63 6f 64 69 6e 67 'grpc-encoding' value=69 64 65 6e 74 69 74 79 'identity', key=67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding' value=69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip' deadline=2346737.278543174} SEND_MESSAGE:flags=0x00000000:len=6 SEND_TRAILING_METADATA{}
I0823 17:25:16.708798419  148095 call.c:1690]                grpc_call_start_batch(call=0x325db00, ops=0x3277230, nops=3, tag=0x32a8370, reserved=(nil))
I0823 17:25:16.708806780  148095 call.c:1366]                ops[0]: RECV_INITIAL_METADATA ptr=0x32a8398
I0823 17:25:16.708811534  148095 call.c:1366]                ops[1]: RECV_MESSAGE ptr=0x32a83c0
I0823 17:25:16.708816180  148095 call.c:1366]                ops[2]: RECV_STATUS_ON_CLIENT metadata=0x32a83e0 status=0x32a83f8 details=0x32a8400
I0823 17:25:16.708821997  148095 client_channel.c:109]       OP[client-channel:0x325e108]: RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
I0823 17:25:16.708859492  148094 completion_queue.c:333]     grpc_completion_queue_next(cc=0x323c500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
D0823 17:25:16.710726111  148096 connectivity_state.c:92]    CONWATCH: 0x31c3ad8 (null): get IDLE
D0823 17:25:16.710751810  148096 connectivity_state.c:156]   SET: 0x3202748 client_channel: IDLE --> IDLE [new_lb+resolver] error=(nil) null
D0823 17:25:16.710760462  148096 connectivity_state.c:109]   CONWATCH: 0x31c3ad8 (null): from IDLE [cur=IDLE] notify=0x32ca048
D0823 17:25:16.710769521  148096 connectivity_state.c:109]   CONWATCH: 0x32cc0c8 subchannel: from IDLE [cur=IDLE] notify=0x32214b8
D0823 17:25:16.710775949  148096 connectivity_state.c:156]   SET: 0x32cc0c8 subchannel: IDLE --> CONNECTING [state_change] error=(nil) null
D0823 17:25:16.710779095  148096 connectivity_state.c:183]   NOTIFY: 0x32214b8
D0823 17:25:16.710997283  148096 tcp_client_posix.c:305]     CLIENT_CONNECT: ipv4:10.162.85.17:50051: asynchronously connecting
D0823 17:25:16.711015548  148096 connectivity_state.c:156]   SET: 0x31c3ad8 (null): IDLE --> CONNECTING [connecting_changed] error=(nil) null
D0823 17:25:16.711018833  148096 connectivity_state.c:183]   NOTIFY: 0x32ca048
D0823 17:25:16.711022194  148096 connectivity_state.c:109]   CONWATCH: 0x32cc0c8 subchannel: from CONNECTING [cur=CONNECTING] notify=0x32214b8
**D0823 17:25:16.711025449  148096 connectivity_state.c:156]   SET: 0x3202748 client_channel: IDLE --> CONNECTING [lb_changed] error=(nil) null
D0823 17:25:16.711028701  148096 connectivity_state.c:109]   CONWATCH: 0x31c3ad8 (null): from CONNECTING [cur=CONNECTING] notify=0x32ca1c8
D0823 17:25:17.711377133  148094 tcp_client_posix.c:104]     CLIENT_CONNECT: ipv4:10.162.85.17:50051: on_alarm: error=null
D0823 17:25:17.711514209  148094 tcp_client_posix.c:135]     CLIENT_CONNECT: ipv4:10.162.85.17:50051: on_writable: error={"created":"@1535070317.711489409","description":"FD shutdown","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":948}**
D0823 17:25:17.711662548  148094 connectivity_state.c:156]   SET: 0x32cc0c8 subchannel: CONNECTING --> TRANSIENT_FAILURE [connect_failed] error=0x32218b0 {"created":"@1535070317.711592326","description":"Connect Failed","file":"src/core/ext/client_config/subchannel.c","file_line":638,"referenced_errors":[{"created":"@1535070317.711489409","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":948,"os_error":"Timeout occurred","target_address":"ipv4:10.162.85.17:50051"}]}
D0823 17:25:17.711697048  148094 connectivity_state.c:183]   NOTIFY: 0x32214b8
I0823 17:25:17.711705225  148094 subchannel.c:642]           Connect failed: {"created":"@1535070317.711489409","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":948,"os_error":"Timeout occurred","target_address":"ipv4:10.162.85.17:50051"}
**I0823 17:25:17.711711821  148094 subchannel.c:645]           Retry immediately**
D0823 17:25:17.711726961  148094 connectivity_state.c:156]   SET: 0x31c3ad8 (null): CONNECTING --> TRANSIENT_FAILURE [connecting_transient_failure] error=0x32218b0 {"created":"@1535070317.711592326","description":"Connect Failed","file":"src/core/ext/client_config/subchannel.c","file_line":638,"referenced_errors":[{"created":"@1535070317.711489409","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":948,"os_error":"Timeout occurred","target_address":"ipv4:10.162.85.17:50051"}]}
D0823 17:25:17.711732074  148094 connectivity_state.c:183]   NOTIFY: 0x32ca1c8
D0823 17:25:17.711753560  148094 connectivity_state.c:92]    CONWATCH: 0x32cc0c8 subchannel: get TRANSIENT_FAILURE
D0823 17:25:17.711758449  148094 connectivity_state.c:109]   CONWATCH: 0x32cc0c8 subchannel: from TRANSIENT_FAILURE [cur=TRANSIENT_FAILURE] notify=0x32214b8
I0823 17:25:17.711790848  148094 subchannel.c:609]           Failed to connect to channel, retrying
D0823 17:25:17.711797666  148094 connectivity_state.c:156]   SET: 0x32cc0c8 subchannel: TRANSIENT_FAILURE --> CONNECTING [state_change] error=(nil) null
D0823 17:25:17.711800894  148094 connectivity_state.c:183]   NOTIFY: 0x32214b8
D0823 17:25:17.711883032  148094 tcp_client_posix.c:305]     CLIENT_CONNECT: ipv4:10.162.85.17:50051: asynchronously connecting
D0823 17:25:17.711910797  148094 connectivity_state.c:156]   SET: 0x3202748 client_channel: CONNECTING --> TRANSIENT_FAILURE [lb_changed] error=0x32218b0 {"created":"@1535070317.711592326","description":"Connect Failed","file":"src/core/ext/client_config/subchannel.c","file_line":638,"referenced_errors":[{"created":"@1535070317.711489409","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":948,"os_error":"Timeout occurred","target_address":"ipv4:10.162.85.17:50051"}]}

I set "grpc.initial_reconnect_backoff_ms" to 10000 ms but from this traces it seems it retries immediately. 

Here is my code:
`const string host_and_port = host_ + ":" + to_string(port_);
  {
    grpc::SslCredentialsOptions options;
    options.pem_root_certs = agents_keys_certs_ca_cert_pem();
    options.pem_private_key = agents_keys_certs_magneto_key_pem();
    options.pem_cert_chain = agents_keys_certs_magneto_cert_pem();

    grpc::ChannelArguments args;
    args.SetSslTargetNameOverride("Agent (gRPC server)");
    args.SetInt("grpc.initial_reconnect_backoff_ms", 1000 * 10);
    args.SetInt("grpc.max_reconnect_backoff_ms", 1000 * 10);

    channel_ = grpc::CreateCustomChannel(
        host_and_port, grpc::SslCredentials(options), args);
  }
`

**Comment by nicolasnoble** [comment]
.. have you disabled Windows' firewall ? This trace simply states you weren't able to do a simple TCP connect.

**Comment by svishalm** [comment]
Yes, I did disable Windows' firewall.

**Comment by svishalm** [comment]
Looks like found the root cause of this issue. It turns out to be grpc server running on Windows Server leaks network connections. There are thousands of network connections are in CLOSE_WAIT state. Upgrading grpc from 1.0.0 to 1.15.0 helped resolved this issue.
