### ISSUE TITLE
FLAKE: server:server_builder_test@poller=poll-cv

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#16431]
https://source.cloud.google.com/results/invocations/d2eb25f0-642f-4c29-9fa6-851a1dd88543/targets/%2F%2Ftest%2Fcpp%2Fserver:server_builder_test@poller%3Dpoll-cv/tests

```
test/cpp/server/server_builder_test.cc:77
      Expected: ServerBuilder() .RegisterService(&g_service) .AddListeningPort(GetPort(), InsecureServerCredentials()) .AddListeningPort(GetPort(), InsecureServerCredentials()) .AddChannelArgument("grpc.so_reuseport", 0) .BuildAndStart()
      Which is: 8-byte object <10-32 A5-00 00-00 00-00>
To be equal to: nullptr
      Which is: 8-byte object <00-00 00-00 00-00 00-00>
```

**Comment by jtattermusch** [comment]
I didn't find any occurrence of this in the historical data, so our only occurrence is under poll-cv, which was removed in #18298. I think it's safe to close.
