### ISSUE TITLE
Issue with cmake-ing cpp helloworld example on windows

### ISSUE THREAD

**Issue by wneo003** [grpc/grpc#16439]
Configure step fails with:
`CMake Error at C:/dev/grpc/.build/gRPCConfig.cmake:8 (include):
  include could not find load file:

    C:/dev/grpc/.build/gRPCTargets.cmake

Call Stack (most recent call first):
  CMakeLists.txt:73 (find_package)`

**Comment by sreecha** [comment]
Need more information. Can you please add more details on the exact repro steps? (i.e how did you set up, what command did you run and a detailed error message you got?)

**Comment by wneo003** [comment]
I set up by git cloning the folder from the grpc github url: https://github.com/grpc/grpc

I had also installed Protocol Buffers. Then I try to install gRPC c++, this is done by going to the grpc>examples>cpp>helloworld directory, and creating a build folder, then going into that folder and run "cmake -G "Visual Studio 14" .. via commandprompt and this failure message appears.

`-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compiler features
-- Detecting C compiler features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using protobuf
CMake Error at C:/protoc/gRPCConfig.cmake:8 (include):
    include could not find load file:
 
    C:/protoc.gRPCTargets.cmake
Call Stack (most recent call first):
    CMakeLists.txt:73 (find_package)`

**Comment by wneo003** [comment]
Same error as #12442

Any fixes so far?

**Comment by wangyun** [comment]
any fix?

**Comment by wangyun** [comment]
I found the reason, I should build and install grpc first. it's not install by default.

**Comment by wneo003** [comment]
> I found the reason, I should build and install grpc first. it's not install by default.

Hi there, are you able to build and install grpc first by cmake? Because I am facing issue with that as well

**Comment by wangyun** [comment]
@wneo003 please refer to this：
https://github.com/grpc/grpc/issues/13841
and this
https://github.com/grpc/grpc/issues/12384

basicly， you need to build and install your own openssl, zlib library... firstly, not using the submodule version. After that, do cmake to build grpc.

**Comment by Siron777** [comment]
Why is it possible to build a version with all the third parties as submodules if it is not usable once installed ? It is totally confusing.

**Comment by zackgalbreath** [comment]
> @zackgalbreath looks like an improved documentation would help here.

Agreed, we will provide more details about installing with CMake in our updated documentation.

#21411 has also improved this situation for those using CMake 3.13 or newer.
