### ISSUE TITLE
Unable to create executable with googleapis included in .proto file

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#16449]
### What version of gRPC and what language are you using?
 C++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04 in a docker container
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.4.0
 
### What did you do?
Trying to create executable with googleapis annotation.proto included in proto file. I was able to create object files, while creating the executable I get the following error: 
undefined reference to `protobuf google 2fapi 2fannotations_2eproto::Add Descriptors()`
collect2: error: ld returned 1 exit status

### What did you expect to see?
 Expected to have the executable created. 
 
### What did you see instead?
Error:
communicator.pb.o: In function `protobuf_communicator_2eproto::AddDescriptorsImpl()':
communicator.pb.cc:(.text+0xc43): undefined reference to protobuf_google_2fapi_2fannotations_2eproto::AddDescriptors()'
collect2: error: ld returned 1 exit status
`

 
### Anything else we should know about your project / environment?
NA

**Comment by Noctunus** [comment]
I just today ran into the same issue which has been resolved by making sure that the resulting object files are named unique. If you just run over the proto files and generate the .h/.cc files everything is placed in subdirectories. If you know run over the .cc files, compile everything to object files make sure to also consider the directories the files are in as the filenames are *not* unique over the subdirs.
This fixed it for me - hope it helps!

**Comment by jhagmar** [comment]
Yes, like @Noctunus wrote, separate .h and .cpp files for the annotations.proto file are generated. These have to be compiled and linked into the final executable.

**Comment by navono** [comment]
@Noctunus I had the same problem and I don't get your solution, can you explain more? thanks.

**Comment by Noctunus** [comment]
Hey @navono - sure. So the problem for me was, that I simply made a loop over all existing proto files, generated the .cc/.h files into one single folder and tried to compile it. 
That alone is already the problem as the names of the proto-files (and therefore the resulting .cc/.h files are *not* unique) resulting in missing files as they overwrite each other.
So my solution was just to take the whole input directory of the proto files in the loop to generate unique output names for the .cc/.h files. 
Meanwhile I figured out that if you just use a for loop over all proto files (simply with a find) and push them all one-by-one through protoc with --cpp-out / --grpc_out pointing to a single directory it automatically uses the relative directory (or maybe the namespaces?) as subdirectories for the generated files.

**Comment by navono** [comment]
Thank you for your reply @Noctunus . 

After the last comment, I found the solution about the relative way. It's a subtle problem as said in [issue 2005](https://github.com/protocolbuffers/protobuf/issues/2005).

**Comment by sachin-pandit** [comment]
@navona: How did you fix this issue ? I tried following issue-2005, but that was not the case with me. I have single .proto file, and that .proto is importing google/api/annotations.proto

**Comment by navono** [comment]
@sachin-pandit Sorry for the late reply. I can't remember the details. it seems that protoc params need be absolute path as [the issue](https://github.com/protocolbuffers/protobuf/issues/2005) said, you can try it.
