### ISSUE TITLE
The type or namespace name 'GroundTruth' does not exist in the namespace 'Osi3' (are you missing an assembly reference?)	

### ISSUE THREAD

**Issue by mshaheerm** [grpc/grpc#16450]
I tried building the .cs files from the .proto via grpc.. but the file contains many errors which i am unable to resolve.
.proto file is...
![capture](https://user-images.githubusercontent.com/40594242/44577121-8e571100-a790-11e8-97b6-556b0982000e.JPG)

and the erros are..
![capture1](https://user-images.githubusercontent.com/40594242/44577129-9747e280-a790-11e8-9fff-264ae5ceb0d5.JPG)

code is...
![capture2](https://user-images.githubusercontent.com/40594242/44577170-b0e92a00-a790-11e8-8706-660dd2963df1.JPG)

how to resolve them? Thanks in Advance !!

**Comment by nicolasnoble** [comment]
You're not providing enough information. Please share all of your .proto files if you want us to help you - but this is most likely an error you have in your own files.

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/44645502-19761800-a9d8-11e8-9512-4386232be183.JPG)

@nicolasnoble this is the proto file of the groundtruth which the error is being generated of. i am also including the imports but its not helping me out. let me know if anything else is needed.

**Comment by mshaheerm** [comment]
solved.. adding all the .cs to the project.. thank you!!!
