### ISSUE TITLE
[bazel-test-failure]Memory leaks with several ASAN QPS benchmarks

### ISSUE THREAD

**Issue by billfeng327** [grpc/grpc#16471]
See logs below:
All tests with leaks: https://source.cloud.google.com/results/invocations/361eb033-92ac-49e9-be47-c57b687929a3/targets
Details of the leak: https://source.cloud.google.com/results/invocations/361eb033-92ac-49e9-be47-c57b687929a3/targets/%2F%2Ftest%2Fcpp%2Fqps:qps_json_driver_test_1@poller%3Depollex/log

**Comment by adelez** [comment]
Assigning to dgq for initial triage.

**Comment by dgquintas** [comment]
@ncteisen do you own these?

**Comment by jtattermusch** [comment]
Changing to P1 as said tests are failing with 100% rate on master.

**Comment by yashykt** [comment]
Adding some keywords for easy searching -
//test/cpp/qps:qps_json_driver_test_cpp_generic_async_streaming_qps_1channel_1MBmsg_insecure@poller=epollex
qps_json_driver_test

**Comment by ncteisen** [comment]
Due to the heavy weight nature of treating QPS benchmarks as unit tests, we exclude running these under ASAN and TSAN.

See [here](https://github.com/grpc/grpc/blob/ceecf80283e6ca184df587f76ed053f1f5295b7f/test/cpp/qps/gen_build_yaml.py#L105).

I think we should also exclude these for Bazel builds

**Comment by ncteisen** [comment]
@billfeng327, can you take over from here and disable ASAN and TSAN for QPS test?

**Comment by jtattermusch** [comment]
Seems fixed by #16568.
