### ISSUE TITLE
Proto version 2, Objective-C autogen code issue

### ISSUE THREAD

**Issue by gaginan** [grpc/grpc#16474]
### What version of gRPC and what language are you using?
  1.14.1
### What operating system (Linux, Windows, …) and version?
 macOS 10.14 Beta
 
### What did you do?

my proto file:

`syntax = "proto2";

message Packet {
    optional uint32 seq = 1;	
    extensions 0x1000 to max;
}

extend Packet {
    optional ActionReq CMD_ACTION_REQ = 0x10000;
    optional ActionRsp CMD_ACTION_RSP = 0x10001;
}

message ActionReq {
    optional uint32 action_type = 1;
}

message ActionRsp {
    optional uint32 result = 1;	
}

service ActionService {
    rpc CreateAction(Packet) returns (Packet) {}	
}
`
The auto generated code ActionServer.probjc.h. see the DynamicMethods, these class methods **not implemented** in ActionServer.probjc.m 

`
@interface ActionServerRoot : GPBRootObject
@end

@interface ActionServerRoot (DynamicMethods)
+ (GPBExtensionDescriptor *)cmdActionReq;
+ (GPBExtensionDescriptor *)cmdActionRsp;
@end

`

**Comment by muxi** [comment]
gRPC only supports proto3.
