### ISSUE TITLE
build timeout: grpc_interop_toprod

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#16484]
https://source.cloud.google.com/results/invocations/ec9c64f3-c837-4ed8-8c5d-46399609d89d/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

**Comment by hcaseyal** [comment]
I had a similar timeout issue in grpc_interop_tocloud: 
https://source.cloud.google.com/results/invocations/9d9dc476-4abe-455d-a2e6-b4eb42661add/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

2018-09-03 12:48:05,571 TIMEOUT: build_docker_node [pid=11057, time=1800.7sec]
2018-09-03 12:48:05,571 FAILED: Failed to build interop docker images.
stty: standard input: Inappropriate ioctl for device

**Comment by murgatroid99** [comment]
I'm not really sure what needs to change here. The test log just shows docker and git operations, and then the job times out.

**Comment by murgatroid99** [comment]
OK, the second log has the tests running, but I can't tell why it's slow.
