### ISSUE TITLE
Cmake failure

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#16493]
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04
 
### What did you do?
Build grpc using cmake, added grpc as sub_directory to cmakelists. 
 
### What did you expect to see?
 Successful build
 
### What did you see instead?
Build failure
`Building CXX object third-party/grpc/third_party/gflags/CMakeFiles/gflags_static.dir/src/gflags.cc.o
In file included from xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:112:0:
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:147:3: error: #error Need to implement mutex.h for your architecture, or #define NO_THREADS
 #error Need to implement mutex.h for your architecture, or #define NO_THREADS
   ^
In file included from xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:112:0:
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:189:3: error: ‘MutexType’ does not name a type
   MutexType mutex_;
   ^
In file included from xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:113:0:
xxxxx/third-party/grpc/third_party/gflags/src/util.h: In function ‘void google::MakeTmpdir(std::__cxx11::string*)’:
xxxxx/third-party/grpc/third_party/gflags/src/util.h:264:37: error: ‘mkdir’ was not declared in this scope
  int err = mkdir(path->c_str(), 0755);
                                     ^
xxxxx/third-party/grpc/third_party/gflags/src/util.h:267:37: error: ‘mkdir’ was not declared in this scope
   mkdir("/tmp/gflags_unittest", 0755);
                                     ^
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc: In member function ‘std::__cxx11::string google::{anonymous}::FlagValue::ToString() const’:
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:380:44: error: expected ‘)’ before ‘PRIu32’
       snprintf(intbuf, sizeof(intbuf), "%" PRIu32, VALUE_AS(uint32));
                                            ^
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:380:68: warning: spurious trailing ‘%’ in format [-Wformat=]
       snprintf(intbuf, sizeof(intbuf), "%" PRIu32, VALUE_AS(uint32));
                                                                    ^
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:380:68: warning: too many arguments for format [-Wformat-extra-args]
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:380:68: warning: spurious trailing ‘%’ in format [-Wformat=]
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:380:68: warning: too many arguments for format [-Wformat-extra-args]
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:383:67: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘google::int64 {aka long int}’ [-Wformat=]
       snprintf(intbuf, sizeof(intbuf), "%" PRId64, VALUE_AS(int64));
                                                                   ^
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:383:67: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘google::int64 {aka long int}’ [-Wformat=]
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:386:68: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘google::uint64 {aka long unsigned int}’ [-Wformat=]
       snprintf(intbuf, sizeof(intbuf), "%" PRIu64, VALUE_AS(uint64));
                                                                    ^
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:386:68: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘google::uint64 {aka long unsigned int}’ [-Wformat=]
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc: In member function ‘const char* google::{anonymous}::CommandLineFlag::CleanFileName() const’:
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:593:24: error: ‘PATH_SEPARATOR’ was not declared in this scope
     if (*clean_name == PATH_SEPARATOR) {
                        ^
xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:601:26: error: ‘PATH_SEPARATOR’ was not declared in this scope
   while ( *clean_name == PATH_SEPARATOR ) ++clean_name;  // Skip any slashes
                          ^
In file included from xxxxx/third-party/grpc/third_party/gflags/src/gflags.cc:112:0:
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h: At global scope:
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:174:15: warning: inline function ‘void gflags_mutex_namespace::Mutex::Lock()’ used but never defined
   inline void Lock();    // Block if needed until free then acquire exclusively
               ^
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:175:15: warning: inline function ‘void gflags_mutex_namespace::Mutex::Unlock()’ used but never defined
   inline void Unlock();  // Release a lock acquired via Lock()
               ^
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:183:15: warning: inline function ‘void gflags_mutex_namespace::Mutex::ReaderLock()’ used but never defined
   inline void ReaderLock();   // Block until free or shared then acquire a share
               ^
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:184:15: warning: inline function ‘void gflags_mutex_namespace::Mutex::ReaderUnlock()’ used but never defined
   inline void ReaderUnlock(); // Release a read share of this Mutex
               ^
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:164:10: warning: inline function ‘gflags_mutex_namespace::Mutex::Mutex()’ used but never defined
   inline Mutex();
          ^
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:172:10: warning: inline function ‘gflags_mutex_namespace::Mutex::~Mutex()’ used but never defined
   inline ~Mutex();
          ^
xxxxx/third-party/grpc/third_party/gflags/src/mutex.h:169:10: warning: inline function ‘gflags_mutex_namespace::Mutex::Mutex(gflags_mutex_namespace::Mutex::LinkerInitialized)’ used but never defined
   inline Mutex(LinkerInitialized);
          ^
third-party/grpc/third_party/gflags/CMakeFiles/gflags_static.dir/build.make:62: recipe for target 'third-party/grpc/third_party/gflags/CMakeFiles/gflags_static.dir/src/gflags.cc.o' failed
make[2]: *** [third-party/grpc/third_party/gflags/CMakeFiles/gflags_static.dir/src/gflags.cc.o] Error 1
CMakeFiles/Makefile2:5814: recipe for target 'third-party/grpc/third_party/gflags/CMakeFiles/gflags_static.dir/all' failed
make[1]: *** [third-party/grpc/third_party/gflags/CMakeFiles/gflags_static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by jtattermusch** [comment]
Not sure if there's an actual bug (we do have a distribtest that's passing), but perhaps we should take a look at the error and see if our documentation can be improved to avoid problems like this.

The distribtest that uses grpc via `add_subdirectory()`
https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake_as_submodule.sh

**Comment by zackgalbreath** [comment]
Take a look at the following gist:

https://gist.github.com/zackgalbreath/73c9bacbebaa9d54db69b56535390da6

It uses [CMake's FetchContent module](https://cmake.org/cmake/help/latest/module/FetchContent.html) to clone grpc at configure time. It then build's grpc using `add_subdirectory` and uses the resulting libraries to create the helloworld example. This works without error for me on Ubuntu 18.04 (bionic).

**Comment by jtattermusch** [comment]
@zackgalbreath  @KyleFromKitware  I'm unable to tell what is it that the user did wrong to get the error listed above (seems like badly misconfigured build), but if you know, let's keep this in mind when improving the "how to use" docs.

I'm going to close this issue for now.
