### ISSUE TITLE
Create a Windows iomgr suitable for the callback-based API

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#16505]
### What version of gRPC and what language are you using?

master, C++ 
 
### What operating system (Linux, Windows, …) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A
 
### What did you do?

Used the gRPC C++ API
 
### What did you expect to see?
 
A Windows iomgr suitable for running the callback-based API
 
### What did you see instead?
 
Not sure

**Comment by hdnn** [comment]
@guantaol can I ask you about this issue status? Maybe there is information about the planned completion date? Looking forward to the release with this issue to start working with callback API)

**Comment by jtattermusch** [comment]
@guantaol  can you provide and update or close?

**Comment by markdroth** [comment]
Closing as a duplicate of #16504.
