### ISSUE TITLE
Implement libuv-based EventManager

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#16504]
### What version of gRPC and what language are you using?

master, C++ 
 
### What operating system (Linux, Windows, …) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A
 
### What did you do?

Used the gRPC C++ API
 
### What did you expect to see?
 
An iomgr implementation for Mac and Linux platforms that can support the callback-based API by using a dedicated threadpool
 
### What did you see instead?
 
iomgr implementations that don't have a threadpool for servicing callback-based RPCs, limiting the callback-based API to inproc transport usage

**Comment by jtattermusch** [comment]
@guantaol can you provide and update or close?

**Comment by markdroth** [comment]
Renaming to reflect current plan.

**Comment by guantaol** [comment]
The implementation is almost done but we are currently blocked by the build support for libuv in the grpc repo #22030

**Comment by clarkzinzow** [comment]
What's the current status of this? It looks like that PR was closed.

**Comment by drfloob** [comment]
This specific work is discontinued, but there are other efforts working to support the Callback API. I see you've already found this other thread, but for anyone else who lands here looking for updates, #25169 recently enabled the C++ Callback API for all platforms.
