### ISSUE TITLE
IOmgr objects are leaking on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1650]
Recently (I think after #1563) I started seeing messages like this upon grpc_shutdown in C# on Windows:

D5/18/2015 6:51:54 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:114: Waiting for 8 iomgr objects to be destroyed
D5/18/2015 6:52:04 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:137: Failed to free 8 iomgr objects before shutdown deadline: memory leaks are likely
D5/18/2015 6:52:04 PM 124669648 c:\users\jtattermusch\github\grpc\src\core\iomgr\iocp_windows.c:130: iocp_loop is done

**Comment by jtattermusch** [comment]
I can easily replicate this by just running GreeterClient against GreeterServer or MathClient against MathServer
The client finishes with message "Failed to free 1 iomgr object" 100% of time. I checked GRPC_TRACE=surface,batch output and everything looks like it should.

@nicolasnoble, any ideas here?

**Comment by jtattermusch** [comment]
@a11r  FYI this is potentially a release blocker, let's sync up on this one

**Comment by jtattermusch** [comment]
Update on this after labelling iomgr objects was introduced:
D6/4/2015 1:51:22 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:120: Waiting for 6 iomgr objects to be destroyed
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:145: Failed to free 6 iomgr objects before shutdown deadline: memory leaks are likely
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:150: LEAKED OBJECT: client
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:150: LEAKED OBJECT: server
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:150: LEAKED OBJECT: client
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:150: LEAKED OBJECT: server
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:150: LEAKED OBJECT: client
D6/4/2015 1:51:32 PM 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:150: LEAKED OBJECT: server
D6/4/2015 1:51:32 PM 114011240 c:\users\jtattermusch\github\grpc\src\core\iomgr\iocp_windows.c:130: iocp_loop is done

**Comment by ctiller** [comment]
Someone should probably make the labels more descriptive :)

**Comment by Zerqkboo** [comment]
The bug seems to be still there on windows.

**Comment by jtattermusch** [comment]
#2416 fixed this.

**Comment by jtattermusch** [comment]
The 0.6.1 version of Grpc nuget packages was published and it contains the fix (an some related windows stabillity fixes).
