### ISSUE TITLE
How can I connect electron grpc client to nodejs grpc server?

### ISSUE THREAD

**Issue by zhaozhongyu** [grpc/grpc#16531]
### What version of gRPC and what language are you using?
 grpc: 1.14.1
nodejs: 10.6.0
electron: 1.8.4
 
### What operating system (Linux, Windows, …) and version?
 windows 7 sp1
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I have a nodejs grpc server running in my localhost, and when i try to invoke it using my grpc client startup with electron, it happened throw a error: Error: 14 UNAVAILABLE: Connect Failed

### What did you expect to see?
 can i connect  electron grpc client to nodejs grpc server?
 
### What did you see instead?
it happened throw a error: Error: 14 UNAVAILABLE: Connect Failed
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
 i can connect nodejs grpc client to nodejs grpc server and it works, and the same code in electron it goes wrong, what happen?

**Comment by nicolasnoble** [comment]
It should work, but you're not really providing nearly enough information. Can you share reproduction code? Logs? What have you attempted to solve the issue yourself?

**Comment by zhaozhongyu** [comment]
my proto file is like this 
```
syntax = "proto3";

package testPackage;

service testService { rpc ping (pingRequest) returns (pingReply) {} }

message pingRequest { }

message pingReply { string message = 1; }
```

and my server.js 
```
const grpc = require('grpc')

const PROTO_PATH = __dirname + '../protos/test.proto' 
const testProto = grpc.load(PROTO_PATH).testPackage

function test(call, callback) { callback(null, {message: 'Pong'}) }

const server = new grpc.Server();
server.addProtoService(testProto.testService.service, {test: ping}) 
server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure()) 
server.start()
```

in my electron index.js i start a client try to connect server, client is written in different project with server and i install by `npm install grpc --save --runtime=electron --target=1.8.4`. it looks like this: 
```
const grpc = require('grpc')

const PROTO_PATH = __dirname + '../protos/test.proto' 
const testProto = grpc.load(PROTO_PATH).testPackage

const client = new testProto.testService('0.0.0.0:50051', grpc.credentials.createInsecure());

client.ping({}, function(err, response) { console.log('ping -> :', response.message); });
```

Then i startup server, and 10 seconds later i start client, it throw a error said `Error: 14 UNAVAILABLE: Connect Failed`. So i try to run the same client code in nodejs environment and it works well. 

And when i try to connect an electron grpc client and server, it does not work, but electron grpc server and nodejs grpc client can work.

**Comment by zhaozhongyu** [comment]
I got it, in electron client, i should use the address '127.0.0.1:50051' instead of '0.0.0.0:50051', there is something wrong in connecting '0.0.0.0:50051'.

**Comment by nicolasnoble** [comment]
0.0.0.0 isn't a valid address to connect to to begin with.
