### ISSUE TITLE
Add equality testing support to C# ChannelOption

### ISSUE THREAD

**Issue by evildour** [grpc/grpc#16533]
### What version of gRPC and what language are you using?
C# - 1.14.1

 
### What did you do?
Tried to compare two `ChannelOption` instances to see if they had the same type and underlying value.
 
### What did you expect to see?
`Equals` and `GetHashCode` overrides defined on `ChannelOption`
 
### What did you see instead?
No support for comparing channel options. Testing manually is awkward because there's no way to get the underlying value as an object, so testing logic needs to be switched based on type.
 
### Anything else we should know about your project / environment?
Implementing `IEquatable<ChannelOption>` would also be good.

cc @jskeet

**Comment by jtattermusch** [comment]
this will be in the upcoming v1.16.0 release
