### ISSUE TITLE
gcc-4.4 Travis test is not actually using gcc-4.4

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#1653]
Hello there,
I am convinced that the gcc-4.4 test is not actually using gcc-4.4 . @dgquintas  recently pushed code that has range-based for loops (PR #1649 ) , and the Travis build actually passed. There was no actual compilation done in that Travis build. gcc did not support range-based for until version 4.6 .
There is a problem here.

**Comment by vjpai** [comment]
Ok, not a P0, but not a feature request either. Something in between.

**Comment by ctiller** [comment]
Throwing a help wanted on this and unassigning it from myself just to be clear that I don't think I'll get a chance to touch this promptly.

**Comment by ctiller** [comment]
Stale
