### ISSUE TITLE
Couldn't find any implementation related to hellostreamingworld.proto C++

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#16538]
### What did you do?
I am trying to run a c++ client with proto similar to hellostreamingworld.proto, I am streaming from the server but unable to keep client connection alive after one response from server. Wanted to have some example which will guide how to implement it. 
 
### What did you expect to see?
 Implemetation of hellostreamingworld.proto

**Comment by ncteisen** [comment]
There is no C++ impl for helloworld streaming.

Check out the route guide example: https://github.com/grpc/grpc/tree/master/examples/cpp/route_guide

**Comment by lucifercr07** [comment]
@ncteisen have checked the route_guide example. There is no async implemetation as there is for hello.proto

**Comment by ncteisen** [comment]
Ahh I see, you would like to see async streaming example. In that case the best guide will be our QPS driver benchmarking application.

Take a look at the async streaming server: https://github.com/grpc/grpc/blob/master/test/cpp/qps/server_async.cc#L305

and the async streaming client: https://github.com/grpc/grpc/blob/master/test/cpp/qps/client_async.cc#L336

**Comment by lucifercr07** [comment]
@ncteisen Thanks for pointing out!!!
