### ISSUE TITLE
Unused parameter in C++ generated code

### ISSUE THREAD

**Issue by rojer** [grpc/grpc#16542]
### What version of gRPC and what language are you using?

master 
 
### What operating system (Linux, Windows, …) and version?

linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

clang 6.0.0 
 
### What did you do?

define a streaming method, try compiling C++ code with `-Wextra`
 
### What did you expect to see?

code compiles 
 
### What did you see instead?
 
```
./port_fwd_service.grpc.pb.h:90:48: error: unused parameter 'context' [-Werror,-Wunused-parameter]
    ::grpc::Status Conn(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::dw::PortFwdFrame, ::dw::PortFwdFrame>* stream) final override {
```
 
### Anything else we should know about your project / environment?

---

C++ code generated for streaming methods contains functions with unused arguments that trip up compilcation with `-Wunused-parameter` (part of `-Wextra`).
In particular, the issue is with the stubs for synchronous versions of methods generated [here](https://github.com/grpc/grpc/blob/b0aa05b73471724dc367213225fc26d27a3ac343/src/compiler/cpp_generator.cc#L669) and in a few other places - `context` and `stream` end up unused. 

This is similar to https://github.com/grpc/grpc/issues/6518 but ina different place.

A simple C++ compile test with `-Wextra` would catch this.

**Comment by rojer** [comment]
hm. i don't see any added _complexity_, per se - just throw a bunch of `(void) arg1;` at the end.
it will increase the size, sure, but not complexity.
since this particular is in the generated header, it effectively prevents use of `-Wunused-parameter` on the entire project (if it only applied to c code i could've isolated it by applying only to generated sources).
so please, if you don't plan to address it systematically, at least fix this particular instance for now.

**Comment by jlisee** [comment]
This is also effecting a project I am working on and it's not really possible to generated files from the gRPC compiler.  Right now we are doing:

```
```

**Comment by chrisse42** [comment]
Hi there,

i'd like to suggest a simple solution for this class of problems with the generated code.

As far as i can read the code, the problem stems from disabled methods like in:

https://github.com/grpc/grpc/blob/master/src/compiler/cpp_generator.cc : line 792
```
  if (method->NoStreaming()) {
    printer->Print(
        *vars,
        "// disable synchronous version of this method\n"
        "::grpc::Status $Method$("
        "::grpc::ServerContext* context, const $Request$* request, "
        "$Response$* response) override {\n"
        "  abort();\n"
        "  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, \"\");\n"
        "}\n");
```

The compiler warns us, that we didnt use "context", "request" and "response" - understandable, but we dont want to change the method-signature and dont want to forget the variable name. 

So we change the code by hiding the varable-names from the compiler (using comments /* and */):

```
  if (method->NoStreaming()) {
    printer->Print(
        *vars,
        "// disable synchronous version of this method\n"
        "::grpc::Status $Method$("
        "::grpc::ServerContext* /*context*/, const $Request$* /*request*/, "
        "$Response$* /*response*/) override {\n"
        "  abort();\n"
        "  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, \"\");\n"
        "}\n");
```

This leads to the compiler not complaining (no warning anymore), the signature remains the same and the readability does not suffer.

As my company would like to change the existing communication infrastructure to grpc and we have a strict no-warning policy, i would offer to adapt the code in this way...

Is my reasoning correct?

Would you possibly accept merge requests?

Regards,
Christian

**Comment by chrisse74** [comment]
This should be closed, as it is already fixed at the master branch...
