### ISSUE TITLE
Allow servers to accept unknown client certificates

### ISSUE THREAD

**Issue by max-tet** [grpc/grpc#16547]
For a peer2peer application, I need servers to require client authentication via certificate (chain) but accept them even if they are unknown.

Instead the server would save the root certificate (via `context.auth_context()` in order to recognize when the same client comes back later. This would be implemented as part of the application.

For this to work, it should be possible to create server credentials like this (python example): 
`grpc.ssl_server_credentials(((server_key, server_cert_chain),), require_client_auth=True)`. Currently, this would not work, because no `root_certificates` were provided.

As an additional requirement (perhaps for a separate issue?),  `context.auth_context()` should give access to the whole certificate chain of the client, instead of only the certificate at the end of the chain.

**Comment by nicolasnoble** [comment]
All of the code is there to support all this in the core, but may not have been exposed to the API of the language you're interested in. Which are they?

**Comment by max-tet** [comment]
Mainly Python. Perhaps later Java.

**Comment by jtattermusch** [comment]
FYI a similar request exists for C#: https://github.com/grpc/grpc/issues/14381
