### ISSUE TITLE
Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Trying to connect an http1.x server)>

### ISSUE THREAD

**Issue by sj1703** [grpc/grpc#16551]
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by mehrdada** [comment]
You are probably connecting to an HTTP1 server or proxy that is not responding in HTTP2. I don't know how to further help with the information provided, so I am closing the issue.
