### ISSUE TITLE
ruby package build on linux is flaky: build_package.ruby_package

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16555]
Kokoro job `grpc/core/master/linux/grpc_build_packages`:
https://source.cloud.google.com/results/invocations/4b8eaa5e-a2e5-4938-87f6-ee2224ec8406/targets/github%2Fgrpc/tests
https://source.cloud.google.com/results/invocations/8cbc3596-0d9e-4f35-bfee-8b1e9f6838d4/targets/github%2Fgrpc/tests
https://source.cloud.google.com/results/invocations/e37036aa-2e7c-4555-9444-ce540eb42d3d/targets/github%2Fgrpc/tests

It looks like it might be failing when copying over the protoc artifacts, which seem to be missing:
```
+ cp /var/local/git/grpc/third_party/protobuf/src/google/protobuf/wrappers.proto /var/local/git/grpc/src/ruby/tools/bin/x86-windows/google/protobuf/wrappers.proto
+ for plat in '{windows,linux,macos}'
+ input_dir=/var/local/jenkins/grpc/input_artifacts/protoc_linux_x86
+ output_dir=/var/local/git/grpc/src/ruby/tools/bin/x86-linux
+ mkdir -p /var/local/git/grpc/src/ruby/tools/bin/x86-linux/google/protobuf
+ mkdir -p /var/local/git/grpc/src/ruby/tools/bin/x86-linux/google/protobuf/compiler
+ cp '/var/local/jenkins/grpc/input_artifacts/protoc_linux_x86/protoc*' '/var/local/jenkins/grpc/input_artifacts/protoc_linux_x86/grpc_ruby_plugin*' /var/local/git/grpc/src/ruby/tools/bin/x86-linux/
cp: cannot stat '/var/local/jenkins/grpc/input_artifacts/protoc_linux_x86/protoc*': No such file or directory
cp: cannot stat '/var/local/jenkins/grpc/input_artifacts/protoc_linux_x86/grpc_ruby_plugin*': No such file or directory
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc/artifacts
+ docker cp build_and_run_docker_95a5563b-3294-48d4-b3e3-b97c830d638f:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
+ docker rm -f build_and_run_docker_95a5563b-3294-48d4-b3e3-b97c830d638f
build_and_run_docker_95a5563b-3294-48d4-b3e3-b97c830d638f
+ '[' true '!=' '' ']'
+ exit 1
```
Not sure if this is the problem in our scripts or in kokoro.

**Comment by jtattermusch** [comment]
For build_packages build  https://source.cloud.google.com/results/invocations/4b8eaa5e-a2e5-4938-87f6-ee2224ec8406/details I looked up the corresponding build_artifacts build:

https://source.cloud.google.com/results/invocations/6874bd94-d89d-415c-8a7a-fd8a41f0c3ee/details (the artifacts are here: 
https://pantheon.corp.google.com/storage/browser/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/linux/grpc_build_artifacts/2284/20180903-172919/github/grpc/artifacts/protoc_linux_x86/)   and it looks like the artifacts are there - that might mean that there's a problem with kokoro copying over those artifacts to the build_packages job.

**Comment by jtattermusch** [comment]
Filed internal b/113865501

**Comment by SophisticaSean** [comment]
I can't get any ruby code generated on alpine linux because of this issue, there's no executables in the grpc-tools gem for linux...

What's the ETA on a fix?

**Comment by apolcyn** [comment]
@SophisticaSean how do you mean that there are no executables in the grpc-tools gem for linux? I don't see that this is the case.

E.g., gem unpack on the latest `grpc-tools-1.14.2.gem` and `grpc-tools-1.15.0.gem` packages shows, among other things:

```
...
./grpc-tools-1.15.0/bin/x86_64-linux/protoc
./grpc-tools-1.15.0/bin/x86_64-linux/grpc_ruby_plugin
...
./grpc-tools-1.15.0/bin/x86-linux/protoc
./grpc-tools-1.15.0/bin/x86-linux/grpc_ruby_plugin
...
```

**Comment by SophisticaSean** [comment]
@apolcyn so while some sort of reference shows up for those items they are not executable. 

I get this error when I try to use those files: 
```
/usr/lib/ruby/gems/2.4.0/gems/grpc-tools-1.15.0/bin/grpc_tools_ruby_protoc:33:in `exec': No such file or directory - /usr/lib/ruby/gems/2.4.0/gems/grpc-tools-1.15.0/bin/x86_64-linux/protoc (Errno::ENOENT)
	from /usr/lib/ruby/gems/2.4.0/gems/grpc-tools-1.15.0/bin/grpc_tools_ruby_protoc:33:in `<top (required)>'
	from /usr/bin/grpc_tools_ruby_protoc:23:in `load'
	from /usr/bin/grpc_tools_ruby_protoc:23:in `<main>'
```

**Comment by apolcyn** [comment]
@SophisticaSean is what you're seeing a regression? That is, did this used to work for you on your platform with older versions of the `grpc-tools` package, but now it doesn't?

It it is a regression, I'm wondering what version introduced the regression. If it's not a regression, then I suspect this never worked, and that the problem lies in how we some up with the expected directory name of the protoc executables https://github.com/grpc/grpc/blob/master/src/ruby/tools/platform_check.rb#L21

**Comment by SophisticaSean** [comment]
@apolcyn This is the first time I've tried to generate protobuf for ruby on linux. The gem works great on OSX. I went back to gem 1.10.0 and it still doesn't work. 

I rand `ldd` against it and it said: 
```
bash-4.4# ldd /usr/lib/ruby/gems/2.4.0/gems/grpc-tools-1.10.0/bin/x86_64-linux/protoc
	/lib64/ld-linux-x86-64.so.2 (0x7fe99f172000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe99f172000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe99f172000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe99f172000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/lib/ruby/gems/2.4.0/gems/grpc-tools-1.10.0/bin/x86_64-linux/protoc)
```

so i installed `apk add libc6-compat` and now I'm getting a seg fault: 
```
./bin/gen-ruby.sh: line 4:  7230 Segmentation fault      grpc_tools_ruby_protoc -I . --proto_path ${GOPATH}/src --ruby_out="../ruby-proto/lib" --grpc_out="../ruby-proto/lib" $newJ/*.proto
```

**Comment by apolcyn** [comment]
@SophisticaSean not sure about the root cause, but I think this problem is specific to Alpine linux

**Comment by SophisticaSean** [comment]
@apolcyn Yeah it seems alpine specific. I got this working on the latest docker image of Ubuntu 18.04. Would be awesome if we could get it working on Alpine, but I can make do for now.

**Comment by apolcyn** [comment]
@SophisticaSean just to note, unfortunately `grpc-tools` support for Alpine will be a low priority
