### ISSUE TITLE
Cannot start server and client in virtual environment

### ISSUE THREAD

**Issue by marcosfelt** [grpc/grpc#16559]
### What version of gRPC and what language are you using?
Python with gRPC ver 1.14.2
 
### What operating system (Linux, Windows, …) and version?
 Mac OS 10.13.6 (High Sierra)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python version
 
### What did you do?
I am trying to run the helloworld example. I used pipenv to install  grpcio, grpcio-tools and googleapis-common-protos. I compiled the stubs on my machine by running `python -m grpc_tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/helloworld.proto` inside the virtualenv.

I was able to start the server successfully.  However, when I switch to a different terminal and start the [client](https://github.com/grpc/grpc/blob/v1.14.1/examples/python/helloworld/greeter_client.py), I get the following error: 
````
 File "greeter_client.py", line 3, in <module>
    import grpc
  File "/Users/Kobi/.local/share/virtualenvs/grpc_test-z23tqVo_/lib/python3.6/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: dlopen(/Users/Kobi/.local/share/virtualenvs/grpc_test-z23tqVo_/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-darwin.so, 2): Symbol not found: _deflate
  Referenced from: /Users/Kobi/.local/share/virtualenvs/grpc_test-z23tqVo_/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/Kobi/.local/share/virtualenvs/grpc_test-z23tqVo_/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-darwin.so
````
 
### What did you expect to see?
I expected the client to connect to the server.

 
### What did you see instead?
See above.   I am thinking it has to do with the virtual environment and the cython namespace.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by nicolasnoble** [comment]
@mehrdada isn't this the anaconda issue ?

**Comment by mehrdada** [comment]
@marcosfelt Are you using Anaconda to install Python? If true, while we don't officially test on Anaconda, users have reported similar issues and apparently it was resolved by trying `conda install grpcio` instead of `pip install grpcio`

**Comment by marcosfelt** [comment]
Okay, I will give it a try. I sorted the issue out by switching to the
default python version (instead of anaconda).

**Comment by lidalei** [comment]
@marcosfelt Try this https://github.com/grpc/grpc/issues/15510#issuecomment-404459720
