### ISSUE TITLE
Limit the max number of executor threads based on ENV variable

### ISSUE THREAD

**Issue by yfinkelstein** [grpc/grpc#16557]
### What version of gRPC and what language are you using?
A new feature request 
 
### What operating system (Linux, Windows, …) and version?
All
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
All
 
### What did you do?
Under high IO load, GPRC spawns executor threads up to max which is computed to be ```2*sched_getcpu()``` on linux.
 
### What did you expect to see?
I want to limit this number explicitly via an optional ENV variable. 

### What did you see instead?
If a Linux OS sees 64 cores, each container will have up to 128 executor threads. 
 
This poses a problem for container-based gprc app deployments in some cases. Each container believes its concurrency is only limited by the number of physical cores in the system (the fact that sched_getcpu() reflects a smaller number in cases a cgroup policy pins the app to specific cores is of little help here - it's not practical to specify explicit core pinning in cloud environments running on bare metal machines). It's needless to say that excessive number of threads results in degraded system performance and higher memory usage due to each thread getting a stack (ex 1MB* 100 is not to be ignored)
 
The following patch illustrates what needs to be done:
```
--- executor.cc	2018-09-02 18:28:05.000000000 -0700
+++ grpc-1.14.1/src/core/lib/iomgr/executor.cc	2018-09-02 19:33:23.000000000 -0700
@@ -45,9 +45,24 @@
 GPR_TLS_DECL(g_this_thread_state);
 
 GrpcExecutor::GrpcExecutor(const char* executor_name) : name_(executor_name) {
+  static const char* prefix = "MAX_THREADS_";  
   adding_thread_lock_ = GPR_SPINLOCK_STATIC_INITIALIZER;
   gpr_atm_no_barrier_store(&num_threads_, 0);
-  max_threads_ = GPR_MAX(1, 2 * gpr_cpu_num_cores());
+  max_threads_ = 0;
+  char* env = (char*)alloca(strlen(prefix) + strlen(executor_name) + 1);
+  sprintf(env, "%s%s", prefix, executor_name);
+  char *current_pos = strchr(env,'-');
+  while (current_pos){
+      *current_pos = '_';
+      current_pos = strchr(current_pos,'-');
+  }  
+  char* mt = getenv(env);
+  if (mt != NULL) max_threads_ = atoi(mt);
+  if (max_threads_ == 0) {
+    max_threads_ = GPR_MAX(1, 2 * gpr_cpu_num_cores());
+    printf("GRPC Executor's %s max_threads is computed to be %d\n", executor_name, max_threads_);
+  }
+  else printf("GRPC Executor's %s max_threads overwritten by env variable to be %d\n", executor_name, max_threads_);
 }
 
 void GrpcExecutor::Init() { SetThreading(true); }
```

**Comment by vadimskipin** [comment]
I really think it is a BUG actually. You are absolutely right there should be configurable limit for number of threads. But code needs to be fixed to not spawn so many threads at first.

I ran into this issue as well after grpc upgrade from 1.1.4 (no additional grpc_executor threads) to 1.12.0 (112 dummy threads on my 56-core box).

As I can understand it is something related to the usage of grpc_executor_scheduler(GRPC_EXECUTOR_LONG) in the TCP code (see CoverSelf).

**Comment by vadimskipin** [comment]
It would be really nice if somebody would describe the ideas behind these commits:
https://github.com/grpc/grpc/commit/8ef68a570faebde6c79b80b3922a121f0540f342
https://github.com/grpc/grpc/commit/7a82afde1e1705168e482bbbc427b1ee5840bee3
