### ISSUE TITLE
got duplicate symbols errors when build with libgrpc_cronet.a and libgrpc++_cronet.a

### ISSUE THREAD

**Issue by mqingli** [grpc/grpc#16569]
### What version of gRPC and what language are you using?
 v1.11.0 C++
 
### What operating system (Linux, Windows, …) and version?
 MACOS Darwin Kernel Version 17.7.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc Apple LLVM version 9.1.0 (clang-902.0.39.2)

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

We try to build a C++ library that links with libgrpc_cronet.a and libgrpc++_cronet.a to support gRPC cronet 
 
### What did you expect to see?
 build success.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

We got many duplicate symbols errors like: multiple definition of grpc_avl_add in both libgrpc_cronet.a and libgrpc++_cronet.a libraries. We checked CMakeLists.txt in grpc, many source files are included in both libgrpc_cronet and libgrpc++_cronet libraries.

**Comment by sheldonneuberger** [comment]
This looks like a similar issue to these:  https://github.com/grpc/grpc/pull/11247 and https://github.com/grpc/grpc/pull/11097

**Comment by muxi** [comment]
gRPC+Cronet is not officially released. Particularly, Cronet does not support pure C++ until very recently; they can only be used with ObjC for now. Please use the version without Cronet. I'm gonna add some comment to avoid further confusion on this.
