### ISSUE TITLE
Getting Pre-built binaries not found for grpc@0.14.1 and node@8.11.4

### ISSUE THREAD

**Issue by ils-sapnaj** [grpc/grpc#16565]
I am getting following error during npm install  on my windows 10 system.

> @newrelic/native-metrics@2.4.0 install D:\XXXXXXX\node_modules\@newrelic\native-metrics
> node ./lib/pre-build.js install native_metrics

> C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean configure
> C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build -j 2 /t:native_metrics
  native_metrics.cpp
  GCBinder.cpp
  LoopChecker.cpp
  RUsageMeter.cpp
..\src\GCBinder.cpp(47): warning C4996: 'Nan::MakeCallback': was declared deprecated [D:\XXXXXXX\node_modules\@newrelic\native-metrics\build\native_metrics.vcxproj]
  D:\XXXXXXX\node_modules\nan\nan.h(979): note: see declaration of 'Nan::MakeCallback'
  win_delay_load_hook.cc
     Creating library D:\XXXXXXX\node_modules\@newrelic\native-metrics\build\Release\native_metrics.lib and object D:\XXXXXXX\node_modules\@newrelic\native-metrics\build\Release\native_metrics.exp
  Generating code
  Finished generating code
  native_metrics.vcxproj -> D:\XXXXXX\node_modules\@newrelic\native-metrics\build\Release\\native_metrics.node
  native_metrics.vcxproj -> D:\XXXXXXX\node_modules\@newrelic\native-metrics\build\Release\native_metrics.pdb (Full PDB)
install successful: _newrelic_native_metrics-2_4_0-native_metrics-57-win32-x64

> fibers@2.0.0 install D:\XXXXXXX\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-57` exists; testing
Binary is fine; exiting

> grpc@0.14.1 install D:\XXXXXXX\node_modules\gcloud\node_modules\grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'D:\\XXXXXXX\\node_modules\\gcloud\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@8.11.4 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "D:\XXXXXXX\node_modules\gcloud\node_modules\grpc\src\node\extension_binary\grpc_node.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.14.1/node-v57-win32-x64.tar.gz
node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.14.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.14.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@0.14.1 and node@8.11.4 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.14.1/node-v57-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  WINDOWS_BUILD_WARNING
  "..\IMPORTANT: Due to https:\github.com\nod
https://github.com/nodejs\node\issues\4932, to build this library on Windows, you must first remove C:\Users\dell\.node-gyp\8.11.4\include\node\openssl"
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  WINDOWS_BUILD_WARNING.vcxproj -> D:\XXXXXX\node_modules\gcloud\node_modules\grpc\build\Release\\WINDOWS_BUILD_WARNING.node
  WINDOWS_BUILD_WARNING.vcxproj -> D:\XXXXXXX\node_modules\gcloud\node_modules\grpc\build\Release\WINDOWS_BUILD_WARNING.pdb (Full PDB)
  err_data.c
  aes.c
  mode_wrappers.c
  a_bitstr.c
C:\Users\dell\.node-gyp\8.11.4\include\node\openssl/e_os2.h(276): warning C4005: 'OPENSSL_EXPORT': macro redefinition (compiling source file ..\src\boringssl\err_data.c) [D:\XXXXXXX\node_modules\gcloud\node_modules\grpc\build\boringss
l.vcxproj]

At the end, I am getting following output : 

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\XXXXXX\\node_modules\\gcloud\\node_modules\\grpc\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=D:\\XXXXXX\\node_modules\\gcloud\\node_modules\\grpc\\src\\node\\extension_binary"
gyp ERR! cwd D:\XXXXXX\node_modules\gcloud\node_modules\grpc
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\XXXXXX\node_modules\gcloud\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=D:\XXXXXX\node_modules\gcloud\node_modules\grpc\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\XXXXXX\node_modules\gcloud\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\XXXXXX\\node_modules\\gcloud\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\XXXXXX\node_modules\gcloud\node_modules\grpc
node-pre-gyp ERR! node -v v8.11.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\XXXXXX\node_modules\gcloud\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=D:\XXXXXX\node_modules\gcloud\node_modules\grpc\src\node\extension_binary' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@0.14.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.14.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2018-09-05T13_55_24_424Z-debug.log

I have tried all the possible solutions mentioned over different tickets and groups but still, the problem is same. Can somebody help me to come out of this issue ???

Node version : 8.11.4
NPM version : 5.6.0

**Comment by nicolasnoble** [comment]
gRPC 0.14.1 is a horribly old version, and it didn't support node 8 at the time. Either downgrade node to 6 or even 4, or upgrade grpc to a much recent version.

**Comment by nicolasnoble** [comment]
Also, you're using the "gcloud" package, which is deprecated. See https://www.npmjs.com/package/gcloud for migration options.
