### ISSUE TITLE
how to use AsyncQpsServerTest?

### ISSUE THREAD

**Issue by hanyaqian** [grpc/grpc#16563]
how to use AsyncQpsServerTest defined in [code](https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/test/cpp/qps/server_async.cc)
@hassox @timburks @tenderlove @proppy 

thanks

**Comment by ncteisen** [comment]
Take  look at https://github.com/grpc/grpc/tree/master/tools/run_tests#performance-benchmarks-run_performance_testspy
