### ISSUE TITLE
c++ namespace enum keyword compiling error 

### ISSUE THREAD

**Issue by Christophernt** [grpc/grpc#16564]
### What version of gRPC and what language are you using?
gRPC 1.14.2 c++
 
### What operating system (Linux, Windows, …) and version?
Windows 7 sp1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
visual studio 2015 update3
 
### What did you do?
syntax = "proto3";
package common.enum;
option java_multiple_files = false;
option java_package = "com.my.proto.common";
option java_outer_classname = "Enum";
enum EClientType
{
	UNKNOWN = 0;
	IOS = 1;
	ANDROID = 2;
	WEB = 3;
}
 
### What did you expect to see?
namespace 
 
### What did you see instead?
::common::enum::EClientType client_type() const; 
compiling error 
 
### Anything else we should know about your project / environment?
grpc-java no compiling error,but enum in namespace is one of c++ keywords。Because the project has already started,without modify proto package,can we go through other ways?

**Comment by ncteisen** [comment]
I don't think there is a way to make this work for C++ since enum is a keyword... Is it possible to change the proto file?

**Comment by vjpai** [comment]
We have discussed dealing with reserved words in .proto files but don't have a specific plan. I would suggest that the path of least resistance (and probably quickest speed) is to change your .proto
