### ISSUE TITLE
Use Windows trust store by default.

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#16571]
This is a feature request, not a bug.  On Windows application developers must set an environment variable, or install `roots.pem` in a well-known directory to use TLS/SSL.  This was fixed for Linux on #16083 and it is being fixed on macOS on #16246.  This issue is a request to do a similar thing for Windows.

**Comment by coryan** [comment]
Note that #16246 was closed without merging, so macOS still does not use the native trust store.

**Comment by coryan** [comment]
This remains a problem.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work

**Comment by veblush** [comment]
Reopened it as it's a still valid issue.

**Comment by matthewstevenson88** [comment]
This was fixed in #34874.
