### ISSUE TITLE
Python pip source install issue on Onion Omega 2 (580MHz MIPS-based Linux platform)

### ISSUE THREAD

**Issue by cluster10537** [grpc/grpc#16586]
### What version of gRPC and what language are you using?
 gRPC version 1.14.2
Language Python 3.6.2
 
### What operating system (Linux, Windows, …) and version?
  LEDE (Linux Embedded Development Environment) Linux operating system, a distribution based on OpenWRT
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.6.2
 
### What did you do?
I tried to install gRPC (grpcio) via pip on onion omega 2+.

### What did you expect to see?
 Successfully installed.
 
### What did you see instead?
 
```
root@Omega-872F:~# pip install grpcio
Collecting grpcio
  Downloading https://files.pythonhosted.org/packages/a4/92/be89519c8328d78f88136a4b11951378a28525fd9606fc51c279fff48e5c/grpcio-1.14.2.tar.gz (14.4MB)
   100% |████████████████████████████████|14.4MB 10kB/s 
Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/site-packages (from grpcio) (1.11.0)
Requirement already satisfied: futures>=2.2.0 in /usr/lib/python2.7/site-packages (from grpcio) (3.2.0)
Requirement already satisfied: enum34>=1.0.4 in /usr/lib/python2.7/site-packages (from grpcio) (1.1.6)
Installing collected packages: grpcio
  Running setup.py install for grpcio ... error
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-eylBXM/grpcio/setup.py';
f=getattr(tokenize, 'open',open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
install --record /tmp/pip-record-imVtRI/install-record.txt --single-version-externally-managed --compile"
failed with error code 1 in /tmp/pip-install-eylBXM/grpcio/
``
```

 
### Anything else we should know about your project / environment?
This is the list of pip packages installed on onion omega 2+ with their respective versions.
```
root@Omega-872F:~# pip list
Package                  Version
------------------------ -------
gcloud                   0.17.0 
googleapis-common-protos 1.5.3  
httplib2                 0.11.3 
jws                      0.1.3  
oauth2client             3.0.0  
pip                      18.0   
protobuf                 3.6.1  
pyasn1                   0.4.4  
pyasn1-modules           0.2.2  
python-jwt               2.0.1  
requests                 2.11.1 
rsa                      3.4.2  
setuptools               40.2.0 
six                      1.11.0 
wheel                    0.31.1 
```
This is the information about onion omega 2+
**Operating system** - OpenWrt
**System on chip used** - MediaTek MT7688
**CPU** - 580 MHz 32-bit computing Single-core MIPS 24KEc
**Memory** - 64 MB (128 MB for Omega2 Plus)
**Storage** - 16 MB (32 MB and a Micro SDHC slot for Omega2 Plus)
**Graphics** - No graphic
**Power** - 0.6 Watts

More about onion omega 2+ can be found here https://docs.onion.io/omega2-docs/

**Comment by mehrdada** [comment]
Do you have `python-dev` and a sufficiently new C++ compiler installed on your system? There are no binaries available for your system so you are going to need build-from-source dependencies installed.

**Comment by cluster10537** [comment]
When tried to install `python-dev` on onion omega 2+ using the command `opkg install python-dev`, it says
`package python-dev already included in package python-base` 
I do not know about the new C++ compiler though. Should all these packages and compiler be installed on onion omega 2+ to build from source dependencies or should I use a different host machine to do that.
Please guide me through this process!! Thanks in advance.

**Comment by nicolasnoble** [comment]
All in all, there's not enough information on this bug to tell us exactly what failed...

**Comment by cluster10537** [comment]
I do not have any idea on how to source build the dependencies and what all packages and compilers it takes to do so. I would like to give it a try though, with some help and learning. 

So as of now is there no other way to install grpcio (gRPC) on the omega 2+???

**Comment by mehrdada** [comment]
@cluster10537 Have you tried running `pip install grpcio` after installing a relatively modern C++ compiler? If that fails, you may want to try "From Source" instructions on this page: https://github.com/grpc/grpc/tree/master/src/python/grpcio

**Comment by cluster10537** [comment]
No i have not tried it yet. It might take some time to do so as I have encountered some other issues with omega 2+. Will try to resolve them as soon as possible and update the results. Will also refer "From Source" until then. Thank you!!

**Comment by mehrdada** [comment]
Sounds good, please report back what you find. I strongly encourage exhausting your luck with `pip install` before trying the git route.

**Comment by cluster10537** [comment]
I factory reset my omega 2+ and did a fresh start. I installed C & C++ compilers on the onion omega 2+ following this guide https://onion.io/2bt-compiling-c-and-cpp-applications-on-omega/ and successfully ran C and C++ programs on omega 2+ to verify the installation as described in the above guide.

But however I am hit with the same installation error this time too.
```
root@Omega-872F:~# pip install grpcio
Collecting grpcio
  Downloading https://files.pythonhosted.org/packages/f7/40/875c30426e2df486dbb032c28478b2d551f6f8531cbc566040507bd7a4e5/grpcio-1.15.0.tar.gz (14.5MB)
    100% |████████████████████████████████| 14.5MB 6.2kB/s 
Collecting six>=1.5.2 (from grpcio)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting futures>=2.2.0 (from grpcio)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting enum34>=1.0.4 (from grpcio)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Installing collected packages: six, futures, enum34, grpcio
  Running setup.py install for grpcio ... error
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-GfiLdQ/grpcio/setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
install --record /tmp/pip-record-g0K4Ts/install-record.txt --single-version-externally-managed --compile" 
failed with error code 1 in /tmp/pip-install-GfiLdQ/grpcio/
```
The pip packages installed with their respective versions are
```
root@Omega-872F:~# pip list
Package    Version
---------- -------
enum34     1.1.6  
futures    3.2.0  
pip        18.0   
setuptools 40.2.0 
six        1.11.0 
```
Is there something I am missing?? Something that should be done after installing the C & C++ compilers. Please let me know what else should be done.

**Comment by mehrdada** [comment]
Please try `pip install -v -v -v`

**Comment by srini100** [comment]
We don't support this platform. Closing this issue.
