### ISSUE TITLE
grpc-go interop tests use old Go versions

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc#16604]
Go 1.11 has recently been released; the interop tests should be updated to use newer versions.  Go 1.7 and 1.8 will be unsupported by grpc-go in about a month.

**Comment by jtattermusch** [comment]
@dfawley  feel free to update docker tag to version you'd like to test with.

https://github.com/grpc/grpc/blob/1b6c3a01cf292159cd4208e8fbe64f84c8b90a8b/templates/tools/dockerfile/interoptest/grpc_interop_go/Dockerfile.template#L17
and then run `tools/buildgen/generate_project.sh`

**Comment by dfawley** [comment]
As the maintainer of this, would you mind making the changes?
