### ISSUE TITLE
Kerberos support?

### ISSUE THREAD

**Issue by lidavidm** [grpc/grpc#16612]
### What version of gRPC and what language are you using?
 
gRPC 1.10.1 (though we could use a later version), C++
 
### What operating system (Linux, Windows, …) and version?

Linux/Debian
 
### What did you do?

We have a `grpc_call_credentials` implementation of Kerberos authentication - it's pretty simple, just uses GSSAPI and adds a metadata field/HTTP header. We'd like to clean this up and upstream it, to use `grpc_cli` in particular for testing. Is this something you would be willing to add, alongside the other provided authentication methods (OAuth, etc)? It would add a (optional?) GSSAPI dependency.

**Comment by nicolasnoble** [comment]
Since this would be new cross language api, this would need a GRFC first, but otherwise, why not.

**Comment by lihalite** [comment]
This now has an GRFC: https://github.com/grpc/proposal/pull/101
