### ISSUE TITLE
memory leak in grpclb.cc: gpr_dump output not freed.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16619]
the output of gpr_dump need to be freed with  `gpr_free()`

https://github.com/grpc/grpc/blob/20345b21bb00c626ef346c26dbb3903c96c21c52/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L858

**Comment by jtattermusch** [comment]
Also probably worth mentioning that gpr_free needs to be called in grpc_dump_slice's doc comment.

**Comment by dgquintas** [comment]
grpc_dump_slice mentions it simply wraps gpr_dump, which mentions the need to free its result. Even though it's one level removed, I don't think it's necessary to repeat the semantics of gpr_dump in grpc_dump_slice (and doing so may be a bad idea: if the semantics change, there'd be two places where the comment would need updating, something the compiler wouldn't warm about).
