### ISSUE TITLE
TypeError: Expected bytes, NoneType found

### ISSUE THREAD

**Issue by mihail911** [grpc/grpc#16623]
### What version of gRPC and what language are you using?
``` 
Language: Python
grpcio: 1.15.0
```
 
### What operating system (Linux, Windows, …) and version?
 `macOS High Sierra 10.13.2`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 `Python: 3.5.5`
 
### What did you do?
Here is the relevant code:
```
import grpc
import numpy as np
import os

from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc

private_key_file = "/path/to/private/key/file"

# Create stub
server = "IP_ADDR:PORT"
channel = grpc.secure_channel(
                              server,
                              credentials=grpc.ssl_channel_credentials(
                              private_key=open(private_key_file, 'rb').read()))
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

# Create prediction request object
request = predict_pb2.PredictRequest()
...
# Call the prediction server
result = stub.Predict(request, 10.0)  # 10 secs timeout
```
 
### What did you expect to see?
 A valid request being made
 
### What did you see instead?
 
```
TypeError: expected bytes, NoneType found
Exception ignored in: 'grpc._cython.cygrpc.SSLChannelCredentials.c'
TypeError: expected bytes, NoneType found
Traceback (most recent call last):
  File "/path/to/client/grpc_client.py", line 54, in <module>
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/path/to/lib/python3.5/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/path/to/lib/python3.5/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "lame client channel"
	debug_error_string = "{"created":"@1536854327.468471000","description":"lame client channel","file":"src/core/lib/surface/lame_client.cc","file_line":90}"
```

### Anything else we should know about your project / environment?

I need to use a secure channel so that I can connect to a cloud machine instance, using authentication.

The only relevant issue I could find addressing this was here: https://github.com/grpc/grpc/issues/13866. Sadly, the suggested fix did not work. I've also tried running this code using a python2.7 env. I also know the contents of the file are there, as I've printed them to stdout. 

In addition, I've tried reading the file in non-byte format and then encoding to bytes, using something like `open(private_key_file, 'r').read().encode('utf-8')` but that also did not work.

At this point, I'm not entirely sure how to get this to work or what the possible source of error is. Any help/pointers would be greatly appreciated!

**Comment by mehrdada** [comment]
Have you tried reading the contents of the file on a separate line, printing it to ensure it was read correctly, and only then pass it as `private_key` argument? We have had tricky type issues between bytes and str because of different Python versions, but in this example something seems to be `None`, which is a bit different.

**Comment by mihail911** [comment]
Thanks for your prompt response @mehrdada. Yes I include the following lines:
```
with open(private_key_file, "rb") as f:
    key_pem_contents = f.read()
print(key_pem_contents)
```
right before calling:
```
channel = grpc.secure_channel(server,
                              credentials=grpc.ssl_channel_credentials(
                              private_key=key_pem_contents))
```
The printed output is:
```
b'----BEGIN RSA PRIVATE KEY [private_key_contents] ---END RSA PRIVATE KEY-----\r\n\r\n'
```
and I still get the error:
```
TypeError: expected bytes, NoneType found
```

**Comment by mehrdada** [comment]
@mihail911 Please try the last nightly build tomorrow from https://packages.grpc.io and confirm that #16640 has fixed the issue. Thanks

**Comment by mihail911** [comment]
Seems good to me. Thanks for the response -- feel free to close to the issue!
