### ISSUE TITLE
Remove "g stands for" word from User Agent string.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16630]
Example of User-Agent strings for all C-core based languages:
```
grpc-csharp/1.10.0 grpc-c/6.0.0 (windows; chttp2; glamorous),gzip(gfe)
grpc-ruby/1.13.0 grpc-c/6.0.0 (linux; chttp2; gloriosa),gzip(gfe)
...
(similar for other wrapped languages)
```

The g-stands-for word (glamorous, gloriosa, ...) is redundant (it's just a codeword for the version number and has no internal logic to help with easy version ID) and is taking up network bandwidth and memory. (On the wire it actually gets HPACK-compressed away but still needs to be sent at least once for a new connection). Let's remove from user agent string.

For comparison, Go's user agent string is `grpc-go/1.10.0,gzip(gfe)`  and java is `grpc-java-netty1.9.0,gzip(gfe)`

**Comment by mehrdada** [comment]
![sad](https://user-images.githubusercontent.com/900411/45524405-1d998800-b783-11e8-81a0-c59e093aa25a.gif)

**Comment by jtattermusch** [comment]
CC @a11r , @ejona86, @dfawley, @hsaliak , @markdroth, @ncteisen what do you think?

**Comment by ejona86** [comment]
A 10 byte optimization per-connection is so very small there's little sense discussing it. The same applies to the in-memory argument since HPACK will make the allocation per-connection.

That said, I was against adding it to the user-agent string originally because it is just noise that makes parsing user-agent information harder for no gain.

**Comment by markdroth** [comment]
FWIW, I'm ambivalent.  I'm not opposed to removing it if that's the consensus, but I also don't see a compelling argument here for removing it.  My default would probably be to just leave it here, since doing nothing is the easiest path forward. :)

**Comment by ncteisen** [comment]
I am in favor of removing it

**Comment by nicolasnoble** [comment]
I'm with @markdroth.

**Comment by dfawley** [comment]
+1 for removing; it has no function and it presumably takes about the same effort to update it for one release as it would to remove it forever.

**Comment by ncteisen** [comment]
For your consideration: #16634

**Comment by nicolasnoble** [comment]
@dfawley actually, no, it takes zero effort, because it's an automated process with the rest of the normal release process.

**Comment by hsaliak** [comment]
Sadly, my vote is to remove so it does not show up in logs. I would still encourage the convention to update what g stands for in every release.

**Comment by ncteisen** [comment]
FWIW, while we are talking about user agent, I would like to stop unconditionally surfacing it to server apps, as it causes an allocation in the RPC hotpath. Added a knob to disable in #16558, would like to flip the default...

**Comment by mehrdada** [comment]
@hsaliak I think if we are going to get rid of it, we should just fix the API to return "gRPC", mark it deprecated, and get done with updating it as well, as naming controversies cannot arise if we have one name.

**Comment by vjpai** [comment]
Let the record show that I LBTM'ed the PR creating this abomination.

**Comment by vjpai** [comment]
Quick, tell me what version 1.4 was called without looking it up. You can't, can you? I can do this for all the Android versions, but not for more than a few versions of grpc. We laugh for 5 minutes about our names, but they're really not that memorable.

**Comment by mehrdada** [comment]
@hsaliak I agree with @vjpai and I think straddling between "g stands for something every time" and "g stands for gRPC" loosens our marketing stance and people default on the common (incorrect) wisdom of "g = google". Since I think few people ever grokked g changes every time in the community, despite my interest in having cuteness like that, I have to say we should double down on g stands for gRPC and get rid of gimmicks.

**Comment by hsaliak** [comment]
If the plan is to fix g stands for "grpc" going forward then that's fine.
It's simple.

I personally don't agree that this is a gimmick or not that this is
something forgetful. It's something fun that our project does -- there is
nothing wrong in us having fun with it.

However I do concede that the bikeshedding is not worth it and we should
take the chance to end the argument once and for all. So let's fix on g
stands for gRPC :)

**Comment by vjpai** [comment]
Thanks, @hsaliak . And I think it would still be awesome to make a new "g" name each time and announce it in our release notes, but more as a curiosity than anything else. I'm still waiting on gaoRPC for @yang-g .

**Comment by jtattermusch** [comment]
I still think this should be removed. It is not useful for anything and it just makes us send X extra bytes (depending on the length of the codeword) on the wire for every first RPC on a given connection (for following RPCs it gets HPACK'd away, but it's still useless).

Here is a TCP dump for sending a first RPC, you can see that "ganges" is sent on the wire.
```
I0906 11:46:40.896949 4368844224 /Users/jtattermusch/github/grpc/src/core/lib/iomgr/tcp_posix.cc:1058: WRITE 0x7ff1a870fcc0 (peer=ipv6:[::1]:8070)
D0906 11:46:40.896955 4368844224 /Users/jtattermusch/github/grpc/src/core/lib/iomgr/tcp_posix.cc:1062: DATA: 75 73 65 72 2d 61 67 65 6e 74 'user-agent'
I0906 11:46:40.896960 4368844224 /Users/jtattermusch/github/grpc/src/core/lib/iomgr/tcp_posix.cc:1058: WRITE 0x7ff1a870fcc0 (peer=ipv6:[::1]:8070)
D0906 11:46:40.897121 4368844224 /Users/jtattermusch/github/grpc/src/core/lib/iomgr/tcp_posix.cc:1062: DATA: 39 '9'
I0906 11:46:40.897136 4368844224 /Users/jtattermusch/github/grpc/src/core/lib/iomgr/tcp_posix.cc:1058: WRITE 0x7ff1a870fcc0 (peer=ipv6:[::1]:8070)
D0906 11:46:40.897165 4368844224 /Users/jtattermusch/github/grpc/src/core/lib/iomgr/tcp_posix.cc:1062: DATA: 67 72 70 63 2d 63 73 68 61 72 70 2f 32 2e 32 34 2e 30 2d 64 65 76 20 67 72 70 63 2d 63 2f 38 2e 30 2e 30 20 28 6f 73 78 3b 20 63 68 74 74 70 32 3b 20 67 61 6e 67 65 73 29 'grpc-csharp/2.24.0-dev grpc-c/8.0.0 (osx; chttp2; ganges)'
```
