### ISSUE TITLE
gRPC WaitForConnected always return true

### ISSUE THREAD

**Issue by pavanpalaksha** [grpc/grpc#16636]
I have grpc server and grpc client solution running as 2 separate services. If the client comes up first, it tries to connect to grpc server and if server is not up, it suppose to wait. I thought WaitForConnected is defined for this purpose. It looks like it's not working correctly.

My Code:

    if (!channel->WaitForConnected(gpr_time_add(
              gpr_now(GPR_CLOCK_REALTIME),
              gpr_time_from_seconds(600, GPR_TIMESPAN)))) {
        //Log error and return
        // This never gets executed even if server is not up.
      }
     grpc_connectivity_state state = channel->GetState(true);
     // cout << state always return 2 (GRPC_CHANNEL_READY) even if server is not up.  

Grpc branch: 1.6.x
Language: c++

**Comment by mljack** [comment]
Found the same issue with grpc-1.15.0 in docker environment, but it works fine in its Ubuntu 16.04 host environment. In a docker environment, client never connected to server, but WaitForConnected() always returns true no matter whether the server is up or down. Both client and server use 127.0.0.1 inside the docker.

**Comment by badc0re** [comment]
Any chance of this getting fixed soon, or any other way to check it?
