### ISSUE TITLE
Surface exceptions in Cython code

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#16643]
gRPC Python consists of a bunch of logic written in Cython that calls into gRPC Core. The Cython code is not marked as `except *` thereby ignoring exceptions that happen when manipulating Python objects. To be clear, these are often exceptions that happen due to incorrect type or invalid input values not errors from C core. This matter is exacerbated due to Python being a dynamically typed language (although Cython does typechecking at times, even those exceptions are buried by default and reduced to a log statement, except for API surfaces). 

It'd be a good idea to apply `except *` throughout Cython wrapping layer to expose the exceptions to the user.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
