### ISSUE TITLE
python: helloworld demo can not run

### ISSUE THREAD

**Issue by AgainstWind** [grpc/grpc#16669]
### What version of gRPC and what language are you using?
 Python 2.7.5
 
### What operating system (Linux, Windows, …) and version?
 CentOS Linux release 7.5.1804 (Core) 
kernel: 3.10.0-862.9.1.el7.x86_64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
  Python 2.7.5
 
### What did you do?
```shell
# python greeter_server.py // no exception
# python greeter_client.py // exception occurred
```
 
### What did you see instead?
```
E0921 10:45:16.156462100   27754 uri_parser.cc:45]           bad uri.scheme: '4.38.51.70:3128'
E0921 10:45:16.156496995   27754 uri_parser.cc:51]                            ^ here
E0921 10:45:16.156502452   27754 http_proxy.cc:52]           cannot parse value of 'http_proxy' env var
Traceback (most recent call last):
  File "/home/yuezht/workspace/grpc-master/examples/python/helloworld/greeter_client.py", line 35, in <module>
    run()
  File "/home/yuezht/workspace/grpc-master/examples/python/helloworld/greeter_client.py", line 28, in run
    with grpc.insecure_channel('4.38.51.219:50051') as channel:
AttributeError: __exit__
```

**Comment by nicolasnoble** [comment]
Well, as the error message says, you have a environment variable called `http_proxy`. Either unset it, or set it up to a valid value, such as `http://4.38.51.70:3128`, if you really need to use this proxy.
