### ISSUE TITLE
Makefile fails linking with `prefix` variable

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#16664]
### What version of gRPC and what language are you using?
 1.12.1, C++
 
### What operating system (Linux, Windows, …) and version?
 Centos 
 
### What did you do?
make command to build grpc

### What did you expect to see?
 successful make
 
### What did you see instead?
 make failed since user doesnot has permission to access /usr/local/include or any root directory. Is there any way to pass file path params to Makefile in order to make grpc install .so and other headers in Users directory.

Error: 
`cannot create directory `/usr/local/include/grpc': Permission denied`

**Comment by lucifercr07** [comment]
@nicolasnoble Thanks a lot. 👍

**Comment by lucifercr07** [comment]
@nicolasnoble Using prefix variable doesnot create so's linking properly.
Example: 
`make install`
Output: `ldd libgrpc++_reflection.so.1.12.1`
`	linux-vdso.so.1 =>  (0x00007ffcc2371000)
	libgrpc.so.6 => /usr/local/lib/libgrpc.so.6 (0x00007fc01b026000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc01aca4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc01aa8e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc01a6c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc01b71c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc01a4bc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc01a1b3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc019f96000)
`

`make install prefix=/foo/bar`
Output: `ldd libgrpc++_reflection.so.1.12.1`
`	
        linux-vdso.so.1 =>  (0x00007ffd27ff5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fce60130000)
	libgrpc++.so.1 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fce5fdae000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fce5fb98000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fce5f7ce000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fce60710000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fce5f4c5000)
`

**Comment by nicolasnoble** [comment]
The .so linking is a facility provided by the tool `ldconfig`. It's not something the Makefile does, nor something that should. Please take the appropriate steps to configure your system accordingly.

**Comment by lucifercr07** [comment]
@nicolasnoble should I run ldconfig after running? I tried export LD_LIBRARY_PATH, but still the libgrpc.so.1 link is not found. 
Can you please guide?

**Comment by nicolasnoble** [comment]
As I said, when you do `make install` on the system in the normal location, your system's `ldconfig` tool will find the libraries and link them appropriately. You simply need to learn and use this tool accordingly with your environment.

Please read the following documentation to learn about how this works:
http://man7.org/linux/man-pages/man8/ldconfig.8.html
