### ISSUE TITLE
GRPC .so's dynamic link failing C++

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#16670]
### What version of gRPC and what language are you using?
 1.12, C++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu
 
### What did you do?
I have `libgrpc++.so  libgrpc++_reflection.so  libgrpc.so  libprotobuf-lite.so`, I was trying to create a greeting_client binary using dynamic linking. I have header files inside third-party/include, I am not able to create binary.

### What did you expect to see?
 Successful binary creation.
 
### What did you see instead?
`libgpr.so: cannot open shared object file: No such file or directory`

**Comment by jtattermusch** [comment]
what compiler did you use & what build system (make, cmake, ..) ? What were the exact commands you ran, were you following any of our tutorials?
