### ISSUE TITLE
GRPC C++ Build Fails for gcc 8.2

### ISSUE THREAD

**Issue by kapilsh** [grpc/grpc#16675]
### What version of gRPC and what language are you using?

1.15.0  and C++
 
### What operating system (Linux, Windows, …) and version?
 
Linux - CentOS 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc 8.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```
# With gcc 8.2 in environment
$ gcc --version
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ git clone --recursive https://github.com/grpc/grpc
$ cd grpc && git checkout v1.15.0 -b v1.15.0
$ mkdir build && cd build
$ cmake ..
$ make -j4
```  

### What did you expect to see?
 
Build Successfully
 
### What did you see instead?
```
/home/ksharma/Downloads/grpc/third_party/boringssl/crypto/x509/x509_test.cc: In member function ‘virtual void X509Test_ZeroLengthsWithX509PARAM_Test::TestBody()’:
/home/ksharma/Downloads/grpc/third_party/boringssl/crypto/x509/x509_test.cc:712:10: error: declaration of ‘struct X509Test_ZeroLengthsWithX509PARAM_Test::TestBody()::Test’ shadows a previous local [-Werror=shadow]
   struct Test {
          ^~~~
In file included from /home/ksharma/Downloads/grpc/third_party/boringssl/crypto/x509/x509_test.cc:19:
/home/ksharma/Downloads/grpc/third_party/boringssl/third_party/googletest/include/gtest/gtest.h:375:23: note: shadowed declaration is here
 class GTEST_API_ Test {
 ```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

I tried building it with `gcc 7.3` and it built successfully. So, I some default warnings/error compiler flags introduced in `gcc 8` fails the build.

**Comment by nicolasnoble** [comment]
First, this is on boringssl, not on us. Second, you're trying to build everything, including the tests, which is the default with cmake. Please change your cmake settings to only build the main library.

**Comment by nicolasnoble** [comment]
And in all cases, the *test* code might not be compatible with all compilers, while the main library code is. As I said, if you disable compiling the tests, it'll work.

**Comment by kapilsh** [comment]
yes - my bad `1.15.0`

**Comment by kapilsh** [comment]
gotcha - will do. Thanks! 

Just a heads up that `master` of `boringssl` builds successfully (with tests) in `gcc 8.1` and `8.2`. so the issue is probably fixed in a later hash.

**Comment by nicolasnoble** [comment]
We're trying to stick on the same released versions of boringssl as the chromium project.

**Comment by daveharmon** [comment]
How exactly can I disable compiling the tests? It seems like `gRPC_BUILD_TESTS` already defaults to off

**Comment by nicolasnoble** [comment]
We've updated our BoringSSL submodule actually - is it still an issue?

**Comment by Lance0312** [comment]
Same here on `v1.16.1`

**Comment by ncwhale** [comment]
Here is a Quick fix: just checkout the boringssl's master branch, and done.

`Refs: [v1.16.0], v1.12.1-2456-g759390f99e
Author:     whalemo <flan@kouga.us>
AuthorDate: Mon Dec 3 14:38:40 2018 +0800
Commit:     whalemo <flan@kouga.us>
CommitDate: Mon Dec 3 14:38:40 2018 +0800

    Move boringssl submodule to new master branch.

    Fix BUG #16675.
---
 third_party/boringssl | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/third_party/boringssl b/third_party/boringssl
index b29b21a81b..0f5ecd3a85 160000
--- a/third_party/boringssl
+++ b/third_party/boringssl
@@ -1 +1 @@
-Subproject commit b29b21a81b32ec273f118f589f46d56ad3332420
+Subproject commit 0f5ecd3a854546d943104e1f7421e489b7f4d5aa
`

**Comment by vjpai** [comment]
@nicolasnoble : has this been updated/fixed? I think so, but wanted to confirm.

**Comment by handicraftsman** [comment]
Seems to not be fixed

**Comment by regulrjoe** [comment]
Also facing this issue on Debian Buster in 1.22.0.

**Comment by kapilsh** [comment]
I ended up using openssl instead of boringssl. I believe it support both.

**Comment by monocleus** [comment]
This is not fixed and unfortunately the crypto module ( boringssl/crypto ) doesn't have any flag which controls building the test. It will have to be fixed by boringssl

**Comment by nicolasnoble** [comment]
We're overhauling our errors / warnings stuff, but this one should be fine now.

**Comment by irsdkv** [comment]
Just if anybody still need solution:
This patch helped for me:
https://boringssl-review.googlesource.com/c/boringssl/+/28524/2/crypto/x509/x509_test.cc
