### ISSUE TITLE
request_response argument-count mismatch between server.rb and client_stub.rb

### ISSUE THREAD

**Issue by jkub** [grpc/grpc#16684]
It seems "metadata" became a named_argument in client_stub.rb, but server.rb is still passing it as a positional argument on line 170. "metadata" needs to get passed as a named argument.

```
irb(main):010:0> stub.show_tables('foo', '')
Traceback (most recent call last):
        4: from /usr/local/bin/irb:11:in `<main>'
        3: from (irb):10
        2: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
        1: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:148:in `request_response'
ArgumentError (wrong number of arguments (given 5, expected 4))
irb(main):011:0>

```

 
### What version of gRPC and what language are you using?
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
grpc v1.13.1  (befc7220cadb963755de86763a04ab6f9dc14200)
 
### What operating system (Linux, Windows, …) and version?
linux debian 9.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 ruby 2.5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

See above. Attempt to make a single synchronous client request to a service stub in ruby.
 
### What did you expect to see?
 I expected it to work
 
### What did you see instead?
 Exception paste above

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
Nope. Looks like a 1-line fix.

**Comment by apolcyn** [comment]
From the git blame, `metadata` has been a keyword argument in `client_stub.rb` for the last two years (since around the GA release), so there doesn't seem to be any recent breakage here, and I don't think there's a problem here.

When you call: 

```
stub.show_tables('foo', '')
```

What does the second "empty string" param that you are passing correspond to? Also did this ever work, and do you know at what grpc version this worked for? 

That said, one issue I can see is that `metadata` is not a good name for for the parameter in https://github.com/grpc/grpc/pull/16685/files#diff-37292ab4014737ea90165c478a9a0e50L168. Rather than `metadata` that variable should be named something like `call_options`, because that argument corresponds to the hash which can contain things like `deadline`, `metadata`, and `return_op`.

**Comment by jkub** [comment]
@apolcyn thank you for the quick response. You are correct. I'm sorry for the distraction.

When I made the above change, I got a much more informative error, which led me to believe I had made forward progress. I realized then that my stub request was malformed, and I fixed it. It had simply not occurred to me that the malformed request was the root cause of the previous exception as well.

After the fix:

irb(main):019:0> stub.show_tables 'foo', ''
Traceback (most recent call last):
        9: from /usr/local/bin/irb:11:in `<main>'
        8: from (irb):19
        7: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
        6: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
        5: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
        4: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
        3: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:353:in `request_response'
        2: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:35:in `block in marshal_proc'
        1: from /usr/local/lib/ruby/gems/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:35:in `method'
NameError (undefined method `encode' for class `#<Class:String>')
