### ISSUE TITLE
in make phase (C++) : third_party/cares/cares/ares_init.c error . all warnings being treated as errors

### ISSUE THREAD

**Issue by marcoippolito** [grpc/grpc#16688]
Hi,

I 'm my Ubuntu 18.04.1 LTS I'm just trying to install and build gRPC, but in the "make" step there, as you can see, there is an error:

    third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
    third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same 
    expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-
    memaccess]
               sizeof(src->local_dev_name));

These are the steps followed:

    marco@PC:~$ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100     8  100     8    0     0     31      0 --:--:-- --:--:-- --:--:--    31
    Cloning into 'grpc'...
    remote: Counting objects: 398293, done.
    remote: Compressing objects: 100% (31/31), done.
    remote: Total 398293 (delta 22), reused 21 (delta 21), pack-reused 398241
    Receiving objects: 100% (398293/398293), 179.33 MiB | 9.12 MiB/s, done.
    Resolving deltas: 100% (307519/307519), done.
    Note: checking out 'd2c7d4dea492b9a86a53555aabdbfa90c2b01730'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    marco@PC:~$ cd grpc
    marco@PC:~/grpc$ git submodule update --init
    Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp) registered for path 
    'third_party/abseil-cpp'
    Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 
    'third_party/benchmark'
    Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 
    'third_party/bloaty'
    Submodule 'third_party/boringssl' (https://github.com/google/boringssl.git) registered for path 
    'third_party/boringssl'
    Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for 
    path 'third_party/boringssl-with-bazel'
    Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 
    'third_party/cares/cares'
    Submodule 'third_party/gflags' (https://github.com/gflags/gflags.git) registered for path 
    'third_party/gflags'
    Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 
    'third_party/googletest'
    Submodule 'third_party/libcxx' (https://github.com/llvm-mirror/libcxx.git) registered for path 
    'third_party/libcxx'
    Submodule 'third_party/libcxxabi' (https://github.com/llvm-mirror/libcxxabi.git) registered for path 
    'third_party/libcxxabi'
    Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 
    'third_party/protobuf'
    Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
    Cloning into '/home/marco/grpc/third_party/abseil-cpp'...
    Cloning into '/home/marco/grpc/third_party/benchmark'...
    Cloning into '/home/marco/grpc/third_party/bloaty'...
    Cloning into '/home/marco/grpc/third_party/boringssl'...
    Cloning into '/home/marco/grpc/third_party/boringssl-with-bazel'...
    Cloning into '/home/marco/grpc/third_party/cares/cares'...
    Cloning into '/home/marco/grpc/third_party/gflags'...
    Cloning into '/home/marco/grpc/third_party/googletest'...
    Cloning into '/home/marco/grpc/third_party/libcxx'...
    Cloning into '/home/marco/grpc/third_party/libcxxabi'...
    Cloning into '/home/marco/grpc/third_party/protobuf'...
    Cloning into '/home/marco/grpc/third_party/zlib'...
    Submodule path 'third_party/abseil-cpp': checked out 'cc4bed2d74f7c8717e31f9579214ab52a9c9c610'
    Submodule path 'third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
    Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
    Submodule path 'third_party/boringssl': checked out 'b29b21a81b32ec273f118f589f46d56ad3332420'
    Submodule path 'third_party/boringssl-with-bazel': checked out    
    '8149b351bf797bd80e063787886b7618f508e451'
    Submodule path 'third_party/cares/cares': checked out 
    '3be1924221e1326df520f8498d704a5c4c8d0cce'
     Submodule path 'third_party/gflags': checked out '30dbc81fb5ffdc98ea9b14b1918bfe4e8779b26e'
    Submodule path 'third_party/googletest': checked out 'ec44c6c1675c25b9827aacd08c02433cccde7780'
    Submodule path 'third_party/libcxx': checked out '6599cac0965be8e5a835ab7a5684bbef033d5ad0'
    Submodule path 'third_party/libcxxabi': checked out '9245d481eb3e890f708ff2d7dadf2a10c04748ba'
    Submodule path 'third_party/protobuf': checked out '48cb18e5c419ddd23d9badcfe4e9df7bde1979b2'
    Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'

     marco@PC:~/grpc$ make
    marco@PC:~/grpc$ make
    [MAKE]    Generating /home/marco/grpc/libs/opt/pkgconfig/grpc.pc
    [MAKE]    Generating /home/marco/grpc/libs/opt/pkgconfig/gpr.pc
    [MAKE]    Generating /home/marco/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
    [MAKE]    Generating cache.mk
     [C]       Compiling third_party/address_sorting/address_sorting.c
    [C]       Compiling third_party/address_sorting/address_sorting_posix.c
    [C]       Compiling third_party/address_sorting/address_sorting_windows.c
    [AR]      Creating /home/marco/grpc/libs/opt/libaddress_sorting.a
    [C]       Compiling third_party/cares/cares/ares__close_sockets.c
    [C]       Compiling third_party/cares/cares/ares__get_hostent.c
    [C]       Compiling third_party/cares/cares/ares__read_line.c
    [C]       Compiling third_party/cares/cares/ares__timeval.c
    [C]       Compiling third_party/cares/cares/ares_cancel.c
    [C]       Compiling third_party/cares/cares/ares_create_query.c
    [C]       Compiling third_party/cares/cares/ares_data.c
    [C]       Compiling third_party/cares/cares/ares_destroy.c
    [C]       Compiling third_party/cares/cares/ares_expand_name.c
    [C]       Compiling third_party/cares/cares/ares_expand_string.c
    [C]       Compiling third_party/cares/cares/ares_fds.c
    [C]       Compiling third_party/cares/cares/ares_free_hostent.c
    [C]       Compiling third_party/cares/cares/ares_free_string.c
    [C]       Compiling third_party/cares/cares/ares_getenv.c
    [C]       Compiling third_party/cares/cares/ares_gethostbyaddr.c
    [C]       Compiling third_party/cares/cares/ares_gethostbyname.c
    [C]       Compiling third_party/cares/cares/ares_getnameinfo.c
    [C]       Compiling third_party/cares/cares/ares_getopt.c
    [C]       Compiling third_party/cares/cares/ares_getsock.c
    [C]       Compiling third_party/cares/cares/ares_init.c
    third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
    third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same 
    expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-
    memaccess]
               sizeof(src->local_dev_name));
                     ^
    third_party/cares/cares/ares_init.c: At top level:
    cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
    cc1: all warnings being treated as errors
    Makefile:2896: recipe for target '/home/marco/grpc/objs/opt/third_party/cares/cares/ares_init.o' failed
    make: *** [/home/marco/grpc/objs/opt/third_party/cares/cares/ares_init.o] Error 1
    marco@PC:~/grpc$

What do I have to do to solve the problem? Looking forward to your kind hints and help.
Marco

**Comment by fho** [comment]
The fix is part of the 1.15.0 c-ares release (https://github.com/c-ares/c-ares/releases/tag/cares-1_15_0). It was released on the 23.10.18.

**Comment by fho** [comment]
The issue was fixed with PR https://github.com/grpc/grpc/pull/18519
