### ISSUE TITLE
Thank u!I understand.but Grpc website did not introduce how to use Xcode tools to building gRPC.

### ISSUE THREAD

**Issue by cuteworld** [grpc/grpc#16683]
I don't know how to do it.I hope you can tell me.

_Originally posted by @cuteworld in https://github.com/grpc/grpc/issues/16673#issuecomment-423745228_

**Comment by srini100** [comment]
Does this help? https://github.com/grpc/grpc/tree/master/examples/objective-c/helloworld

**Comment by muxi** [comment]
A more complete version is [here](https://grpc.io/docs/quickstart/objective-c.html).

**Comment by nicolasnoble** [comment]
I'm fairly certain they weren't asking about Objective-C, but about C++.

**Comment by muxi** [comment]
Ahh that was forwarded from #16673.

There's no doc in this case. As a very high level description of the process, if you used Xcode before, you may create a workspace and add your project to it. Then you can add another xcodeproj to the workspace, which builds all gRPC files and produce a static library (.a). Once that works, you can use this new project as dependency in your project.

**Comment by nicolasnoble** [comment]
Or, more generally speaking, sorry, but we're not going to start training people on how to use development tools. I'll direct you to guides such as http://railsapps.github.io/xcode-command-line-tools.html or https://www.embarcadero.com/starthere/berlin/mobdevsetup/ios/en/installing_the_xcode_command_line_tools_on_a_mac.html
