### ISSUE TITLE
Pull requests on v1.15.x branch unable to be merged

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#16689]
There are a few problems actually
* **The required `Bazel Build Basic` test is unable to get report (test succeeded though)**
* A lot of bazel builds consistently failing
* Interop tests seems to consistently failing

Ref PR: #16676, #16677, #16678 

@nicolasnoble

**Comment by muxi** [comment]
No longer P1 since the affected PRs are force merged (thanks @nicolasnoble :)

**Comment by jtattermusch** [comment]
Seems solved? This is likely due to recent renaming of the test name. We updated the github configuration on master, we might have needed to update on v1.15.x branch too.

Reassigning to @nicolasnoble  as I don't have the access rights to change the settings anyway.
