### ISSUE TITLE
Copy constructor of grpc::CompletionQueue is invalid

### ISSUE THREAD

**Issue by benhansen-io** [grpc/grpc#16705]
CompletionQueue appears to have the default copy constructor which naively copies the internal pointer.  This causes multiple CompletionQueue objects to share the same internal pointer which will be destroyed by the first one that calls its destructor. See https://github.com/grpc/grpc/blob/8bf52535d1008a3f38e70d1387846f0e942761b5/include/grpcpp/impl/codegen/completion_queue.h#L111

The copy constructor should be disabled.

### What version of gRPC and what language are you using?
 
Version 1.15.1 with C++
 
### What operating system (Linux, Windows, …) and version?

Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
C++ compiled with GCC 7.2
 
### What did you do?

```
#include "grpcpp/grpcpp.h"                                                    
                                                                              
int main(int argc, char* argv[]) {                                            
  // Causes crash
  grpc::CompletionQueue* cq_copy_from = new grpc::CompletionQueue();          
  grpc::CompletionQueue cq = *cq_copy_from;                                   
  delete cq_copy_from;                                                        
  //                                                                       
                                                                              
  /* Works fine                                                               
  grpc::CompletionQueue cq;                                                   
  */                                                                          
                                                                              
  void* tag;                                                                  
  bool ok;                                                                    
  cq.Next(&tag, &ok);                                                         
}                     
```
 
### What did you expect to see?
 
Wait indefinitely on CompletionQueue.Next(...)
 
### What did you see instead?
 
Crash on assertion inside gRPC

**Comment by benhansenslc** [comment]
This appears to still be an issue based on the diff between https://raw.githubusercontent.com/grpc/grpc/8bf52535d1008a3f38e70d1387846f0e942761b5/include/grpcpp/impl/codegen/completion_queue.h and https://raw.githubusercontent.com/grpc/grpc/master/include/grpcpp/impl/codegen/completion_queue_impl.h

**Comment by benhansenslc** [comment]
Still applicable.

**Comment by yashykt** [comment]
I think this can be closed now since CompletionQueue API has an implicitly deleted copy constructor
