### ISSUE TITLE
How to send the NSDATA in byte chunks form using the grpc streaming in objective c??

### ISSUE THREAD

**Issue by mohanbright** [grpc/grpc#16723]
I am facing the problem data sending the byte form over the grpc using the GRXBufferedPipe or GRXWriter. If i am sending the data in the form of NSData the sever show the the file but its corrupted. 
Sever is in Golang and it recieve the empty bytes.
Any help is appreciated

Thanks

**Comment by muxi** [comment]
That is weird. `GRXBufferedPipe` should be able to take `NSData`. Are you using `ProtoRPC`? If you are using that, it expects you to pass a protobuf message rather than `NSData`. That's one possible way I can think of to make the data corrupted.

**Comment by muxi** [comment]
@mohanbright - Any follow up?
