### ISSUE TITLE
compile error: ‘dynamic_init_dummy_src_2fproto_2fgrpc_2fcore_2fstats_2eproto’ defined but not used [-Werror=unused-variable]

### ISSUE THREAD

**Issue by mingwugmail** [grpc/grpc#16739]
### What version of gRPC and what language are you using?

git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc

c++ 
 
### What operating system (Linux, Windows, …) and version?
 
 Ubuntu 16.04.5 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04) 

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
build error.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

$ make
...
[PROTOC]  Generating protobuf CC file from src/proto/grpc/core/stats.proto
[CXX]     Compiling /grpc/gens/src/proto/grpc/core/stats.pb.cc
/grpc/gens/src/proto/grpc/core/stats.pb.cc:185:13: error: ‘dynamic_init_dummy_src_2fproto_2fgrpc_2fcore_2fstats_2eproto’ defined but not used [-Werror=unused-variable]
 static bool dynamic_init_dummy_src_2fproto_2fgrpc_2fcore_2fstats_2eproto = []() { AddDescriptors_src_2fproto_2fgrpc_2fcore_2fstats_2eproto(); return tr
             ^
cc1plus: all warnings being treated as errors
Makefile:2658: recipe for target '/grpc/gens/src/proto/grpc/core/stats.pb.o' failed
make: *** [/grpc/gens/src/proto/grpc/core/stats.pb.o] Error 1

**Comment by apolcyn** [comment]
Re: `git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc`

Can you please share the specific git commit or release tag that was used here?

**Comment by mlda065** [comment]
I'm getting the same issue with tag `v1.3.2`.

I did 

```
git checkout tags/v1.3.2
git submodule update --init --recursive
make
```

As per [these instructions](https://github.com/p4lang/PI).

**Comment by sampleref** [comment]
Getting same issue with tag v1.20.0 . I am using 

git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc

**Comment by sampleref** [comment]
Simple shell script hack as mentioned at https://github.com/grpc/grpc/issues/16739#issuecomment-445442067 while compiling as below,

git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc /var/local/git/grpc && \
	cd /var/local/git/grpc && \
    git submodule update --init && \
    echo "--- installing grpc ---" && \
	**ex -s -c '356i|CPPFLAGS += -Wno-unused-variable' -c x Makefile && \**
    make -j$(nproc) && make install && ldconfig && \
	echo "--- installing protobuf ---" && \
    cd third_party/protobuf && \
    make install && make clean && ldconfig && \
	cd /var/local/git/grpc && make clean && \
    cd / && \
	rm -rf /var/local/git/grpc

**Comment by glukasiknuro** [comment]
Similar issue on
commit 9dfbd34f5c0b20bd77658c73c59b9a3e4e8f4e14 (HEAD, tag: v1.20.0)

For `$ make grpc_cli`

```
 $ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

$ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

$ python --version
Python 2.7.12
```

**Comment by weinrea** [comment]
I got this too trying to build v1.20.0 with gcc on Ubuntu 16.04.
Any of the following works:
- Ignore warnings
`$ CXXFLAGS='-Wno-error' make`
- Use clang
`$ CC=clang CXX=clang++ make`
