### ISSUE TITLE
GRPC error with ubuntu 12.04

### ISSUE THREAD

**Issue by manuurdevang** [grpc/grpc#16730]
This is my system architecture
![screenshot from 2018-09-27 13-52-52](https://user-images.githubusercontent.com/756181/46132791-a4a72f80-c25c-11e8-9cd9-a24757e2c5f1.png)

This is bug I am facing
![screenshot from 2018-09-27 13-51-14](https://user-images.githubusercontent.com/756181/46132721-7b869f00-c25c-11e8-99e3-cbb9926f1add.png)

Thanks Manohar M R

_Originally posted by @manuurdevang in https://github.com/grpc/grpc/issues/13908#issuecomment-425002901_

**Comment by apolcyn** [comment]
@manuurdevang the strange thing that pops out here is that you seem to be using the one of the pre-compiled `x86_64` grpc packages on what looks like a 32 bit architecture.

I'm wondering how the `x86_64` grpc package was downloaded here in the first place. Normally, the package manager should be fetch the 32-bit pre-compiled grpc package when it recognizes that it's installing for a 32-bit platform.

One more thing I'm wondering, can you please run:

```
$ irb
irb> RUBY_PLATFORM
```

and share the output here? thanks
