### ISSUE TITLE
There is no gRPCTargets.cmake generated

### ISSUE THREAD

**Issue by ShengliangD** [grpc/grpc#16741]
### What version of gRPC and what language are you using?
 v1.15.0, C++
 
### What operating system (Linux, Windows, …) and version?
Windows 10
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 2015 Win64 

 
### What did you do?
After building and installing grpc, I tried to configure another project using cmake which uses grpc.
 
### What did you expect to see?
 The configuration procedure should finish normally.
 
### What did you see instead?
```
CMake Error at xxx/gRPCConfig.cmake:8 (include):
  include could not find load file:
    xxx/gRPCTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:1438 (find_package)
```

I read through related issues but got no idea how to make it work...

**Comment by ShengliangD** [comment]
Well, I faked this file using [this](https://github.com/matrix-io/protocol-buffers/blob/master/cmake/FindGRPC.cmake), and now it seems to be working...

**Comment by apolcyn** [comment]
Does [this example](https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld/cmake_externalproject) help on this end?

**Comment by jtattermusch** [comment]
You can only install gRPC if all the dependencies are set to gRPC_*_PROVIDER=package (i.e. they are preinstalled), if you use dependencies from submodules, installation will be disabled automatically (as there is no way to make that work with cmake).

Examples:
https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.bat
and 
https://github.com/grpc/grpc/blob/04b78efb45ad93106f84a9293b1d21d8896ae526/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt#L78

**Comment by ShengliangD** [comment]
> You can only install gRPC if all the dependencies are set to gRPC_*_PROVIDER=package (i.e. they are preinstalled), if you use dependencies from submodules, installation will be disabled automatically (as there is no way to make that work with cmake).
> 
> Examples:
> https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.bat
> and
> 
> [grpc/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt](https://github.com/grpc/grpc/blob/04b78efb45ad93106f84a9293b1d21d8896ae526/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt#L78)
> 
> Line 78 in [04b78ef](/grpc/grpc/commit/04b78efb45ad93106f84a9293b1d21d8896ae526)
>  ExternalProject_Add(grpc

I left this problem for almost a month... Several days ago, I spend some time installing the dependencies, then grpc(with dependencies set to gRPC_*_PROVIDER=package). Thank you!!!
