### ISSUE TITLE
Bazel linking for C++ failed on external dependency based on gRPC v1.13.1

### ISSUE THREAD

**Issue by ravil23** [grpc/grpc#16776]
### What version of gRPC and what language are you using?
 gRPC 1.13.1 (C++)
 
### What operating system (Linux, Windows, …) and version?
 OS X
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel 0.17.2
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I  try to add external dependency by next code in my WORKSPACE file:
```
git_repository(
    name = "grpc",
    remote = "https://github.com/grpc/grpc.git",
    tag = "v1.13.1",
    init_submodules = True,
)
```

After that I run building of some library:
```
bazel build @grpc//:grpc_transport_inproc 
```
 
### What did you expect to see?

Building from gRPC repository succeeded:
```
INFO: Analysed target //:grpc_transport_inproc (0 packages loaded).
INFO: Found 1 target...
Target //:grpc_transport_inproc up-to-date:
  bazel-bin/libgrpc_transport_inproc.a
  bazel-bin/libgrpc_transport_inproc.so
INFO: Elapsed time: 0.706s, Critical Path: 0.17s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed successfully, 3 total actions
```
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target @grpc//:grpc_transport_inproc (9 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/BUILD:1628:1: Linking of rule '@grpc//:grpc_transport_inproc' failed (Exit 1)
ld: illegal thread local variable reference to regular symbol __ZN9grpc_core7ExecCtx9exec_ctx_E for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target @grpc//:grpc_transport_inproc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.334s, Critical Path: 0.45s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by nicolasnoble** [comment]
That's unfortunate... but I have no idea what's going on there. Our Bazel CI works fine otherwise.

Also, to be fair, I have never seen this error before.
