### ISSUE TITLE
.proto to .json

### ISSUE THREAD

**Issue by arturgontijo** [grpc/grpc#16815]
### What version of gRPC and what language are you using?
 1.14.2 (Python)
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.6.5
 
### What did you do?
I'm trying to "parse" the .proto and generate a .json.
 
### What did you expect to see?
 Something like pbjs does (but in Python).
 
### What did you see instead?
I couldn't find a clean way until now. Looking for some help on it.

**Comment by mehrdada** [comment]
I am not aware of a tool off the top of my head, but I recommend filing an issue on the google/protobuf issue tracker, as it is going to be more appropriately addressed there.
