### ISSUE TITLE
error `framework not found openssl` after update to GRPC 1.15.1 & BoringSSL 0.0.2

### ISSUE THREAD

**Issue by sibinlu** [grpc/grpc#16821]
### What version of gRPC and what language are you using?
 Objective-C Swift3
GRPC 1.15.1 
BoringSSL 0.0.2
 
### What operating system (Linux, Windows, …) and version?
 Xcode 10.0

### What did you do?
I use cocoapod to install a sdk (TokenSdk) which depends on GRPC. everything is all right before 1.15.1 release. After GRPC update to 1.15.1, an error
 `ld: framework not found openssl`
will be throw when I want to archive my project.

Currently I add `pod 'BoringSSL-GRPC', '0.0.1'` to avoid the pod update.

Podfile:

project 'Token', 'BetaDebug' => :debug, 'BetaAdhoc' => :release

def common_pods
    source 'https://github.com/CocoaPods/Specs.git'
    source 'https://github.com/tokenio/token-cocoa-pods.git'
    pod 'CocoaLumberjack/Swift'
    pod 'AFNetworking''
    pod 'Fabric'
    pod 'TokenSdk'
    pod 'Crashlytics'
    pod 'RealmSwift', '3.1.0'
    pod 'Localize-Swift'
    #pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
    #pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
    pod 'Bolts-Swift'
    pod 'Alamofire'
    pod 'CountryPicker'
    pod 'BugfenderSDK/ObjC'
    pod 'Firebase/Messaging'
    pod 'Firebase/Core'
    pod 'BoringSSL-GRPC', '0.0.1'
end
 
### What did you expect to see?
 Archive successfully
 
### What did you see instead?
 `ld: framework not found openssl`

Any idea why this happens?

**Comment by petard** [comment]
I have the same issue

**Comment by muxi** [comment]
@sibinlu @petard - what are the names of the pods that you are using? The reason was likely those pods you used were using BoringSSL that gRPC depended on, but they did not explicitly specify the dependency in their podspec. We recently renamed the BoringSSL lib to avoid conflict with other openssl libraries, which can cause issue in this case.

**Comment by petard** [comment]
From my pod file:
```
pod 'googleapis', :path => '.'
```
and the `googleapis` is defined in this [podspec for GCP](https://raw.githubusercontent.com/GoogleCloudPlatform/ios-docs-samples/master/speech/Swift/Speech-gRPC-Streaming/googleapis.podspec)

Locking the pod `pod 'BoringSSL-GRPC', '0.0.1'` works for me too.

**Comment by muxi** [comment]
@petard - thanks. And can you tell us which line did you fail on? I tried building `googleapis`; it seems building ok on my side.

**Comment by sibinlu** [comment]
@muxi Im using this sdk. https://github.com/tokenio/sdk-objc 
I tried to add `ss.dependency "BoringSSL-GRPC"` explicitly in sdk's Podspec but it don't work.
Building will not throw the error. Only archiving with xcode will have this issue.

**Comment by muxi** [comment]
@sibinlu - Sorry I actually meant archiving was ok on my side. Let me try your sdk.

**Comment by muxi** [comment]
@sibinlu - I also passed archiving tokensdk. I wonder if you have any `#include <openssl/...>` header in your project?

**Comment by sibinlu** [comment]
Hey @muxi , we don't have any `#include <openssl/...>` header in my project. 

The good news is that you remind me to check the xcode project file and I find that there is a setting `-framework openssl` in **Other Linker Flag**. After I update them to openssl_grpc, the archiving works.

My theory is that if you have worked with earlier version boringSSL, your project will explicitly have the openssl framework setting. Even after you update to the new version, for some reason the flag hasn't been changed. That explain why muxi don't have that issue on a new project.

If you link an earlier version (in my case that's TokenSdk 1.0.99) then switch to the new version (1.0.100), you will suffer that issue. @petard Hope this works for you too.

**Comment by muxi** [comment]
That makes sense. Thanks for the idea @sibinlu. By `update them to openssl_grpc`, did you do it manually in Xcode or did you regenerate using Cocoapods?

**Comment by sibinlu** [comment]
I did it manually.

**Comment by petard** [comment]
@sibinlu Awesome, changing the framework name `openssl_grpc` fixed it for me too. Great find!
