### ISSUE TITLE
Unity C#: Xcode reports libgrpc_csharp_ext.a does not contain bitcode

### ISSUE THREAD

**Issue by fbernaly** [grpc/grpc#16839]
### What version of gRPC and what language are you using?
I am using the experimental plugin for Unity  in C#. I followed the instruction [here](https://github.com/grpc/grpc/tree/master/src/csharp/experimental)

After exporting my Unity project to Xcode and compiling the exported project I am getting this error:

`
/../Libraries/Plugins/Grpc.Core/runtimes/ios/libgrpc_csharp_ext.a(grpc_csharp_ext.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
`
 
I am using Xcode 10, and deployment target: 11.2

**Comment by fbernaly** [comment]
@jtattermusch could you enabled bitcode for `libgrpc_csharp_ext.a` for iOS?

**Comment by jtattermusch** [comment]
@fbernaly  please note that pull requests with contributions are always welcome.

**Comment by re-polm** [comment]
I've fixed this by disabling the Bitcode option on the target. If you set it on it requires every static library to have it on, which includes grpc.

**Comment by fbernaly** [comment]
@re-polm: were you able to archive your app? what architectures are you using?

**Comment by re-polm** [comment]
arm64

**Comment by NickBullseye** [comment]
@fbernaly @jtattermusch I am getting the same error when building for iOS? Is there a version with bitcode enabled? Because I tried to build it myself, but could not do it so far. Thanks in advance.

**Comment by Inspekt2** [comment]
Have the same issue. Has somebody found a solution?

**Comment by akselilukkarila** [comment]
I have tried adding `-fembed-bitcode` flag to the _build_native_ext_for_ios.sh_ script and then build the runtime but bitcode is still not generated. Anybody have an idea how to get it to be generated?

**Comment by Inspekt2** [comment]
@akselilukkarila This solution works great for me. You have to add BuildHelper.cs to you project. Hope this can help.
https://qiita.com/shiena/items/6c3b34a8d8f1bb938470

**Comment by akselilukkarila** [comment]
> @akselilukkarila This solution works great for me. You have to add BuildHelper.cs to you project. Hope this can help.
> https://qiita.com/shiena/items/6c3b34a8d8f1bb938470

That just disables bitcode for iOS builds, which is the opposite of what we want to do.

**Comment by koshelevpavel** [comment]
> I have tried adding `-fembed-bitcode` flag to the _build_native_ext_for_ios.sh_ script and then build the runtime but bitcode is still not generated. Anybody have an idea how to get it to be generated?

It works for me. You have to delete folder 'objs' from root and run _build_native_ext_for_ios.sh_ 
I added `-fembed-bitcode` like this:
`CPPFLAGS="-O2 -Wframe-larger-than=16384 -arch $ARCH -fembed-bitcode -isysroot $(xcrun --sdk $SDK --show-sdk-path) -mios-version-min=6.0 -DPB_NO_PACKED_STRUCTS=1"`

**Comment by akselilukkarila** [comment]
> > I have tried adding `-fembed-bitcode` flag to the _build_native_ext_for_ios.sh_ script and then build the runtime but bitcode is still not generated. Anybody have an idea how to get it to be generated?
> 
> It works for me. You have to delete folder 'objs' from root and run _build_native_ext_for_ios.sh_
> I added `-fembed-bitcode` like this:
> `CPPFLAGS="-O2 -Wframe-larger-than=16384 -arch $ARCH -fembed-bitcode -isysroot $(xcrun --sdk $SDK --show-sdk-path) -mios-version-min=6.0 -DPB_NO_PACKED_STRUCTS=1"`

That worked! Thanks a lot :)
