### ISSUE TITLE
install step fails with `gRPC_BUILD_CODEGEN=OFF` 

### ISSUE THREAD

**Issue by sagamusix** [grpc/grpc#16856]
When `gRPC_BUILD_CODEGEN=OFF` , gRPC still tries to install some targets that are not built, for example grpc++_error_details, grpcc_reflection and grpcpp_channelz.

The respective blocks in CMakeLists.txt should probably start with `if (gRPC_INSTALL AND gRPC_BUILD_CODEGEN)` rather than just `if (gRPC_INSTALL)`.

**Comment by jtattermusch** [comment]
I'm not sure if we wan't to fragment the installation to support both values of `gRPC_BUILD_CODEGEN` (it adds extra complexity). What is the motivation for building with gRPC_BUILD_CODEGEN=OFF?

**Comment by sagamusix** [comment]
From what I remember, without `gRPC_BUILD_CODEGEN=OFF`, various targets don't (or didn't at the time this was reported) compile when cross-compiling e.g. for iOS arm64 on Darwin x64.

**Comment by JonasVautherin** [comment]
> I'm not sure if we wan't to fragment the installation to support both values of `gRPC_BUILD_CODEGEN`

I still need `gRPC_BUILD_CODEGEN=OFF` at least for Android (I can confirm that for iOS if you want).

But anyway I believe this is a bug: `gRPC_BUILD_CODEGEN=OFF` disable some builds, but not the corresponding installs.

> From what I remember, without `gRPC_BUILD_CODEGEN=OFF`, various targets don't (or didn't at the time this was reported) compile when cross-compiling e.g. for iOS arm64 on Darwin x64.

Yes, and Android as well, as far as I remember (it was around a year ago). I believe the idea was that Android/iOS don't really need to generate the code (i.e. the code is cross-compiled from a system that builds the codegen plugins). So it is valid to disable `gRPC_BUILD_CODEGEN` in those cases. That's my use-case at least.

**Comment by JonasVautherin** [comment]
After investigation, what I can see is that in CMakeLists.txt.template, [`<%def name="cc_library(lib)">`](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L373) conditionally sets [`if (gRPC_BUILD_CODEGEN)`](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L375) and [`endif (gRPC_BUILD_CODEGEN)`](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L471).

However, [in the places where `cc_library(...)` is used](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L327-L341), it is [sometimes](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L334) [used](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template#L339) in conjunction with `cc_install(...)`. Consequently, it seems to me like `cc_install(...)` should also conditionally disable `gRPC_BUILD_CODEGEN`.

I am proposing a fix in #18151.
