### ISSUE TITLE
How to assign address for add_insecure_port() and insecure_channel() for python example

### ISSUE THREAD

**Issue by jk78346** [grpc/grpc#16865]
I'm a beginer of grpc.
I had tried python/helloworld example with server and client both on local host, works fine.
Now I have two machines. In my setting, I have my PC and server connected via TCP protocol. 
Not sure what the address should be given.
I try:

    with grpc.insecure_channel('192.168.5.20:50051') as channel: #client side

and

    server.add_insecure_port('[::]:50051') #server side

But those are permission denied.
The main problem here is that I don't know exactly what the addresses should be (anything between two apostrophe's).
I'm sure that server and client can ping each other and TCP works fine.

**Comment by nicolasnoble** [comment]
If you're getting something like "permission denied", that's not necessarily something within gRPC's source code. But if you were to share the exact error code or message you're getting, that'd be much more useful, since with this current report, we can't really tell what's going on.

**Comment by jk78346** [comment]
After checking the IP address, I find out I misunderstand the IPs of each side. I simply place the clent's address on it's own side, not the server IP address. Here is something I originally not understand about TCP. So should not be an issue related to gprc. fixed it, thanks.
