### ISSUE TITLE
GCE detection on windows crashes with multiple processes.

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#16872]
### What version of gRPC and what language are you using?

1.14.1 with C++, but the problem is present on `master`  
 
### What operating system (Linux, Windows, …) and version?
 
 Windows.

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC 2017. 
 
### What did you do?

This is hard to reproduce. You need to run two (or more) gRPC clients more or less at the same time. One of the clients will crash.
 
### What did you expect to see?
 
The programs should all run as normal.
 
### What did you see instead?

The program crashes with:

```
E1013 00:19:57.764000000  4380 check_gcp_environment.cc:60] BIOS data file cannot be opened.
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] ClientOptionsTest.ClientOptionsDefaultSettings (2001 ms)
[ RUN      ] ClientOptionsTest.EditDataEndpoint
E1013 00:19:57.778000000  4380 sync_windows.cc:38] assertion failed: !mu->locked
        Start  13: cluster_config_test
```

### Anything else we should know about your project / environment?

I think the problem is here:

https://github.com/grpc/grpc/blob/07eecd8421314d62e8df33b14a33203864f91bee/src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc#L106

gRPC is using powershell to create a file (`windows.data`), note that if multiple programs start concurrently they will all create the same file.  After the file is created and parsed it is deleted. If one of the programs deletes the file before another concurrent program gets to read it the second would crash.

Probably the easiest fix is to read the stdout from `CreateProcess` directly:

https://docs.microsoft.com/en-us/windows/desktop/ProcThread/creating-a-child-process-with-redirected-input-and-output
https://stackoverflow.com/questions/35969730/how-to-read-output-from-cmd-exe-using-createprocess-and-createpipe

**Comment by coryan** [comment]
Ping, this is still a problem. Also the priority seems low.  A crash on a major platform seems like something you would want to fix.

**Comment by tmatsuo** [comment]
Ping and sub

**Comment by tmatsuo** [comment]
FWIW, even when we run the integration tests serially, we occasionally see this error. It's not very often, but in my opinion it's too often. I'd recommend you re-consider the priority.
