### ISSUE TITLE
Test coverage for adding callbacks to futures returned from Face API

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1687]
#1686 fixes a defect that such test coverage could long ago have exposed.

**Comment by nicolasnoble** [comment]
So since #1686 was merged, does that means this one is fixed ?

**Comment by nathanielmanistaatgoogle** [comment]
#1686 fixed the defect; this issue is about adding regression test coverage and should remain open for now.

**Comment by nathanielmanistaatgoogle** [comment]
The desired test coverage was added in 0c6177674a0474757ffdee37.
