### ISSUE TITLE
Assertion failure with C++ in perform_stream_op_locked

### ISSUE THREAD

**Issue by michihenning** [grpc/grpc#16876]
Opening this bug report after discussion on the grpc.io group:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/grpc-io/y4xE4C18c2c/Kjc2fXKyBQAJ

grpc compiled from source, latest commit: d8020cb6daa87f1a3bb3b0c299bc081c4a3de1e8
Ubuntu 16.04 with gcc 7.3.0, with --std=c++17 -g

Stack trace for crash: https://www.dropbox.com/s/n2494rjnhj0hq56/stack-trace.txt?dl=0

Tsan output: https://www.dropbox.com/s/7fkxdu3rmcji6eo/tsan.txt?dl=0

Following up on the original question, at times, I also see the code deadlocking. Basically, the whole grpc thing just stops and no more requests are processed; the writer thread gets stuck in its call to stream->Write(), and the whole show stops.

I've tried to reproduce with a trivial test case. Surprise, surprise, the crash doesn't show up there, presumably because the timings are different. (In my original code, other threads are doing all sorts of other things, and the race is fairly hard to hit.)

However, when I run the trivial test case (my code and grpc compiled with tsan), I see complaints from tsan on both client and server side. 

Client tsan output: https://www.dropbox.com/s/11rj4xcsj8t8zmr/client-tsan.txt?dl=0

Server tsan output: https://www.dropbox.com/s/3oqewm8qmd1o3a3/server-tsan.txt?dl=0

I had to run the code for quit a long time (several hours) on a Core i7-7700 machine (3.6 Ghz) before I hit the race.

This is the quick-and-dirty test case: https://www.dropbox.com/s/gqjpl4vqymllbcf/test-case.tar?dl=0

**Comment by michihenning** [comment]
I'm also seeing failures where the grpc runtime live-locks. My client writer thread gets stuck in a Write(), and no more messages flow. While in this state, some thread that's internal to grpc ends up spinning and consumes 100% CPU.

**Comment by hsaliak** [comment]
@yashykt could you please help take a look. /cc @vjpai @a11r

**Comment by yashykt** [comment]
My plate is full for the next few days. Assigning it to @sheenaqotj

**Comment by a11r** [comment]
I took a brief look at the test code and it looks like the test client is ignoring Read() and write() errors and continues to Read(0/Write() more. This will lead to undefined behavir as there is a requirement that once a Read or Write fails, subsequent attempts to Read or Write should not be made.

**Comment by a11r** [comment]
The best way to fix the test is for the client-side sender to just Finish() the RPC when it sees a failing Write(). It can then start a new RPC and resume Write() calls on it. 

If the application has long-lived session semantics, it would need to add enough data to each message to make resumption across RPCs possible.

Thanks

**Comment by michihenning** [comment]
What the code does when a write fails is irrelevant for this because no write() ever fails. When I run the code, it runs without ever encountering an error. But thread sanitizer complains about race conditions. This is with both gRPC and the test code compiled with g++-7 and thread sanitizer. There should not be any race conditions reported at all, and I suspect that these race conditions relate to hangs and crashes I'm seeing in my production code.

Here is a link to another archive. The code just calls _exit() if there is an error (but I don't see an error when the code runs).

Please compile this and gRPC with thread sanitizer and run it. You should see complaints from thread sanitizer, but it may take quite a while. (It took over an hour for me to get a bunch of complaints from tsan on a Core-i7 7700 machine.

[bug2.zip](https://github.com/grpc/grpc/files/2504575/bug2.zip)

**Comment by michihenning** [comment]
I left the code running for most of the day and overnight. Beside the tsan complaints, I got a segfault in the client. That was after the code had run between 7 and 20 hours. I've attached the stack trace. The thread that caused the fault is thread #3.

[gdb.txt](https://github.com/grpc/grpc/files/2512705/gdb.txt)

**Comment by yashykt** [comment]
This should be fixed after https://github.com/grpc/grpc/pull/18491
