### ISSUE TITLE
"*_nosec" end2end tests are not being run on foundry

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16881]
List of missing tests in the foundry runs
```
h2_census_nosec
h2_compress_nosec
h2_fd_nosec
h2_full+pipe_nosec
h2_full+trace
h2_full+trace_nosec
h2_full+workarounds_nosec
h2_full_nosec
h2_http_proxy_nosec
h2_proxy_nosec
h2_sockpair+trace
h2_sockpair+trace_nosec
h2_sockpair_1byte_nosec
h2_sockpair_nosec
h2_ssl_cert
h2_uds_nosec
```

while on kokoro there are these tests:
https://source.cloud.google.com/results/invocations/a86610dc-f214-499d-aa5d-7e7e2aa3bdb3/targets/github%2Fgrpc%2Fc_linux_dbg_native/tests;query=_nosec

Likely root cause is that https://github.com/grpc/grpc/blob/d0cb61eada9d270b9043ec866b55c88617d362be/test/core/end2end/generate_tests.bzl   is missing a group of _nosec tests mentioned here:
https://github.com/grpc/grpc/blob/d0cb61eada9d270b9043ec866b55c88617d362be/test/core/end2end/gen_build_yaml.py#L316
or here:
https://github.com/grpc/grpc/blob/d0cb61eada9d270b9043ec866b55c88617d362be/test/core/end2end/gen_build_yaml.py#L346

**Comment by jtattermusch** [comment]
@billfeng327 as you have experience with the generated bazel tests, can you please take a look and fix?

**Comment by billfeng327** [comment]
resolved by PR [16965](https://github.com/grpc/grpc/pull/16965)
