### ISSUE TITLE
Unity: HoloLens and gRPC C#: "System.AppDomain" doesn't exist in target framework

### ISSUE THREAD

**Issue by vgarciavazquez** [grpc/grpc#16909]
I was trying to develop an application in HoloLens using Unity but it does not work. I followed the steps detailed in https://github.com/grpc/grpc/tree/master/src/csharp/experimental to use gRPC in Unity (grpc_unity_package.1.17.0-dev.zip). The application works in Unity Editor (version 2018.2.8f1). However, when I build the application in Unity to generate the Visual Studio Solution for HoloLens I get some errors such as:

```
Reference rewriter: Error: type `System.AppDomain` doesn't exist in target framework. It is referenced from Grpc.Core.dll at System.Void Grpc.Core.GrpcEnvironment/ShutdownHooks::Register().
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1058)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:208)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Any idea to solve this problem?

**Comment by vgarciavazquez** [comment]
In Unity, the SDK for the Universal Windows Platform selected was 10.0.16299.0

**Comment by AtosNicoS** [comment]
With urhosharp we were able to use grpc on the hololense. You might want to try that out.

**Comment by jtattermusch** [comment]
@vgarciavazquez  interesting. The target framework used by gRPC C# Unity support is net45, so the type `System.AppDomain`, should be available, because it's part of net45.
