### ISSUE TITLE
grpc cross compile process to get static lib has issues for QNX OS

### ISSUE THREAD

**Issue by bakkiraju** [grpc/grpc#16918]
### What version of gRPC and what language are you using?
Latest top of the tree , c++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 qcc 
 
### What did you do?
Figured out from documentation and discussions here that cmake was the best option for cross compiling and created the file qnx_toolchain.cmake

Contents of qnx_toolchain.cmake   
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_CROSSCOMPILING 1)
set(arch gcc_ntoarmv7le)

set(CMAKE_C_COMPILER qcc)
set(CMAKE_C_COMPILER_TARGET ${arch})
set(CMAKE_CXX_COMPILER QCC)
set(CMAKE_CXX_COMPILER_TARGET ${arch})
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
 
mkdir build && cd build 

cmake -DCMAKE_TOOLCHAIN_FILE=../qnx_toolchain.cmake -DCMAKE_CROSSCOMPILING=1 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0 -DRUN_HAVE_STEADY_CLOCK=0 -DCMAKE_SYSTEM_PROCESSOR=armv7-le ..

### What did you expect to see?
Expect the build to go through and see  libgrpc.a static library
 
### What did you see instead?
 [  0%] Building CXX object CMakeFiles/gen_legal_metadata_characters.dir/tools/codegen/core/gen_legal_metadata_characters.cc.o
[  0%] Linking CXX executable gen_legal_metadata_characters
/home/user1/qnx700/host/linux/x86_64/usr/bin/arm-unknown-nto-qnx7.0.0eabi-ld: cannot find -lrt
/home/user1/qnx700/host/linux/x86_64/usr/bin/arm-unknown-nto-qnx7.0.0eabi-ld: cannot find -lpthread
cc: /home/user1/qnx700/host/linux/x86_64/usr/bin/arm-unknown-nto-qnx7.0.0eabi-ld error 1
CMakeFiles/gen_legal_metadata_characters.dir/build.make:94: recipe for target 'gen_legal_metadata_characters' failed
make[2]: *** [gen_legal_metadata_characters] Error 1

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
On QNX linking to pthread library comes from including -lc flag, so I went in and edited the following file
CMakeFiles/gen_legal_metadata_characters.dir/link.txt 

which helped me to move forward but I got another issue with 

[  0%] Building C object third_party/boringssl/crypto/CMakeFiles/crypto_base.dir/refcount_lock.c.o
In file included from /home/user1/grpc/third_party/boringssl/crypto/refcount_lock.c:15:0:
/home/user1/grpc/third_party/boringssl/crypto/internal.h:446:36: error: 'PTHREAD_RWLOCK_INITIALIZER' undeclared here (not in a function)
 #define CRYPTO_STATIC_MUTEX_INIT { PTHREAD_RWLOCK_INITIALIZER }

 Looks like QNX  cross-compiling is getting messed up  because of something related to pthread lib and headers, dont know what and how to fix it.  A recipe for cross compiling in general would be helpful, otherwise average users like me who rarely have to build stuff from source code will have really hard time figuring out stuff

**Comment by jtattermusch** [comment]
QNX OS is not something we officially support, so I'd expect some friction. We could take a look but we should not do any work beyond supporting crosscompilation and cmake crosscompilation toolchains in general.
