### ISSUE TITLE
Arm support for windows (e.g. windows iot core on a raspberry pi 3b+)

### ISSUE THREAD

**Issue by andre-laskawy** [grpc/grpc#16929]
After weeks of digging through the grpc code and its submodules, i finally made it to crosscompile the grpc_csharp_ext for ARM architectures on a windos based system (For example if you want to run grpc on a raspery pi with windows iot core). 

To finally make it work i still had to add the following to the charp code:

Inside the PlatformApis.cs i had to add a method to check for a arm architecture:

```
public static bool IsArm
        {
            get
            {
                PortableExecutableKinds peKind;
                ImageFileMachine machine;
                typeof(object).Module.GetPEKind(out peKind, out machine);
                return machine == ImageFileMachine.ARM;
            }
        }
```
Inside the UnmanagedLibrary.cs i had to integrate the check during the LoadSymbol method:

```
private IntPtr LoadSymbol(string symbolName)
        {
            if (PlatformApis.IsWindows)
            {
                // See http://stackoverflow.com/questions/10473310 for background on this.
                if (PlatformApis.Is64Bit || (PlatformApis.IsWindows && PlatformApis.IsArm))
                {
                    return Windows.GetProcAddress(this.handle, symbolName);
                }
                ....
```
@jtattermusch 
Would be nice if you could integrated this inside the next versions.

**Comment by jtattermusch** [comment]
@andre-laskawy   if you have code to contribute, please create a PR, copy pasting the code that you want added into an issue so that someone else needs to take that code a create a PR from what you copy pasted is waste of everyone's time.

Also, I'm afraid for windows ARM support we'd need some way to test this, before we claim that your snippet is useful. Do you have a document describing how to crosscompile for windows ARM?

**Comment by jtattermusch** [comment]
Can you please post the entire howto for crosscompiling on ARM? Also for code changes, please create a PR.

**Comment by andre-laskawy** [comment]
PR here: https://github.com/grpc/grpc/pull/16987

It just includes the essential changes inside the grpc core c# code for a potential arm support. 
Be aware i had to change to netstandard2.0 to check for arm architecture inside the code (it should be upgraded anyway in my opinion). 

The changes needed to cross compile on linux for arm i will document here, becuase they probably not production ready. 
I was basically just hacking through the code until it was building.
So what i did:

1. Add the following line on the top of src/csharp/ext/grpc_csharp_ext.c

		#pragma comment(lib, "advapi32")

2. Go to the submodule boringssl to the file crypto/thread_win.c and remove the else part of
	
		#ifdef _WIN64
		#pragma comment(linker, "/INCLUDE:_tls_used")
		#pragma comment(linker, "/INCLUDE:p_thread_callback_boringssl")
		#else
		#pragma comment(linker, "/INCLUDE:__tls_used")
		#pragma comment(linker, "/INCLUDE:_p_thread_callback_boringssl")
		#endif
		
		change to:
		
		#ifdef _WIN64
		#pragma comment(linker, "/INCLUDE:_tls_used")
		#pragma comment(linker, "/INCLUDE:p_thread_callback_boringssl")
		#endif

4. Go to the submodule boringssl to the CMakeLists.txt and remove the following lines 165 and 166 (the werror stuff)
	
		set(CMAKE_C_FLAGS   "-utf-8 -Wall -WX ${MSVC_DISABLED_WARNINGS_STR} ${MSVC_LEVEL4_WARNINGS_STR}")
		set(CMAKE_CXX_FLAGS "-utf-8 -Wall -WX ${MSVC_DISABLED_WARNINGS_STR} ${MSVC_LEVEL4_WARNINGS_STR}")
		
2. Go to the submodule boringssl to the file crypto/cpu-arm-linux.c

	- remove #include <stdlib.h> at line 23
	
	- Add the following to beneath line 26 (#include "internal.h") -> For detailed infiormation see here: https://stackoverflow.com/a/826027/1202830

		#ifndef _UNISTD_H
		#define _UNISTD_H 1

		/* This is intended as a drop-in replacement for unistd.h on Windows.
		 * Please add functionality as neeeded.
		 * https://stackoverflow.com/a/826027/1202830
		 */

		#include <direct.h> /* for _getcwd() and _chdir() */
		#include <io.h>
		#include <process.h> /* for getpid() and the exec..() family */
		#include <stdlib.h>

		#define srandom srand
		#define random rand

		/* Values for the second argument to access.
		   These may be OR'd together.  */
		#define R_OK 4 /* Test for read permission.  */
		#define W_OK 2 /* Test for write permission.  */
		//#define   X_OK    1       /* execute permission - unsupported in windows*/
		#define F_OK 0 /* Test for existence.  */

		#define access _access
		#define dup2 _dup2
		#define execve _execve
		#define ftruncate _chsize
		#define unlink _unlink
		#define fileno _fileno
		#define getcwd _getcwd
		#define chdir _chdir
		#define isatty _isatty
		#define lseek _lseek
		/* read, write, and close are NOT being #defined here, because while there are
		 * file handle specific versions for Windows, they probably don't work for
		 * sockets. You need to look at your app and consider whether to call e.g.
		 * closesocket(). */

		#ifdef _WIN64
		#define ssize_t __int64
		#else
		#define ssize_t long
		#endif

		#define STDIN_FILENO 0
		#define STDOUT_FILENO 1
		#define STDERR_FILENO 2
		/* should be in some equivalent to <sys/types.h> */
		typedef __int8 int8_t;
		typedef __int16 int16_t;
		typedef __int32 int32_t;
		typedef __int64 int64_t;
		typedef unsigned __int8 uint8_t;
		typedef unsigned __int16 uint16_t;
		typedef unsigned __int32 uint32_t;
		typedef unsigned __int64 uint64_t;

		#endif /* unistd.h  */

		/* This file intended to serve as a drop-in replacement for
		 *  unistd.h on Windows.
		 *  Please add functionality as neeeded.
		 *  Original file from: http://stackoverflow.com/a/826027
		 */

		#include <direct.h> /* for _getcwd() and _chdir() */
		#include <io.h>
		#include <process.h> /* for getpid() and the exec..() family */
		#include <stdlib.h>

		#define srandom srand
		#define random rand

		/* Values for the second argument to access.
		   These may be OR'd together.  */
		#define R_OK 4 /* Test for read permission.  */
		#define W_OK 2 /* Test for write permission.  */
		#define X_OK                                                   \
		  R_OK         /* execute permission - unsupported in Windows, \
						  use R_OK instead. */
		#define F_OK 0 /* Test for existence.  */

		#define access _access
		#define dup2 _dup2
		#define execve _execve
		#define ftruncate _chsize
		#define unlink _unlink
		#define fileno _fileno
		#define getcwd _getcwd
		#define chdir _chdir
		#define isatty _isatty
		#define lseek _lseek
		/* read, write, and close are NOT being #defined here,
		 * because while there are file handle specific versions for Windows,
		 * they probably don't work for sockets.
		 * You need to look at your app and consider whether
		 * to call e.g. closesocket().
		 */

		#define ssize_t int

		#define STDIN_FILENO 0
		#define STDOUT_FILENO 1
		#define STDERR_FILENO 2
		/* should be in some equivalent to <sys/types.h> */
		typedef __int8 int8_t;
		typedef __int16 int16_t;
		typedef __int32 int32_t;
		typedef __int64 int64_t;
		typedef unsigned __int8 uint8_t;
		typedef unsigned __int16 uint16_t;
		typedef unsigned __int32 uint32_t;
		typedef unsigned __int64 uint64_t;

		#endif /* unistd.h  */


3. inside the grpc do mkdir _build / cd _build and run 
	cmake ../ -G "Visual Studio 15 2017 ARM" -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_GNU_POSIX_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0 -DRUN_HAVE_STEADY_CLOCK=0
	
	* you need to install all c++ stuff from the visual studio setup (i also installed the windows driver kit, dont know it this is really necessary)
	
4. afterwards i just did a cmake --build . 
The build finished with errors, but the grpc_csharp_ext.dll was created anyway. 
I tried the lib already on my raspberry pi 3 b+, and the client now is already running for a whole week without any errors. 
So works in my machine ;)

**Comment by DevJohnC** [comment]
+1 for an ARMv6 version of the C#->C core gRPC library. Providing a built library for ARMv6 would allow gRPC to run on C# in situations where the ASPNET Core version can't run (ie, rpi version 1 and the "zero" edition) because dotnet core requires ARMv7.

**Comment by jtattermusch** [comment]
I think for Grpc.Core, making things work once would be possible, but the challenge ensuring that this won't get broken in the future (we'd need a continuous test, which is hard to ensure for ARM v6 raspberry pi hardware)

**Comment by jtattermusch** [comment]
Btw, I think you might be more lucky running on raspberry pi when using linux - I think we're building some ARMv6 artifacts for linux, so perhaps the C-core build on armv6 linux  will work just fine. gRPC C# works both on linux and windows.

**Comment by jtattermusch** [comment]
We don't have plans to support ARM for the windows platform (partially also because we don't have a good way of testing that).
