### ISSUE TITLE
Python grpc server.start() do not complain about port already in use

### ISSUE THREAD

**Issue by rosun82** [grpc/grpc#16920]
### What version of gRPC and what language are you using?
 
1.8

### What operating system (Linux, Windows, …) and version?
 
Mac

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

When a port is already in use, server.start() just continues like nothing happens, no exception, not even a log message. It is almost impossible to know whether the server is already running or it is just pretending to be running.
 
### What did you expect to see?

An exception, something like PortNotAvailable.
 
### What did you see instead?

Nothing.
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by mehrdada** [comment]
@rosun82 gRPC Python unlike gRPC C++ binds to the endpoint on `add_[in]secure_port` and not on `start`. It does not throw an exception when it fails, rather it returns 0 instead of the correct port number.

**Comment by lidizheng** [comment]
By default, the underlying C layer of gRPC will bind the port with the option `SO_REUSEPORT`. It allows multiple servers (processes or threads) to bind to the same port if they all enabled this option. It provides potential scalability for gRPC servers. [Learn more](https://lwn.net/Articles/542629/)

Please mind that gRPC server default will bind with IPv6. So if your machine has another process using the same port but IPv4, the kernel will not throw an error hence you wouldn't get an exception.

For more actionable detail, you can add this option by 
```
server = grpc.server(thread_pool, options=(('grpc.so_reuseport', 0),))
```
 There is an detailed example, please check [here](https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/python/grpcio_tests/tests/unit/_channel_connectivity_test.py#L86).

If you have any more questions, please reopen this issue.
