### ISSUE TITLE
Backward compatibility test matrix will not work for new grpc-go releases as of December 4th

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc#16928]
Filing this as a follow-up from #16908, which addressed this issue in the ongoing interop tests.

The backward compatibility scripts assume all versions of grpc-go should be tested with Go 1.7 and 1.8.  However, the 1.7 release of grpc-go will no longer support these versions of Go.  We need a way to build and test docker images using arbitrary combinations of Go version & grpc-go version.

**Comment by jtattermusch** [comment]
I've verified manually that the v1.17.0 interop tests are passing with docker images with go 1.11 using a modified version of create_matrix_images.py (https://github.com/grpc/grpc/blob/master/tools/interop_matrix/README.md).
I have an in-progress PR to allow disabling specific runtimes for different version tags, but I'd still want to give it a bit more thought and I don't want to commit a half-baked solution.
I'll be OOO starting from tomorrow (until Dec 17), so I will finish up the PR after that.
