### ISSUE TITLE
Debug APIs for getting connection parameters

### ISSUE THREAD

**Issue by rahulpr2708** [grpc/grpc#16954]
### What version of gRPC and what language are you using?
 1.3.0, C++
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang 3.7
 
### What did you do?
We run a grpc server on our device. Currently for debugging any grpc performance related issues, we are using the grpc traces. These give a very good amount of debug information. But these traces are too verbose and enabling them dump way too much of information. Enabling these traces on a live system is not recommended because of this.
 
### What did you expect to see?
 Would be helpful if there is some way to get the health of the connection parameters at run time via some APIs. Things needed for these are the current http window size of the server and the stream windows and the max and the min values that these parameters have taken during the time the connection is active. Other information like the initial connection window size, client grpc version, language etc. can also be added to this.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

/cc @robjs@google.com

**Comment by ncteisen** [comment]
I thiknk you may be interested in the channelz feature: https://github.com/grpc/proposal/blob/master/A14-channelz.md

It is currently in development
