### ISSUE TITLE
C# plugin doesn't compile with Ubuntu precise.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1695]
Got that one when trying out of fix for protobuf under gcc-4.8 and gcc-4.6:

```
[HOSTCXX] Compiling src/compiler/csharp_generator.cc
src/compiler/csharp_generator.cc: In function 'std::string grpc_csharp_generator::{anonymous}::GetFileNamespace(const FileDescriptor*)':
src/compiler/csharp_generator.cc:67:23: error: 'const class google::protobuf::FileOptions' has no member named 'has_csharp_namespace'
src/compiler/csharp_generator.cc:68:28: error: 'const class google::protobuf::FileOptions' has no member named 'csharp_namespace'
make: *** [objs/opt/src/compiler/csharp_generator.o] Error 1
root@23ea38de1900:/grpc# gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This happens on a fresh docker image:

```
$ docker run -t -i ubuntu:precise bash -l
root@23ea38de1900:/# apt-get update
root@23ea38de1900:/# apt-get dist-upgrade
root@23ea38de1900:/# apt-get install git build-essential autoconf libtool curl wget unzip
root@23ea38de1900:/# git clone --recursive git@github.com:nicolasnoble/grpc.git
root@23ea38de1900:/# cd grpc/
root@23ea38de1900:/grpc# git checkout origin/protobuf-4.8 # this is the branch for my PR
root@23ea38de1900:/grpc# make
```

**Comment by nicolasnoble** [comment]
Ignore this - that last test I didn't have the proper protobuf branch checked out.

**Comment by fta1** [comment]
I see the same error while building grpc master (fdc9af8dc as of now) with protobuf 3.0.0-alpha-2 (which works fine with grpc release-0_6_0). I'm quite sure I don't have any other protobuf is the system, as it's a docker image.

**Comment by fta1** [comment]
..and apparently, protobuf 3.0.0-alpha-2 doesn't have csharp_namespace anywhere.
Does grpc need an even newer protobuf ??

**Comment by jtattermusch** [comment]
yes, grpc_csharp_plugin depends on version of protobufs that has c# support. Which was added after 3.0.0-alpha-2. so for now, you need to use head of protobuf to compile the latest version of grpc. This will get once a new version of protobuf is released (= very soon).
