### ISSUE TITLE
node_generator does not use upstream sources

### ISSUE THREAD

**Issue by vmax** [grpc/grpc#16956]
### What version of gRPC and what language are you using?

`340bffa55560f02944dd81413aa764081a60f329`

### What operating system (Linux, Windows, …) and version?
 
macOS 10.14
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
```
ghost:grpc vmax$ clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
 
### What did you do?
Updated `node_generator.cc` in [grpc/grpc-node](https://github.com/grpc/grpc-node) repo
 
### What did you expect to see?
Updated plugin behaviour when using `grpc/grpc`
 
### What did you see instead?

`node_generator` source are vendored-in [here](https://github.com/grpc/grpc/tree/master/src/compiler)
 
### Anything else we should know about your project / environment?

I'm going to work on making `grpc/grpc` use generator plugin from `grpc/grpc-node`. Any advice on how to best approach it?

**Comment by murgatroid99** [comment]
Can you explain a little more what exactly you are trying to do here?

Also, I want to clarify that the node generator code is not vendored into `src/compiler`. Rather, it has been moved from `src/compiler` to the grpc-node repo, and we have not completed the second step of that process, which is deleting the original copies.

**Comment by vmax** [comment]
@murgatroid99 
goal: I need [this commit](https://github.com/grpc/grpc-node/commit/0aedb0768ca8986864be60eb8f89536bebcd2e51) to be available on [`grpc/grpc`](https://github.com/grpc/grpc) because that's what [`pubref/rules_proto`](https://github.com/pubref/rules_proto/blob/master/deps.bzl#L64-L68) is using to integrate gRPC with `bazel` projects

implementation detail: I'm trying to get sources from `grpc/grpc-node` to build the generator and plugin together in `grpc/grpc`

shortest way of achieving the goal will probably be syncronizing `node_generator.cc` file in this repo with `grpc/grpc-node` 

what's the plan for sources removal from `grpc/grpc`?

**Comment by murgatroid99** [comment]
Moving forward, it seems like the best solution would be to have a BUILD file in grpc/grpc-node to build the plugin, and then you can depend on that directly.
