### ISSUE TITLE
async streaming ping-pong benchmark failed on Travis

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1697]
Missed the log, but asserting !cc->shutdown... So probably starting an op after cq shutdown.

**Comment by ctiller** [comment]
@vjpai @dgquintas 

```c
    bool read_done(bool ok) {
      if (ok) {
        // invoke the method
        ResponseType response;
        // Call the RPC processing function
        grpc::Status status = invoke_method_(&req_, &response);
        // initiate the write
        stream_.Write(response, AsyncQpsServerTest::tag(this));
        next_state_ = &ServerRpcContextStreamingImpl::write_done;
      } else {  // client has sent writes done
        // finish the stream
        stream_.Finish(Status::OK, AsyncQpsServerTest::tag(this));
        next_state_ = &ServerRpcContextStreamingImpl::finish_done;
      }
      return true;
    }
    bool write_done(bool ok) {
      // now go back and get another streaming read!
      if (ok) {
        stream_.Read(&req_, AsyncQpsServerTest::tag(this));
        next_state_ = &ServerRpcContextStreamingImpl::read_done;
      } else {
        stream_.Finish(Status::OK, AsyncQpsServerTest::tag(this));
        next_state_ = &ServerRpcContextStreamingImpl::finish_done;
      }
      return true;
    }
```

In these functions, Shutdown() may have already been called on the server, at which point we're not allowed to call grpc_call_start_batch (which stream_.{Read,Write,Finish} do).

I can think of a dozen fixes, none of which I like - anyone want to chat?

**Comment by jayantkolhe** [comment]
I can repro this locally by  ./tools/run_tests/run_tests.py -t -c opt -l c c++ -n 100

**Comment by jayantkolhe** [comment]
Relevant Log:
START: bins/opt/async_unary_ping_pong_test
...
E0521 16:34:57.580726962    1694 completion_queue.c:151] assertion failed: !cc->shutdown
FAILED: bins/opt/async_streaming_ping_pong_test [ret=-6, pid=1664]

**Comment by ctiller** [comment]
Didn't tag the fix properly. It should be merged soon.

**Comment by nicolasnoble** [comment]
The fix WAS merged in for this one, correct ?

**Comment by ctiller** [comment]
Right.

**Comment by nicolasnoble** [comment]
Closing then.
