### ISSUE TITLE
Upgrade pip to 18.1 (or later)

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#16970]
Currently we pin `pip` to 10.0.1 but newer versions are available. We should upgrade our tests to pin on a newer pip.

**Comment by lanolunip** [comment]
Maybe u shuld considering logged in as super user first and then try to install it 
-----------------------------
`su`
`pip install -U pip' (if its python 2.x) 
or
`pip3 install -U pip` (if its python 3.x) 
----------------------------
it's worked for me

**Comment by mehrdada** [comment]
@lanolunip correct. This is an issue to track updating the pip version that we pin for our test infrastructure to run. We do want to pin to an exact version of pip to ensure are tests are robust and reproducible and won't break when pip updates ship, but we need to manually update the pinned version on a regular basis.

**Comment by lanolunip** [comment]
ah.. i see
