### ISSUE TITLE
Getting error while making GRPC call 

### ISSUE THREAD

**Issue by Vicky4** [grpc/grpc#16978]
### What version of gRPC and what language are you using?

 grpc : 
Language : Objective c 
 
### What operating system (Linux, Windows, …) and version?
macos Sierra (10.12)

 
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Simply calling the GRPCProtoCall in which sending request and recieving data back. 

   Synchronicity *client = [[Synchronicity alloc] initWithHost:HOST_URL]; 
    StreamDataBytes * request = [StreamDataBytes message];
    request.content=imageData;
    
 GRPCProtoCall *call =  [client RPCToSimpleRPCBytesWithRequestsWriter:[GRXWriter writerWithValue:request] eventHandler:^(BOOL done, StreamDataResponseBytes * _Nullable response, NSError * _Nullable error)

 
### What did you expect to see?
It should work properly. 

### What did you see instead?
This error i recieved 

NSDebugDescription={"created":"@1540318942.296673000","description":"Error received from peer","file":"/Users/vickysharma/SimpleCameraApp/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"EOF","grpc_status":2},
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by muxi** [comment]
I think it should work if you create the writer with `[GRXWriter writerWithValue:[request data]]`.
