### ISSUE TITLE
Cannot use OpenCensus + gRPC 1.16.0 with default Bazel options.

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#16989]
### What version of gRPC and what language are you using?

gRPC-1.16.0 with C++. 
 
### What operating system (Linux, Windows, …) and version?
 
Linux, Debian
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

g++ (Debian 7.3.0-5) 7.3.0

But I think this does not depends on the compiler. 
 
### What did you do?

Try to compile gRPC-1.16.0, particularly the OpenCensus plugin, with Bazel, but it fails with:

```
bazel build //:all
INFO: SHA256 (https://github.com/abseil/abseil-cpp/archive/cd95e71df6eaf8f2a282b1da556c2cf1c9b09207.tar.gz) = 8d6d1d6609ba9d77b3663278091643798f670d5128e0e72bf579187269281516
INFO: SHA256 (https://github.com/census-instrumentation/opencensus-cpp/archive/fdf0f308b1631bb4a942e32ba5d22536a6170274.tar.gz) = c3a0a760759420645699140f0f7124605177a12ce0b8a2379946973771473c5d
INFO: Analysed target //:test (18 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/d995bb9e9900bc0e725140e74b62b9bc/external/com_github_grpc_grpc/BUILD:2137:1: C++ compilation of rule '@com_github_grpc_grpc//:grpc_opencensus_plugin' failed (Exit 1)
In file included from external/com_github_grpc_grpc/src/cpp/ext/filters/census/grpc_plugin.h:25:0,
                 from external/com_github_grpc_grpc/src/cpp/ext/filters/census/measures.h:25,
                 from external/com_github_grpc_grpc/src/cpp/ext/filters/census/measures.cc:21:
external/com_github_grpc_grpc/include/grpcpp/opencensus.h:23:2: error: #error OpenCensus for gRPC is only supported when building with bazel.
 #error OpenCensus for gRPC is only supported when building with bazel.
  ^~~~~
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.665s, Critical Path: 1.15s
INFO: 12 processes: 12 linux-sandbox.
FAILED: Build did NOT complete successfully
```
 
### What did you expect to see?

A sucessful build. 
 
### What did you see instead?
 
The failure shown above. I used the attached `WORKSPACE`, `BUILD` and `test.cc` files to reproduce the problem.

[repro.tar.gz](https://github.com/grpc/grpc/files/2511885/repro.tar.gz)
 
### Anything else we should know about your project / environment?

Do not think so.

**Comment by coryan** [comment]
Ping.

**Comment by coryan** [comment]
AFAIK this remains a problem.

**Comment by coryan** [comment]
And continues to be a problem. Why do I have to remind the gRPC team of these things?  If you have no plans to fix something can you just say "Won't Fix" or something?

**Comment by jtattermusch** [comment]
We'd love to have this fixed but unfortunately can't find the cycles to fix. I applied the "help wanted" label to make it clear that we'd like to accept a PR that fixes that. (But for now we unfortunately have no plans to work on this).

**Comment by veblush** [comment]
It's an really old. When I tried to build this with gRPC 1.47.1, it worked. So I think we can call this is fixed?

**Comment by coryan** [comment]
I think we can, thanks for checking.
