### ISSUE TITLE
bins/opt/chttp2_socket_pair_with_grpc_trace_invoke_large_request_unsecure_test (and others) fail on master

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#1698]
SHA: faff1ca
Am I the only one or is master broken?

**Comment by ctiller** [comment]
invoke large request is just broken. We disabled it on Travis. I'll fix it
soon (with the test rewrite forced by removing the backup poller).

**Comment by jboeuf** [comment]
ah, OK, I think you actually told me about this test before. I'll merge master my server auth context branch then so that it can be merged back when you're OK with it.
