### ISSUE TITLE
RST_STREAM on HTTP/2 half-close with Python client but not Go client

### ISSUE THREAD

**Issue by cdelguercio** [grpc/grpc#16981]
### What version of gRPC and what language are you using?
1.15.0 Python
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 18.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.6.6
 
### What did you do?
I have a server side streaming endpoint that is being proxied through Envoy.

### What did you expect to see?
No errors.
 
### What did you see instead?
Under certain circumstances the client will receive a "RST_STREAM with error code 0" "grpc_status: 13". The most consistent way that I trigger the error is by streaming a lot of data and then turning off the stream for a few seconds. It is similar to what is outlined here: https://github.com/envoyproxy/envoy/issues/3724 but in my case it is unidirectional streaming from the server only. Also, my application sends a heartbeat empty message every 5 seconds so that the response stream is never idle. (so it's not a server timeout issue)

The envoyproxy/envoy issue suggests a fix with Envoy, but I DON'T see this issue with my Golang client (which uses grpc/grpc-go). I'm wondering if there is something different about how the grpc client is implemented in Python over the Go implementation which is causing this issue?

Any help is greatly appreciated.

**Comment by srini100** [comment]
@cdelguercio, is it possible to try the same without the proxy in the middle? 
@menghanl, any idea why this would work for grpc-go client when Envoy is resetting the stream upon half close.

**Comment by menghanl** [comment]
It seems weird to me that golang client is not affected.
If the proxy always resets half-closed streams, maybe the golang client sends something to the proxy that makes the proxy believe the stream is not half-closed?

@cdelguercio  Can you share more information about what you did in the python client and the golang client?

**Comment by menghanl** [comment]
I just tried locally, and confirmed that even for a golang client (with a server streaming RPC so the client does half-close), envoy also resets the stream after 15 seconds. I used the same config from https://github.com/envoyproxy/envoy/issues/3724.
