### ISSUE TITLE
gRPC 1.16.0 Segmentation fault on hello world example running under WSL

### ISSUE THREAD

**Issue by baboyo** [grpc/grpc#16998]
### What version of gRPC and what language are you using?
 gRPC v1.16.0 c++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04 WSL (also tried the same under Debian/GNU)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc  6.3.0 (also tried with gcc 7.3.0)
 
### What did you do?
Compiled and installed gRPC 1.16.0 with cmake according to `test/distrib/cpp/run_distrib_test_cmake.sh`. 
Secondly I started the "greeter_server" located in the "test/cpp/helloworld" example

>  ./greeter_server
 
### What did you expect to see?
E1025 10:44:05.609210900    1414 socket_utils_common_posix.cc:198] check for SO_REUSEPORT: {"created":"@1540457045.609141900","description":"OS Error","errno":92,"file":"/home/developer/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":175,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E1025 10:44:05.611697100    1414 server_chttp2.cc:40]    
Server listening on 0.0.0.0:50051

Note; Error message is likely related to the SO_REUSEPORT issue under WSL (issue #13517).
 
### What did you see instead?
E1025 10:44:05.609210900    1414 socket_utils_common_posix.cc:198] check for SO_REUSEPORT: {"created":"@1540457045.609141900","description":"OS Error","errno":92,"file":"/home/developer/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":175,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E1025 10:44:05.611697100    1414 server_chttp2.cc:40]        {"created":"@1540457045.611636300","description":"No address added out of total 1 resolved","file":"/home/developer/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":321,"referenced_errors":[{"created":"@1540457045.611627100","description":"Failed to add any wildcard listeners","file":"/home/developer/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":324,"referenced_errors":[{"created":"@1540457045.611546000","description":"Unable to configure socket","fd":5,"file":"/home/developer/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1540457045.611533400","description":"OS Error","errno":92,"file":"/home/developer/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":299,"os_error":"Protocol not available","syscall":"setsockopt(TCP_USER_TIMEOUT)"}]},{"created":"@1540457045.611625200","description":"Unable to configure socket","fd":5,"file":"/home/developer/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1540457045.611615100","description":"OS Error","errno":92,"file":"/home/developer/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":299,"os_error":"Protocol not available","syscall":"setsockopt(TCP_USER_TIMEOUT)"}]}]}]}
Server listening on 0.0.0.0:50051
Segmentation fault (core dumped)
 
### Anything else we should know about your project / environment?

The hello world server example was still working in gRPC v1.15.1 on WSL despite the SO_REUSEPORT (issue #13517). Maybe both the WSL server and new socket default time out implementation are related to this issue. 

I could not reproduce this issue on a native (non WSL) ubuntu (16.04) machine. There, the hello world example is running perfectly fine. 

Disabling the "tcp_user_timeout_enabled" (manually) seems to fix the issue:

src/core/lib/iomgr/socket_utils_common_posix.cc

 static bool g_default_client_tcp_user_timeout_enabled = false;
-static bool g_default_server_tcp_user_timeout_enabled = true;
+static bool g_default_server_tcp_user_timeout_enabled = false;

**Comment by baboyo** [comment]
Just did a clean check out of master (e0d9692fa30cf3a7a8410a722693d5d3d68fb0fd) and things seem to work again under WSL.  Some work has been done in  grpc/src/core/lib/iomgr/socket_utils_common_posix.cc, which might have adressed this issue i guess. Unit tests are also all passing on my WSL test bench.

**Comment by mhaidrygoog** [comment]
Issue resolved
