### ISSUE TITLE
C++ client-server hello world

### ISSUE THREAD

**Issue by vandevoorde** [grpc/grpc#170]
Hi,

A have a newbie request:  I'm unable to find documentation describing what I need to do to compile and link a service that I write.

I see the code in test/cpp/*, and interop/{client,server} are particularly helpful as an example.  But there are no Makefiles  there, and the top-level file is 10K lines :(

 -Mark

**Comment by nicolasnoble** [comment]
By the way, we've made efforts to improve that documentation, and created example projects here: https://github.com/grpc/grpc-common/tree/master/cpp - could you see if this seems better for you or if you still have comments about it ?

**Comment by jayantkolhe** [comment]
done
