### ISSUE TITLE
Channel destructor failure during teardown

### ISSUE THREAD

**Issue by stub42** [grpc/grpc#17004]
### What version of gRPC and what language are you using?
 
grpcio 1.16.0, Python2
 
### What operating system (Linux, Windows, …) and version?
 
Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 2.7.12
 
### What did you do?

Command line script that opens a TLS channel with interceptors, creates a client, makes some calls, closes the channel, and terminates.
 
### What did you expect to see?
 
The script terminate cleanly
 
### What did you see instead?
 
A spurious failure in a Python destructor. The grpc._channel.Channel.__del__ method is attempting to call module global functions, but they have already been destroyed. `cygrpc.fork_unregister_channel(self)` fails, because cygrpc is None. Similarly, _moot is already gone.

```
I1025 17:06:40.485048414   25945 completion_queue.cc:1382]   grpc_completion_queue_shutdown(cq=0x3d4eb40)
I1025 17:06:40.485095120   25945 completion_queue.cc:1388]   grpc_completion_queue_destroy(cq=0x3d4eb40)
I1025 17:06:40.485114258   25945 completion_queue.cc:1382]   grpc_completion_queue_shutdown(cq=0x3d4eb40)
I1025 17:06:40.485136530   25945 completion_queue.cc:1382]   grpc_completion_queue_shutdown(cq=0x3a03660)
I1025 17:06:40.485155296   25945 completion_queue.cc:1388]   grpc_completion_queue_destroy(cq=0x3a03660)
I1025 17:06:40.485224591   25945 completion_queue.cc:1382]   grpc_completion_queue_shutdown(cq=0x3a03660)
I1025 17:06:40.485249325   25945 channel.cc:455]             grpc_channel_destroy(channel=0x3a56d80)
I1025 17:06:40.485638087   25945 init.cc:158]                grpc_shutdown(void)
Exception AttributeError: "'NoneType' object has no attribute 'fork_unregister_channel'" in <bound method Channel.__del__ of <grpc._channel.Channel object at 0x7f272ad99510>
 ```
### Anything else we should know about your project / environment?

I have not been able to put together a reproducible test case, as it seems hard to get the stars to align just right. The script that does trigger it is a Django command line application with a mass of dependencies, but I don't think anything bad is being done to mess with Python garbage collection. I think it is just bad luck that my client and the channel it contains is being garbage collected too late. The failure is documented Python behavior when the reference to the object is at module scope (in my case, a simple cache):

> when __del__() is invoked is response to a module being deleted (e.g., when execution of the program is done), other globals referenced by the __del__() method may already have been deleted

Work around is simple:

```python
    def __del__(self):
        # TODO(https://github.com/grpc/grpc/issues/12531): Several releases
        # after 1.12 (1.16 or thereabouts?) add a "self._channel.close" call
        # here (or more likely, call self._close() here). We don't do this today
        # because many valid use cases today allow the channel to be deleted
        # immediately after stubs are created. After a sufficient period of time
        # has passed for all users to be trusted to hang out to their channels
        # for as long as they are in use and to close them after using them,
        # then deletion of this grpc._channel.Channel instance can be made to
        # effect closure of the underlying cygrpc.Channel instance.
        if cygrpc is not None:
            cygrpc.fork_unregister_channel(self)
        if _moot is not None:
            _moot(self._connectivity_state)
```

**Comment by srini100** [comment]
@stub42, #17008 looks good. Please close this issue if you think that solves it. Once it is merged you can verify a nightly build from https://packages.grpc.io/
