### ISSUE TITLE
gRPC cross compile fails to generate dynamic libs

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#17035]
### What version of gRPC and what language are you using?
 1.12
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu16.04, cross compile for arm-linux-gnueabihf
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 arm-linux-gnueabihf-gcc-6.4.0, arm-linux-gnueabihf-g++
 
### What did you do?
Tried to cross compile to generate dynamic libs with command:
`make HAS_PKG_CONFIG=false CC=arm-linux-gnueabihf-gcc-6.4.0 
CFLAGS="--sysroot=sysroot-lin-arm7a-hf" 
CXX=arm-linux-gnueabihf-g++ 
CXXFLAGS="--sysroot=sysroot-lin-arm7a-hf" 
LD=arm-linux-gnueabihf/bin/ld 
LDXX=arm-linux-gnueabihf-g++ 
RANLIB=arm-linux-gnueabihf/bin/ranlib 
AR=arm-linux-gnueabihf/bin/ar 
STRIP=arm-linux-gnueabihf/bin/strip 
PROTOBUF_CONFIG_OPTS="--host=arm-linux-gnueabihf --with-protoc=/usr/local/bin/protoc"
 `
### What did you expect to see?
 Successfully built dynamic libs
 
### What did you see instead?
fails with following error:
`
[LD] Linking grpc/libs/opt/libaddress_sorting.so.6.0.0
arm-linux-gnueabihf/bin/ld: unrecognized option '-Wl,-soname,libaddress_sorting.so.6'
arm-linux-gnueabihf/bin/ld: use the --help option for usage information
Makefile:3089: recipe for target 'grpc/libs/opt/libaddress_sorting.so.6.0.0' failed
`

**Comment by wuyuanyi135** [comment]
try `LD=arm-linux-gnueabihf/bin/gcc LDXX=arm-linux-gnueabihf/bin/g++`

**Comment by mhaidrygoog** [comment]
Response provided. Please re-open if still a issue
