### ISSUE TITLE
C/Java HTTP2 interop failure

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1705]
Reported on grpc.io:

We're running gRPC on iOS. We're experiencing occasional crashes of the app after a timeout event is received. Specifically the following assertion is causing the error :

```c
hpack_parser.c :
void grpc_chttp2_hpack_parser_set_has_priority(grpc_chttp2_hpack_parser *p) {
  GPR_ASSERT(p->state == parse_begin);
  p->state = parse_stream_dep0; 
}
```

I managed to catch the assertion in the debugger. At this point p->state which should be parse_begin is pointing to parse_string_prefix , thus the assertion fails, Attahced below is the full stack trace and the 

Here's the code that invokes the call to AsyncNext. Note that what happened was that we received a timeout in the previous call to AsyncNext, then the subsequent call probably entered an inconsistent state of the parser :

 
```c
  std::unique_ptr<Resp> Get(uint64_t timeout, RpcStatus *rpc_status) {
  std::unique_ptr<Resp> response = make_unique<Resp>();

   auto tag = GenerateTag();
    grpc::Status status;
    response_reader_->Finish(response.get(), &status, tag);

    if (!status.IsOk()) {
      *rpc_status = RpcStatus::FAILED;
      return nullptr;
    }


    bool ok;

    auto aStatus = cli_cq_->AsyncNext(&tag, &ok, std::chrono::system_clock::now() +
                                      std::chrono::milliseconds(timeout));

    if (aStatus == grpc::CompletionQueue::NextStatus::TIMEOUT) {
      *rpc_status = RpcStatus::TIMEOUT;
      RevokeCall(context_.get(), cli_cq_.get());
      return nullptr;
    }

   if (!ok) {
      GrpcLogStatus(status);
      if (status.code() == grpc::StatusCode::UNAUTHENTICATED) {
        *rpc_status = RpcStatus::UNAUTHENTICATED;
      } else {
        *rpc_status = RpcStatus::FAILED;
      }
      return nullptr;
    }

    *rpc_status = RpcStatus::READY;
    is_done_ = true;
    return response;
  }
```

**Comment by ctiller** [comment]
This was a C++ client against a Java server - suspect a state machine mixup in the C HTTP2 parser - priorities are not a well tested path for us.

**Comment by ohad7** [comment]
Is there a temporary workaround where we can maybe detect and reset the state machine and return with an error ?

**Comment by ctiller** [comment]
I'm going to do up a quick fix to simply drop the connection in this case.

**Comment by ctiller** [comment]
Can you try to reproduce with #1710 patched in? This should fix the problem.

**Comment by ohad7** [comment]
So far #1710  works well without crashes. That's awesome! Thank you so much!

I'll let you know if I encounter aborts.
