### ISSUE TITLE
Large timeouts may be encoded as more than 8 digits

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc#17079]
@ncteisen 

See: https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/core/lib/transport/timeout_encoding.cc#L76

If I'm reading the code correctly, `enc_seconds` only uses H or M encoding if the timeout is a multiple of 3600 or 60 seconds, respectively.  This means if a user specifies a time of 100,000,000 seconds, it would be encoded in the header as "100000000S", which is illegal per the [gRPC HTTP/2 spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md): 

> Timeout → "grpc-timeout" TimeoutValue TimeoutUnit
> TimeoutValue → {positive integer as ASCII string of at most 8 digits}

Using 100,000,020 seconds would result in "1666667M", which is legal.

Go has recently been changed to be more strict about what it allows in the headers - it used to allow 9+ digit timeouts but no longer does, so we should make sure all our implementations are following the spec.  For reference, this is how Go does its timeout encoding:

https://github.com/grpc/grpc-go/blob/cfb96008516cbda549042f43fdd23befea331172/internal/transport/http_util.go#L411

**Comment by yashykt** [comment]
From looking at the new code, I believe this is fixed.

**Comment by yashykt** [comment]
we've got tests too - https://github.com/grpc/grpc/blob/master/test/core/transport/timeout_encoding_test.cc
