### ISSUE TITLE
Publish gRPC release schedule as an .md file on github.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17070]
(Filing an issue before I forget about it)

This would be good to have, the internal doc is hard to share with users and right now we need to keep forwarding something that should be available to everyone.

**Comment by mehrdada** [comment]
dupe of https://github.com/grpc/grpc/issues/15487

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/master/doc/grpc_release_schedule.md
