### ISSUE TITLE
Add the third_party submodules with gRPC releases

### ISSUE THREAD

**Issue by perone** [grpc/grpc#17092]
It would be nice to have all third_party and correct versions/dependencies together inside the gRPC releases, otherwise, the release files are useless.

In the issue #11446, it was mentioned that the releases are ouf of control, but this doesn't seems to be complete true because you can create your own binary file and add as the release binary file. If you you don't want to change the release files, then you can add just another file together with the release as a new asset.

**Comment by nicolasnoble** [comment]
As stated in #11446, we'd rather have the users git cloning from the release tags themselves. There's very little difference at that point between doing a "download of a source release file" and a "git recursive clone of a tag", so the additional amount of work you're requesting us to do per release isn't really worth it.

I'd rather wish github would simply allow us to remove the automatic tarball links so we stop having people creating these issues.
