### ISSUE TITLE
[grpc-python] Python Server Leaking Memory (and CPU) when running for longer time 

### ISSUE THREAD

**Issue by none-da** [grpc/grpc#17113]
### What version of gRPC and what language are you using?
 v1.16.0 and even tried 1.14.0
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04.09 and even tried 16.04.10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.6.5, gcc version 5.4.0 20160609, Ubuntu 16.04.10, 4.4.0-1070-aws Kernel, Glibc 2.23
 
### What did you do?
Running grpc python server in a K8s pod
 
### What did you expect to see?
A pod running with expected memory and cpu 
 
### What did you see instead?
Memory utilization kept on increasing from 200 Mb to 8 Gb, so is CPU. File Descriptor counts were also growing like crazy (in the order of 200K). 

Server is started with the below code
```py
server = grpc.server(
            futures.ThreadPoolExecutor(max_workers=1)
        )
server.add_insecure_port(self._prepare_service_domain_url(options['port']))
server.start()
try:
    while 1:
        time.sleep(86400)
except KeyboardInterrupt:
    stop_grpc_server()


def stop_grpc_server():
     grpc_server.stop(10)


def graceful_stop_handler(signal, frame):
    stop_grpc_server()

import signals
import atexit
signals_package.signal(signals_package.SIGTERM, graceful_stop_handler)
atexit.register(stop_grpc_server)
```
 
### Anything else we should know about your project / environment?
We have seen that the above code is running perfectly fine, in the below environment. Not sure if its a conicidence or an environment that won't trigger resource leaks in grpc-python. Hence just mentioning it.
```
 Python 3.6.5, gcc version 5.4.0 20160609, Ubuntu 16.04.09, 4.4.0-1062-aws Kernel, Glibc 2.23
```

**Comment by none-da** [comment]
<img width="493" alt="screenshot 2018-11-06 at 5 22 59 pm" src="https://user-images.githubusercontent.com/157880/48062794-0ad28b00-e1e9-11e8-813e-65f43b826225.png">
<img width="683" alt="screenshot 2018-11-06 at 5 23 11 pm" src="https://user-images.githubusercontent.com/157880/48062795-0b6b2180-e1e9-11e8-95ac-789b0a8ba003.png">

Screenshots showing the leaks.

**Comment by lidizheng** [comment]
@lidizheng

**Comment by none-da** [comment]
Its the unary RPCs. Infact it was just health-check RPCs, running every 5 secs once.

**Comment by none-da** [comment]
> Its the unary RPCs. Infact it was just health-check RPCs, running every 5 secs once.

@srini100 Something like this:
```py
import os
import socket

class HealthCheckService(HealthCheckServicer):

    def GetHealth(self, request, context):
        try:
            '''
            SQL Query for this is:
               SELECT (1) AS `a`
               FROM `some_important_table`
               WHERE `some_important_table`.`id` = 1234
               LIMIT 1;
            
            '''
            is_object_exists = SomeImportantTable.objects.filter(id=settings.DEFAULT_ID).using('default').exists()
        except OperationalError as mysql_error:
            from django.db import connection
            connection.close()

            # We should propagate the db operationalerror so that subsequent traffic is never directed to the
            # current running service
            raise mysql_error

        if not is_object_exists:
            # as a safe check, in case in future if we deleted this entry from our DB.
            # Still this is a valid case to test mysql availability.
            logger.exception("HealthCheckService: SomeImportantTable Object doesn't exist for ID: {}".
                             format(settings.DEFAULT_ID))
        response_dict = {
            'HOST': socket.gethostname(),
            'uptime': elapsed(),
            'SLA': '40 ms',
            'version': os.getenv('VERSION', '0.1.0')
        }
        return GetHealthResponse(health_response=str(response_dict))
```

and the Health-Check probe definition is like this:
```yaml
readinessProbe:
    exec:
    command:
    - /app/bin/python
    - /app/health_check/rpc/v1/get_health_check.py
    failureThreshold: 2
    initialDelaySeconds: 20
    periodSeconds: 5
    successThreshold: 3
    timeoutSeconds: 1
```

**Comment by srini100** [comment]
Closing this. Please reopen of the issue can be reproduced without the mysql code.
