### ISSUE TITLE
Should pre-existing Unix domain sockets be automatic unlinked in tcp_server_add_port?

### ISSUE THREAD

**Issue by diegonehab** [grpc/grpc#17122]
### What version of gRPC and what language are you using?

v1.16.0 in C++ 
 
### What operating system (Linux, Windows, …) and version?

Ubuntu 18.04.1 LTS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)  
 
### What did you do?

Started a server bound to "unix:&lt;path&gt;". Then, while the first one is running, started another server using the same address "unix:&lt;path&gt;". 
 
### What did you expect to see?

Expected the second server creation to fail. 
 
### What did you see instead?
 
The second server unlinks the socket created by the first server and creates a new one in its place.
Then, when the second server quits, it unlinks the new socket, leaving the first server hidden forever. 

The culprit is line 395 in file 

    https://github.com/grpc/grpc/blob/v1.16.0/src/core/lib/iomgr/tcp_server_posix.cc

where grpc_unlink_if_unix_domain_socket is called unilaterally.

I don't understand the scenario in which it would be useful to replace an existing socket with a new one. The starting of the second server was most likely an error and the only way to detect this error is for creation to fail right away.
It seems odd that a new server can forever hide a previously running server.

Perhaps the current behavior could be made available through a GRPC_ARG_UNIX_PREUNLINK (or some such) channel argument?
Otherwise, shouldn't at least an option GRPC_ARG_NO_UNIX_PREUNLINK (or some such) be available?
 
### Anything else we should know about your project / environment?

Not really.

**Comment by mhaidrygoog** [comment]
This looks like a legitimate concern. We should be throwing an error instead of directly unlinking the previous socket. Upgrading this to a enhancement

**Comment by bduclaux** [comment]
Another related issue is that a GRPC server will reset the permissions of the unix socket file when starting.

For instance, when a unix socket has different uid and gid, such as prod.www-data (username prod, group www-data), these permissions are reset to prod.prod when the GRPC server starts. The GRPC code should not attempt to reset these permissions. It might be a consequence of the grpc_unlink_if_unix_domain_socket call mentioned above.

This is a bug IMHO, as it prevents communication between a GRPC server and a client running under different uid / gid through a unix domain socket, which is often the case when the client runs into a NGINX/PHP-FPM server under www-data uid, and the GRPC server in the back-end with another uid.
