### ISSUE TITLE
assertion failed: status == mode.expect_status

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#1712]
This is on PR #1693 , Travis build 1763.3

D0521 19:03:01.486248119   15046 test_config.c:52] test slowdown: machine=4.000000 build=1.000000 total=4.000000
I0521 19:03:01.486523333   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/cancel
I0521 19:03:01.486814217   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/deadline
I0521 19:03:21.487276835   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/cancel
I0521 19:03:21.487681049   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/deadline
I0521 19:03:41.488276396   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/cancel
D0521 19:03:41.498044838   15046 server.c:943] server destroys call 0x7fdd580108e0
I0521 19:03:41.498102531   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/deadline
I0521 19:04:01.498634745   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/cancel
D0521 19:04:01.499131002   15046 server.c:943] server destroys call 0x7fdd580108e0
I0521 19:04:01.499163491   15046 cancel_after_invoke.c:57] test_cancel_after_invoke/chttp2/socketpair/deadline
E0521 19:04:21.499621733   15046 cancel_after_invoke.c:161] assertion failed: status == mode.expect_status
FAILED: bins/opt/chttp2_socket_pair_cancel_after_invoke_unsecure_test [ret=-6, pid=15046]

**Comment by ctiller** [comment]
reproduced locally.

**Comment by nicolasnoble** [comment]
Seen again right now. Seems very rare.

**Comment by ctiller** [comment]
Rare here too. Wouldn't block the release on it, but would like to fix it.

We get a CANCELLED status instead of a DEADLINE_EXCEEDED status.

**Comment by nicolasnoble** [comment]
Just saw it again on Travis.

**Comment by ctiller** [comment]
CNR
