### ISSUE TITLE
Ruby server doesn't receive fields with underscore

### ISSUE THREAD

**Issue by theodorosidmar** [grpc/grpc#17139]
### What version of gRPC and what language are you using?
Ruby and grpc gem 1.16.0
 
### What operating system (Linux, Windows, …) and version?
 macOS Mojave 10.14
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 I'm just using ruby gem.
 
### What did you do?
I have a Ruby gRPC server and a proto file with some properties named with underscore. Example: `value_in_cents`, `price_in_cents` and `birth_date`. No matters what type they are, my server does not "receive" them properly. When I tried `string`, they came `empty`. When `int`, they came `zero`. I noticed this coincidence was happening only with fields which name had underscore. So, I renamed them to `valueincents`, `priceincents` and `birthdate` and they just worked out finely.
 
### What did you expect to see?
 I expect to use properties named with underscore normally.
 
### What did you see instead?
Properties named with underscore, my Ruby server did not handle it properly. They were always zero or empty, when int and string respectively.
 
### Anything else we should know about your project / environment?
Yes.
- My client is a Node.js application using `grpc` package from `npm` version `1.15.1`;
- I'm using Docker for my client and for my server with docker-compose. Dockerfiles below;
- Responding with fields named with underscore just works fine.

Ruby server `Dockerfile`:
```
FROM ruby:2.5.3-alpine3.8
WORKDIR /discounts-service
COPY Gemfile .
COPY Gemfile.lock .
RUN apk add --update build-base
RUN BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install --jobs $(nproc) --without development test
COPY . .
CMD ["ruby", "app.rb"]
```

Node.js client `Dockerfile`:
```
FROM node:9.5.0-alpine
WORKDIR /products-service
COPY . .
RUN apk add --no-cache --virtual .gyp python make g++
RUN npm install --production --no-cache
RUN apk del .gyp
CMD ["npm", "start"]
```

`Gemfile`:
```
source 'https://rubygems.org/'

gem 'dotenv', '2.5.0'
gem 'grpc', '~> 1.16.0'
```

`Gemfile.lock`:
```
GEM
  remote: https://rubygems.org/
  specs:
    dotenv (2.5.0)
    google-protobuf (3.6.1)
    googleapis-common-protos-types (1.0.2)
      google-protobuf (~> 3.0)
    grpc (1.16.0)
      google-protobuf (~> 3.1)
      googleapis-common-protos-types (~> 1.0.0)

PLATFORMS
  ruby

DEPENDENCIES
  dotenv (= 2.5.0)
  grpc (~> 1.16.0)

BUNDLED WITH
   1.16.5
```

`package.json`:
```
...
"dependencies": {
  "grpc": "1.15.1"
},
...
```

Code [repository](https://github.com/theodorosidmar/hashlab-hiring-exam).
Looks like #8257 but I have already tried `v1.0.1` and it didn't work out.

**Comment by murgatroid99** [comment]
The most likely explanation here is that there is some kind of mismatch between how messages are handled on the client and server, so it would help to see the relevant code on both sides.

**Comment by nicolasnoble** [comment]
@murgatroid99 check https://github.com/theodorosidmar/hashlab-hiring-exam

**Comment by theodorosidmar** [comment]
Well, it started with me thinking it was a bug on Ruby server and ended up with a coding mistake on Node.js client. I just used option `keepCase: true` on `protoLoader.loadSync` and it worked fine.

Thank you very much @murgatroid99 and @nicolasnoble !

I'm closing the issue.
