### ISSUE TITLE
TCP_USER_TIMEOUT not supported for this platform

### ISSUE THREAD

**Issue by vadimi** [grpc/grpc#17206]
### What version of gRPC and what language are you using?
`1.16.0`, python 3.6
 
### What operating system (Linux, Windows, …) and version?
Ubuntu Linux
`uname -r` returns `4.15.0-38-generic`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.6
 
### What did you do?
Performing regular unary RPC call with enabled keepalive options and using `GRPC_VERBOSITY=Debug` and `GRPC_TRACE=round_robin` to print some Debug logs
 
### What did you expect to see?
No `TCP_USER_TIMEOUT not supported for this platform` message
 
### What did you see instead?
Even though my kernel version is `4.15` I see the following message in the log:

`I1113 14:16:31.657144159   22799 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform`

According to this code https://github.com/grpc/grpc/blob/62a16fb45a7a01ca0e06b75184c5935b3d35ca2b/src/core/lib/iomgr/port.h#L87 in order to use TCP_USER_TIMEOUT option my kernel version needs to be higher than `2.6.37`

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by srini100** [comment]
@ericgribkoff, is it possible that due to manylinux1 compatibility, gRPC-python is not able to use newer kernel features? If yes, then this is a python specific issue.

**Comment by yashykt** [comment]
Please try it on head. The log should only be enabled on GRPC_TRACE=tcp

**Comment by yashykt** [comment]
Also, if the build is using manylinux1 as @srini100 said, then we do not enable this. We need this header for LINUX_VERSION_CODE to work
https://github.com/grpc/grpc/blob/abbfd89dfc7e140fb1658f671b36e3276bfc37ce/include/grpc/impl/codegen/port_platform.h#L177

**Comment by vadimi** [comment]
I tried version `1.17.0rc1` and it only prints this message on `GRPC_TRACE=tcp`. I also checked `quay.io/pypa/manylinux1_x86_64` docker image (I presume this is the one used for python build) and it looks like it has an old `linux/version.h` file with `KERNEL_VERSION` lower than `2.6.37`.

Is there a plan to enable it for python - it seems like a very useful feature to have?

**Comment by srini100** [comment]
@yashykt, since this is a compile time check, the python pkg will not be able to use TCP_USER_TIMEOUT even if the kernel supports it. This should be changed to a run time check.

**Comment by yashykt** [comment]
That would mean having to recreate the fields that we need from the headers. Hmm, that might be worth it. I don't see any other way this would be supported for python unless users build from source themselves

**Comment by keithstellyes** [comment]
Still experiencing this on macOS on HEAD

**Comment by yashykt** [comment]
This shouldn't have been closed by the stale bot. Sorry about that.

I haven't been able to give this time either. Hence marking it never stale. In the mean time, if someone is able to get to this before me, pull requests are welcome :)

**Comment by veblush** [comment]
I made a change to address this problem but this only affects Linux since Linux is the only platform to support TCP_USER_TIMEOUT as of today.
