### ISSUE TITLE
C++: Call Finish() on bidi-streaming after client closed connection will have 2 responses from server side CompletionQueue

### ISSUE THREAD

**Issue by fengzhyuan** [grpc/grpc#17222]
### What version of gRPC and what language are you using?
 C++11 with gRPC version 1.12
 
### What operating system (Linux, Windows, …) and version?
 Linux, Ubuntu 16.04 64 bit
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.4
 
### What did you do?
setup:
Server: async server for bidi-streaming call/request; Client: async client for bidi-streaming;
reproduce steps:
1. client start bidi-request and send messages with 16KB binary data for each message; from terminal I can see server responds 
2. press ctrl+c in terminal to terminate client
3. on server side I saw the following response:
3.1 From handleRPC() loops: CompletionQueue got non-ok status; 
3.2 server call Finish() function; and print some information: context.IsCancelled(): false
3.3 server CompletionQueue got ok status, and print some information: context.IsCancelled(): true
3.4 delete the request since I already got response after called Finish()
3.5 server CompletionQueue got the 2nd response of this request with ok status, and with printed information: context.IsCancelled(): true
 
### What did you expect to see?
step 3.5 should not happen 
 
### What did you see instead?
 step 3.5 happened which will cause pure virtual method error since I already deleted the request at step 3.4

**Comment by ppLorins** [comment]
I observed the same phenomenon as yours.   My case:
win10   grpc : v1.21.x    vs2015 .

I suppose the first notification(3.3) is mean to say that the `final status` set by the server side has already been sent, and the second notification(3.5) is mean to say that the stream has already been closed now.

And my solution is just deleting the request object(3.4) after the second notification(3.5).

**Comment by DinoStray** [comment]
Got the same error

**Comment by DinoStray** [comment]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f7589455801 in __GI_abort () at abort.c:79
#2  0x00007f7589e48957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f7589e4eae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f7589e4eb21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f7589e4f8ff in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000056419c50f7c5 in grpc::ServerInterface::BaseAsyncRequest::FinalizeResult(void**, bool*) ()
#7  0x000056419c32f8c7 in grpc::ServerInterface::RegisteredAsyncRequest::FinalizeResult (this=0x7f75380017d0, tag=0x7f7553ff8fb8, status=0x7f7553ff8fb3)
    at /usr/local/include/grpcpp/impl/codegen/server_interface.h:245
#8  0x000056419c33a77f in grpc::ServerInterface::PayloadAsyncRequest<poolin::service::RequestSubscribeJob>::FinalizeResult (this=0x7f75380017d0, tag=0x7f7553ff8fb8, status=0x7f7553ff8fb3)
    at /usr/local/include/grpcpp/impl/codegen/server_interface.h:323
#9  0x000056419c501409 in grpc_impl::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) ()
#10 0x000056419c2bf377 in grpc_impl::CompletionQueue::Next (this=0x56419d8b4990, tag=0x7f7553ff8fb8, ok=0x7f7553ff8fb3) at /usr/local/include/grpcpp/impl/codegen/completion_queue_impl.h:176
