### ISSUE TITLE
Missing C++ API to set IP_TOS (DSCP) on a gRPC server stream

### ISSUE THREAD

**Issue by infn-ke** [grpc/grpc#17225]
I need a C++ API to set IP_TOS (DSCP) on gRPC server stream. How can this be done? I could not find a C++ API for this.

There are many use cases where marking the IP frames with DSCP is important. Notably, googles own gNMI spec is one of them requiring the gRPC stream to have DSCP marking!

**Comment by mhaidrygoog** [comment]
I think this may be achieved by implementing a grpc_socket_mutator and set the appropriate option in the mutate callback.
@apolcyn Could you please confirm?

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work

**Comment by bjosv** [comment]
@jtattermusch Hi! We need an API like this and I will look into how it can be implemented, to prepare a PR. Since this issue was closed more then a year ago I would like to first check if the conditions have changed. Do you know if there are any new thoughts in this area?
