### ISSUE TITLE
Client doesn't detect Server disconnection

### ISSUE THREAD

**Issue by kalman5** [grpc/grpc#17236]
In my application (c++) I have a service exposed as:

grpc foo(stream Request) returns (Reply) { }

The issue is that when the server goes down (CTRL-C) the stream on the client side keeps going indeed the

grpc::ClientWriter::Write

doesn't return false. I can confirm that using netstat I don't see any connection between the client and the server (apart a TIME_WAIT one that after a while goes away) and the client keeps calling that Write without errors.

Is there a way to see if the underlying connection is still up instead to rely on the Write return value ? I use grpc version 1.12

**Comment by mhaidrygoog** [comment]
Closing duplicate issue
