### ISSUE TITLE
PHP CLI fork bug

### ISSUE THREAD

**Issue by aizuyan** [grpc/grpc#17240]
### What version of gRPC and what language are you using?
`php`
```
grpc support => enabled
grpc module version => 1.15.0
 ```
### What operating system (Linux, Windows, …) and version?
` MAC OS`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 ```
php -v:
PHP 7.2.10 (cli) (built: Sep 14 2018 07:07:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
```
 
### What did you do?
I want to fork 3 process on cli model, trigger three orphan process, but child process not quit
```php
$user = 3;
while ($user >= 1) {
    $pid = pcntl_fork();
    if (-1 == $pid) {
        die("fork进程失败\n");
    } else if (0 == $pid) {
        break;
    } else {
        $user--;
        if ($user == 0) {
            exit;
        }
    }
}
```

```
➜  Test ps -l
  UID   PID  PPID        F CPU PRI NI       SZ    RSS WCHAN     S             ADDR TTY           TIME CMD
  501   852   833     4006   0  31  0  4297248   1280 -      Ss+                 0 ttys001    0:00.25 /bin/zsh --login -i
  501   696   695     4006   0  31  0  4298336   4940 -      S                   0 ttys002    0:00.83 -zsh
  501  1480     1        6   0  31  0  4356908   2212 -      S                   0 ttys002    0:00.00 php Test.php
  501  1481     1        6   0  31  0  4356908   2216 -      S                   0 ttys002    0:00.00 php Test.php
  501  1482     1        6   0  31  0  4356908   2228 -      S                   0 ttys002    0:00.00 php Test.php
```
 
### What did you expect to see?
in cli model fork multi process, even don't use grpc, only install it
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by stanley-cheung** [comment]
Please try `sudo pecl install grpc-beta` to get the latest version `1.17.0RC2`. Fork() support has been just recently added.

**Comment by aizuyan** [comment]
@stanley-cheung 

this issue still trigger
```
grpc
grpc support => enabled
grpc module version => 1.17.0RC2
PWD => /Users/ruitao/Downloads/grpc
$_SERVER['PWD'] => /Users/ruitao/Downloads/grpc
```

**Comment by krecu** [comment]
> @stanley-cheung
> 
> this issue still trigger
> 
> ```
> grpc
> grpc support => enabled
> grpc module version => 1.17.0RC2
> PWD => /Users/ruitao/Downloads/grpc
> $_SERVER['PWD'] => /Users/ruitao/Downloads/grpc
> ```

Work fine! use env GRPC_ENABLE_FORK_SUPPORT=1 
`GRPC_ENABLE_FORK_SUPPORT=1 php ./test.php`

**Comment by aizuyan** [comment]
@krecu @stanley-cheung 
```
pecl install grpc-beta
```

```
grpc
grpc support => enabled
grpc module version => 1.17.0
```

```
export GRPC_ENABLE_FORK_SUPPORT=1
```


work fine
