### ISSUE TITLE
Python fork support logspam on epollex

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#17253]
The newly added fork support in gRPC Python does not extend to `epollex`. That's somewhat understandable (although it's a bummer since `epollex` is the default when built from source or `pip install`ing the source `grpcio` package). However, the old supported behavior with regard to fork-exec now causes log spam from https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/fork_posix.cc#L64 when using `epollex` under plain fork-exec:

```
fork_posix.cc:63]           Fork support is only compatible with the epoll1 and poll polling strategies
```

My understanding is that this is supposed to work (and still does), but the logspam is misleading and a bit problematic. Can we eliminate this line from the supported use-case? [Please confirm this is still a supported use-case even under `epollex`, correct?]

(cc: @ericgribkoff)

**Comment by ericgribkoff** [comment]
Yes, fork+exec is always supported. There's a mismatch between the default values of GRPC_FORK_SUPPORT_ENABLED in core, where it defaults to true, and in the Python layer, where it defaults to false. There is no signal in core that could let us distinguish beforehand between fork without exec and fork with exec. This is why the earlier error log message ([here](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/fork_posix.cc#L56)) is not "log spam" by default. I am fine changing the "Fork support is only compatible..." log statement in `fork_posix.cc` to INFO level, but we still want an error to surface to Python users that have explicitly set GRPC_FORK_SUPPORT_ENABLED=1. This can probably be done by checking `grpc_get_poll_strategy_name()` in `fork_posix.pyx.pxi`.

**Comment by mehrdada** [comment]
Perhaps the `gpr_log` should be `INFO` and not error?

**Comment by ericgribkoff** [comment]
I agree(d), as it's not a detectable configuration error in core.

> I am fine changing the "Fork support is only compatible..." log statement in fork_posix.cc to INFO level
