### ISSUE TITLE
Allow clients to disable reconnection backoff behavior

### ISSUE THREAD

**Issue by ryanpbrewster** [grpc/grpc#17250]
gRPC automatically performs backoff on reconnection attempts. I would like to be able to disable this feature. Currently the best I can do is set the `max_reconnect_backoff_ms` option to 100ms ([link](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/subchannel.cc#L511)). Is there any objection to changing the minimum legal value for this option to 0ms?

 We have a use-case where we are running integration tests over gRPC. Each test is checking that a specific illegal action will trigger a server-side error and close the gRPC stream.

Related issue: https://github.com/grpc/grpc/issues/5377

**Comment by murgatroid99** [comment]
You say that each error closes the gRPC stream. But the point of gRPC is that multiple streams exist on a single connection. So unless you're closing the entire connection every time a single stream has an error, you shouldn't be encountering the reconnection backoff much.

**Comment by ryanpbrewster** [comment]
That's a good point. I was mistaken about the cause here, it doesn't matter that we're closing the stream. The actual issue is that each test case is creating a new client, checking some logic, then closing down the client. As such, we cannot (easily) re-use the connection.

**Comment by murgatroid99** [comment]
If you are explicitly shutting down clients and creating new ones, how can you tell that the reconnection backoff time is kicking in there? If you are simply experiencing delays, that may just be the time it takes for gRPC to establish a new connection.

**Comment by ryanpbrewster** [comment]
I enabled logging and see results like:
```
I1119 16:23:30.238573350  260556 subchannel.cc:517]          Subchannel 0x41a68f0: Retry in 55738 milliseconds
```

Additionally, setting `'grpc.max_reconnect_backoff_ms': 100` largely mitigates this issue. https://github.com/grpc/grpc/pull/17251 would allow us to eliminate the reconnection backoff and eliminate the issue entirely.

**Comment by AspirinSJL** [comment]
If the server is always up, and you are creating and destroying a client repetitively, then backoff should be unrelated here. 

When the channel is destroyed, the subchannel will be unreffed and destroyed (if no other channel is has a ref to it). If the subchannel is destroyed, it can't have any backoff and reconnection attempt. 

But you do see a retry log, so I guess your server is unreachable at some point? 

I'm not sure about the real problem and expectation here yet.

**Comment by ryanpbrewster** [comment]
The server is always up and reachable. We don't see any refused connections. I can inspect the server logs and see that there are new connections coming in with exponential backoffs.

Happy to help dig in, but we do know that capping the `max_reconnect_backoff_ms` to 100ms does indeed mitigate this issue, so I'm pretty confident that it is actually causing reconnections and triggering this backoff behavior.
