### ISSUE TITLE
grpc-node TypeError: challenge.setBrandId is not a function

### ISSUE THREAD

**Issue by vijifru** [grpc/grpc#17269]
### What version of gRPC and what language are you using?
 gRPC 1.16.0 and Node v8.11.2
 
### What operating system (Linux, Windows, …) and version?
 Mac
 
### What did you do?
Am trying to set or get the repeated int32 type values 
 
### What did you see instead?

status |  
-- | --
statusCode | 1
statusType | "ERROR"
statusMessage | "TypeError: challenge.setBrandId is not a function /api/challenges/savechallenges"
data | []
stackTrace |  
0 | "TypeError: challenge.setBrandId is not a function"
1 | "    at Object.saveChallenges (/Users/300027560/Documents/blink_workspace/spectrum-server/src/routes/challenges/api.js:42:15)"
2 | "    at router.get (/Users/300027560/Documents/blink_workspace/spectrum-server/src/routes/challenges/index.js:12:25)"
3 | "    at Layer.handle [as handle_request] (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/layer.js:95:5)"
4 | "    at next (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/route.js:137:13)"
5 | "    at compression (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-middlewares/node_modules/compression/index.js:217:5)"
6 | "    at Layer.handle [as handle_request] (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/layer.js:95:5)"
7 | "    at next (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/route.js:137:13)"
8 | "    at updateSession (/Users/300027560/Documents/blink_workspace/spectrum-server/src/lib/app.js:136:2)"
9 | "    at Layer.handle [as handle_request] (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/layer.js:95:5)"
10 | "    at next (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/route.js:137:13)"
11 | "    at /Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-middlewares/xsrfVerify.js:6:36"
12 | "    at Layer.handle [as handle_request] (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/layer.js:95:5)"
13 | "    at next (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/express/lib/router/route.js:137:13)"
14 | "    at processUserProfile (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-middlewares/authviaidea.js:160:9)"
15 | "    at /Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-middlewares/authviaidea.js:41:7"
16 | "    at /Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-httpclient/lib/service.js:221:7"
17 | "    at Request.callback (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-httpclient/node_modules/superagent/lib/node/index.js:692:16)"
18 | "    at parser (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-httpclient/node_modules/superagent/lib/node/index.js:903:18)"
19 | "    at IncomingMessage.res.on (/Users/300027560/Documents/blink_workspace/spectrum-server/node_modules/unity-httpclient/node_modules/superagent/lib/node/parsers/json.js:19:7)"
20 | "    at emitNone (events.js:111:20)"
21 | "    at IncomingMessage.emit (events.js:208:7)"
22 | "    at endReadableNT (_stream_readable.js:1064:12)"

**Comment by murgatroid99** [comment]
Can you share the code that reproduces this error, including any `.proto` files or similar that define the service?
