### ISSUE TITLE
Ruby flake on Travis

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1726]
The log is [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/63681966/log.txt). The test failure was 

```
  1) GRPC::ActiveCall#each_remote_read the returns an enumerator that can read n responses
     Failure/Error: expect(e.next).to eq(reply)
     StopIteration:
       iteration reached an end
     # ./spec/generic/active_call_spec.rb:249:in `next'
     # ./spec/generic/active_call_spec.rb:249:in `block (4 levels) in <top (required)>'
     # ./spec/generic/active_call_spec.rb:247:in `times'
     # ./spec/generic/active_call_spec.rb:247:in `block (3 levels) in <top (required)>'
```

**Comment by tbetbetbe** [comment]
> The log is [here]([here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/63681966/log.txt)). The test failure was

Sadly that links to a passing test, and it's only 8 minutes since the test run.  Are you sure that's the right log? In future, please copy a bit more of the logs into the issue.

**Comment by tbetbetbe** [comment]
@murgatroid99 - can you identify the right log ?
my initial expectation with is that's there's a transient environment problem
- this is a fairly simple test that does not involve multi-threading like other flaky tests.
- I've never seen this flake locally in the x80 runs that I've been running in the background to explore the other flakes
- with the log, a lot of investigation time can be saved

**Comment by tbetbetbe** [comment]
Closing.  
- It's been a month and there have been no reports of this failure occurring again
- It was more than likely that there were external factors on the test host that might have caused the flake.  Unlike other test stability issues, no multi-threading is involved in this test.
