### ISSUE TITLE
Objective-C:How can I update the Objective-C Compiled files？

### ISSUE THREAD

**Issue by ztkgithub** [grpc/grpc#17289]
When I change the protos files, such as remove a proto ,and I pod install or pod update ,but  the compiled files from the removed proto are still here ,How I can update the compiled files when I change the protos files? best wishes!

**Comment by muxi** [comment]
I doubt that this being a gRPC issue. Check your Podfile and local podspec for any `protoc` usage. I am unable to provide more info without seeing your project.
