### ISSUE TITLE
Need a way to specify source address in GRPC C++ channel creation

### ISSUE THREAD

**Issue by mailravi02** [grpc/grpc#17284]
### What version of gRPC and what language are you using?
 Release v1.16.0  and C++
 
### What operating system (Linux, Windows, …) and version?
 Debian Stretch
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
There is no way to specify source IP in GRPC C++
 
### What did you expect to see?

An option to specify a source address during channel Creation( CreateChannel). 

### What did you see instead?
 
There is no way to specify source IP in GRPC C++

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by yashykt** [comment]
More information is needed here on what the motive here is.

**Comment by mailravi02** [comment]
In our application we will specify the source interface for each GRPC connection and the expectation is that the GRPC connection will use the VRF and source IP of that interface. To achieve this we need an option in GRPC to set vrf/namespace and source IP. 

This feature will be useful in case the destination GRPC server IP is resolved through multiple interface.  User configures a source interface, through which the GRPC packet should be sent out (by setting the source IP of that interface in the packet source IP field). 

Temporarily we have used setns option to set the namespace. We are also not able to set multiple namespace/vrf for different GRPC connection. Is that expected GRPC behavior?

**Comment by yashykt** [comment]
@markdroth to comment on whether we want to provide the option for clients to specify source address as a channel argument.

**Comment by markdroth** [comment]
This use-case seems very reasonable.

I'd like input from @ejona86 and @dfawley on this.  Do Java and Go support this?  If so, what does the API look like?

**Comment by dfawley** [comment]
There is no way to specify this specifically in Go, but you can inject your own custom dialer which could accomplish it.

**Comment by sanjaypujare** [comment]
In grpc-jave there is something called LocalSocketPicker. See https://github.com/grpc/grpc-java/issues/4917

**Comment by halochou** [comment]
Any update to this issue?
