### ISSUE TITLE
Build fails on Fedora 29 + clang7.0

### ISSUE THREAD

**Issue by draft6** [grpc/grpc#17287]
### What version of gRPC and what language are you using?
 Release v1.16.1 and C++
 
### What operating system (Linux, Windows, …) and version?
 GNU/Linux Fedora 29
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang version 7.0.0 (Fedora 7.0.0-2.fc29)
 
### What did you do?
Untar release and run make.
 
### What did you expect to see?
 Successfull build
 
### What did you see instead?
 CXX]     Compiling src/core/ext/transport/chttp2/transport/flow_control.cc
src/core/ext/transport/chttp2/transport/flow_control.cc: In member function ‘virtual uint32_t grpc_core::chttp2::TransportFlowControl::MaybeSendUpdate(bool)’:
src/core/ext/transport/chttp2/transport/flow_control.cc:193:50: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       static_cast<const uint32_t>(target_window());
                                                  ^
cc1plus: all warnings being treated as errors
make: *** [Makefile:2919: /mnt/storage/grpc-1.16.1/objs/opt/src/core/ext/transport/chttp2/transport/flow_control.o] Error 1

I have disabled -Werror, build then progresses past this point. This same issue happens on the v1.17.0-pre2 as well as master. 

Also worth noting is that the build has no issues on latest OSX Mojave with clang 7.0 injected into the path overriding Apple's clang altho im not sure what compiler got selected during that particular build.

**Comment by graywolf** [comment]
Same issue on archlinux.

**Comment by iamsergio** [comment]
Please remove -Werror from user builds. -Werror is great during development but shouldn't be used by users, as it frequently breaks the build with compiler upgrades
