### ISSUE TITLE
Cancel a server side streaming call from client side in c++

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#17292]
### What version of gRPC and what language are you using?
 v1.12, C++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc6
 
### What did you do?
I have a server side streaming call of sort rpc ListFeatures(Rectangle) returns (stream Feature) {}. How can I cancel the stream from client side or close the channel cleanly?

I have tried context.TryCancel() it does the job, but is it the correct way to close a channel or cancel the stream?

**Comment by kalman5** [comment]
What happens if you close the ClientReader on the client side, at that point on the server side the ServerWriter::Write should start to return false

**Comment by lucifercr07** [comment]
@kalman5 are you referring to ClientReader Finish() ?

**Comment by yashykt** [comment]
Yes TryCancel() from the client should do the job. That is the right way to cancel a stream.
