### ISSUE TITLE
grpc fails straight to no proxy when https_proxy is invalid

### ISSUE THREAD

**Issue by UsmannK** [grpc/grpc#17339]
This issue exists to accompany PR #17311 

 
### What version of gRPC and what language are you using?
 1.16 // impacts all languages

### What did you do?
Defined the env vars http_proxy and https_proxy. Defined https_proxy with an invalid uri scheme. 
 
### What did you expect to see?
 http_proxy is used
 
### What did you see instead?
no proxy was used 

This issue exists to accompany PR #17311

**Comment by UsmannK** [comment]
@apolcyn any updates?

**Comment by apolcyn** [comment]
@yashykt is https://github.com/grpc/grpc/pull/15698 related?

**Comment by AspirinSJL** [comment]
#17311 is doing the right thing, I think.

**Comment by gnossen** [comment]
@yashykt Since #17311 has been closed, is this issue still valid?

**Comment by yashykt** [comment]
ok!
