### ISSUE TITLE
Error while building grpc ruby implementation with OpenSSL and disabling boringssl

### ISSUE THREAD

**Issue by shahidhs-ibm** [grpc/grpc#17334]
### What version of gRPC and what language are you using?
Version: master
Language: Ruby
 
### What operating system (Linux, Windows, …) and version?
OS: Ubuntu 18.04.1 LTS (Bionic Beaver)
Arch: x86_64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
OpenSSL 1.1.0g  2 Nov 2017
 
### What did you do?
Using rake to install grpc from source code using OpenSSL and disabling embedded boringssl.

Steps to reproduce:
1. apt-get install -y build-essential ruby git-core ruby-dev libssl-dev libgoogle-perftools-dev protobuf-compiler pkg-config
2. git clone https://github.com/grpc/grpc.git
3. cd grpc/src/ruby/
4. git submodule update --init
5. gem install bundle
6. Edit "./ext/grpc/extconf.rb" file and set the ENV['EMBED_OPENSSL'] = 'false'
7. bundle install
8. rake
 
### What did you expect to see?
Successful completion of command rake. 
 
### What did you see instead?
Getting the following error:
```
/usr/bin/ruby2.5 -I/var/lib/gems/2.5.0/gems/rspec-support-3.8.0/lib:/var/lib/gems/2.5.0/gems/rspec-core-3.8.0/lib /var/lib/gems/2.5.0/gems/rspec-core-3.8.0/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb

An error occurred while loading spec/spec_helper.
Failure/Error: return gem_original_require(path)

LoadError:
  /SSworkspace/grpc/src/ruby/lib/grpc/grpc_c.so: undefined symbol: SSL_CTX_set_cert_store - /SSworkspace/grpc/src/ruby/lib/grpc/grpc_c.so
```
 
### Anything else we should know about your project / environment?
I am trying to build grpc ruby implementation from source with OpenSSL (disabled boringssl). This looks like OpenSSL 1.0.x and 1.1.x API incompatibility issue to me.

**Comment by prankkelkar** [comment]
Any solutions?

**Comment by shahidhs-ibm** [comment]
This was solved by workaround to switch to gRPC's C++ build. Closing the issue.
