### ISSUE TITLE
gRPC-Core.podspec is missing system libz system library dependency

### ISSUE THREAD

**Issue by paulb777** [grpc/grpc#17365]
gRPCCore.podspec should include `s.library = 'z'`

### What version of gRPC and what language are you using?
 
Using gRPC-Core (1.14.0)
 
### What operating system (Linux, Windows, …) and version?
 
MacOS, CocoaPods 1.6.0 pre-release
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Xcode 10.1
 
### What did you do?

Building Firestore Tests
 
### What did you expect to see?

Successful build
 
 
### What did you see instead?
 
Undefined symbols for architecture x86_64:
  "_deflateInit2_", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in message_compress.o
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in stream_compression_gzip.o
  "_deflate", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in message_compress.o
      grpc_stream_compress_gzip(grpc_stream_compression_context*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, grpc_stream_compression_flush) in stream_compression_gzip.o
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in stream_compression_gzip.o
  "_inflate", referenced from:
      zlib_decompress(grpc_slice_buffer*, grpc_slice_buffer*, int) in message_compress.o
      grpc_stream_decompress_gzip(grpc_stream_compression_context*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, bool*) in stream_compression_gzip.o
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in stream_compression_gzip.o
      grpc_stream_compression_context_destroy_gzip(grpc_stream_compression_context*) in stream_compression_gzip.o
      gzip_flate(grpc_stream_compression_context_gzip*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, int, bool*) in stream_compression_gzip.o
  "_deflateEnd", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in message_compress.o
      grpc_stream_compression_context_destroy_gzip(grpc_stream_compression_context*) in 

### Anything else we should know about your project / environment?

The podspec should include `s.library = 'z'`

**Comment by muxi** [comment]
I am not sure if `s.library = 'z'` is a misspell or it's a new feature in Cocoapods 1.16, since we have `ss.libraries = 'z'` [here](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L182). I wonder why that did not work.

**Comment by paulb777** [comment]
Yep it looks like a CocoaPods 1.6.0 issue.

`gRPC-Core.xcconfig no longer defines `OTHER_LD_FLAGS`.

The 1.5.3 version specifies the -lz there.

**Comment by muxi** [comment]
Closed as the reason is identified in #8333.
