### ISSUE TITLE
Unimplemented RPC should return a non-empty message.

### ISSUE THREAD

**Issue by realazthat** [grpc/grpc#17366]
### What version of gRPC and what language are you using?

1.14.1, C++
 
### What operating system (Linux, Windows, …) and version?
 
N/A (Ubuntu 16.04.5 LTS) 

### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A (gcc 7.3.0)
### What did you do?

I implemented the [gRPC Server Reflection Tutorial](https://github.com/grpc/grpc/blob/5fed8e54528ca94213fec7038f56d9db91709c33/doc/server_reflection_tutorial.md) and used the [gRPC command line tool](https://github.com/grpc/grpc/blob/5fed8e54528ca94213fec7038f56d9db91709c33/doc/command_line_tool.md), without implementing my service's single function.

```proto
syntax = "proto3";

package mykpg;

message CreateTableRequest {
}

message CreateTableReply {
}

service MyServer {
  rpc CreateTable (CreateTableRequest) returns (CreateTableReply);
}
```

```c++
...
struct MyServerImpl final : public mypgk::MyServer::Service {};
```

### What did you expect to see?
 
I expected to see an error telling me that I didn't implement the function I called.
 
### What did you see instead?

```
Rpc failed with status code 12, error message: 
```

I had to find this via [status_code_enum.h](https://github.com/grpc/grpc/blob/5fed8e54528ca94213fec7038f56d9db91709c33/include/grpcpp/impl/codegen/status_code_enum.h#L115), and/or by guessing/counting on [statuscodes.md](https://github.com/grpc/grpc/blob/5fed8e54528ca94213fec7038f56d9db91709c33/doc/statuscodes.md).

----

I suggest gRPC replaces `::grpc::StatusCode::UNIMPLEMENTED, \"\")` with `::grpc::StatusCode::UNIMPLEMENTED, \"UNIMPLEMENTED\")` in [cpp_generator.cc](https://github.com/grpc/grpc/blob/5fed8e54528ca94213fec7038f56d9db91709c33/src/compiler/cpp_generator.cc).

I can make a PR if the project is amenable (or someone else can).

----

A further and separate suggestion is to enhance the documentation on [statuscodes.md](https://github.com/grpc/grpc/blob/5fed8e54528ca94213fec7038f56d9db91709c33/doc/statuscodes.md) to include the integer codes that the status code enums represent.

**Comment by yashykt** [comment]
I am neither for or against this. Seems to me that a simple enum to string function would also do the job.
