### ISSUE TITLE
Compile error on archlinux

### ISSUE THREAD

**Issue by graywolf** [grpc/grpc#17369]
### What version of gRPC and what language are you using?

v1.16.1, c++

### What operating system (Linux, Windows, …) and version?

```
Linux xxx 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
gcc (GCC) 8.2.1 20180831
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```
$ wget https://github.com/grpc/grpc/archive/v1.16.1.tar.gz
$ tar xvf v1.16.1.tar.gz
$ cd grpc-1.16.1/
$ CXXFLAGS=-Wno-ignored-qualifiers make
```

NOTE: the `-Wno-ignored-qualifiers` is to work around #17287.

### What did you expect to see?

Compilation to work.

### What did you see instead?

```
[CXX]     Compiling src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc
src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc: In function ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’:
src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:70:10: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Werror=stringop-truncation]
   strncpy(req->initial_request.name, lb_service_name,
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           GRPC_GRPCLB_SERVICE_NAME_MAX_LENGTH);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

### Anything else we should know about your project / environment?

No

**Comment by yashykt** [comment]
Pull requests are welcome :)

**Comment by ius** [comment]
@yashykt Pull request has been there for a year (https://github.com/grpc/grpc/pull/14452), but it's not moving.

Related: #18565 #18299 

It's unfortunate that grpc builds with *-Werror* even though nobody seems to actually develop using a recent version of gcc (ie. 8, soon to be 9).

**Comment by yashykt** [comment]
@nicolasnoble do you have time to look at this?

**Comment by nicolasnoble** [comment]
I have fixed all gcc 8 build issues recently, and these should be on the 1.20 branch. We are now using gcc 8 to build some of our artifacts. This ought to be resolved. Please open new issues if there are still lingering problems not covered by our test cases.
