### ISSUE TITLE
ServerBuilder::SetDefaultCompressionLevel doesn't work

### ISSUE THREAD

**Issue by my-fish** [grpc/grpc#17372]
### What version of gRPC and what language are you using?
 c++
 
### What operating system (Linux, Windows, …) and version?
 macOS 
 
### What did you do?
use ServerBuilder to construct a server with `SetDefaultCompressionLevel()`
 
### What did you expect to see?
 the server send compressed data
 
### What did you see instead?
the data does not been compressed.
 
### How to
Please insert code `maybe_default_compression_level_.is_set = true;` in function ServerBuilder::SetDefaultCompressionLevel()

```
ServerBuilder& ServerBuilder::SetDefaultCompressionLevel(
    grpc_compression_level level) {
  maybe_default_compression_level_.is_set = true;  // code to be inserted
  maybe_default_compression_level_.level = level;
  return *this;
}
```

**Comment by yashykt** [comment]
A pull request would be welcome next time :)
