### ISSUE TITLE
GCC 5.1.0: ISO C does not support '__FUNCTION__' predefined identifier

### ISSUE THREAD

**Issue by sarum9in** [grpc/grpc#1739]
Compilation fails under GCC 5.1.0
```
src/core/httpcli/httpcli.c:71:28: error: ISO C does not support '__FUNCTION__' predefined identifier [-Werror=pedantic]
```

Can be fixed with
```
find . -type f -exec sed -r 's|__FUNCTION__|__func__|g;s|c89|c99|g' -i '{}' ';'
```

**Comment by ctiller** [comment]
The correct thing to do I think is remove all references. It's non-C89
without a portable alternative.

**Comment by ctiller** [comment]
Also, TIL __FUNCTION__ is non-standard.

**Comment by ctiller** [comment]
Actually, lets just introduce GPR_FUNCTION_NAME in port_platform.h?
