### ISSUE TITLE
HTTP->gRPC status code mapping for 404 errors

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#17390]
According to https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md, a client that receives a 404 error and no gRPC status from a server should convert that to a gRPC UNIMPLEMENTED status. This is done by Java, but Core converts it to a CANCELLED error, and Go appears to convert it to INTERNAL.

This was reported by a Python user, but applies to C++ and likely all wrapped languages as well. CANCELLED doesn't seem very informative for this case, and disagrees with the spec, but I don't have all of the context for how/why the error code is converted in core. I went back as far as gRPC Python v1.3.0 and confirmed that the 404->CANCELLED behavior existed then as well.

This can currently be reproduced with the interop client against an invalid *.googleapis.com domain, e.g.:

```
$ bins/opt/interop_client --server_host=dsldksd.googleapis.com --server_host_override=dsldksd.googleapis.com --server_port=443 --use_tls=true
I1204 08:52:00.091349377  134560 client.cc:101]              Testing these cases: large_unary
E1204 08:52:00.209103463  134560 interop_client.cc:138]      Error status code: 1 (expected: 0), message: Received http2 header with status: 404, debug string: {"created":"@1543942320.204908547","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":121,"grpc_message":"Received http2 header with status: 404","grpc_status":1,"value":"404"}
```

cc @ejona86

**Comment by srini100** [comment]
cc @dfawley

**Comment by dfawley** [comment]
This is related to https://github.com/grpc/grpc-go/issues/2064 which we hope to address this week or next.
