### ISSUE TITLE
FLAKY: grpc/core/pull_request/macos/grpc_ios_binary_size

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#17419]
Test `grpc/core/pull_request/macos/grpc_ios_binary_size` is flaky, and recent 36 builds all failed.

https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Agrpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size

**Comment by lidizheng** [comment]
CC @jtattermusch

**Comment by jtattermusch** [comment]
Duplicate of https://github.com/grpc/grpc/issues/17420

**Comment by lidizheng** [comment]
This issue is for ios binary size test flakyness. And #17420 is for cpp basic tests. Do they share the same root cause?
