### ISSUE TITLE
FLAKY: grpc/core/pull_request/macos/grpc_basictests_dbg

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#17420]
The C++ test tends to timeout.
```
2018-12-05 15:44:13,472 TIMEOUT: run_tests_c++_macos_dbg_native [pid=63354, time=519080.8sec]
```

Recent 34 builds are failed:
https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_dbg

@jtattermusch

**Comment by jtattermusch** [comment]
After rolling back to sierra workers, the macos tests seem to be passing again.
