### ISSUE TITLE
RPC stats

### ISSUE THREAD

**Issue by fta1** [grpc/grpc#1743]
I'm trying to expose the time to 1st byte of my RPC calls, along with the total time (round trip). I achieved the latter with an extra ping/pong RPC, that I can also turn into a decorator on any call in the client side (my clients are in Python), but for the former, it is difficult. Also, it sort of clutters the code as it forces every single call to be wrapped (and in a microservice environment, that could mean touching a lot of code living in different places, and possibly several languages). It would be nice if that was collected by gRPC itself, and exposed via the various language APIs.
I'm not really expecting one-way measurements, as that would mean enforcing ntp synced boxes (or worse)... yet, that would be extra nice to have.

If that also counts the number of calls, even better. The server should be able to expose that per client, while the client should probably only show the server it is connected to (per stub).

**Comment by ctiller** [comment]
We have some ongoing work to bring our statistics and tracong code open source. I don't have the exact plan at my fingertips, but it is coming.

@aveitch may be able to provide some further colour.

**Comment by a-veitch** [comment]
We will have those stats (and more features) available, and there is an
early version of it in the core/statistics directory (provides latency
stats only for now). I'm in the middle of refactoring this to make
integration into both our open source and google-internal systems easier -
you should start seeing some of that this week. Over the coming months,
we'll be adding more functionality.

Cheers,
    Alistair

**Comment by srini100** [comment]
open-census could be an option here. closing this
