### ISSUE TITLE
Calling next() on a shutdown client completion queue block indefinitely

### ISSUE THREAD

**Issue by Siron777** [grpc/grpc#17438]
### What version of gRPC and what language are you using?
 1.17.0
### What operating system (Linux, Windows, …) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 C++ / Visual studio 2017
### What did you do?

I have an asynchronous client with a bidirectional stream to a server.  The client close the connection to the server by calling:
**streamer->WritesDone(tag(tagDone));**
The server is notified of that and close itself (shutdown the completion queue and the application is stopped). If before I try to call **stream.Finish(grpc::Status(), tag(tagFinish));** on the server side, it crashes. So I assume that I cannot call this function when the client has already notified the server of the termination of the communication.
The call to next on the completion queue of the client returns the fact that the WritesDone operation is done. I thus shutdown the client completion queue and call next() on it, expecting it to return false, but it stays stuck on wait. If instead of calling next(), I close the program, I have a warning on the console:
`E1207 11:17:53.906000000 19048 backup_poller.cc:110] run_poller: {"created":"@1544177873.906000000","description":"Shutting down timer system","file":"C:\dev\conan_c\gRPC\1.17.0\AI\extern\build\78cd7b38ad8b4d21bb87826d9e499814103125be\gRPC_v1.17.0\src\core\lib\iomgr\timer_generic.cc","file_line":704}`

 Why ? What is wrong in my code ? 

Here is my code:
`    
auto streamer = m_stub->PrepareAsyncgetEvent(&context, &cq);
    auto status = grpc::Status();
    streamer->Finish(&status, tag(tagFinish));
    streamer->StartCall(tag(tagConnection));

    bool ok;
    void* tagReceived;
    while(cq.Next(&tagReceived, &ok)) {
        if(ok) {
            switch(detag(tagReceived)) {
                case tagConnection:
                    streamer->Read(&event, tag(tagRead));
                    break;
                case tagRead:
                    request.set_id(event.id());
                    streamer->Write(request, tag(tagWrite));
                    break;
                case tagWrite:
                    if(event.id() > 10) {
                        streamer->WritesDone(tag(tagDone));
                    } else {
                        streamer->Read(&event, tag(tagRead));
                    }
                    break;
                case tagDone:
                    cq.Shutdown();
                    //return; //Create a warning on the console 
                    break;
                case tagFinish:
                    cq.Shutdown();
                    break;
                default:
                    abort();
            }
        }
    }

`

**Comment by Croydon** [comment]
Hi @Siron777!
Since you are using grpc via Conan may I ask which recipe you are using?

Also for the case you didn't see it yet: #15363

**Comment by yashykt** [comment]
You are calling Finish() too early. Please refer to the documentation here for the correct order for calling it.
https://github.com/grpc/grpc/blob/5e50a89502a22f6c10f59259151bd0d0362c4b55/include/grpcpp/impl/codegen/async_stream.h#L79
