### ISSUE TITLE
Bazel 0.20 fixes into release 1.17.x [request]

### ISSUE THREAD

**Issue by moriarty** [grpc/grpc#17445]
### What version of gRPC and what language are you using?

I'm using gRPC from commit f8696b5136 (author: @nicolasnoble, reviewer: @jtattermusch)
which is from grpc/grpc#17363 which fixes an issue with **Bazel 0.20.0**

This is my WORKSPACE file:

```
##
# We need a specific unreleased version of gRPC:
#  which fixes grpc & bazel 0.20 issues
#  https://github.com/grpc/grpc/pull/17363
##
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = 'com_github_grpc_grpc',
    url = 'https://github.com/grpc/grpc/archive/f8696b5136108fd2d46e553fdd550e1be6ba2677.zip',
    sha256 = 'e8484fba47a3eebaed82704e8197a5f98f20d6843e44ea2a5e007180958ad545',
    strip_prefix = 'grpc-f8696b5136108fd2d46e553fdd550e1be6ba2677',
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

```
 
### What operating system (Linux, Windows, …) and version?
 
Ubuntu 18.04 & Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7.3.0
 
### What did you do?

We were using grpc, with a specific release specified in our WORKSPACE (1.14.2) file, but then we upgraded to **Bazel 0.20.0** and it failed due to deprecated imports of the grpc_deps.
 
### What did you expect to see?
 
To be able to continue using a released version of gRPC.
It would be better to point to a specific release: **1.17.0** was released just after #17363 went it, so I first tried the latest release **1.17.0** but that also didn't work.
 
### What did you see instead?
 
It didn't compile, but I find the fix had been merged to master with: f8696b5136108fd2d46e553fdd550e1be6ba2677
 
### Anything else we should know about your project / environment?

could f8696b5136108fd2d46e553fdd550e1be6ba2677 get cherry-picked into *1.17.1*

**Comment by moriarty** [comment]
f8696b5 is a merge commit so I didn't cherry-pick that commit.

I don't know now **gRPC** is with rebasing other commits, I considered rebasing the original **fix-bazel-0.20** branch but then I decided for two cherry-picks.

 2192  git cherry-pick f0fbee59326402e6c1f0a7c6a1f8899fd2b0025a
 2197  git cherry-pick 237cc52ffd58c6f46a68d5662fd69cac05b52ec2

**Comment by moriarty** [comment]
Looks like we're not the only ones using a specific commit from grpc:

https://github.com/stackb/rules_proto/pull/2 they're also pointing to f0fbee59326402e6c1f0a7c6a1f8899fd2b0025a

```diff -157,8 +157,8 @@ def com_google_protobuf(**kwargs):
 def com_github_grpc_grpc(**kwargs):
     name = "com_github_grpc_grpc"
-    ref = get_ref(name, "5f84445781ef29e50435c2eea661ca435a19b6bc", kwargs) # v1.15.0
-    sha256 = get_sha256(name, "8c09d35806c857dcb3a383c81052cc7ba1c5855e827d0792a83bd57251821e29", kwargs)
+    ref = get_ref(name, "f0fbee59326402e6c1f0a7c6a1f8899fd2b0025a", kwargs) # Bazel 0.20.0 workspace fixes.
+    sha256 = get_sha256(name, "6cea8d3dbe289872343aafe67736539b0a28ecd062d3ff4965f157f5d9d77d1d", kwargs)
     github_archive(name, "grpc", "grpc", ref, sha256)

```

**Comment by srini100** [comment]
@moriarty, release branch cut happens 2 weeks before the release so a commit has to be in the master branch at the time of branch cut. See [release schedule](https://github.com/grpc/grpc/blob/master/doc/grpc_release_schedule.md)

Unfortunately, this commit cannot be cherrypicked into 1.17.1 patch as 1.17.1 RC was released a week ago which is promoted to final version without any more changes. The patch is scheduled to go out today and we cannot make any more changes.

@nicolasnoble, I will let you decided if you want to backport to v1.17.x branch in case we do another patch from this branch later.

**Comment by moriarty** [comment]
@srini100 thanks for the update. I appreciate the link to the release schedule, but does a broken build not have anyway of getting a hot-fix or patch made? I guess working with the latest release of bazel isn't a release criteria?

@nicolasnoble 
If it could be back-ported to any released branch or tag that would be greatly appreciated.

To provide more information why this would be useful
-----
Obviously this might be a one off case, there may be not that many users who want to use a combination of the latest version of **Bazel** without specifying additional flags, and still use a _tagged release_ of **gRPC**

I'd like to maintain consistent versions of gRPC across a system. Before this was working by pointing all of the components to a released tag of gRPC.

But now now the components of the system using **bazel 0.20** need a specific commit. Options were to roll back freeze the version of bazel, or to move forward and use **bazel 0.20**.
As seen in the diff above from stackb/rules_proto@72a9e46e741d1e6f4f871222b67b663ce2fa9ccc pointing to a specific commit in a bazel project isn't much of a problem.

But with non-bazel components of the system, if we want to continue to sync or version of bazel this involved actually modifying a Dockerfile. Instead of just passing an argument to a Dockerfile, because it can't be specified during the git clone command. For example: https://github.com/grpc/grpc-docker-library/blob/master/1.12.0/cxx/Dockerfile. 

A more specific example **Dockerfile**
```diff
- ARG GRPC_RELEASE_TAG=v1.14.2
+ ARG GRPC_RELEASE_TAG=f0fbee59326402e6c1f0a7c6a1f8899fd2b0025a

- RUN git clone --recursive --branch ${GRPC_RELEASE_TAG} --single-branch --depth=1 \
-       https://github.com/grpc/grpc /var/local/git/grpc && \
+ RUN git clone https://github.com/grpc/grpc /var/local/git/grpc && \
+     cd /var/local/git/grpc && \
+     git checkout ${GRPC_RELEASE_TAG} && \
+     git submodule update --init && \
      cd /var/local/git/grpc/third_party/protobuf && \
      ./autogen.sh && \
      ./configure --enable-shared && \
      make -j$(nproc) && \
      make -j$(nproc) check && \
      make install && \
      make clean && \
      ldconfig && \
      cd /var/local/git/grpc && \
      make -j$(nproc) && \
      make install && \
      make clean && \
      ldconfig && \
      cd / && \
      rm -rf /var/local/git/grpc
```

**Comment by srini100** [comment]
@moriarty, v1.17.2 is tagged with this fix. Hope this helps.

**Comment by moriarty** [comment]
Perfect thanks!
