### ISSUE TITLE
control tracing at run time

### ISSUE THREAD

**Issue by fta1** [grpc/grpc#1744]
I'm trying to change the level of tracing at run time (in python). The idea is to be able to turn on/off the tracing in a server without having to restart it (for troubleshooting purposes).
It seems the GRPC_TRACE env is only read once during grpc_init(), and not tracked afterwards.
If tracking is not acceptable, maybe exposing grpc_tracer_init to the API would be better?

**Comment by ctiller** [comment]
It would take a lot to convince me that tracking is worthwhile (it would be quite expensive).

I have considered something like:
grpc_tracer_set_enabled(const char *name, intended enabled);
To allow fine grained control at runtime of individual trace variables.

**Comment by fta1** [comment]
indeed, when I wrote the op, I already knew tracking would not be acceptable for the reason you mentioned, and it's probably not even needed for this use case. Hence the request for an API.

Your grpc_tracer_set_enabled() proposal would be nice, esp if it came with another method to list the supported traces (which seem dynamic, in the C code).
I see parse() called by grpc_tracer_init() is complaining when an unknown variable is passed in. That should probably be reported as an error code or something..
