### ISSUE TITLE
Python: Add unit tests to examples/python/helloworld

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#17453]
We already have documentation for our unit testing framework published here: https://grpc.io/grpc/python/grpc_testing.html

But it would be helpful for users to have a stand-alone example of unit tests for `greeter_client` and `greeter_server` when getting started with gRPC Python, as the only other usages of the testing APIs are in our own internal tests, which can be hard for new users to parse through

**Comment by lidizheng** [comment]
I have doubts about the usability of `grpcio-testing` package. It requires to retrieve ProtoBuf descriptors about the servicer, but it seems not supported yet. There are two related issues:
https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/python/grpcio_tests/tests/testing/_application_testing_common.py#L20
https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/python/grpcio_tests/tests/testing/_application_testing_common.py#L21

#11657 got closed and moved to https://github.com/grpc/grpc/issues/3898 which got closed and never solved.

The implementation of `grpcio-testing` is correct and the unit test passed steadily. However, it is using hard-coded method descriptors... Before further investigation, I won't be confident to recommend this package to gRPC Python users.

**Comment by shahidash** [comment]
Absolutely!

**Comment by lucascharlesz** [comment]
That would be awesome!

**Comment by Lawouach** [comment]
That would be indeed awesome. It feels a little odd that the code is so well documented but usage is quite under-documented. 

Maybe @nathanielmanistaatgoogle could chime in? I was browsing around and saw a few PRs and SO comments but none led to me a full/complete example of using the testing framework unfortunately :(

**Comment by alexykot** [comment]
I've figured out how to use the `grpc_testing` server test suite and created a minimal running example for `Greeter` helloworld service. Available [here](https://github.com/alexykot/grpcio-test-example). 

I'm not sure where exactly it should go in the [grcp/grcp](https://github.com/grpc/grpc) repo structure, so not sure how to create a pull request for this.

Also I'm not sure that I'm not doing anything stupid in the example I've created, so would want some sanity check from @nathanielmanistaatgoogle, @ericgribkoff or anyone else in the know of how the `grpc_testing` actually should be used.

**Comment by gnossen** [comment]
@alexykot These tests look great. We'd be more than happy to take a PR.
We've actually started adding tests to each example as it's added. Check out the [multiprocessing](https://github.com/grpc/grpc/tree/e553590a0ac50a91b32fb5cbd0b229ed62f6564e/examples/python/multiprocessing) and [wait_for_ready](https://github.com/grpc/grpc/tree/e553590a0ac50a91b32fb5cbd0b229ed62f6564e/examples/python/wait_for_ready) directories. All that should differ is the infrastructure surrounding the test. We're trying to converge around bazel.

**Comment by gnossen** [comment]
@alexykot Are you still hoping to contribute unit tests to the `helloworld` example?

**Comment by alexykot** [comment]
Sorry, this is unlikely now as we've switched over to Go entirely in our stack and phased out Python services, so I'm not using Python gRPC anymore.

**Comment by ericxiao251** [comment]
@gnossen I don't mind contributing @alexykot 's example back to gRPC, if I have his permissions. I recently stumbled upon it his example and it was great to follow!

**Comment by alexykot** [comment]
Oh, I didn't realize this is still not solved and my solution is actually workable.
I'll move the examples from my archive to gRPC asap.

**Comment by alexykot** [comment]
Created PR #27481  to relocate my examples into the upstream.

**Comment by kavithamadhavaraj** [comment]
+1 
> How can I configure interceptors on the test server?

I'm struggling with this too. From the grpcio-testing documentation, I figured there isn't a way to inject interceptors to the server. Any possible workaround for this available? 

IMO, this is very useful feature to include.
