### ISSUE TITLE
Python equivalent of C++ server's Wait() method

### ISSUE THREAD

**Issue by KamyarGhajar** [grpc/grpc#17452]
Hi,
Isn't there a more proper way to keep the grpc server alive in a dynamic manner not like this hard-coded death time of the server (e.g. One day in seconds)?
[code](https://github.com/grpc/grpc/blob/f03344e73a4e0eafb969fe4675babcb50ac08ae6/examples/python/route_guide/route_guide_server.py#L123)

**Comment by ericgribkoff** [comment]
Python does not currently have an equivalent of the C++ server's [`Wait()`](https://grpc.io/grpc/cpp/classgrpc_1_1_server.html) method. I thought I remembered some earlier discussions about this, but could not locate the relevant issue(s). I've marked this issue as a feature request for gRPC Python.

**Comment by jeryini** [comment]
I was also quite surprised when I saw that sleep call in the example. Please do implement the Wait method.
