### ISSUE TITLE
C/C++ build failure on SuSE 12

### ISSUE THREAD

**Issue by minddrive** [grpc/grpc#17471]
### What version of gRPC and what language are you using?
 1.16.1
 
### What operating system (Linux, Windows, …) and version?
 SuSE 12 Enterprise
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 GCC 7.3.0 ( / GCC 4.8.5)
 
### What did you do?
 Someone hard to fully detail here, as our build process currently uses CMake to manage all the steps, but the basic case is pretty straightforward:

- Checked out tag for 1.16.1 from the Git repository
- cd into checkout directory
- ran 'make prefix=/tmp/install install'
 
### What did you expect to see?
 The build run to completion
 
### What did you see instead?
 A failure very early on:
```
19:41:14 [C]       Compiling third_party/cares/cares/ares_cancel.c
19:41:14 [C]       Compiling third_party/cares/cares/ares_create_query.c
19:41:14 [C]       Compiling third_party/cares/cares/ares_data.c
19:41:15 third_party/cares/cares/ares_data.c: In function 'ares_malloc_data':
19:41:15 third_party/cares/cares/ares_data.c:167:40: error: this statement may fall through [-Werror=implicit-fallthrough=]
19:41:15          ptr->data.txt_ext.record_start = 0;
19:41:15          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
19:41:15 third_party/cares/cares/ares_data.c:170:7: note: here
19:41:15        case ARES_DATATYPE_TXT_REPLY:
19:41:15        ^~~~
19:41:15 third_party/cares/cares/ares_data.c: At top level:
19:41:15 cc1: error: unrecognized command line option '-Wno-invalid-source-encoding' [-Werror]
19:41:15 cc1: all warnings being treated as errors
19:41:15 Makefile:2902: recipe for target '/tmp/grpc/objs/opt/third_party/cares/cares/ares_data.o' failed
19:41:15 make[4]: *** [/tmp/grpc/objs/opt/third_party/cares/cares/ares_data.o] Error 1
```

 As a further note, if I run the make command directly from the command line, the build fully succeeds.

### Anything else we should know about your project / environment?
 The build is run via a Jenkins job and is run inside a Docker container on a SuSE 12 VM (run on Xen). 
 While we built GCC 7.3.0 for SuSE 12 and installed it in /usr/local, there is a system GCC installed in /usr that is 4.8.5 (and is needed for rpm-build, which we use for packaging).  From our logs, our top-level CMake setup is definitely finding the former:
```
19:40:11 + cmake .. -DPACKAGE=grpc
19:40:11 -- The C compiler identification is GNU 7.3.0
19:40:11 -- The CXX compiler identification is GNU 7.3.0
```

However, the error makes it feel that when the build itself starts, it's finding the system GCC instead.  The various CMake cache files corroborate this, and I'm unable to find any log/cache files generated for the Makefiles from within grpc, so I am at a loss as to what might be wrong here.  Any help would be appreciated.

**Comment by apolcyn** [comment]
c-ares dependency was updated in https://github.com/grpc/grpc/pull/18519, has this been fixed?
