### ISSUE TITLE
grpc_cli compile error in Mac after v1.16 

### ISSUE THREAD

**Issue by swuecho** [grpc/grpc#17472]
### What version of gRPC and what language are you using?

master
 
 
### What operating system (Linux, Windows, …) and version?

Mac
 
### where does the bug appear?

I am able to compile the grpc_cli in v1.15.0, but can not in v1.16.0 and v.1.17.0

I guess the bug is introduced in https://github.com/grpc/grpc/commit/3fe2c98877f376cc0c8d7da61d6e63eca83f4bec#r31647692

PS: probably it is doable to create a test to test the compilation in different OS?

**Comment by srini100** [comment]
@apolcyn, can you please check if this is due to change in ruby generator?

**Comment by apolcyn** [comment]
[this comment and reply](https://github.com/grpc/grpc/commit/3fe2c98877f376cc0c8d7da61d6e63eca83f4bec#r31647692) in the ruby generator PR likely explain.

@swuecho can you confirm that you are seeing the issue described in https://github.com/grpc/grpc/commit/3fe2c98877f376cc0c8d7da61d6e63eca83f4bec#r31647692?

**Comment by swuecho** [comment]
I followed the step in https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md
I double check the protobuff submodule, the version is 3.6.1. but the protobuf is not compiled probably, because I installed an old version of protobuf already. anyway, this seems not a real problem. sorry for the trouble.

**Comment by prestonvanloon** [comment]
I am having this same problem on linux. How was this resolved?
