### ISSUE TITLE
gRPC/C++ : OnDone callback not getting invoked on Reactor for certain RPCs

### ISSUE THREAD

**Issue by mhaidrygoog** [grpc/grpc#17473]
### What version of gRPC and what language are you using?
 HEAD
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Bazel
 
### What did you do?
 Ran streaming benchmarks on Callback client 
### What did you expect to see?
 Successful completion of benchmarks with resulting latency numbers
 
### What did you see instead?
Hanging of benchmark code. Further analysis showed that the OnDone callback for reactor is not being invoked by certain RPCs 

### Logs

Client logs
I1211 15:16:31.081142  146177 call.cc:1508] ops[0]: RECV_MESSAGE ptr=0x7fecfce29b20
I1211 15:16:31.081173  146234 completion_queue.cc:782] cq_end_op_for_pluck(cq=0x7fecfd61b060, tag=0x7fecfd881888, error="No Error", done=0x56435c709170, done_arg=0x7fecfe5279e0, storage=0x7fecfe527a58)
I1211 15:16:31.081239  146234 completion_queue.cc:1299] RETURN_EVENT[0x7fecfd61b060]: OP_COMPLETE: tag:0x7fecfd881888 OK
I1211 15:16:31.081281  146234 qps_worker.cc:214] RunClientBody: Mark response given
I1211 15:16:31.081322  146234 call.cc:1903] grpc_call_start_batch(call=0x7fecfe524860, ops=0x7fed3117b550, nops=1, tag=0x7fed3117b808, reserved=(nil))
I1211 15:16:31.081365  146234 call.cc:1508] ops[0]: RECV_MESSAGE ptr=0x7fed3117b820
I1211 15:16:31.081417  146234 completion_queue.cc:782] cq_end_op_for_pluck(cq=0x7fecfd61b060, tag=0x7fed3117b808, error="No Error", done=0x56435c709170, done_arg=0x7fecfe527740, storage=0x7fecfe5277b8)
I1211 15:16:31.081447  146186 completion_queue.cc:847] cq_end_op_for_callback(cq=0x7fecfd3f38a0, tag=0x7fecfce29c70, error="No Error", done=0x56435c709170, done_arg=0x7fecfcdd3240, storage=0x7fecfcdd32b8)
I1211 15:16:31.081478  146234 completion_queue.cc:1299] RETURN_EVENT[0x7fecfd61b060]: OP_COMPLETE: tag:0x7fed3117b808 OK
I1211 15:16:31.081518  146234 qps_worker.cc:217] RunClientBody: Awaiting Threads Completion
I1211 15:16:31.081521  146186 call.cc:1903] grpc_call_start_batch(call=0x7fecfce28060, ops=0x7fed3688c730, nops=1, tag=0x7fecfce29910, reserved=(nil))
I1211 15:16:31.081566  146186 call.cc:1508] ops[0]: SEND_MESSAGE ptr=0x7fecfccfa6a0
I1211 15:16:31.081662  146177 completion_queue.cc:847] cq_end_op_for_callback(cq=0x7fecfd3f38a0, tag=0x7fecfce29910, error="No Error", done=0x56435c709170, done_arg=0x7fecfcdd3780, storage=0x7fecfcdd37f8)
I1211 15:16:31.081725  146177 call.cc:1903] grpc_call_start_batch(call=0x7fecfce28060, ops=0x7fed376e7da0, nops=1, tag=0x7fecfce29ac8, reserved=(nil))
I1211 15:16:31.081776  146177 call.cc:1508] ops[0]: SEND_CLOSE_FROM_CLIENT
I1211 15:16:31.081856  146177 completion_queue.cc:847] cq_end_op_for_callback(cq=0x7fecfd3f38a0, tag=0x7fecfce29ac8, error="No Error", done=0x56435c709170, done_arg=0x7fecfd61ab40, storage=0x7fecfd61abb8)
I1211 15:16:36.232041  151370 completion_queue.cc:963] grpc_completion_queue_next(cq=0x7fecff2258a0, deadline=gpr_timespec { tv_sec: 695881, tv_nsec: 187114722, clock_type: 0 }, reserved=(nil))
I1211 15:16:46.233045  151370 completion_queue.cc:963] grpc_completion_queue_next(cq=0x7fecff2258a0, deadline=gpr_timespec { tv_sec: 695891, tv_nsec: 188124037, clock_type: 0 }, reserved=(nil))
I1211 15:16:56.234049  151370 completion_queue.cc:963] grpc_completion_queue_next(cq=0x7fecff2258a0, deadline=gpr_timespec { tv_sec: 695901, tv_nsec: 189126045, clock_type: 0 }, reserved=(nil))

Server logs
I1211 15:16:31.082024   13031 call.cc:1508] ops[0]: SEND_MESSAGE ptr=0x7f9ff73db2a0
I1211 15:16:31.082110   13031 completion_queue.cc:699] cq_end_op_for_next(cq=0x7f9ff807b120, tag=0x7f9ff8ec5f40, error="No Error", done=0x5624c3e7e170, done_arg=0x7f9ffe4938b0, storage=0x7f9ffe493928)
I1211 15:16:31.082240   13031 call.cc:1903] grpc_call_start_batch(call=0x7f9ffe490860, ops=0x7fa0226a52e0, nops=1, tag=0x7f9ff8ec5dd8, reserved=(nil))
I1211 15:16:31.082286   13031 call.cc:1508] ops[0]: RECV_MESSAGE ptr=0x7f9ff8ec5df0
I1211 15:16:31.082343   13031 completion_queue.cc:699] cq_end_op_for_next(cq=0x7f9ff807b120, tag=0x7f9ff8ec5dd8, error="No Error", done=0x5624c3e7e170, done_arg=0x7f9ffe493610, storage=0x7f9ffe493688)
I1211 15:16:31.082460   13031 call.cc:1903] grpc_call_start_batch(call=0x7f9ffe490860, ops=0x7fa0226a5290, nops=1, tag=0x7f9ff8ec6148, reserved=(nil))
I1211 15:16:31.082513   13031 call.cc:1508] ops[0]: SEND_STATUS_FROM_SERVER status=0 details=(null)(nil)
I1211 15:16:31.082591   13031 completion_queue.cc:699] cq_end_op_for_next(cq=0x7f9ff807b120, tag=0x7f9ffe493340, error="No Error", done=0x5624c3e7e170, done_arg=0x7f9ffe4934c0, storage=0x7f9ffe493538)
I1211 15:16:31.082734   13031 completion_queue.cc:699] cq_end_op_for_next(cq=0x7f9ff807b120, tag=0x7f9ff8ec6148, error="No Error", done=0x5624c3e7e170, done_arg=0x7f9ffe493a00, storage=0x7f9ffe493a78)
I1211 15:16:31.082868   13031 completion_queue.cc:963] grpc_completion_queue_next(cq=0x7f9ff807b120, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I1211 15:16:31.082928   13031 completion_queue.cc:1063] RETURN_EVENT[0x7f9ff807b120]: OP_COMPLETE: tag:0x7f9ff8ec6148 OK
I1211 15:16:31.082986   13031 metadata_array.cc:34] grpc_metadata_array_destroy(array=0x7f9ff64e27b0)
I1211 15:16:31.083028   13031 call.cc:561] grpc_call_unref(c=0x7f9ffe490860)
I1211 15:16:31.083061   13031 metadata_array.cc:34] grpc_metadata_array_destroy(array=0x7f9ffe491438)
I1211 15:16:31.083138   13031 security_context.cc:79] grpc_auth_context_release(context=(nil))
I1211 15:16:31.083228   13031 metadata_array.cc:34] grpc_metadata_array_destroy(array=0x7f9ff64e27b0)
I1211 15:16:31.083291   13031 server.cc:1549] grpc_server_request_registered_call(server=0x7f9ffa8aca20, rmp=0x7f9ffedd1e20, call=0x7f9ffa335ce0, deadline=0x7f9ff7eb8e70, initial_metadata=0x7f9ff7eb8eb0, optional_payload=(nil), cq_bound_to_call=0x7f9ff807b120, cq_for_notification=0x7f9ff807b120, tag=0x7f9ffa335ca0)
I1211 15:16:31.083334   13031 completion_queue.cc:963] grpc_completion_queue_next(cq=0x7f9ff807b120, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I1211 15:16:34.821843   12958 completion_queue.cc:963] grpc_co

**Comment by vjpai** [comment]
Confirmed that this is a client-side issue

**Comment by vjpai** [comment]
This issue will become obsolete since we're changing the client-side callback streaming API
