### ISSUE TITLE
Collecting response time metrics including sending over the network in .NET

### ISSUE THREAD

**Issue by Chakrygin** [grpc/grpc#17497]
Hi!

Is it possible to collect a response time metric of the gRPC methods (on the server side), taking into account the time of sending the response to the client over the network? (For .NET, gRPC version 1.17.0)

We’re using interceptors and it looks like this:

```cs
public sealed class StopwatchInterceptor : Interceptor
{
    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request,
        ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        var sw = Stopwatch.StartNew();

        try
        {
            return await continuation(request, context);
        }
        finally
        {
            sw.Stop();

            Console.WriteLine($"{context.Method}: {sw.Elapsed}"); // ReportMetric
        }
    }
}
```

But in this case, the timer stops before sending a response to the client, so this metric is not entirely correct.

Is there another way?

**Comment by jtattermusch** [comment]
I'm not sure how useful it is to measure the time until the response gets sent out by the server to the client (what does it mean exactly? Until all the bytes are sent to the write() syscall?). This metric also doesn't tell you much about how quickly the client actually gets the response. It seems you should just measure on the client (start stopwatch before sending the request and stop after receiving the response). Alternatively, you want to use a tracing solution (put the client and server  in a service mesh and the proxies can trace the requests and give you some good statistics about how long does it take to process a single request etc.).
A few thoughts:
- if you want to measure time until the response gets sent, you probably want to measure also the time from the moment the first bytes of the request reach the server (which is difficult).
- if you really want to measure some approximation of the time including the time to send the response, you can use a bidi-streaming RPC, which has the MoveNext() and WriteAsync() methods exposed explicitly (and you can time time them, if that's useful).
