### ISSUE TITLE
after fork how can execute grpc_init again  in forked process

### ISSUE THREAD

**Issue by chenbaggio** [grpc/grpc#17514]
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by ericgribkoff** [comment]
We will need some additional information to answer this, including the answers to the questions in the issue template posted above.

In particular, what gRPC language(s) are you using and is this on the client or server side?

**Comment by chenbaggio** [comment]
What version of gRPC and what language are you using?
1.4.x

What operating system (Linux, Windows, …) and version?
linux centos 7

What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36

**Comment by chenbaggio** [comment]
What version of gRPC and what language are you using?
1.14.2

**Comment by ericgribkoff** [comment]
In gRPC v1.14.2, there is no support for fork. In v1.15.0, Python client-side fork support was added. There is no action required from the client other than setting the environment variable `GRPC_ENABLE_FORK_SUPPORT=1`.

**Comment by ericgribkoff** [comment]
Marking this closed. @chenbaggio if you have a specific question feel free to respond here.
