### ISSUE TITLE
Tracking issue for Python/Cython deallocation changes

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#17515]
This is an umbrella issue for remaining questions about gRPC Python's handling of deallocation. Many of these (#15756, #17093, #17214, #17258) will be resolved by PR https://github.com/grpc/grpc/pull/17444, but on the Cython server side there's still some remaining machinery (a backup completion queue) that's intended to be used for shutting down the core server when the Cython object is garbage collected before user has initiated a shutdown.

The findings reported in https://github.com/grpc/grpc/issues/4221#issuecomment-446637957 suggests that this is not likely to be a safe thing to do upon garbage collection. #17444 fixes the bug found via PyPy, but it remains a follow-up work to either safely use the backup completion queue or delete it from the code altogether.

**Comment by lidizheng** [comment]
Recently, there are couple memory leaks reported for gRPC Python. This issue might be a good tracker.

https://github.com/grpc/grpc/issues/22851
https://github.com/grpc/grpc/issues/22123

**Comment by lidizheng** [comment]
Haven't seen this issue in a long time. Closing.
