### ISSUE TITLE
C++ needs a way to get service name and method name for logging purpose

### ISSUE THREAD

**Issue by zxfishhack** [grpc/grpc#17520]
### What version of gRPC and what language are you using?
 1.17.2 c++
 
### What operating system (Linux, Windows, …) and version?
 CentOS 7.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 needs a way to get service name and method name from ServerContext, for logging purpose, just like GenericServerContext.
 
### What did you see instead?
currently can't get service name and method name in method handler, i just make a workaround by create a channel_filter to add grpc.service and grpc.method into client_metadata.
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
needs a common way to logging any rpc call, with service name, method name and expected message filed.

**Comment by yashykt** [comment]
What you want can be achieved with the interception API.
