### ISSUE TITLE
Windows opt builds not reporting status on windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17538]
The opt windows build often doesn't come back with result. On master many builds don't finish or fail.

We expected the revert https://github.com/grpc/grpc/pull/17488 to fix this but it doesn't seem to be the case.

**Comment by nicolasnoble** [comment]
I actually suspect that the introduction of the logging made the existing problem worse.

**Comment by jtattermusch** [comment]
Update: I checked the history of windows/grpc_basictests_opt  job and it turns out the pipeline was blocked by a job that got stuck for multiple days (so the failing test runs are actually from Dec 09). I killed the stuck job and I expect the windows_opt test to start passing now.
