### ISSUE TITLE
py37_native.test.reflection._reflection_servicer_test.ReflectionServicerTest failure

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#17553]
Failed at #17544 

```
Unexpected successes: []
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/tools/run_tests/helper_scripts/run_python.sh: line 25: 81028 Segmentation fault: 11  $PYTHON "$ROOT/src/python/grpcio_tests/setup.py" "$2"
```

https://source.cloud.google.com/results/invocations/3c511522-cde5-48fe-b316-224c641331d6/targets/github%2Fgrpc%2Fpython_macos_opt_native/tests

**Comment by ericgribkoff** [comment]
Same failure as https://github.com/grpc/grpc/issues/15308, although this is the first time seeing it with Python 3.
