### ISSUE TITLE
Support multiple server completion queues in Python

### ISSUE THREAD

**Issue by therc** [grpc/grpc#17569]
### What version of gRPC and what language are you using?
 1.17, Python
 
### What did you do?
Tried to find a way to create multiple completion queues in the same server process. Right now, there's a hard limit on concurrent RPCs. Once that's hit, new RPCs fail. But not all RPCs are the same: sometimes you want to set different limits for different services or have some special requests (e.g. liveness checks) that you want to process as soon as they're received. Multiple completion queues are a way to accomplish that. It's supported in C++, e.g. as mentioned in  https://github.com/grpc/grpc/issues/1468 (which is similar to this issue, but more vague).

### What did you expect to see?
 A way to have multiple queues in a Python server. One per servicer might suffice.
 
### What did you see instead?

The current server only has one queue and one limit:

https://github.com/grpc/grpc/blob/e0d9692fa30cf3a7a8410a722693d5d3d68fb0fd/src/python/grpcio/grpc/_server.py#L801

**Comment by ericgribkoff** [comment]
Could you provide more details on what you are trying to accomplish?

As for the "hard limit on concurrent RPCs", [`grpc.create_server`](https://grpc.io/grpc/python/grpc.html#create-server) has a `maximum_concurrent_rpcs` parameter that defaults to `None`, indicating no limit on the number of concurrent RPCs. The thread pool provided to the server  limits the maximum number of RPCs that are processed simultaneously, as once all threads are in use future RPCs will be queued up, but they should not be failed.

It sounds like your goal is to set separate hard limits for different services via a per-service equivalent of `maximum_concurrent_rpcs`, but additional details about what specifically you need will help us determine if this actually requires multiple completion queues or an alternative approach may suffice. Thanks.

**Comment by therc** [comment]
I'm trying to prevent overloaded servers from
1. running out of memory
1. getting killed while still processing requests

`maximum_concurrent_rpcs` takes care of the first.  Under heavy load, queued up RPCs might actually fail, in a way, e.g. if the deadline is exceeded because of excessive backlog.

When running the server under Kubernetes, you can use two different kinds of health checks:
1. readiness: I'm ready to receive traffic from the load balancer
1. liveness: I'm alive and doing work, please do not kill me

The problem under load is that both health checks (which have a short timeout) will fail. The readiness check is expected to fail and, if everything is set up correctly, will prevent the server instance from receiving further requests from the load balancer, until the backlog has cleared.

If the liveness check fails, though, Kubernetes will kill the server, which has two bad side effects:
* you can lose requests that were in flight
* you add gratuitous downtime, especially if the server does not restart instantly, e.g. because it needs to read configuration data from somewhere else or to precompute internal objects

So, for example, I want to run a server that

- processes up to ten different `/RouteGuide/*`methods (from the gRPC demos) at the same time, queuing the rest
- still answers one (maybe two, if really generous) `/Health/Check` request from the standard `grpc.health.v1` package, no matter how busy the other queue is.

**Comment by ericgribkoff** [comment]
Thanks for the detailed explanation. That seems like a very reasonable use case and one that we should support.

From a look over our code, it appears that the necessary machinery to support multiple completion queues is already present in our Cython layer, wrapped around gRPC's core API. The Python layer (`_server.py`) will need to be modified to actually instantiate multiple queues, and we will also need to modify our current single threadpool usage to support priorities as well (the servicer invocation to handle in incoming rpc is executed via the threadpool). I would guess the API might be something like one threadpool per completion queue, but this will need some more thought.

I don't have an ETA for this just yet but I'll post another update here sometime in the next week.

**Comment by ericgribkoff** [comment]
Quick update: I've added implementing this feature to my todo list for this quarter (community contributions are always welcomed as well :))

As far as the API goes, @lidizheng suggested adding an optional "annotation"/member to the servicer that, when present, provides a service-specific `futures.ThreadPoolExecutor` to gRPC Python for handling that service's RPCs. Whether each such servicer gets its own completion queue or whether we ensure one completion queue per unique ThreadPoolExecutor (in case two+ services are annotated with the same executor instance) also needs to be resolved.
