### ISSUE TITLE
build //helloworld fail by bazel ,OS: MacOs,  no such package '@boringssl//'

### ISSUE THREAD

**Issue by Darksweat** [grpc/grpc#17589]
<!--
My os is MacOS 10.14
I want to build helloworld by bazel, here is the command:
`bazel build //examples:greeter_client`
but it occurs fail, here is log.
```
INFO: Invocation ID: 91208f6c-1266-4461-a008-72e09c365111
INFO: Build options have changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_ron/982c29563026d479ed77edd90126227f/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:29:5: no such package '@boringssl//': java.io.IOException: thread interrupted and referenced by '//external:libssl'
ERROR: Analysis of target '//examples:greeter_client' failed; build aborted: Analysis failed
INFO: Elapsed time: 58.988s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 1213 targets c\
onfigured)
    Fetching @com_google_protobuf; fetching 58s
    Fetching @com_github_nanopb_nanopb; fetching 58s
    Fetching @boringssl; fetching 58s
    Fetching @com_github_madler_zlib; fetching 58s
    Fetching @com_github_cares_cares; fetching 58s
```

**Comment by strongman1995** [comment]
I have the same problem. When fetching @boringssl, the build always failed.
the error information is shown below:
no such package '@boringssl//': java.io.IOException: thread interrupted and referenced by '//external:libssl'

**Comment by rmstar** [comment]
Another instance of this failure: https://source.cloud.google.com/results/invocations/0c58c4ee-d06e-4d9c-a0a7-7a1f42f7b698/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_flaky_network/log

**Comment by muxi** [comment]
@AspirinSJL - I believe it's related to C++ on macOS; please assign accordingly.
