### ISSUE TITLE
h2_sockpair_1byte_nosec_test@cancel_after_invoke Bazel RBE Opt C/C++ failure

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#17584]
//test/core/end2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller=poll-cv failure

```
E1221 21:45:42.401169666      19 cancel_after_invoke.cc:167] assertion failed: status == mode.expect_status || status == GRPC_STATUS_INTERNAL
*******************************
Caught signal SIGABRT
```
Seen on #17536

**Comment by jtattermusch** [comment]
The failure link is:
https://source.cloud.google.com/results/invocations/4bb82cef-0d38-484b-ae88-ee3ba0a2a3e0/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller%3Dpoll-cv/log

```
Executing tests from //test/core/end2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller=poll-cv
-----------------------------------------------------------------------------
D1221 21:45:42.399639626      19 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=2, poller=5, total=10
D1221 21:45:42.399988084      19 ev_posix.cc:170]            Using polling engine: poll-cv
D1221 21:45:42.400110846      19 dns_resolver.cc:334]        Using native dns resolver
I1221 21:45:42.400164456      19 cancel_after_invoke.cc:43]  Running test: test_cancel_after_invoke/chttp2/socketpair_one_byte_at_a_time/cancel [3 ops]
I1221 21:45:42.400776491      19 cancel_after_invoke.cc:43]  Running test: test_cancel_after_invoke/chttp2/socketpair_one_byte_at_a_time/deadline [3 ops]
E1221 21:45:42.401169666      19 cancel_after_invoke.cc:167] assertion failed: status == mode.expect_status || status == GRPC_STATUS_INTERNAL
*******************************
Caught signal SIGABRT
```

**Comment by jtattermusch** [comment]
Recent failures:
https://source.cloud.google.com/results/invocations/e8fe34af-9af2-44b8-ab2a-81e9fd5fa246
https://source.cloud.google.com/results/invocations/140bfe80-b7b2-45cb-910f-9d9c2662839d
https://source.cloud.google.com/results/invocations/c69c7647-147e-4583-8aed-7c6a9b6d3a26
https://source.cloud.google.com/results/invocations/e0e920b3-304c-46f0-b3b3-1d89f31819ea
https://source.cloud.google.com/results/invocations/24a2ba59-29d9-42be-a2f4-f9931153bc73

**Comment by jtattermusch** [comment]
manual repro:
`bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=opt --runs_per_test=500 //test/core/end2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller=poll-cv`

**Comment by jtattermusch** [comment]
Based on historical data, this seems to have been happening mostly on poll-cv and the problem seems like could be what was discovered by @yashykt in #18272.
poll-cv was removed in #18298.
