### ISSUE TITLE
gRPC 0.9.0 release depends on unreleased protobuf features

### ISSUE THREAD

**Issue by sarum9in** [grpc/grpc#1759]
It is not possible to build objective_c and csharp plugins with latest release (v3.0.0-alpha-2) of protobuf.
They depend on:
 - google::protobuf::FileOptions::objc_class_prefix
 - google::protobuf::FileOptions::csharp_namespace

To build other part of project I used:
```
for plugin in csharp objective_c
do  
  sed -r 's|\$\(BINDIR\)/\$\(CONFIG\)/grpc_'${plugin}'_plugin ||' -i Makefile
  sed -r 's|src/compiler/'${plugin}'_generator\.cc||' -i Makefile
  sed -r 's|\$\(Q\) \$\(INSTALL\) \$\(prefix\)/bin/grpc_'${plugin}'_plugin||' -i Makefile
done
```
This may be useful for maintainers.

**Comment by GeertJohan** [comment]
Afaik the complete grpc project depends on protobuf v3 (which is still alpha).

**Comment by sarum9in** [comment]
Yes, but it is released: https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-2
Previous gRPC release worked just fine with this version. New gRPC requires new features.

**Comment by wkubiak** [comment]
Yes, current version of grpc targets a different version of protobuf than we can find in protobuf's current master branch, hence the compilation problems as described above.

**Comment by nicolasnoble** [comment]
Yes, my bad, I jumped the gun a bit here, thinking that their own release of alpha 3 was already out of the doors. But it should be a matter of moments now. Sorry about that.

**Comment by sarum9in** [comment]
I think that can be closed now, https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-3
I was able to build gRPC with proto-3.0.0-alpha3.

**Comment by wkubiak** [comment]
It still doesn't work for the master branch of protobuf.

**Comment by sarum9in** [comment]
I thought that gRPC release is supposed to be used with https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-3, and I reported bug just about it.
Since proto-3.0.0-alpha3 is released now and gRPC can be build with this release just fine, I closed this one.
I am sorry, I don't understand the problem you describe, but maybe it should be reported separately?

**Comment by wkubiak** [comment]
The problem is that you shouldn't be "supposed to think" that you have to target the new release of protobuf when all the current grpc readmes and docs point at just git cloning the master branch of protobuf, with which you can't build the current grpc plugins.

I hope that now you see the issue and inconvenience of the current situation.

**Comment by sarum9in** [comment]
I am sorry, but from what I see in .gitmodules
```
[submodule "third_party/protobuf"]
	path = third_party/protobuf
	url = https://github.com/google/protobuf.git
	branch = v3.0.0-alpha-1
```
it was clear for me that gRPC targets for releases, not master branches.

And again, sorry for my ignorance, but I didn't find these docs, saying that I have to use master branch.
`grep master README.md` or `grep -i proto README.md` give me no references to protobuf's master branch.

**Comment by wkubiak** [comment]
Ah, now I get it. Sorry about the misunderstanding @sarum9in 

In my workflow I tend to build the protobuf sources separately, not the ones defined in grpc submodules.

In any case, I issued a pull request in protobuf to merge the two branches. Master branch is behind v3.0.0-alpha-3 by 7 days and over 40 commits.
