### ISSUE TITLE
Python When I try to generate files for protobuf I get error ModuleNotFoundError

### ISSUE THREAD

**Issue by Valentin-Miroshnichenko** [grpc/grpc#17595]
When I try to generate files with the command

`(venv) C:\Users\Valentin\PycharmProjects\protoactor-python\tests\remote\grpc_wrapper>python -m grpc_tools.protoc -I./ --python_out=. --grpc_python_out=. service.proto`

I get error.

```
Traceback:
test_client.py:11: in <module>
    from tests.remote.grpc_wrapper.service_pb2_grpc import TestServiceServicer, add_TestServiceServicer_to_server, \
service_pb2_grpc.py:4: in <module>
    import service_pb2 as service__pb2
E   ModuleNotFoundError: No module named 'service_pb2'
```
How can I fix it? I truing reinstall protobuf but it don’t help me.

```
pip uninstall protobuf
pip install -U protobuf
```

P.S. I use conda, I truing use

`conda install protobuf`

but it don’t help me too.

**Comment by lidizheng** [comment]
Can you see the generated files under `C:\Users\Valentin\PycharmProjects\protoactor-python\tests\remote\grpc_wrapper` directory? The directory references mismatch might cause this problem.

**Comment by Valentin-Miroshnichenko** [comment]
![2018-12-26_19-25-36](https://user-images.githubusercontent.com/10279529/50455901-fb0e3200-0961-11e9-929f-15312ec87560.png)
Yes, Pycharm show it.

**Comment by lidizheng** [comment]
Hi @Valentin-Miroshnichenko , I am not able to reproduce your case, can you provide a minimal way of reproducing the bug? Also, I have seen editors behave incorrectly with generated code,  a restart of editor might fix it.

**Comment by Valentin-Miroshnichenko** [comment]
I have found a solution. Use "from . import" in _pb2_grpc.py for example from . import service_pb2 as service__pb2

https://github.com/grpc/grpc/issues/9575

**Comment by lidizheng** [comment]
According to comments in #9575
> Nevermind, I found the solution. I will quickly explain it in case anyone else is looking at this.
> 
> I now moved my proto files into a directory called `proto/some/folder/`
> 
> Then using the following command, the module names and imports are correct and work as expected in python3:
> 
> `python3 -m grpc_tools.protoc -I proto --python_out=. --grpc_python_out=. proto/some/folder/*.proto`
> 
> Note that the combination of including the root directory (`proto/`) and directing the output to `--python_out=.` achieves the desired results:
> 
> Generated files end up in `some/folder/`, also imports are as expected:
> 
> `import some.folder.someservice_pb2 as some_dot_folder_dot_someservice__pb2`

If you can change your generation command to
```
python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. .\tests\remote\grpc_wrapper\service.proto
```
Then the generated code will work for Python 3.

Ad-hoc patch to generated file generally may impair the maintainability for the code base, you may consider update the generation command.
