### ISSUE TITLE
Python - Support send structured error details

### ISSUE THREAD

**Issue by arturgspb** [grpc/grpc#17601]
Hi! I think it's maybe like this:

```python
fv = BadRequest.FieldViolation(field="login", description="Name is not unique")
bad_request = BadRequest(field_violations=[fv])
context.abort(StatusCode.INVALID_ARGUMENT, bad_request.SerializeToString())
```

Unfortunately, the required functionality or not, or the documentation is not clear enough for our team. =(

Thanks in advance for your help.

### What version of gRPC and what language are you using?

Python
grpcio==1.17.1
 
### What operating system (Linux, Windows, …) and version?

MacOS Sierra
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
python 3.6

**Comment by lidizheng** [comment]
Hi Artur, the new API has been implemented in the dev version by PR https://github.com/grpc/grpc/pull/17481, and will be available in next release. There is a related issue https://github.com/grpc/grpc/issues/16366 requesting the rich status error details. Examples and documentation will be added soon.

Here is a short snippet demonstrate the usage of the new rich status API `abort_with_status`:
```Python
# Server side
from grpc_status import rpc_status
from google.protobuf import any_pb2

def ...Servicer(...):
    def ARPCCall(request, context):
        ...
        detail = any_pb2.Any()
        detail.Pack(
            rpc_status.error_details_pb2.DebugInfo(
                stack_entries=traceback.format_stack(),
                detail="Can't recognize this argument",
            )
        )
        rich_status = grpc_status.status_pb2.Status(
            code=grpc_status.code_pb2.INVALID_ARGUMENT,
            message='API call quota depleted',
            details=[detail]
        )
        context.abort_with_status(rpc_status.to_status(rich_status))
        # The method handler will abort
```
To learn more about the design, here is the [gRFC](https://github.com/grpc/proposal/pull/118), comments are welcomed.
