### ISSUE TITLE
grpc C# server crash

### ISSUE THREAD

**Issue by Jesse1205** [grpc/grpc#17616]
### What version of gRPC and what language are you using?
 c#
 
### What operating system (Linux, Windows, …) and version?
 1.8.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 install from nuget
 
### What did you do?
 use the request / response mode 

### What did you see instead?
 server crash like this

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
my server running on windows server 2012

错误应用程序名称: GameServer.exe，版本: 6.7.9.10，时间戳: 0x55f2704b
错误模块名称: grpc_csharp_ext.x64.dll，版本: 0.0.0.0，时间戳: 0x5a4c114a
异常代码: 0xc0000005
错误偏移量: 0x000000000006f870
错误进程 ID: 0xe80
错误应用程序启动时间: 0x01d49fd6177a049a
错误应用程序路径: C:\Data\GameServer.exe
错误模块路径: C:\Data\grpc_csharp_ext.x64.dll
报告 ID: 1bf0472d-0e93-11e9-80c3-8fad6f5cd739
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by jtattermusch** [comment]
Sorry, but this report contains no useful information I could use for debugging (it basically says "I used gRPC and it crashed"). Without further details I can only close.
