### ISSUE TITLE
Bazel for gRPC Python development

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#17622]
Bazel has been around with gRPC for a while, and the gRPC Python has adopted Bazel last summer. It's time to see what is missing to use Bazel for gRPC Python development builds.

Let's recap how to test with Bazel:
```
# For all available tests
$ bazel test --test_output=errors //src/python/grpcio_tests/tests/...

# For specific test
$ bazel test --test_output=errors //src/python/grpcio_tests/tests/channelz:channelz_page_test
$ bazel test --test_output=errors //src/python/grpcio_tests/tests/unit:_api_test
...
```

Currently, here are the pending features for Bazel:
* Test with Python 3 (Bazel & Python 3 integration is really hard to get it right)
* Enable all the test cases
* **REQUESTED** Merge test BUILD files into one

If you want other features, please comment below this issue ;)

**Comment by mehrdada** [comment]
Can we merge the Bazel BUILD files for tests into a single file? I believe that's how we did it internally as well. The way it's done now makes it hard to use for people wanting to import it to monorepos (with things like copybara, etc).

**Comment by lidizheng** [comment]
@mehrdada Sounds good! Added to the description.

**Comment by variantf** [comment]
Any updates here? Are we solved all the pending features?

**Comment by lidizheng** [comment]
Python 3 support is added, and I’m looking for sometime to integrate the
unit tests.
