### ISSUE TITLE
How to archive grpc libs into a shared library?

### ISSUE THREAD

**Issue by HaoLiuHust** [grpc/grpc#17637]
I have compile grpc to static library, now I want warpper some function into a shared library. For user who use my so, I don't want to ship many grpc library with it, but now, if I do not ship gprc related .a library, there will be a lot of undefined reference error when use this so to do other things. How could I do this?

**Comment by muxi** [comment]
I'm not expert in this but I think there are two ways to do this. Either you need to statically link grpc into your .so, or the user needs to install grpc (and your .so dynamically links to grpc which I assume you already have it).

**Comment by HaoLiuHust** [comment]
I have static link grpc into my .so, however, there are many undefined reference error when use this so alone. After some search, it seems static library can only be static linked to a execuable file, is that right?

**Comment by muxi** [comment]
From your description
>if I do not ship grpc related .a library, there will be a lot of undefined reference error
I don't think you have statically linked the grpc archive. I have not done it before but from a brief search pages like [this](https://stackoverflow.com/questions/14889941/link-a-static-library-to-a-shared-one-during-build) suggest that linking static library to a shared library is possible.

**Comment by HaoLiuHust** [comment]
@muxi I have tried this, but many mult-definition error occured

**Comment by srini100** [comment]
Please post details on the steps you are following and the error log.

**Comment by muxi** [comment]
@HaoLiuHust - is this still an issue?

**Comment by HaoLiuHust** [comment]
yes, but I have found a way to not ship all of the grpc library

**Comment by muxi** [comment]
Would be great if you can provide us with some details (steps to reproduce, error logs, etc.) so that we can dig deeper into this issue.
