### ISSUE TITLE
when http_proxy's value is empty, i got an error

### ISSUE THREAD

**Issue by NicoleRobin** [grpc/grpc#17631]
https://github.com/grpc/grpc/blob/a9aec34d08e207400a2303d48ecc079a51709d88/src/core/ext/filters/client_channel/http_proxy.cc#L58
![image](https://user-images.githubusercontent.com/10753813/50678035-cd974780-1037-11e9-834f-25a4e0a16d36.png)

after i execute unset http_proxy, i fixed the error,but i think set empty value to http_proxy is equal to unset http_proxy,am i wrong?
Thank you for reply

**Comment by yashykt** [comment]
Currently, an empty value of http_proxy is not equal to unset, but we can change that.

**Comment by NicoleRobin** [comment]
ok, thanks
