### ISSUE TITLE
Cross Compiling helloworld:  gRPCTargets.cmake missing

### ISSUE THREAD

**Issue by maxwell130631** [grpc/grpc#17636]
### What version of gRPC and what language are you using?
 1.17.1,  eedcd2a7817
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
for compiling on raspberry:
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1) 
for cross compiling: 
 gcc-linaro-6.4.1-2018.05-x86_64_arm-linux-gnueabihf
 
### What did you do?
I want to use grpc to communicate from a raspberry to a pc. For this, I compiled grpc directly on the raspberry with cmake. Now I want to cross compile the helloworld example on my pc with the raspberry as a target. I do this using cmake, the linaro cross compiler, and I set the CMAKE_SYSROOT to an image file of my raspberry system. On the raspberry, the grpc and protobuf libraries got installed to /usr/local/lib, and the cmake files necessary for finding the packages are under /usr/local/lib/cmake/grpc/

When cross compiling the helloworld example I get the following error:

    maxwell@precision:~/work/libs/grpc_raspi/examples/cpp/helloworld/build$ cmake ../ -DCMAKE_TOOKLCHAIN_FILE=./toolchain.cmake
    -- Using protobuf 
     CMake Error at /opt/raspberry/raspberry_sysroot/usr/local/lib/cmake/grpc/gRPCConfig.cmake:8 (include):
      include could not find load file:

        /opt/raspberry/raspberry_sysroot/usr/local/lib/cmake/grpc/gRPCTargets.cmake
     Call Stack (most recent call first):
       CMakeLists.txt:75 (find_package)

     -- Using gRPC 1.17.1
     -- Configuring incomplete, errors occurred!

So the problem is that the file gRPCTargets.cmake is missing/did not get generated. What can I do to make this work?

I should note that in cmake I get the warning:

     CMake Warning at cmake/protobuf.cmake:51 (message):
      gRPC_INSTALL will be forced to FALSE because gRPC_PROTOBUF_PROVIDER is
      "module"

which is the reason why the gRPCTargets.cmake this is not being generated: Quite at the very end of the CmakeLists.txt file seems to be the responsible code:

     install(EXPORT gRPCTargets
        DESTINATION ${CMAKE_INSTALL_CMAKEDIR}
        NAMESPACE gRPC::
    )

Maybe it is not a good idea to have gRPCConfig.cmake reference the target file in the first place? A workaround is of course to not use find_package in cmake and specify the gRPC_DIR variable manually (which is working for me).

**Comment by KyleFromKitware** [comment]
> I should note that in cmake I get the warning:
>
> ```
> CMake Warning at cmake/protobuf.cmake:51 (message):
>   gRPC_INSTALL will be forced to FALSE because gRPC_PROTOBUF_PROVIDER is> 
>   "module"
> ```

That's why `gRPCTargets.cmake` isn't being generated. In order for that file to be generated, the third-party dependencies have to be in `package` mode, where they already exist on the system rather than being built by gRPC.

**Comment by jtattermusch** [comment]
@KyleFromKitware  @zackgalbreath  I'm going to close this, but we should improve the documentation accordingly (the Warning is easily missed) so users are less likely to run into this problem (it's kind of common).
Because this issue is about crosscompiling, we should perhaps also add a section on how to crosscompile and what are the common mistakes in the src/cpp/README.me docs.
