### ISSUE TITLE
Channel gets stuck on duplicates in root certificate list

### ISSUE THREAD

**Issue by jaaant** [grpc/grpc#17646]
### What version of gRPC and what language are you using?
 1.17.1, C++
 
### What operating system (Linux, Windows, …) and version?
 Windows 10, Windows 8
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio Professional 2017, version 15.6.2
 
### What did you do?
 We read certificates from Windows root certificate store and used them as root certificates (grpc::SslCredentialsOptions::pem_root_certs) for a secure gRPC channel. In some cases, the certificate list contained duplicates (if a certificate has been installed for both the current user and the local machine, it shows up twice for the current user). Then we called grpc::ChannelInterface::WaitForConnected to establish the connection.
 
### What did you expect to see?
 The connection gets established and the channel works normally.
 
### What did you see instead?
 When the certificate list contained no duplicates, the channel worked as expected. However, with duplicate certificates the attempt to connect timed out, and Wireshark showed no traffic to the server.

We have now bypassed the issue for ourselves by filtering duplicates out of the certificate list, but the underlying problem in the library remains.

Speculation: A root certificate signs itself, and thus duplicate root certificates sign each other. Perhaps the channel attempts to follow certificate chains, and ends up in an infinite loop?

**Comment by yihuazhang** [comment]
Thanks @jaaant for reporting the issue. 

1) When you say "duplicates", does it mean those certificates have the same content or different contents but for the same CA? In both cases, if all "duplicate" certificates are valid, I do not think there will be a problem. But, the problem happens when one of them is invalid (e.g., expired), and that's the one used for validation. 

2) gRPC also ships its own valid root certificate list, and is it possible to use them instead?

**Comment by yihuazhang** [comment]
Let me take back my argument on #1. In `ssl_transport_security.cc`, it uses `X509_STORE_add_cert` to add each root certificate to the cert store, and if there is any duplication in contents,  `x509_store_load_certs` will return an error. So I assume in your use case, all duplicates will have the same contents.

**Comment by yihuazhang** [comment]
Could you please try #17664, and see if the problem goes away?

**Comment by jaaant** [comment]
That does seem to fix the problem.
