### ISSUE TITLE
Bazel build is broken on macOS

### ISSUE THREAD

**Issue by allevato** [grpc/grpc#17649]
### What version of gRPC and what language are you using?

Clone from master. 
 
### What operating system (Linux, Windows, …) and version?

macOS 10.13.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Xcode 10.1
 
### What did you do?

In the workspace directory, run `bazel build :all`.

### What did you expect to see?

Successful build.
 
### What did you see instead?

An error in one of the external C dependencies:

```
ERROR: /private/var/tmp/_bazel_allevato/09be068f3a9c91bfcb2786dd3fddded0/external/com_github_cares_cares/BUILD.bazel:65:1: C++ compilation of rule '@com_github_cares_cares//:ares' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -iquote ... (remaining 36 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_cares_cares/ares_process.c:198:10: error: use of undeclared identifier 'MSG_NOSIGNAL'
  return swrite(s, data, len);
         ^
external/com_github_cares_cares/setup_once.h:204:54: note: expanded from macro 'swrite'
                                    (SEND_TYPE_ARG4)(SEND_4TH_ARG))
                                                     ^
external/com_github_cares_cares/setup_once.h:126:22: note: expanded from macro 'SEND_4TH_ARG'
#define SEND_4TH_ARG MSG_NOSIGNAL
                     ^
1 error generated.
```

**Comment by rohansingh** [comment]
I ran into similar issues, even after following `BUILDING.md`. In my case, I was using Command Line Tools for Xcode instead of a full Xcode installation. I found that `make` was successful but `bazel build :all` worked.

The issues were resolved once I installed Xcode, used `xcode-select` to switch to that installation, and ran `bazel clean --expunge`.

**Comment by allevato** [comment]
Sorry for the very late delay on this; I got pulled onto other work.

I've found the problem—the `cares` BUILD file only recognizes the `darwin` CPU value, but Bazel also allows `darwin_x86_64` (and that is what the Apple build rules recommend). Until that gets cleaned up, I'm sending a PR to add the alternate CPU value. After doing that, the repository builds properly.
