### ISSUE TITLE
Advertise only 'h2' via ALPN

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1765]
Finally remove draft specs.

**Comment by ctiller** [comment]
Do not fix before June 20.

**Comment by ctiller** [comment]
@louiscryan @ejona86 @iamqizhao @a11r - thoughts on if/when we should do this?

**Comment by ejona86** [comment]
I think it is likely safe to do now. I think previously we thought "as we go Beta" was a fine time, so now seems about the point to follow through.
