### ISSUE TITLE
Thread grpc_global_timer  has high cpu usage

### ISSUE THREAD

**Issue by panjxgithub** [grpc/grpc#17657]
### What version of gRPC and what language are you using?
 v1.11.0 ,   C/C++

const char* grpc_version_string(void) { return "6.0.0"; }
 
### What operating system (Linux, Windows, …) and version?
 linux, ppc e500v2   32bit cpu
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.9.3
 
### What did you do?
ONLY call grpc_init

### What did you see instead?
CPU  high usage 

Process ID  Thread ID        Thread Type                              Usage
      1000     3035432064    grpc_global_timer                     37%

thread info:
Thread 3035432064 (Thread grpc_global_timer):
#00 libgrpc_unsecure.so()
#01 libgrpc_unsecure.so()
#02 (_ZN9grpc_core7ExecCtx3NowEv)   ==>  grpc_core::ExecCtx->Now()
#03 libgrpc_unsecure.so()
#04 (_Z16grpc_timer_checkPi)               ===> grpc_timer_check
#05 libgrpc_unsecure.so()
#06 libgrpc_unsecure.so()
#07 libpthread.so.0() [0xfdf7e24]
#08 (clone)
Thread 3035432064 (Thread grpc_global_timer):
#00 libpthread.so.0() [0xfe04974]
#01 (pthread_cond_timedwait)
#02 (gpr_cv_wait)
#03 libgrpc_unsecure.so()
#04 libgrpc_unsecure.so()
#05 libpthread.so.0() [0xfdf7e24]
#06 (clone)
Thread 3035432064 (Thread grpc_global_timer):
#00 (gpr_convert_clock_type)
#01 (_Z23grpc_millis_to_timespeci14gpr_clock_type)
#02 libgrpc_unsecure.so()
#03 libgrpc_unsecure.so()
#04 libpthread.so.0() [0xfdf7e24]
#05 (clone)

code:
![image](https://user-images.githubusercontent.com/46445566/50805079-c324c880-132b-11e9-8577-eeba088da230.png)
![image](https://user-images.githubusercontent.com/46445566/50805104-d6d02f00-132b-11e9-8e9a-3496f709c304.png)
![image](https://user-images.githubusercontent.com/46445566/50805115-e2235a80-132b-11e9-922f-04842bde2a15.png)

I don't understand,  this high cpu usage happened?
Is this issue #14350 ?  But the system start only 1 day.
Thanks.

**Comment by muxi** [comment]
It's would be surprising that this just started to happen recently? Have you been using this version for a long time?

**Comment by panjxgithub** [comment]
Our team got the root cause.
When use grpc_core::ExecCtx->Now() to get the system time.  kernel use the soft-float， not the hard-float.
Add compile option,   -mabi=spe -mspe -mfloat-gprs=double -te500v2
