### ISSUE TITLE
Dedicated Slack channel

### ISSUE THREAD

**Issue by fenos** [grpc/grpc#17670]
Hi there!

I was wondering why there isn't a dedicated **Slack Team** where, the community and gRPC members could speak and troubleshoot gRPC all together in real-time or near.

A good list of channel for the start could be:

- General
- Announcements

- gRPC C++ 
- gRPC Java
- gRPC Python
- gRPC NodeJS
- gRPC {any other language}

- gRPC-Web

- protocol buffer
- protobuf.js
- protobuf {any language}

- Toolings

- 3d Party projects
- BloomRPC

It could be also worth to think about a discord server.

gRPC is becoming big topic all around! I love this technology and i'd love to speak about it all the time with the community.

Apologise if this is not the right place to open this kind of issue (please advice the best place if that' the case).

Regards

**Comment by madscientist42** [comment]
One wonders why they don't use a Gitter in the same manner.  It's available and up for them and would be tied to issues, commits, etc. from the project.

**Comment by gnossen** [comment]
We actually *do* have [a Slack](https://grpc-oss.slack.com) that I believe predates this issue. However, I don't know how actively members of the team are currently engaging with it.

**Comment by hsaliak** [comment]
We have a mailing list - https://grpc.io/community/ 
An IRC channel - freenode #grpc 
A Gitter channel - https://gitter.im/grpc/grpc

How would adding Slack to this official set of channels help? Perhaps the question is to popularize the gitter presence more?
What about doubling down on IRC?

**Comment by fenos** [comment]
I Believe that using a slack channel as the default real-time chat and communications makes a big difference.

- 1. 90% of companies/developers use slack and they have it already installed in their PC / MAC
- 2. Cross Platform
- 3. Organising topics with channels really makes a difference
- 4. Search history it's amazing

I could go further and list all the great functionalities of slack, but we all know them 😄 


The main point is that, slack it's much more widely used then gitter for community-based real-time chats. It's just remove the needs of 1 extra app to be installed and it can be organised way better.
