### ISSUE TITLE
Python : error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.

### ISSUE THREAD

**Issue by spl0i7** [grpc/grpc#17685]
### What version of gRPC and what language are you using?
 1.17.1

### What operating system (Linux, Windows, …) and version?
 Linux (Debian Buster) 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.2
 
### What did you do?
I am trying to write Grpc client in python for a Grpc server written in go. My client code looks like

```python
with open('server.crt', 'rb') as f:    trusted_certs = f.read()

credentials = grpc.ssl_channel_credentials(trusted_certs)
ops = [('grpc.ssl_target_name_override', 'secure.app')]
channel = grpc.secure_channel('localhost:443', credentials, ops)
stub =  SomeStub(channel)
stub.SomeMethod(Request())

```
but for some reasons it's unable to connect to the server, giving me `CERTIFICATE_VERIFY_FAILED` error.
### What did you expect to see?
 
I expected client to connect to the server, because my go client works perfectly well but python client isn't working well. Here's my what my go client looks like

```go

       var opts []grpc.DialOption

	caFile := testdata.Path(crtPath)


	creds, _ := credentials.NewClientTLSFromFile(caFile, "secure.app")

	opts = append(opts, grpc.WithTransportCredentials(creds))
	conn, _ := grpc.Dial("localhost:443", opts...)
        defer conn.Close()
	client := grpc_api.SomeClient(conn)
	ctx, _ := context.WithTimeout(context.Background(), 10*time.Second)

	res, _ := client.SomeMethod(ctx, &grpc_api.Request{})

```
 
### What did you see instead?
 
Instead I saw following error
```
E0110 19:17:10.922064705   23315 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.

```

**Comment by spl0i7** [comment]
Go has better error reporting mechanism, tells exactly what's wrong but python's error response is bit cryptic and difficult to understand.

**Comment by jiangtaoli2016** [comment]
@srini100 Can someone in your team reproduce the error first? The error message is a generic handshake error indicating certificate is not correct. It is hard to tell without reproducing.

**Comment by spl0i7** [comment]
I figured out the problem, I was using [Certstrap](https://github.com/square/certstrap) to generate the certificate but looked over a fine detail, turns out that for self signed certificate issuer DN must match its subject [rfc5280](DN.http://tools.ietf.org/html/rfc5280#section-3.2). So I did exactly that and everything worked. Weird how go client worked without it though.

**Comment by srini100** [comment]
@spl0i7, thanks for figuring this out. Opened an [issue](https://github.com/grpc/grpc-go/issues/2566) in gRPC-Go repo. Closing this.
