### ISSUE TITLE
gRPC C++ Client Side Fork Support

### ISSUE THREAD

**Issue by robertmu** [grpc/grpc#17695]
Do we have plans to do the following work?
1.  Support fork in ev_epollex_linux.cc like ev_epoll1_linux.cc?
2. make GRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK configurable when compiling c++ client?

**Comment by ericgribkoff** [comment]
> 1. Support fork in ev_epollex_linux.cc like ev_epoll1_linux.cc?

No current plans to add this; we aren't opposed to it, but epoll1 is the default in our python distribution and seems sufficient for current use. For locally compiled versions of gRPC, you can choose epoll1 via the [`GRPC_POLL_STRATEGY`](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) environment variable.

> 2\. make GRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK configurable when compiling c++ client?

No, we do not support fork() without exec() for C++ clients. C++ does not have the same threading limitations that encourages Python clients to fork, so you are better off using threads, or fork() followed by an exec(). gRPC C++ clients do not have a channel close API nor any easy means of ensuring gRPC core shuts down in the child post-fork, which is a requirement for fork support. You can set this already via the `EXTRA_DEFINES` environment variable using make, but it will not work in the same way as with our Python/PHP clients unless you manually ensure gRPC Core shuts down in the child process (which is not trivial), and is not a supported use case.
