### ISSUE TITLE
grpc_csharp_plugin.exe crashes on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1769]
When trying to use grpc_csharp_plugin on windows (for the helloworld example):

C:\Users\jtattermusch\github\grpc-common\csharp>protoc -I Greeter/protos --csharp_out=Greeter --grpc_out=Greeter --plugin=protoc-gen-grpc=grpc_csharp_plugin.exe
 Greeter/protos/helloworld.proto
[libprotobuf FATAL c:\users\jtattermusch\github\grpc\third_party\protobuf\src\go
ogle\protobuf\io\zero_copy_stream_impl_lite.cc:190] CHECK failed: (count) <= (ta
rget_->size()):
--grpc_out: protoc-gen-grpc: Plugin failed with status code 3.

**Comment by jtattermusch** [comment]
Looks like this is happening in Printer destructor after successfully writing all the code to it (by GetServices in csharp_generator.cc).

Printer::~Printer() {
  // Only BackUp() if we have called Next() at least once and never failed.
  if (buffer_size_ > 0 && !failed_) {
    output_->BackUp(buffer_size_);
  }
}

**Comment by jtattermusch** [comment]
This chunk of code breaks for me on Windows.

grpc::string ThisWillCrash() {
  grpc::string output;
  StringOutputStream output_stream(&output);
  Printer out(&output_stream, '$');
  out.Print("AAA");
  return output;
}

**Comment by jtattermusch** [comment]
For reasons unknown to me, this one works:
```
grpc::string ThisWillCrash() {
  grpc::string output;
  StringOutputStream output_stream(&output);
  {
    Printer out(&output_stream, '$');
    out.Print("AAA"); 
  }
  return output;
}
```

**Comment by jtattermusch** [comment]
An explanation: http://programmers.stackexchange.com/questions/258238/move-semantics-in-c-move-return-of-local-variables

**Comment by nicolasnoble** [comment]
This seems similar to what was reported previously on another reported issue that I can't find right now. The problem was concerning VS2010 but maybe it's on VS2013 as well. The reported issue was that the destruction order is messed up. The destruction order during function exit seems to be so that you destroy "output_stream" before destroying "out". As a result, the destructor of the Printer "out" tries to flush its cached buffer to a non-existent string buffer.

**Comment by nicolasnoble** [comment]
Note that the appropriate fix in that case is to explicitly flush the Printer before exitting the functions.

I'm surprised this actually is the problem, because the C++ generation actually works fine. We'd have the same issue there. Unless this is random.
