### ISSUE TITLE
BuildPackageProtos exits with code zero on failure

### ISSUE THREAD

**Issue by sergeant-wizard** [grpc/grpc#17703]
### What version of gRPC and what language are you using?
 
1.17.1 python
 
### What operating system (Linux, Windows, …) and version?
 
Linux, ubuntu 16.04.1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
python 2.7.12, python 3.5.5
 
### What did you do?

```
# setup.py

from setuptools import setup
from grpc_tools.command import BuildPackageProtos


setup(
    package_dir={
        '': 'protos',
    },
    cmdclass={
        'build_proto': BuildPackageProtos,
    },
)
```

```
# protos/foo.proto

syntax = "proto3";

badsyntax
```

output 

```
$ python setup.py build_proto
running build_proto
foo.proto:4:1: Expected top-level statement (e.g. "message").
warning: ['grpc_tools.protoc', '--proto_path=/home/ryo/proto_setup/protos', '--proto_path=/home/ryo/.pyenv/versions/proto_setup3/lib/python3.5/site-packages/grpc_tools/_proto', '--python_out=/home/ryo/proto_setup/protos', '--grpc_python_out=/home/ryo/proto_setup/protos', '/home/ryo/proto_setup/protos/foo.proto'] failed% 

$ echo $?
0
```

exit code *0*

 
### What did you expect to see?
 
non-zero exit code
 
### What did you see instead?

exit code 0
 

### Anything else we should know about your project / environment?

I think an exception should be raised like so:
https://github.com/grpc/grpc/commit/f35c3f3f73f59550ea617e00c47cd2ead3e81d3f

**Comment by lidizheng** [comment]
This behavior is introduced by https://github.com/soltanmm/grpc/commit/ebf81e7a0540a01079ac03661426cd3771664de7#diff-32f55eef2dbde5450848d136fa65ba7b. I agree with you that if the command exit with non-zero code, it should raise a exception.
