### ISSUE TITLE
Cannot build grpc_cli

### ISSUE THREAD

**Issue by prestonvanloon** [grpc/grpc#17706]
### What version of gRPC and what language are you using?
 Master
 
### What operating system (Linux, Windows, …) and version?
 Linux - Ubuntu 18
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Python 2.7.15rc1
 
### What did you do?
Followed the directions here: https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md
```
cd /tmp
git clone git@github.com:grpc/grpc.git
cd grpc
git submodule update --init
make grpc_cli
```
 
### What did you expect to see?
 It builds without issue.
 
### What did you see instead?
Similar to #17472 

```
[HOSTCXX] Compiling src/compiler/ruby_generator.cc
src/compiler/ruby_generator.cc: In function ‘grpc::string grpc_ruby_generator::GetServices(const FileDescriptor*)’:
src/compiler/ruby_generator.cc:165:25: error: ‘const class google::protobuf::FileOptions’ has no member named ‘has_ruby_package’; did you mean ‘has_java_package’?
     if (file->options().has_ruby_package()) {
                         ^~~~~~~~~~~~~~~~
                         has_java_package
src/compiler/ruby_generator.cc:166:38: error: ‘const class google::protobuf::FileOptions’ has no member named ‘ruby_package’; did you mean ‘java_package’?
       package_name = file->options().ruby_package();
                                      ^~~~~~~~~~~~
                                      java_package
Makefile:2963: recipe for target '/tmp/grpc/objs/opt/src/compiler/ruby_generator.o' failed
make: *** [/tmp/grpc/objs/opt/src/compiler/ruby_generator.o] Error 1
```

**Comment by apolcyn** [comment]
Do you have an older version of `protoc` already installed on your system? The latest `grpc_ruby_plugin` (the piece of the build that's failing here) needs protoc 3.6 or later.

**Comment by prestonvanloon** [comment]
Yes.
```
libprotoc 3.3.0
```

**Comment by prestonvanloon** [comment]
I upgraded to 3.6.1 and I still have the same issue.

**Comment by apolcyn** [comment]
Sorry not sure exactly how, but I suspect the problem is very likely that you are still comping the `grpc_ruby_plugin` with an old protobuf library.

**Comment by prestonvanloon** [comment]
Is there a precompiled binary I can download for grpc_cli? 

My system has protoc 3.6.1 and I followed the steps in my original issue description so I'm not sure how I could be using an old protobuf library.

**Comment by prestonvanloon** [comment]
I am still stuck here. How can I proceed?

**Comment by yang-g** [comment]
The previous reply root-caused your issue.
You can try to make with `HAS_SYSTEM_PROTOBUF=false` to force using the third_party version of protobuf, maybe that will resolve your problem.
