### ISSUE TITLE
[.NET Core, Windows] gRPC server shutdown blocks if child process was spawned 

### ISSUE THREAD

**Issue by yulia-d** [grpc/grpc#17704]
Running gRPC C# 1.17.1 under .NET Core on Windows.
One process starts a gRPC server and then spawns a child process. After having exchanged a few gRPC calls with yet another process it needs to close, but is unable to close the server gracefully - ShutdownAsync task never completes until the child process is killed, though in our use case that child process needs to stay up.

I understand that gRPC has [issues with forking in Python](https://github.com/grpc/grpc/blob/master/doc/fork_support.md). Could it be that the same behavior that causes these issues is responsible for my problem? 

Note 1. The child that blocks the shutdown doesn't use gRPC.
Note 2. If gRPC server is started AFTER spawning the child the problem stops reproducing.
Note 3. The child is spawned using .NET System.Diagnostics.Process API. If the latter is replaced with CreateProcess P/Invoke with inheritHandles=false, the problem disappears. (We consider it a work-around, not the solution, since we are aiming for cross-platform code.)
Note 4. gRPC peers are also spawned by the main process, but are not relevant since they are closed by the time the main process starts closing. Some gRPC interaction is required to reproduce the problem - without any interaction or with too little of it the server shuts down normally.

**Comment by jtattermusch** [comment]
@yulia-d  we might a a work-in-progress fix for this problem in #18060, but we still don't have a confirmation that those changes actually fix the problem you reported.

Would you be able to test those changes?

**Comment by yulia-d** [comment]
@jtattermusch I hope I would. How do I do that?

**Comment by jtattermusch** [comment]
> @jtattermusch I hope I would. How do I do that?

I will later post link to grab patched nuget packages to test with.

**Comment by jtattermusch** [comment]
@yulia-d I have built nuget packages than contain the patch from #18060,
can you download them and confirm if the patch fixes this issue or not?
https://storage.googleapis.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/windows/grpc_build_packages/5341/20190314-085942/github/grpc/artifacts/csharp_nugets_windows_dotnetcli.zip
(you need to store the nugets to a local nuget feed and install them to your project from there).

**Comment by jtattermusch** [comment]
@yulia-d  any luck verifying the fix from #18060?

**Comment by yulia-d** [comment]
No capacity for it at the moment, but hopefully will get to it some time next week.

**Comment by jtattermusch** [comment]
@yulia-d  thanks for the confirmation. You can follow https://github.com/grpc/grpc/pull/18060 for updates. After a final round of review, I think we should be able to merge, which would mean that the fix would land in v1.21.0 release

**Comment by jtattermusch** [comment]
This should be resolved by #18060.
