### ISSUE TITLE
"Could not auto-detect platform

### ISSUE THREAD

**Issue by 987410** [grpc/grpc#17716]
Hi, Lemonn,

I followed your step, but got the error below. what 's wrong with that? THX a lot

                from src/core/lib/gpr/alloc.cc:19:
include/grpc/impl/codegen/port_platform.h:357:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^
include/grpc/impl/codegen/port_platform.h:392:2: error: #warning "GPR_PLATFORM_STRING not auto-detected" [-Werror=cpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^
In file included from include/grpc/support/port_platform.h:22:0,
                 from src/core/lib/gpr/alloc.cc:19:
include/grpc/impl/codegen/port_platform.h:442:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^
include/grpc/impl/codegen/port_platform.h:446:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^
include/grpc/impl/codegen/port_platform.h:452:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^
include/grpc/impl/codegen/port_platform.h:458:2: error: #error Must define exactly one of GPR_MSVC_TLS, GPR_GCC_TLS, GPR_PTHREAD_TLS, GPR_CUSTOM_TLS
 #error Must define exactly one of GPR_MSVC_TLS, GPR_GCC_TLS, GPR_PTHREAD_TLS, GPR_CUSTOM_TLS
  ^
cc1plus: all warnings being treated as errors
Makefile:2968: recipe for target '/home/liu/Downloads/grpc/objs/opt/src/core/lib/gpr/alloc.o' failed
make: *** [/home/liu/Downloads/grpc/objs/opt/src/core/lib/gpr/alloc.o] Error 1

The release that I used was the 1.1.0.

I think that your error comes from use **/usr/bin/ld** to link objects that were compilated to ARM. To link these objects, you need to use the ARM linkers ( **LD=arm-xilinx-linux-gnueabi-ld** and **LDXX=arm-xilinx-linux-gnueabi-g++** ). If your make command have these params and still not working, the problem maybe comes from this:

```
export GRPC_CROSS_COMPILE=true
export GRPC_CROSS_AROPTS="cr --target=elf32-little"
```

If **GRPC_CROSS_COMPILATION** is set, the makefile use the command parammeters to compile and link grpc. If not, the default compiler and linker is used.

The steps that I finally followed were this:
* Compile and install protobuf.
```
cd grpc
git submodule update --init
cd third_party/protobuf
./autogen.sh
./configure
make && make check && sudo make install && sudo ldconfig
```
* Compile and install grpc.
```
cd -
make && sudo make install && sudo ldconfig
```
* Clean the current build.
```
make clean
```
* Make grpc plugins.
```
make plugins
```
* Set environment variables for cross compilation.
```
export GRPC_CROSS_COMPILATION=true
export GRPC_CROSS_AROPTS="cr --target=elf32-little"
```
* Compile grpc as static with this command:

```
make HAS_PKG_CONFIG=false \
    CC=arm-xilinx-linux-gnueabi-gcc \
    CXX=arm-xilinx-linux-gnueabi-g++ \
    RANLIB=arm-xilinx-linux-gnueabi-ranlib \
    LD=arm-xilinx-linux-gnueabi-ld \
    LDXX=arm-xilinx-linux-gnueabi-g++ \
    AR=arm-xilinx-linux-gnueabi-ar \
    PROTOBUF_CONFIG_OPTS="--host=arm-xilinx-linux-gnueabi --with-protoc=/usr/local/bin/protoc" static
```

I hope this help you a little :)

Regards,
J. A.

_Originally posted by @AngryLemonn in https://github.com/grpc/grpc/issues/9719#issuecomment-284843131_

**Comment by AngryLemonn** [comment]
Hi,

The makefile for the las current version of GRPC says this:

>The steps for cross-compiling are as follows: 
>
>First, clone and make install of grpc using the native compilers for the host. Also, install protoc (e.g., from a package like apt-get). Then clone a fresh grpc for the actual cross-compiled build. Set the environment variable GRPC_CROSS_COMPILE to true. Set CC, CXX, LD, LDXX, AR, and STRIP to the cross-compiling binaries. Also set PROTOBUF_CONFIG_OPTS to indicate cross-compilation to protobuf (e.g., PROTOBUF_CONFIG_OPTS="--host=arm-linux --with-protoc=/usr/local/bin/protoc" ). Set HAS_PKG_CONFIG=false. To build tests, go to third_party/gflags and follow its ccmake instructions. Make sure that you enable building shared libraries and set your prefix to  something useful like /usr/local/cross. You will also need to set GRPC_CROSS_LDOPTS and GRPC_CROSS_AROPTS to hold additional required arguments for LD and AR (examples below)
>
>Then you can do a make from the cross-compiling fresh clone!

When I wrote the issue and post the steps, I made a mistake with one flag. Change the step of `export GRPC_CROSS_COMPILATION=true` with `export GRPC_CROSS_COMPILE=true` and try again with a fresh grpc.

Regards,
J. A.

**Comment by a11r** [comment]
Please reopen if there is anything pending.
