### ISSUE TITLE
CMake with C++ and iOS compatible 

### ISSUE THREAD

**Issue by madhusameena** [grpc/grpc#17714]
Hi I am trying to build grpc based application
We have common logic in C++ (Using CMake)
And Swift based application for native iOS

While building grpc based libraries (CMake based) on mac which is compatible with mobile iOS (we use tool chain for this) - It is not able to find protoc and grpc installed applications

any clue how to build C++ CMake application with gRPC which should be compatible with iOS device ?

**Comment by muxi** [comment]
Did you install protoc? And how is cmake configured to use protoc? I feel using cmake with protoc is not much different from using any utilities installed in your system.

**Comment by Dimon4eg** [comment]
@madhusameena take a look at https://github.com/heroiclabs/nakama-cpp/tree/master/cmake
`grpc` builds fine with those ios toolchains
