### ISSUE TITLE
Gem for illumos

### ISSUE THREAD

**Issue by gbulfon** [grpc/grpc#17748]
### What version of gRPC and what language are you using?
1.18.0 - Ruby 
 
### What operating system (Linux, Windows, …) and version?
 XStreamOS / illumos (OpenSolaris - Solaris 11)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.7
 
### What did you do?
I could build all the grpc component from source, install everything in a proto area for packaging and published the component that is now installed on a running system.
Now I want this running system to "gem install grpc" without rebuilding any native stuff, because I already have everything from the built package : I would like it to use all my built stuff.
Trying to build the gem from the source tree gives errors inside the "third_party" tree, which is not used during the component build because I already have all as system libs.

 
### What did you expect to see?
I would like to build a gem that reuse my built stuff and system libs. 
 
### What did you see instead?
Always trying to look for native stuff as third_party which I already have in the system.
 
### Anything else we should know about your project / environment?
I also tried from the running system a gem install with "--use-system-libraries", but it will always try to build the third_party stuff.

**Comment by sanjaypujare** [comment]
@apolcyn @gbulfon pls adjust priority as needed

**Comment by apolcyn** [comment]
@gbulfon do you mean that you would like new `gem install grpc` commands to use your system libraries? E.g., use the system openssl rather than boringssl? Or that you would like the re-use build artifacts from previous `gem install grpc`s on the same system? The former is doable but the latter likely isn't possible.

**Comment by gbulfon** [comment]
Hi, forme I think.
I mantain the XStreamOS distribution packages, so I already prepared all the required ones, including grpc as system libraries.
Once I gem install grpc with "--use-system-libraries", it sill tries to build some third party stuff.
For example, I already built and installed c-ares, but still it's trying to build it internally : I had to bring my own ares_config.h from my userland build into the installing machine to see it continue building its own ares (beacuse it has no clue about Solaris), but then ended with errors because it needs some of my tricks to build (which I already did on my own build, installed in the system).
Also zlib is built, which I have, so for no reason.

**Comment by gbulfon** [comment]
Or alternatively, build my own gem in the grpc component source tree, now that I have the "gmake install" done, but containing references to my own system libs.

**Comment by gbulfon** [comment]
Hi, could you help me how to achieve "use all available system libraries" on "gem install grpc"?

**Comment by gbulfon** [comment]
I've seen many "HAS_SYSTEM..." variables in the Makefile building the third_party libs.
I'm trying to pass these to "gem install" so that it will reach gmake, but I can't do it.
Here I'm trying it directly as call env:

```
sonicle@cloudserver:~/.bundle$ PATH=/usr/gnu/bin:$PATH HAS_PKG_CONFIG=true HAS_SYSTEM_CARES=true HAS_SYSTEM_ZLIB=true gem install grpc
Building native extensions.  This could take a while...
ERROR:  Error installing grpc:
        ERROR: Failed to build gem native extension.

    current directory: /usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0/src/ruby/ext/grpc
/usr/ruby/2.3/bin/ruby -r ./siteconf20190122-7000-1xnwebw.rb extconf.rb
Building internal gRPC into /usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0/src/ruby/ext/grpc/libs/opt
make: Entering directory '/usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0'
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
mkdir -p `dirname /usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o`
[C]       Compiling third_party/zlib/crc32.c
mkdir -p `dirname /usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/compress.o`
[C]       Compiling third_party/zlib/deflate.c
mkdir -p `dirname /usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/deflate.o`
mkdir -p `dirname /usr/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.18.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/crc32.o`
[C]       Compiling third_party/zlib/gzclose.c
....

```
but they're also inside the bundle config file as:

`BUNDLE_BUILD__GRPC: "--use-system-libraries HAS_PKG_CONFIG=true HAS_SYSTEM_CARES=true HAS_SYSTEM_ZLIB=true"`


Any idea how to pass these to gem install up to gmake and let it skip building of third_party libs which I already have in my system???

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
