### ISSUE TITLE
how to load multi root certs on server？

### ISSUE THREAD

**Issue by BalrogMithrandir** [grpc/grpc#17743]
### What version of gRPC and what language are you using?
 the latest version download at 2019.01.15
 
### What operating system (Linux, Windows, …) and version?
linux  ubuntu 1404
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Python 2.7.6

### What did you do?
I'am using the examples/cpp/helloworld/ to run a grpc server with ssl  mutual authentication. And the multi clients have different rootCA.  After search from related issue, i tried three method:

First I tried to use default root path ```GRPC_NOT_USE_SYSTEM_SSL_ROOTS``` and copy all root ca to the default path, the server ssl code :
```c
    grpc::SslServerCredentialsOptions sslOps;
    sslOps.pem_root_certs = "";
    gpr_setenv("GRPC_NOT_USE_SYSTEM_SSL_ROOTS", "true");
    sslOps.pem_key_cert_pairs.push_back ( keycert );
    sslOps.force_client_auth = true;
    sslOps.client_certificate_request = GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY;

    builder.AddListeningPort(server_address, grpc::SslServerCredentials( sslOps ));
```

and when i run client , i got```E0117 00:19:27.373245641   47942 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.```

Then I tried to use cat cmd to combine all root ca files which  i need to a single file like this: 
```cat ./*.crt > roots.pem```

and then use GRPC_DEFAULT_SSL_ROOTS_FILE_PATH:
```c
    grpc::SslServerCredentialsOptions sslOps;
    sslOps.pem_root_certs = "";
    gpr_setenv("GRPC_DEFAULT_SSL_ROOTS_FILE_PATH", "/home/caros/src/grpc/examples/cpp/helloworld/rootca/roots.pem");
    sslOps.pem_key_cert_pairs.push_back ( keycert );
    sslOps.force_client_auth = true;
    sslOps.client_certificate_request = GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY;
    builder.AddListeningPort(server_address, grpc::SslServerCredentials( sslOps ));
    GreeterServiceImpl service;
    builder.RegisterService(&service);
```
And after I run the client and server, i also get ```E0117 00:36:28.794324705   47982 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED```

At last I tried to use  cat cmd to combine all root ca files which  i need to a single file again, and to load this single file in code:
```c
    read ( "cert/server.crt", cert );
    read ( "cert/server.key", key );
  read ( "rootca/roots.pem", root );
    ServerBuilder builder;

    grpc::SslServerCredentialsOptions::PemKeyCertPair keycert =
    {
        key,
        cert
    };
    grpc::SslServerCredentialsOptions sslOps;
    sslOps.pem_root_certs = root;
    sslOps.pem_key_cert_pairs.push_back ( keycert );
    sslOps.force_client_auth = true;
    sslOps.client_certificate_request = GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY;
    builder.AddListeningPort(server_address, grpc::SslServerCredentials( sslOps ));
    GreeterServiceImpl service;
    builder.RegisterService(&service);

```
And this time i got this when client try to connect to server: ```E0116 23:19:33.155545952   47368 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
```

I am sure that the root ca is correct because when i use ```sslOps.pem_root_certs``` to load each single root ca to connect with signle client, it's ok on server.

### What did you expect to see?
client connect to server with mutual authentication, and server run without ssl error
 
### What did you see instead?
``` E0117 00:39:37.811897864   48020 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.```

Or ```E0116 23:19:33.155545952   47368 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
```

**Comment by BalrogMithrandir** [comment]
@lidizheng hi, can anybody give me some suggestions?

**Comment by lidizheng** [comment]
@yang-g  @jiangtaoli2016 Can you please take a look?

**Comment by jiangtaoli2016** [comment]
I am confused about what you try to achieve. 

If your server cert is self-signed or signed by your own CA, you can just config your grpc client with `sslOps.per_root_certs = server_ca_root`
Why you want to combine your own CA root cert with the system roots?

**Comment by BalrogMithrandir** [comment]
@jiangtaoli2016 hi, thank you for reply first. Maybe I didn't make myself clear, let me give a example about my question:  I have a server and two clients--client A and client B. Client A and B have different root CA, so the server need to load two root CA certificates, my question is that how to load these two root CA on the server?  Look forward to your reply!

**Comment by jiangtaoli2016** [comment]
You should be able to combine two root CA certificates into one file. Could you show us the combined root pem file?

You can take the following as an example 
https://github.com/grpc/grpc/blob/master/etc/roots.pem

Each certificate is separated with
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----

**Comment by BalrogMithrandir** [comment]
@jiangtaoli2016 Thank you, it works.  It didn't work before because i use two root ca with the same CN, now. Thank you!
