### ISSUE TITLE
Add public object UserData to C# ServerCallContext

### ISSUE THREAD

**Issue by chwarr** [grpc/grpc#17759]
In the C# implementation, consider adding a `public object UserData { get; set; }` property/field/method to `ServerCallContext`.

Such a field could be used to [thread state between collaborating interceptors and calls](https://github.com/grpc/grpc/issues/15757#issuecomment-445053226) cheaper and more nicely bracketed than `AsyncLocal<T>`. [PR #17733, "Make C# ServerCallContext implementation agnostic"](https://github.com/grpc/grpc/pull/17733) may end up refactoring `ServerCallContext` into an abstract class; however, I don't see a way to use my own concrete `ServerCallContext` child class without wrapping all of call dispatching, so I think something more is needed here.

**Comment by jtattermusch** [comment]
Would it make sense to provide something more type-safe? I'm thinking a bag of values accessed by their type, something like this:
```
var myData = context.UserData.Get<MyTypedUserDataStorage>();
```

**Comment by chwarr** [comment]
I like the `.Get<MyTypedUserDataStorage>()` proposal. This also solves the problem of how to avoid stepping on another interceptor stack's toes: they need to use different types. This may end up with some wrapper types just for distinguishing purposes, but that seems like an OK compromise to avoid implementing `UserData.Get<MyType>("my name")`

**Comment by chwarr** [comment]
If we can settle on a design, it looks like I'll have time to contribute the implementation.

I think the public interface is just:

````
public interface IUserData {
    T Get<T>();
    void Set<T>(T instance);
}
```

The setter allows resetting the instance if there's a type that someone wants to use the doesn't have a `Reset()` member (e.g., immutable types).

Not sure if `T` needs a `class` constraint. I'm thinking no, so you can put a `Guid` or similar in the user data without explicitly wrapping in a box.

**Comment by jtattermusch** [comment]
@jskeet  @apolcyn  do you have opinions on the proposed API design?

@JamesNK @JunTaoLuo would this new API be useful for Grpc.AspNetCore.Server?

**Comment by dpsenner** [comment]
@chwarr if the public interface is the one mentioned in your comment, doesn't it make sense to let it be a getter and a setter of the type `IServiceProvider` instead, wouldn't it? I.e. something along the lines of:

```csharp
public class ServerCallContext
{
    IServiceProvider ServiceProvider { get; set; }
}
```

There already exists a good implementation for `IServiceProvider` and I do not see a reason that justifies reinventing that wheel.

**Comment by jskeet** [comment]
I don't know enough about the use case to be of much help, but if this is meant to provide arbitrary context information, the `Get<>` approach works for me.

**Comment by chwarr** [comment]
> does it make sense to let it be a getter and a setter of the type `IServiceProvider` instead? I.e. something along the lines of:
> 
> ```cs
> public class ServerCallContext
> {
>     IServiceProvider ServiceProvider { get; set; }
> }
> ```

@dpsenner, I tried to come up with a way to make just a mutable `IServiceProvider` work, but I can't. The fundamental problem is that `IServiceProvider` doesn't provide any way to add new types to the UserData.

I see the need to be able to compose multiple sets of collaborating interceptors. For example, a service consumes an authN + authZ set developed by team A, an instrumentation set developed by team B, and a cross-cutting business logic set developed by team C. Each of these sets consists of multiple interceptors, depending on which functionality the service wants to opt-in to.

These sets of interceptors don't collaborate with each other to store their per-call data in the same type, but they also don't conflict with each other. (The interceptors within a set do collaborate with each other.)

A single, settable `IServiceProvider` doesn't work in this case. It either forces them to conflict with each other or it forces them to collaborate with each other.

The forced conflict arises when the independent sets perform their per-call initialization. Since each set needs some type to store its per-call data, the first interceptors in each set does something like this:

```cs
var sp = new ConcreateServiceProvider.Add<SomeType>().Build();
serverCallContext.ServiceProvider = sp;
```

Now, whichever initialization interceptor runs last wins, destroying the work the others have done.

The forced collaboration arises when trying to solve this. Some sort of initialization interceptor gets added that now knows about all the types across all the sets. ASP.NET Core takes this approach by fully embracing `Microsoft.Extensions.DependencyInjection`. I assume that gRPC C# doesn't want to have an opinion about whether or how to use that library.

These problems can be addressed with some changes to the interface, but not without trade-offs.

```cs
interface IUserData // attempt 1
{
    IServiceProvider ServiceProvider { get; }
    void AddService<T>(T instance);
}
```

In attempt 1, the members exposed are mismatched: there's one to retrieve the collection and one to add an item to it. However, to get an item, a chain of calls is needed: `ServiceProvider.GetService<T>()`.

```cs
interface IUserData : IServiceProvider // attempt 2
{
    void AddService(Type forType, object instance);
}
```

Attempt 2 is better. The members are now `GetService(...)` and `AddService(...)`. This does allows use of *some* `IServiceProvider` extension methods, like `GetRequiredService()`, but not ones like `CreateScope()`.

However, this approach doesn't provide anything from `Microsoft.Extensions.DependencyInjection`, like lifetimes or scopes; I suspect it would confound expectations.

```cs
public interface IUserData // original proposal, slightly amended
{
    T Get<T>();
    void Set<T>(T instance);
    // perhaps also
    void Set<TType, TImplementation>(TImplementation instance);
}
```

This interface is just paired getter(s) and setters. It's job is to be a per-call state bag. It doesn't depend on the package or the ideas from `Microsoft.Extensions.DependencyInjection`, but it doesn't get in their way. It can be composed with an existing implementation of `IServiceProvider` with some ceremony, but not too much:

```cs
public StartScopeInterceptor
{
    private readonly IServiceProvider sp;

    public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        context.UserData.Set(sp);
        // or, perhaps, if the ServiceProvider is known to support scopes
        context.UserData.Set(sp.CreateScope().ServiceProvider);
        return continuation(request, context);
    }
}
```

If anyone is aware of an existing interface with similar semantics elsewhere, let me know. Bonus points for an implementation.

**Comment by JamesNK** [comment]
> @JamesNK @JunTaoLuo would this new API be useful for Grpc.AspNetCore.Server?

To be honest I'm still learning gRPC's capabilities and uses of your API. I'm not sure. Ask me in a couple of weeks 😄

**Comment by JamesNK** [comment]
From https://github.com/grpc/grpc/issues/15757#issuecomment-445053226

> I've run into the need to pass state between interceptors and call handlers myself.

I don't think @chwarr's needs will be important for AspNetCore.Server. If I understand interceptors correctly from [here](https://github.com/grpc/proposal/blob/master/L12-csharp-interceptors.md) then they sound similar to ASP.NET Core middleware.

In AspNetCore.Server it should be simple enough to have middleware that puts state in the HttpContext and then for you to [get it from the HttpContext in the gRPC method](https://github.com/grpc/grpc-dotnet/issues/36).

**Comment by chwarr** [comment]
> Is the idea of user data similar to HttpContext.Items?

@JamesNK, yes.

**Comment by JamesNK** [comment]
In that case I'd just go with `IDictionary<object, object> UserData { get; set; }`, with the getter lazily allocating the dictionary the first time `UserData` is accessed if it is null. That keeps the feature pay-for-play.

When it comes to a bag of data, dictionaries are hard to beat 😄

**Comment by JunTaoLuo** [comment]
Right, I believe I mentioned in passing that the interceptors in GRPC world is middleware in ASP.NET Core world, and we have the `HttpContext.Items` API to achieve the objective.

**Comment by dpsenner** [comment]
@chwarr  I think you're unaware of an [essential piece](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollection?view=aspnetcore-2.2). Last but most of all, `IServiceProvider` integrates very well because concrete implementations for IoC and DI build upon that interface. That makes `IServiceProvider` a good candidate

Generally speaking, there's no need to make the `IServiceProvider` interface mutable when the implementation can be made mutable if needed. In most situations it is however desirable that it is not mutable at all. If it has to be mutable, it is fair to construct a new `IServiceProvider` from a `ServiceCollection` by invoking `serviceCollection.GetServiceProvider()` and replacing the current service provider on the `ServerCallContext` by doing `serverCallContext.ServiceProvider = serviceCollection.GetServiceProvider()`. The application architect is given a plentiful of options like nesting `IServiceProvider` and overriding generic implementations and whatnot.

**Comment by dpsenner** [comment]
> When it comes to a bag of data, dictionaries are hard to beat smile

@JamesNK .. not if the interface provides access to types that can be anything that is a type. :smile:

**Comment by JamesNK** [comment]
An `IServiceProvider` is not mutable. Its intended design is to be setup on application startup and then used for the lifetime of the app. The provider created from `ServiceCollection` does IL gen to resolve types as quickly as possible. Creating a new `ServiceCollection` and then getting a service provider from it for every request would have very bad performance. 

Now you could introduce the concept of a request scoped to Grpc.Core, and then people could register some type as scoped per-request with the service provided, and then resolve that type from a `IServiceProvider` during requests, BUT that would require a dependency on `Microsoft.Extensions.DependencyInjection` which I doubt this project would want to do, and it isn't the pit of success for anyone who just wants to set some state during a call. A dictionary is easy for every developer to understand.

**Comment by chwarr** [comment]
I have started [PR #18086](https://github.com/grpc/grpc/pull/18086) that implements the `IDictionary<object, object>` option that was discussed here. It looks pretty clean to me. Cleaner than the `.Get<T>()` proposal.
