### ISSUE TITLE
Tool for manually sending requests to gRPC servers

### ISSUE THREAD

**Issue by hjfreyer** [grpc/grpc#1776]
gRPC needs browser and/or CLI based tools for manually sending requests to servers, for testing and fiddling-about purposes.

**Comment by yang-g** [comment]
As I just replied in grpc-common: please look at grpc_cli at https://github.com/grpc/grpc/blob/master/test/cpp/util/grpc_cli.cc
It is very simple but can do the simple rpcs.

**Comment by yang-g** [comment]
Any feature request or contribution will be welcomed. I am closing this now.
