### ISSUE TITLE
grpc-node linux tests are consistently failing on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17779]
https://source.cloud.google.com/results/invocations/e2b2536c-60f2-4757-9170-bb7aff916805/targets

First failure on Jan 18, 100% runs failing since then https://source.cloud.google.com/results/invocations/db5863a8-a057-4dd4-820f-7a7a116b192b/targets

**Comment by murgatroid99** [comment]
Currently this looks like a bug in one version of Node itself that we are testing on. We are looking into a fix.

**Comment by jtattermusch** [comment]
Tests seems green starting from this build:
https://source.cloud.google.com/results/invocations/06adafc9-c026-4dd4-8c03-50434e786e11/targets
