### ISSUE TITLE
BoringSSL UBSan suppressions no longer necessary?

### ISSUE THREAD

**Issue by davidben** [grpc/grpc#17791]
https://github.com/grpc/grpc/blob/10fa27866035afec60d4d28323a2dc2dcf70785c/test/core/util/ubsan_suppressions.txt has a bunch of BoringSSL suppressions.

Have you all checked if they're still necessary? There isn't even a function named `ssl_copy_key_material`. We cleared a lot of the alignment silliness a long while ago, along with [working around](https://boringssl-review.googlesource.com/12928) a C [language flaw](https://www.imperialviolet.org/2016/06/26/nonnull.html) around `memcpy`, etc.

**Comment by a11r** [comment]
@hcaseyal Can you please do a quick check to see if UBSan suppression is still needed ?

**Comment by hcaseyal** [comment]
@a11r We are looking at the test results in #17930. Will update back when tests are finished running.

**Comment by hcaseyal** [comment]
@a11r It appears from #17930 that these suppressions are no longer necessary. @davidben , thanks for pointing this out.

**Comment by nicolasnoble** [comment]
Suppressions for BoringSSL have been removed.

**Comment by davidben** [comment]
Glad to hear it!

Relatedly, these suppressions are probably bugs in your leak checker environment somewhere, so you should at least change the comment. They're freed by thread-local destructors. I've seen reports of leak checkers mess this up before, but never managed to reproduce it.
https://github.com/grpc/grpc/blob/master/test/core/util/lsan_suppressions.txt
(We've run BoringSSL against LSan for years and would definitely had noticed if something as core as the PRNG and error queue leaked.)
