### ISSUE TITLE
Ruby client hangs on Windows

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#17799]
### What version of gRPC and what language are you using?

* grpc-1.18.0-x64-ming32 gem (Tested 1.18.0 through to 1.8.0, the behavior is likely consistent on earlier versions.)
 
### What operating system (Linux, Windows, …) and version?
 
* Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

* ruby 2.5, 2.4, 2.3 (all 64bit)
 
### What did you do? What did you expect to see? What did you see instead?

GitHub issue googleapis/google-cloud-ruby#2826 reports that a ruby process hangs after successfully calling the Vision API using the Ruby gRPC client. We have investigated this and have successfully reproduced a hung ruby processes by only creating a `GRPC::Core::CallCredentials` object. It hangs even though a service stub object is never created, much less used to make an API call.

I have reduced the steps to demonstrate the hung process and [posted the needed files to this gist](https://gist.github.com/blowmage/23b4daca452cef1ec35b292eb0f7b8f2). You should be able to reproduce by cloning the gist locally, adding the path to a service credentials JSON file, and running `bundle update` and `bundle exec rake`.

You can uncomment the `GRPC_VERBOSITY` and `GRPC_TRACE` lines in `repro.rb` to get more information. I have occasionally seen the script exit cleanly with those lines uncommented, but I have never seen the script exit cleanly when all of the other code in the file is also uncommented.

We have also seen numerous [Kokoro CI jobs fail on Windows](https://source.cloud.google.com/results/invocations/61fbf6e4-90e2-4cc7-a45b-aa2c79210aea/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-ruby%2Fcontinuous-windows/log) due to the build timing out. We have never has a successful build on Windows due to these timeouts AFAIK.
 
### Anything else we should know about your project / environment?

I have reproduced this on a clean Windows 10 PC. I installed Ruby by downloading it from here: https://rubyinstaller.org/downloads/ No other compilers or environment variables have been added to this PC. It does not have the gRPC project, any compilers installed, or any custom environment variables set. Only the pre-compiled Ruby gems were used.

**Comment by blowmage** [comment]
@apolcyn Can you take a look at this?

**Comment by NathanBockrath** [comment]
Hi all, 

I'm new here, and my estimator is broken; any idea on the time frame for this issue to be addressed?
I see that apoclyn has 874 issues on the plate and I don't know if that means 1 year, 5 years or never.
I've my own management overlords asking for estimates, and "I don't know" is getting me the unfunny looks.

**Comment by blowmage** [comment]
@JustinBeckwith @dazuma Can you guys help this issue get some internal attention?

**Comment by apolcyn** [comment]
Sorry, looking to address this for the next 1.19 release

**Comment by NathanBockrath** [comment]
OK, Thank you.  What is the time-frame for that release?

**Comment by apolcyn** [comment]
I'd have to guess about 3 weeks out

**Comment by NathanBockrath** [comment]
OK.

Thanks again!

**Comment by apolcyn** [comment]
This should be fixed by https://github.com/grpc/grpc/pull/17997

I have a package built off of that fix that works on ruby 2.5  in https://github.com/apolcyn/grpc/tree/39e4081628f5dad999996e11df686ee3cea1d9cc/pkg, if interested.

Otherwise, once that PR is merged we'll have nightly packages available; I'll work to get it backported to 1.18

**Comment by NathanBockrath** [comment]
I have run with the provided gem; it is no longer hanging the prompt. 

It does generate an unexpected output printout near the start:

D0211 10:59:55.448000000 15932 ../../../../src/ruby/ext/grpc/rb_grpc.c:323] GRPC_RUBY: grpc_ruby_init - prev g_grpc_ruby_init_count:0

I don't know what other kinds of testing you may need to do for coverage. but it seems like it is fine from my standpoint.   

Thank you!

**Comment by apolcyn** [comment]
Thanks for confirming that it worked for you (the spurious log message was fixed in the submitted PR)

**Comment by apolcyn** [comment]
FYI the `1.19.0.pre1` release was just uploaded, which has the fix for Windows.

**Comment by apolcyn** [comment]
`1.19.0` was just released with the fix

**Comment by NathanBockrath** [comment]
**Thank you!**

**Comment by NathanBockrath** [comment]
Thank you
