### ISSUE TITLE
Flake in VM preparation: Could not get lock /var/lib/dpkg/lock-frontend

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17794]
```
++ sudo apt-get install -y jq
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
https://source.cloud.google.com/results/invocations/acda7a2c-1c53-48c8-9a4c-0295c0ab5fea/log

**Comment by jtattermusch** [comment]
Seen again, maybe not so rare afterall.

**Comment by yashykt** [comment]
I'm seeing this quite often too. Is this just increased load in testing?

**Comment by yashykt** [comment]
could we maybe add a retry loop over there after a sleep?

**Comment by billfeng327** [comment]
PR [17815](https://github.com/grpc/grpc/pull/17815) submitted

**Comment by jtattermusch** [comment]
Should be fixed by #17836.

**Comment by apolcyn** [comment]
Have to reopen, just noticed several instances of this today in https://github.com/grpc/grpc/pull/17894
https://source.cloud.google.com/results/invocations/8739c921-7932-495e-b3cb-c9f398364358/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_c_ubsan/log

https://source.cloud.google.com/results/invocations/f2edac9a-4d3a-4b45-a797-ac4df84fa962/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_basictests_c_dbg/log

https://source.cloud.google.com/results/invocations/5889d933-16b6-4435-b552-04ff20a4a520/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_basictests_c_opt/log

https://source.cloud.google.com/results/invocations/7cb66f9f-9a9c-4fae-a3c6-795dffc93002/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_cpp_asan/log

https://source.cloud.google.com/results/invocations/d7b3f199-25ec-47e7-ba92-9211a07d2a33/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_c_asan/log

**Comment by jtattermusch** [comment]
Likely fixed by switching to "grpc-performance-kokoro-v4"  image that has auto-updates disabled. See https://github.com/grpc/grpc/pull/17928

**Comment by apolcyn** [comment]
noticed one like occurrence:

https://source.cloud.google.com/results/invocations/fecc3315-793a-4b15-8c93-87e87d06c9b1/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_microbenchmark_diff/log

in PR: https://github.com/grpc/grpc/pull/18384

```
Test Fusion Url (This url will not work until build finishes): https://fusion.corp.google.com/runanalysis/info/prod%3Agrpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_microbenchmark_diff/prod%3Agrpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_microbenchmark_diff/KOKORO/fecc3315-793a-4b15-8c93-87e87d06c9b1/1552681398697/prod%3Agrpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_microbenchmark_diff%20Build%20%237217/Targets
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[13:24:36] Transferring environment variable script to build VM
[13:24:37] Transferring kokoro_log_reader.py to build VM
[13:24:38] Transferring source code to build VM
[13:24:39] Executing build script on build VM
[ID: 8244894] Executing command via SSH:
export KOKORO_BUILD_NUMBER="7217"
export KOKORO_JOB_NAME="grpc/core/pull_request/linux/grpc_microbenchmark_diff"
source /tmpfs/kokoro-env_vars.sh; cd /tmpfs/src/ ;  chmod 755 github/grpc/tools/internal_ci/linux/grpc_microbenchmark_diff.sh ;  nohup bash -c "( rm -f /tmpfs/kokoro_build_exit_code ; github/grpc/tools/internal_ci/linux/grpc_microbenchmark_diff.sh   ) > /tmpfs/kokoro_build.log 2>&1 ; echo \$? > /tmpfs/kokoro_build_exit_code" > /dev/null 2>&1 & echo $! > /tmpfs/kokoro_build.pid ; python /tmpfs/kokoro_log_reader.py /tmpfs/kokoro_build.log /tmpfs/kokoro_build_exit_code /tmpfs/kokoro_build.pid /tmpfs/kokoro_log_reader.pid --start_byte 0
+ BENCHMARKS_TO_RUN='bm_fullstack_unary_ping_pong bm_fullstack_streaming_ping_pong bm_fullstack_streaming_pump bm_closure bm_cq bm_call_create bm_error bm_chttp2_hpack bm_chttp2_transport bm_pollset bm_metadata'
++ dirname github/grpc/tools/internal_ci/linux/grpc_microbenchmark_diff.sh
+ cd github/grpc/tools/internal_ci/linux/../../..
+ source tools/internal_ci/helper_scripts/prepare_build_linux_perf_rc
++ ulimit -n 32768
++ ulimit -c unlimited
++ '[' -n 18384 ']'
++ sudo apt-get install -y jq
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
[ID: 8244894] Build finished after 2 secs, exit value: 100
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[13:24:41] Collecting build artifacts from build VM
Build script failed with exit code: 100
```

**Comment by jtattermusch** [comment]
I thought we disabled autoupdates in our linux image here:
https://github.com/grpc/grpc/blob/8c3d4a7dfdeb2282acd90bfb17ca14ce707636f9/tools/gce/linux_kokoro_performance_worker_init.sh#L218

**Comment by vjpai** [comment]
I had multiple occurrences of this on #18493 after the temporary disabling and re-enabling of kokoro

**Comment by muxi** [comment]
Still seeing this in a run about 10 min ago.

https://source.cloud.google.com/results/invocations/6b4a4a7c-f2de-4ba7-8b40-46aa56a3ff54/targets

**Comment by markdroth** [comment]
I'm seeing this a lot lately.  It's happened to me several different times in #18628 alone, and I've seen similar behavior in other PRs.

**Comment by jtattermusch** [comment]
For context:
this seems to be a problem with background auto-updates running in our custom linux kokoro image (a background apt update conflicts with apt-get command we run in our test scrips).  Disabling the autoupdates should solve this. We tried to do that in https://github.com/grpc/grpc/pull/17928 but it seems that wasn't the right way to disable the auto-updates as we still keep seeing this issue.

Note that disabling auto-updates does only requires general ubuntu knowledge (no kokoro internals knowledge is required), so this item is up for grabs - someone just needs to spend sufficient time on this.

**Comment by jtattermusch** [comment]
Found an additional place where we might need to disable the autoupdates:

```
/etc/apt/apt.conf.d$ cat 20auto-upgrades 
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1"; 
```

https://linuxconfig.org/disable-automatic-updates-on-ubuntu-18-04-bionic-beaver-linux

**Comment by jtattermusch** [comment]
I think I have a fix coming: https://github.com/grpc/grpc/pull/18695

**Comment by jtattermusch** [comment]
We switched to v5 image internally, so hopefully this is fixed.
