### ISSUE TITLE
Clarify health check state

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#17805]
In the current [health check](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), it says that servers should declare an overall health using the empty string ```''``` service.  However, it isn't specified what the default state should be, either serving or not serving.  This came up as a question in https://github.com/grpc/grpc-java/pull/5274   where the Java implementation was modified to set the default.

Without signal from the application it feels wrong to assume healthiness (dependent connections may not be ready, or other code caches hot).  However, p2p health checking servers may not be aware they need to intentionally set healthiness.  Also, the other gRPC implementations seem to set all services to serving, so Java is copying that precedent.

**Comment by markdroth** [comment]
I think the right behavior is that the empty string should be set to SERVING by default, but no other services should be automatically set to SERVING until the application explicitly does so.  I think this reflects the expected use cases:

- There are environments (like what we do internally) where health checking is enabled by default using "" as the service name.  In those environments, applications that don't want to explicitly manage their own health status can do nothing, and the right thing will happen.

- For any service that wants to explictly manage its health status, it can use a different service name in both the service config and the server application code, and the service should not be considered healthy until the application's custom code has explicitly verified that it is healthy.
