### ISSUE TITLE
PHP: Installation compile error (using PECL, CentOS 7.6.1810)

### ISSUE THREAD

**Issue by Oihso** [grpc/grpc#17812]
### What version of gRPC and what language are you using?
 

- PHP gRPC 1.18.0

 
### What operating system (Linux, Windows, …) and version?
 

- CentOS Linux release 7.6.1810 (Core) 

 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 

- gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

 
### What did you do?

1. I tried to install gRPC 1.18.0, got a compilation error
2. Updated gcc to 4.8.5 and again tried to install gRPC 1.18.0, got the same compilation error
3. Updated system components, tried to install gRPC 1.18.0, got all the same compilation error
P.S. I also tried to compile gRPC 1.18.0 on my own, but got a compilation error 

 
### What did you expect to see?
 
- Successfully installed gRPC

### What did you see instead?
 
`[root@localhost /]# opt/remi/php72/root/bin/pecl install grpc`
downloading grpc-1.18.0.tgz ... 
Starting to download grpc-1.18.0.tgz (2,654,507 bytes) 
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done: 2,654,507 bytes 
1207 source files, building 
running: phpize 
Configuring for: 
PHP Api Version: 20170718 
Zend Module Api No: 20170718 
Zend Extension Api No: 320170718 
building in /var/tmp/pear-build-rootlFzt48/grpc-1.18.0 
running: /var/tmp/grpc/configure --with-php-config=/opt/remi/php72/root/usr/bin/php-config 
checking for grep that handles long lines and -e... /usr/bin/grep 
checking for egrep... /usr/bin/grep -E 
checking for a sed that does not truncate output... /usr/bin/sed 
checking for cc... cc 
checking whether the C compiler works... yes 
checking for C compiler default output file name... a.out 
checking for suffix of executables... 
checking whether we are cross compiling... no 
checking for suffix of object files... o 
checking whether we are using the GNU C compiler... yes 
checking whether cc accepts -g... yes 
checking for cc option to accept ISO C89... none needed 
checking how to run the C preprocessor... cc -E 
checking for icc... no 
checking for suncc... no 
checking whether cc understands -c and -o together... yes 
checking for system library directory... lib 
checking if compiler supports -R... no 
checking if compiler supports -Wl,-rpath,... yes 
checking build system type... x86_64-unknown-linux-gnu 
checking host system type... x86_64-unknown-linux-gnu 
checking target system type... x86_64-unknown-linux-gnu 
checking for PHP prefix... /opt/remi/php72/root/usr 
checking for PHP includes... -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib 
checking for PHP extension directory... /opt/remi/php72/root/usr/lib64/php/modules 
checking for PHP installed headers prefix... /opt/remi/php72/root/usr/include/php 
checking if debug is enabled... no 
checking if zts is enabled... no 
checking for re2c... no configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers. 
checking for gawk... gawk 
checking whether to enable grpc support... yes, shared 
checking for g++... g++ 
checking whether we are using the GNU C++ compiler... yes 
checking whether g++ accepts -g... yes 
checking how to run the C++ preprocessor... g++ -E 
checking how to print strings... printf 
checking for a sed that does not truncate output... (cached) /usr/bin/sed 
checking for fgrep... /usr/bin/grep -F 
checking for ld used by cc... /usr/bin/ld 
checking if the linker (/usr/bin/ld) is GNU ld... yes 
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B 
checking the name lister (/usr/bin/nm -B) interface... BSD nm 
checking whether ln -s works... yes 
checking the maximum length of command line arguments... 1572864 
checking whether the shell understands some XSI constructs... yes 
checking whether the shell understands '+='... yes 
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop 
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop 
checking for /usr/bin/ld option to reload object files... -r 
checking for objdump... objdump 
checking how to recognize dependent libraries... pass_all 
checking for dlltool... no 
checking how to associate runtime and link libraries... printf %s 
checking for ar... ar 
checking for archiver @FILE support... @ 
checking for strip... strip 
checking for ranlib... ranlib 
checking for gawk... (cached) gawk 
checking command to parse /usr/bin/nm -B output from cc object... ok 
checking for sysroot... no 
checking for mt... no 
checking if : is a manifest tool... no 
checking for ANSI C header files... yes 
checking for sys/types.h... yes 
checking for sys/stat.h... yes 
checking for stdlib.h... yes 
checking for string.h... yes 
checking for memory.h... yes 
checking for strings.h... yes 
checking for inttypes.h... yes 
checking for stdint.h... yes 
checking for unistd.h... yes 
checking for dlfcn.h... yes 
checking for objdir... .libs 
checking if cc supports -fno-rtti -fno-exceptions... no 
checking for cc option to produce PIC... -fPIC -DPIC 
checking if cc PIC flag -fPIC -DPIC works... yes 
checking if cc static flag -static works... no 
checking if cc supports -c -o file.o... yes 
checking if cc supports -c -o file.o... (cached) yes 
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes 
checking whether -lc should be explicitly linked in... no 
checking dynamic linker characteristics... GNU/Linux ld.so 
checking how to hardcode library paths into programs... immediate 
checking whether stripping libraries is possible... yes 
checking if libtool supports shared libraries... yes 
checking whether to build shared libraries... yes 
checking whether to build static libraries... no 
checking how to run the C++ preprocessor... g++ -E 
checking for ld used by g++... /usr/bin/ld -m elf_x86_64 
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes 
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes 
checking for g++ option to produce PIC... -fPIC -DPIC 
checking if g++ PIC flag -fPIC -DPIC works... yes 
checking if g++ static flag -static works... no 
checking if g++ supports -c -o file.o... yes 
checking if g++ supports -c -o file.o... (cached) yes 
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes 
checking dynamic linker characteristics... (cached) GNU/Linux ld.so 
checking how to hardcode library paths into programs... immediate 
configure: creating ./config.status 
config.status: creating config.h 
config.status: executing libtool commands 
running: make 
/bin/sh /var/tmp/pear-build-rootlFzt48/grpc-1.18.0/libtool --mode=compile cc -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -I. -I/var/tmp/grpc -DPHP_ATOM_INC -I/var/tmp/pear-build-rootlFzt48/grpc-1.18.0/include -I/var/tmp/pear-build-rootlFzt48/grpc-1.18.0/main -I/var/tmp/grpc -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib -I/var/tmp/grpc/include -I/var/tmp/grpc/src/php/ext/grpc -I/var/tmp/grpc/third_party/boringssl/include -I/var/tmp/grpc/third_party/address_sorting/include -I/var/tmp/grpc/third_party/nanopb -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -g -O2 -D PB_FIELD_32BIT=1 -c /var/tmp/grpc/src/php/ext/grpc/byte_buffer.c -o src/php/ext/grpc/byte_buffer.lo 
libtool: compile: cc -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -I. -I/var/tmp/grpc -DPHP_ATOM_INC -I/var/tmp/pear-build-rootlFzt48/grpc-1.18.0/include -I/var/tmp/pear-build-rootlFzt48/grpc-1.18.0/main -I/var/tmp/grpc -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib -I/var/tmp/grpc/include -I/var/tmp/grpc/src/php/ext/grpc -I/var/tmp/grpc/third_party/boringssl/include -I/var/tmp/grpc/third_party/address_sorting/include -I/var/tmp/grpc/third_party/nanopb -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -g -O2 -D PB_FIELD_32BIT=1 -c /var/tmp/grpc/src/php/ext/grpc/byte_buffer.c -fPIC -DPIC -o src/php/ext/grpc/.libs/byte_buffer.o 
In file included from /opt/remi/php72/root/usr/include/php/Zend/zend.h:328:0, 
				 from /opt/remi/php72/root/usr/include/php/main/php.h:35, 
				 from /var/tmp/grpc/src/php/ext/grpc/byte_buffer.c:19: 
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h: In function 'fast_long_increment_function': 
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h:446:2: error: implicit declaration of function '__builtin_saddl_overflow' [-Werror=implicit-function-declaration] 
	if (UNEXPECTED(__builtin_saddl_overflow(Z_LVAL_P(op1), 1, &lresult))) { 
	^ 
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h: In function 'fast_long_decrement_function': 
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h:500:2: error: implicit declaration of function '__builtin_ssubl_overflow' [-Werror=implicit-function-declaration] 
	if (UNEXPECTED(__builtin_ssubl_overflow(Z_LVAL_P(op1), 1, &lresult))) { 
	^ 
/var/tmp/grpc/src/php/ext/grpc/byte_buffer.c: At top level: 
cc1: error: unrecognized command line option '-Wno-parentheses-equality' [-Werror] 
cc1: all warnings being treated as errors 
make: *** [src/php/ext/grpc/byte_buffer.lo] Error 1 ERROR: `make' failed 

`[root@localhost /]# cat /etc/centos-release`
CentOS Linux release 7.6.1810 (Core) 

`[root@localhost /]# gcc --version`
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc. 

 
### Anything else we should know about your project / environment?

- Nope

**Comment by ZhouyihaiDing** [comment]
`cc1: error: unrecognized command line option '-Wno-parentheses-equality' [-Werror]`
The issue is similar to https://github.com/grpc/grpc/issues/10233

Does the `pecl install` works for gRPC before 1.18.0(like 1.2.0) with your current gcc version? Thanks for the help.

**Comment by Oihso** [comment]
> `cc1: error: unrecognized command line option '-Wno-parentheses-equality' [-Werror]`
> The issue is similar to #10233
> 
> Does the `pecl install` works for gRPC before 1.18.0(like 1.2.0) with your current gcc version? Thanks for the help.

No, this command did not work with earlier versions either.

**Comment by stanley-cheung** [comment]
@toc007 is looking into reproducing this.

**Comment by toc007** [comment]
Dockerfile to reproduce issue

```Dockerfile
FROM centos:centos7.6.1810

RUN yum update -y

RUN yum install -y gcc make

# prep and install php and pecl
RUN yum-config-manager --enable remi-php72
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y yum-utils
RUN yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum install -y php72 php72-php-fpm php72-php-mysqlnd php72-php-opcache php72-php-xml php72-php-xmlrpc php72-php-gd php72-php-mbstring php72-php-json php72-php-pear php72-php-devel

# add php and pecl to path
ENV PATH=$PATH:/opt/remi/php72/root/bin/
```

**Comment by toc007** [comment]
Attempt to build from source yields similar error while building grpc php plugin:
```
[root@073a72369c6b grpc]# make
/bin/sh /grpc/src/php/ext/grpc/libtool --mode=compile cc -Wall -Werror -std=c11 -I. -I/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/grpc/src/php/ext/grpc/include -I/grpc/src/php/ext/grpc/main -I/grpc/src/php/ext/grpc -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /grpc/src/php/ext/grpc/byte_buffer.c -o byte_buffer.lo
libtool: compile:  cc -Wall -Werror -std=c11 -I. -I/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/grpc/src/php/ext/grpc/include -I/grpc/src/php/ext/grpc/main -I/grpc/src/php/ext/grpc -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /grpc/src/php/ext/grpc/byte_buffer.c  -fPIC -DPIC -o .libs/byte_buffer.o
In file included 
   from /opt/remi/php72/root/usr/include/php/Zend/zend.h:328:0,
   from /opt/remi/php72/root/usr/include/php/main/php.h:35,
   from /grpc/src/php/ext/grpc/byte_buffer.c:19:
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h: In function 'fast_long_increment_function':
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h:446:2: error: implicit declaration of function '__builtin_saddl_overflow' [-Werror=implicit-function-declaration]
   if (UNEXPECTED(__builtin_saddl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
   ^
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h: In function 'fast_long_decrement_function':
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h:500:2: error: implicit declaration of function '__builtin_ssubl_overflow' [-Werror=implicit-function-declaration]
    if (UNEXPECTED(__builtin_ssubl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
    ^
cc1: all warnings being treated as errors
make: *** [byte_buffer.lo] Error 1
```

**Comment by toc007** [comment]
The following Dockerfile yields a successful install.
```Dockerfile
FROM centos:centos7.6.1810

RUN yum update -y

RUN yum install -y make git which

# fix from issue 16686
RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-7-gcc*
RUN echo "scl enable devtoolset-7 bash" >> /root/.bashrc

# prep and install php and pecl
RUN yum-config-manager --enable remi-php72
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y yum-utils
RUN yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum install -y php72 php72-php-fpm php72-php-mysqlnd php72-php-opcache php72-php-xml php72-php-xmlrpc php72-php-gd php72-php-mbstring php72-php-json php72-php-pear php72-php-devel zlib-devel

# add php and pecl to path
ENV PATH=$PATH:/opt/remi/php72/root/bin/
```
I believe that this problem is closely related to issue #16686, which is a gcc versioning issue.
Please try the following steps to install the latest version of gcc
```bash
sudo yum install -y centos-release-scl
sudo yum install -y devtoolset-7-gcc*
scl enable devtoolset-7 bash
```
