### ISSUE TITLE
Ruby flake: GRPC::RpcServer#run with no connect_metadata should handle multiple parallel requests

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1782]
```
Failures:
  1) GRPC::RpcServer#run with no connect_metadata should handle multiple parallel requests
     Failure/Error: n.times { expect(q.pop).to be_a(EchoMsg) }
     fatal:
       No live threads left. Deadlock?
     # ./spec/generic/rpc_server_spec.rb:472:in `pop'
     # ./spec/generic/rpc_server_spec.rb:472:in `block (5 levels) in <top (required)>'
     # ./spec/generic/rpc_server_spec.rb:472:in `times'
     # ./spec/generic/rpc_server_spec.rb:472:in `block (4 levels) in <top (required)>'
Finished in 12.76 seconds (files took 0.60367 seconds to load)
15 examples, 1 failure
Failed examples:
rspec ./spec/generic/rpc_server_spec.rb:459 # GRPC::RpcServer#run with no connect_metadata should handle multiple parallel requests
```

**Comment by ctiller** [comment]
Seems related (on another run):

  1) GRPC::RpcServer#run with no connect_metadata should not receive metadata if the client times out
     Failure/Error: t = Thread.new { @srv.run }
     GRPC::Core::CallError:
       start_batch completion failed
     # ./lib/grpc/generic/rpc_server.rb:443:in `run_batch'
     # ./lib/grpc/generic/rpc_server.rb:443:in `new_active_server_call'
     # ./lib/grpc/generic/rpc_server.rb:423:in `loop_handle_server_calls'
     # ./lib/grpc/generic/rpc_server.rb:383:in `run'
     # ./spec/generic/rpc_server_spec.rb:410:in `block (5 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.1.5/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
     # /home/travis/.rvm/gems/ruby-2.1.5/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
  2) GRPC::RpcServer#run with no connect_metadata should handle cancellation correctly
     Failure/Error: t = Thread.new { @srv.run }
     GRPC::Core::CallError:
       start_batch completion failed
     # ./lib/grpc/generic/rpc_server.rb:443:in `run_batch'
     # ./lib/grpc/generic/rpc_server.rb:443:in `new_active_server_call'
     # ./lib/grpc/generic/rpc_server.rb:423:in `loop_handle_server_calls'
     # ./lib/grpc/generic/rpc_server.rb:383:in `run'
     # ./spec/generic/rpc_server_spec.rb:426:in `block (5 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.1.5/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
     # /home/travis/.rvm/gems/ruby-2.1.5/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'

**Comment by tbetbetbe** [comment]
The test in the bug report has been deleted in #3494
