### ISSUE TITLE
handshake_client_ssl test failing

### ISSUE THREAD

**Issue by arjunroy** [grpc/grpc#17845]
### What version of gRPC and what language are you using?
 CORE_VERSION=7.0.0-dev
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
 
### What did you do?
1) git clone git@github.com:grpc/grpc.git
2) git submodule update --init 
3) python tools/run_tests/run_tests.py -l c -r handshake_client_ssl 

### What did you expect to see?
"All tests passed successfully".
 
 
### What did you see instead?
 
FAILED: bins/opt/handshake_client_ssl GRPC_POLL_STRATEGY=poll-cv [ret=-6, pid=51786, time=3.0sec] 
FAILED: bins/opt/handshake_client_ssl GRPC_POLL_STRATEGY=epoll1
FAILED: bins/opt/handshake_client_ssl GRPC_POLL_STRATEGY=epollex
FAILED: bins/opt/handshake_client_ssl GRPC_POLL_STRATEGY=poll
FAILED: bins/opt/handshake_client_ssl GRPC_POLL_STRATEGY=poll-cv
FAILED: Some tests failed 

The following assertion fails in each case:
E0128 15:45:58.581634170   51786 client_ssl.cc:321]          assertion failed: !client_ssl_test(const_cast<char*>("foo"))
 
See also: grpc/test/core/handshake/client_ssl.cc line 321.

### Anything else we should know about your project / environment?

Clean checkout, no changes.

**Comment by wangkirin** [comment]
we have met the same problem in v1.12.0, Could anyone give some advice?
