### ISSUE TITLE
Stream removed error with C# client and Kestrel server

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#17840]
I am getting an error - "Status(StatusCode=Unknown, Detail="Stream removed")" - from the C# client when calling a gRPC service hosted in Kestrel. The error happens after thousands of gRPC requests but it is consistent.

Attached are Wireshark logs. You can see that the error happens after the server sends a "WINDOW_UPDATE" message to the client and then the client resets the stream. This is consistent between runs.

[grpc-stream-reset.zip](https://github.com/grpc/grpc/files/2804845/grpc-stream-reset.zip)

![image](https://user-images.githubusercontent.com/303201/51864317-517af000-23a8-11e9-9e2c-ad47ca2eae7c.png)

Why does the client throw a "Stream removed" after receiving a "WINDOW_UPDATE"?

Potentially related - https://github.com/grpc/grpc/issues/15623

// @jtattermusch @JunTaoLuo

**Comment by JamesNK** [comment]
Discussion with Kestrel devs - https://github.com/aspnet/AspNetCore/issues/6974

We think it is an issue with the client.

**Comment by JamesNK** [comment]
gRPC logging: [log.zip](https://github.com/grpc/grpc/files/2809445/log.zip)

Vebosity: DEBUG
Trace: ALL

Search for "Stream removed" for the area where the problem occurred.

**Comment by JamesNK** [comment]
```
D0130 08:48:49.880843 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc:720: {"created":"@1548791329.880000000","description":"Error received from peer","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1036,"grpc_message":"Stream removed","grpc_status":2}
```

**Comment by JamesNK** [comment]
Opps, I got the related link wrong. It is to this long standing issue - https://github.com/grpc/grpc/issues/15623

**Comment by jtattermusch** [comment]
@JamesNK  I tried running BenchmarkClient and BenchmarkServer  to reproduce, but after following instructions from https://github.com/aspnet/AspNetCore/issues/6974#issue-402508405, I got a build error:
```
$ GrpcEndpointRouteBuilderExtensions.cs(28,23): error CS0246: The type or namespace name 'IEndpointConventionBuilder' could not be foun d (are you missing a using directive or an assembly reference?) [C:\Users\jtattermusch\github\grpc-dotnet\src\Grpc.AspNetCore.Server\ Grpc.AspNetCore.Server.csproj]
```
I assume this might be because the PR with benchmarks might be slightly out of date. Is it possible to get it to a buildable state?

**Comment by jtattermusch** [comment]
> @JamesNK I tried running BenchmarkClient and BenchmarkServer to reproduce, but after following instructions from [aspnet/AspNetCore#6974 (comment)](https://github.com/aspnet/AspNetCore/issues/6974#issue-402508405), I got a build error:
> 
> ```
> $ GrpcEndpointRouteBuilderExtensions.cs(28,23): error CS0246: The type or namespace name 'IEndpointConventionBuilder' could not be foun d (are you missing a using directive or an assembly reference?) [C:\Users\jtattermusch\github\grpc-dotnet\src\Grpc.AspNetCore.Server\ Grpc.AspNetCore.Server.csproj]
> ```
> I assume this might be because the PR with benchmarks might be slightly out of date. Is it possible to get it to a buildable state?

@JamesNK  sorry for the confusion, I realized I can use https://github.com/grpc/grpc-dotnet/pull/67 and I'm able to build and reproduce with that code.

**Comment by jtattermusch** [comment]
So far I was able to confirm that this happens on both linux and windows.

**Comment by jtattermusch** [comment]
See analysis of what's going on (and fix) in https://github.com/grpc/grpc/pull/17950.

**Comment by jtattermusch** [comment]
A bit more explanation about what happens in this scenario:
- gRPC fails to parse the WINDOW_UPDATE
- it sends a RST_STREAM for all outstanding calls on that connection
- that ends up in "Stream removed".

Btw, it doesn't seem that this "Stream removed" problem would be related to https://github.com/grpc/grpc/issues/15623 as suggested above.
