### ISSUE TITLE
remove grpc_channel_ping() from C-core API

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#17857]
This function is not used outside of tests, so there's no reason it needs to be in the C-core API.

**Comment by markdroth** [comment]
This is still something we should do eventually.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work

**Comment by markdroth** [comment]
This is actually an internal cleanup.
