### ISSUE TITLE
Bazel Basic Tests for Python (Local) failure //src/python/grpcio_tests/tests/qps:basic_benchmark_test

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#17850]
Seen on #17806.. The result store shows that it has been failing since #17644 got introduced.

Log https://source.cloud.google.com/results/invocations/1d758624-905d-41ed-bb09-8b2a6df16938/targets

**Comment by jtattermusch** [comment]
Confirmed that this is failing on master in 100% runs.
https://source.cloud.google.com/results/invocations/cf079d0a-3c67-4f95-b279-942590c1d428/log

**Comment by yashykt** [comment]
Thanks for quickly taking care of it
