### ISSUE TITLE
Add grpc_core::Map<> to replace the AVL

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#17864]
As mentioned here https://github.com/grpc/grpc/pull/17513#pullrequestreview-187052786, we should try using "std::map<> in C-core by overriding the allocator, similarly to what we do for grpc_core::UniquePtr<> (i.e., create a new file src/core/lib/gprpp/map.h defining grpc_core::Map<>)".

Currently, we are using an AVL tree as an implementation of a map for the subchannel pool interface.

This is not ideal:

- The code is complex, and hard to debug.
- A lot of channel args creation happens in the AVL tree, as analyzed in memory usage investigation.

**Comment by AspirinSJL** [comment]
cc @ncteisen

**Comment by markdroth** [comment]
It looks like `std::map<>` does incur a link-time dependency on the C++ standard library, so this won't work.  See #18052 for details.
