### ISSUE TITLE
Allow unary call to take byte buffer request

### ISSUE THREAD

**Issue by mhaidrygoog** [grpc/grpc#17870]
Modify codegen to take byte buffers as requests for the async and callback unary request methods

**Comment by vjpai** [comment]
@sreecha points out that this would be useful for responses coming from the server as well. Since the same motivation applies to a server that wants to send the same preserialized data multiple times.

**Comment by vjpai** [comment]
WRT the latter issue, @ncteisen had made progress on it (raw request or raw response without raw to both) but we left it aside since it seemed like an API explosion. But that said, the API is already pretty exploded and it may be worth reviving #15805

**Comment by vjpai** [comment]
Fixed by #18165 
Let's make a separate issue for server-side
