### ISSUE TITLE
Grpc.Tools: Change the casing of msbuild property ProtoBuf to Protobuf

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc#17884]
### What version of gRPC and what language are you using?
 1.18.0 with C#
 
### What operating system (Linux, Windows, …) and version?
 Windows 10 but this change is platform agnostic
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET Core 3.0 preview 1 though this shouldn't matter either
 
### What did you do?
Inspected the MSBuild targets/items/properties in Grpc.Tools
 
### What did you expect to see?
The preferred naming should be `Protobuf` see https://github.com/grpc/grpc-dotnet/pull/48#discussion_r252303008
 
### What did you see instead?
The naming `ProtoBuf` was used: https://github.com/grpc/grpc/blob/4b11d7063096c7133972e2cccab7ece933a8f846/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L25-L31
 
### Anything else we should know about your project / environment?
N/A

cc @jtattermusch

**Comment by kkm000** [comment]
Roger.

**Comment by kkm000** [comment]
@jtattermusch, wondering if GitHub will let you change the Assignee field to me; if it does, could you please do? More efficient than mirroring like https://github.com/kkm000/grpc/issues/3

**Comment by jtattermusch** [comment]
@kkm000  unfortunately github won't let me assign to you as you're not member of the grpc org.

**Comment by kkm000** [comment]
@jtattermusch I see, thanks. No biggie.
