### ISSUE TITLE
[Flaky] grpc_ios_binary_size Timeout

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#17902]
The core error log:
```
xcodebuild \
    build \
    -workspace *.xcworkspace \
    -scheme $SCHEME \
    -destination generic/platform=iOS \
    -derivedDataPath Build/Build \
    CODE_SIGN_IDENTITY="" \
    CODE_SIGNING_REQUIRED=NO \
    | egrep -v "$XCODEBUILD_FILTER" \
    | egrep -v "^$" -
ERROR: Aborting VM command due to timeout of 3600 seconds
```

Full error log can be found here: https://source.cloud.google.com/results/invocations/255b1d27-a2fc-45c8-9508-2aaef7082c7a/log

30 most recent builds failed 29 times, but succeed once so I marked it as flaky: https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size

**Comment by jtattermusch** [comment]
Dup of #17561, hopefully fixed by https://github.com/grpc/grpc/pull/17890.
