### ISSUE TITLE
Load balancing support

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1790]

**Comment by aaronjheng** [comment]
@nicolasnoble sorry, what is the status of this issue?

**Comment by dgquintas** [comment]
This is currently under heavy development. See https://github.com/grpc/grpc/blob/master/doc/load-balancing.md for the protocol.

**Comment by public** [comment]
Is there anywhere we can contribute to or observe the development of the implementation?

**Comment by dgquintas** [comment]
There's been a recent update to  https://github.com/grpc/grpc/blob/master/doc/load-balancing.md

In addition, Q4 2016 saw _a lot_ of bug fixes and improvements to https://github.com/grpc/grpc/blob/master/src/core/ext/lb_policy/grpclb/grpclb.c

The https://github.com/grpc/grpc/blob/master/src/core/ext/lb_policy/grpclb directory is where all the action related to gRPCLB happens.

**Comment by AspirinSJL** [comment]
Closing this because the main LB functionality has been added for nearly one year.
