### ISSUE TITLE
grpc::Alarm doesn't allow reuse without leaking memory

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#17915]
`grpc::Alarm` increments the reference count of the `CompletionQueue` passed on each call to `Set`, but only unrefs it in the destructor at most once. The documentation for the class does not explicitly say that it's not reusable, and looking at the code it seems like the intent was for it to be reusable just fine, as the internal C-core object is recreated every time and the one-time-setting constructor is deprecated in favor of a `Set` method. (Is that not the case? If so please clarify the docs. It seems to work fine when reused appropriately except for this leak which doesn’t seem to hard to fix)

By reuse, I specifically refer to the narrow case of using the alarm in a sane way: only calling `Set` when it's new, fired, or canceled [in other words, calling `Set` when the `Alarm` is never used or only after the associated tag is taken out of CQ].

**Comment by mehrdada** [comment]
cc @vjpai

**Comment by vjpai** [comment]
Great point, it is implicit in our API right now that this should only be set once; I should add a comment or make it resettable.

**Comment by mehrdada** [comment]
Thanks. We got bitten by this and found it with some ASAN investigation. As a matter of feedback, making it resettable would be ideal (at least with the precondition that the previous tag had been drained) and seems feasible looking at the code, as it makes for a better API from a usability perspective (right now I have to wrap it with `std::unique_ptr` and recreate the instance every time.)
