### ISSUE TITLE
cross compile make all does not build protoc plugins

### ISSUE THREAD

**Issue by wuyuanyi135** [grpc/grpc#17910]
### What version of gRPC and what language are you using?
 grpc-cpp v1.18.0
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 18.10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 aarch64-linux-gnu-gcc 7.4
 
### What did you do?
Assume the build machine has protoc and grpc installed in the default location (/usr/local/), and the cross version of protobuf has been built without problem with the command below
```
export CROSS_TRIPLE=aarch64-linux-gnu
cd /var/local/git/grpc && \
    echo "--- installing cross protobuf ---" && \
     cd third_party/protobuf && \
     ./autogen.sh && ./configure --enable-shared --host=${CROSS_TRIPLE}&& \
     make -j$(nproc) && make install DESTDIR=/grpc && ldconfig && \
```
Then, build grpc with
```
    export CROSS_TRIPLE=aarch64-linux-gnu
    make install \
        prefix=/grpc/usr/local \
        -j$(nproc) \
        CC=`which ${CROSS_TRIPLE}-gcc` \
        LD=`which ${CROSS_TRIPLE}-gcc` \
        CXX=`which ${CROSS_TRIPLE}-g++` \
        LDXX=`which ${CROSS_TRIPLE}-g++` \
        AR=`which ${CROSS_TRIPLE}-ar` \
        STRIP=`which ${CROSS_TRIPLE}-strip` \
        PROTOBUF_CONFIG_OPTS="--host=${CROSS_TRIPLE} --with-protoc=`which protoc`" \
        HAS_PKG_CONFIG=false \
        GRPC_CROSS_COMPILE=true \
        GRPC_CROSS_LDOPTS="-L/grpc/usr/local/lib -L/usr/aarch64-linux-gnu/lib -L/usr/lib -L/usr/local/lib" \
        GRPC_CROSS_AROPTS="rcs --target=elf64-littleaarch64"
```
 
### What did you expect to see?
 Build and install without error
 
### What did you see instead?
 `grpc_cpp_plugin` was not built, failing `all` or `install` target.

### Workaround
If I make grpc_cpp_plugin target first then install, it will pass

### Possible reason
Makefile line 427 `USE_BUILT_PROTOC = false` negates line 828 and the protoc plugin is not built.

**Comment by wuyuanyi135** [comment]
The question is whether x-compile is meant to build the compiler plugins for the target platform or just the runtime libraries. Instead, the proto files should be compiled on the host machine. 
In my case, I use my laptop to cross build docker images for my aarch64 and arm32 computers. They have the capabilities to build grpc but very slow. So in this case I actually need the protoc plugins.

**Comment by nicolasnoble** [comment]
This really is on purpose. The plugin are compilation tools, so they are meant to be run on the host machine, in order to produce target code.

There are pieces of the library that requires the plug-ins to be run on the host machine, during the compilation of the target code that is.

**Comment by wuyuanyi135** [comment]
I see. Closing.
