### ISSUE TITLE
*san failure in subchannel: call stack destruction is after channel stack destrcution

### ISSUE THREAD

**Issue by arjunroy** [grpc/grpc#17911]
### What version of gRPC and what language are you using?
 Latest
 
### What operating system (Linux, Windows, …) and version?
PR test flow
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

https://source.cloud.google.com/results/invocations/f86fee4d-11a1-406e-b626-fd74cfab74ae/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_http_proxy_test@keepalive_timeout@poller%3Dpoll-cv/log 

### What did you expect to see?
 
 Test usually passes.

### What did you see instead?
 
Test fails.

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/core/end2end:h2_http_proxy_test@keepalive_timeout@poller=poll-cv
-----------------------------------------------------------------------------
D0202 00:49:55.155219627      20 test_config.cc:391]         test slowdown factor: sanitizer=4, fixture=1, poller=5, total=20
D0202 00:49:55.166912142      20 ev_posix.cc:170]            Using polling engine: poll-cv
D0202 00:49:55.170543781      20 dns_resolver.cc:334]        Using native dns resolver
I0202 00:49:55.171683601      20 keepalive_timeout.cc:43]    keepalive_timeout/chttp2/fullstack
I0202 00:49:55.171774527      20 http_proxy_fixture.cc:536]  Proxy address: localhost:25771
E0202 00:49:55.173510247      20 channel_args.cc:345]        grpc.keepalive_timeout_ms ignored: it must be >= 1
D0202 00:49:55.188258444      20 dns_resolver.cc:275]        Start resolving.
E0202 00:49:55.192125101      21 channel_args.cc:345]        grpc.keepalive_timeout_ms ignored: it must be >= 1
I0202 00:49:55.195038000      20 http_connect_handshaker.cc:299] Connecting to server localhost:25770 via HTTP proxy ipv6:[::1]:25771
D0202 00:49:55.196851337      24 http_proxy_fixture.cc:384]  on_read_request_done: 0x723000000000 "No Error"
I0202 00:49:55.200639215      20 subchannel.cc:1020]         New connected subchannel at 0x704000001280 for subchannel 0x71500001fe00
D0202 00:49:58.701620171      23 dns_resolver.cc:275]        Start resolving.
I0202 00:49:58.701734372      24 http_proxy_fixture.cc:162]  HTTP proxy client read: {"created":"@1549068598.701582533","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":479,"grpc_status":14,"target_address":"ipv6:[::1]:41500"}
I0202 00:49:58.704230772      24 http_proxy_fixture.cc:162]  HTTP proxy server read: {"created":"@1549068598.701824670","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":532,"grpc_status":14,"referenced_errors":[{"created":"@1549068598.701582533","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":479,"grpc_status":14,"target_address":"ipv6:[::1]:41500"}]}
D0202 00:49:58.704305703      24 http_proxy_fixture.cc:130]  endpoints: 0x718000010000 0x718000010400
==20==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xfc3ff1 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*) /proc/self/cwd/src/core/lib/transport/transport.cc:198:14
    #1 0x11aba13 in destroy_call_elem(grpc_call_element*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/connected_channel.cc:174:3
    #2 0x10bf846 in grpc_call_stack_destroy(grpc_call_stack*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/channel_stack.cc:217:5
    #3 0xb94cd8 in grpc_core::(anonymous namespace)::SubchannelCallDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:128:3
    #4 0x1273658 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #5 0x1272ac0 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #6 0x51b07c in grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:108:5
    #7 0x10cf16a in grpc_call_unref /proc/self/cwd/src/core/lib/surface/call.cc:596:1
    #8 0x68ce08 in test_keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:211:3
    #9 0x68960d in keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:224:3
    #10 0x4f7c49 in grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:472:7
    #11 0x4eb8fd in main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:128:5
    #12 0x7f0cffd0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x472b68 in _start (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/end2end/h2_http_proxy_test@keepalive_timeout@poller=poll-cv.runfiles/com_github_grpc_grpc/test/core/end2end/h2_http_proxy_test+0x472b68)
  Uninitialized value was stored to memory at
    #0 0xfc3eb4 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*) /proc/self/cwd/src/core/lib/transport/transport.cc:197
    #1 0x11aba13 in destroy_call_elem(grpc_call_element*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/connected_channel.cc:174:3
    #2 0x10bf846 in grpc_call_stack_destroy(grpc_call_stack*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/channel_stack.cc:217:5
    #3 0xb94cd8 in grpc_core::(anonymous namespace)::SubchannelCallDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:128:3
    #4 0x1273658 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #5 0x1272ac0 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #6 0x51b07c in grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:108:5
    #7 0x10cf16a in grpc_call_unref /proc/self/cwd/src/core/lib/surface/call.cc:596:1
    #8 0x68ce08 in test_keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:211:3
    #9 0x68960d in keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:224:3
    #10 0x4f7c49 in grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:472:7
    #11 0x4eb8fd in main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:128:5
    #12 0x7f0cffd0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
  Uninitialized value was created by a heap deallocation
    #0 0x498309 in __interceptor_free /tmp/clang-build/src/compiler-rt/lib/msan/msan_interceptors.cc:221:3
    #1 0x149f23a in gpr_free /proc/self/cwd/src/core/lib/gpr/alloc.cc:77:3
    #2 0xbbdd70 in grpc_core::(anonymous namespace)::ConnectionDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:983:3
    #3 0x1273658 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #4 0x1272ac0 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #5 0x11db71b in run_some_timers() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:139:30
    #6 0x11daac1 in timer_main_loop() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:245:9
    #7 0x11da8a0 in timer_thread(void*) /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:292:3
    #8 0x14a8039 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100:27
    #9 0x14a7629 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74:25
    #10 0x7f0d00fec6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/src/core/lib/transport/transport.cc:198:14 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*)
Exiting

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by apolcyn** [comment]
pasting the sponge log while it's accessible:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/core/end2end:h2_http_proxy_test@keepalive_timeout@poller=poll-cv
-----------------------------------------------------------------------------
D0202 00:49:55.155219627      20 test_config.cc:391]         test slowdown factor: sanitizer=4, fixture=1, poller=5, total=20
D0202 00:49:55.166912142      20 ev_posix.cc:170]            Using polling engine: poll-cv
D0202 00:49:55.170543781      20 dns_resolver.cc:334]        Using native dns resolver
I0202 00:49:55.171683601      20 keepalive_timeout.cc:43]    keepalive_timeout/chttp2/fullstack
I0202 00:49:55.171774527      20 http_proxy_fixture.cc:536]  Proxy address: localhost:25771
E0202 00:49:55.173510247      20 channel_args.cc:345]        grpc.keepalive_timeout_ms ignored: it must be >= 1
D0202 00:49:55.188258444      20 dns_resolver.cc:275]        Start resolving.
E0202 00:49:55.192125101      21 channel_args.cc:345]        grpc.keepalive_timeout_ms ignored: it must be >= 1
I0202 00:49:55.195038000      20 http_connect_handshaker.cc:299] Connecting to server localhost:25770 via HTTP proxy ipv6:[::1]:25771
D0202 00:49:55.196851337      24 http_proxy_fixture.cc:384]  on_read_request_done: 0x723000000000 "No Error"
I0202 00:49:55.200639215      20 subchannel.cc:1020]         New connected subchannel at 0x704000001280 for subchannel 0x71500001fe00
D0202 00:49:58.701620171      23 dns_resolver.cc:275]        Start resolving.
I0202 00:49:58.701734372      24 http_proxy_fixture.cc:162]  HTTP proxy client read: {"created":"@1549068598.701582533","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":479,"grpc_status":14,"target_address":"ipv6:[::1]:41500"}
I0202 00:49:58.704230772      24 http_proxy_fixture.cc:162]  HTTP proxy server read: {"created":"@1549068598.701824670","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":532,"grpc_status":14,"referenced_errors":[{"created":"@1549068598.701582533","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":479,"grpc_status":14,"target_address":"ipv6:[::1]:41500"}]}
D0202 00:49:58.704305703      24 http_proxy_fixture.cc:130]  endpoints: 0x718000010000 0x718000010400
==20==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xfc3ff1 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*) /proc/self/cwd/src/core/lib/transport/transport.cc:198:14
    #1 0x11aba13 in destroy_call_elem(grpc_call_element*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/connected_channel.cc:174:3
    #2 0x10bf846 in grpc_call_stack_destroy(grpc_call_stack*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/channel_stack.cc:217:5
    #3 0xb94cd8 in grpc_core::(anonymous namespace)::SubchannelCallDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:128:3
    #4 0x1273658 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #5 0x1272ac0 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #6 0x51b07c in grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:108:5
    #7 0x10cf16a in grpc_call_unref /proc/self/cwd/src/core/lib/surface/call.cc:596:1
    #8 0x68ce08 in test_keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:211:3
    #9 0x68960d in keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:224:3
    #10 0x4f7c49 in grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:472:7
    #11 0x4eb8fd in main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:128:5
    #12 0x7f0cffd0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x472b68 in _start (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/end2end/h2_http_proxy_test@keepalive_timeout@poller=poll-cv.runfiles/com_github_grpc_grpc/test/core/end2end/h2_http_proxy_test+0x472b68)
  Uninitialized value was stored to memory at
    #0 0xfc3eb4 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*) /proc/self/cwd/src/core/lib/transport/transport.cc:197
    #1 0x11aba13 in destroy_call_elem(grpc_call_element*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/connected_channel.cc:174:3
    #2 0x10bf846 in grpc_call_stack_destroy(grpc_call_stack*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/channel_stack.cc:217:5
    #3 0xb94cd8 in grpc_core::(anonymous namespace)::SubchannelCallDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:128:3
    #4 0x1273658 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #5 0x1272ac0 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #6 0x51b07c in grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:108:5
    #7 0x10cf16a in grpc_call_unref /proc/self/cwd/src/core/lib/surface/call.cc:596:1
    #8 0x68ce08 in test_keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:211:3
    #9 0x68960d in keepalive_timeout(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/keepalive_timeout.cc:224:3
    #10 0x4f7c49 in grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:472:7
    #11 0x4eb8fd in main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:128:5
    #12 0x7f0cffd0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
  Uninitialized value was created by a heap deallocation
    #0 0x498309 in __interceptor_free /tmp/clang-build/src/compiler-rt/lib/msan/msan_interceptors.cc:221:3
    #1 0x149f23a in gpr_free /proc/self/cwd/src/core/lib/gpr/alloc.cc:77:3
    #2 0xbbdd70 in grpc_core::(anonymous namespace)::ConnectionDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:983:3
    #3 0x1273658 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #4 0x1272ac0 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #5 0x11db71b in run_some_timers() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:139:30
    #6 0x11daac1 in timer_main_loop() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:245:9
    #7 0x11da8a0 in timer_thread(void*) /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:292:3
    #8 0x14a8039 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100:27
    #9 0x14a7629 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74:25
    #10 0x7f0d00fec6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/src/core/lib/transport/transport.cc:198:14 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*)
Exiting
```

**Comment by AspirinSJL** [comment]
Looks similar with https://github.com/grpc/grpc/issues/17335. I will debug it today.

**Comment by vjpai** [comment]
Bumping this to P1 since I've now seen it on OPT tests , not just *san . This hasn't been reported in the wild afaik but this is something that certainly could arise out there.
