### ISSUE TITLE
dotnet app example fails when you use GitBash with Unhandled Exception

### ISSUE THREAD

**Issue by TsuyoshiUshio** [grpc/grpc#17919]
### What version of gRPC and what language are you using?
 
 C#

### What operating system (Linux, Windows, …) and version?
 
Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
dotnet --version
2.1.503
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 I follow the quick start of C# 
https://grpc.io/docs/quickstart/csharp.html

When I start the GreeterServer on the GitBash, it fails. 

```
$ dotnet run -f netcoreapp2.1
Greeter server listening on port 50051
Press any key to stop the server...

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at GreeterServer.Program.Main(String[] args) in C:\Users\tsushi\Codes\grpc\grpc\examples\csharp\Helloworld\GreeterServer\Program.cs:line 46

```
 
### What did you see instead?
 
It works on cmd. 
 
### Anything else we should know about your project / environment?

I have workaround. However, I'd like to know why it happens.  Someone new might confused if there is no direction for not using GitBash.

**Comment by itn3000** [comment]
maybe it's not grpc problem.
As you say, `System.ReadKey` is always failed when running on mintty directly.
I used `winpty dotnet [args]` for workaround.

**Comment by apolcyn** [comment]
Ok, given the exception message surfaced, this doesn't look like an issue within grpc, so closing. Thanks for the update
