### ISSUE TITLE
run grpc php test filed

### ISSUE THREAD

**Issue by yifanes** [grpc/grpc#17922]
php client code:
`        $call = $client->PingPong();

        for ($i = 1; $i < 3; $i++) {
            $request = new \Go\Micro\Srv\Yifanes\Com\Ping();
            $msg = $i;
            $request->setStroke($msg);
            echo sprintf("send msg: %s", $msg);
            $call->write($request);
        }
        $call->writesDone();

        while ($replay = $call->read()) {
            var_dump($replay->getStroke());
        }`
go server code:

```
func (e *Example) PingPong(ctx context.Context, stream example.Example_PingPongStream) error {
		for {
			req, err := stream.Recv()
			if err != nil {
				log.Logf("Got ping %s", err)
				return err
			}
			log.Logf("Got ping %v", req.Stroke)
	
			if err := stream.Send(&example.Pong{Stroke: req.Stroke}); err != nil {
				return err
			}
		}
	}
```
go server log:
> 2019/02/03 23:17:04 Got ping EOF

but I think server will rev 1 and 2 stroke!

**Comment by ZhouyihaiDing** [comment]
Hi. Is PingPong() a bidi-streaming RPC? Can you please provide the proto information you are using?

**Comment by zhangxianyou** [comment]
> Hi. Is PingPong() a bidi-streaming RPC? Can you please provide the proto information you are using?

yes

```
syntax = "proto3";

package go.micro.srv.yifanes.com;

service Example {
	rpc Call(Request) returns (Response) {}
	rpc Stream(StreamingRequest) returns (stream StreamingResponse) {}
	rpc PingPong(stream Ping) returns (stream Pong) {}
	rpc FindWordsById(WordsId) returns (stream Words) {}
}

message Message {
	string say = 1;
}

message Request {
	string name = 1;
}

message Response {
	string msg = 1;
}

message StreamingRequest {
	int64 count = 1;
}

message StreamingResponse {
	int64 count = 1;
}

message Ping {
	int64 stroke = 1;
}

message Pong {
	int64 stroke = 1;
}

message WordsId {
	int64 id = 1;
}

message Words {
	int64 id = 1;
	string word = 2;
	string createdAt = 3;
}
```

**Comment by yifanes** [comment]
> Hi. Is PingPong() a bidi-streaming RPC? Can you please provide the proto information you are using?

yes

```
syntax = "proto3";

package go.micro.srv.yifanes.com;

service Example {
	rpc Call(Request) returns (Response) {}
	rpc Stream(StreamingRequest) returns (stream StreamingResponse) {}
	rpc PingPong(stream Ping) returns (stream Pong) {}
	rpc FindWordsById(WordsId) returns (stream Words) {}
}

message Message {
	string say = 1;
}

message Request {
	string name = 1;
}

message Response {
	string msg = 1;
}

message StreamingRequest {
	int64 count = 1;
}

message StreamingResponse {
	int64 count = 1;
}

message Ping {
	int64 stroke = 1;
}

message Pong {
	int64 stroke = 1;
}

message WordsId {
	int64 id = 1;
}

message Words {
	int64 id = 1;
	string word = 2;
	string createdAt = 3;
}
```

**Comment by ZhouyihaiDing** [comment]
That's strange. The php code seems fine to me.
Can you please try replacing the client with other language like python see if it can get the correct result, so we can locate the issue is caused by the PHP client for sure?
Thank you for the help!
