### ISSUE TITLE
Server reflection support

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1793]

**Comment by vjpai** [comment]
Can we get a status update on this?

**Comment by ctiller** [comment]
@a11r - I'd be willing to move this to GA (along with any dependencies of it - including grpc-tool).

**Comment by ctiller** [comment]
(We should submit the spec to the repository before Beta however).

**Comment by ctiller** [comment]
Reassigning: @a11r is taking over the care and feeding of this document.

**Comment by a11r** [comment]
The specification of the design is now done. Implementation is still pending and will be a blocker for GA. Switching the milestone from Beta to GA.

**Comment by mwitkow** [comment]
@iamqizhao is server reflection something that is planned for gRPC-Go? :)

**Comment by bluecmd** [comment]
Ping! This was set to be in GA but silently removed. No update for a year. Could we have an update please?

**Comment by bluecmd** [comment]
Update from the mailinglist:

> The alpha version of server reflection has been provided in C++ and Go. Its interface is defined in [reflection.proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto). To enable reflection in a C++ server,  we need to link the reflection library to the binary like [this](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/Makefile#L43). We also provide a [descriptor database](https://github.com/grpc/grpc/blob/master/test/cpp/util/proto_reflection_descriptor_database.h) that could be used in client side to fetch server protos.

> Server reflection in other languages may come later. A server reflection example in C++ will be added shortly.

**Comment by y-zeng** [comment]
C++ Server Reflection tutorial: https://github.com/grpc/grpc/blob/master/doc/server_reflection_tutorial.md

**Comment by sreecha** [comment]
@y-zeng - I am assuming this can be closed.

**Comment by y-zeng** [comment]
C++ server reflection is done. Wrapped language server reflection can be tracked in #2565 (python),  #2566 (C#), #2567 (Ruby), #2568 (Node).
