### ISSUE TITLE
InsecureServerCredentials->SetAuthMetadataProcessor() will crash the app

### ISSUE THREAD

**Issue by jozefizso** [grpc/grpc#17942]
### What version of gRPC and what language are you using?
 grpc v1.14.1, C++
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 MSVC
 
### What did you do?
We want to use our own `AuthMetadataProcessor` class in a gRPC server which uses insecure server credentials.
 
### What did you expect to see?
 Server credentials configured with custom `AuthMetadataProcessor` implementation.
 
### What did you see instead?
 Application will crash when it calls `InsecureServerCredentials->SetAuthMetadataProcessor()` method.

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: Server.exe

abort() has been called

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```
 
### Anything else we should know about your project / environment?

Sample code:

```cpp
auto* processor = new TestAuthMetadataProcessor();
auto serverCredentials = grpc::InsecureServerCredentials();
serverCredentials->SetAuthMetadataProcessor(std::shared_ptr<AuthMetadataProcessor>(processor));
```

**Comment by apolcyn** [comment]
I believe setting an `SetAuthMetadataProcessor()` is not supported on insecure credentials for security reasons.

**Comment by apolcyn** [comment]
see this groups chat for some background: https://groups.google.com/forum/#!topic/grpc-io/ifL63H0kN48... I think the assertion hit here is not something we want to remove
