### ISSUE TITLE
Missing good enough C++ platform portability and cross compilation instructions

### ISSUE THREAD

**Issue by maettu-this** [grpc/grpc#17961]
### What version of gRPC and what language are you using?
Latest version
C++
 
### What operating system (Linux, Windows, …) and version?
Build = Windows 10 x64
Target = Segger embOS on Cortex-M3/M4 based MCUs
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
IAR ARM
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

1. Downloaded latest release from [releases](https://github.com/grpc/grpc/releases).
2. Tried to compile that code in IAR ARM, coming to conclusion that cross compilation of gRPC is required to run gRPC on a truly aka single chip aka bare metal embedded system.
3. Tried to cross compile according to [issue 9719](https://github.com/grpc/grpc/issues/9719), coming to conclusion that cross compilation only seems possible with gcc, since several language specifics like __inline, __sync_synchronize, __volatile__,... are being used.

**=> Stuck.**
 
### What did you expect to see?
Good enough instructions on how to cross compile to an truly embedded target. After all, https://grpc.io/blog/installation says "easy installation" and https://grpc.io/blog/principles "viable on CPU & memory limited devices".
 
### What did you see instead?
Several issues describing issues with cross compilation.
No known use of gRPC on an ARM based truly embedded MCU.
 

 
### Anything else we should know about your project / environment?
On truly embedded systems, IAR ARM is among the four mostly used compilers (ARM, GCC, IAR, Keil).

**Comment by nicolasnoble** [comment]
That's not a supported platform. Only windows or posix environnements are supported.

**Comment by maettu-this** [comment]
Is this a not yet supported platform, or will it never be? In the latter case, please adjust the "viable on CPU & memory limited devices" at https://grpc.io/blog/principles accordingly.

In any case, I think the C++ cross compilation instructions should be more clearly stated somewhere. And just referring to [issue 9719](https://github.com/grpc/grpc/issues/9719) cannot be a solution.

**Comment by nicolasnoble** [comment]
Very likely to never be, at least not by this codebase. The underlying architecture is highly tuned around a multithreaded network polling system in C++, which makes supporting bare metal MCUs close to impossible. The blog post refers to devices like the raspberry pi. Please note that the post and documentation only talks about CPU. What you're referring to are MCUs.

**Comment by maettu-this** [comment]
I see. Two comments:

- There is no reason why multithreading and TCP/IP networking should not be possible on truly embedded MCUs. Yes, it may be limited in terms of performance and memory availability, but no, this alone cannot explain why it shouldn't be possible.
- MCUs actually **are** "CPU & memory limited", since an MCU contains a relatively simple CPU as well as a limited amout of memory. I cannot see why that statement wouldn't apply to MCU based systems...

**Comment by maettu-this** [comment]
PS: Maybe the initial title _missing good enough C++ cross compilation instructions_ wasn't accurate enough, so I have just refined it to _missing good enough C++ platform portability and cross compilation instructions_. Maybe this should rather be two separate tickets, though topics are highly coupled to each other. In the end, the following questions should be answered:

- How can I port gRPC to a different platform?
   a) Given my platform partly supports POSIX, which APIs are needed for gRPC?
   b) Given my platform does not support POSIX, which functionality does the platform have to provide and how can I adapt gRPC accordingly?
- How can I port gRPC to a different compiler, e.g. IAR ARM, in order to be able to cross compile with that compiler?

Hoping I could further clarify the topic with these additional questions. And if gRPC does not intend to ever support truly embedded platforms and related compilers, that's OK, just clearly state that at a location where people find the information.

**Comment by maettu-this** [comment]
Hey guys, (or hey stale bot), just because you don't find time to get this fixed, it doesn't mean it no longer applies!

**Comment by jtattermusch** [comment]
Some improvements have been made to https://github.com/grpc/grpc/blob/master/BUILDING.md (cross compilation examples).

Beyond that, we support major linux distributions, mac OS X and windows.

**Comment by jtattermusch** [comment]
There's always need for better documentation, but for now I'm going to close with "help wanted" label.
