### ISSUE TITLE
Missing description of minimal system requirements

### ISSUE THREAD

**Issue by maettu-this** [grpc/grpc#17962]
### What version of gRPC and what language are you using?
None so far, yet evaluating.
 
### What operating system (Linux, Windows, …) and version?
Build = Windows 10 x64
Target = Segger embOS on Cortex-M3/M4 based MCUs
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
IAR ARM
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Downloaded latest release, browsed through information at https://grpc.io/, googled for several keywords like "gRPC system requirements", "gRPC minimal requirements", "gRPC memory requirements",...
 
### What did you expect to see?
Given the hello world example, the resulting code size on a typical Cortex-M based MCU system.
Given the hello world example, the required RAM size on a typical Cortex-M based MCU system.
The required functionality of the underlying host/subsystem, like synchronization primitives, process invocation, process termination, exception handling, debugging,...
 
### What did you see instead?
Didn't find anything. Except https://grpc.io/blog/principles which states "viable on CPU & memory limited devices" and https://grpc.io/blog/optimizing-grpc-part-1 which talks about speed optimization. But nothing regarding memory footprint.
 

 
### Anything else we should know about your project / environment?
On truly aka single chip aka bare metal embedded system speed is often not the limiting factor, but memory is. Typical larger MCUs offer 512 KB of Flash and 64 KB of RAM. Higher memory requirements can only be met by adding external memory, increasing cost and reducing performance.

**Comment by nicolasnoble** [comment]
There no bare metal support.

**Comment by maettu-this** [comment]
Is there no bare metal support yet, or will there never be? In the latter case, please adjust the "viable on CPU & memory limited devices" at https://grpc.io/blog/principles accordingly.

In any case, I think minimal system requirements should be clearly stated somewhere. Even if it is just something like "full POSIX or Win32 API required".

**Comment by maettu-this** [comment]
Hey guys, (or hey stale bot), just because you don't find time to get this fixed, it doesn't mean it no longer applies!

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work

**Comment by maettu-this** [comment]
To me (being a software engineer) closed means closed = done or rejected. And done means implemented + documented + verified and whatever else the definition of done requires. While [help wanted] definitely makes sense, seeing [closed] on something that is a "valid feature request" sounds strange to me.

Well then, yet another improvement ticket that eventually will drown in a software's ocean of open issues... Too bad that this happens all the time, even with no-brainers like this one which could easily be solved just by editing some online text...

> please adjust the "viable on CPU & memory limited devices" at https://grpc.io/blog/principles accordingly.

> minimal system requirements should be clearly stated somewhere. Even if it is just something like "full POSIX or Win32 API required".
