### ISSUE TITLE
gRPC ObjC new API does not report initial metadata immediately

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#17968]
The gRPC Objective-C's new API is using the old API, but the old API does not proactively report reception of initial metadata, so the new API must depend on a successful read_message to trigger itself checking initial metadata being published, then push it to the user. This is counter intuitive and should be fixed.

**Comment by danlanxiaohei** [comment]
@srini100 I had the same problem, i use  gRPC bidirectional streaming  call, the iOS client will not call 【- (void)didReceiveInitialMetadata:(nullable NSDictionary *)initialMetadata;】until the server send a message  first ! Can you  help ?

**Comment by danlanxiaohei** [comment]
@muxi do  you have any new progress on this issue ? I had the same problem.

**Comment by muxi** [comment]
@danlanxiaohei - we have not looked into this issue in detail since we expected this problem to only affect a very small fraction of users and can be worked around (with an empty/nop message in the beginning of the response stream). Thanks for letting us know that you are affected. If we get to fix this we'll update it here, but contributions are always great and welcome.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
