### ISSUE TITLE
provide a public api to convert a StatusCode to a string

### ISSUE THREAD

**Issue by benjaminp** [grpc/grpc#17969]
There should be a way to obtain a symbolic string representation of `grpc::StatusCode`. `grpc_status_code_string` exists, but it's not provided in a public header.

**Comment by benjaminp** [comment]
seems like it remains a valid feature request

**Comment by mhaidrygoog** [comment]
Not sure, what the issue is. error_message() and error_details() are both available as part of the Status class
https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/status.h

**Comment by benjaminp** [comment]
The goal is turn a value of the `StatusCode` enum into a string. This task is not directly related to the `Status` class and its associated error messages.

As noted in the OP, I essentially want a public version of `grpc_status_code_to_string`.

**Comment by benjaminp** [comment]
(Do you mind reopening this issue?)
