### ISSUE TITLE
Workspace setup makes it hard to depend on GRPC

### ISSUE THREAD

**Issue by kwasimensah** [grpc/grpc#17963]
This is essentially the same as https://github.com/grpc/grpc/issues/11630. I'm trying update https://github.com/bazelbuild/bazel to not have it's own local copy of GRPC, but I need to setup all the binds in https://github.com/grpc/grpc/blob/007b721f8045ceef4ebf418a2935ab772fbe3708/bazel/grpc_deps.bzl for that to work.

Bind is not recommended (https://github.com/bazelbuild/bazel/issues/1952), not strictly necessary (you can refer to these targets through their repo qualified label), and requires projects that want to depend on you to know about the internals of how you have your dependencies structured.

**Comment by kwasimensah** [comment]
ok, not completely the same as #11630 as they wanted a full copy in third_party. But don't think I can make protobuf's WORKSPACE file depend on grpc_deps.bzl. I could copy and paste that into their repo that opens up version inconsistencies.

**Comment by jtattermusch** [comment]
CC @nicolasnoble  who handled the original issue and knows the context

**Comment by kwasimensah** [comment]
Reopening as the usage of bind should be fixed

**Comment by kwasimensah** [comment]
i.e. this should be reopened. I don't have the priviliges to do that here

**Comment by jtattermusch** [comment]
CC @gnossen

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
