### ISSUE TITLE
Add sha256 to http_archive rules

### ISSUE THREAD

**Issue by kwasimensah** [grpc/grpc#17966]
The http_archive rules in https://github.com/grpc/grpc/blob/007b721f8045ceef4ebf418a2935ab772fbe3708/bazel/grpc_deps.bzl don't specify the sha256 attribute.

This is not recommend for released projects (https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L210). It's a security risk and also makes bazel's remote fetching less efficient.

**Comment by jtattermusch** [comment]
@AspirinSJL  it's mostly C/C++ stuff dependencies, so this should be addressed by C-core team.

**Comment by jtattermusch** [comment]
CC @nicolasnoble

**Comment by jtattermusch** [comment]
I believe this has been already fixed.
