### ISSUE TITLE
Consider updating System.Interactive.Async to 3.2

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#17976]
Grpc.Core is referencing System.Interactive.Async 3.1.1. It was released in 2016.

Consider updating to System.Interactive.Async 3.2.0.

https://www.nuget.org/packages/System.Interactive.Async

**Comment by jtattermusch** [comment]
We've considered that (see https://github.com/grpc/grpc/pull/16745), but there seems to be some problem that breaks the unity build, I'll have to see if that got fixed since.

**Comment by jtattermusch** [comment]
Fixed by #16745.
