### ISSUE TITLE
ABI finalization.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1799]
After we release 1.0, we won't have many opportunities to make API changes that break gRPC's ABI. We need to stabilize it by then.

**Comment by nicolasnoble** [comment]
Technically done in #2612, but re-assigning to @ctiller for double-checking if everything was covered, and potentially doing the same with the channel state API (or not).

**Comment by vjpai** [comment]
Oops! I just created a new issue to see about doing this for channel
connectivity. I will close that up as a dupe.

**Comment by jboeuf** [comment]
Assigning myself to take care of grpc_security.h.

**Comment by jayantkolhe** [comment]
Fixed with #2947
