### ISSUE TITLE
[Fea]  implement grpc++ pubsub pattern

### ISSUE THREAD

**Issue by yiakwy** [grpc/grpc#18001]
### What version of gRPC and what language are you using?
 grpc-c++
 
### What operating system (Linux, Windows, …) and version?
 MacOS, Linux (CentOS, Ubuntu)
 
### What did you do?
 
Without using ROS2, there is no easy way to use grpc in PubSub pattern. I am currently trying to implement a grpc based pubsub server for grpc nodes to inherit. The key point is how to implement a broker service. Google does provide us with a cloud-based rpc non-c++ SDK for developers who host kubenetes services in gcloud. However, for one thing, we implement algorithms in c++ deeply relying on c++ ecosystem; another thing is that we are reluctant to use google cloud simply for RPC services. 

ROS2 has already integrated grpc for fast rpc. However, it is too big for our CMake based project.

Hence, I conclude that we need to develop my own grpc++ PubSub services. I want to know whether do you have any plan to do such things? Bits of help and suggestions are welcome!

### What did you expect to see?
 
Grpc++ PubSub for IPC or local machine clusters. 

### What did you see instead?
 
RPC without Pubsub is useless. I can't imagine how to develop a distributed application without Pubsub and brokers. Otherwise, WebSocket can do many dirty things for us. I especially have a preference in c++ CMake projects.
 
### Anything else we should know about your project/environment?
 
I love linux and macOS

**Comment by yiakwy** [comment]
@hassox @timburks @blowmage @haberman

**Comment by yiakwy** [comment]
@@vjpai @markdroth

**Comment by AspirinSJL** [comment]
We are at RPC layer, so implementing pubsub may not be in our scope. Sorry, closing.

But you may find this example helpful: https://gist.github.com/yang-g/257d758cdb990eec42f8.

**Comment by yiakwy** [comment]
@AspirinSJL I already implemented almost every function a pubsub service need by following gcloud pubsub proto .

I stucked in grpc async server multiple threads model. I am currently reading https://github.com/grpc/grpc/blob/master/test/cpp/qps/server_async.cc to learn how host multiple services methods. But I have no idea how to implement threading model with 1 or more completion queue.

In this example we have,  each thread has a unique completion queue and CallData (ServerRpcContext instance, like CallData in our cpp demo) . I think completion queue used for multiplexing. Each time an event arrives, we spawn a new thread to handle the event and give it a unique tag. Why do we need multi completion queue in that example I am confused. 
@AspirinSJL  @vjpai 

Hi, AspirinSJL, I found vjpai is active in community and wrote those test codes, could you help me to find him?

**Comment by AspirinSJL** [comment]
Regarding async service implementation, I wrote the load reporter service before, which may be helpful in your case. It uses one completion queue.
 https://github.com/grpc/grpc/blob/master/src/cpp/server/load_reporter/load_reporter_async_service_impl.cc

Vijay is available on github. You are @ing the right account.

**Comment by yiakwy** [comment]
@AspirinSJL Thank you! I read it immediately. grpc code base itself is the treasure I am pursuing to understand. It feels like that you are trying to decouple the completion queue with service logics.

**Comment by AspirinSJL** [comment]
Actually the service logic should be independent on the completion queue?

The completion queue is to do polling related work, and the loop to use it is very similar among different services' implementation.

**Comment by yiakwy** [comment]
It is really cool! That was what I was trying to figure out in the past few days after reading demo codes. We could improve documentation by employing the pattern you give. I also invite you to participate in the discussion https://github.com/grpc/grpc/issues/18055 to help me figure out threading model problems.  I post them on https://groups.google.com/forum/#!topic/grpc-io/CC73-Dr4Ilc

**Comment by AspirinSJL** [comment]
So I'm wondering why the qps service is listed as demo code in our repo. It's test code. 

Any link to where you see it as demo code?

**Comment by yiakwy** [comment]
It is not demo code. Instead it gives me more feeling about how to use Cq
with thread for multiple services. This was first seen in grpc.io when
people discuss about grpc "threading model" and one of the developers wrote
that "there are more complex codes in test/qps" using a threading model
compared to the codes in test/cpp/hybrid_async.cc and other codes related
to async server threading models.

Juanli Shen <notifications@github.com> 于2019年2月22日周五 下午3:34写道：
