### ISSUE TITLE
grpcio + poetry (incorrect dependency of enum34 + futures)

### ISSUE THREAD

**Issue by adithyabsk** [grpc/grpc#18013]
### What version of gRPC and what language are you using?
Python gRPC:
* grpcio == 1.18.0
 
### Issue Summary
While installing tensorflow through poetry, I ran into an issue with grpcio as it seems that due to the way this project was packaged, enum34 and futures shows up as a dependency (through sdist) for python 3+ even though it is not. 

* See https://github.com/sdispater/poetry/issues/881#issue-408695021

### Potential Solution
After further digging it seems that ading environment markers to the setup.py might be the way to solve this problem in compliance with PEP 508

* See https://github.com/sdispater/poetry/issues/844#issuecomment-458178991

**Comment by gnossen** [comment]
Resolved by #18032

**Comment by jjinux** [comment]
@gnossen, I'm trying to understand how your fix fixes the issue. You made a change to setup.py. However, according to https://github.com/sdispater/poetry/issues/328, "Poetry never executes the setup.py file for security reasons and as such relies on the package metadata available in the JSON API: https://pypi.org/pypi/grpcio/json". Also, I'm trying to use grpcio 1.19.0 (which is the newest version), and Poetry still insists on installing futures.

**Comment by gnossen** [comment]
@jjinux You're correct that `poetry` pulls from the json api, but `setup.py` is how we generate the wheel whose `METADATA` file -- from a quick parse of the [`warehouse`](https://github.com/pypa/warehouse/blob/master/warehouse/legacy/api/json.py#L179) and [`twine`](https://github.com/pypa/twine/blob/master/twine/wheel.py#L45) codebases -- is used by `PyPi` to generate its json metadata. PR #18032 just missed the branch cut for `1.19`, so it didn't make it into that release, but it should be in `1.20` very soon.

**Comment by jjinux** [comment]
Thanks, @gnossen!

**Comment by jjinux** [comment]
BTW, @gnossen, any idea when the next version will be released? Since the code involves C extensions, it's non-trivial to just use master.

**Comment by gnossen** [comment]
The branch cut is actually happening today, so you can expect the release in a few weeks. In the meantime, there should be a release candidate pushed to `PyPi` that you *may* be able to opt into in the next couple of days. I'm not sure how well `poetry` plays with release candidates.

**Comment by jjinux** [comment]
Thanks.

**Comment by ADR-007-SoftServe** [comment]
Hi!
Do you have a daily build somewhere?

**Comment by gnossen** [comment]
[We sure do.](https://packages.grpc.io/)

**Comment by ADR-007-SoftServe** [comment]
Thanks!

**Comment by jjinux** [comment]
Gosh, I wish I had known that. I ended up creating a futures repo with no real code in it to fake out Poetry until the next release :-/

**Comment by ADR-007-SoftServe** [comment]
> Gosh, I wish I had known that. I ended up creating a futures repo with no real code in it to fake out Poetry until the next release :-/

Another solutions:
1. Use Python 3.7.2 instead of 3.7.3
2. Download the package and install it 
```
pip download grpcio
poetry add --file vendor/grpcio_blabla.whl grpcio
```
