### ISSUE TITLE
Name resolution failure error in Unity Android with grpc 1.19.0

### ISSUE THREAD

**Issue by raulpereztangelo** [grpc/grpc#18038]
### What version of gRPC and what language are you using?
 grpc_unity_package.1.19.0-dev.zip and C# in Unity.
 
### What operating system (Linux, Windows, …) and version?
 MacOS 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Issue happens in Android and I build the solution with IL2CPP.
 
### What did you do?
Update from grpc_unity_package.1.18.0-dev.zip to 1.19.0
Make a request in MacOS
Make the same request in Android
 
### What did you expect to see?
 async request in osx successful
 async request in android successful
 
### What did you see instead?
 async request in osx successful
 async request in android failed with: **"Name resolution failure"**

**Comment by gnossen** [comment]
@apolcyn Perhaps related to the `c-ares` change?

**Comment by apolcyn** [comment]
It seems likely. @raulpereztangelo any chance your able to run the android code under environment variable settings:
* `GRPC_VERBOSITY=DEBUG`
* `GRPC_TRACE=http,client_channel,cares_resolver,cares_address_sorting`
?

and share the output?

**Comment by apolcyn** [comment]
@raulpereztangelo if you can share a bit more info on the Android environment, e.g. Android version or device, that would be helpful.

**Comment by ericgribkoff** [comment]
@apolcyn I'm able to reproduce the failure on master using our [C++ Android interop client](https://github.com/grpc/grpc/tree/master/src/android/test/interop) on a physical Pixel 3 device running Android 9.  ("Resolver transient failure", I believe the message may have changed earlier today in https://github.com/grpc/grpc/commit/bab812376331ac90b714d342667eb941c9e8a4ab). Resolution succeeds when building on v1.18.0.

**Comment by ericgribkoff** [comment]
Actually, the "Resolver transient failure" error was with our helloworld app, the interop client actually crashes: I believe this is related to https://github.com/c-ares/c-ares/pull/148

**Comment by ericgribkoff** [comment]
@apolcyn This can be closed as fixed now, right?

**Comment by apolcyn** [comment]
Yeah, this can be fixed. I've just left a TODO to re-evaluate Android support after upgrading c-ares
