### ISSUE TITLE
Improve grpc-tool.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1805]
We want to be able to parse proto files instead of just using binary files. Potentially also wanting to use the server reflection from #1793.

**Comment by ctiller** [comment]
We've talked about moving this to GA - it doesn't make sense without server reflection up, which is also on the GA list afaik.

**Comment by bluecmd** [comment]
Update from the mailing list:

> gRPC CLI already supports reflection. Instructions on how to build and use it can be found at https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md
> Currently it only has 'call' command and supports unary calls. More commands and streaming call support will come soon.
