### ISSUE TITLE
Please Write A Beta Release Note

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1809]
Feel free to add pull requests in the comments below to get the attention of whomever writes the pull request. Write your release notes in here if that's easier for you.

**Comment by nicolasnoble** [comment]
#1558 needs a word or two.

**Comment by nicolasnoble** [comment]
#1577 should definitely be documented in the release notes for Beta.

**Comment by nicolasnoble** [comment]
#1758 could use some release notes.

**Comment by ctiller** [comment]
Naming needs a release note.

**Comment by stanley-cheung** [comment]
Can this issue be closed now?

**Comment by soltanmm** [comment]
If anyone takes issue with this being closed they can hit me over the head with a newspaper later.
