### ISSUE TITLE
Latest versions not available as composer packages

### ISSUE THREAD

**Issue by ronnylt** [grpc/grpc#18137]
### What version of gRPC and what language are you using?
v 1.18
PHP
 
### What did you do?
I am using the latest grpc version (1.18), but it is  not available as a composer package in https://packagist.org/packages/grpc/grpc
 
### What did you expect to see?
The latest releases available as a composer packages (the last version currently  available is 1.15) 
 
### What did you see instead?
 Last version currently  available is 1.15

**Comment by stanley-cheung** [comment]
Working on it: https://github.com/grpc/grpc-php/pull/11

**Comment by stanley-cheung** [comment]
Done. v1.19.0 has been released for the composer package. But really, there's effectively no change since v1.15.0.
