### ISSUE TITLE
Out-of-bound memory read in hpack_parser.cc

### ISSUE THREAD

**Issue by equinox1993** [grpc/grpc#18132]
### What version of gRPC and what language are you using?
 gRPC++, commit 318c67782a752a8324233ff95e594a19f85578a7
 
### What operating system (Linux, Windows,...) and version?
 gLinux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

clang version 9.0.0 (trunk 353250)
Target: x86_64-unknown-linux-gnu
Thread model: posix

GN args to repro (for building on Chromium):
```
host_cpu = "x86"
is_asan = true
is_component_build = true
is_debug = true
optimize_for_fuzzing = true
symbol_level = 1
target_cpu = "x86"
use_goma = true
use_libfuzzer = true
```
 
### What did you do?
1. Build and run the `grpc_hpack_parser_fuzzer_test` target on Chromium with the GN args above. This essentially runs `test/core/transport/chttp2/hpack_parser_fuzzer_test.cc` on 32-bit environment.

1. Feed the fuzzer with this 8-byte input:
   ```
   0x41 0x7f 0xff 0xf6 0xff 0xff 0x8e 0x00
   ```
 
### What did you expect to see?
 The test shall not fail
 
### What did you see instead?
Test failed. Complaining `Heap-buffer-overflow READ 4` in the `gpr_murmur_hash3` function.

Backtrace:
```
#0  __sanitizer::Die() ()
    at /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:51
#1  0x5668959c in ~ScopedInErrorReport ()
    at /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/asan_report.cc:186
#2  0x566888fb in ReportGenericError ()
    at /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/asan_report.cc:463
#3  0x5668194a in __asan_memcpy ()
    at /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:22
#4  0x56a9d46b in gpr_murmur_hash3 (key=0xf4b07288, len=4026530814, seed=0)
    at ../../third_party/grpc/src/src/core/lib/gpr/murmur_hash.cc:47
#5  0x56894e30 in grpc_slice_default_hash_impl (s=...)
    at ../../third_party/grpc/src/src/core/lib/slice/slice_intern.cc:162
#6  0x56895683 in grpc_slice_hash (s=...)
    at ../../third_party/grpc/src/src/core/lib/slice/slice_intern.cc:176
#7  0x568969b5 in grpc_slice_intern (slice=...)
    at ../../third_party/grpc/src/src/core/lib/slice/slice_intern.cc:210
#8  0x567f129e in take_string (p=0xf5f26c10, str=0xf5f26c50, intern=true)
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:664
#9  0x567eb71c in finish_lithdr_incidx (p=0xf5f26c10, 
    cur=0xe4b06e86 <error: Cannot access memory at address 0xe4b06e86>, end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:803
#10 0x567e955e in parse_next (p=0xf5f26c10, 
    cur=0xe4b06e86 <error: Cannot access memory at address 0xe4b06e86>, end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:686
#11 0x567ecc8f in begin_parse_string (p=0xf5f26c10, cur=0xf4b07288 "", end=0xf4b07288 "", 
    binary=0 '\000', str=0xf5f26c50)
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1463
#12 0x567ec31b in parse_value_string (p=0xf5f26c10, cur=0xf4b07288 "", end=0xf4b07288 "", 
    is_binary=false)
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1522
#13 0x567eb1eb in parse_value_string_with_indexed_key (p=0xf5f26c10, cur=0xf4b07288 "", 
    end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1531
#14 0x567e955e in parse_next (p=0xf5f26c10, cur=0xf4b07288 "", end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:686
#15 0x567ea81d in parse_value5up (p=0xf5f26c10, cur=0xf4b07287 "", end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1195
#16 0x567ea078 in parse_value4 (p=0xf5f26c10, cur=0xf4b07286 "\216", end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1165
#17 0x567e9aa4 in parse_value3 (p=0xf5f26c10, cur=0xf4b07285 "\377\216", end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1131
#18 0x567e97e4 in parse_value2 (p=0xf5f26c10, cur=0xf4b07284 "\377\377\216", end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1113
#19 0x567e9334 in parse_value1 (p=0xf5f26c10, cur=0xf4b07283 "\366\377\377\216", 
    end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1095
#20 0x567e9071 in parse_value0 (p=0xf5f26c10, cur=0xf4b07282 "\377\366\377\377\216", 
    end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1077
#21 0x567ebc45 in parse_string_prefix (p=0xf5f26c10, cur=0xf4b07281 "\177\377\366\377\377\216", 
    end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1220
#22 0x567e59d5 in parse_lithdr_incidx (p=0xf5f26c10, 
    cur=0xf4b07280 "A\177\377\366\377\377\216", end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:831
#23 0x567e23b2 in parse_begin (p=0xf5f26c10, cur=0xf4b07280 "A\177\377\366\377\377\216", 
    end=0xf4b07288 "")
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:698
#24 0x567e30e9 in grpc_chttp2_hpack_parser_parse (p=0xf5f26c10, slice=...)
    at ../../third_party/grpc/src/src/core/ext/transport/chttp2/transport/hpack_parser.cc:1583
#25 0x566b7773 in LLVMFuzzerTestOneInput (data=0xf4b07280 "A\177\377\366\377\377\216", size=8)
    at ../../third_party/grpc/src/test/core/transport/chttp2/hpack_parser_fuzzer_test.cc:45
#26 0x5673a2e4 in fuzzer::Fuzzer::ExecuteCallback (this=0xf4903680, 
    Data=0xf4b07500 "A\177\377\366\377\377\216", Size=8)
    at ../../third_party/libFuzzer/src/FuzzerLoop.cpp:529
#27 0x566d1fb0 in fuzzer::RunOneTest (F=0xf4903680, 
    InputFilePath=0xf4b01880 "/usr/local/google/home/yuweih/.clusterfuzz/cache/testcases/5710351129772032_testcase/fuzz-0", MaxLen=0) at ../../third_party/libFuzzer/src/FuzzerDriver.cpp:286
#28 0x566d9a4e in fuzzer::FuzzerDriver (argc=0xf5eeab50, argv=0xf5eeab60, 
    Callback=0x566b73f0 <LLVMFuzzerTestOneInput(uint8_t const*, size_t)>)
    at ../../third_party/libFuzzer/src/FuzzerDriver.cpp:715
#29 0x567700bb in main (argc=5, argv=0xffffc9d4)
    at ../../third_party/libFuzzer/src/FuzzerMain.cpp:19
```

Clusterfuzz details: https://clusterfuzz.com/testcase-detail/5710351129772032
Bug on Chromium: http://crbug.com/934128 

### Anything else we should know about your project / environment?

Looks like the problem is in this line:
https://github.com/grpc/grpc/blob/15c947a080e20b4d5627d26eb8b5b10fe62a82b8/src/core/ext/transport/chttp2/transport/hpack_parser.cc#L1195

~~`parse_value5up` calls `parse_next` on `cur + 1` regardless of `cur + 1` being the same as `end`, and `parse_next` parses the data without checking `cur < end` either.~~

Looks like `parse_next` is expected to have `cur == end` in some cases so the problem really is `begin_parse_string` doesn't handle the `cur == end` case well.

Note that I can't reproduce the failure on x64 target architecture (which is where gRPC's clusterfuzz runs IIUC) even with the same input. Something might be causing a false negative.

**Comment by equinox1993** [comment]
There is another crash in hpack_parser.cc. I'm investigating it.

Chromium bug if you're interested: http://crbug.com/934087

**Comment by equinox1993** [comment]
Seems to be similar issue. This one happens in `parse_value4`:
https://github.com/grpc/grpc/blob/15c947a080e20b4d5627d26eb8b5b10fe62a82b8/src/core/ext/transport/chttp2/transport/hpack_parser.cc#L1167

I think `parse_next` should do something like this as in the `parse_begin` function?
```
  if (cur == end) {
    p->state = parse_begin;
    return GRPC_ERROR_NONE;
  }
```

**Comment by yang-g** [comment]
I think what happened is an overflow under 32bit system.

Note when we are trying to parse a string from HPACK, we first decode the string's length. In the above case of `0x41 0x7f 0xff 0xf6 0xff 0xff 0x8e 0x00`, the length is `4026530687`, which is then converted to `intptr_t` in https://github.com/grpc/grpc/blob/15c947a080e20b4d5627d26eb8b5b10fe62a82b8/src/core/ext/transport/chttp2/transport/hpack_parser.cc#L1455

The conversion, if `intptr_t` is 32bit, will result in `-268436609`. At this time, `end == cur` and the comparison `0 >= -268436609` tests to true and then the error.

I could not see the second bug details but I would guess it is something similar.

So I think the fix linked above is likely not right, because this can happen when `end > cur` too.

It seems like a valid thing to be fixed as we should not parse out of bound on *any* data read from wire and I suppose we do not have a guard in front of the parser to check this (the test is creating a parser directly).
The right fix seems to be to return an error when `p->strlen` is going to overflow when converting to a `int32_t` or even further lower the bound with `SETTINGS_MAX_HEADER_LIST_SIZE`.

**Comment by yang-g** [comment]
The `p->strlen` is defined as `uint32_t`, if it is not clear from the context.

**Comment by equinox1993** [comment]
FYI the second test input is `00 7F FF FF FF FF 08`. Anyhow your PR fixes both of the test cases :)

**Comment by yang-g** [comment]
@equinox1993 Thanks for checking it out.
