### ISSUE TITLE
rpath not sufficient to allow installing in non-default location on Linux

### ISSUE THREAD

**Issue by dankegel** [grpc/grpc#18131]
### What version of gRPC and what language are you using?
1.17.1, C++ 
 
### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 18.04 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
default gcc (7.3.0)
 
### What did you do?
Configured, built, and installed grpc with --prefix=/opt/foobar
 
### What did you expect to see?
Expected "ldd /opt/foobar/lib/libgrpc++.so.6" to find all its dependencies
 
### What did you see instead?
ldd output "libgrpc.so.6 => not found"

Not sure why this didn't bite me on ubuntu 16.04, too, but the following patch (and the corresponding change to the generated Makefile) got me up and running:

```
--- grpc-1.17.1/templates/Makefile.template.old	2019-01-03 16:11:42.458892567 -0800
+++ grpc-1.17.1/templates/Makefile.template	2019-01-03 16:14:29.296294987 -0800
@@ -274,6 +274,28 @@
   LDFLAGS += -pthread
   endif
 
+  # If we are installing into a non-default prefix, both
+  # the libraries we build, and the apps users build,
+  # need to know how to find the libraries they depend on.
+  # There is much gnashing of teeth about this subject.
+  # It's tricky to do that without editing images during install,
+  # as you don't want tests during build to find previously installed and
+  # now stale libraries, etc.
+  ifeq ($(SYSTEM),Linux)
+  ifneq ($(prefix),/usr)
+  # Linux best practice for rpath on installed files is probably:
+  # 1) .pc file provides -Wl,-rpath,$(prefix)/lib
+  # 2) binaries we install into $(prefix)/bin use -Wl,-rpath,$ORIGIN/../lib
+  # 3) libraries we install into $(prefix)/lib use -Wl,-rpath,$ORIGIN
+  # cf. https://www.akkadia.org/drepper/dsohowto.pdf
+  # Doing all of that right is hard, but using -Wl,-rpath,$ORIGIN is always
+  # safe, and solves problems seen in the wild.  Note that $ORIGIN
+  # is a literal string interpreted much later by ld.so.  Escape it
+  # here with a dollar sign so Make doesn't expand $O.
+  LDFLAGS += '-Wl,-rpath,$$ORIGIN'
+  endif
+  endif
+
   #
   # The steps for cross-compiling are as follows:
   # First, clone and make install of grpc using the native compilers for the host.
```

**Comment by dankegel** [comment]
Also reproduced with tip of master.

```
$ sudo mkdir /opt/grpc
$ git clone --recursive git@github.com:grpc/grpc
$ cd grpc
$ git describe
v1.12.1-4984-ga0e06fdac4
$ make shared prefix=/opt/grpc
$ sudo chown $LOGNAME /opt/grpc
$ make install prefix=/opt/grpc
$ ldd /opt/grpc/lib/libgrpc++.so.1
        linux-vdso.so.1 (0x00007ffde8b07000)
        libgrpc.so.7 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f07f5cb3000)
...
```

**Comment by dankegel** [comment]
How relocatable are grpc shared libraries supposed to be?  Are there situations where an absolute rpath is bad?  If so, maybe I should try a relative rpath of some sort.

**Comment by nicolasnoble** [comment]
So, we've been really relying on people's ld.conf system to solve this for us. I am not THAT much an expert, and I don't necessarily have strong opinions, but my solution to issues similar to the ones you're describing always has been for me to drop a line in /etc/ld.so.conf.d/ somewhere and rerun `ldconfig`.

I'm actually fine with #18183, provided it doesn't break existing usage.

**Comment by dankegel** [comment]
Reviewing #18183 I see it's already relative.  I had forgotten that I did it right already :-)
I feel fairly confident it won't break existing usage, and we've been using the patch here for some time.
