### ISSUE TITLE
Auto ping open P0/P1 issues periodically  

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#18135]
There are some existing github bots to auto comment issues, but no one is doing it periodically. 

We may have to write it from scratch and make it a cron job on GCE.

**Comment by nicolasnoble** [comment]
https://github.com/firebase/oss-bot could be a good base.

**Comment by jtattermusch** [comment]
Setting up such bot would be useful, but implementing on our own is problematic - such things always need maintenance and we already have too much.

**Comment by AspirinSJL** [comment]
I agree.. Maybe I will do it as a fun project when I have time.

**Comment by nicolasnoble** [comment]
My advice would be to contribute to oss-bot for instance, and then use it.

**Comment by AspirinSJL** [comment]
CC @adelez

**Comment by AspirinSJL** [comment]
We decided to update progress on P0/P1 in person at each standup meeting.
