### ISSUE TITLE
grpc_call.status_error leaked when call_start_batch is called twice with it

### ISSUE THREAD

**Issue by equinox1993** [grpc/grpc#18144]
### What version of gRPC and what language are you using?
 commit 318c67782a752a8324233ff95e594a19f85578a7, C++
 
### What operating system (Linux, Windows,...) and version?
 gLinux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
clang version 9.0.0 (trunk 353250)
Target: x86_64-unknown-linux-gnu
Thread model: posix
 
### What happened?
Our project's clusterfuzz runs the [api_fuzzer test](https://github.com/grpc/grpc/blob/master/test/core/end2end/fuzzers/api_fuzzer.cc) and identified a memory leakage.

Chromium bug: http://crbug.com/934086

LeakSanitizer log:
 
```
=================================================================
--
  | ==2705251==ERROR: LeakSanitizer: detected memory leaks
  | Direct leak of 224 byte(s) in 1 object(s) allocated from:
  | #0 0x56195c92ecef in __interceptor_realloc third_party/llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:164:3
  | #1 0x56195ca90872 in gpr_realloc third_party/grpc/src/src/core/lib/gpr/alloc.cc:83:7
  | #2 0x56195caa0828 in get_placement(grpc_error**, unsigned long) third_party/grpc/src/src/core/lib/iomgr/error.cc:203:37
  | #3 0x56195ca9d9c9 in internal_set_str(grpc_error**, grpc_error_strs, grpc_slice) third_party/grpc/src/src/core/lib/iomgr/error.cc:237:12
  | #4 0x56195ca9eac1 in grpc_error_set_str(grpc_error*, grpc_error_strs, grpc_slice) third_party/grpc/src/src/core/lib/iomgr/error.cc:478:3
  | #5 0x56195cb1d9c8 in call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, int) third_party/grpc/src/src/core/lib/surface/call.cc:1710:17
  | #6 0x56195cb1c32b in grpc_call_start_batch third_party/grpc/src/src/core/lib/surface/call.cc:1912:11
  | #7 0x56195c960b87 in LLVMFuzzerTestOneInput third_party/grpc/src/test/core/end2end/fuzzers/api_fuzzer.cc:1059:35
  | #8 0x56195c9a73ed in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/libFuzzer/src/FuzzerLoop.cpp:529:15
  | #9 0x56195c9728da in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/libFuzzer/src/FuzzerDriver.cpp:286:6
  | #10 0x56195c9784f8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/libFuzzer/src/FuzzerDriver.cpp:715:9
  | #11 0x56195c9c3c3c in main third_party/libFuzzer/src/FuzzerMain.cpp:19:10
  | #12 0x7f193829882f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
  | SUMMARY: AddressSanitizer: 224 byte(s) leaked in 1 allocation(s).
```

Input to reproduce: 
[clusterfuzz-testcase-minimized-grpc_api_fuzzer-direct-leak.txt](https://github.com/grpc/grpc/files/2896206/clusterfuzz-testcase-minimized-grpc_api_fuzzer-direct-leak.txt)
 
### Anything else we should know about your project / environment?

Looks like the fuzzer test for some reason called `grpc_call_start_batch` twice on the same `grpc_call` object, and over there:
https://github.com/grpc/grpc/blob/318c67782a752a8324233ff95e594a19f85578a7/src/core/lib/surface/call.cc#L1716

This code replaces the raw pointer in `call->status_error` without freeing the existing one, which causes the memory leakage. This can be easily fixed by freeing the old status_error if it is set before setting the new one, but there are two more questions I can imagine:
* Why is `grpc_call_start_batch` called twice, and shall we/how to prevent this from happening?
* Why does the fuzzer ever try to call `grpc_call_start_batch` on the same call object twice?

**Comment by vjpai** [comment]
It's funny that you bring this up, as we were just having a discussion about api_fuzzer this morning in our team meeting. api_fuzzer isn't a "real" fuzzing failure in the way that uri_fuzzer or hpack_fuzzer are. These are just cases of api misues (IMO) and nothing can protect against all cases of API misuse. For example, if you pass the same pointer to free twice, the program will crash. So although we protect against some misuses and assert in others, there are hundreds more that we don't even attempt to protect against. As a result, the team is not even of one mind as to whether or not api fuzzing is worth keeping. That's some context, and why this won't likely get high triage priority. Thanks for the PR and we'll review it at some point, but I wouldn't suggest that it will get a prompt reaction.

**Comment by equinox1993** [comment]
Thanks for clarifying this! I've commented this on the Chromium bug and deprioritized it.
