### ISSUE TITLE
C-core API: grpc_metadata::flags is unused

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#18160]
CC @murgatroid99 

The `grpc_metadata` struct has a `flags` field that does not appear to be used.  In addition, the `GRPC_INITIAL_METADATA_*` macros don't have a comment clarifying that they are actually passed in via the `grpc_op::flags` field instead of via the individual metadata elements, which leads to confusion about how the API is supposed to work.

We should eliminate `grpc_metadata::flags` and improve the comment on the `GRPC_INITIAL_METADATA_*` macros.

**Comment by markdroth** [comment]
This is still something we should take care of at some point.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.

**Comment by markdroth** [comment]
This is actually more of an internal cleanup than an enhancement.

**Comment by itsemmanuelfrancis** [comment]
https://github.com/grpc/grpc/pull/26562

**Comment by itsemmanuelfrancis** [comment]
https://github.com/grpc/grpc/pull/26562

This PR should fix this issue
