### ISSUE TITLE
run_tests destroys its cache when interrupted during writing it

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1816]
Either delete the cache when invalid at startup or ensure it's written safely

**Comment by nathanielmanistaatgoogle** [comment]
This smells stale; is the problem reported here still present in today's codebase?

**Comment by ctiller** [comment]
Yeah, this is still broken.
I might just remove the cache.

**Comment by sreecha** [comment]
Cache is deleted. This issue is not relevant anymore
