### ISSUE TITLE
C# code generated with Grpc.Tools nuget package misses Google.Protobuf dependency

### ISSUE THREAD

**Issue by rolfik** [grpc/grpc#18179]
Using gRPC.Tools 1.18 to generate C# code from .proto file in .NET Framework 4.6.2 project ends with compilation error with missing namespace global::Google.Protobuf.
This is due to missing nuget dependency Google.Protobuf - when added manually to the project, compilation succeeds.
Google.Protobuf should be added as dependency into Grpc.Tools nuget.

Developing on Windows 10 1809

**Comment by jtattermusch** [comment]
The problem with your suggesting is that Grpc.Tools is meant to be a build-only dependency (it is only needed for code generation locally in your project, projects depending on project using Grpc.Tools should know nothing about Grpc.Tools being used).

So adding a Google.Protobuf dependency (which should propagate transitively) to Grpc.Tools actually leads to wrong usage pattern.
Also see "PrivateAssets="All" in https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md for details.

We might have a metapackage in the future that will include Grpc + Protobuf as one bundle.
