### ISSUE TITLE
Init methods must return a type related to the receiver type

### ISSUE THREAD

**Issue by puzhiguang** [grpc/grpc#18187]
Convenience initializer missing a 'self' call to another initializer.

- (GRPCUnaryProtoCall *)initPasswordWithMessage:(InitPasswordRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"initPassword"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[GPBEmpty class]];
}

**Comment by RoCry** [comment]
We have met this problem just right now.

**Comment by jandyx** [comment]
Same problem.

**Comment by pinlin168** [comment]
Any luck with this issue?

**Comment by RoCry** [comment]
@lidizheng Do we have any progress on this?

**Comment by lidizheng** [comment]
@rmstar @muxi Can you take a look?

**Comment by muxi** [comment]
I'll take a look into this issue later this week.
