### ISSUE TITLE
Request for a Complete gRPC Python Server Interceptor

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#18191]
As described in [L13-python-interceptors](https://github.com/grpc/proposal/blob/master/L13-python-interceptors.md), the Python server-side interceptor is not complete as other gRPC implementations. With out it, gRPC Python users have to hack their way to achieve common functionality like:

* Server-level exception handler [StackOverflow](https://stackoverflow.com/questions/52608502/how-to-define-a-global-error-handler-in-grpc-python)
* Method-level authentication [StackOverflow](https://stackoverflow.com/questions/54864232/pass-objects-from-server-interceptors-to-functions)
* Access log generation [grpc-io](https://groups.google.com/forum/#!searchin/grpc-io/ross%7Csort:date/grpc-io/RUFgL6VK0jo/KoZMpnQ2AAAJ)

Also, it actually hurt gRPC Python's image, and it is an obstacle for users to adopt gRPC Python server.

**Comment by mehrdada** [comment]
Some historical context: while the server-side interceptor that we shipped may have been hard to use by some users, the original hook provided to substitute service handler on lookup is theoretically sufficient for an external gRPC user to write interceptors by relying only on the public API. The reason we decided to at least temporarily delay a interceptor API at the service handler invocation case is that it's not clear how to deal with `ServicerContext` API (say in the `abort` case) and what return values/exceptions are valid from the `continuation` (some team members at the time objected to adding exception types or making it valid to raise exceptions from service handlers) we would pass during handler execution. So that's something to clearly think about when adding to the core library. By leaving it out from the core design, we kept the flexibility of expanding the API later.

**Comment by lidizheng** [comment]
@mehrdada Thank you for the context, I agree that implement this feature won't be a trivial effort. I found the OpenTracing team have a valid implementation of interceptor depends solely on our public API at [grpcext](https://github.com/opentracing-contrib/python-grpc/blob/master/grpc_opentracing/grpcext/_interceptor.py), though the implementation doesn't solve all the problem you mentioned.

The exception type does seem error-prone, and since the `RPCState` is internal, users have no legit way to tell if an `Exception` is an abort exception or raised from their application. But today, 2 years after GA, maybe it is too late to add a full-fledged set of exception types. A potential workaround can be exposing an `aborted` flag or an `is_aborted` method in servicer context.

**Comment by jceresini** [comment]
Just a note, the access log link in the original post actually links to a gmail search. I believe the link was meant to be to [this google groups thread](https://groups.google.com/forum/#!searchin/grpc-io/ross%7Csort:date/grpc-io/RUFgL6VK0jo/KoZMpnQ2AAAJ)

**Comment by somerska** [comment]
gRPC is touted as officially supporting many languages, Python is on that list.  The reality is that not all languages are equality supported and we're trying to use gRPC with python.

**Comment by lidizheng** [comment]
@somerska May I ask to what extend are you using gRPC Python? gRPC Python client only? gRPC Python server only? Both?

Please feel free to post feature request issue, or bugs.

**Comment by somerska** [comment]
@lidizheng we use CPython 3.7 for both client and server, I'm agreeing that I'd like a complete implementation of the server interceptor in gRPC Python

**Comment by mehrdada** [comment]
@lidizheng I agree, but please feel free to take the opportunity to think carefully about the exception types. Maybe there's some path forward to stabilize without breaking API? Once you fix the handler-invocation-time interceptor design, it'll be harder to change.

**Comment by lidizheng** [comment]
@mehrdada The incremental design and the feature itself, hopefully, will be scheduled as one of the goals in Q2. I personally like the way OpenTracing team does it, though it added another set of APIs.

**Comment by mehrdada** [comment]
@lidizheng I had never been against it, although I don't like too many types to distinguish different things just for better error messages getting printed if they don't make sense from a programmer to take different code paths, but `Abortion` can use its own type maybe, or somehow using the return value of `continuation` can signal success/failure (which would be better). Another question is whether the user should be able to raise the exception or only the gRPC library would be allowed to raise.

**Comment by lidizheng** [comment]
@the-code-robot gRPC has interop tests that testing all combinations of client and server in different languages for every pull request. We ensure that every client and server always interoperable for stable features.

However, interceptors are experimental API that originally contributed by community. It is challenging for contributors to implement this feature in every languages. The support for experimental API isn't the highest priority work right now.

**Comment by snitkoff** [comment]
I use this interceptor as exception handler or for user authentication
` 

    def _wrap_rpc_behavior(handler, fn):

        if handler is None:
            return None

        if handler.request_streaming and handler.response_streaming:
            behavior_fn = handler.stream_stream
            handler_factory = grpc.stream_stream_rpc_method_handler
        elif handler.request_streaming and not handler.response_streaming:
            behavior_fn = handler.stream_unary
            handler_factory = grpc.stream_unary_rpc_method_handler
        elif not handler.request_streaming and handler.response_streaming:
            behavior_fn = handler.unary_stream
            handler_factory = grpc.unary_stream_rpc_method_handler
        else:
            behavior_fn = handler.unary_unary
            handler_factory = grpc.unary_unary_rpc_method_handler
        return handler_factory(fn(behavior_fn,
                                  handler.request_streaming,
                                  handler.response_streaming),
                               request_deserializer=handler.request_deserializer,
                               response_serializer=handler.response_serializer)


    class TracebackLoggerInterceptor(grpc.ServerInterceptor):

        def intercept_service(self, continuation, handler_call_details):
            def latency_wrapper(behavior, request_streaming, response_streaming):

                def new_behavior(request_or_iterator, servicer_context):  

                    # Now you can use this interceptor as exception handler
                    try:
                        return behavior(request_or_iterator, servicer_context)
                    except Exception as err:
                        logger.exception(err, exc_info=True)

                    # Or you can use this interceptor for user authentication
                    ...
                    servicer_context.user = user
                        return behavior(request_or_iterator, servicer_context)

                return new_behavior

            return _wrap_rpc_behavior(continuation(handler_call_details), latency_wrapper)
`

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.

**Comment by antspy** [comment]
Hi, 

I have been trying the solution from @snitkoff (thanks a lot btw!) as I am trying to pass an user to the context. But it does not seem to work. The (limited) type suppor tells me that the line 
`servicer_context.user = user` is probably to blame, as the `servicer_context` class does not allow adding values to the metadata like that. 

Is there another way of doing this?
