### ISSUE TITLE
[Proposal] Async Grpc Croutine based solution using glib ucontext

### ISSUE THREAD

**Issue by yiakwy** [grpc/grpc#18204]
## Background

Currently, the techniques async version gRPC uses is far behind network model implemented in several languages including cpp.

gRPC uses completion queue to notify users when an event is ready, as a result of which we are not real multiplexing even though we have done this in our c core. Actually, in c++ we use `ucontext` to control how, when and where to stop and resume a thread. By utilizing this technique, we can develop an async gRPC server with coroutines and coroutine based threading models.

## Impact on the current progress

Implement callback based asyn gRPC server is meaningless, because:

1) this will cause callbacks hell finally.
2) the main thread cannot move when we are waiting for events. This is not how epoll works at all. 
3) not easy to debug contracted to all croutine based solutions

## Terminology

This proposal will refer to key terminologies used in python (https://github.com/python/cpython/blob/a6fba9b827e395fc9583c07bc2d15cd11f684439/Lib/asyncio/futures.py#L30:7) and cpp `ucontext` library.

#### Event loop

event loop is where we handle linux io events and tigger memory transfer or jumps. It is also the environment to run a coroutine.

``` c++
SimpleEventLoop loop.run_until_complete(croutine);

```
Here is an example of how we control socket event flow

```c++
class Response 
{
public:
std::string method;
std::string url;
sock_t sock;
SimpleEventLoop* loop_;
bool chunked_;
HTTPResponse res_; // we will generate HTTP header mannually and use data from sock as body.

...
void set_contex(Context* ctx) {} // where we resume

void Resume() {
// set context for wake up
}

void _read(size_t CHUNK, std::function<void()> onReadable)
{
Feature* fut = new Future();
Integer fd = sock.fd(); // Linux file descriptor for a connection

// onReadable will call sock to accept data
loop_->selector.register(fd, EVENT_READ, onReadable);
// thread 1, time clock $1
fut->Resume();
// thread 2, time clock $2
loop_->selector.unregister(fd);
return fut->get_ret(); // return chunck of data read by sock in onReadable
}

...

}
```

#### Future

Future is just a promise. It can add done callbacks, error callbacks and so on so forth.

#### Coroutine

> class Crotoutine : public Future;

A programme which we can stop, resume a thread. It records where it stops and waits for io events. Once io events are ready, coroutines read and jump address set by the main thread. A coroutine is conceptually equal to a future instance of type Future

Inside event loop, we do two things

```c++
void run_until_complete(Croto* croto) 
{
// part1:  driven the croto to run and get next future it , for example, in python we will use 
//   Future_Or_Othertype* next_ = croto->send(fut->ret()); 
// to set fut->ret() to the left of the current yield and get the right vaule of the next yield , which is the next future instance or just normal values. 
// If we return from a future, this means we go deep into function stack and we need to know the last future we stop and the next place we stop.
// If we return from an ordinary value of no future types, we can just keep routine running just like in normal function stack. 
// We use loop to extract the `next_fut` or just reach the end of the jumps. Ok, we have next_fut now do it recursively
// cpp cannot check instance type dynmaically and dispatch it. We can explicityly denote it when we write codes by calling `auto ret = fut->Resume()` (<=> yield fut)

// part2:  linux epoll like forever loop without blocking the main thread and check kernel signals.
}

```

Once the coroutine is done , it sets event loop stops status and stop the event loop. 

All operations done in a single thread and can support multiple threading models.
 
Some details could be found in Guido van Rossum 's article "A Web Crawler With asyncio Coroutines". I expanded the codes base to a runable spider with scrapy architecture.

Remember when a call like `onReadable` and set vaule we will call execute callbacks to drive the future running again.

**Comment by vjpai** [comment]
Hi there, I responded to this on https://groups.google.com/forum/#!topic/grpc-io/52PC2DJtCjM . It may be an interesting alternative approach but we're moving forward with a callback API as our official plan of record. We'll keep the community up to date when it's ready to land.
