### ISSUE TITLE
grpc project cannot reference other local project with C#

### ISSUE THREAD

**Issue by maxwelltsai1536** [grpc/grpc#18203]
### What version of gRPC and what language are you using?
 v1.19.0 & csharp
 
### What operating system (Linux, Windows,...) and version?
 windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 C# 7.1 & vs2017
 
### What did you do?
when i reference other project
 
### What did you expect to see?
grpc server start 
 
### What did you see instead?
 then have a typeInitializationException at Grpc.Core.Internal.PlatformApis & TargetInvocationException & SecurityException
 
### Anything else we should know about your project / environment?
the full exception message is 
```
未经处理的异常:  System.TypeInitializationException: “Grpc.Core.Internal.PlatformApis”的类型初始值设定项引发异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Security.SecurityException: ECall 方法必须打包到系统模块中。
   在 UnityEngine.Application.get_platform()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   在 System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   在 System.Reflection.PropertyInfo.GetValue(Object obj)
   在 Grpc.Core.Internal.PlatformApis..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Grpc.Core.Internal.PlatformApis.get_IsXamarinIOS()
   在 Grpc.Core.GrpcEnvironment.get_IsNativeShutdownAllowed()
   在 Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   在 Grpc.Core.GrpcEnvironment..ctor()
   在 Grpc.Core.GrpcEnvironment.AddRef()
   在 Grpc.Core.Server..ctor(IEnumerable`1 options)
   在 Grpc.Core.Server..ctor()
   在 TestConsole.Program.Main(String[] args)
```

**Comment by jtattermusch** [comment]
From the trace it looks like this might be happening:
PlatformApis try to detect on which platform you're on. The test if you're running on Unity
is basically checking if class `UnityEngine.Application` from UnityEngine assembly exists. If so, it is assumed that you're running on unity and other unity specific code runs (and fails because you don't seem to be running on Unity).
https://github.com/grpc/grpc/blob/280c0287a69a7bbad5e91e2bc75956f714eeb258/src/csharp/Grpc.Core/Internal/PlatformApis.cs#L75

Is there a reason why UnityEngine.Application is accessible from your project? (it seems a bit odd).

**Comment by jtattermusch** [comment]
I haven't heard back from the reported so I'm going to close as "not reproducible"

**Comment by maxwelltsai1536** [comment]
Sorry~ reply too late ,my project is web project,so i am surprised, too. any else information do i need provide?

**Comment by jtattermusch** [comment]
see my comment https://github.com/grpc/grpc/issues/18203#issuecomment-469317023 .  Any reason why UnityEngine.Application is available in your project?

**Comment by maxwelltsai1536** [comment]
i found it in qrcode extension,the project url is https://github.com/codebude/QRCoder/

**Comment by jtattermusch** [comment]
Yes, you're right https://github.com/codebude/QRCoder/blob/1be41a1403883687b14eac4fe617ff07043fa192/QRCoder/QRCoder.NETCore20.csproj#L30,

I'm wondering why QRCoder is referencing UnityEngine assembly (which makes gRPC's platformdetector think it's running on unity) but at the same time your project is not a Unity project.

What is the target platform of your project?

**Comment by maxwelltsai1536** [comment]
that is windows.

**Comment by maxwelltsai1536** [comment]
and i think my project references qrcoder third part is normal,how did you think?and do you have any suggestion for this qustion?
