### ISSUE TITLE
Linux SO_REUSEPORT Support

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#18210]
Currently, `manylinux1` is our only supported linux wheel. Since this platform does not support [`SO_REUSEPORT`](https://lwn.net/Articles/542629/), installing from source is currently the only way to leverage this feature on Linux.

[`manylinux2010`](https://www.python.org/dev/peps/pep-0571/) is a revision to the `manylinux` standard that supports `SO_REUSEPORT`. Its PEP was accepted in April, 2018 and it is [undergoing a slow roll-out](https://github.com/pypa/manylinux/issues/179). This platform will also support a newer version of `libstdc++`. However, due to our continued support of `manylinux1`, this does not mean that Core can make greater use of modern C++ features.

`SO_REUSEPORT` is often brought up as a partial answer to multiprocessing in Linux. Until we resolve this issue, we will have to add this caveat.

**Comment by asgoel** [comment]
Any update on this? Seems like the `manylinux2010` spec has progressed nicely (and the newest versions of pip will give it higher priority over `manylinux1`).

**Comment by nicolasnoble** [comment]
We'll gladly accept any pull request on our build scripts and tests to migrate from manylinux1 to manylinux2010.

**Comment by hungrybirder** [comment]
Any progress on this?
`pip install grpcio --no-binary grpcio`
can enable tcp reuseport, but it should be the default behavior.

**Comment by lidizheng** [comment]
@asgoel @hungrybirder SO_REUSEPORT support should be shipped by default now. We are shipping `manylinux2010` and 3.8 in latest `v1.24.3`. If the pip version is `> 19.0`, then it will automatically pick the `manylinux2010` wheel.

**Comment by gnossen** [comment]
I don't think we can declare victory quite yet. Manylinux2010 supports it, but we still have to include it in our wheel. I've manually verified that this is not yet working:

```python
    ...
    options = (('gprc.so_reuseport', 1),)
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10), options=options)
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    server.wait_for_termination()
    ...
```

```
(venv) rbellevi@rbell:~/Dev/grpc/examples/python/helloworld$ python greeter_server.py 
^Z
[2]+  Stopped                 python greeter_server.py
(venv) rbellevi@rbell:~/Dev/grpc/examples/python/helloworld$ bg
[2]+ python greeter_server.py &
(venv) rbellevi@rbell:~/Dev/grpc/examples/python/helloworld$ python greeter_server.py 
E1023 10:45:13.944153692  214436 server_chttp2.cc:40]        {"created":"@1571852713.944117818","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1571852713.944114057","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":341,"referenced_errors":[{"created":"@1571852713.944101726","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1571852713.944099048","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1571852713.944113306","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1571852713.944111096","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
```
This is probably going to require some changes to [`port_platform.h`](https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/include/grpc/impl/codegen/port_platform.h).

**Comment by hungrybirder** [comment]
> @asgoel @hungrybirder SO_REUSEPORT support should be shipped by default now. We are shipping `manylinux2010` and 3.8 in latest `v1.24.3`. If the pip version is `> 19.0`, then it will automatically pick the `manylinux2010` wheel.

I test it on centos7 and it still doesn't work for me.
`grpcio==1.24.3
pip 19.3.1
`

**Comment by Sayed-Soroush-Hashemi** [comment]
@gnossen 
Do we have a timeline for this? Installing `grpcio` with `--no-binary` flag requires compiling it, which takes too long.

**Comment by danjenson** [comment]
I am using Fedora 29, python 3.74, pip 19.3.1, grpcio 1.25.0, and examples/python/multiprocessing/server.py and while the socket binds and has the SO_REUSEADDR property, as soon as `server.add_insecure_port(...)` is called, I get the following for each process:

``` 
E1128 13:14:19.214173125   22940 server_chttp2.cc:40]        {"created":"@1574968459.214073830","description":"No address added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1574968459.214035945","description":"Unable to configure socket","fd":9,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":208,"referenced_errors":[{"created":"@1574968459.214019723","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1574968459.214068908","description":"Unable to configure socket","fd":9,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":208,"referenced_errors":[{"created":"@1574968459.214063443","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]}]}
```

**Comment by WenqianZhao** [comment]
> I am using Fedora 29, python 3.74, pip 19.3.1, grpcio 1.25.0, and examples/python/multiprocessing/server.py and while the socket binds and has the SO_REUSEPORT property, as soon as `server.add_insecure_port(...)` is called, I get the following for each process:
> 
> ```
> E1128 13:14:19.214173125   22940 server_chttp2.cc:40]        {"created":"@1574968459.214073830","description":"No address added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1574968459.214035945","description":"Unable to configure socket","fd":9,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":208,"referenced_errors":[{"created":"@1574968459.214019723","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1574968459.214068908","description":"Unable to configure socket","fd":9,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":208,"referenced_errors":[{"created":"@1574968459.214063443","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]}]}
> ```
> 
> Seems like `options=(('grpc.so_reuseport', 1),)` is not working. I also ran `pip install grpcio --no-binary grpcio`, but it says requirement already satisfied [UPDATE: uninstalling and re-installing with that command worked].

you can uninstall it first and then run `pip install grpcio --no-binary grpcio`, that works for me.

**Comment by srajagopalan-fliptrx** [comment]
I am running the multiprocessing example , but on the server logs, I see that same process id is being printed. This means that different processes are not being used ?

**Comment by gnossen** [comment]
@srajagopalan-fliptrx That would make sense if you're running on a single core machine. Regardless, I think that's a separate from this issue. Would you create a new issue with more detail?

**Comment by yzhao-2023** [comment]
The example does not work https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing
