### ISSUE TITLE
Code generation via msbuild does not handle `import "google/api/annotations.proto";` 

### ISSUE THREAD

**Issue by mrt181** [grpc/grpc#18214]
### What version of gRPC and what language are you using?
gRPC: v1.19.0
lang: C#
 
 
### What operating system (Linux, Windows,...) and version?
 Windows 7 64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .net Standard 2.0
 
### What did you do?
I have gRPC service definitions which use this

`import "google/api/annotations.proto";`

I try to autogenerate the code via msbuild

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>api.service</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" Version="1.5.0" />
    <PackageReference Include="Google.Protobuf" Version="3.6.1" />
    <PackageReference Include="Grpc" Version="1.19.0" />
    <PackageReference Include="Grpc.Tools" Version="1.19.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../proto/api/**/*.proto" Exclude="../../proto/api/**/*_service.proto" ProtoRoot="../../proto" OutputDir="api-csharp/api-csharp/%(RelativeDir)" CompileOutputs="true" GrpcServices="None" />
    <Protobuf Include="../../proto/api/**/*_service.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\" />
  </ItemGroup>

</Project>
```
 
### What did you expect to see?
 generated server and client stubs
 
### What did you see instead?
```
1>------ Rebuild All started: Project: Api.Service, Configuration: Debug Any CPU ------
1>google/api/annotations.proto: File not found.
1>api/trading/v1/data_service.proto: Import "google/api/annotations.proto" was not found or had errors.
1>C:\Users\r892107\.nuget\packages\grpc.tools\1.19.0\build\_protobuf\Google.Protobuf.Tools.targets(263,5): error MSB6006: "C:\Users\r892107\.nuget\packages\grpc.tools\1.19.0\tools\windows_x64\protoc.exe" exited with code 1.
1>Done building project "Api.Service.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by jasons-codes** [comment]
I got same error at 1.19.0

**Comment by jtattermusch** [comment]
`google/api/annotations.proto` is not a well-known .proto file (as opposed to e.g. google.protobuf.Any and other types that are distributed along with protobuf runtime and the Grpc.Tools pacakge) and therefore you actually need to add a copy google/api/annotations.proto to your project in order to be able to build. The file needs to be under "google/api" directory (so that the import path matches).

Here's the .proto file:
https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto

**Comment by mrt181** [comment]
Yes I figured out that I could manually add that file but hoped that `Google.Api.CommonProtos` might be supported directly as those annotations are used in the gRPC service rpc definitions

**Comment by jtattermusch** [comment]
Sure, but unlike the well-known protos provided by the protobuf team, the google.api protos aren't really general purpose so it makes no sense to have built-in support in Grpc.Tools package - there are many other use cases of protobuf than for Google APIs.
