### ISSUE TITLE
protobuf removal from grpc++

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#1821]
The C++ layer currently depends too much on protobuf. We need to be able to support other marshalling APIs, and first get rid of the hard dependency on protobuf.

**Comment by ctiller** [comment]
Started some refactoring to get to this.

**Comment by ctiller** [comment]
It's likely worth splitting protobuf entirely out of grpc++.a, but I think this can occur post-beta.

**Comment by sreecha** [comment]
Can this be closed ?

**Comment by yang-g** [comment]
Yes.
