### ISSUE TITLE
How to proactive close writer-reader stream on server side (C++)

### ISSUE THREAD

**Issue by fy2462** [grpc/grpc#18227]
Hi，everyone：

Who knows how to proactive close writer-reader stream from server side using C++ code？

I want to only keep one writer-reader stream in server side, so I need to close the old stream when found a new stream send message to server. But I found that I can not release the old stream->Read(message) because of hang when the old client is connecting to server.

anyone help me ?
thanks all of them very very much.

**Comment by yashykt** [comment]
it looks like you want to close the RPC from the server side. TryCancel() on the ServerContext might be what you are looking for.
