### ISSUE TITLE
I need to share CompletionQueue across multiple connections instead of exclusive it?

### ISSUE THREAD

**Issue by qtcdxxyuc** [grpc/grpc#18232]
### What version of gRPC and what language are you using?

`grpc 1.16.1` `c++`

### What operating system (Linux, Windows,...) and version?

`Ubuntu 18.04LTS`

### What runtime / compiler are you using ?

`gcc version 7.3.0`

### What did you do?
In async-grpc server,I tried to create an exclusive `context` and `CompletionQueue` for each connection.I create exclusive context and cq when a connection comes in, and destruct them at the end of the connection.This works well, but there is an efficiency problem.`CompletionQueue` is created very slowly.

> benchmark.cpp
>

```c++
BENCHMARK(CompletionQueue){
    grpc::CompletionQueue cq;
}

BENCHMARK(ClientContext){
    grpc::ClientContext cc;
}

BENCHMARK(ServerContext){
    grpc::ServerContext sc;
}

BENCHMARK(std_queue){
    std::queue<int> cq;
}

TEST(benchmark,base){
    folly::runBenchmarks();
}
```

> computer INFO

```c++
cpu: i5-7400 @ 3.00GHZ
RAM: 8GB
```

> result(release)

```c++
============================================================================
benchmark.cpp                                   relative  time/iter  iters/s
============================================================================
CompletionQueue                                             65.27us   15.32K
ClientContext                                               29.31ns   34.12M
ServerContext                                               46.70ns   21.42M
std_queue                                                   20.33ns   49.18M
============================================================================
```

I use folly's `banchmark` for testing.The construction speed of `CompletionQueue` is `15.32K/s`.

### What did you expect to see?

The construction speed of `CompletionQueue` is limited.Does this mean that I need to share `CompletionQueue` across multiple connections instead of exclusive it?

### What did you see instead?

No more.

### Anything else we should know about your project / environment?

No more.

**Comment by jtattermusch** [comment]
You can definitely use a single completion queue for multiple connections (both on client side and the server side). Completions queues used with async C++ API are supposed to be long-lived - lost of applications you should just create completions queues (in a thread pool) when they start and destroy them when they shut down.
