### ISSUE TITLE
GET method is mentioned in interop test, but not in the spec

### ISSUE THREAD

**Issue by stepancheg** [grpc/grpc#18230]
[cacheable_unary test](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#cacheable_unary) says: "test verifies that gRPC requests marked as cacheable use GET verb instead of POST".

However [gRPC over HTTP2](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) document does not mention GET method.

**Comment by lidizheng** [comment]
@stepancheg Sorry for the late reply. Cacheable is an experimental feature (see [code](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L454)), that currently only C++ implemented. And it is not tested on regular basis based on the [interop matrix](https://github.com/grpc/grpc/blob/dd5f0fcf48e503d285ea76f3d1d2459c94f62727/tools/interop_matrix/testcases/cxx__master). I don't have full context about these feature, maybe it is used internally.

Then about the GET or POST HTTP method. By default, gRPC is running on **POST**, it is specified in the [Requests](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) section of gRPC over HTTP2. The GET method means getting cached response which has different semantic than POST.

If you have further questions, feel free to reopen the issue.
