### ISSUE TITLE
C#: Add ServerCallContext.StatusChanged event to allow Status monitoring

### ISSUE THREAD

**Issue by rolfik** [grpc/grpc#18233]
It would be usefull to add StatusChanged event to ServerCallContext to allow Status monitoring.
It will complement single case only available now: ServerCallContext.CancellationToken.Register.

During server streaming to clients, this would allow to better clear unusable server call contexts of disconnected clients.

Thank you

Marek

**Comment by jtattermusch** [comment]
not sure what you mean by "status monitoring", but it looks like you should just use ServerCallContext.CancellationToken to get the signal you need. On the server side, this signals that the call was interrupted with an error (client cancelled, connections lost, ..) and that's all the information you can get. The status is only sent from the server to the client, so there's no way of providing more details about the nature of an error (and it's probably also not very useful for the server to know).

**Comment by rolfik** [comment]
Actually I am testing gRPC server streaming to clients.

Clients connect to server via rpc call getting server stream of notifications.
Server notifies connected clients.
I have found that some response streams used by the server may become unusable during client restarts etc. even though I discard response streams when the ServerCallContext.CancellationToken signals its cancellation...

How to detect client disconnection in such server streaming calls?
How to detect server disconnection in such server stream consumptions by clients?

**Comment by jtattermusch** [comment]
when a TCP/IP connection breaks, it necessarily makes the RPC fail (and you might want to setup RPC keepalive intervals or just send heartbeat messages yourself).
- on the serverside, the serverCallContext.CancellationToken will be triggered.
- on client side, you'll see the call end with an error status. If that's what you see, just start a new RPC on the client.

**Comment by rolfik** [comment]
@jtattermusch Thank you for the comments.

I have isolated my gRPC testing into separate solution:
https://github.com/rolfik/gRPC.Test

The problem I had was caused in my Monitor method server implementation returning just after registering a calling client internally and later notifications were written by server to the provided response streams - at that time, those streams were not usable anymore.
See that implementation at:
https://github.com/rolfik/gRPC.Test/tree/452205410718b733f4404300223f9d0210fc96ad

After adding helper ServerStreamingCall wrapper to wrap client calls on server and returning uncompleted ServerStreamingCall.Task from server Monitor method, all started to work as expected:
- after closing clients, server receives cancellation via ServerCallContext.CancellationToken
- after restarting server, clients reconnect after failures via new Monitor server calls

Now I wonder how to do your suggestions in the gRPC C# framework:

> when a TCP/IP connection breaks, it necessarily makes the RPC fail (and you might want to setup RPC keepalive intervals or just send heartbeat messages yourself).

When server notifies clients via response streams about changes occasionally, will the connection be kept alive by the framework like in WCF, or will it break after some idle time?
What are the gRPC settings regarding this.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/56006f0c532fd98a2b327852c763778279616e01/doc/keepalive.md

all these options can be used from C# via ChannelOptions.
