### ISSUE TITLE
Inconsistent behavior of RECV_STATUS_ON_CLIENT  and  RECV_MESSAGE  operation when a call gets cancelled

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#18234]
This is the root cause of https://github.com/grpc/grpc/issues/17761 (which can happen in other languages than C# as well).

The scenario:
1 .client starts server streaming call and the server responds to the call "quickly" by sending a small response and the call status. Both get immediately sent on the wire and they are also received on the client side.
2. client requests a "late" call cancellation, but in the meantime the response message and OK status have already been received from the server (which can happen in practice, there's always an inherent "race" between client requesting cancellation and the server sending responses).
3. The pending RECV_STATUS_ON_CLIENT operation returns an OK status because that's what was received on the wire.
4. an operation RECV_MESSAGE on the client side will return success==false, and won't return the received message (but we know that internally, the message was read just fine, because we were able to read the OK status coming right after it).

The problem is the inconsistency between behavior or RECV_STATUS_ON_CLIENT  and RECV_MESSAGE.  The received status is reported as OK, but the received message is thrown away at the same time.

Proposed behavior (both are fine)
option 1: the call reports an error status and the response message is thrown away 
option 2: the call reports OK status and the cached message is returned normally (it must have been cached because we were able to read the OK status).

The current behavior is something in-between and it is hard to come up with reasonable wrapping logic to make things behave as expected in the C# layer without reimplementing a lot of C core logic (which we definitely don't want).

**Comment by jtattermusch** [comment]
@AspirinSJL  can you take a look?

**Comment by jtattermusch** [comment]
My repro and unsuccessful attempts to fix in the C# layer are here https://github.com/grpc/grpc/pull/18124

**Comment by AspirinSJL** [comment]
The received message is thrown away because the client has cancelled the call, right?

Looks like the problem is due to the different sources to determine the results of RECV_STATUS_ON_CLIENT and RECV_MESSAGE. 

I think option 1 is more reasonable. We should overwrite the status to "cancelled" in this case because that reflects the user's intent. 

I will try to fix this early this week.

**Comment by jtattermusch** [comment]
The problem with option 1 is that the RECV_STATUS_ON_CLIENT operation is always pending since the start of a server streaming call, so it could happen that the OK status being returned by the surface API wil race with client trying to request cancellation.

Option 2 would be some something along "we know that we already reported the call's status as OK, so we should not throw away the received message despite the users' attempt to cancel - because the call has in fact already finished."

**Comment by AspirinSJL** [comment]
After looking at the the existing `End2endTest.ClientCancelsResponseStream` and modifying it to show the expected behavior, I feel that a successful read in this case doesn't necessarily mean that we should always return an OK status. It just happens in the example of this issue that the server returns OK quickly. But it's reasonable to return a CANCELLED after a read generally. 

If the read fails, we must return CANCELLED though.

What do you think?

**Comment by jtattermusch** [comment]
Update: I had a chat with @AspirinSJL offline and @AspirinSJL  will try to fix the behavior on the C-core side.

**Comment by jtattermusch** [comment]
This is still an issue.

**Comment by yashykt** [comment]
@AspirinSJL Do you have a working C++ repro that I might be able to reuse?

**Comment by AspirinSJL** [comment]
https://github.com/grpc/grpc/pull/18328 attempts to repro and fix this issue. But looks like most of the tests are passing...

**Comment by yashykt** [comment]
@jtattermusch Can you please verify that this issue still exists. I remember dealing with similar issues in the past and I just recalled that I have a PR - 
https://github.com/grpc/grpc/pull/19545 which deals with a similar issue

**Comment by jtattermusch** [comment]
I tried the repro from https://github.com/grpc/grpc/pull/18124 and after rebasing the PR, and the repro is still failing on the current master. I haven't tested it against your PR yet (I can do so).

**Comment by jtattermusch** [comment]
This is still an issue.

**Comment by tonydnewell** [comment]
I've verified this was fixed. I've added a test to the C# code
https://github.com/grpc/grpc/pull/30523

**Comment by jtattermusch** [comment]
> #19545

Do we know which PR/commit has fixed the problem? Was it perhaps https://github.com/grpc/grpc/pull/19545. I'd like to see a proof that the reproduction reproduced the problem just before a given change and we we could not reproduce anymore just after that change. Without that, we can't be really sure that this was really fixed.

**Comment by yashykt** [comment]
Yeah, #19545 fixed it iirc (it's been a few years and I forgot to close this). I added tests for this in the PR itself.
