### ISSUE TITLE
Proxy authentication via digest does not work

### ISSUE THREAD

**Issue by jmeinke** [grpc/grpc#18250]
### What version of gRPC and what language are you using?
In our electron app, we're using firebase/firestore@1.0.1 from firebase-js which uses grpc-node 1.17 which uses grpc 1.17.

### What operating system (Linux, Windows,...) and version?
Windows 10, Electron 3.0.15 (32 bit)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
We're using the prebuilt binaries which are released with grpc-node here: https://github.com/grpc/grpc-node/releases
 
### What did you do?
We're setting the proxy and auth credentials in corporate environment via the **https_proxy env variable**. Then we try to connect to our Firestore instance. GRPC correctly picks up the https_proxy variable and tries to set up a HTTPS TUNNEL on the proxy in order to connect to firestore.googleapis.com:443.
 
### What did you expect to see?
We would expect that the connection is established successfully.
 
### What did you see instead?
Instead, we get a proxy authentication error 407 and on the squid/access.log we get the following:
```
1551795481.599      0 127.0.0.1 TCP_DENIED/407 4085 CONNECT firestore.googleapis.com:443 - HIER_NONE/- text/html
2019/03/05 15:49:20 kid1| WARNING: Unsupported or unconfigured/inactive proxy-auth scheme, 'Basic **********************'
```
 
Squid expects proxy authentication via digest. grpc however tries to authenticate via HTTP Basic auth.

**Comment by nicolasnoble** [comment]
We don't support anything but Basic authentication scheme at the moment.

**Comment by jmeinke** [comment]
Okay, I hope it can be implemented in the future. Also see this related post: https://stackoverflow.com/questions/52441316/firestore-grpc-behind-a-corporate-firewall-proxy

**Comment by serverhorror** [comment]
I’m dealing with the same problem

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.
