### ISSUE TITLE
Issues reconnecting with expired SSL certs

### ISSUE THREAD

**Issue by smaye81** [grpc/grpc#18257]
### What version of gRPC and what language are you using?
 v1.15.0, C++
 
### What operating system (Linux, Windows,...) and version?
 Linux Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang 3.8
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I am connecting to a grpc server via a C++ client using `grpc::CreateCustomChannel` and passing in my credentials.  The connection works fine initially, but issues abound if the certs expire and then the connection drops.
 
### What did you expect to see?
I would expect the grpc connection semantics to reconnect but obviously this won't work if the certs are expired since the connection logic will use the initial certs.
 
 
### What did you see instead?
Errors such as:

```
gRPC-Log: Handshake failed with fatal error SSL_ERROR_SSL: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired.
Connect failed: {"created":"@1551719461.917496408","description":"Handshake failed","file":"external/com_github_grpc_grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
 
```

What is the easiest way to reconnect when certs expire?  Also related, what is the easiest way to tell when certs expire?  There doesn't seem to be any intuitive way to catch channel connection errors.

**Comment by jiangtaoli2016** [comment]
gRPC code does **not** manage certificates. It is up to caller to monitor the life-cycle of certificate (and restart gRPC binary if needed when certificate expires).
gRPC security API does provide credential reloading capability
https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L406
With credential reloading, it is possible to reload a new certificate without re-starting your binary.

**Comment by smaye81** [comment]
What is the difference between that file and `https://github.com/grpc/grpc/blob/master/include/grpcpp/security/credentials.h`?  We are using the `CreateCustomChannel` from the latter to establish our channel.  How would I create a custom channel using your typedef above?  Is it documented anywhere?

**Comment by jiangtaoli2016** [comment]
@smaye81 We only plumb through this API for python [dynamic_ssl_server_credentials](https://grpc.io/grpc/python/grpc.html).
By the way, this certificate reloading feature is only available on server side.

**Comment by jiangtaoli2016** [comment]
assign back to @srini100 for possible plumb this credential reloading API to c++.

By the way, we have gRPC [SPIFFE credential](https://github.com/grpc/grpc/pull/16614) @yihuazhang  is implementation. It has full credential reloading capability on both client and server side. Again, the work is still at c core level. It will take time to plumb into wrapped languages (C++, python, etc.)

**Comment by smaye81** [comment]
That would be good.  I need it on the client side.  Looking forward to this.  Let me know if I can help in any way to expedite the process.
