### ISSUE TITLE
Ruby interop matrix docker image build fails

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#18262]
Since 1.18.0 release we get this error while building interop docker image locally:

Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.9)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.9)' in any of the relevant sources:
  the local ruby installation
FAILED: build_docker_ruby [ret=6, pid=245194, time=653.4sec]
FAILED: Failed to build interop docker images.

This does't get resolved even after cleaning the cache completely.

**Comment by srini100** [comment]
@apolcyn, can you please try building the images for 1.19.0 and 1.20.0 and upload if it works? We are falling behind on Ruby interop. Bumping this to release blocker so this is fixed before next release.

**Comment by apolcyn** [comment]
ack. I ran into problems building the images myself earlier, looking into it today.

**Comment by apolcyn** [comment]
Ruby 1.19.0 and 1.20.0 images just uploaded to GCR. I'm unfortunately not sure where the error was coming from, in the original post here.

**Comment by srini100** [comment]
Doing `docker pull debian:jessie` resolved this issue.
