### ISSUE TITLE
PHP interop matrix test failure in 1.19.0

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#18264]
To repro the failure, add 1.19.0 to tools/interop_matrix/client_matrix.py and run "tools/interop_matrix/run_interop_matrix_tests.py -l php --release v1.19.0". Seeing this error:
$ tools/interop_matrix/run_interop_matrix_tests.py -l php --release v1.19.0
START: Downloading images for language "php"
PASSED: pull_image_gcr.io/grpc-testing/grpc_interop_php:v1.19.0 [time=37.8sec, retries=0:0]
SUCCESS: All images downloaded successfully.
PASSED: php__php_v1.19.0:php:grpc-test:timeout_on_sleeping_server [time=1.3sec, retries=0:0]

Running test case ping_pong
Server returned too few responses
FAILED: php__php_v1.19.0:php:grpc-test:ping_pong [ret=1, pid=193874, time=17.1sec]

Running test case large_unary
Call did not complete successfully. Status object:
object(stdClass)#390 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(14)
  ["details"]=>
  string(14) "Connect Failed"
}
FAILED: php__php_v1.19.0:php:grpc-test:large_unary [ret=1, pid=193862, time=17.1sec]

**Comment by stanley-cheung** [comment]
Collecting a bunch of data first:

1. From `master`, `./tools/interop_matrix/run_interop_matrix_tests.py -l php --release v1.19.0` FAILED

2. From `master`, `./tools/interop_matrix/run_interop_matrix_tests.py -l php --release v1.18.0` PASSED

3. From `v1.19.x`, `./tools/run_tests/run_interop_tests.py -l php -s c++ --use_docker -t -j 8` PASSED

4. From `v1.19.x`, `./tools/run_tests/run_interop_tests.py -l php7 -s c++ --use_docker -t -j 8` PASSED

5. From `v1.19.x`, `./tools/run_tests/run_interop_tests.py -l php7 --cloud_to_prod --use_docker -t -j 8` PASSED

6. From `v1.19.x`, `./tools/run_tests/run_interop_tests.py -l php --cloud_to_prod --use_docker -t -j 8` PASSED

7. There's no material difference between `v1.18.x` and `v1.19.x` for PHP `git diff upstream/v1.18.x:src/php upstream/v1.19.x:src/php`

Now I wonder what's so special about `run_interop_matrix_tests.py` and `v1.19.0`

**Comment by srini100** [comment]
1.20.0 is getting close. Any update on this?

**Comment by stanley-cheung** [comment]
The plot thickens.

As mentioned from the original post, running the main script `./tools/interop_matrix/run_interop_matrix_tests.py -l php --release v1.19.0` failed. So I try to dissect the script to see what's going on.

I realized I can add a `--keep` flag to keep the docker images, so `./tools/interop_matrix/run_interop_matrix_tests.py --keep -l php --release v1.19.0`. And I got a couple of pulled docker images like `gcr.io/grpc-testing/grpc_interop_php7:v1.19.0`.

Next, by looking at `run_interop_matrix_tests.py`, I noticed that it's reading from the `testcases` directory, basically this file: `tools/interop_matrix/testcases/php__master`. Inside that file, there's a bunch of `docker run` statements like this:

```
docker run -i --rm=true -w /var/local/git/grpc --net=host $docker_image bash -c "src/php/bin/interop_client.sh --server_host=grpc-test.sandbox.googleapis.com --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=large_unary" 
```

So I tried to replace `$docker_image` with the docker image ID of the pulled `gcr.io/grpc-testing/grpc_interop_php7:v1.19.0` image, and just run the `docker run` command above, locally, and it passed!!

As far as I can tell, running the main script `run_interop_matrix_tests.py` and running the `docker run` command above is exactly the same. Both are running against the "published" docker image `gcr.io/grpc-testing/grpc_interop_php7:v1.19.0`. But the former failed while the latter passed.

**Comment by srini100** [comment]
@stanley-cheung, any progress on this. 1.20.0 is out and we don't have php interop since 1.19.0. I am bumping this to release blocker so this is prioritized before next release.

**Comment by jtattermusch** [comment]
@stanley-cheung  and I investigated this today more in depth and found this:
- c-ares seems to have become a the default resolver in v1.19.0
- with c-ares resolver, if secure channel target is specified only as an IP address (`74.125.206.210` in our case), the port doesn't default to `443` (as before with the native resolver), but it defaults to `0` instead, which breaks the PHP interop tests when the cmdline options are `--server_host=74.125.206.210 --server_host_override=grpc-test.sandbox.googleapis.com` (because it then tries to connect to port 0, which makes no sense)

Also see https://github.com/grpc/grpc/blob/044a8e29df4c5c2716c7e8250c6b2585e1c425ff/src/php/tests/interop/interop_client.php#L533 (this is something that's currently required for php for the jwt_token_creds interop test to work)

**Comment by stanley-cheung** [comment]
We are going to backport #19230 to the `v1.21.x` branch, and then try #19228 (to add say `v1.21.4` to the interop_matrix) again.

**Comment by stanley-cheung** [comment]
This is **finally** fixed! This command is now finally passing:

`~/grpc$ ./tools/interop_matrix/run_interop_matrix_tests.py -l php --release v1.21.4-pre1`

Will properly tag the `v1.21.4` release for this soon. Then we can update #19228 and add PHP back to the interop matrix.

Thanks @jtattermusch for helping me debug and get to the bottom of this.

**Comment by srini100** [comment]
@stanley-cheung,  local PHP interop test is passing with this change. I have uploaded the 1.21.4 PHP image.
