### ISSUE TITLE
Cmake installation doesn't generate .so files (dynamic libraries)

### ISSUE THREAD

**Issue by Azure7sky** [grpc/grpc#18271]
### What version of gRPC and what language are you using?
git Version: v1.12.1,  C++
 
### What operating system (Linux, Windows,...) and version?
 ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc version 5.4.0
 
### What did you do?
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init --recursive
cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DCMAKE_BUILD_TYPE=Release .
make 
make install

 
 
### What did you expect to see?
 I want to install gRPC via cmake first and link its dynamic library to my existing c++ project. 
 
### What did you see instead?
 
Now I can locate it with find_package(gRPC CONFIG),  but the problem is that grpc doesn't generate .so files(dynamic libraries) and it only creates .a (static libraries)files. When I look into the grpc folder after cmake installation, it doesn't generate libs and objs folders under /grpc .

### Anything else we should know about your project / environment?
protobuf, zilb, ssl and c-ares are already installed on my machine.

**Comment by Azure7sky** [comment]
when I change the cmake command to be "cmake -DCMAKE_BUILD_TYPE=Release .", it will generate .so  files, however this time the find_package( gRPC REQUIRED ) failed because gRPCConfig.cmake is not generated. So how to succeed find_package( gRPC REQUIRED ) and generate .so files at the same time?

**Comment by didibaba** [comment]
I got the same questions.

**Comment by KyleFromKitware** [comment]
I built this with the same command as you but added a `-DBUILD_SHARED_LIBS=ON` argument to the initial `cmake` invocation. This generated .so files as well as `gRPCConfig.cmake`.
