### ISSUE TITLE
gRPC and openssl ENGINE support

### ISSUE THREAD

**Issue by akshayku** [grpc/grpc#18293]
### What version of gRPC and what language are you using?
 Latest. 1.19.0.
Languages: C++, C#, Java, Go
 
### What operating system (Linux, Windows,...) and version?
 Linux, Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
 
### What did you do?
gRPC don't support ENGINES as exposed by openssl. Specifically, `ssl_ctx_use_private_key` in gRPC function don't support engines. It directly calls `SSL_CTX_use_PrivateKey`. 

As a comparison, NGINX allows usage of openssl ENGINE and use `ENGINE_by_id`/`ENGINE_load_private_key` functions to load the key and then use it in `SSL_CTX_use_PrivateKey`. See `ngx_ssl_load_certificate_key` at https://github.com/nginx/nginx/blob/0808b04c4690354aab43e0cdfe49588abb942e8c/src/event/ngx_event_openssl.c 
 
### What did you expect to see?
 Wanted to use ENGINES in openssl via gRPC. 
 
### What did you see instead?
 Only in memory keys are allowed.

**Comment by jtattermusch** [comment]
CC @ejona86  @markdroth  @jiangtaoli2016  @dfawley @hsaliak  @a11r

**Comment by dfawley** [comment]
@akshayku for Go, there is no "official" OpenSSL library, so we most likely will not provide first-party support for it.  However, I did find a wrapper [here](https://github.com/spacemonkeygo/openssl) that could be used.

In gRPC-Go, support in our library for OpenSSL (or any other transport security) is not required for you to be able to use it. Transport security is very flexible - you would need to create a type that implements [credentials.TransportCredentials](https://godoc.org/google.golang.org/grpc/credentials#TransportCredentials) and pass that to your clients and servers using [grpc.WithTransportCreds](https://godoc.org/google.golang.org/grpc#WithTransportCredentials) and [grpc.Creds](https://godoc.org/google.golang.org/grpc#Creds).  The client and server handshakers are passed the raw network connection and give back a `net.Conn` whose `Read` and `Write` methods are overridden to decrypt/encrypt as appropriate around those operations on the underlying connection.  Please let us know if you have any questions or concerns or if you run into any problems with implementation.

**Comment by akshayku** [comment]
@dfawley, Can you clarify few things for me to understand it better?

- Which language projections of gRPC uses OpenSSL?
- What do you mean by no "official" OpenSSL library? If there is none, which one gRPC uses? 
- What issues do you see supporting ENGINE (only for places where you call openSSL)? 
  - If any projection is not calling openSSL, we are not asking for its support. 
  - We are just asking to expose one supported configuration in openSSL to be also available through gRPC.
- How is your "credentials.TransportCredentials" reference different from "MetadataCredentialsPlugin" class? Are there any examples of "TransportCredentials" that I can fork in the source code?

**Comment by dfawley** [comment]
> Which language projections of gRPC uses OpenSSL?

I think only Go and possibly some wrapped languages do not use OpenSSL.

> What do you mean by no "official" OpenSSL library? If there is none, which one gRPC uses?

gRPC-Go does not have any integration with OpenSSL.  However, it should be possible to use 
OpenSSL with gRPC-Go by implementing `credentials.TransportCredentials`.  I believe the fastest way to get this working would be to use an existing OpenSSL CGo wrapper library like the one linked above.

> What issues do you see supporting ENGINE (only for places where you call openSSL)?

I'll leave this for the C/C++ & Java experts to answer.

> How is your "credentials.TransportCredentials" reference different from "MetadataCredentialsPlugin" class? Are there any examples of "TransportCredentials" that I can fork in the source code?

Sorry, I am not familiar with `MetadataCredentialsPlugin` to compare them.  We have an implementation of `TransportCredentials` in the grpc-go repo for TLS that you could use as a reference:

https://github.com/grpc/grpc-go/blob/495133b619416f2b99dacb9b23d4da53a0f54d10/credentials/credentials.go#L155:6

**Comment by akshayku** [comment]
Thanks @dfawley for the clarification. Can you also tag C/C++ owners as that work is needed urgently for us? I can provide the patch, test it on my end to make this work.

I will also look at your suggestion of transportCredentials once I am done with supporting ENGINE natively with C/C++.

**Comment by markdroth** [comment]
I think @jiangtaoli2016 is the right person to address this for C/C++.

**Comment by akshayku** [comment]
@jiangtaoli2016, Can you suggest how best we can fix this??

**Comment by jiangtaoli2016** [comment]
@akshayku Is that possible to have a **prototype** from Microsoft to see how ENGINE works on gRPC c core? Then @markdroth and I can decide how to change grpc security API to support this feature.

**Comment by akshayku** [comment]
Sure. I will provide something next week. Thanks for the reply.

**Comment by wdullaer** [comment]
Has any progress been made on this issue?

**Comment by akshayku** [comment]
Sorry for the delay. We were planning to propose a PR where we can outline our thinking.. Hoping to get back to you soon.

**Comment by wdullaer** [comment]
Activity: we are still interested in this feature being implemented and there are outstanding PRs that address it.
