### ISSUE TITLE
Add armv7 support for Xamarin.iOS to libgrpc_csharp_ext.a

### ISSUE THREAD

**Issue by tylersouthard** [grpc/grpc#18294]
### What version of gRPC and what language are you using?
 1.19.0, C# (Xamarin.iOS)
 
### What operating system (Linux, Windows,...) and version?
 macOS 10.14.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Xamarin.iOS toolchain (msbuild)
 
### What did you do?
Attempt to build a Xamarin.iOS project referencing the Grpc.Core nuget for armv7 + arm64.
 
### What did you expect to see?
(I didn't expect it to work, but it would be nice if it did.)
 
### What did you see instead?
No symbols for _grpcsharp* found for armv7.

Is this just a matter of adding two lines to the build_native_ext_for_ios.sh script?

**Comment by tylersouthard** [comment]
Looks like the build_native_ext_for_ios.sh script would need to be updated to modify the min os version as well.

**Comment by jtattermusch** [comment]
What hardware are you targeting that you need armv7?   arm64 should be good enough for most iOS devices.

**Comment by tylersouthard** [comment]
A non-negligible segment of our user-base still uses 4th generation iPads (capped at iOS 10).

Unfortunately developing applications for use in schools or other environments where funding for devices is allocated inconsistently or rarely results in the need to support devices sometimes 6-8 years into their lifetime.

**Comment by tylersouthard** [comment]
Resolved by #18324. Closing.
