### ISSUE TITLE
Multiple custom root certificates not used

### ISSUE THREAD

**Issue by hesmar** [grpc/grpc#18304]
### What version of gRPC and what language are you using?
C++, master
 
### What operating system (Linux, Windows,...) and version?
Linux (Ubuntu 16.04 and 18.04)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 5.4.0
 
### What did you do?
I want to connect to multiple servers using TLS. The certificates on these servers are self-signed by different keys. I copied the root certificates to a single certificate file:
```
-----BEGIN CERTIFICATE-----
<RootCert0Pem>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<RootCert1Pem>
-----END CERTIFICATE-----
...
```
In my application, I read the file to `grpc::SslCredentialsOptions::pem_root_certs` and pass it to the channel:
```
auto sslCredOpts = grpc::SslCredentialsOptions{};
sslCredOpts.pem_root_certs = readRootCerts();

auto sslCred = grpc::SslCredentials(sslCredOpts);
auto channel = grpc::CreateCustomChannel(uri, sslCred, arguments);
```

### What did you expect to see?
The connection should work to all servers.
 
### What did you see instead?
 
The connection only works to the server which was signed by the first certificate in that file. For the connection to the other servers, I get the following error message:
```
E0308 13:14:40.605374260    7580 ssl_transport_security.cc:1239] Handshake failed with fatal error SSL_ERROR_SSL: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding.
E0308 13:14:41.626596721    7580 ssl_transport_security.cc:1239] Handshake failed with fatal error SSL_ERROR_SSL: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding.
E0308 13:14:43.171714585    7580 ssl_transport_security.cc:1239] Handshake failed with fatal error SSL_ERROR_SSL: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding.
```
So it seems that only the first certificate is used. 
 
### Anything else we should know about your project / environment?
I tried the same under Windows and there the connection to all servers was working.

**Comment by goudan-er** [comment]
same issue... any help?

**Comment by floodcode** [comment]
Me too

**Comment by mijuva** [comment]
Having the same on Windows, using Visual Studio 2019, grpc 1.27.0 built against OpenSSL 1.1.1d. It looks like only the first cert is parsed from the pem_root_certs string. If the string is written to a file and fed through GRPC_DEFAULT_SSL_ROOTS_FILE_PATH environment variable, then the connection works.
