### ISSUE TITLE
Blocking writes during connectivity loss prevent resumption of stream 

### ISSUE THREAD

**Issue by smaye81** [grpc/grpc#18309]
### What version of gRPC and what language are you using?
 1.15.0 - C++
 
### What operating system (Linux, Windows,...) and version?
 Linux Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang 3.8
 
### What did you do?
We are using the grpc C++ client in an environment with spotty network connectivity.  What we have noticed is that stream writes that occur during a time of connection loss seem to block the reconnection logic from re-establishing the channel.  

For example, our flow is like this:

1.  CreateCustomChannel using SSL certs
2.  Get stub for API (i.e. `auto api = FooAPI::NewStub(channel)`)
3.  Issue the call to get the stream (i.e. `auto stream = api->SendFoo`)
4.  Stream the writes:

```
for (req : requests) {
    stream->Write(req);
}
```

If the connectivity drops during the loop that is writing to the stream, the `Write` call will block instead of failing fast.  When connectivity comes back, the grpc channel will attempt it's reconnection logic.

### What did you expect to see?
I would expect the reconnection logic to retry the blocked write and continue writing.
 
### What did you see instead?
The channel reconnects, but writes to this stream remain blocked.  This then causes our grpc channel to go to IDLE status and no rpcs to flow through.  

Sometimes the write will unblock and RPCs start flowing again.  This causes the channel to move to CONNECTING.  However, if our SSL certs have expired at this point, we get an SSL alert certificate expired error.  It would be nice to provide a callback to re-retrieve certs, which was the impetus for this issue I filed (https://github.com/grpc/grpc/issues/18257).

However, the fact that the write continues to block even after the channel re-establishes is what is my main concern is for this issue.  

One thing we have tried is to wrap the `Write` in an async call and then wait on it.  If the call blocks for longer than some time period, we issue `TryCancel`.  However, this is not guaranteed to cancel the call and in most cases does not appear to:

```
auto f = std::async(std::launch::async, [this, &req, ok]() {
   *ok = stream->Write(req);
});
auto timeout = f.wait_for(5000ms) != std::future_status::ready;
if (timeout) {
   foo_context->TryCancel();
}
```

What is the preferred/recommended approach for dropped connectivity during long-running streams?  Ideally I would expect a way to either deterministically cancel the blocked call or allow it to block and then retry when the stream comes back up, but neither seem to be possible.

**Comment by gnossen** [comment]
@smaye81 Can you reproduce with 1.19?

**Comment by gnossen** [comment]
CC @vjpai @yashykt

**Comment by smaye81** [comment]
I can try.  Was there any change in reconnection logic between 1.15 and 1.19?
