### ISSUE TITLE
please give a one client to two servers example with loadbalance

### ISSUE THREAD

**Issue by chenbaggio** [grpc/grpc#18322]
### What version of gRPC and what language are you using?
 
 version : 1.18
### What operating system (Linux, Windows,...) and version?
 
 linux centos 7.2
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 gcc 4.8
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 the example lb is only one client to one server, can you provide a example 
one client and over two servers, because i do not know how to do it ,is pass target like 
that "192.168.0.10:2790;192.168.0.10:2791" while create custom channel?
and whether I use the grpc lb and known which server is crash etc. ?
 
### What did you see instead?
 
only one client to one server in example

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
@chenbaggio Can you please clarify which language you are requesting an example for? Tentatively assuming C++.

**Comment by gnossen** [comment]
CC @AspirinSJL @markdroth

**Comment by AspirinSJL** [comment]
@chenbaggio The "target" passed to the channel is usually a single server name. The server addresses are returned by the resolver given the server name. For more details, please refer to https://github.com/grpc/grpc/blob/master/doc/load-balancing.md#workflow.

The example under example/cpp/load_balancing currently only shows how to set the load balancing policy name. We need to add the resolution part to make it complete.

Before that's done, please refer to our unit test to get a sense of the mechanism. https://github.com/grpc/grpc/blob/6d5a48a35a69eefc77a0724261be83624c0afd54/test/cpp/end2end/client_lb_end2end_test.cc#L435

**Comment by chenbaggio** [comment]
thank you

**Comment by chenbaggio** [comment]
the case I have read ,but still two questions want to ask:

1. whether create channel must fill target is "fake:///" ? 

2. actual server list how can I pass to resolver,   json conf or others? if it is json conf, please give me
a format example, and whether is set channel argument about json conf?

**Comment by AspirinSJL** [comment]
1. No. This is the doc for naming: https://github.com/grpc/grpc/blob/master/doc/naming.md. The test cases are using "fake:///" scheme to mock away the real name resolving. For most of the cases, DNS is used.

2. If it's for production use, the resolution should be done by the name resolving component itself. If you want to set up a fake lookup table, @apolcyn may know better.

**Comment by apolcyn** [comment]
You can use DNS for load balancing with "grpclb" by publishing DNS records as described in https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md. However, I'd note that "grpclb" is considered deprecated, since we're moving towards some envoy protocols for load balancing (@AspirinSJL if there are more details on that).

Regardless of that, as for how DNS records would be set up to do gRPCLB with two servers, suppose the client targets `foo.bar.com`, and suppose the gRPCLB load balancer is running on IP Address X.X.X.X which is resolveable by `foo.balancer.com`, on port 10000:

Publish an SRV record of `_grpclb._tcp.foo.bar.com`, with data section:
`0 0 10000 foo.balancer.com`

This could be done with using e.g. a BIND DNS server. For a locally running DNS server, you could write a zone file, and run the `named` DNS server on your machines port 53. Then you'd also add an entry for `localhost` in the `nameserver` list of your `/etc/resolv.conf` file so that your DNS clients will reach that DNS server. Alternatively to BIND, for example you could also run e.g. a twisted python DNS server on your local machine (we do that in e.g. [here](https://github.com/grpc/grpc/blob/master/test/cpp/naming/utils/dns_server.py) for some tests that do real DNS queries). Lots of other options also exist for serving the DNS records.

**Comment by apolcyn** [comment]
^ note that service configs are published DNS according to the design in https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md. So similarly to the above comment, if the client is targeting `foo.bar.com`, a TXT DNS record of the name `_grpc_config.foo.bar.com` could be published, containing `grpc_config=<service config as JSON>`

**Comment by chenbaggio** [comment]
thank you all

the following is my pseudo code, please give me your advoices:

1. use CreateCustomChannel create a channel and stub (load balance policy set in here)

2. parse URLs from resolve (here if we do not use resolve,  can use final address format t make address list)

3. use  address list generated by step 2  to get channel arguments and add to 

4.  in your test case , it use to initialize closure_arg(but it still it in fake, and I  could not understand what is closure), how to make it to attach 
to the channel or stub created by step 1 ? whether just the initialize running env is ok ?
     
      the step seems confused !
5. send rpcs

**Comment by chenbaggio** [comment]
hello, the complete example when would you provide?  thank you

**Comment by AspirinSJL** [comment]
Stepping back a little bit, could you describe your use case with more background details?

**Comment by chenbaggio** [comment]
ok! my request is like that:

I setup two grpc servers to implement RPC in HA, and the two servers have different address, so 
I want to use the balance ,  the balance can help me to monitor server status and provide a alive
server to communicate

I just know how to create a channel , stub and set balance argument, but i do not know how to let it work in using balance , for example, the function CreateCustomChannel, the target argument I even do not know how to fill in the situation, so I need your help to provide a case that purely in client view(not the unit test, it can include a lots header files those can not get in grpc SDK), thank you!

**Comment by chenbaggio** [comment]
hello! How are things going? please help, thank you!

**Comment by AspirinSJL** [comment]
You may want to try this:
1. Use "round_robin" LB policy.
2. Make the server target name be resolved to the addresses of your two backend servers. @apolcyn has mentioned a few solutions. The easiest way might be to change your `etc/hosts` file.

**Comment by chenbaggio** [comment]
thank you! the method is use external loadbalancer,  whether thicker client mode is not support in grpc ?

**Comment by AspirinSJL** [comment]
In your case, separate load balancer can solve the problem but is not necessary; client side load balancing is enough.

We support two client side load balancing policies, which are `pick_first` and `round_robin`.

**Comment by chenbaggio** [comment]
thank you!
