### ISSUE TITLE
Grpc.Tools: Cannot run protoc in alpine based dotnet SDK 

### ISSUE THREAD

**Issue by slolife** [grpc/grpc#18338]
### What version of gRPC and what language are you using?
Nuget package Grpc.Tools 1.19.0 (https://www.nuget.org/packages/Grpc.Tools/)
 
### What operating system (Linux, Windows,...) and version?
Alpine Linux docker image with dotnet 2.2 sdk

https://hub.docker.com/_/microsoft-dotnet-core-sdk/
 microsoft/dotnet:2.2-sdk-alpine
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 microsoft dotnet 2.2 sdk
 
### What did you do?
See this sample repo: https://github.com/slolife/alpine-protoc
Build the docker image:

`docker build .`
 
### What did you expect to see?
No errors during build 
 
### What did you see instead?
``` 
/root/.nuget/packages/grpc.tools/1.19.0/build/_protobuf/Google.Protobuf.Tools.targets(263,5): error MSB6003: The specified task executable "/root/.nuget/packages/grpc.tools/1.19.0/tools/linux_x64/protoc" could not be run. No such file or directory [/src/alpine-protoc.csproj]
```

### Anything else we should know about your project / environment?
If I shell into the docker container and look for the `"/root/.nuget/packages/grpc.tools/1.19.0/tools/linux_x64/protoc` file, it does exist.

To get access to the container, comment out the last line in the docker image that starts with `RUN dotnet build` and then run the docker container. 

I tried running `apk add libc6-compat` and re-running the build. This time I got a "Segmentation fault" error.

**Comment by slolife** [comment]
I tried running `apk add libc6-compat` and re-running the build. This time I got the following error:

`/root/.nuget/packages/grpc.tools/1.19.0/build/_protobuf/Google.Protobuf.Tools.targets(263,5): error MSB6006
: "/root/.nuget/packages/grpc.tools/1.19.0/tools/linux_x64/protoc" exited with code 139. [/src/alpine-proto
c.csproj]`

**Comment by nicolasnoble** [comment]
There's quite no way we can support Alpine linux for this package.

**Comment by slolife** [comment]
I would love to see this fixed in the package so it works without having to add to the docker file, but I have posted a workaround dockerfile to the repo: https://github.com/slolife/alpine-protoc

**Comment by jtattermusch** [comment]
Do we understand why after installing `apk add libc6-compat` protoc fails with a segfault?

**Comment by jtattermusch** [comment]
According to @nicolasnoble  the segfault is because of musl libc incompatibilities and it would be a lot of work to make protoc work properly on alpine.

**Comment by jtattermusch** [comment]
If someone once to try to make protoc work on alpine, the pointer is that something like this would probably need to be done in protobuf:

> memcpy wrapper, and the getenv wrapper, mainly.
> https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/wrap_memcpy.cc
> https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/env_linux.cc
> And in general, everywhere we have GPR_BACKWARDS_COMPATIBILITY_MODE

**Comment by psmolkin** [comment]
@slolife See [my comment](https://github.com/grpc/grpc/issues/18428#issuecomment-535041155)

**Comment by jtattermusch** [comment]
Because there's now a known workaround (I verified it works), I will now close this issue as we don't have any immediate plans to work on this.
