### ISSUE TITLE
Build grpc++ successfull but unable to include port_def.inc

### ISSUE THREAD

**Issue by Garu94** [grpc/grpc#18337]
Hi,
I was able to compile, after some troubles, the grpc whole project (includeing the grpc++ one), and to generate the files from the .proto file. The only part that I am missing is to build the example code, because of some external symbols that can't be found, in particular "port_def.inc". I already included the additional directories third_party\protobuf\src and grpc\include

**Comment by nicolasnoble** [comment]
This may mean you have protobuf installed on your system at an older version, and your compiler is preferring to use it instead of the one in third_party\protobuf.

**Comment by Garu94** [comment]
> This may mean you have protobuf installed on your system at an older version, and your compiler is preferring to use it instead of the one in third_party\protobuf.

How could I discover if I have indeed an older version installed?

**Comment by nicolasnoble** [comment]
Well, try to locate the file `descriptor.pb.h` anywhere on your computer.

**Comment by Garu94** [comment]
> Well, try to locate the file `descriptor.pb.h` anywhere on your computer.

Ok, thanks to you I was able to avoid the previous error, but I got a new one. This time, the missing inclusion is about all the < grpcc/impl/codegen/...> stuff.

**Comment by Garu94** [comment]
No, unfortunately I was unable to use the CMake to generate it due to this error, and I was unable to figure out what to do to solve this:

`CMake Error at CMakeLists.txt:73 (find_package):
  find_package Error reading CMake code from
  "C:/extlibs/grpc/cmake/gRPCConfig.cmake".`

When I make the CMake. after setting gRPC_DIR to the directory containing gRPCConfig.cmake

**Comment by nicolasnoble** [comment]
Right, okay. So the long story short here is you're missing dependencies in your project file. I can see you're missing the cares library at least.

**Comment by Garu94** [comment]
I tried following every procedure I found online, but unfortunately I am not really an expert of CMake. Could you please explain me how to build one of the example projects using CMake? Or at least point me to a list of needed dependencies for using gRPC?
