### ISSUE TITLE
External dependence for py_proto_dependencies will never be upstreamed

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#18331]
### What version of gRPC and what language are you using?

master, C++ 
 
### What operating system (Linux, Windows,...) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
bazel
 
### What did you do?

Tried to upgrade googletest build dependence

### What did you expect to see?
 
Should have been able to upgrade without problem

### What did you see instead?
 
py_proto_dependencies is a problem .  It in turn invokes cpp_proto_dependencies, which then includes a build dependence on a version of googletest that is neither the one that we currently use nor the one that I want to start using.

https://github.com/grpc/grpc/blob/8bed44b2c47577fe255eb5b9fe754a2756cefed7/WORKSPACE#L53-L58 refers to code that should get upstreamed in https://github.com/pubref/rules_protobuf/pull/196 , but that PR has been closed without merging, the repo deprecated, and its contents moved to another repo altogether in another org.

As a general rule, we should reduce these kinds of dependences on outside code that affect our build process. Can this dependence be removed?

**Comment by mehrdada** [comment]
I was looking at similar rules to generate protos for Python the other day, https://github.com/stackb/rules_proto seems like a robust source.

**Comment by nicolasnoble** [comment]
Instead, could we reduce external dependencies and build our own? Or have them in protobuf?

**Comment by mehrdada** [comment]
@nicolasnoble I agree. There should be official grpc bazel rules (perhaps in the main repo, why not?)

Also, scratch my previous comment. That set of rules have issues too :(
