### ISSUE TITLE
No warnings as errors (-Werror flag)

### ISSUE THREAD

**Issue by b00f** [grpc/grpc#18349]
### What version of gRPC and what language are you using?
 I tried grpc 1.18 and 1.19.1 inside Travis deployment
 
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 Try to build gRPC inside a docker

### What did you expect to see?
It should compile without any error 
 
### What did you see instead?
 An error because all warning being treated as error

### Anything else we should know about your project / environment?
At the moment there are lots of issues because of treating warning as error. Look [here](https://github.com/grpc/grpc/search?q=%22all+warnings+being+treated+as+errors%22&unscoped_q=%22all+warnings+being+treated+as+errors%22&type=Issues)
I suggest to make an option to disable it for automation builds.

**Comment by bclermont** [comment]
this is not really helpful, you should give more context such as output of errors

**Comment by b00f** [comment]
My point is not fixing these kind of errors which are result of warnings in different OSs in different machines (or maybe dockers). I mean give this option to the user to build grpc without `-Werror` flag. After searching a lot I fixed this issue by running this command, before make:  
`sed -i 's/-Werror/ /g' Makefile`

**Comment by nicolasnoble** [comment]
We are slowly moving towards recommending using the cmake solution to build grpc. At the moment, the Makefile is designed for our test infrastructure mainly, and for lesser capable build systems, such as Ruby or PHP.

**Comment by nicolasnoble** [comment]
Our using Bazel, in fact.

**Comment by b00f** [comment]
> We are slowly moving towards recommending using the cmake solution to build grpc. 

CMake is a tools in C++ world that anyone loves to hate it. ;)
