### ISSUE TITLE
Segmentation fault in main thread using gRPC client from inside Pebble forked gRPC server

### ISSUE THREAD

**Issue by jshlbrd** [grpc/grpc#18342]
### What version of gRPC and what language are you using?
version: 1.19.0
language: Python (3.6)
 
### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 18.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.7
 
### What did you do?
Attempted to launch a gRPC client request from inside a forked gRPC server. Here is the exact setup:

1. Create pool of subprocesses (I've been using Pebble's ProcessPool)
2. Start gRPC server, passing previously created pool as an arg
3. Assign incoming RPCs as tasks to the pool
4. Have subprocesses in the pool create gRPC client requests 
4. Seg fault in main thread

This variation also causes a seg fault:

1. Create pool of subprocesses (once again, Pebble ProcessPool)
2. Start gRPC server
3. Assign tasks to the pool that create gRPC client requests
4. Seg fault in main thread

Pseudo-code:

```py
class TestServicer(test_pb2_grpc.TestServicer):
    def __init__(self):
        pass


def test():
    <make your gRPC requests here>  

pool = pebble.ProcessPool(max_workers=1,
                          max_tasks=1)
executor = futures.ThreadPoolExecutor(max_workers=1)
server = grpc.server(executor,
                     maximum_concurrent_rpcs=None)
test_pb2_grpc.add_TestServicer_to_server(TestServicer, server)
server.add_insecure_port('127.0.0.1:8443')
server.start()

futures = []
for i in range(10):
    futures.append(pool.schedule(test))

for f in futures:
    print(f.result())
```

Here's some debug output from a script like the one described above:
```
process MainProcess thread MainThread: appending futures
process Process-3 thread MainThread: sending RPC request
process Process-2 thread MainThread: sending RPC request
process Process-1 thread MainThread: sending RPC request
Segmentation fault
```

### What did you expect to see?
 
gRPC client requests execute normally. 

### What did you see instead?
 
Segmentation fault errors in the parent process (where pool is defined).

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

Nothing else to add except consider that this may be related to this: https://github.com/grpc/grpc/issues/13998. See this comment for an example of how multiprocessing is used in my case: https://github.com/grpc/grpc/issues/16001#issuecomment-470185940

**Comment by jshlbrd** [comment]
I just discovered that this may not happen with the built-in multiprocessing.Pool (which Pebble is a wrapper for) -- Pebble's pool does some polling of the processes inside the pool, perhaps this is clashing with polling that happens with gRPC.

**Comment by gnossen** [comment]
After a bit of digging, it looks like a `pebble.ProcessPool` creates its workers lazily. That is, your worker processes are being `fork`ed on `pool.schedule(test)`, *not* when the pool is instantiated.

```
(Pdb) where
  ~/Dev/pebble/pebble_test.py(11)<module>()
-> pool.schedule(foo)
  ~/Dev/pebble/pebble/pool/process.py(86)schedule()
-> self._check_pool_state()
  ~/Dev/pebble/pebble/pool/base_pool.py(91)_check_pool_state()
-> self._update_pool_state()
  ~/Dev/pebble/pebble/pool/base_pool.py(100)_update_pool_state()
-> self._start_pool()
  ~/Dev/pebble/pebble/pool/process.py(64)_start_pool()
-> self._pool_manager.start()
  ~/Dev/pebble/pebble/pool/process.py(189)start()
-> self.worker_manager.create_workers()
  ~/Dev/pebble/pebble/pool/process.py(345)create_workers()
-> self.new_worker()
> ~/Dev/pebble/pebble/pool/process.py(359)new_worker()
-> worker = launch_process(
```

**Comment by gnossen** [comment]
This [multiprocessing example](https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing) hot off the presses might be relevant to your interests.

**Comment by jshlbrd** [comment]
Thanks for looking into this, I’ll take a look at that example — at one point I had tried reuseport but it was causing erratic behavior in my application (unfortunately nothing more to share on that topic, I didn’t take notes on the behavior and quickly moved on from it). 

For now, it seems like a Pebble Pool will not work but a multiprocessing Pool will.

**Comment by jshlbrd** [comment]
@gnossen on second thought, any chance you have any insight into what happens in a multiprocessing Pool when processes die/start? I'm assuming that falls into the same category as Pebble (fork would happen after the gRPC server starts).

**Comment by jshlbrd** [comment]
To possibly close the thread on this, all Python subprocess pools that I've tested (multiprocessing.Pool, pebble.ProcessPool, billiard.Pool) exhibit the segmentation fault behavior when `maxtasksperchild` (or a similar setting) is enabled. I suspect that the same thing would apply to any crashed subprocesses that are recreated. IMO this rules out any support of process pools for Python gRPC.

**Comment by noxdafox** [comment]
All process pools automatically deal with process termination. Processes might terminate due to timeout (`pebble`, `billiard`), task cancellation (`pebble`, `billiard`), task limit exceeded or crashes.

Therefore, if the constraint is to pre-fork I would recommend against using process pools.

As `grpc` uses a server-client interface, I would recommend to interleave requests using pools of threads rather than processes. You can still use process pools for unstable or CPU intensive operations.
