### ISSUE TITLE
1.19.0 iOS version support

### ISSUE THREAD

**Issue by mxl123** [grpc/grpc#18350]
### What version of gRPC and what language are you using?
1.19.0
 
### What operating system (Linux, Windows,...) and version?
 Xcode10, MacOS 10.14.2, iOS 9.x or iOS 10.x
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Xcode
 
### What did you do?
Run with gRPC 1.19.0
 
### What did you expect to see?
No crash
 
### What did you see instead?
Crash every time

**Comment by mxl123** [comment]
I can’t find anywhere in the readme or in any of the introductory blog posts any mention of what iOS version are supported. Is there any information about what version supported for gRPC version?

**Comment by gnossen** [comment]
@mxl123 Can you provide any more details surrounding the circumstances of your crash?

**Comment by gnossen** [comment]
CC @muxi
