### ISSUE TITLE
A precondition for calling grpc_call_start_batch wasn't met. Error 8

### ISSUE THREAD

**Issue by clausjoergensen** [grpc/grpc#18364]
### What version of gRPC and what language are you using?
1.18
 
### What operating system (Linux, Windows,...) and version?
iOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Objective-C
 
### Bug

We're seeing the following error `A precondition for calling grpc_call_start_batch wasn't met. Error 8`  as part of the `GRPCProtoCall.start()` call. Error 8 apparently translates to  `GRPC_CALL_ERROR_TOO_MANY_OPERATIONS`

So, how can there be too many operations when calling .start() (as part of an app launch sequence), and how can it be a _precondition_ failure? (Also, please print the string name for the error, not just the number 8. "Error 8" isn't very informative)

The gRPC part of the stack is as follows

```
#3	0x105bc50ac in -[GRPCWrappedCall startBatchWithOperations:errorHandler:] at Pods/gRPC/src/objective-c/GRPCClient/private/GRPCWrappedCall.m:304
#4	0x105bc04a0 in -[GRPCCall sendHeaders:] at Pods/gRPC/src/objective-c/GRPCClient/GRPCCall.m:327
#5	0x105bc11b4 in -[GRPCCall startCallWithWriteable:] at Pods/gRPC/src/objective-c/GRPCClient/GRPCCall.m:467
#6	0x105bc136c in -[GRPCCall startWithWriteable:] at Pods/gRPC/src/objective-c/GRPCClient/GRPCCall.m:504
#7	0x1065113d0 in -[ProtoRPC startWithWriteable:] at Pods/gRPC-ProtoRPC/src/objective-c/ProtoRPC/ProtoRPC.m:107
```

We have never been able to reproduce this locally, but Crashlytics collected data report this as happening for tens of thousands of users in our real world app. 

This is possible related to #4628

**Comment by jtattermusch** [comment]
Can you provide a snippet that reproduces the problem? This looks like it could be wrong use of API.

**Comment by rmstar** [comment]
Yes, this could be caused by incorrect API usage. `GRPC_CALL_ERROR_TOO_MANY_OPERATIONS`  is likely returned from [here](https://github.com/grpc/grpc/blob/v1.18.0/src/core/lib/surface/call.cc#L1550). Maybe you're trying to send `GRPC_OP_SEND_INITIAL_METADATA` more than once on the same call?

**Comment by clausjoergensen** [comment]
We managed to get a proper symbolicated crash for the full stack now:

{code}

Thread 8 name:
--
Thread 8 Crashed:
0   grpc                          	0x0000000106b145dc grpc_validate_header_key_is_legal(grpc_slice) + 673244 (validate_metadata.cc:69)
1   grpc                          	0x0000000106a83140 prepare_application_metadata(grpc_call*, int, grpc_metadata*, int, int, grpc_metadata*, int) + 78144 (call.cc:891)
2   grpc                          	0x0000000106a83140 prepare_application_metadata(grpc_call*, int, grpc_metadata*, int, int, grpc_metadata*, int) + 78144 (call.cc:891)
3   grpc                          	0x0000000106a8298c call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, int) + 76172 (call.cc:1589)
4   grpc                          	0x0000000106a82210 grpc_call_start_batch + 74256 (call.cc:1908)
5   GRPCClient                    	0x00000001062a1070 -[GRPCWrappedCall startBatchWithOperations:errorHandler:] + 53360 (GRPCWrappedCall.m:288)
6   GRPCClient                    	0x000000010629c4a0 -[GRPCCall sendHeaders:] + 33952 (GRPCCall.m:327)
7   GRPCClient                    	0x000000010629d1b4 -[GRPCCall startCallWithWriteable:] + 37300 (GRPCCall.m:468)
8   GRPCClient                    	0x000000010629d36c -[GRPCCall startWithWriteable:] + 37740 (GRPCCall.m:506)
9   ProtoRPC                      	0x00000001067f13d0 -[ProtoRPC startWithWriteable:] + 21456 (ProtoRPC.m:109)
{code}

The code triggering the start call is (slightly simplified) as follows:

{code}
let service = MyService(host: "service.company.com") // gRPC generated class
let pipeWriter = GRXBufferedPipe()
let subscription = service.rpcToSubscribe(withRequestsWriter: pipeWriter, eventHandler: onEvent)
subscription.start()
{code}

We still can't reproduce the issue locally, but we have 100k+ crashes in production, with no clear reason as to why (device and OS versions differs)

**Comment by clausjoergensen** [comment]
ok, good news, we're not longer seeing this crash with gRPC 1.19 (we're seeing another crash in the start flow, but I'll create another ticket if I can find a symbolicated stack for it)
