### ISSUE TITLE
The release commit should have a tag with the substring "0.5.0"

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#1836]
For our Podspec to be admitted into Cocoapods' main repo, the tag of the release must include the library version as a substring. @a11r agreed to add a tag "release-0_x_y-objectivec-0.a.b".

An alternative is to use "release-0.9.x" instead of "release-0_9_x", and I just assign version 0.9.x to the podspec. The problem is really the underscores.

I'm fine to wait till release 0.9.1 next week.

**Comment by nicolasnoble** [comment]
Like https://github.com/grpc/grpc/tree/release-0_9_1-objectivec-0.5.1 ?

**Comment by jcanizales** [comment]
Yep :) I'll submit the podspec to Cocoapods.
