### ISSUE TITLE
GRPC c++ file descriptor leak

### ISSUE THREAD

**Issue by IzakMarais** [grpc/grpc#18365]
### What version of gRPC and what language are you using?
 1.18.0, C++
 
### What operating system (Linux, Windows,...) and version?
Linux (Debian Stretch)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
 
### File descriptor leak bug

I have uploaded a minimal example that reproduces the bug to this repo: https://github.com/IzakMarais/grpc-bug. The readme has details on reproducing it.

When running this the client we see file descriptor leaks. The client continually recreates a channel and a stub, which is probably not the recommended behaviour?

The leak is observed when building against the latest versions of `grpc` (1.18) and `protoc` (3.6.1) fetched by the `vcpkg` package manager.

When building against the latest `grpc/cxx` Docker image, the leak is *not* present. The  image contains `grpc` 1.10.x (based on [this dockerfile](https://hub.docker.com/r/grpc/cxx/dockerfile/)) and `protoc` 3.5.0.

**Comment by IzakMarais** [comment]
Issue still relevant as far as I am concerned.

**Comment by bengamine** [comment]
The file description leak issue is also observed on grpc (1.19), is there any update for this issue?

**Comment by rainerschoe** [comment]
Also experiencing this on 1.19, so still relevant. We need to work-around this issue.

This seems to happen if you create multiple channels with overlapping live-times within the same process. It does not happen, if you close previous channel again before opening the next one.

In our case we are implementing a "watchdog" repeatedly self-testing the gRPC server, which now leaks file-descriptors.

**Comment by yashykt** [comment]
Reassigning to the new owner

**Comment by samta** [comment]
I can observe the same behaviour with 1.18, do we have fix for this issue?

**Comment by yashykt** [comment]
@samta, @IzakMarais I am sorry this bug did not receive attention. Can you please try with head?

**Comment by amanand** [comment]
I am observing same issue in grpc 1.18. I have a server application that hosts Streaming RPCs, in my case i dont see one of the fd (TCP socket, with one of the grpc client) in the grpc pollset, but i continue to see the fd in CLOSE state in my application for more than few days now. Is there any chance of failure in closing the socket after removing it from pollset in the grpc stack? Possibly a missed/wrong error handling?

**Comment by veblush** [comment]
Recreating a channel every time is not recommended in general. It may cache established connections internally so it could explain why fd seems to keep increasing. So please reuse the channel if possible. If you think it's still relevant, please feel free to reopen this.

**Comment by rainerschoe** [comment]
Hi @veblush
Thanks for your input, We are well aware that recreating channels is not performant, however we are doing it at low frequencies as a "watchdog" to self-test the server. i.e. to test if new gRPC connections can still be established.

Right now we are observing sporadic FD-leaks with this "watchdog" enabled. I am still working on isolating the problem in our application to verify if this is the same issue as described here.

Any input on how the caching of "established conections internally" works and how it might lead to FD leaks would be really helpful. (we see server-side sockets stuck in TCP_CLOSE_WAIT state building up until system crashed due to out of resources)
