### ISSUE TITLE
Support for async bidirectional streaming client in Python

### ISSUE THREAD

**Issue by stephan-tolksdorf** [grpc/grpc#18376]
### What version of gRPC and what language are you using?

v1.19.0 Python
 
### What operating system (Linux, Windows,...) and version?
 N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 N/A
 
### What did you do?

I tried to implement an async Python client for a bidirectional streaming gRPC call, including support for cancellation.
 
### What did you expect to see?
 
I expected the Python gRPC library to be similarly full-featured as e.g. the C# library.
 
### What did you see instead?
 
I saw that the Python gRPC library is missing support for async bidirectional streaming gRPC calls.

**Comment by lidizheng** [comment]
This is on the road map of gRPC Python team. We have some experimental proposals, but yet to decide which way to go. One of the promising proposal is supporting AsyncIO, and the async bidirectional streaming API will be added at the same time.

If possible, can you give more details about your use case and how you approach it?

**Comment by stephan-tolksdorf** [comment]
I intended to use the bidirectional streaming RPC for a prototype backend service call that sends a (potentially long) series of sequentially dependent work items that each generate a response message.

**Comment by lidizheng** [comment]
@stephan-tolksdorf Can you explain more why you want the async bidi-streaming API?

As for a workaround, if your backend service is deadlocking due to limited threads, I would recommend to set `max_workers=None` for your thread pool to trade off a little performance for correctness.
