### ISSUE TITLE
Error: ares.h: No such file or directory during bazel compilations

### ISSUE THREAD

**Issue by Ark-kun** [grpc/grpc#18403]
When I try to compile some projects using bazel, the compilation fails during the grppc calculation:

```
ERROR: /usr/local/google/home/avolkov/.cache/bazel/_bazel_avolkov/31e08d5c4be525ad16464e998010eee7/external/grpc/BUILD:1515:1: C++ compilation of rule '@grpc//:grpc_resolver_dns_ares' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_F
ORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 49 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:23:10: fatal error: ares.h: No such file or directory
 #include <ares.h>
          ^~~~~~~~
compilation terminated.
```

Same thing happened with people compiling other projects: https://github.com/tensorflow/tensorflow/issues/19464
https://github.com/tensorflow/tensorflow/issues/23673
https://github.com/bazelbuild/bazel/issues/6898
https://github.com/kubeflow/pipelines/issues/970
https://github.com/tensorflow/models/issues/5751

Is grpc's ares dependency properly documented for bazel?

Bazel version:
Build label: 0.23.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 11 16:47:03 2019 (1552322823)
Build timestamp: 1552322823
Build timestamp as int: 1552322823

**Comment by apolcyn** [comment]
We added https://github.com/grpc/grpc/pull/13561 a while back to provide a utility that automatically adds grpc's dependencies to a project, by that project putting e.g. these lines in their WORKSPACE file:

```
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```

See [implementation of grpc_deps](https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L7) - this adds grpc's c-ares dependency it it doesn't already exist.

Does the `grpc_deps()` utility fix the problem for you?

> Is grpc's ares dependency properly documented for bazel?

Hmm, AFAIK there isn't documentation for grpc's bazel dependencies in any central place. I'm wondering if it would help to add an example for this - consuming grpc from a 3rd party project, via bazel.

**Comment by Ark-kun** [comment]
>>Is grpc's ares dependency properly documented for bazel?
>Hmm, AFAIK there isn't documentation for grpc's bazel dependencies in any central place. 

By "documented for Bazel" I meant "specified to Bazel in a way it can understand".

**Comment by Ark-kun** [comment]
> See [implementation of grpc_deps](https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L7) - this adds grpc's c-ares dependency it it doesn't already exist.
> 
> Does the `grpc_deps()` utility fix the problem for you?

@neuromage, do you think we could use this?
