### ISSUE TITLE
socket errors unhelpful

### ISSUE THREAD

**Issue by mwytock** [grpc/grpc#1840]
Messages such as these should include the host:port, otherwise its not possible to know what end point is causing problems in a process with multiple connections:

E0531 04:33:48.682259810       8 tcp_client_posix.c:145] socket error: connection refused
E0531 04:33:50.682653580       8 tcp_client_posix.c:145] socket error: connection refused
E0531 04:33:54.728829060       8 tcp_client_posix.c:145] socket error: connection refused
E0531 04:34:02.729196699       8 tcp_client_posix.c:145] socket error: connection refused
E0531 04:34:18.828834811       8 tcp_client_posix.c:145] socket error: connection refused

**Comment by nicolasnoble** [comment]
This is probably also true for Windows sockets.

**Comment by ctiller** [comment]
One of the things I'd like for us to do in coming weeks is to establish an internal api for capturing and reporting more context for all of our error messages. Just host:port will be insufficient when building a client side load balanced channel, for instance.

**Comment by ctiller** [comment]
This duplicates #49
