### ISSUE TITLE
PHP: MacOS build failed

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#18423]
```
Starting test 'PersistentListTest::testPersistentChannelTwoUpperBoundOutBound3'.
E0318 16:27:44.188030000 140735862252416 ssl_utils.cc:464]             load_file: {"created":"@1552951664.188004000","description":"Failed to load file","file":"src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"/usr/local/share/grpc/roots.pem","referenced_errors":[{"created":"@1552951664.188002000","description":"No such file or directory","errno":2,"file":"src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}
E0318 16:27:44.188082000 140735862252416 ssl_utils.cc:304]             Could not get default pem root certs.
src/php/bin/run_tests.sh: line 29:  5806 Segmentation fault: 11  php $extension_dir -d max_execution_time=300 $(which phpunit) -v --debug ../tests/unit_tests/PersistentChannelTests
```

https://source.cloud.google.com/results/invocations/3e780997-4659-4cbb-bf46-3fc7fd350af8/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_dbg/log

**Comment by stanley-cheung** [comment]
The "Basic Tests MacOS" build was passing up till #18398, and starts failing from #18401 onwards.

**Comment by nicolasnoble** [comment]
#18393 only adds source code without using it, so it's unlikely related.

**Comment by stanley-cheung** [comment]
Yea it's more like the tests start failing *when #18393 was created*.

**Comment by stanley-cheung** [comment]
Not reproducible when I run the tests locally on a Mac.

**Comment by stanley-cheung** [comment]
By looking at this: https://fusion.corp.google.com/projectanalysis/history/KOKORO/prod%3Agrpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_dbg

We had a suspicion that #18115 is causing the PHP tests to start to fail
