### ISSUE TITLE
C#: Resolving dependencies in Alpine OS v3.9

### ISSUE THREAD

**Issue by psmolkin** [grpc/grpc#18428]
gRPC:
1.18.0/1.19.0

OS:
Alpine 3.9

dotnet sdk:
2.2.105

I'v tried to move my app to new dotnet base images based on Alpine v3.9.
Installation of the *ibc6-compat* dependency is required for the `libgrpc_csharp_ext.x64.so` library to work. 
*libc6-compat ver1.1.20-r4* from */3.9/main* branch stores necessary `ld-linux-x86-64.so.2` at new location: 
`/lib64/ld-linux-x86-64.so.2` (against `/lib/ld-linux-x86-64.so.2` at 3.8 branch)
where `libgrpc_csharp_ext.x64.so` can`t find it

Of cause, I can copy *ld-linux-x86-64.so.2* to */lib/* dir but it's not looks good.

Can you fix dependencies path resolving and add */lib64* to the scanned paths?

**Comment by tadeuszwojcik** [comment]
I've stumbled exactly on the same issue but with .net core 3 previews

**Comment by Jeskz0rd** [comment]
Same happens with the official Microsoft image that uses `libgrpc_csharp_ext.x64.so `.
ie: mcr.microsoft.com/dotnet/core/aspnet:2.1.11-alpine3.9

I checked with `.NetCore 2.2 and 2.1`

**Comment by jtattermusch** [comment]
PRs with suggested fix are welcome

**Comment by jtattermusch** [comment]
Related problems is that as of now, protoc binary doesn't work out of the box for alpine linux, which makes developing on Alpine linux problematic (Grpc.Tools .proto integration won't work correctly): https://github.com/grpc/grpc/issues/18338

**Comment by psmolkin** [comment]
Using https://github.com/sgerrand/alpine-pkg-glibc instead of libc6-compat solves all issues with grpc.* nuget packages.
Tested with Alpine 3.9
@jtattermusch

**Comment by harryparkdotio** [comment]
tried using `alpine-pkg-glibc`, unfortunately didn't work for me

---

using `dotnet core 2.1`

**Comment by jtattermusch** [comment]
> Using https://github.com/sgerrand/alpine-pkg-glibc instead of libc6-compat solves all issues with grpc.* nuget packages.
> Tested with Alpine 3.9
> @jtattermusch

I was able to get both Grpc.Tools and the grpc runtime working fine on Alpine 3.9 with the workaround provided. Adding  a distribtest to test continously https://github.com/grpc/grpc/pull/17272

**Comment by jtattermusch** [comment]
Because there's now a known workaround (https://github.com/grpc/grpc/issues/18428#issuecomment-535041155 - I verified it works), I will now close this issue as we don't have any immediate plans to work on this.
