### ISSUE TITLE
C#: How to dispose duplex streaming call properly?

### ISSUE THREAD

**Issue by ElderOrb** [grpc/grpc#18432]
### What version of gRPC and what language are you using?
 1.19.0
 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 MSVC 2017
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I'm executing duplex streaming call like this: 

```
        public Message.Types.LoginResponse Login(Message.Types.LoginRequest.Types.LoginType loginType)
        {
            using(var call = _securityService.Login(_metadata, null, _cancelGrpcTasks.Token))
            {
                var grpcIdentity = new GrpcIdentity<Message, Message>((data) =>
                {
                    return new Message
                    {
                        NegotiateMessage = new Message.Types.NegotiateMessage
                        {
                            Data = ByteString.CopyFrom(data)
                        } 
                    };
                }, (message) =>
                {
                    return message.NegotiateMessage.Data.ToByteArray();
                });

                grpcIdentity.Send(call.RequestStream, call.ResponseStream);

                call.RequestStream.WriteAsync(new Message
                {
                    LoginRequest = new Message.Types.LoginRequest
                    {
                        LoginType = loginType
                    }

                }).Wait(_cancelGrpcTasks.Token);

                call.ResponseStream.MoveNext(_cancelGrpcTasks.Token).Wait(_cancelGrpcTasks.Token);
                var response = call.ResponseStream.Current.LoginResponse;

                // uncommenting fixes ShutdownAsync !!!
                // call.ResponseStream.MoveNext(_cancelGrpcTasks.Token);
                return response;
            }
```

### What did you expect to see?

 ... and I would expect this call to be fully disposed after leaving 'using' block. In reality seems like it is not unless 'call.ResponseStream.MoveNext(_cancelGrpcTasks.Token);' executed (see commented code). 

I would expect channel.ShutdownAsync().Wait() to fully uninitialize grpc channel. 
 
### What did you see instead?

channel.ShutdownAsync().Wait() results int infinite wait. 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

So what is the right way to uninitialize grp channel from the client? I don't want to terminate 'grpc environment' because I'd like to be able to recreate channel later if required. And I hate an idea of adding senseless 'call.ResponseStream.MoveNext(_cancelGrpcTasks.Token);' at the end of every streaming call I have *just* to make ShutdownAsync().Wait() to work.

**Comment by jtattermusch** [comment]
Just to make sure we're on the same page:

1. you invoke the snippet provided
2. you call `channel.ShutdownAsync().Wait()` and it hangs (unless you've called ResponseStream.MoveNext() previously)

Does the logging provide any additional info?

**Comment by ElderOrb** [comment]
1. yes
2. and yes. 

Frankly speaking I haven't review log results but can collect it and provide you. Or maybe I can just provide sample application illustrating the issue.

**Comment by jtattermusch** [comment]
@ElderOrb  a sample app would be useful.

**Comment by ElderOrb** [comment]
Weird, but I can't reproduce the issue using simple sample. I guess issue can be closed for now until I find what contribute to such a behaviour...
