### ISSUE TITLE
Grpc "stream removed" in Azure

### ISSUE THREAD

**Issue by yunfandev** [grpc/grpc#18468]
### What version of gRPC and what language are you using?
 1.19.0
 
### What operating system (Linux, Windows,...) and version?
 Linux & Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 dotnet core
 
### What did you do?

We put our grpc server on Azure and then we try to call these grpc servces locally. Everything works fine at first, but it can't be called normally after waiting for five minutes.

There is sample code.
[GrpcConsoleApp.zip](https://github.com/grpc/grpc/files/2993222/GrpcConsoleApp.zip)
 
### What did you expect to see?
How to solve my problem
 
### Anything else we should know about your project / environment?
We tried AWS and Aliyun, no similar problems. 😂😂😂😂

**Comment by yunfandev** [comment]
Just like this:
![grpc](https://user-images.githubusercontent.com/8027453/54772577-9aca1c00-4c42-11e9-876f-91afc0ce779c.png)

**Comment by Wisgary** [comment]
Are you using an Azure LB? Perhaps the TCP idle connection is killing you? To test this you can bump that up from the default (I think it is 4 or 5 minutes?) up to 30 and see if the app stops working after 30 minutes instead. 

You may need to turn on keep-alive otherwise. Check out [keepalive.md](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) Other people can speak to whether or not "Stream removed" is the appropriate error you should be receiving.

**Comment by yunfandev** [comment]
@Wisgary 
We add the following code on server side, but the problem still exists.
```csharp            
var options = new List<ChannelOption>()
            {
                new ChannelOption("GRPC_ARG_KEEPALIVE_TIME_MS", 1000 * 60 * 1),
                new ChannelOption("GRPC_ARG_KEEPALIVE_TIMEOUT_MS", 1000 * 10),
                new ChannelOption("GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS", 1000 * 10),
                new ChannelOption("GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA", 0),
                new ChannelOption("GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS", 1)
            };
```
![Wireshark](https://user-images.githubusercontent.com/8027453/54809616-c854ab00-4cbe-11e9-8e9f-18527fef42ae.png)
We can't receive any packets about HTTP2 pings, 😭😭😭😭😭😭😭

**Comment by yunfandev** [comment]
@Wisgary
When the client's sleep time is greater than the Azure TCP idle timeout time, the grpc call will be failed with "Stream Removed"

**Comment by Wisgary** [comment]
Hi yunfan - if you look at [grpc_types.h](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h)

#define GRPC_ARG_KEEPALIVE_TIME_MS **"grpc.keepalive_time_ms"**

You want the value rather than the symbol for your channel options - so "grpc.keepalive_time_ms".

**Comment by yunfandev** [comment]
@Wisgary 
(⊙o⊙)？😂😂😂😂，It seems that I made a mistake, thx.
