### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nferreira** [grpc/grpc#1849]
Hi,

I am trying to compile grpc on Mac and I get the following error:

[LD]      Linking libs/opt/libgrpc++.dylib
Undefined symbols for architecture x86_64:
  "_grpc_call_set_credentials", referenced from:
      grpc::SecureCredentials::ApplyToCall(grpc_call*) in secure_credentials.o
  "_grpc_server_register_completion_queue", referenced from:
      grpc::Server::Server(grpc::ThreadPoolInterface*, bool, int) in server.o
      grpc::ServerBuilder::BuildAndStart() in server_builder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/opt/libgrpc++.dylib] Error 1

**Comment by nicolasnoble** [comment]
So I've seen this being reported sporadically. I have no clue about how this can happen or how to reproduce it. Would you care sharing more information with us about it, how  you investigated it, and so on ? That'd be great.

**Comment by soltanmm** [comment]
I may have seen this before, and I think I saw in the context of stale libs. Could you first try uninstalling any old GRPC libraries you may have (as in `rm libgrpc.*` and `rm libgpr.*` them from your install directory), then building?

If that doesn't work, take note of that and then try:

```
git clean -xdf
git submodule foreach 'git clean -xdf'
```

Then build again.

If that still doesn't work, take note of that and please tell us what's up.

**Comment by nicolasnoble** [comment]
*facepalm* I know, and I've seen someone suggesting the solution for it, but I think we dropped the ball, @soltanmm. We need to add a -L in the Makefile's CPPFLAGS that goes in the libs directory.

**Comment by nferreira** [comment]
As suggested by @soltanmm, after deleting the previous version of grpc and recompiling it, it worked just fine!
