### ISSUE TITLE
C++ client unable to connect to server fails with cert error

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#18506]
### What version of gRPC and what language are you using?
 1.12.x
 
### What operating system (Linux, Windows,...) and version?
 Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc6
 
### What did you do?
Tried connecting client with multiple certs in `ca.crt` to server, even though the cert exists in `ca.crt` connect fails with error code 14.

### What did you expect to see?
 Successful connection
 
### What did you see instead?
 gRPC Debug logs:
I0322 08:56:35.814007670     154 ssl_transport_security.cc:211]                 LOOP - TLS client read_certificate_st  - !!!!!!
I0322 08:56:35.814014042     154 ssl_transport_security.cc:211]                 LOOP - TLS client verify_server_certi  - !!!!!!
E0322 08:56:35.814190388     154 ssl_transport_security.cc:1227] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0322 08:56:35.814215477     154 security_handshaker.cc:129] Security handshake failed: {"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0322 08:56:35.814223612     154 ev_posix.cc:222]            (fd-trace) fd_shutdown(9)
E0322 08:56:35.814229548     154 lockfree_event.cc:160]      LockfreeEvent::SetShutdown: 0x7f5148010280 curr=(nil) err={"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
E0322 08:56:35.814253700     154 lockfree_event.cc:160]      LockfreeEvent::SetShutdown: 0x7f5148010288 curr=0x2 err={"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
E0322 08:56:35.814259196     154 lockfree_event.cc:160]      LockfreeEvent::SetShutdown: 0x7f5148010290 curr=(nil) err={"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0322 08:56:35.814272606     154 handshaker.cc:212]          handshake_manager 0xa33f50: error={"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"} shutdown=0 index=2, args={endpoint=(nil), args=(nil) {size=0: (null)}, read_buffer=(nil) (length=0), exit_early=0}
I0322 08:56:35.814277762     154 handshaker.cc:245]          handshake_manager 0xa33f50: handshaking complete -- scheduling on_handshake_done with error={"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0322 08:56:35.814282833     154 timer_generic.cc:467]       TIMER 0xa33fd0: CANCEL pending=true
I0322 08:56:35.814334483     154 resource_quota.cc:818]      RQ anonymous_pool_a33980 ipv4:23.208.223.73:443: free 8192; free_pool -> 8192
I0322 08:56:35.814339365     154 resource_quota.cc:818]      RQ anonymous_pool_a33980 ipv4:23.208.223.73:443: free 8192; free_pool -> 16384
I0322 08:56:35.814343788     154 ev_posix.cc:215]            (fd-trace) grpc_fd_orphan, fd:9 closed
I0322 08:56:35.814387357     154 connectivity_state.cc:164]  SET: 0x7f5148008300 subchannel: CONNECTING --> TRANSIENT_FAILURE [connect_failed] error=0xa47f50 {"created":"@1553244995.814376968","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}]}
I0322 08:56:35.814393209     154 connectivity_state.cc:190]  NOTIFY: 0x7f5148008300 subchannel: 0x7f51480108e8
I0322 08:56:35.814397204     154 subchannel.cc:668]          Connect failed: {"created":"@1553244995.814200430","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}

Is gRPC not able to read multiple certs from a file?

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
