### ISSUE TITLE
python build failure under windows for grpc_build_artifacts

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#18520]
cygrpc.cpp
c:\python27\include\pyconfig.h(142) : warning C4005: 'MS_WIN64' : macro redefinition
        command-line arguments :  see previous definition of 'MS_WIN64'
src\python\grpcio\grpc/_cython/cygrpc.cpp(542) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

**Comment by lidizheng** [comment]
Test failure log https://source.cloud.google.com/results/invocations/aba9009a-f60a-4829-b97e-ca78619f214a/targets/grpc%2Fcore%2Fpull_request%2Fwindows%2Fgrpc_build_artifacts/log

**Comment by lidizheng** [comment]
The typedef code in generated `cygrpc.cpp`.
```cpp
#ifdef _MSC_VER
    #ifndef _MSC_STDINT_H_
        #if _MSC_VER < 1300
           typedef unsigned char     uint8_t;
           typedef unsigned int      uint32_t;
        #else
           typedef unsigned __int8   uint8_t;
           typedef unsigned __int32  uint32_t;
        #endif
    #endif
#else
   #include <stdint.h>
#endif
```
