### ISSUE TITLE
Protoc plugins should be named like protoc-gen-objcgrpc

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#1852]
As the name is arbitrary, there's no reason not to use the name protoc expects: protoc-gen-*

It'll prevent things like https://github.com/grpc/homebrew-grpc/pull/24.

CC: @jtattermusch @tbetbetbe

**Comment by hsaliak** [comment]
@jcanizales moving this out of GA milestone, let me know if there are any concerns with that.
