### ISSUE TITLE
Ruby implementation has limited support for bad HTTP requests

### ISSUE THREAD

**Issue by warhammerkid** [grpc/grpc#18525]
### What version of gRPC and what language are you using?
Ruby GRPC 1.19
 
### What operating system (Linux, Windows,...) and version?
Any
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby 2.4
 
### What did you do?
We are currently running a Ruby GRPC server in production sitting behind Envoy Proxy's JSON transcoder, which itself sits behind an Amazon ALB. We recently launched to the public and immediately started seeing all kinds of `GRPC::Core::CallError` exceptions at a variety of locations, as well as exceptions in our code from attempting to process unary requests with no actual request object.

My first step was to attempt to reproduce these issues, which I can do by making invalid HTTP 1.1 requests to Envoy Proxy with the following code, which closes the connection before sending the body. (Note that using Envoy's buffer filter can mitigate this specific issue, but other invalid requests still cause problems, like sending the body and immediately closing).

```ruby
require 'socket'

body = <<-END_OF_JSON
{"random":"json"}
END_OF_JSON

headers = {
  'Host' => 'localhost:10000',
  'User-Agent' => 'Bad Ruby',
  'Accept' => '*/*',
  'Content-Type' => 'application/json',
  'Content-Length' => body.length * 2
}

# Build request
request = "POST /some/api/endpoint HTTP/1.1\r\n"
headers.each do |key, value|
  request << "#{key}: #{value}\r\n"
end
request << "\r\n"

# Make request
s = TCPSocket.new('localhost', 10000)
s.write(request)
sleep 2
s.close
```

With the ability to consistently reproduce the issue, I went digging in the Ruby implementation alongside the Python implementation to see if I could see what it was doing that the Ruby implementation wasn't. The first thing I found was that the [Python implementation](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_server.py#L375) doesn't actually run the call if there's no request, in comparison to the [Ruby implementation](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_desc.rb#L51). It also seems like the [Python implementation](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_server.py#L657) checks for connection closes during the initial request read, but I haven't done much digging into exactly how each of the batch ops works, so I could be misreading this. In addition, the [Ruby implementation](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/active_call.rb#L206) for `send_status` does not actually check to see if the call has been cancelled before running the appropriate ops, which seems likely the reason why I'm seeing it throw a `GRPC::Core::CallError` sometimes instead of gracefully ignoring the closed connection.

For my purposes I'm only making unary-unary requests, but if it would help I'd be happy to do some further digging into the other request types. In addition, if it would help I could attempt to reproduce this with an HTTP/2 client rather than a proxied HTTP/1 client. This was easier to reproduce quickly, but it leaves open the possibility that Envoy is doing something so wrong that it couldn't ever happen in real life over HTTP/2 directly.

**Comment by nicolasnoble** [comment]
I'm raising this one to P1 at least, since my initial reading is that this can cause a misbehaving client to crash a Ruby server.

**Comment by warhammerkid** [comment]
Just to clarify, it doesn't cause a "crash" - the exceptions I was able to trigger were all caught before they caused any serious problems to the application server itself. The furthest I've seen the exception go up is the worker thread, which I can get to [complain](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_server.rb#L140), but that doesn't actually break the worker thread. That said, I have no idea if there's required cleanup that is not being performed because it is throwing.

**Comment by nicolasnoble** [comment]
I see, so the exception is caught before it reaches the user code. Good. Otherwise that'd be a big issue, yes.

**Comment by warhammerkid** [comment]
Reviewing the code changes to the Ruby gem since I reported this issue, I don't see any changes that would have addressed this. I still think it would be nice to have this fixed, as it creates very bizarre crash traces depending on where you inject crash tracing (my projects are wrapping `GRPC::RpcDesc#run_server_method` to log exceptions).
