### ISSUE TITLE
Invalid metadata causes crash in gRPC (triggers an assert)

### ISSUE THREAD

**Issue by RahulMitra** [grpc/grpc#18527]
### What version of gRPC and what language are you using?
Language: C++
Version: 1.18.0 
 
### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04.5 LTS
 x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
 
### What did you do? What did you expect to see? What did you see instead?
In gRPC C++, placing invalid metadata causes an assert to be triggered, which is crashing our entire app in production. Here is a repro:

```
    std::string target = "";
    auto grpc_channel = grpc::CreateChannel(target, grpc::InsecureChannelCredentials());
    std::shared_ptr<SeDatastoreRpc::Stub> stub = SeDatastoreRpc::NewStub(grpc_channel);
    auto request = SeDatastoreGetReq();
    auto response = new SeDatastoreObject();

    ClientContext context;
    context.AddMetadata("version", "\272\253\001\000\000\000\000\060\062\071) 2019-01-11 10:08:05 UTC");
    stub->Get(&context, request, response);
``` 

I would expect this to error out gracefully and not crash the app.  But instead, we see a crash from triggering an assert:
 ```
E0326 22:23:55.723905898   18932 call.cc:897]                validate_metadata: {"created":"@1553639035.723888113","description":"Illegal header value","file":"src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":0,"raw_bytes":"ba ab 01 '...'"}
E0326 22:23:55.724043413   18932 call_op_set.h:872]          assertion failed: GRPC_CALL_OK == g_core_codegen_interface->grpc_call_start_batch( call_.call(), ops, nops, core_cq_tag(), nullptr)
Aborted
```

Ideally gRPC would simply discard this invalid metadata and send the RPC without it. Or it would return an error saying that the metadata is invalid. However, I feel that crashing in this case is not ideal.

If this assert absolutely must exist, then perhaps it would be ideal to have an option to silence all asserts at compile time.

**Comment by RahulMitra** [comment]
Any thoughts on this?

**Comment by rmstar** [comment]
You're tripping on the assert because you're using the API incorrectly. 
https://github.com/grpc/grpc/issues/18536#issuecomment-477684270 explains why an assert is required.
