### ISSUE TITLE
C++: Set grpc ssl cipher suite to desired cipher list without using env var 

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#18538]
### What version of gRPC and what language are you using?
 1.12
 
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc6
 
### What did you do?
I want to set GRPC_SSL_CIPHER_SUITES to list of desired ciphers without using env var. Is there a way to pass it to some function. I couldn't find any examples or tests which do so. 
This function `grpc_get_ssl_cipher_suites();` gets ssl cipher suites but it explicitly uses the env var. Is there a way to override this and use my own cipher set?

**Comment by yashykt** [comment]
There doesn't seem to be any other way at the moment. In gRPC Core, we have many configurations that depend on environment variables.
