### ISSUE TITLE
The example cmakefiles aren't working properly under windows 

### ISSUE THREAD

**Issue by Garu94** [grpc/grpc#18537]
It has now been some weeks that I have been trying different procedures to get grpc to work on Windows on the Helloworld example provided.
Now I am, or at least I think, the closest to make it work. I was able to get "only" 3 unresolved externals after getting grpc via vcpkg.
Here it is the erro list:
`1>libprotobuf.lib(libprotobuf.dll) : error LNK2005: "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __thiscall google::protobuf::internal::ArenaStringPtr::GetNoArena(void)const " (?GetNoArena@ArenaStringPtr@internal@protobuf@google@@QBEABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) already defined in helloworld.pb.obj 1>libprotobuf.lib(libprotobuf.dll) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl google::protobuf::internal::GetEmptyStringAlreadyInited(void)" (?GetEmptyStringAlreadyInited@internal@protobuf@google@@YAABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) already defined in helloworld.pb.obj 1>helloworld.grpc.pb.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA) 1>helloworld.pb.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A) 1>helloworld.pb.obj : error LNK2001: unresolved external symbol "bool google::protobuf::internal::proto3_preserve_unknown_" (?proto3_preserve_unknown_@internal@protobuf@google@@3_NA)`

What do you think I'm missing?

**Comment by nicolasnoble** [comment]
This is usually a mismatch in the protobuf library you're using.

**Comment by Garu94** [comment]
> This is usually a mismatch in the protobuf library you're using.

Meaning I compiled the .proto file with a version different from the one I'm including?

**Comment by nicolasnoble** [comment]
Meaning you're using version X of the protobuf library to link while the grpc library you're using is expecting version Y.

**Comment by Garu94** [comment]
> Meaning you're using version X of the protobuf library to link while the grpc library you're using is expecting version Y.

I used the version found in the package downloaded with vcpkg, so I thought that one was the one that grpc library was using. Is this a wrong assumption? How can I know which version is grpc library using, if it's not the one found in the package?

**Comment by nicolasnoble** [comment]
The thing is, we don't own nor publish the vcpkg binary package of grpc, and we have no way of knowing which version it actually requires. The fact protobuf C++ has no stable ABI across minor versions is exactly why we're not distributing binary versions of neither protobuf nor grpc, and why we always recommend building from sources. Using a prebuilt library for the C++ version of grpc and protobuf isn't recommended for this reason.

**Comment by Garu94** [comment]
> The thing is, we don't own nor publish the vcpkg binary package of grpc, and we have no way of knowing which version it actually requires. The fact protobuf C++ has no stable ABI across minor versions is exactly why we're not distributing binary versions of neither protobuf nor grpc, and why we always recommend building from sources. Using a prebuilt library for the C++ version of grpc and protobuf isn't recommended for this reason.

Ok, I understand, thank you very much. I'll give another try to build everything from source as soon as I can, even if I have been trying for weeks without success, for a problem or for another. It seems really hard to make grpc work on Windows.

**Comment by nicolasnoble** [comment]
I routinely use the cmakefile to generate visual studio files and run tests there. This is how we run tests per-pull request, and in our CI, and is our recommended way of building. Have you seen our building instructions at https://github.com/grpc/grpc/blob/master/BUILDING.md ?

**Comment by Garu94** [comment]
I already did, but I'm trying again to follow that instructions. During the build, I have some stuff labeled as "not found", and some tests that fail to compile and other that fail. Though, the cmake generation seems to succeed, outputting the file to the .build folder. After that, the `cmake --build . --config Release` seems to perform with success, with 160 warnings and 0 errors.

But, when I then try to make the HelloWorld example from the provided CMakeLists.txt, I get this error:
`CMake Error at C:/extlibs/grpc/.build/gRPCConfig.cmake:8 (include):
  include could not find load file:

    C:/extlibs/grpc/.build/gRPCTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:73 (find_package)`

after setting the path of grpc-DIR and protobuf-DIR to their config.cmake files.
If I try, instead, to add the greater_server.cc and the output files of `protoc.exe --cpp_out, protoc.exe --grpc_out` to a solution created from scratch, including zlib.lib, grpc++_unsecure.lib, libprotobuf.lib and cares.lib (these were, as I understood, the required libraries, aren't they?), I still get these 5 unresolved externals (this time, the libraries are the one built from sources from the guide you linked)
`1>grpc++_cronet.lib(byte_buffer_cc.cc.obj) : error LNK2005: "public: class grpc::ByteBuffer & __thiscall grpc::ByteBuffer::operator=(class grpc::ByteBuffer const &)" (??4ByteBuffer@grpc@@QAEAAV01@ABV01@@Z) already defined in helloworld.grpc.pb.obj
1>greeter_server.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
1>helloworld.pb.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
1>helloworld.grpc.pb.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA)
1>helloworld.pb.obj : error LNK2001: unresolved external symbol "public: virtual unsigned char * __thiscall google::protobuf::MessageLite::InternalSerializeWithCachedSizesToArray(unsigned char *)const " (?InternalSerializeWithCachedSizesToArray@MessageLite@protobuf@google@@UBEPAEPAE@Z)
1>helloworld.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::AssignDescriptors(struct google::protobuf::internal::AssignDescriptorsTable *)" (?AssignDescriptors@internal@protobuf@google@@YAXPAUAssignDescriptorsTable@123@@Z) referenced in function "public: virtual struct google::protobuf::Metadata __thiscall helloworld::HelloReply::GetMetadata(void)const " (?GetMetadata@HelloReply@helloworld@@UBE?AUMetadata@protobuf@google@@XZ)
1>helloworld.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::AddDescriptors(struct google::protobuf::internal::DescriptorTable *,void (__cdecl*const *)(void),int)" (?AddDescriptors@internal@protobuf@google@@YAXPAUDescriptorTable@123@PBQ6AXXZH@Z) referenced in function "void __cdecl AddDescriptors_helloworld_2eproto(void)" (?AddDescriptors_helloworld_2eproto@@YAXXZ)`

**Comment by nicolasnoble** [comment]
Right, that's fair. Our examples might not be the best thing at the moment.

**Comment by Garu94** [comment]
So, which are the libraries to include to make it work? As I said, I tried to include zlib, cares, grpc++_unsecure and libprotobuf but without success

**Comment by Garu94** [comment]
I mean, would it be possible at least to provide a list of libraries to be included?

**Comment by jtattermusch** [comment]
See the C++ usage instructions here: 
https://github.com/grpc/grpc/tree/master/src/cpp#cmake (for each of the ways of installing there's a link to a cmake buildfile).
For these methods of including gRPC in your project, we also have a continuous tests that verify that it's buildable (and installable) - and those tests are green.
See scripts here: https://github.com/grpc/grpc/tree/master/test/distrib/cpp and compare what you're doing step by step - you might find the reason why things are not working for you.

**Comment by Garu94** [comment]
> But, when I then try to make the HelloWorld example from the provided CMakeLists.txt, I get this error:
> `CMake Error at C:/extlibs/grpc/.build/gRPCConfig.cmake:8 (include):
> include could not find load file:
> 
> 
> C:/extlibs/grpc/.build/gRPCTargets.cmake
> 
> Call Stack (most recent call first):
> CMakeLists.txt:73 (find_package)`

I tried building the Helloworld exampel project from the cmake provided in the master branch,helloworld example folder, but this was the outcome.


Instead, when I try running the .bat file you linked to, here's the error I get:

'Import-Module : The specified module 'C:\vcpkg-master\scripts\posh-vcpkg' was not loaded because no valid module file
was found in any module directory.
At C:\Users\simone.garuglieri\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:2 char:1
+ Import-Module 'C:\vcpkg-master\scripts\posh-vcpkg'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\vcpkg-master\scripts\posh-vcpkg:String) [Import-Module], FileNo
   tFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand'

**Comment by Garu94** [comment]
Any new clue about what I am missing?

**Comment by jtattermusch** [comment]
Which .bat file did you try to run?
https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.bat or https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake_as_externalproject.bat?
The log you provided seems to be complaining about vcpkg problems and that seems to be completely unrelated to any of those two scripts, so it doesn't seem you're repeating the steps from those .bat files.

**Comment by Garu94** [comment]
Here are the [errors ](https://imgur.com/a/7YE64Et)I was talking about, though it seems to finish all the builds with success.
At the end, I have the .exes of greeter_server and greeter_client, and finally it seems they are working! Thank you very much for your patience!  Even if I'm thinking it will be a pain in the back to integrate this beautiful stuff in my project.

**Comment by jtattermusch** [comment]
> Here are the [errors ](https://imgur.com/a/7YE64Et)I was talking about, though it seems to finish all the builds with success.
> At the end, I have the .exes of greeter_server and greeter_client, and finally it seems they are working! Thank you very much for your patience! Even if I'm thinking it will be a pain in the back to integrate this beautiful stuff in my project.

Those errors seem only to be related to using powershell  to download OpenSSL library a URL, they  they have little to do with the actual cmake build (any way of downloading works).

Glad that your issue was resolved, feel free to share what the actual problem was and how you resolved it - it might help others trying to do the same thing.

**Comment by Garu94** [comment]
> > Here are the [errors ](https://imgur.com/a/7YE64Et)I was talking about, though it seems to finish all the builds with success.
> > At the end, I have the .exes of greeter_server and greeter_client, and finally it seems they are working! Thank you very much for your patience! Even if I'm thinking it will be a pain in the back to integrate this beautiful stuff in my project.
> 
> Those errors seem only to be related to using powershell to download OpenSSL library a URL, they they have little to do with the actual cmake build (any way of downloading works).
> 
> Glad that your issue was resolved, feel free to share what the actual problem was and how you resolved it - it might help others trying to do the same thing.

At this point I think it was about some missing dependencies, here is the list of all the include folders and lib that are linked in the cmake build and all the configuration stuff to make it work, maybe they could be useful for others: 

Additional Include Directories
`     C:\extlibs\grpc\examples\cpp\helloworld\cmake\build
     C:\extlibs\grpc\testinstall\include`

Preprocessor Definition
`    _WIN32_WINNT=0x600`

Additional Dependencies
`    C:\extlibs\grpc\testinstall\lib\grpc++_unsecure.lib
    C:\extlibs\grpc\testinstall\lib\libprotobuf.lib
    C:\extlibs\grpc\testinstall\lib\grpc_unsecure.lib
    C:\extlibs\grpc\testinstall\lib\gpr.lib
    C:\extlibs\grpc\testinstall\lib\zlib.lib
    C:\extlibs\grpc\testinstall\lib\cares.lib
    C:\extlibs\grpc\testinstall\lib\address_sorting.lib
    wsock32.lib
    ws2_32.lib
    kernel32.lib
    user32.lib
    gdi32.lib
    winspool.lib
    shell32.lib
    ole32.lib
    oleaut32.lib
    uuid.lib
    comdlg32.lib
    advapi32.lib`
