### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhangmiaowater** [grpc/grpc#18533]
### What version of gRPC and what language are you using?
 1.19.1
 
### What operating system (Linux, Windows,...) and version?
 CentOS Linux release 7.5.1804 (Core)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 when i type "make" command , show error like:
 make: *** No rule to make target `/usr/local/src/grpc/objs/opt/third_party/cares/cares/ares_strsplit.o', needed by `/usr/local/src/grpc/libs/opt/libares.a'.  Stop.
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by apolcyn** [comment]
One thing that sticks out here is that `ares_strsplit.c` is added in c-ares 1.15 release, and the 1.19.1 grpc release is pinned to the 1.13 c-ares release, at least in it's submodule.

I want to say that what's happening here is a "submodule build", but against a different version of c-ares than the grpc Makefile is meant to do a submodule build against.

How exactly are you compiling? Did you run `git submodule update`?
