### ISSUE TITLE
grpc_server share port with web_server

### ISSUE THREAD

**Issue by figodeng** [grpc/grpc#18531]
### What version of gRPC and what language are you using?
 
 1.17.1
### What operating system (Linux, Windows,...) and version?
 windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Csharp
 
### What did you do?
start grpc_server hosted by a web server. the web server monitor a port for http request, when i start the grpc server, need to prepare a new port. confused with it.

 
### What did you expect to see?
 grpc_server can share port with web_server

**Comment by jtattermusch** [comment]
gRPC is a standalone server and it cannot share the same port with other web servers (the implementation is a completely different stack).

If you're using ASP.NET Core, you might be interested in https://github.com/grpc/grpc-dotnet (note that the new implementation is not production-ready).
