### ISSUE TITLE
Distribution Tests Linux (standalone subset) failed to get packages from ftp.debian.org

### ISSUE THREAD

**Issue by guantaol** [grpc/grpc#18548]
https://source.cloud.google.com/results/invocations/29f122f1-ff17-4f5b-88db-45f05813da2d/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_distribtests_standalone/log

It looks like that the distribution test has problems in getting packages from ftp.debian.org.

```
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

404  Not Found
```

**Comment by jtattermusch** [comment]
This might be related to https://github.com/grpc/grpc/issues/18477.
