### ISSUE TITLE
ALPN setting no longer checked as of 1.17.0

### ISSUE THREAD

**Issue by f3nry** [grpc/grpc#18549]
### What version of gRPC and what language are you using?

Versions of gRPC after 1.17.0 in Ruby are no longer checking the ALPN setting as advertised by the peer, using default channel credentials.
 
### What operating system (Linux, Windows,...) and version?

Ubuntu, MacOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby 2.5.3. 

### What did you do?

We use AWS ELB in SSL/TCP mode to proxy gRPC traffic. Prior to gRPC version 1.17.0, connections failed with the following error:

```
Connect failed: {"created":"@1553715424.830762000","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/s
ecurity_connector.cc","file_line":869}
```

The service is used with very minimal defaults.

```
creds = GRPC::Core::ChannelCredentials.new
stub = Service::Stub.new("<elb>:443", creds)
```

`openssl s_client` shows `No ALPN negotiated`, which is expected.
 
### What did you expect to see?

After 1.17.0, we expected the connection to still fail. I don't see anything in the release notes about this either.

It would be great if the ALPN verification was a runtime setting for Ruby, similar to how the Go libraries expose an option for constructing the [raw TLS configuration](https://godoc.org/google.golang.org/grpc/credentials#NewTLS).
 
### What did you see instead?
 
The connections successfully negotiate SSL after 1.17.0, through 1.19.0 even with missing ALPN.
 
### Anything else we should know about your project / environment?

We normally use a proxy to get around this behavior, but noticed that this suddenly started working.

This code seems to be under constant refactoring in the past few versions of gRPC. Would this potentially be related? https://github.com/grpc/grpc/commits/master/src/core/lib/security/security_connector/ssl/ssl_security_connector.cc

**Comment by jiangtaoli2016** [comment]
@yihuazhang maybe you can take a look? It may be related to your refactoring of ssl_security_connector

**Comment by yihuazhang** [comment]
@jiangtaoli2016 The problematic PR that did refactoring has been reverted in #18469. 
Based on the error log, the security connector linked to the version of gRPC before 1.17.0 (the one outputs expected behavior) is the one before https://github.com/grpc/grpc/pull/16963 gets merged. 

@f3nry, could you please elaborate your use case in more details so that I can reproduce it?

**Comment by f3nry** [comment]
@yihuazhang we were just surprised that gRPC core after 1.17 is no longer validating the ALPN protocol with default channel credentials. 

Is this something we would be able to rely on at this point or will the behavior revert at some point? It would be great if this validation was a bit more lax, as we run a layer 4 TCP proxy between gRPC services that doesn't advertise ALPN.

**Comment by mdehoog** [comment]
Agree with @f3nry. Prior to 1.17 we were unable to connect to a gRPC service running behind a layer 4 AWS CLB with anything other than Go clients (possibly related: #9991). After 1.17 Ruby clients can now connect fine. Our preference would be that we can continue to connect with these C++ backed clients, but perhaps with an opt-in or opt-out of ALPN verification.
