### ISSUE TITLE
Feature Request: callback/co-routine based async model for C++ api's

### ISSUE THREAD

**Issue by sumukhs** [grpc/grpc#18550]
Hi,

This is a feature suggestion for the async programming model in gRPC.

The C# API's for the proto files consist of Task based client and server API's in the generated code - which allows for "await client->MethodAsync" to be invoked without blocking the thread.

For C++ though, I do not see this paradigm. The only available option seems like a polling based mechanism on a completion queue. I did notice a method named "AsyncNext" added by @vjpai , but again we need to provide a deadline and if there is a timeout, there is no good value to provide as the parameter the next time we need invoke the method as the caller has no idea how long it would take for the work to be done.

I am new to async programming patterns on linux environments and am wondering if I am missing something obvious. On windows, we have always passed callbacks in async API's. These callbacks are invoked by the callee with a context when the API is completed. This way, we never need to poll to check if the work is completed or not. Cancellations and timeouts are handled similarly as well.

In the C# API mentioned above, the await key word in .NET creates an implicit callback and yields the thread until the callback is ready to run. The new C++ standards (C++20) have also approved the coroutines into the standards and are expected to release it in the coming year.

Is there a reason the gRPC C++ API's were not designed this way? Any history or context would help greatly!

Thanks,
Sumukh

**Comment by mikedanese** [comment]
Is this covered by the callback APIs?

https://github.com/grpc/grpc/blob/d418c42f1ef2f433df54aaee42c75f8d58742927/include/grpcpp/impl/codegen/client_callback.h#L43-L50

Original issue https://github.com/grpc/grpc/issues/7352

**Comment by sumukhs** [comment]
Is there a unit test I can take a look at for the usage?

**Comment by mikedanese** [comment]
https://github.com/grpc/grpc/blob/9c882bc7253a91262d662409453c5fc70b019d20/test/cpp/end2end/client_callback_end2end_test.cc#L201-L218

**Comment by sumukhs** [comment]
Makes sense.. Thanks for the pointer. Is there a similar one for the server processing requests using the callbacks?

The only test I found was for a generic bidirectional server. Is the unary version located anywhere else?

https://github.com/grpc/grpc/blob/96f8b7a532006e4c7908828a336a7217123724f1/test/cpp/end2end/hybrid_end2end_test.cc#L800-L834

**Comment by karthikravis** [comment]
Callback API is currently is not supported since there is no polling engine available for it yet. There is ongoing work to enable a polling engine for the Callback API. Till then this API is not supported.
