### ISSUE TITLE
Use of google/benchmark@v1.4.1 is not compatible with CMake < 3.6

### ISSUE THREAD

**Issue by chwarr** [grpc/grpc#18559]
### What version of gRPC and what language are you using?
 
gRPC++ as of commit 4e1a89c
 
### What operating system (Linux, Windows,...) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
clang 3.8.0
 
### What did you do?

Attempted to build gRPC with CMake version 3.5.1.

### What did you expect to see?
 
Successful build.
 
### What did you see instead?

During CMake Makefile generation:

> CMake Error at thirdparty/grpc/third_party/benchmark/src/CMakeLists.txt:14 (list):
  list does not recognize sub-command FILTER

### Proposed fix

Update google/benchmark to a commit after https://github.com/google/benchmark/commit/505be96ab23056580a3a2315abba048f4428b04e, as this has been fixed upstream. There isn't a tagged release later than v1.4.1, though.

I'm happy to submit this fix as a PR if we can agree on a commit. I propose https://github.com/google/benchmark/commit/6a5c379cafef3b49314b600bec6a928ebb2f209a, the current commit as of opening this issue.
 
### Background

The CMake command `list(FILTER...)` was added in CMake 3.6. gRPC's CMakeLists.txt says that CMake 2.8 or newer is required.

**Comment by chwarr** [comment]
I have a fix for this issue, but it is blocked on a different problem with the CMake build: the upb library's include headers aren't set up correctly. I've started a fix for that in https://github.com/grpc/grpc/pull/18984, but I need someone to review and merge that before I can submit the fix for this issue.

**Comment by chwarr** [comment]
My fix for this is still blocked on getting #18984 reviewed.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/19384 should unblock you.

Btw the minimum CMake version required by protobuf is 3.1.3, so there's probably no point of supporting anything older.
https://github.com/protocolbuffers/protobuf/blob/f2a919f58f12574ac04ca79e6b84577dec6f2b43/cmake/CMakeLists.txt#L2
Our distribtests on linux currently test with cmake 3.6 (which is what's available in jessie backports)

**Comment by chwarr** [comment]
Thanks. I'll try to get this working with CMake 3.1. If not, 3.6 seems like an OK minimum version.
Ubuntu 16.04 LTS has CMake 3.5 FWIW.

**Comment by chwarr** [comment]
* I [started a PR to change the benchmark version to work with CMake <3.6](https://github.com/grpc/grpc/pull/19466).
* I [started a PR to change the minimum CMake version to 3.1.3](https://github.com/grpc/grpc/pull/19467).

**Comment by jtattermusch** [comment]
We ended up bumping to google/benchmark 3.5.0 in https://github.com/grpc/grpc/pull/19535/files, so seems this can be closed?

**Comment by chwarr** [comment]
Yes, #19535 is a fix for this. Closing.
