### ISSUE TITLE
Variables in generated code can't start from digit

### ISSUE THREAD

**Issue by telezhnaya** [grpc/grpc#18568]
### What version of gRPC and what language are you using?
 Version: 1.19.0 + Python 3.5
 
### What operating system (Linux, Windows,...) and version?
 
Ubuntu 18.04.1 LTS
 
### What did you do?

I just created simple proto file with name `1.proto` and generated the code.
 
### What did you expect to see?
 
Correct code
 
### What did you see instead?

Incorrect syntax: some variable names start from digit (`1`). I compared my code with official example, and yes: these variables are using filename for naming. I guess you need to make checks if the variable name is correct for chosen language. I also suppose that it's not only Python issue, digits at the beginning of variable names are prohibited in most of the programming languages. 
 
Generated code (incorrect):
```
rpc_method_handlers = {
      'GetMode': grpc.unary_unary_rpc_method_handler(
          servicer.GetMode,
          request_deserializer=1__pb2.Empty.FromString,
          response_serializer=1__pb2.SystemMode.SerializeToString,
      ),
  }
```

**Comment by telezhnaya** [comment]
It's not hard to guess that the problem is wider. Try also `%.proto` or `a b.proto` (with space). These examples are synthetic, but the first one (with digit) was just my real attempt to try GRPC.

**Comment by nicolasnoble** [comment]
This isn't a grpc issue, but a protobuf issue.

**Comment by yashykt** [comment]
Closing this since this needs to be tracked in the protobuf repository instead.

**Comment by telezhnaya** [comment]
@yashykt  Yes, thanks, I have already done it and forgot to close this one.
