### ISSUE TITLE
C++ grpc client not able to connect with wildcard in cert

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#18566]
### What version of gRPC and what language are you using?
 1.16
 
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc6
 
### What did you do?
I am trying to connect to a server which has generic wildcard cert with CN=*.example.com. Unable to connect to the server with GRPC debug logs stating:
E0322 08:56:35.814190388     154 ssl_transport_security.cc:1227] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
 
Error code: 14
Error message: Connect Failed
### What did you expect to see?
 Successful Connection
 
Is this a known issue with the grpc C++ similar to https://github.com/grpc/grpc-node/issues/663 ?

**Comment by nicolasnoble** [comment]
Please provide a full reproduction case for us.

**Comment by nicolasnoble** [comment]
Note that the error you are getting can stem from a lot of other issues with your actual certificate. Without seeing the certificate nor the actual sequence of things you are doing or error you are getting, this will be impossible to debug and help you with.

**Comment by lucifercr07** [comment]
Thanks @nicolasnoble for quick response. Issue was with the certs being bundled by server.
