### ISSUE TITLE
Check validity of server port

### ISSUE THREAD

**Issue by TorbenJ** [grpc/grpc#18569]
### What version of gRPC and what language are you using?
 gRPC 1.19.0, C#
 
### What operating system (Linux, Windows,...) and version?
 Linux/Windows 10

### What did you do?
Create a new `ServerPort` instance with invalid port.  
`new ServerPort("0.0.0.0", 500051, ServerCredentials.Insecure)`  
(Notice the invalid port value)
 
### What did you expect to see?
 `OutOfRangeException` or `ArgumentException` maybe
 
### What did you see instead?
No error at all during start of the server.  
As soon as I connected with my client, the client got a `RpcException`  
`Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")`  
This was not really helpful because I initially thought that this might be some issue with Docker but I never expected it to be an issue with the server socket itself.  

I guess API-wise it would be the easiest to take a `ushort` instead of `int` for the port value as this prevents to pass an invalid port value.  
As this breaks the API there should be some validation in the constructor instead that throws an exception if the port value is invalid.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by nicolasnoble** [comment]
This behavior is unfortunately consistent with the `getaddrinfo` API. In fact, in `getaddrinfo`, the `service` parameter is a whole string, which can wrap around without leaving any error:

```
$ cat getaddrinfo.c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <memory.h>

int main() {
    struct addrinfo hints;
    struct addrinfo * info = NULL;
    memset(&hints, 0, sizeof hints);

    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags =  AI_CANONNAME | AI_NUMERICSERV;

    int s = getaddrinfo("localhost", "500051", &hints, &info);
    if (s != 0) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(s));
        return -1;
    }

    if (info->ai_addr->sa_family != AF_INET) {
        fprintf(stderr, "Wrong family\n");
        return -1;
    }

    struct sockaddr_in * addr = (struct sockaddr_in *) info->ai_addr;


    printf("port: %i\n", ntohs(addr->sin_port));

    freeaddrinfo(info);
    return 0;
}
$ gcc -o getaddrinfo getaddrinfo.c
$ ./getaddrinfo
port: 41299
```

Therefore, this behavior is consistent across the board in every languages, and consistent with what the operating system allows and does. Closing this one.
