### ISSUE TITLE
Build error with GCC 8.2.1: -Werror=class-memaccess being thrown

### ISSUE THREAD

**Issue by minddrive** [grpc/grpc#18565]
### What version of gRPC and what language are you using?

 master, C/C++ 
 
### What operating system (Linux, Windows,...) and version?

 RHEL 8
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 GCC 8.2.1

### What did you do?

 Checked out master branch, ran 'make install'
 
### What did you expect to see?
 
 A successful build

### What did you see instead?
 
[CXX]     Compiling src/core/lib/transport/transport.cc
src/core/lib/transport/transport.cc: In function 'grpc_transport_op* grpc_make_transport_op(grpc_closure*)':
src/core/lib/transport/transport.cc:264:36: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'grpc_transport_op' {aka 'struct grpc_transport_op'}; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(&op->op, 0, sizeof(op->op));
                                    ^
In file included from src/core/lib/transport/transport.cc:21:
./src/core/lib/transport/transport.h:274:16: note: 'grpc_transport_op' {aka 'struct grpc_transport_op'} declared here
 typedef struct grpc_transport_op {
                ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[4]: *** [Makefile:2916: /tmp/grpc/objs/opt/src/core/lib/transport/transport.o] Error 1
make[4]: *** No rule to make target 'install'.  Stop.
 
### Anything else we should know about your project / environment?

Standard environment within RHEL 8, no customizations.

### Additional notes

 I've seen quite a few tickets related to the new strictness of GCC 8.x, but unfortunately nothing in particular that will help with this specific error.

**Comment by yashykt** [comment]
Closing this as per https://github.com/grpc/grpc/issues/17369#issuecomment-480970347
