### ISSUE TITLE
iphone5 ios8 Change NetWork is Crash

### ISSUE THREAD

**Issue by lubaoyilang** [grpc/grpc#18567]
### What version of gRPC and what language are you using?
 
Objective-c
 
### What operating system (Linux, Windows,...) and version?
 
iOS 8.0    Iphone5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

Crash Log

2019-03-29 15:13:25.319 teacher[1266:92727] -[UIImageView connectivityChanged:]: unrecognized selector sent to instance 0x14ff1130
2019-03-29 15:13:59.490 teacher[1266:92727] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView connectivityChanged:]: unrecognized selector sent to instance 0x14ff1130'
*** First throw call stack:
(0x2a99de3f 0x3804bc8b 0x2a9a3189 0x2a9a10a7 0x2a8d3208 0x2a9564a1 0x2a8b293d 0x2b5e29b9 0x2b5e751f 0x21fcb7b 0x2dde49c7 0x2a96458f 0x2a96399f 0x2a962005 0x2a8b0621 0x2a8b0433 0x31c5e0a9 0x2de9a809 0xc752b 0x385cbaaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by muxi** [comment]
`UIImageView` does not look like a gRPC class. Did you register some other object to the notification center with name `kGRPCConnectivityNotification` in your app? Did you try another version of iOS and saw it worked?

**Comment by HarrisonXi** [comment]
In iOS8, we must remove notification observer before the observer instance's dealloc.
In GRPCCall class, the codes only add notification observer but not remove it.
