### ISSUE TITLE
Problems building grpcio tarball from PyPI

### ISSUE THREAD

**Issue by danieldk** [grpc/grpc#18570]
### What version of gRPC and what language are you using?

 1.18.0, 1.19.0
 
### What operating system (Linux, Windows,...) and version?
 
macOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 2.7 and Python 3.7 

### What did you do?

Build the grpc Python module with nixpkgs.

### What did you expect to see?

A succesful compile. 
 
### What did you see instead?
 
We have encountered build failures with the grpc Python module in nixpkgs on Darwin (macOS). Builds fail with:

~~~
The target you are trying to run requires an OpenSSL implementation.
Your system doesn't have one, and either the third_party directory
doesn't have it, or your compiler can't build BoringSSL.
~~~ 

Log: https://hydra.nixos.org/build/90316360/nixlog/1

When digging a bit deeper, it turns out that the check that verifies whether BoringSSL can be compiled fails. The reason is that the source tarball that is provided through PyPI does not include the `test` directory, whereas `test/build/boringssl.c` is required for this check.

If we instead build the module from the grpc repository rather than the PyPI source tarball, the module compiles as expected.

### Anything else we should know about your project / environment?

nixpkgs issue/PR: nixos/nixpkgs#58456
For reference, the successful build log: https://logs.nix.ci/?key=nixos/nixpkgs.58456&attempt_id=cba0120a-d6e7-482d-9894-436a42de77d7

**Comment by nicolasnoble** [comment]
Nice find.
