### ISSUE TITLE
Python Rendezvous exception when running python server, multithreaded python client and C++ subprocess

### ISSUE THREAD

**Issue by negralexx** [grpc/grpc#18626]
### What version of gRPC and what language are you using?
Python gRPC 1.19.0
 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7
 
### What did you do?
See instructions below to reproduce the following _Rendezvous exception:
```
File "C:\Python27\lib\site-packages\grpc\_channel.py", line 549, in __call__
   return _end_unary_response_blocking(state, call, False, None)
File "C:\Python27\lib\site-packages\grpc\_channel.py", line 466, in _end_unary_response_blocking
   raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with:
   status = StatusCode.UNKNOWN
   details = "Stream removed"
   debug_error_string = "{"created":"@1554290961.920000000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Stream removed","grpc_status":2}"
```

Follow this steps to get the above exception:
- Unzip the attached ReproduceGRPCIssue.zip
- Go to the BreakGRPC folder and compile BreakGRPC.sln. Make sure BreakGRPC.exe is saved in BreakGRPC/x64/Release.
- Go to the Services/src folder and open two command prompts there.
- Run "python GRPCserver.py" in one command prompt.
- Run "python GRPCclient.py" in the other command prompt.

[ReproduceGRPCIssue.zip](https://github.com/grpc/grpc/files/3038385/ReproduceGRPCIssue.zip)
 

See this post on the google group for more background information:
https://groups.google.com/forum/#!msg/grpc-io/fmYzH6iHw2E/IVp2H54EBgAJ

**Comment by MrBents** [comment]
Same issue here on python 3.5... No luck so far.

**Comment by negralexx** [comment]
Hi @gnossen, is there any update on this? Thanks.
