### ISSUE TITLE
c# how to set grpc request/response timeout

### ISSUE THREAD

**Issue by Jesse1205** [grpc/grpc#18622]
### What version of gRPC and what language are you using?
 request/response
 
### What operating system (Linux, Windows,...) and version?
 windows 

### What runtime / compiler are you using (e.g. python version or version of gcc)
 c#
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 set request time out
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
It isn't appropriate to file questions like this as github issues, but
https://github.com/grpc/grpc/blob/119be19126ef16ac41859e5e1e88a69fcd644bed/src/csharp/Grpc.Core.Api/CallOptions.cs#L43
