### ISSUE TITLE
Improve the compression code/doc

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#18638]
It's not very clear how we do the compression..

We need to at least improve the docs to clarify the spec.

https://github.com/grpc/grpc/blob/master/doc/compression.md
https://github.com/grpc/grpc/blob/master/doc/compression_cookbook.md

1. https://github.com/grpc/grpc/blob/master/doc/compression_cookbook.md
The last diamond in the first flow chart checks that the grpc-encoding of the incoming message is present in the grpc-accept-encoding of the same incoming message. But do we really need this check if the compression is asymmetric as said in https://github.com/grpc/grpc/blob/master/doc/compression.md.

2. Clarify how to set the compression algorithm. There are several ways to do that. We need to clarify the priority.

3. Clarify "Message-Accept-Encoding" in https://github.com/grpc/grpc/blob/master/doc/compression.md.

**Comment by nicolasnoble** [comment]
Sadly, I can't assign @dgquintas on this one.

**Comment by AspirinSJL** [comment]
cc @muxi

**Comment by jtattermusch** [comment]
cc @jtattermusch

**Comment by jtattermusch** [comment]
One more item:

while implementing compression for grpc-dotnet (in https://github.com/grpc/grpc-dotnet/pull/125), there was some confusion around the fact that the algorithm of request compression is fully independent of the algorithm used for response compression (which is the case, but it could be specified more clearly in the spec to avoid confusion).

**Comment by AspirinSJL** [comment]
still wanted
