### ISSUE TITLE
Streaming example requires the same fix as callback

### ISSUE THREAD

**Issue by sheenaqotj** [grpc/grpc#18634]
https://github.com/grpc/grpc/blob/da76faf2b882ba1e07bd52379bfb8eba8354155c/examples/cpp/route_guide/route_guide_server.cc#L150

We need to use a shared thread-safe list, not a local variable for this codelab to be meaningful.

**Comment by AspirinSJL** [comment]
https://github.com/grpc/grpc/pull/18460 is fixing it.
