### ISSUE TITLE
Lonely completion queue crash.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1863]
I create a cq, cq->shutdown() and then cq->next(). Expected behavior is that next immediately returns with SHUTDOWN event. Instead, it crashes.

E0601 17:55:24.358835176   14718 sync_posix.c:48] assertion failed: pthread_mutex_lock(mu) == 0

	/usr/bin/cli() [0x4b73d8]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f7a6ea81340]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f7a6e6e2cc9]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f7a6e6e60d8]
	/usr/local/lib/libgpr.so.0(gpr_mu_lock+0x4a) [0x7f7a6a761060]
	/usr/local/lib/libgrpc.so.0(grpc_completion_queue_next+0x35) [0x7f7a6a351a0e]
	/usr/local/lib/libgrpc_csharp_ext.so(grpcsharp_completion_queue_next+0x29) [0x7f7a6a96918d]
	[0x41d20858]

My C# code:
var cq = CompletionQueueSafeHandle.Create();
cq.Shutdown();
var ev = cq.Next();
cq.Dispose();

**Comment by ctiller** [comment]
The pull request attached performs said operations on a completion queue - and doesn't crash.
Can you take a look at it and see if I missed anything?

**Comment by jtattermusch** [comment]
After, doing more investigation, I realized this was caused by imbalanced stack after P/Invoke call with a wrong signature. I'm not sure exactly it could cause this issues, but it clearly did. So this issue is a false alarm, sorry about that.
