### ISSUE TITLE
Interop matrix docker build error

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#18646]
Interop matrix docker builds are failing due to amd64 pkgs not found. Here is the log:

----------

Step 8/10 : RUN apt-get update && apt-get -y install libgflags-dev libgtest-dev libc++-dev clang && apt-get clean
 ---> Running in 44689cac932b
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Hit http://deb.debian.org jessie Release.gpg
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Ign http://deb.debian.org jessie-updates Release.gpg
Hit http://deb.debian.org jessie Release
Ign http://deb.debian.org jessie-updates Release
Get:3 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Fetched 9968 kB in 31s (314 kB/s)
Removing intermediate container 44689cac932b
The command '/bin/sh -c apt-get update && apt-get -y install libgflags-dev libgtest-dev libc++-dev clang && apt-get clean' returned a non-zero code: 100
+ exit 100
FAILED: build_docker_cxx [ret=100, pid=152895, time=46.9sec]
FAILED: Failed to build interop docker images.

**Comment by srini100** [comment]
@jtattermusch, @nicolasnoble have you seen this error before?

**Comment by jtattermusch** [comment]
@murgatroid99  is this possibly the same problem we had in https://github.com/grpc/grpc/pull/18530/files?

**Comment by jtattermusch** [comment]
Can this be closed?

**Comment by srini100** [comment]
@jtattermusch, how did this get fixed?

**Comment by jtattermusch** [comment]
@srini100  ah, I thought the cherrypick #18662 was the fix - turns out it's something else. Do you have a PR with interop_matrix additions you're trying to do?

**Comment by srini100** [comment]
@jtattermusch, I tried to create interop images for 1.19.1. It failed with above error. It works fine for 1.20.0-pre1, so I think something broke on 1.19.x branch or not backported from master. I will be releasing 1.19.2 this week. Is it fine to leave the interop at 1.19.0?

**Comment by jtattermusch** [comment]
@srini100  the differences between v1.19.0 and v1.19.1 seem very minimal (https://github.com/grpc/grpc/compare/v1.19.0..v1.19.1) so the risk of not updating to v1.19.1 seems pretty low. Considering we are going to push v1.20.x stuff soon (which work), I'd say it's fine to stick with v1.19.0 if building v1.19.1 seems problematic.

**Comment by srini100** [comment]
I was planning to do 1.19.2 to pick up some [backports](https://github.com/grpc/grpc/compare/v1.19.1..v1.19.x) after 1.19.1 but given this issue I will hold off on 1.19.2 unless absolutely needed. Also, 1.20.0 just got released.
