### ISSUE TITLE
Complex object with KnownType attribute C#

### ISSUE THREAD

**Issue by shashi127** [grpc/grpc#18653]
I have my response structure with inherited concept

```
    [Schema]
    [KnownType(typeof(CustomResponse))]
    public class ICustomResponse
    {
        [Id(0)]
        public int Id { get; set; }
    }

    [Schema]
    public class CustomResponse : ICustomResponse
    {
        [Id(1)]
        public int Payload { get; set; }

        [Id(2)]
        public int Output { get; set; }
    }
```

My Return type of the method is ICostomResponse

```
public static Method<CustomRequest, ICustomResponse> Method =
new Method<CustomRequest, ICustomResponse>(.....
```

Implementation would be
```
private static ICustomResponse AddTwoNumbers(CustomRequest additionRequest)
{
return new CustomResponse { Output = additionRequest.X + additionRequest.Y };
}
```

I wants to retrieve actual data returned from the server. But while I receive the response at client end it contains only the ICustomResponse object. Can't convert ICustomRespnse to CustomResponse object.

Is there any way to include [KnownType(typeof(CustomResponse))] while serializing and deserializing the object?

 I refereed sample project and made few changes- https://github.com/Horusiath/GrpcSample

**Comment by jtattermusch** [comment]
Looks like you are using Microsoft Bond as the serialization layer (while the default and recommended serialization format is Google Protobuf) and it also seems that this question is about Bond serialization specifics, not really about gRPC itself, so this is not the right repository to ask the question.  (Perhaps you can ask here https://github.com/Microsoft/bond ?)
