### ISSUE TITLE
Build failed with mingw7.3

### ISSUE THREAD

**Issue by Ludea** [grpc/grpc#18657]
### What version of gRPC and what language are you using?
 grpc 1.19.1 with c++ language
 
### What operating system (Linux, Windows,...) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Mingw 7.3
 
### What did you do?
I try to build grpc on Windows with Cmake and Mingw 7.3
1 - Configure and generate Mingw project into Cmake
2 - Open project and build grpc
 
### What did you expect to see?
 successful build
 
### What did you see instead?
\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm|21|error: invalid size for operand 1|

into Cmake I have these logs :
```-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
```
 
### Anything else we should know about your project / environment?
Host : Win 10 64bits
IDE : C::B

**Comment by LesyaHoy** [comment]
I have the same problem. 
OS Win 10 64 bit
grpc 1.19.1 with c++ language
g++ (Rev2, Built by MSYS2 project) 9.1.0

`md .build
cd .build
cmake .. -G "MinGW Makefiles"
cmake .`

Result:
`[  2%] Generating chacha-x86.asm
Scanning dependencies of target chacha
[  2%] Building C object third_party/boringssl/crypto/chacha/CMakeFiles/chacha.dir/chacha.c.obj
[  2%] Building ASM_NASM object third_party/boringssl/crypto/chacha/CMakeFiles/chacha.dir/chacha-x86.asm.obj
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:21: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:22: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:23: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:24: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:30: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:383: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:384: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:385: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:386: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:392: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:393: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:394: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:395: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:956: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:957: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:958: error: invalid size for operand 1
C:\software\grpc\.build\third_party\boringssl\crypto\chacha\chacha-x86.asm:959: error: invalid size for operand 1
mingw32-make.exe[2]: *** [third_party\boringssl\crypto\chacha\CMakeFiles\chacha.dir\build.make:87: third_party/boringssl/crypto/chacha/CMakeFiles/chacha.dir/chacha-x86.asm.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2897: third_party/boringssl/crypto/chacha/CMakeFiles/chacha.dir/all] Error 2`

Is there any solution for this problem?

**Comment by jtattermusch** [comment]
Please note that we officially only support MSVC for our windows cmake build - all mingw support is at a "best effort" basis. We could accept a one time fix if it's simple and will likely continue to work without being thoroughly tested, but we won't look actively into solving this problem.

**Comment by manhnt9** [comment]
I met this issue too. Please provide applicable patch file for older version since I (and probably other users) use flatbuffers and compatible gRPC version for flatbuffers is 1.15.1. Thank you!

**Comment by manhnt9** [comment]
After adding OPENSSL_NO_ASM to boringssl and apply patch here: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-grpc

I can build GRPC without ASM OpenSSL support. Not sure how much performance is affected though. Do you guys have some links about it?

Btw multiple ssl and benchmark test are failing to build too (this is the same as MacOS that I got around by simply removing CMake code related to tests). I may contribute a patch to disable all tests in case someone just need to build, then we can fix the test compile errors later.

**Comment by manhnt9** [comment]
Oh I've just learned that I can completely replace BoringSSL by remove boringssl folder of third_party folder. Great! BoringSSL is causing other compile errors on MinGW too, type conflicts, alignment error, etc.

**Comment by manhnt9** [comment]
Default libssl and libcrypto can't be used, I had to replace with msys2's openssl in order to link with application. It's all well now. MingGW build works without OpenSSL ASM support.

**Comment by manhnt9** [comment]
Well not exactly, since my OpenSSL is MSYS2's OpenSSL, which should have been built with ASM.

**Comment by jtattermusch** [comment]
FTR, In some scenarios, OPENSSL_NO_ASM can make a big difference (e.g. 10x less throughput in some scenarios).
some additional documentation is https://github.com/grpc/grpc/blob/master/doc/ssl-performance.md

**Comment by zackgalbreath** [comment]
FWIW we added better handling of BoringSSL and OPENSSL_NO_ASM here:

https://github.com/grpc/grpc/pull/21427

Further work would likely be necessary to better support mingw.

**Comment by jtattermusch** [comment]
Closing because we don't officially support mingw build: https://github.com/grpc/grpc/issues/18657#issuecomment-539559023
