### ISSUE TITLE
Travis failure: npm ERR! Failed at the grpc@0.9.0 install script.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1867]
Seen with #1864 
https://travis-ci.org/grpc/grpc/jobs/65019765

The command "gem install bundler" exited with 0.
3.38s$ ./tools/run_tests/prepare_travis.sh
Configuring for disbribution 6356a36510c7c953bcadc005ed23c2e1
gflags-05b155ff59114735ec8cd089f669c4c3d8f59029-opt-prebuilt-6356a36510c7c953bcadc005ed23c2e1.tar.gz ...openssl-3df69d3aefde7671053d4e3c242b228e5d79c83f-opt-prebuilt-6356a36510c7c953bcadc005ed23c2e1.tar.gz ... Found.
protobuf-3e2c8a5dd79481e1d36572cdf65be93514ba6581-opt-prebuilt-6356a36510c7c953bcadc005ed23c2e1.tar.gz ... Found.
The command "./tools/run_tests/prepare_travis.sh" exited with 0.
0.01s$ if [ ! -z "$USE_GCC" ] ; then export CC=gcc-$USE_GCC ; export CXX=g++-$USE_GCC ; fi
The command "if [ ! -z "$USE_GCC" ] ; then export CC=gcc-$USE_GCC ; export CXX=g++-$USE_GCC ; fi" exited with 0.
19.13s$ ./tools/run_tests/run_tests.py -l $TEST -t -j $JOBS -c $CONFIG -s 4.0
START: make
PASSED: make [time=5.3sec]
START: tools/run_tests/build_node.sh
+CONFIG=opt
++dirname tools/run_tests/build_node.sh
+cd tools/run_tests/../..
++pwd
+export CXXFLAGS=-I/home/travis/build/grpc/grpc/include
+CXXFLAGS=-I/home/travis/build/grpc/grpc/include
++pwd
+export LDFLAGS=-L/home/travis/build/grpc/grpc/libs/opt
+LDFLAGS=-L/home/travis/build/grpc/grpc/libs/opt
+cd src/node
+npm install
> grpc@0.9.0 install /home/travis/build/grpc/grpc/src/node
> node-gyp rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
gyp ERR! System Linux 2.6.32-042stab090.5
gyp ERR! command "node" "/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/grpc/grpc/src/node
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm ERR! grpc@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.9.0 install script.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab090.5
npm ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "install"
npm ERR! cwd /home/travis/build/grpc/grpc/src/node
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/grpc/grpc/src/node/npm-debug.log
npm ERR! not ok code 0
FAILED: tools/run_tests/build_node.sh [ret=1, pid=9256]
FAILED: Some tests failed

**Comment by murgatroid99** [comment]
I'm not going to close this yet, but I think it's just the Travis machine sometimes failing to download dependencies.

**Comment by murgatroid99** [comment]
I don't think the occasional `ECONNREFUSED` during installation is something we can fix. I'm going to close this until we have some reason to think otherwise.
