### ISSUE TITLE
GCC 8 issues for v1.20.x

### ISSUE THREAD

**Issue by ius** [grpc/grpc#18689]
### What version of gRPC and what language are you using?

1b488f83 (v.1.20.x)

### What operating system (Linux, Windows,...) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

host: gcc version 8.2.1 20181127 (GCC) 
target: gcc version 8.3.0 (cross, powerpc)

### Anything else we should know about your project / environment?

I'm cross compiling and link against external OpenSSL instead of BoringSSL. Coverage might thus not be 100% for GCC 8.3.0.

### Issues

As requested in https://github.com/grpc/grpc/issues/17369#issuecomment-480970347 by @nicolasnoble

````
src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc: In function ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’:
src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:70:10: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Werror=stringop-truncation]
   strncpy(req->initial_request.name, lb_service_name,
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           GRPC_GRPCLB_SERVICE_NAME_MAX_LENGTH);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
````

Fixed by: https://github.com/grpc/grpc/pull/14452/commits/97252b240664b7cf70dff29643a0ba7c8b5356ec

````
src/cpp/common/channel_filter.cc: In member function ‘grpc_linked_mdelem* grpc::MetadataBatch::AddMetadata(const string&, const string&)’:
src/cpp/common/channel_filter.cc:33:48: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘grpc_linked_mdelem’ {aka ‘struct grpc_linked_mdelem’}; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(storage, 0, sizeof(grpc_linked_mdelem));
                                                ^
In file included from ./src/core/lib/transport/transport.h:34,
                 from ./src/core/lib/channel/channel_stack.h:48,
                 from src/cpp/common/channel_filter.cc:21:
./src/core/lib/transport/metadata_batch.h:33:16: note: ‘grpc_linked_mdelem’ {aka ‘struct grpc_linked_mdelem’} declared here
 typedef struct grpc_linked_mdelem {
                ^~~~~~~~~~~~~~~~~~
````

Fixed by: [5b99a54](https://github.com/grpc/grpc/pull/14452/commits/5b99a5446d6ed861cdd8b8a6d57875ffd3a467ec#diff-dfa72cd859a531cb82278e4c3450b5a3L33) (just channel_filter.cc)

**Comment by nicolasnoble** [comment]
Great, there's more of that. Thanks.

**Comment by zglozman** [comment]
Guys this is somehow totally stupid, this is still broken with gcc8, and the only way i could resolve it is by removing the -Werror flag. I am unclear on what is the status of the pull request, but defacto it does not build with gcc8

**Comment by JakeHedman** [comment]
I'm not able to `npm install` firebase packages anymore due to this error. Anyone know how to use the `-Werror` workaround with npm?

**Comment by dankegel** [comment]
Affects me, too.

**Comment by Triose** [comment]
I tried editing the Makefile in the grpc root directory and commented out all `-Werror` flag.
It works.

**Comment by b00f** [comment]
Change Makefile to not treat warning as error:
`sed -i 's/-Werror/ /g' Makefile`

Look [here](https://github.com/grpc/grpc/issues/18349) for more info

**Comment by salamanders** [comment]
Found this bug after running into the same issue.

Should we be using the sed workaround, or switching away from make? 
(which is easiest? the instructions to install Bazel look like a lot of steps)

**Comment by b00f** [comment]
Using sed is just a workaround. Better use CMake or Bazel. which people love to hate them!

**Comment by travellingprog** [comment]
I was able to install grpc 1.20.3 using gcc 9.3.0 and Node 12.22.4. I'm running Linux Mint 20.2, which is built on top of Ubuntu 20.04
