### ISSUE TITLE
c-ares on Windows failed to search with a .local hostname when expected to

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#18691]
As originally reported by @amitwaisel in [this comment](https://github.com/grpc/grpc/issues/18290#issuecomment-480770740). I'm bringing this issue outside of #18290 since it seems to be a separate problem.

**Comment by apolcyn** [comment]
Hi @amitwaisel, this is likely due to a change made in the 1.19 release to change the DNS resolver implementation from <i>native</i> (i.e. `getaddrinfo`) to <i>ares</i> (an async DNS resolver based on the c-ares library). Also see the `GRPC_DNS_RESOLVER` bullet in https://github.com/grpc/grpc/blob/master/doc/environment_variables.md.

It may be worth trying out the `1.20.0-pre2` release, which depends on an upgraded version of the c-ares library.

Also if it feasible to run your application under the environment variables `GRPC_DNS_RESOLVER=native`, then doing so should fix the problem (that will force use of the native `getaddrinfo` based resolver).

Regarding the channel shutdown upon DNS resolution failure: I don't think that the DNS resolution failure is the <i>cause</i> of the channel getting shut down. DNS resolution failures can cause <i>RPC's</i> to fail, but they shouldn't shut down a channel. In the log that you posted, I can see that calls were made to `grpc_channel_destroy` - I think that this call must have been made by your application?

**Comment by amitwaisel** [comment]
Thank you @apolcyn. I will try the environment-variable-solution and will let you know. 
I will also check the channel shutdown scenario to understand why it happens after the DNS resolve fails.
Just to emphasize - this issue happens every time we try using only the host name, but the DNS is configured with the FQDN - which has the "DNS suffix" that one of the network interfaces has. It's not only `local` suffix.

**Comment by apolcyn** [comment]
Also, what version of Windows is being used here?

> Just to emphasize - this issue happens every time we try using only the host name, but the DNS is configured with the FQDN - which has the "DNS suffix" that one of the network interfaces has. It's not only local suffix.

Sorry, if I understand correctly, you are saying that there is nothing special about the `.local` search domain, and that for you, c-ares is failing to suffix hostnames with any configured search domain?

I think that there's a chance that you are hitting https://github.com/c-ares/c-ares/issues/197, which was fixed in the `1.15` release of c-ares and so would be included in the `1.20.x` releases of grpc - I am keen to find out if the grpc `1.20.x` branch works for you.

**Comment by amitwaisel** [comment]
I am using the latest Windows 10, but it also happened on older Windows 7 machines. I didn't test it on Linux/MacOS yet.
The `1.20.0-pre3` tag is now compiling, it takes some time... (why don't you publish the native build results for the different platforms? 😄). I'll update here once it is built and integrated to our product.

**Comment by apolcyn** [comment]
> Edit 1:
Building with newest protoc generator, creates autogenerated code which does not compile on Visual Studio due to warnings on enum definition:

...
INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min()
INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
warning C4003: not enough actual parameters for macro 'min'

The preprocessor interprets min and max as macros, as they are defined in Windows headers, and the build fails when compiling with treat warnings as errors compiler flag.
To solve this, the autogenerated .pb.h files must be included before other Windows headers.

cc @nicolasnoble about this problem.

> The new c-ares has solved the issue! But, please fix the min/max issue mentioned above before we can migrate to a newer gRPC version (as it messes up our header files)

I am happy to hear, thank you for testing with it!

**Comment by nicolasnoble** [comment]
Please file a separate bug for this. This might even be a protobuf-specific issue. There's definitely not enough context for me to tell here.

**Comment by amitwaisel** [comment]
@nicolasnoble I think the protobuf-related issue happens for any enum defined in the `proto` file, as it is translated to a C++-enum which has the `INT_MIN_SENTINEL_DO_NOT_USE_` and `INT_MAX_SENTINEL_DO_NOT_USE_` internal values which use `min` and `max` keywords in their definition.
On Windows, the public `Windows.h` header defines `min` and `max` as preprocessor macros, which actually expect parameters, thus it makes the protobuf enum definition quite problematic for the compiler.

Take a basic `cpp` file and include Windows' header **before** the autogenerated-protobuf header. It would be something like
```C++
#include <Windows.h>
#include "myproto.pb.h"

int main(int argc, char* argv[]) { return 0; }
```
Try to compile with `/WX` (`treat warnings as errors` MSVC compiler flag) and `/W4` (warning level 4), and then the compiler will raise the warning mentioned above, which will fail the build thanks to the `/WX` flag.
For example, you may get the following warning (which is treated as an error):
> warning C4003: not enough actual parameters for macro 'min'

**Comment by nicolasnoble** [comment]
Which is also an issue when using `std::min` and `std::max` from the `algorithm` standard include, not just when using protobuf. Microsoft eventually added the `NOMINMAX` macro to define before including `windows.h` for this reason exactly. Also works by doing `/D NOMINMAX` on the command-line.

Still, this is a protobuf codegen-related issue, and that's not on grpc.

**Comment by amitwaisel** [comment]
@apolcyn is this still relevant? (not the min/max preprocessor collision, but the c-ares DNS resolver issue). Thank you

**Comment by apolcyn** [comment]
I believe the c-ares DNS resolver issue was fixed, as noted in comment:

```
The new c-ares has solved the issue! But, please fix the min/max issue mentioned above before we can migrate to a newer gRPC version (as it messes up our header files)
```

The min/max preprocess collision was why this was left open

**Comment by amitwaisel** [comment]
Oh, forgot about it 😂 Thank you!
