### ISSUE TITLE
VB.NET Support

### ISSUE THREAD

**Issue by InteXX** [grpc/grpc#18692]
### What version of gRPC and what language are you using?
Latest stable, VB.NET 
 
### What operating system (Linux, Windows,...) and version?
Windows client, Raspbian server
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A
 
### What did you do?
N/A
 
### What did you expect to see?
N/A 
 
### What did you see instead?
N/A
 
### Anything else we should know about your project / environment?
N/A

**--FEATURE REQUEST--**

Please add support for VB.NET code generation

**Comment by Rantanen** [comment]
Would it be possible to just use C# code generation and compile that into an assembly? You can still write your own code in VB.NET. You would need to set up the C# project and include it in the build, but the rest you can do in VB.NET.

**Comment by InteXX** [comment]
Yes, this would be an acceptable workaround.

Native support would be best, but in its absence this would do.

**Comment by Rantanen** [comment]
Yeah, of course. :)

Just wanted to offer a workaround that could get you going today instead of waiting for something else to be implemented.

**Comment by InteXX** [comment]
Very good, thank you.

In your opinion, then, should this issue stay open, in pursuit of the RFE?

**Comment by Rantanen** [comment]
That's up to the maintainers. I'm not one and I don't know what the protocol for this project is. I just spotted the open issue while looking for something completely unrelated.

I'd keep it open at least until the maintainers acknowledge it and state their stance.

**Comment by InteXX** [comment]
> I'm not one...

That's pretty much what I figured. That's why when I started to write something else I changed it to 'in your opinion.'

Thanks for chiming in!
