### ISSUE TITLE
descriptor.upb.c fail to build

### ISSUE THREAD

**Issue by deryck1031** [grpc/grpc#18701]
### What version of gRPC and what language are you using?
 
 Latest version from GIT, for C++
### What operating system (Linux, Windows,...) and version?
 
 Linux:   2.6.32-754.9.1.el6.x86_64 #1 SMP Wed Nov 21 15:08:21 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 gcc 7.4 
### What did you do?
Build failed once enabled gRPC_BUILD_TESTS:
third_party/upb/google/protobuf/descriptor.upb.c:10:10: fatal error: upb/msg.h: No such file or directory
 #include "upb/msg.h"
          ^~~~~~~~~~~
compilation terminated.
 
### What did you see instead?
 
build failed
 
### Anything else we should know about your project / environment?

I dont see -I including third_party/upd/ directory:

/efs/dist/fsf/gcc/7.4.0/exec/bin/gcc -DPB_FIELD_32BIT -I/home/zkn8etz/source/third_party/grpc@master/third_party/zlib -I/home/zkn8etz/source/third_party/grpc@master/include -I/home/zkn8etz/source/third_party/grpc@master -I/home/zkn8etz/source/third_party/grpc@master/third_party/protobuf -I/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/grpc-build/third_party/zlib -I/home/zkn8etz/source/third_party/benchmark@master/include -I/home/zkn8etz/source/third_party/grpc@master/third_party/cares/cares -I/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/grpc-build/third_party/cares/cares -I/home/zkn8etz/source/third_party/grpc@master/third_party/address_sorting/include -I/home/zkn8etz/source/third_party/grpc@master/third_party/nanopb -isystem /efs/dist/fsf/openssl/1.1.1/exec/include  -std=c99 -g -fPIC   -o CMakeFiles/upb.dir/third_party/upb/google/protobuf/descriptor.upb.c.o   -c /home/zkn8etz/source/third_party/grpc@master/third_party/upb/google/protobuf/descriptor.upb.c

**Comment by jtattermusch** [comment]
I think this has the same rootcause as https://github.com/grpc/grpc/issues/20392 - `third_party/upb` is a submodule, but our cmake build doesn't reflect that and acts as if the sources are "local" (live in this repository).

**Comment by jtattermusch** [comment]
Fixed by https://github.com/grpc/grpc/pull/20662
