### ISSUE TITLE
program crashes when both grpc++ and openssl are linked

### ISSUE THREAD

**Issue by richardxu36** [grpc/grpc#18716]
### What version of gRPC and what language are you using?
 0.3.6 / c++
 
### What operating system (Linux, Windows,...) and version?
 Linux Rethat 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.2.1
 
### What did you do?
I'm trying to build a program using Bazel. which depends on "@com_github_grpc_grpc//:grpc++"
and restclient-cpp, which in turn depends on a system installed openssl .so files, version 1.0.1 

grpc++  built from src and statically linked into the program, but restclient-cpp is prebuilt and distributed as .so files.

### What did you expect to see?
 Program should not crash.
 
### What did you see instead?
When I remove the grpc++ dependency, program does not crash. When I remove the restclient-cpp dependency, program does not crash.

When both grpc++ and restclient-cpp are linked(verified by examining ldd and binary sizes),program crashes at run time:

    @     0x7fb3dc6e05e0 (unknown)
    @     0x7fb3db05599c SSL_ctrl
    @     0x7fb3e11464f3 ossl_connect_common
    @     0x7fb3e1147410 Curl_ssl_connect_nonblocking
    @     0x7fb3e1100652 https_connecting
    @     0x7fb3e1111e91 Curl_protocol_connect
    @     0x7fb3e1125a0e multi_runsingle
    @     0x7fb3e11267b1 curl_multi_perform
    @     0x7fb3e111d12c curl_easy_perform
    @     0x7fb3e0ee26b6 RestClient::Connection::performCurlRequest()
    @     0x7fb3e0ee2b02 RestClient::Connection::post()
 
### Anything else we should know about your project / environment?
From searching Google, some users have suggested to point grpc to build against openssl instead of boringssl to fix this issue. I'm just wondering how I can go about doing this and whether this will have implications down the line when future grpc versions are released.

**Comment by nicolasnoble** [comment]
Wait... are you seriously talking about grpc 0.3.6?

**Comment by nicolasnoble** [comment]
If you are building a software using Bazel, use grpc's Bazel files themselves. You will then avoid the problem altogether, since Bazel will enforce a single openssl library being linked in.

In general with Bazel, do NOT use .a files in there. Always compile everything.

**Comment by richardxu36** [comment]
Hi Nicolas, thanks for the reply. To clarify:

1) I am building an application using bazel
2) the dependency "@com_github_grpc_grpc//:grpc++" of my application is pointing to the grpc source(i.e., all of grpc and its own dependencies are compiled and statically linked into my binary)
3) In addition to grpc++, my application is also pulling in a precompiled restclient-cpp .so via cc_import, (note we don't want to compile this particular dependency from src as this is already packaged and vetted prior). The restclient-cpp links in curl, which in turn links a system provided openssl. 

Only when both of these are linked into the application, the program crashes with the above stacktrace. it 's happy when only one of these two dependencies exist.

**Comment by nicolasnoble** [comment]
There's no right way to solve this. That's kind of on bazel, not grpc. You simply can't do this properly with bazel. You need to build ALL of your dependencies with bazel for it to properly work.

One ugly workaround would be to provide grpc with a different library of OpenSSL that coincides with the one your .so uses. But again, that's not the intended usage of bazel.
