### ISSUE TITLE
Segfault using the experimental CQ callback

### ISSUE THREAD

**Issue by pfreixes** [grpc/grpc#18721]
### What version of gRPC and what language are you using?

master 
 
### What operating system (Linux, Windows,...) and version?
 
Mac
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

```bash
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
 
 
### What did you do?
When I'm using the experimental `grpc_completion_queue_create_for_callback` CQ with callback interface together with `grpc_call_start_batch` Im having a segfault due to having the application execution context with a `Nil` value.

How this Nil value is eventually placed and used can be understood by following the next steps:

1) The application context is allocated in the thread local store once the `grpc_call_start_batch` is called [1].
2) The destructor is eventually called once the `callback_exec_ctx` runs out of the scope [2] which will set the application context for that thread to null.
3) If `grpc_call_start_batch` was configured to use a completion queue of type callback and the cq_end_op_for_callback  is eventually called after `2` will enqueue a callback [3] in a Nill context.

[1] https://github.com/grpc/grpc/blob/master/src/core/lib/surface/call.cc#L1915
[2] https://github.com/grpc/grpc/blob/master/src/core/lib/surface/call.cc#L1920
[3] https://github.com/grpc/grpc/blob/master/src/core/lib/surface/completion_queue.cc#L853
 
### What did you expect to see?

Having the `functor_run` related to that tag being executed.
 
 
### What did you see instead?

A segfault

```bash
I0411 00:24:22.210500000 140735909585856 completion_queue.cc:833]      cq_end_op_for_callback(cq=0x7fa6c6cd5cc0, tag=0x10ff598c0, error="No Error", done=0x10f9ab020, done_arg=0x7fa6c8099440, storage=0x7fa6c80994b8)
D0411 00:24:22.210603000 140735909585856 transport.cc:59]              CALL_STACK 0x7fa6c8098e60:0x7fa6c8098470 UNREF 4->3 completion
I0411 00:24:22.210613000 140735909585856 completion_queue.cc:852]      functor=0x10ff598c0
I0411 00:24:22.210621000 140735909585856 exec_ctx.h:336]               1
I0411 00:24:22.210628000 140735909585856 exec_ctx.h:343]               ctx=(0x0)
make: *** [acceptance] Segmentation fault: 11
```

/cc @vjpai

**Comment by yashykt** [comment]
Has this been fixed?

**Comment by pfreixes** [comment]
Yes this has been fixed.
