### ISSUE TITLE
Ability to detect slow/blocked client on streaming RPC

### ISSUE THREAD

**Issue by gimmi** [grpc/grpc#18739]
### What version of gRPC and what language are you using?
gRPC C# 1.18.0
 
### What operating system (Linux, Windows,...) and version?
Windows 10 & Linux via Docker
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet core 2.2
 
### What did you do?
I am implementing a RPC with streaming response, in this scenario the "backpressure" feature will  make the call to `IServerStreamWriter<T>.WriteAsync(T message)` block when a given client is too slow in processing messages.
 
### What did you expect to see?
I wish to be able to detect when a slow client has the receive queue full and act appropriately (for example, disconnecting with `RpcException("too slow")` or something like that)
 
### What did you see instead?
Seems that there is no way for the server to know in advance if a call to `WriteAsync` will block until client is ready, and this can make a bad client run server processing.

**Comment by jtattermusch** [comment]
WriteAsync() "asynchronously blocking" when client is too slow in processing messages is working as intended, we designed gRPC to behave that way.
The behavior you're describing sounds like very specific to your use case and it doesn't sound like something we'd want to support as a generally available feature (also I have my doubts if such behavior actually makes sense for HTTP2 over TCP traffic). But if that's the behavior you need in your application, there are certainly ways to emulate such behavior: e.g. you can cancel your request if WriteAsync waits longer that some amount of time or you can come up with a custom bidi protocol that allows you to send confirmations from the client to signal that client is able too keep up with the requests.

**Comment by gimmi** [comment]
Thanks @jtattermusch for commenting.

I agree this is a very specific use case, maybe a better fit would be some custom service running over plain UDP.
