### ISSUE TITLE
Run-Time Check Failure #0 when using gRPC on C++

### ISSUE THREAD

**Issue by Garu94** [grpc/grpc#18756]
I'm trying to implement a simple server-client communication, but I get this error:
`Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.`
When running the client while the server is running. Here's the line that is causing the error:
`auto* request = new (g_core_codegen_interface->grpc_call_arena_alloc(
        call, sizeof(RequestType))) RequestType();`

As I am understanding, the cause should be some kind of mismatch in the types of the caller and the called, am I right?
Here's the code of the .proto file:

```
service DataSourceSetter {
  rpc SetSystemReady (IntValue) returns (HelloReply) {}
}
message IntValue {
  int32 value = 1;
}
message HelloReply {
  string message = 1;
}
```

Here's the client implementation:
```
class DataSourceSetterClient {
public:
	DataSourceSetterClient(std::shared_ptr<Channel> channel)
		: stub_(DataSourceSetter::NewStub(channel)) {}

	std::string SetSystemReady(const std::int32_t& value) {
		IntValue valueCarrier;
		valueCarrier.set_value(value);

		HelloReply reply;

		ClientContext context;

		Status status = stub_->SetSystemReady(&context, valueCarrier, &reply);

		if (status.ok()) {
			return reply.message();
		}
		else {
			std::cout << status.error_code() << ": " << status.error_message()
				<< std::endl;
			return "RPC failed";
		}
	}

private:
	std::unique_ptr<DataSourceSetter::Stub> stub_;
};

int main(int argc, char** argv) {
	DataSourceSetterClient setter(grpc::CreateChannel("127.0.0.1:50051", grpc::InsecureChannelCredentials()));
	std::int32_t value = 1;
	std::string reply = setter.SetSystemReady(value);

	system("PAUSE");
	return 0;
}

```
And, finally, the server-side implementation:
```
class DataSourceSetterServiceImpl final : public DataSourceSetter::Service {
public:
	DataSourceSetterServiceImpl(KanziApplication *application)
		: mApplication(application)
	{
	}
	Status SetSystemReady(ServerContext* context, const IntValue* valueCarrier,
		HelloReply* reply) override {
		kzLogDebug(("RECEIVED client request, {}", valueCarrier->value()));
		
		mApplication->getSettingsModule().getDataSource()->getGeneral().getSystemReady().setValue(1);
		std::string prefix("SystemReady set to: {}", valueCarrier->value());
		reply->set_message(prefix);
		return Status::OK;
	}

private:
	KanziApplication* mApplication;
};

void KanziApplication::RunServer() {
	std::string server_address("127.0.0.1:50051");
	DataSourceSetterServiceImpl service(this);

	ServerBuilder builder;

	builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());

	builder.RegisterService(&service);

	std::unique_ptr<Server> server(builder.BuildAndStart());
	kzLogDebug(("Server listening on {}", server_address));

	server->Wait();
}
```
Apart from the custom constructor, there are really few differences among this and the Helloworld example, but also by deleting the custom constructor just to print the received value, the error I get is the same.

EDIT: If it can be useful to know, the server in my implementation is running on a detached thread.

EDIT 2: also, when I run the modified HelloWorld example including the files generated by protoc, it works fine apart from the client, that outputs on screen only the first letter of the reply message.

**Comment by Garu94** [comment]
I solved including grpc\testinstall\include that was missing, sorry for bothering

**Comment by AspirinSJL** [comment]
Closing because the user solved the issue.
