### ISSUE TITLE
serving get sigterm then do shutdown, it's just refused and not exit,  what's wrong?

### ISSUE THREAD

**Issue by bainiu87** [grpc/grpc#18768]
#include <iostream>
#include <memory>
#include <string>
#include <grpcpp/grpcpp.h>
#include <unistd.h>
#include <getopt.h>
#include <csignal>

#include "helloworld.pb.h"
#include "helloworld.grpc.pb.h"

namespace hello {
    std::unique_ptr<::grpc::Server> grpc_server_;

    class GreeterServiceImpl final : public helloworld::Greeter::Service {

    public:

        int count=0;
        unsigned int response_duration;

        explicit GreeterServiceImpl(unsigned int res_dur){
            this->response_duration = res_dur;
            std::cout << "response duration: " << this->response_duration << std::endl;
        }

        grpc::Status SayHello(grpc::ServerContext* context, const helloworld::HelloRequest* request, helloworld::HelloReply* response) override {
            this->count++;
            sleep(this->response_duration);
            std::cout << "requests: "+request->name()+" count: "<< count << std::endl;
            std::string prefix("Hello ");
            response->set_message(prefix+request->name());
            return grpc::Status::OK;
        }
    };

    void RunServer(unsigned int rep_dur) {
        std::string serving_address("0.0.0.0:3000");
        std::cout << "Server listening on " << serving_address << std::endl;
        GreeterServiceImpl service(rep_dur);
        grpc::ServerBuilder builder;
        builder.AddListeningPort(serving_address, grpc::InsecureServerCredentials());
        builder.RegisterService(&service);
        grpc_server_ = builder.BuildAndStart();
        if (grpc_server_ != nullptr) {
            grpc_server_ -> Wait();
        }
    }
}

void signalHandler (int signum) {
    std::cout << "Interrupt signal (" << signum << ") received.\n";
    if(hello::grpc_server_ != nullptr) {
        std::cout << "hhh" << std::endl;
        hello::grpc_server_ -> Shutdown();
    }
    exit(signum);
}

int main(int argc, char *argv[]) {
    signal(SIGTERM, signalHandler);
    unsigned int response_duration = 10;
    hello::RunServer(response_duration);
    return 0;
}

**Comment by mhaidrygoog** [comment]
Please refile following bug template guidelines for the issue.
