### ISSUE TITLE
C4702 Unreachable Code Warnings in GRPC Generated Header Files Related to abort()

### ISSUE THREAD

**Issue by theoneneoxu** [grpc/grpc#18777]
### What version of gRPC and what language are you using?
Version: 1.10.0
Language: c++
 
### What operating system (Linux, Windows,...) and version?
OS: Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Compiler: Visual Studio 2017 
 
### What did you do?
I was checking compiler warnings of the cpp files generated using grpc.
 
### What did you expect to see?
I expected to see no compiler warnings from cpp files generated using grpc.
 
### What did you see instead?
VS 2017 gave C4702 Unreachable Code warnings in lots of .h header files generated by grpc. There is return statement after abort() in the generated grpc code. I assume the issue is from following example code in grpc/src/compiler/cpp_generator.cc file.
    printer->Print(
        *vars,
        "// disable synchronous version of this method\n"
        "::grpc::Status $Method$("
        "::grpc::ServerContext* context, const $Request$* request, "
        "$Response$* response) override {\n"
        "  abort();\n"
        "  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, \"\");\n"
        "}\n");
In code like this, the return statement is unreachable in the eyes of VS 2017 and hence triggers C4702 warnings.

**Comment by theoneneoxu** [comment]
This issue is important because the warnings come from header files which cannot be easily disabled in a small scope (header files can be included from anywhere in our code). And we don't want to suppress the C4702 Unreachable Code warning globally in our project because the warning is efficacious in finding bugs.

**Comment by theoneneoxu** [comment]
Hi, just want to know is the problem going to be fixed and in which release plan? Thanks!

**Comment by nicolasnoble** [comment]
This isn't really on our radar, as "fixing" this would cause the OTHER warning that we're not returning anything in a function that has a return type. Trying to clean up generated code is a sisyphean task. The best I could suggest as a quick workaround in the meantime would be to do something along the lines:

```
#pragma warning(push)
#pragma warning(disable: 4702)
#include "some_header.grpc.pb.h"
#pragma warning(pop)
```

**Comment by theoneneoxu** [comment]
Okay. We suppressed the warning from the header files. Thanks for the work around.
