### ISSUE TITLE
Missing grpc_set_default_iomgr_platform

### ISSUE THREAD

**Issue by jsmouret** [grpc/grpc#18787]
### What version of gRPC and what language are you using?

C#
gRPC v1.21.0 @ 2019-04-16
 
### What operating system (Linux, Windows,...) and version?
 
MacOS, Unity
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Build for iOS using IL2CPP
 
### What did you do?

Compile using the latest grpc unity package.
 
### What did you expect to see?

Compile success 

### What did you see instead?
``` 
Undefined symbols for architecture arm64:
  "grpc_set_default_iomgr_platform()", referenced from:
      grpc_determine_iomgr_platform() in libgrpc.a(iomgr_internal.o)
ld: symbol(s) not found for architecture arm64
```
 
### Anything else we should know about your project / environment?

Nothing special

**Comment by rulk** [comment]
Hi, had the same issue with latest nightly builds.
I had to downgrade to 4081a04b-a38e-4bec-b438-af180c0a3d5b from 2019-02-26T02:51:36-0800
It works there.
Waiting for the fix!
