### ISSUE TITLE
undefined symbol: grpc_metadata_array_destroy with static libs

### ISSUE THREAD

**Issue by rameshpasunoori** [grpc/grpc#18788]
### What version of gRPC and what language are you using?
 grpc v1.4
 
### What operating system (Linux, Windows,...) and version?
Linux RHEL 7.4
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
Loading the customer dll failed with message 
undefined symbol: grpc_metadata_array_destroy with static libs
 
### What did you see instead?
 Custom DLL is to loaded without erros.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by AspirinSJL** [comment]
I suggest using an updated gRPC version. Please reopen this bug if it still happens on recent versions.
