### ISSUE TITLE
Platform Detection in Grpc.Core For Unity Causes Assembly Load Attempt for UnityEngine.dll

### ISSUE THREAD

**Issue by martysupple** [grpc/grpc#18801]
### What version of gRPC and what language are you using?
 Grpc.Core 1.20 (latest as of this posting)
 
### What operating system (Linux, Windows,...) and version?
 Windows Server 2012
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .Net 4.5 CSharp
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 - Using Visual Studio 2017/2019 and the latest Google Grpc Tools/Core runtimes generated a Grpc client proxy from a set of protobuff files. Everything works as expected when calling into these CSharp generated classes (generated using the Grpc.Tools protoc.exe). When attempting to run these client classes from an SSIS (MS SQL Server Integration Services) Script Task and due to a 'bug' in the SSIS Telemetry runtime regarding Assembly resolution (when .Net/Reflection is trying to resolve an assembly to load it). the GRPC client code fails.

### What did you expect to see?
 Same client that works in a standard .Net exe work from an SSIS Script task.
 
### What did you see instead?
 An exception thrown in the SSIS telemetry code due to UnityEngine.dll attempting to get loaded by ,Net to service the Type.GetType() call made from Grpc.Core!

I THINK what you want to do in Grpc.Core to detect Unity is just call Type.GetType("UnityEngine.Application") which will not cause .Net to try to load any additional assemblies. Let's say you are running a NON Unity .Net app on a machine that has the Unity Engine in the GAC, then isUnity would actually resolve to true and I suspect you would get undesirable results after that point as it is NOT a Unity application just because the Unity engine was available for .Net/Reflection to load.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
I tried and the suggested fix `Type.GetType("UnityEngine.Application")` actually fails on Unity. We need a better solution for detecting we're actually running on unity.

This is only a problem if you have "UnityEngine.dll" in your GAC (which seems to be non-standard, why do you have it there?).

**Comment by martysupple** [comment]
I am not using Unity at all in my solution. But it seemed your implementation for 'detecting' if this application was a Unity application seemed less than ideal. Just because the Unity dll can be loaded by .net does not necessarily mean its a unity application. I worked around this problem by running my GRPC code out of process from SSIS for now. Thanks..

**Comment by jtattermusch** [comment]
@martysupple I agree that the way we detect unity could use an improvement, but I don't know a better solution myself, so I'm open to new suggestions. Until then, the current way seems acceptable.

**Comment by martysupple** [comment]
If there is not a 100% reliable way to detect Unity, why not give the caller the option to override your auto-detection so we can avoid the .net assembly load attempt for the unity dll?

**Comment by jtattermusch** [comment]
@martysupple  I'd be very surprised if there wasn't a 100% reliable way of detecting Unity - we just haven't figured it out yet. Maybe some of the Unity users can chime in and suggest a better approach?

**Comment by jtattermusch** [comment]
Let's keep open.

**Comment by TieSKey** [comment]
I'm suffering from this problem too. I have a non-unity app that uses some Unity3D managed types and thus Unity3D.dll is part of the project. 

While we wait for some novel idea on how to approach this, can't you catch that exception and asume it is not a unity app? 

Please note that while this thread talks about an unwanted dll load, there are legit reasons to include the Unity3D.dll in a non-unity project (more in line with #23334 )

**Comment by motive-ray** [comment]
As a sometime Unity dev, my first thought is check for compilation symbols. I think something like below is actually sufficient:

```
bool isUnity = false;
#if UNITY_5_3_OR_NEWER
    isUnity = true;
#endif
```

**Comment by TieSKey** [comment]
Afaik preprocesor/compiler directives are only available at compilation time. 
It work for those that compile their own Grpc.Core dlls along with their projects but not for rest that use precompiled (nuget) ones.

**Comment by motive-ray** [comment]
> Afaik preprocesor/compiler directives are only available at compilation time.
> It will work for those that compile their own Grpc.Core dlls along with their projects but not for rest that use precompiled (nuget) ones.

ty for the response I assumed there was some reason this wouldn't work, didn't fully think that through 👍
