### ISSUE TITLE
error: ‘pthread_setname_np’ was not declared in this scope

### ISSUE THREAD

**Issue by ppietrasa** [grpc/grpc#18802]
### What version of gRPC and what language are you using?
 
 gRPC v1.20.0

### What operating system (Linux, Windows,...) and version?

Linux,  SUSE Linux Enterprise Server 11 (x86_64)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC v6.3.1
 
### What did you do?

I tried to build the gRPC on the aforementioned system.
 
### What did you expect to see?
 
I expected the build to complete.
 
### What did you see instead?

```
<long path>/grpc-1.20.0/src/core/lib/gprpp/thd_posix.cc: In lambda function:
<long path>/grpc-1.20.0/src/core/lib/gprpp/thd_posix.cc:99:67: error: ‘pthread_setname_np’ was not declared in this scope
                             pthread_setname_np(pthread_self(), buf);
                                                                   ^
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gprpp/thd_posix.cc.o] Error 1
```
 
### Anything else we should know about your project / environment?

The function `pthread_setname_np()` is not available on an older GLIBC.  It was introduced in glibc 2.12.  
This patch/workaround worked for me:
```patch
--- a/include/grpc/impl/codegen/port_platform.h
+++ b/include/grpc/impl/codegen/port_platform.h
@@ -176,7 +176,7 @@
 #else /* _LP64 */
 #define GPR_ARCH_32 1
 #endif /* _LP64 */
-#ifdef __GLIBC__
+#if __GLIBC__ >= 2 && __GLIBC_MINOR__ >= 12
 #define GPR_POSIX_CRASH_HANDLER 1
 #define GPR_LINUX_PTHREAD_NAME 1
 #include <linux/version.h>
```

**Comment by nicolasnoble** [comment]
Feel free to transform your small patch into a pull request.
