### ISSUE TITLE
rpmbuild execvp: /bin/sh: Argument list too long

### ISSUE THREAD

**Issue by apptut** [grpc/grpc#18810]
Hi, dears:

I try to build a c core lib rpm package from source code according the php grpc doc, as below: 

```bash
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc

cd grpc
git submodule update --init
make
sudo make install
```
I tar all the code to grpc-version.tar.gz and then make rpm spec file :

```
%build
make %{?_smp_mflags} prefix=%{_prefix}

%install
make install prefix=%{buildroot}%{_prefix}
```
But it's not success, and some error show blew:

```
[INSTALL] Installing libgrpc_unsecure.so.7.0.0
ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
[INSTALL] Installing public C++ headers
make: execvp: /bin/sh: Argument list too long
make: *** [install-headers_cxx] Error 127
error: Bad exit status from /var/tmp/rpm-tmp.1WeEIh (%install)
```
 My company have some many servers need deploy, so rpms is easy way to do this things。Anybody can help me or give some advise ?

**Comment by nicolasnoble** [comment]
Which version of `make` are you using...?

**Comment by apptut** [comment]
@nicolasnoble 
```bash
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
```

**Comment by nicolasnoble** [comment]
I *think* we require at least make 4.0... what version of redhat comes with such an ancient version of GNU Make?

**Comment by apptut** [comment]
I just compile with root user install it to the system immediately. This is success。But when I make  that with rpmbuild to a chroot dir, this is not ok。rpmbuild tool build package in some /tmp/Y.asiusy dir. I think the Makefile some config `/etc/ld.so` is absulte path，not have a prefix 。in rpmbuild mode, if the path is `%{buildroot}/etc/` may be work. 

But I do not know how to fix that.

**Comment by apptut** [comment]
I update my make tool version to 4.2, but not work too。I think the problem is the ldconfig command in file somewhere , because rpmbuild nor run in root env, maybe ldconfig need add `-r` params to change root path dir。But I can find where ldconfig used。

**Comment by apptut** [comment]
I fixed the problem finally. two problems:
 1. ldconfig create cache no permission.
 2. c++ headers( execvp: /bin/sh: Argument list too long err)

The first I just comment these lines in Makefile:
```bash
grep -n 'ldconfig' rpmbuild/SOURCES/grpc-1.20.0/Makefile
3044:	#$(Q) ldconfig || true
3106:	#$(Q) ldconfig || true
3123:	#$(Q) ldconfig || true
```
Because ldconfig is runtime config， but now just in compile process. so I set the command  after the rpm install to user system time, just like:

```bash
# post section will run after the rpm install to user system
%post
ldconfig
```
The second problem, I found in another issue here: [#17763](https://github.com/grpc/grpc/pull/17763/commits/be133485cf6f578866837255049de8f142aaf7f0).

This is not problem in normal installation, because the default install path is `/usr/local/include`, but in rpmbuild build mode, the install dir is `/home/work/rpmbuild/BUILDROOT/grpc-1.20.0-1.el7.x86_64/usr/local/include`.

That patch is useful, hope to merge to master !!!
