### ISSUE TITLE
grpc make error:  : In function conn_callback_ctrl: at gcc 8.3.0

### ISSUE THREAD

**Issue by huangnie** [grpc/grpc#18819]
third_party/boringssl/crypto/bio/connect.c: In function ‘conn_callback_ctrl’:
third_party/boringssl/crypto/bio/connect.c:491:29: error: cast between incompatible function types from ‘bio_info_cb’ {aka ‘long int (*)(struct bio_st *, int,  const char *, int,  long int,  long int)’} to ‘int (*)(const struct bio_st *, int,  int)’ [-Werror=cast-function-type]
       data->info_callback = (int (*)(const struct bio_st *, int, int))fp;
                             ^
cc1: all warnings being treated as errors
make: *** [Makefile:2901: /work/development/golang/src/grpc/objs/opt/third_party/boringssl/crypto/bio/connect.o] Error 1

**Comment by D4ywa1k3r** [comment]
I get the same error message..

**Comment by gocarlos** [comment]
having the same issue on ubuntu 19.04 gcc 8.3

**Comment by shahbazshueb** [comment]
I am facing the same issue in ubuntu:19.04 container.

**Comment by vnagineni** [comment]
In am also facing the same problem. How to resolve it?

**Comment by JianshuLiu1721** [comment]
I encounter the same problem on RHEL6, have anyone solved this issue?

**Comment by sampleref** [comment]
same problem on ubuntu 18.10, any solution? workaround/hack?

**Comment by jeffreyqw** [comment]
Try this command" env CC=clang env CXXFLAGS="-Wno-tautological-compare -Wno-class-memaccess -Wno-ignored-qualifiers" make "

**Comment by CraftyDragon678** [comment]
I also have the same problem in Raspbian. is there anyone knowing how to solve it?

**Comment by CraftyDragon678** [comment]
I solved this problem with "export CFLAGS=-Wno-error" and "export CXXFLAGS=-Wno-error"

**Comment by AspirinSJL** [comment]
@nicolasnoble I've seen several such boringssl related build issues, such as https://github.com/grpc/grpc/issues/19468. Is adding compiler flags the right way to solve it? Do we have any long term fix?
