### ISSUE TITLE
How to store private data on the client side of a web app?

### ISSUE THREAD

**Issue by wangh09** [grpc/grpc#18825]
Hi, I have been searching for how to manipulate tokens on the client side of a web app for days. As we all know, the only secure storage on the client side is the http-only cookie, but it seems that grpc has no way to interact with it, and one can only store the token obtained from trailer metadata in the local storage (or something like that) and put it in the header metadata when calling other functions. Since local storage can be stolen by any js code, is there a better way to handle such data? Thanks!

**Comment by srini100** [comment]
If you are asking about the kind of sandboxing a browser provides for cookies, then no, gRPC doesn't provide such facility. It is outside the scope of gRPC to provide filesystem protection/isolation you want. This is a generic question about data isolation and protection between processes which should be asked on forums like stackoverlow.

**Comment by wangh09** [comment]
> If you are asking about the kind of sandboxing a browser provides for cookies, then no, gRPC doesn't provide such facility. It is outside the scope of gRPC to provide filesystem protection/isolation you want. This is a generic question about data isolation and protection between processes which should be asked on forums like stackoverlow.

So cookie should not be a part of HTTP protocol right?
