### ISSUE TITLE
C# RpcException "message" arg not being sent to the remote peer (unlike status)

### ISSUE THREAD

**Issue by jstafford5380** [grpc/grpc#18822]
### What version of gRPC and what language are you using?
 gRPC v1.20.0
C#
 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
netcore 3.0
 
### What did you do?
Throw an `RpcException(status, message)` from the gRPC server with a string message
 
### What did you expect to see?
On the client side, I catch `RpcException` and I expect to see the message I included in the excpetion. 
 
### What did you see instead?
The instance of `RpcException` received on the client side does not include the message. Instead, in the Message property, it has the ToString() value of the Status.
 
On the server side, I put a breakpoint on the exception I'm throwing, and I can see that the message I specified is on the object, in the Message property. I see in the implementation that the message is passed to the base constructor. So that is to be expected. However, it doesn't make it over to the client side. To get a message across, I'd have to include it in the status object. This makes for a misleading exception API.

**Comment by xolott** [comment]
I'm using Linux (ubuntu 18.04) and having the same issue. I was trying to use the `RpcException` like this:
*  StatusCode: StatusCode from the protocol (Unknown, Cancelled, etc)
*  Details: Some internal exception code, like `E0005`
*  Message: Some human-readable exception message

But, I keep getting `Status(StatusCode=Unknown, Detail="E0005")` as Message property on the client's side.
Shouldn't this be considered as `kind/bug` instead of `kind/enhancement`?

**Comment by jtattermusch** [comment]
As you're realized, the "message" field is only the standard exception message and it's not passed to from the server to the client. This is working as intended (as the status code and status details are the only pieces that are supposed to be passed to the client), but we could probably improve the documentation or RpcException to make that clearer. 
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/RpcException.cs

Under normal circumstances, you should probably use `RpcException(Status status)` and `RpcException(Status status, Metadata trailers)` constructors.
https://github.com/grpc/grpc/blob/2951e72aeec6f96b1a411378839252736e03d15a/src/csharp/Grpc.Core.Api/RpcException.cs#L36
