### ISSUE TITLE
Implement IDisposable on generated clients and Channel

### ISSUE THREAD

**Issue by jstafford5380** [grpc/grpc#18821]
### What version of gRPC and what language are you using?
 gRPC v1.20.0
C#
 
### What operating system (Linux, Windows,...) and version?
 Windows 10 and Linux (various distos for docker base images)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 netcore 3.0
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
No error, just a feature request.
 
### What did you expect to see?
 In .net core, the normal way of creating instances of services is to do so through dependency injection (e.g. Microsoft.Extensions.DependencyInjection). In the case of creating a gRPC client, we're expected to call `channel.ShutdownAsync();` when we're done using the channel but if we're using correct DI patterns, we will never see that Channel because an initialized channel would be injected into the client when the client service is requested. For example, a calling unit might look like this:

``` csharp
public class MyCallingClass
{
	private Greeter.GreeterService _greeterService;
	
	public MyCallingClass(Greeter.GreeterService greeterService) 
	{
		// our DI framework would assemble this client with an initialized channel
		_greeterService = greeterService;
	}
	
	public async Task DoThing()
	{
		await _greeterService.CallToService(...);
	}
}
```

In this example, we simple request the greeter service from DI. I cannot call `channel.ShutdownAsync()`  because I don't have access to the channel nor do I want to do this anyway. 
 
### ~~What did you see instead?~~
Suggestion:
When the lifecycle of a service ends, IoC containers will generally look for the IDisposable interface and invoke it if it exists. If you were to implement IDisposable on generated clients and/or Channel, then when either is disposed (e.g. by the IoC container), then shutdown can be called on the channel automatically.
 
 
### Anything else we should know about your project / environment?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-client?view=aspnetcore-3.0&tabs=visual-studio

**Comment by jtattermusch** [comment]
let's keep this open.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
