### ISSUE TITLE
support node.js 12

### ISSUE THREAD

**Issue by zuohuadong** [grpc/grpc#18849]
### What version of gRPC and what language are you using?
 
ubuntu 14.04.5

### What operating system (Linux, Windows,...) and version?
 
 1.20.0

### What runtime / compiler are you using (e.g. python version or version of gcc)

   gcc 4.8.4 

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
`npm install grpc`

### What did you expect to see?
 
successful
 
### What did you see instead?

![Z}3O232}TUHNYQKXT_VE$3G](https://user-images.githubusercontent.com/11203929/56656558-64137580-66c8-11e9-939d-67fec7acb0ad.png)

https://travis-ci.org/nestjs/nest/jobs/523923958
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by DRoet** [comment]
wrong repo, see <https://github.com/grpc/grpc-node/issues/834>
