### ISSUE TITLE
Unexpected delay(bug) for newer grpc version when issuing rpc frequently

### ISSUE THREAD

**Issue by BintaSong** [grpc/grpc#18860]
### What version of gRPC and what language are you using?
 grpc 20, cpp
 
### What operating system (Linux, Windows,...) and version?
 ubuntu 16.04.4
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 6.5.0 
 
### What did you do?

My client includes several stubs to maintain rpc with two servers, the client may issue rpc requests to different servers at the same time.

### What did you expect to see?
 I think maintaining multi stubs for different destination is quite common, they should not affect each other.
 
### What did you see instead?
I find when changing from one stub to another, it takes 10 seconds to complete the second rpc request, but things will be fine if the second stub is once used. At first I thought it would be my misuse of stubs, but when i try to use only one stub to issue many rpc calls sequentially, the delay still happens for the first time call sometimes.

Then I thought my code has problem and changed to run the example helloword provided from the repo. I found that if the client program is run too frequently in terminal, the 10-seconds delay also happens. So far this happens for both grpc version 19 and version 20(I only tested this two version), and the client program is test on three different ubuntu machines, all encountered the delay.

However, this **delay does not happen** when i changed to early grpc version [release-0_14](https://github.com/grpc/grpc/tree/release-0_14/), both my code and the helloworld perfectly worked without 10-seconds delay

**Comment by yashykt** [comment]
Please re-open the issue with a test or code identifying the issue, so that we can reproduce and debug.
