### ISSUE TITLE
well_known_protos not passed as dependencies of _[target]_grpc_only

### ISSUE THREAD

**Issue by Kernald** [grpc/grpc#18864]
### What version of gRPC and what language are you using?
 1.19.1, C++
 
### What operating system (Linux, Windows,...) and version?
 Linux (up-to-date Archlinux)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Clang 8.0, Bazel 0.22.0 and 0.24.1
 
### What did you do?
I've got a simple service using `google.protobuf.Empty` as an argument (I know this is a design flaw and I should pass a message, but this exacerbates an issue with gRPC). My BUILD rule is the following:

```
cc_grpc_library(
    name = "tictactoe_cc_grpc",
    srcs = ["tictactoe.proto"],
    proto_only = False,
    well_known_protos = [
        "@com_google_protobuf//:empty_proto",
    ],
    deps = [],
)
```

When I run `bazel build //...`, the generated `_tictactoe_cc_grpc_only` fails to build:
```
ERROR: /home/kernald/dev/wksp/apps/tictactoe/proto/BUILD:7:1: Generating Descriptor Set proto_library //apps/tictactoe/proto:_tictactoe_cc_grpc_only failed (Exit 1) protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--descriptor_set_out=bazel-out/k8-fastbuild/genfiles/apps/tictactoe/proto/_tictactoe_cc_grpc_only-descriptor-set.proto.bin' ... (remaining 5 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
google/protobuf/empty.proto: File not found.
apps/tictactoe/proto/tictactoe.proto: Import "google/protobuf/empty.proto" was not found or had errors.
apps/tictactoe/proto/tictactoe.proto:66:29: "google.protobuf.Empty" is not defined.
apps/tictactoe/proto/tictactoe.proto:67:18: "google.protobuf.Empty" is not defined.
```
 
### What did you expect to see?
The compilation should work and `google.protobuf.Empty` should be provided to the generated target.
 
### What did you see instead?
The compilation failed.
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by Kernald** [comment]
Note that I also tried providing a `cc_proto_library` wrapping `google.protobuf.Empty`:

```
cc_grpc_library(
    name = "tictactoe_cc_grpc",
    srcs = ["tictactoe.proto"],
    proto_only = False,
    well_known_protos = [
        "@com_google_protobuf//:empty_proto",
    ],
    deps = [":empty_proto_cc"],
)

cc_proto_library(
    name = "empty_proto_cc",
    deps = [
        "@com_google_protobuf//:empty_proto",
    ],
)
```

This doesn't work as it's looking for a target named `_empty_proto_cc_only` - no idea why. Renaming my target to this name doesn't help either:

```
ERROR: /home/kernald/dev/wksp/apps/tictactoe/proto/BUILD:7:1: in deps attribute of proto_library rule //apps/tictactoe/proto:_tictactoe_cc_grpc_only: cc_proto_library rule '//apps/tictactoe/proto:_empty_proto_cc_only' is misplaced here (expected proto_library). Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /home/kernald/.cache/bazel/_bazel_kernald/58c025fbb926eac6827117ef80f7d2fa/external/com_github_grpc_grpc/bazel/cc_grpc_library.bzl:34:14
```

**Comment by vam-google** [comment]
@Kernald @gnossen `well_known_protos` is poorly documented and is actually a `boolean` field. 

Currently `cc_grpc_library` will add `"@com_google_protobuf//:well_known_protos"` as well_known_protos dependency if the `well_known_protos = True`. To add custom well_known_protos add them as regular deps in your rule.
