### ISSUE TITLE
c# memory leaking with CancellationTokenRegistration from AsyncDuplexStreamingCall

### ISSUE THREAD

**Issue by wuyuntao** [grpc/grpc#18879]
### What version of gRPC and what language are you using?
 
grpc 1.20.1,  c#

### What operating system (Linux, Windows,...) and version?
 
Linux / Windows 

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
.net core 2.2.0
 
### What did you do?

I'm implementing a etcd client with grpc. I found out that LeaseKeepAlive causing memory leaking. 

```
var channel = new Channel("127.0.0.1", 2379, ChannelCredentials.Insecure);
var leaseClient = new Lease.LeaseClient(channel);

for (int i = 0; i < 100; i++)
{
    var leaseGrantReq = new LeaseGrantRequest()
    {
        TTL = 100,
    };
    var leaseGrantRes = await leaseClient.LeaseGrantAsync(leaseGrantReq, cancellationToken: channel.ShutdownToken);
    using (var leaser = leaseClient.LeaseKeepAlive(cancellationToken: channel.ShutdownToken))
    {
        var leaseKeepAliveReq = new LeaseKeepAliveRequest() { ID = leaseGrantRes.ID };
        await leaser.RequestStream.WriteAsync(leaseKeepAliveReq);
        await leaser.RequestStream.CompleteAsync();
        while (await leaser.ResponseStream.MoveNext(channel.ShutdownToken))
        {
            var leaseKeepAliveRes = leaser.ResponseStream.Current;
            if (leaseKeepAliveRes.ID == leaseKeepAliveReq.ID)
                break;
        }
    }
}
```
 
### What did you expect to see?

`CancellationTokenRegistration` are all unregisted (disposed) after `leaser` is disposed
 
### What did you see instead?
 
`CancellationTokenRegistration` still exists in memory snapshot

### Anything else we should know about your project / environment?

Here is a demo project of memory leaking [grpc-mem-leak](https://github.com/wuyuntao/grpc-mem-leak)

**Comment by jtattermusch** [comment]
I tried running your demo but it contains client only code. Can you also provide the server code so that I can actually run the reproduction?

**Comment by wuyuntao** [comment]
The demo contains an [etcd](https://etcd.io/) client. You can reproduce by connecting to an etcd server.

**Comment by jtattermusch** [comment]
I'm running your example and as far as I can tell, after each call, there is an invocation of  `cancellationTokenRegistration.Dispose();`, so I'm actually not sure if there an actual leak https://github.com/grpc/grpc/blob/af1eaa0d058cdd319a975c2afeaf6383bdec2753/src/csharp/Grpc.Core/Internal/AsyncCall.cs#L416

Btw, I upgraded your repro to Grpc.Core 2.25.0 (the latest release).

**Comment by jtattermusch** [comment]
Closing for now as I haven't been able to reproduce (see above). I can reopen if there's more inputs/evidence that this is an actual memory leak.
