### ISSUE TITLE
Generate C# client interfaces

### ISSUE THREAD

**Issue by mrmartan** [grpc/grpc#18877]
This issue has already been dealt with over here https://github.com/grpc/grpc/issues/14213#issuecomment-361174486 and closed as a deliberate chioce. I understand the reason for doing so. I also think it is time to revisit it as C#8 allows for providing default implementation for interfaces.

Having an interface instead of a class would of great benefit, as previously stated, especially for testing and DI.

**Comment by mrmartan** [comment]
Sry, seems like I am mistaken. The language feature was proposed but has not made it into the final product (yet).

https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md

**Comment by jtattermusch** [comment]
The problem is that default interface methods are only available starting from C# 8 and it's going to take a while until majority of users is using C# 8.
