### ISSUE TITLE
How to close the long link between php-fpm and grpc server？

### ISSUE THREAD

**Issue by tangleiao** [grpc/grpc#18880]
### What version of gRPC and what language are you using?
 1.20
 
### What operating system (Linux, Windows,...) and version?
 centos 7.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
This my client code
 require dirname(__FILE__).'/vendor/autoload.php';

@include_once dirname(__FILE__).'/Pb/UserServiceClient.php';
@include_once dirname(__FILE__).'/Pb/UserResponse.php';
@include_once dirname(__FILE__).'/Pb/UserRequest.php';
@include_once dirname(__FILE__).'/GPBMetadata/User.php';

function user($userId)
{
    $client = new Pb\UserServiceClient('10.70.93.72:50051', [
        'credentials' => Grpc\ChannelCredentials::createInsecure(),
    ]);
    $request = new Pb\UserRequest();
    $request->setUserid($userId);
    list($reply, $status) = $client->getUserById($request)->wait();
        var_dump($client);
        //var_dump($status);
1 change; before #2  2 seconds ago
        var_dump($client);
        //var_dump($status);
    $user = $reply->getUser();
        print_r(get_object_vars($client));
    $client->close();
    return $user;
}
$num = 1;
$sum = 0;
echo '<pre>';
for($i=0;$i<$num;$i++){
        $stime = microtime(true);
        $result = user(51);
        print_r($result->getUsername());
        $etime = microtime(true);
        $rtime = $etime - $stime;
        $sum += $rtime;
//      echo "Running time:".$rtime."\n";
}
$atime = $sum/$num;
//echo "Average Running time:".$atime."\n";
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 this is my php client， 20 php-fpm process
[root@grpc2 php-fpm.d]# netstat -tnlpa |grep php-fpm
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      23898/php-fpm: mast 
tcp6       0      0 10.70.120.76:39600      10.70.93.72:50051       ESTABLISHED 23907/php-fpm: pool 
tcp6       0      0 10.70.120.76:39668      10.70.93.72:50051       ESTABLISHED 23912/php-fpm: pool 
tcp6       0      0 10.70.120.76:39702      10.70.93.72:50051       ESTABLISHED 23917/php-fpm: pool 
tcp6       0      0 10.70.120.76:38958      10.70.93.72:50051       ESTABLISHED 23901/php-fpm: pool 
tcp6       0      0 10.70.120.76:39316      10.70.93.72:50051       ESTABLISHED 23903/php-fpm: pool 
tcp6       0      0 10.70.120.76:39688      10.70.93.72:50051       ESTABLISHED 23909/php-fpm: pool 
tcp6       0      0 10.70.120.76:39700      10.70.93.72:50051       ESTABLISHED 23905/php-fpm: pool 
tcp6       0      0 10.70.120.76:39666      10.70.93.72:50051       ESTABLISHED 23902/php-fpm: pool 
tcp6       0      0 10.70.120.76:39670      10.70.93.72:50051       ESTABLISHED 23904/php-fpm: pool 
tcp6       0      0 10.70.120.76:39684      10.70.93.72:50051       ESTABLISHED 23914/php-fpm: pool 
tcp6       0      0 10.70.120.76:39680      10.70.93.72:50051       ESTABLISHED 23908/php-fpm: pool 
tcp6       0      0 10.70.120.76:39750      10.70.93.72:50051       ESTABLISHED 23915/php-fpm: pool 
tcp6       0      0 10.70.120.76:39658      10.70.93.72:50051       ESTABLISHED 23900/php-fpm: pool 
tcp6       0      0 10.70.120.76:39676      10.70.93.72:50051       ESTABLISHED 23910/php-fpm: pool 
tcp6       0      0 10.70.120.76:39592      10.70.93.72:50051       ESTABLISHED 23913/php-fpm: pool 
tcp6       0      0 10.70.120.76:39686      10.70.93.72:50051       ESTABLISHED 23911/php-fpm: pool 
tcp6       0      0 10.70.120.76:39682      10.70.93.72:50051       ESTABLISHED 23916/php-fpm: pool 
tcp6       0      0 10.70.120.76:39566      10.70.93.72:50051       ESTABLISHED 23906/php-fpm: pool 
tcp6       0      0 10.70.120.76:39706      10.70.93.72:50051       ESTABLISHED 23899/php-fpm: pool 
tcp6       0      0 10.70.120.76:39728      10.70.93.72:50051       ESTABLISHED 23918/php-fpm: pool 

This is  grpc server，20  connections by php-fpm
[centos@10.70.93.72 ~]$sudo netstat -tnlpa|grep 50051
tcp6       0      0 :::50051                :::*                    LISTEN      19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39668      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39592      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39316      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39682      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39680      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39728      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39600      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39702      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39706      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39658      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39750      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39684      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39666      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39670      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39676      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:38958      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39686      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39688      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39700      ESTABLISHED 19297/./user-servic
tcp6       0      0 192.168.111.79:50051    10.70.120.76:39566      ESTABLISHED 19297/./user-servic

 
### What did you see instead?
 I want to close 20 connections，not long link.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
@tangleiao Can you please provide more information? In particular, please make sure to fill in all parts of the github issue form and provide a detailed explanation of the problem you're experiencing.

At first glance though, I would say that 1.9 is quite an old version of gRPC. Have you tried upgrading?

**Comment by tangleiao** [comment]
@gnossen  I update some information.  I  want to  close the long link between php-fpm and grpc server, ,but  close function is useless in php code.   Can you help me ?

**Comment by tangleiao** [comment]
@stanley-cheung @gnossen  II want to close the long link between php-fpm and grpc server, ,but close function is useless in php code. Can you help me ?

**Comment by tangleiao** [comment]
@ZhouyihaiDing I want to close the long link between php-fpm and grpc server, ,but close function is useless in php code. Can you help me ?

**Comment by stanley-cheung** [comment]
@tangleiao By default, the underlying grpc connection is "persistent" - this is to make sure that for every subsequent request that hit php-fpm, we don't have to re-create the underlying grpc connection over and over again.

Now I see that you mentioned that you created 20 connections to the backend, did you call `->close()` on all 20 of those? Coz we maintained a "reference count" from the client and we only kill the underlying connection when no more client is maintaining a persistent connection.

**Comment by stanley-cheung** [comment]
This is the relevant piece of code that deals with this: https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/channel.c#L70. Basically, if you have multiple clients referencing the same backend, you need to call `->close()` on every single one of them.

**Comment by tangleiao** [comment]
@stanley-cheung  
I use https://github.com/grpc/grpc-php  lib,  and call ->close() on connection, but these are not closed.

This my client code:
require dirname(FILE).'/vendor/autoload.php';

@include_once dirname(FILE).'/Pb/UserServiceClient.php';
@include_once dirname(FILE).'/Pb/UserResponse.php';
@include_once dirname(FILE).'/Pb/UserRequest.php';
@include_once dirname(FILE).'/GPBMetadata/User.php';

function user($userId)
{
$client = new Pb\UserServiceClient('10.70.93.72:50051', [
'credentials' => Grpc\ChannelCredentials::createInsecure(),
]);
$request = new Pb\UserRequest();
$request->setUserid($userId);
list($reply, $status) = $client->getUserById($request)->wait();
var_dump($client);
//var_dump($status);
1 change; before #2 2 seconds ago
var_dump($client);
//var_dump($status);
$user = $reply->getUser();
print_r(get_object_vars($client));
$client->close();
return $user;
}

**Comment by tangleiao** [comment]
If I have 100 client， every client open  100 php-fpm worker,  I make a grpc server with nginx,  there are 10000 persistent connections on proxy server,  right?

**Comment by ZhouyihaiDing** [comment]
If 100 clients share one channel, then it's one connection.

If you expect the channel shutdown immediately when closing it, it sounds you don't want to persist the channel for further use. Can you please try set `"grpc_target_persist_bound" => 0` for disabling the persistent channel?

**Comment by smallmenu** [comment]
@tangleiao @ZhouyihaiDing 
Hi, I had the same problem.  

PHP 7.1.23 with Nginx + php-fpm。and the grpc is 1.20.0

then I set the "grpc_target_persist_bound" => 0，But it will print some warning in the output。
this will tigger the json parse error in the frontend.

see the channel.c code:

`
php_printf("[Warning] The number of channel for the"
                 " target %s is maxed out bounded.\n", target);
      php_printf("[Warning] Target upper bound: %d. Current size: %d.\n",
                 target_bound_status->upper_bound,
                 target_bound_status->current_count);
      php_printf("[Warning] Target %s will not be persisted.\n", target);
`

But I don't Know how to close this warning, any suggestion?   
Thanks.

**Comment by ZhouyihaiDing** [comment]
@smallmenu  
Probably when the persistent channel support is disabled(`"grpc_target_persist_bound" => 0`), we don't need to dump the warning log.
Can you please create a new issue for it?
