### ISSUE TITLE
gRPC-Core couldn't find openssl files.

### ISSUE THREAD

**Issue by jacksun0124** [grpc/grpc#18886]
I am building a Flutter App. But when I build IOS app via XCode, I got an error message:

`'openssl/bio.h' file not found`
 
This error message from a file called "src/core/tsi/alts/crypt/aes_gcm.cc" which under gRPC-Core.

![2D4921BF-BCD7-47CF-9D42-D53811FE6874](https://user-images.githubusercontent.com/42154731/56832414-ef604880-6839-11e9-9a42-da5d708831b5.png)

However, I do have openssl installed in my Mac. 

when I run: openssl version, I got the following info.

```
openssl version
OpenSSL 1.0.2r  26 Feb 2019
```

I also have openssl in my project folder, 
When I run: sudo find ./ -name "bio.h"  in my project folder, I got the following info 

`.//Pods/BoringSSL-GRPC/include/openssl/bio.h`

If I manually include "bio.h" file to "src/core/tsi/alts/crypt/aes_gcm.cc", I will get another error message and tells me "pb_decode.h" file not found. It seems endless. And manually include files doesn't fix this problem. 

So can anyone help me?

### What version of gRPC and what language are you using?
 
gRPC-C++ (0.0.6)
gRPC-Core (1.17.0)

### What operating system (Linux, Windows,...) and version?
 Mac 10.14.4

### What runtime / compiler are you using (e.g. python version or version of gcc)
 XCode
 
### pod install information
 
ShijiedeMini:ios shijiesun$ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
Fetching podspec for `barcode_scan` from `.symlinks/plugins/barcode_scan/ios`
Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `firebase_database` from `.symlinks/plugins/firebase_database/ios`
Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
Fetching podspec for `flutter_statusbar` from `.symlinks/plugins/flutter_statusbar/ios`
Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
Fetching podspec for `fluwx` from `.symlinks/plugins/fluwx/ios`
Fetching podspec for `geolocator` from `.symlinks/plugins/geolocator/ios`
Fetching podspec for `google_api_availability` from `.symlinks/plugins/google_api_availability/ios`
Fetching podspec for `google_maps_flutter` from `.symlinks/plugins/google_maps_flutter/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
Fetching podspec for `screen` from `.symlinks/plugins/screen/ios`
Fetching podspec for `share` from `.symlinks/plugins/share/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
Fetching podspec for `stripe_payment` from `.symlinks/plugins/stripe_payment/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Downloading dependencies
Installing Bolts (1.9.0)
Installing BoringSSL-GRPC (0.0.2)
Installing FBSDKCoreKit (4.39.1)
Installing FBSDKLoginKit (4.39.1)
Installing FMDB (2.7.5)
Installing Firebase (5.20.2)
Installing FirebaseAnalytics (5.8.1)
Installing FirebaseAnalyticsInterop (1.2.0)
Installing FirebaseAuth (5.4.2)
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore (5.4.1)
Installing FirebaseDatabase (5.1.1)
Installing FirebaseFirestore (1.2.1)
Installing FirebaseInstanceID (3.8.1)
Installing FirebaseMessaging (3.5.0)
Installing FirebaseStorage (3.1.1)
Installing Flutter (1.0.0)
Installing GTMSessionFetcher (1.2.1)
Installing GoogleAppMeasurement (5.8.1)
Installing GoogleMaps (3.1.0)
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.2.0)
Installing GoogleUtilities (5.8.0)
Installing MTBBarcodeScanner (5.0.11)
Installing Protobuf (3.7.0)
Installing Reachability (3.2)
Installing Stripe (15.0.1)
Installing audioplayers (0.0.1)
Installing barcode_scan (0.0.1)
Installing cloud_firestore (0.0.1)
Installing connectivity (0.0.1)
Installing device_info (0.0.1)
Installing firebase_auth (0.0.1)
Installing firebase_core (0.0.1)
Installing firebase_database (0.0.1)
Installing firebase_messaging (0.0.1)
Installing firebase_storage (0.0.1)
Installing flutter_facebook_login (0.0.1)
Installing flutter_local_notifications (0.0.1)
Installing flutter_sound (0.0.1)
Installing flutter_statusbar (0.0.1)
Installing fluttertoast (0.0.2)
Installing fluwx (0.0.1)
Installing gRPC-C++ (0.0.6)
Installing gRPC-Core (1.17.0)
Installing geolocator (3.0.1)
Installing google_api_availability (2.0.0)
Installing google_maps_flutter (0.0.1)
Installing google_sign_in (0.0.1)
Installing image_picker (0.0.1)
Installing leveldb-library (1.20)
Installing nanopb (0.3.901)
Installing path_provider (0.0.1)
Installing permission_handler (3.0.0)
Installing screen (0.0.1)å
Installing share (0.5.2)
Installing shared_preferences (0.0.1)
Installing sqflite (0.0.1)
Installing stripe_payment (0.0.1)
Installing url_launcher (0.0.1)
Installing video_player (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 34 dependencies from the Podfile and 61 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

**Comment by nicolasnoble** [comment]
> gRPC-C++ (0.0.6)
> gRPC-Core (1.17.0)

What?

**Comment by nicolasnoble** [comment]
Also, the pod is for Objective-C, not C++. What are you doing *exactly* ?

**Comment by jacksun0124** [comment]
@nicolasnoble pod dose install this for me, but I am not sure why it is installing this version. Maybe some Flutter packages need this gRPC-Core. You can see pod install info.

**Comment by nicolasnoble** [comment]
I'm so confused. @muxi ?

**Comment by muxi** [comment]
`pod install` is supposed to run prepare_command which replace some of the include directory path for inconsistency, but it looks like your Cocoapods did not do this for you. I am not sure about the reason. What Cocoapods version are you using? Could you share your Podfile?

**Comment by jacksun0124** [comment]
My pod version :
```
pod --version
1.6.1
```


And here is my Podfile 

```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}


# pod 'GoogleAnalytics'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do

  pod 'Firebase/Core'
  pod 'FBSDKCoreKit', '4.39.1' 
  pod 'FBSDKLoginKit', '4.39.1'

  use_frameworks!
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  
  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end

```

**Comment by muxi** [comment]
Thanks! I still don't see anything wrong in the Podfile. If possible, I suggest you clean up the installed pods (`rm -rf Pods` and `rm Podfile.lock`), then `pod install --verbose`. See if that makes the installation correct; if not, the logs from pod install should be able to reveal why prepare_command of gRPC-Core was not run during your installation.

**Comment by muxi** [comment]
I see. Cocoapods pulled the same thing out of your cache. Could you clear your Cocoapods cache (`pod cache clean gRPC-Core') and try again the previous commands?

**Comment by jacksun0124** [comment]
It works!!! Thank you so so so much!! You are awesome!! @muxi

**Comment by muxi** [comment]
All right :) Glad it works.

**Comment by Eralyne** [comment]
Hey, I'm having this same issue except the error is: 'openssl_grpc/ssl.h' file not found.
This error is not restricted to ssl.h but also applies to other openssl files like bio.h

I've attempted doing the solution that @muxi presented with the cache clean and pod reinstall, however, it isn't working for me. I've been at it for three days now and can't find any answer or solution online. I really hope that I'm missing something and can be directed to the right place.

I am also curious as to what the difference between openssl and openssl_grpc is, maybe tha's causing my problem??

Rather than a Flutter app, I'm building a React Native app and I am willing to post my Podfile, or most anything for that matter, if necessary. Any help would be much, much appreciated.

**Comment by muxi** [comment]
'openssl_grpc/ssl.h' not found could be a few things. Basically, check your Header Search Paths in build settings for whatever project including this line of code, check if `"${PODS_ROOT}/Headers/Public/BoringSSL-GRPC"` is there. Then in your project root directory, check if `"Pods/Headers/Public/BoringSSL-GRPC/openssl_grpc/ssl.h"` exists. Based on your symptom it looks like one of them might be missing.

**Comment by Eralyne** [comment]
`Pods/Headers/Public/BoringSSL-GRPC/openssl_grpc/ssl.h` is not present. In fact, the entire `Pods/Headers/Public/BoringSSL-GRPC` folder is missing. I do have a folder in my public headers folder, that appears to be new (git says it's a change), named `openssl_grpc`.

Maybe something changed without me knowing? I never had this issue before and it just became present after running Pod install after not doing so for about a month.

**Comment by muxi** [comment]
Hmm.. it's strange that Cocoapods does not pull it for you. I actually think the suggestions above should be working for you as well. What did you try exactly?

**Comment by Eralyne** [comment]
I've cleared cache for gRPC-Core, cleared all of the pod files and podlock using the commands you providee and reinstalled. After that didn't work, I cleared the cache of every pod file, cleared all pod files and podlock and reinstalled again, which didn't work either.

**Comment by muxi** [comment]
Are you using `use_frameworks!`? If you are using frameworks, the headers are expected to be somewhere else.

**Comment by Eralyne** [comment]
No, I'm not using `use_frameworks!`. Here is my Podfile if it helps:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Comely' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Comely

  # React
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'

  # Crashlytics
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # Facebook
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '~> 4.41.2'
  pod 'FBSDKLoginKit', '~> 4.41.2'
  pod 'FBSDKShareKit', '~> 4.41.2'

  # Navigation
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  # Radar
  pod 'RadarSDK', '~> 2.1.0'
  pod 'react-native-radar', :path => '../node_modules/react-native-radar'

  # Image Crop Picker
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  # Image Resizer
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  # Maps
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Touch Through View
  pod 'RNTouchThroughView', :path => '../node_modules/react-native-touch-through-view'

  # WebView
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # Clear React
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end
end


```

**Comment by muxi** [comment]
Hmm.. I am not sure then. What version of gRPC are you pulling? And your Cocoapods version?

**Comment by Eralyne** [comment]
Pod version is:
`1.7.0.rc.1`

gRPC versions are:
`Using BoringSSL-GRPC (0.0.2)`
`Using gRPC-C++ (0.0.6)`
`Using gRPC-Core (1.17.0)`

**Comment by Eralyne** [comment]
Downgrading Cocoapods to 1.6.1 and reinstalling all of the pods fixed my issue. Thanks for your help @muxi

**Comment by muxi** [comment]
OK! That does not sound good to us though. I'll check if gRPC has any issue with Cocoapods 1.7.0.  Thanks a lot for the heads up.

**Comment by muxi** [comment]
I tried Cocoapods 1.7.0 rc1 but did not encounter any issue.
