### ISSUE TITLE
Method not found: 'Void Grpc.Core.CallOptions..ctor

### ISSUE THREAD

**Issue by ahcho0819** [grpc/grpc#18889]
### What version of gRPC and what language are you using?
 1.19.0 (Tried with 1.20.0 as well) and using C#
 
### What operating system (Linux, Windows,...) and version?
 Window 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Using Visual Studio 2019 
 
### What did you do?
Our extension is using the GRPC to communicate with middle-ware and on the startup of VS2019, it displays an error message to see the ActivityLog.xml
 
### What did you expect to see?
 Very interestingly, our extension works with VS2017 without any problems. I was expecting the same for VS2019.
 
### What did you see instead?
We are seeing the below stack trace in the ActivityLog.xml for VS2019

Method not found: &apos;Void Grpc.Core.CallOptions..ctor(Grpc.Core.Metadata, System.Nullable`1&lt;System.DateTime&gt;, System.Threading.CancellationToken, Grpc.Core.WriteOptions, Grpc.Core.ContextPropagationToken, Grpc.Core.CallCredentials)&apos;.&#x000D;&#x000A;System.MissingMethodException: Method not found: &apos;Void Grpc.Core.CallOptions..ctor(Grpc.Core.Metadata, System.Nullable`1&lt;System.DateTime&gt;, System.Threading.CancellationToken, Grpc.Core.WriteOptions, Grpc.Core.ContextPropagationToken, Grpc.Core.CallCredentials)&
 
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
That's odd, can you provide a VS project that reproduces the problem?  What platforms are you targeting? Can you reproduce also using v1.18.0 or is this a newly introduced in v1.19.0?

**Comment by ahcho0819** [comment]
I don't think I can provide a sample project currently. 
Also, we have already upgraded to v1.19.0 and in order for us to downgrade to 1.18.0 requires our middle application need to be downgraded, so it won't be possible for now. 

Not sure if this is introduced in v1.19.0. The reason for that is we have not tried to use v1.18.0 with VS2019.

**Comment by jtattermusch** [comment]
We've move some of the APIs from Grpc.Core to Grpc.Core.Api as part of https://github.com/grpc/grpc/releases/tag/v1.19.0 release (see https://github.com/grpc/grpc/pull/17778), but the changes shouldn't be causing any problems. Are you seeing the same problem with v1.18.0 as well?

**Comment by ahcho0819** [comment]
I have recently upgraded the Visual Studio 2019 version to 16.1.* and it resolved the issue for me. I think there was something with how Visual Studio was loading the dlls. 

@jtattermusch For your question, we have not tried to downgrade the grpc version.
