### ISSUE TITLE
PHP: Expection "Timeval expects a long" setting a value of 3600000 to TimeVal()

### ISSUE THREAD

**Issue by PaoloNardini** [grpc/grpc#18916]
### What version of gRPC and what language are you using?
gRPC 1.19.0-7.1 Windows DLL x86 TS  
 
### What operating system (Linux, Windows,...) and version?
Windows 10 - DLL version php_grpc-1.19.0-7.1-ts-vc14-x86
 
### What did you do?

One of the packages using this library (Google Ads API) try to set a call timeout value of 3600 seconds (1 hour).

Trying to create a Timeval() passing a PHP value of 3600000 (3600x1000) raise an exception "Timeval expects a long"

This exception is thrown by https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/timeval.c at line 63

Setting a lower value, i.e. 600000 (600 seconds) it's OK.  

Maybe it's a windows X86 related problem? Any workaround? (we cannot set a lower value because it's a Google Api package!)

Thank you.

**Comment by stanley-cheung** [comment]
This should be fixed with #23994 in release 1.33.
