### ISSUE TITLE
gRPC C++ Asynchronous Server Push Notifications

### ISSUE THREAD

**Issue by krishnakoney** [grpc/grpc#18911]
We would like to use gRPC servert(golang) to push notifications/events to gRPC clients(C++) asynchrnously. I am looking for a observer pattern where gRPC client can subscribe for certain events from gRPC server; Once gRPC server has events that client subscribed to, it can PUSH to gRPC client. Can we do this using gRPC ?

Thanks a lot for your help..
krishnakoney

**Comment by a11r** [comment]
This can be achieved through a long lived RPC (unary or streaming). Unsolicited push notifications are not supported in gRPC and are not on the RoadMap.
