### ISSUE TITLE
Need additional support to debug why a stream is terminated in a Python client?

### ISSUE THREAD

**Issue by ykhsu** [grpc/grpc#18924]
### What version of gRPC and what language are you using?
Python client - gRPC 1.18.0 & 1.7.0 
C++ server - gRPC 1.18.0
 
### What operating system (Linux, Windows,...) and version?
Client in CentOS 7.2 and Windows 10
Server in CentOS 7.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Client - python 2.7.16
 
### What did you do?
I have a simple gRPC subscription client like:
```
try:
    responses = stub.Subscribe(req_iterator, options.timeout, metadata=metadata)
    for response in responses:
        if response.HasField('sync_response'):
            # do something
        elif response.HasField('update'):
            # do something
```
The client works as expected in gRPC 1.7.0 with the server (C++ in 1.7 then 1.18). But once we upgraded the client to 1.18, the subscription stream always ends right after getting a `sync_response` and `update` protobuf message.

Debugging it led me to [_Rendezvous._next()](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py) where its `_state.code` has been changed to `grpc.StatusCode.OK`. Unless I missed something, this is set by the wrapped C++ implementation in a separate thread. The server team looked at their log and concluded the client closed this stream. But the client isn't doing anything but wait... So I am stuck; I can't determine what actually happened in the wrapped C++code to do something. Turning on GRPC_TRACE does not help much since the output is really not specific enough to understand at the application level. Looking at the output, I just wonder why this is so difficult for gRPC to let the application know (1) who closed the stream and (2) if it is the client, why?

For now, we have to keep running the client under 1.7.0.

### What did you expect to see?
Critical information with regard to stream state changes and operations (who & what) taken place in the wrapped gRPC implementation should be made meaningful to applications; e.g.

- the stream termination detected (i.e., the server closed the stream)
- closing the stream because <reason>
 
### What did you see instead?
 Lots of 
```
I0430 15:16:24.858246379   18320 channel_stack.cc:226]       OP[connected:0x8cee418]:  RECV_MESSAGE
I0430 15:16:24.858252866   18320 chttp2_transport.cc:1683]   perform_stream_op[s=0x8ceef78]:  RECV_MESSAGE
I0430 15:16:24.858259090   18320 call_combiner.cc:153]       ==> grpc_call_combiner_stop() [0x8ced320] [passed batch to transport]
I0430 15:16:24.858264920   18320 call_combiner.cc:160]         size: 1 -> 0
I0430 15:16:24.858269876   18320 call_combiner.cc:189]         queue empty
I0430 15:16:24.858276621   18320 chttp2_transport.cc:1379]   perform_stream_op_locked:  RECV_MESSAGE; on_complete = (nil)
I0430 15:16:24.858288782   18320 stream_lists.cc:125]        0x8eef950[3][cli]: add to writable
I0430 15:16:24.858312429   18320 chttp2_transport.cc:1228]   complete_closure_step: t=0x8eef950 0x7f5db0001fe8 refs=0 flags=0x0000 desc=op->on_complete err="No Error" write_state=IDLE

```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by lidizheng** [comment]
@ykhsu Do you think you can create a minimum reproduction case? Also, can you try out the possible tracing parameters in `GRPC_TRACE` (see [environment_variables.md](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md))?

**Comment by ykhsu** [comment]
@lidizheng I did tried `GRPC_TRACE`. As shown below, I can guess/see the stream was closed but it still does not tell me who closed it and why. I am left with the option of trying to understand the problem by reading source code like [lockfree_event.cc](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/lockfree_event.cc). This just seems so wrong to ask someone who only uses gRPC to write an application to pay such a price. That's why I wrote this up.

I am not sure what you meant by creating a minimum reproduction case. The problem occurred in a piece of code just like I stated above (IMO, a pretty standard code template for a subscription stream client application). It is reproducible every time when it runs on gRPC 1.18 but no problem at all in gRPC 1.7. It would be easier if this subscription does not work in gRPC 1.18 at all (instead of after getting two messages successfully). I am also playing with different versions in between trying to nail down the cause. Again, this seems so wrong :-)

```
I0501 13:07:53.629693192   22133 completion_queue.cc:963]    grpc_completion_queue_next(cq=0x6faa280, deadline=gpr_timespec { tv_sec: 1556730473, tv_nsec: 829688841, clock_type: 1 }, reserved=(nil))
I0501 13:07:53.629704221   22133 ev_epoll1_linux.cc:748]     PS:0x6faa348 BEGIN_STARTS:0x7f15c7294ce0
I0501 13:07:53.629710962   22133 ev_epoll1_linux.cc:767]     PS:0x6faa348 BEGIN_REORG:0x7f15c7294ce0 kick_state=UNKICKED is_reassigning=1
I0501 13:07:53.629718645   22133 ev_epoll1_linux.cc:836]     PS:0x6faa348 BEGIN_DONE:0x7f15c7294ce0 kick_state=DESIGNATED_POLLER shutdown=0 kicked_without_poller: 0
I0501 13:07:53.803030723   22133 ev_epoll1_linux.cc:728]     ps: 0x6faa348 poll got 1 events
E0501 13:07:53.803059362   22133 lockfree_event.cc:213]      LockfreeEvent::SetReady: 0x7f15a0001088 curr=0x6fc4d40
E0501 13:07:53.803069077   22133 lockfree_event.cc:213]      LockfreeEvent::SetReady: 0x7f15a0001090 curr=0x2
I0501 13:07:53.803075868   22133 ev_epoll1_linux.cc:928]     PS:0x6faa348 END_WORKER:0x7f15c7294ce0
I0501 13:07:53.803082479   22133 ev_epoll1_linux.cc:908]      .. mark pollset 0x6faa348 inactive
I0501 13:07:53.803089274   22133 tcp_posix.cc:535]           TCP:0x6fc4ba0 got_read: "No Error"
I0501 13:07:53.803096395   22133 tcp_posix.cc:526]           TCP:0x6fc4ba0 do_read
I0501 13:07:53.803110966   22133 tcp_posix.cc:411]           TCP:0x6fc4ba0 call_cb 0x6f78028 0x7f15ad107c10:0x6f77fd0
I0501 13:07:53.803117283   22133 tcp_posix.cc:414]           read: error="No Error"
I0501 13:07:53.803129814   22133 tcp_posix.cc:419]           READ 0x6fc4ba0 (peer=ipv4:135.104.234.62:8980): 17 03 03 00 33 00 00 00 00 00 00 00 06 d3 9f bc 96 70 0f a4 42 c3 30 88 38 ee 88 e2 5a 86 99 72 b2 8b 2b dd b9 be e1 f2 e5 7d 82 28 ee 21 fb fe 2a b2 19 a8 09 36 15 c5 '....3............p..B.0.8...Z..r..+......}.(.!..*....6..'
I0501 13:07:53.803207250   22133 secure_endpoint.cc:163]     READ 0x6f77fd0: 00 00 01 01 05 00 00 00 03 be 00 00 08 06 00 00 00 00 00 00 00 00 00 00 00 00 01 '...........................'
I0501 13:07:53.803228344   22133 parsing.cc:661]             parsing trailing_metadata
I0501 13:07:53.803241343   22133 hpack_parser.cc:636]        Decode: 'grpc-status: 0', elem_interned=1 [3], k_interned=1, v_interned=1
I0501 13:07:53.803265988   22133 parsing.cc:503]             HTTP:3:TRL:CLI: grpc-status: 30 '0'
I0501 13:07:53.803277031   22133 call_combiner.cc:116]       ==> grpc_call_combiner_start() [0x71d0940] closure=0x71d1c20 [recv_message_ready] error="No Error"
I0501 13:07:53.803283208   22133 call_combiner.cc:125]         size: 0 -> 1
I0501 13:07:53.803288251   22133 call_combiner.cc:134]         EXECUTING IMMEDIATELY
I0501 13:07:53.803296226   22133 stream_lists.cc:93]         0x7192710[3][cli]: remove from writable
I0501 13:07:53.803304836   22133 call_combiner.cc:116]       ==> grpc_call_combiner_start() [0x71d0940] closure=0x71d1db8 [recv_trailing_metadata_ready] error="No Error"
I0501 13:07:53.803310162   22133 call_combiner.cc:125]         size: 1 -> 2
I0501 13:07:53.803314952   22133 call_combiner.cc:140]         QUEUING
I0501 13:07:53.803322807   22133 chttp2_transport.cc:829]    W:0x7192710 CLIENT state IDLE -> WRITING [PING_RESPONSE]
I0501 13:07:53.803333219   22133 call_combiner.cc:153]       ==> grpc_call_combiner_stop() [0x71d0940] [recv_message_ready]
I0501 13:07:53.803338842   22133 call_combiner.cc:160]         size: 2 -> 1
I0501 13:07:53.803343845   22133 call_combiner.cc:167]         checking queue
I0501 13:07:53.803348997   22133 call_combiner.cc:181]         EXECUTING FROM QUEUE: closure=0x71d1db8 error="No Error"
I0501 13:07:53.803357167   22133 completion_queue.cc:699]    cq_end_op_for_next(cq=0x6faa280, tag=0x7157b90, error="No Error", done=0x7f15ad0b9b60, done_arg=0x7f158c0025c0, storage=0x7f158c002610)
I0501 13:07:53.803371727   22133 ev_epoll1_linux.cc:1165]     .. kicked while waking up
I0501 13:07:53.803377704   22133 tcp_posix.cc:535]           TCP:0x6fc4ba0 got_read: "No Error"
I0501 13:07:53.803383201   22133 tcp_posix.cc:526]           TCP:0x6fc4ba0 do_read
I0501 13:07:53.803391200   22133 tcp_posix.cc:253]           TCP:0x6fc4ba0 notify_on_read
E0501 13:07:53.803397557   22133 lockfree_event.cc:98]       LockfreeEvent::NotifyOn: 0x7f15a0001088 curr=(nil) closure=0x6fc4d40
I0501 13:07:53.803407048   22133 call_combiner.cc:153]       ==> grpc_call_combiner_stop() [0x71d0940] [recv_trailing_metadata_ready]
I0501 13:07:53.803412447   22133 call_combiner.cc:160]         size: 1 -> 0
I0501 13:07:53.803417256   22133 call_combiner.cc:189]         queue empty
I0501 13:07:53.803430939   22133 completion_queue.cc:699]    cq_end_op_for_next(cq=0x6faa280, tag=0x7157290, error="No Error", done=0x7f15ad0b9b60, done_arg=
```

**Comment by lidizheng** [comment]
@ykhsu By reproduction case, ideally, I mean a code snippet that can easily reproduce the bug you are reporting (sometime it can be challenging to write). The subscription mode (or streaming calls) is well-tested across languages, so you might hit some corner cases.

The info you provided is not sufficient for me to guess the root cause. From the section you provided, I can see the Python client received trailing metadata `grpc-status: 0` instead of `CANCELLED(8)`.

In addition, can you please try `GRPC_VERBOSITY=DEBUG` and `GRPC_TRACE=connectivity_state,api,channel,call_error`? The log might be super-long, you can use https://gist.github.com/ to share it.

**Comment by ykhsu** [comment]
@lidizheng As you suggested, I created  [subscription_grpc_1_18_0.log](https://gist.github.com/ykhsu/b0c558940c481abdfc5b821e1486f9d4#file-subscription_grpc_1_18_0-log) . But it is actually pretty short. So I decided to add [subscription_grpc_debug_all_1_18_0.log](https://gist.github.com/ykhsu/b0c558940c481abdfc5b821e1486f9d4#file-subscription_grpc_debug_all_1_18_0-log) with `GRACE_TRACE=all`.

Though the subscription part of the code is pretty straightforward, it is difficult to dig out a snippet with lots of other data modeling works around it. Thank you so much for the help and suggestion!

**Comment by lidizheng** [comment]
@ykhsu Thank you for providing the detailed log. I inspected the code, and found no error or cancellation on the client-side (1229:1425). But the server does sent ending frame with trailing metadata (:1379), which means the cpp server implementation might accidentally ended the method handler too early.

Can you provide the tracing log from the server side? Also, which C++ API are you using, sync API or async API?

**Comment by ykhsu** [comment]
@lidizheng The person on the server is gone for the day. I can try but likely won't be able to. I assume you want a log with GRPC_TRACE on as earlier. Let me know if otherwise.

FYI, from my last exchange with him, the server side's ran a thread with following code:
```
      // just wait here until the stream is closed from the other side...
      while(stream->Read(&request)) {
        _TRACE("got an update of the SubscribeReqest...");
      }
      // When we exit the loop above it can be either because user closed
      // the session, or because we cancelled it on server side.
      // grpc::ServerContext requires us to make sure that StatusCode::CANCELLED is
      // returned if the session is closed on server side.
      if (context->IsCancelled()) {
        result = Status(grpc::StatusCode::CANCELLED, "Session was cancelled!");
        _TRACE("Session was cancelled!");
      }
      _TRACE("done with sending notifications...");
```
With ::[Read()](https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_reader_writer.html#adc1925f519a8d1dc7b7101d37513774b) from gRPC framework defines its return value as follows:
```
bool grpc::ServerReaderWriter< W, R >::Read ( R *  msg)

Returns
    false when there will be no more incoming messages, either because the other side has called WritesDone() or the stream has failed (or been cancelled). 
```
Without seeing `Session was cancelled!` on the server side during the test, we assumed the client closed the stream.
Again, thank for the support.

**Comment by ykhsu** [comment]
@lidizheng I still wonder whether there are other possibilities since the same client running under gRPC 1.7 won't get the same treatment from the server?

**Comment by lidizheng** [comment]
@ykhsu The code seems legit to me. Yes, I would like to see the tracing log.

Since I haven't got a reproduction case, do you think you can help me bisect the first buggy commit? You can clone the gRPC repo, build the Python library, and bisect between 1.7 to 1.18. The process will roughly look like this:

```shell
# Start bisecting
$ git clone git@github.com:grpc/grpc.git
$ git bisect start
$ git checkout v1.7.0
$ git bisect good
$ git checkout v1.18.0
$ git bisect bad

# Building gRPC Python, then use the Python in the Virtualenv
$ git clean -xdf
$ git submodule update --init
$ tools/run_tests/run_tests.py -l python --compiler python2.7 --newline_on_success -j 8 --build_only
$ source py27_native/bin/activate

# Run your tests, see if it fails;
# If failed
$ git bisect bad
# If passed
$ git bisect good
# Then go back to building gRPC Python again.
```

**Comment by ykhsu** [comment]
@lidizheng Since this gRPC server is just a process among the hundreds in a device, we could not catch GRPC debug output in both its own trace or the device's console at this time. This will take an effort with SW change and new build. I will let you know once we are able to get the log as you expected.

I'll try what you suggested with gRPC Python even though I am not sure what it means...

**Comment by tejaskumark** [comment]
@lidizheng I have also faced same issue with Python Client and Go Server.

**Comment by tejaskumark** [comment]
Attaching debug logs.
[debug.txt](https://github.com/grpc/grpc/files/3142273/debug.txt)

**Comment by lidizheng** [comment]
@tejaskumark Which gRPC Python version are you using? And your platform?
Do you think you can help me to identify which first broken major version? You can install each major version with:
```
pip install grpcio==1.R.0
```

**Comment by tejaskumark** [comment]
@lidizheng I did bisect from v1.7.0 to v1.18.0, and find no good commit where stream works as expected. Also my experience is same, it was working on python v1.18.0 and after some server side changes(related to gNMI/gNXI) streaming broke. So I do think issue lies somewhere else, but can not sure where.

**Comment by lidizheng** [comment]
@tejaskumark Thank you for the bisect effort :)
There is not much I can do as an outsider of your project without a reproduction case. Other than that, If you can provide more detail or log, I can help inspect them.

**Comment by ykhsu** [comment]
@lidizheng While the server team is working on getting GRPC trace on v1.18.0, I got a chance to test against their previous release implemented in gRPC 1.14.0. With the client also running v1.14.0, the subscription stream would end after 1st update as before; the log is documented in [grpc_1_14_0.log](https://gist.github.com/ykhsu/716dae53f6fcd2b357b451a4b490566d#file-grpc_1_14_0-log) .
However, I did not see "**_trailing_metadata_**" this time. 

If I switch the client back to v1.7.0, everything works.

**Comment by ykhsu** [comment]
@lidizheng  Got a break!
Looking back at changes we made from past years, I realize we had this problem when gRPC subscription interface was added to our support initially. During the time, we did encounter the same problem with gRPC v1.7.0. But not knowing enough then (and remain so now), we tried and had it fixed it by replacing the last line of the following in __consume_request_iterator_() in [_channel.py](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py) :
```
                            state.condition.wait(condition_wait_timeout)
                            cygrpc.block_if_fork_in_progress(state)
                            if state.code is None:
```
to 
```
                            if state.code is not  None:
```
I just did not remember this till today. After making the same change for v1.18.0, the problem is gone. Still I don't know if we should have done something different in our own code. Hope to get a feedback.

Also, the original intent of why I wrote this issue stands. There should be better information provided for applications to understand such situations.

**Comment by lidizheng** [comment]
@ykhsu That looks promising! Can you try to use [pdb](https://docs.python.org/3/library/pdb.html) `import pdb; pdb.set_trace()` in `_consume_request_iterator` to see what happened? The deletion of those lines doesn't make sense to me...

**Comment by ykhsu** [comment]
@lidizheng As stated early, only "**the last line**" (and not all) of the code snippet was replaced.

**Comment by lidizheng** [comment]
@ykhsu Oh. Okay. Thank you for the clarification. I will try to reproduce the issue around these lines. It does look like a bug in Python client.

**Comment by tejaskumark** [comment]
@lidizheng Code change suggested by @ykhsu also works for me. So this is a python client bug only.

**Comment by MrSaints** [comment]
Is this related https://github.com/grpc/grpc/commit/e30dcefeab460ccec0f5583da329a0e9cb2428f5#diff-e87a8cfa4c9a2b7758e5ab8b8cbbf5d7 ?
