### ISSUE TITLE
Bazel RBE Asan failure on test/core/end2end/h2_http_proxy_test@disappearing_server@poller=epoll1

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#18939]
https://source.cloud.google.com/results/invocations/db80efd1-4aa7-43e4-9903-1d9879263a86/targets

```
exited with error code 134
```

**Comment by murgatroid99** [comment]
This looks like the same failure as #18840

Also seen in UBSAN: https://source.cloud.google.com/results/invocations/a821af9a-2b1d-4bae-ad2b-905e2d9f24c4/targets

**Comment by yashykt** [comment]
Closing since it is a dup of #18840
