### ISSUE TITLE
reserved word RELEASE in atomic.h causes compilation issue

### ISSUE THREAD

**Issue by alan-yjzhang** [grpc/grpc#18936]
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by nicolasnoble** [comment]
Please file a proper issue.
