### ISSUE TITLE
frequent UNAVAILABLE error on Windows when using Google Text-to-Speech

### ISSUE THREAD

**Issue by shifeng-genesys** [grpc/grpc#18938]
### What version of gRPC and what language are you using?
1.3.x 
 
### What operating system (Linux, Windows,...) and version?
Windows 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
VS2013 
 
### What did you do?
We just call Google clould Text-to-Speach function ::grpc::Status SynthesizeSpeech() in our program. From time to time, we got an UNAVAILABLE error. Normally a retry would have the function work.
 
### What did you expect to see?
We barely saw the UNAVAILABLE error on Linux. So we'd expect it should be the same on Windows. 
 
### What did you see instead?
We've seen a few UNAVAILABLE on Windows with error message showing "Endpoint read failed".

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
None

**Comment by a11r** [comment]
This error report needs a couple of extra details to be actionable.
1. A usable reproduction of the issue.
2. Evidence that this is not an issue with the environment.
