### ISSUE TITLE
I am using gRPC version 1.20.0 from pecl site pre-compiled DLL using PHP version 7.2.6.

### ISSUE THREAD

**Issue by adeelmichael** [grpc/grpc#18951]
I am using gRPC version 1.20.0 from pecl site pre-compiled DLL using PHP version 7.2.6. 
Operating system is windows 10.
 As for PHP it is PHP compiler.
 I download php_grpc.dll from https://pecl.php.net/package/gRPC/1.20.0/windows. My xampp system architecture is x86 so I chosed  for php 7.2 version( 7.2 Non Thread Safe (NTS) x86  ).
I extracted the zip and copied dll file to php/ext/php_grpc.dll.
Then I opened my php.ini file and wrote under dynamic extensions
extension=grpc
Error I get
PHP startup: unable to load dynamic library 'grpc'  (tried F:\devs\php\ext\grpc) the specified module could not be found F:\devs\php\ext\php_grpc.dll in unknown in line 0;

I  expect to see no error as I have configured it correctly same as I configure other extensions for PHP. So it should be loading with no errors.

PHP startup: unable to load dynamic library 'grpc'  (tried F:\devs\php\ext\grpc) the specified module could not be found F:\devs\php\ext\php_grpc.dll in unknown in line 0;

For you reference I am sharing my php.ini file 
[php_ini.zip](https://github.com/grpc/grpc/files/3142358/php_ini.zip)

_Originally posted by @adeelmichael in https://github.com/grpc/grpc/issues/18949#issuecomment-489118771_

**Comment by stanley-cheung** [comment]
Did this work for you for older versions of the grpc extension?

**Comment by adeelmichael** [comment]
I have tried an older version i.e 1.19.0 and 1.18.0 but same error. Can you please help?

**Comment by adeelmichael** [comment]
Is there any other way to install grpc extension on windows 10? 
Can I use it directly in laravel by composer without installing on windows?

**Comment by adeelmichael** [comment]
Hi Stanley,

I solved my problem, I was downloading my grpc extension from pecl site but then found this link to download

https://windows.php.net/downloads/pecl/releases/grpc/1.10.0/

this solved my problem.


Thanks,
