### ISSUE TITLE
Environment markers not having desired effect in armv71 binary distribution

### ISSUE THREAD

**Issue by pp81381** [grpc/grpc#18957]
### What version of gRPC and what language are you using?

grpc 1.20.1
Python 3.5.3
 
### What operating system (Linux, Windows,...) and version?

`Raspbian GNU/Linux 9 (stretch)`
`Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.5.3
 
### What did you do?

pip install the binary distribution.   Here is a script to reproduce the issue.

```shell
#! /bin/bash
VENVDIR=/tmp/testvenv
LOGFILE=/tmp/pip3.log
/bin/rm -rf "$VENVDIR" "$LOGFILE"
python3 -m venv "$VENVDIR"
source "$VENVDIR"/bin/activate
python --version
pip3 install --upgrade pip setuptools
pip3 --no-cache --log "$LOGFILE" install grpcio
pip list
```

### What did you expect to see?

```
Package       Version
------------- -------
grpcio        1.20.1 
pip           19.1   
pkg-resources 0.0.0  
setuptools    41.0.1 
six           1.12.0 
```
 
### What did you see instead?

The enum34 and futures packages appear despite the environment markers added in commit `91db94b278b12a6de7afe69805d3678bb670fd46`

```
Package       Version
------------- -------
enum34        1.1.6  
futures       3.1.1  
grpcio        1.20.1 
pip           19.1   
pkg-resources 0.0.0  
setuptools    41.0.1 
six           1.12.0 
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

Version 1.19.0 works
Version 1.20.1 works if I use the source distribution (e.g. `pip3 --no-cache --log "$LOGFILE" install --no-binary grpcio grpcio`)
Version 1.20.1 works with Python 3.5.3 on i686 so this issue seems to be restricted to the armv71 bdist
I checked last night's nightly build and it is still an issue in that.   (As an aside, why are there two identical versions of the armv71 bdist?)

**Comment by gnossen** [comment]
You're right. The METADATA file for the ARM distribution does not have the environment markers. Good catch. Looking into this.
