### ISSUE TITLE
Undefined reference to gflags

### ISSUE THREAD

**Issue by xkszltl** [grpc/grpc#18974]
### What version of gRPC and what language are you using?

Both master/v1.20.1
C++
 
### What operating system (Linux, Windows,...) and version?

CentOS 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 8.2.1 (devtoolset-8)
 
### What did you do?

Build with CMake/Ninja (with tests) and pre-built gflags.

### What did you see instead?

Linking error with undefined reference to gflags.

![image](https://user-images.githubusercontent.com/5203025/57292260-350ce480-7076-11e9-9b15-b5504c3af3a8.png)

### Anything else we should know about your project / environment?

This may be the issue.
https://github.com/grpc/grpc/blob/7741e806a213cba63c96234f16d712a8aa101a49/cmake/gflags.cmake#L29-L32

If I build gflags as shared lib, the correct target should be gflags::gflags_shared

![image](https://user-images.githubusercontent.com/5203025/57292229-26bec880-7076-11e9-9faa-5bd7ceb2e59c.png)

**Comment by xkszltl** [comment]
After some investigation, the issue is not related to the `gflags::gflags_shared` above as `gflags::gflags` is always defined.

The actual fix is to add `-DGFLAGS_USE_TARGET_NAMESPACE=ON` based on `gflags-config.cmake`
![image](https://user-images.githubusercontent.com/5203025/57293828-a484d300-707a-11e9-9ce3-d16860753590.png)

Since the switch is off by default, I would suggest to either flip it on in grpc, or at least fail the configuration.
The current `if (TARGET)` approach doesn't look good without an else block.

**Comment by nicolasnoble** [comment]
Why are you building the tests?

**Comment by xkszltl** [comment]
Usually I build unit tests and run them for anything I build for verification.
For gRPC I don't know how to run those tests but it is still good to build them to verify that symbols are there, no weird compiling issues and etc.

**Comment by nicolasnoble** [comment]
Right. While I appreciate the sentiment, building the tests for gRPC at the moment is a very involved process. We have some plans to heavily reduce the tests to only a few smoketests in our Makefile and CMakefile, and use Bazel exclusively for our internal testing. Right now, I can't recommend anyone external to try and run our tests.

**Comment by xkszltl** [comment]
Thanks for these info.
If that's the case I won't put hard dependency on this.
It may also be helpful to print a warning message in cmake when people try to build test, just to mentioned error is expected.

I was able to build tests successfully at this point with some work-arounds.
One of them is `-DGFLAGS_USE_TARGET_NAMESPACE=ON` and additional `-I` as in #18975

**Comment by apolcyn** [comment]
Closing since this issue looks resolved
