### ISSUE TITLE
greeter_async_client core at centos6.5

### ISSUE THREAD

**Issue by danhuiwang** [grpc/grpc#18977]
### What version of gRPC and what language are you using?
 master and C++
 
### What operating system (Linux, Windows,...) and version?
 linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 hellworld  greeter_async_client run at centos 6.5
 
### What did you see instead?
centos 6.5 
cpp examples hellworld  greeter_async_client  core at grpc_slice_hash
cpp examples hellworld  greeter_async_server run nomal

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
the same build step，cpp examples hellworld  greeter_async_client  run nomal at ubuntu 16.04

**Comment by apolcyn** [comment]
> cpp examples hellworld greeter_async_client core at grpc_slice_hash

Sorry I'm not certain what problem happened. Did your `greeter_async_client` program crash, or fail to build?

**Comment by danhuiwang** [comment]
yes , greeter_async_client program crash on centos 6.5,   but nomal  on centos 7

**Comment by apolcyn** [comment]
Do you have a trace available?

**Comment by nicolasnoble** [comment]
Please provide reproduction steps with for example a Dockerfile that we can run ourselves.

**Comment by danhuiwang** [comment]
> Do you have a trace available?

it crash at grpc_slice_hash

**Comment by danhuiwang** [comment]
> Please provide reproduction steps with for example a Dockerfile that we can run ourselves.

os centos 6.5
1、yum install -y gcc-c++ autoconf libtool
yum groupinstall -y "Development Tools"
2、install gcc 4.8.5
3、build grpc
git clone https://github.com/grpc/grpc.git
cd grpc
git submodule update --init
cd third_party/protobuf/
./autogen
./configure
make
make install
ldconfig
which protoc
protoc --version

cd ../..
make
make install
4、build demo
cd examples/cpp/helloworld/
make
5、run greeter_async_client
./greeter_async_client
then it crash

**Comment by nicolasnoble** [comment]
So, digging a bit, there is no CentOS 6.5 Docker image. This version of the operating system isn't supported anymore: https://github.com/CentOS/sig-cloud-instance-images/issues/13 - in fact, only CentOS 6.10 and above are still currently supported.

This means I can't even begin trying to reproduce your problem. Please try and provide us with a full Dockerfile that exhibits your issue. We are not redhat experts, and we can't navigate how to use this system to reproduce your issue if you don't provide us with an real reproduction method.

Also, just saying "it crash at grpc_slice_hash" isn't enough. Provide maybe a gdb backtrace or something that shows the full stacktrace of the crash.

**Comment by danhuiwang** [comment]
> So, digging a bit, there is no CentOS 6.5 Docker image. This version of the operating system isn't supported anymore: [CentOS/sig-cloud-instance-images#13](https://github.com/CentOS/sig-cloud-instance-images/issues/13) - in fact, only CentOS 6.10 and above are still currently supported.
> 
> This means I can't even begin trying to reproduce your problem. Please try and provide us with a full Dockerfile that exhibits your issue. We are not redhat experts, and we can't navigate how to use this system to reproduce your issue if you don't provide us with an real reproduction method.
> 
> Also, just saying "it crash at grpc_slice_hash" isn't enough. Provide maybe a gdb backtrace or something that shows the full stacktrace of the crash.

ok, thank you.

**Comment by AspirinSJL** [comment]
Please reopen this bug when a stacktrace is available.
