### ISSUE TITLE
Python Channels with Identical Server Strings do not share TCP Connections on Windows

### ISSUE THREAD

**Issue by CodArs-van** [grpc/grpc#18985]
### What version of gRPC and what language are you using?
v1.20.1
Client: Python 3.7.1
Server: C++
 
### What operating system (Linux, Windows,...) and version?
Windows 10 1809 (OS Build 17763.523)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python: 3.7.1
Compiler: Visual Studio 2017 x64
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Repro steps:
1. Define a proto file like this:
![image](https://user-images.githubusercontent.com/25216338/57342148-5dd2bf80-70f2-11e9-9389-442159e232c5.png)
2. Implement server in C++ and start the server
![image](https://user-images.githubusercontent.com/25216338/57342173-7511ad00-70f2-11e9-8ee8-298fe60c0bd1.png)
3. Run python client for different numbers
![image](https://user-images.githubusercontent.com/25216338/57342194-8eb2f480-70f2-11e9-817d-3ad11c5c7a23.png)
 
### What did you expect to see?
I expect success completion of the 100000 calls.
 
### What did you see instead?
The python client runs normally at the beginning, then after some iteration it starts to suffer from _Rendezvous exception:

This is from the beginning:
![image](https://user-images.githubusercontent.com/25216338/57342271-e5203300-70f2-11e9-872f-e36430e5791c.png)

This is when I saw the error happening:
![image](https://user-images.githubusercontent.com/25216338/57342283-f406e580-70f2-11e9-8a2c-07137aba07e5.png)
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by lidizheng** [comment]
A potentially related issue with Python client & C++ server: https://github.com/grpc/grpc/issues/18626

**Comment by gnossen** [comment]
This looks like a [simple case of running out of ports](https://blogs.msdn.microsoft.com/dgorti/2005/09/18/only-one-usage-of-each-socket-address-protocolnetwork-addressport-is-normally-permitted/). Instead of creating your channel in `CalculateExp`, try creating it *once* in your `main` function and simply passing it into `CalculateExp`. This will ensure that you consume only a single port for all RPCs and should also decrease latency pretty signficantly.

**Comment by CodArs-van** [comment]
@gnossen I am trying to simulate a scenario where tons of client requests are coming and each time the client will need to re-bind the server ip & ports and run the CalculateExp again, so I do need to write code this way.
Changing the code as you suggested will likely workaround the issue, but that doesn't hide the fact that there is a bug in the Python library, I've tried the same client code written in C++ and it worked perfectly fine in C++.

**Comment by gnossen** [comment]
The Windows kernel only guarantees 65,535 ports. This is a *kernel* limitation. What's more, the kernel will keep those sockets in the `TIME_WAIT` state for four minutes. You can verify that this is what's happening with `netstat`. Without using a socket option like `SO_REUSEADDR` or adjusting the `MaxUserPort` or `TcpTimedWaitDelay` option, there is no possibility of 100,000 independent clients being spun up in less than 6.1 minutes.

 I would be surprised if a C++ client were able to somehow overcome this limitation. Can you provide a sample of your successful C++ client?

**Comment by CodArs-van** [comment]
Interesting. To double check I tested C++ one more time and it passed again.

![image](https://user-images.githubusercontent.com/25216338/57411267-e3fa0f00-71a1-11e9-983d-52c7d71b72fd.png)

Here's the cpp client code I use:
```cpp
#include <iostream>
#include <chrono>
#include <random>
#include <memory>

#include <grpcpp/grpcpp.h>
#include "../gRPCPerfServer/PerfService.grpc.pb.h"
#include "../gRPCPerfServer/PerfService.pb.h"

using grpc::Channel;
using grpc::ClientContext;
using grpc::Status;
using grpc::ServerReader;
using PerfMeasure::PerfService;
using PerfMeasure::ExpReqRes;
using PerfMeasure::ScaleReqRes;
using namespace std;

inline float RunRemoteExp(float val)
{
    auto client = PerfService::NewStub(grpc::CreateChannel("localhost:50052", grpc::InsecureChannelCredentials()));
    ClientContext context;
    ExpReqRes request;
    ExpReqRes reply;
    request.set_val(val);
    auto status = client->Exp(&context, request, &reply);
    return reply.val();
}

int main(int argc, char** argv)
{
    std::random_device rd;
    std::mt19937 mt(rd());
    std::uniform_real_distribution<float> dist(1.0, 10.0);
    const int n = 100000;
    vector<float> vecfs(n);

    for (int i = 0; i < n; ++i)
    {
        vecfs[i] = dist(mt);
    }

    auto start = chrono::steady_clock::now();
    for (int i = 0; i < n; ++i)
    {
        auto ret = RunRemoteExp(vecfs[i]);

        if (i % 10000 == 0)
        {
            auto mid = chrono::steady_clock::now();
            cout << chrono::duration_cast<chrono::seconds>(mid - start).count() << endl;
        }
    }
    auto end = chrono::steady_clock::now();
    cout << chrono::duration_cast<chrono::seconds>(end - start).count() << endl;

    return 0;
}
```

**Comment by CodArs-van** [comment]
Note Python client consistently fails after some 30K calls, while C++ client passes all 100K calls.

**Comment by gnossen** [comment]
Interesting. I just talked with @nicolasnoble about the intended behavior of channels in gRPC core. If two channels are instantiated for the same destination, they should share a single TCP connection. This is happening in C++, while, for whatever reason, it *isn't* happening in Python. Looking into things from that angle.

**Comment by CodArs-van** [comment]
Thanks! Let me know if you need further information from me.

**Comment by nicolasnoble** [comment]
Also, in the future, please do not post screenshots of code, but the code itself, so it can be copy-pastable.

**Comment by gnossen** [comment]
As a quick update, I have so far been unsuccessful in reproducing on Linux. This appears to be a Windows-only issue.

**Comment by CodArs-van** [comment]
@nicolasnoble  Apologies, I'll post the code in text should I file new bugs later. ^_^

**Comment by gnossen** [comment]
@CodArs-van Could you please help me gather some debug logs? Let's reduce down to 2 channels and turn up logging by setting the environment variables

```
GRPC_VERBOSITY=DEBUG
GRPC_TRACE=all
```

Please include the logs for both C++ and Python so we can analyze the differences. Thanks!

**Comment by CodArs-van** [comment]
This is the client log:
[client.log](https://github.com/grpc/grpc/files/3163942/client.log)

Let me try to give you a server log later, the server becomes much slower after enabling the log, now it has been running for 15 minutes and the client hasn't crashed yet.

**Comment by gnossen** [comment]
I don't think we'll actually need the server log. This looks like a purely client-side issue. We'll just need the C++ client log and the Python client log.

**Comment by CodArs-van** [comment]
@gnossen Both cpp and python client logs are uploaded, please take a look.

**Comment by mehrdada** [comment]
The `with` statement ends up closing the channel on each RPC. You can happily reuse channels. No reason you should close it right away if you intend to reuse.

**Comment by narenandu** [comment]
Wondering if there was any update on this issue? We are seeing an issue in our infrastucture with same `debug_error_string` and exactly the same error. We use server written in Go and Python Client

**Comment by CodArs-van** [comment]
Reusing the channel kind of mitigates the issue for me, but still I think it's a bug.
