### ISSUE TITLE
grpc_socket_mutator is not usable.

### ISSUE THREAD

**Issue by fmagellan** [grpc/grpc#18989]
Hi,

"grpc_socket_mutator" is meant to be used by the application to set custom socket options, before starting gRPC server. I would expect the the header file "src/core/lib/iomgr/socket_mutator.h" to be made  available in "include/grpcpp/" directory, so that the applications can use socket_mutator as intended. Since, the header is not made available to the applications, grpc_socket_mutator feature cannot be used by the applications, as intended !

### What version of gRPC and what language are you using?
 v1.10.0
 
### What operating system (Linux, Windows,...) and version?
 GNU/Linux

### Anything else we should know about your project / environment?
I compiled grpc binary from cpp code base.
I copied grpc-related binaries & cpp-header files ( from "include" directory) to my project.
I linked grpc-binary to my project, and the compilation fails.
 
### Code snippet ###
I copied a sample code snippet. I am not able to get it compiled, because grcp_socket_mutator class definition is not available to the user, in "include/grpcpp" directory.
```
#include <grpc/grpc.h>
#include <grpcpp/grpcpp.h>

extern grpc_arg_pointer_vtable socket_mutator_arg_vtable;
using grpc::Service;
using grpc::Status;

class CustomServerBuilderOption: public ServerBuilderOption {
    public:
        CustomServerBuilderOption() {}
        ~CustomServerBuilderOption() {}

        // Alter the ChannelArguments used to create the gRPC server.
        // This will be called inside ServerBuilder::BuildAndStart().
        // We have to push any custom channel arguments into args.
        virtual void UpdateArguments(ChannelArguments* args);

        // Alter the ServerBuilderPlugin map that will be added into ServerBuilder.
        // We do not need this. However, this is a mandatory virtual
        // method, hence defining it as an empty method.
        virtual void UpdatePlugins(std::vector<std::unique_ptr<ServerBuilderPlugin>> *plugins) {}
};

class CustomSocketMutator: public grpc_socket_mutator {
    public:
        CustomSocketMutator();
        ~CustomSocketMutator() {}
        bool MutateFd(int fd);
};

bool custom_mutator_mutate_fd(int fd, grpc_socket_mutator* pMutator) {
    CustomSocketMutator* pCustomSM = (CustomSocketMutator *)pMutator;
    return pCustomSM->MutateFd(fd);
}

int custom_mutator_compare(grpc_socket_mutator* lhs, grpc_socket_mutator* rhs) {
    return GPR_ICMP(lhs, rhs);
}

void custom_mutator_destroy(grpc_socket_mutator* pMutator) {
    CustomSocketMutator* pCustomSM = (CustomSocketMutator *)pMutator;
    delete pCustomSM;
}

grpc_socket_mutator_vtable custom_mutator_vtable = {custom_mutator_mutate_fd, custom_mutator_compare, custom_mutator_destroy};

void CustomServerBuilderOption::UpdateArguments(ChannelArguments *pArg) {
    CustomSocketMutator *pSocketMutator = new CustomSocketMutator();
    pArg->SetSocketMutator(pSocketMutator);

    return;
}

CustomSocketMutator::CustomSocketMutator() {
    // Init the grpc_socket_mutator vtable.
    grpc_socket_mutator_init(this, &custom_mutator_vtable);
}

bool CustomSocketMutator::MutateFd(int fd) {
    if(0 != setsockopt(fd, SOL_SOCKET, /*SO_NSID*/ 42, &grpcVrfId, sizeof(grpcVrfId)))     {
        WaveNs::trace(TRACE_LEVEL_ERROR, "CustomSocketMutator::MutateFd:Socketopt(42) failed !");
        return 1;
    }

    return 0;
}

int main (void) {
    string server_address("0.0.0.0:52231");

    ServerBuilder builder;
    unique_ptr<Server> myServer;
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());

    // builder.RegisterService() ==> register custom-services.
    // builder.AddCompletionQueue();

    // Set(add) the ServerBuilderOption in ServerBuilder.
    unique_ptr<CustomServerBuilderOption> pVrfServerBuilderOption(new CustomServerBuilderOption());
    builder.SetOption(std::move(pVrfServerBuilderOption));
    // Finally assemble the server.
    myServer = builder.BuildAndStart();

   // That's all.

    return (0);
}
```
 
### What did you expect to see?
Compilation to go successful, and be able to use socket_mutator to change socket options, as I see fit.
 
### What did you see instead?
Compilation error.

**Comment by nicolasnoble** [comment]
You are incorrect in assuming this is intended for public consumption.

**Comment by weiyongji** [comment]
maybe you can refer to socket_utils_test.cc, otherwise it is needed to pack these interface into the "include" directory.

**Comment by fmagellan** [comment]
Hi @nicolasnoble,
Please check the below two test-files (examples) provided by you (grpc-team), that shows how an application can start a grpc-server with socket-mutator options. This is clearly meant for public consumption.
**test/cpp/server/server_builder_with_socket_mutator_test.cc**
**test/cpp/common/channel_arguments_test.cc**

Hi @weiyongji,
I checked the file socket_utils_test.cc. It also closely refers to grpc_socket_mutator, which needs to be made available for public consumption.

It would be great, if you can make this structure available in **include** directory.

**Comment by weiyongji** [comment]
ofcource I can try to do it, but I think these shall be defined in grpc.h, how do you think about this @nicolasnoble ?

**Comment by weiyongji** [comment]
hi, @fmagellan, I have written a demo on my fork-br:[https://github.com/weiyongji/grpc/tree/mutator](url),  maybe this can help for you compile errors.
because modify of the core API shall be careful designed, I need other more authoritative advice from other commiters before make a PR. @nicolasnoble
