### ISSUE TITLE
Patched GeventWorker + gunicorn causes calls to `subprocess` to segfault

### ISSUE THREAD

**Issue by jamwalla** [grpc/grpc#18980]
Originally filed as gevent/gevent#1420

* gevent version: 1.4.0
* grpcio version: 1.19.0
* gunicorn version 19.9.0
* Python version: 3.7
* Operating System: Ubuntu (appengine flex VM)
(from docker: `FROM ubuntu:latest` `RUN apt update -y && apt install -y python3.7-dev`)
 

### Description:

Patched GeventWorker + gunicorn causes calls to `subprocess` to segfault.

We run an appengine flex project with gunicorn using a patched gevent worker, so we can make asynchronous calls to the `requests` library. 
```python
from gunicorn.workers.ggevent import GeventWorker
from grpc.experimental import gevent
class GeventGrpcWorker(GeventWorker):
    def patch(self):
        super(GeventGrpcWorker, self).patch()
        gevent.init_gevent()
        self.log.info('patched grpc')
```
We found this issue while trying to use [tabula-py](https://github.com/chezou/tabula-py): all calls to `subprocess` cause a segfault like the following:
```
aef-default-v1--0--28-3573 kernel: [47918.185101] gunicorn[2328]: segfault at 0 ip 00007fbb87466b16 sp 00007ffd63a35630 error 4 in cygrpc.cpython-37m-x86_64-linux-gnu.so[7fbb87376000+3af000]
```

### What I've run:
I've tried unpatching subprocess `import importlib; importlib.reload(subprocess)` and excluding `patch_subprocess` in the original patch; neither prevents the segfault.

**Comment by speedplane** [comment]
I ran into almost an identical issue, also using `gevent` on gunicorn on App Engine Flexible.

Here's my setup/monkey patch code:

```
    # Only applies to monkey gunicorn gevent serving.
    if _gunicorn_worker_class() != 'gevent':
        return
    # Do the monkey patch.
    try:
        from gevent import monkey
    except Exception as e:
        pass
    else:
        monkey.patch_all()
        import grpc.experimental.gevent as grpc_gevent
        grpc_gevent.init_gevent()
        logging.info("gevent and gRPC succesfully monkey patched.")
```

We're using the `browsermob` library, and the code segfaults when it's trying to launch the associated server using `subprocess.Popen`:

```
self.command = ['/home/vmagent/app/binlibs/browsermob/bin/browsermob-proxy', '--port=9082']
...
self.process = subprocess.Popen(self.command,
                                        stdout=self.log_file,
                                        stderr=subprocess.STDOUT)
```

And here's the segfault that resulted:
```
May 15 00:00:07 aef-vm-20190514t175204-f32j kernel: [  628.398151] gunicorn[8532]: segfault at 0 ip 00007f5696102016 sp 00007fffee378770 error 4 in cygrpc.so[7f5696013000+3ac000]
```

Version info:
```
# Needed for gunicorn's worker model.
gevent==1.4.0
# Cloud datstore libraries that we use pretty often.
google-cloud-datastore==1.7.3
google-cloud-logging==1.10.0
google-cloud-storage==1.15.0
google-cloud-tasks==1.0.0
```

**Comment by gnossen** [comment]
@speedplane @jamwalla 
A couple of initial thoughts:
1. Do you have a minimal repro case I can use to debug this issue? Can you even reproduce the segfault outside of appengine?
2. Are you setting the environment variable [`GRPC_ENABLE_FORK_SUPPORT` to `true`](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)?

**Comment by speedplane** [comment]
1. There seems to be a nice clean example in the potentially duplicate issue #15620
2. No.

**Comment by jamwalla** [comment]
1. I don't have a minimal repro case but might be able work on one. This doesn't reproduce locally (I can build a docker image that runs gunicorn and subprocess calls are fine), only on appengine.
2. Setting the `GRPC_ENABLE_FORK_SUPPORT` flag doesn't solve this either - just to be sure, is this something I should pass through the gunicorn runtime with a line like `raw_env = ['GRPC_ENABLE_FORK_SUPPORT=true']` in the conf file or as a commandline arg (`-e`) passed to gunicorn?

**Comment by gnossen** [comment]
Encountered in https://github.com/grpc/grpc/pull/19481.

**Comment by gnossen** [comment]
I believe the issue has been resolved. If anyone sees it in the wild again, please chime in.

**Comment by c0rvax** [comment]
Hi

I started facing similar issue, although i am not using gevent. I use multiprocessing to run a lot of tasks in the background. Again the issue is only reproduced in Google Cloud (i use kuberentes for instance)

Here are some of the logs. Should i somehow update grpc on the server?

```
segfault at 5624cee97ea0 ip 00007fdd6bf2eec5 sp 00007fdd6b33b758 error 4 in cygrpc.cpython-37m-x86_64-linux-gnu.so[7fdd6be7d000+2
94000]
segfault at 5617d60e01a0 ip 00007f33118b3ec5 sp 00007f3310c9c758 error 4 in cygrpc.cpython-37m-x86_64-linux-gnu.so[7f3311802000+2
94000]
segfault at 20 ip 00007fb3506a8ee5 sp 00007fb34fab5758 error 4 in cygrpc.cpython-37m-x86_64-linux-gnu.so[7fb3505f7000+294000]
```

**Comment by gnossen** [comment]
@c0rvax  If `gevent` isn't involved, then it's definitely not the same issue. Could you please open a new issue and include full logs?
