### ISSUE TITLE
grpc client non-deterministically failing with `pthread_mutex_lock` assertion error

### ISSUE THREAD

**Issue by jlzhao27** [grpc/grpc#18994]
### What version of gRPC and what language are you using?
 1.15.0
 
### What operating system (Linux, Windows,...) and version?
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 2.7.12
 
### What did you do?

Started python script that spawns off several non-related subprocesses using `multiprocess.Process` then proceeds to construct the the grpcclient in the main process and makes calls to a remote server.

the calling code is pretty standard
```
 with grpc.insecure_channel(<host>) as c:
       stub = <sample_service>.Stub(c)
       c.CallServer()
```

One note is that the grpcclient is running with tensorflow code so not sure if that is causing issues.
 
### What did you expect to see?
 No errors and grpc client should function correctly.
 
### What did you see instead?
 
We see rare failures roughly 1/20 jobs where there is the following error:
```
RPC call failed:
{"created":"@1555085974.187246509","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2636,"referenced_errors":[{"created":"@1555085974.187239106","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1555085974.186709222","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1555085974.186656676","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.cc","file_line":194,"os_error":"Timeout occurred","referenced_errors":[

{"created":"@1555085974.186621825","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":114}
],"target_address":"ipv4:<ip>:80"}]}]}]}
E0412 16:19:44.197736281 33208 sync_posix.cc:47] assertion failed: pthread_mutex_lock(mu) == 0
```

 
### Anything else we should know about your project / environment?
This is running in a docker container with the nvidia cuda 10 runtime with kernel version ubuntu 16.04.

I also read through previous issues here on `pthread_mutex_lock` and found this: https://github.com/grpc/grpc/issues/15334 but according to the resolution, that should've been fixed in 1.15.0 which was the version we were running. Also, our failure is non-deterministic and somewhat rare.

**Comment by nicolasnoble** [comment]
Can you retry with version 1.20? Lots happened in the meantime...

**Comment by jlzhao27** [comment]
Yep we bumped to 1.20, will report back if we see this error again. For my understanding, is this due to a threading issue with multiple processes using the grpc client?

**Comment by nicolasnoble** [comment]
No. gRPC is inherently multithreaded. Even if you use it from a single thread, it'll create threads internally to process work.
