### ISSUE TITLE
Connectivity callback prints exception trace in background thread

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#18995]
gRPC Python 1.19.0 (most likely in 1.20.0 too) on Linux (not platform specific)
 
We create a gRPC channel and immediately call `subscribe` on it passing a connectivity callback. At some point, we call `close` on the channel without having called `unsubscribe` beforehand. We see the following exception:

```
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
    self.run()
  File "threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../com_github_grpc_grpc/src/python/grpcio/grpcio-cpython-27/grpc/_channel.py", line 915, in _poll_connectivity
    time.time() + 0.2)
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 487, in cygrpc.Channel.watch_connectivity_state
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 349, in cygrpc._watch_connectivity_state
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 357, in cygrpc._watch_connectivity_state
ValueError: Cannot invoke RPC: Channel closed!```
```

Seems like the connectivity tag is seen on the completion queue, but the channel is closed when gRPC Python layer sees that tag, and thinks the user has called a method in an invalid closed state, as opposed to the underlying system.  The `Channel.close()` should make it so that callbacks should not be called once `close()` is received and no exception is thrown either.

cc @lidizheng @gnossen

**Comment by mehrdada** [comment]
Please note that the stack trace above is printed from a background thread and no exception is thrown in the main thread.

I investigated this a bit further trying to minimize the test case and I am less confident about the circumstances that leads to this are as I described. There's another possibility I am worried about, which is something is calling `subscribe`  in the background. However, the following is my understanding reading [gRPC source code for `_subscribe`](https://github.com/grpc/grpc/blob/v1.19.x/src/python/grpcio/grpc/_channel.py#L941): it will not raise an exception even if channel is closed (which may or may not be the intended behavior), but it might cause an exception trace to be printed in the background thread. I suspect we either want an exception to be raised in the caller thread immediately and not start polling connectivity, or make it a no-op (no exception) but do not start watching either, and in either case we should not see that exception logged to console.

**Comment by srini100** [comment]
This issue https://github.com/grpc/grpc/issues/16290 may have some relevant info.

**Comment by mehrdada** [comment]
I made a minimal test case that consistently reproduces the problem:

```
from __future__ import print_function
import logging

import grpc
import time

import helloworld_pb2
import helloworld_pb2_grpc

def watch(state):
    print(state)

def run():
    # NOTE(gRPC Python Team): .close() is possible on a channel and should be
    # used in circumstances in which the with statement does not fit the needs
    # of the code.
    with grpc.insecure_channel('localhost:50051') as channel:
        channel.subscribe(watch, try_to_connect=True)
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
        print("Greeter client received: " + response.message)
        #channel.unsubscribe(watch)  # works fine when uncommented

if __name__ == '__main__':
    logging.basicConfig()
    run()
    time.sleep(10)
```

**Comment by gnossen** [comment]
Reopening as a tracking issue for adding a regression test.

**Comment by gnossen** [comment]
@lidizheng and I just had a conversation about this general class of problem. When I pull in a library and see that it logs errors (without crashing) under normal operation, it leaves a bad taste in my mouth and I'm likely to have a poor opinion of it. Exceptions on threads besides the main thread are just one example of causes of a such a situation.

Our test suite should verify this behavior for all use cases currently under test and the effort to add a new  test case should be minimally. Ideally, we would be able to just check in @mehrdada 's repro case above and call it a day. Perhaps we should write a new test runner that performs this check and add a new kokoro job for it.
