### ISSUE TITLE
Certificate verification fail when Server uses TLSCert + IntermediateCert and client uses RootCert.

### ISSUE THREAD

**Issue by YanlongLi** [grpc/grpc#18998]
### What version of gRPC and what language are you using?
C#, gRPC 1.18.0 
 
### What operating system (Linux, Windows,...) and version?
 Windows [Version 10.0.17763.523]
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET Framework 4.6.2
 
### What did you do?
I have three cert RootCA -> IntermediateCert -> TLS Cert.

The server is initialized with the chain without RootCA and client uses the RootCA to auth the server.

### What did you expect to see?
Client can make connection to server with the Root CA.
 
### What did you see instead?
I got 
```
 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1238: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED. 
```

If I change to use the intermediate cert in client, it works.

**Comment by nicolasnoble** [comment]
Please share your code.

**Comment by YanlongLi** [comment]
Server:
```
var cred = new SslServerCredentials(
    new KeyCertificatePair[] { new KeyCertificatePair(chain, privateKeyPEM) }, // Chain here is in PEM format that includes the TLS cert and intermediate cert.
    rootCertificates: null,
    SslClientCertificateRequestType.DontRequest);
var server = new Server
{
    Ports =
    {
     new ServerPort(host, port, GrpcSslCredentials.GetServerCredential(_sslConfiguration))
    }
};
server.Services.Add(service);
server.Start();
```

Client:
```
var cred = new SslCredentials(serverRootPEM); // serverRootPEM here is the root cert of server TLS cert, it works if I use the intermediate cert here.
var channel = new Channel("host", port, cred);
var client = new ExampleClient(channel);
```
I use WireShark to view the TLS header, the server cert chain was sent to client.

**Comment by YanlongLi** [comment]
@nicolasnoble @jiangtaoli2016

**Comment by onisac-K** [comment]
can we reopen this issue? I met the same problem..
