### ISSUE TITLE
Podspecs cannot yet depend on Protobuf ~> 3.0

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1899]
In the Objective C documentation, the example Podspec includes a dependency line that says `ms.dependency 'Protobuf', '~> 3.0'`. This does not work because the current version of the Protobuf pod is `3.0.0-alpha-3`, which comes *before* `3.0` (according to http://semver.org/).

**Comment by jcanizales** [comment]
Yeah I submitted Protobuf.podspec with that version so that people will be updated when 3.0 is final.

I then spent the full day battling Cocoapods to successfully lint gRPC.podspec. I'll submit it to the repo now, send you the changes for review, and then fix the examples, tests, etc.
