### ISSUE TITLE
Document server initialization order invariant with regard to interceptors

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#19000]
See internal bug for full logs and description. The core issue is that third_party/grpc/include/grpcpp/server_impl.h has a dependency on its private fields being initialized in a particular order. Moving 
'std::unique_ptr<grpc::HealthCheckServiceInterface> health_check_service_;
bool health_check_service_disabled_;'
to above the "private:" section causes many test failures.

**Comment by vjpai** [comment]
But is it a problem? This is allowed by the C++ specification, and some ordering has to exist in any case.

**Comment by hcaseyal** [comment]
It's an undocumented dependency as far as I can tell, so that would make it a bug. It also forces me to do things a little messily in https://github.com/grpc/grpc/pull/19001

If we are indeed depending on this initialization ordering, then we should clearly state that.

**Comment by vjpai** [comment]
#19001 is bad form anyway; protected data members are not allowed in the standard.

**Comment by hcaseyal** [comment]
@vjpai Perhaps we should discuss this offline and see what the better alternative is.

**Comment by hcaseyal** [comment]
To recap our offline discussion: depending on fields being initialized in a certain order is not a bug in and of itself - the issue I was raising here was that there wasn't a clear reason for the dependency here, so it smelled like a bug.

@vjpai brought up that there could be a reason here, and that's with interceptor destruction. However, if this is the case, I would contend that we should document the invariant that's being enforced here.

**Comment by hcaseyal** [comment]
In particular, it seems like the issue is with interceptors destructing before the health checking service
