### ISSUE TITLE
C++ callback API: Server OnDone should signal Finish outcome

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#19019]
### What version of gRPC and what language are you using?

master, C++
 
### What operating system (Linux, Windows,...) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A
 
### What did you do?

Want to determine if a server-side Finish operation actually completed or whether there was a stream break or something
 
### What did you expect to see?
 
The bool value about the Finish result being exposed through the API, such as in OnDone . This result is available in the sync and async APIs.
 
### What did you see instead?
 
The bool value about the Finish result is swallowed internally and OnDone has no arguments

**Comment by vjpai** [comment]
@a11r raises a concern about this: namely, if the server finds out that it wasn't able to send status, there's really not much that it can do about it at this point since the server sending status is a signal that the server is done processing the RPC. At most, it could only track a statistic or log in the OnDone call. We can take a look and see if there's any uses of the Finish(bool) result in the existing sync or async APIs or see if there's a practical use case to justify that this an important issue.

**Comment by karthikravis** [comment]
Hey @vjpai , @sheenaqotj : please update this issue when you get a chance. Thanks!

**Comment by sheenaqotj** [comment]
Karthik's comment appeared right when I was looking at this page. :) Re-reading this a few times, this is about whether the server wants to know when its Finish() might have failed. Will take a look at the other APIs.

**Comment by vjpai** [comment]
Sync api has no such concept since the Status is reported as the return value from the method handler.
Stubby has no such concept since status is set differently and the "done callback" doesn't give any way of knowing that it's over.
The gRPC async API has this possibility, but it's hard to tell if anyone ever used this feature or what they would have done with it.
So maybe this is worth closing.

**Comment by sheenaqotj** [comment]
Thanks for the discussion. Closing.
