### ISSUE TITLE
GRPC does not set AssemblyVersion on dotnet wrapper

### ISSUE THREAD

**Issue by Groostav** [grpc/grpc#19024]
### What version of gRPC and what language are you using?

~~1.20.1.0~~ 1.0.0.0 _as per `AssemblyVersion`_, en-us
 
### What operating system (Linux, Windows,...) and version?
 
Windows 10 build 1809
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
.net + MSBuild with VS 2017 + nuget published grpc 1.20.1 artifacts
 
### What did you do?

1. Create a new project
2. downloaded most recent GRPC package from Nuget. Nuget's Displayed version is 1.21.0

**expected**: `AssemblyVersion` (on DLL's manifest) is 1.21.0
**actual**: `AssemblyVersion` is 1.0.0.0

_continued with more passive-aggression than is really warranted, but hopefully understandable considering my trip through DLL hell_

3. set your project up as an plugin to a huge old software's plugin framework (HugeOldSoft)
4. build and test your plugin outside of the plugin framework
5. deploy your application and test it with a live version of HugeOldSoft.

**expected**: HugeOldSoft smartly uses `AppDomain`s to ensure your library loads its appropriate dependencies
**actual**: HugeOldSoft loads your library in its own `AppDomain`, and since HugeOldSoft has its own copy of GRPC (AssemblyVersion 1.0.0.0, AssemblyFileVersion 1.0.0.0), and my app depends on GRPC (AssemblyVersion 1.0.0.0, AssemblyFileVersion 1.21.1.0), **I get HugeOldSoft's copy from the GAC**, and a `Type Not found: Grpc...Interceptor` linkage error. 
 
### What did you expect to see?
 
the .net wrapper for GRPC should have AssemblyVersion attributes that match the AssemblyFileVersion attribute.
 
### What did you see instead?
 
The GRPC wrapper is hard-coded to use an AssemblyVersion of 1.0.0.0, for all versions of GRPC. 

![image](https://user-images.githubusercontent.com/1680611/57723825-55244100-763e-11e9-93e4-b254aa315f21.png)

### Anything else we should know about your project / environment?

The .net framework provides a number of tools for runtime dll version management. Speaking very naively, the "best" solution is probably simply to expose the most information (IE a high fedility version string, like `1.20.1.1234`) possible to that system, and leave it to fusion and binding-redirects provided by users to correctly find GRPC.

**Comment by Groostav** [comment]
Alright so, I've basically decided I need to build this library from source rather than use the Nuget published artifact, and that seems do-able because as-of 7741e806a213cba63c96234f16d712a8aa101a49, grpc's build system seems quite nice. 

What isn't nice is that BUILDING.md doesnt include instructions on how to build the C# wrapper in addition to the native code. Can such an update be made? In the mean time I simply opened VS and said "build solution", which gave me a host of targeting errors. it looks to me like I need to run MSbuild with some configuration --or I really do need all of .net core + .net standard + specific .net framework(s).

**Comment by jtattermusch** [comment]
C# building instructions: https://github.com/grpc/grpc/tree/master/src/csharp#build-from-source

the assembly version is set as intended, see https://github.com/grpc/grpc/issues/6201 and the article linked from there for details.
