### ISSUE TITLE
SIGSEGV in google.golang.org/grpc.(*ClientConn).healthCheckConfig

### ISSUE THREAD

**Issue by t57root** [grpc/grpc#19061]
### What version of gRPC and what language are you using?
 
commit 4b60e3b6a1900853971945c616869c0fc211ac75
language is golang 
 
### What operating system (Linux, Windows,...) and version?
 
CentOS Linux release 7.3.1611 (Core)
3.18.6-2.el7.centos.x86_64 #1 SMP Mon Oct 24 13:01:33 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
go version go1.12.4 linux/amd64
 
### What did you do?

just standard usage of grpc over tls, all things including grpc.DialContext and RPC call work well, but seems something happened in the health checking part. will try to streamline the code to reproduce the problem if it's necessary
 
### What did you expect to see?
 
Run without SIGFAULT
 
### What did you see instead?
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x268 pc=0x7e7895]

goroutine 16 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
google.golang.org/grpc.(*ClientConn).healthCheckConfig(0x0, 0x0)
        /build/src/google.golang.org/grpc/clientconn.go:828 +0x35
google.golang.org/grpc.(*addrConn).resetTransport(0xc00031a000)
        /build/src/google.golang.org/grpc/clientconn.go:1080 +0x513
created by google.golang.org/grpc.(*addrConn).connect
        /build/src/google.golang.org/grpc/clientconn.go:765 +0xb6

**Comment by srini100** [comment]
Please file this in [grpc-go](https://github.com/grpc/grpc-go/issues) repo. Closing this one.
