### ISSUE TITLE
PHP: Class 'Routeguide\RouteGuideClient' not found

### ISSUE THREAD

**Issue by kaychem** [grpc/grpc#19064]
the php examples:
PHP Fatal error:  Uncaught Error: Class 'Routeguide\RouteGuideClient' not found in /Users/kay/www/grpc/examples/php/route_guide/route_guide_client.php:26
Stack trace:

**Comment by stanley-cheung** [comment]
Have you run the `protoc` command to generate the client stub class `RouteGuideClient`?
