### ISSUE TITLE
libgrpc++.a is not containing grpc_core::ExecCtx::exec_ctx_

### ISSUE THREAD

**Issue by tunz** [grpc/grpc#19075]
### What version of gRPC and what language are you using?
grpc 1.20.x cpp
 
### What operating system (Linux, Windows,...) and version?
Linux, CentOS 7 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ 7.3.1
 
### What did you do?
I was trying to link `libgrpc++.a` into my shared library with `--whole-archive` option.
 
### What did you expect to see?
Loading successfully.
 
### What did you see instead?
This error appeared when loading the shared library.
```
undefined symbol: _ZN9grpc_core7ExecCtx9exec_ctx_E
``` 

This is what I debugged about this briefly.

`libgrpc++.a` references `grpc_core::ExecCtx::exec_ctx_`, but does not have a definition in itself.
```
$ objdump -t libgrpc++.a | grep _ZN9grpc_core7ExecCtx9exec_ctx_E
0000000000000000         *UND*  0000000000000000 _ZN9grpc_core7ExecCtx9exec_ctx_E
0000000000000000         *UND*  0000000000000000 _ZN9grpc_core7ExecCtx9exec_ctx_E
0000000000000000         *UND*  0000000000000000 _ZN9grpc_core7ExecCtx9exec_ctx_E
0000000000000000         *UND*  0000000000000000 _ZN9grpc_core7ExecCtx9exec_ctx_E
```

while `libgrpc.a` have it.
```
$ objdump -t libgrpc.a | grep _ZN9grpc_core7ExecCtx9exec_ctx_E
...
0000000000000008 g       .tbss  0000000000000008 _ZN9grpc_core7ExecCtx9exec_ctx_E
...
```

looks like there are some cpp files referencing `grpc_core::ExecCtx`
```
$ ack exec_ctx ./src/cpp/
src/cpp/common/alarm.cc
27:#include "src/core/lib/iomgr/exec_ctx.h"
50:    grpc_core::ApplicationCallbackExecCtx callback_exec_ctx;
51:    grpc_core::ExecCtx exec_ctx;
71:                      this, grpc_schedule_on_exec_ctx);
76:    grpc_core::ApplicationCallbackExecCtx callback_exec_ctx;
77:    grpc_core::ExecCtx exec_ctx;
87:                      this, grpc_schedule_on_exec_ctx);
92:    grpc_core::ApplicationCallbackExecCtx callback_exec_ctx;
93:    grpc_core::ExecCtx exec_ctx;

src/cpp/common/channel_arguments.cc
27:#include "src/core/lib/iomgr/exec_ctx.h"
69:  grpc_core::ExecCtx exec_ctx;
97:  grpc_core::ExecCtx exec_ctx;
```

But, `LIBGRPC++_SRC` in Makefile is not including `src/core/lib/iomgr/exec_ctx.cc`.

My temporary workaround for this issue is to remove objects overlapping with `libgrpc.a` from `libgrpc++.a` when building, and link `libgrpc.a` and `libgrpc++.a` together.

**Comment by tunz** [comment]
another workaround is to give the `--whole-archive` flag only to `libgrpc++.a`, and disable the flag for `libgrpc.a`.
```
g++ ... -Wl,--whole-archive libgrpc++.a -Wl,--no-whole-archive libgrpc.a
```

If we always have to link libgrpc.a and libgrpc++.a together, isn't it better to remove duplicated objects from libgrpc++.a in makefile?

**Comment by weiyongji** [comment]
+1, also have question on this, I see some cpp are compiled into other libs like libgrpc++_cronet.a, how was the dependence between these libs?

**Comment by veblush** [comment]
Sorry for being late to answer. To use gRPC C++, both `libgrpc.a` and `libgrpc++.a` need to be linked against. Please reopen this if it doesn't work as expected.
