### ISSUE TITLE
C# runtime exception in Unity Android build.

### ISSUE THREAD

**Issue by Zulug** [grpc/grpc#19072]
### What version of gRPC and what language are you using?
 1.20.1 / csharp
 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Unity / Android / .Net 4.x / Mono
 
### What did you do?
Trying to call any native method of libgrpc_csharp_ext.so on Android device.
 
### What did you expect to see?
I expect to see native method invocation. 
 
### What did you see instead?
DllNotFoundException

05-18 14:56:39.875: E/Unity(15509): Unable to find grpc_csharp_ext
05-18 14:56:39.967: E/Unity(15509): DllNotFoundException: grpc_csharp_ext
05-18 14:56:39.967: E/Unity(15509):   at (wrapper managed-to-native) Grpc.Core.Internal.NativeMethods+DllImportsFromSharedLib.grpcsharp_redirect_log(Grpc.Core.Internal.GprLogDelegate)
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.Internal.NativeLogRedirector.Redirect (Grpc.Core.Internal.NativeMethods native) [0x00028] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.Internal.NativeExtension..ctor () [0x00011] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.Internal.NativeExtension.Get () [0x00022] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.Internal.NativeMethods.Get () [0x00000] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.GrpcEnvironment.GrpcNativeInit () [0x00016] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.GrpcEnvironment..ctor () [0x0001e] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.GrpcEnvironment.AddRef () [0x00028] in <421e6b12b8864c61a4c26dc14ec084f1>:0 
05-18 14:56:39.967: E/Unity(15509):   at Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials, System.Collections.G

### Anything else we should know about your project / environment?
It was tested also on grpc_unity_package.1.22.0-dev / Unity 2018.3.11f1

I hope that adding Android platform in the list of LoadNativeMethodsUnity (in Grpc.Core.Internal.NativeExtension::LoadNativeMthodsUnity) will solve the problem. As android uses static libraries similar to iOS. Something like:

        private static NativeMethods LoadNativeMethodsUnity()
        {
            switch (PlatformApis.GetUnityRuntimePlatform())
            {
                case "IPhonePlayer":
                case "Android":
                    return new NativeMethods(new NativeMethods.DllImportsFromStaticLib());
                default:
                    // most other platforms load unity plugins as a shared library
                    return new NativeMethods(new NativeMethods.DllImportsFromSharedLib());
            }
        }

**Comment by Zulug** [comment]
It was tested also on grpc_unity_package.1.22.0-dev / Unity 2018.3.11f1

**Comment by jtattermusch** [comment]
As far as I can tell, the `LoadNativeMethodsUnity` is correct. Android uses a shared library.

https://github.com/grpc/grpc/blob/2780136fcf9bd268aaddea74b115fbc2faa97c61/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L138

**Comment by Zulug** [comment]
Figured out the problem, that was my mistake. I used custom Google.Cloud.Firestore package in Unity along with grpc_unity_package. And lost armv7 version of libgrpc_csharp_ext.so somewhere in between. Sorry for false alarm.
