### ISSUE TITLE
Remove Python 2 Usages from Repo

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#19083]
This is a tracking issue for all current usages of Python 2 in this repo.

The instances listed here have not been triaged farther than to verify that they are in fact running with Python 2. The transition process may actually be as simple as changing out their shebang.

Discovered using `find . -type f | xargs egrep -ni 'py.*2' | grep -iv copyright`

### Known Build/Test-Time Usages:
 - [ ] `tools/distrib/python_wrapper.sh`
 - [ ] `test/core/http/test_server.py`
 - [ ] `tools/distrib/run_clang_tidy.py`
 - [ ] `tools/distrib/check_include_guards.py`
 - [ ] `tools/distrib/python/submit.py`
 - [ ] `tools/distrib/python/docgen.py`
 - [ ] `tools/distrib/c-ish/check_documentation.py`
 - [ ] `tools/run_tests/python_utils/port_server.py`
 - [ ] `tools/run_tests/performance/build_performance.sh`
 - [ ] `tools/run_tests/performance/run_worker_python.sh`
 - [ ] `tools/run_tests/start_port_server.py`
 - [ ] `tools/run_tests/lb_interop_tests/gen_build_yaml.py`
 - [ ] `tools/debug/core/chttp2_ref_leak.py`
 - [ ] `tools/profiling/ios_bin/binary_size.py`
 - [ ] `tools/profiling/qps/qps_diff.py`
 - [ ] `tools/profiling/latency_profile/profile_analyzer.py`
 - [ ] `tools/profiling/bloat/bloat_diff.py`
 - [ ] `tools/profiling/microbenchmarks/bm_diff/bm_diff.py`
 - [ ] `tools/profiling/microbenchmarks/bm_diff/bm_build.py`
 - [ ] `tools/profiling/microbenchmarks/bm_diff/bm_constants.py`
 - [ ] `tools/profiling/microbenchmarks/bm_diff/bm_speedup.py`
 - [ ] `tools/profiling/microbenchmarks/bm_diff/bm_main.py`
 - [ ] `tools/profiling/microbenchmarks/bm_diff/bm_run.py`
 - [ ] `tools/profiling/microbenchmarks/bm2bq.py`
 - [ ] `tools/codegen/core/gen_stats_data.py`
 - [ ] `tools/codegen/core/gen_static_metadata.py`
 - [ ] `tools/codegen/core/gen_server_registered_method_bad_client_test_body.py`
 - [ ] `tools/codegen/core/gen_header_frame.py`
 - [ ] `tools/codegen/core/gen_settings_ids.py`
 - [ ] `tools/internal_ci/linux/run_performance_profile_daily.sh`
 - [ ] `tools/internal_ci/helper_scripts/prepare_build_linux_perf_rc`
 - [ ] `tools/gcp/utils/big_query_utils.py`
 - [ ] `tools/dockerfile/test/cxx_alpine_x64/Dockerfile`
 - [ ] `tools/dockerfile/test/cxx_jessie_x86/Dockerfile`
 - [ ] `tools/dockerfile/test/csharp_stretch_x64/Dockerfile`
 - [ ] `tools/dockerfile/test/php_jessie_x64/Dockerfile`
 - [ ] `tools/run_tests/artifacts/artifact_targets.py`
 - [ ] `tools/interop_matrix/client_matrix.py`
 - [ ] `tools/buildgen/mako_renderer.py`
 - [ ] `tools/buildgen/plugins/list_api.py`
 - [ ] `tools/buildgen/generate_projects.py`

**Comment by lidizheng** [comment]
cc @lidizheng

**Comment by lidizheng** [comment]
Link a contribution to this issue: https://github.com/grpc/grpc/pull/19354

**Comment by jtattermusch** [comment]
While doing this, it would be good to review the Dockerfiles at https://github.com/grpc/grpc/tree/master/tools/dockerfile and make sure we don't install python2 unnecessarily (right now all the testing scripts are being run with python2 so virtually all docker images would install python2 for that reason).
