### ISSUE TITLE
Method not found: 'Void Grpc.Core.CallOptions..ctor(Grpc.Core.Metadata, System.Nullable1<System.DateTime>, System.Threading.CancellationToken, Grpc.Core.WriteOptions, Grpc.Core.ContextPropagationToken, Grpc.Core.CallCredentials)

### ISSUE THREAD

**Issue by jess-sheneberger** [grpc/grpc#19085]
### What version of gRPC and what language are you using?
 gRPC 1.20.1, CSharp

### What operating system (Linux, Windows,...) and version?
 MacOS 10.14.4 (18E226) 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

```
$ dotnet --version
2.2.106

$ func version 
2.7.1149

$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
...
```
 
### What did you do?

I wrote an Azure Function to use gRPC 1.20.1 and connect to an external service.  When that didn't work, I rolled back to gRPC 1.18.0 and that did work. I made an example repro with instructions here: (https://github.com/jess-sheneberger/grpc-method-not-found-repro)
 
### What did you expect to see?
 I expected gRPC 1.20.1 and 1.18.0 to behave identically.
 
### What did you see instead?
 Azure Function with gRPC 1.20.1 throws an exception:
```
System.Private.CoreLib: Exception while executing function: TestHttpTriggerFunc. client-azure-function: Method not found: 'Void Grpc.Core.CallOptions..ctor(Grpc.Core.Metadata, System.Nullable1<System.DateTime>, System.Threading.CancellationToken, Grpc.Core.WriteOptions, Grpc.Core.ContextPropagationToken, Grpc.Core.CallCredentials)'.
```

### Anything else we should know about your project / environment?

Interestingly, a similar client (https://github.com/jess-sheneberger/grpc-method-not-found-repro/tree/master/client-console) written to run as a console app does not exhibit the same behavior, so it seems to be the combination of something that changed from 1.18.0 to 1.20.1 and the Azure Function runtime.

**Comment by jess-sheneberger** [comment]
This looks a lot like #18889 and may be a dupe, but my environment seemed sufficiently different to create a new issue. I found that issue first while googling my problem. Noticed there was a request for a repro, so I put one together here: (https://github.com/jess-sheneberger/grpc-method-not-found-repro)

**Comment by luca233** [comment]
i have the same proble, i try to init server from function az and response error Method not found: 'Grpc.Core.ServerServiceDefinition HotelsService.Hotels.BindService(HotelsBase)'.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/18889#issuecomment-495657430 mentioned that upgrading visual studio has helped. What VS version are you using and can you try to upgrade?

**Comment by jess-sheneberger** [comment]
I actually don't have VS installed, just the .NET Core SDK, which is fairly recent at 2.2.106 (2.2.107 is most recent here: https://dotnet.microsoft.com/download)...I think msbuild gets installed as part of that bundle, so I'm not certain how to get to 16.1.* instead of 15.9.20 that msbuild shows

**Comment by jtattermusch** [comment]
Is this still a problem?

**Comment by jtattermusch** [comment]
Is the latest release still impacted?

**Comment by jess-sheneberger** [comment]
Sorry, I'm not working on the Azure Function that was using GRPC anymore and I don't have the environment I was using.
