### ISSUE TITLE
census grpc plugin doesn't set current_context in opencensus

### ISSUE THREAD

**Issue by jinmel** [grpc/grpc#19092]
Grpc plugin does not set opencensus context

in //opencensus/trace/trace_util.h and //opencensus/trace/context.h, we get the current active span within thread local storage. 

I am not sure if I should file this issue here or opencensus/opencensus-cpp. I am filing here first because the grpc plugin is implemented in this repository.

**Comment by AspirinSJL** [comment]
I'm not sure what issue you're facing with from the description. Maybe @g-easy has more context.

**Comment by g-easy** [comment]
I agree with @jinmel that the grpc plugin (which predates opencensus context) should install the span it creates into the context so that user code (e.g. RPC handler) can use context.

**Comment by yashykt** [comment]
Since OpenCensus is now deprecated, any new effort is going to go towards OpenTelemetry
