### ISSUE TITLE
The inconsistencies of status code mapping from two documents

### ISSUE THREAD

**Issue by legendtang** [grpc/grpc#19094]
### What version of gRPC and what language are you using?
 
 All
### What operating system (Linux, Windows,...) and version?
 
 All
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 All
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 There are two documents define the mapping behavior of status codes between HTTP and gRPC.
https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md
But it seems there are many inconsistencies here. I found in the implementation that gRPC favors the former. What should I use?
### What did you expect to see?
 the harmony
 
And apparently, mapping here https://github.com/grpc/grpc/blob/master/src/core/lib/transport/status_conversion.cc does not follow this document https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md Any suggestions?
### What did you see instead?
many inconsistent mapping
 
### Anything else we should know about your project / environment?
Nope

**Comment by hcaseyal** [comment]
@ejona86 Have the inconsistencies been resolved with your latest PR?

**Comment by dapengzhang0** [comment]
The doc is fixed. But the C core implementation https://github.com/grpc/grpc/blob/v1.23.0/src/core/lib/transport/status_conversion.cc#L82 is still wrong, there shouldn't be such conversion.

**Comment by ejona86** [comment]
Yeah, the doc inconsistencies are fixed. But I've not touched status_conversion.cc

**Comment by yashykt** [comment]
This is still an issue
