### ISSUE TITLE
[Suggestion dotnet] publish .snupkg to nuget.org as well 

### ISSUE THREAD

**Issue by hanabi1224** [grpc/grpc#19103]
https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements

**Comment by jtattermusch** [comment]
We are already publishing the pdb symbols as part of the the nuget packages themselves. Does the source stepping not work for you in visual studio?

**Comment by hanabi1224** [comment]
@jtattermusch That works, however, there might be some small drawbacks of .nupkg embedded dlls which are documented [here](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements)
>If a .pdb is included in a normal .nupkg, NuGet and NuGet.org will not do any special validation or indexing of the .pdbs. Debugging of the .nupkg will work in a limited way as the symbols will be cached next to the .dll, but it will not be indexed and downloaded from a symbol server. The only way to ensure indexing on the symbol server is to include the .snupkg. If the symbols are not indexed, certain scenarios will not work, such as crash dump debugging and attaching to an application.
