### ISSUE TITLE
python: channel.close() cost too long time.

### ISSUE THREAD

**Issue by alpaca2333** [grpc/grpc#19100]
### What version of gRPC and what language are you using?
ver 1.12 
python 
 
### What operating system (Linux, Windows,...) and version?
 centos 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
py 2.7.15
 
### What did you do?
I was doing sth wrong, as i created a channel each time i invoke a grpc call.
```c++
with grpc.insecure_channel(adapter_service_url) as channel:
    grpc.channel_ready_future(channel).result(timeout=3.0)
    stub = zone_interface_pb2_grpc.ZoneServiceStub(channel)
    metadata = [("apm4s-span-id", update_award_status_span)]
    update_status = stub.UpdateAwardStatus(award_req, metadata=metadata)
```
despite of my wrong practice, i found the channel being closed cost a long time(200ms). With higher concurrency, it could be even longer(up to ten thousands ms). Is this a bug or design?
 
### What did you expect to see?
 the channel being closed immediately.
 
### What did you see instead?
 the channel being closed cost a long time(200ms)

 
Should the channel and the stub be reused during the lifetime of a server or either of them be created each time a call is invoked?

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
