### ISSUE TITLE
Unable to install Python package grpcio

### ISSUE THREAD

**Issue by saltysealion** [grpc/grpc#19102]
### What version of gRPC and what language are you using?
gRPC 1.21.0
Python 3.6.4
 
### What operating system (Linux, Windows,...) and version?
OSX 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 4.6.4
pip 19.1.1
 
### What did you do?
I ran 
$pip install grpcio==1.21.0
 
### What did you expect to see?
 grpcio to be installed
 
### What did you see instead?
 Collecting grpcio==1.21.0
  ERROR: Could not find a version that satisfies the requirement grpcio==1.21.0 (from versions: 0.4.0a0, 0.4.0a1, 0.4.0a2, 0.4.0a3, 0.4.0a4, 0.4.0a5, 0.4.0a6, 0.4.0a7, 0.4.0a8, 0.4.0a13, 0.4.0a14, 0.5.0a0, 0.5.0a1, 0.5.0a2, 0.9.0a0, 0.9.0a1, 0.10.0a0, 0.11.0b0, 0.11.0b1, 0.12.0b0, 0.13.0, 0.13.1rc1, 0.13.1, 0.14.0rc1, 0.14.0, 0.15.0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2rc0, 1.0.2, 1.0.3, 1.0.4, 1.1.0rc1, 1.1.0, 1.1.3, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0, 1.3.3, 1.3.5, 1.4.0rc1, 1.4.0, 1.6.0rc1, 1.6.0, 1.6.3, 1.7.0rc1, 1.7.0, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.6, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1rc1, 1.10.1rc2, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.12.0rc1, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0rc3, 1.13.0, 1.14.0rc1, 1.14.0rc2, 1.14.0, 1.14.1, 1.14.2rc1, 1.14.2, 1.15.0rc1, 1.15.0, 1.16.0rc1, 1.16.0, 1.16.1rc1, 1.16.1, 1.17.0rc1, 1.17.0, 1.17.1rc1, 1.17.1, 1.18.0rc1, 1.18.0, 1.19.0rc1, 1.19.0, 1.20.0rc1, 1.20.0rc2, 1.20.0rc3, 1.20.0, 1.20.1, 1.21.0rc1)
ERROR: No matching distribution found for grpcio==1.21.0

**Comment by jakyns** [comment]
I just found this too!

**Comment by stabacco** [comment]
Yes, last release doesn't seem to have all the files.

**Comment by Tenzer** [comment]
Compare the files available for the 1.20.1 release: https://pypi.org/project/grpcio/1.20.1/#files
with the files for the 1.21.0 release: https://pypi.org/project/grpcio/1.21.0/#files.

For some reason there's only wheels uploaded for some Python 2.7 distributions. There aren't any Python 3.x or source distributions available.

**Comment by gnossen** [comment]
We [ran into an issue](https://github.com/pypa/wheel/issues/189) that prevented us from uploading all of our artifacts to PyPI. [We're working on a fix for that.](https://github.com/grpc/grpc/pull/19105) In the meantime, we've deleted the `1.21.0` release on PyPI so we don't cause any issues downstream. In the next couple of days, we'll be releasing a `1.21.1` patch.

**Comment by gnossen** [comment]
[grpcio `1.21.1` has been uploaded](https://pypi.org/project/grpcio/1.21.1/). Thanks everyone for reaching out.
