### ISSUE TITLE
Cannot rebuild Java interop base image

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#19113]
The Java interop images use Oracle 8 JDK (and are named as such: grpc_interop_java_oracle8). However, now all Oracle JDKs are unavailable for automatic download. So the PPA we were using to [grab oracle8 is discontinued](https://launchpad.net/~webupd8team/+archive/ubuntu/java).

So it seems clear we need to swap to OpenJDK, but then we should really change the interop name from grpc_interop_java_oracle8. I'm not familiar enough with the build scripts to make such a change. There is a grpc_interop_java Dockerfile, but it is completely unused to my knowledge.

@jtattermusch, ideas?

**Comment by ejona86** [comment]
For the v1.21.0 release, I did the following hack:
```
$ docker pull grpctesting/grpc_interop_java_oracle8_526e137c4cddc42089201442034d43543d7ddab3
$ docker tag grpctesting/grpc_interop_java_oracle8_526e137c4cddc42089201442034d43543d7ddab3 grpc_interop_java_oracle8_526e137c4cddc42089201442034d43543d7ddab3
```

```patch
diff --git a/tools/run_tests/dockerize/build_interop_image.sh b/tools/run_tests/dockerize/build_interop_image.sh
index fe37defd14..966347715d 100755
--- a/tools/run_tests/dockerize/build_interop_image.sh
+++ b/tools/run_tests/dockerize/build_interop_image.sh
@@ -95,7 +95,8 @@ then
   time docker pull "$BASE_IMAGE"
 else
   # Make sure docker image has been built. Should be instantaneous if so.
-  docker build -t "$BASE_IMAGE" --force-rm=true "tools/dockerfile/interoptest/$BASE_NAME" || exit $?
+  #docker build -t "$BASE_IMAGE" --force-rm=true "tools/dockerfile/interoptest/$BASE_NAME" || exit $?
+  :
 fi
 
 CONTAINER_NAME="build_${BASE_NAME}_$(uuidgen)"
```

"docker build" is only instantaneous if you previously built the same image _on the same machine_.

**Comment by ejona86** [comment]
In client_matrix.py, I see LANG_RUNTIME_MATRIX. For go it seems they have two and change which subset of the runtimes they specify depending on the release. I guess we can do the same.

**Comment by jtattermusch** [comment]
I think we can add the openjdk runtime to 
https://github.com/grpc/grpc/blob/b7da8d39c1dcc105ce3d81fc2f16466e90723dac/tools/interop_matrix/client_matrix.py#L62

and then use the `runtime_subset=['java_oracle8']` argument for older versions and runtime_subset=['java_openjdk'] for the newer versions. Same idea as what we did for go when we had to switch from go1.8 to go1.11 runtime
https://github.com/grpc/grpc/blob/b7da8d39c1dcc105ce3d81fc2f16466e90723dac/tools/interop_matrix/client_matrix.py#L123

**Comment by ejona86** [comment]
@jtattermusch, looking at Go, it appears they still have go1.8 interop files (tools/dockerfile/interoptest/grpc_interop_go1.8). That's not an option here. I need to make sure that master builds only use the new image. It looks like I need to rip out the "check that all selected runtimes are valid for given language" verification in `get_runtimes_for_lang_release()`. I've sent out #19137
