### ISSUE TITLE
Grpc.Tools NuGet package does not deliver grpc_cpp_plugin.exe

### ISSUE THREAD

**Issue by dm185016** [grpc/grpc#19124]
### What version of gRPC and what language are you using?
 I used NuGet package manager in VS2015 to download Grpc.cpp v1.0.1.  Coding in C++.
 
### What operating system (Linux, Windows,...) and version?

Windows 10
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2015 SP 3 and VS2019
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I used the NuGet Package manager to download grpc.cpp v1.0.1 and Grpc.Tools v1.21.0.
 
### What did you expect to see?
I expected the NuGet package to download the grpc_cpp_plugin.exe to E:\Source\Phase3.9\controls\packages\Grpc.Tools.1.21.0\tools\windows_x86.
 
 
### What did you see instead?
The NuGet package only installed grpc_csharp_plugin.exe in that directory.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by dm185016** [comment]
It turns out this package does NOT include anything needed to build C++ code.  There are no headers or libraries installed either.  So does that mean that I need to always build my own when building C++ projects?

**Comment by jtattermusch** [comment]
Let me explain:
- the Grpc.Tools package is mostly meant for C# projects and as such only includes the grpc_csharp_plugin and the msbuild integration for the C# projects. (at some point we might add C++ project support, but it's not a priority and there's no ETA)
- there's no official nuget package for gRPC C++ (in fact the nuget support for C++ projects has always been poorly supported and documented so we're not planning to ever support it) and even if there was, it wouldn't be called Grpc.Tools. Please refer to https://github.com/grpc/grpc/tree/master/src/cpp for how to install and use gRPC C++. On windows you can use cmake and there's also a vcpkg package you could use.

**Comment by jtattermusch** [comment]
Btw, the https://www.nuget.org/packages/grpc.cpp/ is not an official gRPC packages (it was created by one of the contributors) and it's way out of date. You should not use it.
