### ISSUE TITLE
run only tests that are expected to pass by run_test in travis mode on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1912]
On jenkins, C and C++ tests on Windows fails because we include unimplemented tests in our test suite.
Run tests with -t option should only run tests that are expected to pass so I can get green on Jenkins.

This applies to C and C++:
python tools/run_tests/run_tests.py -t -l c
python tools/run_tests/run_tests.py -t -l c++

See here for example:
http://grpc-testing.appspot.com/job/gRPC/24/

**Comment by ctiller** [comment]
Tagging unimplemented-on-windows tests with platform=['posix'] in the
build.json.

**Comment by ctiller** [comment]
^^ should do what you want...

Please file issues for each test that gets tagged (under the Beta milestone)

**Comment by jtattermusch** [comment]
C and C++ on Windows are the last two red balls in Jenkins right now - it would be great if we could get rid of them.
http://grpc-testing.appspot.com/job/gRPC/7/

**Comment by jtattermusch** [comment]
It looks like these C test are currently failing:

all   "..._shutdown_finishes_inflight_calls...." tests
json_rewrite_test
cancel_after_invoke_test

**Comment by nicolasnoble** [comment]
A bunch of the tests have been flagged now to be Posix only.
