### ISSUE TITLE
When is the deadline set for the request and make effect? 

### ISSUE THREAD

**Issue by hittingnote** [grpc/grpc#19155]
Recently, I really care about when the deadline is set for the request and start to count down. I know that if server doesn't return result before deadline, i.e., t_res is greater than D, the request is invalid, but I don't know whether t_res includes the duration that the args are marshaled and the request is waiting for being sent at the client. Does the deadline start to count down after the request is sent out? I hope anyone that familiar with that can help me. Thanks!

**Comment by srini100** [comment]
Deadline is a gRPC concept and handled at gRPC layer. The deadline starts just before the payload is handed down to HTTP/2 layer. The time taken for buffering in HTTP/2, TCP and the network is all part of deadline count down. 
Please ask such question on [grpcio](https://groups.google.com/forum/#!forum/grpc-io) group where more ppl can see your question. Closing it here.
