### ISSUE TITLE
Improve memory-overhead of sending large data-buffers via gRPC

### ISSUE THREAD

**Issue by msn-tldr** [grpc/grpc#19154]
### What version of gRPC and what language are you using?
 1.15 and C++
 
### What operating system (Linux, Windows,...) and version?
 Ubuntu 18.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc/g++ 7.4.0
 
### What did you do?
Using gRPC, I have a client writing data to gRPC server, through an async unary rpc. The data-buffer to be written, is sent as a 'string-field' in protobuf. The client has to make a 'string-copy' of this buffer for gRPC/protobuf. Also the client keeps the data-buffers around, until the rpc is successfully completed implying server has received the data-buffer, otherwise it has to re-try. As the buffers are atleast few MBs, data-transfer throughput has to be reduced to take into account memory-overhead of this copy.

Can this behaviour be improved for communicating large data buffers?  At a very high level, I would recommend having 'zero-copy-ing' large data buffers when passing them to gRPC.

At my current employer, there is an internal implementation of 'zero-copy-buffers' that can be open-sourced with a suitable license, if it helps this effort.

**Comment by msn-tldr** [comment]
Any thoughts here? Would be appreciated...

**Comment by msn-tldr** [comment]
Would appreciate any initial thoughts here.

**Comment by yashykt** [comment]
I am not sure what you mean when you say - the client needs to make a copy of the buffer. If the requirement of creating a copy is just arising from using protobuf and the consequent serialization, you can use ByteBuffer instead.
