### ISSUE TITLE
Python Build Environment wheel Packages are Out of Date

### ISSUE THREAD

**Issue by michaelaelise** [grpc/grpc#19162]
Hi,
When getting google-cloud-pubsub==0.39.1|0.41 and google-api-python-client==1.7.8 using a requirements file during a dpkg build using a line like `pip3 install -r requirements.txt --ignore-installed --target debian/<redacted>` I see the following...

> Collecting futures>=2.2.0 (from grpcio>=1.8.2; extra == "grpc"->google-api-core[grpc]<2.0.0dev,>=1.6.0->google-cloud-pubsub==0.41->-r requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz
Collecting enum34>=1.0.4 (from grpcio>=1.8.2; extra == "grpc"->google-api-core[grpc]<2.0.0dev,>=1.6.0->google-cloud-pubsub==0.41->-r requirements.txt (line 20))

enum34 and futures is being collected and installed even though we are using python3.6

This is on an armhf device running ubuntu 18.04.
pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

When I build the dpkg on an x64 vm using the same repo we have, it does not collect these.

I noticed the link https://github.com/grpc/grpc/issues/9900 where others seem to experience the issue but did not see any resolution.

Looking through the code I see there is a version < 3.4 check

I apologize if this issue is caused by my environment.

Update:

I downloaded the wheels from https://pypi.org/project/grpcio/#files
Inside `grpcio-1.21.1-cp36-cp36m-linux_armv7l.whl` is:

> Metadata-Version: 2.0
> Name: grpcio
> Version: 1.21.1
> Summary: HTTP/2-based RPC framework
> Home-page: https://grpc.io
> Author: The gRPC Authors
> Author-email: grpc-io@googlegroups.com
> License: Apache License 2.0
> Platform: UNKNOWN
> Classifier: Development Status :: 5 - Production/Stable
> Classifier: Programming Language :: Python
> Classifier: Programming Language :: Python :: 2
> Classifier: Programming Language :: Python :: 2.7
> Classifier: Programming Language :: Python :: 3
> Classifier: Programming Language :: Python :: 3.4
> Classifier: Programming Language :: Python :: 3.5
> Classifier: Programming Language :: Python :: 3.6
> Classifier: License :: OSI Approved :: Apache Software License
> Requires-Dist: enum34 (>=1.0.4)
> Requires-Dist: futures (>=2.2.0)
> Requires-Dist: six (>=1.5.2)

And inside `grpcio-1.21.1-cp36-cp36m-manylinux1_x86_64.whl` is:
> Metadata-Version: 2.1
> Name: grpcio
> Version: 1.21.1
> Summary: HTTP/2-based RPC framework
> Home-page: https://grpc.io
> Author: The gRPC Authors
> Author-email: grpc-io@googlegroups.com
> License: Apache License 2.0
> Platform: UNKNOWN
> Classifier: Development Status :: 5 - Production/Stable
> Classifier: Programming Language :: Python
> Classifier: Programming Language :: Python :: 2
> Classifier: Programming Language :: Python :: 2.7
> Classifier: Programming Language :: Python :: 3
> Classifier: Programming Language :: Python :: 3.4
> Classifier: Programming Language :: Python :: 3.5
> Classifier: Programming Language :: Python :: 3.6
> Classifier: License :: OSI Approved :: Apache Software License
> Requires-Dist: six (>=1.5.2)
> Requires-Dist: futures (>=2.2.0); python_version < "3.2"
> Requires-Dist: enum34 (>=1.0.4); python_version < "3.4"

So it appears that the arm package does not have the `python_version` checks.

The arm .whl also contains a `metadata.json` file and the x64 version does not.

**Comment by gnossen** [comment]
@michaelaelise Thanks for the report! This is not due to a problem in your build environment. It's a problem in *ours*. The version of the `wheel` package we're using to build our ARM packages (and probably Windows and Mac too...) are very outdated.

This was actually a large factor in [the trouble we had last week releasing `1.21`](https://github.com/grpc/grpc/issues/19102). I'm co-opting this issue to track this more general problem.

**Comment by michaelaelise** [comment]
Awesome! Thank you.

**Comment by gnossen** [comment]
I believe the Windows build environment still needs to be looked at.
