### ISSUE TITLE
Python: Handling Watch Stream Exception

### ISSUE THREAD

**Issue by neliel123** [grpc/grpc#19166]
### What version of gRPC and what language are you using?
 1.11
 
### What operating system (Linux, Windows,...) and version?
 linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
I have this code that is implemented as a thread as a watch component.

```
class MyWatcher(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)


    def run(self):
        self.init_kube_config()
        python_api = client.CoreV1Api()
        try:
            w = watch.Watch()
            for event in w.stream(python_api.list_namespaced_config_map, namespace="my-namespace"):
                self.process_event(event)
        except ApiException as e:
            logger.error("Exception encountered while watching for event stream :: list_namespaced_config_map :: {}".format(e))
            pass
```
			
But sometimes for some reason, I am getting below exception

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/kube/my_watcher.py", line 21, in run
    for event in w.stream(python_api.list_namespaced_config_map, namespace="my-namespace"):
  File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 128, in stream
    resp = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 27 May 2019 07:48:35 GMT', 'Content-Length': '186'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'
```

Currently I am catching the APIException and let it pass...I am just wondering what should be the proper way to handle this?
Should I stop the watch object and then create a new watch object?

I don't exactly know how to reproduce the error as it seems to be random in nature so I am just wondering what should I do in my except code.

### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by neliel123** [comment]
Upon looking, my error stacktrace seems to be similar to this [internal server error when call watch on list_pod_for_all_namespace](https://github.com/kubernetes-client/python/issues/701) but this seems unanswered as well.

So should I just stop the watch object and then recreate it?
I don't know exactly know how to reproduce this as this seems so random in nature.

**Comment by gnossen** [comment]
@neliel123 I may be missing something. I don't see where gRPC is sitting in your stack. The stacktrace all belongs to the Kubernetes client and the error appears to be JSON over HTTP 1.1. Where does gRPC fit into the picture?

**Comment by neliel123** [comment]
> @neliel123 I may be missing something. I don't see where gRPC is sitting in your stack. The stacktrace all belongs to the Kubernetes client and the error appears to be JSON over HTTP 1.1. Where does gRPC fit into the picture?

Oh sorry posted on the wrong project..closing this then.
