### ISSUE TITLE
latest nuget 1.21.0 can't build in xamarin.ios

### ISSUE THREAD

**Issue by fatfatson** [grpc/grpc#19172]
msbuild error log:
```
"/Users/wellbye/repos/j/mb/mb.iOS/mb.iOS.csproj" (build target) (1) ->
(_CompileToNative target) -> 
  clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/wellbye/repos/j/mb/mb.iOS/mb.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: operator delete(void*). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/wellbye/repos/j/mb/mb.iOS/mb.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: operator new(unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/wellbye/repos/j/mb/mb.iOS/mb.iOS.csproj]
  MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -L/Users/wellbye/repos/j/mb/packages/Grpc.Core.1.21.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load /Users/wellbye/repos/j/mb/packages/Grpc.Core.1.21.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -L/Users/wellbye/repos/j/mb/packages/Grpc.Core.1.21.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load /Users/wellbye/repos/j/mb/packages/Grpc.Core.1.21.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/wellbye/repos/j/mb/mb.iOS/obj/iPhoneSimulator/Debug/Entitlements.xcent [/Users/wellbye/repos/j/mb/mb.iOS/mb.iOS.csproj]
  MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Users/wellbye/repos/j/mb/mb.iOS/mb.iOS.csproj]
```

the xamarin sample in repo is using 1.18.0 which is ok.
so there must be something wrong in the new version.
please check~

**Comment by jtattermusch** [comment]
Let's keep this open.

**Comment by Kozzers** [comment]
I would say this is still relevant, I experience similar errors while trying to run the xamarin demo included.

**Comment by aabc123** [comment]
FWIW, I've been playing with these recently with a Xamarin.Forms app.  Grpc.Core 1.22.1 works OK but the latest 2.29.0 fails with lots of linker errors to do with std::basic_string etc (basically the C++ runtime).  Editing ~/.nuget/packages/grpc.core/2.29.0/build/Xamarin.iOS10/Grpc.Core.Targets and adding

<IsCxx>True</IsCxx>

For both libraries makes it build and run for me (with just linker warnings).  So with this I can use 2.29.0 for both iOS and Android Xamarin.Forms targets.

**Comment by Kozzers** [comment]
@aabc123 Do you just add "True" or was there more to that that got cut off?

**Comment by aabc123** [comment]
Oh, sorry, looks like it's stripped out the IsCxx stuff.  It's an XML tag IsCxx with a value of True.  Like the ForceLoad tag that is there.

**Comment by drchilds** [comment]
Has any progress been made on this issue? I'm unable to use the latest stable builds in a Xamarin.Forms iOS app, even with the RuntimeIdentifiers and NuGetRuntimeIdentifiers workarounds. 1.22.1 seems to be the latest version that will build.

**Comment by chaoyebugao** [comment]
Same problem...

**Comment by neyugnluan** [comment]
[path]]MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -L/[user path MAC OS]/.nuget/packages/grpc.core/2.31.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load /[user path MAC OS]/.nuget/packages/grpc.core/2.31.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -L/[user path MAC OS]/.nuget/packages/grpc.core/2.31.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load /[user path MAC OS]/.nuget/packages/grpc.core/2.31.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a -L/[project path]/packages/Grpc.Core.2.31.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load /[project path]/packages/Grpc.Core.2.31.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -L/[project path]/packages/Grpc.Core.2.31.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load /[project path]]/packages/Grpc.Core.2.31.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a (MT5201)

The same problem, can't make the app running, the error occurred during running.
I saw some workaround like
```
 <PropertyGroup>
    <RuntimeIdentifiers>mac;mac-x86;mac-x64</RuntimeIdentifiers>
    <NuGetRuntimeIdentifier>mac</NuGetRuntimeIdentifier>        
  </PropertyGroup>
```
The above error shows me.

**Comment by pelevinma** [comment]
Same problem. Visual Studio for Mac 2019. Clear mac project. Build failed after installation Grpc

**Comment by jtattermusch** [comment]
Note that the Xamarin example project has been updated in https://github.com/grpc/grpc/pull/24425. Can you try if the problem still persists for you?

**Comment by pelevinma** [comment]
Yes. But maybe my problem is different. I am creating new macos(Cocoa) solution. A clean project compiles successfully. Then I install Grpc (2.33.1 latest stable) via NuGet Packages Manager and get this error:
```
ld: symbol(s) not found for architecture x86_64
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MMP : error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.
```
full log - https://drive.google.com/file/d/1O5Ya4n2XKOX54r6NEGgFOAJPl158EM1F/view?usp=sharing

<img width="400" alt="Screenshot 2020-10-27 at 13 16 42" src="https://user-images.githubusercontent.com/8969713/97288773-63c4df00-1857-11eb-867f-605cc3883d19.png">

**Comment by neyugnluan** [comment]
> Yes. But maybe my problem is different. I am creating new macos(Cocoa) solution. A clean project compiles successfully. Then I install Grpc (2.33.1 latest stable) via NuGet Packages Manager and get this error:
> 
> ```
> /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/maksimp/Projects/testGRPC4/obj/Debug/response-file.rsp 
>     Process exited with code 1, command:
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang System.Collections.Generic.List`1[System.String]
>     Undefined symbols for architecture x86_64:
> ....
> ld: symbol(s) not found for architecture x86_64
> clang : error : linker command failed with exit code 1 (use -v to see invocation)
> MMP : error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.
> ```
> 
> full log - https://drive.google.com/file/d/1O5Ya4n2XKOX54r6NEGgFOAJPl158EM1F/view?usp=sharing
> 
> <img alt="Screenshot 2020-10-27 at 13 16 42" width="400" src="https://user-images.githubusercontent.com/8969713/97288773-63c4df00-1857-11eb-867f-605cc3883d19.png">

I did this way too same error as you
Tried create new project under windows then back to macOS run doesn’t work so far.

**Comment by krjw-eyev** [comment]
I got the same problem on macOS 10.15.7 VS 2019 8.8 with NuGet package 2.33.1 (why does the NuGet package start with 2?)

I get 103 linker errors:

```
/Users/user/Documents_local/Projects/dfsdf.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::exception::~exception(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (sdf.iOS)


/Users/user/Documents_local/Projects/sfsdf.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -L/Users/user/.nuget/packages/grpc.core/2.33.1/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load /Users/user/.nuget/packages/grpc.core/2.33.1/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -L/Users/user/.nuget/packages/grpc.core/2.33.1/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load /Users/user/.nuget/packages/grpc.core/2.33.1/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a (MT5201) (sdf.iOS)

```

`<IsCxx>True</IsCxx>`

and

```
    <PropertyGroup>
        <RuntimeIdentifiers>mac;mac-x86;mac-x64</RuntimeIdentifiers>
        <NuGetRuntimeIdentifier>mac</NuGetRuntimeIdentifier>
    </PropertyGroup>
```

did not help!!

On Android I get `System.DllNotFoundException: grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)` on calling a function.

**Comment by krjw-eyev** [comment]
I got it to work... The Android was an obvious one... I had a x86_64 Emulator but there is no according lib for that.

iOS worked after adding the following to my iOS.csproj:

```
    <Target Name="GrpcCoreShim" BeforeTargets="CoreCompile">
        <PropertyGroup>
            <GrpcCoreTargetsRelativePath>..\..\..\..\..\.nuget\packages\grpc.core\2.33.1\build\Xamarin.iOS10\</GrpcCoreTargetsRelativePath>
        </PropertyGroup>
        <ConvertToAbsolutePath Paths="$(GrpcCoreTargetsRelativePath)">
            <Output TaskParameter="AbsolutePaths" PropertyName="GrpcCoreTargetsAbsPath" />
        </ConvertToAbsolutePath>
        <ItemGroup>
            <NativeReference Remove="libgrpc_csharp_ext.a" />
            <NativeReference Remove="libgrpc.a" />
            <NativeReference Include="$(GrpcCoreTargetsAbsPath)..\..\native\ios\universal\libgrpc_csharp_ext.a">
                <Kind>Static</Kind>
                <ForceLoad>True</ForceLoad>
                <IsCxx>True</IsCxx>
            </NativeReference>
            <NativeReference Include="$(GrpcCoreTargetsAbsPath)..\..\native\ios\universal\libgrpc.a">
                <Kind>Static</Kind>
                <ForceLoad>True</ForceLoad>
                <IsCxx>True</IsCxx>
            </NativeReference>
        </ItemGroup>
    </Target>
```

The amount of `..\`  on `< GrpcCoreTargetsRelativePath>` is individual... maybe an absolute path would wok better...

This is the solution for macOS ... for windows look here: https://techblog.livongo.com/fixing-grpc-xamarin-ios-linking-errors/

**Comment by isax5** [comment]
What´s going on here?
I can't use gRPC on Xamarin.iOS ??
I noticed there is a package call gRPC.Core.Xamarin but it doesn't work correctly yet !!

**Comment by isax5** [comment]
This is still not working !!

**Comment by chaoyebugao** [comment]
Let's keep this open
