### ISSUE TITLE
statuscodes.md: status is UNAVAILABLE if client metadata fails not UNAUTHENTICATED

### ISSUE THREAD

**Issue by evanj** [grpc/grpc#19186]
[`statuscodes.md` states](https://github.com/grpc/grpc/blame/d80650db3110115dc03f68e4aab72f72d4b6736d/doc/statuscodes.md#L57):

* *Case*: "Incorrect Auth metadata ( Credentials failed to get metadata, Incompatible credentials set on channel and call, Invalid host set in :authority metadata, etc.)"
* *Code*: UNAUTHENTICATED
* *Generated at Client or Server*: Both

However, when the client fails to get the authentication metadata from the plugin, it sets the status code to `UNAVAILABLE`. I would suggest updating `statuscodes.md` to document this, either by replacing this row, or by splitting it into two separate cases, or updating the implementation to return the documented code, if it should be. (IMO: It would be weird if the client returned `UNAUTHENTICATED` in this case, but `UNAVAILABLE` also seems a bit weird. I would expect it to return `INTERNAL`, which is what the Python-side of the client plugin actually sets.)

statuscodes.md code reference: https://github.com/grpc/grpc/blame/d80650db3110115dc03f68e4aab72f72d4b6736d/doc/statuscodes.md#L57

Implementation that sets this status code (I think): https://github.com/grpc/grpc/blob/d80650db3110115dc03f68e4aab72f72d4b6736d/src/core/lib/security/transport/client_auth_filter.cc#L163

**Comment by yang-g** [comment]
I noticed that in a recent change (https://github.com/grpc/grpc/pull/19139) too.
Note the plugin credentials can return some status by itself and I believe we should use the returned status as grpc status around here: https://github.com/grpc/grpc/blob/d80650db3110115dc03f68e4aab72f72d4b6736d/src/core/lib/security/credentials/plugin/plugin_credentials.cc#L75

**Comment by evanj** [comment]
That would be ideal! However, that would *still* have a mismatch between what is documented and how the system works. At the very least the Python auth plugin sets the status to `INTERNAL` if it fails, while my reading of `statuscodes.md` that I quoted above suggests it will be `UNAUTHENTICATED`.
