### ISSUE TITLE
Support for sanity test, gcov and GCC tests  on Jenkins

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1918]
Add (or consider adding) jenkins counterparts for these travis builds:
- CONFIG=opt TEST=sanity JOBS=1
- CONFIG=gcov TEST=c JOBS=16
- CONFIG=gcov TEST=c++ JOBS=16
- USE_GCC=4.4 CONFIG=opt TEST=build JOBS=16

As a first stage, perhaps adding the sanity test might be enough.

**Comment by jtattermusch** [comment]
FYI @nicolasnoble 

@ctiller, please also add issues for C/C++ related stuff you'd like to see on Jenkins soon (perhaps things that weren't really feasible on travis). Computing power shouldn't be an issue - I can add more Linux workers as needed.

**Comment by ctiller** [comment]
Seems done?
