### ISSUE TITLE
Make build error

### ISSUE THREAD

**Issue by mandreyel** [grpc/grpc#19192]
I get this compile error when building with make
```
src/cpp/common/channel_filter.cc:33:48: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘grpc_linked_mdelem’ {aka ‘struct grpc_linked_mdelem’}; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(storage, 0, sizeof(grpc_linked_mdelem));
```
 
### What version of gRPC and what language are you using?
 
v.1.20.0
 
### What operating system (Linux, Windows,...) and version?
 
Ubuntu 19.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 8.3.0
GNU Make 4.2.1
 
### What did you do?

```
git clone --depth 1 -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
make
```

**Comment by KeithMoyer** [comment]
I believe this should be fixed by https://github.com/grpc/grpc/pull/19068

**Comment by rodoufu** [comment]
Same here.
Also same OS, gRPC, gcc and make versions.

**Comment by rodoufu** [comment]
> I believe this should be fixed by #19068

Do you know any work around?

**Comment by KeithMoyer** [comment]
My project uses Bazel, not make, so i cannot give a definitive answer (nor would be able to help you debug), but it should be a matter of passing the needed warning flags to the compiler when building.

Something like the following?
```
make CXXFLAGS="-Wno-error=class-memaccess"
```

There were a number of warnings present for a while in gRPC when building with GCC 8, so you may find you need to add more similar flags to silence other things (e.g., -Wno-error=tautological-compare).

**Comment by hcaseyal** [comment]
@rodoufu As stated, this should have been fixed. Please update your gRPC version if you haven't already. @KeithMoyer's suggestions should work as well

**Comment by rodoufu** [comment]
> @rodoufu As stated, this should have been fixed. Please update your gRPC version if you haven't already. @KeithMoyer's suggestions should work as well

@hcaseyal What branch or version from https://github.com/grpc/grpc should I use? I've tried `v1.22.1`, `v1.22.0` and `master`.

**Comment by hcaseyal** [comment]
@rodoufu You tried those versions of gRPC and you're getting the exact same error message in the original post?

**Comment by rodoufu** [comment]
All failed, let me check if it is the same and I came back

**Comment by hcaseyal** [comment]
@rodoufu If it ends up being a different error message, please open up a new issue
