### ISSUE TITLE
The native method "grpcsharp_batch_context_recv_message_to_buffer" does not exist

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc#19211]
### What version of gRPC and what language are you using?
 
1.21.0 / .NET
 
### What operating system (Linux, Windows,...) and version?
 
Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Visual Studio 2017
MSBuild

I have a setup with multiple projects. There is a common library built against .NET Standard 2.0 that references GRPC. On top of that, there is an executable running on .NET Framework 4.6.1 and a library built against .NET Framework 4.6.1 or .NET Framework 4.7.2. The latter library is registered as COM component. 

The exception occurs in the common library when executed through the COM component compiled against either .NET Framework 4.6.1 or 4.7.2. It does, however, not occur on the separate .NET Framework 4.6.1 executable that executes the same library code.
 
### What did you do?
Open a new channel.

`var channel = new Channel($"{host}:{port}", ChannelCredentials.Insecure);`
 
### What did you expect to see?
 
Channel created successfully
 
### What did you see instead?
 
**System.MissingMethodException:** The native method "grpcsharp_batch_context_recv_message_to_buffer" does not exist

Stack trace: 
`   at Grpc.Core.Internal.UnmanagedLibrary.GetNativeMethodDelegate[T](String methodName)`

### Anything else we should know about your project / environment?

There was recently a commit to remove the method in question (8a5b803). The commit message states that it seemed that the method in question is no longer used. Apparently, it is.

**Comment by jtattermusch** [comment]
There seems to be some kind of mismatch between the grpc_csharp_ext version you're using (seems to be v1.21.0) and the Grpc.Core assembly. That's should never happen as grpc_csharp_ext is shipped as part of the Grpc.Core package (so perhaps it somehow didn't get updated properly in your system?).  All references to `grpcsharp_batch_context_recv_message_to_buffer` were removed in https://github.com/grpc/grpc/pull/18865

**Comment by georghinkel** [comment]
Yeah, I just realized that the library in the output folder is 1.16, even though all projects in the solution reference 1.21.0. I have no idea where the 1.16 version comes from. I checked that all assemblies contained in the 1.21.0 package are indeed 1.21.0. However, when I remove the entire build output, VS reproducibly recreates the 1.16 lib.

**Comment by georghinkel** [comment]
One thing I noticed, though, is that the assembly version of gRPC is always 1.0.0.0, regardless of the actual version that is only persisted as informational version and file version. Therefore, the CLR (and perhaps also MSBuild?) will happily load an older version, because it only looks for 1.0.0.0 and this is found regardless of the actual version.

Is there any particular reason why the gRPC version is not persisted in the assembly version, but only in informational version and file version?

**Comment by georghinkel** [comment]
I updated gRPC machine-wide to 1.21.0 and now it works.

**Comment by jtattermusch** [comment]
Ad assembly version: see https://github.com/grpc/grpc/issues/6201 for details.
