### ISSUE TITLE
Channel state is ready when connecting to non-grpc endpoint

### ISSUE THREAD

**Issue by MD-V** [grpc/grpc#19212]
### What version of gRPC and what language are you using?
 1.20.1
 
### What operating system (Linux, Windows,...) and version?
 
Windows 7 / Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
C#, Visual Studio 2017
 
### What did you do?

We are trying to implement a client side CallInvoker which creates and updates the Channel according to a naming service. Therefor we exchange the channel sometimes (new server or disconnect) and we need to know if the Channel was successfully established. 

When connecting to a port that is used by any tcp socket the Channel changes its state to ready (see the following example)

```
    class Program
    {
        private static ChannelState _LastKnownState;
        private static Channel _Channel;

        public static async Task Main(string[] args)
        {
            var ipHostInfo = Dns.GetHostEntry(Dns.GetHostName());
            var ipAddress = ipHostInfo.AddressList.First(a => a.AddressFamily == AddressFamily.InterNetwork);
            var localEndPoint = new IPEndPoint(ipAddress, 11000);

            var socket = new Socket(ipAddress.AddressFamily,
                SocketType.Stream, ProtocolType.Tcp);

            socket.Bind(localEndPoint);
            socket.Listen(100);

            _Channel = new Channel($"{ipAddress}:11000", ChannelCredentials.Insecure);
            SetupNewStateListener();

            await _Channel.ConnectAsync(DateTime.UtcNow.AddMilliseconds(5000));

            Console.ReadKey();
        }

        private static void SetupNewStateListener()
        {
            _Channel.WaitForStateChangedAsync(_Channel.State).ContinueWith(t =>
            {
                _LastKnownState = _Channel.State;
                Console.WriteLine(_LastKnownState);
                if (_Channel.State != ChannelState.Shutdown)
                {
                    SetupNewStateListener();
                }
            });

        }
    }
```
### What did you expect to see?
 
I expect to see a TransientFailure on Channel.State because the channel connects to a non-grpc endpoint and therefor is not ready.
 
### What did you see instead?
 
Channel.State reports ready.

**Comment by jtattermusch** [comment]
I think channel is set as ready whenever the underlying TCP connection is established and there's no way of knowing if the peer is talking gRPC protocol unless you start an RPC (which makes sense, how would you make sure that the server talks grpc protocol without sending a request to it?).

Btw, in most cases you don't need to call channel.ConnectAsync() - just starting an RPC will trigger the connection automatically. if you just create a channel and start a call, you'll get an error if the server isn't actually a gRPC server.
