### ISSUE TITLE
First message in server-streaming stream is not sent if client connects to a just-started server.

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#19215]
### What version of gRPC and what language are you using?
 Client - gRPC v1.21.0 for Java (Android)
Server - gRPC v1.21.0 for C# (dotnet core 2.1)
 
### What operating system (Linux, Windows,...) and version?
 Client - Android 8, Android 9
Server - Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 All packages were taken from official builds (Nuget, Gradle)
 
### What did you do?
 When a client initiates a server-side streaming RPC call, while the server is not yet up - once the server is loaded (*before* the client times out), and the connection is established, the first message written to the write-end of the stream (on the server side - `IServerStreamWriter`) is not sent. When a second `WriteAsync` call is made, then both messages are sent immediately.
On other cases where the server is already up when the client initiates the RPC call, everything works well
 
### What did you expect to see?
 The first call to `WriteAsync` should send the message immediately.
 
### What did you see instead?
 The message wan't sent until a second message was written to the stream.
When the server is already up when the client initiates the RPC call, everything works well.

**Comment by jtattermusch** [comment]
Could you provide a snippet that reproduces this? Does this only happen with Android Java client against C# server or in other languages as well?

**Comment by amitwaisel** [comment]
Here are some snippets:

**proto**
```proto
rpc FetchCommands (FetchCommandRequest) returns (stream FetchCommandResponse) { }
```

**client (Android)**
```java
...
// Called from `AsyncTask`'s `doInBackground` callback - like in your Android example code
Iterator<FetchCommandResponse> commands = blockingStub.fetchCommands(request);
...
// Called from `AsyncTask`s `onPostExecute` callback (on UI thread)
// - so we use thread executor to read the stream asynchronously without blocking the UI thread
Executor executor = Executors.newSingleThreadExecutor();
executor.execute(new Runnable() {
    @Override
    void run() {
         // >> This line doesn't return (sometimes) after C#'s first call to `WriteAsync`
        while (commands.hasNext()) {
            FetchCommandResponse command = commands.next();
            ....
        }
    }
});
...
```

**server (C# on Windows dotnet core 2.1)**
```C#
public override async Task FetchCommands(FetchCommandRequest request,
    IServerStreamWriter<FetchCommandResponse> responseStream, ServerCallContext context)
{
    while (!context.CancellationToken.IsCancellationRequested)
    {
        var command = await pending_commands.Dequeue(context.CancellationToken);
        await commands_stream.WriteAsync(command);
    }
}
```

If it's not helpful, we can try to reproduce it on a smaller scale.

**Comment by jtattermusch** [comment]
Is this only reproducible when the client is on Android  and the Server is on windows, or have you also seen it in other situations (e.g. linux client to linux server  or windows client to windows server)?
How often is "sometimes" in ` This line doesn't return (sometimes)`?

**Comment by amitwaisel** [comment]
Hi @jtattermusch I missed your last comment
I think it happens all the time under the circumstances described (the server is loaded during the connection initialization process from the client side). My code already bypasses this issue (triggers multiple calls to “flush the buffers” on connection) so I cannot know for sure if it still happens on latest versions. I encountered it only on Android client + Windows server, although I didn’t try the same flow on other platforms

**Comment by gnossen** [comment]
@jtattermusch Ping.

**Comment by jtattermusch** [comment]
This seems similar to https://github.com/grpc/grpc/issues/21484.

Reproducing with the Android client + Windows server setup is difficult, it would be helpful if there was a reproduction on a single system only.

**Comment by jtattermusch** [comment]
@amitwaisel  it would be good to know at which point the data gets stuck when the first message is not delivered.
Can you try running the server with GRPC_VERBOSITY=debug GRPC_TRACE=tcp to see if the payload of the first message is actually read on the server side (but the server side logic doesn't emit the received message to the user code)?

**Comment by amitwaisel** [comment]
It does sound similar to #21484. My application's connection flow was significantly changed since, and so are the software versions, it is not trivial to re-test it immediately. I will try to setup a small test to see if it is reproducible.

**Comment by jtattermusch** [comment]
> It does sound similar to #21484. My application's connection flow was significantly changed since, and so are the software versions, it is not trivial to re-test it immediately. I will try to setup a small test to see if it is reproducible.

Great! Ideally you'd provide ready-to-run project (e.g. in a github repo) that reproduces the problem.

**Comment by jtattermusch** [comment]
I can reopen once there's a reproduction.

**Comment by Sequel1** [comment]
Same problem here.
First message is sent as second message is triggered. Subsequent messages are fine
We use c# gRPC NuGet v2.28.1 and have a .Net Standard 2.0 server and .net core 3.1 web service as a client both on Win10.
We encounter the problem on each start of the gRPC stream on first message after AsyncServerStreamingCall.

Please reopen this issue.

**Comment by jtattermusch** [comment]
@Sequel1  please provide a reproduction (ideally as a project in a github repo) that demonstrates the problem.

**Comment by MaximGurschi** [comment]
Seeing the same issue. Running on Windows 10.

API is client UNI, service Streaming. For a client request there are precisely 2 service responses. The service sends the first response (ie performs WriteAsync). The client does not receive it until the service completes the web request.

**Comment by MaximGurschi** [comment]
Looks like this only occurs if i use HttpClient. If i revert to using SocketsHttpHandler then it behaves as expected?

**Comment by jtattermusch** [comment]
> Looks like this only occurs if i use HttpClient. If i revert to using SocketsHttpHandler then it behaves as expected?

Does that mean that you can reproduce with using Grpc.Net.Client (from https://github.com/grpc/grpc-dotnet) against a Grpc.Core server?
If so, then the issue could be at the server side as the original issue reports the problem with a grpc-java client against a Grpc.Core (C#) server. The problem could be that the messages are actually not sent on the wire by the C# server - which should be visible from the logs (if extra logging & tracing is enabled).

Again having a working reproduction would help a lot (as a github repo?) - without it it's hard to assess who is seeing what behavior exactly and also to debug.

**Comment by jtattermusch** [comment]
I can reopen this once there's a working reproduction.
