### ISSUE TITLE
Add Blazor support for gRPC C#

### ISSUE THREAD

**Issue by Galileon** [grpc/grpc#19210]
Hi, Please make support for Blazor App. Looks like there is a problem about Error: 
```
System.InvalidOperationException: Unsupported platform.
  at Grpc.Core.Internal.NativeExtension.GetNativeLibraryFilename ()
```
Thanx

**Comment by jtattermusch** [comment]
More details would be useful.

**Comment by jtattermusch** [comment]
Also, have you tried https://github.com/grpc/grpc-dotnet?

**Comment by Galileon** [comment]
hi thanx i will check but the problem is that i try to use existing library which have this grpcclient code generated and its based on grpc main lib ( referenced ).

**Comment by jtattermusch** [comment]
Closing until there's more details what's needed and whether it's feasible.

**Comment by markdchurchill** [comment]
This will not be feasible. Blazor sits on top of the browser/wasm - it will run into the same issues as a hypothetical native JS implementation, and would have to use a proxy.

**Comment by rafaelbfs** [comment]
> Also, have you tried https://github.com/grpc/grpc-dotnet?

@jtattermusch Will happen the same here the reason why:

> Please note that gRPC for .NET does not replace gRPC for C# (gRPC C# API over native C-core binaries). These implementations coexist and share many of the same APIs to avoid lock-in.
