### ISSUE TITLE
Subset of ruby distrib tests is failing consistently on linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#19229]
For some distros the tests are failing consistently on master.

Recent failures:
https://source.cloud.google.com/results/invocations/e63349a3-d065-4e17-b9ec-9e68dc73b414/targets/github%2Fgrpc/tests
https://source.cloud.google.com/results/invocations/3b896123-222e-4511-b28e-2effdd0311b7/targets/github%2Fgrpc/tests

**Comment by apolcyn** [comment]
I checked failures and looks like this are all in tests that run on ruby 2.2, but when fetching protobuf 3.8 (which no longer supports ruby 2.2). So this will be a test fix:

All errors are:

```
google-protobuf-3.8.0-x86_64-linux requires ruby version >= 2.3, which is
incompatible with the current version, ruby 2.2.10p489
```

**Comment by apolcyn** [comment]
WIP dropping ruby 2.2 support in https://github.com/grpc/grpc/pull/19304

**Comment by apolcyn** [comment]
FTR ran into a problem: the centos6 distrib test platforms have dockerfiles which aren't rebuildable without changes to a typical host system doing the building, the problem is described in https://github.com/moby/moby/issues/34301
