### ISSUE TITLE
Properly Specify Channel.close Behavior in Python

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#19235]
`Channel.close` and `__del__` semantics in Python have been a contentious issue for a while. There's a TODO comment in https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L1096 referencing an issue to call `close()` on `__del__` and require `Channel.close` at all times. In the meanwhile, it's not perfectly documented how `close`  will interact with `subscribe/unsubscribe`, etc. Let's fix these issues, decide on the semantics, and document the `close()` API appropriately. (I just encountered a timeout (deadlock?) on process termination issue in a test that was not explicitly closing that happens only under Python3 that I am trying to isolate and repro that reminded me of this problem.)

Historically, `close` was not available, and various resource leaks that are mostly fixed or at least much less problematic, made it a critical feature.  Looking at the way gRPC is used, I observe the following two statements to be true:

- To say we "require" `close` is quite meaningless. What are we going to do if the user does not `close` and process terminates? It's not at all acceptable to interfere with clean exit of the process even without `close`, so there's no choice but to handle it gracefully.
- It's probably not acceptable to ever make `__del__` call `close`, unless all active calls hold a reference to the Python `Channel` object. Otherwise, if a channel object goes out of scope directly, which is a sensible thing in complex uses of gRPC, all active calls get terminated behind the user's back, which is quite weird. 

In light of the above, I think the comment on "requiring" `close` should be removed. `close` should be optional (and encouraged maybe? I am not sure about it as folks end up closing and recreating channels per RPC which is problematic) in simple cases when possible, with its intent documented as something in line with "cancelling all active calls, connectivity subscriptions, and releasing all resources consumed by calls/channel right away", but you would not be required to `close` channels before process terminates. When you do not call close, the channel still tries to minimize its resource use and deallocate resources as it gets done with things like finished calls, threads used for them, and is carefully written not to interfere with process termination in any way. If channel goes out of scope, active calls and connectivity subscriptions should remain active as long as there's a sensible way to interact with them (e.g. through the `Call` object or an active request generator thread). Garbage collector should not terminate those just because you lost an explicit reference to the channel.

What do you think @lidizheng @gnossen @srini100?

**Comment by gnossen** [comment]
This loose end definitely needs to be tied up. We just recently improved our internal documentation to clarify this issue. The most confounding issue for people was the fact that memory will leak if `close()` is not called. I also agree that `close()` shouldn't be called from `__del__`

**Comment by mehrdada** [comment]
Not just memory leak--I think some concerns were there for background threads attributed to streaming/future calls, but yeah.

And we need to in fact advocate to reuse channels as opposed to burn and recreate.

**Comment by lidizheng** [comment]
If I read your description correctly, the two major issues of current Channel close implementations are:

1) Interfere with process termination;
2) All client-side features are bound with the life cycle of the Channel object.

The first issue is definitely a bug need to fix. The second one may need to re-deisgn the way how gRPC client-side object wired together to make garbage collection work in the way we want.

**Comment by mehrdada** [comment]
@lidizheng I agree (1) is a bug. (2) is not even clearly documented (even if we don't "redesign" we need to document). 

There's a (3) which is removing that comment from `close()` API which I suppose is a subset of (2). I guess what I really am looking for is spending a couple hours thinking hard about the requirement and having a clear design and then fix the "bugs" (contradictions in the current implementation).

If you are planning to cut Python2.7, I would prioritize this, so people who end up sticking to an old versions end up having a proper and stable API/documentation to rely on that has been iterated on a couple releases, so you don't have to worry about backporting stuff later to 1.26.x under duress of inevitable Py2.7 customers. :D

**Comment by lidizheng** [comment]
@mehrdada Thank you for noting about the PY2 cut. It is indeed burning...

For issue (2), I guess I have to dig into how each of the following object you mentioned react to Channel object deallocation to proceed:
* Ongoing RPC calls
* Connectivity subscription
* Registered callbacks

**Comment by sathuhareesh** [comment]
@mehrdada Can you tell me what happens when a channel connection times out (Basically after default channel timeout set on server side.) Will all the active RPC calls fail? How does this even work. I have been doing research regarding this from last 4 days but no help.
