### ISSUE TITLE
py_proto_library and py_grpc_library Bazel macros

### ISSUE THREAD

**Issue by g-easy** [grpc/grpc#19255]
Please provide `py_proto_library` and `py_grpc_library` macros that mirror the semantics of the existing `cc_proto_library` and `cc_grpc_library` macros.

This would be very useful for Python language support in googleapis, envoy, opencensus-proto, and probably many other projects.

**Comment by gnossen** [comment]
Related: https://github.com/grpc/grpc/pull/19183

**Comment by kyessenov** [comment]
Any progress on this?

**Comment by gnossen** [comment]
@kyessenov  No updates yet. I'm hoping to get to this soon. The beginning of next quarter at the latest.

**Comment by kyessenov** [comment]
Any news on this? We'd like to move forward with moving googleapis dependency forward. As far as I understand it, this is holding us at pinned versions of opencensus, googleapis, etc in envoy.

**Comment by gnossen** [comment]
@kyessenov This is actively being worked. I'll post here as changes are checked in.

**Comment by kyessenov** [comment]
The immediate issue has been resolved in envoy, but we'd prefer a long term solution. The rules have been added to googleapis here: https://github.com/googleapis/googleapis/blob/master/google/api/BUILD.bazel#L534
(`py_proto_library` is mapped to "" in the repository rule).

**Comment by gnossen** [comment]
This should be good to go now. You can see an example usage in the test for these macros. https://github.com/grpc/grpc/blob/835786a476c250a30e7d95bf4c335cdbcf3a47c2/bazel/test/python_test_repo/BUILD#L30
