### ISSUE TITLE
grpc make failed: protoc-gen-grpc: Plugin killed by signal 6: generated_message_util.cc:794] CHECK failed

### ISSUE THREAD

**Issue by lianfulei** [grpc/grpc#19265]
cd /root/grpc
make 

errors

```
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/channelz/channelz.proto
[libprotobuf FATAL google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
make: *** [/root/grpc/gens/src/proto/grpc/channelz/channelz.grpc.pb.cc] Error 1
```

**Comment by jtattermusch** [comment]
Many people run `make` on our repo every day and it works for them just fine, so it's likely you'll need to provide more details about your system, otherwise we won't be able to reproduce.

**Comment by jtattermusch** [comment]
A dockerfile that demonstrates the problem would be useful.

**Comment by danieljoos** [comment]
Had a similar issue.
The problem was caused by a missing linker dependency to `pthread`. Without that it fails to start the main thread of the plugin and aborts (signal 6).
Adding `-pthread` to the `CMAKE_EXE_LINKER_FLAGS` solved the problem for me. (There might be more elegant ways to solve it, though)

**Comment by lianfulei** [comment]
I've settled it.

**Comment by colfox** [comment]
Hi, I have the same issue on ubuntu 14.04, how did you settle it?
