### ISSUE TITLE
in grpc._channel.Channel constructor, compression argument is documented as optional but it's not

### ISSUE THREAD

**Issue by phinicota** [grpc/grpc#19268]
### What version of gRPC and what language are you using?

grpcio 1.21.1
 
### What operating system (Linux, Windows,...) and version?

 Linux (Ubuntu 14.04, though the problem is not related to this)
 
### What did you do?

Our codebase (python) has a class that inherits from ~~`grpc.Channel`~~ `grpc._channel.Channel`.
Apparently the constructor of ~~`grpc.Channel`~~ `grpc._channel.Channel` changed since version `1.20.1` and now takes one more argument.

```python
>> super(Channel, self).__init__('{}:{}'.format(ip, port), options,
>> None)
> E TypeError: __init__() takes exactly 5 arguments (4 given)
```
 
### What did you expect to see?

According to `grpc.Channel` documentation, the `compression` argument should be **optional**. Here it is:

```python
 class Channel(grpc.Channel):
    """A cygrpc.Channel-backed implementation of grpc.Channel."""

    def __init__(self, target, options, credentials, compression):
        """Constructor.

        Args:
          target: The target to which to connect.
          options: Configuration options for the channel.
          credentials: A cygrpc.ChannelCredentials or None.
          compression: An optional value indicating the compression method to be
            used over the lifetime of the channel.
        """
``` 
 
### What did you see instead?
 
I expect an **optional** argument to have a **default** value so that we can call the constructor safely without providing it.

If a default argument is not provided then documentation is wrong and it should **not** say it's optional.

**Comment by gnossen** [comment]
`grpc.Channel` has not changed. The snippet you listed above is the definition of `grpc._channel.Channel`.  As the underscore in the module indicates, that class is module-private. It is *not* part of our public API.

But you are right, the docstring here is inaccurate.

**Comment by phinicota** [comment]
> `grpc.Channel` has not changed. The snippet you listed above is the definition of `grpc._channel.Channel`. As the underscore in the module indicates, that class is module-private. It is _not_ part of our public API.

Yup, my bad.
Thanks for the clarification.

**Comment by gnossen** [comment]
@phinicota I'm still interested in supporting your use case though. Can you link to your project? In situations like this, we've preferred composition over inheritance in the past.

**Comment by phinicota** [comment]
I'm afraid it's a closed source project.
Here's a representing snippet though it doesn't show much:
```python
class Channel(_channel.Channel):
    DEFAULT_ARGS = (
        ('grpc.initial_reconnect_backoff_ms', INITIAL_RECONNECT_BACKOFF_MS),
        ('grpc.min_reconnect_backoff_ms', 100),
        ('grpc.max_reconnect_backoff_ms', 1000),
        ('grpc.max_receive_message_length', -1),
    )
    def __init__(self, ip=DEFAULT_IP, port=DEFAULT_PORT, options=DEFAULT_ARGS):
        super(Channel, self).__init__('{}:{}'.format(ip, port), options, None)
    def state(self):
        return self._channel.check_connectivity_state(True)
```

> In situations like this, we've preferred composition over inheritance in the past.

In hindsight, we probably should have opted for composition.
I believe the original intention was to define an easy access method for the channel state.
I've checked out the API just now to see if there was another way and it seems our use case could be solved with [grpc.channel_ready_future](https://grpc.github.io/grpc/python/grpc.html#grpc.channel_ready_future) or [Channel.subscribe](https://grpc.github.io/grpc/python/grpc.html#grpc.Channel.subscribe).

**Comment by gnossen** [comment]
Right. I think your use case could be solved like this:

```python3
# Disclaimer: Untested sample code.
class CustomChannel(grpc.Channel):
    def __init__(self, ip=DEFAULT_IP, port=DEFAULT_PORT, options=DEFAULT_OPTIONS):
        self._underlying_channel = CustomChannel(grpc.secure_channel(f"{ip}:{port}", options=options))
        self._connectivity = False
        self._connectivity_lock = threading.RLock()
        self._underlying_channel.subscribe(on_connectivity_change)

    def on_connectivity_change(self, connectivity):
        with self._connectivity_lock:
            self._connectivity = connectivity            

    def state(self):
        with self._connectivity_lock:
            return self._connectivity

    def close(self):
        self._underlying_channel.close()
    
    def stream_stream(self, *args, **kwargs):
        return self._underlying_channel.stream_stream(*args, **kwargs)

    # And so on for all abstract methods on grpc.Channel.
    # If this is too much boilerplate for you, you could probably hack it with __getattr__.
```

Note that `grpc._cython.cygrpc.Channel.check_connectivity_state` is also an internal API. We make no guarantees about its stability.

**Comment by phinicota** [comment]
You're right, thanks!
