### ISSUE TITLE
Support OpenSSL with no NPN

### ISSUE THREAD

**Issue by sujiths** [grpc/grpc#19273]
### What version of gRPC and what language are you using?
grpc version 1.20.0
Language : C++
 
### What operating system (Linux, Windows,...) and version?
 MacOS 10.14.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang x86_64-apple-darwin18.6.0
 
### What did you do?
compile with opensslconf.h where OPENSSL_NO_NEXTPROTONEG is defined 
 
### What did you expect to see?
 successful compilation
 
### What did you see instead?
[CXX]     Compiling src/core/tsi/ssl_transport_security.cc
src/core/tsi/ssl_transport_security.cc:1039:5: error: use of undeclared identifier 'SSL_get0_next_proto_negotiated'
    SSL_get0_next_proto_negotiated(impl->ssl, &alpn_selected,
    ^
src/core/tsi/ssl_transport_security.cc:1726:7: error: use of undeclared identifier 'SSL_CTX_set_next_proto_select_cb'; did you mean 'SSL_CTX_set_alpn_select_cb'?
      SSL_CTX_set_next_proto_select_cb(
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      SSL_CTX_set_alpn_select_cb
/Users/sujsudha/Perforce/sujsudha_dev/ngc/proj_Negasonic_nvm/published/openssl/include/openssl/ssl.h:1319:6: note: 'SSL_CTX_set_alpn_select_cb' declared here
void SSL_CTX_set_alpn_select_cb(SSL_CTX *ctx,
     ^
src/core/tsi/ssl_transport_security.cc:1727:24: error: cannot initialize a parameter of type 'int (*)(SSL *, const unsigned char **, unsigned char *, const unsigned
      char *, unsigned int, void *)' (aka 'int (*)(ssl_st *, const unsigned char **, unsigned char *, const unsigned char *, unsigned int, void *)') with an lvalue
      of type 'int (SSL *, unsigned char **, unsigned char *, const unsigned char *, unsigned int, void *)' (aka 'int (ssl_st *, unsigned char **, unsigned char *,
      const unsigned char *, unsigned int, void *)'): type mismatch at 2nd parameter ('const unsigned char **' vs 'unsigned char **')
          ssl_context, client_handshaker_factory_npn_callback, impl);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sujsudha/Perforce/sujsudha_dev/ngc/proj_Negasonic_nvm/published/openssl/include/openssl/ssl.h:1320:39: note: passing argument to parameter 'cb' here
                                int (*cb) (SSL *ssl,
                                      ^
src/core/tsi/ssl_transport_security.cc:1905:7: error: use of undeclared identifier 'SSL_CTX_set_next_protos_advertised_cb'
      SSL_CTX_set_next_protos_advertised_cb(
      ^
4 errors generated.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by rmstar** [comment]
@jiangtaoli2016 PTAL

**Comment by GetcharWu** [comment]
Greetings, I've encountered a similar issue. May I inquire if you've already discovered a solution?
