### ISSUE TITLE
grpc_interop_alts is broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#19271]
first failing build is:
https://source.cloud.google.com/results/invocations/ee62184b-85d9-4281-8349-93d323772cab/targets/github%2Fgrpc%2Finterop_test/tests
since then all the builds on master are failing

I wasn't able to link the problem to any merged PR.

**Comment by yihuazhang** [comment]
It seems all failed tests involve either Java client or server. @jiangtaoli2016, do you know if there is any recent changes at Java side?

**Comment by jiangtaoli2016** [comment]
@carl-mastrangelo Any recent change in Java could trigger this?

**Comment by jiangtaoli2016** [comment]
The root is because the recent change
https://github.com/grpc/grpc-java/commit/7657523b28624016cf3ca642c02e713da5f33ca3#diff-7e67d9b63c2f5c408b886cd90c2b0027L139
Handshaker service returns 128-bytes, ALTS stack only need less. So we only copy what is needed.
