### ISSUE TITLE
php: Missing releases from packagist  1.21.3

### ISSUE THREAD

**Issue by sebglon** [grpc/grpc#19284]
### What version of gRPC and what language are you using?
GRPC 1.21.3
PHP 7 
 
 
### What did you do?
the php package  1.21.3 is not available on packagist
  
### What did you expect to see?
 packagist can have version 1.21.3
 
### What did you see instead?
https://packagist.org/packages/grpc/grpc

**Comment by stanley-cheung** [comment]
Pushed the v1.22.0 tag today.
