### ISSUE TITLE
Benchmarking dashboard hasn't been updating for a while

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#19289]
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

It looks like the data stopped around May 28th.

**Comment by lidizheng** [comment]
Ping?

Performance dashboards under (https://grpc.io/docs/guides/benchmarking/) are not functional...
* Multi-language performance dashboard @latest_release (lastest available stable release)
* Multi-language performance dashboard @master (latest dev version)
* C++ detailed performance dashboard @master (latest dev version)

**Comment by jtattermusch** [comment]
It looks like that one of the 8core workers (we are reusing a set of dedicated VMs for each run) has run out of the disk space
```
+ ssh kbuilder@grpc-kokoro-performance-client2-8core 'tar -xf ~/performance_workspace/grpc.tar -C ~/performance_workspace || tar -xf ~/performance_workspace/grpc.tar -C ~/performance_workspace'
tar: grpc-node/.git/modules/packages/grpc-native-core/deps/grpc/modules/third_party/boringssl-with-bazel/index: Wrote only 1024 of 10240 bytes
tar: grpc-node/.git/modules/packages/grpc-native-core/deps/grpc/modules/third_party/boringssl-with-bazel/logs: Cannot mkdir: No space left on device
tar: grpc-node/.git/modules/packages/grpc-native-core/deps/grpc/modules/third_party/boringssl-with-bazel/logs: Cannot mkdir: No space left on device
tar: grpc-node/.git/modules/packages/grpc-native-core/deps/grpc/modules/third_party/boringssl-with-bazel/logs/HEAD: Cannot open: No such file or directory
tar: grpc-node/.git/modules/packages/grpc-native-core/deps/grpc/modules/third_party/boringssl-with-bazel/logs: Cannot mkdir: No space left on device
```

**Comment by jtattermusch** [comment]
It turns out this was because of https://github.com/grpc/grpc/issues/19289 which over time left a huge number of exited containers on the disk. (the problem didn't affect 32core workers and python benchmarks are only run on 8core)
the exited containers can be easily cleaned up by docker `rm $( docker ps -q -f status=exited)`, but the tricky part is SSHing to the VMs that have a full disk

**Comment by jtattermusch** [comment]
@lidizheng  problems like this are yet more evidence we need the kubernetes-based benchmark setup that will make the setup easier to maintain.

**Comment by jtattermusch** [comment]
I cleaned up the old containers or worker VMs, the benchmark dashboard should start being populated soon.
