### ISSUE TITLE
Test building C/C++ with GCC on Jenkins

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1928]
4.4, 4.6, 4.9, ~~5.1~~ 5.3
opt, dbg.

**Comment by ctiller** [comment]
@jtattermusch has got infrastructure in place, but there are some build failures:
1. fix bugs
2. tag Jan
3. PROFIT

**Comment by jtattermusch** [comment]
How to test this:

`tools/run_tests/run_tests.py -l c++ --compiler clang3.4 --use_docker`  (don't forget the --use_docker).

Currently, there's support for clang3.4 and clang3.6  and gcc4.4 and gcc5.3.

**Comment by jtattermusch** [comment]
More compiler versions can be added pretty easily by adding new dockerfiles.

**Comment by jtattermusch** [comment]
For C core, we seem to be covered pretty well. (https://grpc-testing.appspot.com/job/gRPC_portability_master/)  We need to make sure tests are passing for c++ and then we can add it.

**Comment by jtattermusch** [comment]
`tools/run_tests/run_tests.py -l c++ --compiler clang3.4 --use_docker`  seems to work well.

`tools/run_tests/run_tests.py -l c++ --compiler clang3.6 --use_docker`  fails with warnings being treated like errors.

**Comment by jtattermusch** [comment]
`tools/run_tests/run_tests.py -l c++ --compiler gcc5.3 --use_docker` also fails to build with warnings.

**Comment by vjpai** [comment]
This has mostly gone to Jan recently so I'm making that official with the assignment

**Comment by jtattermusch** [comment]
Well, I've setup the infrastructure to run the tests and see the issues with compilation and tests, but now I need to people to actually run the run_tests.py script using the examples I've provided and fix compiler warnings and test failures.

Assigning back to @vjpai, but it would be great if other C core team members could help a bit as well.

**Comment by vjpai** [comment]
I have gotten most of the C++ issues sorted with regard to gcc-4.4 : nullptr comparisons, range-based for, etc. I will document this as well. But there is still an issue outstanding in that gcc-4.4 does not work with map<T, unique_ptr<P>> . This appears in the ServerBuilderPlugin API, so I think it is API-affecting. It's the copy-constructor issue that I had previously worked on. I am going to raise this issue to the C++.

**Comment by jtattermusch** [comment]
Current  portability status for C/C++ code (after merging #6869)
https://grpc-testing.appspot.com/job/gRPC_portability_master/2974/

gcc4.4 and 4.6 need some work, 
for other configurations, things build and some tests are failing (tests.bins/dbg/qps_openloop_test polling=poll seems to time out for several compilers?)
