### ISSUE TITLE
compilation error version v1.21.0

### ISSUE THREAD

**Issue by diiiego83** [grpc/grpc#19286]
### What version of gRPC and what language are you using?
v 1.21.0 
 
### What operating system (Linux, Windows,...) and version?
 Linux lubuntu (Ubuntu 18.10)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 8.3.0 
 
### What did you do?
cd $HOME/Downloads
wget -q https://github.com/grpc/grpc/archive/v1.21.0.tar.gz
tar -xf v1.21.0.tar.gz
cd $HOME/Downloads/grpc-1.21.0
make -j $(nproc)
sudo make install
sudo ldconfig
 
### What did you expect to see?
compiles with no errors
 
### What did you see instead?
src/cpp/common/channel_filter.cc: In member function ‘grpc_linked_mdelem* grpc::MetadataBatch::AddMetadata(const string&, const string&)’:
src/cpp/common/channel_filter.cc:33:48: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘grpc_linked_mdelem’ {aka ‘struct grpc_linked_mdelem’}; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(storage, 0, sizeof(grpc_linked_mdelem));
                                                ^
In file included from ./src/core/lib/transport/transport.h:35,
                 from ./src/core/lib/channel/channel_stack.h:48,
                 from src/cpp/common/channel_filter.cc:21:
./src/core/lib/transport/metadata_batch.h:33:16: note: ‘grpc_linked_mdelem’ {aka ‘struct grpc_linked_mdelem’} declared here
 typedef struct grpc_linked_mdelem {
                ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:2958: /home/diego/Downloads/grpc-1.21.0/objs/opt/src/cpp/common/channel_filter.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by KeithMoyer** [comment]
I believe this should be fixed by https://github.com/grpc/grpc/pull/19068

**Comment by AspirinSJL** [comment]
Please reopen if it still exists.
