### ISSUE TITLE
Test building C++ with clang on Jenkins

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1929]
Versions 3.5, 3.6, 3.7.
opt, dbg.

**Comment by jtattermusch** [comment]
Just as for https://github.com/grpc/grpc/issues/1928, the infrastructure is setup, now we need to make sure C/C++ compiles and fix tests.

**Comment by jtattermusch** [comment]
clang3.4 is currently broken but it's NOT our target for GA (verified with @ctiller).

**Comment by jtattermusch** [comment]
Current portability status for C/C++ code (after merging #6869)
https://grpc-testing.appspot.com/job/gRPC_portability_master/2974/

gcc4.4 and 4.6 need some work, 
for other configurations, things build and some tests are failing (tests.bins/dbg/qps_openloop_test polling=poll seems to time out for several compilers?)
