### ISSUE TITLE
Cxx interop build for v1.21.3 failing

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#19295]
cxx interop build for v1.21.3 is failing with the following errors. Python and csharp are building fine and tests are also passing.

Get:3 http://security.debian.org jessie/updates/main amd64 Packages [849 kB]
Get:4 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10000 kB in 27s (364 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
Removing intermediate container c34768df44fe
The command '/bin/sh -c apt-get update && apt-get -y install libgflags-dev libgtest-dev libc++-dev clang && apt-get clean' returned a non-zero code: 100
+ exit 100
FAILED: build_docker_cxx [ret=100, pid=46551, time=42.3sec]
FAILED: Failed to build interop docker images.

**Comment by srini100** [comment]
@jtattermusch, please reassign as needed. This is a new error.

**Comment by jtattermusch** [comment]
I was able to build cxx interop docker images for v1.21.4 just fine. Was this just an intermittent error?
You also might have stale docker cache (try running `docker pull debian:jessie` first).

**Comment by srini100** [comment]
Running `docker pull debian:jessie` resolved the issue. Thanks.
