### ISSUE TITLE
Error: using typedef-name 'grpc::CompletionQueue' after 'class' class ServerCompletionQueue;

### ISSUE THREAD

**Issue by spinkernel** [grpc/grpc#19293]
### What version of gRPC and what language are you using?
Git HEAD (f8b1e6cb44..bb6a97b0c8), C++ (during make)
 
### What operating system (Linux, Windows,...) and version?
Linux ubuntu 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 powerpc-604-linux-gnu-gcc -v
Using built-in specs.
COLLECT_GCC=powerpc-604-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/home/user/ueipac-4.0.2/powerpc-604-linux-gnu/bin/../libexec/gcc/powerpc-604-linux-gnu/6.3.0/lto-wrapper
Target: powerpc-604-linux-gnu
Configured with: /home/aservadio/SVN_TMP/UEIPAC/cross-compiler/ueipac-gcc/targets/src/gcc-6.3.0/configure --build=i686-build_pc-linux-gnu --host=i686-build_pc-linux-gnu --target=powerpc-604-linux-gnu --prefix=/home/aservadio/x-tools/powerpc-604-linux-gnu --with-sysroot=/home/aservadio/x-tools/powerpc-604-linux-gnu/powerpc-604-linux-gnu/sysroot --enable-languages=c,c++ --with-cpu=604 --with-float=hard --with-pkgversion='crosstool-NG crosstool-ng-1.23.0' --enable-__cxa_atexit --disable-libmudflap --disable-libgomp --disable-libssp --disable-libquadmath --disable-libquadmath-support --disable-libsanitizer --disable-libmpx --with-gmp=/home/aservadio/SVN_TMP/UEIPAC/cross-compiler/ueipac-gcc/targets/powerpc-604-linux-gnu/buildtools --with-mpfr=/home/aservadio/SVN_TMP/UEIPAC/cross-compiler/ueipac-gcc/targets/powerpc-604-linux-gnu/buildtools --with-mpc=/home/aservadio/SVN_TMP/UEIPAC/cross-compiler/ueipac-gcc/targets/powerpc-604-linux-gnu/buildtools --with-isl=no --with-cloog=no --enable-lto --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --enable-threads=posix --disable-plugin --disable-nls --disable-multilib --with-local-prefix=/home/aservadio/x-tools/powerpc-604-linux-gnu/powerpc-604-linux-gnu/sysroot --enable-long-long
Thread model: posix
gcc version 6.3.0 (crosstool-NG crosstool-ng-1.23.0)
 
### What did you do?
Attempting to cross-compile for a powerpc 604 cpu. 

used:
export GRPC_CROSS_COMPILE=true
export GRPC_CROSS_LDOPTS="-L/cross/compile/dir/lib -L/cross/compile/dir/powerpc-604-linux-gnu/powerpc-604-linux-gnu/lib -L/cross/compile/dir/powerpc/lib"
export UEIPACROOT="/some/location/ueipac-4.0.2"
CROSS_COMPILE=powerpc-604-linux-gnu

make HAS_PKG_CONFIG=false \
     CC=${CROSS_COMPILE}-cc \
     CXX=${CROSS_COMPILE}-c++ \
     RANLIB=${CROSS_COMPILE}-ranlib \
     LD=${CROSS_COMPILE}-ld \
     LDXX=${CROSS_COMPILE}-c++ \
     AR=${CROSS_COMPILE}-ar \
     PROTOBUF_CONFIG_OPTS="--host=powerpc-604-linux --with-protoc=/usr/local/bin/protoc" \
     GRPC_CROSS_AROPTS="rc --target=elf32-powerpc" \
     EMBED_OPENSSL=/home/user/repos/grpc/third_party/openssl-1.1.1a

Cross-compiled openssl successfully 
removed -Wall (as got some error: src/core/lib/iomgr/tcp_posix.cc:526:61: error: dereferencing type-punned pointer will break strict-aliasing rules) 
set prefixes to match where i wanted stuff in the Makefile, and had to force protoc to use my host's bin in the make file (even though I told it in the PROTOBUF_CONFIG_OPTS where to look)

### What did you expect to see?
 
successful complication....
everything compiles fine when I did a standard make for the host machine. 
 
### What did you see instead?

After forcing the location of protoc I get:
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/channelz/channelz.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/health/v1/health.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/health/v1/health.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/echo_messages.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/testing/echo_messages.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/simple_messages.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/echo.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/testing/simple_messages.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/testing/echo.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/duplicate/echo_duplicate.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/testing/duplicate/echo_duplicate.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/core/stats.proto
[CXX]     Compiling /home/user/repos/grpc/gens/src/proto/grpc/core/stats.pb.cc
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/core/stats.proto
[CXX]     Compiling /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc
In file included from /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc:6:0:
/home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.h:43:7: error: using typedef-name 'grpc::CompletionQueue' after 'class'
 class CompletionQueue;
       ^~~~~~~~~~~~~~~
In file included from include/grpcpp/impl/codegen/call_op_set.h:35:0,
                 from include/grpcpp/impl/codegen/server_context.h:29,
                 from include/grpcpp/impl/codegen/async_stream.h:25,
                 from include/grpcpp/impl/codegen/async_generic_service.h:22,
                 from /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.h:25,
                 from /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc:6:
include/grpcpp/impl/codegen/completion_queue.h:26:38: note: 'grpc::CompletionQueue' has a previous declaration here
 typedef ::grpc_impl::CompletionQueue CompletionQueue;
                                      ^~~~~~~~~~~~~~~
In file included from /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc:6:0:
/home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.h:45:7: error: using typedef-name 'grpc::ServerCompletionQueue' after 'class'
 class ServerCompletionQueue;
       ^~~~~~~~~~~~~~~~~~~~~
In file included from include/grpcpp/impl/codegen/call_op_set.h:35:0,
                 from include/grpcpp/impl/codegen/server_context.h:29,
                 from include/grpcpp/impl/codegen/async_stream.h:25,
                 from include/grpcpp/impl/codegen/async_generic_service.h:22,
                 from /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.h:25,
                 from /home/user/repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc:6:
include/grpcpp/impl/codegen/completion_queue.h:27:44: note: 'grpc::ServerCompletionQueue' has a previous declaration here
 typedef ::grpc_impl::ServerCompletionQueue ServerCompletionQueue;
                                            ^~~~~~~~~~~~~~~~~~~~~
Makefile:2975: recipe for target 'repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.o' failed
make: *** [repos/grpc/gens/src/proto/grpc/core/stats.grpc.pb.o] Error 1 

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by mehrdada** [comment]
I suspect you are using a different version of protoc/gRPC C++ protoc plugin to generate stubs from `.proto` files than the gRPC version you are trying to compile.

**Comment by a11r** [comment]
Thanks @mehrdada for the suggestion. Closing the issue. Please reopen if any action is needed.
