### ISSUE TITLE
many TIMEOUT occurs on linux testing

### ISSUE THREAD

**Issue by OceanOfWest** [grpc/grpc#19303]
### What version of gRPC and what language are you using?
v1.21.2
 
### What operating system (Linux, Windows,...) and version?
 Linux 4.4.0 (Ubuntu 5.4.0)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 5.4.0
python 2.7.12
 
### What did you do?
git clone https://github.com/grpc/grpc.git
cd grpc
git submodule update --init
make
tools/run_tests/run_tests.py -l c -x report.xml
 
### What did you expect to see?
 all tests pass
 
### What did you see instead?
lost of testcases failed,  part of log:
D0609 17:30:38.986865214    6581 test_config.cc:384]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0609 17:30:38.987097576    6581 ev_epoll1_linux.cc:116]     grpc epoll fd: 3
D0609 17:30:38.987110403    6581 ev_posix.cc:174]            Using polling engine: epoll1
D0609 17:30:38.987151354    6581 dns_resolver_ares.cc:483]   Using ares dns resolver
D0609 17:30:38.990410023    6581 tcp_posix.cc:1256]          cannot set inq fd=5 errno=92
TIMEOUT: bins/opt/h2_census_test max_connection_age GRPC_POLL_STRATEGY=epoll1 [pid=6581, time=301.1sec]
 
D0609 17:30:38.997006487    6595 test_config.cc:384]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0609 17:30:38.997242944    6595 ev_epoll1_linux.cc:116]     grpc epoll fd: 3
D0609 17:30:38.997255036    6595 ev_posix.cc:174]            Using polling engine: epoll1
D0609 17:30:38.997301416    6595 dns_resolver_ares.cc:483]   Using ares dns resolver
I0609 17:30:38.997343417    6595 server_finishes_request.cc:39] Running test: test_invoke_simple_request/chttp2/simple_ssl_fullstack
D0609 17:30:39.000060806    6595 tcp_posix.cc:1256]          cannot set inq fd=5 errno=92
TIMEOUT: bins/opt/h2_ssl_cred_reload_test server_finishes_request GRPC_POLL_STRATEGY=epoll1 [pid=6595, time=301.0sec]
WAITING: 12 jobs running, 194 complete, 71 failed (load 3.90) next: bins/opt/api_fuzzer_one_entry test/core/end2end/fuzzers/api_fuzzer_corpus/ef63ab3c4dbf27ed1f15c2b310bf41ff3a2a7e3c GRPC_POLL_STRATEGY=none 
 
### Anything else we should know about your project / environment?
I have installed the pre-requisites specified in BUIDING.md & prepare_build_linux_rc & prepare_build_linux_perf_rc.
is there some other dependencies or system config need to be set beforehand?

**Comment by lidizheng** [comment]
Can you try to run one of the timeout test cases, and enable the trace logging? You can simply specify two environment variables: `GRPC_TRACE=all` and `GRPC_VERBOSITY=debug`.

Add a data point: I just tried on macOS, and the test passed.

**Comment by OceanOfWest** [comment]
thanks for response, I try to run a single testcase, but it is blocking for a long time(20+min):
tools/run_tests/start_port_server.py
2019-06-11 16:40:05,951 detected port server running version 20
2019-06-11 16:40:05,985 my port server is version 20
Port server started successfully
root@dggphicprc07936:/home/wei/grpc# bins/opt/h2_compress_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 GRPC_TRACE=all GRPC_VERBOSITY=debug
D0611 16:40:07.785003972    8356 test_config.cc:384]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1

**Comment by OceanOfWest** [comment]
I try gdb bins/opt/h2_compress_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 ,
and seems the test is blocked in the loop: port_server_client.cc:233,

### stack back trace:
```
Thread 1 "h2_compress_nos" hit Breakpoint 16, grpc_tcp_create (em_fd=em_fd@entry=0x79ad80, channel_args=<optimized out>, peer_string=<optimized out>) at src/core/lib/iomgr/tcp_posix.cc:1256
1256        gpr_log(GPR_DEBUG, "cannot set inq fd=%d errno=%d", tcp->fd, errno);
(gdb) bt
#0  grpc_tcp_create (em_fd=em_fd@entry=0x79ad80, channel_args=<optimized out>, peer_string=<optimized out>) at src/core/lib/iomgr/tcp_posix.cc:1256
#1  0x0000000000452905 in grpc_tcp_client_create_from_fd (fd=fd@entry=0x79ad80, channel_args=<optimized out>, addr_str=<optimized out>) at src/core/lib/iomgr/tcp_client_posix.cc:133
#2  0x0000000000452b45 in on_writable (acp=0x788430, error=<optimized out>) at src/core/lib/iomgr/tcp_client_posix.cc:183
#3  0x000000000044dc01 in exec_ctx_run (error=0x0, closure=<optimized out>) at src/core/lib/iomgr/exec_ctx.cc:40
#4  grpc_core::ExecCtx::Flush (this=0x7fffffffddf0) at src/core/lib/iomgr/exec_ctx.cc:148
#5  0x0000000000491df0 in end_worker (worker_hdl=<optimized out>, worker=0x7fffffffd900, pollset=0x7866d0) at src/core/lib/iomgr/ev_epoll1_linux.cc:954
#6  pollset_work (ps=0x7866d0, worker_hdl=<optimized out>, deadline=<optimized out>) at src/core/lib/iomgr/ev_epoll1_linux.cc:1054
#7  0x00000000004436ae in grpc_pick_port_using_server () at test/core/util/port_server_client.cc:233
#8  0x0000000000442836 in grpc_pick_unused_port_impl () at test/core/util/port.cc:84
#9  0x00000000004429d9 in grpc_pick_unused_port_or_die_impl () at test/core/util/port.cc:93
#10 0x0000000000406ecc in chttp2_create_fixture_fullstack_compression (client_args=client_args@entry=0x0, server_args=server_args@entry=0x0) at test/core/end2end/fixtures/h2_compress.cc:48
#11 0x0000000000418480 in begin_test (test_name=0x5061c1 "filter_status_code", client_args=0x0, server_args=0x0, config=...) at test/core/end2end/tests/filter_status_code.cc:63
#12 test_request (config=...) at test/core/end2end/tests/filter_status_code.cc:116
#13 0x0000000000418cb9 in filter_status_code (config=...) at test/core/end2end/tests/filter_status_code.cc:398
#14 0x0000000000408ca9 in grpc_end2end_tests (argc=argc@entry=5, argv=argv@entry=0x7fffffffe508, config=...) at test/core/end2end/end2end_nosec_tests.cc:446
#15 0x0000000000403261 in main (argc=5, argv=0x7fffffffe508) at test/core/end2end/fixtures/h2_compress.cc:127
(gdb) ```

**Comment by lidizheng** [comment]
It seems the test is blocked because it failed to obtain an useable port.

I would suggest:
1) Reset firewall/networking settings or check if anything prevent you from either get a port or communicate through local socket;
2) Try to use higher permission to run the test.

Also, does your environment support IPv6?

```C
while (pr.port == -1) {
      grpc_pollset_worker* worker = nullptr;
      if (!GRPC_LOG_IF_ERROR( .  // <- Line:233
              "pollset_work",
              grpc_pollset_work(
                  grpc_polling_entity_pollset(&pr.pops), &worker,
                  grpc_core::ExecCtx::Get()->Now() + GPR_MS_PER_SEC))) {
        pr.port = 0;
      }
}
```

**Comment by gnossen** [comment]
I'd also suggest using the `--use_docker` flag. That will cause the tests to run in a network namespace, so the port exhaustion should stop.

**Comment by OceanOfWest** [comment]
@lidizheng ,IPV6 is supported, and I try to close the firewall, it doesn't work however, still testing other settings. 0-0
@gnossen , thanks, I will try it.

**Comment by lidizheng** [comment]
@nicolasnoble Have you seen this problem occurred to C-Core before?
