### ISSUE TITLE
1.21.0 breaks the build for iOS

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc#19301]
@muxi: I believe that may concern you.

I build gRPC and its deps from source, using CMake, with [this simple repo (branch: ios)](https://github.com/JonasVautherin/grpc-build/tree/ios). Note that I apply [a patch](https://github.com/JonasVautherin/grpc-build/blob/ios/grpc/grpc_ios.patch) to gRPC, that I think is not relevant to this issue (I will open a PR with that patch, btw).

Building 1.20.0 is fine, using the following command:

```
cmake -DCMAKE_TOOLCHAIN_FILE=tools/ios.toolchain.cmake -Bbuild/ios -S.
```

Now, building 1.21.0 fails with the following error

```
Scanning dependencies of target grpc++
[ 77%] Linking C executable grpc_create_jwt.app/grpc_create_jwt
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
[ 77%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/insecure_credentials.cc.o
Undefined symbols for architecture armv7:
  "operator delete(void*)", referenced from:
      CFStreamHandle::Unref(char const*, int, char const*) in libgrpc.a(cfstream_handle.cc.o)
  "operator new(unsigned long)", referenced from:
      CFStreamHandle::CreateStreamHandle(__CFReadStream*, __CFWriteStream*) in libgrpc.a(cfstream_handle.cc.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [grpc_verify_jwt.app/grpc_verify_jwt] Error 1
make[4]: *** [CMakeFiles/grpc_verify_jwt.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
Undefined symbols for architecture armv7:
  "operator delete(void*)", referenced from:
      CFStreamHandle::Unref(char const*, int, char const*) in libgrpc.a(cfstream_handle.cc.o)
  "operator new(unsigned long)", referenced from:
      CFStreamHandle::CreateStreamHandle(__CFReadStream*, __CFWriteStream*) in libgrpc.a(cfstream_handle.cc.o)
```

Am I doing something wrong, or is that a bug in gRPC?

This can be easily reproduced by:

1. Cloning my repo (note: you want the "ios" branch):
```
    git clone -b ios https://github.com/jonasvautherin/grpc-build
```

2. Building 1.20.0 to convince yourself it works:
```
    cmake -DCMAKE_TOOLCHAIN_FILE=tools/ios.toolchain.cmake -Bbuild/ios_1.20.0 -S.
```

3. Changing [grpc/CMakeLists.txt](https://github.com/JonasVautherin/grpc-build/blob/ios/grpc/CMakeLists.txt#L40) to point to 1.21.0 instead of 1.20.0, and build that to see the error:
```
    cmake -DCMAKE_TOOLCHAIN_FILE=tools/ios.toolchain.cmake -Bbuild/ios_1.21.0 -S.
```

Note: there is a [bug in CMake](https://gitlab.kitware.com/cmake/cmake/issues/19282) for the current version distributed on Homebrew. You can either use the `pip`-provided cmake or the CMake nightly build.

**Comment by muxi** [comment]
@JonasVautherin - thanks for reporting the issue. I agree that including CMake iOS toolchain into our supported list might be of interest. I am a bit confused by the PR you submitted though; just to be clear: if I understand correctly your PR triggered this error rather than fixed this error, right?

In the mean time if you find a solution to the problem we would very appreciate contribution to the project. The error messages itself looks like the build chain did not include the standard c++ library when linking. I have not looked into detail yet but it could be as simple as adding a flag such as `-stdlib=libc++`.

**Comment by JonasVautherin** [comment]
> if I understand correctly your PR triggered this error rather than fixed this error, right?

Right, sorry for the confusion.

With recent iOS toolchains, the build fails because `CMAKE_SYSTEM_NAME` is now "iOS" instead of "Darwin". That is what my PR is aiming to solve. I did not open an issue for that because I had a fix already (hence the PR).

Once I fix the issue that my PR solves, then I see that 1.21.0+ fail to build, where 1.20.0 pass. Hence this issue.

> The error messages itself looks like the build chain did not include the standard c++ library when linking.

Assuming it is a toolchain issue, does it make sense that 1.20.0 builds, and 1.21.0 doesn't?

**Comment by muxi** [comment]
hm that is right. I think I probably know what's wrong and I'll try a fix for it.

**Comment by JonasVautherin** [comment]
Thanks a lot @muxi!
