### ISSUE TITLE
GRPC_CSHARP Bug - Migration From Google AdWords To Google Ads

### ISSUE THREAD

**Issue by tanveerhamidpolyvista1** [grpc/grpc#19307]
I want to upgrade from Google Adwords to Google Ads.

I am facing GPRC_CSharp error after installing Google.Ads.GoogleAds nuget package in my C#.net MVC project.

When I install this package in a new C# project it works perfect, but when I add Google.Ads.GoogleAds nuget package in my C#.Net MVC web project (it already has Google AdWords and Google Analytics nuget packages installed) I get the following error in my library project (this library project works fine when referenced in a new project).

Error Detail:

```
Error loading native library. Not found in any of the possible locations: D:\ProductSuite\IPDFWithGoogleAnalytics_Production_AdsAPI\CurrentDev\Source\UI\Public\PolyVista.IPDFGA.Web\bin\grpc_csharp_ext.x64.dll,D:\ProductSuite\IPDFWithGoogleAnalytics_Production_AdsAPI\CurrentDev\Source\UI\Public\PolyVista.IPDFGA.Web\bin\runtimes/win/native\grpc_csharp_ext.x64.dll,D:\ProductSuite\IPDFWithGoogleAnalytics_Production_AdsAPI\CurrentDev\Source\UI\Public\PolyVista.IPDFGA.Web\bin../..\runtimes/win/native\grpc_csharp_ext.x64.dll
```

My C#.Net MVC project is compiled in .NET Framework 4.5.2.

Please help me in fixing this issue. It's urgent ?

**Comment by jtattermusch** [comment]
Looks like something went wrong with copying the grpc_csharp_ext.x64.dll to your build output directory? (this should happen automatically upon build for .NET Framework 4.5 projects).

Here's the code that looks for the location of grpc_csharp_ext.x64.dll
https://github.com/grpc/grpc/blob/cc0653207ac681cbfe645d9f22415a409eed47f9/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L83

**Comment by tanveerhamidpolyvista1** [comment]
I faced the following error when I added this class in App_Start folder of my MVC application.

Error: "NativeMethods is inaccessible due to ites protection level"

You can see the error in attachment as well.
![NativeMethodError](https://user-images.githubusercontent.com/50982173/59444584-95cad200-8e17-11e9-8869-4448915b4794.png)

**Comment by jtattermusch** [comment]
@tanveerhamidpolyvista1  the point wasn't for you to add the NativeExtension.cs file into your application, but to give a pointer how does the grpc_csharp_ext.x64.dll loading logic work - perhaps from looking at the source code (it's actually pretty simple, only a few if statements), you'll be able to see what exactly is it that's failing in your setup.

**Comment by jtattermusch** [comment]
@tanveerhamidpolyvista1  have you managed to resolve the problem?
