### ISSUE TITLE
Cannot build gRPCTargets.cmake on Windows

### ISSUE THREAD

**Issue by angelinatquach** [grpc/grpc#19323]
**System**
Windows 10, x64
C++/cmake project

**Dependencies**
Downloaded all dependencies (Go, Yasm, ActivePerl, CMake, Git, Visual Studio 2015)
ran commands found in (https://github.com/grpc/grpc/blob/master/BUILDING.md)

> powershell git clone --recursive -b ((New-Object System.Net.WebClient).DownloadString(\"https://grpc.io/release\").Trim()) https://github.com/grpc/grpc
> cd grpc
>git submodule update --init
> md .build
> cd .build
> call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x64
> cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
> cmake --build .
> Ninja install

After this did not work, I ran grpc/test/distrib/cpp/run_distrib_test_cmake.bat. This also failed with the call cmake -DCMAKE_INSTALL_PREFIX=C:/OPSWAT/grpc/testinstall -DOPENSSL_ROOT_DIR=C:/OPSWAT/grpc/OpenSSL-Win32 -DZLIB_ROOT=C:/OPSWAT/grpc/testinstall ../..   || goto :error

The same error result followed.

**Expected Result**
Be able to build my own C++ project with find_package(gRPC CONFIG) to use gRPC dependency.

**Actual Result**
CMake Error at C:/grpc/.build/gRPCConfig.cmake:8 (include):
  include could not find load file:

    C:/grpc/.build/gRPCTargets.cmake

**Comment by ssamira** [comment]
I have the exact same problem. Did you get it working?
