### ISSUE TITLE
Set MaxInboundMetadataSize in Ruby

### ISSUE THREAD

**Issue by mcloonan** [grpc/grpc#19337]
### What version of gRPC and what language are you using?
Ruby 1.20, but we will definitely update to a new version for this functionality

The Google Ads API sometimes returns metadata headers greater than the default max size, so we need a mechanism to set the MaxInboundMetadataSize in Ruby. It doesn't look like it's possible to set right now.

**Comment by apolcyn** [comment]
We do have the `grpc.max_metadata_size` channel arg, which corresponds to the `HTTP/2 MAX_HEADER_LIST_SIZE` (see https://tools.ietf.org/html/rfc7540#section-6.5.2).

See code snippet for example usage in ruby:

```
stub = Helloworld::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure, channel_args: {'grpc.max_metadata_size': 1000})
```

See https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L265 for documentation on that option. Also see https://groups.google.com/forum/#!topic/grpc-io/FoLNUJVN4o4 for Q/A on that option.

That said, re:

> sometimes returns metadata headers greater than the default max size

Can you describe a bit more details of what's happening here? E.g., what is the status code and message details when this happens? Also, do you have an estimate of the size or metadata that you need to support?

**Comment by AnashOommen** [comment]
We are going with 16MB for all Google Ads API libraries for now.
