### ISSUE TITLE
gRpc C#- Server with SslServerCredentials - Failed to bind port "127.0.0.1:50051"

### ISSUE THREAD

**Issue by Gooner** [grpc/grpc#19352]
I am getting the following error while trying to create gRpc server with SSL.

Unhandled Exception: System.IO.IOException: Failed to bind port "127.0.0.1:50051"
   at Grpc.Core.Server.CheckPortsBoundSuccessfully() in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 313
   at Grpc.Core.Server.Start() in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 155

gRpc version: 1.21.0
OS: Windows 10 1803
Dotnet Core 2.2

server core 

`          var server = new Server
            {
                Services = {MessageBrokerV3Service.BindService(new MockBrokerV3ServiceImpl())},
                Ports = { new ServerPort("127.0.0.1", 50051, new SslServerCredentials(new []
                {
                    new KeyCertificatePair(certificateChain, privateKey), 
                })) }
            };
            server.Start();`

**Comment by jtattermusch** [comment]
My guess is that this doesn't seem to have to do anything with the fact you're using SSL. It just seems that the port is already bound by some other server. Have you tired binding another port?

You can get more logs by following https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by jtattermusch** [comment]
I'll reopen if the problem persists.
