### ISSUE TITLE
Python: Handling Stream Error <class 'grpc._channel._Rendezvous'>

### ISSUE THREAD

**Issue by neliel123** [grpc/grpc#19367]
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 I have this simple streaming service...wherein I used oneof to signify the presence of an error or none.

// sample service
rpc getInfo(Request) returns (stream Response) {}

```
message Request {
}

message Response {
       oneof statusResponse {
               Result result = 1;
               Error error = 2;
       }
}

message Result {
       string data = 1;
}

message Error {
       string message = 1;
	   int32 code = 2
}
```

And in my service I specifically set the error..

```
def getInfo(self, request, context):
    return info_pb2.Response(
                error=info_pb2.Error(
                code=1234,
                message="Sample Error"))
```

Now, In a sample test case..I wanted to extract the data by using HasField on the messages				
				
```
def test_existing_info(self):
    request = info_pb2.Request()

    response = self.stub.getInfo(request)
    print(type(response))
	

	self.assertFalse(response.HasField('result'))
    self.assertTrue(response.HasField('error '))
```
	
but it looks like the data type is like this **<class 'grpc._channel._Rendezvous'>**

In my debugger, I noticed that the
	`response._state.code = StatusCode.OK`
	
so which means that I am setting the correct exception.  How do you handle streaming exception when using oneof?  How can I test the response object?
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by lidizheng** [comment]
@neliel123 You can find the answers of your question in [example code](https://github.com/grpc/grpc/tree/master/examples/python) and [tutorial](https://grpc.io/docs/tutorials/basic/python/). Here, I will try to give a short answer. 

The first thing I noticed in your code is that you maybe confused about the types:

1) Your server method implementation should use `yield` semantic to make it returns a generator.
2) The returned type is a generator that will yield your proto message. Here're some example usage:

```Python
response_iterator = self.stub.getInfo(request)
response = next(response_iterator)
print(type(response))
```

```Python
response_iterator = self.stub.getInfo(request)
for response in response_iterator:
    print(response)
```

Secondly, if you want to return error, I would suggest either use our `abort` semantic or `abort_with_status` for more complex error message ([example](https://github.com/grpc/grpc/tree/master/examples/python/errors)). A short example will be:

```Python
# On the server-side
class FooServicer():
    def getInfo(self, request, context):
        if not bar_validation(request):
            context.abort(
                code=grpc.StatusCode.INVALID_ARGUMENT,
                details='Bar validation failed!'
            )
        else:
            # Your logic to yield multiple response
```

```Python
# On the client-side
try:
    response_iterator = self.stub.getInfo(request)
except grpc.RpcError as rpc_error:
    print(f'RPC failed with code {rpc_error.code()}: {rpc_error}')
```

Does this answer your question?

**Comment by neliel123** [comment]
Hi, thank you for your comments and the links you have provided..

I think I did not explain myself well.. Imagine I have this service that retrieves list of books from another service.

So if we receive a list of books then we can just stream the result back by using yield


```
def getBooks(self, request, context):
	# IF Book Server is Up and we receive a book list
		books = list() #Assuming there is a list of book
		response = info_pb2.Response()
		for book in books
			response.result.data = book
			yield response
	#ELSE
		# If an exception occurs like the Book Server is down then we return a response
		return info_pb2.Response(
					error=info_pb2.Error(
					code=1234,
					message="Unable to connect to the book server"))
```
				
However in extreme cases, if the book server is down or if a book is not present then I can use the oneof right?
I think this is how protobuf message was envisioned for oneof correct?

So in my test case, I wanted to know how can I capture the return of the response object and validate it

**Comment by lidizheng** [comment]
The return value of the method on stub is a generator of your response object. You can get your response object by iterating it.

The oneof of proto message usage can be found at ProtoBuf's documentation: https://developers.google.com/protocol-buffers/docs/reference/python-generated#oneof

In short, you can check the value by invoking `HasField`.

**Comment by neliel123** [comment]
Hi,
That is where I really am confused about..because even if I iterate the response, there is nothing there.

The return code of the response is statuscode.OK though which is weird but there is no object to iterate.

**Comment by lidizheng** [comment]
On the server side, as I suggested in my first comment, should use `yield` or return a Python generator. However, according to your code, you are returning a proto message directly. If you turn on the Python logging on server-side, you should see exception being raised there.

**Comment by ArjunBansil** [comment]
I am trying to unit test my project that has a similar issue. I'm trying to send a unary request to a stream request (for the sake of creating an error) and I am unable to error handle it from the server. Is there anyway to handle that kind of error? 
Below is my code if it helps: 
//Gets a stream of inputs and sends 8 words in a stream
    def stream_stream_prediction(self, request_iterator, context):
        print("Stream-Stream Prediction")
        if request_iterator is None:
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details("Sent a unary request, was expecting a stream")
            return PredictReply()
        if not self.is_iterable(request_iterator):
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details("Sent a unary request, was expecting a stream")
            return PredictReply()
        words = self.predictor.predict_completions(None, 5)
        for word in words:
            yield PredictReply(word1=word)

**Comment by neliel123** [comment]
> On the server side, as I suggested in my first comment, should use yield or return a Python generator. However, according to your code, you are returning a proto message directly. If you turn on the Python logging on server-side, you should see exception being raised there.

That is my mistake.... combining yield and return.  
Thank you very much as I am able to retrieve my error response.
