### ISSUE TITLE
CFI cast violations in InlinedVector

### ISSUE THREAD

**Issue by equinox1993** [grpc/grpc#19375]
### What version of gRPC and what language are you using?

gRPC++ @ b245ad4ae810ed6bc13378421edfd3986a8ffac3

### What operating system (Linux, Windows,...) and version?

Linux/ChromeOS

0.0.0 Linux 4.4.180-16533-g77dd0cb94c17 #1 SMP PREEMPT Wed May 29 14:05:13 PDT 2019 x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)

clang version 9.0.0 (https://github.com/llvm/llvm-project/ 80fee25776c2fb61e74c1ecb1a523375c2500b69)
Target: x86_64-unknown-linux-gnu
Thread model: posix

### What did you do?

grpc_core::InlinedVector has a few static_cast's/reinterpret_cast's that seem benign but will trigger clang's CFI (control flow integrity) cast check.

For example `inline_` is created uninitialized, then when caller calls `emplace_back()`, it calls `data()` to get back the pointer to initialize, then it runs a placement-new operator on it to initialize the element. The issue is that when `data()` is called, it tries to reinterpret_cast `inline_` to `T*` before `inline_` gets initialized, which doesn't have the right VMT pointer to pass the CFI cast check, and thus crashes the app with a SIGILL signal.

https://github.com/grpc/grpc/blob/7dcdabf593f4d9b8d78721e5c5e78e704eb2e2a9/src/core/lib/gprpp/inlined_vector.h#L83

The `reserve()` method has similar issue.

I guess the right fix is to prevent prematurely casting `inline_` or `dynamic_` to `T*` before they are initialized, and always pass the generic (void*) pointer to placement-new instead. Given that these casts look kind of benign, it might be fine to just suppress CFI cast checking on this class.

### Context

http://crbug.com/972108 (need to sign in with a @google.com account)

**Comment by equinox1993** [comment]
Per pcc@'s discussion doing placement new with a void* pointer is the correct fix. I'm happy to make that change.

**Comment by AspirinSJL** [comment]
Please open a PR to propose your change, thanks!

**Comment by equinox1993** [comment]
Sorry I'm busy working on some other stuff right now. Feel free to take it if you like to work on this :)

**Comment by nico** [comment]
This is still a problem, and we have a CFI suppression for this in Chromium. Could someone reopen this?
