### ISSUE TITLE
Add continuous opt runs

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1938]
run_tests -n inf -f -c opt -l all
with errors flagged

This should be run continuously on whatever is at head on master.

**Comment by nathanielmanistaatgoogle** [comment]
This has a lot of language labels on it and also has "FOR DISCUSSION". What is to be done by each language for this issue, and what is to be discussed?

**Comment by ctiller** [comment]
FOR DISCUSSION was a label we used during a meeting a few weeks ago when deciding whether to include something in Beta or not. It looks like we didn't get to this one, but I suspect the impact it'll make to our beta milestone is inconsequential at this point. Moving to GA unless someone feels strongly otherwise.

**Comment by ctiller** [comment]
(lots of wrapped languages because the point of this is to help out all the implementations by shaking out flakes earlier and faster)

**Comment by ctiller** [comment]
(meaning there's probably little if anything for wrapped language folks to actually do)

**Comment by murgatroid99** [comment]
We seem to have this now. Is this OK to close?

**Comment by murgatroid99** [comment]
OK, I think this is resolved with the current Jenkins master build. If someone thinks there is still work to be done here, they can reopen it.
