### ISSUE TITLE
how to install grpc prerequisites  in centos?

### ISSUE THREAD

**Issue by namjitharavind** [grpc/grpc#19398]
These are for ubuntu, can i install this for centos
Pre-requisites
Linux
 $ [sudo] apt-get install build-essential autoconf libtool pkg-config
If you plan to build from source and run tests, install the following as well:

 $ [sudo] apt-get install libgflags-dev libgtest-dev
 $ [sudo] apt-get install clang libc++-dev

**Comment by weiyongji** [comment]
maybe you can try: yum install xxx
