### ISSUE TITLE
building grpc with multiple protoc/protobuf versions

### ISSUE THREAD

**Issue by fischeru** [grpc/grpc#19399]
### What version of gRPC and what language are you using?
1.22 
 
### What operating system (Linux, Windows,...) and version?
Linux 9.9 stretch 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
6.3.0 
 
### What did you do?
I followed the instruction for compiling grpc from source using make: https://chromium.googlesource.com/external/github.com/grpc/grpc/+/v1.11.1/INSTALL.md
 
### What did you expect to see?
No error 
 
### What did you see instead?
When I run make I get an error when linking the grpc_*_plugins:

/usr/bin/ld: warning: libprotobuf.so.17, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
/usr/bin/ld: warning: libprotobuf.so.17, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
/usr/bin/ld: /data1/fischeru/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): undefined reference to symbol '_ZNK6google8protobuf16MethodDescriptor11output_typeEv'
//usr/local/lib/libprotobuf.so.17: error adding symbols: DSO missing from command line

### Anything else we should know about your project / environment?
By default I have libprotobuf.so.10 and protoc 3.0 under /usr/lib and /urs/bin installed. I do not want to uninstall these, since gnome depends on those.
In /usr/local I have protoc 3.6 and libprotobuf.so.17.
From what I understand somewhere in the build process both protobuf versions are mixed. I do not want to be restricted to protobuf 3.0 just because its installed by default on my pc. 

I've seen the same issue at https://github.com/grpc/grpc/issues/9549, but the one suggestion does not work. The discussion seemed to reach the conclusion that its bad behaviour, but nobody cares. I disagree.

**Comment by magnanta** [comment]
[grpc_error.log](https://github.com/grpc/grpc/files/3446273/grpc_error.log)
I am also getting similar kind of issue do u know the solution.I know that i had multiple protobuff versions.
