### ISSUE TITLE
import cygrpc into staticaly compiled python runtime

### ISSUE THREAD

**Issue by Sythanis** [grpc/grpc#19402]
### What version of gRPC and what language are you using?
 Using Bazel 0.27 with python_rules and rules_proto
 
### What operating system (Linux, Windows,...) and version?
 Arch Linux fully updated on 19/6/2019
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Statically build Python 3.6.8
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I have a bazel monorepo with checked in python run time that was statically compiled. I use rules_python to install python dependencies. 

`grpcio`  version 1.20.0 has been installed as `rules_proto` use that version as well. 

in `BUILD` file dependency on grpcio was declared
```
    deps = [
    ...,
    requirement("grpcio"),
    ....,
    ],
```
to the python file import statement has been added
```import grpc```
 
### What did you expect to see?
 `grpc` library should be able to be imported without an error
 
### What did you see instead?
```
Traceback (most recent call last):
  File "/home/user/test/services/classification_service/tests/acceptance/ServiceControlLib.py", line 4, in <module>
    import grpc
  File "/home/user/.cache/bazel/_bazel_urban/228edeacaae981c311aebaa15063220d/sandbox/linux-sandbox/569/execroot/__main__/bazel-out/k8-fastbuild/bin/services/classi
fication_service/classification_service_acceptnace.runfiles/pypi__grpcio_1_20_0/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
PYTHONPATH:
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
I have located a folder called `_cygrpc` in the cache of the `pypi__grpcio_1_20_1`. Hard chaining the import from `import cygrpc as _cygrpc` to `import _cygrpc` fails with missing symbol error.

Also switching to platform python makes the import work

On demand I can provide `Modules/Setup` file used for python static compile.

**Comment by gnossen** [comment]
@SythanisCan Any chance you can link to your project so we can reproduce?

**Comment by Sythanis** [comment]
@gnossen  thank you for a fast reply. I cannot share the codebase as it is proprietary, but will try to generate a minimal example throughout the day. Will get back to you soon.

**Comment by joekewl70** [comment]
Can you break it down for me? I should have money lots.....right?

**Comment by gnossen** [comment]
@Sythanis Were you able to get a minimal example together?

**Comment by joekewl70** [comment]
I can send you a screenshot I guess

**Comment by joekewl70** [comment]
Here are a couple of screenshots I am jojodeco 2 and joekewl70

**Comment by joekewl70** [comment]
I don't know how to work it from there

**Comment by joekewl70** [comment]
Google





Joe Hebert (Joseph Hebert)


Joe Hebert (Joseph Hebert)

I shared a list with you






View on Google Maps




Google

© 2018 Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043

Sent by Joe Hebert (Joseph Hebert) via Google Maps
