### ISSUE TITLE
Labeling iomgr objects makes C# tests crash

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1940]
#1856 seems to make C# tests crash
tools/run_tests/run_tests.py -l csharp

This commit has C# tests already broken
https://github.com/grpc/grpc/commit/19fdb33da268b4ded64c64bd7bde7b75714ab0a0

With its parent, C# tests pass
https://github.com/grpc/grpc/commit/206e6e844140a3a477d65767d4a92e19d9893e56

Unfortunately, this is also part of the 0.9.1 release. I haven't released the NuGet packages yet though - I was testing manually that everything works and that's how I discovered this one.
Because all of C# alpha users are using NuGet, I don't think we've broken anyone.

**Comment by jtattermusch** [comment]
I am working on getting more details about the crash.

**Comment by jtattermusch** [comment]
p = 0xfeeefeee 

>	grpc_csharp_ext.dll!gpr_free(void * p) Line 47	C
 	grpc_csharp_ext.dll!grpc_iomgr_unregister_object(grpc_iomgr_object * obj) Line 176	C
 	grpc_csharp_ext.dll!do_request(void * rp) Line 139	C
 	grpc_csharp_ext.dll!thread_body(void * v) Line 72	C

**Comment by nicolasnoble** [comment]
Wait, that's wrong. That wasn't supposed to be in the 0.9.1 release.
