### ISSUE TITLE
aclocal: couldn't open directory `m4': No such file or directory

### ISSUE THREAD

**Issue by vnagineni** [grpc/grpc#19418]
Compilation is failing on my box. Can somebody please help me in figuring out the reason.

[vnagineni@suppressless grpc--grpc]$ make all PROTOBUF_CONFIG_OPTS=LDFLAGS="-Wl,-rpath,/home/y/lib64 -L/home/y/lib64 -lrt"
[MAKE]    Generating cache.mk
[AUTOGEN] Preparing protobuf
aclocal: couldn't open directory `m4': No such file or directory
autoreconf: aclocal failed with exit status: 1
make: *** [third_party/protobuf/configure] Error 1

[vnagineni@suppressless grpc--grpc]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)

[vnagineni@suppressless grpc--grpc]$ which gcc
/opt/rh/devtoolset-6/root/usr/bin/gcc

**Comment by karthikravis** [comment]
@vnagineni : Is this still an issue? can you try installing gcc version 8 and then retry?

**Comment by karthikravis** [comment]
Please re-open if still an issue.
