### ISSUE TITLE
Performance issue caused by grpc_core::ExecCtx::Get()->Flush() in pollset_windows.cc

### ISSUE THREAD

**Issue by yingnanl** [grpc/grpc#19417]
### What version of gRPC and what language are you using?
 1.21.0
 
### What operating system (Linux, Windows,...) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 c#
 
### What did you do?
I'm testing grpc on a big environment which contains thousands of machines. 
 
### What did you expect to see?
Request can be sent out ASAP.
 
### What did you see instead?
Sometimes it takes several ms to actually send or receive requests. Per to some traces, it seems requests are blocked by grpc_core::ExecCtx::Get()->Flush() in pollset_windows.cc. For example, re-connect happens in Flush which requires dns lookup. dns lookup itself can takes over 20ms to complete. When this happens, all other workers are blocked. Besides re-connect, it seems send/read also happens in Flush per to traces. Is it possible to remove grpc_core::ExecCtx::Get()->Flush() on line 131 to improve concurrency. In my env, machines are in different regions (although close enough but high latency on higher percentile is expected). It will be great to reduce the bad impact of slow connections.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
let's keep this open.
