### ISSUE TITLE
MacOS Basic Tests C/C++ and Node Time Out

### ISSUE THREAD

**Issue by bigfacebear** [grpc/grpc#19422]
Basic Tests C/C++ MacOS and Basic Tests Node MacOS flakes.
When they fail, I see a bunch of messages saying "file has vanished"

> file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/check_qps_scenario_changes.py"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/check_shellcheck.sh"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/check_submodules.sh"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/check_test_filtering.py"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/check_tracer_sanity.py"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/check_version.py"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/core_banned_functions.py"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/core_untyped_structs.sh"
file has vanished: "/tmpfs/src/github/grpc/workspace_c_macos_opt_native/tools/run_tests/sanity/sanity_tests.yaml"
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1677) [generator=3.1.3]

https://source.cloud.google.com/results/invocations/9b4b867c-54ba-436a-b188-4e281627fe0d/targets
https://source.cloud.google.com/results/invocations/adb1dbdc-5999-4ad0-a2a0-2a6a2a4fb518/targets

**Comment by yashykt** [comment]
similar issue with python tests on macos
https://source.cloud.google.com/results/invocations/a02400a3-cf38-45d9-9819-797d1bfb1e1f/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_python/log

**Comment by gnossen** [comment]
This is actually an error cascading from
```
2019-09-16 16:57:59,751 START: run_tests_python_macos_opt_gevent

ERROR: Aborting VM command due to timeout of 3600 seconds
```

In other words, this just indicates a test timeout.

**Comment by nicolasnoble** [comment]
We've tweaked things, this error shouldn't appear anymore.

**Comment by markdroth** [comment]
Seen again:

https://source.cloud.google.com/results/invocations/b032c4a3-e006-47e2-b5c7-7b864f3e4b25/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp/log

**Comment by jtattermusch** [comment]
dup of https://github.com/grpc/grpc/issues/20694.

**Comment by jtattermusch** [comment]
FTR The logs being flooded with "file has vanished" messages are a consequence of an unrelated issue if a build times out and should be fixed by https://github.com/grpc/grpc/pull/28259.
