### ISSUE TITLE
Improve Error Cases when adding ports to server

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#19431]
The core API specifies that 0 is returned when the library fails to add a port.

```C
/** Add a HTTP2 over plaintext over tcp listener.
    Returns bound port number on success, 0 on failure.
    REQUIRES: server not started */
GRPCAPI int grpc_server_add_insecure_http2_port(grpc_server* server,
                                                const char* addr)
```

Python has this behavior as well. [But it is not documented.](https://grpc.github.io/grpc/python/_modules/grpc.html#Server.add_generic_rpc_handlers) As a result, the most likely outcome for an application that fails to bind a port (e.g. in the case of multiple listeners without `SO_REUSEPORT`), is for the application to continue under the assumption that it is listening properly while it is actually incapable of handling requests.

I think we should do one of the following:
 - Handle the case that the result returned from core is 0 and throw a Python-level exception for it.
 - Improve the documentation to clarify the return value in case of error.

However, depending on how you view things, the first option could be seen as a backwards-incompatible change.

**Comment by gnossen** [comment]
CC @lidizheng

**Comment by lidizheng** [comment]
I personally prefer the later option. My first reason is the same, it might break user. The second reason is that currently we only have one exception class `grpc.RpcError`, it isn't really fit into this scenario semantically.

**Comment by gnossen** [comment]
As noted in the issue description, agree on the compatibility side. However, most of the errors that this would generate would fall firmly under `OSError`, which is built in.

I'll go ahead and put together a PR to clarify the documentation.

**Comment by lidizheng** [comment]
Fixed by https://github.com/grpc/grpc/pull/23632. After all, we picked the first solution.
