### ISSUE TITLE
Can I directly send the "Tensor/Torch/Numpy" data to the remote service?

### ISSUE THREAD

**Issue by YangjieZhou** [grpc/grpc#19443]
Hi,

I am new to the rpc service as well as the grpc and protobuf field. I find that the "protocol buffer" does not have the data type supporting for the "Tensor/Torch/Numpy".

If I want to set up a function of which the paras have the  "Tensor/Torch/Numpy". How can I deal with the "proto" file in the protocol buffer to generate the "xx_pb.py" and "xx_pb_grpc.py"

Could anyone knowing how to achieve it help me? Or am I going in the wrong direction?

Thank you very much!!

**Comment by gnossen** [comment]
Let's start with your question about linear algebra data types.

This is not built in to gRPC or protobufs. However, they provide the necessary ingredients to make this happen. Check out [tensorflow's `tensor.proto` file.](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/framework/tensor.proto) Basically, type information is encoded using standard integer and string types and the content of the tensor is stored as a `bytes` object.

If you go down the path of using, e.g. [numpy's `tobytes` method](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.tobytes.html), you should make sure that whatever byte representation you're using isn't host-dependent.

As for generated code, please check out [the gRPC Basics guide.](https://grpc.io/docs/tutorials/basic/python/)
