### ISSUE TITLE
Request gRPC to be officially supported by CMake

### ISSUE THREAD

**Issue by leimao** [grpc/grpc#19444]
### What version of gRPC and what language are you using?
1.20 C++
 
### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04 LTS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.4.0
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
Hi I am a CMake fan and I would like to see CMake officially support gRPC as it has done for Protobuf. I saw some unofficial cmake files to support finding gRPC in CMake, however, those usually don't have very good documentations. If CMake could officially support gRPC, I would be appreciated.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
gRPC C++ does support cmake and it's one of the recommended ways of building and installing (on some platforms like windows or android the only one).
See https://github.com/grpc/grpc/tree/master/src/cpp#cmake

We are aware that the documentation always needs improvements, we're happy to take suggestions on what exactly is it that's not clear.
