### ISSUE TITLE
Unknown type name 'grpc_slice_refcount_vtable';

### ISSUE THREAD

**Issue by sauravexodus** [grpc/grpc#19461]
### What version of gRPC and what language are you using?
 0.0.9
 
### What operating system (Linux, Windows,...) and version?
 macOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Xcode
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
I am using `FirebaseFirestore` cocoapod from Firebase. gRPC++ is a dependency for FirebaseFirestore and it's not compiling anymore.

**Comment by arjunroy** [comment]
What is the normal compilation process for FirebaseFirestore? (ie. specific commands)

**Comment by sauravexodus** [comment]
Fixed it by deleting the Pods folder and running `pod install` again.
