### ISSUE TITLE
csharp marshaller : emulate legacy serializer via contextual API, or provide ability to specify legacy *and* contextual serializer

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#19470]
Right now when creating a `Marshaller<T>`, you can only specify **either** the legacy **or** contextual serializer. If you use the contextual API, it creates intentionally broken delegates for the legacy API:

``` c#
// gRPC only uses contextual serializer/deserializer internally, so emulating the legacy
// (de)serializer is not necessary.
this.serializer = (msg) => { throw new NotImplementedException(); };
this.deserializer = (payload) => { throw new NotImplementedException(); };
```

This is fine for Grpc.Core, but [breaks if another host wants to use the legacy API](https://github.com/grpc/grpc-dotnet/issues/357) (possibly to avoid the "experimental" API surface).

What would be ideal is if we had another constructor, to allow the configuring code to specify both a contextual *and* legacy API; if the legacy API is omitted, then sure: omit them. By which I mean:

``` c#
public Marshaller(
    Action<T, SerializationContext> serializer,
    Func<DeserializationContext, T> deserializer)
        : this(serializer, deserializer, null, null) {}
public Marshaller(
    Action<T, SerializationContext> contextualSerializer,
    Func<DeserializationContext, T> contextualDeserializer,
    Action<T, SerializationContext> legacySerializer,
    Func<DeserializationContext, T> legacyDeserializer)
{
    this.contextualSerializer = GrpcPreconditions.CheckNotNull(contextualSerializer, nameof(contextualSerializer));
    this.contextualDeserializer = GrpcPreconditions.CheckNotNull(contextualDeserializer, nameof(contextualDeserializer));
    // gRPC only uses contextual serializer/deserializer internally, so emulating the legacy
    // (de)serializer (when they are not provided by the caller) is not necessary.
    this.serializer = legacySerializer ?? ((msg) => { throw new NotImplementedException(); });
    this.deserializer = legacyDeserializer ?? ((payload) => { throw new NotImplementedException(); });
}
```

This would allow callers to supply "best and fallback" implementations, so that it can *at least work* on all hosts, even if it doesn't get the full advantages if the host only *consumes* the legacy API.

Happy to do a PR if it is viable.

**Comment by mgravell** [comment]
Another option of course being to emulate it with a spoof ctx; that should be pretty easy too - happy to help

**Comment by mgravell** [comment]
on reflection, I think emulation is the better option - then there's only one API for the caller to implement either way; added a PR

**Comment by jtattermusch** [comment]
I think the right solution is to switch grpc-dotnet to contextual serialization API which should solve the problems you're seeing
https://github.com/grpc/grpc/pull/19471#issuecomment-508213682
