### ISSUE TITLE
c++ assignment willing to PAY

### ISSUE THREAD

**Issue by bperalta88** [grpc/grpc#19476]
need a assignment done and will pay 15 bucks for anyone who can code this by midnight. Must follow the output .

Assuming there are no deposits other than the original investment, the balance in a savings account after one year may be calculated as,

amount = Principal  * (1 + Rate / T ) T

Principal is the balance in the savings account, Rate is the annual interest rate, and T is the number of times the interest is compounded during a year ( for example, T is 12 if the interest is compounded monthly), amount is the end balance in the savings account, interest is the different of principal from the amount

Write a program that asks for the account number, the full name of the account holder, the principal, the interest rate, and the number of times the interest is compounded. Then display the account information in a table format.

Hint: use setw() and setprecision() to display the output in a table format. All currency should be in two decimal digits. Include <cmath> library to use pow() function to calculate the amount.

Interest = amount - principal;

![Output for Assignment](https://user-images.githubusercontent.com/52253733/60199781-86755c80-97f9-11e9-931b-2b5c4cd6c713.PNG)

**Comment by jtattermusch** [comment]
spam.
