### ISSUE TITLE
csharp new API proposal for the contextual write API

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#19509]
Emphasis: I'm happy to put a PR together doing the legwork, but thought it best to throw the idea down in words first.

---

Problem statement:

Right now the contextual write API isn't really fleshed out; there is a single public api: `void Complete(byte[])`

The intent of this proposal is to put together a simple but effective write API that will allow effective use of pooled buffers, non-contiguous, memory, etc.

Right now:

`DefaultSerializationContext` (`internal`) - stores the state and exposes `byte[] GetPayload()` to return it

this is used by `UnsafeSerialize` in `AsyncCallBase` (internal), which carries a `byte[]` in
both server and client paths;

server; `StartSendStatusFromServer` (`INativeCall`, internal) which calls down to
`grpcsharp_call_send_status_from_server`

client: `StartUnary` => `grpcsharp_call_start_unary` etc

---

Thought process:

- because of the implementation, we will always need buffered serialize (rather than writing directly
to the native output buffers)
- we want to enable pooled buffers for write
- the current native API takes a byte[] (marshalled as a root pointer) and length
- we want to allow `IBufferWriter` style serialization and/or over-sized arrays
- there is no defined consume API on `SerializationContext`, relying on internal implementations; we should rationalize that
- any API here should work similarly with or without ROS support

---

Proposal:

1. add a new type that represents an (oversized) buffer along with lifetime management
(a recycler callback); when MEMORY is available, this will be based on `ReadOnlySequence<T>`; otherwise, `ArraySegment<byte>` - but the API is unified between the two implementations; something like:

``` c#
readonly struct PayloadBuffer
{
    public PayloadBuffer(ArraySegment<byte> payload, Action<ArraySegment<byte>> onCompletion = null);
    public int Length {get;}
    public bool TryGetArray(out ArraySegment<byte> segment); // only true if single buffer
    public void WriteTo(byte[] destination, int offset = 0); // copies to a linear buffer
    public void Complete(); // tests onCompletion type, invoking in the appropriate way
#if MEMORY
    public PayloadBuffer(ReadOnlySequence<byte> payload, Action<ReadOnlySequence<byte>> onCompletion = null);
    public ReadOnlySequence<byte> AsReadOnlySequence();
#endif
}
```

2. change all the payload APIs that currently pass around a `byte[]` to pass around a `PayloadBuffer` instead, all the way down to the native wrapper; these are all `internal` once past the `SerializationContext`

3. in the wrapper API *in Grpc.Core*:

- `if TryGetArray && segment.Offset == 0`, use the existing single array and `.Count` for the length
- otherwise, rent a buffer from the array-pool, use `WriteTo` to linearize, write *that*, then return the leased buffer
- call `Complete` (releases the payload data as defined by the implementation)

Dotnet.Grpc can choose which API to consume

Note: if we can change the native wrapper API to use byte* instead of byte[] (no change to the C/C++ - just the wrapper), we could also allow non-zero-rooted arrays and other kinds of memory without the extra copy (WriteTo) - but in reality this probably isn't really needed; in virtually all cases where a single buffer is used: it will be a zero-rooted array

4. Update `SerializationContext` to expose this API:

- When #MEMORY, add `public IBufferWriter BufferWriter {get;}` and `public void Complete()`; have them throw on the base
- add `Complete(ArraySegment<byte>, Action<ArraySegment<byte>>)` overload for oversized/pooled usage without `IBufferWriter`; throws on base
- existing `Complete(byte)` => `Complete(new ArraySegment<byte>(payload), null)`

5. Create a new `public class BufferedSerializationContext : SerializationContext, IBufferWriter`

- overrides `.BufferWriter` returning `this`;
- has logic to implement `IBufferWriter` using the array pool, defaulting to non-trivial (8k? 16k?) pages
- adds `public PayloadBuffer GetPayload()` method that returns the appropriate thing

6: change `DefaultSerializationContext`, plus whatever Dotnet-Grpc defines, to inherit this implementation from `BufferedSerializationContext` (to avoid writing / maintaining it twice)

--- 

Outcome:

- right now, no code will consume the `IBufferWriter` API, but *it can start*, making use of pooled memory throughout, plus non-contiguous memory, etc
- likewise, new code can issue oversized arrays as payloads without an extra alloc/copy, and/or make use of pooled buffers
- in most common cases, no extra copy to linearize the data will be required; but when it is, the larger linear block is pooled and *only* leased for the duration of the P/Invoke step

---

Example usage from contextual serializer marshallers:

``` c#
value.WriteTo(ctx.BufferWriter); // some synchronous IBufferWriter API
ctx.Complete(); // still expected to call *some* kind of Complete after writing
```

/cc @jtattermusch @JamesNK

**Comment by jtattermusch** [comment]
I think @JamesNK  and me were assuming that we will go with the option *"When #MEMORY, add public IBufferWriter BufferWriter {get;} and public void Complete(); have them throw on the base"*
and not provide any extra APIs for folks that don't have System.Memory.
The reasons:

- The API should be trivially implementable on AspNetCore 3 and it's relatively easy to implement in the native implementation too.
- Everyone on netstandard2.0 can trivially use System.Memory and we can probably add the dependency on System.Memory for net45 target too. So there won't be almost any users that seriously care about performance and at the same time cannot use IBufferWriter-based API.
- we should make the API footprint as small as possible (and it looks liek there's little value in duplicating the functionality though an extra API)

Ad native (C-core based implementation):
*"the current native API takes a byte[] (marshalled as a root pointer) and length"* - that's something that can change. C-core actually consumes a grpc_byte_buffer as the payload. The buffer consists of 0-n grpc_slice continguous buffer segments. The Grpc.Core implementation of IBufferWriter can actually manage instances of grpc_slice (native type, so no GC comes into play) and let the user write directly into these slices. It shouldn't be hard to come up with some basic logic that allocates grpc_slice buffers to write into and exposes their memory as Span<byte>.

**Comment by mgravell** [comment]
OK, that's super useful context, thanks. Totally agree that creating an additional API would be bad if this is an option later. I don't know anywhere near enough about the native API to touch that, so I propose I just walk away from that one for now. Happy to help if I can help later, though!

**Comment by jtattermusch** [comment]
@mgravell  I was planning to come up with a prototype implementation of IBufferWriter for the native implementation (using grpc_slices internally) for a while, I just need to set aside some time to do that. Please stay tuned.
