### ISSUE TITLE
CSharp: Set compression on the server

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#19513]
CSharp doesn't support the `server_compressed_streaming` and `server_compressed_unary` interop tests. There is no API on `ServerCallContext` to set a response to use compression on a call-by-call basis.

C++ for example does this via `ServerContext.set_compression_algorithm`
https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_context.html#ade949b886faed50627e5cbd35fe4ec72

Java has `ServerCall.setCompression`
https://github.com/grpc/grpc-java/blob/e5bd7f282c45a7e90fdb9a9b6939b6ada6f8e31a/api/src/main/java/io/grpc/ServerCall.java#L187-L202

CSharp should add `string ServerCallContext.Compression { get; set; }`

**Comment by jtattermusch** [comment]
@JamesNK  is this still relevant? Given that Grpc.Core is in maintenance mode we definitely won't do this for Grpc.Core. If this is still relevant for grpc-dotnet, we can move this issue there?
My opinions is that we don't really need this and we can close (but we can reopen and move if you want).
