### ISSUE TITLE
Repository for windows prebuilt libs

### ISSUE THREAD

**Issue by thommyho** [grpc/grpc#19518]
Hi folks,
I use gRPC (cpp) with visual studio 2017 for quite some time now and its now my first choice for a robust and awesome RPC framework🥇 . Great job on that 👍 .
But .... I missed prebuilt libraries for windows for the common msvc compilers (14, 14.1, 14.2). So I started a github repository which I will keep up to date with the latest (important) versions.
I also added a basic example (helloworld) with a property sheet which should help you generating the protobuf grpc sources and headers + include/library path+libraries to link etc.
Link --> https://github.com/thommyho/gRPC_windows

Greetings,
Thomas

**Comment by AspirinSJL** [comment]
@gnossen @srini100  Should this be P1?

**Comment by gnossen** [comment]
@thommyho The [grpc-ecosystem](https://github.com/grpc-ecosystem) organization houses repositories that complement the main gRPC repos. If you're interested, we could potentially rehome your repo there.

**Comment by srini100** [comment]
Details on how to contribute to grpc-ecosystem are [here](https://github.com/grpc/grpc-community/blob/master/grpc_ecosystem.md).

This shouldn't be P1.
