### ISSUE TITLE
csharp discussion : lifetime of Metadata.Entry, possible change

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#19527]
I'm looking at performance and allocations, and one big spot at the moment is Metadata.Entry, and their contents.

I see a way to massively reduce the cost of these, but it would be a sort-of change, one worthy of decent discussion.

Intent: performance

---

Hypothesis: most headers and trailers aren't inspected, yet we new up arrays (binary) and strings (otherwise) for their contents.

Context: server-side request-headers; client-side response headers and trailers.

Idea: don't do that.

With some relatively simple changes, we could use rented oversized arrays for a copy of the data during pre-processing. If the caller uses any of the existing API surface to fetch the value, then **at that point** we materialize the actual value, and swap it into the fields.

If the caller doesn't touch the values for the duration of the server operation or client-side operation (before the dispose): they degrade and are recycled into the pool; if they attempt to access it, throw an appropriate error telling them to touch it if they want it. If they have touched a value: fine, the Entry keeps working forever until GC.

It changes the usage slightly, but saves a lot of allocs.

Thoughts, @jamesnk @jtattermusch

**Comment by mgravell** [comment]
Note: another way of implementing this would be to have the client and server elect *out* of headers/trailers; for example via `CallOptions`. Much less. Odd and fewer surprises - it *enables* a high perf mode without changing the default behaviour.

**Comment by JamesNK** [comment]
On the server they are created on demand. If the dev doesn't access ServerCallContext.RequestHeaders in their methods then Metadata are never allocated.

I haven't looked closely at client allocations yet.

**Comment by jtattermusch** [comment]
I think the on-demand mentioned by @JamesNK approach makes sense. 
In Grpc.Core, it might be possible to make ServerCallContext.RequestHeaders on-demand as well (= only creating managed object from the native data once the user requests that) but there might be some challenges (e.g. keeping the native object that holds the metadata alive. currently we read the request headers when the call starts and we can throw away the native data, which is easier).

**Comment by mgravell** [comment]
@jtattermusch IMO this could be implemented without impacting the native timings by using the pool, and releasing the pool data after the server method completes. This would be very easy to implement, and just means that if a server implementation decides to bleed `Metadata.Entry` items *outside of the scope of the server-side operation*, **without looking at the values first** (to bake them into `string` etc) then they will stop working - presumably throwing `InvalidOperationException`. IMO this is a very reasonable compromise that will impact *almost nobody*, and as long as the exception (and release notes) tells them how to fix it (i.e. "look at the values before leaking the object"): all great!

Happy for me to take a stab at that at some point?

**Comment by jtattermusch** [comment]
> Note: another way of implementing this would be to have the client and server elect _out_ of headers/trailers; for example via `CallOptions`. Much less code to change, and fewer surprises - it _enables_ a high perf mode without changing the default behaviour.

Makes sense but I'd prefer to have a stack where you can get good performance with the default setup: without needing to make a conscious choice to sacrifice features for performance or vice versa.

**Comment by jtattermusch** [comment]
I think it's fair to recycle and reuse `Metadata` and `Metadata.Entry` values if the user haven't 
seen the entire metadata instance at all (e.g. `ServerCallContext.RequestHeaders` property is never read)

That's assuming we can come up with a change that implement this behavior without adding too much complexity.
