### ISSUE TITLE
windows cpp client does something odd with deadlines, and crashes

### ISSUE THREAD

**Issue by larsonmpdx** [grpc/grpc#1953]
I added a deadline to the getfeature rpc:

context.set_deadline(std::chrono::system_clock::time_point(std::chrono::system_clock::now() + std::chrono::seconds(5)));

this produces this error (visible on server, either windows server or linux server): chttp2_transport.c:1440] Ignoring bad timeout value '-./,),(-*,(S'

the windows client then crashes

a linux client running the same code works fine, and has the expected 5 second deadline

see fork of grpc-common here:

https://github.com/larsonmpdx/grpc-common/tree/testing-timeout/cpp

(same build setup as in issue #1952)

I commented out the server streaming RPCs which didn't work (#1952)

**Comment by larsonmpdx** [comment]
I replaced the deadline with

context.set_deadline(gpr_time_from_seconds(5));

and it gives the same error (server shows same bad value)

replacing it with

context.set_deadline(gpr_time_add(gpr_now(), gpr_time_from_seconds(5)));

which I thought would be equivalent to the std::chrono version - gives an immediate crash with no server error

**Comment by randooom** [comment]
Removing the "_USE_32BIT_TIME_T" Pre-proccessor flag from all grpc libraries resolved some strange crashes with deadlines (e.g. references pointing to wrong locations).

Adding "_USE_32BIT_TIME_T" to own projects might also work.

**Comment by jtattermusch** [comment]
we are no longer using _USE_32BIT_TIME_T
#4315
