### ISSUE TITLE
Error when enabling google_default_credentials interop test for aspnetcore

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#19534]
When I enabled auth tests for aspnetcore - https://github.com/grpc/grpc/pull/19512/commits/e9ad360759a85db168bc21e254a5a761de16405e - the interop tests threw an error I'm not familiar with:

> Invalid transport security option aspnetcore in cloud_to_prod_jobspec. Lang: google_default_credentials

https://source.cloud.google.com/results/invocations/dcbd8dcf-ab3f-4bc3-b2c0-52ee5f275b28/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

What needs to be done to allow aspnetcore to run google_default_credentials?

@jtattermusch

**Comment by jtattermusch** [comment]
The error is coming from here:
https://github.com/grpc/grpc/blob/df998f70239ec80af7d9af7133f9c0757e952f39/tools/run_tests/run_interop_tests.py#L893

currently the google_default_credentials is only supported by c++, go and java and it uses a special google_default_credentials credential type which has some special GCE-specific logic (which would be very hard to implement IMHO), while there are simpler alternatives available (GoogleCredential from the C# auth library will do the same job). The right approach here is to first get the other auth tests working (https://github.com/grpc/grpc/pull/19512) and perhaps revisit this test case later.

**Comment by JamesNK** [comment]
aspnetcore now supports ChannelCredentials. We should get this test passing to verify we can get full compatibility with the current v2 changes.

**Comment by jtattermusch** [comment]
Enabling `google_default_credentials` is out of scope for now and the tests being enabled in https://github.com/grpc/grpc/pull/20099 should be sufficient for now.
(the requirement is to be able to use the "application default credentials" implemented in pure C# in Grpc.Auth/Google.Apis.Auth)
