### ISSUE TITLE
.gitmodules branches are outdated

### ISSUE THREAD

**Issue by pkl97** [grpc/grpc#19547]
The .gitmodules file on the master branch seems a bit outdated:

    [submodule "third_party/protobuf"]
        path = third_party/protobuf
        url = https://github.com/google/protobuf.git
        branch = 3.0.x

The latest branch in the protobuf repository is 3.8.x (containing release 3.8.0).

    [submodule "third_party/cares/cares"]
        path = third_party/cares/cares
        url = https://github.com/c-ares/c-ares.git
        branch = cares-1_12_0

There is no branch cares-1_12_0 in the c-ares repository. Only a tag with this name exists.

Running "git submodule update --remote" results in this error:
Unable to find current origin/cares-1_12_0 revision in submodule path 'third_party/cares/cares'

I ran into these issues when compiling gRPC (C++) from source.

Regards, Peter.

**Comment by jtattermusch** [comment]
CC @nicolasnoble @gnossen

**Comment by jtattermusch** [comment]
The file seems out of date indeed
https://github.com/grpc/grpc/blob/master/.gitmodules
