### ISSUE TITLE
windows cpp server does not get metadata

### ISSUE THREAD

**Issue by larsonmpdx** [grpc/grpc#1954]
same build instructions as #1952.  see grpc-common fork here:

https://github.com/larsonmpdx/grpc-common/tree/testing-metadata/cpp/route_guide

I added this code to getfeature on the client:

context.AddMetadata("foo", "hi");

and this code to getfeature on the server:

	std::multimap<grpc::string, grpc::string>::const_iterator foo_iterator = context->client_metadata().find("foo");

	if (foo_iterator != context->client_metadata().end())
	{
		std::cout << "client metadata for foo: " << foo_iterator->second << std::endl;
	}
	else
	{
		std::cout << "client metadata for foo not found" << std::endl;
	}

this works correctly with a linux server/linux client, and also a linux server/windows client.  a windows server does not get metadata from a windows client

**Comment by larsonmpdx** [comment]
multimap.size() reads as 0 on the windows server

**Comment by larsonmpdx** [comment]
same as #1952, I don't care too much.  I don't plan to run a windows server, and the client does work correctly

**Comment by nicolasnoble** [comment]
The code moved a huge lot since then. I would be surprised if this is still an issue. I am going to preemptively close it - please update with comments if that's not the case and we'll re-open.
