### ISSUE TITLE
 c# Client Connecting Issue DNS lookup error for '127.0.0.1'. 'Non-Existent Domain'

### ISSUE THREAD

**Issue by sujit9923** [grpc/grpc#19559]
We are getting below error while connecting to a server on the local machine

DNS lookup error for '127.0.0.1'. 'Non-Existent Domain'

Please suggest solution

**Comment by a11r** [comment]
Looks like the system resolver is unable to resolve '127.0.0.1'. That needs to be fixed on the OS.
