### ISSUE TITLE
SegFault when attempting to serialize \Google\Protobuf\Internal\Message

### ISSUE THREAD

**Issue by paquettg** [grpc/grpc#19550]
### What version of gRPC and what language are you using?

gRPC: 1.2.1
Language: PHP 7.0

### What operating system (Linux, Windows,...) and version?

Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Proto-c: libprotoc 3.7.1
 
### What did you do?
I attempted to serialize (https://www.php.net/manual/en/function.serialize.php) a response object received from the standard worker. I attempted this on all the generated response objects.
 
### What did you expect to see?
 To return a serialized string that represent the object.
 
### What did you see instead?
I get a seg fault and an empty core directory.

This should be easy enough to replicate using PHP 7.0. As far as I can tell

**Comment by stanley-cheung** [comment]
Please log this issue to the https://github.com/protocolbuffers/protobuf repo highlighting this is for PHP Protobuf.
