### ISSUE TITLE
How to send Custom Error codes thru the GrpcLoadBalancing 

### ISSUE THREAD

**Issue by gautammoulik** [grpc/grpc#19558]
I am working on my own custom GRPCLoadBalancer based on https://github.com/grpc/grpc/blob/master/doc/load-balancing.md and  https://godoc.org/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1 , it is working fairly well.
Currently, I am in a need to send a custom error code as the status code and custom error message as error message when the client tries to connect to a downstream service (thru my Grpc LoadBalancer)
Essentially, I am trying to send thru this Custom error code and message from the BalanceLoad(), the signature of the func is BalanceLoad(LoadBalancer_BalanceLoadServer) error [this func is part of LoadBalancerServer interface ].
This method only allows throws an error (which is essentially an error string) and I have seen the error it throws doesn't reach to the the client. 
How can I send my custom error message and code to the Grpc channel, so that client should receive my custom error not error message like "Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Failed to create subchannel")"
So instead of StatusCode = "Unknown", it will be my custom error code and the Detail will by my custom error message.

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by a11r** [comment]
It is not possible for the balancer to influence the status of RPCs. The Balancer is a control plane entity and its job is to help the client find a backend. 

That said, the balancer can still return error details on the load balancing request it receives from the client.

**Comment by gautammoulik** [comment]
@a11r -- 
Thanks for replying, on "That said, the balancer can still return error details on the load balancing request it receives from the client." 
I am throwing a custom error from the routine which is handling the load balancer request, however  the client gets "Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Failed to create subchannel")",  my guess is the GRPC lib eats up my exception and throw this generic exception to the client. 
Do you happen to have any sample code on this, as in how we can send error to the load balancing request ... ?
