### ISSUE TITLE
Is it normal there is no throw error when there is no 'data' event listener on client? (Node.js)

### ISSUE THREAD

**Issue by lesomnus** [grpc/grpc#19575]
### What version of gRPC and what language are you using?

Node.js v12.4.0
grpc v1.12.1 on npm
 
### What operating system (Linux, Windows,...) and version?
 
Windows10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Node.js
 
### What did you do?
A client receives data from the server via stream but the client ignores the data chunk from the server some reason (so the client doesn't listen to the `data` event from ClientReadableStream).
Although, the client listens to the `error` event like:
```js
stream.on('error', (err)=>console.log(err))
```

Meanwhile, the server encountered an error, so emit error like:
```js
call.emit('error', err)
```

### What did you expect to see?
 
I expected that the `err` is logged.
 
### What did you see instead?

Nothing.

If the client listens to both `data` and `error`, however, the `err` is logged as I expected.
Is it intended situation?

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
