### ISSUE TITLE
Name Resolution Error...with raw IPv4?

### ISSUE THREAD

**Issue by mastergberry** [grpc/grpc#19576]
I am using GRPC 1.13 with C++.
 
I am using the Windows OS x64 bit.
 
I am using Visual Studios 2015 to compile GRPC.

I tried to open a simple connection to an IPv4 and Port...but I got a name resolution failrue instead.
 
In the logs I saw "Name resolution failure - Error 14" (my formatting of the GRPC errors).

I'm a bit confused why this is happening...shouldn't GRPC not do any DNS lookup when using a raw IP/port? Is this a feature that was added later or one that still needs to be accounted for?

**Comment by a11r** [comment]
It is not uncommon to use the system resolver unconditionally, and rely on the resolver to handle IP addresses properly.
