### ISSUE TITLE
g_default_client_callbacks shouldn't be global variable #17154 and after it memory leak exists for g_default_client_callbacks

### ISSUE THREAD

**Issue by klion-ru** [grpc/grpc#19590]
### What version of gRPC and what language are you using?
gRPC version 1.21.1-1, c++
 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2015
 
### What did you do?
I compile my dll-plugin with static gRPC and after unload my plugin i see memory leak/
I check dbg crt memory blocks and see memory leak for g_default_client_callbacks (or the same g_client_callbacks).
 
### What did you expect to see?
 No memory leak.
 
### What did you see instead?
 I see memory leak for g_default_client_callbacks in client_context.cc:
`static DefaultGlobalClientCallbacks* g_default_client_callbacks =
    new DefaultGlobalClientCallbacks();
` 

### Anything else we should know about your project / environment?
--

This memory leak occurred after a commit: "g_default_client_callbacks shouldn't be global variable #17154".
I think We need an external interface to access the variable g_default_client_callbacks (or g_client_callbacks) to destroy it.

**Comment by weiyongji** [comment]
what operation have you done? 
I think there shall be a clear() function to delete the object, after reviewing the code.

**Comment by klion-ru** [comment]
I need to unload my DLL which contains grpc static lib. Maybe there will be
a clear() function. I know when I will call this function on unload my DLL.


ср, 10 июл. 2019 г., 15:27 weiyongji <notifications@github.com>:
