### ISSUE TITLE
pypi sdist package for grpc-tools-1.22.0

### ISSUE THREAD

**Issue by nareshv** [grpc/grpc#19608]
### What version of gRPC and what language are you using?
 1.22.0
 
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 3.x, rhel7
 
### What did you do?
Find if there is grpc-tools-1.22.0.tar.gz in Pypi
 
### What did you expect to see?
 Expected to see source package for 1.22.0 in https://pypi.org/simple/grpcio-tools/
 
### What did you see instead?
 All binary packages for 1.22.0
 
### Anything else we should know about your project / environment?
None

**Comment by gnossen** [comment]
Thanks for the heads up. The problem should be resolved now. We'll be improving the release process to ensure this doesn't happen again.
