### ISSUE TITLE
FR: create a standalone API to transform grpc style path to protobuf style

### ISSUE THREAD

**Issue by yzhao1012** [grpc/grpc#19618]
It would need to extract the code at https://github.com/grpc/grpc/blob/7bf82de9eda0aa8fecfe5edb33834f1b272be30b/test/cpp/util/grpc_tool.cc#L374 to some other appropriate place.

WDYT?

I'll contribute a PR if this is fine.

The use case is that we want to check gRPC HTTP2 traffic, and need to associate the HTTP2 :path header to the protobuf path for reflection.

**Comment by yang-g** [comment]
It is a small piece of code and the logic is unlikely to change. Thus I think it might be better to just re-implement it in your application.

**Comment by yzhao1012** [comment]
> It is a small piece of code and the logic is unlikely to change. Thus I think it might be better to just re-implement it in your application.

>> It is a small piece of code and the logic is unlikely to change.

I think this is precisely the reason why such code should be in grpc code base? I.e., small means trivial change, consistent means it saves a lot client repetition.

I am not arguing to reopen this, as said it's trivial to replicate the code. But it's such a shame that client needs to replicate a piece of code that is already inside the official library...

**Comment by yang-g** [comment]
I understand your point, but note the code lives in test/ at the moment. We try to not expand our API surface unless necessary and this feature is not core to gRPC and will unlikely be widely used by our users. If we put it as part of gRPC's API then we need to support it forever, and all the users will have it, see it and they might try to understand what it does.

We had discussions about moving the cli related pieces into its own repo such as grpc_utils and if we have that, it could be a better home form this helper routine.

**Comment by yzhao1012** [comment]
Thanks for your explanation, Yang!

The idea of moving into a separate grpc_utils is great! I'll like to see it becomes more helpful for gRPC users to build and share tools and libraries around gRPC. The results can be very valuable and far-reaching.

As a Xoogler, I can imagine that being very useful already, as we had much better internal toolings.
