### ISSUE TITLE
resolver_component_test fails under MacOS

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#19619]
D0711 13:57:54.846727000 123145420189696 resolver_component_test.cc:387] Opened fd: 55
D0711 13:57:54.846760000 123145420189696 resolver_component_test.cc:387] Opened fd: 56
D0711 13:57:54.846809000 123145420189696 resolver_component_test.cc:387] Opened fd: 57
D0711 13:57:54.846844000 123145420189696 resolver_component_test.cc:387] Opened fd: 58
D0711 13:57:54.846864000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 5
D0711 13:57:54.846911000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 8
D0711 13:57:54.846939000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 9
D0711 13:57:54.846964000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 7
D0711 13:57:54.846980000 140735503315840 dns_test_util.cc:56]          Failed to bind UDP ipv6 socket to [::1]:5353
D0711 13:57:54.846995000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 10
D0711 13:57:54.847026000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 12
*******************************
Caught signal SIGABRT
D0711 13:57:54.847058000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 11
  no backtrace
D0711 13:57:54.847083000 123145420189696 resolver_component_test.cc:400] non-blocking accept then close on 14
test/cpp/naming/resolver_component_tests_runner.py: now kill DNS server

Test log: https://source.cloud.google.com/results/invocations/f8b4bc4e-053a-4a8c-a7d4-8b51b7782a43/targets/github%2Fgrpc%2Fcpp_macos_opt_native/tests;group=cpp_macos_opt_native;test=bins%2Fopt%2Fresolver_component_tests_runner_invoker_unsecure%20--test_bin_name%3Dresolver_component_test_unsecure%20--running_under_bazel%3Dfalse%20GRPC_POLL_STRATEGY%3Dpoll;row=1

**Comment by jtattermusch** [comment]
```
test/cpp/naming/resolver_component_tests_runner.py: Health check: attempt to connect to DNS server over TCP.
Traceback (most recent call last):
  File "test/cpp/naming/utils/tcp_connect.py", line 38, in <module>
    main()
  File "test/cpp/naming/utils/tcp_connect.py", line 35, in main
    timeout=args.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 61] Connection refused
```

https://source.cloud.google.com/results/invocations/3e468247-6f07-4189-9dac-56f438fd3abd/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_opt_native/tests
