### ISSUE TITLE
Anyway to reset tcp connection by client?

### ISSUE THREAD

**Issue by randylu** [grpc/grpc#19640]
### What version of gRPC and what language are you using?
client: objective-c
server: c++
grpc version: 1.4.5

### What operating system (Linux, Windows,...) and version?
Linux version 3.10.0-957.10.1.el7.x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (GCC) 4.8.5

### What did you do?
We create a grpc server, and many IOS device will connect to it.

### What did you expect to see?
When the client sends request to the server, the server reponses on time.

### What did you see instead?
Sometimes the server reponses quickly, sometimes you need wait for a long time, then fail(maybe 10 minutes).

### Anything else we should know about your project / environment?
  I'm not very familiar with grpc, so it's hard to analyze the situation. Then i use Wireshark to capture packages between the client and server, and find something interesting. 
  I just guess that the clent will send a TCP Keep Alive package to server periodically, if the client doesn't send it for some reason, then server will close the TCP connection later?
  If the above is right, does grpc provide a method to disconnet the connection by client?

**Comment by srini100** [comment]
gRPC doesn't enable TCP keepalive but provides API to enable HTTP level keepalive (by default it is off). A TCP connection may get disconnected for any number of reasons like NAT routers in the middle, firewalls, LBs etc. If the connection is idle for a long time there is a higher chance that the connection is broken. When client sends RPC on a broken TCP connection that the client is not aware of (socket is still healthy), then client will be stuck waiting for a response until TCP timeout happens which could take several minutes. You can try enabling keepalive in gRPC to detect broken connections faster.

**Comment by AspirinSJL** [comment]
Please reopen if you have further questions.

**Comment by danlanxiaohei** [comment]
@srini100 @AspirinSJL I have a similar question,  i use gRPC bidirectional streaming to implement a chat app, the client is iPhone, when open the app, start a gRPCCall, when press the home button(app will enter background mode), finish the Call, everything works fine. 
But when i started a gRPCCall, after a while, the network suddenly instable (such as lose package), then i can not read or write any data, then i finish the call, start a new call , the new call will stuck for a long time !

i understand gRPC use one connection for all gRPCCalls, i can start or stop gRPCCall, but i can not find any API to manage the connection. so when the connection goes wrong , the gRPCCall can not success.
any idea on this question?

**Comment by AspirinSJL** [comment]
@danlanxiaohei 

I recommend recreating a channel in this case.

**Comment by srini100** [comment]
If you are using gRPC-OjbC, there is no API to access channel. It is abstracted out under gRPCCall. gRPC-ObjC uses CFStream in the transport layer. If there is a local (on-device) connectivity issue that iOS can detect, the CFStream socket will fail and the transport is closed. If there is a connection failure outside the device which cannot be detected until there is a socket timeout (which can be several minutes), then you have to set gRPC keepalive to detect network failure. For unary RPCs, setting a deadline on the call is another option but since you are using long lived bi-di streaming you don't have that option.

**Comment by danlanxiaohei** [comment]
@srini100 any way to set idle timeout in Objective-C ? i find 【GRPC_ARG_MAX_CONNECTION_IDLE_MS】in grpc_type.h ,  but it does not work!
