### ISSUE TITLE
Jave gRPC server throws GO_AWAY error even though the C++ gRPC client is not configured with keepalive settings

### ISSUE THREAD

**Issue by mailravi02** [grpc/grpc#19644]
### What version of gRPC and what language are you using?
 client: C++
server: python/Java/C++
grpc C++ Client version: 1.15.1
grpc Java Server version: 1.22

grpc python Server version: 1.15.1

 
### What operating system (Linux, Windows,...) and version?
 Debian Stretch

 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
### What did you do?
The C++ grpc client is not configured with keepalive settings.  Initiate a gRPC connection with Java server. The server will throw GO_AWAY after 10 minutes.

 
### What did you expect to see?
 There should not be any keepalive pings sent from the C++ grpc client.
 
### What did you see instead?
 The client sends ping every 5 minutes to the server. The ping interval is based on the value set for GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS.   The keepalive settings are default in Client.

**Comment by mailravi02** [comment]
The python/C++/Java gRPC servers does not have any keepalive settings configured.

**Comment by mailravi02** [comment]
[client_ping_logs.txt](https://github.com/grpc/grpc/files/3390909/client_ping_logs.txt)

Note:
The attached log is taken from a python gRPC server. The server responds to the client ping for every 5 minutes (Search for logs WRITING [PING_RESPONSE]).

**Comment by mailravi02** [comment]
[java_grpc_server_log.txt](https://github.com/grpc/grpc/files/3397714/java_grpc_server_log.txt)
The attached java server logs has the GO_AWAY error

**Comment by yashykt** [comment]
Yes, C++ clients do send BDP pings to estimate what the flow control window should be. But, we can disable it

**Comment by yashykt** [comment]
args->SetInt(GRPC_ARG_HTTP2_BDP_PROBE, 0);

By settings this channel argument, we would be disabling it.
