### ISSUE TITLE
grpc completion queue delivering messages to application in a reversed order as opposite to client entrusting.

### ISSUE THREAD

**Issue by ppLorins** [grpc/grpc#19658]
### What version of gRPC and what language are you using?
 v1.21.x c++
 
### What operating system (Linux, Windows,...) and version?
 windows 10pro
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 vs2015 Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
 
### What did you do?
1> entrust  serveral mesasges in  such a way
 ```c++
    void SayHello(const std::string& user,int idx) {
  
    HelloRequest request;
    request.set_name(std::to_string(idx));

    AsyncClientCall* call = new AsyncClientCall;

    std::chrono::time_point<std::chrono::system_clock> _deadline = std::chrono::system_clock::now()
                    + std::chrono::milliseconds(3100);
    call->context.set_deadline(_deadline);
    
    call->response_reader = stub_->PrepareAsyncSayHello(&call->context, request, cq_);
    call->response_reader->StartCall();
    call->response_reader->Finish(&call->reply, &call->status, (void*)call);
}

//Calling SayHello 10 times in a sequence of:
SayHello("xx",1);
SayHello("xx",2);
SayHello("xx",3);
....
```

And finally the current return the to the  `CQ::Next()` call to trigger the messages to be sent.

2> retrieve the messages and print them on the server side, there are only one CQ and one thread polling on it:
```c++
 void HandleRpcs(int cq_idx) {
    void* tag;  
    bool ok;
    while (true) {
      GPR_ASSERT(m_cq[cq_idx]->Next(&tag, &ok));
      CallDataBase* _p_ins = (CallDataBase*)tag;
      _p_ins->Proceed(ok);
    }
  }

void Proceed(bool ok) {
	if (status_ == PROCESS) {
		this->SpawnInstance(service_, cq_);
    
    std::string prefix("Hello ");
    reply_.set_message(prefix + request_.name());

    std::cout << "req name:" << request_.name() << std::endl;

    status_ = FINISH;
    responder_.Finish(reply_, Status::OK, (void*)this);
  } else {
       if (status_ != FINISH) {
           std::cout << "wrong status:" << status_ << std::endl;
           assert(false);
       }
   
    delete this;
  }
}

```

### What did you expect to see?
 output:
req name:0
req name:1
req name:2
....

the order being the **same** as the client entrusing.
 
### What did you see instead?
 output:
req name:9
req name:8
req name:7
....

the order is the **reversed version** as the client entrusing.

the order is the same as the client entrusing
 
### Anything else we should know about your project / environment?
My server is little kind of stateful, and the order message is critical for performance in my application.

**Comment by lidizheng** [comment]
Do you think streaming RPC is an option for your service? Our streaming RPC ensure the arriving order of messages.

**Comment by ppLorins** [comment]
No. It's not. The requests are from different clients which are prefer to
have a short connection request.     Why the delivering order cannot be
guaranteed by CQ?

**Comment by lidizheng** [comment]
@guantaol  @yashykt Who probably is more qualified to answer the underlying technical details. 
---
By the multiplex nature of HTTP2, the sending and receiving order of messages can be mixed. It only guarantee the message order within each STREAM.

However, a completely reversed arrival order definitely indicates there are something weird going on. Can you either provide a complete reproduction case? Or try if the sync API also have the same problem?

**Comment by ppLorins** [comment]
1. Client side code is [here](https://gist.github.com/ppLorins/f30e6a2e14c3738288200b43a803b122)
note the `SayHello` invoking code, the order is defined here:
```c++
for (int i = 0; i < thread_num; ++i) {
        auto * _p_client = new GreeterClient(_addr,&one_cq,count);
        _vec.push_back(_p_client);

        std::string user("world " + std::to_string(i));
        for (int j = 0; j < count; j++)
            _p_client->SayHello(user, j);  // The actual RPC call!
    }
```

2. Server side code is [here](https://gist.github.com/ppLorins/d3392111992097c68454e9381d53b446)
note the `CallDataUnary::Proceed()` definition, the printing order is defined here:
```c++
  void Proceed(bool ok) {
      static int counter = 0;

     if (status_ == PROCESS) {
        this->SpawnInstance(service_, cq_);

        std::string prefix("Hello ");
        reply_.set_message(prefix + request_.name());

        std::cout << "req name:" << request_.name() << std::endl;
      ...
```

The running result is:
![image](https://user-images.githubusercontent.com/5534049/61526001-24042a80-aa4c-11e9-9d06-6c13977aaa79.png)


3.  > By the multiplex nature of HTTP2, the sending and receiving order of messages can be mixed. It only guarantee the message order within each STREAM.

But this reminds me something:  **Is the STREAM represented by a `Stub` object in grpc or a reader/writter object like `ClientAsyncResponseReader` in grpc**?

4. I'm using different channels by passing into different channel arguments in the posted code, and this will lead to using different HTTP2 connections. Seems this should be the reason for disordering (`presumption X` ), but not the reason for strictly reversed order.  And I can quickly  overthrow `presumption X` by doing another experiment:

I slightly modified the client code in two places:
1>
```c++
   std::string _key = "key_" + std::to_string(_sec.count());
   std::string _val = "val_" + std::to_string(_sec.count());

   //This line is commented now.
  // _channel_args.SetString(_key,_val);

```

we now passing the same empty channel arguments to different channel objects, but the channel objects will still sharing one tcp connection according to some other materials I've read before.

2>
```c++
 for (int i = 0; i < thread_num; ++i) {
        auto * _p_client = new GreeterClient(_addr,&one_cq,count);
        _vec.push_back(_p_client);
        std::string user("world " + std::to_string(i));

        int _count_each_stub = 5;

        for (int j = 0; j < count; j++) {
            for (int k = 0; k < _count_each_stub; ++k) {
                int _idx = j * _count_each_stub + k;
                _p_client->SayHello(user, _idx); 
            }

        }
    }
```
which means that  each of 5 continuous requests will be counted as a group, and each group is entrusted by a same STREAM, different group using different STREAMS, aka 
[0-4] should be received in order by the server side application, 
[5-9] should be received in order by the server side application, too.
[10-14]....
[15-19]....

and the order between [0-4] and [5-9]  cannot be guaranteed. 

But , in fact , I still got the same reversed order as before:
![image](https://user-images.githubusercontent.com/5534049/61528458-6e3bda80-aa51-11e9-84d3-9008c284a364.png)

By the above experiments, I can even got the conclusions of:
message delivering order to the server side application cannot be guaranteed even they are in the same STREAM!

What is wrong?

**Comment by yashykt** [comment]
If I recall correctly, the completion queue API does not guarantee ordering of tags returned, so the implementation is free to change the order of tags returned.

**Comment by ppLorins** [comment]
Hi, any updates on this issue?  I encounter this again, and this reverse really hit me a lot.

**Comment by yashykt** [comment]
Each RPC corresponds to a different HTTP2 stream. A reader/writer object would correspond to a stream (not the stub).

To repeat, gRPC does NOT provide any ordering guarantees to RPCs. If the RPC is a streaming RPC, then the ordering of messages will be maintained, but there is NO ordering guarantees between separate RPCs. 

If there is a need of such a guarantee, you would need to provide a layer on top of gRPC to handle the ordering.
