### ISSUE TITLE
gRPC Ruby GEM contains unnecessarily files

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#19675]
# What version of gRPC and what language are you using?

gRPC Ruby 1.22 
 
### What operating system (Linux, Windows,...) and version?
 
Debian 10 x86_64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Ruby 2.5
 
### What did you do?

```
$ gem install grpc

$ find /var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux -name "*.ruby"
/var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux/grpc_c.32.ruby
/var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux/grpc_c.64.ruby

$ find /var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux -name "*.so"
/var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux/src/ruby/lib/grpc/2.6/grpc_c.so
/var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so
/var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux/src/ruby/lib/grpc/2.5/grpc_c.so
/var/lib/gems/2.5.0/gems/grpc-1.22.0-x86_64-linux/src/ruby/lib/grpc/2.4/grpc_c.so
```

### What did you expect to see?

Only *.so file should present. 
 
### What did you see instead?

Along with *.so file, there are *.ruby files for windows, which increases the size of gem file unnecessarily.

**Comment by veblush** [comment]
Please keep this live.

**Comment by yoniamir** [comment]
There should be a lean distribution for production environment. Currently the gem takes up 38.01MB which is incredibly excessive.

**Comment by yoniamir** [comment]
this is a real issue. the gem size is really excessive.

**Comment by yoniamir** [comment]
This is a real issue. Total gem size is quite excessive.

**Comment by veblush** [comment]
#23344 replaced `grpc_*.ruby` with the empty files. So it will be expected to be downsized from 1.31.
