### ISSUE TITLE
can't pip install grpc

### ISSUE THREAD

**Issue by lvhuijia** [grpc/grpc#19677]
### What version of gRPC and what language are you using?
 gRPC==0.3-19 
language ==python
 
### What operating system (Linux, Windows,...) and version?
 windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 3.5.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 pip install grpc==0.3-19
### What did you expect to see?
 successfully pip
 
### What did you see instead?
     Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lvhuijia\AppData\Local\Temp\pip-install-5ks4ngri\grpc\setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "C:\Users\lvhuijia\AppData\Local\Temp\pip-install-5ks4ngri\grpc\grpc\__init__.py", line 6, in <module>
        from .rpc import *
      File "C:\Users\lvhuijia\AppData\Local\Temp\pip-install-5ks4ngri\grpc\grpc\rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\lvhuijia\AppData\Local\Temp\pip-install-5ks4ngri\grpc\

### Anything else we should know about your project / environment?
I created a conda environment and pip inside it

Many thanks!

**Comment by lvhuijia** [comment]
in addition, I tried upgrade my pip and setuptools as follow:
pip install --upgrade setuptools
python -m pip install --upgrade pip
still doesn't work =.=

**Comment by gnossen** [comment]
Unfortunately, our package is named `grpcio` because `grpc` was already taken by a *different* project. The project using the name `grpc` on PyPI appears to be both broken and abandoned, [so many people are feeling this pain](https://github.com/pypa/warehouse/issues/5435).

**Comment by lvhuijia** [comment]
thanks for your help! @gnossen
