### ISSUE TITLE
C#: Add GrpcEnvironment.SetHttpProxy and SetGrpcTrace settings.

### ISSUE THREAD

**Issue by lobster2012-user** [grpc/grpc#19706]
Perhaps this will be true for other languages.
How do you look at adding properties to GrpcEnvironment ( instead of referring to the System.Environment)?

```csharp
            Environment.SetEnvironmentVariable("http_proxy", "http://127.0.0.1:8888/");
            Environment.SetEnvironmentVariable("GRPC_TRACE", "all");
```
->
```csharp
        GrpcEnvironment.SetHttpProxy ("http://127.0.0.1:8888/") ;
        GrpcEnvironment.SetGrpcTrace( GprcTrace.All) ;
```

**Comment by jtattermusch** [comment]
I think we'd rather not duplicate ways of setting these options (=more complexity, not much of benefit). 

Btw, to be able to do this, we would first need to solve the issue mentioned in https://github.com/Falco20019 (Environment.SetEnvironmentVariable changes aren't visible to the native layer on all platforms).

**Comment by lobster2012-user** [comment]
Hi @jtattermusch
Where exactly to look at the description of the problem?

**Comment by jtattermusch** [comment]
@lobster2012-user  sorry, I updated the link
