### ISSUE TITLE
When a keepalive ping is triggered, its watchdog is always fired

### ISSUE THREAD

**Issue by Cytoo** [grpc/grpc#19711]
### What version of gRPC and what language are you using?
 
 We're using grpc 1.19.0, in C++.

### What operating system (Linux, Windows,...) and version?
 
 We're using it on various versions of Windows. More specifically, i do reproduce it on Windows 10.

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 MSVC Toolchain v141 (Visual Studio 2017)

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
The simplest reproduction case is a client attempting to join two different servers. One of the server is not launched, meaning we expect the calls toward this server to fail. This is relevant because we did not reproduce when only attempting to connect to the one server that is up.

both server adresses are local to the client (localhost).

We set the GRPC_ARG_KEEPALIVE_TIME_MS to 10s.
GRPC_ARG_KEEPALIVE_TIMEOUT_MS to 5s, On both the client and the server.
So, after 10 second of inactivity, each of them initate a ping toward the other.

At the beginning of the scenario, we make quick calls to both server. The first server successfully processes the call, and the second call, with the server being down, returns in error.

The problem arises when we wait 15 seconds after this call. Then the client logs a GRPC error 

Please not that line offsets might be off, due to adding some additional logging in grpc files. 
> (chttp2_transport.cc:2782) ipv4:127.0.0.1:10300: Keepalive watchdog fired. Closing transport.

Which is unexpected, given that the server is up and running.
When we traces packets using Wireshark, and coupling it with full GRPC trace, we can notice that:
* This is actually the first instance of the keepalive timer starting. Each other ping we see before have been triggered by the BDP ping.
* In the case of the Keepalive ping, we observe that the client does not react to the server ping.
* We do also observe that the server reacts to the client ping, send a PING ACK, but that is obviously not handled by the client.

Even though Wireshark capture shows a PING being sent, there is no trace of 
> (tcp_windows.cc:189) TCP:000001D2CD40C610 on_read

in the client, that leads me to thinking that for whatever reason it stops to even try to read on the socket at some point ? This is where my knowledge of GRPC internals stops.

### What did you expect to see?

No watchdog fired when the server is up and running
 
### What did you see instead?
 
Watchdog firing every time.
 
### Anything else we should know about your project / environment?

[watchdog.log](https://github.com/grpc/grpc/files/3417669/watchdog.log)

127.0.0.1:10300 is the Server that is running, 127.0.0.1:10333 is the server that is down.

The watchdog fires at 10:56:07, the ping is sent at 10:56:02. At this point we should see a READ on : 
* The ACK of the client's ping. 
* The ping from the server

but we don't see any of those. The only activity we see is at 10:56:05, when we attempt to reconnect to 10333.

**Comment by yashykt** [comment]
Note that the current gRPC release is 1.24. Please try it again on HEAD.

One guess I would make is that the client is a synchronous client and that there is no thread on the client that is currently driving the completion queue and hence, not reading the socket. If we want the client to be able to always respond to the server then the application would need to provide a thread to gRPC to poll the socket.

**Comment by HeathLee** [comment]
I have same problem with python client and server with grpcio==1.27.2

**Comment by yashykt** [comment]
I won't be able to tell what's going on with the python client, but for the C++ client/server, I would advise retrying with the async API where we always have a thread working the completion queue.
