### ISSUE TITLE
Docs on grpc_completion_queue_next and grpc_completion_queue_pluck are incorrect

### ISSUE THREAD

**Issue by endobson** [grpc/grpc#1972]
Both of these docs say that the functions return `NULL` on timeout. But since they actually return a `grpc_event` with the `type` set to `GRPC_QUEUE_TIMEOUT`.

https://github.com/grpc/grpc/blob/master/include/grpc/grpc.h#L361

https://github.com/grpc/grpc/blob/master/src/core/surface/completion_queue.c#L215

**Comment by vjpai** [comment]
Thanks for reporting this! Your comment is, of course, correct.
