### ISSUE TITLE
PHP: Missing addref on ChannelCredentials in Channel constructor causes segfault.

### ISSUE THREAD

**Issue by kellegous** [grpc/grpc#19721]
This needs label:lang/php

### What version of gRPC and what language are you using?
1.22.0 (issue is still in master) 
 
### What operating system (Linux, Windows,...) and version?
 LInux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP
```
PHP 7.2.20 (cli) (built: Jul 12 2019 23:20:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
 
### What did you do?
The code to reproduce:
``` php
<?php
new \Grpc\Channel('localhost', [
    'credentials' => \Grpc\ChannelCredentials::createSsl(),
]);
```

### What did you expect to see?
The php file above should execute without a segfault and produce no output.
 
### What did you see instead?

```
# php -d 'extension=grpc.so' err.php
Segmentation fault
```

GDB shows a back trace of:
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff3f614ef in zim_Channel___construct (execute_data=<optimized out>, return_value=<optimized out>) at /grpc-1.22.0/src/php/ext/grpc/channel.c:383
#2  0x0000555555b053bc in execute_ex ()
#3  0x0000555555b06278 in zend_execute ()
#4  0x0000555555a63db3 in zend_execute_scripts ()
#5  0x0000555555a01448 in php_execute_script ()
#6  0x0000555555b087ae in ?? ()
#7  0x00005555556d107c in ?? ()
#8  0x00007ffff73c009b in __libc_start_main (main=0x5555556d0bf0, argc=4, argv=0x7fffffffea68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffea58) at ../csu/libc-start.c:308
#9  0x00005555556d117a in _start ()
```
 
The issue seems to be here:
https://github.com/grpc/grpc/blob/1d5357d1bbfd1e83bad7f5b02c1b4937bdc9b61f/src/php/ext/grpc/channel.c#L333-L335

A reference to the object stored in the `"credentials"` key is in `creds_obj` and the `refcount` seems to be `1` (due to the reference in `array_hash`). Once `php_grpc_zend_hash_del` removes the `"credentials"` key, the `refcount` drops to `0` even though `creds_obj` still references the object. This eventually results in memory corruption of the pointer `creds->hashstr` which is why `strlen(creds->hashstr)` segfaults.

Some evidence to support this hypothesis.

The following script does not experience the segfault. Notice that aliasing the `ChannelCredentials` into `$creds` has the effect of adding to the `refcount`.
```php
<?php
$creds = \Grpc\ChannelCredentials::createSsl();
new \Grpc\Channel('localhost', [
    'credentials' => $creds,
]);
```

Additionally, if we add the following on line 333, the original script does not crash.
```
Z_ADDREF(*creds_obj);
```

**Comment by kellegous** [comment]
cc @stanley-cheung

**Comment by stanley-cheung** [comment]
@kellegous Thanks for the detail report!
