### ISSUE TITLE
multi thread and multi channel problems

### ISSUE THREAD

**Issue by dmthinker** [grpc/grpc#19731]
Hi
   I'm appreciated if anyone can help me with follow two questions.
  1, When High-concurrent-request from the grpc client,  if creating multi-channels is more efficient than only one channel?
  2, When High-concurrent-request from the grpc client,  should I use multithread to handle the requests in grpc-server?  And I'm not sure if the grpc server has integrated multithread already, or I have to use the multithread in the grpc-server myself, and I didn't find the tensorflow-model-server use the multithread when use grpc.

**Comment by DavidLiuXh** [comment]
I have observed that channel and TCP connection are not one-to-one correspondences

**Comment by srini100** [comment]
What language are you using? Assuming your target resolves into a single IP (no LB involved), for high concurrency it is better to create more channels so more TCP connections are created to the target. This will help avoid saturating a single TCP connection and better utilize multiple cores on the client machine. In C++ (but not in Java and Go), different channels may end up sharing the same sub-channel (TCP connection) if the target and channels args are the same.

**Comment by dmthinker** [comment]
@srini100 Thank you very much for answering me. "In C++ (but not in Java and Go), different channels may end up sharing the same sub-channel (TCP connection) if the target and channels args are the same.", I'm a little confused of this. Do you mean different channels with same args won't work when the client is c++? What should I do if I want to use multi channels in C++.

**Comment by srini100** [comment]
In C++ there is an optimization where two channels with same arguments will share an underlying sub-channel (TCP connection). One would expect the channels to create their own sub-channels and hence provide more throughput but that's not the default behavior. If you want channels to not share sub-channels then just provide different channel args like a unique key value pair. https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_channel_arguments.html#a6506784ed2e66dc2ca2358d68fadf317

**Comment by dmthinker** [comment]
You means one-to-many or many-to-one

发自我的 iPhone

**Comment by dmthinker** [comment]
Thx,this helps a lot

发自我的 iPhone
