### ISSUE TITLE
Docs still refer to removed functions: grpc_call_invoke, etc

### ISSUE THREAD

**Issue by endobson** [grpc/grpc#1973]
These functions were renamed in https://github.com/grpc/grpc/commit/c4f0ebe63bbd4b7f9ca551fd6dcb0df026464623 and removed in https://github.com/grpc/grpc/commit/0e91956b49c2782ef7fae0acf2362a8863b37ee4.

The references are here:
https://github.com/grpc/grpc/blob/master/include/grpc/grpc.h#L435

**Comment by jayantkolhe** [comment]
fixed
