### ISSUE TITLE
i want know the data frame of grpc.

### ISSUE THREAD

**Issue by hbgongen** [grpc/grpc#19750]
according to grpc over http2.i also has some questions about it.
grpc data fram: compress flag(1 bytes) | message length(4 bytes) | message(binary bytes)|EOS(bytes?)
can i understand in this way.
data frame
00000000                    |00000000 00000000 00000000 00000000|           .......            |EOS
1 byte (compress flag)|                        4 bytes length                   |message content |

EOS:i don't know what it is and how many bytes does it have?
**_can you give me a example of data frame._**(hope it can accurate to bit)
i want to make a http2 to grpc by myself.thanks a lot.

**Comment by yang-g** [comment]
EOS is indicated in the http2 frame header. For example, a http2 data frame has flag 0x1 as END_STREAM bit. See https://http2.github.io/http2-spec/#DATA

gRPC message just has its 5-byte header. So if you have X bytes in your serialized message, X+5 bytes will be sent as HTTP2 payload.

**Comment by hbgongen** [comment]
@yang-g
Thanks.i got it.Does grpc have another different areas in header from http2 header?

**Comment by yang-g** [comment]
No it does not. You can get a sense of what gRPC uses . in https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

You can dump the output of gRPC with gRPC tracers such as TCP tracer as described in https://github.com/grpc/grpc/blob/master/doc/environment_variables.md
