### ISSUE TITLE
TIMEOUT: python_linux_opt_native > py37_native.test.unit._compression_test.CompressionTest

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#19755]
https://source.cloud.google.com/results/invocations/01b3c879-0cdd-4e11-aecd-1a5b3b768612/targets/github%2Fgrpc%2Fpython_linux_opt_native/tests

**Comment by lidizheng** [comment]
@gnossen It seems weird that this test didn't finish within 300 seconds...
