### ISSUE TITLE
MetadataCredentialsPlugin missing from csharp libraries

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [grpc/grpc#19775]
### What version of gRPC and what language are you using?

1.22, csharp, C\#
 
 
### What operating system (Linux, Windows,...) and version?
 
Windows 10, Windows Server 2016
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
.NET 4.7.1
 
### What did you do?

The [gRPC Auth documentation](https://grpc.io/docs/guides/auth/), under "Extending gRPC to support other authentication mechanisms", states that custom call credentials can be implemented using grpc::MetadataCredentialsPlugin. However, I can find no such type in the C\# libraries disributed via nuget.

I cannot locate MetadataCredentialsPlugin abstract class, and I cannot locate the MetadataCredentialsFromPlugin static method.

*Note: Why do I need this? I am trying to implement custom authentication using API Keys. And we want to do so without adding a custom credentials parameter to every service call, and without adding custom authentication code to every service method implementation -- hence the desire to use custom CallCredentials via the MetadataCredentialsPlugin method and leverage the gRPC authentication framework.*

 
### What did you expect to see?

I expected to see the types MetadataCredentialsPlugin and the function MetadataCredentialsFromPlugin, as shown in the [gRPC Documentation](https://grpc.io/docs/guides/auth/), in the Grpc.Core library or (perhaps) in the Grpc.Core.Api library.
 
### What did you see instead?
 
Nothing. Cannot find MetadataCredentialsPlugin abstract class, and cannot find anything like it under a different name.
 
### Anything else we should know about your project / environment?

Visual Studio 2017.

**Comment by jtattermusch** [comment]
What you're looking for in C# is  `CallCredentials.FromInterceptor` factory method
https://github.com/grpc/grpc/blob/ff8354ed5e463da1925afe3f2688167428356257/src/csharp/Grpc.Core.Api/CallCredentials.cs#L48

Usage example can be found e.g. here
https://github.com/grpc/grpc/blob/19ed319a941cfdaf98a02353ee92d66626e1954a/src/csharp/Grpc.IntegrationTesting/MetadataCredentialsTest.cs#L74
