### ISSUE TITLE
Python flakiness on Travis test

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#1978]
+python2.7 -B -m grpc._adapter._future_invocation_asynchronous_event_service_test
testCancelledStreamRequestStreamResponse (__main__.FutureInvocationAsynchronousEventServiceTest) ... I0608 15:56:35.228180939    9225 server.c:1041] grpc_server_request_call(server=0x2146f10, call=0x7f07d5b319c0, details=0x1d4f370, initial_metadata=0x1d4f3a0, cq_bound_to_call=0x2146730, cq_for_notification=0x2146730, tag=0x1d4f360)
I0608 15:56:35.242341154    9235 call.c:1205] grpc_call_start_batch(call=0x7f07b40029d0, ops=0x7f07b40044f0, nops=1, tag=0x7f07b4004470)
I0608 15:56:35.242378645    9235 call.c:1205] ops[0]: SEND_INITIAL_METADATA
I0608 15:56:35.242494811    9235 call.c:1205] grpc_call_start_batch(call=0x7f07b40029d0, ops=0x7f07b4004b30, nops=1, tag=0x7f07b4004ab0)
I0608 15:56:35.242506704    9235 call.c:1205] ops[0]: RECV_INITIAL_METADATA ptr=0x7f07b4004a90
I0608 15:56:35.242543110    9235 call.c:1205] grpc_call_start_batch(call=0x7f07b40029d0, ops=0x7f07b4004ec0, nops=1, tag=0x7f07b4004e40)
I0608 15:56:35.242557733    9235 call.c:1205] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7f07b4004dc0 status=0x7f07b4004de0 details=0x7f07b4004e00
I0608 15:56:35.251334899    9235 completion_queue.c:223] RETURN_EVENT[0x214d390]: OP_COMPLETE: tag:0x7f07b4004470 ERROR
I0608 15:56:35.251410617    9235 completion_queue.c:223] RETURN_EVENT[0x214d390]: OP_COMPLETE: tag:0x7f07b4004e40 OK
I0608 15:56:35.251588829    9235 completion_queue.c:223] RETURN_EVENT[0x214d390]: OP_COMPLETE: tag:0x7f07b4004ab0 OK
I0608 15:56:35.255335552    9232 completion_queue.c:223] RETURN_EVENT[0x2146730]: OP_COMPLETE: tag:0x1d4f360 ERROR
I0608 15:56:35.306698085    9232 completion_queue.c:223] RETURN_EVENT[0x2146730]: QUEUE_SHUTDOWN
ok
testCancelledStreamRequestUnaryResponse (__main__.FutureInvocationAsynchronousEventServiceTest) ... I0608 15:56:35.307643958    9225 server.c:1041] grpc_server_request_call(server=0x21fe4a0, call=0x7f07d5b31d00, details=0x1d4f370, initial_metadata=0x1d4f3a0, cq_bound_to_call=0x21fe070, cq_for_notification=0x21fe070, tag=0x1d4f360)
I0608 15:56:35.330820307    9241 call.c:1205] grpc_call_start_batch(call=0x7f07a4001d60, ops=0x7f07a4002c90, nops=1, tag=0x7f07a4002c10)
I0608 15:56:35.330857411    9241 call.c:1205] ops[0]: SEND_INITIAL_METADATA
I0608 15:56:35.330983301    9241 call.c:1205] grpc_call_start_batch(call=0x7f07a4001d60, ops=0x7f07a40030f0, nops=1, tag=0x7f07a4003070)
I0608 15:56:35.330993782    9241 call.c:1205] ops[0]: RECV_INITIAL_METADATA ptr=0x7f07a4003050
I0608 15:56:35.331266555    9241 call.c:1205] grpc_call_start_batch(call=0x7f07a4001d60, ops=0x7f07a40032a0, nops=1, tag=0x7f07a4003220)
I0608 15:56:35.331281789    9241 call.c:1205] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7f07a40031a0 status=0x7f07a40031c0 details=0x7f07a40031e0
I0608 15:56:35.332684813    9241 call.c:1205] grpc_call_start_batch(call=0x7f07a4001d60, ops=0x7f07a40058b0, nops=1, tag=0x7f07a4004800)
I0608 15:56:35.332701287    9241 call.c:1205] ops[0]: SEND_MESSAGE ptr=0x7f07a40057c0
I0608 15:56:35.334600813    9242 completion_queue.c:223] RETURN_EVENT[0x212fb90]: OP_COMPLETE: tag:0x7f07a4002c10 ERROR
I0608 15:56:35.334690512    9242 completion_queue.c:223] RETURN_EVENT[0x212fb90]: OP_COMPLETE: tag:0x7f07a4004800 ERROR
I0608 15:56:35.334936376    9242 completion_queue.c:223] RETURN_EVENT[0x212fb90]: OP_COMPLETE: tag:0x7f07a4003220 OK
I0608 15:56:35.335123051    9242 completion_queue.c:223] RETURN_EVENT[0x212fb90]: OP_COMPLETE: tag:0x7f07a4003070 OK
I0608 15:56:35.336372942    9238 completion_queue.c:223] RETURN_EVENT[0x21fe070]: OP_COMPLETE: tag:0x1d4f360 ERROR
I0608 15:56:35.406936990    9238 completion_queue.c:223] RETURN_EVENT[0x21fe070]: QUEUE_SHUTDOWN
ok
testCancelledUnaryRequestStreamResponse (__main__.FutureInvocationAsynchronousEventServiceTest) ... I0608 15:56:35.408319790    9225 server.c:1041] grpc_server_request_call(server=0x220f7b0, call=0x21b6120, details=0x1d4f370, initial_metadata=0x1d4f3a0, cq_bound_to_call=0x220f380, cq_for_notification=0x220f380, tag=0x1d4f360)
I0608 15:56:35.416170801    9247 call.c:1205] grpc_call_start_batch(call=0x7f0790001540, ops=0x7f07900026b0, nops=1, tag=0x7f0790002630)
I0608 15:56:35.416209458    9247 call.c:1205] ops[0]: SEND_INITIAL_METADATA
I0608 15:56:35.416349376    9247 call.c:1205] grpc_call_start_batch(call=0x7f0790001540, ops=0x7f0790002b10, nops=1, tag=0x7f0790002a90)
I0608 15:56:35.416358379    9247 call.c:1205] ops[0]: RECV_INITIAL_METADATA ptr=0x7f0790002a70
I0608 15:56:35.416392809    9247 call.c:1205] grpc_call_start_batch(call=0x7f0790001540, ops=0x7f0790002cc0, nops=1, tag=0x7f0790002c40)
I0608 15:56:35.416402779    9247 call.c:1205] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7f0790002bc0 status=0x7f0790002be0 details=0x7f0790002c00
I0608 15:56:35.416544336    9247 call.c:1205] grpc_call_start_batch(call=0x7f0790001540, ops=0x7f0790003590, nops=1, tag=0x7f0790002f20)
I0608 15:56:35.416553536    9247 call.c:1205] ops[0]: SEND_MESSAGE ptr=0x7f07900034a0
E0608 15:56:35.506551055    9226 tcp_client_posix.c:151] socket error: 104
E0608 15:56:35.506686736    9226 tcp_client_posix.c:151] socket error: 104
I0608 15:56:35.506998500    9245 completion_queue.c:223] RETURN_EVENT[0x2205560]: OP_COMPLETE: tag:0x7f0790002630 OK
I0608 15:56:35.507139243    9245 completion_queue.c:223] RETURN_EVENT[0x2205560]: OP_COMPLETE: tag:0x7f0790002f20 OK
I0608 15:56:35.606448714    9244 completion_queue.c:223] RETURN_EVENT[0x220f380]: OP_COMPLETE: tag:0x1d4f360 OK
E0608 15:56:35.606476267    9226 tcp_client_posix.c:148] socket error: connection refused
E0608 15:56:35.606519702    9226 tcp_client_posix.c:148] socket error: connection refused
I0608 15:56:35.606739231    9244 call.c:1205] grpc_call_start_batch(call=0x7f07cc010520, ops=0x7f07b0000ea0, nops=1, tag=0x7f07b0000e20)
I0608 15:56:35.606750873    9244 call.c:1205] ops[0]: RECV_CLOSE_ON_SERVER cancelled=0x7f07b0001110
I0608 15:56:35.606775716    9244 call.c:1205] grpc_call_start_batch(call=0x7f07cc010520, ops=0x7f07b0000d40, nops=1, tag=0x7f07b0001560)
I0608 15:56:35.606783080    9244 call.c:1205] ops[0]: SEND_INITIAL_METADATA
I0608 15:56:35.606898868    9244 call.c:1205] grpc_call_start_batch(call=0x7f07cc010520, ops=0x7f07b0001690, nops=1, tag=0x7f07b0001a80)
I0608 15:56:35.606907578    9244 call.c:1205] ops[0]: RECV_MESSAGE ptr=0x7f07b0001670
I0608 15:56:35.607352033    9245 completion_queue.c:223] RETURN_EVENT[0x2205560]: OP_COMPLETE: tag:0x7f0790002a90 OK
I0608 15:56:35.608628930    9244 server.c:1041] grpc_server_request_call(server=0x220f7b0, call=0x21b65a0, details=0x7f07b0007860, initial_metadata=0x7f07b0007890, cq_bound_to_call=0x220f380, cq_for_notification=0x220f380, tag=0x7f07b0007850)
I0608 15:56:35.608654750    9244 completion_queue.c:223] RETURN_EVENT[0x220f380]: OP_COMPLETE: tag:0x7f07b0001560 OK
I0608 15:56:35.608696167    9244 completion_queue.c:223] RETURN_EVENT[0x220f380]: OP_COMPLETE: tag:0x7f07b0001a80 OK
I0608 15:56:35.608837802    9244 call.c:1205] grpc_call_start_batch(call=0x7f07cc010520, ops=0x7f07b0000d40, nops=1, tag=0x7f07b0000d70)
I0608 15:56:35.608847038    9244 call.c:1205] ops[0]: RECV_MESSAGE ptr=0x7f07b00010f0
E0608 15:56:36.705358176    9226 tcp_client_posix.c:148] socket error: connection refused
E0608 15:56:36.705524915    9226 tcp_client_posix.c:148] socket error: connection refused
E0608 15:56:36.805359397    9226 tcp_client_posix.c:148] socket error: connection refused
E0608 15:56:36.805406778    9226 tcp_client_posix.c:148] socket error: connection refused
I0608 15:56:38.416593308    9244 completion_queue.c:223] RETURN_EVENT[0x220f380]: OP_COMPLETE: tag:0x7f07b0000d70 OK
I0608 15:56:38.417082893    9244 completion_queue.c:223] RETURN_EVENT[0x220f380]: OP_COMPLETE: tag:0x7f07b0000e20 OK
I0608 15:56:38.418058011    9245 completion_queue.c:223] RETURN_EVENT[0x2205560]: OP_COMPLETE: tag:0x7f0790002c40 OK
ERROR:root:Unexpected exception from task run in logging pool!
Traceback (most recent call last):
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 43, in _wrapping
    return behavior(*args, **kwargs)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/face/testing/stock_service.py", line 269, in service
    _watch_future_trades(request, response_consumer, control, context.is_active)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/face/testing/stock_service.py", line 80, in _watch_future_trades
    raise abandonment.Abandoned()
Abandoned

**Comment by vjpai** [comment]
More at https://s3.amazonaws.com/archive.travis-ci.org/jobs/65908815/log.txt

**Comment by nathanielmanistaatgoogle** [comment]
Closing - `grpc._adapter.future_invocation_asynchronous_event_service_test` is no longer in the codebase.
