### ISSUE TITLE
[Aio] When using a process executor a segmentation fault is received

### ISSUE THREAD

**Issue by pfreixes** [grpc/grpc#19793]
Once the gRPC aio has been initialized by using the `init_grpc_aio` [1] function the usage of a process executor breaks the application receiving a segmentation fault. 

For the following snippet

```python
import asyncio
import concurrent.futures

from grpc.experimental import aio


def cpu_bound():
    # CPU-bound operations will block the event loop:
    # in general it is preferable to run them in a
    # process pool.
    return sum(i * i for i in range(10 ** 7))

async def coro(loop):
    print("Initializing gRPC aio")
    aio.init_grpc_aio()

    print("Running thread executor")
    with concurrent.futures.ThreadPoolExecutor() as pool:
        result = await loop.run_in_executor(pool, cpu_bound)

    print("Running process executor")
    with concurrent.futures.ProcessPoolExecutor() as pool:
        result = await loop.run_in_executor(pool, cpu_bound)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(coro(loop))
```

Once it is executed the application finishes abruptly receiving a segmentation fault

```bash
$ python /private/tmp/aio_fork_breaks.py
Initializing gRPC aio
Running thread executor
Running process executor
Segmentation fault: 11
```

We should find out why is the application receiving a segmentation fault and fix it, otherwise, users won't be able to use processes for offloading CPU bound work, and what is most annoying receiving abruptly segmentation faults.

[1] https://github.com/Skyscanner/grpc/blob/unary_unary_client_aio_unit_tests/src/python/grpcio/grpc/_cython/_cygrpc/aio/iomgr/iomgr.pyx.pxi#L156

**Comment by pfreixes** [comment]
@gnossen / @lidizheng this is the issue that I was commenting about receiving an abrupt segmentation fault when the process runs a fork after having the gRPC aio initialized. Could you add this as part of the gRPC Easy project? Thanks!

**Comment by pfreixes** [comment]
Seems that the root cause would be caused when a custom `iomgr` is used and the `grpc_prefork` function is called since `grpc_get_poll_strategy_name` is an undefined symbol accessing to its raises a segfault [1].

Running the snippet attached to this bug with the environment variable `GRPC_ENABLE_FORK_SUPPORT` configured to 0 it works like a charm.

We should fix this bug in the core source for not having this segfault when the `GRPC_ENABLE_FORK_SUPPORT` is not used and the library has been compiled for having the support, we should also design and implement the proper plan when there is a fork and the `aio` module is being used.

```bash
$ GRPC_ENABLE_FORK_SUPPORT=0 python /tmp/segfault.py
Initializing gRPC aio
Running thread executor
Running process executor```

[1] https://github.com/grpc/grpc/blob/7f54da6bff4ae4ec5511badeeba313656953ab88/src/core/lib/iomgr/fork_posix.cc#L64

**Comment by lidizheng** [comment]
Thank you for the investigation. It is a known issue, and has been fixed by https://github.com/grpc/grpc/pull/19556. If you sync this branch with master, this segfault problem should go away.
