### ISSUE TITLE
python: Can stream server send a list of reply but not return, client parse one by one like go[stream.Recv()]?

### ISSUE THREAD

**Issue by DengkeDu** [grpc/grpc#19804]
### What version of gRPC and what language are you using?
```
 v1.19.1
python
 ```
### What operating system (Linux, Windows,...) and version?
```
 ubuntu 16.04
 ```
### What runtime / compiler are you using (e.g. python version or version of gcc)
```
 gcc version: 5.4.0
 ```
### What did you do?
```
c++ grpc stream server on machine A
python grpc client on machine B
```

```
rpc Report (Request) returns (stream Reply) {}
```
 
```
grpc server send a lot of Reply in program's many aspect,  but did not return Status::OK, until the program end life.
grpc client revice a reply, parse it and do something.
```
### What did you expect to see?

Like [go client](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L68)

```
stream.Recv()
```

but python always return a whole list of reply like [this](https://github.com/grpc/grpc/blob/master/examples/python/route_guide/route_guide_client.py#L59)
I just want to get one and one, then parse one and one.
### What did you see instead?
 
Server send all the time, but client always receive one, and error follows:
```
Traceback (most recent call last):
  File "client.py", line 20, in <module>
    rsp = next(res)
  File "/home/ddk/venv/lib/python3.5/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/home/ddk/venv/lib/python3.5/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1564542280.668378122","description":"Error received from peer ipv4:127.0.0.1:36163","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Socket closed","grpc_status":14}"
>

```

**Comment by gnossen** [comment]
The API looks a little different from Go's, but the functionality should be equivalent. In [the example you linked](https://github.com/grpc/grpc/blob/master/examples/python/route_guide/route_guide_client.py#L59), `features` is not a `list` object, [it is a generator over which you may iterate](https://grpc.github.io/grpc/python/grpc.html#grpc.UnaryStreamMultiCallable) to receive the results incrementally.
