### ISSUE TITLE
cloud_to_prod:python:default:timeout_on_sleeping_server:tls

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#19834]
This is another of the timeout_on_sleeping_server bugs. I didn't spot one from cloud_to_prod on python, so creating a new issue. These can be merged into one if the root cause is the same.

```
2019-08-01 16:49:59,634 TIMEOUT: cloud_to_prod:python:default:timeout_on_sleeping_server:tls [pid=29682, time=187.8sec]
2019-08-01 16:49:59,923 FAILED: Some tests failed
```

https://source.cloud.google.com/results/invocations/5b6c5b07-dba8-4d23-9805-14702d2c3fa5/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

seen on #19316

**Comment by markdroth** [comment]
Seeing this again:

https://source.cloud.google.com/results/invocations/19ed1166-cec4-4178-90f9-bc1da1cbb172/log

**Comment by markdroth** [comment]
Seeing a similar failure in tests.cloud_to_cloud:python:dart_server:timeout_on_sleeping_server:tls.

https://source.cloud.google.com/results/invocations/3a2d3535-2c16-44e7-98a7-0c9e77ef526c/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by yashykt** [comment]
Closing since we decided to use buganizer for CI test failures.
