### ISSUE TITLE
verify_peer_callback ignored in SSL handshake

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc#19845]
## What version of gRPC and what language are you using?
 1.22-2.25 / C#
 
### What operating system (Linux, Windows,...) and version?
 Windows 10 64bit
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET 4.7.2
 
### What did you do?
Extended the greeter example with a peer verify callback.

**Server**

```
var cacert = File.ReadAllText(@"..\ca.crt");
var servercert = File.ReadAllText(@"..\server.crt");
var serverkey = File.ReadAllText(@"..\server.key");
var keypair = new KeyCertificatePair(servercert, serverkey);
var sslCredentials = new SslServerCredentials(new List<KeyCertificatePair>() {keypair}, cacert, SslClientCertificateRequestType.DontRequest);
Server server = new Server
{
    Services = {Greeter.BindService(new GreeterImpl())},
    Ports = {new ServerPort("localhost", Port, sslCredentials)}
};
server.Start();
Console.WriteLine("Greeter server listening on port " + Port);
Console.WriteLine("Press any key to stop the server...");
Console.ReadKey();
server.ShutdownAsync().Wait();
```

**Client**
```
var cacert = File.ReadAllText(@"..\ca2.crt");
var clientcert = File.ReadAllText(@"..\client.crt");
var clientkey = File.ReadAllText(@"..\client.key");
var ssl = new SslCredentials(cacert, new KeyCertificatePair(clientcert, clientkey), VerifyPeer);
var channel = new Channel("localhost", 51000, ssl);
var client = new Greeter.GreeterClient(channel);
String user = "you";

var reply = client.SayHello(new HelloRequest {Name = user});
Console.WriteLine("Greeting: " + reply.Message);

channel.ShutdownAsync().Wait();
Console.WriteLine("Press any key to exit...");
Console.ReadKey();
```
The method `VerifyPeer` looks like this:
```
private static bool VerifyPeer(VerifyPeerContext context)
{
  return true;
}
```

*Edit:* A complete minimal example is here: https://github.com/georghinkel/grpc/commit/e0a625f5646f50df1161077671a4367b7d636d51
 
### What did you expect to see?
gRPC would call `VerifyPeer` in order to check whether a connection to the host should be established. Since the method is implemented to just return `true`, the connection should be established successfully.
 
### What did you see instead?

The connection cannot be established. Instead, the following error message occurs:

> **Grpc.Core.RpcException**: 'Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")'   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 78

>    at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46

>    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Interceptors\InterceptingCallInvoker.cs:line 51

>    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174

>    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Interceptors\InterceptingCallInvoker.cs:line 48

>    at Helloworld.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions options) in C:\Projects\grpc\examples\csharp\Helloworld\Greeter\obj\Debug\netstandard1.5\HelloworldGrpc.cs:line 109

>    at Helloworld.Greeter.GreeterClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Projects\grpc\examples\csharp\Helloworld\Greeter\obj\Debug\netstandard1.5\HelloworldGrpc.cs:line 99

>    at GreeterClient.Program.Main(String[] args) in C:\Projects\grpc\examples\csharp\Helloworld\GreeterClient\Program.cs:line 34
> 

I put a breakpoint into the `VerifyPeer` method, but it has not been called. 

However, when both Client and Server use the same CA, the callback is indeed called. This gives me an Option to fail the Connection via the callback. However, I would also like to accept the Connection.
 
### Anything else we should know about your project / environment?
I would like to implement a client that can connect to servers that use self-signed certificates. Upon a connection, I would like to ask the user whether the server should be trusted. I have seen that the `verify_peer_callback` that existed for ages in the C library has been exposed to C# recently, but I cannot get this to work.

**Comment by georghinkel** [comment]
BTW: I based the changes to SSL on the following commit that also includes scripts to generate the openSSL certificates: https://github.com/zut/grpc/commit/3d0e76ef544fc69311e98f20d8ecae5334578d95

Unlike this example, I used different self-signed CAs for server and client, noted as ca.crt and ca2.crt.

**Comment by jtattermusch** [comment]
I suggest running  the client with extra logging, that might tell you what's wrong:
`GRPC_VERBOSITY=debug GRPC_TRACE=handshaker dotnet run -f netcoreapp2.1 GreeterClient.csproj`

**Comment by jtattermusch** [comment]
The most interesting log I'm getting is:
```
I1107 12:04:32.293278 140147165890368 /var/local/git/grpc/src/core/ext/filters/client_channel/subchannel.cc:926: Connect failed: {"created":"@1573146272.292847064","description":"Peer name localhost is not in peer certificate","file":"/var/local/git/grpc/src/core/lib/security/security_connector/ssl/ssl_security_connector.cc","file_line":55}
```

**Comment by jtattermusch** [comment]
CC @yihuazhang can you confirm that this the right behavior for the VerifyPeerCallback?

**Comment by georghinkel** [comment]
Sorry for the late Reply, unfortunately I was given other priorities in the last months. I will upload a commit with a complete example in a moment. The error trace I am getting is:

```
I1209 14:09:49.231985 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:178: handshake_manager 00000232C3F1BB20: calling handshaker security [00000232DC973300] at index 1
E1209 14:09:49.236540 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1246: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D1209 14:09:49.236650 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:186: Security handshake failed: {"created":"@1575896989.236000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I1209 14:09:49.237319 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:131: handshake_manager 00000232C3F1BB20: error={"created":"@1575896989.236000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"} shutdown=0 index=2, args={endpoint=0000000000000000, args=0000000000000000 {size=0: (null)}, read_buffer=0000000000000000 (length=0), exit_early=0}
I1209 14:09:49.238382 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:164: handshake_manager 00000232C3F1BB20: handshaking complete -- scheduling on_handshake_done with error={"created":"@1575896989.236000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

I also tried to use the same ca.crt file for both client and server. If I do that, it does work and actually the `VerifyPeer` method is called, so to say as an extension of the normal verification. I also verified that if I was to return false here, I get an exception. If I use certificates based on different `ca.crt`s, the `VerifyPeer` is not called, but I immediately get an exception that the client failed to connect on all addresses.

**Comment by georghinkel** [comment]
A Minimum example is here:  https://github.com/georghinkel/grpc/commit/e0a625f5646f50df1161077671a4367b7d636d51

My expectation is that it would work (because I have given a callback that always returns true), but in fact, it does not and the callback provided is not even executed. This example is using gRPC version 2.25. However, when I use the same root certificate for server and client, the callback is executed and lets me fail the connection.

**Comment by georghinkel** [comment]
Also fails with 2.26.0-pre1

**Comment by georghinkel** [comment]
I am actually not sure that this is C#-specific. Given that the callback is executed when Client and Server have the same CA, I guess it is rather a principle behavior of the C library that a verify_peer callback if present does not override the SSL handshake verification, but is only called in addition.

**Comment by yihuazhang** [comment]
@georghinkel  Sorry for the late reply. I also suspect the problem happens during SSL handshake instead of during the invocation of verify_peer_callback. Notice that in C-core verify_peer_callback() will be invoked after SSL handshake successfully finishes and has nothing to do with SSL handshake verification (mentioned in your above comment).

**Comment by georghinkel** [comment]
In that case, my issue pretty much boils down that I would expect that a verify_peer_callback if present would override the peer verification and not only act as an additional verification step. Actually, I do not really see a use case in restricting the peers to work with further, but I do see a use case to open up the peer verification. That would enable scenarios where you connect to servers that use self-signed certificates where you don't know their CA in advance.

**Comment by georghinkel** [comment]
@jtattermusch Given the Analysis, I assume that my issue is not at all related to C#. Therefore, I also updated the issue title. Could you Change the labels as well? Or should I rather create a new issue and close this one (because the callback Integration appears to work)

**Comment by jtattermusch** [comment]
Looks like this is entirely about what secure connections are accepted with the C-core server (in your case the connection is rejected even before verify_peer_callback is invoked - can you provide the error logs?). Reassigning to @yihuazhang  as this is not C# related and it's purely about the C-core security layer.

**Comment by georghinkel** [comment]
Error logs see https://github.com/grpc/grpc/issues/19845#issuecomment-563236334 or are there any further logs that I could supply?

**Comment by jtattermusch** [comment]
Actually from the log mentioned in https://github.com/grpc/grpc/issues/19845#issuecomment-551172996 it looks like your certificates are basically invalid - the message "Peer name localhost is not in peer certificate" basically says that the client thinks the server impersonating someone else ("I'm trying to connect to someone with hostname localhost but the server's certificate is telling me that it's someone else so I'm talking to the wrong server so I'd better hang up because this is dangerous"). So the problem seems to be that your certificates are setup incorrectly.

**Comment by georghinkel** [comment]
@jtattermusch Sorry I messed up the comment links. The correct link is https://github.com/grpc/grpc/issues/19845#issuecomment-563236334

I don't think it is a certificate problem, because the client raises an exception depending on the client configuration, not the server configuration. When I execute the client with the same CA as the server, it works fine. The problem is when the client does not know the servers CA, then the upper layer code interprets this as
