### ISSUE TITLE
Server closes connection (C++)

### ISSUE THREAD

**Issue by UltraCoderRU** [grpc/grpc#19861]
### What version of gRPC and what language are you using?
gRPC 1.22.0 C++
 
### What operating system (Linux, Windows,...) and version?
Linux Mint 19.1 (Ubuntu 18.04)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang 6.0.0, GCC 7.4.0

### What did you do?
Trying to run my [test application](https://github.com/UltraCoderRU/my-assistant) to work with Google Assistant Service (based on [this example](https://github.com/googlesamples/assistant-sdk-cpp)).
1. Start network capture with Wireshark (based on hostname `embeddedassistant.googleapis.com`).
2. Run application:
```
GRPC_VERBOSITY=DEBUG GRPC_TRACE=tcp,tsi ./run_assistant_text --credentials ../credentials.json
```
3. Enter some text as request.

### What did you expect to see?
Connection established, and response to request shown on console.
 
### What did you see instead?
`error: Broken pipe`
TCP connection established, but server decided to close it during TLS negotiation. Wireshark shows TLS alert message "Protocol version".
![Screenshot from 2019-08-06 15-10-48](https://user-images.githubusercontent.com/1450836/62550814-8db96c80-b873-11e9-96e5-ccfd22029f79.png)
It seems like library selected old version of TLS (1.0).
[Logs and Wireshark session](https://github.com/grpc/grpc/files/3472923/issue.tar.gz)

### Anything else we should know about your project / environment?
Building all with CMake, gRPC included as subdirectory. Switching from BoringSSL to system OpenSSL doesn't change anything.

**Comment by yashykt** [comment]
At first look, this issue might be better tracked at https://github.com/googlesamples/assistant-sdk-cpp/issues

**Comment by AspirinSJL** [comment]
I agree that this might be better tracked at assistant repo.
