### ISSUE TITLE
bm_chttp2_transport consistently failing with segfault

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#19877]
Test log:
bins/dbg/bm_chttp2_transport --benchmark_filter=BM_TransportStreamSend/134217728$ GRPC_POLL_STRATEGY=poll

D0805 16:26:48.958285370   25878 ev_posix.cc:174]            Using polling engine: poll
D0805 16:26:48.958459186   25878 dns_resolver_ares.cc:485]   Using ares dns resolver
2019-08-05 16:26:48
Running bins/dbg/bm_chttp2_transport
Run on (32 X 2300 MHz CPU s)
CPU Caches:
  L1 Data 32K (x16)
  L1 Instruction 32K (x16)
  L2 Unified 256K (x16)
  L3 Unified 46080K (x1)
***WARNING*** Library was built as DEBUG. Timings may be affected.
Command terminated by signal 11
real 0.93
user 0.17
sys 0.29

**Comment by hcaseyal** [comment]
Doesn't look like that PR is actually the issue (although our test UI says otherwise)...

**Comment by hcaseyal** [comment]
Resultstore link: https://source.cloud.google.com/results/invocations/e67e2209-c883-45d1-9762-34ea29664faa/targets

**Comment by hcaseyal** [comment]
Here seems to be the first instance where it fails: https://source.cloud.google.com/results/invocations/e2b334c4-0107-43ca-9e9b-5f182479b3a7/targets/github%2Fgrpc%2Fcpp_linux_dbg_native/tests

Culprit PRs:
https://github.com/grpc/grpc/pull/19696/files
https://github.com/grpc/grpc/pull/19695/files

@yunjiaw26 Can you take a look?

**Comment by guantaol** [comment]
I do not think this failure is related to https://github.com/grpc/grpc/pull/19696 or https://github.com/grpc/grpc/pull/19695. The fixed-size threadpool has not been integrated to the grpc runtime yet, so it won't affect any test except its own unit tests.

@hcaseyal can you take another look?

**Comment by jtattermusch** [comment]
@guantaol   from the historical data we can see that the breakage started in close proximity of those PRs being merged (very rare failures before that PR got merged and close to 100% failure rate after the PR got merged).  Have you actually tried reproducing the issue before and after the commit? If so, it would be good if you could help investigating - the rootcause is something that got merged +- a few hours from the PRs mentioned and this is our best candidate so far.

**Comment by hcaseyal** [comment]
@guantaol can you try reproing with 'tools/run_tests/run_tests.py -l c++ -c dbg -r bm_chttp2_transport'?
I found that the test fails only under load (aka, when multiple jobs are running). If I just run bins/dbg/bm_chttp2_transport, it will pass.

**Comment by hcaseyal** [comment]
Assigning to arjunroy@ since he has been making hpack changes recently. Also upgrading the priority to P1 since it's causing near 100% breakages on master.

**Comment by arjunroy** [comment]
Running "tools/run_tests/run_tests.py -l c++ -c dbg -r bm_chttp2_transport" does not appear to successfully build on a clean checkout:

/usr/bin/ld: /usr/local/google/home/arjunroy/github/repro/grpc/libs/dbg/libgrpc_plugin_support.a(objective_c_generator.o): undefined reference to symbol '_ZNK6google8protobuf16MethodDescriptor11output_typeEv'

**Comment by arjunroy** [comment]
I have build it with ASAN, and there are indeed issues - it appears that the a grpc_transport_stream_op_batch is being accessed in a manner that crashes the microbenchmark:

BM_TransportStreamSend/262144                                                       14482 ns      14483 ns      48539                                                             
=================================================================                                                                                                                 
==133183==ERROR: AddressSanitizer: unknown-crash on address 0x7fff499ea660 at pc 0x000000688754 bp 0x7f9e35ffd590 sp 0x7f9e35ffd588                                               
READ of size 1 at 0x7fff499ea660 thread T1 (default-executo)                                                                                                                      
    #0 0x688753  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x688753)                                                                       
    #1 0x718edb  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x718edb)                                                                       
    #2 0x6210a6  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x6210a6)                                                                       
    #3 0x71d3eb  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x71d3eb)                                                                       
    #4 0x71e0a3  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x71e0a3)                                                                       
    #5 0x7e0349  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x7e0349)                                                                       
    #6 0x7dfc6b  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x7dfc6b)                                                                       
    #7 0x50123e  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x50123e)                                                                      
    #8 0x7f9e3942dc72  (/lib/x86_64-linux-gnu/libpthread.so.0+0x7c72)                                                                                                            
    #9 0x7f9e38f39dee  (/lib/x86_64-linux-gnu/libc.so.6+0xf8dee)                                                                                                                 
                                                                                                                                                                                 
Address 0x7fff499ea660 is located in stack of thread T0 at offset 8096 in frame                                                                                                  
    #0 0x5331df  (/usr/local/google/home/arjunroy/github/repro/grpc/bins/asan/bm_chttp2_transport+0x5331df)                                                                      
                                                                                                                                                                                 
  This frame has 21 object(s):                                                                                                                                                   
    [32, 7568) 'track_counters' (line 393)                                                                                                                                       
    [7824, 7896) 'exec_ctx' (line 394)                                                                                                                                           
    [7936, 7952) 'f' (line 395)                                                                                                                                                  
    [7968, 8016) 'ref.tmp' (line 395)                                                                                                                                            
    [8048, 8056) 's' (line 396)                                                                                                                                                  
    [8080, 8192) 'op' (line 398) <== Memory access at offset 8096 is inside this variable                                                                                        
    [8224, 8368) 'op_payload' (line 399)                                                                                                                                         
    [8432, 8448) 'reset_op' (line 400)                                                                                                                                           
    [8464, 8496) 'send_slice' (line 408)                                                                

Will dig into this further on Monday.
