### ISSUE TITLE
Missing `gRPCTargets.cmake`

### ISSUE THREAD

**Issue by hdoradu** [grpc/grpc#19873]
There's been a set of cmake fixes recently, but starting with https://github.com/grpc/grpc/pull/12469, we added a test that once can install gRPC with cmake and then use it from another cmake project, so things should be working well right now. Closing.

_Originally posted by @jtattermusch in https://github.com/grpc/grpc/issues/11378#issuecomment-330250204_

The issue is still there.
I just built and installed `grpc` with `cmake` and now I'm trying to build the `helloworld` c++ example.
I am getting the same error:

```
CMake Error at /usr/local/lib/cmake/grpc/gRPCConfig.cmake:8 (include):
  include could not find load file:

    /usr/local/lib/cmake/grpc/gRPCTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:73 (find_package)


-- Using gRPC 1.20.0
-- Configuring incomplete, errors occurred!

```

**Comment by gnossen** [comment]
CC @nicolasnoble

**Comment by hdoradu** [comment]
I think the issue is with the `grpc` install step. I ran cmake again on it and I see this:
```
 gRPC_INSTALL will be forced to FALSE because gRPC_ZLIB_PROVIDER is "module"
```

**Comment by hdoradu** [comment]
I got my answer from [this](https://github.com/grpc/grpc/issues/13841#issuecomment-355510534) post.
What I don't understand is why isn't the `package` set as default if the `cmake` install does not work with `module`. 
Can't it look for installed `package`s and in case thy are not there fallback to `module`?

**Comment by jtattermusch** [comment]
@hdoradu  this is a tradeoff between making build as easy as possible for contributors (they'd usually build using submodules) vs installation experience (there's always room to improve, but the process is relatively well documented and installing c++ libraries is a hard problem in general). We hope to improve the c++ installation experience in the following months, let's see how that goes.

**Comment by igormcoelho** [comment]
I'm having the same issue here... any way to properly install gRPC C++ on linux and run helloworld?

**Comment by hdoradu** [comment]
@igormcoelho, check [this](https://stackoverflow.com/questions/57413975/cmake-with-grpc-cannot-find-grpctargets-cmake)
