### ISSUE TITLE
Need to know how NettyServerBuilder allocates memory to the buffer

### ISSUE THREAD

**Issue by RSoodAMAT** [grpc/grpc#19887]
If i increase the inbound max message size at server side  to be  1GB by NettyServerBuilder, how will the memory be allocated to buffer? 

Will complete 1GB be allocated to the messaging buffer or will it be lazy allocation meaning only that only that much memory will be allocated , that is needed by object. 

For example : If i set NettyServerBuilder.maxMessageSize(MAX_MESSAGE_SIZE), where MAX_MESSAGE_SIZE = 1GB 

Then if  client sends 500 MB object , will complete 1GB memory will be allocated or simply 500 MB memory will be allocated to the buffer ?

**Comment by yashykt** [comment]
Issues for grpc-java are tracked at https://github.com/grpc/grpc-java/issues
