### ISSUE TITLE
cancel_ares_query_test Failure

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#19880]
CancelDuringAresQuery
TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful

```
test/cpp/naming/cancel_ares_query_test.cc:365
Expected equality of these values:
  status
    Which is: 4
  expected_status_code
    Which is: 14
```
https://source.cloud.google.com/results/invocations/4a8493fd-7a1f-444c-9ea4-c41fb6b8af56/targets/%2F%2Ftest%2Fcpp%2Fnaming:cancel_ares_query_test@poller%3Dpoll/tests
Seen on #19865

**Comment by hcaseyal** [comment]
This is still flaking on master

**Comment by apolcyn** [comment]
Haven't yet had time to take a look but plan to in the next couple of days
