### ISSUE TITLE
macos/grpc_build_artifacts timeout

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#19898]
https://source.cloud.google.com/results/invocations/47b2cf5d-896a-4e35-82f4-f48f7d272b25/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log

```
checking for finite... yes
checking for flock... yes
checking for hypot... yes
checking for isinf... yes
checking for isnan...
ERROR: Aborting VM command due to timeout of 7200 seconds
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[14:27:46] Collecting build artifacts from build VM
Build script failed with exit code: 1
```

**Comment by markdroth** [comment]
Seeing a whole bunch of timeouts for mac artifact build in #21909:

https://source.cloud.google.com/results/invocations/293223a9-5fd4-4008-bc07-98b6a115f5b4/targets/github%2Fgrpc/tests;group=tasks;test=build_artifact.csharp_ext_macos_x64;row=1

**Comment by yashykt** [comment]
seen again - https://source.cloud.google.com/results/invocations/8b0688a2-7197-46c7-b55d-42ee8200a945/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log

**Comment by jtattermusch** [comment]
Seems state now.
