### ISSUE TITLE
channelz api not accessible in c# server

### ISSUE THREAD

**Issue by Kadajski** [grpc/grpc#19909]
### What version of gRPC and what language are you using?
 grpc.core 1.22.0 - C#
 
### What operating system (Linux, Windows,...) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 dotnet core 2.2
 
### What did you do?
Ran a grpc server which should have channelz api enabled by default in c-core #15986 and created a client that calls the server with [channelz.proto](https://github.com/grpc/grpc-proto/blob/master/grpc/channelz/v1/channelz.proto) on RPC `GetTopChannels` and got `Status(StatusCode=Unimplemented, Detail="")`
 
### What did you expect to see?
 The results for TopChannels implemented in c-core [channelz_service](https://github.com/grpc/grpc/blob/master/src/cpp/server/channelz/channelz_service.cc)
 
### What did you see instead?
 `Status(StatusCode=Unimplemented, Detail="")`
 
### Anything else we should know about your project / environment?
N/A

Seems like c# implementation has it's own set of services defined so is unaware of the service defined in c-core [see here](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Server.cs#L342). Is there a way for the c-core service to be exposed so that I can see all the same info as if my server was running in c++

**Comment by jtattermusch** [comment]
@karthikravis  am I right saying that since the channelz service is implemented in C++, there is no way of using it from any other language than C++?

**Comment by jtattermusch** [comment]
Still an issue.

**Comment by jtattermusch** [comment]
Since Grpc.Core is now in maintenance mode (see https://grpc.io/blog/grpc-csharp-future/), we don't plan to add any new feature.
