### ISSUE TITLE
Xcode build error BoringSSL-GRPC "use of undeclared identifier 'SSL_get_secure_renegotiation_support'; did you mean 'GRPC_SHADOW_SSL_get_secure_renegotiation_support'?"

### ISSUE THREAD

**Issue by d2vydov** [grpc/grpc#19908]
### What version of gRPC and what language are you using?
Objective-C/Swift, gRPC is 1.19.0
 
### What operating system (Linux, Windows,...) and version?
 macOS 10.14.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Xcode 10.3, command line tools 10.3, toolchain - 10.3
 
### What did you do?

- Create an empty iOS project
- Add Podfile with `pod 'gRPC-Core', '1.19.0'`
- `$ pod install`
- trying to build project

### What did you expect to see?
 Compiles fine
 
### What did you see instead?
I've got an error: `/Users/denis/TestGRPC/Pods/BoringSSL-GRPC/ssl/t1_lib.cc:3224:9: Use of undeclared identifier 'SSL_get_secure_renegotiation_support'; did you mean 'GRPC_SHADOW_SSL_get_secure_renegotiation_support'?`

 
##### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.3 (18D42)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/denis/.rbenv/versions/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d876e83863fb65cb10cb7bbea32383c74b117ba6
```

##### Installation Source

```
Executable Path: /Users/denis/.rbenv/versions/2.5.0/bin/pod
```

##### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

##### Podfile

```ruby
platform :ios, '11.0'

target 'TestGRPC' do
  use_frameworks!

  pod 'gRPC-Core', '1.19.0'


  target 'TestGRPCTests' do
    inherit! :search_paths
  end

  target 'TestGRPCUITests' do
    inherit! :search_paths
  end

end
```

##### Podfile.lock
```
PODS:
  - BoringSSL-GRPC (0.0.3):
    - BoringSSL-GRPC/Implementation (= 0.0.3)
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Implementation (0.0.3):
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Interface (0.0.3)
  - gRPC-Core (1.19.0):
    - gRPC-Core/Implementation (= 1.19.0)
    - gRPC-Core/Interface (= 1.19.0)
  - gRPC-Core/Implementation (1.19.0):
    - BoringSSL-GRPC (= 0.0.3)
    - gRPC-Core/Interface (= 1.19.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.19.0)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)

DEPENDENCIES:
  - gRPC-Core (= 1.19.0)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - BoringSSL-GRPC
    - gRPC-Core
    - nanopb

SPEC CHECKSUMS:
  BoringSSL-GRPC: be3aaeecf82982187df61ccf8844f62ac75c1e32
  gRPC-Core: 8ce876480da74af2988f1466b8daa99b8f5c79bb
  nanopb: 9f8aa4fc4e9d32c345e927e12c7bd9c0ea088353

PODFILE CHECKSUM: df95a72cdc757624b9d86270a2b04a0837fa2c40

COCOAPODS: 1.7.5
```

### What am I already tried?
clean project, clean derived data, remove cocoapods cache, reboot, update repo and reinstall pods, delete pods folder, reinstall cocoapods, reinstall Xcode, etc :(

**Comment by d2vydov** [comment]
so, I tried to compile with other versions, there are results:

- 1.22.0 - **fails**
- 1.16.0 - **fails** 
- 1.13.0 - **works fine**

do somebody have ideas why this happening?

**Comment by muxi** [comment]
Do you have any instruction for us to reproduce this issue? We do not see this problem for now.

Also, one good thing to try is to build the hello world example in `/example/objective-c/helloworld`. That could help decide if the issue is in gRPC or your project.

**Comment by d2vydov** [comment]
I've just created new admin in my PC and all works fine now.

I think the problem is a lot of redefines `SSL_get_secure_renegotiation_support` without `#ifdef` checks.

**Comment by d2vydov** [comment]
The issue should be closed, I think, but perhaps you can create issue for fix redefines with `#ifdef` checks?
