### ISSUE TITLE
Python channel close can deadlock when keepalive timeout happens

### ISSUE THREAD

**Issue by jpeel** [grpc/grpc#19910]
### What version of gRPC and what language are you using?
 1.17.1
 
### What operating system (Linux, Windows,...) and version?
 Linux 3.19.2.28437
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.5.3
 
### What did you do?
I connect to a device and send frequent (one or two per second) async requests with a deadline/timeout of 5 seconds. The keepalive time of the channel is set to be much less than the keepalive timeout of the channel. To make this bug more likely to happen, use a keepalive time of 1000 ms and a keepalive timeout of 3000 milliseconds. Then disconnect the device. When a keepalive exception is hit which happens pretty frequently, the close() method is invoked on the channel, but it deadlocks. A backtrace shows that it is waiting for the requests to be cleared out of the queue. I also put in code to keep track of the number of open requests and log when request callbacks are invoked. When the close() deadlocks, there are still open requests and the callbacks are never invoked.
 
### What did you expect to see?
 When a keepalive exception happens, all open requests should go into an error state and any new requests should be rejected or go into an error state. All requests should be cleared out of the completion queues properly so that the channel can be closed.
 
### What did you see instead?
A deadlock in the close() method of the channel because requests were never handled when a keepalive watchdog timeout was encountered.
 
### Anything else we should know about your project / environment?
If I set the keepalive time to larger than the keepalive timeout, then this issue doesn't happen because an "OS Error" happens instead. This is due to the TCP timeout which is set to match the keepalive timeout. When the TCP timeout pathway is encountered, requests appear to always be handled properly so that the channel's close() method can complete. I think that most users set the keepalive time longer than the keepalive timeout and this is what we are doing to work around the issue. However, this is clearly a bug in the keepalive watchdog timeout code. I believe the issue is in the core code. I think that comparing the two pathways of the keepalive watchdog timeout pathway vs. the TCP timeout pathway should help to find the problem.

I looked at all of the changes since 1.17.1 and don't see anything that addresses this issue as far as I can tell.

**Comment by jpeel** [comment]
I've been doing more research into this. The issue is that any unhandled exception in the callback of a grpc future in Python will kill the channel_spin thread. With the channel spin thread gone, the remaining requests will sit in the completion queue forever and the channel will not be able to close. The exception we were running into was a callback trying to do another async request (using the future method). This caused an exception because the channel is already closed, but it also ended up closing the processing thread for the integrated requests (async requests).

**Comment by gnossen** [comment]
This sounds pretty similar to https://github.com/grpc/grpc/issues/19973. And I think the fix should be pretty similar to https://github.com/grpc/grpc/pull/19988. Thanks for the research!
