### ISSUE TITLE
DefaultHealthCheckService not correctly serving

### ISSUE THREAD

**Issue by HunterLarco** [grpc/grpc#19927]
### What version of gRPC and what language are you using?
 version: 1.20.1
lang: C++
 
### What operating system (Linux, Windows,...) and version?
 operating system: Ubuntu (linux-gnu)
version: 18.04.3 LTS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 bazel 0.28.1
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```cc
int main(int argc, char** argv) {
  std::string server_address("0.0.0.0:8080");

  grpc::ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());

  grpc::EnableDefaultHealthCheckService(true);

  std::unique_ptr<grpc::Server> server(builder.BuildAndStart());
  std::cout << "Server listening on " << server_address << std::endl;
  server->Wait();
}
```
 
### What did you expect to see?

```
$ grpc_cli ls localhost:8080
> grpc.health.v1.Health

$ grpc_cli ls localhost:8080 grpc.health.v1.Health
> Check
> Watch

$ grpc_cli call localhost:8080 grpc.health.v1.Health.Check ""
> status: SERVING
```
 
### What did you see instead?

```
$ grpc_cli ls localhost:8080
> grpc.health.v1.Health

$ grpc_cli ls localhost:8080 grpc.health.v1.Health
> Service or method grpc.health.v1.Health not found.

$ grpc_cli call localhost:8080 grpc.health.v1.Health.Check ""
> Method name not found
> Failed to find method grpc.health.v1.Health in proto files.
> Method name not found
> Method name not found
> Failed to parse request.
```
 
### Anything else we should know about your project / environment?

No.

**Comment by yang-g** [comment]
This is sort of expected at the moment. We do not export the health check service in the same way as user-provided services because we do not want to add protobuf dependency. Thus the cli tool may not get the details of the health check service.

For a potential workaround for `grpc_cli call`, which I guess is a bit important, you may want to try setting the proto file directly using `--proto_path`, `--protofiles` and `--noremotedb`.
