### ISSUE TITLE
Running gRPC python with BUILD_WITH_SYSTEM_OPENSSL=1 flag.  How can I verify version of openSSL being used?

### ISSUE THREAD

**Issue by Andrew-Lev** [grpc/grpc#19953]
I am building grpc from source and attempting to use openssl instead of boringssl.
I run the build using
> GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 pip install ~/grpc

as per the [documentation](https://github.com/grpc/grpc/blob/master/setup.py).

```
# Export this variable to use the system installation of openssl. You need to
# have the header files installed (in /usr/include/openssl) and during
# runtime, the shared library must be installed
BUILD_WITH_SYSTEM_OPENSSL = os.environ.get('GRPC_PYTHON_BUILD_SYSTEM_OPENSSL',
                                           False)
```

Everything builds successfully: 
> Successfully installed grpcio-1.18.0

I am looking for some way to verify that openssl is indeed being used, and also what version of open ssl.  I have tried looking through the logs for any indication of this, but don't see any information that would be relevant.
I used the following two system variables - GRPC_VERBOSITY=DEBUG;GRPC_TRACE=all

While searching for info I came across this [file ](https://github.com/grpc/grpc/blob/v1.18.x/tools/openssl/use_openssl.sh)which seems to indicate that openssl 1.0.2f gets downloaded.  Is this the case here?  Could I modify this to use the system library dynamically?
```

# allow openssl to be pre-downloaded
if [ ! -e third_party/openssl-1.0.2f.tar.gz ]
then
  echo "Downloading https://openssl.org/source/old/1.0.2/openssl-1.0.2f.tar.gz to third_party/openssl-1.0.2f.tar.gz"
  wget https://openssl.org/source/old/1.0.2/openssl-1.0.2f.tar.gz -O third_party/openssl-1.0.2f.tar.gz
fi
```

### What version of gRPC and what language are you using?
1.18.0 Python
 
### What operating system (Linux, Windows,...) and version?
RHEL7 3.10.0 x86_64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.6.1
 Gcc && gcc-c++ 4.8.5

**Comment by lidizheng** [comment]
AFAIK, the script you are pointing is not used during the build process. The build is handled purely by Python's `setuptools`. If you are using `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1`, then it is already link to your system openssl.

**Comment by gnossen** [comment]
Luckily, [OpenSSL provides a function specifying their version as an integer](https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_VERSION_NUMBER.html) that you can inspect inside of the wheel. So, for example, if you wanted to check out the version statically linked into the `1.22.0` grpcio release, you could do
```bash
rbellevi@rbell:/tmp$ unzip grpcio-1.22.0-cp27-cp27m-manylinux1_x86_64.whl &>/dev/null && objdump -dS grpc/_cython/cygrpc.so | grep -A 5 OpenSSL_version_num
00000000001e7840 <OpenSSL_version_num>:
  1e7840:	b8 7f 00 10 10       	mov    $0x1010007f,%eax
  1e7845:	c3                   	retq   
  1e7846:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
  1e784d:	00 00 00 
```
As you can see, the function just returns `0x1010007f`, which, according to the version scheme linked above, maps to `1.1.0.7 release`.

**Comment by Andrew-Lev** [comment]
I tried what you suggested and see the same result in 1.18.  Looks like its also using version 1.1.0.7

```
unzip grpcio-1.18.0-cp36-cp36m-linux_x86_64.whl &>/dev/null && objdump -dS grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so | grep -A 5 OpenSSL_version_num
00000000001ac7b0 <OpenSSL_version_num>:
  1ac7b0:       b8 7f 00 10 10          mov    $0x1010007f,%eax
  1ac7b5:       c3                      retq
  1ac7b6:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)ex
  1ac7bd:       00 00 00
```

Is there a way to dynamically link this to use openssl from the system? I tried to build on a system that only has OpenSSL 1.0.2k-fips installed, but it still shows 1.1.0.7 so I'm assuming its statically linked.

**Comment by gnossen** [comment]
As of right now, our build system only supports statically linking OpenSSL because incurring a runtime dependency on `openssl` is against [the manylinux specification](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy). But pull requests are always welcome. `BUILD_WITH_SYSTEM_OPENSSL` was [added by an external contributor](https://github.com/grpc/grpc/pull/15548).

**Comment by Andrew-Lev** [comment]
I looked into this a bit more.  When I build with the OPENSSL flag I can see the openssl library in the .so and it appears to be linked to whatever is installed on my system at the time.
```

[root@af5ffbf53875 _cython]# ldd cygrpc.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007fff04bf5000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fa677cff000)
        **libssl.so.10 => /lib64/libssl.so.10 (0x00007fa677a8d000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fa67762b000)**
        libpython3.6m.so.1.0 => /lib64/libpython3.6m.so.1.0 (0x00007fa677143000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa676f27000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fa676c20000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa67691e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa676551000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa67832f000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fa676304000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fa67601b000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fa675e17000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fa675be4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fa6759e0000)
        libz.so.1 => /opt/SymantecDLP/Protect/lib/native/libz.so.1 (0x00007fa6757c3000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fa6755c0000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa6753aa000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fa67519a000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fa674f96000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fa674d7d000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fa674b56000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fa6748f4000
```

```
(smsEnviron) [root@af5ffbf53875 lib64]# ls -l libssl.so.10
lrwxrwxrwx 1 root root 16 Jul 19 20:08 libssl.so.10 -> libssl.so.1.0.2k
lrwxrwxrwx 1 root root 19 Jul 19 20:08 /lib64/libcrypto.so.10 -> libcrypto.so.1.0.2k
```

It seems like the objdump -dS grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so | grep -A 5 OpenSSL_version_num command is giving incorrect information ($0x1010007f,%eax), or am I confusing something?
