### ISSUE TITLE
Is there a way to use shared memory instead of socket on a local machine for rpc?

### ISSUE THREAD

**Issue by wanglzh** [grpc/grpc#19959]

**Comment by AspirinSJL** [comment]
Could you explain your question in more details?

**Comment by wanglzh** [comment]
we have a strict performance situation where two processes complete a RPC within 20 us, so if grpc support shared memory as a transport, that will be good, thanks for your answer !

**Comment by AspirinSJL** [comment]
If my understanding is correct, you have two processes on the same machine that are communicating with each other. So you want to use shared memory as a transport to optimize performance.

We don't currently support this though, sorry. But proposal and implementation is welcome if you want to contribute.

**Comment by AspirinSJL** [comment]
Please reopen if you have further question. Thanks!

**Comment by wanglzh** [comment]
It's exactly what you understand ! Do you have a plan to add such feature ?

**Comment by AspirinSJL** [comment]
Sorry, it's not on our plan. But community contribution is welcomed.

**Comment by wanglzh** [comment]
Well, thanks for your answer !

**Comment by linghudaxiao** [comment]
You can Apache Thrift. It does support what you want.

**Comment by wanglzh** [comment]
@linghudaxiao thanks, I will have a look at it.

**Comment by ethanjyx** [comment]
@wanglzh Did you end up using thrift later? We are also having a similar problem

**Comment by wanglzh** [comment]
@ethanjyx  Not yet, we are considering to use a single process app for our business.
