### ISSUE TITLE
Is there an example of a multi-threaded asynchronous server?

### ISSUE THREAD

**Issue by X-Crack** [grpc/grpc#19958]
My English is not very good, I hope to understand a lot.

I want to be able to get a multi-threaded, purely asynchronous server-side example.

The official C++ example is too small. I hope to give more examples.
thank you very much!!!!

**Comment by AspirinSJL** [comment]
https://github.com/grpc/grpc/tree/master/src/cpp/server/load_reporter is a complete example in production.
