### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error starting a batch of operations: 8'

### ISSUE THREAD

**Issue by phlippieb** [grpc/grpc#19963]
### What version of gRPC and what language are you using?

Objective-C, gRPC 1.22.0
 
### What operating system (Linux, Windows,...) and version?

Building on MacOS 10.14.6 (18G87)
Running on various iOS >= 12.0
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gRPC as installed by CocoaPods

gcc:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
 
### What did you do?

This crash sometimes occurs when a stream gets started. It looks like this might be specific to streams that were previously running, were then stopped, and are then started again.

The stream is stopped by doing this in a class that maintains a single protocall for a bi-di stream:

```
func stop() {
   func _stop() {
      if let protocall = self.protocall {
         self.protocallBeingStopped = protocall // Ensure the protocall is retained while it is stopped.
         protocall.cancel()
      }
      self.protocall = nil
   }

   self.startStopQueue.async {
      _stop()
   }
```

And it is started by doing this (simplified):
```
func start() {
   func _start() {
      self.writer = GRXBufferedPipe()
      self.protocall = self.setupProtocall(writer: self.writer, responseHandler: self.handleResponseFromStream(done:response:error:))
      self.protocall?.start()
   }

   self.startStopQueue.syncSafe {
      _start()
   }
}
```

So some points:
- Starting and stopping are synchronised on a serial dispatch queue to prevent overlap
- When stopping, the protocall is retained
- When started, a new protocall and request writer is created
 
### What did you expect to see?

No crashes
 
### What did you see instead?

The following crash:

```
2019-08-15 15:21:53.292937+0200 DEVELOPMENT[60358:2318636] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error starting a batch of operations: 8'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001166ca6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011557dac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001166ca482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000110793927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   GRPCClient                          0x0000000110394918 -[GRPCWrappedCall startBatchWithOperations:errorHandler:] + 1512
	5   GRPCClient                          0x000000011037f6b1 -[GRPCCall finishRequestWithErrorHandler:] + 417
	6   GRPCClient                          0x000000011037f80b __36-[GRPCCall writesFinishedWithError:]_block_invoke + 43
	7   libdispatch.dylib                   0x000000011959bccf _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000011959cd02 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00000001195a3720 _dispatch_lane_serial_drain + 705
	10  libdispatch.dylib                   0x00000001195a4261 _dispatch_lane_invoke + 398
	11  libdispatch.dylib                   0x00000001195acfcb _dispatch_workloop_worker_thread + 645
	12  libsystem_pthread.dylib             0x000000011997e611 _pthread_wqthread + 421
	13  libsystem_pthread.dylib             0x000000011997e3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

This occurs occasionally in various user journeys, but I can reproduce it almost consistently in one particular case, where it seems like we're mostly just rapidly polling the state of the stream, without doing any starts or stops. In that case, the app shows a system permission dialog for notifications (so technically the app becomes inactive). As soon as the dialog is dismissed, the above crash occurs.
 
### Anything else we should know about your project / environment?

There are many (probably >10) of these streams running simultaneously, some of which may be dealing with fairly high throughput.

**Comment by phlippieb** [comment]
Update: I removed all polling of the state of the protocall and of the writer. It had no effect -- the crash still occurs.

**Comment by muxi** [comment]
> It looks like this might be specific to streams that were previously running, were then stopped, and are then started again.

The state transition of a call does not support "started again" : 
```
NotStarted -> Started <-> Paused -> Finished
```

**Comment by phlippieb** [comment]
Ok, that makes sense. But our `start` method should always create a new protocall and writer, so it should be impossible for our code to actually try and go from finished to started on a single protocall/writer pair, at least explicitly. I'll have a debug this week and confirm that that's the case.

That also makes me think that perhaps an invalid state transition is happening accidentally. Our most reliable repro case is when the app is temporarily backgrounded to show a system popup. Perhaps when this happens, the state transitions to finished automatically? Which would then cause an invalid transition when it tries to resume when the app is foregrounded again. If that is the case, I might be able to create a simple repro app. I'll investigate and come back to you.

**Comment by phlippieb** [comment]
Hi @muxi, I have recently updated to Xcode11 / iOS13, and have not been able to replicate the crash in the new environment. So I'm closing this issue. Thanks for your feedback!
