### ISSUE TITLE
C++:Custom verification of server certificate from client side

### ISSUE THREAD

**Issue by sujiths** [grpc/grpc#19962]
### What version of gRPC and what language are you using?
 1.20.0, C++
 
### What operating system (Linux, Windows,...) and version?
 MacOS Mojave (10.14.5)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Apple LLVM version 10.0.1 (clang-1001.0.46.4)
 
Is there a way currently to let the certificate verification be done by OS apis rather than grpc doing it internally using OpenSSL?
**grpc_ssl_credentials_create** is taking **verify_peer_options** as an argument which contains a call back but **SslCredentialsOptions** is not exposing this.  Also **grpc_ssl_credentials_create** seems to be deprecated. 
Is there any other way for the client to receive server certificate and verify it during hand shake?
 
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yihuazhang** [comment]
@sujiths  Sorry for the late response. I am a little confused about what you want to achieve. Especially "Is there any other way for the client to receive server certificate and verify it during hand shake?" and your concern about "verify_peer_options" do not indicate the same thing. Because client will always validate server's certificate during the handshake, and the callback specified in "verify_peer_options" will be carried out after the handshake completes, which further checks about server's identity with its certificate.

**Comment by sujiths** [comment]
Thanks @yihuazhang 
I was looking for a way to receive the server certificate during the handshake and use the OS APIs to verify certificate instead of grpc doing it via OpenSSL. Like Security Framework APIs in OSX and wincrypt.h APIs in Windows. Since OpenSSL wont read the OS Trust stores in any of these platforms, deployments have to package the root certificate(roots.pem) along with the software or enumerate the OS trust store and fill SSLCredOptions.pem_root_certs. It would have been better if grpc use the OS APIs to verify the certificate or let the client code do the verification using whatever they deem fit (OpenSSL or OS APIs)

Now I am enumerating the trust store in each platform(win, osx, etc) and filling the SSLCredOptions.pem_root_certs. So my problem is solved but still this is good to have feature if you don't mind offloading this security feature to client code.

**Comment by yashykt** [comment]
I was about to close the issue since it is marked as kind/question. But, seems like it is actually a feature request. I am going to change the label to reflect this, so that it can be picked up.

**Comment by sujiths** [comment]
Thanks @yashykt.

**Comment by yashykt** [comment]
Unfortunately, doesn't look like anyone picked this up so I'm going to keep it closed as mentioned in the guidelines but I'm going to mark this as "help wanted" for future work if interest rises.

**Comment by sujiths** [comment]
Thanks @yashykt. Right now our problem is fixed via enumerating store and filling SSLCredOptions.pem_root_certs. It is working fine on all platforms. But it is a long path for a small problem.
