### ISSUE TITLE
would anyone share an example of grpc reload certificate in C++?

### ISSUE THREAD

**Issue by roy-xu709** [grpc/grpc#19972]
### What version of gRPC and what language are you using?
 1.16.0 (if not support reloading certificate, the newest version is also ok)
 
### What operating system (Linux, Windows,...) and version?
 linux
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 an example of reloading certificate without restarting in c++
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yihuazhang** [comment]
Sorry for the late response. In SSL stack, we currently do not provide a C++ API for doing credential reload (it is possible in C-core with `grpc_ssl_server_credentials_create_options_using_config_fetcher`). However in TLS stack, we provide a C++ API to do the reload and you can find an example in https://github.com/grpc/grpc/pull/20568 (WIP).
