### ISSUE TITLE
"grpcsharp_native_callback_dispatcher_init" exception when create new Channel()

### ISSUE THREAD

**Issue by Inspekt2** [grpc/grpc#19983]
### What version of gRPC and what language are you using?
 Unity package 2.24.0-dev
 C#
 Error exists for all packages after 1.18.0 version.

### What operating system (Linux, Windows,...) and version?
 MacOS 10.14.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 osx runtime inside the unity package.
 
### What did you do?
`Channel channel = new Channel(_channelTarget, ChannelCredentials.Insecure);`
 Error occurs on this line.

### What did you expect to see?
 Execution without errors.
 
### What did you see instead?
"grpcsharp_native_callback_dispatcher_init" exception in the new Channel() line.
It works good for Windows build. Error occurs for Mac and Ios builds.
 
```
EntryPointNotFoundException: grpcsharp_native_callback_dispatcher_init
Grpc.Core.Internal.NativeCallbackDispatcher.Init (Grpc.Core.Internal.NativeMethods native) (at T:/src/github/grpc/src/csharp/Grpc.Core/Internal/NativeCallbackDispatcher.cs:45)
Grpc.Core.Internal.NativeExtension..ctor () (at T:/src/github/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:47)
Grpc.Core.Internal.NativeExtension.Get () (at T:/src/github/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:65)
Grpc.Core.Internal.NativeMethods.Get () (at T:/src/github/grpc/src/csharp/Grpc.Core/Internal/NativeMethods.cs:49)
Grpc.Core.GrpcEnvironment.GrpcNativeInit () (at T:/src/github/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:373)
Grpc.Core.GrpcEnvironment..ctor () (at T:/src/github/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:302)
Grpc.Core.GrpcEnvironment.AddRef () (at T:/src/github/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:78)
Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials, System.Collections.Generic.IEnumerable`1[T] options) (at T:/src/github/grpc/src/csharp/Grpc.Core/Channel.cs:70)
Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials) (at T:/src/github/grpc/src/csharp/Grpc.Core/Channel.cs:55)
Helloworld.Example.Awake () (at Assets/Scripts/Example.cs:17)
```
 
### Anything else we should know about your project / environment?
Unity 2018.10.3f1
There was the same issue, but it was closed.
[https://github.com/grpc/grpc/issues/18593](url)

**Comment by briceio** [comment]
Any progress on this? Same issue here and starting to be painful for any iOS-runtime GCP developments.

**Comment by minhdtb** [comment]
I got the same issue. How to resolve it?

**Comment by briceio** [comment]
After looooong hours I find the solution, not perfect but I guess the only one. Seems like the dependency isn't injected at the right place in the compiled macOS binary.

Once the binary is generated:
- Right click on it with the Finder and select "Display the content of the package"
- Navigate to Contents/Plugins

Here you'll see that **grpc_csharp_ext.bundle** is in the **x86_64** subfolder (Content/Plugins/x86_64) but it shouldn't be here. **Just move it to Content/Plugins**.

And you're done. You have to do this each time you generate the binary...

**Comment by markdroth** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by jtattermusch** [comment]
I will look into the info provided in https://github.com/grpc/grpc/issues/19983#issuecomment-601755521.

Update: I don't see anything wrong the location of `grpc_csharp_ext.bundle` here: https://github.com/grpc/grpc/blob/791729d09ffb227d739fdb17c89502fc14b5870a/src/csharp/build_unitypackage.bat#L54 (the bundle is placed based on whether it's 32bit or 64bit build).
