### ISSUE TITLE
npm rebuild fatal error: address_sorting/address_sorting.h: No such file or directory

### ISSUE THREAD

**Issue by Jeff-Tian** [grpc/grpc#19996]
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by Jeff-Tian** [comment]
Sorry I just try to search relative issues but accidentally hit the `enter` key and the empty issue was just created.

**Comment by eouia** [comment]
Is it solved?

**Comment by Jeff-Tian** [comment]
By fixing the version to 1.21.1

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
