### ISSUE TITLE
Error in C++ Version Installation

### ISSUE THREAD

**Issue by qiuxin** [grpc/grpc#19997]
I follow the instruction from the installation link:   https://github.com/grpc/grpc/blob/master/BUILDING.md

Encounter the following errors, some help! Many thanks in advance!

root@parallels-Parallels-Virtual-Platform:/usr/local/grpc# bazel build :all
ERROR: /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/io_bazel_rules_python/python/pip.bzl:39:25: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/io_bazel_rules_python/python/pip.bzl", line 37
		repository_rule(attrs = {"requirements": attr.la...")}, ...)
	File "/root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/io_bazel_rules_python/python/pip.bzl", line 39, in repository_rule
		attr.label(allow_files = True, mandatory = Tr..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: error loading package '': Extension file 'python/pip.bzl' has errors
ERROR: error loading package '': Extension file 'python/pip.bzl' has errors
INFO: Elapsed time: 0.283s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

root@parallels-Parallels-Virtual-Platform:/usr/local/grpc# bazel build :all --incompatible_disable_deprecated_attr_params=false
Killed non-responsive server process (pid=29096)
Starting local Bazel server and connecting to it...
DEBUG: Rule 'org_pubref_rules_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "1623a5a083f2a702bd62692d059353b4e06f3a5e", shallow_since = "1532967846 +0000" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'org_pubref_rules_protobuf' which is a git_repository (rule definition at /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /usr/local/qiuxin/grpc/WORKSPACE:54:1
ERROR: /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl:771:21: name 'FileType' is not defined
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/org_pubref_rules_protobuf/python/rules.bzl: in /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/org_pubref_rules_protobuf/protobuf/rules.bzl: Extension 'protobuf/internal/proto_compile.bzl' has errors
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/org_pubref_rules_protobuf/python/rules.bzl: in /root/.cache/bazel/_bazel_root/416e294999b2f0ca85243bb61458d7d2/external/org_pubref_rules_protobuf/protobuf/rules.bzl: Extension 'protobuf/internal/proto_compile.bzl' has errors
INFO: Elapsed time: 35.712s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by JoneJay** [comment]
Me too！

**Comment by mciancia** [comment]
Same problem here :(

**Comment by markdroth** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
