### ISSUE TITLE
gRPC Testing Failure - AppVerifier Heaps test

### ISSUE THREAD

**Issue by JonathanMcDevitt** [grpc/grpc#20005]
### What version of gRPC and what language are you using?

C++ 1.20.1

### What operating system (Linux, Windows,...) and version?

Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)

VS 140

### What did you do?

1. Set up AppVerifier to run on tests for creating a read session. In AppVerifier:
   1. Go to File->Add Application; select the executable for running the aforementioned tests
   2. Under the Tests window
      1. Deselect Basic
      2. Select Basic->Heaps
2. Run your test executable

### What did you expect to see?

Tests run successfully regardless of whether AppVerifier is instrumenting.

### What did you see instead?

Test crashes with access violation when referencing `GrpcPolledFdWindows* polled_fd->gotten_into_driver_list()` from `SockToPolledFdMap::CloseSocket` definition (grpc_ares_ev_driver_windows.cc). See attached screenshot.

### Anything else we should know about your project / environment?

Please find below a screenshot with the stack. The lead-in code to creating the read session is viewable there as well. Please see [the AppVerifier documentation][1] for details on the AppVerifier Heaps test.

![gRPC_AppVerifier_Failure_Heaps_StackSnapshot][2]*Stack Snapshot and CreateReadSession Lead-In Code*

[1]: https://docs.microsoft.com/en-us/windows/win32/win7appqual/application-verifier
[2]: https://user-images.githubusercontent.com/50157372/63371455-feaf5880-c338-11e9-8238-873229b0f240.png

**Comment by jtattermusch** [comment]
does this issue have a similar rootcause as  https://github.com/grpc/grpc/issues/18461?(unconfirmed).

@apolcyn  based on the stacktrace this is ares-related.

**Comment by apolcyn** [comment]
See #18461 for related followup

**Comment by JonathanMcDevitt** [comment]
Hi apolcyn,

Thanks for getting on this! Do we know which release label/tag of gRPC this will be made available in? We are currently blocked on releasing to customers until we can get this fix, and I would prefer to ensure that everything is stable together than check out particular commits and risk an instability in the label. There is already one such issue with 1.24.x and protobuf for which we've had to do something similar. I had a look at the commit from https://github.com/grpc/grpc/pull/20274 and it's currently only in master.

Thanks,
~Jon

**Comment by jtattermusch** [comment]
@JonathanMcDevitt  we have a 6weekly release cadence: https://github.com/grpc/grpc/blob/master/doc/grpc_release_schedule.md (in this case it seems we missed the 1.24.x branch cut, so it's going to be released with 1.25.x which corresponds to 2.25.x for C#).

**Comment by JonathanMcDevitt** [comment]
Hi @jtattermusch,

We've done some testing and the fix addresses our crash. Thanks a lot!

~Jon
