### ISSUE TITLE
Error  assertion failed: g_state != nullptr

### ISSUE THREAD

**Issue by kanagunbr** [grpc/grpc#20034]
I am creating two channels. one to connect to spanner and another for pubsub. Both will be running in a single threaded process.  However, The Second CreateChannel command always fails with the error message ""E0822 14:58:29.720362062   82737 resolver_registry.cc:215]   assertion failed: g_state != nullptr".  When I comment one, the other will be successful. the g_state variable get initialized when the first CreateChannel function is executed, but before the second CreateChannel command, the pointer become null. 

void CreateSpannerChannel()
{
	auto creds = grpc::GoogleDefaultCredentials();	
	m_channel = grpc::CreateChannel("spanner.googleapis.com", creds);
}

void CreatePubSubChannel()
{
	auto creds = grpc::GoogleDefaultCredentials();	
	m_channel = grpc::CreateChannel("pubsub.googleapis.com", creds);
}

void main()
{
     CreateSpannerChannel();
     CreatePubSubChannel(); // This fails with the assertion. If I comment the 
                                              // CreateSpannerChannel, this line is successful
}

### What version of gRPC and what language are you using?
v1.23.0

### What operating system (Linux, Windows,...) and version?
Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by kanagunbr** [comment]
This is based on the GRPC release v1.23.0

**Comment by AspirinSJL** [comment]
This seems like a easy-to-debug bug. Could you please provide a minimal reproduction code?

**Comment by kanagunbr** [comment]
I actually call these functions from Node Modules (NAPI). There are two separate modules (pubsub & Spanner) and thus two separate DLLs (pubsub.node & spanner.node). It seems the dependency of GRPC static/global variables between two dlls causing this issue. Not sure how to solve but I didn't have this issue in the earlier version of GRPCs. I need to debug further. I will update the findings here.

**Comment by kanagunbr** [comment]
When I combined all the calls into single module, everything started working. As I have the workaround, I am find in closing the defect. However, if you want to pursue this defect further, I can help.

**Comment by AspirinSJL** [comment]
I see. I don't have any good idea about improving the singleton pattern here to avoid this issue. But let's try to revamp it if more people are faced with this issue.

**Comment by raulchen** [comment]
Hi @AspirinSJL and @kanagunbr. I‘m seeing the exactly same problem. My python program loads two SO libraries, both of which contains grpc. When I use grpc in the second lib, I'll get `assertion failed: g_state != nullptr`. 

Do you know how to work around this issue? Or do you know which older version doesn't have this bug? I'm using 1.21.4. Thanks.

**Comment by vlasenkoalexey** [comment]
Spent few days chasing down this issue, and it might potentially cause a lot of pain to TensorFlow users. All TensorFlow operators implemented in C++ are built as a shared libraries like this one: https://github.com/tensorflow/io/blob/master/tensorflow_io/bigquery/BUILD 
Whenever 2 different libraries using grpc and loaded into one process, calls to grpc::CreateChannel in a library that is loaded second will fail. For users it is going to look like some working code started crashing, and such issue is going to be pretty hard to debug. 

The repro is simple: 
git clone https://github.com/tensorflow/io.git
Build as described here: https://github.com/tensorflow/io#python

From docker container, run 2 tests for libraries using grpc:
python  -m pytest -v tests/test_grpc_eager.py tests/test_bigquery_eager.py
Test will crash. If you run tests separately they will succeed.

I'd suggest bumping issue priority to P1.

**Comment by AspirinSJL** [comment]
Raising to P1 because it's hitting multiple users and it's a crash.

**Comment by AspirinSJL** [comment]
From my understanding after offline discussion with @veblush , this linking issue happens when gRPC is used as a library in an unexpected way. 

Reassigning to @veblush .

**Comment by veblush** [comment]
@vlasenkoalexey Thank you for the steps on how to reproduce it. But it seems I cannot do it and test result is

```
(tfio-dev) root@veblush:/v# python -m pytest -v tests/test_grpc_eager.py tests/test_bigquery_eager.py
================================= test session starts =================================
platform linux -- Python 3.6.9, pytest-5.2.1, py-1.8.0, pluggy-0.13.0 -- /miniconda/envs/tfio-dev/bin/python
cachedir: .pytest_cache
rootdir: /v
collected 4 items                                                                     

tests/test_bigquery_eager.py::BigqueryOpsTest::test_fake_server PASSED          [ 25%]
tests/test_bigquery_eager.py::BigqueryOpsTest::test_parallel_read_rows PASSED   [ 50%]
tests/test_bigquery_eager.py::BigqueryOpsTest::test_read_rows PASSED            [ 75%]
tests/test_bigquery_eager.py::BigqueryOpsTest::test_session SKIPPED             [100%]

================================== warnings summary ===================================
/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15
  /miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
====================== 3 passed, 1 skipped, 1 warnings in 1.88s =======================
```

I expected it would crash but it didn't.

**Comment by vlasenkoalexey** [comment]
This is because in order to mitigate this issue for tensorflow-io @yongtang has moved all ops using grpc under one library, see https://github.com/tensorflow/io/pull/545.

In order to repro grpc issue, sync to the commit before that like git checkout 954ee240ee6d2c9823bae9cd927ceceafb7edd37 and rebuild.
I just confirmed that I can repro issue this way.
And thanks for looking into this.

**Comment by LostVector** [comment]
Having the same issue. We are currently testing grpc inside a dynamically loaded module.  When we load a new revision of our plugin, we encounter the same assertion causing everything to crash.

**Comment by LostVector** [comment]
I believe I managed to work around the issue in my own project by explicitly called grpc_init and grpc_shutdown.  After reading through the code, it seems many samples implicitly initialize grpc, so you wouldn't necessarily know to do this.  The comments also say calling those functions is required, so it's puzzling that example code doesn't seem to do it.

**Comment by vlasenkoalexey** [comment]
I tried calling grpc_init when debugging this, but it crashed later when connecting to the channel.

**Comment by excorearchitect** [comment]
I'd like to report the same issue. I'm using v1.25.0. In my case, I'm getting assertion error every time when using grpc client from the shared library while the same code works properly if compiled as executable. Unfortunately, I have to use shared library in order to integrate it with other components. I run it on Centos 7/g++ 7.4. Please let me know if any upcoming fixes or updates.

**Comment by ebrevdo** [comment]
The problem seems closely related to the ResolverRegistry having static state, essentially set at link-time:

https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/resolver_registry.h#L34

And the various plugins being re-registered in .so because grpc_init is called e.g. [here](https://github.com/grpc/grpc/blob/568f490aef0dc0bbddd767ea2cd687b6ab241d0c/src/cpp/client/secure_credentials.cc#L98) and the std::atomic (or whatever it is) [g_basic_init](https://github.com/grpc/grpc/blob/master/src/core/lib/surface/init.cc#L127) is not shared by the different .so files.

**Comment by ebrevdo** [comment]
Followup: gpr_once is a [pthread_once_t](https://github.com/grpc/grpc/blob/db38d4ca9b7684e9793a8b5edd626ed8d3f76d1b/include/grpc/impl/codegen/sync_posix.h#L48); which sounds similar to [absl::once_flag](https://github.com/abseil/abseil-cpp/blob/master/absl/base/call_once.h#L77); either way, it's not clear that these kinds of flags are safe to use when multiple DSOs link your library.

**Comment by spxcds** [comment]
I got the same issue in grpc1.20.0.

**Comment by yashykt** [comment]
@veblush Any update on this? (Pinging since this has been marked as a P1 bug.)

**Comment by veblush** [comment]
Changing the priority back to P2 because I believe this only happens with customized gRPC which happens to have multiple gRPC libraries, which violates ODR issue. Since we fixed the our-own ODR problem a few months ago, this shouldn't be a problem for users which simply rely on gRPC libraries.

**Comment by ebrevdo** [comment]
Issues like these were resolved in Reverb by being very careful about what
symbols our .so libraries exposed (among other tricks we had to use):
we generate
and use
<https://github.com/deepmind/reverb/blob/master/reverb/cc/platform/default/build_rules.bzl#L430>
a version_script (lds) file that only exports init symbols.

**Comment by jarivk** [comment]
I got around this issue by stripping the symbols from all the shared libraries which were making GRPC calls. Kept only the required symbols visible from shared libararies.

**Comment by xiay-nv** [comment]
> Changing the priority back to P2 because I believe this only happens with customized gRPC which happens to have multiple gRPC libraries, which violates ODR issue. Since we fixed the our-own ODR problem a few months ago, this shouldn't be a problem for users which simply rely on gRPC libraries.

Which version was ODR issue fixed in?

**Comment by veblush** [comment]
@xiay-nv https://github.com/grpc/grpc/pull/21662 is the one to fix it. I don't remember which version was the oldest one with this PR but I guess 1.28 or later should have it.
