### ISSUE TITLE
'@build_bazel_rules_swift' could not be resolved

### ISSUE THREAD

**Issue by LoveJuzi** [grpc/grpc#20042]
I meet a problem when I want to use bazel build the project that is reference the grpc library. The WORSPACE content is as follow:

```bazel
git_repository(
    name = "com_github_grpc_grpc",
    remote = "https://github.com/grpc/grpc.git",
    tag = "v1.20.0",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```
My building error is as follow:

```txt
ERROR: Skipping ':all': while parsing ':all': error loading package '': in /home/juzi/.cache/bazel/_bazel_juzi/1e8133fe9124757d871aca576252130a/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/juzi/.cache/bazel/_bazel_juzi/1e8133fe9124757d871aca576252130a/external/build_bazel_rules_apple/apple/ios.bzl: in /home/juzi/.cache/bazel/_bazel_juzi/1e8133fe9124757d871aca576252130a/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl: in /home/juzi/.cache/bazel/_bazel_juzi/1e8133fe9124757d871aca576252130a/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl: Unable to find package for @build_bazel_rules_swift//swift:swift.bzl: The repository '@build_bazel_rules_swift' could not be resolved
```

My OS system is Manjaro 18.04. My bazel version is bazel 0.20.0.

Is this a bug?

**Comment by ola-rozenfeld** [comment]
Reproduces for me as well with gRPC 1.24.0 and Bazel 0.29.1 on Linux when I tried to migrate the https://github.com/bazelbuild/remote-apis repository to the latest gRPC.
Btw, we're not using Swift and would really like an option to not pull in Swift dependencies. We use a version of `switched_rules_by_language` macro to enable this for our API.

**Comment by thibault-martinez** [comment]
Having the exact same issue, any news on this ?

**Comment by tony84727** [comment]
Does this help? https://github.com/grpc/grpc/pull/20586#issuecomment-546182904

**Comment by ola-rozenfeld** [comment]
Yes, it does, thank you!

**Comment by ola-rozenfeld** [comment]
Although, using the grpc_extra_deps leads to a different problem with Bazel 1.0's switch to incompatible_load_proto_rules_from_bzl (https://github.com/bazelbuild/bazel/issues/8922)
I narrowed the problem down to:

```
load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
api_dependencies()
```

Not sure yet why, but this causes simple `proto_library` rules to stop building.

**Comment by ola-rozenfeld** [comment]
Another thing: not sure why, but I need to load the `bazel_skylib` repository separately:

```
http_archive(
    name = "bazel_skylib",
    sha256 = "97e70364e9249702246c0e9444bccdc4b847bed1eb03c5a3ece4f83dfe6abc44",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.2/bazel-skylib-1.0.2.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.2/bazel-skylib-1.0.2.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
```

Ideally, this would be part of `grpc_deps`, right?

**Comment by ustiugov** [comment]
Dear developers, I would really appreciate if you could include the two lines, mentioned in [#20586 (comment)](https://github.com/grpc/grpc/pull/20586#issuecomment-546182904),  to [README](https://github.com/grpc/grpc/blob/master/src/cpp/README.md).
```
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
```

Without them build that depends on GRPC just does not work. Tested with C++, v1.27.1.

Also, the community would definitely value that if there was a complete example of how-to-build a project that depends on GRPC with bazel.
