### ISSUE TITLE
WritesPerRpcTest.UnaryPingPong Fails on Mac

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#20096]
```
2019-08-27 14:39:05,165 FAILED: bins/opt/writes_per_rpc_test --gtest_filter=WritesPerRpcTest.UnaryPingPong  GRPC_POLL_STRATEGY=poll
```

https://source.cloud.google.com/results/invocations/75c63dae-0f8f-4b47-b9a0-f4e75a2e3a6c/log

**Comment by jtattermusch** [comment]
I'm seeing this on almost every PR now

**Comment by jtattermusch** [comment]
Is this a dupe of https://github.com/grpc/grpc/issues/19819?
