### ISSUE TITLE
Make grpc inside generated code private

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20132]
I have observed users directly using the `grpc` module from the generated code in their application. I think this is unintended behavior, and should be stopped.

```Python
from foo import bar_pb2_grpc

channel = bar_pb2_grpc.grpc.insecure_channel('localhost:23333')
```

**Comment by gnossen** [comment]
Do you have any examples of this?

I don't think we can prevent this. I think the best we can do is discourage it with something like `import grpc as _grpc` in the generated code.
