### ISSUE TITLE
How to compile c++ grpc for android platform ?

### ISSUE THREAD

**Issue by mangorui** [grpc/grpc#20143]
I am not familiar with cmake, have a lot of information, but have not figured out how to compile the android version of the c++ library, can you provide a compilation guide? 

    Thank you！

**Comment by dapengzhang0** [comment]
Although we have grpc c++ Android build for testing compatibility, Android is not officially supported by grpc C++. Also, your question seems more of how to build c++ for Android in general, not grpc specific. You may take a look at our example https://github.com/grpc/grpc/tree/master/examples/android/helloworld which has cpp in src directory.
