### ISSUE TITLE
grpc client how to use server's hostname alias

### ISSUE THREAD

**Issue by ankit0706** [grpc/grpc#20153]
Hi all, I am using gRPC for my client/server. This is about using the server's hsotname at client side code. At server side I used the following code connecting to the service

public static NettyChannelBuilder.forAddress(String host, int port)

Earlier we used the actual hostname and it worked but now we are aked to use alias.
 the alias name when put in the same code does not work and I get the error
 No name matching found....

How to use the alias name in grpc client code to connect.

**Comment by mhaidrygoog** [comment]
Needs more information. Could you please post a code sample and your inputs as well as the error logs you receive. This will help in providing in more context and resolving any potential issues. Thanks for filing the issue.

**Comment by mhaidrygoog** [comment]
Closing after awaiting response
