### ISSUE TITLE
Add C# wrapper for SPIFFE credentials

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#20157]
We intend to use short-lived dynamic certificates in our application. Since the SPIFFE security stack was already added since version 1.20.0, we would love to rely on it.

This is related to #19778 which will add the wrappers to C++.

**Comment by sagva123** [comment]
ling c#

**Comment by jtattermusch** [comment]
@jiangtaoli2016  what is the C-core credentials object to wrap?

**Comment by Falco20019** [comment]
This is the gRFC: https://github.com/grpc/proposal/pull/98

**Comment by jiangtaoli2016** [comment]
@jtattermusch Could you help us wrap in C#? Our team does not have expertise.

**Comment by jtattermusch** [comment]
> @jtattermusch Could you help us wrap in C#? Our team does not have expertise.

What are the types to wrap and what is approximately the intended API? (I can make adjustments for C# idiomacity etc).

**Comment by Falco20019** [comment]
Please keep alive

**Comment by jtattermusch** [comment]
@jiangtaoli2016  what is the API to wrap?

**Comment by Falco20019** [comment]
Any news on any method of reloading credentials?

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/15502

**Comment by Falco20019** [comment]
Ok, I will wait for the gRFC to be finalized. I assume, once that's finalized, I might pick it up.

**Comment by jiangtaoli2016** [comment]
@Falco20019 @jtattermusch We are working on revising the SPIFFE/TLS credential Core API. It will be simple to wrap to support credential reloading. But it will take 1-2 quarter to complete.

**Comment by sagva123** [comment]
It can wrapped up by the C api ,use the C class wrapper tool to wrap up the
function and also use the same api which is present
