### ISSUE TITLE
GCC 8 issues for v1.22.0

### ISSUE THREAD

**Issue by baicaixmj** [grpc/grpc#20154]
### What version of gRPC and what language are you using?
v1.22.0

### What operating system (Linux, Windows,...) and version?
Linux centos6u3

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 8.2.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I change the branch of protobuf v3.7.1 , gflags v2.2.2 by edit branch in file .gitmodules and run "git submodule update --remote third_party/protobuf" and "git submodule update --remote third_party/gflags"

### What did you see instead?
src/cpp/server/channelz/channelz_service.cc: In function ‘grpc::protobuf::util::Status grpc::ParseJson(const char*, grpc::protobuf::Message*)’:
src/cpp/server/channelz/channelz_service.cc:30:11: error: ‘struct google::protobuf::util::JsonParseOptions’ has no member named ‘case_insensitive_enum_parsing
   options.case_insensitive_enum_parsing = true;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by nicolasnoble** [comment]
Should be gone now.

**Comment by klmr** [comment]
@nicolasnoble Could you point me to the commit(s) that fixes this? I’m locally dependent on a copy that branches off from v1.22.0, and I’m unable to find the fix in the commits that happened between 3 Sept and your message.

**Comment by LockLi** [comment]
> @nicolasnoble Could you point me to the commit(s) that fixes this? I’m locally dependent on a copy that branches off from v1.22.0, and I’m unable to find the fix in the commits that happened between 3 Sept and your message.

same problem while complie.
it looks like json_util.h in third_party can't be included.

**Comment by wenerme** [comment]
got the same error for 1.25.0

```
gcc --version
gcc (Alpine 8.3.0) 8.3.0
```

```
third_party/protobuf/src: warning: directory does not exist.
third_party/protobuf/src: warning: directory does not exist.
[AR]      Creating /build/aports/community/grpc/src/grpc-1.25.0/libs/opt/libgrpc++_error_details.a
src/cpp/server/channelz/channelz_service.cc: In function 'grpc::protobuf::util::Status grpc::ParseJson(const char*, grpc::protobuf::Message*)':
src/cpp/server/channelz/channelz_service.cc:30:11: error: 'struct google::protobuf::util::JsonParseOptions' has no member named 'case_insensitive_enum_parsing'
   options.case_insensitive_enum_parsing = true;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by wenerme** [comment]
after using the newest protobuf，problem solved
