### ISSUE TITLE
//test/cpp/end2end:xds_end2end_test@poller=poll times out

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#20163]
```
//test/cpp/util:time_test@poller=poll                                    PASSED in 14.8s
//test/cpp/end2end:xds_end2end_test@poller=poll                         TIMEOUT in 465.6s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-dbg/testlogs/test/cpp/end2end/xds_end2end_test@poller=poll/test.log
```

https://source.cloud.google.com/results/invocations/e645c3b3-c4e2-4ed5-8ff2-f3aedc647deb/log

**Comment by apolcyn** [comment]
Possibly related unavailable error in `BackendsRestart` test in https://source.cloud.google.com/results/invocations/309d8d97-27d6-479b-9721-50cfff4ac069/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Dpoll/tests

seen in PR: https://github.com/grpc/grpc/pull/20447

**Comment by jtattermusch** [comment]
Likely fixed by https://github.com/grpc/grpc/pull/21274
