### ISSUE TITLE
Implement lock-free delayed callbacks

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2016]

**Comment by vjpai** [comment]
I'd like to take this; I think there are some data structure tricks that will be fine here. Correct me if I'm wrong, but there's no requirement for ordering among delayed_cbs, is there? They're currently maintained as a FIFO, but I think there is no semantic reason for imposing that.

**Comment by vjpai** [comment]
Fun fact: allow_synchronous_callbacks is always false. This doesn't cost any locks but it does force an extra (highly-predictable) branch.

**Comment by ctiller** [comment]
I don't think there are: the easy experiment is to turn it into a LIFO and observe the results.

**Comment by ctiller** [comment]
RE: allow_synchronous_callbacks - that seems odd and worth understanding also. It's definitely a latency hit.

**Comment by ctiller** [comment]
allow_synchronous_callbacks is 1 if called through pollset->maybe_work (maps to multipoll_with_epoll_pollset_maybe_work) then grpc_fd_become_{readable,writable}.

**Comment by vjpai** [comment]
Ok, didn't see that one. Nevertheless, I will look into that one and see if it's actually needed.

**Comment by ctiller** [comment]
It's absolutely needed... not doing so means (likely) losing thread locality... I'd be more in favor of working towards getting more code able to allow_synchronous_callback than to reducing its use.

Not doing the synchronous callback means we would need to unroll stack to the completion queue and then repeat all the checks that we made coming down before we got a chance to do the work.

**Comment by ctiller** [comment]
For reference: this is what I was originally considering implementing:
http://www.1024cores.net/home/lock-free-algorithms/queues/intrusive-mpsc-node-based-queue

Probably with modifications to make it multiple-consumer instead of single consumer, but I figured V1 could punt.

**Comment by vjpai** [comment]
Yes, I also found some research papers on related topics and was looking them over. Most are focused on high-perf SPSC but some look at other variations. Atomic CAS instructions are definitely our friends.

**Comment by vjpai** [comment]
I will work toward an implementation based on the 1996 PODC paper by Valois from RPI.

**Comment by ctiller** [comment]
Thinking about this a little more... We probably want to go one better and provide multiple worklists. If we had a worklists per completion queue we could cover all per call use cases, and one per channel could cover other uses.

I think one per channel ends up requiring an eventfd per open socket however. I'm starting to feel like this is justified to preserve our work isolation story. Would certainly make the transport work easier: if we have an acceptable work spilling mechanism I think I can bring transport level synchronization down to a few CAS operations.

**Comment by vjpai** [comment]
So, pull request #2383 may need to be adjusted to support this, since that's a lockfree stack of short ints (meant to work in another context) and this would not be.

**Comment by vjpai** [comment]
When complete and merged, #7279 will resolve this issue. Closing it as obsolete for now.
