### ISSUE TITLE
grpc_tls_key_materials_config_set_key_materials should not free the input array

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#20161]
[This line](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.cc#L156) calls `gpr_free` on the input array supposedly constructed by the user (often makes sense as a stack allocated). The ownership of the array should remain in hands of the user.

(To be clear, should the ownership transfer is the intent, there should be a helper `create` function, as the user is not supposed to use `gpr_*` to allocate things).

cc @yihuazhang

**Comment by jiangtaoli2016** [comment]
Thanks @mehrdada for reporting the bug. We will fix asap.

**Comment by ZhenLian** [comment]
@mehrdada 
Thanks for pointing out the bug! I will try to fix this asap. 
Just to be clear, the link in the description seems out of date because line number grows. Do you mean [this line](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.cc#L176)?

**Comment by mehrdada** [comment]
@ZhenLian the real bug is unclear memory ownership semantics in the API. It needs to be consistent with the rest of API and surely should not free a `const char*` type.  Most likely the best course of action is to expect the user to free it, not us. Please note that once we change this, there are code that may be using this that may need to be updated as well so care is necessary. Please try writing comprehensive tests and running them under ASAN. I believe the existing test uses `gpr_free` which is a red flag--i.e. test should be testing against the public API as if a user was using it, but `gpr_free` is private API.

**Comment by ZhenLian** [comment]
@mehrdada  Thanks for the input, Mehrdad!
During the discussion with @yihuazhang , we revisited the APIs and spotted the following places where may cause users' memory leak:

1. in [Grpc_tls_key_materials_config_set_key_materials](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.cc#L159), we may need to memcpy user-provided key materials (root, cert chain) before proceeding
2. All the error_details, such as [this one](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L920), are user-provided information and we'd better not free them
3. C++ wrapper, for example, [here](https://github.com/grpc/grpc/blob/ee020be62c24b4fcb4d7e2f3fc16a83ba3105bc5/src/cpp/common/tls_credentials_options.cc#L38), is following the same ownership pattern as C core and we'd better change them
4. (Not strictly relevant here, but just write it down for reference) [cb_user_data](https://github.com/grpc/grpc/blob/ee020be62c24b4fcb4d7e2f3fc16a83ba3105bc5/include/grpc/grpc_security.h#L923) is used to [point back to the security connector](https://github.com/grpc/grpc/blob/8a7c2893d52a1450194b098d2b38d036059a93fc/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L380). We might want to at least improve the comments, or change it to a pointer to grpc_closure, to better explain the use of this field

I will work on these improvements soon. Feel free to let me know if we miss anything, or there are any other places that could be improved. Thanks again for the valuable discussions here!

**Comment by mehrdada** [comment]
@ZhenLian Thanks! it'd be great if it is clarified in the documentation what in `key_materials` passed to callback when reloading can be reused and how it should be handled.

**Comment by ZhenLian** [comment]
@mehrdada 
It looks like my #3 has already been fixed by https://github.com/grpc/grpc/pull/21932.
But I agree in general, we need to improve the documentation for better user experience. I will keep that in mind when fixing this. Thanks for the suggestions!

**Comment by sanjaypujare** [comment]
I agree with improving user experience which includes:

- excellent API documentation i.e. the API comments in the header file (which also gets copied to grpc.io which most people use?)
- an example for each API (or set of APIs for a feature) that illustrates the use-case for that example
- good error checking and reporting (this is in code and not just doc)

Also when there are multiple features (typically used via [grpc_tls_credentials_options)](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L720) I am assuming certain combinations cannot/should not be used together. For example, does it make sense to use [grpc_tls_credentials_options_set_key_materials_config](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L752) and [grpc_tls_credentials_options_set_credential_reload_config](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L761) together?

**Comment by ZhenLian** [comment]
@sanjaypujare 
IIUC, if user specifies both fields, the key_material set by [grpc_tls_credentials_options_set_key_materials_config](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L752) will get replaced immediately by the key_material set by [grpc_tls_credentials_options_set_credential_reload_config](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L761), which makes the former meaningless. We didn't disallow that but setting the first param is useless here. @yihuazhang Please correct me if I am wrong.
But yeah, I got the idea. I will also clean up the documentation for C++. Thanks a lot for the suggestions!

**Comment by sanjaypujare** [comment]
@ZhenLian I wasn't entirely sure if using the second one makes the first one meaningless. May be grpc_tls_credentials_options_set_key_materials_config sets the initial value(s) and  grpc_tls_credentials_options_set_credential_reload_config will only conditionally replace that value based on some dynamic conditions. Is that possible or even a use-case we anticipated?

My point is that it is not easy to use the advanced features without very good documentation which needs to be more than just API comments in the header file. Users are likely to make mistakes if there is no high level documentation with use-cases, examples etc.

So I just searched and  [grpc_tls_credentials_options](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security.h#L720) is used in the following APIs:

grpc_tls_credentials_options_set_cert_request_type
grpc_tls_credentials_options_set_server_verification_option
grpc_tls_credentials_options_set_key_materials_config
grpc_tls_credentials_options_set_credential_reload_config
grpc_tls_credentials_options_set_server_authorization_check_config

Some are new and some are old and probably some of the new ones make some of the old ones obsolete. Or may be some of them can be used together in a complex use-case. To me it's not easy to figure out.

**Comment by ZhenLian** [comment]
@sanjaypujare 

> @ZhenLian I wasn't entirely sure if using the second one makes the first one meaningless. May be grpc_tls_credentials_options_set_key_materials_config sets the initial value(s) and grpc_tls_credentials_options_set_credential_reload_config will only conditionally replace that value based on some dynamic conditions. Is that possible or even a use-case we anticipated?
I just checked the code and yes, the logic behaves like you described. One thing to note is that, users need reloading don't necessarily have to use set_key_materials_config to provide the initial key_material - they could also set it through credential_reload_config and make set_key_materials_config empty.

> My point is that it is not easy to use the advanced features without very good documentation which needs to be more than just API comments in the header file. Users are likely to make mistakes if there is no high level documentation with use-cases, examples etc.
OK, got it. Examples are in our plate but I will fix this issue first.

**Comment by ZhenLian** [comment]
@mehrdada 
The issues mentioned above have all been fixed. Please let me know if you have any further concerns/suggestions, and feel free to close this issue. Thanks again for bringing up this issue :-)

**Comment by mehrdada** [comment]
Looks like it's fixed now, thanks! Will reopen if I discovered an issue with it.
