### ISSUE TITLE
Better support for flatbuffers in grpc

### ISSUE THREAD

**Issue by smahapatra1** [grpc/grpc#20168]
We would like to use flatbuffers, but it appears that integration with grpc is still lacking. More languages (apart from C++ and GO) such as Java, NodeJS and Python will really help. Second, if the maintainers can also make sure that flatbuffers doesn't stop working after a release, it will give confidence to build with flatbuffers.

**Comment by jtattermusch** [comment]
We would like to support flatbuffers, but our resources are limited. IMHO, flatbuffer support (as well as support for other serialization formats) will always be driven and maintained by the community (which doesn't mean it won't have a great level of support at some point - it just means that grpc team should not be its maintainer).

**Comment by AspirinSJL** [comment]
From @jtattermusch 's comment, I feel we won't fix this in close future. Closing it. Please re-open if you don't agree.

**Comment by smahapatra1** [comment]
Please take a look at this paper:

https://static1.squarespace.com/static/5a60ec649f8dce866f011db6/t/5ab286da2b6a283afce7d752/1521649372997/Safety-Serialization.pdf

You might change your mind after seeing the difference. At least the
languages maintained by the google team should add FlatBuffers support
first and leave others to the open source community.

Regards,
Saroj Mahapatra

**Comment by jtattermusch** [comment]
@smahapatra1  I get that flatbuffer support might be important for many users, but so are other features. It's all about prioritization. If you're on a team that really needs flatbuffer support, please consider offering a helping hand and contribute. I'd recommend starting with flatbuffers support for java, because if performance (and latency) is your motivation, languages like python will likely be too slow for your for use case anyway.

**Comment by smahapatra1** [comment]
Hi, I'd love to contribute back, but unfortunately my team doesn't have the
skillset to build such packages.

I attended the first gRPC conference and I have been trying to promote the
use of gRPC in Bank of America, but high performance financial applications
will have difficulty in using gRPC for two reasons - 1) low QPS from async
C++ and 2) serialization/deserialization overhead of protobufs (unlike
FlatBuffers).

Still it is a great product and we plan to use for GUI, app server and even
high performance servers that provide gRPC endpoint to such app servers
while using something custom for main-line processing.
For that reason, even python with its low performance is important to have
support - sometimes it is good enough for application servers (behind React
GUI) that in turn make other gRPC calls and it can be replaced by Java/C++
later when need for speed arises.

Thanks,
Saroj

**Comment by jtattermusch** [comment]
@smahapatra1   I can't really promise that we'll work on better flatbuffer integration anytime soon (lack of resources and other priorities), but thanks for sharing your story. I actually do have a background in financial applications as well (I used to be involved in high-frequency trading), so out of personal interest, I'd like to hear more if you're willing to share - feel free to reach out to me via e-mail.

**Comment by smahapatra1** [comment]
I used to run Automated Options Market-making where if you have 10 microseconds tick-to-trade latency, you are better than average but not top. Now I am involved in building trading products for trading floor and latency needs are not as strict except few special apps for routing orders to market. I am still trying to learn gRPC (it is huge) and I will post more questions in the group.   
  
Please take a look at seastar product for some ideas on improving the performance in async mode. Even Facebook folly UnboundefQueue has some nice performance.
  

  
Thank you.
  

  
  

  
  
>
