### ISSUE TITLE
Possible dereference of null pointer

### ISSUE THREAD

**Issue by Dmitry-Me** [grpc/grpc#20175]
This was found with CppCheck
lb_policy_registry.cc contains ParseLoadBalancingConfigHelper() function which goes like this:

      if (lb_config_array == nullptr || lb_config_array->type != GRPC_JSON_ARRAY) {
    gpr_asprintf(&error_msg, "field:%s error:type should be array",
                 lb_config_array->key);

In case `lb_config_array` is null control enters the `if` and then attempt to compute `lb_config_array->key` causes dereferencing of null pointer and undefined behavior.

**Comment by markdroth** [comment]
This won't actually ever be a problem in practice, since all of the callers of this function ensure that the input is not null.  But I've sent out a PR to have it handle that case anyway.
