### ISSUE TITLE
Python -m grpc_tools.protoc fails on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by rvlietstra** [grpc/grpc#20174]
### What version of gRPC and what language are you using?
sudo pip3 install grpcio-tools
grpcio-tools (1.23.0)
grpcio>=1.23.0 (1.23.0)
protobuf>=3.5.0.post1 (3.9.1)
six>=1.5.2 (1.12.0)
setuptools (41.2.0)

### What operating system (Linux, Windows,...) and version?
Linux, stretch

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.7

### What did you do?

$ python3.7 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. calculator.proto

### What did you expect to see?
I expected code files to be generated

### What did you see instead?

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/grpc_tools/protoc.py", line 20, in <module>
    from grpc_tools import _protoc_compiler
ImportError: /usr/local/lib/python3.7/dist-packages/grpc_tools/_protoc_compiler.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

### Anything else we should know about your project / environment?
It seems protobuf had the same issue and fixed it by linking to atomic, see https://github.com/protocolbuffers/protobuf/commit/55ed1d427ccc0d200927746329ac9b811dee77b9
https://github.com/protocolbuffers/protobuf/issues/5219

**Comment by Fox5150** [comment]
I tried to install it again on another Raspberry Pi Zero. The installation was frozen and I got the message :
cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++

**Comment by lidizheng** [comment]
@Fox5150 `pip` is trying to compile gRPC from source, and it does take some time. Alternatively, you can check https://www.piwheels.org/project/grpcio/ for precompiled wheels made for Raspberry Pi.

This issue should be fixed by #20414. If your issue persists, please consider open a new issue.

**Comment by Fox5150** [comment]
@lidizheng Thanks very much ! It worked. I installed this version : 
1.26.0 | cp37m | grpcio-1.26.0-cp37-cp37m-linux_armv7l.whl
Thanks again !
