### ISSUE TITLE
New call creation is serialized on grpc_server::mu

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2017]
Investigate the activities that are occurring under this lock.

Consider:
- splitting activity under the lock
- sharding into multiple queues

First step on this bug should be enumerating the usage of the lock here.

**Comment by vjpai** [comment]
I volunteer as tribute.

**Comment by ctiller** [comment]
Please do any investigations against #1577 - the code significantly changed.

**Comment by vjpai** [comment]
Ok, thanks for the tip.

**Comment by ctiller** [comment]
Note that after #2028 goes in, mutrace reports this as our primary contention point.

**Comment by vjpai** [comment]
Ok, I will make this a higher priority for the short-term than the
lock-free callbacks, though I will keep that in mind also.

**Comment by vjpai** [comment]
Yes, I can see from mutrace that something like 80% of the lock contention is coming from here. I also believe that only one of the static code paths that holds this lock for a substantial amount of time is on the critical path, so hopefully that helps. I should have something quantitative to report tomorrow.

**Comment by ctiller** [comment]
One thought I had:

We currently keep the ALL_CALLS list around:
- so we know when we've got none left
- so we can cancel them all at shutdown

This structure should be trivially shard-able (just split it N ways, N = k * numcpus()?), but I was thinking:
- transports already need to track all the calls on the transport
- servers have to track all the channels (and therefore all the transports)
- is there a way we can re-use that knowledge and ditch the ALL_CALLS list entirely?

**Comment by vjpai** [comment]
I like the idea of CLEAN ALL THE CALLS! or rather CLEAN THE ALL CALLS! . I'll look things over and see what the effects of that area.

**Comment by ctiller** [comment]
So I think we can ensure that all calls are gone before all channels are gone (by refcounting alone).
Which means it suffices on the server to just wait for all channels to be gone.

We can introduce a channel op (into channel_stack.h) that cancels all calls on a channel to aid the implementation of grpc_server_cancel_all_calls. It could tunnel its way down the channel stack to the transport, and then the transport could do its transport thing. There's some existing code to do that on disconnection.

**Comment by vjpai** [comment]
So, the first part about refcounting alone looks good.
As for the second part, are you saying that the relevant information is already there, or would this require creating a list of all-calls in each channel? If so, the current mu_global will get contended for managing that list and we'll need to move toward a sharded lock per channel. But that may not be as rough, will have to see.

**Comment by ctiller** [comment]
So transports are required to keep track of the list of all calls active on
them, which should suffice. We need to drill down from the channel layer to
the transport layer to do this, and that's what the event types
in grpc_channel_op_type are for... consider making something
like GRPC_CHANNEL_GOAWAY but called GRPC_CHANNEL_CANCEL_ALL_CALLS.

**Comment by vjpai** [comment]
ok, I see. Will investigate.

**Comment by vjpai** [comment]
This issue has been resolved by PR #2105, #2303, #2315, and others. There may be new issues that need investigation, but it is not about any server-wide serialization anymore. Issue #2016 remains open and the lock-free structure built for that will also help improve server performance in general.
