### ISSUE TITLE
Stream message from one to second client

### ISSUE THREAD

**Issue by MdLejTeCole** [grpc/grpc#20190]
### Additional context
Add any other context about the feature request here.

**Comment by MdLejTeCole** [comment]
Stream messages form client to server, and stream the same messages you get from client, to secound client from server.

**Comment by nanahpang** [comment]
Could you describe your question more clearly? Right now, I guess your requirement is to implement a client 1 -> server -> client 2 workflow using streaming. This logic should be implemented in your program, instead of gRPC itself.

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
