### ISSUE TITLE
Ruby travis problem: grpc_channel_destroy() not in -lgrpc

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2019]
#1995 

checking for grpc_channel_destroy() in -lgrpc... *** ../../../../ext/grpc/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

https://travis-ci.org/grpc/grpc/jobs/66133689

**Comment by soltanmm** [comment]
Underlying cause of this is the same as in #2021, closing this as a duplicate.
