### ISSUE TITLE
Please support HTTPS for proxy connection

### ISSUE THREAD

**Issue by mdz** [grpc/grpc#20199]
### Is your feature request related to a problem? Please describe.
I want to access a grpc service using an HTTP proxy, and have the connection to the proxy be secure.

### Describe the solution you'd like
If the `http_proxy` environment variable contains an `https://` URL, grpc should connect to the proxy using TLS, similar to how `curl(1)` behaves. Currently, this produces a "scheme not supported in proxy URI" warning, and the proxy is ignored (https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/http_proxy.cc#L64)

**Comment by mdz** [comment]
I still care about this capability

**Comment by yashykt** [comment]
I'm going to mark this as disposition/help wanted since we do not have bandwidth to work on this at the moment.

**Comment by markdroth** [comment]
Closing this since no one has come forward to work on it.  If someone wants to volunteer, we can reopen.
