### ISSUE TITLE
Eliminate allocations from the data path

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#202]
At various points on the critical data path we allocate small temporary buffers for (eg) metadata send queues.

Inline such queues into the owning objects for reasonable queue lengths and eliminate these allocations.

**Comment by ctiller** [comment]
@dgquintas - meta bug for work we'll be doing soon

**Comment by yang-g** [comment]
Is this done?

**Comment by dgquintas** [comment]
Yes
