### ISSUE TITLE
Very unfriendly <make.exe": no_c_compiler: Command not found> message when no gcc is installed

### ISSUE THREAD

**Issue by Dmitry-Me** [grpc/grpc#20205]
I followed these instructions https://github.com/grpc/grpc/blob/master/BUILDING.md on clean "Ubuntu 18.04.3 LTS" and whenever I ran "make" to actually compile grpc I would face (that's the valuable part of the message):

    make.exe": no_c_compiler: Command not found

(and this is the full message):

    [C]       Compiling third_party/address_sorting/address_sorting.c
    make: no_c_compiler: Command not found
    Makefile:2899: recipe for target '/home/admin-/grpc/objs/opt/third_party/address
            _sorting/address_sorting.o' failed
    make: *** [/home/admin-/grpc/objs/opt/third_party/address_sorting/address_sortin
            g.o] Error 127

Mmmkay, what do I do with that? Some recipe failed, some command not found, rather hard for someone not very experienced with `make`.

Turns out I had no C compiler installed and I needed to install one, for example, gcc, using

    apt get install gcc

It would be nice if there was better diagnostics for this situation. Not some "command not found" thing but a more explicit text like "no C compiler found on the machine, maybe install one, maybe even gcc"

It looks like the following chain at the beginning of `Makefile`:

    ifeq ($(HAS_CC),true)
      DEFAULT_CC = cc
      DEFAULT_CXX = c++
    else
    ifeq ($(HAS_GCC),true)
      DEFAULT_CC = gcc
      DEFAULT_CXX = g++
    else
    ifeq ($(HAS_CLANG),true)
      DEFAULT_CC = clang
      DEFAULT_CXX = clang++
    else
      DEFAULT_CC = no_c_compiler
      DEFAULT_CXX = no_c++_compiler
    endif
    endif
   endif    

is in charge of compiler detection. The "no compiler" part can be changed to this:

    # (clang was detected)
    else
     #add this 
     $(error No C compiler found. Please ensure cc, gcc or clang is installed.)
     #and remove the "no_compiler" variables
    endif
     
and this emits the following error message:

    Makefile:61: *** No C compiler found. Please ensure cc, gcc or clang is installed. Stop.

Very clear and easy to read.

**Comment by Dmitry-Me** [comment]
@nicolasnoble I included the possible way to resolve the issue - the latest edit. Could you please take a look?

**Comment by jtattermusch** [comment]
Our plan for the future is to only support cmake and bazel. Makefile will be only used for building binary artifacts for languages that require it. So I'm not sure if addressing this makes sense in the long run. You should switch your builds to cmake.

**Comment by jtattermusch** [comment]
Makefile support is now deprecated. Please use cmake.
