### ISSUE TITLE
Grpc message lost accidentally

### ISSUE THREAD

**Issue by ABNER-1** [grpc/grpc#20203]
I have a problem:
When I use grpc, executing a normal request, the server has already  handled the request and has gotten it from the completed queue for the second time (executing the delete operation. Does this step mean that http2 has guaranteed that the client has received it? ). However, there is no event gotten from the client's cq successfully. Because in this step I set it to wait, so my program behaves as no response. How can i  view the conversion information from stub to cq? Are there any other similar tests to guarantee the reliability of this step？

**Comment by nanahpang** [comment]
I am confused about the scenario you described above. Could you paste more information such as traced logs or test codes?

**Comment by MdLejTeCole** [comment]
Hi, I have the same problem, but in my case i lose a lot of messages, when i dont use Thread.Sleep between send mesages. I use Grpc.Core, and i send message by streaming.
My connection look like this:
```
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            var servicesProvider = new Provider();
            servicesProvider.SetServiceConnection(typeof(Client.Greeter.GreeterClient), "localhost", 5001, ChannelCredentials.Insecure);
            servicesProvider.CreateServiceAndCache<Greeter.GreeterClient>();
            var client = servicesProvider.GetService<Greeter.GreeterClient>();

```
And i Send messages like this:

```
var call = client.SendComputeUnitTagsStream();
            var _requestStream = call.RequestStream;
foreach (var s in dict)
                {
                   
                    var msg = iMapper.Map<RepeatedField<Tag>>(s.Value);

                    ComputeUnitTags result = new ComputeUnitTags();
                    result.ComputeUnit = new ComputeUnit() { Id = s.Key };
                    result.Tags = new Tags();
                    result.Tags.Tags_.AddRange(iMapper.Map<RepeatedField<Tag>>(s.Value.Take(i)));

                   await _requestStream.WriteAsync(result);;
                }
```
In my program i cant make sleep. What I should do to dont lost messages? i cant lock it because it is await. I tried a lot of things, and without sleep nothing work.
