### ISSUE TITLE
Is there any way to get current load(request-per-second) in grpc channel? 

### ISSUE THREAD

**Issue by eendru** [grpc/grpc#20218]

**Comment by nanahpang** [comment]
Could you add more description about why you cannot calculate the load in your program?

**Comment by AspirinSJL** [comment]
The census filter uses opencensus for such stats.
https://github.com/grpc/grpc/blob/master/src/cpp/ext/filters/census/measures.h
https://github.com/grpc/grpc/blob/master/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc

Looks like the closest measure is the `*CompletedRpcs`.
