### ISSUE TITLE
E0910 resolver_registry.cc:80] don't know how to resolve 'localhost:50051' or 'dns:///localhost:50051'

### ISSUE THREAD

**Issue by willamzheng** [grpc/grpc#20219]
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by manhnt9** [comment]
I'm having same issue, Linux runs fine but with the same grpc version built for iOS, it can't resolve server url. Maybe MacOS/iOS has different UNIX implementation from Linux which affects the DNS resolver service.

**Comment by manhnt9** [comment]
My error is: `E0915 17:47:49.414627000 4317522880 resolver_registry.cc:80]           don't know how to resolve`

**Comment by manhnt9** [comment]
E0915 17:47:49.414627000 4317522880 resolver_registry.cc:80]           don't know how to resolve 'REMOVED_IP:REMOVED_PORT' or 'dns:///REMOVED_IP:REMOVED_PORT
E0915 17:47:49.415092000 4317522880 resolver_registry.cc:80]           don't know how to resolve 'dns:///REMOVED_IP:REMOVED_PORT' or 'dns:///dns:///REMOVED_IP:REMOVED_PORT'
E0915 17:47:49.415328000 4317522880 channel.cc:95]                     channel stack builder failed: {"created":"@1568544469.415137000","description":"resolver creation failed","file":"XXX/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":740}

**Comment by manhnt9** [comment]
I find out that maybe cares is not available on iOS/Android. Looking for way to enable native solver.

**Comment by manhnt9** [comment]
I tried setting GRPC_DNS_RESOLVER to native in Xcode but it doesn't affect result.
Which function do I call to force native DNS solver as default?

**Comment by manhnt9** [comment]
I described in a new issue here: https://github.com/grpc/grpc/issues/20261

**Comment by apolcyn** [comment]
@willamzheng can you describe the language and the steps taken to build and run your application with grpc?

The analysis in https://github.com/grpc/grpc/issues/20261#issuecomment-531580096 sounds applicable here....

cc @muxi
