### ISSUE TITLE
gRPC python server performance trouble with gevent

### ISSUE THREAD

**Issue by liuyicarl** [grpc/grpc#20215]
### What version of gRPC and what language are you using?
Python 3.7.1
grpcio 1.19.0
gevent 1.4.0

### What operating system (Linux, Windows,...) and version?
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1+deb8u2 

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.1

### What did you do?
https://github.com/liuyicarl/grpc_demo

### What did you expect to see?
qps does not fall down.

### What did you see instead?

api upload total time is 1084 at 2019-09-10 12:50:14.411698
api upload total time is 1085 at 2019-09-10 12:50:15.412432
api upload total time is 1078 at 2019-09-10 12:50:16.413014
api upload total time is 1058 at 2019-09-10 12:50:17.413019
api upload total time is 1113 at 2019-09-10 12:50:18.413451
api upload total time is 1033 at 2019-09-10 12:50:19.413572
api upload total time is 1051 at 2019-09-10 12:50:20.414005
api upload total time is 1129 at 2019-09-10 12:50:21.415035
api upload total time is 1090 at 2019-09-10 12:50:22.415331
api upload total time is 998 at 2019-09-10 12:50:23.416155
api upload total time is 1015 at 2019-09-10 12:50:24.416794
api upload total time is 909 at 2019-09-10 12:50:25.416943
api upload total time is 1090 at 2019-09-10 12:50:26.417606
api upload total time is 1161 at 2019-09-10 12:50:27.418041
api upload total time is 1096 at 2019-09-10 12:50:28.418843
api upload total time is 1061 at 2019-09-10 12:50:29.419445
api upload total time is 987 at 2019-09-10 12:50:30.420166
api upload total time is 1045 at 2019-09-10 12:50:31.420393
api upload total time is 1017 at 2019-09-10 12:50:32.420900
api upload total time is 924 at 2019-09-10 12:50:33.421358
api upload total time is 890 at 2019-09-10 12:50:34.422325
api upload total time is 892 at 2019-09-10 12:50:35.423042
api upload total time is 1062 at 2019-09-10 12:50:36.423366
api upload total time is 1072 at 2019-09-10 12:50:37.424366
api upload total time is 946 at 2019-09-10 12:50:38.425225
api upload total time is 922 at 2019-09-10 12:50:39.425240
api upload total time is 842 at 2019-09-10 12:50:40.425680
api upload total time is 879 at 2019-09-10 12:50:41.426483
api upload total time is 772 at 2019-09-10 12:50:42.426855
api upload total time is 825 at 2019-09-10 12:50:43.427329
api upload total time is 828 at 2019-09-10 12:50:44.427976
api upload total time is 849 at 2019-09-10 12:50:45.428931
api upload total time is 970 at 2019-09-10 12:50:46.429403
api upload total time is 970 at 2019-09-10 12:50:47.429447
api upload total time is 977 at 2019-09-10 12:50:48.430296
api upload total time is 976 at 2019-09-10 12:50:49.430861
api upload total time is 963 at 2019-09-10 12:50:50.431014
api upload total time is 858 at 2019-09-10 12:50:51.432185
api upload total time is 817 at 2019-09-10 12:50:52.432895
api upload total time is 825 at 2019-09-10 12:50:53.433717
api upload total time is 765 at 2019-09-10 12:50:54.434924
api upload total time is 690 at 2019-09-10 12:50:55.435701
api upload total time is 755 at 2019-09-10 12:50:56.436010
api upload total time is 782 at 2019-09-10 12:50:57.436413
api upload total time is 705 at 2019-09-10 12:50:58.436815
api upload total time is 734 at 2019-09-10 12:50:59.437461
api upload total time is 702 at 2019-09-10 12:51:00.438244
api upload total time is 784 at 2019-09-10 12:51:01.438639
api upload total time is 741 at 2019-09-10 12:51:02.439006
api upload total time is 850 at 2019-09-10 12:51:03.439731
api upload total time is 876 at 2019-09-10 12:51:04.440438
api upload total time is 915 at 2019-09-10 12:51:05.440678
api upload total time is 883 at 2019-09-10 12:51:06.441059
api upload total time is 860 at 2019-09-10 12:51:07.441326
api upload total time is 843 at 2019-09-10 12:51:08.442339
api upload total time is 737 at 2019-09-10 12:51:09.442980
api upload total time is 659 at 2019-09-10 12:51:10.443881
api upload total time is 680 at 2019-09-10 12:51:11.444462
api upload total time is 794 at 2019-09-10 12:51:12.445543
api upload total time is 818 at 2019-09-10 12:51:13.445643
api upload total time is 770 at 2019-09-10 12:51:14.446751
api upload total time is 607 at 2019-09-10 12:51:15.447018
api upload total time is 680 at 2019-09-10 12:51:16.447926
api upload total time is 659 at 2019-09-10 12:51:17.449204
api upload total time is 622 at 2019-09-10 12:51:18.450517
api upload total time is 615 at 2019-09-10 12:51:19.451824
api upload total time is 659 at 2019-09-10 12:51:20.451987
api upload total time is 686 at 2019-09-10 12:51:21.452912
api upload total time is 661 at 2019-09-10 12:51:22.454283
api upload total time is 640 at 2019-09-10 12:51:23.454420

**Comment by lidizheng** [comment]
This is quite weird, `gevent` should boost the performance of server instead of bringing it down. Can you tell more about your scenario setup?

**Comment by liuyicarl** [comment]
What do you want to know about the scenario setup?

you can try to run `https://github.com/liuyicarl/grpc_demo` 

`python server_simple.py`   for starting rpc server.
`python client.py` for starting rpc client.

**Comment by liuyicarl** [comment]
> This is quite weird, `gevent` should boost the performance of server instead of bringing it down. Can you tell more about your scenario setup?

What do you want to know about the scenario setup?

you can try to run https://github.com/liuyicarl/grpc_demo

python server_simple.py for starting rpc server.
python client.py for starting rpc client.

**Comment by lidizheng** [comment]
What is your baseline? How do you determine this is a performance regression?

**Comment by liuyicarl** [comment]
> What is your baseline? How do you determine this is a performance regression?

Maybe I didn't describe the problem clearly.

I used the grpc official demo to make a slight modification. Through the single-threaded client continuously request the server. 
At the beginning, qps is about 1000, but qps will drop rapidly until it drops to about 40qps.

why? I am very confused.

**Comment by liuyicarl** [comment]
> Confirmed the wrong behavior. With `gevent`, I observed the same drop of QPS over time. After disabled `gevent`, the drop of QPS is gone.
> 
> More specifically, to reproduce this performance regression, the server needs to call `init_gevent` and the client needs to continuously using the same channel.

sorry for the late reply.

I tested with the gevent 1.2.2 version is normal, qps will not drop.

Perhaps it is a bug in the gevent, which needs further analysis.

**Comment by lidizheng** [comment]
@liuyicarl We would be appreciated if you can help with the digging and tracing of this gevent issue. Sorry we are short of people right now, and gevent is an experimental feature.

1. Can you help with `git bisect` to see which gRPC version causes this issue? Or which gevent version causes this issue? 
2. Can you you use Python profilers to dig into the server application? I'm thinking of `cProfile` for CPU time, and [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) for memory usage.

**Comment by mariosnikolaou** [comment]
This is most likely a [gevent](https://github.com/gevent/gevent) bug and is already fixed on the development version 1.5 (unreleased).

In the example code shared, the issue can be narrowed down to the server code and bisecting gevent versions from 1.3a1 (good) to 1.3a2 (bad), one finds that the issue was first introduced by commit [760a080](https://github.com/gevent/gevent/commit/760a080cdadc4e7b957ab47346950e235d99b29a).

Luckily, a [related issue](https://github.com/gevent/gevent/issues/1371) was identified in gevent and [a fix](https://github.com/gevent/gevent/commit/e64647fe5ebc44eaf9b00ab4dc570898f3d9b2db) was introduced in the 1.5 development code, by removing the need to store additional stack frame data from the spawning greenlet. See the commit and issue for more info.

The currently latest released version of gevent, 1.4.0, suffers from this issue, but in [a comment for the gevent issue](https://github.com/gevent/gevent/issues/1371#issuecomment-476780540), there is a description on a workaround that can be applied to currently released gevent versions. The suggestions is to set the environment variable `GEVENT_TRACK_GREENLET_TREE=False` ([doc](http://www.gevent.org/configuration.html#gevent._config.Config.track_greenlet_tree)) when starting the server code. Starting the server code with this environment variable
```
GEVENT_TRACK_GREENLET_TREE=False python server_simple.py
```
seems to alleviate the performance issues, at least in my tests.

I propose we close this issue as not a gRPC issue, but rather a gevent issue that is fixed.

**Comment by lidizheng** [comment]
Many thanks for the investigation effort! As reasoning above, we are closing this issue :)
