### ISSUE TITLE
Failed to compile OpenSSL packages on Travis

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2021]
#1995 

https://travis-ci.org/grpc/grpc/jobs/66133689

**Comment by soltanmm** [comment]
Whaaaaaaat...

**Comment by nicolasnoble** [comment]
The actual error is this:

`hm_ameth.c:162:1: error: missing initializer [-Werror=missing-field-initializers]`

Basically, OpenSSL failed to compile. The reason it was even trying to compile it in the first place is probably because it failed to grab the pre-compiled packages from storage.

**Comment by soltanmm** [comment]
Re-purposing this issue for the OpenSSL build error on Travis... What's up with the pre-compiled packages?

**Comment by nicolasnoble** [comment]
Travis timed-out to grab it ?
