### ISSUE TITLE
authentication in python, AuthMetadataPlugin, AuthMetadataContext or Interceptor?

### ISSUE THREAD

**Issue by allenling** [grpc/grpc#20231]
i run a python grpc server, and i want to setup a  jwt authentication,  simply:

1. client send their data with token(metadata) to server

2. server auth token and create user object, and save user object to context

sure, i can create a Interceptor to do authentication according to example https://github.com/grpc/grpc/blob/master/examples/python/auth/customized_auth_server.py

but how can i save user object to context?  

i read python example reandme https://github.com/grpc/grpc/tree/master/examples/python/auth
, should i use  AuthMetadataPlugin? and where could i find a complete AuthMetadataPlugin example?

**Comment by allenling** [comment]
grpcio v1.23.0

**Comment by p-ryan** [comment]
allenling@ could you elaborate on how to do this?  Pointers to example code, docs, etc.

**Comment by gnossen** [comment]
@allenling Can you please elaborate on your use case? What exactly do you mean by context?

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
