### ISSUE TITLE
how to make client keepalive in C#?

### ISSUE THREAD

**Issue by Rorsch431** [grpc/grpc#20240]
I'm using pi-stream way to send files.But I get error:"System.InvalidOperationException: Already finished " when the server called WriteAsync() method.Only when I use Thread.sleep the client sometimes can get the stream during the sleeping time. I guess maybe the client close the stream.
I tried add 
new ChannelOption("grpc.keepalive_time_ms", 5 * 60 *  1000),
new ChannelOption("grpc.keepalive_permit_without_calls", 1)
after read https://stackoverflow.com/questions/45257255/set-keepalive-for-grpc-in-c-sharp-client
But  it seems not work, plz tell me what can I  do!

here's the code.
                proto:
                rpc CppyFile(stream Chunk)returns(stream Back){}

                message Chunk{
                bytes Content=1;
                string FileName=2;
                string Flag=3;
                }

                message Back{
                bytes Content=1;
                string Flag=2;
                }

                Server:
                await responseStream.WriteAsync(new Back
                            {
                                Content = ByteString.FromStream(stream),
                                Flag = "1",
                            });

                client:

                using (var call = client.CppyFile())
            {

                try
                {
                    await call.RequestStream.WriteAsync(chunk);
                    Console.WriteLine("Sending");

                        //################################################################################## here's Problem

                        await call.RequestStream.CompleteAsync();
                    //Thread.Sleep(8 * 1000);
                        //##################################################################################

                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }

                 //receiving from server
                 var responseReaderTask = Task.Run(async () =>
                { 
                    while (await call.ResponseStream.MoveNext())
                    {
                        var note = call.ResponseStream.Current;    
                                        
                                        ......

**Comment by jtattermusch** [comment]
What could help diagnosing is to set e.g. GRPC_TRACE=tcp  (see https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md), which will log the raw TCP traffic and that could tell who why the call has shutdown (and whether it was client or server who initiated it).

Looking at your code, what might be wrong it that you're using Thread.Sleep in your async code (which is an antipattern). You should be using await Task.Delay( ) instead.
I don't quite understand the pattern of what client is doing (btw, requestStream.CompleteAsync() should only be called once per call).

**Comment by jtattermusch** [comment]
What is the pattern of use that makes you convinced that the keepalive doesn't work?

**Comment by Rorsch431** [comment]
> What is the pattern of use that makes you convinced that the keepalive doesn't work?
Sorry for replying late! 
I found the problem is that I called CompleteAsync() too much times. 
thx a lot! Having a nice day!
