### ISSUE TITLE
Upb compiler error causing node linux compilee error

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#20254]
CC(target) Release/obj.target/grpc/deps/grpc/third_party/upb/upb/encode.o
  CC(target) Release/obj.target/grpc/deps/grpc/third_party/upb/upb/msg.o
../deps/grpc/third_party/upb/upb/decode.c: In function 'upb_skip_unknowngroup':
../deps/grpc/third_party/upb/upb/decode.c:164:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   CHK(d->end_group == field_number);
                    ^
../deps/grpc/third_party/upb/upb/decode.c:48:22: note: in definition of macro 'CHK'
 #define CHK(x) if (!(x)) { return 0; }
                      ^
../deps/grpc/third_party/upb/upb/decode.c: In function 'upb_decode_groupfield':
../deps/grpc/third_party/upb/upb/decode.c:321:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   CHK(d->end_group == field_number);
                    ^
../deps/grpc/third_party/upb/upb/decode.c:48:22: note: in definition of macro 'CHK'
 #define CHK(x) if (!(x)) { return 0; }
                      ^
  CC(target) Release/obj.target/grpc/deps/grpc/third_party/upb/upb/port.o
  CC(target) Release/obj.target/grpc/deps/grpc/third_party/upb/upb/table.o
  CC(target) Release/obj.target/grpc/deps/grpc/third_party/upb/upb/upb.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/transport_security.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/authority.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/chttp2_connector.o
../deps/grpc/third_party/upb/upb/table.c: In function 'upb_inttable_pop':
../deps/grpc/third_party/upb/upb/table.c:588:3: error: 'val.val' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   return val;
   ^
cc1: all warnings being treated as errors
grpc.target.mk:535: recipe for target 'Release/obj.target/grpc/deps/grpc/third_party/upb/upb/decode.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/third_party/upb/upb/decode.o] Error 1
make: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
grpc.target.mk:535: recipe for target 'Release/obj.target/grpc/deps/grpc/third_party/upb/upb/table.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/third_party/upb/upb/table.o] Error 1
make: Leaving directory '/var/local/git/grpc-node/packages/grpc-native-core/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.15.16-041516-generic
gyp ERR! command "/root/.nvm/versions/node/v6.17.1/bin/node" "/root/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--

**Comment by karthikravis** [comment]
[kokoro-sisyphus_resultstore_prod_grpc_core_pull_request_linux_grpc_basictests_node_72f53098-bdee-4599-abf4-bfad18589201_build.log](https://github.com/grpc/grpc/files/3611205/kokoro-sisyphus_resultstore_prod_grpc_core_pull_request_linux_grpc_basictests_node_72f53098-bdee-4599-abf4-bfad18589201_build.log)

**Comment by veblush** [comment]
@nicolasnoble Please take a look at this? Probably it's because of the recent change of compiler option for warnings.

**Comment by nicolasnoble** [comment]
Should be gone now.
