### ISSUE TITLE
iOS runtime over 250mb in latests Unity builds

### ISSUE THREAD

**Issue by raulpereztangelo** [grpc/grpc#20252]
I updated my project with the latest Unity package and the iOS runtime went from 70mb to more than 250mb. Is this intentional? It's kind of too much for a mobile game.

**Comment by jtattermusch** [comment]
We reverted the change that caused this https://github.com/grpc/grpc/pull/20233. The binary size is going to be back to normal in the 2.24.0 release.

**Comment by raulpereztangelo** [comment]
The iOS runetime is 125mb in the latest releases. This is still too high imo, we can't push it to github at the moment. Bear in mind that it used to be 75mb.

**Comment by jtattermusch** [comment]
Do you know the reason for the difference?
