### ISSUE TITLE
ServicerContext.is_active() returning True after client's disconnection

### ISSUE THREAD

**Issue by cscarpitta** [grpc/grpc#20259]
### What version of gRPC and what language are you using?
grpcio==1.23.0 
python

### What operating system (Linux, Windows,...) and version?
Linux Xubuntu with kernel 5.2.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 2.7

### What did you do?
I'm trying to use the stream gRPCs in my python application. 
A client subscribes to a stream of updates once and receives all changes to the server state until the client disconnects (forcefully or gracefully).

### What did you expect to see?
If the client disconnects forcefully I expect that ServicerContext.is_active() whould return False, so that I can check it and stop sending updates to the client.

### What did you see instead?
ServicerContext.is_active() continues to return True when the client disconnects from the server.

### Anything else we should know about your project / environment?
The bug has been already signaled in the past years
https://stackoverflow.com/questions/43948975/grpc-unary-streaming-continues-after-disconnect-blocks-on-interrupt

https://github.com/grpc/grpc/issues/11157

https://groups.google.com/forum/#!topic/grpc-io/45LxvLyYVLk

Is it possible to fix it?

**Comment by cscarpitta** [comment]
The problem just happens on python 2.7

I tried on python 3.7 and it works correctly.
After quitting the client, the ServicerContext.is_active() invoked on the server returns False as expected

**Comment by karthikravis** [comment]
@gnossen : can you please take a look?
