### ISSUE TITLE
Enable watchOS experimental support

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#20258]
watchOS experimental support was disabled because we were unable to upgrade `!ProtoCompiler.podspec` at this time to add watchOS support. This issue is a reminder to re-enable watchOS flags in the following places:
* `src/objective-c/!ProtoCompiler-gRPCPlugin.podspec`
* `tools/run_tests/run_tests.py`

**Comment by muxi** [comment]
not stale

**Comment by RomeuG** [comment]
Hi.

ProtoCompiler seems to have support for watchOS. Why hasn't it been enabled in gRPCPlugin podspec?
