### ISSUE TITLE
 Information about client connection

### ISSUE THREAD

**Issue by MdLejTeCole** [grpc/grpc#20263]
My server is streaming to client. I am looking for mechanism which let me check client dont lose connection with server. I send Token, but dont see any options to do this. 
In my server method i have loop "while" and it should be work while dont lose connection with client.

         public override async Task Get(Compute compute, IServerStreamWriter<T> asyncStreamWriter, 
        ServerCallContext ctx)
        {
        Computers.Set(compute, asyncStreamWriter);

        while (true)
        {

            await Task.Delay(1000);
        }
    }

**Comment by jtattermusch** [comment]
You have multiple options:
- you can configure the keepalive functionality: https://github.com/grpc/grpc/blob/master/doc/keepalive.md
- you can be sending "heartbeat" messages over the streaming call yourself (effectively emulating the keepalive functionality).
- you also might wanna take a look at https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md
