### ISSUE TITLE
Use Grpc.Core.Channel call duplex stream service, the response stream read task status is always "WaitingForActivation" 

### ISSUE THREAD

**Issue by lv-conner** [grpc/grpc#20273]
### What version of gRPC and what language are you using?
Grpc Version: 2.23.0
Language C#
### What operating system (Linux, Windows,...) and version?
windows 1607.

### What runtime / compiler are you using (e.g. python version or version of gcc)
CoreCLR. SDK Version: .Net Core 3.0.100-preview9-014004

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Code Repository: https://github.com/lv-conner/GrpcLearn.git
### What did you expect to see?
the response task should work like in debug mode
the read task normal execute;
### What did you see instead?
the read task status always be WaitingForActiviation until the RequestStream call CompleteAsync();

### Anything else we should know about your project / environment?
if i use GrpcChannel provide by Grpc.Net.Client eveything is ok,what's different between GrpcChannel and Channel;
Did i make mistake?

the client invoke code as follow:
```
        static async Task Main(string[] args)
        {
            //when host in Grpc.AspNetCore.Server use this;
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            //when use this,it can work;
            //var channel = GrpcChannel.ForAddress("http://localhost:8888", new GrpcChannelOptions()
            //{
            //    Credentials = ChannelCredentials.Insecure
            //});
            //then host in aspnetcore with https; use this;
            //var channel = GrpcChannel.ForAddress("https://localhost:8888");
            //use this will work when service host in aspnetcore.but can not work when service host in Grpc.Core.Server
            var channel = new Channel("localhost:8888", ChannelCredentials.Insecure);
            var client = new HelloMessageService.HelloService.HelloServiceClient(channel);
            var helloRes = client.SayHello(new HelloMessage.HelloMessageRequest() { Name = "tim lv" });

            var res = await client.SayHelloAsync(new HelloMessage.HelloMessageRequest() { Name = "tim lv" });
            Console.WriteLine(res.Message);

            var call = client.SayHelloStreamVersion();
            var readTask = Task.Run(async () =>
            {
                while(await call.ResponseStream.MoveNext())
                {
                    var message = call.ResponseStream.Current;
                    Console.WriteLine(message);
                }
            });
            while (true)
            {
                var result = Console.ReadKey(intercept: true);
                if (result.Key == ConsoleKey.Escape)
                {
                    break;
                }
                await call.RequestStream.WriteAsync(new HelloMessage.HelloMessageRequest() { Name = "tim lv" });
            }
            await call.RequestStream.CompleteAsync();
            await readTask;
            Console.ReadLine();
        }
```

**Comment by jtattermusch** [comment]
From your code example, I don't see which task is always in the state "WaitingForActivation" in Grpc.Core (and is not in that state when using grpc-dotnet). Can you clarify that.
From your code example I also don't understand why the behavior you're experiencing is problematic.

**Comment by lv-conner** [comment]
> From your code example, I don't see which task is always in the state "WaitingForActivation" in Grpc.Core (and is not in that state when using grpc-dotnet). Can you clarify that.
> From your code example I also don't understand why the behavior you're experiencing is problematic.

Thank you for your attention。the read task is always in WaitingForActivation status  when i use .net core 3.0.100-preview9-014004 .After i upgrade .net core preview 9 to .net core rc1。the read task work ！ i'm try to uninstall the rc1 and reinstall the preview 9 ,but the rc1 install with vs2019 preview。so i think this may be the .net core preview9 issue and they fix it in rc1。
