### ISSUE TITLE
Linker error when building grpc: 'recompile with -fPIC'

### ISSUE THREAD

**Issue by brunojadami** [grpc/grpc#20279]
### What version of gRPC and what language are you using?
C++, 1.22.1

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

### What did you do?
Just tried to download and build it with make:

```
git clone https://github.com/grpc/grpc/
cd grpc
git checkout tags/v1.22.1
git submodule update --init
make
```

### What did you expect to see?
Success?

### What did you see instead?
```
[LD]      Linking /home/bruno/Desktop/herooj/libs/grpc/libs/opt/libgrpc++_error_details.so.1.22.0
/usr/bin/ld: //usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_PC32 against symbol `_ZN6google8protobuf8internal9ArenaImpl23lifecycle_id_generator_E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:6462: recipe for target '/home/bruno/Desktop/herooj/libs/grpc/libs/opt/libgrpc++_error_details.so.1.22.0' failed
```

Full output after make in: [https://pastebin.com/KxEiPvaT](https://pastebin.com/KxEiPvaT)

### Anything else we should know about your project / environment?
On my notebook it worked, but on my Desktop it fails with that. My Notebook is Intel while my Desktop is AMD, which I suspect needs to be compiled 'pic-enabled'?

Let me know if you need any more info.

Thanks in advance

**Comment by brunojadami** [comment]
I notice that it is trying to use my version of the protobuf, instead of the one from the git submodules. Is that expected? I went ahead and recompiled the protobuf library with -Dprotobuf_BUILD_SHARED_LIBS=ON and now it works!

Is it expected that the make config will use my libraries instead of the git submodules ones?

Thanks (feel free to close this if that is expected)

**Comment by markdroth** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
