### ISSUE TITLE
Getting grpc errors in corporate network - "Failed to connect to remote host: FD shutdown"

### ISSUE THREAD

**Issue by btelintelo** [grpc/grpc#20276]
We are using firebase firestore in our mobile app, which uses grpc.  On iOS devices only, and on our corporate network only, we cannot connect to firestore.   We have turned on grpc logging, and see some errors:

"Failed to connect to remote host: FD shutdown"

Here is our corresponding firestore issue which gives the full logs.
https://github.com/firebase/firebase-ios-sdk/issues/3817

**Comment by muxi** [comment]
From the gRPC log it shows the TCP connection to `172.217.7.138:443` was attempted and timed out after 30s. If that is a correct IP address hosting your service, I would suspect it's something in the network that's blocking the connection. Do you have any corporate proxy/firewall in the middle?
