### ISSUE TITLE
ProtoCompiler don't support gRPC-ProtoRPC 1.14.1.

### ISSUE THREAD

**Issue by sibinlu** [grpc/grpc#20296]
We are building an SDK with gRPC in Objective-C https://github.com/tokenio/sdk-objc . After gRPC-ProtoRPC 1.14.1 is released, a lot of lint error occurs:

- ERROR | [TokenSdk/Implementation] xcodebuild:  /Users/sibinlu/token-repo/sdk-objc/src/generated/gateway/Gateway.pbrpc.m:36:17: error: no visible @interface for 'GRPCProtoService' declares the selector 'initWithHost:packageName:serviceName:callOptions:'
    - ERROR | [TokenSdk/Implementation] xcodebuild:  /Users/sibinlu/token-repo/sdk-objc/src/generated/gateway/Gateway.pbrpc.m:112:16: error: no visible @interface for 'GatewayService' declares the selector 'RPCToMethod:message:responseHandler:callOptions:responseClass:'

And I find out it happens because our SDK is using the ProtoCompiler objective-c plugin for compiling the proto files:
PODS:
  - "!ProtoCompiler (3.8.0)":
    - Protobuf (~> 3.0)
  - "!ProtoCompiler-gRPCPlugin (1.23.0)":
    - "!ProtoCompiler (= 3.8.0)"
    - gRPC-ProtoRPC (= 1.23.0)

The latest available version 3.8.0 is using gRPC-ProtoRPC 1.23.0 only, and 1.23.0 supports the error api above.

However, the latest available version of gRPC-ProtoRPC is 1.14.1 now, which all our sdk user will get after `pod update`. And the apis are not longer there in the new version, then the lint error throws.

I believe this affect all the objective c grpc users, could you fix the issue? Maybe update the ProtoCompiler to support 1.14.1?

**Comment by muxi** [comment]
I'll take a look. I believe you are talking about 1.24.1. Correct me if that's not the case

**Comment by sibinlu** [comment]
I see. It's weird that when I do `pod update` and a gRPC-ProtoRPC version is not specified, it updates me to `1.14.1`. It leads me to think `1.14.1` is newer than `1.23.0` and it is not true.

Could you take a look at how come an older version is pointed to when I do `pod update` with gRPC-ProtoRPC?

 It works all the time and it breaks suddenly from about a couple weeks ago.

When I run pod update without the versions in dependencies:
Installing gRPC 1.14.1 (was 1.23.0)
Installing gRPC-Core 1.14.1 (was 1.23.0)
Installing gRPC-ProtoRPC 1.14.1 (was 1.23.0)
Installing gRPC-RxLibrary 1.14.1 (was 1.23.0)

TokenSDK spec:
s.subspec "Implementation" do |ss|
        ss.source_files = "src/api/*.{h,c,m}","src/rpc/*.{h,c,m}","src/authorization/*.{h,c,m}","src/security/*.{h,c,m}",
                "src/util/*.{h,c,m}","src/ed25519/src/*.{h,c,m}","src/security/**/*.{h,c,m}",
                "#{gendir}/*.pbrpc.m", "#{gendir}/**/*.pbrpc.m"
        ss.ios.source_files = "src/authorization/ios/*.{h,c,m}"
        ss.requires_arc = true
        ss.public_header_files = "src/api", "src/security", "src/security/secureenclave", "src/authorization/", "src/security/token", "src/util"
        ss.ios.public_header_files =  "src/authorization/ios"
        ss.exclude_files = "**/*_test.*","**/test_*.*","**/test/*.*","**/test.*", "#{gendir}/fank/*"
        ss.dependency "BoringSSL-GRPC"
        ss.dependency "gRPC-ProtoRPC"
        ss.dependency "#{s.name}/Messages"
        ss.dependency "OrderedDictionary"
        ss.platform = :osx, '10.11'
        ss.platform = :ios, '9.0'
    end

**Comment by muxi** [comment]
I have never seen an issue like this before. If your project was depending on 1.23.0, there is not another release after that except pre-releases (and IIRC cocoapods does not take a pre-release with `pod update`), so effectively there has been no change on gRPC side that should have affected your repo. I would recommend checking any podspec or Podfile that you created for any explicit dependency onto a particular gRPC version.
