### ISSUE TITLE
Transcoding http/Json to gRPC

### ISSUE THREAD

**Issue by haseeAmarathunga** [grpc/grpc#20300]
Improve some build-in proxy server and container with gRPC, transcode http/Json to gRPC easily and quickly without using proxy servers like envoy and without containers like docker or kubernettes.

**Comment by wenbozhu** [comment]
Could you clarify your question, as whether you have specific problems with using Envoy, or you want to see other proxies to be developed, and if so, what you have in mind?

**Comment by markdroth** [comment]
This hasn't received any response from the user in a long time, so closing as stale.
