### ISSUE TITLE
service_config_test fails on gcc4.8

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#20318]
### What version of gRPC and what language are you using?
C++, latest version

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc4.8

### What did you do?
Looked at our portability suite runs on master and saw the gcc4.8 tests failing on master because of the service_config_test

Local repro: sudo tools/run_tests/run_tests.py -c dbg --compiler gcc4.8 --regex service_config_test -l c++ --use_docker -j 8

### What did you expect to see?
The test should pass

### What did you see instead?
The test fails.

The issue is that std::regex doesn't functionally work in gcc4.8, although it compiles. 

I'm making a workaround that skips the test for gcc4.8. However, I recommend either:
1) yashkt@ confirming that the test behavior should be identical across compilers and closing this bug or
2) Reworking the test to use something besides std::regex when running under gcc4.8

**Comment by yashykt** [comment]
I think as long as we have tests running on a working compiler, it should be fine to disable it for a compiler under gcc4.8

**Comment by hcaseyal** [comment]
Thanks for the confirmation, yashykt. I'll close this and proceed with the workaround.

**Comment by hcaseyal** [comment]
Apparently my fix didn't quite work...while it did disable tests from running on gcc4.8 and below, it also disables them from running on clang (thanks to roth@ for reporting). We're still thinking about the right solution here.

According to nnoble@, the original issue is actually due to libstdc++, not gcc4.8. The reason it manifested only in older versions of gcc is that gcc and libstdc++ release in lockstep. Clang does not do this lockstep release and just uses whatever libstdc++ that's installed. 

The right thing to do here is to check for the version of libstdc++ that's installed; however, there's apparently no good way to do this.
