### ISSUE TITLE
[Flake] test/core/channel:channelz_test@poller=epoll1

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#20324]
test/core/channel/channelz_test.cc:302
Expected equality of these values:
  millis1
    Which is: 351
  millis2
    Which is: 352
test/core/channel/channelz_test.cc:308
Expected equality of these values:
  millis1
    Which is: 351
  millis3
    Which is: 352

https://source.cloud.google.com/results/invocations/c1bb890c-6d30-48a4-a39c-ec2685813ba0/targets/%2F%2Ftest%2Fcore%2Fchannel:channelz_test@poller%3Depoll1/tests;group=ChannelzChannelTestSweep%2FChannelzChannelTest;test=LastCallStartedMillis%2F4;row=1

**Comment by hcaseyal** [comment]
Saw this on the macOS tests as well

[ RUN      ] ChannelzChannelTestSweep/ChannelzChannelTest.LastCallStartedMillis/2
test/core/channel/channelz_test.cc:308: Failure
Expected equality of these values:
  millis1
    Which is: 1
  millis3
    Which is: 2
[  FAILED  ] ChannelzChannelTestSweep/ChannelzChannelTest.LastCallStartedMillis/2, where GetParam() = 64 (6 ms)

https://source.cloud.google.com/results/invocations/d201fe20-81ae-4a1c-a3bc-e132d553a348/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp/log

**Comment by markdroth** [comment]
Closing this as a dup of #22185.
