### ISSUE TITLE
unresolved external symbol 

### ISSUE THREAD

**Issue by mohit83k** [grpc/grpc#20335]
I am trying to build GRPC on windows machine. I'm getting following errors. 

`1>facialpluginpoc.grpc.pb.obj : error LNK2019: unresolved external symbol "public: __thiscall google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QAE@W4LogLevel@23@PBDH@Z) referenced in function "int __cdecl google::protobuf::internal::ToIntSize(unsigned int)" (?ToIntSize@internal@protobuf@google@@YAHI@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: __thiscall google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QAE@W4LogLevel@23@PBDH@Z)
1>facialpluginpoc.grpc.pb.obj : error LNK2019: unresolved external symbol "public: __thiscall google::protobuf::internal::LogMessage::~LogMessage(void)" (??1LogMessage@internal@protobuf@google@@QAE@XZ) referenced in function "int __cdecl google::protobuf::internal::ToIntSize(unsigned int)" (?ToIntSize@internal@protobuf@google@@YAHI@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: __thiscall google::protobuf::internal::LogMessage::~LogMessage(void)" (??1LogMessage@internal@protobuf@google@@QAE@XZ)
1>facialpluginpoc.grpc.pb.obj : error LNK2019: unresolved external symbol "public: class google::protobuf::internal::LogMessage & __thiscall google::protobuf::internal::LogMessage::operator<<(char const *)" (??6LogMessage@internal@protobuf@google@@QAEAAV0123@PBD@Z) referenced in function "int __cdecl google::protobuf::internal::ToIntSize(unsigned int)" (?ToIntSize@internal@protobuf@google@@YAHI@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: class google::protobuf::internal::LogMessage & __thiscall google::protobuf::internal::LogMessage::operator<<(char const *)" (??6LogMessage@internal@protobuf@google@@QAEAAV0123@PBD@Z)
1>facialpluginpoc.grpc.pb.obj : error LNK2019: unresolved external symbol "public: void __thiscall google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QAEXAAVLogMessage@123@@Z) referenced in function "int __cdecl google::protobuf::internal::ToIntSize(unsigned int)" (?ToIntSize@internal@protobuf@google@@YAHI@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: void __thiscall google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QAEXAAVLogMessage@123@@Z)
1>facialpluginpoc.grpc.pb.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const *,int)" (?WriteAliasedRaw@ZeroCopyOutputStream@io@protobuf@google@@UAE_NPBXH@Z)
1>facialpluginpoc.grpc.pb.obj : error LNK2019: unresolved external symbol "public: bool __thiscall google::protobuf::MessageLite::ParseFromZeroCopyStream(class google::protobuf::io::ZeroCopyInputStream *)" (?ParseFromZeroCopyStream@MessageLite@protobuf@google@@QAE_NPAVZeroCopyInputStream@io@23@@Z) referenced in function "class grpc::Status __cdecl grpc::GenericDeserialize<class grpc::ProtoBufferReader,class facialpluginpoc::NoParams>(class grpc::ByteBuffer *,class google::protobuf::MessageLite *)" (??$GenericDeserialize@VProtoBufferReader@grpc@@VNoParams@facialpluginpoc@@@grpc@@YA?AVStatus@0@PAVByteBuffer@0@PAVMessageLite@protobuf@google@@@Z)
1>facialpluginpoc.grpc.pb.obj : error LNK2019: unresolved external symbol "public: bool __thiscall google::protobuf::MessageLite::SerializeToZeroCopyStream(class google::protobuf::io::ZeroCopyOutputStream *)const " (?SerializeToZeroCopyStream@MessageLite@protobuf@google@@QBE_NPAVZeroCopyOutputStream@io@23@@Z) referenced in function "class grpc::Status __cdecl grpc::GenericSerialize<class grpc::ProtoBufferWriter,class facialpluginpoc::NoParams>(class google::protobuf::MessageLite const &,class grpc::ByteBuffer *,bool *)" (??$GenericSerialize@VProtoBufferWriter@grpc@@VNoParams@facialpluginpoc@@@grpc@@YA?AVStatus@0@ABVMessageLite@protobuf@google@@PAVByteBuffer@0@PA_N@Z)
1>facialpluginpoc.grpc.pb.obj : error LNK2001: unresolved external symbol "class grpc::CoreCodegenInterface * grpc::g_core_codegen_interface" (?g_core_codegen_interface@grpc@@3PAVCoreCodegenInterface@1@A)
1>facialpluginpoc.grpc.pb.obj : error LNK2001: unresolved external symbol "class grpc::GrpcLibraryInterface * grpc::g_glip" (?g_glip@grpc@@3PAVGrpcLibraryInterface@1@A)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::VerifyVersion(int,int,char const *)" (?VerifyVersion@internal@protobuf@google@@YAXHHPBD@Z) referenced in function "void __cdecl InitDefaultsscc_info_NoParams_facialpluginpoc_2eproto(void)" (?InitDefaultsscc_info_NoParams_facialpluginpoc_2eproto@@YAXXZ)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::OnShutdownRun(void (__cdecl*)(void const *),void const *)" (?OnShutdownRun@internal@protobuf@google@@YAXP6AXPBX@Z0@Z) referenced in function "void __cdecl google::protobuf::internal::OnShutdownDestroyMessage(void const *)" (?OnShutdownDestroyMessage@internal@protobuf@google@@YAXPBX@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "private: __int64 __thiscall google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int)" (?ReadVarint32Fallback@CodedInputStream@io@protobuf@google@@AAE_JI@Z) referenced in function "public: bool __thiscall google::protobuf::io::CodedInputStream::ReadVarint32(unsigned int *)" (?ReadVarint32@CodedInputStream@io@protobuf@google@@QAE_NPAI@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "private: unsigned int __thiscall google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)" (?ReadTagFallback@CodedInputStream@io@protobuf@google@@AAEII@Z) referenced in function "public: struct std::pair<unsigned int,bool> __thiscall google::protobuf::io::CodedInputStream::ReadTagWithCutoffNoLastTag(unsigned int)" (?ReadTagWithCutoffNoLastTag@CodedInputStream@io@protobuf@google@@QAE?AU?$pair@I_N@std@@I@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static unsigned char * __cdecl google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char *)" (?WriteStringWithSizeToArray@CodedOutputStream@io@protobuf@google@@SAPAEABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAE@Z) referenced in function "public: static unsigned char * __cdecl google::protobuf::internal::WireFormatLite::WriteBytesToArray(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char *)" (?WriteBytesToArray@WireFormatLite@internal@protobuf@google@@SAPAEHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAE@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: void * __thiscall google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned int)" (?AllocateAligned@ArenaImpl@internal@protobuf@google@@QAEPAXI@Z) referenced in function "private: void * __thiscall google::protobuf::Arena::AllocateInternal<struct google::protobuf::internal::InternalMetadataWithArenaBase<class google::protobuf::UnknownFieldSet,class google::protobuf::internal::InternalMetadataWithArena>::Container>(bool)" (??$AllocateInternal@UContainer@?$InternalMetadataWithArenaBase@VUnknownFieldSet@protobuf@google@@VInternalMetadataWithArena@internal@23@@internal@protobuf@google@@@Arena@protobuf@google@@AAEPAX_N@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: void * __thiscall google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned int,void (__cdecl*)(void *))" (?AllocateAlignedAndAddCleanup@ArenaImpl@internal@protobuf@google@@QAEPAXIP6AXPAX@Z@Z) referenced in function "private: void * __thiscall google::protobuf::Arena::AllocateInternal<struct google::protobuf::internal::InternalMetadataWithArenaBase<class google::protobuf::UnknownFieldSet,class google::protobuf::internal::InternalMetadataWithArena>::Container>(bool)" (??$AllocateInternal@UContainer@?$InternalMetadataWithArenaBase@VUnknownFieldSet@protobuf@google@@VInternalMetadataWithArena@internal@23@@internal@protobuf@google@@@Arena@protobuf@google@@AAEPAX_N@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: void __thiscall google::protobuf::internal::ArenaImpl::AddCleanup(void *,void (__cdecl*)(void *))" (?AddCleanup@ArenaImpl@internal@protobuf@google@@QAEXPAXP6AX0@Z@Z) referenced in function "private: void __thiscall google::protobuf::Arena::OwnInternal<class google::protobuf::Message>(class google::protobuf::Message *,struct std::integral_constant<bool,1>)" (??$OwnInternal@VMessage@protobuf@google@@@Arena@protobuf@google@@AAEXPAVMessage@12@U?$integral_constant@_N$00@std@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "private: void __thiscall google::protobuf::Arena::OnArenaAllocation(class type_info const *,unsigned int)const " (?OnArenaAllocation@Arena@protobuf@google@@ABEXPBVtype_info@@I@Z) referenced in function "private: void __thiscall google::protobuf::Arena::AllocHook(class type_info const *,unsigned int)const " (?AllocHook@Arena@protobuf@google@@ABEXPBVtype_info@@I@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual class google::protobuf::MessageLite * __thiscall google::protobuf::MessageLite::New(class google::protobuf::Arena *)const " (?New@MessageLite@protobuf@google@@UBEPAV123@PAVArena@23@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall google::protobuf::MessageLite::InitializationErrorString(void)const " (?InitializationErrorString@MessageLite@protobuf@google@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::MessageLite::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@MessageLite@protobuf@google@@UBEXPAVCodedOutputStream@io@23@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual unsigned char * __thiscall google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char *)const " (?SerializeWithCachedSizesToArray@MessageLite@protobuf@google@@UBEPAEPAE@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual unsigned char * __thiscall google::protobuf::MessageLite::InternalSerializeWithCachedSizesToArray(unsigned char *)const " (?InternalSerializeWithCachedSizesToArray@MessageLite@protobuf@google@@UBEPAEPAE@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static bool __cdecl google::protobuf::internal::WireFormatLite::ReadBytes(class google::protobuf::io::CodedInputStream *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?ReadBytes@WireFormatLite@internal@protobuf@google@@SA_NPAVCodedInputStream@io@34@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: virtual bool __thiscall facialpluginpoc::Result::MergePartialFromCodedStream(class google::protobuf::io::CodedInputStream *)" (?MergePartialFromCodedStream@Result@facialpluginpoc@@UAE_NPAVCodedInputStream@io@protobuf@google@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static void __cdecl google::protobuf::internal::WireFormatLite::WriteInt32(int,int,class google::protobuf::io::CodedOutputStream *)" (?WriteInt32@WireFormatLite@internal@protobuf@google@@SAXHHPAVCodedOutputStream@io@34@@Z) referenced in function "public: virtual void __thiscall facialpluginpoc::Result::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@Result@facialpluginpoc@@UBEXPAVCodedOutputStream@io@protobuf@google@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static void __cdecl google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class google::protobuf::io::CodedOutputStream *)" (?WriteBytesMaybeAliased@WireFormatLite@internal@protobuf@google@@SAXHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAVCodedOutputStream@io@34@@Z) referenced in function "public: virtual void __thiscall facialpluginpoc::Result::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@Result@facialpluginpoc@@UBEXPAVCodedOutputStream@io@protobuf@google@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::InitSCCImpl(struct google::protobuf::internal::SCCInfoBase *)" (?InitSCCImpl@internal@protobuf@google@@YAXPAUSCCInfoBase@123@@Z) referenced in function "void __cdecl google::protobuf::internal::InitSCC(struct google::protobuf::internal::SCCInfoBase *)" (?InitSCC@internal@protobuf@google@@YAXPAUSCCInfoBase@123@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::DestroyMessage(void const *)" (?DestroyMessage@internal@protobuf@google@@YAXPBX@Z) referenced in function "void __cdecl google::protobuf::internal::OnShutdownDestroyMessage(void const *)" (?OnShutdownDestroyMessage@internal@protobuf@google@@YAXPBX@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: void __thiscall google::protobuf::UnknownFieldSet::MergeFrom(class google::protobuf::UnknownFieldSet const &)" (?MergeFrom@UnknownFieldSet@protobuf@google@@QAEXABV123@@Z) referenced in function "public: void __thiscall google::protobuf::internal::InternalMetadataWithArena::DoMergeFrom(class google::protobuf::UnknownFieldSet const &)" (?DoMergeFrom@InternalMetadataWithArena@internal@protobuf@google@@QAEXABVUnknownFieldSet@34@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static class google::protobuf::UnknownFieldSet const * __cdecl google::protobuf::UnknownFieldSet::default_instance(void)" (?default_instance@UnknownFieldSet@protobuf@google@@SAPBV123@XZ) referenced in function "public: static class google::protobuf::UnknownFieldSet const & __cdecl google::protobuf::internal::InternalMetadataWithArena::default_instance(void)" (?default_instance@InternalMetadataWithArena@internal@protobuf@google@@SAABVUnknownFieldSet@34@XZ)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "private: void __thiscall google::protobuf::UnknownFieldSet::ClearFallback(void)" (?ClearFallback@UnknownFieldSet@protobuf@google@@AAEXXZ) referenced in function "public: void __thiscall google::protobuf::UnknownFieldSet::Clear(void)" (?Clear@UnknownFieldSet@protobuf@google@@QAEXXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::Message::CopyFrom(class google::protobuf::Message const &)" (?CopyFrom@Message@protobuf@google@@UAEXABV123@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::Message::MergeFrom(class google::protobuf::Message const &)" (?MergeFrom@Message@protobuf@google@@UAEXABV123@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall google::protobuf::Message::InitializationErrorString(void)const " (?InitializationErrorString@Message@protobuf@google@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::Message::DiscardUnknownFields(void)" (?DiscardUnknownFields@Message@protobuf@google@@UAEXXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual unsigned int __thiscall google::protobuf::Message::SpaceUsedLong(void)const " (?SpaceUsedLong@Message@protobuf@google@@UBEIXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall google::protobuf::Message::GetTypeName(void)const " (?GetTypeName@Message@protobuf@google@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::Message::Clear(void)" (?Clear@Message@protobuf@google@@UAEXXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall google::protobuf::Message::IsInitialized(void)const " (?IsInitialized@Message@protobuf@google@@UBE_NXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::Message::CheckTypeAndMergeFrom(class google::protobuf::MessageLite const &)" (?CheckTypeAndMergeFrom@Message@protobuf@google@@UAEXABVMessageLite@23@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall google::protobuf::Message::MergePartialFromCodedStream(class google::protobuf::io::CodedInputStream *)" (?MergePartialFromCodedStream@Message@protobuf@google@@UAE_NPAVCodedInputStream@io@23@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual unsigned int __thiscall google::protobuf::Message::ByteSizeLong(void)const " (?ByteSizeLong@Message@protobuf@google@@UBEIXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::Message::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@Message@protobuf@google@@UBEXPAVCodedOutputStream@io@23@@Z)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "private: virtual void __thiscall google::protobuf::Message::SetCachedSize(int)const " (?SetCachedSize@Message@protobuf@google@@EBEXH@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::AssignDescriptors(struct google::protobuf::internal::DescriptorTable const *)" (?AssignDescriptors@internal@protobuf@google@@YAXPBUDescriptorTable@123@@Z) referenced in function "private: static struct google::protobuf::Metadata __cdecl facialpluginpoc::NoParams::GetMetadataStatic(void)" (?GetMetadataStatic@NoParams@facialpluginpoc@@CA?AUMetadata@protobuf@google@@XZ)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::AddDescriptors(struct google::protobuf::internal::DescriptorTable const *)" (?AddDescriptors@internal@protobuf@google@@YAXPBUDescriptorTable@123@@Z) referenced in function "void __cdecl `dynamic initializer for 'dynamic_init_dummy_facialpluginpoc_2eproto''(void)" (??__Edynamic_init_dummy_facialpluginpoc_2eproto@@YAXXZ)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static void __cdecl google::protobuf::internal::ReflectionOps::Merge(class google::protobuf::Message const &,class google::protobuf::Message *)" (?Merge@ReflectionOps@internal@protobuf@google@@SAXABVMessage@34@PAV534@@Z) referenced in function "public: virtual void __thiscall facialpluginpoc::NoParams::MergeFrom(class google::protobuf::Message const &)" (?MergeFrom@NoParams@facialpluginpoc@@UAEXABVMessage@protobuf@google@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static bool __cdecl google::protobuf::internal::WireFormat::SkipField(class google::protobuf::io::CodedInputStream *,unsigned int,class google::protobuf::UnknownFieldSet *)" (?SkipField@WireFormat@internal@protobuf@google@@SA_NPAVCodedInputStream@io@34@IPAVUnknownFieldSet@34@@Z) referenced in function "public: virtual bool __thiscall facialpluginpoc::NoParams::MergePartialFromCodedStream(class google::protobuf::io::CodedInputStream *)" (?MergePartialFromCodedStream@NoParams@facialpluginpoc@@UAE_NPAVCodedInputStream@io@protobuf@google@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static void __cdecl google::protobuf::internal::WireFormat::SerializeUnknownFields(class google::protobuf::UnknownFieldSet const &,class google::protobuf::io::CodedOutputStream *)" (?SerializeUnknownFields@WireFormat@internal@protobuf@google@@SAXABVUnknownFieldSet@34@PAVCodedOutputStream@io@34@@Z) referenced in function "public: virtual void __thiscall facialpluginpoc::NoParams::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@NoParams@facialpluginpoc@@UBEXPAVCodedOutputStream@io@protobuf@google@@@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static unsigned char * __cdecl google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(class google::protobuf::UnknownFieldSet const &,unsigned char *)" (?SerializeUnknownFieldsToArray@WireFormat@internal@protobuf@google@@SAPAEABVUnknownFieldSet@34@PAE@Z) referenced in function "public: virtual unsigned char * __thiscall facialpluginpoc::NoParams::InternalSerializeWithCachedSizesToArray(unsigned char *)const " (?InternalSerializeWithCachedSizesToArray@NoParams@facialpluginpoc@@UBEPAEPAE@Z)
1>facialpluginpoc.pb.obj : error LNK2019: unresolved external symbol "public: static unsigned int __cdecl google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(class google::protobuf::UnknownFieldSet const &)" (?ComputeUnknownFieldsSize@WireFormat@internal@protobuf@google@@SAIABVUnknownFieldSet@34@@Z) referenced in function "public: virtual unsigned int __thiscall facialpluginpoc::NoParams::ByteSizeLong(void)const " (?ByteSizeLong@NoParams@facialpluginpoc@@UBEIXZ)
1>facialpluginpoc.pb.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
1>Test.obj : error LNK2019: unresolved external symbol "class std::shared_ptr<class grpc_impl::ServerCredentials> __cdecl grpc_impl::InsecureServerCredentials(void)" (?InsecureServerCredentials@grpc_impl@@YA?AV?$shared_ptr@VServerCredentials@grpc_impl@@@std@@XZ) referenced in function "class std::shared_ptr<class grpc_impl::ServerCredentials> __cdecl grpc::InsecureServerCredentials(void)" (?InsecureServerCredentials@grpc@@YA?AV?$shared_ptr@VServerCredentials@grpc_impl@@@std@@XZ)
1>Test.obj : error LNK2019: unresolved external symbol "public: __thiscall grpc_impl::ServerBuilder::ServerBuilder(void)" (??0ServerBuilder@grpc_impl@@QAE@XZ) referenced in function "void __cdecl RunServer(void)" (?RunServer@@YAXXZ)
1>Test.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall grpc_impl::ServerBuilder::~ServerBuilder(void)" (??1ServerBuilder@grpc_impl@@UAE@XZ) referenced in function "void __cdecl RunServer(void)" (?RunServer@@YAXXZ)
1>Test.obj : error LNK2019: unresolved external symbol "public: virtual class std::unique_ptr<class grpc_impl::Server,struct std::default_delete<class grpc_impl::Server> > __thiscall grpc_impl::ServerBuilder::BuildAndStart(void)" (?BuildAndStart@ServerBuilder@grpc_impl@@UAE?AV?$unique_ptr@VServer@grpc_impl@@U?$default_delete@VServer@grpc_impl@@@std@@@std@@XZ) referenced in function "void __cdecl RunServer(void)" (?RunServer@@YAXXZ)
1>Test.obj : error LNK2019: unresolved external symbol "public: class grpc_impl::ServerBuilder & __thiscall grpc_impl::ServerBuilder::RegisterService(class grpc::Service *)" (?RegisterService@ServerBuilder@grpc_impl@@QAEAAV12@PAVService@grpc@@@Z) referenced in function "void __cdecl RunServer(void)" (?RunServer@@YAXXZ)
1>Test.obj : error LNK2019: unresolved external symbol "public: class grpc_impl::ServerBuilder & __thiscall grpc_impl::ServerBuilder::AddListeningPort(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::shared_ptr<class grpc_impl::ServerCredentials>,int *)" (?AddListeningPort@ServerBuilder@grpc_impl@@QAEAAV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$shared_ptr@VServerCredentials@grpc_impl@@@4@PAH@Z) referenced in function "void __cdecl RunServer(void)" (?RunServer@@YAXXZ)`

**Comment by veblush** [comment]
Please give us more context using the default template. I'm closing this and feel free to reopen this with more detail.
