### ISSUE TITLE
Feature request: `channel_from_env` method

### ISSUE THREAD

**Issue by michaelsafyan** [grpc/grpc#20330]
### Is your feature request related to a problem? Please describe.

Sort of. The problem is that servers often need to connect to clients using different methods depending on configuration / environment. For example, while in production, a server may want to connect over a secure channel, in debug/test environments, it may be desireable to connect to an insecure channel. A lot of this logic will be redundant across servers, and so it would be ideal to have a common, standard way to do this which isn't highly varied by server.

### Describe the solution you'd like

I'd like there to be a simple interface like:

```
channel = grpc.channel_from_env(prefix='MY_BACKEND')
```

That will automatically look for environment variables according to the prefix in order to select the appropriate channel type. For example, the above might look for things like:

```
MY_BACKEND_ADDRESS
MY_BACKEND_ENCRYPTION_ENABLED
MY_BACKEND_ENCRYPTION_ALGORITHM
MY_BACKEND_ENCRYPTION_PRIVATE_KEY
MY_BACKEND_ENCRYPTION_PUBLIC_KEY
MY_BACKEND_COMPRESSION_ENABLED
MY_BACKEND_COMPRESSION_ALGORITHM
MY_BACKEND_COMPRESSION_LEVEL
...
```

... And, based on the above set of environment variables, determine the appropriate connection type (secure vs insecure, if secure which credentials to use, etc.). Basically, this would offload a lot of that logic out of client code and into configuration in a more uniform way.

### Describe alternatives you've considered
An alternative would be a method like `grpc.channel_from_string` which has the disadvantage of requiring a lot of configuration to be encoded into a single string (likely to be more error-prone and less readable than separating configuration into separate variables/lines that aren't just a single string). Another alternative would be to support something more generic like `grpc.channnel_from_config` where `os.getenv` is one way to resolve configuration keys, but where the keys can come from elsewhere like a file. Personally, I would recommend and approach like that as an implementation detail of `channel_from_env` so that `channel_from_env(prefix=prefix)` is simply a more convenient way to do `channel_from_config(prefix=prefix, resolver=os.getenv)`.

**Comment by markdroth** [comment]
From the proposed code snippet, I assume you're asking about Python.  I am reassigning this to one of our python folks.

**Comment by michaelsafyan** [comment]
Yes. My primary concern/request is for Python, though it would be ideal to have the equivalent capability/feature supported in the clients for all languages (so that a common standard of how to define such environment variables would apply to all servers regardless of implementation language). Consider this oughly an equivalent to the internal "smartservice" concept (but defined in terms of environment variables rather than commandline flags).

**Comment by markdroth** [comment]
If you want this as a cross-language feature, then @a11r should probably weigh in.

My gut inclination is that this is not something that gRPC should be providing.  I think applications that need this can provide something like this on their own.
