### ISSUE TITLE
server.wait_for_termination()

### ISSUE THREAD

**Issue by 90h** [grpc/grpc#20333]
server.wait_for_termination()
AttributeError: '_Server' object has no attribute 'wait_for_termination'

**Comment by veblush** [comment]
Please give us more context using the default template. I'm closing this and feel free to reopen this with more detail.

**Comment by AngularPadawan** [comment]
I think this refers to the error you get when you use the current master version of the helloworld example. You need to use the version from the respective release branch (e.g. 1.23.xx).
