### ISSUE TITLE
Build fails on MacOS (link error)

### ISSUE THREAD

**Issue by tsvisabo** [grpc/grpc#20332]
### What version of gRPC and what language are you using?
1.22.0

### What operating system (Linux, Windows,...) and version?
MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang 10.0.1

### What did you do?
Tried to build grpc as a dependency using Bazel

### What did you see instead?

ld: illegal thread local variable reference to regular symbol __ZN9grpc_core7ExecCtx9exec_ctx_E for architecture x86_64

**Comment by veblush** [comment]
It seems to be the same issue with #13856 and it's supposed to be fixed. @vjpai can you take a look at this?

**Comment by gmishkin** [comment]
Loathe to add a “me too” but I subscribed to this a while back because I’m having the same issue. And I just got a notification and was excited but it was the stale bot so I thought I’d chime in!

**Comment by markdroth** [comment]
Duplicate of #13856.
