### ISSUE TITLE
Fail to new an instance of gRPC.Core.Channel when code run in Partial Trust

### ISSUE THREAD

**Issue by EthanXiaQun** [grpc/grpc#20346]
### What version of gRPC and what language are you using?
Grpc version 2.23.0 using C#.

### What operating system (Linux, Windows,...) and version?
The OS is Windows Server 2016 Standard. 

### What runtime / compiler are you using (e.g. python version or version of gcc)
I am trying to use Grpc.Core.Channel call a gRPC service. When code run in Partial Trust environment, an error below would pop up.

"Inheritance security rules violated by Type:'Grpc.Core.internal.SafeHandleZeroIsInvalid' Derived types must either match the security accessibility of the base type or be less accessible"

### What did you do?
Look into gRPC code, a .net class SafeHandle is inherited by SafeHandleZeroIsInvalid. As official document described, for partially trusted code, it’s not allowed. InheritanceDemand of SafeHandle is: "for full trust for inheritors. This member cannot be inherited by partially trusted code." https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle?view=netframework-4.8

I had a try to create my own class which inherited from SafeHandle. And, I tryed to new an instance of this class. When code run in Partial Trust, the same error pop up. What I am thinking the SafeHandle is the root reason cause this problem.
//the code is super simple, I just try to create a channel on a constructor. 
public class WriterClient
{
    private Channel _channel;
    private LoggingCenter _logger;
    public WriterClient(int port, ILogging logger)
    {
        _logger = logger == null? new LoggingCenter(new NullLogger()): new LoggingCenter(logger);
        //when run in Partial Trust, the code below will throw an exception.
        _channel = new Channel("127.0.0.1", port, ChannelCredentials.Insecure);            
    }
### What did you expect to see?
When code run in partial trust environment, Channel can be used to call a gRPC service.

### What did you see instead?
The type initializer for 'Cxxx.TimerssFactory' threw an exception.
at Finance.Executives.CLM_ExecutiveOrderBookings(String View, Nullable`1 Detail, String SiteGroup, Nullable`1 DateStarting, Nullable`1 DateEnding, String FilterString)

Inheritance security rules violated by type: 'Grpc.Core.Internal.SafeHandleZeroIsInvalid'. Derived types must either match the security accessibility of the base type or be less accessible.

at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
at Client.NLogFlatXMLWriterClient..ctor(Int32 port, ILogging logger)
at Cxxx.TimerssFactory..cctor()

### Anything else we should know about your project / environment?
The project is .NET Standard 2.0. 
Grpc (2.23.0) is gotten through NUGet.

**Comment by jtattermusch** [comment]
What is the situation in which you need to run in "Partial Trust" mode?
Grpc.Core is using a native library internally and I think for that you need to be in a fully trusted mode (and there's no way to work around that).

**Comment by EthanXiaQun** [comment]
Our product needs to be run on Amazon Cloud. Limited Customization is allowed too. For security consideration, the code needs to be run with limited permission. "Partial Trust" mode is selected here. 

When call Grpc service, except Channel, could we have another method for it? 

I go through the generated C# code according to Protobuf definition, for Client, the second way is to use CallInvoker. The definition is below.
/// <summary>Creates a new client for LogWriter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LogWriterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
However, how can I create a CallInvoker? 
Seems, we still need to have an instead of Channel first, right?

Any suggestion is welcome!
Thanks a lot!

**Comment by EthanXiaQun** [comment]
What about using Channel in C++ assembly to call C# Grpc Service? Does it work in "Partial Trust" Mode?
Plan steps:
1. Create a new C++ project in Visual Studio and referent the defined Protobuf. After that, the Client code can be generated in C++.
2. On C# side, a service will still be established using C# code
3. When consume Grpc service, the C++ class created on step1 will be used here which will still be called by C# code.
If so, SafeHandle will not be created when create Channel. 
However, if the calling native library is the key problem which cause code fail running in "Partial Trust" mode, this way would not work too.

Any suggestion is welcome!

**Comment by EthanXiaQun** [comment]
Since "Partial Trust" mode would be needed on Cloud, at least on my case, what about enhancing this part allow Grpc running in "Partial Trust" mode?

**Comment by jtattermusch** [comment]
IMHO, with a native library in play, you just won't be able to run things in "partial trust" mode and efforts to work around that are not going to be very fruitful (feel free to try though).
