### ISSUE TITLE
Ipv6 not matched with compacted and fully qualified representation

### ISSUE THREAD

**Issue by linxiulei** [grpc/grpc#20342]
### What version of gRPC and what language are you using?

1.16/cpp

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

python3.7

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Client connects to server with ipv6

### What did you expect to see?

Connect successfully with any representation of ipv6 as long as they are valid

### What did you see instead?

The server complaints "servername :::::::056a not found". However there is :::::::56a in SANs within certificate.

GRPC simply compare the ipaddress strings here. https://github.com/grpc/grpc/blob/c379323b3140cb62efe7c1aa9ce984fc575cc7b3/src/core/tsi/ssl_transport_security.cc#L1941

And the property of ipaddress string was populated by inet_ntop(), which returns compacted representation. Maybe we should also compact it when comparing them.

**Comment by gnossen** [comment]
@linxiulei Can you please provide a little more detail on your setup? You say you're using "1.16/cpp" but then say you're using "python3.7". What's the setup here? A python client and a c++ server?

How are you connecting to the server? With a secure channel? Have you verified that you can successfully connect with an insecure channel? Can you give us your full error message?

**Comment by linxiulei** [comment]
> @linxiulei Can you please provide a little more detail on your setup? You say you're using "1.16/cpp" but then say you're using "python3.7". What's the setup here? A python client and a c++ server?
> 

Yes, you're correct

> How are you connecting to the server? With a secure channel? Have you verified that you can successfully connect with an insecure channel? Can you give us your full error message?

Yes, I setup a secure server with IPV6 in its cert. I can successfully connect it if I used compacted ipv6 e.g ":::::::56a".

Sorry, I don't have the env handy now. I had to work it around with using compacted ipv6, but I still think full qualified representation should be also acceptable

Thanks

**Comment by gnossen** [comment]
CC @yihuazhang
