### ISSUE TITLE
The gRPC object creates extra processes that don't close

### ISSUE THREAD

**Issue by maxf9** [grpc/grpc#20365]
### What version of gRPC and what language are you using?
Python 2.7.12
grpcio==1.16.1
grpcio-tools==1.16.1

### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04.6 LTS 
4.4.0-143-generic

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.12

### What did you do?
I developed the application with gRPC servicer. The point of my application is: 
1) gRPC servicer (class **DexFxServicer** in the code below) has **Transmit** method which is called by gRPC client outside.
2) **Transmit** method creates multiple channels and stubs for the different hosts from hostList.
3) Further application creates the process pool and launches it. 
4) Each child process calls gRPC method **SendHostListAndGetMetrics** for its own stub and receives response iterator. 

This code works well, the application invokes **Transmit** method and receive all needed results from the process pool. But I noticed when outside gRPC client calls **Transmit** method  multiple times, this code didn't close some of its child processes. And it leads to extra nonclosing processes creation as htop shows.
When I try to close gRPC channels by channel.close() method, extra processes are being created more intensively.   

```Python
from concurrent import futures
import sleep
import grpc
import sys
import cascade_pb2
import cascade_pb2_grpc
import metrics_pb2
import metrics_pb2_grpc
from multiprocessing import Pool

class DexFxServicer(cascade_pb2_grpc.DexFxServicer):

    def __init__(self, args):
        self.args = args

    def Transmit(self, request, context):
        entrypoint = request.sender.host_address # entrypoint is a string
        hostList = []                 # hostList is a list of strings
        for rec in request.sender.receiver:
            hostList.append(rec.host_address)

        channels = {}
        stubs = {}

        for host in hostList:
            try:
                channels[host] = grpc.insecure_channel('%s:%d' % (host, self.args.cascadePort))
            except Exception as e:
                print(e)
                sys.exit(0)
            else:
                stubs[host] = metrics_pb2_grpc.MetricsStub(channels[host])

        def collect_metrics(host):
            mtrx = []
            hosts = (metrics_pb2.Host(hostname = i) for i in hostList + [entrypoint])
            for i in stubs[host].SendHostListAndGetMetrics(hosts):
                mtrx.append(i.mtrx)
            return mtrx

        pool = Pool(len(hostList))
        results = pool.map(collect_metrics, hostList)
        pool.close()
        pool.terminate()
        pool.join()
       
       # Return the iterator of the results
```

### What did you expect to see?
I expect to see the code which doesn't create extra nonclosing processes. Please, suggest me what to do in this case.

### What did you see instead?
Htop show me that the main application process creates extra processes and doesn't close some of them.

### Anything else we should know about your project / environment?
**DexFxServicer** is launched by means of the code below:

```Python
def RunCascadeClient[(args):

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
    cascade_pb2_grpc.add_DexFxServicer_to_server(DexFxServicer(args), server)
    server.add_insecure_port('[::]:%d' % 7777) 
    server.start()
    try:
        while True: time.sleep(30)
    except KeyboardInterrupt:
        print('Program has been interrupted by Ctrl+C. Exit.')
        server.stop(0)
```

**Comment by lidizheng** [comment]
Can you confirm this is a gRPC Python problem? Could this be a feature of `multiprocessing.Pool` to keep child processes around for a while? Also, can you confirm that each child processes execution is ended (finishes `collect_metrics`)?

Also, we have a fix for signal processing. Can you upgrade your gRPC Python version to see if the problem goes away?

**Comment by maxf9** [comment]
I just updated grpcio and grpcio-tools to 1.23.0 version and that solved my problem. Thanks for help.

**Comment by lidizheng** [comment]
@maxf9 Glad to hear that the problem goes away. If there isn't any more unresolved problem, please close this issue ;)
