### ISSUE TITLE
multi-threads process request  assert failed when call Finish()  C++

### ISSUE THREAD

**Issue by leaout** [grpc/grpc#20364]
### What version of gRPC and what language are you using?
Release v1.24.0-pre2 C++

### What operating system (Linux, Windows,...) and version?

Linux  ubuntu18.04
### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I build a Async Server, many threads wait for  m_complete_queue->Next(&tag,&ok)
then do something ,

when I build a async client to call server 10000 times , the server sometimes crash (assert failed)  but when i set 1 thread process  tasks it runs well.
error:
```
call_op_set.h:940]          assertion failed: GRPC_CALL_OK == g_core_codegen_interface->grpc_call_start_batch( call_.call(), ops, nops, core_cq_tag(), nullptr)
```
 m_complete_queue->Next(&tag,&ok) is thread safe.
 
ServerAsyncResponseWriter<HelloUltipaReply> m_responder;
 m_responder.Finish(m_replay, Status::OK, this); 
why when run to  Finish ,assert failed?  is the function  not thread-safe?

### What did you expect to see?
I need to know why it failed, assert failed not make sense,
maybe it should return a error code.

### What did you see instead?
assert failed.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
the stack :
__GI_raise 0x00007f279e16ae97
__GI_abort 0x00007f279e16c801
grpc::CoreCodegen::assert_fail(char const*, char const*, int) 0x00007f279f601b34
grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpServerSendStatus, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::ContinueFillOpsAfterInterception call_op_set.h:938
grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpServerSendStatus, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::FillOps call_op_set.h:869
grpc::internal::Call::PerformOps call.h:69
grpc_impl::ServerAsyncResponseWriter<ultipa::HelloUltipaReply>::Finish async_unary_call_impl.h:257
CSayHello::process SayHello.cpp:31
CAsyncServer::process AsyncServer.cpp:75
thread_process AsyncServer.cpp:84
std::__invoke_impl<void, void (*)(void*), void*> invoke.h:60
std::__invoke<void (*)(void*), void*> invoke.h:95
std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::_M_invoke<0ul, 1ul> thread:234
std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::operator() thread:243
std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), void*> > >::_M_run thread:186
<unknown> 0x00007f279e7f266f
start_thread 0x00007f279ecef6db
clone 0x00007f279e24d88f

in my code  when it step to:             
`m_responder.Finish(m_replay, Status::OK, this);`  
it crashed, and grpc code:
```
  void ContinueFillOpsAfterInterception() override {
    static const size_t MAX_OPS = 6;
    grpc_op ops[MAX_OPS];
    size_t nops = 0;
    this->Op1::AddOp(ops, &nops);
    this->Op2::AddOp(ops, &nops);
    this->Op3::AddOp(ops, &nops);
    this->Op4::AddOp(ops, &nops);
    this->Op5::AddOp(ops, &nops);
    this->Op6::AddOp(ops, &nops);
    GPR_CODEGEN_ASSERT(GRPC_CALL_OK ==
                       g_core_codegen_interface->grpc_call_start_batch(
                           call_.call(), ops, nops, core_cq_tag(), nullptr));
  }
```

protos:
```
/*------------------------1.SayHello------------------------------*/
// The request message containing the user's name.
message HelloUltipaRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloUltipaReply {
  string message = 1;
}
```
/*--------------------------SayHello----------------------------*/
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by nicolasnoble** [comment]
Please provide us with your source code so we can reproduce.

**Comment by leaout** [comment]
The AsyncServer code below.
AsyncServer.h:
`#pragma once

#include <iostream>
#include <unordered_map>
#include <grpcpp/grpcpp.h>
#include <grpc/support/log.h>
#include "../pbcpp/ultipa.grpc.pb.h"

using namespace std;

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::ServerCompletionQueue;
using grpc::ServerAsyncResponseWriter;
using grpc::Status;
using ultipa::UltipaRpcs;

class CAsyncServer final{
public:
    CAsyncServer();
    ~CAsyncServer();
    void run(string shost = "0.0.0.0:60061");
    void process();
private:
    unique_ptr<Server> m_server;
    unique_ptr<ServerCompletionQueue> m_complete_queue;
    UltipaRpcs::AsyncService m_service;
};
`
AsyncServer.cpp:

`//
// Created by curse on 2019/9/9.
//
#include <thread>
#include "AsyncServer.h"
#include "AsyncData.h"


CAsyncServer::CAsyncServer(){

}
CAsyncServer::~CAsyncServer(){
//    m_bruning = false;
    if(m_server){
        m_server->Shutdown();
    }
    if(m_complete_queue){
        m_complete_queue->Shutdown();
    }
}

void CAsyncServer::run(string shost){

    ServerBuilder m_builder;
    // Listen on the given address without any authentication mechanism.
    m_builder.AddListeningPort(shost, grpc::InsecureServerCredentials());
    // Register "service_" as the instance through which we'll communicate with
    // clients. In this case it corresponds to an *asynchronous* service.
    m_builder.RegisterService(&m_service);
    // Get hold of the completion queue used for the asynchronous communication
    // with the gRPC runtime.
    m_complete_queue = m_builder.AddCompletionQueue();
    // Finally assemble the server.
    m_server = m_builder.BuildAndStart();

    new CAsyncData(&m_service,m_complete_queue.get());

    thread th1(std::bind(&CAsyncServer::process, this));
    thread th2(std::bind(&CAsyncServer::process, this));
//    m_bruning = true;
//    start(4);
    std::cout <<"Server Listening On:"<< shost<<std::endl;

    th1.join();
    th2.join();
}

void CAsyncServer::process(){
    std::cout <<"process start!"<< std::endl;

    void* tag;
    bool ok;
    while(true){
//        bool issuc = m_complete_queue->Next(&tag,&ok);
        GPR_ASSERT(m_complete_queue->Next(&tag,&ok));
        GPR_ASSERT(ok);

        static_cast<CAsyncData*>(tag)->process();

    }
}
`
AsyncData.h AsyncData.cpp:
`//
// Created by curse on 2019/9/10.
//

#pragma once
#include <grpcpp/grpcpp.h>
#include <grpcpp/server_builder.h>
#include "../pbcpp/ultipa.grpc.pb.h"
//#include "EngineManager.h"


using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::ServerCompletionQueue;
using grpc::Status;
using ultipa::UltipaRpcs;

using ultipa::HelloUltipaRequest;
using ultipa::HelloUltipaReply;
using grpc::ServerAsyncResponseWriter;
//enum AsyncFuncType{
//    SayHello = 0,
//    SearchAB,
//};
enum CallStatus {
    PROCESS = 1,
    FINISH
};

class CAsyncData {
public:
    CAsyncData(UltipaRpcs::AsyncService* service,ServerCompletionQueue* complete_queue);
    virtual~CAsyncData();

    void process();

public:
    UltipaRpcs::AsyncService* m_service;
    ServerCompletionQueue* m_complete_queue;
    ServerContext m_ctx;
    CallStatus m_status;

    HelloUltipaRequest m_request;
    HelloUltipaReply   m_replay;
    ServerAsyncResponseWriter<HelloUltipaReply> m_responder;
};


`
`//
// Created by curse on 2019/9/10.
//

#include "AsyncData.h"

CAsyncData::CAsyncData(UltipaRpcs::AsyncService* service,
        ServerCompletionQueue* complete_queue):
        m_service(service), m_complete_queue(complete_queue),
        m_status(PROCESS),m_responder(&m_ctx){
    m_service->RequestSayHello(&m_ctx, &m_request, &m_responder, m_complete_queue, m_complete_queue,
                               this);
}
CAsyncData::~CAsyncData(){

}

void CAsyncData::process(){
    if(m_status == PROCESS){
        new CAsyncData(m_service,m_complete_queue);

        std::string prefix("Welcome To GRPC ");
        m_replay.set_message(m_request.name() + prefix);

        m_responder.Finish(m_replay, Status::OK, this);
        m_status = FINISH;
    } else{
        GPR_ASSERT(m_status == FINISH);
        delete this;
    }
}
`
main.cpp:
`#include <thread>
#include "src/AsyncServer.h"
using namespace std;


int main(int argc, char* argv[]) {

    do{

        CAsyncServer as_server;
        as_server.run();
        
    }while(0);

    return 0;
}`

proto define:
`syntax = "proto3";

package ultipa;

// The greeting service definition.
service UltipaRpcs{
  // Sends a greeting
  rpc SayHello (HelloUltipaRequest) returns (HelloUltipaReply) {}
}
/*------------------------1.SayHello------------------------------*/
// The request message containing the user's name.
message HelloUltipaRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloUltipaReply {
  string message = 1;
}
/*--------------------------SayHello----------------------------*/
`

**Comment by leaout** [comment]
The AsyncClient Code Below.
UltipaAsyncClient.h UltipaAsyncClient.cpp:
`//
// Created by curse on 24/09/2019.
//

#pragma once
#include <iostream>
#include <memory>
#include <string>

#include <grpcpp/grpcpp.h>
#include "../pbcpp/ultipa.grpc.pb.h"
#include "AsyncClientData.h"

using ultipa::UltipaRpcs;
using grpc::Channel;
using grpc::ClientAsyncResponseReader;
using grpc::ClientContext;
using grpc::CompletionQueue;
using grpc::Status;

class CUltipaAsyncClient {
public:
    explicit CUltipaAsyncClient(std::shared_ptr<Channel> channel);
    ~CUltipaAsyncClient();
    void say_hello(std::string user);
public:
    void async_process();
private:
    // Out of the passed in Channel comes the stub, stored here, our view of the
    // server's exposed services.
    std::unique_ptr<UltipaRpcs::Stub> stub_;

    // The producer-consumer queue we use to communicate asynchronously with the
    // gRPC runtime.
    CompletionQueue cq_;
};



`
`//
// Created by curse on 24/09/2019.
//

#include "UltipaAsyncClient.h"

CUltipaAsyncClient::CUltipaAsyncClient(std::shared_ptr<Channel> channel):
stub_(UltipaRpcs::NewStub(channel)){

}
CUltipaAsyncClient::~CUltipaAsyncClient(){

}

void CUltipaAsyncClient::async_process(){
    void* got_tag;
    bool ok = false;

    // Block until the next result is available in the completion queue "cq".
    while (cq_.Next(&got_tag, &ok)) {
        // The tag in this example is the memory location of the call object
        CAsyncClientData* call = static_cast<CAsyncClientData*>(got_tag);

        // Verify that the request was completed successfully. Note that "ok"
        // corresponds solely to the request for updates introduced by Finish().
        GPR_ASSERT(ok);

        if (call->status.ok())
        {
            std::cout << "Greeter received! " << std::endl;
            call->process();
        }
        else
            std::cout << "RPC failed" << std::endl;

        // Once we're complete, deallocate the call object.
        delete call;
    }
}
using ultipa::HelloUltipaRequest;
using ultipa::HelloUltipaReply;
void CUltipaAsyncClient::say_hello(std::string user){
    HelloUltipaRequest request;
    request.set_name(user);

    // Call object to store rpc data
    CAsyncHelloUltipaData* call = new CAsyncHelloUltipaData;

    // stub_->PrepareAsyncSayHello() creates an RPC object, returning
    // an instance to store in "call" but does not actually start the RPC
    // Because we are using the asynchronous API, we need to hold on to
    // the "call" instance in order to get updates on the ongoing RPC.
    call->response_reader =
            stub_->PrepareAsyncSayHello(&call->context, request, &cq_);

    // StartCall initiates the RPC call
    call->response_reader->StartCall();

    // Request that, upon completion of the RPC, "reply" be updated with the
    // server's response; "status" with the indication of whether the operation
    // was successful. Tag the request with the memory address of the call object.
    call->response_reader->Finish(&call->reply, &call->status, (void*)call);
}`

AsyncClientData.h AsyncClientData.cpp:

`//
// Created by curse on 24/09/2019.
//

#pragma once
#include <grpcpp/grpcpp.h>
#include "../pbcpp/ultipa.grpc.pb.h"

using grpc::Channel;
using grpc::ClientAsyncResponseReader;
using grpc::ClientContext;
using grpc::CompletionQueue;
using grpc::Status;
using ultipa::HelloUltipaReply;

class CAsyncClientData {
public:
    CAsyncClientData(){}
    ~CAsyncClientData(){}

    virtual void process();

public:
    ClientContext context;

    // Storage for the status of the RPC upon completion.
    Status status;


//    std::unique_ptr<ClientAsyncResponseReader<HelloUltipaReply>> response_reader;
};


class CAsyncHelloUltipaData :public CAsyncClientData{
public:
    CAsyncHelloUltipaData(){}
    ~CAsyncHelloUltipaData(){}

    virtual void process();

public:
    HelloUltipaReply reply;
    std::unique_ptr<ClientAsyncResponseReader<HelloUltipaReply>> response_reader;

};




`

`//
// Created by curse on 24/09/2019.
//

#include "AsyncClientData.h"


void CAsyncClientData::process(){

}

void CAsyncHelloUltipaData::process(){
    std::cout << "HelloUltipa response:" << reply.message() <<std::endl;
}`

test.cpp:
`//
// Created by curse on 24/09/2019.
//
#include <iostream>
#include <thread>
#include <gtest/gtest.h>
#include "src/UltipaAsyncClient.h"

int main(int argc, char* argv[]){
    CUltipaAsyncClient ultipa_client(grpc::CreateChannel(
            "localhost:60061", grpc::InsecureChannelCredentials()));

    std::thread thread_ = std::thread(&CUltipaAsyncClient::async_process, &ultipa_client);

    for (int i = 0; i < 10000; i++) {
        std::string user("world " + std::to_string(i));
        ultipa_client.say_hello(user);  // The actual RPC call!
    }

    std::cout << "Press control-c to quit" << std::endl << std::endl;
    thread_.join();  //blocks forever

    return 0;
}
`

**Comment by leaout** [comment]
hey, I solve the problem,
`m_responder.Finish(m_replay, Status::OK, this);
m_status = FINISH;`
change the position of code above.
`m_status = FINISH;
m_responder.Finish(m_replay, Status::OK, this);
`
but i don't know what that means to  grpc.
@vjpai @nicolasnoble @hassox @timburks
