### ISSUE TITLE
c++ Synchronous Server unresponsive, after threadlimit was reached

### ISSUE THREAD

**Issue by chrisse74** [grpc/grpc#20366]
### What version of gRPC and what language are you using?
gRPC 1.23.0, C++

### What operating system (Linux, Windows,...) and version?
Red Hat Enterprise Linux Server release 7.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang7el7

### Summary
When the server is unable to spawn a new worker thread (because ulimit -u was reached), this is silently ignored and leads to it being unable to respond, even after the offending threads ended.
Possible solution outlined.

### What did you do?
Using a simple bash-script i started a large number of client processes on the same machine (and same user) as the server:
```
#!/bin/bash
count=4200
for (( i=0; i<$count; i++ )); do
  ./myForeverPollingClient &
done
```

When i let these clients end (more or less gracefully), the server does not respond to grpc calls and cannot shutdown regularly anymore.

### What did you expect to see?
* the server responds with "resource exhausted" messages, as long as the tight process situation remains
* after ending the client processes the server responds to calls as expected, without needing to restart the server
* the server can shutdown regularly

### What did you see instead?
Server did not react and could not shut down gracefully.

### Locating the error:
Debugging a sane server and comparing it to the unresponsive one i am missing one worker thread (ThreadManager::MainWorkLoop).

By adding some debug output and debugging the unresponsive server some more i could solve the issue, but i am not sure, if this is the best way - so i would appreciate you looking into it:

### The root of the problem, that i could track:
In src/cpp/thread_manager/thread_manager.cc:void ThreadManager::MainWorkLoop() there is some code that spawns a "new WorkerThread".
This starts a "grpc_core::Thread" in its constructor - when this grpc_core::Thread fails to create a pthread, this is ignored by the constructor code (success gets defaulted to nullptr in src/core/lib/gprpp/thd.h).
Back in the ThreadManagers MainWorkLoop it is assumed, that the WorkerThread has been spawned and in the end the MainWorkLoop is exited ( num_pollers_ would be >= max_pollers_ ).

### The solution that worked for me:
 * added a boolean flag to the WorkerThread (created_).
 * used it when invoking grpc_core::Thread
 * added the getter function isCreated to the WorkerThread
 * Saved new WorkerThread() to a pointer, when isCreated evaluated to false:
   * num_pollers_-- 
   * num_threads_--
   * resource_exhausted=true

### After patching this:
* the server responds with "resource exhausted" messages, as long as the tight process situation remains
* after ending the client processes the server responds to calls as expected, without needing to restart the server
* the server can shutdown regularly

### Open items
* what about the lock - would this be needed here?
* what if "void ThreadManager::Initialize()" can not get WorkerThreads?
* is there a better way altogether

**Comment by nicolasnoble** [comment]
Possibly related to #20364.

**Comment by chrisse74** [comment]
Maybe the situation described here caused the behaviour seen in #18848.
#19311 sounds like a workaround needed, because the WorkerThread exited silently as described above?
