### ISSUE TITLE
C# server currently doesn't allow listening on UDS sockets

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20375]
C core supports UDS sockets and so would C#, but currently listening on a UDS socket doesn't work for C# servers because of a small API glitch.

- while the server can accept a UDS address just fine (e.g. "unix:///path/to/my/uds_test_socket") but `ServerPort` always requires to pass a port and concatenates the address and the port, thus creating a broken UDS address. 

- creating a client for a UDS socket works just fine for a UDS socket: e.g. `var channel = new Channel("unix:///path/to/my/uds_test_socket", ChannelCredentials.Insecure);`

https://github.com/grpc/grpc/blob/39e982a263e5c48a650990743ed398c1c76db1ac/src/csharp/Grpc.Core/Server.cs#L277

workaround:
`new ServerPort("unix:///path/to/my/uds_test_socket", 1234, ServerCredentials.Insecure)` actually creates a UDS socket named "/path/to/my/uds_test_socket:1234" and the client can connect to it (by providing the "port number" that will become suffix of the UDS socket name). Obviously, the name of the file is wrong, but it allows to make a successful connection.

**Comment by jtattermusch** [comment]
Let's keep open.

**Comment by markdroth** [comment]
Jan, are you actively working on implementing this?  If not, let's close this and add a help-wanted label.

**Comment by Code-Codex** [comment]
I am trying to use UDS on windows 10 using C# and I keep on getting IOException at CheckPortsBoundSuccessfully(). I am using the workaroud that is provided in the main message above.

**Comment by jtattermusch** [comment]
> CheckPortsBoundSuccessfully()

Looks like that's an unwanted side effect of https://github.com/grpc/grpc/issues/18100. 
The gRPC C# support for UDS sockets should be revisited to make sure it works.

**Comment by Code-Codex** [comment]
It would be very helpful to get UDS working. Can this issue be opened again?
