### ISSUE TITLE
Python call of Stub results an interpreter crash

### ISSUE THREAD

**Issue by Zerqkboo** [grpc/grpc#2038]
Hi,
I used grpc in python to do my work, finding some problems. To simplify the problem, I tested on the examples of [route_guide](https://github.com/grpc/grpc-common/tree/master/python/route_guide) with my same usage of grpc in my project.
I created a new client which is similar to line 117-130 of [route_guide_client.py](https://github.com/grpc/grpc-common/blob/master/python/route_guide/route_guide_client.py#L117-130). The new client is as below:
```python
import route_guide_client as rgc
import route_guide_pb2
import time

def run(stub):
    with stub:
        rgc.guide_route_chat(stub)

if __name__ == '__main__':
    count = 0
    stub = route_guide_pb2.early_adopter_create_RouteGuide_stub('localhost', 50051)
    while True:
        count += 1
        print "run start on count:", count
        run(stub)
        time.sleep(1)
```
All the other codes and environment configure are as the [example](https://github.com/grpc/grpc-common/tree/master/python/route_guide) shows. Finally, the python interpreter which runs the above client crashes! (run in python2.7.9 virtualenv on win10 build 10074, crash is uncertain to occur, but very likely to happen)

I think the problem is the frequent run of code `with stub`, which actually runs `stub.__enter__()` and `stub.__exit__()` frequently, and that's the only difference between the above codes and the origin. But I think it's a normal usage. Can anybody help to check if it's a bug?

**Comment by nathanielmanistaatgoogle** [comment]
Something that makes the interpreter crash is definitely a bug.

Thank you for including your code; what does the crash look like? What gets printed?

**Comment by Zerqkboo** [comment]
I run the script on windows' console by using `python myclient.py`, there are no any prints get except for a crash notification window as below, it just tells me something is wrong but no extra messages...
![qq 20150612094929](https://cloud.githubusercontent.com/assets/4116046/8122132/447241c8-10e8-11e5-89b9-8ec77824bec2.png)

**Comment by yang-g** [comment]
python.exe has stopped working

An error occurred, causing the program to stop working normally. If there is any solution, WIndows is going to close the program and notify you.

**Comment by soltanmm** [comment]
Thanks, @yang-g, for the translation!

**Comment by Zerqkboo** [comment]
There seem to be no problems any more on new release 0.10.0. It should be fixed by some unkown commits. :+1:  The original test is carried on release 0.9.1.
