### ISSUE TITLE
java interop tests failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20384]
https://source.cloud.google.com/results/invocations/07049fac-cfb3-4c49-89d6-667ad4788d56/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_cloud:c%2B%2B:java_server:cancel_after_first_response:alts;row=1

Eric tells me that this should be assigned to @creamsoup, although github won't let me assign to him for some reason.

**Comment by creamsoup** [comment]
oops the ui says assign to me, and removed it =(

**Comment by yashykt** [comment]
Adding keywords - Interop ALTS Tests

**Comment by ejona86** [comment]
This was fixed by grpc/grpc-java#6207
