### ISSUE TITLE
v1.24.0 archive does not contain third_party/upb/upb

### ISSUE THREAD

**Issue by moubctez** [grpc/grpc#20392]
### What version of gRPC and what language are you using?
1.24.0

### What operating system (Linux, Windows,...) and version?
any

### What did you do?
It is difficult to package gRPC (in my case, for PkgSrc.org), since the v1.24.0 archive does not contain third_party/upb, and cmake fails with
```
CMake Error at CMakeLists.txt:4250 (add_library):
  Cannot find source file:

    third_party/upb/upb/decode.c
```

Can UPB support be optional?

**Comment by jengelh** [comment]
And the plain build (just `make`, without cmake) just fails at some point:

```
[   62s] c++ -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -DOPENSSL_LOAD_CONF  -Ithird_party/address_sorting/include -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/upb -Isrc/core/ext/upb-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/home/abuild/rpmbuild/BUILD/grpc-1.24.0/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\"     -pthread  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -Wno-error -std=c++11   -fno-rtti -fno-exceptions -MMD -MF /home/abuild/rpmbuild/BUILD/grpc-1.24.0/objs/opt/src/core/lib/security/credentials/alts/alts_credentials.dep -c -o /home/abuild/rpmbuild/BUILD/grpc-1.24.0/objs/opt/src/core/lib/security/credentials/alts/alts_credentials.o src/core/lib/security/credentials/alts/alts_credentials.cc
[   62s] In file included from ./src/core/tsi/alts/handshaker/transport_security_common_api.h:29,
[   62s]                  from ./src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26,
[   62s]                  from ./src/core/lib/security/credentials/alts/alts_credentials.h:26,
[   62s]                  from src/core/lib/security/credentials/alts/alts_credentials.cc:21:
[   62s] src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12:10: fatal error: upb/generated_util.h: No such file or directory
[   62s]    12 | #include "upb/generated_util.h"
[   62s]       |          ^~~~~~~~~~~~~~~~~~~~~~
[   62s] compilation terminated.
```

**Comment by jtattermusch** [comment]
I think this is because starting from v1.24.x we actually started depending on the upb code, but we never added upb properly as a cmake dependency.

I started the work of add upb properly in https://github.com/grpc/grpc/pull/19384/files but ended up not having enough time to finish that.

I think our distribtest didn't catch the problem because we don't delete `third_party/upb` in our distribtest like we do for other dependencies
https://github.com/grpc/grpc/blob/373fc2413ae36464e982694aa9d4df846aedb5f7/test/distrib/cpp/run_distrib_test_cmake.sh#L35 (that is also something to fix).

**Comment by coryan** [comment]
@jtattermusch you probably know this, but `upb` lacks an `install` target (I just created protocolbuffers/upb#215), I think that breaking #19384

**Comment by jtattermusch** [comment]
@coryan  you're right. For now we decided to just do a code dump and add upb sources as a subdirectory as a repository (upb won't have an install target in the nearest future not it has stable ABI for now).

@veblush  will look into fixing the problem (by adding upb to our repo).
