### ISSUE TITLE
Successful synchronous unary-unary calls sometimes block until deadline, then return successfully

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#2039]
I noticed this in python_plugin_test and have been able to reproduce it in early_adopter/implementations_test.

Rather than investigate immediately I'll leave it until the beta API is in place and then look for it there.

**Comment by Zerqkboo** [comment]
It occurs in my test project too!
It really used to make me puzzled for a long time!
Finally I changed my call with 
```python
response_future = stub.rpcmethord().async(message, timeout)
reponse = response_future.result()
```

**Comment by nathanielmanistaatgoogle** [comment]
Retitled - I'm not aware of this happening with asynchronous (Future-returning) calls, only blocking calls.

**Comment by nathanielmanistaatgoogle** [comment]
I believe that this defect is specific to the alpha code will be resolved this week as the beta code goes live. All the tests of the beta code that we currently have check for this problem and do not find it.

**Comment by jayantkolhe** [comment]
Obsolete
