### ISSUE TITLE
undefined symbol: __atomic_exchange_8

### ISSUE THREAD

**Issue by rprhernandez** [grpc/grpc#20400]
### What did you do? from google.cloud import speech
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
it should run as expected

### What did you see instead?
got an error for undefined symbol: __atomic_exchange_8

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by s3bi77** [comment]
Hi, I encountered the same issue just now. Downgrading to 1.23 solved the issue for me.

**Comment by gamescom15** [comment]
I'm also having the same issue.

traceback:
```
(venv) ➜  google_home$ googlesamples-assistant-pushtotalk --project-id <removed>  --device-model-id <removed>                    
Traceback (most recent call last):
  File "/home/pi/google_home/venv/bin/googlesamples-assistant-pushtotalk", line 6, in <module>
    from googlesamples.assistant.grpc.pushtotalk import main
  File "/home/pi/google_home/venv/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 28, in <module>
    import grpc
  File "/home/pi/google_home/venv/lib/python3.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /home/pi/google_home/venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_exchange_8
```


Hardware is a newly setup Raspberry Pi 3b+

I can also confirm that  @s3bi771 's workaround, a downgrade to 1.23.0, removed the error.

**Comment by rprhernandez** [comment]
I also downgraded to 1.23.0 to fix this issue

**Comment by cats0713** [comment]
I have same problem. 
what do I downgarde?

**Comment by rprhernandez** [comment]
sudo pip install grpcio==1.23.0

**Comment by cats0713** [comment]
Thank you very much :)

**Comment by vjpai** [comment]
@veblush : can you investigate this issue? I believe that __atomic_exchange_8 is from libstdc++

**Comment by veblush** [comment]
This is because it lacks `libatomic` when building gRPC Python on arm linux such rasberian. ([ref](https://stackoverflow.com/questions/30591313/why-does-g-still-require-latomic)) It seems that we had the same problem with **grpc_tools.protoc** 1.23 #20174.

Just adding `-latomic` to linker would be enough to fix this problem under arm and I will try to make a patch on this. In the meantime, it's possible to try [workaround](https://github.com/opencv/opencv/issues/15278#issuecomment-520893950) to use gRPC 1.24 on rasberian.

**Comment by vjpai** [comment]
@rprhernandez @s3bi77 @gamescom15 @cats0713 Can you try the workaround solution that @veblush mentioned and let us know if it works for you?
