### ISSUE TITLE
C# NuGet package Grpc.HealthCheck does not implement Watch method

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [grpc/grpc#20403]
### What version of gRPC and what language are you using?
v1.24.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2017 v15.9.16 (C# & C++)

### What did you do?
Call the `Watch` method of the `Health` service implementation that is provided by the Grpc.HealthCheck NuGet package v2.24.0 (https://www.nuget.org/packages/Grpc.HealthCheck/2.24.0).

### What did you expect to see?
Immediate response with the service status.

### What did you see instead?
The `Health` service implementation calls the code `throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));`.
In my C++ test client this results in the grpc::CompletionQueue::Next method returning with ok==false.

Looking at https://github.com/grpc/grpc/blob/v1.24.0/src/csharp/Grpc.HealthCheck/HealthServiceImpl.cs (the source for the NuGet package) we can see that only the `Check` method is implemented but the `Watch` method is missing.

### Anything else we should know about your project / environment?
no

**Comment by jtattermusch** [comment]
The Watch() method has been added to health.proto later than the other method, so you're right that the support is missing - it shouldn't be hard to add it.
Contributions are welcome!
