### ISSUE TITLE
FLAKE: tests.build_docker_javaokhttp

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20423]
https://source.cloud.google.com/results/invocations/b39f654e-edf0-4cbe-8339-3e268a6e7971/targets/github%2Fgrpc%2Finterop_docker_build/tests

I think this is the relevant line from the log:

```
rm: cannot remove '/root/.gradle': Directory not empty
```

**Comment by ejona86** [comment]
Hmm... That's probably from https://github.com/grpc/grpc/blob/5911d2c7314ccce3b1a6d44d985d36e323317098/tools/dockerfile/interoptest/grpc_interop_java/build_interop.sh#L35

Which likely means a new file is created while `rm -r` is running. We could probably disable the gradle daemon to avoid this. Although it seems it is very rare.
