### ISSUE TITLE
c# macos build failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20420]
https://source.cloud.google.com/results/invocations/ea1b31ed-ce41-4f19-b776-10a9c49e2782/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_csharp_macos_dbg_native/tests

I *think* this is the relevant error message, but I might be reading the log wrong:

```
CMake Error at CMakeLists.txt:3780 (add_library):
  No SOURCES given to target: grpc++_test
```

**Comment by jtattermusch** [comment]
Should be fixed by https://github.com/grpc/grpc/pull/20415
