### ISSUE TITLE
How to stop this frequent logging from http_server_filter.cc

### ISSUE THREAD

**Issue by shawncao** [grpc/grpc#20469]
I have a default/standard setup using grpc+envoy proxy, on the server console, I saw these logs keep coming in, otherwise all function well. 

I looked at the file http_server_filter.cc, this log seems happening when a metadata option (cachable request) is missing, with my little understanding on the whole grpc internals, I don't really know how to stop these messages, maybe some header setting in envoy? maybe some grpc server configs when starting up? can anybody shed some light here? I really don't want these messages flooding my server console logs, thank you!

reference: 
- my envoy config: [envoy.yaml](https://github.com/shawncao/nebula/blob/master/src/service/http/envoy.yaml)
- server start up:  [all defaults](https://github.com/shawncao/nebula/blob/master/src/service/server/NebulaServer.cpp#L220)

...
E1003 15:56:29.942786565   50957 http_server_filter.cc:271]  GET request without QUERY
E1003 15:56:47.566157443     150 http_server_filter.cc:271]  GET request without QUERY
E1003 15:56:50.065000632   50957 http_server_filter.cc:271]  GET request without QUERY
E1003 15:56:55.249132004     150 http_server_filter.cc:271]  GET request without QUERY
E1003 15:56:59.965248609   50957 http_server_filter.cc:271]  GET request without QUERY
E1003 15:57:17.572831992     150 http_server_filter.cc:271]  GET request without QUERY
...

**Comment by shawncao** [comment]
anybody help take a look? thanks!

**Comment by makhov** [comment]
@shawncao 
Hi! I had the same issue and solved it by simply adding `grpc: {}` into the "match" section. So your envoy.yaml should be changed like that:

```
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
-                        - match: { prefix: "/" }
+                        - match:
+                            prefix: "/"
+                            grpc: {}
                          route:
                            cluster: nebula_service
                            max_grpc_timeout: 0s
```

For more information see [RouteMatch spec](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=routes#envoy-v3-api-msg-config-route-v3-routematch)

**Comment by shawncao** [comment]
Awesome, @makhov, I'll give it a try, thanks for sharing!

**Comment by yashykt** [comment]
The question seems to have been answered. Also, please note that this form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
