### ISSUE TITLE
Command line tool does not parse JSON for Any with wrapper type in it

### ISSUE THREAD

**Issue by kenichi-fukushima** [grpc/grpc#20486]
### What version of gRPC and what language are you using?
version=HEAD
language=N/A

### What operating system (Linux, Windows,...) and version?
macOS 10.13.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
The command line tool built as per https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md

### What did you do?
Attempted to make an RPC with a request in JSON format. The request contains `google.protobuf.Any` with a `google.protobuf.DoubleValue` in it, like `{"@type":"type.googleapis.com/google.protobuf.DoubleValue"}`.

### What did you expect to see?
The request is sent to the server.

### What did you see instead?
Got this error.
```Failed to convert json format to proto.
Failed to parse request.
```

### Anything else we should know about your project / environment?
- The command line tool can parse `google.protobuf.Duration` in `google.protobuf.Any`, like `{"@type":"type.googleapis.com/google.protobuf.Duration"}`.
- The Go implementation of the JSON deserializer can handle the input in question.

**Comment by arberx** [comment]
It's also an issue when the response includes an `Any`. The type is properly deduced, but the message is not deserialized.

E.g:
```
./grpc_cli call localhost:50051 GetOperation  "name: '46a5640e-c3c5-4c7e-b622-df0709540107'"
connecting to localhost:50051
name: "46a5640e-c3c5-4c7e-b622-df0709540107"
metadata {
  type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteOperationMetadata"
  value: "\010\003\022E\n@ee75ef7c24f7fd1e4d094cc9ade4de9b5d6b8601d8a6f5a436c3133263baeb91\020\212\001"
}
response {
  type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteResponse"
}
```
