### ISSUE TITLE
Sockpair doesn't work on MacOS when build using bazel

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20494]
I can reproduce with some local modifications to make macos bazel build working:

`bazel --bazelrc=tools/remote_build/mac.bazelrc  test //test/core/iomgr:endpoint_pair_test`

ends with error:
`Symbol not found: __Z31grpc_iomgr_create_endpoint_pairPKcP17grpc_channel_args`

```
FAIL: //test/core/iomgr:endpoint_pair_test (see /private/var/tmp/_bazel_jtattermusch/4690b3cecd520a08d66e7529f10bff45/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/testlogs/test/core/iomgr/endpoint_pair_test/test.log)
INFO: From Testing //test/core/iomgr:endpoint_pair_test:
==================== Test output for //test/core/iomgr:endpoint_pair_test:
D1004 15:13:26.539641000 4750603712 test_config.cc:384]                test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1004 15:13:26.541331000 4750603712 ev_posix.cc:174]                   Using polling engine: poll
D1004 15:13:26.541946000 4750603712 dns_resolver_ares.cc:485]          Using ares dns resolver
I1004 15:13:26.542430000 4750603712 endpoint_tests.cc:71]              multiple_shutdown_test/tcp/tcp_socketpair
dyld: lazy symbol binding failed: Symbol not found: __Z31grpc_iomgr_create_endpoint_pairPKcP17grpc_channel_args
  Referenced from: /private/var/tmp/_bazel_jtattermusch/4690b3cecd520a08d66e7529f10bff45/sandbox/darwin-sandbox/1/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/test/core/iomgr/endpoint_pair_test.runfiles/com_github_grpc_grpc/test/core/iomgr/endpoint_pair_test
  Expected in: flat namespace

dyld: Symbol not found: __Z31grpc_iomgr_create_endpoint_pairPKcP17grpc_channel_args
  Referenced from: /private/var/tmp/_bazel_jtattermusch/4690b3cecd520a08d66e7529f10bff45/sandbox/darwin-sandbox/1/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/test/core/iomgr/endpoint_pair_test.runfiles/com_github_grpc_grpc/test/core/iomgr/endpoint_pair_test
  Expected in: flat namespace

*******************************
Caught signal SIGABRT
  no backtrace
external/bazel_tools/tools/test/test-setup.sh: line 310: 61119 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
================================================================================
Target //test/core/iomgr:endpoint_pair_test up-to-date:
  bazel-bin/test/core/iomgr/endpoint_pair_test
```

https://source.cloud.google.com/results/invocations/33eb4307-4ace-4f39-b372-6b18a7df8044

The problem might be that https://github.com/grpc/grpc/blob/474b97e44e2cfccb8a8dc54aeca143d2abe1c3ae/src/core/lib/iomgr/endpoint_pair_posix.cc#L23 is not defined?

**Comment by jtattermusch** [comment]
@nicolasnoble  @vjpai   should the sockpair actually work on MacOS or should tests involving sockpairs be disabled on mac?
It looks like we're not running the sockpair-related tests on MacOS with run_tests.py, but I'm not sure that intended?

Should GPRC_POSIX_SOCKET be defined on mac?

**Comment by vjpai** [comment]
Very interesting. Yes, socketpair should work on Mac since it is Posix, and we should be defining things accordingly.

**Comment by jtattermusch** [comment]
Ok, I found the reason why the sockpair tests are broken on MacOS when building with bazel.

It's because use_cfstream=True in 
https://github.com/grpc/grpc/blob/a0ad4081cbea0f3e524d4fc51c6a5c7dbbf3d6dc/BUILD#L954

and when  GRPC_CFSTREAM is defined, it disables GRPC_POSIX_SOCKET (which in turn breaks sockpair tests because `grpc_iomgr_create_endpoint_pair` will become undefined)
https://github.com/grpc/grpc/blob/84895f6f57ec84c3dc34052f9306a70e600e71cc/src/core/lib/iomgr/port.h#L146

@rmstar  can we enable  sockpair support when CFSTREAM is in use, or is there any other solution you'd suggest?

**Comment by rmstar** [comment]
@jtattermusch it looks like this patch fixes the issue: 
```
diff --git a/src/core/lib/iomgr/endpoint_pair_posix.cc b/src/core/lib/iomgr/endpoint_pair_posix.cc
index 5c5c246f99..6ed250b5f5 100644
--- a/src/core/lib/iomgr/endpoint_pair_posix.cc
+++ b/src/core/lib/iomgr/endpoint_pair_posix.cc
@@ -20,7 +20,7 @@

 #include "src/core/lib/iomgr/port.h"

-#ifdef GRPC_POSIX_SOCKET
+#if defined(GRPC_POSIX_SOCKET) || defined(GRPC_CFSTREAM)

 #include "src/core/lib/iomgr/endpoint_pair.h"
 #include "src/core/lib/iomgr/socket_utils_posix.h"
```

**Comment by jtattermusch** [comment]
> @jtattermusch it looks like this patch fixes the issue:
> 
> ```
> diff --git a/src/core/lib/iomgr/endpoint_pair_posix.cc b/src/core/lib/iomgr/endpoint_pair_posix.cc
> index 5c5c246f99..6ed250b5f5 100644
> --- a/src/core/lib/iomgr/endpoint_pair_posix.cc
> +++ b/src/core/lib/iomgr/endpoint_pair_posix.cc
> @@ -20,7 +20,7 @@
> 
>  #include "src/core/lib/iomgr/port.h"
> 
> -#ifdef GRPC_POSIX_SOCKET
> +#if defined(GRPC_POSIX_SOCKET) || defined(GRPC_CFSTREAM)
> 
>  #include "src/core/lib/iomgr/endpoint_pair.h"
>  #include "src/core/lib/iomgr/socket_utils_posix.h"
> ```

There's many places like that and I don't think it's a good idea to change all occurences of `#ifdef GRPC_POSIX_SOCKET` to `#if defined(GRPC_POSIX_SOCKET) || defined(GRPC_CFSTREAM)`.
It it fine to just enable GRPC_POSIX_SOCKET whenever GRPC_CFSTREAM is on?

**Comment by jtattermusch** [comment]
@rmstar friendly ping - It it fine to just enable GRPC_POSIX_SOCKET whenever GRPC_CFSTREAM is on? (see my last question)

**Comment by rmstar** [comment]
Enabling both GRPC_POSIX_SOCKET and GRPC_CFSTREAM is not allowed as the assumption is that exactly one socket type is enabled. See https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/port.h#L208-L212.

The iomgr implementation is chosen based on the socket type. If GRPC_POSIX_SOCKET is defined, we also [define GRPC_POSXI_SOCKET_IOMGR](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/port.h#L222). If GRPC_POSIX_SOCKET_IOMGR is defined, we use the [posix iomgr implementation](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/iomgr_posix.cc). 
OTOH, if GRPC_CFSTREAM is defined, we use the [CFStream iomgr implementation](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/iomgr_posix_cfstream.cc).

**Comment by jtattermusch** [comment]
@rmstar  I understand, but it also means that we'll need to do some hygiene in terms of our usage of #ifdef GRPC_POSIX_SOCKET  in tests - there's many occurrences and I'm not sure what's the intention there (it depends whether each particular test is meant to work with cfstream or not).

**Comment by rmstar** [comment]
@jtattermusch Yes, I believe some hygiene around usage of `#ifdef GRPC_POSIX_SOCKET` is required. 
In many cases, we actually want  something like`#ifdef POSIX_SOCKET_EV` or  `#ifdef POSIX_SOCKET_TCP`, which are defined even when CFStream is enabled. 
I took at stab at fixing ifdefs in Core and C++ tests: https://github.com/grpc/grpc/pull/20864. WDYT?

**Comment by jtattermusch** [comment]
This has been fixed by https://github.com/grpc/grpc/pull/20510
