### ISSUE TITLE
Python Server on OS X leaks ports

### ISSUE THREAD

**Issue by endobson** [grpc/grpc#2050]
I'm getting the following error message from the python server.
E0612 22:13:33.983661000 4544274432 tcp_server_posix.c:299] Failed accept4: Too many open files

This happens after about 230 requests. Looking in activity monitor I see a big growing section of open ports that looks like:
```
localhost:irdmi->localhost:58978
localhost:irdmi->localhost:58979
localhost:irdmi->localhost:58980
localhost:irdmi->localhost:58981
localhost:irdmi->localhost:58982
localhost:irdmi->localhost:58983
```

My client is sending the following request "'\x08\x01\x10\x12'" to the "/grpc.testing.TestService/UnaryCall" method.

**Comment by nathanielmanistaatgoogle** [comment]
I'm not even mad. That's amazing.

Are you able to come up with steps to reproduce the problem? Are you able to run the test suite, and if so, are you able to write a test that reproduces the problem (and presumably fails)?

**Comment by endobson** [comment]
Very easy to reproduce.

```
# Server
ulimit -n 15 # This just makes it show up quicker
tools/run_tests/run_python.sh src/python/interop/interop/server.py --port 8000

# Client
while true; do tools/run_tests/run_python.sh src/python/interop/interop/client.py --server_host localhost --server_port 8000 --test_case=empty_unary; done
```

Writing a test that fails is hard because without the limit it takes forever. I'm not sure why but the python client is very slow in test cases. I tried writing a loop but it was like ~10 seconds per request.

**Comment by ctiller** [comment]
How much like 10 seconds per request? Like 11 or 10+epsilon?

**Comment by endobson** [comment]
10 seconds by back of the hand observation. I added a date call in the front of the client process and it was ~7 seconds (1 significant digit).

**Comment by endobson** [comment]
Note that it is not about the number of client requests, but client channels. Sending a bunch of requests on one channel works, but this tests a bunch of different clients connecting/disconnecting.

**Comment by ctiller** [comment]
Believe this is fixed
