### ISSUE TITLE
FLAKE: //test/core/slice/slice_test.exe is flaky on windows RBE opt

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20519]
Seems to be failing with the opt config https://source.cloud.google.com/results/invocations/5322bbef-9cde-4065-9192-66c6817ca729/targets/%2F%2Ftest%2Fcore%2Fslice:slice_test/log in all builds.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/373fc2413ae36464e982694aa9d4df846aedb5f7/test/core/slice/slice_test.cc#L246

**Comment by jtattermusch** [comment]
After a lot of investigation I think I now have a proof this is actually due to a compiler bug: https://github.com/grpc/grpc/pull/20554/files

**Comment by vjpai** [comment]
Did this start failing 7 days ago or had we seen failures before then?

**Comment by jtattermusch** [comment]
@vjpai  we started getting the failure ~7days ago but that's mostly because that's when I enabled the testsuite The first build where the build finishes and the test actually runs is https://source.cloud.google.com/results/invocations/b39d6f2a-c02d-4ae1-b794-92bc6210fbf7/targets.  (after merging https://github.com/grpc/grpc/pull/20507)

**Comment by jtattermusch** [comment]
The compiler version I can reproduce with is
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64>cl /Bv
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

Compiler Passes:
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\cl.exe:        Version 19.23.28106.4
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\c1.dll:        Version 19.23.28106.4
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\c1xx.dll:      Version 19.23.28106.4
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\c2.dll:        Version 19.23.28106.4
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\link.exe:      Version 14.23.28106.4
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\mspdb140.dll:  Version 14.23.28106.4
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\1033\clui.dll: Version 19.23.28106.4
```

**Comment by jtattermusch** [comment]
I filed issue for the compiler bug here: https://developercommunity.visualstudio.com/content/problem/779761/optimizer-bug-in-c-leads-to-incorrect-behavior-at.html
