### ISSUE TITLE
Use .NET Core 3, without upgrading to Grpc.Core to 2.x

### ISSUE THREAD

**Issue by ivan-penchev** [grpc/grpc#20533]
Our current setup:

- Grpc library [Class Library targeted on .NET Standard 2.0] (Implemented using gRPC C# running on Grpc.Core 1.22) -- Contains Stubs
- WebApi [.NET Core 2.1] -- contains concrete gRPC stub implementation

- Database lib [EF Core 2.1; Class Library targeted on .NET Standard 2.0] // Doesn't reference the Grpc library
- Third party library (Dependent on  >= Grpc.Core 1.13.1)

Due to the fact that the third party library is critical component, and it does not support Grpc.Core 2.X, we can not upgrade to using Grpc.AspNetCore.

However we would like to use some of the new capabilities (other than gRPC support) of .NET Core 3, and make our transition to the new LTS (3.1) smoother.

After reading [gRPC C# 2.x Release proposal ](https://github.com/grpc/proposal/blob/master/L57-csharp-new-major-version.md), which states that basically transitioning to 2.X is needed because of "conflicts with .NET base class library".

Assuming the conflict in BCL came in .Net core 3
Can I:
 **Migrate WebApi to .Net Core 3; Database lib to EF core 3 + target .Net Standard 2.1 If I leave the Grpc library on Net Standard 2.0 and Grpc.Core 1.22?**

(I am not clear when will this conflic with BCL arise basically)

P.S. From Grpc.Core the main classes we are using is "IAsyncStreamReader" for request and "IServerStreamWriter" for responses, and "Server" to start the server.

**Comment by jtattermusch** [comment]
It's hard to reason about details of a project I'm not familiar with, but if you're able to build, you should be fine (I don't think there's anything that would make thing break silently).

May I ask what's the third party library you're using - at some point they should migrate to Grpc.Core 2.x as well.

Another idea is that you can try to re-build the third-party library from source yourself (if you have access to the sources), against Grpc.Core 2.x - the sources should build just fine and you could use that until they migrate to Grpc.Core 2.x officially.
