### ISSUE TITLE
Error 12 in hello_world cpp example 

### ISSUE THREAD

**Issue by amtagrwl** [grpc/grpc#20550]
### What version of gRPC and what language are you using?
Server: 1.24.1 
Client: 1.19.1
### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 5.4.0 

### What did you do?
Was facing issues using TF-Serving with my C++ code to perform inference on a trained model. Both, the C++ code and TF-Serving are in separate docker containers on the same host machine. The gRPC requests would return Error 14: Name Resolution Failure. This did not seem reasonable, so I decided to test a few things. 

- Tested and confirmed that if requests are sent from a Jupyter Notebook (using Python code similar to my C++ code) to the same TF-Serving container, then requests are fulfilled accurately and consistently. 
- Testing hello_world example by running the `greeter_server` in the TF-Serving container and running `greeter_client` in my C++ docker container. 
  - This did not work reliably
  - It would either work correctly and display "Hello World" or the RPC would fail with error code 12 
  - When using the asynchronous versions of the greeter client and server, in each run, either all requests would fail with error 12 or all requests would succeed. 
  - Tried with GRPC_DNS_RESOLVER="ares" and "native" to no avail 

### What did you expect to see?
Expected all requests from `greeter_client` to succeed and respond with "Hello World" 

### What did you see instead?

It would either work correctly and display "Hello World" or the RPC would fail with error code 12 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
[Failure.txt](https://github.com/grpc/grpc/files/3710188/Failure.txt)
[Success.txt](https://github.com/grpc/grpc/files/3710189/Success.txt)
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

**Comment by AspirinSJL** [comment]
@nanahpang Do you have time on this bug?

**Comment by amtagrwl** [comment]
I'm not sure if I understand what you mean. 

The attached log files were collected with GRPC_TRACE="all" and GRPC_VERBOSITY="debug"
