### ISSUE TITLE
grpc_server_register_method is untested with non-null third argument

### ISSUE THREAD

**Issue by endobson** [grpc/grpc#2055]
I was attempting to register a method in my server using `grpc_server_register_method` with third argument `"localhost"` and could not get it to work (no notifications ever happened). After a bunch of debugging I found out that only the C++ server is using this method and in both call sites it is passing in `nullptr`. 
```
https://github.com/grpc/grpc/blob/master/src/cpp/server/server.cc#L230
https://github.com/grpc/grpc/blob/master/src/cpp/server/server.cc#L248
```

Switching over to using a `nullptr` fixed my issue, but I'm not sure if I was misusing `grpc_server_register_method` or if it is broken with a non-null host.

Grep output:
```
endobson@yggdrasil () ~/proj/grpc % grep -I grpc_server_register_method -R .
./include/grpc/grpc.h:void *grpc_server_register_method(grpc_server *server, const char *method,
./src/core/surface/server.c:void *grpc_server_register_method(grpc_server *server, const char *method,
./src/core/surface/server.c:    gpr_log(GPR_ERROR, "grpc_server_register_method method string cannot be NULL");
./src/cpp/server/server.cc:    void* tag = grpc_server_register_method(server_, method->name(), nullptr);
./src/cpp/server/server.cc:    void* tag = grpc_server_register_method(server_, service->method_names_[i],
```

**Comment by ctiller** [comment]
@vjpai - since you're working with this code at the moment, could you take this one on also?
@yang-g - this will probably be a blocker for the C++ API.
