### ISSUE TITLE
Is there a need to recreate a new stream by gprc stream client side ? 

### ISSUE THREAD

**Issue by lrouter** [grpc/grpc#20574]
There is a grpc stream server and client. the client dials to server through gprc bidirectional stream.
I have encountered a problem. The server is running on a kunbeness docker. 

After upgrading  kubeness server once, the client always get a EOF error when trying to send a request to stream server. I found that the tcp connection is alive. Why ?

Do I need to recreate a new strean by calling "NewStream" API in go-grpc ?
`func (cc *ClientConn) NewStream(ctx context.Context, desc *StreamDesc, method string, opts ...CallOption) (ClientStream, error)`

If I set keep-alive parameters when dialing to gprc stream server, does the stream would be reconnected automatically or just the tcp connection ?

Thanks.

**Comment by AspirinSJL** [comment]
Looks like you are using Go. Please re-post in https://github.com/grpc/grpc-go. Thanks!
