### ISSUE TITLE
PHP: Received message larger than max

### ISSUE THREAD

**Issue by Allkoman** [grpc/grpc#20581]
### What version of gRPC and what language are you using?
php 7.2.21

### What operating system (Linux, Windows,...) and version?
mac os and ubuntu

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 11.0.0 (clang-1100.0.33.8)

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
learning to use grpc
### What did you see instead?
Received message larger than max, and I can not find someplace to change the max limit
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by Allkoman** [comment]
the grpc version is 1.22.0

**Comment by stanley-cheung** [comment]
Can you provide more information about what you mean by "received message larger than max"? Can you provide some steps to reproduce?

**Comment by Allkoman** [comment]
![image](https://user-images.githubusercontent.com/9135356/66973006-2583d400-f0c9-11e9-8c8a-d1c8d06b668b.png)

**Comment by Allkoman** [comment]
I use php grpc-1.22.0  as the client to receive data from the server, which is a golang micro-server,
e.g. when I send a 'id' list(a large list) from the client to get data from server,  the exception will show up like the photo, I think there may be some optional value In the package [https://packagist.org/packages/grpc/grpc](url)  to solve this problem? but I can not find one.

**Comment by stanley-cheung** [comment]
You can try setting this channel args:

```
$client = new Helloworld\GreeterClient('localhost:50051', [
    'credentials' => Grpc\ChannelCredentials::createInsecure(),
    'grpc.max_receive_message_length' => 8*1024*1024,
]);
```

**Comment by Allkoman** [comment]
thx, it works ! where can I see this document ?

**Comment by Allkoman** [comment]
i open it just for where to see the doc ...

**Comment by stanley-cheung** [comment]
I recently refreshed the main [PHP readme](https://github.com/grpc/grpc/tree/master/src/php#misc-config-options) and added a section about various config options there.
