### ISSUE TITLE
grpc 1.24.2 compilation issue

### ISSUE THREAD

**Issue by chenrui333** [grpc/grpc#20587]
### What version of gRPC and what language are you using?

1.24.2

### What operating system (Linux, Windows,...) and version?

macOS: 10.14.6-x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)

Clang: 11.0 build 1100
python3 

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Jenkins build reference, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/49693/version=mojave/console

### What did you expect to see?

Fix the build issue

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

```
00:03:44 ==> ENV
00:03:44 HOMEBREW_CC: clang
00:03:44 HOMEBREW_CXX: clang++
00:03:44 MAKEFLAGS: -j6
00:03:44 CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local
00:03:44 CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
00:03:44 CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
00:03:44 PKG_CONFIG_PATH: /usr/local/opt/c-ares/lib/pkgconfig:/usr/local/opt/gflags/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/protobuf/lib/pkgconfig
00:03:44 PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
00:03:44 HOMEBREW_GIT: git
00:03:44 HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
00:03:44 ACLOCAL_PATH: /usr/local/share/aclocal
```
Relates to https://github.com/Homebrew/homebrew-core/pull/45106

**Comment by sab24** [comment]
same as #20392 , download upb and put it in third_party directory.

**Comment by AspirinSJL** [comment]
Please reopen if you feel this is different from https://github.com/grpc/grpc/issues/20392.
