### ISSUE TITLE
C++: no place to add in application-level authentication

### ISSUE THREAD

**Issue by dhasenan** [grpc/grpc#2059]
A lot of applications roll their own authentication for any number of reasons. While I can create my own `grpc_credentials` substruct, that just gives me a way to add some items to request metadata. I want to add an RPC interceptor that looks at the metadata and target method for all requests and compares that against a policy, eg:

    bool Accept(string serviceName, string methodName, Message* message, ServerContext* context, Status* status) {
      if (methodName == "Login" && !VerifyAuthToken(context->client_metadata()["auth_token"])) {
        *status = Status(UNAUTHORIZED);
        return false;
      }
      return true;
    }

Currently, I could subclass AsynchronousService and provide a DispatchImpl implementation that checks request metadata and throws an exception if the correct metadata isn't there. Then I need to `#define AsynchronousService AuthenticatingAsynchronousService` before importing `*.grpc.pb.h`.

If I don't want to gouge my eyes out on that hack, I'm pretty much left with putting credential checking logic in every RPC handler and credential refreshing and retrying around every RPC call.

Similarly, on the client side, I want a credential system that can detect automated logout (server restart with ephemeral storage, credentials that expire a certain amount of time after being issued, etc). In the current code, I need to create my own copy of `Channel` that can detect credential expiration (either standard timeout or server restart with ephemeral storage) and refresh credentials as needed. Not ideal.

Ideally, I'd have a client RPC response interceptor that can examine the response status. If I get UNAUTHORIZED, my interceptor would get a fresh set of credentials.

**Comment by ctiller** [comment]
@a11r also - since this straddles the auth/C++ API boundary.

**Comment by jboeuf** [comment]
We are going to provide a hook server-side to verify metadata in an
interceptor (see
https://github.com/grpc/grpc/blob/master/src/core/security/server_auth_filter.c#L55
).

For your second request, we could we provide a similar filter with a hook.
However, I think that the retry logic will still need to be handle by the
application code.

**Comment by jayantkolhe** [comment]
post beta

**Comment by jboeuf** [comment]
We now have APIs to do this:

1. Client Side: create your own credentials with the credentials metadata plugin API:
https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L292

2. Server Side interceptor: auth metadata processor:
https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L383
