### ISSUE TITLE
Release 3.8 Wheels for gRPC Python

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20615]
Ideally, release for Linux, macOS and Windows. Highly depends on if our Kokoro image support 3.8 for macOS and Windows.

**Comment by lidizheng** [comment]
Link one user issue asking for Windows wheels: https://github.com/grpc/grpc/issues/20604

**Comment by lidizheng** [comment]
Another user issue asking for Windows 3.8 wheel: https://github.com/grpc/grpc/issues/20831

**Comment by lidizheng** [comment]
@jtattermusch @nicolasnoble How can we install 3.8 on Kokoro images for macOS, Windows (and ARM)?

**Comment by naphta** [comment]
Also wondering when the macOS wheel is due

**Comment by jtattermusch** [comment]
> @jtattermusch @nicolasnoble How can we install 3.8 on Kokoro images for macOS, Windows (and ARM)?

That's quite problematic: kokoro doesn't provide updates to testing images anymore. That means we either need to maintain an image ourselves (complicated for windows, extremely complicated on macos). Or we just need to install whatever we need in the prepare script before we start building.

E.g. if you only need to install this for the artifact build:
https://github.com/grpc/grpc/blob/456f08a06474165fed8a485d627e10cf40cf75ea/tools/internal_ci/windows/grpc_build_artifacts.bat#L23
(be careful that if the prepare step fails, the build will also fail, so we'd better choose some reliable "installation method").

**Comment by griffinator76** [comment]
Note that the installation steps listed in the package documentation e.g. here: https://github.com/googleapis/google-cloud-python/tree/master/container say to install **Python >= 3.5**

If the user installs the apparently compatible Python 3.8 based on these instructions they will be unable to complete the pip install step to install the package, as the installation fails with grpcio errors as described in #20604 and elsewhere.

**Comment by nimish** [comment]
Any idea where the macOS wheel for 3.8 went?

**Comment by lidizheng** [comment]
@nimish For macOS, it is much easier to get the compilation right by installing `Cython` and `gcc`.

**Comment by nimish** [comment]
Sure, but it takes minutes.

**Comment by t-mart** [comment]
@jtattermusch 
> That's quite problematic: kokoro doesn't provide updates to testing images anymore. 

With this preventing progress here (and probably any future versions for any language), are alternatives to Kororo being considered?

Also, what is Kokoro?

**Comment by bd-cbentzel** [comment]
Excited to see recent progress on getting 3.8 wheels together! Also another +1 on this being gRPC-customer impacting.

**Comment by gnossen** [comment]
@bd-cbentzel Can you help us understand the scope of the impact of this issue on you?

**Comment by lidizheng** [comment]
Now all codes are checked in, pre-compiled wheels should be released at `Tuesday, December 3, 2019` as `1.25.0rc1`.

**Comment by Harmon758** [comment]
Hasn't [v1.25.0](https://github.com/grpc/grpc/releases/tag/v1.25.0) already been released?

**Comment by lidizheng** [comment]
@Harmon758 You are right, thanks for pointing out. Corrected to `1.26.0rc1`.

**Comment by gnossen** [comment]
`1.26.0rc1` just went live with 3.8 binaries for both MacOS and Windows thanks to @lidizheng.

 - [Mac](https://files.pythonhosted.org/packages/6f/8e/00268b77755410307d011374d56cd6ccfd09ad5cb2704beffbb69c493265/grpcio-1.26.0rc1-cp38-cp38-macosx_10_9_x86_64.whl)
 - [Windows](https://files.pythonhosted.org/packages/69/21/384983868a1cdfa18bcc6e64853b7277e819bbef6d1170ad09618284f738/grpcio-1.26.0rc1-cp38-cp38-win_amd64.whl)

Check out the [full release page](https://pypi.org/project/grpcio/1.26.0rc1/#files) for more details.
