### ISSUE TITLE
regression #17002 reintroduced

### ISSUE THREAD

**Issue by pkit** [grpc/grpc#20619]
### What version of gRPC and what language are you using?

see #17002

### What operating system (Linux, Windows,...) and version?

see #17002

### What runtime / compiler are you using (e.g. python version or version of gcc)

see #17002

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

see #17002

### What did you expect to see?

see #17002

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

see #17002

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

bug/problem that was reported in #17002 was reintroduced in commit c1451e83d569b27ca0ed920ab72ef4c060591fcc
and macos builds fail again even with the newest master

**Comment by lidizheng** [comment]
@pkit Sorry we don't have enough bandwidth to fully trace down this issue right now. But I have one work around for you. Can you try to compile `grpcio` with `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1` env?

If you can help digging into this problem, it would be very helpful :)

**Comment by pkit** [comment]
@lidizheng somehow missed this one.
Will do and report. Thanks
