### ISSUE TITLE
FLAKE: github/grpc/run_tests/grpc-node_macos_dbg_native/tools/run_tests/helper_scripts/run_grpc-node.sh[default]

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20624]
https://source.cloud.google.com/results/invocations/976e0c37-65bf-4c20-a03b-bac6f1518893/log

It's not obvious from the log what the problem actually is.

**Comment by yashykt** [comment]
Another instance - https://source.cloud.google.com/results/invocations/9cd0c773-0894-4a31-80ba-e8ca143b30f9/targets
