### ISSUE TITLE
Generate C# gRPC services as interfaces with C# 8 default interface implementations

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [grpc/grpc#20620]
Please read #14213
gRPC services deliberately compile to abstract base classes instead of interfaces, because classes implementing these interfaces do not compile anymore when new methods are added to the interface but not to the class.
However, C# 8 added "Default Interface Methods", which should solve these issues. This new feature should be opt-in with a new command-line argument to protoc.exe because C# 8 requires .NET Core 3.0.

**Comment by barcoders** [comment]
Can someone tell me why it is so bad to "break the build" when new methods are added to the protocol?

When the proto file is updated with a new method, I **want** my build to break!  I want **the compiler** to tell me what methods I need to add!  I don't want to find them manually.

I don't want stubs which throw an "Unimplemented" exception.  I want them to be abstract methods (or interfaces) so the project won't compile until I implement the new methods.

Can we add a setting or command-line argument to make this happen?

**Comment by jtattermusch** [comment]
The idea is that grpc + protobuf services are supposed to be backwards compatible, so adding a new method (which is an allowed action in terms of backwards compatibility) should not break the existing implementation (not even the build, because the assumption is that the old version of the service will still work perfectly fine - if that's not the case, you shouldn't be adding a new method to an existing service at all).
For this reason, we cannot implement what you requested (definitely not before we release a new major version and we're not planning on that any time soon).

**Comment by barcoders** [comment]
Bottom line is I think there should be some automated tool that tells me, "Your C# server doesn't implement the following methods from this proto file. They will return unimplemented exceptions. You may want to add them."

The fact that there is no tool that can do this is, to me, crazy.

It could be a separate tool, called grpcaudit or grpclint or something. But in a compiled language, it would be natural for the compiler to do it via compilation errors or compilation warnings. I'm not asking you to change it for everyone. I'm just wishing there was a command-line switch to do it for those who opt in.

Is it possible to add a command-line switch for just the C# codegen? Can you tell me where in the code I might get started? I'm fine to fork...

**Comment by jtattermusch** [comment]
@barcoders  note that such tool can be written in ~15lines of reflection code (you're basically looking for methods of a base class that haven't been overriden, pretty trivial) and you can include it in your unit tests.

We are not planning to include a command line switch for the behavior - the bar for adding a command line switch is much higher (if we added a command line switch for every feature request, we would have 1000 switches by now).
