### ISSUE TITLE
pod `use_modular_headers!` does not work with BoringSSL-GRPC as a library

### ISSUE THREAD

**Issue by jmagman** [grpc/grpc#20631]
### What version of gRPC and what language are you using?
Embedded into Xcode project via CocoaPods:
```
PODS:
  - BoringSSL-GRPC (0.0.4):
    - BoringSSL-GRPC/Implementation (= 0.0.4)
    - BoringSSL-GRPC/Interface (= 0.0.4)
  - BoringSSL-GRPC/Implementation (0.0.4):
    - BoringSSL-GRPC/Interface (= 0.0.4)
  - BoringSSL-GRPC/Interface (0.0.4)
```

### What operating system (Linux, Windows,...) and version?
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87

### What did you do?
Create a Podfile with `use_modular_headers!` in conjunction with `pod 'BoringSSL-GRPC'` (I noticed this working with Firebase).
```ruby
target 'UseModularHeadersTest' do
  use_modular_headers!
  pod 'BoringSSL-GRPC'
end
```

### What did you expect to see?
No compilation errors.

### What did you see instead?
'/<>/Pods/Headers/Private/openssl_grpc/BoringSSL-GRPC.modulemap' not found
That file does not exist.
Everything works if `use_frameworks!` is used.

The real modulemap is here:
Pods/Target Support Files/BoringSSL-GRPC/BoringSSL-GRPC.modulemap
```
  module openssl {
    umbrella header "umbrella.h"
    textual header "arm_arch.h"
    export *
    module * { export * }
  }
```

BoringSSL-GRPC is specifying the modulemap explicitly:
https://github.com/grpc/grpc/blob/ead48a64a6df7c6bb3821af81692a4bf9470de5c/templates/src/objective-c/BoringSSL-GRPC.podspec.template#L114

**Comment by jmagman** [comment]
Evidently custom module map files for static libraries is not supported by CocoaPods.
https://github.com/CocoaPods/CocoaPods/issues/9023

**Comment by jmagman** [comment]
I guess you can close this if you want.  It doesn't look like grpc can do anything to make this work, other than removing the custom module map.

**Comment by muxi** [comment]
Yea unfortunately the modular headers do not work for gRPC, not only for BoringSSL-GRPC podspec but for all gRPC pods due to the difference in include styles. We purposely use the non-modular header approach to accommodate gRPC project's include style. Not ideal but it's non-trivial to change that for now. I don't think we will invest in that any time soon.
