### ISSUE TITLE
Cannot  install BoringSSL-GRPC pod

### ISSUE THREAD

**Issue by ikarelin** [grpc/grpc#20661]
Trying to build my project on Mac.
I have a BoringSSL-GRPC as a dependency of one of my pods.
So I'm trying to run:
`$ pod install`
And it takes forever with:
`Installing BoringSSL-GRPC (0.0.2)`
(Already spent 2-3 hours trying to build my project).

**Comment by muxi** [comment]
`BoringSSL-GRPC` pod is now 0.0.4. Something is not right in your project. We would need more information on your project to provide any further help I think.

**Comment by muxi** [comment]
Closing since we are not hearing response. We can reopen if necessary.
