### ISSUE TITLE
grpc.io website not accessible via HTTPS

### ISSUE THREAD

**Issue by dsymonds** [grpc/grpc#2067]
If I visit https://www.grpc.io/, my browser prevents me viewing it because the presented certificate is for www.github.com. gRPC's website should be HTTPS accessible.

**Comment by LisaFC** [comment]
I'll take a look. It's running using Github Pages and Jekyll, which *should* support HTTPS access.

**Comment by LisaFC** [comment]
Hrmm, seems it's only enabled by default for *.github.io domains. Will investigate further.

**Comment by LisaFC** [comment]
@mugurm as I think he set up the domain stuff.....

**Comment by LisaFC** [comment]
Though if America can do it then so can we: https://theunitedstates.io/

**Comment by jtattermusch** [comment]
@mugurm, friendly ping.

**Comment by johanbrandhorst** [comment]
This is still not fixed, and this issue doesn't have an explanation for why. If it's not possible with github pages it's trivial to do with netlify. Perhaps consider switching? It's frankly embarassing that a high profile google project like gRPC doesn't serve it's documentation of HTTPS.

**Comment by LisaFC** [comment]
Github Pages is the problem - it unfortunately doesn't support HTTPS for sites with a custom domain (which grpc.io uses). I know at least one other site that has used a workaround for it but IIRC it was pretty kludgey.

I have been looking into Netlify for other reasons so will add that to our "reasons to investigate".

**Comment by mehrdada** [comment]
This issue has been resolved. https://grpc.io works now.
