### ISSUE TITLE
FLAKE: "unknown file SEH exception with code 0xc0000005 thrown in TearDown()" failure on Windows

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20677]
https://source.cloud.google.com/results/invocations/804a4860-c905-46c2-8797-4ce1d4156699/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fchttp2:settings_timeout_test/tests

Yet another instance of the Windows "SEH exception" failure:

```
unknown file
SEH exception with code 0xc0000005 thrown in the test body.
```

**Comment by jtattermusch** [comment]
I checked a bunch of recent occurrences of the `//test/core/transport/chttp2:settings_timeout_test` test and here are the findings:

- it only happens on windows opt build
- this is one of the top windows RBE flakes, at 14% flakiness rate (so should be addressed ASAP)

All the occurrences I've seen have this error message:
```
Executing tests from //test/core/transport/chttp2:settings_timeout_test
-----------------------------------------------------------------------------
D1105 21:11:38.859000000  3584 test/core/util/test_config.cc:384] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1105 21:11:38.866000000  3584 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:503] Using ares dns resolver
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SettingsTimeout
[ RUN      ] SettingsTimeout.Basic
I1105 21:11:38.892000000  3584 test/core/transport/chttp2/settings_timeout_test.cc:226] starting server on localhost:32744
I1105 21:11:38.916000000  3584 test/core/transport/chttp2/settings_timeout_test.cc:230] starting client connect
I1105 21:11:39.864000000  3584 test/core/transport/chttp2/settings_timeout_test.cc:180] OnEventDone(): {"created":"@1572988299.864000000","description":"socket is null","file":"src/core/lib/iomgr/tcp_client_windows.cc","file_line":113}
test/core/transport/chttp2/settings_timeout_test.cc(118): error: Expected equality of these values:
  ((grpc_error*)0)
    Which is: NULL
  state.error()
    Which is: 000001F7A377A310
I1105 21:11:39.868000000  3584 test/core/transport/chttp2/settings_timeout_test.cc:234] starting client read
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] SettingsTimeout.Basic (978 ms)
```

**Comment by jtattermusch** [comment]
This doesn't look like an infrastructure flake and should be fixed by C-core team, so assigning to buildcop to triage further.

**Comment by jtattermusch** [comment]
Recent occurrences:
https://source.cloud.google.com/results/invocations/f231fcfd-5c01-4837-b20c-73b9fe87355a/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fchttp2:settings_timeout_test/log
https://source.cloud.google.com/results/invocations/6ae88c1d-ecbc-427a-a60c-8b01bba8001d/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fchttp2:settings_timeout_test/log
https://source.cloud.google.com/results/invocations/4c5d0770-4a87-4981-bf82-c32e48c36e9b/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fchttp2:settings_timeout_test/log
https://source.cloud.google.com/results/invocations/3f9cac3f-69b2-4d5c-9232-3ad50db77ae6/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fchttp2:settings_timeout_test/tests

**Comment by jtattermusch** [comment]
This is trivial to reproduce with a manual run on a windows machine: 

`bazel --bazelrc=tools/remote_build/windows.bazelrc test --config=windows_opt //test/core/transport/chttp2:settings_timeout_test  --runs_per_test=10`

**Comment by markdroth** [comment]
Seeing another occurrence of this in end2end test:

https://source.cloud.google.com/results/invocations/ed4bf68d-2917-4746-a9ec-2dcaa2de51df/targets/%2F%2Ftest%2Fcpp%2Fend2end:end2end_test/tests

**Comment by donnadionne** [comment]
{"created":"@1572988299.864000000","description":"socket is null","file":"src/core/lib/iomgr/tcp_client_windows.cc","file_line":113}

indicates tcp_client_windows may not have been able to successfully connect 

adding logs to confirm

**Comment by jtattermusch** [comment]
https://stackoverflow.com/questions/13157671/seh-exception-with-code-0xc0000005-thrown-in-the-test-body
