### ISSUE TITLE
Undefined reference to grpc_server_add_secure_http2_port

### ISSUE THREAD

**Issue by HndsmJohn** [grpc/grpc#20672]
### What version of gRPC and what language are you using?
1.25.0-dev, in C++

### What operating system (Linux, Windows,...) and version?
Linux ubuntu 16.04 (kernel version : 4.15.0-65-generic)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 5.4.0

### What did you do?
I tried to create a secure server based on the code provided by [this issue (#9593)](https://github.com/grpc/grpc/issues/9593).

### What did you expect to see?
I expected my program to compile.

### What did you see instead?
I got an linking error : 
```
/usr/local/lib/libgrpc++.a(secure_server_credentials.o): 
In function `grpc_impl::SecureServerCredentials::AddPortToServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, grpc_server*)':
(.text+0xe): undefined reference to `grpc_server_add_secure_http2_port'
```
After investigating I saw that the only references (in the install directory) to this function are in both ```libgrpc.a``` and ```libgrpc++.a``` as well as in the ```grpc_security.h``` file.
Both of these libraries are linked to my source code.

Here is the output of  ```grep -rn "grpc_server_add_secure_http2_port"``` in the directory grcp/src :
```
objective-c/tests/CronetTests/CoreCronetEnd2EndTests.mm:99:  GPR_ASSERT(grpc_server_add_secure_http2_port(f->server, ffd->localaddr.get(), server_creds));
php/ext/grpc/server.c:189:  RETURN_LONG(grpc_server_add_secure_http2_port(server->wrapped, addr,
ruby/ext/grpc/rb_grpc_imports.generated.h:416:typedef int(*grpc_server_add_secure_http2_port_type)(grpc_server* server, const char* addr, grpc_server_credentials* creds);
ruby/ext/grpc/rb_grpc_imports.generated.h:417:extern grpc_server_add_secure_http2_port_type grpc_server_add_secure_http2_port_import;
ruby/ext/grpc/rb_grpc_imports.generated.h:418:#define grpc_server_add_secure_http2_port grpc_server_add_secure_http2_port_import
ruby/ext/grpc/rb_grpc_imports.generated.c:149:grpc_server_add_secure_http2_port_type grpc_server_add_secure_http2_port_import;
ruby/ext/grpc/rb_grpc_imports.generated.c:422:  grpc_server_add_secure_http2_port_import = (grpc_server_add_secure_http2_port_type) GetProcAddress(library, "grpc_server_add_secure_http2_port");
ruby/ext/grpc/rb_server.c:330:    recvd_port = grpc_server_add_secure_http2_port(
core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc:40:int grpc_server_add_secure_http2_port(grpc_server* server, const char* addr,
core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc:48:      "grpc_server_add_secure_http2_port("
python/grpcio/grpc/_cython/_cygrpc/grpc.pxi:534:  int grpc_server_add_secure_http2_port(grpc_server *server, const char *addr,
python/grpcio/grpc/_cython/_cygrpc/server.pyx.pxi:84:        result = grpc_server_add_secure_http2_port(
csharp/ext/grpc_csharp_ext.c:1086:  return grpc_server_add_secure_http2_port(server, addr, creds);
cpp/server/secure_server_credentials.cc:102:  return grpc_server_add_secure_http2_port(server, addr.c_str(), creds_);
```

Does this function lack an implementation ?

### Anything else we should know about your project / environment?
I added the grpc repository as a submodule of my project. I built it with the default ```make``` command and installed it with a ```check install``` in the default install directory that is /usr/local/.

**Comment by yang-g** [comment]
I think more information is needed. From what you described, I cannot see why you are seeing the linker error.

**Comment by Brown-LiuZan** [comment]
The same issue.  Any progress?

**Comment by Brown-LiuZan** [comment]
My issue fixed.
With find_package() configured, it's not enough to just target_link_libraries() libgrpc++_unsecure.a and following librariries are also needed:
libgrpc_unsecure.a
libaddress_sorting.a
libgpr.a
c-ares/lib/libcares.a
zlib/lib/libz.a

**Comment by yashykt** [comment]
The question seems to be answered.

Also, this issue has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
