### ISSUE TITLE
CPP: Method TraceFlagList::Add(TraceFlag* flag) of trace.cc makes its chained list loop to itself

### ISSUE THREAD

**Issue by psylambda** [grpc/grpc#20690]
### What version of gRPC and what language are you using?
c++ 3.10.0-862.11.6.el7.x86_64

### What operating system (Linux, Windows,...) and version?
Linux 

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (GCC) 8.3.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
In bazel build,  

`cc_test A` dependends on `cc_library B` and `@com_github_grpc_grpc//:grpc++`

`cc_library B` depends on `@com_github_grpc_grpc//:grpc++_unsecure`

### What did you expect to see?
`grpc_init()` successfully returns.

### What did you see instead?
`grpc_init()` stuck at `bool TraceFlagList::Set(const char* name, bool enabled)`
Because the following for loop runs infinitely,

```
for (t = root_tracer_; t; t = t->next_tracer_) {
      if (0 == strcmp(name, t->name_)) {
        t->set_enabled(enabled);
        found = true;
      }
    }
```

I guess the problem is because some TraceFlags like `TraceFlag grpc_lb_glb_trace(false, "glb")` in `grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc` are defined twice.  

The constructor is called once in .so `@com_github_grpc_grpc//:grpc++`, and called another time in .so `@com_github_grpc_grpc//:grpc++_unsecure`, which results in `TraceFlagList` forms a cycle

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

The problem is very similar to an already opened [problem](https://stackoverflow.com/questions/57891055/method-traceflaglistaddtraceflag-flag-of-grpc-trace-cc-makes-its-chained-li) in StackOverflow.

**Comment by yang-g** [comment]
I think it is a mistake to depend on both grpc++ and grpc++_unsecure as currently they are kind of duplicates rather than one layering on top of each other. See the TODO in BUILD line 120.
