### ISSUE TITLE
//test/cpp/end2end:xds_end2end_test is flaky on UBSAN

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20695]
Saw failures in many recent builds on master.

https://source.cloud.google.com/results/invocations/e4cf8b14-1404-4fd2-a5fc-9d544f9decf3/targets
https://source.cloud.google.com/results/invocations/5831efb6-8e7f-43ca-b183-9ee7daf3c131/targets

The "Unevaluated target" might actually be a timeout problem.

**Comment by jtattermusch** [comment]
This is happening for more than 50% of UBSAN builds on master. Suggest raising to P1.

**Comment by jtattermusch** [comment]
Suspect PRs merged around the time when the flakiness rate increased
https://github.com/grpc/grpc/pull/20526
https://github.com/grpc/grpc/pull/20542

**Comment by markdroth** [comment]
How do we tell whether the "unevaluated target" is a timeout?  I'm not sure how to debug this, given that there are no logs from the test.

**Comment by yashykt** [comment]
```
[24,109 / 24,310] 4852 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=epoll1; 145s remote ... (200 actions running)
[27,675 / 27,878] 5736 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=epoll1; 215s remote ... (200 actions, 199 running)
[31,753 / 31,960] 6783 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=epoll1; 295s remote ... (200 actions running)
```

This is the last log I see. Do we have a timeout of 5 minutes on the test? In that case, should we simply increase it?

**Comment by yashykt** [comment]
Nevermind, on the other logs, I saw this - 
```
[24,736 / 29,089] 1820 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 163s remote ... (200 actions running)
[25,130 / 29,089] 2215 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 200s remote ... (200 actions running)
[25,669 / 29,089] 2753 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 241s remote ... (200 actions running)
[26,245 / 29,089] 3330 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 289s remote ... (200 actions running)
[26,931 / 29,089] 4015 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 345s remote ... (200 actions running)
[27,745 / 29,089] 4830 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 408s remote ... (200 actions running)
[28,571 / 29,089] 5655 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 481s remote ... (200 actions running)
[31,327 / 31,527] 6611 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 565s remote ... (200 actions running)
[35,909 / 36,111] 7852 / 8114 tests; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 661s remote ... (200 actions, 199 running)
```

**Comment by jtattermusch** [comment]
@markdroth  Normally timeouts are reported timeouts, but in this particular case there seems to be some problem (could be because some of our tests are misconfigured), I don't know it's a timeout for sure, but I made a guess based on seeing similar situation in the past and I though that this insight might help investigating.

How to debug: Seems that the best bet is to try starting the RBE test manually (it runs on the same cluster, with same settings, so you're very likely to be able to reproduce)?
`bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=ubsan //test/cpp/end2end:xds_end2end_test@poller=epollex --runs_per_test=10`
(as documented in https://github.com/grpc/grpc/tree/master/tools/remote_build)

Also, a good check would be to run bisect to confirm/reject the hypothesis it's one of the PRs that seems to have some connection the failure when triaging.

Btw, one of my observations is that the regular run time for the xds_end2end_test  (under UBSAN specifically) is  ~1600-1800seconds (and it's around ~1000sec under opt). That to me seems crazy. I'm not surprised at all that with tests designed to run for such long time we are facing problems with timeouts that are hard to debug.

**Comment by jtattermusch** [comment]
I ran the with the above command with --runs_per_test=10 
and got this result (unfortunately I didn't see the exact same error, but I ran into some other failure).
https://source.cloud.google.com/results/invocations/5e07f89d-50ef-4969-a1aa-5e7c61be0ec6/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Depollex;shard=1;run=10/tests

**Comment by jtattermusch** [comment]
Looks like the xds_end2end_test is by far the slowest bazel test we have:
Here's the avg runtime in seconds for the longest tests over the last few days.

```

grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/cpp/end2end:xds_end2end_test@poller=poll | 1965.9316666666662 |  
-- | -- | -- | --
2 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/cpp/end2end:xds_end2end_test@poller=epollex | 1857.05786111111 |  
3 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/cpp/end2end:xds_end2end_test@poller=epoll1 | 1632.7458240740737 |  
4 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller=poll | 157.28865000000002 |  
5 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_sockpair_1byte_test@cancel_after_invoke@poller=epoll1 | 156.9729 |  
6 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_sockpair_1byte_test@cancel_after_invoke@poller=epollex | 156.64929999999998 |  
7 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_sockpair_1byte_test@cancel_after_invoke@poller=poll | 156.469 |  
8 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller=epollex | 156.2662 |  
9 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_sockpair_1byte_nosec_test@cancel_after_invoke@poller=epoll1 | 156.23655 |  
10 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_http_proxy_nosec_test@cancel_after_invoke@poller=epollex | 143.37025 |  
11 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_http_proxy_test@cancel_after_invoke@poller=epollex | 142.8877 |  
12 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_http_proxy_test@cancel_after_invoke@poller=poll | 138.64145 |  
13 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/core/end2end:h2_http_proxy_nosec_test@cancel_after_invoke@poller=poll | 137.58095 |  
14 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_ubsan | //test/cpp/end2end:server_crash_test@poller=epoll1 | 134.51895
```

**Comment by jtattermusch** [comment]
@markdroth 

This has been failing a large number of USBAN runs on master (>50%, the grey ones in https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fbazel_rbe%2Fgrpc_bazel_rbe_ubsan)

Recent Examples:
https://source.cloud.google.com/results/invocations/5a366242-1bc7-4fa9-96ad-623ba67c2b85/targets
https://source.cloud.google.com/results/invocations/2e5e1bb8-7c8d-4df9-9f80-2f5092eacf7d/targets
https://source.cloud.google.com/results/invocations/1eb0a5b4-b512-4d4b-9eb8-79f5f01200ae/targets

The reason why the tests show up as "Unevaluated" is pretty complicated (but everything is described in detail in b/143134296), but basically it boils down to `xds_end2end_test` taking way too long (>25 mins on ubsan), which is something that RBE currently has problems handling.
As explained above, the 25min duration seems to high in general and it's degrading our testing experience regardless of the RBE problem, so it would be good to reduce the xds_end2end_test runtime anyway.

Can we make the xds_end2end_test run faster or split it up into some logical units?

**Comment by jtattermusch** [comment]
@markdroth  friendly ping, this is our top source of flakiness (and tool failures) for bazel RBE tests.

**Comment by markdroth** [comment]
Sorry for the delay; I've been a bit backlogged lately.  I probably won't have time to look at this before Thanksgiving, but I'll look at it the week after.
