### ISSUE TITLE
nmake is slow on windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2070]
We currently build tests on Windows using nmake.exe (MS flavor of make) from makefile vsprojects/Grpc.mak

It turns out nmake can only build tests one by one and given there's a large number of tests, the build step on Windows takes long time and there's a chance it would time out.

**Comment by ctiller** [comment]
Consider ninja

**Comment by jtattermusch** [comment]
My plan was to generate an msbuild file instead of nmake file (msbuild supports parallel jobs, unlike nmake) or look into jom (which should be nmake compatible, but supports -j option).

I think an msbuild project would be the most portable solution for users coming from windows.

**Comment by jtattermusch** [comment]
We are not using nmake anymore.
