### ISSUE TITLE
Upgrade the Python in Bazel Docker Image to 3.6+

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20723]
Currently, the Docker image we are using for all Bazel tests is `grpctesting/bazel_400859c7360e244a6d8f2dffd1e3cfd56ae9cfd4`. Its Python version is `3.5.2` which is lower than minimal requirement of gRPC Async Stack (3.6).

The tricky thing is that the image is originated from [oss-fuzz](https://github.com/google/oss-fuzz/blob/master/projects/grpc/Dockerfile). Hope this can happen soon.

Blocking: https://github.com/grpc/grpc/issues/20117

**Comment by gnossen** [comment]
Do we know the origin of this image or who owns it? Perhaps `docker history` would be enlightening?

**Comment by lidizheng** [comment]
I can only see @yang-g 's signature on the image.

@jtattermusch Hi Jan, do we know if we are using this Bazel image for fuzzing test? If we can switch the base image, 3.6 installation will be easier.

**Comment by jtattermusch** [comment]
I know that fuzzing is being run for us in an external project (so there might be a good reason for inheriting the docker image from oss-fuzz, but I don't remember the details.
