### ISSUE TITLE
How to read async server side streaming using c++

### ISSUE THREAD

**Issue by LaxmiAhirwar** [grpc/grpc#20730]
Hi everybody,

I am trying to implement asynchronous server side streaming using C++.  but I am not able to find any good example for the same. i am having hard time with reading stream asynchronously.

This is my client code -----
class GreeterClient
{
public:
    GreeterClient(std::shared_ptr<Channel> channel)
        : stub_(MultiGreeter::NewStub(channel))
    {}
    void SayHello(const std::string& user, const std::string& num_greetings)
    {
        HelloRequest request;
        request.set_name(user);
        request.set_num_greetings(num_greetings);
        ClientContext context;
        CompletionQueue cq;
        void* got_tag = (void*)1;
        bool ok = false;
       std::unique_ptr<ClientAsyncReader<HelloReply>>       reader(stub_>PrepareAsyncSayHello(&context,request, &cq));    
            std::cout << "Got reply: " << reply.message() << std::endl;          
            reader->Read(&reply,got_tag);
        Status status;
       reader->Finish(&status, (void*)1);
        GPR_ASSERT(cq.Next(&got_tag, &ok));
        GPR_ASSERT(ok);   
        if (status.ok()) 
        {
            std::cout << "sayHello rpc succeeded." << std::endl;
        } 
        else 
        {
            std::cout << "sayHello rpc failed." << std::endl;
            std::cout << status.error_code() << ": " << status.error_message() << std::endl;
        }
    }
private:
    std::unique_ptr<MultiGreeter::Stub> stub_;
};

My proto service -----
rpc SayHello (HelloRequest) returns (stream HelloReply) {}

I am getting this error-
Assertion failed: (started_), function Finish, file /usr/local/include/grpcpp/impl/codegen/async_stream_impl.h, line 250.
23:25:40: The program has unexpectedly finished.

Thanks in advance.

**Comment by yang-g** [comment]
The best example we can might be client_async.cc under test/cpp/qps

There are several issues in your code
1. you will need to call reader->StartCall after your PrepareAsyncSayHello
2. Every time after you issue the tag, you need to call cq.Next and wait for the tag to get back before you can issue another api call. Thus you need to insert cq.Nexts to right after StartCall, after Read.

**Comment by LaxmiAhirwar** [comment]
I tried to do it what u said. but I am still getting the same error. 

This is my updated client code---
class GreeterClient
{
public:
    enum Type {
        CONNECT = 1,
        READ = 2,
        FINISH = 3
      };
    GreeterClient();
    GreeterClient(std::shared_ptr<Channel> channel)
        : stub_(MultiGreeter::NewStub(channel))
    {
        grpc_thread_.reset(
                    new std::thread(std::bind(&GreeterClient::GrpcThread, this)));
        reader = stub_->PrepareAsyncSayHello(&context, request, &cq);
    }

void SayHello(const std::string& user, const int& num_greetings)
    {
        request.set_name(user);
        request.set_num_greetings(num_greetings);
       reader->StartCall(reinterpret_cast<void*>(Type::CONNECT));
        std::cout << "Got reply: " << reply.message() << std::endl;
        reader->Read(&reply,reinterpret_cast<void*>(Type::READ));
  }
void GrpcThread() {
        while (true) {
            void* got_tag;
            bool ok = false;
            if (!cq.Next(&got_tag, &ok)) {
                std::cerr << "Client stream closed. Quitting" << std::endl;
                break;
            }

            if (ok) {
                std::cout << std::endl
                          << "**** Processing completion queue tag " << got_tag
                          << std::endl;
                switch (static_cast<Type>(reinterpret_cast<long>(got_tag))) {
                case Type::READ:
                    std::cout << "Read a new message." << std::endl;
                    break;
               case Type::CONNECT:
                    std::cout << "Server connected." << std::endl;
                    break;
                case Type::FINISH:
                    std::cout << "Client finish; status = "
                              << (status.ok() ? "ok" : "cancelled")
                              << std::endl;
                    context.TryCancel();
                    cq.Shutdown();
                    break;
                default:
                    std::cerr << "Unexpected tag " << got_tag << std::endl;
                    GPR_ASSERT(false);
                }
            }
        }
    }

private:
    std::unique_ptr<MultiGreeter::Stub> stub_;
    std::unique_ptr<std::thread> grpc_thread_;
    std::unique_ptr<ClientAsyncReader<HelloReply>> reader;
    CompletionQueue cq;
    HelloReply reply;
    ClientContext context;
    HelloRequest request;
    grpc::Status status = grpc::Status::OK;
};
