### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ConnectivityState'

### ISSUE THREAD

**Issue by P4-WCZ** [grpc/grpc#20747]
Hello,someone.
I‘m using Linux ubuntu16.04,which python version is 3.5.When i run example/helloworld/greet_server.py in pycharm,it raises an error:’
![image](https://user-images.githubusercontent.com/55369151/67348432-86068b80-f577-11e9-8c1e-78b2889d7115.png)
Thanks someone for helping me.

**Comment by gnossen** [comment]
This sort of error generally indicates a packaging problem, e.g. a mismatch between Python interpreter version and wheel version. Can you please supply more information about the exact gRPC wheel that you installed?

**Comment by P4-WCZ** [comment]
Hello gnossen,  I git grpc from GitHub on Ubuntu16. I can run _python greet_server.py_ successfully in _/example/python/helloworld/_. However when i put grpc/src/python/grpcio/grpc module(have install grpcio and grpcio-tools sucessfully) and greet_server.py into pycharm and run the file,it raises error.I think some files is missing or others?
![aa](https://user-images.githubusercontent.com/55369151/67539773-c996fc00-f715-11e9-93ca-99e0e48fbc9f.png)
This is my pycharm's settings.
Thank you for helping me@@

**Comment by gnossen** [comment]
How are you installing the `grpcio` package? From source, or with pip. In the latter case, please provide the install logs. [There are many different files it could be](https://pypi.org/project/grpcio/1.24.3/#files), even knowing that it's 1.24.3.

**Comment by gnossen** [comment]
Also, in the future, please use the issue template. Much of this information is asked for in the template. Also, please prefer text to screenshots where possible.
