### ISSUE TITLE
C++ Server Stuck in TraceFlagList:Set during startup

### ISSUE THREAD

**Issue by Thalhammer** [grpc/grpc#20757]
### What version of gRPC and what language are you using?
1.24.3
C++

### What operating system (Linux, Windows,...) and version?
Linux <host> 5.3.0+ #1 SMP Wed Oct 2 16:58:18 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

### What did you do?
Build an existing project against the most recent version of GRPC.

### What did you expect to see?
Everything working as expected.

### What did you see instead?
Server hangs during BuildAndStart in method TraceFlagList::Set.

### Anything else we should know about your project / environment?
There has been a similar bug to this which was closed with mentioning that you should not link against both grpc_unsecure and grpc, however I don't do this and still have an endless loop.
See #20690 
So instead of ignoring this and seeing is as a user error, I suggest adding to the end of the list which should prevent endless loops, as the last element will always be null.
Please see below patch file for a quick workaround.
[tracer.txt](https://github.com/grpc/grpc/files/3761430/tracer.txt)

NOTE: This is a workaround which hides the real problem of TraceFlag constructor getting executed twice with the same object. I don't know why this happens in my case.

**Comment by yashykt** [comment]
I have two comments here - 
1) As described in #20690, depending on grpc++ and grpc++_unsecure is likely to cause many other such issues. If this is the only issue that is being caused, then I am not AGAINST adding this as a paper fix. An important thing to realize is that we will not have tests against this so there is NO guarantee that this will not break in the future.
2) Users are encouraged to create pull requests, especially in this case where you already have a supposed fix.

**Comment by yashykt** [comment]
Also, cc-ing @yang-g as the original commentor

**Comment by yang-g** [comment]
I am against having cover-up changes to work around a problem that not fully understood. If you have a way to reproduce your issue, we can take a look at why it is experiencing the problem.

**Comment by Thalhammer** [comment]
While trying to build a minimal example that reproduces the problem, I found the error I had in my case.
I have a situation where I have multiple libraries which all use parts of grpc(or grpc++ which in turn uses grpc). Looks like for whatever reason one of the project build files picked grpc as a static lib while all the others had it linked dynamically. After making sure they all use the either the static or the dynamic lib it worked fine again.

I therefore do not consider this a bug, but rather missing documentation issue. I am not the first and not the last person the stumble upon this and as you mentioned linking to both grpc++ and grpc++_unsecure might cause even more funny bugs. I think there should be a big and visible notice somewhere in the documentation to warn users that this can happen. Or even better: Since we already have a place where it creates problems: Why not check for this and issue a warning (or even abort the process, which should be fine, as it will not work correctly anyway) in case this is detected.

**Comment by yashykt** [comment]
Created https://github.com/grpc/grpc/issues/20871

**Comment by sudhagarc** [comment]
Hmm! I notice this issue when executing greeter_server & client (.../grpc/examples/cpp/helloworld).  The patch provided in https://github.com/grpc/grpc/issues/20757#issue-511191128 works for me. I don’t see examples (helloworld) linking to both grpc++ and unsecure. So, I’m wondering whether this is really not a bug or something in my environment? Any inputs appreciated.

**Comment by agudpp** [comment]
I had the same issue, hanging there forever. It started to happen (I think) when updated to the last version of protobuf (latest master), since I was getting a issue with different versions detected on the header (which comes from multiple versions of the lib). After updating protobuf I recompiled grpc again from scratch.
I also triple verified that there were no link against static libs anywhere (deleted all versions of static libs for protobuf and grpc). Also ensured that I was only compiling against grpc++ or unsecure isolated (the example) but still happening. Before that I was compiling against both grpc++ and unsercure but no issues hanging on the `TraceFlagList::Set` part.
After applying the patch mentioned worked perfectly again. (`g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609`)
