### ISSUE TITLE
rad studio build error

### ISSUE THREAD

**Issue by rhineswimmer** [grpc/grpc#20779]
### What version of gRPC and what language are you using?
v1.24.3

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
c++ RadStudio  bcc64 v5.0.2  + ilink64 v6.90 +Ninja

### What did you do?
I tried to build grpc using cmake. Firstly, I've completed everything from http://docwiki.embarcadero.com/RADStudio/Rio/en/Using_CMake_with_C%2B%2B_Builder  . Then called cmake like >>  cmake .. -DCMAKE_C_COMPILER=bcc64.exe -DCMAKE_CXX_COMPILER=bcc64.exe -G Ninja 

### What did you expect to see?
Successfully build grpc.

### What did you see instead?
I've got a multiple Unresolved external error from the linker:

[1386/1401] cmd.exe /C "cd . && C:\PROGRA~2\EMBARC~1\Studio\20.0\bin\bcc64.exe -othird_party\protobuf\protoc.exe -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug/psdk" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release/psdk" -v -tC  -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug/psdk" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release/psdk" -tM  -O0 -g   third_party\protobuf\protocd.lib  third_party\protobuf\protobufd.lib third_party\protobuf\CMakeFiles\protoc.dir\__\src\google\protobuf\compiler\main.cc.obj && cd ."
FAILED: third_party/protobuf/protoc.exe
cmd.exe /C "cd . && C:\PROGRA~2\EMBARC~1\Studio\20.0\bin\bcc64.exe -othird_party\protobuf\protoc.exe -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug/psdk" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release/psdk" -v -tC  -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/debug/psdk" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release" -L "C:/Program Files (x86)/Embarcadero/Studio/20.0/lib/win64/release/psdk" -tM  -O0 -g   third_party\protobuf\protocd.lib  third_party\protobuf\protobufd.lib third_party\protobuf\CMakeFiles\protoc.dir\__\src\google\protobuf\compiler\main.cc.obj && cd ."
Embarcadero C++ 7.40 for Win64 Copyright (c) 2012-2018 Embarcadero Technologies, Inc.
Embarcadero Technologies Inc. bcc64 version 5.0.2 (36917.e4aabb3.b018c58) (based on LLVM 5.0.2)
Target: x86_64-pc-windows-elf
Thread model: posix
InstalledDir: C:\Program Files (x86)\Embarcadero\Studio\20.0\bin
bcc64.exe: warning: argument unused during compilation: '-nobuiltininc' [-Wunused-command-line-argument]
 "\"C:\\Program Files (x86)\\Embarcadero\\Studio\\20.0\\bin\\ilink64.exe\"" "@\"C:\\Users\\maz\\AppData\\Local\\Temp\\protoc-14b3b2.cfg\""
Turbo Incremental Link64 6.90 Copyright (c) 1997-2017 Embarcadero Technologies, Inc.
Error: Unresolved external 'google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|command_line_interface.cc.obj
Error: Unresolved external 'google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::internal::LogMessage::operator<<(char const*)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::internal::LogMessage::~LogMessage()' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::internal::fixed_address_empty_string' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::SplitStringUsing(std::string const&, char const*, std::vector<std::string, std::allocator<std::string> >*)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::SplitStringAllowEmpty(std::string const&, char const*, std::vector<std::string, std::allocator<std::string> >*)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|code_generator.cc.obj
Error: Unresolved external 'google::protobuf::io::win32::open(char const*, int, int)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|command_line_interface.cc.obj
Error: Unresolved external 'google::protobuf::io::win32::write(int, void const*, unsigned long long)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|command_line_interface.cc.obj
Error: Unresolved external 'google::protobuf::io::win32::close(int)' referenced from C:\USERS\MAZ\DOCUMENTS\GRPC_TEST2\REPO\GRPC\.BUILD\THIRD_PARTY\PROTOBUF\PROTOCD.LIB|command_line_interface.cc.obj

... and many errors like this.

### Anything else we should know about your project / environment?

Has anyone ever used RadStudio compiler for that?

**Comment by rhineswimmer** [comment]
SOLVED!!!
Needed to say that I was wrong about symbols, they are really absent in the static library. Moreover, the size of grpc.lib, grpc_cronet.lib, grpc_cpp_unsecure.lib and libprotobuf.lib was suspiciously small: from 1Kb to 198Kb.  As it turned out, the rule for linkage in rules.ninja was wrong:
rule CXX_STATIC_LIBRARY_LINKER__grpc
  command = cmd.exe /C "$PRE_LINK && tlib64 /p2048 $LINK_FLAGS /a "$TARGET_FILE" @$RSP_FILE && $POST_BUILD"
  description = Linking CXX static library $TARGET_FILE
  rspfile = $RSP_FILE
  rspfile_content = $in_newline $LINK_PATH $LINK_LIBRARIES     <<<== WRONG!!!

The working variant looks like this:
  rspfile_content = $in $LINK_PATH $LINK_LIBRARIES     

Just replace $in_newline  with $in and it will work for tlib64.  Seems like it is connected with MVSC  (see https://ninja-build.org/manual.html#_conceptual_overview ).  In theory everything must work with $in_newline  also because the RSP_FILE contains a list of obj files separated by \n but it doesn't. Maybe it is RadStudio specific.

**Comment by yashykt** [comment]
Glad that you got it working :)

**Comment by rhineswimmer** [comment]
No problem! RadStudio compiler and linker are really specific, I had to make changes in two dozen of files to make it work. Anyone who still have to use  ugly-buggy-crappy toolset by Embarcadero feel free to ask any questions :)

**Comment by ycdtosa** [comment]
I am late to the party, but seeing that grpc is using protobuffers, did you manage to build the protobuffers runtime / library with RadStudio?
