### ISSUE TITLE
Can't build plugin, get error

### ISSUE THREAD

**Issue by Ku6ep** [grpc/grpc#20786]
### What version of gRPC and what language are you using?

Swift 5.1, 3.1.0 

### What operating system (Linux, Windows,...) and version?

Mac
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
make
### What did you expect to see?
No error

### What did you see instead?

Resolving https://github.com/apple/swift-protobuf.git at 1.0.3
/Users/Ku6ep/grpc-swift/Sources/CgRPC/src/core/tsi/alts/zero_copy_frame_protector/alts_iovec_record_protocol.cc:52:5: error: use of undeclared identifier 'assert'
    assert(*dst != nullptr);
    ^
1 error generated.
[11/761] Compiling alts_transport_security.cc
make: *** [all] Error 1

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
Is this https://github.com/grpc/grpc-swift/issues what you are looking for?
