### ISSUE TITLE
C++ ServerWriter<>->Write() always returns false

### ISSUE THREAD

**Issue by tmartin-gh** [grpc/grpc#20797]
My use case is to have a client connect to a server with an "rpc ... returns (stream ...)" where the server will forever call writer->Write() every few seconds with updates until the client disconnects. 

### What version of gRPC and what language are you using?
v1.24.3

### What operating system (Linux, Windows,...) and version?
Linux ubuntu-18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Modified the route_guide example.  Server is C++, client is Go or Python.

Server modifications:
continue calling writer->Write() while return value is true 

Client modifications (for Python):
continue calling response.next() while StopIteration exception not thrown.

### What did you expect to see?
Since client never closes connection, server's writer->Write() should always return true. 

### What did you see instead?
writer->Write() returns false after first call

This seems kinda-sorta similar to #14812 and/or #20409 except I'm not using Async mode and the stream is on the server side not client side.

**Comment by yashykt** [comment]
A Write returning false indicates that the stream has been closed. If you collect detailed logs, you would see the reason as to why the stream was closed. As an alternative, you could check the status details on the client side too.

**Comment by tmartin-gh** [comment]
In the process of sanitizing my code to provide an executable snippet, I found it was a (very very stupid) bug in my code.  I confirm this feature is working as expected - Write() returns true while the client is still connected and returns false once it disconnects.
