### ISSUE TITLE
gRPC throws "Did not read entire message" for unknown reason

### ISSUE THREAD

**Issue by AntonQubecinema** [grpc/grpc#20802]
# What version of gRPC and what language are you using?
`v1.24.3`, C++, Python

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 18.04, x64

### What runtime / compiler are you using (e.g. python version or version of gcc)
```bash
gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
```
```bash
python3 --version
Python 3.6.8
```

### What did you do?
We use gRPC in our product (thank you for it). Our testers reported a bug that one of the APIs didn't work.

### What did you expect to see?
Working rpc.

### What did you see instead?
```
"Did not read entire message","grpc_status":13"
```
For no reason we faced the error ^^ above. I did some investigations and figured out that the issue could be fixed simply by the variables re-ordering in that particular message.

### Sample application
I've written a sample application to confirm the bug https://github.com/AntonQubecinema/grpc-issue. Please refer to README for the details.

If you need any help, feel free to contact me here.

**Comment by yashykt** [comment]
Esun, can you take a look?

**Comment by AntonQubecinema** [comment]
@yashykt is there any hope that this will be resolved?

**Comment by yashykt** [comment]
This should not have been closed, sorry for that!
 @veblush ping

**Comment by yashykt** [comment]
I decided to take a look myself since it seemed interesting.

I was unable to replicate the build instructions exactly, so I had to copy over the content to my existing setup.

Looking at the example, I was first suspicious of the name 'option' being used. I would expect protobuf to treat that as a keyword and give an error on compilation, but surprisingly it did not.

On running the example with grpc_cli, the RPC succeeded with both TestFailed and TestPassed.

**Comment by AntonQubecinema** [comment]
@yashykt thanks for your response! 
Please let me know if you have any questions.

**Comment by yashykt** [comment]
My above response does use grpc_cli so it does not seem to be reproducible with a C++ client (grpc_cli).

I tried creating a Python client too and this time TestFailed did fail with the following log - 
```
_open_source_grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = ""
	debug_error_string = "{"created":"@1597740539.550490995","description":"Error received from peer ipv4:127.0.0.1:1234","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"","grpc_status":13}"
```

I did suspect that the field name 'option' might be causing an issue but that turned out to not be the case, since TestFailed still failed even after changing the field name to 'optiona'. 

Based on this, I do acknowledge that this is weird behavior and should be investigated though this bug might potentially lie in protobuf territory. I doubt gRPC Python is doing anything special for serializing the protos, but I will ask the Python folks @lidizheng  @gnossen for their opinion.

**Comment by yashykt** [comment]
(Lidi, Richard: I've got an internal setup ready for reproducing the bug if the steps provided by @AntonQubecinema do not work for you either)

**Comment by lidizheng** [comment]
After running the example, I can reproduce the error. However, I find Python client serializes the `TestFailedRequest` successfully and the `StatusCode.INTERNAL` was returned by Core as an event.

**Comment by lidizheng** [comment]
Unfortunately, this doesn't seem like a gRPC Python issue but an issue between ProtoBuf and Core. gRPC Python client's behavior looks legit but peer returned internal error.

@AntonQubecinema Can you help to provide the tracing log for both the Python client and the C++ server? To turn on tracing, set environment variable `GRPC_TRACE=all` and `GRPC_VERBOSITY=debug`. See https://github.com/grpc/grpc/blob/master/doc/environment_variables.md for more details.

**Comment by yashykt** [comment]
@lidizheng did the internal repro not work for you?

**Comment by lidizheng** [comment]
@yashykt It works (is reproducible). But I still can't get the tracing log with debug build.

**Comment by AntonQubecinema** [comment]
> @AntonQubecinema Can you help to provide the tracing log for both the Python client and the C++ server? To turn on tracing, set environment variable GRPC_TRACE=all and GRPC_VERBOSITY=debug. See https://github.com/grpc/grpc/blob/master/doc/environment_variables.md for more details.

Please see the attached files, @yashykt , @lidizheng 
[client.log](https://github.com/grpc/grpc/files/5102404/client.log)
[server.log](https://github.com/grpc/grpc/files/5102405/server.log)

**Comment by lidizheng** [comment]
From the tracing log, the binary message was sent out of client, but it is still unclear why the server directly set status code to 13 (INTERNAL).

**Comment by yashykt** [comment]
@lidizheng is there a difference when compared to a C++ client?

**Comment by lidizheng** [comment]
I haven't got time to produce the tracing log and compare the actual bytes yet.

**Comment by AntonQubecinema** [comment]
@yashykt @lidizheng 
Me added [C++ client to the demo](https://github.com/AntonQubecinema/grpc-issue/blob/master/src/Client.cpp)
Both tests passed for C++ client. See the tracing logs attached.
[cpp-client.log](https://github.com/grpc/grpc/files/5142665/cpp-client.log)
[cpp-server.log](https://github.com/grpc/grpc/files/5142666/cpp-server.log)

**Comment by lidizheng** [comment]
Thank you for providing the trace log for both languages.

For server side, unfortunately, there isn't any interesting log about why the method decided to return a status code 13.

For client side, the only difference I found is the encoded protobuf message:
```
C++ Client:    DATA: 00 00 00 03 00 00 00 00 0f 0a 0d 0a 06 62 6c 61 62 6c 61 10 f4 03 18 '.............blabla....'
Python Client: DATA: 00 00 00 03 00 00 00 00 0d 0a 06 62 6c 61 62 6c 61 10 f4 03 18 01 00 '...........blabla......'
```

So, I checked the encoded message for these two client. There are 2 bytes difference:
```
C++ Encoded Message:    0A 0D 0A 06 62 6C 61 62 6C 61 10 F4 03 18 01
Python Encoded Message:       0A 06 62 6C 61 62 6C 61 10 F4 03 18 01
```

This is definitely something wrong, and I created an issue https://github.com/protocolbuffers/protobuf/issues/7863 to their repo.

**Comment by lidizheng** [comment]
@AntonQubecinema Awkwardly, a ProtoBuf maintainer pointed out that the Python client is creating the sub message `TestFailedMsg` https://github.com/AntonQubecinema/grpc-issue/blob/master/client/manual/test_client.py#L24. While C++ client is creating legitimate `TestFailedRequest`.

Why the malformed Python client passes the first unit test is still unclear to me. It could be those two different messages accidentally have the same serialized output.

**Comment by yashykt** [comment]
whoops, this turned out to be a wild-goose chase

**Comment by AntonQubecinema** [comment]
@lidizheng @yashykt thanks for your time, guys! Such a stupid mistake ...
