### ISSUE TITLE
[FLAKE] macOS grpc_basictests_c_cpp Build script failed with exit code: 1

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20816]
https://source.cloud.google.com/results/invocations/64f4d179-085f-43b0-b4e6-52648495ccd1/targets;collapsed=/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp/log

**Comment by yashykt** [comment]
This seems like one of the many 'File has vanished' bugs

**Comment by yashykt** [comment]
dup of #20694
