### ISSUE TITLE
[FLAKE] Windows portability test timeout

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20817]
https://source.cloud.google.com/results/invocations/e47b5335-af79-4615-80c9-e22b49d7fb98/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_c%2B%2B_windows_dbg_native_x64_cmake_vs2017_buildonly/tests

**Comment by yashykt** [comment]
Jan, can you take a look please?

**Comment by jtattermusch** [comment]
Not much to see there, looks like the build has just gotten stuck
```
2019-10-25 13:19:22,759 START: cmake

2019-10-25 14:15:47,283 TIMEOUT: run_tests_c++_windows_dbg_native_x64_cmake_vs2017_buildonly [pid=2684, time=3600.1sec]
```

**Comment by yashykt** [comment]
seems outdated
