### ISSUE TITLE
make error for php gRPC

### ISSUE THREAD

**Issue by luqman27180** [grpc/grpc#20827]
[root@localhost grpc]# make
[MAKE]    Generating cache.mk
[MAKE]    Building protobuf
checking whether to enable maintainer-specific portions of Makefiles... yes
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
make: *** [/var/www/html/grpc/libs/opt/protobuf/libprotobuf.a] Error 1

**Comment by stanley-cheung** [comment]
Not a grpc specific issue. You are probably missing some dependencies like `automake`, `autoconf` or `libtool`.
