### ISSUE TITLE
GRPC's build system is incompatible with external dependencies

### ISSUE THREAD

**Issue by HunterLarco** [grpc/grpc#20828]
### What version of gRPC and what language are you using?
1.24.3

### What operating system (Linux, Windows,...) and version?
Linux — Ubuntu 18.04.3 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-6 (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

**WORKSPACE**
```python
# Install GRPC

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "c84b3fa140fcd6cce79b3f9de6357c5733a0071e04ca4e65ba5f8d306f10f033",
    strip_prefix = "grpc-1.24.3",
    url = "https://github.com/grpc/grpc/archive/v1.24.3.tar.gz",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps", "grpc_test_only_deps")

grpc_deps()
grpc_test_only_deps()

# FIXME: Until grpc/commit/c22c215ea548838bc4cf2d400fd34ec409cb82af is
# released, we need to explicitly include grpc's children dependencies.

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
load("@upb//bazel:workspace_deps.bzl", "upb_deps")
load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")

protobuf_deps()
upb_deps()
api_dependencies()
go_rules_dependencies()
go_register_toolchains()
apple_rules_dependencies()

# Install GRPC Proto

http_archive(
    name = "com_google_grpc_proto",
    sha256 = "73c362cb2223d746ce6d22d203babfe8e51be4080549402a72256c2c77b9f58d",
    strip_prefix = "grpc-proto-5ce8e3e598b805a1e0372062913f24b0715fdefc",
    url = "https://github.com/grpc/grpc-proto/archive/5ce8e3e598b805a1e0372062913f24b0715fdefc.zip",
)
```

**BUILD**
```python
cc_proto_library(
    name = "health_cc_proto",
    deps = ["@com_google_grpc_proto//:health_proto"],
)

cc_grpc_library(
    name = "health_grpc_proto",
    srcs = ["@com_google_grpc_proto//:health_proto"],
    deps = [":health_cc_proto"],
    grpc_only = True,
)
```

**&lt;command line&gt;**
```
$ bazel build -c opt :health_grpc_proto
```

### What did you expect to see?
A successful build.

### What did you see instead?
Due to [line 30 of generate_cc.bzl](https://github.com/grpc/grpc/blob/a6c7b66f75/bazel/generate_cc.bzl#L30)
```
'external/com_google_grpc_proto/grpc/health/v1/health.proto' does not lie within ''
```

This is frustrating because it means that we need to copy grpc's common protos within our project instead of depending on them (which IMHO is much cleaner). Alternative, grpc/grpc does expose build rules for these protos within `src/proto/grpc`. However, depending on these results in the following `#include`

```
#include "src/proto/grpc/health/v1/health.grpc.pb.h"
```

whereas the following would be much cleaner

```
#include "grpc++/proto/health/v1/health.grpc.pb.h"
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by HunterLarco** [comment]
Friendly ping

**Comment by HunterLarco** [comment]
bump~

**Comment by yashykt** [comment]
Hey @nicolasnoble are you working on this? If not, we should mark this as disposition/help wanted
