### ISSUE TITLE
PHP MacOS Interceptor Test Flake

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#20845]
```
There was 1 failure:

1) InterceptorTest::testClientChangeRequestInterceptor
Failed asserting that null is identical to 'intercepted_stream_request'.

/Volumes/BuildData/tmpfs/src/github/grpc/workspace_php_macos_dbg_native/src/php/tests/unit_tests/InterceptorTest.php:365

FAILURES!
Tests: 132, Assertions: 311, Failures: 1.
```

https://source.cloud.google.com/results/invocations/4875df59-bc5c-4915-ab99-13486c5e523f/log

**Comment by stanley-cheung** [comment]
This seems to be not happening recently.

**Comment by markdroth** [comment]
I just saw this again:

https://source.cloud.google.com/results/invocations/8ee7aaf5-de17-4850-982d-1ee87a753cea/targets/github%2Fgrpc%2Frun_tests%2Fphp7_macos_opt_native%2Fsrc%2Fphp%2Fbin%2Frun_tests.sh/tests
