### ISSUE TITLE
Local credentials fail on Windows (win_get_fd always returns -1)

### ISSUE THREAD

**Issue by manzaltu** [grpc/grpc#20855]
### What version of gRPC and what language are you using?
v1.24.3 (Bug exists also on master), C++

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS 2017

### What did you do?
I used grpc_impl::experimental::LocalCredentails and LocalServerCredentials in a client and a server I wrote for Windows. 

### What did you expect to see?
The client executes an RPC command successfully on the server.

### What did you see instead?
The server and the client reject each other. Status error returned from the stub == 14.

During debugging, I found that win_get_fd implementation (src/core/lib/iomgr/tcp_windows.cc) always returns -1. This led to the failure of local_check_peer (src/core/lib/security/security_connector/local/local_security_connector.cc) to get the fd socket name. Because of that, local credentials are not working under Windows.

I opened a PR that solves this issue by fixing win_get_fd to return the correct socket fd https://github.com/grpc/grpc/pull/20857

**Comment by lidizheng** [comment]
A friendly ping.

**Comment by drfloob** [comment]
I think this is obsolete, since the local security connector no longer relies on FDs. See https://github.com/grpc/grpc/pull/26290.

@manzaltu if you are still invested in this, please confirm it's fixed without any further changes. Otherwise, I'll let this issue close as fixed.
