### ISSUE TITLE
SSL handshake failed due to WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Juniortheone** [grpc/grpc#20858]
What version of gRPC and Python version are you using:
gRPC - grpcio (1.24.1)
Python - 2.7

What operating system:
Linux 16.04
What did you do?

I turned up logging by setting the environment variables to
`GRPC_VERBOSITY=DEBUG and GRPC_TRACE=all` 

What did you expect to see?
I expected to see a successful connection

What did you see instead?
```
E1030 04:14:03.945278288    4707 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E1030 04:14:03.956440173    4713 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
 `#I cropped out this part relating to my code `
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1572408843.945502370","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1572408843.945477127","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
```

**Comment by stanley-cheung** [comment]
We need more information to proceed. How is your server set up? What's the client code? What kind of environment - running in a VM? local machine? docker?  Anything that can help us reproduce this issue will be appreciated.

**Comment by Juniortheone** [comment]
I'm running in Vagrant
Below is the section that involves the client and server
[issue.txt](https://github.com/grpc/grpc/files/3792202/issue.txt)
Thank you.

**Comment by anbali** [comment]
I`ve got the same problem :(

**Comment by lidizheng** [comment]
@Juniortheone This is a certificate related issue that maybe the cert setup is not entirely correct.
`Handshake failed...OPENSSL_internal:WRONG_VERSION_NUMBER`

Can you give more information about how you generate your certificate?

**Comment by Juniortheone** [comment]
@lidizheng I used this command to generate the certificate
`openssl req \
       -newkey rsa:2048 -nodes -keyout domain.key \
       -x509 -days 365 -out domain.crt`

**Comment by lidizheng** [comment]
The generation looks fine. Can you investigate more to confirm if this is specific to Python? E.g. try to use these certs with Golang client or C++ client?
