### ISSUE TITLE
Channel state doesn't update upon server disconnection

### ISSUE THREAD

**Issue by mihalios** [grpc/grpc#20861]
### What version of gRPC and what language are you using?
2.24.0
C# .NET CORE 2.2

### What operating system (Linux, Windows,...) and version?
Linux (version not known at the moment)

### What did you do?
I have a service deployed in Kubernetes that exposes a gRPC server in Envoy.
Another service is acting as the gRPC client and establishes a connection to the server and starts to stream data (server streaming).

The client service polls the gRPC channel state and when this changes from Ready to anything else, it assumes the connection is dropped and tries to re-connect.

When I manually delete the server pod, on the client side the stream is closed but the channel's state remains as Ready.

Performing exactly the same actions locally (running both services in Debug mode via Visual Studio instances), results in the channel state changing immediately from Ready to Idle and my client service attempting to reconnect.

### What did you expect to see?
When the gRPC server is stopped I expect the channel to go instantly in a !Ready state. I appreciate that I may have an incorrect understanding of the lifetime of a Channel. But it is peculiar that the behaviour locally is different to that in Kubernetes.

### What did you see instead?
The state did not change immediately, and finally timed-out after the default 30 minutes elapsed.

I raised the issue previously with Istio (https://github.com/istio/istio/issues/18436) but I realise now it might not necessarily be related to that.

**Comment by yashykt** [comment]
I'll assign this to @jtattermusch for further questioning, but I have an initial question on whether there is an active stream or keepalive pings enabled on the server. If there isn't any traffic active between the two endpoints, a client might not realize that the channel is down.

**Comment by mihalios** [comment]
Thanks @yashykt. What you’re saying is accurate, once the stream is closed there’s no traffic between the two endpoints. 

So I’d like to stress the fact that the behaviour differs between debugging locally and running on K8s. That’s what made me open this issue.

**Comment by mihalios** [comment]
Thinking more about this, it might be the case that the Client Idle timeout is different on the Kubernetes than on my Windows machine.

One way to overcome the issue would be to set it in-code to a known value, 1 second would satisfy my requirement. However, from what I can tell client_idle_timeout_ms is not an available Channel Option in the C# implementation (https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/ChannelOptions.cs).

**Comment by jtattermusch** [comment]
@mihalios  I'd recommend trying to send keepalives on your connection.
A hint how to setup keepalive in C# (you basically set one or more of the keepalive related channel options).
https://stackoverflow.com/questions/45257255/set-keepalive-for-grpc-in-c-sharp-client

**Comment by mihalios** [comment]
Thanks @jtattermusch , I can give that a shot.

Although, looking at the source the option you mentioned doesn't look like it's available https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/ChannelOptions.cs

**Comment by jtattermusch** [comment]
Just use the string name of the channel arg. The lack of a defined string constant is not a problem.
https://github.com/grpc/grpc/blob/40955d2cb4d8f73a4c87df0052921eb28c090277/include/grpc/impl/codegen/grpc_types.h#L227

**Comment by mihalios** [comment]
@jtattermusch How does the client know that the transport is disconnected (because the keepalive check failed)? So far I've been using .WaitForStateChangedAsync(ChannelState.Ready) and that seems fairly reliable.

Assuming a server is already running, Channel.ConnectAsync() will succeed. Is there a callback or any other way to detect a disconnection if I don't have any RPC calls taking place?

**Comment by jtattermusch** [comment]
@mihalios `WaitForStateChangedAsync(ChannelState.Ready)` is the way if you don't have any in-flight RPCs. Be sure to set https://github.com/grpc/grpc/blob/40955d2cb4d8f73a4c87df0052921eb28c090277/include/grpc/impl/codegen/grpc_types.h#L234 if you want the connection survive even without RPCs.

**Comment by jtattermusch** [comment]
Did setting keepalives solve the problem?

**Comment by mihalios** [comment]
@jtattermusch and how can I set keepalive settings on the server side?

**Comment by jtattermusch** [comment]
If you want, you can set keepalive on the server as well (use the same ChannelOption and pass it to the server when creating it).
https://github.com/grpc/grpc/blob/bad1b352a1a5d508965296e1090789fc89f28244/src/csharp/Grpc.Core/Server.cs#L68

**Comment by mihalios** [comment]
I set the following, hoping the transport would disconnect but it didn't:

CLIENT:
keepalive_time_ms= 5000, send keepalives every 5 seconds
keepalive_timeout_ms = 5000, await up to 1 seconds for an ACK
keepalive_permit_without_calls = 1, as I don't have any live RPCs

SERVER:
keepalive_permit_without_calls = 0, so that the transport is disconnected

**Comment by jtattermusch** [comment]
I don't think that's how it works
keepalive_permit_without_calls = 0 means that server won't send it's own pings if there are no RPCs, it doesn't mean it won't respond to clients ping requests if requested to do so.
The client sending keepalives (and getting ping  reponses from server) is enough to keep the connection alive.
Under the hood the keeaplives are just HTTP/2 keepalive, so you can read up the details about how they work.

**Comment by mihalios** [comment]
Ok thanks @jtattermusch. I was trying to think of a way of testing the grpc keepalives locally (debugging server and client). I know that if the server is stopped (e.g. manually by stopping the service) the client handles that fine but I haven't verified the keepalive logic.

I need a way to have the Channel be Ready but no keep-alives sent to the Client. It doesn't sound trivial, does it?

**Comment by yashykt** [comment]
Hi @mihalios,
A lot of the information on keepalive is already published on https://github.com/grpc/grpc/blob/master/doc/keepalive.md

I think what you are looking for is a misbehaving client which sends many pings. One way to do that would be to create a HTTP/2 connection to the server and sending many pings. If you want the gRPC client to send those misbehaving pings, you would need to change some of the other channel args described in the doc.

Also, the nature of the issue seems to be a question that should be rerouted to our wider communities. Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
