### ISSUE TITLE
A hotspot function "sched_getcpu" in ARM server when running c++ benchmarking code.

### ISSUE THREAD

**Issue by wudiX** [grpc/grpc#20876]
### What version of gRPC and what language are you using?
v1.25.0-pre1

### What operating system (Linux, Windows,...) and version?
linux 4.19.36 (arm64)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.3.0

### What did you do?
I run the benchmarking code following guide in 'tools/run_tests/performance/README.md'. A c++ server 'qps_worker' is ran on a ARM server. The scenario of "cpp_protobuf_async_streaming_qps_unconstrained_secure" is applied in benchmark test. However, a hotspot called "sched_getcpu" is found in "perf report", while this hotspot accounts for a small proportion of x86 server. It is called by "gpr_cpu_current_cpu" in "src/core/lib/gpr/cpu_linux.cc".
![image](https://user-images.githubusercontent.com/24285372/67758863-6db3d680-fa79-11e9-859b-2dd3dea8b8d7.png)

As I return 0 as bellow (just like it is done in musl-libc), the performance is improved significantly. 
![image](https://user-images.githubusercontent.com/24285372/67909487-5a5c5480-fbba-11e9-9b20-b3ae22d404c3.png)

I wonder how "sched_getcpu" works what role does the obtained CPU play in the gRPC life cycles?
Can it be handle like this (return 0)?
### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
sched_cpu() is used for a bit of stat-keeping. I would expect there to be a few gains there. The core issue seems to be that it will be called each time ExecCtx is created, even if starting_cpu() is not needed. 

starting_cpu() is what ends up calling sched_cpu

#22314 lazily initializes starting_cpu_
