### ISSUE TITLE
C core should verify gzipped messages are correctly terminated

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#20889]
.Gzip has a footer containing an adler32 (think CRC32). grpc-dotnet recently introduced a bug where this was missing (https://github.com/grpc/grpc/issues/20884). However, the C++ client did not fail. The gzip decoder should have failed noticing the checksum was missing/invalid.

(https://github.com/grpc/grpc-go/issues/3135 is the equivalent of this issue for Go.)

**Comment by ejona86** [comment]
In https://github.com/grpc/grpc-go/issues/3135#issuecomment-549432661 we discovered that Go had the compression tests disabled. Looking at other languages, it seems most of them have disabled compression tests in one way or another. C++ has them enabled, so there still seems the implementation is not verifying the gzip trailer. But it also appears we need to enable compression tests on more implementations.

**Comment by yashykt** [comment]
Interesting, this shouldn't have happened since internally gRPC Core uses zlib for compression/decompression

**Comment by ejona86** [comment]
You have to check for FINISHED result at the end for decompressing.

**Comment by yashykt** [comment]
Ah I see, that makes sense. I spot it. We should be checking for Z_STREAM_END at the end.

**Comment by yashykt** [comment]
I checked again and I was about to change the implementation, and I noticed that grpc_msg_decompress actually does the right thing, and it is only treated as a success if the return value is 1 (Z_STREAM_END)

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/blob/f2839869ff3fa7c46beac9a237ff20088202f94a/test/core/compression/message_compress_test.cc#L169 we also have a test which corrupts the output and makes sure that grpc_msg_decompress fails

**Comment by yashykt** [comment]
I think it's possible that the interop test succeeded for a different reason, possibly that the C++ interop client is not really set up to check for corrupt messages. 

I am just guessing that maybe a payload of nul characters somehow ended up avoiding the issue?

https://github.com/grpc/grpc/blob/f2839869ff3fa7c46beac9a237ff20088202f94a/test/cpp/interop/interop_client.cc#L181

**Comment by ejona86** [comment]
Corruption is neither here nor there.

It doesn't matter if grpc_msg_decompress checks the return code if zlib_decompress doesn't:

https://github.com/grpc/grpc/blob/b531a04dc29e0bb4e84dc072baf191cc8ba4cd4d/src/core/lib/compression/message_compress.cc#L135-L136

**Comment by yashykt** [comment]
After talking @ejona86 , 
What I saw was just smashing the CRC and the decompression failed as expected then.

next steps - 
1) Remove the CRC instead of smashing it and see if there's a bug there.
2) Try removing any finish frame from the code and see if we can expose a bug there

**Comment by yashykt** [comment]
Doh! Removing the gzip trailer instead of smashing it reproduced the issue. Don't know what I was thinking. I should have just followed the original instructions. #22929 fixes it for Core.
