### ISSUE TITLE
Using address sanitizer (ASAN) changes the definition of gpr_mu

### ISSUE THREAD

**Issue by tudor** [grpc/grpc#20887]
### What version of gRPC and what language are you using?

1.24.2, C++

### What operating system (Linux, Windows,...) and version?

Linux x86-64, Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7.4

### What did you do?

I'm trying to build my own code with `-fsanitize=address` *without also building GRPC with ASAN*. (GRPC is not built in-tree; it's built as shared libraries as a dependency for our project).

This used to work, but it doesn't any more. I traced this to the fact that GRPC now changes the definition of the mutex structure (`gpr_mu`) when using ASAN: https://github.com/grpc/grpc/blob/85e22ef28d55f27e8efb3d5e2e43ca6f59971065/include/grpc/impl/codegen/sync_posix.h#L28

So, our code is compiled with ASAN, so, while included from our code, `sync_posix.h` has `GRPC_ASAN_ENABLED`, so `gpr_mu` contains the `leak_checker` member.

But GRPC itself was not compiled with ASAN, so, in object files inside the GRPC shared library, `gpr_mu` doesn't contain the `leak_checker` member.

This of course leads to memory corruptions everywhere.

### What did you expect to see?

Building a project that uses GRPC with ASAN should work even when GRPC itself is built without ASAN.

### What did you see instead?

Memory corruptions due to mismatched structure definitions.

**Comment by tudor** [comment]
One possible avenue for a fix would be to define `GRPC_ASAN_ENABLED` if **GRPC itself** was compiled with ASAN, and then persist it in some `features.h`-style file.

**Comment by hcaseyal** [comment]
@tudor gRPC does not officially support the use case you're describing. There shouldn't be a downside to building gRPC with asan since gRPC is committed to fixing any asan issues. Is there a particular reason you don't want to build gRPC itself with asan in this case?

**Comment by tudor** [comment]
In our case, gRPC is *not* built in-tree (like a Bazel build would do).

For us, gRPC is just another shared library that's installed on the system. We do builds in Docker, and we have a "base image" that's based on Ubuntu 18.04 + a bunch of other libraries that we build from source, including gRPC; we rebuild this base image weekly or whenever we update the version of some dependent library.

This means that we don't want to rebuild gRPC whenever we rebuild our code. (Just like we don't rebuild any of the other libraries, ranging from libstdc++ to gRPC and other dependencies).

All other libraries that we've seen work fine if you build your code with ASAN but link against a library that's not built with ASAN; gRPC seems to be the only offender.

**Comment by hcaseyal** [comment]
@nicolasnoble

**Comment by aurelienrb** [comment]
FYI I've just been bitten by this same issue and lost an entire day spotting the reason why : https://github.com/grpc/grpc/issues/21838

the scenario is quite simple:
- build grpc normally (since you don't event know it has a special mode for ASAN)
- build your code normally
- run it happily for a while
- later on build your code with ASAN to check if everything is fine, and :boom:

**Comment by coryan** [comment]
I think this is a duplicate of #19224

**Comment by yashykt** [comment]
Closing in favor of #19224
