### ISSUE TITLE
Two consistently calls causes error - Received RST_STREAM with error code 2

### ISSUE THREAD

**Issue by slavabulgakov** [grpc/grpc#20883]
### What version of gRPC and what language are you using?
gRPC: 1.24.2
I use Objective-C gRPC library from Swift 5.0 code

Server was written on grpc-go v1.19.0

### What operating system (Linux, Windows,...) and version?
iOS 12.2

### What did you do?
I have a class which conforms to `GRPCProtoResponseHandler` protocol and it has a method `foo` which creates two services and calls one method from each service:
```swift
class MyClass: NSObject, GRPCProtoResponseHandler {
    var dispatchQueue: DispatchQueue {
        return .main
    }
    
    func foo() {
        let callOptions = GRPCMutableCallOptions()
        callOptions.initialMetadata = ["authorization": "Bearer eyJhbGciO..."]
        
        featureService = FeatureTogglingService(host: "example.com:443", callOptions: callOptions)
        userService = UserService(host: "example.com:443", callOptions: callOptions)
        
        let userCall = userService?.sendOnlineStatus(withMessage: userRequest, responseHandler: self, callOptions: nil)
        let featureCall = featureService?.getFeaturesWithMessage(featureTogglingRequest, responseHandler: self, callOptions: nil)
        featureCall?.start()
        userCall?.start()
    }
    
    func didReceiveProtoMessage(_ message: GPBMessage?) {
    }
    
    func didClose(withTrailingMetadata trailingMetadata: [AnyHashable : Any]?, error: Error?) {
        print("🛑🛑🛑 error: \(error)")
    }
}
```
I call `foo` method.

### What did you expect to see?
I expected to see two callings back the method `func didClose(withTrailingMetadata trailingMetadata: [AnyHashable : Any]?, error: Error?)` with `error == nil`

### What did you see instead?
I see two callings back the method `func didClose(withTrailingMetadata trailingMetadata: [AnyHashable : Any]?, error: Error?)` where `error` contains:
```
🛑🛑🛑 error: Optional(Error Domain=io.grpc Code=13 "{"created":"@1572546519.322425000","description":"Error received from peer ipv4:...:443","file":".../Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}" UserInfo={io.grpc.HeadersKey={
    date = "Thu, 31 Oct 2019 18:28:39 GMT";
    server = nginx;
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1572546519.322425000","description":"Error received from peer ipv4:...:443","file":".../Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}, NSLocalizedDescription=Received RST_STREAM with error code 2})
🛑🛑🛑 error: Optional(Error Domain=io.grpc Code=13 "{"created":"@1572546519.322339000","description":"Error received from peer ipv4:...:443","file":".../Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}" UserInfo={io.grpc.HeadersKey={
    date = "Thu, 31 Oct 2019 18:28:39 GMT";
    server = nginx;
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1572546519.322339000","description":"Error received from peer ipv4:...:443","file":".../Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}, NSLocalizedDescription=Received RST_STREAM with error code 2})
```
But in server logs I see that every call went ok because response status 200. That's why I think there is a problem on client side in gRPC Objective-C library.

### Anything else we should know about your project / environment?
My protos:
```proto
syntax = "proto3";
package ...;

message Response {
    ServiceStatus status = 1;
}

message ResultStatus {
    Status status = 1;
}

enum Status {
    OK = 0;
    ...
}
```

```proto
syntax = "proto3";
package ...;

message Feature {
    string name = 1;
    bool is_enabled = 2;
    int64 valid_until = 3;
}

message QueryFeatures {
}

message ResultFeature {
    common.ResultStatus status = 1;
    repeated Feature features = 2;
    reserved 3;
}

service FeatureTogglingService {
    rpc GetFeatures(QueryFeatures) returns (ResultFeature);
}
```

```proto
syntax = "proto3";
package ...;

message CommandSendOnlineStatus {

}

service UserService {
    rpc SendOnlineStatus(CommandSendOnlineStatus) returns (Response);
}
```

**Comment by muxi** [comment]
The error message does indicate that a RST_STREAM from the server was received, maybe unexpectedly in your context. I don't see an indication of bug in gRPC ObjC library. For gRPC messages, the server always respond 200 status code, even with an error. gRPC status code is sent over to the client in the HTTP/2 trailer. I think the main issue here is why the server issued an RST_STREAM.

**Comment by slavabulgakov** [comment]
@muxi Could you explain what means RST_STREAM? What cases does server should send RST_STREAM ordinarily? I need that information to speak with backend developers to define and point servers side bug.

**Comment by muxi** [comment]
It's the `RST_STREAM` frame in [HTTP/2](https://tools.ietf.org/html/rfc7540#page-36) that gRPC uses. Usually it means the server decides that a call (stream) is terminated on the server side due to some error. See some of the details [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#user-content-http2-transport-mapping).

**Comment by slavabulgakov** [comment]
@muxi We defined the issue - it is located inside backend. When a grpc response is going from Ambassador to Nginx with error message `upstream sent frame for closed stream 1 while reading response header from upstream ` a grpc client receive an error which described above. Therefore I close that issue. Thank you a lot!

**Comment by muxi** [comment]
Thanks for the update @slavabulgakov
