### ISSUE TITLE
[ruby] Can't provide list of interrupt strings with frozen_string_literals enabled

### ISSUE THREAD

**Issue by jewilmeer** [grpc/grpc#20897]
### What version of gRPC and what language are you using?
1.24

### What operating system (Linux, Windows,...) and version?
Linux & osX

### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby 2.6

### What did you do?
```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'grpc'

server = GRPC::RpcServer.new()
server.add_http2_port('0.0.0.0:80', :this_port_is_insecure)
GRPC.logger.info "Server started"
server.run_till_terminated_or_interrupted(%w[EXIT INT QUIT KILL])
GRPC.logger.info "Server terminated"
```

### What did you expect to see?

A running server, that would terminate without segmentation faults when receiving on the provided interrupt signals

### What did you see instead?

While running the server I received this in the logs;

```
grpc-7bf5cdf9dc-pclw9 grpc FrozenError: can't modify frozen String
grpc-7bf5cdf9dc-pclw9 grpc   /usr/local/bundle/gems/grpc-1.24.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:395:in `upcase!'
grpc-7bf5cdf9dc-pclw9 grpc   /usr/local/bundle/gems/grpc-1.24.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:395:in `block in run_till_terminated_or_interrupted'
grpc-7bf5cdf9dc-pclw9 grpc   /usr/local/bundle/gems/grpc-1.24.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:392:in `each'
grpc-7bf5cdf9dc-pclw9 grpc   /usr/local/bundle/gems/grpc-1.24.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:392:in `run_till_terminated_or_interrupted'
grpc-7bf5cdf9dc-pclw9 grpc   /app/config/grpc_server.rb:34:in `<top (required)>'
```

The error is triggered by this code snippet: https://github.com/grpc/grpc/blob/398be272878825ede60a5b32c4f98a865ff62ec4/src/ruby/lib/grpc/generic/rpc_server.rb#L395

If you follow the code snippet, you'll see the code tries to upcase the string in place, which is forbidden when enabling frozen string literals. Enabling this has become the default in our codebase, and for what I know isn't a strange default to have.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

Our application is running in kubernetes, so we rely on signals to terminate our application. This is why we've chosen to use `run_till_terminated_or_interrupted` instead of the default `run_till_terminated`

**Comment by sheim-dev** [comment]
Two PRs, both #20867 and the considerably simpler #21740, provide fixes for this issue.

It is a well established best practice to run Ruby with frozen string literals by now - gRPC would benefit from staying compatible with the respective implementation language's paradigms / established best practices as far as painlessly possible.

Can we get this reviewed, merged, and ultimately included in an upcoming release please?

**Comment by suever** [comment]
This is still an issue and #21740 provides the necessary fix

**Comment by apolcyn** [comment]
sorry, this was merged yesterday: https://github.com/grpc/grpc/pull/20867, which I believe obsoletes #21740

**Comment by suever** [comment]
@apolcyn Yup looks like that will do it thanks!
