### ISSUE TITLE
Let people assign a credentials object once to the stub, and not worry about them anymore.

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2089]
To let people just write `call.accessToken = token`.
Similarly, a readonly string property `grpc_authChallenge` can be added to `NSError`.

**Comment by jcanizales** [comment]
Let's also track in this issue implementing a way to let people assign credentials to a `ProtoService` object once and not having to worry about them anymore.

**Comment by jcanizales** [comment]
@jayantkolhe I have this almost ready ([diff here](https://github.com/grpc/grpc/compare/master...jcanizales:ease-async-access-tokens?expand=1)), but it ended up being exclusively additive to the API, not breaking. So it can be finished and merged after Beta.

**Comment by makdharma** [comment]
@jcanizales I see that this work is already done in some form, i.e. creds are specified per host not per RPC. OK to close this bug?

**Comment by jcanizales** [comment]
No, that's different; those credentials are for people that want to modify the SSL handshake. This issue is intended for people making RPCs with OAuth2. In the current state, the access token needs to be set on all RPCs made, which is a pain because you almost never want to change it.

**Comment by jcanizales** [comment]
@hsaliak this is one of the biggest pain points of the library. Why close it?

**Comment by hsaliak** [comment]
I think that's an accident. We bulk closed the "to close" label. If you see the history, we prioritized this for 1.1 but the to close label was already applied from June, hence it got caught in that list. 

Thanks for flagging - issue reopened.

**Comment by muxi** [comment]
Got more user request of this feature. Let us put this on schedule.

**Comment by muxi** [comment]
Please give #11832 a try.

**Comment by pbatg** [comment]
It would be more convenient to have a method to set the token provider (GRPCAuthorizationProtocol) on GRPCProtoService, rather than GRPCCall.  Otherwise, the application needs to remember to configure every GRPCCall return by the stub, which is more error-prone than setting it once when the service is initialized.
