### ISSUE TITLE
Streaming request in python : when reconnecting always one request object is not sent

### ISSUE THREAD

**Issue by space88man** [grpc/grpc#20896]
### What version of gRPC and what language are you using?
1.24.3 Python

### What operating system (Linux, Windows,...) and version?
Linux , Fedora 31, 

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.4

### What did you do?
1. Create bidirectional streaming proto based on HelloWorld
2. Run server
3. Run client: generate a request every five seconds. Process a few messages...
4. Ctrl+C the server
5. Client will throw exception and rebuild a new channel and *Stub (the previous channel is closed) and attempt to reconnect
6. Restart the server
7. RPC continues...

### What did you expect to see?
All requests are processed, no messages missed

### What did you see instead?
On the client size, during cleanup and before the construction of the new channel and *Stub object, one request is extracted from the message generator. This is not processed as the channel is closed.

Somehow the thread that extracts from the generator always survives its matching *Stub by exactly one more item.

Reproducer: https://github.com/space88man/grpc-stream-bug

**Comment by space88man** [comment]
Proto file:
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (stream HelloRequest) returns (stream HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
  int64 id = 2;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
  int64 id = 2;
}
```

**Comment by space88man** [comment]
Server:
```
from concurrent import futures
import time
import grpc
from .HelloWorld_pb2_grpc import GreeterServicer, add_GreeterServicer_to_server
from .HelloWorld_pb2 import HelloReply


class ServiceImpl(GreeterServicer):
    def SayHello(self, request_iterator, context):
        for request in request_iterator:
            yield HelloReply(message=request.name.upper(), id=request.id)


def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))
    server.add_insecure_port("127.0.0.1:7000")
    add_GreeterServicer_to_server(ServiceImpl(), server)
    server.start()
    print(">>>> Greeter service is started")
    while True:
        time.sleep(60)


if __name__ == "__main__":
    serve()
            
```

**Comment by space88man** [comment]
Client:
```
from queue import Queue
from concurrent import futures
import time
import random
import functools
import threading

import grpc
from .HelloWorld_pb2_grpc import GreeterStub
from .HelloWorld_pb2 import HelloRequest


def continuous_sender(itr):
    try:
        chan = grpc.insecure_channel("127.0.0.1:7000")
        fut = grpc.channel_ready_future(chan)

        while not fut.done():
            print("channel is not ready")
            time.sleep(1)

        stub = GreeterStub(chan)

        for result in stub.SayHello(itr):
            print("Result:", result.id, result.message)
    except Exception as exc:
        print(exc)
    chan.close()


def request_iterator(queue):
    datum = queue.get()
    print("Extracted:", datum[0])
    return(datum[1])


def message_generator(queue):
    count = 0
    while True:
        time.sleep(5)
        datum = HelloRequest(id=count, name="".join(random.choices("abcdefghikjlmnopqrstuvwxyz", k=16)))
        print(f"Generating {count}:", datum)
        queue.put((count, datum))
        count += 1


if __name__ == "__main__":
    queue = Queue()
    worker = threading.Thread(target=message_generator, args=(queue,))
    worker.start()

    while True:
        continuous_sender(
            iter(functools.partial(request_iterator, queue), None)
        )
        print("Reconnecting...")
        time.sleep(2)
```

**Comment by space88man** [comment]
Sample session:
```
channel is not ready
Generating 0: name: "leiqxtufkasexbkg"

Extracted: 0
Result: 0 LEIQXTUFKASEXBKG
Generating 1: name: "zdkytqtwgehpirvg"
id: 1

Extracted: 1
Result: 1 ZDKYTQTWGEHPIRVG
Generating 2: name: "rvcxbfhehiqarewn"                                                                                                                      
id: 2                       
                                                                              
Extracted: 2                                                                  
Result: 2 RVCXBFHEHIQAREWN
Generating 3: name: "vslfwrkgwhotsgmt"                                                                                                                      
id: 3                             
                                                                              
Extracted: 3      
Result: 3 VSLFWRKGWHOTSGMT
Generating 4: name: "joiyvwyvgsmjsozu"
id: 4

Extracted: 4
Result: 4 JOIYVWYVGSMJSOZU
Generating 5: name: "jyoixipqpocgkeno"
id: 5

Extracted: 5
Result: 5 JYOIXIPQPOCGKENO
<_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1572616177.013099158","description":"Error received from peer ipv4:127.0.0.1:7000","file":"src/core/lib/surface/c
all.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"
>
Reconnecting...
Generating 6: name: "chhcvcclpjhxiakh"
id: 6

Extracted: 6
channel is not ready
channel is not ready
channel is not ready
channel is not ready
Generating 7: name: "plpxwzitfevuwnbj"
id: 7

channel is not ready
channel is not ready
channel is not ready
channel is not ready
channel is not ready
Generating 8: name: "zllrawcuwmbvwmer"
id: 8

channel is not ready
Extracted: 7
Extracted: 8
Result: 7 PLPXWZITFEVUWNBJ
Result: 8 ZLLRAWCUWMBVWMER
Generating 9: name: "dekqgzafaphlsbfd"
id: 9

Extracted: 9
Result: 9 DEKQGZAFAPHLSBFD
```

**Comment by gnossen** [comment]
@space88man Thanks for the detailed write-up. The behavior is exactly as you've described. But this is actually working as intended.

A message being pulled from the request iterator does not necessarily guarantee that it will be observed by the server. One of the guarantees of gRPC is that all messages in a given RPC will be sent to the *same* server. In a situation where the connection is severed, we cannot guarantee that the server before the severance and after the severance are the same, and so we cannot simply send buffered messages.

Suppose we did just buffer messages pulled from the request iterator and send them to a server with which we've reestablished contact. This new server may have no context for the buffered messages, since it did not observe the messages that preceded them.

For the echoed count situation you've laid out here, I would recommend one of two options.

1. If you require a strict ordering between the client's observation of messages and the server's observation of messages, you could simply use a unary-unary RPC. This will trivially guarantee that no messages are dropped.

2. If you *don't* require a strict ordering between the client's observation of messages and the server's observation of messages, you could augment your current stream-stream protocol with additional coordination between the client and the server. When establishing/re-establishing a connection the client can query the server for its most recently observed message. The client can then begin its stream from there.

**Comment by space88man** [comment]
@gnossen Thanks for the wonderfully educational explanation! I am closing this as a result.
