### ISSUE TITLE
Does anyone compile grpc C++ with dockerfile(https://hub.docker.com/r/grpc/cxx/dockerfile) success? 

### ISSUE THREAD

**Issue by qingtiandalaoye** [grpc/grpc#20911]
### What version of gRPC and what language are you using?

1.21.3 version , current master version
### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

boringssl always compile error 

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

1 ) create a Dockerfile
2) copy and paste the contents from https://hub.docker.com/r/grpc/cxx/dockerfile
3) run comand :
docker build -t grpc-devel:1.0 .
4) wait for the error message

### What did you expect to see?
pass the grpc C++ compile.

### What did you see instead?
compile error ...
did anyone compile boringssl success? I have tried about 20 times in 6 months recently on 1.23.X grpcor master( continus commit days)master version, but not success.

I tried the https://hub.docker.com/r/grpc/cxx/dockerfile , it has compiles error too.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
What is the output of the failed build?

**Comment by jtattermusch** [comment]
Btw the dockerfile is pinned at gRPC 1.10.x version of gRPC (which is very old).

**Comment by qingtiandalaoye** [comment]
but it is the offical grpc/cxx, isn't it?  

the error log :

third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/fipsmodule/rand/urandom_test.cc.o
In file included from /root/grpc/third_party/boringssl/third_party/googletest/include/gtest/gtest.h:375,
from /root/grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc:15:
/root/grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc: In function 'void GetTrace(std::vector*, unsigned int, std::function<void()>)':
/root/grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc:179:23: error: 'PTRACE_O_EXITKILL' was not declared in this scope
PTRACE_O_EXITKILL | PTRACE_O_TRACESYSGOOD))
^~~~~~~~~~~~~~~~~

.................
make[2]: *** [third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/fipsmodule/rand/urandom_test.cc.o] Error 1
make[1]: *** [third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by jtattermusch** [comment]
@qingtiandalaoye  images from that repo are no longer being updated so it might be they are just broken (sorry, we are working on a better solution). I advise against using them. See https://github.com/grpc/grpc-docker-library/pull/71.

**Comment by qingtiandalaoye** [comment]
sorry, could you please explain me to use what ? 
https://github.com/grpc/grpc-docker-library/pull/71   is just a message:
"Add info that images in this repo are out of date "
