### ISSUE TITLE
Can't build C++ helloworld example

### ISSUE THREAD

**Issue by damien-lloyd** [grpc/grpc#20914]
### What version of gRPC and what language are you using?

C++; latest version of gRPC

### What operating system (Linux, Windows,...) and version?
Linux (64-bit)

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++

### What did you do?
```
$ cd grpc/examples/cpp/helloworld
$ make
```

### What did you expect to see?
I expected a clean build so I can run the server/client

### What did you see instead?
```
protoc -I ../../protos --cpp_out=. ../../protos/helloworld.proto
g++ -std=c++11 `pkg-config --cflags protobuf grpc`  -c -o helloworld.pb.o helloworld.pb.cc
Package grpc was not found in the pkg-config search path.
Perhaps you should add the directory containing `grpc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'grpc', required by 'virtual:world', not found
protoc -I ../../protos --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ../../protos/helloworld.proto
g++ -std=c++11 `pkg-config --cflags protobuf grpc`  -c -o helloworld.grpc.pb.o helloworld.grpc.pb.cc
Package grpc was not found in the pkg-config search path.
Perhaps you should add the directory containing `grpc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'grpc', required by 'virtual:world', not found
g++ -std=c++11 `pkg-config --cflags protobuf grpc`  -c -o greeter_client.o greeter_client.cc
Package grpc was not found in the pkg-config search path.
Perhaps you should add the directory containing `grpc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'grpc', required by 'virtual:world', not found
g++ helloworld.pb.o helloworld.grpc.pb.o greeter_client.o -L/usr/local/lib `pkg-config --libs protobuf grpc++` -pthread -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -o greeter_client
Package grpc++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `grpc++.pc'
to the PKG_CONFIG_PATH environment variable
Package 'grpc++', required by 'virtual:world', not found
/usr/bin/ld: helloworld.pb.o: undefined reference to symbol '_ZTIN6google8protobuf7MessageE'
/usr/bin/ld: /usr/lib/libprotobuf.so.18: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:44: greeter_client] Error 1
```

**Comment by nicolasnoble** [comment]
It looks like you didn't build and install grpc. Please do that first.

**Comment by sheenaqotj** [comment]
Please try Nico's suggestion.

**Comment by jtattermusch** [comment]
Instructions are here: https://github.com/grpc/grpc/tree/master/src/cpp#to-start-using-grpc-c

**Comment by damien-lloyd** [comment]
@nicolasnoble @sheenaqotj @jtattermusch Hello you three! I have followed the instructions prior to creating this issue. Thus, gRPC and thirdparty/protocol_buffers were installed through `make` which I then proceeded to install through `sudo make install`. Despite a second attempt, this linking issue still persists. The main issue seems to be with `/usr/bin/ld: helloworld.pb.o: undefined reference to symbol '_ZTIN6google8protobuf7MessageE'` which is implying I don't have a dependency installed or perhaps the example's build file is not adding the correct locations.

**Comment by jtattermusch** [comment]
@damien-lloyd  I'd recommend using cmake instead of make (the long term plan is for make installation support to be removed in favor of cmake).

Here are some examples for cmake: https://github.com/grpc/grpc/tree/master/src/cpp#cmake

Btw the installation scripts here: 
https://github.com/grpc/grpc/tree/master/test/distrib/cpp are being continously tested (and they are passing), so perhaps you can take a look at them and see if you've done something wrong.
