### ISSUE TITLE
[FLAKE] ios-test-interoptests

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20921]
Basic Tests ObjC iOS 

https://source.cloud.google.com/results/invocations/7aece7cf-eb3a-4232-9777-7f62a1237597/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-test-interoptests/tests
```
Failing tests:
	-[InteropTestsLocalCleartext testCancelAfterFirstResponseRPC]
	-[InteropTestsLocalCleartext testCancelAfterFirstResponseRPCWithV2API]
** TEST FAILED **
```

**Comment by jtattermusch** [comment]
dupe of https://github.com/grpc/grpc/issues/20751
