### ISSUE TITLE
[QUESTION] How to make grpc transport and serialize datas faster?

### ISSUE THREAD

**Issue by fishpenguin** [grpc/grpc#20920]
I change my data type from repeated int64 to bytes in .proto files, but it is still cost much more time than thrift in transport and serialize time, almost 3 times slower.
What can I do to improve my transporting and serializing performance?

**Comment by gnossen** [comment]
@fishpenguin What languages are you using on the client and server?

**Comment by gnossen** [comment]
@fishpenguin Can you please provide any more details about your setup? Any code samples or particular functions that you think are slow?
