### ISSUE TITLE
[FLAKE] Bazel RBE Windows Opt C/C++

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20922]
test/core/end2end/h2_full+workarounds_test@retry_streaming_succeeds_before_replay_finished.exe
```
exited with error code 1
```
https://source.cloud.google.com/results/invocations/6ce0bca5-d6af-4004-bb21-f9800af194a9/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_full%2Bworkarounds_test@retry_streaming_succeeds_before_replay_finished/tests

**Comment by jtattermusch** [comment]
The actual log is in the "Target log" tab:

```
Executing tests from //test/core/end2end:h2_full+workarounds_test@retry_streaming_succeeds_before_replay_finished
-----------------------------------------------------------------------------
LAUNCHER ERROR: Cannot open the binary to read launch data
LAUNCHER ERROR: Failed to parse launch info.
```

**Comment by yashykt** [comment]
Closing stale issue
