### ISSUE TITLE
Don't use Cocoapods' implementation details in the podspec

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2093]
See: https://github.com/grpc/grpc/blob/master/gRPC.podspec#L34

One way around it is, during installation (`prepare_command`), move all headers under `include/grpc/...` into `grpc/...` (i.e., remove the `include` element from their path).

**Comment by jcanizales** [comment]
(Another way around is if Cocoapods would let us specify explicitly which directories of the repo to include in the headers search path).

**Comment by murgatroid99** [comment]
Why do we need that line in the first place? Without it, includes within the C core still seem to work.

**Comment by jcanizales** [comment]
Maybe it was an issue with a previous version of Cocoapods. (Or maybe you're testing it on a project that was already configured that way in a previous `pod install`, and `pod install` again without that line fails to delete the config?). If we can simply delete the line, by all means let's do it :)
