### ISSUE TITLE
How to look at compression

### ISSUE THREAD

**Issue by yyf1986** [grpc/grpc#20932]
I refer with https://github.com/grpc/grpc/tree/master/examples/python/compression,and my server is running ok.but how to look compression and no compression?

**Comment by gnossen** [comment]
@yyf1986 Can you please clarify what you mean? Are you looking for a method to determine whether a given message is compressed or not on the server side?

**Comment by yyf1986** [comment]
Yes, I'm not sure if it's compressed on the server side

**Comment by gnossen** [comment]
If you're looking for a manual check, you can simply count bytes on the wire. We have a unit test doing that [here](https://github.com/grpc/grpc/blob/ae6b1c9d38deb32fa8c94e8cd49bda957cc914d3/src/python/grpcio_tests/tests/unit/_compression_test.py#L191). You can use a tool like `iftop` to get this information manually.

If you're looking for a server-side API for this, there currently isn't one. What is your use case for it?

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
