### ISSUE TITLE
Create an umbrella header file, and have the .pbrpc.h import it.

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2094]
So users don't have to look up what did they need to import to do something. It'll also help discoverability (through XCode's autocompletion and via command-click navigation). So by writing:

``` objective-c
#import <gRPC/gRPC.h>
```

You'd get at least:

``` objective-c
#import <gRPC/GRPCCall.h>
#import <gRPC/GRPCMethodName.h>
#import <gRPC/GRXBufferedPipe.h>
#import <gRPC/GRXWriteable.h>
#import <gRPC/GRXWriter.h>
#import <gRPC/GRXWriter+Immediate.h>
#import <gRPC/GRXWriter+Transformations.h>
#import <gRPC/ProtoRPC.h>
```

These files, and most of our READMEs, will be simplified:

https://github.com/grpc/grpc/blob/master/src/objective-c/examples/Sample/Sample/ViewController.m#L36
https://github.com/grpc/grpc/blob/master/src/objective-c/tests/LocalClearTextTests.m#L37
https://github.com/grpc/grpc/blob/master/src/objective-c/tests/RxLibraryUnitTests.m#L37
https://github.com/grpc/grpc/blob/master/src/objective-c/tests/LocalClearTextTests.m#L37
https://github.com/grpc/grpc/blob/master/src/objective-c/tests/GRPCClientTests.m#L37
https://github.com/grpc/grpc/blob/master/src/objective-c/tests/InteropTests.m#L39
https://github.com/grpc/grpc-common/blob/master/objective-c/route_guide/ViewControllers.m#L36

**Comment by jcanizales** [comment]
The `<gRPC/gRPC.h>` name _might_ conflict with the core's `grpc/grpc.h`? (Are imports case-sensitive?)

**Comment by jcanizales** [comment]
@jayantkolhe This won't break client applications; it'll just make life easier to the developers who decide to use it.

**Comment by makdharma** [comment]
We are largely happy with current scheme of things. Closing this bug with no action for one year.

**Comment by jcanizales** [comment]
Why not just leave it open as an enhancement? It's both the customary thing to do for ObjC libraries, and easier for users of the library. No action for a year because it's super low priority compared to the other stuff we've done. It's also an ideal candidate for an external contributor that wants to get their feet wet.
