### ISSUE TITLE
Install gRPC Python on linuxkit

### ISSUE THREAD

**Issue by christopheryang90** [grpc/grpc#20964]
**What version of gRPC and what language are you using?**
grpcio-1.25 (trying to install)
pip 19.3.1

**What operating system (Linux, Windows,...) and version?**
Linux a64864bb776d 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 aarch64 GNU/Linux

**What runtime / compiler are you using (e.g. python version or version of gcc)**
python2.7.11

**What did you do?**
```
bash-4.3# pip install grpcio        
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting grpcio
  Downloading https://files.pythonhosted.org/packages/e4/60/40c4d2b61d9e4349bc89445deb8d04cc000b10a63446c42d311e0d21d127/grpcio-1.25.0.tar.gz (15.4MB)
     |################################| 15.4MB 8.6MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w9rk3b/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w9rk3b/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-w9rk3b/grpcio/pip-egg-info
         cwd: /tmp/pip-install-w9rk3b/grpcio/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w9rk3b/grpcio/setup.py", line 190, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-w9rk3b/grpcio/setup.py", line 151, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    OSError: [Errno 2] No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by lidizheng** [comment]
You are using `linuxkit` which might not be `manylinux` compatible, so you can't get pre-compiled wheels from PyPA. I would suggest you either digging into the compilation process, or use other container image.

**Comment by christopheryang90** [comment]
gotcha, regarding compiling grpc myself, could you give me some search keywords that I could start with? I am not familiar with how to install packages without using managers like Pip. 
Thanks!

**Comment by lidizheng** [comment]
I'm not an expert on the minimal image area. I assume you can start by installing linker and compiler `gcc` / `g++` for your image. After that, try to see what the `pip` installation is asking for. You can always use `pip install --no-binary -U grpcio` to explicitly compile the `grpcio` package.

**Comment by yashykt** [comment]
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at
StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc 

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
