### ISSUE TITLE
[php] Log debug info to file rather than stderr

### ISSUE THREAD

**Issue by jdpedrie** [grpc/grpc#20974]
When using the grpc PHP extension with Apache or nginx and the `GRPC_VERBOSITY` and `GRPC_TRACE` environment variables turned up, it can be difficult to obtain debugging output from stderr. As PHP is invoked not directly by the user but by the web server, this information is often not easy to see or find. Some web server and PHP configurations will pipe stderr to the server logfile, and some will not. The means to configure this are not clear or easily explainable.

It would be great to have a configuration option setting a log location which grpc would write to in lieu of writing to stderr.

cc @stanley-cheung

**Comment by stanley-cheung** [comment]
This fix is now included in the `1.26.0` release. Fixed by #20991. Here are the few entries that need to be added to the `php.ini` file to activate this:

```
grpc.grpc_verbosity=debug
grpc.grpc_trace=all,-timer_check
grpc.log_filename=/var/log/grpc.log
```
