### ISSUE TITLE
Question: Do u have example on implementing this on laravel?

### ISSUE THREAD

**Issue by codeitlikemiley** [grpc/grpc#20989]
I wanna know how i can implement this on laravel , php popular framework
but i never seen anyone on the web when i google it...

Anyone can point me to the right directions?

**Comment by stanley-cheung** [comment]
There isn't really anything special about integrating gRPC with Laravel. You have to install the `grpc` extension, and require the `grpc/grpc` composer package. The rest is using our `protoc` code generator plugin to turn your `.proto` service into stub classes that you can then import into your project. The gist of it are all documented in our [main PHP page](https://github.com/grpc/grpc/tree/master/src/php).
