### ISSUE TITLE
Improve layout of the generated code

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2098]
Ideally, generated signatures would have the handler parameter in a second line, with the colons aligned ( https://github.com/grpc/grpc/blob/master/src/compiler/objective_c_generator.cc#L76 ).

There's also a few places where extra newlines are needed.

**Comment by makdharma** [comment]
@jcanizales can you clarify what you need here? (exactly where do you need extra new lines?)

**Comment by jcanizales** [comment]
Yeah that link was to a branch, which obviously drifted over time :) Better link, to a tag: https://github.com/grpc/grpc/blob/release-0_14_1/src/compiler/objective_c_generator.cc#L74

But in general, the generated code has method signatures that are billions of characters long, all in single lines. Pretty hard to inspect. They should be split in the usual ObjC way: one parameter per line, colons aligned.
