### ISSUE TITLE
Question: Python GRPC client, is there a way to create multiple connections with in the same channel?

### ISSUE THREAD

**Issue by songohannyc** [grpc/grpc#20985]
This is for Python implementation. grpc version 1.25.0

Currently, we are using grpc.insecure_channel() to create a channel. From my understanding, a single channel creates a single connection to a single server, am I correct? 

We are hitting istio-proxy max_requests limit of 1024 and just wondering what is the best way to create connection pools for a channel.

I have a hard time locating documentation on all available channel_options that might allow me to create connection pools. Is it possible to do it via channel_options?  Or we have to create multiple grpc's channels and self-managed those channels?

Please advice.

**Comment by lidizheng** [comment]
There are several questions need to be answered here.

> Currently, we are using grpc.insecure_channel() to create a channel. From my understanding, a single channel creates a single connection to a single server, am I correct?

Underlying our Python wrapper, the Channel object uses C-Core's Channel which will reuse existing connections. E.g. if you create 100 channel object to the same destination with same options, there will be only 1 outstanding TCP connection.

> We are hitting istio-proxy max_requests limit of 1024 and just wondering what is the best way to create connection pools for a channel.

I'm not sure about the definition of max_requests limit here. By "requests", does it mean connections or individual HTTP/2 streams (RPC)? Also, who enforces that limit? Is it possible to throttle on the application side?

> Is it possible to do it via channel_options?

Unfortunately, no. The subchannel (TCP connection) pooling is on by default, but it is not tune-able through `channel_options`.

> Or we have to create multiple grpc's channels and self-managed those channels?

@gnossen for ongoing proposal of designing Python level Channel pooling.

**Comment by songohannyc** [comment]
> There are several questions need to be answered here.
> 
> > Currently, we are using grpc.insecure_channel() to create a channel. From my understanding, a single channel creates a single connection to a single server, am I correct?
> 
> Underlying our Python wrapper, the Channel object uses C-Core's Channel which will reuse existing connections. E.g. if you create 100 channel object to the same destination with same options, there will be only 1 outstanding TCP connection.
> 
Thank you very much for the information

> > We are hitting istio-proxy max_requests limit of 1024 and just wondering what is the best way to create connection pools for a channel.
> 
> I'm not sure about the definition of max_requests limit here. By "requests", does it mean connections or individual HTTP/2 streams (RPC)? Also, who enforces that limit? Is it possible to throttle on the application side?
> 

"requests" means number of RPC requests not connections.  The limit of 1024 is number of RPC requests per a single connection. Yes, currently, we are workaround this by throttle on the client application. We are seeking a better way.

> > Is it possible to do it via channel_options?
> 
> Unfortunately, no. The subchannel (TCP connection) pooling is on by default, but it is not tune-able through `channel_options`.

In Golang I see a way to create connection pool https://godoc.org/google.golang.org/api/option#WithGRPCConnectionPool
Is this possible in python? Thank you for your help
> 
> > Or we have to create multiple grpc's channels and self-managed those channels?
> 
> @gnossen for ongoing proposal of designing Python level Channel pooling.

**Comment by lidizheng** [comment]
@songohannyc You are referring to Golang's Google Cloud API library. Equivalently, here is the Python version: https://github.com/googleapis/google-cloud-python. They also have the connection pooling in their layer. For specific usage example, please refer to their documentation.

**Comment by songohannyc** [comment]
Thanks @lidizheng. I did't realize that is google cloud api library. Thought that was GRPC library for a minute. :)

**Comment by lidizheng** [comment]
@songohannyc If there is any new issue related to this topic, feel free to re-open or start a new thread.
