### ISSUE TITLE
Bazel could not find grpc++.h

### ISSUE THREAD

**Issue by linghudaxiao** [grpc/grpc#20995]
### What version of gRPC and what language are you using?
name = "com_github_grpc_grpc"
remote = "https://github.com/grpc/grpc"
commit = "bd0aa9a600a13cc988c6ebfd12deab8d1abcf171"

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
bazel 1.0.1

### What did you do?
Wrote a small grpc test application

in WORSPACE

workspace(name = "grpc_test")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_github_grpc_grpc",
    remote = "https://github.com/grpc/grpc",
    commit = "bd0aa9a600a13cc988c6ebfd12deab8d1abcf171",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()

in hello_world.proto

syntax = "proto3";

package hello_world;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

in hello_world.proto BUILD

package(default_visibility = ["//visibility:public"])

load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")

cc_grpc_library(
    name = "hello_world",
    srcs = [":hello_world.proto"],
    deps = [],
)

in server.cpp

#include <iostream>
#include <memory>
#include <string>

#include <grpc++/grpc++.h>

#include "proto/hello_world.pb.h"
#include "proto/hello_world.grpc.pb.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;
using hello_world::HelloRequest;
using hello_world::HelloReply;
using hello_world::Greeter;
using std::string;

class GreeterServiceImpl final : public Greeter::Service {
  Status SayHello(ServerContext* context, const HelloRequest* request,
                  HelloReply* reply) override {
    string prefix("Hello ");
    reply->set_message(prefix + request->name());
    return Status::OK;
  }
};

void RunServer() {
  std::string server_address("0.0.0.0:10001");
  GreeterServiceImpl service;

  ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  builder.RegisterService(&service);
  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << "Server listening on " << server_address << std::endl;

  server->Wait();
}

int main(int argc, char** argv) {
  RunServer();

  return 0;
}

in server.cpp BUILD

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "server",
    srcs = ["server.cpp"],
    deps = [
        "//proto:hello_world",
    ],
)

### What did you expect to see?
I should be able to run 
 bazel build client:client --sandbox_debug

### What did you see instead?
INFO: Writing tracer profile to '/home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/command.profile.gz'
INFO: Analyzed target //client:client (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/caixuanting/grpc_test/client/BUILD:3:1: C++ compilation of rule '//client:client' failed (Exit 1) linux-sandbox failed: error executing command 
  (cd /home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/sandbox/linux-sandbox/8/execroot/grpc_test && \
  exec env - \
    PATH=/home/caixuanting/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/bin:/home/caixuanting/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/caixuanting/.cache/bazel/_bazel_caixuanting/install/0eaad79e03c843a15f078930a471406a/_embedded_binaries/linux-sandbox -t 15 -w /home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/sandbox/linux-sandbox/8/execroot/grpc_test -w /tmp -w /dev/shm -D -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/client/_objs/client/client.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/client/_objs/client/client.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-fastbuild/bin/external/zlib -iquote external/com_github_grpc_grpc -iquote bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-fastbuild/bin/external/zlib -isystem external/com_github_grpc_grpc/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c client/client.cpp -o bazel-out/k8-fastbuild/bin/client/_objs/client/client.pic.o)
src/main/tools/linux-sandbox.cc:154: linux-sandbox-pid1 has PID 4821
src/main/tools/linux-sandbox-pid1.cc:175: working dir: /home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/sandbox/linux-sandbox/8/execroot/grpc_test
src/main/tools/linux-sandbox-pid1.cc:194: writable: /home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/sandbox/linux-sandbox/8/execroot/grpc_test
src/main/tools/linux-sandbox-pid1.cc:194: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:194: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/lock
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/snapd/ns
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/user/1000
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/unified
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/hugetlb
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/rdma
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/config
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/fuse/connections
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/docker/384
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core/7917
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core/8039
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/lxcfs
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/sandbox/linux-sandbox/8/execroot/grpc_test
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /home/caixuanting/.cache/bazel/_bazel_caixuanting/56e1e1f496eedd6c32ee33d10eb39038/sandbox/linux-sandbox/8/execroot/grpc_test
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /dev/shm
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
client/client.cpp:5:10: fatal error: grpc++/grpc++.h: No such file or directory
 #include <grpc++/grpc++.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
src/main/tools/linux-sandbox-pid1.cc:437: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:457: child exited with code 1
src/main/tools/linux-sandbox.cc:204: child exited normally with exitcode 1
Target //client:client failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.559s, Critical Path: 0.09s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

It seems -isystem external/com_github_grpc_grpc/include
and the IDE could find <grpc++/grpc++.h>

What is wrong here?

Thanks a lot!

**Comment by nicolasnoble** [comment]
This header name has been deprecated because XCode doesn't like non-ascii characters. If using the Makefile this header still exists, but for Bazel, one needs to use the new one called `grpcpp/grpcpp.h`

**Comment by linghudaxiao** [comment]
Hi nicolasnoble 

 I also tried grpcpp/grcpp.h

It has the same problem.

Thanks a lot.

**Comment by linghudaxiao** [comment]
Seems the include path is configured:

-isystem external/com_github_grpc_grpc/include

**Comment by mgyong** [comment]
@linghudaxiao Has the problem been solved? If yes, how did you solve it? I was having the same problem when using #include 'grpcpp/grcpp.h'

**Comment by linghudaxiao** [comment]
No, it is not solved. 

Nobody gave the answer yet.

Thanks.

**Comment by linghudaxiao** [comment]
Anyone could help?

**Comment by linghudaxiao** [comment]
So I did some test.

By including "@com_github_grpc_grpc//:include/grpcpp/grpcpp.h", bazel could find grpcpp.h. However, it could not find header files inside grpcpp.h. That means I need recursively include all header file path. 

I think this is a bug in grpc repository. The include path is not properly set.

Not sure how to fix that.

Thanks.

**Comment by linghudaxiao** [comment]
Finally someone gives the answer.

I need add  "@com_github_grpc_grpc//:grpc++" in deps.

So stupid mistake

**Comment by yashykt** [comment]
It seems like this has been resolved.

Also, This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at
StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc 

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
