### ISSUE TITLE
gRPC PHP extension prevents pcntl_waitpid() to return PID

### ISSUE THREAD

**Issue by simPod** [grpc/grpc#20994]
### What version of gRPC and what language are you using?

PHP 7.3, grpc 1.25

### What operating system (Linux, Windows,...) and version?

macOS Catalina

### What runtime / compiler are you using (e.g. python version or version of gcc)

php

### What did you do?

```php
<?php
declare(strict_types=1);
$childProcs = [];
for ($batch = 0; $batch < 1; $batch++) {
    $pid = pcntl_fork();
    if ($pid === -1) {
        throw new RuntimeException('Failed to create child process');
    }
    if ($pid !== 0) {
        $childProcs[] = [
            'pid' => $pid,
        ];
    } else {
        echo 'Exiting child';
        echo PHP_EOL;
        exit(0);
    }
}
while (count($childProcs) > 0) {
    foreach ($childProcs as $key => $procData) {
        $res = pcntl_waitpid($procData['pid'], $status, WNOHANG);
        if ($res === $procData['pid']) {
            unset($childProcs[$key]);
            echo 'unset child ' . $key;
            echo PHP_EOL;
        }
    }
}
```

### What did you expect to see?

echoed `unset child 0`

### What did you see instead?

The script loops infinitelly as `pcntl_waitpid` does not return PID.

### Anything else we should know about your project / environment?

When gRPC extension is not enabled `pcntl_waitpid()` returns child's PID on child exit.

**Comment by stanley-cheung** [comment]
Fork support was not by default enabled. You need to add the following lines to your php.ini file.

```
grpc.enable_fork_support = 1
grpc.poll_strategy = epoll1
```

See #18539

**Comment by simPod** [comment]
@stanley-cheung thanks, I'll try to set it. 

Isn't there any way to notify the consumer of this extension, that ext-pnctl gets broken by it? I installed the extension as it was required by some 3rd party project but had no idea it can break function of another extension. Took some time to discover this extension was the cause...
