### ISSUE TITLE
How to define an uncertain type?

### ISSUE THREAD

**Issue by hscspring** [grpc/grpc#20992]
Like the title, I have a dict as input, the keys are strings, but values are not certain. for example, 
some like 
```python
{"age": 24, "sex": "male"}
```

some other may like
```python
{"age": 24, "cost": 100.2}
```

I want to define a prop, like:

message Input {
    map<string, ?(here use what)> props = 1;
}

**Comment by lidizheng** [comment]
Please ask ProtoBuf question in https://github.com/protocolbuffers/protobuf.

This type of usage is not recommended, but some times it is the only option. You may want to try [`protobuf.Any`](https://developers.google.com/protocol-buffers/docs/proto3#any).

**Comment by hscspring** [comment]
Thanks for the reply.

I used serialization to the input,:)
