### ISSUE TITLE
[C++]Why don't you implement "void RepeatedField<Element>::Add(Iter begin, Iter end)"

### ISSUE THREAD

**Issue by fishpenguin** [grpc/grpc#21019]
"void RepeatedField<Element>::Add(Iter begin, Iter end)" is very friendly for C++ performance, Why grpc just provide "void RepeatedField<Element>::Add()"?

**Comment by hcaseyal** [comment]
@fishpenguin You're talking about protobuf, right? Where does it say that gRPC doesn't support "void RepeatedField::Add(Iter begin, Iter end)"?

**Comment by fishpenguin** [comment]
> @fishpenguin You're talking about protobuf, right? Where does it say that gRPC doesn't support "void RepeatedField::Add(Iter begin, Iter end)"?

Yes, it's my fault, I'm talking about protobuf. However I still hope that you can solve my question.

**Comment by nicolasnoble** [comment]
That's for protobuf, not for us. Please file an issue at https://github.com/protocolbuffers/protobuf.

**Comment by hcaseyal** [comment]
@fishpenguin Can you please provide some more context? What issue did you run into and how? Please refer to the issue template for how to give context on issues.

gRPC doesn't do anything to alter protobuf's behavior, so as long as protobuf provides the feature, gRPC will have it. Protobuf seems to provide the API you're looking for (see https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/repeated_field.h#L154), so I'm not sure why you're saying it's unimplemented.
