### ISSUE TITLE
Make grpc-packages@google.com owner of the podspecs

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2101]
I guess both gRPC's and Protobuf's? We can ask proto team if they prefer another alias.

Cocoapods has a way to add additional owners, or reclaim full ownership, of existing pods.

**Comment by murgatroid99** [comment]
I'm not sure about Protobuf. I don't think we own any of their other packages.

**Comment by jcanizales** [comment]
Well, right my account owns their podspec, so we have to clarify with them what do they prefer :)

**Comment by hsaliak** [comment]
@muxi this would be good to verify and get done.
