### ISSUE TITLE
Remove const cast warning in GRPCSecureChannel.m

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2103]
By deleting [this `const`](https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/private/GRPCSecureChannel.m#L41). Then turn [warnings in the GRPCClient library](https://github.com/grpc/grpc/blob/master/gRPC.podspec#L77) back on.

@jboeuf @ctiller or @nicolasnoble : Is the non-constness of the `grpc_credentials` argument to [`grpc_secure_channel_create`](https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L148) on purpose?

**Comment by ctiller** [comment]
Yes it's deliberate. We mutate internal state stored in that object.
