### ISSUE TITLE
cmake "configure" step on Windows 10 takes way too long (~7mins)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21060]
I've noticed that the "configure" step in our windows cmake build is extremely slow (~7mins)

My observations:
- on Windows 7, the configure step takes a reasonable amount of time (much shorter), only on Windows 10 (and newer?) it takes extremely long
- on linux and macos the configure step is very quick (~ seconds)

The command we run looks very normal:
`cmake -G "Visual Studio 14 2015" -A %ARCHITECTURE% -DgRPC_BUILD_TESTS=OFF -DgRPC_MSVC_STATIC_RUNTIME=ON ../../..`

examples where we use it:
https://github.com/grpc/grpc/blob/0605a977c88af6dc4d3ab308dd8b7cbb5aec9ea6/tools/run_tests/helper_scripts/pre_build_csharp.bat#L31
https://github.com/grpc/grpc/blob/0605a977c88af6dc4d3ab308dd8b7cbb5aec9ea6/tools/run_tests/helper_scripts/pre_build_cmake.bat#L27

On stackoverflow I found this:
https://developercommunity.visualstudio.com/content/problem/162361/cmake-configuration-is-unbearably-slow.html

The pre_build_csharp took 434.5secs in my local build
```
$ python tools/run_tests/run_tests.py -l csharp -c dbg --build_only                                                                                                                                              
2019-11-12 10:37:50,055 START: tools\run_tests\helper_scripts\pre_build_csharp.bat                                                                                                                               
2019-11-12 10:45:04,562 PASSED: tools\run_tests\helper_scripts\pre_build_csharp.bat [time=434.5sec, retries=0:0]                                                                                                 
2019-11-12 10:45:04,565 START: cmake                                                                                                                                                                             
2019-11-12 10:53:27,068 PASSED: cmake [time=502.5sec, retries=0:0]                                                                                                                                               
2019-11-12 10:53:27,071 START: tools\run_tests\helper_scripts\build_csharp.bat                                                                                                                                   
2019-11-12 10:53:57,391 PASSED: tools\run_tests\helper_scripts\build_csharp.bat [time=30.3sec, retries=0:0]                                                                                                      
2019-11-12 10:53:57,394 SUCCESS: All tests passed 
```

**Comment by jtattermusch** [comment]
@KyleFromKitware  @zackgalbreath   can you take a look? This is most likely some problem with cmake on windows. Suggestions are welcome.

**Comment by KyleFromKitware** [comment]
Thanks @jtattermusch. I tried configuring with the Visual Studio generator, and it took about 3 minutes (though not the 7 minutes that it took for you.) It took a little less time with the Ninja generator and a Visual Studio compiler (about 1-2 minutes) and even less with Ninja + MinGW (under a minute.) None of them are blazing fast like on Linux, though.

**Comment by KyleFromKitware** [comment]
Visual Studio only: 3:14
Ninja + Visual Studio: 1:34
Ninja + MinGW: 1:02

**Comment by jtattermusch** [comment]
@KyleFromKitware   random thought: I am consistently seeing higher latencies on my machine (it's a laptop) but I'm also able to reproduce higher latencies on our CI (8core windows VMs). Is there some parameter that influences the duration observed (such as the number of VS versions installed on the machine or so)?

Zack has suggested trying with the latest version of cmake as well, just to see if there are any optimizations we could make use of.

**Comment by KyleFromKitware** [comment]
> Is there some parameter that influences the duration observed (such as the number of VS versions installed on the machine or so)?

I don't think the number of installed VS versions would matter, as CMake is only using one. However, I spoke to @mathstuf offline, and he mentioned that the Visual Studio generator will inherently take longer to configure because every `try_compile()` invocation generates four configurations instead of one (this is probably why Ninja runs so much faster.) He recommended trying to cut out as many `try_compile()`s as we can to avoid unnecessary overhead in the configure step.

**Comment by mathstuf** [comment]
Well, VS generators will take 4 times as long to *generate*. `try_compile` has a generate step, so that is being paid for there too.

[This MR](https://gitlab.kitware.com/cmake/cmake/merge_requests/2760) can be used to get *configure* time performance metrics. It outputs a JSON file that browser debuggers know how to render.

**Comment by KyleFromKitware** [comment]
With CMake 3.16.0-rc3:

Visual Studio only: 2:33
Ninja + Visual Studio: 0:56
Ninja + MinGW: 0:45

Definitely a little better, though still not super fast.

**Comment by KyleFromKitware** [comment]
> `try_compile` has a generate step, so that is being paid for there too.

Right, so if your configure step has a lot of `try_compile()`s (which gRPC does) then your configure step will take longer. (I realize that it's technically the *generate* step that's taking longer within the `try_compile()`, but from a user point of view, gRPC is taking a long time to configure because of it.)

**Comment by KyleFromKitware** [comment]
> This MR can be used to get *configure* time performance metrics. It outputs a JSON file that browser debuggers know how to render.

A quick run with that profiler confirms that we're spending the vast majority of our time in `try_compile()`, with `try_run()` being a distant second.

Interestingly, about 75% of the *entire* configure step is spent in `third_party/cares/cares`. I bet if we built against an external c-ares, the configure time wouldn't be nearly as long (though the same build on Linux still doesn't have this problem, even with all the `try_compile()`s.)

**Comment by mathstuf** [comment]
> Interestingly, about 75% of the entire configure step is spent in third_party/cares/cares

Indeed. I see about 200 or so `try_compile` calls here: <https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/CMakeLists.txt#L134>. Working with upstream to remove the absolutely unnecessary calls first would be best (search to see if the preprocessor define for each is actually used). Next, things like "assume `windows.h` exists `#if _WIN32`" logic can be applied to trim down the rest.

**Comment by jtattermusch** [comment]
Is there any good explanation why on Win 7 the cmake configure step is significantly faster?
```
2019-11-13 05:05:21,750 START: tools\run_tests\helper_scripts\pre_build_csharp.bat
2019-11-13 05:07:02,828 PASSED: tools\run_tests\helper_scripts\pre_build_csharp.bat [time=101.1sec, retries=0:0; cpu_cost=0.0; estimated=1.0]
```

**Comment by mathstuf** [comment]
Knowing whether it is in the configure or generate phase would be useful. What's the relative time for a reconfigure (which shouldn't have any `try_compile` runs)?

**Comment by mathstuf** [comment]
This is probably still relevant. How is one supposed to interpret a closed "help wanted" issue?

The last activity was asking for numbers.

**Comment by jtattermusch** [comment]
Yes it is still relevant but we won't be able to spend any time on it in foreseeable future. Help wanted label is there because we'd be happy to accept help if someone knew the solution.

**Comment by mathstuf** [comment]
But it being closed sends the wrong message… At least it does to me. I don't search closed issues for things to work on other projects at least.

**Comment by walkthetalk** [comment]
what is the current state??

**Comment by StefanBattmer** [comment]
Just stumbled on this issue, since this is bugging me as well for quite some time. Right now I am working with CMake 3.23.2 and I just wanted to ask if there is still any activity no this topic. I am not even complaining that everything runs slightly slower on Windows for whatever reason, but I think there is at least some mystery here as well. There always seems a period when nothing seems to happen and most of the time is actually spent there:
```
// lots of stuff going on here with decent performance and various messages, then
1>-- Configuring done
// nothing seems to happen here but at least a minute is spent until the next message is generated
1>-- Generating done
```

So can anyone shed some light on what is happening between these last 2 messages?

**Comment by mathstuf** [comment]
CMake is taking the abstract target build graph that the CMake described and turning it into the actual instructions for the actual generator. Things that can take a long time here:

- complex build graph
- complex usage requirements (i.e., deep graph, lots of generator expressions)
- large build files (e.g., lots of flags, long command lines)

For Visual Studio builds, you pay the above for each configuration in `CMAKE_CONFIGURATION_TYPES`. It may pay off to remove `MinSizeRel` or other unused configurations from the default list if "no one" cares about it. A [performance trace](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-profiling-output) would help a lot here.

**Comment by StefanBattmer** [comment]
Dear Ben,

thanks for the hints. I learned quite some new, interesting stuff about CMake and its profiling capabilities from that. However I have to admit, that Windows Defender and the way it is configured on our systems seems to be the guilty one here. Whenever CMake writes back a massive amount of files to the build directory I see the MsMpEng.exe process taking time and as soon as this is done the actual build in Visual Studio starts. So from what I see, CMake has nothing to do with that behaviour. I just wanted to provide this as feedback that might be helpful for others and will try to get the Windows Defender set up differently now.

Thanks again!
