### ISSUE TITLE
[PHP] provide enum mapping from value to key in addition to from key to value

### ISSUE THREAD

**Issue by lauren** [grpc/grpc#21081]
### Is your feature request related to a problem? Please describe.
If I define an enum like this in a proto file:

```proto
enum Animals {
  CATS = 0;
  DOGS = 1;
}
```

When I generate code in Go I end up with mappings from the key to the value and from the value to the key like this:

```go
var Animals_name = map[int32]string{
    0: "CATS",
    1: "DOGS",
}

var Animals_value = map[string]int32{
    "CATS": 0,
    "DOGS":  1,
}
```

But when I generate code in PHP, I only get mappings from the key to the value and not the other way around:
```php
class Animals
{
    /**
     * Generated from protobuf enum <code>CATS = 0;</code>
     */
    const CATS = 0;
    /**
     * Generated from protobuf enum <code>DOGS = 1;</code>
     */
    const DOGS = 1;
}
```

### Describe the solution you'd like
I'd like to be able to get the key from the value as well, like I can in Go.

Something like this would work:
```php
class Animals
{
    const VALUES = [
        "CATS" => 0,
        "DOGS" => 1,
    ];

    const NAMES = [
        0 => "CATS",
        1 => "DOGS",
    ];
}
```
### Describe alternatives you've considered
The only alternative is for me to create something like the "values" mapping manually, which will quickly get out of date.

### Additional context
Add any other context about the feature request here.

**Comment by stanley-cheung** [comment]
I have logged an issue https://github.com/protocolbuffers/protobuf/issues/6875 to the protobuf team to track this.

**Comment by yashykt** [comment]
Sounds like a protobuf feature request that is being tracked accordingly
