### ISSUE TITLE
Convert Unicode characters in metadata to ASCII

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2110]
There are three places in `NSDictionary+GRPC.m` where we need to prevent sending non-ASCII chars to the C core library. We shouldn't _escape_ the characters, as there's no guarantee the server expect us to. Plus, if someone really really wishes to send unicode, they can use a binary header (for metadata keys they're out of luck).

We can either drop the characters or the whole header, raise an exception, or do [this transformation](http://stackoverflow.com/a/2591182/3642676) (which sounds like the nicest thing to do).

**Comment by jcanizales** [comment]
For Beta, we might want to call [`canBeConvertedToEncoding:`](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/#//apple_ref/occ/instm/NSString/canBeConvertedToEncoding:) and throw if not, so that later on we can choose another behavior without breaking code.

**Comment by murgatroid99** [comment]
The other languages just validate that the string content consists of allowable characters, or lets the C core do it for them. That's all I'm going to do here. In the future, we can broaden the set of allowed characters by doing this conversion.
