### ISSUE TITLE
We should test our clients against misbehaving servers, and vice versa

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2112]
The behavior of a server shouldn't make a client application crash (or occupy resources indefinitely, or leak them), and vice versa.

Obviously, this is true for Java and Go too.

**Comment by ctiller** [comment]
Pre-1.0, but not for Beta

**Comment by carl-mastrangelo** [comment]
I have almost all the infra to start adding test cases quickly in https://github.com/grpc/grpc/pull/3991

**Comment by hsaliak** [comment]
@carl-mastrangelo whats the status here? Is this something still targeted for GA?

**Comment by carl-mastrangelo** [comment]
@hsaliak On hold, per jkolhe.

**Comment by ctiller** [comment]
Continuous fuzzing for clients and servers is in place.
