### ISSUE TITLE
Repeatedly getting Security handshake failed

### ISSUE THREAD

**Issue by moodya** [grpc/grpc#21139]
D1112 12:26:06.109187 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1573561566.109000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1573561566.109000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}

D1112 12:26:06.110134 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\server\chttp2_server.cc:123: Handshaking failed: {"created":"@1573561566.109000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1573561566.109000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}

We have hosted a .net grpc sevrer in an azure container.

<PackageReference Include="Google.Api.Gax.Grpc" Version="2.7.0" />
<PackageReference Include="Google.Protobuf" Version="3.8.0" />
<PackageReference Include="Grpc" Version="1.22.0" />
<PackageReference Include="Grpc.Core" Version="1.22.0" />
<PackageReference Include="Grpc.Tools" Version="1.22.0" PrivateAssets="All" />

We have set it up to use ssl. In terms of being able to connect to the server everything works fine, and a third party has confirmed this. However when I switch on DEBUG logging we our repeatedly getting the above. What does this mean?

**Comment by moodya** [comment]
If you need more information please let me know?

**Comment by yashykt** [comment]
Hi, This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at
StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc 

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
