### ISSUE TITLE
Servers should return UNIMPLEMENTED for non-existent methods

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2115]
The test server at grpc-test.sandbox.google.com currently returns `NOT_FOUND`.

In general, `UNIMPLEMENTED` is better for this case because it signals the client that such a call shouldn't be made (nor retried). Except for rare use cases, it's a bug in the client. `NOT_FOUND`, instead, can be the result of a perfectly good call, like "`GetBook`" using a book ID that was deleted in the server. The server state can be modified (say, with someone else calling "`InsertBook`") to render the call successful if it were retried.

**Comment by ctiller** [comment]
This seems worth finding someone to address before beta. Thoughts @a11r?

**Comment by a11r** [comment]
I agree. Will work on a fix.

**Comment by a11r** [comment]
This has now been fixed in the corresponding server impl.
