### ISSUE TITLE
ActiveSupport notifications for Ruby on Rails

### ISSUE THREAD

**Issue by danielmbarlow** [grpc/grpc#21164]
I looked for a specific Ruby repository to see if I should post this there, but didn't find one.

### Is your feature request related to a problem? Please describe.
We need see how much time our Ruby on Rails application is taking on gRPC requests. In particular we're using the [GoogleAds](https://github.com/googleads/google-ads-ruby) gem.

### Describe the solution you'd like
I would like to be able to configure gRPC to provide ActiveSupport notifications like we get from the Excon HTTP library. Please [see their documentation](https://github.com/excon/excon#instrumentation) about that functionality. We found it very easy to use.

### Describe alternatives you've considered
* I looked to see if [InterceptorRegistry](https://github.com/grpc/grpc/blob/v1.25.0/src/ruby/lib/grpc/generic/interceptor_registry.rb) was available to callers, but it's internal to gRPC.
* I also checked our main interest in gRPC tracing: the GoogleAdsRuby gem. It [implements interceptors](https://github.com/googleads/google-ads-ruby/blob/d0e0465/lib/google/ads/google_ads/logging_interceptor.rb). However it doesn't make the interceptor API public or provide ActiveSupport notifications

**Comment by houstonheat** [comment]
Same here, I am also interested in this.

**Comment by danielmbarlow** [comment]
We wanted active support notifications because that would enable tracing in OpenCensus. In the end I don't think we really got a solution. However we are moving to OpenTelemetry. I haven't looked into it much, but there is an unfinished PR to implement gRpc instrumentation using OpenTelemetry:

https://github.com/open-telemetry/opentelemetry-ruby/pull/854
