### ISSUE TITLE
All MacOS and iOS tests are failing

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#21198]
```
Collecting python
  ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is the error we see

**Comment by jtattermusch** [comment]
Failure link e.g.: https://source.cloud.google.com/results/invocations/afb1de94-4992-4aa5-9cc7-7c11d0f9001d/log (same problem for all macos builds).

```
+ source tools/internal_ci/helper_scripts/prepare_build_macos_rc
++ launchctl limit maxfiles
	maxfiles    500000         500000
++ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 500000
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2500
virtual memory          (kbytes, -v) unlimited
++ pip install google-api-python-client oauth2client --user python
Requirement already satisfied: google-api-python-client in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.7.9)
Requirement already satisfied: oauth2client in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (4.1.3)
Collecting python
  ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is a problem in the prepare script that fails when running
`pip install google-api-python-client oauth2client --user python`
https://github.com/grpc/grpc/blob/abdf47084aaeee483b698a82bf0beb643cce30e9/tools/internal_ci/helper_scripts/prepare_build_macos_rc#L23

Possible rootcause it that a new version of google-api-python-client has been pushed (and it's failing to install on our kokoro macs).

**Comment by jtattermusch** [comment]
Ok, this is due to kokoro macos workers being updated to Mojave
https://groups.google.com/a/google.com/g/kokoro-users/c/Px9_LAlw9Vk

**Comment by nicolasnoble** [comment]
Even after rolling back to High Sierra, there are still some failures:

https://source.cloud.google.com/results/invocations/78677922-7d06-4347-8103-7bb8084b3a8d/targets/grpc%2Fnode%2Fpull_request%2Fmacos/log

**Comment by jtattermusch** [comment]
@nicolasnoble  I only updated jobs for grpc/grpc,  you should be able to do the same for grpc-node if needed (but it would be better if you could make the node tests work with macos mojave - because we'll need to to that anyway sooner or later).
