### ISSUE TITLE
Any API to Client side close grpc channel? C++

### ISSUE THREAD

**Issue by ramarkandasamy** [grpc/grpc#21201]
### What version of gRPC and what language are you using?
1.20.0dev

### What operating system (Linux, Windows,...) and version?
linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
Want to close the gRPC connection

### What did you see instead?
Close gRPC connection and tears of TCP sockets

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment]
When an instance of `Channel` is destroyed, it will close the internal gRPC channel.
