### ISSUE TITLE
cancel call fails to kick CQ under epoll1

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#21227]
communication for internal issue b/144444259

User reported all threads blocked on C++ CQ dtor waiting for the pending rpc's to finish. The pending rpcs were cancelled previously. The user is using epoll1.

**Comment by yang-g** [comment]
Copied from internal bug, further questions I have:


1. If the bug is not hard to reproduce, can you try to use poll rather than epoll1 as the polling engine by setting environment variable GRPC_POLL_STRATEGY=poll for their binary. This might help us narrow down the problem to polling engine.
2. It does not seem to make sense that all the threads are blocked on the cv, as I would imagine some thread should do a epoll_wait under CQ::Next. Are there other threads driving the CQs? Is it possible to share all the stack traces via "bt thread apply all"?
3. It sounds like the total alive CQ count is way larger than the total number of threads. Is that right?

**Comment by eoghanoh1** [comment]
> If the bug is not hard to reproduce, can you try to use poll rather than epoll1 as the polling engine by setting environment variable GRPC_POLL_STRATEGY=poll for their binary. This might help us narrow down the problem to polling engine.

It is reproducible under load but it is intermittent so I am unsure how long it will take to reproduce. We had issues in the setting environment variables for GRPC to read in the past. I am not sure I will be able to try this without making changes to the GRPC code. 

> It does not seem to make sense that all the threads are blocked on the cv, as I would imagine some thread should do a epoll_wait under CQ::Next. 

I don't understand exactly what you are saying here. What is the criteria for the CQ::Next code hitting the epoll_wait function? 

> Are there other threads driving the CQs? 

In this load test there are 16 threads driving the completion queues. All these threads are blocked at the time of the issue. One completion queue should only be interacted with by a single thread. A thread could be processing multiple completion queues at the same time though.

> Is it possible to share all the stack traces via "bt thread apply all"?

I will attach the stack traces for all threads to the Google support case. All the 16 processing threads that are blocked are in the same call stack - I have previously confirmed this.

> 3. It sounds like the total alive CQ count is way larger than the total number of threads. Is that right?

Yes that is correct. The number of completion queues depends on the load test rate. Information on this was provided in the Google support case. The number of processing threads is pretty static for an environment (16 in this case).

**Comment by yang-g** [comment]
Thanks for the reply.
I am not sure about your build process but it might be useful to either use the env var or alter the code to try poll to see whether it can repro the problem.

Regarding 2, the epoll1 works with all CQs sharing the same set of fds, and one of the CQ/thread should be doing epoll to listen for any event on the fds (in this case the two client channel fds). That is why I wanted to ask whether there is any thread waiting on epoll. 

This is going to be hard to debug as we do not have a reliable repro, but I will look at the stack traces to see whether anything can be inferred. Thanks.

**Comment by yang-g** [comment]
Hey we are in this meeting, are you going to join? @eoghanoh1

**Comment by yashykt** [comment]
This sounds very much like the problem that is being solved by https://github.com/grpc/proposal/blob/master/A18-tcp-user-timeout.md

It is possible that something is wrong with the network and we are still waiting for some bytes to go out. In some systems, the defaults are such that the socket does not close for 15 minutes, and this is some scenarios ends up blocking gRPC calls even if deadlines are set. Refer https://github.com/grpc/grpc/issues/15889 for a similar problem.

https://github.com/grpc/grpc/blob/master/doc/keepalive.md talks about how to set keepalives.

**Comment by yashykt** [comment]
```
  grpc::ChannelArguments channel_args;
  channel_args.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 60*1000 /* 1 minute */);
  channel_args.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 20*1000 /* 20 seconds */);
  auto channel = grpc::CreateCustomChannel(target, creds, channel_args);
```

**Comment by eoghanoh1** [comment]
Hi,

As you specified in the support case, the kernel version does not support TCP_USER_TIMEOUT. As you suggested the tcp_retries2 configuration change was made from default of 15 to 6. This did seem to improve the length of time that the deadlock or issues were occurring for.

On the latest load test (4+ days), we noticed ~5 occurrences of the issue - for the most recent occurrence there were platform traces captured including some GRPC tracing. 

Below is a timeline of information in the traces when the issues occurs;

1. There seems to be a slow down of WRITE's within GRPC (t=0). 
2. Deadlines start exceeding on requests (t=8). This is approximately 8 seconds after the slow down of writes - our configured request deadline is 8 seconds.
3. Connection time out in the TCP layer of GRPC (t=24) - this indicates 'Broken Pipe'. All 12 configured GRPC channels indicate this.
4. There is a reconnect of the channels - CLIENT_CONNECT (t=42)

I will attach the platform traces + GRPC traces to the support case - I would appreciate you taking a look. 

Can you explain why the connections were closed and which side closed them?
Can you explain why it took 16-18 seconds from the connections timing out to the new connections being created? Is there a way to make the recovery faster?

Regards,
Eoghan

**Comment by yashykt** [comment]
The corresponding case was closed. 

For others, gRPC has a few channel args to be able to vary connection backoff values - GRPC_ARG_MIN_RECONNECT_BACKOFF_MS, GRPC_ARG_MAX_RECONNECT_BACKOFF_MS and GRPC_ARG_INITIAL_RECONNECT_BACKOFF_MS. These can be changed for faster re-connection attempts.
