### ISSUE TITLE
FLAKE: disappearing_server test case is flaky on multiple platforms

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21221]
Currently this is one of the top test flakes on bazel RBE.
- flaky both on linux and windows (on linux mostly epoll1 is affected)
- flaky across multiple flavors of the same test (h2_http_proxy_nosec_test, h2_proxy_nosec_test, h2_http_proxy_test, h2_spiffe_test, h2_http_proxy_nosec_test)
- because of many flavors of the test are flaky, the flakiness adds up and we see a lot of red

List of recent failures (including test result pages)

Row | job_name | test_target | result | timestamp | build_id | build_url |  
-- | -- | -- | -- | -- | -- | -- | --
1 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg | //test/core/end2end:h2_http_proxy_nosec_test@disappearing_server | FAILED | 2019-11-15 13:42:05.700 UTC | 3446 | https://source.cloud.google.com/results/invocations/805bcb34-73f3-41c7-8c42-a55622281f7d |  
2 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_dbg | //test/core/end2end:h2_http_proxy_nosec_test@disappearing_server@poller=epoll1 | FAILED | 2019-11-15 13:38:17.101 UTC | 3371 | https://source.cloud.google.com/results/invocations/15bf6cb6-2c37-4c11-801d-dbd87b5d95f5 |  
3 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_opt | //test/core/end2end:h2_proxy_nosec_test@disappearing_server | FAILED | 2019-11-15 07:28:30.490 UTC | 682 | https://source.cloud.google.com/results/invocations/ddd22587-6023-4bf8-8d24-9ccbd2aa597b |  
4 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_opt | //test/core/end2end:h2_http_proxy_test@disappearing_server | FAILED | 2019-11-15 05:33:39.107 UTC | 681 | https://source.cloud.google.com/results/invocations/8c7b500f-a22b-4381-8202-a8248be74a07 |  
5 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg | //test/core/end2end:h2_http_proxy_test@disappearing_server | FAILED | 2019-11-15 02:10:40.742 UTC | 3439 | https://source.cloud.google.com/results/invocations/ef247fd7-c4a9-4744-9a9f-d3645ca28614 |  
6 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg | //test/core/end2end:h2_http_proxy_test@disappearing_server | FAILED | 2019-11-14 21:45:41.032 UTC | 3436 | https://source.cloud.google.com/results/invocations/cf64d326-81de-4e2d-b2f6-d43f5061c924 |  
7 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_opt | //test/core/end2end:h2_spiffe_test@disappearing_server@poller=epoll1 | FAILED | 2019-11-14 17:30:08.298 UTC | 3399 | https://source.cloud.google.com/results/invocations/62be841e-5465-49d6-8d3b-50762c23409b |  
8 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg | //test/core/end2end:h2_http_proxy_test@disappearing_server | FAILED | 2019-11-14 15:44:28.141 UTC | 3430 | https://source.cloud.google.com/results/invocations/a90ff3fd-995e-4b2a-9b9c-cf8e89a16fe0 |  
9 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_dbg | //test/core/end2end:h2_http_proxy_test@disappearing_server@poller=epoll1 | FAILED | 2019-11-14 09:37:19.877 UTC | 3352 | https://source.cloud.google.com/results/invocations/0d0000f5-988d-4d59-af3e-cd3af452b8fb |  
10 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_opt | //test/core/end2end:h2_http_proxy_test@disappearing_server@poller=epoll1 | FAILED | 2019-11-14 03:32:58.481 UTC | 3391 | https://source.cloud.google.com/results/invocations/1f56042d-d83f-4000-8c24-66668a0fe952 |  
11 | grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_opt | //test/core/end2end:h2_spiffe_test@disappearing_server@poller=epoll1 | FAILED | 2019-11-14 01:48:28.509 UTC | 3390 | https://source.cloud.google.com/results/invocations/60330434-a6da-4aa7-b607-b1cdd1b238c6 |  
12 | grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_opt | //test/core/end2end:h2_http_proxy_nosec_test@disappearing_server | FAILED | 2019-11-14 01:35:14.916 UTC | 662 | https://source.cloud.google.com/results/invocations/f849adb2-5457-4932-851e-e57e53272e3e |

**Comment by jtattermusch** [comment]
@sheenaqotj  please assign to someone on C-core team to investigate. The test is also flaky on linux, so this shouldn't be hard to debug.

Manual repro on linux:
`bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=opt //test/core/end2end:h2_http_proxy_nosec_test@disappearing_server@poller=epoll1 --runs_per_test=250`

**Comment by lidizheng** [comment]
Currently, test cases under this issue has top flake rates of 5%, 5.26%, 5.56%, 10.53%, 16.67% on master. Escalate to P1.

Statistically, any PR on master has at least 36.63% of chance failing due to this flake.

**Comment by yashykt** [comment]
I was finally able to give this time. I believe I know what is happening here.

This test makes sure that in-flight requests are completed before the server shuts down.
1) Client sends a request.
2) Before the request is completed, the server starts shutting down.
3) The request is completed.
4) The server shuts down.

After this,
5) The server is recreated.
6) Client sends a second request.
7) Before the request is completed, the server starts shutting down.
8) The request is completed.
9) The server shuts down.

In the failure mode, what happens is, before the client detects the server shutdown, it starts the second request which fails because the server has already shutdown. 

This problem worsens when we are using proxies in the middle because it adds to the timing problem.

**Comment by yashykt** [comment]
This issue would also not occur if the C client correctly handled GOAWAY frames. If the client refused to start new requests on connections where a GOAWAY has been received, we would not have this issue.

**Comment by yashykt** [comment]
The fix should remove the flakiness for atleast linux based systems. Verified with 1000 runs of the test with both h2_http_proxy and h2_tls. I think it should work for Windows too, but I'm not 100% sure.
