### ISSUE TITLE
Update embedded copy of protoc to 3.10 in grpc-tools rubygem

### ISSUE THREAD

**Issue by pravi** [grpc/grpc#21226]
### What version of gRPC and what language are you using?
1.25.0

### What operating system (Linux, Windows,...) and version?
GNU/Linux Debian unstable/sid

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.5

### What did you do?
We noticed embedded copy of protoc inside grpc-tools rubygems is still 3.8.0

### What did you expect to see?
It should be updated to latest version of protoc 3.10.1

### What did you see instead?
It was using protoc 3.8.0

### Anything else we should know about your project / environment?
We'd like to use protoc 3.10.1 in debian to build gitaly but it fails with protoc 3.8.0 with following error.

```
> grpc_tools_ruby_protoc --version
libprotoc 3.8.0
-> grpc_tools_ruby_protoc -I ./proto --ruby_out=ruby/proto/gitaly --grpc_out=ruby/proto/gitaly proto/blob.proto proto/cleanup.proto proto/commit.proto proto/conflicts.proto proto/diff.proto proto/hook.proto proto/namespace.proto proto/objectpool.proto proto/operations.proto proto/ref.proto proto/remote.proto proto/repository-service.proto proto/server.proto proto/shared.proto proto/smarthttp.proto proto/ssh.proto proto/wiki.proto
[libprotobuf WARNING google/protobuf/compiler/ruby/ruby_generator.cc:509] Omitting proto2 dependency 'google/protobuf/descriptor.proto' from proto3 output file 'shared_pb.rb' because we don't support proto2 and no proto2 types from that file are being used.
--ruby_out: shared.proto: Extensions are not yet supported for proto2 .proto files.
```

See https://gitlab.com/gitlab-org/gitaly/issues/2164#note_245423255 for context and discussion

**Comment by apolcyn** [comment]
It looks like the reason for this is just that our `protobuf` submodule dependency is a bit old, and hasn't been updated since https://github.com/grpc/grpc/pull/19182

It may be worth an update.

@jtattermusch @nicolasnoble, do you have any extra context here?

**Comment by jtattermusch** [comment]
3.11 release of protobuf will be out soon, we should make sure we'll update to that one (there were some C# issues in 3.9 and 3.10 and we never updated, it should be fine with 3.11)

**Comment by pravi** [comment]
@jtattermusch protobuf 3.11 is now released, I hope we can have a new release soon with this version.

**Comment by mvinicius563** [comment]
+1, I'm currently blocked by this as well.
It would be fantastic if the grpc-tools rubygem could be updated to protobuf 3.11! :)

**Comment by pravi** [comment]
@apolcyn we are blocked on this for updating grpc-tools/protoc in gitlab and debian, it'd be great if this can be fixed soon.

**Comment by jtattermusch** [comment]
We upgraded to protobuf 3.11.2 in https://github.com/grpc/grpc/pull/21590.  Updated protoc will be in the next release of grpc (1.27.x)
