### ISSUE TITLE
invalid urls in grpc

### ISSUE THREAD

**Issue by tanjunchen** [grpc/grpc#21236]
|file|url|
|----|----|
|grpc/examples/cpp/route_guide/README.md |https://grpc.io/docs/tutorials/basic/c.html|
|grpc/src/cpp/README.md  |https://grpc.io/docs/tutorials/basic/c.html|
|grpc/src/php/README.md |https://github.com/grpc/grpc/tree/master/src/node/examples|
|grpc/src/objective-c/README.md |https://github.com/grpc/grpc/tree/master/src/objective-c/tests/GRPCClientTests.m|
|grpc/doc/python/server_reflection.md|https://github.com/grpc/tree/master/examples/python/helloworld|
|grpc/doc/core/epoll-polling-engine.md |https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/ev_epollsig_linux.c|
grpc/doc/compression_cookbook.md |https://github.com/grpc/grpc/blob/master/src/core/lib/compression/compression.c
grpc/.github/ISSUE_TEMPLATE/feature_request.md| https://github.com/grpc/grpc-LANGUAGE/issues/new|
grpc/.github/ISSUE_TEMPLATE/bug_report.md| https://github.com/grpc/grpc-LANGUAGE/issues/new|
grpc/.github/ISSUE_TEMPLATE/cleanup_request.md| https://github.com/grpc/grpc-LANGUAGE/issues/new|

**Comment by sheenaqotj** [comment]
Thanks for identifying these! Any chance you could put together a PR also? :)
