### ISSUE TITLE
Compilation error while doing npm install

### ISSUE THREAD

**Issue by DefJunx** [grpc/grpc#21265]
### What version of gRPC and what language are you using? 
I'm not using gRPC directly, as it's getting installed by running a `npm install` command.

- gRPC version: 1.24.2
- Node version: v12.10.0
- npm version: 6.11.3

### What operating system (Linux, Windows,...) and version?

I'm on FreeBSD version 12.0 .

### What runtime / compiler are you using (e.g. python version or version of gcc)

The package is being compiled with Python, version "2.7.16".

### What did you do?

I've run the command `npm install --production`. This gives me two issues:

- When it tries to download the precompiled binaries, it gives:

```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-freebsd-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.2 and node@12.10.0 (node-v72 ABI, unknown) (falling back to source compile
```

- Since it fails downloading the binaries, it tries to compile but gives the following errors:

```
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:17:
In file included from ../deps/grpc/third_party/cares/cares/ares_setup.h:214:
../deps/grpc/third_party/cares/cares/setup_once.h:113:8: error: redefinition of 'timeval'
struct timeval {
       ^
/usr/include/sys/_timeval.h:49:8: note: previous definition is here
struct timeval {
       ^
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:17:
In file included from ../deps/grpc/third_party/cares/cares/ares_setup.h:214:
../deps/grpc/third_party/cares/cares/setup_once.h:178:3: error: unknown type name 'Error'
  Error Missing_definition_of_macro_sread
  ^
../deps/grpc/third_party/cares/cares/setup_once.h:178:42: error: expected ';' after top level declarator
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:20:
In file included from ../deps/grpc/third_party/cares/cares/ares_private.h:95:
../deps/grpc/third_party/cares/cares/ares_ipv6.h:25:8: error: redefinition of 'sockaddr_in6'
struct sockaddr_in6
       ^
/usr/include/netinet6/in6.h:125:8: note: previous definition is here
struct sockaddr_in6 {
       ^
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:20:
In file included from ../deps/grpc/third_party/cares/cares/ares_private.h:117:
../deps/grpc/third_party/cares/cares/ares_writev.h:26:8: error: redefinition of 'iovec'
struct iovec
       ^
/usr/include/sys/_iovec.h:45:8: note: previous definition is here
struct iovec {
       ^
1 warning and 5 errors generated.
gmake: *** [ares.target.mk:216: Release/obj.target/ares/deps/grpc/third_party/cares/cares/ares__close_sockets.o] Error 1
gmake: Leaving directory '/var/www/node/node_notifiche/node_modules/grpc/build'
```

### What did you expect to see?

I expected the package to compile and the npm packages installation to proceed / complete succesfully.

### What did you see instead?

I've seen the errors reported.

### Anything else we should know about your project / environment?

Nothing much, it's a basic backend which sends push notification to devices written in Typescript + node + expressjs .

**Comment by OiledAmoeba** [comment]
On FreeBSD 12.0 I've managed to compile packages that depend on grpc by specify version 1.21.1 _and_ use gcc7 and node8. 
In bash: `env LINK=gcc7 CC=gcc7 CXX=g++7 LINKXX=g++7 npm install -g grpc@1.21.1 --unsafe-perm` (depend on what are you want to do, you may not have to use `-g --unsafe-perm`)
Then you can install packages that depends on grpc. I didn't figured out how to compile on node 10/12 or gcc8/9. Also grpc-versions greater than 1.21.1 won't compile.
