### ISSUE TITLE
Passing copts to pyx_library

### ISSUE THREAD

**Issue by mehrdadn** [grpc/grpc#21269]
Hi, this is a trivial change, I just wanted to ask if, inside `bazel/cython_library.bzl`, you can add a `copts=` parameter to `pyx_library` which gets passed through to `cc_binary`? Currently there's no way to pass compiler flags for Cython libraries. Thank you.

**Comment by gnossen** [comment]
@mehrdadn Seems reasonable. Just curious. What's your use case?

**Comment by mehrdadn** [comment]
@gnossen At the moment it's for passing warning suppression flags to Cython libraries (and occasionally other minor things, like `-fcolor-diagnostics`), but perhaps for more as time goes on.

**Comment by mehrdadn** [comment]
I don't believe this is resolved.

**Comment by mehrdadn** [comment]
I don't believe this is resolved.

**Comment by mehrdadn** [comment]
I don't believe this is resolved.

**Comment by drfloob** [comment]
I think your best bet is to build with `bazel build --copt='-fcolor-diagnostics' :my_target`. It's unfortunately not trivial to set compiler flags globally for all targets from _within_ BUILD files. The cygrpc build depends on many other grpc core library targets, and there's no great way to pass `copt`s down through the dependency tree in bazel. Your suggestion to modify the `pyx_library ` is indeed pretty simple, but that flag would only apply to the cygrpc target's compilation directly, not the compilation of its dependencies.

**Comment by mehrdadn** [comment]
@drfloob No, that isn't our best bet. This isn't about `-fcolor-diagnostics`. It's about passing extra flags to `cc_binary`, intentionally solely to the compilation target. That's why I didn't ask how to do this globally. We ended up [having to add a `**cc_kwargs` argument](/ray-project/ray/blob/0998d69968608012ca6cdd1ee166961df1aa0f0b/BUILD.bazel#L1664) just to work around this limitation.

**Comment by drfloob** [comment]
I see. So the request here isn't limited to `copts` either, as the issue states. You want pyx_library to support the addition of arbitrary arguments to the resulting cc_binary targets. That does seem useful, though gRPC's pyx_library is considered internal, not supported for 3rd party use. We should update the docs to clarify that point.

@gnossen any argument against accepting a patch for this? There aren't any internal needs for it atm.

**Comment by gnossen** [comment]
Definitely. Contributions are welcome. I see you have several patches in your linked repo.

I'm also interested in your use case. Are you using our `pyx_library` rule directly? Or do you need this argument to somehow modify the gRPC Python library?

**Comment by mehrdadn** [comment]
Yeah, we only needed `copts` at the time. The need for other arguments arose later. We are using it [directly](https://github.com/ray-project/ray/blob/0998d69968608012ca6cdd1ee166961df1aa0f0b/BUILD.bazel#L1664). That said, now I'm thinking maybe it's not appropriate to make the change in gRPC after all? I don't recall what the implications at the time, but it's possible I might have simply missed the fact that gRPC's implementation was lifted from Tensorflow's implementation (which in turn appears to have been lifted from Cython's own implementation). I don't know if Ray had special requirements that made it start using gRPC's implementation, but it's quite possible that was done only because the dependence on gRPC was already there. So perhaps this only makes sense upstream.

**Comment by gnossen** [comment]
> So perhaps this only makes sense upstream.

AFAIK, the Cython repo has the only version of this rule that seems intended for external consumption. The others arose out of necessity/expedience. But I can't vouch for it, since I've never used it myself.
