### ISSUE TITLE
C# GRPC client enters fails at high load after TCP connection termination

### ISSUE THREAD

**Issue by djluck** [grpc/grpc#21272]
### What version of gRPC and what language are you using?
grpc ver= 2.25.0
lang=C#, 

### What operating system (Linux, Windows,...) and version?
Windows	10.0.18362 Build 18362

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET 4.7.1, C#7.3

### What did you do?
Issued a high volume of requests (200+ on my machine) on a disconnected TCP connection, which resulted in every request processing successfully reaching the GRPC server but the client could not successfully process _any_ of the requests.

Sample psuedo-code:
```
// succeeds
await grpcClient.HealthService.CheckAsync(new HealthCheckRequest(), deadline: DateTime.UtcNow.AddSeconds(5));

// idle connection timeout of AWS ELB is set to 60 seconds, wait for our underlying TCP connection to be terminated
await Task.Delay(TimeSpan.FromSeconds(65));

// 200+ requests fail :(
var tasks = Enumerable.Range(1, 200)
	.Select(_ => Task.Run(async () => { await grpcClient.HealthService.CheckAsync(new HealthCheckRequest(), deadline: DateTime.UtcNow.AddSeconds(10)); }))
	.ToArray();
```

I have a program that can reliably reproduce the errors, happy to run it with any requested `GRPC_TRACE` values.

### What did you expect to see?
All requests complete successfully. 

### What did you see instead?
Of the 200 GRPC requests, 1 request fails `StatusCode=Unavailable, Detail=RST_STREAM with error code 7` with while the other 199 requests fail with `StatusCode=Unavailable, Detail=GOAWAY received`.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
- GRPC server is running `grpc-dotnet`
- GRPC server is sitting behind an AWS ELB using a TCP listener to route traffic. It is here that idle connections are disconnected.
- Sending low volumes of GRPC requests _does work_ on a disconnected connection.

**Comment by djluck** [comment]
Something I haven't ruled out is the AWS ELB being at fault. I will run some tests using the dotnet-grpc client on Monday.

**Comment by djluck** [comment]
Closing this issue- I mistakenly though that the `grpc` library was at fault when it seems to be the `grpc-aspnet` library.

**Comment by djluck** [comment]
Re-opening this as I believe I have a better understanding of what is happening.

It seems that the GRPC client does not utilize the `SETTINGS_MAX_CONCURRENT_STREAMS` returned from the server until a connection has been successfully established. Should a connection transition from `Connected` to `Idle` then this setting will be "forgotten". Bursts of thousands of requests can then bypass this setting as the client has no prior knowledge of `SETTINGS_MAX_CONCURRENT_STREAMS`, resulting in the server terminating the excess streams.

**Comment by djluck** [comment]
Ive' attached 
[a sample log](https://github.com/grpc/grpc/files/3885360/client.txt)
 of the misbehaving client application. As you can see, `MAX_CONCURRENT_STREAMS = 1` is received from the server but this doesn't seem to be respected for in-progress streams.

**Comment by jtattermusch** [comment]
@yashykt   do you find the explanation in https://github.com/grpc/grpc/issues/21272#issuecomment-557966698 plausible? If so, it's probably a C-core bug.

@djluck  just to confirm:
- does this problem seem to be Windows specific, or are you seeing the same issue on Linux?
- would you be able to come up with a reproduction that doesn't involve external infrastructure (AWS ELB) - just two local processes talking to each other
- is this also a problem if you use Grpc.Core C# server (as opposed to grpc-dotnet) or does this seem to be some kind of incompatibility between the two?

**Comment by jtattermusch** [comment]
@djluck  re-reading the question, it seems that things might be behaving "as expected" in the sense that if your connection is terminated, you cannot expect the client to magically know 
what MAX_CONCURRENT_STREAMS setting will be set by server once we connect to it.

At the same time, if you create a large number of concurrent RPCs at the same time and the number of the concurrent RPCs is larger than  the MAX_CONCURRENT_STREAMS accepted by the server, it's not surprising that they get rejected.

reference for the HTTP/2 setting:
SETTINGS_MAX_CONCURRENT_STREAMS https://http2.github.io/http2-spec/#SettingValues

Also see the scenario in which we test the max_concurrent_stream functionality:
https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/doc/http2-interop-test-descriptions.md#max_streams

**Comment by jtattermusch** [comment]
> [I've attached a sample log](https://github.com/grpc/grpc/files/3885360/client.txt) of the misbehaving client application. In this example, I didn't wait for any connections to idle + expire- just sending a sufficiently high volume against the server and lowering the server setting of `MAX_CONCURRENT_STREAMS` to `1` was enough to trigger the failure.
> As you can see in the logs, `MAX_CONCURRENT_STREAMS = 1` is received from the server but this doesn't seem to be respected for in-progress streams. I don't have a good understanding of what happens under the hood but I believe that streams are in the process of creation before the `MAX_CONCURRENT_STREAMS` setting is received from the server and this value is not respected for streams already in-flight.

I'm pretty sure we only check against MAX_CONCURRENT_STREAMS value when a new RPC is about to be created. If the RPC is already in progress, we don't artificially "kill the RPC" when MAX_CONCURRENT_STREAMS is lowered.

**Comment by djluck** [comment]
Thanks for the explanation @jtattermusch, this makes sense. After reading your explanation and the HTTP/2 rfc, it seems that this library is not at fault- I believe the dotnet-grpc server should not be terminating a connection in the case of DATA frames being received on closed streams (rather they should just be returning errors of STREAM_CLOSED for that stream). I'll open my issue there.

**Comment by jtattermusch** [comment]
@djluck  feel free to post the issue number here for the reference.

**Comment by djluck** [comment]
Sure thing- https://github.com/aspnet/AspNetCore/issues/17484.
