### ISSUE TITLE
Fix warnings about precision loss from implicit integer narrowing

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2127]
The C core has several instances of using 64-bit integer values as smaller integers, which causes warnings in XCode.

 This is part of fixing #2102.

**Comment by ctiller** [comment]
This needs a Jenkins test that will fail given the current code.

**Comment by jcanizales** [comment]
Are these warnings showing up on Linux? We might need to wait for Jenkins' Macs otherwise.

**Comment by ctiller** [comment]
We compile warning free on Linux and Mac currently, and enforce it with
-Werror.

**Comment by murgatroid99** [comment]
As far as I can tell, the flag to enable that warning in GCC is `-Wconversion`, which we are not currently using in the core Makefile.
