### ISSUE TITLE
tcp_posix_test on MacOS silently fails with SIGPIPE (under run_tests.py)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21282]
tcp_posix_test is being continuously run on MacOS C/C++ tests with `run_tests.py`
and `run_tests.py` reports it as "PASSED", but the the test actually exits with SIGPIPE and non-zero error code without finishing.

I'm guessing silently ignoring SIGPIPE is due to the way python runs jobs in jobset.py.

I discovered this when trying setup continuous `bazel test` job on Mac (and bazel correctly reports the test as failed.

Repro
```
tools/run_tests/run_tests.py -l c -c dbg -r tcp_posix_test
SUCCESS: All tests passed
```

But the test actually fails:
```
# run after building
bins/dbg/tcp_posix_test || echo "process exited with error"
```

More logs:
```
GRPC_VERBOSITY=debug bins/dbg/tcp_posix_test; echo "Exited with code $?"
D1125 12:57:04.291217000 4498785728 test_config.cc:384]                test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1125 12:57:04.291674000 4498785728 ev_posix.cc:174]                   Using polling engine: poll
D1125 12:57:04.291835000 4498785728 dns_resolver_ares.cc:503]          Using ares dns resolver
D1125 12:57:04.291930000 4498785728 buffer_list.cc:303]                Timestamps callback is not enabled for this platform
I1125 12:57:04.291944000 4498785728 endpoint_tests.cc:71]              multiple_shutdown_test/tcp/tcp_socketpair
Exited with code 141
```

**Comment by veblush** [comment]
@jtattermusch Jan, is this still relevant? Is it happening on the gRPC CI?

**Comment by jtattermusch** [comment]
Based on the historical data, there don't seem to be anys failure in the last 100 days.
