### ISSUE TITLE
Remove unreachable code in C core

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2128]
The C core has several instances of unreachable code, most of which are `abort();` and/or `gpr_log(GPR_ERROR, "should never reach here");`. These should be removed.

This is part of fixing #2102

**Comment by ctiller** [comment]
This needs a test on Jenkins that will fail given the current code.

**Comment by jcanizales** [comment]
Is the compiler currently used on Linux not emitting those warnings, or is it that it doesn't treat them as errors?

Is Jenkins currently just calling `make`?

**Comment by ctiller** [comment]
This is actually fiddly. The current compiler suite doesn't error on these. We will end up with compilers that do emit errors on this, and compilers that complain that this code is not there.

Suggest:
```
#define GPR_UNREACHABLE_CODE(xxx) do { abort(); xxx; } while (0)
/* or: */
#define GPR_UNREACHABLE_CODE(xxx)
```
in port_platform.h defined as appropriate for the detected compiler.

Used like:
```
GPR_UNREACHABLE_CODE(return 0);
```
