### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Warchant** [grpc/grpc#21280]
### What version of gRPC and what language are you using?
1.24.2, C++11

### What operating system (Linux, Windows,...) and version?
```bash
$ uname -a
Linux xps 4.19.85-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:38:39 UTC 2019 x86_64 GNU/Linux
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```bash
$ clang -v 
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
...
```

CC=clang CXX=clang++

### What did you do?
Our code is very simple. Just connect from C++ client to java server with InsecureChannelCredentials.

```C++
std::string ip = "127.0.0.1";
std::string port = "19012";
std::shared_ptr<Channel> channel = grpc::CreateChannel(ip + ":" + port, grpc::InsecureChannelCredentials());
```

`CreateChannel` hangs forever (in infinite loop), both with java service being online/offline.

Bug can be reproduced with or without GRPC_* env vars defined.

If we define these ENV vars:
```
export GRPC_VERBOSITY=DEBUG
export GRPC_TRACE=all
```

And run our binary, you can see this:
```
D1123 20:20:56.903306023   25004 ev_posix.cc:174]            Using polling engine: epollex
D1123 20:20:56.908538708   25004 dns_resolver_ares.cc:503]   Using ares dns resolver
```

htop shows 100% CPU load, and process hangs (even CTRL+C does not kill it).

I tried all options for GRPC_POLL_STRATEGY (epoll, poll, legacy), but only poll seems to be working.

Also I tried GRPC_DNS_RESOLVER (ares, native), both stuck on the same place.

This bug can be reproduced on Linux and can not be reproduced on Windows. We did not test MACs.

We did not investigate this bug in details, but it seems that it comes from the GRPC_TRACE processing code. 

### Anything else we should know about your project / environment?

std=C++11
Protobuf - v3.10.0
gflags - v2.2.2
cares - cares-1_15_0

**Comment by Warchant** [comment]
I tried earlier version of GRPC. This bug exists in v1.21.1

**Comment by Warchant** [comment]
Found this comment 

>GRPC library contains tracing subsystem, and initialization of trace flags is done as static init (init of static variables). Internally, each init code adds trace flag metadata to shared linked list. For some reason, in my app, before main(), each static init is called twice (I admit i have to spend some efforts to investigate, but unfortunately I have other things to do). Linked list, due to reinvention of the wheel, is written the way which is causing circular references if same elements are added twice, and any subsequent internal effort to traverse resulting list causes infinite loop. Had to patch it. If I link against libraries provided by system package manager, it shows same behavior. Note that grpc init is first stuff in my app main() function, and I don't use static init in my own code.

https://gitter.im/grpc/grpc?at=5d91cda8086a72719e8baaa7

**Comment by Warchant** [comment]
```
grpc::InsecureChannelCredentials()
```
is the cause of infinite loop. digging further..

**Comment by beef9999** [comment]
+1
CentOS 6, grpc 1.25x, g++ 6.0+

**Comment by Warchant** [comment]
Same issue
- #21507 
- #21552 
- #21548

**Comment by DuckSoft** [comment]
Please fix this issue.

**Comment by bduclaux** [comment]
This issue should be P1. 
Same issue here: https://github.com/grpc/grpc/issues/21213

Please fix !

**Comment by blockspacer** [comment]
Please fix this issue.
This issue still occurs in 1.26.0 release!
Tested under docker, removed system `libprotobuf-dev` (due to install from sources)

```
ARG GRPC_RELEASE_TAG=v1.26.0

# ...

ENV LC_ALL=C.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en

# ...
  # Uninstall the default version provided by Ubuntu package manager, so we can install custom one
  $APT remove -y libprotobuf-dev || true \
  && \
  # Uninstall the default version provided by Ubuntu package manager, so we can install custom one
  $APT remove -y libprotobuf9v5 || true \
  && \
  # Uninstall the default version provided by Ubuntu package manager, so we can install custom one
  $APT remove -y libprotobuf8 || true \
  && \
  # Uninstall the default version provided by Ubuntu package manager, so we can install custom one
  find /usr/lib -name "*protobuf*" -delete \

# ...
      git clone -b ${GRPC_RELEASE_TAG} https://github.com/grpc/grpc /var/local/git/grpc \
      && \
      cd /var/local/git/grpc \
      && \
      git submodule update --init --recursive \
      && \
      echo "-- installing protobuf (from remote repo)" \
      && \
      cd /var/local/git/grpc/third_party/protobuf \
      && \
      git submodule update --init --recursive \
      && \
      ./autogen.sh && ./configure --enable-shared \
      && \
      make -j$(nproc) && make install && make clean && ldconfig \
      && \
      echo "-- installing grpc (requires protobuf) (from remote repo)" \
      && \
      cd /var/local/git/grpc \
      && \
      make -j$(nproc) && make install && make clean && ldconfig \
      && \
      rm -rf /var/local/git/grpc \

```

**Comment by Warchant** [comment]
@blockspacer try use branch 1.26.x, for me it works

**Comment by abcdabcd987** [comment]
+1 Same problem on Arch Linux / Manjaro, grpc 1.26.0-4

**Comment by Warchant** [comment]
Solved in branch 1.26.x

**Comment by coryan** [comment]
Does the gRPC team plan to create 1.26.1?

**Comment by veblush** [comment]
Since we're about to release 1.27.0 pretty soon, there is no plan to make 1.26.1 tag. If you need it, please feel free to open the issue for that.
