### ISSUE TITLE
DNS Resolution to bind server

### ISSUE THREAD

**Issue by TachyonRSA** [grpc/grpc#21284]
### What version of gRPC and what language are you using?
2.25.0
C#

### What operating system (Linux, Windows,...) and version?
Windows 10 1909

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Core

### What did you do?
I am trying to setup the server to listen on its unique DNS name that was specified in the application manifest file.

The manifest file has the following record:
```
<Service Name="AccountService" ServiceDnsName="accountservice.application1" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="AccountServiceType" InstanceCount="[AccountService_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
```

And I am trying to bind the service as follows:
```
var grpcServer = new Server();
grpcServer.Ports.Add("accountservice.application1", 4949, ServerCredentials.Insecure);
grpcServer.Services.Add(Greeter.BindService(new GreeterImpl()));
grpcServer.Start();
```

### What did you expect to see?
Expect to see the server bind to the hostname

### What did you see instead?

> Failed to bind port "accountservice.application1:4949

**Comment by jtattermusch** [comment]
The manifest file you mentioned doesn't seem like something we support.
