### ISSUE TITLE
String inside metadata has bad characters

### ISSUE THREAD

**Issue by samuelazcona** [grpc/grpc#21288]
Hi guys!

I'm sending a JWT HS256 Token string inside metadata of grpc call:

this is the json example of the metadata client call:

`{"authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzQ4MDYwNzQsInVzZXJJZCI6IjExRTlGOTJGRDk0QjhDMkZCQzE0MDI0MkFDMTIwMDAyIn0.VjdjJwFmDTjbZHOmnf1CnlVZElZb3Jt3e5BASEuYfRc"}`

the problem is that in the grpc++ server I'm getting the metadata string with some random bad characters for example this:

`Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzQ4MDYwNzQsInVzZXJJZCI6IjExRTlGOTJGRDk0QjhDMkZCQzE0MDI0MkFDMTIwMDAyIn0.VjdjJwFmDTjbZHOmnf1CnlVZElZb3Jt3e5BASEuYfRc�������g�`

in some cases I receive it ok but it the major cases the string has that random unknown characters

I'm using this function to get the string from the metadata:

```
const std::string
Security::Token::extractTokenFromGrpcMetadata(const std::multimap<grpc::string_ref, grpc::string_ref> &metadata) {
    auto map = metadata;
    std::multimap<grpc::string_ref, grpc::string_ref>::iterator itr;
    for (itr = map.begin(); itr != map.end(); ++itr) {
        if (itr->first == "authorization") {
            try {
                std::cout << "ORIGINAL TOKEN STRING IS \n";
               // this print the token to check if the data is correct or have bad characteres
                std::cout << itr->second.data() << "\n";
                std::string erase = "Bearer ";
                std::size_t pos = itr->second.find(erase);
                std::string value = itr->second.data();
                std::string token = value.erase(pos, erase.length());
                return token;
            } catch (...) {
                throw SecurityException("TOKEN Format invalid you need tu use Bearer token");
            }

        }

    }

    throw SecurityException("TOKEN IS MISSING, YOU NEED TO SEND YOUR TOKEN AS METADATA example: authorization: Bearer token");
}
```

Any ideas?

Thanks.

**Comment by samuelazcona** [comment]
UPDATE:
construct the std::string using begin and end solve the issue, the issue is related to .data() from grpc::string_ref have dirty characters:

```
               std::string erase = "Bearer ";
                std::cout << "TOKEN STRING IS \n";
                std::size_t pos = itr->second.find(erase);
                grpc::string_ref value = itr->second;
                grpc::string_ref strip_token = value.substr(erase.length(), itr->second.size()-pos);
                std::string token(strip_token.begin(), strip_token.end());
                stripUnicode(token);
                std::cout << token << "\n";
```

**Comment by mehrdada** [comment]
This is not a bug: `grpc::string_ref` is not necessarily `NULL`-terminated, so you are not supposed to read past it.
