### ISSUE TITLE
[Python install] grpc 1.17.2-1 build failure on xenial. (works great on bionic though)

### ISSUE THREAD

**Issue by frederic-loui** [grpc/grpc#21295]
### What version of gRPC and what language are you using?
grpc-1.17.2-1

### What operating system (Linux, Windows,...) and version?
Linux ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.12

### What did you do?
I wanted to buid grpc-1.17.2-1 packages using source package from:
`https://salsa.debian.org/debian/grpc/tree/debian/1.17.2-1`

### What did you expect to see?
I had sevral errors that I could overcome:
0- I disabled documentation by commenting out the line in debian/rules:
`#export GRPC_PYTHON_ENABLE_DOCUMENTATION_BUILD = 1`
And remove python sphinx package reference in debian/control
1- I had to add CFLAGS and CXXFLAGS in rules by add the lines below:
export DEB_CFLAGS_MAINT_APPEND  += -fPIC
export DEB_CXXFLAGS_MAINT_APPEND  += -fPIC
2- During debuild I saw: a `DSO missing from command line` error
```
/usr/bin/ld: python_build/temp.linux-x86_64-2.7/src/core/lib/gpr/env_linux.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "setup.py", line 353, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/lib/python2.7/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/floui/build/grpc/grpc-1.17.2/src/python/grpcio/commands.py", line 275, in build_extensions
    support.diagnose_build_ext_error(self, error, formatted_exception)
  File "/home/floui/build/grpc/grpc-1.17.2/src/python/grpcio/support.py", line 109, in diagnose_build_ext_error
    "backtrace).\n\n{}".format(formatted))
commands.CommandError: 
```
3- I Added " -ldl" in setup.py for grpcio compilation
`EXTRA_ENV_LINK_ARGS += ' -lpthread -ldl'`
the `DSO missing` error disappeared
 
### What did you see instead?
grpcio still fail to compile seeing:
```
...
Traceback (most recent call last):
  File "setup.py", line 353, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/lib/python2.7/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/floui/build/grpc/test/grpc/src/python/grpcio/commands.py", line 275, in build_extensions
    support.diagnose_build_ext_error(self, error, formatted_exception)
  File "/home/floui/build/grpc/test/grpc/src/python/grpcio/support.py", line 109, in diagnose_build_ext_error
    "backtrace).\n\n{}".format(formatted))
commands.CommandError:

We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the titl
e; please attach the whole log (including everything that may have appeared above the Python backtrace).

...
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I installed requirement.txt before hand. i.e:
```
floui@xenial-tmp:~/build/grpc/test$ cat grpc/requirements.txt 
# GRPC Python setup requirements
coverage>=4.0
cython==0.28.3
enum34>=1.0.4
protobuf>=3.5.0.post1
six>=1.10
wheel>=0.29
floui@xenial-tmp:~/build/grpc/test$ sudo dpkg -l | egrep "cython|coverage|wheel|enum34|six|protobuf"
ii  cython                                0.28.3-0.4                                 amd64        C-Extensions for Python
ii  cython-dbg                            0.28.3-0.4                                 amd64        C-Extensions for Python - debug build
ii  cython-doc                            0.28.3-0.4                                 all          C-Extensions for Python - documentation
ii  cython3                               0.28.3-0.4                                 amd64        C-Extensions for Python 3
ii  cython3-dbg                           0.28.3-0.4                                 amd64        C-Extensions for Python 3 - debug build
ii  libprotobuf-dev:amd64                 3.6.1.3-1                                  amd64        protocol buffers C++ library (development files) and proto files
ii  libprotobuf-java                      3.6.1.3-1                                  all          Java bindings for protocol buffers
ii  libprotobuf-lite17:amd64              3.6.1.3-1                                  amd64        protocol buffers C++ library (lite version)
ii  libprotobuf17:amd64                   3.6.1.3-1                                  amd64        protocol buffers C++ library
ii  protobuf-compiler                     3.6.1.3-1                                  amd64        compiler for protocol buffer definition files
ii  pypy-coverage                         4.5+dfsg.1-3                               all          code coverage tool for Python 2 PyPy
ii  python-coverage                       4.5+dfsg.1-3                               amd64        code coverage tool for Python 2
ii  python-coverage-doc                   4.5+dfsg.1-3                               all          code coverage tool for Python — documentation
ii  python-enum34                         1.1.2-1                                    all          backport of Python 3.4's enum package
ii  python-protobuf                       3.6.1.3-1                                  amd64        Python bindings for protocol buffers
ii  python-six                            1.10.0-3                                   all          Python 2 and 3 compatibility library (Python 2 interface)
ii  python-wheel                          0.29.0-1                                   all          built-package format for Python
ii  python3-coverage                      4.5+dfsg.1-3                               amd64        code coverage tool for Python 3
ii  python3-protobuf                      3.6.1.3-1                                  amd64        Python 3 bindings for protocol buffers
ii  python3-six                           1.10.0-3                                   all          Python 2 and 3 compatibility library (Python 3 interface)
ii  ruby-google-protobuf:amd64            3.6.1.3-1                                  amd64        Protocol Buffers
```

Full log here:
[debuild-grpc-1.17.2-1-xenial.log](https://github.com/grpc/grpc/files/3891781/debuild-grpc-1.17.2-1-xenial.log)

PS: I had also to upgrade c-ares:
```
floui@xenial-tmp:~/build/grpc/test$ sudo dpkg -l | egrep "ares"                                     
ii  libc-ares-dev:amd64                   1.14.0-1                                   amd64        asynchronous name resolver - development files
ii  libc-ares2:amd64                      1.14.0-1                                   amd64        asynchronous name resolver
```

Otherwise  I had an error as libc-ares-dev in a stock xenial has a too old version.

Last but not least. This compilation works perfectly on Bionic. The issue is only obsrevd during python-grpc compilation on Bionic.

**Comment by veblush** [comment]
Richard, can you take a look at this?

**Comment by gnossen** [comment]
@frederic-loui https://salsa.debian.org/debian/grpc is an independent fork not maintained by the gRPC team. Your full build log looks like the Python isn't being linked into the C extension. You should report this problem to the maintainer of that repo. If the problem turns out to be reproducible in upstream, please reopen with a minimal reproduction that doesn't require the fork.

**Comment by frederic-loui** [comment]
Hi, Thanks for your answer.
But I tried also to git clone your repository 1.17.x and get the same
errors when I want to build it on ubuntu 16.04.

Did you already try to deploy 1.17.x on xenial ?
grpc compilation is OK but pyton-grpcio is not and it appears that this is
during linking/libtool process. (cython)

All the best,
Frederic

**Comment by gnossen** [comment]
@frederic-loui I am unable to reproduce with the `ubuntu:16.04` docker image:

```bash
root@622bb5bfae15:/grpc# history
    1  apt-get update -y && apt-get install -y git
    2  git clone https://github.com/grpc/grpc.git
    3  cd grpc
    4  git fetch origin -a
    5  git checkout origin/v1.17.x
    6  apt-get install -y python python-dev
    7  apt-get install -y build-essential
    8  apt-get install -y python-setuptools
    9  git submodule init
   10  git submodule update --recursive
   11  python setup.py install
   12  echo $?
   13  python
   14  history
```

**Comment by frederic-loui** [comment]
Hi Thanks for your effort and reply.
Don't you rebuild python-grpcio using cython on xenial ?

the idea is to rebuild from source as we are trying to build 1.17.x package
for xenial: (notice the [-v] trigger for pip)
Usually you end with the errors (lib-ares-dev not being up to date) I've
overcome this by backporting c-ares, cython: (here)
https://launchpad.net/~frederic-loui/+archive/ubuntu/p4lang-3rd-party-xenial/+packages

But if you look at the build log : (full log here)

https://launchpadlibrarian.net/453289929/buildlog_ubuntu-xenial-amd64.grpc_1.17.2_BUILDING.txt.gz

It shows a linking error: /usr/bin/ld:
python_build/temp.linux-x86_64-2.7/src/core/lib/gpr/env_linux.o: undefined
reference to symbol 'dlsym@@GLIBC_2.2.5'
I added "-ld" in setup.py:

line 152: EXTRA_ENV_LINK_ARGS += ' -lpthread -dl'
So this error message dosapear but I get an other linking error describe in
my initial bug report.

If you want to reproduce it, you can install a fresh ubuntu, use the PPA
above. (
https://launchpad.net/~frederic-loui/+archive/ubuntu/p4lang-3rd-party-xenial/+packages
)
Install all package except grpc.

Download:
grpc debian folder:
https://launchpad.net/~frederic-loui/+archive/ubuntu/p4lang-3rd-party-xenial/+sourcefiles/grpc/1.17.2/grpc_1.17.2.debian.tar.xz
grpc: tar.gz source tarball
https://launchpad.net/~frederic-loui/+archive/ubuntu/p4lang-3rd-party-xenial/+sourcefiles/grpc/1.17.2/grpc_1.17.2.orig.tar.gz

cp -r debian/ grpc-1.17.2/
cd grpc-1.17.2/
debuild -us -uc

You'll observe the dso missing error.

* Update setup.py and add '-ldl' on line 152:
* dpkg commit the source before for a poatch generation)
   dpkg-source commit
* debuild again
   debuild -us -uc
   -> you'll see an other error related to linking library on xenial ...

$ export REPO_ROOT=grpc  # REPO_ROOT can be any directory of your choice
$ git clone -b $(curl -L https://grpc.io/release)
https://github.com/grpc/grpc $REPO_ROOT
$ cd $REPO_ROOT
$ git submodule update --init

# For the next two commands do `sudo pip install` if you get
permission-denied errors
$ pip install -rrequirements.txt
$ GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip -v install .

When I disable python-grpcio 1.17.x  package builds all grpc deb are
building fine.

All the best,
Frederic
