### ISSUE TITLE
Static build with OpenSSL 1.1.1+ on Windows

### ISSUE THREAD

**Issue by Rantanen** [grpc/grpc#21293]
This is duplicate of https://github.com/grpc/grpc/issues/12231 which has been closed as stale and in which I cannot comment.

### What version of gRPC and what language are you using?
C++ 1.24/1.25

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2015

### What did you do?
Compiled static OpenSSL and attempted to compile static gRPC.

### What did you expect to see?
Successful build

### What did you see instead?
Undefined references related to symbols in Microsoft's crypt32.lib. Unfortunately I don't have the build log with me currently.

### Anything else we should know about your project / environment?
The build I've configured attempts to mimic the vcpkg build - vcpkg works around this issue by patching the CMakeLists file with the following patch:

https://github.com/microsoft/vcpkg/blob/master/ports/grpc/00006-crypt32.patch

(I'm a bit disappointed to see no attempt on vcpkg's behalf to upstream any of the patches in vcpkg.)

I've now built gRPC from my own fork of 1.25.0 successfully by having the patch applied on top of the v1.25.0 branch: https://github.com/Rantanen/grpc/commits/v1.25.0-mfiles

Would gRPC be interested in upstreaming this change? I can prepare a merge request if that's the case. I know there's some shift in focus onto Bazel these days, but I haven't found a way to create a static gRPC archive with Bazel (not that I looked for one _that_ much). Our product toolchain is based on Visual Studio, so currently we are compiling gRPC as static archive and including that in the VS builds.

Also I'm not sure how testable such MR would be, given - as far as I know - the CI doesn't compile static libraries or link against OpenSSL (1.1.x).

**Comment by jozefizso** [comment]
As OpenSSL 1.0.2 has end of life on 31st Dec 2019 and we should move to OpenSSL 1.1, this patch from vcpkg should be incorporated into grpc.

**Comment by Croydon** [comment]
I'm packaging grpc for Conan and this patch finally allows me to upgrade OpenSSL from 1.0.2 to 1.1.1

This patch should get merged

https://github.com/inexorgame/conan-grpc/commit/f72a7c47b277845236949c5bc52896133c9ce053

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/21611
