### ISSUE TITLE
go interop tests failing on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21297]
both interop_toprod and interop_tocloud are failing with 100% failure rate on master

https://source.cloud.google.com/results/invocations/ab42fd6a-7ef4-4a77-ac30-2239a1c8a3ae/targets/github%2Fgrpc%2Finterop_test/tests

https://source.cloud.google.com/results/invocations/cd6f2931-040b-4997-8797-3e289f2caf22/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud/log

**Comment by menghanl** [comment]
This looks like a dup of #21301
