### ISSUE TITLE
gRPC configuration "grpc.max_connection_age_ms" and "grpc.max_connection_age_grace_ms" causing server crash

### ISSUE THREAD

**Issue by thomasfrisko** [grpc/grpc#21327]
# What version of gRPC and what language are you using?
1.22.1

### What operating system (Linux, Windows,...) and version?
Linux 4.14.138

### What runtime / compiler are you using (e.g. python version or version of gcc)
ASP .NET Core

### What did you do?
Applied the following settings "grpc.max_connection_age_ms" and "grpc.max_connection_age_grace_ms" 

can sometimes cause crash on gRPC service with the error E1122 /var/local/git/grpc/src/core/lib/transport/connectivity_state.cc:154: assertion failed: cur != GRPC_CHANNEL_SHUTDOWN

### What did you expect to see?
I expected TCP connections to be terminated based on the value of the setting "grpc.max_connection_age_ms". e.g. setting it to 10000 would cause 120000 would terminate the TCP connection after 2 minutes 

### What did you see instead?
It terminated TCP connections as expected, however, sometimes the server would crash with the error:
E1122 /var/local/git/grpc/src/core/lib/transport/connectivity_state.cc:154: assertion failed: cur != GRPC_CHANNEL_SHUTDOWN

The application is running in a Docker container on Kubernetes where the exit code 139 which could mean a segmentation fault.
When not using grpc.max_connection_age_ms configuration, this error never seem to appear.

**Comment by bensimian** [comment]
We recently are getting assertion failed: cur != GRPC_CHANNEL_SHUTDOWN and have set the grpc.max_connection_age_ms. @thomasfrisko were you able to come to any conclusions

**Comment by thomasfrisko** [comment]
No we never figured out what the issue is so we removed the settings

**Comment by bensimian** [comment]
Thanks @thomasfrisko for getting back. We actually tested the scenario by blocking the Node event loop for longer than the Ping and Timeout. So something, at least our Hypothesis is pointing in something blocking the process.
