### ISSUE TITLE
The C++ load balance example needs more details

### ISSUE THREAD

**Issue by beef9999** [grpc/grpc#21326]
Hi,

Could you elaborate more on the C++ load balance example? Some important concepts and code are missing, like Resolver, Builder and UpdateState.
https://github.com/grpc/grpc/blob/master/examples/cpp/load_balancing/greeter_client.cc

The Golang example is quite a good one, for your reference. https://github.com/grpc/grpc-go/blob/master/examples/features/load_balancing/client/main.go

**Comment by muxi** [comment]
@markdroth - documentation enhancement request for load balancing.

**Comment by markdroth** [comment]
The example you pointed to is actually not an example of how to write a load balancing policy; it's just a very simple example of how to set up multiple backends to use the round_robin LB policy with.

The C-core load balancing policy is actually not a public API yet, although we are working on making it one.  But until that's done, there's nothing to document yet.
