### ISSUE TITLE
Flake: mac-test-basictests boringssl fetch fails

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#21320]
INFO: Call stack for the definition of repository 'boringssl' which is a http_archive (rule definition at /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/bazel/grpc_deps.bzl:100:9
 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/WORKSPACE:5:1
WARNING: Download from https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'boringssl':
   java.io.IOException: Error downloading [https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/boringssl/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz: Read timed out
ERROR: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/bazel/grpc_deps.bzl:24:5: //external:libssl depends on @boringssl//:ssl in repository @boringssl which failed to fetch. no such package '@boringssl//': java.io.IOException: Error downloading [https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/boringssl/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz: Read timed out
ERROR: Analysis of target '//test/cpp/interop:interop_server' failed; build aborted: Analysis failed
INFO: Elapsed time: 675.476s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 1695 targets configured)
FAILED: Build did NOT complete successfully (13 packages loaded, 1695 targets configured)

2019-11-27 11:36:42,670 FAILED: mac-test-basictests [ret=1, pid=32848, time=1128.5sec]
2019-11-27 11:36:42,671 FAILED: mac-test-basictests
2019-11-27 11:36:42,678 FAILED: Some tests failed

2019-11-27 11:36:42,712 FAILED: run_tests_objc_macos_opt_native [ret=2, pid=31711, time=1152.0sec]
2019-11-27 11:36:42,728 FAILED: Some run_tests.py instances have failed.
+ FAILED=true

https://source.cloud.google.com/results/invocations/52318d17-31ba-4c06-bc4c-2aefe836f5d2/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_objc_mac/log

**Comment by jtattermusch** [comment]
Looks like the URL can be flaky when downloading from the following URL on our mac workers https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L129

Perhaps adding a backup `url =` arg would help? Perhaps bazel also lets you configure retries when downloading http_archive?
