### ISSUE TITLE
Grpc-protobuf 1.25 brings in protobuf 3.10, which has a bug on Android

### ISSUE THREAD

**Issue by catenocrypt** [grpc/grpc#21334]
Protobuf 3.10 has a compatibilty issue on Android.  This has already been resolved in 3.11.  Suggestion is to move from 3.10 to the already released 3.11.

"Java: Remove the usage of MethodHandle, so that Android users prior to API version 26 can use protobuf-java"
https://github.com/protocolbuffers/protobuf/releases/tag/v3.11.0

### What version of gRPC and what language are you using?

grpc-protobuf 1.25

### What operating system (Linux, Windows,...) and version?

dev MacOS 10.15, build Ubuntu 16.04, target Android

### What runtime / compiler are you using (e.g. python version or version of gcc)

clang

### What did you do?

- Include dependency 'io.grpc:grpc-protobuf:1.25.0'
- Performing ./gradlew assembleAndroidTest

### What did you expect to see?

Success

### What did you see instead?

Protobuf version 3.10 was resolved.
Produced an error while performing DexingNoClasspathTransform.
This is a known compatibility issue of protobuf 3.10 on Android.

**Comment by muxi** [comment]
Closing this issue as it looks like gRPC has already moved to 3.11.4.
