### ISSUE TITLE
performance limitation of one client process

### ISSUE THREAD

**Issue by yong0819** [grpc/grpc#21332]
### What version of gRPC and what language are you using?
1.20

### What operating system (Linux, Windows,...) and version?
linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
rpc communication from c++ grpc client to java grpc server.
one process, multiple threads(10-50), and one new channel/client (grpc::CreateChannel) per thread. When I start one process and send message from each threads through its rpc client, I can get only 6500qps/334MB/s. When I start two processes and send message with same pattern , I can get 11700qps/620MB/s.
After looking into the state, I found there is only one socket connected to the server for each process, even there is multiple client/channel sending messages to the server.
I'm guessing whether the online socket number is the root cause of bandwidth limitation.
Any response is appreciated.

### What did you expect to see?
multiple http2 socket connections.

### What did you see instead?
only one http2 socket connection.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yong0819** [comment]
v1.20.0

**Comment by muxi** [comment]
@markdroth - looks like issue with shared subchannel. Could you take a look?

**Comment by markdroth** [comment]
This is working as intended.  Multiple channels to the same server will share underlying connections.  There is a channel arg you can use to inhibit this behavior called `GRPC_ARG_USE_LOCAL_SUBCHANNEL_POOL`:

https://github.com/grpc/grpc/blob/9993d2b9a421a0b27b604c52fa93260fe0638b12/include/grpc/impl/codegen/grpc_types.h#L414
