### ISSUE TITLE
C++ build documentation and examples lacking

### ISSUE THREAD

**Issue by xd009642** [grpc/grpc#21330]
I've been attempting to build grpc with the opencensus support via grpcpp/opencensus.h and have been running into issues. I'm trying to use cmake and make (preferably cmake) and there's no documentation on building grpc with any extension support or general guidance on the web.

So I'd appreciate some help, but also I feel the build documentation could do with a lot of improvements

**Comment by muxi** [comment]
I'll leave the issue open for tracking the documents enhancement. But if you still have any question, please move the discussion to [gRPC mailing list](https://groups.google.com/forum/#!forum/grpc-io).

**Comment by markdroth** [comment]
Unfortunately, opencensus does not support building with cmake, only with bazel.  So the only way we can build gRPC with opencensus support is to build gRPC with bazel.
