### ISSUE TITLE
Question about ruby Interceptors

### ISSUE THREAD

**Issue by estolfo** [grpc/grpc#21350]
Hello
I'd like to use the [Interceptor](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/interceptors.rb) API in the ruby gem for its instrumentation in the [Elastic APM Ruby agent](https://github.com/elastic/apm-agent-ruby).
I see that it's marked as "Experimental" but was added a few years ago.
Is the API still indeed experimental? If so, is there a estimated date for its GA?
Thanks in advance!

**Comment by muxi** [comment]
Closing the PR according to gRPC process. If the question still applies, .please ask the question on [gRPC mailing list](https://groups.google.com/forum/#!forum/grpc-io).
