### ISSUE TITLE
Getting memory crashes in NSOperationQueue (QOS: UNSPECIFIED) EXC_BAD_ACCESS 0x0000000000000000

### ISSUE THREAD

**Issue by tikekar** [grpc/grpc#21367]
### What version of gRPC and what language are you using?
1.22.0 grpc version and using Swift language

### What operating system (Linux, Windows,...) and version?
iOS

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

We have an iOS app using Protobuf and grpc-swift ( https://github.com/grpc/grpc-swift ) library. Internally it is using grpc 1.22.0 version. But our app's users are seeing lots of crashes like these -

We haven't been able to understand those crashes or what can cause it. As our implementation is in swift and those errors are way deep into cc files, not sure what we are doing wrong here. We do use Protobuf for communication which internally uses GRPC. 

### What did you expect to see?
No crashes

### What did you see instead?
The crashes are at various places. But it might be great if we can get some help in finding some pattern regarding what can cause those.
![image](https://user-images.githubusercontent.com/8505549/70113182-0efbf280-160d-11ea-97c4-98291277bf82.png)

![image](https://user-images.githubusercontent.com/8505549/70113196-2044ff00-160d-11ea-9d7c-454e37ee282a.png)

Crashed: NSOperationQueue 0x10b8259d0 (QOS: UNSPECIFIED)
0  grpc                             0x10b1b9954 grpc_slice_ref + 54 (slice.cc:54)
1  SwiftGRPC                        0x10a979804 cgrpc_metadata_array_copy + 86 (metadata_shim.c:86)
2  SwiftGRPC                        0x10a97b814 Call.start(_:metadata:message:completion:) + 108 (Metadata.swift:108)
3  SwiftGRPC                        0x10a98a0b4 ClientCallUnaryBase.start(request:metadata:completion:) + 49 (ClientCallUnary.swift:49)

Crashed: NSOperationQueue 0x10d91df70 (QOS: UNSPECIFIED)
0  libsystem_kernel.dylib           0x1c2410ef4 __pthread_kill + 8
1  libsystem_pthread.dylib          0x1c2331d1c pthread_kill + 196
2  libsystem_c.dylib                0x1c22c1a54 abort + 104
3  grpc                             0x10d271254 gpr_zalloc + 64 (alloc.cc:64)
4  SwiftGRPC                        0x10caa97c8 cgrpc_metadata_array_copy + 83 (metadata_shim.c:83)
5  SwiftGRPC                        0x10caab814 Call.start(_:metadata:message:completion:) + 108 (Metadata.swift:108)
6  SwiftGRPC                        0x10caba0b4 ClientCallUnaryBase.start(request:metadata:completion:) + 49 (ClientCallUnary.swift:49)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
It is an iOS app using Swift, grpc-swift library and Protobuf

**Comment by muxi** [comment]
I don't think we are able to address this issue without more information. The crash looks to be related to the usage of grpc core API (e.g. double destroy of metadata or slice). I'd suggest to file issue with grpc-swift to check for reason.
