### ISSUE TITLE
C++ ThreadManager: thread limit: backlog vs resource_exhausted option

### ISSUE THREAD

**Issue by chrisse74** [grpc/grpc#21373]
### Is your feature request related to a problem? Please describe.
The C++ gRPC ThreadManager (see https://github.com/grpc/proposal/blob/4c8ae7b9a112a34d34958254c2f0f1820f4c72a7/L26-Ability-to-restrict-max-threads-in-C%2B%2BSyncServer.md ) 
allows to restrict the maximum number of threads of the sync-server via a ResourceQuota.

The current behaviour of the ThreadManager, when reaching this thread limit, is to reject the call, giving status resource_exhausted, leaving the client to deal with this.

We would rather have a backlog of requests, ideally the size of this backlog would be configurable - is this possible, using the sync-server?

### Describe the solution you'd like
Experimentally I removed the setting of the resource_exhausted flag in ThreadManager. 

```
diff -Nur grpc-1.24.2/src/cpp/thread_manager/thread_manager.cc grpc-1.24.2.patched/src/cpp/thread_manager/thread_manager.cc
--- grpc-1.24.2/src/cpp/thread_manager/thread_manager.cc    2019-12-04 10:11:26.266310797 +0100
+++ grpc-1.24.2.patched/src/cpp/thread_manager/thread_manager.cc    2019-12-03 11:11:21.000718544 +0100
@@ -205,7 +205,9 @@
             // There are no pollers to spare and we couldn't allocate
             // a new thread, so resources are exhausted!
             lock.Unlock();
-            resource_exhausted = true;
+          //  resource_exhausted = true;
           }
         } else {
           // There are a sufficient number of pollers available so we can do
```

This works as intended in our test-settings, but raises at least two questions.

1. Upgrading versions with a patch of this kind seems error-prone. Could we introduce some kind of server-parameter for this?
2. When the server does not respond to a new connection attempt for more than 20 seconds (because no thread polls the completion queue, when all worker threads are working), the client times out the handshake and no re-connect is done (we would have expected the client trying until GRPC_SUBCHANNEL_RECONNECT_MAX_BACKOFF_SECONDS [=120] is reached, but it corresponds with GRPC_SUBCHANNEL_RECONNECT_MIN_TIMEOUT_SECONDS). I am aware, that this has been discussed in #12830, which is closed - does this really work as intended?

### Additional context
We are using gRPC 1.24.2 at the moment.

**Comment by vjpai** [comment]
We intentionally chose not to use a backlog since that can lead to deadlocks. I discussed this in the context of the Ruby server in #8603 but it applies to C++ once you have a bounded limit. Since I don't really know Ruby well, the example that I gave in the comment section of how this can deadlock was in pseudo-C++.

**Comment by chrisse74** [comment]
Okay, thanks for your answer. I close the issue now as the backlog was omitted by design.
(I still think, that the reconnect-backoff is not working as it should, but I will have to retest it (eventually) and file a new ticket.)
