### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe error in gRPC Server

### ISSUE THREAD

**Issue by darcome** [grpc/grpc#21406]
### What version of gRPC and what language are you using?
C#, gRPC version: 2.25.0

### What operating system (Linux, Windows,...) and version?
Windows 10 1909

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET 4.72

### What did you do?
I simply called a function from my client to my server.

### What did you expect to see?
The result from my call.

### What did you see instead?
An RpcException with status "Cancelled". I then enabled logging on both client and server and from the server log I saw this message: 

```
W1206 09:25:28.059618 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occurred in the handler or an interceptor. System.IO.IOException: Failed to deserialize request message. ---> System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()
   --- End of inner exception stack trace ---
   at Grpc.Core.Internal.SliceMemoryManager.GetSpan()
   at System.Buffers.MemoryManager`1.get_Memory()
   at Grpc.Core.Internal.ReusableSliceBuffer.PopulateFrom(IBufferReader bufferReader)
   at Grpc.Core.Internal.DefaultDeserializationContext.PayloadAsReadOnlySequence()
   at Grpc.Core.Internal.DefaultDeserializationContext.PayloadAsNewBuffer()
   at Grpc.Core.Marshaller`1.EmulateContextualDeserializer(DeserializationContext context)
   at Grpc.Core.Internal.AsyncCallBase`2.TryDeserialize(IBufferReader reader, TRead& msg)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.ServerRequestStream`2.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__4.MoveNext()
W1206 09:25:28.065602 Grpc.Core.Server Exception while handling RPC. System.IO.FileNotFoundException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Grpc.Core.Internal.CallSafeHandle.StartSendStatusFromServer(ISendStatusFromServerCompletionCallback callback, Status status, MetadataArraySafeHandle metadataArray, Boolean sendEmptyInitialMetadata, SliceBufferSafeHandle optionalPayload, WriteFlags writeFlags)
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<Handl
```

The problem is that NuGet downloaded the latest version of the Unsafe assembly which is 4.7.0. Is this my error, NuGet error, or gRPC that has to update the version of Unsafe used?

Thanks in advance!

**Comment by jtattermusch** [comment]
Can you provide an example project that reproduces the problem?
It looks like you might have a wrong combination of dependencies in your project, but I have no idea how you arrived to that state.

**Comment by kgreed** [comment]
I solved this issue by copying dlls from my development machine. I am wondering if the problem is to do with [ [this question](https://stackoverflow.com/questions/61402207/why-does-azure-devops-change-the-date-on-dlls-downloaded-from-nuget)

**Comment by jtattermusch** [comment]
@JamesNK  could this be the same problem for which you have proposed a fix in different context (for protobuf)?

https://github.com/protocolbuffers/protobuf/pull/5888/files#diff-11e9fec2abed5e691748c15066e71c04R49
```
<!-- Needed for netcoreapp2.1 to work correctly. .NET is not able to load the assembly without this -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2"/>
  </ItemGroup>
```
Do you know what's the underlying issue for this being necessary?

**Comment by jtattermusch** [comment]
@darcome  @kgreed  we might have an idea for how to fix this, but I cannot reproduce the problem - can you provide a minimal reproduction which can be used to verify a potential fix?

**Comment by JamesNK** [comment]
> W1206 09:25:28.059618 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occurred in the handler or an interceptor. System.IO.IOException: Failed to deserialize request message. ---> System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Looks like an assembly binding issue.

You should add a redirect to your config file and see whether that fixes it.

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by vivainio** [comment]
I have got similar error from System.Buffers:

```
Grpc.Core.Server Exception while handling RPC. System.IO.FileLoadException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. 
```

These are caused by missing binding redirects. We have automatic binding redirection creation from Paket, but for some directories some redirects can be missing (esp. if you are not directly depending from Grpc.Core).

First fix should be to make this easier to diagnose, i.e. these should fail immediately when instantiating Grpc Server - and they should fail by explicit exception instead of seeing it only when handling a request when GRPC_VERBOSITY environment variable is set.

@jtattermusch should I create a new suggestion ticket for that?

**Comment by YanlongLi** [comment]
I got the same error on System.Buffers, should package `System.Buffers` be added as a nuget dependency of [Grpc.Core](https://www.nuget.org/packages/Grpc.Core/)
```
Type: System.IO.FileNotFoundException
Message: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
StackTrace:
    at Grpc.Core.Internal.CallSafeHandle.StartSendStatusFromServer(ISendStatusFromServerCompletionCallback callback, Status status, MetadataArraySafeHandle metadataArray, Boolean sendEmptyInitialMetadata, SliceBufferSafeHandle optionalPayload, WriteFlags writeFlags)
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__4.MoveNext()
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()
```

**Comment by vivainio** [comment]
@YanlongLi that wouldn't help. Problems is you don't have direct dependency to grpc and that's why your app.config is missing the binding redirects

**Comment by PaxHumana** [comment]
The issue that requires a redirect, seems to be a bad reference? Grpc.Core references System.memory 4.0.1.1 which references System.Buffers 4.0.3.0. But the Grcp.Core also directly reference System.Buffers 4.0.2.0

Grpc.Core 2.0.0.0
    │  │  ├──mscorlib 4.0.0.0
    │  │  ├──Grpc.Core.Api 2.0.0.0
    │  │  │  ├──mscorlib 4.0.0.0
    │  │  │  ├──System.Memory 4.0.1.1
    │  │  │  │  ├──mscorlib 4.0.0.0
    │  │  │  │  ├──System 4.0.0.0
    │  │  │  │  ├──System.Numerics.Vectors 4.1.4.0
    │  │  │  │  │  ├──mscorlib 4.0.0.0
    │  │  │  │  │  └──System.Numerics 0.0.0.0
    │  │  │  │  ├──System.Runtime.CompilerServices.Unsafe 4.0.4.1
    │  │  │  │  │  └──mscorlib 4.0.0.0
    │  │  │  │  └──System.Buffers 4.0.3.0
    │  │  │  │      └──mscorlib 4.0.0.0
    │  │  │  └──System.Core 4.0.0.0
    │  │  ├──System.Core 4.0.0.0
    │  │  ├──System 4.0.0.0
    │  │  ├──System.Memory 4.0.1.1
    │  │  │  ├──mscorlib 4.0.0.0
    │  │  │  ├──System 4.0.0.0
    │  │  │  ├──System.Numerics.Vectors 4.1.4.0
    │  │  │  │  ├──mscorlib 4.0.0.0
    │  │  │  │  └──System.Numerics 0.0.0.0
    │  │  │  ├──System.Runtime.CompilerServices.Unsafe 4.0.4.1
    │  │  │  │  └──mscorlib 4.0.0.0
    │  │  │  └──System.Buffers 4.0.3.0
    │  │  │      └──mscorlib 4.0.0.0
    │  │  └──**System.Buffers 4.0.2.0 -> 4.0.3.0**
    │  │      └──mscorlib 4.0.0.0

**Comment by jtattermusch** [comment]
I think nothing wrong with the references we define in Grpc.Core.csproj and Grpc.Core.Api.csproj

https://github.com/grpc/grpc/blob/014a2a0d54849fff795efbcb96b18416cbd7e189/src/csharp/Grpc.Core/Grpc.Core.csproj#L58
https://github.com/grpc/grpc/blob/014a2a0d54849fff795efbcb96b18416cbd7e189/src/csharp/Grpc.Core.Api/Grpc.Core.Api.csproj#L23

nowhere in those projects we reference `System.Buffers` directly as far as I can tell.

**Comment by daniol** [comment]
I had the same error but on on the gRPC client.
I have a gRPC client written as a C# DLL (.NET Framework 4.8). I call the DLL methods from a UI program.
Copying the "System.Runtime.CompilerServices.Unsafe.dll" to the output directory did not work. I solved the problem by adding the "System.Runtime.CompilerServices.Unsafe.dll" to the references of the main project (VS: Add reference -> Assemblies -> Extensions -> System.Runtime.CompilerServices.Unsafe.dll).
