### ISSUE TITLE
support to construct length-prefixed message at application layer

### ISSUE THREAD

**Issue by hicqu** [grpc/grpc#21424]
### Is your feature request related to a problem? Please describe.

Length-prefixed message is defined as
```
Length-Prefixed-Message → Compressed-Flag Message-Length Message
```

Currently it's constructed in grpc-core. However if we can construct it at application layer, grpc can be used in batch style: we can call `grpc_call_start_batch` to send many messages at once. Generally it helps to improve performance.

### Describe the solution you'd like

I want to add a new `WriteFlag`: `GRPC_WRITE_LENGTH_PREFIXED`.

With the flag, the `grpc_byte_buffer` passed in `grpc_call_start_batch` is encoded as repeated length-prefixed messages.

### Describe alternatives you've considered
We can also call `grpc_call_start_batch` many times with `buffer_hint=true`. But I think it still introduces more context switch because we need to fetch more tags back when calling `grpc_completion_queue_next`.

**Comment by hicqu** [comment]
PTAL @karthikravis thanks!
If you think it's ok to add the feature, it's my pleasure to help implementing it.

**Comment by vjpai** [comment]
I've commented in the PR, but my basic concern is that I'm not seeing that this is a substantial cost being avoided and would like to see that before adding API surface.
