### ISSUE TITLE
Wrong protoc binary is used when crosscompiling gRPC

### ISSUE THREAD

**Issue by hdoradu** [grpc/grpc#21422]
### What version of gRPC and what language are you using?
gRPC `v1.20.0` / C++

### What operating system (Linux, Windows,...) and version?
Linux (`ubuntu:latest` `docker` image)

### What runtime / compiler are you using (e.g. python version or version of gcc)
arm-none-linux-gnueabi-g++ (`crosstool-NG` crosstool-ng-1.23.0-42-gbae9ae2) 6.3.1 20170109

### What did you do?
```
$ cmake -DCMAKE_CROSSCOMPILING=1 \
        -DgRPC_BUILD_TESTS=OFF \
        -Dprotobuf_BUILD_TESTS=OFF \
        -DgRPC_BUILD_CSHARP_EXT=OFF \
        -DgRPC_SSL_PROVIDER=package \
        -DOPENSSL_INCLUDE_DIR=$OPENSSL_INSTALL_DIR/include/ \
        -DOPENSSL_CRYPTO_LIBRARY=$OPENSSL_INSTALL_DIR/lib/libcrypto.a \
        -DOPENSSL_SSL_LIBRARY=$OPENSSL_INSTALL_DIR/lib/libssl.a \
        -DRUN_HAVE_STD_REGEX=0 \
        -DRUN_HAVE_GNU_POSIX_REGEX=0 \
        -DRUN_HAVE_POSIX_REGEX=0 \
        -DRUN_HAVE_STEADY_CLOCK=0 \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_TOOLCHAIN_FILE="/build/toolchain.cmake" \
        ..
$ make
```
### What did you expect to see?
Successful `make` completion. 

### What did you see instead?
gRPC libs were cross-compiled, but it failed afterwards to run some tests:
```
[ 39%] Running gRPC C++ protocol buffer compiler on src/proto/grpc/status/status.proto
/bin/sh: 1: /work/grpc/.buildc/third_party/protobuf/protoc-3.7.0.0: Exec format error
CMakeFiles/grpc++_error_details.dir/build.make:63: recipe for target 'gens/src/proto/grpc/status/status.grpc.pb.cc' failed
make[2]: *** [gens/src/proto/grpc/status/status.grpc.pb.cc] Error 2
CMakeFiles/Makefile2:654: recipe for target 'CMakeFiles/grpc++_error_details.dir/all' failed
make[1]: *** [CMakeFiles/grpc++_error_details.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
Regardless if I set `protobuf` as `module` or `package`, it is trying to use the `cross-compiled` `protoc`, which cannot run on the `x64` machine, as it is made for `armv7`.
I set `CMAKE_CROSSCOMPILING=TRUE`, but this just pinpoints the proper `grpc_cpp_plugin` which I have compiled and install previously for `x64`. This flag is not used when setting the `protoc` path.

**Comment by jtattermusch** [comment]
FYI @KyleFromKitware  @zackgalbreath

**Comment by jtattermusch** [comment]
Looks like this will be addressed by the work in https://github.com/grpc/grpc/pull/21476.

**Comment by jtattermusch** [comment]
This should work now. https://github.com/grpc/grpc/pull/21476 Make sure to use the newest grpc release.
