### ISSUE TITLE
Flake: ios-test-interoptests testHijackingRemoteInterceptor

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#21426]
Test Case '-[InteropTestsRemote testHijackingInterceptor]' started.
<unknown>:0: error: -[InteropTestsRemote testHijackingInterceptor] : Asynchronous wait failed: Exceeded timeout of 32 seconds, with unfulfilled expectations: "Internal gRPC call completed.".
Test Case '-[InteropTestsRemote testHijackingInterceptor]' failed (32.210 seconds).

https://source.cloud.google.com/results/invocations/764aa1eb-d0d8-4aa5-a5f4-724e3ef14123/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-test-interoptests/tests

**Comment by muxi** [comment]
This was fixed by #22687
