### ISSUE TITLE
ares_android.h is not in a BUILD file

### ISSUE THREAD

**Issue by ipetr0v** [grpc/grpc#21437]
### What version of gRPC and what language are you using?
grpc-1.24.3

### What operating system (Linux, Windows,...) and version?
Debian 9

### What runtime / compiler are you using (e.g. python version or version of gcc)
Android Native Development Kit
`external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -target x86_64-none-linux-android`

### What did you do?
I'm using an Android Native Development Kit to compile gRPC for x86_64 with Bazel.
```bash
bazel build //examples/hello_world/client/android:client_app --fat_apk_cpu=x86_64
```

### What did you see instead?
I have got the following error:
```bash
ERROR: /root/.cache/bazel/_bazel_root/b6bc0828d5b43c7085b650e0698bf388/external/com_github_cares_cares/BUILD.bazel:109:1: C++ compilation of rule '@com_github_cares_cares//:ares' failed (Exit 1) clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -target x86_64-none-linux-android -fPIC ... (remaining 42 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_cares_cares/ares_library_init.c:34:10: fatal error: 'ares_android.h' file not found
#include "ares_android.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```
It looks like `ares_android.h` is not included as a header in a BUILD file:
https://github.com/grpc/grpc/blob/a12a8f0ce202f791521a39796840052c0861bec2/third_party/cares/cares.BUILD#L163-L189

### Anything else we should know about your project / environment?
Originated from https://github.com/project-oak/oak/issues/353

**Comment by ipetr0v** [comment]
Related to https://github.com/grpc/grpc/issues/19779
But here I cannot use `--crosstool_top //external:android/crosstool` since I'm using an Android NDK:
```bash
ERROR: /root/.cache/bazel/_bazel_root/b6bc0828d5b43c7085b650e0698bf388/external/androidndk/BUILD.bazel:41:1: in cc_toolchain_suite rule @androidndk//:toolchain-libcpp: cc_toolchain_suite '@androi
dndk//:toolchain-libcpp' does not contain a toolchain for cpu 'k8'
```

**Comment by ipetr0v** [comment]
I have created a PR https://github.com/grpc/grpc/pull/21463
But it looks like I can't assign labels. And it's required for the PR to be mergeable.

**Comment by ipetr0v** [comment]
I got the following tests failed:
- Basic Tests ObjC MacOS
- Bazel RBE Windows Opt C/C++

Not sure, how an additional header in a BUILD file could affect this.

**Comment by muxi** [comment]
@apolcyn - were you able to take a look on this, Alex?

**Comment by apolcyn** [comment]
Sorry for delay, I made a comment on the PR

**Comment by damonkey2** [comment]
Doesn't look like Ivan is around to respond to the comments on the PR. I've sent an equivalent one without the config settings check (which appears to be unnecessary as best I can tell). 

I too cannot add labels, @apolcyn any chance you can take a look? :)
