### ISSUE TITLE
gRPC python ; loading crashes as side effects

### ISSUE THREAD

**Issue by SebBlin** [grpc/grpc#21435]
### What version of gRPC and what language are you using?
This issue is related to Python and the module grpcio 1.25

pip list
Package    Version
grpcio     1.25.0 
pip        19.3.1 
setuptools 41.6.0 
six        1.13.0 
wheel      0.33.6 

### What operating system (Linux, Windows,...) and version?
I'm using python container 3.8 from GitHub
uname -a 
Linux 875ddf0303e3 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
python --version
Python 3.8.0

### What did you do?
I'm just trying to execute the following piece of code:
```
#import grpc

import ctypes as ct
lib_khiops = './libKhiopsNativeInterface.so'
_lib = ct.cdll.LoadLibrary(lib_khiops)

_lib.KNIOpenStream.argtypes = [ct.c_char_p, ct.c_char_p, ct.c_char_p, ct.c_char]
_lib.KNIOpenStream.restype = ct.c_int

def OpenStream(sDictionaryFileName: str, sDictionaryName: str, sStreamHeaderLine: str, cFieldSeparator: str) -> int:
    ct_DictionaryFileName = ct.c_char_p(sDictionaryFileName.encode())
    ct_DictionaryName = ct.c_char_p(sDictionaryName.encode())
    ct_StreamHeaderLine = ct.c_char_p(sStreamHeaderLine.encode())
    ct_FieldSeparator = cFieldSeparator[0].encode()
    print ('before')
    hStream = _lib.KNIOpenStream(ct_DictionaryFileName, ct_DictionaryName, ct_StreamHeaderLine, ct_FieldSeparator)
    print ('after: ', hStream)
    return hStream

ct_StreamHeaderLine = 'SepalLength	SepalWidth	PetalLength	PetalWidth	Class'
hStream = OpenStream('./data/ModelingIris.kdic', 'SNB_Iris', ct_StreamHeaderLine, '\t')
```

it works very well, unless I uncomment the first line that import gRPC !
then it crashes with the message:
```
double free or corruption (out)
Aborted
```
This occurs when executing the line `_lib.KNIOpenStream(...)`

It seams that loading just gRPC (even without using any of its features) has sides effects on loading other libraries.

Any help would be useful to correct this issue.

**Comment by lidizheng** [comment]
@SebBlin We might need your help to investigate this issue together. Can you try to run the application under MSAN or valgrind?

**Comment by SebBlin** [comment]
I can try but I don't know anything about MSAN or valgrind, 
Would you have any entry point or  tutorials to put me to the right direction?

**Comment by lidizheng** [comment]
A quick example of valgrind usage: http://cs.ecs.baylor.edu/~donahoo/tools/valgrind/
Wiki page for MSAN: https://github.com/google/sanitizers/wiki/MemorySanitizer

**Comment by lidizheng** [comment]
@SebBlin Alternatively, since this is a crash, `gdb` might be able to print the stack trace and identify the culprit object that being freed twice.

**Comment by SebBlin** [comment]
Thanks for the details.
I will need some time to setup the environnement and learn everything :-/

**Comment by Chrozayis** [comment]
I believe there's some syntax that was deprecated in 3.8. Look at the pip install log:
```
$ pip3 install grpc
Collecting grpc
  Using cached https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6b4jy_mr/grpc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6b4jy_mr/grpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-6b4jy_mr/grpc/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6b4jy_mr/grpc/setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "/tmp/pip-install-6b4jy_mr/grpc/grpc/__init__.py", line 6, in <module>
        from .rpc import *
      File "/tmp/pip-install-6b4jy_mr/grpc/grpc/rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by SebBlin** [comment]
At last, I was able to do additional tests with the guys that develop the library I'm including in the script. The library I tested first, integrates its own memory allocation functions. The developper built me a new release of this library that uses the standard memory allocation function; and there is no problem anymore.
Unfortunately, the code of this library is private so I can't share any gdb traces.

The good news is : I made it work, at last.
The bad news is : I don't understand what type of interactions between gcp and this library caused the crash...

I'm not used to create issues : should we close it ? or should we try to understand in deep what happened ?

**Comment by lidizheng** [comment]
@SebBlin Glad to hear that you found a fix. Usually, you could create a minimal reproduction case to let people in the community investigate. However, for your case, there is a high chance the bug hides in the memory allocation conflict (since gRPC Core also has its own version).

If we want to investigate, we need a repro. Otherwise, feel free to close this issue.

**Comment by gnossen** [comment]
@Chrozayis That's not actually our library. Our pypi package is `grpcio`, not `grpc`. See https://github.com/pypa/pypi-support/issues/3
