### ISSUE TITLE
hpack_encoder.cc sets END_STREAM flag on CONTINUATION frame

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#21436]
If a gRPC C++ server's trailers are large enough to be split over a HEADER frame plus subsequent CONTINUATION frames, C++'s implementation sets the END_STREAM flag on the final CONTINUATION frame rather than on the HEADER frame. This is a bug because HTTP/2 CONTINUATION frames do not have an END_STREAM flag (see [relevant section of the spec](https://http2.github.io/http2-spec/#CONTINUATION)); rather, then the END_STREAM should be set on the HEADERS frame itself (the lack of the END_HEADERS flag will let client's know that this really means the stream is over after the subsequent CONTINUATION frames are received). As-is, compliant client implementations will see that the HEADER frame received from a gRPC C++ server does not specify that it is end-of-stream, process the continuations, then dutifully wait (hang forever) until end-of-stream is received on another HEADERS frame that is not going to come.

This issue was reported by a user with a gRPC Java client and a gRPC C++ server ([original issue](https://github.com/grpc/grpc-java/issues/6484)). The reporter's [second comment](https://github.com/grpc/grpc-java/issues/6484#issuecomment-561998631) details the behavior of C++ here, including the lines of code responsible for this behavior.

**Comment by ejona86** [comment]
Why is this assigned to me? Just to make sure it is a correct change? I agree with @ericgribkoff's findings.

**Comment by karthikravis** [comment]
@ejona86 : The assignment was to get an assessment.

@yashykt : are you the right owner for chttp2?

**Comment by yashykt** [comment]
yes, i'm the right owner

**Comment by niejar** [comment]
Hello, any estimation for getting correction? This bug is impacting in our real product environment and we need to get correction (decent one) for it. Thank you.

**Comment by bocon13** [comment]
Hi everyone, I submitted a PR that fixes this issue: https://github.com/grpc/grpc/pull/22626

I've tested it in my environment and the client (golang in my case) no longer hangs. Please let me know if you have any feedback.

Thanks!
