### ISSUE TITLE
[Aio] Continuous performance benchmark

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#21448]
AsyncIO stack not only focus on plugging Python 3 features into gRPC, but also performance improvement. We have observed the prototype of AsyncIO stack produces great benchmark result. However, as we implementing more and more features, we might trade speed for simplicity / functionality. So, to keep better tracking how we are doing, we need a way to run continuous performance benchmark.

The baseline solution is joining OSS benchmark dashboard, but it doesn't allow us to add more items. Based on what customer are asking, we may need following additional numbers:

1. Maximum throughput measurement
2. Cold start latency measurement
3. Server streaming scenarios

@gnossen do you have more items to add?

**Comment by gnossen** [comment]
Latency and throughput with interceptors would be nice to have, but I don't think we currently have those numbers for even the sync stack.
