### ISSUE TITLE
[FLAKE] grpc_android timeout

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#21453]
Timed out after 3600 seconds.

https://source.cloud.google.com/results/invocations/bcea1762-f327-41f1-b60d-f184ffede28b/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_android/log

**Comment by jtattermusch** [comment]
This seem to be a very rare flake: based on the build history the jobs is very stable: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_android
