### ISSUE TITLE
Malloc aborts

### ISSUE THREAD

**Issue by mayureshnw** [grpc/grpc#21466]
### What version of gRPC and what language are you using?
1.18 C++

### What operating system (Linux, Windows,...) and version?
Centos 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Not sure how to reproduce it. We see it frequently enough to know its an issue but no clear way of reproducing this. 

### What did you see instead?
(gdb) bt
#0  0x00007f4107bf01f7 in raise () from /lib64/libc.so.6
#1  0x00007f4107bf18e8 in abort () from /lib64/libc.so.6
#2  0x00007f4109115388 in gpr_malloc () from /usr/local/lib/libgrpc.so.7
#3  0x00007f41091163bf in gpr_strdup () from /usr/local/lib/libgrpc.so.7
#4  0x00007f4109068a80 in grpc_error_string(grpc_error*) () from /usr/local/lib/libgrpc.so.7
#5  0x00007f410909987b in grpc_error_get_status(grpc_error*, long, grpc_status_code*, grpc_slice*, grpc_http2_error_code*, char const**) () from /usr/local/lib/libgrpc.so.7
#6  0x00007f410908b284 in ?? () from /usr/local/lib/libgrpc.so.7
#7  0x00007f4109071f9e in ?? () from /usr/local/lib/libgrpc.so.7
#8  0x00007f4109072207 in grpc_core::ExecCtx::Flush() () from /usr/local/lib/libgrpc.so.7
#9  0x00007f410908e005 in grpc_call_unref () from /usr/local/lib/libgrpc.so.7
#10 0x00007f41093fbe22 in grpc::ServerContext::~ServerContext() () from /usr/local/lib/libgrpc++.so.1
#11 0x00007f41093f8e5a in grpc::Server::SyncRequest::CallData::ContinueRunAfterInterception() () from /usr/local/lib/libgrpc++.so.1
#12 0x00007f41093fa0e2 in grpc::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) () from /usr/local/lib/libgrpc++.so.1
#13 0x00007f41093fe348 in grpc::ThreadManager::MainWorkLoop() () from /usr/local/lib/libgrpc++.so.1
#14 0x00007f41093fe4cc in grpc::ThreadManager::WorkerThread::Run() () from /usr/local/lib/libgrpc++.so.1
#15 0x00007f41091184ac in ?? () from /usr/local/lib/libgrpc.so.7
#16 0x00007f4107f85e25 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f4107cb334d in clone () from /lib64/libc.so.6
(gdb)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
The app runs in a centos:7 docker image. 
We run 2 servers and a client , each started in its own thread.
server1: handles unary rpc (<1 rpc/s)
server2: handles streaming rpc with writes and writes done. Each rpc has 50 messages. (20 rpc/s)
client1: sends a unary rpc.(4 rpc/s)

This issue is crashing the application at least once every 24 hours. Valgrind says no memory leaks. The docker container uses 30Mb of RAM at maximum, and has 8Gb of RAM allocated to it. 

Any help to resolve this would be greatly appreciated. 
Thank you.

**Comment by vjpai** [comment]
I think we really need additional information to hep repro this problem.
