### ISSUE TITLE
Wrong statuses delivered by C core in C# after backup poller was removed 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2146]
Already raised this before #1577 was merged, we agreed to address this soon, so filing a separate bug for this.

I ran some iterations of C# tests after #1577 was merged and it looks like the returned status codes for some of the calls are still getting mixed up from time to time. In unknown method handler tests, I sometimes receive "Unkown" status instead of "Unimplemented" and in some other tests, I sometimes get "cancelled" instead of "unknown".

I ran with -n 100 ( = 300 suites in total) and got 15 failures.

**Comment by jcanizales** [comment]
Seen again on Jenkins: https://grpc-testing.appspot.com/job/gRPC_pull_requests/308/config=opt,language=csharp,platform=linux/console (while testing unrelated #2211).

```
Errors and Failures:
1) Test Failure : Grpc.Core.Tests.ClientServerTest.UnknownMethodHandler
     Expected: Unimplemented
  But was:  Unknown

at Grpc.Core.Tests.ClientServerTest.UnknownMethodHandler () [0x00000] in <filename unknown>:0
```
