### ISSUE TITLE
verify_peer_callback ignored in SSL handshake

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc#21474]
Sorry for Posting this issue again, but I could not reopen #19845  and believe it has been closed due to a misunderstanding. The issue still persists in the Code and unfortunately, I am not proficient enough with the C-core to have an idea how to resolve this.

## What version of gRPC and what language are you using?
 1.22-2.25 / C#
 
### What operating system (Linux, Windows,...) and version?
 Windows 10 64bit
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET 4.7.2
 
### What did you do?

I would like to implement a client that can connect to servers that use self-signed certificates. Upon a connection, I would like to ask the user whether the server should be trusted. Recently, the `verify_peer_callback` that existed for ages in the C library has been exposed to C#, but it seems to be applied only after a successful SSL handshake. However, in my situation I would need to override the peer verification and handle it in user code, in order to accept connections to servers with self-signed certificates whose CA is unknown in advance.

I tested the Scenario with the following C# code, modifying the greeter example:

**Server**

```
var cacert = File.ReadAllText(@"..\ca.crt");
var servercert = File.ReadAllText(@"..\server.crt");
var serverkey = File.ReadAllText(@"..\server.key");
var keypair = new KeyCertificatePair(servercert, serverkey);
var sslCredentials = new SslServerCredentials(new List<KeyCertificatePair>() {keypair}, cacert, SslClientCertificateRequestType.DontRequest);
Server server = new Server
{
    Services = {Greeter.BindService(new GreeterImpl())},
    Ports = {new ServerPort("localhost", Port, sslCredentials)}
};
server.Start();
Console.WriteLine("Greeter server listening on port " + Port);
Console.WriteLine("Press any key to stop the server...");
Console.ReadKey();
server.ShutdownAsync().Wait();
```

**Client**
```
var cacert = File.ReadAllText(@"..\ca2.crt");
var clientcert = File.ReadAllText(@"..\client.crt");
var clientkey = File.ReadAllText(@"..\client.key");
var ssl = new SslCredentials(cacert, new KeyCertificatePair(clientcert, clientkey), VerifyPeer);
var channel = new Channel("localhost", 51000, ssl);
var client = new Greeter.GreeterClient(channel);
String user = "you";

var reply = client.SayHello(new HelloRequest {Name = user});
Console.WriteLine("Greeting: " + reply.Message);

channel.ShutdownAsync().Wait();
Console.WriteLine("Press any key to exit...");
Console.ReadKey();
```
The method `VerifyPeer` looks like this:
```
private static bool VerifyPeer(VerifyPeerContext context)
{
  return true;
}
```
A complete minimal example is here: https://github.com/georghinkel/grpc/commit/e0a625f5646f50df1161077671a4367b7d636d51

This also includes scripts to generate the self-signed certificates using openssl.
 
### What did you expect to see?
gRPC would call `VerifyPeer` in order to check whether a connection to the host should be established. Since the method is implemented to just return `true`, the connection should be established successfully.
 
### What did you see instead?

The script generates two client certificates, one with the same CA as the server and one that uses a different one. If I start the client using the same CA as the server, the verify peer callback is executed and allows me to fail the connection if I returned false. If the client uses a different CA, the verify_peer_callback is not executed but the connection fails before because the SSL handshake does not consider the callback.  

Instead, the following error message occurs:

> **Grpc.Core.RpcException**: 'Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")'   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 78

>    at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46

>    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Interceptors\InterceptingCallInvoker.cs:line 51

>    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174

>    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Interceptors\InterceptingCallInvoker.cs:line 48

>    at Helloworld.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions options) in C:\Projects\grpc\examples\csharp\Helloworld\Greeter\obj\Debug\netstandard1.5\HelloworldGrpc.cs:line 109

>    at Helloworld.Greeter.GreeterClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Projects\grpc\examples\csharp\Helloworld\Greeter\obj\Debug\netstandard1.5\HelloworldGrpc.cs:line 99

>    at GreeterClient.Program.Main(String[] args) in C:\Projects\grpc\examples\csharp\Helloworld\GreeterClient\Program.cs:line 34
> 

I put a breakpoint into the `VerifyPeer` method, but it has not been called. 

The trace is the following:

```
I1209 14:09:49.231985 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:178: handshake_manager 00000232C3F1BB20: calling handshaker security [00000232DC973300] at index 1
E1209 14:09:49.236540 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1246: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D1209 14:09:49.236650 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:186: Security handshake failed: {"created":"@1575896989.236000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I1209 14:09:49.237319 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:131: handshake_manager 00000232C3F1BB20: error={"created":"@1575896989.236000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"} shutdown=0 index=2, args={endpoint=0000000000000000, args=0000000000000000 {size=0: (null)}, read_buffer=0000000000000000 (length=0), exit_early=0}
I1209 14:09:49.238382 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:164: handshake_manager 00000232C3F1BB20: handshaking complete -- scheduling on_handshake_done with error={"created":"@1575896989.236000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

I also tried to install the server certificate or the CA in the Windows user certificate store as trusted root certificate but that didn’t help me to connect to the server. Currently, passing the server  CA as client CA seems the only option to connect to a server that uses a self-signed certificate.
 
### Anything else we should know about your project / environment?

Our intended usage of gRPC is for laboratory automation where each lab device would act as a SiLA2 server. SiLA2 is a protocol recently established for communication between laboratory devices and it uses gRPC for the transport layer. The standard requires servers to use TLS, but allows self-signed certificates. Of course, I can try to memorize the CA for each server, but I would like to get rid of this manual effort.

**Comment by georghinkel** [comment]
@akshayku I've seen you merged commits that disable certificate verification already. Is there some documentation how this functionality is exposed in the wrappers? Disabling certificate Validation would solve this issue as well.

**Comment by akshayku** [comment]
Disabling certificate verification right now is in experimental namespace and opt in. You will have to set [GRPC_TLS_SKIP_ALL_SERVER_VERIFICATION](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpc/grpc_security_constants.h#L129) in [TlsCredentialOptions](https://github.com/grpc/grpc/blob/e9665070b92962f860825f1a7c04a8f2d00bbd5c/include/grpcpp/security/tls_credentials_options.h#L288).

@yihuazhang for FYI.

**Comment by georghinkel** [comment]
@akshayku I haven't seen any usage of this enumeration in the repo, so how is this supposed to work?

Given that boringssl does provide an option to make certificate validation non-fatal, why not just using that one?

**Comment by georghinkel** [comment]
@akshayku I haven't seen any usage of this enumeration in the repo, so how is this supposed to work?

Given that boringssl does provide an option to make certificate validation non-fatal, why not just using that one?

**Comment by heinemml** [comment]
@georghinkel I figured how to call this API in C++ Code. Maybe that helps you a bit. 
But I still get the following error when trying to connect:

```
16: Invalid host localhost:50051 set in :authority metadata.
Greeter received: RPC failed
``` 

My modified greeter_client is here: https://gist.github.com/heinemml/ee95e21d6e1805d5702370cda6caf675

From searching through the grpc source it seems the hostname validation functions are still called on the client side. Maybe I'm holding it wrong...

**Comment by georghinkel** [comment]
@heinemml Thanks, I had a hard time trying to map that to C# and finally understood that the entire encryption is completely different. So far, I am using SSL but this is TLS. I thought the distinction would be somewhere at a lower level, but it is right below the surface already.

**Comment by amrmahdi** [comment]
@georghinkel were you able to create a channel with `GRPC_TLS_SKIP_ALL_SERVER_VERIFICATION`  in C#?

**Comment by georghinkel** [comment]
@amrmahdi No, encryption got deprioritized at our end because we use a separate network.

**Comment by JinsPeter** [comment]
Has anybody been able to skip SSL Validation?

**Comment by heinemml** [comment]
sadly no. But to be honest I didn't check for some time now. We are currently sticking with our "old" non-grpc solution where we can work with self-signed certs.

**Comment by giggiu16** [comment]
Hello, any update on this? Just tried with v1.35.x branch, and the problem reported by @heinemml still persists.

The behaviour I would like to implement is creating a secure TLS channel without checking for hostname inside the certificate (gRPC client&servers run in a local subnet but still need encryption to talk each other. There's no need to generate a certificate for each server, also because I don't know hostnames in advance).

**Comment by JinsPeter** [comment]
Hi,
There is a way to do something similar in C#  DotNET.
Use gRPC argument keys GRPC_SSL_TARGET_NAME_OVERRIDE to configure the
target name used by the certificate you use. Keys can be set up at the time
of channel instantiation as a ChannelOption using ChannelOptions parameter.

https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga218bf55b665134a11baf07ada5980825

**Comment by tudor-turcu** [comment]
Any news about this issue? 
We are using Grpc.Core .NET package, version="2.38.1", on .NET Framework 4.5-4.7 (Windows), and we have to offer the user the option to ignore certificate validation errors (mainly for self signed certificates), without having to install the server certificate on the client computer.
We don't have currently the option to upgrade to .NET Core and to the new Grpc .NET library.

**Comment by antibarbie** [comment]
@georghinkel same problem here, that library is our small-step-by-step-migration-path out of the doomed WCF technology, so we just CANNOT use .NET Core.

**Comment by antibarbie** [comment]
We worked this around this using a lame pre-connexion with bouncycastle, recovering the server's certificate and CN, adding the CN into the expected name, and the cert into the trusted roots of our GRPC Client...   One callback missing, and this is just hell !

**Comment by spowers225** [comment]
Any updates to this?

**Comment by georghinkel** [comment]
Sadly no, as I said earlier, encryption got deprioritized on our end since we have a separate, dedicated network. Furthermore, we extended the zeroconf handshake that we use to identify servers to additionally include the entire server certificate, if present. In addition, we use a target name override. With all of that in place, it works, but the chances that every server we come across implements this are practically zero, even though this got part of the laboratory automation standard we are working with.

**Comment by tudor-turcu** [comment]
Unfortunately the bug was closed by a .. bot, even if it's still valid.. :( It seems that Google has abandoned those that still must use .NET Framework instead of .NET Core.

**Comment by qfornaguera** [comment]
What I'm about to write is not a solution, but I recommend the use of gRPC debugging environment variables such as `GRPC_VERBOSITY=DEBUG` & `GRPC_TRACE=all` to get extra output information about what could be happening.

I don't know if there is really a bug but error reporting should be better at least 😮‍💨. "failed to connect all addresses" when what really happens is `Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED` because the certificate was expired (well if a cert in the chain is expired kinda makes sense that `verifyPeer` is skipped) or is `Security handshake failed: {"created":"@1699266693.176186000","description":"Cannot check peer: missing selected ALPN property.` because it required some ALPN extension configuration in the NLB side or client side(through headers), leaves you a bit stranded

Using the environment vars at least unblocked so I could turn to right fix/workaround. Hope this information helps to another helpless soul 🤞
