### ISSUE TITLE
C# Grpc Server-side streaming RPC. The client received the first message only with the second one (on Windows 7)

### ISSUE THREAD

**Issue by SLavaLL** [grpc/grpc#21484]
### What version of gRPC and what language are you using?
C# language, gRPC version 2.25.0

### What operating system (Linux, Windows,...) and version?
Windows 7 64-bit

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2017, .NetFramework 4.8

### What did you expect to see?
I am trying to implement server-side streaming rpc to send messages from server to client.
`rpc CheckSystem(CheckSystemRequest) returns (stream CheckSystemResponse) {}`

Server code:
```
public override Task CheckSystem(CheckSystemRequest request, IServerStreamWriter<CheckSystemResponse> responseStream, ServerCallContext context) {
  return Task.Run(async () => {
    for(int i = 1; i <= 10; i++) { 
      await responseStream.WriteAsync(new CheckSystemResponse { Type = i.ToString() });
      Console.WriteLine($"{DateTime.Now}: Sent {i}");
      Thread.Sleep(10000);
    }
  });
}
```

Client code:
```
public static async Task TestAsync() {
  try {        
    using (var call = client.CheckSystem(new CheckSystemRequest { Code = "1" })) {
      var responseStream = call.ResponseStream;
      while (await responseStream.MoveNext()) {
        var current = responseStream.Current;
        Console.WriteLine($"{DateTime.Now}: Received: Type = {current.Type}");
      }
    }
  }
  catch (Exception ex) {
    Console.WriteLine(ex.Message);
  }
}
``` 

After starting, I see that on the server side a message is sent every 10 seconds.
I expect that messages will be received on the client application immediately after sending from the server.

### What did you see instead?
The first message arrives at the client only after the second is sent from the server.
Server console output:

> 13.12.2019 **16:31:31**: Sent 1
13.12.2019 **16:31:41**: Sent 2
13.12.2019 16:31:51: Sent 3
13.12.2019 16:32:01: Sent 4
13.12.2019 16:32:11: Sent 5
13.12.2019 16:32:21: Sent 6
13.12.2019 16:32:31: Sent 7
13.12.2019 16:32:41: Sent 8
13.12.2019 16:32:51: Sent 9
13.12.2019 16:33:01: Sent 10

Client console output:

> 13.12.2019 **16:31:41**: Received: Type = 1
13.12.2019 **16:31:41**: Received: Type = 2
13.12.2019 16:31:51: Received: Type = 3
13.12.2019 16:32:01: Received: Type = 4
13.12.2019 16:32:11: Received: Type = 5
13.12.2019 16:32:21: Received: Type = 6
13.12.2019 16:32:31: Received: Type = 7
13.12.2019 16:32:41: Received: Type = 8
13.12.2019 16:32:51: Received: Type = 9
13.12.2019 16:33:01: Received: Type = 10

### Anything else we should know about your project / environment?

[Stackoverflow link](https://stackoverflow.com/questions/59323865/c-sharp-grpc-server-side-streaming-rpc-the-client-received-the-first-message-on)

**Comment by jtattermusch** [comment]
A few questions
How big is the message you're sending (how many bytes after being serialized)?
Does size of the message influence the behavior?
Do you see symmetric behavior on the client side? (when client streams the requests and server is on the receiving side).

**Comment by SLavaLL** [comment]
The message size is small - a few bytes. 
When I increase the size to 100kB, messages come immediately.
In client-side streaming RPC mode, this problem is not observed.

**Comment by jtattermusch** [comment]
@SLavaLL  thanks for the inputs. Can you provide a project that reproduces the problem? (there's probably something special about your setup, because I'd be surprised if we didn't catch a bug like this with our tests).

**Comment by SLavaLL** [comment]
I attached the RouteGuide project, taken from grpc.io with some changes, to reproduce the problem I indicated.
Now, in the console, I get the following result (the time of receipt of the first and second messages is the same):

> *** ListFeatures: lowLat=400000000 lowLon=-750000000 hiLat=420000000 hiLon=-7300
00000
17.12.2019 **18:34:00**, { "name": "Patriots Path, Mendham, NJ 07945, USA", "locatio
n": { "latitude": 407838351, "longitude": -746143763 } }
17.12.2019 **18:34:00**, { "name": "101 New Jersey 10, Whippany, NJ 07981, USA", "lo
cation": { "latitude": 408122808, "longitude": -743999179 } }
17.12.2019 18:34:05, { "name": "U.S. 6, Shohola, PA 18458, USA", "location": { "
latitude": 413628156, "longitude": -749015468 } }
17.12.2019 18:34:10, { "name": "5 Conners Road, Kingston, NY 12401, USA", "locat
ion": { "latitude": 419999544, "longitude": -740371136 } }

Sometimes it happens that messages go fine, but, in most cases, no.

[RouteGuide.zip](https://github.com/grpc/grpc/files/3974079/RouteGuide.zip)

**Comment by jtattermusch** [comment]
@SLavaLL  I've run the example you provided 10+ times but it always behaved correctly (one message delivered every 5 seconds), the first message never got delayed. I am running both apps locally on a Windows 10 machine.

**Comment by SLavaLL** [comment]
On a computer running Windows 10 and Windows Server 2016, applications run correctly. The problem is reproduced on a computer with Windows 7. Also, the problem is reproduced when the server part is running on Windows Server 2016, and the client part is running on Windows 7.

**Comment by jtattermusch** [comment]
Windows 7 is End of Life as of January 14 2020.
That means I don't have a good way of testing/reproducing this and it also probably means it's not really worth spending time on this. We haven't eliminated the possibility of this actually being a windows bug. If someone has a simple fix, we can consider integrating it.
