### ISSUE TITLE
NetBIOS name resolution doesn't work

### ISSUE THREAD

**Issue by Rantanen** [grpc/grpc#21496]
### What version of gRPC and what language are you using?
1.25 C++

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC

### What did you do?
Upgraded from vcpkg 1.18 to self compiled 1.25 and tried to connect to the local computer using its NetBIOS name instead of localhost.

### What did you expect to see?
Connection succeeds.

### What did you see instead?
Server not responding error.

### Anything else we should know about your project / environment?
The vcpkg to self compiled build change also ended up downgrading c-ares by few commits. Currently I'm using the official 1.15 c-ares release while vcpkg is using a later commit that isn't part of an official c-ares release (I believe the reason it's doing this is to fix Windows ARM builds) - looking at the commit log, I didn't see anything related to this.

I'm still in process of looking into this issue. The only place I can reproduce this currently is our integration test CI pipeline that uses virtual machines to execute the tests and which takes 11 hours to encounter the issue so I'm not 100% certain the report above is correct.

I believe this issue was reported earlier in #18411, but that one was closed after an unrelated fix.

**Comment by Rantanen** [comment]
### Currently I'm looking for comments on two different aspects:

- How can I disable c-ares in the CMake build? That issue seems to imply that using the native resolver acts as a workaround, but I'd prefer to be able to do that without environmental parameters.
- Are NetBIOS names supposed to work by default? If so, which side is responsible for resolving these: gRPC or c-ares?

**Comment by Rantanen** [comment]
The issue still exists when using c-ares.

As a workaround, compiling gRPC without c-ares solves the issue for us. With CMake this can be done with the following option: `-DgRPC_CARES_PROVIDER=none`

**Comment by yashykt** [comment]
@apolcyn Please check if there is an actionable item here.

**Comment by Rantanen** [comment]
> The issue still exists when using c-ares

Just to be clear this is to say we couldn't find a workaround with gRPC 1.25 that didn't involve disabling c-ares. I don't know if the issue still exists in more recent gRPC versions with c-ares.

**Comment by yashykt** [comment]
Thanks for the information, @Rantanen !

**Comment by anon17** [comment]
I have this issue and suspect that ares uses the wrong dns server: it can resolve httpbin.org just fine, but not lan hosts. I have two networks at home and they have their own dns servers, grpc doesn't log which dns server it uses. If I run the same code inside my company network, it resolves both netbios name and dns name (with domain suffix) on both windows and linux.

**Comment by apolcyn** [comment]
Closing this since there isn't any obvious path forward without adding support for netbios resolution in c-ares itself.

Workaround is to use the native DNS resolver, by setting env var `GRPC_DNS_RESOLVER=native`.

cc @yijiem
