### ISSUE TITLE
potential leak in xds failover edge case handling

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#21498]
See below for details.

Second comment in https://github.com/grpc/grpc/pull/19981#pullrequestreview-291849195

https://github.com/grpc/grpc/blob/d665f8359a84ca54db4e28cfdbf2f66197c28436/src/core/ext/filters/client_channel/lb_policy/xds/xds.cc#L1421

cc @markdroth

**Comment by markdroth** [comment]
This was addressed in #22117.
