### ISSUE TITLE
Make python unit tests run in parallel under run_tests.py

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#215]
run_python.sh has the line:

PYTHONPATH=third_party/protobuf/python python2.7_virtual_environment/bin/python2.7 -B -m unittest discover -s src/python -p '*.py'

I'm assuming this is globbing for python files containing unit tests - ideally PythonLanguage() in run_tests.py would do this, returning a list of python command lines to run. This would allow run_tests to execute these tests in parallel, reducing testing latency.

**Comment by ctiller** [comment]
I'm going to tackle this for Python today.

**Comment by nathanielmanistaatgoogle** [comment]
This objective is complete, right?

**Comment by ctiller** [comment]
Yes

**Comment by nathanielmanistaatgoogle** [comment]
Thanks.
