### ISSUE TITLE
grpc::GoogleDefaultCredentials() hangs

### ISSUE THREAD

**Issue by tmatsuo** [grpc/grpc#21501]
### What version of gRPC and what language are you using?

gRPC version: v1.26.0-pre1
language: c++

### What operating system (Linux, Windows,...) and version?

Debian Buster

### What runtime / compiler are you using (e.g. python version or version of gcc)

g++ (Debian 8.3.0-6) 8.3.0

### What did you do?

Create 3 files

Dockerfile
```Dockerfile
FROM debian:buster as devtools

ENV GOOGLE_APPLICATION_CREDENTIALS /home/service-account.json
ARG NCPU=4

# Dependencies
RUN \
  apt-get update && \
  apt-get -y install \
          autoconf \
          build-essential \
          clang-tidy \
          curl \
          gcc \
          git-core \
          g++ \
          libtool \
          make \
          pkg-config \
          vim

# Build source dependencies
RUN \
  cd /home/ && \
  git clone https://github.com/grpc/grpc.git && \
  cd grpc/ && \
  git checkout v1.26.0-pre1 && \
  git submodule update --init && \
  make -j ${NCPU} && \
  make install && \
  cd third_party/protobuf/ && \
  make -j ${NCPU} install && \
  ldconfig

from devtools as grpc-repro

COPY . /home/src
RUN cd /home/src && make
```

Makefile
```Makefile
CXX = g++
CPPFLAGS += -I/usr/local/include -pthread
CXXFLAGS += -std=c++11
LDFLAGS += -L/usr/local/lib `pkg-config --libs grpc++ grpc`       \
           -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed \
           -lprotobuf -lpthread -ldl

.PHONY: all
all: creds

creds: creds.o
        $(CXX) $^ $(LDFLAGS) -o $@

clean:
        rm -f *.o creds
```

creds.cc
```c++
#include <grpc++/grpc++.h>

int main() {
  auto creds = grpc::GoogleDefaultCredentials();
  return 0;
}
```

Build the Docker image:

```bash
$ docker build -t grpc-repro .
```

Run the Docker image:

```bash
$ docker run -t -i grpc-repro bash
```

Run the binary in the Docker container
```bash
# /home/src/creds
```

This program hangs indefinitely (or for a very long time).

### What did you expect to see?

This program just exits immediately.

### What did you see instead?

This program hangs indefinitely (or for a very long time).

### Anything else we should know about your project / environment?

It doesn't happen with gRPC version v1.25.0. With v1.25.0, the same program immediately exits.

When enabling GRPC_TRACE, it displayed the following:

```
root@34cbc3da3f59:/# /home/src/creds
D1217 22:54:47.710033257       6 ev_posix.cc:174]            Using polling engine: epollex
D1217 22:54:47.710392245       6 dns_resolver_ares.cc:503]   Using ares dns resolver
```

**Comment by yashykt** [comment]
This looks like the same issue as https://github.com/grpc/grpc/issues/21213
Please try using bazel instead

**Comment by tmatsuo** [comment]
@yashykt Thanks. FWIW, the program works as expected when building gRPC with cmake.

**Comment by yashykt** [comment]
Looks like there is nothing else to be done here. I'll be closing this issue now
