### ISSUE TITLE
dead cycle in trace.cc

### ISSUE THREAD

**Issue by jackleehunter** [grpc/grpc#21507]
### What version of gRPC and what language are you using?
Vesion 1.18.x
and protobuf is version 3.9.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04.9

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 5.4.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
My server is running, but dead cycle in trace.cc(TraceFlagList::Set() function) : 
code at line 57: for (t = root_tracer_; t; t = t->next_tracer_) , can't out this loop;

My code:
class PushClient{
public:
    PushClient() {}
    ~PushClient() {}
    CompletionQueue cq_;   // in here ,  it dead loop here when construct is mem object.
    ......
}

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
The issue has already been raised 
https://github.com/grpc/grpc/issues/21213#issuecomment-554944145
