### ISSUE TITLE
need update PHP example for docker

### ISSUE THREAD

**Issue by keyyuki** [grpc/grpc#21524]
I follow readme at /grpc/examples/php/echo but all file docker-compose use image 
```
grpc-php/base
```
that no longer existed in docker-hub, please check 
https://hub.docker.com/search?q=grpc-php%2Fbase&type=image

**Comment by stanley-cheung** [comment]
The `grpc-php/base` base image was never uploaded to docker hub. You need to build it by

```
$ cd examples/php/echo
$ docker build -t grpc-php/base -f ./base.Dockerfile .
```

Just like how the README says.
