### ISSUE TITLE
PHP: Undefined method call in release v1.26.0 from composer

### ISSUE THREAD

**Issue by javiermarinros** [grpc/grpc#21535]
Call to undefined method Grpc\ChannelCredentials::isDefaultRootsPemSet() at BaseStub.php:46

**Comment by jvdlaar** [comment]
Also the path to the roots.pem file doesn't seem to be correct https://github.com/grpc/grpc-php/commit/fbe451374df66e187792e5982a3564d97b3bb3c1#diff-63102fd921f3f50e769e3b53b2a0d051

**Comment by ZhouyihaiDing** [comment]
@javiermarinros, After upgrading the grpc php version to [v1.26.0](https://packagist.org/packages/grpc/grpc) in composer, have you upgraded the C extension to [1.26.0](https://pecl.php.net/package/gRPC/1.26.0)?

**Comment by ZhouyihaiDing** [comment]
@jvdlaar Thanks. Created https://github.com/grpc/grpc-php/pull/17

**Comment by stanley-cheung** [comment]
grpc/grpc-php#17 is merged. Thanks @ZhouyihaiDing 

I am creating an additional fix grpc/grpc-php#18 to not require PECL extension 1.26 to be upgraded simultaneously.

**Comment by stanley-cheung** [comment]
This should fixed.

There are 2 solutions:

1. If you haven't upgraded the PECL extension to version 1.26, you can pin the composer package `grpc/grpc` to version v1.25.0.

2. I have pushed an additional fix for the composer package `grpc/grpc` namely version `v1.26.1`, which will handle an older version of PECL extension more gracefully

**Comment by stanley-cheung** [comment]
Hm for some reason Packagist is not picking up the 1.26.1 release

**Comment by javiermarinros** [comment]
@ZhouyihaiDing I'm using the GRPC extension bundled with Google App Engine Standard environment: 1.19.0

I can't update it since the machines are fully managed from Google side.

I'll check if release 1.26.1 fixes the problem, thank you!
