### ISSUE TITLE
grpc doesn't work with gevent & flask (non gunicorn)

### ISSUE THREAD

**Issue by shaunakgodbole** [grpc/grpc#21533]
### What version of gRPC and what language are you using?
grpcio==1.23.0
flask==1.0.0
gevent==1.4.0
greenlet==0.4.15          # via gevent

### What operating system (Linux, Windows,...) and version?
Linux (Ubuntu 18)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7

### What did you do?
We have a simple flask server that is initialized using gevent.  A handler in the flask server uses grpc to connect to fetch some information from a grpc server.  Here are snippets to set up the gevent, grpc & flask servers:

*Monkey Patch the grpc requests* (Based on [gevent / grpc compatibility thread](https://github.com/grpc/grpc/issues/4629))
```
from gevent import monkey
monkey.patch_all()

import grpc._cython.cygrpc
grpc._cython.cygrpc.init_grpc_gevent()
```

*Initialize the flask server, grpc channels and stubs*
```
gevent_server = WSGIServer(('', port), wsgi_app)
opts = [(
        u'grpc.lb_policy_name',
        u'round_robin',
)]
channel = grpc.insecure_channel('localhost:9901', opts)
rpc_client = rpc_service_pb2_grpc.RpcServiceStub(channel)
gevent_server.serve_forever()
```

*Use the RPC client to invoke a method*
```
def get(self):
  logging.info('before request')
  resp, err = rpc_client.Method(request, timeout=20)
  logging.info('after request')
```

We run this entire setup on a kubernetes cluster.  The RPC server is set up as a headless service. 

### What did you expect to see?
The request executing successfully on the server, and 

### What did you see instead?
When running this setup locally, everything works as expected.

However, when we deploy this service to a kubernetes cluster, the request is never received by the grpc server.  Additionally, regardless of the timeout specified in the `rpc_client.Method`, the request always hangs.  Additionally looking at the rpc server logs, we don't see any request that gets received. 

This makes me believe that we are not even able to establish a channel / send a request.  

But, when I take out the grpc's gevent patching block:
```
import grpc._cython.cygrpc
grpc._cython.cygrpc.init_grpc_gevent()
```
everything works as expected.  We haven't tested it under load to actually see if other things break. 

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by lidizheng** [comment]
@shaunakgodbole I didn't spot any red flags in your code. We have tests running for gevent, so you might encountering some corner case here. Can you create a minimal repro case?

**Comment by shaunakgodbole** [comment]
@lidizheng I'll try to set up a minimal repro case for this.  Note that this will require pushing the changes to a kubernetes cluster (i'll provide the yamls as well). 

[This works completely fine on localhost which is what is confusing us.]

**Comment by shaunakgodbole** [comment]
I tried to create a minimal repro case over the weekend and deployed it on to a temporary kubernetes cluster.  However, the issue that I reported did not show up :(.  I'll try to see if I have missed anything.

**Comment by shaunakgodbole** [comment]
I was able to fix our issue though. 

In my previous repro, the `init_rpc_client` happens before the server has started.  The code block looks like following:
```
def init_rpc_client():
  <initialize rpc client>

init_rpc_client()

def start_and_serve():
  <start the server>
  server.serve()

if __name__ == '__main__':
  start_and_serve()
```

However, if I put the `init_rpc_client` method inside `start_and_serve` method, after `<start the serve>` candidate is done, the request seems to flow appropriately. 
```
```
def init_rpc_client():
  <initialize rpc client>

def start_and_serve():
  <start the server>
  init_rpc_client()
  server.serve()

if __name__ == '__main__':
  start_and_serve()
```

So I'm guessing if there is a race condition here.

**Comment by fraybabak** [comment]
I have this problem too. what  should I do. suppose I have flask app that is my main core . I need to have many microservices that connect to my flask app. so I decided to use grpc for handing those needs.

this is my entrypoint. index.py:

```
if __name__ == '__main__':
    GRPC()
    flask.run(app, port=os.environ.get('PORT'), host="0.0.0.0")
```

and this is my grpc server : 
```
stop_event = threading.Event()
def GRPC():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
    worker_pb2_grpc.add_WorkerGuideServiceServicer_to_server(Listener(), server)
    server.add_insecure_port("[::]:4010")
    try:
        server.start()
        LOG.debug("grpc server started at port : 4010")
        stop_event.wait()

    except Exception as e:
        LOG.error(f"ERROR on running grpc server: {e}")
        server.stop(0)
```
