### ISSUE TITLE
FLAKE: c_macos_dbg_native.bins/dbg/concurrent_connectivity_test fails with "Too many open files"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21534]
https://source.cloud.google.com/results/invocations/cfe84625-e024-46f3-b197-686dd5ae6285/targets/github%2Fgrpc%2Frun_tests%2Fc_macos_dbg_native/tests;group=c_macos_dbg_native;test=bins%2Fdbg%2Fconcurrent_connectivity_test%20GRPC_POLL_STRATEGY%3Dpoll;row=2

```
D1219 11:21:31.679461000 140735622603648 test_config.cc:384]           test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1219 11:21:31.680686000 140735622603648 ev_posix.cc:174]              Using polling engine: poll
D1219 11:21:31.680908000 140735622603648 dns_resolver_ares.cc:503]     Using ares dns resolver
D1219 11:21:31.681041000 140735622603648 concurrent_connectivity_test.cc:176] Wave 1
I1219 11:21:31.686913000 123145387610112 subchannel.cc:1003]           Connect failed: {"created":"@1576783291.686839000","description":"Failed to connect to remote host: Connection refused","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv6:[::1]:54321"}
I1219 11:21:31.687162000 123145387610112 subchannel.cc:1003]           Connect failed: {"created":"@1576783291.687124000","description":"Failed to connect to remote host: Connection refused","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:54321"}
I1219 11:21:31.687225000 123145386000384 subchannel.cc:942]            Subchannel 0x7f820b004cf0: Retry in 1001 milliseconds
E1219 11:21:31.826813000 123145409073152 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E1219 11:21:31.826867000 123145409073152 ev_poll_posix.cc:942]         pollset_work: {"created":"@1576783291.826846000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E1219 11:21:31.826887000 123145409073152 completion_queue.cc:1044]     Completion queue next failed: {"created":"@1576783291.826846000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E1219 11:21:31.826906000 123145433755648 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E1219 11:21:31.826907000 123145409073152 concurrent_connectivity_test.cc:77] assertion failed: grpc_completion_queue_next(cq, poll_time, nullptr).type == GRPC_OP_COMPLETE



*******************************
Caught signal SIGABRT
E1219 11:21:31.826958000 123145433755648 ev_poll_posix.cc:942]         pollset_work: {"created":"@1576783291.826939000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E1219 11:21:31.827094000 123145433755648 completion_queue.cc:1044]     Completion queue next failed: {"created":"@1576783291.826939000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E1219 11:21:31.827120000 123145433755648 concurrent_connectivity_test.cc:77] assertion failed: grpc_completion_queue_next(cq, poll_time, nullptr).type == GRPC_OP_COMPLETE
```

We already do increase ulimit at the start of the build:
```
+ source tools/internal_ci/helper_scripts/prepare_build_macos_rc
++ launchctl limit maxfiles
	maxfiles    256            unlimited      
++ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited
```

**Comment by jtattermusch** [comment]
Some c++ tests have failed for the same reason ("Too many open files") as well:
https://source.cloud.google.com/results/invocations/cfe84625-e024-46f3-b197-686dd5ae6285/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_dbg_native/tests

**Comment by yashykt** [comment]
Looks like we are running into system limits.
If that is indeed the case, then I can think of two solutions - 
1) Reducing the number of concurrent tests being run on the machine.
2) Increasing the system limit - Referring https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by jtattermusch** [comment]
@yashykt  how many concurrent connections does the test require and what's the reasoning behind that number? I understand it's supposed to test concurrent connectivity, but my guess is that the concurrently level chosen for the test is pretty much arbitrary (and we don't have a proof that setting the concurrency very high will increase the likelihood of detecting bugs).

1. Reducing the number of concurrent tests is kind of complicated (it can affect other stuff and can negatively impact the overall test latency) and whether we hit the issue or not also depends on the exact order of running the tests (which is pretty much random). Our lives would be much easier if we didn't have tests that look like unit tests but in fact consume too many resources to be runnable in parallel with other tests. So I'd be in favor or reducing parallelism in concurrent_connectivity_test (at least on Mac).

2. As mentioned above we already set the system limit and AFAIK its set to the maximum allowed value (I spent a lot of time experimenting with tweaking the system limits before and do not plan to do that again).

**Comment by jtattermusch** [comment]
@yashykt  how do I estimate the number of file descriptors needed to be concurrently open from the constants here? https://github.com/grpc/grpc/blob/d18b52f5db44b1bfae42a08b3622a0d9b3688fa2/test/core/surface/concurrent_connectivity_test.cc#L49?

**Comment by jtattermusch** [comment]
Btw, this failure could also be causes by interaction with other tests that require a lot of resources (
https://screenshot.googleplex.com/1bi0saYtpMs   shows thread_stress_test, client_channel_stress_test etc.)

**Comment by yashykt** [comment]
@jtattermusch You are right. The numbers chosen are arbitrary. The test itself has 100 threads, but just from that and the number of loop iterations we wouldn't know for sure whether those file descriptors can be reused in that short interval. A safe target would be a multiple of all of them I guess, but even then we would hit into issues with other tests running at the same time.

**Comment by jtattermusch** [comment]
@yashykt  btw, the  test currently fails in 65% of macos on master builds, so this is high priority item to fix.

From go/grpc-flaky (weekly data) It looks like on MacOS (which generally has less beefy testing machines that linux and windows) whenever  `concurrent_connectivity_test` fails, all of these tests fail as well:
sequential_connectivity_test
client_channel_stress_test
thread_stress_test --gtest_filter=End2endTest.ThreadStress

That probably means that one of these is true:
1. one of these tests is broken, consumes way more resources than normally and that causes also the other ones to fail
2. the test fail when they run concurrently because they all require a lot of resources.

**Comment by jtattermusch** [comment]
@yashykt 

from looking at a bunch of logs, it seems that `bins/dbg/sequential_connectivity_test` always runs first (before the the other tests) and when it runs out of  file descriptors, the other tests I mentioned (some of which run much later) also run of file descriptors pretty quickly as a result of that.

So my theory is that something is wrong with `sequential_connectivity_test` and when it fails it causes the other tests (it doesn't cleanup after itself?)

**Comment by yashykt** [comment]
Alright, I'll send out a PR to reduce the workload on OSX environments

**Comment by yashykt** [comment]
@jtattermusch When process exits, it should trigger cleaning up of its resources. The system itself might not be able to use those resources immediately, so as a temporary fix till we can better macos testing resources the reduced workload should help.

**Comment by jtattermusch** [comment]
On commit 659653d757d77cceef9ae8d5c15fb5fcd2a47a8b,
I'm able to easily reproduce the "too many open files problem" locally with:
`tools/run_tests/run_tests.py -l c -c dbg -r concurrent_connectivity_test` 
or `tools/run_tests/run_tests.py -l c -c dbg -r sequential_connectivity_test`

On commit 3fc71d29633961f080ff4e1c226fa5b7aa254969 (just after merging https://github.com/grpc/grpc/pull/21701/files),
I'm not able to reproduce anymore.

It seems that even after merging https://github.com/grpc/grpc/pull/21701, 
`client_channel_stress_test` and `thread_stress_test --gtest_filter=End2endTest.ThreadStress` are still failing - so they are probably caused by an unrelated problem.
