### ISSUE TITLE
Android xamarin: unexpected end of stream on when I call the service

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc#21545]
I have a project in which I have the service, the gRPC client in a sparate library and two clients that use this gRPC client library. One client is a WPF application and the other application is an android xamarin application.

When I do a call from my WPF applicartion, it warks, but when I try to call from my andriod application, I get the error unexpected end of stream on.

When I debug the android application, I am not using a virtual machine, but I am using a phone with android 8.0.

In the android application I configurate to requier internet access and network.

[GestorAplicaciones.zip](https://github.com/grpc/grpc/files/3992699/GestorAplicaciones.zip)

Thanks.

**Comment by yashykt** [comment]
Hi, from your description, it's hard to figure out whether you are looking for help debugging your project, or whether you are pointing to a bug within gRPC Core implementation itself.

If you are looking for help debugging your project, then a community like stackoverflow might be better suited to help. 

Cheers!

I will also cc @ericgribkoff if he has anything to add
