### ISSUE TITLE
trace message in executor.cc Line 146 need to be fixed

### ISSUE THREAD

**Issue by fadingsoul** [grpc/grpc#21549]
I think executor.cc Line 146 
      EXECUTOR_TRACE("(%s) SetThreading(true). curr_num_threads == 0", name_);
should be：
      EXECUTOR_TRACE("(%s) SetThreading(true). curr_num_threads > 0", name_);

**Comment by yashykt** [comment]
You are right. Thanks for pointing it out :)
https://github.com/grpc/grpc/pull/21560
