### ISSUE TITLE
examples/cpp/helloworld/greet_server hang up with 100% cpu usage

### ISSUE THREAD

**Issue by danielhongwoo** [grpc/grpc#21548]
### What version of gRPC and what language are you using?
* v1.26.0
* c++

### What operating system (Linux, Windows,...) and version?
* Linux, Ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
* g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

### What did you do?
```
git clone https://github.com/grpc/grpc.git
cd grpc
git checkout v1.26.0
git submodule update --init
cd examples/cpp/helloworld/
mkdir build
cd build
cmake -DGRPC_AS_SUBMODULE=ON -DBUILD_SHARED_LIBS=ON ..
make -j7
```

### What did you expect to see?
* helloworld example works fine.

### What did you see instead?
* helloworld example doens't work with 100% cpu usage on v1.26.0.
```
$ GRPC_VERBOSITY=debug GRPC_TRACE=api ./greeter_server
D1224 13:52:19.215704837   28805 ev_posix.cc:174]            Using polling engine: epollex
D1224 13:52:19.216050358   28805 dns_resolver_ares.cc:503]   Using ares dns resolver
<<< HANG UP for more than 5 minutes >>>
```
* but it works just fine on v1.25, v1.24

**Comment by yashykt** [comment]
This was fixed by #21662
