### ISSUE TITLE
[c++] exchange data between Interceptor and application

### ISSUE THREAD

**Issue by Ryan-Git** [grpc/grpc#21558]
### Is your feature request related to a problem? Please describe.
When implementing an interceptor, there's no easy way to pass some data down to the application or vise versa.

### Describe the solution you'd like
Add a map or a void* field into ServerContext.

### Describe alternatives you've considered
- Share a map between interceptor factory and application code. Use ServerContext* as key. But then each operation will go through this map.
- Add the interceptor instances into server context. It works in this scenario. But the solution above is more general.

### Additional context
version 1.26.0
async server with unary and bidi streaming rpc.

**Comment by yashykt** [comment]
Hi @Ryan-Git, that's an interesting suggestion.

As you described, syncing through the interceptor factory is one way of doing things.

Have you considered the alternative of adding the data as part of the metadata or the message?

**Comment by Ryan-Git** [comment]
Yes, but there're some data not suitable as metadata and message(which would pass through the network). For example, we'd like to pass the message received time to application code.

**Comment by yashykt** [comment]
To be clear, if the interceptors on the receive side add content as metadata or to the message, it would not go through the network.

Thinking about the void * solution, it would not be a general solution, since it would be a single field and if multiple interceptors want to make use of it, it would not work.

**Comment by Ryan-Git** [comment]
Happy new year :)

Modify message wouldn't go through network for sure, but it needs all messages containing the same field, which isn't acceptable in our case. 

How to add content as metadata? Use `GetRecvInitialMetadata` and add additional key to the returned map? This seems fine.

Application developer has full responsibility for this void *, so it can work. It could be better as a map of integer key to void*.

**Comment by yashykt** [comment]
Hi @Ryan-Git, the whole idea is that it might not be possible for an application to know what all interceptors are attached. For each interceptor to know which other interceptors exist and at which order they exist would be difficult. We could for sure provide a map and provide official semantics and ordering knowledge but that seems unnecessary given that there are other solutions to the problem.

**Comment by Ryan-Git** [comment]
Take servlet from java world as an example, there's `Object getAttribute(String)` and `void setAttribute(String, Object)` on `ServletRequest`.

The problem with `GetRecvTrailingMetadata` is the value has to be a `string_ref` which needs additional allocation in some cases.

**Comment by yashykt** [comment]
I understand the issue @Ryan-Git and I would very much like to provide a good solution for this.
The map as I said earlier would need the user to understand the order of interceptors, and if users are guaranteed to know the order, it would be easier to simply share the interceptor objects through the ServerContext. (I don't find this to be very clean either.)
The cleanest solution I can think of would be sharing data between the factory and the application.

@vjpai what do you think?
