### ISSUE TITLE
How to set connect timeout time when server is not avalible or blocked

### ISSUE THREAD

**Issue by charlesld** [grpc/grpc#21555]
### What version of gRPC and what language are you using?
python

### What operating system (Linux, Windows,...) and version?
linux debian 9 

### What runtime / compiler are you using (e.g. python version or version of gcc)

 python2.7

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

just lanuch a client with: 
1.  server not worked
2.  server worked , but firewall will drop server port sometimes
the client code like this.
```python
def run():
    start = time.time()
    try:
      with grpc.insecure_channel('172.20.22.12:5005') as channel:
          stub = helloworld_pb2_grpc.GreeterStub(channel)
          response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
      print("Greeter client received: " + response.message)
    except grpc._channel._Rendezvous as err:
      print("keepAlive check ping pong err in  %s  and caused by : %s"% ((time.time() - start) , err) )
```

result on   server not worked is 

```shell
# python greeter_client.py
keepAlive check ping pong err in  0.0137319564819 and caused by : failed to connect to all addresses
```
> cost only few ms and return

result on  server port dropped by firewall is 

![image](https://user-images.githubusercontent.com/23304239/71446921-bb8c4880-2763-11ea-9737-ea968681d08a.png)

> yea, cost 20 second and return

And I have done many tests, I  found that some extreme cases take 2 minutes to return or no return

### What did you expect to see?

How can  handle  this 20 seconds   to 2 seconds when a server is block by firewall, And I will do some action to release the firewall's interception.

### What did you see instead?
I read the channel params , but I found nothing .

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by charlesld** [comment]
@lidizheng   Hi, big master. help help help~~~

**Comment by charlesld** [comment]
And  I found , When the host Ip is not routeable  , the connection timeout is also 20 seconds.   
I have some apps  , that the interface will change dynamically， so the route will be  changed and grpc server will be unreachable in 20 ~ 30 second.   
I hope reduce the connection time  to 2second , thus, I can handle the other callbacks。

**Comment by charlesld** [comment]
By the test , I Found a channel arg ,`options=[("grpc.min_reconnect_backoff_ms",100)`,  can reduce the timeout time.    
So I change My code like this 

```python
def run():
    count = 0
    while True:
      start = time.time()

      try:
        with grpc.insecure_channel('172.16.22.12:50051',
                                   options=[("grpc.min_reconnect_backoff_ms",100)  ]) as channel:
            stub = helloworld_pb2_grpc.GreeterStub(channel)
            response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
        print("Greeter client received: " + response.message)
      except grpc._channel._Rendezvous as err:
        count +=1
        print("err in %s and caused by:  %s  and reconnect times : %s "% ((time.time() - start) , err.details(),count) )

```
But another unstable  case made me wonder.

![image](https://user-images.githubusercontent.com/23304239/71447977-e03aed00-2770-11ea-97f5-c1c60dd47bf0.png)


![image](https://user-images.githubusercontent.com/23304239/71448040-acac9280-2771-11ea-8b2e-724dc526a203.png)

![image](https://user-images.githubusercontent.com/23304239/71448059-dd8cc780-2771-11ea-9167-81302bd810f4.png)

where is the time 33 been set?

**Comment by charlesld** [comment]
emm. seem I found reason

a `tcp sync retries` time map was here. 
![image](https://user-images.githubusercontent.com/23304239/71497219-32bffa80-2892-11ea-8e8b-5167cea0689c.png)

SO , I change retry times to 2 , and  the uncontrol time was near 7
![image](https://user-images.githubusercontent.com/23304239/71497707-5ab05d80-2894-11ea-96e3-cb236c47d22a.png)

**Comment by lidizheng** [comment]
For keep-alive specific options, please take a look at https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L231. You can pass those channel argument as channel options (see https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_client_with_options.py).

The header file also contains more advanced flag that might help your application.

**Comment by charlesld** [comment]
@lidizheng  thx, I've already solved this problem, and  released online. Now seems  working stable.

![image](https://user-images.githubusercontent.com/23304239/72403481-1fb39280-378d-11ea-9c02-c7438cc67d07.png)

And dalao can give me your weixin?hhhhh. my  chat is `("a"+"d"*5+"oa")` in py.

**Comment by lidizheng** [comment]
Can you update the details about how you solved the problem? It might be helpful for people who will read this issue.

**Comment by ashley** [comment]
@charlesld Could you update this issue with how you solved the problem? I'm running into a similar problem even after setting up the Keep Alive and backoff configs.
