### ISSUE TITLE
c++ cross compiling grpc_cpp_plugin issue for raspberrypi

### ISSUE THREAD

**Issue by agudpp** [grpc/grpc#21551]
### What version of gRPC and what language are you using?
Latest version, compiling for c++

### What operating system (Linux, Windows,...) and version?
Linux ubuntu 16.04, but compiling for raspberrypi `arm-rpi-4.9.3-linux-gnueabihf`

### What runtime / compiler are you using (e.g. python version or version of gcc)
Toolchain from `https://github.com/raspberrypi/tools.git`
```
arm-linux-gnueabihf-gcc (crosstool-NG crosstool-ng-1.22.0-88-g8460611) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### What did you do?
I'm trying to compile for raspberrypi, I'm able to compile using a toolchain file that specify the compilers and extra flags and make parameters like 
```
export GRPC_CROSS_COMPILE=true
export GRPC_CROSS_AROPTS="cr --target=elf32-little"
# ...
CC=$RBP_TOOLCHAIN_FOLDER/bin/arm-linux-gnueabihf-gcc
CXX=$RBP_TOOLCHAIN_FOLDER/bin/arm-linux-gnueabihf-g++
RANLIB=$RBP_TOOLCHAIN_BIN_FOLDER/ranlib
LD=$RBP_TOOLCHAIN_FOLDER/bin/arm-linux-gnueabihf-gcc
LDXX=$RBP_TOOLCHAIN_FOLDER/bin/arm-linux-gnueabihf-g++
AR=$RBP_TOOLCHAIN_BIN_FOLDER/ar
STRIP=$RBP_TOOLCHAIN_BIN_FOLDER/strip
PROTOBUF_CONFIG_OPTS="--host=arm-linux-gnueabihf --with-protoc=$ONLINELOCK_DEP_DIR/bin/protoc"
#...
make install-pkg-config_cxx install-plugins install-shared_cxx install-headers_cxx VERBOSE=1 -j 8
```

### What did you expect to see?
I expect to be able to compile everything without errors... but

### What did you see instead?
I see that grpc is compiled and plugins as well, problem happens for the g++ libs, that use the `grpc_cpp_plugin`, but this plugin is compiled for arm and cannot run on my linux machine, so it fails. This is in `bins/opt/grpc_cpp_plugin`. If if hand-copy the binary compiled for linux (the `grpc_cpp_plugin`) and paste it there and then run again the compilation, it works and all the compilation ends correctly generating all the grpc++ libs.
I didn't find any way of setting this option as makefile parameter, maybe I miss something somewhere... will be good if we can specify the grpc_cpp_plugin as argument on the makefile

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
marking this as "help wanted" since we do not have resources to provide official support for raspberry pi

**Comment by michkrom** [comment]
This applies to any cross builds not just raspbery.

**Comment by yashykt** [comment]
Unfortunately, as far as I know, we do not have testing at the moment for any cross builds with C++.

**Comment by agudpp** [comment]
sorry delay, yes is a little tricky since you will have to separate all the toolings (i.e. compile them) for the host and using them when cross compiling for the target.
Fast solution would be to provide an optional argument (hence required in some cases) a path for the protoc + plugins (and all other required tools) from the host in addition to the compiler / linker / ar / etc. This would not work if the generated files (.cpp / .h) are platform dependent based on the compiler used (which I assume should not).

**Comment by advra** [comment]
Any updates on this? I am facing a similar issue for my repo.

**Comment by agudpp** [comment]
@advra I didn't tried anything else more than what I mentioned before, basically doing that hack (overwriting the host protoc with the target one)  will let you move forward

**Comment by patrickdepinguin** [comment]
See also following patch in Buildroot that allows specifying the path to a host version of grpc_cpp_plugin, for cross-compilation.
https://git.busybox.net/buildroot/tree/package/grpc/0001-target-build-using-host-plugin.patch
