### ISSUE TITLE
Using SslCredentials with non-null arguments is not supported by GrpcChannel

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc#21554]
I am trying to connect from a client to the service. The service is configurated to use a self signed Ssl certificate and I am trying to configurate the client with the client certificate. I am using this code:

```
string cacert = System.IO.File.ReadAllText("certificados/ca.crt");
string cert = System.IO.File.ReadAllText("certificados/client.crt");
string key = System.IO.File.ReadAllText("certificados/client.key");

KeyCertificatePair keypair = new KeyCertificatePair(cert, key);
SslCredentials sslCreds = new SslCredentials(cacert, keypair);

var channel = GrpcChannel.ForAddress("https://x.x.x.x:5001", new GrpcChannelOptions { Credentials = sslCreds });
var client = new Gestor.GestorClient(channel);
```

But I am getting the following error: using SslCredentials with non-null arguments is not supported by GrpcChannel.

I don't understand very good the message error. SslCredentials is ChannelCredentials? type, and SslCreds is Grpc.Core.SslCredentials. It can be compiled, so the type I guess it is correct.

What I would like to know it is how I can configure the client to use the self signed certificate that I have created.

Thanks.

**Comment by jtattermusch** [comment]
Answered here:
https://stackoverflow.com/questions/59229663/grpc-and-asp-net-core-using-sslcredentials-with-non-null-arguments-is-not-suppo

Also, GrpcChannel belongs to the "grpc-dotnet" codebase so this issues should filed in a wrong repository https://github.com/grpc/grpc-dotnet
