### ISSUE TITLE
Could not get default pem root certs.

### ISSUE THREAD

**Issue by MaksTech** [grpc/grpc#21556]
### What version of gRPC and what language are you using?
PHP PECL `php_grpc.dll` - v1.26.0 (tried also with v1.24 and v1.25)
`grpc-php` - v1.26.1

### What operating system (Linux, Windows,...) and version?
Windows 1909 (also happens on Mac 10.14 but haven't done much testing there but similar setup)

### What did you do?
Using with [Google Ads PHP library](https://github.com/googleads/google-ads-php), when using with composer `grpc` v1.26.1, leads to error. Setting version in composer explicitly to v1.25 or lower, fixes the issue. 
It happens with any PHP gRPC extension of versions (as far as I've tried) v1.24.0, v1.25.0, v1.26.0.

### What did you see instead?
This is response on Windows, but similar happens on Mac:
`E1226 20:40:50.775000000 17272 ssl_utils.cc:452] load_file: {"created":"@1577385650.775000000","description":"Fail
ed to load file","file":"ext\grpc\src\core\lib\iomgr\load_file.cc","file_line":71,"filename":"/usr/share/grpc/roots.pem","referenced_errors":[{"created":"
@1577385650.775000000","description":"No such file or directory","errno":2,"file":"ext\grpc\src\core\lib\iomgr\load_file.cc","file_line":45,"os_error":"No
 such file or directory","syscall":"fopen"}]}
E1226 20:40:50.810000000 17272 ssl_security_connector.cc:423] Could not get default pem root certs.
E1226 20:40:50.817000000 17272 secure_channel_create.cc:132] Failed to create secure subchannel for secure name 'googleads.googleapis.com:443'
E1226 20:40:50.832000000 17272 secure_channel_create.cc:50] Failed to create channel args during subchannel creation.
E1226 20:40:50.836000000 17272 ssl_security_connector.cc:423] Could not get default pem root certs.
E1226 20:40:50.841000000 17272 secure_channel_create.cc:132] Failed to create secure subchannel for secure name 'googleads.googleapis.com:443'
E1226 20:40:50.846000000 17272 secure_channel_create.cc:50] Failed to create channel args during subchannel creation.
`

**Comment by yashykt** [comment]
I believe the issue was fixed in https://github.com/grpc/grpc-php/pull/17

Please refer https://github.com/grpc/grpc/issues/21535 for more information
