### ISSUE TITLE
error: 'memcpy' was not declared in this scope   while compiling protobuf   in QNX  

### ISSUE THREAD

**Issue by SwapnilGiripunje** [grpc/grpc#21553]
In protobuf  file protobuf/src/google/protobuf/stubs/fastmem.h  
  
code are   as below : 
 
#ifndef GOOGLE_PROTOBUF_STUBS_FASTMEM_H_
#define GOOGLE_PROTOBUF_STUBS_FASTMEM_H_

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include<cstring>

#include <google/protobuf/stubs/common.h>

#include <cstring>
#include  <cstdio>
#include <cstdlib>

namespace google {
namespace protobuf {
namespace internal {

// Return true if the n bytes at a equal the n bytes at b.
// The regions are allowed to overlap.
//
// The performance is similar to the performance memcmp(), but faster for
// moderately-sized inputs, or inputs that share a common prefix and differ
// somewhere in their last 8 bytes. Further optimizations can be added later
// if it makes sense to do so.:w
inline bool memeq(const char* a, const char* b, size_t n) {
  size_t n_rounded_down = n & ~static_cast<size_t>(7);
  if (GOOGLE_PREDICT_FALSE(n_rounded_down == 0)) {  // n <= 7
    return memcmp(a, b, n) == 0;
  }
  // n >= 8
  uint64 u = GOOGLE_UNALIGNED_LOAD64(a) ^ GOOGLE_UNALIGNED_LOAD64(b);
  uint64 v = GOOGLE_UNALIGNED_LOAD64(a + n - 8) ^ GOOGLE_UNALIGNED_LOAD64(b + n - 8);
  if ((u | v) != 0) {  // The first or last 8 bytes differ.
    return false;
  }

 ### What version of gRPC and what language are you using?
         grpc-1.13x   ,c++ 

### What operating system (Linux, Windows,...) and version?
        QNX

### What runtime / compiler are you using (e.g. python version or version of gcc)
          compile time     , qnx  compiler   

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you see instead?

/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/repeated_field.h:1448:11: error: 'memcpy' was not declared in this scope
/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/repeated_field.h: In instantiation of 'void google::protobuf::internal::ElementCopier<Element, true>::operator()(Element*, const Element*, int) [with Element = long long int]':
/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/repeated_field.h:1430:37:   required from 'void google::protobuf::RepeatedField<T>::CopyArray(Element*, const Element*, int) [with Element = long long int]'
/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/repeated_field.h:1424:12:   required from 'void google::protobuf::RepeatedField<T>::MoveArray(Element*, Element*, int) [with Element = long long int]'
/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/repeated_field.h:1405:14:   required from 'void google::protobuf::RepeatedField<T>::Reserve(int) [with Element = long long int]'
/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/wire_format_lite_inl.h:381:5:   required from 'static bool google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive(google::protobuf::io::CodedInputStream*, google::protobuf::RepeatedField<T>*) [with CType = long long int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)16u]'
/home/sgiripunje/grpc-1.13.x/third_party/protobuf/src/google/protobuf/wire_format_lite_inl.h:416:1:   required from here

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
My first instinct was to redirect you to https://github.com/protocolbuffers/protobuf/issues since the issue seems to be when you are compiling protobuf, but it looks like that the issue might be more to do with the environment. 

I haven't worked with QNX so I won't be able to tell what's missing or if there are some other peculiarities. A wider community like stackoverflow might be better able to help.
