### ISSUE TITLE
Can we avoid memory bloat if many stubs created for same channel

### ISSUE THREAD

**Issue by codefever** [grpc/grpc#21563]
### What version of gRPC and what language are you using?
1.26.0

### What operating system (Linux, Windows,...) and version?
ubuntu18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

### What did you do?
In our client, we create new stubs with the same channel (pre-created). The resident memory of the program keeps going higher.

I make a simplified repo to reproduce this. Every time you press 'enter' for the client, you can see its memory goes higher.

> bazel-bin/client --times_for_once=1000000

https://github.com/codefever/grpc_leaks

### Anything else we should know about your project / environment?
I found that it's caused by `registered_calls` in the channel objects which are not released even when stubs are destructed.
![image](https://user-images.githubusercontent.com/1624981/71560026-8ce1db00-2a9f-11ea-9ab7-340fbb52d408.png)
![image](https://user-images.githubusercontent.com/1624981/71560034-a08d4180-2a9f-11ea-83df-55d468830b22.png)
![image](https://user-images.githubusercontent.com/1624981/71560041-b1d64e00-2a9f-11ea-88ac-c1ad01ef69f8.png)

**Comment by psylambda** [comment]
I found the same problem, and have to reuse stubs to bypass this problem. @yashykt

**Comment by vjpai** [comment]
It's not a leak. The methods registered on the channel will get freed when the channel is destructed. But if you create a new stub each time and reuse the same channel, it will be a long time until the memory is freed if the channel stays alive a long time. The best practice is to do what @psylambda said: reuse stubs. Best is to use 1 or a small constant # of stubs per channel per service.

**Comment by psylambda** [comment]
> It's not a leak. The methods registered on the channel will get freed when the channel is destructed. But if you create a new stub each time and reuse the same channel, it will be a long time until the memory is freed if the channel stays alive a long time. The best practice is to do what @psylambda said: reuse stubs. Best is to use 1 or a small constant # of stubs per channel per service.

@vjpai 
Can I use the same stub to send grpc requests in multiple threads concurrently?

**Comment by vjpai** [comment]
@psylambda Yes! Stubs are thread-safe. We should probably document this if it isn't already.

**Comment by vjpai** [comment]
This has hit several people over the years though so I think we can do this better.  The cool thing is that `grpc_channel_register_call` is only used by the C++ wrapping (Python etc just use `grpc_channel_create_call`) so we can just map from {method,host}->{registered_call} before adding things into the registered_call list.

**Comment by chrisse74** [comment]
Thanks for improving this @vjpai, we just stumbled over the same issue in our code. Will this be included in 1.28? :)
