### ISSUE TITLE
callOptions  GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS can not larger than kDefaultChannelDestroyDelay(30s)

### ISSUE THREAD

**Issue by danlanxiaohei** [grpc/grpc#21564]
### What version of gRPC and what language are you using?

v1.26.0 Objective-C

### What operating system (Linux, Windows,...) and version?
Mac

### What runtime / compiler are you using (e.g. python version or version of gcc)
xcode

### What did you do?
i use iOS device as a client , and golang as server, i start a bidirectional streaming call with 【additionalChannelArgs[@GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS] = [NSNumber numberWithInteger:60000];】, then cannel the call. After 30 seconds the connection disconnected.
### What did you expect to see?
i expect to see the connection disconnect after 60 seconds

### What did you see instead?
i saw the connection disconnect after 33 seconds

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

i debug it , and i found the connection disconnected because of the kDefaultChannelDestroyDelay [in GRPCChannelPool.m file]，the channel will aways destroy after kDefaultChannelDestroyDelay=30 seconds. so if the [GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS] is bigger than  kDefaultChannelDestroyDelay, it will not work!
<img width="662" alt="WeChatcd44dc2b12ca2a1c18736e29b99becf6" src="https://user-images.githubusercontent.com/3272530/71569578-12e73b80-2b0b-11ea-967f-03e304c050d4.png">
![WechatIMG5](https://user-images.githubusercontent.com/3272530/71578651-ff9c9600-2b33-11ea-96ee-7abb02861252.jpeg)

**Comment by danlanxiaohei** [comment]
@bigfacebear @hcaseyal @vjpai @AspirinSJL

**Comment by danlanxiaohei** [comment]
@srini100 Can you help?

**Comment by srini100** [comment]
@danlanxiaohei, feel free to submit a fix PR and tag @muxi. Folks are just trickling back in from holidays so this will take some time to address.

**Comment by muxi** [comment]
The idea of gRPC ObjC channel pool is that users are only to interact with calls but not channels. gRPC manages the channels, which has a 30s destroy delay after idle which cannot be changed at this moment. The option `additionalChannelArgs` exists more for the purpose of workaround issues with arguments not directly supported in ObjC layer but is supported in core. It's unfortunate and inevitable that such options from gRPC core allows you to control the channel behavior in some way, but that is not the intention of the ObjC wrapper.

**Comment by dennycd** [comment]
closing this ticket as no-op
