### ISSUE TITLE
Update Google.Protobuf version in Unity package 

### ISSUE THREAD

**Issue by Dig-Doug** [grpc/grpc#21571]
[Context](https://github.com/grpc/grpc/pull/21544)

I am using the grpc unity package in my project. I generate my C# protos outside of unity with bazel using the latest protoc/grpc versions and import them into my project. Recently, I ran into an issue where the generated code was not compatible with the latest grpc-unity package. Here's an example of the error I saw:

```
error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments
```

After some digging, I found that this [PR](https://github.com/protocolbuffers/protobuf/pull/5350) (and maybe others) changed the API of the generated code so the packaged Google.Protobuf version in the unity package is not compatible with code files generated with the latest code generation plugins.

Is it possible to update the unity package to use the latest versions?

Thanks for your help!

@jtattermusch

**Comment by jtattermusch** [comment]
I am planning to upgrade  protobuf in our repository soon, but for your use case, the only thing you need to do is to make sure that you're using compatible versions of `protoc`, `grpc_csharp_plugin` and the Google.Protobuf runtime.  This should be pretty easy to achieve.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/21590

**Comment by jtattermusch** [comment]
#21590 has been merged for a while, which should have fixed the problem.
