### ISSUE TITLE
Compile grpcio on Windows

### ISSUE THREAD

**Issue by hadim** [grpc/grpc#21591]
I am trying to compile grpcio for the [conda forge package](https://github.com/conda-forge/grpcio-feedstock) and I am running into an error for the Windows build:

```
  D:\bld\grpcio_1573021347641\_h_env\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DWIN32_LEAN_AND_MEAN=1 -DCARES_STATICLIB=1 -DGRPC_ARES=0 -DNTDDI_VERSION=100663296 -DNOMINMAX=1 -DMS_WIN64=1 -Isrc\python\grpcio -Iinclude -I. -Ithird_party\address_sorting\include -Ithird_party\cares -Ithird_party\cares\cares -I/usr\include\openssl -Ithird_party\upb -Isrc\core\ext\upb-generated -I/usr\include -ID:\bld\grpcio_1573021347641\_h_env\Library\include -ID:\bld\grpcio_1573021347641\_h_env\include -ID:\bld\grpcio_1573021347641\_h_env\include -c src\python\grpcio\grpc/_cython/cygrpc.cpp -o python_build\temp.win-amd64-3.6\Release\src\python\grpcio\grpc\_cython\cygrpc.o -std=c++11 /MT
    gcc: error: /MT: No such file or directory
```

Here is how the package is built: https://github.com/conda-forge/grpcio-feedstock/blob/master/recipe/bld.bat as indicated in your documentation.

Did the build system change for Python?

An internal issue has been opened on the google side according to https://github.com/grpc/grpc/issues/21217#issuecomment-566162822

Here is the relevant conda forge PR: https://github.com/conda-forge/grpcio-feedstock/pull/14

**Comment by lidizheng** [comment]
@hadim Thanks for trying to include `grpcio` into conda forge. `/MT` means statically link VC dll into your binary, can you check your version of Visual Studio on your CI? And make sure it matches corresponding Python interpreter version: https://wiki.python.org/moin/WindowsCompilers
