### ISSUE TITLE
proto_utils.h uses deprecated ByteSize API

### ISSUE THREAD

**Issue by awrichar** [grpc/grpc#21603]
When compiling grpc against a new version of protobuf (3.11.2), gcc complains that `ByteSize` is deprecated because it is used in `proto_utils.h`.

```
proto_utils.h:52:31: error: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Werror=deprecated-declarations]
```

Currently this can only be remedied by disabling the warning with `-Wno-deprecated-declarations`.

**Comment by itayzafrir** [comment]
I also stumbled upon this yesterday. 

grpc version 1.26.0 x64 on Windows 10 - installed via vcpkg.
using Visual Studio 2019 C++ console application.

Temporary workaround for this is to disable SDL Checks in the VS C++ project properties. But disabling SDL (which is enabled by default) has other implications.

**Comment by nicolasnoble** [comment]
@vjpai is there any reason we're still using this deprecated API?

**Comment by vjpai** [comment]
Nothing that I know of. I was wondering about this myself.

**Comment by nicolasnoble** [comment]
Alright, please approve #21827 then :)
