### ISSUE TITLE
grpc 1.26.0 , xcode archive with Error: Multiple commands produce gRPCCertificates.bundle

### ISSUE THREAD

**Issue by SarielTang** [grpc/grpc#21608]
Showing All Messages
Multiple commands produce '/Users/bluecity/Library/Developer/Xcode/DerivedData/Blued2015-hhuulvxsnatkqbacsxmghmgbczqq/Build/Intermediates.noindex/ArchiveIntermediates/Blued2015/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle':
1) Target 'gRPC-GRPCCore-Interface-Interface-Legacy-gRPCCertificates' has create directory command with output '/Users/bluecity/Library/Developer/Xcode/DerivedData/Blued2015-hhuulvxsnatkqbacsxmghmgbczqq/Build/Intermediates.noindex/ArchiveIntermediates/Blued2015/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle'
2) Target 'gRPC-gRPCCertificates' has create directory command with output '/Users/bluecity/Library/Developer/Xcode/DerivedData/Blued2015-hhuulvxsnatkqbacsxmghmgbczqq/Build/Intermediates.noindex/ArchiveIntermediates/Blued2015/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle'

**Comment by jiangguangpeng** [comment]
I also encountered this problem and found it in both 1.28.0 and 1.29.0
