### ISSUE TITLE
GRPC framework forces users to compromise their auth certs through file system

### ISSUE THREAD

**Issue by mcfly722** [grpc/grpc#21613]
Hello GRPC Team,
Im working on GRPC service (coded on Go) and I'm trying to use certificate for TLS authentication from Windows Cert Store.

Windows Cert Store is absolutelly essential, because file system (.pem/.key files) or any other method to store certificate with private key (database, json...) is unsecure.
When service would be compromised, private key could be easely stolen from file system or any other this kind certificate source.

Especially for that case, Microsoft involves separate Certificates store which has OS API without private key export/usage for non admin service accounts.

Also there are scenario when private key is located on USB token and OS have no access to it at all (only to encrypt/decrypt/sign API though USB).

Do you plan to envolve some stub for TLS encryption/decryption through OS API, or you have no such plans, and this GRPC framework could not be used in high security risk projects?

**Comment by jiangtaoli2016** [comment]
One possibility is to use OpenSSL Engine in gRPC.
@akshayku recently coded Engine supported in gRPC core and wrapped languages. https://github.com/grpc/grpc/pull/20316

It is not available in Go and Java -- since they use different code base.

**Comment by jiangtaoli2016** [comment]
The other possibility is use TLS handshaker service in gRPC. This is under development. Stay tuned for updates. @cesarghali  FYI
