### ISSUE TITLE
client_channel_stress_test timeouts under tsan and msan

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#21627]
https://source.cloud.google.com/results/invocations/0f6a36ca-9e32-4e25-87dd-2eb961fa4e29/targets/%2F%2Ftest%2Fcpp%2Fclient:client_channel_stress_test@poller%3Dpoll/log

https://source.cloud.google.com/results/invocations/eb057c9d-0432-475c-a788-fc1e316c550f/targets/%2F%2Ftest%2Fcpp%2Fclient:client_channel_stress_test@poller%3Dpoll/log

**Comment by jtattermusch** [comment]
https://source.cloud.google.com/results/invocations/50e29372-723a-45ce-acbe-9d9bab865a5a/targets/%2F%2Ftest%2Fcpp%2Fclient:client_channel_stress_test@poller%3Dpoll/log

**Comment by jtattermusch** [comment]
Who's looking into this and what's the plan?
Currently the test is failing 45% of tsan and of 45% msan on master for the past week. 

See the overview here:
https://screenshot.googleplex.com/O6r2C4okizU
go/grpc-flaky

**Comment by jtattermusch** [comment]
I've bisected this down to commit https://github.com/grpc/grpc/commit/5b18402914b97244020a462ce1a560669a7ccd4a
from https://github.com/grpc/grpc/pull/20803.

Manual reproduction
`bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=tsan //test/cpp/client:client_channel_stress_test@poller=poll --runs_per_test 10`

@markdroth  assigning to you. Please fix soon, this is our top bazel flake.

**Comment by yashykt** [comment]
seen again on #22615
Setting priority to P2

**Comment by jtattermusch** [comment]
Fixed by https://github.com/grpc/grpc/pull/22657
