### ISSUE TITLE
How to add Resolver Plugin to ObjC gRPC Client?

### ISSUE THREAD

**Issue by slavabulgakov** [grpc/grpc#21636]
### What version of gRPC and what language are you using?
1.24.2, Swift

### What operating system (Linux, Windows,...) and version?
iOS

### Question
Hi there!

I read (https://github.com/grpc/grpc/blob/master/doc/naming.md) it possible to add `Resolver Plugins` to gRPC client and do name resolution, but I cannot find any example for ObjC gRPC. I want to implement my own logic of DNS caching. Can I do it on ObjC gRPC Client? Are there any examples?

Apologise if this is not the right place to open this kind of issue. I have added question in Gitter chat and IRC, but there are no answers there yet.

**Comment by slavabulgakov** [comment]
I have found `Resolver Plugin` https://github.com/grpc/grpc/blob/477fc8068eb175c4f9fd8a903085a7b8c8a8bfe9/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L51 and the place where it is added https://github.com/grpc/grpc/blob/fa6920f601308f6e4f13831fa412818187c4add6/src/core/plugin_registry/grpc_plugin_registry.cc#L89. So as far as I understood there is only one way to add my own dns resolver is forking git@github.com:grpc/grpc.git. Am I right?

**Comment by IMelker** [comment]
I have the same question.
@slavabulgakov Did you manage to implement it this way?
