### ISSUE TITLE
How to check if the message has been posted from grpc library or not

### ISSUE THREAD

**Issue by udaykumar84** [grpc/grpc#21634]
Hi,
We are using streaming grpc-c++ service in our application. The grpc api module just returns if the message posting to GRPC queue is successful or not. We really dont have a way to check if the message has been really sent out of the sockets or not.
 
If the connection gets broken is there a way to check the below:
1) The message sent by application to the grpc message queue has it been sent out via the tcp socket or not ?
2) Api or way to check if any message are still been present in the grpc queue to be sent out or not ?
3) Api to retrieve the message which has not been sent out of the queue.
4) Api to check no of message present in the queue.

Please to let us know if any of the above is supported or any alternative methods are present.

Thanks,
uday

**Comment by karthikravis** [comment]
@udaykumar84 : Some follow up questions

The message sent by application to the grpc message queue has it been sent out via the tcp socket or not ?
>> Do you mean you want to know if the application message sent to gRPC client is successful or not? Your gRPC call will have a return status which will tell if the call was successful or not. That is the canonical way to know if the gRPC call succeeded/not.
Api or way to check if any message are still been present in the grpc queue to be sent out or not ?
Api to retrieve the message which has not been sent out of the queue.
Api to check no of message present in the queue.
>> These are internals and not exactly exposed to the application. I would suggest using the gRPC call status to know this information.

**Comment by udaykumar84** [comment]
Sorry for the delayed response !!! Thanks for the response !!! 
As per our understanding **"the gRPC call return status"** tells success or not for writing into the library not on wire.

But we want the status  of the stream if its has been sent out on the wire or not. 

Based on this after reconnect we can know if we are losing a message or not so that we can resend or not

Thanks,
uday
