### ISSUE TITLE
The Node build breaks with the latest core

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#21639]
When I tried to update the Node library to use the current version of the core in grpc/grpc-node#1232, the build fails with the following error:

```
gyp: Duplicate basenames in sources section, see list above
static library binding.gyp:grpc#target has several files with the same basename:
  http.upb: deps/grpc/src/core/ext/upb-generated/google/api/http.upb.c deps/grpc/src/core/ext/upb-generated/envoy/type/http.upb.c
libtool on Mac cannot handle that. Use --no-duplicate-basename-check to disable this validation.
```

I tried the suggested argument and it didn't help, and I expect that if it did, the Mac build would still have problems.

**Comment by markdroth** [comment]
I have no idea what you expect us to do about this.  These two files are generated from proto files in the google APIs repo and the xds repo, respectively.  We don't control either one and cannot dictate to them what filenames they use.  There is absolutely nothing wrong with them each having a filename called "http.proto".

I think this is something that needs to be solved in the node build system.

**Comment by murgatroid99** [comment]
@nicolasnoble has suggested that it may be possible to have `protoc` mangle the names of those files so that they do not collide like that.

**Comment by murgatroid99** [comment]
In addition, this is a known Mac issue that is not specific to the Node build tools/process. For example #5335 describes a time in 2016 when we broke the Mac core build by including two files with the same base name in different directories.

**Comment by murgatroid99** [comment]
Similarly, #5473 describes a more detailed warning message from libtool on Mac that was caused by files having the same base name.

**Comment by nicolasnoble** [comment]
> I have no idea what you expect us to do about this. These two files are generated from proto files in the google APIs repo and the xds repo, respectively. We don't control either one and cannot dictate to them what filenames they use. There is absolutely nothing wrong with them each having a filename called "http.proto".
> 
> I think this is something that needs to be solved in the node build system.

So, Mark, yes, there is something wrong with it: MacOS forbids it. We've been lucky so far, but that doesn't mean we can ignore the ticking time bomb.

**Comment by markdroth** [comment]
We still have no control over the filenames used by our dependencies.  You're welcome to try to convince one or both of them to change the name, but I don't think you're going to have much luck.
