### ISSUE TITLE
C# Build Task Custom Plugin Support

### ISSUE THREAD

**Issue by harrisse** [grpc/grpc#21637]
### Is your feature request related to a problem? Please describe.
I'd like to generate additional code beyond just what protoc-gen-grpc generates. I can't find a good way to do that with the existing C# build task.

### Describe the solution you'd like
I'd like to be able to specify additional custom plugin paths and output directories in the C# build task with the result getting appended to the protoc command that gets run (e.g. `protoc.exe --plugin=proto-gen-myplugin=./path/to/myplugin.exe --myplugin_out=./`)

**Comment by harrisse** [comment]
@kkm000 Tagging you based on https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#reporting-issues

**Comment by jtattermusch** [comment]
We don't have resources to work on this. Feel free to contribute or create your own version of Grpc.Tools package that supports this.
