### ISSUE TITLE
[Python] Make Response deserializer available in client-side interceptors

### ISSUE THREAD

**Issue by mcnamam** [grpc/grpc#21659]
### Is your feature request related to a problem? Please describe.
I am writing a client side unary-unary request interceptor as part of creating a gRPC->HTTP bridge (following guidelines [here](https://www.envoyproxy.io/docs/envoy/v1.9.1/configuration/http_filters/grpc_http1_bridge_filter)). 

This requires me to serialize the request message and deserialize the response message myself.
However there is currently no way to resolve the response deserializer from within an interceptor and I'm left with users of my interceptor channel having to deserialize every request themselves, like so:
```
channel = custom_http_bridge_channel(host="my-service.net")
stub = my_service_pb2_grpc.MyServiceStub(channel)
response = my_service_pb2.GetSomethingResponse.ParseFrom(
                     stub.GetSomething(my_service_pb2.GetSomethingRequest()))  
```

Within an unary-unary interceptor, the only variables available are:
- A continuation function
- A call details NamedTuple with method added by default
- The unserialized Request message object
(see intercept_unary_unary in [_interceptor.py](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_interceptor.py))

However in other languages like Go the interceptor receives a lot of other fields including unserialized Response message object. (See UnaryClientInterceptor in [interceptor.go](https://github.com/grpc/grpc-go/blob/04ea82009cdb9ecdefc6289f4c93ec919a10b3b6/interceptor.go))

### Describe the solution you'd like
I'd like users to be able to receive a deserialized response, like so:
```
get_something_response = stub.GetSomething(my_service_pb2.GetSomethingRequest())
```
To do this, I believe I'll need to be able to call the response deserializer from within an interceptor. That could be done by either passing in the response message itself, passing in the response deserializer, adding request serializer and response deserializer to the passed-in client_call_details, or something along those lines. 
In short, I'd like some way for interceptors like UnaryUnaryClientInterceptor to know how to deserialize responses for the input request.

### Describe alternatives you've considered
The response deserializer is available (albeit not in a straightforward way) in interceptor.py's `_UnaryUnaryMultiCallable` as `self._thunk(self._method)._response_deserializer`. However I have no way to access that from within `intercept_unary_unary` or force that to be called on the result of `intercept_unary_unary`.

### Additional context
Here is a modified sample of the interceptor I am developing:
```python
import asyncio
import grpc
import requests
from google.protobuf.message import Message as ProtoMessage
from struct import pack

def http_bridge_channel(host: str = "", req_headers: dict = None, options=None, compression=None) -> grpc.Channel:
    req_headers = {} if not req_headers else req_headers
    grpc_channel = grpc.insecure_channel(host, options=options, compression=compression)
    return grpc.intercept_channel(grpc_channel, _CustomGRPCRequestInterceptor(req_headers))


class _CustomGRPCRequestInterceptor(grpc.UnaryUnaryClientInterceptor):
    """
    Custom interceptor that is invoked on all requests on a channel to enable bridging gRPC request over HTTP
    """
    def __init__(self, req_headers: dict = None, host: str = ""):
        self.req_headers = req_headers
        self.host = host

    def intercept_unary_unary(self, continuation, client_call_details: grpc.ClientCallDetails = None, request: ProtoMessage = None):
        # ensure gRPC content type header is present
        self.req_headers.update({"Content-Type": "application/grpc"})
        request_url = "https://{host}{method}".format(host=self.host, method=client_call_details.method)
        try:
            service_response = requests.post(request_url=request_url, headers=self.headers, data=grpc_wrap(request.SerializeToString()))
            if service_response and service_response.ok:
                fut = asyncio.get_running_loop().create_future()
                fut.set_result(grpc_unwrap(service_response.content))
                return fut
            else:
                error_code = str(
                    service_response.status_code) if service_response else "(No response from service at {url})".format(
                    url=request_url)
                raise Exception("Request returned error code: {error_code}".format(error_code=error_code))
        except Exception as err:
            print("Exception calling service at {url}: ".format(url=request_url), err)


def grpc_wrap(request_bytes: bytes = None) -> bytes:
    """
    Adds gRPC header bytes to a given serialized request message.

    This is for envoy HTTP/1.1 bridges. It is structured like so:
        - 1 byte: zero (signaling no compressed)
        - 4 byte: proto message length (network order)
        -    ...: serialized proto message

    Arguments:
        request_bytes: A serialized protobuf request message (Message.SerializeToString())
    Returns:
        bytes: A byte array representing request payload for a gRPC over HTTP/1.1 bridge
    """
    payload_len_bytes = len(request_bytes)
    return pack('!cI', b'\0', payload_len_bytes) + request_bytes


def grpc_unwrap(response_bytes: bytes = None) -> bytes:
    """
     Strips the header added in grpc_wrap (first five bytes) from a given serialized response message.

     Arguments:
        response_bytes: A serialized response message (Response.content)
    Returns:
        bytes: A byte array representing an unwrapped gRPC response payload
    """
    if len(response_bytes) < 5:
        return None
    return response_bytes[5:]
```

**Comment by lidizheng** [comment]
@mcnamam Nice work for the HTTP/1.1 bridge! There is a quick solution. If you take a look at the generated stub file, you can see the method (aka. url) and proto message serializer / deserializer. You can craft your own stub object without serializers / deserializer (or with your own version), then you should be able to access the raw request data.

**Comment by lidizheng** [comment]
For Golang interceptors, the request and response object are `interface {}` but still proto messages. If you want to access unserialized message body, then the application might not using ProtoBuf. Did I miss something?

**Comment by mcnamam** [comment]
@lidizheng Thanks for the quick reply! 
I noticed that the generated service stub has all of the info I need but how do I access that from within the interceptor? Or if I crafted my own, how would the interceptor have access to that? 
My interceptor will be used by numerous different services so each one would need to pass in its stub.

**Comment by lidizheng** [comment]
To call different services (or even backends), you may be more than one stub object. You could create your own factory class to strip of serializers and deserializers. The interceptors will supply the request / response message to you as raw bytes.

**Comment by mcnamam** [comment]
Ok what I ended up doing was making a custom method that creates the service stub with interceptor attached and a map of stub_method - > response_deserializer, like so:
```
def grpc_stub(stub_module, host, options, compression):
    no_intercept_channel = auth_transport_grpc.secure_authorized_channel(credentials=None, request=None, target=host+":443")
    # need to make an instance of the stub with unintercepted channel in order
    # to have access to the stub's methods and serializers/deserializers
    no_intercept_stub = stub_module(no_intercept_channel)
    
    # create a dict from stub API method to associated response deserializer
    deserializers = {}
    stub_method_tuples = list(filter(lambda member: not member[0].startswith("__"), inspect.getmembers(no_intercept_stub)))
    for stub_method, method_handler in stub_method_tuples:
        deserializers[stub_method] = method_handler._response_deserializer
    
    interceptor = __GrpcRequestInterceptor(host=host, deserializers=deserializers)
    intercept_channel = grpc.intercept_channel(no_intercept_channel, interceptor)
    return stub_module(intercept_channel)
```
Then in the interceptor:
```
def intercept_unary_unary(self, continuation, client_call_details, request):
    request_url = "https://{host}{method}".format(host=self.host, method=client_call_details.method)
    try:
        service_response = requests.post(url=request_url, headers=headers, data=self.__grpc_wrap(request.SerializeToString()))
    except Exception as err:
         raise Exception("Exception calling service at {url}: {err}".format(url=request_url, err=err))

    if service_response is None:
        raise Exception("No response from service at {url}".format(url=request_url))
    elif service_response.ok:
        req_method = client_call_details.method.split("/")[-1]
        response_deserializer = self.deserializers.get(req_method)
        result = response_deserializer(self.__grpc_unwrap(service_response.content))
        fut = Future()
        fut.set_result(result)
        return fut
```

This allowed me to get the clean interface I wanted:
```
stub = grpc_stub(stub_module=my_service_pb2_grpc.MyServiceStub, host="my-service.net")
get_something_response = stub.GetSomething(my_service_pb2.GetSomethingRequest())
```

I think it would still be useful to have similar ability using the normal channel passed to stub constructor pattern but this works for now. 

Anyways thanks for your help!
