### ISSUE TITLE
GreeterClient greeter(grpc::CreateChannel(       "localhost:50051", grpc::InsecureChannelCredentials()))    hang

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [grpc/grpc#21666]
### What version of gRPC and what language are you using?
c++

### What operating system (Linux, Windows,...) and version?
CentOS Linux release 7.6.1810

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 8.3.1 20190311

### What did you do?
cd xxx/grpc/grpc/examples/cpp/helloworld/
./greeter_server &
./greeter_client

no output 

### What did you expect to see?
I add logs ,and find  GreeterClient hang 

```
  std::cout << "1" << std::endl;

  GreeterClient greeter(grpc::CreateChannel(
      "localhost:50051", grpc::InsecureChannelCredentials()));

  std::cout << "2" << std::endl;
```
 only "1" printed , 2 does not

**Comment by zhengxiaochuan-3** [comment]
greeter_server also hang,  no "Server listening on ...." print out

**Comment by yashykt** [comment]
Should be fixed after https://github.com/grpc/grpc/pull/21662
