### ISSUE TITLE
[FLAKE] tests.build_docker_javaokhttp

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#21675]
https://source.cloud.google.com/results/invocations/77155b58-1857-4b32-ac85-0a8354b81e0c/targets/github%2Fgrpc%2Finterop_docker_build/tests

**Comment by yashykt** [comment]
@jtattermusch do you know what's going on here?

**Comment by nicolasnoble** [comment]
I'm fairly certain this was resolved.
