### ISSUE TITLE
[FLAKE] end2end:xds_end2end_test

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#21674]
https://source.cloud.google.com/results/invocations/ca84c7f0-ea92-4629-bcbe-e88c60a05aef/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test/tests;group=XdsTest%2FBalancerUpdateTest;test=Repeated%2FXdsResolverWithLoadReporting;row=1

**Comment by jtattermusch** [comment]
Other occurrences:
https://source.cloud.google.com/results/invocations/1ababd5f-a2f7-48f1-881b-fc17f85465e2/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Depollex/log
https://source.cloud.google.com/results/invocations/1ababd5f-a2f7-48f1-881b-fc17f85465e2/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Depollex/log

**Comment by jtattermusch** [comment]
another failure: https://source.cloud.google.com/results/invocations/4c6733c8-c65b-43f5-92b5-dddf02b81822/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test/tests
