### ISSUE TITLE
About Certificates

### ISSUE THREAD

**Issue by Mankvis** [grpc/grpc#21718]
localhost.crt

localhost.key

Root.crt

How can I use OpenSSL to generate these three files? I hope I can give you a detailed command

Thank you.

**Comment by nicolasnoble** [comment]
This is way outside the scope of the sort of support we are willing to
offer here. That being said, there are lots of stackoverflow answers for
this already:

https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl
