### ISSUE TITLE
can grpc-python provide an api for loop socket message in client-side?

### ISSUE THREAD

**Issue by mnff** [grpc/grpc#21716]
As i know,  callback witch add by future's add_done_callback actually run in another thread，this does not work for me. I want to get the socket looper through an api so I can execute the callback in the appropriate thread, does this api already exist?

**Comment by lidizheng** [comment]
@mnff gRPC Python has a background thread which handles the communication between Python and C extension. Callbacks will be scheduled to that thread. And currently, we don't have an API for your usage.

However, in the callback, you can use Python `threading` module to delegate your work to another thread.

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question.
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.

**Comment by mnff** [comment]
> @mnff gRPC Python has a background thread which handles the communication between Python and C extension. Callbacks will be scheduled to that thread. And currently, we don't have an API for your usage.
> 
> However, in the callback, you can use Python `threading` module to delegate your work to another thread.

your suggestion is useful to me, thank you very much!

**Comment by mnff** [comment]
> @mnff gRPC Python has a background thread which handles the communication between Python and C extension. Callbacks will be scheduled to that thread. And currently, we don't have an API for your usage.
> 
> However, in the callback, you can use Python `threading` module to delegate your work to another thread.

@lidizheng your suggestion is useful to me, thank you very much!

**Comment by mnff** [comment]
> This issue is being closed because it has been marked with the label kind/question.
> Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.

@yashykt https://groups.google.com/g/grpc-io is 404
