### ISSUE TITLE
Error when building a sln project by cmake

### ISSUE THREAD

**Issue by For-thewin** [grpc/grpc#21726]
I am using the cmake to build a sln project. There is a error in the configure process.

CMake Error at cmake/cares.cmake:25 (add_subdirectory):
  The source directory
    /grpc-master/third_party/cares/cares
  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:191 (include)

So is there something wrong with my operation? Actully i just want to get the .lib and .plugin files such as "grpc_cpp_plugin.exe", then i want to run the helloworld demo.

**Comment by karthikravis** [comment]
@For-thewin : Have you tried the instructions here? https://github.com/grpc/grpc/blob/master/BUILDING.md

Windows, Using Visual Studio 2015 or 2017
When using the "Visual Studio" generator, cmake will generate a solution (grpc.sln) that contains a VS project for every target defined in CMakeLists.txt (+ few extra convenience projects added automatically by cmake). After opening the solution with Visual Studio you will be able to browse and build the code.

> @rem Run from grpc directory after cloning the repo with --recursive or updating submodules.
> md .build
> cd .build
> cmake .. -G "Visual Studio 14 2015"
> cmake --build . --config Release
If you want to build DLLs, run cmake with -DBUILD_SHARED_LIBS=ON.

Windows, Using Ninja (faster build).
Please note that when using Ninja, you will still need Visual C++ (part of Visual Studio) installed to be able to compile the C/C++ sources.

> @rem Run from grpc directory after cloning the repo with --recursive or updating submodules.
> md .build
> cd .build
> call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x64
> cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
> cmake --build .
If you want to build DLLs, run cmake with -DBUILD_SHARED_LIBS=ON.

**Comment by markdroth** [comment]
This hasn't seen a response from the reporter for months.  Closing.

**Comment by fhkong** [comment]
I use the grpc.io's method to install grpc from source code in ubuntu, but when I use cmake command, I broke a bug, which says " CMake Error at cmake/cares.cmake:25 (add_subdirectory)".
What can I do?

**Comment by NoWait126** [comment]
try this command in the grpc code repository ` git submodule update --init` , 
then try your `cmake` command  again

**Comment by XR-stb** [comment]
> 

It didn't work. I made the same mistake.

```
xiaoran@LAPTOP-V1TAJVBV:~/cpp_project/grpc$ git submodule update --init
xiaoran@LAPTOP-V1TAJVBV:~/cpp_project/grpc$ cd cmake/build/
xiaoran@LAPTOP-V1TAJVBV:~/cpp_project/grpc/cmake/build$ cmake ../../
CMake Warning at cmake/abseil-cpp.cmake:30 (message):
  gRPC_ABSL_PROVIDER is "module" but ABSL_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:318 (include)


CMake Error at cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /home/xiaoran/cpp_project/grpc/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:321 (include)


CMake Warning at cmake/protobuf.cmake:51 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:322 (include)


CMake Warning at cmake/re2.cmake:41 (message):
  gRPC_RE2_PROVIDER is "module" but
  RE2_ROOT_DIR(/home/xiaoran/cpp_project/grpc/third_party/re2) is wrong
Call Stack (most recent call first):
  CMakeLists.txt:323 (include)


CMake Warning at cmake/ssl.cmake:55 (message):
  gRPC_SSL_PROVIDER is "module" but BORINGSSL_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:324 (include)


CMake Warning at cmake/zlib.cmake:39 (message):
  gRPC_ZLIB_PROVIDER is "module" but ZLIB_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:327 (include)


-- Checking for module 'libsystemd>=233'
--   No package 'libsystemd' found
-- Configuring incomplete, errors occurred!
See also "/home/xiaoran/cpp_project/grpc/cmake/build/CMakeFiles/CMakeOutput.log".
See also "/home/xiaoran/cpp_project/grpc/cmake/build/CMakeFiles/CMakeError.log".
```
