### ISSUE TITLE
Ruby GRPC client cannot retrieve streaming response

### ISSUE THREAD

**Issue by MengChan32119** [grpc/grpc#21732]
### What version of gRPC and what language are you using?
grpc version 1.26.0, ruby 2.5.5

### What operating system (Linux, Windows,...) and version?
 Centos 7 Kernel 4.20.5-1.el7.elrepo.x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby version 2.5.5, grpc version 1.26.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I use deadline TimeConsts::INFINITE_FUTURE on etcdv3-ruby client for watch some key,ruby client cannot get any events update after the connection have been idle for several hours, There is no error occur and etcd service is up and running. when using golang etcd client have not happen same case.

### What did you expect to see?

I expect client get new events after the connection have been idle for several hours.

### What did you see instead?
ruby etcdv3 client
![ruby](https://user-images.githubusercontent.com/59998876/72787102-3153d900-3c6a-11ea-86b9-95cab7ec568c.png)

golang etcdv3 client
![golang](https://user-images.githubusercontent.com/59998876/72787107-32850600-3c6a-11ea-8c2e-8e8aba17686a.png)

### Anything else we should know about your project / environment?
my project run on Kubernetes version 1.13.

**Comment by nicolasnoble** [comment]
This originally was assigned as a "Ruby" issue, but I feel this isn't specific to Ruby. This requires investigation. Maybe @apolcyn could give it a go too just to make sure this isn't Ruby specific?

**Comment by markdroth** [comment]
This might be a case where keepalives need to be enabled.

**Comment by alto-ruby** [comment]
@MengChan32119, is this still an issue?
FYI for details about keep alive, please refer to https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Comment by alto-ruby** [comment]
Assume this is keepalives issue, closing. Feel free to reopen if otherwise.
