### ISSUE TITLE
Program hangs when creating instance of grpc::Server

### ISSUE THREAD

**Issue by sveinung-r** [grpc/grpc#21759]
Program hangs when creating instance of grpc::Server. 

Code works fine with version 1.25, but hangs on version 1.26. 

Debugger output shows that program is stuck in grpc_core::TraceFlagList::Set(char const*, bool). 

CPU usage for the process is 100% suggesting that this might be some sort of infinite loop.

**Comment by veblush** [comment]
It's already fixed on HEAD, 1.27x, and 1.26.x branches. (but not in 1.26.0 tag)

**Comment by jaakristioja** [comment]
@veblush Can You please tell in which commit(s) this was this fixed in? I think I'm seeing this issue with 1.27.2 as well.
