### ISSUE TITLE
[FLAKE] Failed to create Google credentials grpc_bazel_cpp_ios_tests

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#21776]
This test build is failing continuously on master

```
E0123 05:56:54.259514000 4512646016 google_default_credentials.cc:349] Could not create google default credentials: {"created":"@1579787814.256563000","description":"Failed to create Google credentials","file":"src/core/lib/security/credentials/google_default/google_default_credentials.cc","file_line":283,"referenced_errors":[{"created":"@1579787814.256620000","description":"creds_path unset","file":"src/core/lib/security/credentials/google_default/google_default_credentials.cc","file_line":226},{"created":"@1579787814.256823000","description":"Failed to load file","file":"src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"/Users/kbuilder/Library/Developer/CoreSimulator/Devices/A86DE087-1214-4F19-9F53-DBB6540A7838/data/.config/gcloud/application_default_credentials.json","referenced_errors":[{"created":"@1579787814.256818000","description":"No such file or directory","errno":2,"file":"src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}]}
```

The issue looks like a credential-not-found issue. From the fusion log, it might caused by https://github.com/grpc/grpc/pull/21766 (@yihuazhang). If I'm wrong, feel free to reassign to me.

https://source.cloud.google.com/results/invocations/ff3b2138-8161-4739-8128-ff870b39a751/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_bazel_cpp_ios_tests/log

**Comment by yihuazhang** [comment]
F.Y.I. @matthewstevenson88
I think the problem is caused by `LoadTlsServerCredentials` added in  #21766. Please revert the PR.

**Comment by matthewstevenson88** [comment]
Thanks @lidizheng and @yihuazhang! I've reverted the PR in #21778

**Comment by matthewstevenson88** [comment]
After rolling back the PR #21778, we've discovered that the root cause of this failure was really [Issue #20311](https://github.com/grpc/grpc/issues/20311). For that reason, a new PR #21804 has been posted with the TLS credential changes and I will be merging it back in now.
