### ISSUE TITLE
gRPC C++ with Ninja does not build on windows

### ISSUE THREAD

**Issue by noahdav** [grpc/grpc#21782]
### What version of gRPC and what language are you using?
latest master (commit https://github.com/grpc/grpc/commit/214fd8822bc86d50b4900743757b85d0b17780f4)

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64 

### What did you do?
I followed the instructions from https://github.com/grpc/grpc/blob/master/BUILDING.md

cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
cmake --build .

### What did you expect to see?
Successful build

### What did you see instead?
Build failed

```
..\include\grpcpp/server_impl.h(353): note: see reference to class template instantiation 'std::shared_ptr<grpc_impl::Server::GlobalCallbacks>' being compiled
[2027/2072] Building CXX object third_party\boringssl\tool\CMakeFiles\bssl.dir\transport_common.cc.obj
FAILED: third_party/boringssl/tool/CMakeFiles/bssl.dir/transport_common.cc.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DBORINGSSL_IMPLEMENTATION -DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -D_STL_EXTRA_DISABLED_WARNINGS="4774 4987" -D_WIN32_WINNT=0x600 -D_WINSOCK_DEPRECATED_NO_WARNINGS -I..\third_party\boringssl\third_party\googletest\include -I..\third_party\boringssl\tool\..\include -utf-8 -Wall -WX  -wd4061 -wd4100 -wd4127 -wd4200 -wd4204 -wd4221 -wd4242 -wd4244 -wd4267 -wd4371 -wd4388 -wd4296 -wd4350 -wd4365 -wd4389 -wd4464 -wd4510 -wd4512 -wd4514 -wd4548 -wd4610 -wd4623 -wd4625 -wd4626 -wd4628 -wd4668 -wd4706 -wd4710 -wd4711 -wd4800 -wd4820 -wd5026 -wd5027 -wd5045  -w44265 /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fothird_party\boringssl\tool\CMakeFiles\bssl.dir\transport_common.cc.obj /Fdthird_party\boringssl\tool\CMakeFiles\bssl.dir\ /FS -c ..\third_party\boringssl\tool\transport_common.cc
..\third_party\boringssl\tool\transport_common.cc(19): error C2220: warning treated as error - no 'object' file generated
..\third_party\boringssl\tool\transport_common.cc(19): warning C4005: '_SCL_SECURE_NO_WARNINGS': macro redefinition
..\third_party\boringssl\tool\transport_common.cc(19): note: command-line arguments:  see previous definition of '_SCL_SECURE_NO_WARNINGS'
[2036/2072] Building CXX object third_party\boringssl\ssl\CMakeFiles\ssl_test.dir\ssl_test.cc.obj
ninja: build stopped: subcommand failed.
```

Looking in the CMakeError.log it looks like pthread.h is not found.

Determining if the include file pthread.h exists failed with the following output:
```
Change Dir: E:/src/grpc/.build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/ProgramData/chocolatey/bin/ninja.exe cmTC_397aa && [1/2] Building C object CMakeFiles\cmTC_397aa.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_397aa.dir/CheckIncludeFile.c.obj 

C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /wd4065 /wd4506 /wd4200 /wd4291 /wd4244 /wd4267 /wd4987 /wd4774 /wd4819 /wd4996 /wd4619  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_397aa.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_397aa.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.
```

### Anything else we should know about your project / environment?
Instead of using %VS140COMNTOOLS%..\..\VC\vcvarsall.bat I tried to use vs 2017 (19.16.27034) and it also failed but made it a little further

```
[2036/2072] Building CXX object third_party\boringssl\tool\CMakeFiles\bssl.dir\transport_common.cc.obj
FAILED: third_party/boringssl/tool/CMakeFiles/bssl.dir/transport_common.cc.obj
C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DBORINGSSL_IMPLEMENTATION -DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -D_STL_EXTRA_DISABLED_WARNINGS="4774 4987" -D_WIN32_WINNT=0x600 -D_WINSOCK_DEPRECATED_NO_WARNINGS -I..\third_party\boringssl\third_party\googletest\include -I..\third_party\boringssl\tool\..\include -utf-8 -Wall -WX  -wd4061 -wd4100 -wd4127 -wd4200 -wd4204 -wd4221 -wd4242 -wd4244 -wd4267 -wd4371 -wd4388 -wd4296 -wd4350 -wd4365 -wd4389 -wd4464 -wd4510 -wd4512 -wd4514 -wd4548 -wd4610 -wd4623 -wd4625 -wd4626 -wd4628 -wd4668 -wd4706 -wd4710 -wd4711 -wd4800 -wd4820 -wd5026 -wd5027 -wd5045  -w44265 /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fothird_party\boringssl\tool\CMakeFiles\bssl.dir\transport_common.cc.obj /Fdthird_party\boringssl\tool\CMakeFiles\bssl.dir\ /FS -c ..\third_party\boringssl\tool\transport_common.cc
..\third_party\boringssl\tool\transport_common.cc(19): error C2220: warning treated as error - no 'object' file generated
..\third_party\boringssl\tool\transport_common.cc(19): warning C4005: '_SCL_SECURE_NO_WARNINGS': macro redefinition
..\third_party\boringssl\tool\transport_common.cc: note: see previous definition of '_SCL_SECURE_NO_WARNINGS'
[2045/2072] Running gRPC C++ protocol buffer compiler on src/proto/grpc/channelz/channelz.proto
ninja: build stopped: subcommand failed.
```

**Comment by noahdav** [comment]
<Adding cmake log files>

[CMakeOutput.log](https://github.com/grpc/grpc/files/4105861/CMakeOutput.log)
[CMakeError.log](https://github.com/grpc/grpc/files/4105862/CMakeError.log)

**Comment by larsonmpdx** [comment]
I get the same error starting with 1.25.x.  1.24.x works

**Comment by noahdav** [comment]
Correct.  We have the same issue.  We need to upgrade from 1.24 due to the new features that we need to use.  Does anyone have a workaround for this?

**Comment by veblush** [comment]
Jan, can you take a look at this problem? It looks related with boringssl.

**Comment by noahdav** [comment]
Yes if I set gRPC_SSL_PROVIDER:STRING=package  and OPENSSL_ROOT_DIR this issue does not exist.

**Comment by nicolasnoble** [comment]
This has been fixed a while back in BoringSSL, we just need to (successfully) upgrade BoringSSL, which we keep reverting due to many different issues.

https://github.com/google/boringssl/commit/43890dbd693d5d972afbc676860e5adf4a44236a

**Comment by noahdav** [comment]
@nicolasnoble Is there any update to when BoringSSL will be updated?  

After looking at this more this currently is broken for cmake too.  In order to build, I need to use openssl as a package instead of BoringSSL by setting gRPC_SSL_PROVIDER:STRING=package and OPENSSL_ROOT_DIR.  For now, we can work around this by building OpenSSL separately but for the long term, this should not be needed.

**Comment by uecasm** [comment]
Not sure if this is interesting or not, but at tag v1.27.0 (8cf19cfdd840731b) I was able to successfully compile on Windows -- but it did require patching third_party\boringssl\tool\transport_common.cc to wrap an #ifndef around the #define at the top, due to already being defined externally.

I was not using cmake command line, but instead using VS2017's native CMake support (which does still use Ninja to compile).

This still seems to work at v1.27.2 as well.  (I haven't checked if things actually work yet, just if they compile.... except that apparently the install target doesn't work; it installed the headers but not the libs.)

**Comment by jtattermusch** [comment]
third_party/boringssl-with-bazel is now at https://github.com/google/boringssl/tree/1c2769383f027befac5b75b6cedd25daf3bf4dcf, which should be new enough to fix the problem.
