### ISSUE TITLE
Latest release on grpc.io/release points to old version v1.20.0

### ISSUE THREAD

**Issue by everflux** [grpc/grpc#21795]
Many installation guides recommend using https://grpc.io/release to determine the latest release.
This is currently (January 2020) pointing to v1.20.0 while the latest stable release should be v1.26.0 according to the GitHub release page.

**Comment by veblush** [comment]
Thank you for the report! We will make it return the recent version of gRPC.

**Comment by everflux** [comment]
Issue is in fact fixed.
