### ISSUE TITLE
Extension grpc.ddl invisible ?

### ISSUE THREAD

**Issue by sergedevillez** [grpc/grpc#21836]
## What version of gRPC and what language are you using?
I'm using **php_grpc-1.26.0-7.3-ts-vc15-x86** et **php version 7.3.12**

### What operating system (Linux, Windows,...) and version?
Windows 10

### What did you do?
I created a new php project, installed the extension Grpc1.26 on this page : https://pecl.php.net/package/gRPC
I then moved the ddl extension in my locahost wampserver directory  C:\wamp64\bin\php\php7.3.12\ext.
I also added the dependancy to the file php.ini (and later checked apache /.../php.ini and it was there).
I added the dependancies in my composer.json file then update/install.
I created a class firestore to access my firestore database.
Then I ran a simple php file index.php with : 
$fs = new Firestore('cities');
print_r($fs->getDocument('London'));

I re-tested after closing-down both local server (wampserver) and phpstorm and no difference at all.

### What did you expect to see?
I expected to see the array from getDocument telling me that the document were added to my database

### What did you see instead?
An error message telling me : 
_Fatal error: Uncaught Google\Cloud\Core\Exception\GoogleException: The requested client requires the gRPC extension. Please see https://cloud.google.com/php/grpc for installation instructions. in C:\wamp64\www\
firebase-php-master\vendor\google\cloud\Core\src\ClientTrait.php:75
Stack trace:
#0 C:\wamp64\www\firebase-php-master\vendor\google\cloud\Firestore\src\FirestoreClient.php(139): Google\Cloud\Firestore\FirestoreClient->requireGrpc()
#1 C:\wamp64\www\firebase-php-master\Firestore.php(13): Google\Cloud\Firestore\FirestoreClient->__construct(Array)
#2 C:\wamp64\www\firebase-php-master\index.php(6): Firestore->__construct('cities')
#3 {main}
  thrown in C:\wamp64\www\firebase-php-master\vendor\google\cloud\Core\src\ClientTrait.php on line 75_

![Capture d’écran (3)](https://user-images.githubusercontent.com/33464975/73442691-96d45380-4355-11ea-834f-66a1ed450a1d.png)

![Capture d’écran (5)](https://user-images.githubusercontent.com/33464975/73442696-976cea00-4355-11ea-8c86-df23c4e7a3fc.png)

![Capture d’écran (6)](https://user-images.githubusercontent.com/33464975/73442697-976cea00-4355-11ea-8a4a-a6e91cbb91ae.png)

![Capture d’écran (7)](https://user-images.githubusercontent.com/33464975/73442698-976cea00-4355-11ea-9b81-269002e8da83.png)

![Capture d’écran (8)](https://user-images.githubusercontent.com/33464975/73442699-976cea00-4355-11ea-92a4-a920068f523b.png)
Here, I'm checking  the php extensions currently used and grpc doesn't appear.

**Comment by stanley-cheung** [comment]
Please make sure the gRPC extension has been placed in the right directory (the extension_directory as indicated by `php -i`), and is referred to with the right spelling in your `php.ini` file. (is it named `grpc.dll`? I am not sure if it should be `grpc.ddl`, etc).

**Comment by sergedevillez** [comment]
The ddl file is in the correct directory (C:\wamp64\bin\php\php7.3.12\ext), it is also named in the file php.ini as an extension (without the commentary ;)
Here are the pictures : 

php -i result : 
![Capture d’écran (9)](https://user-images.githubusercontent.com/33464975/73525960-79b08b00-4410-11ea-920b-f80546a7f87b.png)
the grcp.ddl file : 
![Capture d’écran (10)](https://user-images.githubusercontent.com/33464975/73525962-7a492180-4410-11ea-8f37-89556f2c815b.png)
and the php.ini : 
![Capture d’écran (11)](https://user-images.githubusercontent.com/33464975/73525963-7a492180-4410-11ea-97be-9feab4edba52.png)

**Comment by sergedevillez** [comment]
No answer after 17 days and I had to found a different way to use firebase without grpc and I did so case close altough the problem problably still exist.
