### ISSUE TITLE
Unable to use py_proto_library & py_grpc_library outside workspace

### ISSUE THREAD

**Issue by gertvdijk** [grpc/grpc#21830]
### What version of gRPC and what language are you using?
1.26.0

(also reproducible for master @ b94490bc74a2efc727)

### What operating system (Linux, Windows,...) and version?
Linux/Ubuntu, Bazel (via Bazelisk) 1.2.1, 2.0.0 and 2.1.0rc1 all affected.

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.9 (default Ubuntu 18.04 host)

### What did you do?
Define a `py_proto_library` or `py_grpc_library` target in one workspace, try to load it (use as dep) in another.

Example repository demonstrating the bug:

* 1.26.0: https://github.com/gertvdijk/grpc-bazel-proto-bug
* master @ b94490bc74a2efc727: https://github.com/gertvdijk/grpc-bazel-proto-bug/tree/grpc-master

### What did you expect to see?
It to work like any other cross-workspace dependency of a `py_library`.

### What did you see instead?
A Bazel error that a file was declared but not produced on that path:

    ERROR: /path/to/bazel/cache/external/myorg_foo_lib/myorg/foo/BUILD.bazel:23:1: output 'external/myorg_foo_lib/myorg/foo/hello_pb2_grpc.py' was not created
    ERROR: /path/to/bazel/cache/external/myorg_foo_lib/myorg/foo/BUILD.bazel:23:1: not all outputs were created or valid

Because of this clear error with a true positive Bazel complaint, I filed a bug rather than asking a question. I strongly suspect some logic is wrong in the Bazel rules provided by gRPC.

### Anything else we should know about your project / environment?
Nope, all very straightforward with Ubuntu 18.04 and Bazelisk, already shows up in the simplest form of a workspace as per [example repository](https://github.com/gertvdijk/grpc-bazel-proto-bug).

**Comment by nicolasnoble** [comment]
For technical reasons, these rules can only work with proto files that live in the same bazel workspace.  They *might* work if you have a `proto_library()` that's in your own workspace, but importing a `filegroup()` from a third party library. There is no technical way for us to do otherwise, without introducing breaking changes to these rules.

In other words, we can't fix this.

**Comment by gertvdijk** [comment]
Hmm, that's a bummer. The usefulness of these rules drop near-zero for anyone having proto files in another repository or providing them for others to use.

Could you elaborate a bit more on what kind of 'breaking changes' you mean? Because I really like the quality of the rules otherwise, I am exploring the option to vendor the rules to make these breaking changes for use in my project.

**Comment by gertvdijk** [comment]
I've managed to make it work for at least the use case as in the minimal example. It imposes a minor change to the code. It would be nice if someone could take a look at this to see if this is acceptable; I'm happy to create a PR then.

[patch: `0001-Allow-depending-on-the-Bazel-Python-rules-from-other.patch`](https://github.com/gertvdijk/grpc-bazel-proto-bug/blob/ec3d90ceeca20068803c347706d651eae779063c/foo_lib/third_party/patches/com_github_grpc_grpc/0001-Allow-depending-on-the-Bazel-Python-rules-from-other.patch)
