### ISSUE TITLE
grpc and grpc tools 2.26 version gives runtime error

### ISSUE THREAD

**Issue by madhurabindu** [grpc/grpc#21837]
I have a desktop application that communicates with a python server (on the same system) using GRPC. Desktop app is built on .netframework 7.5
the GRPC Proto file is built on .net standard 2.0 and compiled sing VS default proto compiler.

This has been working perfectly fine for last year or so.
I had GRPC version 2.25.

I moved to 2.26 and I get runtime error saying System.Runtime.CompilerServices 4.5.2 is not compatible. 
Is this a known issue?

I have reverted back to 2.25 and it works fine.

**Comment by jtattermusch** [comment]
Can you provide a reproduction?
