### ISSUE TITLE
Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by shashwat12june** [grpc/grpc#21868]
I am using ruby 2.7.0 on  mac os HIGH SIERRA version 10.13.4

Issue: getting `encode': "\\xCF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

STEP to regenerate:

-Open terminal
-irb
-Press arrow keys.

result: irb stops with error message "/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/unicode.rb:70:in `encode': "\\xCF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)"

![Screen Shot 2020-02-02 at 5 02 50 PM](https://user-images.githubusercontent.com/21045925/73607581-eb89ff80-45dd-11ea-9752-bffa5b75ff00.png)

**Comment by alto-ruby** [comment]
Don't have the exact environment but cannot reproduce with ruby 2.7.6 with Terminal on macOS 13.4.1.
This is not gRPC related anyways. Closing.
