### ISSUE TITLE
py36_asyncio.test_aio.unit.metadata_test.TestMetadata Flake

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#21907]
https://source.cloud.google.com/results/invocations/b7097b50-859b-4380-8cde-b803ec022e37/targets/github%2Fgrpc%2Frun_tests%2Fpython_windows_opt_asyncio%2Fpy36_asyncio.test_aio.unit.metadata_test.TestMetadata/tests

**Comment by lidizheng** [comment]
Should be fixed by https://github.com/grpc/grpc/pull/21903

**Comment by lidizheng** [comment]
Observed another type of failure on the same test case:
https://source.cloud.google.com/results/invocations/418cdd64-0133-44a8-9a90-10224e454143/targets/github%2Fgrpc%2Frun_tests%2Fpython_windows_opt_asyncio%2Fpy36_asyncio.test_aio.unit.metadata_test.TestMetadata/tests
