### ISSUE TITLE
Get Link error in the Unity Il2Cpp 32bit build

### ISSUE THREAD

**Issue by na-kubota** [grpc/grpc#21949]
### What version of gRPC and what language are you using?
Unity C#
grpc 1.27.0

### What operating system (Linux, Windows,...) and version?
Win 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2018
Standalone
Il2cpp
.Net 4.*
32bit

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

1:Create New UnityProjects
2:Import grpc
3:New Script
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class UseGRPC : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        var insecure = Grpc.Core.ChannelCredentials.Insecure;
        var hoge = new Grpc.Core.Channel("", insecure);
    }
}
```
4:Unity Build (Standalone, Il2cpp, .Net 4.*, 32bit) is Build Failed

※4:Unity Build (Standalone, Il2cpp, .Net 4.*, 64bit) is Build Success!!
Why Failed in 32bit??

### What did you expect to see?
Build Success

### What did you see instead?
Build Error LNK2019

sample Stack Trace:
???C?u???? D:\work\New Unity Project222\Library\il2cpp_cache\linkresult_242157DA687ED5916DF990BDAE316608\GameAssembly.lib ??I?u?W?F?N?g D:\work\New Unity Project222\Library\il2cpp_cache\linkresult_242157DA687ED5916DF990BDAE316608\GameAssembly.exp ?????
15BC985DEC92B67530E04230712A8699.obj : error LNK2019: ???????O???V???{?? _grpcsharp_init@0 ????? _DllImportsFromStaticLib_grpcsharp_init_m5DA087A04425B1D1FDBAD9599AE149B2C2FA6C8C ??Q??????????B
15BC985DEC92B67530E04230712A8699.obj : error LNK2019: ???????O???V???{?? _grpcsharp_shutdown@0 ????? _DllImportsFromStaticLib_grpcsharp_shutdown_mD2AA862907DA1352A16F8A536942A252CDC9358C ??Q??????????B
15BC985DEC92B67530E04230712A8699.obj : error LNK2019: ???????O???V???{?? _grpcsharp_version_string@0 ????? _DllImportsFromStaticLib_grpcsharp_version_string_mCDADBE758244CDB17FF33EB92BB881652207FA89 ??Q??????????B
15BC985DEC92B67530E04230712A8699.obj : error LNK2019: ???????O???V???{?? _grpcsharp_batch_context_create@0 ????? _DllImportsFromStaticLib_grpcsharp_batch_context_create_mB0CC51310DAA0A1160F3F1EF49CB06042C17D07E ??Q??????????B

and more...

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Please Help!!

**Comment by markdroth** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at
- StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
For questions that specifically need to be answered by gRPC team members, please ask/look for answers at
- grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by xerdink** [comment]
why close this issue? @na-kubota already posted a bug here?

it indeed is a known bug and affects my build also.
