### ISSUE TITLE
[Aio] Type of metadata?

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#21953]
In recent discussion, there is a proposed idea from @pfreixes that we should improve the usability of our metadata. Currently, it is using an immutable tuple-in-tuple data structure. It creates some toil if the application want to modify the metadata, especially in interceptors.

One possible solution is entirely converting the tuple-in-tuple to Python `dict`. There are two potential issues:
1. The order is not necessary preserved for < 3.7;
2. Multiple entries with the same key is now prohibited (which is allowed in the existing stack).

Another solution is accepting `dict` and tuple-in-tuple for input, and output tuple-in-tuple in methods. Or similar combination of mixing two types of data structure. This might create some confusion for users, and provides limited help for interceptor authors.

Or, we introduce a new metadata class, that can provide the necessary convenient methods, but also can be treated as tuple.

WDYT @pfreixes @gnossen

**Comment by pfreixes** [comment]
The issues that you are commenting on are the ones that are addressed by `multidict` [1], indeed I would say that the use cases that the gRPC library and Aiohttp want to support are the same which for the second one the `mutlidict` is the chosen implementation.

IIRC these are the main use cases:

- Support multidis or other compatible iterables for giving the headers https://github.com/aio-libs/aiohttp/blob/master/aiohttp/typedefs.py#L42
- Response headers are returned as a proxy of a multidict, I guess for immutability reasons https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.headers

My personal taste, I like the idea implemented by Aiohttp. Not sure how much freedom we have on adopting `multidict` as a dependency.

WDYT?


[1 ]https://github.com/aio-libs/multidict

**Comment by gnossen** [comment]
@pfreixes I had the same response. A multimap/multidict is definitely the best abstraction for this. Our stance on library usage is "only if we absolutely have to". At the moment, that includes `six` and `futures`, for obvious reasons. We don't even have a hard dependency on `protobuf`. In general, we follow the rule "a little duplication is better than a little dependency". There is no multimap/multimap abstraction in the Python standard library and there is no special syntactic support for such a data structure, so I think we should stick to `Sequence[Tuple[AnyStr, AnyStr]]` in and `Tuple[Tuple[str, str]]` out.

**Comment by pfreixes** [comment]
Unfortunately correct me if I'm wrong but the ability to have multiple entries with the same key is a must, so if we can not provide a mapping interface with that feature we can not move forward. 

If this is right, and the usage of `multidict` is out of the scope or implement our own interface, then there is no way for implementing the desired feature with the default Python dict implementation.

Any ideas?

**Comment by gnossen** [comment]
What would the interface look like if we created our own data structure for this?

**Comment by pfreixes** [comment]
I guess that would be what `multidict` does, with the following requirements as a must

- Allow multiple entries with the same key
- Order preservation
- Immutability view

IMO the new type could be optional when the headers are given for making a new RPC call, so other types for legacy reasons could be accepted. But as @lidizheng said, would be interesting to use it yes or yes by the interceptors interface, which would address the current pain on having to create a new tuple every time that we want to add a header.

Call response would expose the immutable view of that data structure.

**Comment by pfreixes** [comment]
Indeed the gRPC Java implements its own type [1], which if I'm not reading in the wrong way is basically storing the values into an array [2].

[1] https://github.com/grpc/grpc-java/blob/d35fbd7eee072854c20b61ea7fcf7c70a8e8cb8e/core/src/main/java/io/grpc/Metadata.java
[2] https://github.com/grpc/grpc-java/blob/d35fbd7eee072854c20b61ea7fcf7c70a8e8cb8e/core/src/main/java/io/grpc/Metadata.java#L129

**Comment by gnossen** [comment]
Fair enough. Implementing our own type should be fine.

**Comment by pfreixes** [comment]
maybe @rmariano wants to work on this. We would need this before the alpha release.

I would suggest on summarizing the key points of the implementation before starting, which definitely would help with having the expectations aligned.

**Comment by lidizheng** [comment]
@pfreixes That would be great. @gnossen and I discussed the possibilities today. The feature requirement is clearly stated by your [comment](https://github.com/grpc/grpc/issues/21953#issuecomment-585402231). Also, we would like to keep in mind of its performance impact. One potential solution is that we could subclass built-in `dict`  which is implemented in C.

@rmariano feel free to propose a design here, or as a PR.

**Comment by gnossen** [comment]
One addendum:

> subclass built-in `dict`

I'd prefer composition to inheritance.

**Comment by rmariano** [comment]
I agree with creatinga bespoke class, as it would give us the best flexibility in the long term..
I'd also like to take this. If you agree, I'll propose a design here, and we can iterate (and agree) on it, before moving onto the actual implementation...

**Comment by rmariano** [comment]
> What would the interface look like if we created our own data structure for this?

These are the traits I drafted based on the [requirements outlined before](https://github.com/grpc/grpc/issues/21953#issuecomment-585402231), based on how the new type can be used from a client's perspective:

```python
# Initialisation
>>> metadata = Metadata()
>>> metadata2 = Metadata(  # ... or init from *args
  ('initial-md-key', b'initial-md-value'),
  ('initial-md-key', b'other-md-value'),
  ('initial-md-key-bin', b'\x00\x02'),
)
# Write
>>> metadata.add('initial-md-key', b'initial-md-value')
>>> metadata.add('initial-md-key', b'other-md-value')
>>> metadata.add('initial-md-key-bin', b'\x00\x02')

# Read
>>> metadata.get("initial-md-key")
[b'initial-md-value', b'other-md-value']

>> metadata.get("initial-md-key-bin")
[b'\x00\x02']

>>> metadata.get("non-existing-key")
[]

>>> metadata.view()  # same as tuple(metadata)
(
  ('initial-md-key', b'initial-md-value'),
  ('initial-md-key', b'other-md-value'),
  ('initial-md-key-bin', b'\x00\x02'),
)

# Iteration
>>> [m for m in metadata]
[
  ('initial-md-key', b'initial-md-value'),
  ('initial-md-key', b'other-md-value'),
  ('initial-md-key-bin', b'\x00\x02'),
]
# Container
>>> 'initial-md-key' in metadata
True
>>> 'INITIAL-MD-KEY' in metadata
True
>>> 'non-existing-key' in metadata
False
>>> len(metadata)
3

# Comparison
>>> metadata == metadata2
True
```

I look forward to get your feedback on this, in order to know if this is something you think will be useful for your use case on interceptors.

Speaking in terms of the next steps, I'd like to separate the implementation in (at least) to separate PRs
1. Create the new abstractions (with their respective tests), completely isolated from the rest of the unary unar calls, and then another part to
2. Refactor our current use of metadata in the calls, so they use the new available abstraction.

In terms of implementation, I'd start with a class that abstracts built-in data structures (lists, dicts, etc.) by composition, and exposes this interface.

**Comment by pfreixes** [comment]
Hi @rmariano thanks for the draft, looks promising! I have only a few questions:

1 - Should we provide a specific method for getting all values for a specific key, like `getAll` and leave the `get` method for returning the first occurrence? IIRC is what Java interface does, and might be based on the fact that most of the cases the user will know explicitly that there is only one value and have many values is an edge case that the user would need to consider explicitly and use the right `getAll` method for them. 

2- Should we try to provide an implementation of the `Mapping` [1] interface?

3- Regarding the view, IIRC the original requirement was to provide _two sides of the same coin_. One, which would mean providing an immutable view of the data that would be used by the `Call` methods [2] that return `MetadataType` objects. And the second one, having the chance of mutating the object for reducing the current friction on the interceptors which forces to you to rebuild the whole object.

4 - Outstanding question, How are we gonna preserve the order? For example, I can foresee some complicated scenarios where there could be multiple values for the same key being inserted in a different order. 

[1] https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping
[2] https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/experimental/aio/_base_call.py#L89

**Comment by rmariano** [comment]
@pfreixes thanks for your feedback

About [1] and [2]. Yes, we can implement the mapping interface, and in that case the ``get`` method could be just ``__getitem__`` and rename the ``get`` from the original proposal to ``get_all``. This way ``__getitem__`` / ``get`` will return only the first occurrence.

[3] The ``.view()`` method should address the immutable view of the data, and this object should also be mutable. If necessary, we can add a ``.replace(key, current_value, new_value)`` method to make this more explicit, but the design shouldn't restrict this.

[4] That's more an implementation detail, but an option could be to wrap ``OrderedDict`` (to make sure it'll work on all supported Python versions, and not just 3.7+), or list if we think it's strictly required.

Please let me know if you have any more queries or concerns.

**Comment by pfreixes** [comment]
Regarding the `view` remember that one of the goals is making the life easier to the develop, so not having to iterate for the whole object returned by the `initial_metadata` methods for finding one specific key. So theoretically the user  should be able to do something like this

```python
call = Stub(...)
foo = await call.initial_metadata()['foo']
```

When the mutable interface is provided adding or replace how could be done? just by something like this?

```python
metdata['new_key'] = 'new_key'
```

User and interceptor developers must take care that multiple values per key would be allowed.

**Comment by rmariano** [comment]
For the view endpoint, then yes, since we're implementing the mapping interface the `` await call.initial_metadata()['foo']`` will work and there's no need to iterate the result of the ``view`` method (although it can be still available).

As for the writing, since a key can have multiple values, the ``__setitem__`` semantics can be misleadiing, so we can assume, it will replace whatever keys it had for a single one that's the new one (and keep the ``replace`` method to replace just a particular instance).
For example

```python
>>> metadata = Metadata(("new_key", "value1"), ("new_key", "value2"))
>>> metadata.get_all("new_key")
["value1", "value2"]
>>> metadata["new_key"] = "new_key"
>>> metadata.get_all("new_key")
["new_key"]
>>> metadata["new_key"]
"new_key"

>>> metadata2 = Metadata(("new_key", "value1"), ("new_key", "value2"))
>>> metadata2.replace(("new_key", "value1"), ("new_key", "foo"))
>>> metadata2["new_key"]
"foo"
>>> metadata2.get_all("new_key")
["foo", "value2"]
```
WDYT?

**Comment by pfreixes** [comment]
not sure about the last one I would prefer @lidizheng or @gnossen giving his thoughts since they know better how this new type would be used.

**Comment by rmariano** [comment]
Good it seems most of the points are OK, so we just need to decide on the interface for allowing mutability of the attributes. If you'd like more detail, I drafter a PR with the basic implementation agreed so far at https://github.com/grpc/grpc/pull/22306

As per the last point, we can make it the ``__setitem__`` accept a string or a list of strings, to override all the values in both ways.
Or we can make the ``__setitem``__ override with only one single element always (as in the previous example), and add another method ``set_all(key, list_of_values)``, analogous to the ``get_all()``. I like this second option more, for consistency.

**Comment by lidizheng** [comment]
@rmariano The second option sounds better to me.

The proposal looks great, I added my comments. Looking forward to it :)

**Comment by gnossen** [comment]
@rmariano Mostly looks good! Just a couple of questions. Suppose I wanted to append a value for a particular key without touching what's already there. How would I do that?

**Comment by rmariano** [comment]
@gnossen for appending a value to a particular key, the ``add(key, value)`` method can be used. With that and the``__setitem__`` + ``set_all()`` the mutation capabilities should be covered.

**Comment by pfreixes** [comment]
In progress, don't close it stale bot.

**Comment by rmariano** [comment]
Indeed, this is in progress.
