### ISSUE TITLE
Python tutorial doesn't work for latest version (v1.27.1)

### ISSUE THREAD

**Issue by staticdev** [grpc/grpc#21952]
### What version of gRPC and what language are you using?
v1.27.1 / Python

### What operating system (Linux, Windows,...) and version?
Linux Ubuntu 18.04.3 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.4

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I tried running `greeter_server.py` following along [Google tutorial](https://grpc.io/docs/quickstart/python/):

### What did you expect to see?
A running server.

### What did you see instead?
```
Traceback (most recent call last):
  File "greeter_server.py", line 21, in <module>
    import helloworld_pb2
  File "/home/user/workspace/grpc/examples/python/helloworld/helloworld_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Nope.

**Comment by lidizheng** [comment]
Can you try to install ProtoBuf package?

```
pip install protobuf
```

gRPC meant to be a generic RPC system that applications can pick their own codec.

**Comment by gnossen** [comment]
@staticdev What artifact did you install `grpcio` from? Can you show us the results of

```
pip uninstall grpcio
pip install grpcio
```

**Comment by staticdev** [comment]
I will reopen it if I have problem with newer version.
