### ISSUE TITLE
Unable to compile grpc C++ for Ubuntu

### ISSUE THREAD

**Issue by abhiarora4** [grpc/grpc#21962]
I am trying to compile gRPC for my Ubuntu machine:

I have followed the instructions over here: https://github.com/grpc/grpc/blob/master/BUILDING.md

cmake --version => 3.13.2

     cmake   -DCMAKE_BUILD_TYPE=Release   -DgRPC_INSTALL=ON   -DgRPC_BUILD_TESTS=OFF   -DgRPC_SSL_PROVIDER=package   ../..
    -- The C compiler identification is GNU 7.4.0
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:188 (include):
      include could not find load file:

        cmake/abseil-cpp.cmake

    CMake Error at CMakeLists.txt:189 (include):
      include could not find load file:

        cmake/address_sorting.cmake

    CMake Error at CMakeLists.txt:190 (include):
      include could not find load file:

        cmake/benchmark.cmake

    CMake Error at CMakeLists.txt:191 (include):
      include could not find load file:

        cmake/cares.cmake

    CMake Error at CMakeLists.txt:192 (include):
      include could not find load file:

        cmake/gflags.cmake

    CMake Error at CMakeLists.txt:193 (include):
      include could not find load file:

        cmake/protobuf.cmake

    CMake Error at CMakeLists.txt:194 (include):
      include could not find load file:

        cmake/ssl.cmake

    CMake Error at CMakeLists.txt:195 (include):
      include could not find load file:

        cmake/upb.cmake

    CMake Error at CMakeLists.txt:196 (include):
      include could not find load file:

        cmake/zlib.cmake

    CMake Error: File /home/abhishek/develop/grpc/cmake/gRPCConfig.cmake.in does not exist.
    CMake Error at CMakeLists.txt:18402 (configure_file):
      configure_file Problem configuring file

    CMake Error: File /home/abhishek/develop/grpc/cmake/pkg-config-template.pc.in does not exist.
    CMake Error at CMakeLists.txt:18430 (configure_file):
      configure_file Problem configuring file
    Call Stack (most recent call first):
      CMakeLists.txt:18439 (generate_pkgconfig)

    CMake Error: File /home/abhishek/develop/grpc/cmake/pkg-config-template.pc.in does not exist.
    CMake Error at CMakeLists.txt:18430 (configure_file):
      configure_file Problem configuring file
    Call Stack (most recent call first):
      CMakeLists.txt:18449 (generate_pkgconfig)

    CMake Error: File /home/abhishek/develop/grpc/cmake/pkg-config-template.pc.in does not exist.
    CMake Error at CMakeLists.txt:18430 (configure_file):
      configure_file Problem configuring file
    Call Stack (most recent call first):
      CMakeLists.txt:18459 (generate_pkgconfig)

    CMake Error: File /home/abhishek/develop/grpc/cmake/pkg-config-template.pc.in does not exist.
    CMake Error at CMakeLists.txt:18430 (configure_file):
      configure_file Problem configuring file
    Call Stack (most recent call first):
      CMakeLists.txt:18469 (generate_pkgconfig)

    CMake Error: File /home/abhishek/develop/grpc/cmake/pkg-config-template.pc.in does not exist.
    CMake Error at CMakeLists.txt:18430 (configure_file):
      configure_file Problem configuring file
    Call Stack (most recent call first):
      CMakeLists.txt:18479 (generate_pkgconfig)

**Comment by kevinyaoxm** [comment]
I was having the same issue and later I found out I accidentally deleted the cmake folder which contains those .cmake files

**Comment by yashykt** [comment]
Did you run 
```
git submodule update --init
```
?

Also, please try bazel. That's the preferred approach.

As a reminder, this form is not intended for questions. Questions should be targeted towards platforms like stack-overflow or the grpcio google group.
