### ISSUE TITLE
Python 2 required via third_party/py/python_configure.bzl

### ISSUE THREAD

**Issue by gertvdijk** [grpc/grpc#21963]
### What version of gRPC and what language are you using?
1.27.0 (sources for Bazel) / 1.27.1 (PyPI package)

### What operating system (Linux, Windows,...) and version?
Debian Buster

### What runtime / compiler are you using (e.g. python version or version of gcc)
I'm trying to use Python 3.7, without the need for installing Python 2. As Python 2 is EOL, I don't like to have that installed in order to use gRPC.

### What did you do?
I'm depending on gRPC-Python in my Bazel project and loading the dependencies via `bazel/grpc_python_deps.bzl`.

### What did you expect to see?
It to load the dependencies without the need for Python 2 on my system. I expect this to work because https://github.com/grpc/grpc/issues/19083 is merged.

### What did you see instead?
It fails
```
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at /path/to/bazel/cache/external/com_github_grpc_grpc/third_party/py/python_configure.bzl:347:20):
 - /path/to/bazel/cache/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl:51:5
 - /path/to/bazel/cache/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl:51:5
 - /path/to/bazel/cache/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:282:5
 - /home/gert/myproject/WORKSPACE:80:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "/path/to/bazel/cache/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 331
                _create_single_version_package(<5 more arguments>)
        File "/path/to/bazel/cache/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 284, in _create_single_version_package
                _get_python_bin(repository_ctx, <2 more arguments>)
        File "/path/to/bazel/cache/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 166, in _get_python_bin
                _fail(<1 more arguments>)
        File "/path/to/bazel/cache/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 35, in _fail
                fail(<1 more arguments>)
Python Configuration Error: Cannot find python in PATH, please make sure python is installed and add its directory in PATH, or --define PYTHON2_BIN_PATH='/something/else'.
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

### Anything else we should know about your project / environment?
Reproducible using this Dockerfile & Bazel 2.1.0:

```
FROM debian:buster

RUN apt update && apt install -y build-essential python3 python3-dev python3-distutils && apt clean

# Omitted installation of Bazel and other project-level dependencies.
```

and 

```
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("@com_github_grpc_grpc//bazel:grpc_python_deps.bzl", "grpc_python_deps")

grpc_python_deps()
```

in a Bazel project WORKSPACE.

I now learned that the Python rules still actively checks for a Python 2 lib+bin as commented here:
https://github.com/grpc/grpc/blob/425137634b7fb96d16b72633bc13296213af94c5/third_party/py/python_configure.bzl#L369-L370

But there's no _why_ to this mentioned.

I've tried to remove all Python 2 remnants there by hand and run the rules, but get stuck on Cython invocations:

```
ERROR: /path/to/bazel/cache/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/BUILD.bazel:5:1: Executing genrule @com_github_grpc_grpc//src/python/grpcio/grpc/_cython:cygrpc.pyx_cython_translation failed (Exit 127) process-wrapper failed: error executing command
  (cd /path/to/bazel/cache/sandbox/processwrapper-sandbox/213/execroot/my_workspace && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /path/to/bazel/install/cprocess-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PYTHONHASHSEED=0 bazel-out/host/bin/external/cython/cython_binary --cplus external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.pyx --output-file bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp')
/usr/bin/env: 'python': No such file or directory
```

where `bazel-out/host/bin/external/cython/cython_binary` is Python 2:

```
$ head -n1 bazel-out/host/bin/external/cython/cython_binary
#!/usr/bin/env python
```

And even updating Cython to latest development version seems not to solve it; it's stuck on Python 2:

https://github.com/cython/cython/blob/738bccf74b5e00b1d66141eb83e3a6ba53627811/bin/cython#L1

**Comment by robbrit** [comment]
Going to +1 this one; gRPC is the only thing in our stack that still uses Python 2. Python 2 is dead and gone, they are no longer releasing security updates for it or anything.

Even executing the final built executable doesn't require Python 2 (our production Docker containers don't have it installed), it's just the gRPC build process that seems to want to look for Python 2 headers.

**Comment by gnossen** [comment]
I actually think this has been taken care of: https://github.com/grpc/grpc/pull/24407

@robbrit Are you still seeing issues?

**Comment by robbrit** [comment]
We're using an older release of gRPC (v1.31.1), it's the newest one that compiles. The latest one (v1.34.0) gives a compile error when we attempt to use it:
```
ERROR: /home/rob/.cache/bazel/_bazel_rob/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/BUILD.bazel:12:12: Executing genrule @com_github_grpc_grpc//src/python/grpcio/grpc/_cython:cygrpc.pyx_cython_translation failed (Exit 127): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
```
This error doesn't seem terribly useful, let me know if anything else could help.

**Comment by gnossen** [comment]
Yeah, unfortunately all the useful bits are truncated from that error message. I think [`--verbose_failures`](https://docs.bazel.build/versions/master/user-manual.html#flag--verbose_failures) is the flag you'll want to use.

**Comment by dHannasch** [comment]
I'm seeing this in another bazel project, I think. I *think* this is the root cause.

```
INFO: Repository local_config_python instantiated at:
/ray/WORKSPACE:9:19: in <toplevel>
/ray/bazel/ray_deps_build_all.bzl:18:12: in ray_deps_build_all
/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:241:21: in grpc_deps
/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl:57:21: in grpc_python_deps
Repository rule python_configure defined at:
/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_grpc_grpc/third_party/py/python_configure.bzl:294:35: in <toplevel>

ERROR: An error occurred during the fetch of repository 'local_config_python':
Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 281, column 35, in _python_autoconf_impl
_create_single_version_package(repository_ctx,
File "/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 251, column 22, in _create_single_version_package
_check_python_bin(repository_ctx, python_bin, bin_path_key)
File "/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 211, column 14, in _check_python_bin
_fail("--define %s='%s' is not executable. Is it the python binary?" %
ERROR: /ray/BUILD.bazel:1695:12: //:python/ray/_raylet.so depends on @local_config_python//:python_headers in repository @local_config_python which failed to fetch. no such package '@local_config_python//': Python Configuration Error: --define PYTHON2_BIN_PATH='/usr/bin/python' is not executable. Is it the python binary?
ERROR: Analysis of target '//:ray_pkg' failed; build aborted: Analysis failed
```

My bazel-fu is weak, but clearly this is coming from https://github.com/grpc/grpc/blob/master/third_party/py/python_configure.bzl#L347. I'm assuming the `.cache/bazel` thing is just a thing bazel does, yell at me if I'm wrong.

**Comment by gnossen** [comment]
Right. Python 2 is an optional dependency for the Bazel build. We still test backwards compatibility with Python 2, though probably not for much longer, so we need to retain a way to test it.

> '/usr/bin/python' is not executable

`/usr/bin/python` is being interpreted as a Python 2 interpreter, per an earlier version of [PEP 394](https://www.python.org/dev/peps/pep-0394/#history-of-this-pep). It seems that this path is not executable on your system.

Since the guidance in PEP 394 has changed, we probably need to stop assuming that `/usr/bin/python` refers to a Python 2 installation, but we're so close to removing Python 2 from our infrastructure entirely, that it may be worth it just to wait until it's all ripped out instead of trying to doctor things to continue the Python 2 life support.

You should be able to work around this for the moment by setting the environment variable `PYTHON2_BIN_PATH=""`
