### ISSUE TITLE
Interop Tests Broken on Master

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#21966]
Python is failing to install `grpcio_tools`: 

```
2020-02-10 14:28:51,658 WAITING: ETA 839.4 sec; 2040 queued, 8 jobs running, 50 complete, 0 failed (load 8.00) next: cloud_to_cloud:python:node_server:empty_stream:tls @ 1.00 cpu
2020-02-10 14:28:51,732 Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 22, in <module>
    import grpc_tools.command
ModuleNotFoundError: No module named 'grpc_tools'
```

This has been broken [since 3:27AM this morning](https://fusion.corp.google.com/runanalysis/buildlogs/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud/KOKORO/981f4cc6-0582-4082-85ba-ca2438362a1d/1581334029902/build%20%2310629/Targets) and it does not seem to be related to any particular code change. Kokoro change perhaps?

**Comment by lidizheng** [comment]
Manually followed the interop test process, both building and running of interop tests are fine. However, if I use the `run_interop_tests.py` to perform the test, it would generate the error above.

**Comment by gnossen** [comment]
Quick update for anyone who stumbles upon this today. The first attempt to solve this problem did not work. The Python team is working on this as our number one priority.
