### ISSUE TITLE
//test/core/end2end:h2_proxy_test@invoke_large_request Failure RBE Windows Debug C/C++

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#21976]
https://source.cloud.google.com/results/invocations/76852598-dc07-4dc2-b352-263763afc7a6/targets

Does Windows RBE even give us detailed logs from the test invocation. I can't seem to find them.

**Comment by markdroth** [comment]
You can see the detailed log via the "target log" tab.

This is a dup of #20609.
