### ISSUE TITLE
How can I compile grpc with opencensus in a x86 environment?

### ISSUE THREAD

**Issue by heylaender** [grpc/grpc#21991]
I've the above problem.

I can compile grpc with vcpkg manager as x86 binary, but opencensus plugin is missing.
I can compile grpc with opencensus using bazel, but only as x64 binary.

Is there any documentation or could you provide steps how to get this working?

**Comment by markdroth** [comment]
OpenCensus currently supports only bazel builds, so we can't easily integrate it into any other build system.  If OpenCensus added support for make/cmake/vcpkg/etc, we could support it in those configurations as well.

I suggest you file a bug against OpenCensus for this.  If they fix it, then you can file a bug against gRPC to integrate that into our build system.
