### ISSUE TITLE
RPC call on client hangs even with deadline when the service is not reachable or not running

### ISSUE THREAD

**Issue by pkbehera** [grpc/grpc#22004]
### What version of gRPC and what language are you using?
C++, gRPC version: commit 5d57a8d (tag: v1.13.0)

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 16.04.6 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version: 7.3.0

### What did you do?
Simple test to see if `set_deadline()` is working fine for gRPC clients when a gRPC service is NOT reachable or when the service is not running at all. See the code below.

```
#include <grpc++/grpc++.h>
#include <gtest/gtest.h>
#include "foo.grpc.pb.h"

/**
// foo.proto
syntax = "proto3";
package foo;

message HelloReply { string message = 1; }
message HelloRequest { string name = 1; }
service Greeter {
  rpc SayHello(HelloRequest) returns (HelloReply) {}
}
*/
TEST(GrpcTest, DeadLine) {
  // no service is running at this address
  auto greeter_stub = foo::Greeter::NewStub(CreateChannel("bogus.com:12121", 
                                  grpc::InsecureChannelCredentials()));
  grpc::ClientContext hello_ctxt;
  // set a deadline of 1 second
  hello_ctxt.set_deadline(std::chrono::system_clock::now() + std::chrono::seconds(1));
  foo::HelloRequest hello_req;
  hello_req.set_name("Foo");
  foo::HelloReply hello_rep;
  auto  start = std::chrono::system_clock::now();
  greeter_stub->SayHello(&hello_ctxt, hello_req, &hello_rep);
  // should not this return in about 1 second?
  auto dur = std::chrono::duration_cast<std::chrono::seconds>
                    (std::chrono::system_clock::now() - start);
  EXPECT_LT(dur.count(), 2);
}

GTEST_API_ int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```
### What did you expect to see?
The RPC should return after the deadline expires, if the service is not reachable or not running.

### What did you see instead?
The RPC hangs, making the above test timed out.

### Anything else we should know about your project / environment?
We use bazel to build our c++ code inside a docker instance running Linux (Ubuntu 16.04.6 LTS)

**Comment by pkbehera** [comment]
Interestingly the RPC returns after the deadline expires if the _**service endpoint address is a unix domain socket.**_ Replace the following line in the above code sample

```
auto greeter_stub =
      foo::Greeter::NewStub(CreateChannel("bogus.com:12121",
      grpc::InsecureChannelCredentials()));
```
with

```
auto greeter_stub = // this address too does not exist
      foo::Greeter::NewStub(CreateChannel("unix:/bogus_addr",
      grpc::InsecureChannelCredentials()));
```  
and the RPC returns immediately after the deadline of 1 seconds expires.

**Comment by markdroth** [comment]
I'll try to take a look at this next week.

**Comment by pkbehera** [comment]
@markdroth did you get a chance to look at this? Thanks!

**Comment by pkbehera** [comment]
can @markdroth or someone look at this once place? Thank you!

**Comment by markdroth** [comment]
I'm fairly sure this has been fixed.  Please try with a recent version and gRPC.  If you're still having a problem, let us know, and we can reopen this.

**Comment by pkbehera** [comment]
https://groups.google.com/g/grpc-io/c/ly-JwdzS1EM Kindly see this discussion, don't think it is fixed in recent versions.

**Comment by markdroth** [comment]
That discussion thread does not seem to be talking about the same thing as this issue.  This issue was about a client RPC not terminating at its deadline, whereas the discussion thread is talking about a problem with shutting down gRPC globally.

**Comment by markdroth** [comment]
If you have code that can reproduce the problem being discussed in this thread with a recent version of gRPC, please post the code, and I will reopen the issue.
