### ISSUE TITLE
System.InvalidOperationException: 'Nullable object must have a value.' in DefaultDeserializationContext

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc#22005]
### What version of gRPC and what language are you using?
NuGet package Grpc 2.27.0 in C#

### What operating system (Linux, Windows,...) and version?
Windows 10 64bit

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework 4.6.1

### What did you do?
Connect to a gRPC Server using plain text.

### What did you expect to see?
Connection successful

### What did you see instead?
Since 2.23, it happens to me from time to time that I get an InvalidOperationException saying that the nullable object must have a value. This seems to happen in the `Grpc.Core.Internal.DefaultDeserializationContext`:

```
        public void Initialize(IBufferReader bufferReader)
        {
            this.bufferReader = GrpcPreconditions.CheckNotNull(bufferReader);
            this.payloadLength = bufferReader.TotalLength.Value;  // payload must not be null
        }
```

The Problem is that at runtime, the value of the TotalLength is indeed null. Grpc does not catch this error message and the exception eventually pops up at the surface, telling me that the connection failed at all ports. Do you have an idea what scenario could lead to the payload being null? Could you raise a specific exception in that case?

This error may happen spontaneously and then disappear from one moment to another without any change in the code or even without restarting the application. However, since the `bufferReader` is actually a wrapper around some native object, I can't really debug what could be wrong here.

### Anything else we should know about your project / environment?
I am using gRPC with protobuf-net instead of the Google Protobuf implementation both at the client and at a server-side. However, I check that all serialized byte arrays are not null. Clients written in Java can communicate with my server.

**Comment by malkia** [comment]
I'm hitting the same issue, strangely grpc_csharp_ext .dll is not loaded (or at least the IDE debugger's Modules view does not show it). Not sure if it's related though. I use gRPC for test automation, and use xUnit there, though have a standalone too.

**Comment by jtattermusch** [comment]
Can you provide a minimal snippet/project that reproduces the problem?

**Comment by jtattermusch** [comment]
I can imagine that when some internal error happens (from the report it's not obvious which one exactly), the message fails to be read (internally the payload is "null"), which then causes problems deserializing the payload (which should always be non-null). I'd need to know more to be able to tell what's going wrong. A minimal reproduction would be the best.

**Comment by jtattermusch** [comment]
Also, does this happen with a unary call or a streaming call?
Unary call response is handler here:
https://github.com/grpc/grpc/blob/54749bf49c409a3a0a6a3efc73330e78bbb729d9/src/csharp/Grpc.Core/Internal/AsyncCall.cs#L547 
Streaming call response here:
https://github.com/grpc/grpc/blob/54749bf49c409a3a0a6a3efc73330e78bbb729d9/src/csharp/Grpc.Core/Internal/AsyncCallBase.cs#L336

**Comment by DanFTRX** [comment]
I started hitting this issue after updating a different dependency that caused the linked System.Memory version to be 4.5.4 instead of 4.5.3

**Comment by DanFTRX** [comment]
Yeah, I can hit this on my previously working fine project by just forcing System.Memory version 4.5.4

**Comment by jtattermusch** [comment]
Posting again: Can you provide a minimal project that reproduces the problem? (ideally a github repo?). Thanks!

**Comment by DanFTRX** [comment]
@jtattermusch I'm working on reproducing the issue in a minimal project.

**Comment by DanFTRX** [comment]
[MinReproGRPCIssue.zip](https://github.com/grpc/grpc/files/4594552/MinReproGRPCIssue.zip)
I have built this reproduction case.  There are 3 projects:  Client, Server, and ServiceContract.   Just open the solution and run "Client" to see the issue.    To resolve the issue, change the version of "System.Memory" in "Client" from 4.5.4 to 4.5.3.    Code consists of a single grpc call.

**Comment by DanFTRX** [comment]
@jtattermusch

**Comment by jtattermusch** [comment]
@DanFTRX  I tried your reproduction and wasn't able to reproduce anything unusual.
The "ServiceHost.exe" part of the project seemed suspicious so I modified it to just start a server at a given port (10000) and then ran the client to connect to that port.
When the server was down I got "failed to connect to all addresses" and when it was up, the RPCs were succeeding.

**Comment by jtattermusch** [comment]
@georghinkel  would you be able to provide a reproduction for the originally posted problem?

**Comment by georghinkel** [comment]
Unfortunately, I cannot reproduce the problem in a MVP. In the meantime, I guess my problem was a certificate problem where the client essentially found that the certificate was invalid for whatever reason. The said Java client uses Netty to ignore all certificate problems, which is not possible in the C-based gRPC. When I change the channel credentials to insecure, all problems are gone. 

I can definitely exclude an incompatible System.Memory version because this is at 4.5.3 here.

**Comment by DanFTRX** [comment]
@jtattermusch Interesting, I made the same modification on my local copy and no longer saw the issue.  It seems spawning the process via Process.Start may somehow be related?   Also as for the ServiceHost.exe, it is just a link to the compiled binary of the "Server" project.  It is not distributed with the zip, but built locally as part of your build.

**Comment by DanFTRX** [comment]
@jtattermusch Would you be more comfortable if I put the whole thing on github?  Because my reproduction project has a 100% reproduction rate when run as is.   And I really need this resolved as I have a use case that involves spawned processes running grpc.   Also should I create a new ticket since it seems to be a different issue than OP's here.

**Comment by jtattermusch** [comment]
@DanFTRX  I'm happy to try again if you provide a repro, but please don't involve extraneous stuff like ServiceHost.exe tricks that are unrelated to gRPC. If this is indeed a gRPC issue, there has to be a way of reproducing without it (btw I have no idea how ServiceHost.exe could influence the behavior).

**Comment by DanFTRX** [comment]
@jtattermusch Is it the name of the exe thats bothering you?  "ServiceHost.exe" is just a random name for the compiled "Server" project.  It is not an external trick or anything.  The reproduction steps I have determined are:
    1. Start a client.
    2. The client spawns a child process
    3. The child process starts a grpc server
    4. The client connects to the grpc server
    5. The client makes a grpc request and it fails

The key portion is that its a child process.   Sorry for using the output file name "ServiceHost.exe" because I had forgotten it is the same name as used by Windows for some system services.  But I assure you it has nothing to do with external to the source code issues.  I will change the name of the output exe so its more clear.

**Comment by DanFTRX** [comment]
@jtattermusch Scratch all that, just realized my problem while refactoring to avoid naming.  I had set up my Visual Studio projects to copy the resulting server exe into the client's bin directory, but I had forgotten the exe.config that contained the assembly bindings.

**Comment by jtattermusch** [comment]
@DanFTRX  thanks for updating the issue with the real rootcause.

**Comment by Kryptos-FR** [comment]
@DanFTRX how did you solve it? I have the exact same issue [HelloWorld tutorial](https://github.com/grpc/grpc/tree/master/examples/csharp/Helloworld) with the only change is that I created the projects with the old format. I'm not sure what assembly bindings I have to use to fix it.

**Comment by DanFTRX** [comment]
@Kryptos-FR I made sure every project is explicitly using the same version of System.Memory.  and also make sure the .exe.config is present next to the .exe

**Comment by Kryptos-FR** [comment]
@DanFTRX Seems like my issues were a combination of some bad DLLs in the GAC and a rogue proxy preventing some connections.
Thanks for the reply anyway.

**Comment by perf2711** [comment]
It still happens on .NET Framework 4.7.2. I have "fixed" it by supplying `System.Memory.dll` built for `netstandard2.0`, not for `net461`.

**Comment by szarykott** [comment]
**If the code indeed looks like OP has written**, then the explanation for the error is simple. This [SO questions](https://stackoverflow.com/questions/1896185/nullable-object-must-have-a-value) has it.

It just requires an explicit null check, so relatively simple thing to add.
