### ISSUE TITLE
flake: github/grpc/run_tests/objc_macos_opt_native/ios-test-cronettests

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#22019]
https://source.cloud.google.com/results/invocations/820ef692-5f83-4b07-8e66-74e0266026c6/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-test-cronettests/tests

I've seen this test fail several times recently.

**Comment by yashykt** [comment]
Another failure mode - https://source.cloud.google.com/results/invocations/9d7cdcef-a581-4665-9682-6ee5fe64d46c/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-test-cronettests/tests
