### ISSUE TITLE
Python protobuf doesn't use C++ extensions by default

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#2201]
The [dependency][1]

```python
    install_requires=[
        ...
        'protobuf==3.0.0a3'
    ]
```

does not pass the `--cpp_implementation` flag to `setup.py` for `protobuf` and so does not use the C++ speedups, even if the system libs/headers for `protobuf` are on the system. (Maybe this should be filed with the `protobuf` people?)

[1]: https://github.com/grpc/grpc/blob/d9145d91f542e838827dfdd83978586e2686973f/src/python/src/setup.py#L96

**Comment by dhermes** [comment]
I just filed google/protobuf#539 as well over there.

Even if `protobuf` was already installed, if `--cpp_implementation` was not passed `grpc` may still want to do something like

```bash
pip install --ignore-installed protobuf==3.0.0a3 --install-option="--cpp_implementation"
```

**Comment by soltanmm** [comment]
I'm not sure we can tackle this from our end. [This](https://github.com/pypa/pip/pull/2537) appears to be a fairly recent (note: not necessarily widely available) addition to `pip`. Additionally, there's [this](http://stackoverflow.com/questions/17045817/setuptools-and-passing-options-to-dependencies) unanswered question on StackOverflow.

It's also interesting to note that wanting to support this in the `requirements.txt` file would nix my arguments [here](https://github.com/grpc/grpc/pull/1717#issuecomment-104478472).

**Comment by dhermes** [comment]
I didn't realize `--install-option` was so new. You could still manually download the [source][1] from PyPI and then run `setup.py` with the necessary flag.

----

As for your comment

1.  The `CFLAGS` and `LD_LIBRARY_PATH` path can be mitigated if
    1.  NPN is supported, allowing the installed version of `openssl` to be used instead of shadowing with `openssl 1.0.2` to gain ALPN
    1.  The latest version of `protobuf` is installed as a system library (I'm unclear why it needs to be siloed with homebrew, but maybe there is a reason?)
    1.  The `grpc` source is installed as a system library (again not sure why you don't want this)
    1.  FWIW, under this scenario it'd just be

        ```bash
        curl -fsSL https://goo.gl/getgrpc | sudo bash  # To install JUST system libs
        # All dependencies can be found or install fails with helpful message
        [sudo] pip install grpcio
        ```

1.  You could (should?) use `tox` for tests, then you don't need to worry about `requirements.txt`.
1.  I'm not sure what you mean by `application` in your 2.
1.  See how inheritance [works with `tox`][2].

[1]: https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0a3.tar.gz#md5=6674fa7452ebf066b767075db96a7ee0
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/b975d9cf81c177f38336e4d3ce1fecc7eb692ad3/tox.ini#L20-L21

**Comment by soltanmm** [comment]
> You could still manually download the source from PyPI and then run setup.py with the necessary flag.

I'm not sure how to interpret that with respect to the perspective of a dev-user trying to install our package.

> You could (should?) use tox for tests, then you don't need to worry about `requirements.txt`.

I haven't looked into reconciling that with our use of the `tools/run_tests/run_tests` script with respect to separating out the individual jobs in such a way that `run_tests` is aware of those individual test jobs being separate. Maybe at some point in the future.

> I'm not sure what you mean by application in your 2.

I was being abstract (but why are we discussing this here?).

----

I'll look into `tox` at some point, but overall this seems like an enhancement we can put off for a later date.

**Comment by soltanmm** [comment]
Actually, reading the following made me think of something else:

> iii. The grpc source is installed as a system library (again not sure why you don't want this)

We *could* install it directly into the virtualenv (I think that works linker-wise? still seems a bit futzy). We don't install them as system libraries because we don't want to install libraries under test in such locations (a lot of stuff has been exposed in the C core via the wrapping libraries) and because someone shouldn't need `sudo` to run our tests. Changing the install prefix and `make install`ing could clean that up.

**Comment by dhermes** [comment]
RE: installing in test, you can have an optional prefix that defaults to `/usr` or `/usr/local` and just have the test runner set the environment variable.

----

As for C++ extensions, yes it is something you could put off (or just hope the `protobuf` folks take care of it).

As for "I'm not sure how to interpret that with respect to the perspective of a user/dev trying", I had in mind a simple line in `setup.py` which performed this before the rest of the install. But again it'd be much easier if the `protobuf` folks handled it natively.

**Comment by soltanmm** [comment]
> you can have an optional prefix that defaults to /usr or /usr/local and just have the test runner set the environment variable.

We have that. We just happen to arbitrarily have the test builder and runner set up to use env-vars to point to the build directories.

> it'd be much easier if the protobuf folks handled it natively

I also think that's the more 'right' course of action.

**Comment by dhermes** [comment]
We should just close this out and let google/protobuf#539 run its course.

----

As a follow-up I'd love to open an issue / discussion about what we (myself and @tseaver) see as the "right" way to install for Python:

```
curl -fsSL https://goo.gl/getgrpc | sudo bash  # To install JUST system libs
# All dependencies can be found or install fails with helpful message
[sudo] pip install grpcio
```

(This is of course contingent on `openssl` / NPN issues since we don't want to shadow existing system libs. This may also be an issue with `protobuf` system libs but I don't think so.)

**Comment by soltanmm** [comment]
Sure.
