### ISSUE TITLE
Client-side terminating bidi streams in async server yields tags in random order resulting in crashes

### ISSUE THREAD

**Issue by Rantanen** [grpc/grpc#22021]
### What version of gRPC and what language are you using?

1.18-1.25

### What operating system (Linux, Windows,...) and version?

Windows 10, Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC (VS 2015), GCC 7.4.0

### What did you do?

- Basic async bidi stream that queues `Read`s and listens for `RequestDone`. Once `RequestDone` triggers, the stream cleans itself up by deleting self.
- Two completion queues and two threads reading these.

Full example code in a comment below.

### What did you expect to see?

The async streams work just fine.

### What did you see instead?

The process crashes.

As the client disconnects, the `RequestDone` finishes first, this causes the request-handler to delete itself and as the `Read` operation is being returned from the completion queue (with `done == false`) the context has already been deleted and this causes an access violation.

### Anything else we should know about your project / environment?

We have two servers in the same process as we needed to know through which port the request is coming. One of the endpoints is bound to local interface and one is bound to `0.0.0.0` - requests coming through the local interface have slightly relaxed security requirements. We couldn't find a way to recognize the listening port when serving the request so we ended up instantiating different `Service` implementations that carry the state with them.

**Comment by Rantanen** [comment]
Server:
```C++
#include <iostream>
#include "grpcpp\grpcpp.h"
#include "Generated\service.pb.h"
#include "Generated\service.grpc.pb.h"

using namespace grpc;
using namespace std;

#define TID() "T:" << GetCurrentThreadId() << " "

// Service implementation.
class ServiceImpl : public test::MyService::WithAsyncMethod_StreamStuff<test::MyService::Service> {};

// Various tag values indicating what happened.
enum class Event
{
	NewRequest,
	Read,
	Done,
};

std::ostream& operator<<(std::ostream& out, const Event event)
{
	switch(event)
	{
		case Event::NewRequest:
			return out << "NewRequest";
		case Event::Read:
			return out << "Read";
		case Event::Done:
			return out << "Done";
		default:
			abort();
	}
}

// Tag structure for tracking which operation on what task finished.
struct AsyncStream;
struct Tag
{
	Tag(AsyncStream* op, Event event): op(op), event(event)
	{
		std::cout << TID() << "Create tag, " << op << " -> " << event << std::endl;
	}

	AsyncStream* op;
	Event event;
};

struct AsyncStream
{
	// Constructor queues new request.
	AsyncStream( ServiceImpl* service, ServerCompletionQueue* cq ): service(service), cq(cq), context(), stream(&context)
	{
		service->RequestStreamStuff(&context, &stream, cq, cq, new Tag(this, Event::NewRequest));
		context.AsyncNotifyWhenDone(new Tag(this, Event::Done));
	}

	// Process async event notifications.
	void Process(Event event)
	{
		switch(event)
		{

		// New request for procesing. Queue new one and read the stream.
		case Event::NewRequest:
			new AsyncStream( service, cq );
			stream.Read( &request, new Tag( this, Event::Read ) );
			break;

		// Request is done, client has disconnected the request.
		// Delete the current operation.
		case Event::Done:
			std::cout << TID() << "AsyncStream::Delete " << this << std::endl;
			delete this;
			break;

		// Read event done.
		// In the test the client shouldn't write anything so this should never trigger.
		case Event::Read:
			std::cout << TID() << "AsyncStream::Read " << this << std::endl;
			break;

		// Unknown event. Shouldn't happen.
		default:
			std::cerr << TID() << "Unknown event " << (int)event << std::endl;
		}
	}

	ServiceImpl* service;
	test::Request request;
	grpc::ServerCompletionQueue* cq;
	grpc::ServerContext context;
	grpc::ServerAsyncReaderWriter<test::Response, test::Request> stream;
};

std::thread RunThread( ServiceImpl* service, std::unique_ptr<ServerCompletionQueue> cq ) {
	return std::thread{
		[service = service, cq = move( cq )] {
			std::cerr << GetCurrentThreadId() << std::endl;

			new AsyncStream( service, cq.get() );
			void* ptag;
			bool ok;
			while( cq->Next( &ptag, &ok ) )
			{
				Tag* tag = static_cast<Tag*>(ptag);
				std::cerr << TID() << "Received tag, " << tag->op << " -> " << tag->event;

				if(ok)
				{
					std::cerr << "... Executing" << std::endl;
					tag->op->Process( tag->event );
				}
				else
				{
					std::cerr << "... Cancelling" << std::endl;
				}
				delete tag;
			}
			std::cerr << TID() << "Completion queue stopped" << std::endl;
		}
	};
}

int main() {

	// Endpoint 1
	ServerBuilder builder1;
	ServiceImpl* service1 = new ServiceImpl();
	builder1.RegisterService( service1 );
	builder1.AddListeningPort( "0.0.0.0:5000", InsecureServerCredentials() );
	auto cq1 = builder1.AddCompletionQueue();
	auto server1 = builder1.BuildAndStart();
	std::cerr << "Starting primary thread: ";
	auto thread1 = RunThread( service1, std::move(cq1));

	// (Ensure the RunThread thread has time to write the thread ID before this thread writes more output)
	Sleep( 10 );

	// Endpoint 2
	ServerBuilder builder2;
	ServiceImpl* service2 = new ServiceImpl();
	builder2.RegisterService( service2 );
	builder2.AddListeningPort( "0.0.0.0:5001", InsecureServerCredentials() );
	auto cq2 = builder2.AddCompletionQueue();  // Couldn't get reproduced with one CQ
	auto server2 = builder2.BuildAndStart();
	std::cerr << "Starting secondary thread: ";
	auto thread2 = RunThread(service2, std::move(cq2));

	thread1.join();
	server1->Wait();
	thread2.join();
	server2->Wait();

	return 0;
}
```

Client:
```C++
#include "grpcpp\grpcpp.h"
#include "Generated\service.pb.h"
#include "Generated\service.grpc.pb.h"

using namespace grpc;

int main()
{
	auto channel = CreateChannel( "localhost:5000", InsecureChannelCredentials() );
	auto client = test::MyService::NewStub( channel );

	// Send a request.
	CompletionQueue cq;
	auto stream = client->AsyncStreamStuff( new ClientContext(), &cq, nullptr );

	// Wait for the request to be accepted.
	void* tag;
	bool ok;
	cq.Next( &tag, &ok );

	// Finish the request.
	stream->Finish( new Status(), nullptr );
	return 0;
}
```

Proto:
```protobuf

syntax = "proto3";

package test;

message Request { int32 id = 1; }
message Response { int32 id = 1; }

service MyService {
	rpc StreamStuff ( stream Request ) returns ( stream Response );
}
```

**Comment by Rantanen** [comment]
The above code results in the following server output:

```
Starting primary thread: 67316
T:67316 Create tag, 000002A234559F70 -> NewRequest
T:67316 Create tag, 000002A234559F70 -> Done
Starting secondary thread: 60276
T:60276 Create tag, 000002A23455EFD0 -> NewRequest
T:60276 Create tag, 000002A23455EFD0 -> Done
T:67316 Received tag, 000002A234559F70 -> NewRequest... Executing
T:67316 Create tag, 000002A2345696C0 -> NewRequest
T:67316 Create tag, 000002A2345696C0 -> Done
T:67316 Create tag, 000002A234559F70 -> Read
T:67316 Received tag, 000002A234559F70 -> Done... Executing
T:67316 AsyncStream::Delete 000002A234559F70
```

If the `delete this` on `AsyncStream::Delete` is commented out, the above output is continued with:

```
T:67316 Received tag, 000002A234559F70 -> Read... Cancelling
```

If there is only one completion queue, the output has `Read... Cancelling` _before_ `Done... Executing`

Couple of other highlights:

In the example server above, I'm constructing two servers in different ports. This is mainly to mirror our production case but also to ensure that only one of these queues should be responsible for handling client requests coming to port 5000. The issue reproduces just fine even with one server, as long as that one server then has two completion queues registered for it.

Currently the `AsyncStream` (which is responsible for handling a single request) deletes itself when the tag given to `AsyncNotifyWhenDone` returns from the completion queue. As far as I know, this is the expected behavior, but I haven't seen comprehensive example of how bidi streams should be implemented. The [C++ async server example](https://grpc.io/docs/tutorials/async/helloasync-cpp/) handles only unary requests and does not concern itself with `AsyncNotifyWhenDone`.

A workaround to the issue would be to reference count the request handler based on existing tags and only `delete` the handler once all tags have been returned from the completion queue.

**Comment by Rantanen** [comment]
This seems to be a race condition of some kind. I did further debugging and added some logging into the completion queue `Push`/`Pop` operations. I managed to make the server flaky _even with a single completion queue_.

Below are two test output from the test server with _only one `grpc::Server`/completion queue_. In the failing case, during the first `cq->Next()` call, the completion queue receives two `Push`es: `NewRequest` and `Done`. In the succeeding scenario only the `NewRequest` tag is pushed into the completion queue during the first `cq->Next()` call and once the example server is done processing the `NewRequest`, the next tag pushed is the ´Read` tag, followed by `Done`.

```
PS C:\Dev\Projects\grpc-test-project\x64\Debug> .\HangServer.exe
D0214 21:06:07.170000000 73528 dns_resolver_ares.cc:483] Using ares dns resolver
Starting primary thread: 70788
T:70788 Create tag, 00000252711CB780 for 000002527120A6B0 -> NewRequest
T:70788 Create tag, 00000252711CBA50 for 000002527120A6B0 -> Done
T:70788 Entering cq->Next(...)
D0214 21:06:08.812000000 70788 completion_queue.cc:472] Push: 00000252711CB780
D0214 21:06:08.816000000 70788 completion_queue.cc:504] Pop: 00000252711CB780
D0214 21:06:08.820000000 70788 completion_queue.cc:472] Push: 00000252711CBA50
T:70788 Leaving cq->Next(...)
T:70788 Received tag, 000002527120A6B0 -> NewRequest... Executing
T:70788 Create tag, 00000252711CBE10 for 0000025271215CF0 -> NewRequest
T:70788 Create tag, 00000252711CBE60 for 0000025271215CF0 -> Done
T:70788 Create tag, 00000252711CBEB0 for 000002527120A6B0 -> Read
D0214 21:06:08.839000000 70788 completion_queue.cc:472] Push: 00000252711CBEB0
T:70788 Entering cq->Next(...)
D0214 21:06:08.845000000 70788 completion_queue.cc:504] Pop: 00000252711CBA50
T:70788 Leaving cq->Next(...)
T:70788 Received tag, 000002527120A6B0 -> Done... Executing
T:70788 AsyncStream::Delete 000002527120A6B0
T:70788 Entering cq->Next(...)
D0214 21:06:08.857000000 70788 completion_queue.cc:504] Pop: DDDDDDDDDDDDDDDD
```
```
PS C:\Dev\Projects\grpc-test-project\x64\Debug> .\HangServer.exe
D0214 21:06:10.909000000 71832 dns_resolver_ares.cc:483] Using ares dns resolver
Starting primary thread: 75432
T:75432 Create tag, 0000010F5181BAD0 for 0000010F518597D0 -> NewRequest
T:75432 Create tag, 0000010F5181C020 for 0000010F518597D0 -> Done
T:75432 Entering cq->Next(...)
D0214 21:06:12.829000000 75432 completion_queue.cc:472] Push: 0000010F5181BAD0
D0214 21:06:12.831000000 75432 completion_queue.cc:504] Pop: 0000010F5181BAD0
T:75432 Leaving cq->Next(...)
T:75432 Received tag, 0000010F518597D0 -> NewRequest... Executing
T:75432 Create tag, 0000010F5181C110 for 0000010F518642A0 -> NewRequest
T:75432 Create tag, 0000010F5181C160 for 0000010F518642A0 -> Done
T:75432 Create tag, 0000010F5181BD00 for 0000010F518597D0 -> Read
T:75432 Entering cq->Next(...)
D0214 21:06:12.848000000 75432 completion_queue.cc:472] Push: 0000010F5181BD00
D0214 21:06:12.852000000 75432 completion_queue.cc:472] Push: 0000010F5181C020
D0214 21:06:12.855000000 75432 completion_queue.cc:504] Pop: 0000010F5181BD00
T:75432 Leaving cq->Next(...)
T:75432 Received tag, 0000010F518597D0 -> Read... Cancelling
T:75432 Entering cq->Next(...)
D0214 21:06:12.864000000 75432 completion_queue.cc:504] Pop: 0000010F5181C020
T:75432 Leaving cq->Next(...)
T:75432 Received tag, 0000010F518597D0 -> Done... Executing
T:75432 AsyncStream::Delete 0000010F518597D0
T:75432 Entering cq->Next(...)
```

(Note the line numbers aren't really comparable to the source here as those Push/Pop log messages didn't exist in the codebase and I had to add them there locally.)

**Comment by Rantanen** [comment]
I'm also able to avoid the issue by having the client terminate the connection cleanly. The example client intentionally terminates itself _immediately_ after invoking the asynchronous `stream->Finish()`. Adding a 10 ms sleep after the `stream->Finish()` avoids any issues. Unfortunately requiring the internet to behave isn't really an option for production system. :)

**Comment by Rantanen** [comment]
I'm starting to speculate this has something to do with a race condition of the client having canceled the request before the server has had time to fetch the `NewRequest` from the completion queue. Unfortunately, as far as I can tell, there's no way to tell the request has already finished when processing the `NewRequest`. `context.IsCancelled()` still signals `false` in this case.

**Comment by Rantanen** [comment]
I might be also missing some crucial parts of the service implementation. I did some more investigation on the client side, and I can't get the `stream->Finish()` to complete at all.

One thing I was missing was `SendInitialMetadata()` on the server side. Adding this allows client to complete `ReadInitialMetadata()`. However it feels like I'm still missing something else here. Client is able to `stream->Write()` just fine, but `stream->Finish()` doesn't result in anything happening on the server.

Only terminating the client process results in the `Event::Done` being signaled (with context stating `IsCancelled == 1` - in both the success and failure case).

I tried responding to `Event::Done` by invoking `stream.Finish` on the server-side, but the tag given to `stream.Finish` just ends up returned from `cq->Next` with `ok == false`. It would seem `Event::Done` is the last tag that is returned with `ok == true`, which means it would need to delete the handler (if it should be possible to avoid having the tags reference count the handler).

After the client calls `stream->Finish`, the server does react to it by writing the following log messages (`all,-timer,-timer_check` @ debug verbosity). So some (parts of the?) message seems to reach the server at this point. However I can't tell from that log why the finish never bubbles up from the completion queue.

```
I0215 04:45:08.415000000 77448 completion_queue.cc:979] grpc_completion_queue_next(cq=000001D5EFA81A00, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0000000000000000)
D0215 04:45:08.424000000 77448 completion_queue.cc:957] PENDING TAGS: 000001D5EFA848D0 000001D5EFAC3540 000001D5EFA86BF0 000001D5EFAC4E50
D0215 04:45:08.430000000 77448 completion_queue.cc:984] CQ:000001D5EFA81A00   ref 4 -> 5 next
D0215 04:45:10.779000000 77448 exec_ctx.cc:34] running closure 000001D5EFA87798: created [c:\dev\projects\grpc-test-project\grpc\src\core\lib\iomgr\tcp_windows.cc:520]: scheduled [c:\dev\projects\grpc-test-project\grpc\src\core\lib\iomgr\socket_windows.cc:148]
I0215 04:45:10.794000000 77448 tcp_windows.cc:187] TCP:000001D5EFA87780 on_read
I0215 04:45:10.800000000 77448 tcp_windows.cc:216] READ 000001D5EFA87780 (peer=ipv6:[::1]:26698): 00 00 08 06 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 01 00 00 00 00 00 00 04 08 00 00 00 00 01 00 00 00 05 00 00 04 08 00 00 00 00 00 00 00 00 05 '....................................................'
D0215 04:45:10.814000000 77448 tcp_windows.cc:235] TCP unref 000001D5EFA87780 : read 2 -> 1
I0215 04:45:10.820000000 77448 combiner.cc:167] C:000001D5EFA6EE90 grpc_combiner_execute c=000001D5EFABC640 last=1
D0215 04:45:10.830000000 77448 exec_ctx.cc:43] closure 000001D5EFA87798 finished
I0215 04:45:10.833000000 77448 combiner.cc:231] C:000001D5EFA6EE90 grpc_combiner_continue_exec_ctx contended=0 exec_ctx_ready_to_finish=0 time_to_execute_final_list=0
I0215 04:45:10.842000000 77448 combiner.cc:254] C:000001D5EFA6EE90 maybe_finish_one n=000001D5EFABC640
I0215 04:45:10.850000000 77448 combiner.cc:167] C:000001D5EFA6EE90 grpc_combiner_execute c=000001D5EFABDD58 last=3
D0215 04:45:10.856000000 77448 flow_control.cc:113] 000001D5EFABDB98[1][svr] | s updt recv | trw:                       4194304, tlw:                       4194309, taw:                       4194309, srw:            4194304 -> 4194309, slw:                       4194309, saw:                       4194309
D0215 04:45:10.872000000 77448 flow_control.cc:113] 000001D5EFABDB98[0][svr] | t updt recv | trw:            4194304 -> 4194309, tlw:                       4194309, taw:                       4194309, srw:                              , slw:                              , saw:
I0215 04:45:10.887000000 77448 ref_counted.h:97] chttp2_refcount:000001D5EFABC488 c:\dev\projects\grpc-test-project\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:2592 ref 7 -> 8 keep_reading
I0215 04:45:10.899000000 77448 combiner.cc:167] C:000001D5EFA6EE90 grpc_combiner_execute c=000001D5EFABDEA8 last=5
I0215 04:45:10.905000000 77448 tcp_windows.cc:253] TCP:000001D5EFA87780 win_read
D0215 04:45:10.911000000 77448 tcp_windows.cc:282] TCP   ref 000001D5EFA87780 : read 1 -> 2
I0215 04:45:10.914000000 77448 ref_counted.h:152] chttp2_refcount:000001D5EFABC488 c:\dev\projects\grpc-test-project\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:2605 unref 8 -> 7 keep_reading
I0215 04:45:10.924000000 77448 combiner.cc:296] C:000001D5EFA6EE90 finish old_state=7
I0215 04:45:10.932000000 77448 combiner.cc:231] C:000001D5EFA6EE90 grpc_combiner_continue_exec_ctx contended=0 exec_ctx_ready_to_finish=0 time_to_execute_final_list=0
I0215 04:45:10.940000000 77448 combiner.cc:254] C:000001D5EFA6EE90 maybe_finish_one n=000001D5EFABDD58
I0215 04:45:10.944000000 77448 chttp2_transport.cc:2639] ipv6:[::1]:26698: Complete BDP ping err="No Error"
I0215 04:45:10.948000000 77448 bdp_estimator.cc:50] bdp[ipv6:[::1]:26698]:complete acc=52 est=65536 dt=3.633951 bw=0.000114Mbs bw_est=0.000000Mbs
I0215 04:45:10.955000000 77448 combiner.cc:296] C:000001D5EFA6EE90 finish old_state=5
I0215 04:45:10.955000000 78400 combiner.cc:167] C:000001D5EFA6EE90 grpc_combiner_execute c=000001D5EFABDCB8 last=3
I0215 04:45:10.961000000 77448 combiner.cc:231] C:000001D5EFA6EE90 grpc_combiner_continue_exec_ctx contended=0 exec_ctx_ready_to_finish=0 time_to_execute_final_list=0
I0215 04:45:10.972000000 77448 combiner.cc:254] C:000001D5EFA6EE90 maybe_finish_one n=000001D5EFABDEA8
I0215 04:45:10.977000000 77448 ref_counted.h:97] chttp2_refcount:000001D5EFABC488 c:\dev\projects\grpc-test-project\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:2754 ref 7 -> 8 init keepalive ping
I0215 04:45:10.986000000 77448 ref_counted.h:152] chttp2_refcount:000001D5EFABC488 c:\dev\projects\grpc-test-project\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:2759 unref 8 -> 7 init keepalive ping
I0215 04:45:10.996000000 77448 combiner.cc:296] C:000001D5EFA6EE90 finish old_state=5
I0215 04:45:11.001000000 77448 combiner.cc:231] C:000001D5EFA6EE90 grpc_combiner_continue_exec_ctx contended=1 exec_ctx_ready_to_finish=0 time_to_execute_final_list=0
I0215 04:45:11.009000000 77448 combiner.cc:254] C:000001D5EFA6EE90 maybe_finish_one n=000001D5EFABDCB8
I0215 04:45:11.014000000 77448 bdp_estimator.h:53] bdp[ipv6:[::1]:26698]:sched acc=0 est=65536
I0215 04:45:11.017000000 77448 combiner.cc:296] C:000001D5EFA6EE90 finish old_state=3
```

The client code for the finish is more or less just an additional `cq.Next` after the `stream->Finish`:
```C++
	Sleep( 5 * 1000 );
	std::cerr << "Finish" << std::endl;
	Status status;
	stream->Finish( &status, &status );
	std::cerr << "Waiting finish" << std::endl;
	cq.Next( &tag, &ok );
        return 0;
```

**Comment by Rantanen** [comment]
This just reproduced in Linux as well.

I was looking into the callstacks to see where the early request done push sneaks into the completion queue. This seems to happen through the `RegisterAsyncRequest::FinalizeResult`, which does something with `CompletionOp::FillOps`.

In any case, while I was trying to see whether the difference between Windows and Linux was the early async tag or something else, I added similar logging to my grpc sources in Linux (just a simple `gpr_log(... "Push")` in `CqEventQueue::Push`) - this seemed to throw the timings off enough that now I'm encountering a `pure virtual method called`-crash in Linux as well with the log showing a very similar output:

Successful, with only one `Push` before the `NewRequest` execution:
```
D0217 03:46:37.478498413   10862 tcp_posix.cc:1257]          cannot set inq fd=11 errno=92
D0217 03:46:37.479093274   10862 completion_queue.cc:467]    Push
T:140145453954816 Received tag, 0x7f7620010930 -> NewRequest... Executing
T:140145453954816 Create tag, 0x7f7620009aa0 -> NewRequest
T:140145453954816 Create tag, 0x7f7620009aa0 -> Done
T:140145453954816 Create tag, 0x7f7620010930 -> Read
D0217 03:46:37.479803549   10862 completion_queue.cc:467]    Push
D0217 03:46:37.479848896   10862 completion_queue.cc:467]    Push
T:140145453954816 Received tag, 0x7f7620010930 -> Read... Cancelling
T:140145453954816 Received tag, 0x7f7620010930 -> Done... Executing
T:140145453954816 AsyncStream::Delete 0x7f7620010930
```

Failure with two `Push` before the `NewRequest` execution:
```
D0217 03:46:37.520624716   10862 tcp_posix.cc:1257]          cannot set inq fd=11 errno=92
D0217 03:46:37.521149070   10862 completion_queue.cc:467]    Push
D0217 03:46:37.521348892   10862 completion_queue.cc:467]    Push
T:140145453954816 Received tag, 0x7f7620009aa0 -> NewRequest... Executing
T:140145453954816 Create tag, 0x7f762000b280 -> NewRequest
T:140145453954816 Create tag, 0x7f762000b280 -> Done
T:140145453954816 Create tag, 0x7f7620009aa0 -> Read
D0217 03:46:37.521540886   10862 completion_queue.cc:467]    Push
T:140145453954816 Received tag, 0x7f7620009aa0 -> Done... Executing
T:140145453954816 AsyncStream::Delete 0x7f7620009aa0
pure virtual method called
terminate called without an active exception
Aborted
```

**Comment by Rantanen** [comment]
I'm looking at the grpc internals for reference async stream implementations. `LoadReporterAsyncServiceImpl` seems to be internal usage of async bidi stream in gRPC. This implementation seems to use `std::shared_ptr` to hold a reference to the current handler on the tags to ensure the references stay alive:

https://github.com/grpc/grpc/blob/64fb7d47452e32e8746569bf0d1c19c5d1f1a1d9/src/cpp/server/load_reporter/load_reporter_async_service_impl.cc#L315-L327

Interestingly the `Shutdown` on the last line ends up invoking `stream_.Finish` after `OnDoneNotified`. In my tests I couldn't get the `Finish` to go through and the tag was always returned with `ok == false`.

In any case, all of this differs quite a bit from the basic async service example, where the call handler itself is responsible for invoking `delete this` when it figures it won't be needed anymore. This is a bit misleading once there start being multiple async operations for the same reader/writer/context.

https://github.com/grpc/grpc/blob/64fb7d47452e32e8746569bf0d1c19c5d1f1a1d9/examples/cpp/helloworld/greeter_async_server.cc#L112-L116

Is there a more comprehensive example somewhere? Or alternatively some sort of best practices documentation on implementing async servers?

**Comment by DinoStray** [comment]
> I'm looking at the grpc internals for reference async stream implementations. `LoadReporterAsyncServiceImpl` seems to be internal usage of async bidi stream in gRPC. This implementation seems to use `std::shared_ptr` to hold a reference to the current handler on the tags to ensure the references stay alive:
> 
> https://github.com/grpc/grpc/blob/64fb7d47452e32e8746569bf0d1c19c5d1f1a1d9/src/cpp/server/load_reporter/load_reporter_async_service_impl.cc#L315-L327
> 
> Interestingly the `Shutdown` on the last line ends up invoking `stream_.Finish` after `OnDoneNotified`. In my tests I couldn't get the `Finish` to go through and the tag was always returned with `ok == false`.
> 
> In any case, all of this differs quite a bit from the basic async service example, where the call handler itself is responsible for invoking `delete this` when it figures it won't be needed anymore. This is a bit misleading once there start being multiple async operations for the same reader/writer/context.
> 
> https://github.com/grpc/grpc/blob/64fb7d47452e32e8746569bf0d1c19c5d1f1a1d9/examples/cpp/helloworld/greeter_async_server.cc#L112-L116
> 
> Is there a more comprehensive example somewhere? Or alternatively some sort of best practices documentation on implementing async servers?

I wonder the grpc C++ lib not support bi-di stream async server by now, so the developer afraid of offer more comprehensive example.

**Comment by Rantanen** [comment]
Since this was opened, I'll clarify that the fix I'd expect for this is just better documentation/example. After figuring out what the problem was, it makes sense to me that the streams shouldn't be destroyed before all related tags have been received. So just having better documentation that instructs that the tags may come in arbitrary order and the programmer needs to ensure the related bits are kept alive until all related tags have been resolved should work. This should also be demonstrated in the C++ async example as well.

Although ensuring things are not cleaned up while there's unresolved tags somewhat relies on resolving all tags. This ties into the https://github.com/grpc/grpc/issues/10136 issue (which I believe is still present, but the github issue has been closed as stale again). Our current implementation for this is to keep track of all the alive tags on our side as well and after the gRPC server/CQ has been shut down, we'll go through the remaining tags and delete those.

**Comment by jtattermusch** [comment]
@Rantanen  feel free to open a PR that improves the documentation.

**Comment by Rantanen** [comment]
Is there any information what would be the idiomatic implementation?

There's at least two problems that I don't have an obvious answer for: What is a tag and how is the request instance referenced. The way we've gone is to use `Tag` interface. The way the load reporter above is implemented is to use tags that carry `std::function` that knows what to call in continuation.

For the request instance, the load balancer is passing `std::shared_ptr<Self> self` to each request method that needs to create new tags while we ended up using `enable_shared_from_this`. `enable_shared_from_this` is more convenient, but having to pass the `shared_ptr` around manually gives better compile-time guarantees that the developer is calling methods that they are allowed to call. This also results in compile time guarantees that whoever is calling those methods has a shared_ptr on their hand that keeps the request alive.

**Comment by yashykt** [comment]
I'm sorry that this didn't get any attention. 
>What is a tag and how is the request instance referenced. The way we've gone is to use Tag interface. The way the load reporter above is implemented is to use tags that carry std::function that knows what to call in continuation.

sounds correct.

We've been suggesting moving to the C++ async callback API which should be easier to use and understand. We've also added a bunch of examples surrounding it.
