### ISSUE TITLE
Build fail on Ubuntu while building core/lib/iomgr/socket_utils_common_posix.cc

### ISSUE THREAD

**Issue by loics2** [grpc/grpc#22035]
### What version of gRPC and what language are you using?
I'm trying to compile `v1.27.2`, and I also tried `1.26.0`.

### What operating system (Linux, Windows,...) and version?
Ubuntu 19.10 eoan

### What runtime / compiler are you using (e.g. python version or version of gcc)
cmake version 3.13.4
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

### What did you do?

I followed the [CMake installation instructions](https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make)

```bash
git clone -b v1.27.2 https://github.com/grpc/grpc
cd grpc
mkdir build
cd build
cmake ..
make
```

### What did you expect to see?
A successful compilation.

### What did you see instead?

The compilation fail with the following error : 
```
[ 12%] Building CXX object CMakeFiles/grpc_unsecure.dir/src/core/lib/iomgr/socket_utils_common_posix.cc.o
In file included from /home/loic/dev/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc:36:
/usr/include/netinet/tcp.h:112:17: error: redeclaration of ‘uint8_t tcphdr::<unnamed union>::<unnamed struct>::th_off’
  112 |  uint8_t th_off:4; /* data offset */
      |                 ^
/usr/include/netinet/tcp.h:109:10: note: previous declaration ‘uint8_t tcphdr::<unnamed union>::<unnamed struct>::th_off’
  109 |  uint8_t th_off:4; /* data offset */
      |          ^~~~~~
/usr/include/netinet/tcp.h:113:16: error: redeclaration of ‘uint8_t tcphdr::<unnamed union>::<unnamed struct>::th_x2’
  113 |  uint8_t th_x2:4; /* (unused) */
      |                ^
/usr/include/netinet/tcp.h:108:10: note: previous declaration ‘uint8_t tcphdr::<unnamed union>::<unnamed struct>::th_x2’
  108 |  uint8_t th_x2:4; /* (unused) */
      |          ^~~~~
make[2]: *** [CMakeFiles/grpc_unsecure.dir/build.make:1129: CMakeFiles/grpc_unsecure.dir/src/core/lib/iomgr/socket_utils_common_posix.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:272: CMakeFiles/grpc_unsecure.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

### Anything else we should know about your project / environment?
Nope

**Comment by markdroth** [comment]
This looks like it must be some sort of problem with your system headers.  The relevant lines in /usr/include/netinet/tcp.h are:

```
# if __BYTE_ORDER == __LITTLE_ENDIAN
        uint8_t th_x2:4;        /* (unused) */
        uint8_t th_off:4;       /* data offset */
# endif
# if __BYTE_ORDER == __BIG_ENDIAN
        uint8_t th_off:4;       /* data offset */
        uint8_t th_x2:4;        /* (unused) */
# endif
```

The only way I can see that both definitions of `th_off` could be used is if `__LITTLE_ENDIAN` is defined to the same value as `__BIG_ENDIAN`.  That seems to imply a fairly serious compiler installation problem.

I don't think this is a gRPC issue.

**Comment by loics2** [comment]
You're right, it doesn't seem to be a gRPC issue.

I tried to reinstall `gcc`, `g++`, and the Linux headers, and even downgrade `gcc` and `g++` to `8.3`, and it looks like `__BYTE_ORDER`, `__LITTLE_ENDIAN` and `__BIG_ENDIAN` are not correctly defined...
