### ISSUE TITLE
Custom serializer for C# while still using auto generated code

### ISSUE THREAD

**Issue by IIFE** [grpc/grpc#22038]
Hi,

Is it possible to specify a custom serializer/deserializer when using Grpc.Core for C#, while still making use of the auto generated code?

I found [this example](https://github.com/Horusiath/GrpcSample) that uses a custom serializer, however it's quite verbose as I have to define the descriptors for each request/response, instead of relying on the auto generated code.

What I'm looking for is to continue to use the auto generated code, but be able to specify a custom serializer for the auto code generation (i.e. is it possible to change the code generation to use a custom supplied serializer)?

Thanks

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question.
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
