### ISSUE TITLE
Bazel python rules could support specifying output path flag of protoc.

### ISSUE THREAD

**Issue by SilverTux** [grpc/grpc#22033]
### Is your feature request related to a problem? Please describe.
When using py_proto_library and py_grpc_library bazel rules the user cannot specify a location where these rules will generate the py files. It would be good to have a new attribute for these rules which can be used to pass a prefix for _--python_out=_ flags value.

### Describe the solution you'd like
A good solution could be as the following:
```
py_proto_library(
    name = "my_generated_python_sources",
    deps = [":my_proto_files"],
    out_path = "path/to/generate",
)
```

### Describe alternatives you've considered
There is no good alternative solution which is easy to use. If a user want to generate python sources for proto files which are organized well to subdirectories than she/he needs to use custom written genrules to copy generated files.

### Additional context
None.

**Comment by SilverTux** [comment]
I have created a PR to solve this #22034

**Comment by yashykt** [comment]
The PR seems to be in progress.
