### ISSUE TITLE
Error in cmake file for cpp helloworld external project example

### ISSUE THREAD

**Issue by nisargshah95** [grpc/grpc#22037]
### What version of gRPC and what language are you using?
gRPC v1.27.0 (but applies to master branch too)
Language: C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
cmake 3.10.2

### What did you do?
Build helloworld C++ example using external cmake file at 

https://github.com/grpc/grpc/blob/cce83b9971f3f28c820abc3c00122a10ee076c3e/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt#L57
```
  SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../../third_party/protobuf/cmake"
```
This makes cmake clone the protobuf repository into `${CMAKE_CURRENT_SOURCE_DIR}/../../../../third_party/protobuf/cmake` directory and attempt to build it by looking for a CMakeLists.txt file in that directory, which is not found. The fix here should be
```
  SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../../third_party/protobuf"
  SOURCE_SUBDIR cmake
```
`SOURCE_SUBDIR` option makes cmake look for CMakeLists.txt file under `cmake` directory of the protobuf repository.

**Comment by yashykt** [comment]
Please send out a PR for the fix. Thanks!

**Comment by nisargshah95** [comment]
Not an issue.
