### ISSUE TITLE
Huge increase of Android/iOS binary sizes

### ISSUE THREAD

**Issue by ronnylt** [grpc/grpc#22040]
### What version of gRPC and what language are you using?
- Upgrading from version 1.23 to 1.27
- Using Unity experimental package

### What runtime / compiler are you using
Unity package / Native extension for Android / Native extension for iOS

### What did you do?
I am upgrading from  version 1.23 to 1.27 using the Unity package.

### What did you expect to see?
Similar size of the binary native extension. 

### What did you see instead?
The size of the binary native extension has doubled in size. 

In Android, from ~20MB  to ~42MB
In iOS, from ~90MB to ~208 MB

This makes the package near to unusable in mobile. Something happened from version 1.23 onwards that provoked the compiled code to double in size.

Can you please help with this? Thanks

**Comment by ronnylt** [comment]
Related: https://github.com/grpc/grpc/issues/20252

**Comment by nicolasnoble** [comment]
See my comments in the e-mail thread:

https://groups.google.com/forum/#!msg/grpc-io/EfHQaXnAuic/0EPRmQWxAwAJ

Most of the size you're seeing is debug symbols, which exist for, well, debugging purposes. You need to strip the binaries out of debug symbols when creating your release packages. The *actual* code footprint is closer to 5MB.

**Comment by AkhilRaja** [comment]
> See my comments in the e-mail thread:
> 
> https://groups.google.com/forum/#!msg/grpc-io/EfHQaXnAuic/0EPRmQWxAwAJ
> 
> Most of the size you're seeing is debug symbols, which exist for, well, debugging purposes. You need to strip the binaries out of debug symbols when creating your release packages. The *actual* code footprint is closer to 5MB.

How do I strip the debug symbols? Is there a documentation you can point me to or an already stripped version I could use please ?
