### ISSUE TITLE
No VerifyPeerCallback equivalent in C++

### ISSUE THREAD

**Issue by IIFE** [grpc/grpc#22059]
### Is your feature request related to a problem? Please describe.
I am unable to use custom verification of self signed server certificate from the client side when using C++

### Describe the solution you'd like
In the .NET implementaition of gRPC, there is the `VerifyPeerCallback` functionality that allows the client side to provide custom verification of the SSL credentials. There does not appear to be an equivalent functionality in the C++ implementation.

Does such functionality exist in any form using the C++ implementation, or has it not been considered for C++?

### Describe alternatives you've considered
No possible alternative if wanting to only use C++ for the client.

### Additional context
gRPC on Windows, installed using vcpkg and targeting Visual Studio 2015.

**Comment by markdroth** [comment]
Jiangtao, what's the current status of the verify peer callback in C++?  Do we expose this?

**Comment by georghinkel** [comment]
Actually, the very same verify callback functionality exposed to .NET is also available for C++, namely giving you the chance to discard a connection _after_ a successful handshake, see #21474

**Comment by IIFE** [comment]
@georghinkel I can't see it available in C++? How exactly can it be hooked up?

Thanks.

**Comment by georghinkel** [comment]
@IIFE It is not really exposed, but the C++ wrapper is very thin, so it is easy for you to get that in. You just have to add this method to circumvent the Surface API:

```
// Builds SSL Credentials given SSL specific options
std::shared_ptr<ChannelCredentials> SslCredentials(
    const SslCredentialsOptions& Options, const verify_peer_options* verify_peer_options) {
  grpc::GrpcLibraryCodegen init;  // To call grpc_init().
  grpc_ssl_pem_key_cert_pair pem_key_cert_pair = {
      options.pem_private_key.c_str(), options.pem_cert_chain.c_str()};

  grpc_channel_credentials* c_creds = grpc_ssl_credentials_create(
      options.pem_root_certs.empty() ? nullptr : options.pem_root_certs.c_str(),
      options.pem_private_key.empty() ? nullptr : &pem_key_cert_pair, verify_peer_options,
      nullptr);
  return WrapChannelCredentials(c_creds);
}
```

However, as said, this still has the same limitations of the verify peer callback in the C core: The callback is only executed after a successful handshake, so it won't allow you to connect to servers that have certificate problems (such as self-signed certificates where you don't know the CA), it only allows you to discard the connection if you want to pose extra requirements onto the certificate. In other words, the callback does not replace the builtin verification, it only extends it.

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question.
Please direct questions to https://groups.google.com/g/grpc-io so that the wider community can help answer.
