### ISSUE TITLE
SSL vs. TLS

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc#22071]
### Is your feature request related to a problem? Please describe.
There is a new standard for lab Automation that is based on the gRPC protocol and requires implementors to use TLS, accepting also self-signed certificates.

### Describe the solution you'd like
In all examples I have seen so far, encrypted connections with gRPC are done using classes that map to the SSL functions in the C-core of gRPC even when the example was specifically about TLS, e.g. [TLS support for gRPC in C#](https://stackoverflow.com/questions/47271629/tls-support-for-grpc-in-c-sharp).

So my simple question is, what does gRPC use at the moment, if you use the classes that have SSL in their name and boil down to `grpc_ssl_credentials_create`? Is it still SSL 3.0? I have seen that gRPC also has `grpc_tls_credentials_create`, but this is in experimental namespace and has no mapping to the language-specific wrappers.

Is there a Roadmap somewhere when TLS is planned to be supported officially, including wrappers?

**Comment by mehrdada** [comment]
gRPC definitely supports modern TLS (and it always has)! Unfortunately, the security functions were originally named using the colloquial synonym "`ssl`".  The new functions named `tls_*` basically utilize the same underlying TLS protocol--the real difference is the semantics under which they validate the other party's identity.  Original `ssl` functions utilize the HTTPS way of validating third-party identity vs `tls` use SPIFFE-conforming naming validation conventions.

**Comment by jiangtaoli2016** [comment]
@ZhenLian @yihuazhang 
grpc_tls_credentials_create is the new credentials we are developing for
- support SPIFFE credential as well as traditional web PKI style SSL credentials
- credential reloading
- server authorization (secure naming) check

This is still WIP (just minor cleanup remains). We will deprecate grpc_ssl_credentials_create.

**Comment by mehrdada** [comment]
@jiangtaoli2016 I'd say the new API has *major* issues and horribly broken and needs patching and that has remained unaddressed, despite me frequently pointing it out; see: https://github.com/grpc/grpc/issues/20161 and elsewhere.

The memory ownership of arguments needs careful revisiting. It frees a `const char*` for example!!! https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.cc#L168

We run a patch internally similar to the PR I authored here but I don't have bandwidth to fix broader implications and fix all tests.

**Comment by jiangtaoli2016** [comment]
@mehrdada We will fix as soon as possible. Stay tuned. 
I did not notice this issue until now.

**Comment by georghinkel** [comment]
Thanks for the info!

**Comment by duanbing** [comment]
hi,  @jiangtaoli2016 @georghinkel, Can you help to take a look at this question?

**Comment by ZhenLian** [comment]
@duanbing I left some comments. Let's just iterate on that SO question, since this is a closed issue.
