### ISSUE TITLE
C# client: Unobserved ObjectDisposedException after disposing channel

### ISSUE THREAD

**Issue by alexrp** [grpc/grpc#22097]
### What version of gRPC and what language are you using?

```
$ dotnet list package
...
   > Google.Protobuf                                3.10.0      3.10.0
   > Grpc.Net.Client                                2.26.0      2.26.0
   > Grpc.Tools                                     2.25.0      2.25.0
...
```

### What operating system (Linux, Windows,...) and version?

`Microsoft Windows [Version 10.0.19041.21]`

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26
```

### What did you do?

Connected to an unsecured (no TLS) gRPC service, made a successful duplex streaming call, and disposed the channel.

### What did you expect to see?

No errors.

### What did you see instead?

I have a handler set up on `TaskScheduler.UnobservedTaskException` so bugs in my program don't go unnoticed. Because of that, I saw this:

```
Unhandled exception. System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.
Object name: 'System.Net.Sockets.ExposedSocketNetworkStream'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.ExposedSocketNetworkStream'.
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.FlushOutgoingBytesAsync()
   --- End of inner exception stack trace ---
   at Crux.Launcher.Program.<>c.<Main>b__0_0(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Users\alex\source\repos\crux\src\launcher\Program.cs:line 14
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
```

This occurs shortly after disposing the channel.

### Anything else we should know about your project / environment?

Unfortunately I've not managed to create a reliable repro yet. This happened once out of many hundreds of runs of my application. Worse yet, it's a private code base, so I can't even point to a GitHub repository. 😢 If I manage to repro it with more logging/tracing enabled, I'll update this issue.

I realize this is not much to go on at all, but I thought I would post it in case anyone has a hunch as to what could be causing it.

**Comment by jtattermusch** [comment]
This issue belongs to https://github.com/grpc/grpc-dotnet (as uses Grpc.Net.Client nuget and not Grpc.Core)
