### ISSUE TITLE
support request path prefix

### ISSUE THREAD

**Issue by qlisc** [grpc/grpc#22106]
### Is your feature request related to a problem? Please describe.
The Issue is specific to *grpc-c++*. 
We have two gRPC services 'A' and 'B' that implement the same proto service definition. These two service server hosts are behind the same gateway.  At the gateway, we need a way to figure out if the client gRPC request is for 'A' or 'B' and route the request to their backend service servers. Our gateways supports routing based on request's :authority or :path header.

We use cronet transport to take advantage of QUIC and other benefits from cronet. We found client fails to set authority header if cronet channel is used. From grpc source code https://github.com/grpc/grpc/blob/master/src/core/ext/transport/cronet/transport/cronet_transport.cc#L1445, looks like authority header is not supported from grpc-cronet interface. 

We are wondering if gRPC-C++ can add prefix request path support to allow client to prefix original gRPC request path.  In this way, "A" and "B" requests can have different request path. Our gateway can route these requests to their own backend service hosts.

### Describe the solution you'd like
Choice 1 (preferred). support set path prefix for each RPC request. ie add set path prefix api to ClientContext.
Choice 2. (if choice 1 is not doable). Support path prefix per channel or client stub. ie add set path prefix channel argument.

### Describe alternatives you've considered
support set authority header from grpc - cronet transport

**Comment by markdroth** [comment]
The fact that the path is the RPC service and method name is a pretty fundamental part of the gRPC-over-HTTP/2 protocol.  We do not want to support changing the path.

I don't actually understand why you can't do what you want via normal virtual hosting.  If the names in DNS (or whatever name service you're using) for services A and B both point to the same gateways, and you have some clients talking to A and others talking to B, shouldn't cronet automatically set the ":authority" header based on the name that the client tried to connect to?  Why do you need the ability to override the ":authority" header?

To ask that question a different way, if you can change the clients to override the ":authority" header, can't you also just change the target URI that you create the channel to?

**Comment by qlisc** [comment]
@markdroth, thanks for the response. We will consider this option. I mostly work on client side. Based on our backend engineer's feedback, using different DNSs may cause security risks by adding wildcarded domains to clients. They will review this with our security team. Based on my understanding, the security risks is related to wildcard domain certificates and :authority header override doesn't need wildcard certs.

**Comment by markdroth** [comment]
Okay.  I'm going to go ahead and close this, since I don't think there's anything actionable here for gRPC.  We're not going to support path prefixes, so even if your security folks don't want to take the approach I suggested, I think your next step would be to try to convince the cronet folks to support overriding the authority header.

Good luck!
