### ISSUE TITLE
[http] gRPC removes `:authority` inbound metadata

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc#22105]
### What version of gRPC and what language are you using?
gRPC 1.27.2, issue is in grpc-core so language is not important.

### What did you do?
Accept external gRPC traffic, check `:authority` inbound metadata in business logic (for domain assertion, logging, setting cookies, etc).

### What did you expect to see?
`:authority` inbound metadata contains the hostname of the request, e.g. www.example.com.

### What did you see instead?
`:authority` inbound metadata is missing.

It looks like grpc-core removes the `:authority` header from inbound metadata:
https://github.com/grpc/grpc/blob/master/src/core/lib/surface/server.cc#L760-L761

Can this header be preserved? This access is read only, and therefore doesn't provide any security concerns.

**Comment by yashykt** [comment]
gRPC metadata iirc have the restriction that they cannot start with a ':'. What I think is doable is providing a getter method for authority through ServerContext.

@vjpai @markdroth thoughts on a getter method to get the host/authority?

**Comment by markdroth** [comment]
I would be okay with a getter method for authority on ServerContext.  But we'd need @a11r to approve as well.

**Comment by apolcyn** [comment]
This should already be available in the `host` field of the `grpc_call_details` object?

Whether or not that `grpc_call_details` object is surfaced on wrapped language APIs might be another matter. But, for example, it's effectively plumbed into the `host()` getter of the C++ `GenericServerContext` (https://github.com/grpc/grpc/blob/c342345a9e426ca5e657a7c789a94ae54ae694ef/include/grpcpp/impl/codegen/async_generic_service.h#L44).
