### ISSUE TITLE
GRPC Python 2.7: import grpc fails with "ImportError: No module named enum"

### ISSUE THREAD

**Issue by ustiugov** [grpc/grpc#22109]
### What version of gRPC and what language are you using?
1.27.2 (but it seems that older versions are affected)

### What operating system (Linux, Windows,...) and version?
Linux aa7ca59c4759 4.11.0-13-generic #19~16.04.1-Ubuntu (in Docker)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.17

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```
docker run -it --rm --cpus=1 -m=512m -p 50051:50051 ubuntu:latest bash
>>>>>(inside container)
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/grpc/__init__.py", line 18, in <module>
    import enum
ImportError: No module named enum

```
### What did you expect to see?
import grpc should not fail

### What did you see instead?
import grpc failed
### Anything else we should know about your project / environment?
The error appears with other Ubuntu and grpc versions.

**Comment by ustiugov** [comment]
A workaround is to downgrade enum34 module to 1.1.6.

**Comment by lidizheng** [comment]
@ustiugov Please upgrade to Python 3, which has built-in `enum` library. After 2020, we are not providing support for Python 2 issues.
