### ISSUE TITLE
Explicitly state bazel version support

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc#22115]
### Is your feature request related to a problem? Please describe.
I had a hard time trying to build grpc from sources. A lot of error messages that seemed to lead nowhere. In the end, it turned out that it was just that the bazel configuration for the most recent bazel version 2.1.4 was missing.

### Describe the solution you'd like
It would be nice to explicitly state the required bazel version range in the docs. Yes, there is a debug message in the build saying that no configuration for bazel 2.1.4 could be loaded, but I underestimated how bad that is. All my problems disappeared after installing bazel 1.0.0 (and Wheel in the Python 2.7 that came with it -- I only had Python 3.7).

**Comment by nicolasnoble** [comment]
We've already addressed this using bazel itself: if you rely on a normal distribution of bazel, we have a hijack of its invocation done automatically using our own settings: https://github.com/grpc/grpc/blob/master/tools/bazel

Obviously, we don't want to override things on a global scope if you include gRPC into your own project, but when building the repository only, this override should happen automatically:

```
~/sources/grpc (master)$ bazel
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 1.0.0 will be used instead of system-wide bazel installation.
Starting local Bazel server and connecting to it...
                                                           [bazel release 1.0.0]
```
