### ISSUE TITLE
Verify self-signed 'localhost' certificate fails. Implementing checkServerIdentity callback has no effect

### ISSUE THREAD

**Issue by sjkummer** [grpc/grpc#22111]
### What version of gRPC and what language are you using?
1.24.2

### What operating system (Linux, Windows,...) and version?
macOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Node

### What did you do?
Enabling SSL/TLS using a self-signed "localhost" certificate. Both instances are running on the same machine.
No CA certificate is used, as desribed here: https://github.com/grpc/grpc/issues/9761

Server
```
const grpcCredentials = grpc.ServerCredentials.createSsl(null,
          [ {
            'cert_chain': cert,
            'private_key': key }
          ], false);
```

Client:
```
const verifyOptions: grpc.VerifyOptions = {
        checkServerIdentity: (hostname: string, cert: Certificate) => {
          return undefined;
        }
      };
      const grpcCredentials = grpc.credentials.createSsl(null, null, null, verifyOptions);
```

Certificate generation:
```
openssl req -x509 -out localhost.crt -keyout localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```
https://letsencrypt.org/de/docs/certificates-for-localhost/

### What did you expect to see?
The client should establish a connection to the server using SSL/TLS.

### What did you see instead?
The client refuses the certificate, even though it was accepted / set to "trust always" in the keychain and the `VerifyOptions` callback never throws an error.

`E0223 13:16:22.291976000 4557901248 ssl_transport_security.cc:1245]    Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.`

**Comment by georghinkel** [comment]
The verify peer callback is only executed after a successful handshake, see #21474. I created a PR to resolve this, but waiting for Feedback (#21588)

**Comment by ZhenLian** [comment]
Hi @sjkummer 
I am not quite familiar with the details in Nodejs, but it looks like you didn't specify any trust certificates in your client side code? In order to make the self-signed cert work, we need to set the same cert we used in server side as the trust certs in client side. This is basically telling the client to trust whoever possesses the certificate, which in your case is the server.
After fixing that, you might also encounter some default hostname check error like this https://github.com/grpc/grpc/issues/22119, and you can refer to the solution there. Again, I am not familiar with the language details in Node.js but feel free to reach out again if any problem still exists and I could have someone else to look into it.

**Comment by sjkummer** [comment]
@ZhenLian Thanks for your hint!

I now got the localhost certificate working by leaving the RootCert empty on server side but passing the servers localhost-cert as RootCert on client, plus using the overrides in the options.

Server: 
```
const grpcCredentials = grpc.ServerCredentials.createSsl(null,
          [ {
            'cert_chain': cert,
            'private_key': key }
          ], false);
```

Client:
`const grpcCredentials = grpc.credentials.createSsl(cert, null, null, verifyOptions);
`

Overrides:
```
options['grpc.ssl_target_name_override'] = 'localhost';
options['grpc.default_authority'] = 'localhost';
```

**Comment by ZhenLian** [comment]
@sjkummer  Really glad to see it works! Please do not hesitate to reach out if you have any other questions. Cheers! :-)
