### ISSUE TITLE
Ruby Jenkins flake: GRPC::RpcServer#run with no connect_metadata should receive metadata if a deadline is specified

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2212]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/307/config=dbg,language=ruby,platform=linux/console

(Triggered by ObjC change #2209)

```
Failures:

  1) GRPC::RpcServer#run with no connect_metadata should receive metadata if a deadline is specified
     Failure/Error: expect(stub.an_rpc(req, deadline, k1: 'v1', k2: 'v2')).to be_a(EchoMsg)
     GRPC::BadStatus:
       4:Deadline Exceeded
     # ./lib/grpc/generic/active_call.rb:46:in `check_status'
     # ./lib/grpc/generic/active_call.rb:191:in `finished'
     # ./lib/grpc/generic/active_call.rb:328:in `request_response'
     # ./lib/grpc/generic/client_stub.rb:159:in `request_response'
     # ./lib/grpc/generic/service.rb:179:in `block (3 levels) in rpc_stub_class'
     # ./spec/generic/rpc_server_spec.rb:392:in `block (4 levels) in <top (required)>'

Finished in 11.56 seconds (files took 0.59283 seconds to load)
15 examples, 1 failure

Failed examples:

rspec ./spec/generic/rpc_server_spec.rb:384 # GRPC::RpcServer#run with no connect_metadata should receive metadata if a deadline is specified
```

Maybe related to #1782?

**Comment by tbetbetbe** [comment]
The failure is 'Deadline Exceeded' meaning that the test is running an rpc against a server and the server is failing to respond in reasonable time.  This specific test whose description states 'should receive metadata if a deadline is specified' deliberately sets a deadline to confirm that metadata
is still received even when the deadline is set.

I will leave this open, but plan no further action - there is no fix in ruby code

**Comment by tbetbetbe** [comment]
@jayantkolhe - removing from Beta

**Comment by tbetbetbe** [comment]
Closing, has not been seen in months
