### ISSUE TITLE
Question: How to use GRPC_TLS_SKIP_ALL_SERVER_VERIFICATION in Python

### ISSUE THREAD

**Issue by crash-g** [grpc/grpc#22127]
As far as I have understood the `GRPC_TLS_SKIP_ALL_SERVER_VERIFICATION` option can be used to make a client skip the verification of a server certificate. Is there a way to get this behavior from Python?

grpcio version: 1.26.0

**Comment by lidizheng** [comment]
@yihuazhang Can you take a look at this question? I don't have enough context on this option.

**Comment by yihuazhang** [comment]
@crash-g, Unfortunately, `GRPC_TLS_SKIP_ALL_SERVER_VERIFICATION` is only available in gRPC C-core TLS credentials (i.e., `grpc_tls_credentials_create()` in `grpc_security.h`) and its C++ wrapper. Currently, Python SSL wrapper is based on gRPC C-core SSL stack which does not provide that option.

**Comment by yashykt** [comment]
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
