### ISSUE TITLE
Why protobuf message is support == operator in the route guide example for python? 

### ISSUE THREAD

**Issue by laobaox** [grpc/grpc#22126]
the route guide example for python
https://github.com/grpc/grpc/blob/master/examples/python/route_guide/route_guide_server.py

```
def get_feature(feature_db, point):
    """Returns Feature at given location or None."""
    for feature in feature_db:
        if feature.location == point:
            return feature
    return None
```

the feature.location is a protobuf message Point object, I am confused, why is it support compare ? 
 I can not find any document for that ? 
Is it fit for other language except python ？

**Comment by gnossen** [comment]
[Protobuf Python certainly supports this feature](https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/message.py#L74). The way to do this sort of thing varies from language to language. For example, in Go, [it's a function, not a method](https://godoc.org/github.com/golang/protobuf/proto#Equal), but every language has a way to determine the equality of two protocol buffer message objects.

**Comment by laobaox** [comment]
> [Protobuf Python certainly supports this feature](https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/message.py#L74). The way to do this sort of thing varies from language to language. For example, in Go, [it's a function, not a method](https://godoc.org/github.com/golang/protobuf/proto#Equal), but every language has a way to determine the equality of two protocol buffer message objects.

thanks
