### ISSUE TITLE
Cannot connect to bidirectional stream

### ISSUE THREAD

**Issue by slavabulgakov** [grpc/grpc#22120]
### What version of gRPC and what language are you using?
1.24.2, swift

### What operating system (Linux, Windows,...) and version?
iOS 12.4

### What did you do?
There is bidirectional stream service:
```proto
service TypingService {
   rpc TypingStream (stream OutgoingTyping) returns (stream IncomingTyping);
}
```
I try to connect to it by following code:
```swift
let headers = ...
let callOptions = GRPCMutableCallOptions()
callOptions.flowControlEnabled = true
callOptions.setHeaders(headers)
callOptions.keepaliveInterval = 5
callOptions.keepaliveTimeout = 2
callOptions.userAgentPrefix = "MyUserAgent"
callOptions.retryEnabled = true
let path = "/com.example.messages.TypingService/TypingStream"
let requestOptions = GRPCRequestOptions(host: "...", path: path, safety: .default)
call = GRPCCall2(requestOptions: requestOptions, responseHandler: responseHandler, callOptions: callOptions)
call?.start()
call?.receiveNextMessages(1)
```
### What did you expect to see?
A started stream without any errors

### What did you see instead?
I instantly get callback in the method `func didClose(withTrailingMetadata trailingMetadata: [AnyHashable: Any]?, error: Error?)` in class which conforms to GRPCResponseHandler with error `"grpc_status":2, unknown, No status received`:
```
Error Domain=io.grpc Code=2 "{"created":"@1582558092.202200000","description":"No status received","file":".../src/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1080,"grpc_status":2}" UserInfo= {io.grpc.HeadersKey={
}, io.grpc.TrailersKey={
    "content-length" = 0;
    date = "Mon, 24 Feb 2020 15:28:12 GMT";
    server = nginx;
}, NSDebugDescription={"created":"@1582558092.202200000","description":"No status received","file":".../src/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1080,"grpc_status":2}, NSLocalizedDescription=No status received}
```

### Anything else we should know about your project / environment?
However the same service perfectly works with `grpc-java`.

**Comment by yashykt** [comment]
Since, this is grpc swift, the issues are tracked here - https://github.com/grpc/grpc-swift/issues

**Comment by yashykt** [comment]
Opened a corresponding issue - https://github.com/grpc/grpc-swift/issues/788

**Comment by slavabulgakov** [comment]
@yashykt An issue occurred using objective-c grpc framework, not grpc swift

**Comment by yashykt** [comment]
I see. In that case, let's reopen this

**Comment by muxi** [comment]
From the error message it looks like something going on in the HTTP/2 layer. Particularly, the HTTP/2 stack of gRPC parsed a HEADER frame as trailer but the contents of the HEADER frame seem to be actually a header, not a trailer. I think we will need the message sequence between your client and server to tell what happened exactly. Can you provide that?

(If you do not have other tools, gRPC logs could be one way to obtain that. To enable it, assuming you are using TLS channel which is the default, set GRPC_TRACE=DEBUG and GRPC_VERBOSITY=secure_endpoint as environment variable and get the logs from the console)

**Comment by yulin-liang** [comment]
Closing since we are not hearing response. We can reopen if necessary.
