### ISSUE TITLE
Can Server sends request to Client?

### ISSUE THREAD

**Issue by Codes-Breaker** [grpc/grpc#22143]
### Is your feature request related to a problem? Please describe.
I am new to RPCs, and it is really fun to play with, but I am a bit confused about Client and Server. For example, sometimes server needs to check or get some status from the client side by sending rpcs. Is it possible for the server to send active request instead of receiving requests passively?

**Comment by yashykt** [comment]
You can have a client and a server running inside the same process. So, you can simply start a gRPC client/server alongside the existing server/client. Please direct further questions to https://groups.google.com/g/grpc-io
