### ISSUE TITLE
What protocols do gRPC services in these two examples use for transport? 

### ISSUE THREAD

**Issue by grassit** [grpc/grpc#22164]
The wikipedia article for gRPC says that gRPC uses HTTP/2 as its transport protocol. Is that always true?

 1. In the HelloWorld example of grpc for C#:
    
    In the service:
    https://github.com/grpc/grpc/blob/v1.27.0/examples/csharp/Helloworld/GreeterServer/Program.cs
    
        Server server = new Server
        {
            Services = { Greeter.BindService(new GreeterImpl()) },
            Ports = { new ServerPort("localhost", Port, ServerCredentials.Insecure) }
        };
    
    In the client:
    https://github.com/grpc/grpc/blob/v1.27.0/examples/csharp/Helloworld/GreeterClient/Program.cs
    
        Channel channel = new Channel("127.0.0.1:50051", ChannelCredentials.Insecure);
    
    Which protocol does the gRPC service in the example use for
    transport?  Does it use TCP directly for transport?
 2. In another example in
    https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio-code,
    it creates an ASP.NET Core gRPC Server.
    
    In its client
    
        using var channel = GrpcChannel.ForAddress("https://localhost:5001");
    
    Which protocol does the gRPC service in the example use for
    transport?

  

Thanks.

**Comment by yashykt** [comment]
HTTP/2 is the default transport to be used. gRPC Core does provide transports for inproc and cronet for relevant cases.

I believe in your examples HTTP/2 is used by default as the transport.

Also, please use https://groups.google.com/g/grpc-io for questions so that the wider community may be able to help answer.
