### ISSUE TITLE
Please upgrade dependency on io_bazel_rules_go to the current version.

### ISSUE THREAD

**Issue by bimargulies-google** [grpc/grpc#22172]
grpc_deps is pulling in an old version of rules_go (0.18.5). 

 rules_go 0.18.5 is not compatible with Go 1.13 or newer.

**Comment by noahdietz** [comment]
Thanks for opening this, I'm affected by the same issue and I'm unable to upgrade rules_go in https://github.com/googleapis/googleapis (it's pretty outdated). Thanks @yashykt for opening a fix so quickly.

**Comment by yashykt** [comment]
As seen on the bug, there seem to be issues with doing this upgrade.

**Comment by yashykt** [comment]
@jtattermusch do you know if we can start using bazel 1.2.0 for our infrastructure?

**Comment by jtattermusch** [comment]
We would really like to keep the bazel 1.0.0 compatibility unless it's absolutely necessary to break it.

**Comment by noahdietz** [comment]
I figured out a workaround for the shared dependency issue.

**Comment by yashykt** [comment]
@noahdietz Please share the workaround so that others might be able to benefit too. :)

**Comment by noahdietz** [comment]
@yashykt download `rules_go` and load its dependencies before gRPC in your WORKSPACE file, like we are doing here: https://github.com/googleapis/googleapis/blob/master/WORKSPACE#L79-L104

Then gRPC won't bring in its own, older version of `rules_go`

**Comment by yashykt** [comment]
Thanks @noahdietz
