### ISSUE TITLE
TIMEOUT: ios-test-cfstream-tests

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22181]
https://source.cloud.google.com/results/invocations/b7254e93-ad34-43a2-bf25-d39264528e11/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_objc_macos_opt_native/tests

**Comment by yashykt** [comment]
ping

**Comment by muxi** [comment]
This has been filed as bug to Kokoro team

**Comment by yulin-liang** [comment]
Fixed: #24473
