### ISSUE TITLE
false positive in grpc_is_epollexclusive_available()

### ISSUE THREAD

**Issue by tbuyukliev** [grpc/grpc#22182]
### What version of gRPC and what language are you using?
1.27.3, C++

### What operating system (Linux, Windows,...) and version?
VMware ESXi 6.7

`grpc_is_epollexclusive_available()` checks that the invalid EPOLLEXCLUSIVE | EPOLLONESHOT flag combination fails with EINVAL and declares success, but not that any other valid combination that has EPOLLEXCLUSIVE succeeds.

VMware's VMkernel supports epoll, but not EPOLLEXCLUSIVE. it returns EINVAL just because it sees the unsupported flag and `grpc_is_epollexclusive_available()` returns true.

the end of the function should be changed to also do a positive check, for example:

```C++
  // Now check that EPOLLEXCLUSIVE is supported at all.
  ev.events =
      static_cast<uint32_t>(EPOLLET | EPOLLIN | EPOLLEXCLUSIVE);
  if (epoll_ctl(fd, EPOLL_CTL_ADD, evfd, &ev) != 0) {
    if (!logged_why_not) {
      gpr_log(GPR_DEBUG,
              "epoll_ctl with EPOLLEXCLUSIVE failed with error: "
              "%d. Not using epollex polling engine.",
              errno);
      logged_why_not = true;
    }
    close(fd);
    close(evfd);
    return false;
  }

  close(evfd);
  close(fd);
  return true;
}
```

also it will be good the file descriptors to be closed by RAII.

**Comment by yashykt** [comment]
Hi, please send out the change in the form of a pull request

**Comment by tbuyukliev** [comment]
we'll send a pull request in the coming weeks.

**Comment by yashykt** [comment]
shouldn't have been closed. Sorry about that
