### ISSUE TITLE
Translate comments in Python example to English

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#22196]
https://github.com/grpc/grpc/blob/master/examples/python/data_transmission/client.py has some comments written in a language other than English, I believe it is Chinese. Please fix.

**Comment by lidizheng** [comment]
@vjpai This is contributed by an external contributor who wanted to check-in a Chinese example, and we thought it might be beneficial to our repo. The content of example doesn't contain additional information than others.

**Comment by vjpai** [comment]
Oh, ok, I just passed the text into translate and I see that the Chinese version is just translated below in English already. This confused some students at a Hackathon.
