### ISSUE TITLE
raspberry pi: C++ grpc build error

### ISSUE THREAD

**Issue by pluggee** [grpc/grpc#22203]
### What version of gRPC and what language are you using?
v1.27.3 for C++

### What operating system (Linux, Windows,...) and version?
```
Distributor ID:	Raspbian`
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
```

### What did you do?
I followed the build instructions
```
git clone -b v1.27.3 https://github.com/grpc/grpc
cd grpc
git submodule update --init
mkdir -p cmake/build
cd cmake/build
cmake ../.. -DgRPC_INSTALL=ON -DCMAKE_BUILD_TYPE=Release
make -j4
```

I also tried v.1.26.0 with the same exact result

### What did you expect to see?
Expected to see successful build, it build properly on my x86 Ubuntu 18.04

### What did you see instead?
```
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc: In member function ‘virtual void PerAEADTest_UnalignedInput_Test::TestBody()’:
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:545:54: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH + 1];
                                                      ^
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:546:58: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t nonce[EVP_AEAD_MAX_NONCE_LENGTH + 1];
                                                          ^
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:547:39: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t plaintext[32 + 1];
                                       ^
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:548:32: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t ad[32 + 1];
                                ^
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:566:75: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t ciphertext[sizeof(plaintext) + EVP_AEAD_MAX_OVERHEAD];
                                                                           ^
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:574:45: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t out[sizeof(ciphertext)];
                                             ^
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc: In member function ‘virtual void PerAEADTest_Overflow_Test::TestBody()’:
/home/pi/git/grpc/third_party/boringssl/crypto/cipher_extra/aead_test.cc:588:50: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH];
                                                  ^`
```

### Anything else we should know about your project / environment?
I tried it on rasperry pi 4 (2GB RAM) and raspberry pi 3, same exact result.

**Comment by ebomfim** [comment]
I have the same problem. Someone have a idea when that could be fix? There are some workaround meanwhile?

**Comment by pluggee** [comment]
I was able to build, here's what I did

1- I edited `grpc/third_party/boringssl/CMakeLists.txt` and removed `-Werror` from GCC flags, that way it will continue to build on warnings. The only warnings I saw where in test functions, so I'm assuming the build is ok except I want to run tests on a raspberry pi
2- I added `atomic` to `target_link_libraries` in `grpc/CMakeLists.txt` and `+LDFLAGS += -latomic` in `grpc/Makefile`, for raspberry pi `std::atomic` to link
3- I also had to do the same for protobuf, add `+LDFLAGS="$LDFLAGS -latomic"` in `grpc/third_party/protobuf/configure.ac` to link successfully

please let me know if there are any adverse effects that I don't see, it would be nice if the team consider adding the switches for arm raspberry pi builds

**Comment by yashykt** [comment]
This problem itself seems specific to boringssl, and your workaround seems fine to me till boringssl fixes it. 

(Having different knobs for different platforms might be worthwhile but I don't think specific problem warrants it.)

**Comment by ntsipes** [comment]
@pluggee Could you share where in the file you make the changes detailed in 2 and 3? I'm having the same issue.
