### ISSUE TITLE
System.IO.IOException "Failed to bind port" when explicitly binding to IPv4 and IPv6 "unspecified" addresses

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [grpc/grpc#22200]
### What version of gRPC and what language are you using?
C#
NuGet package v2.27.0 

### What operating system (Linux, Windows,...) and version?
Windows 10 Version 1909

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019 v16.4.5
.NET Classic v4.5

### What did you do?
```
class Program
{
    const int Port = 50051;

    public static void Main(string[] args)
    {
        Server server = new Server
        {
            Services = { Greeter.BindService(new GreeterImpl()) },
            Ports = {
                // IPv4
                new ServerPort("0.0.0.0", Port, ServerCredentials.Insecure),
                // IPv6
                new ServerPort("[::]", Port, ServerCredentials.Insecure) }
        };
        server.Start();

        Console.WriteLine("Greeter server listening on port " + Port);
        Console.WriteLine("Press any key to stop the server...");
        Console.ReadKey();

        server.ShutdownAsync().Wait();
    }
}
```

### What did you expect to see?
// netstat -ao | Findstr 50051
//   TCP    0.0.0.0:50051          MYCOMPUTER:0        LISTENING
//   TCP    [::]:50051             MYCOMPUTER:0        LISTENING

### What did you see instead?

The line "server.Start()" crashes with `System.IO.IOException: 'Failed to bind port "[::]:50051"'`.
If I swap the order of the ports, I get the following exception:
`System.IO.IOException: 'Failed to bind port "0.0.0.0:50051"'`

### Anything else we should know about your project / environment?
The same code works fine when using the loopback addresses:
```
class Program
{
    const int Port = 50051;

    public static void Main(string[] args)
    {
        Server server = new Server
        {
            Services = { Greeter.BindService(new GreeterImpl()) },
            Ports = {
                // IPv4
                new ServerPort("127.0.0.1", Port, ServerCredentials.Insecure),
                // IPv6
                new ServerPort("[::1]", Port, ServerCredentials.Insecure) }
        };
        server.Start();

        Console.WriteLine("Greeter server listening on port " + Port);
        Console.WriteLine("Press any key to stop the server...");
        Console.ReadKey();

        server.ShutdownAsync().Wait();
    }
}
```
netstat -ao | Findstr 50051
  TCP    127.0.0.1:50051        MYCOMPUTER:0        LISTENING
  TCP    [::1]:50051            MYCOMPUTER:0        LISTENING

**Comment by Science-and-Motion-Sports** [comment]
By the way, it seems like gRPC automatically connects to IPv4 AND IPv6 when using EITHER "0.0.0.0" OR "[::]", but not when using EITHER "127.0.0.1" OR "[::1]".

// C#
new ServerPort("localhost", 50051, ServerCredentials.Insecure)
// netstat -ao | Findstr 50051
//   TCP    127.0.0.1:50051        MYCOMPUTER:0        LISTENING       29660
//   TCP    [::1]:50051            MYCOMPUTER:0        LISTENING       29660
 
// C#
new ServerPort("127.0.0.1", 50051, ServerCredentials.Insecure)
// netstat -ao | Findstr 50051
//   TCP    127.0.0.1:50051        MYCOMPUTER:0        LISTENING       26344
 
// C#
new ServerPort("[::1]", 50051, ServerCredentials.Insecure)
// netstat -ao | Findstr 50051
//   TCP    [::1]:50051            MYCOMPUTER:0        LISTENING       14372
 
// C#
Ports = {
    new ServerPort("127.0.0.1", Port, ServerCredentials.Insecure),
    new ServerPort("[::1]", Port, ServerCredentials.Insecure) }
// netstat -ao | Findstr 50051
//   TCP    127.0.0.1:50051        MYCOMPUTER:0        LISTENING       15312
//   TCP    [::1]:50051            MYCOMPUTER:0        LISTENING       15312

// C#
new ServerPort("0.0.0.0", 50051, ServerCredentials.Insecure)
// netstat -ao | Findstr 50051
//   TCP    0.0.0.0:50051          MYCOMPUTER:0        LISTENING       4876
//   TCP    [::]:50051             MYCOMPUTER:0        LISTENING       4876
 
// C#
new ServerPort("[::]", 50051, ServerCredentials.Insecure)
// netstat -ao | Findstr 50051
//   TCP    0.0.0.0:50051          MYCOMPUTER:0        LISTENING       17676
//   TCP    [::]:50051             MYCOMPUTER:0        LISTENING       17676
 
// C#
Ports = {
    new ServerPort("0.0.0.0", Port, ServerCredentials.Insecure),
    new ServerPort("[::]", Port, ServerCredentials.Insecure) }
System.IO.IOException: 'Failed to bind port "[::]:50051"'

**Comment by yashykt** [comment]
That is right. 0.0.0.0 and :: are wildcard addresses and gRPC treats them the same. So you do not need to provide both of them.

Also, 127.0.0.1 and ::1 are localhost addresses and treated different from the previous two. There doesn't seem to be an action item here.
