### ISSUE TITLE
Break apart system library install from language library install

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#2220]
Follow-up from #2201.

For dynamic languages (Python, Ruby, Node), the system libraries (`openssl`, `protobuf`, `grpc`) are required to build the C/C++ extensions for those libraries.

However, the process does not need to be coupled (and arguably shouldn't be coupled). So installing the libraries would be it's own phase

```bash
$ # To install libs SYSTEM-WIDE, use root
$ curl -fsSL https://goo.gl/getgrpc | sudo bash
$ # To install libs locally, set a prefix (and don't use root)
$ curl -fsSL https://goo.gl/getgrpc | bash -s PREFIX="/path/to/install/prefix"
```

and then the language installs can check for the present of the needed headers and includes files and fail with a helpful message if not found:

```bash
[sudo] pip install grpcio
[sudo] gem install grpc
[sudo] npm install [--global] grpc
```

This would also make it so that the funky options in the [install script]

```
gem install grpc -- --with-grpc-dir=$brew_root
CXXFLAGS=-I${brew_root}/include LDFLAGS=-L${brew_root}/lib npm install --global grpc
CFLAGS=-I${brew_root}/include LDFLAGS=-L${brew_root}/lib pip install grpcio
```

could be detected as either the default prefix (`/usr` or `/usr/local`) or some other environment variable (or installer CLI argument) which indicates the prefix used.

/cc @soltanmm 

[1]: https://raw.githubusercontent.com/grpc/homebrew-grpc/98889dade81d033ff2883d240264259f263054db/scripts/install

**Comment by soltanmm** [comment]
i didn't respond to this particular bit in the previous issue because I didn't think it was the proper place. That said...

What exactly is different between what you're suggesting and what we currently have?

**Comment by dhermes** [comment]
@soltanmm The prefixes are used in the default install script (which points to some location owned by homebrew on both Linux and OS X):

- [ruby][1]
- [node][2]
- [python][3]

----

The difference is the "break apart" I am mentioning. It really is the content of https://goo.gl/getgrpc that I am referring to, because installing from source already supports using any prefix you like.

The difference is that users won't want to / know how to install from source, so the recommended install should "just work" and the two scenarios above (local prefix vs. system `/usr`) reasonably cover this.

[1]: https://github.com/grpc/homebrew-grpc/blob/98889dade81d033ff2883d240264259f263054db/scripts/install#L93
[2]: https://github.com/grpc/homebrew-grpc/blob/98889dade81d033ff2883d240264259f263054db/scripts/install#L104
[3]: https://github.com/grpc/homebrew-grpc/blob/98889dade81d033ff2883d240264259f263054db/scripts/install#L115

**Comment by soltanmm** [comment]
Ah, okay. I didn't realize we were discussing the brew bits.

cc @tbetbetbe

**Comment by dhermes** [comment]
Yeah sorry. I am specifically targeting the install story from the **user** perspective. And as of right now, a user needs to be pretty determined to get gRPC installed

**Comment by murgatroid99** [comment]
You can see that I referenced this issue from #2231. I think once we do that, we can fix this a lot more simply.

**Comment by dhermes** [comment]
Awesome to hear! Thanks for the pointer!

**Comment by tbetbetbe** [comment]
@dhermes - just to clarify for @jayantkolhe 
- so far, we have been aiming for a one-line installer focusing on a non-system install of grpc
- the thrust of this issue is that since we can't know whether a user wants a system install or otherwise, our installation instructions should not actually favor the non-system install as it currently does
- i.e we should always have two steps rather than one

**Comment by dhermes** [comment]
Also `linux-brew` is essentially unknown by Linux users.

**Comment by tbetbetbe** [comment]
@dhermes - we're updating the docs to reflect that we now have a installable debian package.
For now, on other linux distros, the advice is to install from source, other installers are tracked in other PRs. e.g, #1209

Just checking, 
- once #2990 is done and a follow-up to clear up other references to linuxbrew from the docs, do you agree that this issue is resolved ?

**Comment by dhermes** [comment]
That's great. And the debian installer doesn't install any libs for dynamic languages right? (e.g. Python, Ruby, Node, PHP) It's just the core? If yes, I suppose we can close this.

**Comment by tbetbetbe** [comment]
#2990 is submitted, so this can be closed

**Comment by dhermes** [comment]
:+1: Yay!
