### ISSUE TITLE
Programmatically defining an http proxy with authentication

### ISSUE THREAD

**Issue by NicholasAzar** [grpc/grpc#22224]
### Is your feature request related to a problem? Please describe.
Currently it seems like there's no api available to define the http proxy outside of environment variables. This is an issue when application code is running in an environment where exposing these parameters may not be per the best practices of the organization especially when credentials are involved.

I've seen #12815 and #13323 which don't provide an answer that would cover this case and was wondering if there's anything like this already available? Or whether it's possible to have it built in?

To add, I'm particularly interested in the .net library specifically.

### Describe the solution you'd like
I would like to see an api which supports programmatically defining an http proxy (with authentication).

### Additional context
https://github.com/googleapis/google-cloud-dotnet/issues/4446

**Comment by vadimi** [comment]
@NicholasAzar I think you might be able to achieve something like that in C# by specifying `default_authority` channel option - `new ChannelOption(ChannelOptions.DefaultAuthority, hostPort)`. This is how I was able to proxy grpc requests through envoy and linkerd. You need to make sure your proxy is grpc aware (envoy/linkerd/nginx). I'm not sure how to do authentication though.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
