### ISSUE TITLE
C# server - apply server config/retry policy

### ISSUE THREAD

**Issue by IIFE** [grpc/grpc#22243]
### What version of gRPC and what language are you using?
1.27.1-1

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Core C# libraries

### What did you do?
I want to apply [server config](https://github.com/grpc/grpc/blob/master/doc/service_config.md) on a C# server so that I can use [retry policies](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retry-policy) on server methods.

### What did you expect to see?
To be able to apply server config/retry policy on C# server.

### What did you see instead?
Could not find a way to apply server config/retry policy on C# server.

**Comment by jtattermusch** [comment]
Can you point me to and example of what is possible in terms of retry policies in some other language (e.g. Java or C++) and is not possible in C#?

**Comment by IIFE** [comment]
@jtattermusch 

[This class](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html) in Java allows clients to specify server config.

[This one in go](https://github.com/grpc/grpc-go/blob/master/service_config.go) also seems to allow the same.

No clear example available in C# (core) to do the same.

**Comment by jtattermusch** [comment]
AFAIK You can use service config in C# by setting the `grpc.service_config` channel argument
https://github.com/grpc/grpc/blob/c333aac06033369a6f6d66b5b6b31a0b56dfb4cd/include/grpc/impl/codegen/grpc_types.h#L296

In C# you can specify the argument as a `ChannelOption` when creating a channel https://github.com/grpc/grpc/blob/c333aac06033369a6f6d66b5b6b31a0b56dfb4cd/src/csharp/Grpc.Core/ChannelOptions.cs#L32

**Comment by IIFE** [comment]
Set it to what exactly, a JSON string, a comma separate string, etc?

This needs documenting.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/c333aac06033369a6f6d66b5b6b31a0b56dfb4cd/include/grpc/impl/codegen/grpc_types.h#L296 I posted before says:
`/** Service config data in JSON form.
    This value will be ignored if the name resolver returns a service config. */`
