### ISSUE TITLE
A crash related to BoringSSL

### ISSUE THREAD

**Issue by SarielTang** [grpc/grpc#22249]
Hello, I encountered a problem related to BoringSSL. We introduced Tencent Cloud's SuperPlayer player in the iOS project. When using GRPC, it will crash.
Tencent feedback is that they also use BoringSSL, but have renamed it, I do not know why it will cause GRPC crash.
The error message is as follows:
![image](https://user-images.githubusercontent.com/12050371/76070207-172e4a00-5fcf-11ea-8b69-1892e3902f4c.png)

**Comment by SarielTang** [comment]
grpc version is 1.23.0

**Comment by muxi** [comment]
It looks like symbol conflict between the two BoringSSL binaries. gRPC has its own BoringSSL version (BoringSSL-GRPC) and renames its symbols to avoid conflicts when linking with other OpenSSL/BoringSSL copies coexist in the same application.

In this particular case, from what you post it appears to me that both gRPC and the Tencent library are trying to do the same thing (i.e. package a private BoringSSL copy) but both fail to rename the [`ssl_crypto_x509_method`](https://github.com/google/boringssl/blob/0b710a305b42b67522003a314dea3e3868485665/ssl/ssl_x509.cc#L499) symbol.

The renaming process is not trivial and hard to get right, as it's not directly modifying BoringSSL code, but rather extract symbols to rename from BoringSSL binary, then write a prefix headers to force renaming of these symbols. We got OpenSSL part right; people are linking with grpc and other libraries with OpenSSL dependency without issue, but unfortunately from your report it looks like it's broken when it coexists with another BoringSSL copy.

One thing that worth notes is, we have a draft PR (#21194) related to this issue. It replaces our custom symbol renaming process with the same process provided by BoringSSL (but in experimental state). It potentially could help with the difficulties we are having here and catch a few more symbols that we should have renamed. However, I just did an experiment with that change and found that even with BoringSSL's renaming process, `ssl_crypto_x509_method` is not correctly renamed. So I don't think that will be helpful for your situation.

Right now I do not have a good suggestion for you. There could be some way to correctly rename `ssl_crypto_x509_method` in gRPC but I don't think we will be able to take a look on that soon. You can ask Tencent and see if they can rename the symbol (and potentially some other similar symbols) on their side too; if that's possible that'll allow your application to build. Or feel free to contribute to gRPC (or BoringSSL) to improve the renaming process of the BoringSSL symbols.

**Comment by davidben** [comment]
`ssl_crypto_x509_method` is a C++ symbol, which BoringSSL's process will rename via C++ inline namespaces. That's also why your tools are probably not picking them up. C++ has better mechanisms for this.

**Comment by muxi** [comment]
Ha that's interesting. I built as BoringSSL instructed, and then used nm to check the symbols and found the symbol's name not changed. Maybe did something wrong; will check again.

**Comment by muxi** [comment]
@davidben - hey it looks you're right. I was looking at a stale binary

@SarielTang - so it looks like #21194 will make it work for you. I'll try to get it merged

**Comment by Shyrou** [comment]
Hey, in case it helps someone, my colleague Julian just opened [this PR](https://github.com/grpc/grpc/pull/26109) to the gRPC guys. We encountered a similar issue when trying to use gRPC with another lib on IOS, both including BoringSSL. 
The issue gets solved by adding a couple of compiler flags when building gRPC.
