### ISSUE TITLE
Error to build from release source code

### ISSUE THREAD

**Issue by jackonan** [grpc/grpc#22248]
### What version of gRPC and what language are you using?
version: v1.26.0, v1.25.0
language: c++

### What operating system (Linux, Windows,...) and version?
Ubuntu

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 5.4.0
cmake version 3.5.1

### What did you do?
I download the source code from some release version, such as v1.25.0, and then try to build.
But errors happen. I want to figure out whether I can build from release source code.
Here are my steps.

wget https://github.com/grpc/grpc/archive/v1.25.0.tar.gz
tar -zxf v1.25.0.tar.gz 
mkdir build
cd build
cmake ../grpc-1.25.0/

### What did you expect to see?
cmake succeed.

### What did you see instead?

CMake Warning at cmake/benchmark.cmake:27 (message):
  gRPC_BENCHMARK_PROVIDER is "module" but BENCHMARK_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:137 (include)

CMake Error at cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /path/grpc-1.25.0/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:138 (include)

CMake Warning at cmake/cares.cmake:33 (message):
  gRPC_INSTALL will be forced to FALSE because gRPC_CARES_PROVIDER is
  "module"
Call Stack (most recent call first):
  CMakeLists.txt:138 (include)

CMake Warning at cmake/gflags.cmake:24 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:139 (include)

CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)

CMake Warning at cmake/ssl.cmake:34 (message):
  gRPC_SSL_PROVIDER is "module" but BORINGSSL_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:141 (include)

CMake Warning at cmake/zlib.cmake:29 (message):
  gRPC_ZLIB_PROVIDER is "module" but ZLIB_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:143 (include)

### Anything else we should know about your project / environment?
No

**Comment by veblush** [comment]
Please check the similar issue (https://github.com/grpc/grpc/issues/22231).
