### ISSUE TITLE
[C#] Add stream reader ReadAllAsync method

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#22250]
### Is your feature request related to a problem? Please describe.
Follow-up to #19060

Is there any plan for a `.netstandard2.1` targeting version? It's a bit annoying that we are not able to use C#8 feature on `IAsyncStreamReader`.

### Describe the solution you'd like
```csharp
var namesRequestStream = f.ResponseStream;
await foreach (var request in namesRequestStream.ReadAllAsync())
{
    ServiceLogger.LogInformation("Result: {result}", request);
}
``` 

### Describe alternatives you've considered
```csharp
var namesRequestStream = f.ResponseStream;

// Variant 1: The old way
while (await namesRequestStream.MoveNext())
{
    ServiceLogger.LogInformation("Result: {result}", namesRequestStream.Current);
}

// Variant 2: Using ForEachAsync but having to return Task.CompletedTask
await namesRequestStream.ForEachAsync(request => {
    ServiceLogger.LogInformation("Result: {result}", namesRequestStream.Current);
    return Task.CompletedTask;
});

// Variant 3: Using ForEachAsync with async delegate but creating a code warning
await namesRequestStream.ForEachAsync(async request => {
    ServiceLogger.LogInformation("Result: {result}", namesRequestStream.Current);
});
``` 

### Additional context
We can not use grpc-dotnet since our application has to target `.netcore3.1` and we don't want to include the full AspNetCore stuff.

// @JamesNK @jtattermusch

**Comment by Falco20019** [comment]
One idea would be to add a reference to `Grpc.Net.Common` in the `Grpc.Core` target for `.netstandard2.1`.

**Comment by JamesNK** [comment]
Grpc.Core referencing Grpc.Net.Common would create a circular dependency.

The best solution is to add the ReadAllAsync extension method to Grpc.Core.Api and update Grpc.Net.Common to type forward to it.

The difficulty here is Grpc.Core.Api only supports a certain version of C#. ReadAllAsync uses async yield which is only available in the most recent version of C#. This is the reason we didn't add it to Grpc.Core.Api.

Need to either:
1. Allow Grpc.Core.Api to use the required version of C# for async yield, or
2. Create an IAsyncEnumerable implementation that doesn't use async yield

**Comment by Falco20019** [comment]
Looks like that’s just the way it will be right now, right? Then we can close the issue.
