### ISSUE TITLE
Error including latest Unity package ("Could not load signature of Google.Protobuf.ByteString:get_Span")

### ISSUE THREAD

**Issue by kcarlson** [grpc/grpc#22251]
### What version of gRPC and what language are you using?
grpc_unity_package.2.29.0-dev csharp

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2019.3.3f1

### What did you do?
I downloaded the last unity package (2.29.0) from https://packages.grpc.io/, extracted it to the Asset/Plugins folder.

### What did you expect to see?
No errors, normal unity editor environment.

### What did you see instead?
Two errors, multiple occurrences of the former, one off the latter:
1) Error: Could not load signature of Google.Protobuf.ByteString:get_Span due to: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>

2) Unloading broken assembly Assets/Plugins/Google.Protobuf/lib/net45/Google.Protobuf.dll, this assembly can cause crashes in the runtime

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by kcarlson** [comment]
This seems to happen after grpc_unity_package.2.26.0-dev, so grpc_unity_package.2.26.0-dev and prior do not elicit the same error message

**Comment by nicolasnoble** [comment]
This may not be on grpc, but on protobuf? Although I think we're building that package.

**Comment by canghwan** [comment]
https://issuetracker.unity3d.com/issues/could-not-load-file-or-assembly-error-when-assembly-dependency-is-in-another-folder?_ga=2.195835948.1013030992.1586163171-425932875.1567394600

I not sure it clearly solve a bug.
I gather all of dll in same folder then error message disappeared.
platform build testing in progress, but editor is clearly fine.

**Comment by ZCube** [comment]
System.Memory uses 4.0.1.1 (.net sdk 4.5.3) for grpc and 4.0.1.0 (.net sdk 4.5.2) for protobuf.

Unity3D cannot have two versions of dependencies.

in Google.Protobuf.csproj
```
...
  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.2"/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" Version="1.0.0"/>
    <!-- Needed for the net45 build to work on Unix. See https://github.com/dotnet/designs/pull/33 -->
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="All" Version="1.0.0"/>
  </ItemGroup>

  <!-- Needed for netcoreapp2.1 to work correctly. .NET is not able to load the assembly without this -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2"/>
  </ItemGroup>
...
```

in Grpc.Core.csproj
```
...
  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.3" />
  </ItemGroup>
...
```

**Comment by ZCube** [comment]
workaround here

```
@rem System.Memory 4.0.1.0 -> 4.0.1.1
@rem warn: this remove sign from Google.Protobuf.DLL
@rem .netfx 4.6.1 tools tested
"ildasm" /UNICODE /all /text Google.Protobuf.dll /out=Google.Protobuf.il
powershell -Command "(gc Google.Protobuf.il) -replace '.ver 4:0:1:0', '.ver 4:0:1:1' | Out-File -encoding UNICODE Google.Protobuf-mod.il"
@rem need admin permission or Could not create output file, error code=0x80070005
"ilasm.exe" /DLL "%CD%\Google.Protobuf-mod.il" "/output:Google.Protobuf.dll" "/resource=Google.Protobuf.res"
del /q Google.Protobuf*.il
del /q Google.Protobuf.res
```

**Comment by drew-512** [comment]
Thanks for driving this, ZCube!

**Comment by mchiang-goo** [comment]
> This seems to happen after grpc_unity_package.2.26.0-dev, so grpc_unity_package.2.26.0-dev and prior do not elicit the same error message

Using 2.26-0-dev causes another error when I import generated csharp files: 

`error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments`

Environment and tools used:
Unity 2019.2.13f1
protoc 3.12.4
grpc_csharp_plugin (from grpc.tools 2.31.0)

What is the consensus on a solve for these related issues?

**Comment by mchiang-goo** [comment]
> > This seems to happen after grpc_unity_package.2.26.0-dev, so grpc_unity_package.2.26.0-dev and prior do not elicit the same error message
> 
> Using 2.26-0-dev causes another error when I import generated csharp files:
> 
> `error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments`
> 
> Environment and tools used:
> Unity 2019.2.13f1
> protoc 3.12.4
> grpc_csharp_plugin (from grpc.tools 2.31.0)
> 
> What is the consensus on a solve for these related issues?

I ended up getting things working by using an older version of protoc and grpc_csharp_plugin:

Mac OSX Mojave
- Protoc (v3.8) and grpc_csharp_plugin ([grpc-protoc_macos_x64-1.26.0-dev.tar.gz](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)) was used to compile and generate code files from proto.
- [grpc_unity_package.2.26.0-dev.zip](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)

**Comment by cloutiertyler** [comment]
> > > This seems to happen after grpc_unity_package.2.26.0-dev, so grpc_unity_package.2.26.0-dev and prior do not elicit the same error message
> > 
> > 
> > Using 2.26-0-dev causes another error when I import generated csharp files:
> > `error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments`
> > Environment and tools used:
> > Unity 2019.2.13f1
> > protoc 3.12.4
> > grpc_csharp_plugin (from grpc.tools 2.31.0)
> > What is the consensus on a solve for these related issues?
> 
> I ended up getting things working by using an older version of protoc and grpc_csharp_plugin:
> 
> Mac OSX Mojave
> Unity 2019.2.13f1
> 
> * Protoc (v3.8) and grpc_csharp_plugin ([grpc-protoc_macos_x64-1.26.0-dev.tar.gz](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)) was used to compile and generate code files from proto.
> * [grpc_unity_package.2.26.0-dev.zip](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)

@mchiang-goo Having the exact same issue. Is that the latest version of protobuf that this will work with?

**Comment by mchiang-goo** [comment]
@cloutiertyler Yup, just reference protobuf/src with -I. My very messy script to generate files looks like this:

```
$PROTOC_PATH \
-I ~/workspace/github/googleapis \
-I ~/workspace/github/protobuf/src \
-I ~/Downloads/protoc-3.11.1-osx-x86_64/include \
--csharp_out $OUT_PATH \
--grpc_out $OUT_PATH \
$PROTO_PATH/assistant/embedded/v1alpha2/embedded_assistant.proto $PROTO_PATH/type/latlng.proto $PROTO_PATH/api/annotations.proto $PROTO_PATH/api/http.proto \
--plugin=protoc-gen-grpc=~/Downloads/grpc-protoc_macos_x64-1.26.0-dev/grpc_csharp_plugin
```

**Comment by Jhovanni** [comment]
>     * grpc_csharp_plugin

I ran into same issue. grpc_unity_package.2.26.0-dev.zip resolve the error messages as mentioned.
I have a couple of questions, repo documentation does not say how to actually generate proto files. C# main repo does mention it but it mentions to use dotnot package manager, something not fully available in unity.
If you are able to provide support for this:
How do you compile proto files? How did you installed grpc_csharp_plugin?

**Comment by doctorpangloss** [comment]
> workaround here
> 
> ```
> @rem System.Memory 4.0.1.0 -> 4.0.1.1
> @rem warn: this remove sign from Google.Protobuf.DLL
> @rem .netfx 4.6.1 tools tested
> "ildasm" /UNICODE /all /text Google.Protobuf.dll /out=Google.Protobuf.il
> powershell -Command "(gc Google.Protobuf.il) -replace '.ver 4:0:1:0', '.ver 4:0:1:1' | Out-File -encoding UNICODE Google.Protobuf-mod.il"
> @rem need admin permission or Could not create output file, error code=0x80070005
> "ilasm.exe" /DLL "%CD%\Google.Protobuf-mod.il" "/output:Google.Protobuf.dll" "/resource=Google.Protobuf.res"
> del /q Google.Protobuf*.il
> del /q Google.Protobuf.res
> ```

It's close, but the command doesn't output a `res` file.

**Comment by jtattermusch** [comment]
Protobuf has been upgraded to the same version of System.Memory as Grpc here: protocolbuffers/protobuf#7940. So once a new version of Google.Protobuf is released, things will work without requiring any workarounds.

**Comment by isbdnt** [comment]
> > This seems to happen after grpc_unity_package.2.26.0-dev, so grpc_unity_package.2.26.0-dev and prior do not elicit the same error message
> 
> Using 2.26-0-dev causes another error when I import generated csharp files:
> 
> `error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments`
> 
> Environment and tools used:
> Unity 2019.2.13f1
> protoc 3.12.4
> grpc_csharp_plugin (from grpc.tools 2.31.0)
> 
> What is the consensus on a solve for these related issues?

I encountered the same error, it turned out that I was using new version of protoc.exe, try to execute "protoc.exe --version" to know if you are using correct one, it should be 3.8.0

**Comment by virtumonde** [comment]
I still get the same error. Can someone confirm?

**Comment by QuinnBast** [comment]
Just commenting here to say the same thing. I get the same errors as everyone else here. Downgrading to the [2.26.0](https://packages.grpc.io/archive/2019/11/6950e15882f28e43685e948a7e5227bfcef398cd-6d642d6c-a6fc-4897-a612-62b0a3c9026b/index.xml) version works

**Comment by rdcm** [comment]
+1
