### ISSUE TITLE
LocalCredentials do not Recognize "localhost" as local on Windows

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#22257]
@yihuazhang 

I verified this under local testing. It might be that this isn't feasible or even the right behavior on Windows, but it was certainly surprising to me.

Let me know if you need any additional information.

**Comment by yihuazhang** [comment]
Thanks for filing the bug @gnossen. I will look into it.

**Comment by gnossen** [comment]
@yihuazhang Let me know if you need help getting a local set up for reproduction. That was by far the hardest part for me.

**Comment by gnossen** [comment]
@yihuazhang Have you gotten a chance to take a look at this? I just got bitten by it again.

**Comment by yihuazhang** [comment]
Sorry for dropping the ball. I found a similar issue https://github.com/grpc/grpc/issues/20855 reported some time ago (also assigned to me). Did you observe the same issue (i.e., `win_get_fd()` returns -1)?

**Comment by gnossen** [comment]
I'm afraid I didn't dig into the problem to the same depth as that user apparently did. His black box description seems the same though, so I'm reasonably confident that if his concerns are addressed, mine will be too.

**Comment by yihuazhang** [comment]
SG. Let's then first fix the problem in https://github.com/grpc/grpc/issues/20855 as without it being fixed C core local credentials is broken on Windows.

**Comment by yihuazhang** [comment]
Move the discussion to https://github.com/grpc/grpc/pull/20857

**Comment by erm-g** [comment]
@gnossen it looks like the root cause was solved [here](https://github.com/grpc/grpc/issues/20855#issuecomment-1332584168) - does it sill reproducable in your setup?

**Comment by gnossen** [comment]
I'm not likely to get my setup back up after this long and considering it's not a high priority on my end, I'll treat [this comment ](https://github.com/grpc/grpc/issues/20855#issuecomment-1332584168) as resolution. Thanks!
