### ISSUE TITLE
Support ARM64 in C# grpc.tools package

### ISSUE THREAD

**Issue by aidapsibr** [grpc/grpc#22263]
### Is your feature request related to a problem? Please describe.
It appears not to be possible to compile proto files using msbuild and the dotnet SDK even with protoc on the path and PROTOBUF_PROTOC set. 

It appears the grpc.tools nuget package doesn't support ARM64 as there is not a linux_arm64 folder in the tools directory for loading the plugin

### Describe the solution you'd like
Include a linux_arm64 tools folder and compiled plugin, update .targets to add arm64 as a platform.

### Describe alternatives you've considered
None

### Additional context
OS: Debian 10
Device: Microsoft Surface Pro X

**Comment by nicolasnoble** [comment]
Sorry, our stance on the state of precompiled tools that we provide is that we're only going to support Intel for these binaries. Meaning that if you want to develop, either you need to select an Intel platform to work with, or you need to build your own versions of the tools on your non-Intel platform.

Note that this is different from what we support for production packages.

**Comment by turowicz** [comment]
@nicolasnoble I haven't heard such nonsense in years! Let me make a screenshot of your response.

**Comment by aidapsibr** [comment]
@nicolasnoble Now that Apple is moving to arm64 and 2 fairly large projects are blocked on this. Is it possible to re-open this issue and re-evaluate this stance?

**Comment by dystopiandev** [comment]
Bump.

Any news on this?

**Comment by nicolasnoble** [comment]
Our stance on native ARM64 (which, if we were to publish binaries for, would be targeting Linux) hasn't changed much, although ARM machines might be added in the future.

M1 is a completely different problematic however, and would require a different solution. It's not appropriate to conflate ARM64 (Linux) and M1 (MacOS).

**Comment by jtattermusch** [comment]
> Bump.
> 
> Any news on this?

Grpc.Tools has had ARM64 codegen support on **Linux** for a while now. See https://grpc.io/blog/grpc-on-arm64/

We don't have plans for Apple M1 yet, but this issue is about ARM64 on linux, not on mac - so debates about ARM64 on Mac don't belong here.
