### ISSUE TITLE
Grpc.Core NuGet Package Native DLL's are not versioned

### ISSUE THREAD

**Issue by fscan** [grpc/grpc#22284]
### What version of gRPC and what language are you using?
C# - Grpc.Core 2.27.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019

Hi,

we would like to use gRPC for IPC in our product. Everything is working nicely but we cannot deploy the runtime because our deployment system needs all dll's to be versioned, which imho is  reasonable requirement.
These files from the NuGet package are missing version information:
grpc_csharp_ext.x86.dll
grpc_csharp_ext.x64.dll

**Comment by jtattermusch** [comment]
@fscan  just FYI, grpc_csharp_ext.x86.dll and grpc_csharp_ext.x64.dll are not C# assemblies, they are native .dlls. Does your deployment policy cover those as well?

**Comment by fscan** [comment]
@jtattermusch yes, i'm aware of this. Our system needs all .dll and .exe files to be versioned. They are used to ensure consistency when upgrading (or downgrading) deployments. Its also necessary for keeping a history of deployed versions.

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
