### ISSUE TITLE
grpc.github.io still hosts the full old site

### ISSUE THREAD

**Issue by chalin** [grpc/grpc#22294]
The official gRPC website is https://grpc.io. AFAIK, the website used to be on GitHub Pages at https://grpc.github.io, via the gh-pages branch: https://github.com/grpc/grpc/tree/gh-pages.

My understanding is that this repo's GH Pages branch is used to host **API reference** pages, somehow generated from this repo.

The problem is that grpc.github.io **still hosts the full old site content**. It shouldn't, otherwise we run the risk of confusing folks, especially those who still have links to the old site.

The only content that should be accessible from grpc.github.io, should be the API reference pages. Any other site URL should either redirect to grpc.io automatically, and/or show a page with a notice along the lines of "This page has moved to grpc.io".

cc @thisisnotapril @nicolasnoble @lucperkins @jtattermusch @dwiner @srini100 @lowasser @bshaffer

**Comment by jtattermusch** [comment]
Thanks for noticing this. Yes, we should fix this. 
Btw, while not ideal, the old page design is unfortunately better than the new one from usability and UX perspective.

**Comment by chalin** [comment]
@jtattermusch, if you'd like I can work on this. Let me know.

> while not ideal, the old page design is unfortunately better than the new one from usability and UX perspective.

I agree. This surprised me when I found the old site.
Why was the old site design abandoned?

Some nice improvements (by @lucperkins) to the new site repo have just landed, actually recovering some of the old site's design and navigation elements.

**Comment by chalin** [comment]
@jtattermusch One solution would be to add a banner, informing folks of, and offering a link to the new site.(My offer still stands to take care of this. The sooner it is done the better IMHO.)

**Comment by jtattermusch** [comment]
Can we just make the old page redirect to the new one? I don't see why we would need both pages and a banner.

**Comment by chalin** [comment]
Actually, I was wrong about the location of the files. https://github.com/grpc/grpc/tree/gh-pages only hosts the API reference docs. I believe that the main site content still comes from https://github.com/grpc/grpc.github.io. I'm not sure how this will need to be handled. Maybe someone needs to temporarily un-archive the grpc.github.io repo first before I can make any changes. @jtattermusch @nicolasnoble do either of you have the permissions to do so?

**Comment by chalin** [comment]
@srini100 - to you have admin access to https://github.com/grpc/grpc.github.io? It needs to be temporarily unarchived. cc @thisisnotapril

**Comment by srini100** [comment]
@chalin, just unarchived. Let me know when you are done.

**Comment by chalin** [comment]
See https://github.com/grpc/grpc.github.io/pull/858, which adds an "obsolete!" banner to every page.

Why I opted for a banner:

- **GitHub pages doesn't support redirect patterns**, which is what we'd need because we're rendering the old doc site content obsolete, but not the API pages.
  - We could just drop all doc pages, and add a warning to the old homepage, but then folks with old doc page links would simply get a 404, which doesn't offer an acceptable UX.
- The banner on each page **offers the reader a link to the corresponding page on the new site** (using the same page URL).

**Comment by chalin** [comment]
From https://github.com/grpc/grpc.github.io/pull/858#issuecomment-603513596, you'll note that I went ahead and merged the PR since, IMHO, it is better to have a banner than to leave readers uninformed about the obsolete status of the doc pages. If this solution isn't seen as acceptable, then I can submit followup PRs. Feel free to open issues over grpc.github.io. Thanks!

**Comment by thisisnotapril** [comment]
lgtm!

**Comment by chalin** [comment]
Thanks for confirming April!

**Comment by chalin** [comment]
> @chalin, just unarchived. Let me know when you are done.

@srini100 - FYI, I've just (re-)archived the site now that we have the banners up and that April has LGTM'd.
