### ISSUE TITLE
CMakeList.txt pollutes upper project

### ISSUE THREAD

**Issue by thothothotho** [grpc/grpc#22303]
### What version of gRPC and what language are you using?

gRPC v1.28.0-pre3 c++ with cmake.

### What operating system (Linux, Windows,...) and version?

Linux Ubuntu 18

### What runtime / compiler are you using (e.g. python version or version of gcc)

cmake 3.13.4 gcc-8 (or clang-9)

### What did you do?

add gRPC as a sub cmake of my cmake project.

```
add_subdirectory(ThirdParty/grpc)
```

### What did you expect to see?

I did expect no observable change with respect to my project that is still not using anything from grpc.

### What did you see instead?

Those two flags  (and only those)
```
-I../foo/ThirdParty/grpc/third_party/zlib
-Ifoo/ThirdParty/grpc/third_party/zlib
```

are injected on all the compiler invocations.

Now, if I do this

```
add_subdirectory(ThirdParty/grpc)
target_link_libraries(foo PRIVATE grpc++)
```

then, those are the flags injected:

```
-I../foo/ThirdParty/grpc/third_party/zlib
-Ifoo/ThirdParty/grpc/third_party/zlib
-I../foo/nqrpc/include
-I../foo/nqrpc/source
-I../foo/ThirdParty/grpc/include
-I../foo/ThirdParty/grpc/third_party/protobuf/src
-Ifoo/ThirdParty/grpc/third_party/cares/cares
-I../foo/ThirdParty/grpc/third_party/cares/cares
-I../foo/ThirdParty/grpc/third_party/abseil-cpp
```

This is mostly correct.  It is questionable whether business code needs `cares` or `abseil` (or even zlib).  If those library are not referenced by grpc's include files, then maybe those `-I` should not leak into the business project.

madler/zlib looks dead.  Their cmake is broken (you already have a workaround in your own cmake).  You might consider switching to https://github.com/zlib-ng/zlib-ng

**Comment by thothothotho** [comment]
This bug is very annoying.  This is especially bad it happens with `zlib`.  With another library, it would have been unnoticed. We want to use grpc as part of a much bigger project with many `CMakeList`, where zlib is also used by several others sub components, most of them shipping their own copy of zlib (with symbols properly mangled to avoid link issues).  You can imagine that this _header search path_ contamination  breaks everything.
Absolutely all the  targets of the root CMakeList get contaminated. 

I don't even know how zlib's cmake can achieve that.  Cmake's scoping rules are designed to prevent contamination  from a lower CMakeList to its parent.  Any setting you do in a CMakeList is only visible to children by default.

**Comment by jtattermusch** [comment]
Unfortunately this is an inherent problem when including cmake projects with add_subdirectory (which is generally simpler, but has a risk of polluting your cmake environment by third_party CMakeLists.txt).  

Solution 1:
The canonical way of depending on gRPC is to first pre-install gRPC and all its dependencies under a prefix and then importing gRPC using `find_package()` That way, your CMakeLists.txt will stay completely clean and you will also be able to de-duplicate dependencies such as zlib (in case more of your dependencies need zlib)
https://github.com/grpc/grpc/tree/master/src/cpp#find_package 

Solution 2:
Btw, if you have zlib already installed on your system (e.g. you're on linux and it look like you are), you can just set `cmake -DGRPC_ZLIB_PROVIDER=package` when configuring gRPC and zlib's CMakeLists.txt won't get imported into your project at all.
https://github.com/grpc/grpc/blob/f7591a3426becbed20dbd1a80beb9c1e2ca1a738/cmake/zlib.cmake#L45

That said, we acknowledge that madler/zlib has its problems and we might look into using zlib-ng in the future, but we have no imminent plans to look into that (other priorities). The solutions I mentioned about should be enough to solve your problems.
