### ISSUE TITLE
User CMAKE_MODULE_PATH is overridden 

### ISSUE THREAD

**Issue by johnor** [grpc/grpc#22300]
### What version of gRPC and what language are you using?
v1.27.3, C++

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019, version 16.3.9

### What did you do?
I am trying to build grpc using CMake with a custom FindZLIB.cmake. The path to this file is added to CMAKE_MODULE_PATH. 

### What did you expect to see?
No errors and grpc picks up my version of FindZLIB.cmake

### What did you see instead?
Grpc picks up the version included in cmake which will not find zlib on my system, and the build fails:

CMake Error at C:/Python37/Lib/site-packages/cmake/data/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.3")
Call Stack (most recent call first):
  C:/Python37/Lib/site-packages/cmake/data/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Python37/Lib/site-packages/cmake/data/share/cmake-3.15/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  build/VS2019/MultiBuildType/_deps/grpc-src/cmake/zlib.cmake:46 (find_package)
  build/VS2019/MultiBuildType/_deps/grpc-src/CMakeLists.txt:155 (include)

### Anything else we should know about your project / environment?
It looks like grpc is overwriting CMAKE_MODULE_PATH instead of appending to it here: https://github.com/grpc/grpc/blob/67ca5501470349323226a3dceeea2311c83e0ae4/CMakeLists.txt#L164

Would you accept a PR that appends "${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules" to CMAKE_MODULE_PATH instead?

**Comment by jtattermusch** [comment]
CC @zackgalbreath @KyleFromKitware looks like this problem was introduced by 
 https://github.com/grpc/grpc/pull/20815/files

**Comment by KyleFromKitware** [comment]
I'll submit a patch.
