### ISSUE TITLE
Getting error when trying to use ClientAsyncReaderWriter for async notification

### ISSUE THREAD

**Issue by saintnoah** [grpc/grpc#22316]
Hi, I am learning grpc and trying to use grpc to do notification. My use case is client want to subscribe to change on server, when there is change happens on server, server will notify the client. I am using [gnmi protocol](https://github.com/openconfig/gnmi/blob/master/proto/gnmi/gnmi.proto) for async subscribe rpc which called AsyncSubscribe.
In gnmi proto, it defines the subscribe rpc as

    rpc Subscribe(stream SubscribeRequest) returns (stream SubscribeResponse);

When I test my code I got the error code as below. The error happened after client send a request to server and when completion queue receive a response from server and try to read the response
I turned on the GRPC_TRACE=api and GRPC_VERBOSITY=debug:

	I0312 06:56:14.290450200  37 call.cc:1967]   grpc_call_start_batch(call=0x5649c1591020, ops=0x7f40d1b50a10, nops=2, tag=0x5649c1592000, reserved=(nil))
	I0312 06:56:14.290466500  37 call.cc:1565]   ops[0]: RECV_INITIAL_METADATA ptr=0x5649c1576a58
	I0312 06:56:14.290516500  37 call.cc:1565]   ops[1]: RECV_MESSAGE ptr=0x5649c1592028
	E0312 06:56:14.290535100  37 call_op_set.h:947]  assertion failed: false

I followed the grpc async example code(difference is I am using ClientAsyncReaderWriter) and my client code is as follows.

	void AsyncSubscribe( Message* objMsg)
	{
		SubscribeRequest subReq = GenerateSubReq(objMsg);
		AsyncSubTag* subTag = new AsyncSubTag();
	        subTag->reader_writer = stub->PrepareAsyncSubscribe( &(subTag->context), &mSubCq );
		subTag->reader_writer->StartCall((void*)subTag);
	        subTag->reader_writer->Write( subReq, (void*)subTag );
	}

    // this method runs in a worker thread to moniter the completion queue Next
    void AsyncSubCompleteRpc()
    {
        void* got_tag;
        bool ok = false;
	    SubscribeResponse reply;
        while (mSubCq.Next(&got_tag, &ok)) {
        	AsyncSubTag* tag = static_cast<AsyncSubTag*>(got_tag);
		tag->reader_writer->Read(&reply, got_tag);
		cout << "AsyncSubCompleteRpc read sub reply: \n" << reply.DebugString() << endl;
        }
    }
	
	class AsyncSubTag
	{
	public:
		virtual ~AsyncSubTag() {}
		ClientContext context;
		std::unique_ptr<ClientAsyncReaderWriter<SubscribeRequest, SubscribeResponse>> reader_writer;
	};	

	mSubThread = std::thread(&Client::AsyncSubCompleteRpc, this);
	CompletionQueue mSubCq;
	
I read the comment in async_stream_impl.h but still cannot figure out why I got this error. I just sent one subreq to server and use a thread to check completion queue Next(), and read the response until next result is available. 

In call_op_set.h, for the assert, comment says

      // A failure here indicates an API misuse; for example, doing a Write
      // while another Write is already pending on the same RPC or invoking
      // WritesDone multiple times
But I could not figure out why my code leads to "another Write is already pending on the same RPC".
Could you please help to see is there anything wrong with my code?

Thanks a lot for your help!

**Comment by saintnoah** [comment]
Hi, if completion queue Next() method did not receive any event when server send notification. And with "export GRPC_TRACE=api,call_error, export GRPC_VERBOSITY=debug" all turned on, still no log showing at all. 
Is there any other way to check any event available in the queue?

**Comment by mitjans** [comment]
Hi! May I ask how did you solve this problem? I'm facing the same error doing something similar in the client side.

**Comment by saintnoah** [comment]
> Hi! May I ask how did you solve this problem? I'm facing the same error doing something similar in the client side.

Basically the solution is don't send the subscribe request(Write) when you issue asyncsubscribe, just do StartCall.
In the listening event thread, send out the subreq. You might need a simple state machine to tell which state you are in(done with StartCall, done with sending subreq, etc).
Good luck!

**Comment by testerarm** [comment]
```
class TaskClient {
  public:
    explicit TaskClient(std::shared_ptr<Channel> channel): stub_(RpcImage::NewStub(channel)) {}

    // Assembles the client's payload and sends it to the server.
    void SendImage(std::string filename) {
       AsyncClientCall* call = new AsyncClientCall;
        call->response_reader = stub_->AsyncSendImage(&call->context, &cq_ , (void*) call );

         std::cout << " here 4" <<std::endl;
        // StartCall initiates the RPC call
        // call->response_reader->StartCall((void*)call);
        std::cout << " here 5" <<std::endl;
        

        ImageRequest irq;
        irq.set_filename(filename);
        // Call object to store rpc data
        //call->response_reader->
       
        std::cout << " here 1 " <<std::endl;

        try
        {
          /* code */
           grpc::WriteOptions writeOptions;
           (call->response_reader)->Write(irq, writeOptions , (void*) call); // E1207 17:35:49.704812226    1537 call_op_set.h:973]          assertion failed: false
            //std::sleep(std::chrono::seconds(1));
             std::cout << " here 1 222" <<std::endl;
           call->response_reader->WritesDone( (void*) call);
        }
        catch(const std::exception& e)
        {
          std::cerr << e.what() << '\n';
        }
        
   

    }

    // Loop while listening for completed responses.
    // Prints out the response from the server.
    ImageResponse AsyncCompleteRpc() {
        void* got_tag;
        bool ok = false;

        // Block until the next result is available in the completion queue "cq".
        //int check = 0;
        while(cq_.Next(&got_tag, &ok)) {
            // The tag in this example is the memory location of the call object
            //std::cout << " Complete Rpc Call: " <<  check << std::endl;
             
            AsyncClientCall* call = static_cast<AsyncClientCall*>(got_tag);

            // Verify that the request was completed successfully. Note that "ok"
            // corresponds solely to the request for updates introduced by Finish().
            GPR_ASSERT(ok);
			
            if (call->status.ok()) {
                //std::cout << "RPC reply: " << call->reply.price() << std::endl;
                 //check++;
                
                ImageResponse ir1;
                call->response_reader->Read( &ir1 , (void*)call);
                std::cout << " Received message:  " << ir1.id() << std::endl;



                // std::cout << "Greeter received: " << call->reply.message() << std::endl;
            } else {
                std::cout << "RPC failed" << std::endl;
				std::cout << "Error Message: " << (call->status.error_message()) <<std::endl;
				std::cout << (call->status.error_code()) <<std::endl;

                 //check++;
				// call->reply.set_tasksuccess(0);
                //return call->response_reader->Finish();
            }

            // Once we're complete, deallocate the call object.
            delete call;
        }
           
        //std::cout << " End Async Rpc Call: " <<  check << std::endl;
    }

  private:

    // struct for keeping state and data information
    struct AsyncClientCall {
        // Container for the data we expect from the server.
        ImageResponse repsonse;

        // Context for the client. It could be used to convey extra information to
        // the server and/or tweak certain RPC behaviors.
        ClientContext context;
		

		// with a deadline maybe try exponential backoff 

        // Storage for the status of the RPC upon completion.
        Status status;


        std::unique_ptr<ClientAsyncReaderWriter<ImageRequest, ImageResponse>> response_reader;
    };

    // Out of the passed in Channel comes the stub, stored here, our view of the
    // server's exposed services.
    std::unique_ptr<masterworker::RpcImage::Stub> stub_;

    // The producer-consumer queue we use to communicate asynchronously with the
    // gRPC runtime.
    CompletionQueue cq_;
};
```


So i think I am getting the same error: E1207 17:35:49.704812226    1537 call_op_set.h:973]          assertion failed: false

This is from this line: (call->response_reader)->Write(irq, writeOptions , (void*) call); // E1207 17:35:49.704812226    1537 call_op_set.h:973] assertion failed: false

call-> response_reader is type ClientAsyncReaderWriter, I still don't understand what is wrong.
Any help please?
