### ISSUE TITLE
Consecutive writes in server on a stream blocks incoming tags on other streams when using 1 thread for both polling CQ and processing the tag/event.

### ISSUE THREAD

**Issue by sumsarj** [grpc/grpc#22318]
## What version of gRPC and what language are you using?
1.27.0, C++

## What operating system (Linux, Windows,...) and version?
Debian buster/sid (Minideb) running in container...
## What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 9.2.1
### my use case
I have a server with an async service containing two different bidirectional streaming RPCs (call them stream1 and stream2).
I also have an async bidir streaming client connected to this server.
When the server receives a Read on stream1, it responds with 100000 Writes to the client.
When the client receives a Read on stream1, it saves the response-data into a vector. The client has an alarm triggering a "write_tag" in a loop when the vector of response-data is empty. When it is not empty, it pops first element from the vector (FIFO) and does a Write on stream2.

When the server receives a Read on stream2, it simply responds with a Write.
#### server setup
stream1 and stream2 has their own ServerContexts but share completion queue. I have only one thread which polls the CQ and processes the tag before polling the CQ again... (except for in my second solution to the problem). Each stream instance lives in its own CallData object. The tags are the address of the CallData object in question.
#### client setup
stream1 and stream2 uses separate ClientContexts but share completion queue. It too has only one thread which polls the CQ and processes the tag. Here the tag is an enum which contains all possible operations for both streams, the tags are separated between the streams with READ_STREAM1 and READ_STREAM2 etc..

### my problem
My problem is that the server isnt responding the client on stream2 until it is done Writing on stream1. 

![unfair_completion_queue](https://user-images.githubusercontent.com/8549749/76512092-6c95ab80-6454-11ea-86f7-869dfb94bd6e.png)

### solution 1
If I introduce an Alarm between each write-invocation, it works as it's meant to, but at terrible performance. Same appoach as the GResearch team has in their [article](https://www.gresearch.co.uk/article/lessons-learnt-from-writing-asynchronous-streaming-grpc-services-in-c/). Their code example is [here](https://github.com/G-Research/grpc_async_examples/blob/master/async_streaming_server_queue_to_back.cc#L98).
### solution 2
Another way of solving this, is to have a dedicated thread to get tags from the CQ with CQ->next(), and then store the tags in a queue, from which another thread reads the tags and does the corresponding processing. This too, (due to bad implmementation of busy-waiting) performed really bad.

Is there any ideas as to why the Writes in stream1 is prioritized over the Writes or Reads of stream2? My current solution arent good, so would like to get to the bottom with this.

## What did you expext to see?
That the server serves incoming tags on different streams fairly. (see image)

## What did you see?
If I do consecutive writes on one stream, tags from another stream will not get served until the writes are done or paused/delayed on the former stream. (see image)

# Update:
One solution I have figured out is to have a new thread working on a new separate completion queue of type DEFAULT_POLLING that is not used to serve any client connections. That means that this thread will be fully dedicated grpc's IO work.

Then I can have the other completion queues which actually are serving client requests to be of type NO_POLLING. (not sure if there are any gains in having them as NO_POLLING)

This seems to help out in serving clients fairly.

Is this a stupid idea? Is this scalable?

**Comment by sumsarj** [comment]
From my investigation of the completion_queue, it does FIFO push/pull operations to the queue. So is perhaps the unfairness on a deeper level, say the reading/writing of a socket? Where writing on a socket can get priority over reading from another?

**Comment by sumsarj** [comment]
I may also add that I use NEXT completion_type and the ordinary Next() operation on the completion_queue.

**Comment by veblush** [comment]
Hi, This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at
StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
