### ISSUE TITLE
gRPC on embedded devices - RTOS with posix wrappers

### ISSUE THREAD

**Issue by hale2bopp** [grpc/grpc#22331]
Hello, 

I was wondering if it is feasible to use an embedded board with enough RAM to support gRPC, which is running an RTOS such as FreeRTOS or TI-RTOS, with POSIX wrappers implemented such as 
[http://software-dl.ti.com/simplelink/esd/simplelink_msp432e4_sdk/2.40.00.11/docs/tiposix/Users_Guide.html#building-your-program-with-ti-posix-support]
 
I know gRPC only officially supports Windows or Posix platforms. However, is there a list of Posix APIs that need to be implemented for other RTOSes? Has anyone tried this, and if so how feasible is it to do so?

**Comment by markdroth** [comment]
I don't know why this issue didn't get assigned to the default assignee, but that's why it slipped through our triage process.

Unfortunately, we don't have a list of all POSIX APIs that would need to be supported for gRPC.  However, the code is OSS, so you can look for yourself. :)

Good luck!
