### ISSUE TITLE
cc_grpc_library does not work with --incompatible_generated_protos_in_virtual_imports

### ISSUE THREAD

**Issue by joelwilliamson** [grpc/grpc#22339]
### What version of gRPC and what language are you using?
gRPC 1.26.0 and 1.27.3

### What operating system (Linux, Windows,...) and version?
macOS 10.15.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel 2.2.0, LLVM 8.0

### What did you do?
In the package `//path/to/service`, we have a bazel rule that generates a proto file containing our gRPC definition.
```skylark
create_proto(
    name = "service_proto_def",
    out = "a/b/service.proto"
)
```
We then build a C++ library the normal way
```skylark
proto_library(
    name = "service_proto",
    #N.B. The deps can be on either the file or the rule; doesn't affect this bug.
    deps = ["a/b/service.proto"],
)

cc_proto_library(
    name = "service_cc_proto",
    deps = ["service_proto"],
)

cc_grpc_library(
    name = "service_grpc",
    srcs = ["service_proto"],
    grpc_only = True,
    deps = ["service_cc_proto"],
)
```

### What did you expect to see?
Running `bazel build service_grpc` should succeed

### What did you see instead?
The build failed with the error
```
: undeclared inclusion(s) in rule '//path/to/service:service_grpc':
this rule is missing dependency declarations for the following files included by 'path/to/service/_virtual_imports/service_proto/path/to/service/a/b/service.grpc.pb.cc
   'bazel-out/darwin-opt/bin/path/to/service/_virtual_imports/service_proto/path/to/service/a/b/service.pb.h'
```

### Anything else we should know about your project / environment?
We were running bazel 0.25.3 before and it was building fine with an older version of gRPC.
Flipping the `--incompatible_generated_protos_in_virtual_imports` (https://github.com/bazelbuild/bazel/issues/9215) flag back to false allows the build to run, but I assume it will be removed at some point

**Comment by joelwilliamson** [comment]
@tndhagedorn You might need to follow up on this to make sure the build doesn't break when this flags gets removed.

**Comment by tndhagedorn** [comment]
> @tndhagedorn You might need to follow up on this to make sure the build doesn't break when this flags gets removed.

Thanks @joelwilliamson !

**Comment by tndhagedorn** [comment]
@grpc-google-owners - is there a suggested workaround for this case that doesn't involve using `--incompatible_generated_protos_in_virtual_imports` ?

**Comment by veblush** [comment]
I assume that this issue was address given that gRPC uses Bazel 6.
