### ISSUE TITLE
Compile error on Android Clang-5 due to abseil-cpp

### ISSUE THREAD

**Issue by julianoes** [grpc/grpc#22338]
### What version of gRPC and what language are you using?

`v1.27.2` or `v1.28.0-pre3`

### What operating system (Linux, Windows,...) and version?

Android build using [dockcross](https://github.com/dockcross/dockcross/).

### What runtime / compiler are you using (e.g. python version or version of gcc)

clang-5

### What's the problem?

When building with dockcross for Android, we ran into a build error with abseil-cpp and reported it there: https://github.com/abseil/abseil-cpp/issues/626. It has since been [fixed on master](https://github.com/abseil/abseil-cpp/commit/c6954897f7ece5011f0126db9117361dc1a6ff36) but the this version is not referenced in grpc. Instead it uses the LTS release.

Can we expect the submodule to be updated soon or do you recommend to fork or patch ourselves in the meantime? Thanks.

Build with `v1.28.0-pre3`:
https://github.com/mavlink/MAVSDK/pull/982/checks?check_run_id=505079949#step:4:4060

**Comment by julianoes** [comment]
@dapengzhang0 any update when this might be fixed? Or should I try to patch this myself? Thanks.

**Comment by nicolasnoble** [comment]
@veblush: looks like we need to update our abseil dependency?

**Comment by julianoes** [comment]
@veblush @nicolasnoble any chance abseil could get updated?

**Comment by veblush** [comment]
@julianoes We have to keep using the latest LTS version of abseil to get aligned with other package systems. Since Abseil master branch has the fix, can you ask them to backport it onto the latest LTS branch?

**Comment by julianoes** [comment]
Thanks to a hint by @derekmauro in https://github.com/abseil/abseil-cpp/issues/626#issuecomment-624637832 we could solve this by adding the definition `-DABSL_NO_XRAY_ATTRIBUTES` to the abseil build (see https://github.com/mavlink/MAVSDK/pull/982/commits/32bea3f726856846cba41cacfca267cb31c36848).
