### ISSUE TITLE
gRPC Basics - C++: protoc does not compile 

### ISSUE THREAD

**Issue by tomatac** [grpc/grpc#22353]
### Issue
Issues specific to gRPC Basics - C++  example (https://grpc.io/docs/tutorials/basic/cpp/)

### What version of gRPC and what language are you using?
v1.27.2 / C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### What did you do?
1. make route_guide.grpc.pb.cc route_guide.pb.cc
2. make

### What did you expect to see?
compile proto file

### What did you see instead?
1. program not found or is not executable
2. You don't have the grpc c++ protobuf plugin installed in your path.

### You don't have the grpc c++ protobuf plugin installed in your path.
yes:
protoc --version 
libprotoc 3.0.0

**Comment by karthikravis** [comment]
@tomatac : make is not being actively supported. cmake and bazel are suggested.
