### ISSUE TITLE
is possible to support shared ptr response

### ISSUE THREAD

**Issue by xingjy10** [grpc/grpc#22358]
In my cases, i want to Save my Requests and Responses, but my response takes about 400 ms to serialize to string. I do not want to slow down the online services, So I use a new thread to do the saving things. but the response will be destructed when the main thread returns.
So i wonder if there is a way to operate the response after return status. may be a shared_ptr could do this?

service MyService {
    rpc Serve (Request) returns (Response);
}
can the grpc support shared ptr responses like bellow?
::grpc::Status Serve(grpc::Options &options, Request& request, Response* response);
=>
::grpc::Status Serve(grpc::Options &options, shared_ptr\<Request\> request, shared_ptr\<Response\> response);
or is there any other way to solve my problem?

**Comment by karthikravis** [comment]
Serialization and De-serialization are a part of the RPC and cannot be avoided. The cost is proportional to the complexity of the object being serialized/de-serialized. We're not considering a shared_ptr based API at the moment.

That said 400 msec for serializing an object seems high, I would suggest re-profiling and filing an issue with concrete data and repro steps.
