### ISSUE TITLE
gRPC crash on response streaming (client side: Python) 

### ISSUE THREAD

**Issue by shivanjanip007** [grpc/grpc#22354]
### What version of gRPC and what language are you using?
2.26.0 and Protobuf version: 3.11.3 and Server language: c#, client side : Python

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Runtime and version of pthon 3.8.1

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
Streaming response in python should handle the iteration perfectly without errors

### What did you see instead?
Muliutthread issue and status code: UnKNOWN. This is not for first iteration after two iterations i'm able to see this issue/ Please refer below snapshot. Help me out with the solution
![image](https://user-images.githubusercontent.com/61161754/76727818-12118d80-677b-11ea-8e6f-bae656493f86.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by shivanjanip007** [comment]
#gRPC #gRPC-Python #gRPCstraming #gRPCresponse #gRPCclientserver

**Comment by shivanjanip007** [comment]
![image](https://user-images.githubusercontent.com/61161754/76733897-b8639000-6787-11ea-9961-799da1b435ea.png)
Later I tried using "for loop" I'm getting this error 
What I'm trying to do: Display streaming response in python using threads and display the response in treeview using tkinter .

**Comment by shivanjanip007** [comment]
![image](https://user-images.githubusercontent.com/61161754/76734185-60795900-6788-11ea-86b7-fa4a5117120d.png)

Error on c# server side

**Comment by karthikravis** [comment]
@shivanjanip007 : Thanks for the isssue. Do you have steps for reproduction?

**Comment by shivanjanip007** [comment]
![image](https://user-images.githubusercontent.com/61161754/76824025-da1e4f00-683b-11ea-950a-4b230524a8cc.png)
This is the piece of code snippet of Python client. I'm getting error at "for loop" when i'm trying to fetch the streaming response from server.

**Comment by shivanjanip007** [comment]
> ### What version of gRPC and what language are you using?
> 2.26.0 and Protobuf version: 3.11.3 and Server language: c#, client side : Python
> 
> ### What operating system (Linux, Windows,...) and version?
> Windows 10
> 
> ### What runtime / compiler are you using (e.g. python version or version of gcc)
> Runtime and version of pthon 3.8.1
> 
> ### What did you do?
> Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
> 
> ### What did you expect to see?
> Streaming response in python should handle the iteration perfectly without errors
> 
> ### What did you see instead?
> Muliutthread issue and status code: UnKNOWN. This is not for first iteration after two iterations i'm able to see this issue/ Please refer below snapshot. Help me out with the solution
> ![image](https://user-images.githubusercontent.com/61161754/76727818-12118d80-677b-11ea-8e6f-bae656493f86.png)
> 
> Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
> 
> See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
> 
> ### Anything else we should know about your project / environment?

**Comment by karthikravis** [comment]
Hi @gnossen : can you please advise? Thanks!

**Comment by gnossen** [comment]
Based on your error, [the problem is on the C# server side.](https://github.com/grpc/grpc/blob/f2751504c10b87dc2703abd68f2607defc228e89/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L314) It looks like your server handler is throwing an exception, pretty cut and dry. You'll want to check your server logs and maybe catch exceptions and convert them into something more readable.

@jtattermusch In case I'm off base.

**Comment by gnossen** [comment]
Also, @shivanjanip007 , in the future, please prefer text to images when providing snippets. A bit part of the point of these snippets is to reproduce. If all we have are images, we'd have to manually transcribe the whole snippet in order to use it.

**Comment by shivanjanip007** [comment]
Thanks @gnossen but I can see the gRPC error like “Multhithreadrendezvous: status code:Unknown” Could you please elaborate what is it exactly meant ?

**Comment by gnossen** [comment]
Exactly. The link I posted above was [the line of C# code that generates that response](https://github.com/grpc/grpc/blob/f2751504c10b87dc2703abd68f2607defc228e89/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L314).This indicates that an exception was thrown in your server handler, which is written in C#. The Python client is simply displaying this message. When it says "Exception thrown by handler," it presumably means your C# server handler.

You can verify for yourself that that's the only place in the gRPC codebase that this error message comes from:

```
rbellevi@rbell:~/Dev/tmp/grpcs/grpc030$ grep -rn "Exception was thrown by handler" src
src/csharp/Grpc.Core/Internal/ServerCallHandler.cs:314:            return new Status(StatusCode.Unknown, "Exception was thrown by handler.");
```

**Comment by shivanjanip007** [comment]
Thank you so much @gnossen 
I’ll make changes

**Comment by gnossen** [comment]
@jtattermusch Are C# stack traces not propagated in error responses?

**Comment by jtattermusch** [comment]
@gnossen in the general case, the C# stack traces should NOT be propagated in the error response because it's a security risk. Optionally, one can use the status.proto which allows returning the error in a standardized format, but there is no such thing as automatically sending the exception's stacktrace in the "details" string.
