### ISSUE TITLE
Single threaded Ruby server responding with resource exhaustion with just 1 client

### ISSUE THREAD

**Issue by dounan** [grpc/grpc#22389]
### What version of gRPC and what language are you using?
Master branch at commit f2751504c10b87dc2703abd68f2607defc228e89. Ruby

### What operating system (Linux, Windows,...) and version?
Mac 10.14.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
Using the pregenerated ruby files included in the `examples/ruby/lib` directory

### What did you do?
1) Set server to `pool_size: 1`
2) Update client to send 10,000 requests *sequentially* and log any errors it gets back
3) Run the client

Branch here: https://github.com/dounan/grpc/commit/42ae37487370c74ac7d174274a415f5dd3f73542

### What did you expect to see?
All requests succeed

### What did you see instead?
Non-zero number of resource exhausted errors

![image](https://user-images.githubusercontent.com/1095431/76908846-f5528400-6866-11ea-9b44-675aea93d5fb.png)

### Anything else we should know about your project / environment?
Not that I can think of

**Comment by dounan** [comment]
bump for stale bot

**Comment by apolcyn** [comment]
This looks WAI.

The fixed-size thread pool is there for server-side control over resources. And for more context, we changed clients to get "resource exhausted" following the thinking in https://github.com/grpc/grpc/issues/9716.

So if the thread pool size is limited to 1, and there's an active RPC using that thread, then all other incoming RPCs will be rejected.

Is there a reason you can't fix this by sufficiently increasing the thread pool size limit?

**Comment by dounan** [comment]
The confusion for me is why it responds with resource exhausted when the requests are made serially by the same blocking client. I would understand if the test was making parallel requests. See the branch linked in the description for the test case.

**Comment by apolcyn** [comment]
I see - first question then is how many failed with "Resources Exhausted" out of the 10,000 requests?

And, do the first RPC(s) succeed?

The RPC server is not strictly atomic in how it increments/decrements the thread pool's "available thread" count, with respect to the termination of an RPC - in fact in it's current state the server is basically racey on the side of rejecting new RPC's with resource exhausted. 

Do you actually need this specific use case to work?

**Comment by dounan** [comment]
> how many failed with "Resources Exhausted" out of the 10,000 requests?

Not many. I don't remember the total number, but it was just a handful.

> Do you actually need this specific use case to work?

No. We were evaluating gRPC and this behavior was just surprising to us

> The RPC server is not strictly atomic in how it increments/decrements the thread pool's "available thread" count, with respect to the termination of an RPC - in fact in it's current state the server is basically racey on the side of rejecting new RPC's with resource exhausted.

Makes sense. Thanks for clearing that up 😄 I had thought we misunderstood something. Will close the ticket since this is expected.

**Comment by apolcyn** [comment]
Sounds good. FTR if this behavior was really a problem, it could be fixed perhaps by changing each worker thread to poll for RPCs itself, so that each thread polls for one new RPC only after its done processing an RPC. That hasn't been a good reason to pursue that that I'm aware of, though.
