### ISSUE TITLE
Upgrade test credentials to use RSA 2048-bit keys

### ISSUE THREAD

**Issue by jiangtaoli2016** [grpc/grpc#22381]
Current keys are 1024-bit RSA keys and caused test flakey.

The test credentials are located at src/core/tsi/test_creds/

**Comment by jiangtaoli2016** [comment]
@jtattermusch @yihuazhang @ZhenLian

**Comment by jtattermusch** [comment]
https://source.cloud.google.com/results/invocations/94f921a9-f2c7-40a5-9a93-10cdd2958b00/targets/github%2Fgrpc%2Frun_tests%2Fc_linux_dbg_native_x64_gcc8.3/tests

**Comment by jtattermusch** [comment]
the problem might only be in support code: `test_server.py`
https://github.com/grpc/grpc/blob/61a0212539214d2b40d1c2deea0a7c2eb9313b85/test/core/http/test_server.py#L61

**Comment by jiangtaoli2016** [comment]
I will change all test credentials to 2048 in any way. Stay tuned

**Comment by veblush** [comment]
@jiangtaoli2016 Thank you for your effort and can you close this if all necessary changes got merged already?

**Comment by markdroth** [comment]
I suspect this was done.
