### ISSUE TITLE
How to respond by interceptor directly without executing RPC call by C++

### ISSUE THREAD

**Issue by llamalinly** [grpc/grpc#22395]
Hi,

I use gRPC for C++ with 1.20.x branch to build gRPC server. I follow these link to know how to implement interceptor:

[Question: C++ server interceptor](https://github.com/grpc/grpc/issues/9035)
[server_interceptors_end2end_test.cc](https://github.com/grpc/grpc/blob/7bf82de9eda0aa8fecfe5edb33834f1b272be30b/test/cpp/end2end/server_interceptors_end2end_test.cc)

My question is, if my authentication interceptor doesn't allow this request. I want to respond gRPC status code with my detailed reason by interceptor, and this request would not pass to gRPC service. How do I do?

client stub  ---- RPC call----> server auth interceptor ----No pass to----> server RPC service

Thank you for your suggestion.

**Comment by veblush** [comment]
Hi, This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at
StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
