### ISSUE TITLE
Flake: //test/cpp/end2end:xds_end2end_test@poller=epoll1 XdsTest/LocalityMapTest.UpdateMap/XdsResolverWithLoadReporting

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#22408]
C++ Bazel RBE MSAN

https://source.cloud.google.com/results/invocations/3e79de60-1075-43b0-9ae6-95c67c8b2e05/targets

```
test/cpp/end2end/xds_end2end_test.cc:2458
Value of: locality_picked_rates[i]
Expected: (is >= 0.145455) and (is <= 0.218182)
  Actual: 0.221 (of type double)
```

Note that this is on the `v1.28.x` branch. But the xDS files should be up-to-date with master, so this is probably still applicable.

**Comment by markdroth** [comment]
Duplicates #21746.
