### ISSUE TITLE
Basic Tests C# MacOS Timeout (Aborting VM command due to timeout of 3600 seconds)

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#22409]
https://source.cloud.google.com/results/invocations/04b83495-3198-4f75-8e64-fb7c9852c98f/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_csharp/log

**Comment by jtattermusch** [comment]
This seems like a random kokoro issue. Let's reopen if we see the problem again.
