### ISSUE TITLE
Grpc.tools not working

### ISSUE THREAD

**Issue by sachabarber** [grpc/grpc#22417]
So I cloned the repo today, and tried the C# examples HelloWorld. It worked fine. So I then modified the HelloWorld.proto, did a clean and rebuild, and the GpcTools failed to generate any new C# output files, and both the Client/Server projects failed.

This issue is reported here : https://github.com/grpc/grpc/issues/18625

I don't know that was closed I could repeat this straight away on Windows 10

**Comment by jtattermusch** [comment]
I did exactly what you described and I wasn't able to reproduce. (I have VS2019 and Win10)
