### ISSUE TITLE
[FLAKE] test/core/iomgr/tcp_server_posix_test.test/core/iomgr/tcp_server_posix_test

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#22411]
Bazel C/C++ Opt MacOS
```
exited with error code 134
```
https://source.cloud.google.com/results/invocations/2e44eac7-811a-45b2-9550-a7a6019f6926/targets/%2F%2Ftest%2Fcore%2Fiomgr:tcp_server_posix_test/tests

**Comment by donnadionne** [comment]
test has been health as of lately: https://source.cloud.google.com/results/invocations/3c362125-bc72-48ca-bbf4-f48902a6a017/targets;query=tcp
