### ISSUE TITLE
Build error for asp.net core project consuming a gRPC service on macOS

### ISSUE THREAD

**Issue by sayedihashimi** [grpc/grpc#22433]
When building an asp.net core web app that consumes a gRPC service on macOS you will get the build error below

```
/Users/sayedhashimi/.nuget/packages/grpc.tools/2.23.0/build/_protobuf/Google.Protobuf.Tools.targets(140,54): error MSB4113: Specified condition " !%(ProtoCompile) " evaluates to "!" instead of a boolean. [/Users/sayedhashimi/Projects/WebApp02/WebApp02/WebApp02.csproj]
```

This is due to a minor error in the targets file at https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets.

I will send a PR to fix this in a few in.

**Comment by jtattermusch** [comment]
Fixed in #22434. Thanks fore reporting this!
