### ISSUE TITLE
Emulator is opened but not linked to my appcode .

### ISSUE THREAD

**Issue by Badr-essa** [grpc/grpc#22439]
21:56	Emulator: emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: C:\Users\badr\.android\emulator-grpc.cer security will be disabled.

21:56	Emulator: Started GRPC server at 127.0.0.1:8554

**Comment by markdroth** [comment]
There's not enough information here to understand the problem report.  Please use one of the issue templates to ensure that we have enough information.
