### ISSUE TITLE
Client crash when compiled with asan and call unsuccessful

### ISSUE THREAD

**Issue by Thalhammer** [grpc/grpc#22438]
### What version of gRPC and what language are you using?
Grpc v1.27.3
libprotoc 3.11.4
C++14

### What operating system (Linux, Windows,...) and version?
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.1.2 Hera
Release:	5.1.2
Codename:	hera

### What runtime / compiler are you using (e.g. python version or version of gcc)
Gcc version 9.2.1 20191102 (Ubuntu 9.2.1-17ubuntu1~18.04.1) 

### What did you do?
* Build a client project with -fsanitize=address and -lasan
* Let the server return any GRPC Status which is not OK (in my case NOT_FOUND)
* Run the Sync method of the client

### What did you expect to see?
Client should return error and behave identically to one compiled without asan.

### What did you see instead?
Segfault.
Pinned down using GDB to:
```
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:403
#1  0x00007ffff7241bcf in ?? () from /usr/lib/gcc/x86_64-linux-gnu/9/libasan.so
#2  0x00007ffff6d0282d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6d02b9a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00005555555e25b6 in grpc_impl::ClientContext::set_debug_error_string (this=0x616000000690, 
    debug_error_string="{\"created\":\"@1584784189.325544034\",\"description\":\"Error received from peer ipv4:10.0.0.157:44041\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1056,\"grpc_message\":\"Invalid uri\",\"grpc_status\":3}") at /usr/include/grpcpp/impl/codegen/client_context_impl.h:452
#5  0x00005555555e7631 in grpc::internal::CallOpClientRecvStatus::FinishOp (this=0x7fffffffd1f8) at /usr/include/grpcpp/impl/codegen/call_op_set.h:781
#6  0x00005555555faf9b in grpc::internal::CallOpSet<grpc::internal::CallOpClientRecvStatus, grpc::internal::CallNoOp<2>, grpc::internal::CallNoOp<3>, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::FinalizeResult (this=0x7fffffffd1f0, tag=0x7fffffffd0f0, status=0x7fffffffd0e0) at /usr/include/grpcpp/impl/codegen/call_op_set.h:888
#7  0x00005555555e226a in grpc_impl::CompletionQueue::Pluck (this=0x60b000001868, tag=0x7fffffffd1f0) at /usr/include/grpcpp/impl/codegen/completion_queue_impl.h:317
#8  0x00005555555f04cd in grpc_impl::ClientReader<MyResponse>::Finish (this=0x60b000001850) at /usr/include/grpcpp/impl/codegen/sync_stream_impl.h:228
```

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==16440==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7f88fedf8696 bp 0x7ffc9ff7b600 sp 0x7ffc9ff7ad68 T0)
==16440==The signal is caused by a WRITE memory access.
==16440==Hint: address points to the zero page.
```
### Anything else we should know about your project / environment?
GRPC and Protobuf are both build on a jenkins server using
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
and distributed using a deb package to my development PC.
I don't think that causes an issue (it never did for me) but I can't 100% rule it out either.
Note: Building against the same library but not using asan for the application itself works fine.
If I build the parts related to the grpc client without asan and enable it for everything else it also works fine.

**Comment by Enna1** [comment]
Hi, it seems thar I encounter the same issue. Has you solved this @Thalhammer, Thanks!
