### ISSUE TITLE
Server streaming with Callback after each streamed message

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc#22445]
I need to know if it is possible to stream (Server --> client), in which after each streamed message i am able to release the resources before the next message streamed.
So i need something like a callback action that i can use it to release the resources of old streamed message.

Thanks for any Advice or Suggestion.

**Comment by Thalhammer** [comment]
I might understand your issue wrong but if you use an async version you get an tag delivered once the message is sent. If you use a sync server you should be able to clean up the message once Write returns.

**Comment by MhdAna** [comment]
Hi, 
Thanks for your answer, i think you have understood what i need. 
You Said i should use a sync server to clean up the message once Write returns to the Server, it is a new Information for me that there are two different Server implementation **Sync** and **Async** , could you please show me how can i implement such a **Sync Server**

Thanks a lot in advance.

**Comment by Thalhammer** [comment]
@MhdAna 
https://grpc.io/docs/tutorials/async/helloasync-cpp/#async-server
