### ISSUE TITLE
Unity3D: Is it possible to use main thread function in a Service

### ISSUE THREAD

**Issue by Codes-Breaker** [grpc/grpc#22447]
When I defined a service on the Unity side, I wrote the method in Task but i can't use functions from UnityEngine since Unity is not thread-safe. Is there a good way to get around this?

**Comment by donnadionne** [comment]
Please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
