### ISSUE TITLE
[FLAKE] Basic Tests Python MacOS Timeout

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#22458]
https://source.cloud.google.com/results/invocations/08a5bce3-261a-4e73-ad67-540c219025f5/targets

Time limit 3600 seconds is not sufficient to compile gRPC Python for 3 times in a slow Kokoro Mac VM. Since none of the gRPC Python version has special compilation flags, we should be able to compile-once-then-reuse.

**Comment by lidizheng** [comment]
Another occurrence https://source.cloud.google.com/results/invocations/28ef2a95-41a2-4867-881d-9ca00d745ad8/log

**Comment by donnadionne** [comment]
Test has been healthy for 14+ days:
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_basictests_python
