### ISSUE TITLE
when I call a function inside grpc_server, grpc_client gives timeout.

### ISSUE THREAD

**Issue by Martin20** [grpc/grpc#22472]
### What version of gRPC and what language are you using?

I use the grpc inside Cyber RT with C++ programming.

### What operating system (Linux, Windows,...) and version?
ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
I use bazel.

### What did you do?
I sent a message from grpc_client to grpc_server. I want to use the message so that it calls a function for the message. When I call the function, grpc_client gives me a timeout. If I do not call a function, the message passing works perfectly.

### What did you expect to see?
receiving the message.

### What did you see instead?

Error code 4, which is a timeout.

### Anything else we should know about your project/environment?

I use it in apollo 5.0 in cyber RT.

**Comment by markdroth** [comment]
Can you show the code you're using?  It's hard to diagnose this problem without seeing that.

When you get a DEADLINE_EXCEEDED status from an RPC, that means that the call did not complete faster than the call's deadline.  If the server needs more time to respond, you can try increasing the deadline that you set on the call on the client side.

**Comment by Martin20** [comment]
Thank you for your fast reply.

Actually, I want to receive a message via grpc from mochine1 to machine2 and then publish in machine2. When I send it by grpc, I received it without any problem in machine2. However, when I want to publish it in machine2, I receive the timeout in the client. If you look at the server code, there is a line (calling function line which is "os_interface->sendCarStatus(request);") If I remove it, grpc works fine. I need that line to publish "request" in the machine2 (server).

I think the problem is not from the timeout duration since I even increased it to one second (timespec.tv_nsec = 1000000000 )but I still received the error number 4. 
I added the codes. The grpc_server, grpc_client and the used proto file. Please let me know if you need more information.

**### The code for the server is:**
#include "cyber/cyber.h"

//this proto file is mentioned at the end:
#include "modules/v2x/proto/v2x_service_car_to_obu.grpc.pb.h"

grpc::Status GrpcServerImpl::PushCarStatus(
	grpc::ServerContext* /*context*/ ,
	const std::shared_ptr <CarStatus> request,
        UpdateStatus* response){
	ADEBUG << "Received the request from client! \n";
	response->set_updated(true);
//calling function line
        os_interface->sendCarStatus(request);

  return Status::OK;
}
#########################################################################
**### The code for the client is:**

void GrpcClientImpl::SendMsgToGrpc(const std::shared_ptr<CarStatus> &msg) {
  AINFO << "sending message in client";
  // verify CarStatus msg valid
  if (!msg->has_localization() /*  || !msg->has_chassis_detail() */) {
    AERROR << "SendCarStatusToObu msg is not valid";
    AINFO << "Localization is valid to send";
    return;
  }
  // set timeout
  ClientContext context;
  gpr_timespec timespec;
  timespec.tv_sec = 0;
  timespec.tv_nsec = carstatus_tv_nsec_;  // 80000000; // 80ms
  timespec.clock_type = GPR_TIMESPAN;
  context.set_deadline(timespec);

  // StatusResponse response;
  UpdateStatus response;



  // time used statistics
  auto start = std::chrono::steady_clock::now();
  Status status = stub_->PushCarStatus(&context, *msg, &response);
    AINFO << "lakerdar after calling in client";
  auto end = std::chrono::steady_clock::now();
  std::chrono::duration<double> time_used = end - start;

  // response check: error_code 4: time out; 0: success;
  if (status.error_code() != 0) {
    AERROR << "stub PushCarStatus error : code " << status.error_code();
    AINFO << "lakerdar stub PushCarStatus error : code " << status.error_code();
  } else {
    ADEBUG << "stub PushCarStatus success. time used: "
    << time_used.count() * 1000 << "ms"
    << "error : code " << status.error_code();
    AINFO << "stub PushCarStatus success. time used: "
    << time_used.count() * 1000 << "ms"
    << "error : code " << status.error_code() ;
  }
}
##############################################################
This is the related proto file that is included in the server file:
//this proto file is mentioned at the end:
//#include "modules/v2x/proto/v2x_service_car_to_obu.grpc.pb.h"
###########################################################


syntax = "proto2";

package apollo.v2x;

import "modules/perception/proto/perception_obstacle.proto";
import "modules/v2x/proto/v2x_carstatus.proto";

service CarToObu {
  rpc PushCarStatus (apollo.v2x.CarStatus) returns (UpdateStatus) {}
}

message UpdateStatus {
  required bool updated = 1 [default = false];

}

**Comment by markdroth** [comment]
What does `os_interface->sendCarStatus()` actually do?  How long does it take to run?  I suggest that you try logging the time both before and after that call to see how long it takes.

You can also try increasing the deadline to something much longer than 1 second to see if that helps.

**Comment by Martin20** [comment]
When I call it inside the server-side, the server function is never called. Therefore, there is a timed out on the client-side.

**Comment by markdroth** [comment]
I don't see how the presence of the server function can cause a timeout if the server function is never getting called.

I suspect that there's some bug either in your application or in your debugging.  But without seeing detailed logs showing the time before and after the server function, I don't think there's anything we can do to help.

Good luck!

**Comment by vjpai** [comment]
Use std::chrono for setting deadlines on the ClientContext, not gpr_timespec . The latter may build for reasons, but isn't actually part of the c++ api and shouldn't be used by user code.
