### ISSUE TITLE
Provide surface access to credentials error messages

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#2247]
If e.g. `grpc_google_default_credentials_create` returns a null pointer, there's no way at the surface API (beyond hackily watching stderr/stdout) to know which precondition wasn't met.

**Comment by jayantkolhe** [comment]
Tackle post beta

**Comment by ctiller** [comment]
Please provide more context.

**Comment by soltanmm** [comment]
If a user calls that function and receives a null pointer, the user has little idea why the call failed unless staring at the stderr output (unless this has changed recently). There was a scenario some time ago (I think it was over gchat and thus lost to the aether) wherein someone was having trouble figuring out why they couldn't get their default credentials to work, and Python couldn't report back the failed precondition via code (I think it was an environment variable that wasn't set or some such?). Rather, the failure was printed to stderr.

**Comment by ctiller** [comment]
Would flagging this in the request status help?

**Comment by soltanmm** [comment]
@ctiller I'm not sure what you mean by request status in this context. :-/
