### ISSUE TITLE
Bug: race condition between threads updating handshakers

### ISSUE THREAD

**Issue by hunterlxt** [grpc/grpc#22489]
### What version of gRPC and what language are you using?
core: v1.26.0
language: Rust

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
grpc-rs has supported `bind_with_fetcher`, so we can use `grpc_ssl_server_credentials_create_options_using_config_fetcher` to reloading certs without shutdown server. [Related PR](https://github.com/tikv/grpc-rs/commit/9a6411b83172092a35eea045801f6a8299f8afa7)

But we found that this is not a thread-safe behavior. Multi threads could update `server_handshaker_factory_` in grpc-core, and they want to unref the previous `server_handshaker_factory_`. But when 2 more threads come in and try to unref it, something terrible happened.
```c++
    if (server_handshaker_factory_) {
      tsi_ssl_server_handshaker_factory_unref(server_handshaker_factory_);
    }
```

This is the [PR](https://github.com/tikv/tikv/pull/7251) in TiKV I tried to fix this issue, but I can't lock the update in fetcher itself. Because the fetcher is called when adding handshakers and that's not locked by mutex.

### What did you expect to see?
Use mutex lock the `tsi_ssl_server_handshaker_factory_unref` behavior.

### What did you see instead?
Coredump

**Comment by hunterlxt** [comment]
ping, any progress? @markdroth @yihuazhang

**Comment by yihuazhang** [comment]
@hunterlxt, Sorry for the late response. I will take a look by the end of this week.

**Comment by hunterlxt** [comment]
Thanks, and I have tested grpc-python (as the only language exporting the feature) doesnt encounter this problem because it bind only one completion queue and looks like it doesnt support adjust number like grpc-c++ or grpc-rs.

**Comment by yihuazhang** [comment]
I agree that it's indeed a problem. As you mentioned, we need to use a lock in server's security connector to synchronize the updates to `server_handshaker_factory_ `. We already applied the similar mechanism in [TLS](https://github.com/grpc/grpc/blob/c97492faf01b3d2d19c39fc7f81edc3a90d74ef8/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L580). I will prepare for a PR to fix it.

**Comment by yihuazhang** [comment]
Mailed out https://github.com/grpc/grpc/pull/22647 for a review
