### ISSUE TITLE
C++ compression example doesn't use compression

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#22494]
I recorded the compression example with wireshark. I had the C++ compression_client communicate with the C++ compression_server. I see `grpc-encoding` in the request and response headers. However the request and response message is uncompressed.

Changing the name from `"world"` to `"world"` repeated 1600 times (I wanted 8k in my test...) changes the behavior where it starts compressing in both directions (and it compresses to 53 bytes). We should probably find a better test string.

**Comment by markdroth** [comment]
Which compression example are you looking at?

**Comment by ejona86** [comment]
https://github.com/grpc/grpc/tree/master/examples/cpp/compression . The Bazel target names were examples/cpp:compression_client and :compression_server.
