### ISSUE TITLE
Can't load grpc.core 2.0.0.0

### ISSUE THREAD

**Issue by dirkbaum** [grpc/grpc#22492]
OS:  Windows 10

Language: C# 8.0

Environment:  .Net Core 3.0 Console app calling a method in a .Net Standard 2.0 dll which makes a gRPC call

IDE:  Visual Studio 2019 16.5

Problem:  
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Grpc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad'. The system cannot find the file specified.
  Source=Isam
  StackTrace:
   at DHI.Isam.RIsamCommgRPC.Open(Boolean intentSequential, ValueTuple`2& values) in C:\Projects\Sierra\Isam\Isam\RemoteClient\RIsamCommgRPC.cs:line 96
   at DHI.Isam.RIsam.Open(Boolean intentSequential) in C:\Projects\Sierra\Isam\Isam\RemoteClient\RIsam.cs:line 414
   at CallROpen.Program.Main(String[] args) in C:\Temp\CallROpen\Program.cs:line 13

The dependencies for the dll project look like this:
![image](https://user-images.githubusercontent.com/33075098/77701918-f0838380-6f7c-11ea-93d8-4879744e750f.png)

I find the following file on my file system: "C:\Users\dirkb.DHICORP\.nuget\packages\grpc.core\2.27.0\lib\netstandard2.0\Grpc.Core.dll"

Any help would be greatly appreciated.

**Comment by jtattermusch** [comment]
This is impossible to debug without you providing a minimal project that reproduces the problem (e.g. as a git repository).
There's likely something wrong with your setup, otherwise this kind of problem would have been much more widely reported (because you're basically unable to build).

**Comment by donnadionne** [comment]
Please provide necessary setup to debug and reopen if problem persists.

**Comment by makabakayangyang** [comment]
I meet the same problem when I try to create a rider plugin, have you found the solution?
