### ISSUE TITLE
A strange crash

### ISSUE THREAD

**Issue by SarielTang** [grpc/grpc#22505]
![image](https://user-images.githubusercontent.com/12050371/77820067-86084a00-711a-11ea-9c75-f0e133e63b44.png)
The crash information is shown above.

**Comment by SarielTang** [comment]
We have promotion from 3 to 5 o'clock, so the crashes are concentrated in this period.

**Comment by stanley-cheung** [comment]
@SarielTang Can you share how we can reproduce this issue please? Is there an xcode project you can share?

**Comment by SarielTang** [comment]
Sorry, we also happen occasionally, I don't know how to reproduce.

**Comment by stanley-cheung** [comment]
still an issue

**Comment by yulin-liang** [comment]
Closing since we are not hearing response. We can reopen if necessary.
