### ISSUE TITLE
Ssl Credentials memory leaks

### ISSUE THREAD

**Issue by hdnn** [grpc/grpc#22506]
### What version of gRPC and what language are you using?
1.23

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
msbuild

### What did you do?
```
int main() {
  {
    auto greeter = std::make_shared<rpc::tests::Greeter::Service>();
    grpc::ServerBuilder builder;
    int selected_port = -1;
    try {
      auto ssl_creds = CreateServerSslCredentials(kSslCertPrivateFileName, kSslCertPublicFileName);
      builder.AddListeningPort("0.0.0.0:0", ssl_creds /*grpc::InsecureServerCredentials()*/, &selected_port);
    } catch (const fc::traced_exception_ec&) {
    }
    builder.RegisterService(greeter.get());
    auto server = builder.BuildAndStart();
  }
  google::protobuf::ShutdownProtobufLibrary();
  return 0;
}
```
If I uncomment `grpc::InsecureServerCredentials()` but still call `CreateServerSslCredentials` - Memory Dump output will be almost clear(it still print 48 leaked bytes, but it nothing in comparison with   Ssl Credential leaks. I can make addition screenshot with allocations callstack from Memory Usage Diagnostic Tool of VS).

### What did you expect to see?
No memory leaks

### What did you see instead?

Full Debug gRPC trace:
![1](https://user-images.githubusercontent.com/8512124/77823565-1cce0a00-710d-11ea-96b7-9809ad64bdcb.png)
And sample screenshot with leaked allocation callstack:
![2](https://user-images.githubusercontent.com/8512124/77823622-92d27100-710d-11ea-829b-82259a8c3726.png)
There is a lot of leaks. All of them that I saw have the same callstack.
And of course Output window filled with next output:
```
Detected memory leaks!
Dumping objects ->
{13565} normal block at 0x01533008, 12 bytes long.
 Data: <` S         > 60 FE 53 01 00 00 00 00 00 00 00 00 
{13564} normal block at 0x014D9A88, 64 bytes long.
 Data: < 0S             > 08 30 53 01 00 00 00 00 00 00 00 00 00 00 00 00 
{13563} normal block at 0x014AFEF8, 96 bytes long.
 Data: <  M  !y{p  {    > 88 9A 4D 01 10 21 79 7B 70 8B 80 7B 08 00 00 00 
{13562} normal block at 0x0153FE60, 400 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{13554} normal block at 0x01532C88, 12 bytes long.
 Data: <h-S         > 68 2D 53 01 00 00 00 00 06 00 00 00 
{13553} normal block at 0x0153A1D0, 16 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{13552} normal block at 0x01539D90, 20 bytes long.
 Data: <      S         > 00 00 00 00 D0 A1 53 01 00 00 00 00 04 00 00 00 
{13551} normal block at 0x01532D68, 12 bytes long.
 Data: <      S     > 06 00 00 00 90 9D 53 01 00 00 00 00 
{13430} normal block at 0x01533040, 12 bytes long.
 Data: <8+S         > 38 2B 53 01 00 00 00 00 0A 00 00 00 
{13429} normal block at 0x01539B90, 16 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```
Full log have 6550 lines in my case.

**Comment by hdnn** [comment]
![1](https://user-images.githubusercontent.com/8512124/77826350-e352ca00-711f-11ea-973d-835d7e1b51c8.png)
![2](https://user-images.githubusercontent.com/8512124/77826352-e483f700-711f-11ea-8b76-98775e4d0b44.png)
![3](https://user-images.githubusercontent.com/8512124/77826353-e483f700-711f-11ea-9d6d-7cada088f74c.png)
![4](https://user-images.githubusercontent.com/8512124/77826354-e51c8d80-711f-11ea-95c0-9926289e7e8b.png)
![5](https://user-images.githubusercontent.com/8512124/77826355-e5b52400-711f-11ea-8d8a-80a7ed9665d2.png)

**Comment by yihuazhang** [comment]
Thanks for reporting the issue. From gRPC debug trace, it is unclear which part of sslcredentials have the claimed memory leaks. Could you please be more specific?

**Comment by hdnn** [comment]
But I also attached allocation callstack and source code... How I can be more specific?

In my example `auto ssl_creds` is `std::shared_ptr<grpc::ServerCredentials>`. If I just create this object(using `grpc::InsecureServerCredentials()`), I won't have that type memory leak. If I use this object in `grpc::ServerBuilder::AddListeningPort` function, I will give described leaks

**Comment by yihuazhang** [comment]
How did you define `CreateServerSslCredentials()`? I could not find it in the gRPC repo. Can you use `SslServerCredentials()` and see if the problem is still around?

**Comment by hdnn** [comment]
CreateServerSslCredentials() is my own function. Sorry, that I skipped it. 
It just loading certificates from files, filling `grpc::SslServerCredentialsOptions` struct and creating `std::shared_ptr<grpc::ServerCredentials>`:
```
[[nodiscard]] static std::string GetGrpcCert(const std::string_view filename) {
  fc::filesystem::path certificate_store_dir;
  if (!fc::config::GetIniValueCertificateStoreDir(certificate_store_dir))
    FC_THROW_EC_ERROR(fc_error::Fail, "Certificate store directory not found.\n");

  certificate_store_dir /= filename;

  std::ifstream file(certificate_store_dir.generic_string(), std::ios::in);

  std::stringstream ss;
  if (file.is_open()) {
    ss << file.rdbuf();
    file.close();
  }

  return ss.str();
}

[[nodiscard]] static std::shared_ptr<grpc::ServerCredentials> CreateServerSslCredentials(std::string_view priv_key_name,
                                                                    std::string_view public_key_name) {
  grpc::SslServerCredentialsOptions ssl_opt;
  ssl_opt.pem_root_certs = GetGrpcCert(kSslCertCAFileName);
  grpc::SslServerCredentialsOptions::PemKeyCertPair key_pair = {GetGrpcCert(priv_key_name), GetGrpcCert(public_key_name)};
  if (ssl_opt.pem_root_certs.empty() || key_pair.private_key.empty() || key_pair.cert_chain.empty())
    throw std::runtime_error( "Can't open gRPC certificates. Communication won't work correctly.\n");
  ssl_opt.pem_key_cert_pairs.push_back(key_pair);
  return grpc::SslServerCredentials(ssl_opt);
}
```

**Comment by hdnn** [comment]
So, after some time I found, that most part of this leaks can be resolved by manual cleaning OpenSSL data:
```
void OpenSSLCleanUp() {
  EVP_cleanup();
  CRYPTO_cleanup_all_ex_data();
  ERR_remove_state(0);
  ERR_free_strings();
}

int main(){
//...
google::protobuf::ShutdownProtobufLibrary();
OpenSSLCleanUp();
return 0;
}
```
And all the rest leaks come with initializations(raw memory allocations) of next variables: `g_plugin_factory_list` (and you had closed merge request about it https://github.com/grpc/grpc/pull/13847 ), `g_default_client_callbacks`, `g_shutting_down_cv` and `g_glip` variables that never freed.

**Comment by yihuazhang** [comment]
I do not think users are expected to manually call OpenSSL cleanup libraries and all other variables are gRPC global variables which I expect to be destroyed in `grpc_shutdown()`. Can you try calling `grpc_shutdown()` at the end of program and see if the memory leak goes away?

**Comment by markdroth** [comment]
Note that `grpc_shutdown()` is not a public API and is not something that users should ever have to invoke directly.  And in fact, we're working to eliminate that API as part of the EventEngine migration.

It's fine to ask a user to try running it to help diagnose a problem, but it's not really a good solution.

**Comment by hdnn** [comment]
Sorry, guys, I changed company and don't work with this library any more

**Comment by gtcooke94** [comment]
Since there's no other reports like this and you aren't dealing with it anymore, let's close this. We can re-open if it is still a problem that needs fixing
