### ISSUE TITLE
Dart client with grpc-dotnet server: some interop test cases are flaky 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#22512]
Affected test cases:
```
cloud_to_cloud:dart:aspnetcore_server:timeout_on_sleeping_server:tls
cloud_to_cloud:dart:aspnetcore_server:cancel_after_begin:tls
```

A few recent failures:
https://source.cloud.google.com/results/invocations/7caa00ca-fcd9-4dcf-82f2-7b0cd4e60293/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_cloud:dart:aspnetcore_server:cancel_after_begin:tls;row=1
https://source.cloud.google.com/results/invocations/7892334e-d125-468a-9b74-c1ecea19669f
https://source.cloud.google.com/results/invocations/313f6357-e840-47a8-86c2-3e9c58c3ebb1
https://source.cloud.google.com/results/invocations/8b003997-a952-431b-9621-c3beb65685bd
https://source.cloud.google.com/results/invocations/e048167f-428f-4ec5-a079-73bcdd3779bc

From the go/grpc-flaky dashboard
![image](https://user-images.githubusercontent.com/9939684/77893943-e14e4f80-7274-11ea-8d09-ce77ebdd9484.png)

The error message is similar to some flakes we've seen the for grpc-dart client in the past, so we can assume that the problem is on the grpc-dart side.
```
Passed.
Unhandled exception:
NoSuchMethodError: The method 'read' was called on null.
Receiver: null
Tried calling: read()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Socket._onData (dart:io-patch/socket_patch.dart:1785:27)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#6      _StreamController._add (dart:async/stream_controller.dart:640:7)
#7      _StreamController.add (dart:async/stream_controller.dart:586:5)
#8      _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
``

**Comment by jtattermusch** [comment]
@mit-mit  @sigurdm can you take a look?

The error message looks similar to https://github.com/grpc/grpc/issues/21755

**Comment by jtattermusch** [comment]
It should be possible to reproduce with `tools/run_tests/run_interop_tests.py -l dart -s aspnetcore --use_docker` (after a few attempts)

**Comment by jtattermusch** [comment]
I'm able to reproduce locally with `DOCKERHUB_ORGANIZATION=grpctesting tools/run_tests/run_interop_tests.py -l dart -s aspnetcore --use_docker` very reliably.

**Comment by sigurdm** [comment]
I tried locally ~10 times without being able to reproduce:
```
DOCKERHUB_ORGANIZATION=grpctesting tools/run_tests/run_interop_tests.py -l dart -s aspnetcore --use_docker
No module named apiclient
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_dart [time=24.2sec, retries=0:0]
PASSED: build_docker_aspnetcore [time=56.6sec, retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_aspnetcore
PASSED: cloud_to_cloud:dart:aspnetcore_server:timeout_on_sleeping_server:tls [time=4.1sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:empty_stream:tls [time=4.1sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:server_streaming:tls [time=4.1sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:cancel_after_begin:tls [time=4.2sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:client_streaming:tls [time=4.2sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:cancel_after_first_response:tls [time=4.2sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:unimplemented_method:tls [time=4.3sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:unimplemented_service:tls [time=4.3sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:empty_unary:tls [time=4.4sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:status_code_and_message:tls [time=4.4sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:large_unary:tls [time=4.4sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:ping_pong:tls [time=4.5sec, retries=0:0]
PASSED: cloud_to_cloud:dart:aspnetcore_server:custom_metadata:tls [time=4.4sec, retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_aspnetcore:22fd58c1-7859-4c68-adf2-bc5b1e9ca948
Removing docker image grpc_interop_dart:858c56c2-fa94-4f8d-a33d-82130d66ed71
Traceback (most recent call last):
  File "tools/run_tests/run_interop_tests.py", line 1693, in <module>
    report_utils.render_junit_xml_report(resultset, _TESTS_XML_REPORT)
  File "/usr/local/google/home/sigurdm/projects/grpc/tools/run_tests/python_utils/report_utils.py", line 59, in render_junit_xml_report
    create_xml_report_file(tree, report_file)
  File "/usr/local/google/home/sigurdm/projects/grpc/tools/run_tests/python_utils/report_utils.py", line 82, in create_xml_report_file
    tree.write(report_file, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 802, in write
    file = open(file_or_filename, "wb")
IOError: [Errno 13] Permission denied: 'interop_test/sponge_log.xml'
```
Not sure what the log-error means, but it looks like the tests pass.
This is with grpc, grpc-dart and grpc dotnet all at todays master

**Comment by jtattermusch** [comment]
@sigurdm  that's odd, because I can reproduce pretty consistently.
Would the trick that fixed similar error on the dart server in https://github.com/grpc/grpc-dart/pull/274/files help fix the client part?

**Comment by sigurdm** [comment]
Hmm - that's hard to say without further debugging.
I'll try to poke a bit more at it today, and look if something like that could be the reason.

**Comment by sigurdm** [comment]
Looking at the corresponding location of the stacktrace in the current sdk (https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/bin/socket_patch.dart#L1981) this should not be able to happen. (We have just checked that _raw is not null.
That check has been in the sdk for 9 moths: https://github.com/dart-lang/sdk/commit/f664a808500c09dcdcc14765a262a8eaf646892a
Fixing https://github.com/dart-lang/sdk/issues/37522.

Probably the tests are running an older sdk.

**Comment by sigurdm** [comment]
I'm OOO next week. So will not be able to get to the bottom of this before that. But updating the dart sdk used for the tests *might* be enough to fix this.

**Comment by jtattermusch** [comment]
I updated the dart SDK in the interop test to 2.7. Let's see if that helps.

**Comment by jtattermusch** [comment]
The last occurrence of this flake is https://source.cloud.google.com/results/invocations/0293e59e-e6fa-4caf-98aa-153048a06b56 (just before this PR got merged). We haven't seen the flake since.
Closing this issue.

@sigurdm  thanks for help!

**Comment by sigurdm** [comment]
Sure - and thanks for yours!
