### ISSUE TITLE
PHP Composer PSR-4 Warnings

### ISSUE THREAD

**Issue by andreladocruz** [grpc/grpc#22514]
Posting here as we cannot open the issue at https://github.com/grpc/grpc-php/issues/new.

Deprecation Notice: Class Grpc\Gcp\AffinityConfig located in ./vendor/google/grpc-gcp/src/generated/Grpc/Gcp/AffinityConfig.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Grpc\Gcp\AffinityConfig_Command located in ./vendor/google/grpc-gcp/src/generated/Grpc/Gcp/AffinityConfig_Command.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Grpc\Gcp\ApiConfig located in ./vendor/google/grpc-gcp/src/generated/Grpc/Gcp/ApiConfig.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.
0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Grpc\Gcp\ChannelPoolConfig located in ./vendor/google/grpc-gcp/src/generated/Grpc/Gcp/ChannelPoolConfig.php does not comply with psr-4 autoloading standard. It will not autoload anymore
 in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Grpc\Gcp\MethodConfig located in ./vendor/google/grpc-gcp/src/generated/Grpc/Gcp/MethodConfig.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Compos
er v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by stanley-cheung** [comment]
I believe this is the same as https://github.com/GoogleCloudPlatform/grpc-gcp-php/issues/35
