### ISSUE TITLE
Need a way to specify source address in GRPC C++ channel creation

### ISSUE THREAD

**Issue by ramarkandasamy** [grpc/grpc#22511]
Hi Team,

    We are using gRPC channel for gobgp communication. From our gobgp client, we are establishing channel to gobgp server.  It is using default global ip for establishing grpc connection. 
We would like to use specific source ip for establishing connection as we have multiple interfaces/ip addresses.

Is there any way to specify source ip address in gRPC channel creation?
Please advise.

Thanks,
Ramar
 
       channel_1 = grpc::CreateCustomChannel(sGoServerIP+ ":50051", grpc::InsecureChannelCredentials(), args);

**Comment by codingninja-95** [comment]
You can explore void SetSocketMutator(grpc_socket_mutator* mutator) API of ChannelArguments class, which is passed as an arg to CreateCustomChannel. you can change the socket interface with setsockopt

**Comment by markdroth** [comment]
I'm not sure how this got filed without a default assignee, but that's why it slipped through our triage process.

The socket mutator approach should work for this.  If you have further questions about this, please ask on the grpc.io mailing list.

**Comment by kulpatel** [comment]
Anyone has any working example here it will help me. @markdroth  markdroth @ramarkandasamy @codingninja-95
