### ISSUE TITLE
Server is stuck in CompletionQueue::Next when multiple server streaming request are sent from client

### ISSUE THREAD

**Issue by CurtisFu** [grpc/grpc#22510]
### What version of gRPC and what language are you using?
https://github.com/grpc/grpc/archive/b54a5b338637f92bfcf4b0bc05e0f57a5fd8fadd.tar.gz
The nearest tag is v1.27.0-pre1 and I'm using C++.

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang8.0

### What did you do?
I have one service(A) and the service has two server streaming RPC(A1 and A2). The main thread in client sends RPC request A1 then RPC request A2. If there is no delay between these 2 RPC requests, the client is able to receive both A1 and A2 responses from server. However, if I add a delay between 2 RPC requests, client only receives the response for the first sent RPC request. Besides the main thread, client has two threads to read the responses. The following class includes the code for the client to send RPC request A1 and the thread function to receive A1 response(I have another class ClientA2 for RPC A2). 
```
class ClientA1 {
public:
  explicit ClientA1(std::shared_ptr<Channel> channel)
      : stub_(helloworld::ServiceA::NewStub(channel)) {}

  void MethodA1() {
    helloworld::MethodA1Request request;
    call_.response_reader =
        stub_->AsyncMethodA1(&call_.context, request, &cq_, (void *)&call_);
  }

  // Loop while listening for completed responses. Run in a thread.
  void AsyncCompleteRpc() {
    void *got_tag;
    bool ok = false;

    // Block until the next result is available in the completion queue "cq".
    while (cq_.Next(&got_tag, &ok)) {
      // The tag in this example is the memory location of the call object
      AsyncClientCall *call = static_cast<AsyncClientCall *>(got_tag);

      if (ok) {
        call->response_reader->Read(&call->response, (void *)call);
      } else {
        call->response_reader->Finish(&call->status, (void *)call);
        break;
      }
    }

    // Deplete the completion queue
    while (cq_.Next(&got_tag, &ok)) {
    }
  }

private:
  // struct for keeping state and data information
  struct AsyncClientCall {
    helloworld::MethodA1Response response;
    ClientContext context;
    Status status;
    std::unique_ptr<ClientAsyncReader<helloworld::MethodA1Response>>
        response_reader;
  };

  std::unique_ptr<helloworld::ServiceA::Stub> stub_;
  CompletionQueue cq_;
  AsyncClientCall call_;
};
```
Main thread in client creates a ClientA1 object and a ClientA2 object, spawns threads to handle responses, and call MethodA1 and MethodA2 to send RPC requests to server. A 5-second delay is added between sending A1 request and A2 request. 
```
      threads.emplace_back(&ClientA1::AsyncCompleteRpc, &client_a1);
      client_a1.MethodA1();
      
      // Add a delay.
      std::this_thread::sleep_for(std::chrono::milliseconds(5000));

      threads.emplace_back(&ClientA2::AsyncCompleteRpc, &client_a2);
      client_a2.MethodA2();
```   
Server has two completion queues and spawns two threads to check the completion queue. The tag pushed to and pop from completion queue is defined as follows: 
```
enum class Rpc { A1, A2};
struct CallData {
  CallData(const Rpc &rpc)
      : rpc_(rpc), response_cnt_(0), status_(CallStatus::CREATE) {}
  Rpc rpc_;
  // How many responses have been sent to the client.
  int response_cnt_;
  // State machine with the following states.
  enum class CallStatus { CREATE, PROCESS, FINISH };
  CallStatus status_; // The current serving state.
};
```
Server run the following initialization to spawns two threads.
```
    // Generate ServerAsyncWriter for A1 response and A2 response, respectively. 
    std::shared_ptr<ServerAsyncWriter<helloworld::MethodA1Response>>
        a1_responder =
            std::make_shared<ServerAsyncWriter<helloworld::MethodA1Response>>(
                &ctx[0]);
    std::shared_ptr<ServerAsyncWriter<helloworld::MethodA2Response>>
        a2_responder =
            std::make_shared<ServerAsyncWriter<helloworld::MethodA2Response>>(
                &ctx[1]);
   
    // Spawn thread to check completion queue - cq[0]
    call_data.emplace_back(std::make_unique<CallData>(Rpc::A1));
    threads_.emplace_back(&ServerImpl::HandleRpc, this, cq_[0].get(),
                              a1_responder, a2_responder);
    helloworld::MethodA1Request request;
    call_data.back()->status_ = CallData::CallStatus::PROCESS;
    // Request RPC
    service_a_.RequestMethodA1(&ctx[0], &request, a1_responder.get(),
                                   cq_[0].get(), cq_[0].get(),
                                   (void *)call_data.back().get());
    
    // Spawn another thread to check completion queue - cq[1] and then request RPC A2(same as above)
``` 
The function run in thread ServerImpl::HandleRpc basically checks the type of the tag then call ServerAsyncWriter::Write() to write responses. For example, if the type of the tag(CallData::rpc_) is Rpc::A1, a1_responder->Write() will be called. 

### What did you expect to see?
I expected client receives both server streaming responses.

### What did you see instead?
Without the delay in client, client receives both server streaming responses. However, with delay, client only receives the first response.

### Anything else we should know about your project / environment?
No.

**Comment by sumsarj** [comment]
is the sever continuously writing to the client over the streams? I have had similar issues with the server serving only one stream but not the other, however I used only one completion_queue. I initially thought that the pop/push of the completion queue was unfair somehow, but didnt find anything suggesting that in the source code. So maybe my issue is the same as yours. 
In my case, I had async bidirectional streaming, where a client write 1 message on stream1 and then read 100K messages on stream1. For each read message on stream1, the client issues a write on stream2 to the same server (this implies a small delay between the inital write on stream1 and first write on stream2, similar to yours when introducing a delay). However the server never served the client over stream2, only stream1. Only once the stream1's 100k messages were done with, it started serving the stream2's requests.

A solution was if I dedicated the completion_queue polling thread (HandleRpc), to only and only read tags. Instead of doing the processing of the tags, it saves the tags to a queue, which another thread (processRPC) pops tags from, processes them and writes the responses. This way, the server managed to serve both streams fairly. However the performance were terrible due to copying and busy_waiting in the processRPC thread.

Another work-around is to not do consequtive writes, but issuing an alarm between each Write. 
So, instead of this:
Write(response, tag=WRITE)
cq->Next(tag);
if tag == WRITE do Write(response, tag = WRITE) // write next message..
Do this:
Write(tag=WRITE)
cq->Next(tag);
if tag == WRITE then alarm.set(.., deadline = now(), tag = WRITE_ALARM); endif;
cq->NExt(tag)
if tag == WRITE_ALARM then Write(tag = WRITE); endif;
cq->Next()....

, alternating between a Write and an Alarm. This will hand over priority to other streams (?) etc... However this, too, performs badly in my case. So none of the solutions are perfect so far. Maybe the first solution can be polished to work better tho...
My issue is here: https://github.com/grpc/grpc/issues/22318
Maybe mine is not related to yours at all. in that case im sorry for my wall of text...

**Comment by CurtisFu** [comment]
Yes, the server continuously writes responses to the client.
In your case, did you call ServerAsyncWriter::Finish() when the stream1's 100k messages were sent?
If so, I think I also observe the same thing. My server has to call Finish() for the first streaming(A1) and after that, client starts to receive responses(A2).

**Comment by sumsarj** [comment]
> Yes, the server continuously writes responses to the client.
> In your case, did you call ServerAsyncWriter::Finish() when the stream1's 100k messages were sent?
Yes I did.
> If so, I think I also observe the same thing. My server has to call Finish() for the first streaming(A1) and after that, client starts to receive responses(A2).
Yeah sounds very much alike

**Comment by sumsarj** [comment]
Hi again, 
Any progress to the problem so far?

I have found one solution which might work for your case as well:

The solution is to have one thread working on a new separate completion queue of type DEFAULT_POLLING that is not used to serve any client connections. That means that this thread will be fully dedicated to grpc's IO work.

Then I can have the other completion queues which actually are serving client requests to be of type NO_POLLING. (not sure if there are any gains in having them as NO_POLLING)

This seems to help out in serving clients fairly.

Is this a stupid idea? Is this scalable?

**Comment by fboranek** [comment]
It looks like I hit the same problem. If connect to 1-2 servers it works when connectiooon more then 3 it start to break.

I made [minimal example](https://github.com/fboranek/grpc-client-cpp) and tested it on Debian Buster withe grpc frpm 1.26.x branch. I didn't test any other version yet.

Workaround for me was 
```
export GRPC_POLL_STRATEGY=epoll1
```
where override default  `epollex` polling engine.

```cpp
        grpc_impl::CompletionQueue cq;
        std::vector<GrpcStatusContextResponse<::Response>> grpcCalls {stubs.size()};
        std::vector<std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::Response>>> rpcs;

        // start requests to all servers
        auto deadline = std::chrono::system_clock::now() + timeout;
        for (size_t i = 0; i < stubs.size(); ++i) {
            grpcCalls[i].index = i + 1;
            grpcCalls[i].context.set_deadline(deadline);

            auto rpc = stubs[i]->Asynctest(&grpcCalls[i].context, request, &cq);
            rpc->Finish(&grpcCalls[i].response, &grpcCalls[i].status, reinterpret_cast<void*>(i));
            rpcs.push_back(std::move(rpc));
        }

        // mark queue as finished
        cq.Shutdown();

        // wait on all responses
        void* got_tag;
        bool ok = false;
        while (cq.Next(&got_tag, &ok)) 
             ;
```

**Comment by jazevedo620** [comment]
Are there any updates on this bug? It breaks my workflow for performing an asynchronous multicast to multiple (more than 2) servers at once. I made a simplified MWE displaying the same problem that was shared by the previous commenter (I don't want to ping): https://github.com/jazevedo620/grpc-async-multicast.

The workaround of using `epoll1` does work for me, though.

**Comment by veblush** [comment]
gRPC recently removed the epollex while making epoll1 a default poller on Linux so I think this indirectly solved this issue. Please feel free to reopen this if required.
