### ISSUE TITLE
Memory leaks in Synchronous server helloworld example 

### ISSUE THREAD

**Issue by tumusudheer** [grpc/grpc#22527]
### What version of gRPC and what language are you using?
grpc version 1.20 and C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### What did you do?
Running `valgrind --leak-check=full --show-leak-kinds=all ./greeter_server`
cpp example hello world [greeter_server](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_server.cc)

### greeter_server.cc?

```
#include <iostream>
#include <memory>
#include <string>
#include <chrono>
#include <grpcpp/grpcpp.h>
#include <thread>
#ifdef BAZEL_BUILD
#include "examples/protos/helloworld.grpc.pb.h"
#else
#include "helloworld.grpc.pb.h"
#endif

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;
using helloworld::HelloRequest;
using helloworld::HelloReply;
using helloworld::Greeter;

int shutdown_flag = 0;
std::unique_ptr<grpc::Server> server;
// Logic and data behind the server's behavior.
class GreeterServiceImpl final : public Greeter::Service {
  Status SayHello(ServerContext* context, const HelloRequest* request,
                  HelloReply* reply) override {
    std::string prefix("Hello ");
    
    reply->set_message(prefix + request->name());
    shutdown_flag = 1;
    return Status::OK;
  }
};

void RunServer() {
  std::string server_address("0.0.0.0:70071");
  GreeterServiceImpl service;

  ServerBuilder builder;
  // Listen on the given address without any authentication mechanism.
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  // Register "service" as the instance through which we'll communicate with
  // clients. In this case it corresponds to an *synchronous* service.
  builder.RegisterService(&service);
  // Finally assemble the server.
  //std::unique_ptr<Server> server(builder.BuildAndStart());
  server = builder.BuildAndStart();
  std::cout << "Server listening on " << server_address << std::endl;

  // Wait for the server to shutdown. Note that some other thread must be
  // responsible for shutting down the server for this call to ever return.
  std::thread shutdowner([server]()
  {
    while(true)
    {
      if(shutdown_flag)
      {
        std::cout << "calling.. shutdown\n";
        server->Shutdown();
        break;
      }
    }
  });
  shutdowner.join();
  std::cout << "called.. shutdown\n";

  // Wait for the server to shutdown. Note that some other thread must be
  // responsible for shutting down the server for this call to ever return.
  server->Wait();
  std::cout << "after.. wait\n";
  std::this_thread::sleep_for (std::chrono::seconds(10));
}

int main(int argc, char** argv) {
  RunServer();

  return 0;
}
```

I set up the server such that after serving one request, server will shutdown. Also thought since `server->Shutdown();`  is non-blocking call, the program will wait for 10 seconds before it exists.
But still the valgrind is showing memory leaks.
### Valgrind report:
==6107== LEAK SUMMARY:
==6107==    definitely lost: 0 bytes in 0 blocks
==6107==    indirectly lost: 0 bytes in 0 blocks
==6107==      possibly lost: 1,855 bytes in 9 blocks
==6107==    still reachable: 151,765 bytes in 187 blocks
==6107==         suppressed: 0 bytes in 0 blocks
==6107== 
==6107== For counts of detected and suppressed errors, rerun with: -v
==6107== ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 0 from 0)
Complete report has been attached to this thread.
[memcheckreport.txt](https://github.com/grpc/grpc/files/4412007/memcheckreport.txt)

**Comment by tumusudheer** [comment]
Hi,
Just checking for any help regarding this.

**Comment by nicolasnoble** [comment]
I suspect the shutdown method is wrong here, but @yashykt should be the authority of how it's supposed to happen.

**Comment by tumusudheer** [comment]
Tried with both valgrdin 3.13 and valgrind 3.15 on Ubuntu 18.04  with gcc. Kindly let me know how to fix the shutdown code if the memory leaks are occurring due to shutdown code.

**Comment by tumusudheer** [comment]
Hi,
Just checking for any assistance. Thank you.

**Comment by yashykt** [comment]
Hi, this seems to be working normally. gRPC has some global data structures that are allocated once and never released. We are basically depending on them being cleaned up automatically on process shutdown.
