### ISSUE TITLE
build failure for the generated c++ code when a service contains over 500 rpc methods

### ISSUE THREAD

**Issue by frank-xlj** [grpc/grpc#22530]
### What version of gRPC and what language are you using?
1.17.2-9, c++

### What operating system (Linux, Windows,...) and version?
Windows10

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS 2017 with c++17 support

### What did you do?
Define a service which contains over 500 rpc methods (non-streaming methods) in proto file, the generated grpc.pb.h contains 5 typedefs which is nested template declaration. Those typedefs caused the build failure. 
The error is: C1202: recursive type or function dependency too complex.

### What did you expect to see?
No build failure

### What did you see instead?
build failure message: C1202: recursive type or function dependency too complex.

**Comment by frank-xlj** [comment]
No comments?

**Comment by veblush** [comment]
It's been a while but CI test running with VS2017 is building gRPC continuously so I'm closing this. Please feel free to reopen it if it happens again.

**Comment by Austin-Hu** [comment]
I got the same issue with >500 rpc methods declared in single service, with the configuration below:

**What version of gRPC and what language are you using?**
1.50.1 (protobuf 3.21.8.0), c++

**What operating system (Linux, Windows,...) and version?**
Windows 11

**What runtime / compiler are you using (e.g. python version or version of gcc)**
VS 2022 with c++14/17/20 support

**Comment by frank-xlj** [comment]
> 

We just split rpc methods to multiple services to work around this at that time.

**Comment by Austin-Hu** [comment]
@frank-xlj, yes, we could work around the issue as well, like what you did by commenting out `AsyncService_method1...`, but maybe we need to do this every time when autogen with the .proto file updated.

So we had to work around it with another way you edided as our preference:

> We just split rpc methods to multiple services to work around this at that time.

Thanks!

**Comment by regrainb** [comment]
I have the same issue. And I agree with @Austin-Hu: with an autogen from the .proto file, we will get the issue each time.
We currently are on:
- VS2019.11.7
- GRPC 1.15.1

If we remove the lines, are there consequences in the run of GRPC? and which ones?
When can we hope having a fix for that?
