### ISSUE TITLE
FR: grpc_cli: support for local credentials

### ISSUE THREAD

**Issue by nfelt** [grpc/grpc#22570]
This is a feature request that the `grpc_cli` tool add an option to use [`LocalCredentials`](https://github.com/grpc/grpc/blob/0362df725f1ed9db3cb3e50456e2ad59cb4a1c1b/include/grpcpp/security/credentials.h#L130-L133).  As described in the [python `local_channel_credentials()` API](https://github.com/grpc/grpc/blob/a687274c74b7055a081ec5e1a9fad6f324ae89ef/src/python/grpcio/grpc/__init__.py#L1776), local channel credentials are a better alternative to the `insecure` credential type that can be used in testing situations and allow passing call credentials.

This FR could be implemented by adding support for `--channel_creds_type=local` in addition to the existing options:
https://github.com/grpc/grpc/blob/f930b0bdcc5ede9d9d07770980eb68c2b0df8258/test/cpp/util/cli_credentials.cc#L216

Since local credentials are parameterized with a [connection type](https://github.com/grpc/grpc/blob/2b200d2313e739fa1841edf3ea86ab8532862505/include/grpc/grpc_security_constants.h#L139), currently `LOCAL_TCP` and `UDS`, this would presumably also require adding a flag like `--local_connection_type=local_tcp,uds` to choose the correct connection type.  That flag could probably default to `local_tcp` to match the Python implementation above.

Note that I realize local credentials are an experimental credential option, but as precedent `grpc_cli` already implements `--channel_creds_type=alts` which is also experimental.

**Comment by donnadionne** [comment]
We acknowledge this may be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.

**Comment by jiangtaoli2016** [comment]
@yihuazhang grpc_cli is a useful tool. We shall add local credentials support.

**Comment by yihuazhang** [comment]
SG. I will work on it this week. We have an internal feature request for it as well.

**Comment by yihuazhang** [comment]
F.Y.I. mailed out https://github.com/grpc/grpc/pull/23037.

**Comment by markdroth** [comment]
Sounds like this is fixed.
