### ISSUE TITLE
python -m grpcio_tools.protoc behaves counter to how it seemingly should behave 

### ISSUE THREAD

**Issue by xkortex** [grpc/grpc#22579]
Heart of the matter: https://github.com/grpc/grpc/blob/master/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L34-L36

Kinda related to #8753 but it seems like it hasn't really resolved. 

### What version of gRPC and what language are you using?
python3.6.9, python3.7.7

### What operating system (Linux, Windows,...) and version?
tested on ubuntu 18, mac sierra

### What runtime / compiler are you using (e.g. python version or version of gcc)
python3.6.9, python3.7.7

**Env1:**
grpcio           1.27.2
grpcio-tools     1.27.2
pip              20.0.2
protobuf         3.11.3

**Env2**
grpcio                   1.27.2
grpcio-health-checking   1.15.0
grpcio-tools             1.24.3
googleapis-common-protos 1.6.0
protobuf                 3.10.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

```bash 
git clone -b bug/grpcio https://github.com/xkortex/protosanity.git
cd protosanity/test
make test # this will succeed
make fail  # this will fail
```

### What did you expect to see?
successfully generate `foolib/protobuf/myservice_pb2_grpc.py`

### What did you see instead?
```
python -m grpc_tools.protoc --proto_path=foolib/protobuf --python_out=. --grpc_python_out=. ./foolib/protobuf/myservice.proto
foolib/protobuf/common.proto: File not found.
myservice.proto:3:1: Import "foolib/protobuf/common.proto" was not found or had errors.
myservice.proto:23:5: "MyImportedError" is not defined.
myservice.proto:26:5: "foolib.protobuf.MyImportedError" is not defined.
make: *** [fail] Error 1
```

If you instead run 
```PB_MODE=alt PB_ARG_IDX=1 python -m foolib.compile_pb --proto_path=foolib/protobuf --python_out=. --grpc_python_out=. ./foolib/protobuf/myservice.proto```

which is analogous to 
```python
# protoc.py
if __name__ == '__main__':
    proto_include = pkg_resources.resource_filename('grpc_tools', '_proto')
    sys.exit(main(sys.argv[1:])
```

it works totally fine. If we set `PB_ARG_IDX=0`, we get `foolib/protobuf/common.proto: File not found.`, and if we run 
```
PB_MODE=protoc PB_ARG_IDX=1 python -m foolib.compile_pb --proto_path=foolib/protobuf --python_out=. --grpc_python_out=. ./foolib/protobuf/myservice.proto` 
```
```
./foolib/protobuf/myservice.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

`PB_MODE=protoc PB_ARG_IDX=0` gives the usual File not found,
which is really strange, because the proto path is in fact spelled out. `sys.argv[0]` should just be the script name, so I have no idea why it impinges on the protoc compilation process. 

I can
```
	cd foolib/protobuf
	python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. common.proto 
```
but myservice.proto fails. 

Finally, this recipe compiles, but the generated python is broken: 
```
cd foolib/protobuf && \
	python -m grpc_tools.protoc --proto_path=. --proto_path=../../ --python_out=. --grpc_python_out=. common.proto && \
	python -m grpc_tools.protoc --proto_path=. --proto_path=../../ --python_out=. --grpc_python_out=. myservice.proto;
```
```
$ python -c "import foolib.protobuf.myservice_pb2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mike/wk/src/github.com/xkortex/protosanity/test/foolib/protobuf/myservice_pb2.py", line 26, in <module>
    dependencies=[foolib_dot_protobuf_dot_common__pb2.DESCRIPTOR,])
  File "/Users/mike/.virtualenvs/ml/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 879, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "myservice.proto":
  foolib/protobuf/common.proto: Import "foolib/protobuf/common.proto" has not been loaded.
  foolib.protobuf.ProcResponse.err: "foolib.protobuf.MyImportedError" seems to be defined in "common.proto", which is not imported by "myservice.proto".  To use it here, please add the necessary import.
  foolib.protobuf.ProcResponse.err2: "foolib.protobuf.MyImportedError" seems to be defined in "common.proto", which is not imported by "myservice.proto".  To use it here, please add the necessary import.
```

Edit: you can now `pip install protosanity/test` and then start `python -m foolib.server` and then `python -m foolib.client 'ls -lah'` to run a test example (just runs the command passed on the server side).

**Comment by xkortex** [comment]
Huh, so actually this does what I expected to to now: 
```
	python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. ./foolib/protobuf/common.proto
	python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. ./foolib/protobuf/myservice.proto
```

I seem to remember this path structure/ protoc syntax not working a year ago, like it generated the wrong relative import path. Maybe I'm misremembering or had some minor yet significant difference. 

Either way, it seems like both `-I.` and `-Ifoolib/protobuf` should work the same. Why does the latter break?

**Comment by donnadionne** [comment]
Please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
