### ISSUE TITLE
TIMEOUT: cpp_macos_dbg_native.bins/dbg/boringssl_crypto_test --gtest_filter=BNTest.PrimeChecking  GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22577]
https://source.cloud.google.com/results/invocations/29c0fade-869a-42b9-b6b4-bdb6d3ef81d0/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_dbg_native/tests

**Comment by donnadionne** [comment]
The test has been healthy for 14+ days
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_basictests_c_cpp

Closing the issue
