### ISSUE TITLE
cmake gRPC_BUILD_TESTS build failing

### ISSUE THREAD

**Issue by raboof** [grpc/grpc#22574]
On current master (46838d1a0446356f2b9ca69052dc2d29afcfd82e), `cmake -DgRPC_BUILD_TESTS=ON && make` fails for me with:

```
[ 97%] Building CXX object third_party/benchmark/test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o
/tmp/grpc/third_party/benchmark/test/cxx03_test.cc:8:2: error: #error C++11 or greater detected. Should be C++03.
    8 | #error C++11 or greater detected. Should be C++03.
      |  ^~~~~
/tmp/grpc/third_party/benchmark/test/cxx03_test.cc:12:2: error: #error C++11 or greater detected by the library. BENCHMARK_HAS_CXX11 is defined.
   12 | #error C++11 or greater detected by the library. BENCHMARK_HAS_CXX11 is defined.
      |  ^~~~~
make[2]: *** [third_party/benchmark/test/CMakeFiles/cxx03_test.dir/build.make:63: third_party/benchmark/test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:20170: third_party/benchmark/test/CMakeFiles/cxx03_test.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

What would be the direction to resolve this? I guess options are:
* change cxx03_test.c to skip the test when C++11 is detected instead of failing
* change the cmake configuration to skip cxx03_test.c when C++11 is used
* ...?

Which would you prefer?

**Comment by raboof** [comment]
Hm, of course `third_party/benchmark` is not in this repo ;), and their `test/CMakeLists.txt` does seem to have some logic to treat this test specially.

I didn't really look closer, but 'just blindly' updating the benchmark submodule *seems* to do the trick. Perhaps it's as simple as that?

**Comment by donnadionne** [comment]
It appears that there is no real GRPC issues here.  Closing
