### ISSUE TITLE
Think through reconnection for SSL

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2258]
There are various cases where we need to reconnect the underlying transport for a channel. This currently means reusing a security_connector. Think through the implications of this and figure out if there are security implications.

#2256 gets things to the point where no objects are leaked.
#2208 solidifies when this is allowed to happen.

**Comment by jboeuf** [comment]
Is this still an issue considering my last comment on #2256?

**Comment by hsaliak** [comment]
@ctiller is this still relevant?
