### ISSUE TITLE
can grpc allow .proto file importing remote proto definition?

### ISSUE THREAD

**Issue by RaymondReddington** [grpc/grpc#22587]
can grpc allow .proto file importing remote proto definition?
grpc definition is always service only definition, and different service may share message structure.
store same message definition in different grpc deinition files will make it hard to change , update or fix message definition.

**Comment by donnadionne** [comment]
We acknowledge this may be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.

**Comment by donnadionne** [comment]
Please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
