### ISSUE TITLE
grpc-python get reflected services

### ISSUE THREAD

**Issue by foreverchaos** [grpc/grpc#22590]
hello, 
I want to request a feature for grpc-python, like grpc_cli in go
Given a service endpoint: 1.2.3.4:50001, return the all services list and rpc api under these services
is there an existing api for above in grpc-python?

**Comment by lidizheng** [comment]
Please see your thread in grpc-io group: https://groups.google.com/g/grpc-io/c/SS9pkHMiLK4/m/r8XM1mqfBQAJ

We handle questions in Google groups and StackOverflow.
