### ISSUE TITLE
C# remove the class constraint on TRequest / TResponse

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#22605]
The API currently has a fundamental constraint against value-types, with:

``` c#
            where TRequest : class
            where TResponse : class
```

scattered throughout lots of the call APIs. This is fine for the Google protobuf implementation which is always classes, but I've seen repeated calls for support for value-types - both [from protobuf-net.Grpc users](https://github.com/protobuf-net/protobuf-net.Grpc/issues/27), and [separately (F#, etc)](https://stackoverflow.com/q/61082096/23354).

I would like to test the water for how people think about removing this constraint. Fortunately this constraint doesn't go through to the `Marshaller<T>` API, so the work isn't actually huge - it is only really used for the response stream APIs, where `null` is interpreted to mean "no data". This can be trivially avoided. I have [smoke-tested the changes required](https://github.com/mgravell/grpc/commit/7ae6a4e056f6a6d9184e61e1c6732e28e9f1a65f), and it doesn't seem arduous, so: how would people feel about doing this for real?

In particular, note that I've only checked the "core" implementation - the dotnet implementation may also need work (/cc @JamesNK - and yes, I'll happily do that work too if this is a direction the API wants to go)

**Comment by mgravell** [comment]
@JamesNK [and here for the grpc-dotnet impact](https://github.com/mgravell/grpc-dotnet/commit/076e4f64359b142f3c535e623a6dc93d71113f52) - not including the actual `TRequest 
: class`/`TResponse : class` removals, which are dependent on the API change here first, but hypothetically *the changes in this message* could be applied in advance separately

**Comment by mgravell** [comment]
(obviously if I were to put together PRs for either of these, I would add tests actually showing it being used with value-types, but that is secondary to checking that folks are interested in the API change)

**Comment by mgravell** [comment]
Any early thoughts on where this ranks? something on a scale between "no way, never, not going to happen" thru "hmm, interesting, maybe at the next major" all the way up to "hell yeah, let's do this"? @jtattermusch maybe?

**Comment by Donis-** [comment]
+1 Would be really beneficial.

**Comment by jtattermusch** [comment]
I think this is definitely something we can consider in the next major version but removing the constraint is a breaking change AFAIK so we can't really do it unless it's critically important (https://github.com/grpc/grpc/blob/master/doc/versioning.md).

It would actually be nice to start collecting ideas for API improvements for the next major version - such list would come in handy if we are at some point forced to update the public API .(to be clear we're not planning a next major version any time soon)

**Comment by mgravell** [comment]
btw, I investigated this, and I'm not convinced it is even a breaking change, either at runtime or build time.

## Runtime

The constraint is burned into the *declaration*, but not the *call site*; in IL terms this is:

``` msil
    .method private hidebysig static 
        void WithConstraint<class T> () cil managed 
``

vs

``` msil
    .method private hidebysig static 
        void NoConstraint<T> () cil managed
```

which is fine, but *at the call site*, the value-type vs ref-type of the `T` is burned in *either way*; i.e.

calling a generic method without a constraint, for a ref-type `Foo`:

``` msil
call void C::NoConstraint<class Foo>()
```

and calling a generic with a constraint, for a ref-type `Foo`:

``` msil
call void C::WithConstraint<class Foo>()
```

(if the generic arg is itself coming from a generic parameter, then the special `!!T` is used in all cases)

So: I *do not believe* that removing the constraint would cause any runtime problems whatsoever.

## Build time

Any code that exists and compiles today will still be happy with *fewer* constraints, and it is not possible to overload APIs based just on the existence (or not) of a constraint, so: removing the constraint should not impact any existing code, unless someone has a test method that is "try to compile this code (using value-types) via Roslyn and assert that it fails", and we break their test :)

---

If I'm wrong here, I'm always happy to learn: but I simply don't think this represents a breaking change *at all*.

Conversely: *adding* a generic type constraint: absolutely, no argument there.

**Comment by mgravell** [comment]
As a validation, I created a library with:

``` c#
public class Foo<T> where T : class
{
    public override string ToString()
    {
        var type = typeof(T);
        var category = type switch
        {
            null => "null",
            _ when type.IsValueType => "struct",
            _ when type.IsClass => "class",
            _ when type.IsInterface => "interface",
            _ when type.IsGenericParameter => "<T>",
            _ => "???",
        };
        return $"{typeof(T).Name}, {category}";
    }
}
```

and a calling project that consumes this:

``` c#
// direct
Console.WriteLine(new Foo<SomeClass>());

// runtime
EvilReflectionTest(typeof(SomeClass));
EvilReflectionTest(typeof(SomeStruct)); // expect this to fail initially

static void EvilReflectionTest(Type type)
{
    try
    {
        Console.WriteLine(Activator.CreateInstance(typeof(Foo<>).MakeGenericType(type)));
    }
    catch (Exception ex)
    {
        Console.WriteLine($"{type.Name}: {ex.Message}");
    }
}
class SomeClass { }
struct SomeStruct{ }
```

This executes as expected:

``` txt
SomeClass, class
SomeClass, class
SomeStruct: GenericArguments[0], 'SomeStruct', on 'Foo`1[T]' violates the constraint of type 'T'.
```

Now, if we remove the generic constraint in the library **without** rebuilding the application, but simply dropping the new library over the top, and re-run it:

``` txt
SomeClass, class
SomeClass, class
SomeStruct, struct
```

So: no runtime break at all; it *is* (as shown) possible to detect the difference by observing the JIT failure, but that doesn't impact any realistic existing code.

Likewise, there is no build-time impact whatsoever, other than that we can now do additional things, i.e. 

``` c#
Console.WriteLine(new Foo<SomeStruct>());
```

So: to emphasize: I don't think this represents a break scenario.

**Comment by neuecc** [comment]
@JamesNK 
@jtattermusch
@mgravell

We also now encountering this problem.
MagicOnion that based on grpc-dotnet, already used by some users, is using normal C# types.
https://github.com/Cysharp/MagicOnion/

Until now, TRequest and TResponse were treated as byte[] in the gRPC layer, and deserialized into class and struct in another layer (body is MessagePack for C#).
To support IBufferWriter, I looked at both client/server, but to do so, I needed to pass the actual type to TRquest/TResponse.
That includes struct.

For example, in MagicOnion
`UnaryResult<int> Sum(int x, int y)`.
is serialized by MessagePack as `TRequest = ValueTuple(int, int), TResponse = int` and forwarded by gRPC.

I'm in trouble right now.
If compatibility can be maintained, I would like the constraint to be removed now,
and If not, please reopen the issue.

**Comment by mayuki** [comment]
In addition to what he said, Essentially, the following code should work for a custom `Marshaller` using MessagePack:

```csharp
// (1)
var marshaller = new Marshaller<TResponse>(
    serializer: (obj, ctx) =>
    {
        MessagePackSerializer.Serialize(ctx.GetBufferWriter(), obj, serializerOptions);
        ctx.Complete();
    },
    deserializer: (ctx) => MessagePackSerializer.Deserialize<TResponse>(ctx.PayloadAsReadOnlySequence(), serializerOptions)
);

var method = new Method<TRequest, TResponse>(...);

```

But due to the `class` constraint, it needs to be manually boxed as the following code.

```csharp
// (2)
var marshaller = new Marshaller<Box<TResponse>>(
    serializer: (obj, ctx) =>
    {
        MessagePackSerializer.Serialize(ctx.GetBufferWriter(), obj.Value, serializerOptions);
        ctx.Complete();
    },
    deserializer: (ctx) => new Box<TResponse>(MessagePackSerializer.Deserialize<TResponse>(ctx.PayloadAsReadOnlySequence(), serializerOptions))
);

var method = new Method<TRequest, Box<TResponse>>(...);
...

public class Box<T>
{
    public readonly T Value;

    public Box(T value)
    {
        Value = value;
    }
}
```

This means that we need four code paths, `(RefType, RefType)`, `(RefType, ValueType)`, `(ValueType, RefType)` and `(ValueType, ValueType)` with and without boxing. We don't want to add this complexity to our code where possible.

**Comment by mgravell** [comment]
To reiterate:

- there's a reasonable level of demand for the change from multiple sources
- by my validation (although I don't claim infallibility), it isn't a breaking change
- I'm willing to write the PRs to make the change work, for both the Google and Microsoft bits; I just need a "yes, this would be considered"

**Comment by mgravell** [comment]
So I did a thing... ^^^
