### ISSUE TITLE
How to take the initiative Server Call the active Client Function

### ISSUE THREAD

**Issue by fengshaoxie** [grpc/grpc#22601]
### What version of gRPC and what language are you using?
grpc-1.27.x  C++ 

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.4

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc version 7.5.0
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
I want to  make one Server and 
 one Client ,after Client Connected to Server ,Server send message to client
### What did you expect to see?
same to previous question

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by donnadionne** [comment]
Please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
