### ISSUE TITLE
Surprisingly high memory usage in async helloworld C++ example

### ISSUE THREAD

**Issue by MatthewT123** [grpc/grpc#22603]
### What version of gRPC and what language are you using?
C++ v1.25.0

### What operating system (Linux, Windows,...) and version?
Linux, ubuntu-18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 7.4.0

### What did you do?
Ran the greeter async client and server example with the three minimal edits detailed below in [greeter_diffs.txt](https://github.com/grpc/grpc/files/4445428/greeter_diffs.txt).  This makes 100k async calls to the greeter.  All executables are on the same machine.

### What did you expect to see?
Memory usage to increase, but not excessively.  I expected the thread consuming replies in the client to delete the replies as they arrive, so that the usage would only be those that were queued waiting for the thread, so usage would go up but plateau.  Messages are small so the rise should be small.  This test was after writing code for a more complex example and seeing similar but much more exaggerated behaviour.

### What did you see instead?
Memory usage in the client of around 12k/request (1.2GB total) (note 1), which seems excessive.  Memory usage increasing linearly during the run and not decreasing until all requests are processed.  When the client memory limit was imposed many of the calls failed due to lack of memory, rather than the library attempting to stick to the limit but using more if required, which is what the docs suggest.  

In contrast I found that adding the resource limit in the server worked as expected - it went over 50MB peaking at around 100MB, but was still much smaller than the 1GB or so without the limit.

Note 1) Space measured using the DATA (stack + heap) field in 'top', ignoring the usual fields for virtual memory as these misleadingly include the executable and libraries.  

### Anything else we should know about your project / environment?
What I am unsure of is whether this is a reasonable test that shows high overheads for large numbers of calls - or whether I have constructed an artificial example that overloads the sytem in an unrealistic way.  I would in practice be running large numbers of requests - though I chose this number (100k) mostly because it meant the process ran long enough for the resource usage to be easily observed.

**Comment by gnossen** [comment]
@nicolasnoble Are you actively working on this? It looks like this could be related to a memory leak in Python.

**Comment by yashykt** [comment]
Checking in. Are you seeing this issue on the newer releases as well?
