### ISSUE TITLE
FLAKE: nodepurejs interop failures

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22607]
https://source.cloud.google.com/results/invocations/7b08fe77-8ccd-4869-b9e3-b04c99e59830/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_prod:nodepurejs:default:server_streaming:tls;row=3

It looks like several tests are failing due to calls terminating with status CANCELLED.

**Comment by gnossen** [comment]
It appears that this is a partly a problem with changes to the GFE.

**Comment by donnadionne** [comment]
Failure seems to have gone away: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_toprod

(wither the run is a  pass or the few failures in this build are no longer due to this issue)

Consider closing this issue
