### ISSUE TITLE
Spurious error messages running tests that use gRPC client with Bazel

### ISSUE THREAD

**Issue by bdhess** [grpc/grpc#22613]
### What version of gRPC and what language are you using?
C++; commit `78ace4cd5dfcc1f2eced44d22d752f103f377e7b` built with Bazel

### What operating system (Linux, Windows,...) and version?
CentOS Linux release 7.7.1908 (Core)
This is a GCE VM.

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

### What did you do?
Used Bazel to run integration tests that use a gRPC client with Google default credentials.  The GCE VM has an IAM service account identity configured. The integration tests completed successfully.

### What did you expect to see?
No spurious glog messages.

### What did you see instead?
Persistent messages glog messages at level ERROR
```
E0407 22:17:39.608810525   26304 credentials_generic.cc:34]  Could not get HOME environment variable.
```

gRPC logs this at level ERROR despite the fact that it goes on to successfully create GCE credentials.

### Anything else we should know about your project / environment?

Bazel strips as much out of the environment as possible, so HOME is not set.

**Comment by yashykt** [comment]
I'm sorry that this didn't get a response earlier, but the error makes it clear that the `HOME` environment variable is not set
