### ISSUE TITLE
C#: Running in Debian Buster docker container fails with "Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/app/libgrpc_csharp_ext.x86.so"

### ISSUE THREAD

**Issue by pawelpetruch** [grpc/grpc#22632]
### What version of gRPC and what language are you using?
C#

### What operating system (Linux, Windows,...) and version?
Docker, Debian 3.1-buster-slim-arm32v7 running on Raspberry Pi 3.

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Core 3.1

### What did you do?
I was trying to build a docker image to use it on arm32v7 (RPi). 
This build without specifying **-arm32v7** and **-r linux-arm** works fine on linux-amd64.

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
COPY ["Project/Project.csproj", "Project/"]
WORKDIR /src
RUN dotnet restore "Project/Project.csproj"
COPY . .
WORKDIR "/src/Project"
RUN dotnet build "Project.csproj" -c Release -r linux-arm -o /app/build

FROM build AS publish
RUN dotnet publish "Project.csproj" -c Release -r linux-arm -o /app/publish 

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Project.dll"]
```
### What did you expect to see?
The application working fine.

### What did you see instead?
```
System.IO.IOException: Error loading native library "/app/libgrpc_csharp_ext.x86.so". /app/libgrpc_csharp_ext.x86.so: cannot open shared object file: No s
uch file or directory
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Grpc.Core.Server..ctor()
```

### Anything else we should know about your project / environment?
Similar to #15605 but not using Alpine.
libgrpc_csharp_ext.x86.so and libgrpc_csharp_ext.x64.so are present in a running container in the folder /app/.

**Comment by jtattermusch** [comment]
The Grpc.Core nuget doesn't provide a pre-built version of libgrpc_csharp_ext.x64.so for ARM processors (only for intel - feel free to look at the native libraries provided by default by inspecting the contents of the nuget), so what you're trying to do is not supported.

**Comment by pawelpetruch** [comment]
My post doesn't mention libgrpc_csharp_ext.**x64**.so but  libgrpc_csharp_ext.**x86**.so.

How could I use the grpc library in this container then? Would I need to build it manually?

**Comment by jtattermusch** [comment]
thanks for the correction - but it's the same situation. Yes, if you want it to run it on ARM, you'd need to build grpc_sharp_ext..so manually for your platform.
