### ISSUE TITLE
Provide a way to customize generated classes in dotnet Grpc.Tools

### ISSUE THREAD

**Issue by HassanHashemi** [grpc/grpc#22637]
### Is it a feature request?
Yes, However not sure if it's technically possible (because we just delegate the call to `protoc` command line tool to generate the code).

we are in the process of migrating a CQRS over rest API based app to GRPC.
today our API actions look like this: `FooController`

    public async Task<IActionResult> CreateFoo(CreateFooCommand command)
    {
        var result = await CommandBus.Execute(command);
        return Created(result.Uri);
    }

In order to apply multiple AOP techniques, the `CreateFooCommand`  implements multiple interfaces.
In context of a GRPC service this scenario requires manual mapping between the parameters of generated service methods and the command, e.g: `FooService.cs`

    public override async Task<CreateFooReply> Create(CreateFooRequest request, context)
    {
        // 1. map request parameter
        var command = mapper.Map<CreateFooRequest, CreateFooCommand>(request);
        var commandResult = await CommandBus.Execute(command);
        
        // 2. map response parameter
        return mapper.Map<CreateFooCommandResult, CreateFooReply>(commandResult);
    }

### Solution
Provide a way to customize `CreateFooRequest` (**or access the internal code generator**) so that we can have it implement an interface, as result we will have

    public override Task<CreateFooReply> Create(CreateFooRequest request, context)
    {
         return CommandBus.Execute(request);
    }

/cc @kkm000

**Comment by jtattermusch** [comment]
Technically you've always had the opportunity to customize your codegen by forking https://github.com/grpc/grpc/tree/master/src/compiler (but TBH I wouldn't recommend that unless your use case is highly specialized and you're willing to invest a lot of time into the solution).

We are not planning any options to "customize" the generated code (in the way you described). Our codegen is meant to be general purpose and works well in a wide variety of use cases and there's no place for accommodating special requests like yours.

**Comment by HassanHashemi** [comment]
Not sure if my request was something "special".
But the issue was closed anyway.
