### ISSUE TITLE
Bazel build fails with incompatible_load_cc_rules_from_bzl

### ISSUE THREAD

**Issue by KeithMoyer** [grpc/grpc#22653]
### What version of gRPC and what language are you using?
HEAD (b25682427c)

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel 3.0.0

### What did you do?
`bazel build --incompatible_load_cc_rules_from_bzl //:grpc`

### What did you expect to see?
Successful build

### What did you see instead?
```
ERROR: .../external/upb/BUILD:57:1: in cc_library rule @upb//:port: The native C++/Objc rules are deprecated. Please load cc_library from the rules_cc repository. See http://github.com/bazelbuild/rules_cc and https://github.com/bazelbuild/bazel/issues/7643. You can temporarily bypass this error by setting --incompatible_load_cc_rules_from_bzl=false.
```

### Anything else we should know about your project / environment?
`incompatible_load_cc_rules_from_bzl` (https://github.com/bazelbuild/bazel/issues/8743) is currently tagged to flip in Bazel 4.0. I have my team's project compatible with this flag other than the gRPC dependency (so we cannot even run our tests with this flag to keep from backsliding in our own compatibility).
gRPC previously addressed `incompatible_load_proto_rules_from_bzl` in 06ecc8729056c6cdc5e50fc35e11b70e744f0a15, you already have `rules_cc` imported as a dependency, and this seems like the kind of change about which you all would already be in discussion with the Bazel team. However, I could not find any issue indicating that this was known or in-progress. So, filing a bug to make sure this is being (or is planned to be) addressed.

**Comment by yashykt** [comment]
This seems to be fixed at head now
