### ISSUE TITLE
NO_PROXY handling doesn't support CIDR addresses

### ISSUE THREAD

**Issue by electrofelix** [grpc/grpc#22681]
# What version of gRPC and what language are you using?

1.27.1 python

### What operating system (Linux, Windows,...) and version?

Debian 10 (python:3.7-slim)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7

### What did you do?

Spun up a container in a local k8s development environment with NO_PROXY set to include the local CIDR range for the cluster internal IP addresses in addition to other settings for the internal corp network so that it could connect via GRPC to another pod within the cluster while also accessing resources external to the corporate network.

### What did you expect to see?

Client should connect without going through the proxy

### What did you see instead?

Debug logs showing response from the proxy and connection failed.

### Anything else we should know about your project / environment?

Looking at the code https://github.com/grpc/grpc/blob/4466a4ce6156cd9b93a7ce130bf3f59b9c09d700/src/core/ext/filters/client_channel/http_proxy.cc#L147-L154 I can see that it currently should work for complete matches for IP addresses, hostnames and I think domains, though I'm a little rusty with C so I'm not completely sure. Looks like the piece of code `&(server_host.get()[uri_len - no_proxy_len]))` is indexing into the string for a starting point so that if you have `hostname.domainname` and `.domainname` is in the no_proxy that it would start the comparison from the 9th character in the server_host variable in order to compare domain names only.

Though this does look like there is a subtle bug should someone use a domain name in the no_proxy without a leading dot as `domainname` would also match `hostname.someotherdomainname` as well

I'm thinking making use of something like https://stackoverflow.com/a/28535174/1597808 and if the return value is >=0 then https://stackoverflow.com/a/31041121/1597808 would be used to complete the comparison. Little unsure if it's correct to convert the server_host to an IP address in such a case if it's not already an IP.

Is it worth making a stab at fixing this?

**Comment by yashykt** [comment]
Hi, sorry for the super late response. This does seem like low priority to me. A range in NO_PROXY does not seem to have wide support, but if you are interested in it, contributions would definitely be apprecated.

**Comment by stanhu** [comment]
https://github.com/grpc/grpc/pull/31119 seems to work for me.
