### ISSUE TITLE
undefined symbol: __atomic_exchange_8 when building grpc_csharp_ext on raspberry pi

### ISSUE THREAD

**Issue by pawelpetruch** [grpc/grpc#22685]
### What version of gRPC and what language are you using?
1.28.1 and C# 

### What operating system (Linux, Windows,...) and version?
Raspbian, Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
To build a native library: Raspbian 8.3.0-6+rpi1

### What did you do?
Client is being initialized in a different part of the code. Runs okay on AMD. 

```
                var request = new MonitorRequest { Start = true };

                using (var call = client.InitializeMonitoring(request))
                {
                    var responseStream = call.ResponseStream;
                    while (await responseStream.MoveNext())
                    {
                        // some things
                    } 
                }
```

After `var request = new MonitorRequest { Start = true };` I get the below error.

### What did you expect to see?
A working client. 

### What did you see instead?

dotnet: symbol lookup error: /app/libgrpc_csharp_ext.x86.so: undefined symbol: __atomic_fetch_add_8

### Anything else we should know about your project / environment?
It is running on RPi 3 in a Linux container. libgrpc_csharp_ext.x86.so is built on RPi.

**Comment by nicolasnoble** [comment]
There are several layers of information missing here.

But most importantly: did you download the x86 package hoping it'd work on an ARM architecture?

**Comment by pawelpetruch** [comment]
@nicolasnoble As mentioned above - libgrpc_csharp_ext.x86.so was built on RPi.

I used this script: 
https://github.com/erikest/libgrpc_csharp_ext/blob/master/compile_csharp_ext.sh

**Comment by nicolasnoble** [comment]
Oh, the script is renaming it to x86, whatever the platform, I see.

In this case, if you've built on the same platform you're trying to run, this is a problem with your environment. `__atomic_fetch_add_8` is a function provided by the compiler, and used by the compiler to generate atomic code. If your compiler generates this code, and your system libraries don't provide it, it means you've got discrepancy between your compiler and your system libraries.

**Comment by jtattermusch** [comment]
Btw, possibly unrelated, but we have a distribtest that checks that crosscompilation for raspberry pi works, so you might also try that https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_raspberry_pi.sh.

Please also note that runing gRPC C# on raspberry pi isn't officially supported (so you might run into other issues).
