### ISSUE TITLE
Failure: build_docker_dart

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#22691]
https://source.cloud.google.com/results/invocations/eddfb3fd-16f0-4da6-a736-00687eaa9319/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

seen on #22575

**Comment by markdroth** [comment]
Seeing a similar failure here:

https://source.cloud.google.com/results/invocations/bd793d01-81f1-425d-9199-bea2803553ae/targets/github%2Fgrpc%2Finterop_docker_build/tests

**Comment by yashykt** [comment]
closing it in favor of #23055
