### ISSUE TITLE
Cronet transport : Fail writes when end of stream is received

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#22693]
The original bug report https://github.com/grpc/grpc/issues/14812 was for chttp2
https://github.com/grpc/grpc/issues/20409 is for inproc

https://github.com/grpc/grpc/pull/22668 provides the fix for inproc and also adds a test for it.

Muxi, can you check if this needs to be fixed for cronet too.

**Comment by muxi** [comment]
I believe this has been taken care of in #22693.
