### ISSUE TITLE
php serializeToJsonString bug

### ISSUE THREAD

**Issue by YeDongaidiiqu** [grpc/grpc#22702]
### What version of gRPC and what language are you using?
grpc: 1.26.0
php:  v3.3.16

### What operating system (Linux, Windows,...) and version?
Linux master1 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

["name"=>'',
"age"=>0]

->serializeToJsonString()

### What did you expect to see?
["name"=>'',
"age"=>0]

### What did you see instead?
[]

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
linux

**Comment by stanley-cheung** [comment]
This is a protobuf issue. Please log an issue to the repo https://github.com/protocolbuffers/protobuf/.
