### ISSUE TITLE
[FLAKE] Bazel C/C++ Dbg MacOS test/cpp/client/credentials_test

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#22725]
https://source.cloud.google.com/results/invocations/779ee44d-fb24-45df-8030-3d2640ff1d19/targets/%2F%2Ftest%2Fcpp%2Fclient:credentials_test/tests

**Comment by jtattermusch** [comment]
see internal b/153136407

**Comment by matthewstevenson88** [comment]
Flaky test removed in #21932. Have separate tracking for resending the test.
