### ISSUE TITLE
[FLAKE] Bazel RBE UBSAN C/C++ json_run_localhost_cpp_protobuf_sync_unary_ping_pong_insecure

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#22726]
test/cpp/qps/json_run_localhost_cpp_protobuf_sync_unary_ping_pong_insecure@poller=epoll1.test/cpp/qps/json_run_localhost_cpp_protobuf_sync_unary_ping_pong_insecure@poller=epoll1

https://source.cloud.google.com/results/invocations/021106d4-8525-455b-aee6-55b69e7e32bd/targets/%2F%2Ftest%2Fcpp%2Fqps:json_run_localhost_cpp_protobuf_sync_unary_ping_pong_insecure@poller%3Depoll1/tests

**Comment by veblush** [comment]
Closing (obsolete)
