### ISSUE TITLE
C++ async client code extremely slow

### ISSUE THREAD

**Issue by durkmurder** [grpc/grpc#22724]
### What version of gRPC and what language are you using?
v.1.28.1

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.5.0

### What did you do?
Tried using callback API with reactors from `Stub::experimental_async()`. Comparing to sync unary call performance is extremely poor. Seems like CQ is delivering events with big lag. 

### What did you expect to see?
Expected to see same performance(or near the same) as sync or async calls. 

### What did you see instead?
Did some benchmarking to compare against sync version:

Sync version:
    Client Before UnaryCall: 1587471542330
    Server UnaryCall: 1587471542332
    Client After UnaryCall: 1587471542332
In total 2ms for call.

Async(Callback) version:
    Client Before UnaryCall: 1587471542339
    Server UnaryCall: 1587471547341
    Client onDone: 1587471552339
    Client After acquire: 1587471552339
5s from starting a call and sending response.
5s from getting response and delivering it to user code in `onDone`.
In total 10s.

### Anything else we should know about your project / environment?
I am using setup where client and server run from same process just on different threads. 
Code that I have used:
Server:
```
class TestServer : public test::TestService::Service {
    // Service interface
public:
    grpc::Status UnaryCall(grpc::ServerContext *context, const test::RequestCall *request, test::ResponseCall *response) override
    {
        response->set_requestid(request->requestid());
        std::cout << "Server UnaryCall: " << QDateTime::currentMSecsSinceEpoch() << std::endl;
        return grpc::Status{};
    }
```
Client sync:
```
std::cout << "Client Before UnaryCall: " << QDateTime::currentMSecsSinceEpoch() << std::endl;
auto status = stub->UnaryCall(&ctx, request, &response);
std::cout << "Client After UnaryCall: " << QDateTime::currentMSecsSinceEpoch() << std::endl;
```
Client async(callbacks):
```
struct UnaryReactor : grpc::experimental::ClientUnaryReactor {
    UnaryReactor(QSemaphore &sema, grpc::Status &status) :
        sema(sema),
        status(status)
    {
    }
    virtual void OnDone(const ::grpc::Status& s) override
    {
        std::cout << "Client onDone: " << QDateTime::currentMSecsSinceEpoch() << std::endl;
        status = s;
        sema.release();
    }
    virtual void OnReadInitialMetadataDone(bool /*ok*/) override
    {

    }

    QSemaphore &sema;
    grpc::Status &status;
};

UnaryReactor reactor(sem, status);

std::cout << "Client Before UnaryCall: " << QDateTime::currentMSecsSinceEpoch() << std::endl;
stub->experimental_async()->UnaryCall(&ctx, &request, &response, &reactor);
reactor.StartCall();
sem.acquire();
std::cout << "Client After acquire: " << QDateTime::currentMSecsSinceEpoch() << std::endl;
```

**Comment by yashykt** [comment]
The callback API needs the event manager poller to work properly. Basically, background threads which poll the fds. This is not available yet and hence the slow processing speed.

**Comment by mbroadst** [comment]
@yashykt @vjpai can you speak more about this? In particular I'm interested in learning more about [these lines|https://github.com/grpc/grpc/blob/master/src/cpp/server/server_cc.cc#L1337-L1349] which say:

**Comment by yashykt** [comment]
@drfloob might be able to provide some more information on the current status of the event manager work.

As for the alternative CQ variant, @vjpai can you provide more details. I don't know the exact status of this.

**Comment by drfloob** [comment]
@mbroadst The fact that we're looking at almost exactly a 5s delay between client send and server receive (5002ms) has me suspect there's a timeout involved somewhere. Since you're using Qt (assumed given the use of Qsemaphore here), I wonder if maybe a thread is being tied up somewhere, maybe via the Qt event loop? I could be off, but I'd recommend trying to gather more telemetry data from your example.

While I think it's maybe tangential to this discussion, I am doing some work to replace gRPC's underlying I/O mechanisms, and it's a ways off. You're right though, the background poller is only used internally at Google at the moment.

@vjpai might have more insight into where this sort of regular delay might come from, if it is related to the Callback Alternative implementation.

**Comment by drfloob** [comment]
Apologies, I didn't notice there are two different conversations going on here, two different folks.

@durkmurder The first paragraph above was in response to your original post, if you're still interested.

@mbroadst that's not really related to this issue I don't think, but I've replied above with some background information. Please feel free to take the discussion to the mailing list or gitter if you have any further questions.

**Comment by yashykt** [comment]
@drfloob the 5 second timeout is coming from the frequency of the backup poller I believe https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/src/core/ext/filters/client_channel/backup_poller.cc#L38

**Comment by yashykt** [comment]
These pollers usually come into play when there are no other threads polling certain fds.

**Comment by durkmurder** [comment]
I am still interested if we are going to get a proper polling mechanism to use the callbacks. I had to implement my own event loop to implement async code since callbacks weren't working at that moment.

**Comment by drfloob** [comment]
> I am still interested if we are going to get a proper polling mechanism to use the callbacks.

Glad to hear it! We just discussed this on Gitter, actually, please join up! To recount it a bit, there are two efforts going on in parallel to support the callback API (neither based on what we call the event manager). One has been in production for about 2 months, called the "callback alternative". The other, called EventEngine, is a replacement for gRPC's I/O layer and it's being prototyped now with timeline for availability (at least experimentally) this year.
