### ISSUE TITLE
C#: Add helper methods to Metadata for fetching values

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#22728]
Metadata is a collection of name/value Entry instances. Typically metadata will contain one entry for a name, but it is possible for there to be multiple entries with the same name.

Today there is no easy way to get a value from Metadata. Developers often write code that looks like this:

```csharp
var trailers = call.GetTrailers();
var myValue = trailers.First(e => e.Key == "my-trailer-name"); // or Single(...)
```

This is inefficient (uses LINQ, allocations `IEnumerable`, maybe allocates a closure over the delegate, delegate invocation, etc) and also not immediately obvious.

Metadata should have `GetValue` helper methods that do this for you.

```csharp
var trailers = call.GetTrailers();
var myValue = trailers.GetValue("my-trailer-name");
var myBinaryValue = trailers.GetValueBinary("my-trailer-name-binary");
```

These would get the value for a given name. If the name is not present then they would return null. If there are multiple entries with that name then an error would be thrown.

If there are multiple values (uncommon case) then Metadata + LINQ can continue to be used.

@jtattermusch

**Comment by jtattermusch** [comment]
We always wanted to add support for getting a value by metadata key (see 35b24e530cc9cd4a26ef005b5ed580f07ba21370) but never got to it.

If you want to contribute the implementation, I'll be happy to review.

Some thoughts about the API:
- one option is using the indexer (which takes a string and returns Metadata.Entry)
- perhaps `GetValue` throwing when there's multiple values seems like a bit of an unexpected behavior unless you explicitly call it e.g. `GetSingleValue`?
- How about having GetSingle(key)  / GetFirst(key) methods that return the Metadata.Entry with given key and handle multiple values accordingly?

- should we have some internal logic (lazily initialized?) that indexes the entries so you don't have to iterate through all of the metadata entries?  What does ASP.NET core do for headers?

**Comment by JamesNK** [comment]
> should we have some internal logic (lazily initialized?) that indexes the entries so you don't have to iterate through all of the metadata entries? What does ASP.NET core do for headers?

There is the concept of "known headers" (e.g. content-type, length, etc) and special code generation that optimizes getting and setting values for them.
