### ISSUE TITLE
Cannot connect to server using SSL via PHP Client

### ISSUE THREAD

**Issue by itsursujit** [grpc/grpc#22727]
I created key<==>crt pair usiing openssl

```
 openssl req -newkey rsa:2048 -nodes -keyout keys/app.key -x509 -days 365 -out keys/app.crt
```
On gRPC Server, I'm using go.
The server is running fine with the key files. And I can connect gRPC server using GRPCUI using insecure mode..

To test thhe client, I copied the crt file to php client and tried to send request to server as follow:
```
<?php

use App\Calculator\CalculatorClient;

require 'vendor/autoload.php';

$client = new CalculatorClient(
    'localhost:50051',
    [
        'credentials' => \Grpc\ChannelCredentials::createSsl(file_get_contents('app.crt')),
    ]
);
$i = 2;
$sum = new \App\Calculator\Sum([
    'a' => $i,
    'b' => $i + 1
]);
[$result, $mt] = $client->Sum($sum)->wait();
var_dump($mt);
```
But I'm getting following error:
`failed to connect to all addresses`

Here i'm using gRPC 1.27 as PHP Extension on Ubuntu 18.04.

What am I missing with PHP Client? Or it's some kind of bug

**Comment by stanley-cheung** [comment]
Not clear what the problem is from the error message, but I was thinking: does your certificate match your actual hostname? In addition to the `credentials` key, which you supplied correctly, you may have to supply the `grpc.ssl_target_name_override` key and provide the hostname that you are trying to connect to.

**Comment by itsursujit** [comment]
How would I put above keys: `grpc.ssl_target_name_override` and the `grpc.default_authority` in PHP as the PHP Client has following parameters

`new Client($host, $options, $channel = null)`

**Comment by stanley-cheung** [comment]
Those would be part of the `$options` parameter:

```
$client = new CalculatorClient(
    'localhost:50051',
    [
        'credentials' => \Grpc\ChannelCredentials::createSsl(file_get_contents('app.crt')),
        'grpc.ssl_target_name_override' => '<your value>',
        'grpc.default_authority' => '<your value>'
    ]
);
```
