### ISSUE TITLE
tools/bazel reports error on Mac

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#22775]
`tools/bazel` script reports the following error when running `tools/bazel build @com_google_protobuf//:protoc`:
```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/tools/bazel-1.0.0-darwin-x86_64: line 1: syntax error near unexpected token `newline'
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/tools/bazel-1.0.0-darwin-x86_64: line 1: `<html>'
```

Sample build log: https://source.cloud.google.com/results/invocations/2854f73d-d668-4eea-a44f-d48e1e5b8336/log

**Comment by jtattermusch** [comment]
To explain the weird error message: I think what happends is that the download of bazel binary fails (and curl stores a HTML document with an error instead) and after that we try to execute that file (which contains garbage).
 
https://github.com/grpc/grpc/blob/ce93ed85bfb70f3c3357402929dd318427bad628/tools/bazel#L66
