### ISSUE TITLE
Asan report

### ISSUE THREAD

**Issue by kalman5** [grpc/grpc#22783]
### What version of gRPC and what language are you using?

GRPC 1.28

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang 11

### What did you do?
Run a unit test with sanitizer enabled 
-fsanitize=address -fsanitize-address-use-after-scope -fsanitize=undefined

### What did you expect to see?
No warning

### What did you see instead?

/usr/local/include/grpcpp/impl/codegen/client_context_impl.h:477:13: runtime error: load of value 64, which is not a valid value for type 'bool'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/local/include/grpcpp/impl/codegen/client_context_impl.h:477:13 in

**Comment by xkszltl** [comment]
This error is from ubsan, not asan.

**Comment by supercoolgreatcoder** [comment]
I am having this issue with ubsan

**Comment by veblush** [comment]
Can you provide the command you run and full error message from ubsan?

**Comment by jayv** [comment]
We're seeing similar errors when linking in a library that's compiled with asan/ubsan  (no sanitizers are enabled on the grpc application that consumes the library)
```
/usr/local/include/grpcpp/impl/codegen/client_context_impl.h:457:13: runtime error: load of value 240, which is not a valid value for type 'bool'
```

**Comment by veblush** [comment]
I suspect that this is because ClientContext is not initialized yet so I need a small repro or your code snippet around ClientContext initialization.

**Comment by gautamtada** [comment]
Hi, @veblush @jayv @kalman5 @yashykt @xkszltl, facing the same issue with gRPC: v1.25.0. Any suggestions how to fix this issue?
