### ISSUE TITLE
pylint_code.sh sanity check failing for several hours

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#22796]
### What version of gRPC and what language are you using?

master, core

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

N/A

### What did you do?

Sent a PR for testing, got failure on pylint_code.sh .  (My PR had no Python code in it)

### What did you expect to see?

Passing sanity tests

### What did you see instead?

It looks like it has been failing for several hours since https://source.cloud.google.com/results/invocations/6fb6d9bb-fdd2-4522-9678-b9393ec1427d/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Fdistrib%2Fpylint_code.sh/tests

**Comment by gnossen** [comment]
Looks like we were pinning the version of our linter, but not the versions of the transitive dependencies. [Astroid pushed a new version 8 hours ago](https://pypi.org/project/astroid/2.4.0/), which appears to be giving a false linter error. https://github.com/grpc/grpc/pull/22798 should resolve.
