### ISSUE TITLE
Get grpc error in tensorflow Java API.

### ISSUE THREAD

**Issue by tywtyw** [grpc/grpc#22790]
### What version of gRPC and what language are you using?
JAVA

### What operating system (Linux, Windows,...) and version?
MacOS

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I run tensorflow java api to load model in flink cluster, it works fine the first time. But When I run the job the second time in cluster, it turns out to be an error like below:
### What did you see instead?
[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/descriptor_database.cc:58] File already exists in database: tensorflow/core/protobuf/eager_service.proto
[libprotobuf FATAL external/protobuf_archive/src/google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Describe the expected behavior

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by a11r** [comment]
Please file a complete issue report. You may need to go to https://github.com/grpc/grpc-java
