### ISSUE TITLE
Python request message to define map type parameter

### ISSUE THREAD

**Issue by Mengjianhua-c** [grpc/grpc#22791]
I defined a request message structure for a service is:

```
message MultiStatsReq {
    message Record {
        int64 origin_id = 1;
        int64 message_id = 2;
    }
    message Business {
        repeated Record records = 1;
    }
    // business and records
    map<string, Business> business = 2;
  
}
```

The data used when constructing the request client to pass parameters is:
`    params = {
        "business": {
            "Hello": {
                "records": [
                    {
                        "origin_id": 20,
                        "message_id": 20
                    }
                ]
            }
        }
    }
byte_params = self.client_pb2.MultiStatsReq(**params)
`
But the error is returned as follows:
`TypeError: Parameter to MergeFrom() must be instance of same class: expected service.MultiStatsReq.Business got dict.
`
How should I pass in the parameters?

**Comment by lidizheng** [comment]
ProtoBuf message is not Python `Dict`. The conversion can be found at https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html. GitHub is the platform for issue tracking, please ask questions in StackOverflow.

**Comment by Mengjianhua-c** [comment]
> ProtoBuf message is not Python `Dict`. The conversion can be found at https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html. GitHub is the platform for issue tracking, please ask questions in StackOverflow.

Thanks, I solved it after referring to the documentation. I will ask questions on StackOverflow later
