### ISSUE TITLE
ObjC example not working

### ISSUE THREAD

**Issue by rvcarlig** [grpc/grpc#22792]
Hello, I tried updating the proto files in my project and I noticed that the application no longer compiles. Upon further inspection, I tried the steps from https://grpc.io/docs/tutorials/basic/objective-c/#protoc and the samples are also not compiling.

### What version of gRPC and what language are you using?
I'm using the latest version of gRPC(1.28.1) for ObjC

### What operating system (Linux, Windows,...) and version?
MacOS 10.15.3 (19D76)

### What did you do?
1) Follow the steps from https://grpc.io/docs/tutorials/basic/objective-c/#protoc
2) Try to run the project

### What did you expect to see?
The application installs.

### What did you see instead?
A lot of errors like:

 'GRPCClient/GRPCTransport.h' file not found

No visible @interface for 'RTGRouteGuide' declares the selector 'initWithHost:callOptions:'
The initializer for the service is like this:
- (instancetype)initWithHost:(NSString *)host NS_DESIGNATED_INITIALIZER;
and it should receive a GRPCCallOptions parameter

The GRPCCallOptions are missing altogether.

Please advise.

**Comment by yulin-liang** [comment]
@rvcarlig I also ran into this problem before. Can you open `HelloWorld.xcworkspace` and check if you have `GRPCCore`, `Interface`, `Interface-Legacy` and `Support Files` directories inside your `Pods/gRPC`directory. If not, try to run `pod update` to install the latest `gRPC-Core` dependency.

**Comment by yulin-liang** [comment]
Closing since we are not hearing response. We can reopen if necessary.
