### ISSUE TITLE
py_proto_library doesn't work with proto imports

### ISSUE THREAD

**Issue by awbraunstein** [grpc/grpc#22811]
### What version of gRPC and what language are you using?
1.28.1

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel, python 3

### What did you do?
I have two protos: `a.proto` and `b.proto` where `a.proto` imports `b.proto`, a python file that imports a.proto and a BUILD file with the following:
```bazel
proto_library(
    name = "a_proto",
    srcs = ["a.proto"],
    deps = [":b.proto"],
)

py_proto_library(
    name = "a_py_pb2",
    deps = ["a_proto"],
)

proto_library(
    name = "b_proto",
    srcs = ["b.proto"],
)

py_proto_library(
    name = "b_py_pb2",
    deps = ["b_proto"],
)

py_binary(
    name = "test",
    srcs = ["test.py"],
    deps = [":a_py_pb2"],
)
```

### What did you expect to see?
I expected that `b_py_pb2` would make it into the runfiles for `test`.

### What did you see instead?
Module not found error from python because `b_py_pb2` didn't make it into the runfiles.

**Comment by daicoden** [comment]
FWIW - I ran into this too and tried to fix it, but there is no way for a_py_proto to figure out that there is a rule named b_py_proto. The best you can do with an aspect is see that a_proto has a dependency on b_proto, and perhaps by naming convention arrive at b_py_proto. But note: when you build :test, b_py_pb2 is not part of the graph, and will not be built.

I think maybe this is why bazel's native py_proto_library takes proto files instead of proto rules.

my solution was to create a :lib which includes a_py_pb2 and b_py_pb2, and then a test which ensures all the deps of lib contains all the py_proto_libraries so when protos are added at least a build 

Would be very interested in what your solution ends up being if you figure out something different.

**Comment by odashi** [comment]
Any updates on this? The @daicoden 's solution would work, but is very weird as we are required to manage every transitive proto dependencies by hand.

**Comment by daicoden** [comment]
For what it's worth, here's my solution. My heuristic is each proto file directory exposes one python lib. All proto files in a directory for python must be included in the lib. Any change to proto files does cause a full build/test of any python dependencies, but you can manage this by breaking into new directories, and the the proto compilation dependency graph is still honored.

```BUILD
genquery(
    name = "common_py_libraries",
    expression = """
      kind(py_library, siblings(//authorization/api/src/main/proto/cfht/authorization:account_service_proto))
      union
      kind(py_library, siblings(//authorization/api/src/main/proto/cfht/common:pagination_proto))
    """,
    scope = [
        "//authorization/api/src/main/proto/cfht/authorization:account_service_proto",
        "//authorization/api/src/main/proto/cfht/common:pagination_proto",
    ],
    deps = [],
)

test_ij_module_has_all_deps(
    name = "py_module_complete_test",
    expected_targets = [
        ":common_py_libraries",
    ],
    rule_to_test = ":py_lib",
)
```

and test_ij_module_has_all_deps

```
def test_ij_module_has_all_deps(name, rule_to_test, expected_targets = [], testonly = False, **kwargs):
    all_deps = "all_{}_deps".format(name)

    native.genquery(
        name = all_deps,
        expression = "deps({})".format("//" + native.package_name() + rule_to_test),
        scope = ["//" + native.package_name() + rule_to_test],
        deps = [],
        testonly = testonly,
    )

    native.py_test(
        name = name,
        args = [
            native.package_name(),
            rule_to_test,
        ] + ["$(location {})".format(target) for target in [all_deps] + expected_targets],
        srcs = ["//rules/intellij:test_module_has_all_deps.py"],
        main = "//rules/intellij:test_module_has_all_deps.py",
        data = [all_deps] + expected_targets,
        size = "small",
        testonly = testonly,
        **kwargs
    )
```

and the python

```
import sys


def test_all_files_included(rule_package, rule_name, target_dependency_file, expected_dependency_files):
    with open(target_dependency_file) as f:
        all_dependencies = set(f.read().splitlines())

    expected_dependencies = set()

    for dep_file in expected_dependency_files:
        with open(dep_file) as f:
            for dep in f.read().splitlines():
                expected_dependencies.add(dep)

    missing_dependencies = expected_dependencies.difference(all_dependencies)
    if len(missing_dependencies) > 0:
        print("FAILED //%s%s is missing dependencies:" % (rule_package, rule_name))
        for missing_dependency in missing_dependencies:
            print("\"%s\"," % missing_dependency)
        print("Please add these dependencies to //%s%s" % (rule_package, rule_name))
        exit(1)


if __name__ == "__main__":
    test_all_files_included(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:])
```

Could be named something else, but built it to solve intellij problems.
