### ISSUE TITLE
Do not install channelz when gRPC_USE_PROTO_LITE

### ISSUE THREAD

**Issue by avalon1610** [grpc/grpc#22826]
#21011 fixed issue that we should not compile channelz when use gRPC_USE_PROTO_LITE, but not for install. 
when gRPC_INSTALL is ON, we got:
`install TARGETS given target "grpcpp_channelz" which does not exist.`

So we need add `AND NOT gRPC_USE_PROTO_LITE` to install part too.

**Comment by tiolan** [comment]
Any news on this?

**Comment by veblush** [comment]
This was fixed by https://github.com/grpc/grpc/pull/25772
