### ISSUE TITLE
Clarification needed for correct use of ClientContext::TryCancel()

### ISSUE THREAD

**Issue by p4654545** [grpc/grpc#22839]
After reading through discussions on Google Groups grpc.io and many open/closed issues here regarding ClientContext::TryCancel() and Finish(), it's still not clear to me how to cancel an RPC call from the client side.

Without cancellation, the sequence would be to read messages until "ok=false" for a Read() operation, then Finish() to get the server status and finally release the any resources associated with the RPC:

- Read(), ok =true
- Read(), ok =true
- Read(), ok =true
- Read(), ok = true
- Read(), ok = false // nothing more to read
- Finish(), ok = true // gets server RPC status
- Delete ClientAsyncReader, ClientContext, ...

Now suppose the client throws an exception while processing the response returned by the second Read() and therefore wants to cancel the RPC. This [message](https://groups.google.com/d/msg/grpc-io/hahFSzQBN4s/dNtJuH4hta0J) on google groups grpc.io says:

> Even when you Cancel at the client, you should continue reading till ClientReader::Read() returns false. Only then is it correct to call ClientReader::Finish().
>The above sequence is required to deal with server to client messages that race with the cancellation.

So the sequence with early termination would be:

- Read(), ok =true
- Read(), ok =true, exception while applying business logic
- ClientContext::TryCancel()
- Read(), ok =true // could happen from what I understand
- Read(),  false = true
- Finish(), ok = true
- Delete ClientAsyncReader and ClientContext

Another [message](https://groups.google.com/d/msg/grpc-io/R0NTqKaHLdE/KVxfG6iIAQAJ) by Vijay Pai says:

> If you want to forcibly shut down the stream, just call a TryCancel on the ClientContext object.

From what I understand Vijay is a real grpc expert, so I am inclined to think that he is correct and therefore the following sequence is valid (if the client is not interested in the server RPC status):

- Read(), ok =true
- Read(), ok =true, exception while applying business logic
- ClientContext::TryCancel()
- Delete ClientAsyncReader and ClientContext

IMHO this seems reasonable, except the client probably has to guarantee there is no uncompleted operation before deleting ClientAsyncReader and ClientContext in the last step.

I can imagine both approaches are valid. Depending on whether the client is interested in the server RPC status, it can choose to do the Read-until-false-then-finish sequence.

Question 1: Is my understanding correct? Am I missing relevant details?

Question 2: Does the same logic apply to the other RPC types?

**Comment by a11r** [comment]
We are discouraging the posing of general questions as issues. Kindly use stackoverflow for this.
