### ISSUE TITLE
Cross compilation for Win ARM64 doesnt happen in one cmake command run. It takes 2 runs.

### ISSUE THREAD

**Issue by NeethJose** [grpc/grpc#22832]
### What version of gRPC and what language are you using?
1.29.0-dev

### What operating system (Linux, Windows,...) and version?
Windows 10 on x64 based PC

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.2
C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.25.28610/
Cmake 3.17 + Ninja 

### What did you do?
Trying to cross compile for ARM64 platform from host x64 Windows platform

### What did you expect to see?
Successfully build ARM64 for grpc binaries + protoc.exe as well. Currently able to see ARM64 grpc binaries getting built. (I am able to get the x64 and x86  binaries built.)
The issue is that if I want a successful cross compilation for ARM64, I need to 
1. Build x64 binaries first
2. Point _gRPC_CPP_PLUGIN, _gRPC_PROTOBUF_PROTOC_EXECUTABLE variables to the x64 version. If I don't do this, CMake+Ninja will complain.
3. Run the cmake command for ARM64 binaries

I expect the the ARM64 binaries to get built successfully without me having to point the cmake to x64 versioned _gRPC_CPP_PLUGIN, _gRPC_PROTOBUF_PROTOC_EXECUTABLE.

### What did you see instead?
If I run an ARM64 build, ARM64 protoc.exe gets built and this causes failure during the cmake command run
Steps to reproduce
-- I added a toochain.cmake file to aid the cross compilation in the grpc\tools\ directory--
toolchain.cmake's contents are as below ->
```
set (CMAKE_SYSTEM_NAME Windows)
set (CMAKE_SYSTEM_PROCESSOR arm64)

set (CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.25.28610/bin/Hostx64/arm64/cl.exe")
set (CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.25.28610/bin/Hostx64/arm64/cl.exe")
```
----End of toolchain.cmake file ----
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat was run with the argument amd64_arm64

I ran the cmake command as given below->
cmake.exe G:\G3\grpc\cdpx\..\.build\.. -GNinja -DgRPC_INSTALL:BOOL=ON -DgRPC_SSL_PROVIDER:STRING=package -DOPENSSL_ROOT_DIR=<Path to ARM64 openssl root dir> -DCMAKE_TOOLCHAIN_FILE="G:\G3\grpc\tools\toolchain.cmake" -DCMAKE_INSTALL_PREFIX:PATH=G:\G3\grpc\cdpx\..\.build\..\..\out\amd64_arm64\release -DCMAKE_BUILD_TYPE=RelWithDebInfo -Wno-dev

Failure log

[1348/1391] Linking C shared library third_party\zlib\zlib.dll
   Creating library third_party\zlib\zlib.lib and object third_party\zlib\zlib.exp
[1372/1391] Running gRPC C++ protocol buffer compiler on src/proto/grpc/reflection/v1alpha/reflection.proto
FAILED: gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h gens/src/proto/grpc/reflection/v1alpha/reflection_mock.grpc.pb.h gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc gens/src/proto/grpc/reflection/v1alpha/reflection.pb.h
cmd.exe /C "cd /D G:\G3\grpc && _gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND --grpc_out=generate_mock_code=true:G:/G3/grpc/.build/gens --cpp_out=G:/G3/grpc/.build/gens --plugin=protoc-gen-grpc=_gRPC_CPP_PLUGIN-NOTFOUND -I . -I G:/G3/grpc/third_party/protobuf/src src/proto/grpc/reflection/v1alpha/reflection.proto"
'_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
operable program or batch file.
[1373/1391] Running gRPC C++ protocol buffer compiler on src/proto/grpc/channelz/channelz.proto
FAILED: gens/src/proto/grpc/channelz/channelz.grpc.pb.cc gens/src/proto/grpc/channelz/channelz.grpc.pb.h gens/src/proto/grpc/channelz/channelz_mock.grpc.pb.h gens/src/proto/grpc/channelz/channelz.pb.cc gens/src/proto/grpc/channelz/channelz.pb.h 
cmd.exe /C "cd /D G:\G3\grpc && **_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND -**-grpc_out=generate_mock_code=true:G:/G3/grpc/.build/gens --cpp_out=G:/G3/grpc/.build/gens --plugin=protoc-gen-grpc=_gRPC_CPP_PLUGIN-NOTFOUND -I . -I G:/G3/grpc/third_party/protobuf/src src/proto/grpc/channelz/channelz.proto"
'**_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND**' is not recognized as an internal or external command,
operable program or batch file.
[1374/1391] Running gRPC C++ protocol buffer compiler on src/proto/grpc/status/status.proto
FAILED: gens/src/proto/grpc/status/status.grpc.pb.cc gens/src/proto/grpc/status/status.grpc.pb.h gens/src/proto/grpc/status/status_mock.grpc.pb.h gens/src/proto/grpc/status/status.pb.cc gens/src/proto/grpc/status/status.pb.h
cmd.exe /C "cd /D G:\G3\grpc && **_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND** --grpc_out=generate_mock_code=true:G:/G3/grpc/.build/gens --cpp_out=G:/G3/grpc/.build/gens --plugin=protoc-gen-grpc=_**gRPC_CPP_PLUGIN-NOTFOUND** -I . -I G:/G3/grpc/third_party/protobuf/src src/proto/grpc/status/status.proto"
'_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
operable program or batch file.
[1376/1391] Linking CXX shared library grpc_csharp_ext.dll
   Creating library grpc_csharp_ext.lib and object grpc_csharp_ext.exp
   Creating library grpc_csharp_ext.lib and object grpc_csharp_ext.exp
ninja: build stopped: subcommand failed.
________________________________________________________________________________________
The errors for can be avoided if I add the following 2 lines to the toolchain.cmake file
set (_gRPC_CPP_PLUGIN "G:/G3/grpc/.build/grpc_cpp_plugin.exe")
set (_gRPC_PROTOBUF_PROTOC_EXECUTABLE "G:/G3/grpc/.build/third_party/protobuf/protoc.exe")

However,as the protoc.exe was made for ARM64 and is being made to run on x64 platform, it throws the following error. -> 

[1342/1391] Linking C shared library third_party\zlib\zlib.dll
   Creating library third_party\zlib\zlib.lib and object third_party\zlib\zlib.exp
[1369/1391] Running gRPC C++ protocol buffer compiler on src/proto/grpc/status/status.proto
FAILED: gens/src/proto/grpc/status/status.grpc.pb.cc gens/src/proto/grpc/status/status.grpc.pb.h gens/src/proto/grpc/status/status_mock.grpc.pb.h gens/src/proto/grpc/status/status.pb.cc gens/src/proto/grpc/status/status.pb.h
cmd.exe /C "cd /D G:\G3\grpc && G:\G3\grpc\.build\third_party\protobuf\protoc.exe --grpc_out=generate_mock_code=true:G:/G3/grpc/.build/gens --cpp_out=G:/G3/grpc/.build/gens --plugin=protoc-gen-grpc=G:/G3/grpc/.build/grpc_cpp_plugin.exe -I . -I G:/G3/grpc/third_party/protobuf/src src/proto/grpc/status/status.proto"
This version of G:\G3\grpc\.build\third_party\protobuf\protoc.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
[1370/1391] Running gRPC C++ protocol buffer compiler on src/proto/grpc/channelz/channelz.proto
FAILED: gens/src/proto/grpc/channelz/channelz.grpc.pb.cc gens/src/proto/grpc/channelz/channelz.grpc.pb.h gens/src/proto/grpc/channelz/channelz_mock.grpc.pb.h gens/src/proto/grpc/channelz/channelz.pb.cc gens/src/proto/grpc/channelz/channelz.pb.h 
cmd.exe /C "cd /D G:\G3\grpc && G:\G3\grpc\.build\third_party\protobuf\protoc.exe --grpc_out=generate_mock_code=true:G:/G3/grpc/.build/gens --cpp_out=G:/G3/grpc/.build/gens --plugin=protoc-gen-grpc=G:/G3/grpc/.build/grpc_cpp_plugin.exe -I . -I G:/G3/grpc/third_party/protobuf/src src/proto/grpc/channelz/channelz.proto"
_This version of G:\G3\grpc\.build\third_party\protobuf\protoc.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher_.
[1371/1391] Running gRPC C++ protocol buffer compiler on src/proto/grpc/reflection/v1alpha/reflection.proto
FAILED: gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h gens/src/proto/grpc/reflection/v1alpha/reflection_mock.grpc.pb.h gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc gens/src/proto/grpc/reflection/v1alpha/reflection.pb.h
cmd.exe /C "cd /D G:\G3\grpc && G:\G3\grpc\.build\third_party\protobuf\protoc.exe --grpc_out=generate_mock_code=true:G:/G3/grpc/.build/gens --cpp_out=G:/G3/grpc/.build/gens --plugin=protoc-gen-grpc=G:/G3/grpc/.build/grpc_cpp_plugin.exe -I . -I G:/G3/grpc/third_party/protobuf/src src/proto/grpc/reflection/v1alpha/reflection.proto"
_This version of G:\G3\grpc\.build\third_party\protobuf\protoc.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher._
[1376/1391] Linking CXX shared library grpc_csharp_ext.dll
   Creating library grpc_csharp_ext.lib and object grpc_csharp_ext.exp
   Creating library grpc_csharp_ext.lib and object grpc_csharp_ext.exp
ninja: build stopped: subcommand failed.

____________________________________________________________________________________
The build succeeds only if I make the x64 binaries first and then set the the following in the toolchain.cmake file (paths to the x64 binaries)
```
set (_gRPC_CPP_PLUGIN "G:/G3/out/x64/release/bin/grpc_cpp_plugin.exe")
set (_gRPC_PROTOBUF_PROTOC_EXECUTABLE "G:/G3/out/x64/release/bin/protoc.exe")
```

### Request
I was wondering if we could find the reason why x64 protoc is not getting made automatically during arm64 cross compilation as the CMAKE_CROSSCOMPILING should ideally get set.

**Comment by LightSun** [comment]
I met the similar error. build android on win10 platform.
```
[ 86%] Running gRPC C++ protocol buffer compiler on src/proto/grpc/reflection/v1alpha/reflection.proto
'_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
make.exe[2]: *** [gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Error 1
make.exe[1]: *** [CMakeFiles/grpc++_reflection.dir/all] Error 2
make.exe: *** [all] Error 2
[  1%] Built target zlibstatic
[  1%] Built target absl_spinlock_wait
[  2%] Built target upb
[  2%] Built target absl_int128
[  2%] Built target absl_log_severity
[  2%] Built target absl_raw_logging_internal
[  2%] Built target absl_base
[  3%] Built target absl_throw_delegate
[  3%] Built target absl_demangle_internal
[  3%] Built target absl_debugging_internal
[  3%] Built target absl_time_zone
[  3%] Built target absl_civil_time
[  3%] Built target absl_bad_optional_access
[  3%] Built target absl_strings_internal
[  4%] Built target absl_strings
[  4%] Built target absl_time
[  5%] Built target absl_str_format_internal
[  6%] Built target absl_cord
[  6%] Built target absl_malloc_internal
[  6%] Built target absl_symbolize
[  6%] Built target absl_stacktrace
[  6%] Built target absl_status
[  7%] Built target absl_graphcycles_internal
[  7%] Built target absl_synchronization
[ 10%] Built target gpr
[ 10%] Built target address_sorting
[ 10%] Built target absl_wyhash
[ 10%] Built target absl_city
[ 10%] Built target absl_bad_variant_access
[ 10%] Built target absl_hash
[ 10%] Built target absl_exponential_biased
[ 13%] Built target c-ares
[ 14%] Built target re2
[ 14%] Built target absl_statusor
[ 14%] Built target absl_hashtablez_sampler
[ 14%] Built target absl_raw_hash_set
[ 29%] Built target grpc_unsecure
[ 33%] Built target libprotobuf
[ 35%] Built target grpc++_unsecure
[ 39%] Built target libprotoc
[ 39%] Built target grpc_plugin_support
[ 39%] Built target grpc_ruby_plugin
[ 41%] Built target ssl
[ 54%] Built target crypto
[ 83%] Built target grpc
[ 83%] Built target grpc_csharp_ext
[ 85%] Built target grpc++
[ 85%] Built target grpc++_alts
[ 86%] Built target grpc++_error_details
[ 86%] Built target grpc_cpp_plugin
[ 86%] Built target protoc
[ 86%] Running gRPC C++ protocol buffer compiler on src/proto/grpc/reflection/v1alpha/reflection.proto
'_gRPC_PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
make.exe[2]: *** [gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Error 1
make.exe[1]: *** [CMakeFiles/grpc++_reflection.dir/all] Error 2
make.exe: *** [all] Error 2
请按任意键继续. . .
```

**Comment by jtattermusch** [comment]
I think this is working as expected. If you're crosscompiling, you need to:
1. first build the protoc.exe and the codegen plugins to target x64.
2. make the binaries available on PATH (or make them discoverable by cmake's `find_program(_gRPC_CPP_PLUGIN grpc_cpp_plugin)` in some other fashion - e.g. the trick you used) `https://github.com/grpc/grpc/blob/0e20a5fce8e53510255fa1a5199544a86ebfcd8e/CMakeLists.txt#L311
3. run the grpc cmake build with the ARM64 crosscompilation options.

I agree that having everything work out of the box would be nice, but it would be a significant investment to make things work that way (and test it accordingly to make sure it stays that way) and given that the current way of crosscompiling works well (as you basically discovered yourself) and only includes 2 more commands, this really isn't a priority.

**Comment by LightSun** [comment]
@jtattermusch also error.
```
F:/cpp_builds/grpc_1.38.0_x86_install/bin/grpc_cpp_plugin.exe: Unknown option: --grpc_out=generate_mock_code=true:F:/cpp_builds/grpc_1.38.0_x86/grpc/build-android-armv7/gens
make.exe[2]: *** [gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Error 1
make.exe[1]: *** [CMakeFiles/grpc++_reflection.dir/all] Error 2
make.exe: *** [all] Error 2
```
