### ISSUE TITLE
grpc 1.28.1 shows Assertion failed: (t->alloc == a), function upb_check_alloc, file /wrkdirs/usr/ports/devel/grpc/work/grpc-1.28.1/third_party/upb/upb/table.c, line 22. (grpc 1.22 works)

### ISSUE THREAD

**Issue by mfechner** [grpc/grpc#22845]
I'm the port maintainer for Gitlab in FreeBSD and we try to upgrade grpc from 1.22 (which works) to 1.28.1 (which fails).
The upgrade of grpc seems to be necessary as the used rubygem grpc version 1.27 seems to require a newer gRPC and does not work with gRPC 1.22 anymore.

### What version of gRPC and what language are you using?
We currently test gRPC 1.28.1 together with rubygem grpc version 1.24 and 1.27.

gRPC 1.22 works, 1.28.1 fails with Gitlab. It seems it started to break with something after 1.22.1, I tested 1.24 and it has the same problem.

There is a report existing which documents that 1.24.1 has the same problem:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241754

### What operating system (Linux, Windows,...) and version?
FreeBSD 12.1.

### What runtime / compiler are you using (e.g. python version or version of gcc)
The gRPC port is build using the ports in FreeBSD, a full build log can be found here (here you can find everything):
https://pkg.fechner.net/data/121amd64-gitlab/2020-05-02_08h10m52s/logs/grpc-1.28.1,2.log

Some patches are applied to gRPC for FreeBSD, you can find them here:
https://gitlab.fechner.net/mfechner/Gitlab/-/tree/master/devel%2Fgrpc%2Ffiles

### What did you do?
I tested the Gitlab migration by running the gitlab specific command:
`su -l git -c "cd /usr/local/www/gitlab-ce && rake db:migrate RAILS_ENV=production"`

### What did you expect to see?
The process should run through without errors.

### What did you see instead?
`Assertion failed: (t->alloc == a), function upb_check_alloc, file /wrkdirs/usr/ports/devel/grpc/work/grpc-1.28.1/third_party/upb/upb/table.c, line 22.
`

### Anything else we should know about your project / environment?
We tried also to patch these assert commands out, but it fails toom so it seems that after version 1.22 something was changed that breaks gRPC for FreeBSD or at least with the way it is build/used with FreeBSD.

I will send the link to this issue to the gRPC maintainer, so he can give you more details about how the port is build and why.

**Comment by a11r** [comment]
Thank you for filing a complete report. Unfortunately , FreeBSD is not among the list of platforms here (https://grpc.io/about/#officially-supported-languages-and-platforms) so we will move this to Help Wanted label.

**Comment by markdroth** [comment]
Josh, this looks like it may be a upb issue.

**Comment by mfechner** [comment]
Is there anything we can help?

**Comment by mfechner** [comment]
What can we do here?
I really would like to have a newer grpc version rolled out on FreeBSD.

**Comment by haberman** [comment]
Is there any way of getting a stack trace? That would really help narrow down what is going on here.

Also is there a relatively easy way of reproducing this in a VM?

**Comment by mfechner** [comment]
I can try to setup an vagrant script using virtualbox with ansible.
If these tools are available on the system you want to test it.

Please let me know if that would be visible, then I try to prepare there something were I can reproduce the problem using gitlab.

If that is visible let me see what I can provide.

**Comment by haberman** [comment]
I'm not too familiar with these tools, but it looks like they are all available for Ubuntu. If you can post a repro I will try to see if I can reproduce it.

**Comment by mfechner** [comment]
Great, we will prepare something, I will let you know if it is ready.

**Comment by mfechner** [comment]
It seems that the problem is fixed with grpc 1.34.0:
https://reviews.freebsd.org/D27752

I will close the issue, thanks a lot!
