### ISSUE TITLE
add RDMA as one transport layer inside gRPC

### ISSUE THREAD

**Issue by gwnet** [grpc/grpc#22846]
### Additional context
Add any other context about the feature request here.

**Comment by a11r** [comment]
This is a substantial feature request. We would be open to contributions here.

**Comment by dmadisetti** [comment]
Tensorflow contrib allows for fancier network protocols than TCP and is migrating to [Tensorflow networking](https://github.com/tensorflow/networking) which allows for `grpc+verb` as [per this comment](https://github.com/tensorflow/tensorflow/issues/2916#issuecomment-455725989)

I'm not sure if this would be a good starting point, as I don't know how much they've deviated from gRPC/ made it particular to tensors

**Comment by gwnet** [comment]
Yes, I also noticed Tensorflow RDMA gRPC solution. it is not general.

**Comment by zhucan** [comment]
> not general.

Next steps is?

**Comment by jiwq** [comment]
@a11r As we know the TensorFlow Networking is not the general solution, and whether had any plan to implement a new solution?
