### ISSUE TITLE
pip install grpc is throwing error

### ISSUE THREAD

**Issue by gkiran292** [grpc/grpc#22849]
### What version of gRPC and what language are you using?
gRPC==0.3-19
language ==python

### What operating system (Linux, Windows,...) and version?
Mac OS (venv environment)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.7

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
pip install -r requirements.txt

Contents of requirements.txt
```
google
protobuf
google-api-python-client
googleapis-common-protos
grpcio
requests
grpc
```

### What did you expect to see?
grpc being installed

### What did you see instead?
```
ERROR: Command errored out with exit status 1:
     command: /Users/gkiran/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-install-lo2c4bul/grpc/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-install-lo2c4bul/grpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-pip-egg-info-msn_fngb
         cwd: /private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-install-lo2c4bul/grpc/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-install-lo2c4bul/grpc/setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "/private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-install-lo2c4bul/grpc/grpc/__init__.py", line 6, in <module>
        from .rpc import *
      File "/private/var/folders/5v/gb09btt1621g_l5nvjnb26v00000gn/T/pip-install-lo2c4bul/grpc/grpc/rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I used venv environment

**Comment by rgrishigajra** [comment]
The issue seems to be fixed when installing grpcio instead of grpc, which was a different package altogether. I suppose we don't need the pip package grpc ?

**Comment by lidizheng** [comment]
Unfortunately, the official package for gRPC Python is named `grpcio` instead of `grpc`.

```
pip install grpcio
```

**Comment by knuesel** [comment]
Now that the ownership of the `grpc` package has been transferred to Google (see https://github.com/pypa/pypi-support/issues/3 ), this looks like an issue that could be fixed by the gRPC team. Maybe it should be reopened?

**Comment by safee60** [comment]
> package has been transferred to Google (see [pypa/pypi-support#3](https://github.com/pypa/pypi-support/issues/3) ), this looks like an issue that could be fixed by the gR



> Unfortunately, the official package for gRPC Python is named `grpcio` instead of `grpc`.
> 
> ```
> pip install grpcio
> ```

**Comment by safee60** [comment]
> Unfortunately, the official package for gRPC Python is named `grpcio` instead of `grpc`.
> 
> ```
> pip install grpcio
> ```
