### ISSUE TITLE
php fpm, grpc api  timeout for a few minutes when php file replacement does not interrupt the program

### ISSUE THREAD

**Issue by codeMingo** [grpc/grpc#22850]
### What version of gRPC and what language are you using?
1.28

### What operating system (Linux, Windows,...) and version?
linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
phpex

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
not timeout

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by stanley-cheung** [comment]
@codeMingo Can you provide more information on this? What does "php file replacement does not interrupt the program" mean?
