### ISSUE TITLE
libgrpc.so.9 exists but is not found at runtime

### ISSUE THREAD

**Issue by gabroo** [grpc/grpc#22861]
### What version of gRPC and what language are you using?

gRPC v1.28.1 with C++17

### What operating system (Linux, Windows,...) and version?

Vagrant VM with the ubuntu/bionic64 box

### What runtime / compiler are you using (e.g. python version or version of gcc)

GNU 7.5.0

### What did you do?

1.  Installed gRPC in the provision step of Vagrant file with the following code, using cmake v3.17.2:

```
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc ~/grpc
cd ~/grpc
git submodule update --init
mkdir -p cmake/build
cd cmake/build
cmake -DgRPC_INSTALL=ON -DBUILD_SHARED_LIBS=ON ../..
make
make install
```

2.  Use the CMakeLists.txt example to find packages:

```
# Find Protobuf installation
# Looks for protobuf-config.cmake file installed by Protobuf's cmake installation.
set(protobuf_MODULE_COMPATIBLE TRUE)
find_package(Protobuf CONFIG REQUIRED)
message(STATUS "Using protobuf ${protobuf_VERSION}")

set(_PROTOBUF_LIBPROTOBUF protobuf::libprotobuf)
set(_REFLECTION gRPC::grpc++_reflection)
if(CMAKE_CROSSCOMPILING)
  find_program(_PROTOBUF_PROTOC protoc)
else()
  set(_PROTOBUF_PROTOC $<TARGET_FILE:protobuf::protoc>)
endif()

# Find gRPC installation
# Looks for gRPCConfig.cmake file installed by gRPC's cmake installation.
find_package(gRPC CONFIG REQUIRED)
message(STATUS "Using gRPC ${gRPC_VERSION}")

set(_GRPC_GRPCPP gRPC::grpc++)
if(CMAKE_CROSSCOMPILING)
  find_program(_GRPC_CPP_PLUGIN_EXECUTABLE grpc_cpp_plugin)
else()
  set(_GRPC_CPP_PLUGIN_EXECUTABLE $<TARGET_FILE:gRPC::grpc_cpp_plugin>)
endif()
```

3. Build the server:

```
add_executable(func_server ${SRV_HDRS} ${SRV_SRCS})
target_link_libraries(func_server 
    PUBLIC
    glog::glog
    ${_REFLECTION}
    ${_GRPC_GRPCPP} 
    ${_PROTOBUF_LIBPROTOBUF})
```

### What did you expect to see?

A working executable.

### What did you see instead?

The compilation is entirely successful, however, at runtime, the gRPC shared libraries cannot be found:

<img width="414" alt="ss 2020-05-04 at 12 55 58 AM" src="https://user-images.githubusercontent.com/6046841/81024996-10cf1980-8e2a-11ea-80fd-9880d7b6669e.png">

However, when I search for it it appears here. If I set LD_LIBRARY_PATH to this folder and run the executable it works as expected. But I'm not sure why the directory is not already being searched for at runtime.
 
<img width="731" alt="ss 2020-05-04 at 4 57 25 PM" src="https://user-images.githubusercontent.com/6046841/81024979-0745b180-8e2a-11ea-8355-e7420b431835.png">

**Comment by markdroth** [comment]
This looks like a problem with your system setup.  You are installing the library into a location where your system is not looking for them.

If you need more help with this, I suggest posting on the grpc.io mailing list.

Good luck!
