### ISSUE TITLE
Python server call gets stuck yielding in cancelled streaming responses

### ISSUE THREAD

**Issue by nikiask** [grpc/grpc#22874]
### What version of gRPC and what language are you using?
grpcio==1.28.1
grpcio-tools==1.28.1

Python 3.6.9

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04 LTS

### What did you do?
https://github.com/nikiask/grpc-repro

### What did you expect to see?
Server RPC call exiting after client call exits

### What did you see instead?
Server call stuck trying to yield

Someone pointed this out in #11157 as well.

**Comment by gnossen** [comment]
@nikiask Thanks for the nice repro case! We may want to firm up our semantics here, but at the moment, **yielding a response message after the client has cancelled will block indefinitely**, as you have noticed. We might want to consider a different behavior in this case, like raising an exception in the handler instead. This at least would free up the thread in the server's thread pool.

However, `is_active()` is not how we recommend that you deal with client cancellation. Take a look at our cancellation example: https://github.com/grpc/grpc/blob/9993d2b9a421a0b27b604c52fa93260fe0638b12/examples/python/cancellation/server.py#L50

**Comment by gnossen** [comment]
@nikiask Please let me know if this answer satisfies you.

**Comment by nikiask** [comment]
@gnossen thank you for your advice. grpc does in fact exit the call, I put a try / finally in my [repro example.py code](https://github.com/nikiask/grpc-repro/blob/f1650ce887d1275f9ce368f8091a732e481c673e/example.py) and the print statement in the finally gets run. I incorrectly assumed that it would consume the next message in the generator causing the statement after the yield to get run.
What it actually does is throw an exception in the generator? I tried adding an except clause but it caught nothing.
