### ISSUE TITLE
How to monitor the time of sending message?

### ISSUE THREAD

**Issue by hobbitlzy** [grpc/grpc#22872]
I am trying to figure out the relationship between the message size and the transmission time. So I need to know the time of sending a message from client device to server device. My program is python. Does anyone know how can I record the elapsed time of sending a message?

I have tried to use the time.time() to record the elapsed time. But the problem is I am not sure where should I put this sentence, because some messages will be written into the buffer and I cannot know when are they written in. And I have found the value of time.time() is not synchronous on different machines. So, I think this method does not work...

**Comment by stanley-cheung** [comment]
Please direct general question like this one to https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
