### ISSUE TITLE
Grpc.Tools: Please add documentation for AdditionalImportDirs directive for .csproj build integration

### ISSUE THREAD

**Issue by koliyo** [grpc/grpc#22878]
### What version of gRPC and what language are you using?
1.28.1, C#

### What operating system (Linux, Windows,...) and version?
Mac, Linux, Windows

### What did you do?
I tried to set up a .NET project with multiple gprc directories including each other. But when looking at the documentation in https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md

I could not find a way of using multiple directories, so I set up a pipeline where I copy all proto files to a common root directory, which I then set using `ProtoRoot` in the `csproj`.

But after looking at the grpc .NET source code I found the `AdditionalImportDirs` declaration!

If I hade seen this earlier in the documentation it would have saved me some hours of workarounds.

### What did you expect to see?
I expected `AdditionalImportDirs` to be documented. It is a very useful feature!

### What did you see instead?
Could not find it anywhere. The only occurance is this one line in the source file `Google.Protobuf.Tools.targets`

```
      ProtoPath="%(_Protobuf_OutOfDateProto.AdditionalImportDirs);$(Protobuf_StandardImportsPath);%(_Protobuf_OutOfDateProto.ProtoRoot)"
```

**Comment by Cephei** [comment]
@koliyo thank you for pointing this out! I've no idea anyone with large scale projects does without this. ProtoRoot was driving me crazy and I kept running into problems that `AdditionalImportDirs` solved completely.

**Comment by jtattermusch** [comment]
@Cephei  @koliyo  Feel free to create a PR that adds the documentation.

**Comment by jtattermusch** [comment]
> @Cephei @koliyo Feel free to create a PR that adds the documentation.

Perhaps we could add an item here? https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#protobuf-item-metadata-reference

**Comment by jtattermusch** [comment]
FTR https://github.com/grpc/grpc/blob/163fcfa0f32769e690eb6e33749c5bda2ba08161/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L268

**Comment by juwens** [comment]
Apperently you cannot use "AdditionalImportDirs" as Attribute of Protobuf anymore in 2.37.1

# The following did not work
```
<ItemGroup>
    <Protobuf Include="**/*.proto" ProtoRoot="." AdditionalImportDirs="PathWithProtoFiles" />
<ItemGroup>   
```

# What did work though
### Solution A
```
<ItemGroup>
    <Protobuf Include="**/*.proto" ProtoRoot="." AdditionalProtocArguments="--proto_path=$(MSBuildProjectDirectory)\PathWithProtoFiles" />
<ItemGroup>   
```

### Solution B
```
<PropertyGroup>
 
 
 
 
 <Protobuf_StandardImportsPath>$(Protobuf_StandardImportsPath);$(MSBuildProjectDirectory)\PathWithProtoFiles</Protobuf_StandardImportsPath>

</PropertyGroup>
<ItemGroup>
    <Protobuf Include="**/*.proto" ProtoRoot="." AdditionalProtocArguments="--proto_path=$(MSBuildProjectDirectory)\PathWithProtoFiles" />
<ItemGroup>   
```

**Comment by jtattermusch** [comment]
@juwens  what are the situations in which "AdditionalImportDirs" didnt'

> Using "AdditionalImportDirs" as Attribute of Protobuf didn't work for me in some scenarios with 2.37.1
> 
> # That works for some scenarios
> ```
> <ItemGroup>
>     <Protobuf Include="**/*.proto" ProtoRoot="." AdditionalImportDirs="PathWithProtoFiles" />
> <ItemGroup>   
> ```

Can you share the exact scenarios where using the `AdditionalImportDirs` didn't work?
I think it would be useful FTR.

> 
> # What did work everytime:
> ### Solution A
> ```
> <ItemGroup>
>     <Protobuf Include="**/*.proto" ProtoRoot="." AdditionalProtocArguments="--proto_path=$(MSBuildProjectDirectory)\PathWithProtoFiles" />
> <ItemGroup>   
> ```
> 
> ### Solution B
> ```
> <PropertyGroup>
>     <Protobuf_StandardImportsPath>$(Protobuf_StandardImportsPath);$(MSBuildProjectDirectory)\PathWithProtoFiles</Protobuf_StandardImportsPath>
> </PropertyGroup>
> <ItemGroup>
>     <Protobuf Include="**/*.proto" ProtoRoot="."  />
> <ItemGroup>   
> ```

**Comment by adeal** [comment]
The best documentation I've found is at:

https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md.

**Comment by tonydnewell** [comment]
I've created a PR for updating the documentation: https://github.com/grpc/grpc/pull/30405

The example I have working has one proto file inside the project (`Protos/greet.proto`) that includes a proto file `message.proto` outside the project (in `E:\work\grpc\issues\multiprotos\ouside-project\`):

```proto
syntax = "proto3";

// this is imported from outside of the project
import "messages.proto";

option csharp_namespace = "GrpcGreeter";

package Greet;

service Greeter {
  rpc SayHello (Greet.HelloXXXRequest) returns (Greet.HelloXXXReply);
}
```

the project file has:

```XML
  <PropertyGroup>
    <MyOutsideProtos>E:\work\grpc\issues\multiprotos\ouside-project\</MyOutsideProtos>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos/greet.proto" GrpcServices="both" ProtoRoot="Protos"
              AdditionalImportDirs="$(MyOutsideProtos)" />
    <Protobuf Include="$(MyOutsideProtos)*.proto" GrpcServices="none" AdditionalImportDirs="$(MyOutsideProtos)" />
  </ItemGroup>
```

**Comment by tonydnewell** [comment]
Document changes (https://github.com/grpc/grpc/pull/30405) have now been merged into master
