### ISSUE TITLE
plumb subchannel connection failure status up to LB policy

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22885]
In keeping with #22883, we should change the `SubchannelInterface` API such that it returns subchannel connection failure information (probably in the form of `absl::Status`) up to the LB policy to be included in error messages.  We will also need to make sure that failures from the security connector are reported appropriately.

See related questions from users in https://groups.google.com/g/grpc-io/c/zVZNM8KYMbs.

**Comment by connect2satz** [comment]
Hi Mark,  Currently i am using grpc with secure channel (tls 1.3). if severe fails to validate client certificate(client's certificate: x509: certificate signed by unknown authority), client is getting grpc error code 2 with description "stream removed".

**Comment by markdroth** [comment]
Yes, that's a good example of what this issue is talking about.  Once we can plumb the specific connection failure information up from the subchannel to the LB policy, the LB policy can include this information in its error messages.

**Comment by connect2satz** [comment]
Here "stream removed" doesn't give enough information about what happened in the server side. is there a way to propagate ssl error description back to grpc status till you fix this?

**Comment by markdroth** [comment]
No.  Propagating the error into the status messages is exactly what this bug is about.

**Comment by connect2satz** [comment]
Hi Mark,
when can we expect the fix for this issue ?

**Comment by markdroth** [comment]
This was actually fixed recently in #23480.

That having been said, note that this is an internal-only change at this point, since our LB policy API is not yet public.  There's some more work to do in the context of #22883 to actually plumb this information into RPC failure status messages.  The fix to that issue is what will make the error statuses more useful.
