### ISSUE TITLE
msbuild cannot find protoc.exe

### ISSUE THREAD

**Issue by chinadragon0515** [grpc/grpc#22880]
I have simple .NET SDK project with a simple proto file,, the project is like 

_

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <Protobuf Include="hello.proto" />
  </ItemGroup>
</Project>
```

_

And my msbuild vesion is 16.5.0.12403

When I run msbuild of the project, I will get error 
[INFO] [1456] C:\NuGetPackages\grpc.tools\2.28.0\build\_protobuf\Google.Protobuf.Tools.targets(264,5): error MSB6004: The specified task executable location "\windows_x86\protoc.exe" is invalid. [C:\source\GrpcContract.csproj]

Seems the build cannot include the generate properties file GrpcContract\obj\GrpcContract.csproj.nuget.g.props which imports grpc.tools\2.28.0\build\Grpc.Tools.props

/cc @kkm000

**Comment by markdroth** [comment]
This forum is for bugs and feature requests only.  For questions, please post to one of the following forums:

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
