### ISSUE TITLE
is it possible to use my error code in grpc with python client and golang server?

### ISSUE THREAD

**Issue by Creek-Shi** [grpc/grpc#22881]
// grpc server with golang
func (p *HelloService) Hello(ctx context.Context, args *pb.String,) (*pb.String, error) {
    return nil, status.Error(codes.Code(100), "hello failed") // 100 is the error code of my own
}

// grpc client with python
try:
    stub = test_pb2_grpc.HelloServiceStub(channel)
    response = stub.Hello(test_pb2.SayHello())
except grpc.RpcError as rpc_error:
    print(rpc_error.details()) 				// print  Server sent unknown code None and details "hello failed"
    status = rpc_status.from_call(rpc_error)
    print(status) 							// print none
    status_code = rpc_error.code()
    print(status_code) 						// print StatusCode.UNKNOWN

The problem is: how can i get 100 in my python grpc client ?

**Comment by stanley-cheung** [comment]
Please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
