### ISSUE TITLE
Looks for roots.pem in /usr/local when grpc was installed in /opt/local

### ISSUE THREAD

**Issue by siddharthab** [grpc/grpc#2288]
This is on Mac OS 10.10.3 with grpc installed in /opt/local.

While using JWT creds, my client complains that roots.pem file can not be found:
```
E0701 17:02:01.209390000 140735188198144 file.c:81] Could not open file /usr/local/share/grpc/roots.pem (error = No such file or directory).
E0701 17:02:01.210179000 140735188198144 security_connector.c:569] Could not get default pem root certs.
```

Symlinking the file from /opt/local made the issue go away.

**Comment by nicolasnoble** [comment]
You need to make sure you're building and installing grpc with the same options. Since I guess you did a `sudo make install prefix=/opt/local`, you should've done a `make prefix=/opt/local` too.

**Comment by siddharthab** [comment]
Ah I see. I was tripped by the install instructions at https://github.com/grpc/grpc/blob/master/INSTALL#L30

Your suggestion or skipping the `make all` step entirely removes this problem.
