### ISSUE TITLE
Use absl::Status and absl::StatusCode

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc#22890]
Are there any plans to move from grpc++ own types to `absl::Status` and `absl::StatusCode`?

It looks like grpc's vendored version of absl does already have them.

**Comment by markdroth** [comment]
Esun and Yang, please advise.

**Comment by yang-g** [comment]
Esun would be the better person about the plan. From my perspective, absl::Status was designed with gRPC team's involvement about gRPC's requirement and there is general agreement that we will use one Status type in the future. However, I am not sure it is possible to do so now without breaking the existing grpc::Status users. Also we currently do not expose any absl types in C++ API layer. Thus I feel like this can be something with several steps and the API change may happen when we have 2.0.

**Comment by gravypod** [comment]
@yang-g, would it be possible to produce implicit constructors to turn absl::Status into grpc::Status for results?

**Comment by tamama** [comment]
@yang-g @veblush @gravypod  Or... maybe 
```
struct grpc::Status : absl::Status { ... };
```
^ this would be a dream-come-true ...
