### ISSUE TITLE
Hash of hash is not supported, ArgumentError: Unknown field name 'bar' in initialization map entry.

### ISSUE THREAD

**Issue by anjali-globallogic** [grpc/grpc#22904]
grpc gem version "1.28.0", Language Ruby: 2.5.0
Gem Dependencies
"google-protobuf", "~> 3.11",
googleapis-common-protos-types "~> 1.0"

Platform : Ubuntu-18.04.4 LTS
@cpu="x86_64", @os="linux"

I am implementing a client in Ruby. While passing parameters to server call, I am encountering this issue. Ruby Hash of Hash is not supported by grpc, it's giving
 `ArgumentError: Unknown field name 'bar' in initialization map entry.`

 In my service_pb.rb file I have:
```
add_message 'request' do
  ...
  optional :test, :message, 12, 'google.protobuf.Struct'
end
```
Now I am trying to pass the request params in my client.rb:
```
params = {xyz: "abc", test: { bar: "296" }}
stub = Message::Stub.new('localhost:9999', :this_channel_is_insecure)
msg = Request.new(params)
```

while running this I am getting: `ArgumentError: Unknown field name 'bar' in initialization map entry.`

It should not ask for keys to be present in map entry since keys are dynamic data.

**Comment by apolcyn** [comment]
I think this is a question about the ruby-protobuf API, more than gRPC, so this seems like a question for https://github.com/protocolbuffers/protobuf/tree/master/ruby or for the protobuf support forum: https://developers.google.com/protocol-buffers/docs/faq. Please ask this question in one of those places, thanks.

**Comment by chenwnicole** [comment]
[This](https://stackoverflow.com/a/61772109) is helpful if anyone comes across the same issue (use `Google::Protobuf::Struct.from_hash`).
