### ISSUE TITLE
Headers not being passed from Server to Client using BlockingUnaryCall

### ISSUE THREAD

**Issue by cameronharp** [grpc/grpc#22909]
### What version of gRPC and what language are you using?
**Version**: 2.28.1
**Language**: C#

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Core 3.1/NETCOREAPP3.1

### What did you do?
**Sync**
1.) On the server set any header value on the context
2.) On the client read that header value in the BlockingUnaryCall it will not exist.

Below is our TestInterceptor where we have been testing everything with. But this can be tested using a simple HelloWorld base applications.

![image](https://user-images.githubusercontent.com/1463002/81456136-8b5fa800-914e-11ea-8cde-f517777a7e3a.png)

**Async**
1.) On the server set any header value on the context
2.) On the client in the AsyncUnaryCall the header values exist

Async works as expected.

### What did you expect to see?
Header values when running sync(blocking). I would expect async and sync calls to be able to do the same functionality.

### What did you see instead?
Instead we are not able to get the desired behavior via sync as we can async. Not all our products are converted over to use async so we need it to work in both ways.

**Comment by jtattermusch** [comment]
I can reopen if more details are provided.
