### ISSUE TITLE
Unmanaged memory not released after message exchanged

### ISSUE THREAD

**Issue by kanekotic** [grpc/grpc#2292]
Profiling my C# application I have come across that the unmanaged memory, is increasing quite rapidly starting on the moment that messages are exchanged between client and server application (please find the next snapshots that explain the behaviour in memory)

1. Server initial state (no messages) :
![server_1](https://cloud.githubusercontent.com/assets/3071208/8477281/361cc670-20c9-11e5-8de3-9b3ca54821d7.PNG)

2. Server starting exchange of messages:
![server_2](https://cloud.githubusercontent.com/assets/3071208/8477327/811ceda8-20c9-11e5-9eb0-6cbf775a5ea3.PNG)

3. continuous exchanged of messages:
![server_3](https://cloud.githubusercontent.com/assets/3071208/8477344/a59b4e7c-20c9-11e5-95ad-97fb271e24d0.PNG)

4. after client app kill or crash:
![server_4](https://cloud.githubusercontent.com/assets/3071208/8477347/b1adead0-20c9-11e5-8143-545644fc42df.PNG)

The output is that betweent 4 and 8 minutes of continous exchange of messages there is a c++exception (shon on C# by Grpc.Core.RpcException {"Status(StatusCode=Unavailable, Detail=\"\")"}. 

I've check if I was doing something strange, but with or without opening a new channel per message the behaviour is the same. As per my understanding there is non other IDisposable element that could be cleared.

**Comment by kanekotic** [comment]
any update?...this is for me a critical bug? it crashes an app in less than 10 min (and i am just trying with one string + int32). Let me know because if its not going to be solved i will need to use another RPC.

**Comment by jtattermusch** [comment]
Hi, thanks for reporting this and sorry for the delay.

We've recently fixed a memory leak that could be causing this (see https://github.com/grpc/grpc/pull/2125 for more details). Also, gRPC C# nuget packages version 0.6.0 have been released earlier today, and they contain the bugfix. Please upgrade gRPC nuget packages to 0.6 and check if you are still seeing the issue.

**Comment by kanekotic** [comment]
jtattermusch thanks for your reply :+1:

I will update my nuget package and give it a try. I will get back to you to confirm if its solved, and any new finding

**Comment by kanekotic** [comment]
:+1: 

seems solved here are some screenshots on how memory behaves now:

Server side:
![memorysnapshotserver](https://cloud.githubusercontent.com/assets/3071208/8698536/6b70cc3c-2aff-11e5-8295-2e9289ab7b15.PNG)

client side:
![memorysnapshotclient](https://cloud.githubusercontent.com/assets/3071208/8698540/72cfe8fa-2aff-11e5-87eb-2eb7212a73ab.PNG)

 great job :+1:
