### ISSUE TITLE
Cmake template doesn't support header-only libraries in the cmakefile

### ISSUE THREAD

**Issue by nanahpang** [grpc/grpc#22937]
### Is your feature request related to a problem? Please describe.

Issue #20208 needs to install header-only libraries "/grpcpp/test/mock_stream.h" and the fixed PR is in pull request #20369. But header-only libraries is not supported in the cmake template.

**Comment by jtattermusch** [comment]
@nanahpang  is this still a problem? What exactly is the desired solution?

**Comment by nanahpang** [comment]
Yes, the problem is that we can't declare a header-only library in cmake files, it shows error "No SOURCES given to target: grpc++_test": https://github.com/grpc/grpc/pull/20369#issuecomment-548975485. 
Because some users want to use "/grpcpp/test/mock_stream.h", which is a test library with only header files, we are looking for support of adding header-only library into the cmake template, and then merge pull request #20369 again. Thanks!

**Comment by jtattermusch** [comment]
@vjpai has mentioned that this article might have a solution to the header-only library problem: http://mariobadr.com/creating-a-header-only-library-with-cmake.html . The magic incantation seems to be INTERFACE

Btw, currently grpc++_test doesn't seem to be header-only library as it does have a .cc file:
https://github.com/grpc/grpc/blob/44fb37c99f2853cc23f04fba15468980d9e28e41/BUILD#L2357

Btw, `grpc++_test` library is currently present in our cmake build:
https://github.com/grpc/grpc/blob/44fb37c99f2853cc23f04fba15468980d9e28e41/build_autogenerated.yaml#L2306 so you should be able to build it (and install it if set as installable). Note that currently its build is set as "private" (not sure if that's a problem, but it's a different issue than what's discussed here).

https://github.com/grpc/grpc/blob/44fb37c99f2853cc23f04fba15468980d9e28e41/tools/buildgen/extract_metadata_from_bazel_xml.py#L639

**Comment by jtattermusch** [comment]
Closing this issue as it's not a problem anymore (grpc++_test is not a header-only library anymore).
