### ISSUE TITLE
Type Mismatch: Negative to Unsigned

### ISSUE THREAD

**Issue by divyaKalusulingam** [grpc/grpc#22942]
**Summary**
The function in ec_asn1.c is declared to return an unsigned value, but on line 72 it returns a negative value.The function is declared to return an unsigned value, but in some cases it returns a negative value.

### What version of gRPC and what language are you using?
0.0.3
IOS

### What operating system (Linux, Windows,...) and version?
MAC- 10.15.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
Xcode

### What did you do?
**Explanation**
It is dangerous to rely on implicit casts between signed and unsigned numbers because the result can take on an unexpected value and violate weak assumptions made elsewhere in the program.

**Comment by stanley-cheung** [comment]
The file `ec_asn1.c` is under `third_party/boringssl-with-bazel`
