### ISSUE TITLE
c# bug

### ISSUE THREAD

**Issue by jinyuttt** [grpc/grpc#22946]
The flow mode of the server is abnormal. It is planned to push a lot of data to the client, but an error is reported.

System.InvalidOperationException: Only one write can be pending at a time.

grpc2.28.1  

c#

**Comment by jtattermusch** [comment]
it seems like you're using the API wrong.
In streaming calls, you're only allowed to one message at a time, and the next one is only allowed to be sent once the task returned by the stream.WriteAsync() operation finishes. The reason it's done that way is to allow flow control to push back to the application logic if the peer cannot keep us with the rate you're sending.

The right way of using the streaming API is sufficiently documented by the examples (e.g. in `await stream.WriteAsync()`)

**Comment by jtattermusch** [comment]
Closing as "working as expected"
