### ISSUE TITLE
Unreleased Resource: Synchronization 

### ISSUE THREAD

**Issue by divyaKalusulingam** [grpc/grpc#22944]
**Summary**
The function gpr_cv_init() in sync_posix.cc fails to release a lock it acquires on line 132, which might lead to deadlock.The program fails to release a lock it holds, which might lead to deadlock.

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

### What version of gRPC and what language are you using?
0.0.3 , Swift

### What operating system (Linux, Windows,...) and version?
Mac OS - 10.15.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
Xcode 11.3.1

### What did you do?
**Explanation**
The program can potentially fail to release a system resource.

In this case, there are program paths on which the resource allocated in sync_posix.cc at line 132 is not always released.

Resource leaks have at least two common causes:

- Error conditions and other exceptional circumstances.

- Confusion over which part of the program is responsible for releasing the resource.

Most unreleased resource issues result in general software reliability problems. However, if an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of service by depleting the resource pool.

**Comment by stanley-cheung** [comment]
I was looking at the `gpc_cv_init()` function https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/sync_posix.cc#L94 but I don't see the lock you mentioned in that line you mentioned. Can you double check?
