### ISSUE TITLE
Null Dereference

### ISSUE THREAD

**Issue by divyaKalusulingam** [grpc/grpc#22941]
Summary
The function check_crl() in x509_vfy.c can crash the program by dereferencing a null-pointer on line 1552.The program can potentially dereference a null-pointer, thereby causing a segmentation fault.
### What version of gRPC and what language are you using?
0.0.3
IOS - Swift/Objective C

### What operating system (Linux, Windows,...) and version?
MAC - Os - 10.15.3

### What did you do?
Explanation
Null-pointer exceptions usually occur when one or more of the programmer's assumptions is violated. There are at least three flavors of this problem: check-after-dereference, dereference-after-check, and dereference-after-store. A check-after-dereference error occurs when a program dereferences a pointer that can be null before checking if the pointer is null. Dereference-after-check errors occur when a program makes an explicit check for null, but proceeds to dereference the pointer when it is known to be null. Errors of this type are often the result of a typo or programmer oversight. A dereference-after-store error occurs when a program explicitly sets a pointer to null and dereferences it later. This error is often the result of a programmer initializing a variable to null when it is declared.

In this case, the variable can be null when it is dereferenced at line 1552, thereby causing a segmentation fault.

Most null-pointer issues result in general software reliability problems, but if an attacker can intentionally trigger a null-pointer dereference, the attacker may be able to use the resulting exception to bypass security logic in order to mount a denial of service attack, or to cause the application to reveal debugging information that will be valuable in planning subsequent attacks.

### Anything else we should know about your project / environment?
XCode - 11.3.1

**Comment by stanley-cheung** [comment]
The file `x509_vfy.c` is under `third_party/boringssl-with-bazel`.
