### ISSUE TITLE
Type Mismatch: Signed to Unsigned 

### ISSUE THREAD

**Issue by divyaKalusulingam** [grpc/grpc#22943]
**Summary**
The function in http2_settings.cc is declared to return an unsigned value, but on line 46 it returns a signed value.The function is declared to return an unsigned number but returns a signed value.

### What version of gRPC and what language are you using?
0.0.3 , IOS Swift
### What operating system (Linux, Windows,...) and version?

MAC OS -10.15.3

### What did you do?
**Explanation**
It is dangerous to rely on implicit casts between signed and unsigned numbers because the result can take on an unexpected value and violate weak assumptions made elsewhere in the program.

**Comment by stanley-cheung** [comment]
I was looking at https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/http2_settings.cc and https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/http2_settings.h, I don't see any function that's supposed to return an unsigned value and don't see a return on line 46. Can you please clarify?

**Comment by Anmolreshi** [comment]
yes
