### ISSUE TITLE
AsyncNext return TIMEOUT but ok is true and tag is not null Then cause memory leak

### ISSUE THREAD

**Issue by goudan-er** [grpc/grpc#22962]
This is my `Poller` function
```cpp
  void Poller(grpc::ServerCompletionQueue* cq) {
    void* tag = nullptr;
    bool ok = false;
    grpc::CompletionQueue::NextStatus status = grpc::CompletionQueue::SHUTDOWN;
    while ((status = cq->AsyncNext(&tag, &ok, std::chrono::system_clock::now())) == grpc::CompletionQueue::GOT_EVENT && ok) {
      LDB_ASSERT(tag != nullptr);
      static_cast<AsyncCallInterface*>(tag)->Proceed();
      ok = false;
      tag = nullptr;
    }
    // debug
    if (tag != nulptr) {
      LOG_FATAL("Memory leak", ("status", status)("ok", ok)); // status:2 ok:1
    }
    if (status != grpc::CompletionQueue::SHUTDOWN) {
      // reinvoke `Poller` to this thread....
    } else {
      // shutdown...
    }
```
The `AsyncNext` return TIMEOUT, but ok is true and the tag is not null. So the tag can not execute `Proceed` and delete itself. Proceed just like [greeter_async_server](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_server.cc#L85)
I go deep grpc a little bit and check the implementation. One possible reason that I got this issue seems `grpc_completion_queue_next` return `GRPC_OP_COMPLETE` but `core_cq_tag->FinalizeResult(tag, ok)` return `false` in the first iteration then `grpc_completion_queue_next` return `GRPC_QUEUE_TIMEOUT`. 
```cpp
CompletionQueue::NextStatus CompletionQueue::AsyncNextInternal(
    void** tag, bool* ok, gpr_timespec deadline) {
  for (;;) {
    auto ev = grpc_completion_queue_next(cq_, deadline, nullptr);
    switch (ev.type) {
      case GRPC_QUEUE_TIMEOUT:
        return TIMEOUT;
      case GRPC_QUEUE_SHUTDOWN:
        return SHUTDOWN;
      case GRPC_OP_COMPLETE:
        auto core_cq_tag = static_cast<internal::CompletionQueueTag*>(ev.tag);
        *ok = ev.success != 0;
        *tag = core_cq_tag;
        if (core_cq_tag->FinalizeResult(tag, ok)) {
          return GOT_EVENT;
        }
        break;
    }
  }
```
I have 2 questions.
1. Is this case, `grpc_completion_queue_next` return `GRPC_OP_COMPLETE` but `core_cq_tag->FinalizeResult(tag, ok)` return `false`  possible? If yes, what are the possible reasons?
2. How to use `AsyncNext` correctly? Is it ok of my `Poller` function?

BTW, _GRPC version: v1.19.1; GCC version: 5.3; OS: CentOS 7.6_

**Comment by goudan-er** [comment]
BTW, GRPC version is v1.19.1

**Comment by stanley-cheung** [comment]
I noticed you are using a really old version of gRPC 1.19.1 (more than a year ago now). Is there a particular reason you need to use that version? Or can you use a newer version? There might have been bug fixes and improvement for this.

Also, please direct general question like this one to https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
