### ISSUE TITLE
All node interop tests failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22968]
Cloud to cloud: https://source.cloud.google.com/results/invocations/c3e99981-e4d0-486b-8cad-d78951632460/targets/github%2Fgrpc%2Finterop_test/tests

Cloud to prod: https://source.cloud.google.com/results/invocations/7189ce83-88d4-4fac-ad41-8af1147c06e7/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by jtattermusch** [comment]
This seems fixed now.

**Comment by jtattermusch** [comment]
FTR https://github.com/grpc/grpc-node/pull/1430 and https://github.com/grpc/grpc-node/pull/1427
