### ISSUE TITLE
Google Cloud Storage error: The caller does not have permission

### ISSUE THREAD

**Issue by dmitry-saprykin** [grpc/grpc#22980]
### What version of gRPC and what language are you using?

gRPC 1.28.1
c++

### What operating system (Linux, Windows,...) and version?

CentOS 7

### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC 730

### What did you do?

I need to upload/download some files to Google Cloud Storage + publish/consume Google Pubsub messages. I was able to use service account json key to work with PubSub using googleapis+gRPC. Unfortunately the same credentials do not allow to read bucket data. Request fails with error "7: The caller does not have permission" (Details: "Requested bucket not on allow-list")
I see that client sends the same Bearer token to API for both PubSub and GCS.
I was successfully able to read the same data using Google Cloud cpp client library. So it does not seem like ACL problem. Please find code reproducing below.

Google Cloud cpp client library uses REST Api, does not have api to use PubSub (marked as under construction) and does not support async operations so I would prefer to use googleapis+gRPC as it is IMHO more uniform, clear and efficient.

```cpp
string bucket_name = "...";
string file_name = "...";
string account_filename = "...";
ifstream account_file(account_filename);
string json_key((istreambuf_iterator<char>(account_file)), istreambuf_iterator<char>());
auto creds = grpc::ServiceAccountJWTAccessCredentials(json_key, grpc::kMaxAuthTokenLifetimeSecs);

 //Using Service Account json key to read bucket file using GRPC+googleapis. Fails with error:
 //Output:        >> GetObjectMediaRequest failed with error 7: The caller does not have permission
 //Error details: >> Requested bucket not on allow-list. 
{
    auto channel = grpc::CreateChannel("storage.googleapis.com", grpc::SslCredentials({}));
    auto storage = make_unique<google::storage::v1::Storage::Stub>(channel);
    google::storage::v1::GetObjectMediaRequest request;
    request.set_bucket(bucket_name);
    request.set_object(file_name);
    grpc::ClientContext context;
    context.set_credentials(creds);
    auto rpc = storage->GetObjectMedia(&context, request);
    google::storage::v1::GetObjectMediaResponse response;
    rpc->Read(&response);
    auto status = rpc->Finish();
    if (!status.ok()) {
        cerr << "GetObjectMediaRequest failed with error " << status.error_code() << ": " + status.error_message() << endl;           
    }
}

 // Using Service Account json key to publish PubSub message using GRPC+googleapis. The same authentication header - Works
 // Output: >> Message id: 448091143349786
{
    auto channel = grpc::CreateChannel("pubsub.googleapis.com", grpc::SslCredentials({}));
    auto pubsub = make_unique<google::pubsub::v1::Publisher::Stub>(channel);
    grpc::ClientContext context;
    context.set_credentials(creds);
    google::pubsub::v1::PublishRequest request;
    google::pubsub::v1::PublishResponse response;
    request.set_topic("projects/.../topics/test");
    google::pubsub::v1::PubsubMessage msg;
    msg.mutable_attributes()->insert({"property", "value"});
    *request.add_messages() = msg;
    auto status = pubsub->Publish(&context, request, &response);
    if (!status.ok()) {
        cerr << "Publish failed with error " << status.error_code())) << ": " << status.error_message() << endl;
    } else {
        cout << "Message id: " << response.message_ids(0) << endl;
    }
}

 // Using Service Account json key to read bucket file using GCS cpp client library - Works
 // Output: >> Bucket contents - Hello World!
{
    namespace gcs = google::cloud::storage;
    auto creds = gcs::oauth2::CreateServiceAccountCredentialsFromJsonFilePath(account_filename);
    if (!creds) {
        std::cerr << "Failed to create ServiceAccountCredentials, status=" << creds.status() << endl;
    }

    gcs::ClientOptions options(creds.value());
    gcs::Client client(options);
    auto reader = client.ReadObject(bucket_name, file_name);
    string contents{istreambuf_iterator<char>{reader}, {}};
    cout << "Bucket contents - " << contents << endl;
}
```

### What did you expect to see?

Expected to be able to read bucket data using Service account json key to get call credentials using ServiceAccountJWTAccessCredentials()

### What did you see instead?

Error 7: The caller does not have permission
Error details:  Requested bucket not on allow-list. 

### Anything else we should know about your project / environment?
``

**Comment by zackangelo** [comment]
Also running into this error when trying to download an object via gRPC in Rust.

**Comment by nicolasnoble** [comment]
I think this is something you want to file into the client libraries' repository, but I am not really sure where it'd be.

**Comment by dmitry-saprykin** [comment]
Ok, thank you

**Comment by ernestas-poskus** [comment]
@dmitry-saprykin did you find the cause of issue?

**Comment by dmitry-saprykin** [comment]
@ernestas-poskus No, I use REST API as workaround and this issue is in technical debt to revisit later.
