### ISSUE TITLE
GRPCChannel.m line 63 the containsString api only supported in iOS8

### ISSUE THREAD

**Issue by Jiangmx** [grpc/grpc#2298]
In iOS 6 or 7,we use the [host hasPrefix:@"http"] to check wether the host has scheme provided.

**Comment by ctiller** [comment]
Note that grpc core handles uris differently in #2208. We need to provide consistency here. What is ObjC using uris for?

**Comment by nicolasnoble** [comment]
https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/private/GRPCChannel.m#L62

Finding the port to use and if SSL has to be enabled, apparently.

**Comment by Jiangmx** [comment]
Yes it is.but "[host containsString:@"://"]" can only works on devices with iOS8 or later.Doesn't grpc support iOS 6 & 7(it will crash because no such method).  

Use [host rangeOfString:@"://"] to instead?

This method return length==0 if the target string is not found. So, to check for containment: ([str rangeOfString:@"target"].length > 0).

**Comment by wangscu** [comment]
HI, @jcanizales  we found the same problem,  [string containsString ] api just work on ios 8, but in ios 7 does not work, cloud you fix this quickly?

**Comment by jcanizales** [comment]
Sorry, I was searching for ways to test this so it doesn't happen again. But apparently doing it requires installing older versions of XCode, so that will need to wait until we have Jenkins set up for iOS.

**Comment by jcanizales** [comment]
Update: We have Travis running our tests now, but it can't still be configured to run iOS 7 and 9, it's either/or (tracked at https://github.com/travis-ci/travis-ci/issues/4011).
