### ISSUE TITLE
Ruby grpc gem indirectly drops support for ruby version < 2.5

### ISSUE THREAD

**Issue by estolfo** [grpc/grpc#22990]
Hi, thanks for this Ruby gem!

I noticed that a [new version (`3.12.0`)](https://rubygems.org/gems/google-protobuf/versions/3.12.0-x86_64-linux) of the `google-protobuf` gem now only supports ruby >= 2.5. The [previous version, `3.11`](https://rubygems.org/gems/google-protobuf/versions/3.11.4-x86-mingw32), supports ruby >= 2.3.

The grpc gem's [dependency](https://github.com/grpc/grpc/blob/master/grpc.gemspec#L35) on `google-protobuf` is defined as `'~> 3.11'`. That means that now the latest version of `google-protobuf` will be installed with the grpc gem and won't support ruby 2.3 or 2.4 though the required ruby version is [defined as `>= 2.3.0`](https://github.com/grpc/grpc/blob/master/grpc.gemspec#L16).

I leave it up to you to decide what you'd like to do :) Whether you want to update your defined required ruby version and the `google-protobuf` dependency to `~> 3.12` or if you want to restrict the version of `google-protobuf` installed based on the ruby version.
Or if you want to leave it up to the user to explicitly install `google-protobuf` version `3.11` when using ruby < 2.5.
Thanks!

**Comment by stanley-cheung** [comment]
Related to #22978

**Comment by alto-ruby** [comment]
dropped ruby 2.5 support in https://github.com/grpc/grpc/pull/30699
