### ISSUE TITLE
C# client dead lock during server streaming call

### ISSUE THREAD

**Issue by rolfik** [grpc/grpc#23001]
### What version of gRPC and what language are you using?
C# Grpc 2.26.0

### What operating system (Linux, Windows,...) and version?
Windows Server 2019 / Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Core 3.1 / .NET Framework 4.8

### What did you do?
We use ASP.NET Core 3.1 with Grpc.AspNetCore 2.25.0 server and calls with server streaming from .NET Core 3.1 / .NET Framework 4.8 clients using Grpc 2.26.0.
When a client enumerates server stream with IAsyncStreamReader<T>.MoveNext() it deadlocks after some (hard to tell) time.

### What did you expect to see?
To move to the next message or respect given CancellationToken

### What did you see instead?
Deadlock

When debugged in Visual Studio:
![image](https://user-images.githubusercontent.com/4658651/82415183-73eebc00-9a78-11ea-94ef-d8fc1cb97079.png)
![image](https://user-images.githubusercontent.com/4658651/82417382-c382b700-9a7b-11ea-8af9-64066e28459a.png)

### Anything else we should know about your project / environment?
Our scenario: We began to see these deadlocks in clients during server stream enumerations as described above and because these calls are kept on server to notify clients for long time (as long as possible during client runtime) we thought it is some keep alive issue, but server continued to send messages to clients without problems, but clients did not receive anything after some time. Anyway we have added gRPC channel options for keep alive on clients and veryfied the Kestrel server replied to HTTP2 pings well, but the issue was not solved. So we have decided to dispose old call already being enumerated and recall new one at the same server endpoint after some configurable time to avoid the problem, but the issue remains unsolved.

**Comment by rolfik** [comment]
#21633 mentions similar behaviour.

**Comment by jtattermusch** [comment]
@rolfik  can you provide a reproduction (ideally as a project in a git repo)? Without it the description of the problem is way too vague to be actionable.
Also please describe what exactly you mean by "deadlock" in this case.

**Comment by rolfik** [comment]
@jtattermusch I have no simple reproduction now, but only complex applications.
By "deadlock" I mean what I have already written:
ASP.NET server keeps long time client (C wrapped with .NET) calls for streaming notifications to them.
It may send some notifications and wait longer time and send next ones. But even when server sends notifications after longer pause (hours) to client stream with success, the client still awaits MoveNext call while enumerating notification stream and does not receive the notification.
Another thing I have found is that when a CancellationToken passed to MoveNext is cancelled and MoveNext still awaits next message, the token is ignored and nothing is cancelled.
We have solved this in production now with custom MoveNext method which awaits two tasks and ends immediatelly after the cancellation is requested while still letting the original MoveNext in progress. This allows us to cancel MoveNext call after specified timeout, dispose it and call server again to begin new notification stream enumeration.

```csharp
        /// <summary>
        /// Moves to next message
        /// </summary>
        /// <remarks>
        /// <paramref name="cancellation"/> is not honored between waiting for next call in <see cref="IAsyncStreamReader{T}.MoveNext"/>, so this method solves it with extra cancellation task respecting <paramref name="cancellation"/> and <see cref="Task.WhenAny"/>, but when <paramref name="cancellation"/> is cancelled between messages, <see cref="IAsyncStreamReader{T}.MoveNext"/> is still in progress which can be stopped by disposing its call.
        /// </remarks>
        /// <typeparam name="T">Message type</typeparam>
        /// <param name="stream">Stream</param>
        /// <param name="cancellation">Cancellation</param>
        /// <returns>Whether there is any next message</returns>
        public static async Task<bool> MoveNextWith<T>(this IAsyncStreamReader<T> stream, CancellationToken cancellation)
        {
            Validate(stream);
            bool next;
            if (cancellation.CanBeCanceled)
            {
                var cancellationTaskSource = new TaskCompletionSource<bool>();
                using var cancellationRegistration = cancellation.Register(
                    ct => ((TaskCompletionSource<bool>)ct).SetCanceled(),
                    cancellationTaskSource
                    );
                var moveNextTask = stream.MoveNext(cancellation);
                var task = await Task.WhenAny(moveNextTask, cancellationTaskSource.Task);
                if (task == cancellationTaskSource.Task)
                    throw new OperationCanceledException(cancellation);
                next = task.Result;
            }
            else
                next = await stream.MoveNext(cancellation);
            return next;
        }

**Comment by rolfik** [comment]
Any news?

**Comment by jtattermusch** [comment]
Ok, looks like your are actually using grpc-dotnet (not Grpc.Core) - I haven't noticed that before.

@JamesNK  can you please take a look?

**Comment by JamesNK** [comment]
There shouldn't be any issue with a Grpc.Core client calling Grpc.AspNetCore server. There are cases where you'd want to mix the two. For example, if you're in Kubernetes then you might want Grpc.Core's client side load balancing to talk to Grpc.AspNetCore servers.

**Comment by jtattermusch** [comment]
@tonydnewell  can you please take a look and suggest the best next steps here?

**Comment by tonydnewell** [comment]
@rolfik is this still an issue? I know you have a workaround but are you still able to reproduce the original problem? Are you able to provide a reproduction (ideally as a project in a git repo)? Or could you provide some diagnostic logging - see https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md ?
