### ISSUE TITLE
Python experimental channel credential functions

### ISSUE THREAD

**Issue by larkee** [grpc/grpc#23000]
Is there any plan to remove the experimental status of insecure_channel_credentials or local_channel_credentials? If so, what kind of timeline would that be?

**Comment by gnossen** [comment]
`insecure_channel_credentials` are part of a [recently introduced set of APIs](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_simple_stubs.py) that are themselves experimental. We're still proving them out, so we expect them to retain their experimental status for at least the next few months. Did you have a particular use case for it? Do note that [`insecure_channel`](https://grpc.github.io/grpc/python/grpc.html?highlight=insecure_channel#grpc.insecure_channel) is, of course, a stable API and likely what you're actually looking for.

CC @yihuazhang to comment on the plans for `local_channel_credentials`.

**Comment by yihuazhang** [comment]
Thanks for looping me in. I will bring it up in the next gRPC security team meeting and get back to you. Currently, gRPC C++, python and Go (very close - https://github.com/grpc/grpc-go/pull/3517) support local credentials.

**Comment by larkee** [comment]
> Did you have a particular use case for it? Do note that insecure_channel is, of course, a stable API and likely what you're actually looking for.

I have found an alternative that does not require `insecure_channel_credentials`.

> Currently, gRPC C++, python and Go (very close - [grpc/grpc-go#3517](https://github.com/grpc/grpc-go/pull/3517)) support local credentials.

In Python, [it is still labelled experimental](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L1779). Is this correct or out of date?

**Comment by gnossen** [comment]
`local_channel_credentials` is correctly labelled experimental. As @yihuazhang said, he'll come back with a timeline for graduation after conferring with the security team.

**Comment by gnossen** [comment]
Going ahead and closing, since the original questions have been answered. Feel free to reopen if you need further clarification.
