### ISSUE TITLE
c# The server stream mode cannot be received

### ISSUE THREAD

**Issue by jinyuttt** [grpc/grpc#23039]
#229774
I ran into a problem and started the test. I feel deadlocked due to asynchronous programming problems. Programming like async / await can deadlock. Business code may not have been written in consideration. Whether to consider not generating interfaces in this way. Directly back to the era of task

**Comment by yashykt** [comment]
Hi, sorry for closing down the question. This form is intended for bugs and feature requests. Please target questions to wider communities like stack-overflow
