### ISSUE TITLE
I have the same error  just like this.

### ISSUE THREAD

**Issue by batmancn** [grpc/grpc#23043]
I have the same error  just like this.
How do you fix this ?

go Server + go Client -> OK
go Server + grpc-gateway + curl -> OK
go Server + Py3.5 Client -> line 445 raise _Rendezvous(state, None, None, deadline)

_Originally posted by @cheung-chifung in https://github.com/grpc/grpc/issues/9987#issuecomment-287126303_

**Comment by markdroth** [comment]
This is not the right forum for questions.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
