### ISSUE TITLE
[FLAKE] Ruby package build failure

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#23047]
Ruby package build still fails in our CI `prod:grpc/core/master/linux/grpc_build_packages`. It seems Docker related, maybe update the images will fix the issue?

https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_packages

```
+ cp '/var/local/jenkins/grpc/input_artifacts/protoc_macos_x86/protoc*' '/var/local/jenkins/grpc/input_artifacts/protoc_macos_x86/grpc_ruby_plugin*' /var/local/git/grpc/src/ruby/tools/bin/x86-macos/
cp: cannot stat '/var/local/jenkins/grpc/input_artifacts/protoc_macos_x86/protoc*': No such file or directory
cp: cannot stat '/var/local/jenkins/grpc/input_artifacts/protoc_macos_x86/grpc_ruby_plugin*': No such file or directory
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc/artifacts
+ docker cp build_and_run_docker_51214002-81cb-4bf2-a786-3c3b510bd47c:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
+ docker rm -f build_and_run_docker_51214002-81cb-4bf2-a786-3c3b510bd47c
build_and_run_docker_51214002-81cb-4bf2-a786-3c3b510bd47c
+ '[' true '!=' '' ']'
+ exit 1

2020-05-26 10:35:37,306 FAILED: build_package.ruby_package [ret=1, pid=7751, time=76.5sec]
```

**Comment by apolcyn** [comment]
This is because the upstream macos artifacts build is failing (which is what makes those binaries available for packaging here).

In the upstream job we have this error:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/gpg
Target /usr/local/bin/gpg
already exists. You may want to remove it:
  rm '/usr/local/bin/gpg'

To force the link and overwrite all conflicting files:
  brew link --overwrite gnupg

To list all files that would be deleted:
  brew link --overwrite --dry-run gnupg

Possible conflicting files are:
```

https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_build_artifacts?search_pattern=grpc%2Fcore%2F&include_inactive_projects=false

**Comment by lidizheng** [comment]
It seems only affect Ruby compilation, maybe the `--overwrite` flag fixes the issue?

**Comment by apolcyn** [comment]
Yes I'm not sure why only ruby is affected in the package build - the artifacts macos build I think is failing for all languages.

I will try that `--overwrite` flag, trying https://github.com/grpc/grpc/pull/23048 first

**Comment by apolcyn** [comment]
cc @jtattermusch

**Comment by stanley-cheung** [comment]
This has been green the last few days.
