### ISSUE TITLE
Interop Cloud-to-Prod Tests (build_docker_dart)

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23055]
build_docker_dart error seen on https://github.com/grpc/grpc/pull/23053 error - 

https://source.cloud.google.com/results/invocations/a1314158-9b5d-4860-8eb0-e96e3263c4f0/log

**Comment by yashykt** [comment]
@sigurdm PTAL

**Comment by sigurdm** [comment]
I don't see any errors printed in the log. Does this look like a flake?

**Comment by yashykt** [comment]
yes, it looks like a flake, and you are right that the logs do not mention any errors. I was hoping that it was some kind of known issue with a known workaround. In this case, it looks like the starting step would be to have a way to atleast know what kind of issue it was. 

I'm going to close this issue for now, but if it flares up again, we should spend some time to figure out why it failed.

**Comment by yashykt** [comment]
well, turns out we are seeing it more often.

**Comment by yashykt** [comment]
@jtattermusch any suggestions?

**Comment by stanley-cheung** [comment]
Getting some more verbose debug after #23496.

Here's one new `build_docker_dart` failure: https://source.cloud.google.com/results/invocations/7453503d-dbb3-4ff7-a214-778b6afea212/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

```
FINE: Exception type: ClientException
FINE: package:http/src/io_client.dart 65:7        IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 109:52           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 122:11           captureErrors
    | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand

2020-07-16 16:12:07,242 FAILED: build_docker_dart [ret=69, pid=21383, time=137.6sec]
```

... although it's unclear to me what that means.

**Comment by jtattermusch** [comment]
I also don't understand it, but I think pretty likely it's a download error. Ideally our interop test build wouldn't require any downloads but for some languages that's basically an impossible standard.
I think just `pub get || pub get` would help (I don't think the sleep is necessary).

**Comment by jtattermusch** [comment]
btw, based on our historical data, we should be able query which interop builds fail the most often (java, dart or something else..) and tackle them first (fixing only the most important ones improves experience but saves time - we likely won't be able to make all our builds really 100.0% flake proof).
