### ISSUE TITLE
nuget fails on .NET 4.5.1 and 4.5.2

### ISSUE THREAD

**Issue by carstn** [grpc/grpc#2305]
Nuget will not download and install the GRPC package if you're targeting .NET 4.5.1 or 4.5.2. Version 4.5 works.

**Comment by carstn** [comment]
Actually I think it doesn't work on .Net 4.5 either.
[One package dependency](http://www.nuget.org/packages/Microsoft.Bcl.Immutable) has been rolled into System.Collections.Immutable. @jtattermusch Perhaps this is something you know about?

**Comment by jtattermusch** [comment]
I wasn't able to replicate this one. I tried creating a new console app project and installing Grpc package in it and it worked just fine. I tried for both .NET 4.5   and .NET 4.5.1. Can you please describe more in detail what issues you've been seeing?

Regarding the System.Collections.Immutable - yeah, it looks like that one was finally released as stable and consequently, Microsoft.Bcl.Immutable was hidden from nuget.org. But, nuget packages that depend on  the hidden package should still work without any problem (you won't be able to locate the package when searching for it, but it's still there and visual studio downloads it just fine).

**Comment by jtattermusch** [comment]
Closing this as I wasn't able to replicate this. Please reopen if you are still seeing this.
