### ISSUE TITLE
Artifact Build MacOS (internal CI) fails

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23054]
Seen on https://github.com/grpc/grpc/pull/23053

https://source.cloud.google.com/results/invocations/e68c4538-dc87-49ce-a922-e72644d339bf/log

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
Requirements installation failed with status: 1.
__rvm_rm_rf already gone: /Users/kbuilder/.rvm/tmp/3021*

[ID: 3310865] Build finished after 461 secs, exit value: 1

Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[17:36:41] Collecting build artifacts from build VM
Build script failed with exit code: 1

**Comment by karthikravis** [comment]
Same issue seen on "Basic Tests Ruby MacOS" as well

https://source.cloud.google.com/results/invocations/10303c4c-5603-48fe-89d5-c01e627d0da2/log

**Comment by stanley-cheung** [comment]
#23027

**Comment by stanley-cheung** [comment]
This is fixed with #23057
