### ISSUE TITLE
The grpc gem doesn't build with TruffleRuby on Mac OS

### ISSUE THREAD

**Issue by norswap** [grpc/grpc#23069]
### What version of gRPC and what language are you using?

Ruby, latest version (1.28.0) & git master head.

### What operating system (Linux, Windows,...) and version?

Mac OS Catalina (10.15.4)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby: [TruffleRuby] (git head, dev for 20.2)
GCC: [Sulong] (dev for 20.2)

[TruffleRuby]: https://github.com/oracle/truffleruby
[Sulong]: https://github.com/oracle/graal/tree/master/sulong

### What did you do?

As part of our work on TruffleRuby, we are trying to get the grpc gem to build and run on TruffleRuby (cf. https://github.com/oracle/truffleruby/issues/1982).

TruffleRuby supports native Ruby extensions using [Sulong], which re-implement the LLVM toolchain on top of GraalVM.

grpc builds correctly with TruffleRuby/Sulong on Linux, but we ran into multiple build issues on Mac OS, which I managed to fix in the following way:

1. Remove out all lines ending with `if RUBY_PLATFORM =~ /darwin/` in [`extconf.rb](https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/extconf.rb).
2. Add the path to our LLVM toolchain binaries on the path.

Regarding (1), this might be too broad a change, but many of those definitely have adverse effects. In particular, `ENV['ARCH_FLAGS'] = '-arch i386 -arch x86_64'` caused the `lipo` error reported by our user (https://github.com/oracle/truffleruby/issues/1982). `ENV['AR'] = 'libtool -o' if RUBY_PLATFORM =~ /darwin/` overwrites the `AR` variable set by TruffleRuby which points to Sulong's own `libtool`.

Regarding (2), this is necessary because the top-level makefile calls `ranlib` directly instead of indirecting through `$(RANLIB)`. Hopefully that's the only issue fixed by that, I will try to confirm this. Replacing `ranlib` to `$(RANLIB)`.

To reproduce: 
- install [TruffleRuby]
- (with TruffleRuby on path): `gem install grpc`

Note that even if you fix the `ranlib` issue, it won't work as of right now because we still have to define `RANLIB` in TruffleRuby's `RbConfig`. I'll get that merged ASAP and update when done.

Note that `grpc` currently *does not run* on TruffleRuby after installing (on any platform), but that is most likely due to a bug on our side which we have reported to the Sulong team.

### What did you expect to see?

The gem installing correctly.

### What did you see instead?

Detailed in https://github.com/oracle/truffleruby/issues/1982 :
- `lipo`issues
- `libtool` issues (after fixing the above)
- `ranlib` issues (after fixing the above)

**Comment by norswap** [comment]
Update: the steps above do not actually fix the issue. I thought they would because when I run `bundle install && bundle exec rake` it does launch the test and produce the error we see also on Linux.

But actually trying to install with `bundle exec rake install` still fails with various problems:
- unsupported `-no_warning_for_no_symbols` for Sulong's `ranlib` (patched that manually in the top level makefile)
- `unsupported load command` on `strip` — here I am stuck. I tried adding the `-x` flag as `extconf.rb` originally did, but that leads to another error:

```
/Users/norswap/work/ws/truffleruby/mxbuild/truffleruby-jvm/jre/lib/llvm/bin/llvm-strip: error: 'grpc_c.bundle': option not supported by llvm-objcopy for MachO
```

And I have no idea where that one come from, and so what I could change to get rid of it.

This hacked build also comes with tons of warnings of the type:

```
ld: warning: linking module flags 'Dwarf Version': IDs have conflicting values ('i32 2' from /Users/norswap/work/ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/grpc-1.30.0.dev/src/ruby/ext/grpc/libs/opt/libgrpc.a(tls_record.o) with 'i32 4' from ld-temp.o)
```

**Comment by norswap** [comment]
Removing the final `if grpc_config == 'opt'` block (which adds strip rules) from `extconf.rb` fixes the final issues, and all the Dwarf warnings.

So to summarize all changes I did to make it build & install fine:

- removed all `darwin` checks in `extconf.rb`
- remove `if grpc_config == 'opt'` block at end of `extconf.rb`
- use `$(RANLIB)` instead of `ranlib` in top level makefile
- remove `-no_warning_for_symbols` flag in top-level makefile

**Comment by karthikravis** [comment]
@apolcyn : can you please help with this Ruby question? Thanks.

**Comment by apolcyn** [comment]
@norswap thanks for this detailed issue.

As you may know, we only develop and test against MRI ruby versions, and unfortunately I don't think I'll have the time to add and test this support for TruffleRuby myself. However, I would be happy to accept a patch for this support, especially if the patch can be done without being too invasive to the existing linux/macos/windows MRI ruby builds.

So I'll label this as help wanted. @norswap are you able to work on this in a pull request?

**Comment by norswap** [comment]
We're looking into whether that's possible at the moment. It might require some legal approval at Oracle. Will let you know!

(Otoh, making the outlined changes work should be really easy: `$(RANLIB)` should be a simple change in the CMake to emit a variable (+ initialize it if unset). The changes in `extconf.rb` can be a simple as sticking an extra condition to all the outlined places (`RUBY_ENGINE == 'truffleruby'`). The only thing that requires a little more thought is `-no_warning_for_symbols`, but I will enquire if we could potentially fix that one upstream.)

**Comment by apolcyn** [comment]
Sounds good. I'd prefer to accept a pull request than to make this PR myself with guidance, mainly because I don't think I'll be able to test Truffle Ruby support as well as you. So I'll wait to hear if that's an option for you.

**Comment by norswap** [comment]
We're looking into it and we'll let you know. It might take a while to even have an answer, but I don't think this is super urgent as long as the gem itself doesn't run.

But if it doesn't pan out, we can also test it to make sure everything is fine before merging, and you can always send me a message if you have any questions. We also have some plans currently to run some gems on CI to avoid regressions, so that might also be a possibility soon.

**Comment by kvokka** [comment]
Just pinging @norswap with the question if there are any movements in this issue?
Thank you

**Comment by norswap** [comment]
Actually, I got back word last week that it had been approved. Will have a look as soon as possible.

**Comment by kvokka** [comment]
thank u, @norswap
