### ISSUE TITLE
"Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute '_rpc_event'"

### ISSUE THREAD

**Issue by Psykepro** [grpc/grpc#23070]
Can anybody please help me I'm trying to use the new Asyncio API of gRPC in out project but I got this error:
"Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute '_rpc_event'"

**Comment by Psykepro** [comment]
Can anybody please help me I'm trying to use the new Asyncio API of gRPC in out project but I got this error:
`"Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute '_rpc_event'"`

**Comment by lidizheng** [comment]
Can you share your code and context of this error? Maybe there is a mix between non-asyncio and asyncio API usage.

**Comment by Psykepro** [comment]
Thanks for answering! Yep, you were right there is a mix of non-asyncio and asyncio API usage. I'll explain what we are doing first. So we have a python core for creating microservices that are implemented in a way to reuse the implementation for each method for REST and for gRPC. And we have a ServiceServicer which overrides the normal Servicer for the particular microservice and adds up Base Methods and replace the method handlers with a 'process' method which dispatches maps the Request message to a dict then this dict is passed to the reused implementation and the response is mapped back to the Response message and then is returned. So the non-asyncio functionality which I saw now are the following methods:
```
grpc.unary_unary_rpc_method_handler
grpc.method_handlers_generic_handler
```
From what I've saw here: https://github.com/grpc/proposal/pull/155/files/7e10026a1a31e26e60b053fc8e3756227a20ccb8
You wrote that it is added async implementations for them but when I've tried to search them don't found them in `grpc.aio` neither in `grpc.experimental.aio`. Please tell with what I need to replace them to work. :)

**Comment by Psykepro** [comment]
Also now I saw the actual error comes from this in out python core: 
```
    @classmethod
    def get_call_source_name(cls, context):
        return context._rpc_event.call_details.method.decode("utf-8").split('/')[-1]
```

**Comment by Psykepro** [comment]
And wonder why it is using `_cython.cygrpc._ServicerContext` instead of `_base_server.ServicerContext ` which is the async implementation. 

We are generating the protobuf files with the following command: 
`python3.7 -m grpc_tools.protoc --python_out=. --grpc_python_out=. --proto_path=. {microservice_name}.proto -I=../base` - where **base** is proto file containing the base services and messages which are reused also.

And I can see that the `${microservice_name}_pb2_grpc.py` do import **grpc** instead of **grpc.experimental.aio** which is used for the **ServiceServicer** and **ServiceStub**. And this is what I think causes the application to use the non-asyncio implementation.
 
Is there any way to change the command to generate them with the **asyncio** implementation?

**Comment by Psykepro** [comment]
Here is the refactored code of the GRPCServicer:

`import asyncio
import time
from concurrent import futures

import grpc
import grpc.experimental.aio as grpc_async
from protobuf_to_dict import protobuf_to_dict

from python_core.helpers import protobuf
from python_core.helpers.environment import environment
from python_core.helpers.grpc import GRPCHelper
from python_core.helpers.url import URLHelper
from python_core.libraries.default_handler import DefaultHandler

base_grpc_template = GRPCHelper.load_grpc_template(template_name='base')
app_grpc_template = GRPCHelper.load_grpc_template()
app_definitions_module = GRPCHelper.load_grpc_template(file_extension='_pb2.py')
base_definitions_module = GRPCHelper.load_grpc_template(template_name='base', file_extension='_pb2.py')

server_host, server_port = environment.get_variable('GRPC_HOST'), environment.get_variable('GRPC_PORT')


class GRPCServicer(app_grpc_template.ServiceServicer):
    def __init__(self, requests_details_dict):
        self.requests_details_dict = requests_details_dict

    def process(self, request, context):
        request_to_dict = protobuf_to_dict(request)
        # Get path, method and options from request details dictionary by gRPC request object type
        request_details = self.requests_details_dict[type(request).__name__]
        path = URLHelper.replace_params_in_path(request_details['path'], request)
        request_to_dict['path'] = path
        request_to_dict['method'] = request_details['method']
        request_to_dict['protocol'] = 'gRPC'

        if 'data' in request_to_dict:
            request_to_dict.update({'body': request_to_dict['data']})

        # Get client function name from context (е.g. post_comment, get_comment...)
        # so that the handler can take action based on that name
        function_name = GRPCHelper.get_call_source_name(context)
        response = asyncio.run(DefaultHandler.handle(function_name, request_to_dict))

        # Convert json response back to protobuf format
        response_class = getattr(app_definitions_module, request_details['response'])
        if response['data'] is None:
            response.update({'data': ''})
        grpc_response = protobuf.dictionary_to_protobuf(response_class, response)

        return grpc_response


def add_base_methods_to_server(app_servicer, server):
    base_servicer = base_grpc_template.ServiceServicer()
    base_methods = [method for method in dir(base_servicer) if not method.startswith('__')]
    # Replace defined functions pointers with process function so that all gRPC calls get handled by it
    for base_method in base_methods:
        setattr(base_servicer, base_method, app_servicer.process)

    base_methods = base_definitions_module._SERVICE.methods
    rpc_method_handlers = {}
    for method in base_methods:
        # Add process function as rpc handler for all base methods
        rpc_method_handlers[method.name] = grpc.unary_unary_rpc_method_handler(
            app_servicer.process,
            request_deserializer=method.input_type._concrete_class.FromString,
            response_serializer=method.output_type._concrete_class.SerializeToString,
        )

    generic_handler = grpc.method_handlers_generic_handler('base.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


def start_grpc_asyncio_server(requests_details_dict, loop):
    grpc_async.init_grpc_aio()
    server = grpc_async.server()
    
    # Register main servicer
    grpc_servicer = GRPCServicer(requests_details_dict)
    servicer = app_grpc_template.ServiceServicer()
    methods = [method for method in dir(servicer) if not method.startswith('__')]

    # Replace defined functions pointers with process function so that all gRPC calls get handled by it
    for method in methods:
        setattr(grpc_servicer, method, grpc_servicer.process)

    app_grpc_template.add_ServiceServicer_to_server(grpc_servicer, server)
    add_base_methods_to_server(grpc_servicer, server)
    server.add_insecure_port('{}:{}'.format(server_host, server_port))
    loop.run_until_complete(server.start())`

**Comment by lidizheng** [comment]
One nitpicking about your code, `loop.run_until_complete` might behave differently than you expect. `server.start()` is not a long-running method, it continues if the server is started. You can consider calling `loop.create_task` to schedule it asynchronously, or `wait_for_termination` after server start. Other than this, the code is good 👍 

> Is there any way to change the command to generate them with the asyncio implementation?

The ProtoBuf generated code can be shared between sync stack and asyncio stack. You should be able to reuse the generated "pb2" modules.

> "grpc.unary_unary_rpc_method_handler" and "grpc.method_handlers_generic_handler"

Turned out, these two methods don't require asyncio specific modification yet. As said in the proposal, the API design might become obsolete. The up-to-date API reference should be found here: https://grpc.github.io/grpc/python/grpc_asyncio.html.

**Comment by Psykepro** [comment]
I thought that `server.start()` will create task okay I'll change it to `loop.create_task(server.start())`. However, I think I don't need `wait_for_termination` because after starting the gRPC server I'm starting REST (Quart/Pint)  server which is stopping the application from finishing. So I suggest I need to find a way to refactor this part:
```
    @classmethod
    def get_call_source_name(cls, context):
        return context._rpc_event.call_details.method.decode("utf-8").split('/')[-1]
```
 To work with `grpc._cython.cygrpc._ServicerContext` but the problem is that this is C-Type from what I  can see and the debugger cannot decompile it so I cant find which field can give me the name of the called function. 

Btw isn't something wrong in our implementation because I can't figure out why I'm receiving `grpc._cython.cygrpc._ServicerContext` instead of `grpc.experimental.aio.ServicerContext` which is specified in the API reference: https://grpc.github.io/grpc/python/grpc_asyncio.html

**Comment by chennupushkar** [comment]
> Here is the refactored code of the GRPCServicer:
> 
> ```python
> import asyncio
> import time
> from concurrent import futures
> 
> import grpc
> import grpc.experimental.aio as grpc_async
> from protobuf_to_dict import protobuf_to_dict
> 
> from python_core.helpers import protobuf
> from python_core.helpers.environment import environment
> from python_core.helpers.grpc import GRPCHelper
> from python_core.helpers.url import URLHelper
> from python_core.libraries.default_handler import DefaultHandler
> 
> base_grpc_template = GRPCHelper.load_grpc_template(template_name='base')
> app_grpc_template = GRPCHelper.load_grpc_template()
> app_definitions_module = GRPCHelper.load_grpc_template(file_extension='_pb2.py')
> base_definitions_module = GRPCHelper.load_grpc_template(template_name='base', file_extension='_pb2.py')
> 
> server_host, server_port = environment.get_variable('GRPC_HOST'), environment.get_variable('GRPC_PORT')
> 
> 
> class GRPCServicer(app_grpc_template.ServiceServicer):
>     def __init__(self, requests_details_dict):
>         self.requests_details_dict = requests_details_dict
> 
>     def process(self, request, context):
>         request_to_dict = protobuf_to_dict(request)
>         # Get path, method and options from request details dictionary by gRPC request object type
>         request_details = self.requests_details_dict[type(request).__name__]
>         path = URLHelper.replace_params_in_path(request_details['path'], request)
>         request_to_dict['path'] = path
>         request_to_dict['method'] = request_details['method']
>         request_to_dict['protocol'] = 'gRPC'
> 
>         if 'data' in request_to_dict:
>             request_to_dict.update({'body': request_to_dict['data']})
> 
>         # Get client function name from context (е.g. post_comment, get_comment...)
>         # so that the handler can take action based on that name
>         function_name = GRPCHelper.get_call_source_name(context)
>         response = asyncio.run(DefaultHandler.handle(function_name, request_to_dict))
> 
>         # Convert json response back to protobuf format
>         response_class = getattr(app_definitions_module, request_details['response'])
>         if response['data'] is None:
>             response.update({'data': ''})
>         grpc_response = protobuf.dictionary_to_protobuf(response_class, response)
> 
>         return grpc_response
> 
> 
> def add_base_methods_to_server(app_servicer, server):
>     base_servicer = base_grpc_template.ServiceServicer()
>     base_methods = [method for method in dir(base_servicer) if not method.startswith('__')]
>     # Replace defined functions pointers with process function so that all gRPC calls get handled by it
>     for base_method in base_methods:
>         setattr(base_servicer, base_method, app_servicer.process)
> 
>     base_methods = base_definitions_module._SERVICE.methods
>     rpc_method_handlers = {}
>     for method in base_methods:
>         # Add process function as rpc handler for all base methods
>         rpc_method_handlers[method.name] = grpc.unary_unary_rpc_method_handler(
>             app_servicer.process,
>             request_deserializer=method.input_type._concrete_class.FromString,
>             response_serializer=method.output_type._concrete_class.SerializeToString,
>         )
> 
>     generic_handler = grpc.method_handlers_generic_handler('base.Service', rpc_method_handlers)
>     server.add_generic_rpc_handlers((generic_handler,))
> 
> 
> def start_grpc_asyncio_server(requests_details_dict, loop):
>     grpc_async.init_grpc_aio()
>     server = grpc_async.server()
>     
>     # Register main servicer
>     grpc_servicer = GRPCServicer(requests_details_dict)
>     servicer = app_grpc_template.ServiceServicer()
>     methods = [method for method in dir(servicer) if not method.startswith('__')]
> 
>     # Replace defined functions pointers with process function so that all gRPC calls get handled by it
>     for method in methods:
>         setattr(grpc_servicer, method, grpc_servicer.process)
> 
>     app_grpc_template.add_ServiceServicer_to_server(grpc_servicer, server)
>     add_base_methods_to_server(grpc_servicer, server)
>     server.add_insecure_port('{}:{}'.format(server_host, server_port))
>     loop.run_until_complete(server.start())
> ```

@Psykepro I am also facing the same issue which you have mentioned. Any luck with the solution?
