### ISSUE TITLE
NameError: global name 'services_withWeights' is not defined

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#23079]
Started happening after #23009 is merged, looks like.

Looks like this is the typo? https://github.com/grpc/grpc/commit/e3d26ffc7463da30f95be1f07083104aa2eaf9a4#diff-90f4c3f4d1b5066f622fc01e5bcb5a56R1091

Log: https://source.cloud.google.com/results/invocations/e76b15cd-ccf1-4ffc-9b07-03492560e045/targets;collapsed=/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_ruby/log

**Comment by menghanl** [comment]
Fix is in https://github.com/grpc/grpc/pull/23078

**Comment by stanley-cheung** [comment]
> Fix is in #23078

Thanks!
