### ISSUE TITLE
how to keep alive connection with php?

### ISSUE THREAD

**Issue by Robertzyp** [grpc/grpc#23098]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by stanley-cheung** [comment]
See https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Comment by j0hnsmith** [comment]
Since this ranks on google... the keepalive params (and all the other) are listed on https://github.com/grpc/grpc/blob/v1.36.x/include/grpc/impl/codegen/grpc_types.h

Pass options into the channel as an array, eg 

```
$opts = ['grpc.keepalive_time_ms' => 2000];
...
```
