### ISSUE TITLE
undefined reference to `google::protobuf::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)'

### ISSUE THREAD

**Issue by DazedDreamer** [grpc/grpc#23097]
Hi!

I am working on writing a Food finder service wherein I utilize a gRPC client-server model to produce results. The client asks the user for a ingredient, then requests the server to lookup a list of vendors who have that ingredient and returns the results back.

My code is in this repository: https://github.com/DazedDreamer/OpenTelemetry-StarterProject.git

My sequence of commands for compilation and executing the code is:
mkdir -p build
cd build
cmake ..
make

When I run make, I get the following error:

![image](https://user-images.githubusercontent.com/31712484/83347381-8cad6c00-a2d9-11ea-9cdf-487d3cf9bf83.png)

I am using protoc version 3.11.2, and am suspecting it has something to do with the compatibility of protoc with gRPC.

Any help would be really appreciated. 

Thank you!

**Comment by markdroth** [comment]
This is not the right forum for questions.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
