### ISSUE TITLE
iOS  if .proto has same object ,  like 2 .proto also has 'base' element, that will be errors, duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by bluestonesea** [grpc/grpc#23112]
iOS  if .proto has same object ,  like 2 .proto also has 'base' , that will be errors, duplicate symbols for architecture x86_64

**Comment by stanley-cheung** [comment]
Can you share be a little more concrete please? Is there a small .proto test case, and a protoc command to reproduce what you mean?
