### ISSUE TITLE
How can I use boringssl instead of openssl ?

### ISSUE THREAD

**Issue by jackonan** [grpc/grpc#23113]
Hi, I want to use grpc as a static library. That is, linking libgrpc++.a and libgrpc.a into my libmy.so. But I found that, if openssl has installed on my machine, grpc will use openssl instead of boringssl, which makes libmy.so depends on libopenssl.so. That is not what I want. Can I find some options to disable openssl ? 

My version is 1.26.x.

Thanks!

**Comment by jiangtaoli2016** [comment]
The simplest way is the uninstall openssl library from your system, the grpc build-in boringSSL will be triggered.

e.g., something like `sudo apt-get remove libssl-dev`

@nicolasnoble may have better suggestions.

**Comment by veblush** [comment]
Depending on how to build gRPC;
- `EMBED_OPENSSL=true` for makefile 
- `gRPC_SSL_PROVIDER=module` for cmake

**Comment by alyubimof** [comment]
How to use this otion if builded grpc with ./vcpkg install grpc ?
