### ISSUE TITLE
Consider adding an issue template config with links to other implementation repos

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#23124]
You can add links to other repos on the issues page.

Example config:
https://github.com/grpc/grpc-dotnet/blob/master/.github/ISSUE_TEMPLATE/config.yml

What it looks like:
https://github.com/grpc/grpc-dotnet/issues/new/choose

grpc/grpc should add links to other repositories. It should reduce how often issues are created in the wrong repository.

**Comment by srini100** [comment]
Thanks for the suggestion. We'll have to add buttons for several repos like Java, Go, Node, Dotnet, Swift, Kotlin etc. That'll be too many buttons. I don't think creating issues in the wrong repo has been a big issue. @yashykt, what do you think?

**Comment by yashykt** [comment]
It hasn't been much of an issue for us, but I do see the benefit of such links. Especially, for example to be able to create bugs specifically for Python or a different wrapped language, but then that would be too many buttons like Srini said.
