### ISSUE TITLE
How to keep data for current thread in grpc Service?

### ISSUE THREAD

**Issue by ljch2018** [grpc/grpc#23127]
I has a big dictionary in momory，but it is not thread-safe.
Anyone know how to keep it is grpc Service? Thank.

This feature can be found in brpc, [https://github.com/apache/incubator-brpc/blob/master/docs/en/server.md](url)
```
session-local
A session-local data is bound to a server-side RPC: from entering CallMethod of the service, to calling the server-side done->Run(), no matter the service is synchronous or asynchronous. All session-local data are reused as much as possible and not deleted before stopping the server.

After setting ServerOptions.session_local_data_factory, call Controller.session_local_data() to get a session-local data. If ServerOptions.session_local_data_factory is unset, Controller.session_local_data() always returns NULL.

If ServerOptions.reserved_session_local_data is greater than 0, Server creates so many data before serving.
```

**Comment by markdroth** [comment]
This is not the right forum for questions.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
