### ISSUE TITLE
[C++] ByteBuffer API is unnecessarily pessemistic

### ISSUE THREAD

**Issue by oakad** [grpc/grpc#23120]
Followup from #17605 and previous discussion.

Dumping into `std::vector<Slice>` is unnecessarily pessimistic and restrictive. It will be substantially more convenient, if `Dump` method was templated to accept an arbitrary consumer:

```
template<typename Consumer>
Status Dump(Consumer &&cons)
```
where `Consumer` type can be any `auto (*)(Slice const &) -> Status` callable (assuming that non-ok status breaks consumption).

Alternatively, ByteBuffer could implement a proper iterator interface, but this will be more boilerplate, which is not necessarily a good thing.

This simple modification will allow to remove evil (to non PB users) friend declarations of this sort: https://github.com/grpc/grpc/blob/f257562786f91b6c61ec20885f6022580a5c1640/include/grpcpp/impl/codegen/byte_buffer.h#L184-L185

Because, why PBs are made special and every other message format is supposed to linger in the cold? :-)

**Comment by veblush** [comment]
I don't think that I have context on this issue. Vijay, can you help me this issue? and @oakad, can you elaborate this a little bit more?

**Comment by oakad** [comment]
I want to use GRPC with flatbuffers. The project I'm working on has flatbuffers pretty ingrained in it, so not feasible to switch to something else. To this end, I need to implement a custom `SerializationTraits<flatbuffers::grpc::Message<T>>` class, which happens to have a `Deserialize` method, like outlined below (a big chunk of lame-ish code with a `thread_local` vector to top it up).

This is simply not right. The proposed change in this issue will allow to implement the same in much nicer fashion with less lines and confusing checks.

To solve the very same problem with Protobufs, the PB traits were simply given friend access to ByteBuffer internals.

```
        static thread_local std::vector<::grpc::Slice> sliceVec;

	static ::grpc::Status Deserialize(
		::grpc::ByteBuffer *buffer,
		flatbuffers::grpc::Message<T> *msg
	) {
		if (!buffer)
			return ::grpc::Status(
				::grpc::StatusCode::INTERNAL, "No payload"
			);

		auto bufferCleaner = [](::grpc::ByteBuffer *b) {
			b->Clear();
		};
		std::unique_ptr<
			::grpc::ByteBuffer, decltype(bufferCleaner)
		> bufferGuard(buffer, bufferCleaner);

		auto sliceCleaner = [](decltype(sliceVec) *v) {
			v->clear();
		};
		std::unique_ptr<
			decltype(sliceVec), decltype(sliceCleaner)
		> cleanerGuard(&sliceVec, sliceCleaner);

		auto rc(buffer->Dump(&sliceVec));
		if (!rc.ok())
			return rc;

		::grpc::Slice msgSlice;
		switch (sliceVec.size()) {
		case 0:
			return ::grpc::Status(
				::grpc::StatusCode::INTERNAL, "No payload"
			);
		case 1:
			msgSlice = sliceVec[0];
			break;
		default: {
			msgSlice = Slice(buffer->Length());
			auto p(msgSlice.begin());
			for (auto &s: sliceVec) {
				memcpy(
					const_cast<uint8_t *>(p),
					s.begin(),
					s.size()
				);
				p += s.size();
			}
		}
		}

		*msg = flatbuffers::grpc::Message<T>(
			msgSlice.c_slice(), false
		);
#if FLATBUFFERS_GRPC_DISABLE_AUTO_VERIFICATION
		return ::grpc::Status::OK;
#else
		if (msg->Verify()) {
			return ::grpc::Status::OK;
		} else {
			return ::grpc::Status(
				::grpc::StatusCode::INTERNAL,
				"Message verification failed"
			);
		}
#endif
	}
```

**Comment by oakad** [comment]
Just to give credit where it's due: flatbuffers do have an existing implementation of the above in their repo, but it's based on "plain C" grpc_* calls and thus not compatible with newer versions of GRPC library.

**Comment by veblush** [comment]
@vjpai Friendly ping :smile:

**Comment by oakad** [comment]
Right now, the gRPC introduction states the following:

> By default, gRPC uses protocol buffers as the Interface Definition Language (IDL) for describing both the service interface and the structure of the payload messages. It is possible to use other alternatives if desired.

However, in reality, other alternatives are rather difficult to use due to the unnecessarily restrictive C++ API. If there is no desire to change this situation, may be update the docs to state "gRPC is protobufs only" and we will go elsewhere. :-)

**Comment by vjpai** [comment]
Hi there,

Thanks for the feature request. We had previously looked at making BB iterable but as you mentioned, it's a lot of boilerplate to get right and we never continued with it. This FR might be a little more actionable for us. Can you give a concrete example of how you would _like_ to use the proposed API? That would give us a testable code-snippet that we could use as a dev target.

**Comment by oakad** [comment]
We used to have the C api - it was ok and it was usable. So, I will answer a question with a question: let's say you need to use some other message format for your grpc setup, not protobufs. How would you go implementing this with the current C++ api?

Granted, the above is easy to achieve in most "managed memory" languages. But, I'm looking specifically at C++.

**Comment by vjpai** [comment]
I'm happy to engage in feature request discussions and implementations, to review design documents, to present my own design documents, etc., but I don't have the cycles to propose a design for a feature that I have no intention of using. Which is why I asked [my question above](https://github.com/grpc/grpc/issues/23120#issuecomment-737427133) - can you give a concrete example of the usage of the proposed API so that we can evaluate it and potentially use it as a development target? Any addition to the C++ API would need to go through a gRFC so I'd personally like a sign of commitment and support before moving forward on this.

**Comment by oakad** [comment]
We must establish the reasoning for the current state of affairs, aren't we?

So, you've got `SerializationTraits::Deserialize` method which is supposed to read the `ByteBuffer`. Alas, presently `ByteBuffer` has no public methods for reading (ignoring the horrible `Dump` for a second). Given the current API, how one is supposed to read the passed in `ByteBuffer` (again, see my example above - it's quite bad as it is)?

Why we can not have a method which allows us to look at the slice pointers one by one (as described in my OP)? Or, why `ByteBuffer` can not implement the forward iterator trait with "const pointer to slice" value type?

Which other library on this planet requires a pointer to `vector<T, StdAlloc>` passed in for mere reading in the server hot path?

**Comment by vjpai** [comment]
Please feel free to submit a gRFC with your API proposal and usage example. Thanks.

**Comment by nicolasnoble** [comment]
@oakad the reasoning for the current state of affairs is that this wasn't a priority to get this path to be really fast and optimal, because this isn't our primary use case. Call it an afterthought if you will.

We're open to suggestions and improvements, but we're not really clear in there what you'd ultimately want to see and the end result. There's a difference between pointing at code saying "this is bad", and offering a fuller picture of a proposed change, showing both ends of the changes, in gRPC's API, and in user code. Just pointing at the gRPC API saying "change this" doesn't properly explain the how, nor how the end users would need to adapt their own code in consequences to the change.

**Comment by oakad** [comment]
#20594 <- suppose it will be better to put everything under one issue.
