### ISSUE TITLE
PHP xDS tests broke after switching to xds:///

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#23123]
PHP xDS tests dashboard: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_php

Seems to consistently break after #23105. That PR switches the tests from `xds-experimental:///` to `xds:///`.

I did some debugging and added some debug statements to the PHP tests. 

If I leave it as `xds:///`, when PHP client is making the `$stub->UnaryCall()`, it fails with code = 14 and details = "DNS resolution failed".

But if I switch it back to `xds-experimental:///`, the tests passed again.

Ruby seems to be fine switching to `xds:///`. I have not much idea why this is only happening to PHP.

cc @ericgribkoff

**Comment by markdroth** [comment]
The "DNS resolution failed" message implies that the code is actually falling back to the DNS resolver, presumably because it doesn't know about the xds resolver.  I have no idea why this might be; the xds resolver is clearly present in core, as evidenced by the fact that it's working in the other languages.

Is it possible that PHP is somehow not building from the most recent snapshot of C-core?

**Comment by stanley-cheung** [comment]
ohhhhhh this is interesting. No wonder I couldn't reproduce locally. Here's what's possible that happened.

- When I test locally, I re-compile C-core all the time.
- This kokoro test, which broke, is based off on a docker image off the `tools` directory. That's a snapshot in the past that wasn't rebuilt every time. That could be the reason.

Let me look into that direction. Thanks for the pointer!

**Comment by markdroth** [comment]
I think our tests should always build C-core from head.

**Comment by stanley-cheung** [comment]
Agreed - this could be an interesting way to expose a bug in how the PHP tests were constructed. Looking into fixing that.

**Comment by stanley-cheung** [comment]
Should be fixed in #23126. Will keep an eye on the new set of tests results.
