### ISSUE TITLE
Does ClientStreamingInterface need Close interface?

### ISSUE THREAD

**Issue by rhettdyao** [grpc/grpc#23130]
In example/cpp/route_guide/route_guide_client.cc, if I write many message to server, but I read slow. if I want to stop read, it will be very complex. 

example 1: writer.join() will be blocked because no stop signal; stream->Finish() will be blocked because not all messages be read.

  _void RouteChat() {
    ClientContext context;

    std::shared_ptr<ClientReaderWriter<RouteNote, RouteNote> > stream(
        stub_->RouteChat(&context));

	size_t count = 10000000;
    std::thread writer([stream]() {
	  	for(size_t i = 0; i < count; i++){
			RouteNote note = MakeRouteNote("First message", i, 0);
			if(!stream->Write(note)){
				break;
			}
		}
		stream->WritesDone();   
    });

    RouteNote server_note;
	size_t c;
    while (stream->Read(&server_note)) {
      std::cout << "Got message " << server_note.message()
                << " at " << server_note.location().latitude() << ", "
                << server_note.location().longitude() << std::endl;
	  sleep(5);
	  if(c++ > 100){
		break;
	  }
    }
    writer.join();
    Status status = stream->Finish();
    if (!status.ok()) {
      std::cout << "RouteChat rpc failed." << std::endl;
    }
  }_

example2: stream->Finish() will be blocked because not all messages be read.
  _void RouteChat() {
    ClientContext context;

    std::shared_ptr<ClientReaderWriter<RouteNote, RouteNote> > stream(
        stub_->RouteChat(&context));

	size_t count = 200;
    std::thread writer([stream]() {
	  	for(size_t i = 0; i < count; i++){
			RouteNote note = MakeRouteNote("First message", i, 0);
			if(!stream->Write(note)){
				break;
			}
		}
		stream->WritesDone();   
    });

    RouteNote server_note;
	size_t c;
    while (stream->Read(&server_note)) {
      std::cout << "Got message " << server_note.message()
                << " at " << server_note.location().latitude() << ", "
                << server_note.location().longitude() << std::endl;
	  sleep(5);
	  if(c++ > 100){
		break;
	  }
    }
    writer.join();
    Status status = stream->Finish();
    if (!status.ok()) {
      std::cout << "RouteChat rpc failed." << std::endl;
    }
  }_

**Comment by markdroth** [comment]
This isn't the right forum for user questions.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
