### ISSUE TITLE
grpc 1.29.0 , xcode archive with Error: Multiple commands produce gRPCCertificates.bundle

### ISSUE THREAD

**Issue by jiangguangpeng** [grpc/grpc#23131]
After I updated grpc from 1.23.0 to 1.29.0, xcode archive with Error: Multiple commands produce gRPCCertificates.bundle.
Showing All Messages:
Multiple commands produce '/Users/youxiuqingnianlindingding/Library/Developer/Xcode/DerivedData/Blued2015-gfdmkqyhlrdtfegtvezrrwsjguzx/Build/Intermediates.noindex/ArchiveIntermediates/Blued2015/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle':
1) Target 'gRPC-GRPCCore-Interface-Interface-Legacy-gRPCCertificates' has create directory command with output '/Users/youxiuqingnianlindingding/Library/Developer/Xcode/DerivedData/Blued2015-gfdmkqyhlrdtfegtvezrrwsjguzx/Build/Intermediates.noindex/ArchiveIntermediates/Blued2015/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle'
2) Target 'gRPC-gRPCCertificates' has create directory command with output '/Users/youxiuqingnianlindingding/Library/Developer/Xcode/DerivedData/Blued2015-gfdmkqyhlrdtfegtvezrrwsjguzx/Build/Intermediates.noindex/ArchiveIntermediates/Blued2015/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/gRPCCertificates.bundle'

and I found a same Issue: [https://github.com/grpc/grpc/issues/21608#issue-546613525](url)

**Comment by yulin-liang** [comment]
@jiangguangpeng Can you describe your environment, like Xcode version and Mac OS version etc.

**Comment by jiangguangpeng** [comment]
> @jiangguangpeng Can you describe your environment, like Xcode version and Mac OS version etc, and paste the whole error log?
> 
> Can you also try to delete your **Pods** directory and **~/Library/Developer/Xcode/DerivedData**, install it again to see if it works.

Xcode : 11.5
Mac OS : 10.15.4

I think it's because XCOED upgrades the new Build system. After I changed xcode build system to Legacy Build System，that's it.

> The new build system has stricter checks for cycles between elements in the build in order to prevent unnecessary rebuilds.

> It is an error for any individual file in the build to be produced by more than one build command. For example, if two targets each declare the same output file from a shell script phase, factor out the declaration of the output file into a single target.

**Comment by yulin-liang** [comment]
We only generate this file once, https://github.com/grpc/grpc/blob/master/gRPC.podspec#L137.

**Comment by jiangguangpeng** [comment]
> We only generate this bundle resource once, https://github.com/grpc/grpc/blob/master/gRPC.podspec#L137.
> 
> You can take a look at this similar issue: [firebase/firebase-ios-sdk#2102](https://github.com/firebase/firebase-ios-sdk/issues/2102).
> Have you tried to delete your Pods directory and ~/Library/Developer/Xcode/DerivedData and install again?

I've tried it, but it doesn't work.
I found no problems with version 1.23.0, but problems with versions after 1.26.0.

**Comment by jiangguangpeng** [comment]
@yulin-liang The attachment is the archive log, hope it is useful！
[Archive Blued2015_2020-06-05T10-57-55.txt](https://github.com/grpc/grpc/files/4734972/Archive.Blued2015_2020-06-05T10-57-55.txt)

**Comment by yulin-liang** [comment]
@jiangguangpeng Thanks for providing the archive log, I noticed that you had a weird **gRPC-GRPCCore-Interface-Interface-Legacy** target, which generated the **gRPCCertificates.bundle** one more time.  Can you paste your **grpc related podspec** code here?

Can you also help me check how many **gRPCCertificates.bundle** do you have, and their **target membership**?
![1](https://user-images.githubusercontent.com/64815511/83920359-048ff200-a731-11ea-9925-cb2230c4f38b.jpg)

**Comment by jiangguangpeng** [comment]
@yulin-liang Thank you for your feedback. There are really two gRPCCertificates. Bundle. We just replaced the VERSION of GRPC without any other changes. I don't know how this happened. Attached are the spec file, SH file and some screenshots, hope it is useful！
[files.zip](https://github.com/grpc/grpc/files/4743399/files.zip)

**Comment by yulin-liang** [comment]
Thanks @jiangguangpeng , I guess the issue is caused by the following line in your **Pods-NotificationPush-resources.sh**:
`install_resource "${PODS_CONFIGURATION_BUILD_DIR}/gRPC-GRPCCore-Interface-Interface-Legacy/gRPCCertificates.bundle"`

Can you try to replace it with `install_resource "${PODS_CONFIGURATION_BUILD_DIR}/gRPC/gRPCCertificates.bundle"`.

**Comment by jiangguangpeng** [comment]
@yulin-liang Thank you! 
I tried, but it didn't work. I think the key question is why ‘’**gRPC-GRPCCore-Interface-Interface-Legacy‘**’ target is generated in gRPC! The screenshot shows the differences between versions 1.23 and 1.28. 
This problem occurred after the GRPC version was upgraded. I have no problem using version 1.23.0 for the same environment. Has the new version changed anything? 
 I think some changes in the upgrade caused the problem.

<img width="344" alt="截屏2020-06-09 上午9 19 23" src="https://user-images.githubusercontent.com/5679548/84096317-3906f500-aa34-11ea-8b34-0ac199483dd7.png">
<img width="516" alt="截屏2020-06-09 上午9 38 17" src="https://user-images.githubusercontent.com/5679548/84096684-1de8b500-aa35-11ea-9c82-e22f25cec4e2.png">

**Comment by yulin-liang** [comment]
Feels like it is a bug of **Cocoapods**, because  **Blued2015** and **NotificationPush** targets both use **grpc 1.29.0**, but only **Pods-NotificationPush-resources.sh** add **gRPCCertificates.bundle** into **gRPC-GRPCCore-Interface-Interface-Legacy**.

Which version of Cocoapods do you use? 

Can you also paste the grpc related code in the **Blued2015** and **NotificationPush** targets?

**Comment by jiangguangpeng** [comment]
@yulin-liang CocoaPods version :  1.9.1.
I was puzzled. If we assumed it was for CocoaPods, why didn't we have a problem with Version 1.23.0?
[files-2.zip](https://github.com/grpc/grpc/files/4755608/files-2.zip)

**Comment by yulin-liang** [comment]
Since we changed the target of ** gRPCCertificates** in [1.24.0](https://github.com/CocoaPods/Specs/blob/master/Specs/1/2/a/gRPC/1.24.0/gRPC.podspec.json), here's [1.23.0](https://github.com/CocoaPods/Specs/blob/master/Specs/1/2/a/gRPC/1.23.0/gRPC.podspec.json). but you can see, we don't `gRPC-GRPCCore-Interface-Interface-Legacy` target in our podspec.

Can you also paste the grpc related code in the Blued2015 and NotificationPush targets?

**Comment by SarielTang** [comment]
I found this sentence in podspec
"ss.dependency "#{s.name}/Interface-Legacy", version"
Will it be related to this?

**Comment by yulin-liang** [comment]
But the problem is that **Blued2015** and **NotificationPush** use the same podspec(1.29.0), why the target of **gRPCCertificates.bundle** is different, which causes the issue, right? So I'm curious about the way you import the grpc library into these targets, can you paste related code?

**Comment by SarielTang** [comment]
The above attachment files-2.zip is podfile

**Comment by yulin-liang** [comment]
@SarielTang @jiangguangpeng Thanks for all these information. This is likely an instance of the CocoaPods issue - https://github.com/CocoaPods/CocoaPods/issues/8206#issuecomment-432314637.

I think you'd better also file a Cocoapods issue.

**Comment by jiangguangpeng** [comment]
@yulin-liang **Thank you very much for your advice and help!** We have now fixed the problem. We modified the Podfile to  specific dependent version in both target, and the problem was solved!

<img width="314" alt="截屏2020-06-11 下午1 55 46" src="https://user-images.githubusercontent.com/5679548/84350427-d6585980-abeb-11ea-9b4d-01413434d3f0.png">
<img width="520" alt="截屏2020-06-11 下午1 56 33" src="https://user-images.githubusercontent.com/5679548/84350444-dbb5a400-abeb-11ea-89ed-11661f0e258c.png">

**Comment by yulin-liang** [comment]
@jiangguangpeng That's great, thanks for your update!
