### ISSUE TITLE
Breaking change with compression/max receive length in latest gRPC version

### ISSUE THREAD

**Issue by nycdotnet** [grpc/grpc#23149]
### What version of gRPC and what language are you using?
I am using C# and have an issue that reproduces on the Grpc 2.29.0 NuGet package (latest), but does not reproduce with 2.28.1 or below.  I originally opened [this issue](https://github.com/grpc/grpc-dotnet/issues/936) in the grpc-dotnet repo, but @JamesNK suggested it should be opened here.

### What operating system (Linux, Windows,...) and version?
Windows 10 x64 and Linux Docker (`FROM mcr.microsoft.com/dotnet/core/runtime`, etc.)

### What runtime / compiler are you using (e.g. python version or version of gcc)
The issue repros on .NET Core 2.1 using the C# gRPC quickstart.  We originally found this issue using .NET Core 3.1 in a test environment at work.

### What did you do?
Follow the instructions for the C# Quick Start, but before running everything, update the Grpc and Grpc.Tools NuGet packages to 2.29.0.  Also, change the GreeterClient Program.cs Main method to this, which sends a 4 MB `name` to the server using a client that opts-in to request compression:

```csharp
public static void Main(string[] args)
{
	Channel channel = new Channel("127.0.0.1:50051", ChannelCredentials.Insecure, new ChannelOption[] {
	  new ChannelOption(ChannelOptions.MaxReceiveMessageLength, 8 * 1024 * 1024) //plenty of room
	});

	var client = new Greeter.GreeterClient(channel);

	var reply = client.SayHello(new HelloRequest { Name = new string('A', 4 * 1024 * 1024) },
	  new Metadata { { "grpc-internal-encoding-request", "gzip" } });
	Console.WriteLine("Greeting: " + reply.Message);

	channel.ShutdownAsync().Wait();
	Console.WriteLine("Press any key to exit...");
	Console.ReadKey();
}
```

Run the server and run the client as instructed by the quickstart.  You will get an exception.

Kill the server.  Downgrade the Grpc and Grpc.Tools NuGet packages to 2.28.1.  Run the server and the client again.  The client will print out a response from the server.

### What did you expect to see?
I expected that the client would compress the request via gzip (based on using the `grpc-internal-encoding-request` header).  Because the request is all "A", it should compress very well with gzip, and therefore be well under the gRPC default max message receive size of 4 MB.  This has been the behavior of gRPC with .NET for at least the last year or so, probably longer.

### What did you see instead?
With the 2.29.0 NuGet, the server returns a gRPC error which the client presents as `Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=ResourceExhausted, Detail="Received message larger than max (4194309 vs. 4194304)")`.  With 2.28.1 and earlier, everything works fine and the client prints out several screens of "A" to the console.

### Anything else we should know about your project / environment?
We've been using gRPC in prod for several years now.  This appears to have been an undocumented breaking change from 2.28.1 to 2.29.0.  I suspect it may be related to the work in this PR  https://github.com/grpc/grpc/pull/22575  ?  The cause may be just as simple as having reversed the order in which the checks for max message size are made, possibly to work around zip bombs?

I'd like clarity on if this breakage was an intentional change and therefore if we should be setting a higher max receive size even if using compression.  Whether this change was intentional or not, I would also like to request that the consensus of "how compression relates to max receive and send size" be documented in here, as it's not mentioned: https://github.com/grpc/grpc/blob/master/doc/compression.md  I am willing to make that PR.

I also suppose I expected to see a note about a breaking change here or here https://github.com/grpc/grpc-dotnet/releases  https://github.com/grpc/grpc/releases  If this was indeed intentional, I'd like to request that a note be added.

Thank you all so much for your hard work on this library.

**Comment by jtattermusch** [comment]
@yashykt  is this related to the change https://github.com/grpc/grpc/pull/22575 (as mentioned by the user) - from the description it seems that it might be likely? If so, can you please respond to user's concerns?
