### ISSUE TITLE
AsyncNext throws Segment fault.

### ISSUE THREAD

**Issue by mercury0114** [grpc/grpc#23147]
I posted a question to stack-overflow regarding the potential bug of AsyncClient Next() function:

https://stackoverflow.com/questions/62211126/why-grpc-asyncclient-throws-segfault-when-waiting-for-the-next-result-in-the-com

I read that this was an issue of older grpc version. Could it be that the bug still exists in later grpc versions? I am using version 1.23.1 in my project.

**Comment by veblush** [comment]
Jan, can you take a look at this issue? 

@mercury0114 Can you please verify if this is reproducible with the latest gRPC?

**Comment by mercury0114** [comment]
That issue is not resolved.
