### ISSUE TITLE
Make use of uris consistent across implementations

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2314]
It's important that services be able to publish a single canonical string that all clients can use to connect to that service.

ObjC currently uses a bastardized HTTP/HTTPS scheme to determine whether to start SSL or not. This should be moved to passing a credentials object and a grpc style target string.

**Comment by jcanizales** [comment]
What's a "a grpc style target string" and how doesn't it work with the ObjC library?

**Comment by ctiller** [comment]
grpc uses URI's to specify targets... there's a brief write-up at https://github.com/grpc/grpc/tree/master/src/core/client_config that I hope to expand upon as time permits.

These are not http:// and https://, so services publishing their target strings will currently have to provide a differently encoded string for Objective-C clients. The string you're passing as 'host' now is actually able to be a full URI, and all users of grpc api's should need to do is pass in that target string. There should be zero code in the Objective-C wrapper trying to interpret or mutate the string.

**Comment by jcanizales** [comment]
Can you clarify with examples what types of URIs the C core will now start or stop supporting, w.r.t. what it supported before those changes? Specifically, will it now stop supporting "myapidomain.com:port", without a scheme?

> so services publishing their target strings will currently have to provide a differently encoded string for Objective-C clients

In what cases will a service want to publish its target as "unix:..." or "dns:///..."?

**Comment by jcanizales** [comment]
Fixed in PR #2758.
