### ISSUE TITLE
Stream request got cancelled every second

### ISSUE THREAD

**Issue by ikecao** [grpc/grpc#23152]
### What version of gRPC and what language are you using?
2.24.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.net framework

### What did you do?
I created a long running stream request. The client keeps writing data into the stream while the server keeps reading data from the stream. The volume of the data depends on the user request volume. 

### What did you expect to see?
The server can keep receiving data successfully and the client can keep sending data successfully

### What did you see instead?
When the load is high, the client got RpcException every second and had to recreate the stream request. However the request can only work for up to one second and then fail again.

This is the exception received at client side.
Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

When the volume is not high, the error does not happen and a stream can keep working for a long time

**Comment by jtattermusch** [comment]
How many concurrent RPC do you have in total? There's a configurable limit on how many concurrent RPCs you can have.
It would be easier if you could provide a simple project that reproduces the issue (e.g. as a github repo).

**Comment by jtattermusch** [comment]
Closing as there was no response from the reporter.
