### ISSUE TITLE
C# Grpc.Core: Detect binding redirect problems on startup

### ISSUE THREAD

**Issue by vivainio** [grpc/grpc#23167]
### Is your feature request related to a problem? Please describe.

You'll sometimes see crashes caused by missing binding redirects. Example:

https://github.com/grpc/grpc/issues/21406

The crash is hard to find because you don't get an exception at start. Rather, you need to have GRPC_VERBOSITY set, otherwise you just see RpcException("Cancelled") on client side, with no server side call stacks.

### Describe the solution you'd like

When the server is started, we should check the references and raise exception immediately.

Here's an example doing just that:

https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/5ae5fe451c4f71a618c4324f62c3beb2dc0b39a5/src/Pipelines.Sockets.Unofficial/Helpers.cs#L142-L172

**Comment by jtattermusch** [comment]
Could you provide an example project that suffers from missing binding redirect? (e.g. as a github repo). I personally have never run into this problem.

**Comment by vivainio** [comment]
I have no reproduction available at this time (as it always happened with our large projects). I may provide one at a later date

**Comment by vivainio** [comment]
I have a separate nuget package "AssyCheck" that solves this: https://github.com/vivainio/AssyCheck

Closing this as separate fix for grpc is not required, hopefully the bug report still serves as a tip for future googlers.
