### ISSUE TITLE
grpc build fails due to "error: only virtual member functions can be marked 'override'" and "use of undeclared identifier 'FEATURE_PROTO3_OPTIONAL'"

### ISSUE THREAD

**Issue by gorakhargosh** [grpc/grpc#23184]
### What version of gRPC and what language are you using?
Language: C++
GRPC version: git commit 80e834abab5dff45e16e9a1e3b98f20eae5f91ad

### What operating system (Linux, Windows,...) and version?
1. Mac OS X 10.15.5
2. ClearLinux with Linux kernel 5.6.17-960 x86_64  

### What runtime / compiler are you using (e.g. python version or version of gcc)
1. clang 11.0.3
2. gcc 10.1.1

### What did you do?
Tried to build an example grpc service based on the proto definitions here:
[C++ quickstart](https://grpc.io/docs/languages/cpp/quickstart/)

I included GRPC in a Bazel WORKSPACE file as follows:
```
grpc_version = "80e834abab5dff45e16e9a1e3b98f20eae5f91ad"

git_repository(
    name = "com_github_grpc_grpc",
    commit = grpc_version,
    remote = "https://github.com/grpc/grpc.git",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

```

Bazel configuration follows:

```
build --verbose_failures
build --cxxopt='-std=c++17'
build --cxxopt='-Wall'
build --cxxopt='-Wextra'
build --cxxopt='-Wpedantic'
build --cxxopt='-Werror=unused'
build --cxxopt='-Werror=uninitialized'
build --compilation_mode=dbg
build --strip=never

```

### What did you expect to see?
A complete build without errors.

### What did you see instead?
```
INFO: Analyzed 104 targets (0 packages loaded, 0 targets configured).
INFO: Found 104 targets...
...
Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_github_grpc_grpc/src/compiler/cpp_plugin.cc:21:
In file included from external/com_github_grpc_grpc/src/compiler/cpp_plugin.h:29:
In file included from external/com_github_grpc_grpc/src/compiler/protobuf_plugin.h:24:
In file included from external/com_github_grpc_grpc/src/compiler/python_generator_helpers.h:29:
external/com_github_grpc_grpc/src/compiler/python_generator.h:47:41: error: only virtual member functions can be marked 'override'
  uint64_t GetSupportedFeatures() const override;
                                        ^~~~~~~~
In file included from external/com_github_grpc_grpc/src/compiler/cpp_plugin.cc:21:
external/com_github_grpc_grpc/src/compiler/cpp_plugin.h:37:41: error: only virtual member functions can be marked 'override'
  uint64_t GetSupportedFeatures() const override {
                                        ^~~~~~~~~
external/com_github_grpc_grpc/src/compiler/cpp_plugin.h:38:12: error: use of undeclared identifier 'FEATURE_PROTO3_OPTIONAL'
    return FEATURE_PROTO3_OPTIONAL;
           ^
3 errors generated.
INFO: Elapsed time: 2.072s, Critical Path: 1.95s
INFO: 10 processes: 10 darwin-sandbox.
FAILED: Build did NOT complete successfully

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gorakhargosh** [comment]
It appears this commit may have broken it:

https://github.com/grpc/grpc/commit/eccbac34438390948138160d3b9a08205d7d638a

**Comment by stanley-cheung** [comment]
This is a new feature we just introduced. But `@com_github_grpc_grpc//bazel:grpc_deps.bzl` should have tried to pull in the `3.12.2` version of protobuf, as seen [here](https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L154). I am not sure what the disconnect here seems to be. But can you check if the protobuf dependencies have been pulled in correctly?

**Comment by gorakhargosh** [comment]
The problem was that my WORKSPACE file contained an additional conflicting reference to rules_proto and protobuf elsewhere. Removing those while only retaining the GRPC reference appears to have addressed the issue. Closing the bug.

Thank you for the hint! Cheers.
