### ISSUE TITLE
BasicTests Python MacOS on pull-requests failing for several hours

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#23188]
Tests have been nearly all red since 10 AM on June 11.

### What version of gRPC and what language are you using?

Head, PRs, Python

### What operating system (Linux, Windows,...) and version?

MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)

CI platform

### What did you do?

Tried to create a PR

### What did you expect to see?

Green test

### What did you see instead?

Red tests for several hours according to https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_python

**Comment by vjpai** [comment]
Seems to be obsolete and fixed already.

**Comment by gnossen** [comment]
The new version of the RSA package apparently did not fix the issue. Looking into this now.

**Comment by gnossen** [comment]
Related: 
 - https://github.com/googleapis/google-auth-library-python/pull/528
 - https://github.com/sybrenstuvel/python-rsa/issues/152

**Comment by donnadionne** [comment]
I also see linux python failing; same issue?

**Comment by sybrenstuvel** [comment]
I fixed it in the Python-RSA package so that package managers now know which version they can use. Python-RSA 4.3 is now the last one to support Python 2.7, version 4.4 explicitly requires Python 3.5+.

**Comment by gnossen** [comment]
Resolved by #23197
