### ISSUE TITLE
Validating server certificates against the system's trust store

### ISSUE THREAD

**Issue by hkparker** [grpc/grpc#23194]
### Is your feature request related to a problem? Please describe.

I can't tell if this is a missing feature, if it's just undocumented, or if there's something I'm missing that explains why this isn't done.  I haven't been able to find any examples or documentation anywhere of how to do this.

I'd like to use gRPC to connect to a server that presents a valid certificate trusted by my system's trust store ala HTTPS.  This lets me create a client that uses TLS without having to manually  configure the server's certificate, and to update the server certificate as I see fit.  The primary use case is a publicly available gRPC API.  This seems like pretty obvious behavior to me so I'm surprised I don't see it anywhere.  Is there a reason this cannot be supported that I'm missing?

### Describe the solution you'd like

The default behavior of TLS clients, when no server certificate is defined, should be to check the system's trust store in the same way HTTPS does, I would think.

**Comment by jiangtaoli2016** [comment]
Right now, using system trust store is enabled by default for Linux, but not available for Windows or MacOS (due to some technical difficulties).

PS: gRPC has shipped roots (downloaded from mozilla routinely).

**Comment by hkparker** [comment]
Oh wow, ok, that's good news.  Is there an example anywhere of how this is done in python?  I'd imagine you could use a secure channel but pass `None` as the server certificate, but I have never seen that documented or discussed.

**Comment by jiangtaoli2016** [comment]
If you use `ssl_credentials = grpc.ssl_channel_credentials()` in python, it will use automatically uses the system root if app runs on Linux. 
@lidizheng Maybe you can update Python comment on root certificates?

**Comment by lidizheng** [comment]
Forwarding the documentation of [ssl_channel_credentials](https://grpc.github.io/grpc/python/grpc.html#grpc.ssl_channel_credentials):

> root_certificates – The PEM-encoded root certificates as a byte string, or None to retrieve them from a default location chosen by gRPC runtime.

I understand it is a little weird that applications have to create a channel credential without any parameter. But gRPC supports many types of credentials, SSL is one of them. So, `secure_channel` can't assume which should be the default credentials.

**Comment by hkparker** [comment]
Thank you for the help here, really appreciate it.  I'll close this, if I encounter a more specific issue with this technique I'll open an actual bug, now that I understand the intended behavior.
