### ISSUE TITLE
ObjC support for runtime #import prefixing

### ISSUE THREAD

**Issue by thomasvl** [grpc/grpc#23196]
ObjC Protobufs recently added an generation option (https://github.com/protocolbuffers/protobuf/pull/7609) to support custom prefixes on the runtime import directories. This allows better integration with build systems where Framework imports aren't used.  Please look at adding such a feature.

**Comment by thomasvl** [comment]
Note: you'll likely need two directives.  One for the path to the objc protobuf runtime, and one for the grpc ones.

**Comment by yulin-liang** [comment]
Hi @thomasvl , currently I can not get your change(protocolbuffers/protobuf#7609), should I wait until the change is released?

**Comment by thomasvl** [comment]
If you are using the ImportWriter, then you likely need an update for the api changes.  If you are doing the support all yourself, you should be able to implement it at any time.

**Comment by yulin-liang** [comment]
I see, thanks for your explanation!

**Comment by yulin-liang** [comment]
@thomasvl One more question, for the **protobuf prefix**, we only need to add it to **WKT paths**, is that right? Import paths of other files like `GPBProtocolBuffers_RuntimeSupport.h` or users created file, i.e., `message.pbobjc.h` etc, are not affected. Is that right?

**Comment by thomasvl** [comment]
Any of the public headers from the protobuf runtime, WKTs or `GPBProtocolBuffers.h`.  You shouldn't have to import any RuntimeSupport files directly.

The headers for individual proto files users have don't use this.
