### ISSUE TITLE
ObjC Update WKT generated #imports

### ISSUE THREAD

**Issue by thomasvl** [grpc/grpc#23195]
### What version of gRPC and what language are you using?

ObjC

### What operating system (Linux, Windows,...) and version?

Apple platforms

### What runtime / compiler are you using (e.g. python version or version of gcc)

n/a

### What did you expect to see?

Generated reference to the WellKnownTypes (WKTs) bundled with the ObjC Protobuf library need their import paths update.

See https://github.com/protocolbuffers/protobuf/pull/7173 for the changes made (now in a release).  This was done to hopefully fix some other problems around nested proto files.

Note: `ImportWriter` in the objc helpers might have made this transparent for you in that when the new support landing, things might have already adapted for you.  But tweaking your custom logic to match would also work.

**Comment by yulin-liang** [comment]
@thomasvl I wanna double check with you, we only need to 1) update paths of WKT files from objectivec/google/protobuf/ to objectivec/ and 2) add GPB prefix to the headers. Is that right?

**Comment by thomasvl** [comment]
Correct.

You'll need to also set your min version for protobuf to the release where we shipped this.
