### ISSUE TITLE
httpcli should return response payload as a gpr_slice

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#232]
To be mildly consistent with the rest of the codebase.

**Comment by mohamed-moanis** [comment]
I can work this one.
@ctiller Do you mean `grpc_httpcli_response` should hold a `grpc_slice` instead of the *array.

**Comment by hsaliak** [comment]
@mmoanis yes - I believe it has been renamed since the issue was published. /cc @vjpai

**Comment by ncteisen** [comment]
Stale issue, closing
