### ISSUE TITLE
libgrpc++ breaks ABI without changing the soname

### ISSUE THREAD

**Issue by AdrianBunk** [grpc/grpc#23205]
https://bugs.debian.org/955279
`
The _ZN4grpc13ClientContextC1Ev symbol for grpc::ClientContext::ClientContext() was included in
libgrpc++1 versions up to 1.17.2-1.
Since version 1.22.0-2 it is missing from that library.
`

Commit d166e38e appears to be a revert of a (partial?) soname bump for libgrpc++, such a soname bump would fix this problem.

**Comment by veblush** [comment]
Michael, can you take a look at this since your commit seems related to this issue.

**Comment by weltling** [comment]
Looks like there's no SONAME change happening in general. For example, `_ZN9grpc_impl13ServerBuilderD1Ev` has disappeared in 1.31.x. But then, the `grpc_impl` namespace has been sequentially removed in the follow up versions. Still it's the same SONAME, while a breach is introduced at least in every minor version of `libgrpc++`. That's an issue that makes sequential upgrades with side-by-side grpc versions very hard.

Thanks.

**Comment by veblush** [comment]
One thing I want to add here is that gRPC++ doesn't guarantee ABI compatibility. (It keeps API compatibility, though) Hence, having gRPC++ as a pre-built package isn't a good idea in general.

**Comment by weltling** [comment]
Thanks for the check. Yeah, the API compat is fine, and for the ABI there are two POVs. If it is about just a consuming project and especially a one that is distributed as a source or that links statically - yeah, the API compatibility in GRPC is good enough. However, if it's about third party binary artifacts consuming shared DSO, downstream and similar use cases where possibly side-by-side versions of GRPC can be required - that use case is currently not served. In that case, the event of the minor version change might be a milestone that could be useful to differentiate in the SONAME, as suggested in the linked PR. That would already improve the situation in several ways.

Thanks

**Comment by AdrianBunk** [comment]
> However, if it's about third party binary artifacts consuming shared DSO, downstream and similar use cases where possibly side-by-side versions of GRPC can be required - that use case is currently not served.

The original problem is actually a slightly different variant of that:
Debian (and Ubuntu) ship a shared DSO of gRPC++ that is used by several package in the distribution.
Side-by-side versions can be a bonus, the bigger point here is having proper handling of ABI changes by controlled transitions to new soname versions instead of random breakages.

**Comment by weltling** [comment]
Thanks for bringing this up. Of course, the side-by-side thing is just a subset of "keeping ABI in sync". Just as it is told officially "no ABI garantee", i thought at least suggesting a cut at a minor version might be a start. In the initial example, the breach happens between some minor versions, I'd guess ABI within the same minor version is usually more or less stable anyway. But having always the same SONAME is definitely not a good experience.

Thanks.
