### ISSUE TITLE
gRPC with .net framework

### ISSUE THREAD

**Issue by rajcool1239** [grpc/grpc#23208]
While we want to move to .net core in the future, we would like to use grpc with .net framework. However this needs PEM file during service start, is there any workaround/solution that doesn't need PEM file? Also, why does gRPC with .Net core not require the PEM file and why is PEM file only needed when using gRPC with .Net framework?

```
   SslServerCredentials sslServerCredentials = new SslServerCredentials(new List<KeyCertificatePair>() { new KeyCertificatePair(certificatePem, certificateKey) }, null, false);
        Grpc.Core.Server server = new Grpc.Core.Server
        {
            Services = { service.BindService(new Server()) },
            Ports = { new ServerPort(server.Host, server.Port, sslServerCredentials) }
        };
        server.Start();
```

**Comment by jtattermusch** [comment]
This is a question, not an actionable bug/feature request. I responsed here: https://groups.google.com/g/grpc-io/c/CEr49QbmfIM/m/ybqdWvrzBwAJ.

Closing.
