### ISSUE TITLE
Build error when doing make

### ISSUE THREAD

**Issue by Jiboxiake** [grpc/grpc#23234]
I was trying install grpc on my Ubuntu VM. However, when I tried to make, I keep getting some strange errors. I tried to search on the web and I did not find it in previous issues. The errors are at the end of the messages.
[  1%] Built target absl_int128
[  2%] Built target zlibstatic
[  2%] Built target absl_log_severity
[  2%] Built target absl_dynamic_annotations
[  3%] Built target absl_spinlock_wait
[  3%] Built target upb
[  3%] Built target address_sorting
[  6%] Built target c-ares
[  7%] Built target absl_exponential_biased
[  8%] Built target ssl
[ 12%] Built target libprotobuf
[ 12%] Built target absl_time_zone
[ 12%] Built target absl_civil_time
[ 12%] Built target absl_leak_check
[ 12%] Built target absl_leak_check_disable
[ 24%] Built target crypto
[ 24%] Built target absl_city
[ 24%] Built target absl_random_seed_gen_exception
[ 24%] Built target absl_random_internal_randen_hwaes_impl
[ 24%] Built target absl_random_internal_randen_slow
[ 25%] Built target acountry
[ 25%] Built target adig
[ 25%] Built target ahost
[ 26%] Built target libprotobuf-lite
[ 27%] Built target bssl
[ 27%] Built target absl_raw_logging_internal
[ 28%] Built target zlib
[ 28%] Built target gen_percent_encoding_tables
[ 28%] Built target gen_legal_metadata_characters
[ 28%] Built target absl_periodic_sampler
[ 28%] Built target absl_scoped_set_env
[ 32%] Built target libprotoc
[ 33%] Built target absl_debugging_internal
[ 33%] Built target absl_bad_variant_access
[ 33%] Built target absl_random_internal_randen_hwaes
[ 33%] Built target absl_bad_any_cast_impl
[ 33%] Built target example64
[ 33%] Built target minigzip
[ 33%] Built target example
[ 33%] Built target absl_strings_internal
[ 34%] Built target minigzip64
[ 34%] Built target absl_throw_delegate
[ 34%] Built target absl_base
[ 35%] Built target grpc_plugin_support
[ 35%] Built target absl_bad_optional_access
[ 35%] Built target protoc
[ 35%] Built target absl_stacktrace
[ 35%] Built target absl_demangle_internal
[ 36%] Built target absl_random_internal_randen
[ 36%] Built target absl_cord
[ 37%] Built target absl_strings
[ 37%] Built target grpc_ruby_plugin
[ 37%] Built target grpc_cpp_plugin
[ 37%] Built target grpc_php_plugin
[ 37%] Built target grpc_python_plugin
[ 37%] Built target grpc_node_plugin
[ 37%] Built target grpc_csharp_plugin
[ 37%] Built target grpc_objective_c_plugin
[ 37%] Built target absl_malloc_internal
[ 37%] Built target absl_time
[ 37%] Built target absl_random_internal_seed_material
[ 37%] Built target absl_hash
[ 37%] Built target absl_random_distributions
[ 37%] Built target absl_symbolize
[ 37%] Built target absl_graphcycles_internal
[ 37%] Built target absl_str_format_internal
[ 37%] Built target absl_random_internal_pool_urbg
[ 37%] Built target absl_examine_stack
[ 38%] Built target absl_synchronization
[ 40%] Built target gpr
[ 41%] Built target absl_flags_marshalling
[ 41%] Built target absl_random_seed_sequences
[ 41%] Built target absl_random_internal_distribution_test_util
[ 41%] Built target absl_status
[ 41%] Built target absl_hashtablez_sampler
[ 41%] Built target absl_failure_signal_handler
[ 41%] Built target absl_flags_program_name
[ 41%] Built target absl_raw_hash_set
[ 41%] Built target absl_flags_config
[ 41%] Built target absl_flags_registry
[ 41%] Built target absl_flags_internal
[ 57%] Built target grpc_unsecure
[ 57%] Built target absl_flags
[ 73%] Built target grpc_cronet
[ 73%] Built target absl_flags_usage_internal
[ 93%] Built target grpc
[ 95%] Built target grpc++_unsecure
[ 95%] Built target absl_flags_usage
[ 95%] Built target grpc_csharp_ext
[ 95%] Linking CXX executable grpc_verify_jwt
[ 95%] Linking CXX executable grpc_create_jwt
[ 97%] Built target grpc++
[ 97%] Linking CXX executable grpc_print_google_default_creds_token
[ 98%] Built target gen_hpack_tables
[ 98%] Built target check_epollexclusive
[ 98%] Built target absl_flags_parse
[ 99%] Built target grpc++_alts
[ 99%] Built target grpc++_error_details
[ 99%] Built target grpc++_reflection
[ 99%] Built target grpcpp_channelz
/usr/bin/ld: libgrpc.a(ev_posix.cc.o):(.data.rel+0x78): undefined reference to `grpc_init_epoll1_linux(bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/grpc_verify_jwt.dir/build.make:119: grpc_verify_jwt] Error 1
make[1]: *** [CMakeFiles/Makefile2:1468: CMakeFiles/grpc_verify_jwt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: libgrpc.a(ev_posix.cc.o):(.data.rel+0x78): undefined reference to `grpc_init_epoll1_linux(bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/grpc_create_jwt.dir/build.make:121: grpc_create_jwt] Error 1
make[1]: *** [CMakeFiles/Makefile2:1596: CMakeFiles/grpc_create_jwt.dir/all] Error 2
/usr/bin/ld: libgrpc.a(ev_posix.cc.o):(.data.rel+0x78): undefined reference to `grpc_init_epoll1_linux(bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/grpc_print_google_default_creds_token.dir/build.make:119: grpc_print_google_default_creds_token] Error 1
make[1]: *** [CMakeFiles/Makefile2:1641: CMakeFiles/grpc_print_google_default_creds_token.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by yashykt** [comment]
There isn't much information available here. The function is defined here https://github.com/grpc/grpc/blob/1630efd8ab3d2ff4b006f1288fde1be5c29dc651/src/core/lib/iomgr/ev_epoll1_linux.cc#L1328

I suspect that there might have been a bug with the definition of the various version and platform macros. If this has not yet been fixed, please provide some instructions to reproduce this.
