### ISSUE TITLE
Can not install grpc PHP on MacOS (neither by pecl nor build from source)

### ISSUE THREAD

**Issue by TrongTran95** [grpc/grpc#23259]
Info:
- gRPC version: v1.29.1
- OS: Mac Catalina 10.15.3
- Install PHP version

Tried hours to install grpc extension (both by pecl or build from souce) but always end up with this error: 
```
/grpc/src/php/ext/grpc/byte_buffer.c:19:10: fatal error: 
      'php.h' file not found
#include <php.h>
         ^~~~~~~
1 error generated.
make: *** [byte_buffer.lo] Error 1
```

**Comment by stanley-cheung** [comment]
Do you have PHP headers installed in your system anywhere at all? If not, that would be rather difficult. In Linux, it would be an equivalent package of something like `apt-get install php7.3-dev`. In Mac, there may already be a system-installed version of PHP? In my system - I don't remember installing PHP headers separately - I have:

```
~$ sudo find /usr -name php.h
/usr/local/include/php/main/php.h
```

If you can't find any trace of `php.h` in your system, then you might need to install PHP from source first (that's a rather uncommon situation).

**Comment by stanley-cheung** [comment]
Perhaps this can help you https://donatstudios.com/MojaveMissingHeaderFiles

**Comment by TrongTran95** [comment]
> Do you have PHP headers installed in your system anywhere at all? If not, that would be rather difficult

Yes, I've used `php --version` command to check if there's php avaiable in macOS.
=>PHP 7.3.11
But when I ran `sudo find /usr -name php.h`, the result return nothing.
Then I decided to install php by brew `brew install php` and ran `sudo find /usr -name php.h` command again.
=> /usr/local/Cellar/php/7.4.7/include/php/main/php.h
After that, I've ran `sudo pecl install grpc` to install grpc but it was also failed
```
/private/tmp/pear/install/grpc/src/php/ext/grpc/byte_buffer.c:19:10: fatal error: 'php.h' file not found
#include <php.h>
         ^~~~~~~
1 error generated.
make: *** [src/php/ext/grpc/byte_buffer.lo] Error 1
ERROR: `make' failed
```

**Comment by krotovic** [comment]
I have installed php onto Catalina using Macports and I have faced the same issue. 
I have noticed this on the start of the log output:
```
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
```
And since PECL uses phpize (which is just bash script) to set the correct paths I thought that it might be problem to run `sudo pecl install ...` so I tried to run `sudo su` first and then `pecl install grpc` and it worked.

**Comment by marianoarga** [comment]
Same problem here

**Comment by JacopoKenzo** [comment]
Same problem here
`sudo su` didn't fix it..

**Comment by lemartva** [comment]
Same error here, any ideas?

**Comment by zenkog** [comment]
Same problem here.. Help!! need this urgently.

**Comment by ajaydiya** [comment]
Is the problem fixed? Having the same issue

**Comment by rok-clarifai** [comment]
Same problem here. I searched the net, I didn't find a solution. I ended up using PHP in a Docker.

**Comment by stanley-cheung** [comment]
I was able to install the `grpc` extension via `sudo pecl install grpc` on my Mac laptop with Big Sur 11.1 just now. I did compile PHP 7.4.13 from source, which might have helped.

Versions:
- Big Sur: 11.1
- PHP: 7.4.13
- pecl: 1.10.9
- phpunit: 8.5.13
- grpc.so: 1.35.0
with these I was able to run the unit tests suite fully with no errors.

I also have some other packages installed via `brew`. 

Here are some high level steps I took to compile PHP from source on my mac:

```
$ git clone https://github.com/php/php-src
$ cd php-src
$ git checkout PHP-7.4.13
$ ./buildconf --force
$ ./configure <some flags needed, see below>
$ make
$ sudo make install
```

Now the `./configure` command takes some tries to get it right. Here's what eventually worked for me:

```
$ export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/Cellar/openssl@1.1/1.1.1i/lib/pkgconfig:/usr/local/Cellar/libxml2/2.9.10_2/lib/pkgconfig
$ ./configure --with-openssl --with-zlib --with-iconv=/usr/local/Cellar/libiconv/1.16 --with-libxml
```

I might have installed these `brew` packages during my tries

```
libiconv 1.16
libxml2 2.9.10_2
openssl@1.1 1.1.1i  (this I already have installed a while ago)
re2c 2.0.3
zlib 1.2.11  (already installed previously)
```

Hope this helps.
