### ISSUE TITLE
How does the server return the corresponding data when python grpc is accessed by multiple clients

### ISSUE THREAD

**Issue by NanQiL** [grpc/grpc#23261]
when I use python grpc,I have multiple clients。Multiple clients send data to the server, and the server processes it for a long time. It requires interface operations and then returns the data to the client. At this time, the returned data is not returned to the correct client, but is returned randomly. To one of the clients, how to deal with this kind of problem, can the server reply according to the client's IP、port?

**Comment by markdroth** [comment]
This is not the right forum for user questions.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
