### ISSUE TITLE
Ability to override TLS certificate name check in C++ library

### ISSUE THREAD

**Issue by makkarpov** [grpc/grpc#23278]
### Is your feature request related to a problem? Please describe.
By default, gRPC library validates TLS certificates by matching server name to CN/SAN's. However, there are some use cases when I want to be sure that I'm talking to a correct **component** of a system, not to specific host.

Such components may be identified by specific DN, just like Kubernetes is using `O=system:masters, CN=kubernetes-admin` to authenticate clients. This authentication does not correspond with any hostname, which can be generated, auto-discovered or just be absent (IP's are good too).

Currently I didn't found any clues that it is possible in current versions of library.

### Describe the solution you'd like

Some callback that can verify identity of server cert and return outcome of verification.

### Describe alternatives you've considered

The only alternative that I see is to use host-based CN's and setup DNS resolvers accordingly.

**Comment by makkarpov** [comment]
*not stale*

**Comment by makkarpov** [comment]
_not stale_

**Comment by jiangtaoli2016** [comment]
@makkarpov You can use [TlsCredentials](
https://github.com/grpc/grpc/blob/master/include/grpcpp/security/credentials.h#L337), in this CredentialsOptions, you can config your own check per connection. You will need to config GRPC_TLS_SKIP_HOSTNAME_VERIFICATION as option to skip standard hostname check.

Does this address your issue?

**Comment by makkarpov** [comment]
Partially, since with this solution I need to reccompile gRPC and can't, for example, use pre-built binaries from repos.

**Comment by ZhenLian** [comment]
Hi Maxim,
Sorry, I don't get the reason why you can't use this API. This is a normal API in C++, except it is experimental. You don't need to use any pre-built binaries in order to use it.
I will probably note that the API is aiming to solve exactly the same problem you have encountered, but it's still experimental, and subject to change(actually it's very likely to change since we are working on a design to make it more composable). You can see the gRFC(https://github.com/grpc/proposal/pull/205, "Custom Authorization" section in particular).

**Comment by makkarpov** [comment]
@ZhenLian, If I understand correctly, `GRPC_TLS_SKIP_HOSTNAME_VERIFICATION` is a compile-time option, so library must be rebuilt when it is changed.

**Comment by jiangtaoli2016** [comment]
@makkarpov Your only option is using an old version of gprc library where TlsCredentials is not available?

If so, you can only disable hostname check.

**Comment by makkarpov** [comment]
Nevermind, I misunderstood the docs. It's ok.
