### ISSUE TITLE
Benchmarks seem broken

### ISSUE THREAD

**Issue by ncioj10** [grpc/grpc#23297]
**Issue description**
The benchmarks page does not seem to display any data for most graphs. 
I get "no data available" for all except of "Unary secure throughput QPS (32 core client to 32 core server)" and "Streaming secure throughput QPS (32 core client to 32 core server)" and those are missing the Java data.

**Steps to reproduce the issue**
1. Go to https://www.grpc.io/docs/guides/benchmarking/#overview
2. Go to https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5636470266134528 (aka multi-language performance dashboard)

**Expected behavior**
There should be benchmark data displayed. 

**Screenshots**

![no-data](https://user-images.githubusercontent.com/10393747/85482591-7be3d380-b5c3-11ea-9fed-8c970895d5c9.PNG)

**Desktop (if relevant):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by chalin** [comment]
FYI: also reported by https://github.com/grpc/grpc.io/issues/337. I've added a note to the benchmarking page (https://github.com/grpc/grpc.io/pull/339).

**Comment by jtattermusch** [comment]
Hopefully we will be able to revive the dashboard in Q4 2020. We don't plan to performance data snapshot as:
1. we'd like to focus on a long-term fix (= improve the underlying benchmarking framework) rather than manually generating performance data.
2. if you need to you can generate the data yourself by using run_performance_tests.py script (https://github.com/grpc/grpc/tree/master/tools/run_tests#performance-benchmarks-run_performance_testspy).
3. The data we publish in the dashboard are mostly informative - if you are building a performance-sensitive app, you'll need run app-specific benchmarks yourself anyway.

**Comment by kitcheung1480** [comment]
Is it because the default SQL only retrieve data from the pass 2 weeks? Try editing the SQL code to target the data to retrieve desired data.
![node_vs_python](https://user-images.githubusercontent.com/30243428/99926902-444da300-2d7e-11eb-994c-8147dd06fab1.png)

**Comment by xieus** [comment]
@kitcheung1480 Thanks for sharing. Somehow my tried your SQL query but it doesn't work out..

**Comment by xieus** [comment]
@jtattermusch I was wondering if we are getting closer to resolve this issue.

**Comment by kitcheung1480** [comment]
for your reference here:

SELECT
	summary.latency50 / 1000 as value,
    DATE_ADD(metadata.created, -8, "HOUR") as date,
    scenario.name as scenario
FROM
	[grpc-testing:performance_released.performance_experiment]
WHERE
	metadata.created >= DATE_ADD(CURRENT_TIMESTAMP(), -13, "WEEK") AND
    (scenario.name = "java_protobuf_unary_ping_pong_secure" OR
     scenario.name = "ruby_protobuf_unary_ping_pong" OR
     scenario.name = "node_protobuf_unary_ping_pong" OR
     scenario.name = "csharp_protobuf_sync_to_async_unary_ping_pong" OR
     scenario.name = "cpp_protobuf_sync_unary_ping_pong_secure" OR
     scenario.name = "go_protobuf_sync_unary_ping_pong_secure" OR
     (scenario.name = "python_protobuf_sync_unary_ping_pong") OR
     scenario.name = "netperf_tcp_rr")
     
ORDER BY
	date;

**Comment by xieus** [comment]
Thanks, @kitcheung1480  Here is the screenshot from my side. I adjusted the number of weeks, from -13, to -50, -100. No luck so far

![image](https://user-images.githubusercontent.com/12957223/102047870-ea476880-3d92-11eb-9e31-b141f6088d3e.png)

**Comment by jtattermusch** [comment]
We are still working on a new framework to run the OSS benchmarks (in a more stable a maintainable way).
Hopefully we'll have the dashboard populated by the new benchmarks in Q1 2021.
This is the repository to track https://github.com/grpc/test-infra/tree/master/benchmarks

**Comment by kitcheung1480** [comment]
> Thanks, @kitcheung1480  Here is the screenshot from my side. I adjusted the number of weeks, from -13, to -50, -100. No luck so far
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/12957223/102047870-ea476880-3d92-11eb-9e31-b141f6088d3e.png)
> 
> 

Have you press refresh afterwards?

**Comment by nikolaydubina** [comment]
Still not working. https://github.com/grpc/test-infra/tree/master/benchmarks leads to 404

**Comment by jtattermusch** [comment]
The test repo link is here: https://github.com/grpc/test-infra

**Comment by jtattermusch** [comment]
We've recently deployed a new version of GKE-based performance benchmark framework - this new version should be much more stable (and easier to maintain) than the previous one.
The new dashboard being populated by that framework is here: https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5180705743044608

https://grpc.io/docs/guides/benchmarking/ has been updated.

**Comment by nikolaydubina** [comment]
Thank you!
