### ISSUE TITLE
grpc c++ framework cost too much time ?

### ISSUE THREAD

**Issue by ljch2018** [grpc/grpc#23296]
My server codes just like these.
```
    // max threads
    grpc::ResourceQuota quota;
    quota.SetMaxThreads(server_config.max_threads());
    //builder.SetResourceQuota(quota);
    builder.SetMaxMessageSize(0x7FFFFFFF);
    //builder.SetDefaultCompressionAlgorithm(GRPC_COMPRESS_DEFLATE);
    // port 
    std::string server_address("0.0.0.0:" + std::to_string(server_config.listen_port()));
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    // service
    builder.RegisterService(&service);

    // Run Server
    std::unique_ptr<grpc::Server> server(builder.BuildAndStart());
    server->Wait();
```
I found the framework cost 70ms, event I do nothing in the service function.
Am I missing something ? Thank you.
My request size is 2M, should I setup some special configurations ?

**Comment by yashykt** [comment]
This form is not for questions. I'll still reply though - 
I'm not sure I understood your question properly. Is the concern that a single request of 2M size is taking 70ms round-trip? That sounds conceivable and depends on the network speeds. Even if you are doing nothing in the service function, gRPC would still need to send the request over and I am guessing that is where the 70ms is arising from.
