### ISSUE TITLE
Python: AttributeError: 'NoneType' object has no attribute 'cancelled'

### ISSUE THREAD

**Issue by justinvp** [grpc/grpc#23290]
### What version of gRPC and what language are you using?

Python grpcio package version 1.30.0

### What operating system (Linux, Windows,...) and version?

macOS 10.14.6

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
$ venv/bin/python --version
Python 3.7.7
```

### What did you do?

The problem happens when creating a vanilla [Pulumi](https://www.pulumi.com/docs/get-started/) Python program:

```
$ mkdir emptypytest && cd emptypytest
$ pulumi new python

...

Successfully installed dill-0.3.2 grpcio-1.30.0 protobuf-3.12.2 pulumi-2.4.0 six-1.15.0
Finished installing dependencies

Your new project is ready to go! ✨

To perform an initial deployment, run 'pulumi up'
```

### What did you expect to see?

```
$ pulumi up

Previewing update (dev):
     Type                 Name             Plan       
 +   pulumi:pulumi:Stack  emptypytest-dev  create     
 
Resources:
    + 1 to create
```

### What did you see instead?

```
$ pulumi up

Previewing update (dev):
     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  emptypytest-dev  create     8 messages
 
Diagnostics:
  pulumi:pulumi:Stack (emptypytest-dev):
    Exception ignored in: <function _ChannelCallState.__del__ at 0x1062d8290>
    Traceback (most recent call last):
      File "/Users/user/Desktop/emptypytest/venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
    AttributeError: 'NoneType' object has no attribute 'cancelled'
    Exception ignored in: <function _ChannelCallState.__del__ at 0x1062d8290>
    Traceback (most recent call last):
      File "/Users/user/Desktop/emptypytest/venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
    AttributeError: 'NoneType' object has no attribute 'cancelled'
```

After downgrading and pinning to grpcio 1.29.0, the error no longer happens:

```
$ venv/bin/pip uninstall grpcio
$ venv/bin/pip install grpcio==1.29.0
$ pulumi up

Previewing update (dev):
     Type                 Name             Plan       
 +   pulumi:pulumi:Stack  emptypytest-dev  create     
 
Resources:
    + 1 to create
```

**Comment by lidizheng** [comment]
This is fixed by https://github.com/grpc/grpc/pull/23201 and https://github.com/grpc/grpc/pull/23201. Unfortunately, they wasn't picked up by `v1.30.0`. This is a log spam during garbage collect or interpreter shutdown, and it should not affect your application's functionality.

**Comment by justinvp** [comment]
Thanks, @lidizheng. Any idea when the fix will be released? It affects all our Python users.

**Comment by lidizheng** [comment]
@justinvp We are working on a patch. We will release it shortly (depending on other fixes going into this patch).

**Comment by bollard** [comment]
Seeing the same issue. Thanks for the fix. Looking forward to the patch release

**Comment by drather19** [comment]
FYI, with the fix, I now see (in our code, not in the Pulumi example given):

```
Exception ignored in: <function _ChannelCallState.__del__ at 0x10fc66830>
Traceback (most recent call last):
  File "/Users/achu/.oc3/python-envs/oc3/lib/python3.7/site-packages/grpc/_channel.py", line 1129, in __del__
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 515, in grpc._cython.cygrpc.Channel.close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 399, in grpc._cython.cygrpc._close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 429, in grpc._cython.cygrpc._close
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 365, in notify_all
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable
```

If I print the `self.channel` reference in `ChannelCallState.__del__` just before the `close()` invocation, it returns `<grpc._cython.cygrpc.Channel object at 0x10c382690>` like we would expect, but it still errors when invoking on `self.channel`.

If I update `Channel.__del__` to call `self.close()` rather than `self._unsubscribe_all()` (line 1455), the error goes away.

**Comment by lidizheng** [comment]
@drather19 Can you try again with our daily builds? It should suppress this error. The `Channel` object can be short-lived compare to RPCs. Closing the channel when `Channel` object go out-of-scope halts ongoing RPCs.

**Comment by drather19** [comment]
> Can you try again with our daily builds? It should suppress this error. The Channel object can be short-lived compare to RPCs. Closing the channel when Channel object go out-of-scope halts ongoing RPCs.

With the daily build from [here](https://packages.grpc.io/archive/2020/07/86eb64011d952645bcad5af263d5164643021624-8fb3426e-cb5b-4849-8a83-cfc653d6f094/index.xml), I see the same issue. Seems like the reference to `self.channel.` in `_ChannelCallState` is gone when we attempt to `self.channel.close()`, but you can print it to console before the `close()` invocation for some reason.

**Comment by lidizheng** [comment]
Oh, I found the error-suppression PR was still pending... https://github.com/grpc/grpc/pull/23351.

**Comment by lidizheng** [comment]
Closing the bug for now. The fixes were in, and we improved the close logic of channel in recent releases. Feel free to reopen if the issue still exist for latest releases.
