### ISSUE TITLE
Python exception when port addition fails

### ISSUE THREAD

**Issue by mgasner** [grpc/grpc#23315]
Two previous issues (#11394 and #13096) point out that the behavior of `grpc.Server.add_insecure_port` and `grpc.Server.add_secure_port` is undocumented when port addition fails. It would be great if, in Python, an exception were raised. Right now a C++ error like the following is printed but there is no exception and so this is quite difficult to handle in Python code.

E0625 08:30:39.322084000 4616256960 server_chttp2.cc:40]               {"created":"@1593088239.322057000","description":"Only 1 addresses added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":406,"referenced_errors":[{"created":"@1593088239.322056000","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1593088239.322051000","description":"Address already in use","errno":48,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}

**Comment by mgasner** [comment]
It's unclear, I guess, whether grpc attempts to bind early (when add_insecure_port is called) or late (server.start). In either case, it'd be helpful if this were documented.

**Comment by lidizheng** [comment]
Thanks for reporting. This indeed has been an issue for years. I filed https://github.com/grpc/grpc/pull/23632 to attempt fixing it.
