### ISSUE TITLE
latest 1.30.0 release fails to build on linux

### ISSUE THREAD

**Issue by david-geiger** [grpc/grpc#23311]
Hi,

I tried on Mageia Cauldron to build latest 1.30.0 release but it fails to build with:

> In file included from ./src/compiler/python_generator_helpers.h:29,
                 from ./src/compiler/protobuf_plugin.h:24,
                 from src/compiler/python_generator.cc:35:
./src/compiler/python_generator.h:47:12: error: 'uint64_t grpc_python_generator::PythonGrpcGenerator::GetSupportedFeatures() const' marked 'override', but does not override
   47 |   uint64_t GetSupportedFeatures() const override;
      |            ^~~~~~~~~~~~~~~~~~~~
src/compiler/python_generator.cc: In member function 'uint64_t grpc_python_generator::PythonGrpcGenerator::GetSupportedFeatures() const':
src/compiler/python_generator.cc:881:10: error: 'FEATURE_PROTO3_OPTIONAL' was not declared in this scope
  881 |   return FEATURE_PROTO3_OPTIONAL;
      |          ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:2945: /home/iurt/rpmbuild/BUILD/grpc-1.30.0/objs/opt/src/compiler/python_generator.o] Error 1
make: *** Waiting for unfinished jobs....

Full build log:
[build.0.20200625044101.log](https://github.com/grpc/grpc/files/4829135/build.0.20200625044101.log)

**Comment by Manu343726** [comment]
This is broken for the CMake build in the latest release, the above PR only fixes it for the makefile build

**Comment by Manu343726** [comment]
BTW it would be nice if the minimum protobuf version required is documented somewhere, I checked both this repo and the C++ getting started manual in the official docs and there's no mention about this, it only states "Protobuf 3".

**Comment by connor-bugler** [comment]
Bump, getting this error with baze on ubuntu as well
