### ISSUE TITLE
Multi-Config Generator (VS2019) fails building helloworld C++ Example

### ISSUE THREAD

**Issue by jjELT** [grpc/grpc#23326]
# Development Environment

Applies to gRPC versions 1.29.1 and 1.30.0
Windows 10
Microsoft Visual Studio 2019
Language: C++

# Prerequisites

## Installation of gRPC

I built both the `Debug` and `Release` configurations of  gRPC via the following commands:

### Configuration

```
cmake \\
-S<GRPC_SOURCE_DIR> \\
-B<GRPC_BUILD_DIR> \\
-G"NMake Makefiles" \\
--loglevel=DEBUG \\
-DCMAKE_BUILD_TYPE=Debug \\
-DCMAKE_C_FLAGS=/DWIN32 /D_WINDOWS \\
-DCMAKE_CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc \\
-DCMAKE_C_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe \\
-DCMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe \\
-DCMAKE_INSTALL_PREFIX=<GRPC_INSTALL_DIR>
```

and same for `Release` with the changed build type value of course (`-DCMAKE_BUILD_TYPE=Release`)

### Build and Install

```
cmake --build <GRPC_BUILD_DIR>
```

## Creating a VS2019 Solution for the `helloworld` Example

```
cmake \\
-S<GRPC_SOURCE_DIR>/examples/cpp/helloworld \\
-B<HELLOWORLD_EXAMPLE_BUILD_DIR> \\
-G"Visual Studio 16 2019" \\
-A x64 \\
--loglevel=DEBUG \\
-DCMAKE_PREFIX_PATH=<GRPC_INSTALL_DIR>
```

# Problem Description

When I open the solution file created for the `helloworld` project (`<HELLOWORLD_EXAMPLE_BUILD_DIR>\HelloWorld.sln`) I can only build either the `Debug` or `Release` configuration, depending on which gRPC configuration **I built last**.

I get either this kind of error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in greeter_client.obj	greeter_client	<HELLOWORLD_EXAMPLE_BUILD_DIR>\grpc++.lib(client_context.cc.obj)	1	
... (and many more)
```

or the other way around

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '1' in greeter_client.obj	greeter_client	<HELLOWORLD_EXAMPLE_BUILD_DIR>\grpc++.lib(client_context.cc.obj)	1	
... (and many more)
```

The other build types (`MinSizeRel` and `RelWithDebInfo`) do not work either.

# Single-Config Generators Work

Using MinGW I do not get this problem. In fact I only need to build the release version of gRPC. No matter the `CMAKE_BUILD_TYPE` I use for the `helloworld` example, e.g. `Debug`:

```
cmake -B<HELLOWORLD_EXAMPLE_BUILD_DIR_MINGW> -G"MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=<PATH_TO_MY_TOOLCHAIN_FILES>/mingw64.toolchain --loglevel=STATUS -DCMAKE_BUILD_TYPE=Debug
```

it works with the `Release` version of gRPC.

# Multi-Config Generators

I know MS VS2019 is not officially supported. But I guess the problem is the same for VS2017 and VS2015. Can anyone confirm?

**Comment by nicolasnoble** [comment]
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '1' in greeter_client.obj	greeter_client	<HELLOWORLD_EXAMPLE_BUILD_DIR>\grpc++.lib(client_context.cc.obj)	1	
> ... (and many more)
> ```

I have no idea where this comes from, but it looks like a tooling mismatch on your end. I've used 2019 to compile gRPC successfully.

**Comment by jjELT** [comment]
I just ran my code again and I don't know why, but this time I could build **both** the `Debug` **and** `Release` configurations without problems. Still no luck with `MinSizeRel` and `RelWithDebInfo`, the same error as mentioned above pops up.

@nicolasnoble: Are you saying you tested all configurations in Visual Studio and all of them work for you out of the box?

# Possible Solution

In the meanwhile I have found a solution for this problem in my main project, where I am using gRPC. For `MinSizeRel` and `RelWithDebInfo` to get built, I have to [map the imported targets](https://cmake.org/cmake/help/latest/prop_tgt/MAP_IMPORTED_CONFIG_CONFIG.html) correctly.
I tried out my solution in the `CMakeLists.txt` of the `helloworld` project and with this code I can also build all configurations.

You can find the CMake function I used to fix this problem here: [RecursivelyMapImportedConfigurationOfTargets.zip](https://github.com/grpc/grpc/files/4883212/RecursivelyMapImportedConfigurationOfTargets.zip)


Here is an excerpt of the altered `examples\cpp\helloworld\CMakeLists.txt`:

```
...
# Include generated *.pb.h files
include_directories("${CMAKE_CURRENT_BINARY_DIR}")

# ==============================================================
# Fix Issue 23326 Start
# ==============================================================
# Check if MSVC is used.
if(MSVC)
	list(APPEND CMAKE_MODULE_PATH "<PATH_TO_RecursivelyMapImportedConfigurationOfTargets.cmake>")
	include(RecursivelyMapImportedConfigurationOfTargets)

	# Make sure VS2019 can build the configurations MinSizeRel and RelWithDebInfo.
	recursively_map_imported_configuration_of_targets(
			"MinSizeRel;RelWithDebInfo" 
			"Release" 
			"${_REFLECTION};${_GRPC_GRPCPP};${_PROTOBUF_LIBPROTOBUF}"
			"gRPC;protobuf"
		)
endif()
# ==============================================================
# Fix Issue 23326 End
# ==============================================================

# Targets greeter_[async_](client|server)
foreach(_target
  greeter_client greeter_server
  greeter_async_client greeter_async_client2 greeter_async_server)
  add_executable(${_target} "${_target}.cc"
    ${hw_proto_srcs}
    ${hw_grpc_srcs})
  target_link_libraries(${_target}
    ${_REFLECTION}
    ${_GRPC_GRPCPP}
    ${_PROTOBUF_LIBPROTOBUF})
endforeach()
```

**Comment by yashykt** [comment]
We took a look at this, and it seems like this issue is not specific to gRPC, and instead pertains to the workings of CMake with Visual Studio. Please comment/open a new issue if you think differently.
