### ISSUE TITLE
gRPC client calls eventually stall when connecting to a dead host

### ISSUE THREAD

**Issue by thomaspedley** [grpc/grpc#23342]
### What version of gRPC and what language are you using?
v1.25.0, C++

### What operating system (Linux, Windows,...) and version?
x86_64 Linux, Ubuntu 14.04.6 (Linux 4.4.0-148-generic), but has been observed on a Yocto distro running on an i.MX6 ARM-based single-board computer, too

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 5.2.0

### What did you do?
I created a very simple client in C++ that repeatedly calls a synchronous method on a server. The protobuf file is defined as follows:

```
syntax = "proto3";

package GrpcErr;

service TestService {
    rpc FireAndforget(FireAndForgetRequest) returns (FireAndForgetResponse);
}

message FireAndForgetRequest {
    int32 request_a = 1;
}

message FireAndForgetResponse {
    int32 response_a = 1;
}
```

The client code simply tries to repeatedly request the "FireAndForget" RPC against a remote IP address (over an internet connection) where the server is intentionally not running (and any connections are silently dropped, rather than rejected) to inspect the behaviour of the client when it cannot connect to a server. The client code is called every 100ms by a timer (though the execution blocks re-triggers of the timer, so it may take longer):

```
void FireAndForgetClient::fireAndForget() {
    ::GrpcErr::FireAndForgetRequest request{};
    ::GrpcErr::FireAndForgetResponse response;
    qCDebug(logger) << "I'll fire, then I'll forget. Count:" << count++;
    m_clientContext = std::unique_ptr<::grpc::ClientContext> {new ::grpc::ClientContext()};
    const auto timeSpan = gpr_time_from_millis(100, GPR_TIMESPAN);
    m_clientContext->set_deadline(timeSpan);

    auto status = m_stub->FireAndforget(getClientContext(), request, &response);

    // If the status indicates an issue...
    if (!status.ok()) {
        qCDebug(logger) << "Status is not ok";

        const QString errorMessage = QString::fromStdString(status.error_message());
        const QString errorDetails = QString::fromStdString(status.error_details());
        qCDebug(logger).noquote().nospace() << "gRPC request error: " << errorMessage << " - " << status.error_code() << " - " << errorDetails;
    }
    else {
        qCDebug(logger).noquote().nospace() << "Status is ok.";
    }
}
```

Only one request is attempted at a time (there are no concurrent requests).

The channel setup looks like this:
```
void ClientBootstrapper::init() {
    qCDebug(logger) << "Initialising.";
    Q_ASSERT(m_clientManager == nullptr);

    // Channel parameters (such as reconnection backoff periods).
    grpc::ChannelArguments cArgs;
    cArgs.SetInt(GRPC_ARG_INITIAL_RECONNECT_BACKOFF_MS, 100);
    cArgs.SetInt(GRPC_ARG_MAX_RECONNECT_BACKOFF_MS, 100);
    cArgs.SetInt(GRPC_ARG_MIN_RECONNECT_BACKOFF_MS, 100);
    cArgs.SetInt(GRPC_ARG_MAX_RECEIVE_MESSAGE_LENGTH, 1000);
    cArgs.SetInt(GRPC_ARG_MAX_SEND_MESSAGE_LENGTH, 1000);
    cArgs.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 1000);
    cArgs.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 2000);
    cArgs.SetInt(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 1);

    // Construct the channel and instantiate ourselves.
    const QString host = QString(m_host).append(":%1").arg(m_port);
    qCInfo(logger) << "Will connect to gRPC server at" << host;
    const auto channel = grpc::CreateCustomChannel(host.toStdString(), grpc::InsecureChannelCredentials(), cArgs);

    m_clientManager = std::make_shared<ClientManager>(channel);

    emit initialised();
    qCDebug(logger) << "Initialised.";
}
```

### What did you expect to see?
I expect to see the client retry its attempts to call "FireAndForget" on the server indefinitely, with each failing after around 100ms due to the deadline being exceeded.

### What did you see instead?
Instead, I see the client makes several attempts (roughly 100ms apart, as expected) before it is blocked for 2 minutes, after which it continues:

> 20200629 17:01:53.477 <0x638e70> >>> [debug] ClientBootstrapper: Initialising.
> 20200629 17:01:53.477 <0x638e70> >>> [info] ClientBootstrapper: Will connect to gRPC server at "x.x.x.x:1337"
> 20200629 17:01:53.477 <0x638e70> >>> [debug] ClientBootstrapper: Initialised.
> 20200629 17:01:53.584 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 0
> 20200629 17:01:53.684 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:53.685 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: Deadline Exceeded - 4 - 
> 20200629 17:01:53.687 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 1
> 20200629 17:01:53.789 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:53.789 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: Deadline Exceeded - 4 - 
> 20200629 17:01:53.793 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 2
> 20200629 17:01:53.894 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:53.894 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: Deadline Exceeded - 4 - 
> 20200629 17:01:53.894 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 3
> 20200629 17:01:53.902 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:53.902 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:01:53.994 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 4
> 20200629 17:01:54.014 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:54.014 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:01:54.093 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 5
> 20200629 17:01:54.115 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:54.115 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:01:54.193 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 6
> 20200629 17:01:54.216 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:54.216 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:01:54.293 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 7
> 20200629 17:01:54.317 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:54.317 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:01:54.392 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 8
> 20200629 17:01:54.423 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:01:54.423 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:01:54.493 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 9
> E0629 17:01:57.423179510   14873 chttp2_transport.cc:2876]   ipv4:x.x.x.x:1337: Keepalive watchdog fired. Closing transport.
> 20200629 17:04:01.673 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:04:01.673 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: Deadline Exceeded - 4 - 
> 20200629 17:04:01.673 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 10
> 20200629 17:04:01.774 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:04:01.774 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: Deadline Exceeded - 4 - 
> 20200629 17:04:01.779 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 11
> 20200629 17:04:01.880 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:04:01.880 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: Deadline Exceeded - 4 - 
> 20200629 17:04:01.883 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 12
> 20200629 17:04:01.894 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:04:01.894 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:04:01.989 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 13
> 20200629 17:04:01.994 <0x638e70> >>> [debug] FireAndForgetClient: Status is not ok
> 20200629 17:04:01.994 <0x638e70> >>> [debug] FireAndForgetClient: gRPC request error: failed to connect to all addresses - 14 - 
> 20200629 17:04:02.093 <0x638e70> >>> [debug] FireAndForgetClient: I'll fire, then I'll forget. Count: 14
> E0629 17:04:04.995437531   14873 chttp2_transport.cc:2876]   ipv4:x.x.x.x:1337: Keepalive watchdog fired. Closing transport.
> ...

This pattern of stalling and recovering after 2 minutes (shown twice above) repeats indefinitely.

Note that the keepalive watchdog firing to close the transport after the configured 2000ms period does not seem to have any effect of unblocking the attempted call.

The number of attempts between being blocked is unpredictable.

I have also had the programme segfault instead of block on two occasions. However, I have not been able to capture a coredump of this as it is a very rare occurrence.

If I omit setting the following channel arguments, then I do not experience this behaviour. However, the time required to reconnect to the server when it becomes available is then unpredictable (as expected, but unacceptable for my project):

```
    cArgs.SetInt(GRPC_ARG_INITIAL_RECONNECT_BACKOFF_MS, 100);
    cArgs.SetInt(GRPC_ARG_MAX_RECONNECT_BACKOFF_MS, 100);
    cArgs.SetInt(GRPC_ARG_MIN_RECONNECT_BACKOFF_MS, 100);
```

### Anything else we should know about your project / environment?
The issue is not observed when trying to connect to localhost rather than a remote system.

**Comment by nicolasnoble** [comment]
This may be a too old version of gRPC you're using, and some similar bugs may have been fixed in the meantime. Can you retry with a more recent version of the library?

**Comment by thomaspedley** [comment]
I've tested this in my development environment and it appears to have fixed the issue. 

Sorry for not trying this earlier, but upgrading the libraries for our project beyond my development environment is not a simple endeavour.

Hopefully this issue will help people with the same issue as me as there wasn't much around online to indicate that the problem existed or was fixed that I could find.
