### ISSUE TITLE
grpc Failed to pick subchannel

### ISSUE THREAD

**Issue by changqing98** [grpc/grpc#23340]
_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1593330482.005402565","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3981,"referenced_errors":[{"created":"@1593330482.005396918","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}

python client version grpcio=1.28.1
Java server version grpc =1.16.1

Is this error caused by the different grpc version?

**Comment by nicolasnoble** [comment]
There's not nearly enough information for us to help you there. All versions of gRPC are compatible with each other however.

**Comment by nicolasnoble** [comment]
Note that this can simply mean your Internet isn't connecting properly, due to firewall, or other factors.

**Comment by XiaokangLiuCUG** [comment]
anyone solve this prbolem? I have got the same issue

**Comment by bettdouglas** [comment]
@XiaokangLiuCUG i had my code like this 
```python
from alaska_pb2_grpc import AlaskerStub
from alaska_pb2 import Feature
import grpc

if __name__ == "__main__":
    with grpc.insecure_channel('localhost:4326') as channel:
        alasker_stub = AlaskerStub(channel)

        print(channel._connectivity_state.connectivity)

        rivers = alasker_stub.GetRivers(Feature())
        for river in rivers.rivers:
```
after changing from 'localhost' to `0.0.0.0` the call to server was successful

```python
from alaska_pb2_grpc import AlaskerStub
from alaska_pb2 import Feature
import grpc

if __name__ == "__main__":
    with grpc.insecure_channel('0.0.0.0:4326') as channel:
        alasker_stub = AlaskerStub(channel)

        print(channel._connectivity_state.connectivity)

        rivers = alasker_stub.GetRivers(Feature())
        for river in rivers.rivers:
```

**Comment by bettdouglas** [comment]
@changqing98 since you closed this, could you share how were you able to fix the problem?

What happens on my side is a probabilistic one. One moment I can connect and get a response from the server(localhost) in my case and then the next I get this error. 
Changing from 0.0.0.0 or localhost doesn't fix the problem. 

Below is a stack trace.

>   File "alaska_pb_client.py", line 14, in <module>
    airports = alasker_stub.GetAirports(Feature())
  File "/home/bett/Documents/dev/python/grpc_py/venv/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/bett/Documents/dev/python/grpc_py/venv/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1605246453.178423644","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1605246453.178408343","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"

My dependencies `grpcio==1.32.0` `grpcio-tools==1.32.0`

**Comment by bettdouglas** [comment]
And also, this issue happens only to the python client(even when running the basic RouteGuide example). I have a dart client which makes the call successfully without any delays every time.

**Comment by sakthivel-chidambaram** [comment]
We noticed this issue today in an application running in Service Fabric on one node (this app runs in multiple other nodes and also in multiple other clusters). Any thoughts on the cause and mitigation?

`Status(StatusCode="Unknown", Detail="Exception calling application: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1606779601.685000000"," Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception calling application: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1606779601.685000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1606779494.919000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1606779601.686000000","description":"Error received from peer ipv4:10.0.0.5:20006","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"Exception calling application: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n`

**Comment by shelmingsong** [comment]
@bettdouglas @changqing98 @XiaokangLiuCUG @sakthivel-chidambaram 

I had the same issue today, and this problem occurs only on the python client, there is nothing wrong with my go client.

This problem stopped when I turned off the network proxy, but I don't know what the underlying cause was.

I don't know if that helps you.

```bash
unset http_proxy
unset https_proxy
```

**Comment by bettdouglas** [comment]
@shelmingsong where do you set that?

From what I've observed the last two weeks, if you don't call server.stop(0) somewhere in your program, it seems the connection is not stopped and so the port is still bound to the previous server.

I noted that python server has no way to access the port which the server is running on which causes problems even for logging purposes.

**Comment by yuyang199226** [comment]
I also has the same prolems.

```
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1608626175.496221529","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4166,"referenced_errors":[{"created":"@1608626175.496211826","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
```

but my go client can access ok

**Comment by YukiNanCC-USYD** [comment]
Anyone solve this issue?

**Comment by choopm** [comment]
@YukiNanCC-USYD @bettdouglas
You are probably failing the hostname verification, see this: https://github.com/grpc/grpc/issues/5697#issuecomment-230198556
You can also dig into it using these environment vars:
```
export GRPC_TRACE=all
export GRPC_VERBOSITY=debug
```

**Comment by kibblewhite** [comment]
Hello, Same here, experiencing the same issue on PHP. My client bombs out with:
ERROR: 14, Empty update

Following the trace and looking up the errors I'm receiving are the same/matches those who are experiencing the same in this thread also.

**Comment by valaxkong** [comment]
I offer a debug direction for this issue.
That is making sure your grpc server is listening the target port before trying to invoke remote function from client.

**Comment by RelyanceRachel** [comment]
I have the same problem.
I have one javascript grpc server with python grpc client packed into docker. It runs on several machines. Only one machine saw this connection issue.

**Comment by RelyanceRachel** [comment]
Finally, I got mine to work. I started the JavaScript grpc server and send the request right away from client. It looks like the server has not started yet. So I added some sleep time before sending out the request. Everything works.

**Comment by Ipicky22** [comment]
I had the same problem, and I solved it.
I try to do a grpc server / client and kafka poducer / consumer, in Python.
I trigger this error because I call my grpc client before my grpc server.

`
python                    3.9.7
`
`
grpcio                    1.40.0
`
`
grpcio-tools              1.40.0
`

Client.py : 
```Python
from grpc_folder.proto_folder.service_pb2 import Request
from grpc_folder.proto_folder.service_pb2_grpc import StreamServiceStub
import grpc


def Listen(url):
    channel = grpc.insecure_channel(url)
    client = StreamServiceStub(channel)
    request = Request(id=1)
    response = client.Stream(request)
    for key in response:
        print(key)
```

Server.py :
```Python
from concurrent import futures
import grpc
import time
import grpc_folder.proto_folder.service_pb2 as service_pb2
import grpc_folder.proto_folder.service_pb2_grpc as service_pb2_grpc


class OutputService(service_pb2_grpc.StreamServiceServicer):
    x = 0

    def __init__(self):
        self.responses = []

    def Stream(self, request, context):
        while True:
            time.sleep(2)
            OutputService.x = OutputService.x+1
            response = service_pb2.Response()
            response.result = OutputService.x.to_bytes(2, 'big')
            yield response


def serve(urlGrpcServer):
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    service_pb2_grpc.add_StreamServiceServicer_to_server(
        OutputService(), server
    )
    server.add_insecure_port(urlGrpcServer)
    server.start()
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
```

Main.py : 
```Python
from grpc_folder import client as GRPCClient
from grpc_folder import server as GRPCServer

def Init( urlGrpcClient, urlGrpcServer):
    GrpcServer = GRPCServer.serve(urlGrpcServer)
    GrpcClient = GRPCClient.Listen(urlGrpcClient)
    return GrpcClient, GrpcServer
```

I hope this post helps you.

**Comment by choufler** [comment]
I have the same problem.
Tried different clients: python sync & async, c++ .

the issue appears only if I implement async callback (inherit from ```CallbackService```):
from this proposal https://github.com/grpc/proposal/blob/master/L67-cpp-callback-api.md

as long as I change my implementation back to normal ```Service``` - everything works ok.
Has anyone came across this?
