### ISSUE TITLE
grpc_csharp_plugin' failed 

### ISSUE THREAD

**Issue by zanshuo** [grpc/grpc#23359]
System:ubuntu 16.04
input command:
git clone https://github.com/grpc/grpc.git grpc
cd grpc
git checkout "v1.3.2"
git submodule update --init --recursive 
make
then I  got:
![image](https://user-images.githubusercontent.com/47976773/86110548-4590e180-baf8-11ea-83a5-19f74e306c0a.png)

How to solve it?I have compiled and installed protobuf in grpc/third_party,and the version of protoc is 3.2.0.

**Comment by nicolasnoble** [comment]
You have an incompatible and / or outdated version of protobuf installed on your system. Please upgrade it and retry.
