### ISSUE TITLE
ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE.

### ISSUE THREAD

**Issue by fanyl3** [grpc/grpc#23370]
### What version of gRPC and what language are you using?
client: c++ 1.6.0
server: python 1.12.0

### What operating system (Linux, Windows,...) and version?
client： linux mipse64 arch
server：linux/windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.7.0
python 2.7.15

### What did you do?
I created a c++ tls client on device and created a python tls server on my PC， then i used the client to connect the server， but it failed。

### What did you expect to see?
The client can connect to the server normally

### What did you see instead?
There is an error:
E0701 10:56:10.998183812    3214 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE.

**Comment by nicolasnoble** [comment]
First, these are horribly out of date versions of the library, and second, these problems are inside OpenSSL itself. Please upgrade to a more recent version and retry.
