### ISSUE TITLE
Wheel support for aarch64(arm64)

### ISSUE THREAD

**Issue by odidev** [grpc/grpc#23373]
**Summary**
Installing grpcio on aarch64 via pip using command "pip3 install grpcio" tries to build wheel from source code

**Problem description**
grpcio don't have wheel for aarch64 on PyPI repository. So, while installing grpcio via pip on aarch64, pip builds wheel for same resulting in it takes more time to install grpcio. Making wheel available for aarch64 will benefit aarch64 users by minimizing grpcio installation time.

**Expected Output**
Pip should be able to download grpcio wheel from PyPI repository rather than building it from source code.

@grpcio-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make grpcio wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by nicolasnoble** [comment]
Due to a lack of proper infrastructure support for the arm architecture, we do not have any plans for this at this time.

**Comment by rhenwood-arm** [comment]
This request relates to: https://github.com/grpc/grpc/issues/21283

**Comment by AGSaidi** [comment]
What infrastructure do you need @nicolasnoble? TravisCI does support Arm builds now and the Graviton2 ones are quite fast.

**Comment by odidev** [comment]
@nicolasnoble, can you please let me know what infrastructure do you need. Travis-ci is providing Arm64 build machine as well. I can help you in building AArch64 wheel and deploying on pypi.

**Comment by mattsplats** [comment]
@nicolasnoble Seems like this would work:
- Add an arm64 build to the existing `.travis.yml` to run on new commits to `master`
- Run [submit.py](https://github.com/grpc/grpc/blob/master/tools/distrib/python/submit.py) with the output wheel

You'd just need to add the twine username and password to the Travis environment variables.

Any objections? There seem to be [a lot of open issues and thumbs up on arm64 builds/wheels](https://github.com/grpc/grpc/issues/24002), so if you're open to PR I'm happy to contribute.

**Comment by mattsplats** [comment]
@odidev Might want to add arm64 to the title so more people see (and don't duplicate) this ticket: https://github.com/grpc/grpc/issues/24369

**Comment by srini100** [comment]
@mattsplats, Travis CI hasn't scaled well for gRPC org in the past. grpc-java and grpc-go repos use up most of the quota and other repos like grpc-swift also share the quota. That's why we moved away from Travis for grpc/grpc. 
I believe the paid version requires giving write access to the repo. Here is a relevant comment: https://github.com/grpc/grpc/issues/23797#issuecomment-673128578

**Comment by jvesely** [comment]
> I believe the paid version requires giving write access to the repo. Here is a relevant comment: [#23797 (comment)](https://github.com/grpc/grpc/issues/23797#issuecomment-673128578)

This is wrong, and it has been disproved in the same conversation. Questions about migrating from travic-ci.org to travis-ci.com should be directed to travis support.

**Comment by srini100** [comment]
@jvesely, the info [here](https://docs.travis-ci.com/user/github-oauth-scopes/#travis-ci-for-open-source-and-private-projects) says it requires write access to administration. Our security team doesn't allow that. They got an update from Travis that they are planning to update the requested scopes but it hasn't happened yet.

**Comment by jvesely** [comment]
> @jvesely, the info [here](https://docs.travis-ci.com/user/github-oauth-scopes/#travis-ci-for-open-source-and-private-projects) says it requires write access to administration. Our security team doesn't allow that. They got an update from Travis that they are planning to update the requested scopes but it hasn't happened yet.

thanks for the update. the permissions reported by github are:
```
Permissions
 Read access to code, metadata, and pull requests
 Read and write access to checks, commit statuses, deployments, and repository hooks
```
Given the migration attempt in #23797 I assumed that access to checks/status/hooks/... is OK.
while you can set up hooks manually and can do without deployments.
I don't see how you can have useful CI without access to checks/statuses.

**Comment by srini100** [comment]
To clarify, the Github app itself doesn't require write access to the code but to set it up and maintain, the user GitHub sign-in on travis-ci.com requires full write access to the repo. See this [comment](https://travis-ci.community/t/is-there-a-plan-to-stop-travis-requesting-read-write-access-on-travis-ci-com-login/1364/16).

Regardless of the permission issue, the free tier capacity is still a blocker.

**Comment by jvesely** [comment]
Thanks for the clarification. I stand corrected.

**Comment by lidizheng** [comment]
We still want this.

**Comment by jtattermusch** [comment]
Closing as a duplicate of https://github.com/grpc/grpc/issues/21283
