### ISSUE TITLE
Memory leaks in gRPC versions 1.18 and 1.3

### ISSUE THREAD

**Issue by mbcolson** [grpc/grpc#23382]
Hi All,

Does anyone know of any fixes for the following memory leaks seen in gRPC versions 1.18 and 1.3?

Note: we see these leaks when running valgrind on the process. There is steaming activity on the gRPC server in all of these leaks.

In gRPC version 1.18,

==19520== 9,838 (6,963 direct, 2,875 indirect) bytes in 1 blocks are definitely lost in loss record 1,220 of 1,254
==19520==    at 0x4EDA0F3: malloc (vg_replace_malloc.c:300)
==19520==    by 0xE904549: gpr_malloc (alloc.cc:57)
==19520==    by 0xE904764: gpr_malloc_aligned (alloc.cc:93)
==19520==    by 0xE8B8798: gpr_arena_alloc_maybe_init(unsigned int) (arena.cc:61)
==19520==    by 0xE8B873A: gpr_arena_create(unsigned int) (arena.cc:157)
==19520==    by 0xE8A9903: grpc_call_create(grpc_call_create_args const*, grpc_call**) (call.cc:332)
==19520==    by 0xE8755FA: accept_stream(void*, grpc_transport*, void const*) (server.cc:868)
==19520==    by 0xE81B46B: grpc_chttp2_parsing_accept_stream(grpc_chttp2_transport*, unsigned int) (chttp2_transport.cc:804)
==19520==    by 0xE805D95: init_header_frame_parser(grpc_chttp2_transport*, int) (parsing.cc:622)
==19520==    by 0xE805250: init_frame_parser(grpc_chttp2_transport*) (parsing.cc:292)
==19520==    by 0xE80469F: grpc_chttp2_perform_read(grpc_chttp2_transport*, grpc_slice) (parsing.cc:177)
==19520==    by 0xE822FF6: read_action_locked(void*, grpc_error*) (chttp2_transport.cc:2527)

==19520== 5,696 (5,120 direct, 576 indirect) bytes in 32 blocks are definitely lost in loss record 1,208 of 1,254
==19520==    at 0x4EDA0F3: malloc (vg_replace_malloc.c:300)
==19520==    by 0xE904549: gpr_malloc (alloc.cc:57)
==19520==    by 0xE8C5227: grpc_raw_compressed_byte_buffer_create (byte_buffer.cc:39)
==19520==    by 0xE8C51D0: grpc_raw_byte_buffer_create (byte_buffer.cc:30)
==19520==    by 0xE8B0445: process_data_after_md(batch_control*) (call.cc:1304)
==19520==    by 0xE8AF893: receiving_stream_ready(void*, grpc_error*) (call.cc:1329)
==19520==    by 0xE8AEACA: receiving_stream_ready_in_call_combiner(void*, grpc_error*) (call.cc:1341)
==19520==    by 0xE8EDE65: exec_ctx_run(grpc_closure*, grpc_error*) (exec_ctx.cc:40)
==19520==    by 0xE7DEB22: grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) (closure.h:259)
==19520==    by 0xE7DC633: recv_message_ready(void*, grpc_error*) (message_size_filter.cc:202)
==19520==    by 0xE8EDE65: exec_ctx_run(grpc_closure*, grpc_error*) (exec_ctx.cc:40)
==19520==    by 0xE8EDCA1: grpc_core::ExecCtx::Flush() (exec_ctx.cc:147)

==29823== 948 (160 direct, 788 indirect) bytes in 1 blocks are definitely lost in loss record 1,097 of 1,233
==29823==    at 0x4EDA0F3: malloc (vg_replace_malloc.c:300)
==29823==    by 0xE904549: gpr_malloc (alloc.cc:57)
==29823==    by 0xE8D451B: grpc_resource_quota_create (resource_quota.cc:632)
==29823==    by 0xE8D0101: grpc_tcp_create(grpc_fd*, grpc_channel_args const*, char const*) (tcp_posix.cc:1073)
==29823==    by 0xE8CD686: on_read(void*, grpc_error*) (tcp_server_posix.cc:248)
==29823==    by 0xE8EDE65: exec_ctx_run(grpc_closure*, grpc_error*) (exec_ctx.cc:40)
==29823==    by 0xE8EDCA1: grpc_core::ExecCtx::Flush() (exec_ctx.cc:147)
==29823==    by 0xE8E433F: pollset_work(grpc_pollset*, grpc_pollset_worker**, long long) (ev_poll_posix.cc:1133)
==29823==    by 0xE8E1C4D: pollset_work(grpc_pollset*, grpc_pollset_worker**, long long) (ev_posix.cc:322)
==29823==    by 0xE8F9BED: grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long long) (pollset.cc:48)
==29823==    by 0xE8BAAF7: cq_next(grpc_completion_queue*, gpr_timespec, void*) (completion_queue.cc:1039)
==29823==    by 0xE8B9812: grpc_completion_queue_next (completion_queue.cc:1115)

------------------------------------------------------------------------------------------------------------------------------------------
In gRPC version 1.3,

==67657== 4,807,025 (1,536 direct, 4,805,489 indirect) bytes in 12 blocks are definitely lost in loss record 1,012 of 1,012
==67657==    at 0x4EDA0F3: malloc (vg_replace_malloc.c:300)
==67657==    by 0xE8288DE: gpr_malloc (alloc.c:71)
==67657==    by 0xE80BD37: grpc_raw_compressed_byte_buffer_create (byte_buffer.c:50)
==67657==    by 0xE80BCE0: grpc_raw_byte_buffer_create (byte_buffer.c:42)
==67657==    by 0xE7C0F3F: process_data_after_md (call.c:1247)
==67657==    by 0xE7BF51A: receiving_stream_ready (call.c:1270)
==67657==    by 0xE822E91: exec_ctx_run (exec_ctx.c:102)
==67657==    by 0xE824934: grpc_closure_run (closure.c:132)
==67657==    by 0xE7855E8: recv_message_ready (message_size_filter.c:135)
==67657==    by 0xE822E91: exec_ctx_run (exec_ctx.c:102)
==67657==    by 0xE824934: grpc_closure_run (closure.c:132)
==67657==    by 0xE7D4751: null_then_run_closure (chttp2_transport.c:1079)

==67657== 591 (112 direct, 479 indirect) bytes in 1 blocks are definitely lost in loss record 924 of 1,012
==67657==    at 0x4EDA0F3: malloc (vg_replace_malloc.c:300)
==67657==    by 0xE8288DE: gpr_malloc (alloc.c:71)
==67657==    by 0xE7E361B: grpc_resource_quota_create (resource_quota.c:581)
==67657==    by 0xE7A164B: grpc_tcp_create (tcp_posix.c:590)
==67657==    by 0xE79CBAE: grpc_tcp_client_create_from_fd (tcp_client_posix.c:161)
==67657==    by 0xE79D031: tcp_client_connect_impl (tcp_client_posix.c:328)
==67657==    by 0xE79D601: grpc_tcp_client_connect (tcp_client_posix.c:385)
==67657==    by 0xE76D439: chttp2_connector_connect (chttp2_connector.c:205)
==67657==    by 0xE802944: grpc_connector_connect (connector.c:49)
==67657==    by 0xE7FED75: continue_connect_locked (subchannel.c:419)
==67657==    by 0xE7FDD44: maybe_start_connecting_locked (subchannel.c:501)
==67657==    by 0xE7FDA18: grpc_subchannel_notify_on_state_change (subchannel.c:552)

Thanks,

Mike

**Comment by veblush** [comment]
I'm afraid to say I don't have clue which PR fixed this problem. First of all, the latest version of gRPC, 1.30 doesn't have this problem? If it's fixed, you can bisect the version of gRPC started to address this problem and might be able to find the right PR.
