### ISSUE TITLE
check_linker_need_libatomic() checks system cc instead of user compiler

### ISSUE THREAD

**Issue by dkonst13** [grpc/grpc#23384]
### What version of gRPC and what language are you using?

1.26.0 and local installation of gcc 9.3.0

### What operating system (Linux, Windows,...) and version?

Centos8

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 9.3.0

### What did you do?

python2 setup.py install --root=/ --prefix=/tmp/BUILD/lcgcmake-install/grpcio/1.26.0/x86_64-centos8-gcc9-opt

### What did you expect to see?

Expect to see normal installation

### What did you see instead?
`
Traceback (most recent call last):
  File "setup.py", line 190, in <module>
    if check_linker_need_libatomic():
  File "setup.py", line 151, in check_linker_need_libatomic
    stderr=PIPE)
  File "/tmp/BUILD/lcgcmake-install/Python/2.7.16/x86_64-centos8-gcc9-opt/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/tmp/BUILD/lcgcmake-install/Python/2.7.16/x86_64-centos8-gcc9-opt/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`
GNU GCC doesn't have a symlink cc pointing to gcc and system doesn't have system gcc installed.

**Comment by lidizheng** [comment]
@dkonst13 It seems the script cannot find the compiler. Can you try other methods to install gcc (e.g., yum)?

I'm not sure, but have you run `make install` for your local installation? If so, you might want to dig the parameters of `./configure` to fix the local installation.
