### ISSUE TITLE
Python - grpc.ServicerContext..invocation_metadata() - subclasses return different value types

### ISSUE THREAD

**Issue by glebarez** [grpc/grpc#23429]
Hello gRPC team!
I've stumbled across this bug in grpcio python:
the server-side context returns different types of value in method invocation_metadata().
in grpcio-testing: returns dict
in grpcio: return tuple of tuples

I need therefore to explicitly check return type in my code to avoid failing in either tests or normal run

**Comment by veblush** [comment]
The provided information is insufficient for debugging/action. Please re-open the issue with additional information/instructions on reproducing the issue.
