### ISSUE TITLE
assertion failed: !completion_op_

### ISSUE THREAD

**Issue by HaoLiuHust** [grpc/grpc#23442]
In some case, below assertion failed will occur, I wonder in which case completion_op_ will be shutdown by grpc?
E0710 13:00:23.566525614   12191 server_context.cc:269]      assertion failed: !completion_op_

**Comment by veblush** [comment]
The provided information is insufficient for debugging/action. Please re-open the issue with additional information/instructions on reproducing the issue.

**Comment by HaoLiuHust** [comment]
I have made a server with grpc(c++), and write an async client(python) which open 50 threads to request to server, at server side, I have open 7 threads to process requests, after running several  minutes, the assertion will occur, server crashed then.
I am using grpc v1.19.0

**Comment by HaoLiuHust** [comment]
@veblush @yashykt

**Comment by yashykt** [comment]
Hi @HaoLiuHust , we already have cases of gRPC use with many threads. You would need to provide something like a unit test case maybe as a github gist that we can run and verify. Also, gRPC support is limited to the previous two releases and gRPC v.1.19.0 is slightly old now.

**Comment by HaoLiuHust** [comment]
I will try the newest version. I wonder in which case "completion_op_" will be null so I can check if I have make some mistake?

**Comment by XinyuZeng** [comment]
Hi @HaoLiuHust , did you figure this out?

**Comment by HaoLiuHust** [comment]
> Hi @HaoLiuHust , did you figure this out?

no, not yet...， I just replace GPR_ASSERT with if，no longer meet this issue...
![image](https://user-images.githubusercontent.com/7233091/100176282-f2865380-2f0a-11eb-8b30-af48995206f8.png)
