### ISSUE TITLE
gRPC C++ installation error via Cocoapod

### ISSUE THREAD

**Issue by hsivakum** [grpc/grpc#23448]
grpc Version
v1.28.2

OS
MacOSX 10.14.6

Compiler Version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix

Trying to do pod install with grpc dependencies, where it was downloading v1.28.2 but ended up in error at sed empty string in filename
things to reproduce,
ruby version
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin18]
cocoa pods version
1.9.3
to test package, you can use **cloud_firestore:** as flutter dependency and try to run pod install
I suspect this empty string in the sed is throwing error in mac `sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\` in file https://github.com/grpc/grpc/blob/046ee0196d6278679cd7d01d5b81258ee8fffc57/gRPC-C%2B%2B.podspec#L1317

I would like to install the cloud_firestore which internally requires the grpc-c++ version. the pods not installing the grpc in this specific scenario

I see the below error while doing pod install

**
[!] /usr/local/bin/bash -c
set -e
sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g' $(find src/core -type f \( -path '*.h' -or -path '*.cc' \) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)
    find src/core/ third_party/upb/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "upb/(.*)";#if COCOAPODS==1\
  #include  "third_party/upb/upb/\1"\
#else\
  #include  "upb/\1"\
#endif;g'
    find src/core/ third_party/upb/ -type f -name '*.grpc_back' -print0 | xargs -0 rm
    find src/core/ src/cpp/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "(.*).upb.h";#if COCOAPODS==1\
  #include  "src/core/ext/upb-generated/\1.upb.h"\
#else\
  #include  "\1.upb.h"\
#endif;g'
    find src/core/ src/cpp/ -type f -name '*.grpc_back' -print0 | xargs -0 rm

sed: (standard: No such file or directory
**

**Comment by yulin-liang** [comment]
@hsivakum Does this only happen on v1.28.2? Have you tried any other version?

**Comment by dcristolovean** [comment]
+1, got this exact same error today too.
Same versions, gRPC-C++ is used probably by some Firebase pods that I have.

**Comment by tkdp** [comment]
i have currently the same problem in my flutter-project; how can i switch the sed?

**Comment by yulin-liang** [comment]
@tkdp I'm not pretty sure, but I think you may need to remove the gnu-sed Path variable.

**Comment by tkdp** [comment]
thanks yulin, i have done an `alias sed=gsed` and it worked
