### ISSUE TITLE
Installing grpcio-1.30.0 from Google Function for Google Dataflow reference

### ISSUE THREAD

**Issue by posypanka** [grpc/grpc#23459]
### What version of gRPC and what language are you using?

grpcio-1.30.0 Python

### What operating system (Linux, Windows,...) and version?

Linux, Ubuntu 18.04 (Google Cloud Functions)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7.6

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Create a Google Function which deploys Google Dataflow with grpcio>=1.12.1 in the requirements

### What did you expect to see?

Install grpcio

### What did you see instead?

Error: function terminated. Recommended action: inspect logs for termination reason. Details:
Full traceback: Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/apache_beam/utils/processes.py", line 85, in check_output
    out = subprocess.check_output(*args, **kwargs)
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/env/bin/python3.7', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', './requirements_dataflow.txt', '--exists-action', 'i', '--no-binary', ':all:']' returned non-zero exit status 1.
 
 Pip install failed for package: -r         
 Output from execution of subprocess: b'Collecting grpcio>=1.12.1
  Downloading grpcio-1.30.0.tar.gz (19.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /env/bin/python3.7 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-download-ii_x0roq/grpcio/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-download-ii_x0roq/grpcio/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\
\'"\'"\', \'"\'"\'\
\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-download-ii_x0roq/grpcio/pip-egg-info
         cwd: /tmp/pip-download-ii_x0roq/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-ii_x0roq/grpcio/setup.py", line 196, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-download-ii_x0roq/grpcio/setup.py", line 156, in check_linker_need_libatomic
        stderr=PIPE)
      File "/opt/python3.7/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/opt/python3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: \'cc\': \'cc\'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the \'/env/bin/python3.7 -m pip install --upgrade pip\' command.

**Comment by veblush** [comment]
This error message meant that your system doesn't have C/C++ compilers so you might need to install gcc and g++. From the version of pip, 20.0.2, your pip should be aware of manylinux artifacts but your system might not be compatible to it by observing it tried to build it from source. Can you please let us know the detail of your system? hardware, linux version, so on.

**Comment by posypanka** [comment]
Hi, thanks for the reply. It's Google Cloud Function (server-less service) https://cloud.google.com/functions/docs/concepts/exec

All I found is that it's Linux, Ubuntu 18.04 with Python 3.7.6.

**Comment by lidizheng** [comment]
Ubuntu should automatically pick up our precompiled wheels. Can you try to manually install the [1.30.0 x86 wheel](https://files.pythonhosted.org/packages/cf/10/ed3caaa9e4c1b8c275b866438e2047d34d5e64dacc75dd0b1daf28ae07af/grpcio-1.30.0-cp37-cp37m-manylinux2010_x86_64.whl)?

**Comment by posypanka** [comment]
I think the problem is in --no-binary', ':all: which is set automatically and is not configurable.

**Comment by lidizheng** [comment]
Sorry, this issue cannot be resolved on our end. Can you copy the details here and file a bug to Cloud Functions?

You can find their public issue tracker here:
* https://cloud.google.com/support/docs/issue-trackers
* https://issuetracker.google.com/issues/new?component=187195&template=0

Feel free to CC me on the created bug, so I can help if needed.
