### ISSUE TITLE
undefined reference to grpc_core::JoinHostPort

### ISSUE THREAD

**Issue by sertoa812** [grpc/grpc#23452]
When I try to build opensse-schemes project on 
It came out an error in linking procedure:

```
../lib/librunners.so: undefined reference to `grpc_core::JoinHostPort(absl::lts_2020_02_25::string_view, int)'
../lib/librunners.so: undefined reference to `OPENSSL_free'
../lib/librunners.so: undefined reference to `upb_arena_init'
../lib/librunners.so: undefined reference to `gpr_mu_lock'
../lib/librunners.so: undefined reference to `bool absl::lts_2020_02_25::str_f
```

I suspect in their linking file, there is missing a crucial .so or .a library

Besides, there is the link command, can you help me recognize which library it missed?

`/usr/bin/c++  -O3 -DNDEBUG  -rdynamic CMakeFiles/sophos_client.dir/sophos_client.cpp.o  -o sophos_client  -Wl,-rpath,/root/opensse-schemes/build/lib:/root/opensse-schemes/build/third_party/crypto/src:/usr/local/lib:/root/opensse-schemes/build/third_party/db-parser/src ../lib/librunners.so ../lib/libschemes.so ../third_party/crypto/src/libsse_crypto.so /usr/local/lib/libsodium.so -lgmp -lgmpxx /usr/local/lib/librelic.so /usr/lib/x86_64-linux-gnu/libcrypto.so ../third_party/db-parser/src/libdbparser.so /usr/local/lib/librocksdb.a /usr/local/lib/libgrpc++.a /usr/local/lib/libgrpc.a -ldl /usr/local/lib/libprotobuf.a -lpthread`

**Comment by veblush** [comment]
This is because it doesn't link to [absl](https://github.com/abseil/abseil-cpp/tree/master/absl). I don't know the build system of `opensse-schemes` but it looks that it need to extend its build configuration to add absl.

**Comment by sertoa812** [comment]
It works! Really appreciate your help!

**Comment by Issaaaaaaaaam** [comment]
hi, @sertoa812  I wanted to know if you could tell me how did you solve your problem I have the exact same issue and I am new to linux. Thanks alot

**Comment by tanhunggg** [comment]
> It works! Really appreciate your help!

pls tell me how to solve the problem. thanks alot
