### ISSUE TITLE
node interop tests failing due to npm build error

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#23466]
https://source.cloud.google.com/results/invocations/3d42dd8d-1c1e-4475-a067-a252bf7eead3/targets/github%2Fgrpc%2Finterop_docker_build/tests;group=tests;test=build_docker_nodepurejs;row=1

I think this is the relevant error:

```
> @grpc/proto-loader@0.5.5 compile /var/local/git/grpc-node/packages/proto-loader
> tsc -p .

[96m../../node_modules/@types/gulp-mocha/index.d.ts[0m:[93m10[0m:[93m39[0m - [91merror[0m[90m TS2304: [0mCannot find name 'MochaSetupOptions'.

[7m10[0m declare function mocha(setupOptions?: MochaSetupOptions): NodeJS.ReadWriteStream;
[7m  [0m [91m                                      ~~~~~~~~~~~~~~~~~[0m


Found 2 errors.
```

**Comment by stanley-cheung** [comment]
@murgatroid99 I attempted to fix this in https://github.com/grpc/grpc-node/pull/1500, PTAL, thanks!

**Comment by jtattermusch** [comment]
Still broken on master. Bumping to P1

**Comment by murgatroid99** [comment]
I think I have fixed this by merging grpc/grpc-node#1504.

**Comment by stanley-cheung** [comment]
Having a green build now: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud

**Comment by stanley-cheung** [comment]
This should be fixed now.
