### ISSUE TITLE
Linux and macos distribtests are broken

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#23461]
Internal issue:
b/160166189

https://source.cloud.google.com/results/invocations/b74b6d46-f043-4f64-8c6e-a8623386d655/targets/github%2Fgrpc/tests;group=tasks;test=distribtest.python_dev_linux_x64_ubuntu1404;row=1

https://source.cloud.google.com/results/invocations/fa1f61f6-cebd-4f41-a8fb-5bdffc0f3449/targets/github%2Fgrpc/tests

Broken since https://github.com/grpc/grpc/pull/21941.

**Comment by jtattermusch** [comment]
@markdroth  @nicolasnoble what's the plan here? We have a branch cut scheduled for tomorrow and this issue is blocking it.

**Comment by jtattermusch** [comment]
Another thing that's broken is the grpc_cfstream job on master: b/160165400

**Comment by srini100** [comment]
We'll have to rollback #21941 if this and #23307 can't be fixed this week.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/21941 has been rolled back but the linux distribtests are still failing (perhaps the rollback from https://github.com/grpc/grpc/pull/23524 hasn't been 100% successful?)

**Comment by lidizheng** [comment]
Triggered one more build: http://sponge/7295e3ed-9d91-4e8b-90bf-d78ddc284d45

**Comment by jtattermusch** [comment]
Both #23552 and #23565 have been merged so this should be fixed.
