### ISSUE TITLE
Crash in ciena::tmet::grpc::ServerContextImpl::run

### ISSUE THREAD

**Issue by colinmai123** [grpc/grpc#23474]
Crash found in grpcio-1.14.1
I am getting a coredump in the grpc library. Please let me know if there is a fix available for this. Thank you.

_#0 0x0000000000000035 in ?? () 
 #1 0x00007f214a9643d2 in ciena::tmet::grpc::ServerContextImpl::run ( 
 this=0x7f2134000f70) 
 at /usr/src/debug/telemetry/1.0.0+gitAUTOINC+9d0ba07e1f-r0/git/src/transport/grpc/server.cpp:375 
 #2 0x00007f214a962a69 in ciena::tmet::grpc::ServerContext::run() () 
 at /usr/include/c++/9.2.0/bits/unique_ptr.h:352 
 #3 0x000000000040467c in grpcServer(void*, void*) () 
 at /usr/src/debug/telemetry/1.0.0+gitAUTOINC+9d0ba07e1f-r0/git/src/main.cpp:67 
 #4 0x00007f214a50f150 in svcCzmqActorFn (pPipe=0x48fc90, pArgs=0x490500) 
 at /usr/src/debug/libcncore/1.0.0+gitAUTOINC+4aa04575d5-r0/git/cncore/src/serviceContext.c:4758 
 #5 0x00007f21494cae94 in s_thread_shim (args=0x48fc70) 
 at /usr/src/debug/czmq/4.2.0-r0/czmq-4.2.0/src/zactor.c:68 
 #6 0x00000039aba08ed4 in start_thread (arg=) 
 at /usr/src/debug/glibc/2.30-r0/git/nptl/pthread_create.c:479 
 #7 0x00000039ab6f8e6f in clone () 
 at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95_ 

Did some debugging and nextStep seems to be NULL

_(gdb) ptype ICompletionManager
type = class ciena::tmet::grpc::ICompletionManager {
  public:
    ~ICompletionManager();
    virtual void nextStep(ciena::tmet::grpc::IServerImpl *);
    virtual void cancel(void);
    virtual void shutdown(void);
}
(gdb) p ((ICompletionManager *)0x7fbf04086b80)->nextStep
Cannot take address of method nextStep.
(gdb) p ((ICompletionManager *)0x7fbf04086b80)->cancel
$10 = {void (ciena::tmet::grpc::ICompletionManager * const)} 0x7fbf1e1002d0_

This might be a duplicate of https://github.com/grpc/grpc/issues/23270, please let me know if it is so I can close it. 

Thank you for the hard work!

**Comment by markdroth** [comment]
gRPC 1.14 is quite old.  Please try a more recent version.
