### ISSUE TITLE
Add Bazel setup to Android example

### ISSUE THREAD

**Issue by Nimrodda** [grpc/grpc#23486]
### Is your feature request related to a problem? Please describe.
I'm using the Android example in my own project. Currently the example uses CMake/Gradle, which is slow and requires to clone all the gRPC's submodules to build.

### Describe the solution you'd like
As gRPC's main build tool is Bazel, it would be great if you could add Bazel's setup to the example in addition to CMake/Gradle so that developer can choose.

### Describe alternatives you've considered
I'm very new to Bazel and I tried to set it up myself (for now just to build the c++ code) like so:
I added BUILD file in src/main:
```
cc_library(
    name = "grpc-helloworld",
    srcs = ["cpp/grpc-helloworld.cc"],
    copts = [
        "-std=c++14",
        "-frtti",
        "-fexceptions",
        "-DANDROID_STL=c++_static",
        "-DRUN_HAVE_POSIX_REGEX=0",
        "-DRUN_HAVE_STD_REGEX=0",
        "-DRUN_HAVE_STEADY_CLOCK=0",
        "-Dprotobuf_BUILD_PROTOC_BINARIES=off",
        "-DgRPC_BUILD_CODEGEN=off",
        ],
    linkopts = ["-landroid", "-llog"],
    deps = [
        "@grpc//:grpc++"
    ]
)
```
And WORKSPACE file under app/ :
```
android_sdk_repository(name = "androidsdk")
android_ndk_repository(name = "androidndk")

local_repository(
    name = "grpc",
    path = "../../../../"
)
```

Unfortunately when I execute:
```
bazel build //src/main:grpc-helloworld \
      --crosstool_top=@androidndk//:default_crosstool \
      --cpu=x86 \
      --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
```

I get an error:
```
error loading package '@grpc//': in /private/var/tmp/_bazel_nimrod/1c284265d2687bff10a5d7b5b04bf8cb/external/grpc/bazel/grpc_build_system.bzl: Unable to find package for @build_bazel_rules_apple//apple:ios.bzl: The repository '@build_bazel_rules_apple' could not be resolved. and referenced by '//src/main:grpc-helloworld'
```

gRPC Bazel config is quite advanced and it's easy to make mistakes especially for somebody like me who's a Bazel beginner so I think it would be great if you could add the required Bazel config out-of-the-box.

**Comment by karthikravis** [comment]
@Nimrodda : Please send a PR with a suggestion. We're open to contributions from the community.
