### ISSUE TITLE
[Ruby] grpc_tools_ruby_protoc generates wrong namespace for fully-qualified rpc response type

### ISSUE THREAD

**Issue by dazuma** [grpc/grpc#23490]
### What version of gRPC and what language are you using?

grpc_tools_ruby_protoc 1.30.1 (see https://rubygems.org/gems/grpc-tools/versions/1.30.1) on Ubuntu bionic

### What did you do?

Running the grpc protoc plugin on the google.cloud.oslogin.v1 proto (as part of client library codegen). The GetSshPublicKey and UpdateSshPublicKey RPCs generate an incorrect Ruby type for their response type.

Proto: https://github.com/googleapis/googleapis/blob/1b969c28a6579265e89cd35e6c2ecacc89970e2d/google/cloud/oslogin/v1/oslogin.proto#L72

Result: https://github.com/googleapis/google-cloud-ruby/pull/7036/files#diff-963ba7c73491dae821dd8275d003634e (you'll have to click View Diff to see it).

Here's a screen shot in case the PR gets closed: ![screen shot](https://user-images.githubusercontent.com/8911/87488884-61b37900-c5f6-11ea-9348-a31b36e624c4.png)

Note that the generated type of the response is incorrect (part of the namespace is duplicated).

Some items of note that might be pertinent to this case:
* The response in the proto is fully-qualified.
* The proto has defined a custom Ruby namespace (i.e. a `ruby_package` proto option). The response type is also in a custom Ruby namespace.

Note that the "extra" namespace path that is being added corresponds to the "fully-qualified" segments of the response type, but does not conform to the custom Ruby namespace for this proto. (Look carefully at the case of the "L" in "OsLogin".)

**This appears to be a regression in grpc_tools 1.30.** (Previous generation runs using 1.28 did not exhibit this behavior.)

**Comment by stanley-cheung** [comment]
Here's a simpler reproducible test case:

`myapi/foo/foo1.proto`:
```
syntax = "proto3";
package myapi.foo;
import "myapi/bar/bar1.proto";
message MyRequest {
  string name = 1;
}
service MyService {
  rpc DoSomething (MyRequest) returns (myapi.bar.MyResponse);
}
```
`myapi/bar/bar1.proto`:
```
syntax = "proto3";
package myapi.bar;
option ruby_package = "Myapi::Bar";
message MyResponse {
  string name = 1;
}
```

Run:
```
$ protoc -I=. myapi/foo/foo1.proto myapi/bar/bar1.proto --grpc_out=. --plugin=protoc-gen-grpc=./bins/opt/grpc_ruby_plugin
```

Output `myapi/foo/foo1_services_pb.rb`:
```
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: myapi/foo/foo1.proto for package 'myapi.foo'

require 'grpc'
require 'myapi/foo/foo1_pb'

module Myapi
  module Foo
    module MyService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'myapi.foo.MyService'

        rpc :DoSomething, MyRequest, Myapi::Bar::Myapi::Bar::MyResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
```

Notice the `Myapi::Bar::Myapi::Bar::MyResponse`.

This only reproduces in `1.30.x` but not `1.29.x` or before.


Looking into `ruby_generator.cc` to see what the problem is.
