### ISSUE TITLE
Certificate validation occurs on every request

### ISSUE THREAD

**Issue by noahdav** [grpc/grpc#23498]
### What version of gRPC and what language are you using?
1.29.1

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC

### What did you do?
I have implemented an AuthMetadataProcessor to authenticate the caller.  I am setting it by calling ServerCredentials::SetAuthMetadataProcessor.  This works however it is called to authenticate every request.  This is causing way too much of a perf impact.  I would expect that this is only called when authenticating a new connection not every request on the connection.  Is ?there a way to not authenticate every request and only when the connection is established?

### What did you expect to see?
The AuthMetadataProcessor::Process method is called when the connection is established but not on every request.

### What did you see instead?
AuthMetadataProcessor::Process is called for every request.

**Comment by markdroth** [comment]
The metadata being authenticated by this plugin is sent on a per-RPC basis, and each individual RPC can have different metadata, so the authentication needs to be done on each request.  This cannot be done on a per-connection basis.

Depending on how your AuthMetadataProcessor implementation works, you might consider doing some sort of caching in the implementation to improve performance.

**Comment by noahdav** [comment]
@markdroth There typically is a difference between authentication and authorization.  I understand why authorization needs to occur on every request but why does authentication need to be done like this?  Is there a different way that I can perform the authentication on a per connection basis?

**Comment by markdroth** [comment]
If you're using metadata for either authentication or authorization, the metadata is sent on a per-request basis, so it has to be checked on a per-request basis.  If you want to do authentication on a per-connection basis, consider using something like mTLS.

**Comment by noahdav** [comment]
@markdroth I am using the TlsServerAuthorizationCheckConfig on the client when I create the channel.  In my TlsServerAuthorizationCheckInterface I check the server cert.  After digging into this It looks like on the server I am not setting the TlsServerAuthorizationCheckConfig.  I assume this why I am not able to validate the client.  

I will set the TlsServerAuthorizationCheckConfig on the server and see if that makes a difference.

Thanks for your help.

**Comment by noahdav** [comment]
@markdroth can you point me to mTLS examples?  On my server I am trying to validate the client.  After digging into this more 
I am trying to figure out how to validate the client cert on the channel.  Looking at the grpc_impl::experimental::TlsCredentialsOptions the server_authorization_auth_config is only valid on client credentials not server credentials.

grpc_impl::experimental::TlsCredentialsOptions options(
                GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_BUT_DONT_VERIFY,
                GRPC_TLS_SKIP_ALL_SERVER_VERIFICATION,
                config,
                nullptr,
                nullptr <-- config is only valid for client not server
                );

Is there a way to validate the client credentials on the server side?

**Comment by markdroth** [comment]
@jiangtaoli2016, can you please advise this user as to the right way to set up mTLS today?

**Comment by jiangtaoli2016** [comment]
Server authorization is designed for validating server's identity on the client side. In web PKI semantics, client verifies server's hostname against server's x509 cert. In SPIFFE, server's hostname does not necessarily match the SPIFFE identity in the server's x509 cert, thus we provide a server authz callback.

@noahdav Why standard certificate validation does not work in your use case?

**Comment by noahdav** [comment]
@jiangtaoli2016 I am trying to setup mutual auth.  We are a foundation service in Azure.  In this environment there is a custom PKI infrastructure certificate which in addition to TLS also has an ACL which needs to be verified.  On the client we use the TlsServerAuthorizationCheckConfig to validate the server cert matches the server ACL we expect.  However on the server we also need a way to validate the client ACL.  Currently on the server I validate the client certificate + acl through in the AuthProcessor but this occurs on every request and is too expensive to do this frequently.  I need a way to do this only when the channel is connected or a cert is revoked/replaced.

In addition to the ACL these certs are rotated at random intervals so we need a way to refresh them.  I am using the TlsCredentialReloadConfig to refresh both the client and server certs as needed.  I just set the new certificate which seems to work on the client.  From my testing I was able to repo this with the client but not yet for server.  Can you please confirm that this will also work for the server cert reload too.

**Comment by jiangtaoli2016** [comment]
I see you use case now.

@yihuazhang @ZhenLian FYI. Given grpc core does not support revocation check now. It may make sense to expose ServerAuthorizationCheckConfig to server side as well.  So that application can use this callback to do whatever per-connection check needed.

We may also want to rename it, rather than `ServerAuthorizationCheckConfig`, rename to `AuthorizationCheckConfig`

**Comment by noahdav** [comment]
Is this something you can provide in the near future?  If not can we provide a PR for this?  If so can you point me at anything to get me started?

**Comment by ZhenLian** [comment]
For changing `ServerAuthorizationCheckConfig` to `AuthorizationCheckConfig`, I can do the changes in Core as I am changing the tls_security_connector for new credential reloading logic, but I think this also involves updating the Core API and C++ wrapper, which might take some time. @jiangtaoli2016 are we sure we want to make such changes?
 TlsCredentialReloadConfig should work for both sides, but one thing to note here is that we are proposing a new credential reloading API. Once that is done, the current per-connection callback reloading will be replaced by a distributor-provider based reloading(imagine there is a class object where you can call setCredentials on it and we will pick up the updates in the new connections). In other words, TlsCredentialReloadConfig will go away in the future.

**Comment by jiangtaoli2016** [comment]
@ZhenLian Let's discuss offline.

**Comment by noahdav** [comment]
@ZhenLian this new distributor-provider based reloading sounds very intriguing to our scenario.  Since our certs regularly rotate and the old ones get deleted this seems like a perfect use case for this new provider.  We could just tell it that we have new certs when the cert is rotated before it is deleted.  Can you please give us more information on this and let us know when this is ready and we can start testing with this instead.

**Comment by noahdav** [comment]
@ZhenLian any update on this?

**Comment by ZhenLian** [comment]
Hi Noah, please see the gRFC here: https://github.com/grpc/proposal/pull/205
Roughly speaking, the new gRFC contains the following proposed changes:

1. TLS credentials and TLS options for users to set providers, custom authorization functions, etc
2. StaticDataCertificateProvider that will load static credential data
3. FileWatcherCertificateProvider that will load credential data from file system and periodically reload it
4. ExternalCertificateProvider that is implementable by users for custom provider implementation
5. Custom authorization improvements
6. TLS version selection

We've done task 1&2, and we are in the process of wrapping up task 3. My next planned task is 5, which should include the changes to make `AuthorizationCheckConfig` also available on the server side.
Feel free to let me know if you have any questions. Thanks!

**Comment by noahdav** [comment]
Thanks for the update.  I will look through this and get back to you with any questions.

**Comment by dineshR478** [comment]
@noahdav I am trying to use AuthMetadataProcessor to validate my client cert in server side. can you provide me your code for reference. I could not find the best one in internet.
