### ISSUE TITLE
Installation of grpc with pip in docker image very slow for x86_64

### ISSUE THREAD

**Issue by pwais** [grpc/grpc#23509]
### What version of gRPC and what language are you using?

GRPC version 1.30.1 (latest)
Python 3.6

### What operating system (Linux, Windows,...) and version?

Linux ubuntu bionic in docker on a linux x86_64 intel xeon host

### What runtime / compiler are you using (e.g. python version or version of gcc)

python

### What did you do?

I am trying to create a docker image that includes grpc for python installed via `pip3 install grpc grpcio-tools`.  But the command
`pip3 install grpcio grpcio-tools`
takes more than 15 minutes, even though this is a xeon host with 32 physical CPUs (NOT virtualized, NOT cloud machine).
My docker images uses `bionic-20200311` as a base image.  I have also tried using a different bionic base image and a different host and see the same issue.

### What did you expect to see?

A fast installation of grpc.  I hypothesize that the grpc build might be single-threaded and/or unnecessary (i.e. Google should be building and shipping x86_64 wheels; perhaps something is broken here? ).

### What did you see instead?

```
> Building wheels for collected packages: grpcio, grpcio-tools
>   Building wheel for grpcio (setup.py): started
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
>   Building wheel for grpcio (setup.py): still running...
```

### Anything else we should know about your project / environment?

See also https://github.com/grpc/grpc/issues/20493

**Comment by gnossen** [comment]
Try upgrading your version of pip. We do have precompiled x86-64 wheels, but they're manylinux2010. If your pip is too old, it won't recognize those artifacts and will instead default to installing from source. As for the slow from-source build, that is indeed a case of single-threaded compilation. That has now been parallelized by default on the master branch, but this has not made its way into a release yet.

**Comment by gnossen** [comment]
Going ahead and closing due to lack of response from the original poster. Feel free to reopen if you have any further trouble.

**Comment by wader** [comment]
`pip install --upgrade pip` fix it for me

**Comment by TalhaNaeem1** [comment]
pip install --upgrade pip did not fix it for me on python:3.8.9-alpine3.12 base image. @gnossen

**Comment by wader** [comment]
@TalhaNaeem1 If i remember correctly the cause of the slowness for me was that the grpc package somehow could not use any "wheel" variant of the package forced it to build from source. I think what variant can be used depends on pip version, package version and what OS/distribution you use. Maybe this helps https://stackoverflow.com/questions/37793046/how-does-pip-decide-which-many-linux-wheel-to-use

**Comment by TalhaNaeem1** [comment]
Thank you
