### ISSUE TITLE
Bazel RBE Debug C/C++ failure due to assertion failure

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23510]
https://source.cloud.google.com/results/invocations/7e2de56d-40ad-47e9-aa1d-fdeebc02a1aa/log

I0713 23:00:17.334909480      20 driver.cc:284]              Shutdown clients
I0713 23:00:17.334993122      20 driver.cc:303]              Finishing servers
I0713 23:00:17.335459687      20 driver.cc:319]              Receiving final status from servers
E0713 23:00:17.335501428      20 driver.cc:331]              Couldn't get final status from server 0
E0713 23:00:17.335531313      20 driver.cc:332]              assertion failed: false
I0713 23:00:17.484199367      17 json_run_localhost.cc:74]   driver: subprocess terminated with signal 6
I0713 23:00:17.484374421      17 json_run_localhost.cc:74]   worker: subprocess terminated with signal 6
E0713 23:00:20.859383347      17 json_run_localhost.cc:137]  assertion failed: driver_join_status == 0
Aborted (core dumped)
================================================================================
[37,245 / 37,253] 8238 / 8245 tests, 1 failed; Testing //test/cpp/qps:json_run_localhost_cpp_generic_async_streaming_qps_unconstrained_2waysharedcq_secure@poller=epollex; 15s remote ... (8 actions running)
INFO: Elapsed time: 273.838s, Critical Path: 97.01s
INFO: 19386 processes: 18286 remote cache hit, 1100 remote.
INFO: Build completed, 1 test FAILED, 37253 total actions

**Comment by yashykt** [comment]
This is outdated, and we decided not to track this here anyway
