### ISSUE TITLE
build_docker_go failure

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23518]
https://source.cloud.google.com/results/invocations/2cc4f644-55af-4bf6-9ab3-54312e60c4d9/log

Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2?go-get=1
golang.org/x/oauth2 (download)
Fetching https://golang.org/x/oauth2/google?go-get=1
Parsing meta tags from https://golang.org/x/oauth2/google?go-get=1 (status code 200)
get "golang.org/x/oauth2/google": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2/google?go-get=1
get "golang.org/x/oauth2/google": verifying non-authoritative meta tag
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
Fetching https://cloud.google.com/go/compute/metadata?go-get=1
Parsing meta tags from https://cloud.google.com/go/compute/metadata?go-get=1 (status code 200)
get "cloud.google.com/go/compute/metadata": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://github.com/googleapis/google-cloud-go"} at https://cloud.google.com/go/compute/metadata?go-get=1
get "cloud.google.com/go/compute/metadata": verifying non-authoritative meta tag
Fetching https://cloud.google.com/go?go-get=1
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
cloud.google.com/go (download)
Fetching https://golang.org/x/oauth2/jwt?go-get=1
Parsing meta tags from https://golang.org/x/oauth2/jwt?go-get=1 (status code 200)
get "golang.org/x/oauth2/jwt": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2/jwt?go-get=1
get "golang.org/x/oauth2/jwt": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/xds/experimental?go-get=1
Parsing meta tags from https://google.golang.org/grpc/xds/experimental?go-get=1 (status code 200)
get "google.golang.org/grpc/xds/experimental": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/xds/experimental?go-get=1
get "google.golang.org/grpc/xds/experimental": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
google.golang.org/grpc (download)
package google.golang.org/grpc/xds/experimental: cannot find package "google.golang.org/grpc/xds/experimental" in any of:
	/usr/local/go/src/google.golang.org/grpc/xds/experimental (from $GOROOT)
	/go/src/google.golang.org/grpc/xds/experimental (from $GOPATH)
github.com/golang/mock (download)
github.com/golang/glog (download)
github.com/cncf/udpa (download)
github.com/envoyproxy/protoc-gen-validate (download)
github.com/envoyproxy/go-control-plane (download)
github.com/census-instrumentation/opencensus-proto (download)
make: *** [Makefile:10: deps] Error 1

2020-07-16 15:35:14,896 FAILED: build_docker_go [ret=2, pid=10791, time=87.5sec]

**Comment by stanley-cheung** [comment]
This seems to be already fixed in #23515
