### ISSUE TITLE
Typed Exceptions for context.abort

### ISSUE THREAD

**Issue by robbrit** [grpc/grpc#23514]
### Is your feature request related to a problem? Please describe.

The problem is that in Python's `ServiceContext` when calling `abort()`, the exception raised is of type `Exception` with no arguments, so there's no clean way to catch these exceptions and take action.

This is important because we want to log most exceptions that are raised within the endpoint to Stackdriver, so that everything is channeled to GCP's Error Reporting API. There are some though like `NOT_FOUND` or `PERMISSION_DENIED` that we don't care about logging, since those aren't internal errors to us and end up just spamming our logs.

### Describe the solution you'd like
Instead of raising `Exception`, raise a sub-type. Re-using `grpc.RpcError` would be fine, so long as we can grab the gRPC status code from it.

### Describe alternatives you've considered

1. Accept the log spam. Not great since it crowds out actual issues, and makes monitoring much more complicated.
1. Filter out the exceptions based on the stack trace.
1. Use our own exceptions instead of calling `context.abort`, skip logging when exceptions we don't care about are thrown, and then call `context.abort` with the proper arguments.

**Comment by hijerusalem** [comment]
+1
