### ISSUE TITLE
C# tests all succeed but test script exits with code 1

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#2351]
[Job](https://travis-ci.org/grpc/grpc/jobs/70277908).

[Log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/70277908/log.txt).
![Image of a Log](https://openclipart.org/download/218084/Log_Side.svg)

**Comment by jtattermusch** [comment]
Really? 
What I see is 
The command "./tools/run_tests/run_tests.py -l $TEST -t -j $JOBS -c $CONFIG -s 4.0" exited with 0.

Feel free to reopen if you don't agree.

**Comment by soltanmm** [comment]
(... Does Travis overwrite log files after builds are restarted?)
