### ISSUE TITLE
compatibility with async_grpc

### ISSUE THREAD

**Issue by Wkkkkk** [grpc/grpc#23546]
### What version of gRPC and what language are you using?
gRPC1.29.1, C++

### What operating system (Linux, Windows,...) and version?
Linux Mint 19.3(Ubuntu 18.04)

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++8.4

### What did you do?
I've been using cartographer-project/async_grpc in my project for a long time. Recently when I recompiled the aysnc_grpc library with the latest gRPC, I found that there is a compiling error saying the use of deleted function ‘grpc_impl::CompletionQueue::CompletionQueue(const grpc_impl::CompletionQueue&)’.

As I traced it down to grpc_impl::CompletionQueue in grpcpp/impl/codegen/completion_queue_impl.h, I found the newly added member variables which make this class uncopyable(since class grpc::internal::Mutex is uncopyable).

```
  // List of servers associated with this CQ. Even though this is only used with
  // NDEBUG, instantiate it in all cases since otherwise the size will be
  // inconsistent.
  mutable grpc::internal::Mutex server_list_mutex_;
  std::list<const Server*> server_list_ /* GUARDED_BY(server_list_mutex_) */;
```
Therefore I add Marco NDEBUG for this part and it worked. The result looks like this.

```
#ifndef NDEBUG
  // List of servers associated with this CQ. Even though this is only used with
  // NDEBUG, instantiate it in all cases since otherwise the size will be
  // inconsistent.
  mutable grpc::internal::Mutex server_list_mutex_;
  std::list<const Server*> server_list_ /* GUARDED_BY(server_list_mutex_) */;
#endif
```

In my case, this Marco is defined so both server_list_mutex_ and server_list_ won't be defined. Therefore CompletionQueue is copyable and async_grpc will be able to define things like std::vector < CompletionQueue > . But I don't know whether it's the correct way to handle this error and whether the inconsistent size warning from the annotation will cause any further issue.

Looking forward to hearing from you.

**Comment by PeakDing** [comment]
Do you solved the problem? Can you give me some advise? and the old grpc version you use?

**Comment by Wkkkkk** [comment]
> Do you solve the problem? Can you give me some advise? and the old grpc version you use?@Wkkkkk
Kind of solved. I was using gRPC1.29.1.
1. find file grpcpp/impl/codegen/completion_queue_impl.h
2. find the following part of code
`
  // List of servers associated with this CQ. Even though this is only used with
  // NDEBUG, instantiate it in all cases since otherwise the size will be
  // inconsistent.
  mutable grpc::internal::Mutex server_list_mutex_;
  std::list<const Server*> server_list_ /* GUARDED_BY(server_list_mutex_) */;
`
3. use Marco NDEBUG to wrap it, just like this 
`
#ifndef NDEBUG
// the code
#endif
`
4. that's all.

Reason for doing this is already explained in the last part of my question.

**Comment by clarkzinzow** [comment]
I ran into this as well upon upgrading gRPC, temporarily solved by changing our `std::vector<grpc::CompletionQueue>` to a `std::vector<std::unique_ptr<grpc::CompletionQueue>>`, although this isn't optimal for our async gRPC layer.

**Comment by Wkkkkk** [comment]
That's brilliant. Just make grpc::CompletionQueue movable/copyable.

**Comment by veblush** [comment]
I don't think there is something gRPC team can do for this. Please reopen this or make PR.
