### ISSUE TITLE
Time cost for each step of a request in GRPC c++?

### ISSUE THREAD

**Issue by ljch2018** [grpc/grpc#23547]
I implemented client and server on  GRPC c++，and met a wired problem.
It costs 122ms for each request in the client side, but it only costs 60ms in server side.（Time cost for calling my Business function.）
The server and client are deploy in the same machine, so time cost of  network is limited.

I want to  checkout why grpc framework cost 62ms for each request ? 
First, I used the following variables to print all debug messages, but found no time cost information.
```
export GRPC_TRACE=all;
export GRPC_VERBOSITY=DEBUG
```
Second, I found [server_interceptors_end2end_test.cc](https://github.com/grpc/grpc/blob/7bf82de9eda0aa8fecfe5edb33834f1b272be30b/test/cpp/end2end/server_interceptors_end2end_test.c), but it fails to print time cost inside the framework.

Sincerely，Thanks for your time.

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
