### ISSUE TITLE
Why there are no makefile in examples/cpp/keyvaluestore directory?

### ISSUE THREAD

**Issue by Murphy-OrangeMud** [grpc/grpc#23542]
Hi, I'm new to grpc and cmake. 
I tried to do what the tutorial says to the key-value store project but I found there were no makefile in it. Why ? So how should I compile the project? Or is it a bug?
Thanks for replying.

**Comment by yashykt** [comment]
Hi, gRPC is trying to move away from Makefiles and is preferring bazel instead.
