### ISSUE TITLE
signal 6 in grpc_chttp2_settings_create

### ISSUE THREAD

**Issue by jiapeish** [grpc/grpc#23551]
### What version of gRPC and what language are you using?
1.26.0
C++

### What operating system (Linux, Windows,...) and version?
LInux 3.10

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5

### What did you do?
We use grpc to connect to ETCD V3.4.6, in our production environment, the process with etcd client(which uses grpc) restart after about 6 days. A signal 6 occured.

### What did you expect to see?
We expect to see the process which uses grpc run stably at least for 7 * 24 hours.

### What did you see instead?
Coredump occured.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Stack:
gsignal+0xb0
abort+0x154
_Z27grpc_chttp2_settings_createPjPKjjm+0x1e4
_Z23grpc_chttp2_begin_writeP21grpc_chttp2_transport+0xe48
0xffffb04e2f0c
_Z31grpc_combiner_continue_exec_ctxv+0x184
_ZN9grpc_core7ExecCtx5FlushEv+0x6c        0x0000ffffb04b2f6c - ffffb0438000
0xffffb04c44ac - ffffb0438000 = 8 C4AC                  <_Z19grpc_timer_heap_popP15grpc_timer_heap@@Base>:
0xffffb056e918 - ffffb0438000 = 13 6918                 <_ZN9grpc_core21GlobalConfigEnvString3SetEPKc@@Base>  
0xffffb865d8bc                                          libpthread-2.28.so
0xffffb85a59fc                                          libpthread-2.28.so

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by karthikravis** [comment]
@jiapeish : thanks for the issue. can you please provide a simple repro test so it will be helpful to root cause the issue? Thanks!

**Comment by jiapeish** [comment]
It's a bit hard to provide a repro test since this coredump has a low probability. 

We're continue testing it, if it's reproduced, I'll update the status.

**Comment by jiapeish** [comment]
This issue happen again in the ARM environment, I suspect this coredump is more likely to happen in some cpu architecture.

**Comment by yashykt** [comment]
Please re-open with a repro/more details if this issue still persists.
