### ISSUE TITLE
Unable to run Hello World C# client on Linux

### ISSUE THREAD

**Issue by abravo73** [grpc/grpc#23566]
### What version of gRPC and what language are you using?
2.23, C#

### What operating system (Linux, Windows,...) and version?
Embedded Linux with ARM Cortex A8 processor

### What runtime / compiler are you using (e.g. python version or version of gcc)
Microsoft Visual Studio 2019

### What did you do?
I compiled the Greeter solution in Visual Studio and copied the GreeterClient and GreeterServer netcoreapp2.1 files over to my Linux computer.

### What did you expect to see?
The server started up with no problems. I expected the client to work as described in the example (Calls SayHello and gets a response).

### What did you see instead?
D0721 10:48:02.129084 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/home/root/ms/GreeterClient/libgrpc_csharp_ext.x86.so"
D0721 10:48:02.797480 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0721 10:48:02.810664 1074606624 /home/mitydsp/grpc/src/core/lib/iomgr/is_epollexclusive_available.cc:86: epoll_ctl with EPOLLEXCLUSIVE | EPOLLONESHOT succeeded. This is evidence of no EPOLLEXCLUSIVE support. Not using epollex polling engine.
I0721 10:48:02.814539 1074606624 /home/mitydsp/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1630: Skipping epollex because it is not supported.
I0721 10:48:02.815882 1074606624 /home/mitydsp/grpc/src/core/lib/iomgr/ev_epoll1_linux.cc:121: grpc epoll fd: 38
D0721 10:48:02.816584 1074606624 /home/mitydsp/grpc/src/core/lib/iomgr/ev_posix.cc:173: Using polling engine: epoll1
D0721 10:48:02.818049 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "grpclb"
D0721 10:48:02.818751 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "cds_experimental"
D0721 10:48:02.819392 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "eds_experimental"
D0721 10:48:02.820032 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "lrs_experimental"
D0721 10:48:02.820643 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "priority_experimental"
D0721 10:48:02.821101 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "weighted_target_experimental"
D0721 10:48:02.821558 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "xds_routing_experimental"
D0721 10:48:02.822169 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "pick_first"
D0721 10:48:02.822688 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:39: registering LB policy factory for "round_robin"
D0721 10:48:02.823176 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:504: Using ares dns resolver
E0721 10:48:02.826960 1074606624 /home/mitydsp/grpc/src/core/lib/debug/trace.cc:65: Unknown trace var: 'client_call_channel'
I0721 10:48:03.532709 1074606624 /home/mitydsp/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc:378: Disabling AF_INET6 sockets because socket() failed.
D0721 10:48:03.538599 1074606624 /home/mitydsp/grpc/src/core/lib/iomgr/tcp_posix.cc:1812: cannot set inq fd=44 errno=92
I0721 10:48:03.540705 1074606624 /home/mitydsp/grpc/src/core/ext/filters/client_channel/subchannel.cc:1085: New connected subchannel at 0x26c050 for subchannel 0x26b0b0
E0721 10:48:03.542475 1074606624 /home/mitydsp/grpc/src/core/lib/slice/slice_buffer.cc:380: assertion failed: sb->count > 0
Aborted

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I'm just trying to run the Hello World example on my embedded Linux computer to test out .NET core and gRPC. I am running .NET core runtime 3.1.5.

**Comment by jtattermusch** [comment]
The Grpc.Core package uses a pre-compiled native c-core library internally and the nuget package doesn't contain a pre-compiled version of that binary (libgrpc_csharp_ext) for ARM processors.
for .NET desktop / .NET core we currently only support Intel processors.

In theory you can pre-compile the right libgrpc_csharp_ext binary for your platform and use it, but it requires some nontrivial expertise.

**Comment by jtattermusch** [comment]
Alternatively, you can also try using https://github.com/grpc/grpc-dotnet (which is fully managed and doesn't have the native library limitation)
