### ISSUE TITLE
Support building without c-ares in CMake

### ISSUE THREAD

**Issue by eldruin** [grpc/grpc#23589]
### What version of gRPC and what language are you using?
1.30.2 - C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04, 18.04, Windows 10, macOS (Mojave, Catalina)

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC5, GCC7, VS2017, VS2019, Apple LLVM version 10.0.1 (clang-1001.0.46.4), Apple clang version 11.0.3 (clang-1103.0.32.62)

### What did you do?
Attempt to build without the c-ares library using CMake.

### What did you expect to see?
I expected to be able to deactivate the use of c-ares and use the native DNS resolver instead (src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc)
I expected failure to find the c-ares library would result in a `-DGRPC_ARES=0` definition.

### What did you see instead?
> src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:23:10: fatal error: ares.h: No such file or directory

### Anything else we should know about your project / environment?
This can be solved by adding an `else` case at the end of the `cmake/cares.cmake` file:

```
# ...
else()
  add_definitions(-DGRPC_ARES=0)
endif()
```
After doing this gRPC for C++ and Python (the languages that we use) build fine.

I can prepare a PR doing this if you are interested.

**Comment by jtattermusch** [comment]
We don't want to make our build more complex by adding more build options than necessary (=more build options also means combinatorial explosion of scenarios to test / maintain and we don't what to do that).

If you want to use the "native" DNS resolver, you can achieve that at runtime (no rebuild needed at all) by setting env variable `GRPC_DNS_RESOLVER=native` (see more documentation in https://github.com/grpc/grpc/blob/master/doc/environment_variables.md).

**Comment by jtattermusch** [comment]
(Closed because what you needed to do is already supported and no changes to build are required).

**Comment by eldruin** [comment]
The problem I have is that the c-ares library is always necessary at build time, although we do not want to use it or install it in all our supported (build) platforms.
Anyway for anybody interested, the workaround I listed above works just fine.
