### ISSUE TITLE
Error in deserializing message from a stream

### ISSUE THREAD

**Issue by andreafresa** [grpc/grpc#23584]
### What version of gRPC and what language are you using?
grpcio=1.30.0 (Python)

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8.2

### What did you do?
I am receiving a message from a Client with the following protobuf
`syntax ="proto3";

package nbsb;

message SDF {
    Thing thing = 1;
    repeated Object objects = 2;
    string type = 3;
}

message Property {
    string name = 1;
    string value = 2;
}
message Thing {
    string id = 1;
    string name = 2;
}
message Object {
    repeated string idObject = 1;
    string name = 2;
    repeated Property properties = 3;
}

message Response {
    repeated string id = 1;
    string value = 2;
}

service Connector{
    rpc Get(SDF) returns (Response){}
    rpc Put(SDF) returns (Response){}
    rpc Post(stream SDF) returns (stream SDF){}
}

`

The called rpc method is Post.
When I am receiving the message here it is what I am doing:
`def Post(self, request_iterator, context):
        print("Post")
        for request in request_iterator:
            print("Request")
            if hasattr(request , "type"):
                print("Has type")`

### What did you expect to see?
Deserialized message from the stream

### What did you see instead?
But I get the following error:
ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
  File "C:\Python\Python3\lib\site-packages\grpc\_common.py", line 84, in _transform
    return transformer(message)
  File "C:\Python\Python3\lib\site-packages\google\protobuf\internal\python_message.py", line 1082, in SerializeToString
    if not self.IsInitialized():
AttributeError: 'NoneType' object has no attribute 'IsInitialized'
But I tried to print the message in transformer method and it seems to arrive ( b'\n\r\n\x011\x12\x08RobotArm\x12\x17\n\x08Gripper1\x12\x0bGripperType\x1a\x0bOpenGripper')
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
The client is in Javascript,

**Comment by lidizheng** [comment]
Is it possible to provide an end to end reproduction case? This is a normal gRPC code path we tests extensively. There could be other factors that makes the request iterator malfunction.
