### ISSUE TITLE
Unity C#: Xcode reports libgrpc_csharp_ext.a does not contain bitcode

### ISSUE THREAD

**Issue by sramosubi** [grpc/grpc#23606]
Hi,

I'm having [this same issue](https://github.com/grpc/grpc/issues/16839) on version 2.30. I saw on the repo that bitcode was enabled to solve the issue, but then the change was reverted. Would it be possible to keep bitcode enabled?

Thank you.

**Comment by shubear** [comment]
I am facing the same issue on 2.35 and unable to build for grpc with ios and tvos. Tried to build with ENABLE_BITCODE set to false for both Unity-iPhone and UnityFramework, however the build continues to fail. Any suggestions on how I could work around this ?

**Comment by shubear** [comment]
I dug a little deeper and tried both the provided experimental build (without bitcode) and a custom build (with bitcode.)
In both scenarios I ended up with the following error
`Undefined symbols for architecture arm64:
  "_deflateInit2_", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _z_deflateInit2_, _il2cpp_z_deflateInit2_ )
  "_deflate", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_compress_gzip(grpc_stream_compression_context*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, grpc_stream_compression_flush) in libgrpc.a(stream_compression_gzip.o)
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _unity_z_deflateCopy, _unity_z_deflateTune , _unity_z_deflatePending , _unity_z_deflateSetHeader , _unity_z_deflateResetKeep , _unity_z_deflateParams , _il2cpp_z_deflate_copyright , _il2cpp_z_deflateTune , _il2cpp_z_deflatePrime , _il2cpp_z_deflatePending , _il2cpp_z_deflateSetHeader , _il2cpp_z_deflateGetDictionary , _il2cpp_z_deflateResetKeep , _il2cpp_z_deflateReset , _il2cpp_z_deflateInit_ , _unity_z_deflatePrime , _z_deflateInit_ , _z_deflateInit2_ , _unity_z_deflateEnd , _il2cpp_z_deflate , _il2cpp_z_deflateInit2_ , _unity_z_deflate , _unity_z_deflateSetDictionary , _il2cpp_z_deflateCopy , _il2cpp_z_deflateSetDictionary , _unity_z_deflate_copyright , _il2cpp_z_deflateParams , _unity_z_deflateBound , _unity_z_deflateReset , _il2cpp_z_deflateBound , _unity_z_deflateGetDictionary , _il2cpp_z_deflateEnd )
  "_inflate", referenced from:
      zlib_decompress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_decompress_gzip(grpc_stream_compression_context*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, bool*) in libgrpc.a(stream_compression_gzip.o)
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in libgrpc.a(stream_compression_gzip.o)
      grpc_stream_compression_context_destroy_gzip(grpc_stream_compression_context*) in libgrpc.a(stream_compression_gzip.o)
      gzip_flate(grpc_stream_compression_context_gzip*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, int, bool*) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _unity_z_inflate_copyright, _unity_z_inflateUndermine , _unity_z_inflateCopy , _unity_z_inflateSyncPoint , _unity_z_inflateSync , _unity_z_inflateGetHeader , _unity_z_inflateSetDictionary , _unity_z_inflatePrime , _il2cpp_z_inflate_copyright , _z_inflateInit_ , _unity_z_inflateBack , _unity_z_inflateBackInit_ , _il2cpp_z_inflateCodesUsed , _il2cpp_z_inflateValidate , _il2cpp_z_inflateCopy , _il2cpp_z_inflateSetDictionary , _il2cpp_z_inflate_fast , _il2cpp_z_inflatePrime , _il2cpp_z_inflateInit_ , _il2cpp_z_inflateReset , _il2cpp_z_inflateResetKeep , _unity_z_inflateReset2 , _png_zlib_inflate , _unity_z_inflate , _unity_z_inflateReset , _il2cpp_method_is_inflated , _il2cpp_class_is_inflated , scripting_class_is_inflated(ScriptingClassPtr) , _unity_z_inflateGetDictionary , _il2cpp_z_inflate , _il2cpp_z_inflateEnd , _il2cpp_z_inflateMark , _il2cpp_z_inflateUndermine , _il2cpp_z_inflateSyncPoint , il2cpp_codegen_inflate_generic_class(Il2CppClass*, Il2CppGenericInst const*) , _unity_z_inflateCodesUsed , _unity_z_inflateEnd , _unity_z_inflateMark , _unity_z_inflate_fast , _il2cpp_z_inflateReset2 , _z_inflateInit2_ , _unity_z_inflate_table , _il2cpp_z_inflateGetHeader , _unity_z_inflateResetKeep , _unity_z_inflateValidate , _il2cpp_z_inflateGetDictionary , _unity_z_inflateBackEnd , _il2cpp_z_inflate_table , _il2cpp_z_inflateSync , _il2cpp_z_inflateInit2_ )
  "_deflateEnd", referenced from:
      zlib_compress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_compression_context_destroy_gzip(grpc_stream_compression_context*) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _unity_z_deflateEnd, _il2cpp_z_deflateEnd )
  "_inflateInit2_", referenced from:
      zlib_decompress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_compression_context_create_gzip(grpc_stream_compression_method) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _z_inflateInit2_, _il2cpp_z_inflateInit2_ )
  "_inflateEnd", referenced from:
      zlib_decompress(grpc_slice_buffer*, grpc_slice_buffer*, int) in libgrpc.a(message_compress.o)
      grpc_stream_compression_context_destroy_gzip(grpc_stream_compression_context*) in libgrpc.a(stream_compression_gzip.o)
     (maybe you meant: _il2cpp_z_inflateEnd, _unity_z_inflateEnd )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by shubear** [comment]
I managed to get it running by adding `libz.tbd` as a library on UnityFramework. The steps to build with unity ios should be added to the experimental readme.
I figured it out from: https://github.com/Cysharp/MagicOnion#ios-build-with-grpc

**Comment by rdcm** [comment]
@shubear Thanks a lot!

Look like I have something similar:
https://github.com/grpc/grpc/issues/25522

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
