### ISSUE TITLE
what does lameduck as a verb is this repo mean?

### ISSUE THREAD

**Issue by techieshark** [grpc/grpc#23621]
RE: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

As a small improvement, could the docs be updated to clarify what is meant here? 

HTTP2 Code | GRPC Code
-- | --
NO_ERROR(0) | INTERNAL - An explicit GRPC status of OK should have been sent but this might be used to aggressively lameduck in some scenarios.

Questions that arise:

1) What does "lameduck" mean? This seems a creative reuse of a political term that could perhaps be made more clear.

2) Similarly... what does "aggressively lameduck" mean? Perhaps a reference to the current US president after Nov. 3rd?

3) "....in some scenarios." what scenarios?

I'm trying to understand this error code as I'm seeing the following error in logs (coming from grpc-js used by google-gax):

```
Error: 13 INTERNAL: Received RST_STREAM with code 0"  
```

**Comment by donnadionne** [comment]
Please direct general question like this one to https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.

**Comment by techieshark** [comment]
hi @donnadionne thanks for the quick actioning on this! :)

I've updated the title to reflect the fact that I was actually suggesting a change in this repo rather than asking a question. Apologies that wasn't clear earlier.

Given that the change is being proposed in a *documentation file*, it does not seem acceptable to send people off to another _documentation_ site (stackoverflow). Rather, I would hope the doc linked in the issue could be fixed to not use what appears to be (based on searching stackoverflow and Google) a Google-specific jargon that is otherwise undefined (at least: publicly).

Could this be re-opened? 

Thanks for your help :)
