### ISSUE TITLE
Referencing gRPC causes csproj to always rebuild 

### ISSUE THREAD

**Issue by rdconnelly** [grpc/grpc#23622]
### What version of gRPC and what language are you using?
Grpc and Grpc.Core version 2.30.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSBuild

### What did you do?

Added a reference to a Grpc and Grpc.Core reference to my csproj

### What did you expect to see?

The project is not rebuilt after a successful build, unless changes are made.

### What did you see instead?

The project is always rebuilt. 

I believe this commit is the culprit https://github.com/grpc/grpc/commit/e071b7d0f9c496a3b47febe7f694b496d4c0fa51 , which was done to address https://github.com/grpc/grpc/issues/20782

**Comment by jtattermusch** [comment]
Interesting. https://github.com/grpc/grpc/pull/20859 might really be causing this.
Can you confirm that with Grpc.Core v1.25.0 (before the PR got introduced) doesn't suffer from this problem?

If we confirm that https://github.com/grpc/grpc/pull/20859 has caused this, we can revert it, but that would also break https://github.com/grpc/grpc/issues/20782 again. We'd have to see which one is worse.

**Comment by jtattermusch** [comment]
Should be fixed by #23391.
