### ISSUE TITLE
API for setting User-Agent in Python port

### ISSUE THREAD

**Issue by kotori2** [grpc/grpc#23644]
### Is your feature request related to a problem? Please describe.
It seems API for setting customized User-Agent was already added years before. #2661
But there seems not having any Python API for that. I also tried setting metadata like
```
metadata=[
            ["user-agent", "grpc-csharp/2.24.0-dev grpc-c/8.0.0 (ios; chttp2; ganges)"]
        ]
```
but it doesn't work.

### Describe the solution you'd like
add an API for Python to set User-Agent header, or make user-agent header in metadata working.

### Describe alternatives you've considered
Haven't looked into the code.

### Additional context
my code here
```
  def server_info(self):
        channel = grpc.secure_channel("CENSORED:443", self.credentials)
        stub = MQRPC_pb2_grpc.MQRPC_EntrypointsStub(channel)
        resp = stub.Current(MQRPC_pb2.EntrypointsCurrentRequest(
            deviceType=self.platform,
            clientVersion=self.version
        ), metadata=[
            ["user-agent", "MyGame/1.0.0"],
            ["accept-language", "zh"]
        ])
        print(resp)
```

**Comment by gnossen** [comment]
As the PR you referenced points out, this was implemented in Core years ago. While it's not well documented and not especially pretty, you should be able to access [that functionality](https://github.com/grpc/grpc/blob/6c3ec4460f51f6b8a509381dbd3eedef43f75c90/include/grpc/impl/codegen/grpc_types.h#L247) today like this:

```python
 channel = grpc.secure_channel("CENSORED:443",
    self.credentials,
    options=(("grpc.primary_user_agent", "MyGame/1.0.0"),))
```
