### ISSUE TITLE
google/cloud-firestore v1.11.0 requires ext-grpc * -> the requested PHP extension grpc is missing from your system.

### ISSUE THREAD

**Issue by CodeNinjaUG** [grpc/grpc#23646]
- google/cloud-firestore v1.11.0 requires ext-grpc * -> the requested PHP extension grpc is missing from your system.
We have an issue with grpc extension i have installed it and followed the guide but its not being seen by compilers nor being seen any anywhere i keep getting errors of that sort no changes i have changed the php.ini file and downloaded the extnesion from pecl site and placed it in the php/ext folder bt its not being seen am trying to to work with google cloud firestore what could be the issue.??

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
