### ISSUE TITLE
Failure: XdsTest/ClientLoadReportingWithDropTest.Vanilla/XdsResolverV3WithLoadReporting

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#23674]
Test expectation failure seen in this test running on MSAN:

```
test/cpp/end2end/xds_end2end_test.cc:5191
Expected equality of these values:
  num_drops
    Which is: 831
  client_stats.total_dropped_requests()
    Which is: 757
```

https://source.cloud.google.com/results/invocations/0e01a31e-0c2d-487c-bd38-ccd12254cbe0/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Dpoll/tests

Seen in https://github.com/grpc/grpc/pull/23670

**Comment by markdroth** [comment]
@donnadionne just fixed this in #23662.
