### ISSUE TITLE
Client DNS Resolution with Internal Kubernetes Service

### ISSUE THREAD

**Issue by maganaluis** [grpc/grpc#23681]
### What version of gRPC and what language are you using?

Python==3.8
grpcio==1.30.0
grpcio-tools==1.30.0
protobuf==3.12.4

### What operating system (Linux, Windows,...) and version?

Docker Image: 
```
tiangolo/uvicorn-gunicorn:python3.8
```

Kubernetes Version: 
1.16

Vendor:
Azure 

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

DNS resolution does not work when we pass the internal Kubernetes version

```
client = dex_api.DexStub(grpc.insecure_channel("dex-grpc.auth.svc.cluster.local:5557"))
```

It only works if you explicitly pass the ClusterIP for that service

```
client = dex_api.DexStub(grpc.insecure_channel("10.0.105.63:5557"))
```

### What did you expect to see?

DNS resolution should work with internal Kubernetes services.

### What did you see instead?

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed"
	debug_error_string = "{"created":"@1596122930.480295305","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1596122930.480289905","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":216,"referenced_errors":[{"created":"@1596122930.480288605","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":375,"grpc_status":14,"referenced_errors":[{"created":"@1596122930.480269503","description":"C-ares status is not ARES_SUCCESS qtype=A name=dex-grpc.auth.svc.cluster.local is_balancer=0: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":287}]}]}]}"
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
This looks like a problem with your local DNS configuration.  The relevant part of the error is shown in the debug error string:

```
C-ares status is not ARES_SUCCESS qtype=A name=dex-grpc.auth.svc.cluster.local is_balancer=0: Domain name not found
```

If you need more help, please try one of these forums:

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by maganaluis** [comment]
@markdroth Thank you, I also tried switching the GRPC service to a ClusterIP instead of a NodePort and worked as expected. Posting here in case someone runs into this issue. 

```

apiVersion: v1
kind: Service
metadata:
  name: dex-ci
  namespace: auth
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 5557
    protocol: TCP
    targetPort: 5557
  selector:
    app: dex
```

**Comment by harishks** [comment]
@maganaluis Was `dex-grpc` the service name or the app-port combination based key? I am running into a similar issue. Thanks!

**Comment by maganaluis** [comment]
> @maganaluis Was `dex-grpc` the service name or the app-port combination based key? I am running into a similar issue. Thanks!

This was when accessing the service internally within the cluster

**Comment by Kewei-Lu** [comment]
@maganaluis Hi, did you find the root cause of such the problem? I am facing a similar issue. Thanks!
