### ISSUE TITLE
Grpc.Tools: Allow passing --experimental_allow_proto3_optional (protoc flag) in <protobuf/> definition

### ISSUE THREAD

**Issue by JohnGalt1717** [grpc/grpc#23686]
### Is your feature request related to a problem? Please describe.
Right now it's impossible to use items under feature flags like optional with C# as far as I can tell from the docs, multiple stackoverflow posts and looking in the source code.

### Describe the solution you'd like
The <Protobuf/> definition in the csproj files should allow passing options to protoc and this should be documented on HOW to do so.

### Describe alternatives you've considered
I've tried using GrpcOutputOptions as appears might do something in the docs with "experimental_allow_proto3_optional" and "--experimental_allow_proto3_optional" as posibilities and neither worked. I also tried the same with GrpcOptions as well with the same results.

### Additional context
I think that all options that you could manually pass to protoc should be available on the C# Grpc.Tools.
Note that I posted about this here: https://github.com/grpc/grpc-dotnet/issues/977#issuecomment-663252909 and they instructed me to come here.  I believe that I've determined that either the documentation is incomplete and needs to be updated, or this isn't supported and needs to be.

Also note line 72 here: https://chromium.googlesource.com/external/github.com/protocolbuffers/protobuf/+/refs/heads/master/CHANGES.txt which says that this needs to be implemented by the generator.  One would assume that this would generate classes that use nullable types if the csproj had them enabled.

**Comment by stanley-cheung** [comment]
There is another way to test proto3 optional when the feature is under experimental. See https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#satisfying-the-experimental-check

> 2. Make your filename (or a directory name) contain the string test_proto3_optional. This indicates that the proto file is specifically for testing proto3 optional support, so the check is suppressed.

There is an example there:

```
# Another option:
$ cp test.proto test_proto3_optional.proto
$ ./src/protoc test_proto3_optional.proto --cpp_out=.
```

So you can try that with `--csharp_out` and the corresponding `--grpc_out` I suppose.

**Comment by msschl** [comment]
Needed feature 👍 

@stanley-cheung I tried your suggestion but unfortunately it's not working.

**Comment by kskalski** [comment]
I tried to put the ``test_proto3_optional`` as part of directory name, but it doesn't seem to work:
```
  C:\Users\kamil\.nuget\packages\grpc.tools\2.31.0\tools\windows_x86\protoc.exe --csharp_out=obj\Debug\netstandard2.0 --proto_path=C:\Users\kamil\.nuget\packages\grpc.tools\2.31.0\build\native\include --proto_path=protos_test_proto3_optional --dependency_out=obj\Debug\netstandard2.0\3ff48a2dbec97afb_voting_session.protodep --error_format=msvs protos_test_proto3_optional\voting_session.proto
voting_session.proto : error : This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set. [D:\rep\Kogut\src\VotingKernel\VotingKernel.csproj]
```

I will try putting it directly to .proto filename, or maybe it needs to be part of the subdirectory name below ``--proto_path`` ?

**Comment by kskalski** [comment]
Ok, both putting ``test_proto3_optional`` into filename and in subdirectory of ``--proto_path`` work to enable ``optional`` fields, a bit of pity, since I need to modify all the imports to contain that string one way or the other.

**Comment by jtattermusch** [comment]
This is now possible by using https://github.com/grpc/grpc/pull/25374
