### ISSUE TITLE
PHP7 pecl install error make: *** [Makefile:1774: third_party/upb/upb/upb.lo] Error 1

### ISSUE THREAD

**Issue by act28** [grpc/grpc#23698]
### What version of gRPC and what language are you using?
gRPC 1.30.0 stable, PHP 7.4.8, PEAR Version: 1.10.12

### What operating system (Linux, Windows,...) and version?
Linux manjaro 5.4.52-1-MANJARO #1 SMP PREEMPT Thu Jul 16 16:07:11 UTC 2020 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 10.1.0 (GCC)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

`sudo pecl install grpc`

### What did you expect to see?

Package installed successfully

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
```
...
/tmp/pear/temp/grpc/third_party/upb/upb/upb.c: In function ‘upb_status_seterrmsg’:
/tmp/pear/temp/grpc/third_party/upb/upb/upb.c:40:3: error: ‘strncpy’ specified bound 127 equals destination size [-Werror=stringop-truncation]
   40 |   strncpy(status->msg, msg, sizeof(status->msg));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/grpc/third_party/upb/upb/upb.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:1774: third_party/upb/upb/upb.lo] Error 1
ERROR: `make' failed
```

**Comment by stanley-cheung** [comment]
Looks like this has been fixed upstream in https://github.com/protocolbuffers/upb/pull/268 (https://github.com/protocolbuffers/upb/issues/262). 

For grpc php version `1.30.0`, looks like the `upb` dependency was older than the fix: https://github.com/grpc/grpc/tree/v1.30.x/third_party/upb (last updated in Jan 2020, before the fix above). 

But for grpc php version `1.31.0`, looks like the `upb` dependency should be newer than the fix: https://github.com/grpc/grpc/tree/v1.31.x/third_party/upb (last updated in Jun 2020, after the fix above).

So can you please try the PECL extension `1.31.0` to see if the issue still exists?

**Comment by act28** [comment]
@stanley-cheung thanks, that fixed it

**Comment by christianr11** [comment]
Thanks. Using grpc 1.31.0 fixed the problem. Im using php:7.4-fpm-alpine. GCC Version: 10.2.1
