### ISSUE TITLE
//test/cpp/util:byte_buffer_test failed

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23708]
https://source.cloud.google.com/results/invocations/e96c8f93-0ac8-455f-b2ff-814c3e9b1532/log

test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Func_class<_Ret,ServiceType *,ServerContextType *,RequestType *,grpc_impl::ServerAsyncWriter<grpc::testing::SimpleResponse> *,grpc::CompletionQueue *,grpc::ServerCompletionQueue *,void *>::_Reset_impl': decorated name length exceeded, name was truncated
        with
        [
            _Ret=void,
            ServiceType=grpc::testing::BenchmarkService::AsyncService,
            ServerContextType=grpc::ServerContext,
            RequestType=grpc::testing::SimpleRequest
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Func_class<_Ret,ServerContextType *,RequestType *,grpc_impl::ServerAsyncResponseWriter<grpc::testing::SimpleResponse> *,void *>::_Reset_impl': decorated name length exceeded, name was truncated
        with
        [
            _Ret=void,
            ServerContextType=grpc::ServerContext,
            RequestType=grpc::testing::SimpleRequest
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator<_Ty>::construct': decorated name length exceeded, name was truncated
        with
        [
            _Ty=std::unique_ptr<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::ServerRpcContext,std::default_delete<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::ServerRpcContext>>
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Func_class<_Ret,ServerContextType *,grpc_impl::ServerAsyncReaderWriter<grpc::testing::SimpleResponse,grpc::testing::SimpleRequest> *,void *>::_Reset_impl': decorated name length exceeded, name was truncated
        with
        [
            _Ret=void,
            ServerContextType=grpc::ServerContext
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Func_class<_Ret,ServerContextType *,grpc_impl::ServerAsyncReader<grpc::testing::SimpleResponse,grpc::testing::SimpleRequest> *,void *>::_Reset_impl': decorated name length exceeded, name was truncated
        with
        [
            _Ret=void,
            ServerContextType=grpc::ServerContext
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Func_class<_Ret,ServerContextType *,RequestType *,grpc_impl::ServerAsyncWriter<grpc::testing::SimpleResponse> *,void *>::_Reset_impl': decorated name length exceeded, name was truncated
        with
        [
            _Ret=void,
            ServerContextType=grpc::ServerContext,
            RequestType=grpc::testing::SimpleRequest
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator<_Ty>::construct': decorated name length exceeded, name was truncated
        with
        [
            _Ty=std::unique_ptr<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::PerThreadShutdownState,std::default_delete<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::PerThreadShutdownState>>
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator_traits<_Alloc>::destroy': decorated name length exceeded, name was truncated
        with
        [
            _Alloc=std::allocator<std::unique_ptr<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::PerThreadShutdownState,std::default_delete<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::PerThreadShutdownState>>>
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator_traits<_Alloc>::destroy': decorated name length exceeded, name was truncated
        with
        [
            _Alloc=std::allocator<std::unique_ptr<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::ServerRpcContext,std::default_delete<grpc::testing::AsyncQpsServerTest<grpc::testing::SimpleRequest,grpc::testing::SimpleResponse,grpc::testing::BenchmarkService::AsyncService,grpc::ServerContext>::ServerRpcContext>>>
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Uninitialized_move_al_unchecked': decorated name length exceeded, name was truncated
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Wrap_alloc<std::allocator<_Other>>::construct': decorated name length exceeded, name was truncated
        with
        [
            _Other=_Myimpl
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::_Uninitialized_move_al_unchecked1': decorated name length exceeded, name was truncated
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator_traits<_Alloc>::destroy': decorated name length exceeded, name was truncated
        with
        [
            _Alloc=std::allocator<_Myimpl>
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator_traits<_Alloc>::construct': decorated name length exceeded, name was truncated
        with
        [
            _Alloc=std::allocator<_Myimpl>
        ]
test/cpp/qps/server_async.cc(595): warning C4503: 'std::allocator<_Other>::construct': decorated name length exceeded, name was truncated
        with
        [
            _Other=_Myimpl
        ]
[12,577 / 12,677] 1926 / 2009 tests; Linking test/cpp/server/load_reporter/lb_load_data_store_test.exe; 26s remote ... (100 actions running)
[12,621 / 12,700] 1940 / 2009 tests; Linking test/cpp/server/load_reporter/lb_load_data_store_test.exe; 74s remote ... (79 actions running)
[12,680 / 12,729] 1963 / 2009 tests; Linking test/cpp/server/load_reporter/lb_load_data_store_test.exe; 126s remote ... (49 actions running)
FAIL: //test/cpp/util:byte_buffer_test (see C:/users/builder/_bazel_kbuilder/lndsuir7/execroot/com_github_grpc_grpc/bazel-out/x64_windows-dbg/testlogs/test/cpp/util/byte_buffer_test/test.log)
INFO: From Testing //test/cpp/util:byte_buffer_test:
==================== Test output for //test/cpp/util:byte_buffer_test:

**Comment by veblush** [comment]
Closing (obsolete)
