### ISSUE TITLE
Grpc.Tools 2.30 does not generate correct client code.

### ISSUE THREAD

**Issue by obiwanjacobi** [grpc/grpc#23713]
Doing my first grpc greeter sample (template) and following the tutorial to create a C# client.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio

The following code does not compile with Grpc.Tools v2.30 (`Greeter.GreeterClient` does not exist)
```csharp
var client =  new Greeter.GreeterClient(channel);
```
Grpc.Tools v2.29 works fine.

HIH/2c

**Comment by jtattermusch** [comment]
The code you provided definitely should continue working just fine. Can you provide a full reproduction of your problem (an actual .csproj and other needed files, e.g. as a github repo) and also include more additional info (platform, VS version, .NET SDK version, ...) ? Otherwise it seems this seems as some mistake on your side, because problem likely this definitely wouldn't go unnoticed.

**Comment by obiwanjacobi** [comment]
Here you go:
https://github.com/obiwanjacobi/Grpc23713

**Comment by jtattermusch** [comment]
With you example " dotnet build Grpc23713.sln" has passed on a mac. I'll try on other platforms.

**Comment by jtattermusch** [comment]
"dotnet build Grpc23713.sln" has also passed on a Windows machine for me.

 dotnet --version
3.1.301

**Comment by jtattermusch** [comment]
I was also able to build without problems with Version 16.6.2 (by opening the solution in the UI and clicking "build solution).
Looks like the problem isn't reproducible?

**Comment by obiwanjacobi** [comment]
I hate it when that happens :-)
It may not be a problem with v2.30 specifically because I also had this issue when adding a new .proto to my existing (then working) project... After some fiddling it generated the client class correctly - of course I am not sure what I did exactly.

Would it help if I turn on detailed logging?

This is the code that is generated on my machine - it's missing the client class.

```csharp
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/greet.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcService1 {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class Greeter
  {
    static readonly string __ServiceName = "greet.Greeter";

    static readonly grpc::Marshaller<global::GrpcService1.HelloRequest> __Marshaller_greet_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService1.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService1.HelloReply> __Marshaller_greet_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService1.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcService1.HelloRequest, global::GrpcService1.HelloReply> __Method_SayHello = new grpc::Method<global::GrpcService1.HelloRequest, global::GrpcService1.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_greet_HelloRequest,
        __Marshaller_greet_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcService1.GreetReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Greeter</summary>
    [grpc::BindServiceMethod(typeof(Greeter), "BindService")]
    public abstract partial class GreeterBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GrpcService1.HelloReply> SayHello(global::GrpcService1.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GreeterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GreeterBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService1.HelloRequest, global::GrpcService1.HelloReply>(serviceImpl.SayHello));
    }

  }
}
#endregion
```

**Comment by DrHardReset** [comment]
Today I was setting up my first grpc greeter sample, too.
I faced the exactly same problem like you when using the tutorial  https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio.

In step "Add greet.proto" I added the following to my project file:

```xml
<ItemGroup>
  <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
</ItemGroup>
```

As it just added a folder with a dead link to my project, I deleted the link and added the file "greet.proto" myself.
This led to default file properties what leaded to missing generating of client code. Then I corrected the properties as shown in the attachment, client code gets generated as expected.

Hope this helps.
![greet_proto_fileproperties](https://user-images.githubusercontent.com/35699007/90034601-22de1500-dcc1-11ea-8297-900f575d07ed.PNG)

**Comment by jtattermusch** [comment]
Looks like the problem was due to incorrectly setting `"GrpcServices="Server"` in `<Protobuf ... />`?

**Comment by obiwanjacobi** [comment]
@jtattermusch that is the server/service! That should say `Server`!
The problem is in the client -the console app in my example- which has the correct setting:
https://github.com/obiwanjacobi/Grpc23713/blob/afa629e6b36ac65532a844b3e8c40b31de75c942/ConsoleApp1/ConsoleApp1.csproj#L22
Please reopen the issue.

**Comment by jtattermusch** [comment]
@obiwanjacobi  are you saying that you can reproduce with "dotnet build Grpc23713.sln" on windows with dotnet SDK 3.1.302?

Also, in https://github.com/grpc/grpc/issues/23713#issuecomment-669702130 you mentioned that things started working for you "after some fiddling" - so it's unclear whether you can still reproduce or if the problem went away.
Without a proper reproduction there's little we can do unfortunately.

**Comment by obiwanjacobi** [comment]
I tried the following:
1. Added a copy of greet.proto to the server. Named it greet2 and changed the package, namespace and service name with a 2-postfix.
2. Dragged and dropped the new .proto file into my client (console) project. That generated an entry in the .csproj file with `GrpcServices="Server"` - changed that to Client and saved the .csproj. 
3. Tagged on the 2-postfix to the code in Program.cs to use the new proto definition.
4. Build `dotnet build Grpc23713.sln` fails. The client class was not generated.

So somehow it seems to be linked to the way I add a new proto file to the client project?

Deleting the obj folder and rebuilding fixes the issue (regenerating).
Hope this helps.

**Comment by grempel** [comment]
Very similar problem. I could not use my service unless it was a modification of the greet.proto sample. I could not rename it.
The solution: The proto file in your server should be set to Server Only. The copy of the proto file in my Client must be set to Client Only.
Duplicating the file will cause problems - if I could figure out how to use the same proto in two places I would.
Thanks.

**Comment by alexv-be** [comment]
I was looking around the web for this behavior. My issue was not that it did not recompile, but I did the following:
1. create grpc service from vs template
2. compile, test all good.
3. remove the Services/GreeterService.cs
4. Recompile -> failure.
5. Put endpoints.MapGrpcService<GreeterService>(); in Startup.cs in comments so it compiles, giving it a chance to regenerate the GreeterService.cs --> no luck, no GreeterService.cs
6. If you enable "show all files in VS" you can see in the obj/ folder that the necessary files are generated.
7. If you then implement the  base class Greeter.GreeterBase and re-enable the code in startup.cs all is fine.

Not really the issue as advertised, but it was confusing to me.
hth

**Comment by inforzip** [comment]
I'm having the same problem in WPF and UWP projects, I'm looking for a solution for days and nothing.
My Error	CS0246	The type or namespace name 'Greeter' could not be found (are you missing a using directive or an assembly reference?)
Visual generates classes from proto file, but missssing the namespace.

**Comment by fabiorosadev** [comment]
Hi guys... 
I don't know if is the same problem that you have here... but I've found this topic when I started develop my first gRPC tutorial  from Microsoft Website: https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio-code

And I had the same problem: It won't generate the client code.... 

After some research, I tried install this packages on client project:
- Grpc.Tools
- Google.Protobuf

After that, I rebuild the project and the client code was generated successfully!

**Comment by freddy311082** [comment]
> Hi guys... I don't know if is the same problem that you have here... but I've found this topic when I started develop my first gRPC tutorial from Microsoft Website: https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio-code
> 
> And I had the same problem: It won't generate the client code....
> 
> After some research, I tried install this packages on client project:
> 
> * Grpc.Tools
> * Google.Protobuf
> 
> After that, I rebuild the project and the client code was generated successfully!

I'm using macOS and I followed the same guide and the client is not generated. I have the same problem

**Comment by tonydnewell** [comment]
I don't believe there is anything wrong with the code generation.  I've successfully followed the instructions.

The Microsoft documentation could be clearer and more explicit e.g. for the _Visual Studio Code_ version it says _"Build the client project to create the types in the GrpcGreeterClient namespace."_ without saying how to do the build.  When in doubt go to the command line and use:
`dotnet build` for building and `dotnet run` for running.
