### ISSUE TITLE
csharp_macos_dbg_native_csharp_Grpc_Reflection_Tests_ReflectionClientServerTest.csharp.Grpc.Reflection.Tests.ReflectionClientServerTest failed

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23725]
https://source.cloud.google.com/results/invocations/8149aab6-0b5a-4b14-ba4a-3e9cecdc2bbf/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_macos_dbg_native%2Fcsharp.Grpc.Reflection.Tests.ReflectionClientServerTest/tests

Test Files
    /Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_macos_dbg_native/src/csharp/Grpc.Reflection.Tests/bin/Debug/net45/Grpc.Reflection.Tests.exe

Test Filters
    Test: Grpc.Reflection.Tests.ReflectionClientServerTest

=> Grpc.Reflection.Tests.ReflectionClientServerTest
D0803 11:39:29.092033 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_macos_dbg_native/src/csharp/Grpc.Reflection.Tests/bin/Debug/net45/libgrpc_csharp_ext.x64.dylib"
D0803 11:39:29.157919 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
=> Grpc.Reflection.Tests.ReflectionClientServerTest.FileByFilename
=> Grpc.Reflection.Tests.ReflectionClientServerTest.FileByFilename_NotFound
=> Grpc.Reflection.Tests.ReflectionClientServerTest.FileContainingExtension
=> Grpc.Reflection.Tests.ReflectionClientServerTest.FileContainingSymbol
=> Grpc.Reflection.Tests.ReflectionClientServerTest.FileContainingSymbol_NotFound
=> Grpc.Reflection.Tests.ReflectionClientServerTest.ListServices
Stacktrace:

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object

**Comment by jtattermusch** [comment]
The test hasn't failed in the last 100 days.
