### ISSUE TITLE
[Objc] Install gRPC plugins and libraries failed with "error: use of undeclared identifier 'GRPC_ARG_HTTP_PROXY' "

### ISSUE THREAD

**Issue by XinLin** [grpc/grpc#23722]
I followed steps [here](https://grpc.io/docs/languages/objective-c/quickstart/) 
v1.30.0

Failed on step:

Install gRPC plugins and libraries

$ cd grpc
$ make

Here are the logs:
xinlinp@xinlinp-C02XG1R5JGH6 grpc % make
[MAKE]    Generating /Users/xinlinp/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /Users/xinlinp/grpc/libs/opt/pkgconfig/gpr.pc
[MAKE]    Generating /Users/xinlinp/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling third_party/address_sorting/address_sorting.c
[C]       Compiling third_party/address_sorting/address_sorting_posix.c
third_party/address_sorting/address_sorting_posix.c:54:42: warning: unused parameter 'factory' [-Wunused-parameter]
    address_sorting_source_addr_factory* factory,
                                         ^
1 warning generated.
[C]       Compiling third_party/address_sorting/address_sorting_windows.c
[AR]      Creating /Users/xinlinp/grpc/libs/opt/libaddress_sorting.a
[C]       Compiling third_party/upb/upb/decode.c
third_party/upb/upb/decode.c:164:20: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and
      'int' [-Wsign-compare]
  CHK(d->end_group == field_number);
      ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
third_party/upb/upb/decode.c:48:22: note: expanded from macro 'CHK'
#define CHK(x) if (!(x)) { return 0; }
                     ^
third_party/upb/upb/decode.c:325:20: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and
      'int' [-Wsign-compare]
  CHK(d->end_group == field_number);
      ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
third_party/upb/upb/decode.c:48:22: note: expanded from macro 'CHK'
#define CHK(x) if (!(x)) { return 0; }
                     ^
2 warnings generated.
[C]       Compiling third_party/upb/upb/encode.c
[C]       Compiling third_party/upb/upb/msg.c
[C]       Compiling third_party/upb/upb/port.c
[C]       Compiling third_party/upb/upb/table.c
[C]       Compiling third_party/upb/upb/upb.c
[AR]      Creating /Users/xinlinp/grpc/libs/opt/libupb.a
[CXX]     Compiling third_party/abseil-cpp/absl/base/dynamic_annotations.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/cycleclock.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/raw_logging.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/spinlock.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/spinlock_wait.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/sysinfo.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/thread_identity.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/throw_delegate.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.cc
[CXX]     Compiling third_party/abseil-cpp/absl/base/log_severity.cc
[CXX]     Compiling third_party/abseil-cpp/absl/numeric/int128.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/ascii.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/charconv.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/escaping.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/charconv_bigint.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc
third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integers of different signs:
      'std::size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    } else if (post_decimal_digits > digits_left) {
               ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~
third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integers of different signs:
      'std::size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    } else if (post_decimal_digits > digits_left) {
               ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~
third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:497:22: note: in instantiation of function template
      specialization 'absl::lts_2020_02_25::strings_internal::ParseFloat<10>' requested here
template ParsedFloat ParseFloat<10>(const char* begin, const char* end,
                     ^
third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integers of different signs:
      'std::size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    } else if (post_decimal_digits > digits_left) {
               ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~
third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:499:22: note: in instantiation of function template
      specialization 'absl::lts_2020_02_25::strings_internal::ParseFloat<16>' requested here
template ParsedFloat ParseFloat<16>(const char* begin, const char* end,
                     ^
3 warnings generated.
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/escaping.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/memutil.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/ostringstream.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/str_format/arg.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/str_format/bind.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/str_format/extension.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/str_format/float_conversion.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/str_format/output.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/str_format/parser.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/internal/utf8.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/match.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/numbers.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/str_cat.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/str_replace.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/str_split.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/string_view.cc
[CXX]     Compiling third_party/abseil-cpp/absl/strings/substitute.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/civil_time.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/clock.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/duration.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/format.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/civil_time_detail.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_fixed.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_format.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_if.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_info.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_lookup.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_posix.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/internal/cctz/src/zone_info_source.cc
[CXX]     Compiling third_party/abseil-cpp/absl/time/time.cc
[CXX]     Compiling third_party/abseil-cpp/absl/types/bad_optional_access.cc
[AR]      Creating /Users/xinlinp/grpc/libs/opt/libgrpc_abseil.a
/Applications/Xcode.11.2.1.11B500.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (escaping.o) in output file used for input files: /Users/xinlinp/grpc/objs/opt/third_party/abseil-cpp/absl/strings/internal/escaping.o and: /Users/xinlinp/grpc/objs/opt/third_party/abseil-cpp/absl/strings/escaping.o (due to use of basename, truncation, blank padding or duplicate input files)
[CXX]     Compiling src/core/lib/gpr/alloc.cc
[CXX]     Compiling src/core/lib/gpr/atm.cc
[CXX]     Compiling src/core/lib/gpr/cpu_iphone.cc
[CXX]     Compiling src/core/lib/gpr/cpu_linux.cc
[CXX]     Compiling src/core/lib/gpr/cpu_posix.cc
[CXX]     Compiling src/core/lib/gpr/cpu_windows.cc
[CXX]     Compiling src/core/lib/gpr/env_linux.cc
[CXX]     Compiling src/core/lib/gpr/env_posix.cc
[CXX]     Compiling src/core/lib/gpr/env_windows.cc
[CXX]     Compiling src/core/lib/gpr/log.cc
[CXX]     Compiling src/core/lib/gpr/log_android.cc
[CXX]     Compiling src/core/lib/gpr/log_linux.cc
[CXX]     Compiling src/core/lib/gpr/log_posix.cc
[CXX]     Compiling src/core/lib/gpr/log_windows.cc
[CXX]     Compiling src/core/lib/gpr/murmur_hash.cc
[CXX]     Compiling src/core/lib/gpr/string.cc
[CXX]     Compiling src/core/lib/gpr/string_posix.cc
[CXX]     Compiling src/core/lib/gpr/string_util_windows.cc
[CXX]     Compiling src/core/lib/gpr/string_windows.cc
[CXX]     Compiling src/core/lib/gpr/sync.cc
[CXX]     Compiling src/core/lib/gpr/sync_abseil.cc
[CXX]     Compiling src/core/lib/gpr/sync_posix.cc
[CXX]     Compiling src/core/lib/gpr/sync_windows.cc
[CXX]     Compiling src/core/lib/gpr/time.cc
[CXX]     Compiling src/core/lib/gpr/time_posix.cc
[CXX]     Compiling src/core/lib/gpr/time_precise.cc
[CXX]     Compiling src/core/lib/gpr/time_windows.cc
[CXX]     Compiling src/core/lib/gpr/tls_pthread.cc
[CXX]     Compiling src/core/lib/gpr/tmpfile_msys.cc
[CXX]     Compiling src/core/lib/gpr/tmpfile_posix.cc
[CXX]     Compiling src/core/lib/gpr/tmpfile_windows.cc
[CXX]     Compiling src/core/lib/gpr/wrap_memcpy.cc
[CXX]     Compiling src/core/lib/gprpp/arena.cc
[CXX]     Compiling src/core/lib/gprpp/fork.cc
[CXX]     Compiling src/core/lib/gprpp/global_config_env.cc
[CXX]     Compiling src/core/lib/gprpp/host_port.cc
[CXX]     Compiling src/core/lib/gprpp/mpscq.cc
[CXX]     Compiling src/core/lib/gprpp/thd_posix.cc
[CXX]     Compiling src/core/lib/gprpp/thd_windows.cc
[CXX]     Compiling src/core/lib/profiling/basic_timers.cc
[CXX]     Compiling src/core/lib/profiling/stap_timers.cc
[AR]      Creating /Users/xinlinp/grpc/libs/opt/libgpr.a
[CXX]     Compiling src/core/ext/filters/census/grpc_context.cc
[CXX]     Compiling src/core/ext/filters/client_channel/backend_metric.cc
In file included from src/core/ext/filters/client_channel/backend_metric.cc:23:
In file included from src/core/ext/upb-generated/udpa/data/orca/v1/orca_load_report.upb.h:12:
third_party/upb/upb/generated_util.h:44:61: warning: unused parameter 'type' [-Wunused-parameter]
                                            upb_fieldtype_t type,
                                                            ^
1 warning generated.
[CXX]     Compiling src/core/ext/filters/client_channel/backup_poller.cc
[CXX]     Compiling src/core/ext/filters/client_channel/channel_connectivity.cc
[CXX]     Compiling src/core/ext/filters/client_channel/client_channel.cc
[CXX]     Compiling src/core/ext/filters/client_channel/client_channel_channelz.cc
[CXX]     Compiling src/core/ext/filters/client_channel/client_channel_factory.cc
[CXX]     Compiling src/core/ext/filters/client_channel/client_channel_plugin.cc
[CXX]     Compiling src/core/ext/filters/client_channel/global_subchannel_pool.cc
[CXX]     Compiling src/core/ext/filters/client_channel/health/health_check_client.cc
In file included from src/core/ext/filters/client_channel/health/health_check_client.cc:31:
In file included from src/core/ext/upb-generated/src/proto/grpc/health/v1/health.upb.h:12:
third_party/upb/upb/generated_util.h:44:61: warning: unused parameter 'type' [-Wunused-parameter]
                                            upb_fieldtype_t type,
                                                            ^
1 warning generated.
[CXX]     Compiling src/core/ext/filters/client_channel/http_connect_handshaker.cc
[CXX]     Compiling src/core/ext/filters/client_channel/http_proxy.cc
src/core/ext/filters/client_channel/http_proxy.cc:63:54: error: use of undeclared identifier 'GRPC_ARG_HTTP_PROXY'
      gpr_strdup(grpc_channel_args_find_string(args, GRPC_ARG_HTTP_PROXY));
                                                     ^
1 error generated.
make: *** [/Users/xinlinp/grpc/objs/opt/src/core/ext/filters/client_channel/http_proxy.o] Error 1

**Comment by yulin-liang** [comment]
Hi Xinlin, can you try the following commands?
```
$ make clean
$ git submodule update --init
$ make
```
If it doesn't work, please let me know.

**Comment by XinLin** [comment]
Same error here after

[CXX]     Compiling src/core/ext/filters/client_channel/http_proxy.cc
src/core/ext/filters/client_channel/http_proxy.cc:63:54: error: use of undeclared identifier
      'GRPC_ARG_HTTP_PROXY'
      gpr_strdup(grpc_channel_args_find_string(args, GRPC_ARG_HTTP_PROXY));
                                                     ^
1 error generated.
make: *** [/Users/xinlinp/grpc/objs/opt/src/core/ext/filters/client_channel/http_proxy.o] Error 1

**Comment by XinLin** [comment]
I can see `GRPC_ARG_HTTP_PROXY` was defined in `~/grpc/include/grpc/impl/codegen/gpr_types.h `

**Comment by XinLin** [comment]
my OS is MacOS 10.15.6

**Comment by yulin-liang** [comment]
Xinlin, have you tried other versions? Does this issue also happen?

**Comment by yulin-liang** [comment]
It's really weird, I tried it on three mac machines, but I couldn't reproduce it. Can you follow the [C++ instruction](https://grpc.io/docs/languages/cpp/quickstart/) and use `cmake` to install gRPC plugins. Let's see if it provides more details.

**Comment by XinLin** [comment]
Thanks for your quick response!

Yeah, I saw that `make` was deprecated so I will try bazel now...

I tried v1.29.1 and it had a different issue there:

Undefined symbols for architecture x86_64:
  "grpc_core::SplitHostPort(absl::lts_2020_02_25::string_view, std::__1::unique_ptr<char, grpc_core::DefaultDeleteChar>*, std::__1::unique_ptr<char, grpc_core::DefaultDeleteChar>*)", referenced from:
      grpc_core::(anonymous namespace)::HttpProxyMapper::MapName(char const*, grpc_channel_args const*, char**, grpc_channel_args**) in http_proxy.o
      grpc_parse_ipv4_hostport(char const*, grpc_resolved_address*, bool) in parse_address.o
      grpc_parse_ipv6_hostport(char const*, grpc_resolved_address*, bool) in parse_address.o
      grpc_dns_lookup_ares_continue_after_check_localhost_and_ip_literals_locked(grpc_ares_request*, char const*, char const*, char const*, grpc_pollset_set*, int, grpc_core::Combiner*) in grpc_ares_wrapper.o
      grpc_dns_lookup_ares_locked_impl(char const*, char const*, char const*, grpc_pollset_set*, grpc_closure*, std::__1::unique_ptr<absl::lts_2020_02_25::InlinedVector<grpc_core::ServerAddress, 1ul, std::__1::allocator<grpc_core::ServerAddress> >, std::__1::default_delete<absl::lts_2020_02_25::InlinedVector<grpc_core::ServerAddress, 1ul, std::__1::allocator<grpc_core::ServerAddress> > > >*, std::__1::unique_ptr<absl::lts_2020_02_25::InlinedVector<grpc_core::ServerAddress, 1ul, std::__1::allocator<grpc_core::ServerAddress> >, std::__1::default_delete<absl::lts_2020_02_25::InlinedVector<grpc_core::ServerAddress, 1ul, std::__1::allocator<grpc_core::ServerAddress> > > >*, char**, int, grpc_core::Combiner*) in grpc_ares_wrapper.o
      grpc_core::channelz::(anonymous namespace)::PopulateSocketAddressJson(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, grpc_core::Json, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, grpc_core::Json> > >*, char const*, char const*) in channelz.o
      try_split_host_port(char const*, char const*, std::__1::unique_ptr<char, grpc_core::DefaultDeleteChar>*, std::__1::unique_ptr<char, grpc_core::DefaultDeleteChar>*) in resolve_address_custom.o
      ...
  "grpc_core::SplitHostPort(absl::lts_2020_02_25::string_view, absl::lts_2020_02_25::string_view*, absl::lts_2020_02_25::string_view*)", referenced from:
      (anonymous namespace)::grpc_fake_channel_security_connector::check_call_host(absl::lts_2020_02_25::string_view, grpc_auth_context*, grpc_closure*, grpc_error**) in fake_security_connector.o
      grpc_ssl_channel_security_connector_create(grpc_core::RefCountedPtr<grpc_channel_credentials>, grpc_core::RefCountedPtr<grpc_call_credentials>, grpc_ssl_config const*, char const*, char const*, tsi_ssl_session_cache*) in ssl_security_connector.o
      grpc_ssl_check_peer_name(absl::lts_2020_02_25::string_view, tsi_peer const*) in ssl_utils.o
      grpc_ssl_host_matches_name(tsi_peer const*, absl::lts_2020_02_25::string_view) in ssl_utils.o
      grpc_ssl_check_call_host(absl::lts_2020_02_25::string_view, absl::lts_2020_02_25::string_view, absl::lts_2020_02_25::string_view, grpc_auth_context*, grpc_error**) in ssl_utils.o
      grpc_core::TlsChannelSecurityConnector::TlsChannelSecurityConnector(grpc_core::RefCountedPtr<grpc_channel_credentials>, grpc_core::RefCountedPtr<grpc_call_credentials>, char const*, char const*) in tls_security_connector.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/xinlinp/grpc_1_29_1/libs/opt/libgrpc.dylib] Error 1

**Comment by XinLin** [comment]
what should I do after I did:
```
# From the grpc repository root

# Build gRPC C++
$ bazel build :all
```
? @yulin-liang

**Comment by yulin-liang** [comment]
You can take a look at this instruction(https://github.com/grpc/grpc/tree/master/examples/objective-c/helloworld). The last section is running the example with `Bazel`.

**Comment by XinLin** [comment]
thanks, I followed the cmake steps and this is only way we can run the gRPC HelloWorld!

**Comment by yulin-liang** [comment]
So glad that `cmake` works. It's really weird that `make` failed on your machine. We have tests using makefile on macos, and I couldn't reproduce it on three different mac machines. Looks like it's probably related to your environment.
