### ISSUE TITLE
build_artifact.python_manylinux2010_x64_cp37-cp37m failed

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23724]
https://source.cloud.google.com/results/invocations/b4044dad-7f94-4099-833c-437a63ee4ad0/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_build_artifacts/log

grpcio_tools-1.32.0.dev0-cp37-cp37m-linux_x86_64.whl is consistent
with the following platform tag: "manylinux2010_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libgcc_s.so.1 with versions {'GCC_3.0'},
libc.so.6 with versions {'GLIBC_2.2.5', 'GLIBC_2.4'}, libpthread.so.0
with versions {'GLIBC_2.2.5'}, libstdc++.so.6 with versions
{'GLIBCXX_3.4.10', 'CXXABI_1.3', 'GLIBCXX_3.4.11', 'GLIBCXX_3.4',
'GLIBCXX_3.4.9'}

This constrains the platform tag to "manylinux2010_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
with the following platform tag: "manylinux2010_x86_64".
This constrains the platform tag to "manylinux2010_x86_64". In order
+ auditwheel repair tools/distrib/python/grpcio_tools/dist/grpcio_tools-1.32.0.dev0-cp37-cp37m-linux_x86_64.whl -w /var/local/git/grpc/artifacts/python_manylinux2010_x64_cp37-cp37m
INFO:auditwheel.main_repair:Repairing grpcio_tools-1.32.0.dev0-cp37-cp37m-linux_x86_64.whl
INFO:auditwheel.wheeltools:Previous filename tags: linux_x86_64
INFO:auditwheel.wheeltools:New filename tags: manylinux2010_x86_64
INFO:auditwheel.wheeltools:Previous WHEEL info tags: cp37-cp37m-linux_x86_64
INFO:auditwheel.wheeltools:New WHEEL info tags: cp37-cp37m-manylinux2010_x86_64
INFO:auditwheel.main_repair:
Fixed-up wheel written to /var/local/git/grpc/artifacts/python_manylinux2010_x64_cp37-cp37m/grpcio_tools-1.32.0.dev0-cp37-cp37m-manylinux2010_x86_64.whl
+ rm tools/distrib/python/grpcio_tools/dist/grpcio_tools-1.32.0.dev0-cp37-cp37m-linux_x86_64.whl
+ '[' TRUE '!=' '' ']'
+ /opt/python/cp37-cp37m/bin/pip install -rrequirements.txt
ERROR: Could not install packages due to an EnvironmentError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
You should consider upgrading via the '/opt/_internal/cpython-3.7.7/bin/python3.7 -m pip install --upgrade pip' command.
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc/artifacts
+ docker cp build_and_run_docker_436e347f-8f80-4b02-99ec-004a6afeffb2:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
+ docker rm -f build_and_run_docker_436e347f-8f80-4b02-99ec-004a6afeffb2
build_and_run_docker_436e347f-8f80-4b02-99ec-004a6afeffb2
+ '[' true '!=' '' ']'
+ exit 1

2020-08-03 12:14:10,299 FAILED: build_artifact.python_manylinux2010_x64_cp37-cp37m [ret=1, pid=26972, time=684.4sec]

**Comment by gnossen** [comment]
This looks like a transient connection error to PyPi, the Python package manager. Let's hold off on this until we see it causing more problems.

**Comment by JScon01** [comment]
Please stop sending me these Emails!

Jeffrey H. Conz
