### ISSUE TITLE
The current Makefile is not applicable to non-Intel platforms(like arm). 

### ISSUE THREAD

**Issue by jijiwawa** [grpc/grpc#23751]
### What version of gRPC and what language are you using?
branch master
c++

### What operating system (Linux, Windows,...) and version?
Linux centos7.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.3

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
When i compile grpc on the ARM Platform ,meeting a error like this 
"c++: error: unrecognized command line option ‘-msse4’"

### What did you expect to see?
Compilation is complete and no error occurs. 

### What did you see instead?
![image](https://user-images.githubusercontent.com/33614409/89499640-ec048c80-d7f2-11ea-8844-a8a0b0d8e33c.png)
AES/SSE is not supported on the ARM platform.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
None

**Comment by ljluestc** [comment]
Would it be possible for you to attach a text format log instead of a screenshot? This would greatly help with quicker triage and analysis of the issue.

**Comment by yashykt** [comment]
please re-open the issue with the exact steps to reproduce
