### ISSUE TITLE
Go client timeout on Interop Cloud to Cloud tests

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#23750]
All the interop cloud-to-cloud tests involving Go clients seem to start failing since 11am Aug 5 PDT. 

Dashboard (master): https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud

Log example: https://source.cloud.google.com/results/invocations/b429d843-9d0d-4fb5-a90c-0bcf43414373/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud/log

Cloud-to-Prod seems to be fine.

**Comment by menghanl** [comment]
Potentially caused by grpc/grpc-go#3786
@easwars is taking a look

**Comment by easwars** [comment]
This should take care: https://github.com/grpc/grpc-go/pull/3804

**Comment by stanley-cheung** [comment]
Looks like we are getting back some green builds! Will monitor a little more. Thanks!
