### ISSUE TITLE
grpc::ServiceAccountJWTAccessCredentials generates JWT token with = padding

### ISSUE THREAD

**Issue by yxue** [grpc/grpc#23754]
### What version of gRPC and what language are you using?
c++

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Client side:
I am using `grpc::ServiceAccountJWTAccessCredentials` to add JWT token in the grpc request. 

```cpp
channel_credentials = grpc::SslCredentials(ssl_options);
channel_args.SetSslTargetNameOverride(options.ssl_domain_name);
// json key is from the service account key file
auto call_credentials = grpc::ServiceAccountJWTAccessCredentials(json_key, 6000);
auto composite = grpc::CompositeChannelCredentials(channel_credentials, call_credentials);
```

Server side:
I am using Envoy as the ingress gateway. The Envoy proxy is configured with authn filter which fails to parse the JWT token. I copied the JWT token from the Envoy log and verified in the [jwt.io.](http://www.jwt.io). The jwt.io reports some warning: 
> Warning: Looks like your JWT payload is not encoded correctly using base64url ... Note that the padding ("=") must be omitted...

### What did you expect to see?
JWT token is either rejected or accepted. 

### What did you see instead?
Failed to parse the jwt token.

**Comment by jiangtaoli2016** [comment]
I suspect the problem is on the Envoy side. Please check with Envoy folks first.

**Comment by yxue** [comment]
Thanks! @jiangtaoli2016 I check the authorization header in Envoy log in the server side and found the "=" in the jwt token. Is there any way to dump the request in the client side to help diagnose?
