### ISSUE TITLE
14 socket closed

### ISSUE THREAD

**Issue by ps142020** [grpc/grpc#23753]
Hi, I am running C++ helloworld with client and server on different terminal on ubuntu 18.04 and see "14: Socket closed" I see previously many folks faced this but did not see a root cause or solution, can someone help?  This happens continuously for me. This is the first time am running grpc. Attaching the logs of client server collected with GRPC_VERBOSITY=debug GRPC_TRACE=tcp,http,api

cmake version 3.18.1
grpc 1.30.2
protobuf 3.12.2
[server_grpc.docx](https://github.com/grpc/grpc/files/5034703/server_grpc.docx)
[client_grpc.docx](https://github.com/grpc/grpc/files/5034705/client_grpc.docx)

**Comment by ps142020** [comment]
@nicolasnoble any thoughts on this issue? i am unable to make any progress with gRPC

**Comment by ps142020** [comment]
@lukasgit pls see above

**Comment by apolcyn** [comment]
Please paste the client and server log file contents directly into this github issue, rather than linked to as docx files.

**Comment by lukasgit** [comment]
#2427

**Comment by lukasgit** [comment]
This issue is being tracked in https://github.com/googleapis/google-cloud-php/issues/2427
