### ISSUE TITLE
GRPC Setup for CPP client server using Visual Studio 2017

### ISSUE THREAD

**Issue by Nithisha-BR** [grpc/grpc#23761]
Hi,

Myself Nithish. I want to use GRPC for one of my application. I am using Visual Studio 2017 with CPP.  I am not getting proper channel to setup the environment for windows system using visual studio to use GRPC. Kindly guide me to the proper channel. Any help will be appreciated.

**Comment by apolcyn** [comment]
Please see the examples under the examples directory on this repo as a starting point.

This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
