### ISSUE TITLE
Dropped status codes from `gsec_aead_crypter_decrypt_iovec()`

### ISSUE THREAD

**Issue by ErrReporter** [grpc/grpc#23775]
### What version of gRPC and what language are you using?
ec216362a1247c378e9cbab4eecaa19f31837b3b
Latest

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Examine the code.

### What did you expect to see?
The original status codes should be preserved as `GRPC_STATUS_INVALID_ARGUMENT` or anything else at https://github.com/grpc/grpc/blob/ec216362a1247c378e9cbab4eecaa19f31837b3b/src/core/tsi/alts/zero_copy_frame_protector/alts_iovec_record_protocol.cc#L408-L416, rather than translated to `GRPC_STATUS_INTERNAL`.

Or is there a special motivation behind this change?

### What did you see instead?

Dropped status codes.

**Comment by apolcyn** [comment]
This issue doesn't appear refer to any actual problem, so I'm going to close. If this causes a real issue, then please explain what the problem is that this causes. Ideally in the form of a reproducibly failing test.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by ErrReporter** [comment]
> This issue doesn't appear refer to any actual problem, so I'm going to close. If this causes a real issue, then please explain what the problem is that this causes. Ideally in the form of a reproducibly failing test.
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

I don't understand why you closed the issues so quickly. To our understanding of your [document](https://grpc.github.io/grpc/core/md_doc_statuscodes.html), the `GRPC_STATUS_INVALID_ARGUMENT` is caused by invalid inputs from the client. I believe if this error occurs, there shall be illegal input from the clients. That is why I mentioned the error should be kept rather than converting to a `GRPC_STATUS_INTERNAL`. I am not sure gRPC programming guidelines allow internal error conversion, either.
