### ISSUE TITLE
grpc_cli: Multiple `--proto_path`

### ISSUE THREAD

**Issue by rajmondx** [grpc/grpc#23773]
protoc supports multiple `--proto_path` arguments to specify extra paths to search for .proto files in.

It would be nice if `grpc_cli` would support this.

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/issues/10273#issuecomment-608554503
Quoting @gnossen, "We've actually started encouraging people to use grpcurl. It's well-maintained, has published binaries, and has a pretty complete feature set."

(grpc_cli is not deprecated but it is not the object of active development at the present moment.)
