### ISSUE TITLE
go cloud-to-cloud interop test timeouts and failures

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#23785]
Looks like most of the go cloud-to-cloud interop tests are failing, some with timeouts and some with outright failures:

https://source.cloud.google.com/results/invocations/40c3c099-447a-4134-8e99-7047f145c08f/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

**Comment by menghanl** [comment]
This is a dup of #23750.
Potentially caused by https://github.com/grpc/grpc-go/pull/3786 
@easwars is taking a look
