### ISSUE TITLE
(c++) gRPC client in Windows Service fails due to an absl::strcat call (for release build only)

### ISSUE THREAD

**Issue by ashf** [grpc/grpc#23789]
### What version of gRPC and what language are you using?
VCPKG: grpc:x86-windows 1.29.1 (c++)

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC v142

### What did you do?
I have been implementing a simple Windows Service (https://www.codeproject.com/Articles/499465/Simple-Windows-Service-in-Cplusplus). I put a gRPC client inside the Event method that is making a hello to a server I have setup. When I run the event method directly (not as a windows service) the hello message goes through to the server perfectly fine (in debug/release). However, when I run the Event method as part of the ServiceWorkerThread the hello message fails in release (fine in debug). I've narrowed this down to the child_policy_handler.cc absl::StrCat call:
![image](https://user-images.githubusercontent.com/6597733/89909774-6f402c80-dbbd-11ea-913d-5ac75579015b.png)
when it works correctly it resolves in client_channel.cc AddTraceEvent as such:
![image](https://user-images.githubusercontent.com/6597733/89909989-aca4ba00-dbbd-11ea-9bac-27c3156a1654.png)
when it doesn't work correctly it resolves in client_channel.cc AddTraceEvent as such:
![image](https://user-images.githubusercontent.com/6597733/89910300-09a07000-dbbe-11ea-9141-64e9c29b2c0b.png)

### What did you expect to see?
I expected the gRPC hello message to function correctly and not have an issue resolving an absl call while in a windows service owned thread.

### What did you see instead?
An incorrect absl resolution resulting in an incorrect message size that created a heapinit error further down the call stack.

**Comment by markdroth** [comment]
Can you run the client with the following environment variables set and share the log?

GRPC_VERBOSITY=DEBUG
GRPC_TRACE=client_channel_routing

**Comment by markdroth** [comment]
Also, please share your code.  We'll need some way to reproduce this problem.

**Comment by JScon01** [comment]
Mark,
I just Emailed you asking for you to stop sending me these Emails.

Jeffrey H. Conz

**Comment by ashf** [comment]
(Un)fortunately the issued magically resolved itself. So unclear why this occurred and why its stopped being an issue. I'll re-open if I come across it again.
