### ISSUE TITLE
PHP: AbstractCall fails with 32bit timeout value in options

### ISSUE THREAD

**Issue by PierrickVoulet** [grpc/grpc#23790]
Initially [reported](https://github.com/googleads/google-ads-php/issues/393) by @adrianlaraperez88 

### What version of gRPC and what language are you using?
PHP
1.31.0

### What operating system (Linux, Windows,...) and version?
32bit
Windows local W10, server W server 2012

### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP extension installed and configured

### What did you do?
Tried to send a call.

### What did you expect to see?
Successful call.

### What did you see instead?

[logs](https://user-images.githubusercontent.com/19626181/89820414-fa1c1b00-db1a-11ea-9389-6cdf591ee0c7.png)

### Anything else we should know about your project / environment?
@adrianlaraperez88 [experiment](https://github.com/googleads/google-ads-php/issues/393#issuecomment-671968907) should help to investigate.

**Comment by stanley-cheung** [comment]
Seems similar to #18916, which we don't really have a solution for now.
