### ISSUE TITLE
grpcio Python module fails to build on IBM/z (s390x) machine

### ISSUE THREAD

**Issue by jvesely** [grpc/grpc#23797]
### What version of gRPC and what language are you using?
Python grpcio-1.31

### What operating system (Linux, Windows,...) and version?
Ubuntu Linux 18.04.03

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.6/3.7/3.8 the package is built using gcc 7.4.0

### What did you do?

pip install grpcio

### What did you expect to see?

package installs 

### What did you see instead?

package fails to build (starts from [0]):
The top errors are (the rest is mostly undefined things which look like consequence fo these two):
```
  cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
  In file included from third_party/boringssl-with-bazel/src/include/openssl/asn1.h:61:0,
                   from third_party/boringssl-with-bazel/src/include/openssl/x509.h:66,
                   from ./src/core/tsi/ssl_transport_security.h:29,
                   from ./src/core/lib/security/security_connector/security_connector.h:33,
                   from ./src/core/lib/security/credentials/credentials.h:37,
                   from src/core/lib/http/httpcli_security_connector.cc:37:
  third_party/boringssl-with-bazel/src/include/openssl/base.h:122:2: error: #error "Unknown target CPU"
   #error "Unknown target CPU"
    ^~~~~
  In file included from third_party/boringssl-with-bazel/src/include/openssl/asn1.h:68:0,
                   from third_party/boringssl-with-bazel/src/include/openssl/x509.h:66,
                   from ./src/core/tsi/ssl_transport_security.h:29,
                   from ./src/core/lib/security/security_connector/security_connector.h:33,
                   from ./src/core/lib/security/credentials/credentials.h:37,
                   from src/core/lib/http/httpcli_security_connector.cc:37:
  third_party/boringssl-with-bazel/src/include/openssl/bn.h:165:2: error: #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
   #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
    ^~~~~
```
[0] https://travis-ci.com/github/jvesely/PsyNeuLink/jobs/370356257#L1059

### Anything else we should know about your project / environment?

you can add Travis CI env to test this regularly

**Comment by gnossen** [comment]
@nicolasnoble can provide more detail, but we do not support the IBM Z platform. We're happy to accept patches that expand support, but since we don't have access to the hardware, we can't run continuous integration on it and therefore can't claim any level of support for it.

**Comment by jvesely** [comment]
> @nicolasnoble can provide more detail, but we do not support the IBM Z platform. We're happy to accept patches that expand support, but since we don't have access to the hardware, we can't run continuous integration on it and therefore can't claim any level of support for it.

This doesn't make sense. Travis CI is free and includes IBM/Z platform, so you can run CI (it's in the name -- Travis *CI*)
Reading more than just the headline would reveal that.

I'd understand if there are other reasons to not support a niche platform, but "can't do CI" is both cheap and not true.

**Comment by nicolasnoble** [comment]
> This doesn't make sense. Travis CI is free and includes IBM/Z platform, so you can run CI (it's in the name -- Travis _CI_)

The major issue with Travis is that its free tier is absolutely not scalable for the truly enormous amount of testing we are doing for gRPC (I can't share numbers, but the amount of CPU we're burning on Google Compute Engine for gRPC testing is absolutely mind boggling), and their paid-for tier requires write access to the repository, which our security team won't let us have.

**Comment by jvesely** [comment]
Since the FOSS offerring was migrated to travis-ci.com, there shouldn't be a difference between the level of access for the free and paid offering.
The github app permissions are:
 Read access to code, metadata, and pull requests
 Read and write access to checks, commit statuses, deployments, and repository hooks

Unless there's a major difference in the app used for trial/academic plan vs. paid plans (which is imo unlikely).

thanks for explaining the issue.

**Comment by nicolasnoble** [comment]
![image](https://user-images.githubusercontent.com/7281574/90273049-300b1900-de13-11ea-9a94-b0e00be8b720.png)
¯\_(ツ)_/¯

**Comment by jvesely** [comment]
> ![image](https://user-images.githubusercontent.com/7281574/90273049-300b1900-de13-11ea-9a94-b0e00be8b720.png)
> ¯\_(ツ)_/¯

This looks like a question for travis ci support.

**Comment by xturtle** [comment]
Hi, here is some workaround under RHEL8 on s390x:

# yum install openssl openssl-devel
# GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 pip3 install grpcio

the main concept is using system OpenSSL lib (s390x workable) instead of the boringssl included in grpcio package.

enjoy it.
