### ISSUE TITLE
`gcloud docker` is deprecated and will stop working

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#23808]
Creating GCR interop_matrix images uses `gcloud docker`. It uses it [in the readme](https://github.com/grpc/grpc/blob/1b025b60e45972d8cb844839c03c314fbe9036a1/tools/interop_matrix/README.md#step-by-step-instructions-for-adding-a-gcr-image-for-a-new-release-for-compatibility-test) and also [create_matrix_images.py](https://github.com/grpc/grpc/blob/c4dd07aa7527f0904532d459321ea5b6c301d103/tools/interop_matrix/create_matrix_images.py#L355). When using `gcloud docker` it produces the warning:

```
WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03.

As an alternative, use `gcloud auth configure-docker` to configure `docker` to
use `gcloud` as a credential helper, then use `docker` as you would for non-GCR
registries, e.g. `docker pull gcr.io/project-id/my-image`. Add
`--verbosity=error` to silence this warning: `gcloud docker
--verbosity=error -- pull gcr.io/project-id/my-image`.

See: https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker
```

There may be other references; I didn't dig very hard.

**Comment by yashykt** [comment]
closing in favor of internal b/301123131
