### ISSUE TITLE
I'm trying to connect to grpc server with negotiation type TLS

### ISSUE THREAD

**Issue by ravichiripurapu** [grpc/grpc#23803]
I'm looking for a similar kind of functionality in grpc python but I could not find it. Is it available in Python grpc. 

Here is similar code in Java
NettyChannelBuilder.forAddress(endpoint.getHost(), endpoint.getPort())
        .negotiationType(NegotiationType.TLS)
        .sslContext(GrpcSslContexts.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE)
                .keyManager(new File(certPath), new File(keyPath))
                .build())
        .intercept(metadataInterceptor());

// ssl context with Negotiation Type TLS
NettyChannelBuilder.forAddress(endpoint.getHost(), endpoint.getPort())
        .negotiationType(NegotiationType.TLS)
        .sslContext(GrpcSslContexts.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build())
        .intercept(metadataInterceptor());

**Comment by apolcyn** [comment]
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

That said, I believe this is covered in these docs: https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls-4
