### ISSUE TITLE
Objective-C in framework user gRPC for pod

### ISSUE THREAD

**Issue by Nexus-GT-One** [grpc/grpc#23816]
I want to Quote gRPC from pod，but xcode show the error 
/Pods/Protobuf/objectivec/GPBUtilities_PackagePrivate.h:85:3: Include the header <string.h> or explicitly provide a declaration for 'memcpy'

but I set #include <string.h> 

it dosn't work

**Comment by yulin-liang** [comment]
Could you share your podspec file?

**Comment by Nexus-GT-One** [comment]
> Could you share your podspec file?


Pod::Spec.new do |s|
  s.name     = "gRPCDemo"#名称
  s.version  = "0.0.1"#版本号
  s.license  = "Apache License, Version 2.0"#开源协议
  s.authors  = { 'gRPC contributors' => 'grpc-io@googlegroups.com' }#作者信息
  s.homepage = "https://grpc.io/"#主页,这里要填写可以访问到的地址，不然验证不通过
  s.summary = "gRPCDemo Project"#简短介绍，下面是详细介绍
  s.source = { :git => 'https://github.com/grpc/grpc.git' } #项目地址，这里不支持ssh的地址，验证不通过，只支持HTTP和HTTPS，最好使用HTTPS

  s.ios.deployment_target = "7.1"
  s.osx.deployment_target = "10.9"

  #设置：三方依赖库
  #Protobuf                  Protobuf，序列化反序列化框架
  #gRPC-Core                 C 语言 gRPC 实现
  #gRPC                      ObjC gRPC wrapper
  #gRPC-ProtoRPC             ObjC gRPC Serivce 定义
  #gRPC-RxLibrary            Reactive 拓展 (大雾，好贴心)
  #ProtoCompiler             Protobuf 编译器
  #ProtoCompiler-gRPCPlugin  gRPC protobuf 编译器插件
  
  s.dependency "!ProtoCompiler", "~> 3.11.0"
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.28.0"
  s.dependency "Protobuf", "~> 3.11.0"
  s.dependency "gRPC", "~> 1.28.0"
  s.dependency "gRPC-Core", "~> 1.28.0"
  s.dependency "gRPC-ProtoRPC", "~> 1.28.0"
  s.dependency "gRPC-RxLibrary", "~> 1.28.0"


#  # Path where Cocoapods downloads protoc and the gRPC plugin.（插件的路径）
#  pods_root = 'Pods'
#  protoc_dir = "#{pods_root}/!ProtoCompiler"
#  protoc = "#{protoc_dir}/protoc"
#  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

#  #生成的pbobjc 与 pbrpc的路径
#  dir = "#{pods_root}/#{s.name}"

#  #新建一个Messages的文件目录，放置OC的pb运行文件
#  s.subspec "Messages" do |ms|
#    ms.source_files = "#{dir}/*.pbobjc.{h,m}", "#{dir}/**/*.pbobjc.{h,m}"
#    ms.header_mappings_dir = dir
#    ms.requires_arc = false
#    # The generated files depend on the protobuf runtime.
#    ms.dependency "Protobuf"#三方依赖库
#  end
#
#  #新建一个Services的文件目录，生成服务器的API文件（pbrpc 则是接口 API）
#  s.subspec "Services" do |ss|
#    ss.source_files = "#{dir}/*.pbrpc.{h,m}", "#{dir}/**/*.pbrpc.{h,m}"
#    ss.header_mappings_dir = dir
#    ss.requires_arc = true
#    # The generated files depend on the gRPC runtime, and on the files generated by protoc.
#    ss.dependency "gRPC-ProtoRPC" #三方依赖库
#    ss.dependency "#{s.name}/Messages" #三方依赖库
#  end

  s.pod_target_xcconfig = {
    # This is needed by all pods that depend on Protobuf:
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    # This is needed by all pods that depend on gRPC-RxLibrary:
    'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  }
  
end

**Comment by Nexus-GT-One** [comment]
> Could you share your podspec file?

Pod::Spec.new do |s|
  s.name     = "gRPCDemo"#名称
  s.version  = "0.0.1"#版本号
  s.license  = "Apache License, Version 2.0"#开源协议
  s.authors  = { 'gRPC contributors' => 'grpc-io@googlegroups.com' }#作者信息
  s.homepage = "https://grpc.io/"#主页,这里要填写可以访问到的地址，不然验证不通过
  s.summary = "gRPCDemo Project"#简短介绍，下面是详细介绍
  s.source = { :git => 'https://github.com/grpc/grpc.git' } #项目地址，这里不支持ssh的地址，验证不通过，只支持HTTP和HTTPS，最好使用HTTPS

  s.ios.deployment_target = "7.1"
  s.osx.deployment_target = "10.9"

  #设置：三方依赖库
  #Protobuf                  Protobuf，序列化反序列化框架
  #gRPC-Core                 C 语言 gRPC 实现
  #gRPC                      ObjC gRPC wrapper
  #gRPC-ProtoRPC             ObjC gRPC Serivce 定义
  #gRPC-RxLibrary            Reactive 拓展 (大雾，好贴心)
  #ProtoCompiler             Protobuf 编译器
  #ProtoCompiler-gRPCPlugin  gRPC protobuf 编译器插件
  
  s.dependency "!ProtoCompiler", "~> 3.11.0"
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.28.0"
  s.dependency "Protobuf", "~> 3.11.0"
  s.dependency "gRPC", "~> 1.28.0"
  s.dependency "gRPC-Core", "~> 1.28.0"
  s.dependency "gRPC-ProtoRPC", "~> 1.28.0"
  s.dependency "gRPC-RxLibrary", "~> 1.28.0"


#  # Path where Cocoapods downloads protoc and the gRPC plugin.（插件的路径）
#  pods_root = 'Pods'
#  protoc_dir = "#{pods_root}/!ProtoCompiler"
#  protoc = "#{protoc_dir}/protoc"
#  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

#  #生成的pbobjc 与 pbrpc的路径
#  dir = "#{pods_root}/#{s.name}"

#  #新建一个Messages的文件目录，放置OC的pb运行文件
#  s.subspec "Messages" do |ms|
#    ms.source_files = "#{dir}/*.pbobjc.{h,m}", "#{dir}/**/*.pbobjc.{h,m}"
#    ms.header_mappings_dir = dir
#    ms.requires_arc = false
#    # The generated files depend on the protobuf runtime.
#    ms.dependency "Protobuf"#三方依赖库
#  end
#
#  #新建一个Services的文件目录，生成服务器的API文件（pbrpc 则是接口 API）
#  s.subspec "Services" do |ss|
#    ss.source_files = "#{dir}/*.pbrpc.{h,m}", "#{dir}/**/*.pbrpc.{h,m}"
#    ss.header_mappings_dir = dir
#    ss.requires_arc = true
#    # The generated files depend on the gRPC runtime, and on the files generated by protoc.
#    ss.dependency "gRPC-ProtoRPC" #三方依赖库
#    ss.dependency "#{s.name}/Messages" #三方依赖库
#  end

  s.pod_target_xcconfig = {
    # This is needed by all pods that depend on Protobuf:
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    # This is needed by all pods that depend on gRPC-RxLibrary:
    'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  }
  
end

**Comment by yulin-liang** [comment]
Can you try to follow this [instruction](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/src/objective-c/README.md) to generate your podspec file?
