### ISSUE TITLE
Flakes surfacing only when running tests with console output (ie, through make test)

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#2381]
For instance, running `bins/opt/chttp2_socket_pair_with_grpc_trace_invoke_large_request_test` manually results in:

```
...
I0710 14:08:23.040276756    4365 server.c:616]               OP[server:0x1484cc0]: RECV
I0710 14:08:23.040282727    4365 http_server_filter.c:211]   OP[http-server:0x1484cd8]: RECV
I0710 14:08:23.040287775    4365 connected_channel.c:69]     OP[connected:0x1484cf0]: RECV
D0710 14:08:23.040295683    4365 tcp_posix.c:542]            WRITE 0x1466390: 00 00 04 08 00 00 00 00 01 00 00 ff fc '.............'
I0710 14:08:23.040310413    4365 completion_queue.c:221]     RETURN_EVENT[0x1465ee0]: QUEUE_TIMEOUT
E0710 14:08:23.040317983    4365 cq_verifier.c:202]          no event received, but expected:
0x66 GRPC_OP_COMPLETE result=1

Aborted (core dumped)
```

whereas running `tools/run_tests/run_tests.py -l c -r chttp2_socket_pair_with_grpc_trace_invoke_large_request_test` success.

Likewise, if we prevent console output, for instance, through `bins/opt/chttp2_socket_pair_with_grpc_trace_invoke_large_request_test 2>&1 | tail`, everything works as well. 

It seems the slowdown introduced by console output makes the flake surface.

**Comment by vjpai** [comment]
If it's a matter of slowdown, have you tried running the tests with the antagonists option?

**Comment by dgquintas** [comment]
Yes, and it doesn't make it happen. Only the console output seems to do the trick.

**Comment by nicolasnoble** [comment]
Actually, isn't that just a regular timeout ? Like, the app is dumping so much stuff on its console that it just eventually timeouts waiting on events ?
