### ISSUE TITLE
grpc csharp dealing with multi connections

### ISSUE THREAD

**Issue by lsylusiyao** [grpc/grpc#23829]
### What version of gRPC and what language are you using?
grpc 2.13.0, C#

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet core 3.1 desktop

### What did you do?
I used grpc to create a wrapper for a class ( Let's call it `MyEnv' ), which basically looks like this.

```csharp
public class BridgeWrapper : GEnv.GEnvBase
{
    private MyEnv myenv;

    public override Task<Empty> CreateClass(Empty request, ServerCallContext context)
    {
        myenv = new MyEnv();
        Console.WriteLine($"Build Once! hash is {myenv.GetHashCode()}");
        return Task.FromResult(new Empty());
    }

    public override Task<Empty> DoSth(Empty request, ServerCallContext context)
    {
        myenv.DoSth();
        Console.WriteLine($"hash is {myenv.GetHashCode()}");
        return Task.FromResult(new Empty());
    }

}


```

The client I used is Python and it created 4 different threads to connect the csharp server. The `DoSth` would be run in a circle for multi times.

### What did you expect to see?

The four `Build Once` gave four different hash, and in `DoSth`, hash should be different in different thread. In console I should see 4 different hash. 

### What did you see instead?

```
Build Once!, hash is 7044526
hash is 7044526
Build Once!, hash is 45653674
hash is 45653674
Build Once!, hash is 56140151
hash is 56140151
Build Once!, hash is 39086322
hash is 39086322
Build Once!, hash is 36181605
hash is 36181605
hash is 36181605
hash is 36181605
hash is 36181605
hash is 36181605
hash is 36181605
hash is 36181605
hash is 36181605
...... ( till end they're same )
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
Sorry but I don't understand what erroneous gRPC behavior you're trying to describe. AFAICT, you have a server side stub that prints hash of an object and the logs you provided don't really show anything that would indicate a gRPC problem.

Also I don't see why you're claiming that  "hash should be different in different thread".

**Comment by lsylusiyao** [comment]
Well, several days later I've found out that I misunderstood the meaning of gRPC. gRPC helps call a `function` rather than an `object` remotely, which means I can't create or delete an object directly. Previously I thought if I called to create objects in different thread, , the objects should be different even if later I called the objects' function. Sorry to trouble here.
