### ISSUE TITLE
Port it to termux. Please

### ISSUE THREAD

**Issue by tathastu871** [grpc/grpc#23853]
### Is your feature request related to a problem? Please describe.

Error log
```
http://sprunge.us/PJOVfj
```

### Additional context
Add any other context about the feature request here.

**Comment by markdroth** [comment]
This issue does not include a lot of information, but from the error log, it looks like this is trying to use grpc-python.

**Comment by gnossen** [comment]
I don't think that supporting Python on Termux is a high priority, given that we've never heard this request before. In principle though, I don't see why this shouldn't work. If you can use a prebuilt wheel, that would be the easiest route; getting a full build toolchain set up on Termux (which is what you appear to be doing here) is likely to be a pain.

The error here looks odd.

**Comment by gnossen** [comment]
```
2020-08-15T22:07:18,870         raise ImportError("This platform lacks a functioning sem_open" +
2020-08-15T22:07:18,871     ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

Interesting. It looks like the `multiprocessing` module is non-functional on Termux. We don't *need* it to build, but it does speed things up pretty substantially. Given that we apparently can't always expect this import to work, we might want to wrap it in a `try except ImportError` block with a fallback to a single process build.
