### ISSUE TITLE
Default value for channel option 'grpc.max_concurrent_streams'

### ISSUE THREAD

**Issue by YanlongLi** [grpc/grpc#23861]
I tried to search information about the default value for **grpc.max_concurrent_streams** and when we should set the value explicitly in server side and client side, but I don't see too much documents about it.

Also, I also want to check the default value for  **grpc.min_reconnect_backoff_ms**, **max_reconnect_backoff_ms** and **grpc.max_reconnect_backoff_ms**.

**Comment by veblush** [comment]
Not sure about the which library but in general, default values for those would be (those are found in .cc source files)

- `MAX_CONCURRENT_STREAMS`: 4294967295u
- `GRPC_SUBCHANNEL_RECONNECT_MIN_TIMEOUT_SECONDS`: 20
- `GRPC_SUBCHANNEL_RECONNECT_MAX_BACKOFF_SECONDS`: 120

**Comment by YanlongLi** [comment]
Thanks @veblush , we are using the C# library and the information you provided is very helpful. These values are buried in different source code files and have different names with the exposed arg name, which makes it hard to find. Maybe it's better to specify the default values in [group__grpc__arg__keys.html](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#gad7d9d143858d8f5e138cf704b0082973) and user can easily decide whether to override it.

**Comment by veblush** [comment]
I'm glad that this helped you and thanks for suggestion about the better documentation. I will follow-up that via #24073.
