### ISSUE TITLE
Remove Asserts somewhere in Debug builds

### ISSUE THREAD

**Issue by nikitamikhaylov** [grpc/grpc#23914]
### Is your feature request related to a problem? Please describe.
I use `grpc` as a submodule in my project. When I compile it with debug options, it fails due to asserts. I looked through the stacktrace and noticed, that you have 'todos' to remove asserts. For example, here: https://github.com/grpc/grpc/blob/b3808b73dad065bb6d4cd20496077d2462bcc1c5/include/grpcpp/impl/codegen/async_stream_impl.h#L561 
So, I am confused, because I don't know is there a bug in my code or not..

### Describe the solution you'd like
Remove asserts :) You already have 'todo' in the code.

### Describe alternatives you've considered
Maybe I do something wrong, and in normal situations it won't be an assert. Please, tell me about it.

**Comment by markdroth** [comment]
I think that without seeing a stack trace, this isn't really actionable, so I'm going to close it.  Please let us know when you can provide a stack trace, and we can reopen this (or you can just file a separate issue).
