### ISSUE TITLE
build failed with cmake using -DgRPC_CARES_PROVIDER=package

### ISSUE THREAD

**Issue by WANGKE-InCodeWeTrust** [grpc/grpc#23920]
### What version of gRPC and what language are you using?
gRPC version: v1.31.0
language: c++

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.5.0

### What did you do?

1. Run cmake
```
cmake ../.. -DgRPC_INSTALL=ON                \
	      -DCMAKE_INSTALL_PREFIX=$HOME/tools/runtime \
              -DCMAKE_BUILD_TYPE=Release       \
              -DgRPC_ABSL_PROVIDER=module      \
              -DgRPC_CARES_PROVIDER=package    \
              -DgRPC_PROTOBUF_PROVIDER=package \
              -DgRPC_SSL_PROVIDER=package      \
              -DgRPC_ZLIB_PROVIDER=package
```
and the result is :
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found c-ares: /home/parallels/tools/runtime/lib/cmake/c-ares/c-ares-config.cmake (found suitable version "1.16.0", minimum required is "1.13.0")
-- Found Protobuf: /home/parallels/tools/runtime/lib/libprotobuf.so;-lpthread (found version "3.13.0")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/parallels/tools/src/grpc/cmake/build
```

2. make, then encountered the error:

> /home/parallels/tools/src/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:23:10: fatal error: ares.h: No such file or directory
>  #include <ares.h>
>           ^~~~~~~~
> compilation terminated.
> 

### What did you expect to see?

compilation success

### What did you see instead?
> /home/parallels/tools/src/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:23:10: fatal error: ares.h: No such file or directory
>  #include <ares.h>
>           ^~~~~~~~
> compilation terminated.
> 

### Anything else we should know about your project / environment?
c-ares was built from source using cmake and it is installed in $HOME/tools/runtime.
Specifically, the header files are in  $HOME/tools/runtime/include and the files are "ares_build.h  ares_dns.h  ares.h  ares_rules.h  ares_version.h"; 

Cmake successfully found c-ares
 (as seen in the cmake result : 
`-- Found c-ares: /home/parallels/tools/runtime/lib/cmake/c-ares/c-ares-config.cmake (found suitable version "1.16.0", minimum required is "1.13.0"`)
 ),

but failed to add c-ares header file directory into the building process, i.e. failed to add `-I/home/parallels/tools/runtime/include` ( 
as seen in the verbose gcc command :
 ```
/usr/bin/c++  -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I/home/parallels/tools/src/grpc/third_party/re2 -I/home/parallels/tools/src/grpc/include -I/home/parallels/tools/src/grpc -I/home/parallels/tools/src/grpc/third_party/address_sorting/include -I/home/parallels/tools/src/grpc/cmake/build/third_party/re2 -I/home/parallels/tools/src/grpc/src/core/ext/upb-generated -I/home/parallels/tools/src/grpc/third_party/upb -I/home/parallels/tools/src/grpc/third_party/abseil-cpp  -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/grpc_unsecure.dir/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc.o -c /home/parallels/tools/src/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc
/home/parallels/tools/src/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:23:10: fatal error: ares.h: No such file or directory
 #include <ares.h>
          ^~~~~~~~
compilation terminated.
```
)

**Comment by veblush** [comment]
When I retried this by changing `cmake ..` to `cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/tools/runtime` for c-ares, it still worked. Maybe this could be cmake issue. Can you reproduce this with docker so that I can take a look at?

Also from cmake, I confirmed it actually used the installed one.

```
-- Found c-ares: /root/tools/runtime/lib/cmake/c-ares/c-ares-config.cmake (found suitable version "1.16.1", minimum required is "1.13.0") 
```
