### ISSUE TITLE
How to build gRPC++ with OpenSSL instead of BoringSSL

### ISSUE THREAD

**Issue by kotori2** [grpc/grpc#23931]
My project uses MySQL connector, which use OpenSSL as its dependency.
I've integrate gRPC with my project using `FetchContent` described [here](https://github.com/grpc/grpc/tree/master/src/cpp), and I also have OpenSSL installed in my system. What I tried was:

- Installing OpenSSL with Homebrew, then link manually to system path on macOS. 
- Installing OpenSSL with vcpkg on Windows.

They both doesn't work.

Also there are some issues discussing about similar problem in #23113.

**Comment by jtattermusch** [comment]
@kotori2 yes that is the correct approach - use cmake and `set(gRPC_SSL_PROVIDER package)` or `-DgRPC_SSL_PROVIDER=package` on the commandline.
https://github.com/grpc/grpc/blob/f57a0619bc5697ea98c2d5b2c983c7024f43a5db/cmake/ssl.cmake#L66
