### ISSUE TITLE
Python tests by Bazel failure due to missing "_protos"

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#23946]
After the dynamic stubs is merged, the following error appears on my local Bazel builds. It might be related to my local version of `grpcio-tools`, but it still fails after `bazel clean --expunge`. CC @gnossen for any advices?

```
ImportError: cannot import name '_protos' from 'grpc_tools.protoc' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/grpc_tools/protoc.py)
```

Also, recently, when Core folks trying to build Python with Bazel, they always end up with an error saying: the binary is built for python 3.7 but runtime has 3.8. It is fixable with `PYTHON3_PATH`, but there is a possibility to make it automatic.

**Comment by yashykt** [comment]
I believe I was trying to run interop tests for python. I think if it is simply a version mismatch, there isn't much to be done here other than simply setting the path and using the right version.
