### ISSUE TITLE
Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="Cancelled"……

### ISSUE THREAD

**Issue by JACKCHEN96** [grpc/grpc#23955]
Hi, I'm getting this error from client side in 
```
CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request) :
Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="Cancelled", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1598237258.589000000","description":"Error received from peer ipv4:127.0.0.1:50051","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\surface\call.cc","file_line":1055,"grpc_message":"Cancelled","grpc_status":1}")”
```

#### Description

I'm just testing the connection of client and server on MS unit test and get the RpcException. The simple Greeter service works well on my demo (which is a console program), but get error in unit test. So the problem description can be simplified as following:

Unit test Client & Unit test server CANCELLED;
Demo Client & Demo Server  YES;
Unit test Client & Demo Server YES;
Demo Client & Unit test Server CANCELLED.

#### Environment details

  - OS: Windows
  - .NET version: 4.6.2
  - Package name and version: .NET framework 4.7.2 & Grpc.Core 2.24.0 & protobuf-net 2.3.7.0

#### Steps to reproduce

  1. Simple Greeter service on unit test
  2. Using "protobuf-net" for serialization/deserialization

Thanks!

**Comment by jtattermusch** [comment]
A few notes:
- just FYI, we don't officially support "protobuf-net" in gRPC C# (this might or might not be related to your issue).
- from your description it's impossible to tell what's wrong (because you provide very little details about your setup and no reproduction), but my hunch is that something is just setup incorrectly in your unit tests.

Feel free to use https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md to get extra debugging info or provide a minimal reproduction, but I suspect the behavior you're seeing is problem in your code (and/or your client/server configuration) rather than a gRPC bug.

**Comment by Faebs23** [comment]
Hi,
have you fixed this problem? I have the same issue. When i run my server as a console application everything works fine. But when I host my server as a windows service I got the follwing exception when I send a client request.

```
Status(StatusCode="Cancelled", Detail="Cancelled", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1629268018.289000000","description":"Error received from peer ipv4:10.0.0.12:19587","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":"Cancelled","grpc_status":1}")
210818 082658 <Error> RpcException: Status(StatusCode="Cancelled", Detail="Cancelled", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1629268018.289000000","description":"Error received from peer ipv4:10.0.0.12:19587","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":"Cancelled","grpc_status":1}")
    StackTrace: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)

```

**Comment by AustinEscobedo** [comment]
Running into the same issue as well. Any resolution/troubleshooting information?
Status(StatusCode="Cancelled", Detail="Cancelled", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1630433128.330000000","description":"Error received from peer ipv6:[::1]:8061","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":"Cancelled","grpc_status":1}")

**Comment by Faebs23** [comment]
Found my problem. Wrong version of System.Buffers DLL. I used an assembly binding in the app.config which bound the wrong version.

**Comment by AustinEscobedo** [comment]
Thanks for the info, can confirm this fixed our issue as well.

**Comment by muler415** [comment]
I have same problem. and was this issue resolved? 
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="CANCELLED", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1639285302.562000000","description":"Error received from peer ipv4:192.168.61.10:9007","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1064,"grpc_message":"CANCELLED","grpc_status":1}")
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   在 Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   在 Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   在 Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   在 Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   在 AtpGrpcLibrary.AtpGrpcService.AtpGrpcServiceClient.GetProjectInfos(Empty request, CallOptions options)

**Comment by muler415** [comment]
I figured out the root cause is - I did not copy System.Numerics.Vectors.dll to execution folder. That led to failure status. I am wondering why there is no exception thrown out.  if there is exception in detail, that would be great!

**Comment by lugatecan** [comment]
Changing to an older version of the System.Buffers DLL for me solved the issue. 
Using a .NET Framework 4.8 project. The new version from netstandard2.0 did not work.  Not sure why this would cause the issue. 
For me using the wrong System.Buffers DLL I got a StatusCode="Unknown" instead of "Cancelled"
