### ISSUE TITLE
grpc-gateway equivalent in the grpc python package

### ISSUE THREAD

**Issue by Talador12** [grpc/grpc#23979]
## Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Add support for [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) as an option available in the [grpc python package](https://pypi.org/project/grpc/)

I have found a [python example](https://gist.github.com/doubleyou/41f0828e4b9b50a38f7db815feed0a6c) that claims to integrate this kind of gateway via python. Is this the accepted method?

### Describe alternatives you've considered
For non HTTP2 traffic, we are considering not using gRPC at all. We would prefer to use gRPC for both HTTP2 and HTTP1 via the grpc-gateway

### Additional context
Crossposted with the [grpc-gateway-repository](https://github.com/grpc-ecosystem/grpc-gateway/issues/1613)

**Comment by Talador12** [comment]
Hey @ karthikravis

Thank you for picking this up. Any questions? How could I help out?

**Comment by gnossen** [comment]
@Talador12 Can you please be a bit more specific? `grpc-gateway` is a separate binary/process from your server. It can be deployed alongside a server of any language, which (I assume) is what's happening in the gist you linked above. We have talked about in-library support for this sort of thing in the past. That way, you wouldn't have to orchestrate a separate gateway process. But that would be a pretty substantial effort.

Does that answer your question?

**Comment by Talador12** [comment]
```
We have talked about in-library support for this sort of thing in the past. That way, you wouldn't have to orchestrate a separate gateway process. But that would be a pretty substantial effort.
```

This is exactly what I am referring to. As gRPC has grown in popularity and usage, I think an option to run in-library support would be a huge win for many teams. Instead of sidecar, could this gateway be run alongside the gRPC server instance itself? As it would be a `substantial effort`, what is the right way to get this effort started? Even as a "nice to have" stretch goal, this would be a welcome feature

**Comment by gnossen** [comment]
The first step would be for the interested party to start a gRFC in https://github.com/grpc/proposal. There, you'd want to get relevant people from all of the languages to chime in on the requirements for the cross-language feature. Then, we'd need to get into per-language details. Finally, we'd need to ensure that support is added across the language matrix, which will entail at least three different implementations: Core (C++), Java, and Go.

**Comment by Talador12** [comment]
gRFC proposal - https://github.com/grpc/proposal/pull/208

grpc google group discussion - https://groups.google.com/g/grpc-io/c/rEfqlLL9Emw
