### ISSUE TITLE
build with cmake error

### ISSUE THREAD

**Issue by l30006821** [grpc/grpc#23970]
### What version of gRPC and what language are you using?
1.31.0

### What operating system (Linux, Windows,...) and version?
Linux
### What runtime / compiler are you using (e.g. python version or version of gcc)
Cmake 3.18

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

i try build grcp whith CMake on Linux,but running into some errors. log report /usr/bin/ld: libgrpc++_test_config.so.1.31.0:undefind reference to 'google::ParseCommandLineFlags(int*, char***, bool)'

i've already installed gflags and gflags-devel package and i try ldd libgrpc++_test_config.so.1.31.0 but there is no link to gflags...

i think the cmake/gflags.cmake has some error in line 28 because find_package target is gflags but the next line TARGET become gflags::gflags...

thereis my build command: cmake ../.. -DgRPC_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DgRPC_CARES_PROVIDER=package -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_GFLAGS_PROVIDER=package -DgRPC_BUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON

make

make install

### What did you expect to see?
build success

### What did you see instead?
an error occur

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by l30006821** [comment]
finally, i modify `gflags::gflags` to `gflags` and build success

**Comment by markdroth** [comment]
Sounds like this is resolved, then.
