### ISSUE TITLE
Memory leak in server when using  string tensor?

### ISSUE THREAD

**Issue by FancyXun** [grpc/grpc#23986]
Ubutun 18, python 3.6, gRPC 1.24.3
Server:
```
import time
import grpc
from concurrent import futures
import tensorflow as tf
from google.protobuf import any_pb2
import numpy as np
import random
import compute_pb2, compute_pb2_grpc  


class ComputeServicer(compute_pb2_grpc.ComputeServicer):
    def SayHello(self, request, ctx):
        max_len = str(len(request.helloworld))
        return compute_pb2.HelloReply(result=max_len)

    def Compute(self, request, ctx):
        n = 100
        # This 2 lines makes memory leak
        for i in range(n):
            value = tf.constant([str(random.randint(10000000,99999999)) * 16] * 5000000, dtype=tf.string)
        '''
        for i in range(n):
            value = tf.constant([i] * 100000000, dtype=tf.int64)
        ''' 
        value = tf.constant([1] * 50000000, dtype=tf.int64)
        tensor_proto = tf.make_tensor_proto(value)
        any_pb = any_pb2.Any()
        any_pb.Pack(tensor_proto)
        value_proto = compute_pb2.Value(tensor=any_pb)
        return compute_pb2.ComputeResponse(value=value_proto)


def main():
    options = [
        ('grpc.max_send_message_length', -1), ('grpc.max_receive_message_length', -1)
    ]
    server_kwargs = {}
    server_kwargs['options'] = options
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10), **server_kwargs)
    servicer = ComputeServicer()
    compute_pb2_grpc.add_ComputeServicer_to_server(servicer, server)
    server.add_insecure_port('127.0.0.1:19999')
    server.start()
    try:
        print("running...")
        time.sleep(1000)
    except KeyboardInterrupt:
        print("stopping...")
        server.stop(0)


if __name__ == '__main__':
    main()
```

client:
```
import grpc
import compute_pb2
import compute_pb2_grpc
import tensorflow as tf
import time

_HOST = '127.0.0.1'
_PORT = '19999'


def main():
    num = 0
    while num < 100:
        with grpc.insecure_channel("{0}:{1}".format(_HOST, _PORT),
                                   options=[('grpc.max_send_message_length', -1),
                                            ('grpc.max_receive_message_length', -1)]
                                   ) as channel:
            client = compute_pb2_grpc.ComputeStub(channel=channel)
            response = client.Compute(compute_pb2.HelloRequest(helloworld="123456"))
            value_proto = response.value
            tensor_proto = tf.make_tensor_proto(values=0)
            if not value_proto.tensor.Unpack(tensor_proto):
                raise ValueError('Unable to unpack the received tensor value.')

            tensor_value = tf.make_ndarray(tensor_proto)
            print(num)
            num+=1



if __name__ == '__main__':
    main()
```
proto:
```
syntax = "proto3"; 
import "google/protobuf/any.proto";


package compute;
service Compute {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
    rpc Compute(HelloRequest) returns (ComputeResponse) {}
}

message HelloRequest {
    string helloworld = 1;
}

message HelloReply {
    string result = 1;
}

message ComputeResponse {
  Value value = 1;
}

message Value {
  oneof value {
    google.protobuf.Any tensor = 1;
  }
}
```

Memory usage increases over time in server side. If I remove string tensor in server or replace it with int64, The server's memory usage is  stable over time.

**Comment by gnossen** [comment]
This sounds like a garbage collection issue. How many requests were you getting and how long were they taking to complete?

**Comment by FancyXun** [comment]
@gnossen I simulated 10 requests for grpc server, the whole time is about 9 minutes, the time of each result below

> request1 takes 48.327646017074585s
> request2 takes 46.64272689819336s
> request3 takes 47.69695973396301s
> request4 takes 46.57152080535889s
> request5 takes 47.96682834625244s
> request6 takes 46.77770256996155s
> request7 takes 46.8488392829895s
> request8 takes 47.416603565216064s
> request9 takes 47.36856150627136s
> request10 takes 46.41548943519592s

The memory in server was increasing from 258M to 9433 MB. I recorded memory every 2 seconds below

> 258.80078125 MB
> 601.546875 MB
> 2417.21875 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 2455.84765625 MB
> 3262.1328125 MB
> 2382.44921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 2455.921875 MB
> 3297.59375 MB
> 2456.06640625 MB
> 4103.2890625 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 4248.76171875 MB
> 5231.08984375 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4184.21875 MB
> 4854.4375 MB
> 4184.25 MB
> 5939.03125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 5976.9453125 MB
> 6303.39453125 MB
> 5912.40234375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 5977.109375 MB
> 6532.4375 MB
> 5977.25 MB
> 6827.91796875 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 7705.125 MB
> 8522.44921875 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 7640.58203125 MB
> 8213.6953125 MB
> 7640.59765625 MB
> 8312.7109375 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9433.296875 MB
> 9750.2109375 MB
> 9368.75 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9433.45703125 MB
> 9942.37890625 MB
> 10237.046875 MB
> 9433.59375 MB
> 9433.59375 MB

**Comment by FancyXun** [comment]
Can anyone help me fix this?
