### ISSUE TITLE
xdsResolver run() in a loop, consume a lot of CPU

### ISSUE THREAD

**Issue by zxpan** [grpc/grpc#23985]
### What version of gRPC and what language are you using?
go language, v1.31.0

### What operating system (Linux, Windows,...) and version?
MacOS version 10.14.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A

### What did you do?
I am running a simple XDS client.  GetMyAddress in the below is part of HTTP handler, the code snippet as in the following
 
```
import (
  "context"
  "flag"
  "fmt"
  "log"
  "net/http"
  "time"

  "github.com/gin-gonic/gin"
  _ "golang.org/x/net/context"
  "google.golang.org/grpc"
  _ "google.golang.org/grpc/xds"
)
var (
  conn *grpc.ClientConn
)

type Env struct {
  xds_address string
}

type ErrorResponse struct {
  Status string `json:status`
  Error  string `json.error`
}

func (env Env) GetMyAddress(c *gin.Context) {
  conn, err := grpc.Dial(env.xds_address, grpc.WithInsecure(),grpc.WithBlock())
  if err != nil {
    rsp := ErrorResponse{"failed", err.Error()}
    c.JSON(http.StatusInternalServerError, rsp)
    return
  }
  defer conn.Close()
  c.JSON(http.StatusOK, {})
}

func main() {
  address := flag.String("host", "xds:///testing", "load balancer URL")
  var port = flag.Int("port", 9080, "TCP/IP port for listening to")
  flag.Parse()
  env := Env{xds_address: *address}
  router := gin.Default()
  router.GET("/srs", env.GetMyAddress)
  router.Run(fmt.Sprintf(":%v", *port))
}
```

### What did you expect to see?
I don't expect the CPU usage too high

### What did you see instead?
I see one of go routine running in a loop, 

(dlv) grs
  Goroutine 1 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/netpoll.go:203 internal/poll.runtime_pollWait (0x103619e)
  Goroutine 2 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 3 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 4 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 18 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 19 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 20 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 21 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 22 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 34 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 36 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 37 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 38 - User: /usr/local/Cellar/go/1.14.7/libexec/src/runtime/proc.go:305 runtime.gopark (0x103db2b)
  Goroutine 45 - User: /Users/<username>go/pkg/mod/google.golang.org/grpc@v1.31.0/xds/internal/resolver/xds_resolver.go:178 google.golang.org/grpc/xds/internal/resolver.(*xdsResolver).run (0x1b46875) (thread 361476)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I am attempting to see how xDS  API can be used for lookaside load balancer, typically I am interested in  developing a plug in to do customized load balancer logic

**Comment by zxpan** [comment]
Should break. out the loop in case the connection is close, or **r.ctx** is cancelled. 
```
func (r *xdsResolver) run() {
  for {
    select {
    case <-r.ctx.Done():
    case update := <-r.updateCh:
      if update.err != nil {
```

**Comment by zxpan** [comment]
Any updates? or my observation is wrong

**Comment by markdroth** [comment]
It looks like this is about grpc-go.  Please file this issue in https://github.com/grpc/grpc-go instead of in this repo.

**Comment by zxpan** [comment]
Thanks for pointing this out.  Filed to grpc-go repo.
