### ISSUE TITLE
Documentation Issue: Parameter 'selected_port[out]' not found in the function declaration

### ISSUE THREAD

**Issue by gilrodar** [grpc/grpc#23997]
"Parameter 'selected_port[out]' not found in the function declaration"
"Did you mean 'selected_port'?"

<img width="486" alt="Captura de Pantalla 2020-08-26 a la(s) 15 17 05" src="https://user-images.githubusercontent.com/13817108/91352497-8e3ee100-e7af-11ea-926f-ce946f8b7aea.png">

<img width="273" alt="Captura de Pantalla 2020-08-26 a la(s) 15 19 51" src="https://user-images.githubusercontent.com/13817108/91352530-9860df80-e7af-11ea-8454-a059c758ea6f.png">

**Comment by markdroth** [comment]
This looks like a problem in one of our C++ headers.  See also firebase/firebase-ios-sdk#6340.

**Comment by veblush** [comment]
Oh this should be fixed with the PR above.
