### ISSUE TITLE
test and build infrastructure for arm64 support

### ISSUE THREAD

**Issue by vielmetti** [grpc/grpc#24002]
### Is your feature request related to a problem? Please describe.

Multiple projects on arm64 are blocked because of lack of arm64 support for `grpc`.

If "gRPC is a modern, open source, high-performance remote procedure call (RPC) framework that can run anywhere", then it should run anywhere including on arm64.

It has been pointed out several times that arm64 support is limited in part
because of lack of test and build infrastructure.

arm64 support is relevant to several sets of devices, including the following:

* forthcoming arm64 "Apple Silicon"
* Windows on Arm, primarily in laptop forms
* AWS "Graviton2" server platform
* Ampere eMag and Altra servers
* 64-bit operating systems for the Raspberry Pi (Raspberry Pi OS / Ubuntu 20.04)
* CI infrastructure from Travis CI and Drone Cloud

### Describe the solution you'd like

Address the question of test and build infrastructure - what is
needed, where could it be hosted, and what tooling someone
internal or external to the project would need to make progress on this.

Note that Bazel as of https://github.com/bazelbuild/bazel/issues/8833 includes
arm64 support, so that there's some tooling available.

### Describe alternatives you've considered

There isn't really a good alternative to working within the existing project;
the build infrastructure is sufficiently complex to make it unwise to fork
it.

### Additional context

Related issues:

* #23373 Wheel support for aarch64 
* #23336 gRPC multiple languges on ARM
* #22263 Support ARM64 in C# grpc.tools package
* #21283 ARM64v8 wheel [Python] - 
* #23310 grpc fails to compile on windows under arm64 architecture
* #14741 grpc-tools arm64 support [Node.JS]
* https://github.com/pulumi/pulumi/issues/5244 Pulumi on arm64
* https://github.com/EventStore/EventStore/issues/2380 Eventstore on arm64

**Comment by guthom** [comment]
Any news on this? it could be really helpfull for some of my projects if there would be a way to enable arm64 builds!

Best Guthom

**Comment by jtattermusch** [comment]
I'm not really sure what the answer should be here.

The gRPC team realizes that the importance of ARM64 is growing and we are actually making steps towards supporting it. As expressed before, the main challenge is setting up the test infrastructure and integrating it with the tests we currently have. gRPC is not a small project and its testing infrastructure is quite complicated and there are many kinds of tests in 10 languages and a ton of support scripts in bash and python. The volume of our testing is also quite high (we run hundreds of hours worth of tests on each pull request and also continuously). Our current CI plaform has currently no way of integrating with ARM64 servers. Altogether, figuring out the question of how to test on ARM in a way that's feasible, reliable maintainable and cost efficient way is not an easy task - it's not as simple as just grabbing an ARM server and starting to running tests on it, there's tens of smaller subproblems to solve (and many of them require in-depth knowledge of gRPC's testing infrastructure and the tests themselves). This is also the reason why a cannot give you a one paragraph summary of "what's needed" (there's a lot of things) and how you can make progress (which is also quite complicated once you go beyond the obvious "try to build and run on a ARM64 server and if you find a bug, come back with a PR that fixes it")

That said, ARM64 support is something we're actively investigating so over time you should be seeing more and more progress towards this goal.

Hope this makes sense and thanks for coming up with a list of the ARM related issues.

**Comment by Marcelverhoeven** [comment]
Dear Mr Tattermusch
Thank you for your quick replies.
Allow me to briefly present myself: I am the Precision Systems and Telematic Innovation manager within CNHi (https://www.cnhindustrial.com/en-us/Pages/homepage.aspx) 
I would like to speak with you about our global project and the issue of the missing support for ARM64 (see discussion here above).
I believe I have a good proposal to solve this issue while not jeopardizing the potential impact at your side.
I would greatly appreciate if you could contact me on marcel.verhoeven@cnhind.com

**Comment by jtattermusch** [comment]
Just to provide a quick update here: the gRPC team is actively working on providing official ARM64 linux support (including official packages in package managers and continuous tests in place). Please stay tuned.

**Comment by Hajime-Sugiuchi** [comment]
@jtattermusch  Dear Mr Tattermusch,
It's a great news for gRPC users.  We do appreciate tremendous effort to the gPRC team. Waiting for good news.

**Comment by vielmetti** [comment]
A blog post at https://grpc.io/blog/grpc-on-arm64/ has lots of updates!

**Comment by jtattermusch** [comment]
> A blog post at https://grpc.io/blog/grpc-on-arm64/ has lots of updates! Thanks @jtattermusch for all your work.
> 
> I note in that post that there's a gap in Ruby support. The Ruby team just spun up some systems for build/test on arm64 at @WorksOnArm - let me know if I can make any introductions.

Yes, we don't provide native ruby gems, this is tracked as https://github.com/grpc/grpc/issues/26391 and https://github.com/protocolbuffers/protobuf/issues/8682. The main blocker there is lack of support for aarch64 linux crosscompilation in rake-compiler-dock (which is what we use for building the native gems) - see https://github.com/rake-compiler/rake-compiler-dock/issues/47.

**Comment by jtattermusch** [comment]
Since linux arm64 support is now official (as announced in https://grpc.io/blog/grpc-on-arm64/), it makes sense to close this issue. Feel fee to open separate issues for arm64 on Mac and arm64 on Windows - but as mentioned in the blogpost we don't have a clear plan there yet.
