### ISSUE TITLE
Building wheel for grpcio (setup.py) . . . takes forever while installing firebase-admin on the Jetson Nano

### ISSUE THREAD

**Issue by gapro20022** [grpc/grpc#24026]
I am trying to install firebase-admin on the Jetson Nano which runs on Ubuntu 18.04 LTS. It returned a bunch of errors which didn't even fit an entire scroll of the terminal, but here's what it says after it returned the errors.

`  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
DEPRECATION: Could not build wheels for grpcio which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: grpcio
    Running setup.py install for grpcio ... -
`

I've run this many times and both 'Building wheel...' and 'Running setup.py...' return a bunch of errors.

I am using python 3.6.9. Pip and setuptools are up to date. I have tried so many methods but none were fruitful, please help me.

Thank you,
Henry

**Comment by gapro20022** [comment]
Update:
Running setup.py install for grpcio... returned this
`commands.CommandError:
    
    We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).
    
    Traceback (most recent call last):
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/unixccompiler.py", line 204, in link
        self.spawn(linker + ld_args)
      File "/tmp/pip-install-egyuu8jd/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run, **kwargs)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/spawn.py", line 88, in spawn
        "command %r failed with exit code %s" % (cmd, exitcode))
    distutils.errors.DistutilsExecError: command '/usr/bin/aarch64-linux-gnu-g++' failed with exit code 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-egyuu8jd/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/home/jetson/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
        target_lang=language)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/ccompiler.py", line 717, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/home/jetson/.local/lib/python3.6/site-packages/setuptools/_distutils/unixccompiler.py", line 206, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command '/usr/bin/aarch64-linux-gnu-g++' failed with exit code 1
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-egyuu8jd/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-egyuu8jd/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a7ww7n7o/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/grpcio Check the logs for full command output.`

**Comment by rajesh0therascal** [comment]
Hi @gapro20022, 

Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.

**Comment by charlielito** [comment]
> Hi @gapro20022,
> 
> Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.

I can confirm this, I was having trouble installing grpc in a Jetson Xavier AGX and this solved it

**Comment by gapro20022** [comment]
Thank you very much! I will close this now.

**Comment by cole-myers** [comment]
After downgrading to setuptools==49.6.0, I still have a very long wheel build and then successive failure when attempting grpcio install, anyone else still experiencing issues installing?

**Comment by samho93** [comment]
does anyone know if grpcio is working on macos Big Sur? i cant find a solution to install it on my pyenv virtualenv

**Comment by samho93** [comment]
P.S im on an intel based mac

**Comment by calebjohn24** [comment]
> P.S im on an intel based mac

Yep same here have been struggling

**Comment by gnat79** [comment]
Same problem on big sur. I've been battling with this a couple days on and off, but it keeps failing to build grpcio. Any output I could post that would help? It looks like it is not compiling, but I'm not great at interpreting python output.

**Comment by xdays** [comment]
@samho93 @calebjohn24 @gnat79 you guys can give this solution a try, it works for me.

https://github.com/grpc/grpc/issues/24677#issuecomment-729983060

**Comment by gnat79** [comment]
> @samho93 @calebjohn24 @gnat79 you guys can give this solution a try, it works for me.
> 
> [#24677 (comment)](https://github.com/grpc/grpc/issues/24677#issuecomment-729983060)

That worked. I used "GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install grpcio" and then I was able to complete the install and it appears to be successful after a couple quick tests.

THANK YOU!

**Comment by gPass0s** [comment]
I was able to solve by running `pip install wheel`

**Comment by muzammil360** [comment]
> > Hi @gapro20022,
> > Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.
> 
> I can confirm this, I was having trouble installing grpc in a Jetson Xavier AGX and this solved it

I was trying to install yolov5 on xavier NX. I was about to downgrade when installation completed successfully on its own. Using 
docker `nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3` on `r32.5.1`

**Comment by speedplane** [comment]
For anyone seeing this more recently, you grpcio [1.40.0 was recently released on Sep 7, 2021](https://pypi.org/project/grpcio/#history), and this issue came up again for me. Adding the following to my requirements file locked in the earlier version:

```
grpcio==1.39.0; python_version < '3.0'
```

**Comment by Florian-Bolli** [comment]
pip install --upgrade pip

**Comment by tpaulshippy** [comment]
This also happened when we accidentally used pypy instead of python. We use github actions to setup python and accidentally had this:

```
    - name: Setup Python
      uses: actions/setup-python@v4 
      with:
        python-version: pypy3.8 
```

We fixed it by changing to:
```
    - name: Setup Python
      uses: actions/setup-python@v4 
      with:
        python-version: 3.8
```

**Comment by PavelPrist** [comment]
Hey! Help please!
 I am stuck during
install grpc   grpcio-1.59.2 :  Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... |
Mac Pro 11.7.10

**Comment by NickNaskida** [comment]
> Hey! Help please! I am stuck during install firebase-admin and it needs install grpc grpcio-1.59.2 : Building wheels for collected packages: grpcio Building wheel for grpcio (setup.py) ... | Mac Pro 11.7.10

Same issue :( Have you found a fix?

**Comment by arslan-rashidov** [comment]
> > Hey! Help please! I am stuck during install firebase-admin and it needs install grpc grpcio-1.59.2 : Building wheels for collected packages: grpcio Building wheel for grpcio (setup.py) ... | Mac Pro 11.7.10
> 
> Same issue :( Have you found a fix?

+
Have you found a fix?))

**Comment by NickNaskida** [comment]
@arslan-rashidov I was using the alpine version of python image in my Dockerfile. Changing it to a slim version helped `python:3.11.6-slim`

**Comment by AbhisekBag** [comment]
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... - 
  
  while installing tensorflow with python=3.10
  
  It runs forever. Pls help.

**Comment by anhnlh** [comment]
This issue is CLOSED. Please have some decency. Just make a new issue, how hard is it? Owners, contributors with write access, PLEASE lock this conversation. Thank you 🙏
@ctiller @jtattermusch @markdroth @vjpai

**Comment by maiiabocharova** [comment]
For me 
```
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
```
solved the problem

**Comment by TeddyZaremba** [comment]
For me this fixed the issue 
```bash
python3 -m pip install --upgrade pip setuptools wheel
```

setuptools==75.3.2
wheel==0.45.1
