### ISSUE TITLE
when I install grpcio it crashes when running: "Running setup.py install for grpcio ... \"

### ISSUE THREAD

**Issue by keikomori** [grpc/grpc#24037]
### What version of gRPC and what language are you using?
I'm install a version grpcio==1.30.0 - python==3.6.9

### What operating system (Linux, Windows,...) and version?
Lubuntu version 18.04.5

### What runtime / compiler are you using (e.g. python version or version of gcc)
I'm using a python version

### What did you do?
dont
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
So its work!!!!!

### What did you see instead?

`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hpq5jtn0/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-48xyxihh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hpq5jtn0/grpcio/`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by rajesh0therascal** [comment]
Similar problem.

While installing tensorflow on Jetson Nano, It requires grpcio 
Failed to build wheel for grpcio
Jetpack Version : 4.3
Ubuntu : 18.04.5 LTS
Python: 3.6.9
grpcio: 1.31.0

Python-dev and setuptools updated to latest versions as on date.

Error description:

<pre><font color="#CC0000">ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 
&apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-install-eofuxbpa/grpcio/setup.py&apos;&quot;&apos;&quot;&apos;; 
__file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-install-eofuxbpa/grpcio/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)
(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);
f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; 
install --record /tmp/pip-record-bl2egy6d/install-record.txt --single-version-externally-managed 
--compile --install-headers /usr/local/include/python3.6/grpcio 
Check the logs for full command output.</font>
</pre>

**Comment by rajesh0therascal** [comment]
Hi @keikomori 

Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.

**Comment by sidikalamini** [comment]
Facing similar error yesterday while installing tensorflow. Installation of grpcio successful after downgrading setuptools to 47.3.1 from 50.x (latest version)

**Comment by keikomori** [comment]
> Hi @keikomori
> 
> Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.

ok I will try.

**Comment by chinvelski** [comment]
Hi, 

> Hi @keikomori
> 
> Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.

Worked for me. Thanks

**Comment by OmarAlmighty** [comment]
I tried installing using pip3 and it works

First, upgrade pip3
`sudo -H pip3 install --upgrade pip`

Then, install it:
`pip3 install grpcio`

**Comment by kptkin** [comment]
For me it helped to upgrade `pip` as well!

> I tried installing using pip3 and it works
> 
> First, upgrade pip3 `sudo -H pip3 install --upgrade pip`
> 
> Then, install it: `pip3 install grpcio`
