### ISSUE TITLE
Specify Source Address in Channel Creation

### ISSUE THREAD

**Issue by thaishankar** [grpc/grpc#24035]
### Is your feature request related to a problem? Please describe.
Request a way for client side binding to a source address. I have multiple network interfaces on the client side, each with a source address in a different network. The outgoing traffic from the client to the server seems to be going on an arbitrary interface as decided by the Operating System. Would it be possible to add an option to channel creation to use a specific source address?

### Describe the solution you'd like
Current Implementation:
Channel channel = new Channel(serverAddress, ChannelCredentials.Insecure, channelOptions);

Proposed:
Channel channel = new Channel(serverAddress, sourceAddress, ChannelCredentials.Insecure, channelOptions);

A similar solution seems to exist for Java and Go
grpc/grpc-java#4900
https://stackoverflow.com/questions/57278822/sending-grpc-communications-over-a-specific-port

**Comment by markdroth** [comment]
You didn't say what language this is for, but from the code snippet, I'm guessing it's C#.  Routing accordingly.

**Comment by thaishankar** [comment]
Sorry I didn't add the language earlier! Yes it is C#

**Comment by apolcyn** [comment]
Adding myself since Jan is OOO for the next few weeks.

I could imagine a channel arg to specify a source address causing the grpc/TCP code to bind to it before calling "connect" on a socket. It would probably need to be ported to the different platforms, though.

Looks like Go and Java support this, some relevant conversation in https://github.com/grpc/grpc-java/issues/4900.

cc @markdroth @yang-g @yashykt -- any thoughts?

**Comment by thaishankar** [comment]
Hi @apolcyn , want to follow up on the status of this and to see if this is a feature you plan on supporting.
This would be very useful for anyone who uses Grpc with C# and also brings it in parity with Java and Go.

**Comment by thaishankar** [comment]
Hey guys any updates on this? We would like to use GRPC on our platform but we are blocked on the decision as we need this feature

**Comment by markdroth** [comment]
I think this is something that we should do, but I don't know that we'll have time to get to it anytime soon.  If someone wants to contribute code to C-core to allow this, we can talk about the best way to implement it.  We might be able to leverage the socket mutator code-path somehow.

**Comment by thaishankar** [comment]
@markdroth @jtattermusch  If this feature is not actively worked on, I was wondering if I might be able to assist with some of the changes. 

I took a quick look at the source code if I followed the call stack correctly, C# Channel create seems to call grpc_channel_create in 
https://github.com/grpc/grpc/blob/3d4bb01e1d1942c44c1d8961bdabb400a3af046e/src/core/lib/surface/channel.cc.

**Comment by jtattermusch** [comment]
> @markdroth @jtattermusch If this feature is not actively worked on, I was wondering if I might be able to assist with some of the changes.
> 
> I took a quick look at the source code if I followed the call stack correctly, C# Channel create seems to call grpc_channel_create in
> https://github.com/grpc/grpc/blob/3d4bb01e1d1942c44c1d8961bdabb400a3af046e/src/core/lib/surface/channel.cc.

No -  that's a codepath that C++ uses, not C#.
See e.g. https://github.com/grpc/grpc/blob/3f011c2171612edf1a54ca106a1c092e08534d33/src/csharp/ext/grpc_csharp_ext.c#L432

**Comment by jtattermusch** [comment]
Since Grpc.Core is now in maintenance mode (see https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0), I don't see a point in adding this functionality now. If this is something that will be needed in grpc-dotnet, we can open an issue there (the API for creating a channel is different in grpc-dotnet and this issue is specific to Grpc.Core).
