### ISSUE TITLE
Broken ObjC test testKeepaliveWithV2API with BDP fix #22997

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#24039]
After #22997 which fixes bdp pings to not be sent unnecessarily, testKeepaliveWithV2API was affected and disabled.

**Comment by yulin-liang** [comment]
Looks like the client doesn't receive the close callback in 32s. I'm going to increase the test timeout to see if it works. I'll enable it when it is fixed.

**Comment by yashykt** [comment]
This test does not affect the sending of keepalive pings. Can you share the logs for the test, or maybe help me run the test locally?

**Comment by yulin-liang** [comment]
Here's a failure log: https://source.cloud.google.com/results/invocations/c80b152d-8aab-42ba-994a-4b498ab42006/log

When running the test on Xcode locally, I can always get `error code 14`. I don't know why it always fails on Kokoro.

**Comment by yashykt** [comment]
I was looking for logs with
GRPC_VERBOSITY=DEBUG and GRPC_TRACE=all env variables so that we can get traces.
