### ISSUE TITLE
Delay on first connection in C# with grpclb and c-ares

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#24042]
### What version of gRPC and what language are you using?
C# 2.31.0 via NuGET

### What operating system (Linux, Windows,...) and version?
Windows 10 Enterprise 1803

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019 Professional 16.7.0
.NET Core 3.1 / .NET Standard 2.1

### What did you do?
```
public static async Task Main(string[] args)
{
  Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");
  Environment.SetEnvironmentVariable("GRPC_TRACE", "all");
  using var logger = TextWriter.Synchronized(File.CreateText("test.txt"));
  GrpcEnvironment.SetLogger(new TextWriterLogger(logger));

  Channel channel = new Channel("dns://127.0.0.1:8010/test.my-company.com", ChannelCredentials.Insecure, new[]
  {
    new ChannelOption("grpc.lb_policy_name", "grpclb"),
    new ChannelOption("grpc.service_config", "{\"serviceConfig\":{\"load_balancing_config\":{ \"grpclb\": {} },\"waitForReady\":true}}"),
    new ChannelOption("grpc.dns_enable_srv_queries", 1)
  });

  var client = new Delay.DelayClient(channel);
  var reply = await client.TestDelayAsync(new DelayRequest{Ticks = DateTime.UtcNow.Ticks});
  Console.WriteLine("Ticks: " + reply.Ticks);
  reply = await client.TestDelayAsync(new DelayRequest{Ticks = DateTime.UtcNow.Ticks});
  Console.WriteLine("Ticks: " + reply.Ticks);

  await channel.ShutdownAsync();
  Console.WriteLine("Press any key to exit...");
  Console.ReadKey();
}
```

### What did you expect to see?
The first call being slightly slower than the second due to DNS resolution, load balancing and subchannel creation,

### What did you see instead?
There is a huge delay before the first request is even trying to contact the DNS server of around 10-35 seconds: [test.txt](https://github.com/grpc/grpc/files/5157697/test.txt)

### Anything else we should know about your project / environment?
Doing direct calls to a IPv4 target results in the expected small delay without big time gap. So it seems to be related to c-ares or grpclb. Can’t use native DNS resolver as I need the authority to use grpclb as there is no way to define a resolver in C# or target grpclb directly (see #11879, #13639, #16617, #19874).

This is an issue for us since 2017 and especially Android will become a big issue for as since there is neither support for the resolver nor for c-ares to abuse as our workaround. We will have a look at xDS in the future, but I still first need to get our code working again as the last releases seem to have broken our workaround.

_Originally posted by @Falco20019 in https://github.com/grpc/grpc/issues/24018#issuecomment-684991069_

**Comment by Falco20019** [comment]
@apolcyn As promised, here a test shortly after rebooting. The machine was not close to it's limits.

The channel was created on 08:38:34, name resolution started the same second and the resolver returned success on 08:39:04... So round about 30 seconds.

![grafik](https://user-images.githubusercontent.com/940619/91939579-5fb48f00-ecf6-11ea-9638-8a03b71ee581.png)
[test2.txt](https://github.com/grpc/grpc/files/5160539/test2.txt)

**Comment by Falco20019** [comment]
@apolcyn I tested it with a colleague in my company. The same behavior with the same delays of 15 - 60 seconds.

**Comment by apolcyn** [comment]
Interesting. The unexpectedly long amount of time in what appears to be a non-blocking c-ares DNS lookup initiation is definitely suspicious.

Is it possible for you to use perhaps a debugger to briefly pause the process during those 15 seconds, and dump stack traces of all threads? (Or a wall time profiler may also accomplish roughly the same) Maybe that can show a suspicious mutex wait or blocking I/O....

**Comment by Falco20019** [comment]
I assume you need a C++ debugger? Or should I be able to dump the trace as windump with C# / Windows? The native DLL should be included in the managed application, so it might appear. I have the JetBrains Ultimate suite at hand. So dotMemory and dotTrace dumps might help.

I will give it a try.

**Comment by apolcyn** [comment]
Something that can see native stack traces would be ideal.

**Comment by Falco20019** [comment]
I sadly can not see the native stack trace. Is there an easy way to get a `grpc_csharp_ext.x64.dll` with symbols without having to setup the whole build environment? Technically, JetBrains dotTrace would have the capability to also trace native code if symbols are available. So it only notes that 57.5% of the trace have no resolved functions.

![grafik](https://user-images.githubusercontent.com/940619/91976487-4d9c1600-ed21-11ea-8bc6-d55cc2b72358.png)

**Comment by apolcyn** [comment]
I believe you can get symbols from the `Grpc.Core.NativeDebug` nuget ? https://github.com/grpc/grpc/issues/15437 for a bit of background

**Comment by Falco20019** [comment]
Thanks for the hint about `Grpc.Core.NativeDebug`. I was able to create a dump while it was stuck.

![grafik](https://user-images.githubusercontent.com/940619/92110597-40e3f480-edeb-11ea-87ee-cafea46475d4.png)
![grafik](https://user-images.githubusercontent.com/940619/92110571-36c1f600-edeb-11ea-879b-52b686e13683.png)

To me (without knowing too much C++ and c-ares), it looks like it's stuck on reading my hosts file. I will give that file a look.

**Comment by Falco20019** [comment]
I just checked my host files and it was 300 MB, mostly consisting of empty lines and 5 lines of Docker... Would be interesting if Docker messed the file up or if our IT was the culprit. By resetting the hosts file to default, gRPC runs like a charm again!

Thanks for the support @apolcyn!

**Comment by apolcyn** [comment]
Good to know, interesting find @Falco20019 !
