### ISSUE TITLE
adding data to context  from  server  intercept_service  in python

### ISSUE THREAD

**Issue by girirajthara** [grpc/grpc#24048]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by JScon01** [comment]
Hi,I need some help. I want to speak with anyone with C++ experience.

**Comment by donnadionne** [comment]
Could you clarify your question?  Some sample code would help.  Also,  Is this a question in C++ or python?

**Comment by girirajthara** [comment]
class SignatureValidationInterceptor(grpc.ServerInterceptor):
  def __init__(self):

    def abort(ignored_request, context):
      context.abort(grpc.StatusCode.UNAUTHENTICATED, 'Invalid signature')
    self._abortion = grpc.unary_unary_rpc_method_handler(abort)
  def intercept_service(self, continuation, handler_call_details):
    '''' want to add data to metadata through handler_call_details """
    return continuation(handler_call_details)

**Comment by gnossen** [comment]
You can modify the `handler_call_details` before passing them on to the continuation. [This example](https://github.com/grpc/grpc/blob/7c1dab7297dfe6cc9a72ee95cc83866612db0628/examples/python/interceptors/headers/request_header_validator_interceptor.py#L37) isn't exactly the same, but it should be instructive.

**Comment by gnossen** [comment]
If this isn't enough information, feel free to ping the thread.

**Comment by girirajthara** [comment]
> If this isn't enough information, feel free to ping the thread.


that example shows just checking with the handler , I want to add data. Please can I get an example?

**Comment by gnossen** [comment]
@girirajthara Sorry for the delay. Suppose you wanted to add metadata, you could do something like this:

```python
    def intercept_service(self, continuation, handler_call_details):
        handler_call_details.invocation_metadata = handler_call_details.invocation_metadata + ('new_key', 'new_value')
        return continuation(handler_call_details)
```

**Comment by girirajthara** [comment]
I am getting an error while running your code 
grpcio==1.32.0
python:3.7.3
error : (<class 'AttributeError'>, AttributeError("can't set attribute"), <traceback object at 0x7fd48a21fa88>)

**Comment by kushagra-arta** [comment]
@gnossen 
```
   def intercept_service(self, continuation, handler_call_details):
        handler_call_details.invocation_metadata = handler_call_details.invocation_metadata + ('new_key', 'new_value')
        return continuation(handler_call_details)
 ```

This does not seem to work. Facing the same issue as @girirajthara. Any workarounds?

**Comment by chamini2** [comment]
Hi, I am getting

```
	details = "Unexpected <class 'AttributeError'>: attribute 'invocation_metadata' of 'grpc._cython.cygrpc._HandlerCallDetails' objects is not writable"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:6005 {created_time:"2022-12-12T16:36:35.474689-04:00", grpc_status:2, grpc_message:"Unexpected <class \'AttributeError\'>: attribute \'invocation_metadata\' of \'grpc._cython.cygrpc._HandlerCallDetails\' objects is not writable"}"
```

It seems we cannot set the `invocation_metadata`. Is this intentional or should we be able to add metadata to it in server side?

**Comment by seaguest** [comment]
@girirajthara @chamini2 
Hello guys, have you solved the problem?
I have the same needs, how to make it work?

**Comment by seaguest** [comment]
for people who come across the same problem, please check this [PR](https://github.com/grpc/grpc/pull/32840)
this does work for me.
