### ISSUE TITLE
Python gRPC client can't handle HTTP2 GOAWAY frame properly

### ISSUE THREAD

**Issue by huangchong94** [grpc/grpc#24069]
### What version of gRPC and what language are you using?

server: Nginx 1.17.8 as load balancer  gRPC python server  grpcio==1.26.0

client: python gRPC grpcio==1.31.0 (1.26.0 also tested)

### What operating system (Linux, Windows,...) and version?
server: linux centos 2.6.32-573.3.1.el6.x86_6

client: macOS 10.14.2

### What runtime / compiler are you using (e.g. python version or version of gcc)
python  3.8

### What did you do?
python gRPC client send requests in a loop, while looping, reload Nginx

### What did you expect to see?
python client will handle this situation reconnect automatically

### What did you see instead?
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1599533975.386975000","description":"Error received from peer ipv4:172.30.73.37:10000","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
```

### packet capture result using Wireshark
1. Nginx send HTTP2 GOAWAY
2. Nginx send TCP [FIN]
3. client respond two TCP [ACK]
4. client send gRPC request
5. client send HTTP2 RST_STREAM
5. client send TCP [FIN, ACK]
6. Nginx send TCP [RST] connection closed

**Comment by hijerusalem** [comment]
hello anybody?

**Comment by mantasmatelis** [comment]
I've also been bit by this issue, it's hard to include nginx as a reliable proxy/loadbalancer for gRPC because of it. I think it's an issue for all C-core gRPC implementations.

I've been following https://github.com/grpc/grpc/issues/9884, I think resolving that issue is a requirement for the client to handle GOAWAY frames correctly.

**Comment by ejona86** [comment]
> 1. Nginx send HTTP2 GOAWAY
> 2. Nginx send TCP [FIN]

If there's only a single GOAWAY, then nginx isn't doing a graceful shutdown of the HTTP/2 connection and that will result in failures that can only be solved client-side with retries. If you don't want failures, then nginx would need to send one GOAWAY with last-stream-id of MAX_INT, wait a period of time for the client to receive it, and then a second GOAWAY and bring down the connection (assuming there are no streams still).

I don't recall offhand if nginx does a graceful goaway. I know it used to not do so when it initially added HTTP/2 support, but it might have improved the situation.

**Comment by XuanWang-Amos** [comment]
Closing this issue since it should be fixed in lasted release, if this issue still exist, please open a new issue.
