### ISSUE TITLE
Can't find re2 on Homebrew

### ISSUE THREAD

**Issue by nealrichardson** [grpc/grpc#24077]
### What version of gRPC and what language are you using?

1.31.1

### What operating system (Linux, Windows,...) and version?

macOS

### What runtime / compiler are you using (e.g. python version or version of gcc)

Homebrew

### What did you do?

The update of the grpc Homebrew formula today seems to have changed how dependencies are resolved. grpc appears to build from source any dependencies not declared as coming from system packages, and it appears that these third party libraries get installed in the same location that the system package would go. So on Apache Arrow, when we test on macOS with Homebrew dependencies, we now get a failure because it can't install `re2` with Homebrew due to the fact that grpc has installed something with the same name: https://github.com/apache/arrow/pull/8136/checks?check_run_id=1087052173#step:4:442

To work around this, I tried to add `re2` as a system dependency to `grpc`'s Homebrew formula: https://github.com/Homebrew/homebrew-core/pull/60803

But this fails like this:

```
CMake Error at cmake/re2.cmake:45 (find_package):
  Could not find a package configuration file provided by "re2" with any of
  the following names:

    re2Config.cmake
    re2-config.cmake

  Add the installation prefix of "re2" to CMAKE_PREFIX_PATH or set "re2_DIR"
  to a directory containing one of the above files.  If "re2" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:228 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/grpc-20200908-27206-nt2b8t/cmake/build/CMakeFiles/CMakeOutput.log".
```

I also tried setting `-Dre2_DIR=#{Formula["re2"].prefix}` in the Homebrew formula, but that also didn't help it find the cmake config file it was looking for. (I also searched the `re2` install directory and didn't find one.)

### What did you expect to see?

I expected that I would be able to use system/Homebrew `re2` for `grpc`, which would have resolved the dependency clash. I also would have expected that if `grpc` were vendoring third-party libraries, that they wouldn't cause path/name collisions for other projects.

### What did you see instead?

See above.

**Comment by veblush** [comment]
Because I don't know about how homebrew manages and builds gRPC and re2, I'm not sure but this might be relevant to #24088 which makes gRPC to use system-wide installed re2.

**Comment by donnadionne** [comment]
MacOS builds are currently running fine with RE2 as a dependency.
