### ISSUE TITLE
How can i have a control over Server Streaming?

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc#24071]
Hi, 
I have a scenario which is described with the following:
gRPC Version is : 1.19.0
i am streaming data from server to client by using API IServerStreamWriter. 
On the Client side i am trying to read the streamed data by using IAsyncStreamReader :

while (await call.ResponseStream.MoveNext().ConfigureAwait(false))
 {
      ......
 }

Since there are no data streamed from client side, i found that i am not getting out of this loop (client side) as fast as i expected.

**First Question**      : Do i need to set the completeness of the streaming from the server side.
**Second Question** : Am i able (On the client side) to check that the streaming (ResponseStream) is Completed?     
otherwise this Call **call.ResponseStream.MoveNext()** causes some exception, because this call tries to pick up unavailable data.

**Third Question**   : Is there any possibilities to define some time out for waiting the data on the client side.

I have so far checked what is provided by the API on the server side IServerStreamWriter, and on the client side IAsyncStreamReader, which it doesn't help me to achieve my Goal.
Do i need to get a new upgraded gRPC version, which could help me further?

Thanks a lot for any help.

Best regards
Anas

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
