### ISSUE TITLE
[Ruby] Add setter for GRPC.logger

### ISSUE THREAD

**Issue by nvh0412** [grpc/grpc#24084]
### Is your feature request related to a problem? Please describe.
Inside our system, we're using logger object which is passed from some upstream services, sometime it's instance of Logger ruby module, sometime it's Rails logger and sometime it's logging gem. It leads us to quite hard to inject these logger instance into `GRPC.logger` to get `info logs`

### Describe the solution you'd like
Implement a setter for logger of GRPC module which allows upstream service (or used place) easy to inject their custom logger

### Describe alternatives you've considered
Upstream service can inject their logger instance by themselve by using GRPC.extend(Module.new.....), but I believe it isn't a suitable way to use a custom logger inside a library

**Comment by nvh0412** [comment]
@markdroth  and @apolcyn is there any chance to make it happen?

**Comment by gabetax** [comment]
The official docs for setting up a logger are at https://cloud.google.com/ruby/docs/reference/google-cloud-pubsub/latest/LOGGING

The suggested syntax from that page is:

```ruby
require "logger"
require "grpc"

module MyLogger
  LOGGER = Logger.new $stderr, level: Logger::WARN
  def logger
    LOGGER
  end
end

# Define a gRPC module-level logger method before grpc/logconfig.rb loads.
module GRPC
  extend MyLogger
end
```

Using order dependent monkey-patching for basic configuration seems notably unidiomatic, and a setter method would be welcome.
