### ISSUE TITLE
FLAKE: github/grpc/run_tests/csharp_windows_dbg_native_default_coreclr/csharp.Grpc.IntegrationTesting.ExternalDnsWithTracingClientServerTest[default]

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#24096]
https://source.cloud.google.com/results/invocations/3f6ae5c0-1f9e-4f29-9426-662744f367ad/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_dbg_native_default_coreclr%2Fcsharp.Grpc.IntegrationTesting.ExternalDnsWithTracingClientServerTest/tests

**Comment by apolcyn** [comment]
Internal issue with some analysis and history in b/158831490

**Comment by jtattermusch** [comment]
This only failed once in the last 3 months.
 https://source.cloud.google.com/results/invocations/c7821df8-12ab-4555-9ceb-fbdac4d4b47c

I'm going to close.

If we ever have to reopen, let's fine an internal bug (we're going to track flakiness in buganizer going forward).
