### ISSUE TITLE
[MIPS64] Google.Protobuf.Tools cannot determine host OS and CPU

### ISSUE THREAD

**Issue by xiangzhai** [grpc/grpc#24105]
Hi,

### What version of gRPC and what language are you using?

* v1.28.0 and master
* C#

### What operating system (Linux, Windows,...) and version?

Linux 3.10.84-20.fc21.loongson.3.mips64el

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 4.9.4

### What did you do?

1. dotnet new grpc
2. dotnet build

dotnet SDK for MIPS64:  https://github.com/gsvm/loongson-dotnet/releases

### What did you expect to see?

Support MIPS64:  https://github.com/grpc/grpc/pull/24068

### What did you see instead?

```
/home/loongson/.nuget/packages/grpc.tools/2.27.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/home/loongson/zhaixiang/HelloGRPC/HelloGRPC.csproj]
/home/loongson/.nuget/packages/grpc.tools/2.27.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64} to try the closest match to your system. [/home/loongson/zhaixiang/HelloGRPC/HelloGRPC.csproj]
/home/loongson/.nuget/packages/grpc.tools/2.27.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). [/home/loongson/zhaixiang/HelloGRPC/HelloGRPC.csproj]
    0 Warning(s)
    1 Error(s)
```

Thanks,
Leslie Zhai

**Comment by jtattermusch** [comment]
We don't support MIPS64 as a platform, sorry. There is also no plan to add such support because there's little demand, it would require a lot of work and we also don't have a way to test on MIPS64
