### ISSUE TITLE
grpcio-1.32 fail to open 'Con.proto'

### ISSUE THREAD

**Issue by jvesely** [grpc/grpc#24106]
### What version of gRPC and what language are you using?
grpcio-1.32.0, grpcio-tools-1.32.0

### What operating system (Linux, Windows,...) and version?
windows server 2019  (10.0.17763)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python-3.6.8 (but also observed on 3.7.9 and 3.8.5)
Linux nad macOS do not see this issue

### What did you do?

import elfi

### What did you expect to see?
 success

### What did you see instead?
```
self = <grpc_tools.protoc.ProtoFinder object at 0x0000023B38439470>
fullname = 'ConfigParser', path = None, target = None

    def find_spec(self, fullname, path, target=None):
        filepath = _module_name_to_proto_file(self._suffix, fullname)
        for search_path in sys.path:
            try:
                prospective_path = os.path.join(search_path, filepath)
>               os.stat(prospective_path)
E               OSError: [WinError 87] The parameter is incorrect: 'D:\\a\\PsyNeuLink\\PsyNeuLink\\Con.proto'

c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\grpc_tools\protoc.py:152: OSError
```

The full CI log can be found at https://github.com/PrincetonUniversity/PsyNeuLink/runs/1093766511?check_suite_focus=true#step:14:169

The error indicates that 'Con' was interpreted as an attempt to stat a console: 

### Anything else we should know about your project / environment?
`D:\a\PsyNeuLink\PsyNeuLink` is the working directory
Reverting to 1.31.0 fixes the issue: https://github.com/jvesely/PsyNeuLink/runs/1094860822?check_suite_focus=true

**Comment by gnossen** [comment]
@jvesely Thanks for the report! I'm working on a fix for this to be added to a patch. For the moment, you can set the `GRPC_PYTHON_DISABLE_DYNAMIC_STUBS` environment variable to `true` to get working with 1.32.0 in the meantime.
