### ISSUE TITLE
ObjC Tests not working(1.33.0-dev)

### ISSUE THREAD

**Issue by zhungxd** [grpc/grpc#24107]
### What version of gRPC and what language are you using?
grpc-objc 1.33.0-dev

### What operating system (Linux, Windows,...) and version?
Mac

### What did you do?
pod install
run objective-c/tests/Tests.xcworkspace

### What did you expect to see?
build success

### What did you see instead?
build failed

grpc/src/core/ext/upb-generated/udpa/annotations/versioning.upb.c:10:10: fatal error: 'upb/msg.h' file not found
#include "upb/msg.h"
         ^~~~~~~~~~~
1 error generated.

seems not generate the COCOAPODS change
#if COCOAPODS==1
  #include  "third_party/upb/upb/msg.h"
#else
  #include  "upb/msg.h"
#endif

**Comment by yulin-liang** [comment]
That's really weird, we do generate **#if COCOAPODS==1** statement for `vesioning.upb.c`(https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L1746). I couldn't reproduce it. Can you try to clean and rebuild it? If it still doesn't work, can you check if **1.32.0** works?

**Comment by zhungxd** [comment]
1.32.0 works. I will retry.
