### ISSUE TITLE
Better Python support by integrating python-betterproto

### ISSUE THREAD

**Issue by soerenwolfers** [grpc/grpc#24110]
The Python integration of gRPC/protobuf has a lot of obvious flaws
- No `__init__.py` module files get generated
- Output is not importable
  - Import paths break in Python 3 unless you mess with `sys.path`
- Bugs when names clash (e.g. `codecs` package)
- Generated code is not idiomatic
  - Completely unreadable runtime code-generation
  - Much code looks like C++ or Java ported 1:1 to Python
  - Capitalized function names like `HasField()` and `SerializeToString()`
  - Uses `SerializeToString()` rather than the built-in `__bytes__()`
  - Special wrapped types don't use Python's `None`
  - Timestamp/duration types don't use Python's built-in `datetime` module
- No typing support or code completion/intelligence (requires additional `mypy` plugin)
- No `async` support (requires additional `grpclib` plugin)

In it's current state, gRPC/protobuf is really no fun to work with in Python.

The list above is taken from https://github.com/danielgtaylor/python-betterproto , which solves a lot of these, but it feels weird to use a non-standard version of something that I mainly use because it's a standard. 

Would it be a lot of work to merge python-betterproto into the official grpc repo?

**Comment by gnossen** [comment]
@soerenwolfers I agree with basically all the pain points in your message except for one:

> No async support (requires additional grpclib plugin)

This is no longer true. The `grpcio` library now natively supports `asyncio`.

I think the two biggest impedances are level of effort and backwards compatibility. Addressing all of these issues is something we'd like to get to eventually, but it's not the highest priority item we have. If you (or someone else) would like to write up a gRFC at https://github.com/grpc/proposal and look into the implementation, we'd be more than happy to help the process along.

**Comment by wj-Mcat** [comment]
Wating for the `betterproto` support.
