### ISSUE TITLE
Does gPRC support proto2 with c++?

### ISSUE THREAD

**Issue by rocqina** [grpc/grpc#24122]
And which tag in master supports it?

I make install the latest version of grpc. And the protoc --version is libprotoc 3.13.0.

In fact I hope to keep the  protoc --version is libprotoc 2.x.x becasue I do not want the class is final in xxx.pb.h.

Can we do it in grpc?  If can do it,  which tag in master supports it?

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
