### ISSUE TITLE
Python client fails when using TLS

### ISSUE THREAD

**Issue by robbrit** [grpc/grpc#24129]
### What version of gRPC and what language are you using?

Python client 1.32.0
Go server v1.29.1

### What operating system (Linux, Windows,...) and version?
Linux: Debian Buster

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.4
Go 1.13.5

### What did you do?
On the client side, all RPCs using TLS are failing - doesn't matter the target or the endpoint.

To reproduce:
* set up a basic gRPC server using a Go server and Python client with the versions listed above
* make an RPC using TLS

### What did you expect to see?
The RPCs to function correctly.

### What did you see instead?

A stack trace:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/code/shared/services/jobs/job_manager_client.py", line 167, in get_workflows
    response = stub.GetWorkflows(request, timeout=grpc_utils.DEFAULT_TIMEOUT_SECS)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1599857253.622139009","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1599857253.622132398","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```
Afterwards, this message starts repeating, even when using the Python REPL:
```
E0911 20:48:01.468607783     312 ssl_transport_security.cc:1439] Handshake failed with fatal error SSL_ERROR_SSL: error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT.
```

### Anything else we should know about your project / environment?
It's running on Google Cloud, Kubernetes engine. These are RPCs over the local network.

Rolling back to Python client v1.31.0 fixes the problem. We didn't need to change the Go server at all.

This was an accidental discovery; only one of our Python microservices did not have a hard-coded version of `grpcio` in their requirements file. The gRPC client was accidentally pulled in through another package (opencensus) and since it worked until now, nobody noticed that it was missing from the requirements file.
The other services were working just fine, it was just this one that started failing after the v1.32.0 release 2 days ago.

**Comment by adampinky85** [comment]
Hi all, we're encountering the same issue, our project works with server-side tls encryption using grpcio v1.31.0 but fails with the latest version with the openssl error below. Is there a known workaround to enable our codebase to upgrade grpcio?

Client side error:
_E0526 16:53:37.779055036   25206 ssl_transport_security.cc:1468] Handshake failed with fatal error SSL_ERROR_SSL: error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT._

Environment:
_Ubuntu 20.04.2 LTS
Python 3.9.1_

**Comment by jiangtaoli2016** [comment]
@ZhenLian @matthewstevenson88  The error is related to choosing the wrong key algorithm. Did we change the cipher list or order of cipher list recently in gRPC SSL transport security?

**Comment by yihuazhang** [comment]
The only PR that touches `ssl_transport_security.cc` in between v1.31.0 and v1.32.0 is [Re-enable TLS 1.3 in the C-core.](https://github.com/grpc/grpc/commit/85337d69c2439eba90a4b8985402c78ef84754b8#diff-d156f50027c4d27c927b506ac4813b3446b41337e92103513cfab376979aef1d). @robbrit, could you please try reverting the changes in the above PR, and see if it works?

**Comment by matthewstevenson88** [comment]
+1, I wonder if this is related to enabling TLS 1.3.

@robbrit @adampinky85 What SSL library + version are you using (e.g. OpenSSL/BoringSSL/LibreSSL/...)?

**Comment by adampinky85** [comment]
Hi thanks @matthewstevenson88 and team, further debugging yesterday found a solution. During local development, we're using self-signed certificates, for both the client / server using openssl. 

Our previous openssl config file set the `keyUsage = keyEncipherment, dataEncipherment` which works in the earlier version of grpcio. Updating the `keyUsuage` for `digitalSignature` resolves the issues and works in the latest grpcio.

It would be great to understand the issue further and what has changed. I'm assuming our certificates were not well formed previously for mutual TLS?

openssl version
_OpenSSL 1.1.1f  31 Mar 2020_

**Comment by matthewstevenson88** [comment]
Between the 2 gRPC releases, we enabled TLS 1.3 by default, as @yihuazhang pointed out. My guess is that OpenSSL's TLS 1.3 libraries require that the `digitalSignature` bit is set (as is required by the [spec](https://datatracker.ietf.org/doc/html/rfc8446#section-4.4.2.2)), but OpenSSL's TLS 1.2 libraries do not require this.

Unfortunately, I don't know enough about OpenSSL's internals to confirm this. Perhaps @agl or @davidben may know?

**Comment by agl** [comment]
TLS prior to 1.3 included non-forward secure modes that encrypted data to the peer's public key. TLS 1.3 is always forward-secure and thus always needs to create signatures.

The correct behaviour here isn't starkly clear. There's an argument that BoringSSL should transparently limit the connection to TLS 1.2 if the certificate isn't capable of signing. On the other hand, allowing subtle issues like this to downgrade the security of the connection seems like setting a trap for people. Since having the incorrect key usage is always (in my experience) unintentional, and we want to clean things up for TLS 1.3, it's currently an error and the error name, at least, points pretty strongly in the correct direction.

**Comment by matthewstevenson88** [comment]
Thanks for clarifying @agl!

Closing this, since I think we've gotten to the bottom of the issue, but please feel free to re-open if we missed anything.

**Comment by davidben** [comment]
BTW, this isn't a TLS 1.3 only thing. We have code to enforce the bit in TLS 1.2 as well and will eventually enable that too, once we've gotten it fully enabled in Chrome.
