### ISSUE TITLE
Error in completion queue next

### ISSUE THREAD

**Issue by ncarenton** [grpc/grpc#24139]
### What version of gRPC and what language are you using?
grpc:1.32.0

### What operating system (Linux, Windows,...) and version?
ubuntu:16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.5.6

### What did you do?
Could not reproduce

### What did you expect to see?
No errors

### What did you see instead?

`E0913 05:15:51.161517349   54841 completion_queue.cc:1280]   Completion queue next failed: {"created":"@1599974151.161498165","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":321,"referenced_errors":[{"created":"@1599974151.161496624","description":"Invalid argument","errno":22,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":948,"os_error":"Invalid argument","syscall":"epoll_wait"}]}`

and

`E0913 05:09:40.453355688  164358 completion_queue.cc:1280]   Completion queue next failed: {"created":"@1599973780.453341299","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":321,"referenced_errors":[{"created":"@1599973780.453339821","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":948,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}`

### Anything else we should know about your project / environment?

Sorry I do not have much more information, what would be the steps to dig further? I suspect this to be caused by `google-cloud-bigtable` or `google-cloud-storage` since I moved from grpc:1.28 to grpc:1.31.0

Here is the pipdeptree:

    - google-cloud-bigtable [required: Any, installed: 1.4.0]
      - google-api-core [required: >=1.14.0,<2.0.0dev, installed: 1.21.0]
        - google-auth [required: >=1.18.0,<2.0dev, installed: 1.18.0]
          - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
          - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
            - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
          - rsa [required: >=3.1.4,<5, installed: 4.6]
            - pyasn1 [required: >=0.1.3, installed: 0.4.8]
          - setuptools [required: >=40.3.0, installed: 46.1.3]
          - six [required: >=1.9.0, installed: 1.15.0]
        - googleapis-common-protos [required: >=1.6.0,<2.0dev, installed: 1.52.0]
          - protobuf [required: >=3.6.0, installed: 3.12.2]
            - setuptools [required: Any, installed: 46.1.3]
            - six [required: >=1.9, installed: 1.15.0]
        - protobuf [required: >=3.12.0, installed: 3.12.2]
          - setuptools [required: Any, installed: 46.1.3]
          - six [required: >=1.9, installed: 1.15.0]
        - pytz [required: Any, installed: 2020.1]
        - requests [required: >=2.18.0,<3.0.0dev, installed: 2.24.0]
          - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
          - chardet [required: >=3.0.2,<4, installed: 3.0.4]
          - idna [required: >=2.5,<3, installed: 2.8]
          - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.9]
        - setuptools [required: >=34.0.0, installed: 46.1.3]
        - six [required: >=1.10.0, installed: 1.15.0]
      - google-cloud-core [required: >=1.0.3,<2.0dev, installed: 1.3.0]
        - google-api-core [required: >=1.16.0,<2.0.0dev, installed: 1.21.0]
          - google-auth [required: >=1.18.0,<2.0dev, installed: 1.18.0]
            - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
            - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
              - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
            - rsa [required: >=3.1.4,<5, installed: 4.6]
              - pyasn1 [required: >=0.1.3, installed: 0.4.8]
            - setuptools [required: >=40.3.0, installed: 46.1.3]
            - six [required: >=1.9.0, installed: 1.15.0]
          - googleapis-common-protos [required: >=1.6.0,<2.0dev, installed: 1.52.0]
            - protobuf [required: >=3.6.0, installed: 3.12.2]
              - setuptools [required: Any, installed: 46.1.3]
              - six [required: >=1.9, installed: 1.15.0]
          - protobuf [required: >=3.12.0, installed: 3.12.2]
            - setuptools [required: Any, installed: 46.1.3]
            - six [required: >=1.9, installed: 1.15.0]
          - pytz [required: Any, installed: 2020.1]
          - requests [required: >=2.18.0,<3.0.0dev, installed: 2.24.0]
            - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
            - chardet [required: >=3.0.2,<4, installed: 3.0.4]
            - idna [required: >=2.5,<3, installed: 2.8]
            - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.9]
          - setuptools [required: >=34.0.0, installed: 46.1.3]
          - six [required: >=1.10.0, installed: 1.15.0]
      - grpc-google-iam-v1 [required: >=0.12.3,<0.13dev, installed: 0.12.3]
        - googleapis-common-protos [required: >=1.5.2,<2.0.0dev, installed: 1.52.0]
          - protobuf [required: >=3.6.0, installed: 3.12.2]
            - setuptools [required: Any, installed: 46.1.3]
            - six [required: >=1.9, installed: 1.15.0]
        - grpcio [required: >=1.0.0,<2.0.0dev, installed: 1.31.0]
          - six [required: >=1.5.2, installed: 1.15.0]
    - google-cloud-storage [required: Any, installed: 1.29.0]
      - google-auth [required: >=1.11.0,<2.0dev, installed: 1.18.0]
        - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
        - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
          - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
        - rsa [required: >=3.1.4,<5, installed: 4.6]
          - pyasn1 [required: >=0.1.3, installed: 0.4.8]
        - setuptools [required: >=40.3.0, installed: 46.1.3]
        - six [required: >=1.9.0, installed: 1.15.0]
      - google-cloud-core [required: >=1.2.0,<2.0dev, installed: 1.3.0]
        - google-api-core [required: >=1.16.0,<2.0.0dev, installed: 1.21.0]
          - google-auth [required: >=1.18.0,<2.0dev, installed: 1.18.0]
            - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
            - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
              - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
            - rsa [required: >=3.1.4,<5, installed: 4.6]
              - pyasn1 [required: >=0.1.3, installed: 0.4.8]
            - setuptools [required: >=40.3.0, installed: 46.1.3]
            - six [required: >=1.9.0, installed: 1.15.0]
          - googleapis-common-protos [required: >=1.6.0,<2.0dev, installed: 1.52.0]
            - protobuf [required: >=3.6.0, installed: 3.12.2]
              - setuptools [required: Any, installed: 46.1.3]
              - six [required: >=1.9, installed: 1.15.0]
          - protobuf [required: >=3.12.0, installed: 3.12.2]
            - setuptools [required: Any, installed: 46.1.3]
            - six [required: >=1.9, installed: 1.15.0]
          - pytz [required: Any, installed: 2020.1]
          - requests [required: >=2.18.0,<3.0.0dev, installed: 2.24.0]
            - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
            - chardet [required: >=3.0.2,<4, installed: 3.0.4]
            - idna [required: >=2.5,<3, installed: 2.8]
            - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.9]
          - setuptools [required: >=34.0.0, installed: 46.1.3]
          - six [required: >=1.10.0, installed: 1.15.0]
      - google-resumable-media [required: >=0.5.0,<0.6dev, installed: 0.5.1]
        - six [required: Any, installed: 1.15.0]

**Comment by lidizheng** [comment]
@ncarenton Ideally, we will need a reproduction case to work on this issue. Can you provide information about: 1. how was this error being triggered?; 2. led to what behavior?; 3. if you upgrade to 1.32, is the problem fixed?

**Comment by pkaminsk** [comment]
I have seen similar issue. It is random and rare, happens only during initialization. If it happens application is unusable. I believe file descriptor is corrupted. In my case it is gRPC 1.17. What in general may cause FD to go/initialize badly in polling work?

**Comment by lidizheng** [comment]
@pkaminsk please file another issue with detailed error log and reproduction case.

I'm closing this issue as the reporter was inactive.
