### ISSUE TITLE
Windows applications using Microsoft leak detection (_CRTDBG_LEAK_CHECK_DF) report hundreds of leaks

### ISSUE THREAD

**Issue by stefan301** [grpc/grpc#24133]
gRPC version: 1.31.1 installed with vcpkg (compiled with Visual Studio 2017)

Language: C++

OS: Windows 10

Compiler: Visual Studio 2017

I Just enabled the leak check in the Helloworld example (GreeterClient.cpp) by adding this line at the beginning of main to show the problem we are having in our big old legacy application that absolutely has to use this feature to avoid introducing leaks):

```
int main(int argc, char** argv) {
	_CrtSetDbgFlag(_CRTDBG_LEAK_CHECK_DF);
// main code of GreeterClient.cpp

}
```

### What did you expect to see?

I didn't expect to see this message at the end of the GreeterClient: 'Detected memory leaks!'

### What did you see instead?

Detected memory leaks!
Dumping objects ->
{1771} normal block at 0x006E01D8, 4 bytes long.
 Data: < n  > 94 6E 20 01 
{1770} normal block at 0x006E00E8, 4 bytes long.
 Data: <`m  > 60 6D 20 01 
{1769} normal block at 0x006E0148, 4 bytes long.
 Data: < n  > 80 6E 20 01 
{1768} normal block at 0x006DD1B8, 16 bytes long.
 Data: <  m 8 m $Y    5 > C8 9F 6D 00 38 CD 6D 00 24 59 20 01 10 D0 35 01 
{1767} normal block at 0x006EBCE0, 8 bytes long.
 Data: <  n     > 1C ED 6E 00 00 00 00 00 
..................
{157} normal block at 0x006CB7E8, 8 bytes long.
 Data: <H Hz    > 48 10 48 7A 00 00 00 00 
Object dump complete.
The program '[34088] GreeterClient.exe' has exited with code 0 (0x0).

-> 208 memory leaks 

### Anything else we should know about your project / environment?

adding google::protobuf::ShutdownProtobufLibrary(); at the end of main, reduced the number of leaks to 3, but grpc still 'leaks' memory:

```
int main(int argc, char** argv) {
	_CrtSetDbgFlag(_CRTDBG_LEAK_CHECK_DF);

// main code of GreeterClient.cpp

	google::protobuf::ShutdownProtobufLibrary();
	return 0;
}
```

Detected memory leaks!
Dumping objects ->
{1771} normal block at 0x017FD7E8, 4 bytes long.
 Data: < nE > 94 6E 45 01 
{1770} normal block at 0x017FD8A8, 4 bytes long.
 Data: <`mE > 60 6D 45 01 
{1769} normal block at 0x017FD938, 4 bytes long.
 Data: < nE > 80 6E 45 01 
Object dump complete.

**I know these leaks are not real leaks because the memory is reclaimed by the OS at the end of the process, but it makes the leak detection feature completely useless.**

same issue as 'gRPC v1.29.1 memory leaks #23330' but hopefully illustrated more clearly.

**Comment by markdroth** [comment]
If this is the same issue as in #23330, let's just track it there -- we don't need two bugs for the same issue.
