### ISSUE TITLE
Cannot run interop for cpp in 1.32.0

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#24134]
Looks like the docker build for cxx is broken so not able to find bins/opt/interop_client in the docker image.

$ tools/interop_matrix/run_interop_matrix_tests.py -l cxx --release v1.32.0
PASSED: pull_image_gcr.io/grpc-testing/grpc_interop_cxx:v1.32.0 [time=18.5sec, retries=0:0]

bash: bins/opt/interop_client: No such file or directory
FAILED: cxx__cxx_v1.32.0:cxx:grpc-test:large_unary [ret=127, pid=245082, time=0.8sec]

@markdroth

**Comment by markdroth** [comment]
Nico, any idea what might be wrong here?

**Comment by jtattermusch** [comment]
@srini100  do you want to finish the C++ 1.32.0 interop matrix or should I do it?

**Comment by srini100** [comment]
@jtattermusch, can you please take care of this in case any other issue pops up?
