### ISSUE TITLE
absl compiling error during gRPC C++ build using cmake Fetchcontent

### ISSUE THREAD

**Issue by KestutisMa** [grpc/grpc#24143]
### What version of gRPC and what language are you using?
v1.32.0

### What operating system (Linux, Windows,...) and version?
Windows 10, Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.

### What did you do?
Adding gRPC to cmake project using *fetchcontent* as described here: https://github.com/grpc/grpc/tree/master/src/cpp#fetchcontent

### What did you expect to see?
Configure step without errors

### What did you see instead?
```
CMake Error at build/_deps/grpc-src/third_party/abseil-cpp/CMake/AbseilHelpers.cmake:350 (message):
[cmake]    ABSL: compiling absl requires a gtest CMake target in your project,
[cmake]                      see CMake/README.md for more details
[cmake] Call Stack (most recent call first):
[cmake]   build/_deps/grpc-src/third_party/abseil-cpp/CMakeLists.txt:105 (check_target)
```

**Comment by KestutisMa** [comment]
could be related to https://github.com/abseil/abseil-cpp/issues/74

**Comment by veblush** [comment]
This was fixed by https://github.com/abseil/abseil-cpp/issues/690 and gRPC will pick the new Abseil version soon by #24270
