### ISSUE TITLE
Unity package protobuf version does not match

### ISSUE THREAD

**Issue by krzysztofsroga** [grpc/grpc#24142]
Operating System: Linux Manjaro (newest)
Unity version: 2020.1.3f1 
gRPC versions affected: 2.27-2.33

I was following [the guide](https://github.com/grpc/grpc/tree/master/src/csharp/experimental):
 - Create new project in Unity
 - Change runtime to .NET 4.x
 - Extract the `grpc_unity_package` into Assets

Unity throws an error:
```
Assembly 'Assets/Plugins/Google.Protobuf/lib/net45/Google.Protobuf.dll' will not be loaded due to errors:
Google.Protobuf references strong named System.Memory in a different folder, versions has to match. Assembly references: 4.0.1.0 Found in project: 4.0.1.1.
```
At first I tried this with the newest version (2.33). Then I checked 2.32 and tried older ones month by month. The newest version that runs without an error is 2.26
It does not work with this build and newer: [2.27](https://packages.grpc.io/archive/2020/02/a747a50cc12e21f09001aac622ce649b556d5a10-a4cb86ab-ec70-41bd-ad42-f50ed39084d5/index.xml)
It does work with this build and older: [2.26](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)

It's an empty project on clean Unity installation.

**Comment by jtattermusch** [comment]
This should be fixed by https://github.com/protocolbuffers/protobuf/pull/7940 (which will be in the next protobuf release).

**Comment by trakevital** [comment]
For me Uninstalling System.Memory in NugetForUnity plus a bit of "surgical work" did the trick (it changed System.Memory from 4.5.3 to 4.5.2)
