### ISSUE TITLE
Is there a C++ equivalent of the Java Any.pack() class/method?

### ISSUE THREAD

**Issue by ericmandm** [grpc/grpc#24165]
I'm trying to pack another proto (e.t. deviceStatus) into the Status proto but I cannot find 'Any' in the c++ API, nor any examples about how to do this in C++
Thanks

Java Code:
```
com.google.rpc.Status build = com.google.rpc.Status.newBuilder()
        .setCode(grpcErrorCode.getNumber())
        .setMessage(dex.getMessage())
        .addDetails(Any.pack(deviceStatus))
        .build();
```

**Comment by markdroth** [comment]
This form is for bugs and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
