### ISSUE TITLE
Wasm cross-platform support

### ISSUE THREAD

**Issue by itamarsher** [grpc/grpc#24166]
I'm want to compile a C++ library that uses grpc to WASM (Web Assembly) using Emscripten (Upstream) + CMake (3.18.0)
I've managed to compile the grpc library itself after patching (hacking) a little bit of code to prevent grpc from using some features that don't exist (as far as I can tell) in WASM.
Sadly, when I try to load the compiled code in node (12.8.1) I get a pretty ambiguous error: 
`failed to asynchronously prepare wasm: CompileError: AsyncCompile: Wasm decoding failed: unexpected section: Code @+34028`

The CMake configuration that I've used is (some of it is probably redundant):
`cmake ../../ -DCMAKE_INSTALL_PREFIX="~/wasm_dist/" -DgRPC_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=~/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DgRPC_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CROSSCOMPILING=1 -DCMAKE_CXX_FLAGS=-DJSON_USE_INT64_DOUBLE_CONVERSION -DCMAKE_C_FLAGS_RELEASE="-s WASM=1" -DCMAKE_CXX_FLAGS_RELEASE="-s WASM=1 -s USE_PTHREADS=1" -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-lwebsocket.js -s USE_PTHREADS=1 -fexcess-precision=standard -s WASM=1 -s MALLOC=emmalloc -s MODULARIZE=1 -static -s LLD_REPORT_UNDEFINED" -DOPENSSL_NO_ASM=TRUE -DgRPC_BUILD_CSHARP_EXT=OFF`

the patches that I've made:
```
diff --git a/include/grpc/impl/codegen/port_platform.h b/include/grpc/impl/codegen/port_platform.h
index 33f8a1a59d..f10bd4cbf9 100644
--- a/include/grpc/impl/codegen/port_platform.h
+++ b/include/grpc/impl/codegen/port_platform.h
@@ -396,6 +396,50 @@
 #define GPR_POSIX_TIME 1
 #define GPR_HAS_PTHREAD_H 1
 #define GPR_GETPID_IN_UNISTD_H 1
+#elif defined(__EMSCRIPTEN__)
+#define GPR_PLATFORM_STRING "emscripten"
+#ifndef _BSD_SOURCE
+#define _BSD_SOURCE
+#endif
+#ifndef _DEFAULT_SOURCE
+#define _DEFAULT_SOURCE
+#endif
+#ifndef _GNU_SOURCE
+#define _GNU_SOURCE
+#endif
+#include <features.h>
+#define GPR_CPU_POSIX 1
+#define GPR_GCC_ATOMIC 1
+#define GPR_GCC_TLS 1
+#define GPR_POSIX_TMPFILE 1
+#define GPR_POSIX_STRING 1
+#define GPR_POSIX_SYNC 1
+#define GPR_POSIX_TIME 1
+#define GPR_POSIX_LOG 1
+#define GPR_POSIX_ENV 1
+#define GPR_HAS_PTHREAD_H 1
+#define GPR_ARCH_32 1
+#define GRPC_POSIX_HOST_NAME_MAX 1
+#define GRPC_POSIX_WAKEUP_FD 1
+#define GRPC_POSIX_NO_SPECIAL_WAKEUP_FD // wakeup_fd_nospecial.cc
+#define GRPC_POSIX_SOCKET_EV_POLL // ev_poll_posix.cc
+#define GRPC_ARES 0 // don't use the c-ares dns
+#define GRPC_POSIX_SOCKET 1 // some functions are only defined if this is on (TODO: more detailed)
+#define GRPC_POSIX_SOCKET_IF_NAMETOINDEX 1
+#define GRPC_POSIX_SOCKET_IOMGR 1 // This is recquired by the client channel
+#define GRPC_POSIX_SOCKET_EV 1 // ev_posix.cc
+#define GRPC_POSIX_SOCKET_EV_EPOLL1 1 // ev_epoll1_linux.cc needs this to create dummy grpc_init_epoll1_linux
+#define GRPC_POSIX_SOCKET_EV_EPOLLEX 1 // ev_epollex_linux.cc needs this to create dummy grpc_init_epollex_linux
+#define GRPC_POSIX_SOCKET_RESOLVE_ADDRESS 1
+#define GRPC_POSIX_SOCKET_SOCKADDR 1
+#define GRPC_POSIX_SOCKET_SOCKET_FACTORY 1
+#define GRPC_POSIX_SOCKET_TCP 1
+#define GRPC_POSIX_SOCKET_TCP_CLIENT 1
+#define GRPC_POSIX_SOCKET_TCP_SERVER 1
+#define GRPC_POSIX_SOCKET_TCP_SERVER_UTILS_COMMON 1
+#define GRPC_POSIX_SOCKET_UTILS_COMMON 1
+#define GRPC_LINUX_SOCKETUTILS // accept4
+#define GPR_NO_AUTODETECT_PLATFORM 1
 #else
 #error "Could not auto-detect platform"
 #endif
diff --git a/src/core/lib/iomgr/port.h b/src/core/lib/iomgr/port.h
index 2a8d67b261..3b7a2f807c 100644
--- a/src/core/lib/iomgr/port.h
+++ b/src/core/lib/iomgr/port.h
@@ -196,6 +196,7 @@
 #endif
 
 #ifdef GRPC_POSIX_SOCKET
+#ifndef __EMSCRIPTEN__
 #define GRPC_POSIX_SOCKET_ARES_EV_DRIVER 1
 #define GRPC_POSIX_SOCKET_EV 1
 #define GRPC_POSIX_SOCKET_EV_EPOLLEX 1
@@ -213,6 +214,7 @@
 #define GRPC_POSIX_SOCKET_UDP_SERVER 1
 #define GRPC_POSIX_SOCKET_UTILS_COMMON 1
 #endif
+#endif
 
 #if defined(GRPC_POSIX_HOST_NAME_MAX) && defined(GRPC_POSIX_SYSCONF)
 #error "Cannot define both GRPC_POSIX_HOST_NAME_MAX and GRPC_POSIX_SYSCONF"
```

I'll be posting a similar issue on Emscripten's repo, but regardless I was wondering if anyone else managed to compile grpc to WASM. Also feel free to pop in and convince me that what I'm doing doesn't make sense (I'll use it in production eventually) 

**EDIT:** The hello world example fails with this error code when launching greeter_server - RuntimeError: abort(CompileError: AsyncCompile: Wasm decoding failed: unexpected section: Code @+37085)

Thanks in advance

**Comment by sbc100** [comment]
This looks like a pretty fundamental issue, like the wasm file produced by emscripten is not valid.  Lets follow up on emscripten-core/emscripten#12257.

**Comment by itamarsher** [comment]
Updating after getting some help in the Emscripten repo. 
Now the server starts running but I get another error.
I intend to continue investigating, so feel free to leave this issue open and I'll update here on my progress. 
```
node --experimental-wasm-threads --experimental-worker --experimental-wasm-bulk-memory greeter_server.js
E0919 20:05:53.487000000  632752 cpu_posix.cc:41]                      Cannot determine number of CPUs: assuming 1
E0919 20:05:53.504000000  632752 socket_utils_common_posix.cc:223]     check for SO_REUSEPORT: {"created":"@1600535153.504000000","description":"Protocol not available","errno":50,"file":"~/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":198,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}
E0919 20:05:53.506000000  632752 server_chttp2.cc:40]                  {"created":"@1600535153.505000000","description":"No address added out of total 1 resolved","file":"~/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1600535153.505000000","description":"Failed to add any wildcard listeners","file":"~/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":341,"referenced_errors":[{"created":"@1600535153.505000000","description":"Unable to configure socket","fd":3,"file":"~/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1600535153.505000000","description":"Protocol not available","errno":50,"file":"~/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":239,"os_error":"Protocol not available","syscall":"setsockopt(TCP_NODELAY)"}]},{"created":"@1600535153.505000000","description":"Unable to configure socket","fd":3,"file":"~/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1600535153.505000000","description":"Protocol not available","errno":50,"file":"~/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":239,"os_error":"Protocol not available","syscall":"setsockopt(TCP_NODELAY)"}]}]}]}
Server listening on 0.0.0.0:50051
exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[61]:0x9d26
    at main (<anonymous>:wasm-function[63]:0x9e6f)
    at ~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:26530
    at callMain (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:211052)
    at doRun (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:211649)
    at run (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:211821)
    at runCaller (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:210458)
    at removeRunDependency (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:25341)
    at receiveInstance (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:27553)
    at receiveInstantiatedSource (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:27883)
```

**Comment by itamarsher** [comment]
Updating again, I hacked into grpc code again and disabled additional socket features - SO_REUSEADDR, SO_REUSEPORT, and TCP_NODELAY. Now the code runs without errors but Stub->SayHello (using greeter_client.cc) never returns. 
I used Wireshark to sniff the loopback device and I didn't see and network activity initiated by the wasm greeter client.
Due to the limited debugging in WASM I'm not sure what will be the best approach to narrowing done what's the problem on the grpc side of things (besides inserting prints in the grpc code and waiting a couple of minutes between compile times).
Since the support seems experimental at best, I've decided against using grpc within WASM at the moment. If you need anything further from me than please let me know.

**Comment by markdroth** [comment]
Seems like this is not being actively worked on at the moment, so I'm going to close it.  Feel free to file a new issue if you need something else.

**Comment by abdullahaygun** [comment]
> Updating again, I hacked into grpc code again and disabled additional socket features - SO_REUSEADDR, SO_REUSEPORT, and TCP_NODELAY. Now the code runs without errors but Stub->SayHello (using greeter_client.cc) never returns. I used Wireshark to sniff the loopback device and I didn't see and network activity initiated by the wasm greeter client. Due to the limited debugging in WASM I'm not sure what will be the best approach to narrowing done what's the problem on the grpc side of things (besides inserting prints in the grpc code and waiting a couple of minutes between compile times). Since the support seems experimental at best, I've decided against using grpc within WASM at the moment. If you need anything further from me than please let me know.

I'm trying to compile gRPC with Web WASM with Emscripten, but it keeps giving errors. 
I wonder if you could do it? 
Thanks.

**Comment by jellespijker** [comment]
Are there any plans to add support for WASM support. I'm currently investigating if we can run [CuraEngine](https://github.com/Ultimaker/CuraEngine) (the slicing engine of UltiMaker [Cura](https://github.com/Ultimaker/Cura)) client-side using WASM.
