### ISSUE TITLE
Mysterious SymInitialize failure when running tests using Bazel RBE on Windows 

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#24178]
### What version of gRPC and what language are you using?

gRPC C++

### What operating system (Linux, Windows,...) and version?

Windows / Bazel-RBE

### What runtime / compiler are you using (e.g. python version or version of gcc)

HEAD

### What did you do?

Running test
- Bazel RBE Windows Debug C/C++ 
- Bazel RBE Windows Opt C/C++ 

### What did you expect to see?

Passed

### What did you see instead?

Following tests failed

- //test/core/client_channel/resolvers:dns_resolver_connectivity_using_native_resolver_test
- //test/cpp/qps:qps_json_driver_test_cpp_generic_async_streaming_qps_unconstrained_insecure
- //test/cpp/qps:qps_json_driver_test_cpp_protobuf_async_streaming_from_client_1channel_1MB
- //test/cpp/qps:qps_json_driver_test_cpp_protobuf_sync_streaming_qps_unconstrained_insecure

Error message: (note that 2147483653 = 0x80000005)

```
[symbolize_win32.inc : 53] RAW: SymInitialize() failed: 2147483653
```

When rerunning tests after renaming these tests, failing tests changed like

- //test/cpp/qps:qps_jd_cpp_generic_async_streaming_qps_unconstrained_2waysharedcq_insecure
- //test/cpp/qps:qps_jd_cpp_protobuf_async_streaming_from_client_qps_unconstrained_insecure
- //test/cpp/qps:qps_jd_cpp_protobuf_async_streaming_from_server_qps_unconstrained_insecure
- //test/cpp/qps:qps_jd_cpp_protobuf_async_streaming_qps_unconstrained_2waysharedcq_insecure

This is not like that tests with a long name fail because there were other tests with way longer one. But it seems like that tests with 89 or 90 length of the name tend to fail.

Example of failure: 
- https://source.cloud.google.com/results/invocations/6ad2cdc1-4913-402a-84e7-e582dc9f41ae/targets
- https://source.cloud.google.com/results/invocations/db0dd6bd-cf82-4b33-bf0f-8e7c025a9580/targets

internal b/169902891

**Comment by jtattermusch** [comment]
Not sure if that's related, but we do call SymInitialize when trying to install  crash handler on Windows in our tests:

https://github.com/grpc/grpc/blob/c516eb7c09f06766bb4f253fbd2281efa1b865ad/test/core/util/test_config.cc#L182

**Comment by jtattermusch** [comment]
@veblush  can you provide a few link to said failures FTR?

**Comment by veblush** [comment]
@jtattermusch Thanks. I added links to the failures to the description.

Abseil uses the same function with the same arguments.
https://github.com/abseil/abseil-cpp/blob/887d0eee6bab35847253181b32e78ff707010ccd/absl/debugging/symbolize_win32.inc#L48

When the abseil debugging symbolizer is used by gRPC, `install_crash_handler` won't be called so they're mutually exclusive. The difference is that Abseil aborts when it gets an error from `SymInitialize` but gRPC doesn't. I guess gRPC's windows crash handler wasn't able to get symbols for these strange targets.

**Comment by jtattermusch** [comment]
Is this perhaps similar to b/151617965?

**Comment by drfloob** [comment]
The same inscrutable error is popping up in flaky the past 8 hours or so: b/187424257. I didn't find any reputable reference for the error code.

**Comment by davinci26** [comment]
I am also observing this issue in Envoy CI. 

If it helps with anything this error is either `STATUS_BUFFER_OVERFLOW (The data was too large to fit into the specified buffer.)` or `E_POINTER (Invalid pointer)`.

It is hard to know exactly without knowing the exact system calls that absl is doing

**Comment by wrowe** [comment]
This is what abseil is doing; https://github.com/abseil/abseil-cpp/blob/887d0eee6bab35847253181b32e78ff707010ccd/absl/debugging/symbolize_win32.inc#L48

**Comment by veblush** [comment]
They added the [code](https://github.com/bazelbuild/bazel/commit/42e05dbd606a5059126bda14cdfffa5e0653b652) to workaround this issue and there is no release including this yet and it will be the next version of 4.0.0 presumably.

**Comment by jtattermusch** [comment]
Is this still happening or can we close as obsolete? Please reopen if needed.
