### ISSUE TITLE
I am getting an error while adding metadata to handler_call_details.invocation_metadata in intercept_service 

### ISSUE THREAD

**Issue by girirajthara** [grpc/grpc#24179]
@gnossen I am getting this error.Can you please help me out

I am getting an error while running your code 
grpcio==1.32.0
python:3.7.3
error : (<class 'AttributeError'>, AttributeError("can't set attribute"), <traceback object at 0x7fd48a21fa88>)

_Originally posted by @girirajthara in https://github.com/grpc/grpc/issues/24048#issuecomment-694657454_

**Comment by markdroth** [comment]
This form is for reporting bugs and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
