### ISSUE TITLE
ProtosCompiler unable to locate Classes

### ISSUE THREAD

**Issue by PeterJD** [grpc/grpc#24195]
Currently using Recode to convert WCF app to grpc all classes etc appear to be converted, a bit like AutoMapper

But the ProtoCompiler errors
BalanceDto" is not defined.

project ContractCore	
file contract_core.proto 

any ideas what the issue is
Kind regards
Peter

**Comment by PeterJD** [comment]
using grpc.AspNetCore

**Comment by jtattermusch** [comment]
Sorry, I don't understand what is the issue you're facing. You'd need to provide more details and code examples.
