### ISSUE TITLE
TLS not working in latest tag grpc core 1.32 - C++

### ISSUE THREAD

**Issue by dilipnd** [grpc/grpc#24196]
### What version of gRPC and what language are you using?
gRPC core 1.32 tag

### What operating system (Linux, Windows,...) and version?
Centos 8

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++

### Issue: TLS not working. Service API returns after sometime

Server Side code:
       ServerBuilder builder;
        grpc::SslServerCredentialsOptions sslOpts;
        sslOpts.client_certificate_request = GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE;
        sslOpts.force_client_auth = false;
        sslOpts.pem_key_cert_pairs.push_back(
                    grpc::SslServerCredentialsOptions::PemKeyCertPair{readFile(keyfile),
                    readFile(servcert)});
        sslOpts.pem_root_certs = readFile(_config->getCACert());
        auto creds = grpc::SslServerCredentials(sslOpts);
        builder.AddListeningPort(address, creds);
        builder.RegisterService(&service);
        server = builder.BuildAndStart();
    	server->Wait();

Client code:
        grpc::SslCredentialsOptions sslOpts;
        sslOpts.pem_root_certs = readFile(_config->getCACert());
        sslOpts.pem_cert_chain = "";
        sslOpts.pem_private_key = "";
        auto creds = grpc::SslCredentials(sslOpts);
        auto channel = grpc::CreateChannel(address, creds);
        grpcClient client(channel);

When I invoke my Service API from client. The client API hangs for some time and then return the following error
"errorcode: 14 , failed to connect to all addresses"

**Comment by dilipnd** [comment]
The same code when used with grpc core 1.31 works fine.
When 1.32 core is used, it is not working

**Comment by dilipnd** [comment]
### **Server trace:**
D0921 02:49:44.859482050    6364 ev_posix.cc:173]            Using polling engine: epollex
D0921 02:49:44.859717438    6364 lb_policy_registry.cc:40]   registering LB policy factory for "grpclb"
D0921 02:49:44.859734694    6364 lb_policy_registry.cc:40]   registering LB policy factory for "cds_experimental"
D0921 02:49:44.859743246    6364 lb_policy_registry.cc:40]   registering LB policy factory for "eds_experimental"
D0921 02:49:44.859757092    6364 lb_policy_registry.cc:40]   registering LB policy factory for "lrs_experimental"
D0921 02:49:44.859768477    6364 lb_policy_registry.cc:40]   registering LB policy factory for "priority_experimental"
D0921 02:49:44.859776040    6364 lb_policy_registry.cc:40]   registering LB policy factory for "weighted_target_experimental"
D0921 02:49:44.859783614    6364 lb_policy_registry.cc:40]   registering LB policy factory for "xds_routing_experimental"
D0921 02:49:44.859791442    6364 lb_policy_registry.cc:40]   registering LB policy factory for "pick_first"
D0921 02:49:44.859799085    6364 lb_policy_registry.cc:40]   registering LB policy factory for "round_robin"
D0921 02:49:44.859808863    6364 dns_resolver_ares.cc:507]   Using ares dns resolver
E0921 02:49:44.859846818    6364 trace.cc:65]                Unknown trace var: 'transport_security'
I0921 02:49:44.860185902    6364 server_builder.cc:319]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0921 02:49:44.861318814    6364 socket_utils_common_posix.cc:352] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I0921 02:51:01.631224539    6377 handshaker.cc:99]           handshake_manager 0x7fffd4001920: adding handshaker security [0x7fffd400b2e0] at index 0
I0921 02:51:01.631277858    6377 handshaker.cc:129]          handshake_manager 0x7fffd4001920: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffd4000ea0, args=0x7fffd4002520 {size=4: grpc.primary_user_agent=grpc-c++/1.32.0, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x63bb30, grpc.security_connector=0x649e90}, read_buffer=0x7fffd400b7c0 (length=0), exit_early=0}
I0921 02:51:01.631290060    6377 handshaker.cc:176]          handshake_manager 0x7fffd4001920: calling handshaker security [0x7fffd400b2e0] at index 0
I0921 02:51:21.628798115    6377 handshaker.cc:99]           handshake_manager 0x7fffd400bbc0: adding handshaker security [0x7fffd401ec20] at index 0
I0921 02:51:21.628832726    6377 handshaker.cc:129]          handshake_manager 0x7fffd400bbc0: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffd4027a70, args=0x7fffd4020ed0 {size=4: grpc.primary_user_agent=grpc-c++/1.32.0, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x63bb30, grpc.security_connector=0x649e90}, read_buffer=0x7fffd4027ec0 (length=0), exit_early=0}
I0921 02:51:21.628844015    6377 handshaker.cc:176]          handshake_manager 0x7fffd400bbc0: calling handshaker security [0x7fffd401ec20] at index 0
D0921 02:51:21.628893471    6377 security_handshaker.cc:184] Security handshake failed: {"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]}
I0921 02:51:21.628948189    6377 handshaker.cc:129]          handshake_manager 0x7fffd4001920: error={"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0921 02:51:21.628961434    6377 handshaker.cc:162]          handshake_manager 0x7fffd4001920: handshaking complete -- scheduling on_handshake_done with error={"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]}
D0921 02:51:21.628972977    6377 chttp2_server.cc:200]       Handshaking failed: {"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]}
I0921 02:51:41.629751999    6377 handshaker.cc:99]           handshake_manager 0x7fffd402d530: adding handshaker security [0x7fffd40137d0] at index 0
I0921 02:51:41.629785764    6377 handshaker.cc:129]          handshake_manager 0x7fffd402d530: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffd4000ea0, args=0x7fffd4001380 {size=4: grpc.primary_user_agent=grpc-c++/1.32.0, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x63bb30, grpc.security_connector=0x649e90}, read_buffer=0x7fffd400b7c0 (length=0), exit_early=0}
I0921 02:51:41.629796884    6377 handshaker.cc:176]          handshake_manager 0x7fffd402d530: calling handshaker security [0x7fffd40137d0] at index 0
D0921 02:51:41.629844542    6377 security_handshaker.cc:184] Security handshake failed: {"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]}
I0921 02:51:41.629983294    6377 handshaker.cc:129]          handshake_manager 0x7fffd400bbc0: error={"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0921 02:51:41.629999135    6377 handshaker.cc:162]          handshake_manager 0x7fffd400bbc0: handshaking complete -- scheduling on_handshake_done with error={"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]}
D0921 02:51:41.630009926    6377 chttp2_server.cc:200]       Handshaking failed: {"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]}
D0921 02:51:41.632800781    6377 security_handshaker.cc:184] Security handshake failed: {"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]}
I0921 02:51:41.632895249    6377 handshaker.cc:129]          handshake_manager 0x7fffd402d530: error={"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0921 02:51:41.632910171    6377 handshaker.cc:162]          handshake_manager 0x7fffd402d530: handshaking complete -- scheduling on_handshake_done with error={"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]}
D0921 02:51:41.632921345    6377 chttp2_server.cc:200]       Handshaking failed: {"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]}




### **CLientside**
D0921 02:49:44.859482050    6364 ev_posix.cc:173]            Using polling engine: epollex
D0921 02:49:44.859717438    6364 lb_policy_registry.cc:40]   registering LB policy factory for "grpclb"
D0921 02:49:44.859734694    6364 lb_policy_registry.cc:40]   registering LB policy factory for "cds_experimental"
D0921 02:49:44.859743246    6364 lb_policy_registry.cc:40]   registering LB policy factory for "eds_experimental"
D0921 02:49:44.859757092    6364 lb_policy_registry.cc:40]   registering LB policy factory for "lrs_experimental"
D0921 02:49:44.859768477    6364 lb_policy_registry.cc:40]   registering LB policy factory for "priority_experimental"
D0921 02:49:44.859776040    6364 lb_policy_registry.cc:40]   registering LB policy factory for "weighted_target_experimental"
D0921 02:49:44.859783614    6364 lb_policy_registry.cc:40]   registering LB policy factory for "xds_routing_experimental"
D0921 02:49:44.859791442    6364 lb_policy_registry.cc:40]   registering LB policy factory for "pick_first"
D0921 02:49:44.859799085    6364 lb_policy_registry.cc:40]   registering LB policy factory for "round_robin"
D0921 02:49:44.859808863    6364 dns_resolver_ares.cc:507]   Using ares dns resolver
E0921 02:49:44.859846818    6364 trace.cc:65]                Unknown trace var: 'transport_security'
I0921 02:49:44.860185902    6364 server_builder.cc:319]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0921 02:49:44.861318814    6364 socket_utils_common_posix.cc:352] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I0921 02:51:01.631224539    6377 handshaker.cc:99]           handshake_manager 0x7fffd4001920: adding handshaker security [0x7fffd400b2e0] at index 0
I0921 02:51:01.631277858    6377 handshaker.cc:129]          handshake_manager 0x7fffd4001920: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffd4000ea0, args=0x7fffd4002520 {size=4: grpc.primary_user_agent=grpc-c++/1.32.0, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x63bb30, grpc.security_connector=0x649e90}, read_buffer=0x7fffd400b7c0 (length=0), exit_early=0}
I0921 02:51:01.631290060    6377 handshaker.cc:176]          handshake_manager 0x7fffd4001920: calling handshaker security [0x7fffd400b2e0] at index 0
I0921 02:51:21.628798115    6377 handshaker.cc:99]           handshake_manager 0x7fffd400bbc0: adding handshaker security [0x7fffd401ec20] at index 0
I0921 02:51:21.628832726    6377 handshaker.cc:129]          handshake_manager 0x7fffd400bbc0: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffd4027a70, args=0x7fffd4020ed0 {size=4: grpc.primary_user_agent=grpc-c++/1.32.0, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x63bb30, grpc.security_connector=0x649e90}, read_buffer=0x7fffd4027ec0 (length=0), exit_early=0}
I0921 02:51:21.628844015    6377 handshaker.cc:176]          handshake_manager 0x7fffd400bbc0: calling handshaker security [0x7fffd401ec20] at index 0
D0921 02:51:21.628893471    6377 security_handshaker.cc:184] Security handshake failed: {"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]}
I0921 02:51:21.628948189    6377 handshaker.cc:129]          handshake_manager 0x7fffd4001920: error={"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0921 02:51:21.628961434    6377 handshaker.cc:162]          handshake_manager 0x7fffd4001920: handshaking complete -- scheduling on_handshake_done with error={"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]}
D0921 02:51:21.628972977    6377 chttp2_server.cc:200]       Handshaking failed: {"created":"@1600671081.628862729","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671081.628712622","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46852"}]}
I0921 02:51:41.629751999    6377 handshaker.cc:99]           handshake_manager 0x7fffd402d530: adding handshaker security [0x7fffd40137d0] at index 0
I0921 02:51:41.629785764    6377 handshaker.cc:129]          handshake_manager 0x7fffd402d530: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffd4000ea0, args=0x7fffd4001380 {size=4: grpc.primary_user_agent=grpc-c++/1.32.0, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x63bb30, grpc.security_connector=0x649e90}, read_buffer=0x7fffd400b7c0 (length=0), exit_early=0}
I0921 02:51:41.629796884    6377 handshaker.cc:176]          handshake_manager 0x7fffd402d530: calling handshaker security [0x7fffd40137d0] at index 0
D0921 02:51:41.629844542    6377 security_handshaker.cc:184] Security handshake failed: {"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]}
I0921 02:51:41.629983294    6377 handshaker.cc:129]          handshake_manager 0x7fffd400bbc0: error={"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0921 02:51:41.629999135    6377 handshaker.cc:162]          handshake_manager 0x7fffd400bbc0: handshaking complete -- scheduling on_handshake_done with error={"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]}
D0921 02:51:41.630009926    6377 chttp2_server.cc:200]       Handshaking failed: {"created":"@1600671101.629816320","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.629677710","description":"Socket closed","fd":29,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:127.0.0.1:60138"}]}
D0921 02:51:41.632800781    6377 security_handshaker.cc:184] Security handshake failed: {"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]}
I0921 02:51:41.632895249    6377 handshaker.cc:129]          handshake_manager 0x7fffd402d530: error={"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0921 02:51:41.632910171    6377 handshaker.cc:162]          handshake_manager 0x7fffd402d530: handshaking complete -- scheduling on_handshake_done with error={"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]}
D0921 02:51:41.632921345    6377 chttp2_server.cc:200]       Handshaking failed: {"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]}

**Comment by jiangtaoli2016** [comment]
@markdroth It looks like connection issue, rather security issue. It fails at security handshake, but due to failure to read handshake data from peer.

```
{"created":"@1600671101.632772082","description":"Handshake read failed","file":"/root/Documents/insta/grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1600671101.632769076","description":"Socket closed","fd":28,"file":"/root/Documents/insta/grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv6:[::1]:46856"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
```

**Comment by erm-g** [comment]
@dilipnd  keeping in mind that the latest release is [1.52.1](https://github.com/grpc/grpc/releases/tag/v1.52.1) - do you still use 1.32 and need a solution for the issue? Assigning P3 priority for now

**Comment by matthewstevenson88** [comment]
Closing since this is on an old release and not reproducible. Please reopen if this is still reproducible.
