### ISSUE TITLE
Warning after upgrading to 1.32.0: RuntimeWarning: 'grpc_tools.protoc' found in sys.modules after import of package 'grpc_tools'

### ISSUE THREAD

**Issue by aliaugmenta** [grpc/grpc#24197]
### What version of gRPC and what language are you using?
1.32.0

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 20.04 (docker)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.2

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
`python3 -m grpc_tools.protoc -I./proto --python_out=output_dir --grpc_python_out=output_dir ./my_proto.proto`

### What did you expect to see?
Nothing, just the output files should be created (that is what happens with grpc 1.31.0)

### What did you see instead?
A warning:
`/usr/lib/python3.8/runpy.py:126: RuntimeWarning: 'grpc_tools.protoc' found in sys.modules after import of package 'grpc_tools', but prior to execution of 'grpc_tools.protoc'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))`

(The output files are the same except a comment line `"""Generated protocol buffer code."""` added in the output generated by 1.32.0)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by aliaugmenta** [comment]
@gnossen , is this the same warning you fixed [here](https://github.com/grpc/grpc/commit/0b543de30a9b2305d72fa87774ff0f9d005fd54a)?

**Comment by DiegoLelis** [comment]
Facing same issue.

**Comment by GlebIgnatevEmlid** [comment]
+1

**Comment by nemanja28** [comment]
+1

**Comment by abhijits1234** [comment]
+1

**Comment by iss1995** [comment]
+1

**Comment by gnossen** [comment]
Thanks for the reports, everyone! #24216 is up to fix this warning message.
