### ISSUE TITLE
Bidirectional streaming with python client and go server having issue

### ISSUE THREAD

**Issue by tejaskumark** [grpc/grpc#24194]
### What version of gRPC and what language are you using?
v1.31

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04 5.4.0-47-generic

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7 and Go 1.15

### What did you do?
- I have created one simple bidirectional streaming RPC, and trying to stream data.
- I have written server in Go 1.15
- I have written client in Python 3.7
- Whenever I start streaming from client sending request, Go server receives request, but also receives EoF from python client once client is finish sending request.
- On Go server, I am using EoF to cancel RPC, and I think that is write way to do. Unless otherwise I am missing something.
- Client written in Go, works fine as expected and it does not sent EoF once client is finish sending request. 

### What did you expect to see?
- I am expecting client behaviour should be across board.
- May be I am wrong, then is there any text indicating how to terminate the RPC from server side?  
- If catching EoF is not write way to do it, then I would need to understand how to handle scenarios where the client actually wanted to close the connection.

### What did you see instead?
- Client written in Go works fine, but client written in python does not work fine.

### Anything else we should know about your project / environment?
- I tried to debug this issue with respect to python client library, and I see that EoF is coming from https://github.com/grpc/grpc/blob/4f0b8dfe56c955e18c1560d034518a494896d4de/src/python/grpcio/grpc/_channel.py#L245
- Why python and go client is behaving differently? May be one of is having BUG Python or Go(I am not sure which one).

**Comment by tejaskumark** [comment]
Hi Experts, Can someone please help me with this ?

**Comment by tejaskumark** [comment]
Hi Experts, Any pointer appreciated.

**Comment by melissop** [comment]
Hi @tejaskumark, I experience the same behavior with gRPC v1.30. 
In my wireshark capture I can clearly see the End Stream flag been raised and sent by my client in the very next packet. 

Let me ask you, which grpcio-tools version did you use to create your _pb2.py files? Not sure if it does make any difference. I used 1.10

**Comment by melissop** [comment]
@tejaskumark in case you are still struggling with this issue, the problem stems in the request iterator you use in your client stub. You should use a custom iterator instead of the the request message described in your proto. In case of bidirectional stream python request will not keep the stream open until you receive a stream response. In order to  keep your stream open you have to control it on application level. Your issue seems to be similar with https://github.com/grpc/grpc/issues/21737
There is a simple iterator implementation snippet here: https://stackoverflow.com/questions/55029342/handling-async-streaming-request-in-grpc-python

**Comment by tejaskumark** [comment]
@melissop Thanks for help. 
```Let me ask you, which grpcio-tools version did you use to create your _pb2.py files? Not sure if it does make any difference. I used 1.10``` I don't think it does make any difference. By the way I am using pb2 from this source - https://github.com/google/gnxi/tree/master/gnmi_cli_py 
I am still not sure where does problem lies, as in case of bidirectional streaming who decides when to terminate RPC.

@gnossen Since you have shared some lights on issue - https://github.com/grpc/grpc/issues/21737 , can you please help me to understand in case of bidirectional streaming who decides when to terminate RPC and based on what criteria. 
My go server simply listen for EOF to terminate RPC. Here is my sample subscribe code, https://github.com/tejaskumark/gnxi/blob/965d41def8472d556ae3f239826471b14f7e4475/gnmi_cli_py/py_gnmicli.py#L419 
Thanks for your help.

**Comment by tejaskumark** [comment]
@gnossen Gentle reminder.

**Comment by gnossen** [comment]
@tejaskumark Yes, there are some semantic differences between Go's `read`/`write` API and the Python sync stack's iterator-based API, but they provide equivalent functionality. If you're looking for something more like Go's API, take a look at the recently introduced `asyncio` support, which supports both styles.

In a bidirectional streaming RPC, the stream will end when either the client's request iterator ends (so, [`req_iterator` here](https://github.com/tejaskumark/gnxi/blob/965d41def8472d556ae3f239826471b14f7e4475/gnmi_cli_py/py_gnmicli.py#L419) in your case) or when the server ends *its* iteration. If you would like the stream to remain open after all requests have been sent, then your request iterator should block without yielding a request until you'd like the stream to end. This will probably involve a `threading.Condition.wait` call.

**Comment by tejaskumark** [comment]
@gnossen Thanks a lot, for quick reply.
