### ISSUE TITLE
GRPC-Core Client inconsistency between Windows/Unix when server shuts down during a request

### ISSUE THREAD

**Issue by Hamza-Q** [grpc/grpc#24206]
### What version of gRPC and what language are you using?
Python client/server using gRPC core 1.32.0 and 1.31.0
C++ client/server using gRPC core 1.31.0
Go client/server using gRPC core 1.31.0

### What operating system (Linux, Windows,...) and version?
Verified with Windows 10 Home, WSL Ubuntu

### What runtime / compiler are you using (e.g. python version or version of gcc)
Windows: Python 3.7.1, go1.13, Visual Studio 2019 - Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x86

Ubuntu 18.04.4 LTS (WSL version 1): python 3.6.9, go1.14.5 linux/amd64, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Using the helloworld example repository:
1) Add an os.Exit or time.Sleep (with a manual keyboard interrupt) to the rpc handler for the greeter server (for example, here: https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_server/main.go#L36 and https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_server.py#L28 )
2) Start the server.
3) Start the client.
4) Shut down the server with a keyboard interrupt (or it will shut down via os.Exit)

### What did you expect to see?
Consistent error between Windows and Unix: Error Code 14 Unavailable with message "Socket closed"

### What did you see instead?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Error Code 2 with message "Stream removed" on Windows.
From the Windows python greeter_client:
```
C:\Users\Hamza\testgrpc\grpc\examples\python\helloworld>python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 37, in <module>
    run()
  File "greeter_client.py", line 31, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "E:\Hamza\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "E:\Hamza\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "{"created":"@1600748422.156000000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Stream removed","grpc_status":2}"
>
```
From the Ubuntu python greeter_client:
```
qureshi@DESKTOP-DHAG5GE:~/grpc/examples/python/helloworld$ python3 greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 37, in <module>
    run()
  File "greeter_client.py", line 31, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/qureshi/.local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/qureshi/.local/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1600747516.913030200","description":"Error received from peer ipv6:[::1]:50052","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
```
I believe this is a client problem since the errors and differences are the same irrespective of whether the server was from the python, c++, or go examples. The grpc-go client also does not experience the same behavior; it has a consistent code 14 "transport is closing" error between OSes.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I tried this on Windows Server 2019 and macOS Mojave 10.14.6 with the same respective Windows/Unix inconsistency between the two. It also occurs between remote machines as long as it is a windows client.

**Comment by markdroth** [comment]
I suspect the Windows code is failing to explicitly set the gRPC status code when it returns an error, so it's winding up UNKNOWN instead of UNAVAILABLE.  @nicolasnoble, can you please take a look?  Thanks!

**Comment by nicolasnoble** [comment]
@markdroth can you point me at the rough codepath that would do this properly on Unix?

**Comment by markdroth** [comment]
I don't know offhand which codepath it is.  But given that the behavior changes based on Linux vs. Windows, it seems like it has to be some Windows-specific code that is not setting the error properly.  Maybe try reproducing the problem with the steps above and enabling a bunch of tracers to see where the status code is coming from on the Linux side?

**Comment by drfloob** [comment]
I think what you're describing here is mostly working as intended. When a server socket is closed abruptly, the _underlying_ error messages received at the client may very well be platform-specific, gRPC doesn't make any guarantees about that. Those nested messages are generally for humans, not machines. Especially given that there's no reference for "platform <X> is correct, platform <Y> is wrong, per <spec>", it's not a bug that platforms differ in these implementation details.

**Comment by Hamza-Q** [comment]
@drfloob I agree that the error message being different is fine, but the problem IMO is that the error code is different for the same scenario of a server socket being closed abruptly.

For some of our robust processes, we'll retry unconditionally for error code 14 UNAVAILABLE to tolerate server downtime/restarts and some specific server errors. We can't do so for error code 2 UNKNOWN. Our server process on Windows is managed by Windows Jobs that don't allow graceful shutdown mechanisms out of the box (and haven't been worth the time to implement considering our smaller windows user base) so we run into this regularly.

FWIW, we've been working around this just fine by checking the error code == 2 and error message matches on Windows, and keeping an integration test to make sure we catch when the error changes whenever we upgrade. Of course, that was a band aid fix and we never verified the error is ONLY caused by the server socket closing or anything more, but it's acceptable in our case to retry anyway for our idempotent methods.

**Comment by drfloob** [comment]
I see. I didn't catch the top-level error code difference. I'll reopen this and chat with the team about what the right behavior is here, if there is a consistent story we should settle on.

**Comment by drfloob** [comment]
@Hamza-Q https://github.com/grpc/grpc/pull/33502 should fix the issue. Your reproduction case worked just fine, I confirmed by adding an `abort();` to the C++ greeter server and observing status codes in the C++ greeter client. Windows now shows error code 14 (`GRPC_STATUS_UNAVAILABLE`) with the message "Connection reset". I'm not equipped to test Python on Windows at the moment, but I suspect it'll work the same.

**Comment by Hamza-Q** [comment]
Awesome, thanks drfloob!
