### ISSUE TITLE
grpc_ares_ev_driver_windows: Overlapped I/O operation is in progress

### ISSUE THREAD

**Issue by Arrefelt** [grpc/grpc#24232]
### What version of gRPC and what language are you using?
Updated today to dotnet 2.32 in hope to fix this issue, however had the same experience on 2.27.

### What operating system (Linux, Windows,...) and version?
Windows Server 2016  (Azure App Service)

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET 4.7.1

### What did you do?
I'm only using gRPC client requests in my ASP.NET project, and from there I'm fetching info from an external gRPC API. The current implementation has been working flawlessly for a couple of months, however since some time back all of these gRPC requests are insanely slow.

### What did you expect to see?
Normal response times < 1 second. The external API works just as before which can be verified by that the same requests are still fast when running the same code locally on my machine.

### What did you see instead?
Response times are now around 90 seconds for the very same requests that works normally when running locally on my windows machine. Something on the Azure App Service environment are slowing these requests down greatly, it seems to be the DNS resolution.

From what I can tell from the logs, it pretty quickly shows this:

```
T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_ev_driver_windows.cc:185: (c-ares resolver) fd:|c-ares socket: 4588| RegisterForOnReadableLocked WSARecvFrom error code:|997| msg:|Overlapped I/O operation is in progress
```

Then it takes about 90 seconds before it calls it a day with:

```
T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_ev_driver_windows.cc:604: (c-ares resolver) fd:|c-ares socket: 4588| OnIocpReadableInner winsocket_->read_info.wsa_error code:|995| msg:|{""created"":""@1600945877.332000000"",""description"":""OS Error"",""file"":""T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_ev_driver_windows.cc"",""file_line"":599,""os_error"":""The I/O operation has been aborted because of either a thread exit or an application request.\r\n"",""syscall"":""OnIocpReadableInner"",""wsa_error"":995}|",
```

After that, handshake is performed, request is made and a response is received correctly.

### Anything else we should know about your project / environment?
I also have another .NET Core project in the same hosting environment on Azure, and everything is still running correctly there with grpc-dotnet.

**Comment by Arrefelt** [comment]
I tried using GRPC_DNS_RESOLVER=native however the results are pretty much the same so I'm guessing it has nothing to do with ares itself.  But I cannot figure out as to why it cannot resolve dns in my azure environment

**Comment by jtattermusch** [comment]
@apolcyn  can you take a look?

**Comment by apolcyn** [comment]
A packet trace on the DNS server port may help to give some insight here.

For example, if you could run the client and sniff all UDP and TCP traffic with source and/or destination port 53, then we could see the which DNS queries are being sent and when, and which DNS responses are being received and when. That may give insight to e.g. possible unavailability of the nearby DNS server.

Also, it looks like you're already ran the code under verbose grpc trace logs. Can you please share those logs here?

The minimal grpc logs to get could be captured with these env vars:

`GRPC_VERBOSITY=DEBUG`
`GRPC_TRACE=cares_resolver,cares_address_sorting` (this will give verbose logs assuming you're using the c-ares resolver).

Another way to go about debugging this could be to remove gRPC from the equation and test DNS resolution in isolation. For example, something along the lines of the following python command could be ran from a shell:

```
python -c "import socket; socket.getaddrinfo('my.problematic.server', 80, 0, 0, socket.IPPROTO_TCP)"
```

That would test the system resolver (the same resolver as what's used when gRPC is ran with `GRPC_DNS_RESOLVER=native`)

If that reproduces the DNS resolution issue, a packet sniffer ran in the background could give some insight.

**Comment by Arrefelt** [comment]
Thank you for looking into this!

I was actually not able to overcome this issue at all and due to features needing to be published asap I chose to migrate the API to .NET Core where I knew it would work. It now works fine with grpc-dotnet in my case since there is no dependency to grpc_ares_ev_driver_windows.

Because of this I'm also no longer able to reproduce this error and it can be closed if you wish so.
