### ISSUE TITLE
grpc,1.27.3 sendmessage ,crash

### ISSUE THREAD

**Issue by zhangkuo1110** [grpc/grpc#24231]
grpc 1.27.3, client

crash, I donnot know the reason!!! help

# addr2line -f -e ./gent -a 0xc9b256 
0x0000000000c9b256 
_ZNK6google8protobuf10Reflection30UnsafeArenaSetAllocatedMessageEPNS0_7MessageES3_PKNS0
_15FieldDescriptorE 
protobuf/src/google/protobuf/generated_message_reflection.cc:1501 
(discriminator 6) 

# addr2line -f -e ./agent -a 0xc9ae74 
0x0000000000c9ae74 
_ZNK6google8protobuf10Reflection10GetMessageERKNS0_7MessageEPKNS0_15FieldDescriptorEPNS
0_14MessageFactoryE 
google/protobuf/generated_message_reflection.cc:1452 

# addr2line -f -e ./agent -a 0x50daaf 
0x000000000050daaf 
_ZNSt8_Rb_treeIiiSt9_IdentityIiESt4lessIiESaIiEE8_M_eraseEPSt13_Rb_tree_nodeIiE 
/usr/local/include/c++/4.9.4/bits/stl_tree.h:1239 

# addr2line -f -e ./agent -a 0xcfa8f0 
0x0000000000cfa8f0 
_ZN6google8protobuf13RepeatedFieldIlE3SetEiRKl

**Comment by zhangkuo1110** [comment]
It is easy to trigger a crash when the client frequently sends data to the server.
The above is the captured stack information.

**Comment by yashykt** [comment]
The stack traces indicate protobuf. I would guess that there is an error in the usage of protobuf in the client code. I would have been able to provide more help if I could read the code, but based on the stack traces that's my best guess. 

As a side-note, for general help, please redirect questions towards wider communities like stack-overflow or https://groups.google.com/g/grpc-io
