### ISSUE TITLE
Server does not use graceful GOAWAY on graceful shutdown

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#24237]
The server seems to have a concept for graceful shutdown, where it sends a GOAWAY and lets RPCs complete. However, it doesn't do the double-GOAWAY suggested by [MAX_CONNECTION_AGE gRFC](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md#proposal) and the [HTTP/2 spec](https://httpwg.org/specs/rfc7540.html#GOAWAY):

> A server that is attempting to gracefully shut down a connection SHOULD send an initial GOAWAY frame with the last stream identifier set to 2<sup>31</sup>-1 and a NO_ERROR code. This signals to the client that a shutdown is imminent and that initiating further requests is prohibited. After allowing time for any in-flight stream creation (at least one round-trip time), the server can send another GOAWAY frame with an updated last stream identifier. This ensures that a connection can be cleanly shut down without losing requests.

I'd suggest an implementation that sends a PING immediately after the first GOAWAY and sends the second GOAWAY when the ACK arrives. A timer can be set to 10 seconds and the second GOAWAY can be sent when the timer expires if the ACK has failed to arrive. This allows rapid, zero-configuration, race-less shutdowns.

The current server behavior is causing unnecessary RPC failures as it fails RPCs already sent by the client. This has been seen internally when a client swapped the server from GFE to C core, but also in https://github.com/grpc/grpc-java/issues/7409 . I believe we haven't noticed this before because many clients are automatically retrying these failed RPCs, but a bug in grpc-java (https://github.com/grpc/grpc-java/issues/7357) prevented them from showing up as UNAVAILABLE. gRPC clients have also have local races relating to GOAWAY and so it can been hard to determine whether seen instances are client-side races. The internal case was also easier to pin-point because we could do A/B comparison between GFE and C core.

MAX_CONNECTION_AGE is probably more important than normal server shutdown, as it occurs more frequently. But normal server shutdown should also avoid this race. [Go](https://github.com/grpc/grpc-go/blob/8630cac324bf02ea0edfba758c2b2f3344af7bf7/internal/transport/http2_server.go#L1191), [Java](https://github.com/grpc/grpc-java/blob/c29ad76daea0d17637fefcab4dbfd9ef8cb84ebc/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L939), and GFE have had this behavior for years.

CC @veblush

**Comment by ejona86** [comment]
For reference, C's handling of MAX_CONNECTION_AGE:
https://github.com/grpc/grpc/blob/25518e5b084f375b4f834546dd10a23905c90323/src/core/ext/filters/max_age/max_age_filter.cc#L361-L363

And the non-MAX_INT GOAWAY it triggers:
https://github.com/grpc/grpc/blob/e834d0b34b43745b0839b6205e04cfb1a5924c3a/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L1735-L1737

**Comment by yashykt** [comment]
Yes, we already have an internal bug for this b/135458602. It just hasn't reached the top of my priority queue yet. I'll see if I can get it done next quarter.

**Comment by ejona86** [comment]
@yashykt, that looks like a client-side thing whereas this is a server-side thing. If they are the same, then go ahead and cross-link the internal one to reference this one. I would have done so, but a glance made it seem they were different.

**Comment by yashykt** [comment]
You are right. It started off as a client-only thing, but as the discussion progressed, it mentions all the things we want to do including the server-side double GOAWAY shutdown as a wanted feature.
