### ISSUE TITLE
gRPC C# in Unity Client to Remote Server over TLS never connects

### ISSUE THREAD

**Issue by nathantfrank** [grpc/grpc#24236]
### What version of gRPC and what language are you using?
The server is running go 1.14 with grpc 1.32, TLS is setup with Let's Encrypt and certmagic
The client is running Unity 2018.4 with the unity grpc plugins package found [here](https://packages.grpc.io/archive/2019/11/6950e15882f28e43685e948a7e5227bfcef398cd-6d642d6c-a6fc-4897-a612-62b0a3c9026b/index.xml) 

### What operating system (Linux, Windows,...) and version?
Golang on linux
Unity C# on Windows & Mac

### What did you do?
I first created a simple go program to test if I could create a client connection to the server.

```
func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	opts := []grpc.DialOption{grpc.WithBlock()}
	b, _ := ioutil.ReadFile("../../lets_encrypt_chain.crt")
	cp := x509.NewCertPool()
	if !cp.AppendCertsFromPEM(b) {
	 	log.Fatal("credentials: failed to append certificates")
	}
	conf := &tls.Config{
		InsecureSkipVerify: false,
		RootCAs:            cp,
	}
	opts = append(opts,
		grpc.WithTransportCredentials(credentials.NewTLS(conf)),
	)
	_, err := grpc.DialContext(
		ctx,
		"my.address.com:443",
		opts...,
	)
	if err != nil {
		log.Fatal("Unable to Dial Server : " + err.Error())
	} else {
		log.Print("Connected to GRPC Server")
	}
}
```

Which worked exactly as I expected! It even worked with an empty tls.config!

My next step was to recreate this in grpc.core in a Unity Project.
I created a scriptable object to test connecting from Unity to the Go Server, with the following code which would be ran when I clicked on an editor button.

```
public void Connect()
    {
        var certCA = File.ReadAllText(Path.Combine(Application.streamingAssetsPath, "lets_encrypt_chain.crt"));
        var creds = new SslCredentials(certCA);
        var channelInstance = new Channel("my.address.com", 443, creds);
        var client = new myService.MyThingsServiceClient(channelInstance);
        var response = client.ListMyThings(new ListMyThingsRequest());
        Debug.Log(response);
    }
```

The above doesn't work, which leads me to believe there is something wrong either with the library or with my code/environment. I am stuck I have tried many variations on the above code to get it to work including:

- new SslCredentials(); // not including the rootCA cert
- new SslCredentials(certCA, keyPair); // not including the rootCA cert
- Using ChannelCredentials(creds, callCredetials)
- Trying to use Insecure connection

### What did you expect to see?

A response from my server.

### What did you see instead?

```
RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].UnaryCall (TRequest msg) (at T:/src/github/grpc/src/csharp/Grpc.Core/Internal/AsyncCall.cs:141)
Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.CallInvocationDetails`2[TRequest,TResponse] call, TRequest req) (at T:/src/github/grpc/src/csharp/Grpc.Core/Calls.cs:45)
Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) (at T:/src/github/grpc/src/csharp/Grpc.Core/DefaultCallInvoker.cs:47)
Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse] (TRequest req, Grpc.Core.Interceptors.ClientInterceptorContext`2[TRequest,TResponse] ctx) (at T:/src/github/grpc/src/csharp/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:51)
Grpc.Core.ClientBase+ClientBaseConfiguration+ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse] (TRequest request, Grpc.Core.Interceptors.ClientInterceptorContext`2[TRequest,TResponse] context, Grpc.Core.Interceptors.Interceptor+BlockingUnaryCallContinuation`2[TRequest,TResponse] continuation) (at T:/src/github/grpc/src/csharp/Grpc.Core.Api/ClientBase.cs:174)
Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) (at T:/src/github/grpc/src/csharp/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:48)
Recolude.Services.V1.RecordingService+RecordingServiceClient.ListRecordings (Recolude.Services.V1.ListRecordingsRequest request, Grpc.Core.CallOptions options) (at Assets/Recording-serviceGrpc.cs:99)
Recolude.Services.V1.RecordingService+RecordingServiceClient.ListRecordings (Recolude.Services.V1.ListRecordingsRequest request, Grpc.Core.Metadata headers, System.Nullable`1[T] deadline, System.Threading.CancellationToken cancellationToken) (at Assets/Recording-serviceGrpc.cs:95)
GrpcClient.Connect () (at Assets/grpcClient.cs:37)
GrpcClientEditor.OnInspectorGUI () (at Assets/grpcClientEditor.cs:20)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1647)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
```

I know a golang client to my server works. How can I get this Grpc.Core Unity Project to connect to my server over TLS? I am nearly convinced this is a bug in the library.

**Comment by nathantfrank** [comment]
@rib I noticed in your issue #21633 that it looks like you have TLS working with your setup. Would you mind looking over my issue?

**Comment by rib** [comment]
I don't know if it will help or not but I made this bare minimum Unity project for reproducing my bug here: https://github.com/rib/grpc-unity-deadlock-reproduction. Maybe it will help you to see how I set up TLS in there.

Personally I would be very weary about trying to depend on this project's Unity support, I'm not sure that it's maintained. I wasn't able to get any release of gRPC working reliably across any version of Unity and never head from a maintainer.

Good luck!

**Comment by vovasazonov** [comment]
@nathantfrank I have same issue. Did you solve the issue?

**Comment by SAM-tak** [comment]
Or, if Unity implements SocketsHttpHandler, the problem can be solved by using Grpc.Net.Client instead of Grpc.Core.
However, Unity developers don't seem to understand that the lack of implementation of SocketsHttpHandler hinders the practical use of gRPC in Unity.
It is still kept at a low priority. This has not been resolved in Unity 2022 beta.

**Comment by SAM-tak** [comment]
Grpc.Core will be deprecated, but seeing the lack of interest in this issue by Unity technology developers, I don't think anyone will use gRPC in Unity commercial products unless Grpc.Core is given the ability to handle TSL satisfactorily.

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
