### ISSUE TITLE
ld: library not found for -lssl

### ISSUE THREAD

**Issue by adamjstewart** [grpc/grpc#24248]
### What version of gRPC and what language are you using?

gRPC 1.32.0, Python

### What operating system (Linux, Windows,...) and version?

macOS 10.15.6

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.8.5, Apple Clang 12.0.0

### What did you do?

I'm trying to install `py-grpcio` using the Spack package manager. I added the latest version, but it fails to compile.

### What did you expect to see?

Successful compilation.

### What did you see instead?

The build fails to pick up my SSL libraries:
```
ld: library not found for -lssl
```

### Anything else we should know about your project / environment?

Spack uses compiler wrappers to automatically inject the correct `-L/path/to/lib` and `-I/path/to/include` flags to build a project. If you look at the build logs below, it looks like `py-grpcio` is correctly using the compiler wrappers for the first half of the build (`/Users/Adam/spack/lib/spack/env/clang/clang++`) but then starts using the system compiler (`/usr/bin/clang++`) and crashes because it can't find the SSL library. Is there are way to tell it to always use Spack's compiler wrappers?

* [build log](https://github.com/grpc/grpc/files/5287687/spack-build-out.txt)
* [build env](https://github.com/grpc/grpc/files/5287688/spack-build-env.txt)

I realize that you don't officially support Spack, but I'm a Spack developer, so if this is a bug on Spack's side of things I can handle it.

**Comment by yashykt** [comment]
@adamjstewart Please also feel free to jump in and dig through.

**Comment by lidizheng** [comment]
@adamjstewart  From the log, it looks like that Cython picked the correct `clang++` but `setuptools` picked the system compiler. There are several ways to control which compiler to use in `setuptools`, like [distutils.cfg](https://setuptools.readthedocs.io/en/latest/deprecated/easy_install.html?highlight=--compiler#id27), or `--compiler`.

**Comment by adamjstewart** [comment]
Thanks for the suggestion @lidizheng. My understanding for `--compiler` and `distutils.cfg` is that you can only control the type of compiler, not the exact executable that gets used.

Let me try manually injecting all of the compiler flags so that even if it uses the wrong compiler it will still work.

**Comment by lidizheng** [comment]
In your env, `/usr/bin/clang++` is set as `SPACK_CXX`. Could this be the reason?

**Comment by adamjstewart** [comment]
No, that shouldn't be the issue. The way Spack works is that it sets `CXX` to the compiler wrappers, and then in the compiler wrappers, it calls `SPACK_CXX` (the actual compiler) with additional flags like `-L`, `-I`, and `-Wl,-rpath,`.

I think the bigger issue for me is that parts of the build use `CXX` while other parts of the build use the compiler reported by distutils.

**Comment by adamjstewart** [comment]
Okay, manually setting `LIBRARY_PATH` and `CPATH` gets me past the original issue. Now the build crashes with:
```
ld: illegal text reloc in '_ChaCha20_ctr32' to '_OPENSSL_ia32cap_P' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-grpcio-1.32.0-567lpb7qzqrwh4rpdzu74roahrdhl47f/spack-src/src/python/grpcio/commands.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exit_code is not 0:
```
Have you seen anything like this before? The latter warning msg should be easy to fix, but I don't know enough C to fix the former error msg.

**Comment by lidizheng** [comment]
There are many build options you could try at: https://github.com/grpc/grpc/blob/master/setup.py#L121.

E.g., you could set `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true` to build gRPC Python with default OpenSSL in system instead of BoringSSL.

Thanks for suggesting fix for `commands.py`. I put up an PR at https://github.com/grpc/grpc/pull/24271.

**Comment by adamjstewart** [comment]
I'm already using `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true`

**Comment by tswast** [comment]
We're encountering the same `ld: illegal text reloc in '_ChaCha20_ctr32' to '_OPENSSL_ia32cap_P' for architecture x86_64` error while trying to build the conda package.

Logs:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=227579&view=logs&jobId=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445

It also happens when I test this conda build locally.

**Comment by tswast** [comment]
In the conda package, we need to use Open SSL and not BoringSSL, so our fix was to add `export GRPC_BUILD_WITH_BORING_SSL_ASM=""` to the build.sh script.

https://github.com/conda-forge/grpcio-feedstock/pull/29/files#diff-d7075654874cb08007a21aaab3ecd4b3453a9087e7505d034d548b8938b599bcR6

**Comment by adamjstewart** [comment]
Thanks @tswast, your suggestion worked perfectly!

I believe the underlying bug here was fixed by https://github.com/grpc/grpc/pull/24449, so I'm going to close this issue.

We're also updating our Spack package in https://github.com/spack/spack/pull/19710
