### ISSUE TITLE
FLAKE: //test/core/transport/chttp2:too_many_pings_test@poller=epoll1[k8-fastbuild] TooManyPings.BdpPingNotSentWithoutReceiveSideActivity

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#24243]
https://source.cloud.google.com/results/invocations/cc697b66-a4ae-46ec-9917-65a93d9cb646/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fchttp2:too_many_pings_test@poller%3Depoll1/tests

```
test/core/transport/chttp2/too_many_pings_test.cc:728
Expected: (grpc_channel_check_connectivity_state(channel, 0)) != (GRPC_CHANNEL_READY), actual: 2 vs 2
```

**Comment by yashykt** [comment]
Looks like the test is fragile. I'll try to fix it.
