### ISSUE TITLE
Random error writing response for server call

### ISSUE THREAD

**Issue by ppageo** [grpc/grpc#24250]
### What version of gRPC and what language are you using?
1.31.1

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019

### What did you do?
Sometimes, when in the server I'm writing a very large response to a call, the following assert is raised:

GPR_CODEGEN_ASSERT(byte_count_ < total_size_);

This is the first line of the Next method in the proto_buffer_writer.h file. The error does not happen always, only sometimes. When it happens the amount of data to return is of several MBs, and always byte_count_ is equal to total_size_.

### What did you expect to see?

Not an error

### What did you see instead?

An asserting that causes an abort in the GRPC server.

**Comment by yashykt** [comment]
Looks like there is something buggy happening here. Please provide a way to reproduce this error.

**Comment by SaberJJ** [comment]
Is this issue has solved in version upper than 1.3.2 ?

**Comment by ppageo** [comment]
Hello,
the cause of the error was that an uninitialized boolean variable was assigned to a boolean field of a proto structure. In debug mode, boolean variables are initialized to 0, and the error was not happening. However, in release mode, boolean variables are not initialized and sometimes the server was crashing due to this. After initializing properly the boolean variable, the problem is no longer happening.
Thanks and regards.

**Comment by SaberJJ** [comment]
> Hello,
> the cause of the error was that an uninitialized boolean variable was assigned to a boolean field of a proto structure. In debug mode, boolean variables are initialized to 0, and the error was not happening. However, in release mode, boolean variables are not initialized and sometimes the server was crashing due to this. After initializing properly the boolean variable, the problem is no longer happening.
> Thanks and regards.

Thank you, it helps me so much.
