### ISSUE TITLE
grpcioo failing on TLS with ED25519 algorithm

### ISSUE THREAD

**Issue by Sult** [grpc/grpc#24252]
### What version of gRPC and what language are you using?
grpcio 1.32.0

### What operating system (Linux, Windows,...) and version?
Mac OS Catalina, but also tested on Debian resulting in the same issue

### What runtime / compiler are you using (e.g. python version or version of gcc)
grpcio 1.32.0

### What did you do?
I wrote a simple server that should do a TLS handshake with ED25519 certificates. However, I get the following error:
`E0923 15:24:55.786846000 123145480564736 ssl_transport_security.cc:1439] Handshake failed with fatal error SSL_ERROR_SSL: error:100000fd:SSL routines:OPENSSL_internal:NO_COMMON_SIGNATURE_ALGORITHMS.`

When i try to explicitly set the GRPC_SSL_CIPHER_SUITES to TLS_CHACHA20_POLY1305_SHA256 i get 
```
E0928 08:40:04.195376000 4625149376 ssl_transport_security.cc:811]     Invalid cipher list: TLS_CHACHA20_POLY1305_SHA256.
E0928 08:40:04.195416000 4625149376 ssl_security_connector.cc:263]     Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0928 08:40:04.195437000 4625149376 server_secure_chttp2.cc:81]        {"created":"@1601275204.195428000","description":"Unable to create secure server with credentials of type Ssl","file":"src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc","file_line":63}
```

According to what i could find, it should be supported by default: https://github.com/grpc/grpc/blob/ff8ceb700e8a53ed4087edc006830da372b1199a/src/core/lib/security/security_connector/ssl_utils.cc#L69

When I chance the certificate algorithm to RSA, all works as expected

My server code:
```
def run_server(args):
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    service_pb2_grpc.add_EchoServicer_to_server(Echo(), server)

    ca_cert = open(args.ca_cert, 'rb').read()
    dp_cert = open(args.dp_cert, 'rb').read()
    dp_key = open(args.dp_key, 'rb').read()

    credentials = grpc.ssl_server_credentials(
        [(dp_key, dp_cert), ],
        root_certificates=ca_cert,
        require_client_auth=True
    )

    server.add_secure_port('[::]:' + str(args.port), credentials)

    print('Starting server. Listening on port {}...'.format(args.port))
    server.start()
```

I have all my code, including scripts on creating the certificates etc packed in a tar to reproduce it. However I dont know how someone would like to receive it. So if you want it, let me know how I can send it to you.

### What did you expect to see?
I would expect this to work with ED25519 just is it does with RSA

### Anything else we should know about your project / environment?
I am using python 3.8.2. I also tried building my own grpcio from source, but that results in the same problem

**Comment by jorrizza** [comment]
Same problem here. Tried with both Ruby and Python bindings. Set up a server using Go and an ed25519 certificate. Connecting to that server with both Go and OpenSSL s_client works perfectly. Using the same client certificate with this repository however, causes the handshake to fail.

The server has the following log output when connecting to it from either the Python or Ruby client:

    WARNING: 2020/09/29 14:50:22 [core] grpc: Server.Serve failed to complete security handshake from "[::1]:46378": tls: peer doesn't support any of the certificate's signature algorithms

Both clients have the same failure:

    E0929 14:50:22.511022940  110942 ssl_transport_security.cc:1439] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.

**Comment by lidizheng** [comment]
@jiangtaoli2016 PTAL. Could this be an issue with BoringSSL?

@Sult Can you please try if the issue is reproducible with `v1.31.x`? In `v1.32.0`, we enabled ASM optimization for BoringSSL, which could be the culprit.

**Comment by jiangtaoli2016** [comment]
It is not clear if it is BoringSSL issue. I would be surprise if it is a BoringSSL issue.

**Comment by jorrizza** [comment]
Tried with package `1.31.0` from PyPI. That version doesn't even support TLSv1.3, apparently. Allowing TLSv1.2 on the server side results in the same error as above.

I have also built the latest master (b9fe77f2349e1a11835c411f578b37b425e5a544) without the asm optimization and made sure to update all the submodules. This version also results in the same handshake error.

This is strange, as BoringSSL implemented ed25519 before OpenSSL did, right?

**Comment by lidizheng** [comment]
Thanks for trying out previous version and compiling from HEAD.

@jiangtaoli2016 Can you take a look again? I found ed25519 implemented in BoringSSL, but seems not enabled for gRPC. Do you have more context?

**Comment by jiangtaoli2016** [comment]
From SSL transport security code, BoringSSL and OpenSSL have no difference.
If there is some feature that only enabled for OpenSSL but not BoringSSL in gRPC, @nicolasnoble may know, since Nicolas wrote the build system.

**Comment by delfick** [comment]
I have the same problem as above, when I try to connect to my Go grpc server, python gives me a 

```
E1223 09:57:03.587405000 123145559670784 ssl_transport_security.cc:818] Invalid cipher list: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.
E1223 09:57:03.587562000 123145559670784 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1223 09:57:03.587568000 123145559670784 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'my-app.local.co:10181'
E1223 09:57:03.587574000 123145559670784 secure_channel_create.cc:49]  Failed to create channel args during subchannel creation.

code=StatusCode.UNAVAILABLE     details=Empty update
```

If everything is the same but I use python3.8 instead then it works fine

**Comment by niya3** [comment]
### my error logs

server-side ([`GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`](https://github.com/grpc/grpc-go/blob/02cd07d9bb5609fe76f8bb8d948037e79a8b29c7/README.md#how-to-turn-on-logging)):

```
tls: peer doesn't support any of the certificate's signature algorithms
```

client-side ([`GRPC_VERBOSITY=DEBUG GRPC_TRACE=all`](https://github.com/grpc/grpc/blob/0123d5460be898cf16adf5e1b0f4789291d137ae/doc/environment_variables.md)):

```
E0419 ssl_transport_security.cc:1237] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
D0419 security_handshaker.cc:176] Security handshake failed: {"created":"@timestamp","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0419 handshaker.cc:131]          handshake_manager 0x7fb3b000ced0: error={"created":"@timestamp","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"} shutdown=0 index=2, args={endpoint=(nil), args=(nil) {size=0: (null)}, read_buffer=(nil) (length=0), exit_early=0}
I0419 handshaker.cc:164]          handshake_manager 0x7fb3b000ced0: handshaking complete -- scheduling on_handshake_done with error={"created":"@timestamp","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0419 timer_generic.cc:467]       TIMER 0x7fb3b000cf88: CANCEL pending=true
I0419 resource_quota.cc:948]      RQ anonymous_pool_7fb3b000c860 ipv4:ip:port: free 8192; free_pool -> 8192
I0419 subchannel.cc:1034]         Connect failed: {"created":"@timestamp","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

### my solution

Building grpcio from sources using system-wide openssl worked for me on debian 10 + python 3.7 

```bash
apt install -qy build-essential libssl-dev
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
pip install -U grpcio==1.37 --force --no-binary=grpcio
```

PS I don't use pypy, but [`None/tmp` compilation errors](https://github.com/grpc/grpc/issues/25112) forced me to use last available grpcio version

**Comment by zifter** [comment]
@mumbleskates 
I have [asked about that behavior](https://bugs.chromium.org/p/boringssl/issues/detail?id=530) in boringssl project and received answer:
```
This is working as intended. Ed25519 isn't used in the Web PKI yet and not allowed by most root programs, so we don't enable it by default. While it is a nicer signature scheme than ECDSA, PKIs move slowly and we need to start thinking about post-quantum schemes at this point. Applications in other scenarios that do wish to support Ed25519 can use the existing APIs to configure allowed signature schemes.
```
So, the best choice, as for me, it's try to use open ssl library (as mentioned above) or **change crypto algo of you proxy**.

**Comment by gnossen** [comment]
@zifter Thanks for following up. For anyone running into this problem, you can compile against your system openssl by setting `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true` and building from source.
