### ISSUE TITLE
grpc python upload files through the reuse channel sometimes service interrupt with no abnormal information

### ISSUE THREAD

**Issue by kep-w** [grpc/grpc#24260]
**What version of gRPC and what language are you using?**
grpcio 1.30.0
python 2.7.18
**What operating system (Linux, Windows,...) and version?**
Linux run with Docker 
**What runtime / compiler are you using (e.g. python version or version of gcc)**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
Python2.7.18
**What did you do?**

I write a rpc service for my file systerm. it used for upload and download different kinds of files. And client and server are both deployed in docker, the client is start by gunicorn.
When I try to upload large files through the same channel, sometimes docker restarts for no reason, and Python cannot capture the exception information. If use a new channel every time, the client run well. 
The strange thing is that the interface for downloading files runs normally regardless of whether the same channel is used or not.
At first I suspected that it was caused by the memory leak problem, but the memory analysis found that the running memory did not increase sharply, and maintained at a normal magnitude. 
the channel should be reuse or not? and what is the problem cause the client exit with no reason?
The file size about 2M 
my client code like this:
```
import grpc
from .proto.files_pb2_grpc import FileWorkerStub


class Handler:
    def __init__(self, url):
        self.req_url = url
        self.channel = grpc.insecure_channel(url)
        self.stub = FileWorkerStub(self.channel)

    def c_file(self, file=None, timeout=3, logger=logging):
        response = self.stub.cFile(files_pb2.c_request(file_data=file), timeout=timeout)
        return response

    def d_file(self, name, timeout=3, logger=logging):
        response = self.stub.dFile(files_pb2.d_request(file_name=name), timeout=timeout)
        return response

    def __del__(self):
        if self.channel:
            self.channel.close()

if __name__=="main":
    lst = ["f.jpg", "g.jpg", "d.png", "cli.apk"]
    f = Handler("localhost:8999")
    for i in lst:
        with open(i, "rb") as f:
            data = f.read()
            f.c_file(data)
```
**What did you expect to see?**
We cannot migrate the service to Python3 for now！
I would expect to reuse the channel...

**Comment by lidizheng** [comment]
@kep-w Can you try to print out the trace log for the gRPC client in Docker? The trace logging can be enabled with setting 2 environment variables `GRPC_VERBOSITY=debug` and `GRPC_TRACE=all` (see [doc](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)).

Channels should be reused. The client exit must triggered by some error. Two most possible cases (memory leak, file too big) are ruled out by your description. If there is no error and return code is 0, your application might just exited normally.

**Comment by kep-w** [comment]
> @kep-w Can you try to print out the trace log for the gRPC client in Docker? The trace logging can be enabled with setting 2 environment variables `GRPC_VERBOSITY=debug` and `GRPC_TRACE=all` (see [doc](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)).
> 
> Channels should be reused. The client exit must triggered by some error. Two most possible cases (memory leak, file too big) are ruled out by your description. If there is no error and return code is 0, your application might just exited normally.

Thanks for your reply. 
I configed the environment variables GRPC_VERBOSITY=debug and GRPC_TRACE=all, and the log print in std.out. 
But my service was deployed in docker, the information was cleared when the service interupt. 
So how to output logs to a file? In this case, I can persist the file by mounting.
I tried adding the configuration information to the initialized channel as follows, but it didn't work.
`self.channel = grpc.insecure_channel(url, options=[
            ('grpc.max_send_message_length', -1),
            ('grpc.max_receive_message_length', -1),
            ('grpc.grpc_verbosity', 'debug'),
            ('grpc.grpc_trace', 'all, -timer_check'),
            ('grpc.log_filename', '/app/log/grpc/grpc.log'),
        ])`

**Comment by kep-w** [comment]
> GRPC_TRACE=all

Hi, I try to get systerm logs and got this:
kernel: grpc_global_tim[11971]: segfault at 328c220 ip 00007f87be25ce09 sp 00007f87bd1b2c10 error 4 in cygrpc.so[7f87be012000+577000]
abrt-hook-ccpp: Process 1 (python2.7) of user 0 killed by SIGSEGV - ignoring (repeated crash)
abrt-hook-ccpp: Saved core dump of pid 11882 to core.11882 at /app/grpc_test (62062592 bytes)
It is worth noting that this error occurs when the service starts with gunicorn, but not happened when starts with python directly.
Please help me to locate the error. 
Thanks

**Comment by lidizheng** [comment]
You can examine the core dump, or use gdb to locate the error.

If it is a segfault, then it might be caused because the process is forked during channel creation. To safely use forking, you might need to set an environment variable `GRPC_ENABLE_FORK_SUPPORT=true`.

**Comment by kep-w** [comment]
> If it is a segfault, then it might be caused because the process is forked during channel creation. To safely use forking, you might need to set an environment variable `GRPC_ENABLE_FORK_SUPPORT=true`

hi, I try the environment variable GRPC_ENABLE_FORK_SUPPORT=true, but got a new error:
ValueError: Cannot invoke RPC on closed channel!
