### ISSUE TITLE
need documentation on System.InvalidOperationException: Response stream has already been completed.

### ISSUE THREAD

**Issue by daveyostcom** [grpc/grpc#24261]
I can find no documentation about this error message, beyond just the one sentence, which seems unclearly worded.
This happens on a bidirectional stream at the first write from server to client. By "response stream" I guess it means the reading side of the bidirectional stream. Apparently my code to read from the stream is already and is still running when this happens, but it's not clear why that should matter. Seems more like the message is trying to say that something at a lower layer is failing. More complete documentation would help.
Documentation for each error would be very helpful. Years ago bsd unix finally bit the bullet and documented each of the error codes. That was a great day when that happened.

**Comment by daveyostcom** [comment]
Back in those days of 64k memory and no Internet and no error documentation, all we got was an int for an error message, then we looked it up in the source code if we could. Funny how it takes time to fully realize what we can do with more resources. Nowadays, how about we get a short URL to the full documentation on the error? Or the IDE could look it up from the exception class, when a standard way to do that lookup is available.

**Comment by yashykt** [comment]
Posting the logs or atleast the error message would help

**Comment by daveyostcom** [comment]
> Posting the logs or atleast the error message would help :)
`System.InvalidOperationException: Response stream has already been completed.` (see title :)
My server code was writing before reading. Oops. Because the reading started immediately after the writing and I was lucky, it worked. Until some code reorg must have tweaked the timing. (I fixed it so it starts reading, then awaits the initial writes, then awaits the reading.)

I was thrown by the term `response stream` and by the fact that the reading of the stream hadn't even started and couldn't have ”already completed“.

**Comment by yashykt** [comment]
> System.InvalidOperationException: Response stream has already been completed

My bad, I didn't see that. Assigning it to @jtattermusch for C#. (Also, pull requests are welcome. )

**Comment by jtattermusch** [comment]
Looks like it's coming from here
https://github.com/grpc/grpc/blob/86f93801e5d452cff40d6958d21a8eb211da0654/src/csharp/Grpc.Core/Internal/AsyncCallServer.cs#L197

You would normally see this message if you're trying to send a message (= a streaming response in case of a server-side handler of a bidi streaming call) from a call for which the final response has already been sent. This can happen e.g. when you're trying to send more responses on a call that has e.g. already been cancelled or you've already marked the response stream as half closed (by e.g. throwing an exception in the server side handler or returning from the server side handler).

> By "response stream" I guess it means the reading side of the bidirectional stream.

response stream is the stream of messages (responses) that are sent by the server to the client. The "reading side of the bidirectional stream" is ambiguous depending on whether you're talking from client's or server's perspective. (both client and server do reads and writes in bidi calls).
