### ISSUE TITLE
net5.0 'publish single file' makes LoadUnmanagedLibrary fail with ArgumentNullException

### ISSUE THREAD

**Issue by atlemann** [grpc/grpc#24266]
### What version of gRPC and what language are you using?
NuGet 2.24.0, C#

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet 5.0 rc-1

### What did you do?
1) Create some app that tries to create a Grpc Channel
2) dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
3) run the executable

### What did you expect to see?
Application to run without problems

### What did you see instead?

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by procodr** [comment]
Same here, the **no single file** publishing output is OK:
`dotnet publish -r win-x64 --self-contained true`
But when running **single file** published output that produced with this command:
`dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true`
the error will occure.

Note that publishing with enabling **ReadyToRun compilation** and **Trim unused assemblies** is OK too.

**Comment by procodr** [comment]
Same bug in **dotnet 5.0 rc-2**

**Comment by gitfool** [comment]
@angwangiot and I are also seeing this. See my comments with some background info in https://github.com/grpc/grpc/issues/24153#issuecomment-711098455.

**Comment by jtattermusch** [comment]
Looks like there would be two cases to handle:

1. the default case where native libraries are published alongside the app (see https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#build-system-interface which says 
*All other files, including platform-specific native binaries and symbol files, are left alongside the app by default. *).
In this case it seems to be enough to fix the code that determines app assembly's location. (as suggested here: https://github.com/grpc/grpc/issues/24153#issuecomment-711098455). 

https://github.com/grpc/grpc/blob/b4628c6f9df96fbf319fcda91614a98397f3bd25/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L87

2. cases where `IncludeNativeLibrariesForSelfExtract` is enabled (which seems to be more tricky).

Would anyone be interested in drafting a PR with a fix?

**Comment by Macaddict42** [comment]
The problem is that Assembly.Location is no longer usable in the case of single file publish. If you build using it with single file enabled, you'll get a compiler warning that recommends you use AppContext.BaseDirectory. I believe that is the only change that needs to be made once this is updated to target .Net 5.

**Comment by jtattermusch** [comment]
The fix is here: https://github.com/grpc/grpc/pull/24744

**Comment by noamyogev84** [comment]
Can we get any estimate on what version this is expected to be included?

**Comment by jtattermusch** [comment]
@noamyogev84  it turns out https://github.com/grpc/grpc/pull/24744 doesn't fix the single file publish fully -> please follow the PR for updates on a fix.
