### ISSUE TITLE
[Flake] macOS grpc_basictests_python

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#24290]
Recently, Homebrew frequently fails to fetch a GitHub repo which is essential to its package list udpate: `fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining`.

The update failure will result in downloading out-of-date pacakges, and lead to error like `Error: unknown or unsupported macOS version: :lion`. Also, Homebrew won't be able to install newer `coreutils` that includes `md5sum`.

It's unclear yet what is the culprit. It could be a Kokoro network issue, GitHub throttling, or a bug in Homebrew.

CC @veblush 

Here is a short log section for this issue:

```
$ brew update-reset
...
==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Reset branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
Your branch is up to date with 'origin/master'.

++ brew upgrade coreutils
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz

#################                                                         24.0%
#############################################                             63.7%
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
Updating Homebrew...
Error: Failed to import: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/amqp-cpp.rb
amqp-cpp: "cxx11" is not a recognized standard
Error: Failed to import: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-arrow.rb
apache-arrow: "cxx11" is not a recognized standard
Error: unknown or unsupported macOS version: :lion
...
```

https://source.cloud.google.com/results/invocations/5a142e21-1685-4d8f-9440-b98e903b815c/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_python/log

**Comment by veblush** [comment]
Thanks Lidi to take a look at this strange problem. All of sudden, `grpc_basictests_python` on the master started passing from 14:17 Sep 30. Maybe some other external component made a recent change?

**Comment by lidizheng** [comment]
There were two bugs caused macOS Python tests to fail, one is fixed in https://github.com/grpc/grpc/pull/24267, the other one is this network issue.

Another failed build after https://github.com/grpc/grpc/pull/24267 merged:
https://source.cloud.google.com/results/invocations/c6e8cac8-01e4-4de9-885b-1b870a1abd1a/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_basictests_python/log

I guess we can see how flaky it is, then file a bug to Kokoro team.
