### ISSUE TITLE
PHP Distribtest is broken

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#24306]
Distribtest master dashboard: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests

Run that failed: https://fusion.corp.google.com/runanalysis/info/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests/KOKORO/9c73d46c-0844-4a4f-af0c-0b689839b456/1601610249616/build%20%2313358/Targets

Log: https://source.cloud.google.com/results/invocations/9c73d46c-0844-4a4f-af0c-0b689839b456/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests/log

```
2020-10-01 21:08:13,272 ++ dirname tools/run_tests/dockerize/build_and_run_docker.sh
+ cd tools/run_tests/dockerize/../../..
++ pwd
+ git_root=/tmpfs/src/github/grpc
+ cd -
/tmpfs/src/github/grpc
++ basename tools/dockerfile/distribtest/php_jessie_x64
++ sha1sum tools/dockerfile/distribtest/php_jessie_x64/Dockerfile
sha1sum: tools/dockerfile/distribtest/php_jessie_x64/Dockerfile: No such file or directory
++ cut -f1 '-d '
+ DOCKER_IMAGE_NAME=php_jessie_x64:
+ '[' '' '!=' '' ']'
+ '[' grpctesting '!=' '' ']'
+ DOCKER_IMAGE_NAME=grpctesting/php_jessie_x64:
+ docker pull grpctesting/php_jessie_x64:
invalid reference format

2020-10-01 21:08:13,272 FAILED: distribtest.php_linux_x64_jessie [ret=1, pid=29922, time=0.1sec]
```

It's probably because this file `tools/dockerfile/distribtest/php_jessie_x64/Dockerfile` https://github.com/grpc/grpc/pull/24085/files#diff-5d9f6b801fa4039e9522d623a6d9c12a is removed in #24085, while this line https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/distribtest_targets.py#L377 (and consequently this line https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/distribtest_targets.py#L249) is still expecting that docker image to exist.

Fix needed:
----

We need to put this file `tools/dockerfile/distribtest/php_jessie_x64/Dockerfile` back, but as `tools/dockerfile/distribtest/php7_jessie_x64/Dockerfile` and change the Dockerfile to install PHP7 prereqs instead. And then fix  https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/distribtest_targets.py#L234 and https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/distribtest_targets.py#L249 line to `php7`.

And we might as well change the class name from `PHPDistribTest` to `PHP7DistribTest` for consistency: https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/distribtest_targets.py#L230 and https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/distribtest_targets.py#L377-L378

**Comment by veblush** [comment]
Thanks for creating an issue about this breakage. I'm about to roll it back by https://github.com/grpc/grpc/pull/24310.

**Comment by stanley-cheung** [comment]
This should be fixed. The recent `grpc/core/master/linux/grpc_distribtests` runs are all green.
