### ISSUE TITLE
rubygems locked at 0.9.4

### ISSUE THREAD

**Issue by johnwahba** [grpc/grpc#2430]
Rubygems should allow you to install 0.10.0
https://rubygems.org/gems/grpc/ 
@tbetbetbe for visibility

**Comment by johnwahba** [comment]
Thanks!

**Comment by johnwahba** [comment]
https://github.com/grpc/grpc/issues/2457 may be related.

**Comment by tbetbetbe** [comment]
This has been fixed with the release [0.11.0](https://rubygems.org/gems/grpc)
