### ISSUE TITLE
cpr failure in blackbox testing

### ISSUE THREAD

**Issue by ronitshrivastava447** [grpc/grpc#24327]
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by karthikravis** [comment]
Not enough information about the issue. Please re-open/refile with more information.
