### ISSUE TITLE
Surface compression options in the ObjC library

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2433]
At the very least, a user needs to be able to tell the library "don't compress this message".

**Comment by jcanizales** [comment]
I have a design that's non-breaking, so this might happen after Beta.

**Comment by jcanizales** [comment]
@jayantkolhe As clarified in the last meeting, the default of the C library is to not compress anything, so the current status is secure.

Compression is very important for mobile use cases, though, so we'll definitely let the user specify a compression algorithm per host, and whether to disable compression per proto message (or binary message in the case of the raw gRPC library). None of those two things will produce breaking changes in the API:

* Setting a compression algorithm per host will be done by adding a method similar to the ones currently used to specify other per-host options like "[don't use SSL](https://github.com/grpc/grpc/blob/master/src/objective-c/tests/InteropTestsLocalCleartext.m#L54)" or "[use test certificates](https://github.com/grpc/grpc/blob/master/src%2Fobjective-c%2Ftests%2FInteropTestsLocalSSL.m#L57)".
* Disabling compression for a message will be done by adding a BOOL property to `GPBMessage` and `NSData` using an Objective-C category (no code change needed from the proto team). As is customary with category additions, the property name will be prefixed (with `grpc_`) to avoid collisions with properties and methods of the extended class.

It's still pending how will hosts publish what compression algorithms they support.

**Comment by makdharma** [comment]
this is done.
