### ISSUE TITLE
grpc on windows generates warning C4244

### ISSUE THREAD

**Issue by keter-s** [grpc/grpc#24332]
### What version of gRPC and what language are you using?
1.30.2

### What operating system (Linux, Windows,...) and version?
Windows Server 2012R2

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS2017

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

1. define a proto file similar to this:
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.intel.cloudfreed.ipservice.grpcproto";
option java_outer_classname = "IpServiceProto";
package MyServices;

message Test {
    uint32 field1 = 1;
}

Another reproduction can be made on the supplied examples project cpp\helloworld building greeter_async_client.cc.

In the proto file grpc\examples\protos\helloworld.proto change the following message:
// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}
to:
// The request message containing the user's name.
message HelloRequest {
  string name = 1;
  int32 id = 2;
}

2. built the code in VS2017(building for 64 bit)

### What did you expect to see?
passed build, no warnings/errors

### What did you see instead?
compiler issued warning C4244

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
The warning is caused due to assigning to the 32 bit (field1_) a value form an internal method which returns 64bits. 
field1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
the line is part of 
const char* RoiData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx)
the method is part of the generated [proto file].pd.cc (from my proto file)
The problem does not exist in Linux

**Comment by karthikravis** [comment]
Hey Nico - would you be the right person for this issue?

**Comment by gregstoll** [comment]
This looks like the same issue as protocolbuffers/protobuf#7103, which has a fix in a PR right now.

**Comment by veblush** [comment]
We're not trying to remove warnings in all platforms & compilers but PRs to address this specific warning is welcome.
