### ISSUE TITLE
I think one of the OpenSSL version checks in ssl_transport_security.cc is incorrect

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#24339]
This section checks `OPENSSL_API_COMPAT`: https://github.com/grpc/grpc/blob/85337d69c2439eba90a4b8985402c78ef84754b8/src/core/tsi/ssl_transport_security.cc#L165-L171

while right after that there is a different check against `OPENSSL_VERSION_NUMBER`: https://github.com/grpc/grpc/blob/85337d69c2439eba90a4b8985402c78ef84754b8/src/core/tsi/ssl_transport_security.cc#L172

I think the first check is incorrect, because [`OPENSSL_API_COMPAT`](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#OPENSSL_API_COMPAT) is used in the OpenSSL headers to determine visibility of deprecated functions. But that does not apply to `OPENSSL_init_ssl`; that function was introduced in OpenSSL 1.1.0 and is unavailable in previous versions, so I think that should also be an `OPENSSL_VERSION_NUMBER` check like the other one.

**Comment by markdroth** [comment]
Jiangtao, please reassign as appropriate within your team.  Thanks!

**Comment by jiangtaoli2016** [comment]
@murgatroid99 Thanks, I agree it should be OPENSSL_VERSION_NUMBER in line 165.  A fix PR shortly.

**Comment by markdroth** [comment]
Looks like this is resolved now.  Please reopen if that's not the case.
