### ISSUE TITLE
Publish Python 3.9 Wheel for grpcio.

### ISSUE THREAD

**Issue by crwilcox** [grpc/grpc#24344]
Python 3.9 has been released, but grpcio is not yet published with a 3.9 wheel.

**Comment by jacek-jablonski** [comment]
Hello,
it seems that pre-compiled binaries are still missing. Are there any still any issues?

**Comment by lidizheng** [comment]
@jacek-jablonski Just uploaded the `v1.33.1` wheels. Currently, the 3.9 support is available for macOS and Linux.

**Comment by Hazhzeng** [comment]
Much appreciated for the update. We're waiting for Windows Python 3.9 wheel in grpcio. Is there any documents we can follow to build the boringssl by ourselves? Please advise, thanks.

**Comment by laike9m** [comment]
+1. Is there any blocking issue for Windows?

**Comment by lidizheng** [comment]
I tried again to install Python 3.9 via the official installer, Chocolatey, nuget (https://github.com/grpc/grpc/pull/24611). However, none of them works in our CI. Turned out, Python 3.9's installer requires Windows 8.1+, but our CI image is Win7.

So, there might not be a quick fix here.

CC @laike9m @Hazhzeng

**Comment by laike9m** [comment]
> I tried again to install Python 3.9 via the official installer, Chocolatey, nuget (#24611). However, none of them works in our CI. Turned out, Python 3.9's installer requires Windows 8.1+, but our CI image is Win7.
> 
> So, there might not be a quick fix here.
> 
> CC @laike9m @Hazhzeng

My CI is running under windows-latest
https://dev.azure.com/laike9m/laike9m/_build/results?buildId=318&view=logs&j=2bb915cb-e8ef-5017-2a4c-535c7f8269e4
which I believe is Windows 10. And it still failed to install gRPC.

**Comment by lidizheng** [comment]
The error `error: [WinError 2] The system cannot find the file specified` usually indicates that the `setuptools` unable to find the right version of Visual Studio compiler. And it is hard to tame compilers on Windows.

If possible, can you try to install any version of Microsoft Visual C++ and see if `distutils` can pick it up?

**Comment by Hazhzeng** [comment]
Thanks laike9m for sharing the build logs, we're facing the same issue `error: [WinError 2] The system cannot find the file specified` when trying to install grpcio.
https://azfunc.visualstudio.com/Azure%20Functions%20Python/_build/results?buildId=8715&view=logs&j=61aaed16-80b6-5b46-b9f9-aa5a7035753f&t=37b769be-d139-57b9-cf23-99c7ae5c017f

I notice that this issue is triggered by building the BoringSSL, it there a way to mitigate this by substitute BoringSSL build process?

**Comment by ofek** [comment]
Any update on publishing wheels for Windows?

**Comment by ahtik** [comment]
Unfortunately I still get the `src\python\grpcio\grpc/_cython/cygrpc.cpp(1680): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory` when trying to build locally in Windows using v19.27.29112 Compiler from the VS 2019 Build Tools. Strangely enough pthreads.h should not have been included in this platform.

More details at https://github.com/grpc/grpc/issues/24539#issuecomment-717787097

**Comment by praghavan039** [comment]
Any updates yet?

**Comment by lidizheng** [comment]
Our CI is using win7 images, while Python3.9 deprecates it's support for win7 (see [release](https://www.python.org/downloads/release/python-390/)). It requires at least Windows 8.1 now. We need to upgrade our Windows image from win7 to win10 or winserver2016. The Windows CI image is used by Python and many other languages tests and builds.

**Comment by shivanjanip007** [comment]
Any updates ? For windows 10 + python 3.9. Still facing wheel error

**Comment by lidizheng** [comment]
3.9 wheels for Windows is released this afternoon: https://pypi.org/project/grpcio/.

**Comment by jacek-jablonski** [comment]
Hi,
wheels for MacOS Big Sur are missing yet. Could you please add them?

**Comment by hugovk** [comment]
I understand the existing wheels should be usable on Big Sur when these fixes are released in pip, should be quite soon:

* https://github.com/pypa/pip/issues/9138
* https://github.com/pypa/packaging/pull/319

In the meantime you can download a wheel, rename the part of the file to `any`, and `pip install` it. I don't have the details to hand, maybe something like:

```diff
-grpcio-1.33.2-cp39-cp39-macosx_10_9_x86_64.whl
+grpcio-1.33.2-cp39-cp39-any.whl
```

**Comment by spanky-medal** [comment]
Thanks for getting wheel out for 3.9, but it takes ages to build:
```
[11:57:28]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): started
[11:58:29]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): still running...
[11:59:30]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): still running...
[12:00:31]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): still running...
[12:01:33]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): still running...
[12:01:54]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): finished with status 'done'
```

any ideas?

**Comment by lidizheng** [comment]
@spanky-medal The gRPC Core (C/C++) contains hundreds of thousands of LOC. It appears the compilation finished within 5 minutes, that's pretty fast compare to several years ago when we can't parallelize the compilation. On the other hand, can you give more detail why you need to build the wheel from scratch? If needed, please open a new issue for the use case.

I would recommend to use the released [binary wheels](https://pypi.org/project/grpcio-tools/1.34.0/#files), they are on new manylinux standard, so `pip` needs to be upgraded.

**Comment by spanky-medal** [comment]
I have no need to build wheel, but it seems to do it anyway, not sure why. First it does this (because I specifically added wheel to my PIP list)
```
[Step 1/1] Building wheels for collected packages: antlr4-python3-runtime, grpcio-tools, jsmin, jsondiff, markupsafe, multidict, psutil, pyhelm, python-terraform, supermutes, vsts-cd-manager, yarl
```

then

```
[16:51:16]	[Step 1/1]   Building wheel for antlr4-python3-runtime (setup.py): started
[16:51:16]	[Step 1/1]   Building wheel for antlr4-python3-runtime (setup.py): finished with status 'done'
[16:51:16]	[Step 1/1]   Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.7.2-py3-none-any.whl size=140949 sha256=ffbaffa9d882091bc9e5ace92556aa71ab627c3d9e337095f80e8db6b941b7be
[16:51:16]	[Step 1/1]   Stored in directory: /tmp/pip-ephem-wheel-cache-ksie6glx/wheels/09/6d/af/8a11354277136f3e922596f9b0c205e45ddd4b8f0bda5b5c6f
[16:51:16]	[Step 1/1]   Building wheel for grpcio-tools (setup.py): started
```

I upgrade PIP at the very beginning of this process:

```
function abuse_pip() {
  echo "${cyan}> Upgrading PIP...${none}"
  pip3 install --upgrade pip
  python3 -m pip install --upgrade setuptools
}
```

resulting in:

```
[16:48:17]	[Step 1/1] > Upgrading PIP...
[16:48:18]	[Step 1/1] Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (20.3.3)
[16:48:20]	[Step 1/1] Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (51.0.0)
[16:48:25]	[Step 1/1] Collecting setuptools
[16:48:25]	[Step 1/1]   Downloading setuptools-51.1.1-py3-none-any.whl (2.0 MB)
[16:48:25]	[Step 1/1] Installing collected packages: setuptools
[16:48:25]	[Step 1/1]   Attempting uninstall: setuptools
[16:48:25]	[Step 1/1]     Found existing installation: setuptools 51.0.0
[16:48:25]	[Step 1/1]     Uninstalling setuptools-51.0.0:
[16:48:25]	[Step 1/1]       Successfully uninstalled setuptools-51.0.0
[16:48:25]	[Step 1/1] Successfully installed setuptools-51.1.1
```

So I'm not sure why it insists on building wheel here. I put this into `requirements.in`

```
grpcio>=1.33.2
```

which results in the following in `requirements.txt`:

```
grpcio-tools==1.32.0      # via pyhelm
grpcio==1.34.0            # via -r requirements.in, grpcio-tools, pyhelm
```

Any advice is appreciated!

**Comment by ghevge** [comment]
I'm  also seeing this extremely slow (at least 1/2 h just to build the wheels for  grpcio-tools and grpcio) 'Building wheel for grpcio-tools' behavior, each time I'm rebuilding my container after changing something in the requirements. I'm on alpine 3.13 , python 3.9.5 and the latest pip available for this stack. 

grpcio-tools=1.38.1

Is there any way of improving this behavior? 

Thanks

**Comment by ghevge** [comment]
BTW I've tried to installed the precompiled wheels available here: https://pypi.org/project/grpcio-tools/1.38.1/#modal-close but none of them seems to work with my platform. I keep getting the error : '....whl is not a supported wheel on this platform.   '

**Comment by ofek** [comment]
@ghevge you'll want to follow https://github.com/pypa/auditwheel/issues/305

**Comment by lidizheng** [comment]
@ghevge Same as @ofek. Currently, PyPA's binary wheel standards only support glibc-based Linux. If your goal is minimizing the size of the final image, I would recommend trying out out other base images, e.g., [phusion/baseimage](https://github.com/phusion/baseimage-docker). Or [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)

**Comment by ghevge** [comment]
Thanks for the answers. My main goal is to reduce the build time of grpc wheels .

**Comment by lidizheng** [comment]
@ghevge In that case, if you are open to change the base image, you could use `phusion/baseimage:master`. It's a minimum Ubuntu, uses glibc, so we can install the binary wheels from PyPA via `pip`.

**Comment by ghevge** [comment]
I cannot drop alpine. I guess I will have to live with this limitation for now...
