### ISSUE TITLE
Generated mock only mocks Async<>Raw methods which are declared private

### ISSUE THREAD

**Issue by Jumziey** [grpc/grpc#24351]
### What version of gRPC and what language are you using?
3.12.4, cpp

### What operating system (Linux, Windows,...) and version?
Arch Linux, Linux 5.18.12

### What runtime / compiler are you using (e.g. python version or version of gcc)
protoc (libprotoc 3.12.4)

### What did you do? 
protoc -I "$proto_root" --grpc_out=generate_mock_code=true:"$proto_root" --plugin=protoc-gen-grpc="$(which grpc_cpp_plugin)" "$proto_root"/path/to/protofile.proto

### What did you expect to see?
protofile_mock.grpc.pb.h with PrepareAsync and Async methods mocked without the Raw suffix. 

### What did you see instead?
Mocked PrepareAsync and Async methods with the Raw suffix

**Comment by veblush** [comment]
Would you elaborate the issue? I don't see the problem here clearly.
