### ISSUE TITLE
(c#) Self allocation of Service input dtos

### ISSUE THREAD

**Issue by MaximGurschi** [grpc/grpc#24368]
Hi team,

Is there a way for me to inject some code that would allow me to manage allocation of input dtos myself?

Say the C# service methods look like:
public override Task UniClientStreamServer(**MyDto** request,
            IServerStreamWriter<Response> responseStream,
            ServerCallContext context)

public override async Task Bidi(IAsyncStreamReader<**MyDto**> requestStream,
            IServerStreamWriter<Response> responseStream,
            ServerCallContext context)

Is there a way for me to provide the code that materializes the request byte stream into **MyDto** objects that i allocate myself?

For me the goal is to achieve object reuse and avoid creating garbage.

**Comment by jtattermusch** [comment]
Please only post bugs / feature requests as github issue (btw the issue template clearly mentions that).

To respond to the question:
In gRPC C#, you have the ability to use custom marshallers (see https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/Marshaller.cs) and use them to override the serialization /deserialization logic. Of course doing so is a bit advanced topic (and we just recommend using Protobuf), but by defining a custom marshaller you might be able to achieve what you described above.

**Comment by MaximGurschi** [comment]
@jtattermusch Thank you! Can you please confirm if one can mix using the Marshaller for some web methods and standard protobuf for others (within the same service)?

**Comment by jtattermusch** [comment]
With custom marshaller you pretty much control the entire serialization/deserialization, so it's mostly up to you which behavior decide to implement (but then of course if you implement something that's messy, you only have yourself to blame :-) ) So in general, the answer is yet, but note that this wouldn't give you "plain" http2 request anyway as gRPC will add its framing (e.g. message is prepended with a size delimiter on the wire) on top http2. You'll only get gRPC with custom serialization/deserialization (e.g. use JSON instead of protobuf. or both if you come up with some way of determining when to expect JSON and when to expect protobuf).

**Comment by MaximGurschi** [comment]
Sorry to drag this on, but i just want to clarify this:


>  but note that this wouldn't give you "plain" http2 request anyway

The question is - this stream of bytes that i will receive in the Marshaller instance it will be the original bytes (non https encrypted) with length prefixes as the only injected additional bytes? Nothing more than that? 

In any case i think i would want to use the DeserializationContext API of the Marshaller so that i can get at the ReadOnlySequence so as to avoid byte array allocations too. I am aware this is an experimental API. But assuming it becomes a mainstay or something similar is added later I just want to confirm if the "bytes" exposed to the Marshaller are "plain" bytes sent by the client with only maybe length prefixes added.

On a side note, if there will ever be a feature added that allows me to control Service request protobuf object lifecycle then i won't bother with the Marshaller at all.

The API i am thinking is something of the form:
1.T AllocateProtobuf<T>(); // Called when the grpc stack reads the stream of bytes and allocates the object to pass to my Unary/Bidi method.
2.void Release<T>(T protobuf); //Called when the grpc request is completed for whatever reason and the grpc stack no longer needs the object.

**Comment by jtattermusch** [comment]
Marshaller will receive the bytes as in "Message" from https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md (see `Length-Prefixed-Message → Compressed-Flag Message-Length Message`)

**Comment by MaximGurschi** [comment]
For completeness, in the end i just went for altering the generated proto class to allow me to inject a parser that i can set so that i can control the proto instantiation. I used roslyn to generate code based on the existing proto classes so that it is developer friendly.
