### ISSUE TITLE
iOS build : 'absl/base/options.h' file not found

### ISSUE THREAD

**Issue by kirualex** [grpc/grpc#24366]
### What version of gRPC and what language are you using?
1.32.2

### What operating system (Linux, Windows,...) and version?
MacOS (for iOS development)

### What runtime / compiler are you using (e.g. python version or version of gcc)
--

### What did you do?
build for release

### What did you expect to see?
success build

### What did you see instead?
Pods/abseil/absl/base/config.h:66:10: 'absl/base/options.h' file not found
Apparently abseil dependency causes issues, as reverting to a previous version without it (1.19.0) fixes the issue

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yulin-liang** [comment]
Can you try to run `pod install` after removing `Pods/` `project.xcworkspace` and `Podfile.lock`, and see if you find `Pods/abseil/absl/base/options.h`.

**Comment by kirualex** [comment]
Yes @yulin-liang the file is indeed present.
But It appears it's actually conflicting with libopus which itself have imports:
``` objective-c
#include "absl/base/options.h"
#include "absl/base/policy_checks.h"
```
I'm wondering how to prevent this

**Comment by kirualex** [comment]
Ok so after much research, I finally found out that there can be some header conflicts through the `HEADER_MAP` mechanism in Xcode.
I've posted an answer pertaining to this issue here : https://stackoverflow.com/questions/65132661/cocoapods-header-conflict-between-libopus-and-abseil/65182313#65182313
