### ISSUE TITLE
Pip install failing while running setup.py install for grpcio

### ISSUE THREAD

**Issue by sahilsharma011** [grpc/grpc#24390]
### What version of gRPC and what language are you using?
It is getting installed with my pip requirements. I don't know which package has this as a dependency. Here is my requirements.txt
```
Django==2.2.2
celery==3.1.25
django-celery==3.2.2
djangorestframework==3.9.3
redis==2.10.6
djangorestframework-simplejwt==4.3.0
boto3==1.4.4
django-cors-headers==2.4.0
gunicorn==19.9.0
django-storages==1.7.1
boto3==1.4.4
pyOpenSSL==17.1.0
razorpay==1.2.0
psycopg2==2.7.1
Pillow==6.0.0
django-imagekit==4.0.2
--no-binary :all: psycopg2
google-api-python-client==1.7.10
oauth2client==4.1.3
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.0
WeasyPrint==48
bs4==0.0.1
sentry-sdk==0.13.0
google-cloud-texttospeech==1.0.1
firebase-admin==4.0.1

```

### What operating system (Linux, Windows,...) and version?
MacOS Catalina 10.15.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.12

### What did you do?
Ran `pip install -r requirements.txt`
### What did you expect to see?
All dependencies installed successfully

### What did you see instead?
See complete stacktrace at https://paste.ee/p/2aVMF
```
Running setup.py install for grpcio ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sanjiviniahuja/PycharmProjects/chiku/chiku-backend/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pv/207jk0vx6pv6kx4cj7wsqrbm0000gq/T/pip-install-cpbasr9y/grpcio/setup.py'"'"'; __file__='"'"'/private/var/folders/pv/207jk0vx6pv6kx4cj7wsqrbm0000gq/T/pip-install-cpbasr9y/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pv/207jk0vx6pv6kx4cj7wsqrbm0000gq/T/pip-record-xqnbnzdy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sanjiviniahuja/PycharmProjects/chiku/chiku-backend/include/site/python3.6/grpcio
. (Skipped middle because too large. Complete stacktrace at https://paste.ee/p/2aVMF)
.
.
.
.
.
.
ERROR: Command errored out with exit status 1: /Users/sanjiviniahuja/PycharmProjects/chiku/chiku-backend/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pv/207jk0vx6pv6kx4cj7wsqrbm0000gq/T/pip-install-cpbasr9y/grpcio/setup.py'"'"'; __file__='"'"'/private/var/folders/pv/207jk0vx6pv6kx4cj7wsqrbm0000gq/T/pip-install-cpbasr9y/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pv/207jk0vx6pv6kx4cj7wsqrbm0000gq/T/pip-record-xqnbnzdy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sanjiviniahuja/PycharmProjects/chiku/chiku-backend/include/site/python3.6/grpcio Check the logs for full command output.
```

### Anything else we should know about your project / environment?
I am getting this huge 1MB error stack trace. I am not able to understand any particular issue from this stacktrace. I have spent 2 days on this. Please help. Thank you

**Comment by hannesvoss** [comment]
It's firebase-admin. I get the same issue on Windows x64 with firebase-admin==4.4.0. Let's wait for a fix 😟

**Comment by lidizheng** [comment]
The error is caused by the OPENSSL symbol conflicts with the built-in BoringSSL symbols. You can set `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true` and build again.

But, it seems you just want to install gRPC Python, which should not require building from source. We do provide pre-compiled binary wheels for macOS. It's possible that you are taking a very old version of gRPC Python as dependency. Can you upgrade the packages in `requirements.txt` and try again? Especially, the "google-*" ones.

**Comment by lidizheng** [comment]
@hannesvoss Installation errors can be caused by many things. If possible, please try to file another issue.

**Comment by sahilsharma011** [comment]
Thank you @lidizheng. As you mentioned this error was due to some dependency installing an older version of grpcio.  
I just installed the latest version of grpcio in my virtualenv before running `pip install -r requirements.txt` and everything installed perfectly after that.  
I am now closing this issue.

**Comment by sometimescasey** [comment]
Thanks so much for this thread!

I encountered this error today when deploying a Django app via AWS Elastic Beanstalk. I am not using `firebase-admin` but similar to you, a unknown package from my `requirements.txt` must have been installing an incompatible version of `grpcio` which led to these errors:

```
-------------------------------------
/var/log/eb-activity.log
-------------------------------------
        ...
        File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'gcc' failed with exit status 1
      
      
      ----------------------------------------
  Command "/opt/python/run/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nebgt3ma/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x8opdo1o-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/python/run/venv/include/site/python3.6/grpcio" failed with error code 1 in /tmp/pip-build-nebgt3ma/grpcio/
  You are using pip version 9.0.1, however version 20.3.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  2020-12-07 20:44:23,374 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
```

I added the line `grpcio==1.26.0rc1` to `requirements.txt` and kept moving it up until it was above the offending package. This ended up working (file truncated for length):

```
backcall==0.1.0
certifi==2019.3.9
chardet==3.0.4
decorator==4.3.0
dj-database-url==0.5.0
Django==2.2
django-cors-headers==2.4.0
djangorestframework==3.9.1
djangorestframework-jwt==1.11.0
grpcio==1.26.0rc1
...
```

**Comment by lidizheng** [comment]
@sometimescasey Have you tried to install the latest release? If there is an installation issue (like unable to find the binary wheel), please file another issue. We generally recommend to use newer releases.

**Comment by sometimescasey** [comment]
@lidizheng hi, sorry for the delay! I tried pinning to `grpcio==1.34.0` per the latest release on your repo but got the same error as before. Any other suggestions, I am happy to try

**Comment by lidizheng** [comment]
@sometimescasey Can you include the whole installation log and open a new issue?

**Comment by justinwride** [comment]
> The error is caused by the OPENSSL symbol conflicts with the built-in BoringSSL symbols. You can set `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true` and build again.
> 
> But, it seems you just want to install gRPC Python, which should not require building from source. We do provide pre-compiled binary wheels for macOS. It's possible that you are taking a very old version of gRPC Python as dependency. Can you upgrade the packages in `requirements.txt` and try again? Especially, the "google-*" ones.

What finally fixed the issue for me was adding what you recommended along with `GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`.

I'm using a new Apple Silicon M1 MacBook and added these two lines to my **~/.zshrc** file that finally worked:
`export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`

**Comment by MadhavanPillai** [comment]
Facing the same errors while trying to install grpcio on MacOSx.
Already set .
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

**Comment by bhattraideb** [comment]
These commands solved the problem for me on macOS Big Sur(V-11.3.1).

`GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
echo 'export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1'
echo 'export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1'`

**Comment by MutualismPtyLtd** [comment]
> > The error is caused by the OPENSSL symbol conflicts with the built-in BoringSSL symbols. You can set `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true` and build again.
> > But, it seems you just want to install gRPC Python, which should not require building from source. We do provide pre-compiled binary wheels for macOS. It's possible that you are taking a very old version of gRPC Python as dependency. Can you upgrade the packages in `requirements.txt` and try again? Especially, the "google-*" ones.
> 
> What finally fixed the issue for me was adding what you recommended along with `GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`.
> 
> I'm using a new Apple Silicon M1 MacBook and added these two lines to my **~/.zshrc** file that finally worked: `export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1` `export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`

This solved my issue, thank you.

**Comment by AdamYoung71** [comment]
> > The error is caused by the OPENSSL symbol conflicts with the built-in BoringSSL symbols. You can set `GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true` and build again.
> > But, it seems you just want to install gRPC Python, which should not require building from source. We do provide pre-compiled binary wheels for macOS. It's possible that you are taking a very old version of gRPC Python as dependency. Can you upgrade the packages in `requirements.txt` and try again? Especially, the "google-*" ones.
> 
> What finally fixed the issue for me was adding what you recommended along with `GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`.
> 
> I'm using a new Apple Silicon M1 MacBook and added these two lines to my **~/.zshrc** file that finally worked: `export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1` `export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`

Using the M1 chip Mac too, thanks for this, works well now.
