### ISSUE TITLE
How to add metadata to nodejs header without using SSL？

### ISSUE THREAD

**Issue by dtyctrl** [grpc/grpc#24410]
`var channelCredentials = grpc.credentials.createSsl();`
`var credentials = grpc.credentials.createFromMetadataGenerator(generateMetadata);`
 `var client = new services.AsrServiceClient('0.0.0.1:8051', grpc.credentials.combineChannelCredentials(channelCredentials, credentials));`

I have to use SSL add metadata to nodejs header.
How to add metadata to nodejs header without using SSL？

**Comment by donnadionne** [comment]
Please direct general question like this one to https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
