### ISSUE TITLE
[FLAKE] csharp.Grpc.Core.Tests.CompressionTest on Windows

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#24429]
https://source.cloud.google.com/results/invocations/13a44615-bb28-41bb-b82b-ba7595bd2d44/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_opt_native_default_coreclr%2Fcsharp.Grpc.Core.Tests.CompressionTest/tests

**Comment by jtattermusch** [comment]
Haven't seen this in the last 100days.
