### ISSUE TITLE
Import "google/protobuf/wrappers.proto" was not found or had errors. Compiling from gprcio-tools.

### ISSUE THREAD

**Issue by ToucanBran** [grpc/grpc#24432]
### What version of gRPC and what language are you using?
Language: python 3.7.9
Packages: grpcio 1.32.0, grpcio-tools 1.32.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
grpc-tools 1.32.0

### What did you do?
I have the following proto file in my protos directory which looks like this 
```
syntax = "proto3";
import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "io.grpc.examples.tap";
option java_outer_classname = "TapProto";
option objc_class_prefix = "HLW";

package tap;

service TapService {
  rpc IdentifyProduct (IdentifyProductRequest) returns (IdentifyProductResponse) {}
}

message IdentifyProductRequest {
  string fileName = 1;
}

message IdentifyProductResponse {
  string PartNumber = 1;
  string SerialNumber = 2;
}
```

Then I ran this code

```python
protoc.main((
            '',
            f'-I../protos',
            '--python_out=.',
            '--grpc_python_out=.',
            f'../protos/tap.proto',
        ))
```

### What did you expect to see?
No errors, just everything compiled

### What did you see instead?
```
google/protobuf/wrappers.proto: File not found.
tap.proto:2:1: Import "google/protobuf/wrappers.proto" was not found or had errors.
```

**Comment by ToucanBran** [comment]
one other note. If I try to compile using the console:

```python 
python -m grpc_tools.protoc -I../protos --python_out=../protos --grpc_python_out=../protos ../protos/tap.proto
```
It works. However, I'd like to use the protoc.main function from grpc_tools in python code so it can do it at runtime.

**Comment by gnossen** [comment]
You're definitely off the beaten path here. What you're missing is [an include path](https://github.com/grpc/grpc/blob/master/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L170) that the command line invocation adds for you. We package the well-known protos in the `grpcio-tools` package and automatically add them for you:

```
rbellevi@rbell:/tmp/tmp.0bYKUzZ0UO/grpc_tools$ tree _proto
_proto
└── google
    └── protobuf
        ├── any.proto
        ├── api.proto
        ├── compiler
        │   └── plugin.proto
        ├── descriptor.proto
        ├── duration.proto
        ├── empty.proto
        ├── field_mask.proto
        ├── source_context.proto
        ├── struct.proto
        ├── timestamp.proto
        ├── type.proto
        └── wrappers.proto
```

**Comment by ToucanBran** [comment]
@gnossen I copied the code directly from https://github.com/grpc/grpc/blob/v1.32.0/examples/python/route_guide/run_codegen.py

Which part am I missing in the protoc.main code?

**Comment by gnossen** [comment]
Interesting. I missed that detail. In that case, this is a bug, which you should be able to work around for the moment by adding the directory I mentioned above with `sys.path.append(path)`. I'll make a patch for the fix.

**Comment by Triptikothari** [comment]
hi I am gettng this error when converting into the dict and using the Message to Dict 

File "/home/tripti.kothari/.virtualenvs/pgconfiggrpc/lib/python3.10/site-packages/google/protobuf/json_format.py", line 390, in _IsWrapperMessage
    return message_descriptor.file.name == 'google/protobuf/wrappers.proto'
AttributeError: 'google._upb._message.RepeatedCompositeContainer' object has no attribute 'file'

please help me out with issue
