### ISSUE TITLE
FLAKE: tests.cloud_to_cloud:go:dart_server:timeout_on_sleeping_server:tls

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#24442]
https://source.cloud.google.com/results/invocations/27d018a1-6f16-41b9-99d0-cade385ed927/targets/github%2Fgrpc%2Finterop_test/tests

```
FATAL: 2020/10/16 14:51:23 [interop] &{0xc0000e37a0}.Recv() = _, <nil>, want error code 4
exit status 1
```

**Comment by easwars** [comment]
The test case which failed expects that the server does not respond within the stipulated time. The client is in `Go`, while the server in `dart`. There doesn't seem to be enough information in the logs about why the server did not timeout. Essentially, the client got a successful response and hence the test failed.

**Comment by mit-mit** [comment]
What version of dart-grpc is the server running?
