### ISSUE TITLE
make: "clang: Command not found" when building under UnrealEngine

### ISSUE THREAD

**Issue by 1yc** [grpc/grpc#24465]
### What version of gRPC and what language are you using?
latest version

### What operating system (Linux, Windows,...) and version?
**Windows Subsystem Linux**

### What runtime / compiler are you using (e.g. python version or version of gcc)
terminal

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Just when I was running ./Setup.sh came out an error
```
Created an alias to xlocale.h
CFLAGS=-fPIC -Wno-error --sysroot=/mnt/d/GitHub/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v13_clang-7.0.1-centos7/x86_64-unknown-linux-gnu, CXXFLAGS=-std=c++14 -fPIC -nostdinc++ -Wno-expansion-to-defined -Wno-error -I/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/Linux/LibCxx/include -I/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/Linux/LibCxx/include/c++/v1 -I/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/OpenSSL/1_0_2h/include/Linux/x86_64-unknown-linux-gnu, LDFLAGS=-L/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/Linux/LibCxx/lib/Linux/x86_64-unknown-linux-gnu -L/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/OpenSSL/1_0_2h/lib/Linux/x86_64-unknown-linux-gnu -fuse-ld=/mnt/d/GitHub/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v13_clang-7.0.1-centos7/x86_64-unknown-linux-gnu/bin/lld-gnu, LDLIBS=-lc++ -lc++abi -lc, PROTOBUF_LDFLAGS_EXTRA=-L/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/Linux/LibCxx/lib/Linux/x86_64-unknown-linux-gnu -L/mnt/d/GitHub/UnrealEngine/Engine/Source/ThirdParty/OpenSSL/1_0_2h/lib/Linux/x86_64-unknown-linux-gnu -fuse-ld=/mnt/d/GitHub/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v13_clang-7.0.1-centos7/x86_64-unknown-linux-gnu/bin/lld-gnu -lc++ -lc++abi -lc
[MAKE]    Generating /mnt/d/GitHub/InfraworldRuntime/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /mnt/d/GitHub/InfraworldRuntime/grpc/libs/opt/pkgconfig/gpr.pc
[MAKE]    Generating /mnt/d/GitHub/InfraworldRuntime/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
**[C]       Compiling third_party/address_sorting/address_sorting.c
make: /mnt/d/GitHub/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v13_clang-7.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang: Command not found
make: *** [Makefile:2998: /mnt/d/GitHub/InfraworldRuntime/grpc/objs/opt/third_party/address_sorting/address_sorting.o] Error 127**
```
and I cannot go on with the setup process

### What did you expect to see?
success make

### What did you see instead?
error

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Unreal Engine 4.22 with clang-7.0.1 installed

**Comment by jtattermusch** [comment]
The error is 
`/mnt/d/GitHub/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v13_clang-7.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang: Command not found` which more looks like clang is missing in your toolchain?
So this is likely a problem with how your toolchain is setup rather than a gRPC issue per se.

I'm not familiar with UnrealEngine and I'm not sure it's a platform we actually support.
It still might be possible to build gRPC under UnrealEngine, but you might need to experiment a little bit. 
Btw, the Makefile is now intended for internal use only, we recommend external users to use cmake instead (https://github.com/grpc/grpc/blob/master/src/cpp/README.md).
