### ISSUE TITLE
gRPC package in opensuse/tumbleweed installs broken Abseil

### ISSUE THREAD

**Issue by devjgm** [grpc/grpc#24476]
The latest gRPC 1.32.0 package provided by opensuse/tumbleweed doesn't work and broke the https://github.com/googleapis/google-cloud-cpp build, but I believe it will break anyone who uses gRPC and Abseil. See https://github.com/googleapis/google-cloud-cpp/issues/5277 for more details.

## SUMMARY

The opensuse/tumbleweed Docker image was updated a few days ago. The updated image contains a zypper package for gRPC 1.32.0. Here's the spec file: https://build.opensuse.org/package/view_file/openSUSE:Factory/grpc/grpc.spec?expand=1
As you can see in that spec file, they invoke cmake for grpc like

```
%cmake -DgRPC_INSTALL=ON                  \
       -DgRPC_INSTALL_LIBDIR:PATH="%_lib" \
       -DgRPC_INSTALL_CMAKEDIR:PATH="%_libdir"/cmake/grpc \
       -DgRPC_ABSL_PROVIDER=module        \
       -DgRPC_CARES_PROVIDER=package      \
       -DgRPC_PROTOBUF_PROVIDER=package   \
       -DgRPC_RE2_PROVIDER=package        \
       -DgRPC_SSL_PROVIDER=package        \
       -DgRPC_ZLIB_PROVIDER=package
%cmake_build
```

I believe the problem is ` -DgRPC_ABSL_PROVIDER=module`, which _I think_ results in the "cmake install" for gRPC actually installing binary artifacts (like `libabsl_foo.so`) for Abseil. It doesn't install Abseil headers, or Abseil's `.cmake` files. So the gRPC install installs partial binary artifacts for some other project.

The problem is that now callers cannot use the installed Abseil binary artifacts, because there are no headers or `.cmake` files. And similarly, if a caller separately compiles and compiles Abseil, there will be _multiple_ copies of Abseil binary artifacts, which can easily lead to ODR or ABI problems.

## THE FIX

I think it's a mistake for any package to ever install artifacts that it doesn't own. So I think it's a **bug** that gRPC's install target would install any artifacts of Abseil's. [This doesn't look right to me](https://github.com/grpc/grpc/blob/master/cmake/abseil-cpp.cmake).

I think gRPC's "install" should fail if any of its deps was fetched as a "module", as is Abseil in the opensuse example above. If that failed, then the opensuse maintainers would have known to make an Abseil package first and tell gRPC to depend on that instead.

/cc: @derekmauro FYI about Abseil stuff
/cc: @coryan JFYI

**Comment by veblush** [comment]
Thanks Greg for bring up this issue.

First of all, installing from the module is supposed to be used in the formal package so gRPC OpenSUSE package has a bug and should address it to avoid potential ODR problems.

Installation-from-the-module is (I believe) for users to build and install gRPC easily as a better out-of-box experience. (#21411) and this applies to all dependencies gRPC has. @jtattermusch, WDTY?

**Comment by coryan** [comment]
> First of all, installing from the module is supposed to be used in the formal package so gRPC OpenSUSE package has a bug and should address it to avoid potential ODR problems.

Did you mean "... is **not** supposed to be used in the format package ..." ?

**Comment by veblush** [comment]
> > First of all, installing from the module is supposed to be used in the formal package so gRPC OpenSUSE package has a bug and should address it to avoid potential ODR problems.
> 
> Did you mean "... is **not** supposed to be used in the format package ..." ?

Dang, you're right! I edited it. Thanks!

**Comment by devjgm** [comment]
> First of all, installing from the module is not supposed to be used in the formal package so gRPC OpenSUSE package has a bug and should address it to avoid potential ODR problems.

OK, will you or someone on the gRPC team file a bug against opensuse and follow up so they can fix their package?

> Installation-from-the-module is (I believe) for users to build and install gRPC easily as a better out-of-box experience. (#21411) and this applies to all dependencies gRPC has. @jtattermusch, WDTY?

There are other ways to improve the out of the box experience, such as a CMake super build, which is what I'd recommend. And these have the advantage that each project will *install itself*. I maintain that it's a mistake/bug for any project to install artifacts that it does not own, because then users cannot use your project AND the project that actually owns those artifacts.

**Comment by veblush** [comment]
I found the [change](https://build.opensuse.org/package/rdiff/devel:tools/grpc?linkrev=base&rev=63) to introduce `-DgRPC_ABSL_PROVIDER=module` in the package. Since I couldn't find the right channel to file the issue, I just sent a mail to a maintainer.

Can you elaborate superbuild? I guess [this](https://blog.kitware.com/cmake-superbuilds-git-submodules/) is the right one to understand it. I think what we have in the gRPC repo is similar to it, though.

**Comment by devjgm** [comment]
> I found the [change](https://build.opensuse.org/package/rdiff/devel:tools/grpc?linkrev=base&rev=63) to introduce `-DgRPC_ABSL_PROVIDER=module` in the package. Since I couldn't find the right channel to file the issue, I just sent a mail to a maintainer.

Excellent. Thank you.
 
> Can you elaborate superbuild? I guess [this](https://blog.kitware.com/cmake-superbuilds-git-submodules/) is the right one to understand it. I think what we have in the gRPC repo is similar to it, though.

The link you provided is good. The big difference between a super build and what gRPC is currently doing is that a super build fetches the deps that it needs and each dep *installs itself*. The difference with gRPC's current strategy is that *gRPC* is installing part of Abseil and it's doing so incorrectly, thus making it so users can no longer use both gRPC _AND_ Abseil.

I believe it's always a bug for a project to install artifacts that it does not own.

It looks like this probably started with gRPC in https://github.com/grpc/grpc/pull/21411. I think that PR should probably be rolled back or undone in some way.

**Comment by veblush** [comment]
@devjgm I see. If gRPC can install easily without hurting interoperability, I like to have that change. Before starting to work on it, I like to here from Jan's opinion. @jtattermusch

**Comment by devjgm** [comment]
In case it helps, you can take a look at the super build for our project at https://github.com/googleapis/google-cloud-cpp/tree/master/super. We're also happy to chat and help out. Let me know if there's something you need.

**Comment by jtattermusch** [comment]
Ok, so to summarize:
- I agree that when installing, `-DgRPC_ABSL_PROVIDER=package` should be used by packages that are meant for consumption by users (such as linux distro packages, in this case it's OpenSuse).
- If OpenSuse creates their package in a wrong way, it's not gRPC's responsibility as we don't maintain that package. From that perspective it's not a gRPC bug that someone uses gRPC wrong.
- as veblush@ has pointed out, we use `-DgRPC_ABSL_PROVIDER=module` to simplify our internal builds and that's completely fair and I don't see a problem with that (it's true that we don't explicitly forbid running  "install" target with a build configured like that but we cannot have protection for every wrong use pattern there is).
- I'm familiar with "superbuild" and we've actually experimented with it in the past in our cmake build, but there result's weren't very encouraging (basically it lead to a build that's not easy to understand and it didn't quite solve any of our problems), so I'm quite sceptical here as I don't really understand how exactly that would help us (but I guess I can be convinced).

To me, the only usability problem would beif absl cannot really be installed as a separate library (in some reasonable way) and then depended upon by using `-DgRPC_ABSL_PROVIDER=package` - I'm not sure if that's the case currently.

**Comment by devjgm** [comment]
> Ok, so to summarize:
> 
> * I agree that when installing, `-DgRPC_ABSL_PROVIDER=package` should be used by packages that are meant for consumption by users (such as linux distro packages, in this case it's OpenSuse).

Agreed. I think this statement could be made a little stronger by saying that `-DgRPC_ABSL_PROVIDER=package` should be used _by anyone_ who is _installing_ gRPC.

> * If OpenSuse creates their package in a wrong way, it's not gRPC's responsibility as we don't maintain that package. From that perspective it's not a gRPC bug that someone uses gRPC wrong.

Agreed. I don't actually think that this is gRPC's bug, other than the OpenSuse gRPC package is currently broken, and the gRPC folks might want to alert the OpenSuse package maintainers to the problem so they can fix it. Otherwise, customers will have a bad experience with gRPC on OpenSuse.

It looks like @veblush sent them a message according to https://github.com/grpc/grpc/issues/24476#issuecomment-716870223

> * as veblush@ has pointed out, we use `-DgRPC_ABSL_PROVIDER=module` to simplify our internal builds and that's completely fair and I don't see a problem with that (it's true that we don't explicitly forbid running  "install" target with a build configured like that but we cannot have protection for every wrong use pattern there is).

If the goal of `-DgRPC_ABSL_PROVIDER=module` is only to simplify your internal builds, maybe you could add some loud warnings to discourage users from accidentally using it. I think the OpenSuse maintainers made the mistake because it was an easy mistake to make.

Do you need the ability to "install" when using `-DgRPC_ABSL_PROVIDER=module` for your internal builds? If not, prohibiting installs of gRPC's module deps would prevent users from accidentally doing the wrong thing.

To be clear, the main issue I'm reporting in this thread is that gRPC makes it very easy to do the wrong thing by allowing "module" deps to be installed.

> * I'm familiar with "superbuild" and we've actually experimented with it in the past in our cmake build, but there result's weren't very encouraging (basically it lead to a build that's not easy to understand and it didn't quite solve any of our problems), so I'm quite sceptical here as I don't really understand how exactly that would help us (but I guess I can be convinced).

I'd be happy to chat/GVC to see if there's anything I can do to help. But I'd first need to understand what your goals are and how `-DgRPC_ABSL_PROVIDER=module` satisfies those goals.

> 
> To me, the only usability problem would beif absl cannot really be installed as a separate library (in some reasonable way) and then depended upon by using `-DgRPC_ABSL_PROVIDER=package` - I'm not sure if that's the case currently.

Abseil can be installed correctly along with its own `.cmake` files, and I believe it should work fine with `-DgRPC_ABSL_PROVIDER=package`.

**Comment by badshah400** [comment]
Just chiming in here --- as the person who originally introduced the issue into the openSUSE pkg --- that this has been fixed at our end for about a month now, thanks to Jan [1]. We didn't have the `abseil-cpp` shared libraries packaged at the time, and I had understood --- incorrectly, I have since learnt --- that using `-DgRPC_ABSEIL_PROVIDER=module` would just build and install the abseil-cpp library as required too.

I agree with @devjgm that some warning when using `-DgRPC_<foo>_PROVIDER=module` would be helpful for us downstream packagers or really anyone compiling this on their own.

[1] https://build.opensuse.org/request/show/844726

**Comment by veblush** [comment]
This was fixed so closing this.
