### ISSUE TITLE
We should clean up all global memory while server exit

### ISSUE THREAD

**Issue by DinoStray** [grpc/grpc#24488]
We should clean up all global memory while server exit.  
for protobuf, do it by google::protobuf::ShutdownProtobufLibrary();
for libevent, do it by libevent_global_shutdown();
for mysql client, do it by  mysql_library_end();

But for grpc, we do nothing.  
If we use valgrind check memory leaks, it's too annoying.

**Comment by veblush** [comment]
Please take a look at the [proposal](https://github.com/grpc/proposal/pull/199) relevant to this. You can use [sanitizers](https://github.com/google/sanitizers) to detect memory leaks without worrying about static global variables.
