### ISSUE TITLE
Reading of options from env variables is broken in setup.py (e.g. BUILD_WITH_BORING_SSL_ASM)

### ISSUE THREAD

**Issue by nanonyme** [grpc/grpc#24498]
### What version of gRPC and what language are you using?
1.32.0

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 10

### What did you do?
Noticed that there's no possible value that can be passed through as BUILD_WITH_BORING_SSL_ASM that will disable boringssl https://github.com/grpc/grpc/blob/master/setup.py#L109-L110

Since there's no int() conversion of input (or similar), all possible inputs will be regarded as true. 

### What did you expect to see?
It's possible to disable boringssl asm when using system ssl

### What did you see instead?
It's not possible to disable boringssl asm when using system ssl

**Comment by nanonyme** [comment]
Note from my point of view it's fine to just always build boringssl asm unless system ssl is requested but YMMV.

**Comment by gnossen** [comment]
> Since there's no int() conversion of input (or similar), all possible inputs will be regarded as true.

That's not entirely true:

```python
rbellevi@rbell:~/Dev/grpc$ python3
Python 3.8.5 (default, Aug  2 2020, 15:09:07) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> bool("")
False
```

So you could do `export BUILD_WITH_BORING_SSL_ASM="`. But that's not a great user experience. We should probably change this so that "false" and "False" both result in disabling this feature.

**Comment by nanonyme** [comment]
Ah, that's a good point. I'll use that as workaround in our project instead of patching grpcio. Thanks for the correction. IMHO the bigger problem here is really that GRPC_PYTHON_BUILD_SYSTEM_OPENSSL is not a master switch here. I only spotted this because we started getting boringssl build failures while boringssl should not have been built at all.

**Comment by nanonyme** [comment]
Tried making pull request, realized there's CLA required, closed. Above description is fairly complete non-code explanation of desired outcome that would possibly make defaults work better though.

**Comment by jtattermusch** [comment]
Note that the way the option values are read from env variables in setup.py is broken in general:

if you assign `XYZ=False` or `XYZ=false` or `XYZ=0` that's still evaluated as `True` and the corresponding option gets enabled, which is very counterintuitive.
https://github.com/grpc/grpc/blob/711d1d7fe2da56896957e00fea12c84b6d1fa1e1/setup.py#L109-L169

**Comment by nanonyme** [comment]
Using ast.literal_eval is an option. Note, I cannot work on this due to CLA limitation. I haven't had time to clear it with employer. If anyone else has time, feel free.

**Comment by emkornfield** [comment]
I can provide a patch, I wrote this code originally.
