### ISSUE TITLE
fd leak in tcp_client_custom.cc-> custom_connect_callback_internal

### ISSUE THREAD

**Issue by hnutank163** [grpc/grpc#24492]
**in tcp_client_custom.cc -> custom_connect_callback_internal**
why not call grpc_custom_socket_vtable->close(socket, custom_close_callback) when error is not GRPC_ERROR_NONE

**in tcp_client_custom.cc -> on_alarm**
when the socket connect timeout, in tcp_client_custom.cc-> on_alarm will close the socket

if not close the socket when error happen, fd leak will happen when server not avaliable

**Comment by hnutank163** [comment]
why not call grpc_custom_socket_vtable->close(socket, custom_close_callback) when error is not GRPC_ERROR_NONE

when the socket connect timeout in tcp_client_custom.cc-> on_alarm will close the socket

**Comment by markdroth** [comment]
Richard, I'm assigning this to you, since I think Python is the only thing actually using the custom iomgr code these days (for both gevent and asyncio).

**Comment by yashykt** [comment]
This code has been deleted. Closing it.
