### ISSUE TITLE
Testing flags: Migrate from gflags to abseil's flags

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#24493]
Currently there are ~36 uses of [gflags](https://github.com/gflags/gflags) ([docs](https://gflags.github.io/gflags/)) under the `/test` subdirectory. This is to track changing them to use [Abseil Flags](https://github.com/abseil/abseil-cpp/tree/master/absl/flags) ([docs](https://abseil.io/docs/cpp/guides/flags)), which aligns with migrations that have already occurred in the Google monorepo. Abseil's Flags is an evolution of gflags, requiring use of getter and setter methods, and providing, via helper libraries, support for additional types.

**Comment by Capstan** [comment]
Mark, I started some work on this and filed this issue to track it, so you can assign it to me.

**Comment by veblush** [comment]
Nathan, can you please create the PR again with the workaround in my test PR (#24560)? Basically workaround is just using the shortened help message which is not that bad until the Abseil team manages to fix this properly.

**Comment by Capstan** [comment]
Certainly. It'll be tomorrow though. Thanks for chasing down the issue!
