### ISSUE TITLE
third_party/address_sorting uses `size_t` before including a header that defines it.

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#24505]
https://github.com/grpc/grpc/blob/9896c641860a70e41b006a982e44f40bb3f41053/third_party/address_sorting/include/address_sorting/address_sorting.h#L50

If `clang-format` reorders headers, this can cause `#include <address_sorting/address_sorting.h>` to float early in the include order and then fail with an error like:

```
In file included from test/cpp/naming/address_sorting_test.cc:19:
third_party/address_sorting/include/address_sorting/address_sorting.h:50:3: error: unknown type name 'size_t'
  size_t len;
  ^
```

**Comment by apolcyn** [comment]
Opened https://github.com/grpc/grpc/pull/24514 to try to fix this.

That said, @Capstan, out of curiosity, how did you run into this issue? `address_sorting.h` shouldn't normally <i>need</i> to be included by applications, as it's really meant for use by grpc internals. Are you using the address sorting APIs directly?

**Comment by Capstan** [comment]
No, I was working on a PR for this repo (#24506), and using `clang-format` to fix up the formatting, and its rearrangement of headers after my fiddling caused this error. You can see my workaround at https://github.com/grpc/grpc/pull/24506/commits/cb520c3bdc79433d6d5777029c4bdd0062d9ef8e#diff-500a42f8af47e79cad9bf3a6c24c3579641b3bd437866c55b42385dd6bb718daR31, since if you let clang-format have its way, it moves it to the top of the file and then you get compile errors in the test.

**Comment by Capstan** [comment]
Verified; removed the clang workaround.
