### ISSUE TITLE
Make grpc_core::PemKeyCertPair Taking std::string

### ISSUE THREAD

**Issue by ZhenLian** [grpc/grpc#24515]
Current grpc_core::PemKeyCertPair implementation(https://github.com/grpc/grpc/blob/master/src/core/lib/security/security_connector/ssl_utils.h#L146) depends on the core struct `grpc_ssl_pem_key_cert_pair`. Using this in TlsCredentials will cause a lot of unnecessary copies all over the place. It would be good if we change this to take std::string as parameters, and only convert to core struct once when it is actually used.

CC @markdroth @jiangtaoli2016

**Comment by markdroth** [comment]
This was done in #24805.
