### ISSUE TITLE
GRPC c++ gets Segfault (repeatedly)

### ISSUE THREAD

**Issue by kianooshm** [grpc/grpc#2452]
Setup:
- Grpc in bidirectional streaming mode.
- Server: One server with a large-enough thread pool being talked-to via multiple grpc channels from the client.
  - Also tried multiple independent servers (on different ports on the same host) each being talked-to via only one channel from the client. Same problem on the client side.
- Client: N grpc channels, each channel corresponds to 2 threads, one reading and one writing to it. Client crashes if >1 channel, even if only a few.

The crash happens in `ClientReaderWriter::Read()`. If only a single channel, no problem in concurrent read-and-write to that channel. If multiple channels, although they are completely disjoint, segfault happens.

Here is the stack trace. The same every time, though crash happens at different points in time -- after a few hundred requests or sometimes not until after a million requests. If the processing of requests and sending response gets slower (QPS is 0.5--1 million), crash gets less likely.
```
#0  0x00007fc19b572050 in grpc_chttp2_unlocking_check_writes () from /usr/lib/libgrpc.so.0
#1  0x00007fc19b5735ef in ?? () from /usr/lib/libgrpc.so.0
#2  0x00007fc19b55ff64 in ?? () from /usr/lib/libgrpc.so.0
#3  0x00007fc19b55b356 in ?? () from /usr/lib/libgrpc.so.0
#4  0x00007fc19b55db2b in ?? () from /usr/lib/libgrpc.so.0
#5  0x00007fc19b55d5d6 in grpc_pollset_work () from /usr/lib/libgrpc.so.0
#6  0x00007fc19b566a87 in grpc_completion_queue_pluck () from /usr/lib/libgrpc.so.0
#7  0x00007fc19b986080 in grpc::CompletionQueue::Pluck(grpc::CompletionQueueTag*) () from /usr/lib/libgrpc++_unsecure.so.0
#8  0x000000000041316b in Read (msg=0x7fc1927fbdb0, this=0x15241e0) at /usr/local/include/grpc++/stream.h:246
#9  Read (msg=0x7fc1927fbdb0, this=<optimized out>) at .. my code where it calls ClientReaderWriter::Read()
```
Please let me know if you need any more debugging info.

Is this a problem with calling `Read()` and `Write()` simultaneously on the same `ClientReaderWriter` object? I don't find that illegal, since that's how grpc examples are (e.g. RouteChat).

Please help me find a way around this bug.

**Comment by ctiller** [comment]
I think this has been addressed. Please re-open if it's still a problem.

**Comment by kianooshm** [comment]
Thanks ctiller. I've completely restructured that software so no bidirectional connection between components anymore, and this problem didn't happen with unidirectional GRPC. I will reopen the bug if anything similar happened.

**Comment by snandi1603** [comment]
Hi,
I am facing the similar problem, using cpp grpc ver 1.4. Here is the stack trace in GRPC client.
My GRPC session is bi-directional and this happens only in scaled scenario where a significant amount of write requests are being sent to GRPC server.

#0  0x00007f3e6539b68b in ?? () from /usr/share/pfe/usr/lib64/libgrpc.so.0.15.1
#1  0x00007f3e65398b44 in grpc_exec_ctx_flush () from /usr/share/pfe/usr/lib64/libgrpc.so.0.15.1
#2  0x00007f3e65397e9b in ?? () from /usr/share/pfe/usr/lib64/libgrpc.so.0.15.1
#3  0x00007f3e653a54e2 in grpc_completion_queue_pluck () from /usr/share/pfe/usr/lib64/libgrpc.so.0.15.1
#4  0x00007f3e6651fac8 in grpc::CoreCodegen::grpc_completion_queue_pluck(grpc_completion_queue*, void*, gpr_timespec, void*) () from /usr/share/pfe/usr/lib64/libgrpc++.so.0.15.1
#5  0x00007f3e6b75adb3 in grpc::CompletionQueue::Pluck (this=this@entry=0x7f3e57ffe1a0, tag=tag@entry=0x7f3e57ffe1d0)
    at /volume/wrlinux/wrlsdk/vmhost/v8/dev-next/20171208_1620/sdk/sysroots/corei7-64-wrs-linux/usr/include/grpc++/impl/codegen/completion_queue.h:208
#6  0x00007f3e6b7871c0 in grpc::BlockingUnaryCall

Can anyone tell in which scenario we will be hitting this problem
