### ISSUE TITLE
Exclude libgrpc_csharp_ext.x86.so from publish when targetting linux-64

### ISSUE THREAD

**Issue by xtroncode** [grpc/grpc#24531]
### What version of gRPC and what language are you using?
C# , gRPC 2.32.0

### What operating system (Linux, Windows,...) and version?
Linux 64 bit

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet core 3.1

### What did you do?
Build a dotnet core project for linux-64 only.
`dotnet publish -c Release -o build -r linux-x64 --self-contained false .`

### What did you expect to see?
Only have libgrpc_csharp_ext.x64.so in my build directory.

### What did you see instead?

Both libgrpc_csharp_ext.x64.so and libgrpc_csharp_ext.x86.so are copied to the build directory.

Due to this the container size increases by ~70MB . How can I only exclude the x86 binaries ?

Also this issue was already reported here #18106 but closed due to inactivity.

**Comment by jtattermusch** [comment]
On linux and mac, this is now "fixed" as a side effect of https://github.com/grpc/grpc/pull/24378

**Comment by jtattermusch** [comment]
Also, https://github.com/grpc/grpc/pull/24233 seems to aim to a solution that would work for windows as well (and would work for linux and mac if there still were the x86 artifacts).

**Comment by jtattermusch** [comment]
This can be considered fixed due to https://github.com/grpc/grpc/pull/24766 and https://github.com/grpc/grpc/pull/24378
