### ISSUE TITLE
Where to report C# compile error for "Duplicate enum value"

### ISSUE THREAD

**Issue by cgthayer** [grpc/grpc#24533]
Looks like dotnet/msbuild/csproj is attempting to compile this standard test proto from Google but (although it's a warning) is causing an error. Not sure if this is the right place to report the issue??

Namely while compiling https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/test_messages_proto3.proto 

`dotnet build -v n`  

```
       "/c/src/Roblox/bedev2-service-auth/services/envoy-auth/src/EnvoyAuth.csproj" (default target) (1:7) ->
       (_Protobuf_CoreCompile target) ->
         [libprotobuf WARNING google/protobuf/compiler/csharp/csharp_enum.cc : error : 73] Duplicate enum value Qux (originally qux) in AliasedEnum; adding underscore to distinguish [/c/src/Roblox/bedev2-service-auth/services/envoy-auth/src/EnvoyAuth.csproj]

    75 Warning(s)
    1 Error(s)
```

The idea here is that enums can have duplicate values which get renamed, and as long as it's compatible this emits a warning. However something in the msbuild for _Protobuf_CoreCompile is treating it as an Error

The generator code looks like this (C++ from src/google/protobuf/compiler/csharp/csharp_enum.cc):

```
     58 void EnumGenerator::Generate(io::Printer* printer) {                                                                                                                                                                    vice-auth/s
     59   WriteEnumDocComment(printer, descriptor_);
     60   printer->Print("$access_level$ enum $name$ {\n",                                                                                                                                                                      h/src/Envoy
     61                  "access_level", class_access_level(),
     62                  "name", descriptor_->name());
     63   printer->Indent();
     64   std::set<string> used_names;
     65   std::set<int> used_number;                                                                                                                                                                                            o3";' to sp
     66   for (int i = 0; i < descriptor_->value_count(); i++) {
     67       WriteEnumValueDocComment(printer, descriptor_->value(i));
     68       string original_name = descriptor_->value(i)->name();
     69       string name = GetEnumValueName(descriptor_->name(), descriptor_->value(i)->name());
     70       // Make sure we don't get any duplicate names due to prefix removal.
     71       while (!used_names.insert(name).second) {
     72         // It's possible we'll end up giving this warning multiple times, but that's better than not at all.
     73         GOOGLE_LOG(WARNING) << "Duplicate enum value " << name << " (originally " << original_name
     74           << ") in " << descriptor_->name() << "; adding underscore to distinguish";
     75         name += "_";
     76       }
     77       int number = descriptor_->value(i)->number();
     78       if (!used_number.insert(number).second) {
     79           printer->Print("[pbr::OriginalName(\"$original_name$\", PreferredAlias = false)] $name$ = $number$,\n",
     80              "original_name", original_name,
     81              "name", name,
     82              "number", StrCat(number));
     83       } else {
     84           printer->Print("[pbr::OriginalName(\"$original_name$\")] $name$ = $number$,\n",
     85              "original_name", original_name,
     86              "name", name,
     87              "number", StrCat(number));
     88       }
     89   }
     90   printer->Outdent();
     91   printer->Print("}\n");
     92   printer->Print("\n");
```

My details:
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by jtattermusch** [comment]
Could the problem be that your project has set `TreatWarningsAsErrors` to true?

**Comment by jtattermusch** [comment]
Btw, the `libprotobuf WARNING google/protobuf/compiler/csharp/csharp_enum.cc : error : 73] Duplicate enum value Qux (originally qux) in AliasedEnum` is coming from the protobuf protoc codegen:
https://github.com/protocolbuffers/protobuf/blob/48234f5f012582843bb476ee3afef36cda94cb66/src/google/protobuf/compiler/csharp/csharp_enum.cc#L73

So 1. this issue technically doesn't belong to this repository, but to https://github.com/protocolbuffers/protobuf/
2. it would be good to actually provide a .proto (or it's stripped down version) file that generates this warning.

**Comment by jtattermusch** [comment]
Ok, just realized that you're actually providing a .proto file.
The exact location that generates the warning is:
https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/src/google/protobuf/test_messages_proto3.proto#L83
- basically there are 2 enum values that are named alike.
Since the name of one of them needs to be mangled so that a naming conflict is avoided, I'd argue that printing a warning about this is correct - after all it's a very exotic situation and you likely won't see it in any real life protos. In the protobuf's testing protos it's included exactly for the reason that it's a very exotic situation.

**Comment by mongoDynamo** [comment]
Having this same failure in .NET using C#. 

`[libprotobuf WARNING ..\..\..\third_party\protobuf\src\google\protobuf\compiler\csharp\csharp_enum.cc : error : 74] Dup
licate enum value ... `

Trying to find a way to suppress this, but it looks like an internal error that bubbles up. Not sure if a `No Warn` will simply fix this (so far it hasn't)
