### ISSUE TITLE
convert tools/buildgen python scripts to python 3

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#24541]
At the moment, I only have python3 due to Reasons™, and re-running the instructions from https://github.com/grpc/grpc/blob/master/templates/README.md doesn't work, because it installs the python3 version of pip and mako, and then fails to find the mako library.

Python 2 was sunset on January 1, 2020.

**Comment by veblush** [comment]
Thanks, Capstan but this is a duplicate of #24359
