### ISSUE TITLE
build failing: make unable to find object from RE2 library

### ISSUE THREAD

**Issue by tiwariashish86** [grpc/grpc#24553]
1 warning generated.
[C]       Compiling third_party/address_sorting/address_sorting_windows.c
[AR]      Creating /Users/Shared/projects/test/grpc/libs/opt/libaddress_sorting.a
make: *** No rule to make target `/Users/Shared/projects/test/grpc/objs/opt/third_party/re2/re2/bitstate.o', needed by `/Users/Shared/projects/test/grpc/libs/opt/libre2.a'.  Stop.

I am trying to compile on mac for unity package.

**Comment by jtattermusch** [comment]
Are you trying gRPC C# on Unity (which is no longer supported) or just gRPC C++ on Unity (I'm not sure if that was ever supported or if anyone has ever tried that)?

See [recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more info.

**Comment by yashykt** [comment]
Closing due to no updates
