### ISSUE TITLE
Xcode 10.0 caused stack corruption under opt mode

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#24550]
With https://github.com/grpc/grpc/pull/24521, there is a test failure in `client_lb_end2end_test`. The test fails consistently only under macos opt build.

```
[ RUN      ] ClientLbEnd2endTest.ChannelStateConnectingWhenResolving
...
I1023 16:38:19.585681000 4615253440 client_lb_end2end_test.cc:389]     server startup complete
E1023 16:38:19.587544000 4615253440 client_lb_end2end_test.cc:229]     assertion failed: result.service_config != nullptr
```
Playing around it a bit, I noticed the `service_config_json` is not null but pointing to a string of the binary full path at the beginning of `BuildFakeResult`. I altered the code in various ways to see the result.

- If switching MacOs tls from `stdcpp_tls` to `pthread_tls`, the test passes
- If moving the `ExecCtx` from `SetNextResolution` to out of it in the test body, the test pases.
- If adding a log line anywhere in the `SetNextResolution` function, the test passes.

- Removing the default arguments in `BuildFakeResult` does not help.
- Making `BuildFakeResult` non-static and remove the first argument `ipv6_only` does not help.
- Running in non-opt build does not reproduce the issue (test passes)

I can reproduce this with bazel on my macbook pro. @veblush ran this on his macbook pro with different Xcode version and could not reproduce. Hence it is suspected to be a compiler bug.
My macbook has settings:
```
$ /usr/bin/xcodebuild -version
Xcode 10.0
Build version 10A255
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```
The problem goes away when I update xcode to 11.4.
```
$ xcodebuild -version
Xcode 11.4.1
Build version 11E503a
$ clang --version
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```
Assuming this is a bug in Xcode 10's handling of TLS, which may have showed up through `ExecCtx`.

**Comment by veblush** [comment]
@yang-g Most of mac machines are now using Xcode 11. Can you try creating a PR removing workarounds?
