### ISSUE TITLE
Key Management: Hardcoded Encryption Key

### ISSUE THREAD

**Issue by Shakihassan** [grpc/grpc#24563]
Hardcoded encryption keys can compromise security in a way that cannot be easily remedied.

2021305 | channelz.cc : 180 ,channelz.cc : 262 ,channelz_registry.cc : 301,channelz_registry.cc : 319, channelz_registry.cc : 283,channelz_registry.cc : 247 ,jwt_credentials.cc : 149,client_channel_channelz.cc : 164

**Comment by markdroth** [comment]
There are no hard-coded encryption keys in gRPC.  I believe your report is in error.
