### ISSUE TITLE
cpp helloworld latency is insane bigger

### ISSUE THREAD

**Issue by chuan9** [grpc/grpc#24565]
### What version of gRPC and what language are you using?
v1.30.2

### What operating system (Linux, Windows,...) and version?
ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
1. Add filed in the helloworld.proto as time.
```
message HelloRequest {
  string name = 1;
  double time = 2;
}
```
2. create first timestamp in the greeter_async_client.cc
```
    request.set_time(ros::Time::now().toSec());
```
3. create response timestamp in the greeter_async_server.cc
```
        std::string prefix("Hello ");
        reply_.set_message(prefix + request_.name());
        double latency = (ros::Time::now().toSec()-request_.time())*1000;
        std::cout<<"latency: "<<latency<<" ms"<<std::endl;
```
### What did you expect to see?
expect to see latency is smaller than 1ms

### What did you see instead?
```
Server listening on 0.0.0.0:50051
latency: 4.8337 ms
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
greeter_async_server and greeter_async_client run on the same machine.

**Comment by markdroth** [comment]
4ms doesn't seem that unreasonable for the first request on a channel.  Keep in mind that the channel has to do name resolution and then establish a TCP connection and do any necessary handshaking with the other side (e.g., waiting to receive the initial HTTP/2 SETTINGS frame).  Even on a loopback connection, that takes a non-zero amount of time.

Once the channel has become connected, subsequent RPCs should be much faster.

**Comment by chuan9** [comment]
@markdroth Thanks for quick response.
I did the same test on greeter_async_client2, just like you said, it should be much faster. But actually the latency is unstable and is bigger than 1ms. The test data of greeter_async_server  is as bellow:
```
Server listening on 0.0.0.0:50051
latency: 2.04062 ms
latency: 2.00486 ms
latency: 2.03156 ms
latency: 2.05159 ms
latency: 2.08163 ms
latency: 2.1131 ms
latency: 2.13766 ms
latency: 2.16675 ms
latency: 2.563 ms
latency: 2.65121 ms
latency: 2.74253 ms
latency: 2.83766 ms
latency: 2.45476 ms
latency: 3.06726 ms
latency: 3.21555 ms
latency: 3.30353 ms
latency: 3.46279 ms
latency: 3.53813 ms
latency: 3.60966 ms
latency: 3.68381 ms
latency: 3.757 ms
latency: 2.95901 ms
latency: 3.90339 ms
latency: 4.02522 ms
latency: 4.1008 ms
latency: 4.17161 ms
latency: 4.246 ms
latency: 4.31967 ms
latency: 4.39572 ms
latency: 4.46892 ms
latency: 3.48139 ms
latency: 4.60625 ms
latency: 4.67563 ms
latency: 4.74739 ms
latency: 4.81844 ms
latency: 4.88949 ms
latency: 4.95815 ms
latency: 5.02777 ms
latency: 5.10001 ms
latency: 5.17201 ms
latency: 4.04572 ms
latency: 5.3072 ms
latency: 5.38015 ms
latency: 5.45764 ms
latency: 5.53894 ms
latency: 5.61619 ms
latency: 5.6932 ms
latency: 5.76878 ms
latency: 5.84626 ms
latency: 4.56214 ms
latency: 5.98288 ms
latency: 6.05941 ms
latency: 6.13427 ms
latency: 6.21629 ms
latency: 6.57606 ms
latency: 4.89569 ms
latency: 4.92883 ms
latency: 4.96101 ms
latency: 6.36697 ms
latency: 6.41346 ms
latency: 6.43849 ms
latency: 6.4671 ms
latency: 6.49476 ms
latency: 6.52027 ms
latency: 6.54674 ms
latency: 6.58107 ms
latency: 6.63924 ms
latency: 6.67787 ms
latency: 6.68931 ms
latency: 6.7029 ms
latency: 6.71554 ms
latency: 6.72889 ms
latency: 6.74653 ms
latency: 6.76131 ms
latency: 6.76966 ms
latency: 6.77109 ms
latency: 6.78229 ms
latency: 6.78802 ms
latency: 6.79708 ms
latency: 6.80566 ms
latency: 6.83665 ms
latency: 6.845 ms
latency: 6.85358 ms
latency: 6.86431 ms
latency: 6.86955 ms
latency: 6.87957 ms
latency: 6.8903 ms
latency: 6.90126 ms
latency: 6.90675 ms
latency: 6.91724 ms
latency: 6.91795 ms
latency: 6.94299 ms
latency: 6.95872 ms
latency: 6.98328 ms
latency: 7.00903 ms
latency: 7.02333 ms
latency: 7.05457 ms
latency: 7.09081 ms
latency: 7.11632 ms
latency: 7.13944 ms

```
