### ISSUE TITLE
Key Management: Hardcoded Encryption Key 

### ISSUE THREAD

**Issue by Shakihassan** [grpc/grpc#24562]
Hardcoded encryption keys can compromise security in a way that cannot be easily remedied.
In this case, the encryption key is located at strcmp() in compression_args.cc at line 68.

the encryption key is located at in compression_args.cc at line 54.
the encryption key is located at in compression_args.cc at line 104.
the encryption key is located at strcmp() in compression_args.cc at line 41.

the encryption key is located at strcmp() in credentials.cc at line 77.
the encryption key is located at strcmp() in credentials.cc at line 143.

Reported by Fortify on demand team

**Comment by markdroth** [comment]
I'm not sure what you're running to determine this, but there are no hard-coded encryption keys in gRPC.  And nothing in the compression code has anything to do with encryption.  I suspect that whatever tool you are using to generate this is generating false positives.
