### ISSUE TITLE
Weak Encryption

### ISSUE THREAD

**Issue by Shakihassan** [grpc/grpc#24561]
The call to RC2_cbc_encrypt() at e_rc2.c line 399 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

The call to RC2_decrypt() at e_rc2.c line 278 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

The call to RC2_decrypt() at e_rc2.c line 291 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

The call to RC2_encrypt() at e_rc2.c line 261 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

The call to RC2_encrypt() at e_rc2.c line 249 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

The call to RC2_cbc_encrypt() at e_rc2.c line 405 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

**Comment by markdroth** [comment]
We need more information in order to reproduce this.  Were these errors generated during the build or at run-time?  Can you share your code?  If it happened at run-time, how are the client and server configured?

**Comment by jiangtaoli2016** [comment]
The warning is from underlying SSL library. gRPC core does not enable RC2.
