### ISSUE TITLE
A number of auth errors result in status UNAUTHENTICATED without message

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2458]
They pass through the bubble_up_error function at:
https://github.com/grpc/grpc/blob/master/src/core/security/client_auth_filter.c#L81

It's frustrating and time-wasting to try and debug these without at least a message to search for.

**Comment by ctiller** [comment]
No API change needed. #2829 gets the debug story marginally better. Will address sometime in the GA time-frame.

**Comment by hsaliak** [comment]
@ctiller Is this bug still relevant?

**Comment by jcanizales** [comment]
Is there an open issue for "the correct thing to do" as stated in #2829:

> The correct thing to do is move this string into the status response: this will take a little longer however.

**Comment by hsaliak** [comment]
@ctiller @jcanizales is the fix in #2829 good enough for GA? If so, I would like to keep the issue open but drop the milestone.

**Comment by jcanizales** [comment]
I wouldn't block GA on it.

**Comment by ncteisen** [comment]
Just poked through the code history, looks like this was fixed by #6798
