### ISSUE TITLE
How to know the protoc version in grpcio-tools(grpc python  tool)

### ISSUE THREAD

**Issue by mnff** [grpc/grpc#24602]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by mnff** [comment]
why this question closed?

**Comment by lijonath** [comment]
This is a good question and an issue I am running into as well.
