### ISSUE TITLE
unknown type name 'grpc_auth_context'

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#2461]
I get an error when trying to compile grpc release-0_10_0:
```
[...]
[C]       Compiling src/core/httpcli/httpcli.c
In file included from ./src/core/httpcli/httpcli_security_connector.h:37:0,
                 from src/core/httpcli/httpcli.c:43:
./src/core/security/security_connector.h:80:3: error: unknown type name ‘grpc_auth_context’
   grpc_auth_context *auth_context; /* Populated after the peer is checked. */
   ^
./src/core/security/security_connector.h:220:1: error: unknown type name ‘grpc_auth_context’
 grpc_auth_context *tsi_ssl_peer_to_auth_context(const tsi_peer *peer);
 ^
Makefile:2847: recipe for target 'objs/opt/src/core/httpcli/httpcli.o' failed
make[1]: *** [objs/opt/src/core/httpcli/httpcli.o] Error 1
```

**Comment by nicolasnoble** [comment]
That's interesting. 0.10.0 compiles fine on our test environments and locally. But I can see what the problem might be.

What's your compiler / environment ?

**Comment by emmenlau** [comment]
Thanks for the quick reply!
```
 ~> lsb_release -a
LSB Version:	[...]
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
~> gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
```

**Comment by nicolasnoble** [comment]
Okay now that's really odd, this is basically a very standard installation you have. And I just tried with a docker image of ubuntu:15.04, and I was able to compile the release-0_10_0 tag in there. So I'm not really sure what's going on.

**Comment by jboeuf** [comment]
If this is an upgrade, you may not have done a 'make clean' before
compiling the new 0.10 version... Could that be the issue here?

**Comment by emmenlau** [comment]
Crap, I've realized it just this very instant! It is an upgrade and I did not purge the previous destination directory, so it must have picked up headers from the 0_9 install. Sorry! Solved!
