### ISSUE TITLE
Bazel build failure because of descriptor.upbdefs on Windows

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#24626]
Building gRPC with bazel on Windows doesn't work now.

```
$ bazel build --verbose_failures :google_api_upbdefs 
ERROR: C:/cygwin64/home/builder/grpc/BUILD:3169:1: undeclared inclusion(s) in rule '//:google_api_upbdefs':
this rule is missing dependency declarations for the following files included by 'src/core/ext/upbdefs-generated/google/protobuf/descriptor.upbdefs.c':
  'bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/google/protobuf/descriptor.upbdefs.h'
Target //:google_api_upbdefs failed to build

$ bazel --version
bazel 2.2.0
```

This seems related to #23521 and removing `descriptor.upbdefs.*` from `google_api_upbdefs` results in a linker error when building test targets

```
$ bazel build //test/core/util:stack_tracer_test
ERROR: C:/cygwin64/home/builder/grpc/test/core/util/BUILD:190:1: Linking of rule '//test/core/util:stack_tracer_test' failed (Exit 1120)
udpa_annotations_upbdefs.lib(status.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
udpa_annotations_upbdefs.lib(versioning.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
udpa_annotations_upbdefs.lib(sensitive.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
google_api_upbdefs.lib(annotations.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
envoy_annotations_upbdefs.lib(deprecation.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
proto_gen_validate_upbdefs.lib(validate.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
udpa_annotations_upbdefs.lib(migrate.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
udpa_annotations_upbdefs.lib(security.upbdefs.obj) : error LNK2001: unresolved external symbol google_protobuf_descriptor_proto_upbdefinit
bazel-out/x64_windows-fastbuild/bin/test/core/util/stack_tracer_test.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by veblush** [comment]
Note that this issue happened on the VM with `kokoro-win7build-v11-prod-debug` image but it didn't with `kokoro-winserver2016-v2m-prod-debug` so it could be a kokoro image issue.

**Comment by veblush** [comment]
Note that the linking errors above happened on the VM with `kokoro-win7build-v11-prod-debug` image but it didn't with `kokoro-winserver2016-v2m-prod-debug`.

**Comment by ank4r** [comment]
I am getting the same error on fresh build after cloning the source code:

`ERROR: G:/grpc/BUILD:3214:16: undeclared inclusion(s) in rule '//:google_api_upbdefs':
this rule is missing dependency declarations for the following files included by 'src/core/ext/upbdefs-generated/google/protobuf/descriptor.upbdefs.c':
  'bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/google/protobuf/descriptor.upbdefs.h'`

bazel 3.7.1
Windows 10 enterprise version 1909

**Comment by veblush** [comment]
@ank4r Thank you for the report. We assumed that this is something caused by some old version of softwares or incompatible pairs of something. But your bazel and windows don't seem old. Can you tell more about your system (such as version of MSVC) and what you tried to build?

**Comment by devjgm** [comment]
Just to crosslink issues, this looks like it may be the same as, or related to, https://github.com/grpc/grpc/issues/24904

**Comment by ank4r** [comment]
I tried the build command from documentation for CPP:
`>>bazel build :all`

This is the log for MSVC:
`>>"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.7.3111.17308]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 443e4fa9
installDate: 9/22/2019 8:56:04 PM
installationName: VisualStudio/15.9.29+28307.1300
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
installationVersion: 15.9.28307.1300
productId: Microsoft.VisualStudio.Product.Enterprise
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Enterprise 2017
description: Microsoft DevOps solution for productivity and coordination across teams of any size
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.29
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2020-11-20T12:35:34.1998805Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.1300
catalog_id: VisualStudio/15.9.29+28307.1300
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.29
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 29
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.29+28307.1300
catalog_requiredEngineVersion: 1.18.1063.29791
properties_campaignId: 768557598.1541024384
properties_channelManifestId: VisualStudio.15.Release/15.9.29+28307.1300
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

instanceId: 4ec06358
installDate: 4/11/2019 3:08:02 PM
installationName: VisualStudio/16.7.8+30704.19
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
installationVersion: 16.7.30704.19
productId: Microsoft.VisualStudio.Product.Enterprise
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Enterprise 2019
description: Scalable, end-to-end solution for teams of any size
channelId: VisualStudio.16.Release
channelUri: https://aka.ms/vs/16/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660893#16.7.8
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660909
updateDate: 2020-11-19T17:44:58.3591279Z
catalog_buildBranch: d16.7
catalog_buildVersion: 16.7.30704.19
catalog_id: VisualStudio/16.7.8+30704.19
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 16.7.8
catalog_productLine: Dev16
catalog_productLineVersion: 2019
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 8
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 16.7.8+30704.19
catalog_requiredEngineVersion: 2.7.3136.13130
properties_campaignId: 768557598.1541024384
properties_canceled: 0
properties_channelManifestId: VisualStudio.16.Release/16.7.8+30704.19
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
