### ISSUE TITLE
Update documentation, add examples for asyncio based Python gRPC

### ISSUE THREAD

**Issue by Daniel451** [grpc/grpc#24623]
A simple Google search for `"from grpc import aio"` yields 9(!) results (as of 2020-10-30) of which 0 are relevant to start with the new asyncio based gRPC Python API.

The documentation at https://grpc.github.io/grpc/python/grpc_asyncio.html# does not cover a single example, it is basically just a list of method signatures. There is no information given about tying together all the necessary parts to build an actual client/server architecture based upon the new asyncio API.

This not very user friendly...

**Comment by Daniel451** [comment]
@lidizheng I'd totally be willing to contribute to the examples.

Unfortunately, I was unable to find some background information about end-to-end examples.

So far, it seems to me that
```
python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. async.proto
...
from grpc import aio
```
is pretty much the common way to implement a server based upon the well-known API with...
```
MyServicer(ServiceServicer):
    async def Service(self, request_iterator, context):
        ...
```
...while the new API directly accessing the stream via...
```
import grpclib
...

MyServicer(ServiceBase):
    async def Service(self, stream) -> None:
        request = await stream.recv_message()
        ...
        await stream.send_message(...)
```
...needs to be build with...
```
python -m grpc_tools.protoc -I. --python_out=. --grpclib_python_out=. async.proto
                                               ^--------------------^
```
Could the former be considered the high-level API where one simply gets the well-known `request[_iterator], context` methods while the latter is the new "low-level" API?

One thing, for example, that needed custom request iterators in the past are bi-directional streams where input needs to be cached and single responses sent for multiple iterations of the request stream. This seems to be significantly easier and more sophisticated with `.recv_message()` and `.send_message()`. Is this intended to be used for such cases? Are there any - especially negative - performance implications?

**Comment by Daniel451** [comment]
@lidizheng additional question (if I may): how would the client-side look like with `read` and `write` calls?

**Comment by lidizheng** [comment]
> Could the former be considered the high-level API where one simply gets the well-known request[_iterator], context methods while the latter is the new "low-level" API?

The official gRPC Python Protobuf generation flag is "--grpc_python_out". It works with the asyncio API, thanks for Python's tolerance of function signature change, we can assign an "async def" implementation and override parent's "def".

It's hacky, but allows the same generated code to work with py2/py3 and sync/asyncio.

> Is this intended to be used for such cases? Are there any - especially negative - performance implications?

New API supports both "async generator" and "send/receive API". There isn't any observed performance implication. After all, they are implemented in coroutines and shares most underlying logic, just have different shapes of interface.

> how would the client-side look like with read and write calls?

We designed two type of API because they works best under different scenarios. For the "async generator" API, it meant for RPC logic that the sending and receiving of messages are pretty much decoupled. But for the "send/receive" API, it works for RPCs that each request maps to one or several responses, like database queries.

If you find the application needs to write "while True", then it is a good indicator that it should change to "async generator" pattern. In your snippet, it will look like:

```python
MyServicer(ServiceBase):
    async def BidirectService(self, stream) -> None:
        async for request in stream:
            ...
            await stream.send_message(...)
```

**Comment by Daniel451** [comment]
@lidizheng thanks for the update, really appreciate the time taken! I will definitely push some examples soon.

However, I'd have some follow-up questions.

> But for the "send/receive" API, it works for RPCs that each request maps to one or several responses, like database queries.

This is, indeed, a very interesting use-case. However, with the "standard" `--grpc_python_out` flag I was unable to find the `ServiceBase` API in the generated "grpc_pb2.py" file. There was only `ServiceServicer` with the regular `request_iterator`.

How would we get the `async def BidirectService(self, stream) -> None` interface then instead of `async def Service(self, request_iterator, context)`?

Additionally, wouldn't `async for request in stream:` just allow for `1:n` (request:responses)? What if we'd like to have `n:1` or `n:m`? Shouldn't it be comparably easy to read but more modular to do something like `while stream:` and buffer incoming messages, so that the method could handle `n:m` cases?

**Comment by lidizheng** [comment]
Bidi-streaming is not simple. For cases like `n:m`, usually the requests and responses are decoupled, or they can be grouped together into an "1:1" mapping. The async generator and read/write API can work together, like using generator to send requests, but using read to fetch responses.

> There was only ServiceServicer with the regular request_iterator.

You should be able to plug `ServiceServicer` into your service implementation. If you are expecting `async def BidirectService(self, stream) -> None, it means you might confused `grpcio` and `grpclib`. Both projects implement gRPC protocol, but have different interface.

For an example service method implementation for streaming RPC, see https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests_aio/unit/server_test.py#L163.

**Comment by Daniel451** [comment]
@lidizheng thanks for the reply!

Yes, I am aware that `grpclib` is another framework implementing gRPC with the AsyncIO API. I've used this so far for the server because:

> I've only managed to achieve [stream interface with recv/send logic] with the use of grpclib for the server, which is another AsyncIO-native implementation

Thus, I used `grpcio`'s `aio` for the client and `grpclib` for the server.

I've also looked up...
```
    async def _stream_stream_evilly_mixed(self, request_iterator, context):
        assert _REQUEST == await context.read()
        request_count = 0
        async for request in request_iterator:
            assert _REQUEST == request
            request_count += 1
        assert _NUM_STREAM_REQUESTS - 1 == request_count

        yield _RESPONSE
        for _ in range(_NUM_STREAM_RESPONSES - 1):
            await context.write(_RESPONSE)
```
...but does this really allow for `n:m` mappings?

With `grpclib` I could, just for the sake of an example, loop 20x over `await stream.recv_message()` and then execute `stream.send_message()` 2x and put all of this in a `while stream` loop to let the server chunk all requests in `20:2` mappings.

In `async def _stream_stream_evilly_mixed(self, request_iterator, context)` we would loop through `async for request in request_iterator:` as long as results are being sent, right? We would need to break out of the `request_iterator` loop after 20 iterations to realize the example of `20:2` mappings.

I've struggled to see how we would realize the same thing with the `request_iterator` solution of `grpcio`.

**Comment by lidizheng** [comment]
Couple lines above, `grpcio` also offers `read` and `write` methods.

```python
    async def _stream_stream_reader_writer(self, unused_request, context):
        for _ in range(_NUM_STREAM_REQUESTS):
            assert _REQUEST == await context.read()
        for _ in range(_NUM_STREAM_RESPONSES):
            await context.write(_RESPONSE)
```
