### ISSUE TITLE
grpc build issue on Aarch64 platform

### ISSUE THREAD

**Issue by Darsh-Dev** [grpc/grpc#24630]
Not building the grpcio on aarch64 platform. 

`pip3 install grpcio
Collecting grpcio
  Using cached grpcio-1.33.2.tar.gz (20.9 MB)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3.7/site-packages (from grpcio) (1.15.0)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... \`

Hang in while loop here. Also tried with changing the version of grpc, pip (20.2.4), setuptool.

Also checking the https://www.piwheels.org/project/grpcio/#install  

FYI - Referred other grpc issue/thread before generate new issue.

**Comment by jtattermusch** [comment]
That seems odd, for how long has it been stuck? Note that building grpc python from sources can take a while.
Also, if you can reproduce this consistently, it would be nice if you could investigate where exactly the build is stuck (get a stacktrace etc.) - it seems unlikely that the build would just get stuck forever.

**Comment by jtattermusch** [comment]
I tried on aarch64 ubuntu18.04 and I was able to compile without issues (python3.8 and python3.8-dev installed) - the install takes a few minutes though because it needs to build a lot of C/C++ code.
```
python -m pip install grpcio
Collecting grpcio
  Using cached grpcio-1.35.0.tar.gz (21.2 MB)
Requirement already satisfied: six>=1.5.2 in /home/ubuntu/venv/lib/python3.8/site-packages (from grpcio) (1.15.0)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... done
  Created wheel for grpcio: filename=grpcio-1.35.0-cp38-cp38-linux_aarch64.whl size=31962308 sha256=59b5251d3a82e5117c17bccf23300a8078d4f327a68a221fe199929d01851471
  Stored in directory: /home/ubuntu/.cache/pip/wheels/e6/18/ce/dd267126a3d7e3f0dda1ef5d0e6ea1838a52c6a7c941012c35
Successfully built grpcio
Installing collected packages: grpcio
Successfully installed grpcio-1.35.0
```
