### ISSUE TITLE
Support  ImpersonatedCredentials

### ISSUE THREAD

**Issue by salrashid123** [grpc/grpc#24636]
Feature request to support `ImpersonatedCredential`  sources for GCP Credentils.

Impersonated credentials on GCP exchanges a source `access_token` for another GCP service accounts's access_token.  This mechansim is detailed here [Creating short-lived service account credentials](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials)

If a grpc client wants to execute some code as another token type, it can use its curent GCP credentials to interact with the IAM API to finally derive the new token.  Currently, there doesn't seem to be any easy way to use gRPC clients to automatically facilitate this

for ref,this type of identity exchange is in several other GCP apis (in general, not specific to grpc)

* [google-auth-python](https://google-auth.readthedocs.io/en/latest/reference/google.auth.impersonated_credentials.html)
* [google-auth-java](https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java#L88)
* [google-auth-golang](https://pkg.go.dev/google.golang.org/api/option#ImpersonateCredentials)

### Describe the solution you'd like

One possiblity is to perform an exchange explictly  as a new `grpc:GoogleImpersonatedCredentials` [here](https://github.com/grpc/grpc/blob/master/src/cpp/client/secure_credentials.cc#L104):

eg
```c++
    auto creds = grpc::GoogleDefaultCredentials();
    auto creds2 = grpc::GoogleImpersonatedCredentials(cred, "impersonated-svcaccount@iam.gserviceaccount.com");
    m_channel = grpc::CreateChannel("dialogflow.googleapis.com", creds2); 
```

### Describe alternatives you've considered

It _maybe possible_ to use [STS credentials](https://github.com/grpc/grpc/blob/master/src/cpp/client/secure_credentials.cc#L253) against GCP's  [STS endpoint](https://sts.googleapis.com/v1beta/token) to do this (i.,e exchange gcp_access token for another gcp_access token via STS instead of IAMCredentials api

**Comment by salrashid123** [comment]
@nicolasnoble (sorry, i'm unsure how i assigned this issue over (unless this is blunderbuss/autoassining)

**Comment by markdroth** [comment]
Jiangtao, can you please advise, or redirect as appropriate?  Thanks!

**Comment by jiangtaoli2016** [comment]
@salrashid123  I think STS credentials can achieve your needs. STS credentials allow you to to config token exchange service URI to create short-lived service account credentials. Can you use STS credentials instead?

**Comment by jiangtaoli2016** [comment]
@salrashid123  You need ImpersonatedCredentials in c++ grpc, right?  For other languages, we can use Google auth library.

I saw you have contributed to Java auth library to add ImpersonatedCredentials (https://github.com/googleapis/google-auth-library-java/pull/211). If you prefer, you can make a PR to add in grpc repo. We can help review.

**Comment by salrashid123** [comment]
yep, its just in context with cpp (as you mentioned, the other languages can use google auth libraries to source in the impersonated credentials).

I would contribute code to support this but i really don't know cpp in any meaningful detail.

however, i'd be more than happy to help test and discuss/define specifications on its operations if anyone is willing todo the PR.
