### ISSUE TITLE
ServerContextBase::CompletionOp potentially unlocking mutex after destroy

### ISSUE THREAD

**Issue by MaxBrinegar** [grpc/grpc#24644]
### What version of gRPC and what language are you using?
1.33.2 with C++

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 19.0.24234.1

### What did you do?
Calling Next on the completion queue caused `"Mutex unlocked when destroyed or not locked"` fatal errors to begin reporting from RawLogVA after updating gRPC package from 1.29.xx to 1.33.2. Integration tests that read and write continuously to a completion queue started failing at random intervals of instantly to 5 or so minutes.

### What did you expect to see?

No fatal error being reported from RawLogVA due to `"Mutex unlocked when destroyed or not locked"` while calling Next on the completion queue.

### What did you see instead?

RawLogVA  being called with a fatal error of `"Mutex unlocked when destroyed or not locked"` which crashed the running grpc-based application

Stack:
AzPubSubProxy.exe!`anonymous namespace'::RawLogVA(absl::lts_2020_02_25::LogSeverity severity, const char * file, int line, const char * format, char * ap) Line 182	C++
AzPubSubProxy.exe!absl::lts_2020_02_25::raw_logging_internal::RawLog(absl::lts_2020_02_25::LogSeverity severity, const char * file, int line, const char * format, ...) Line 210	C++
AzPubSubProxy.exe!absl::lts_2020_02_25::Mutex::Unlock() Line 1670	C++
AzPubSubProxy.exe!gpr_mu_unlock(__int64 * mu) Line 61	C++
AzPubSubProxy.exe!grpc_core::MutexLock::~MutexLock() Line 60	C++
AzPubSubProxy.exe!grpc::ServerContextBase::CompletionOp::FinalizeResult(void * * tag, bool * status) Line 189	C++
AzPubSubProxy.exe!grpc::CompletionQueue::AsyncNextInternal(void * * tag, bool * ok, gpr_timespec deadline) Line 65	C++
AzPubSubProxy.exe!grpc::CompletionQueue::Next(void * * tag, bool * ok) Line 172	C++
AzPubSubProxy.exe!azpubsub::proxy::Service<azpubsub::hostproxy::HostProxy::WithAsyncMethod_SendMessage<azpubsub::hostproxy::HostProxy::Service>>::CreateRequest::__l10::<lambda>() Line 79	C++

Complete Error:
buffer	0x00000088e98fecc0 "[mutex.cc : 1671] RAW: Mutex unlocked when destroyed or not locked: v=0xdddddddd\n"	char[3000]

Observation:
Could it be possible that [deleting `this` ](https://github.com/grpc/grpc/blob/master/src/cpp/server/server_context.cc#L188) causes `mu_` to be destroyed and when we [exit scope](https://github.com/grpc/grpc/blob/master/src/cpp/server/server_context.cc#L189) the lock attempts to unlock a destroyed mutex? It seems [this code path was updated recently](https://github.com/grpc/grpc/commit/1dd7a01bc71c2279b0291017db886d14b6b5ed1d)

**Comment by MaxBrinegar** [comment]
#24680

**Comment by vjpai** [comment]
Thanks for finding this issue. I'll send in an PR to resolve it by checking the condition within the lock and actually doing the unref outside the lock.

**Comment by MaxBrinegar** [comment]
Thank you!
