### ISSUE TITLE
grpc dns解析中的GRPC_DNS_RESOLVER这个参数的作用是什么，可以设置哪些值 ？

### ISSUE THREAD

**Issue by Nemohaha** [grpc/grpc#24662]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by lidizheng** [comment]
Take a look at https://github.com/grpc/grpc/blob/master/doc/environment_variables.md:

```
GRPC_DNS_RESOLVER Declares which DNS resolver to use. The default is ares if gRPC is built with c-ares support. Otherwise, the value of this environment variable is ignored. Available DNS resolver include:
* ares (default on most platforms except iOS, Android or Node)- a DNS resolver based around the c-ares library
* native - a DNS resolver based around getaddrinfo(), creates a new thread to perform name resolution
```

Next time, please use English, and fill out the description.
