### ISSUE TITLE
Add an appropriate description to the podspec

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2466]
Lack of a [description field](https://github.com/fcanas/Sequence/blob/master/Sequence.podspec#L14) results in Cocoapods reusing the README.md of the repo root: https://cocoapods.org/pods/gRPC

This is inappropriate because:
* It points to instructions to install the C library on the user's machine.
* It talks of "this repository", which doesn't make sense in the context of the Podspec page.
* It points to specific instructions for all languages, when Objective-C is the immediate interest of a user reading the Podspec page.
* The link to Objective-C-specific instructions [is broken](https://raw.githubusercontent.com/grpc/grpc/release-0_9_1-objectivec-0.5.1/src/objective-c), due to Cocoapods getting the README.md file from `raw.githubusercontent.com`.
* It talks of synchronous calls that aren't relevant to this library.

**Comment by jcanizales** [comment]
We should also specify `social_media_url` to point people to the mail list, and `deprecated_in_favor_of = 'gRPC/RxLibrary'` in the old standalone RxLibrary pod.

**Comment by hsaliak** [comment]
@jcanizales checked with Cocoapods team on this issue. Based on the discussion, marking this as infeasible.
