### ISSUE TITLE
client_unary_call.h references CallOpSendInitialMetadata but does not include call_op_set.h

### ISSUE THREAD

**Issue by Archimagus** [grpc/grpc#24676]
#What version of gRPC and what language are you using?
v.1.3.3.x 
ee5b762f33a42170144834f5ab7efda9d76c480b
Also exists in latest master

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019 MSBuild via Cmake

### What did you do?
clone gRPC
md .build
cd .build
cmake .. -G "Visual Studio 16 2019"
cmake --build . --config Release -j8
cmake .. -DgRPC_INSTALL=ON -DgRPC_SSL_PROVIDER=module
cmake --install . --prefix ../../.grpcInstall

### What did you expect to see?
include and library files that work when included and referenced in a project

### What did you see instead?
client_unary_call.h(53,15): error C3861: 'CallOpSendInitialMetadata': identifier not found
client_unary_call.h(55,15): error C3861: 'CallOpClientSendClose': identifier not found

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
if I add 
#include <grpcpp/impl/codegen/call_op_set.h>
to the bottom of the includes list in client_unary_call.h then everything builds and works as expected.

**Comment by veblush** [comment]
@Archimagus Thanks for the report and I reproduced this. This will be fixed by #24889.
