### ISSUE TITLE
/sys/class/dmi/id/product_name File absent on WSL2 leading to log

### ISSUE THREAD

**Issue by meztez** [grpc/grpc#24675]
https://github.com/grpc/grpc/blob/8c60c084ef35649b33b858d3959943b8124b9e63/src/core/lib/security/credentials/alts/check_gcp_environment.cc#L60

Should this be dropped to `GRR_INFO`?

Debian on WSL2 (and probably other distro also running on Windows Subsystem Linux), do not have a "/sys/class/dmi/id/product_name" file. ~~You get the message everytime when using `gdc` for credentials.~~ When you load library, so not so bad.

I thought I should mention it since I could not find a way to shut it off via the log severiry.

**Comment by yihuazhang** [comment]
It makes sense to use `GPR_INFO` to reduce the noise. Let me send a PR to fix it now.
