### ISSUE TITLE
Code examples using custom serializers

### ISSUE THREAD

**Issue by bjornbouetsmith** [grpc/grpc#24687]
### Is your feature request related to a problem? Please describe.

I have tried searching the internet for examples, but all the examples with custom serialization was using the byte array methods.

### Describe the solution you'd like
It would be nice with a code example that shows how to use gRPC with a custom serializer and not using byte[] arrays, i.e.
using the marshaller that expects:
Action<Something, SerializationContext> as serializers.

**Comment by bjornbouetsmith** [comment]
Could we have an update on this?

**Comment by veblush** [comment]
We don't have bandwidth to write this example. Could you help on this? or Flatbufer's gRPC [integration](https://github.com/google/flatbuffers/blob/master/include/flatbuffers/grpc.h) might be useful as a practical example using the custom serializer.
