### ISSUE TITLE
C# generator overwrites files with same *.proto in different folders/namespaces

### ISSUE THREAD

**Issue by saltatory** [grpc/grpc#24697]
### What version of gRPC and what language are you using?

Grpc.Tools 2.27.0 via Grpc.AspNetCore 2.27.0

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

See above

### What did you do?

1. Download the Google FHIR protbuf set from git@github.com:google/fhir.git
2. Run `Build -> Build Solution` which runs the included `protoc` build targets.
3. While watching the build products e.g. in `obj/Debug/netcoreapp3.1` notice that files generated from identically named `*.proto*` files (e.g. `proto/google/fhir/proto/r4/codes.proto` and `proto/google/fhir/proto/stu3/codes.proto`) overwrite each other

### What did you expect to see?

* EITHER files organized into separate folders based on their C# namespace
* OR files with naming prefixes by C# namespace

### What did you see instead?

See above. Files got overwritten resulting in lots of compilation errors.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

I was working in Rider

**Comment by saltatory** [comment]
I WAS on `2.27.0` of Grpc.Tools (and others). When I upgraded to `2.33.1` this problem appeared to be resolved.

**Comment by jtattermusch** [comment]
I think this was fixed by https://github.com/grpc/grpc/pull/22869 (available starting from 2.31.x I think).
