### ISSUE TITLE
Grpc.Tools: Parallelize execution of protoc from MSBuild

### ISSUE THREAD

**Issue by saltatory** [grpc/grpc#24698]
### Is your feature request related to a problem? Please describe.

I have my .NET project configured as follows:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>Ziglet.GRPC</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Protobuf Include="Protos\**\*.proto" ProtoRoot="Protos">
      <GrpcServices>Server</GrpcServices>
      <Access>Public</Access>
      <ProtoCompile>True</ProtoCompile>
      <CompileOutputs>True</CompileOutputs>
      <OutputDir>obj\Debug\netcoreapp3.1\</OutputDir>
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.33.1" />
  </ItemGroup>
</Project>
```

### Describe the solution you'd like

The `Protos` directory contains a fairly large number of `*.proto` files. I would LOVE it if the `protoc` command invoked by the `Protobuf` element ran in parallel.

### Describe alternatives you've considered

I could do this outside the C# project, manually at the command line e.g. via `xargs` or similar but that's a PITA!

Additional note: I notice that MSBuild is running `protoc` one file at a time. When I run this in `bash` as the following:

```bash
$ protoc ./**/*.proto --csharp_out=../obj
```

... it's MUCH faster.
### Additional context

No additional context.

**Comment by jtattermusch** [comment]
The code for Grpc.Tools msbuild integration is open source - feel free to come up with suggestions what to change in order to make the build work in parallel (PR would be ideal). 

Also, once there is a prototype (and if this is feasible at all), it would be good to compare build times for e.g. 1000 .proto files in a project with and without parallel execution.

**Comment by jtattermusch** [comment]
I'm closing this since there seems to be no progress on this. If someone wants to address this in the future, we can reopen.
