### ISSUE TITLE
Unable to share common proto between different projects 

### ISSUE THREAD

**Issue by smartaquarius10** [grpc/grpc#24699]
I'm migrating one of my MVC based .net framework api to grpc. Currently, I have one entity class in model project which is referenced in main and dbcontext project. Now, I'm trying to make same like this with grpc .net core project where, I have one main project which has service proto files and a model class library project having messages proto files.

In my main project I wanted to use this message protos, but the moment I run this command on my main project

dotnet grpc add-file "path to message proto"

It edits the .csproj of main project and add this

<ItemGroup> <Protobuf Include="..\Watcher\Protos\entities.proto" Link="Protos\entities.proto" GrpcServices="Client" /> </ItemGroup>

This adds a copy of this file entities.proto into the Protos folder of main project as well. Now, the moment I try to use it I get ambiguous conflicts and type casting errors: CS04236 & CS00029.

This is obvious because now indirectly, I have 2 proxy classes build by the proto file of same name and same namespace.

Is there anyway to use the proto file which is build in one project and only referenced in other projects like the way we do in .net framework MVC projects.

Please help!!

**Comment by jtattermusch** [comment]
The new issue form asks to not post usage questions, but only suspected grpc issues, please use e.g. stackoverflow next time.

to answer your question:
To share a .proto file between two projects, one of the possible approaches is to use "class library" project that has all the .protos you need and then to reference that project from all other projects that need to use the .protos (if you include the same .proto multiple times, you'll get a conflict as there's going to be two copies of the generated files).
