### ISSUE TITLE
grpc comiplation is failing in linux 7.X version

### ISSUE THREAD

**Issue by Rohit2387** [grpc/grpc#24705]
while compiling grpc in linux 7.X version below error is coming, could any one help?
CMake Error at CMakeLists.txt:251 (include):
  include could not find load file:

    cmake/abseil-cpp.cmake

CMake Error at CMakeLists.txt:252 (include):
  include could not find load file:

    cmake/address_sorting.cmake

CMake Error at CMakeLists.txt:253 (include):
  include could not find load file:

    cmake/benchmark.cmake

CMake Error at CMakeLists.txt:254 (include):
  include could not find load file:

    cmake/cares.cmake

CMake Error at CMakeLists.txt:255 (include):
  include could not find load file:

    cmake/gflags.cmake

CMake Error at CMakeLists.txt:256 (include):
  include could not find load file:

    cmake/protobuf.cmake

CMake Error at CMakeLists.txt:257 (include):
  include could not find load file:

    cmake/re2.cmake

CMake Error at CMakeLists.txt:258 (include):
  include could not find load file:

    cmake/ssl.cmake

CMake Error at CMakeLists.txt:259 (include):
  include could not find load file:

    cmake/upb.cmake

CMake Error at CMakeLists.txt:260 (include):
  include could not find load file:

    cmake/zlib.cmake

CMake Error: File /root/grpc-master/cmake/gRPCConfig.cmake.in does not exist.
CMake Error at CMakeLists.txt:16269 (configure_file):
  configure_file Problem configuring file

CMake Error: File /root/grpc-master/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16298 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16307 (generate_pkgconfig)

CMake Error: File /root/grpc-master/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16298 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16317 (generate_pkgconfig)

CMake Error: File /root/grpc-master/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16298 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16327 (generate_pkgconfig)

CMake Error: File /root/grpc-master/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16298 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16337 (generate_pkgconfig)

CMake Error: File /root/grpc-master/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16298 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16347 (generate_pkgconfig)

**Comment by jtattermusch** [comment]
What do you mean by "linux 7.x"?  Also the error messages you posted seem suspicious, so I'm not really sure what are the commands you ran. Also you don't mention what grpc version you tried.

I will close for now as there's not enough info to tell what's wrong. We can reopen once you provide a better description.

**Comment by eoswald** [comment]
@jtattermusch Can we reopen this? I get the same thing while following the build instructions here: https://github.com/grpc/grpc/blob/master/BUILDING.md#building-with-cmake

```
~/grpc-cmake/cmake/build$ cmake ../.. -DBUILD_SHARED_LIBS=ON
CMake Error at CMakeLists.txt:250 (include):
  include could not find load file:

    cmake/abseil-cpp.cmake


CMake Error at CMakeLists.txt:251 (include):
  include could not find load file:

    cmake/address_sorting.cmake


CMake Error at CMakeLists.txt:252 (include):
  include could not find load file:

    cmake/benchmark.cmake


CMake Error at CMakeLists.txt:253 (include):
  include could not find load file:

    cmake/cares.cmake


CMake Error at CMakeLists.txt:254 (include):
  include could not find load file:

    cmake/protobuf.cmake


CMake Error at CMakeLists.txt:255 (include):
  include could not find load file:

    cmake/re2.cmake


CMake Error at CMakeLists.txt:256 (include):
  include could not find load file:

    cmake/ssl.cmake


CMake Error at CMakeLists.txt:257 (include):
  include could not find load file:

    cmake/upb.cmake


CMake Error at CMakeLists.txt:258 (include):
  include could not find load file:

    cmake/zlib.cmake


CMake Error: File /home/eoswald/grpc-cmake/cmake/gRPCConfig.cmake.in does not exist.
CMake Error at CMakeLists.txt:16415 (configure_file):
  configure_file Problem configuring file


CMake Error: File /home/eoswald/grpc-cmake/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16444 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16453 (generate_pkgconfig)


CMake Error: File /home/eoswald/grpc-cmake/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16444 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16463 (generate_pkgconfig)


CMake Error: File /home/eoswald/grpc-cmake/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16444 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16473 (generate_pkgconfig)


CMake Error: File /home/eoswald/grpc-cmake/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16444 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16483 (generate_pkgconfig)


CMake Error: File /home/eoswald/grpc-cmake/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:16444 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16493 (generate_pkgconfig)


-- Configuring incomplete, errors occurred!
See also "/home/eoswald/grpc-cmake/cmake/build/CMakeFiles/CMakeOutput.log".

```

**Comment by jtattermusch** [comment]
The errors you're mentioning are very odd.
The files mentioned under "include could not find load file" are simply files in this repository: https://github.com/grpc/grpc/blob/master/cmake/abseil-cpp.cmake  
No idea why they would be missing but it seems that something is really wrong with your test environment.

You'd need to provide a working reproduction for someone to be able to look in to this (I have no idea how you could get these kind of errors on a healthy system with a healthy grpc clone).

**Comment by eoswald** [comment]
You're right, I retried on a fresh Ubuntu 20.04 WSL instance and it built fine.
