### ISSUE TITLE
The service listens for only one ipv6 port, not the ipv4 port, resulting in a service exception

### ISSUE THREAD

**Issue by NiuLk** [grpc/grpc#24712]
When I start a service on a Linux server through server.add_secure_port ('127.0.0.1:8084', server_credentials), the service listens for only one ipv6 port, not the ipv4 port, resulting in a service exception, and how to resolve it

`server.add_secure_port('127.0.0.1:8084',server_credentials)`

![1](https://user-images.githubusercontent.com/19512481/98662306-8b04cb80-2382-11eb-85c9-87c1ebb9368d.png)

**Comment by veblush** [comment]
@NiuLk Although it says tcp6, it's actually an ipv4 address as an IPv4-mapped IPv6 addresses and that's why you can see `127.0.0.1` there and it should be accessible from ipv4 address. (e.g. telnet -i4 127.0.0.1 8084)

**Comment by SiegeSailor** [comment]
Sorry, I think this is a Docker networking issue. Changing `127.0.0.1` to `0.0.0.0`/`[::]` fixed my issue 😅

<details><summary>Details</summary>
<p>
@veblush 
Hello 👋, I am facing a similar issue. I have a Docker container (Orbstack) running on my macOS using `--network host` containing multiple Python gRPC servers. The following output is from the container's terminal:

```shell
root@orbstack 
> netstat -tulpn 
tcp6       0      0 127.0.0.1:55005         :::*                    LISTEN      1392/python
tcp6       0      0 127.0.0.1:55004         :::*                    LISTEN      2065/python
tcp6       0      0 127.0.0.1:55003         :::*                    LISTEN      1355/python
tcp6       0      0 127.0.0.1:55002         :::*                    LISTEN      1360/python
tcp6       0      0 127.0.0.1:55001         :::*                    LISTEN      1357/python
tcp6       0      0 :::3000                 :::*                    LISTEN      2123/next-server (v
```

Then, on my host:

```shell
user@MacBook-Pro source % telnet -4 127.0.0.1 55003
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

I tried to connect through a gRPC client on my host using different combinations. None of them worked:

- Server: `add_insecure_port(address="[::]:<port>")` - Client: `insecure_channel(target="[::1]:<port>")`
- Server: `add_insecure_port(address="127.0.0.1:<port>")` - Client: `insecure_channel(target="127.0.0.1:<port>")`
- Server: `add_insecure_port(address="[::]:<port>")` - Client: `insecure_channel(target="127.0.0.1:<port>")`
- Server: `add_insecure_port(address="127.0.0.1:<port>")` - Client: `insecure_channel(target="[::1]:<port>")`

Some error messages:

```
gRPC Error: StatusCode.UNAVAILABLE
failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55001: Failed to connect to remote host: Connection refused
<AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55001: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-12-10T16:49:28.670787-05:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55001: Failed to connect to remote host: Connection refused"}"
>
```

```
StatusCode.UNAVAILABLE
failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::1%5D:55001: Failed to connect to remote host: Connection refused
Error: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::1%5D:55001: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-12-10T16:50:21.000172-05:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::1%5D:55001: Failed to connect to remote host: Connection refused"}"
>
```

However, I also have gRPC clients running in the container, and they can talk to the gRPC servers:

- Server: `grpc.aio.server().add_insecure_port(address="127.0.0.1:<port>")`
- Client: `grpc.aio.insecure_channel(target="127.0.0.1:<port>")`

And, the following also works on my host:

```shell
user@MacBook-Pro source % telnet -4 127.0.0.1 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

Dependencies (both host and container):

- `grpcio`: 1.60.1
- `grpcio-tools`: 1.60.1
- `protobuf`: 4.25.2
- `python`: 3.10.12
</p>
</details>
