### ISSUE TITLE
C# Custom CompressionProviders in Grpc.Core

### ISSUE THREAD

**Issue by alexvazquez** [grpc/grpc#24721]
I have a Server using `Grpc.Net.Client ` and was able to create my custom Compression Provider.  My Client is using `Grpc.Core` because is using `.NET Framework 4.6` and I have been trying to find a way to add customer compression provider or at least trace on the client when decompression and compression happen without any success.

This is my client code:
```

string s = GetRootCertificates();
            var channel_creds = new SslCredentials(s);

            Channel channel = new Channel("localhost:5001", channel_creds, new ChannelOption[] {
                new ChannelOption(ChannelOptions.MaxReceiveMessageLength, 10 * 1024 * 1024), //plenty of room
                new ChannelOption("grpc.default_compression_algorithm",2),
                new ChannelOption("grpc.default_compression_level",(int)CompressionLevel.High),
            });

            var invoker = channel.Intercept(new ClientLoggerInterceptor());

            var client = new Greeter.GreeterClient(invoker);

            var headers = new Metadata();
            headers.Add("grpc-internal-encoding-request", "gzip");
            headers.Add("requester", "client");

            // deadline is the timeout in sedconds
            var callOptions = new CallOptions().WithHeaders(headers).WithDeadline(DateTime.UtcNow.AddSeconds(15)).WithWaitForReady(false);

            DataSetResponse response = await client.GetPatientInfoAsync(new PatientInfoRequest { Uid = "DF24387B-815D-4E06-AD76-9E9E3C255118", LoadContractsOnDemand = false }, callOptions);
```
Does anyone know how to add a Customer Compression provider and how to add a way to trace when decompression and compression happens on client side?

**Comment by jtattermusch** [comment]
Grpc.Core doesn't support custom compression provider (like grpc-dotnet does) and there is no plan to add such support (since the compression is provided by the native C core library).
If you want to use custom compression providers, you need to use Grpc.Net.Client and Grpc.AspNetCore.Server

**Comment by alexvazquez** [comment]
@jtattermusch thanks a lot for your answer, appreciate it so much. Is it possible in client-side to get a log when the compression and decompression happens? Thanks
