### ISSUE TITLE
thread_stress_test leaks

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2475]
Example: https://grpc-testing.appspot.com/job/gRPC_pull_requests/949/ asan C++ build, which is otherwise a purely cosmetic PR.

**Comment by ctiller** [comment]
For reference, in case someone gets to this before me... one of the call instances is not fully un-reffed.
The reason code for the ref is "completing". Suspect we're either:
- missing an edge in completion_queue.c
- somehow not draining the CQ
- something else

I haven't spotted the why yet.

**Comment by ctiller** [comment]
Fixed by #2485
