### ISSUE TITLE
grpc memory usage increase with request in threads.

### ISSUE THREAD

**Issue by Xin2Luo** [grpc/grpc#24759]
### What version of gRPC and what language are you using?
server: C++
client: Python/C++

### What operating system (Linux, Windows,...) and version?
windows7 64

### What runtime / compiler are you using (e.g. python version or version of gcc)
visual studio 2015

### What did you do?
I have much status of devices that need to be synced, so I will send requests to the server in one second. I found that with the request increasing, the memory usage of server increasing until all the memory used. 

I simplify my program to receive my request and do nothing but return status OK. I found that the memory increasing about 3MB/s for my request in 3 threads.

My grpc version is 1.72, I also try to build the latest grpc, and I encounter the same issue.
The Python and C++ stub has the same issue if send requests in threads.

Could you please help to check or tell me what's wrong with my code?  

```
class TestRPCService :public sig::controller_service::SigControlService::Service
{
public:
    TestRPCService() {
        int32_t port = 6566;
        std::string address = "0.0.0.0:" + std::to_string(port);

        m_serverBuilder.AddListeningPort(address, grpc::InsecureServerCredentials());
        m_serverBuilder.RegisterService(this);
    }
    ~TestRPCService() {

    }
    
    void start() {
        m_server = m_serverBuilder.BuildAndStart();
        m_server->Wait();
    }
    void stop() {
        m_server->Shutdown();
        m_server.reset();
    }

    virtual ::grpc::Status queryStatusInfo(::grpc::ServerContext* context, const ::sig::controller_service::QueryDeviceStatusInfoRequest* request, ::sig::controller_service::QueryDeviceStatusInfoResponse* response) override {
        return Status::OK;
    }

    grpc::ServerBuilder                                        m_serverBuilder;
    std::unique_ptr<grpc::Server>                              m_server;
};

int main(int argc, char *argv[]) {
    TestRPCService service;
     service.start();
    return 0;
}

```
My python client test code:
```
class ControllerServiceStub(object):
    def __init__(self, channel):
        self._stub = sig_controller_service_pb2_grpc.SigControlServiceStub(channel)

    def query_device_status(self, index):
        request = sig_controller_service_pb2.QueryDeviceStatusInfoRequest(deviceIndex=index)
        resp = self._stub.queryStatusInfo(request)
        return {'status': DeviceStatus(resp.status)}


if __name__ == "__main__":
    address = '127.0.0.1'
    port = 6566
    channel = grpc.insecure_channel('{}:{}'.format(address, port), options=[
        ('grpc.max_receive_message_length', 50 * 1024 * 1024)])
    stub = ControllerServiceStub(channel=channel)
    stub1 = ControllerServiceStub(channel=channel)
    stub2 = ControllerServiceStub(channel=channel)
    import time
    import threading

    times = 100000


    def test(stub, index):
        for i in range(times):
            status = stub.query_device_status(index)
            print(status)


    t1 = threading.Thread(target=test, args=(stub, 0))
    t2 = threading.Thread(target=test, args=(stub1, 0))
    t3 = threading.Thread(target=test, args=(stub2, 2))
    t1.start()
    t2.start()
    t3.start()

    t1.join()
    t2.join()
    t3.join()
```

### What did you expect to see?
The memory usage of server not increasing with requests.

### What did you see instead?
Memory usage increasing until all the memory used.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment]
@Xin2Luo Can you check the version of gRPC? (You told 1.72 but 1.27 I guess?) and can you do some memory analysis on C++ server? (Visual Studio may have a built-in memory analyzer) 

@lidizheng Can you check the python client source above? I don't spot an obvious flaw there but chances are that the client just created a new channel on every request, which could increase the server's memory footprint.

**Comment by Xin2Luo** [comment]
@veblush  The grpc version of C++ is 1.72, I tried to use visual studio to analyze memory, but nothing found. I will try it again

**Comment by veblush** [comment]
@Xin2Luo Can you recheck the version? The latest one is 1.33.2 as of today.

**Comment by sayeesh** [comment]
@veblush What do you mean by "I don't spot an obvious flaw there but chances are that the client just created a new channel on every request, which could increase the server's memory footprint."
What exactly do u mean by creating new channel?

**Comment by veblush** [comment]
@sayeesh Not sure how gRPC Python handles this but the client can keep creating a channel (or connection) for each request. It causes a server to have many connections which ends up allocating much memory.

**Comment by jyggen** [comment]
Seeing something similar as well, memory keeps creeping up slowly but surely over time on a Python client <-> Python server setup. The channel is created once on app startup and is reused, so that _shouldn't_ be the cause. Using the latest gRPC package om both ends, will try and see if I can get some minimal code that reproduces it.

**Comment by Xin2Luo** [comment]
Hi guys,
     I really find that the memory may service issue, either C++ or Python client, the memory is increasing when call with multi-threads.

**Comment by veblush** [comment]
I'm closing this but please feel free to reopen it if required. If you think there is something gRPC needs, give us a small repro and memory footprint you measured as you increased the number of threads.

**Comment by HaoLiuHust** [comment]
I also met this problem
