### ISSUE TITLE
improvement: reduce grpc library load&init time

### ISSUE THREAD

**Issue by qlisc** [grpc/grpc#24771]
### Is your feature request related to a problem? Please describe.

There are dozens of global/static instances used in grpc library e.g. https://github.com/grpc/grpc/blob/master/src/core/lib/surface/completion_queue.cc#L50. These global/static objects are always initialized at app startup time even they are not used. It increases grpc library load and initialization time. These extra time might not matter to desktop app. But it matters to mobile app where app launch time impacts mobile user experience.

### Describe the solution you'd like

1. Move these static objects into function scope to avoid initializing these instances during app startup. 
2. Or create empty constructor and called during app startup to reduce initialization time. 

### Additional context
Add any other context about the feature request here.

**Comment by veblush** [comment]
@qlisc Could you please provide the evidence (e.g. profiling result) to support your claim? Maybe there is room to improve the startup time but the code you spotted isn't expected to spend too much time.

**Comment by qlisc** [comment]
@veblush thanks for the quick response. Yes, running individual static initialization code won't take significant time. But these statics init time can add up  and can end up cost few 10 ms in mobile app startup. 
Here is the doc
https://chromium.googlesource.com/chromium/src/+/master/docs/static_initializers.md on why banning static initializers

**Comment by veblush** [comment]
Thanks for the info but I don't think that we can apply that guide to this specific trace because it should build a linked list to traverse all traces later.
