### ISSUE TITLE
The received message bytes are invalid/junk in interceptor's POST_RECV_MESSAGE event

### ISSUE THREAD

**Issue by qlisc** [grpc/grpc#24770]
### What version of gRPC and what language are you using?
Grpc v1.21.0 C++

### What operating system (Linux, Windows,...) and version?
IOS 11.4 and MacOS 10.15.7

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 12.0.0 (clang-1200.0.32.21)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

registered the interceptor and process the message in interceptor event.
### What did you expect to see?
no crash all the time

### What did you see instead?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

Sometime we see the received message buffer CallOpRecvMessage:: message_ is invalid in interceptor POST_RECV_MESSAGE event.  message_ contains junk bytes.

Dig into the code, looks like "if (message_ == nullptr)" check might not be enough to indicate if message_ is valid https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/call_op_set.h#L477.  The message_ could be invalid if status is false or deserialization failed in https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/call_op_set.h#L448.  

Should we check got_message flag instead of "if (message_ == nullptr)" for CallOpRecvMessage:: message_  validation?

**Comment by yashykt** [comment]
There already seems to be a check here for got_message - https://github.com/grpc/grpc/blob/600dd1b86c1c0b4cf4bafd21391f15f4b44b0738/include/grpcpp/impl/codegen/call_op_set.h#L480

Is there a quick test that you can provide for this to help reproduce this?

**Comment by qlisc** [comment]
Thanks @yashykt. I think you are right. The intercepter internal recv message buffer should be null if !got_message. The crash could be related to our implementation or other places. You can close the ticket. We are not able to reproduce the crash right now. I will comment/reopen this ticket if we have a reliable reproduce of the crash in the future. 

btw, if !got_message, do you think it's a good idea to avoid to call interceptor_methods->AddInterceptionHookPoint(
        experimental::InterceptionHookPoints::POST_RECV_MESSAGE) as well? https://github.com/grpc/grpc/blob/600dd1b86c1c0b4cf4bafd21391f15f4b44b0738/include/grpcpp/impl/codegen/call_op_set.h#L478
So if anything wrong with received message, POST_RECV_MESSAGE won't be triggered in client's interceptor's events.

**Comment by yashykt** [comment]
> do you think it's a good idea to avoid to call interceptor_methods->AddInterceptionHookPoint(
experimental::InterceptionHookPoints::POST_RECV_MESSAGE) as well?

I think the original intention behind this was that the interceptors would use the nullptr return value to know that a read operation had failed, and I think that is useful in certain cases.
