### ISSUE TITLE
Julia language implementation

### ISSUE THREAD

**Issue by mkschulze** [grpc/grpc#24786]
### Is your feature request related to a problem? Please describe.
There is interest in building an interface to a popular Graph Database in Julia as a community project (MIT), but the ClientAPI to the DB requires gRPC methods for channel/session/transaction etc., which are not available in Julia.  

### Describe the solution you'd like
A maintained Julia implementation would allow for all the benefits Julia has to offer like Multiple Dispatch and others and could be used as the connection layer instead of calling into Python for example.

### Describe alternatives you've considered
The only alternative I can see would be to either call into Python, or build a minimal gRPC Julia pkg, with just the required methods.

### Additional context
There was an approach to build a Julia pkg called [gRPC.jl](https://github.com/tanmaykm/gRPC.jl), but the pkg and it's dependencies are abandoned and even removed from the pkg registry.

**Comment by markdroth** [comment]
Unfortunately, this is not a language in which we have staffing or expertise to support.  However, if someone from the Julia community wants to contribute a Julia gRPC API, we can help facilitate the work, clarify requirements, do API reviews, set up interop tests, etc.  If that's something you're interested in, please reach out to @a11r.

**Comment by mkschulze** [comment]
Ok, I'm passing it further into the community, maybe somebody would like to give it a go as it's above my skill level as well. 

Thanks, for offering the help!

**Comment by mkschulze** [comment]
Hello @a11r, we @Humans-of-Julia/graknclient-team are considering to implement gRPC in Julia  and it would be great to get some guidance from you. What would be the preferred way to get into conversation with you?
We are active on [discord here](https://discord.gg/C5h9D4j) to chat, or via e.mail or better here?

We currently wonder if this would be good approach:

- using [Clang.jl](https://github.com/JuliaInterop/Clang.jl) to wrap the shared C library
- using [LibCURL.jl](https://github.com/JuliaWeb/LibCURL.jl) as a HTTP/2 layer
- using [StructTypes.jl](https://github.com/JuliaData/StructTypes.jl) to do the serialization
- somehow deal with the [low level operations](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h)
- maybe extend [Protobuf.jl](https://github.com/JuliaIO/ProtoBuf.jl) to also generate the StructTypes if possible

Thanks for getting back to us.

**Comment by mkschulze** [comment]
@markdroth how could we ideally get in touch with @a11r ? We would like to further discuss things.

**Comment by markdroth** [comment]
I've sent him a message internally asking him to get back to you.

**Comment by mkschulze** [comment]
Hi @markdroth & @a11r 
we made the following packages work again:
[HTTP/2](https://github.com/tanmaykm/HTTP2.jl)
[HPack](https://github.com/tanmaykm/HTTP2.jl)

That was required for [gRPC.jl](https://github.com/tanmaykm/gRPC.jl) to work again.
It works now, but we don't know in which state it is yet.
Also, one of our team members has owner permissions to these repos now, and we would like to make this stable and up to date again.

As you offered to `help facilitate the work, clarify requirements, do API reviews, set up interop tests`, we would be very interested in this.

If you prefer E-Mail, I'm reachable at mks[at]e.mail.de

Thank you!

**Comment by A1-Mathematik** [comment]
I would be interested in helping implement this. How can I help?

**Comment by mkschulze** [comment]
> I would be interested in helping implement this. How can I help?

There is a working client here: https://github.com/JuliaComputing/gRPCClient.jl

Only a Julia gRPC Server is missing. So, maybe if you are interested to do that, and use the gRPCClient.jl as your client lib, then the implementation would be there.

We used the client to connect to a Java server implementation.

**Comment by DiegoLucadeTena** [comment]
Team, I just launched a project for developing a gRPC server package for Julia on UpWork. I am looking for funds to finance the development. If anyone is interested we can split the cost and share the result :)

[gRPC Server Package Development for Julia - Web Development](https://www.upwork.com/jobs/~021854887408641455298)

Please ping me if interested :)
