### ISSUE TITLE
sync_posix.h conditional definition of grpc_mu is prone to UB under ASAN

### ISSUE THREAD

**Issue by sam-mccall** [grpc/grpc#24790]
### What version of gRPC and what language are you using?
Observed bug in grpc 1.30.2 in C++. Still seems to be present at master.

### What operating system (Linux, Windows,...) and version?
Linux (Debian testing, glinux 5.7.17-1rodete4-amd64)

### What runtime / compiler are you using (e.g. python version or version of gcc)
observed under clang-9 and clang-11

### What did you do?
1) build gRPC libraries from source (without any unusual config)

2) build a project that depends on gRPC (with ASAN enabled).

In our case, this is LLVM (github.com/llvm/llvm-project) with cmake options: `-DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra -DCLANGD_ENABLE_REMOTE=On` (to build the things with the grpc dependency), `-DLLVM_USE_SANITIZER=Address` (to enable ASAN) `-DGRPC_INSTALL_PATH=...` (to point at the grpc lib).

### What did you expect to see?

The resulting program should work. This is a supported usage mode for ASAN:

> Q: I've built my main executable with ASan. Do I also need to build shared libraries?
> A: ASan will work even if you rebuild just part of your program. But you'll have to rebuild all components to detect all errors.

https://github.com/google/sanitizers/wiki/AddressSanitizer#faq

### What did you see instead?

In tests, the program hits various impossible conditions: grpc internal asserts, free of non-malloc'ed pointer (caught by ASAN). UBSan shows that ClientContext::initial_metadata_corked_ (a boolean) has an impossible value of 0x30.

After much investigation, this is due to corruption of the `grpc_impl::ClientContext`, because different translation units expect a different memory layout for it. Specifically:
 - they disagree about the size of grpc_mu: translation units built with asan (those in LLVM) expect it to be 48 bytes, those without (grpc) expect it to be 40 bytes.
 - therefore they also disagree about offset of all `ClientContext` members following `mu_`.

The reason for this is the definition of `grpc_mu` in impl/codegen/sync_posix.h is conditional based on whether `-fsanitize=address` is enabled for the current TU. (Details elided)
```
// grpc/impl/codegen/port_platform.h
#ifndef GRPC_ASAN_SUPPRESSED
#if defined(__SANITIZE_ADDRESS__)
#define GRPC_ASAN_ENABLED
#elif GPR_HAS_FEATURE(address_sanitizer)
#define GRPC_ASAN_ENABLED
#endif
#endif

// grpc/impl/codegen/sync_posix.h
#ifdef GRPC_ASAN_ENABLED
typedef struct {
  pthread_mutex_t mutex;
  int* leak_checker;
} gpr_mu;
#else
typedef pthread_mutex_t gpr_mu;
#endif
```

Now that we know the problem, we can work around it with GRPC_ASAN_SUPPRESSED. However I'm not sure how we could have known this ahead of time, and the UB is introduced by default in a common scenario and is difficult to detect and understand (it took us a few days).
This also affects building asan binaries using the grpc shared library, I believe.

---

A couple of ideas to make this safer:

 - have a compatible by defining the unused pointer in any case (but only using it if grpc was built with asan)
 - require explicit e.g. GRPC_ASAN_ABI in order to enable ABI-breaking features, and require that this is consistent (which for most applications means never setting it)

**Comment by kirillbobyrev** [comment]
This is also reproducible with 1.30.2 gRPC packages in the Debian distribution we are on. This suggests both Debian unstable and Ubuntu 20.04 (which is intended to be an LTS release IIUC) are affected and would benefit from an upgrade.

I built from sources mostly to diagnose and debug the issue but there is an easier way to reproduce:

1. Install gRPC and Protobuf via `apt install libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc` on the distributions I mentioned.
2. And then as described by @sam-mccall 
> In our case, this is LLVM (github.com/llvm/llvm-project) with cmake options: -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra -DCLANGD_ENABLE_REMOTE=On (to build the things with the grpc dependency), -DLLVM_USE_SANITIZER=Address (to enable ASAN) -DGRPC_INSTALL_PATH=... (to point at the grpc lib).

But with system-installed libraries you don't need `-DGRPC_INSTALL_PATH=... (to point at the grpc lib)`.

**Comment by veblush** [comment]
@sam-mccall Your investigation is right and I agree with you that it's easy to get trapped. Currently we're switching to Abseil sync which doesn't have that issue, I believe the master branch shouldn't have this issue. Can you try to use the latest one?

**Comment by kirillbobyrev** [comment]
@veblush thanks for looking into this! I've checked with the master branch and it seems to work now. As we mentioned before, one of the things we're concerned about is that this already made it into major releases in LTS versions of some Linux distributions. It would be great to address this issue in patches to these releases if possible. Otherwise a lot of users might be stuck with suboptimal system packages.

**Comment by veblush** [comment]
@kirillbobyrev Thanks for the testing. For the linux packages, we don't have control over that, though.

**Comment by veblush** [comment]
Closing this since this was fixed on the master branch after switching to Abseil synch.
