### ISSUE TITLE
Python plugin adds same import multiple times to generated outputs

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#2480]
@nathanielmanistaatgoogle I am filing this based on our discussion yesterday.

You said you'd point me to the place in the code to fix.

I found
https://github.com/grpc/grpc/blob/master/src/compiler/python_plugin.cc
but it doesn't seem to be the right place :grin:

**Comment by nathanielmanistaatgoogle** [comment]
Indeed I did say that, and you're close to the right place. Look at the sibling file python_generator.cc and in particular lines 299-303 and 383-387.

**Comment by dhermes** [comment]
For posterity:
https://github.com/grpc/grpc/blob/c876923bc2a3d9c6bbc03f275a7fe68333b95600/src/compiler/python_generator.cc#L299-L303
https://github.com/grpc/grpc/blob/c876923bc2a3d9c6bbc03f275a7fe68333b95600/src/compiler/python_generator.cc#L383-L387

**Comment by dhermes** [comment]
I don't think I'll ever have the throughput to deal with this. Though I'd suggest using https://docs.python.org/2/library/ast.html instead of trying to deal with the syntax tree in C++.

**Comment by nathanielmanistaatgoogle** [comment]
Maybe. A reasonable short-term action would be to just de-duplicate inside the code generator's C++ for loops. The right long-term solution might be to gather all the required imports, filter out the ones that are of the generated module itself, and then have all the other ones at the top of the generated module. Perhaps sometime in the next few months...

**Comment by dhermes** [comment]
Indeed, perhaps in the next few months...

**Comment by nathanielmanistaatgoogle** [comment]
I now expect this to be obviated by #3867.

**Comment by dhermes** [comment]
OK good

**Comment by kpayson64** [comment]
Addressed in #6479
