### ISSUE TITLE
Parameter to MergeFrom() must be instance of same class issue with grpc versions 1.26.0

### ISSUE THREAD

**Issue by smokbel** [grpc/grpc#24816]
### What version of gRPC and what language are you using?

Python 3.8.6, grpc 1.33.2, tried on any grpc version 1.26.0+; protobuf 3.13
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.6

### What did you do?

I generated a pb file, compiled in python 3.8.6, called 'resource_pb2' that is used in a unit test. This pb file has a class called RecognitionResource that is called in the test. 

### What did you expect to see?
The test pass.
### What did you see instead?
Starting gRPC bi-directional streaming session
Parameter to MergeFrom() must be instance of same class: expected RecognitionResource got RecognitionResource.

### Anything else we should know about your project / environment?
I printed out all the Recognition resource class types that are called in that test, I do not see any difference in the classes or ids:
<class 'resource_pb2.RecognitionResource'> 2069160783760
<class 'resource_pb2.RecognitionResource'> 2069160783760
<class 'resource_pb2.RecognitionResource'> 2069160783760

**Comment by lidizheng** [comment]
This is unfortunately a ProtoBuf Python issue, you will have better luck at https://github.com/protocolbuffers/protobuf/issues.
