### ISSUE TITLE
 whether grpc resolver-executor  and mlockall encounter problems together?

### ISSUE THREAD

**Issue by foxge** [grpc/grpc#24833]
Hi

IN our one application with grpc 1.18.0 release, we try to use mlockall(see mlock, mlockall) to improve performance, as result, the current process memory usage increased up to more times.

In a word,  whether grpc resolver-executor  and mlockall encounter problems together? or Whether the resolver-executor thread in 1.18.0 version malloc big memory such as 8MByte ?

Fox

**Comment by donnadionne** [comment]
Please direct general question like this one to https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

Your answer may already be there or you can post a new question if it's not.
