### ISSUE TITLE
There is a error when I make in the directory of grpc: src/boringssl/err_data.c  error

### ISSUE THREAD

**Issue by ITFORPLAY** [grpc/grpc#24847]
There is a error when I make in the directory of grpc.
cd grpc
make
...  
...
[C]   Compiling src/boringssl/err_data.c
src/boringssl/err_data.c:22:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_NONE == 1, library_values_changed_1);
                                                                                   ^~
src/boringssl/err_data.c:23:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_SYS == 2, library_values_changed_2);
                                                                                ^~
src/boringssl/err_data.c:24:35: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_BN == 3, library_values_changed_3);
                                                                              ^~
src/boringssl/err_data.c:25:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_RSA == 4, library_values_changed_4);
                                                                                ^~
src/boringssl/err_data.c:26:35: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_DH == 5, library_values_changed_5);
                                                                              ^~
src/boringssl/err_data.c:27:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_EVP == 6, library_values_changed_6);
                                                                                ^~
src/boringssl/err_data.c:28:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_BUF == 7, library_values_changed_7);
                                                                                ^~
src/boringssl/err_data.c:29:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_OBJ == 8, library_values_changed_8);
                                                                                ^~
src/boringssl/err_data.c:30:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_PEM == 9, library_values_changed_9);
                                                                                ^~
src/boringssl/err_data.c:31:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_DSA == 10, library_values_changed_10);
                                                                                ^~
src/boringssl/err_data.c:32:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_X509 == 11, library_values_changed_11);
                                     ^~
src/boringssl/err_data.c:33:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_ASN1 == 12, library_values_changed_12);
                                                                                  ^~
src/boringssl/err_data.c:34:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_CONF == 13, library_values_changed_13);
                                                                                   ^~
src/boringssl/err_data.c:35:39: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_CRYPTO == 14, library_values_changed_14);
                                                                                        ^~
src/boringssl/err_data.c:36:35: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_EC == 15, library_values_changed_15);
                                                                             ^~
src/boringssl/err_data.c:37:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_SSL == 16, library_values_changed_16);
                                                                                ^~
src/boringssl/err_data.c:38:36: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_BIO == 17, library_values_changed_17);
                                                                              ^~
src/boringssl/err_data.c:39:38: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_PKCS7 == 18, library_values_changed_18);
                                                                                    ^~
src/boringssl/err_data.c:40:38: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_PKCS8 == 19, library_values_changed_19);
                                                                                    ^~
src/boringssl/err_data.c:41:39: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_X509V3 == 20, library_values_changed_20);
                                                                                    ^~
src/boringssl/err_data.c:42:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_RAND == 21, library_values_changed_21);
                                                                                  ^~
src/boringssl/err_data.c:43:39: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_ENGINE == 22, library_values_changed_22);
                                                                                      ^~
src/boringssl/err_data.c:44:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_OCSP == 23, library_values_changed_23);
                                                                                  ^~
src/boringssl/err_data.c:45:35: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_UI == 24, library_values_changed_24);
                                                                             ^~
src/boringssl/err_data.c:46:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_COMP == 25, library_values_changed_25);
                                                                                   ^~
src/boringssl/err_data.c:47:38: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_ECDSA == 26, library_values_changed_26);
                                                                                    ^~
src/boringssl/err_data.c:48:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_ECDH == 27, library_values_changed_27);
                                                                                   ^~
src/boringssl/err_data.c:49:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_HMAC == 28, library_values_changed_28);
                                                                                   ^~
src/boringssl/err_data.c:50:39: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_DIGEST == 29, library_values_changed_29);
                                                                                      ^~
src/boringssl/err_data.c:51:39: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_CIPHER == 30, library_values_changed_30);
                                                                                      ^~
src/boringssl/err_data.c:52:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_HKDF == 31, library_values_changed_31);
                                                                                  ^~
src/boringssl/err_data.c:53:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_LIB_USER == 32, library_values_changed_32);
                                                                                  ^~
src/boringssl/err_data.c:54:37: error: expected ‘)’ before ‘==’ token
 OPENSSL_COMPILE_ASSERT(ERR_NUM_LIBS == 33, library_values_changed_num);
                                                                                   ^~
Makefile:2910: recipe for target '/home/hujun/p4/grpc/objs/opt/src/boringssl/err_data.o' failed
make: *** [/home/hujun/p4/grpc/objs/opt/src/boringssl/err_data.o] Error 1

My operating system is Ubuntu 7.5.0-3ubuntu1~18.04.
Hope someone can help me.

**Comment by donnadionne** [comment]
I am not sure what borginssl code you are using and how it is directly inside src/borginssl directory.

We strongly encourage users to use bazel or cmake as make is deprecated: https://github.com/grpc/grpc/tree/master/src/cpp
