### ISSUE TITLE
grpc_c.bundle fails to load on Apple M1 (wrong architecture)

### ISSUE THREAD

**Issue by nilleb** [grpc/grpc#24846]
### What version of gRPC and what language are you using?
Don't know.

### What operating system (Linux, Windows,...) and version?
MacOS 11.0 on Apple Silicon (M1)

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.7.1

### What did you do?
```sh
rails db:migrate
```
but also just
```sh
ruby -rgrpc -e"puts 'OK'"
```

### What did you expect to see?

The migration complete successfully

### What did you see instead?

```
LoadError: dlopen(/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle, 9): no suitable image found.  Did find:
	/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle: mach-o, but wrong architecture
	/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle: mach-o, but wrong architecture - /Users/nilleb/.rvm/gems/ruby-2.7.1/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/grpc.rb:20:in `<main>'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/nilleb/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

```

**Comment by nilleb** [comment]
I'd like to help if I can. How can I try to build the bundle for a different architecture?

**Comment by nilleb** [comment]
I have been able to compile the code with a few changes. But now I have a different problem
```
Symbol not found: _google_protobuf_Any_msginit
```
when executing `ruby -rgrpc -e"puts 'OK'"`

A similar symbol `google_protobuf_Any_msginit` is mentioned in a lot of source files.

Maybe a shared library is not being found in the path?

**Comment by nilleb** [comment]
I have managed building the bundle, this way: first protobuf, then grpc

# protobuf

git clone https://github.com/protocolbuffers/protobuf
cd protobuf/ruby
bundle
rake

cp tmp/arm64-darwin20/protobuf_c/2.7.2/protobuf_c.bundle /opt/homebrew/lib/ruby/gems/2.7.0/gems/google-protobuf-3.14.0-universal-darwin/lib/google/2.7/protobuf_c.bundle

# grpc

build first zlib
in third_party/zlib
./configure
make

then build the rest with
cd src/ruby
bundle
rake
cp tmp/arm64-darwin20/stage/src/ruby/lib/grpc/grpc_c.bundle /opt/homebrew/lib/ruby/gems/2.7.0/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle

**Comment by Androz2091** [comment]
Hello, I'm not sure it's the same error, but I'm getting these errors with Mac Mini m1 Apple Silicon:

![Capture d’écran 2020-12-06 à 19 03 11](https://user-images.githubusercontent.com/42497995/101288243-cfef1700-37f5-11eb-8bc2-5f5343ab36ba.png)
![Capture d’écran 2020-12-06 à 19 03 23](https://user-images.githubusercontent.com/42497995/101288246-d3829e00-37f5-11eb-8f04-dc0701ae6530.png)

Thank you 👍

**Comment by Androz2091** [comment]
Right, I tested using a Macbook Pro 2019 and same result so I guess that's not related. Marked my comments as off-topic.

**Comment by panlilu** [comment]
+1

**Comment by cabello** [comment]
@nilleb thank you for your instructions, I wouldn't be able to investigate this it without them.

In my case I am using asdf so the destination was slightly different:
```
cp tmp/arm64-darwin20/protobuf_c/2.7.2/protobuf_c.bundle /Users/[YOUR_NAME]/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/google-protobuf-3.12.4-universal-darwin/lib/google/2.7/protobuf_c.bundle
```

I had to make sure my project, and the clones of protobuf and grpc were matching the version by checking out the correct tags.

In my case I wasn't able to compile protobuf:

```
cp tmp/arm64-darwin20/protobuf_c/2.7.2/protobuf_c.bundle tmp/arm64-darwin20/stage/lib/google/protobuf_c.bundle
../src/protoc -I../src --ruby_out=lib ../src/google/protobuf/any.proto
rake aborted!
Command failed with status (127): [../src/protoc -I../src --ruby_out=lib ../s...]
/Users/danilo/workspace/public/protobuf/ruby/Rakefile:37:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => build => genproto => lib/google/protobuf/any_pb.rb
(See full trace by running task with --trace)
```

I did proceed and copy the generated protobuf_c.bundle and I was able to compile grpc, however this is what I get now:

```
danilo@air  % ruby -rgrpc -e"puts 'OK'"
dyld: lazy symbol binding failed: Symbol not found: _grpc_set_ssl_roots_override_callback
  Referenced from: /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle
  Expected in: flat namespace

dyld: Symbol not found: _grpc_set_ssl_roots_override_callback
  Referenced from: /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle
  Expected in: flat namespace

zsh: abort      ruby -rgrpc -e"puts 'OK'"
```

Any ideas, suggestions?

I am on:
* ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]
* grpc (1.35.0)
* google-protobuf (3.14.0)

**Comment by cabello** [comment]
If I do a `bundle pristine` install after updating these dependencies, I get the following:

```
$ bundle pristine
...
Installing google-protobuf 3.14.0 (universal-darwin)
Installing grpc 1.35.0 (universal-darwin)
...
```

I was expecting something like `Installing nokogiri 1.11.1 (arm64-darwin)`.

Then I run `ruby -rgrpc -e"puts 'OK'"`

```
Traceback (most recent call last):
	1: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- grpc (LoadError)
	7: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	6: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	5: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	4: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc.rb:19:in `<top (required)>'
	3: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc.rb:19:in `require_relative'
	2: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
	1: from /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require': dlopen(/Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle: mach-o, but wrong architecture
	/Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle: mach-o, but wrong architecture - /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle
```

Note the wrong architecture message for the `grpc_c.bundle`.

**Comment by cabello** [comment]
I got one step closer by following https://github.com/protocolbuffers/protobuf/issues/8199

A bundle pristine install just works, then when running rspec I get the following:

```
$ bundle exec rspec
dyld: lazy symbol binding failed: Symbol not found: _grpc_set_ssl_roots_override_callback                                     |  ETA: ??:??:??
  Referenced from: /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0/src/ruby/lib/grpc/grpc_c.bundle
  Expected in: flat namespace

dyld: Symbol not found: _grpc_set_ssl_roots_override_callback
  Referenced from: /Users/danilo/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0/src/ruby/lib/grpc/grpc_c.bundle
  Expected in: flat namespace

zsh: abort      bundle exec rspec
```

Even though I am using the arm64 architecture now. 🤔

**Comment by premist** [comment]
I was able to follow @nilleb's instruction with some tweaks. Notably:

- Added `-arm arm64` to ARCH_FLAGS on [extconf.rb](https://github.com/premist/grpc/blob/premist/fork-init/src/ruby/ext/grpc/extconf.rb#L49).
- Forced native extension complication by setting [`bundle config set force_ruby_platform true`](https://github.com/premist/grpc/blob/f3458a6ea769b20e6230af55abba8039cf86006a/.github/workflows/build.yml#L21).
- Not sure if this is needed, but symlinked `/opt/homebrew/lib` to `/opt/local/lib`. This helped troubleshooting some other native gem issue on Apple Silicon.

I hooked everything up to self-hosted GitHub Actions runner I own, and was able to build gem and use it without `_grpc_set_ssl_roots_override_callback` issue reported above. ([GitHub Actions workflow](https://github.com/premist/grpc/blob/premist/fork-init/.github/workflows/build.yml))

Or, you can download [grpc_c.bundle file](https://github.com/premist/grpc/actions/runs/557793322) and just replace from the already installed gem path.

**Comment by cabello** [comment]
Hi @premist , thank you for looking into that as well as suggesting the PR to maintainers.

I tried following your steps, it also required a `xcode-select --install` in order to run xcrun, my resulting file still crashed for some unknown reason: `zsh: killed     bundle exec rspec`.

I downloaded the file from Github actions after checking your [changes](https://github.com/premist/grpc/pull/1) and Apple prevented me from running due to "malicious software", I did the following to correct:

```bash
xattr -l grpc_c.bundle # to see the blocking issue
...
...
com.apple.quarantine: 0083;6027d9ba;Safari;1DC2XXXX-92E0-4235-A927-XXXXXA4207F
xattr -d com.apple.quarantine grpc_c.bundle # to remove the quarantine mark
```

After that my test suite run successfully for the first time, yay! 🎉 

Thank you 🙇

**Comment by konalegi** [comment]
I compiled the grpc manually and replaced it inside gems, but still getting some strange error. 
My steps:
in project
```
bundle config set force_ruby_platform true.
bundle
```
it completes fine
and then compile manually grpc.
```
git clone git@github.com:grpc/grpc.git
git submodule update --init
bundle 
<updated extconf.rb with -arch arm64>
rake 
cp tmp/arm64-darwin20/stage/src/ruby/lib/grpc/grpc_c.bundle /Users/jkonalegi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.35.0/src/ruby/lib/grpc/grpc_c.bundle
```
But still getting the following error. 
```
$ bundle exec ruby -rgrpc -e"puts 'OK'"
[1]    15735 killed     bundle exec ruby -rgrpc -e"puts 'OK'"
```
The same error I get if I download from github actions.
Do you have any ideas about what could be wrong?

**Comment by NielsKSchjoedt** [comment]
+1

**Comment by NielsKSchjoedt** [comment]
@konalegi looks like you did not install v `1.36.0` of `grpc` and once you have done that you need to overwrite the `grpc_c.bundle` at `gems/grpc-1.36.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle` (note the `-universal-darwin` part). Then it worked for me :-)

**Comment by kbarrette** [comment]
Looks like #25419 was merged - are we waiting on a new release of the gem to fix this?

**Comment by Vepk17** [comment]
stfu

**Comment by olivierlacan** [comment]
@Vepk17 Take this abusive language somewhere else. 

@lidizheng or @veblush could you please remove the above comment? And is it possible to cut a new release of the gem if #25419 addresses Apple Sillicon support adequately? Thank you.

**Comment by lidizheng** [comment]
@olivierlacan Thanks for reporting this. The new release is on the way, a release candidate will be tagged soon.

**Comment by tnir** [comment]
@lidizheng Isn't publishing to RubyGems automated? I just created #26334 while I am not sure about release process.

**Comment by lidizheng** [comment]
gRPC Ruby v1.38.0 is pushed to RubyGems by @apolcyn, closing.

**Comment by skanev** [comment]
I'm getting the same issue with 1.38.0, though, sadly.

**Comment by anothermh** [comment]
@skanev I had the same issue with 1.38.0 too. Here's what worked for me.

For a Gemfile with:

```ruby
gem 'google-protobuf', '~> 3.17.0'
gem 'grpc', '~> 1.38.0'
```

Remove the gems (all versions):

```shell
gem uninstall google-protobuf
gem uninstall grpc
```

Add the ruby platform to the Gemfile.lock and remove the arm64-darwin20 platform:

```shell
bundle lock --add-platform ruby
bundle lock --remove-platform arm64-darwin20
```

Force your platform to be ruby:

```shell
bundle config set force_ruby_platform true
```

Install the gems:

```shell
bundle install
```

If you see `Installing grpc 1.38.0 with native extensions` and `Installing google-protobuf 3.17.0 with native extensions` then it worked.

If you see `Installing grpc 1.38.0 (universal-darwin)` or `Installing google-protobuf 3.17.0 (universal-darwin)` then it did not work. (and good luck!)

Confirm working with:

```shell
bundle exec ruby -rgrpc -e"puts 'OK'"
OK
```

**Comment by NielsKSchjoedt** [comment]
If bundler is still installing `universal-darwin` when doing as @anothermh has described then try directly using `gem install`:

`gem install grpc --platform=ruby`

**Comment by ted-hanson** [comment]
```Installing google-protobuf 3.17.3 with native extensions
Using googleapis-common-protos-types 1.0.6
Fetching grpc 1.38.0
Installing grpc 1.38.0 with native extensions
Using anycable 1.0.3
Using anycable-rails 1.0.7
Bundle complete! 120 Gemfile dependencies, 288 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
 ted>  bundle exec ruby -rgrpc -e"puts 'OK'"                                                               
dyld: lazy symbol binding failed: Symbol not found: _grpc_set_ssl_roots_override_callback
  Referenced from: /Users/ted/.rvm/gems/ruby-2.5.8/gems/grpc-1.38.0/src/ruby/lib/grpc/grpc_c.bundle
  Expected in: flat namespace

dyld: Symbol not found: _grpc_set_ssl_roots_override_callback
  Referenced from: /Users/ted/.rvm/gems/ruby-2.5.8/gems/grpc-1.38.0/src/ruby/lib/grpc/grpc_c.bundle
  Expected in: flat namespace

[1]    16553 abort      bundle exec ruby -rgrpc -e"puts 'OK'"
```

**Comment by LouisBoudreau** [comment]
> I'm seeing it compile with native extensions and still see the dyld errors... any other thoughts?
> 
> ```
> Installing google-protobuf 3.17.3 with native extensions
> Using googleapis-common-protos-types 1.0.6
> Fetching grpc 1.38.0
> Installing grpc 1.38.0 with native extensions
> Using anycable 1.0.3
> Using anycable-rails 1.0.7
> Bundle complete! 120 Gemfile dependencies, 288 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> 
> 
> ted>  bundle exec ruby -rgrpc -e"puts 'OK'"                                                               
> dyld: lazy symbol binding failed: Symbol not found: _grpc_set_ssl_roots_override_callback
>   Referenced from: /Users/ted/.rvm/gems/ruby-2.5.8/gems/grpc-1.38.0/src/ruby/lib/grpc/grpc_c.bundle
>   Expected in: flat namespace
> 
> dyld: Symbol not found: _grpc_set_ssl_roots_override_callback
>   Referenced from: /Users/ted/.rvm/gems/ruby-2.5.8/gems/grpc-1.38.0/src/ruby/lib/grpc/grpc_c.bundle
>   Expected in: flat namespace
> 
> [1]    16553 abort      bundle exec ruby -rgrpc -e"puts 'OK'"
> ```

@ted-hanson I had the same errors and upgrading  Ruby from `2.6.5` to `2.7.2` fixed these errors. 
I see that you are running Ruby `2.5.8` so you can try upgrading to `2.7.2`.

**Comment by ted-hanson** [comment]
@LouisBoudreau ruby 2.7 does appear to work... thanks!

**Comment by bbuchalter** [comment]
This is still a problem for me:
```
$ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [arm64-darwin20]
```

```
$ bin/rails c
/Users/brian.buchalter/.gem/ruby/2.7.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': dlopen(/Users/brian.buchalter/.gem/ruby/2.7.3/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle, 9): no suitable image found.  Did find:
	/Users/brian.buchalter/.gem/ruby/2.7.3/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle: mach-o, but wrong architecture
	/Users/brian.buchalter/.gem/ruby/2.7.3/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle: mach-o, but wrong architecture - /Users/brian.buchalter/.gem/ruby/2.7.3/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle (LoadError)
```

Using `gem install grpc --platform=ruby` did not change things.

Here's my list of platforms from `Gemfile.lock`:
```
PLATFORMS
  arm64-darwin-20
  x86_64-darwin-19
  x86_64-darwin-20
  x86_64-linux
```

Any ideas? Why did this get closed?

**Comment by anothermh** [comment]
@bbuchalter 

Try following the steps regarding `bundle config` and `bundle lock` in https://github.com/grpc/grpc/issues/24846#issuecomment-849076613.

**Comment by jaredallard** [comment]
Is there a way to get this working with Ruby 2.6.6? We're... currently on this and, uh, it's problematic to upgrade

**Comment by pnaponoceno** [comment]
@jaredallard have you found a solution? I'm stuck at the same point

**Comment by peang** [comment]
incase anyone still having these issue, i was success runing grpc and google-protobuf in ruby 2.5.7 by installing all required lib such as `rbenv`, `ruby-build` by using prefix `arch -x86_64 $(command)` :

e.g. `arch -x86_63 bundle install`

notes :
make sure u have 2 versions of homebrew installed, and use rbenv from -x86 directory instead.

and this is partial versions of my zshrc :
```
###### Multiple Homebrew
alias abrew="/opt/homebrew/bin/brew"
alias i="arch -x86_64"
alias ibrew="arch -x86_64 /usr/local/bin/brew"
_ARCH=$(arch)
PROMPT="$_ARCH $PROMPT"
# Requires iterm2
if [[ "$_ARCH" == "i386" ]]; then
 #usr/local is X_86
 alias bundle="arch -x86_64 bundle"
 export PATH="/usr/local/bin:$PATH"
 export PATH="/usr/local/opt:$PATH"
 export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
fi
if [[ "$_ARCH" == "arm64" ]]; then
 #usr/local is X_86
 # export GEM_HOME=$HOME/.gems
 export PATH=$HOME/.gems/bin:$PATH
 export PATH="/opt/homebrew/bin:$PATH"
 export PATH="/opt/homebrew/opt:$PATH"
 export PATH="/opt/homebrew/opt/curl/bin:$PATH"
 export PATH="/opt/homebrew/opt/imagemagick@6/bin:$PATH"
 export PATH="/opt/homebrew/opt/mysql@5.7/bin:$PATH"
 export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
 export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"
 export PATH="$(brew --prefix openssl@1.1)/bin:$PATH"
 export PATH="$(brew --prefix postgresql)/bin:$PATH"
 export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(abrew --prefix openssl@1.1)"
 export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
fi


######

eval "$(rbenv init -)"
```

PS:
i was following this tutorial, but instead using abrew, i'm using ibrew and all x86 command instead.
https://udnpico.medium.com/install-ruby-di-macbook-pro-m1-a109be60b8aa (its indonesian, but the commands are pretty clear tho)

hope this helps.

**Comment by jaredallard** [comment]
> @jaredallard have you found a solution? I'm stuck at the same point

Sadly no, AFAICT there is no way to get this working for Ruby 2.6 😢

**Comment by olavloite** [comment]
@anothermh Thanks for your detailed [instructions](https://github.com/grpc/grpc/issues/24846#issuecomment-849076613).

For anyone else running into this problem: The instructions did not work for me with Ruby 3.0.0. It did however work with a clean installation of both Ruby 2.7.2 and 3.0.2.

**Comment by leonid-shevtsov** [comment]
This issue cannot be considered _resolved_ by installing Ruby with `arch -x86_64` - it is but merely sidestepped.

The current state of events is: as long as you need the `grpc` gem, you are stuck with x86 Ruby. Which doesn't sound too bad, but for installing many native gems (like `pg`) you need to obtain x86 dependencies and configure build scripts to use them. And then help your teammates do the same on their M1 machines. It's a huge amount of friction for any updates.

**Comment by andy88566y** [comment]
@anothermh again, thanks for your detailed instructions. 

I have same situation with @olavloite. The instructions did not work for me with Ruby 2.7.1. It did work with Ruby 2.7.2.

**Comment by anothermh** [comment]
> The current state of events is: as long as you need the `grpc` gem, you are stuck with x86 Ruby.

That doesn't sound correct to me. I have an M1 Mac, I use asdf-vm to manage Ruby, it's compiled natively for arm64, and I have the grpc gem installed and working fine using the instructions that I left earlier in this thread about setting the bundle platform to be `ruby`.

```shell
arch
arm64
```

```shell
file /Users/foo/.asdf/installs/ruby/3.0.1/bin/ruby
/Users/foo/.asdf/installs/ruby/3.0.1/bin/ruby: Mach-O 64-bit executable arm64
```

and:

```shell
ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin21]
```

and:

```shell
ruby -rgrpc -e "puts 'OK'"
OK
```

I also checked `/Users/foo/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/extensions/arm64-darwin-21/3.0.0/grpc-1.38.0/gem_make.out` to see what architecture was used when compiling the gem and (as the pathname implies) there's over 1,000 references to `-arch arm64` in there -- safe to say it's all compiled natively for M1.

I'm not sure what problem you're having, but my instructions from May still work for running grpc natively on M1 Macs. (and worked when I did a clean installation of macOS after macOS Monterey was released)

**Comment by leonid-shevtsov** [comment]
Well, by now, `grpc` version 1.42.0 works with M1 Ruby just fine, without tricks. So in any case, it's in the past.

**Comment by kuntoaji** [comment]
`grpc` version 1.42.0 works with Ruby 2.7.5 on my M1 Macbook Pro, but it does not work for Ruby version 2.7.1.

**Comment by jpfourny** [comment]
This seems to be broken again in 1.43 😢 .
As long as I keep < 1.43, it finds the correct extensions for `arm64-darwin-21` platform. Anything >= 1.43 pulls down universal (which will never work).

**Comment by anothermh** [comment]
> This seems to be broken again in 1.43 😢 . As long as I keep < 1.43, it finds the correct extensions for `arm64-darwin-21` platform. Anything >= 1.43 pulls down universal (which will never work).

The easiest and most straightforward way to resolve issues with platforms is to tell bundler to use **only** ruby platform which will force gems with native extensions to be compiled from scratch:

```
bundle config set force_ruby_platform true
```

Your `Gemfile.lock` should have **only** one platform:

```
PLATFORMS
  ruby
```

You should then remove all installed gems with `gem uninstall -aIx` and reinstall your bundle with `bundle install`. Then your gems should compile from scratch and work fine.

**Comment by anothermh** [comment]
> symbol not found in flat namespace '_gpr_asprintf'

https://github.com/grpc/grpc/issues/28509#issuecomment-1011097424

**Comment by Bashorun97** [comment]
> > symbol not found in flat namespace '_gpr_asprintf'
> 
> [#28509 (comment)](https://github.com/grpc/grpc/issues/28509#issuecomment-1011097424)

I still get the same error with ruby versions: 2.7.2, 2.7.3, 2.7.5

**Comment by Bashorun97** [comment]
> Well, by now, `grpc` version 1.42.0 works with M1 Ruby just fine, without tricks. So in any case, it's in the past.

Yes, this works. I had to remove 1.36 for 1.43.1 and it worked!

**Comment by edmangimelli** [comment]
Great news for Ruby 2.6* peeps!
It appears that Ruby **_2.6.9_** works
```
bundle config set force_ruby_platform true
gem uninstall -aIx
bundle install
# install the missing bundle version they tell you to install
bundle install
```
(note: i did not need to remove other platforms from my gemfile (just the `bundle config ...` command above))
cc @pnaponoceno 

(**THANK YOU** @jjworren for figuring this out)

**Comment by touseefmurtaza** [comment]
> @skanev I had the same issue with 1.38.0 too. Here's what worked for me.
> 
> For a Gemfile with:
> 
> ```ruby
> gem 'google-protobuf', '~> 3.17.0'
> gem 'grpc', '~> 1.38.0'
> ```
> 
> Remove the gems (all versions):
> 
> ```shell
> gem uninstall google-protobuf
> gem uninstall grpc
> ```
> 
> Add the ruby platform to the Gemfile.lock and remove the arm64-darwin20 platform:
> 
> ```shell
> bundle lock --add-platform ruby
> bundle lock --remove-platform arm64-darwin20
> ```
> 
> Force your platform to be ruby:
> 
> ```shell
> bundle config set force_ruby_platform true
> ```
> 
> Install the gems:
> 
> ```shell
> bundle install
> ```
> 
> If you see `Installing grpc 1.38.0 with native extensions` and `Installing google-protobuf 3.17.0 with native extensions` then it worked.
> 
> If you see `Installing grpc 1.38.0 (universal-darwin)` or `Installing google-protobuf 3.17.0 (universal-darwin)` then it did not work. (and good luck!)
> 
> Confirm working with:
> 
> ```shell
> bundle exec ruby -rgrpc -e"puts 'OK'"
> OK
> ```

Thanks it works for me.

**Comment by axopadyani** [comment]
> @skanev I had the same issue with 1.38.0 too. Here's what worked for me.
> 
> For a Gemfile with:
> 
> ```ruby
> gem 'google-protobuf', '~> 3.17.0'
> gem 'grpc', '~> 1.38.0'
> ```
> 
> Remove the gems (all versions):
> 
> ```shell
> gem uninstall google-protobuf
> gem uninstall grpc
> ```
> 
> Add the ruby platform to the Gemfile.lock and remove the arm64-darwin20 platform:
> 
> ```shell
> bundle lock --add-platform ruby
> bundle lock --remove-platform arm64-darwin20
> ```
> 
> Force your platform to be ruby:
> 
> ```shell
> bundle config set force_ruby_platform true
> ```
> 
> Install the gems:
> 
> ```shell
> bundle install
> ```
> 
> If you see `Installing grpc 1.38.0 with native extensions` and `Installing google-protobuf 3.17.0 with native extensions` then it worked.
> 
> If you see `Installing grpc 1.38.0 (universal-darwin)` or `Installing google-protobuf 3.17.0 (universal-darwin)` then it did not work. (and good luck!)
> 
> Confirm working with:
> 
> ```shell
> bundle exec ruby -rgrpc -e"puts 'OK'"
> OK
> ```

Still installs the `universal-darwin` versions on mine. Will use the native extensions by using these versions:
```ruby
gem 'grpc', '~> 1.42.0', platforms: :ruby
gem "google-protobuf", '~> 3.21.2', platforms: :ruby
```
