### ISSUE TITLE
Fix error codes in client_auth_filter.c

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#2484]

**Comment by jcanizales** [comment]
Related to #2458 (maybe merge both issues?)

**Comment by jboeuf** [comment]
I think that they are slightly different. Looks like #2458 has more to do
with the ability to have the error string bubbling up to the top and this
one to have better error codes. Agreed?

**Comment by jcanizales** [comment]
Agreed.

**Comment by jayantkolhe** [comment]
@ctiller , please check
