### ISSUE TITLE
How to connect Grpc (NuGet 2.33.1) client (netstandard 2.0) with Grpc.Asp.NetCore (NuGet 2.32.0) server (.NET 5.0) using HTTPS and my own certificate?

### ISSUE THREAD

**Issue by hovek** [grpc/grpc#24851]
https://stackoverflow.com/questions/65057450/how-to-connect-grpc-nuget-2-33-1-client-netstandard-2-0-with-grpc-asp-netcor

**Comment by donnadionne** [comment]
Please direct general question like this one to https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion like you have already done.

Your answer may already be there and any answer would be useful for others as well.
