### ISSUE TITLE
fatal: Remote branch RELEASE_TAG_HERE not found in upstream origin

### ISSUE THREAD

**Issue by chanmmn** [grpc/grpc#24866]
The error is from the page 
https://github.com/grpc/grpc/blob/master/BUILDING.md

![image](https://user-images.githubusercontent.com/33271651/100722801-da348f80-3375-11eb-8b98-1a297ee4b9c3.png)

**Comment by markdroth** [comment]
You need to replace "RELEASE_TAG_HERE" with an actual release tag (e.g., "v1.33.2").
