### ISSUE TITLE
Simplify implementing GRXWriters

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2487]
The code to handle `state` and properly nillify the `GRXWriteable` instance should be encapsulated in the `GRXWriter` superclass.

Depends on #2113.

**Comment by jcanizales** [comment]
Depends on #2109 too.

**Comment by jcanizales** [comment]
The four subclasses that can be simplified are `GRXBufferedPipe`, `GRPCCall`, `GRXForwardingWriter`, and `GRXImmediateWriter`.

* `-setState:` can go to the superclass, and the subclasses hook in particular behavior by overriding `-pause`, `-resume` and `-stop` methods (implemented as noops in the superclass).
* `-startWithWriteable:` and `-finishWithError:` can be implemented in the superclass with the code to manipulate `_state` and `_writeable`. A subclass can override the method with a call to the superclass. For example, `GRPCCall` can pass the superclass a wrapped writeable.
* `-finishOutputWithError:` from `GRXForwardingWriter` could be useful for the other classes. Same as `-start` from `ProtoRPC`.

For future-proofing the API, I guess we'll want to do all this in a new `GRXBaseWriter` class, to leave `GRXWriter` pure abstract.

Beware that, for `GRPCCall`, we want the ability to cancel even if the completion has already been received and enqueued, so we don't release the writeable wrapper on finish, but when the completion has been delivered to the wrapped writeable.

**Comment by ctiller** [comment]
Beta? Seems like an API finalization issue.

**Comment by jcanizales** [comment]
It's introducing a class to simplify the implementation of some others; it won't break any interfaces.

**Comment by makdharma** [comment]
Too old an enhancement. closing.
