### ISSUE TITLE
php Why can't I get the array?

### ISSUE THREAD

**Issue by liuaiyuan** [grpc/grpc#24879]
```ptoto
message UsersResponse {
  message User{
   int64 id = 1; 
   string username = 2;
  }
 repeated User items = 2;
}
```

```php
 /**
* @var $response UsersResponse
*/
list($response, $status) = $client->Users($request)->wait();
var_dump($response->getItems()); //  I want to output the array here
```

**Comment by stanley-cheung** [comment]
`$response->getItems()` first?

**Comment by lihaotian0607** [comment]
> `$response->getItems()` first?

```php
[
   ['id'=>1,'username'=>'user1'],
  ['id'=>2,'username'=>'user2']
]
```

**Comment by liuaiyuan** [comment]
> `$response->getItems()` first?

```php
[
   ['id'=>1,'username'=>'user1'],
  ['id'=>2,'username'=>'user2']
]
```

**Comment by stanley-cheung** [comment]
That's what you want right? your `items` is a `repeated` field. You got a list of `User` objects back.

**Comment by liuaiyuan** [comment]
> That's what you want right? your `items` is a `repeated` field. You got a list of `User` objects back.

Yes, but is there any way to convert to an array, or return to an array?

**Comment by stanley-cheung** [comment]
> > That's what you want right? your `items` is a `repeated` field. You got a list of `User` objects back.
> 
> Yes, but is there any way to convert to an array, or return to an array?

But `$respone->getItems()` does return an array right?

**Comment by liuaiyuan** [comment]
> > > That's what you want right? your `items` is a `repeated` field. You got a list of `User` objects back.
> > 
> > 
> > Yes, but is there any way to convert to an array, or return to an array?
> 
> But `$respone->getItems()` does return an array right?

Now it is an object, I hope to get a !!!
Don't know how to return an array

I am like this now, but this is too cumbersome;
Is there a more convenient way?
```php
$users = [];
foreach ($response->getItems() as $row) {
    array_push($users, [
        'id'       => $row->getId(),
        'nickname' => $row->getNickname(),
    ]);
}
```

**Comment by stanley-cheung** [comment]
I see. But this is a question for [protobuf](https://github.com/protocolbuffers/protobuf/). This is not a grpc question. Your question is basically: given a protobuf object, can I get a PHP associative array representation of it. This is a protobuf question.

**Comment by liuaiyuan** [comment]
> I see. But this is a question for [protobuf](https://github.com/protocolbuffers/protobuf/). This is not a grpc question. Your question is basically: given a protobuf object, can I get a PHP associative array representation of it. This is a protobuf question.

Okay, thank you very much for your reply, I wish you a happy life
