### ISSUE TITLE
.NET build fails under Rosetta 2 on Apple M1 hardware

### ISSUE THREAD

**Issue by follesoe** [grpc/grpc#24885]
### What version of gRPC and what language are you using?
Grpc.Tools version 2.33.1 for .NET.

### What operating system (Linux, Windows,...) and version?
macOS Big Sur 11.0.1 running on Apple M1 Mac mini.

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET 5.0.100

### What did you do?
I am trying to build my .NET class library using the MSBuild task from `Grpc.Tools` from Visual Studio for Mac running under Rosetta 2 on macOS Big Sur 11.0.1.

```xml
<ItemGroup>
  <Protobuf Include="**/*.proto" ProtoRoot="ProtocolDefinitions/protobuf_definitions" GrpcServices="None" />
</ItemGroup>
```

### What did you expect to see?
I expected the build to succeed as it does running the build on my normal Mac Book Pro. All other .NET and Xamarin builds works as expected running emulated on M1.

### What did you see instead?

Build error: `/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/build/_protobuf/Google.Protobuf.Tools.targets(5,5): Error MSB6006: "/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc" exited with code 255. (MSB6006) (Blueye.Protocol.Protobuf)`

```

Building Blueye.App.Shared (Debug|iPhoneSimulator)
Build started 12/2/2020 7:32:52 PM.
__________________________________________________
Project "/Users/follesoe/source/BlueyeApp/Blueye.Protocol.Protobuf/Blueye.Protocol.Protobuf.csproj" (Build target(s)):

Target _Protobuf_CoreCompile:
    /Users/follesoe/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc --csharp_out=obj/Debug/netstandard2.0 --proto_path=/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/build/native/include --proto_path=ProtocolDefinitions/protobuf_definitions --dependency_out=obj/Debug/netstandard2.0/360be932244df0a0_common.protodep --error_format=msvs ProtocolDefinitions/protobuf_definitions/common.proto
    /Users/follesoe/.nuget/packages/grpc.tools/2.33.1/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc" exited with code 255.
Done building target "_Protobuf_CoreCompile" in project "Blueye.Protocol.Protobuf.csproj" -- FAILED.

Done building project "Blueye.Protocol.Protobuf.csproj" -- FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings

Build FAILED.

/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc" exited with code 255.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.31
```

### Anything else we should know about your project / environment?
Running emulated on M1 hardware.

Relevant pieces of .csproj file:

```xml
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.14.0" />
    <PackageReference Include="Google.Protobuf.Tools" Version="3.14.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Grpc.Tools" Version="2.33.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="**/*.proto" ProtoRoot="ProtocolDefinitions/protobuf_definitions" GrpcServices="None" />
  </ItemGroup>
```

**Comment by follesoe** [comment]
This could be a bug in Rosetta 2 in macOS, or Visual Studio for Mac for all I know. I will also try to install protoc and run it manual to determine if it is a more general issue related to running protoc on M1.

**Comment by jtattermusch** [comment]
Can you try running the binary it's complaining about `/Users/follesoe/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc` under rosetta 2 as a stand alone binary?

Ok, now I realized that the path says `linux_x64/protoc` - looks like the Grpc.Tools tooling is incorrectly detecting the current plaform as linux?
So it looks like this is actually a duplicate of https://github.com/grpc/grpc/issues/24529. (can you please try macosx_x64/protoc under rosetta 2?)

If so, the good news is that this issue was already fixed by https://github.com/grpc/grpc/pull/24768 and the fix is available in the just-release Grpc.Tools 2.34.0 - can you try it and post back the result?

**Comment by follesoe** [comment]
Great, thanks for the swift feedback @jtattermusch. I will verify `macosx_x64/protoc` from the NuGet package when I get home tonight. And great to see that a fix is in place. Agreed with your assessment that the error is most likely platform detection, as I was able to use protoc under Rosetta 2. Will let you know once confirmed.

**Comment by follesoe** [comment]
The command executes just fine: ` arch --x86_64 /Users/follesoe/.nuget/packages/grpc.tools/2.33.1/tools/macosx_x64/protoc`. 

Updating to 2.34.0 also resolved the issue, so closing it. 👍

**Comment by richseviora** [comment]
For others affected this issue existed for my non-M1 system as well immediately upon upgrading to MacOS 11.0.1, and the fix above also worked.
