### ISSUE TITLE
Using ServerBuilder, how do I tell that the port is in use?

### ISSUE THREAD

**Issue by xheke** [grpc/grpc#24890]
int bound_port=0;
std::string server_address("0.0.0.0:50051");
builder.AddListeningPort(server_address, grpc::SslServerCredentials(ssl_options) &bound_port);
builder.RegisterService(&service);
std::unique_ptr<Server> server(builder.BuildAndStart());
if(bound_port == 0) { cout<<"port already in use!" << endl; }

I don't know why above code is not work, the bound_port return always is 50051, I can't get 0 as expected when port already in use.

Thanks for your help in advance!

**Comment by markdroth** [comment]
This forum is for bugs and feature requests only.  For questions, please try one of the following:

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
