### ISSUE TITLE
grpcio-tools==1.34.0 seg faults on macOS Big Sur, depending on import order

### ISSUE THREAD

**Issue by zsimic** [grpc/grpc#24897]
### What version of gRPC and what language are you using?

python (any 3.6+ version), gRPC 1.34.0

### What operating system (Linux, Windows,...) and version?

macOS Big Sur 11.0.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

Any python version 3.6+ will exhibit this issue.

```
~: /usr/bin/python3 --version
Python 3.7.3

~: : gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What did you do?

Importing a `_pb2.py` file before importing `grpc` leads to a seg fault.

You can reproduce by using this small shell script in a temp folder:
```
#!/bin/bash -xe

PY=${1:-/usr/bin/python3}

if [[ ! -f $PY ]]; then
    PY=$PY/bin/python
fi

rm -rf venv __pycache__
wget -q https://raw.githubusercontent.com/grpc/grpc/master/test/http2_test/messages_pb2.py -Omessages_pb2.py
virtualenv --python $PY venv
venv/bin/pip install -U pip setuptools wheel
venv/bin/pip install grpcio-tools==1.34.0
venv/bin/python --version
venv/bin/python -c 'import grpc; import messages_pb2'
venv/bin/python -c 'import messages_pb2; import grpc'
```

The 1st import sequence works fine: `import grpc; import messages_pb2`
The reverse import sequence seg faults: `import messages_pb2; import grpc`

### What did you expect to see?

Should not seg fault, regardless of import order.

### What did you see instead?

`Segmentation fault: 11`

### Anything else we should know about your project / environment?

This bug does not occur on Linux, and does not occur with previous version `grpcio-tools==1.33.2` on Big Sur.

**Comment by gnossen** [comment]
@zsimic Thank you for the report and comprehensive repro script! I'm able to reproduce on Catalina. I can also confirm that this issue was introduced by `grpcio-tools` `1.34.0`. I'll keep you posted as I find out more information.

**Comment by gnossen** [comment]
The problem appears to be this `mov` instruction at `0x2cefa`:

```
000000000002cec0 google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*):
   2cec0: 55                            pushq   %rbp
   2cec1: 48 89 e5                      movq    %rsp, %rbp
   2cec4: 41 57                         pushq   %r15
   2cec6: 41 56                         pushq   %r14
   2cec8: 53                            pushq   %rbx
   2cec9: 50                            pushq   %rax
   2ceca: 49 89 f6                      movq    %rsi, %r14
   2cecd: 48 89 fb                      movq    %rdi, %rbx
   2ced0: 48 8b 0f                      movq    (%rdi), %rcx
   2ced3: 48 85 c9                      testq   %rcx, %rcx
   2ced6: 75 11                         jne     17 <google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)+0x29>
   2ced8: eb 17                         jmp     23 <google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)+0x31>
   2ceda: 66 0f f 44 00 00              nopw    (%rax,%rax)
   2cee0: 48 8b 49 20                   movq    32(%rcx), %rcx
   2cee4: 48 85 c9                      testq   %rcx, %rcx
   2cee7: 74 08                         je      8 <google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)+0x31>
   2cee9: 4c 39 71 08                   cmpq    %r14, 8(%rcx)
   2ceed: 75 f1                         jne     -15 <google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)+0x20>
   2ceef: eb 7a                         jmp     122 <google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)+0xab>
   2cef1: 48 8b 43 20                   movq    32(%rbx), %rax
   2cef5: 48 85 c0                      testq   %rax, %rax
   2cef8: 74 19                         je      25 <google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)+0x53>
   2cefa: 48 8b 08                      movq    (%rax), %rcx
```

I believe that instruction corresponds to [this line](https://github.com/protocolbuffers/protobuf/blob/v3.13.0/src/google/protobuf/arena.cc#L116), whose containing function `ArenaImpl::NewBlock` was inlined and simplified by the compiler. At this point, [`options_`](https://github.com/protocolbuffers/protobuf/blob/fde7cf7358ec7cd69e8db9be4f1fa6a5c431386a/src/google/protobuf/arena_impl.h#L362) is equal to `0x1`, which is definitely an invalid address.

I'm still not sure what's causing the invalid `0x1` to show up. I'm sure that's somehow related to the import order, but I see that this code has changed quite a bit on the protobuf repo's master branch since then. I'm going to try compiling against that and see if it clears things up. If not, we can start investigating the nitty gritty of what's causing the invalid pointer.

**Comment by gnossen** [comment]
CC @gerben-s since it looks like he has refactored the arena code (cl/340433871) since the `3.13.0` release and may have more context.

**Comment by gnossen** [comment]
It turns out that this issue is not *solely* caused by either `grpcio-tools` or `protobuf`. The only combination with which I can reproduce is `protobuf==3.14.0` and `grpcio-tools==1.34.0`

**Comment by gnossen** [comment]
@zsimic Out of curiosity, are you using `grpcio-tools` at runtime? If so, what's your use case?

**Comment by zsimic** [comment]
We use `grpcio-tools` to generate `_pb2` files from a `.proto` during build.
It is not used at runtime, only at build time.

**Comment by zsimic** [comment]
Tried modifying the setup so `grpcio-tools` is not part of the tested venv (by creating a dedicated venv with only `grpcio-tools` in it, used solely to generate the `_pb2` files), and indeed I avoid running into the issue in the first place... no more segfault (as `grpc==1.34.0` on its own does not exhibit this issue)

**Comment by lidizheng** [comment]
With the version pin removed in https://github.com/grpc/grpc/pull/24911, maybe we should reopen this issue. We still need a solution to avoid the version divergence. Btw, good finding about the root cause of the segfault!

**Comment by gnossen** [comment]
Definitely. This was autoclosed by my PR, even though I struck out the "fixes bit". My bad for not catching it.

**Comment by rowillia** [comment]
I'm investigating a similar issue - https://github.com/protocolbuffers/protobuf/issues/8291 - I'm guessing similar issues will arise if you also import Tensorflow.

Internally we've worked around this by _not_ statically linking `libprotobuf` into the python protobuf library and having both libprotobuf & my internal project load the system `libprotobuf`.  The version shipped on pypi has `libprotobuf` statically linked in.

Another potential approach may be to have protobuf similarly limit it's exported symbols as gRPC does - https://github.com/grpc/grpc/blob/de32de4600572204031e6b6ef613c41e7996389f/tools/distrib/python/grpcio_tools/setup.py#L146-L148

It might also be worth exploring how numpy and scipy handle this - for example both ship their own version of `libopenblas` relying on dynamic linking + (`audit wheel` on Linux | `delocate` on OSX ) and it doesn't seem to cause any issues that I'm aware of.

One thing to note - this may be exclusively causing crashes on OSX due to a difference in behavior of dlopen - https://docs.python.org/3/library/ctypes.html#:~:text=On%20OSX%2010.3%2C%20this%20is%20RTLD_GLOBAL%2C%20otherwise%20it%20is%20the%20same%20as%20RTLD_LOCAL.

**Comment by gnossen** [comment]
> I'm guessing similar issues will arise if you also import Tensorflow

To clarify, you think that `grpcio-tools` would be responsible for a symbol clash now, even after the merge of https://github.com/grpc/grpc/pull/24992? Or do you mean that most Python applications using `grpcio` also use `protobuf` and that some nontrivial subset of those use `tensorflow` as well and may experience a symbol clash as a result of interactions solely between `protobuf` and `tensorflow`? Assuming that's what you mean for the moment. 

> Internally we've worked around this by not statically linking libprotobuf into the python protobuf library and having both libprotobuf & my internal project load the system libprotobuf.

This is a pretty complex dependency for Python users to manage on their own. Shared object libraries are why the manylinux standard was created, so `pip install`s just work. Tensorflow used to be nearly impossible to install as a lay person. I appreciate that we're talking about MacOS here, but I think the same principle should apply -- reduce system-level dependencies as much as possible. It's reasonable to expect advanced users to wrangle system-level dependencies like this, so we could provide them knobs in the build system to make it happen, but I wouldn't advocate for it being the default option.

> Another potential approach may be to have protobuf similarly limit it's exported symbols as gRPC does

This is the solution I came up with when this problem originally reared its head. As far as I can tell, the only real downside is memory wasted by multiple versions of the library having to be loaded in memory and stored on disk.

> It might also be worth exploring how numpy and scipy handle this - for example both ship their own version of libopenblas relying on dynamic linking + (audit wheel on Linux | delocate on OSX ) and it doesn't seem to cause any issues that I'm aware of.

Interesting. `libopenblas` isn't included in the manylinux standard. In order for these libraries to be manylinux-compatible, this would have to be an optional dependency. Regardless, it seems like a good idea to get those teams' perspectives on this.

**Comment by rowillia** [comment]
Thanks so much for the reply!

> Or do you mean that most Python applications using grpcio also use protobuf and that some nontrivial subset of those use tensorflow as well and may experience a symbol clash as a result of interactions solely between protobuf and tensorflow? Assuming that's what you mean for the moment.

Right, this seems to be a general problem that occurs when using multiple libraries that have a dependency on protobuf.  This is probably more of a thread for the protobuf repo (or even a general pypa issue) but excited to see I'm not alone in facing these issues 😄 .

> This is a pretty complex dependency for Python users to manage on their own. Shared object libraries are why the manylinux standard was created. So pip installs "just work"™. Tensorflow used to be nearly impossible to install as a lay person. I appreciate that we're talking about MacOS here, but I think the same principle should apply -- reduce system-level dependencies as much as possible. It's reasonable to expect advanced users to wrangle system-level dependencies like this, so we could provide them knobs in the build system to make it happen, but I wouldn't advocate for it being the default option.

I agree, it's a nightmare 😆 .  Actually, this thread made me experiment more w/ delocate and it actually appears to work!  Building the protobuf wheel & my project then using delocate to bake in the `.dylib` works correctly without relying on any system packages (although I did hit a bug in delocate - https://github.com/matthew-brett/delocate/issues/95 ).

If you're coordinating with the protobuf folks inside of Google would love to sort something out here that makes it easy to embed protobuf without resorting to deep compiler knowledge like you had to here.

**Comment by gnossen** [comment]
> Actually, this thread made me experiment more w/ delocate and it actually appears to work

`delocate` looks like a very interesting project. I wasn't aware that it existed. Unfortunately, bundling a shared object library with your Python package only makes sense when you assume that your library is the only one included in the applications that's depends on that particular shared object library. Which is exactly the assumption that's broken by the case we're talking about here.

The only way it would be reasonable to use this in that case would be if you were actually an application developer, not a library developer, which I assume you are based on the (brief) description you've given of your project.

 > If you're coordinating with the protobuf folks inside of Google would love to sort something out here that makes it easy to embed protobuf without resorting to deep compiler knowledge like you had to here.

I think I'd recommend that the protobuf team add a compiler flag to ensure only one global symbol on Mac OS like we did in https://github.com/grpc/grpc/pull/24992.

@anandolee What do you think?

**Comment by rowillia** [comment]
@gnossen Thanks so much for your links and pointers!  I've learned more than I ever wanted to about mach-o binaries than I ever wanted to 😆 .  https://github.com/protocolbuffers/protobuf/pull/8346 implements these same ideas for protobuf.
