### ISSUE TITLE
detect_new_failures.py: Too many arguments for format string

### ISSUE THREAD

**Issue by langston-barrett** [grpc/grpc#24917]
This Python code contains a call to `str.format` but the string doesn't have any placeholders. This doesn't result in an exception or anything, but it's likely a bug.

### What version of gRPC and what language are you using?
n/a

### What operating system (Linux, Windows,...) and version?
n/a

### What runtime / compiler are you using (e.g. python version or version of gcc)
n/a

### What did you do?
n/a

### What did you expect to see?
Python code that has as many format string placeholders `{}` as arguments to `.format`

### What did you see instead?

https://github.com/grpc/grpc/blob/78b23852b15819c72677207390b90b4a6804b6eb/tools/failures/detect_new_failures.py#L288-L289

### Anything else we should know about your project / environment?
n/a

**Comment by markdroth** [comment]
I'm not sure if we're actually still using this script for anything as part of the more recent flakiness fixit efforts.  If we're not, let's just get rid of it.

**Comment by yashykt** [comment]
@jtattermusch Do we still use this script?

**Comment by jtattermusch** [comment]
The scripts are unused, let's delete them: https://github.com/grpc/grpc/pull/24933
