### ISSUE TITLE
bloaty->libFuzzer is not accessible

### ISSUE THREAD

**Issue by xkszltl** [grpc/grpc#24926]
### What version of gRPC and what language are you using?

Latest release tag/master, C/C++.

### What did you do?

`git clone --recursive https://github.com/grpc/grpc.git` is impossible in China because of submodule dependency chain `grpc->bloaty->libfuzzer` uses `googlesource.com`:
https://github.com/google/bloaty/blob/73594cde8c9a52a102c4341c244c833aa61b9c06/.gitmodules#L9

But googlesource.com is not accessible in China.

Individual developer may use VPN workaround, but it is not practical for automated system, e.g. CI pipelines or services, where grpc is mainly used for.

### What did you expect to see?

1. Bloaty submodule is old (from 2017). New version does not have libfuzzer submodule. So an upgrade should solve the issue.
2. If there's technical difficulty for upgrading, maybe provide an official mirror of libfuzzer and point to that? Since it is old (seems libfuzzer has been merged into clang?), I assume the standalone repo is no longer updated. May even be OK to do a single copy to grpc org as a not-so-official mirror.

### Anything else we should know about your project / environment?

There are other users reporting this before, but got ignored.
Maybe because it is geo-related and hard to repro?
https://github.com/grpc/grpc/issues/18708
https://github.com/grpc/grpc/issues/19872 (not sure about this one due to insufficient log, could be related given the author is Chinese).

These are similar (also due to googlesource.com banned by GFW), but lucky they're fixed.
https://github.com/grpc/grpc/issues/10499
https://github.com/grpc/grpc/issues/15326

**Comment by xkszltl** [comment]
@nicolasnoble Any news on this?

**Comment by veblush** [comment]
First of all, you don't need to get submodule recursively. So the libFuzzer of bloaty isn't required for gRPC. And this issue should've filed at bloaty as it's their dependency. Nonetheless, bloaty appears to change the [source](https://github.com/google/bloaty/blob/main/.gitmodules) so I think it's already fixed.

**Comment by xkszltl** [comment]
@veblush 
Thanks for the info!
I file it here because regardless of whether bloaty change the code, grpc need to make change to that submodule pointer anyway, so it's better to start filing at the downstream.
Plus I do expect communication would be easier within Google than having an outsider to coordinate the changes across google projects.
