### ISSUE TITLE
grpc ruby built by debian causes segfault in gitlab

### ISSUE THREAD

**Issue by pravi** [grpc/grpc#24934]
### What version of gRPC and what language are you using?

1.30.2 ruby

### What operating system (Linux, Windows,...) and version?

Debian GNU/Linux both stable and unstable has this problem.

### What runtime / compiler are you using (e.g. python version or version of gcc)

10.2.1

### What did you do?

If I use the debian provided version ro ruby-grpc package, it caused a segfault in gitlab. more details here,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966653

If the ruby-grpc package is replaced with grpc gem from rubygems.org, the segfault is gone. I can provide access to a test server with the issue if you like to reproduce it. I'm not able to find another way to reproduce the issue.

### What did you expect to see?

the debian packaged version should work without segfault. I know it may be specific to options used by the debian build, but any suggestions for possible changes in build options would be good. It used to work fine till grpc 1.26 and started failing after a build dependency on absl was added.

### What did you see instead?

The debian bug linked above has the details of the segfault.

### Anything else we should know about your project / environment?

Official debian packages are broken, https://salsa.debian.org/debian/grpc/-/blob/master/debian/rules has the build flags used.

**Comment by alto-ruby** [comment]
Debian bug "Marked as fixed in versions ruby-spamcheck/1.0.0+git20220819.662e6bf-2.", closing.
