### ISSUE TITLE
Visual Studio build error when upgrading to version 2.34.0:  "Strong name signature could not be verified"

### ISSUE THREAD

**Issue by jukentpm** [grpc/grpc#24935]
### What version of gRPC and what language are you using?
2.34.0  VB.NET

### What operating system (Linux, Windows,...) and version?
Windows Server 2019

### What runtime / compiler are you using (e.g. python version or version of gcc)
Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4250.0

### What did you do?
Upgraded via Nuget the packages Grpc.Auth, Grpc.Core, Grpc.Core.Api from version 2.33.1 to 2.34.0

### What did you expect to see?
The project to build successfully after upgrade

### What did you see instead?
The project fails to build with error: "_Could not load file or assembly 'Grpc.Auth' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)_"

### Anything else we should know about your project / environment?
I have tested by downgrading the packages back to v2.33.1 and the project builds and runs successfully again.

**Comment by jwfx** [comment]
Same problem when trying to run unit tests that include the `Grpc.Core.Api` package at version 2.34.0.

**Comment by JustinC92130** [comment]
sn.exe is failing the strong-name validation.  

```
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64> .\sn.exe -v C:\Repos\xxxx\packages\Grpc.Auth.2.34.0\lib\net45\Grpc.Auth.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

**Comment by jskeet** [comment]
@jtattermusch: Could I suggest that this be raised to a p1? I've encountered the same problem in google-cloud-dotnet, and I believe it makes the 2.34.0 a non-starter for us at the moment.

**Comment by jtattermusch** [comment]
I suspect this could have been caused by https://github.com/grpc/grpc/pull/24440.

Maybe this is the problem with strong name missing after building on Linux?
https://github.com/grpc/grpc/blob/b2ca2ba2851cf12c40d25cbd2120956d4d21cc2b/src/csharp/build/common.props#L19

**Comment by jskeet** [comment]
Yes, that would definitely do it... that shouldn't be needed any more, as .NET Core has been able to sign on Linux for a while now.

**Comment by jtattermusch** [comment]
trying out the fix: https://github.com/grpc/grpc/pull/24980
I'll post link to the adhoc-built nuget packages once available so that they could be tested.

**Comment by jtattermusch** [comment]
@jskeet   the adhoc build of nugets from #24980  is here:
https://storage.cloud.google.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/linux/grpc_build_packages/15065/20201214-075255/github/grpc/artifacts/csharp_nugets_windows_dotnetcli.zip
Can you please verify that these packages work for you?

**Comment by jskeet** [comment]
@jtattermusch: Yes, those look good to me. I've only done a test of "reproduce that I can make it fail by running tests; change the dependency version; run the same tests successfully" but given the clarity of the error, I think that's enough in this case.

**Comment by jtattermusch** [comment]
I just pushed the 2.34.1 Grpc.Core nugets that include the fix.
