### ISSUE TITLE
grpc-c++: Support exporting master keys of TLS

### ISSUE THREAD

**Issue by huangqiangxiong** [grpc/grpc#24944]
[Wireshark](https://www.wireshark.org) is an open source network protocol
analyzer, which can be used for protocol development, network troubleshooting,
and education. Currently Wireshark can analyze gRPC messages transmitted in plain text (https://gitlab.com/wireshark/wireshark/-/wikis/grpc), but it will be helpful if there is a way to export TLS master keys into a [key log file](https://gitlab.com/wireshark/wireshark/-/wikis/tls) which can be read by Wireshark for analysis gRPC traffic. (The grpc-go already supports this feature referring to [the wiki page](https://gitlab.com/wireshark/wireshark/-/wikis/How-to-Export-TLS-Master-keys-of-gRPC#golang).)

The [SSL_CTX_set_keylog_callback](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_keylog_callback.html) (since openssl 1.1.1) or [SSL_get_client_random/SSL_get_server_random/SSL_SESSION_get_master_key](https://www.openssl.org/docs/man1.1.1/man3/SSL_SESSION_get_master_key.html) methods of openssl or boringssl can be used to export the master keys (into key log files).

The possible way might be that let user register a master key callback function in `TlsCredentialsOptions` and `tsi_ssl_client_handshaker_options`, and grpc(c++) calls the `SSL_CTX_set_keylog_callback` function in `tsi_create_ssl_client_handshaker_factory_with_options` of 'src\core\tsi\ssl_transport_security.cc'. Using `tsi_create_ssl_server_handshaker_factory_with_options` instead if exporting master keyes in the server-side.

**Comment by huangqiangxiong** [comment]
Hope someone to implement this feature.

**Comment by tamird** [comment]
Could we please reopen this and add the appropriate labels to prevent the bot from closing it again?

**Comment by ZhenLian** [comment]
This feature itself seems fine, while I will note a comment that is already covered at `tls.Config.KeyLogWriter` in Go:
```
Use of KeyLogWriter compromises security and should only be used for debugging.
```
We will probably have to document heavily on this to avoid users exporting their TLS keys in production environments.

Our team is currently busy with some other works, and probably won't be able to implement such features in the next couple of months. @huangqiangxiong @tamird Is it possible for your team to come up with a design and drive the implementation, once we agree to add this feature?

@yihuazhang FYI.

**Comment by tamird** [comment]
For me: no.

I am not a regular used of c++ grpc; I landed on this issue while debugging an internal issue at Google (which required me to modify the guts of grpc to exfiltrate the SSL log).

**Comment by ctiller** [comment]
I might have someone... Touch base tomorrow?

**Comment by ZhenLian** [comment]
@ctiller Sure thing!

**Comment by huangqiangxiong** [comment]
I'm glad to find that this feature is about to be released.

**Comment by ZhenLian** [comment]
Yeah, credits to @Vignesh2208 who landed this end to end!
And thanks everyone who is involved here. Amazing work! I am going to close this issue now :)
