### ISSUE TITLE
grpc ErrorCode:2 ErrorMessage：Stream remove

### ISSUE THREAD

**Issue by LearHan** [grpc/grpc#24963]
### What version of gRPC and what language are you using?
gRPC_1.26

### What operating system (Linux, Windows,...) and version?

Windows xp sp3
### What runtime / compiler are you using (e.g. python version or version of gcc)
visual studio 2019 && C++

### What did you do?
Two threads mutually exclusive access to the GRPC interface. The first thread can successfully access the GRPC interface.When the second thread accesses the GRPC interface, the first thread exits and then the second thread fails to access the GRPC interface.

### What did you expect to see?
Both threads were able to successfully access the GRPC

### What did you see instead?
the second thread fails to access the GRPC interface.

**Comment by veblush** [comment]
This doesn't have enough information to investigate. If this is still the case with the latest version of gRPC, please feel free to reopen it.
