### ISSUE TITLE
gRPC instalation failed (installing gRPC-C++ podspec)

### ISSUE THREAD

**Issue by MarineKh** [grpc/grpc#24966]
**Step 1: Describe your environment**
Xcode version: 12.2
npm version: 6.14.8
node version: v14.15.0
ruby version - 2.6.3p62 
Installation method: CocoaPods

**Step 2: Describe the problem**
Steps to reproduce:
Tried install pod inside ios folder but failed when installing gRPC-C++ (1.28.0)

Installing Yoga (1.14.0)
Installing abseil (0.20200225.0)
Installing boost-for-react-native (1.63.0)
Installing gRPC-C++ (1.28.2)
[!] /bin/bash -c 
set -e
sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g' $(find src/core -type f \( -path '*.h' -or -path '*.cc' \) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)
    find src/core/ third_party/upb/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "upb/(.*)";#if COCOAPODS==1\
  #include  "third_party/upb/upb/\1"\
#else\
  #include  "upb/\1"\
#endif;g'
    find src/core/ third_party/upb/ -type f -name '*.grpc_back' -print0 | xargs -0 rm
    find src/core/ src/cpp/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "(.*).upb.h";#if COCOAPODS==1\
  #include  "src/core/ext/upb-generated/\1.upb.h"\
#else\
  #include  "\1.upb.h"\
#endif;g'
    find src/core/ src/cpp/ -type f -name '*.grpc_back' -print0 | xargs -0 rm

sed: can't read s;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g: No such file or directory

**Comment by yulin-liang** [comment]
Do you use gnu-sed? If so, you need to use macos's default SED instead.
