### ISSUE TITLE
Add missing metadata into DLLs

### ISSUE THREAD

**Issue by AvramM** [grpc/grpc#24977]
Many OEM manufacturers require that software shipped with their devices meet certain requirements. One that I'm facing right now is that all DLLs and executables must have complete metadata (in my case, specifically the version number).

Two of the DLLs that I need to ship have missing metadata, specifically:

- `grpc_csharp_ext.x86.dll`
- `grpc_csharp_ext.x64.dll`

Please alter the build scripts such that the metadata is correctly filled in on these binaries.

P.S. if you can point me to the script that builds it, I'm happy to raise a PR.

**Comment by HormyAJP** [comment]
Nudge on this issue. What would be needed to get this done? Or maybe better questions:

- Are the repo owners happy with the change conceptually?
- Would the repo owners make this change?
- If not, can you point to where the change needs to be made and I can make it please?
