### ISSUE TITLE
PHP MacOS Build Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#25017]
```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_php7_macos_opt_native/src/php/ext/grpc/byte_buffer.c:19:10: fatal error: 'php.h' file not found
#include <php.h>
         ^~~~~~~
1 error generated.
make: *** [byte_buffer.lo] Error 1

2020-12-15 16:19:49,350 FAILED: tools/run_tests/helper_scripts/build_php.sh [ret=2, pid=40656, time=7.2sec]
2020-12-15 16:19:49,350 FAILED: Some tests failed
```

https://source.cloud.google.com/results/invocations/20a1e71b-4733-4bde-b123-1ddacd6d2f0d/log

Potentially related to https://github.com/grpc/grpc/issues/25016 ?

**Comment by stanley-cheung** [comment]
Hm, so looks like the PHP headers themselves went away, or cannot be found (permission issue)? Is it a new set of MacOS environment? Because this should have worked before right?

**Comment by gnossen** [comment]
This is not a new build environment AFAIK. This was just a PR test on the `v1.34.x` branch.

**Comment by stanley-cheung** [comment]
Interestingly, this is the only failure in the last 25 builds: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_php

**Comment by stanley-cheung** [comment]
Haven't seen this for a while. Closing this for now.
