### ISSUE TITLE
example/cpp/route_guide make failed

### ISSUE THREAD

**Issue by dobet** [grpc/grpc#25035]
I follow this step do, but make failed
https://www.grpc.io/docs/languages/cpp/basics/

when i make, 
route_guide.grpc.pb.h:25:10: fatal error: grpc/impl/codegen/port_platform.h: No such file or directory
   25 | #include <grpc/impl/codegen/port_platform.h>

git tag: 64c6cfc791 (HEAD, tag: v1.34.0)
ubuntu20.04
wsl2

**Comment by veblush** [comment]
@dobet Can you let me know detailed steps you did so that I can reproduce the issue? A list of commands would work for me.

**Comment by dobet** [comment]
1. cd grpc/examples/cpp/route_guide
2. protoc -I ../../protos --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ../../protos/route_guide.proto
3. protoc -I ../../protos --cpp_out=. ../../protos/route_guide.proto
4. make

this is make log
[make.log](https://github.com/grpc/grpc/files/5740128/make.log)

**Comment by veblush** [comment]
This is what I run to build the example successfully. 

#### Build & install gRPC

``` 
$ git clone -b v1.34.0 https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ mkdir -p cmake/build
$ cd cmake/build
$ cmake   -DCMAKE_BUILD_TYPE=Release   -DgRPC_INSTALL=ON   -DgRPC_BUILD_TESTS=OFF   -DgRPC_SSL_PROVIDER=package   ../..
$ make -j 8 install
$ cd ../..
```

#### Build route_guide

``` 
$ cd grpc/examples/cpp/route_guide
$  make
```

Can you try this to see whether this is working for you as well?
