### ISSUE TITLE
Intermittent C# gRPC client issue: (Status(StatusCode=Unknown, Detail="Stream removed")) 

### ISSUE THREAD

**Issue by rebel-pyc** [grpc/grpc#25043]
### What version of gRPC and what language are you using?
C# with gRPC 2.28.1 and Protobuf 3.11.4 (gRPC server is Python at 1.31.0)

### What operating system (Linux, Windows,...) and version?
Server Linux 3.10.0-1160.6.1.el7.x86_64 
Client Window 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.3

### What did you do?
Made unary stream call to a Python gRPC server

### What did you expect to see?
Expect to see stream of protobuf message

### What did you see instead?
Exception at the client end 

>System.AggregateException: One or more errors occurred. (Status(StatusCode=Unknown, Detail="Stream removed")) ---> Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
>   at Grpc.Core.Internal.ClientResponseStream '2.MoveNext(CancellationToken token) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ClientResponseStream.cs:line 60`

We enabled the GRPC_TRACE, GRPC_VERBOSITY and got the following exception 
>D1221 23:12:30.290411779    5758 call.cc:739]                set_final_status SVR
>D1221 23:12:30.290500880    5758 call.cc:740]                
>{
>	"created": "@1608621150.290390338",
>	"description": "Error received from peer ipv4:10.161.17.73:65415",
>	"file": "src/core/lib/surface/call.cc",
>	"file_line": 1062,
>	"grpc_message": "Connection timed out",
>	"grpc_status": 14
>}`

### Anything else we should know about your project / environment?
I am unable to  reproduce this issue if both server and client are running in same server or same region.
This problem occurs always when Service running in U.S server and Client from India trying to connect. We don't see this problem often for non-streaming api calls

**Comment by yashykt** [comment]
You seem to be running into connection timeout issues. gRPC has a default initial connection timeout of 20seconds which can be increased if needed. More information on the connection algorithm can be found here https://grpc.github.io/grpc/core/md_doc_connection-backoff.html

These are the corresponding channel args to be set.
```
/** The minimum time between subsequent connection attempts, in ms */
#define GRPC_ARG_MIN_RECONNECT_BACKOFF_MS "grpc.min_reconnect_backoff_ms"
/** The maximum time between subsequent connection attempts, in ms */
#define GRPC_ARG_MAX_RECONNECT_BACKOFF_MS "grpc.max_reconnect_backoff_ms"
/** The time between the first and second connection attempts, in ms */
#define GRPC_ARG_INITIAL_RECONNECT_BACKOFF_MS \
  "grpc.initial_reconnect_backoff_ms"
```

I would normally assume that 20 seconds is enough for connections to be established but there are scenarios where a different initial timeout value might be better. I hope this helps.
