### ISSUE TITLE
Add C++ Documentation for when ServerWriter::Write() returns true / false

### ISSUE THREAD

**Issue by mtan429** [grpc/grpc#25048]
The documentation at https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_writer.html for grpc::ServerWriter::Write() only indicates that it returns a bool. It would be helpful to add clarification on when exactly true or false is returned.

This would help clients who are seeing Write() return false, but want to debug why that's happening.

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/blob/ae7f520358d7145a7484db693376fdebbd72662d/include/grpcpp/impl/codegen/sync_stream.h#L313

This is already documented at https://grpc.github.io/grpc/cpp/classgrpc_1_1internal_1_1_writer_interface.html

Please feel free to suggest improvements to the documentation as a PR.

**Comment by mtan429** [comment]
Thank you. The documentation you pointed to says "true on success, false when the stream has been closed."

If I understand correctly, the stream can only close for two reasons: 1) client closes the stream, 2) network error.  Can you add to the documentation how to tell the difference between these two cases, on the server side?

Our use case is that we want to alert only if the second happens, but not the first.

**Comment by yashykt** [comment]
The way that clients close the streams is by sending a RST_STREAM frame. Unfortunately, that is not something that is exposed to the API.

One possible workaround, I can think of is to use a bidirectional stream to send an explicit application message when the client wants to end the stream.
