### ISSUE TITLE
Trio Support

### ISSUE THREAD

**Issue by twosigmajab** [grpc/grpc#25050]
[Trio](https://trio.rtfd.io) is the popular Python library for async concurrency and I/O that implements *structured concurrency*. Concurrent programs that do not use structured concurrency are analogous to programs that use `goto` rather than modern control flow structures. (Please read https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/ (by the author of Trio) for a full explanation.) Alternative gRPC Python implementations such as https://github.com/standy66/purerpc support Trio, but this official implementation does not. Would you consider adding Trio support, potentially via [anyio](https://anyio.rtfd.io) (like purerpc is doing)? Thank you for your consideration.

**Comment by lidizheng** [comment]
Hi, supporting an extra I/O library is a challenging yet rewarding task. We offers support to `asyncio` since it's the official asynchronous I/O library. We currently don't have plans for supporting `Trio`. Contributions are welcomed.

**Comment by twosigmajab** [comment]
Thanks for the quick response, and great to hear you would accept a contribution to add Trio support.

**Comment by twosigmajab** [comment]
I expect to help onboard a number of potential new Trio and open source contributors in the coming weeks. This issue just might be a good candidate for one of them to work on.

But if anyone else wants to work on this before then, please don't hesitate to!
