### ISSUE TITLE
BadImageFormatException starting 64-bit C# server or client

### ISSUE THREAD

**Issue by kkm000** [grpc/grpc#2505]
Using grpc/grpc-common/csharp project, VS2013 Update 4, Windows 7 64-bit. Added a new solution configuration `x64`, built all projects. Attempting to launch GreeterClient I am getting an exception message
```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)
   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment.Initialize()
   at GreeterClient.ClientMainClass.Main(String[] args) in c:\projects\grpcdemo\csharp\GreeterClient\Program.cs:line 13
```
A similar one for the server.

Looks like native binaries `grpc_csharp_ext.dll, zlib, libeay32, ssleay32` deployed to `csharp\GreeterClient\bin\x64\Debug` are exactly same 32-bit binaries as those in `csharp\GreeterClient\bin\Debug`. I do not think that the package `grpc.native.csharp_ext.0.10.0` even contains the 64-bit files. Is this an unsupported configuration yet? Other dependencies do indeed come in 32 and 64 bit flavors.

**Comment by nickdul** [comment]
The issue still reproduced in `Grpc 0.6.1` package (installed via NuGet).
The only way to make it working - switch solution platform to x86.

**Comment by michaelvlaar** [comment]
Is there any progress on x64?

**Comment by nickdul** [comment]
are there any news about x64 support?

i was tried to build `grpc_csharp_ext.dll` for x64 manually but now my C# gRPC server fails with the following error:
```
..\..\..\src\core\support\stack_lockfree.c:132: assertion failed: (old_val & (1UL << pushed_bit)) == 0
```

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/3852

**Comment by jtattermusch** [comment]
I believe all the necessary work has been done. In the next release, we will publish nuget packages that will fully support Win 32bit and Win 64bit (including autodetection).
See #4820 for details.
