### ISSUE TITLE
C# Xamarin.Android: grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc#25080]
I have a Xamarin Android project, which target is Android 8.0 (Oreo). This application is a gRPC client that will consume the gRPC service that is running in a computer.

I have another client, a simple WPF project which target is Net Core 3.1. This is another client, that runs in the same computer where is my gRPC service.

I have a console application, that runs in the computer and start the gRPC service. This console application is a Net Core 3.1 application.

I have a Net Standard 2.1 library, that has the code that creates the gRPC service and calls the service. It is used for both client, Xamarin and WPF.

When I call to the service from my WPF application, that runs in the same computer, I get response from service, but when I use the Xamarin application, that I am debugging in a device, not in an emultaror, i guet the following error:

grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)

This is the code of how I set my service:

```
public static void Main(string[] args)
{
try
{
//Configuración del nivel de log
//Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");

            //Configuración para indicar el tipo de resolución DNS. Esto en principio no es necesario.
            Environment.SetEnvironmentVariable("GRPC_DNS_RESOLVER", "native");




            //Crea un servicio con gRPC directamente, no con .NET
            const int miPort = 5001;

            var cacert = File.ReadAllText("Keys/ca.crt");
            var cert = File.ReadAllText("Keys/server.crt");
            var key = File.ReadAllText("Keys/server.key");

            var keypair = new KeyCertificatePair(cert, key);
            var sslCreds = new SslServerCredentials(new List<KeyCertificatePair>
                                {
                                    keypair
                                }, cacert, false);


            Server server = new Server()
            {
                Services = { Gestor.BindService(new GestorAplicacionesService()) },
                //Ports = { new ServerPort("0.0.0.0", miPort, ServerCredentials.Insecure) },
                Ports = { new ServerPort("192.168.1.33", miPort, ServerCredentials.Insecure) },
                //Ports = { new ServerPort("0.0.0.0", miPort, sslCreds) },
                //Ports = { new ServerPort("192.168.1.33", miPort, sslCreds) },
                //Ports = { new ServerPort("localhost", miPort, sslCreds) },
            };
            server.Start();
            Console.WriteLine("Started server on port " + miPort);
            server.ShutdownTask.Wait();
            //Console.WriteLine("Press any key to stop...");
            //Console.ReadKey();
        }
        catch (Exception ex)
        {
            using (System.IO.StreamWriter file = new System.IO.StreamWriter(@"log.txt", true))
            {
                file.WriteLine(ex.Message);
            }

            Console.WriteLine(ex.Message);
            Console.ReadKey();
        }
    }
```

This is the code of my client library:

```        private Gestor.GestorClient GetClient()
        {
            Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");
            //Environment.SetEnvironmentVariable("GRPC_TRACE", "api,cares_resolver,cares_address_sorting");


            var keypair = new KeyCertificatePair(_clientCertificate, _clientPrivateKey);
            var sslCreds = new SslCredentials(_caCertificate, keypair);

            //var channel = new Channel(_serviceAddress, _port, sslCreds);
            //var channel = new Channel(_serviceAddress, _port, SslCredentials.Insecure);
            **var channel = new Channel("192.168.1.33", _port, SslCredentials.Insecure);**
            var client = new Gestor.GestorClient(channel);
            return client;
        }
```

NOTE: in in the line that is in bold characters where I get the exception.

this is the code in my Xamarin client:

```
private async void btnTestServicio_Click()
{
try
{
GrpcClient.GestorAplicaciones miGrpcClient = new GrpcClient.GestorAplicaciones(_serviceAddress, _port, _caCertificate, _clientCertificate, _clientPrivateKey);

            string miSaludo = await miGrpcClient.PingAsync("Álvaro");

            ShowAlert("Error", miSaludo);
        }
        catch (Exception ex)
        {
            ShowAlert("Error", ex.Message);
        }
    }
```

I attached all my solution with all the projects, for this could help.
[GestorAplicaciones.zip](https://github.com/grpc/grpc/files/5757150/GestorAplicaciones.zip)

**Comment by Mrsevic** [comment]
As stated in the description of nuget package starting from the version 2.3.4* you need to add the Grpc.Core.Xamarin projects both in your shared project and in the android project.  

Let me know if installing this corresponding package solved the error for you.

**Comment by ComptonAlvaro** [comment]
Thanks so much, this solve my problem.

BUt in my case I have only add the GRPC.Core.Xamarin to my Xamarin project, it is not needed ti add to the common library that has the code of the client of gRPC and that is used for the xamarin and WPF projects.

Thanks so much.

**Comment by Mrsevic** [comment]
You're welcome, good to know about the dependency in the shared project:) Could you please send me a mail I have one question regarding something I have noticed in your code? Thanks

**Comment by ComptonAlvaro** [comment]
I have sent you an email from my main email account to your gmail account. In any way I can help you, tell me.

Thanks so much.

**Comment by SpaaJ** [comment]
Hi ComptoAlvaro,

I tried to get your application to work (adding Grpc.Core.Xamarin in the Xamarin project), but I got this error while pressing btnTest!

Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1609877117.596478880","description":"Failed to pick subchannel","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1609877117.596462457","description":"failed to connect to all addresses","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}")

(The service is started and I passed all the 192.168.1.33 addresses in localhost for the tests)

Do you have an idea ?

**Comment by ComptonAlvaro** [comment]
@SpaaJ Ensure that you are running the service too.

Also try to check the IP that is used in the service. In the Program.cs file, I have this line:

`Ports = { new ServerPort("192.168.1.33", miPort, ServerCredentials.Insecure) }`

Here I set the IP of the computer where I am running the service. Set the IP that you have in your case. I have tried another options like 0.0.0.0, localhost or 127.0.01 but in all these cases I get the same error, failed to connect to all addresses. In my case, the best option it is to set the IP of the computer that is running the service, but really it is not a big problem for me, the service will run in a server an a server should to have a static IP.

If this don't solve your problem, feel free to ask any question.

**Comment by SpaaJ** [comment]
Exactly!
Your solution is a very good example of setting up gRPC in Xamarin ... and learning Spanish :)
Thank you so much !

**Comment by ComptonAlvaro** [comment]
I am glad it is useful for you. Really it is a very early version, my objetive first it was try to connect from mobile to service, and it has many commented code with tests and explanations.

**Comment by jtattermusch** [comment]
It looks like this piece of documentation describes a solution for the original issue:
https://github.com/grpc/grpc/tree/master/src/csharp/experimental#xamarin
> Starting from gRPC C# 2.34.x: in addition to the regular Grpc.Core dependency, you will also need to add Grpc.Core.Xamarin dependency to your project (which has the mobile-specific builds of c# native extension library). The Grpc.Core and Grpc.Core.Xamarin package versions must always match exactly for things to work. Also note that the Grpc.Core.Xamarin needs to be added to your *.Android and *.iOS projects in order for the native library bindings to be registered correctly (see https://github.com/grpc/grpc/issues/16250).
