### ISSUE TITLE
System.Memory for Unity gRPC is still broken

### ISSUE THREAD

**Issue by doctorpangloss** [grpc/grpc#25084]
I'm reopening #22251 here because it is still broken on the latest master, although fixed in `2.26`.

**Comment by ThanoS-max** [comment]
Any updates regarding this?

**Comment by jtattermusch** [comment]
gRPC needs to be upgraded to protobuf 3.14.0 (see https://github.com/grpc/grpc/pull/24855) and after that the generated unity package will behave correctly.

**Comment by ReubenJ** [comment]
FYI this appears to be fixed. Tested in a 2019.4 project using [today's build](https://packages.grpc.io/archive/2021/01/f6f75a6ff86715a28ca55c3facfb729e8dfb5ea8-0dbab2dd-56cd-468b-b26b-6ec4f9ca2003/index.xml).
