### ISSUE TITLE
Grpc.Tools - Include other language plugins

### ISSUE THREAD

**Issue by abbotware** [grpc/grpc#25099]
### Is your feature request related to a problem? Please describe.
I am attempting to build a C# server and Python Client from the same .proto using Visual Studio.  It would be trivial to use grpc.tools if it included the other language plugins.  

### Describe the solution you'd like
I would like a single project with .proto file(s) and I would like to use Grpc.Tools to generate both C# and Python code.  

### Describe alternatives you've considered
I could install the protoc compiler for python directly, but It would be nice to have a single project produce all client code in multiple languages

### Additional context
the integrated Msbuild tasks do everything I would want, but i noticed in the 
`.nuget\packages\grpc.tools\2.32.0\tools\windows_x86\` folder, there is only `grpc_csharp_plugin.exe`

note, if worried about the package size growing, you could always create seperate nugets Grpc.Tools.Python. Grpc.Tools.Cpp, etc such that a user could opt in to include the compiler plugins they are interested in.

@kkm000

**Comment by jtattermusch** [comment]
Currently we don't have plans to make codegen plugins for other languages than C# available as part of Grpc.Tools (which is intended to be used in .NET projects).
gRPC python provides their own integration of the codegen (e.g. see the https://pypi.org/project/grpcio-tools/ pip package and the "grpc easy" project).
