### ISSUE TITLE
FLAKE: tests.cloud_to_cloud:go:dart_server:timeout_on_sleeping_server:tls

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#25090]
https://source.cloud.google.com/results/invocations/bfb9b795-d97a-46ad-b6a2-8062395778d4/targets/github%2Fgrpc%2Finterop_test/tests

```
FATAL: 2020/12/21 23:29:58 [interop] &{0xc000260000}.Recv() = _, <nil>, want error code 4
exit status 1
```

**Comment by drfloob** [comment]
Friendly reping, @easwars, on two more recent failures this week.

**Comment by mit-mit** [comment]
What version of dart-grpc is the server running?
