### ISSUE TITLE
sed command fails on prepare_command step on linux machine from grpc podspec

### ISSUE THREAD

**Issue by tikekar** [grpc/grpc#25096]
### What version of gRPC and what language are you using?
1.24.2
Using Swift

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
We are consuming grpc-core via SwiftGRPC within our framework. We are trying to run pod repo push to publish our framework. 

### What did you expect to see?

It should work successfully.

### What did you see instead?
pod linting and validation fails with following error -

_Running prepare command
   $ /bin/bash -c  set -e sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\   #include <openssl_grpc/\1>\ #else\   #include <openssl/\1>\ #endif;g' $(find src/core -type f \( -path '*.h' -or -path '*.cc' \) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)     find src/core/ third_party/upb/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "upb/(.*)";#if COCOAPODS==1\   #include  "third_party/upb/upb/\1"\ #else\   #include  "upb/\1"\ #endif;g'     find src/core/ third_party/upb/ -type f -name '*.grpc_back' -print0 | xargs -0 rm     find src/core/ src/cpp/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "(.*).upb.h";#if COCOAPODS==1\   #include  "src/core/ext/upb-generated/\1.upb.h"\ #else\   #include  "\1.upb.h"\ #endif;g'     find src/core/ src/cpp/ -type f -name '*.grpc_back' -print0 | xargs -0 rm
   sed: can't read s;#include <openssl/(.*)>;#if COCOAPODS==1\
     #include <openssl_grpc/\1>\
   #else\
     #include <openssl/\1>\
   #endif;g: No such file or directory
 -> OURPODNAMEHERE
    - ERROR | [iOS] unknown: Encountered an unknown error (/bin/bash -c 
set -e
sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g' $(find src/core -type f \( -path '*.h' -or -path '*.cc' \) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)
    find src/core/ third_party/upb/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "upb/(.*)";#if COCOAPODS==1\
  #include  "third_party/upb/upb/\1"\
#else\
  #include  "upb/\1"\
#endif;g'
    find src/core/ third_party/upb/ -type f -name '*.grpc_back' -print0 | xargs -0 rm
    find src/core/ src/cpp/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "(.*).upb.h";#if COCOAPODS==1\
  #include  "src/core/ext/upb-generated/\1.upb.h"\
#else\
  #include  "\1.upb.h"\
#endif;g'
    find src/core/ src/cpp/ -type f -name '*.grpc_back' -print0 | xargs -0 rm
sed: can't read s;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g: No such file or directory_

This worked fine before our grpc-core version was updated. We found that  line 1421 was  added here, (https://github.com/grpc/grpc/blob/master/gRPC-C%2B%2B.podspec#L1421) which caused it to fail on GNU sed (Linux). 
We are running pod repo push on our linux based environment on our build machine. 

In the following command, only line 1421 has **-i '' (empty quotes)** which cause this issue of incorrect parsing on GNU sed. Why is it different from "**sed -E -i'.grpc_back'** format? 
sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\\\n  #include <openssl_grpc/\\1>\\\n#else\\\n  #include <openssl/\\1>\\\n#endif;g' $(find src/core -type f \\( -path '*.h' -or -path '*.cc' \\) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)
    find third_party/upb/ -type f \\( -name '*.h' -or -name '*.hpp' -or -name '*.c' -or -name '*.cc' \\) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "third_party/(.*)";#if COCOAPODS==1\\\n  #include  "third_party/upb/third_party/\\1"\\\n#else\\\n  #include  "third_party/\\1"\\\n#endif;g'
    .............

**Comment by yulin-liang** [comment]
This should be ran in macos's default SED and not gnu-sed

**Comment by tikekar** [comment]
* @yulin-liang this is a regression. And was working in both GNU and BSD environments before we updated the version. 
* This line **sed -E -i ''** with empty quotes broke it on GNU sed environment. I believe it just needs to follow **sed -E -i'.grpc_back'**  syntax with non empty quotes to support both environments. (Refer to the full command below)

We are running this on our linux based build machine with other environment build ups like Android as well. It was working fine before we updated to this version. So we would appreciate if this sed command can support both environments.

Full command -
sed -E -i '' 's;#include <openssl/(.)>;#if COCOAPODS==1\\n #include <openssl_grpc/\1>\\n#else\\n #include <openssl/\1>\\n#endif;g' $(find src/core -type f \( -path '.h' -or -path '.cc' \) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)
find third_party/upb/ -type f \( -name '.h' -or -name '.hpp' -or -name '.c' -or -name '.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "third_party/(.)";#if COCOAPODS==1\\n #include "third_party/upb/third_party/\1"\\n#else\\n #include "third_party/\1"\\n#endif;g'

**Comment by tikekar** [comment]
Any updates on when this fix will be available?

**Comment by yulin-liang** [comment]
Sorry I am working on other things, I'll take a look this afternoon.

**Comment by yulin-liang** [comment]
@tikekar I just check, the `sed` command with `-i` option is incompatible on BSD and GNU, for in-place updating without backup, `BSD' MUST use -i '' and `GNU` must use -i without empty quotes. Since the podspec is mainly for iOS, we must support `BSD` version, I think you still need to use BSD sed.

**Comment by yulin-liang** [comment]
> @tikekar I just checked, the `sed` command with `-i` option is incompatible on BSD and GNU, for in-place updating without backup, `BSD` MUST use -i '' and `GNU`must use -i without empty quotes. Since the podspec is mainly for iOS, we must support`BSD` version, I think you still need to use BSD sed.

**Comment by tikekar** [comment]
Wondering why all other components of that command are doing backup and not only this one. Also I am wondering that if this is expected to run only on BSD sed, how do we handle this on our build machines which are not only specific to iOS use case.

**Comment by yulin-liang** [comment]
@tikekar I tested locally and we can do backup first and remove all backup files to make it work on both environments. I'll create a PR to fix it later.

**Comment by tikekar** [comment]
That will be great! Thanks!

**Comment by tikekar** [comment]
@yulin-liang thanks for fixing this. Will this be available in next library version update?

**Comment by yulin-liang** [comment]
Yes, it will be in the next version.
