### ISSUE TITLE
C# getting a client-side notification that bidi stream has failed without needing to await responses

### ISSUE THREAD

**Issue by richseviora** [grpc/grpc#25101]
### Is your feature request related to a problem? Please describe.
I'm using a client generated by Grpc.Tools from a `.proto` file.

Right now I don't see an easy way to be notified when a bidirectional stream (via `AsyncDuplexStreamingCall`) has been closed without attempting to read or write to it. If I have a bidi stream open and I send a message to it that results in the stream closing, I first need to try to read or write to the response/request streams, and I'm not always immediately waiting for a response.

### Describe the solution you'd like
As one idea, the constructor for `AsyncDuplexStreamingCall` has a `disposeAction` parameter. We could pass an action there via the `Grpc.Core.CallOptions` object.

### Describe alternatives you've considered
Options: 
  - Add a Task to the call that completes or faults when the stream is closed properly or unexpectedly.
  - Add an event handler to the call that emits when the stream is closed.

**Comment by jtattermusch** [comment]
gRPC doesn't actively track the status of bidi RPCs unless you are sending requests / receiving responses. You are right the currently gRPC C# client doesn't allow to "listen" on whether the call has been closed without also awaiting a response (on the server you can use the serverCallContext.CancellationToken to get notified of some events), but I don't think that's a big limitation - in most cases you do want to await responses for the entire lifetime of a streaming RPC.

What exactly is the "protocol" you are trying to implement on top of the gRPC bidi stream?
