### ISSUE TITLE
Python build error when building from source under pypy docker image

### ISSUE THREAD

**Issue by KumaTea** [grpc/grpc#25112]
### What version of gRPC and what language are you using?
`grpcio` 1.32.0 / Python 3.8.5

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.1 (aarch64)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] on linux

gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

### What did you do?

Hello!

I'm installing `tensorflow` v2.4.0, which requires `grpcio` v1.32.0, on an ARMv8 board.

While compiling grpc from source code (`.tar.gz` instead of `whl`), I saw:

```
...

    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_WIN32_WINNT=1536 -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/zlib -I/usr/include/python3.8 -c third_party/zlib/zutil.c -o python_build/temp.linux-aarch64-3.8/third_party/zlib/zutil.o -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    creating None/tmp/tmprcwldhny
    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c /tmp/tmprcwldhny/a.c -o None/tmp/tmprcwldhny/a.o
    Traceback (most recent call last):
      File "/usr/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
        self.spawn(compiler_so + cc_args + [src, '-o', obj] +
      File "/tmp/pip-install-0pt01nq6/grpcio_683fa9309d7446439af2a3941a4059b4/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.8/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
        raise DistutilsExecError(
    distutils.errors.DistutilsExecError: command 'aarch64-linux-gnu-gcc' failed with exit status 4

    During handling of the above exception, another exception occurred:

...
```

Note this: `aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c /tmp/tmprcwldhny/a.c -o None/tmp/tmprcwldhny/a.o`

Seems that it's attemping to work in an invalid directory **`None/tmp/tmprcwldhny`**.

I think it might actually want to do that in `/tmp/tmprcwldhny`, but the `None` keyword is turned to a string. However I could not find which line of codes caused this.

Here's the full error code: 
[grpcio_error_full.log](https://github.com/grpc/grpc/files/5782358/grpcio_error_full.log)

Thank you.

**Comment by pPanda-beta** [comment]
Same happens while I tried building it in pypy docker image
```pypy:3.7-7.3.3```

**Comment by megabyde** [comment]
For me the problem was due to older GLIBC version which I was able to fix with the following patch:

```
diff --git a/include/grpc/impl/codegen/port_platform.h b/include/grpc/impl/codegen/port_platform.h
index 33f8a1a59d..a1e812500e 100644
--- a/include/grpc/impl/codegen/port_platform.h
+++ b/include/grpc/impl/codegen/port_platform.h
@@ -168,7 +168,7 @@
 #endif /* _LP64 */
 #ifdef __GLIBC__
 #define GPR_POSIX_CRASH_HANDLER 1
-#define GPR_LINUX_PTHREAD_NAME 1
+#define GPR_LINUX_PTHREAD_NAME 0
 #include <linux/version.h>
 #else /* musl libc */
 #define GPR_MUSL_LIBC_COMPAT 1
```

**Comment by jtattermusch** [comment]
@KumaTea  are you building under a docker container? sometimes the issue could be that the environment is setup incorrectly (e.g. $HOME is empty,  the uid corresponds to a nonexistent user etc.), which can then result into  `None` being prepended to the path (for the command it looks like it tries to build under user's tmp directory or sth in that sense),
but I'm not so sure this is the actual problem. In the log you provided I also saw a different error `aarch64-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program cc1plus` - isn't that the actual problem?

```
__attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/zlib -I/usr/include/python3.8 -c third_party/boringssl-with-bazel/src/crypto/bn_extra/convert.c -o python_build/temp.linux-aarch64-3.8/third_party/boringssl-with-bazel/src/crypto/bn_extra/convert.o -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc: In instantiation of ‘absl::lts_2020_02_25::strings_internal::ParsedFloat absl::lts_2020_02_25::strings_internal::ParseFloat(const char*, const char*, absl::lts_2020_02_25::chars_format) [with int base = 10]’:
    third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:498:62:   required from here
    third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
      419 |     } else if (post_decimal_digits > digits_left) {
          |                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
    third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc: In instantiation of ‘absl::lts_2020_02_25::strings_internal::ParsedFloat absl::lts_2020_02_25::strings_internal::ParseFloat(const char*, const char*, absl::lts_2020_02_25::chars_format) [with int base = 16]’:
    third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:500:62:   required from here
    third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
    aarch64-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program cc1plus
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
```

Btw, I was previously able to build from source on aarch64 ubuntu18.04.

**Comment by jtattermusch** [comment]
> For me the problem was due to older GLIBC version which I was able to fix with the following patch:
> 
> ```
> diff --git a/include/grpc/impl/codegen/port_platform.h b/include/grpc/impl/codegen/port_platform.h
> index 33f8a1a59d..a1e812500e 100644
> --- a/include/grpc/impl/codegen/port_platform.h
> +++ b/include/grpc/impl/codegen/port_platform.h
> @@ -168,7 +168,7 @@
>  #endif /* _LP64 */
>  #ifdef __GLIBC__
>  #define GPR_POSIX_CRASH_HANDLER 1
> -#define GPR_LINUX_PTHREAD_NAME 1
> +#define GPR_LINUX_PTHREAD_NAME 0
>  #include <linux/version.h>
>  #else /* musl libc */
>  #define GPR_MUSL_LIBC_COMPAT 1
> ```

Are you sure you were experiencing exactly the same issue as describe above?

**Comment by jtattermusch** [comment]
> Same happens while I tried building it in pypy docker image
> `pypy:3.7-7.3.3`

Did you also get the compiler crash?

**Comment by KumaTea** [comment]
> @KumaTea are you building under a docker container? sometimes the issue could be that the environment is setup incorrectly (e.g. $HOME is empty, the uid corresponds to a nonexistent user etc.), which can then result into `None` being prepended to the path (for the command it looks like it tries to build under user's tmp directory or sth in that sense),
> but I'm not so sure this is the actual problem. In the log you provided I also saw a different error `aarch64-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program cc1plus` - isn't that the actual problem?
> 
> ```
> __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/zlib -I/usr/include/python3.8 -c third_party/boringssl-with-bazel/src/crypto/bn_extra/convert.c -o python_build/temp.linux-aarch64-3.8/third_party/boringssl-with-bazel/src/crypto/bn_extra/convert.o -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
>     third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc: In instantiation of ‘absl::lts_2020_02_25::strings_internal::ParsedFloat absl::lts_2020_02_25::strings_internal::ParseFloat(const char*, const char*, absl::lts_2020_02_25::chars_format) [with int base = 10]’:
>     third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:498:62:   required from here
>     third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
>       419 |     } else if (post_decimal_digits > digits_left) {
>           |                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
>     third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc: In instantiation of ‘absl::lts_2020_02_25::strings_internal::ParsedFloat absl::lts_2020_02_25::strings_internal::ParseFloat(const char*, const char*, absl::lts_2020_02_25::chars_format) [with int base = 16]’:
>     third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:500:62:   required from here
>     third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc:419:36: warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
>     aarch64-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program cc1plus
>     Please submit a full bug report,
>     with preprocessed source if appropriate.
>     See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
> ```
> 
> Btw, I was previously able to build from source on aarch64 ubuntu18.04.

Hi. 

I'm not sure if I was using a container, but likely I was.

I just tried to build `grpcio` on `aarch64` again, **not** in docker or other container, with root privilege. This time there's no `Segmentation fault`, but both `1.32.0` and latest `1.35.0` failed.

`1.32.0` (full log:
[grpcio1320.log](https://github.com/grpc/grpc/files/6014228/grpcio1320.log), `KeyboardInterrupt` after error) shows:

```
aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_WIN32_WINNT=1536 -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/zlib -I/usr/include/python3.8 -c third_party/zlib/zutil.c -o python_build/temp.linux-aarch64-3.8/third_party/zlib/zutil.o -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
  src/python/grpcio/grpc/_cython/cygrpc.cpp: In function ‘PyObject* __pyx_pw_4grpc_7_cython_6cygrpc_7Channel_9segregated_call(PyObject*, PyObject*, PyObject*)’:
  src/python/grpcio/grpc/_cython/cygrpc.cpp:18798:48: warning: ‘__pyx_v_c_completion_queue’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  18798 |   __pyx_v_segregated_call->_c_completion_queue = __pyx_v_c_completion_queue;
        |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/python/grpcio/grpc/_cython/cygrpc.cpp:18438:26: note: ‘__pyx_v_c_completion_queue’ was declared here
  18438 |   grpc_completion_queue *__pyx_v_c_completion_queue;
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  /tmp/ccrjBXGh.s: Assembler messages:
  /tmp/ccrjBXGh.s: Fatal error: can't close python_build/temp.linux-aarch64-3.8/src/python/grpcio/grpc/_cython/cygrpc.o: No space left on device
  creating None
  creating None/tmp
  creating None/tmp/tmpeuozutox
  aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c /tmp/tmpeuozutox/a.c -o None/tmp/tmpeuozutox/a.o
```

which is the same error.

---

While `1.35.0` (full log: 
[grpcio.log](https://github.com/grpc/grpc/files/6014232/grpcio.log), at that time `wheel` is missing but it shouldn't matter) shows:

```
    aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 python_build/temp.linux-aarch64-3.8/src/python/grpcio/grpc/_cython/cygrpc.o ...
    collect2: error: ld returned 1 exit status
```

which seemed to be caused by `ld`.

**Comment by jtattermusch** [comment]
How about the `/tmp/ccrjBXGh.s: Assembler messages:
  /tmp/ccrjBXGh.s: Fatal error: can't close python_build/temp.linux-aarch64-3.8/src/python/grpcio/grpc/_cython/cygrpc.o: No space left on device` problem that's in one of the logs?

Sorry this still looks that there problem you're seeing is not grpc related.

**Comment by jtattermusch** [comment]
So far it looks like this is failing for other reasons (e.g. your disk is full etc.). I can reopen once there's more evidence that there is an actual problem in grpc.

**Comment by pPanda-beta** [comment]
Sorry for late reply. 

@jtattermusch Please solve the first problem mentioned here : 

```
    cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
    creating None/tmp/tmpozib8837
    gcc -pthread -DNDEBUG -O2 -fPIC -I/opt/pypy/include -c /tmp/tmpozib8837/a.c -o None/tmp/tmpozib8837/a.o
    Traceback (most recent call last):
      File "/opt/pypy/lib-python/3/distutils/unixccompiler.py", line 133, in _compile
        extra_postargs)
      File "/tmp/pip-install-yfj14vha/grpcio_c3ebdd327f1947668d50df5f87ac1409/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/opt/pypy/lib-python/3/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/opt/pypy/lib-python/3/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/opt/pypy/lib-python/3/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

```

Clearly the directory resolution is broken here.
### This line is toxic : 
`gcc -pthread -DNDEBUG -O2 -fPIC -I/opt/pypy/include -c /tmp/tmpozib8837/a.c -o None/tmp/tmpozib8837/a.o`

### How to reproduce?
`docker run -it pypy:3.7-7.3.3 pip install grpcio==1.35.0`

**Comment by pPanda-beta** [comment]
@jtattermusch Please reopen it.

**Comment by jtattermusch** [comment]
I was able to reproduce by running:
```
docker run -it pypy:3.7-7.3.3 pip install grpcio==1.35.0
```

It looks like that this bug has nothing to do with aarch64 (as it can be reproduced on intel). 
Looks like it is related to pypy? I'm actually not sure to which extent pypy is supported.

Assigning back to @lidizheng

**Comment by pPanda-beta** [comment]
@jtattermusch 
Can you please point me to the cmake build scrips and any other python based build scripts? 
I believe some extremely CPython specific variable is fetched and used in a f-string, which produces in correct root dir : `None/tmp/tmpozib8837/a.o`
(Probably missing a None-check)

**Comment by jtattermusch** [comment]
> @jtattermusch
> Can you please point me to the cmake build scrips and any other python based build scripts?
> I believe some extremely CPython specific variable is fetched and used in a f-string, which produces incorrect root dir : `None/tmp/tmpozib8837/a.o`
> (Probably missing a None-check)

The entry point for everything is https://github.com/grpc/grpc/blob/master/setup.py and https://github.com/grpc/grpc/blob/master/tools/distrib/python/grpcio_tools/setup.py

**Comment by KumaTea** [comment]
> So far it looks like this is failing for other reasons (e.g. your disk is full etc.). I can reopen once there's more evidence that there is an actual problem in grpc.

Just to mention: `grpcio` 1.36.1 can be successfully built in (C)Python 3.6 - 3.9, while I have not tested PyPy on this version yet.

**Comment by lidizheng** [comment]
@pPanda-beta There is a PR https://github.com/grpc/grpc/pull/25778 fixing the gcc warning "cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C". But this warning won't led to compilation failure, you may need to search the whole build output to find the lines has `error:` in it.

**Comment by pPanda-beta** [comment]
@lidizheng  Please check the error I've mentioned previously : https://github.com/grpc/grpc/issues/25112#issuecomment-787059554

This is not warning. This is serious problem determining the output path of object files. 

No unix based system in this world can survive paths like `None/tmp/tmpozib8837/a.o`

**Comment by lidizheng** [comment]
```
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

`None/tmp/tmpozib8837/a.o` is a relative path, it will create a folder named `None` in the current work directory (this is a really bad name choice, I guess we overfitted our test infra). It should work fine.

The exception says "gcc" failed, the compiler usually failed because of errors. When you got a second, can you run the installation again and post the full installation log?

**Comment by pPanda-beta** [comment]
Sure here you go: 

[grpcio.fail.log](https://github.com/grpc/grpc/files/6261034/grpcio.fail.log)

I've generated this using : 
`docker run -it pypy:3.7-7.3.3 pip install grpcio==1.35.0` 

You can also try `pip install -vvv ...` for more verbosity.

**Comment by pPanda-beta** [comment]
## My observations:

So far with output location s ` ... -o python_build/temp.linux-x86_64-3.7/third_party/cares/cares/ ...`
it was happily compiling with some warnings only.
```
...
    gcc -pthread -DNDEBUG -O2 -fPIC -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/zlib -I/opt/pypy/include -c third_party/cares/cares/ares_expand_name.c -o python_build/temp.linux-x86_64-3.7/third_party/cares/cares/ares_expand_name.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
...
```

The moment `None/tmp/...` (<- I still believe this is a null mis handling) as path came into picture, it got failed

```
    creating None/tmp/tmpja36ep5_
    gcc -pthread -DNDEBUG -O2 -fPIC -I/opt/pypy/include -c /tmp/tmpja36ep5_/a.c -o None/tmp/tmpja36ep5_/a.o
    Traceback (most recent call last):
      File "/opt/pypy/lib-python/3/distutils/unixccompiler.py", line 133, in _compile
        extra_postargs)
      File "/tmp/pip-install-w0nhm9qp/grpcio_6484532787cd46d8b527e0dce19028c2/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/opt/pypy/lib-python/3/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/opt/pypy/lib-python/3/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/opt/pypy/lib-python/3/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

I think it could be some directory mismatch. Need to extract out stderr for gcc child process at that moment.

**Comment by lidizheng** [comment]
```
src/python/grpcio/grpc/_cython/cygrpc.cpp: In function ‘int __Pyx_async_gen_init_hooks(__pyx_PyAsyncGenObject*)’:
    src/python/grpcio/grpc/_cython/cygrpc.cpp:148257:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘async_gen_finalizer’
         finalizer = tstate->async_gen_finalizer;
                             ^~~~~~~~~~~~~~~~~~~
    src/python/grpcio/grpc/_cython/cygrpc.cpp:148262:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘async_gen_firstiter’
         firstiter = tstate->async_gen_firstiter;
                             ^~~~~~~~~~~~~~~~~~~
```

This is a known Pypy issue: https://foss.heptapod.net/pypy/pypy/-/issues/3280
Duplicates with https://github.com/grpc/grpc/issues/4221

Based on code, the `async_gen_firstiter` is added to CPython after 3.6. There is a possibility Pypy isn't implemented this CPython C API, and I can't find this symbol in Pypy's source code.

I would say maybe comment on the https://github.com/grpc/grpc/issues/4221 thread?

**Comment by pPanda-beta** [comment]
Okay, is that the root cause?
I'm still trying to figure out why `a.c` compilation got failed. 

Is there any chance that both the errors are independent?

But anyways, as a bird eye level view this seems a pypy support problem only.

**Comment by lidizheng** [comment]
I think `a.c` compilation passed. It's the `cygrpc.cpp` compilation that failed (90% of cases caused by this one), which is the gRPC Core and Python intersection.

Based on [change log](https://doc.pypy.org/en/latest/release-v7.3.3.html) of Pypy v7.3.3, the `async for` is supported. I guess Cython might use an internal API here. If you need this feature strongly, can you help to investigate more? E.g., why Cython is using this API, and why it is not presented in Pypy.

**Comment by hypnobear33** [comment]
I've faced the same issue trying to install `grpcio==1.37.0` on `ubuntu18.04` with `python3.8` for `aarch64-linux-gnu-gcc`
Here's a piece of the stacktrace:
```
    Traceback (most recent call last):
      File "/tmp/pip-install-8micdhtj/grpcio_bcb2d7e87c6041d8bf8fe31dc67e3367/src/python/grpcio/commands.py", line 267, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/tmp/pip-install-8micdhtj/grpcio_bcb2d7e87c6041d8bf8fe31dc67e3367/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
        multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
      File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
        raise self._value
      File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
        return list(map(*args))
      File "/tmp/pip-install-8micdhtj/grpcio_bcb2d7e87c6041d8bf8fe31dc67e3367/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8micdhtj/grpcio_bcb2d7e87c6041d8bf8fe31dc67e3367/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8micdhtj/grpcio_bcb2d7e87c6041d8bf8fe31dc67e3367/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hj0ig2fj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/grpcio Check the logs for full command output.
```

**Comment by lidizheng** [comment]
@hypnobear33 Can you open up a new issue for compilation errors? The real cause should be somewhere in the logs.

Besides, it's hard to get compilation right. I would recommend to use the compiled wheels instead. [Wheels list](https://pypi.org/project/grpcio/#files).

Please download the wheel, upgrade the `pip`, and try install it again: https://files.pythonhosted.org/packages/d8/88/c8e2d5be2d8052901d25aba5707f02ad5c55dc656e911e894678b54e8beb/grpcio-1.37.0-cp38-cp38-manylinux2014_aarch64.whl

**Comment by hypnobear33** [comment]
@lidizheng thanks, I'll try
