### ISSUE TITLE
License is missing required information. Copyright owner?

### ISSUE THREAD

**Issue by ahernsean** [grpc/grpc#25113]
The Apache license requires that the copyright owner be identified. Quoting from the license file here in the release:

```
   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]
```
For this to be valid, the copyright owner needs to be identified and a year provided.

**Comment by jtattermusch** [comment]
I'm not a lawyer but to my knowledge our source files start with the "Copyright [yyyy] The gRPC Authors" header: 

e.g. here "https://github.com/grpc/grpc/blob/0d7e17ff802921a53a409c62dd5eeb66fa0e5c0f/src/csharp/Grpc.Core/Server.cs#L3

so I'm not convinced there's a problem.

**Comment by jtattermusch** [comment]
CC @srini100

**Comment by jtattermusch** [comment]
CC @thisisnotapril

**Comment by ahernsean** [comment]
> I'm not a lawyer but to my knowledge our source files start with the "Copyright [yyyy] The gRPC Authors" header:
> 
> e.g. here:
> 
> https://github.com/grpc/grpc/blob/0d7e17ff802921a53a409c62dd5eeb66fa0e5c0f/src/csharp/Grpc.Core/Server.cs#L3
> 
> so I'm not convinced there's a problem.

I'm not talking about source files. It's great that you have the copyright there. But this bug is about the License file.

**Comment by jtattermusch** [comment]
@ahernsean  can you show an example of some other opensource projects under Apache2 where this is being done? I tried to look up a few and all seem to have the same LICENSE file as we do.

e.g. 
here: https://github.com/kubernetes/kubernetes/blob/master/LICENSE
https://github.com/tensorflow/tensorflow/blob/master/LICENSE

**Comment by ahernsean** [comment]
1. https://github.com/deedy/Apache-License
2. Android: https://github.com/aosp-mirror/platform_system_core/commit/cbb1011c95e0c25c29e40e203a6a31bccd029da3

The bottom of [this](https://www.apache.org/licenses/LICENSE-2.0.html) gives the official instructions about how to apply the license.

Though now that I look at some major projects like [Swift](https://swift.org/LICENSE.txt) and the [Apache httpd server](https://svn.apache.org/viewvc/httpd/httpd/trunk/LICENSE?view=markup), I wonder if I'm mistaken here.

**Comment by jtattermusch** [comment]
My understanding is that the "copyright" line should be in the actual source files (as it already is in our case), but for most open source projects I've seen have the contents of LICENSE file itself unmodified (as in examples both you and I have presented). As said I'm not a lawyer but based on what I've seen I think we should be fine.

**Comment by ahernsean** [comment]
Then I leave it up to you guys whether you want to follow the Android route (fill in the [brackets] in the license file) or the Swift route (leave [brackets] unmodified from original license). Feel free to close this ticket if you like.
