### ISSUE TITLE
Implement connectivity API for Objective-C

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2513]
#2477 introduced the C core API for checking the connectivity state of a channel. This API needs to be wrapped and exposed in any language that exposes a channel-like abstraction.

**Comment by jcanizales** [comment]
The Objective-C library doesn't expose channels. But if we decided to do so in the future, I'd like to leave this around as a reminder.

**Comment by ctiller** [comment]
It may be worth considering adding something to your stubs then. @a11r - thoughts on this?

**Comment by jcanizales** [comment]
One of the projects using the library has already found a use for this, so it'll be exposed somewhere that makes sense.

**Comment by jcanizales** [comment]
To leave this on the record: This feature is specially important for mobiles, due to our wanting people not to use timeouts. If the server becomes unreachable, the user should be warned in the UI even if the C layer keeps trying.
