### ISSUE TITLE
difference between protoloader and generated .js files from grpc

### ISSUE THREAD

**Issue by hounaidarekik** [grpc/grpc#25146]
Hi,
I am a beginner in GRPC and nodejs.
For the first time, I use protoloader to load my services from proto. Then, I want to switch to use generated files from grpc: in my case I have: comment_pb.js, So I replace this code with:
````
import protoLoader from '@grpc/proto-loader';

const packageDefinition = protoLoader.loadSync('../../../protos/comment.proto', {
    keepCase: true,
    longs: String,
    enums: String,
    arrays: true
  });

  //pass proto in grpc 
  var commentProto = grpc.loadPackageDefinition(packageDefinition);`
```
with:
`import protoLoader from './proto/comment_pb.js';`
I don't know what's the diff between this two methods, does this change the rest of code? there any links explain this modification?? Thanks for your help!!

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
