### ISSUE TITLE
C++ compression interface support

### ISSUE THREAD

**Issue by madaoCN** [grpc/grpc#25156]
### Is your feature request related to a problem? Please describe.

grpc-go support registers the compressor with gRPC by its name as following:

```
func RegisterCompressor(c Compressor) {
    registeredCompressor[c.Name()] = c
}
```

srouce code at [https://github.com/grpc/grpc-go/blob/master/encoding/encoding.go](https://github.com/grpc/grpc-go/blob/master/encoding/encoding.go)

And the server written by golang customize a compression algorithms，but  the client written by c++ does not support the algorithms.

### Describe the solution you'd like

As one idea,
- define an Compressor: 
```
/**
 * Represents a message compressor.
 */
public class Compressor {

public:

    /*
     * Returns the message encoding that this compressor uses
     */
    virtual std::string messageEncoding();

    /*
     * Wraps an existing buffer with a compressing buffer
     *  @param is The input buffer of uncompressed data
     *  @return a buffer that compresses
     */
    virtual ByteBuffer* compress(ByteBuffer* buffer);
};
```

- define an Decompressor: 
```
/**
 * Represents a message decompressor.
 */
public class DeCompressor {

public:

    /*
     * Returns the message encoding that this compressor uses
     */
    virtual std::string messageEncoding();

    /*
     * Wraps an existing buffer with a compressing buffer
     *  @param is The input buffer of compressed data
     *  @return a buffer that decompresses
     */
    virtual ByteBuffer* decompress(ByteBuffer* buffer);
};
```

- reigister customize compressor: 
```
void RegisterCompressor(Compressor Compressor);
void RegisterDeCompressor(DeCompressor dempressor);
```

- finally, we can set channelArguments to active the compressor and decompressor as fllowing:  
```
auto channelArgs = grpc::ChannelArguments();
channelArgs.SetCompressor(compressor);
channelArgs.SetDeCompressor(dempressor);
```

### Describe alternatives you've considered
- fork grpc source, add option for `grpc_compression_algorithm `,  and then realize the algorithm by myself.

**Comment by madaoCN** [comment]
Hi, Is there any plan to support this feature? @markdroth

**Comment by markdroth** [comment]
Unfortunately, we probably won't get to this any time soon, since we have too many other higher priorities at the moment.

**Comment by madaoCN** [comment]
Thanks for answering  @markdroth

**Comment by mattnworb** [comment]
@markdroth would you and the team be open to PRs on this topic or https://github.com/grpc/grpc/issues/25390 (adding Snappy support)?
