### ISSUE TITLE
FLAKE: exe.test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#25165]
https://source.cloud.google.com/results/invocations/5c9b6402-c2b4-452e-ab86-5a46d3050a84/targets/%2F%2Ftest%2Fcpp%2Fclient:destroy_grpclb_channel_with_active_connect_stress_test/tests

```
E0114 15:56:37.466000000  2548 src/core/lib/iomgr/socket_windows.cc:122] assertion failed: info->closure == NULL
*** SIGABRT received at time=1610639797 ***
```

**Comment by ananda1066** [comment]
Still flaky with 5 failures in past week:
{
    "job_name": "grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg",
    "build_id": "13044",
    "build_url": "https://source.cloud.google.com/results/invocations/2d825bc9-2ad3-40f2-89c1-4ee42011f43c",
    "test_target": "//test/cpp/client:destroy_grpclb_channel_with_active_connect_stress_test",
    "test_case": "test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe",
    "result": "FAILED",
    "timestamp": "2021-07-09 18:51:35.099 UTC",
    "duration": "5.917",
    "test_class_name": ""
  },
  {
    "job_name": "grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg",
    "build_id": "13043",
    "build_url": "https://source.cloud.google.com/results/invocations/1a56f326-35bc-430b-96fb-4422f635fe0b",
    "test_target": "//test/cpp/client:destroy_grpclb_channel_with_active_connect_stress_test",
    "test_case": "test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe",
    "result": "FAILED",
    "timestamp": "2021-07-09 18:29:42.343 UTC",
    "duration": "3.0",
    "test_class_name": ""
  },
  {
    "job_name": "grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg",
    "build_id": "13033",
    "build_url": "https://source.cloud.google.com/results/invocations/346cc289-1602-474f-b408-48c0cf8a76f6",
    "test_target": "//test/cpp/client:destroy_grpclb_channel_with_active_connect_stress_test",
    "test_case": "test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe",
    "result": "FAILED",
    "timestamp": "2021-07-09 00:48:47.734 UTC",
    "duration": "3.562",
    "test_class_name": ""
  },
  {
    "job_name": "grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg",
    "build_id": "13024",
    "build_url": "https://source.cloud.google.com/results/invocations/11393303-e33f-4416-ae4f-5b46733042a4",
    "test_target": "//test/cpp/client:destroy_grpclb_channel_with_active_connect_stress_test",
    "test_case": "test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe",
    "result": "FAILED",
    "timestamp": "2021-07-08 16:50:29.475 UTC",
    "duration": "4.143",
    "test_class_name": ""
  },
  {
    "job_name": "grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg",
    "build_id": "13015",
    "build_url": "https://source.cloud.google.com/results/invocations/8aefe96a-8994-4c04-ab26-75d1979335d3",
    "test_target": "//test/cpp/client:destroy_grpclb_channel_with_active_connect_stress_test",
    "test_case": "test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe",
    "result": "FAILED",
    "timestamp": "2021-07-08 01:12:46.197 UTC",
    "duration": "3.696",
    "test_class_name": ""
  },
  {
    "job_name": "grpc/core/master/windows/bazel_rbe/grpc_bazel_rbe_dbg",
    "build_id": "13013",
    "build_url": "https://source.cloud.google.com/results/invocations/fc7c1765-ca39-41b3-a9db-d2c38fae292d",
    "test_target": "//test/cpp/client:destroy_grpclb_channel_with_active_connect_stress_test",
    "test_case": "test/cpp/client/destroy_grpclb_channel_with_active_connect_stress_test.exe",
    "result": "FAILED",
    "timestamp": "2021-07-07 20:36:26.183 UTC",
    "duration": "3.638",
    "test_class_name": ""
  }

**Comment by apolcyn** [comment]
This should actually have been fixed by https://github.com/grpc/grpc/pull/26642 (which was merged around noon PST on July 9th).

I think this still shows up in the last week's top five flakes only because the query includes the window of time before the PR was merged.
