### ISSUE TITLE
grpc_cli build does not respect CMAKE_INSTALL_RPATH

### ISSUE THREAD

**Issue by carlocab** [grpc/grpc#25176]
### What version of gRPC and what language are you using?
v1.34.1, C++

### What operating system (Linux, Windows,...) and version?
macOS 11.1 on Apple M1

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 12.0.0 (clang-1200.0.32.28)

### What did you do?
I am updating Homebrew grpc at https://github.com/Homebrew/homebrew-core/pull/69125. The grpc library and grpc_cli build without errors. 

However, CI encountered an error when testing grpc_cli:

```
==> /usr/bin/clang test.cpp -I/opt/homebrew/Cellar/grpc/1.34.1/include -L/opt/homebrew/Cellar/grpc/1.34.1/lib -lgrpc -o test
==> ./test
==> grpc_cli ls localhost:61923 2>&1
sh: line 1: 52165 Abort trap: 6           grpc_cli ls localhost:61923 2>&1
dyld: Library not loaded: @rpath/libgrpc++.1.dylib
  Referenced from: /opt/homebrew/bin/grpc_cli
  Reason: image not found
```

CI run logs available at https://github.com/Homebrew/homebrew-core/pull/69125/checks?check_run_id=1711232122.

### What did you expect to see?
`grpc_cli` should find its libraries and produce the error message `Received an error when querying services endpoint.` This is what happens when `grpc_cli` is installed into `/usr/local`.

### What did you see instead?
The error message shown above.

### Anything else we should know about your project / environment?
For a CI run without the `CMAKE_INSTALL_RPATH` defined, see https://github.com/Homebrew/homebrew-core/runs/1711135820. This makes the C++ library unusable given Homebrew's install prefix on Apple M1 (`/opt/homebrew`).

For reference, the `test.cpp` referenced above is
```cpp
#include <grpc/grpc.h>
int main() {
  grpc_init();
  grpc_shutdown();
  return GRPC_STATUS_OK;
}
```

Additionally, manually adding the appropriate `rpath` to grpc's binary executables works around the error. See https://github.com/Homebrew/homebrew-core/pull/68585

**Comment by drfloob** [comment]
@veblush @jtattermusch I believe this cmake issue is related to #25176. If so, feel free to deduplicate the issues.

**Comment by carlocab** [comment]
Thanks for having a look, but I think we've managed to resolve/work around this issue on our side since then.
