### ISSUE TITLE
Ensure census context can be passed from incoming requests to outgoing requests in Ruby

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2517]

**Comment by tbetbetbe** [comment]
This is already possible:
- server handlers already have access to metadata that is sent to them
- stubs can add arbitrary metadata
- if the code in the server handler makes a request via a stub, the application writer can already propagate the values in the incoming to the outgoing

Will mark as closed for now, please re-open if there is more to this issue

**Comment by murgatroid99** [comment]
That stuff is not sufficient. This is referring to the core API exposed in #2750, and also maybe somehow related to the API exposed in [census.h](https://github.com/grpc/grpc/blob/master/include/grpc/census.h).

**Comment by ctiller** [comment]
Plumbing up #2750 is sufficient.
