### ISSUE TITLE
Segfault in master grpc_distribtests csharp_linux_x64_alpine_dotnetcli

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#25174]
The prod:grpc/core/master/linux/grpc_distribtests job has been consistently failing since Jan 14th, [dashboard](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests).

```
+ dotnet exec bin/Debug/netcoreapp2.1/DistribTestDotNet.dll
test/distrib/csharp/run_distrib_test_dotnetcli.sh: line 54:   259 Segmentation fault      (core dumped) dotnet exec bin/Debug/netcoreapp2.1/DistribTestDotNet.dll
+ FAILED=true
+ '[' '' '!=' '' ']'
+ docker rm -f build_and_run_docker_9b106c8b-7a41-4ef3-8a72-99911dd10f5b
build_and_run_docker_9b106c8b-7a41-4ef3-8a72-99911dd10f5b
+ '[' true '!=' '' ']'
+ exit 1

2021-01-15 09:47:48,693 FAILED: distribtest.csharp_linux_x64_alpine_dotnetcli [ret=1, pid=14462, time=52.0sec]
```

**Comment by jtattermusch** [comment]
Tracked internally as b/177904713

**Comment by jtattermusch** [comment]
I looked at the diff between the last working build and the first broken build and found this PR:
https://github.com/grpc/grpc/pull/25140  I'll need to see whether it could have caused the problem.

**Comment by jtattermusch** [comment]
I tracked the problem down to https://github.com/grpc/grpc/pull/25140 and created a revert PR: https://github.com/grpc/grpc/pull/25212. I'll comment more on the internal bug.

**Comment by stanley-cheung** [comment]
This is fixed by the revert.
