### ISSUE TITLE
how to compile 32bit grpc c++ on linux red hat 64 bit

### ISSUE THREAD

**Issue by esolel** [grpc/grpc#25182]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by markdroth** [comment]
As mentioned in the issue template (which you didn't even modify in your post above), questions should be posted to StackOverflow or to the grpc.io mailing list, not here.
