### ISSUE TITLE
gRPC channel over custom OS level connection

### ISSUE THREAD

**Issue by greendev5** [grpc/grpc#25181]
Hi everyone,

I want to discuss with you some missing functionality of gRPC, which I would like to have and willing to contribute (if it is really missung now). But I am not sure is it compatible with gRPC ideology.

gRPC protocol stack is looks like this now:
1. TCP/UnixDomainSocket - streaming socket
2. TLS - for encryption and host verification 
3. HTTP/2, including nice capability to multiplex parallel data streams from single TCP/TLS socket
4. gRPC itself

So, to send gRPC request we should do next on every level:
1. gRPC client calls connect OS method, gRPC server calls accept
2. gRPC client sends TLS client hello to server, server process this TLS connection
3. gRPC client send HTTP/2 request and wait for response,
4. gRPC servers calls required method

The problem here, is that I did not find a way how to  make TCP/TLS client gRPC server. When TCP/TLS server (level 1-2) accepts connection and creates socket, but after that behaves like HTTP/2/gRPC client with this socket (level 3-4) - sends HTTP/2 request, create gRPC channels, etc.

I am working on distributed system, where nodes of this system distributed around the internet and can be added/removed  dynamically.  Also the may be behind the NAT, so the nodes should initiate TCP connection. Also from the logic of our system, nodes provide services, not consume main server.

A good example of such system is IOT device smart  light bulb, which can establish connection to server and provide gRPC services, like trurnLightOn, setLightPover, etc. In this case the bulb is gRPC server.

The only way how I can implement such logic now is bi-direction gRPC stream, where the node is connected to server via TCP, opens gRPC stream and waits for requests. But in this case we are loosing HTTP/2 multiplexing capabilities.

For example I can send several gRPC calls to server in parallel throw single TCP/TLS stream and HTTP/2 will care about it. With bi-direction client stream I should care about multiplexing myself, or create multiple gRPC streams, both ways are ugly.

Maybe it would be nice feature to separate TCP/TLS and HTTP2/gRPC levels in the c core library?

**Comment by markdroth** [comment]
The gRPC protocol is designed such that TCP connections are always initiated by the client, not the server.  It doesn't really make sense to have a server initiate connections.

I think the bi-di stream approach you suggest is the right approach to use for the use-case you describe.  I think you should be able to build your own application-level protocol on top of a bi-di stream that allows multiplexing.

Good luck!
