### ISSUE TITLE
Bazel: declared output 'src/compiler/grpc_python_plugin.bin' was not created by genrule. 

### ISSUE THREAD

**Issue by PureTryOut** [grpc/grpc#25188]
I'm trying to get Tensorflow compiling, but am currently stuck on an issue with it's dependency on grpc. I was told to report it here, so here I am.

### What version of gRPC and what language are you using?
1.34.1, C++

### What operating system (Linux, Windows,...) and version?
Alpine Linux edge

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 10.2.1

### What did you do?
I've been trying to compile Tensorflow, which has grpc as one of it's dependencies. See [this issue](https://github.com/tensorflow/tensorflow/issues/45446) on the Tensorflow repo. This uses the Bazel build system. However, right now it's failing on grpc.

I have to note that grpc itself comes from the Alpine Linux repositories in my case, not sure if that matters.

### What did you expect to see?
grpc to compile successfully

### What did you see instead?

```
ERROR: /home/bart/.cache/bazel/_bazel_bart/fa04af0b72c1747dcd0d716042f56ed5/external/com_github_grpc_grpc/src/compiler/BUILD:66:8: declared output 'external/com_github_grpc_grpc/src/compiler/grpc_python_plugin.bin' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /home/bart/.cache/bazel/_bazel_bart/fa04af0b72c1747dcd0d716042f56ed5/external/com_github_grpc_grpc/src/compiler/BUILD:66:8: not all outputs were created or valid
ERROR: /home/bart/Documents/Git/alpine/aports/testing/tensorflow/src/tensorflow-2.4.0/tensorflow/python/tools/BUILD:143:10 not all outputs were created or valid
```

### Anything else we should know about your project / environment?
As mentioned, this is in an effort to get Tensorflow compiling, both these projects use Bazel. I'm personally unsure if the build rules from grpc are even used or if Tensorflow has it's own build rules for it, but I was told to file an issue here.

**Comment by veblush** [comment]
Closing this as the original issue was closed.
