### ISSUE TITLE
Setup user-agent string for Python

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2520]
#2370 introduced core API's for user agent string manipulation.
Each language should ensure that it adds a channel argument with key= GRPC_ARG_PRIMARY_USER_AGENT_STRING (in grpc.h) and a value as defined in https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md.

For example, Ruby release 1.2.3 would set it to "grpc-ruby/1.2.3"

**Comment by ctiller** [comment]
Implementations would be encouraged to ensure that the version string does not need to be set in many different places.

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm, I think this is very separable from everything else that we're doing. The version number is currently encoded in setup.py, right? Is there a way to make it accessible from inside the code? What if we moved it into the code itself; could setup.py find it there?

I think the legacy libraries do something smart with not-replicating-the-version-number-thither-and-yon; we may want to follow what they do.

**Comment by soltanmm** [comment]
First thing that comes to mind is having `setup.py` generate a file at build-time and place it in the package tree (as things are similarly done e.g. in 'configure' steps of lotsa libs). Alternatively, it *should* be possible for setup.py to find files in the package tree (it certainly can find them just about anywhere else).

I'm weakly against the idea of putting the version number anywhere else but `setup.py`, as that's where the other bits of our metadata go and where most projects seem to put their project metadata.
