### ISSUE TITLE
Allow user to embed the CallCredentials even in insecure channel

### ISSUE THREAD

**Issue by RyanSiu1995** [grpc/grpc#25209]
### Is your feature request related to a problem? Please describe.
I want to raise the awareness on the `CallCredentials` over insecure channel.

The current Kubernetes native way to secure the connection between service mainly delegates to the service mesh. The connection will be encrypted with mTLS so there is no need to embed the SSL cert on the service itself.

This is actually the use case for the `CallCredentials` over insecure channel. If we try to establish another layer of SSL from the application layer, there will be an overhead.

### Describe the solution you'd like
Allow the user to use `CallCredentials` over insecure channel.

### Describe alternatives you've considered
Termination in the mTLS is not feasible here because you cannot assume all security engineers will allow engineers to disable the service mesh.

### Additional context
Related to issue #8142 in 5 years ago.

**Comment by jtattermusch** [comment]
AFAIK For cases where the security is delegated to the service mesh and you're communicating locally over a trusted channel, you can use LocalCredentials
https://github.com/grpc/grpc/blob/3f011c2171612edf1a54ca106a1c092e08534d33/include/grpc/grpc_security.h#L733

By using LocalCredentials you're basically telling grpc that this connection can be trusted to be able to send CallCredentials over it (which would otherwise be very risky since your secret authentication token could be sent in plain).

**Comment by RyanSiu1995** [comment]
@jtattermusch Thank you for the prompt response.
For the service mesh, the connection to another service will still use the cluster ip for the service.
For example, if we want to connect it to service `my-cool-service`, the caller will use the DNS `my-cool-service` directly.
And the traffic will be directed to the `my-cool-service` with mTLS instead. 
Here, the connection is not using neither `localhost` nor `127.0.0.1` in the code level.
So, I do not think the `LocalCredentials` will work in this case.

**Comment by RyanSiu1995** [comment]
Hi community, any update or discussion on this?

**Comment by jtattermusch** [comment]
Reassigning to @yihuazhang  who is the author of the local credentials.
https://github.com/grpc/grpc/pull/16116

@yihuazhang  @jiangtaoli2016  what is our stance on this topic? User's concern seems to be legitimate.

**Comment by RyanSiu1995** [comment]
Hi @yihuazhang, 
I totally understand the original thought on the implementation with secure channel.
Back in the day, the gRPC itself could force the users to apply the secure channel to send data to eliminate the attack surface.
Nowadays, more and more TLS and security stuff are leveraged to the infrastructure layer. Application itself simply focuses on the business logic.
Instead of changing the behavior inside the code level, would it be something like feature flags with environment variable? Or simply unblock the users during the library building? (I assume that one who need this will know how to configure the library during the building prcoess)

**Comment by yihuazhang** [comment]
Hi @RyanSiu1995, 

gRPC C-core and C++ now allow call credentials to be communicated over insecure channels by using insecure credentials (i.e., `grpc_insecure_credentials_create()`), but there is a requirement that those call credentials should not require any transport security in their communications (dictated by security level).

**Comment by alkasm** [comment]
Popping this back up for discussion as I believe this still isn't available in the Python implementation. Want to also acknowledge that grpc-go does allow `PerRPCCredentials` to _optionally_ require a secure channel: https://pkg.go.dev/google.golang.org/grpc@v1.43.0/credentials#PerRPCCredentials
