### ISSUE TITLE
C#: DllNotFoundException: grpc_csharp_ext when running under Ubuntu / Unity

### ISSUE THREAD

**Issue by minkezhang** [grpc/grpc#25223]
### What version of gRPC and what language are you using?

C#, with NuGet

| Package               | Version |
| --------------------- | ------- |
| Google.Protobuf       | 3.14.0  |
| Grpc                  | 2.34.1  |
| Grpc.Core             | 2.34.1  |
| Grpc.Core.Api         | 2.34.1  |
| Grpc.Net.Client       | 2.34.0  |
| Grpc.Tools            | 2.34.1  |
| Google.Protobuf.Tools | 3.14.0  |

### What operating system (Linux, Windows,...) and version?

Ubuntu 20.04

```bash
$ uname -a
Linux ubuntu 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

Unity 2019.4.18f1, with [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) v2.0.1 to install NuGet packages.

Project is enabled with .NET  4.x APIs.

```bash
$ mono --version  # shouldn't be relevant to Unity
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:26:45 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

```bash
$ dotnet --list-sdks  # shouldn't be relevant to Unity
5.0.102 [/usr/share/dotnet/sdk]
```

### What did you do?

Unity project at https://github.com/downflux/game/tree/feature_client_client/client/DownFlux, with repro instructions in the README.

Error occurs when attempting to start the game in Unity.

### What did you expect to see?

A running game, with error message stating no gRPC server found (nothing booted).

### What did you see instead?

```
DllNotFoundException: grpc_csharp_ext
Grpc.Core.Internal.NativeLogRedirector.Redirect (Grpc.Core.Internal.NativeMethods native) (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.Internal.NativeExtension..ctor () (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.Internal.NativeExtension.Get () (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.Internal.NativeMethods.Get () (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.GrpcEnvironment.GrpcNativeInit () (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.GrpcEnvironment..ctor () (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.GrpcEnvironment.AddRef () (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials, System.Collections.Generic.IEnumerable`1[T] options) (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials) (at <7ef7675911454b7c9df48a7a43e4fc39>:0)
DF.Game.Client.Client..ctor (System.String server, System.TimeSpan sleepDuration) (at Assets/Engine/Client/Client.cs:15)
DF.Game.Game..ctor (System.String server, DF.Game.Config config) (at Assets/Engine/Game/Game.cs:11)
Game.Start () (at Assets/Scripts/Game.cs:15)
```

### Anything else we should know about your project / environment?

This seems to be a rather common issue, see

* https://unitylist.com/p/3u9/Unity-grpc
* https://github.com/grpc/grpc/issues/12154
* https://github.com/xunit/xunit/issues/1363

I've attempted to copy the libgrpc_csharp_ext.so file from Grpc.Core to the `${UNITY_INSTALLS}/${VERSION}/Plugins` directory and reloading Unity, but this does not seem to work. Not sure where I should be putting this file, or if there is another workaround.

Any help would be greatly appreciated.

**Comment by minkezhang** [comment]
Update: The workaround is to

1. unzip Grpc.Core.2.34.1.nupkg
1. cp `runtimes/linux_x64/native/libgrpc_csharp_ext.x64.so` -> `Assets/Plugins/libgrpc_csharp_ext.so`

Looks like gRPC does some DLL path futzing ([code](https://github.com/grpc/grpc/blob/0ebae4e0656fb2e05d8a98b28c58566851e7e1cc/src/csharp/Grpc.Core/Internal/NativeMethods.Generated.cs#L1336)), but it's unclear as to why we need to manually load the file, when it's already included in the package.

I assume if I want to build for Windows or other architecture, I will need to copy the corresponding object files from `runtime/` into the same Plugin directory.

As per https://unitylist.com/p/3u9/Unity-grpc, this issue seems to be around for at least three years; is this a problem with perhaps Unity?

**Comment by jtattermusch** [comment]
Nuget packages haven't been designed to be used with Unity and https://github.com/GlitchEnzo/NuGetForUnity sounds like a neat tool, but it doesn't seem like it's officially supported neither by Unity or nuget. I suspect NuGetForUnity simply doesn't correctly handle nugets that come with native libraries and that's why the workaround of copying the native library (libgrpc_csharp_ext) is required.

This is gRPC's instructions how to use our "unity package" (note that it doesn't involve NuGetForUnity at all).
https://github.com/grpc/grpc/tree/master/src/csharp/experimental#unity
