### ISSUE TITLE
How can we specify to use Http2 with an insecure channel and a kestrel backend able to handle Http1AndHttp2 protocol?

### ISSUE THREAD

**Issue by GFlisch** [grpc/grpc#25225]
I have a kestrel backend with Rest Apis and gRPC services.
As we offer swagger we have to offer Http1 and for gRPC Http2.
In production everything (even k8s) is working because we have the ingress layer exposing our services with https, negotiation is started and gRPC calls are working well => http2 is used.

On our development pc, we use docker desktop and k8s. The services are not using https but http (no ingress layer is used) and the call to the backend failed. If (for test purpose) I force http2 everything is working well.
I can't use the Grpc.Net.Client library because my clients are Uwp and Wpf applications who doesn't accept .NetStandard 2.1.
I don't see a way to force the version of the request to Http2 like I can do when I have access to an HttpHandler (via HttpClient).

Do you see a way to force this?

Thanks.

**Comment by jtattermusch** [comment]
The "new issue" form clearly asks users not to post questions as github issues. Next time please follow the instructions and use the channels mentioned below to ask questions.

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
>

**Comment by jtattermusch** [comment]
You are saying you can't use Grpc.Net.Client, so are you currently using Grpc.Core?
If so, I don't see how your scenario can not work since Grpc.Core always uses HTTP/2 when creating connections (in fact the grpc.core's http implementation only supports HTTP/2).

Are you looking for an option on the server side or on the client side?

**Comment by GFlisch** [comment]
Hi indeed, I am using Grpc.Core and only http/2 is possible but I presume that when the service is running with Http1AndHttp2 the http/2 call doesn't seems to be handled correctly.

For the moment I am looking for a client side and after I will do the same from the BE. Will try in this case with package Grpc.AspNetCore.Server.ClientFactory... but not yet there.

**Comment by GFlisch** [comment]
I have found the issue.

On the .net code I have to add this line of code.

AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

from:
https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#call-insecure-grpc-services-with-net-core-client

And https://github.com/grpc/grpc-dotnet/issues/505.
