### ISSUE TITLE
Artifact Build Windows (internal CI) build fails

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#25238]
T:\src\github\grpc>If "true" == "true" (powershell -File tools\internal_ci\helper_scripts\install_python_interpreters.ps1   || goto :error )
Downloading the Python installer: https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe => C:\tools\python-3.8.0.exe
T:\src\github\grpc\tools\internal_ci\helper_scripts\install_python_interpreters.ps1 : Invalid Python installer: failed
checksum!
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,install_python_interpreters.ps1

**Comment by donnadionne** [comment]
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[16:36:01] Transferring environment variable script to build VM
[16:36:02] Transferring kokoro_log_reader.py to build VM
[16:36:02] Transferring source code to build VM
[16:36:05] Executing build script on build VM



[ID: 6864414] Executing command via SSH:
export KOKORO_BUILD_NUMBER="22097"
export KOKORO_JOB_NAME="grpc/core/pull_request/windows/grpc_build_artifacts"
source /tmpfs/kokoro-env_vars.sh; cd /tmpfs/src/ ;  nohup bash -c "( rm -f /tmpfs/kokoro_build_exit_code ; cmd /c 'github\grpc\tools\internal_ci\windows\grpc_build_artifacts.bat'   ; echo \${PIPESTATUS[0]} > /tmpfs/kokoro_build_exit_code ) > /tmpfs/kokoro_build.log 2>&1" > /dev/null 2>&1 & echo $! > /tmpfs/kokoro_build.pid ; cmd /c 'C:/python27/python.exe T:/kokoro_log_reader.py T:/kokoro_build.log T:/kokoro_build_exit_code T:/kokoro_build.pid T:/kokoro_log_reader.pid --start_byte 0'


T:\src>choco uninstall yasm -y --limit-output
Uninstalling the following packages:
yasm

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - yasm - yasm is not installed. Cannot uninstall a non-existent package.

If a package uninstall is failing and/or you've already uninstalled the
 software outside of Chocolatey, you can attempt to run the command
 with `-n` to skip running a chocolateyUninstall script, additionally
 adding `--skip-autouninstaller` to skip an attempt to automatically
 remove system-installed software. This will only remove the packaging
 files and not things like software installed to Programs and Features.

If a package is failing because it is a dependency of another package
 or packages, then you may first need to consider if it needs removed
 as it is typically installed as a dependency for a reason. If you
 decide that you still want to remove it, head into
 `$env:ChocolateyInstall\lib` and find the package folder you want
 removed. Then delete the folder for the package. This option should
 only be used as a last resort.


T:\src>choco install nasm -y --limit-output
Installing the following packages:
nasm
By installing you accept licenses for the packages.

Progress: Downloading nasm 2.14.02... 15%
Progress: Downloading nasm 2.14.02... 49%
Progress: Downloading nasm 2.14.02... 82%
Progress: Downloading nasm 2.14.02... 100%

nasm v2.14.02 [Approved]
nasm package files install completed. Performing other installation steps.
Downloading nasm 64 bit
  from 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'

Progress: 7% - Saving 70.2 KB of 933.77 KB
Progress: 15% - Saving 148.32 KB of 933.77 KB
Progress: 24% - Saving 226.45 KB of 933.77 KB
Progress: 32% - Saving 304.57 KB of 933.77 KB
Progress: 40% - Saving 382.7 KB of 933.77 KB
Progress: 49% - Saving 460.82 KB of 933.77 KB
Progress: 57% - Saving 538.95 KB of 933.77 KB
Progress: 66% - Saving 617.07 KB of 933.77 KB
Progress: 74% - Saving 695.2 KB of 933.77 KB
Progress: 82% - Saving 773.32 KB of 933.77 KB
Progress: 91% - Saving 851.45 KB of 933.77 KB
Progress: 99% - Saving 929.57 KB of 933.77 KB
Progress: 100% - Completed download of T:\tmp\chocolatey\nasm\2.14.02\nasm-2.14.02-installer-x64.exe (933.77 KB).
Download of nasm-2.14.02-installer-x64.exe (933.77 KB) completed.
Hashes match.
Installing nasm...
nasm has been installed.
 The install of nasm was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

T:\src>cd /d T:\src\github\grpc\tools\internal_ci\windows\\..\..\..

T:\src\github\grpc>set PREPARE_BUILD_INSTALL_DEPS_PYTHON=true

T:\src\github\grpc>call tools/internal_ci/helper_scripts/prepare_build_windows.bat   || exit /b 1

T:\src\github\grpc>set PATH=C:\tools\msys64\usr\bin;C:\Python27;C:\Program Files\CMake\bin;C:\cygwin64\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\cygwin64\bin;C:\Program Files\Microsoft MPI\Bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\tools\ruby25\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files\Java\jdk-9.0.1\bin;C:\Program Files\Java\jdk1.8.0_152\bin;C:\tools\php72;C:\Program Files (x86)\vim\vim80;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Users\kbuilder\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\dotnet;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\python27;C:\Go\bin;C:\bazel;C:\Users\cyg_server\AppData\Local\Microsoft\WindowsApps

T:\src\github\grpc>if defined KOKORO_GITHUB_PULL_REQUEST_NUMBER if defined RUN_TESTS_FLAGS (set RUN_TESTS_FLAGS= --filter_pr_tests --base_branch origin/master )

T:\src\github\grpc>netsh interface ip set dns "Local Area Connection 8" static 169.254.169.254 primary
The filename, directory name, or volume label syntax is incorrect.



T:\src\github\grpc>netsh interface ip add dnsservers "Local Area Connection 8" 8.8.8.8 index=2
The filename, directory name, or volume label syntax is incorrect.



T:\src\github\grpc>netsh interface ip add dnsservers "Local Area Connection 8" 8.8.4.4 index=3
The filename, directory name, or volume label syntax is incorrect.



T:\src\github\grpc>python -m pip install google-api-python-client   || goto :error
Requirement already satisfied: google-api-python-client in c:\python27\lib\site-packages (1.6.4)
Requirement already satisfied: six<2dev,>=1.6.1 in c:\python27\lib\site-packages (from google-api-python-client) (1.11.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in c:\python27\lib\site-packages (from google-api-python-client) (3.0.0)
Requirement already satisfied: oauth2client<5.0.0dev,>=1.5.0 in c:\python27\lib\site-packages (from google-api-python-client) (4.1.2)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in c:\python27\lib\site-packages (from google-api-python-client) (0.10.3)
Requirement already satisfied: rsa>=3.1.4 in c:\python27\lib\site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client) (3.4.2)
Requirement already satisfied: pyasn1-modules>=0.0.5 in c:\python27\lib\site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client) (0.2.1)
Requirement already satisfied: pyasn1>=0.1.7 in c:\python27\lib\site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client) (0.4.2)
You are using pip version 10.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

T:\src\github\grpc>powershell -File src\csharp\install_dotnet_sdk.ps1   || goto :error
Downloading install script: https://dot.net/v1/dotnet-install.ps1 => T:\tmp\dotnet-install.ps1
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.504/dotnet-sdk-2.1.504-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.504/dotnet-sdk-2.1.504-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\Users\kbuilder\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installation finished

T:\src\github\grpc>set PATH=C:\Users\kbuilder\AppData\Local\Microsoft\dotnet;C:\tools\msys64\usr\bin;C:\Python27;C:\Program Files\CMake\bin;C:\cygwin64\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\cygwin64\bin;C:\Program Files\Microsoft MPI\Bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\tools\ruby25\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files\Java\jdk-9.0.1\bin;C:\Program Files\Java\jdk1.8.0_152\bin;C:\tools\php72;C:\Program Files (x86)\vim\vim80;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Users\kbuilder\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\dotnet;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\python27;C:\Go\bin;C:\bazel;C:\Users\cyg_server\AppData\Local\Microsoft\WindowsApps

T:\src\github\grpc>set NUGET_XMLDOC_MODE=skip

T:\src\github\grpc>set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

T:\src\github\grpc>set DOTNET_CLI_TELEMETRY_OPTOUT=true

T:\src\github\grpc>If "true" == "true" (powershell -File tools\internal_ci\helper_scripts\install_python_interpreters.ps1   || goto :error )
Downloading the Python installer: https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe => C:\tools\python-3.8.0.exe
T:\src\github\grpc\tools\internal_ci\helper_scripts\install_python_interpreters.ps1 : Invalid Python installer: failed
checksum!
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,install_python_interpreters.ps1


T:\src\github\grpc>exit /b 1


[ID: 6864414] Build finished after 99 secs, exit value: 1


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[16:37:44] Collecting build artifacts from build VM
Build script failed with exit code: 1

**Comment by lidizheng** [comment]
Just checked the checksum value in [our script](https://github.com/grpc/grpc/blob/master/tools/internal_ci/helper_scripts/install_python_interpreters.ps1#L64) and python.org. The checksum is the same. This issue might be a one-time network issue that the downloaded Python installer is corrupted.

**Comment by donnadionne** [comment]
You are right, this is not reproducible! thanks for checking
