### ISSUE TITLE
master/linux/grpc_portability failing due to error from build_python.sh

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#25261]
All errors seem to point to:

VENV_PYTHON=/var/local/git/grpc/py27_native/bin/python2.7

curl https://bootstrap.pypa.io/get-pip.py

/var/local/git/grpc/py27_native/bin/python2.7
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 1883k 100 1883k 0 0 6848k 0 --:--:-- --:--:-- --:--:-- 6848k
Traceback (most recent call last):
File "", line 24226, in
File "", line 199, in main
File "", line 82, in bootstrap
File "/tmp/tmpOBM481/pip.zip/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax

According to https://stackoverflow.com/questions/65866417/pip-install-failing-on-python2, it seems that get-pip.py has moved.

**Comment by menghanl** [comment]
Is there any way to bypass this? The check "Portability Tests Linux [Build Only] (internal CI)" is failing due to this, and it's **required**. So this is blocking the PRs.

Maybe this should be p1 not p2?

**Comment by menghanl** [comment]
This was fixed by #25277 and #25260. I will cherry pick the fix into my backport PRs.
