### ISSUE TITLE
Error reporting through C++ APIs

### ISSUE THREAD

**Issue by Rantanen** [grpc/grpc#25263]
### Is your feature request related to a problem? Please describe.
We have gRPC as part of a server that the users may install in their own environment and thus need to configure by themselves. The lack of API-level error reporting makes it difficult to troubleshoot issues and to provide user-readable error messages. This includes both the server (Port in use, TLS certificate error, etc.) and client (TLS failure modes).

Currently lack of TLS, untrusted TLS certificate (including those that miss intermediate certificates), invalid host name, etc. are indistinguishable from user point of view (although in the case of the first one at least, I wouldn't be too surprised if that's just us losing that information at some point in the call chains).

### Describe the solution you'd like
Some sort of an API to provide more context on the error; Possible opt-in for performance reasons. While error objects/exceptions might provide the cleanest API, some sort of Thread Local Storage -based `get_last_error` implementation would be suitable as well.

Alternatively `set_error_info_function` similar to `gpr_set_log_function`, that would allow the application itself to figure out how it should store and/or show the error message to the user - for our purposes we could then implement that as Thread Local Storage -based error storage that the caller can check in case of an error.

I don't have any strong preference for the actual error data, minimal information such as "subsystem" and "error code" would be enough to already be a great improvement. If possible, having an option to pass string-based data to communicate host names, etc. would be useful, but I don't want to block the whole feature on that, if it causes issues (and assuming the `error_info` is passed as pointers, adding more data should be okay in the future).

```C
struct error_info {
    enum subsystem subsystem;  // Acts as a namespace for error codes
    int error_code;  // Subsystem specific (possible external, ie. BoringSSL/OpenSSL) error code
};
```

### Describe alternatives you've considered
Currently we provide settings in the software to enable/disable gRPC log messages. However due to performance reasons we do not enable this by default and enabling it (ie. setting `GRPC_TRACE` environment variable) requires server restart, which is often an issue for production environments - gRPC is not the only protocol we support so even if gRPC doesn't work, the server might still be in use.

Relying on the gRPC log messages for human readable error messages also feels quite fragile. gRPC logs as is are not suitable for user-facing errors and parsing them with regexp/etc. doesn't feel great.

### Additional context
I'm interested in providing an implementation for this feature, if there is indication it fits the gRPC core.

**Comment by apolcyn** [comment]
The clients-side aspects of this request probably fit into https://github.com/grpc/grpc/issues/22883

**Comment by yashykt** [comment]
Hi, Thank you for the interest in improving gRPC Core.

> Currently lack of TLS, untrusted TLS certificate (including those that miss intermediate certificates), invalid host name, etc. are indistinguishable from user point of view (although in the case of the first one at least, I wouldn't be too surprised if that's just us losing that information at some point in the call chains).

Have you looked at AuthContext? https://github.com/grpc/grpc/blob/c8c80fd9988fb5e508ae2f6b39e7901c2054d4f6/include/grpcpp/impl/codegen/security/auth_context.h#L65 This might be part of what you want over here.

> Alternatively set_error_info_function similar to gpr_set_log_function, that would allow the application itself to figure out how it should store and/or show the error message to the user - for our purposes we could then implement that as Thread Local Storage -based error storage that the caller can check in case of an error.

It's not clear to me why gpr_set_log_function does not fit the bill here. The log function knows the severity level of the log and it seems straightforward to just filter this on the severity ERROR. What would be more complex and possibly valuable is to associate an error code with this message. Note that we already associate a code to errors that are propagated all the way up as an RPC failure. Looking at the status message and error details, provides more information on the error.

Also, note that C Core already has an error type `grpc_error` for the propagation of errors. We are thinking of moving this to an absl::Status implementation for easier use across API. @veblush

**Comment by Rantanen** [comment]
> gpr_set_log_function 

Is the `gpr_set_log_function` callback guaranteed to execute in the context of the thread that made the original gRPC API call/request that resulted in the failure?

> `AuthContext`

The combination of these two might be what we'll need. I know the `gpr_set_log_function` alone hasn't always been the most useful and I've ended up needing to debug into the OpenSSL/BoringSSL implementation to figure out cert issues for example - although I'm not counting out the fact that I might have just failed at reading the log output. :)

I'll need to see if I can use `gpr_set_log_function` to store the errors in a TLS slot and read the JSON `"description"` for user facing errors. I've been vary of parsing too much of the logs programmatically, but the JSON-description seemed formal enough that I guess we can depend on that being there in the future.

Thanks for the pointers! I'll close this at least for now with the assumption that the above bits solve the issues we have. I'll re-open the issue with more concrete requirements if there are still some changes that would be needed for providing user-friendly errors for the usual error scenarios.

**Comment by yashykt** [comment]
> Is the gpr_set_log_function callback guaranteed to execute in the context of the thread that made the original gRPC API call/request that resulted in the failure?

No, that would be hard to do.

> I'll need to see if I can use gpr_set_log_function to store the errors in a TLS slot and read the JSON "description" for user facing errors. I've been vary of parsing too much of the logs programmatically, but the JSON-description seemed formal enough that I guess we can depend on that being there in the future.

These logs are not meant to be parsed programmatically. They are meant for human eyes. @veblush for more information on how this would change.
