### ISSUE TITLE
Cannot run Python multiprocessing example on within docker container

### ISSUE THREAD

**Issue by HndsmJohn** [grpc/grpc#25275]
### What version of gRPC and what language are you using?

gRPC Version 1.26.0 / Python 3.7.3 (Docker container)
gRPC Version 1.33.1 / Python 3.6.12 (My computer)

### What operating system (Linux, Windows,...) and version?

The container is based on Debian Buster, linux kernel version 5.8.0-38-generic.
My computer runs on Ubuntu 20.04, linux kernel version 5.8.0-38-generic

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7.3 (Docker container)
Python 3.6.12 (My computer)

### What did you do?

I created my docker image with grpc 1.26.0 on it and put it the file within the multiprocessing example folder for python.
When I run the script on my machine, it runs perfectly fine. 
For clarity issues, I fixed the number of processes within the script to 2, it has no influence on the execution error

### What did you expect to see?

I expected the script to run within the container 

### What did you see instead?

The first process (PID 33) created within the script works as expected but I encounter this error on the other process (PID 34) :
```
E0126 16:10:55.580805409      12 server_chttp2.cc:40]        
{"created":"@1611677455.580715854",
 "description":"No address added out of total 2 resolved",
 "file":"src/core/ext/transport/chttp2/server/chttp2_server.cc",
 "file_line":395,
 "referenced_errors":
    [{"created":"@1611677455.580692985",
      "description":"Unable to configure socket",
      "fd":10,
      "file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc",
      "file_line":208,"referenced_errors":
        [{"created":"@1611677455.580680971",
          "description":"Address already in use",
          "errno":98,
          "file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc",
          "file_line":181,
          "os_error":"Address already in use",
          "syscall":"bind"}]},
    {"created":"@1611677455.580710061",
     "description":"Unable to configure socket",
     "fd":10,
     "file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc",
     "file_line":208,"referenced_errors":
        [{"created":"@1611677455.580706594",
          "description":"Address already in use",
          "errno":98,
          "file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc",
          "file_line":181,
          "os_error":"Address already in use",
          "syscall":"bind"}]}]}

```

Here is the debug trace for the process that failed (PID 34) :
```
I0126 16:16:19.776045332      34 ev_epoll1_linux.cc:116]     grpc epoll fd: 7
D0126 16:16:19.776095691      34 ev_posix.cc:174]            Using polling engine: epoll1
D0126 16:16:19.776196554      34 dns_resolver_ares.cc:503]   Using ares dns resolver
I0126 16:16:19.776290643      34 init.cc:165]                grpc_init(void)
I0126 16:16:19.776308809      34 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0126 16:16:19.776340848      34 init.cc:165]                grpc_init(void)
I0126 16:16:19.776379311      34 server.cc:1010]             grpc_server_create(0x7fb9257e2ac8, (nil))
I0126 16:16:19.776421242      34 server.cc:993]              grpc_server_register_completion_queue(server=0x1900dd0, cq=0x1a2fc50, reserved=(nil))
I0126 16:16:19.777491140      34 server_chttp2.cc:34]        grpc_server_add_insecure_http2_port(server=0x1900dd0, addr=localhost:46151)

##
# At this line is printed the error provided right before
##
```

I believe some aspect of this issue may have been addressed with the [issue #16001](https://github.com/grpc/grpc/issues/16001) but I can't get why it works fine on my machine but not within a docker container.

Thank you for your help.

**Comment by lidizheng** [comment]
Have you checked if the [`SO_REUSEPORT`](https://man7.org/linux/man-pages/man7/socket.7.html) feature is enabled in the network stack within the Docker container? The `multiprocessing` example requires the OS to allow sharing a TCP port across processes.

**Comment by bankbiz** [comment]
I had a same issue for running [this tutorial](https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing) with Docker way.

I figure out from [this article](https://iximiuz.com/en/posts/multiple-containers-same-port-reverse-proxy/)

`SO_REUSEPORT` option works only if all the sockets reside in the same network stack. And that's obviously not the case for the default Docker approach, where every container gets its own network namespace, hence an isolated network stack.

I try to follow this article solution (net/http) to fix network stack for gRPC but client on my local machine still "failed to connect to all addresses" in container server.

Is it limitation of gRPC for now? because traditional network like net/http can find the way to go out from container network with `SO_REUSEPORT` option.

Thank you for any suggestion.

**Comment by lidizheng** [comment]
@bankbiz 

For new issues, please consider open a new GitHub Issue for better track-ability. The network setting highly depends on your use case. In general, to load-balance gRPC traffic in a production environment, you will need to use more powerful mechanisms than SO_REUSEPORT which is L4-only.
