### ISSUE TITLE
Change SSL server API creds API so that we add an option to force client authentication

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#2527]

**Comment by nathanielmanistaatgoogle** [comment]
What's the status on this? #163 has this as a possible prerequisite but I'm going to go ahead on it without whatever happens here.

**Comment by jboeuf** [comment]
Thanks. You have the core support that you need for this (as well as #163).

**Comment by nathanielmanistaatgoogle** [comment]
We do? Oh, I see it now - it appears to have landed in the core in 5029b30d1ce8509a4 on 21 July. Should this issue still be open? Is it simply tracking the exposure of the option in the wrapped languages?

**Comment by jboeuf** [comment]
>  Is it simply tracking the exposure of the option in the wrapped languages?
>
Correct.

**Comment by nathanielmanistaatgoogle** [comment]
I've added the python label to this issue because this work is still outstanding for Python. I see the wrapped languages, c, and API BREAKAGE labels on this issue as well - can those be removed if they aren't tracking active work? Are there wrapping languages other than Python that have yet to do this?

**Comment by jboeuf** [comment]
@tbetbetbe looks like ruby still needs to be upgraded. Any other languages? @murgatroid99 may know as well.

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed for Python in 9e4d0610ea5e2bb3; removing the Python label from this issue.

**Comment by tbetbetbe** [comment]
FYI: This was fixed for Ruby in #162.  AFAICT every wrapped language supports this now

**Comment by tbetbetbe** [comment]
Closing: Please re-open if there wrapped-languages with servers that don't have this
