### ISSUE TITLE
Client Connect is invoked from gRPC Internal Thread in Linux

### ISSUE THREAD

**Issue by asbhat10** [grpc/grpc#25284]
In Mac OS, the gRPC connect happens from the same thread which calls the RPC API.
But in Linux, I observed that it uses gRPC internal thread to connect and doesn't use the thread which invoked the RPC.

Is there a way to disable the gRPC internal thread, so gRPC can use caller thread to connect to the gRPC server?

**Comment by asbhat10** [comment]
Mac is running version 1.34 whereas the linux machine is running 1.15.
Was the behavior modified in between these versions?

**Comment by yashykt** [comment]
gRPC's threading architecture is moving to an architecture where most of the work will be done by internal threads. For more information https://github.com/grpc/proposal/pull/182/files
