### ISSUE TITLE
ARM64: //test/cpp/naming:resolver_component_tests_runner_invoker_unsecure@poller=epollex test is failing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#25289]
Repro (run on linux aarch64 machine)

`tools/bazel test --config=dbg --cache_test_results=no  --test_output=streamed //test/cpp/naming:resolver_component_tests_runner_invoker_unsecure@poller=epollex`

resolver_component_tests_runner_invoker (without _unsecure is broken in the same way).
All the other pollers are also failing.

```
E0128 15:21:38.199586121     284 ev_epollex_linux.cc:516]    Error shutting down fd 8. errno: 9
E0128 15:21:39.200610605     284 ev_epollex_linux.cc:516]    Error shutting down fd 47. errno: 9
test/cpp/naming/resolver_component_test.cc:402: Failure
Value of: errno == EAGAIN || errno == EWOULDBLOCK
  Actual: false
Expected: true
OpenAndCloseSocketsStressLoop accept on socket 8 failed in an unexpected way. errno: 22. Socket use-after-close bugs are likely.
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress (8003 ms)
```

**Comment by jtattermusch** [comment]
@apolcyn  any ideas what could be wrong?

**Comment by apolcyn** [comment]
Looks like we failed the sockets open/close loop got an EBADF error.

This is suspicious because it would suggest a socket use-after-close bug, which is exactly the kind of bug that this test is trying to hit.

Any complete trace logs? Or way to repro?

**Comment by jtattermusch** [comment]
> Looks like we failed the sockets open/close loop got an EBADF error.
> 
> This is suspicious because it would suggest a socket use-after-close bug, which is exactly the kind of bug that this test is trying to hit.
> 
> Any complete trace logs? Or way to repro?

I can provide you with access to an ARM64 machine where reproducing is easy (just by running the bazel command). Let's sync up offiline.

**Comment by jtattermusch** [comment]
Logs from a few manual reproductions:
```
/home/ubuntu/.cache/bazel/_bazel_ubuntu/37a2041cb621d0ec4baeca5c97bdf78c/sandbox/linux-sandbox/1711/execroot/com_github_grpc_grpc/bazel-out/aarch64-dbg/bin/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=epollex.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Run test with target: no-srv-ipv4-single-target-inject-broken-nameservers.resolver-tests-version-4.grpctestingexp.
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ResolverComponentTest
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecords
[       OK ] ResolverComponentTest.TestResolvesRelevantRecords (6002 ms)
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress
E0527 13:21:31.865723392     270 ev_epollex_linux.cc:516]    Error shutting down fd 8. errno: 9
E0527 13:21:32.866855381     270 ev_epollex_linux.cc:516]    Error shutting down fd 48. errno: 9
test/cpp/naming/resolver_component_test.cc:402: Failure
Value of: errno == EAGAIN || errno == EWOULDBLOCK
  Actual: false
Expected: true
OpenAndCloseSocketsStressLoop accept on socket 35 failed in an unexpected way. errno: 22. Socket use-after-close bugs are likely.
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress (7004 ms)
[----------] 2 tests from ResolverComponentTest (13006 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (13006 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress

 1 FAILED TEST
```


```
/home/ubuntu/.cache/bazel/_bazel_ubuntu/37a2041cb621d0ec4baeca5c97bdf78c/sandbox/linux-sandbox/1712/execroot/com_github_grpc_grpc/bazel-out/aarch64-dbg/bin/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=epollex.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Run test with target: ipv4-config-causing-fallback-to-tcp-inject-broken-nameservers.resolver-tests-version-4.grpctestingexp.
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ResolverComponentTest
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecords
[       OK ] ResolverComponentTest.TestResolvesRelevantRecords (5004 ms)
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress
E0527 13:23:18.907979342     284 ev_epollex_linux.cc:516]    Error shutting down fd 8. errno: 9
E0527 13:23:19.909179302     284 ev_epollex_linux.cc:516]    Error shutting down fd 48. errno: 9
test/cpp/naming/resolver_component_test.cc:402: Failure
Value of: errno == EAGAIN || errno == EWOULDBLOCK
  Actual: false
Expected: true
OpenAndCloseSocketsStressLoop accept on socket 37 failed in an unexpected way. errno: 22. Socket use-after-close bugs are likely.
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress (7005 ms)
[----------] 2 tests from ResolverComponentTest (12009 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (12009 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress
```


```
/home/ubuntu/.cache/bazel/_bazel_ubuntu/37a2041cb621d0ec4baeca5c97bdf78c/sandbox/linux-sandbox/1713/execroot/com_github_grpc_grpc/bazel-out/aarch64-dbg/bin/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=epollex.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Run test with target: no-srv-ipv4-single-target-inject-broken-nameservers.resolver-tests-version-4.grpctestingexp.
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ResolverComponentTest
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecords
[       OK ] ResolverComponentTest.TestResolvesRelevantRecords (6003 ms)
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress
E0527 13:24:36.511416099     270 ev_epollex_linux.cc:516]    Error shutting down fd 8. errno: 9
test/cpp/naming/resolver_component_test.cc:402: Failure
Value of: errno == EAGAIN || errno == EWOULDBLOCK
  Actual: false
Expected: true
OpenAndCloseSocketsStressLoop accept on socket 9 failed in an unexpected way. errno: 22. Socket use-after-close bugs are likely.
E0527 13:24:37.513138685     270 ev_epollex_linux.cc:516]    Error shutting down fd 10. errno: 9
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress (8004 ms)
[----------] 2 tests from ResolverComponentTest (14007 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (14007 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress
```

```
/home/ubuntu/.cache/bazel/_bazel_ubuntu/37a2041cb621d0ec4baeca5c97bdf78c/sandbox/linux-sandbox/1716/execroot/com_github_grpc_grpc/bazel-out/aarch64-dbg/bin/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=epollex.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Run test with target: ipv4-config-causing-fallback-to-tcp-inject-broken-nameservers.resolver-tests-version-4.grpctestingexp.
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ResolverComponentTest
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecords
[       OK ] ResolverComponentTest.TestResolvesRelevantRecords (6003 ms)
[ RUN      ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress
E0527 13:27:26.347624314     284 ev_epollex_linux.cc:516]    Error shutting down fd 8. errno: 9
E0527 13:27:27.348817384     284 ev_epollex_linux.cc:516]    Error shutting down fd 50. errno: 9
test/cpp/naming/resolver_component_test.cc:402: Failure
Value of: errno == EAGAIN || errno == EWOULDBLOCK
  Actual: false
Expected: true
OpenAndCloseSocketsStressLoop accept on socket 43 failed in an unexpected way. errno: 22. Socket use-after-close bugs are likely.
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress (8003 ms)
[----------] 2 tests from ResolverComponentTest (14007 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (14007 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ResolverComponentTest.TestResolvesRelevantRecordsWithConcurrentFdStress

 1 FAILED TEST
```

**Comment by jtattermusch** [comment]
I looked into this further.

I can consistently reproduce with test scenario `no-srv-ipv4-single-target-inject-broken-nameservers.resolver-tests-version-4.grpctestingexp.`:
https://github.com/grpc/grpc/blob/a44bafec08c1839158953ab361144f65d962b168/test/cpp/naming/resolver_component_tests_runner.py#L592

What I did:
- only run the `no-srv-ipv4-single-target-inject-broken-nameservers.resolver-tests-version-4.grpctestingexp.` scenario (I commented out other scenarios in the py file).
- set `GRPC_VERBOSITY=debug`
- ran the test itself with `strace -f -e trace=close,shutdown`

From the logs I got, it seems that  ares sometimes calls `close(fd)` for a given fd before calling `shutdown(fd)`. The late call to `shutdown` is then correctly detected by the test.

In the log, the interesting part is  `close(13)` on thread 64 (that's the grpc_ares_wrappers's thread), followed by `shutdown(13, ..)` on the same thread. Looks like the fd 13 is picked up by the stress test immediately after `close` is called (that's the `resolver_component_test.cc:385] Opened fd: 17` message - note that strace only prints the syscalls after they returns so that it knows their returnvalue). 
```
D0609 11:02:56.923065333      69 resolver_component_test.cc:385] Opened fd: 15 will store to index 6
D0609 11:02:56.923140992      64 grpc_ares_wrapper.cc:503]   (c-ares resolver) request:0x3099a110 ev_driver=0x309b9580 grpc_ares_ev_driver_start_locked. timeout in 127018 ms
D0609 11:02:56.923290652      64 grpc_ares_wrapper.cc:182]   (c-ares resolver) request:0x3099a110 Ref ev_driver 0x309b9580
D0609 11:02:56.923340809      64 grpc_ares_wrapper.cc:266]   (c-ares resolver) request:0x3099a110 ev_driver=0x309b9580. next ares process poll time in 1000 ms
D0609 11:02:56.923385051      64 grpc_ares_wrapper.cc:182]   (c-ares resolver) request:0x3099a110 Ref ev_driver 0x309b9580
D0609 11:02:56.923449132      69 resolver_component_test.cc:385] Opened fd: 17 will store to index 7
D0609 11:02:56.923501210      64 grpc_ares_wrapper.cc:361]   (c-ares resolver) request:0x3099a110 readable on c-ares fd: 13
[pid    64] close(13)                   = 0
D0609 11:02:56.923736186      69 resolver_component_test.cc:385] Opened fd: 13 will store to index 8
D0609 11:02:56.923947589      64 grpc_ares_wrapper.cc:436]   (c-ares resolver) request:0x3099a110 new fd: c-ares fd: 18
D0609 11:02:56.923990223      64 grpc_ares_wrapper.cc:182]   (c-ares resolver) request:0x3099a110 Ref ev_driver 0x309b9580
D0609 11:02:56.924029073      64 grpc_ares_wrapper.cc:451]   (c-ares resolver) request:0x3099a110 notify read on: c-ares fd: 18
[pid    64] shutdown(13, SHUT_RDWRD0609 11:02:56.924070821      69 resolver_component_test.cc:385] Opened fd: 19 will store to index 9
)     = 0
D0609 11:02:56.924122570      64 grpc_ares_wrapper.cc:202]   (c-ares resolver) request:0x3099a110 delete fd: c-ares fd: 13
D0609 11:02:56.924176247      64 grpc_ares_wrapper.cc:189]   (c-ares resolver) request:0x3099a110 Unref ev_driver 0x309b9580
D0609 11:02:56.924352328      69 resolver_component_test.cc:385] Opened fd: 20 will store to index 10
```

later in the log, the use-after-close is then detected by the test:
```
D0609 11:02:56.936573702      69 resolver_component_test.cc:398] non-blocking accept then close on 13 (index 8 out of 50)
test/cpp/naming/resolver_component_test.cc:402: Failure
Value of: errno == EAGAIN || errno == EWOULDBLOCK
  Actual: false
Expected: true
OpenAndCloseSocketsStressLoop accept on socket 13 failed in an unexpected way. errno: 22. Socket use-after-close bugs are likely.
```


Note that the wrong ordering of close() and shutdown() also happens for other sockets. The symptom is that close() gets called first, and is immediately followd by shutdown() returning error `EBADF` (since the socket has just been closed).
```
D0609 11:02:56.925338222      64 grpc_ares_wrapper.cc:361]   (c-ares resolver) request:0x3099a110 readable on c-ares fd: 22
...
[pid    64] close(22)                   = 0
[pid    64] shutdown(22, SHUT_RDWR)     = -1 EBADF (Bad file descriptor)
E0609 11:02:56.925598125      64 ev_epollex_linux.cc:516]    Error shutting down fd 22. errno: 9
D0609 11:02:56.925646847      64 grpc_ares_wrapper.cc:202]   (c-ares resolver) request:0x3099a110 delete fd: c-ares fd: 22
```

The error message `Error shutting down fd 22. errno: 9` shows up in the test log several times and is easily detectable.

**Comment by jtattermusch** [comment]
The stacktrace when the late fd shutdown happens `Error shutting down fd 22. errno: 9` is this:
```
PC: @     0xffffad6144f8  (unknown)  gsignal
    @           0x8370e0        400  absl::lts_20210324::WriteFailureInfo()
    @           0x836cd0  1363436112  absl::lts_20210324::AbslFailureSignalHandler()
    @     0xffffada045b8        304  (unknown)
    @     0xffffad6158d4        464  abort
    @           0xa16a98         96  fd_shutdown()
    @           0xa11060         32  grpc_fd_shutdown()
    @           0x8900f0        144  grpc_core::GrpcPolledFdPosix::ShutdownLocked()
    @           0x886978        432  fd_node_shutdown_locked()
    @           0x887088        128  grpc_ares_notify_on_event_locked()
    @           0x88a808         32  on_readable_locked()
    @           0x88a63c         32  on_readable()::$_2::operator()()
    @           0x88a47c         32  std::_Function_handler<>::_M_invoke()
    @           0x911658        224  std::function<>::operator()()
    @           0x9d3d9c        112  grpc_core::WorkSerializer::WorkSerializerImpl::Run()
    @           0x9d4304        176  grpc_core::WorkSerializer::Run()
    @           0x88a010         96  on_readable()
    @           0xa100f4        112  exec_ctx_run()
    @           0xa0ff8c        320  grpc_core::ExecCtx::Flush()
    @           0xa17120         96  pollset_work()
    @           0xa114e8         48  pollset_work()
    @           0xa0aa6c        736  grpc_pollset_work()
```

**Comment by jtattermusch** [comment]
From my investigation it looks like that  `close(fd)` is called by `ares_process_fd` here: https://github.com/grpc/grpc/blob/a44bafec08c1839158953ab361144f65d962b168/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L364

`shutdown(fd)` is called by the subsequent https://github.com/grpc/grpc/blob/a44bafec08c1839158953ab361144f65d962b168/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L375.

Looks like the problem is somewhere in ares' processfds?
https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/ares_process.c#L133 (it can sometimes call close and we follow by a subsequent `shutdown`, which is illegal?).

**Comment by apolcyn** [comment]
Sharing my comment from offline chat here:

I think the only remaining question is where are the early `close` calls are coming from.

An early close on a c-ares fd is supposed to be impossible because we use the [STAYOPEN flag in c-ares](https://github.com/grpc/grpc/blob/743055193a31440e9d801282744d4ed7fdfb18dc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L534), and that flag prevents c-ares from calling `close` on any socket returned from [ares_getsock](https://github.com/grpc/grpc/blob/743055193a31440e9d801282744d4ed7fdfb18dc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L424), until [ares_destroy is called](https://github.com/grpc/grpc/blob/743055193a31440e9d801282744d4ed7fdfb18dc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L194).

Meanwhile, we make sure to not call `ares_destroy` until all fds have:
a) been shutdown
b) have no readable or writable callbacks pending

If the `close` calls are coming e.g. from [here](https://github.com/c-ares/c-ares/blob/809d5e84f3423ab8165650d923acb0e246cbd006/src/lib/ares_process.c#L1497), then it would seem that the STAYOPEN flag is not getting set correctly.

However, as Jan also pointed out, c-ares can also close sockets from the [process_broken_connections](https://github.com/c-ares/c-ares/blob/809d5e84f3423ab8165650d923acb0e246cbd006/src/lib/ares_process.c#L717) code path, which actually bypasses the STAYOPEN flag. This might actually be a broken assumption in our usage of the STAYOPEN flag - if we're hitting this, then this may be a deeper bug.

**Comment by jtattermusch** [comment]
I tried to track down the origin of the close() invoked by c-ares.

it's actually coming from `read_udp_packets`:
https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/ares_process.c#L131

**inside read_udp_packets, the sock_recvfrom  fails with errno 111 (connection refused)** (not sure why or if that's something that's expected).
https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/ares_process.c#L516
and `handle_error` is invoked:
https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/ares_process.c#L523

That eventually invokes 
https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/ares_process.c#L1467

and it does `sclose`
https://github.com/c-ares/c-ares/blob/e982924acee7f7313b4baa4ee5ec000c5e373c30/ares_process.c#L1472


From that, it seems that using STAYOPEN flag isn't something that would prevent c-ares from ever calling close() on sockets.
From what I saw I don't think the issue we're seeing is connected to arm64 support - we might just be unlucky to hit this cornercase when running on different hardware.

**Comment by apolcyn** [comment]
Great findings, Jan! I agree this looks like a bug in our usage of c-ares.

A couple of ideas that come to mind for how to fix:

a) patch c-ares to respect STAYOPEN from it's `handle_error` code path

b) leverage the c-ares [socket vtable API](https://github.com/c-ares/c-ares/blob/809d5e84f3423ab8165650d923acb0e246cbd006/src/lib/ares_init.c#L2606) to somehow not actually call `close` if it's buggy to do so, similarly to what is done [for windows](https://github.com/grpc/grpc/blob/f89574cc4ba6b2a2cc81d9dd307814f463ff147a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc#L799)

**Comment by jtattermusch** [comment]
I disabled the tests on arm64 with #26518, but the underlying problem still exists.

**Comment by raarts** [comment]
This isn't fixed yet, did someone communicate with the c-ares people, I could not find a bug report there.

**Comment by jtattermusch** [comment]
> This isn't fixed yet, did someone communicate with the c-ares people, I could not find a bug report there.

This isn't necessarily a bug in c-ares itself, in fact it might be the grpc code making wrong assumptions about c-ares behavior (which leads to a bug).

**Comment by raarts** [comment]
I understand, but I was just wondering if someone talked to the c_ares group about respecting STAYOPEN in handle_error.

**Comment by yashykt** [comment]
Closing since we decided not to track test flakes on github
