### ISSUE TITLE
multiple definition link time error on some upb symbols

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#25301]
### What version of gRPC and what language are you using?
1.35.0 and Rust, the project is at https://github.com/tikv/grpc-rs

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Just compiling tikv/grpc-rs#506 on Linux can reproduce the problem.

### What did you expect to see?
It compiles correctly and successfully.

### What did you see instead?
It failed with [error](https://github.com/tikv/grpc-rs/pull/506/checks?check_run_id=1790282208).
The link contains full error log, but I also quote some lines here for better searching:
```
/home/runner/work/grpc-rs/grpc-rs/target/debug/build/grpcio-sys-ae1bf4d31b8b3dce/out/build/libupb.a(timestamp.upbdefs.c.o):(.data.rel.local.google_protobuf_timestamp_proto_upbdefinit+0x0): multiple definition of `google_protobuf_timestamp_proto_upbdefinit'
          /home/runner/work/grpc-rs/grpc-rs/target/debug/build/grpcio-sys-ae1bf4d31b8b3dce/out/build/libgrpc.a(timestamp.upbdefs.c.o):(.data.rel.local.google_protobuf_timestamp_proto_upbdefinit+0x0): first defined here
          /home/runner/work/grpc-rs/grpc-rs/target/debug/build/grpcio-sys-ae1bf4d31b8b3dce/out/build/libupb.a(wrappers.upbdefs.c.o):(.data.rel.local.google_protobuf_wrappers_proto_upbdefinit+0x0): multiple definition of `google_protobuf_wrappers_proto_upbdefinit'
          /home/runner/work/grpc-rs/grpc-rs/target/debug/build/grpcio-sys-ae1bf4d31b8b3dce/out/build/libgrpc.a(wrappers.upbdefs.c.o):(.data.rel.local.google_protobuf_wrappers_proto_upbdefinit+0x0): first defined here
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
What it does is simply compile grpc library using cmake, and then link all necessary libraries to build a binary, which includes libgrpc.a and libupb.a. And the reported errors come from these two libraries.

Maybe similar to #23307.

/cc @markdroth 

@veblush do you have any suggestions on this? Any help is appreciated.

**Comment by BusyJay** [comment]
Since upb and grpc library both include identical source:

https://github.com/grpc/grpc/blob/257d0045ab958eb767a3591c88e9d0c2bdf4b916/CMakeLists.txt#L1612-L1617

https://github.com/grpc/grpc/blob/257d0045ab958eb767a3591c88e9d0c2bdf4b916/CMakeLists.txt#L1695-L1701

https://github.com/grpc/grpc/blob/257d0045ab958eb767a3591c88e9d0c2bdf4b916/CMakeLists.txt#L3795-L3808

When linking them together there have to be duplicated symbols. If I remove all the duplicated source from upb and change the definition of upb to
```
add_library(upb
  third_party/upb/upb/decode_fast.c
  third_party/upb/upb/decode.c
  third_party/upb/upb/def.c
  third_party/upb/upb/encode.c
  third_party/upb/upb/json_decode.c
  third_party/upb/upb/json_encode.c
  third_party/upb/upb/msg.c
  third_party/upb/upb/reflection.c
  third_party/upb/upb/table.c
  third_party/upb/upb/text_encode.c
  third_party/upb/upb/upb.c
  src/core/ext/upb-generated/google/protobuf/descriptor.upb.c
)
```

I can make it compile and link without any warnings or errors. This can make some symbols missing in libupb.a, but in my case, it's always linked with libgrpc.a, where all those missing symbols can be found, so this seems fine. My only question is is it safe or correct to do so?

**Comment by veblush** [comment]
@BusyJay Thanks for the report. Yeah it looks wrong to me.

**Comment by BusyJay** [comment]
This also is reintroduced by https://github.com/grpc/grpc/pull/28531 and https://github.com/grpc/grpc/pull/27928. Now libgpr.a and libgrpc.a share the same upb symbols now.
