### ISSUE TITLE
[python] gRPC server async, missing parts to make it work

### ISSUE THREAD

**Issue by klausmyrseth** [grpc/grpc#25315]
From looking at the grpc-tools protoc I cant find a way of compiling an async server/client, I can run the server through grpc.aio.server but the service I cant register asynchronously.

I am sure I can handcode this from scratch but I was hoping to use the code generation for this, up to now I have to use the sync variant but since all our other code is async its starting to get tedious ;)

My problem is running grpc_tools.protoc seems to not generate async wrappers to use in the server, either that or you need to add some more examples to see how to use this :)

Is there any way of doing this today, or do you have plans to add this?

**Comment by lidizheng** [comment]
The asyncio API works with normal generated code. This feature was implemented to ensure a smoother migration process. Where do you think we should include this info to prevent future confusion?

Link to the guide to create stub and servicer: https://grpc.io/docs/languages/python/basics/#generating-client-and-server-code
Link to HelloWorld that uses the generated code: https://github.com/grpc/grpc/blob/master/examples/python/helloworld/async_greeter_server.py

**Comment by klausmyrseth** [comment]
This is exactly what i was looking for. Perhaps switch the default examples and so on with these as 2.x is end of life ;)

there you saved my day so i can use my normal apis without a ton of hassle 😀
