### ISSUE TITLE
Dependency on minitest, googleauth and logging

### ISSUE THREAD

**Issue by simonrussell** [grpc/grpc#2532]
These dependencies are marked as:

    s.add_dependency 'googleauth', '~> 0.4'  # reqd for interop tests
    s.add_dependency 'minitest', '~> 5.4'  # reqd for interop tests

Are these interop tests something I'm going to want as a general user of the gem?  Are they something I'm going to want in production?

I'm hesitant to rely on a project that makes me install a test framework and an API client for a service I don't use on my production systems.

My question about the dependency on the "logging" gem is a bit different I suppose; I can see how it might be relevant to a production system, but also I'm not sure I want an RPC library forcing a logging system on me; is it a major part of the library?

**Comment by tbetbetbe** [comment]
The logging and minitest dependencies ought to removed; the linked PRs do this.

GRPC Ruby will install its interop_client as an example binary and it does depend on googleauth, so that dependency is required.

**Comment by murgatroid99** [comment]
Can you make `googleauth` a developer dependency, so that users can choose whether to install it?

**Comment by simonrussell** [comment]
Thanks for those pull requests -- I'm not familiar enough with the project and its motivations to really do the work myself at this point.  However, I think I'd have to say that if interop_client is just an example binary, then perhaps it doesn't belong in the gem at all?

**Comment by tbetbetbe** [comment]
> if interop_client is just an example binary, then perhaps it doesn't belong in the gem at all ?
@simonrussell: do you have an example of best practice for example binaries like this? I know of other multi-gem repos - perhaps that's what should be done here.  I would feel more confident about that if it's clear that it's an established practice.

**Comment by simonrussell** [comment]
Hi there, sorry for the delay in replying.  I've been searching around, but I can't really give you any examples.  To me, it seems like the sort of thing that shouldn't actually be in the gem at all -- it should mainly be production code.  Examples etc feel like they should be a repository or something I can clone and fiddle around with.  This might not match with the goals of the project though.

**Comment by tbetbetbe** [comment]
> Examples etc feel like they should be a repository or something I can clone and fiddle around with.  This might not match with the goals of the project though.

There are [examples](https://github.com/grpc/grpc/tree/master/examples/ruby) that are not packaged as part of the gem.  However, the interop server and client are a bit different.  They are proof that the implementation conforms to the [gRPC specifcation](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) and its [conformance tests](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md).

**Comment by tbetbetbe** [comment]
Closing this:

The resolution is that we've removed the dependencies, but instead choose to include the interop_server and interop_client as binaries delivered with the gRPC gem.  They are high-level tests that provide a system-level verification check
