### ISSUE TITLE
Allow building grpc_cpp_plugin only to aid cross-compilation

### ISSUE THREAD

**Issue by patrickdepinguin** [grpc/grpc#25322]
### Is your feature request related to a problem? Please describe.
To cross-compile grpc, you need a native version of grpc_cpp_plugin. This tool is expected to be found in PATH.
To build such native grpc_cpp_plugin, the simple approach is to build the entire native grpc, but this builds too much, and has a lot of external dependencies, e.g. on a native version of libabseil-cpp, re2, etc.

### Describe the solution you'd like
Allow a way to just build grpc_cpp_plugin, so that this 'minibuild' can be made for the native system, followed by a full build using the cross-compiler.

### Describe alternatives you've considered
Like said above, the existing way is just to build a full native grpc.

I have locally patched the CMakeLists.txt file to add an extra option gRPC_BUILD_PLUGIN_SUPPORT_ONLY, which is used to disable certain components in the rest of that file. The 'minibuild' can then be achieved by building with that option enabled, and passing some additional options to make cmake happy in the configure phase.

While this works, there are following problems:
* I would like to have a solution which is accepted and merged upstream (in grpc itself)
* the patch hacks directly in CMakeLists.txt and not in the templates this file is generated from
* there is no change for other build systems

I would like to hear whether you agree with the idea of allowing such minibuild, and how you would go about it.

Please find attached the patch I'm using now.
[0004-host-grpc-only-cpp-plugin.patch.txt](https://github.com/grpc/grpc/files/5910910/0004-host-grpc-only-cpp-plugin.patch.txt)

I'm using following configure options for the minibuild:
```
	-DgRPC_PROTOBUF_PROVIDER=package \
	-DgRPC_ABSL_PROVIDER=none \
	-DgRPC_CARES_PROVIDER=none \
	-DgRPC_RE2_PROVIDER=none \
	-DgRPC_SSL_PROVIDER=none \
	-DgRPC_ZLIB_PROVIDER=none \
	-DgRPC_BUILD_CODEGEN=OFF \
	-DgRPC_BUILD_CSHARP_EXT=OFF \
	-DgRPC_BUILD_PLUGIN_SUPPORT_ONLY=ON \
	-DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
	-DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
	-DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
	-DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF \
	-DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF \
	-DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF
```

### Additional context
I'm building grpc in Buildroot, a tool to build images for embedded systems.

**Comment by jtattermusch** [comment]
Our cmake build has many targets. You should only build the ones you're interested in. the grpc_cpp_plugin target only has dependencies on what's really needed (and the build finishes much faster than building the entire grpc).
```
cd cmake/build
cmake ../..
make grpc_cpp_plugin    # only build the C++ plugin and its dependencies, for faster build
```

Btw, building all the codegen plugins and building just grpc_cpp_plugin doesn't really make a difference since each codegen plugin is just one extra .cc file. gRPC_BUILD_GRPC_CSHARP_PLUGIN

**Comment by patrickdepinguin** [comment]
The problem with this approach is that the 'cmake' step will still check all dependencies, even those not needed for grpc_cpp_plugin. At that step, cmake is not aware that you are only building grpc_cpp_plugin.

So you get errors like:
```
$ cmake ../..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/abseil-cpp.cmake:30 (message):
  gRPC_ABSL_PROVIDER is "module" but ABSL_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:250 (include)


CMake Error at cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /home/tdescham/repo/contrib/grpc/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:253 (include)


CMake Warning at cmake/protobuf.cmake:51 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:254 (include)


CMake Warning at cmake/re2.cmake:41 (message):
  gRPC_RE2_PROVIDER is "module" but
  RE2_ROOT_DIR(/home/tdescham/repo/contrib/grpc/third_party/re2) is wrong
Call Stack (most recent call first):
  CMakeLists.txt:255 (include)


CMake Warning at cmake/ssl.cmake:55 (message):
  gRPC_SSL_PROVIDER is "module" but BORINGSSL_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:256 (include)


CMake Warning at cmake/zlib.cmake:39 (message):
  gRPC_ZLIB_PROVIDER is "module" but ZLIB_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:258 (include)


-- Configuring incomplete, errors occurred!
```

Of these, only the C-ares error is an 'error', the others are 'warnings'. One can get around that by adapting the command, but then, in addition to above warnings, you get more errors:
```
$  cmake ../..  -DgRPC_CARES_PROVIDER=none 
[..]
-- Configuring done
CMake Error at CMakeLists.txt:2247 (add_library):
  Target "grpc_unsecure" links to target "absl::optional" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:2247 (add_library):
  Target "grpc_unsecure" links to target "absl::time" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
[..]
```

My goal is exactly to avoid the dependencies on libraries not actually needed to build the plugins.
My patch solves this problem by making the parts of CMakeLists.txt that cause these errors and warnings  conditional on an option.
Perhaps I'm overlooking something.

Regarding your suggestion to broaden the problem from 'building grpc_cpp_plugin only' to 'build the code generation plugins only': this approach would be acceptable to me. But I have not find a way to do that either, taking into account the desire of not adding unnecessary dependencies.

**Comment by jtattermusch** [comment]
The error messages you posted only seem to indicate that you haven't restored the git submodule before trying to build 
After running `git submodule update --init`, you should be able to build just the grpc_cpp_plugin just fine. The absl / cares / other depedencies  won't actually be built, you just need to have the submodules restored so that you don't end up with a malformed cmake build - and this is working as intended.

Alternatively, you can also build the protoc plugin with bazel (and again bazel will only build what's absolutely needed, not more).

**Comment by patrickdepinguin** [comment]
My context is about building grpc with Buildroot [1]. Buildroot will build a package and all its dependencies, and downloads of each package is done separately. When building grpc, it will not actually use the submodules inside of grpc, but rather has arranged building all required dependencies up front, e.g. libabseil-cpp, re2, etc.
Today, Buildroot will also build a native version of grpc (host-grpc in Buildroot terminology), which will in turn arrange for native versions of libabseil-cpp, re2, ... which is exactly what I want to avoid.
Downloading and extracting these host-libabseil-cpp and host-re2 without actually building it is not really how Buildroot normally works. Perhaps it could be done, but it does feel very strange if it is only to make cmake happy. For such case it does seem nicer to have a cmake option to steer it.

Buildroot does not currently have integration with bazel.
Would the situation with bazel _not_ require the submodules to be initialized?

[1] https://buildroot.org/

**Comment by jtattermusch** [comment]
What you're doing sounds like quite a narrow use case. But we simply cannot provide a cmake option for every possible scenario in the world. Introducing a new cmake option isn't for free and requires careful design and maintenance.

**Comment by patrickdepinguin** [comment]
I understand your reluctance on adding new options.
I can only share my point of view when cross-compiling grpc and needing the native grpc_cpp_plugin. I don't think this is such a rare scenario, but it's true that cross-compilation is more rare than native compilation.
Thanks anyway for your support.

For reference, I am pasting my simplified patch below. Basically I am making all parts of CMakeLists.txt conditional on a new option, except the parts for `grpc_plugin_support`. This patch was made on top of v1.35.0. 
In Buildroot, the cmake options to build the native part are now reduced to:

```
HOST_GRPC_CONF_OPTS = \
	-DgRPC_PROTOBUF_PROVIDER=package \
	-DgRPC_ABSL_PROVIDER=none \
	-DgRPC_CARES_PROVIDER=none \
	-DgRPC_RE2_PROVIDER=none \
	-DgRPC_SSL_PROVIDER=none \
	-DgRPC_ZLIB_PROVIDER=none \
	-DgRPC_BUILD_PLUGIN_SUPPORT_ONLY=ON
```

Patch is:
```
From de9259c5ee085554ef502f0218686a1e9cb0cff5 Mon Sep 17 00:00:00 2001
From: Thomas De Schampheleire <thomas.de_schampheleire@nokia.com>
Date: Tue, 9 Feb 2021 16:47:05 +0100
Subject: [PATCH] CMakeLists.txt: introduce gRPC_BUILD_PLUGIN_SUPPORT_ONLY

Allow building a minimal host-grpc, only building the language plugins
needed for cross-compilation of grpc.
---
 CMakeLists.txt | 14 ++++++++++++++
 1 file changed, 14 insertions(+)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6bdae22083..5258f1ece6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -48,6 +48,7 @@ option(gRPC_BUILD_TESTS "Build tests" OFF)
 option(gRPC_BUILD_CODEGEN "Build codegen" ON)
 option(gRPC_BUILD_CSHARP_EXT "Build C# extensions" ON)
 option(gRPC_BACKWARDS_COMPATIBILITY_MODE "Build libraries that are binary compatible across a larger number of OS and libc versions" OFF)
+option(gRPC_BUILD_PLUGIN_SUPPORT_ONLY "Build plugin support only" OFF)
 
 set(gRPC_INSTALL_default ON)
 if(NOT CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
@@ -361,6 +362,8 @@ add_custom_target(plugins
   DEPENDS ${_gRPC_PLUGIN_LIST}
 )
 
+if (NOT gRPC_BUILD_PLUGIN_SUPPORT_ONLY)
+
 add_custom_target(tools_c
   DEPENDS
   check_epollexclusive
@@ -3639,6 +3642,7 @@ if(gRPC_INSTALL)
   )
 endif()
 
+endif() # gRPC_BUILD_PLUGIN_SUPPORT_ONLY
 
 add_library(grpc_plugin_support
   src/compiler/cpp_generator.cc
@@ -3705,6 +3709,7 @@ if(gRPC_INSTALL)
   )
 endif()
 
+if(NOT gRPC_BUILD_PLUGIN_SUPPORT_ONLY)
 
 # grpcpp_channelz doesn't build with protobuf-lite
 # See https://github.com/grpc/grpc/issues/19473
@@ -11383,6 +11388,9 @@ target_link_libraries(grpc_cli
 
 
 endif()
+
+endif() # gRPC_BUILD_PLUGIN_SUPPORT_ONLY
+
 if(gRPC_BUILD_CODEGEN AND gRPC_BUILD_GRPC_CPP_PLUGIN)
 
 add_executable(grpc_cpp_plugin
@@ -11649,6 +11657,9 @@ if(gRPC_INSTALL)
 endif()
 
 endif()
+
+if (NOT gRPC_BUILD_PLUGIN_SUPPORT_ONLY)
+
 if(gRPC_BUILD_TESTS)
 
 add_executable(grpc_tls_certificate_distributor_test
@@ -16371,3 +16382,6 @@ generate_pkgconfig(
   "-lgrpc++_unsecure -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_exponential_biased -labsl_hash -labsl_city -labsl_statusor -labsl_bad_variant_access -labsl_status -labsl_cord -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_stacktrace -labsl_debugging_internal -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_civil_time -labsl_strings -labsl_strings_internal -labsl_throw_delegate -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_bad_optional_access -labsl_raw_logging_internal -labsl_log_severity"
   ""
   "grpc++_unsecure.pc")
+
+endif() # gRPC_BUILD_PLUGIN_SUPPORT_ONLY
+
-- 
2.26.2
```
