### ISSUE TITLE
Insecure encryption algorithms in the pem

### ISSUE THREAD

**Issue by upgiveup** [grpc/grpc#25331]
Hi, the grpc/_cython/_credentials/roots.pem in the grpc uses the Insecure encryption algorithms, sha1WithRSAEncryption; could you change it with secure encryption algorithms such as sha256? Thank you very much.

**Comment by jiangtaoli2016** [comment]
roots.pem comes from Mozilla published [roots](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt). 

Which entry uses sha1WithRSAEncryption?
