### ISSUE TITLE
Unity tvOS support for C#

### ISSUE THREAD

**Issue by shubear** [grpc/grpc#25349]
### Is your feature request related to a problem? Please describe.
gRPC csharp doesn't have support for tvOS with Unity

### Describe the solution you'd like
Add support for tvOS with Unity in csharp

### Describe alternatives you've considered
N/A

### Additional context
I have attached a patch (renamed as txt) for the changes. I have successfully built and used this on tvOS and Unity.

[tvOS_support_for_csharp_unity.txt](https://github.com/grpc/grpc/files/5923785/tvOS_support_for_csharp_unity.txt)

**Comment by jtattermusch** [comment]
Since Grpc.Core is now in maintenance mode (see https://grpc.io/blog/grpc-csharp-future/), we don't plan to add any new features (or add support for more platforms).
