### ISSUE TITLE
[grpc objc over cronet] support gzip for client messages including messages with content size = 0 

### ISSUE THREAD

**Issue by XinLin** [grpc/grpc#25352]
### Is your feature request related to a problem? Please describe.
grpc objc over http2 support gzip all request messages even messages with content size = 0;
but grpc objc over cronet will crash when enable gzip for client messages with content size = 0.

see issue [25302](https://github.com/grpc/grpc/issues/25302)

### Describe the solution you'd like
grpc objc over cronet should have the similar behavior with http2 when gzip client messages with content size = 0.

### Additional context
Add any other context about the feature request here.

**Comment by yulin-liang** [comment]
<img width="1011" alt="Screen Shot 2021-02-08 at 2 19 15 PM" src="https://user-images.githubusercontent.com/64815511/107290284-1beb5180-6a1b-11eb-990e-7827e3bcc9f1.png">
I can reproduce the issue in **v1.31.0**, but it has already been fixed in **v1.35.0**, you can try the latest version.
