### ISSUE TITLE
Reopening issues-13327 (seg fault - multithreading scenario)

### ISSUE THREAD

**Issue by PiotrZakrzewski** [grpc/grpc#25353]
Short desc: seg fault while using grpc within google-cloud-logging when running with multiple threads (python3.8).
### What version of gRPC and what language are you using?
protobuf==3.14.0
google-api-core==1.25.1
google-auth==1.25.0
google-cloud-core==1.5.0
google-cloud-logging==2.2.0
googleapis-common-protos==1.52.0

### What operating system (Linux, Windows,...) and version?
Dockerized Ubuntu 20.04 (python-slim)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8.7

### What did you do?

Same as others described in [issue-13327](https://github.com/grpc/grpc/issues/13327) I attempted to send multiple messages per second from many different threads. Seg fault occurs near instantly. 

### What did you expect to see?
No seg-fault / more descriptive error

### What did you see instead?

```
kernel: [730181.560134] grpc_global_tim[113291]: segfault at 5c ip 00007feff7c8e6c1 sp 00007fefd7ffec20 error 6 in cygrpc.cpython-38-x86_64-linux-gnu.so[7feff7a50000+541000]
```

**Comment by gnossen** [comment]
@PiotrZakrzewski What version of the `grpcio` wheel were you using? Can you please provide a core dump?

**Comment by gnossen** [comment]
Also, could you please use [one of our nightly builds](https://packages.grpc.io/archive/2021/02/4dc84aea46396cde21d13813efcf8ca3b2fda692-0cfa9cb0-c8c8-45f0-b055-48770e1c386c/python/grpcio/grpcio-1.36.0.dev0-cp38-cp38-manylinux2014_x86_64.whl) when generating the core dump? Our nightly builds are unstripped, which will help us to interpret the output.

**Comment by PiotrZakrzewski** [comment]
> @PiotrZakrzewski What version of the `grpcio` wheel were you using? Can you please provide a core dump?

grpcio-1.35.0

**Comment by gnossen** [comment]
Friendly ping. There's not much we can do without more information.

**Comment by PiotrZakrzewski** [comment]
Sorry! once we turned off GRPC we could once again get gcp logging working, which made it less urgent. I will try to provide the dump in the coming week!

**Comment by PiotrZakrzewski** [comment]
I verified that the issue no longer occurs on version 2.3.1 of google-cloud-logging (which uses the latest grpc )
