### ISSUE TITLE
C++ client has an undocumented limitation on the length of error messages

### ISSUE THREAD

**Issue by yasushi-saito** [grpc/grpc#25371]
I have a Go GRPC server (1.35) talking to a C++ client (1.34).

When the server responds with an error whose binary-encoded size exceeds 8000 bytes,  the client sees an error: code=INTERNAL, message="Received RST_STREAM with error code 2", instead of the error code/message that the server application actually sent.

This problem doesn't happen with the Go client nor grpc-web client. 

Can we either fix this problem, or at least document the limitation.

Both the client and the server are running on Ubuntu 20.04.

**Comment by yashykt** [comment]
I think the setting you are running into is https://github.com/grpc/grpc/blob/c8c80fd9988fb5e508ae2f6b39e7901c2054d4f6/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L63

To modify it, for C++, you can add the following channel argument on the client side - 
https://github.com/grpc/grpc/blob/c8c80fd9988fb5e508ae2f6b39e7901c2054d4f6/include/grpc/impl/codegen/grpc_types.h#L293
