### ISSUE TITLE
Worker thread hangs if response is not properly formed

### ISSUE THREAD

**Issue by jakubednarek** [grpc/grpc#25373]
### What version of gRPC and what language are you using?
ruby, versions: 1.35, 1.26

### What operating system (Linux, Windows,...) and version?
Linux, MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]

### What did you do?
I returned non-serializable response from the request handler:
```
    def get_customer(_request, _call)
      true
    end
```
While this is clearly an application-level error which needs to be fixed, grpc library should handle it "more gracefully", since it can happen in some complex handlers. Also, due to the fact that it blocks the worker thread for 10 seconds, it can reduce availibity of entire gRPC server.

### What did you expect to see?
An UNKNOWN (or any other more suitable) error code returned to the client.

### What did you see instead?
Worker thread hanged for 10 seconds which resulted in DEADLINE_EXCEEDED error on client side.

## Investigation results
After returning incorrect response from the handler we can observe an error when encoding response, which is expected:
```
2021-02-08 12:41:24.220469 W [5056:70237417735820] GRPC -- failed handler: #<GRPC::ActiveCall:0x00007fc2dece15f0>; sending status:UNKNOWN
2021-02-08 12:41:24.220476 W [5056:70237417735820 rpc_desc.rb:35] GRPC -- Exception: NoMethodError: undefined method `encode' for TrueClass:Class
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_desc.rb:35:in `block in marshal_proc'
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:235:in `server_unary_response'
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
```
Which is caught [here]( https://github.com/grpc/grpc/blob/d374ee9a4f2bf6945f296fe9894aecbbed496f45/src%2Fruby%2Flib%2Fgrpc%2Fgeneric%2Frpc_desc.rb#L153)
As we can see from the code, UNKNOWN error should be send. But in reality, worker thread hangs and we get another exception after 10 seconds:

```
2021-02-08 12:41:34.215607 W [5056:70237417735820] GRPC -- Error in worker thread
2021-02-08 12:41:34.215643 W [5056:70237417735820 active_call.rb:213] GRPC -- Exception: GRPC::Core::CallError: call#run_batch failed somehow
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:213:in `run_batch'
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:213:in `send_status'
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_desc.rb:197:in `send_status'
/Users/jakub/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_desc.rb:152:in `rescue in run_server_method'
```

## Possible solution
I took a quick look at the source code and found a potential fix, which solves the problem but I'm not entirely sure whether it is a proper fix - I came up with a solution only by deduction.
So, basically I checked how this flow is different from the flow where exception is thrown in application code and found out that [these couple of lines](https://github.com/grpc/grpc/blob/90f13f08f06993768b58cb3431d83ab2f5f5f5cc/src%2Fruby%2Flib%2Fgrpc%2Fgeneric%2Factive_call.rb#L228-L232) are executed before marshalling.
So the fix is to move them after `payload = @marshal.call(req)`, so that they are executed only if the marshalling is done without any exceptions. I guess that "moved lines" modify global state which affects the execution of run_batch function when sending error code.
After implementing the fix, everything works as expected, i.e client receives UNKNOWN code with nice error message: "NoMethodError: undefined method `encode' for TrueClass:Class"

If you're happy with the fix, I can prepare a PR with the described changes.

### Anything else we should know about your project / environment?
Same behaviour is present in 1.26 and 1.35

**Comment by alto-ruby** [comment]
Yes, this is caused by line 231: `@metadata_sent = true`, yet the constructed ops were dropped due to the exception; when exception was handled, [send_status](https://github.com/grpc/grpc/blob/90f13f08f06993768b58cb3431d83ab2f5f5f5cc/src%2Fruby%2Flib%2Fgrpc%2Fgeneric%2Factive_call.rb#L207) was called but mistakenly determined that the initial metadata was already sent and caused c-core stuck there.

Your proposal would be the correct fix, and is also what's being done [at the client side](https://github.com/grpc/grpc/blob/90f13f08f06993768b58cb3431d83ab2f5f5f5cc/src%2Fruby%2Flib%2Fgrpc%2Fgeneric%2Factive_call.rb#L351-L364).

Thanks for raising this and the detailed analysis, welcome to create a PR to address this. @jakubednarek
