### ISSUE TITLE
[Flake] Basic Tests C# Linux build

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#25370]
toplevel_run_tests_invocations_run_tests_csharp_linux_opt_native_default_coreclr.run_tests_csharp_linux_opt_native_default_coreclr

https://source.cloud.google.com/results/invocations/ce9e553e-f5b5-4d9b-b337-ba0526a62100/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_csharp_linux_opt_native_default_coreclr/tests

**Comment by jtattermusch** [comment]
I only saw this fail once and builds over last several days are passing.
