### ISSUE TITLE
grpcio build error in docker apline arm

### ISSUE THREAD

**Issue by michaelaelise** [grpc/grpc#25386]
Hello,
During the build of grpcio I get the following error
`#53 3655.1   src/core/lib/gpr/time_posix.cc:77:13: error: 'SYS_clock_gettime' was not declared in this scope; did you mean 'SYS_clock_gettime64'?
#53 3655.1      77 |     syscall(SYS_clock_gettime, clockid_for_gpr_clock[clock_type], &now);
#53 3655.1         |             ^~~~~~~~~~~~~~~~~
#53 3655.1         |             SYS_clock_gettime64`

The requirements file look like:
`django==1.11.17
djangorestframework==3.7.0
django-rest-swagger==2.1.2
djangorestframework-jwt==1.11.0
django-celery==3.2.1
pytz==2020.4
mock==2.0.0
tzlocal==1.4
olefile==0.44
pillow==4.2.1
setuptools==50.3.2
reportlab==3.4.0
bcrypt==3.1.3
psutil==5.7.3
psycopg2==2.8.6
pyyaml==5.2
cryptography==3.3.2
rsa>=3.4.2
pyOpenSSL>=18.0.0
crcmod==1.7
paho-mqtt==1.4.0
python-dateutil==2.7.3
google-cloud-pubsub>=2.0.0`

And the build command is like:
`docker buildx build --push --platform linux/arm/v7,linux/amd64 --tag <redacted.azurecr.io/<redacted>:dev_02082021 .
`

The dockerfile contains the following that install the apk prior to the python requirements being installed.
`RUN set -ex \
    && if [[ `uname -m` == 'x86_64' ]]; then apk add --no-cache --virtual .build-deps cmake curl g++ gcc jpeg-dev libffi-dev libjpeg make musl-dev postgresql-dev python3-dev tzdata zlib zlib-dev openssl-dev; else apk add --no-cache --virtual .build-deps cmake curl g++ gcc jpeg-dev libffi-dev libjpeg make musl-dev musl postgresql-dev python3-dev tzdata zlib zlib-dev libc6-compat libc-dev alpine-sdk build-base linux-headers cython c-ares-dev gdbm libffi openssl-dev; fi;`

It is the armv7 version that is failing.

So far everything else is building fine in both amd64 and armv7. It is only grpcio that fails.

Please let me know any other info that is needed.

Oh and it is using the docker image `FROM python:3.8-alpine as builder`

I have successfully built this directly on an armhf device in the past.

**Comment by michaelaelise** [comment]
Here is more from around the error

> #12 4226.4   gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -D_WIN32_WINNT=1536 -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/zlib -I/usr/local/include/python3.8 -c src/core/lib/gpr/time_posix.cc -o python_build/temp.linux-armv7l-3.8/src/core/lib/gpr/time_posix.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
#12 4226.4   cc1plus: warning: command-line option '-std=gnu99' is valid for C/ObjC but not for C++
#12 4226.4   src/core/lib/gpr/time_posix.cc: In function 'gpr_timespec now_impl(gpr_clock_type)':
#12 4226.4   src/core/lib/gpr/time_posix.cc:77:13: error: 'SYS_clock_gettime' was not declared in this scope; did you mean 'SYS_clock_gettime64'?
#12 4226.4      77 |     syscall(SYS_clock_gettime, clockid_for_gpr_clock[clock_type], &now);
#12 4226.4         |             ^~~~~~~~~~~~~~~~~
#12 4226.4         |             SYS_clock_gettime64

**Comment by michaelaelise** [comment]
How come on pypi (https://pypi.org/project/grpcio/#files) the wheels for armv7 stop at python 3.6?

**Comment by michaelaelise** [comment]
So I found in the source for time_posix.cc:
`#if defined(GPR_BACKWARDS_COMPATIBILITY_MODE) && defined(__linux__)
    /* avoid ABI problems by invoking syscalls directly */
    syscall(SYS_clock_gettime, clockid_for_gpr_clock[clock_type], &now);
#else
    clock_gettime(clockid_for_gpr_clock[clock_type], &now);
#endif
    return gpr_from_timespec(now, clock_type);`

And in the setup.py in the grpcio source is:

`if not DISABLE_LIBC_COMPATIBILITY:
    DEFINE_MACROS += (('GPR_BACKWARDS_COMPATIBILITY_MODE', 1),)`

Which is determined by:
`DISABLE_LIBC_COMPATIBILITY = os.environ.get(
    'GRPC_PYTHON_DISABLE_LIBC_COMPATIBILITY', False)`

So I am going to `RUN export GRPC_PYTHON_DISABLE_LIBC_COMPATIBILITY=1` as the command before it runs `RUN pip3 install -r requirements.txt` and we will see if it builds without failure.

**Comment by michaelaelise** [comment]
Oh, looks as if someone else had a similar issue: https://github.com/termux/termux-packages/issues/5162

**Comment by michaelaelise** [comment]
Success.
`GRPC_PYTHON_DISABLE_LIBC_COMPATIBILITY=1 pip install ....`
It built and is working.
@veblush Is that environment variable documented anywhere?
Building and running in python alpine arm images has always posed issues with grpcio.
Setting this variable does seem to be the fix!

**Comment by veblush** [comment]
@michaelaelise Can you try to install `linux-headers` in advance? (ref: https://github.com/grpc/grpc/issues/21918)

**Comment by michaelaelise** [comment]
@veblush In my original post is the following and it does contain linux-headers,

`The dockerfile contains the following that install the apk prior to the python requirements being installed.
RUN set -ex \ && if [[ uname -m == 'x86_64' ]]; then apk add --no-cache --virtual .build-deps cmake curl g++ gcc jpeg-dev libffi-dev libjpeg make musl-dev postgresql-dev python3-dev tzdata zlib zlib-dev openssl-dev; else apk add --no-cache --virtual .build-deps cmake curl g++ gcc jpeg-dev libffi-dev libjpeg make musl-dev musl postgresql-dev python3-dev tzdata zlib zlib-dev libc6-compat libc-dev alpine-sdk build-base linux-headers cython c-ares-dev gdbm libffi openssl-dev; fi;`

**Comment by veblush** [comment]
@michaelaelise I guess this was introduced by the recent musl change. (presumably this [commit](http://git.musl-libc.org/cgit/musl/commit/?id=2cae9f59da6106b4545da85b33d1e206a1e4c1e7)). Let me try to fix this without the flag.
