### ISSUE TITLE
Macos Bazel opt build failue: src/cpp/server/server_cc.cc:765:31: error: unused parameter 'ok'

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25436]
Error is:

```
Use --sandbox_debug to see verbose messages from the sandbox
src/cpp/server/server_cc.cc:765:31: error: unused parameter 'ok' [-Werror,-Wunused-parameter]
  void DoWork(void* tag, bool ok, bool resources) override {
                              ^
1 error generated.
INFO: Elapsed time: 542.743s, Critical Path
```

Full log: https://source.cloud.google.com/results/invocations/8cbb1be3-1919-4237-a4fd-3c1b43a67e01/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_build_artifacts/log

Seen in unrelated PR: https://github.com/grpc/grpc/pull/25406

Seems related to https://github.com/grpc/grpc/commit/9cceb28b2e5dcabd92a54d84ac0e3d546aa9680f#diff-afab775337cea1e27d51243874ffb2e89d8c9fac8adce2577c39ca7735dc0497

Looks like the `ok` param to `DoWork` under opt builds since `ok` is now read only inside of a `GPR_DEBUG_ASSERT`.

**Comment by stanley-cheung** [comment]
#25438

**Comment by apolcyn** [comment]
https://github.com/grpc/grpc/pull/25438 should fix this
