### ISSUE TITLE
[FLAKE] C# build package failed on v1.36.x

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#25458]
```
+ cp nativelibs/csharp_ext_linux_x64/libgrpc_csharp_ext.so ../../cmake/build
cp: cannot stat 'nativelibs/csharp_ext_linux_x64/libgrpc_csharp_ext.so': No such file or directory
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc/artifacts
+ docker cp build_and_run_docker_136230c6-2b80-415b-8566-aecb20b694ac:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
+ docker rm -f build_and_run_docker_136230c6-2b80-415b-8566-aecb20b694ac
build_and_run_docker_136230c6-2b80-415b-8566-aecb20b694ac
+ '[' true '!=' '' ']'
+ exit 1

2021-02-12 10:24:15,859 FAILED: build_package.csharp_package_nuget_linux [ret=1, pid=6656, time=148.2sec]
```

https://fusion2.corp.google.com/invocations/63b7be2c-6801-4ad8-991e-a179df1d9431/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_packages;config=default/log

With https://github.com/grpc/grpc/pull/25433, the artifact build passes the dependency pulling stage but failed with above message.

**Comment by jtattermusch** [comment]
I suspect the problem is that in the previous stage (build_artifacts, but I don't have a link for that build) the artifact build has failed (for multiple languages actually) and that why the package build is missing the .so files to build the nuget  package.

**Comment by lidizheng** [comment]
The link to build_artifacts [sponge/8df99f11-f530-46b5-89ff-61669f0292b5](http://sponge/8df99f11-f530-46b5-89ff-61669f0292b5).

In a new build [sponge/6749ca03-c4a9-4c18-ac53-8ed306ae54f7](http://sponge/6749ca03-c4a9-4c18-ac53-8ed306ae54f7), the Linux C# build passes but other builds failed. Since this is not a reproducible error, I guess I will re-run the builds to see if any thing breaks again.

Thanks for taking time looking into this issue. There isn't an action item on this issue. Closing.
