### ISSUE TITLE
gRPC cannot compile the protos in googleapis/gooogleapis

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#25508]
### What version of gRPC and what language are you using?

1.35.0, C++

### What operating system (Linux, Windows,...) and version?

Linux, Ubuntu:20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

g++, GCC-9:

```console
$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### What did you do?

This was motivated by customers reporting a bug (GoogleCloudPlatform/cpp-samples#113).  Download and build gRPC using the instructions from:

https://grpc.io/docs/languages/cpp/quickstart/

Then compiled googleapis/googleapis. The gRPC plugin crashes.

The **exact** steps I used to reproduce this problem can be found in this 
[Dockerfile](https://github.com/grpc/grpc/files/6012558/repro-cpp-samples-113-v3.Dockerfile.txt), you can run that using `cat Dockerfile | docker build -`.

This produced the following error:

### What did you expect to see?

A clean build.

### What did you see instead?

A build failure:

```
[libprotobuf FATAL /source/grpc/third_party/protobuf/src/google/protobuf/io/printer.cc:142]  Unclosed variable name.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():   Unclosed variable name.
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
make: *** [Makefile:45: google/maps/routes/v1/route_service.pb.cc] Error 1
```

### Anything else we should know about your project / environment?

I may send CLs to cleanup googleapis/googleapis. For future reference, the version I used was:

https://github.com/googleapis/googleapis/tree/151bfbae10c02f51f07972097b3f72812738dcb9

**Comment by coryan** [comment]
Thanks to @mpietras for documenting the steps necessary to reproduce this problem.

**Comment by coryan** [comment]
Ping. It has been two weeks, any thoughts?

**Comment by karthikravis** [comment]
Esun - can you please take a look when you get a chance? Thanks!

**Comment by veblush** [comment]
https://github.com/grpc/grpc/pull/25538 is in progress to address this.

**Comment by drfloob** [comment]
This was fixed for C++ generated code in https://github.com/grpc/grpc/pull/32190, but I've expanded it to support all wrapped languages in https://github.com/grpc/grpc/pull/32411
