### ISSUE TITLE
Is it Possible to use only one gRPC Channel for 2 Pair Client/Server

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc#25516]
I have a use case that force me to use 2 Pair Client/Server, for some illustration :
I have 2 processes which each of two are playing Client / Server Role, for this reason I have to create 2 Pair Client/Server.
My Question to minimize the overhead of creating 2 Channel to achieve this communication, do we have any possibility to use only one Channel?

Note  : Dual streaming wouldn't help, since in my case the two processes play the Server/Client Role.
 
Thanks for any Help.

**Comment by karthikravis** [comment]
For questions, please use stackoverflow with the grpc tag.
