### ISSUE TITLE
gRPC cannot compile 

### ISSUE THREAD

**Issue by DavenAaron** [grpc/grpc#25520]
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/client_context.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/create_channel.cc.o
[ 97%] Linking CXX executable gen_hpack_tables
[ 97%] Linking C shared library libgrpc_csharp_ext.so
libgrpc.so.14.0.0: undefined reference to `inflateInit2_'
libgrpc.so.14.0.0: undefined reference to `inflate'
libgrpc.so.14.0.0: undefined reference to `deflateInit2_'
libgrpc.so.14.0.0: undefined reference to `deflate'
libgrpc.so.14.0.0: undefined reference to `deflateEnd'
libgrpc.so.14.0.0: undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [check_epollexclusive] Error 1
make[1]: *** [CMakeFiles/check_epollexclusive.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/create_channel_internal.cc.o
[ 97%] Built target grpc_csharp_ext
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/create_channel_posix.cc.o
libgrpc.so.14.0.0: undefined reference to `inflateInit2_'
libgrpc.so.14.0.0: undefined reference to `inflate'
libgrpc.so.14.0.0: undefined reference to `deflateInit2_'
libgrpc.so.14.0.0: undefined reference to `deflate'
libgrpc.so.14.0.0: undefined reference to `deflateEnd'
libgrpc.so.14.0.0: undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [gen_hpack_tables] Error 1
make[1]: *** [CMakeFiles/gen_hpack_tables.dir/all] Error 2
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/credentials_cc.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/insecure_credentials.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/secure_credentials.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/client/xds_credentials.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/codegen/codegen_init.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/alarm.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/auth_property_iterator.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/channel_arguments.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/channel_filter.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/completion_queue_cc.cc.o
[ 97%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/core_codegen.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/resource_quota_cc.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/rpc_method.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/secure_auth_context.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/secure_channel_arguments.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/secure_create_auth_context.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/tls_certificate_provider.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/tls_credentials_options.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/tls_credentials_options_util.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/validate_service_config.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/common/version_cc.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/async_generic_service.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/channel_argument_option.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/create_default_thread_pool.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/dynamic_thread_pool.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/external_connection_acceptor_impl.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/health/default_health_check_service.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/health/health_check_service.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/health/health_check_service_server_builder_option.cc.o
[ 98%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/insecure_server_credentials.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/secure_server_credentials.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_builder.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_callback.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_cc.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_context.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_credentials.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_posix.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/thread_manager/thread_manager.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/byte_buffer_cc.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/status.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/string_ref.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/time_cc.cc.o
[ 99%] Linking CXX shared library libgrpc++.so
[ 99%] Built target grpc++
make: *** [all] Error 2

cmake version 3.19.0-rc1
CentOS Linux release 7.8.2003 (Core)
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

**Comment by DavenAaron** [comment]
git clone --depth 1 -b v1.34.x https://github.com/grpc/grpc.git /var/local/git/grpc
cd /var/local/git/grpc
git submodule update --init --recursive

# protobuf
cd /var/local/git/grpc/third_party/protobuf
./autogen.sh
./configure
make -j$(nproc)
sudo make install
sudo ldconfig
make clean

# grpc
cd /var/local/git/grpc
mkdir -p cmake/build
cd cmake/build
cmake ../.. -DBUILD_SHARED_LIBS=ON -DgRPC_INSTALL=ON
make -j$(nproc)
sudo make install
make clean
sudo ldconfig

**Comment by karthikravis** [comment]
I tried the instructions here verbatim and I could build gRPC as well as the helloworld example using cmake - https://grpc.io/docs/languages/cpp/quickstart/

@DavenAaron : Can you please try this out?

**Comment by Zzjw** [comment]
I met the same question. 
This is the [reason](https://stackoverflow.com/questions/18053546/undefined-symbols-for-architecture-i386-deflate-referenced-from-platcompres)

Then I tried "cmake -DgRPC_INSTALL=ON  -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR ../.." again, and I got 
`CMake Warning at cmake/zlib.cmake:39 (message):
  gRPC_ZLIB_PROVIDER is "module" but ZLIB_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:258 (include)`

I tried "echo $ZLIB_ROOT_DIR" in my terminal and got nothing.

I typed **export ZLIB_ROOT_DIR=/usr/local/opt/zlib (in my mac)** , then anything went well.

**Comment by yashykt** [comment]
Sounds like there is nothing else to be done here
