### ISSUE TITLE
GRPC installation hangs PHP 7.3

### ISSUE THREAD

**Issue by sayanthkoroth** [grpc/grpc#25543]
I am trying to install grpc with php 7.3

OS : Ubuntu 18.04
PHP : 7.3

The installation stuck after sometime

RK=1 -c /tmp/pear/temp/grpc/src/core/ext/xds/xds_client.cc  -fPIC -DPIC -o src/core/ext/xds/.libs/xds_client.o 

Instllation hangs in the above line

**Comment by stanley-cheung** [comment]
Looks like there may be problems with your environment. We have tests against 7.3 and Debian/Ubuntu based environments and didn't see a problem. I couldn't reproduce this with a manual test. If you have a more detail reproducible test case (like a docker image), please re-open with those additional details. Thanks.
