### ISSUE TITLE
Unresolved symbols when using static compilation (grpc installed via vcpkg)

### ISSUE THREAD

**Issue by M0n7y5** [grpc/grpc#25587]
### What version of gRPC and what language are you using?
**1.33.1** via vcpkg

### What operating system (Linux, Windows,...) and version?
**Windows 20H2**

### What runtime / compiler are you using (e.g. python version or version of gcc)
**MSVC 64Bit v142**

### What did you do?
I just tried statically compile this cpp example 
https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_client.cc

Static runtime enabled
![image](https://user-images.githubusercontent.com/17201053/109530201-c1dc2a00-7ab6-11eb-8367-965e963d3fb2.png)
And i am using static libs
![image](https://user-images.githubusercontent.com/17201053/109530143-b12bb400-7ab6-11eb-85d2-dcfebd2ccebb.png)

### What did you expect to see?
Successful compilation 

### What did you see instead?

```
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function capi_open_store
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertCloseStore referenced in function capi_find_key
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertEnumCertificatesInStore referenced in function capi_find_cert
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFindCertificateInStore referenced in function capi_find_cert
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertDuplicateCertificateContext referenced in function capi_load_ssl_client_cert
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function capi_find_key
1>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertGetCertificateContextProperty referenced in function capi_cert_get_fname
1>... Demo.exe : fatal error LNK1120: 7 unresolved externals
```

**Comment by jtattermusch** [comment]
Hi, please note that according to our documentations, the vcpkg packages are not officially supported (see https://github.com/grpc/grpc/tree/master/src/cpp#packaging-systems). From your report it's unclear whether there's a problem with the vcpkg package (which we don't maintain directly and you'd have to file an issue on the vcpkg repo, see the docs link) or if there's a different problem.

Also your instructions don't really make it clear what it is that you've tried (what are the steps?), so it would be hard to reproduce. Some random questions: Is the problem with just the static linking and dynamic works for you? How did you include grpc into your project? did you create the VS project for greeter demo manually or did you import our CMake file?

**Comment by M0n7y5** [comment]
Basically what i did is install needed packages using vcpkg and then copy and pasted helloword example. Dynamic linking is working without problems. I am not using CMake.

**Comment by M0n7y5** [comment]
I can make some repo with that code i you want.

**Comment by jtattermusch** [comment]
> I can make some repo with that code if you want.

Yes please, that would be useful.

**Comment by M0n7y5** [comment]
> > I can make some repo with that code if you want.
> 
> Yes please, that would be useful.

Done 
https://github.com/M0n7y5/grpcStaticTest

**Comment by M0n7y5** [comment]
I think i found a solution https://github.com/openssl/openssl/issues/1061
