### ISSUE TITLE
gRPC server hosted and running in a Windows Service (NET Framework 4.6)

### ISSUE THREAD

**Issue by KHAuckland2021** [grpc/grpc#25581]
Package Grpc.Core V2.36.0
Package Grpc.Core.Api V2.36.0

Project: Windows Service, .NET Framework 4.7.2

I have hosted a gRPC server within a Windows Service (NET Framework 4.6).
When the Windows Service starts up (OnStart()), it also starts the gRPC server, without any errors.
When I send a message to the gRPC server however, the client reports an exception:

GPIB SendCommand exception: 
```
Status(StatusCode="Unknown", Detail="Exception was thrown by handler.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1614392967.578000000","description":"Error received from peer ipv4:127.0.0.1:50051","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Exception was thrown by handler.","grpc_status":2}")
```

I enabled the gRPC trace on the server, attached is the log file when it receives the message from the client (see ...Exception occurred in the handler or an interceptor.)
[grpcTrace.txt](https://github.com/grpc/grpc/files/6053583/grpcTrace.txt)
.

Note, if the same gRPC server runs in a command window, there are no errors. It seems to be related to the Windows Service.

**Comment by jtattermusch** [comment]
From the log it looks like that the call was successfully invoked
and the server-side handler actually started, but then it threw an exception for some reason. The exception was then caught by the server-side grpc logic and the error "Exception was thrown by handler." was reported back to the client.
That seems to indicate that the RPC invocation actually makes it all the way to the server-side handler code (provided by you) and error is successfully reported back to the client.

Once you figure out what is the exception being thrown on the server-side, that will probably explain what's wrong.

You can try to set a breakpoint here and see what the excpetion is?
https://github.com/grpc/grpc/blob/86f93801e5d452cff40d6958d21a8eb211da0654/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L78

https://github.com/grpc/grpc/blob/86f93801e5d452cff40d6958d21a8eb211da0654/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L80

**Comment by jtattermusch** [comment]
Closing since we haven't heard back from the user.
