### ISSUE TITLE
Lots of warnings during x64 compilation using Ninja + Visual Studio v16.8.6 under Windows

### ISSUE THREAD

**Issue by amasciotta** [grpc/grpc#25596]
### What version of gRPC and what language are you using?
gRPC v1.36.0, C++ language

### What operating system (Linux, Windows,...) and version?
Windows 10 Pro 20H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Ninja as build system + MSVC 19.28.29337 for x64 (Visual Studio Professional v16.8.6)

### What did you do?
I'm compiling gRPC from sources using the following commands, run from grpc directory after cloning the repo
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"
cd cmake
mkdir build
cd build
cmake ..\.. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\..\install\x64\Release
cmake --build .
```

### What did you expect to see?
No (or a few) warnings

### What did you see instead?
Lots of warning, mainly C4334 and C4090, but also quite a few of other types (C4715, C4146 and others), mainly coming from files in the `third_party\upb` directory.

**Comment by veblush** [comment]
@amasciotta Thank you for the issue but we generally fix the warnings issue since we cannot remove them entirely on all compilers but having tons of them might be caused by single code which we can do. Can you attach a full log having warnings so that we can take a look at?

**Comment by amasciotta** [comment]
Here you are! The log has been produced by piping to file the output of the following commands:

```
echo off
rem Run from grpc directory after cloning the repo with --recursive or updating submodules.
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"
cd cmake
rem Building x64 Release
mkdir build_x64_Release
cd build_x64_Release
cmake ..\.. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\..\install\x64\Release
cmake --build .
```

[log.txt](https://github.com/grpc/grpc/files/6089444/log.txt)

**Comment by veblush** [comment]
I think this may be fixed because most of warnings came from upb which has been upgraded since then.
