### ISSUE TITLE
Drop support for 32-bit macos ruby builds

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25604]
This tracks dropping support for 32-bit macos ruby builds, which haven't been needed on macos for a while. cc @nicolasnoble

**Comment by alto-ruby** [comment]
@apolcyn I couldn't find "32-bit macos ruby builds" in the code base, is this still an issue?

**Comment by alto-ruby** [comment]
Looks like 32 bit macos build was removed with #24870
