### ISSUE TITLE
TLS 1.0 mentioned in client hello packets

### ISSUE THREAD

**Issue by anlsh** [grpc/grpc#25616]
I've been having some trouble making connections from C-core clients to an asp.net core server (you can read about that [here](https://stackoverflow.com/questions/66478939/https-grpc-connections-from-c-core-clients-to-net-core-server-tls-handshake-fa) for more info), but the gist is that the TLS handshake is failing and I used wireshark to inspect some packets.

In wireshark, I noticed that the client hello packets sent by the GRPC C core clients I've tested (which all immediately get a handshake error packet from the server) have a TLS section that starts with

```
Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 512
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 508
            Version: TLS 1.2 (0x0303)
```
Note the reference to TLS 1.0 sandwiched in the middle. On the other hand, the client hello sent by the .net core client (which succeeds in establishing/using a tls connection) doesn't mention TLS 1.0 anywhere and succeeds in eliciting a TLS server hello
```
 Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 160
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 156
            Version: TLS 1.2 (0x0303)
```

I was wondering if this was a bug in GRPC, or perhaps in OpenSSL (BoringSSL?). 

The python client sending that failing packet  is run via Python 3, Ubuntu 18.04 (on WSL) 
```
$ openssl version
OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.1  11 Sep 2018) 
```

There are other differences between the client hello packets too: I mention a couple in the linked stackoverflow post, where I provide the raw client hellos and server hello as well. This TLS thing is just what immediately seemed odd to me

**Comment by anlsh** [comment]
I think there's a

**Comment by jiangtaoli2016** [comment]
@anlsh You have an unfinished sentence. We need some reproduction of error before we can debug.

**Comment by anlsh** [comment]
Oh, I thought I deleted that pretty quickly. Guess you were on at just the right time :D 

I have a repro, but I no longer suspect that this is a c-core bug. When running the same asp.net core server on linux, it accepts a client hello with the following TLS header just fine
```
Transport Layer Security
    TLSv1.3 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 303
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 299
            Version: TLS 1.2 (0x0303)
```

I suspect that some SSL configuration on asp.net core for/or on windows is to blame. Closing

**Comment by davidben** [comment]
The TLS 1.0 in there is the record later version, which is a vestigial unused version number. We set it to TLS 1.0 in the initial ClientHello because, at least in the early days of TLS 1.1 and 1.2, that was the correct value for compatibility with some old servers. Since it's entirely irrelevant anyway, there doesn't seem much point in revisiting this.

See the definition of legacy_record_version here.
https://tools.ietf.org/html/rfc8446#section-5.1

**Comment by jiangtaoli2016** [comment]
Thanks @davidben for confirming! I found similarly discussion online as well.

**Comment by anlsh** [comment]
Thanks for the confirmation.

@jiangtaoli2016 tangentially related question, do you know how to force GRPC to use TLS 1.2, ie disable TLS 1.3 (I believe this is relevant for getting my clients to connect to the windows aspnetcore server).

I found [this page](https://www.openssl.org/docs/man1.1.1/man3/SSL_CONF_cmd.html) and figured adding the line 
    
    MaxProtocol = TLSv1.2

to `/etc/ssl/openssl.cnf` would do it (I added it as the second line, right after `HOME = .`), but that didn't seem to change anything. Then I remembered GRPC on linux uses boringssl and figured I'd just ask.

**Comment by davidben** [comment]
BoringSSL does not parse a global config file like that, no. I expect there are gRPC APIs for controlling this.

That said, enabling TLS 1.3 should be backwards-compatible. You'll still be able to connect to TLS 1.2 servers. If you're having troubles connecting to some TLS 1.2 server with 1.3 enabled, that's a defect in the server. What evidence do you have that it's related to TLS 1.3?

Your link says the error is "No common application protocol exists between the client and the server. Application protocol negotiation failed". That has nothing to do with TLS 1.3 and is talking about ALPN, which gRPC requires in both TLS 1.2 and TLS 1.3.

**Comment by anlsh** [comment]
> That said, enabling TLS 1.3 should be backwards-compatible. You'll still be able to connect to TLS 1.2 servers. If you're having troubles connecting to some TLS 1.2 server with 1.3 enabled, that's a defect in the server. What evidence do you have that it's related to TLS 1.3?

It's not relevant anymore, I don't believe that TLS 1.3 was an issue: I recompiled GRPC on a version from last year before TLS 1.3 was enabled, used wireshark to confirm that traffic was going over TLS 1.2, and was able to reproduce the problematic behavior in my server (not the TLS version mixing in the packets to be clear, the `no common application protocol` error).

I'm still not totally what it is, but based on a repro I've done on another machine I *suspect* the issue is with Windows server 2019. I'm still investigating though. Either way I don't think it's an issue which concerns the C-core anymore, unless anyone's interested
