### ISSUE TITLE
FLAKE: tasks.distribtest.cpp_windows_x86_cmake is flaky (times out occasionally).

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#25614]
```
2021-03-03 06:54:45,155 TIMEOUT: distribtest.cpp_windows_x86_cmake [pid=392, time=1800.1sec]
```

https://source.cloud.google.com/results/invocations/168c92a0-9edd-465f-9676-13bda095c54b/targets/github%2Fgrpc/tests

**Comment by markdroth** [comment]
I assume you meant to self-assign this, since it seems like an infrastructure problem.

**Comment by jtattermusch** [comment]
Our cmake builds have been sped-up a lot since this was filed (use of ccache, ninja for windows builds) and it's unclear how frequent this issue originally was, so I'm going to close for now.
If we're to ever reopen, let's file an internal bug instead (we're going to track test flakiness in buganizer going forward).
