### ISSUE TITLE
As we konw，use proto generate code would be always include "pb2"，but what does the "2" mean？

### ISSUE THREAD

**Issue by lowmanisbusy** [grpc/grpc#25612]
As we konw，use proto to generate code would be always include "pb2"，but what does the "2" mean？I use "proto3".

./
├── client.py
├── helloworld_pb2_grpc.py
├── helloworld_pb2.py
├── helloworld.proto
├── Pipfile
├── Pipfile.lock
└── server.py

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
