### ISSUE TITLE
[Windows] Server does not throw an exception if it binds to a port that is already in use

### ISSUE THREAD

**Issue by andrekoehler** [grpc/grpc#25636]
### What version of gRPC and what language are you using?
C#, gRPC NuGet package v2.36.1

### What operating system (Linux, Windows,...) and version?
Microsoft Windows [Version 10.0.19042.844]

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET 4.8

### What did you do?
```
server = new Server(new [] { new ChannelOption(ChannelOptions.SoReuseport, 0) })
{
    Services = {
        Health.BindService(new HealthServiceImpl()),
    },
    Ports = {
        new ServerPort(
            "0.0.0.0",
             49667 /* port is already in use by a Windows service */,
             ServerCredentials.Insecure),
    }
};
try
{
    server.Start();
}
catch (IOException) // any port could not be bound
{
    // this code never runs because there is no exception
    // ...
}
```

### What did you expect to see?
The method "Server.Start" should throw an IOException (as documented here https://grpc.github.io/grpc/csharp/api/Grpc.Core.Server.html#Grpc_Core_Server_Start) because it should not be able to listen on a port that is already in use by some other process.

### What did you see instead?
"Server.Start" does not throw any exceptions.
Server.Ports.First().BoundPort does not equal 0.
According to the `netstat -a -b -o -n -p tcp` output, the port is bound by two processes at the same time:

>   TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING       27988
>  [SAM BalanceLab 3.exe]
>   TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING       1720
>   EventLog
>  [svchost.exe]

However, my gRPC client is not able to communicate with my server. It blocks endlessly at the first gRPC call.

I tried changing the channel option `SoReuseport` from 0 to 1 but it does not make any difference.
What does work is if I change the listening IP from "0.0.0.0" to "127.0.0.1". Then I get an exception as expected but then (if I use a free port) my server can only be reached from clients on localhost, but not on other computers.

**Comment by andrekoehler** [comment]
I found out the C# Socket class also allows to bind to a port that is already in use, but only when IPv4 and IPv6 are both enabled for a single socket with SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false). If SocketOptionName.ReuseAddress is false, I can only bind once to a port that is already in use by another process. If ReuseAddress is true I can bind as many times as I want.

```
using System;
using System.Net;
using System.Net.Sockets;

namespace Port
{
    class Program
    {
        static void Main()
        {
            Socket socket = new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp);
            socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);
            socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);
            socket.Bind(new IPEndPoint(IPAddress.IPv6Any, 49667)); // no exception here even though port 49667 is in use by a Windows service
            socket.Listen();
            Console.ReadKey();
        }
    }
}
```

**Comment by jtattermusch** [comment]
Some more insights:

I think the `ChannelOptions.SoReuseport` option, which corresponds to `grpc.so_reuseport` C-core argument is only supported on posix system (and isn't supported on Windows at all).

https://github.com/grpc/grpc/blob/6b8a17d1ead62022526d6156981aea0576155622/include/grpc/impl/codegen/grpc_types.h#L294

See the implementation for non-windows systems:
https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/core/lib/iomgr/tcp_server_posix.cc#L68 

and for windows:
https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/core/lib/iomgr/tcp_server_windows.cc#L103 (there is no mention of so_reuseport)

**Comment by jtattermusch** [comment]
What we could do:
- add a note to the documentation that grpc.so_reuseport is currently only supported on posix systems.
- report an error if trying to enable on windows?

**Comment by jtattermusch** [comment]
@nicolasnoble  can we somehow report an error if trying to bind to a port that's already in use on Windows?

**Comment by andrekoehler** [comment]
Thanks for your effort. My use case was not to bind to the same port multiple times but only to detect if the port is already in use. We use a hard-coded port by default and if this does not work (because on some machines Windows blocks it with svchost) we use a random available port and communicate it to the clients in the local network via DNS-SD.
