### ISSUE TITLE
Issue while compiling adding new proto files in grpc 

### ISSUE THREAD

**Issue by Bharat1981** [grpc/grpc#25646]
I am trying to add the  3rd party proto file but while compiling getting linking errors. While i using the sample program given those are working fine. I am using CMakeList.txt given for one of the sample program.
CMakeFiles/hw_grpc_proto.dir/build.make:71: warning: overriding recipe for target 'speech-to-text.pb.h'
CMakeFiles/hw_grpc_proto.dir/build.make:65: warning: ignoring old recipe for target 'speech-to-text.pb.h'
CMakeFiles/hw_grpc_proto.dir/build.make:71: warning: overriding recipe for target 'speech-to-text.pb.h'
CMakeFiles/hw_grpc_proto.dir/build.make:65: warning: ignoring old recipe for target 'speech-to-text.pb.h'
[ 66%] Built target hw_grpc_proto
[ 83%] Linking CXX executable client
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::clear_error()':
speech-to-text.pb.cc:(.text+0xc30d): undefined reference to `google::rpc::Status::~Status()'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::StreamingRecognizeResponse(speech_to_text::StreamingRecognizeResponse const&)':
speech-to-text.pb.cc:(.text+0xc4fe): undefined reference to `google::rpc::Status::Status(google::rpc::Status const&)'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::Clear()':
speech-to-text.pb.cc:(.text+0xc6b8): undefined reference to `google::rpc::Status::~Status()'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const':
speech-to-text.pb.cc:(.text+0xcaaa): undefined reference to `google::rpc::Status::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::MergeFrom(speech_to_text::StreamingRecognizeResponse const&)':
speech-to-text.pb.cc:(.text+0xd0d5): undefined reference to `google::rpc::Status::MergeFrom(google::rpc::Status const&)'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::SpeechOperation::clear_error()':
speech-to-text.pb.cc:(.text+0x11e8f): undefined reference to `google::rpc::Status::~Status()'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::SpeechOperation::SpeechOperation(speech_to_text::SpeechOperation const&)':
speech-to-text.pb.cc:(.text+0x1219a): undefined reference to `google::rpc::Status::MergeFrom(google::rpc::Status const&)'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::SpeechOperation::clear_result()':
speech-to-text.pb.cc:(.text+0x12332): undefined reference to `google::rpc::Status::~Status()'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::SpeechOperation::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const':
speech-to-text.pb.cc:(.text+0x12a43): undefined reference to `google::rpc::Status::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::SpeechOperation::MergeFrom(speech_to_text::SpeechOperation const&)':
speech-to-text.pb.cc:(.text+0x1309c): undefined reference to `google::rpc::Status::MergeFrom(google::rpc::Status const&)'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::_internal_error() const':
speech-to-text.pb.cc:(.text._ZNK14speech_to_text26StreamingRecognizeResponse15_internal_errorEv[_ZNK14speech_to_text26StreamingRecognizeResponse15_internal_errorEv]+0x28): undefined reference to `google::rpc::_Status_default_instance_'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::SpeechOperation::_internal_error() const':
speech-to-text.pb.cc:(.text._ZNK14speech_to_text15SpeechOperation15_internal_errorEv[_ZNK14speech_to_text15SpeechOperation15_internal_errorEv]+0x2d): undefined reference to `google::rpc::_Status_default_instance_'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o):(.data.rel+0x18): undefined reference to `scc_info_Status_google_2frpc_2fstatus_2eproto'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o):(.data.rel+0x58): undefined reference to `scc_info_Status_google_2frpc_2fstatus_2eproto'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o):(.data.rel.ro+0x0): undefined reference to `descriptor_table_google_2fapi_2fannotations_2eproto'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o):(.data.rel.ro+0x8): undefined reference to `descriptor_table_google_2fapi_2fclient_2eproto'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o):(.data.rel.ro+0x10): undefined reference to `descriptor_table_google_2fapi_2ffield_5fbehavior_2eproto'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o):(.data.rel.ro+0x18): undefined reference to `descriptor_table_google_2frpc_2fstatus_2eproto'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `speech_to_text::StreamingRecognizeResponse::SharedDtor()':
speech-to-text.pb.cc:(.text._ZN14speech_to_text26StreamingRecognizeResponse10SharedDtorEv[_ZN14speech_to_text26StreamingRecognizeResponse10SharedDtorEv]+0xb0): undefined reference to `google::rpc::Status::~Status()'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `google::rpc::Status* google::protobuf::MessageLite::CreateMaybeMessage<google::rpc::Status>(google::protobuf::Arena*)':
speech-to-text.pb.cc:(.text._ZN6google8protobuf11MessageLite18CreateMaybeMessageINS_3rpc6StatusEEEPT_PNS0_5ArenaE[_ZN6google8protobuf11MessageLite18CreateMaybeMessageINS_3rpc6StatusEEEPT_PNS0_5ArenaE]+0x18): undefined reference to `google::rpc::Status* google::protobuf::Arena::CreateMaybeMessage<google::rpc::Status>(google::protobuf::Arena*)'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `char const* google::protobuf::internal::ParseContext::ParseMessage<google::rpc::Status>(google::rpc::Status*, char const*)':
speech-to-text.pb.cc:(.text._ZN6google8protobuf8internal12ParseContext12ParseMessageINS_3rpc6StatusEEEPKcPT_S7_[_ZN6google8protobuf8internal12ParseContext12ParseMessageINS_3rpc6StatusEEEPKcPT_S7_]+0x8c): undefined reference to `google::rpc::Status::_InternalParse(char const*, google::protobuf::internal::ParseContext*)'
/usr/bin/ld: libhw_grpc_proto.a(speech-to-text.pb.cc.o): in function `unsigned long google::protobuf::internal::WireFormatLite::MessageSize<google::rpc::Status>(google::rpc::Status const&)':
speech-to-text.pb.cc:(.text._ZN6google8protobuf8internal14WireFormatLite11MessageSizeINS_3rpc6StatusEEEmRKT_[_ZN6google8protobuf8internal14WireFormatLite11MessageSizeINS_3rpc6StatusEEEmRKT_]+0x18): undefined reference to `google::rpc::Status::ByteSizeLong() const'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/client.dir/build.make:126: client] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/client.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[CMakeLists.txt](https://github.com/grpc/grpc/files/6102067/CMakeLists.txt)

I am looking here to get the CMakeList.txt file correction, Using latest 1.36.x version of the grpc and protobuf

**Comment by markdroth** [comment]
This form is for bugs and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
