### ISSUE TITLE
Dart Interop Test Dependency Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#25652]
```
SLVR:   fact: every version of grpc from path requires SDK version >=2.12.0 <3.0.0
SLVR:   conflict: every version of grpc from path requires SDK version >=2.12.0 <3.0.0
SLVR:   ! grpc from path is satisfied by grpc from path
SLVR:   ! which is caused by "interop depends on grpc from path"
SLVR:   ! thus: version solving failed
SLVR: Version solving took 0:00:00.826840 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.855s).
ERR : The current Dart SDK version is 2.12.0-259.1.beta.
```

https://source.cloud.google.com/results/invocations/09d73c51-868c-4764-94ee-be9d67052989/log
https://source.cloud.google.com/results/invocations/acf47daa-a296-49f2-b767-7147460e916d/log

**Comment by gnossen** [comment]
@stanley-cheung It looks like you dealt with something similar [here](https://github.com/grpc/grpc/pull/25305). Do you know who should be assigned to this?

**Comment by stanley-cheung** [comment]
@iinozemtsev can you take a look please?
