### ISSUE TITLE
INTEROP FAILURE: tests.build_docker_http2

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#25660]
https://source.cloud.google.com/results/invocations/91f15974-ea61-49c2-bda9-94cd9db41245/targets/github%2Fgrpc%2Finterop_docker_build/tests

```
go: cannot find main module, but found .git/config in /var/local/git/grpc
	to create a module there, run:
	cd ../.. && go mod init
```

**Comment by jtattermusch** [comment]
Fixed by https://github.com/grpc/grpc/pull/25707
