### ISSUE TITLE
Failed to build gem native extension using bundler: No rule to make target .../src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o, needed by .../src/ruby/ext/grpc/libs/opt/libz.a

### ISSUE THREAD

**Issue by NielsKSchjoedt** [grpc/grpc#25669]
### What version of gRPC and what language are you using?
ruby 2.7.2: 1.37.0.dev

(gem: 'grpc', github: 'grpc/grpc')

### What operating system (Linux, Windows,...) and version?
OSx Bigsur 11.2.3 on M1 arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

xcode-select version 2384.

### What did you do?
Set: `bundle config force_ruby_platform true`
Add: `gem 'grpc', '1.37.0.dev', github: 'grpc/grpc'` to Gemfile
Then: `bundle install` 

### What did you expect to see?
Successful bundle installing the gem with native extensions following: https://github.com/grpc/grpc/pull/25419

### What did you see instead?

```
Using grpc 1.37.0.dev from https://github.com/grpc/grpc.git (at master@a41a206)
/Users/niels-kristian/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:167: warning: conflicting chdir during another chdir block
/Users/niels-kristian/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:175: warning: conflicting chdir during another chdir block
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/niels-kristian/.rvm/gems/ruby-2.7.2@activemodel-datastore/bundler/gems/grpc-a41a206b8cc2/src/ruby/ext/grpc
/Users/niels-kristian/.rvm/rubies/ruby-2.7.2/bin/ruby -I /Users/niels-kristian/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0 -r ./siteconf20210310-56289-y99799.rb extconf.rb
Building internal gRPC into /Users/niels-kristian/.rvm/gems/ruby-2.7.2@activemodel-datastore/bundler/gems/grpc-a41a206b8cc2/src/ruby/ext/grpc/libs/opt
make: *** No rule to make target `/Users/niels-kristian/.rvm/gems/ruby-2.7.2@activemodel-datastore/bundler/gems/grpc-a41a206b8cc2/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o', needed by
`/Users/niels-kristian/.rvm/gems/ruby-2.7.2@activemodel-datastore/bundler/gems/grpc-a41a206b8cc2/src/ruby/ext/grpc/libs/opt/libz.a'.  Stop.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/niels-kristian/.rvm/rubies/ruby-2.7.2/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /Users/niels-kristian/.rvm/gems/ruby-2.7.2@activemodel-datastore/bundler/gems/grpc-a41a206b8cc2 for inspection.
Results logged to /Users/niels-kristian/.rvm/gems/ruby-2.7.2@activemodel-datastore/bundler/gems/extensions/arm64-darwin-20/2.7.0/grpc-a41a206b8cc2/gem_make.out

An error occurred while installing grpc (1.37.0.dev), and Bundler cannot continue.

In Gemfile:
  activemodel-datastore was resolved to 0.5.0, which depends on
    google-cloud-datastore was resolved to 2.1.0, which depends on
      google-cloud-datastore-v1 was resolved to 0.2.0, which depends on
        gapic-common was resolved to 0.4.0, which depends on
          googleapis-common-protos was resolved to 1.3.11, which depends on
            grpc
```

**Comment by drfloob** [comment]
Thanks for the repro instructions, that's helpful! I'm not terribly familiar with our Ruby install, @apolcyn can you take a look at this one?

**Comment by apolcyn** [comment]
My guess is the zlib git submodule (and probably also all other git submodules of grpc/grpc), weren't cloned while cloning https://github.com/grpc/grpc.git.

This would mean that `third_party/zlib` and other submodule directories wouldn't existing under the cloned grpc repo - that could cause something like this.

**Comment by NielsKSchjoedt** [comment]
@apolcyn hmm, then question is, will that get resolved when you release the gem next time or is it going to be the same thing? Apparently adding the installing the gem from the GitHub master using bundler is not supported...

**Comment by apolcyn** [comment]
The published packages include all necessary source files, so it's not an issue there.

For pulling directly from github, you might need something like `:submodules => true`

**Comment by NielsKSchjoedt** [comment]
@apolcyn 🎉 the `submodules: true` on the gem definition (`gem 'grpc', github: 'grpc/grpc', submodules: true`) did the trick! Now finally it works! I was not aware of that functionality with bundler 🤯. Thanks again! I think you can close issue. Maybe add a comment in the README on checking out edge from Github.

**Comment by bbuchalter** [comment]
After pulling submodules, this was no longer an issue for me.

**Comment by apolcyn** [comment]
Thanks for confirming -- to summarize, the solution here is to make sure that submodules are pulled down along with the grpc repo, when fetching sources from github
