### ISSUE TITLE
Implement reflection for Node

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2568]

**Comment by Lange** [comment]
Is there a status update on this? I'm a novice gRPC user and I'm having difficulty figuring out where reflection is or isn't supported. Thanks!

**Comment by stefanobaghino** [comment]
I'm sorry to re-iterate the message above, but I hope it's not too rude after one year and a half: is there any update on this?

**Comment by nicolasnoble** [comment]
We've moved the repository to grpc-node in the meantime. It'd be more relevant to follow there instead: https://github.com/grpc/grpc-node/issues/79

Unfortunately, the current status is still that this is still not on our radar.

I'm going to close'n'lock this one to redirect people to the other one.
