### ISSUE TITLE
Custom status return with ServerContext TryCancel

### ISSUE THREAD

**Issue by davisduong** [grpc/grpc#25686]
I am currently using TryCancel to stop a reader thread I have on a grpc server but it returns a default status (GRPC_STATUS_CANCELLED, "Cancelled on the server side"). 

Is there anyway to send a custom status to the client?

Im doing this in C++

**Comment by drfloob** [comment]
Hi @davisduong. The "new issue" form clearly asks users not to post questions as github issues. This falls under the category of "general questions". Next time please follow the instructions and use the channels mentioned below to ask questions. The issue template states:

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
>
