### ISSUE TITLE
Flakey builds due to unmirrored envoy_api dep

### ISSUE THREAD

**Issue by GMNGeoffrey** [grpc/grpc#25709]
My project https://github.com/google/iree/ has an integration with TensorFlow and therefore must build parts of TF as part of that integration. As part of our build that does so, we've recently been noticing flakiness fetching the `envoy_api` http_archive. Now setting aside the fact that it's absolutely terrifying to me that our compiler somehow depends on whatever envoyproxy/data-plane-api is, I think the  proximate cause here is that this dependency only has a source fetching from GitHub, which is not really set up to have the reliability for fetching http_archives like this. Could you please add a mirror as you have for other archives?

https://github.com/grpc/grpc/blob/b516dbfa21c5a2065f8a99a5890316d7da75d238/bazel/grpc_deps.bzl#L311-L319

Here's an example of our build failing:
https://source.cloud.google.com/results/invocations/5fc459b2-6d39-4125-9b48-4932f23957c0

**Comment by drfloob** [comment]
Thanks for pointing this out! This should be fixed with #25710

**Comment by GMNGeoffrey** [comment]
Awesome, thanks!
