### ISSUE TITLE
Client takes two minutes to connect to local host when target is System.Net.Dns.GetHostName()

### ISSUE THREAD

**Issue by andrekoehler** [grpc/grpc#25703]
### What version of gRPC and what language are you using?
v2.36.1 C#

### What operating system (Linux, Windows,...) and version?
Microsoft Windows [Version 10.0.19042.844]

### What runtime / compiler are you using (e.g. python version or version of gcc)
Tested with .NET Core 2.1, .NET Core 3.1 and .NET 5.0

### What did you do?
Download example from https://github.com/grpc/grpc/tree/master/examples/csharp/Helloworld. Update NuGet packages to 2.36.1.
Run server, run client, both on same computer. -> Client connects to server instantly.

Replace `ServerPort("localhost"` with `ServerPort("0.0.0.0"` and `Channel("127.0.0.1:30051"` with `Channel(System.Net.Dns.GetHostName() + ":30051"`.
Run server, run client, both on same computer. -> Client needs 120 seconds to connect to server.

Sample project: [Helloworld.zip](https://github.com/grpc/grpc/files/6129905/Helloworld.zip)

### What did you expect to see?
Client connects to server instantly.

### What did you see instead?
Client needs 120 seconds to connect to server.

### More tests:
This issue occurs on 2 out of 3 of my computers. All of them run Windows 10 v20H2. The computers with the issue have Windows 10 Pro, the laptop where it works has Windows 10 Home.

nslookup output:
[GOOD]
nslookup DESKTOP-I9D1JPS.fritz.box
Server: fritz.box
Address: fd00::3631:c4ff:fee7:7bbd

Name: DESKTOP-I9D1JPS.fritz.box
Addresses: 2003:c5:f29:4700:94e3:6a2a:eb2:9523
2003:c5:f29:4700:d174:eeab:ffee:b982
2003:c5:f29:4700:c6f:179:86ac:8f0e
2003:c5:f29:4700:a17c:bac3:add7:7bf3
192.168.178.23

[BAD 1]
nslookup HTPC
Server: fritz.box
Address: fd00::3631:c4ff:fee7:7bbd

DNS request timed out.
timeout was 2 seconds.
Name: HTPC.fritz.box
Address: 192.168.178.46

[BAD 2]
nslookup Ryzen3950X
Server: fritz.box
Address: fd00::3631:c4ff:fee7:7bbd

DNS request timed out.
timeout was 2 seconds.
Name: Ryzen3950X
Address: 192.168.178.33

If I execute the C# code `System.Net.Dns.GetHostEntry()` on the machine with the "DNS request timed out" issue, I instantly get a response that contains 6 IP addresses and all of them work just fine when I use them manually as a Grpc.Core.Channel target.

**Comment by andrekoehler** [comment]
This issue occurs on 2 out of 3 of my computers. All of them run Windows 10 v20H2. The computers with the issue have Windows 10 Pro, the laptop where it works has Windows 10 Home.

**Comment by andrekoehler** [comment]
This seems to be a DNS timeout. gRPC seems to use a default timeout of 120 seconds: https://github.com/grpc/grpc/blob/d2df99a53da0fd17a75f3ff67ad2ff0f20641dbb/include/grpc/impl/codegen/grpc_types.h#L406-L412

If I change the "grpc.dns_ares_query_timeout" channel option to 2000 (milliseconds), the client only needs two seconds to connect:

```
ChannelOption[] channelOptions = new ChannelOption[]
{
    new ChannelOption("grpc.dns_ares_query_timeout", 2000),
};
Channel channel = new Channel(System.Net.Dns.GetHostName() + ":30051", ChannelCredentials.Insecure, channelOptions);
```

**Comment by andrekoehler** [comment]
Here is the full log created with a debug build of gRPC: 
[log.txt](https://github.com/grpc/grpc/files/6131581/log.txt)

**Comment by drfloob** [comment]
Sounds like you found the culprit: nslookup shows you have DNS resolution problems on your network irrespective of gRPC, and gRPC's DNS resolution timeout matches the delay you're seeing. Offhand, I wonder if using the machine's IP address instead of hostname would help your situation. Regardless, this doesn't look like a gRPC bug, and we do try to maintain this space as a place to report bugs and feature requests, so I'll close this. Feel free to pick up the conversation on stackoverflow (possibly serverfault), or the gRPC mailing list.

**Comment by andrekoehler** [comment]
More testing: I changed by DNS servers from my router's DNS server to Google Public DNS servers (8.8.8.8). Now I get a proper "DNS resolution failed for service: Ryzen3950X:30051" for all my computers. So it seems like gRPC is simply not able to resolve Windows host names without a DNS server even though Windows can do it automatically.
