### ISSUE TITLE
how could I use auth policy in istio gateway or traefik, I want to use grpc http2 for the ios app

### ISSUE THREAD

**Issue by emisty** [grpc/grpc#25715]
when my ios app request the grpc server, and my app user needs to auth their identity first, so I use jwt auth for my server. but in my inner network, （like service mesh）request doesn't want jwt auth. http2 is high-efficiency but grpc seems don't friendly to auth in a service mesh

**Comment by emisty** [comment]
when my ios app request the grpc server,  and my app user needs to auth their identity first, so I use jwt auth for my server. but in my inner network, （like service mesh）request doesn't want jwt auth. http2 is high-efficiency but grpc seems don't  friendly to auth in a service mesh

**Comment by drfloob** [comment]
Hi @emisty. The "new issue" form asks users not to post questions as Github issues. Please follow the instructions and use the channels mentioned below to ask questions. For reference, here is the default message that appears when you create a new issue:

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
