### ISSUE TITLE
undefined symbol: __atomic_exchange_8 on Raspberry Pi

### ISSUE THREAD

**Issue by githubkusi** [grpc/grpc#25720]
### What version of gRPC and what language are you using?
1.36.1

### What operating system (Linux, Windows,...) and version?
Raspian Bullseye on Raspberry Pi 4

### What runtime / compiler are you using (e.g. python version or version of gcc)

    $ gcc --version
    gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110  

    $ python --version
    Python 3.9.1+

    $ cython --version
    Cython version 0.29.22

    $ pip list
    Package       Version
    ------------- -------
    coverage      5.5
    Cython        0.29.22
    grpcio        1.36.1
    pip           20.3.4
    pkg-resources 0.0.0
    protobuf      3.15.6
    setuptools    44.1.1
    six           1.15.0
    wheel         0.36.2

### What did you do?
First I installed grpc via pip install. Both global and in a venv. Then I did the installation from source as described [here](https://github.com/grpc/grpc/tree/master/src/python/grpcio) (also in a venv). Importing grpc gives the following error

    Python 3.9.1+ (default, Feb  8 2021, 22:09:01) 
    [GCC 10.2.1 20210110] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import grpc
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pi/develop/speech-to-text/venv_gprc2/lib/python3.9/site-packages/grpc/__init__.py", line 23, in <module>
        from grpc._cython import cygrpc as _cygrpc
    ImportError: /home/pi/develop/speech-to-text/venv_gprc2/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm- 
    linux-gnueabihf.so: undefined symbol: __atomic_exchange_8

### What did you expect to see?
In Python, `import grpc`  should work

### What did you see instead?
undefined symbol: __atomic_exchange_8

Furthermore 

    ldd cygrpc.cpython-39-arm-linux-gnueabihf.so

didn't show any traces of libatomic

### Anything else we should know about your project / environment?
There are many reported issues with regards to atomic. A notable one in Ruby #24249 claims to have it fixed for python. Fix merged in #20414 But this fix doesn't seem to work for me anymore in Bullseye

Please note that this worked out without issues on Raspian Buster. The issue appeared on Bullseye only

**Comment by githubkusi** [comment]
As an ugly workaround, the setup.py can be forced to always include libatomic (worked for my case, but is not a solution of course)


    diff --git a/setup.py b/setup.py
    index edbafe7654..fa6b937904 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -169,6 +169,7 @@ ENABLE_DOCUMENTATION_BUILD = os.environ.get(
 
 
    def check_linker_need_libatomic():
    +    return True
         """Test if linker on system needs libatomic."""
         code_test = (b'#include <atomic>\n' +
                      b'int main() { return std::atomic<int64_t>{}; }')
    diff --git a/tools/distrib/python/grpcio_tools/setup.py b/tools/distrib/python/grpcio_tools/setup.py
    index a316038d05..75c1e2c413 100644
    --- a/tools/distrib/python/grpcio_tools/setup.py
    +++ b/tools/distrib/python/grpcio_tools/setup.py
    @@ -73,6 +73,7 @@ BUILD_WITH_CYTHON = os.environ.get('GRPC_PYTHON_BUILD_WITH_CYTHON', False)
 
    def check_linker_need_libatomic():
    +    return True

**Comment by Alberto97** [comment]
Another quick and dirty way of fixing this for those that do not want to rebuild everything from source would be to cd into the grpc installation path (for me that was ```~/.local/lib/python3.9/site-packages/grpc/_cython```), cd into ```_cython```, make a backup of cygrpc.cpython-39-arm-linux-gnueabihf.so and run the following command:
```
$ patchelf cygrpc.cpython-39-arm-linux-gnueabihf.so --add-needed /lib/arm-linux-gnueabihf/libatomic.so.1
```
That will add a link to libatomic and grpc will not crash anymore:
```
pi@raspberrypi:~/.local/lib/python3.9/site-packages/grpc/_cython $ ldd cygrpc.cpython-39-arm-linux-gnueabihf.so
	linux-vdso.so.1 (0xbef46000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0xb693a000)
	/lib/arm-linux-gnueabihf/libatomic.so.1 (0xb6921000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb68e2000)
	libstdc++.so.6 => /lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb675a000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb66eb000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6597000)
	/lib/ld-linux-armhf.so.3 (0xb6f1d000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb656a000)
```
Hopefully my pull request (or any other fix) will get merged and we won't need this hackery anymore
