### ISSUE TITLE
PHP client环境无法通过？

### ISSUE THREAD

**Issue by srunze** [grpc/grpc#25725]
需要使用PHP client
按照步骤安装依赖
$ git clone https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ make grpc_php_plugin //出错提示 make: *** No rule to make target 'grpc_php_plugin'.  Stop.
grpc包里没有bins/opt目录没有看到相关plugins，这个make grpc_php_plugin的作用是什么呢？ 

或者
$ make
$ make install //出错提示 Installing via 'make' is no longer supported. Use cmake or bazel instead.

**Comment by stanley-cheung** [comment]
Duplicate of https://github.com/grpc/grpc/issues/25350#issuecomment-773688947

**Comment by srunze** [comment]
此时最新版本为1.37.x，使用低版本1.34.x（其他版本没有尝试）可以正常编译成功。
