### ISSUE TITLE
[C#] suggest populating `.InnerException` on `RpcException`

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#25740]
Currently, underlying exceptions behind `RpcException` are exposed in a non-idiomatic way, via the optional `.Status.DebugException`. This is very unusual, and means:

- no standard logging etc tooling will know to look for it
- most developers won't find it

Proposal: automatically populate `.InnerException` (the optional, expected API), when possible. This should be as simple as:

``` c#
- public RpcException(Status status, Metadata trailers, string message) : base(message)
+ public RpcException(Status status, Metadata trailers, string message) : base(message, status.DebugException)
```

(I'm happy to submit a PR)

**Comment by mgravell** [comment]
@jtattermusch this come up again here: https://github.com/protobuf-net/protobuf-net.Grpc/issues/196 - would a PR be considered here?

**Comment by jtattermusch** [comment]
I think this is something we can consider.

My main concern is that we must make it clear that RpcException.InnerException is only a mechanism to help with debugging, and the authoritative info about the RPC results is always the `Status` (along with the StatusCode). The InnerException can never traverse from the remote peer (as gRPC protocol has no way of serializing the exception objects and it also wouldn't be safe to do so). So InnerException is only useful when there is a "local" problem (e.g. cannot create a connection, failed to serialize/deserialize locally etc.).

I'd also like @JamesNK  to asses the impact of having RpcException.InnerException carry debug info sometimes from the grpc-dotnet perspective (I know grpc-dotnet makes use of `Status.DebugException` currently)

We'd need to implement this in a backward-compatible way, but that seems doable.

**Comment by jtattermusch** [comment]
Fixed by https://github.com/grpc/grpc-dotnet/pull/1992, the fix will be in the next release of Grpc.Core.Api (the upcoming 2.52.x). The fix will work both for grpc-dotnet and Grpc.Core, but for Grpc.Core, you need to explicitly use Grpc.Core.Api 2.52+ (once it's released).

**Comment by jtattermusch** [comment]
We can potentially backport the change into 2.46.x as well, but for now there seems to be no reason to do so since Grpc.Core 2.46.x  will work just fine with more recent versions of Grpc.Core.Api.
