### ISSUE TITLE
gRPCTargets.cmake  and gRPCTargets-noconfig.cmake files are missing when intalling grpc using CMake FetchContent in Linux

### ISSUE THREAD

**Issue by hungptit** [grpc/grpc#25752]
### What version of gRPC and what language are you using?

The mater branch of grpc.

### What operating system (Linux, Windows,...) and version?

Linux CentOS 7 kernel 3.10.0-1127.19.1.el7.x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)

clang (clang version 13.0.0 (https://github.com/llvm/llvm-project.git 14da287e18846ea86e45b421dc47f78ecc5aa7cb))

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Below is the CMake script that I use to install gRPC library using the FetchContent feature 

```
cmake_minimum_required(VERSION 3.15)
project(build-grpc LANGUAGES CXX)

include(FetchContent)
FetchContent_Declare(
  grpc
  GIT_REPOSITORY https://github.com/grpc/grpc
  GIT_TAG master)
set(FETCHCONTENT_QUIET OFF)
set(ABSL_ENABLE_INSTALL OFF)
set(gRPC_PROTOBUF_PACKAGE_TYPE module)
set(gRPC_PROTOBUF_PROVIDER module)
FetchContent_MakeAvailable(grpc)
```

### What did you expect to see?

I expect to see 4 cmake files i.e gRPCConfig.cmake,  gRPCConfigVersion.cmake,  gRPCTargets.cmake, and  gRPCTargets-noconfig.cmake.

### What did you see instead?

I only see 2 cmake files gRPCConfig.cmake  and gRPCConfigVersion.cmake and my project is failed to build because it could not find gRPCTargets.cmake. Below is the error message 

```
CMake Error at 3p/lib/cmake/grpc/gRPCConfig.cmake:13 (include):
  include could not find requested file:

    /home/tsi/hdang/working/grpc-cmake-template/3p/lib/cmake/grpc/gRPCTargets.cmake
Call Stack (most recent call first):
  proto/CMakeLists.txt:14 (find_package)


CMake Error at proto/CMakeLists.txt:26 (get_target_property):
  get_target_property() called with non-existent target "grpc_cpp_plugin".


CMake Error at proto/CMakeLists.txt:33 (get_target_property):
  get_target_property() called with non-existent target
  "grpc::grpc_python_plugin".
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

I have a standard environment with CMake 3.20 and clang++-13.0.0

**Comment by hungptit** [comment]
I also see the same issue in macOS and Windows 

**Windows**

```
PS D:\p4\grpc-cmake-template\3p> ls .\lib\cmake\grpc\


    Directory: D:\p4\grpc-cmake-template\3p\lib\cmake\grpc


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/17/2021   2:43 PM                modules
-a----        3/17/2021   2:33 PM            181 gRPCConfig.cmake
-a----        3/17/2021   2:33 PM           2030 gRPCConfigVersion.cmake
```

**macOS**
ls lib/cmake/grpc/
gRPCConfig.cmake        gRPCConfigVersion.cmake modules
```

Below is the build script for Windows 
```
param (
    [Parameter(Mandatory=$true)][ValidateSet('Release', 'Debug')]$config
)

& 'C:\Program Files\CMake\bin\cmake.exe' -G "Visual Studio 14 2015" -A x64 $grpc_path -DCMAKE_INSTALL_PREFIX="$PWD"
& 'C:\Program Files\CMake\bin\cmake.exe' --build . --config $config -- /maxcpucount
& 'C:\Program Files\CMake\bin\cmake.exe' --build . --config $config --target install
```

```

**Comment by hungptit** [comment]
This is by design (from reading the CMakeLists.txt). I will close this issue.

**Comment by danielwangksu** [comment]
Sorry may I ask if this is by design how do we use cmake to to find grpc package. For my gPRCConfig.cmake it is still including gRPCTargets.cmake file, which is missing.
