### ISSUE TITLE
grpc_csharp_ext.x64.dll crash when another 3rd party dll is being used

### ISSUE THREAD

**Issue by noamyogev84** [grpc/grpc#25766]
### What version of gRPC and what language are you using?
Grpc.Core 2.36.1, C#

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
.net core 3.0 console app - self contained  -  x64

### What did you do?
My application has a gRPC server and some services. 
Whenever a method on another 3rd party dll (native-x64) is called, My application crash and the error apperntly comes from gRPC.

![image](https://user-images.githubusercontent.com/7726629/111749541-9c169980-889a-11eb-8b30-1adf7f05326c.png)

### What did you expect to see?
Don't crash

### What did you see instead?
Application crash
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
Can you please provide a minimal reproduction, ideally in a form of a github repository with ready-to-run code? Without it's very hard to say what you've done since you don't provide any detail about the other native library and what code you ran.
