### ISSUE TITLE
RAW is a saved word 

### ISSUE THREAD

**Issue by aradyaron** [grpc/grpc#25775]
### What version of gRPC and what language are you using?
c++

### What operating system (Linux, Windows,...) and version?
AIX

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5

### What did you do?
#include <sys/ioctl>

### What did you expect to see?
compileing successully

### What did you see instead?
failed to compile due to RAW being a saved word, which fails the enum ApiType.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
The issue description is not clear. I simply tried including that header in our tests and it worked. Please re-raise the issue with clear instructions to reproduce.
