### ISSUE TITLE
gRPC CSharp Extension Static library when building using CMake on iOS

### ISSUE THREAD

**Issue by julianxhokaxhiu** [grpc/grpc#25774]
### Is your feature request related to a problem? Please describe.
I'm trying to build the iOS gRPC Cpp library and I found out that only on iOS there's no way to obtain a static library, it always ends up being built as a dynamic one ( .dylib ). Can you please allow that library to be built statically too?

### Describe the solution you'd like
Ideally removing the `SHARED` keywork on this line https://github.com/grpc/grpc/blob/master/CMakeLists.txt#L2084 should be enough. This should allow who builts the lib to decide if the dynamic one or the static one is preferred. Also, it's aligned with all the other `add_library` declarations in the whole file.

### Describe alternatives you've considered
- Using your experimental script to build: https://github.com/grpc/grpc/blob/master/src/csharp/experimental/build_native_ext_for_ios.sh
- Patching manually the line before building ( removing the SHARED keyword )

**Comment by julianxhokaxhiu** [comment]
Apparently, removing `SHARED` from that line, breaks the build of the Android one though as it produces an `.a` file instead of a `.so` one. So I suppose a flag is required, or an update to the whole unity packaging to make use of the `.dylib` one, is required as well.

**Comment by jtattermusch** [comment]
> ... or an update to the whole unity packaging to make use of the `.dylib` one, is required as well.

FYI, on iOS, everything is linked statically so there is (and never will be) a way to use a .dylib there. You need a static library on iOS and dynamic one android.

**Comment by julianxhokaxhiu** [comment]
> Why isn't https://github.com/grpc/grpc/blob/master/src/csharp/experimental/build_native_ext_for_ios.sh sufficient for you?

I ended up using that script in the end, but having a CMake build would be much more robust in terms of pipeline integration, especially if you target multiple platforms. Funny fact: the very same script for Android uses CMake already, so why not unifying this also for iOS?

> FYI, on iOS, everything is linked statically so there is no way (and never will be) to use a .dylib there. You need a static library on iOS and dynamic one android.

Indeed that's true, but a way through CMake must be implemented ( via a flag or autodetection ) in the CMakeLists project file, in order to accomplish that.

I'd be happy to open a PR for that, but I thought about approaching you first to know if this was something you had already in the pipeline or not. Let me know.

Thank you in advance :)

**Comment by jtattermusch** [comment]
> > Why isn't https://github.com/grpc/grpc/blob/master/src/csharp/experimental/build_native_ext_for_ios.sh sufficient for you?
> 
> I ended up using that script in the end, but having a CMake build would be much more robust in terms of pipeline integration, especially if you target multiple platforms. Funny fact: the very same script for Android uses CMake already, so why not unifying this also for iOS?
> 
> > FYI, on iOS, everything is linked statically so there is no way (and never will be) to use a .dylib there. You need a static library on iOS and dynamic one android.
> 
> Indeed that's true, but a way through CMake must be implemented ( via a flag or autodetection ) in the CMakeLists project file, in order to accomplish that.
> 
> I'd be happy to open a PR for that, but I thought about approaching you first to know if this was something you had already in the pipeline or not. Let me know.

How would the cmake flag approach look like?
Also, can you share a cmake command that's analogous to https://github.com/grpc/grpc/blob/master/src/csharp/experimental/build_native_ext_for_ios.sh?
Note that this is something that would need to work on our CI as well (since we do build the artifacts for the Grpc.Core.Xamarin nuget).

> 
> Thank you in advance :)

**Comment by julianxhokaxhiu** [comment]
I'll get back to you ASAP and share the CMake command I was trying to use!

**Comment by julianxhokaxhiu** [comment]
Sorry for the long delay, here is the set of commands I was using, including CMake:

```sh
$ sed -i "" "s/add_library(grpc_csharp_ext SHARED/add_library(grpc_csharp_ext/g" CMakeLists.txt # Temporary until https://github.com/grpc/grpc/issues/25774 is fixed
$ _CMAKE_OSX_ARCHITECTURES="armv7"
$ cmake \
  -S . \
  -B ".dist-$_CMAKE_OSX_ARCHITECTURES" \
  -DCMAKE_SYSTEM_NAME=iOS \
  -DCMAKE_OSX_ARCHITECTURES=$_CMAKE_OSX_ARCHITECTURES \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=9.0 \
  -DCMAKE_BUILD_TYPE=MinSizeRel \
  -DCARES_INSTALL=OFF \
  -Dprotobuf_BUILD_PROTOC_BINARIES=OFF \
  -DgRPC_BUILD_CODEGEN=OFF \
  -DgRPC_BUILD_TESTS=OFF \
  -DgRPC_USE_PROTO_LITE=ON
$ cmake --build ".dist-$_CMAKE_OSX_ARCHITECTURES" --config MinSizeRel
$ _CMAKE_OSX_ARCHITECTURES="arm64"
$ # Repeat the two cmake commands
$ mkdir .dist
$ lipo -create -output .dist/libgrpc.a .dist-armv7/libgrpc.a .dist-arm64/libgrpc.a
$ lipo -create -output .dist/libgrpc_csharp_ext.a .dist-armv7/libgrpc_csharp_ext.a .dist-arm64/libgrpc_csharp_ext.a
```

This creates actually a valid library, but for some reason it doesn't include some symbols and it fails the linkage on projects using this library.

Any help on this direction is appreciated.

**Comment by julianxhokaxhiu** [comment]
I'd be still interested in this.

**Comment by jtattermusch** [comment]
Since https://github.com/grpc/grpc/blob/master/src/csharp/experimental/build_native_ext_for_ios.sh is already available and seems to work, using CMake for the iOS artifacts build is really just a nice-to-have.
Also, since Grpc.Core will be deprecated next year (see https://grpc.io/blog/grpc-csharp-future/), there's probably no point in working on this feature now.
