### ISSUE TITLE
Mechanism to limit build parallelism on gem installation.

### ISSUE THREAD

**Issue by MrJoy** [grpc/grpc#25787]
### Is your feature request related to a problem? Please describe.

When I attempt to do a `bundle install` of my project (which depends on the `grpc` Ruby gem) on CircleCI, The `extconf.rb` detects that the machine it's running on has 36 cores (despite my resource class being limited to 4 vCPUs, no less) and attempts to build the native extension with a parallelism of 72.  This exceeds the 8GB memory ceiling for the resource class.

### Describe the solution you'd like

A means by which I can tell the installation process to limit the build parallelism to something smaller.  Perhaps an environment variable I could pass in?  Whatever the mechanism, it would be ideal if it plays nice with Bundler of course.

### Describe alternatives you've considered

~~I may be able to live with a larger (and thus more expensive) resource class on my CI server, but that would make the `bundle install` step considerably more expensive.~~

Anything larger than the `large` resource class requires approval from a CSM at CircleCI, and we don't want to be on their radar for Enterprise Sales at this time.  In the meantime I've forked this repo, and changed the relevant line of extconf.rb to cap things.  Not an ideal solution, of course.

### Additional context

N/A

**Comment by MrJoy** [comment]
Hrm.  A quick test suggests env vars don't get passed through, so I'm not sure what the mechanism could be to parameterize this.  I'd offer other ideas, but I'm not terribly familiar with native extensions in Ruby, nor with the inner mechanics of Bundler.

**Comment by takamario** [comment]
I'm not sure it's the same issue, but I got sudden `KILL` signal (like OOM killer) when `bundle install` on CircleCI.

`bundle install` log:
```
...(snip)...
Installing grpc 1.36.0 with native extensions

Received "killed" signal
```

I solved by upgrading CircleCI's `resource_class` (medium => large) as a workaround.

**Comment by MrJoy** [comment]
If the exit code of the `bundle install` command is 137, then yes it's the same issue.  I've found that with a resource class of `large` the problem _was_ happening intermittently -- but with recent changes "intermittent" has become "basically every time".  That's capping bundle jobs at 2 (defaults to # of processors, so that should be 36 in this case -- since that's what the sysctl call is returning, even if the Docker container that Circle runs our jobs in is capped to 4 vCPUs), and using 2 malloc arenas to mitigate any Ruby-side memory bloat with glibc malloc.

**Comment by splittingred** [comment]
I've also encountered this - the `grpc` gem is essentially un-installable via bundler in CircleCI or smaller images at present. I believe this is something with the cross-platform support, as:

```
bundle lock --add-platform x86_64-linux
```

_before_ running `bundle install` solves the problem. This makes me wonder if this is related to cross-platform compilation support in grpc in the bundled artifacts.

**Comment by MrJoy** [comment]
Ahhh, there are pre-compiled binaries available.  Of course.  That makes total sense and I feel foolish that it didn't click with me that the problem is that _the pre-built binaries weren't being used_.  D'oh.  Perhaps some documentation could be added to suggest doing this `bundle lock` step for deployments for future users for whom this isn't obvious.
