### ISSUE TITLE
API not supported in UWP app.

### ISSUE THREAD

**Issue by HppZ** [grpc/grpc#25789]
API WSACleanup in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API WSAGetLastError in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API WSASetLastError in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API WSAStartup in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API bind in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API closesocket in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API connect in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API getpeername in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API getsockname in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API htonl in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API htons in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API listen in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API ntohl in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API ntohs in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API setsockopt in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API socket in wsock32.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API SymFromAddr in dbghelp.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API SymInitialize in dbghelp.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.
API SymSetOptions in dbghelp.dll is not supported for this application type. grpc_csharp_ext.x64.dll calls this API.

**Comment by drfloob** [comment]
gRPC C# has been deprecated. Please see https://grpc.io/blog/grpc-csharp-future/
