### ISSUE TITLE
UNAUTHENTICATED errors against Cloud Spanner emulator in v1.36

### ISSUE THREAD

**Issue by larkee** [grpc/grpc#25810]
Details copied from https://github.com/googleapis/google-cloud-php/issues/3911

### What version of gRPC and what language are you using?
grpc v1.36
PHP

### What operating system (Linux, Windows,...) and version?
OS: Debian

### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP version: 7.4

### What did you do?

Steps to reproduce:
https://github.com/taka-oyama/grpc-bug-test

### What did you expect to see?
No errors.

### What did you see instead?

```
Fatal error: Uncaught Google\Cloud\Core\Exception\ServiceException: {
    "message": "Established channel does not have a sufficient security level to transfer call credential.",
    "code": 16,
    "status": "UNAUTHENTICATED",
    "details": []
} in /app/vendor/google/cloud-core/src/GrpcRequestWrapper.php:257
Stack trace:
#0 /app/vendor/google/cloud-core/src/GrpcRequestWrapper.php(146): Google\Cloud\Core\GrpcRequestWrapper->convertToGoogleException(Object(Google\ApiCore\ApiException))
#1 /app/vendor/google/cloud-core/src/GrpcTrait.php(79): Google\Cloud\Core\GrpcRequestWrapper->send(Array, Array, Array)
#2 /app/vendor/google/cloud-spanner/src/Connection/Grpc.php(301): Google\Cloud\Spanner\Connection\Grpc->send(Array, Array)
#3 /app/vendor/google/cloud-spanner/src/Instance.php(264): Google\Cloud\Spanner\Connection\Grpc->getInstance(Array)
#4 /app/vendor/google/cloud-spanner/src/Instance.php(230): Google\Cloud\Spanner\Instance->reload(Array)
#5 /app/test.php(11): Google\Cloud\Spanner\Instance->exists()
#6 {main}
  thrown in /app/vendor/google/cloud-core/src/GrpcRequestWrapper.php on line 257
```

This only happens with grpc v1.36.
Grpc v1.35 does not have this issue.

### Anything else we should know about your project / environment?

This issue is also affecting the Cloud Spanner Github Action which runs the system tests against the emulator. See here for example of failures: 
https://github.com/googleapis/google-cloud-php/pull/3912/checks?check_run_id=2164043364

**Comment by skuruppu** [comment]
Friendly ping on this issue. We would like to raise the priority for this as it's affecting Spanner customers and the Spanner CI.

**Comment by stanley-cheung** [comment]
Looking into this.

**Comment by acoulton** [comment]
Just to confirm this is broader than just the spanner emulator : we have the same issue connecting to the (unofficial) cloud tasks emulator from php with grpc v1.36. 

Looks like it might be related to #25303?

**Comment by stanley-cheung** [comment]
Yea we are starting to look into a class of use case that we didn't exactly anticipate that it will be used that way. Basically it's a combination of using insecure channel and having a call credentials callback. We are looking into a short term fix and a long term fix to make sure these kind of use cases are properly covered.

**Comment by stanley-cheung** [comment]
This should be fixed with the latest point release of the `grpc` pecl extension at version `1.37.1`.

**Comment by acoulton** [comment]
@stanley-cheung thanks, confirm this is solved for us now (against cloud-tasks-emulator, not tested with spanner) on 1.37.1.

**Comment by stanley-cheung** [comment]
@acoulton Thanks for verifying. We have identified the underlying issue but will need some time to seek out a correct path going forward. The ideal path going forward will hopefully involve no code change on your side but we are not sure yet. We will be in touch again if we need to try to test our code change on your use case. Thanks!
