### ISSUE TITLE
AIO set_trailing_metadata not marked as async

### ISSUE THREAD

**Issue by ronf** [grpc/grpc#25813]
According to the documentation at https://grpc.github.io/grpc/python/_modules/grpc/aio/_base_server.html#ServicerContext.set_trailing_metadata, the AIO ServicerContext set_trailing_metadata() function should be defined as async. However, if I'm reading the source right, this is not the case:

https://github.com/grpc/grpc/blob/83b19b2efe5bc87b4dc85d981c087a336c60c9bd/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi#L197

When I try to "await" on this method right now, I get back:

```
TypeError: object NoneType can't be used in 'await' expression
```

The function works when I call it synchronously (without "await"). Given that send_initial_metadata() is async, though, set_trailing_metadata() should probably also be async as the documentation states. However, the implementation and docs appear to be out of sync at the moment.

**Comment by lidizheng** [comment]
Thanks for reporting this! This is an oversight of me. The fix is on the way: https://github.com/grpc/grpc/pull/25814.

**Comment by lidizheng** [comment]
(Also, if possible, please consider using one of our issue templates https://github.com/grpc/grpc/issues/new/choose for new bug/issue/stuff.)

**Comment by ronf** [comment]
Thanks! Sorry for not using the template -- I used the option from the source code line I linked to create the issue, so it ended up skipping the templates.
