### ISSUE TITLE
PHP MacOS Distribtests Timing Out

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#25818]
The last two MacOS distribtest runs have failed due to a timeout in the PHP job:

 - https://source.cloud.google.com/results/invocations/1d058c58-6dd1-4c10-a11e-8132c8d26262
 - https://source.cloud.google.com/results/invocations/02487e6f-fe4f-47d4-8af2-00f4ea3d36d4

Based on the logs, this is not due to a sudden major increase, but a gradual one. The most recent failing job timed out after 905.7 seconds. The most recent passing job took 808.5 seconds.

The PHP build takes by far the longest of any of the distribtests builds. The second longest (C#) takes around 32 seconds.

@stanley-cheung The simplest solution is probably just bumping the timeout, but is there anything we can do to decrease the time taken by the distribtest?

**Comment by stanley-cheung** [comment]
Part of this is also the increasing size / number of files we need to compile in c-core. I wonder if there are some compilation flags that we can include by default that will, by default, not compile the entire c-core but only a subset?

**Comment by gnossen** [comment]
There may also be low-hanging fruit like parallelized compilation. I don't see the make invocation in the log, but it might be as simple as adding `-j`.
