### ISSUE TITLE
gRPC C++ client doesn't work without explicit server's SSL certificate

### ISSUE THREAD

**Issue by xheke** [grpc/grpc#25829]
### What version of gRPC and what language are you using?

CORE_VERSION = 14.0.0
CPP_VERSION = 1.35.0-dev
CSHARP_VERSION = 2.35.0-dev

commit 95ab12cf8fca2d92b4a097369dd8249cf8997b9f 

### What operating system (Linux, Windows,...) and version?
Linux
Linux version 3.10.0-957.21.2.el7.x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 10.2.0

### What did you do?
I follow the below link to write the client code, but it doesn't work.
[With server authentication SSL/TLS](https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls-2)

```
  auto channel_creds = grpc::SslCredentials(grpc::SslCredentialsOptions());
  lycliClient lyclier(grpc::CreateChannel("localhost:50051", channel_creds));
```

### What did you expect to see?

I hope to see the client connect to the server via SSL successfully.

### What did you see instead?

But it failed with below error message on the client side.
```
E0326 16:18:33.580381452    1763 ssl_transport_security.cc:1458] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0326 16:18:33.584376036    1763 ssl_transport_security.cc:1458] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

So i changed the client code as following:

```
  grpc::SslCredentialsOptions ssl_opts;
  ssl_opts.pem_root_certs  = get_file_contents("ly_server.crt");
  std::shared_ptr<grpc::ChannelCredentials> channel_creds = grpc::SslCredentials(ssl_opts);
  //auto channel_creds = grpc::SslCredentials(grpc::SslCredentialsOptions());
  lycliClient lyclier(grpc::CreateChannel("localhost:50051", channel_creds));
```

I see the client connect to the server successfully. but it doesn't match the requirement
[With server authentication SSL/TLS](https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls-2)

Related report can also refer below link:

[Why gRPC C++ client doesn't work without explicit server's SSL certificate, like in samples?](https://stackoverflow.com/questions/56223433/why-grpc-c-client-doesnt-work-without-explicit-servers-ssl-certificate-like/66847487#66847487)

**Comment by dev-jaegwan** [comment]
is there any solution for this?
I got same problem of this.

**Comment by RayKoopa** [comment]
I understand! Sadly I'm in the middle of something right now and new to gRPC, indeed only having an MSVC client project here and never written a test server for it (except for the C# one based on Grpc.Core). I'll see when I get to reproduce it in a small (CMake) sample.

**Comment by ZhenLian** [comment]
This is the expected behavior.
For anyone who runs into this failure and new to this topic(TLS, etc), in gRPC we have set a default path for loading your root certificates, and that path is different on various platforms(MacOS, Linux, etc). In normal situations it should just work automatically, but if you see similar issues, please find the actual locations of your root certs, and set it up in gRPC.
