### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by SagarHuli** [grpc/grpc#25842]
_Recently when I tried to run grpc server in a maven project, I'm getting this warning:_

WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by veblush** [comment]
It seems you're using gRPC Java. Please report it to https://github.com/grpc/grpc-java, instead?
