### ISSUE TITLE
gRPC cpp client : CreateCustomChannel hang forever

### ISSUE THREAD

**Issue by linuxpham** [grpc/grpc#25876]
### What version of gRPC and what language are you using?
Protobuf : version 3.15.6
gRPC : version 1.36.4
Cmake command when compile gRPC : cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCARES_SHARED:BOOL=ON -DgRPC_BUILD_TESTS:BOOL=OFF -DgRPC_CARES_PROVIDER:STRING=package -DgRPC_PROTOBUF_PROVIDER:STRING=package -DgRPC_RE2_PROVIDER:STRING=package -DgRPC_SSL_PROVIDER:STRING=package -DgRPC_ZLIB_PROVIDER:STRING=package -Dprotobuf_WITH_ZLIB:BOOL=ON -DgRPC_ABSL_PROVIDER:STRING=package -DBUILD_SHARED_LIBS:BOOL=ON  -DCMAKE_BUILD_TYPE:STRING=Release ../

### What operating system (Linux, Windows,...) and version?
Ubuntu 20 server

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc/g++

### What did you expect to see?
`D0402 15:41:15.496300422   31895 ev_posix.cc:173]            Using polling engine: epollex

D0402 15:41:15.496423476   31895 init_unsecure.cc:30]        Using insecure gRPC build. Security handshakers will not be invoked even if secure credentials are used.

D0402 15:41:15.496583361   31895 dns_resolver_ares.cc:491]   Using ares dns resolver

D0402 15:41:15.496624282   31895 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"

D0402 15:41:15.496631937   31895 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"

D0402 15:41:15.496635137   31895 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"

D0402 15:41:15.496638988   31895 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"

D0402 15:41:15.496641767   31895 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"

`

### What did you see instead?
`

                std::string pUriStr = "192.168.1.10:6667" ; // This is Port of gRPC server

               grpc::ChannelArguments args;

               grpc::CreateCustomChannel(pUriStr, grpc::InsecureChannelCredentials(), args); // Code hang forever HERE

`

**Comment by linuxpham** [comment]
gRPC server :

<img width="1406" alt="Screen Shot 2021-04-03 at 14 56 52" src="https://user-images.githubusercontent.com/154762/113472341-d6805900-948c-11eb-9ddc-76c4f2bd1cf3.png">

**Comment by linuxpham** [comment]
Hang at line 162 (grpc_tracer_init();) in init.cc file

**Comment by veblush** [comment]
@linuxpham Can you manage to get a callstack when it hang and give us a reproduction code?

**Comment by yashykt** [comment]
It's been more than 30 days since "disposition/requires reporter action" was added. Please feel to re-open/create a new issue if the issue persists.
