### ISSUE TITLE
On CMake allow FetchContent and find_package to work together

### ISSUE THREAD

**Issue by apmcasai** [grpc/grpc#25917]
### Is your feature request related to a problem? Please describe.
Yes, when adding grpc as a dependency to a project using FetchContent, if subsequent dependencies have grpc as a dependency and call `find_package()` an error happens:

CMake Error at src/CMakeLists.txt:27 (find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.

### Describe the solution you'd like
When using FetchContent and populate, find package should work on subsequent dependencies

### Additional context
Here is a way to reproduce the error:

cmake_minimum_required(VERSION 3.15)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
project(foobar)
include(FetchContent)
FetchContent_Declare(
        gRPC
        GIT_REPOSITORY https://github.com/grpc/grpc
        GIT_TAG        v1.36.4
)
set(FETCHCONTENT_QUIET OFF)
FetchContent_MakeAvailable(gRPC)

find_package(gRPC REQUIRED)

**Comment by veblush** [comment]
@jtattermusch We do have a test to build an example with fetch content against local repo but don't seem to have it with the git repo although we have some [code](https://github.com/grpc/grpc/blob/b941a771e2dc1398bacde9efccae2f7f4eaa40be/examples/cpp/cmake/common.cmake#L73) for it. Can you shed some light on this?

**Comment by jtattermusch** [comment]
we are running the test against local repo because it's just simpler and we want to test the exact revision that's being tested in the PR.  The GIT_REPOSITORY way is what users would normally use.
I think this comment https://github.com/grpc/grpc/blob/84b86fe7e815952d36078e296ab127d96ce7f4f0/test/distrib/cpp/run_distrib_test_cmake_fetchcontent.sh#L35 kind of explains it (it is supposed to override the GIT_REPOSITORY setting so that we can test easily).
