### ISSUE TITLE
Why are the Github Releases set to V1.## but the nuget packages report V2.###

### ISSUE THREAD

**Issue by Smurf-IV** [grpc/grpc#25929]
![image](https://user-images.githubusercontent.com/2418812/114027031-df976e80-986e-11eb-8309-46e803fec499.png)

And from inside Visual Studio:
![image](https://user-images.githubusercontent.com/2418812/114027111-f5a52f00-986e-11eb-8daa-4ff1c964fee2.png)

**Comment by jtattermusch** [comment]
This is C# specific thing. For C# we had to do a major version bump to accommodate the introduction of grpc-dotnet implementation and a new version of .NET Core. Everything is explained in https://github.com/jtattermusch/proposal/blob/master/L57-csharp-new-major-version.md.
