### ISSUE TITLE
Please support building with external libxxhash

### ISSUE THREAD

**Issue by musicinmybrain** [grpc/grpc#25945]
### Is your feature request related to a problem? Please describe.
As a Linux distribution packager, I need to build with system copies of third-party libraries whenever possible.

### Describe the solution you'd like
Add a CMake option to use an external copy of libxxhash, similar to `gRPC_ZLIB_PROVIDER` and friends. Use something like `pkg_search_module()` to find it.

### Describe alternatives you've considered
Manually patch `cmake/xxhash.cmake` to use `pkg_search_module()`; use that to set `_gRPC_XXHASH_INCLUDE_DIR` and a new `_gRPC_XXHASH_LIBRARIES`, and (to simplify the downstream patch) shove `${_gRPC_XXHASH_LIBRARIES}` into `_gRPC_ALLTARGETS_LIBRARIES` in CMakeLists.txt. This works. Upstream support would be better.

**Comment by nicolasnoble** [comment]
Feel free to submit a PR for this one? We used a header-only build with an actual code drop to avoid any of these issues on purpose however.

**Comment by musicinmybrain** [comment]
> Feel free to submit a PR for this one? We used a header-only build with an actual code drop to avoid any of these issues on purpose however.

Knowing that the library is not needed is helpful; I had missed the use of `XXHASH_INCLUDE_ALL`. That means I can unbundle downstream simply by removing `third_party/xxhash` and letting the system `xxhash.h` be found instead.

That’s good enough for me; I think it’s best not to attempt a PR that would add configuration to the process.
