### ISSUE TITLE
Can't build C++ route_guide example with the Makefile provided

### ISSUE THREAD

**Issue by FreeSpirit9009** [grpc/grpc#25952]
### What version of gRPC and what language are you using?
==> 1.35, C++

### What operating system (Linux, Windows,...) and version?
==> Ubuntu 20.10 in a VMWare 16 virtual machine

### What runtime / compiler are you using (e.g. python version or version of gcc)
==> gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
==> run "make" (without quotes) in grpc/examples/cpp/route_guide

### What did you expect to see?
==> make succeeds in building an executable

### What did you see instead?
==> a large number of linker errors (see attached make-20210409-01.log
[make-20210409-01.log](https://github.com/grpc/grpc/files/6296823/make-20210409-01.log)
[Makefile.txt](https://github.com/grpc/grpc/files/6296828/Makefile.txt)

)
==> first I had compiler errors, but I was able to fix these (see attached Makefile with my changes)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
==> on the same machine, I was able to build and run the C++ hello world example using CMake. But the route guide example doesn't have a CMake list file, so I tried the Makefile. Therefore I assume that the environment itself is fine.
==> pkg-config works:
xyz$ pkg-config --cflags --libs protobuf
-lpthread -I/home/georg/local/grpc/include -L/home/georg/local/grpc/lib -lprotobuf -lpthread

**Comment by karthikravis** [comment]
I think cmake is the suggested build system and make isn't supported anymore. Adding Esun to comment.

**Comment by veblush** [comment]
It's odd to see those linker errors although we're deprecating makefiles. There is a new [CMakeLists.txt]( https://github.com/grpc/grpc/blob/master/examples/cpp/route_guide/CMakeLists.txt) you can use. Can you try it?
