### ISSUE TITLE
c++ route_guide client on windows/vs2013 error: "Expression: map/set iterators incompatible"

### ISSUE THREAD

**Issue by larsonmpdx** [grpc/grpc#2595]
this is with code checked out today.  route_guide compiled and ran without this error about a month ago (sorry I can't be more specific)

debug breakpoint brings me to /src/cpp/common/call.cc:67

https://github.com/grpc/grpc/blob/master/src/cpp/common/call.cc#L67

line in question
  for (auto iter = metadata.cbegin(); iter != metadata.cend(); ++iter, ++i) {

doesn't make sense to me, it's an auto iterator...

**Comment by larsonmpdx** [comment]
I expanded auto to "std::multimap<grpc::string, grpc::string>::const_iterator" and there was no change

**Comment by yang-g** [comment]
Was the example build and run as is? The codepath seems not hit in the example.

**Comment by larsonmpdx** [comment]
yes.  I had to make a vs project for it with openssl, zlib, etc. includes, I can share that by email to make replicating this easier

options to set are:

additional include directories:

..\..\;C:\grpc\include;C:\grpc\third_party\protobuf\src

additional dependencies:

ssleay32.lib;libeay32.lib;zlib.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;gpr.lib;grpc.lib;grpc++.lib;libprotobuf.lib;ws2_32.lib;%(AdditionalDependencies)

additional library directories: (change if you are not using c:\grpc)

C:\grpc\vsprojects\Debug;C:\grpc\third_party\protobuf\vsprojects\Debug;C:\grpc\vsprojects\packages\grpc.dependencies.zlib.1.2.8.9\build\native\lib\$(PlatformToolset)\$(Platform)\$(Configuration)\static\cdecl;C:\grpc\vsprojects\packages\grpc.dependencies.openssl.1.0.2.2\build\native\lib\$(PlatformToolset)\$(Platform)\$(Configuration)\static

when it didn't work I also tried this pull request

https://github.com/grpc/grpc-common/pull/265

but I think that isn't necessary for vs2013 (more new c++ feature support)

**Comment by larsonmpdx** [comment]
still working on this.  with newest code from today and dynamic thread pool disabled (it's broken somehow), the metadata multimap is 12 million elements and the program takes 350MB when it crashes.  probably there is a problem further up the chain with creating the multimap (or it's uninitialized)

**Comment by larsonmpdx** [comment]
here's a call stack

![image](https://cloud.githubusercontent.com/assets/12436438/8938178/e540ab56-3511-11e5-80ae-a6263edf7af7.png)

in blocking_unary_call, context->send_initial_metadata_ has size 0.  as soon as it gets into SendInitialMetadata() its size is some large number, different each run, so probably corrupted

I can't discount a misconfiguration of my VS project as nobody has replicated this yet (I'll send a zipped project folder ready to go if someone wants to take a look).  The relevant code was refactored about a month ago from pointers to const references, and maybe this uncovered a dumb VS bug

**Comment by larsonmpdx** [comment]
I refactored it back to pointers and no change

**Comment by larsonmpdx** [comment]
the address of context->send_initial_metadata_ changes by +8 when it's passed into SendInitialMetadata(), after which point it's super corrupt.  This is probably just some really dumb thing I'm not getting, does this make sense to anyone else? see variable watch image
![image](https://cloud.githubusercontent.com/assets/12436438/8972559/390e9f46-3610-11e5-8b10-275e4745ca72.png)

**Comment by larsonmpdx** [comment]
I think the off-by-8 address was a red herring.  the multimap itself is corrupted, if I insert a multimap.clear() without passing its address it crashes from an access violation.  maybe some memory is getting overwritten from some other place, or it could be a VS std lib bug

**Comment by larsonmpdx** [comment]
this was fixed by setting /D "_USE_32BIT_TIME_T" in the c++ build command line of the hello world project, see:

https://groups.google.com/d/msg/grpc-io/nomFgnVbuFo/Xk9Qsy2SBwAJ

I feel kinda dumb.  todo: see if this affects any of the tests on windows (I can't get to this till september.  would be a useful exercise for a googler).  anyway, closing
