### ISSUE TITLE
 GRPC .net framework 4.6.2 problems connecting server hosted in AWS

### ISSUE THREAD

**Issue by rosatarraga** [grpc/grpc#25988]
**What version of gRPC and what language are you using?**
.Net framework 4.6.2

**What operating system (Linux, Windows, …) and version?**
Windows 10

**What runtime / compiler are you using (e.g. python version or version of gcc)**
C# .Net Framework 4.6.2

**What did you expect to see?**
Not crashing with Grpc.Core.RpcException

**What did you see instead?**
We are trying to develop a .net application in wpf with which is consuming grpc services which are deployed on AWS. The connection is done through GRPC.

Our code is as follows:

```
public static GrpcManagerFactory GetGrpcManagerFactory(ConnectionConfiguration configuration, string connectionString, DataAccess.Util.Enumerations.LogLevel clientLogLevel, bool errorMode)
{
    Logger logger = new Logger(connectionString, clientLogLevel);          

    var caRootsPem = File.ReadAllText(Path.Combine(@"..", "cacert.pem"));
    var caRootsKey = new KeyCertificatePair(caRootsPem, File.ReadAllText(Path.Combine(@"..", "AmazonRootCA1.key")));
    ChannelCredentials channelCredentials = new SslCredentials(caRootsPem, caRootsKey, VerifyPeerContext);

    var channel = new Channel(configuration.GrpcHost, configuration.GrpcPort, channelCredentials, new List<ChannelOption> {  });

    channel.ConnectAsync(DateTime.Now.AddSeconds(10).ToUniversalTime());

    var provider = DataAccess.DataProvider.Grpc.GrpcFactory.GetGrpcFactory(channel, configuration, logger.LogManager.LogController);
    var manFactory = new GrpcManagerFactory(provider, channel, connectionString, configuration.InterfaceRetries, clientLogLevel);
    manFactory.ErrorMode = errorMode;
    return manFactory;
}
```
When we try to either do a heartbeat or grpc request (.protos), we get either a DNS error, or that all connections fail....

Any idea?

This is our ConnectionConfiguration

```
public ConnectionConfiguration ConnectionConfiguration
        {
#if DEBUG
            get
            {
                
                    return new ConnectionConfiguration
                        {
                            ClientId = _client != null ? _client.ClientId : 0,
                            InterfaceRetries = _clientPreferences != null ? (_clientPreferences.Depot != null ? _clientPreferences.Depot.InterfaceRetries : 1) : 1,
                            WenAccessTokenUrl = "token",
                            WenClientId = "..",
                            WenClientSecret = "..",
                            RealWebServices = true,
                            GrpcHost = "..",
                            GrpcPort = ..,
                            GrpcChannelCredentials = ChannelCredentials.Insecure
                        };
                }

}
```
We tried to self signed our request but we get the same error.

ERROR:

DNS resolution failed for service: (AWS host)

**Comment by jojofeng** [comment]
Hey, not sure if helpful but I got the DNS resolution failed error when I tried connecting to my Python gRPC server hosted as an AWS Fargate task. The problem was that I tried to connect to `http://[HOSTNAME]:[PORT]`; omitting the `http://` solved the problem

... but now I am getting the `"failed to connect to all addresses"`, which has been a huge pain to debug 😛

**Comment by jtattermusch** [comment]
Yes, you should not use the "http:// prefix" for the channel target (see https://github.com/grpc/grpc/blob/master/doc/naming.md)

It's not clear whether you are still experiencing issues or whether the problem was solved. In any case, this is how you can extra debug logs & traces:
https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md
(that might help you see what's going wrong when trying to connect, e.g. whether there's a certificate problem when connecting).

**Comment by rosatarraga** [comment]
Hello all.

The problem was mainly caused because the certificates. Moreover, one curious thing, is that if I test the same code in .net5, the server responses are always correct and immediately. In the other hand, if I use .net 4.6.2, the responses are intermitent (one OK, another one NOK). Do you know what causes that?

**Comment by jtattermusch** [comment]
> Hello all.
> 
> The problem was mainly caused because the certificates. Moreover, one curious thing, is that if I test the same code in .net5, the server responses are always correct and immediately. In the other hand, if I use .net 4.6.2, the responses are intermitent (one OK, another one NOK). Do you know what causes that?

No idea. It sounds very odd though.

Closing as the original problem seems to have been resolved.
