### ISSUE TITLE
Ability to load multiple versions of grpc in single application

### ISSUE THREAD

**Issue by nima-sharaf** [grpc/grpc#25985]
For client libraries which wrap grpc client as their underlying technology, it makes sense to ILMerge or ILRepack their dependencies, this includes grpc.

The consumers of the client library might be using grpc their selves or may have grpc transitively pulled via other dependencies they have in their projects (which may or may not be ILMerged/ILRepack-ed their selves).

While multiple versions of grpc can be managed using the above approach independently, the un-managed code is not going to get benefit from the effect of internalization and merging. Even though it is possible to load the native libraries from a different location via `GRPC_CSHARP_EXT_OVERRIDE_LOCATION` environment variable, but since all versions of grpc share the same variable name for this override, it makes this a bit unmanageable and unsafe to be relied on.

Is it possible to include the grpc version identifier(or native grpc version identifier) in the variable name so that different grpc versions will have different environment variable names hence can load different native extensions accordingly? i.e. 
```private const string CsharpExtOverrideLocationEnvVarName = "2.36.1_GRPC_CSHARP_EXT_OVERRIDE_LOCATION";```

The other approach (similar to how [netty-java](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L131) does this) is to prefix the environment variable with the grpc namespace and then as an extra step (on top of ILMerge/ILRepack) the grpc namespaces can be relocated(similar to maven shade) using Mono.Cecil(for example grpc.core to be renamed to MyFancyClient.relocated.grpc.core).

```private string CsharpExtOverrideLocationEnvVarName = typeof(NativeExtension).Namespace +".GRPC_CSHARP_EXT_OVERRIDE_LOCATION";```

**Comment by jtattermusch** [comment]
I don't think this is feasible in C#, you simply won't be able to load the same native library twice, at different versions, because it would lead to duplicate symbols. At the same time, doing something like that seems very risky (will likely lead to crashes).

Sorry but this is not something we plan to support.
If the native dependency is a problem for you, I recommend trying out the grpc-dotnet implementation - https://github.com/grpc/grpc-dotnet
