### ISSUE TITLE
g_ipv6_loopback_available variable reinitialization

### ISSUE THREAD

**Issue by babuveld** [grpc/grpc#25998]
Hi,

Looks like gRPC code binds to ipv6 loopback address to check if host supports ipv6 and it happens only once when process gets spawned. So if ipv6 loopback address is created after process is spawned there is no way for the process to listen on ipv6 unless process is restarted.

Can you let me know if there is anyother way to reinit g_ipv6_loopback_available without process restart? Does grpc_shutdown() and grpc_init() helps resetting the variable [Though I coudn't find it in the code]?

**Comment by yashykt** [comment]
That sounds correct.

> Can you let me know if there is anyother way to reinit g_ipv6_loopback_available without process restart? Does grpc_shutdown() and grpc_init() helps resetting the variable [Though I coudn't find it in the code]?
`grpc_init()` and `grpc_shutdown()` are not Core APIs and not stable public API. I would not recommend doing that even if it works.

Can you describe your environment in a bit more detail please? I think if we want to support something like this the easiest way to do this would be to remove the init-time check for ipv6 addresses, and to just do the check each time we try to create such a socket.

**Comment by babuveld** [comment]
We use Linux OS and problem seen in both gRPC-1.0.0 and gRPC-1.15.1

**Comment by babuveld** [comment]
Can you also provide a public API to disable the check. Because on Linux the check may not be needed.

[e.g] In below output you can see nginx server can run on dual stack even though ipv6 loopback is not configured.

bash-4.4# ifconfig -a | grep inet6
bash-4.4#

bash-4.4# ss -anp | grep 80
tcp  LISTEN  0       128              0.0.0.0:80                  0.0.0.0:*      users:(("nginx",pid=2379,fd=33),("nginx",pid=2378,fd=33))
tcp  LISTEN  0       128                 [::]:80                     [::]:*      users:(("nginx",pid=2379,fd=34),("nginx",pid=2378,fd=34))
bash-4.4#

**Comment by babuveld** [comment]
Yes, we are working around by enabling it default for now.
