### ISSUE TITLE
Bound metadata context memory

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#260]
Incrementally collect garbage once we reach some threshold number of bytes in use, preferably in lru order (I think)

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog as part of the fixit and this seems like a stale issue. Please re-open if having this as an open issue remains valuable and there is hope to be addressed in its current form (as opposed to filing another issue later).

**Comment by ncteisen** [comment]
This is accomplished via resource quota
