### ISSUE TITLE
Armhf Runtime problem

### ISSUE THREAD

**Issue by xevilmaxx** [grpc/grpc#26020]
### What version of gRPC and what language are you using?
v1.37.x + C# (Net 5.0)

### What operating system (Linux, Windows,...) and version?
Linux Arm (armhf / Raspbian) [Raspberry3]

### What runtime / compiler are you using (e.g. python version or version of gcc)
cmake

### What did you do?
Here is my script for compilation, and it compiles fine enough on some machines:
```
#!/bin/bash

###
#Install Tool Chain
###

sudo apt-get install build-essential autoconf libtool pkg-config
sudo apt-get install libgflags-dev libgtest-dev
sudo apt-get install clang libc++-dev
sudo apt-get install cmake

###
#Get gRPC Source Code
###

git clone https://github.com/grpc/grpc.git --branch v1.37.x
cd grpc
git submodule update --init


###
#Compile libgrpc_csharp_ext target
###

#idk what its for, but on RPI4 it breaks the script
set -ex

#intended to be run from the repository root
cd grpc/

#create location for build files
mkdir -p cmake/build
cd cmake/build

#setup the build files
cmake -DgRPC_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="${MSBUILD_CONFIG}" ../..

#compile libgrpc_csharp_ext.so 
make -j4 grpc_csharp_ext

#Copy the file back to repository root and rename it to what gRPC.Core currently looks for
cp libgrpc_csharp_ext.so ../../../libgrpc_csharp_ext.x86.so
```

### What did you expect to see?
Good Compilation + Working C# GRPC

### What did you see instead?
**Compilation [V]
C# GRPC ->** 
_2021-04-20 17:46:01.7947|ERROR|LibPP54Lite.PP54LiteManager|System.InvalidOperationException: Unsupported architecture "Unknown".
   at Grpc.Core.Internal.NativeExtension.GetArchitectureString()
   at Grpc.Core.Internal.NativeExtension.GetNativeLibraryFilename()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
   at SharedFunctions_NetCore.ClientServer.GetCoreConnector(String corePort)_

Where GetCoreConnector is:
```
public static CoreProto.CoreProtoClient GetCoreConnector(string corePort)
        {

            log.Debug("Trying to connect to: 127.0.0.1:" + corePort);

            var channel = new Channel("127.0.0.1:" + corePort, ChannelCredentials.Insecure);

            var client = new CoreProto.CoreProtoClient(channel);

            //no need to close channel

            return client;

        }
```

### Anything else we should know about your project / environment?
Last working and tested branch: V2.27.0

**Comment by jtattermusch** [comment]
32 bit arm architectures such as armhf are not supported in Grpc.Core. 
If you really want to try this, feel free to look at https://github.com/grpc/grpc/pull/25717 and try making the necessary changes in the native library loader to make this work. That way you could make things work in your local fork.
