### ISSUE TITLE
[Flake] AsyncEnd2endTest.ReconnectChannel

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#26022]
```
D0416 18:26:26.500938000 4535682496 init.cc:226]                       grpc_shutdown starts clean-up now
[waiter.cc : 141] RAW: pthread_mutex_unlock failed: 22
*** SIGABRT received at time=1618622786 ***
PC: @     0x7fff767ef2c2  (unknown)  __pthread_kill

2021-04-16 18:26:26,509 FAILED: cmake/build/async_end2end_test --gtest_filter=AsyncEnd2end/AsyncEnd2endTest.ReconnectChannel/4  GRPC_POLL_STRATEGY=poll [ret=-6, pid=40753, time=0.5sec]
```

https://source.cloud.google.com/results/invocations/d91e4593-5ea0-4355-8958-bcb0da255a59/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_c%2B%2B_macos_dbg_native/tests

**Comment by markdroth** [comment]
I've actually been seeing this kind of crash sporadically across a lot of tests lately.  Could this be related to the recent absl synchronization change?

**Comment by veblush** [comment]
Abseil sync was rolled back so no more error.
