### ISSUE TITLE
Python GRPC - Peer name is not in peer Certificate Error (TLS terminated at Ingress Controller)

### ISSUE THREAD

**Issue by alexcpn** [grpc/grpc#26038]
### What version of gRPC and what language are you using?

```
pip3 show grpcio
Name: grpcio
Version: 1.37.0

ip3 show grpcio-tools
Name: grpcio-tools
Version: 1.37.0
```

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.8.5

### What did you do?
Have a Go based GRPC server running in Kubernetes and exposed as Ingress via HAProxy Ingress Controller. The TLS is terminated at the Ingress Controller and the ingress Controller has a Server certificate (CN=api.test.com)

Ingress End Point for GRPC Service is samplegrpc.XX.nip.io:443 (note the IP part sanitised with XX)

I am able to connect vi Go GRPC Client -below

```

const (
	address = "samplegrpc.XX.nip.io:443"
)

func main() {
	// Set up a connection to the server.
	config := &tls.Config{
		InsecureSkipVerify: true}
	conn, err :=  grpc.Dial(address, grpc.WithTransportCredentials(credentials.NewTLS(config))) //working on 443
	
	//conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewSearchServiceClient(conn)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	r, err := c.Search(ctx, &pb.SearchRequest{Query: "Protocol Buffer",EmailId: "alex.test@xx.com"})
	if err != nil {
		log.Fatalf("could not execute search: %v", err)
	}


```

**When connecting via Python GRPC Client - getting this error**

```
 try:
        with open('sampleserver.cer', 'rb') as f:
            creds = grpc.ssl_channel_credentials(f.read())
            cert_cn = "samplegrpc.XX.nip.io" # or parse it out of the cert data
            options = (('grpc.ssl_target_name_override', cert_cn),)
            channel = grpc.secure_channel("samplegrpc.XX.nip.io:443po",creds,options=options)
            stub = test_pb2_grpc.SearchServiceStub(channel)
            response = stub.Search(test_pb2.SearchRequest
                (query="Protocol Buffer",email_id="alex.test@gmail.com"))
            print(response)
    except (KeyboardInterrupt, SystemExit):
        sys.exit(0)


```

Error trace
```
D0421 15:10:53.449475100    4970 security_handshaker.cc:183] Security handshake failed: {"created":"@1618998053.449456100","description":"Peer name samplegrpc.XX.nip.io is not in peer certificate","file":"src/core/lib/security/security_connector/ssl/ssl_security_connector.cc","file_line":57}
I0421 15:10:53.449609200    4970 handshaker.cc:88]           handshake_manager 0xb6f740: error={"created":"@1618998053.449456100","description":"Peer name samplegrpc.XX.nip.io is not in peer certificate","file":"src/core/lib/security/security_connector/ssl/ssl_security_connector.cc","file_line":57} shutdown=0 index=2, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
```

Certificate at Ingress Controller

```
cert =ssl.get_server_certificate(('samplegrpc.XXX.nip.io', 443))
x509 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
print(x509.get_subject().get_components())
# [(b'C', b'US'), (b'ST', b'Ohio'), (b'L', b'Columbus'), (b'O', b'MyCompany'), (b'CN', b'api.test.com')]
````
### What did you expect to see?

Python GRPC Client should be able to talk to a GRPC server , in the case where Server is behind a reverse proxy/ingress controller and TLS terminated at the ingress controller

**Comment by ZhenLian** [comment]
gRPC TLS will perform a hostname verification after the TLS handshake completes. The check will basically verifies if the target name sent from the client("samplegrpc.XX.nip.io" in your case) matches the peer cert on server's certificate. Failing to perform such checks will expose applications to the man-in-the-middle attacks.
There are several ways to bypass it, but keep in mind to do it only in a toy application. The most easiest way is to use SetSslTargetNameOverride(https://github.com/grpc/grpc/blob/master/include/grpcpp/support/channel_arguments.h#L62) to override the target name, in your case "samplegrpc.XX.nip.io". 
Note that in Go we have similar checks, but in your code you used `InsecureSkipVerify: true` and disabled it. As mentioned before, doing this is highly discouraged in a real production environment.

**Comment by alexcpn** [comment]
Thanks; 

>>There are several ways to bypass it, but keep in mind to do it only in a toy application. The most easiest way is to use SetSslTargetNameOverride(https://github.com/grpc/grpc/blob/master/include/grpcpp/support/channel_arguments.h#L62) to override the target name, in your case "samplegrpc.XX.nip.io".

I have given this option in Python; However, it does not work as expected; Hence this issue

```
 options = (('grpc.ssl_target_name_override', cert_cn),)
            channel = grpc.secure_channel("samplegrpc.XX.nip.io:443po",creds,options=options)
```
>>Failing to perform such checks will expose applications to the man-in-the-middle attacks.

Thanks; this is clear; However this means then that unlike regular web applications which are behind a reverse proxy and TLS terminated at the proxy; and Chrome shows the site as trusted if its CA is in Trusted Certificate;  if we trust the CA of the Ingress/reverse proxy certificate in GRPC client, it still is not enough in GRPC flow ??

Each service behind the proxy should do its own certificate management. ?

**Comment by ZhenLian** [comment]
> I have given this option in Python; However, it does not work as expected; Hence this issue

Hmmm this is weird. Yes, we are debugging the ALPN issue there, but I don't see any correlations between these two problems, unless I missed something. However, I would suggest we wait until that bug is fixed, since I guess it would be very hard to reproduce the problem here.
And a quick question, for the line `channel = grpc.secure_channel("samplegrpc.XX.nip.io:443po",creds,options=options)`, why do we have a suffix "po" in the end of the target name?

> However this means then that unlike regular web applications which are behind a reverse proxy and TLS terminated at the proxy; and Chrome shows the site as trusted if its CA is in Trusted Certificate; if we trust the CA of the Ingress/reverse proxy certificate in GRPC client, it still is not enough in GRPC flow ??

Yes. Verifying the trust certificate can only tell you whether the peer you connected to are from someone you trusted, but not necessarily from someone you were connecting to. For example, Say a client is connecting to "foo.bar.com", it is also essential for the server cert to have "foo.bar.com" in CN or SAN field, so that we are sure whomever we trusted is actually an entity we claimed to connect.
So in your case, it's important for the server to contain a CN with a value `samplegrpc.XX.nip.io` instead of `api.test.com`.

> Each service behind the proxy should do its own certificate management. ?
 
I don't think I have enough context to answer this question, but a general way to think of this is, if you want TLS, then you will at least do the certificate management on the server side, because the certificates are usually issued from a CA, and you will have to think of questions like, how do we distribute the certs from the CA to the application server, etc.

**Comment by alexcpn** [comment]
>>And a quick question, for the line channel = grpc.secure_channel("samplegrpc.XX.nip.io:443po",creds,options=options), why do we have a suffix "po" in the end of the target name?

@ZhenLian  sorry ; that just a typo  here, when I trying to mask the IP;

**Comment by matthewstevenson88** [comment]
@alexcpn I believe this is answered in @ZhenLian's final comment: you should be setting the target override to `api.test.com` rather than `samplegrpc.XX.nip.io`. Please feel free to re-open if this does not work.
