### ISSUE TITLE
FLAKE: "pthread_mutex_lock failed" crash on MacOS (seen in many tests)

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#26042]
I've seen this in a number of tests lately.  The most recent one is here:

https://source.cloud.google.com/results/invocations/34d2f278-60b4-40fc-b50c-0243d5463ec9/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_dbg_native/tests

Could this be related to the recent absl synchronization change?

**Comment by veblush** [comment]
I'm looking out on this since https://github.com/grpc/grpc/pull/25841 and thank you for the report. It doesn't appear that the flakiness changed significantly after the PR merged but it's worth looking at this particular failure.
