### ISSUE TITLE
spinlock due to pollhup in GRPC

### ISSUE THREAD

**Issue by soumik0108** [grpc/grpc#26045]
### What version of gRPC and what language are you using?

grpc 1.18.0 c++
### What operating system (Linux, Windows,...) and version?

Freebsd 11
### What runtime / compiler are you using (e.g. python version or version of gcc)

LLVM 3.7
### What did you do?

the client called shutdown and close on the connection fd.

### What did you expect to see?

No spinlock. Normal CPU usage

### What did you see instead?

high CPU. grpc stuck in spinlock  in POLL.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

Diffrence in behavior of poll in BSD and Linux

If the client calls shutdown of the socket [shutdown(fd,SHUT_RDWR)].

In Linux the poll returns POLLHUP and POLLIN.
reading the fd returns 0 byte.

In BSD poll returns POLLIN reading the fd returns 0 byte.
POLLHUP is returned by poll in BSD when client closes the socket fd.

Looks like this is not handled properly in grpc

Due to 0 byte read(POLLIN) the fd is getting marked as shutdown and the watcher is getting removed(assigned null in fd_begin_poll). And after that once the POLLHUP is getting delivered grpc stack is not handling it.

    
 The Linux/MacOS and BSD behaves differently. If the other end of the
 socket calls shutdown with SHUT_RDWR in Linux poll will return
  POLLHUP and POLLIN. BSD return POLLIN only. And at later point
  when other side closes the socket BSD return POLLHUP. This is
  leading to a spinlock. Due to the POLLIN and 0 byte read the
   the fd is marked for shutdown and the watcher gets removed.
   Later when poll recieves POLLHUP it is not getting processed as
    watcher is already removed. To fix this access pollset, match the
    fd and shutdown field and mark it recieved pollhup.

I am attaching the grpc traces. fd 15 is creating the spinlock. Filename "trace.txt". 
I am attaching the test program used to test poll on LINUX and BSD along with the output file name  "bsd_v_linux.txt".
I have prepared a patch witch fixes the problem filename "pollhup.patch"
[Archive.zip](https://github.com/grpc/grpc/files/6353470/Archive.zip)

**Comment by soumik0108** [comment]
Any update on this?

**Comment by veblush** [comment]
@soumik0108 I was about to ask you to make a PR for this but you already did it (https://github.com/grpc/grpc/pull/26142) thanks! Since we don't have any harnesses for BSD, we might have to depend on your test results about the validness of BSD. If your change keeps it run properly on Linux and your change is verified on your environment, your PR can get merged.

**Comment by veblush** [comment]
@soumik0108 Do you still need this?

**Comment by yashykt** [comment]
It's been more than 30 days since "disposition/requires reporter action" was added. Please feel to re-open/create a new issue if the issue persists.
