### ISSUE TITLE
ignoring new grpc_chttp2_stream creation on client

### ISSUE THREAD

**Issue by CharleyHsiung** [grpc/grpc#26053]
I0422 10:52:09.768395723   27610 timer_manager.cc:132]       flush exec_ctx
I0422 10:52:09.768530778   27610 tcp_posix.cc:887]           TCP:0x1f8efe70 got_read: "No Error"
I0422 10:52:09.768669323   27610 tcp_posix.cc:879]           TCP:0x1f8efe70 do_read
I0422 10:52:09.768880421   27610 tcp_posix.cc:680]           TCP:0x1f8efe70 call_cb 0x1f96d528 0x7f82e96ca8:0x1f96d400
I0422 10:52:09.769037872   27610 tcp_posix.cc:683]           READ 0x1f8efe70 (peer=ipv6:[::]:34699) error="No Error"
D0422 10:52:09.769184021   27610 tcp_posix.cc:689]           DATA: 00 00 04 01 04 00 00 01 4f 88 c2 c1 c0 00 00 17 00 00 00 00 01 4f 00 00 00 00 12 0a 10 7b 22 72 65 74 75 72 6e 22 3a 20 74 72 75 65 7d 00 00 04 01 05 00 00 01 4f bf 0f 2f 00 00 00 04 08 00 00 00 00 00 00 00 00 62 '........O............O.......{"return": true}........O../.............b'
E0422 10:52:09.769347358   27610 parsing.cc:618]             ignoring new grpc_chttp2_stream creation on client
D0422 10:52:09.769497725   27610 flow_control.cc:113]        0x1f96e468[0][cli] |   data recv | trw:                       4194304, tlw:                       4194304, taw:            4194261 -> 4194238, srw:                              , slw:                              , saw:                              
E0422 10:52:09.769644812   27610 parsing.cc:618]             ignoring new grpc_chttp2_stream creation on client

Been stuck here，The log prompts ‘ignoring new grpc_chttp2_stream creation on client’
`call_future = self.__stub.cmd_node.future(input_data, wait_for_ready = True)
result = call_future.result().buf`

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
