### ISSUE TITLE
Use Go version 1.16 instead of 1.11 for future interop tests

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc#26063]
1.11 is now several versions past support by the Go team, and we'd like to drop it from our regular regression tests, since it now causes a good bit of extra maintenance burden for the team.

@jtattermusch, if you can let me know what all needs to happen to make that work, I can do it myself, or if you can make a canonical PR for doing it this time, we can do it in the future.  (We would want to update the version used every 3 Go releases, at least.)  Thanks!

**Comment by jtattermusch** [comment]
Just to clarify:

Did you wanna do this for the interop_matrix (as in https://github.com/grpc/grpc/blob/a2645aaff4a5976836687fc7877397521b6221de/tools/interop_matrix/client_matrix.py#L188)

OR

for the "regular" interop tests? (="run_interop_tests.py") (https://github.com/grpc/grpc/blob/master/tools/dockerfile/interoptest/grpc_interop_go/Dockerfile)
Results are e.g: https://source.cloud.google.com/results/invocations/26fb8971-4a73-4934-ad9b-0f1adcad13de/targets/github%2Fgrpc%2Finterop_test/tests;query=go

**Comment by dfawley** [comment]
We'll need to update both.  New versions of gRPC won't support 1.11 (or even 1.13 at this point since 1.16 is available now, and we only support the last 3 releases of Go - like the Go team's policy).
