### ISSUE TITLE
Enable base-namespace in projects protobuf item group

### ISSUE THREAD

**Issue by maxreb** [grpc/grpc#26070]
### Is your feature request related to a problem? Please describe.
When I use proto files from other Web Apis they are often have package names like "api" or "as" or something. As the `Grpc.Tools` automatically creates the namespaces, the calls are like "As.Get()" or "Api.Get()" which is not quite nice and understandable. I know that I can add `option csharp_namespace = "My.Custom.Namespace";` to all of the proto files, but as I want to keep them updated automatically (and there are a lot of proto files on some webapis) I don't want to change them.

### Describe the solution you'd like
protoc has this option: `--csharp_opt=base_namespace=My.Costom.Namespace`. I would like to see this implemented in the Protobuf tag like this:

    <ItemGroup>
                <Protobuf
                   Include="protobuf\**\*.proto"
                   GrpcServices="Client"
                   BaseNamespace="My.Custom.Namespace"/>
    </ItemGroup>

**Comment by jtattermusch** [comment]
We don't recommend using extra options (such as "base_namespace") when using an automatic integration of codegen into the build. But if you really want to set that option, you can use the "AdditionalProtocArguments" attribute (see "https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md).

Btw, it seems that you are misunderstanding what the "base_namespace" option does - it does not override the "csharp_namespace" option as you're suggesting. Please doublecheck that setting base_namespace is really what you want (it likely is not and it won't help you with your issue IIUC).
