### ISSUE TITLE
Probable memory leak in PHP extension 1.37.0

### ISSUE THREAD

**Issue by lurkie** [grpc/grpc#26085]
### What version of gRPC and what language are you using?
gRPP version 1.37.0 for PHP 7.2.24

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04
uname:
Linux $hostname 5.4.0-72-generic \#80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Also tested on Ubuntu 20.04:
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### What did you do?
When querying GCP's Cloud Datastore using the gRPC PECL extension, it will return (in our case) 29k entities containing XML snippets, totaling for ~125 MB of XML data. We got error messages stating out-of-memory errors in our PHP application. Given the two files described below, I query GCP's Datastore. This example does depend on a preconfigured and pre-filled GCP Project though.

composer.json:
```json
{
    "require": {
        "php": "^7.2",
        "ext-grpc": "*",
        "ext-protobuf": "*",
        "google/cloud-datastore": "^1.12"
    }
}
```

test.php:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
$keyFile = '...';
$kind = '...';
$parentId = '...';
ini_set('memory_limit', 250 * 1024 * 1024);

/**
 * @property string $xml_detail
 */
class TestModel extends Google\Cloud\Datastore\Entity{}

function dumpMemoryUsage(int $i): void {
    $n1 = memory_get_usage(true);
    $n2 = memory_get_peak_usage(true);
    printf(
        "<!-- Item #: %d, usage: %d MB, peak usage: %d MB -->\n",
        $i, intdiv($n1, 1024 ** 2), intdiv($n2, 1024 ** 2)
    );
}

function testMemoryLeak(): void {
    global $keyFile, $kind, $parentId;
    $client = new Google\Cloud\Datastore\DatastoreClient(['keyFilePath' => $keyFile]);
    $parentKey = $client->key($kind, $parentId);
    $query = $client->query()->kind($kind)->hasAncestor($parentKey);
    $entityIterator = $client->runQuery($query, ['className' => TestModel::class]);

    $i = 0;
    // Iterates over ~29k entities
    foreach ($entityIterator as $entity) {
        /** @var TestModel $entity */
        $i++;
        // xml_detail contains ~ 4600 bytes avg
//        echo $entity->xml_detail;
    }
    dumpMemoryUsage($i);
}
testMemoryLeak();
```

Script has been run using CLI.

### What did you expect to see?
I expected to see reasonably memory usage. 

### What did you see instead?
Memory usage is very high, considering PHP output buffering in pretty small (even disabled for CLI) and no entities are being held in memory by this code. Using grpc pecl extension, memory usages is up to 204 MB:
`<!-- Item #: 28702, usage: 204 MB, peak usage: 204 MB -->`

### Anything else we should know about your project / environment?

- We use GCP Datastore using a hierarchy (parent/child entities). I did not try to query a kind without hierarchy.
- GCP also uses PHP extension protobuf. It did not matter whether the protobuf extension was enabled or not.
- I did not yet try to run with GRPC_VERBOSITY or GRPC_TRACE configured, as I'm not that knowledgeable in grpc
- I did try to use the composer package `grpc/grpc` instead of the PHP extension. When using this, memory usage stays at a reasonably low level:
  `<!-- Item #: 28702, usage: 14 MB, peak usage: 18 MB -->`
- I did search for existing issues, finding issues describing memory leaks for other programming languages. Not sure if they are related.

**Comment by stanley-cheung** [comment]
Will look into this.

**Comment by lurkie** [comment]
I was quite sure protobuf did not matter... However, I did some tests again, and it seems to confirm that protobuf is indeed the culprit.

**Memory usage (MB)**

|               |  gRPC:   |        |
|---------------|----------|--------|      
| **Protobuf:** | Disabled | 1.37.0 |
| Disabled      |       16 | 18     |
| 3.15.8        |       16 | 214    |
| 3.16.0        |       16 | 214    |

However, I kept also track of required time to retrieve and process all XML data. It seems enabling gRPC increases the required time, especially when protobuf is disabled. In that case, the CPU utilization of the PHP process also reaches 100%. This was a bit of a surprise to me.

**Avg time (seconds)**.
Average time required on at least 3 runs using the script mentioned it the issue description:

|               |  gRPC:   |        |
|---------------|----------|--------|      
| **Protobuf:** | Disabled | 1.37.0 |
| Disabled      |    37.09 | 121.65 |
| 3.15.8        |    37.39 | 49.86  |
| 3.16.0        |    36.02 | 43.95  |

Should I report this in a new issue?

**Comment by stanley-cheung** [comment]
Yes it's expected - the protobuf extension is supposed to provide a much better performance boost. It's less efficient to use the protobuf composer package.


(Btw, the 2 tables above were slightly mis-aligned - it's a bit hard to read)

**Comment by haberman** [comment]
The fixes in https://github.com/protocolbuffers/protobuf/pull/8614 make the protobuf C extension Valgrind-clean (except for a few edge cases involving exceptions that I was not able to figure out).

This should be released in the next week or two as a patch release of 3.17.x.

**Comment by lurkie** [comment]
@stanley-cheung 

> Yes it's expected - the protobuf extension is supposed to provide a much better performance boost.

I do indeed expect less performance when disabling the protobuf extension. I did not expect an increased performance when I disable both. This should be a bit easier to read:

1. gRPC & protobuf enabled: 43.95s (for protobuf version 3.16.0)
2. only gRPC enabled: 121.65s
3. both disabled: 37.09s

(time required to fetch ~125 MB of XML data)
