### ISSUE TITLE
Pylint gRPC Python code

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#261]
It's not a perfect tool but it catches a lot of problems.

**Comment by nathanielmanistaatgoogle** [comment]
[Pull request 9276](https://github.com/grpc/grpc/pull/9276) may be illustrative for this in so far as it demonstrates running a tool over the codebase and passing or failing sanity testing based on its result.

**Comment by mehrdada** [comment]
#9691 is a first attempt at fixing this issue. It still needs to (a) get enabled for all grpc python packages, and (2) issues preventing pylint to cleanly pass need to be fixed and disabled checks disabled in .pylintrc need to be turned on one by one.

**Comment by nathanielmanistaatgoogle** [comment]
Since in just the last few days I've casually run into problems in `tests/` and `tools/` let's leave this issue open until all the Python files in the codebase are linted.

**Comment by nathanielmanistaatgoogle** [comment]
Just `tools/` remaining, sooo tempting...

**Comment by mehrdada** [comment]
I think we should upgrade Pylint before expanding its scope

**Comment by nathanielmanistaatgoogle** [comment]
Fun fact: we have recently upgraded our use of Pylint. :-)

**Comment by mehrdada** [comment]
Downgrading to p3 as the dry-run shows `tools/` scripts need a non-trivial amount of work and not as high priority to pylint as the the core python runtime.

**Comment by mehrdada** [comment]
Decided to close this bug as Fixed by #15682 among other things.

Will file separate issues to pylint `examples/python` and `tools` as they should be separately prioritized and/or owned.
