### ISSUE TITLE
Unable to checkout '19fb89416f3fdc2d6668f3738f444885575285bc' in submodule path 'third_party/protobuf'

### ISSUE THREAD

**Issue by eugrin** [grpc/grpc#26108]
### What version of gRPC and what language are you using?
1.36.4

### What operating system (Linux, Windows,...) and version?
CentOS 8.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
devtoolset-7

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
# git clone -b v1.30.0 https://github.com/grpc/grpc
# cd grpc
# git submodule update --init

### What did you expect to see?
No errors

### What did you see instead?
**fatal: reference is not a tree: 19fb89416f3fdc2d6668f3738f444885575285bc**
Cloning into 'third_party/protoc-gen-validate'...
remote: Enumerating objects: 9461, done.
remote: Counting objects: 100% (241/241), done.
remote: Compressing objects: 100% (171/171), done.
remote: Total 9461 (delta 92), reused 170 (delta 58), pack-reused 9220
Receiving objects: 100% (9461/9461), 13.96 MiB | 14.62 MiB/s, done.
Resolving deltas: 100% (4479/4479), done.
Submodule path 'third_party/protoc-gen-validate': checked out '872b28c457822ed9c2a5405da3c33f386ac0e86f'
Cloning into 'third_party/re2'...
remote: Enumerating objects: 6471, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 6471 (delta 47), reused 50 (delta 21), pack-reused 6379
Receiving objects: 100% (6471/6471), 3.11 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4942/4942), done.
Submodule path 'third_party/re2': checked out 'aecba11114cf1fac5497aeb844b6966106de3eb6'
Cloning into 'third_party/udpa'...
remote: Enumerating objects: 406, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 406 (delta 32), reused 41 (delta 18), pack-reused 330
Receiving objects: 100% (406/406), 124.96 KiB | 0 bytes/s, done.
Resolving deltas: 100% (152/152), done.
Submodule path 'third_party/udpa': checked out 'cc1b757b3eddccaaaf0743cbb107742bb7e3ee4f'
Cloning into 'third_party/zlib'...
remote: Enumerating objects: 5150, done.
remote: Total 5150 (delta 0), reused 0 (delta 0), pack-reused 5150
Receiving objects: 100% (5150/5150), 3.66 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3612/3612), done.
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
**Unable to checkout '19fb89416f3fdc2d6668f3738f444885575285bc' in submodule path 'third_party/protobuf'**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by mbeaulie** [comment]
1.36.3 suffers from the same issue. BTW.

**Comment by mbeaulie** [comment]
This issue seems to have appeared sometime yesterday. I was able to clone and fetch submodules for these releases 2 days ago.

**Comment by mbeaulie** [comment]
I still get the issue on a clean git clone.
If I click on the commit you list above, I see warning at the top of the page: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

**Comment by mbeaulie** [comment]
That v1.30.0 in the reproduction steps was a typo. Should have been 1.36.4. V1.30.0 seems fine.

**Comment by eugrin** [comment]
It was a typo in the reproduction step. Should be 1.36.4

**Comment by mbeaulie** [comment]
That warning is now gone for that commit, and everything is working again. If it is something you did, thanks! If not, well thanks to whoever fixed things on the protobuf repo side.

I guess  the issue can be closed.

**Comment by eugrin** [comment]
Resolved
