### ISSUE TITLE
CreateChannel(): Could not get default pem root certs

### ISSUE THREAD

**Issue by siriuslan** [grpc/grpc#26106]
### What version of gRPC and what language are you using?
1.35.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019

### What did you do?
I have a grpc server running with ssl certificate installed and I follow example code [here](https://grpc.io/docs/guides/auth/#using-client-side-ssltls) to create a grpc client and connect to my server. Without specify a root certificate, failed to create channel. My code as below

```
`const std::string SECURE_GRPC_CHANNEL_ADDRESS = <MY_SERVER_AND_PORT>;

class GrpcChannel
{
    GrpcChannel()
    {
        **auto ca_cert = get_file_contents(cacert_path);**
        SslCredentialsOptions options = { **ca_cert**, "", "" };
        auto channel_creds = SslCredentials(options);
        channel_ = grpc::CreateChannel(SECURE_GRPC_CHANNEL_ADDRESS, channel_creds); 
    }
}
```
`
I have to use **Bold code** above to provide a root cert, otherwise below error been reported
![image](https://user-images.githubusercontent.com/39588576/116354667-16dcb800-a83c-11eb-9e03-f42d0009b70e.png)

As the behavior is different with what is described [here](https://grpc.io/docs/guides/auth/#using-client-side-ssltls), I write a client using python and it works without giving a root cert.
```
host_server = <MY_SERVER_AND_PORT>
credentials = grpc.ssl_channel_credentials()

with grpc.secure_channel(host_server, credentials) as channel:
    construct stub and call stub method
```

### What did you expect to see?
I expect to create channel successfully on Windows using grpc C++ lib without providing a root cert.

### What did you see instead?
I have a provide root cert so that channel can be created while python client does not need it.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by drfloob** [comment]
Thanks for bringing this up, you're right that you'll need to manually specify your root certs on Windows. Today I learned gRPC's single-sided TLS defaults all assume a posix system. Our documentation doesn't explain that, as you found, so I'll make sure the docs get updated.

As for adding support for defaults on non-posix systems, I'm not sure if our test rigs are set up to exercise TLS on Windows. It seems this is a fairly rare scenario for gRPC-core C++ users, so hopefully documenting this extra step is sufficient for now.

**Comment by BranigansLaw** [comment]
For anyone caught on this, someone added a fix for this with full code:

https://stackoverflow.com/questions/71580681/ssl-grpc-client-works-fine-in-c-but-fails-with-unavailable-empty-update-in-c
