### ISSUE TITLE
C# support for aarch32 Linux

### ISSUE THREAD

**Issue by MD-V** [grpc/grpc#26119]
### Is your feature request related to a problem? Please describe.

We'd like to run a C# application with gRPC Server and Client on the Raspberry Pi 3 (aarch32 Linux).
Currently this is not possbile because only aarch64 is supported.

Support for ARM has already been discussed in https://github.com/grpc/grpc/issues/17451

### Describe the solution you'd like

An aarch32 compatible library for C# as provided in https://github.com/grpc/grpc/pull/25717 for aarch64
It can be included in the nuget package or an alternative nuget package e.g. Grpc.Core.AArch32 

### Describe alternatives you've considered

- We could try to build it by ourselves but I think the better solution is to manage it in this repository.
- use grpc-dotnet --> we don't want to use ASP.NET Core

**Comment by jtattermusch** [comment]
We do not plan to add support for ARM32 for Grpc.Core (gRPC C#), sorry. We only planned to add aarch64 support (and we delivered that).
I'd recommend using grpc-dotnet if you want to run on arm32.

**Comment by MD-V** [comment]
@jtattermusch Thanks for your reply and sorry for opening this issue again, but for our use case the support is very important.

If we would provide a PR that adds support for aarch32 would you accept it?

**Comment by jtattermusch** [comment]
> @jtattermusch Thanks for your reply and sorry for opening this issue again, but for our use case the support is very important.
> 
> If we would provide a PR that adds support for aarch32 would you accept it?

I think to accept it to the upstream, it wouldn't make sense to add support arm32 solely for C#, it would need to be part of a bigger effort.
Adding arm32 binary would futher bloat the size of Grpc.Core and we don't want that.
At this point I think your best option is to compile grpc_csharp_ext yourself (to target aarch32) and then use the `GRPC_CSHARP_EXT_OVERRIDE_LOCATION` env variable to force loading it?
https://github.com/grpc/grpc/pull/25490/files#diff-2c65a0fc0ff30ef55102682b95465c44e758e53921b0f36be1b427f1feb12e18R33
