### ISSUE TITLE
Insecure server construction should be explicit in ruby

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#2614]
Constructing a server that does NOT use SSL should follow an API where there is an explicit insecure credential object passed during server construction. This ensures that server authors learn the API for building a secure server, and that they never build an insecure server implicitly.

**Comment by tbetbetbe** [comment]
I'd like this issue and similar ones to get feedback from our internal ruby API reviewers.
- The API as is already idiomatic for ruby/node/php/python etc.
- The default insecure sentinel object being proposed in a idiom from other programming languages
