### ISSUE TITLE
grpc bazel build fails on Mac mini M1 (Apple Silicon)

### ISSUE THREAD

**Issue by devjgm** [grpc/grpc#26155]
### What version of gRPC and what language are you using?

Current head: edf500fb8259680b773f5271bbeaf61b167b04bb

### What operating system (Linux, Windows,...) and version?

macos M1 (mac mini)
ProductName:    macOS
ProductVersion: 11.3
BuildVersion:   20E232

### What runtime / compiler are you using (e.g. python version or version of gcc)

Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### What did you do?

```
git clone https://github.com/grpc/grpc.git
cd grpc
bazel build ...
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 3.7.1 will be used instead of system-wide bazel installation.
Unsupported architecture: Darwin arm64
```

### What did you expect to see?

The build should succeed.

### What did you see instead?

```
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 3.7.1 will be used instead of system-wide bazel installation.
Unsupported architecture: Darwin arm64
```

### Anything else we should know about your project / environment?

This is a new Mac mini M1

**Comment by drfloob** [comment]
Apple Silicon support is being actively worked on now. Please stay tuned!

Related issue: https://github.com/grpc/grpc/issues/24002

**Comment by vlad2010** [comment]
@drfloob   Could you please give more info on what is the status of Apple Silicon support? I see that ARM64 support was announced for Linux  https://grpc.io/blog/grpc-on-arm64/

**Comment by drfloob** [comment]
Without a reliable continuous integration platform for M1, we're a bit blocked. We're watching and weighing a handful of options, essentially waiting for something workable to become available to us. Until then, unfortunately we can't commit to support.
