### ISSUE TITLE
Disabled ALPN, and encountered Expected SETTINGS frame as the first frame, got frame type 80

### ISSUE THREAD

**Issue by hanming-nls** [grpc/grpc#26160]
### What version of gRPC and what language are you using?
grpc 1.38.0-dev
exists in 1.36 too

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.9
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730 for x64

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Trying to run a Google Document AI sample in windows environment behind a corporate proxy with reference to the following
https://github.com/googleapis/python-documentai/blob/30008b45ecc536ecdd47adc04b37cf9881ca0033/samples/snippets/quickstart_sample.py

However, during runtime, when trying to connect to Google Document AI, it will throw an error
"Cannot check peer: missing selected ALPN property."

Thus, attempt to custom build a grpcio for python with TSI_OPENSSL_ALPN_SUPPORT disabled.
The compilation of of the gprc code and python_build is successful.

However, after the TSI_OPENSSL_ALPN_SUPPORT or ALPN check is disabled, a different error is shown during runtime
"Expected SETTINGS frame as the first frame, got frame type 80"

If attempt to run the same code bypassing the proxy, the execution is successful.

### What did you expect to see?
The execution of the program to be successful

### What did you see instead?
In the console, the log as below

E0504 15:36:52.742000000 12584 src/core/lib/debug/trace.cc:65] Unknown trace var: 'transport_security'
I0504 15:36:52.770000000 12584 src/core/tsi/ssl_transport_security.cc:223]      HANDSHAKE START -       TLS client start_connect  - !!!!!!
I0504 15:36:52.771000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -    TLS client enter_early_data  - !!!!!!
I0504 15:36:52.771000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -   TLS client read_server_hello  - !!!!!!
I0504 15:36:52.793000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_certifi  - !!!!!!
I0504 15:36:52.794000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_certificate_st  - !!!!!!
I0504 15:36:52.794000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client verify_server_certi  - !!!!!!
I0504 15:36:52.795000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_key_exc  - !!!!!!
I0504 15:36:52.795000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_certificate_re  - !!!!!!
I0504 15:36:52.795000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_hello_d  - !!!!!!
I0504 15:36:52.795000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_certifi  - !!!!!!
I0504 15:36:52.795000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_key_exc  - !!!!!!
I0504 15:36:52.797000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_certifi  - !!!!!!
I0504 15:36:52.797000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_finishe  - !!!!!!
I0504 15:36:52.797000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -       TLS client finish_flight  - !!!!!!
I0504 15:36:52.797000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_session_ticket  - !!!!!!
I0504 15:36:52.797000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client process_change_ciph  - !!!!!!
I0504 15:36:52.807000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_finishe  - !!!!!!
I0504 15:36:52.808000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client finish_client_hands  - !!!!!!
I0504 15:36:52.808000000 12584 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -                TLS client done  - !!!!!!
I0504 15:36:52.808000000 12584 src/core/tsi/ssl_transport_security.cc:223]       HANDSHAKE DONE -                TLS client done  - !!!!!!
I0504 15:36:52.826000000 12584 src/core/ext/filters/client_channel/subchannel.cc:1012] Connect failed: {"created":"@1620113812.826000000","description":"Failed parsing HTTP/2","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2536,"referenced_errors":[{"created":"@1620113812.826000000","description":"Expected SETTINGS frame as the first frame, got frame type 80","file":"src/core/ext/transport/chttp2/transport/parsing.cc","file_line":262},{"created":"@1620113812.826000000","description":"Trying to connect an http1.x server","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2489,"grpc_status":13,"http_status":400}]}

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
The corporate proxy is a SSL proxy with it's own certificate

If attempt to run the same code bypassing the proxy, the execution is successful.

related issue?
https://github.com/grpc/grpc/issues/7726

**Comment by yashykt** [comment]
Once the HTTP/2 transport receives an established connection, it expects the SETTINGS frame to be the first frame. From a quick look, it looks like the HTTP/2 transport is seeing a different frame, possibly some leftover frames from the security handshake.

**Comment by yashykt** [comment]
Yihua, please take a look. I definitely see code in gRPC around `TSI_OPENSSL_ALPN_SUPPORT` but I'm not sure if we test it anywhere or if we officially support disabling it.

**Comment by yihuazhang** [comment]
Sorry for the late reply. Yes, we do have ALPN tests in `ssl_transport_security_test.cc`. I do not think we should disable  `TSI_OPENSSL_ALPN_SUPPORT` but rather see what caused  "Cannot check peer: missing selected ALPN property." error. One possible cause may be using an old version of SSL library that does not support ALPN (e.g., only supports NPN).

**Comment by erm-g** [comment]
@hanming-nls keeping in mind that the latest release is [1.52.1](https://github.com/grpc/grpc/releases/tag/v1.52.1) - do you still use 1.38.0 and need a solution for the issue? Assigning P3 priority for now

**Comment by matthewstevenson88** [comment]
Closing this because (a) it is likely that the root cause is an old OpenSSL library that only supports NPN and not ALPN, (b) the `TSI_OPENSSL_ALPN_SUPPORT` macro is an internal implementation detail and it should not be set by users, and (c) no response that this is still an issue when updating to more recent versions.
