### ISSUE TITLE
grpc compilation error error: no matching function for call to StrFormat

### ISSUE THREAD

**Issue by santoojoshi** [grpc/grpc#26163]
grpc version: Release v1.37.1
OS:CentOS Linux release 7.8.2003 (Core)
gcc version: 5.4.0
cmake version 3.12.3

when i run
mkdir -p cmake/build
cd cmake/build
cmake ../.. -DBUILD_SHARED_LIBS=ON -DgRPC_INSTALL=ON
make

[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/alloc.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/atm.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_iphone.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_linux.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_posix.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_windows.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/env_linux.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/env_posix.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/env_windows.cc.o
[ 19%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/log.cc.o
[ 20%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/log_android.cc.o
[ 20%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/log_linux.cc.o
/root/MRCP/google_STT_Plugin/grpc/src/core/lib/gpr/log_linux.cc: In function \u2018void gpr_default_log(gpr_log_func_args*)\u2019:
/root/MRCP/google_STT_Plugin/grpc/src/core/lib/gpr/log_linux.cc:97:62: error: no matching function for call to \u2018StrFormat(const char [22], const char*, char [64], int32_t&, long int&, const char*&, int&)\u2019
       time_buffer, now.tv_nsec, tid, display_file, args->line);
                                                              ^
/root/MRCP/google_STT_Plugin/grpc/src/core/lib/gpr/log_linux.cc:97:62: note: candidate is:
In file included from /root/MRCP/google_STT_Plugin/grpc/src/core/lib/gpr/log_linux.cc:44:0:
/root/MRCP/google_STT_Plugin/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
/root/MRCP/google_STT_Plugin/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
/root/MRCP/google_STT_Plugin/grpc/src/core/lib/gpr/log_linux.cc:97:62: note:   mismatched types \u2018absl::lts_2020_09_23::FormatSpec<Args ...>\u2019 and \u2018const char [22]\u2019
       time_buffer, now.tv_nsec, tid, display_file, args->line);
                                                              ^
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/log_linux.cc.o] Error 1
make[1]: *** [CMakeFiles/gpr.dir/all] Error 2
make: *** [all] Error 2

**Comment by veblush** [comment]
I guess it's related to https://github.com/abseil/abseil-cpp/issues/858 which is caused by the old gcc. You said that it uses gcc 5.4 so can you verify it's 5.4. If so, how did you install it?
