### ISSUE TITLE
client can't connect server when upgrade grpc version.

### ISSUE THREAD

**Issue by PIAOTJ** [grpc/grpc#26173]
hello!

we use grpc server and client.

client use v1.20.0 and we want upgrade version to 1.37.0 or newer.

when upgrade client grpc version, client(ubuntu 16.04, 18.04, centos 7 with gcc 8.x) does not work normally.

client try CompletionQueue::Next(void ** tag, boo *ok), but occurs segmentation faults or some versions not proceed next.

I have a few questions, so I would appreciate your answer.

server info. / grpc 1.23.3 / centos 7.2

1. grpc 1.20.0, 1.23.1 is work well. but i tested 1.31.0, 1.32.0, 1.34.1, 37.0 all not working.

   same source, same enviroment, but only change grpc version, can not work?

2. can client grpc version higher than server grpc version?

3. if client grpc version can higher than server grpc version, 

   there any known bugs on CompletionQueue::Next(void ** tag, boo *ok)?

thanks!

**Comment by yashykt** [comment]
@veblush 
This certainly seems weird. Esun, did certain environments stop being supported?

**Comment by PIAOTJ** [comment]
> @veblush
> This certainly seems weird. Esun, did certain environments stop being supported?

Hello. we update dev server version, now running v1.3.3 based nodejs server.

still not working..

**Comment by veblush** [comment]
@PIAOTJ Sorry for the late reply. Those environment should work. Can you put the callstack when it ran into a segfault. If possible, please share us with a small reproduction case?
