### ISSUE TITLE
i have got Error installing BoringSSL-GRPC

### ISSUE THREAD

**Issue by ronitP12** [grpc/grpc#26174]
### What operating system (Linux, Windows,...) and version?
Mac catelina 10.15.7 version 

### What did you do?
i have created pod file and installed using terminal
### What did you expect to see?
install successfully 

below i attached my log of terminal for error in details.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
![Screen Shot 2021-05-05 at 1 27 46 PM](https://user-images.githubusercontent.com/83056717/117112224-5ceacc00-ada6-11eb-9238-fa9d660d71da.png)
i have project in flutter and installed pods in ios runner folder

**Comment by yulin-liang** [comment]
Can you share your pod file with me?

**Comment by ronitP12** [comment]
i am using flutter yaml file, if you like to see the dependencies , than i can send that list

**Comment by yulin-liang** [comment]
There's a separate repo for gRPC-Dart((https://github.com/grpc/grpc-dart)), I think your issue should be posted on that repo.

**Comment by ronitP12** [comment]
ohk i will check and try that pods

**Comment by yulin-liang** [comment]
Close this issue for now.
