### ISSUE TITLE
Impact of GRPC tracing on the throughput of server

### ISSUE THREAD

**Issue by amanand** [grpc/grpc#26171]
### What version of gRPC and what language are you using?
1.18

### What operating system (Linux, Windows,...) and version?
Freebsd11

### What runtime / compiler are you using (e.g. python version or version of gcc)
llvm 3.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
No impact on the grpc server performance when tracing is enabled.

### What did you see instead?
On one of the customer setups, we are seeing that the throughput seems to dip and the TCP send queue piles up when the grpc tracing is enabled with GRPC verbosity set to debug.
I think there may not be any correlation with the TCP sendQ and grpc tracing, if at all it will lead to slower writing into the TCP socket by the server, is that correct? 
If not, what are the impacts on the grpc server throughput if the setting the grpc tracing is on?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
gRPC logging especially in the tcp layer has been known to slow down the system. With debug mode and huge messages, you can imagine that logging those messages would take especially long. I think it makes sense to enable such extreme logging when debugging but not otherwise.
