### ISSUE TITLE
C# WaitForReady is hard to set for a gRPC call

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#26185]
`CallOptions` has a `WaitForReady` value and a fluent method for setting it to true. However, there is no option to set it to true on the CallOptions constructor.

Getter property:
https://github.com/grpc/grpc/blob/7125bbe5a564e30ad63c4f19bed89e7676cb7c29/src/csharp/Grpc.Core.Api/CallOptions.cs#L114-L122
Set method:
https://github.com/grpc/grpc/blob/7125bbe5a564e30ad63c4f19bed89e7676cb7c29/src/csharp/Grpc.Core.Api/CallOptions.cs#L204-L216
Ctor: (no option for wait for ready)
https://github.com/grpc/grpc/blob/7125bbe5a564e30ad63c4f19bed89e7676cb7c29/src/csharp/Grpc.Core.Api/CallOptions.cs#L39-L58

Also, there is no option for WaitForReady in gRPC generated code:
https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/csharp/Grpc.IntegrationTesting/TestGrpc.cs#L289-L300

Setting it to true requires code like:
```cs
new CallOptions(deadline: DateTime.UtcNow.AddSeconds(5)).WithWaitForReady()
```

**Comment by JamesNK** [comment]
@jtattermusch Thoughts on this?

To avoid breaking changes I think a new constructor would need to be added to CallOptions and a new overload generated by Grpc.Tools.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/26407
