### ISSUE TITLE
use static lib in qt can not find def

### ISSUE THREAD

**Issue by gongwk** [grpc/grpc#26209]
after complie grpc in c++
i use static lib in qt，but when i build the project，the gcc output Info tell me some undefined reference

configure in pro
unix{
    INCLUDEPATH += $(GRPC_INC_DIR)
    LIBS += -L$(GRPC_LIB_DIR) \
    -lcares \
    -lcrypto \
    -lgrpc \
    -lgrpc++ \
    -lgrpc++_alts \
    -lgrpc++_error_details \
    -lgrpc_plugin_support \
    -lgrpc++_reflection \
    -lgrpc_unsecure \
    -lgrpc++_unsecure \
    -laddress_sorting \
    -lgpr \
    -lre2 \
    -lssl \
    -lupb \
    -lz \
    -ldl

    LIBS += -L$(GRPC_LIB64_DIR)  \
    -labsl_debugging_internal \
    -labsl_strerror\
    -labsl_str_format_internal\
    -labsl_strings\
    -labsl_strings_internal\
    -labsl_synchronization\
    -labsl_stacktrace\
    -labsl_bad_any_cast_impl\
    -labsl_bad_optional_access\
    -labsl_bad_variant_access\
    -labsl_base\
    -labsl_city\
    -labsl_civil_time\
    -labsl_cord\
    -labsl_demangle_internal\
    -labsl_examine_stack\
    -labsl_exponential_biased\
    -labsl_failure_signal_handler\
    -labsl_flags\
    -labsl_flags_commandlineflag\
    -labsl_flags_commandlineflag_internal\
    -labsl_flags_config\
    -labsl_flags_internal\
    -labsl_flags_marshalling\
    -labsl_flags_parse\
    -labsl_flags_private_handle_accessor\
    -labsl_flags_program_name\
    -labsl_flags_reflection\
    -labsl_flags_usage\
    -labsl_flags_usage_internal\
    -labsl_graphcycles_internal\
    -labsl_hash\
    -labsl_hashtablez_sampler\
    -labsl_int128\
    -labsl_leak_check\
    -labsl_leak_check_disable\
    -labsl_log_severity\
    -labsl_malloc_internal\
    -labsl_periodic_sampler\
    -labsl_random_distributions\
    -labsl_random_internal_distribution_test_util\
    -labsl_random_internal_platform\
    -labsl_random_internal_pool_urbg\
    -labsl_random_internal_randen\
    -labsl_random_internal_randen_hwaes\
    -labsl_random_internal_randen_hwaes_impl\
    -labsl_random_internal_randen_slow\
    -labsl_random_internal_seed_material\
    -labsl_random_seed_gen_exception\
    -labsl_random_seed_sequences\
    -labsl_raw_hash_set\
    -labsl_raw_logging_internal\
    -labsl_scoped_set_env\
    -labsl_spinlock_wait\
    -labsl_status\
    -labsl_statusor\
    -labsl_symbolize\
    -labsl_throw_delegate\
    -labsl_time\
    -labsl_time_zone\
    -labsl_wyhash\
    -lcares\
    -lprotobuf\
    -lprotobuf-lite \
    -lprotoc\
    -lre2
}
![image](https://user-images.githubusercontent.com/14072360/117529783-35953880-b00c-11eb-8428-0ab1741de2d4.png)
How can I slove this problem?
I also try to (ar x) all the static lib to .o file, and repack all the .o file in one static lib, but when i build the project, it still tell me undefined reference

**Comment by gongwk** [comment]
solved

**Comment by only-test-linux** [comment]
@gongwk I also encountered this problem, can I teach the solution?

**Comment by only-test-linux** [comment]
QMAKE_CXXFLAGS += pkg-config --cflags= protobuf grpc
QMAKE_CXXFLAGS += -std=c++11
QMAKE_LIBS += pkg-config --libs= protobuf grpc++ -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl

**Comment by seyedmmousavi** [comment]
> QMAKE_CXXFLAGS += pkg-config --cflags= protobuf grpc
> QMAKE_CXXFLAGS += -std=c++11
> QMAKE_LIBS += pkg-config --libs= protobuf grpc++ -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl

doesn't works. is there any missing character?

**Comment by seyedmmousavi** [comment]
> solved

how it solved?
