### ISSUE TITLE
Python package cannot be built on current macOS

### ISSUE THREAD

**Issue by niklasb** [grpc/grpc#26218]
### What version of gRPC and what language are you using?

This refers to current master branch (8bdbb74425d6ac13ea7823be41e9297fddd629aa)

The current release version on PyPI (1.37.1) has the same issue.

### What operating system (Linux, Windows,...) and version?

* macOS 11.2.3, Intel MacBook Pro
* macOS 11.2, M1 MacBook Pro

### What runtime / compiler are you using (e.g. python version or version of gcc)

Intel:

Python 3.8.7 (default, Feb  3 2021, 07:09:08)
Apple clang version 12.0.5 (clang-1205.0.22.9)

M1:

Python 3.8.2 (default, Apr 8 2021, 23:19:18)
Apple clang version 12.0.5 (clang-1205.0.22.9)

### What did you do?

To reproduce with PyPI package (`--no-binary grpcio` is not necessary on M1 since no binary is available anyways):

```
$ pip3 install --no-binary grpcio grpcio |& tee /tmp/test.log
```

To reproduce with git master:

```
$ git clone https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init --recursive
$ python3 setup.py install |& tee /tmp/test.log
```

From log:

```
$ less /tmp/test.log
...
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_darwin -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/tcl-tk/include -I/Users/niklas/Library/Caches/pypoetry/virtualenvs/web-backend-vC4WLAE0-py3.8/include -I/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c third_party/boringssl-with-bazel/mac-x86_64/crypto/fipsmodule/rsaz-avx2.S -o python_build/temp.macosx-11-x86_64-3.8/third_party/boringssl-with-bazel/mac-x86_64/crypto/fipsmodule/rsaz-avx2.o -std=c++11 -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
third_party/zlib/gzlib.c:252:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
        ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:252:9: note: did you mean 'fseek'?
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:162:6: note: 'fseek' declared here
int      fseek(FILE *, long, int);
         ^
third_party/zlib/gzlib.c:258:24: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:359:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
        ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:400:15: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
              ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:496:14: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    offset = LSEEK(state->fd, 0, SEEK_CUR);
             ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
5 errors generated.
...
```

### What did you expect to see?

I expected that [this patch](https://github.com/grpc/grpc/commit/d70355ceddbf2fef93249b29e620065f51d0a6df) would have solved the issue

### What did you see instead?

See compilation errors above

**Comment by lidizheng** [comment]
Have you updated the submodules?

```sh
git submodule update --init
```

**Comment by niklasb** [comment]
@lidizheng  I have, yes, just retested the repro from above with `git submodule update --init --recursive`.

Also note this also happens when installing from PyPI (version 1.38.0, when no binary package is used)

**Comment by niklasb** [comment]
I'll retest on macOS 11.4 after I update this machine

**Comment by lidizheng** [comment]
@niklasb You already tested the patch you mentioned in the description, and yet it doesn't work. Can you paste the new compiler complaints for `v1.38.0` source wheel build?

Also, does binary wheel work for you? Can you share more info why you want to build from source?

**Comment by niklasb** [comment]
@lidizheng I addressed all of those questions in the updated report:

1. yes, it happens on latest git HEAD which does include d70355ceddbf2fef93249b29e620065f51d0a6df, see the report for repro. So d70355ceddbf2fef93249b29e620065f51d0a6df does not fix this
2. the compiler errors are always the same, and they are included in the report
3. of course binary wheel works, but it's not available for arm64 architecture (M1 MacBook)

**Comment by lidizheng** [comment]
@niklasb I don't have an M1 Mac. Can you try out if this PR fixed the problem https://github.com/grpc/grpc/pull/26374? The patch you mentioned forgot to update Python flags.

**Comment by niklasb** [comment]
@lidizheng I can't test on the M1 right now but it builds fine on Intel macOS so I assume it's a good fix :)
