### ISSUE TITLE
help for grpc_python_plugin not installed with pip install

### ISSUE THREAD

**Issue by iamnoah** [grpc/grpc#26210]
I would just comment on #15675 if it were not locked, but just wanted to point out there is an easy solution for those looking for a binary for the python gRPC plugin:

```shell
pip install grpclib protobuf
```

The plugin binary is then available as `protoc-gen-grpclib_python` or  `protoc-gen-python_grpc` in the bin/ directory for your python env. (If you are using buf, it can be used as `name: python_grpc` or `name: grpclib_python`.)

**Comment by yashykt** [comment]
Thanks for the comment!

**Comment by morapet** [comment]
the two generators does not seems to generate same code grpc vs grpclib seems to generate different code, mainly with regard to back-end and streaming
