### ISSUE TITLE
gRPC response from server back to client loses data it seems

### ISSUE THREAD

**Issue by mdable2** [grpc/grpc#26217]
### What version of gRPC and what language are you using?
grpcio==1.37.0
python

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.8 64-bit

### What did you do?
I have a simple gRPC client and server where I make a call to the server and expect a certain response. 

The relevant code snippets are below for reproducibility:

Proto
```
enum DetectionClass {
    NONE = 0;
    STAMP = 1; 
    SIGNATURE = 2;
}
message SignatureResponseObject {
    float min_x = 1;
    float min_y = 2;
    float max_y = 3;
    float max_x = 4;
    DetectionClass detection_class = 5;
    float detection_score = 6;
}
message SignatureResponse {
    repeated SignatureResponseObject signatures = 1;
}
service SignatureService {
    rpc FindSignatures(SignatureRequest) returns (SignatureResponse);
}
```
Client
```
client = example_pb2_grpc.SignatureServiceStub(channel)
request = example_pb2.SignatureRequest(
        image=byte_image   
        )

response = client.FindSignatures(request=request)

print(response)
```
Server
```
signature_response_object.detection_class = vision_pb2.DetectionClass.SIGNATURE
signature_response_object.min_x=r.min_x
signature_response_object.min_y=r.min_y
signature_response_object.max_x=r.max_x
signature_response_object.max_y=r.max_y
signature_response_object.detection_score = r.score
signature_response.signatures.append(signature_response_object)
...
print(signature_response)
return signature_response
```
### What did you expect to see?
I expected the print statements in Client and Server to be the same.

### What did you see instead?
Print statement from Server:
```
signatures {
  min_x: 0.3274773359298706
  min_y: 0.7998588681221008
  max_y: 0.8861611485481262
  max_x: 0.573384702205658
  detection_class: SIGNATURE
  detection_score: 0.999962568283081
}
```
Print statement from Client:
```
signatures {
  detection_score: 0.8861611485481262
}
```
You can notice a few things:
1. The Client object only has detection_score instead of the expected 6 total fields.
2. The Client does not use the real detection score. It is replacing detection_score with max_y for some reason.

### Anything else we should know about your project / environment?
I changed some things around to try and fix this issue, but that seemed to create a slightly different bug/unexpected result. Original code can be seen in this question: https://stackoverflow.com/questions/67464388/why-does-my-grpc-response-contents-differ-on-server-vs-client which highlights a similar yet different problem.

**Comment by mdable2** [comment]
@nicolasnoble just wondering when you will have time to look at this. Thanks!

**Comment by mdable2** [comment]
I changed my response object back to this: 

```
message DetectionBoxes {
    float min_x = 1;
    float min_y = 2;
    float max_x = 3;
    float max_y = 4;
}
message SignatureResponseObject {
    DetectionBoxes detection_box = 1;
    DetectionClass detection_class = 2;
    float detection_score = 3;
}
message SignatureResponse {
    repeated SignatureResponseObject signatures = 1;
}

service SignatureService {
    rpc FindSignatures(SignatureRequest) returns (SignatureResponse);
}
```
And am intercepting the traffic sent over the wire:
```
{"message_origin":"server","raw_message":"Ch0KFA0cq6c+FY3DTD8dV8kSPyV122I/EAIdjP1/Pw==","message":{"1":{"1":{"1":0.32747734,"2":0.79985887,"3":0.5733847,"4":0.88616115},"2":"2","3":0.99996257}},"timestamp":"2021-05-14T09:26:58.179817682-05:00"}],"metadata":{":authority":["localhost:35961"],"accept-encoding":["identity,gzip"],"content-type":["application/grpc"],"grpc-accept-encoding":["identity,deflate,gzip"],"user-agent":["grpc-python/1.32.0 grpc-c/12.0.0 (linux; chttp2)"],"via":["HTTP/2.0 127.0.0.1:35961"]},"metadata_response_headers":{"accept-encoding":["identity,gzip"],"content-type":["application/grpc"],"grpc-accept-encoding":["identity,deflate,gzip"]},"metadata_response_trailers":{}}
```
Which looks correct to me. Very stumped on this and would love some guidance!

**Comment by lidizheng** [comment]
There are several possibility here:

1. The proto definition is different between client and server, maybe one of them is out of date;
2. The transmitted object is not the correct type, e.g., the server meant to send `SignatureResponse`, but actual send `SignatureResponseObject `.

ProtoBuf deserialization can be quite tolerant to faulty binary sequences, and yet there isn't a way to verify what type of message is being sent (because schema is not part of the wire protocol).
