### ISSUE TITLE
Python server-side interceptors have direct access to request/response objects

### ISSUE THREAD

**Issue by pikachu** [grpc/grpc#26229]
Currently, python server-side implementations don't have direct access to the request and response objects. There are third party libs like this (https://github.com/d5h-foss/grpc-interceptor), but I'm wondering why we don't build this into the core lib if it works.

I see the explanation:

> To provide more granular interceptor functionality (see semantic comparison section below), the implementation would have to wrap over low-level C-Core APIs like startBatch, which sends batches of gRPC operations into C-Core. The potential amount of work is much more considerable than expected, it might require to refactor abstractions of gRPC or have hacky injections of logic.

in the history section here (https://github.com/grpc/proposal/blob/master/L13-python-interceptors.md). 

Could the core lib implement it in the way the third-party lib implemented it?

**Comment by lidizheng** [comment]
Good to learn there is a decent third party server-side interceptor library. We currently doesn't have the manpower to implement the improved version of server-side interceptor. We really need help on this subject, contributions are always welcome :)
