### ISSUE TITLE
Cannot make on CentOS 7.7?

### ISSUE THREAD

**Issue by alindada** [grpc/grpc#26224]
[MAKE]    Generating cache.mk
[CXX]     Compiling src/core/lib/gpr/log_linux.cc
src/core/lib/gpr/log_linux.cc: 在函数‘void gpr_default_log(gpr_log_func_args*)’中:
src/core/lib/gpr/log_linux.cc:97:62: 错误：对‘StrFormat(const char [22], const char*, char [64], int32_t&, long int&, const char*&, int&)’的调用没有匹配的函数
       time_buffer, now.tv_nsec, tid, display_file, args->line);
                                                              ^
src/core/lib/gpr/log_linux.cc:97:62: 附注：备选是：
In file included from src/core/lib/gpr/log_linux.cc:44:0:
third_party/abseil-cpp/absl/strings/str_format.h:338:34: 附注：template<class ... Args> std::string absl::lts_20210324::StrFormat(absl::lts_20210324::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
third_party/abseil-cpp/absl/strings/str_format.h:338:34: 附注：  template argument deduction/substitution failed:
src/core/lib/gpr/log_linux.cc:97:62: 附注：  mismatched types ‘absl::lts_20210324::FormatSpec<Args ...>’ and ‘const char [22]’
       time_buffer, now.tv_nsec, tid, display_file, args->line);
                                                              ^
In file included from third_party/abseil-cpp/absl/strings/str_format.h:76:0,
                 from src/core/lib/gpr/log_linux.cc:44:
third_party/abseil-cpp/absl/strings/internal/str_format/arg.h: In instantiation of ‘constexpr absl::lts_20210324::FormatConversionCharSet absl::lts_20210324::str_format_internal::ArgumentToConv() [with Arg = int]’:
third_party/abseil-cpp/absl/strings/internal/str_format/arg.h:465:9:   required from ‘static bool absl::lts_20210324::str_format_internal::FormatArgImpl::Dispatch(absl::lts_20210324::str_format_internal::FormatArgImpl::Data, absl::lts_20210324::str_format_internal::FormatConversionSpecImpl, void*) [with T = int]’
third_party/abseil-cpp/absl/strings/internal/str_format/arg.h:419:17:   required from ‘void absl::lts_20210324::str_format_internal::FormatArgImpl::Init(const T&) [with T = int]’
third_party/abseil-cpp/absl/strings/internal/str_format/arg.h:369:5:   required from ‘absl::lts_20210324::str_format_internal::FormatArgImpl::FormatArgImpl(const T&) [with T = int]’
third_party/abseil-cpp/absl/strings/internal/str_format/bind.h:171:48:   required from here
third_party/abseil-cpp/absl/strings/internal/str_format/arg.h:300:46: 警告：成员‘absl::lts_20210324::str_format_internal::ArgConvertResult<(absl::lts_20210324::FormatConversionCharSet)131067u>::value’缺少初始值设定 [-Wmissing-field-initializers]
           std::declval<FormatSinkImpl*>())){});
                                              ^
make: *** [/home/infile/grpcnew/objs/opt/src/core/lib/gpr/log_linux.o] 错误 1

**Comment by SchrodingerZhu** [comment]
gcc was too old. compiled on centos with gcc 7.

**Comment by yashykt** [comment]
Considering this solved
