### ISSUE TITLE
grpc async server should support outbound grpc calls

### ISSUE THREAD

**Issue by ajay516** [grpc/grpc#26231]
### Is your feature request related to a problem? Please describe.
I have grpc async server where service handler makes outbound grpc call. When this happens the server hangs (stack trace points to poll). When I use grpc sync server that makes outbound grpc call - call returns. I have modified example code of `examples/cpp/helloworld` folder and able to reproduce it, gist: https://gist.github.com/ajay516/2cf511f6456592371e7c905b9eea85b2

### Describe the solution you'd like
This seems to one of trivial use-case in server side. There should be documentation on how to modify the service to make it work. Better yet, have section in examples folder to demonstrate working use-case.

### Describe alternatives you've considered
I tried having a separate thread to poll `CompletionQueue` that doesn't work as well.

### Additional context
Add any other context about the feature request here.

**Comment by yashykt** [comment]
You seem to be making a synchronous call from the CQ handling thread which effectively means that there is no thread polling the completion queue for the server leading to no progress.

I would suggest increasing the number of threads and completion queues for the server and also using the async API for making the call. That would avoid blocking the completion queue servicing threads.

**Comment by yashykt** [comment]
I also hear your comments on examples. A lot of our test code some times double as examples, especially for cases where we want a process to act as both - a server and a client.
