### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [grpc/grpc#26260]
How can I add the grpc customer in ibevent?

**Comment by jtattermusch** [comment]
The "new issue" form clearly asks users not to post questions as github issues. Next time please follow the instructions and use the channels mentioned below to ask questions.

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
>
