### ISSUE TITLE
Linking the C++ interop server requires gtest to be installed.

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2626]
This is with `make CONFIG=dbg`. Is it intended? If not, is it avoidable?

**Comment by yang-g** [comment]
I think for anything c++ in build.json with build = "test", the makefile template will try to link gtest. The interop server itself may not need to depend on gtest. Is there a big problem?

**Comment by jcanizales** [comment]
Not a big deal, just unexpected for testing iOS.

**Comment by dgquintas** [comment]
Obsolete?

**Comment by jcanizales** [comment]
Not obsolete, it's still the case. But not worth of much trouble either.

**Comment by vjpai** [comment]
Closing this under the guise of "not worth of much trouble" . Let's call this WAI.
