### ISSUE TITLE
Promote C++ Interceptor to non-experimental status

### ISSUE THREAD

**Issue by drigz** [grpc/grpc#26336]
The C++ Interceptor API has been marked as experimental since it was added in 2018. [In 2019](https://github.com/grpc/grpc/issues/9035#issuecomment-496682530), vjpai said:

> It is indeed implemented under experimental with a hope of moving this to non-experimental in the near future.

### Describe the solution you'd like
Either the API should be promoted, or the current status should be documented so that users can decide whether or not to use the API in its current form. For me, it would suffice to prioritize or deprioritize this issue to indicate whether the feature currently has an owner or not.

### Additional context
https://github.com/grpc/grpc/issues/9035

**Comment by drigz** [comment]
One comment on the current API: I'm surprised that it defines SetInterceptorCreators() and not AddInterceptorCreator(), which would align better with the rest of the ServerBuilder API (AddChannelArgument), and would save the user from initializing a vector to add a single interceptor. (`AddInterceptorCreator(std::move(interceptor))` instead of `std::vector<...> c; c.push_back(interceptor); SetInterceptorCreators(std::move(c))`)

**Comment by ctiller** [comment]
I wonder if it's worth trying to gather some user feedback, and do a lap of
efficiency of implementation review soon to try and make a measured choice
here?

**Comment by veblush** [comment]
@yashykt and @vjpai Could you take a look at this? (I added you here because you're in the past thread)

**Comment by vjpai** [comment]
I think we have a lot of good use of the client interceptor and should probably mark that non-experimental. Which would require @yashykt to write a gRFC for that.

We really don't have substantial use of the server interceptor. I think I only know of 1-2 users who are just doing non-intrusive logging. @ejona86 has raised serious concerns about the capabilities of our current server interceptor model in C++. I think we should not mark the server interceptor non-experimental until we have more usage and maybe have had a discussion to iron out those concerns.

**Comment by vjpai** [comment]
Wrt comment https://github.com/grpc/grpc/issues/26336#issuecomment-845922868, we don't provide an AddInterceptorCreator because interceptor stack implementers typically want their interceptors to run in a specific order. So we leave it up to the interceptor factories to decide that order. This is different from ServerBuilder where each Add method is just setting some other independent parameter of the server.
