### ISSUE TITLE
GRPC causing core dumps when interacting with Google Cloud PubSub

### ISSUE THREAD

**Issue by sriedel** [grpc/grpc#26333]
[grpc_crash_logs.txt](https://github.com/grpc/grpc/files/6537101/grpc_crash_logs.txt)

### What version of gRPC and what language are you using?
Ruby 2.7.2, gPRC gem version 1.37.1.
grpc 1.28.0 is the last stable version, that does not cause the ruby interpreter to dump core.

### What operating system (Linux, Windows,...) and version?
Running in a docker container using Linux, Ubuntu 20.04.01 LTS as a guest system.

### What runtime / compiler are you using (e.g. python version or version of gcc) 
gcc 9.3.0

### What did you do?
Deployed a ruby web application that interacts with google cloud pubsub to google cloud. 

### What did you expect to see?
The application running as expected as with grpc gem versions 1.28.0 and below.

### What did you see instead?
The ruby interpreter is dumping core as soon as it tries to communicate with google cloud pubsub.

The crash logs are quite lengthly (~3000 lines, 290kb uncompressed). Do you have a preferred fashion in which large log files can be provided to you?

**Comment by veblush** [comment]
@sriedel Thank you for the issue and you should be able to attach the file in the issue. ([ref](https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/file-attachments-on-issues-and-pull-requests#:~:text=To%20attach%20a%20file%20to,images%20directly%20into%20the%20box.))

**Comment by sriedel** [comment]
@veblush Ah, thanks for the pointer, I was not aware that attachments are possible now.

I've updated the ticket description with the file. If you need any further information, please let me know.

**Comment by sriedel** [comment]
The LD_PRELOAD workaround mentioned in #25450 works here as well; maybe the underlying cause is the same.

**Comment by HannahShiSFB** [comment]
This is for an environment has mixed use of glibc malloc and jemalloc, as a result the standard allocation APIs (e.g. malloc, free, etc.) point to glibc malloc functions but the non-standard ones (e.g. mallocx, sdallocx, etc.) point to jemalloc functions.

google/boringssl pushed https://boringssl-review.googlesource.com/c/boringssl/+/48885 to fix this issue.

**Comment by alto-ruby** [comment]
boring ssl upgraded, close by assuming fixed. If this still happens, feel free to reopen or open a new one.
