### ISSUE TITLE
Don't crash if protocol buffer serialization or deserialization errors

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#2634]
Error codes generated in python wrapping code should comply with the spec in "gRPC Error Normalization" spreadsheet.

**Comment by nathanielmanistaatgoogle** [comment]
We're way out of compliance, but I've added a "Python" column for the time being describing what we surface.

Retitling this issue to reflect the work to be done bringing us to conformance.

**Comment by jayantkolhe** [comment]
anything missing here?

**Comment by nathanielmanistaatgoogle** [comment]
The important parts of this are fixed as of 1d750d6ca2d878385e4a.

I think we would still have a problem if there's a serialization or deserialization error for protocol buffer objects, but that's deferrable.

**Comment by nathanielmanistaatgoogle** [comment]
Fixed by recent GA changes.
