### ISSUE TITLE
Make grpc_channel_create_call accept NULL for host

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2635]
With recent URI target naming changes, it becomes difficult (if not impossible) for wrapped languages to determine the correct host string to pass to grpc_channel_create_call. 

Make the following architectural change to the client_config/client_channel systems:
- add a host field to grpc_client_config
- allow resolvers to set it
- make existing resolvers provide good host values based on input uri
- stash the host field in client_channel.c somewhere
- add it if no host is provided in initial metadata, add it based upon the value provided

During call creation, omit adding an authority header if host==NULL.

**Comment by jcanizales** [comment]
> it becomes difficult (if not impossible) for wrapped languages to determine the correct host string to pass to grpc_channel_create_call

In which cases, if any, will the `host` argument to `grpc_channel_call_create` need to be something different than `NULL`?

Currently, if the client needs to override the SSL target name for testing, that name also needs to be passed as `host` to `grpc_channel_call_create` for the handshake to succeed. Will that still be the case after this change?

**Comment by jcanizales** [comment]
Ping.

**Comment by ctiller** [comment]
Users will need to supply a host if:
- the core cannot determine it from the target passed to create channel
(this is a pluggable system, so we don't know with certainty when this
would arise)
- the user wants to access a different host than indicated by their target
string (ex: connect to database.google.com, access bigtable.google.com)

**Comment by jcanizales** [comment]
Does one still have to pass the SSL target name override to `grpc_channel_call_create` as host, or can the core determine it from the channel args?

I assume the core can always determine the host for channels created using DNS addresses?

**Comment by murgatroid99** [comment]
It looks like `grpc_channel_call_create` does not automatically pick up the SSL target name override. However, in any case where we need an SSL target name override, we can also pass the channel argument `grpc.default_authority` to avoid this problem.

**Comment by jcanizales** [comment]
Nice catch :) Craig, should the core do that automatically?

**Comment by ctiller** [comment]
I don't think so.

Although related, one of these features is strictly for testing (the SSL
override), while the other is normal behavior.
