### ISSUE TITLE
[question] Is it possible to dynamically change the type of service response?

### ISSUE THREAD

**Issue by tuhao1020** [grpc/grpc#26368]
```proto
message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string msg = 1;
}

message UniResponse {
  int32 code = 1;
  string message = 2;
  optional google.protobuf.Any data = 3;
}

service HelloService {
  rpc Greet(HelloRequest) returns (HelloResponse) {}
}
```
as the code above, `Greet` returns `HelloResponse`， I want all the service returns a type like `UniResponse` without midify the proto file, the `UniResponse` will wrap oringal response data into its data field ,  then success response and error response can keep the same structure. 

```go
func UnaryServerInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	m, err := handler(ctx, req)

        // wrap oringal response
	x := &pb.UniResponse{
		Code: 1001,
                Message: "",
		Data:  m,
	}
	return x, err
}
```
 I have tried server side interceptor，but it doesn't work. Are there
other ways to do this?

**Comment by stanley-cheung** [comment]
You can make use of the `oneof` feature of protobuf - basically a field can be "one of" a group of possible fields.

**Comment by tuhao1020** [comment]
@stanley-cheung  thanks for your suggestion!
```proto
message Hello1Response {
  string msg1 = 1;
}

message Hello2Response {
  string msg2 = 1;
}

message PossibleResponse {
  oneof fields  {
    Hello1Response  h1 = 1;
    Hello2Response  h2 = 2;
  }
}

message UniResponse {
  int32 code = 1;
  string message = 2;
  PossibleResponse data = 3;
}
```
I think I can change the return type to `UniResponse`,  but there is another trouble,  the return data may be like below:
```json
{
  "code": 1001,
  "message": "",
  "data": {
    "hello1Response": {
      "msg1": "hello"
    }
  }
}
```
what I expect is like this: 
```json
{
  "code": 1001,
  "message": "",
  "data": {
      "msg1": "hello"
  }
}
```

**Comment by tuhao1020** [comment]
@stanley-cheung I think I should use `google.protobuf.Struct` instead

**Comment by ccppoo** [comment]
you could use meta data like a header in response
