### ISSUE TITLE
Use NULL for default host in grpc_channel_call_create() in Python

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2636]
#2635 will introduce a mechanism whereby the default host can be correctly determined by core. Since this can (almost) never be correctly determined automatically by wrapped languages without massive code duplication, wrapped languages are encouraged to use this facility once it's available.

**Comment by nathanielmanistaatgoogle** [comment]
Does this mean that I needn't expose to applications any means of additionally setting the host? If I should still expose such a facility, should it be something that applications set on a stub at stub creation time or should it be settable per-RPC?

**Comment by ctiller** [comment]
You should still have a way of setting host - some servers we know of
require it to frequently change.

Generally, if creating stubs in your wrapping is cheap, exposing host
customization only at a stub level should be fine.
If creating stubs is expensive, you probably want a per-call override.

My view is that the host field is logically more closely tied to the stub
than a particular call, and we'll likely be moving to provide a stub-level
C++ override soon.

**Comment by soltanmm** [comment]
(taking this to change the wrapper to allow the string arg passed to `grpc_channel_create_call ` to be `NULL`, then will pass back to @nathanielmanistaatgoogle)

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed in 9e4d0610ea5e2bb3.
