### ISSUE TITLE
Provide a ruby native gem for aarch64 linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#26391]
gRPC ruby does build fine on aarch64 linux and the tests are passing there. 
The missing piece is that we currently don't provide pre-built package (=native gem) for aarch64 linux.

Context: for other languages we already provide cross-compiled packages for aarch64 linux, but ruby's build system is quite complicated so I'm not sure how to integrate cross-compilation with the existing native gem build.

**Comment by nicolasnoble** [comment]
This is technically an issue to file into rake compiler dock. This is where
the cross compiler needs to be added.

https://github.com/rake-compiler/rake-compiler-dock

**Comment by jtattermusch** [comment]
I filed https://github.com/rake-compiler/rake-compiler-dock/issues/47.

**Comment by jtattermusch** [comment]
would https://github.com/grpc/grpc/pull/25992 solve this? (without requiring to have ARM64 mac hardware)

**Comment by jtattermusch** [comment]
linux-aarch64 support has been added to rake-compiler-dock in https://github.com/rake-compiler/rake-compiler-dock/pull/54

**Comment by flavorjones** [comment]
Please note there hasn't been an official release of rake-compiler-dock with https://github.com/rake-compiler/rake-compiler-dock/pull/54 yet. I'll take the responsibility of submitting a PR to grpc once that's happened.

**Comment by j-manu** [comment]
@flavorjones raker-compiler-dock 1.2.0 has been released https://github.com/rake-compiler/rake-compiler-dock/issues/58#issuecomment-1005510139

**Comment by flavorjones** [comment]
@j-manu Ack. Focusing on getting Nokogiri precompiled with this version of rake-compiler-dock, then will tackle GRPC next.

**Comment by chadlwilson** [comment]
Did this one get stuck? Or forgotten? :-)

**Comment by flavorjones** [comment]
Definitely forgotten. I'm still happy to do the work on a PR to add support, but I honestly don't know if the project has test infrastructure to test aarch64-linux. Also I know @apolcyn has been digging into the Ruby builds, I'd like to get his confirmation that they're stable before venturing in.

**Comment by chadlwilson** [comment]
Hmm. Assuming it's all on GH Actions, I guess might need to do so (slowly) via QEMU or docker until https://github.com/actions/runner-images/issues/5631 is eventually done :(

**Comment by chadlwilson** [comment]
Perhaps worth noting that as a dependency of this project, protobufs doesn't have `aarch64-linux` builds [either](https://github.com/protocolbuffers/protobuf/issues/12144).

Having said that, the grpc compile takes a _lot_ longer ( and personally I am struggling to get it to be stable during a ruby `bundle install` on CentOS 9 inside a container - perhaps due to resource requirements, although am still experimenting.

**Comment by chattsm** [comment]
+1 for this!

We've spun up an aarch64 builder and are finding that it's spending most of its time compiling this gem, a pre-built native build for linux-aarch64 would cut drastically cut build times. 🙏
