### ISSUE TITLE
Validate content-type, grpc-timeout, *-bin headers (server-side)

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc#26401]
Per @ejona86 (https://github.com/grpc/grpc-go/pull/4491#discussion_r640131754):

> Java behavior:
>
> - Bad content-type. HTTP 415 with a text/plain error message. Also a gRPC status of INTERNAL with same error message
> - Bad grpc-timeout or bad -bin. Looks like Java throws an exception (from different spots) that should eventually turn into a RST_STREAM(INTERNAL). Not the greatest approach, but not the worst result

For (2), gracefully returning a gRPC status of INTERNAL sounds preferable.

Per @yashykt (https://github.com/grpc/grpc-go/pull/4491#discussion_r640167567):

> Core seems to just ignore it after logging a message -
> 1. https://github.com/grpc/grpc/blob/8bdbb74425d6ac13ea7823be41e9297fddd629aa/src/core/ext/filters/http/server/http_server_filter.cc#L250
> 2. https://github.com/grpc/grpc/blob/8bdbb74425d6ac13ea7823be41e9297fddd629aa/src/core/ext/transport/chttp2/transport/parsing.cc#L430

**Comment by yashykt** [comment]
This will be fixed soon-ish.. Not marking this triaged so I remember to close it down.

**Comment by yashykt** [comment]
This got fixed as part of the recent hpack related cve fixes https://github.com/grpc/grpc/pull/33005 I believe
