### ISSUE TITLE
Unable to create a Unix file socket.

### ISSUE THREAD

**Issue by afeick** [grpc/grpc#26421]
I'm trying to use gRPC for inter-process communication for a project on MacOS, but I ran into an issue creating a unix style file socket with the Objective-C gRPC library. I'm able to create socket in the C++ server project using the address `"unix:/tmp/socket-test"`.  Unfortunately that same address fails on the Objective-C client because the following code is rewriting that address to `"unix:443"`

https://github.com/grpc/grpc/blob/bb994526ba4e92ca293d1c7ad68f52e8f676c638/src/objective-c/GRPCClient/private/GRPCCore/GRPCChannelPool.m#L228-L232

That code was added by @muxi as a [bug fix](https://github.com/grpc/grpc/pull/17683), so it obviously needs to be there in some form.

Does anyone have suggestions for a workaround, an alternative way of creating a file socket, or a way to fix the trailing slashes without breaking unix file sockets?

**Comment by dennycd** [comment]
issue fixed via PR https://github.com/grpc/grpc/pull/26931
