### ISSUE TITLE
Use NULL for default host in grpc_channel_call_create() in Objective-C

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2642]
#2635 will introduce a mechanism whereby the default host can be correctly determined by core. Since this can (almost) never be correctly determined automatically by wrapped languages without massive code duplication, wrapped languages are encouraged to use this facility once it's available.

**Comment by jcanizales** [comment]
Note: see https://github.com/grpc/grpc/issues/2635#issuecomment-127335134 for what we should do with SSL name overrides.

**Comment by jcanizales** [comment]
@jayantkolhe This has no effect on the API surface; there's no reason for it to be Beta.

**Comment by murgatroid99** [comment]
This could change the surface. We can pass NULL as the default host, but we also should have a way to set a different host on a per-call basis.

**Comment by jcanizales** [comment]
> we also should have a way to set a different host on a per-call basis.

Well that's a different feature request; you can't do it today either. It's pretty rare to want to do it from a mobile device though (I've asked and only heard of a use case inside proxies, and without details), so I'm positive we can do it additively if we decide to.

**Comment by jcanizales** [comment]
Fixed by #6906.
