### ISSUE TITLE
retries in client

### ISSUE THREAD

**Issue by litaohe** [grpc/grpc#26437]
Hi,
We used grpc++ in our project and everything works well such as load balance. But when I decide to enable the client 's request retry mechanism when a host is shutdown some thing went wrong: rpc method returns error code "14" with message such as "Socket closed" , but I am sure there are several other nodes that can work, It seems that the retry mechanism is not working. I am not sure if it is a usage error or a grpc‘s bug. Can somebody tell me why or how to enable retries correctly? thanks a lot!

            std::shared_ptr<grpc::Channel> channel;
            grpc::ChannelArguments args;
            args.SetLoadBalancingPolicyName("round_robin");
            args.SetInt(GRPC_ARG_ENABLE_RETRIES, 1); // enable 
            std::vector<std::unique_ptr<grpc::experimental::ClientInterceptorFactoryInterface>> creators;
            creators.push_back(std::unique_ptr<grpc::experimental::ClientInterceptorFactoryInterface>(new ClientInterceptorFactory(this,"test-svc")));
            channel = grpc::experimental::CreateCustomChannelWithInterceptors(strHosts, grpc::InsecureChannelCredentials(), args, std::move(creators));

            auto stub = ProtoService::NewStub(channel);
            stub->SayHello(......); // error : Socket closed

**Comment by markdroth** [comment]
Transparent retries are not yet implemented in C++.  Even the configurable retry code is not quite ready to be enabled by default yet (which is why `GRPC_ARG_ENABLE_RETRIES` is still off by default).  But if you want to try it out, you can inject a service config that configures retries based on the status code for particular RPC methods.

For details, see https://github.com/grpc/proposal/blob/master/A6-client-retries.md.

**Comment by litaohe** [comment]
@markdroth Thanks for your reply, I will try the method you provided.

**Comment by LiChengZiMu** [comment]
> @markdroth Thanks for your reply, I will try the method you provided.

I encounter the same problem,  do you solve it? Thanks

**Comment by markdroth** [comment]
Transparent retries were implemented in gRPC 1.45, so if the RPC is retriable, that should happen automatically if you upgrade to that version.
