### ISSUE TITLE
C# code generation - add option to change generated classes access modifier to internal

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [grpc/grpc#26453]
### Is your feature request related to a problem? Please describe.
When writing tests, I often have to add reference to the projects under test, sometimes both client and server of a Grpc service are needed. This cause annoying problem as generated messages and services are duplicated in both projects, and cannot be used easily in test code.

### Describe the solution you'd like
Add an option to generate classes as internal will alleviate this problem. 
`<Protobuf Access="internal" Include="..\..\proto\greeter.proto" Link="proto\greeter.proto" />`

**Comment by jtattermusch** [comment]
The `Access="internal"` option already exists AFAICT. 
https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#protobuf-item-metadata-reference

If needed, you could also use the `AdditionalProtocArguments` option to specify any other cmdline options needed.

Also, for generated code, it's best to have a separate class library that has all the generated code (and <Protobuf> items in its .csproj) and other projects in your solution simply reference that shared class library.
