### ISSUE TITLE
Fails to compile helloworld example

### ISSUE THREAD

**Issue by ghamarian** [grpc/grpc#26459]
### What version of gRPC and what language are you using?
protobuf:x64-osx                                   3.15.8#1
grpc:x64-osx                                       1.37.0#2

### What operating system (Linux, Windows,...) and version?
OSX, Catalina

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 12.0.0 (clang-1200.0.32.29)

### What did you do?
Followed the instructions, except that I use vcpkg for the dependencies:
 cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR ../..  -DCMAKE_TOOLCHAIN_FILE=/Users/amir/projects/github-code/vcpkg/scripts/buildsystems/vcpkg.cmake

### What did you expect to see?
Compilation successfully finishes

### What did you see instead?
```
[ 72%] Building CXX object CMakeFiles/greeter_callback_client.dir/greeter_callback_client.cc.o
/Users/amir/projects/github-code/grpc/examples/cpp/helloworld/greeter_callback_client.cc:64:12: error: no member named 'async' in 'helloworld::Greeter::Stub'
    stub_->async()->SayHello(&context, &request, &reply,
    ~~~~~  ^
```

**Comment by leikang123** [comment]
I also failed to compile, but I don’t know where

**Comment by drfloob** [comment]
I see that [vcpkg's port](https://github.com/microsoft/vcpkg/blob/master/ports/grpc/portfile.cmake#L8) is based on the gRPC 1.37 release, and the C++ Callback API was moved out of the experimental namespace after the 1.37 branch was cut (8aff94558c7). You might be compile incompatible code, and you could try checking out the v1.37 branch and build the hello world project again. If that fixes it, it's probably worth submitting a PR or filing an issue with the vcpkg team to update their gRPC port.

**Comment by ghamarian** [comment]
Thanks for the reply @drfloob, I confirm that it compiled with the 1.37 release. So I will create an issue for vcpkg. This can be closed.
