### ISSUE TITLE
Zstd compression 

### ISSUE THREAD

**Issue by rakeeb-hossain** [grpc/grpc#26460]
### Is your feature request related to a problem? Please describe.
My team ran into an issue with high CPU utilization when compressing request payloads with the Gzip core library. I added Zstd support in our own fork of gRPC which was a relatively painless process, and think this could be beneficial to other gRPC users. 

### Describe the solution you'd like
I would like to explore adding Zstd (and possibly other compression algorithms) to the gRPC core library. 

### Describe alternatives you've considered
Snappy is another possible codec that would be useful to add.

### Additional context
Just want to gauge feasibility/interest in this feature. Would be happy to try and tackle this myself.

**Comment by drfloob** [comment]
I appreciate the interest, Rakeeb! Similar discussions were had in https://github.com/grpc/grpc/pull/25708#issuecomment-797848237. To repeat briefly: adding support for other compression algorithms within gRPC-core would require coordination between multiple gRPC implementations (Java and Go at least), which isn't really feasible. This isn't an uncommon request, though! There may be value in adding support for user-defined compression mechanisms to the gRPC-core APIs, but that is a tougher job - API changes are not taken lightly, and we'd have to think carefully about how to support wrapped languages across multiple platforms.

**Comment by drfloob** [comment]
I'm curious what you think on this, @ctiller and @markdroth. You've seen more contributions like this than I have.

> Regarding supporting wrapped languages, does that refer to Obj-C, Ruby, PHP, and the other language folders in src, so registering a new core API change would require modifying each of these wrappers as well?

Yes, those are some of the wrapped languages, they use the C library under the hood. Depending on what we want to expose to each wrapped language, there may need to be changes in how the wrapped languages interface with the C-core library, and changes in each wrapped language's public API (say, if we wanted to add support for bringing your own compression library in native python, or alternatively if BYO compression options are only exposed to C and C++). I'm honestly not sure if there would be benefit in exposing hooks for custom compression mechanisms in wrapped languages, or if performance loss might negate any potential benefit from better compression algorithms. I think that'd need to be established, it might inform how we build this.

> Is it a possibility to incrementally add support to each of these languages, starting with just gRPC-core?

Sure, I think it should be possible, but this might need a discussion with the other language owners around whether we should go that route. If it's going to be a valuable feature in wrapped languages, we'll want to put some thought into building it with wrapped languages in mind.

> Would creating a gRFC proposal be a good starting point?

Maybe so. I think this would be a valuable endeavor, but I'm not sure how easy it would be to navigate an external contribution that needs to wrangle so many folks. I'll defer to mark & craig on the best way forward here.

**Comment by markdroth** [comment]
@ejona86 and @dfawley may want to weigh in here as well.  I think that if we did provide an API for pluggable compression algorithms, we'd need a cross-language design for what the semantics of that API should be.

I'm less concerned about wrapped languages (which all use C-core under the hood) and more concerned about Java and Go, which have their own implementations.

**Comment by ejona86** [comment]
Java [already has](https://grpc.github.io/grpc-java/javadoc/io/grpc/CompressorRegistry.html#register-io.grpc.Compressor-) [an API](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#decompressorRegistry-io.grpc.DecompressorRegistry-), [as does Go](https://pkg.go.dev/google.golang.org/grpc@v1.38.0/encoding#RegisterCompressor). Both are experimental. That said, I didn't want the Java API to begin with and I have no plans to stabilize it and get a bit sad when it is used. To my knowledge it is abused for non-compression things more often than to support alternative compression algorithms.

I wouldn't mind as much having support for something like zstd (or brotli; snappy maybe, although zstd might supersede it) in grpc-java as a new module that is detected at runtime.

**Comment by ctiller** [comment]
I think if there's external interest in figuring this out I'd like to encourage that, especially if we can figure ways to limit the abuse vectors seen with the Java API, and I'd be happy to internally help push a gRFC in this direction.

**Comment by rakeeb-hossain** [comment]
Thanks for the response @ctiller - am I able to help externally on this? You mentioned internally pushing a gRFC, so just wanted to confirm if I can help drive that

**Comment by ctiller** [comment]
I meant... without any guarantee that it gets accepted, and with no idea
how many iterations we'd end up doing... If you put together a gRFC, I'd be
willing to help review & iterate on it, and make sure it gets in front of
the right folks internally to maximize chances of acceptance.

**Comment by mattnworb** [comment]
> Java [already has](https://grpc.github.io/grpc-java/javadoc/io/grpc/CompressorRegistry.html#register-io.grpc.Compressor-) [an API](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#decompressorRegistry-io.grpc.DecompressorRegistry-), [as does Go](https://pkg.go.dev/google.golang.org/grpc@v1.38.0/encoding#RegisterCompressor). Both are experimental. That said, I didn't want the Java API to begin with and I have no plans to stabilize it and get a bit sad when it is used. To my knowledge it is abused for non-compression things more often than to support alternative compression algorithms.

To add a small data point here, we have a use case in Java where the existing pluggable compressor support has been very helpful for easily adding internal (within the company) support for Snappy as a less-expensive alternative to gzip, to the point where if it were to be removed we would miss it.

**Comment by ejona86** [comment]
@mattnworb, I have no plans to "strand" use cases like yours. If we removed the API, we'd work with others to figure out other options, whether that is built-in support for Snappy or a migration to something like Zstd or something else. I am happy to hear it was used for actual compression. That said, I still have hope that one day "full-stream compression" (aka, HTTP-standard compression, so streaming messages get to share the compression window) will happen, but the current API could not be used for that purpose.

**Comment by vadimkantorov** [comment]
Custom / more compression codec can be very useful at grpc level given that grpc is used for the https://github.com/triton-inference-server/server inference server. grpc is used there to send/serve ML models' inference requests, so in some setups being able to do some super-speedy transparent compression (in addition to CPU-hungry gzip) can save network usage for binary images or audio with a lot of silence (and sometimes it may be convenient to have this basic compression support directly at the transport level)

**Comment by artem** [comment]
@markdroth @ctiller Could you please reopen the issue? I think that in 2025, given the effectiveness and widespread adoption of Zstd, being locked to what zlib provides is not very practical.

Although c-core still lacks a compressor registry API, I believe that conditionally supporting Zstd as a compile-time option would cover the majority of use cases.

**Comment by vchigrin** [comment]
Made a patch which adds zstd compression support https://github.com/grpc/grpc/pull/41813. Maybe, it will useful for those people, who want this feature, and maintain their own grpc fork. If mainainers consider this feature useful, I can continue working to bring it to master brunch, if no - feel free to close this PR...

**Comment by frittentheke** [comment]
@drfloob with PR https://github.com/grpc/grpc/pull/41813 by @vchigrin  open, maybe you could reopen this issue here?

**Comment by markdroth** [comment]
We'd need a gRFC before we can accept an implementation of this in any language.  We aren't planning to work on this ourselves, but if someone wants to try writing a gRFC themselves, we can try to find time to review it.
