### ISSUE TITLE
Illegal instruction using python wheel in armv6

### ISSUE THREAD

**Issue by fedej** [grpc/grpc#26474]
### What version of gRPC and what language are you using?
1.37.0, 1.37.1, 1.38.0 and Python

### What operating system (Linux, Windows,...) and version?
Linux raspberrypi 5.10.17+ #1421 Thu May 27 13:58:02 BST 2021 armv6l GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.3

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

`pip install --only-binary :all: grpcio==1.37.0 && python -c 'import grpc; print("Hello!")'`

### What did you expect to see?
`Hello!`

### What did you see instead?
`Illegal instruction`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I don't know if this is the right place to report the issue as I've also found info for the same problem in [this thread](https://github.com/googlesamples/assistant-sdk-python/issues/235). It started failing after armv6 wheel support was removed [here](https://github.com/grpc/grpc/pull/25704) and released in 1.37.0.

Building from source (or pinning 1.36.1) works as mitigation, but doing so in RPi1/0 is typically slow. Can you look into building these again?

Thanks!

**Comment by jtattermusch** [comment]
AFAIK we don't support armv6 for python. And we also don't publish armv6 wheels as part of our releases (we do produce armv7 and aarch64 - see https://pypi.org/project/grpcio/1.38.0/#files). So the fact that armv6 doesn't work isn't surprising to me at all?

**Comment by julianoes** [comment]
It looks like the armv6l wheel comes from piwheels, at least that's what happens on my RPi1 Raspbian Buster:

```
Collecting grpcio>=1.11.0 (from mavsdk)
  Downloading https://www.piwheels.org/simple/grpcio/grpcio-1.38.0-cp37-cp37m-linux_armv6l.whl (38.3MB)
```

However, what does work as a workaround for me is to install it from the deb packages:
```
sudo apt-get install python3-grpcio
```

**Comment by julianoes** [comment]
I've filed an issue over there: https://github.com/piwheels/packages/issues/217

**Comment by fedej** [comment]
Thanks for the clarification, looks like it was indeed a coincidence around that ARM build change I saw. Guess no other actions are needed here then
