### ISSUE TITLE
build_package.csharp_package_unity_linux continuously broken on master

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#26483]
It looks like the first failed build happened yesterday at 6:17PM Pacific.

```
+ cp Grpc.Core.Api/bin/Release/net45/Grpc.Core.Api.dll unitypackage/unitypackage_skeleton/Plugins/Grpc.Core.Api/lib/net45/Grpc.Core.Api.dll
+ cp Grpc.Core.Api/bin/Release/net45/Grpc.Core.Api.pdb unitypackage/unitypackage_skeleton/Plugins/Grpc.Core.Api/lib/net45/Grpc.Core.Api.pdb
+ cp Grpc.Core.Api/bin/Release/net45/Grpc.Core.Api.xml unitypackage/unitypackage_skeleton/Plugins/Grpc.Core.Api/lib/net45/Grpc.Core.Api.xml
+ cp Grpc.Core/bin/Release/net45/Grpc.Core.dll unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/lib/net45/Grpc.Core.dll
+ cp Grpc.Core/bin/Release/net45/Grpc.Core.pdb unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/lib/net45/Grpc.Core.pdb
+ cp Grpc.Core/bin/Release/net45/Grpc.Core.xml unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/lib/net45/Grpc.Core.xml
+ cp nativelibs/csharp_ext_linux_x64/libgrpc_csharp_ext.so unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/runtimes/linux/x64/libgrpc_csharp_ext.so
+ cp nativelibs/csharp_ext_macos_x64/libgrpc_csharp_ext.dylib unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/runtimes/osx/x64/grpc_csharp_ext.bundle
+ cp nativelibs/csharp_ext_windows_x86/grpc_csharp_ext.dll unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/runtimes/win/x86/grpc_csharp_ext.dll
cp: cannot stat 'nativelibs/csharp_ext_windows_x86/grpc_csharp_ext.dll': No such file or directory
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc/artifacts
+ docker cp build_and_run_docker_4bd4df45-84cc-40f0-85d4-be15bb652a1f:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
+ docker rm -f build_and_run_docker_4bd4df45-84cc-40f0-85d4-be15bb652a1f
build_and_run_docker_4bd4df45-84cc-40f0-85d4-be15bb652a1f
+ '[' true '!=' '' ']'
+ exit 1

2021-06-15 10:23:31,357 FAILED: build_package.csharp_package_unity_linux [ret=1, pid=8436, time=220.7sec]
2021-06-15 10:23:31,357 WAITING: ETA 147.2 sec; 0 queued, 2 jobs running, 3 complete, 2 failed (load 2.00)
```

https://source.cloud.google.com/results/invocations/f2ea0b84-cee3-45eb-977a-b91c3bf76849/log

**Comment by gnossen** [comment]
@jtattermusch Looks like you're already on top of things: https://github.com/grpc/grpc/pull/26465. I will monitor and close this issue if that PR resolved the problem.

**Comment by gnossen** [comment]
It looks like this failure is currently breaking the following jobs:
- [master/linux/grpc_build_packages](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_packages)
- [master/linux/grpc_distribtests](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests)
- [master/macos/grpc_distribtests](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_distribtests)
- [master/windows/grpc_build_artifacts](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fwindows%2Fgrpc_build_artifacts)
- [master/windows/grpc_distribtests](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fwindows%2Fgrpc_distribtests)

**Comment by gnossen** [comment]
The following commits are the diff between the last good build and the first bad build:
 - https://github.com/grpc/grpc/commit/22cbc3a388999b92c2a3b083a65a3dcc4167c903
 - https://github.com/grpc/grpc/commit/f90716a8210d26ac3fb65693b6bd9965106be2ac
 - https://github.com/grpc/grpc/commit/1e2f19b286fb52e6c58dd0d36a08a0e3170ef777

These look completely unrelated and I see no compilation errors, so this was likely caused by a non-hermetic change in the C# toolchain.

**Comment by jtattermusch** [comment]
I think the real root cause is the windows/grpc_build_artifacts job suddenly getting broken on master.
https://fusion2.corp.google.com/invocations/80f58a79-e645-460e-b0af-6ef8528c5f65/targets/github%2Fgrpc;config=default/tests

I think the real problem is that nasm installation in the prepare step has failed, which later in the build results in failure to build grpc_csharp_ext. Since grpc_csharp_ext.dll cannot be build, all the subsequent steps (build packages & distribtests fail).
This is not the first time we're seeing the problem, unfortunately the nasm installation is not reliable (from time to time it gets broken for a few days and then it starts working again).
```
T:\src>choco install nasm -y --limit-output 


Installing the following packages:


nasm


By installing you accept licenses for the packages.



Progress: Downloading nasm 2.14.02... 15%
Progress: Downloading nasm 2.14.02... 49%
Progress: Downloading nasm 2.14.02... 82%
Progress: Downloading nasm 2.14.02... 100%





nasm v2.14.02 [Approved]


nasm package files install completed. Performing other installation steps.


Attempt to get headers for https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe failed.

  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"


Downloading nasm 64 bit


  from 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'


ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server" 

This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.


The install of nasm was NOT successful.


Error while running 'C:\ProgramData\chocolatey\lib\nasm\tools\chocolateyInstall.ps1'.
```

**Comment by jtattermusch** [comment]
Looks like starting from build 17102 the problem has fixed itself (nasm installation through chocolatey started to work again?): https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fwindows%2Fgrpc_build_artifacts
