### ISSUE TITLE
Need a more reliable way of installing build pre-requisites on windows (than chocolatey)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#26489]
Currently we're using chocolatey to install build prerequisites on kokoro windows workers.

In the past we've seen several cases of installing choco packages being broken for a day or to, with no apparent reason (after which things fix themselves without any interventions).

This causes random hard-to-diagnose test breakages and slows down the team.
E.g.
https://github.com/grpc/grpc/issues/26483
https://github.com/grpc/grpc/issues/26484

Example failed installation:

```
T:\src>choco install nasm -y --limit-output 


Installing the following packages:


nasm


By installing you accept licenses for the packages.



Progress: Downloading nasm 2.14.02... 15%
Progress: Downloading nasm 2.14.02... 49%
Progress: Downloading nasm 2.14.02... 82%
Progress: Downloading nasm 2.14.02... 100%





nasm v2.14.02 [Approved]


nasm package files install completed. Performing other installation steps.


Attempt to get headers for https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe failed.

  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"


Downloading nasm 64 bit


  from 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'


ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-installer-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server" 

This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.


The install of nasm was NOT successful.


Error while running 'C:\ProgramData\chocolatey\lib\nasm\tools\chocolateyInstall.ps1'.
```

Install prerequisite scripts:
https://github.com/grpc/grpc/blob/master/tools/internal_ci/helper_scripts/prepare_build_windows.bat
https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/tools/internal_ci/windows/grpc_build_artifacts.bat#L17
https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/tools/internal_ci/windows/bazel_rbe.bat#L17

**Comment by gnossen** [comment]
Using [Artifactory as a pull-through chocolatey cache](https://jfrog.com/blog/artifactory-as-a-caching-mechanism-for-package-managers/) could be a solution for this. In fact, I think this would be a good idea for all of our various package managers.

**Comment by jtattermusch** [comment]
CC @nicolasnoble

**Comment by jtattermusch** [comment]
I think this can be closed since I recently removed all the places where choco is used to install something (see linked PRs).
(one "choco uninstall" is remaining, but uninstalling shouldn't be flaky).

See https://github.com/grpc/grpc/search?q=choco
