### ISSUE TITLE
windows/grpc_distribtests C# x86_64 continuously broken on master

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#26484]
```
T:\src\github\grpc\workspace_csharp_windows_x86\test\distrib\csharp>cd DistribTest   || goto :error 







T:\src\github\grpc\workspace_csharp_windows_x86\test\distrib\csharp\DistribTest>nuget restore -PackagesDirectory ../packages   || goto :error 



Invalid package version for package id 'Grpc': ''







T:\src\github\grpc\workspace_csharp_windows_x86\test\distrib\csharp\DistribTest>echo Failed! 



Failed!
```

https://source.cloud.google.com/results/invocations/3d48d17d-64d0-472d-a645-dc7ab79d41dd/targets
 Likely related to https://github.com/grpc/grpc/issues/26483

**Comment by gnossen** [comment]
The MacOS distribtests are similarly broken:

```
Running in workspace workspace_csharp_macos_x64
+ cd workspace_csharp_macos_x64
+ test/distrib/csharp/run_distrib_test.sh
++ dirname test/distrib/csharp/run_distrib_test.sh
+ cd test/distrib/csharp
+ unzip -o ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip -d TestNugetFeed
unzip:  cannot find or open ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip, ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip.zip or ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip.ZIP.

2021-06-15 09:08:44,343 FAILED: distribtest.csharp_macos_x64 [ret=9, pid=5248, time=18.4sec]
```

https://source.cloud.google.com/results/invocations/cab4fb1b-1bfd-4cc7-8a9f-560e700ef4b4/targets

**Comment by gnossen** [comment]
Tentatively marking this as a release blocker since a branch cut is scheduled for today. @jtattermusch If you do not agree that this is a release blocker, please chime in.

CC @apolcyn

**Comment by jtattermusch** [comment]
This has likely the same rootcause as https://github.com/grpc/grpc/issues/26483 (failing to install nasm in the initial build_artifact phase).

**Comment by jtattermusch** [comment]
Looks like starting from build 17102 the problem has fixed itself (nasm installation through chocolatey started to work again?): https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fwindows%2Fgrpc_build_artifacts
