### ISSUE TITLE
grpc C++ alternative cryptographic libraries

### ISSUE THREAD

**Issue by MartinKosicky** [grpc/grpc#26491]
Hello, according to the documentation I am somehow able to use a different cryptographic library. I want to use something that is not based on openssl. According to the code I thought that I am supposed to write my own implementation of grpc_channel_credentials. However, that is implicitli importing https://github.com/grpc/grpc/blob/master/src/core/tsi/ssl_transport_security.h

However this header is including 
`#include <openssl/x509.h>`

So the question is if this isn't a bug that this file is using openssl/x509.h , or that in order to swap cryptographic library (for example for windows crypto api) I should do something else?

**Comment by yihuazhang** [comment]
Sorry for the late reply. 

You can always create your own `grpc_channel_credentials` with your own implementation of [TSI interface](https://github.com/grpc/grpc/blob/master/src/core/tsi/transport_security_interface.h). `ssl_transport_security` is just the TSI implementation of SSL and advanced TLS credentials. You do not need to use it if you do not want to.
