### ISSUE TITLE
python3 gRPC asyncio server (FreeBSD-13) seems to spin using 100% cpu

### ISSUE THREAD

**Issue by scottgasch** [grpc/grpc#26517]
### What version of gRPC and what language are you using?
grpcio                   1.34.0
grpcio-tools             1.34.0

### What operating system (Linux, Windows,...) and version?
FreeBSD wannabe.house 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.10

### What did you do?
I've written two simple RPC servers that have the same functionality - they read/set the timestamp of a file.  One uses blocking python and the other uses the python asyncio framework.  The latter (asyncio) seems to spin using 100% of a CPU after the first request arrives at the server.  This seems to continue indefinitely (doesn't revert back to baseline even after hours of burning CPU).  I'm including the code for the probematic asyncio server here in case I've done something stupid:

```
import asyncio
import datetime
from dateutil import tz
import logging
import math

from grpc import aio

import bootstrap
import config
import file_utils
import service_pb2_grpc
import service_pb2

logger = logging.getLogger(__name__)
cfg = config.add_commandline_args(
    f'Timestamps Server ({__file__})',
    'Timestamps GRPC Server',
)
cfg.add_argument(
    '--port',
    type=int,
    default=9999,
    metavar='PORT_NUMBER',
    help='Override the TCP port to listen on',
)


class TimestampServiceServicerImpl(service_pb2_grpc.TimestampServiceServicer):
    async def GetTimestamp(self, request, context):
        logger.debug('Entering GetTimestamp')
        logger.debug(f'Context: {context}')
        logger.debug(f'Request: {request}')
        response = service_pb2.GetTimestampResponse()
        all_ok = True
        for label in request.read_label:
            filename = f'/timestamps/{label}'
            if file_utils.does_file_exist(filename):
                ts = file_utils.get_file_raw_mtime(filename)
                dt = datetime.datetime.utcfromtimestamp(ts)
                logger.info(f'Fetched {filename} mtime ({ts})')
                ok = True
            else:
                logger.warning(f"Requested file {filename} doesn't exist.")
                ts = -1
                dt = None
                ok = False
            all_ok &= ok
            lav = service_pb2.TimestampLabelAndValue()
            lav.label = label
            lav.value.seconds = math.trunc(ts)
            lav.value.nanos = int((ts - lav.value.seconds) * 100000000)
            if dt is not None:
                utc_zone = tz.tzutc()
                local_zone = tz.tzlocal()
                dt = dt.replace(tzinfo=utc_zone)
                lav.value.text_utc = f'{dt}'
                dt = dt.astimezone(local_zone)
                lav.value.text_local = f'{dt}'
            response.label_and_value.append(lav)
            response.ok.append(ok)
        response.all_successful = all_ok
        logger.debug('Response: {response}')
        logger.debug('Leaving GetTimestamp')
        return response

    async def SetTimestamp(self, request, context):
        logger.debug('Entering SetTimestamp')
        logger.debug(f'Context: {context}')
        logger.debug(f'Request: {request}')
        response = service_pb2.SetTimestampResponse()
        all_ok = True
        for lav in request.write_timestamp_with_value:
            filename = f'/timestamps/{lav.label}'
            if file_utils.does_file_exist(filename):
                if lav.value.seconds == 0 or lav.value.seconds is None:
                    file_utils.set_file_raw_atime_and_mtime(filename, None)
                    logger.info(f'Set {filename} atime and mtime to NOW')
                else:
                    file_utils.set_file_raw_atime_and_mtime(filename, lav.value.seconds)
                    logger.info(f'Set {filename} atime and mtime to {lav.value.seconds}')
                ok = True
            else:
                logger.warning(f"Requested file {filename} doesn't exist.")
                ok = False
            response.ok.append(ok)
            all_ok &= ok
        return response


async def serve():
    server = aio.server()
    service_pb2_grpc.add_TimestampServiceServicer_to_server(
        TimestampServiceServicerImpl(), server)
    server.add_insecure_port(f'[::]:{config.config["port"]}')
    await server.start()
    await server.wait_for_termination()


@bootstrap.initialize
def main():
    asyncio.get_event_loop().run_until_complete(serve())


if __name__ == '__main__':
    main()
```

### What did you expect to see?
I expected the CPU utilization of this async server to be less than 100% of a core.

### What did you see instead?
When the process starts up, CPU utilization is normal (low) however upon receiving the first RPC request the utilization ramps up to 100% over the next few seconds and never seems to reduce again.  I've run this with env vars:

GRPC_VERBOSITY=debug GRPC_TRACE=api,polling

This yields the following messages:

D0619 07:58:45.780702796 34374492160 ev_posix.cc:173]                  Using polling engine: poll
D0619 07:58:45.780826146 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "grpclb"
D0619 07:58:45.780838266 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "priority_experimental"
D0619 07:58:45.780848431 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "weighted_target_experimental"
D0619 07:58:45.780857139 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "pick_first"
D0619 07:58:45.780865059 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "round_robin"
D0619 07:58:45.780874006 34374492160 dns_resolver_ares.cc:507]         Using ares dns resolver
D0619 07:58:45.780899862 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "cds_experimental"
D0619 07:58:45.780909720 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "eds_experimental"
D0619 07:58:45.780918413 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "xds_cluster_impl_experimental"
D0619 07:58:45.780927158 34374492160 lb_policy_registry.cc:42]         registering LB policy factory for "xds_cluster_manager_experimental"
E0619 07:58:45.780944697 34374492160 trace.cc:65]                      Unknown trace var: 'polling'
I0619 07:58:45.780987746 34374492160 init.cc:168]                      grpc_init(void)
I0619 07:58:45.781002764 34374492160 completion_queue.cc:523]          grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0619 07:58:45.781422318 34383314176 completion_queue.cc:978]          grpc_completion_queue_next(cq=0x800e5d140, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0x0)
I0619 07:58:45.781606763 34374492160 init.cc:168]                      grpc_init(void)
I0619 07:58:45.781623232 34374492160 server.cc:1451]                   grpc_server_create(0x8039392c0, 0x0)
I0619 07:58:45.786372977 34374492160 server.cc:1462]                   grpc_server_register_completion_queue(server=0x800e08150, cq=0x800e5d140, reserved=0x0)
I0619 07:58:45.788004394 34374492160 server_chttp2.cc:34]              grpc_server_add_insecure_http2_port(server=0x800e08150, addr=[::]:9999)
I0619 07:58:45.788379403 34374492160 server.cc:1490]                   grpc_server_start(server=0x800e08150)
I0619 07:58:45.788460030 34374492160 metadata_array.cc:29]             grpc_metadata_array_init(array=0x8038fc1d0)
I0619 07:58:45.788472254 34374492160 call_details.cc:31]               grpc_call_details_init(cd=0x8038fc170)
I0619 07:58:45.788497372 34374492160 server.cc:1531]                   grpc_server_request_call(server=0x800e08150, call=0x8038fc160, details=0x8038fc170, initial_metadata=0x8038fc1d0, cq_bound_to_call=0x800e5d140, cq_for_notification=0x800e5d140, tag=0x80378bce8)

// request received here

I0619 07:58:55.524555837 34383314176 init.cc:168]                      grpc_init(void)
I0619 07:58:55.524852974 34383314176 call.cc:1562]                     ops[0]: RECV_INITIAL_METADATA ptr=0x804865b28
I0619 07:58:55.524912909 34383314176 completion_queue.cc:704]          cq_end_op_for_next(cq=0x800e5d140, tag=0x80378bce8, error="No Error", done=0x802506a90, done_arg=0x8014283c0, storage=0x8014283e8)
I0619 07:58:55.524928381 34383314176 completion_queue.cc:1079]         RETURN_EVENT[0x800e5d140]: OP_COMPLETE: tag:0x80378bce8 OK
I0619 07:58:55.524980498 34383314176 completion_queue.cc:978]          grpc_completion_queue_next(cq=0x800e5d140, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0x0)
I0619 07:58:55.525230158 34374492160 metadata_array.cc:29]             grpc_metadata_array_init(array=0x8038fc2d0)
I0619 07:58:55.525273034 34374492160 call_details.cc:31]               grpc_call_details_init(cd=0x8038fc270)
I0619 07:58:55.525297292 34374492160 server.cc:1531]                   grpc_server_request_call(server=0x800e08150, call=0x8038fc260, details=0x8038fc270, initial_metadata=0x8038fc2d0, cq_bound_to_call=0x800e5d140, cq_for_notification=0x800e5d140, tag=0x80378bce8)
I0619 07:58:55.525379491 34374492160 call.cc:1966]                     grpc_call_start_batch(call=0x804865060, ops=0x800e450a0, nops=1, tag=0x8038fdbe8, reserved=0x0)
I0619 07:58:55.525396055 34374492160 call.cc:1562]                     ops[0]: RECV_CLOSE_ON_SERVER cancelled=0x803942528
I0619 07:58:55.525506895 34374492160 call.cc:1966]                     grpc_call_start_batch(call=0x804865060, ops=0x800e45190, nops=1, tag=0x8038fdd68, reserved=0x0)
I0619 07:58:55.525519945 34374492160 call.cc:1562]                     ops[0]: RECV_MESSAGE ptr=0x8038fdca0
I0619 07:58:55.525542790 34374492160 completion_queue.cc:704]          cq_end_op_for_next(cq=0x800e5d140, tag=0x8038fdd68, error="No Error", done=0x8024fc4c0, done_arg=0x804867770, storage=0x8048677b8)
I0619 07:58:55.525583469 34383314176 completion_queue.cc:1079]         RETURN_EVENT[0x800e5d140]: OP_COMPLETE: tag:0x8038fdd68 OK
I0619 07:58:55.530419930 34383314176 completion_queue.cc:978]          grpc_completion_queue_next(cq=0x800e5d140, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0x0)
INFO:2021/06/19T07:58:55.531451-0700: Fetched /timestamps/last_disk_selftest_long mtime (1621165980.206687)
INFO:2021/06/19T07:58:55.581430-0700: Fetched /timestamps/last_rpi_cabin_ping mtime (1618510894.062533)
WARNING:2021/06/19T07:58:55.581974-0700: Requested file /timestamps/foobar doesn't exist.
INFO:2021/06/19T07:58:55.582290-0700: Fetched /timestamps/last_playlist_backup mtime (1624094487.026728)
I0619 07:58:55.598323785 34374492160 call.cc:1966]                     grpc_call_start_batch(call=0x804865060, ops=0x8015ca700, nops=3, tag=0x804a02d68, reserved=0x0)
I0619 07:58:55.598372749 34374492160 call.cc:1562]                     ops[0]: SEND_INITIAL_METADATA(nil)
I0619 07:58:55.598383564 34374492160 call.cc:1562]                     ops[1]: SEND_MESSAGE ptr=0x800e5d500
I0619 07:58:55.598394134 34374492160 call.cc:1562]                     ops[2]: SEND_STATUS_FROM_SERVER status=0 details=(nil)
I0619 07:58:55.598481635 34374492160 completion_queue.cc:704]          cq_end_op_for_next(cq=0x800e5d140, tag=0x8038fdbe8, error="No Error", done=0x8024fc4c0, done_arg=0x804867660, storage=0x8048676a8)
I0619 07:58:55.598508969 34374492160 completion_queue.cc:704]          cq_end_op_for_next(cq=0x800e5d140, tag=0x804a02d68, error="No Error", done=0x8024fc4c0, done_arg=0x804867880, storage=0x8048678c8)
I0619 07:58:55.598555858 34383314176 completion_queue.cc:1079]         RETURN_EVENT[0x800e5d140]: OP_COMPLETE: tag:0x8038fdbe8 OK
I0619 07:58:55.598607000 34383314176 completion_queue.cc:978]          grpc_completion_queue_next(cq=0x800e5d140, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0x0)
I0619 07:58:55.598621362 34383314176 completion_queue.cc:1079]         RETURN_EVENT[0x800e5d140]: OP_COMPLETE: tag:0x804a02d68 OK
I0619 07:58:55.598634392 34383314176 completion_queue.cc:978]          grpc_completion_queue_next(cq=0x800e5d140, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0x0)

### Anything else we should know about your project / environment?
No.  I hope this is not just a case of me misunderstanding something; I've looked for options on the RPC server that might affect this and didn't see anything obvious.  Thanks in advance for the advice.

**Comment by lidizheng** [comment]
Based on the trace log, this CPU consumption is happening in the Python space. 

@scottgasch Can we get the pending coroutines in AsyncIO? Also, can you try to minimize the reproduction snippet (stripping the business logic, add proto definitions, add client calls)?

**Comment by scottgasch** [comment]
Hi there.  Thanks for your reply and for looking at this.  I just tried to
repro and it seems to have "fixed itself".  What changed?  Well, my version
of python for one.  I'm now using Python 3.7.12.  None of the code nor the
grpc libraries have changed though.

**Comment by lidizheng** [comment]
Thanks for the quick response. I will close this issue for now. If this problem is recurring, feel free to comment or re-open it.
