### ISSUE TITLE
Assertion Failure on grpc_channel_stack_init when debugging tf-serving 

### ISSUE THREAD

**Issue by threeleafzerg** [grpc/grpc#26526]
I encountered following assertion when debugging tf-serving:
E0622 08:44:11.816529912   29242 channel_stack.cc:135]       assertion failed: (uintptr_t)(user_data - (char*)stack) == grpc_channel_stack_size(filters, filter_count)
It asserts very early when grpc server received an event. 
I add debug flags "GRPC_TRACE=all, GPRC_VERBOSE=DEBUG", but didn't find useful information. 

For server part, it use grpc++ library. For client part, it use grpc java grpc-netty component. 
One of my suspect is:
On server side: the grpc version is:  CPP_VERSION = 1.19.1 (CORE_VERSION = 7.0.0)
On client side: grpc-netty is 1.20.0. 
Is it caused by mismatch of grpc version between server and client? 
Or any other ideas? Thanks!

**Comment by threeleafzerg** [comment]
The background of this issue is as follows:
https://github.com/tensorflow/serving/issues/1870

**Comment by yashykt** [comment]
gRPC is backwards compatible so it is not an issue of mismatch but more likely a real issue.
A possible problem is that the version that you are running is considerably old. If I recall correctly, there have been a few fixes related to alignment in the newer releases.

**Comment by yashykt** [comment]
Would you be able to use a newer release and try it out?

**Comment by threeleafzerg** [comment]
I update tf-serving to 2.4.0 which use grpc 1.27.0 and the issue disappear.

**Comment by yashykt** [comment]
I'm gonna call this fixed in that case (unless an upgrade is not possible and we need a backport to the much older branch for some reason).
