### ISSUE TITLE
protoc compilation failed to generate stubs with status code 3221225781

### ISSUE THREAD

**Issue by msbasanth** [grpc/grpc#26534]
**Platform:** Windows 10 x64

**Language:** C++

**Command used:**
`protoc -I ./Protos --grpc_out=. --plugin="protoc-gen-grpc=D://DEV//vcpkg//buildtrees//grpc//x64-windows-rel//grpc_cpp_plugin.exe" ./Protos/ecgdata.proto`

**Error:**
`--grpc_out: protoc-gen-grpc: Plugin failed with status code 3221225781.`

**How I installed gRPC?**
Installed gRPC using vcpkg https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/src/cpp/README.md#install-using-vcpkg-package
Hope this is the right approach to install gRPC C++ in Windows environment.

```
# install vcpkg package manager on your system using the official instructions
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg

# Bootstrap on Windows instead:
# ./bootstrap-vcpkg.bat

./vcpkg integrate install

# install gRPC using vcpkg package manager
./vcpkg install grpc
```
It took around 30min and all packages installation succeeded. A similar message I saw for each package under grpc - `Installing package grpc[core]:x86-windows... done`

Initially I had problem in finding the grpc_cpp_plugin but now I am inputting the full path. Now I am getting "Plugin failed with status code 3221225781". Any hint what I am doing wrong?

Thanks
Basanth

**Comment by yashykt** [comment]
From the docs - 
`The gRPC port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please create an issue or pull request on the vcpkg repository.`
