### ISSUE TITLE
Spurious tsan race in stack_lockfree

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2653]
Caused by 4-byte aba ctr being stored with each entry.

WARNING: ThreadSanitizer: data race (pid=16029)
  Write of size 4 at 0x7f658d24c004 by thread T1 (mutexes: write M412):
    #0 gpr_stack_lockfree_push /usr/local/google/home/vpai/Git/grpc/src/core/support/stack_lockfree.c:107 (exe+0x0000004c9b7e)
    #1 queue_call_request /usr/local/google/home/vpai/Git/grpc/src/core/surface/server.c:1117 (exe+0x0000002b05bb)
    #2 grpc_server_request_registered_call /usr/local/google/home/vpai/Git/grpc/src/core/surface/server.c:1193 (exe+0x0000002b0f62)
    #3 grpc::Server::SyncRequest::Request(grpc_server*, grpc_completion_queue*) /usr/local/google/home/vpai/Git/grpc/src/cpp/server/server.cc:97 (exe+0x000000232046)
    #4 grpc::Server::RunRpc() /usr/local/google/home/vpai/Git/grpc/src/cpp/server/server.cc:401 (exe+0x000000230f4e)
    #5 void std::_Mem_fn<void (grpc::Server::*)()>::operator()<, void>(grpc::Server*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:601 (exe+0x000000233b43)
    #6 void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1295 (exe+0x000000233a19)
    #7 void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::operator()<, void>() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1353 (exe+0x000000233961)
    #8 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)> >::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2071 (exe+0x000000233448)
    #9 std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2471 (exe+0x000000224820)
    #10 grpc::FixedSizeThreadPool::ThreadFunc() /usr/local/google/home/vpai/Git/grpc/src/cpp/server/fixed_size_thread_pool.cc:53 (exe+0x0000002235e1)
    #11 void std::_Mem_fn<void (grpc::FixedSizeThreadPool::*)()>::operator()<, void>(grpc::FixedSizeThreadPool*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:601 (exe+0x000000229f03)
    #12 void std::_Bind_simple<std::_Mem_fn<void (grpc::FixedSizeThreadPool::*)()> (grpc::FixedSizeThreadPool*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1731 (exe+0x000000229d90)
    #13 std::_Bind_simple<std::_Mem_fn<void (grpc::FixedSizeThreadPool::*)()> (grpc::FixedSizeThreadPool*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1720 (exe+0x000000229d00)
    #14 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::FixedSizeThreadPool::*)()> (grpc::FixedSizeThreadPool*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/thread:115 (exe+0x000000229ca9)
    #15 execute_native_thread_routine /build/buildd/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/src/c++11/../../../../../src/libstdc++-v3/src/c++11/thread.cc:84 (libstdc++.so.6+0x0000000b1a3f)

  Previous atomic read of size 8 at 0x7f658d24c000 by thread T59:
    #0 __tsan_atomic64_load ??:0 (exe+0x0000001a61a4)
    #1 gpr_stack_lockfree_pop /usr/local/google/home/vpai/Git/grpc/src/core/support/stack_lockfree.c:127 (exe+0x0000004c9f70)
    #2 finish_start_new_rpc /usr/local/google/home/vpai/Git/grpc/src/core/surface/server.c:412 (exe+0x0000002b66e4)
    #3 start_new_rpc /usr/local/google/home/vpai/Git/grpc/src/core/surface/server.c:464 (exe+0x0000002b6451)
    #4 server_on_recv /usr/local/google/home/vpai/Git/grpc/src/core/surface/server.c:558 (exe+0x0000002b50ee)
    #5 hs_on_recv /usr/local/google/home/vpai/Git/grpc/src/core/channel/http_server_filter.c:178 (exe+0x0000002fefeb)
    #6 unlock /usr/local/google/home/vpai/Git/grpc/src/core/transport/chttp2_transport.c:474 (exe+0x0000002679e5)
    #7 recv_data /usr/local/google/home/vpai/Git/grpc/src/core/transport/chttp2_transport.c:986 (exe+0x00000026a2ab)
    #8 call_read_cb /usr/local/google/home/vpai/Git/grpc/src/core/iomgr/tcp_posix.c:328 (exe+0x0000002d122d)
    #9 grpc_tcp_continue_read /usr/local/google/home/vpai/Git/grpc/src/core/iomgr/tcp_posix.c:419 (exe+0x0000002d1b6c)
    #10 grpc_tcp_handle_read /usr/local/google/home/vpai/Git/grpc/src/core/iomgr/tcp_posix.c:435 (exe+0x0000002cfa9e)
    #11 grpc_maybe_call_delayed_callbacks /usr/local/google/home/vpai/Git/grpc/src/core/iomgr/iomgr.c:268 (exe+0x000000290ab2)
    #12 grpc_pollset_work /usr/local/google/home/vpai/Git/grpc/src/core/iomgr/pollset_posix.c:143 (exe+0x0000002a15fd)
    #13 grpc_completion_queue_pluck /usr/local/google/home/vpai/Git/grpc/src/core/surface/completion_queue.c:222 (exe+0x00000027689c)
    #14 grpc::CompletionQueue::Pluck(grpc::CompletionQueueTag*) /usr/local/google/home/vpai/Git/grpc/src/cpp/common/completion_queue.cc:74 (exe+0x000000220e72)
    #15 grpc::Status grpc::BlockingUnaryCall<grpc::cpp::test::util::EchoRequest, grpc::cpp::test::util::EchoResponse>(grpc::ChannelInterface*, grpc::RpcMethod const&, grpc::ClientContext*, grpc::cpp::test::util::EchoRequest const&, grpc::cpp::test::util::EchoResponse*) /usr/local/google/home/vpai/Git/grpc/include/grpc++/impl/client_unary_call.h:69 (exe+0x0000001f2e77)
    #16 grpc::cpp::test::util::TestService::Stub::Echo(grpc::ClientContext*, grpc::cpp::test::util::EchoRequest const&, grpc::cpp::test::util::EchoResponse*) /usr/local/google/home/vpai/Git/grpc/gens/test/cpp/util/echo.grpc.pb.cc:41 (exe+0x0000001eef3b)
    #17 grpc::testing::SendRpc(grpc::cpp::test::util::TestService::Stub*, int) /usr/local/google/home/vpai/Git/grpc/test/cpp/end2end/thread_stress_test.cc:222 (exe+0x0000001c52e1)
    #18 void std::_Bind_simple<void (*(grpc::cpp::test::util::TestService::Stub*, int))(grpc::cpp::test::util::TestService::Stub*, int)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1731 (exe+0x0000001cc067)
    #19 std::_Bind_simple<void (*(grpc::cpp::test::util::TestService::Stub*, int))(grpc::cpp::test::util::TestService::Stub*, int)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1720 (exe+0x0000001cbf90)
    #20 std::thread::_Impl<std::_Bind_simple<void (*(grpc::cpp::test::util::TestService::Stub*, int))(grpc::cpp::test::util::TestService::Stub*, int)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/thread:115 (exe+0x0000001cbf39)
    #21 execute_native_thread_routine /build/buildd/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/src/c++11/../../../../../src/libstdc++-v3/src/c++11/thread.cc:84 (libstdc++.so.6+0x0000000b1a3f)

**Comment by jayantkolhe** [comment]
fixed by #2539
