### ISSUE TITLE
Include the version of the generator used in a generated output

### ISSUE THREAD

**Issue by remyleone** [grpc/grpc#26536]
### Is your feature request related to a problem? Please describe.

As a user, I would like to know which version is used to generate a particular piece of code that is included in my dependencies.

At the moment I only see:

```
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
```
without any indication of the version used.

### Describe the solution you'd like

In the generated file in all languages, I would like to see the version of gRPC that was used to generate a particular piece of code.

This could be useful in case a bug is fixed in a given generator and regenerating the code could be a viable solution to a problem.

**Comment by yashykt** [comment]
This seems like a worthwhile feature request.

**Comment by ctiller** [comment]
Should this be reopened (and I think it should), let's be careful to add a
new version number for the generator that varies independently to the grpc
version number: we don't tweak the generator every release, and making it
generate different values will unnecessarily add rebuild steps to some
build systems.
