### ISSUE TITLE
Reorganize the build_artifacts -> build_packages -> distribtest  flow for easy-to-interpret results and simpler troubleshooting.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#26549]
Context https://github.com/grpc/grpc/issues/26546#issuecomment-867480331

Problem statement:
I see folks mis-identifying the rootcause of problems in the artifact - packages - distribtest flow way too often (e.g. https://github.com/grpc/grpc/issues/26546). Basically, I think the issue is that there are multiple jobs (artifact linux, artifact macos, artifact windows, build packages linux, distribtests linux, distribtests macos, distribtests windows) that are grouped/chained together and depend on each other's outcome, but from kokoro perspective, they are mostly presented as individual jobs and that makes finding the links between these jobs far from straightforward.

I think this is something we should fix going forward, otherwise we're going to see confusion and misinterpretation in the future as well. I've already done some work along these lines in #26176, but more work is needed to achieve similar results for other languages.

Potential gains:
- lower test latency (since we won't need to have all the artifacts for all the languages build in a single slow "build_artifacts" job.
- easier to interpret test results, easier to quickly see root causes of problem
- not requiring expert knowledge of the artifact - build packages - distribtest flow in order to be able to diagnose problems
- ability to run distribtest for some languages platform as presubmit tests (e.g. as in #26176). Currently this is not possible since there is now way to display results of a chained job on a github PR (and distribtests are the last link in the build chain).

**Comment by jtattermusch** [comment]
CC @lidizheng, @apolcyn, @stanley-cheung, @veblush

**Comment by veblush** [comment]
@jtattermusch I like this :) Something we need to be aware of is that some language (i.e. ruby) are building Windows artifacts on Linux, which makes this approach a bit complicated.

**Comment by jtattermusch** [comment]
Now with the advent of bazelified RBE tests I think this can be basically considered obsolete.
