### ISSUE TITLE
Unable to retrieve ServerCallContext.RequestHeader values using the Key they were added with

### ISSUE THREAD

**Issue by StingyJack** [grpc/grpc#26551]
### What version of gRPC and what language are you using?
2.37.1  c#

### What operating system (Linux, Windows,...) and version?
Win 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet core 3.1

### What did you do?
On the Client (snips taken from a few places
``` csharp
//UserExecutionContext is a POCO with properties like RequestingUser, CompanyCode, etc. 
var headers = new Metadata
            {
                { $"{nameof(UserExecutionContext)}{Metadata.BinaryHeaderSuffix}", _userExecutionContextBytes }
            };

var channel = GrpcChannel.ForAddress("someUrl");
var client = new ProtoGeneratedClient(channel);
var resp = await client.DoSomeOperation(req, headers);
```

The connection to the service is made without error or issue. When attempting to retrieve the byte value from the ServerCallContext.RequestHeaders, a null is returned.
![image](https://user-images.githubusercontent.com/15381181/123321807-71735700-d501-11eb-8ffb-9ceaa63a6b8f.png)

The value that was added to the request headers is there, but the Key has been changed to lowercase.

### What did you expect to see?
I expect to get the value when I use the same key used to store it.

Programs should not modify data the user would expect to be able to use for retrieval at a later point. If the program must do so for some reason, the user should still be able to locate the data as they expect.  So if there is some specification that requires lowercasing the key values, then the same needs to be applied to all of the `Get()` functions as well (doing the same lowercasing to the key value argument before searching through its contents).

### What did you see instead?
`null`

###
This function 
https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/csharp/Grpc.Core.Api/Metadata.cs#L425

needs to be applied to the `key` value  and that result used for the remainder of this method
https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/csharp/Grpc.Core.Api/Metadata.cs#L120

or the equality check here should be a `string.Equals( key, entry.Key, StringComparison.OrdinalIgnoreCase)`
https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/csharp/Grpc.Core.Api/Metadata.cs#L86

**Comment by jtattermusch** [comment]
Lowercasing of metadata keys is consistent with http/2 protocol which requires all the headers to be converted to lowercase.
AFAIK this is the same behavior that other gRPC implementations use.

**Comment by StingyJack** [comment]
@jtattermusch  - Converting them to lowercase for transmit is OK. However, not letting me access the value by the key that I just used when adding the value is a bug.

Please see PR linked to this (also assigned to you).
