### ISSUE TITLE
Support glibc 2.34 without separate libpthread, librt, libdl

### ISSUE THREAD

**Issue by musicinmybrain** [grpc/grpc#26583]
### What version of gRPC and what language are you using?

1.37.1 (although this should apply to the current release as well); C, C++, Python

### What operating system (Linux, Windows,...) and version?

Fedora Rawhide (development version)

### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC 11.1.1

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Build grpc on a platform with a pre-release version of glibc 2.34. A Fedora Rawhide VM is one option.

### What did you expect to see?

Successful build

### What did you see instead?

```
+ /usr/bin/cmake --build x86_64-redhat-linux-gnu -j6 --verbose
ninja: error: '/usr/lib64/librt.so', needed by 'noop-benchmark', missing and no known rule to make it
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

[Full build log (link may expire)](https://kojipkgs.fedoraproject.org/work/tasks/7837/71057837/build.log)

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

In glibc 2.34, `librt`, `libdl`, and `libpthread` will be removed as separate libraries. See [this announcement](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/7R4RBS2MD75S2MTY42L44IW3KOUT5K36/) by glibc developer Florian Weimer, as well as mentions of [librt](https://sourceware.org/git/?p=glibc.git&a=search&h=HEAD&st=commit&s=librt), [libdl](https://sourceware.org/git/?p=glibc.git&a=search&h=HEAD&st=commit&s=libdl), and [libpthread](https://sourceware.org/git/?p=glibc.git&a=search&h=HEAD&st=commit&s=libpthread) in recent commits.

These libraries should be linked only conditionally, perhaps after testing for existence.

**Comment by musicinmybrain** [comment]
I’m going to close this for now. It seems like linking `-ldl`, `-lrt`, or `-lpthread` should be OK, as the `glib-devel` package still provides the corresponding *static* libraries, and the problem was coming from a hard-coded `/usr/lib64/librt.so` in the CMake files for the `google-benchmark` package. As I continue to work on this downstream, I’ll reopen this issue if it turns out there is something that needs to be adjusted in grpc.

**Comment by veblush** [comment]
@musicinmybrain Thank you for the report and context. If there is something we need to do, please reopen this.

**Comment by musicinmybrain** [comment]
Thanks. It looks like the problem was actually coming from a hard-coded `.so` path in the installed CMake files generated by `google-benchmark`, and rebuilding that package with the updated glibc solved it (by producing a hard-coded `.a` path instead).

It is still true that you no longer have to add `-ldl`, `-lrt`, or `-lpthread` starting with glibc 2.34, but since glibc upstream has provided empty static libraries with those names for compatibility, these arguments harmlessly do (almost) nothing.
