### ISSUE TITLE
AttributeError: module 'grpc' has no attribute 'AuthMetadataPlugin'

### ISSUE THREAD

**Issue by Edvard-D** [grpc/grpc#26590]
### What version of gRPC and what language are you using?
1.34.1, Python

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.5

### What did you do?
1. Download Google Research's [SEED Reinforcement Learning codebase](https://github.com/google-research/seed_rl).
2. Modify the code so that it installs the google-cloud-storage package and imports the google.cloud.storage module at some point after the seed_rl/gcp/run.py file is run.
3. Initialize a Google AI Platform training session by running the .sh file under seed_rl/gcp that corresponds to the environment you modified to import google.cloud.storage.

### What did you expect to see?
For the grpc package to have the attribute 'AuthMetadataPlugin'.

### What did you see instead?
The following error, visible in the Google Cloud Logs Explorer:

    Traceback (most recent call last):
    File "gcp/run.py", line 23, in <module>
    from seed_rl.trader import vtrace_main
    File "/seed_rl/trader/vtrace_main.py", line 24, in <module>
    from seed_rl.trader import batched_environment_settings
    File "/seed_rl/trader/batched_environment_settings.py", line 2, in <module>
    import google.cloud.storage as storage
    File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
    File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
    File "/usr/local/lib/python3.6/dist-packages/google/cloud/_helpers.py", line 38, in <module>
    import google.auth.transport.grpc
    File "/usr/local/lib/python3.6/dist-packages/google/auth/transport/grpc.py", line 43, in <module>
    class AuthMetadataPlugin(grpc.AuthMetadataPlugin):
    AttributeError: module 'grpc' has no attribute 'AuthMetadataPlugin'

### Anything else we should know about your project / environment?
The SEED codebase packages the code as a Docker image and uploads it to Google Cloud. That image is used by AI Platform to execute training. I have not installed the grpcio package directly; the version that's used is the one that was installed as part of the google-auth installation process, which was installed during installation of the google-cloud-storage package.

**Comment by lidizheng** [comment]
@Edvard-D We do provide the API in question: https://github.com/grpc/grpc/blob/f198fb5b41929ef341e8a6f5880b4dcf4a4c22c1/src/python/grpcio/grpc/__init__.py#L613

Can you try upgrading the related Python packages? If that still doesn't work, can you `pip freeze` to print the installed packages?

**Comment by Edvard-D** [comment]
Hey, thanks for the response @lidizheng and sorry for my late response. This ended up being a problem with some changes I made to the SEED codebase that I had made to work around a different bug. I figured out the correct way to fix the original problem, allowing me to use the methodology the SEED programmers used. That resolved this error for me.
