### ISSUE TITLE
Merge 'grpc_base' and 'grpc_base_c' targets in BUILD file

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#26594]
We think these were created as a trial balloon for the conversion from C to C++ - regardless, they don't seem to serve much purpose other than complicate the build, so let's merge them.

**Comment by veblush** [comment]
Crag, just to be sure, do you plan to do it? or just open up the issue?

**Comment by ctiller** [comment]
Right now I'm just opening the issue... no plan to do it yet.
