### ISSUE TITLE
In the process of using two-way flow, the client does not reconnect or exit after disconnection, and does not exit until 30 minutes later

### ISSUE THREAD

**Issue by YJSdream** [grpc/grpc#26619]
c++ In the process of using two-way flow, the client does not reconnect or exit after disconnection, and does not exit until 30 minutes later

**Comment by donnadionne** [comment]
For the future, please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion
 
Your answer may already be there or you can post a new question if it is not.
