### ISSUE TITLE
Invert User-Agent order so application-provided string comes first

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc#2661]
RFC 7231§5.5.3 says:

By convention, the product identifiers are listed in decreasing order of their significance for identifying the user agent software.

Combined with the example, it seems that we should put the application-provided string first.

**Comment by ctiller** [comment]
Wrapped languages can do this by setting the GRPC_ARG_PRIMARY_USER_AGENT_STRING channel argument.

Will file bugs to ensure all languages have appropriate API's.

**Comment by ctiller** [comment]
Since this is mostly a wrapped language issue now, hoping you can take care of closing the meta bug when it's time Tim.
