### ISSUE TITLE
Python: grpc Server stuck after connecting to client only in docker environment

### ISSUE THREAD

**Issue by ginwakeup** [grpc/grpc#26615]
### What version of gRPC and what language are you using?
1.38.1 - Python

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.2 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8.10

### What did you do?
Running a gRPC python server on a docker image.
The docker container is executed on a remote host.

### What did you expect to see?
A working grpc server.

### What did you see instead?
These errors, and no client requests processing:

```
INFO       2021-07-03 22:26:28,184 root                           <module>                             9   : Starting Server,
D0703 22:26:28.186779168       1 ev_posix.cc:173]            Using polling engine: epollex,
D0703 22:26:28.186949026       1 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb",
D0703 22:26:28.186964615       1 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental",
D0703 22:26:28.186977884       1 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental",
D0703 22:26:28.186983487       1 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first",
D0703 22:26:28.186986929       1 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin",
D0703 22:26:28.186993731       1 dns_resolver_ares.cc:499]   Using ares dns resolver,
D0703 22:26:28.187049332       1 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher",
D0703 22:26:28.187059505       1 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental",
D0703 22:26:28.187070283       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental",
D0703 22:26:28.187078316       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental",
D0703 22:26:28.187084520       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental",
I0703 22:26:28.188319532       1 socket_utils_common_posix.cc:429] Disabling AF_INET6 sockets because ::1 is not available.,
I0703 22:26:28.188364801       1 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter,
**I0703 22:26:28.188441210       1 tcp_server_posix.cc:325]    Failed to add :: listener, the environment may not support IPv6: {"created":"@1625351188.188348106","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50051"},**
INFO       2021-07-03 22:26:28,189 root                           run                                  22  : gRpc server started, listening on port 50051...,
D0703 22:26:35.870456263      14 tcp_posix.cc:1833]          cannot set inq fd=15 errno=92,
I0703 22:26:35.870562175      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state IDLE -> WRITING [TRANSPORT_FLOW_CONTROL],
I0703 22:26:35.870568516      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state WRITING -> WRITING+MORE [INITIAL_WRITE],
I0703 22:26:35.870607664      14 chttp2_transport.cc:1840]   perform_transport_op[t=0x7fdf4c002870]:  START_CONNECTIVITY_WATCH:watcher=0x7fdf4c004580:from=IDLE SET_ACCEPT_STREAM:0x7fdf6ac902b0(0x7fdf4c004768,...),
I0703 22:26:35.870626259      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state WRITING+MORE -> WRITING [begin write in current thread],
I0703 22:26:35.870691069      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state WRITING -> IDLE [finish writing],
I0703 22:27:15.643640550      14 chttp2_transport.cc:2913]   transport 0x7fdf4c002870 set connectivity_state=4,
I0703 22:27:15.643687208      14 chttp2_transport.cc:1840]   perform_transport_op[t=0x7fdf4c002870]:  SET_ACCEPT_STREAM:(nil)((nil),...),
```

It seems the server receives the connection from my client but then it never finishes processing it / responding (the service does a simple return operation and I tested it locally [not on docker]).

An interesting error is:

`**I0703 22:26:28.188441210       1 tcp_server_posix.cc:325]    Failed to add :: listener, the environment may not support IPv6: {"created":"@1625351188.188348106","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50051"},**`

I am not sure if this is causing the issue tho.

Also I am not sure if on a remote host the server might have a different address specification?
My server code:

```
server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
managerService_pb2_grpc.add_ManagerServicer_to_server(manager.Manager(), server)
server.add_insecure_port(f"[::]:50051")
server.start()
server.wait_for_termination()
```

Ideas? 

Thanks.

**Comment by ginwakeup** [comment]
<!--

### What version of gRPC and what language are you using?
1.38.1 - Python

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.2 LTS


### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8.10

### What did you do?
Running a gRPC python server on a docker image.
The docker container is executed on a remote host.

### What did you expect to see?
A working grpc server.

### What did you see instead?
These errors, and no client requests processing:


`
INFO       2021-07-03 22:26:28,184 root                           <module>                             9   : Starting Server,
D0703 22:26:28.186779168       1 ev_posix.cc:173]            Using polling engine: epollex,
D0703 22:26:28.186949026       1 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb",
D0703 22:26:28.186964615       1 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental",
D0703 22:26:28.186977884       1 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental",
D0703 22:26:28.186983487       1 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first",
D0703 22:26:28.186986929       1 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin",
D0703 22:26:28.186993731       1 dns_resolver_ares.cc:499]   Using ares dns resolver,
D0703 22:26:28.187049332       1 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher",
D0703 22:26:28.187059505       1 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental",
D0703 22:26:28.187070283       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental",
D0703 22:26:28.187078316       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental",
D0703 22:26:28.187084520       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental",
I0703 22:26:28.188319532       1 socket_utils_common_posix.cc:429] Disabling AF_INET6 sockets because ::1 is not available.,
I0703 22:26:28.188364801       1 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter,
**I0703 22:26:28.188441210       1 tcp_server_posix.cc:325]    Failed to add :: listener, the environment may not support IPv6: {"created":"@1625351188.188348106","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50051"},**
INFO       2021-07-03 22:26:28,189 root                           run                                  22  : gRpc server started, listening on port 50051...,
D0703 22:26:35.870456263      14 tcp_posix.cc:1833]          cannot set inq fd=15 errno=92,
I0703 22:26:35.870562175      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state IDLE -> WRITING [TRANSPORT_FLOW_CONTROL],
I0703 22:26:35.870568516      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state WRITING -> WRITING+MORE [INITIAL_WRITE],
I0703 22:26:35.870607664      14 chttp2_transport.cc:1840]   perform_transport_op[t=0x7fdf4c002870]:  START_CONNECTIVITY_WATCH:watcher=0x7fdf4c004580:from=IDLE SET_ACCEPT_STREAM:0x7fdf6ac902b0(0x7fdf4c004768,...),
I0703 22:26:35.870626259      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state WRITING+MORE -> WRITING [begin write in current thread],
I0703 22:26:35.870691069      14 chttp2_transport.cc:812]    W:0x7fdf4c002870 SERVER [ipv4:10.40.49.80:54452] state WRITING -> IDLE [finish writing],
I0703 22:27:15.643640550      14 chttp2_transport.cc:2913]   transport 0x7fdf4c002870 set connectivity_state=4,
I0703 22:27:15.643687208      14 chttp2_transport.cc:1840]   perform_transport_op[t=0x7fdf4c002870]:  SET_ACCEPT_STREAM:(nil)((nil),...),
`

It seems the server receives the connection from my client but then it never finishes processing it / responding (the service does a simple return operation and I tested it locally [not on docker]).

An interesting error is:

`**I0703 22:26:28.188441210       1 tcp_server_posix.cc:325]    Failed to add :: listener, the environment may not support IPv6: {"created":"@1625351188.188348106","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50051"},**`

I am not sure if this is causing the issue tho.

Also I am not sure if on a remote host the server might have a different address specification?
My server code:

```
server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
managerService_pb2_grpc.add_ManagerServicer_to_server(manager.Manager(), server)
server.add_insecure_port(f"[::]:{const.Grpc.LISTENING_PORT}")
server.start()
server.wait_for_termination()
```

Ideas? 

Thanks.

**Comment by lidizheng** [comment]
@ginwakeup Can you try to listen port `0.0.0.0:50051` instead? The Docker container might not support IPv6 as you suspected.

**Comment by ginwakeup** [comment]
> @ginwakeup Can you try to listen port `0.0.0.0:50051` instead? The Docker container might not support IPv6 as you suspected.

Hey @lidizheng , thanks for replying, apparently the issue was simply on a firewall block.
Closing.
