### ISSUE TITLE
Unary gRPC calls timeout but server still receives it and not cancelled 

### ISSUE THREAD

**Issue by ahtsan** [grpc/grpc#26625]
I have a client invoking unary gRPC request and retrying when each request times out, like

```
conn, err := grpc.Dial(serverURL, grpc.WithInsecure()
client = NewClient(conn)
...
for i := 1; i <= 10; i++ {
  ctx, _ := context.WithTimeout(context.Background(), time.Second * 5)
  
  rep, err = UnaryRPC(ctx)
  if err != nil {
    // retry after 5 sec
    time.Sleep(time.Second * 5);
  }
}
```

However, the server is still getting two RPC calls and replied to the second-last one which is already dropped. Also, I have the server checked all these requests and see if the context is cancelled but all of them are not.

Seems like when a gRPC call timeout, client side does not cancel the context automatically.

**Comment by donnadionne** [comment]
For the future, please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion
 
Your answer may already be there or you can post a new question if it is not.

**Comment by ahtsan** [comment]
I thought it might be a bug that when a gRPC call timeout, client side does not cancel the context automatically. Anyway, I'll try stackoverflow. Thanks :)
