### ISSUE TITLE
 Basic Tests PHP MacOS failing

### ISSUE THREAD

**Issue by itsemmanuelfrancis** [grpc/grpc#26647]
Basic Tests PHP MacOS is failing for the PR: #26471. The failure seems to be unrelated to the changes in the PR.
Log: https://source.cloud.google.com/results/invocations/04416b4c-6754-4ed8-a128-a88c8be78322/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_php/log

**Comment by stanley-cheung** [comment]
This should be fixed now
