### ISSUE TITLE
Artifact Build MacOS (internal CI) failing

### ISSUE THREAD

**Issue by itsemmanuelfrancis** [grpc/grpc#26646]
Artifact Build MacOS (internal CI) is failing for the PR: https://github.com/grpc/grpc/pull/26471. The failure seems to be unrelated to the changes in the PR.
Log: https://source.cloud.google.com/results/invocations/48c8e166-5cd7-4b5e-857e-7695288f909a/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log

**Comment by donnadionne** [comment]
This is a dup of https://github.com/grpc/grpc/issues/26653

PHP installation seems to be faling

**Comment by stanley-cheung** [comment]
Should be fixed now
