### ISSUE TITLE
linux/grpc_distribtests broken due to csharp

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#26651]
Error:

+ unzip -o /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip -d TestNugetFeed
unzip:  cannot find or open /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip, /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip.zip or /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip.ZIP.
+ FAILED=true

This started occuring on July 5th, was passing prior to that. 

This date of failure is same as https://github.com/grpc/grpc/issues/26650

**Comment by donnadionne** [comment]
This is impacting windows as well:


Running in workspace workspace_csharp_windows_x64

+ cd workspace_csharp_windows_x64

+ 'test\distrib\csharp\run_distrib_test.bat'




T:\src\github\grpc\workspace_csharp_windows_x64>cd /d T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp\





T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp>powershell -Command "Add-Type -Assembly 'System.IO.Compression.FileSystem'; [System.IO.Compression.ZipFile]::ExtractToDirectory('../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip', 'TestNugetFeed');"


Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find


file 'T:\src\github\grpc\input_artifacts\csharp_nugets_windows_dotnetcli.zip'."


At line:1 char:56


+ Add-Type -Assembly 'System.IO.Compression.FileSystem';


[System.IO.Compression.Zi ...


+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~


    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException


    + FullyQualifiedErrorId : FileNotFoundException








T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp>update_version.sh auto





T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp>set NUGET=nuget





T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp>cd DistribTest   || goto :error





T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp\DistribTest>nuget restore -PackagesDirectory ../packages   || goto :error


Invalid package version for package id 'Grpc': ''





T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp\DistribTest>echo Failed!


Failed!





T:\src\github\grpc\workspace_csharp_windows_x64\test\distrib\csharp\DistribTest>exit /b 1




2021-07-05 02:39:39,421 FAILED: distribtest.csharp_windows_x64 [ret=1, pid=384, time=51.5sec]

2021-07-05 02:39:39,967 ++ dirname tools/run_tests/artifacts/run_in_workspace.sh

**Comment by jtattermusch** [comment]
Currently the build is passing AFAICT. This was likely a problem with the artifact build step timing out, which made the build_packages step also fail. 
In the future, we'd need https://github.com/grpc/grpc/issues/26549 to make these kinds of issues easier to rootcause.
