### ISSUE TITLE
linux/grpc_build_packages fails on csharp

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#26650]
Error:
/usr/share/dotnet/sdk/2.1.816/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(198,5): error : Could not find a part of the path '/var/local/git/grpc/src/csharp/nativelibs/csharp_ext_macos_x64'. [/var/local/git/grpc/src/csharp/Grpc.Core/Grpc.Core.csproj]
+ FAILED=true

This has started occuring since July 5th; builds were passing before then.

**Comment by jtattermusch** [comment]
Currently the build is passing AFAICT. This was likely a problem with the artifact build step timing out, which made the build_packages step also fail. 
In the future, we'd need https://github.com/grpc/grpc/issues/26549 to make these kinds of issues easier to rootcause.
