### ISSUE TITLE
macos/grpc_build_artifacts failure due to php install failures

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#26653]
brew install php@7.2
==> Installing dependencies for php@7.2: apr, apr-util, argon2, aspell, brotli, c-ares, libidn, libmetalink, libssh2, jansson, jemalloc, libev, nghttp2, openldap, curl-openssl, unixodbc, freetds, libpq, libsodium, libzip and tidy-html5
==> Installing php@7.2 dependency: apr
==> Downloading https://homebrew.bintray.com/bottles/apr-1.7.0.mojave.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "apr"
Download failed: https://homebrew.bintray.com/bottles/apr-1.7.0.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.apache.org/dyn/closer.lua?path=apr/apr-1.7.0.tar.bz2
==> Downloading from https://downloads.apache.org/apr/apr-1.7.0.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/apr/1.7.0/libexec
==> make install
==> Caveats
apr is keg-only, which means it was not symlinked into /usr/local,
because Apple's CLT package contains apr.

If you need to have apr first in your PATH run:
  echo 'export PATH="/usr/local/opt/apr/bin:$PATH"' >> ~/.bash_profile

==> Summary
🍺  /usr/local/Cellar/apr/1.7.0: 59 files, 1.4MB, built in 1 minute 33 seconds
==> Installing php@7.2 dependency: apr-util
==> Downloading https://homebrew.bintray.com/bottles/apr-util-1.6.1_3.mojave.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "apr-util"
Download failed: https://homebrew.bintray.com/bottles/apr-util-1.6.1_3.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.apache.org/dyn/closer.lua?path=apr/apr-util-1.6.1.tar.bz2
==> Downloading from https://mirror.olnevhost.net/pub/apache/apr/apr-util-1.6.1.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/apr-util/1.6.1_3/libexec --with-apr=/usr/local/opt/apr --with-crypto --with-openssl=/usr/local/opt/openssl@1.1 --without-pgsql
==> make
==> make install
==> Caveats
apr-util is keg-only, which means it was not symlinked into /usr/local,
because Apple's CLT package contains apr.

If you need to have apr-util first in your PATH run:
  echo 'export PATH="/usr/local/opt/apr-util/bin:$PATH"' >> ~/.bash_profile

==> Summary
🍺  /usr/local/Cellar/apr-util/1.6.1_3: 54 files, 773.5KB, built in 21 seconds
==> Installing php@7.2 dependency: argon2
==> Downloading https://homebrew.bintray.com/bottles/argon2-20190702_1.mojave.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "argon2"
Download failed: https://homebrew.bintray.com/bottles/argon2-20190702_1.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/P-H-C/phc-winner-argon2/archive/20190702.tar.gz
==> Downloading from https://codeload.github.com/P-H-C/phc-winner-argon2/tar.gz/20190702
==> make PREFIX=/usr/local/Cellar/argon2/20190702_1 ARGON2_VERSION=20190702
==> make test
==> make install PREFIX=/usr/local/Cellar/argon2/20190702_1 ARGON2_VERSION=20190702
🍺  /usr/local/Cellar/argon2/20190702_1: 12 files, 591KB, built in 18 seconds
==> Installing php@7.2 dependency: aspell
==> Downloading https://homebrew.bintray.com/bottles/aspell-0.60.8.mojave.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "aspell"
Download failed: https://homebrew.bintray.com/bottles/aspell-0.60.8.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/aspell/aspell-0.60.8.tar.gz
==> Patching
patching file interfaces/cc/aspell.h
Hunk #1 succeeded at 246 (offset 9 lines).
Hunk #2 succeeded at 332 (offset 9 lines).
==> ./configure --prefix=/usr/local/Cellar/aspell/0.60.8

**Comment by donnadionne** [comment]
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_build_artifacts

Started failing around July 5th

**Comment by donnadionne** [comment]
The same issue impacts https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_distribtests

as well

**Comment by stanley-cheung** [comment]
Should be fixed now
