### ISSUE TITLE
How to bind Network Interface for C++ gRPC client

### ISSUE THREAD

**Issue by k72550** [grpc/grpc#26692]
Our system has an whitelist based on IP address to specify which gRPC client is allowed to connect. once before a new remote gRPC client join the network, the end user has to add its ip into the white list. Most time, it's easy for end user to know which NIC(ip) will be used by the gRPC client, but If there is too many NIC(ip) in the gRPC client node, it's hard for the end user to know which ip will be used before it's running, 'cause which NIC(ip) to be used is determine by the Linux system by default. Maybe 'route -n' command can be used to know the NICs priority, but the end user has to login via ssh, it makes a very bad user experience. So, Our customer deliver a new requirement which suggest us to bind a specified ip address for the gRPC client. I know it's easy for a normal socket programme to use 'bind' routine to bind an ip address for the client socket, but I don't know if there's some way for gRPC client(C++) to do that.

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
