### ISSUE TITLE
An error from SerializationTraits<T>::Serialize will crash the server

### ISSUE THREAD

**Issue by lidavidm** [grpc/grpc#26695]
### What version of gRPC and what language are you using?

v1.36.1, C++ 

### What operating system (Linux, Windows,...) and version?

Linux (Ubuntu 18.04)

```
$ uname -a
Linux partita 5.4.0-77-generic #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
> g++ --version 
g++ (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0
```

### What did you do?

We have a custom SerializationTraits<T>. If it returns an error, gRPC fails an assert and crashes.

This can be observed with the generic handler provided in gRPC as well. Example: modify the helloworld server:

```cpp
class GreeterServiceImpl final : public Greeter::Service {
  Status SayHello(ServerContext* context, const HelloRequest* request,
                  HelloReply* reply) override {
    std::string prefix("Hello ");
    reply->set_message(prefix + request->name());
    // XXX make the Protobuf larger than 2 GiB
    reply->mutable_message()->resize((1ul << 31) + 8);
    return Status::OK;
  }
};
```

### What did you expect to see?

We expected the error message from the serialization handler to either be logged or sent as an error to the client.

### What did you see instead?

gRPC fails an assertion and the server crashes:

```
Server listening on 0.0.0.0:50051
[libprotobuf ERROR google/protobuf/message_lite.cc:410] helloworld.HelloReply exceeded maximum protobuf size of 2GB: 2147483662
E0714 11:01:22.959755591    7710 call_op_set.h:315]          assertion failed: serializer_(msg_).ok()
fish: Job 1, './server' terminated by signal SIGABRT (Abort)
```

### Anything else we should know about your project / environment?

Our project has a custom serialization handler. 

We also noticed that if we return an error without initializing the output byte buffer or setting own_buf, then gRPC would also crash as it tries to duplicate the (uninitialized) output byte buffer without checking the status:

https://github.com/grpc/grpc/blob/a990f6f98717bb6d2a8a4034bce0092d54d27256/include/grpcpp/impl/codegen/call_op_set.h#L410-L412

**Comment by yashykt** [comment]
Yeah, that is true. This is a quirk of our current APIs. I'm not sure what can be done over here other than changing our APIs.

A workaround probably is to use gRPC with the serialized `ByteBuffer` type so the serialization/deserialization can be done by the applications instead of by gRPC library. It takes away from the convenience of the gRPC library, but I don't have a better suggestion at the moment.
