### ISSUE TITLE
xds-protos 0.0.10 missing message fields that were introduced in envoy 1.19

### ISSUE THREAD

**Issue by davidkornel** [grpc/grpc#26707]
Using python [xds-protos 0.0.10](https://github.com/grpc/grpc/tree/da2cf2559252c1fb8abbfca69b1a320526adabe4/tools/distrib/python/xds_protos). 
Envoy's newest version 1.19 was released on July 13. 
xds-protos 0.0.10 was built on July 14.
I'm assuming that the new envoy release (and the changes in the [data-plane-api](https://github.com/envoyproxy/data-plane-api))  triggered the new package version. I was waiting for it for a long time, but it seems like the new 0.0.10 is missing newly added message fields from envoy's data-plane-api.

[The one](https://github.com/envoyproxy/data-plane-api/blob/main/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto#L42) I realized that's missing was added on May 3. [Field](https://github.com/envoyproxy/data-plane-api/commit/aafecd0932bd628784de7b25e58950dd8dd1974a)  I checked a few newly added fields to the 1.19 and they were all missing. Maybe xds-protos 0.0.10 is the same as 0.0.8??

I could not find which data-plane-api branch was the 0.0.10 build based on, but I don't think that it was based on the Main branch on July 14

Checked the version: 
```
>>> version('xds-protos')
'0.0.10'
```
The package's corresponding part where the `key` field should appear:
```
_UDPPROXYCONFIG_HASHPOLICY.containing_type = _UDPPROXYCONFIG
_UDPPROXYCONFIG_HASHPOLICY.oneofs_by_name['policy_specifier'].fields.append(
  _UDPPROXYCONFIG_HASHPOLICY.fields_by_name['source_ip'])
_UDPPROXYCONFIG_HASHPOLICY.fields_by_name['source_ip'].containing_oneof = _UDPPROXYCONFIG_HASHPOLICY.oneofs_by_name['policy_specifier']
_UDPPROXYCONFIG.fields_by_name['idle_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_UDPPROXYCONFIG.fields_by_name['hash_policies'].message_type = _UDPPROXYCONFIG_HASHPOLICY
_UDPPROXYCONFIG.oneofs_by_name['route_specifier'].fields.append(
  _UDPPROXYCONFIG.fields_by_name['cluster'])
_UDPPROXYCONFIG.fields_by_name['cluster'].containing_oneof = _UDPPROXYCONFIG.oneofs_by_name['route_specifier']
DESCRIPTOR.message_types_by_name['UdpProxyConfig'] = _UDPPROXYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UdpProxyConfig = _reflection.GeneratedProtocolMessageType('UdpProxyConfig', (_message.Message,), {

  'HashPolicy' : _reflection.GeneratedProtocolMessageType('HashPolicy', (_message.Message,), {
    'DESCRIPTOR' : _UDPPROXYCONFIG_HASHPOLICY,
    '__module__' : 'envoy.extensions.filters.udp.udp_proxy.v3.udp_proxy_pb2'
    # @@protoc_insertion_point(class_scope:envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig.HashPolicy)
    })
  ,
  'DESCRIPTOR' : _UDPPROXYCONFIG,
  '__module__' : 'envoy.extensions.filters.udp.udp_proxy.v3.udp_proxy_pb2'
  # @@protoc_insertion_point(class_scope:envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig)
  })
_sym_db.RegisterMessage(UdpProxyConfig)
_sym_db.RegisterMessage(UdpProxyConfig.HashPolicy)


DESCRIPTOR._options = None
_UDPPROXYCONFIG_HASHPOLICY.oneofs_by_name['policy_specifier']._options = None
_UDPPROXYCONFIG_HASHPOLICY.fields_by_name['source_ip']._options = None
_UDPPROXYCONFIG.oneofs_by_name['route_specifier']._options = None
_UDPPROXYCONFIG.fields_by_name['stat_prefix']._options = None
_UDPPROXYCONFIG.fields_by_name['cluster']._options = None
_UDPPROXYCONFIG.fields_by_name['hash_policies']._options = None
_UDPPROXYCONFIG._options = None
```

There should be a line like this `_UDPPROXYCONFIG_HASHPOLICY.fields_by_name['key']._options = None`

**Comment by lidizheng** [comment]
@davidkornel Thanks for filing this PR. The data plane API library we are using might be outdated see https://github.com/grpc/grpc/tree/master/third_party. This causes `xds-protos` to not contain the latest Envoy proto changes.

The `v0.0.10` is part of a 27 removal in gRPC repo. If some team member or I have free cycles, we can update the `data-plane-api` repo we are using. Probably, in the next 2 weeks, before the branch cut of `v1.40.0`.

**Comment by davidkornel** [comment]
@lidizheng Thanks for the reply. Alright, I'll wait. I'll send a message here on next weeks Friday, just to make sure not to forget this.
