### ISSUE TITLE
Is _USE_32BIT_TIME_T important in vsprojects?

### ISSUE THREAD

**Issue by Zerqkboo** [grpc/grpc#2671]
Hi, I found that all [vsprojects](https://github.com/grpc/grpc/search?p=1&q=_USE_32BIT_TIME_T&utf8=%E2%9C%93) that build grpc libs in windows have a preprocessor definition called `_USE_32BIT_TIME_T`, which is related with type `time_t`, and the source code is:
```cpp
#ifndef _TIME_T_DEFINED
#ifdef _USE_32BIT_TIME_T
typedef __time32_t time_t;      /* time value */
#else  /* _USE_32BIT_TIME_T */
typedef __time64_t time_t;      /* time value */
#endif  /* _USE_32BIT_TIME_T */
#define _TIME_T_DEFINED         /* avoid multiple def's of time_t */
#endif  /* _TIME_T_DEFINED */
```
But visual studio 12 has some bugs that, `std::chrono` and `_USE_32BIT_TIME_T` don't work togther, which has been recorded [here](http://connect.microsoft.com/VisualStudio/feedbackdetail/view/972033/std-chrono-and-use-32bit-time-t-dont-work-togther). And in my project, I have to use grpc and std::chrono together, so I wonder if something will go wrong when I undefine `_USE_32BIT_TIME_T`, which I found ok on my very simple tests.

**Comment by jtattermusch** [comment]
Currently, the native layer used by C# relies on using 32-bit time_t. So by disabling it, you would definitely break C# on Windows. That said, I don't know any fundamental reason why this would be required, but it would require some work (I remember is was making some things easier in the early phases of the project, but I don't recall what specifically it was).

I think I will be happy to accept a pull request, given it doesn't break C#.

**Comment by larsonmpdx** [comment]
2nd data point: I just ran into this bug on vs12 (std::chrono vs _USE_32BIT_TIME_T) with git code from yesterday .  removing _USE_32BIT_TIME_T from grpc libraries and my application made everything work, no other changes required.

**Comment by jtattermusch** [comment]
we no longer use _USE_32BIT_TIME_T.

https://github.com/grpc/grpc/pull/4315
