### ISSUE TITLE
MacOS Artifact build timing out

### ISSUE THREAD

**Issue by drfloob** [grpc/grpc#26723]
For at least a week, the MacOS artifact build has been timing out. Nightly packages have not been published for _2 weeks_ due to this, as well as other reasons that have since been resolved (brew install issues).

**Comment by apolcyn** [comment]
This appears to also be happening on the 1.39.x branch, and so is blocking the 1.39.0 release

**Comment by apolcyn** [comment]
The build target that's timing out appears to be `build_artifact.ruby_native_gem_macos_x64`
