### ISSUE TITLE
Random  StatusCode.UNAVAILABLE: Connection reset by peer

### ISSUE THREAD

**Issue by Davitron** [grpc/grpc#26731]
### What version of gRPC and what language are you using?
python 3.7
grpcio latest

### What operating system (Linux, Windows,...) and version?
Debian  v9 (Docker container)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Kubernetes (EKS)

### What did you do?
Invoke a function via gRPC

### What did you expect to see?
Normal invocation and computed result

### What did you see instead?
```
<_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Connection reset by peer"
    debug_error_string = "{"created":"@1626692243.576262296","description":"Error received from peer ipv4:172.20.64.67:9010","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Connection reset by peer","grpc_status":14}"
```

### Anything else we should know about your project / environment?
There are no patterns to how this error occurs. We have no means of reproducing it, Which would have been helpful when troubleshooting

**Comment by AminAliH47** [comment]
I have encountered same problem, It's somehow doesn't happen with using retry at below link, though I don't think retry is proper solution.

**Comment by gnossen** [comment]
> `"Connection reset by peer"`

This sounds like a TCP-level issue. Are you sure that you have stable connectivity to your backend?
