### ISSUE TITLE
google.protobuf.empty is not defined

### ISSUE THREAD

**Issue by sadashivjp** [grpc/grpc#26745]
I tried with Counter example from grpc-dotnet. I am getting the error as "google.protobuf.empty" is not defined even after importing it in the top.

`syntax = "proto3";

import "google/protobuf/empty.proto";

package count;

// The counter service definition.
service Counter {
// Increment count by 1
rpc IncrementCount (google.protobuf.Empty) returns (CounterReply);
// Increment count through client stream of multiple counts
rpc AccumulateCount (stream CounterRequest) returns (CounterReply);
// Countdown with server stream
rpc Countdown (google.protobuf.Empty) returns (stream CounterReply);
}

// The request message containing the count to increment by
message CounterRequest {
int32 count = 1;
}

// The response message containing the current count
message CounterReply {
int32 count = 1;
}
`
What could be the problem? I tried in Asp.Net Core 3.1 LTS version.
Environment:
OS: Windows 10

**Comment by drfloob** [comment]
I don't think this has anything to do with gRPC's C# implementation, which is now deprecated regardless.
