### ISSUE TITLE
Call to non-existent service results in a DEADLINE_EXCEEDED rather than a more descriptive failure

### ISSUE THREAD

**Issue by dreveny** [grpc/grpc#2674]
If a gRPC client makes a call to a server requesting method "Foo" from service "Bar", but the server does not have "Bar" registered as a service, the RPC will timeout (or hang indefinitely if no timeout is used).

I would expect that a more descriptive StatusCode would be returned, such as UNKNOWN, NOT_FOUND, UNAVAILABLE, UNIMPLEMENTED, etc., rather than waiting the full timeout and then reporting DEADLINE_EXEEDED.

A simple mistake that caused the service namespace to differ between client and server caused this to happen for me and it took a while to debug since it looked more like a connection issue.  At least if it were logged somewhere it would have been easier to figure out what was going on.

**Comment by nathanielmanistaatgoogle** [comment]
In what languages are you writing your client and server code?

**Comment by dreveny** [comment]
C++.  Sorry, I should have mentioned that.  I can provide a snippet of code to show the issue, but it's very basic and not beyond what I described.

**Comment by yang-g** [comment]
This seems to be a duplicate of #483.
The fix is to return UNIMPLEMENTED.
