### ISSUE TITLE
No source for Python xds-protos version 0.0.10

### ISSUE THREAD

**Issue by musicinmybrain** [grpc/grpc#26756]
### What version of gRPC and what language are you using?

1.39.0 / Python

### What operating system (Linux, Windows,...) and version?

Fedora Linux — any; I am the maintainer of the relevant distribution packages.

### What runtime / compiler are you using (e.g. python version or version of gcc)

Irrelevant, but assume Python 3.9 or 3.10 with latest stable gcc.

### What did you do?

Visit https://pypi.org/project/xds-protos/0.0.10/#history and see version 0.0.10 of the `xds-protos` package.

Note that the PyPI package says its source code is in this repository (https://github.com/grpc/grpc/).

Look at https://github.com/grpc/grpc/blob/master/tools/distrib/python/xds_protos/setup.py and observe that the latest development version of grpc still generates `xds-protos` version 0.0.8.

### What did you expect to see?

Actual source code for generating the latest PyPI release of `xds-protos` is publicly available.

### What did you see instead?

Latest PyPI release of `xds-protos` appears to be generated from something other than the publicly available sources in this repository.

**Comment by lidizheng** [comment]
@musicinmybrain Sorry, I will try to close PR https://github.com/grpc/grpc/pull/26691 soon. `0.0.10` is part of 27 artifacts removal. The latest `xds-protos` removed 27 support completely, but content wise it's exactly the same as `xds-protos==0.0.8`.

**Comment by musicinmybrain** [comment]
Thanks—that’s a very helpful summary!

**Comment by musicinmybrain** [comment]
I see `xds-protos` 0.0.11 is released to PyPI with corresponding sources in this repository, so I am closing this issue. Thanks!

**Comment by lidizheng** [comment]
@musicinmybrain If you got a second, can you share your use case for the `xds-protos` package?

**Comment by musicinmybrain** [comment]
Sure! I am maintaining the `grpc` package in Fedora Linux, including the Python bindings. Since `grpc` 1.39.0, `xds-protos` is a dependency for the new `grpcio-admin` and `grpcio-csds` Python packages, so I package it too.

Since `xds-protos` has its own version number and release schedule, it’s packaged separately from `grpc`, but I do build it from the ultimate sources in this repo and relevant repos referenced as git submodules, rather than from the generated PyPI release tarball. That’s what lead me to file this issue in the first place.

**Comment by lidizheng** [comment]
Thanks. Good to learn.
