### ISSUE TITLE
Dynamically expose new gRPC's in a C++ server

### ISSUE THREAD

**Issue by manushawijekoon** [grpc/grpc#26781]
We have a requirement to expose multiple gRPC services through a single server listening in a single port. We also need to add and remove RPC's on the fly (without re-start of the server).

Platform is Linux and container is written in C++. 

The implementation of the service calls is fixed for all gRPC's as this container only needs to do some generic processing on the gRPC call before handing over to the actual back end which resides outside the container. This processing would involve things like access control, logging, rate limiting. Assuming this can be pre-written and loaded to the C++ container at start-up, what is left is to setup gRPC server (which is already running) to accept calls to new gRPC's and route them to the generic request processor. Similarly, we need to be able to remove gRPC's on the fly. This is like adding new http routes to an already running http server.

We are ok to dynamically load new libraries using 'dlopen' for example.

Is this supported in gRPC? If so where could I find more information.

Thank you

I think this 

One possible way to do this would be:
1. Implement new service 
2. Wrap this in a

**Comment by ctiller** [comment]
Have you looked at grpcs generic API?
