### ISSUE TITLE
v1.38.0 broken submodules reference

### ISSUE THREAD

**Issue by rnwhitehead** [grpc/grpc#26808]
Cloning v1.38.0 with the following command:
```
git -c advice.detachedHead=false clone --depth 1 --recurse-submodules --shallow-submodules -b v1.38.0 
```

Was working until just now.
Now it fails with:

```
fatal: expected shallow/unshallow, got ERR upload-pack: not our ref 436bd7880e458532901c58f4d9d1ea23fa7edd52
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'third_party/protobuf', but it did not contain 436bd7880e458532901c58f4d9d1ea23fa7edd52. Direct fetching of that commit failed.
```

It looks as if the submodule tag referenced has been deleted.

Same with v1.39.0

**Comment by rnwhitehead** [comment]
Also, trying to use the sources.zip / sources.tar.gz file didn't work -  CMake complains of missing makefiles.

**Comment by drfloob** [comment]
Duplicate of https://github.com/grpc/grpc/pull/26811, which tracks the fix as well. A protobuf repository change broke many open source tools.
