### ISSUE TITLE
[C#] Grpc.Tools 2.39.0-pre1 error

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#26819]
Client app setup to use Grpc.Tools version 2.39.0-pre1 errors when compiled.

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
    <PackageReference Include="Google.Protobuf" Version="3.17.3" />
    <PackageReference Include="Grpc.Net.Client" Version="2.38.0" />
    <PackageReference Include="Grpc.Tools" Version="2.39.0-pre1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

Proto: (I don't think this matters)
```proto
syntax = "proto3";

option csharp_namespace = "GrpcService57";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```

Error:

> Protos/greet.proto: Unknown generator option: no_server

![image](https://user-images.githubusercontent.com/303201/127405675-d84fcb7c-4794-4eef-b140-8e7a1b33e3be.png)

Changing Grpc.Tools to `2.38.0` fixes the problem

@apolcyn @jtattermusch

**Comment by JamesNK** [comment]
Reproducible from the command line:

![image](https://user-images.githubusercontent.com/303201/127405856-e8c4337d-2fcc-44fe-b495-2b9d496b04da.png)

**Comment by apolcyn** [comment]
Looks like this is a regression caused by https://github.com/grpc/grpc/pull/26162

I've opened https://github.com/grpc/grpc/pull/26896 on master and https://github.com/grpc/grpc/pull/26897 and https://github.com/grpc/grpc/pull/26898 to backport the fix to the previous and upcoming release branches.
