### ISSUE TITLE
[PHP] Unable to initialize module

### ISSUE THREAD

**Issue by Babwenbiber** [grpc/grpc#26823]
### What version of gRPC and what language are you using?
v1.39.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.2 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### What did you do?
Follow the php installation guide of this [this repo](https://github.com/grpc/grpc/tree/master/src/php):
```
$ git clone -b v1.39.0 https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ EXTRA_DEFINES=GRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK make
$ grpc_root="$(pwd)"
$ cd src/php/ext/grpc
$ phpize
$ GRPC_LIB_SUBDIR=libs/opt ./configure --enable-grpc="${grpc_root}"
$ make
$ [sudo] make install

set extension in php.ini

add grpc into composer
```
until here, everything worked perfectly. No errors or warnings!
```
composer install
```
composer didn't find grpc.so in the fold `/usr/lib/php/20190902/`, because the installation went into `/usr/lib/php/20200930/`.
Therefore, I copied the .so to this folder as well.
When I do a composer install now I get:

```
PHP Warning:  PHP Startup: grpc: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20190902
```

Composer doesn't exit with an error, but clearly something went wrong.

### What did you expect to see?

Composer install without any errors or warnings

### What did you see instead?
```
PHP Warning:  PHP Startup: grpc: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20190902
```

**Comment by stanley-cheung** [comment]
If you are on Ubuntu, the easiest way to install php grpc extension is via `pecl install grpc`.  Is there a specific reason you need to compile from source? 

From the error it looks like the PHP header files being used for compiling the extension is different from your actual `php` runtime. How do you install other pecl extension? You probably should figure out your environment first.

**Comment by Babwenbiber** [comment]
This did the same for me. But yes, it is significantly faster ;D
However, what did the trick for me was to upgrade from php7.4 to php8.0
