### ISSUE TITLE
is there any method to let server close the connection when client hasn't sent stream-request for a long time

### ISSUE THREAD

**Issue by Dsqds** [grpc/grpc#26835]
is there any method to let server close the connection when client hasn't sent stream-request for a long time

**Comment by drfloob** [comment]
The "new issue" form asks users not to post questions as Github issues. Please follow the instructions and use the channels mentioned below to ask questions. For reference, here is the default message that appears when you create a new issue:

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
