### ISSUE TITLE
[Compile] How to config compile options to make abseil-cpp to be .a instead of .so

### ISSUE THREAD

**Issue by LockLi** [grpc/grpc#26833]
#Version#
gRPC-1.36.1

#Compile#
Follow is my compile steps:
PATH="$PROTOBUF_BIN_PATH:$PATH"
mkdir -p cmake/build
cd cmake/build
cmake -DBUILD_SHARED_LIBS=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_INSTALL=ON gRPC_BUILD_CSHARP_EXT=OFF -DgRPC_SSL_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package \
              -DgRPC_PROTOBUF_PROVIDER=package -DProtobuf_INCLUDE_DIR=$PROTOBUF_INCLUDE_PATH -DProtobuf_LIBRARY=$PROTOBUF_LIB_PATH/libprotobuf.so.24.0.0 -DProtobuf_PROTOC_LIBRARY=$PROTOBUF_LIB_PATH/libprotoc.so.24.0.0 \
              -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${OPENSOURCE_OUTPUT}/${GRPC_SOFTWARE_NAME}/usr/local ../..
make -j20
make install

#Result#
libabsl_bad_optional_access.so
libabsl_bad_variant_access.so
libabsl_base.so
libabsl_city.so
libabsl_civil_time.so
libabsl_cord.so
libabsl_debugging_internal.so
libabsl_demangle_internal.so
libabsl_exponential_biased.so
libabsl_graphcycles_internal.so
libabsl_hash.so
libabsl_hashtablez_sampler.so
libabsl_int128.so
libabsl_log_severity.so
libabsl_malloc_internal.so
libabsl_raw_hash_set.so
libabsl_raw_logging_internal.so
libabsl_spinlock_wait.so
libabsl_stacktrace.so
libabsl_statusor.so
libabsl_status.so
libabsl_str_format_internal.so
libabsl_strings_internal.so
libabsl_strings.so
libabsl_symbolize.so
libabsl_synchronization.so
libabsl_throw_delegate.so
libabsl_time.so
libabsl_time_zone.so
libaddress_sorting.so -> libaddress_sorting.so.15
libaddress_sorting.so.15 -> libaddress_sorting.so.15.0.0
libaddress_sorting.so.15.0.0
libcares.a
libgpr.so -> libgpr.so.15
libgpr.so.15 -> libgpr.so.15.0.0
libgpr.so.15.0.0
libgrpc++_alts.so -> libgrpc++_alts.so.1
libgrpc++_alts.so.1 -> libgrpc++_alts.so.1.36.1
libgrpc++_alts.so.1.36.1
libgrpc++_error_details.so -> libgrpc++_error_details.so.1
libgrpc++_error_details.so.1 -> libgrpc++_error_details.so.1.36.1
libgrpc++_error_details.so.1.36.1
libgrpc_plugin_support.so -> libgrpc_plugin_support.so.1
libgrpc_plugin_support.so.1 -> libgrpc_plugin_support.so.1.36.1
libgrpc_plugin_support.so.1.36.1
libgrpcpp_channelz.so -> libgrpcpp_channelz.so.1
libgrpcpp_channelz.so.1 -> libgrpcpp_channelz.so.1.36.1
libgrpcpp_channelz.so.1.36.1
libgrpc++_reflection.so -> libgrpc++_reflection.so.1
libgrpc++_reflection.so.1 -> libgrpc++_reflection.so.1.36.1
libgrpc++_reflection.so.1.36.1
libgrpc++.so -> libgrpc++.so.1
libgrpc.so -> libgrpc.so.15
libgrpc++.so.1 -> libgrpc++.so.1.36.1
libgrpc++.so.1.36.1
libgrpc.so.15 -> libgrpc.so.15.0.0
libgrpc.so.15.0.0
libgrpc_unsecure_fenix.so
libgrpc++_unsecure.so -> libgrpc++_unsecure.so.1
libgrpc_unsecure.so -> libgrpc_unsecure.so.15
libgrpc++_unsecure.so.1 -> libgrpc++_unsecure.so.1.36.1
libgrpc++_unsecure.so.1.36.1
libgrpc_unsecure.so.15 -> libgrpc_unsecure.so.15.0.0
libgrpc_unsecure.so.15.0.0
libre2.so
libupb.so -> libupb.so.15
libupb.so.15 -> libupb.so.15.0.0
libupb.so.15.0.

#My qustion#
Files of abseil-cpp is so many , how can I compile abseil-cpp to be .a file, then integrate .a to other .so files.

**Comment by drfloob** [comment]
The "new issue" form asks users not to post questions as Github issues. Please follow the instructions and use the channels mentioned below to ask questions. For reference, here is the default message that appears when you create a new issue:

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
