### ISSUE TITLE
FLAKE: c_macos_opt_native.cmake/build/fork_test

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#26843]
Lidi, even though this is a problem in core, I'm assigning this to you, since I believe python is the only language that depends on fork support.

https://source.cloud.google.com/results/invocations/8fa5ae2d-97cd-4d30-9880-dd4d8373a80f/targets/github%2Fgrpc%2Frun_tests%2Fc_macos_opt_native/tests

```
D0730 08:55:57.985197000 4400715200 test_config.cc:161]                test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
E0730 08:56:06.001663000 4400715200 fork_test.cc:86]                   assertion failed: gpr_time_similar(end_time, est_end_time, tolerance)
*** SIGABRT received at time=1627660566 ***
PC: @     0x7fff60e852c2  (unknown)  __pthread_kill
```

**Comment by lidizheng** [comment]
Assigning to @ericgribkoff who lead the Python fork support effort.

**Comment by yashykt** [comment]
Closing since we decided not to track test flakes on github
