### ISSUE TITLE
`no_proxy` with an empty string causes grpcio to wildcard everything

### ISSUE THREAD

**Issue by bitspradp** [grpc/grpc#26858]
### What version of gRPC and what language are you using?
`Version` : 1.39.0
`Language`: Python

### What operating system (Linux, Windows,...) and version?
`OS`: Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
`Runtime`: Python 3.8.11

### What did you do?
`Steps to reproduce`:

1. We were running google cloud monitioring apis which were using `grpcio` library underneath.
2. To get past our proxy we had `https_proxy` and `no_proxy` variables set as following
```shell
export https_proxy=$proxy_server
export no_proxy=",127.0.0.1,localhost"
```
Notice the leading `,` for `no_proxy`. This was because we set a few values for `no_proxy` commonly leaving individual applications to add to that list using their own local variables which when unset resulted in the empty string at the beginning. 
3. This made `grpcio` wildcard everything and the requests were not hitting the proxy servers. 

### What did you expect to see?
Requests forwarded to the proxy server.

### What did you see instead?
We were seeing the following error - 
```
Unhandled exception while getting metrics, project=‘*****',
Traceback (most recent call last):
  File “/*/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File “/*/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File “/*/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1626360352.381792140","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1626360352.381790821","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>
```

### Anything else we should know about your project / environment?

This happens even when there is a `trailing-comma`

**Comment by gnossen** [comment]
Reassinging to Yash since he was the last to touch [the relevant file](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/http_proxy.cc).

**Comment by yashykt** [comment]
What's the reason for calling this a bug in gRPC rather than a bug in the application?
It seems weird to leave a leading comma or a trailing comma in the NO_PROXY string.

**Comment by bitspradp** [comment]
I would say the issue is more of handling a zero length string rather than a leading/trailing comma. The behavior in this case is too much of an issue. I would say it would be nice if we could throw a warning pointing to this rather and remove it from the list. What do you think?

**Comment by yashykt** [comment]
#29217 should make it work for you. Please take a look
