### ISSUE TITLE
C#: DeadlineExceeded sometimes seen as status "Internal" on client.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2685]
in C#, I have a simple scenario:

1. Client invokes a call that does nothing but blocks for long time and sets a much lower deadline.
2. Client expects DeadlineExceeded status, but receives "Internal" instead.

**Comment by jtattermusch** [comment]
Feel free to reassign.

**Comment by ctiller** [comment]
Deadline exceeded status is (unfortunately) best effort for grpc over http2.

CC: @a11r, @ejona86 

We track deadlines on both the client and on the server.
It can happen that the server deadline fires, and cancels the request using a HTTP2 RST_STREAM frame. Importantly, there's no way to represent deadline exceeded with RST_STREAM (but it's the only tool we have available). 
The packet can then be received on the client and propagated up *before* the client cancels its alarm.

The core library goes to some efforts to mitigate this in common cases, but AFAIK it's an impossible thing to fix completely without resorting to HTTP2 extensions, which we've been hesitant so far to pursue.
