### ISSUE TITLE
Python helloworld example greeter_client.py fails with grpc code 14

### ISSUE THREAD

**Issue by lambertsbennett** [grpc/grpc#26856]
### What version of gRPC and what language are you using?
gRPC 1.39.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.8

### What did you do?
Clone repository, run greeter_server.py, run greeter_client.py.

### What did you expect to see?
Response from greeter_server.py  "Hello, you!".

### What did you see instead?
```
Traceback (most recent call last):
  File ".\greeter_client.py", line 37, in <module>
    run()
  File ".\greeter_client.py", line 31, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "C:\Users\lambert.bennett-spen\Anaconda3\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\lambert.bennett-spen\Anaconda3\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1627883948.631000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1627883948.631000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by lambertsbennett** [comment]
This seems to be something to do with Windows. I can put the server code into a Docker container and it works fine.

**Comment by z3ke1r** [comment]
Any chance this has something to do with the Anaconda distribution of Python that the machine is using? I just tried this in a venv with just plain Python 3.7.6 distro and it worked.

**Comment by lambertsbennett** [comment]
This could be. I am using Anaconda. In the end I just started packaging my grpc apps in Docker containers, which works fine and is relatively painless.
