### ISSUE TITLE
 build_artifact.php_pecl_package_linux_x64 timeout

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#26863]
https://source.cloud.google.com/results/invocations/7cb8d7d3-079b-4169-b92f-cb958ab0f10e/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_build_artifacts/log

```
2021-08-02 11:52:55,404 TIMEOUT: build_artifact.php_pecl_package_linux_x64 [pid=8016, time=1808.2sec]
```

**Comment by stanley-cheung** [comment]
Job back to green.
