### ISSUE TITLE
fatal error: linux/unistd.h: No such file or directory

### ISSUE THREAD

**Issue by vallbuy** [grpc/grpc#26882]
pecl install grpc

docker
FROM php:7.3-fpm-alpine

/tmp/pear/temp/grpc/third_party/abseil-cpp/absl/base/internal/direct_mmap.h:36:10: fatal error: linux/unistd.h: No such file or directory
   36 | #include <linux/unistd.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1456: third_party/abseil-cpp/absl/base/internal/low_level_alloc.lo] Error 1
ERROR: `make' failed

**Comment by stanley-cheung** [comment]
@HannahShiSFB Can you please take a look?

**Comment by HannahShiSFB** [comment]
Please run
`apk add linux-headers`
to install the missing header files

**Comment by nicolkill** [comment]
really solved [in this place](https://stackoverflow.com/questions/52894632/cannot-install-pycosat-on-alpine-during-dockerizing)
