### ISSUE TITLE
Resolver changes notification will leak objects.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#2688]
This one took me a long time to debug, and I'm still not sure how to fix it, nor what is the proper course of action.

Basically if a resolver (say zookeeper) is calling its notification closure if the watched name changed, then the client channel's on_changed notification will not result in destroying an already established transport. The remaining upper reference (as in, the one that's orphan and needs to be unrefed) is the subchannel's state_watcher. During normal circumstances, on_state_changed is going to be tied to the iomgr's shutdown, but only if we have an active transport. Which is kind of a circular reference here: the subchannel's watcher op is held by the transport, and the transport is held by the subchannel. 

So I'm not sure how to solve that one gracefully. When we are creating a new transport, we could know which was the one before, and call its on_changed on it. Probably. Maybe.

**Comment by ctiller** [comment]
So I fixed a few similar bugs in #2477. I'd want to check that this doesn't manifest there also before doing too much here.

The basic idea is to disconnect any old channels, which puts them into FATAL_FAILURE (changing state), which when seen cancels the watch chain.

**Comment by nicolasnoble** [comment]
Okay :-) I was looking at pull requests when I got sucked into that intense debugging exercise. It's not obvious this will fix it, but I am guessing adding a test for it wouldn't be too hard.

**Comment by hongweiwang** [comment]
I merged this pull request and tested it again. In my experiment, the client performed two RPCs. A change happened to zookeeper after the first RPC, leading to re-resolving zookeeper address before the second RPC. The result showed that it failed to free 2 iomgr objects compared with 1 object in previous experiment before merging the pull request.

**Comment by ctiller** [comment]
OK I think I know what to do about this. Could you point me to a pull request with a failing test under asan, and I'll send you a fix.

**Comment by hongweiwang** [comment]
#2549 My zookeeper test under asan did not fail, but in the terminal it showed iomgr objects leaks.

**Comment by dgquintas** [comment]
Obsolete?
