### ISSUE TITLE
Basic Tests Python Windows "file has vanished"

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#26886]
https://source.cloud.google.com/results/invocations/b8b72acf-3c14-421d-b046-3979c54defc4/targets/grpc%2Fcore%2Fpull_request%2Fwindows%2Fgrpc_basictests_python/log

This is probably due to a timeout

**Comment by gnossen** [comment]
Closing out since this has not been seen in over a week.

**Comment by jtattermusch** [comment]
The logs being flooded with "file has vanished" messages are a consequence of an unrelated issue if a build times out and should be fixed by https://github.com/grpc/grpc/pull/28259.
