### ISSUE TITLE
[objective-c] GRXImmediateWriter.m:writeUntilPausedOrStopped  _enumerator may be nil

### ISSUE THREAD

**Issue by wangscu** [grpc/grpc#2690]
[objective-c] GRXImmediateWriter.m:writeUntilPausedOrStopped  _enumerator may be nil。

grpc ios client crash, and point that in GRXImmediateWriter.m:writeUntilPausedOrStopped  _enumerator is nil.

the crash is sometimes happen, i suppose the reason is the other thread invoke   [writeable writesFinishedWithError:errorOrNil] async when some error happen like tcp closed。

@jcanizales

**Comment by jcanizales** [comment]
Hi,

could you paste here the information in XCode's log window when that crash happens? That will include the stack trace of the exception and its message, which is necessary to understand the cause.

**Comment by jcanizales** [comment]
I was able to replicate it! :) Currently debugging it.

**Comment by jcanizales** [comment]
Stack trace and exception.
<img width="1440" alt="screen shot 2015-08-07 at 11 49 44 am" src="https://cloud.githubusercontent.com/assets/5120183/9143331/818218fc-3cfa-11e5-81bb-6038ef121194.png">

It seems the problem wasn't that `_enumerator` became `nil` (which would have just ended the loop). Rather than there's a race and, because object reads and writes aren't atomic in ARC, two happened concurrently and this code ended up reading garbage (pointer value `0x3`).

**Comment by jcanizales** [comment]
Notes:
* `ImmediateWriter->_writeable` was set to `nil` before its `startWithWriteable` returned from `writeUntilPausedOrStopped`.
* `ImmediateWriter->_state` was set to garbage after being set to `Started`.
* The while loop in `writeUntilPausedOrStopped` went through one iteration successfully, setting `value` to the `AUTHRequest` object. It's possible that a race between reading and setting `_state` made the loop proceed when it shouldn't have.
* The `ForwardingWriter` that wraps the `ImmediateWriter` had its `writeable` (originally, the `ProtoRPC` object) set to `nil` before `[_writer startWithWriteable:self];` returned.
* Its `_writer` was also set to `nil`, but after the correct wrapped writer was started by the call above.
* The `ForwardingWriter` is a `MappingWriter`, as expected.
* The `_requestsWriter` of the `ProtoRPC` was set to `nil` before `[_requestWriter startWithWriteable:self];` (in `GRPCCall-invokeCall`) returned, but after it had successfully messaged the correct writer.
* `ProtoRPC->_state` is `NotStarted`, and is never set in `GRPCCall.m` to started!?

**Comment by jcanizales** [comment]
Ok, (8) implies `finishWithError:` was called on the `GRPCCall`, which notably sets `_requestsWriter` to `nil` _after_ setting its state to `Finished`. Per `GRPCCall-writeValue:`, this could have been called from the completion queue thread when the first write failed.

**Comment by jcanizales** [comment]
The two alternative solutions are to make writers thread-safe (guaranteeing that state modifications take immediate effect _if_ they're made on the same thread that executed the writeable method / that started the writer), or to serialize all `GRPCCall`'s messages to its writer.
