### ISSUE TITLE
function JsonStrongToMessage(...) generate free double-free in protobuf

### ISSUE THREAD

**Issue by mingqiangyin** [grpc/grpc#26934]

**Comment by mingqiangyin** [comment]
#0  raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000007f9ad874a4 in dcos_ms_sig_handler2 () from /usr/local/lib/dji/dcos/libdcos_ms.so
#2  <signal handler called>
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x0000007f9a9478b4 in __GI_abort () at abort.c:79
#5  0x0000007f9a98065c in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f9aa41b88 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#6  0x0000007f9a9869c4 in malloc_printerr (str=str@entry=0x7f9aa3d858 "double free or corruption (out)") at malloc.c:5350
#7  0x0000007f9a9885d8 in _int_free (av=0x7f9aa67a70 <main_arena>, p=0x21983550, have_lock=<optimized out>) at malloc.c:4278
#8  0x0000007f9afd6224 in google::protobuf::internal::GenericTypeHandler<google::protobuf::FieldDescriptorProto>::Delete (arena=0x0, value=<optimized out>) at ./google/protobuf/repeated_field.h:662
#9  google::protobuf::internal::RepeatedPtrFieldBase::Destroy<google::protobuf::RepeatedPtrField<google::protobuf::FieldDescriptorProto>::TypeHandler> (this=<optimized out>, this=<optimized out>)
    at ./google/protobuf/repeated_field.h:1465
#10 0x0000007f9afd6b7c in google::protobuf::RepeatedPtrField<google::protobuf::FieldDescriptorProto>::~RepeatedPtrField (this=0x219348f8, __in_chrg=<optimized out>)
    at ./google/protobuf/repeated_field.h:1923
#11 google::protobuf::DescriptorProto::~DescriptorProto (this=0x219348e0, __in_chrg=<optimized out>) at google/protobuf/descriptor.pb.cc:3723
#12 0x0000007f9afd6bec in google::protobuf::DescriptorProto::~DescriptorProto (this=0x219348e0, __in_chrg=<optimized out>) at google/protobuf/descriptor.pb.cc:3726
#13 0x0000007f9afd6c6c in google::protobuf::internal::GenericTypeHandler<google::protobuf::DescriptorProto>::Delete (arena=0x0, value=<optimized out>) at ./google/protobuf/repeated_field.h:662
#14 google::protobuf::internal::RepeatedPtrFieldBase::Destroy<google::protobuf::RepeatedPtrField<google::protobuf::DescriptorProto>::TypeHandler> (this=<optimized out>, this=<optimized out>)
    at ./google/protobuf/repeated_field.h:1465
#15 0x0000007f9afd7830 in google::protobuf::RepeatedPtrField<google::protobuf::DescriptorProto>::~RepeatedPtrField (this=0x7feabfcb70, __in_chrg=<optimized out>)
    at ./google/protobuf/repeated_field.h:1923
#16 google::protobuf::FileDescriptorProto::~FileDescriptorProto (this=0x7feabfcb40, __in_chrg=<optimized out>) at google/protobuf/descriptor.pb.cc:1855
#17 0x0000007f9afb1854 in google::protobuf::DescriptorPool::TryFindFileInFallbackDatabase (this=this@entry=0x219514e0, name="sensor_table.proto") at google/protobuf/descriptor.cc:1824
#18 0x0000007f9afb1990 in google::protobuf::DescriptorPool::FindFileByName (this=this@entry=0x219514e0, name="sensor_table.proto") at google/protobuf/descriptor.cc:1392
#19 0x0000007f9b0019b4 in google::protobuf::internal::(anonymous namespace)::AssignDescriptorsImpl (table=0x547e60 <assign_descriptors_table_sensor_5ftable_2eproto>)
    at google/protobuf/generated_message_reflection.cc:2354
#20 0x0000007f9ae11c00 in __pthread_once_slow (once_control=0x547e60 <assign_descriptors_table_sensor_5ftable_2eproto>, init_routine=0x7f9ab9dec0 <__once_proxy>) at pthread_once.c:116
#21 0x0000007f9aff6a00 in __gthread_once (__func=<optimized out>, __once=0x547e60 <assign_descriptors_table_sensor_5ftable_2eproto>) at /usr/include/aarch64-linux-gnu/c++/7/bits/gthr-default.h:699
#22 std::call_once<void (&)(google::protobuf::internal::AssignDescriptorsTable const*), google::protobuf::internal::AssignDescriptorsTable*&> (
    __f=@0x7f9b001908: {void (const google::protobuf::internal::AssignDescriptorsTable *)} 0x7f9b001908 <google::protobuf::internal::(anonymous namespace)::AssignDescriptorsImpl(google::protobuf::internal::AssignDescriptorsTable const*)>, __once=...) at /usr/include/c++/7/mutex:684
#23 google::protobuf::internal::AssignDescriptors (table=<optimized out>, table@entry=0x547e60 <assign_descriptors_table_sensor_5ftable_2eproto>) at google/protobuf/generated_message_reflection.cc:2398
#24 0x00000000004c2e00 in config::SensorTable::GetMetadata (this=<optimized out>)
    at /data/Matrix/workspace/jenkins.br1609/storage/20210805200824_7971/catkin_ws/src/storage/release_version/build/src/sensor_table.pb.cc:1693
#25 0x0000007f9b09e3d4 in google::protobuf::Message::GetDescriptor (this=0x2195aa50) at ./google/protobuf/message.h:356
#26 google::protobuf::util::JsonStringToMessage (input=..., message=message@entry=0x2195aa50, options=...) at google/protobuf/util/json_util.cc:261

**Comment by yashykt** [comment]
I'm not sure what the question is but looking at the stacktrace, looks like something for the protobuf repo
