### ISSUE TITLE
Coroutines

### ISSUE THREAD

**Issue by vitruvvius** [grpc/grpc#26945]
### Is your feature request related to a problem? Please describe.

As coroutines / async functions become mainstream across every language, it would make a lot of sense for grpc to transition to coroutines and/or expose an async api on completion queues to open the opportunity to define our own co_routine implantation

### Additional context
Driven by my usage w/ tonic & its hardware utilization on a single core

**Comment by yashykt** [comment]
gRPC C++ is moving to the world of callback APIs. Please take a look at https://github.com/grpc/proposal/blob/master/L67-cpp-callback-api.md

**Comment by vitruvvius** [comment]
i definitely understand - c++ coroutines are also ugly :) i was referring to the current callback apis. the part i enjoy about coroutines or other approaches to grpc with async support happens to be in the simplicity

**Comment by vitruvvius** [comment]
thanks @npuichigo! i'll check it out
