### ISSUE TITLE
Precompiled Library

### ISSUE THREAD

**Issue by vitruvvius** [grpc/grpc#27008]
### Is your feature request related to a problem? Please describe.
It's quite cumbersome to have to rebuild the grpc library for new machines - it would make a lot more sense to have a public grpc static library for every new version

### Describe the solution you'd like
online archive of grpc static libraries for each version

**Comment by veblush** [comment]
@vitruvvius Thank you for the proposal and do you have an idea on how to achieve it? for example; reference OSS libraries doing this well?
