### ISSUE TITLE
CMake flag to disable `gen_percent_encoding_tables` and similar tools

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#27017]
### Is your feature request related to a problem? Please describe.

Building gRPC with CMake on Windows generates (possibly false positive) anti-virus warnings, e.g.:

https://www.virustotal.com/gui/file/16cdaabee73df523ddb91fd4f3a10cf967c9ed4445c423cfec5ae13c8a9dfd36/detection

This causes unnecessary friction when trying to use gRPC in those platforms.

### Describe the solution you'd like

These tools are not necessary for gRPC users, they should not be compiled by default.  Consider defining them with `EXCLUDE_FROM_ALL`:

https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_ALL.html#prop_tgt:EXCLUDE_FROM_ALL
https://cmake.org/cmake/help/latest/command/add_executable.html

e.g.:

```
add_executable(gen_percent_encoding_tables EXCLUDE_FROM_ALL ...)
```

### Describe alternatives you've considered

A CMake option to disable these tools would also be acceptable.

### Additional context

N/A

**Comment by ctiller** [comment]
Reassigning. I'm going to occasionally eliminate the need for these tools, but that opportunistic work shouldn't be counted upon to solve this problem. We likely do need a way to disable generation of these tools, and of our dependencies tests, as part of our cmake story.

**Comment by jtattermusch** [comment]
I haven't found "gen_percent_encoding_tables" anywhere in the repo.

There are some C-core codegen things in https://github.com/grpc/grpc/tree/master/tools/codegen/core but honestly I don't understand how they can trigger an antivirus warning.

**Comment by coryan** [comment]
> I haven't found "gen_percent_encoding_tables" anywhere in the repo.
> 

https://github.com/grpc/grpc/blob/v1.38.x/tools/codegen/core/gen_percent_encoding_tables.cc

apparently no longer there.

> There are some C-core codegen things in https://github.com/grpc/grpc/tree/master/tools/codegen/core but honestly I don't understand how they can trigger an antivirus warning.

Me neither. But they do (or did).

**Comment by ctiller** [comment]
I removed the gen_percent_encoding_tables tool. I'm figuring generally we
could remove anything in tools/core/codegen from the cmake build though:
those tools are for developers of gRPC, and I think trying to support them
in cmake is probably a thing we don't need to do.

**Comment by jtattermusch** [comment]
> > I haven't found "gen_percent_encoding_tables" anywhere in the repo.
> 
> https://github.com/grpc/grpc/blob/v1.38.x/tools/codegen/core/gen_percent_encoding_tables.cc
> 
> apparently no longer there.
> 
> > There are some C-core codegen things in https://github.com/grpc/grpc/tree/master/tools/codegen/core but honestly I don't understand how they can trigger an antivirus warning.
> 
> Me neither. But they do (or did).

Can you check that the antivirus still triggers warnings even after `gen_percent_encoding_tables` was removed? If not, we can close the issue.

**Comment by jtattermusch** [comment]
Btw, it looks like the only remaining item is "gen_" tool in our cmake is `gen_hpack_tables` https://github.com/grpc/grpc/blob/4a267667b73ce961438cdaf398f9d70a51ad7155/build_handwritten.yaml#L33,
but if we removed it from build_handwritten.yaml, it would also disappear from the cmake build, and cmake is currently the only way to build it (it's not available in bazel BUILD or in Makefile). So we would need to remove gen_hpack_tables.cc entirely (no need to keep a file that cannot be built by the build system).

**Comment by coryan** [comment]
> 
> Can you check that the antivirus still triggers warnings even after `gen_percent_encoding_tables` was removed? If not, we can close the issue.

Oh sorry, I should have mentioned that I was filing this on behalf of some other folks.  But I will ask them.

**Comment by coryan** [comment]
FWIW, I compiled it myself and it was clean:

https://www.virustotal.com/gui/file/6c2fc34a079e1978c2cfde6548dfae97ac9f9c864c83241d77ff688d02c22ff6/detection
