### ISSUE TITLE
C# generated service method names should follow C# naming convention

### ISSUE THREAD

**Issue by nickdul** [grpc/grpc#2703]
trying to use the same protobuf definition both for Java and C#
```
service MyService {
    rpc get_meta_data(MyRequestMessage) returns (MyResponse) {}
}
```
unfortunately `Grpc.Tools.0.6.0\tools\protoc` does not transform service method names to CamelCase
:exclamation: on other hand message fields names are converted as expected

**Comment by jtattermusch** [comment]
As per https://developers.google.com/protocol-buffers/docs/style:

**If your .proto defines an RPC service, you should use CamelCase (with an initial capital) for both the service name and any RPC method names:**

**Comment by jtattermusch** [comment]
So your rpc should actually be named GetMetaData and thus service method names will be up to C# standards.
