### ISSUE TITLE
Cross compile: compile arm gRPC on x86_64 host failed because of grpc_cpp_plugin not executable

### ISSUE THREAD

**Issue by LockLi** [grpc/grpc#27034]
### What version of gRPC and what language are you using?
gRPC-1.36.1

### What operating system (Linux, Windows,...) and version?
Linux x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-7.3.3
cmake-3.18.3

### What did you do?
cross compile arm grpc on x86_64 host.
I have provided executable protoc and grpc_cpp_plugin，which were compiled on x86_64 host, but I don't know how to configurate compile configuration to run them.

### What did you expect to see?
cross compile succeeded.

### What did you see instead?
While cross compiling, grpc_cpp_plugin in the compilation path was executed by default.

[100%] Building CXX object CMakeFiles/grpc++_error_details.dir/src/cpp/util/error_details.cc.o
/usr1/jenkins/workspace/FenixMainService/VRP/opensource/grpc/grpc-1.36.1/cmake/build/grpc_cpp_plugin: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
CMakeFiles/grpc++_reflection.dir/build.make:82: recipe for target 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc' failed
make[2]: *** [gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Error 1
CMakeFiles/Makefile2:493: recipe for target 'CMakeFiles/grpc++_reflection.dir/all' failed
make[1]: *** [CMakeFiles/grpc++_reflection.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr1/jenkins/workspace/FenixMainService/VRP/opensource/grpc/grpc-1.36.1/cmake/build/grpc_cpp_plugin: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
CMakeFiles/grpcpp_channelz.dir/build.make:82: recipe for target 'gens/src/proto/grpc/channelz/channelz.grpc.pb.cc' failed
make[2]: *** [gens/src/proto/grpc/channelz/channelz.grpc.pb.cc] Error 1
CMakeFiles/Makefile2:559: recipe for target 'CMakeFiles/grpcpp_channelz.dir/all' failed
make[1]: *** [CMakeFiles/grpcpp_channelz.dir/all] Error 2
[100%] Building CXX object CMakeFiles/grpc++_alts.dir/src/cpp/common/alts_context.cc.o
[100%] Building CXX object CMakeFiles/grpc++_alts.dir/src/cpp/common/alts_util.cc.o
[100%] Linking CXX shared library libgrpc++_error_details.so
[100%] Built target grpc++_error_details
[100%] Linking CXX shared library libgrpc++_alts.so
[100%] Built target grpc++_alts
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment]
Could you try to use the existing cross compilation test [script](https://github.com/grpc/grpc/blob/4dff0ee48a91452b5cb23ea8202661b30ff70d11/test/distrib/cpp/run_distrib_test_cmake_aarch64_cross.sh)?

**Comment by LockLi** [comment]
> Could you try to use the existing cross compilation test [script](https://github.com/grpc/grpc/blob/4dff0ee48a91452b5cb23ea8202661b30ff70d11/test/distrib/cpp/run_distrib_test_cmake_aarch64_cross.sh)?

The script can slove my problem of cross compiling. Thank you so much!
