### ISSUE TITLE
gRPC failed to process compressed response in cronet transport channel

### ISSUE THREAD

**Issue by qlisc** [grpc/grpc#27046]
### What version of gRPC and what language are you using?
v1.33.2 C++

### What operating system (Linux, Windows,...) and version?
IOS, Android ( we use same c++ code in both IOS and Android)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc Apple clang version 12.0.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

We are using cronet channel with gRPC-C++ library. The cronet channel creation example code.
std::shared_ptrgrpc::ChannelCredentials cronetChannelCredentials =
grpc::CronetChannelCredentials([Cronet getGlobalEngine]);
auto channel = grpc::CreateChannel(target, cronetChannelCredentials);

Client sends a gRPC request accepting gzip response. Server returns the gzip compressed response with header "content-encoding=gzip"

### What did you expect to see?
gRPC request succeeds.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

The request failed with DEADLINE_EXCEEDED error code. From grpc trace log, we can see the parsed length from cronet transport is not correct. It's a negative number:
[DEBUG ../src/core/ext/transport/cronet/transport/cronet_transport.cc:1211] length field = -1962409984

If server returns uncompressed response and without "content-encoding=gzip" header, the request success. In this case, we see the processed length from cronet transport is correct. e.g.
[DEBUG ../src/core/ext/transport/cronet/transport/cronet_transport.cc:1211] length field = 98

**Comment by veblush** [comment]
@qlisc Can you try to use the latest version of gRPC (1.39 or later)? You might hit the bug (e.g. https://github.com/grpc/grpc/issues/25352) fixed already.

**Comment by qlisc** [comment]
Hi @veblush, I built and tested with v1.39 gRPC-c++ library. The error is same. This should be different from https://github.com/grpc/grpc/issues/25352. #25352 is related to request compression (client to server direction). This issue is related to response compression (server to client direction).

**Comment by qlisc** [comment]
Hi @veblush,

In addition, we found gzip compressed response works if we use ssl/http2 channel. 

For the compressed response data (e.g, response with content-encoding=gzip header), do you know where the received data are decompressed in grpc-cronet transport stack? e.g. in grpc or cronet stack? Here is one of our findings during investigation. From the [grpc http2 transport source code](https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L1898), looks like the received gzipped data are decompressed in grpc http2 transport code. However, from grpc cronet transport code, we didn't find any decompressing related actions.

Thanks!

**Comment by veblush** [comment]
As cronnet is not actively maintained, I'm not sure what we can do on this issue. @sampajano Any suggestions?

**Comment by sampajano** [comment]
@veblush thanks for ccing.

Recently, Cronet team has decided to deprecate cronet on ios. Also I believe c++ cronet is not officially supported on android either. I will find out more details from cronet team and publish a proposal here (in Jan.)

@qlisc I suppose that you're seeing this issue on both iOS and Android? I would tend to assume that the decompression happens in Cronet even tho i'm not 100% sure yet. I wonder if the issue happens for you if you use other transport? It might help us isolate the issue better.

**Comment by veblush** [comment]
I'm closing this as we've decided to stop supporting Cronet.
