### ISSUE TITLE
Make a new bidi streaming ping pong test with 2 threads per side

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2705]
Have two threads per side, and make one thread the reader and one the writer; this will help expose some concurrency bugs.

**Comment by apolcyn** [comment]
@vjpai is this still relevant?

**Comment by vjpai** [comment]
It's still relevant. We still don't have this, but it's really low priority. I'd prefer to leave it open but move it to "Someday"

**Comment by vjpai** [comment]
It's not a P2 bug. It's a pure feature request.

**Comment by vjpai** [comment]
Possibly not relevant but reassigning to Nana if this might be useful.

**Comment by nanahpang** [comment]
Does this require a new test to reveal the bug of read/write concurrently using two threads on client/server side?
