### ISSUE TITLE
DNS resolution fails on iOS due to ipv6 issues

### ISSUE THREAD

**Issue by kwan-research** [grpc/grpc#27092]
The call to `getaddrinfo` https://github.com/grpc/grpc/blob/cc9c8c06d9a9583846b7d95ae0201d07bd809824/src/core/lib/iomgr/resolve_address_posix.cc#L83 hangs for 30 seconds, then fails with `EAI_NONAME` on iOS when ipv6 DNS is not available.

This is causing problems with the iOS version of Firebase Firestore https://github.com/firebase/firebase-ios-sdk/issues/8503 which can take a few minutes to establish a connection to the server. The problem is intermittent, however. Sometimes it connects straight away.

To reproduce, use a Mac on a network where `dig -6 firestore.googleapis.com` fails, and run an iOS app in a simulator.

This is similar to https://github.com/dart-lang/sdk/issues/41451 where the problem is described in more detail.

It appears to be a bug in Apple's code, but note that the use of `getaddrinfo` in iOS is [not recommended](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/ResolvingDNSHostnames.html) by Apple.

**Comment by tpouriel** [comment]
Hi ! I'm coming here after reading issues [8503](https://github.com/firebase/firebase-ios-sdk/issues/8503) and [9571](https://github.com/firebase/flutterfire/issues/9571) from flutterfire and firebase ios sdk projects.
I have some of my flutter app's users that can't connect to firestore when using cellular network, having the error 

`10.14.0 - [FirebaseFirestore][I-FST000001] WatchStream (104870d08) Stream error: 'Unavailable: DNS resolution failed for firestore.googleapis.com: UNKNOWN: nodename nor servname provided, or not known'`

Any updates on this issue ?

**Comment by rafiqlightwala** [comment]
@tpouriel did you find any solution?

**Comment by SinyavtsevIlya** [comment]
Facing the same issue.
@rafiqlightwala @tpouriel Did you manage to solve this?

**Comment by brianmichel** [comment]
Hey just chiming in here that we see intermittent DNS failures on Windows using gRPC via Firebase's C++ SDK and eventually got routed here as well.

**Comment by polymath74** [comment]
Still a problem for me today at the end of 2024, on a good wifi connection. Auth works fine but Firestore appears to believe the network is down.

```
I0000 00:00:1735614341.376916 1493143 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
nw_connection_get_connected_socket_block_invoke [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x6000033032a0 Failed : error 0:50 [50]
I0000 00:00:1735614341.406886 1493152 subchannel.cc:806] subchannel 0x107963310 {address=ipv6:%5B2404:6800:4006:814::200a%5D:443, args={grpc.client_channel_factory=0x600000024050, grpc.default_authority=firestore.googleapis.com, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x60000260a940, grpc.internal.client_channel_call_destination=0x10558c120, grpc.internal.event_engine=0x6000000242b0, grpc.internal.security_connector=0x600002c2ce00, grpc.internal.subchannel_pool=0x6000029280e0, grpc.keepalive_time_ms=30000, grpc.primary_user_agent=grpc-c++/1.65.1, grpc.resource_quota=0x600000ca5aa0, grpc.server_uri=dns:///firestore.googleapis.com}}: connect failed (UNKNOWN:(domain:NSPOSIXErrorDomain, code:50, description:The operation couldn’t be completed. Network is down) {file:"/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/ZipRelease/2024-07-25T04-01-28/project-ios/Pods/gRPC-Core/src/core/lib/transport/error_utils.cc", file_line:150, created_time:"2024-12-31T13:05:41.406755+10:00", grpc_status:2}), backing off for 976 ms```
