### ISSUE TITLE
[C++] Allow interceptor to modify serialized send and recv message

### ISSUE THREAD

**Issue by cfredri4** [grpc/grpc#27103]
### Is your feature request related to a problem? Please describe.
I have the need to (separately, in addition to TLS transport) encrypt the payload sent between a gRPC client and server. Using grpc-java it is trivial to use an interceptor to modify the marshaller/serializer of the request to first marshall/serialize and then encrypt the bytes (or decrypt the bytes and then unmarshal/deserialize to a message).
Using C++ it appears I can only modify the non-serialized send message via [`ModifySendMessage`](https://grpc.github.io/grpc/cpp/classgrpc_1_1experimental_1_1_interceptor_batch_methods.html#a6be8b4eecdd2ddf3913369dd3b275d43); there is no way to modify the serialized send message, or modify the recv message at all.

### Describe the solution you'd like
A way for a C++ interceptor to get and modify the serializer of the message, similar to what can be done in grpc-java.

### Describe alternatives you've considered
A way for a C++ interceptor to modify both the serialized send and recv message. E.g. `ModifySerializedSendMessage`, `GetSerializedRecvMessage`, `ModifySerializedRecvMessage`.

**Comment by markdroth** [comment]
Yash and Esun, I'm not sure how feasible it is for us to provide a way to do this via the interceptor API.  Is there a reasonable alternative for this use case, such as maybe providing custom `SerializationTraits`?

**Comment by yashykt** [comment]
This is interesting. Some quick comments -
The `ByteBuffer` returned by `GetSerializedSendMessage` is modifiable so I believe that should satisfy the needs on the send side.
On the receive side, there is `GetRecvMessage`, but the message has already been deserialized at that point.

**Comment by yashykt** [comment]
One way I can think of to achieve this without using the interception API is to use the generic async API with ByteBuffer. That way the application is completely responsible for serialization and deserialization.

**Comment by yashykt** [comment]
On the interception API side, if we want to do this, I think we can do this by changing deserialization to only be done in a lazy manner and then provide a `GetSerializedRecvMessage()` method to modify the serialized recv message.

**Comment by yashykt** [comment]
> Is there a reasonable alternative for this use case, such as maybe providing custom SerializationTraits?

I think that might be the cleanest way to do this. (Provide a custom `SerializationTraits` for that message type.) 
This is also what tensorflow is doing - https://github.com/tensorflow/tensorflow/blob/86fb36271f9068f84ddcecae74fe0b7df9ce83ee/tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.h#L33

**Comment by yashykt** [comment]
@cfredri4 Do you think that satisfies your purpose?

**Comment by cfredri4** [comment]
Thanks for the suggestions! I did not know about custom `SerializationTraits`; it sounds like that could work but it would unfortunately be a bit... cumbersome. This would be used with a lot (hundreds) of different message types/clients, and so hence the desire to have one single interceptor that could be added everywhere.

But that `GetSerializedSendMessage` returns a modifiable `ByteBuffer` solves half the problem! Would a similar `GetSerializedRecvMessage` be considered a good addition?

**Comment by engjq** [comment]
I wanna do sth like: 
```
ModifySendMessage(custom_encryption(GetSerializedSendMessage()))
```
How can i recovery(decrypt) the message in recv side,
and continue the rpc procedure? Any api can help?

**Comment by cfredri4** [comment]
@engjq `GetSerializedSendMessage` returns a **modifiable** `ByteBuffer`. I don't know C++ but you would do something like:

```
custom_encryption(GetSerializedSendMessage())
```

But as mentioned above, this would only solve encrypting the message being sent.

If you want to decrypt received messages, then something like a `GetSerializedRecvMessage` and lazy deserialization as suggested by @yashykt will need to be implemented in grpc. I'm still interested in this but I don't know enough C++ to submit a pull request for this.

**Comment by engjq** [comment]
yes,I wanna do sth like below indeed:
in send:
```
ModifySendMessage(custom_encrypt(GetSerializedSendMessage()))
```
and
in recv:
```
ModifyRecvMessage(custom_decrypt(GetSerializedRecvMessage()))
```
thx,and waiting for your pr ,haha

> @engjq `GetSerializedSendMessage` returns a **modifiable** `ByteBuffer`. I don't know C++ but you would do something like:
> 
> ```
> custom_encryption(GetSerializedSendMessage())
> ```
> 
> But as mentioned above, this would only solve encrypting the message being sent.
> 
> If you want to decrypt received messages, then something like a `GetSerializedRecvMessage` and lazy deserialization as suggested by @yashykt will need to be implemented in grpc. I'm still interested in this but I don't know enough C++ to submit a pull request for this.

**Comment by engjq** [comment]
Got some help from 
```
https://stackoverflow.com/questions/23963978/c-protobuf-how-to-iterate-through-fields-of-message
```
