### ISSUE TITLE
Decide whether to use CV notify inside lock or outside

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2714]
There is a choice between doing a CV notify inside the controlling lock or outside it; this usually does not cause any kind of race. However, there may be a performance difference. Our usage pattern is to consistently use the notify inside the lock, but we should see if this is the correct decision.

**Comment by ctiller** [comment]
pthreads on linux at least delays the broadcast/signal until the mutex is actually released - with the advantage that we avoid the possibility of using a double-wakeup.

I'd like to (at some point) ensure we use cv.wait(..., predicate) -- there exist platforms that can optimize for this by checking if predicate is true before issuing the wakeup.

**Comment by vjpai** [comment]
I read that also, which is why I think we are doing the right thing. But I want to make sure that this is the case in a cross-platform sense.

**Comment by ctiller** [comment]
Moot given we no longer have CV's on the critical path.
