### ISSUE TITLE
Converting tensorflow.python.framework.ops.EagerTensor to : bytes, unicode

### ISSUE THREAD

**Issue by K-bhuvan** [grpc/grpc#27151]
gRPC was expecting a byte format value. The query request is not liking the tensor type into the gRPC. I am pretty new to gRPC/APIs. 

    Traceback (most recent call last):
      File "basic_grpc_example.py", line 120, in <module>
        request = client.PrimalRequest(
    TypeError: <tf.Tensor: shape=(1, 512), dtype=int32, numpy=
    array([[  101,  1053,  2015,  2966,  2373,  1997,  4 has type tensorflow.python.framework.ops.EagerTensor, but expected one of: bytes, unicode

Have tried using .tobytes() & byte casting it not liking the tensor format for some reason, Any help is appreciated.

**Comment by gnossen** [comment]
I'm taking the heart emoji as a sign that the issue has been resolved and closing the issue.
