### ISSUE TITLE
how to do the same for client.cc with c++?

### ISSUE THREAD

**Issue by Hazhir007** [grpc/grpc#27176]
Can you please run this under these environment variables:

`GRPC_VERBOSITY=DEBUG`
`GRPC_TRACE=cares_resolver,cares_address_sorting`

and share the output? That will print some useful extra debug info.

_Originally posted by @apolcyn in https://github.com/grpc/grpc/issues/23273#issuecomment-648347127_

**Comment by markdroth** [comment]
If you're asking how to set environment variables, I suggest you consult your shell manual.

This isn't a gRPC problem, so I'm closing this.
