### ISSUE TITLE
Address all TODOs in the interop test specification before GA 

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#2724]
Finalize the set of tests to be done and ensure there is a spec for each case we want to cover, in  https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md,

**Comment by ctiller** [comment]
I'd add a higher goal of having them all implemented and passing before GA.

**Comment by a11r** [comment]
Agreed. Updated the issue description to capture that.

**Comment by ctiller** [comment]
If this is not done now, then it won't be done by GA date.

**Comment by ctiller** [comment]
Propose closing it.

**Comment by jayantkolhe** [comment]
ack.. closing..
