### ISSUE TITLE
Failed to deserialize response message on latest VS 2022 Preview

### ISSUE THREAD

**Issue by AqlaSolutions** [grpc/grpc#27244]
### What version of gRPC and what language are you using?
gRPC 2.39.1, C#, VS 2022 17.0.0 Preview 3.1

### What operating system (Linux, Windows,...) and version?
Windows 10 19043.1165

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS with msbuild, project targets .net core 3.1

### What did you do?
I switched from VS 2019 to VS 2022 on our existing project.
I can't copy-paste a service contract here (because of NDA) but it's a simple method call on a service and the error is reproducable even on empty response class.

### What did you expect to see?
Successful method call.

### What did you see instead?
GrpcException with "Failed to deserialize response message" and no inner exception or other details.

**Comment by Stevecaboose** [comment]
I am able to reproduce this in vs2022 running .net5 and also .net6
Inner exception is swallowed at some point

**Comment by davidjward30** [comment]
I can reproduce this too using the ASP.NET Core template grpc sample (GreeterService). An additional observation is that if you use VS2022 but start the server on the commandline then it works fine.

**Comment by davidjward30** [comment]
Bug reported in VS2022: 

https://developercommunity.visualstudio.com/t/unable-to-debug-grpc-server-code-with-preview-3/1503691

Workaround is to disable Hot CSS Reload.
