### ISSUE TITLE
Ruby Jenkins Flake

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2727]
```
Failures:

  1) the http client/server behaves like basic GRPC message delivery is OK completes calls by sending status to client and server
     Failure/Error: expect(svr_batch.message).to eq sent_message
       
       expected: "sent message"
            got: nil
       
       (compared using ==)
     Shared Example Group: "basic GRPC message delivery is OK" called from ./spec/client_server_spec.rb:398
     # ./spec/client_server_spec.rb:184:in `block (2 levels) in <top (required)>'
```

https://grpc-testing.appspot.com/job/gRPC_pull_requests/1452/config=dbg,language=ruby,platform=linux/testReport/(root)/tests/tools_run_tests_run_ruby_sh/

**Comment by ctiller** [comment]
Seen testing #2726

**Comment by jayantkolhe** [comment]
any update?

**Comment by tbetbetbe** [comment]
@jayantkolhe
I'm removing the beta milestone and pushing this to GA
- this flake still occurs (so the bug should not be closed) but this is more about the test than the behaviour being tested

Details
- the affected test was originally single-threaded
- it was updated to be multi-threaded in response changes in the core server.
- somehow the synchronization around the threading is not correct; e.g, there are other tests that also run servers on their own thread but are not as flaky

**Comment by yang-g** [comment]
Is this fixed?
