### ISSUE TITLE
Release 1.40.0 does not appear on pypi

### ISSUE THREAD

**Issue by Lordnibbler** [grpc/grpc#27273]
I see https://github.com/grpc/grpc/releases/tag/v1.40.0 was released yesterday, but on pypi I only see up to 1.40.0rc1: https://pypi.org/project/grpcio/#history

**Comment by drfloob** [comment]
CC @gnossen. The release tag has been created, but I don't believe the python artifacts have been pushed yet. Barring any build issues, I expect this'll be done soon.

**Comment by gnossen** [comment]
[Artifacts pushed.](https://pypi.org/project/grpcio/1.40.0/)
