### ISSUE TITLE
Missing published Ruby gems for versions >= 1.39.0

### ISSUE THREAD

**Issue by fotos** [grpc/grpc#27288]
### What version of gRPC and what language are you using?

`1.40.0` / Ruby 💎 

### What operating system (Linux, Windows,...) and version?

MacOS 11.5.2 (20G95)

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
$ gcc --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### What did you do?

Want to upgrade to the latest released `grpc` version.

There have been a couple of releases (e.g.[`v1.40.0`](https://github.com/grpc/grpc/releases/tag/v1.40.0), [`v1.39.1`](https://github.com/grpc/grpc/releases/tag/v1.39.1) and [`v.1.39.0`](https://github.com/grpc/grpc/releases/tag/v1.39.0) that do not have [corresponding Ruby gems published to rubygems.org](https://rubygems.org/gems/grpc).

### What did you expect to see?

Versions `v1.40.0`, `v1.39.1` and `v1.39.0` to be published to rubygems.org.

### What did you see instead?

Only pre release versions are published:

- [1.39.0.pre1](https://rubygems.org/gems/grpc/versions/1.39.0.pre1-x86-linux)
- [1.40.0.pre1](https://rubygems.org/gems/grpc/versions/1.40.0.pre1-x86-linux)

The actual releases are missing.

**Comment by apolcyn** [comment]
Both 1.39.0 and 1.40.0 have just been pushed. Sorry for the delay.

**Comment by fotos** [comment]
Thanks @apolcyn! 🙌
