### ISSUE TITLE
Cryptic error when installing 1.40.0 in a Python 2.7 environment 

### ISSUE THREAD

**Issue by Manelmc** [grpc/grpc#27284]
### What version of gRPC and what language are you using?
grpcio 1.40.0
Python

### What operating system (Linux, Windows,...) and version?
Linux version 4.20.11-1.el7.elrepo.x86_64 (mockbuild@Build64R7)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
Python 2.7.5
pip 21.0

### What did you do?
Install package that has grpcio as a dependency. This time the version 1.40.0 was pulled instead of the 1.39.0 which resulted in the following error.

### What did you expect to see?
Either a python 2.7 compatible version should be pulled or an explanatory error message should be thrown. Feels like the missing python_requires metadata should be fixed so pip is not confused.

### What did you see instead?
```
Collecting grpcio>=1.27.1
  Downloading http://jp2p-r2p2-pypi.prod.hnd2.bdd.local/root/pypi/%2Bf/3d1/72158fe886a26/grpcio-1.40.0.tar.gz (21.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/coconuts/lama-venv/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vxBOXZ/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vxBOXZ/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iI5dtz
         cwd: /tmp/pip-install-vxBOXZ/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vxBOXZ/grpcio/setup.py", line 255, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-vxBOXZ/grpcio/setup.py", line 205, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by drfloob** [comment]
Python2.7 is no longer supported. See https://github.com/grpc/grpc/pull/26691 for the removal. CC @lidizheng

**Comment by drfloob** [comment]
Sorry, I missed this bit

> Feels like the missing python_requires metadata should be fixed so pip is not confused.

I had thought that was done already. Reopening for @lidizheng to look at.

**Comment by lidizheng** [comment]
@Manelmc The error is generated via the compilation steps, any error could happen due to different environment.

I would recommend to use our compiled binary wheels instead:

```
python2 -m pip install grpcio --only-binary=:all:
```

**Comment by crwilcox** [comment]
@lidizheng I would suggest adding `python_requires` in in setup.py it will prevent this for future users. The workaround above should work to unblock folks, but adding python_requires will help pip do the right thing.

For example https://github.com/googleapis/python-firestore/blob/main/setup.py#L89

**Comment by lidizheng** [comment]
@crwilcox Thanks, this is very helpful! I didn't know `setuptool` has this option. The PR is up at https://github.com/grpc/grpc/pull/27495. We might also need a bit more change to the distribution tests, and yank the version without `python_requires` to improve 2.7 and 3.5 users experience.

**Comment by crwilcox** [comment]
@lidizheng is this issue close-able?

**Comment by lidizheng** [comment]
The PR is merged and working fine. I would close this issue.
