### ISSUE TITLE
Basic Tests Python Windows Timeout

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#27299]
```
ERROR: Aborting VM command due to timeout of 5400 seconds
```

https://source.cloud.google.com/results/invocations/10900a08-303f-4599-ac18-3d43fe7aa87b/targets/grpc%2Fcore%2Fpull_request%2Fwindows%2Fgrpc_basictests_python/log

The test seems to be timing out

**Comment by gnossen** [comment]
```
++ dirname tools/internal_ci/helper_scripts/delete_nonartifacts.sh
+ cd tools/internal_ci/helper_scripts/../../..
+ find . -type f -not -iname '*sponge_log.*' -not -path './reports/*' -not -path './artifacts/*' -not -path './tools/internal_ci/*' -exec rm -f '{}' +


ERROR: Aborting VM command due to timeout of 5400 seconds
```

The test is seemingly timing out during a cleanup step.

**Comment by gnossen** [comment]
Regardless, this issue has not been seen in over a week. Going ahead and closing out for now.
