### ISSUE TITLE
aarch64 pip wheel not found for version 1.39.0

### ISSUE THREAD

**Issue by vinnnyr** [grpc/grpc#27305]
### What version of gRPC and what language are you using?
Attempting to install `1.39.0`

### What operating system (Linux, Windows,...) and version?
Ubuntu Docker Image, on an aarch64 machine

```
root@2b08dea4c476:/# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)
```
```
root@2b08dea4c476:/# uname -m
aarch64
```
### What runtime / compiler are you using (e.g. python version or version of gcc)
```
root@2b08dea4c476:/# python3 --version
Python 3.8.10
```
```
root@2b08dea4c476:/# python3 -m pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

### What did you do?
In a fresh ubuntu docker container, running on an `aarch64` machine, I attempted to pip install grpcio==1.39.0:
```
root@2b08dea4c476:/# python3 -m pip install grpcio==1.39.0
```
### What did you expect to see?
Based on the conversation here: https://github.com/grpc/grpc/issues/21283#issuecomment-916738990 
The wheels for 1.39.0 are being built and hosted.

I expected to see the wheel being downloaded, like in version 1.38.0:
```
root@2b08dea4c476:/# python3 -m pip install grpcio==1.38.0
Collecting grpcio==1.38.0
  Downloading grpcio-1.38.0-cp38-cp38-manylinux2014_aarch64.whl (39.3 MB)
     |████████████████████████████▏   | 34.6 MB 4.3 MB/s eta 0:00:02^C
ERROR: Operation cancelled by user
```

### What did you see instead?
You can see that this pulls down the tar for version 1.39.0, and builds the wheel, which is undesired. 
```
root@2b08dea4c476:/# python3 -m pip install grpcio==1.39.0
Collecting grpcio==1.39.0
  Downloading grpcio-1.39.0.tar.gz (21.3 MB)
     |████████████████████████████████| 21.3 MB 4.4 MB/s 
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... -^canceled
```

### Anything else we should know about your project / environment?
I don't think so.

**Comment by drfloob** [comment]
I think the problem might be that your OS and pip versions are too old. The [requirements](https://github.com/pypa/manylinux) for manylinux_2_24 are:

* pip >= 20.3 -- you have pip==20.0.2
* Ubuntu >= 21.04 -- you have 20.04.3
* CPython 3.8.10 -- you're good here.

CC @jtattermusch

**Comment by jtattermusch** [comment]
I will close this as the aarch64 wheels definitely are there (but as noted, they are manylinux_2_24):
https://pypi.org/project/grpcio/1.39.0/#files

I think https://github.com/grpc/grpc/issues/27305#issuecomment-916990591 is right about why you are unable to install the wheels.
