### ISSUE TITLE
unlock of unowned mutex

### ISSUE THREAD

**Issue by wanggujin** [grpc/grpc#27324]
I build the master branch in vs2019.
but when i run the example cpp/route_guide/route_guide_callback_server.cc  and cpp/route_guide/route_guide_callback_client.cc. 
it is failed in RouteChat() function in server side. 
the failed message is: unlock of unowned mutex.

Does anyone know why ?

**Comment by drfloob** [comment]
I can't reproduce this on linux or mac, and don't have a Windows machine handy at the moment to test it on. Have you modified the route_guide code at all? If not, we'll need to know more about your environment to determine if there's a bug here. Stack traces would help as well.

**Comment by markdroth** [comment]
Closing this due to lack of response from the poster.
