### ISSUE TITLE
[Python+gevent] Python client gets stuck while reading from grpc stream under load

### ISSUE THREAD

**Issue by nidhi-doshi** [grpc/grpc#27340]
### What version of gRPC and what language are you using?
grpc version  `1.35.0`. Client is in python and server is in golang.

### What operating system (Linux, Windows,...) and version?
Running in docker with Ubuntu 21.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Client is using python with gevent: 
```
Python 3.7.3
grpcio==1.35.0
protobuf==3.12.2
gevent==21.1.2
```

Server is in Golang
`google.golang.org/grpc v1.35.0`

### What did you do?
We have a golang server that implements a server-side streaming endpoint to stream files. 

Proto definition of the streaming response
```
message ReadFileResp {
    optional bytes content = 1;
}
```

Golang server code that sends bytes on the stream
```
	buffer := make([]byte, ReadFileStreamBufferSizeKB*1024)
	for {
		n, readErr := reader.Read(buffer)
		bytesRead += n
		streamErr := stream.Send(ReadFileResp{Content: buffer[:n]})
		if streamErr != nil {
			msg := fmt.Sprintf("Failed to send contents to stream: %v", streamErr)
			return status.NewError(status.Internal, streamErr, msg).GRPCErr()
		}
		if readErr == io.EOF {
			return nil
		} else if readErr != nil {
			msg := fmt.Sprintf("Failed to read content from file. Path: %v. Err: %v", path, readErr)
			return status.NewError(status.Internal, readErr, msg).GRPCErr()
		}
	}
```

Python client code reads from the stream and collects the data into a bytearray
```
    content = bytearray()

    try:
      for read_resp in in_stream:
        if len(read_resp.content) > 0:
          content.extend(read_resp.content)
    except Exception as e:  # catch all exceptions to align with thrift file client
      msg = 'Readfile RPC stream error: {}'.format(e)
      logging.error(msg)`
```

We are calling this server-side streaming api from the python client under load, making approximately 40-80 concurrent requests at a time and running for 10s of minutes.

### What did you expect to see?
Expect to see the streaming read requests complete.
If the load is too high, we expect the latency to increase or the requests to fail. 

### What did you see instead?
After about 10-15 minutes of running under load, all calls to this streaming api get stuck in the python client. 

- Once a particular client node enters this state, it remains stuck indefinitely. Reducing/stopping the load does not help it recover.  Restarting the server does not help, but restarting that particular client does.
- While a client node is in this state, other grpc clients nodes are able to continue successfully communicating with the grpc server. 
- This happens with both streaming and unary rpc calls.
- If we call the streaming api after the client gets stuck, we can see the request successfully reaching the server and the server sending the contents back on the stream. However, on the client side we never receive the contents of the stream. 
- Once the client gets stuck, subsequent calls to the streaming api seem to increase the CPU usage, which never goes back down (maybe we are entering an infinite loop?). Dumping the cpu profile of such a stuck client shows the following information. Even with no load on the system, ncalls for the top functions keeps going up. 

```
`{"status": "OK", "stats": ["
Clock type: CPU
Ordered by: totaltime, desc

name                                  ncall  tsub      ttot      tavg      
..vent/thread.py:99 LockType.acquire  171..  0.762530  2.090877  0.000012
..ges/grpc/_common.py:105 _wait_once  570..  0.040233  1.147533  0.000020
...7/threading.py:264 Condition.wait  570..  1.240049  1.145259  0.000020
..timeout.py:264 _start_new_or_dummy  57024  0.143530  1.139789  0.000020
..eout.py:239 Timeout._on_expiration  57024  0.738490  1.001224  0.000018
..es/gevent/timeout.py:243 start_new  57024  0.325641  0.996259  0.000017
../threading.py:198 _RLock._is_owned  57022  0.139721  0.445448  0.000008
..event/timeout.py:219 Timeout.start  57024  0.258610  0.381557  0.000007
..ing.py:184 _RLock._acquire_restore  57022  0.179657  0.324623  0.000006
..ages/gevent/thread.py:72 get_ident  57022  0.189061  0.305727  0.000005
..nt/timeout.py:349 Timeout.__exit__  57024  0.149478  0.262571  0.000005
..nt/timeout.py:199 Timeout.__init__  57024  0.226992  0.226992  0.000004
..t/timeout.py:341 Timeout.__enter__  57024  0.125360  0.188608  0.000003
..pc/_channel.py:788 _response_ready  57022  0.165941  0.165941  0.000003
..ent/timeout.py:285 Timeout.pending  114..  0.130459  0.130459  0.000001
..event/timeout.py:302 Timeout.close  57024  0.113093  0.113093  0.000002
..eading.py:188 _RLock._release_save  57022  0.111618  0.111618  0.00000
```

### Anything else we should know about your project / environment?
This only seems to happen while running the python client code in docker. 
If I run the server and client code locally on my Mac, I am unable to reproduce the issue. However, if I run the client code inside docker on my Mac laptop, it reproduces consistently.

**Comment by gnossen** [comment]
The gRPC Python gevent implementation is somewhat orphaned at the moment. The tests are known to be flaky and the original author has left the team. There is an active effort to reimplement gevent support in gRPC Python that should be finished in the next few weeks. We will revisit this issue once this effort has been completed.

**Comment by mz-heesun** [comment]
I have the same problem.

in app.py
`
from gevent.monkey import patch_all
patch_all()
import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()
`


I have the same code as below, and I'm seeing intermittent hangs.
The problem does not occur when running without using gevent.
An error occurs when running with both gevent and grpc.

I also checked with docker.
In docker, there are two workers so that the entire logic flows.
I ran the test.

When I request three or four times with ab -n 1000 -c 100 url, it stopped.
The cpu usage is initially set at 30% and then continues to increase.

This seems to be a problem with grpc and gevent.

**Comment by RexTim** [comment]
We are facing this exact same problem.

Is reimplementing gevent support still on the roadmap?

**Comment by gnossen** [comment]
The gevent reimplementation is complete. We have fixed a lot of issues and expect things to be much more stable. @RexTim What version of `grpcio` are you running? Have you tested on `1.51.1`? If not, can you please try that and report back?
