### ISSUE TITLE
Getting "Files has invalid value" using `msbuild /t:Publish`

### ISSUE THREAD

**Issue by jsk95** [grpc/grpc#27366]
### What version of gRPC and what language are you using?
Grpc.Core 2.37.0. C#.

### What operating system (Linux, Windows,...) and version?
Windows Version 10.0.19042 Build 19042

### What runtime / compiler are you using
Runtime: .NET Framework 4.8
Build: .NET SDK 5/Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework

### What did you do?
Ran "msbuild.exe" "project.csproj" /t:Publish /p:Configuration=Release /p:NoBuild:true /m

### What did you expect to see?
Publish to finish successfully

### What did you see instead?
```
C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(267,5): error MSB3021: Unable to copy file "C:\Users\TeamCityAgent\.nuget\packages\grpc.core\2.37.0\build\net45\..\..\runtimes\linux-x64\native\libgrpc_csharp_ext.x64.so" to "bin\publish\C:\Users\TeamCityAgent\.nuget\packages\grpc.core\2.37.0\build\net45\..\..\runtimes\linux-x64\native\libgrpc_csharp_ext.x64.so". The given path's format is not supported. 
```

This is what the publish targets look like in .NET 5 SDK (Microsoft.NET.Publish.targets)
![image](https://user-images.githubusercontent.com/48934750/133559777-ce4e0956-4273-49f8-86fc-8b025aea059a.png)

### Anything else we should know about your project / environment?
No but we did not face this issue with 2.29.0

**Comment by jtattermusch** [comment]
Re-reading the questions, it seems that you might not be actually trying to build Grpc.Core from the source (but it's also a bit unclear what is it you're trying to do - would you mind clarifying it?).

**Comment by jsk95** [comment]
Found out that it was a problem with one of our custom tasks in publish that was causing headaches with hintpath. Will close the issue.
