### ISSUE TITLE
When a build_step in run_tests.py isn't executable, the test fails silently

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2736]
The only message is "Some tests failed".

**Comment by dgquintas** [comment]
Maybe obsolete?

**Comment by jcanizales** [comment]
Is @nicolasnoble a better assignee?

**Comment by dgquintas** [comment]
Maybe. On the other hand this is python related

**Comment by soltanmm** [comment]
Totally'd forgotten this was assigned to me. Not sure it should've been. Also not sure if this is still even a thing.
