### ISSUE TITLE
Find a local server that runs SSL, add tests against it.

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2739]
`interop/server.cc` declares but doesn't use the `use_ssl` flag apparently.

Needed to test #2429 (and obviously for test coverage).

**Comment by yang-g** [comment]
The enable_ssl flag is checked in server_helper.cc :)

**Comment by jcanizales** [comment]
Ah nice! What certificates and ssl target name do I have to use to connect to it?

**Comment by yang-g** [comment]
You may want to use what is under src/node/test/data

**Comment by jcanizales** [comment]
Haha `foo.test.google.fr`? :D
Thanks!
