### ISSUE TITLE
Python multiprocessing server example uses single process on macOS

### ISSUE THREAD

**Issue by declark1** [grpc/grpc#27399]
### What version of gRPC and what language are you using? 
python grpcio 1.39.0

### What operating system (Linux, Windows,...) and version? 
macOS Big Sur 11.4

### What runtime / compiler are you using (e.g. python version or version of gcc) 
python 3.8.3

### What did you do?
Ran python multiprocessing example using 8 processes on macOS. Client requests only run on a single process, despite opening multiple connections. 7 processes remain idle. Tested both fork and spawn.

### What did you expect to see?
Requests distributed across processes.

### What did you see instead?
Requests processed by a single process.

### Anything else we should know about your project / environment?

**Comment by gnossen** [comment]
@dectl I'm assuming you're talking about [this example](https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing). Can you please provide any more details you have on this issue? Do you have logs from your run?

This example is dependent on the SO_REUSEPORT socket option, which admittedly, I have never tested on Mac OS. [Apple documentation](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setsockopt.2.html) seems to indicate that this _should_ work though.
