### ISSUE TITLE
Write Interop metadata test

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2740]
For that, a server that echoes the request metadata in the response metadata is needed. The current tests send a bogus OAuth2 access token to trigger a challenge response header, but a local server has no way to verify access tokens.

**Comment by jcanizales** [comment]
[This](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#custom_metadata) probably means the interop server already has / soon will have such a test.

**Comment by murgatroid99** [comment]
This test case is not in the list of the ones that need to be implemented before beta. So, I am removing the beta milestone from this issue.

**Comment by makdharma** [comment]
This test https://github.com/grpc/grpc/blob/master/src/objective-c/tests/GRPCClientTests.m#L262 does check that server echos back a metadata field. Closing this bug.
