### ISSUE TITLE
Failed to compile GRPC under SLES11: pthread_setname_np is missing

### ISSUE THREAD

**Issue by AntonRechkov** [grpc/grpc#27437]
GRPC 1.39.1 failed to compile under SLES11 because pthread_setname_np was introduced in glibc 2.12.

Glibc version used in SLES11 is libc 2.11.3
    bash-3.2$ getconf GNU_LIBC_VERSION
    glibc 2.11.3

### What version of gRPC and what language are you using?
1.39.1 / C++

### What operating system (Linux, Windows,...) and version?
Linux, SLES11

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Compiling GRPC with old GLIBC give an error

### What did you expect to see?
GRPC compiled on old GLIBC.

### What did you see instead?
/users/xxx/.conan/data/grpc/1.39.1/_/_/build/23a963e55e4a6da15f34448b8aceb08789fb8b92/source_subfolder/src/core/lib/gprpp/thd_posix.cc:125:25: error: ‘pthread_setname_np’ was not declared in this scope; did you mean ‘pthread_getattr_np’?
  125 |                         pthread_setname_np(pthread_self(), buf);
      |                         ^~~~~~~~~~~~~~~~~~
      |                         pthread_getattr_np

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Compile GRPC with Conan on SLES11.

**Comment by yashykt** [comment]
Given that SLES11 has reached EOL, I don't think it makes sense for gRPC to go out of the way to add support for it. 

That being said, please feel free to send a PR if you have a workaround in mind.

**Comment by yashykt** [comment]
looks like @nicolasnoble has a quick fix for this

**Comment by nicolasnoble** [comment]
Note that whole #27540 will make this one go away, this is only best effort from us to maintain code on outdated environments. This one was a simple oversight, but it's difficult to guarantee everything else will work.

**Comment by AntonRechkov** [comment]
Thanks for addressing this. We don't have issue with GRPC on 1.26.0, and while trying to update to 1.39.0 we run into pthread compiling problem.
