### ISSUE TITLE
Merge channels in the gRPC Python xDS interop client

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#27430]
Related https://github.com/grpc/grpc/pull/27416.

In an offline discussion with @menghanl, we found that the gRPC Python xDS interop client may create multiple channels to perform the RPC distribution test (one for each type of RPC). This is different than cpp/java/golang, and blocks the Python client to run the affinity tests (the affinity test asserts the channelz states).

https://github.com/grpc/grpc/blob/933676c56c24b9b4f494e2b68d2488d05987bdd8/src/python/grpcio_tests/tests_py3_only/interop/xds_interop_client.py#L395

This issue tracks the progress of merging the channels in the gRPC Python xDS interop client.

**Comment by lidizheng** [comment]
Maybe @menghanl will have more context about the priority.

**Comment by menghanl** [comment]
I think this is not a super high priority, maybe low p2.
This only affects the python affinity test. And since ringhash logic is the same as in C++, it is already covered by some tests.

**Comment by gnossen** [comment]
Sounds good. I'll plan this as an OKR for next quarter.

**Comment by XuanWang-Amos** [comment]
Closing since looks like it was fixed before 1.53.x from testing in this PR: https://github.com/grpc/psm-interop/pull/66
