### ISSUE TITLE
Bazel does not build Android APK anymore after #27410

### ISSUE THREAD

**Issue by sifmelcara** [grpc/grpc#27470]
Hi Jan,

I noticed that after #27410 I cannot use bazel to build Android APK on my workstation anymore (but the build is fine in kokoro CI for some reason)

APK build instruction: https://github.com/grpc/grpc/tree/master/examples/android/binder/java/io/grpc/binder/cpp

The error message I got
```
ERROR: /home/path/.cache/bazel/_bazel_mingcl/e04078e62f75ecebac0634da148f8f54/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: missing input file 'external/remote_java_tools_linux/java_tools/ijar/ijar.exe', owner: '@remote_java_tools_linux//:java_tools/ijar/ijar.exe'
Target //examples/android/binder/java/io/grpc/binder/cpp/exampleclient:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/path/.cache/bazel/_bazel_mingcl/e04078e62f75ecebac0634da148f8f54/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:3:12 Extracting interface @bazel_tools//src/tools/android/java/com/google/devtools/build/android:all_android_tools failed: 1 input file(s) do not exist
```

Seems like the tools is trying to find `ijar.exe` however there is only `ijar` in that directory. Does the toolchain somehow think I'm a windows machine?

I wonder if you have any immediate idea about potential cause of this issue, if not, I can try to trace this down and report to upstream if required

Thank you!

**Comment by sifmelcara** [comment]
cc @napathome

**Comment by sifmelcara** [comment]
Oh.. actually the CI image is still using old version of Bazel. It also fails after I update it

**Comment by sifmelcara** [comment]
Tried updating rbe config and bazel toolchains to HEAD and updating bazelrc for potentially missing `--java_runtime_version` `--tool_java_runtime_version` and `--extra_toolchains` arguments but no success

**Comment by comius** [comment]
> Tried updating rbe config and bazel toolchains to HEAD and updating bazelrc for potentially missing --java_runtime_version --tool_java_runtime_version and --extra_toolchains arguments but no success

Bazel 4.2.1 works with older rbe config and toolchains (updating to HEAD would break it for sure). 
The flags you mention only work with Bazel 5.0.0 (HEAD, release will happen in couple of months). Using those flags on Bazel 4.2.1 is a noop or even broken.

**Comment by comius** [comment]
I was able to reproduce easily.

- rbe_windows gets added as an execution platform (for local builds)
- java_tools_prebuilt selects a windows binary on that execution plaform
- fails because the binary doesn't exist

Workaround:
Comment out rbe_windows from WORKSPACE file.
```patch
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -10,13 +10,13 @@ load("//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
 
 grpc_extra_deps()
 
-register_execution_platforms(
-    "//third_party/toolchains:rbe_windows",
-)
+#register_execution_platforms(
+#    "//third_party/toolchains:rbe_windows",
+#)
 
-register_toolchains(
-    "//third_party/toolchains/bazel_0.26.0_rbe_windows:cc-toolchain-x64_windows",
-)
+#register_toolchains(
+#    "//third_party/toolchains/bazel_0.26.0_rbe_windows:cc-toolchain-x64_windows",
+#)
 
 load("@bazel_toolchains//rules/exec_properties:exec_properties.bzl", "create_rbe_exec_properties_dict", "custom_exec_properties")
```


Dumps:
```
$ bazel config
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 4.2.1 will be used instead of system-wide bazel installation.
Available configurations:
4522ccda3e6d30644e577c3541e70141abce0d456b8467159e06ff5e6c99dfbc
4a5b0a187a5a2f4104f48df00f0ebaa8386e369e0b691d747b0e7d0308ca951b
9ddd7d489f40b68e2e442721b2d272ed27a7dbb9320dccac3a2a2b6903f5c3c0 (exec)
abba6d9eff71af3e21bff4dfa7964d89aa8cac12f0f4069ec2f77e07c36d9418 (exec)
f84974cd754bd3786ffacdeef3a05b1295d5ff92377c332b2c2aa22dbe42b3ef (host)


$bazel config abba6d9eff71af3e21bff4dfa7964d89aa8cac12f0f4069ec2f77e07c36d9418 |grep platf
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 4.2.1 will be used instead of system-wide bazel installation.
INFO: Displaying config with id abba6d9eff71af3e21bff4dfa7964d89aa8cac12f0f4069ec2f77e07c36d9418
  extra_execution_platforms: []
  host_platform: null
  incompatible_auto_configure_host_platform: true
  platform_mappings: null
  platforms: [//third_party/toolchains:rbe_windows_2019]
  target_platform_fallback: @bazel_tools//platforms:target_platform
  incompatible_use_platforms_repo_for_constraints: false
  platform_suffix: -exec-5A65A9B
  apple_platform_type: macos

$ bazel build --toolchain_resolution_debug //examples/android/binder/java/io/grpc/binder/cpp/exampleclient:app
...
INFO: ToolchainResolution: Target platform @local_config_platform//:host: Selected execution platform //third_party/toolchains:rbe_windows_2019,
...

```

**Comment by comius** [comment]
At the moment I don't have time to inspect RBE configuration for windows and how to make a proper fix.
cc @katre, who might be able to know how to fix this out of top of his head

**Comment by katre** [comment]
Unfortunately I don't. It's unclear to me who owns this anymore. Possibly @ifoox can redirect?

**Comment by bergsieker** [comment]
@coevre, is this something you have any insight into?

@sifmelcara Can you clarify what OS you are building on? It sounds like you are building on Windows locally, but the remote workers are Linux?

**Comment by bergsieker** [comment]
Note that, in general, older versions of bazel-toolchains should still work with newer versions of Bazel.

**Comment by sifmelcara** [comment]
> Can you clarify what OS you are building on?

I'm googler and I build it on my workstation. The issue is also reproducible with [this docker file](https://github.com/grpc/grpc/blob/master/tools/dockerfile/test/binder_transport_apk/Dockerfile) (after replacing `ENV BAZEL_VERSION 3.7.1` with `ENV BAZEL_VERSION 4.2.1`), and I think the docker image is based on Ubuntu 16.04

**Comment by sifmelcara** [comment]
@bergsieker any update?

You tried to cc @coevre but that does not seems to be a valid GitHub username

**Comment by coeuvre** [comment]
The linked PR fixes this by removing `register_*` calls mentioned in https://github.com/grpc/grpc/issues/27470#issuecomment-930852784 since they are registered via `--extra_toolchains` and `--extra_execution_platforms` in `windows.bazelrc`.
