### ISSUE TITLE
C#: Consider exposing optional fields as nullable

### ISSUE THREAD

**Issue by leonardder** [grpc/grpc#27501]
### Is your feature request related to a problem? Please describe.
The way optional fields are implemented in C# is slightly hacky. For Strings, the underlying private field can be null, but the public property raises an exception upon null assignments. For non nullable (value type) fields, the underlying magic is even more scary.

### Describe the solution you'd like
Consider implementing optional fields as nullable properties in C#. This has the following benefits:

1. It takes away the need for using Protobuf's Well Known Types to have fields that translated to nullable C# properties.
2. It allows you to use optional fields in expressions, such as when projecting EF Core models into protobuf messages. For strings for example, you currently need to create a partial class to add an additional property that exposes the internal private field without the null check.
3. It exposes info about whether a field has been set in a language natural way, in contrast to the several HasY properties and ClearY methods currently necessary. With the nullable wrapper types, null is considered a real value, whereas with optional fields, null can be considered a way to communicate that the value of an optional field is kept empty.

**Comment by jtattermusch** [comment]
This is an enhancement request for protobuf, not gRPC (and so it doesn't belong here). Consider filing an issue at https://github.com/protocolbuffers/protobuf/issues.
