### ISSUE TITLE
Grpc.Tools signals libprotobuf warnings as errors

### ISSUE THREAD

**Issue by codami** [grpc/grpc#27502]
### What version of gRPC and what language are you using?
C#
Google.Protobuf: 3.18.0
Grpc.AspNetCore: 2.39.0
Grpc.Tools: 2.40.0

### What operating system (Linux, Windows,...) and version?
Linux & Windows

### What did you do?
I was building a .NET Class Library (gRPC Server side code) out of a proto file, using "dotnet build" and the _Protobuf_CoreCompile task failed after a couple of errors like this one:
`[libprotobuf WARNING T : error : \src\github\grpc\workspace_protoc_windows_x64\third_party\protobuf\src\google\protobuf\compiler\csharp\csharp_enum.cc:74] Duplicate enum value Short (originally MY_VIEW_SHORT) in MyView; adding underscore to distinguish
`

### What did you expect to see?
I would expect to see warnings at most, since the libprotobuf output was just a warning.

### What did you see instead?
The build failed because of errors.

After starting the command manually I have noticed that the original output from the libprotobuf is this one:
`[libprotobuf WARNING T:\src\github\grpc\workspace_protoc_windows_x64\third_party\protobuf\src\google\protobuf\compiler\csharp\csharp_enum.cc:74] Duplicate enum value Short (originally MY_VIEW_SHORT) in MyView; adding underscore to distinguish`

A closer look at the Grpc.Tools implementation shows that the warning above is converted into error by this matching regex: https://github.com/grpc/grpc/blob/ab6beb3f686857d687bf72e80b1fbaf7d3c3e4a4/src/csharp/Grpc.Tools/ProtoCompile.cs#L214

**Comment by tonydnewell** [comment]
I've created a PR to fix this
