### ISSUE TITLE
health.proto Should be in a Proto Jar on Maven Central

### ISSUE THREAD

**Issue by jamesward** [grpc/grpc#27565]
All of the health check instructions I can find indicate that the [https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto](health.proto) should be copy & pasted into a project.  I'd rather pull it in as a dependency but I can't find it in any of the published proto jars on Maven Central.

**Comment by markdroth** [comment]
This sounds like a java issue.  I suggest you file this bug in the grpc/grpc-java repo.
