### ISSUE TITLE
Access to Google speech API regional endpoint failed in C++

### ISSUE THREAD

**Issue by lco38** [grpc/grpc#27577]
### What version of gRPC and what language are you using?

grpc 1.41.0 with C++

### What operating system (Linux, Windows,...) and version?

Linux Debian 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc version 8.3.0

### What did you do?

I use this sample code [transcribe.cc](https://github.com/GoogleCloudPlatform/cpp-samples/blob/main/speech/api/transcribe.cc) to request a speech recognition (speech to text) to Google european end point (replace "speech.googleapis.com" by "eu-speech.googleapis.com" in this code)

### What did you expect to see?

Recognized text from speech file like I see when I use global endpoint speech.googleapis.com

### What did you see instead?

Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.

[Full log](https://github.com/grpc/grpc/files/7279340/eu-speech.googleapis.com.log)

**Comment by yihuazhang** [comment]
lco@, the issue should be fixed in https://github.com/grpc/grpc/pull/27155. We had a similar use case internally that uses google speech API regional endpoints, and the solution worked for them. Could you please double check if you indeed use the version 1.41.0 or configure the regional endpoint correctly?

**Comment by lco38** [comment]
In [log](https://github.com/grpc/grpc/files/7279340/eu-speech.googleapis.com.log) you can see I use version 1.41.0. I put trace in jwt_credentials.cc where I checked your commit :
`gpr_log(GPR_DEBUG, "service_url = %s (%s)\n", cached_.service_url.c_str(), context.service_url);`
The result :
`D1004 16:39:29.140999776   24664 jwt_credentials.cc:101]     service_url = https://eu-speech.googleapis.com/ (https://eu-speech.googleapis.com/google.cloud.speech.v1.Speech)`

I checked configuration following this [page](https://cloud.google.com/speech-to-text/docs/endpoints#speech-sync-recognize-protocol) and the result is OK when I use export "CLOUD_SPEECH_ENDPOINT=https://eu-speech.googleapis.com".

**Comment by yihuazhang** [comment]
I believe the internal fix has been released. @lco38, could you please try it out?

**Comment by lco38** [comment]
Yes. I confirm that fix is OK for me.
