### ISSUE TITLE
moving to new grpc version crash at grpc::internal::BlockingUnaryCallImpl<>::BlockingUnaryCallImpl() 

### ISSUE THREAD

**Issue by ynahum** [grpc/grpc#27596]
Hi,

**What version of gRPC and what language are you using?**

gRPC version v1.38.0-pre1 
Language: C++

**What operating system (Linux, Windows,...) and version?**

Ubuntu 18.04.5 LTSh

**What runtime / compiler are you using (e.g. python version or version of gcc)**

g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
BTW, also fails when building with ICC (intel compiler)

**What did you do?**

I was trying to move FWD with grpc version. built version v1.38.0-pre1 (also tried v1.39.0). used to have v1.17.0 and it worked fine.

My code:
```
  Result reply;
  ClientContext context;
  LOG(INFO) << "call PushWork rpc";
  Status status = _control_stub->PushWork(&context, desc, &reply);
  LOG(INFO) << "returned PushWork rpc";
  if (status.ok()) {
    return true;
  } else {
    LOG(ERROR) << status.error_code() << ": " << status.error_message();
    return false;
  }

```

**What did you expect to see?**

RPC Call Success

**What did you see instead?**

It seems that I have the following crash when issuing the first rpc call on the stub:

ubuntu:~/vascale$ ./distributor.sh
I1005 09:45:33.227728 15271 main.cpp:39] create and start server...
I1005 09:45:33.227814 15271 distributor_data_service_impl.cpp:47] Test! create data packet for testing
I1005 09:45:33.233847 15271 distributor_data_service_impl.cpp:49] Test! setting data
I1005 09:45:33.240685 15271 distributor_run.cpp:49] Registering data service
I1005 09:45:33.240705 15271 distributor_run.cpp:53] distributor data service ip:port : 0.0.0.0:8081
D1005 09:45:33.241049961   15271 ev_posix.cc:169]            Using polling engine: epollex
D1005 09:45:33.241113307   15271 dns_resolver.cc:338]        Using native dns resolver
I1005 09:45:33.241175075   15271 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1005 09:45:33.241780 15271 distributor_run.cpp:57] grpc server listening
I1005 09:45:33.241885 15271 distributor.cpp:70] distributor sending push work
I1005 09:45:33.241894 15271 distributor.cpp:76] desc:
I1005 09:45:33.241904 15271 distributor.cpp:77] desc.set_test_data_transfer_size: 2097152
I1005 09:45:33.241911 15271 distributor.cpp:78] desc.set_camera_index: 1
I1005 09:45:33.241919 15271 master_rpc.cpp:68] call PushWork rpc
E1005 09:45:33.241930430   15271 sync_posix.cc:58]           assertion failed: pthread_mutex_destroy(mu) == 0
*** Aborted at 1633427133 (unix time) try "date -d @1633427133" if you are using GNU date ***
PC: @     0x7fb1bac81fb7 gsignal
*** SIGABRT (@0x3e800003ba7) received by PID 15271 (TID 0x7fb1bc3a3880) from PID 15271; stack trace: ***
    @     0x7fb1bac82040 (unknown)
    @     0x7fb1bac81fb7 gsignal
    @     0x7fb1bac83921 abort
    @     0x7fb1ba8b7463 gpr_mu_destroy
    @     0x7fb1bbd25eb8 grpc::internal::BlockingUnaryCallImpl<>::BlockingUnaryCallImpl()
    @     0x7fb1bbd194bb vascale::proto::StreamModeControlService::Stub::PushWork()
    @     0x560d517516ff (unknown)
    @     0x560d51750fa1 (unknown)
    @     0x560d5174fa4b (unknown)
    @     0x560d5174f659 (unknown)
    @     0x7fb1bac64bf7 __libc_start_main
    @     0x560d5174f74a (unknown)
./distributor.sh: line 32: 15271 Aborted                 (core dumped) GRPC_VERBOSITY=debug GLOG_logtostderr=1 ./distributor_run

any idea? I saw the following issue [20781](https://github.com/grpc/grpc/issues/20781) but couldn't understand what's wrong in my existing code.

Was there an API change? is there a build flag /lib linkage that I'm missing?

Thanks in advance!
Yair

**Comment by veblush** [comment]
@ynahum Could you give us a small reproducible code so that we can take a look at? Also a crash call-stack looks a bit off to me because it contains `sync_posix.cc` but gRPC already started using `sync_abseil.cc` on Linux so there might be some misconfiguration on your build setup.

**Comment by ynahum** [comment]
Hi @veblush,

Thanks for you immediate response. will try to minimize the build as possible and reproduce the problem.
currently using cmake version 3.18.4 BTW.

Thanks,
Yair

**Comment by ynahum** [comment]
Hi,

found that the grpc version wasn't the expected (1.17). 
Managed to clean the files in /usr/local/ <lib/bin/include/share> location by reversing the make install output (rm each file and reinstall).

After that, changed the way the generated protobuf files are generated to be as in helloworld cmake, and also used the ../cmake/common there to find packages.

BTW, before that it looked for "SaneProtobuf".

Now my rpc call doesn't crash but it gets stuck. is it a blocking call? shouldn't it return right away if there is no server?

ubuntu@ip-172-31-60-136:~/dist$ ./distributor.sh
I1006 09:58:07.426522 28443 main.cpp:39] create and start server...
I1006 09:58:07.426612 28443 distributor_data_service_impl.cpp:47] Test! create data packet for testing
I1006 09:58:07.432690 28443 distributor_data_service_impl.cpp:49] Test! setting data
I1006 09:58:07.436512 28443 distributor_run.cpp:49] Registering data service
I1006 09:58:07.436528 28443 distributor_run.cpp:53] distributor data service ip:port : 0.0.0.0:8081
I1006 09:58:07.437090 28443 distributor_run.cpp:57] grpc server listening
I1006 09:58:07.437161 28443 distributor.cpp:70] distributor sending push work
I1006 09:58:07.437170 28443 distributor.cpp:76] desc:
I1006 09:58:07.437176 28443 distributor.cpp:77] desc.set_test_data_transfer_size: 2097152
I1006 09:58:07.437181 28443 distributor.cpp:78] desc.set_camera_index: 1
I1006 09:58:07.437186 28443 master_rpc.cpp:68] call PushWork rpc


Thanks,
Yair.

**Comment by ynahum** [comment]
Hi,
it seems that with intel compiler the rpc calls are executed correctly. will continue debug with GNU toolchain version.
Thanks
