### ISSUE TITLE
"make test_python" should be a thing that exists and runs Python tests.

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#276]
It's acceptable only for the nonce that I've hacked up a few shell scripts that plug into run_tests.py; running Python tests should really be stated properly and doable from both make and run_tests (and the run_tests configuration should be parallelized).

**Comment by nathanielmanistaatgoogle** [comment]
Nicolas, is this task worth doing or should it be closed with the reasoning being that run_tests.py is the only supported way of running Python tests?

**Comment by nicolasnoble** [comment]
I'm actually fine saying the "test_python" target is a .PHONY one that just piggy-backs on run_tests.py - would that satisfy this ?

**Comment by nathanielmanistaatgoogle** [comment]
Yes, I think that would be fine.

**Comment by nathanielmanistaatgoogle** [comment]
This is fixed in #1070.
