### ISSUE TITLE
Ruby tests failing with "Could not download rvm-installer, please report to https://github.com/rvm/rvm/issues"

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#27607]
I'm seeing this consistently in all Ruby tests.  Here are a couple of examples:

https://source.cloud.google.com/results/invocations/d4fe3fe2-1117-4e77-897a-317f8f92beb8/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log

https://source.cloud.google.com/results/invocations/f4372f7a-8a42-42b3-91c4-4a557096a755/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_ruby/log

**Comment by drfloob** [comment]
Fixed by https://github.com/grpc/grpc/pull/27538 as of last night. Both of those errors are from Oct 1
