### ISSUE TITLE
100% reproducible TSI_DATA_CORRUPTED Error

### ISSUE THREAD

**Issue by ayeganov** [grpc/grpc#27601]
### What version of gRPC and what language are you using?
gRPC Version 1.32.0 using C++ std 17

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04. LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-10.3.0-1ubuntu1~20.04

### What did you do?
I am using the asynchrouns API with completion queues. I have a bidirectional server which is expecting to receive audio data. When a client opens its **FIRST** connection it fails due to TSI_DATA_CORRUPTED error pasted below.  The surprising element is that the error occurs once and then does not reappear again.

### What did you expect to see?
I expected the connection to successfully be made and go through its proper life cycle.

### What did you see instead?
I see the error logs from gRPC pointing to SSL corruption:

```
Oct 5, 2021 @ 10:50:56.864959845 | E1005 14:50:56.864782266      10 secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
-- | --

  | Oct 5, 2021 @ 10:50:56.864956025 | E1005 14:50:56.864779860      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864952324 | E1005 14:50:56.864777068      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864948687 | E1005 14:50:56.864773663      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864944835 | E1005 14:50:56.864769416      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864940727 | E1005 14:50:56.864765709      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864937029 | E1005 14:50:56.864761298      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864933220 | E1005 14:50:56.864758506      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864928045 | E1005 14:50:56.864754622      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864855211 | E1005 14:50:56.864750122      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864843832 | E1005 14:50:56.864746242      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864840241 | E1005 14:50:56.864742310      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864836072 | E1005 14:50:56.864738529      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864832178 | E1005 14:50:56.864735631      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864828526 | E1005 14:50:56.864732440      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864823375 | E1005 14:50:56.864728229      10 ssl_transport_security.cc:483] error:1418708B:SSL routines:ssl_do_config:unknown command

  | Oct 5, 2021 @ 10:50:56.864802527 | E1005 14:50:56.864705224      10 ssl_transport_security.cc:507] Corruption detected.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I am able to reproduce the problem, and tried enabling the extra logging as suggested in TROUBLESHOOTING. Unfortunately the extra logs are not really helpful because I don't know what to look for. I would appreciate some advice on what to do to get to the bottom of this.

**Comment by erm-g** [comment]
Hi @ayeganov, do you have time to provide more details mentioned in the [comment](https://github.com/grpc/grpc/issues/27601#issuecomment-938012757) ?

**Comment by ayeganov** [comment]
Hi @erm-g, sorry I have moved on from this project a while ago, so won't be able to provide a lot more detail. That said I believe I was able to resolve the problem by updating gRPC.
