### ISSUE TITLE
Canonicalize header names when setting them, so they're case-insensitive

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2761]
Probably do the same as Apple does in [`NSMutableURLRequest.allHTTPHeaderFields`](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSMutableURLRequest_Class/index.html#//apple_ref/occ/instp/NSMutableURLRequest/allHTTPHeaderFields) and [`NSHTTPURLResponse.allHTTPHeaderFields`](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSHTTPURLResponse_Class/index.html#//apple_ref/occ/instp/NSHTTPURLResponse/allHeaderFields).

Make getting an already-set header be case-insensitive too.

**Comment by ctiller** [comment]
Core does this on send, and will soon start rejecting invalidly capitalized
headers.

**Comment by jcanizales** [comment]
Beta it is, then!

**Comment by ctiller** [comment]
What I'm saying is that there's little besides documentation you'll need to
do

**Comment by jcanizales** [comment]
Wait, I'm confused:

> will soon start rejecting invalidly capitalized headers

Does that mean it won't lowercase headers automatically anymore? If so, I need to lowercase headers myself in the wrapper before beta.

Either way, there's work to do beyond documentation: If the dictionary of request headers can hold `@{@"mykey": @"a", @"MyKey": @"b"}`, it's confusing for the user even if the RPC doesn't fail.
