### ISSUE TITLE
Basic Tests PHP MacOS Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#27641]
```
2021-10-01 17:10:12,217 START: run_tests_php7_macos_dbg_native


ERROR: Aborting VM command due to timeout of 3600 seconds

nc: connection failed, SOCKSv5 error: Connection refused
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

https://source.cloud.google.com/results/invocations/4790e7e3-7bba-4fb5-89ac-072357c2370a/log

The last few lines may actually be coming from Kokoro, not from our test. This might be related to the recent issues we've seen with Kokoro losing connection to the test VM and so might not be related to PHP at all.

**Comment by stanley-cheung** [comment]
Job back to green.
