### ISSUE TITLE
Ruby Gem LetsEncrypt Root Certificate Error

### ISSUE THREAD

**Issue by qgtim** [grpc/grpc#27653]
### What version of gRPC and what language are you using?
ruby gem 1.41.0

### What operating system (Linux, Windows,...) and version?
linux
x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby with grpc gem

### What did you do?
Using GRPC v1.41.0 to connect to a Let'sEncyrpt cetified hostname fails

### What did you expect to see?
GRPC to function as normal

### What did you see instead?
Failed to connect to endpoint, SSL error

### Anything else we should know about your project / environment?
This problem is resolved already, we just need a new Gem cut.  https://github.com/grpc/grpc/pull/27539 already resolve this issue.

**Comment by qgtim** [comment]
This issue is fixed already in the main branch, but a new gem version (1.41.1) needs to be cut.  Python pip was cut 5 days ago for this: https://github.com/grpc/grpc/issues/27727

**Comment by bpeicher** [comment]
Hi all - Any idea when the new gem could be published?

**Comment by qgtim** [comment]
It seems the gem does not get as much attention as other languages of this library :(

**Comment by apolcyn** [comment]
The 1.41.1 gem was just pushed

**Comment by qgtim** [comment]
Looks like its working as expected!  Thank you!
