### ISSUE TITLE
Problems building grpc for Linux and Android (please reopen)

### ISSUE THREAD

**Issue by Shielsy** [grpc/grpc#27668]
I've been using gRPC for many years and it's always been tricky building it for Linux and Android . It's never built for me straight 'out of the box'.  I've cloned the latest master just to test a small Linux application I have written. My cmake command specifies just two flags, gRPC_INSTALL=ON and a CMAKE_INSTALL_PREFIX with the install location. This fails with:

**gRPC_INSTALL will be forced to FALSE because gRPC_ABSL_PROVIDER is "module"**

I don't really want to dig through the CMakeLists file to find out why this is happening, It should just build. It's very frustrating. I may try and figure out the problem later so I won't even attempt to build Android just yet.

UPDATE: It looks like I have to build each submodule myself and install them to a directory. Then I have to specify on the command line "package' for each _PROVIDER_ and point CMAKE_INSTALL_PREFIX to the deps directory..  This is a bit of a pain is the backside - some of the submodules don't even support cmake install so how do I install them with cmake?  😞

**Comment by veblush** [comment]
@Shielsy Could you double-check whether you get the submodules as well? It should support installation with your option. Please read the [doc](https://grpc.io/docs/languages/cpp/quickstart/) on how to install it using cmake.

**Comment by veblush** [comment]
@Shielsy Oops sorry I accidentally clicked the wrong button. Oh You use the old version of cmake. If you can update it to 3.13 or later, you don't need to do install submodules independently. Otherwise, you have to do it manually.
