### ISSUE TITLE
Mac c++ grpc tls connect falied

### ISSUE THREAD

**Issue by Kernal-GH** [grpc/grpc#27709]
The server uses grpc 1.40.x version and uses tls self-signed certificate
Windows client uses grpc1.40.x and C++ development to open tls to connect to the server normally, but the Mac system uses the same version and turns on tls verification and the connection fails. The error shows: Cannot connect to all addresses, error_message_ = "failed to connect to all addresses"
Print the description of context.debug_error_string_:
(std::__1::string) debug_error_string_ = "{\"created\":\"@1634125658.168623000\",\"description\":\"Failed to select sub channel\",\"file\":\"/ User /project/grpc/src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3187,\"referenced_errors\":[{\"created\":\"@1634125658.168622000 \",\"description\":\"Failed to connect to all addresses\",\"file\":\"project/grpc/src/core/lib/transport/error_utils.cc\" ,\ "file_line\":146,\"grpc_status\":14}]}"
The server shows that the connection error is: E1013 16:43:25.824000000 22408 ssl_transport_security.cc:1447] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSLroutines:OPENSSL_internal:WRONG_VERSION_NUM.

If the server closes tls, the Mac client can connect normally. Does grpc on Mac system support tls?

**Comment by Jack-256** [comment]
@Kernal-GH Hey, guy, I have the same problem on iOS, have you solved it?
