### ISSUE TITLE
I need grpc dll file for php,  they say not available although it was there but recently I don't know what happened and it is disappeared from PECL site

### ISSUE THREAD

**Issue by GitMOJ** [grpc/grpc#27706]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by GitMOJ** [comment]
Please share the solution if you make it

**Comment by sandeepdigicraft** [comment]
Hey 
PECL site is fixed, now you can download DLL files. 
![image](https://user-images.githubusercontent.com/92427540/137256169-b9832d85-6fb0-4fe3-acd8-ca518289c57f.png)

**Comment by GitMOJ** [comment]
Thank you brother...you bought me ❤️
