### ISSUE TITLE
Compilation warnings while using protoc which is part of grpc third-party

### ISSUE THREAD

**Issue by mashoodk** [grpc/grpc#27737]
### What version of gRPC and what language are you using?
v1.41.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### What did you do?

We have a proto file which has int32 variables.

Say:

message Info_Response {
...
    optional int32 errorcode = 3;
    optional string errormsg = 4;
...
}

when we use the protoc shipped with grpc it uses ReadVarint64 in place of ReadVarint32, causing compilation warnings. We have strict policy against compilation warning, causing build failure in our product. 

xxxx.pb.cc:4631:71: error: conversion from ‘google::protobuf::uint64’ {aka ‘long unsigned int’} to ‘google::protobuf::int32’ {aka ‘int’} may change value [-Werror=conversion]
 4631 |           errorcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

### What did you expect to see?
No warnings from generated code.
This seems to be fixed here : 
https://github.com/protocolbuffers/protobuf/pull/8769

But not yet part of any release. We would like if we include this fix in next release of grpc. 

### What did you see instead?
Warnings causing build failure

**Comment by veblush** [comment]
Not having warnings are not our goal but I assume that this has already been fixed as gRPC upgraded protobuf with this fix.
