### ISSUE TITLE
core end2end "nosec" tests depend on both grpc and grpc_unsecure, which can lead to hangs in grpc_init()

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#27733]
All targets should depend either on "grpc" or "grpc_unsecure", but not both. Not complying with that can lead to hard-to-debug hangs in grpc_init (e.g. see https://github.com/grpc/grpc/issues/20690 or https://github.com/grpc/grpc/issues/21213), I just encountered that in one of my unrelated PRs (a loop was created in the tracer linked list because  the "glb" tracer from grpclb.cc gets registered twice, so basically the situation from #20690)

But our core end2end "nosec" test do exactly that.

The "grpc" dependency in brought through test-only dependencies, such a "cq_verifier", "http_proxy" etc.

E.g:
```
$  bazel query "allpaths(//test/core/end2end:h2_census_nosec_test,//:grpc)"

//test/core/end2end:h2_census_nosec_test
//test/core/end2end:end2end_nosec_tests
//test/core/util:test_lb_policies
//test/core/end2end:proxy
//test/core/end2end:local_util
//test/core/end2end:http_proxy
//test/core/end2end:cq_verifier
//test/core/util:grpc_test_util
//:grpc
```

At the same time the nosec (="no security") fixtures also explicitly depend on  grpc_unsecure and grpc_test_util_unsecure (since they are nosec fixtures and it kinda makes for them to do that).

```
$ bazel query "allpaths(//test/core/end2end:h2_census_nosec_test,//:grpc_unsecure)"

//test/core/end2end:h2_census_nosec_test
//test/core/util:grpc_test_util_unsecure
//:grpc_unsecure
```

**Comment by drfloob** [comment]
Fixed by #28946
