### ISSUE TITLE
python -m grpc_tools.protoc -I  xxxxx. relatively path raise .proto: warning: directory does not exist.  Missing input file.

### ISSUE THREAD

**Issue by zhangwenkal** [grpc/grpc#27734]
### What version of gRPC and what language are you using?
pthon

### What operating system (Linux, Windows,...) and version?

macOX

### What runtime / compiler are you using (e.g. python version or version of gcc)
python -m grpc_tools.protoc -I

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by drfloob** [comment]
There isn't enough information here for us to be of much help. If you think there's a bug in gRPC, please provide more details around the specific errors you are seeing, the versions and installation methods used on your system, and if possible, a way for others to reproduce the problem you are seeing. If this is a general question, or you think there's a problem with your own code or your local environment, please consider using StackOverflow instead. This forum is for bugs and feature requests.
