### ISSUE TITLE
Compilation warning "not all control paths return a value" in TypeToString switch

### ISSUE THREAD

**Issue by janm2** [grpc/grpc#27792]
### What version of gRPC and what language are you using?
1.41.X 
C++

### What operating system (Linux, Windows,...) and version?
Windows 10 x64 (Windows SDK version 10.0.20348.0 to target Windows 10.0.19042.)

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 19.29.30136.0
CMake 3.20.5

### What did you do?
(using x64/VS2015 OpenSSL(1.1.1k) and zlib(v1.2.8))
cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_CXX_STANDARD_LIBRARIES="Crypt32.Lib User32.lib Advapi32.lib" -Dprotobuf_BUILD_TESTS=OFF" -DgRPC_ZLIB_PROVIDER=package -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES=Release -DgRPC_SSL_PROVIDER=package

cmake --build . --target ALL_BUILD --config Release
gRPC gets build correctly without any issues.

After linking to my project and compiling (with VC v160).
I get error "include\grpcpp\impl\codegen\rpc_service_method.h(149): error C4715: 'grpc::internal::RpcServiceMethod::TypeToString': not all control paths return a value"

### What did you expect to see?
No error/warning while compiling my project

### What did you see instead?
"not all control paths return a value" due to the macro GPR_UNREACHABLE_CODE obfuscating return path for compiler in the default: switch case. 

### Anything else we should know about your project / environment?
Due to my compilation environment this may be warning for some but for me it's error

**Comment by drfloob** [comment]
Sorry I missed this Issue. That's interesting, I'm not sure what's special about this particular use of `GPR_UNREACHABLE_CODE` that would cause the compiler's confusion. This chunk of code hasn't changed in ~3 years. Do you get any other errors around `GPR_UNREACHABLE_CODE`, or just this one spot? And by any chance have you changed `rpc_service_method.h`?

**Comment by drfloob** [comment]
Closing this since no updates have been given in about a year.
