### ISSUE TITLE
C# .NET Framework Cors / AllowOrigins

### ISSUE THREAD

**Issue by MichaelPeter** [grpc/grpc#27815]
Dear Developer Team,

we are hosting an GRPC Service on our client maschines and would like to access it over localhost from our blazor webassembly site in the browser. 

Since our Service still uses .NET Framework Libraries we cannot switch to .NET Core/grpc-dotnet and need to stay on .NET Framework/this native library. 

Now we would like to access the Service from Our Blazor Webassembly Site directly over localhost, but this is not possible since we cannot specify the allow-origins header for the OPTIONS preflight and our browser request gets denied for Cross Origin reasons.

Can you add the possibilty to specify http headers/Metadata for the OPTIONS call so we don't need to add an grpc proxy?
Or an AllowOrigins(string origins) option for the Server class.

Thank you very much
Michael

**Comment by jtattermusch** [comment]
I don't think adding support for custom metadata (headers) in OPTIONS preflight is feasible for the gRPC C-core implementation (and thus it's not feasible for the Grpc.Core C# implementation either).

Given this limitation, I think you'll have to come up with a different solution (one possibility is to create a ASP.NET Core / grpc-dotnet proxy that handles the Cors/AllowOrigin the way you want it and forwards requests to you actual gRPC C# server.

Btw, the "new issue" form clearly asks users not to post questions as github issues. Next time please follow the instructions and use the channels mentioned below to ask questions.

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
>

**Comment by MichaelPeter** [comment]
Thank you for the response, I will use these channels in future. Just posted it here since it was C# relatef
