### ISSUE TITLE
Extra context values for ServicerContext (python)

### ISSUE THREAD

**Issue by lijok** [grpc/grpc#27814]
If interceptors wish to pass values to the request handlers, through the servicer context, we currently must define a new class, wrapping `grpc.aio.ServicerContext` and extending its properties like so:
```py
class ExtensibleServicerContext(grpc.aio.ServicerContext):
    def __init__(self, context: grpc.aio.ServicerContext):
        self._context = context

    async def read(self) -> grpc.aio._typing.RequestType:
        return await self._context.read()

    async def write(self, message: grpc.aio._typing.ResponseType) -> None:
        return await self._context.write(message=message)

    async def send_initial_metadata(
        self, initial_metadata: grpc.aio._typing.Metadata
    ) -> None:
        return await self._context.send_initial_metadata(
            initial_metadata=initial_metadata
        )

    async def abort(
        self,
        code: grpc.StatusCode,
        details: str = "",
        trailing_metadata: grpc.aio._typing.Metadata = tuple(),
    ) -> None:
        return await self._context.abort(
            code=code, details=details, trailing_metadata=trailing_metadata
        )

    def set_trailing_metadata(
        self, trailing_metadata: grpc.aio._typing.Metadata
    ) -> None:
        return self._context.set_trailing_metadata(trailing_metadata=trailing_metadata)

    def invocation_metadata(self) -> t.Optional[grpc.aio._typing.Metadata]:
        return self._context.invocation_metadata()

    def set_code(self, code: grpc.StatusCode) -> None:
        return self._context.set_code(code=code)

    def set_details(self, details: str) -> None:
        return self._context.set_details(details=details)

    def set_compression(self, compression: grpc.Compression) -> None:
        return self._context.set_compression(compression=compression)

    def disable_next_message_compression(self) -> None:
        return self._context.disable_next_message_compression()

    def peer(self) -> str:
        return self._context.peer()

    def peer_identities(self) -> t.Optional[t.Iterable[bytes]]:
        return self._context.peer_identities()

    def peer_identity_key(self) -> t.Optional[str]:
        return self._context.peer_identity_key()

    def auth_context(self) -> t.Mapping[str, t.Iterable[bytes]]:
        return self._context.auth_context()

    def time_remaining(self) -> float:
        return self._context.time_remaining()

    def trailing_metadata(self):
        return self._context.trailing_metadata()

    def code(self):
        return self._context.code()

    def details(self):
        return self._context.details()


class JWTAuthenticatedServicerContext(ExtensibleServicerContext):
    def __init__(
        self,
        context: grpc.aio.ServicerContext,
        claims: dict[str, str]
    ):
        super().__init__(context=context)
        self.user = claims
```

This is a hassle because:
1. everything under the `ExtensibleServicerContext` class in the example is effectively boilerplate, to satisfy the abstractmethod requirements
2. type hinting in request handlers gets trashed, because the methods now need to be aware of interceptors and what type the context will come in as
3. in scenarios where multiple interceptors wish to inject extra information into the context, behaviour becomes difficult to reason about

It would be great if `ServicerContext` had an extra attribute, e.g. `info`, with getters and setters, that interceptors could mutate so that none of the above would be required

Thank you

**Comment by lidizheng** [comment]
Thanks for the rationales. We currently don't have resources to pursuit this aspect. If you have a clear vision about what the API should be, probably, you may write an gRFC at https://github.com/grpc/proposal.

**Comment by micolous** [comment]
FYI, this is possible with `contextvars`. There's an example here, with an interceptor that passes a value to a method: https://github.com/grpc/grpc/blob/master/examples/python/interceptors/async/async_greeter_server_with_interceptor.py

You could have an interceptor validate JWTs and pass the caller's identity (ie: user information) in a `ContextVar`.

Just make sure that your `Servicer` implementation has all `async def` method handlers (and not `def`), otherwise you'll get a `LookupError` or no value at all when calling `ContextVar.get()` due to https://github.com/grpc/grpc/issues/37881 😄
