### ISSUE TITLE
 gRPC server crashes with multiple clients

### ISSUE THREAD

**Issue by rochaudhari** [grpc/grpc#27825]
### What version of gRPC and what language are you using?
grpc-1.41.0 C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What did you do?
Running gRPC sync server.
Running test with multiple clients in parallel.
```
TEST_F(BidiTest, MultipleClientTest) {
  constexpr int kNumClients = 700;
  constexpr int kNumMsgs = 1000;

  std::vector<std::thread> threads;

  for (int id = 0; id < kNumClients; id++) {
    threads.emplace_back(([&] {
      auto client = CreateClient();

      test::TestRequest request;
      for (int i = 0; i < kNumMsgs; i++) {
        std::string temp;
        temp.resize(6400);
        request.set_data(temp.data(), temp.size());
        if (!client->Write(request)) {
          LOG(ERROR) << "writer returned false, exiting.. ";
          break;
        }
      }

      client.reset();
    }));
  }
```

### What did you expect to see?

server to run fine without throwing any error.

### What did you see instead?
`
E1026 15:41:43.262210239   17356 ev_epollex_linux.cc:1454]   pollset_set_add_pollset: {"created":"@1635243103.262149995","description":"Too many open files","errno":24,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/ev_epollex_linux.cc","file_line":563,"os_error":"Too many open files","syscall":"epoll_create1"}
`
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by drfloob** [comment]
Is this a crash or a test failure? If it's a crash, please post a log with the stack trace included. Also, what is your test environment's maximum open file descriptor limit? (`ulimit -n`)

**Comment by rochaudhari** [comment]
@drfloob yes, it was a test issue as you pointed out, number of file descriptors. I was creating clients with different channels and it was hitting a limit. I am closing this issue.
