### ISSUE TITLE
Memory leaks in c# server

### ISSUE THREAD

**Issue by diogojc** [grpc/grpc#2784]
A simple load test on a grpc client and server using the nuget package v0.6.1 seems to expose a memory leak. Memory footprint is always increasing and even after stopping the load test the memory footprint doesn't decrease.

**Comment by diogojc** [comment]
The always increasing memory footprint happens on the server side and only happens if a new channel is open every time a new call is made. I assumed channel is not thread safe.

**Comment by jtattermusch** [comment]
Hi, can you attach the code you are running?

**Comment by jtattermusch** [comment]
Btw, the channel definitely is thread safe. Ideally, your app should be using just one channel to talk to a given server and you should be making all your calls using that channel.
You can also have multiple clients (for different services) use the same channel (if the server servers all those services of course).

Every channel creates it's own TCP connection, so based on what you describe it looks like that server doesn't properly deallocate memory after the connection from a client is closed?

**Comment by diogojc** [comment]
Hi.

Thanks for clearing up the channel thread safety.

Yes, the server doesn't deallocate memory properly after a channel is created a service consumed and the channel closed in the client. If I use channel as a singleton no memory leak occurs.

**Comment by jtattermusch** [comment]
Ok, so after doing some profiling, it looks like that the gpr_slice that does allocated by in win_notify_on_read (tcp_windows.c:195) gets leaked when the connection to a client gets dropped.
Only one slice gets leaked per connection, which explains why the scenario that is using one channel for many call looks like no memory is leaked.
```
tcp->read_slice = gpr_slice_malloc(8192);
```
