### ISSUE TITLE
Avoid non-safe pyyaml's yaml.load() in build system

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#27879]
It was reported to the grpc-security mailing list that gRPC is using unsafe YAML functions. Making this public to ease tracking, as it does not seem to have an actual security impact to us. The function appears to only be involved in the build system such that an attack could just as easily modify a .py file. While not a security issue, we should try and clean this up to ease future audits.

`yaml.load` without a loader [is unsafe](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation). A search shows instances of load() without a loader specified https://github.com/grpc/grpc/search?q=yaml.load . It seems we noticed this before in https://github.com/grpc/grpc/pull/18829 but were worried about the changes suggested.

It's been a year and half since it was looked at previously, so it may now be fine to bump the version of pyyaml. But it was also pointed out that earlier versions of pyyaml actually do have the safe_load alternative: https://github.com/yaml/pyyaml/blob/3.12/lib3/yaml/__init__.py#L88 . It seems doubtful to me that we need the full loader, but I don't actually know how we're using YAML. The full loader is not safe itself (although it aspires to be safe-ish), so using it mainly just signals "yes, this is trusted input," especially if we aren't keeping the pyyaml version up-to-date. It may be good to replace the full loader usages with safe loader as well, from a "why are you even using that YAML feature" perspective.

CC @veblush @jtattermusch

**Comment by jtattermusch** [comment]
@gnossen  since this is python related, could you please take a look into this?

CC @lidizheng

**Comment by jtattermusch** [comment]
I think we can do this as a followup for @gnossen  python3 migration.

**Comment by lidizheng** [comment]
I upgraded the YAML invocations for the generate project code path at https://github.com/grpc/grpc/pull/24673

**Comment by jtattermusch** [comment]
> I upgraded the YAML invocations for the generate project code path at #24673

But the rest still needs to be updated, right?

**Comment by lidizheng** [comment]
Yes. Also, if we use newer Python version, the old YAML loading won't work. So, I guess part of this will be resolved by @gnossen 's Python3 migration.
