### ISSUE TITLE
greeter_server killed at startup and executable deleted!

### ISSUE THREAD

**Issue by lakamsani** [grpc/grpc#27876]
### What version of gRPC and what language are you using?
compiled latest from master as of this morning using bazel 4.2.0, C++

### What operating system (Linux, Windows,...) and version?
macOS  Big Sur, 11.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
```bash
➜  grpc git:(master) g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### What did you do?
Trying to run `greeter_server` using info here:
https://grpc.io/docs/languages/cpp/quickstart/#try-it

### What did you expect to see?
Expected `greeter_server` to run. 
### What did you see instead?
It is killed right away and the executable deleted!

Here's more info: 
```bash
➜  build git:(master) pwd
/Users/vamsee.lakamsani/git/ot/grpc/examples/cpp/helloworld/cmake/build
➜  build git:(master) make -j
[ 22%] Built target hw_grpc_proto
[ 33%] Built target greeter_async_server
[ 44%] Built target greeter_async_client2
[ 55%] Built target greeter_client
[ 66%] Built target greeter_callback_client
[ 77%] Built target greeter_async_client
[ 88%] Built target greeter_callback_server
[ 94%] Linking CXX executable greeter_server
ld: warning: direct access in function '_sk_X509_NAME_deep_copy' from file '/Users/vamsee.lakamsani/.local/lib/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file '/Users/vamsee.lakamsani/.local/lib/libgrpc.a(ssl_transport_security.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[100%] Built target greeter_server
➜  build git:(master) ls -rtl ./greeter_server
-rwxr-xr-x  1 vamsee.lakamsani  staff  30814912 Oct 29 11:29 ./greeter_server*
➜  build git:(master) ./greeter_server
[1]    93695 killed     ./greeter_server
➜  build git:(master) ls -rtl ./greeter_server
ls: ./greeter_server: No such file or directory
```

### Anything else we should know about your project / environment?
The other executables like `greeter_async_server`, `greeter_callback_server` are starting fine. My end goal is to test server reflection using  `grpc_cli ls localhost:50051` as documented [here](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md#list-services). Seems like server reflection is enabled only for the `greeter_server`

Is there a `bazel` way to build these quickstart [examples](https://github.com/grpc/grpc/tree/master/examples/cpp) like greeter and route guide given that `bazel` is recommended over `cmake` for building grpc c++? Thanks.

**Comment by lakamsani** [comment]
Please hold on to this. I suspect some malware scanning software on my company-issued laptop is falsely flagging this executable and deleting it!. Working with our IT security admins to resolve it. I will close after my suspicion is confirmed. thanks.

**Comment by AzadPolat** [comment]
Anyone you should be restart files with cmd than idk lel

**Comment by yashykt** [comment]
I'm going ahead and closing this.
