### ISSUE TITLE
create n servers and n clients and make sure client A go to specfic client X

### ISSUE THREAD

**Issue by doaaperf** [grpc/grpc#27895]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by doaaperf** [comment]
I am trying to create number of servers and I found that through passing diff port number using ./tools/run
-test/start....

my issue is how can I tell the test like "bm_fullstack_unary_ping_pong" to go to specific port not any ?

**Comment by yashykt** [comment]
The tests are made to be run as part of the part of the CI infrastructure, but you can probably modify the tests so as to take a port parameter and use that port.

**Comment by doaaperf** [comment]
how can I pass the the port number to the client? I notice that the port number is always dynamic, even if u start the server with specific port, it doesn't really take it.

**Comment by yashykt** [comment]
The tests use the function `grpc_pick_unused_port_or_die()` to find an unused port. You would want to replace this with the specific port that you want.
