### ISSUE TITLE
TlsChannelCredentialsOptions::set_server_authorization_check_config makes bad use of shared_ptr

### ISSUE THREAD

**Issue by oakad** [grpc/grpc#27907]
Consider the following:
https://github.com/grpc/grpc/blob/7c7fb9e525b947a35633b972957135fd313ec345/src/cpp/common/tls_credentials_options.cc#L170-L178

shared_ptr is passed into the function. The function grabs the managed pointer out of shared_ptr and stores its value. The shared_ptr is now happily allowed to deallocate the pointed to object and cause a crash (as there are 2 shared_ptrs involved it's a bit more complicated, but the general idea is that).

Indeed, the below code snippet will cause an immediate crash on connect:
```cpp
::grpc::experimental::TlsChannelCredentialsOptions authOptions;
authOptions.set_server_authorization_check_config(
    std::make_shared<
       ::grpc::experimental::TlsServerAuthorizationCheckConfig
    >(std::make_shared<CheckImpl>())
);
```

It may be just me, but this is not the right way to design APIs using shared_ptr. :-)

**Comment by ZhenLian** [comment]
Yeah, the `TlsServerAuthorizationCheckConfig` is problematic, and we have some internal users complaining it as well :(
We are under the process of rewriting the whole API. Fortunately, the whole process is almost done, and expected to be landed in 2 weeks(PR: https://github.com/grpc/grpc/pull/25631).
If it is not an urgent task, I suggest you wait until the above PR to be merged. After that, if the problem still exists, we can talk further to discuss better solutions.
Thanks again for raising these issues!

**Comment by ZhenLian** [comment]
Now `TlsServerAuthorizationCheckConfig` is fully gone. Would you mind giving it another try?

**Comment by oakad** [comment]
As in bumping the grpc version to 1.42?

**Comment by ZhenLian** [comment]
Ah yeah, this is not in 1.42, but should be in the next release version.
