### ISSUE TITLE
Jenkins fails to "make interop_server" for macos, opt

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2795]
From the logs of [this run](https://grpc-testing.appspot.com/job/gRPC_master_unstable/config=opt,language=objc,platform=macos/1175/console) and the two preceding it:

```
[LD]      Linking bins/opt/interop_server
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      _zlib_compress in libgrpc.a(message_compress.o)
  "_deflateEnd", referenced from:
      _zlib_compress in libgrpc.a(message_compress.o)
  "_deflateInit2_", referenced from:
      _zlib_compress in libgrpc.a(message_compress.o)
  "_inflate", referenced from:
      _zlib_decompress in libgrpc.a(message_compress.o)
  "_inflateEnd", referenced from:
      _zlib_decompress in libgrpc.a(message_compress.o)
  "_inflateInit2_", referenced from:
      _zlib_decompress in libgrpc.a(message_compress.o)
ld: symbol(s) not found for architecture x86_64
```

The [run preceding them](https://grpc-testing.appspot.com/job/gRPC_master_unstable/config=opt,language=objc,platform=macos/1172/console) did make the server successfully.

I tried `make CONFIG=opt interop_server` on the machine via ssh, in the same commit, to see what's going on. But it fails for a different reason I can't wrap my head around:

```
ccache: error: Failed to create file ~/.ccache/0/8/809fc15abbd45570a383df99635940-15995.manifest.tmp.Jenkinss-Mac-mini.local.8606.P1s1qW: Permission denied
make[2]: *** [mem.o] Error 1
make[1]: *** [build_crypto] Error 1
make: *** [libs/opt/openssl/libssl.a] Error 2
```

Looking at `~/.ccache/0`, the `8/` subdirectory is owned by root and doesn't have write permissions for other users. Why would that happen, I don't know.

**Comment by jcanizales** [comment]
Seems resolved now... I'll reopen if I see it again.

**Comment by zyg1982527** [comment]
I have the same wrong with you . I can't find method to solve it .
how did you solve it?

**Comment by muxi** [comment]
@zyg1982527 - did you try `git submodule update --init`? Seems like your makefile did not find the embedded zlib library. Another possibility is that you installed system global zlib so gRPC is building against that, but that is somehow broken.
