### ISSUE TITLE
C#: AsyncUnaryCall.ConfigureAwait(bool continueOnCapturedContext) should be added?

### ISSUE THREAD

**Issue by max-ieremenko** [grpc/grpc#27961]
### Is your feature request related to a problem? Please describe.
the async methods generated for csharp returns AsyncUnaryCall which is awaitable.

The use of async/await pattern with AsyncUnaryCall is not obvious and sometime leads to mistakes.
Example in context of WPF main thread application:

``` c#
private async Task<string> GetHelloResponseAsync()
{
    // here is not obvious that the call grabs SynchronizationContext
    var reply = await client.SayHelloAsync(new HelloRequest { Name = "the name" }); // it is natural to expect here .ConfigureAwait(false)
	
    // like in this line
    await Task.Delay(100).ConfigureAwait(false);
	
    // fix after surfing the internet, requires the developer to always keep in mind 
    //// var reply = await client.SayHelloAsync(new HelloRequest { Name = "the name" }).ResponseAsync.ConfigureAwait(false);

    return reply.Message; 
}

private async void Button_Click(object sender, RoutedEventArgs e)
{          
    var response = await GetHelloResponseAsync().ConfigureAwait(true);
    MessageBox.Show(response);
}
```

### Describe the solution you'd like

extend AsyncUnaryCall with ConfigureAwait(bool):

``` c#
public sealed class AsyncUnaryCall<TResponse> : IDisposable
{
    // new ConfigureAwait
    public ConfiguredTaskAwaitable<TResponse> ConfigureAwait(bool continueOnCapturedContext) => responseAsync.ConfigureAwait(continueOnCapturedContext);

    // existing GetAwaiter
    public TaskAwaiter<TResponse> GetAwaiter() => responseAsync.GetAwaiter();
}
```

``` c#
private async Task<string> GetHelloResponseAsync()
{
    var reply = await client.SayHelloAsync(new HelloRequest { Name = "the name" }).ConfigureAwait(false);
	
    await Task.Delay(100).ConfigureAwait(false);
	
    return reply.Message; 
}
private async void Button_Click(object sender, RoutedEventArgs e)
{          
    var response = await GetHelloResponseAsync().ConfigureAwait(true);
    MessageBox.Show(response);
}
```

**Comment by jtattermusch** [comment]
FTR this affects both https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/csharp/Grpc.Core.Api/AsyncUnaryCall.cs#L98

and 

https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/csharp/Grpc.Core.Api/AsyncClientStreamingCall.cs#L117

Note that as a workaround you can always use `unaryCall.ResponseAsync.ConfigureAwait(true)` and `clientStreamingCall.ReponseAsync.ConfigureAwait(true)`

**Comment by jtattermusch** [comment]
@JamesNK  WDYT?

**Comment by JamesNK** [comment]
I don't know. I'm not an expert in this area.

@stephentoub What is the recommended pattern to add `ConfigureAwait(bool)` to a non-Task type that has been made awaitable by adding `GetAwaiter`?

Proposal:
```cs
public sealed class AsyncUnaryCall<TResponse> : IDisposable
{
    // new ConfigureAwait
    public ConfiguredTaskAwaitable<TResponse> ConfigureAwait(bool continueOnCapturedContext) => responseAsync.ConfigureAwait(continueOnCapturedContext);

    // existing GetAwaiter
    public TaskAwaiter<TResponse> GetAwaiter() => responseAsync.GetAwaiter();
}
```

Link to `GetAwaiter` on `AsyncUnaryCall<T>`: https://github.com/grpc/grpc/blob/396fdf2991304deda5f840c800f6131d9362e868/src/csharp/Grpc.Core.Api/AsyncUnaryCall.cs#L95-L101

Example of it being awaited:
https://github.com/grpc/grpc/blob/396fdf2991304deda5f840c800f6131d9362e868/src/csharp/Grpc.IntegrationTesting/InteropClient.cs#L584-L587

**Comment by stephentoub** [comment]
> What is the recommended pattern to add ConfigureAwait(bool) to a non-Task type that has been made awaitable by adding GetAwaiter?

The pattern we've followed is that the awaitable thing also exposes a ConfigureAwait method in addition to the GetAwaiter method (with the ConfigureAwait itself returning something that's awaitable), so that you can write:
```C#
await thing;
await thing.ConfigureAwait(false);
```

**Comment by max-ieremenko** [comment]
Thank you!
