### ISSUE TITLE
Use port server for ObjC tests

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2805]
Per #2788. The env variable `GRPC_TEST_PORT_SERVER` has the port server address. An HTTP GET to `/get` on that server returns a free port number in the body.

**Comment by ctiller** [comment]
grpc_pick_unused_port_or_die() does the right thing when running with
run_tests.py.

**Comment by jcanizales** [comment]
Thanks for the tip. I can't start the server from the test code, though (the tests run in the iPhone simulator), so this is tricky.

**Comment by jcanizales** [comment]
@jayantkolhe This is a nice-to-have for our testing infrastructure. Not needed for Beta.
