### ISSUE TITLE
iPhone simulator unable to boot on Jenkins Mac machine

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2807]
[Tests are failing](https://grpc-testing.appspot.com/job/gRPC_master_unstable/config=opt,language=objc,platform=macos/1190/console) with:

`xcodebuild[10509:78312023]  iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.`

Apparently [`xcodebuild` won't start the simulator if run via ssh](http://stackoverflow.com/questions/25380365/timeout-when-running-xcodebuild-tests-under-xcode-6-via-ssh). People have solved it [using launch agents](https://github.com/facebook/xctool/issues/404#issuecomment-57181636). @nicolasnoble, do you know what those agents are?

[Here's what Travis did](https://github.com/travis-ci/travis-worker/pull/99) to solve the issue.

**Comment by jcanizales** [comment]
Step 4 of [this tutorial](http://pivotallabs.com/ios-ci-jenkins/) seems to be what we need.

**Comment by nicolasnoble** [comment]
That should be now in. Please verify and close if that's the case.

**Comment by jcanizales** [comment]
A run [~1h after your message](https://grpc-testing.appspot.com/job/gRPC_master_unstable/config=opt,language=objc,platform=macos/lastBuild/) didn't get it right :( Maybe wait till the next?

**Comment by nicolasnoble** [comment]
After some more digging, it seems you have to go with the full 9 yards of running Xcode once, building a dummy iOS app once, and running it once, before everything's set up to run it automatically from the command line. Done that now. Let's see what will happen for the next build.

**Comment by nicolasnoble** [comment]
https://grpc-testing.appspot.com/job/gRPC_master_unstable/1361/config=opt,language=objc,platform=macos/console

This seems to be actually running the simulator now.

**Comment by jcanizales** [comment]
The log of the failure is similar to the one in [these](http://stackoverflow.com/questions/29208662/xcode-server-ci-bot-test-session-exited-1) [two](http://stackoverflow.com/questions/31475102/xcode-unit-tests-test-session-exited-1-without-checking-in/) StackOverflow questions. There are two suggested solutions:

* [create a plist file in ~/Library/LaunchAgents, and have that user continuously logged in](http://stackoverflow.com/a/31925744/3642676): I verified that the machine has a plist file there, but it's unrelated to any of this. I'm not sure what should the contents of the file be.

* [execute `sudo /usr/sbin/DevToolsSecurity --enable`](http://stackoverflow.com/a/31848753/3642676): Although you might already have gone through that dialog?

**Comment by jcanizales** [comment]
From [these intructions](http://pivotallabs.com/ios-ci-jenkins/), there should be a `org.jenkins-ci` file in a `LaunchDaemons/` directory, which is what we'd have to move to `LaunchAgents/`.

**Comment by murgatroid99** [comment]
I don't think this is relevant anymore, since we switched to testing iOS on Travis.
