### ISSUE TITLE
grpc universal-darwin gem is not universal and does not work on Apple Silicon

### ISSUE THREAD

**Issue by univerio** [grpc/grpc#28085]
This is related to #24846, which has been closed but the underlying issue still persists.

### What version of gRPC and what language are you using?
1.41.1, Ruby

### What operating system (Linux, Windows,...) and version?
MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby 2.7.2

### What did you do?
Install the `grpc` gem on a native arm64 darwin Ruby (i.e. not a x86-64 darwin Ruby through Rosetta) on Apple Silicon:

```sh
gem install grpc
```

and `require` it:

```ruby
require 'grpc'
```

### What did you expect to see?
It should either:

1. Install the `1.41.1-universal-darwin` binary gem and `require`s without any errors, or
2. Install a `1.41.1-x86_64-darwin` binary gem

### What did you see instead?
It installs the `1.41.1-universal-darwin` binary gem, which is not actually universal and only contains x86_64-darwin binaries:

```
$ tar xOf grpc-1.41.1-universal-darwin.gem data.tar.gz | tar xOf - src/ruby/lib/grpc/2.7/grpc_c.bundle > bundle && file bu
ndle
bundle: Mach-O 64-bit bundle x86_64
```

Requiring `grpc` from this gem results in:

```
LoadError: dlopen(/Users/me/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.41.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle, 0x0009): tried: '/Users/me/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.41.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/grpc_c.bundle' (no such file), '/usr/lib/grpc_c.bundle' (no such file) - /Users/me/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/grpc-1.41.0-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle
```

**Comment by apolcyn** [comment]
can you please try out the `1.42.0.pre1` gem? (1.42.0 isn't out yet, this is a pre-release)

arm support is added in the 1.42.0 branch

**Comment by univerio** [comment]
Unfortunately, it doesn't work. The published `arm64-darwin` gem for 1.42.0.pre1 is indeed good and does work:

```
$ curl https://rubygems.org/downloads/grpc-1.42.0.pre1-arm64-darwin.gem | tar xOf - data.tar.gz | tar xOf - src/ruby/lib/grpc/2.7/grpc_c.bundle > bundle && file bundle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9328k  100 9328k    0     0  1697k      0  0:00:05  0:00:05 --:--:-- 2306k
bundle: Mach-O 64-bit bundle arm64
```

the published `universal-darwin` for 1.42.0.pre1 is still not universal and just a x86_64 binary:

```
$ curl https://rubygems.org/downloads/grpc-1.42.0.pre1-universal-darwin.gem | tar xOf - data.tar.gz | tar xOf - src/ruby/lib/grpc/2.7/grpc_c.bundle > bundle && file bundle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.9M  100  9.9M    0     0  32.4M      0 --:--:-- --:--:-- --:--:-- 33.3M
bundle: Mach-O 64-bit bundle x86_64
```

and the way bundler resolves platform-specific gems makes it prefer `universal-darwin` (because, well, it claims to be universal 😅).

**If you pull or stop publishing the `universal-darwin` gem**, then everything should work.

**Comment by steijgeler** [comment]
I got it to work by manually specifying the platform when installing the grpc gem: `gem install grpc:1.41.0 --platform arm64e`. It does break again when running `bundle update`, but at least it's manageable for now

**Comment by univerio** [comment]
@steijgeler IMO a better workaround is `bundle config set --local force_ruby_platform true`, which allows you to still use bundler.

Personally, I've had to resort to writing a monkeypatch in my Gemfile. Unfortunately, the hack is specific to Bundler 2.1.2, but it shouldn't be too difficult to adapt it to other Bundler versions:

```ruby
if RUBY_PLATFORM.include?('arm64-darwin')
  raise "BanUniversalDarwinGemsPatch was written against Bundler 2.1.2, but this is #{Bundler::VERSION}" if Bundler::VERSION != '2.1.2'
  class Bundler::Index
    module BanUniversalDarwinGemsPatch
      def search_by_dependency(dependency, base=nil)
        specs = super
        if dependency.name == 'grpc'
          specs.reject! do |spec|
            platform = spec.platform
            case platform
            when Gem::Platform
              platform.cpu == 'universal'
            when String
              platform.include?('universal')
            else
              raise "Unexpected platform #{platform}"
            end
          end
        end
        specs
      end
    end
    prepend BanUniversalDarwinGemsPatch
  end
end
```

This is ugly, cursed, and goes against every engineering principle out there, but it does work to unblock me while we wait for the problem to be fixed upstream.

**Comment by flavorjones** [comment]
My M1 just arrived and I'm in the process of setting it up. I will be able to work on the arm64-darwin report over the next day or two.

**Comment by univerio** [comment]
Thanks @apolcyn! Since the `universal-darwin` gem is no longer being published, this specific issue can be considered resolved from my perspective, but it sounds like there is still work left to publish a `arm64-darwin` gem (which AFAIU is being tracked elsewhere).

**Comment by jnarowski** [comment]
Where is `arm64-darwin` progress being tracked? I have a new m1 mac and am pretty blocked at the moment. I am struggling to get the old x64 version of ruby 2.6.6 working, and compiling ruby with the silicon architecture means this grpc gem doesn't work.

Short answer is arm64-darwin should be the answer to all my ailments!

**Comment by flavorjones** [comment]
See https://github.com/grpc/grpc/issues/28271#issuecomment-986300461 for related information
