### ISSUE TITLE
[FLAKE] Bazel RBE MSAN C/C++

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#28102]
test/core/transport/binder/binder_transport_test

https://source.cloud.google.com/results/invocations/00550130-c0b2-4b02-a059-cc772d9e02fd/targets/%2F%2Ftest%2Fcore%2Ftransport%2Fbinder:binder_transport_test/tests

**Comment by donnadionne** [comment]
healthy as of lately: https://source.cloud.google.com/results/invocations/c670bf03-5d69-4c60-a54c-9065cd01d4f7/targets;query=binder_transport
