### ISSUE TITLE
Go_server SSL & C++_client --> Failed to build 

### ISSUE THREAD

**Issue by TimelifeCzy** [grpc/grpc#28126]
1) Os: Windows10 ~ vs2019 
2) Latest Grpc (git clone)
3) Go Ssl server:
`
	cert, err := tls.X509KeyPair(crtFile, keyFile)
	if err != nil {
		fmt.Println(err.Error())
		return nil
	}
	certPool := x509.NewCertPool()
	if ok := certPool.AppendCertsFromPEM(caBytes); !ok {
		return nil
	}

	return credentials.NewTLS(&tls.Config{
		Certificates: []tls.Certificate{cert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
		ClientCAs:    certPool,
	})
` 
4) Go_client Success:
	certPool := x509.NewCertPool()

	certPool.AppendCertsFromPEM(ca)

	keyPair, _ := tls.X509KeyPair(cert, privkey)

	dialOptions = append(dialOptions, grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{
		Certificates: []tls.Certificate{keyPair},
		ServerName:   svrName,
		ClientAuth:   tls.RequireAndVerifyClientCert,
		RootCAs:      certPool,
	})), grpc.WithBlock(), grpc.WithTimeout(time.Second*2))

5) c++_client Error Tried multiple solutions,Convert crt to pem:
`
	auto rootcert = get_file_contents(rootcrt_path);
	auto clientkey = get_file_contents(clientkey_path);
	auto clientcert = get_file_contents(clientcrt_path);

	grpc::SslCredentialsOptions ssl_opts;
	ssl_opts.pem_root_certs = rootcert;
	//ssl_opts.pem_private_key = clientkey;
	//ssl_opts.pem_cert_chain = clientcert;
	auto channel_creds = grpc::SslCredentials(ssl_opts);
	//std::shared_ptr<grpc::ChannelCredentials> channel_creds = grpc::SslCredentials(ssl_opts);

	//  grpc::InsecureChannelCredentials()
	static Grpc greeter(
		grpc::CreateChannel("localhost:8888", channel_creds));
`
Error：
`
    auto nRet = stream->Write(rawData);   
    stream->WritesDone();
    status = stream->Finish();
    if (false == status.ok())
`
![image](https://user-images.githubusercontent.com/43507143/142419281-92ebae5b-6f1b-4ff7-ba9c-ce125b2e7615.png)
I read the documentation, but I don’t understand what to do?
https://github.com/grpc/grpc/issues/26106 & https://grpc.io/docs/guides/auth/#using-client-side-ssltls

**Comment by TimelifeCzy** [comment]
I tried some solutions for this problem, but it still doesn't work.

**Comment by ZhenLian** [comment]
Thanks for bringing up this issue.
It's not clear to me what was wrong on the client side. Were you able to see the logs on the client side? In C++, you can set environment variable GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG, then use a debug build(see https://github.com/grpc/grpc/blob/master/doc/environment_variables.md for more).

**Comment by TimelifeCzy** [comment]
Vs2019 uses nuget to manage grpc.
How can I configure the debugging mode?

**Comment by TimelifeCzy** [comment]
> Vs2019 uses nuget to manage grpc.
> How can I configure the debugging mode?

Vs2019 uses nuget to manage grpc.
How can I configure the debugging mode?

**Comment by TimelifeCzy** [comment]
> Thanks for bringing up this issue. It's not clear to me what was wrong on the client side. Were you able to see the logs on the client side? In C++, you can set environment variable GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG, then use a debug build(see https://github.com/grpc/grpc/blob/master/doc/environment_variables.md for more).

How can I provide an error log or view the grpc connection blog?

**Comment by ZhenLian** [comment]
I am not entirely sure about VS2019 and nuget. @markdroth, do we have any experts here?

Also a couple of follow-up questions:
1. I see in your code you were trying to use insecure credentials. Did that work? If that works, then we can probably rule out the connection problems, and the credential might be the cause
2. Can we please make sure the credential you use are valid and correct? Often times I would see users fail to make connections because their certificates are expired, or certificates are not trusted by the root certs, or some other reasons.

**Comment by TimelifeCzy** [comment]
Use vcpkg to install grpc.
Using the same .ca .key, golang successfully ssl to the client.
But I don't confirm whether I used it wrong or the code problem.
Hope that grpc can be configured for debugging. If there are problems in the future, I can check the error log first, and if I encounter difficulties, I can provide as detailed information as possible.
Currently I am not sure how vcpkg configures grpc debugging or output log logs.
This really bothered me for a long time. Hope to get help, grpc is deployed to the server golang as a node of win c++.

**Comment by TimelifeCzy** [comment]
golang server | C++ client
Belongs to the minority, I can’t find much help

**Comment by TimelifeCzy** [comment]
I forgot about this problem recently and tested it again：
1)  ca.crt client.crt client.key convers to .pem
`
openssl x509 -in ca.crt  -out ca.pem
openssl x509 -in client.crt  -out client.pem
openssl rsa -in client.key -out client_key.pem
`
2) SslCredentialsOptions ssl  = {".pem",".pem",".,".pem} --> SslCredentials(ssl) --> CreateChannel("ip:port", SslCredentials(ssl));

Error:
`
E1215 14:53:05.592000000  6576 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.
E1215 14:53:10.601000000 16648 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.
`
exec CreateChannel Error:
`
<HTML>
<head>
<title>Document</title></head>
<body>



  | 名称 | 值 | 类型
-- | -- | -- | --
  | err,hr | ERROR_ENVVAR_NOT_FOUND : 操作系统找不到已输入的环境选项。 | unsigned int



</body>
</HTML>

`
I feel that I have found the answer soon
