### ISSUE TITLE
Release 1.42.0 on rubygems

### ISSUE THREAD

**Issue by lugray** [grpc/grpc#28135]
### Is your feature request related to a problem? Please describe.
https://github.com/grpc/grpc/releases/tag/v1.42.0 exists, but hasn't been released at https://rubygems.org/gems/grpc

### Describe the solution you'd like
A new release

### Describe alternatives you've considered
Using the 1.42.0.pre1 release.

### Additional context
1.42.0 is necessary for arm macs.

**Comment by markdroth** [comment]
The release process isn't finished yet.  We're working on it.
