### ISSUE TITLE
application crash on immediate startup

### ISSUE THREAD

**Issue by npd26** [grpc/grpc#28150]
Hello,

we are using grpc with c++ windows application. when we start .exe and close it and again start immediately application crash with below error.

```
E1112 09:46:30.607000000  3240 tcp_server_windows.cc:336] on_accept error: Either the application has not called WSAStartup, or WSAStartup failed.

E1112 09:46:30.615000000  3240 tcp_server_windows.cc:384] start_accept: {"created":"@1636706790.615000000","description":"OS Error","file":"C:\project\grpc-1.42.0_build\src\core\lib\iomgr\tcp_server_windows.cc","file_line":266,"os_error":"Either the application has not called WSAStartup, or WSAStartup failed.\r\n","syscall":"WSASocket","wsa_error":10093}
Connected
E1112 09:46:30.624000000  3240 tcp_server_windows.cc:384] assertion failed: GRPC_LOG_IF_ERROR("start_accept", start_accept_locked(sp))
```

or some time with

`
E1118 17:12:44.787000000 25792 server_chttp2.cc:48] {"created":"@1637251964.787000000","description":"OS Error","file":"C:\project\grpc-1.42.0_build\src\core\lib\iomgr\resolve_address_windows.cc","file_line":93,"os_error":"Either the application has not called WSAStartup, or WSAStartup failed.\r\n","syscall":"getaddrinfo","wsa_error":10093}`

 but if there is gap between application close and start it work without crashing.

**Comment by veblush** [comment]
This could be caused by the listening port occupied by the application which just exited. Would you try to run `examples/cpp/helloworld` example to see this is reproducible with this simple example?
