### ISSUE TITLE
Proxy CONNECT header generated can be malformed on bad target specification

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#28173]
### What version of gRPC and what language are you using?

1.37, Python

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python3

### What did you do?

1. Set up a proxy using the https_proxy environment variable
2. Create a channel to a target that only includes a name, not a port number (so this is a bad target, I get it)
3. Monitor what gets sent to the proxy

### What did you expect to see?

Since the target was actually improperly specified, gRPC should never have generated a CONNECT request to the proxy, since it can't properly specify to what it wants to connect.

### What did you see instead?

gRPC generates a CONNECT method that only gives the server name, not the port (`CONNECT my.server.name HTTP/1.0`) .

This is a malformed CONNECT since the [HTTP specification indicates that CONNECT must include a host and port](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6). (The wording is cryptic but not ambiguous since it first says that it must be an authority form request target but then goes on to say that it only includes a host and a port.) Since CONNECT is meant to be protocol agnostic in terms of its payload, there is no meaningful default port, unlike the more conventional http URLs.

As a result, the proxy fails with an unparseable header response and that doesn't get reflected back to the RPC in a debuggable way.

Instead, the RPC should fail before sending the CONNECT and some gRPC tracer (or some other mechanism) should indicate that the problem was that the target was improperly specified and thus can't go on to the proxy. For example, the method that [generates the CONNECT](https://github.com/grpc/grpc/blob/ea389c00c2c83e0364c5b1cfb73820c0101daa14/src/core/lib/http/format_request.cc#L96)  should validate `request->http.path` before passing it directly to a CONNECT header.

### Anything else we should know about your project / environment?

We're hiring?

**Comment by vjpai** [comment]
I spoke with @markdroth about this when we observed this problem, and he suggested that I tag @yashykt ; I can't change the assignment, unfortunately.

**Comment by nicolasnoble** [comment]
But I can, hah!

**Comment by yashykt** [comment]
Is this an old bug?

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/pull/26331 should have fixed this if I'm not misreading things.

**Comment by yashykt** [comment]
Ah, 1.37. This PR should be available since 1.39. I can backport it if needed.

**Comment by vjpai** [comment]
Ah, thanks for the info! Looks like we were using the same version that previously reported the bug. No need to backport for me as we've already worked around it.
