### ISSUE TITLE
Expose channel_arg  "grpc.compression_level" in core.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2817]
I think most wrapped languages will want to only expose compression_level enumeration (and not compression_algorithm) in the public API (otherwise things get unnecessarily complicated). This works fine until the point when user wants to set compression for a server/channel - which is done by a channel argument. Currently core only exposes channel argument "grpc.compression_algorithm", which is somewhat unfortunate.

If given wrapped language exposes the channel arguments API directly (I think most of them do, C# definitely does), there is no way of hiding the fact that channel argument actually sets compression algorithm instead of compression level (because user has control over the channel arguments he is passing down) and I think attempts to wrap the compression_algorithm arg to look like it's actually compression_level arg will just result in ugly code. If I could set grpc.compression_level arg instead, the user could happily use the enum CompressionLevel as the argument value and things would make more sense.

**Comment by ctiller** [comment]
We will get to this, but there's no chance of a sensible implementation before beta, and I'm not keen to expose a broken implementation as our only api.

**Comment by jtattermusch** [comment]
Ok, does that mean I need to come up with a workaround for now (and remove that workaround from the API once the right channel argument is available)? Probably yes.

Btw, it looks like C++ currently exposes  API to set compression level (or compression algorithm) for ClientContext and ServerContext  but is doesn't really look like the values set there are actually used anywhere. Does that mean we don't support disabling compression for Unary request and unary response calls? (For streamed responses, you can use the WriteOptions argument when writing a message, but for "unary write", it seems like you cannot).

**Comment by kpayson64** [comment]
@dgq is this done now?

**Comment by dgquintas** [comment]
yes
