### ISSUE TITLE
undefined reference to absl::lts_20211102::debugging_internal::VDSOSupport::Init()

### ISSUE THREAD

**Issue by only-test-linux** [grpc/grpc#28226]
ubuntu20.04 QT compilation error, cmake compilation is normal

**Comment by drfloob** [comment]
Are your submodules initialized and up to date? Assigning to @veblush in case further investigation is needed.

**Comment by only-test-linux** [comment]
The cmake compilation can run normally, but when compiled on QT, absl::lts_20211102 cannot be found

**Comment by only-test-linux** [comment]
Submodule initialization refers to: git submodule update --init? If so, I have already initialized

**Comment by only-test-linux** [comment]
QT's pro file increased
QMAKE_CXXFLAGS += `pkg-config --cflags= protobuf grpc`
QMAKE_CXXFLAGS += -std=c++11
QMAKE_LIBS += `pkg-config --libs= protobuf grpc++` -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl

**Comment by only-test-linux** [comment]
Caused by a configuration error on my side
