### ISSUE TITLE
Bad documentation for C++ async methods

### ISSUE THREAD

**Issue by heretic13** [grpc/grpc#28239]
Hi.

I think you have a problem with the documentation.
Take a look at the page.

https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_async_response_writer.html#details

On methods:
void Finish(const W &msg, const ::grpc::Status &status, void *tag);
void FinishWithError(const ::grpc::Status &status, void *tag);

The documentation doesn't tell us anything about the lifetime of the "const W & msg" and "const::grpc ::Status & status" arguments.

Can I create these parameters on the stack, call the method and destroy immediately?
Or should I keep the arguments (one or both?) and only remove them after the asynchronous operation completes?

I want to note that this is not a "question to the developers", usually such things are described in the documentation (as it is done in other third-party libraries).

**Comment by heretic13** [comment]
Look at this - https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_async_writer.html#a467f70c7460ceb7738fb938b3bf93c85

"gRPC doesn't take ownership or a reference to msg and status, so it is safe to deallocate once WriteAndFinish returns."

I want something similar to be written for the methods of the grpc::ServerAsyncResponseWriter class.

**Comment by drfloob** [comment]
The documentation is less than comprehensive in some spots, I agree. We'd be grateful to accept pull requests where deficiencies are found.

For const reference arguments, ownership is explicitly not transferred, and the lifetime of the objects must outlive their use (stating the obvious here, just in case). If you look at the hello world example's `greeter_async_server`, `greeter_async_client` and `greeter_async_client2`, you'll see three different ways in which the application can choose to manage the lifetime of those objects passed to `Finish`, which are similar for client and server: local stack variables, an object on the heap, and class members that get overwritten. In short, the application owns the objects, knows when processing is finished, and should clean up any objects that it owns when finished. In this case, something like `"gRPC doesn't take ownership or a reference to msg and status, so it is safe to deallocate them once the Finish operation is complete (i.e. a result shows up in the CQ)"`

This is more of an ongoing effort than a specific issue which will get tackled in one go. I'll fix this instance and close the Issue, noting that this doesn't fix _all_ bad documentation.
