### ISSUE TITLE
grpc Ruby gem fails to install due to using too many parallel jobs while compiling inside container

### ISSUE THREAD

**Issue by ivoanjo** [grpc/grpc#28244]
### What version of gRPC and what language are you using?
* grpc version: `1.41.1`
* language: `ruby`

### What operating system (Linux, Windows,...) and version?
* Linux (multiple versions)

### What runtime / compiler are you using (e.g. python version or version of gcc)
* Multiple versions

### What did you do?
* Tried to install gem inside a container: `gem install grpc`

### What did you expect to see?

* `grpc` gem installs successfully

### What did you see instead?

The `grpc` installation was killed by Linux's out-of-memory killer.

This happens because `Etc.nprocessors` as used in grpc's [`extconf.rb` file](https://github.com/grpc/grpc/blob/205d7569eadd03456e2a692a011d630c0ba42a12/src/ruby/ext/grpc/extconf.rb#L72) returns 36 cpus for the CI machine we're using, which makes `grpc` try to compile stuff with `make -j72`.

Unfortunately we're inside a constrained docker container, but the 36 cpus value returned by `Etc.nprocessors` is the value for the host machine, not the container (this is a Ruby, not grpc limitation).

Having 72 instances of gcc is too much for most CircleCI [resource classes](https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes) and thus the installation fails by running out of memory.

### Anything else we should know about your project / environment?
I work @Datadog on our `ddtrace` Ruby gem, and we have support for integrating with `grpc`. I ran into this issue in our integration tests that run in CircleCI (https://github.com/DataDog/dd-trace-rb/issues/1791).

It would be great if `grpc` could actually use the number of CPUs that is assigned to the docker container; failing that, even having a simple environment variable where we can specify the number of make jobs or way of disabling the parallel compilation would be enough to solve the issue for us.

**Comment by apolcyn** [comment]
PTAL at https://github.com/grpc/grpc/pull/28250, which adds an env var to override this
