### ISSUE TITLE
flaky test: python_macos_opt_asyncio_py38_asyncio_test_aio_unit_server_test_TestServer.py38_asyncio.test_aio.unit.server_test.TestServer 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#28242]
https://source.cloud.google.com/results/invocations/5a4b8e54-9fe5-4932-a57a-10ee76a1f978/targets/github%2Fgrpc%2Frun_tests%2Fpython_macos_opt_asyncio%2Fpy38_asyncio.test_aio.unit.server_test.TestServer/tests

**Comment by lidizheng** [comment]
This is the same as b/208447419, should be fixed by https://github.com/grpc/grpc/pull/28229.
