### ISSUE TITLE
INotifyPropertyChanged implementation on IMessage

### ISSUE THREAD

**Issue by MrDeej** [grpc/grpc#28270]
### Is your feature request related to a problem? Please describe.
Every time we build an app which uses gRPC, we need to convert from auto-generated IMessage class, to an separate c# class, to provide INotifyPropertyChanged interface.

This is due to "live-updating" the data on the client side, and that we use databinding in the UI to the instances of the converted IMessages. 

This meas that for each IMessage class, we create an equivalent c# Class, and we also have to write an converter which clone from IMessage to Class instance.

This makes us develop 2 extra steps for each message type, and this is also bug-prone to wich the developer have forgotten and field or somthing like that.

### Describe the solution you'd like
Grpc.Tools should at least have an option to auto-implement INotifyPropertyChanged for all the properties in the IMessage class. Actually i think it should be default enabled like svcutil.exe is. 

### Describe alternatives you've considered
We are currently investigating if we can use some sort of source-code generations to add the lines needed in the set property function in the IMessage class and implementing the interface automatically after the Grpc.Tools have run and done its business. 

We are worried about future changes to Grpc.Tools that will maybe break this.

### Additional context
We would also like to use IMessages as input to EF Core. But that is a different ballgame.
Our current data structure is:

MS SQL Server -> Ef.Core Dbmodels -> IMessages -> Classes with INotifypropertyChanged

We do both the Ef.Core Dbmodels converting to and from IMessage, and IMessage to and from UI Classes with INotifyPropertyChanged.

Each datatable in our SQL we have to make manually 4 different methods to convert back-and-fort between this. Partly due to an self-developed in-memory feature between our SQL server and the IMessage interface to the clients.

**Comment by drfloob** [comment]
By any chance are you using the native C# implementation? If so, you'll want to file this issue at https://github.com/grpc/grpc-dotnet. If you are using the C-core wrapped implementation in this repo, it was deprecated in May, and no new development is planned for it. https://www.grpc.io/blog/grpc-csharp-future/. So you don't have to worry about changes to it, but you should consider migrating regardless.

**Comment by drfloob** [comment]
Closing this as stale and not actionable.
