### ISSUE TITLE
Rearrange C++ headers

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2827]
Move into impl/:
- async_unary_call.h

Move into support/:
- time.h
- slice.h
- config.h
- config_protobuf.h
- byte_buffer.h
- status_code_enum.h
- status.h
- fixed_size_thread_pool.h
- dynamic_thread_pool.h
- thread_pool_interface.h
- channel_arguments.h

Move into generic/:
- async_generic_service.h
- generic_stub.h

**Comment by yang-g** [comment]
async_unary_call.h contains user-facing types. It should stay in the current place?
If we put status.h and channel_arguments.h in support/, then what about stub_options.h, auth_context.h and credentials?
