### ISSUE TITLE
python 3.10.1 failed to connect to all addresses 

### ISSUE THREAD

**Issue by fainle** [grpc/grpc#28323]
### What version of gRPC and what language are you using?
grpcio == 1.42.0
grpcio-tools  == 1.42.0
grpclib == 0.4.2

### What operating system (Linux, Windows,...) and version?
ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10.1

### What did you do?
```python
import asyncio
import grpc

from flow.access import access_pb2
from flow.access import access_pb2_grpc

from grpclib.client import Channel


async def main():
    with grpc.insecure_channel('flow-mainnet.g.alchemy.com:443​', options=(('grpc.enable_http_proxy', 0),)) as channel:
        stub = access_pb2_grpc.AccessAPIStub(channel)        
        request = access_pb2.GetLatestBlockRequest(is_sealed=False)

        a = stub.GetLatestBlock(request)
        print(a)

    channel.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

### What did you expect to see?
block {
  id: "%]9\201\305_\363%\320\247\265\226\332U\2232&\321\3758>P\361\317\0034\0044\313\250\225_"
  parent_id: "\335\004\370\265\253\226\263\033\207\220\235?\264\000\023\245\235\003oE\224\241Wc\334\036P\024j\275|P"
  height: 48716358
  timestamp {
    seconds: 1639053676
    nanos: 390496125
  }
  block_seals {
    block_id: ";\334\343^\250ya|\2115\357\251S.\302\263\035\330So\373\255\02585v/b[\267\000\335"
    execution_receipt_id: "\242P&\256~\002\302N5\260\357T\351m\221\334>X\207&\320B!mK\256\230\374J\214\201D"
  }
  signatures: "\225\377\264-m\003/\202\323 \245\334\233mF\330\256\311\200NF\357/\230\371\010\036\301\033\202W\034\037\374\357\223\275\031D\342\224\027\366\345^\264N\000\220-\013X\2530\27114\016\234o\316\267O\205e\322)\027h\020\205\207\313X\006A\363V\311\366\177\205\006ZQ~\224p\335\226\340x9\246\246\374"
}

### What did you see instead?

raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1639053733.646694051","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1639053733.646693220","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"

flow-mainnet.g.alchemy.com:443 Address failed
access.canary.nodes.onflow.org:9000 Address success

**Comment by lidizheng** [comment]
It's hard to say what the problem is with the given information. Can you share more about the server-side deployment?

`failed to connect to all addresses` means the resolver has returned several addresses, but none of them can be reached by the client.

**Comment by fainle** [comment]
> 很难说给定的信息有什么问题。你能分享更多关于服务器端部署的信息吗？
> 
> `failed to connect to all addresses` 意味着解析器返回了多个地址，但客户端无法访问它们。

The same code, one address can be one address but not

access.canary.nodes.onflow.org:9000 ok
flow-mainnet.g.alchemy.com:443 fail

Is it related to certification?

**Comment by fainle** [comment]
> 很难说给定的信息有什么问题。你能分享更多关于服务器端部署的信息吗？
> 
> `failed to connect to all addresses` 意味着解析器返回了多个地址，但客户端无法访问它们。

It has been resolved, and it is related to the certificate.

**Comment by Ronghefeng** [comment]
> > 很难说给定的信息有什么问题。你能分享更多关于服务器端部署的信息吗？
> > `failed to connect to all addresses` 意味着解析器返回了多个地址，但客户端无法访问它们。
> 
> It has been resolved, and it is related to the certificate.

How do you solve this problem? I have the same problem @fainle 

my code:

```
    with grpc.insecure_channel(
        womo_grpc_addr, options=(("grpc.enable_http_proxy", 0),)
    ) as channel:
        stub = statistics_pb2_grpc.StatisticsStub(channel)

        response = stub.GetUserNoticeDetail(
            statistics_pb2.UserNoticeDetailRequest(user_id=str(sender_id))
        )
```
error:
![image](https://user-images.githubusercontent.com/42339196/149104556-96e34dc3-a836-41d6-afc6-dbb6c0876adc.png)

**Comment by tan-i-ham** [comment]
I met the same problem, how did you solve it? @fainle

**Comment by Malik0411** [comment]
To anyone else that has experienced this issue, in my case, the problem is caused due to using insecure channels to call the gRPC server. I have a gRPC server deployed in GCP Cloud Run; with my endpoints being exposed through GCP API Gateway. In my client code, I have the following from the [gRPC Bookstore example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/bookstore_client.py):
```
if use_tls:
    with open(ca_path, 'rb') as f:
        creds = grpc.ssl_channel_credentials(f.read())
    channel_opts = ()
    channel = grpc.secure_channel('{}:{}'.format(host, port), creds, channel_opts)
else:
    channel = grpc.insecure_channel('{}:{}'.format(host, port))
```
To use the secure channel, I pass `use_tls` as `True` and `ca_path` as the path to my `roots.pem` file to my `run` function in the client. The `roots.pem` file can be found in the same [example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/roots.pem).

After calling the server with a secure channel on port 443, I was able to hit endpoints on my gRPC server! Hope this helps anyone else who was struggling with this issue.

**Comment by timnugent** [comment]
I was having this issue connecting to Flow via Alchemy GPRC - this is how I fixed it:

```
import pprint
import grpc
from flow.access import access_pb2
from flow.access import access_pb2_grpc

ALCHEMY_FLOW_HOST = "flow-mainnet.g.alchemy.com:443"
ALCHEMY_FLOW_KEY_HEADER = "api_key"
ALCHEMY_FLOW_KEY_VALUE = "XXXXXXXXXXXXXX"

class GrpcAuth(grpc.AuthMetadataPlugin):
    def __init__(self, key):
        self._key = key

    def __call__(self, context, callback):
        callback(((ALCHEMY_FLOW_KEY_HEADER, self._key),), None)

if __name__ == "__main__":
    channel = grpc.secure_channel(
        ALCHEMY_FLOW_HOST,
        grpc.composite_channel_credentials(
            grpc.ssl_channel_credentials(),
            grpc.metadata_call_credentials(GrpcAuth(ALCHEMY_FLOW_KEY_VALUE)),
        ),
    )
    stub = access_pb2_grpc.AccessAPIStub(channel)
    response = stub.GetLatestBlock(access_pb2.GetLatestBlockRequest())
    pprint.pprint(response.block.height)
```

**Comment by Ronghefeng** [comment]
> secure_channel

My problem is solved, change 'insecure_channel' to 'secure_channel', and add credentials with grpc.ssl_channel_credentials()

```
    with grpc.secure_channel(
        womo_grpc_addr, grpc.ssl_channel_credentials(),
        options=(("grpc.enable_http_proxy", 0),)
    ) as channel:

       stub = statistics_pb2_grpc.StatisticsStub(channel)

        response = stub.GetUserNoticeDetail(
            statistics_pb2.UserNoticeDetailRequest(user_id=str(sender_id))
        )
    
```
