### ISSUE TITLE
pip install grpcio fails for python3.8 on multiple unix flavours

### ISSUE THREAD

**Issue by huaraz** [grpc/grpc#28337]
I try to install grpcio 1.42 on a unix platform ( Suse SLES11 and cygwin). On both platforms it fails when compiling a.c in None with gcc error.

Markus

$ pip3 install --upgrade grpcio

Collecting grpcio

  Using cached grpcio-1.42.0.tar.gz (21.3 MB)

  Preparing metadata (setup.py) ... done

Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.8/site-packages (from grpcio) (1.14.0)

Building wheels for collected packages: grpcio

  Building wheel for grpcio (setup.py) ... -

.. 

 

compilation terminated.

  creating None

  creating None/tmp

  creating None/tmp/tmpppjalf_l

  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -DOPENSSL_NO_SSL3=1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.10-1.x86_64/build=/usr/src/debug/python38-3.8.10-1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.10-1.x86_64/src/Python-3.8.10=/usr/src/debug/python38-3.8.10-1 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -DOPENSSL_NO_SSL3=1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.10-1.x86_64/build=/usr/src/debug/python38-3.8.10-1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.10-1.x86_64/src/Python-3.8.10=/usr/src/debug/python38-3.8.10-1 -I/usr/include/python3.8 -c /tmp/tmpppjalf_l/a.c -o None/tmp/tmpppjalf_l/a.o

  Traceback (most recent call last):

    File "/usr/lib/python3.8/distutils/unixccompiler.py", line 127, in _compile

      self.spawn(compiler_so + cc_args + [src, '-o', obj] +

    File "/tmp/pip-install-la8i6j_1/grpcio_475c6c67692b4bde9fa8668afd5bae96/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn

      _classic_spawn(self, command)

    File "/usr/lib/python3.8/distutils/ccompiler.py", line 910, in spawn

      spawn(cmd, dry_run=self.dry_run)

    File "/usr/lib/python3.8/distutils/spawn.py", line 36, in spawn

      _spawn_posix(cmd, search_path, dry_run=dry_run)

    File "/usr/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix

      raise DistutilsExecError(

  distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

**Comment by lidizheng** [comment]
We don't support cygwin. For SUSE, if it fits Python's manylinux standard, it should be able to pull our pre-compiled wheels. Have you tried to upgrade `pip`? As latest binary standard might require newer `pip`.

```
pip install -U pip
```
