### ISSUE TITLE
How to use OpenSSL Engine

### ISSUE THREAD

**Issue by daixiang0** [grpc/grpc#28330]
### Is your feature request related to a problem? Please describe.
I check the code and add `engine:dynamic:` in the header of key file, but fail. I do not find an example or a doc for it.

### Describe the solution you'd like
Provide an example or doc for it.

### Additional context
Ref #20316

/cc @akshayku as you are the author.

**Comment by daixiang0** [comment]
@yashykt could you help take a look?

**Comment by daixiang0** [comment]
@lidizheng could you help take a look?

**Comment by lidizheng** [comment]
cc @drfloob

**Comment by yashykt** [comment]
@ZhenLian would you be able to help with this?

**Comment by drfloob** [comment]
Related to https://github.com/grpc/grpc/pull/28727

**Comment by daixiang0** [comment]
@drfloob I am afraid that #28727 only add an example about how to use SSL with gRPC, not about how to use OpenSSL Engine with gRPC.

**Comment by ZhenLian** [comment]
Personally I don't have much experience setting up OpenSSL engine. From the code we have in https://github.com/grpc/grpc/pull/20316, it seems we will need to do the following:

1. Enable OpenSSL Engine: https://www.openssl.org/docs/man1.0.2/man3/engine.html
2. when configuring the private key string, use string format "engine:<engine_id>:<key_id>" and it will automatically pick up the corresponding slot in the engine

Can you please try it out and see if that works? 

@akshayku the original PR author to see if we can get some advice as well.

**Comment by daixiang0** [comment]
It is what I tried in the past, it can not work, also I think step 1 is in the gRPC code.

**Comment by ZhenLian** [comment]
@daixiang0 does your gRPC use BoringSSL or OpenSSL? This feature is only available in OpenSSL. You might have to re-build your gRPC and use OpenSSL if you are using BoringSSL.
We have internal users who successfully built their OpenSSL engine. They are using Python, but should be the same as C++: those two languages have the same gRPC core.
Here is what they said:
```
(1) user has to install a custom gRPC build (to replace BoringSSL with system OpenSSL). The steps are:

# Download the grpc repo.

$ git clone https://github.com/grpc/grpc.git


# Install a custom build with system openssl

$ cd grpc/

$ git submodule update --init

$ python -m pip install -r requirements.txt

$ GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 python -m pip install .


(2) user can then pass the following bytes for the key: b"engine:engine_id:key_uri". 

For example, our engine id is: pkcs11, and key uri is: "key_uri", so the key to use is: b"engine:pkcs11:key_uri".

Regarding the key uri: the key_uri is [RFC7512](https://datatracker.ietf.org/doc/html/rfc7512) format, users can refer to the RFC to figure out the correct value.

Regarding the engine id: user can run "openssl engine" to find the correct id.
```
Please let me know if you have any questions.

**Comment by yashykt** [comment]
Closing since there hasn't been a response from the user.

**Comment by daixiang0** [comment]
Sorry for slow reply, I will try, thanks!
