### ISSUE TITLE
For Obj-C client, how to enable method calls from multiple services to share a underlying http channel?

### ISSUE THREAD

**Issue by xinqianli** [grpc/grpc#2839]
For C# client code, method calls from multiple services can share a underlying http channel, as following:
var channel = new Channel("localhost:50051", credentials);
var client = new Greeter.GreeterClient(channel,
        new StubConfiguration(OAuth2InterceptorFactory.Create(credential)));

But in Obj-C client code, it seems not working:
static NSString * const kHostAddress = @"http://localhost:50051";
HLWGreeter *client = [[HLWGreeter alloc] initWithHost:kHostAddress];

It creates a separated channel per service.

So, for Obj-C client code, how to enable method calls from multiple services to share a underlying http channel, like C# client code?

**Comment by jcanizales** [comment]
> It creates a separated channel per service.

This should definitely not be the case :) The Obj-C client caches and reuses connections to the same host automatically. Are you actually seeing multiple channels being opened, or is it just that we should clarify it in the documentation?

**Comment by xinqianli** [comment]
Thanks @jcanizales . We tested it again and got the expected result that reuses the same connections. Sorry we didn't find why we saw multiple channels for the same host last week.
