### ISSUE TITLE
python distribution test prod failure since yesterday 

### ISSUE THREAD

**Issue by dennycd** [grpc/grpc#28405]
* <https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_distribtests_python>

As seen in samples 

* <https://source.cloud.google.com/results/invocations/0de9ea3a-acbf-4f1b-9251-029782690da1/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_distribtests_python/log>

**Comment by lidizheng** [comment]
I proposed one fix in https://github.com/grpc/grpc/pull/28397, but it has an unwanted side-effect.

**Comment by lidizheng** [comment]
Fixed by https://github.com/grpc/grpc/pull/28410
