### ISSUE TITLE
Segmentation fault occurred, stream service

### ISSUE THREAD

**Issue by byhang** [grpc/grpc#28413]
https://github.com/grpc/grpc/blob/7d8c9ae890c96abd959aae4e0c3191fa9eb0472b/include/grpcpp/impl/codegen/proto_utils.h#L54

Dear, 
I want to wirte a stream service, but segmentation fault occurred when return, Is there any problem with me writing like this?

**.proto**
`rpc func(Request) returns (stream Response) {};`

**.cpp**
```
grpc::ServerWriteReactor<Response> *func(
        CallbackServerContext *context,
        const Request *req) override
    {
        class Lister : public grpc::ServerWriteReactor<Response>
        {
        public:
            Lister(const Request *req)
            {
                req_ = *req;
                NextWrite();
            }
            void OnDone() override { delete this; }
            void OnWriteDone(bool /*ok*/) override { NextWrite(); }

        private:
            void NextWrite()
            {
                if(1)
                {
                        Response res;
                        StartWrite(&res);
                        return;
                }
                Finish(Status::OK);
            }
        };
        return new Lister(req);  // Segmentation fault 
    }
```

**Comment by mocsharp** [comment]
HI @byhang, I was wondering how you solved this issue. Thanks!

**Comment by vlantonov** [comment]
Seems that `Response res;` was accessed after being destroyed which causes segmentation fault. This can be solved by making `res` an argument of `Lister` or by `static Response res;`
