### ISSUE TITLE
Python setup.py does not reflect correct protobuf package minimum version

### ISSUE THREAD

**Issue by charlietsai** [grpc/grpc#28479]
### What version of gRPC and what language are you using?
Python

grpcio==1.43.0
grpcio-health-checking==1.43.0

protobuf==3.8.0

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6

### What did you do?
I installed:
```
 pip install grpcio-health-checking==1.43.0 grpcio==1.43.0 protobuf==3.8.0
```
and attempted to import `from grpc_health.v1 import health`.

### What did you expect to see?

According to the [setup.py](https://github.com/grpc/grpc/blob/v1.43.0/src/python/grpcio_health_checking/setup.py#L65) for e.g., `grpcio-health-checking`, the protobuf requirements is `protobuf>=3.6.0`, so my versions should be compatible. This has worked fine for older versions, like `1.27.1`.

### What did you see instead?

I am seeing this error when importing:
```
from grpc_health.v1 import health
```

```
  File "/root/.pex/installed_wheels/224e0641c7a5f11b4a7ec967f92599b2caa987f2/grpcio_reflection-1.43.0-py3-none-any.whl/grpc_reflection/v1alpha/reflection_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

This looks like the code may have been generated with a later version of `protoc`? If so, the minimum version should be bumped up to reflect that.

### Anything else we should know about your project / environment?

N/A

**Comment by lidizheng** [comment]
A version bump PR is drafted at https://github.com/grpc/grpc/pull/28604. Should fix this problem. Thanks for reporting.
