### ISSUE TITLE
Import proto file was not found when files added as URL service references in Visual Studio

### ISSUE THREAD

**Issue by zakkra** [grpc/grpc#28481]
Added a couple of proto files through "Manage connected services" in VS 2019 (same issue in VS 2022) by using a URL reference to the files.

This added a Protos folder to my project with 2 proto files inside it.
My csproj file also got updated with this section:

```
  <ItemGroup>
    <Protobuf Include="Protos\nullabletypes.proto" GrpcServices="Client">
      <SourceUri>https://somewhere/api/protos/v1/nullabletypes.proto</SourceUri>
    </Protobuf>
    <Protobuf Include="Protos\valuationcriteria.proto" GrpcServices="Client">
      <SourceUri>https://somewhere/api/protos/v1/valuationcriteria.proto</SourceUri>
    </Protobuf>
  </ItemGroup> 
```

The valuationcriteria.proto contains:

```
syntax = "proto3";

//option csharp_namespace = "GrpcValuationsTypes";
import "google/protobuf/timestamp.proto";
import "nullabletypes.proto";

package valuationcriteria;
etc
```

The project doesn't build with error:
Import "nullabletypes.proto" was not found or had errors.	In valuationcriteria.proto	 file	

If I move proto files into the root of the project (getting rid of Protos folder), the project builds OK.
Looks like the code generator is not looking for the imported file in the correct location.

**Comment by drfloob** [comment]
This sounds like an IDE problem with proto paths, I don't see how gRPC is directly involved. A quick googling revealed some similar-sounding issues, with potential solutions: https://stackoverflow.com/a/59411655/10161
