### ISSUE TITLE
GRPC build fail for version 1.43.0

### ISSUE THREAD

**Issue by GammaPi** [grpc/grpc#28507]
### What version of gRPC and what language are you using?

1.43.0, C++

### What operating system (Linux, Windows,...) and version?

Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 9.3.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I manually compiled with cmake and statically linked grpc in cmake. Specifically, I linked two .a files:
1. libgrpc++.a 
2. libprotobuf.a  

### What did you see instead?

```
/usr/bin/ld: CMakeFiles/libScalerHook-unittests.dir/__/__/proto/build/analyzerserver/InfoService.grpc.pb.cc.o: in function `grpc::CompletionQueue::~CompletionQueue()':
/home/st/Projects/Scaler/proto/lib/grpc_1_43_0/release/include/grpcpp/impl/codegen/completion_queue.h:119: undefined reference to `absl::lts_20211102::Mutex::~Mutex()'
/usr/bin/ld: CMakeFiles/libScalerHook-unittests.dir/__/__/proto/build/analyzerserver/InfoService.grpc.pb.cc.o: in function `grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&)':
/home/st/Projects/Scaler/proto/lib/grpc_1_43_0/release/include/grpcpp/impl/codegen/completion_queue.h:253: undefined reference to `absl::lts_20211102::Mutex::~Mutex()'
```

**Comment by GammaPi** [comment]
The problem seems to caused by a legacy findxxx.cmake I downloaded from the internet.

**Comment by hypnoce** [comment]
@GammaPi I'm facing this issue but I don't see any cmake issue o my side. How did you solve it ?
Thanks
