### ISSUE TITLE
Latency increase starting 1.31.0

### ISSUE THREAD

**Issue by pjthepooh** [grpc/grpc#28533]
### What version of gRPC and what language are you using?
gRPC version: 1.41.0
language: Python

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.5 (GCC 7.5.0)

### What did you do?
We were on gPRC version 1.29.0 and things worked fine with the p95 latency of the interested endpoint at ~20ms. After we upgraded to 1.41.0, we saw p95 latency increased to ~50ms on client. We searched the version that the regression was introduced and was able to identified that it was 1.31.0 ([changelog](https://github.com/grpc/grpc/releases/tag/v1.31.0)). We didn't change any user code but only updated the grpcio and grpcio-tools. We moved forward to 1.41.0 and the issue still exists.

We tried flipping `wait_for_ready` flag (because we suspected [this commit](https://github.com/grpc/grpc/pull/23163)) but saw no effect. We next suspected any ssl changes that could cause it, but we explicitly use insecure channel in the code (see last section).

### What did you expect to see?
I'd expect no performance change, at least not so much.

### What did you see instead?
Saw tail latency (p90+) increase in a particular endpoint on client side, no change in p50, p75 etc. There is no server side effect. Note that the latency metric reported is the full cycle of a request, including retries (3 attempts max) and backoff.

A ping from client to server takes ~5-10ms due to multiple hops in our system.

there are handy of these errors but could be irrelevant to the latency increase.
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1641922854.576476021","description":"Error received from peer ipv4:172.17.0.46:5810","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Here is roughly how we implement our gPRC client:
```python
grpc_options = [
    ('GRPC_ARG_KEEPALIVE_TIME_MS', 3000000),
]

channel = grpc.insecure_channel("my_host", options=grpc_options)

interceptors = (
    BasicAuthInterceptor(),
    RetryInterceptor(),
)

grpc_service = featurestore_pb2_grpc.FeatureStoreStub(
    grpc.intercept_channel(channel, *interceptors)
)

res: featurestore_pb2.Response = grpc_service.ingest_features(request=featurestore_pb2.Request, timeout=0.2, wait_for_ready=False)
```
where in `BasicAuthInterceptor`, we create a new `ClientCallDetails` and inject basic auth header in `metadata` and pass other fields from the old call details object along. `RetryInterceptor` has our in-house exponential backoff retry logic.

The host is address to the envoy sidecar in our client side service. Envoy will route the request to an NLB then to the K8s server written in golang.

Proto definitions for request and response
```proto
message Request {
  repeated string included_feature_groups = 1;

  map<string, FeatureGroup1> feature_group_1 = 2;
  map<string, FeatureGroup2> feature_group_2 = 3;
  map<string, FeatureGroup3> feature_group_3 = 4;
}

message Response {
  string response = 1;
}
```

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by gnossen** [comment]
Just a hunch. Can you try your benchmark again with the env var `GRPC_POLL_STRATEGY=epoll1` set and report back results? Also for `GRPC_POLL_STRATEGY=poll`?
