### ISSUE TITLE
Publish gRPC API docs for Ruby

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#2854]

**Comment by tbetbetbe** [comment]
@hsaliak: this actually happens automatically, e.g,  http://www.rubydoc.info/gems/grpc/0.10.0.

Since that's happens after Beta (once beta deb package and gem are published,  can we remove the Beta milestone from this ?  I think this should be tracked amongst the launch issues, once they are added.

**Comment by hsaliak** [comment]
Sounds good - this does not need to be done before beta. I'll leave the beta milestone on this issue because it will help us ensure this gets done when the beta gem is published.

**Comment by tbetbetbe** [comment]
This has been done now that [grpc 0.11.0](http://www.rubydoc.info/gems/grpc/0.11.0)
