### ISSUE TITLE
How to add rest api in python using google.api.http?

### ISSUE THREAD

**Issue by psydok** [grpc/grpc#28545]
How to implement grpc-gateway on rest api in python?

```
syntax = "proto3";
import "google/api/annotations.proto";

service TestService {
    rpc Method(MethodRequest) returns (MethodResponse) { 
            option (google.api.http) = {
            post: "/api/v1/test:method"
            body: "*"
        };
    }
}
```
What should be added here?
```
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    stt_pb2_grpc.add_TestServiceServicer_to_server(
        TestService(), server
    )
    address = f"{host}:{port}"
    server.add_insecure_port(address)
    server.start()
    server.wait_for_termination()
```

**Comment by drfloob** [comment]
The "new issue" form asks users not to post questions as Github issues. Please follow the instructions and use the channels mentioned below to ask questions. For reference, here is the default message that appears when you create a new issue:

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
