### ISSUE TITLE
Error When Returning Pointer to ClientReader"(prior > 0), function RefNonZero, file ref_counted.h"

### ISSUE THREAD

**Issue by brianzhang2101** [grpc/grpc#28550]
### What version of gRPC and what language are you using?
GRPC - v1.43.0 and C++

### What operating system (Linux, Windows,...) and version?
macOS Monterey v12.0.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
C++20
Apple clang version 13.0.0 (clang-1300.0.29.3)

### What did you do?
Inside my client file, I have a function to return a pointer with a response from the server.
```
std::unique_ptr<ClientReader<FlowCellPositionsResponse>> ManagerClient::flow_cell_positions() {
  ClientContext context;
  FlowCellPositionsRequest request; // Request here doesn't need any values
  return std::move(stub_->flow_cell_positions(&context, request)); // Also tried without std::move and same error
}
```
I created a seperate file to use this client function like so:

```
    FlowCellPositionsResponse response;
    std::unique_ptr<ClientReader<FlowCellPositionsResponse> > reader = manager->flow_cell_positions();
    while(reader->Read(&response)) { // Fails here
      std::cout << response.positions(0).name() << std::endl;
      std::cout << response.positions(0).rpc_ports().insecure() << std::endl;
    }
    Status status = reader->Finish();
    if(status.ok()) {
      std::cout << "Finished successfully!" << std::endl;
    } else {
      std::cout << "Failed " << status.error_code() << std::endl;
    }
```

### What did you expect to see?
The seperate file to print out the response's values. If I move this external logic back into the client file, it works fine, but creating this abstraction breaks it for some reason and I can't seem to get why.

### What did you see instead?
```
Assertion failed: (prior > 0), function RefNonZero, file ref_counted.h, line 119.
[1]    8785 abort      ./program
```

**Comment by drfloob** [comment]
Can you try building and running it under ASAN? My first instinct is to look for objects that have different lifetimes, such as maybe `stub_` here, or the helper function's local variables.

**Comment by drfloob** [comment]
Closing due to lack of response.
