### ISSUE TITLE
Review Beta API Docs in gh-pages branch

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#2855]
- Tracking issue to review Beta API docs.
- Provide any styling/css changes

Checklist
- [x] #2851 
- [ ] #2853 
- [ ] #2852 
- [ ] #2850 
- [ ] #2572 
- [ ] #2573

**Comment by soltanmm** [comment]
Is this meant to be a meta-issue tracking several other issues, or is it meant to be for the *review* of the finished work addressing the linked issues?

**Comment by hsaliak** [comment]
This is meant to review finished work. So The checklist is for the owner of the bug to tick after a review.

**Comment by stanley-cheung** [comment]
Can close this issue now?
