### ISSUE TITLE
tsan-reported race in connectivity state code

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2857]
WARNING: ThreadSanitizer: data race (pid=11978)
  Write of size 4 at 0x7d540000fe18 by main thread (mutexes: write M1425):
    #0 grpc_connectivity_state_set_with_scheduler /var/local/git/grpc/src/core/transport/connectivity_state.c:123 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000117646)
    #1 grpc_connectivity_state_set /var/local/git/grpc/src/core/transport/connectivity_state.c:146 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000001179fb)
    #2 cc_start_transport_op /var/local/git/grpc/src/core/channel/client_channel.c:573 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000125e7b)
    #3 grpc_channel_next_op /var/local/git/grpc/src/core/channel/channel_stack.c:201 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000001257e5)
    #4 grpc_channel_destroy /var/local/git/grpc/src/core/surface/channel.c:268 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000fac7b)
    #5 shutdown_client /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:89 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000cbc35)
    #6 end_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:95 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000cb6a5)
    #7 test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:181 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000cb2c0)
    #8 grpc_end2end_tests /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:190 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca79b)
    #9 main /var/local/git/grpc/test/core/end2end/fixtures/chttp2_fullstack_with_poll.c:112 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca4fc)

  Previous read of size 4 at 0x7d540000fe18 by thread T1:
    #0 grpc_connectivity_state_set_with_scheduler /var/local/git/grpc/src/core/transport/connectivity_state.c:119 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x00000011757c)
    #1 grpc_connectivity_state_set /var/local/git/grpc/src/core/transport/connectivity_state.c:146 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000001179fb)
    #2 cc_on_config_changed /var/local/git/grpc/src/core/channel/client_channel.c:507 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000127d05)
    #3 background_callback_executor /var/local/git/grpc/src/core/iomgr/iomgr.c:68 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000d53e8)
    #4 thread_body /var/local/git/grpc/src/core/support/thd_posix.c:57 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x00000018f472)

  Location is heap block of size 536 at 0x7d540000fc80 allocated by main thread:
    #0 malloc <null>:0 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000627fd)
    #1 gpr_malloc /var/local/git/grpc/src/core/support/alloc.c:40 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000182df0)
    #2 grpc_channel_create_from_filters /var/local/git/grpc/src/core/surface/channel.c:96 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000f8dbe)
    #3 grpc_insecure_channel_create /var/local/git/grpc/src/core/surface/channel_create.c:175 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000fb358)
    #4 chttp2_init_client_fullstack /var/local/git/grpc/test/core/end2end/fixtures/chttp2_fullstack_with_poll.c:75 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca06c)
    #5 begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:59 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000cb50b)
    #6 test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:109 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca8b2)
    #7 grpc_end2end_tests /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:190 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca79b)
    #8 main /var/local/git/grpc/test/core/end2end/fixtures/chttp2_fullstack_with_poll.c:112 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca4fc)

  Mutex M1425 (0x7d540000fdb8) created at:
    #0 pthread_mutex_init <null>:0 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000067920)
    #1 gpr_mu_init /var/local/git/grpc/src/core/support/sync_posix.c:44 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x00000018e60a)
    #2 init_channel_elem /var/local/git/grpc/src/core/channel/client_channel.c:658 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000126783)
    #3 grpc_channel_stack_init /var/local/git/grpc/src/core/channel/channel_stack.c:126 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000001248c5)
    #4 grpc_channel_create_from_filters /var/local/git/grpc/src/core/surface/channel.c:137 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000f97a5)
    #5 grpc_insecure_channel_create /var/local/git/grpc/src/core/surface/channel_create.c:175 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000fb358)
    #6 chttp2_init_client_fullstack /var/local/git/grpc/test/core/end2end/fixtures/chttp2_fullstack_with_poll.c:75 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca06c)
    #7 begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:59 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000cb50b)
    #8 test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:109 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca8b2)
    #9 grpc_end2end_tests /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:190 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca79b)
    #10 main /var/local/git/grpc/test/core/end2end/fixtures/chttp2_fullstack_with_poll.c:112 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca4fc)

  Thread T1 (tid=11980, running) created by main thread at:
    #0 pthread_create <null>:0 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x000000066511)
    #1 gpr_thd_new /var/local/git/grpc/src/core/support/thd_posix.c:76 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x00000018f2bc)
    #2 grpc_iomgr_init /var/local/git/grpc/src/core/iomgr/iomgr.c:99 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000d4fec)
    #3 grpc_init /var/local/git/grpc/src/core/surface/init.c:81 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ff16d)
    #4 main /var/local/git/grpc/test/core/end2end/fixtures/chttp2_fullstack_with_poll.c:109 (chttp2_fullstack_with_poll_cancel_after_invoke_unsecure_test+0x0000000ca492)

SUMMARY: ThreadSanitizer: data race /var/local/git/grpc/src/core/transport/connectivity_state.c:123 grpc_connectivity_state_set_with_scheduler

**Comment by ctiller** [comment]
Believe this is fixed.
