### ISSUE TITLE
I meet some troubles when build the tags/v1.3.2

### ISSUE THREAD

**Issue by causimmi** [grpc/grpc#28588]
> [GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/health/v1/health.proto
> *** Error in `/root/bf-sde-8.2.0/grpc_pkgs/grpc/bins/opt/grpc_cpp_plugin': corrupted double-linked list: 0x000000000129c260 ***
> --grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
> Makefile:2226: recipe for target '/root/file/grpc_pkgs/grpc/gens/src/proto/grpc/health/v1/health.grpc.pb.cc' failed
> make: *** [/root/file/grpc_pkgs/grpc/gens/src/proto/grpc/health/v1/health.grpc.pb.cc] Error 1

the protobuf is 3.2.0，and grpc is 1.3.2 I don’t know how to fix it

**Comment by causimmi** [comment]
I use the command as follows:
```
`git clone http://github.com/google/grpc.git
cd grpc
git checkout tags/v1.3.2
git submodule update --init --recursive
make`
```

**Comment by drfloob** [comment]
grpc v1.3.2 is five years old. Support is generally provided for the past 2 releases. Please upgrade to a more recent release if possible, v1.43 or v1.42.
