### ISSUE TITLE
gRPC Ruby build failed

### ISSUE THREAD

**Issue by Sapana-Khemkar** [grpc/grpc#28591]
### What version of gRPC and what language are you using?
gRPC version v1.42.0
Language Ruby

### What operating system (Linux, Windows,...) and version?
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [powerpc64le-linux]
Bundler version 2.3.5
gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)

### What did you do?
git clone https://github.com/grpc/grpc.git
cd grpc
git checkout v1.42.0
git submodule update --init
cd src/ruby
bundle install
rake

### What did you expect to see?
Build successful

### What did you see instead?
Build failed with following error. 
[rake_output.log](https://github.com/grpc/grpc/files/7880879/rake_output.log)

linking shared-object grpc/grpc_c.so
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:264: grpc_c.so] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/gmake...]
/usr/local/rvm/gems/ruby-2.7.2/gems/rake-compiler-1.1.7/lib/rake/extensiontask.rb:181:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.7.2/gems/rake-compiler-1.1.7/lib/rake/extensiontask.rb:180:in `block in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.7.2/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => default => all => suite:idiomatic => suite:wrapper => compile => compile:powerpc64le-linux => compile:grpc_c:powerpc64le-linux => copy:grpc_c:powerpc64le-linux:2.7.2 => tmp/powerpc64le-linux/grpc_c/2.7.2/grpc_c.so
(See full trace by running task with --trace)

### Anything else we should know about your project / environment?
Tried on x86 machine as well and observed same results.
[rake_output_x86.log](https://github.com/grpc/grpc/files/7880884/rake_output_x86.log)

**Comment by apolcyn** [comment]
Building from the github repo via rake explicitly is not officially supported, as this is only intended for internal testing and development.

Please install grpc via one of the gems hosted on ruby gems.

**Comment by Prikalel** [comment]
Help! I have the same issue building gitlab ce from source while compiling Gitaly!
