### ISSUE TITLE
csharp 2.43.0 clients get RST_STREAM error code 2 when talking to a 2.41.1 server

### ISSUE THREAD

**Issue by martinstenhoff** [grpc/grpc#28603]
When we upgraded some of our services to use Grpc.Core version 2.43.0 nuget package from 2.42.0 they can no longer talk to services using Grpc.Core version 2.41.1.

### What version of gRPC and what language are you using?
2.43.0 in client and 2.41.1 server both using C# 

### What operating system (Linux, Windows,...) and version?
Windows 10 (but we see the same issue in our kubernetes cluster using mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim containers)

### What runtime / compiler are you using (e.g. python version or version of gcc)
netcore3.1

### What did you do?
Sent a grpc message _CreateTodo_ from "client" to "server"

### What did you expect to see?
A successful response.

### What did you see instead?
Client throws a Grpc.Core.RpcException:
`Status(StatusCode="Internal", Detail="Received RST_STREAM with error code 2", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1642495764.149278091","description":"Error received from peer ipv4:172.2.194.253:5000","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}") `

With logging enabled in the server we see this (not sure if I've included enough):
```
[gateway-2]: I0118 17:24:06.145650 0 ..\..\..\src\core\lib\surface\call.cc:1574: ops[0]: RECV_INITIAL_METADATA ptr=0x26653431b48
[gateway-2]: I0118 17:24:06.145671 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:677: parsing initial_metadata
[gateway-2]: I0118 17:24:06.145714 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: :scheme: 68 74 74 70 'http'
[gateway-2]: I0118 17:24:06.145731 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: :method: 50 4f 53 54 'POST'
[gateway-2]: I0118 17:24:06.145774 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: :authority: [HEX REMOVED] 'gateway-SVC4.project-gateway:5002'
[gateway-2]: I0118 17:24:06.145794 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: :path: [HEX REMOVED] '/project.protobuf.gateway.GatewayGrpcService/CreateTodo'
[gateway-2]: I0118 17:24:06.145811 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: x-ope-trace-id: [HEX REMOVED] '|feb314b0-44a2b551ed2d9a9d.5.18032fcc_1.a7cc48d0_1.'
[gateway-2]: I0118 17:24:06.145821 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: x-ope-transaction-id: [HEX REMOVED] 'c49478fc-624f-4866-93e7-2960051b0bfa'
[gateway-2]: I0118 17:24:06.145830 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: x-ope-internal-transaction-id: [HEX REMOVED] '6e481269-4c9c-412a-9725-f8914de242d2'
[gateway-2]: I0118 17:24:06.145843 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: user-agent: [HEX REMOVED] 'grpc-csharp/2.43.0 (.NET Core 3.1.22; CLR 3.1.22; netstandard2.0; x64) grpc-c/21.0.0 (windows; chttp2)'
[gateway-2]: I0118 17:24:06.145858 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
[gateway-2]: I0118 17:24:06.145873 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: grpc-accept-encoding: 69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'
[gateway-2]: I0118 17:24:06.145889 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: accept-encoding: 69 64 65 6e 74 69 74 79 2c 67 7a 69 70 'identity,gzip'
[gateway-2]: I0118 17:24:06.145905 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: te: 74 72 61 69 6c 65 72 73 'trailers'
[gateway-2]: I0118 17:24:06.145922 0 ..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc:424: HTTP:1:HDR:SVR: user-agent: [HEX REMOVED] 'grpc-csharp/2.43.0 (.NET Core 3.1.22; CLR 3.1.22; netstandard2.0; x64) grpc-c/21.0.0 (windows; chttp2)'
[gateway-2]: I0118 17:24:06.145972 0 ..\..\..\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:808: W:0000026651C58EB0 SERVER [ipv4:127.0.0.1:4492] state IDLE -> WRITING [RST_STREAM]
...
[gateway-2]: I0118 17:24:06.246369 2638505067632 ..\..\..\src\core\lib\iomgr\timer_manager.cc:197: sleep until kicked
[gateway-2]: W0118 17:24:06.327535 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occurred in the handler or an interceptor. System.ArgumentException: Value does not fall within the expected range.
[gateway-2]: at Grpc.Core.Utils.GrpcPreconditions.CheckArgument(Boolean condition)
[gateway-2]: at Grpc.Core.Internal.UnaryServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq)
[gateway-2]: W0118 17:24:06.332086 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
[gateway-2]: at Grpc.Core.Utils.GrpcPreconditions.CheckState(Boolean condition)
[gateway-2]: at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
[gateway-2]: at Grpc.Core.Internal.UnaryServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq)
[gateway-2]: at Grpc.Core.Server.HandleCallAsync(ServerRpcNew newRpc, CompletionQueueSafeHandle cq, Action`2 continuation)
[gateway-2]: I0118 17:24:06.332254 0 ..\..\..\src\core\lib\surface\server.cc:1552: grpc_server_request_call(server=00000266525ED450, call=00000266523777D0, details=00000266523777D8, initial_metadata=0000026652377838, cq_bound_to_call=000002665222AFD0, cq_for_notification=000002665222AFD0, tag=00000266523777D0)
[gateway-2]: I0118 17:24:06.332393 0 ..\..\..\src\core\lib\surface\call_details.cc:37: grpc_call_details_destroy(details=00000266526FFCD8)
```

_Note: the server log above was not "captured" in the same run as the client exception above._

To have client and server successfully talk to each other we either have to downgrade the "client" back to 2.42.0 or upgrade the server to 2.43.0. 

Are we wrong in thinking that using 2.43.0 Grpc.Core on the client should work with server still on 2.41.1?

**Comment by yashykt** [comment]
It should still work. @jtattermusch PTAL

**Comment by jtattermusch** [comment]
Can you please provide a minimal reproduction, ideally in a form of a github repository with ready-to-run code? It would make it easier for us to reproduce the issue you're experiencing and debug it afterwards.

**Comment by jtattermusch** [comment]
Closing since we haven't heard back from the user.

FTR, it looks like the most interesting part of the log is `[gateway-2]: W0118 17:24:06.327535 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occurred in the handler or an interceptor. System.ArgumentException: Value does not fall within the expected range.`  which possibly comes from here:
https://github.com/grpc/grpc/blob/a3be0726054ee32042f6e25cfa2493d4655cb5ae/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L68

Are you sure that the request message is being correctly send to the unary server call handler?
If a unary server call handler is unable to read the expected single request message, it has no choice but to report and error and cancel the entire call (which is what the "Received RST_STREAM with error code 2" is about).
