### ISSUE TITLE
gRPC doc does not specify how to produce grpc++ library

### ISSUE THREAD

**Issue by konste** [grpc/grpc#28605]
### What version of gRPC and what language are you using?

1.43 C++

### What operating system (Linux, Windows,...) and version?

Windows, Linux

### What did you do?

[gRPC documentation](https://github.com/grpc/grpc/blob/master/BUILDING.md#building-with-bazel-recommended) claims that 
```
bazel build :all
```
builds everything, but from what I could see the library `grpc++`  is not produced.

### Anything else we should know about your project / environment?

I was able to track it down to `grpc_cc_library` in the root BUILD file does not specify any sources, which makes it header only library which does not have binary. 
gRPC related projects definitely use `grpc++` library, so it should be generated, but the doc does not give any clue how.

**Comment by yashykt** [comment]
I'm not sure I understand. What's your motive?
Did you try depending on the `grpc++` target and it didn't work?

**Comment by konste** [comment]
The project which uses gRPC is not built by Bazel and cannot directly depend on grpc++ target. I work on upgrading four years old version of gRPC used in that project with the new one. For that I need to generate new binary artifacts for all platforms, and it seems Bazel build produces everything but gRPC++ library.

**Comment by yashykt** [comment]
I wonder if CMake is a better match for your needs in that case since you are not using bazel.

**Comment by konste** [comment]
We may be forced to use CMake after all despite our desire to move towards Bazel.
But Bazel is the primary (recommended by the docs) build system for gRPC. Could somebody please shed some light on WHY Bazel build produces everything BUT grpc++ library?

**Comment by yashykt** [comment]
The bazel team might have a better answer here. https://github.com/bazelbuild/bazel/issues/1920 and https://github.com/bazelbuild/bazel/issues/492 offer some hacks that might work.

**Comment by yashykt** [comment]
Please re-open/create a new issue if there is some action that can be taken by grpc here.
