### ISSUE TITLE
[C#] Update Grpc.Core target from 4.5 to 4.6.2

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#28619]
Grpc.Core targets .NET Framework 4.5.

Visual Studio 2022 no longer supports developing net45 targets - https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers

net462 is the oldest .NET Framework target that is still supported - https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

Consider updating Grpc.Core (and all other packages and projects) to net462.

@jtattermusch

**Comment by jtattermusch** [comment]
Also here:
https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

**Comment by jtattermusch** [comment]
@jskeet  will the .NET client libraries drop support for all the targets prior net462 with the upcoming major version bump?

**Comment by jskeet** [comment]
@jtattermusch: That hasn't been decided for sure, but it seems reasonable to me. We'll need to check with some other internal users though.

**Comment by jtattermusch** [comment]
This has been done as part of https://github.com/grpc/grpc-dotnet/pull/1651.

Ad client libraries: future versions for client libraries (4.0+) will also target net462, so this shouldn't be a problem.
