### ISSUE TITLE
grpcio: Exception that happens during iterating requests is not properly communicated to users

### ISSUE THREAD

**Issue by heavelock** [grpc/grpc#28613]
This bug report is about grpcio.

### What version of gRPC and what language are you using?
1.43, python, grpcio 1.43.0 (also tested on 1.41 and 1.42)

### What operating system (Linux, Windows,...) and version?
OSx, 

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9

### What did you do?
A Streaming - Unary service requires an iterable to be passed to it. I pass to it a generator that validates input data and prepares a message. Validation fails and raises a TypeError.

### What did you expect to see?
I was expecting the TypeError to bubble up and fail the gRPC connection.  

### What did you see instead?
Instead of the expected exception, grpcio fails with completely uninformative exception:

```
  File “/Users/zpgh/Library/Caches/pypoetry/virtualenvs/sa-xr9n7SZP-py3.9/lib/python3.9/site-packages/grpc/_channel.py”, line 1131, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File “/Users/zpgh/Library/Caches/pypoetry/virtualenvs/sa-xr9n7SZP-py3.9/lib/python3.9/site-packages/grpc/_channel.py”, line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = “Exception iterating requests!”
        debug_error_string = “None”
```

### Summary

The error that is being raised currently is totally true because there was an exception during iterating requests. However the fact that the whole original stack trace was not showed made me waste quite a lot of time on debugging that issue.

**Comment by lidizheng** [comment]
This might be one of the issues complicated by multi-threading. The consumer of the iterator might not be on the same thread as the caller.

**Comment by lidizheng** [comment]
We will need a reproduce snippet to work on this issue, closing the issue for now. If there are more updates, feel free to reopen.
