### ISSUE TITLE
could the php gRPC extension can be smaller?

### ISSUE THREAD

**Issue by lanlin** [grpc/grpc#28621]
![image](https://user-images.githubusercontent.com/3468024/150275136-9133fef9-3c08-45a2-9fac-3b40f89851a6.png)

140.4Mb, it's a really big size for an extension, that makes Alpine a fatty, and my wallet cries...

**Comment by taka-oyama** [comment]
[Stripping it](https://linux.die.net/man/1/strip) will reduce the size to ~7MB.

**Comment by lanlin** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/3468024/162418228-bf70cfcf-08c9-41e7-a4f5-742414952e2c.png">
@taka-oyama it's pretty cool! thx

**Comment by Justin1210** [comment]
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/3468024/162418228-bf70cfcf-08c9-41e7-a4f5-742414952e2c.png">
> 
> @taka-oyama it's pretty cool! thx



> <img alt="image" width="550" src="https://user-images.githubusercontent.com/3468024/162418228-bf70cfcf-08c9-41e7-a4f5-742414952e2c.png">
> 
> @taka-oyama it's pretty cool! thx

What does the "Stripping it " mean? What should I do? guys,please show me more detail
