### ISSUE TITLE
Support pre-built binaries for Ruby 3.1

### ISSUE THREAD

**Issue by erikaxel** [grpc/grpc#28627]
### Is your feature request related to a problem? Please describe.
It seems grpc does not support pre-built binaries for Ruby 3.1. This causes the gem-folder to balloon to almost 1gb. Locally in development this is not a huge issue, but it causes issues for CI and for the images created for deployment.

### Describe the solution you'd like
Add pre-built binaries for Ruby 3.1

### Describe alternatives you've considered
N/A

### Additional context
Ruby 3.1 release note: https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

**Comment by cirdes** [comment]
This issue is preventing me to upgrade my Rails app to Ruby 3.1 on Heroku. My app compressed image went from 290.9M to more than 500M (heroku hard limit). After narrow down the problem I found grpc with more than 1gb.
`1018M	/app/vendor/bundle/ruby/3.1.0/gems/grpc-1.43.1`

In my case this is a relevant issue, I hope this could be fixed soon.

**Comment by simi** [comment]
:thinking: Could this be fixed by using this PR [in RubyGems](https://github.com/rubygems/rubygems/pull/4017)?

**Comment by Stex** [comment]
For me it's not the image sizes that become a problem, but rather the time it takes to actually build them. Even on my M1 Max Macbook Pro, it took over 10 minutes to actually install grpc's native extensions using the `ruby:3.1` image with 5 cores used.

On a shared gitlab.com runner in CI, the build went from 2 minutes to 20 minutes.

**Comment by vitalinfo** [comment]
@cirdes did you found any workarounds for this problem?

**Comment by cirdes** [comment]
@vitalinfo unfortunately not. I'm waiting for a fix. 😞

**Comment by ErikSchierboom** [comment]
We've run into the same issue. The huge size of the gem is also causing issues for us.

**Comment by bouk** [comment]
If you want to save some space (in our case it's like 800MB) you can run the following after installing the gem:

```shell
grpc_path="$(bundle show --paths grpc)/src/ruby/ext/grpc"
make -C $grpc_path clean
rm -rf "$grpc_path"/{libs,objs}
```

**Comment by vitalinfo** [comment]
version 1.45 increases our slug size even more (+43Mb) :(

**Comment by gsar** [comment]
running it the same issue as well, hoping this has the attention of the maintainers.

**Comment by whithajess** [comment]
This issue has us considering removing a google integration in our app because of the speed to build issue.

**Comment by cirdes** [comment]
The fix will be merged soon with https://github.com/grpc/grpc/pull/29000 . But it's the second major ruby releases that I have to wait months to upgrade because of grpc and every Google Cloud gem that I use depends on grpc. 
@whithajess , I'm wandering the same.

**Comment by apolcyn** [comment]
> Is this issue fixed? I also notice a huge slug increase in Heroku after adding this gem (1.53.0 on ruby 3.1.3). Do I have to do something manually to fix this?

Yes this was fixed. It's not clear what issue you're hitting, but you should be able to use a pre-compiled binary if you're running on a platform that supports them.

**Comment by ArthurWD** [comment]
> Yes this was fixed. It's not clear what issue you're hitting, but you should be able to use a pre-compiled binary if you're running on a platform that supports them.

Thanks for the reply! I guess I'm a bit naive, I just added the gem to the Gemfile and pushed it to Heroku. Installation now takes about 10 minutes extra and it increases the slug size a lot. Can I make it use the pre-compiled binary and skip the default installation? I only need it as a dependency of `google-analytics-data`

**Comment by chayuto** [comment]
having the same issue for heroku
