### ISSUE TITLE
service performance degradation and unexpected behavior after using SetMaxThreads

### ISSUE THREAD

**Issue by aluminumbox** [grpc/grpc#28646]
I am using grpc for bidirection streaming service. Beause this is an online real-time service, and we don't want our clients to wait too long, so we want to limit the rpcs to a certain number and reject the extra requests.

We are able to do it in Python with following code:

```
grpcServer = grpc.server(futures.ThreadPoolExecutor(max_workers=10), maximum_concurrent_rpcs=10)
```

In such case, only 10 requests will be processed, and other request will be rejected, the clients will throw a RESOURCE_EXHAUSTED error.

However, we find it hard to do it in C++. We use code following https://stackoverflow.com/questions/52311876/grpc-sync-server-limit-handle-thread
```
ServerBuilder builder;
builder.SetSyncServerOption(ServerBuilder::SyncServerOption::NUM_CQS, 10);
grpc::ResourceQuota quota;
quota.SetMaxThreads(10 * 2);
builder.SetResourceQuota(quota);
```

We are using grpc in many services. Some using kaldi, some using libtorch.
In some cases, the above code behaves normally, it processes 10 requests at a time, and rejects other requests. and the processing speed (our service requires a log of cpu calculation) is ok.
In some cases, it only accepts 9 request at a time.
In some cases, it accepts 10 request at a time, but the processing speed is significantly lower than before.

We also tried
```
builder.AddChannelArgument(GRPC_ARG_MAX_CONCURRENT_STREAMS, 10);
```
But it is useless becuase GRPC_ARG_MAX_CONCURRENT_STREAMS is the max_concurrent_rpcs on a single http connection.

Could someone please point out the equivalent C++ version of the Python code? We want to make our service to handle 10 requests at a time, and rejects other request, we do not want any service to wait in the queue.

**Comment by aluminumbox** [comment]
We have 4 speech related service. service A/B/C using kaldi( a speech recognition tool), service D using libtorch. service D suffers from performance degradation after SetMaxThreads. I doubt this maybe related to the multi-threading technique used in libtorch/MKL. Service A/B is okay after SetMaxThreads. But service C can only support 9 requests, which is exactly minus 1 (If I set NUM_CQS 20, and SetMaxThreads 40, it support 19 requests). What does SetMaxThreads limits? Does it take into account all the threads in grpc server, or it only considers the queues and processing thread?

**Comment by yashykt** [comment]
gRPC indeed does not have an out of the box option to limit the total number of concurrent requests. (Limiting the memory on ResourceQuota would give some control but not as fine grained a control as you want.)

Also note that at present, we do not recommend the sync API for performance. In your case, I would highly recommend using the async API and then the application code itself could be responsible for managing how to handle any extra requests. 

SetMaxThreads on the ResourceQuota would limit the total number of threads allocated from the resource quota. If you really want to use the sync server to do this this, it sounds like you instead want to adjust the minimum and maximum number of pollers. https://github.com/grpc/grpc/blob/7b8fb43b33892b786f1cb8d8d5a086973169c9ac/include/grpcpp/server_builder.h#L229
