### ISSUE TITLE
Help!  why? Client( InsecureChannelCredentials ) can connect server(SslServerCredentials)

### ISSUE THREAD

**Issue by HeatWyf** [grpc/grpc#28724]
the server uses the right root cert.
the client create channel using InsecureChannelCredentials.
why can client receive message from server?

**What version of gRPC and what language are you using?**
grpc 1.41

**What operating system (Linux, Windows,...) and version?**
windows vs2019

server code:
`std::string server_address ( "0.0.0.0:50051" );

    std::string key;
    std::string cert;
    std::string root;

    read ( "E:\\DataCert\\server1.pem", cert );
    read ( "E:\\DataCert\\server1.key", key );
    read ( "E:\\DataCert\\ca.pem", root );

     grpc::SslServerCredentialsOptions::PemKeyCertPair keycert = { key, cert };
 	grpc::SslServerCredentialsOptions sslOps(GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY);
     sslOps.force_client_auth = true;
     sslOps.pem_root_certs = root;
     sslOps.pem_key_cert_pairs.push_back ( keycert );
     std::shared_ptr<grpc::ServerCredentials> creds = grpc::SslServerCredentials(sslOps);

	ServerBuilder builder;
	builder.AddListeningPort(server_address, creds);

    GreeterServiceImpl service;
    builder.RegisterService(&service);

    std::unique_ptr < Server > server ( builder.BuildAndStart () );
    std::cout << "Server listening on " << server_address << std::endl;

    server->Wait ();`

client code:
`std::string server{ "192.168.20.182:50051" };
//	std::unique_ptr<Greeter::Stub> stub_ = Greeter::NewStub(grpc::CreateChannel(server, grpc::SslCredentials(opts)));
    std::unique_ptr<Greeter::Stub> stub_ = Greeter::NewStub(grpc::CreateChannel(server, grpc::InsecureChannelCredentials()));

    std::string user ( "world" );
	HelloRequest request;
	request.set_name(user);
	HelloReply reply;
	ClientContext context;
	Status status = stub_->SayHello(&context, request, &reply);

	if (status.ok())
	{
		std::cout << "Greeter received: " << reply.message() << std::endl;
	}
	else
	{
		std::cout << status.error_code() << ": "
			<< status.error_message() << std::endl;
	}`

result:
client "SayHello"  return status.ok().

**Comment by luisteran1** [comment]
Was this issue resolved? Running into the same issue as well!
