### ISSUE TITLE
ZTS PECL builds for Windows are failing

### ISSUE THREAD

**Issue by cmb69** [grpc/grpc#28756]
### What version of gRPC and what language are you using?

gRPC 1.44.0RC2, PHP extension

### What operating system (Linux, Windows,...) and version?

Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC (Visual Studio)

### What did you do?

I tried to build the ZTS Windows DLLs for grpc-1.44.0RC2.tgz on the PECL build machine.

### What did you expect to see?

The builds succeed.

### What did you see instead?

The ZTS builds failed:
````
C:\php-snap-build\obj\8.0-ts-windows-vs16-x64\Release_TS\resp\GRPC_GLOBAL_OBJS.txt : fatal error LNK1170: line in command file contains 131071 or more characters
````

I cannot (easily) reproduce this locally, but in this environment the linker response file is 128.651 bytes large, and the PECL build machine uses a longer base path. The NTS builds work, because these are build in a subfolder `Release`, whereas ZTS builds use `Release_TS`. Apparently, there is no maximum length of the [response file documented](https://docs.microsoft.com/en-us/cpp/build/reference/at-specify-a-linker-response-file?view=msvc-170), but I assume this is a hard limit that won't change anytime soon. And even if it might be possible to adapt the build environment, it's probably only a matter of time until this issue comes up again – there are just so many obj files to link. I checked the bundled php-src extensions, and the largest response file is only 9.185 bytes here.

Maybe you want to consider to build intermediate libraries instead of linking all object files directly. I'm afraid that there is no direct support for that with the current PHP build system, though. :(

PS: [latest build log files](https://windows.php.net/downloads/pecl/releases/grpc/1.44.0rc2/logs/)

**Comment by Jan-E** [comment]
@cmb69 Hi Christoph, if you ever manage to get the PECL build machine up again, compiling for PHP 8.0 - 8.3 works now. See https://github.com/grpc/grpc/issues/33402#issuecomment-1600244618
