### ISSUE TITLE
[Question] client side load balancing in grpc python

### ISSUE THREAD

**Issue by animesh-sharama** [grpc/grpc#28761]
I was trying to implement client side load balancing in gRPC.
I know how to do it in Java but not able to find appropriate document describing how to do the same in python, below is my Java code.

```
NameResolver.Factory nameResolverFactory = new MultiAddressNameResolverFactory(
            new InetSocketAddress("localhost", 10000),
            new InetSocketAddress("localhost", 10001),
            new InetSocketAddress("localhost", 10002)
    );

ManagedChannel channel = ManagedChannelBuilder.forTarget("service")
            .nameResolverFactory(nameResolverFactory)
            .defaultLoadBalancingPolicy("round_robin")
            .usePlaintext()
            .build();
```

In python I know how to connect to one server but not a list of gRPC servers
```
channel = grpc.insecure_channel('localhost:10000')
```
can anyone kindly guide me or point me to a document on how to implement the same?

stackoverflow que - https://stackoverflow.com/questions/70878942/client-side-load-balancing-in-grpc-python
grpc-io fourm - https://groups.google.com/g/grpc-io/c/ht2N3gpz6OQ/m/UDyrLyFdEgAJ

**Comment by donnadionne** [comment]
For the future, please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion
 
Your answer may already be there or you can post a new question if it is not.
