### ISSUE TITLE
Best practice for using ClientReadReactor class

### ISSUE THREAD

**Issue by proga7med** [grpc/grpc#28772]
What's the best way to use ClientReadReactor class ?

I saw that I should create a child class which is inherited from  ClientReadReactor  class. But I have to store client context, request and I don't think that is the best way.

**Comment by donnadionne** [comment]
For the future, please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion
 
Your answer may already be there or you can post a new question if it is not.
