### ISSUE TITLE
gRPC stopped working with APO on Windows 11

### ISSUE THREAD

**Issue by d-zhukov** [grpc/grpc#28782]
I have a Windows application (APP) and Audio Processing Object (APO) loaded by AudioDG.exe that communicate via gRPC:
1. APP part that is written in C# creates server via Grpc.Core (2.43.0).
2. APO part creates client via grpc++ (1.41.0).
3. Server is on 127.0.0.1:20000 (I can see it's up and listening with "netstat -ano").
4. I can confirm that APO is loaded into audio device graph by inspecting it with process explorer.

Everything worked like a charm on Windows 8 and 10, but on 11 it cannot communicate at all - I get either "Error Code 14, Unavailable, failed to connect to all addresses" or "4, Deadline Exceeded".

What I've tried so far:
- Updating both parts to the latest grpc versions.
- Enabling trace to all and verbosity to debug.
- Using "no proxy", "Http2UnencryptedSupport" and other env variables that are advised on countless SO / dev forums posts.
- Using "localhost" or "0.0.0.0" instead of "127.0.0.1".
- Updating connection to use self signed SSL certificates (root CA, server cert + key, client cert + key).
- Adding inbound / outbound rules for my port, and then disabling firewall completely.
- Creating server on APO side and trying to connect with the client in APP.

Everything works (both insecure and SSL creds) if I create both client and server in C# part, but as soon as it's APP-APO communication it feels blocked or sandboxed.

What has been changed in Windows 11 that can "block" gRPC?

Thanks in advance!

P.S. I'm on Windows 11 Home (21H2).

**Comment by jtattermusch** [comment]
I'd enable extra tracing (e.g. GRPC_TRACE=tcp) and extra debug logging. 

How to get extra debug logs & traces:
https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by d-zhukov** [comment]
Hi @jtattermusch , thanks for your reply!

Troubleshooting doc says:
> Known limitations: GPRC_TRACE=tcp is currently not implemented for Windows (you won't see any tcp traces).

But added "tcp" anyway and FWIW when I try to connect from grpc.core client (APP) to grpc++ server (APO) I see this "socket is null" error:
```
I0207 16:20:59.916447 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:950: subchannel 000001D8B9B01E20 {address=ipv4:127.0.0.1:10000, args=grpc.client_channel_factory=0x1d8bb660460, grpc.default_authority=127.0.0.1:10000, grpc.internal.subchannel_pool=0x1d8b8c291b0, grpc.primary_user_agent=grpc-csharp/2.43.0 (.NET Framework 4.8.4470.0; CLR 4.0.30319.42000; net45; x64), grpc.resource_quota=0x1d8b8c28d90, grpc.server_uri=dns:///127.0.0.1:10000}: connect failed: {"created":"@1644240059.916000000","description":"socket is null","file":"..\..\..\src\core\lib\iomgr\tcp_client_windows.cc","file_line":112}
I0207 16:20:59.916447 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:889: subchannel 000001D8B9B01E20 {address=ipv4:127.0.0.1:10000, args=grpc.client_channel_factory=0x1d8bb660460, grpc.default_authority=127.0.0.1:10000, grpc.internal.subchannel_pool=0x1d8b8c291b0, grpc.primary_user_agent=grpc-csharp/2.43.0 (.NET Framework 4.8.4470.0; CLR 4.0.30319.42000; net45; x64), grpc.resource_quota=0x1d8b8c28d90, grpc.server_uri=dns:///127.0.0.1:10000}: Retry immediately
I0207 16:20:59.916447 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:915: subchannel 000001D8B9B01E20 {address=ipv4:127.0.0.1:10000, args=grpc.client_channel_factory=0x1d8bb660460, grpc.default_authority=127.0.0.1:10000, grpc.internal.subchannel_pool=0x1d8b8c291b0, grpc.primary_user_agent=grpc-csharp/2.43.0 (.NET Framework 4.8.4470.0; CLR 4.0.30319.42000; net45; x64), grpc.resource_quota=0x1d8b8c28d90, grpc.server_uri=dns:///127.0.0.1:10000}: failed to connect to channel, retrying
```

Not sure how to get debug logs from C++ part cause it's loaded by audio device graph (APO dll).
Maybe I could attach custom file logger to it?

**Comment by d-zhukov** [comment]
Turned out that gRPC is not related in any way - same thing with named pipes.
What's interesting is that even though netstat shows both ports as LISTENING, the one at APO level is actually FILTERED - realized that when switched to old-but-gold Port Query tool. 

So, Windows Firewall is blocking the port, but neither disabling it in Win settings, nor adding inbound / outbound rules helped in my case. I've also tried to add my app and even AudioDG.exe (that loads our DLL) as an exception for the firewall - no luck.

Communication works just fine if I disable Firewall the hard way, through the registry key. And again, everything is fine on 8 and 10, the problem only shows up on 11, which seems to be related to tightened security for audio graph. Not sure what could help me "fix" this new behavior. Thanks for looking into this anyway! Appreciated.

P.S. What's the best way to get answer on such a corner case question?
My background is mostly macOS and iOS apps, so I'm not sure where to ask :)

**Comment by AndreiHarasemiuc** [comment]
@d-zhukov How did you end up solving this?
I'm in the same situation, I need to communicate fast between a Win32 app and my APO.

**Comment by d-zhukov** [comment]
@AndreiHarasemiuc it turned out that ports were being blocked by Windows Service Hardening (WSH).
I had to make a script to add special rules regarding needed ports for APO communication to work.
Example:
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ics/adding-a-service-exception

**Comment by AndreiHarasemiuc** [comment]
@d-zhukov Thanks your replying, I appreciate it!
I'm not sure such a script would be viable for me as we're trying to ship an actual product. 
Have you investigated other means of communication between your app and the APO? I'm trying named pipes now but I'm getting some access denied errors, perhaps because of the same issue. Too early to tell, I haven't yet fiddled with it enough.

In our particular scenario we also have a driver (it's a virtual driver, no hardware) that the APO is attached to.

**Comment by d-zhukov** [comment]
@AndreiHarasemiuc we ship actual product too :)
VBScript that "fixes" WSH rules for Win 11 is a part of our MSI and runs during installation process.
I also added another script that removes these rules as a part of uninstallation process.

> Have you investigated other means of communication between your app and the APO?
I use named pipes as a way to communicate between executables (we have several), but not to talk to APO.

**Comment by ss1969** [comment]
@d-zhukov The information I've found indicates that Windows Service Hardening is not part of Windows Firewall. Could you please share specific VBScript examples for setting exceptions within the context of Windows Service Hardening? We're encountering the same issue here as well.

**Comment by d-zhukov** [comment]
Hi @ss1969, my employer wouldn't let me post the exact script I made, but general idea for APO interaction is something like this:
```
 ' Add inbound WSH allow rule
 Dim NewInboundRule
 Set NewInboundRule = CreateObject("HNetCfg.FWRule")
 NewInboundRule.Name = "_YOUR_RULE_NAME_"
 NewInboundRule.ApplicationName = "%systemDrive%\WINDOWS\system32\audiodg.exe"
 NewInboundRule.ServiceName = "AudioSrv"
 NewInboundRule.Protocol = NET_FW_IP_PROTOCOL_TCP
 NewInboundRule.LocalPorts = _PORT_YOU_NEED_TO_OPEN_
 NewInboundRule.Action = NET_FW_ACTION_ALLOW
 NewInboundRule.Direction = NET_FW_RULE_DIR_IN
 NewInboundRule.Enabled = true

 Dim returnVal1
 returnVal1 = wshRules.Add(NewInboundRule)
```

**Comment by ss1969** [comment]
@d-zhukov That's very helpful! Thanks in advance.
