### ISSUE TITLE
python grpcio is installed but grpc can't not be imported

### ISSUE THREAD

**Issue by MeowSaiGithub** [grpc/grpc#28798]
I have already reinstall grpcio

**Comment by MeowSaiGithub** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/67623033/152664279-da74bce1-44fc-4fbb-9bb6-7beb92b22408.png)
pip freeze screen shot, grpc is missing so I cannot use it in python code

**Comment by MeowSaiGithub** [comment]
grpc is missing import but the script still run

**Comment by AshfaqWanclouds** [comment]
same issue with me

**Comment by AshfaqWanclouds** [comment]
i have installed the grpcio==1.30.0 and grpcio-tools==1.30.0 in docker environment for python (3.7, 3.9) 
grpcio and grpcio-tools  installed in the docker environment but now in my file it is throwing the error that No Module name grpc

**Comment by lidizheng** [comment]
@AshfaqWanclouds can you try if our latest release still have the problem on your environment? Also, please open a separate issue, the cause might not be the same.
