### ISSUE TITLE
Remove (experimental) PUT support

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#28792]
At least one user used PUT without realizing it is an incomplete experiment, much more so than other experimental APIs. https://github.com/grpc/grpc-go/issues/2881#issuecomment-1030038253 (and b/217892555). That caused compatibility issues when Go improved its implementation to verify the HTTP method is POST.

I believe I heard @yashykt recently removed the GET support in C (but I failed to find the PR quickly; "get" is hard to search for). Yes, PUT probably has very low maintenance burden, but grpc dev interest in PUT is lower than that of GET, so at this point it seems best to remove the API. If we don't want to do that, I guess we can put a "DO NOT USE" message in the docs.

CC @markdroth, @bdhess, @dfawley

**Comment by yashykt** [comment]
The last I looked at it, we decided not to remove GET/PUT support, but @ctiller just put out https://github.com/grpc/grpc/pull/28922

**Comment by ejona86** [comment]
@yashykt, if GET is still present, how was the HTTP method handled for RBAC?

**Comment by yashykt** [comment]
> @yashykt, if GET is still present, how was the HTTP method handled for RBAC?

It was handled similar to other metadata types. (The method metadata was already available to the rbac filter implementation)
