### ISSUE TITLE
Add a channel option that disables retrying connections

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#288]
Some test failures in Node result in a channel repeatedly attempting to connect to a server after all of the tests have finished running, and even after `SIGINT` has been sent to the process. It would be useful to disable this behavior for tests.

**Comment by vjpai** [comment]
Still relevant?

**Comment by murgatroid99** [comment]
I don't think so. This sort of think shows up as a timeout failure now, which seems good enough to me.
