### ISSUE TITLE
AuthContext properties are not reset on subsequent calls

### ISSUE THREAD

**Issue by Thalhammer** [grpc/grpc#28809]
### What version of gRPC and what language are you using?
1.43.2

### What operating system (Linux, Windows,...) and version?
Linux 5.4.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
C++, Clang12

### What did you do?
* Create a AuthMetadataProcessor
* Use ctx->AddProperty to store information extracted from headers
* Invoke multple requests using the same connection.

### What did you expect to see?
Each invocation of AuthMetadataProcessor::Process starts with a new, clean AuthContext that contains nothing except information about the transport.

### What did you see instead?
If the connection is reused it contains the information of the previous request.

### Anything else we should know about your project / environment?
I am using insecure server credentials via ipv4, but `SslServerCredentials` behaves the same.

**Comment by ZhenLian** [comment]
It seems the behavior is expected. The `auth_context` is per-channel, and `AuthMetadataProcessor::Process` calls per-rpc. For a particular channel, we can have multiple rpc requests. When you update the information in one rpc, it's likely you will see the change in another rpc process request.
What are you trying to do with  `AuthMetadataProcessor`? If you want to build a server authorization service, we now offer a way to build it through some file-based policies(). @yihuazhang @ashithasantosh to provide more info.

**Comment by Thalhammer** [comment]
> It seems the behavior is expected. The auth_context is per-channel, and AuthMetadataProcessor::Process calls per-rpc.

It is expected if you know the implementation but most people using the public api of grpc don't (and I didn't either before I started digging to figure out what the heck is going on). However if you only read the (very spare) documentation on it (https://github.com/grpc/grpc/blob/master/doc/server_side_auth.md), it (at least in my understanding) kindof implies that auth context is a per call thing.

> To perform server-side authentication, gRPC exposes the authentication context for each call.

> Auth interceptors are gRPC components that populate contents of the auth context based on gRPC's internal state and/or call metadata.

It never explicitly says it is per call, but it also never says that its per channel either. 

> If you want to build a server authorization service, we now offer a way to build it through some file-based policies().

Thats pretty much exactly what I want to do (ratelimit based on ip, jwt auth and ratelimit based on user, using the info from the jwt) and I indeed did not know about the file base policies, but based on the [test cases](https://github.com/grpc/grpc/blob/master/test/core/end2end/tests/sdk_authz.cc) which seem to be the only form of documentation it doesn't seem to do what I want.

In my opinion the Process method should have access to the transport information (e.g. cert info), but properties added should only reflect for the currently authorized call, which would be possible by creating a new auth context for each call that chains the original. Ideally it would have the ability to access both separately but I don't know how to do that without breaking the abi and probably most code.

**Comment by ZhenLian** [comment]
I revisited the API and I agreed that the comment can be improved. I will make a pull request to update the API comment and clarify a few points.
The `context` is per-connection instead of per-call, so shouldn't be modified in `AuthMetadataProcessor` in general cases. I will make that clear in the document.

**Comment by ZhenLian** [comment]
Please see the updated documentation in https://github.com/grpc/grpc/pull/28985. I will close this issue; let's continue our discussion in that PR. Thanks!
