### ISSUE TITLE
AuthMetadataProcessor response_metadata is non-functional

### ISSUE THREAD

**Issue by Thalhammer** [grpc/grpc#28810]
### Is your feature request related to a problem? Please describe.
I attempted to use AuthMetadataProcessor for jwt auth and rate limiting, however the header data added to response_metadata never ends up in the response. Running with debug logs prints that its not supported for now, but this is not noted anywhere in the documentation.

### Describe the solution you'd like
Implement support for response_metadata or at least make clear that it's not supported.

### Describe alternatives you've considered
I am currently storing the headers (prefixed) in AuthContext, but this is broken as well because of #28809 .
The only working solution I can think of right now is keeping a global map indexed by something that stays constant during the call.

### Additional context
AuthMetadataProcessor is considered stable, but has major bugs (this & #28809) and short comings (#28807), which makes me seriously wonder if I am maybe just using it wrong.

**Comment by ZhenLian** [comment]
`Running with debug logs prints that its not supported for now
`

Can I please take a look at the logs?

BTW, I am not sure if you've seen it already, but https://github.com/grpc/grpc/blob/master/test/cpp/end2end/end2end_test.cc#L1747-L1770 is an example on how to implement your own MetadataPlugin and start your call credential authentication. It might be helpful if you want to build your own JWT authentication.

**Comment by Thalhammer** [comment]
> Can I please take a look at the logs?

```
D0210 12:33:26.148489405    7556 ev_posix.cc:172]            Using polling engine: epollex
D0210 12:33:26.148999411    7556 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0210 12:33:26.149418488    7556 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0210 12:33:26.149436728    7556 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0210 12:33:26.149447938    7556 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0210 12:33:26.149459168    7556 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0210 12:33:26.149470118    7556 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D0210 12:33:26.149487027    7556 dns_resolver_ares.cc:495]   Using ares dns resolver
D0210 12:33:26.150006683    7556 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0210 12:33:26.150023313    7556 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0210 12:33:26.150035633    7556 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0210 12:33:26.150046963    7556 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0210 12:33:26.150058603    7556 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
I0210 12:33:26.150192042    7556 server_builder.cc:327]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0210 12:33:26.163206200    7556 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I0210 12:33:29.081174200    7561 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
I0210 12:33:29.081806815    7561 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
I0210 12:33:29.082399420    7576 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
I0210 12:33:29.082950046    7561 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
I0210 12:33:29.083541491    7576 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
I0210 12:33:29.084118727    7561 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
I0210 12:33:29.084659372    7576 server_auth_filter.cc:142]  response_md in auth metadata processing not supported for now. Ignoring...
```

The relevant line is the last one which is printed once for each request after AuthMetadataProcessor returns.  The place where it is printed is here: https://github.com/grpc/grpc/blob/17c6a486cd2d71716bb7eb071d6e67160ae370cf/src/core/lib/security/transport/server_auth_filter.cc#L148
Which is the callback invoked with the results from `AuthMetadataProcessor::Process()`.

I've seen that example and don't get me wrong: AuthMetadataProcessor works just fine for **very basic** authentication, like decoding a jwt and saying YES/NO. But as soon as you want to do anything slightly more advanced it doesn't work as expected (at least not the way I expected it). Theres no real way to pass any information from it to Interceptors or the function. 
What I in my specific case wanted to do is to parse the jwt in the auth processor, reject the call completely if the jwt is invalid or doesn't have a scope coresponding to the method and then forward the information within (claims like the user, etc..) using the auth_context to the call itself (See #28809). Another example (which is more relevant to this exact problem is rate limiting, in which case I wanted to put information about the remaining quota (used, total, time till reset) in the response metadata to give the client some information about how to pace requests and/or when to retry. My alternative solution whould have been to attach said information to the authcontext, and copy it to the headers in an interceptor, but that aint working either cause the authcontext is peer channel.

**Comment by ZhenLian** [comment]
Yeah, that seems to be a TODO we never got a chance to fix. I will make that in the document clear as well, and take that ToDO.

**Comment by ZhenLian** [comment]
Please see the updated documentation in https://github.com/grpc/grpc/pull/28985. I will close this issue; let's continue our discussion in that PR. Thanks!
