### ISSUE TITLE
Missing class ChannelCredentials for grpc in the PHP library

### ISSUE THREAD

**Issue by DennisBecker** [grpc/grpc#28811]
Missing class ChannelCredentials for grpc 

### What version of gRPC and what language are you using?
PHP v1.42.0

### What operating system (Linux, Windows,...) and version?
Linux, Debian buster

### What runtime / compiler are you using (e.g. python version or version of gcc)
unknown

### What did you do?
I have build a client an tried an easy request and tried a test rqeuest

### What did you expect to see?
A regular response or error.

### What did you see instead?
```
Uncaught Error: Class 'Grpc\ChannelCredentials' not found in vendor/grpc/grpc/src/lib/BaseStub.php:51

Stack trace:
#0 /home/becker/..../Client.php(6): Grpc\BaseStub->__construct('', Array, NULL)
#1 home/becker/..../Controller.php(28): Client->__construct('', Array)
 in /home/becker/.../vendor/grpc/grpc/src/lib/BaseStub.php on line 51
```

### Anything else we should know about your project / environment?
protobuf-compile is installed, installed https://github.com/protobuf-php/protobuf-plugin for easy compilation of proto files,
using an old project which dates before composer but integrated the composer autoloader

**Comment by stanley-cheung** [comment]
You also need to install the `grpc` pecl extension.

**Comment by DennisBecker** [comment]
Why is the dependency suggested and not required? I thought I could choose between the C extension and the PHP implementation of google/protobuf PHP package.

**Comment by stanley-cheung** [comment]
Yes you can choose the C extension vs the PHP package of `protobuf`. But `grpc` is a separate extension.

**Comment by NeuronSK** [comment]
I have the same problem, and have already installed both the grpc and protobuf extensions (and confirmed they are loaded correctly via phpinfo())

How can I fix this?

**Comment by stanley-cheung** [comment]
@NeuronSK What's the error you are seeing?

**Comment by NeuronSK** [comment]
> @NeuronSK What's the error you are seeing?

Was the same as OP, but turns out it was an artifact of how I was handling autoloading.

I refactored to use PSR 4 autoloading and no longer encounter the error.
