### ISSUE TITLE
C Jwt Access Credentials should cache JWTs

### ISSUE THREAD

**Issue by anthmgoogle** [grpc/grpc#2881]
The JWT Access Credentials should temporarily cache JWTs. Suggested algorithm:
- Hash JWTs using Audience as key.
- Also store the timestamp of last use with each JWT.
- On access clear any JWT unused for more than 1 hour.

**Comment by jboeuf** [comment]
I think that we will still need this at some point... It's fine to close for now (bug bankruptcy) but we will probably reopen that in the future.

**Comment by jtattermusch** [comment]
Yes, this is very important for performance when accessing google APIs. Also, C++ AFAIK doesn't support OAuth flow with token server, so JWT is the only way to authenticate with google APIs.

I vote for reopening (and addressing this).

**Comment by jboeuf** [comment]
OK, let's reopen that. I'll put that in my team's objectives for Q1.

**Comment by hsaliak** [comment]
Can we track this then in the 1.1 milestone. Re-opening a bankrupt issue without a clear timeline is not encouraging :)

**Comment by hsaliak** [comment]
@jboeuf any progress on this one? :)

**Comment by jboeuf** [comment]
No unfortunately. I talked to @yihuazhang about it back in Q1/Q2 but he got busy with other things. We'll discuss that and get back to you.
