### ISSUE TITLE
error: absl/synchronization/mutex.h: No such file or directory  #include "absl/synchronization/mutex.h"   

### ISSUE THREAD

**Issue by chenwenjing1988** [grpc/grpc#28823]
### What version of gRPC and what language are you using?
1.43.0 -- qt

### What operating system (Linux, Windows,...) and version?
linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
![image](https://user-images.githubusercontent.com/5673912/153163188-70909a47-e868-4205-a1ff-633ce50936db.png)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by chenwenjing1988** [comment]
I put the include the source code into a project, prompt absl/synchronization/mutex. H: No to the file or directory, I introduce the GRPC qt project

**Comment by yashykt** [comment]
It isn't clear what you are trying to do here. Please take a look at https://github.com/grpc/grpc/blob/master/src/cpp/README.md for building instructions.
