### ISSUE TITLE
Adding lz4 compression algorithm?

### ISSUE THREAD

**Issue by elftech** [grpc/grpc#28836]
### Is your feature request related to a problem? Please describe.
I use grpc compression to decrease grpc request and response body size to save the transmission cost during network. Now only gzip and deflate compression algorithms are supported.  

### Describe the solution you'd like
Add lz4 compression algorithm to the options, which has showed much more high performance compared to current algorithms. There're lots benchmark showing lz4 performance advantages.

### Describe alternatives you've considered
No alternative ideas.

### Additional context
I have succeed to add lz4 compression to my local grpc repository.  However, hope for official support from your team！

**Comment by zkkxu** [comment]
ANY PROGRESS ABOUT LZ4 SUPPORT?

**Comment by zkkxu** [comment]
@markdroth  can you assgin this feature to me? I have already implement lz4 compression for grpc

**Comment by veblush** [comment]
Closing in favor of https://github.com/grpc/grpc/issues/29767.
