### ISSUE TITLE
python3 setup.py install failed

### ISSUE THREAD

**Issue by hanzhichao** [grpc/grpc#28832]
### What version of gRPC and what language are you using?
tried master branch current and v1.42

### What operating system (Linux, Windows,...) and version?
tried MacOS Montery v12.1 Inter  and CentOS x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)

- Python3.8.4 on MacOS Montery + Apple clang version 13.0.0 
- Centos + gcc (GCC) 11.1.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

try both on MacOS Montery and CentOS 
```sh
git clone https://github.com/hanzhichao/grpc.git
cd grpc
python3 setup.py install
```
> MacOS Montery and CentOS xcode-commandline is installed . 
> CentOS python36-devel is installed by yum

### What did you expect to see?
successfully build complete

### What did you see instead?
In MacOS it seem stacked when build **clang ... /tmp/tmpmq13qzt4/a.c -o None/tmp/tmpmq13qzt4/a.o**
```sh
...
creating None/tmp/tmpmq13qzt4
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c /tmp/tmpmq13qzt4/a.c -o None/tmp/tmpmq13qzt4/a.o

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/unixccompiler.py", line 118, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/Users/superhin/CLionProjects/grpc/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1
...
```
In CentOS it stacked the same step **gcc ... /tmp/tmpivcaghgg/a.c -o None/tmp/tmpivcaghgg/a.o**

```sh
creating None/tmp/tmpivcaghgg
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmpivcaghgg/a.c -o None/tmp/tmpivcaghgg/a.o

```

Make sure you include infor
[python3_setup_install_fail_on_CentOS.txt](https://github.com/grpc/grpc/files/8039606/python3_setup_install_fail_on_CentOS.txt)
mation that can help us debug (full error message, exception listing, stack trace,
[python3_steup_install_fail_on_MacOS.txt](https://github.com/grpc/grpc/files/8039612/python3_steup_install_fail_on_MacOS.txt)
 logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by hanzhichao** [comment]
@lidizheng Appreciate for your replay. After update submodule, It works on CentOS.
Well on  MacOS Montery + Apple clang version 13.0.0, it failed the same place while **clang ... /tmp/../a.c -o None/tmp/.../a.o**

Refer to the bazel test result stdout output and the python3 setup.py install output for details

[bazel_test_result.txt](https://github.com/grpc/grpc/files/8045885/bazel_test_result.txt)
[python_setup_install_failed.txt](https://github.com/grpc/grpc/files/8045886/python_setup_install_failed.txt)

**Comment by lidizheng** [comment]
Bazel seems to be passing, if you take a look at the error log, it might contain why the tests are failing. Probably, due to no Python2 installation.

For the Python setup, I didn't find the failing line in your attachment. I wouldn't recommend to compile from source, if acceptable, you can use `arch -x86_64 /bin/bash` to simulate x64 arch and use gRPC Python binary wheel normally.

**Comment by j05070415** [comment]
谢谢，您的邮件我已收到！
