### ISSUE TITLE
cannot find -lgrpc and -lgpr

### ISSUE THREAD

**Issue by zhenghub** [grpc/grpc#2884]
I did as https://github.com/grpc/grpc/tree/master/src/python/README.md:
 1. $ make shared_c static_c
 2. $ tools/run_tests/build_python.sh

Then I meet two problems during the 2nd step:
> /usr/bin/ld: cannot find -lgrpc
/usr/bin/ld: cannot find -lgpr

I copied libgpr.so libgpr.so.0 libgrpc.so libgrpc.so.0 libgrpc_unsecure.so and libgrpc_unsecure.so.0 under libs/opt which may be generated by step 1 to /usr/libs to fix this problem. But soon I meet another problem when testing:
* $ tools/run_tests/run_python.sh

13 errors reported "/usr/lib/libgrpc.so.0: undefined symbol: GENERAL_NAME_free":
> ___________________________________________________________________________________________________________ ERROR collecting grpc_interop/_insecure_interop_test.py ___________________________________________________________________________________________________________
grpc_interop/_insecure_interop_test.py:34: in <module>
    from grpc.early_adopter import implementations
../../../python_virtual_environment/local/lib/python2.7/site-packages/grpc/early_adopter/implementations.py:34: in <module>
    from grpc._adapter import fore as _fore
../../../python_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/fore.py:38: in <module>
    from grpc._adapter import _intermediary_low as _low
../../../python_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/_intermediary_low.py:57: in <module>
    from grpc._adapter import _low
../../../python_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/_low.py:30: in <module>
    from grpc._adapter import _c
E   ImportError: /usr/lib/libgrpc.so.0: undefined symbol: GENERAL_NAME_free

**Comment by soltanmm** [comment]
This is a documentation bug. Those particular instructions are stale to the tune of... several months.

**Comment by zhenghub** [comment]
Thanks, this helps and I don't need to copy the generated libs to /usr/lib.
But still meet the 13 errors: "/usr/lib/libgrpc.so.0: undefined symbol: GENERAL_NAME_free".
>>
grpc_interop/_insecure_interop_test.py:34: in <module>
    from grpc.early_adopter import implementations
../../../python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/early_adopter/implementations.py:34: in <module>
    from grpc._adapter import fore as _fore
../../../python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/fore.py:38: in <module>
    from grpc._adapter import _intermediary_low as _low
../../../python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/_intermediary_low.py:57: in <module>
    from grpc._adapter import _low
../../../python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/_low.py:30: in <module>
    from grpc._adapter import _c
E   ImportError: /home/zhenghu/document/git/grpc/libs/opt/libgrpc.so.0: undefined symbol: GENERAL_NAME_free

**Comment by soltanmm** [comment]
Have you ensured that the system libs you copied are removed? Do you have the right version of OpenSSL installed (>`1.0.2d`)? Barring that, did you `git submodule update --init` before running `make`? Did you change where the files were located since building Python? Have you tried, from a fresh repository clone, to repeat the steps?

**Comment by zhenghub** [comment]
OK, I redo all the steps from a fresh repository finally succeed. Maybe the key is "git submodule update --init". It always failed because of network problem to execute "git submodule..." while this time succeed.
Thanks!!

**Comment by soltanmm** [comment]
You're welcome!

(Moved documentation issue to #2896)
