### ISSUE TITLE
Request distribution with Python multi-processing

### ISSUE THREAD

**Issue by internetstaff** [grpc/grpc#28867]
We're dealing with a Python grpc server that's extremely CPU intensive with long-running (10-60 second) requests.

Our horizontal scalability was severely limited with the thread executor. We've followed the multi-processing example, and that does allow us to scale with CPU cores quite well.

The major drawback is: requests frequently seem to be accepted by a process that is already busy and forced to wait 60 seconds while other processes are idle. 

I am wondering if there's a way to avoid this or if there's a more optimal solution for parallel processing with Python?

Thanks!

**Comment by internetstaff** [comment]
Threads don't help - these are calls that peg the CPU at 100% for 10-60 seconds.

That's why we're testing the multi-processing example, but then we have the problem above of a sub-process accepting a connection + request even though it's already busy while another sub-process is idle.

**Comment by lidizheng** [comment]
Well, the SO_REUSEPORT load balancing is not ideal, it routes based on ip:port, it's inflexible. We currently don't have a multi-process load balancing solution build-in for gRPC. You can try to add a L7 proxy in front, or use orchestration tools (like K8s).

**Comment by internetstaff** [comment]
I think we can solve our production use case with AWS ALBs and automated retries on RESOURCE_EXHAUSTED.

However, I was wondering if there was a more flexible option: for example, making sure each process can only accept one connection.

Thanks!

**Comment by lidizheng** [comment]
There is a `maximum_concurrent_rpcs` field we support: https://grpc.github.io/grpc/python/grpc.html#grpc.server

**Comment by internetstaff** [comment]
That's what we're using to at least reject the extra requests, but it'd be preferable to allow them to fall to another listener on the socket.

**Comment by lidizheng** [comment]
Well... shredding loads from one process to another at socket level. AFAIK, should not be possible with SO_REUSEPORT 🤔 

Off the cuff, one potential solution is that you can write your own gRPC proxy to manage the routing of requests in that machine. Since the traffic load is not too-big, you can still use Python. This avoids paying extra fees to cloud provider, and gains more control.
