### ISSUE TITLE
AddressSanitizer bad free in CompletionQueue

### ISSUE THREAD

**Issue by Desperado17** [grpc/grpc#28874]
Greetings,

the problem from this stackoverflow issue

https://stackoverflow.com/questions/63789313/grpc-c-addresssanitizer-bad-free

Has now occured for us on an Aarch64 Yocto Linux system.

Is this issue known and is it actually a false positive as the replier suggests?

Regards

Edit: Ok, might be same as this one:
https://github.com/grpc/grpc/issues/23640

Any idea yet what it might be?

**Comment by yashykt** [comment]
Can you please provide your repro code as a gist maybe, so that we can more easily reproduce it on our end?

Head's up - If this is platform-specific (arch64 yocto linux), we might not be able to help immediately.

**Comment by yashykt** [comment]
Also, please make sure that this does not reproduce on head. (might have been fixed since v1.30)
