### ISSUE TITLE
cannot assign requested address

### ISSUE THREAD

**Issue by davidporter** [grpc/grpc#28880]
File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: <urlopen error [Errno 99] Cannot assign requested address>"
        debug_error_string = "{"created":"@1644900494.345978200","description":"Error received from peer ipv4:172.18.0.19:50051","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Exception calling application: <urlopen error [Errno 99] Cannot assign requested address>","grpc_status":2}"

Not sure why I am getting this?  I can wget and see my server but I keep getting this error.  Please help.

**Comment by nicolasnoble** [comment]
This doesn't look like an error within grpc itself. You're getting an error response from the execution of your RPC, which is the python error `Exception calling application: <urlopen error [Errno 99] Cannot assign requested address>`. Basically, gRPC did its job properly; it sent the RPC from your client to your server, but then the server code that's running caused a failure while running the service for said RPC.

Without further detail on what's going on in your server, I don't think we can help much more, but in all cases, everything is fine from the gRPC point of view, it's the application layer that's at fault and is being reported here.

**Comment by davidporter** [comment]
Thank you, that pointed me in the right direction.  It was an issue in another part of my code.  A little hard to track down, but with your info I found it!  Thanks again.
