### ISSUE TITLE
install

### ISSUE THREAD

**Issue by marcgrc** [grpc/grpc#28887]
how do i install grpc 1.44 on raspberry 3
Arm 7 for google assistant project?

**Comment by nicolasnoble** [comment]
Please re-open this issue with the proper details as requested in our bug issue template, or use our mailing list to ask questions.

**Comment by bodiroga** [comment]
Hi @nicolasnoble!

Sorry to bother you writing in a closed issue, but I didn't want to open a new issue to ask for such a simple question:

Do you know when gRPC 1.44.0 version will be available in pypi.org? I have tried manually installing the RC2 version and it works great, but it would be awesome if the final version could be available 😉 

Many thanks for your work and best regards!

**Comment by nicolasnoble** [comment]
@gnossen / @lidizheng ?

**Comment by lidizheng** [comment]
Sorry for the delay. gRPC Python v1.44.0 is now uploaded to PyPI.

**Comment by bodiroga** [comment]
Wow, I didn't expect such a fast replay, thank you very much! 👍🏻 

Keep up with the awesome work, guys!
