### ISSUE TITLE
Update pip and apt packages

### ISSUE THREAD

**Issue by BlackLight** [grpc/grpc#28906]
The 1.44 release was finally pushed a couple of days ago to fix the [infamous libatomic bug](https://stackoverflow.com/questions/70084134/undefined-symbol-atomic-exchange-8), but it hasn't yet been pushed to pypi (still on 1.43) nor to apt (still on 1.30).

Would it be possible to do both? As of now, the only way to get a working grpcio installation on a Raspberry Pi is still to clone the repo and compile/install the code, which is far from ideal on a RPi...

**Comment by ben9923** [comment]
PyPI now seems to have 1.44 (uploaded Feb 17), but it doesn't include `mussllinux` wheels.
Support was added in #28092 and nightly builds do output such artifacts, but they weren't uploaded to PyPI with the latest release.

Would be great to have those, as build from `sdist` can take a while on every install...

**Comment by ben9923** [comment]
@gnossen / @lidizheng could you please help with `musllinux` wheels on PyPI?

Thanks!

**Comment by lidizheng** [comment]
Apologies, the v1.44.0 is uploaded with a bit delay. The `musllinux` build will be included in v1.45.0, the pre-release should be cut this week, or next. The official release should be out in a month.

I can try to ask previous people managing the v1.44.x, to see if I can release a patch.

**Comment by ben9923** [comment]
@lidizheng Ah, I didn't realize it was merged after the `v1.44.x` branch from `master`, so I thought it should already be there. I'm sorry!

Having it in the `v1.45.x` release would be good too, I really just thought it was a deployment error.
Thanks for opening the backport PR, would be cool to have it merged, if possible :)

**Comment by ben9923** [comment]
@lidizheng Hey :)
I tried to download the `1.45.0` release from PyPI but apparently it was yanked.
I could not find the reason for that, any idea? Schedule for another Python release of `1.45.x`?

**Comment by lidizheng** [comment]
Hi @ben9923, sorry for the delay, we are working toward the `v1.45.1` release.

**Comment by lidizheng** [comment]
Closing this issue, thanks for the ping.
