### ISSUE TITLE
Issues connecting to pubsub

### ISSUE THREAD

**Issue by guevarabrik24** [grpc/grpc#28935]
### What version of gRPC and what language are you using?
* Python 3.6.9
* grpc-google-iam-v1==0.12.3
* grpcio==1.43.0
* grpcio-status==1.43.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04 WSL2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.9

### What did you expect to see?
Connect to pubsub

### What did you see instead?

this error occurs multiple times before running into timeout:
E0220 13:28:39.490081100    4464 ev_epollex_linux.cc:515]    Error shutting down fd 18. errno: 9
E0220 13:28:39.490081100    4464 ev_epollex_linux.cc:515]    Error shutting down fd 18. errno: 9

### Anything else we should know about your project / environment?
* Sometimes restarting the machine solves the problem. 
* Sometimes using another network (home network for example) doesn't produce this error. 
* I updated the system drivers to the latest
* I am using a vpn

Any hint on how to fix this issue?

**Comment by yashykt** [comment]
Please take a look at https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for help on logging and tracing. I'll also note that the epollex polling engine has been deleted at head. The default engine is epoll1 currently.
