### ISSUE TITLE
Python out-of-project-tree README.md is stale

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#2896]
This [README.md](https://github.com/grpc/grpc/tree/master/src/python/README.md) file is stale. However, it's not clear to me why we'd want to have it, given that we're distributing `README.rst` files via the PyPI projects and the `README.md` never appears among those files.

Do we want to keep this file and update it, if only to give people browsing GitHub something to look at?

cc @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
I'd like to avoid having the file at all but I think we put it there at release time as part of an all-wrapped-languages decision to have installation instructions there. It may be time to reconsider?

**Comment by yang-g** [comment]
Is this dead?

**Comment by nathanielmanistaatgoogle** [comment]
Not quite dead; I think a conversation has to happen before this can be resolved.

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: there's nothing in `src/python/README.md` that isn't better documented elsewhere, and there's about the tree of files under `src/python` that merits describing in a `README.md` rooted in the tree. Let's kill the file.

**Comment by hsaliak** [comment]
Agreed - let's kill it.
