### ISSUE TITLE
The grpc unity plugin cannot run in the M1 version of unity2021.2

### ISSUE THREAD

**Issue by RuyeRuye** [grpc/grpc#28974]
### What version of gRPC and what language are you using?
gRPC 2.45.0
CSharp

### What operating system (Linux, Windows,...) and version?
Mac OS 12.0.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
CSharp version (Unity)

### What did you do?
I switched the unity version from Intel(2020.3) to M1(2021.2), so I reported an error while the editor was running：
DllNotFoundException: grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)
Grpc.Core.Internal.NativeLogRedirector.Redirect (Grpc.Core.Internal.NativeMethods native) (at /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeLogRedirector.cs:49)

I use the same version of Unity(2021.2) on Windows and don't have this bug , so I don't think dll supports the M1 version of unity editor yet.

### What did you expect to see?
The grpc unity version can support unity(2021.2) for Apple Silicon M1.
### What did you see instead?
![image](https://user-images.githubusercontent.com/88803076/155670256-912c1f80-e7da-4557-a3bd-3fcd46515081.png)

**Comment by Mlisager** [comment]
Same issue here. I'm on Macbook pro M1 macOs 11.6.2 and had the same message after upgrading to 2021 Unity (2021.2.13f1) with the Silicon build.

**Comment by drfloob** [comment]
Pinging @jtattermusch. The gRPC-core-wrapped C# library was placed in maintenance mode around 10 months ago, and unity was never officially supported. I do not imagine there will be bandwidth to investigate this.

**Comment by doctorpangloss** [comment]
I fixed this build, but it's involved. There's no C# gRPC library compatible with Unity right now without these fixes.

**Comment by mandicLuka** [comment]
same here. 
@doctorpangloss I would really appreciate if you could share your solution

**Comment by doctorpangloss** [comment]
You can view the changes here - https://github.com/hiddenswitch/grpc

At a high level, abseil is monkey patched in my revisions to correctly use the OSX architecture, but nowadays abseil has the appropriate fixes. Then, I build the two architectures separately and lipo the final library. Then I patch in the right meta file. It would be way more challenging to modify all of this stuff and grpc isn't going to merge such patches so this was the way.

There care considerable additional pieces. In my application, I use the following `gradle` build script, which you can interpret and adapt for your needs.

File structure
```
src (git clone --recurse-submodule https://github.com/hiddenswitch/grpc src)
build.gradle
unity_skeleton/
  x64/
    grpc_csharp_ext.bundle.meta
```

build.gradle
```groovy
import org.apache.tools.ant.taskdefs.condition.Os

plugins {
  id 'base'
}

task dependences {
  doLast {
    exec {
      commandLine "brew", "install", "autoconf", "automake", "libtool", "shtool"
    }
  }
}

task make {
  onlyIf { Os.isFamily(Os.FAMILY_MAC) }
  inputs.files('src/src/**/*')
  outputs.file('src/libs/opt/libgrpc_csharp_ext.dylib')
  doLast {
    exec {
      environment("LIBTOOL", "glibtool")
      environment("LIBTOOLIZE", "glibtoolize")
      workingDir("$projectDir/src")
      commandLine "make", "-j", "8"
    }
  }
}

def appleArches = ['x86_64', 'arm64']
appleArches.forEach({ arch ->
  def cmake = "cmakeApple_$arch"
  tasks.register(cmake, {
    inputs.files('src/**/CMakeLists.txt')
    outputs.file("$buildDir/cmake-build-release-$arch/CMakeCache.txt")
    doLast {
      exec {
        workingDir("$projectDir/src")
        commandLine "cmake", "-B", "../build/cmake-build-release-$arch", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_OSX_ARCHITECTURES=$arch", "-G", "Xcode", "-DCMAKE_CXX_FLAGS=\"-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk\""
      }
    }
  })

  tasks.register("buildApple_$arch", {
    dependsOn cmake
    inputs.file("$buildDir/cmake-build-release-$arch/CMakeCache.txt")
    inputs.dir('src/src')
    outputs.file("$buildDir/cmake-build-release-$arch/Release/libgrpc_csharp_ext.dylib")
    doLast {
      def cmakeResult = exec {
        workingDir("$projectDir/src")
        commandLine "cmake", "--build", "../build/cmake-build-release-$arch", "--config", "Release"
        ignoreExitValue(true)
      }
      if (cmakeResult.exitValue == 65) {
        throw new GradleException("Log into XCode again")
      }
      if (cmakeResult.exitValue != 0) {
        throw new GradleException("Failed to build")
      }
    }
  })
})

task assembleAppleSilicon {
  onlyIf { Os.isFamily(Os.FAMILY_MAC) }
  dependsOn appleArches.collect { arch -> "buildApple_$arch" }

  def files = appleArches.collect { arch -> "$buildDir/cmake-build-release-$arch/Release/libgrpc_csharp_ext.dylib" }
  inputs.files(files)
  outputs.dir("$buildDir/Protos")

  doLast {
    mkdir("$buildDir/lipo")
    exec {
      workingDir "$buildDir/lipo"
      commandLine(["lipo", "-create"] + files + ["-output", "grpc_csharp_ext.bundle"])
    }
    copy {
      from "unity_skeleton"
      into "$buildDir/Protos/Plugins/Grpc.Core/runtimes/osx"
    }

    copy {
      from "$buildDir/lipo"
      into "$buildDir/Protos/Plugins/Grpc.Core/runtimes/osx/x64"
    }
  }
}

task makeClean {
  destroyables.register(files('src/libs/opt/**'))
  doLast {
    exec {
      environment("LIBTOOL", "glibtool")
      environment("LIBTOOLIZE", "glibtoolize")
      workingDir("$projectDir/src")
      commandLine "make", "clean"
    }
  }
}

build.dependsOn make
assemble.dependsOn assembleAppleSilicon
clean.dependsOn makeClean
```

unity_skeleton/x64/grpc_csharp_ext.bundle.meta
```
fileFormatVersion: 2
guid: 71eee07a271454808af586fd222965fb
PluginImporter:
  externalObjects: {}
  serializedVersion: 2
  iconMap: {}
  executionOrder: {}
  defineConstraints: []
  isPreloaded: 0
  isOverridable: 0
  isExplicitlyReferenced: 0
  validateReferences: 1
  platformData:
  - first:
      : Any
    second:
      enabled: 0
      settings:
        Exclude Editor: 0
        Exclude Linux64: 1
        Exclude OSXUniversal: 0
        Exclude Win: 1
        Exclude Win64: 1
  - first:
      Any: 
    second:
      enabled: 0
      settings: {}
  - first:
      Editor: Editor
    second:
      enabled: 1
      settings:
        CPU: AnyCPU
        DefaultValueInitialized: true
        OS: AnyOS
  - first:
      Standalone: Linux64
    second:
      enabled: 0
      settings:
        CPU: AnyCPU
  - first:
      Standalone: OSXUniversal
    second:
      enabled: 1
      settings:
        CPU: AnyCPU
  - first:
      Standalone: Win
    second:
      enabled: 0
      settings:
        CPU: x86
  - first:
      Standalone: Win64
    second:
      enabled: 0
      settings:
        CPU: x86_64
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```

**Comment by sableangle** [comment]
Hello guys,

I build a binary for the Apple Silicon Mac with native Unity Editor such as Unity 2021.2 2021.3.

You can get the binary on my Google Drive.
[https://drive.google.com/file/d/1wuJsiP-sxpD_4T_COzpRUjUwWDY0S-pJ/view?usp=sharing](url)

And put the files into your Unity Project following the screenshot. (Including the .meta files)
![image](https://i.imgur.com/tDrcT7J.png)

P.S. I'm not a expert for a cmake, so I'm not sure the reason that the built binary is quite larger than the x86 and x86_64 binary.

**Comment by doctorpangloss** [comment]
This doesn't work, because `grpc` doesn't look for the binary in that directory.

**Comment by sableangle** [comment]
It works, actually.
You need to also setup the plugin import correctly, so on my post I metion .meta is also require to import to the Unity Project too.

If the ARM64 binary plugin is set likes the following screenshot, your Unity should works!
The platform setting of a binary plugin should be set to correct CPU, then everything work great.
That is because, Unity doesn't search a binary by the folder structure, Unity search for binary plugin by the plugin's meta setting on the inspector. 

grpc only looking for an entry point which named grpc_csharp_ext.bundle, and Unity decide which grpc_csharp_ext.bundle will be loaded following the plugin import setting.

So, yes one way is bundle all arches into a single grpc_csharp_ext.bundle, or split the arch to different grpc_csharp_ext.bundle files and set the import correctly on Unity, both should works!

At least it works on my local project. (M1, Unity 2021.3 Apple Silicon)

![image](https://imgur.com/taKIWqL.png)

**Comment by doctorpangloss** [comment]
Try issuing the command `file Assets/Plugins/Grpc.Core/runtimes/osx/x64/grpc_csharp_ext.bundle` from your project directory, then paste the output here.

**Comment by doctorpangloss** [comment]
> That is because, Unity doesn't search a binary by the folder structure, Unity search for binary plugin by the plugin's meta setting on the inspector.
It doesn't do either of these things.

**Comment by sableangle** [comment]
Command:
`file /Users/miki/Plugins/Grpc.Core/runtimes/osx/x64/grpc_csharp_ext.bundle`
Result:
`/Users/miki/Plugins/Grpc.Core/runtimes/osx/x64/grpc_csharp_ext.bundle: Mach-O 64-bit dynamically linked shared library x86_64
`


Command:
`file /Users/miki/Plugins/Grpc.Core/runtimes/osx/arm64/grpc_csharp_ext.bundle`
Result:
`/Users/miki/Plugins/Grpc.Core/runtimes/osx/arm64/grpc_csharp_ext.bundle: Mach-O universal binary with 1 architecture: [arm64:Mach-O 64-bit dynamically linked shared library arm64Mach-O 64-bit dynamically linked shared library arm64]
/Users/miki/Plugins/Grpc.Core/runtimes/osx/arm64/grpc_csharp_ext.bundle (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
`

As the result, the grpc_csharp_ext.bundle in /runtimes/osx/x64/ folder only contains x86_64 arch, and the grpc_csharp_ext.bundle in /runtimes/osx/arm64/ folder  only contains arm64 arch(though it is a universal binary, it contains only 1 arch)

**Comment by sableangle** [comment]
I'm not an expert about make and CMake, so I just build the binary following the repo's guide and I don't know how to make a Universal binary which contains both x86_64 and arm64 arches.

I try the build.gradle script which you shared, but always got compile errors, so I try another solution.

If you could kindly shared the universal(contains x86_64 and arm64) grpc_csharp_ext.bundle file, that will be awesome and helpful!

**Comment by doctorpangloss** [comment]
I'm not sure what you are observing. I understand you built a binary that has the right architecture. I think people are welcome to try, and just like I did, they'll observe that following your instructions does not work.

**Comment by sableangle** [comment]
Which version Unity are you using?
I'm not sure does Unity complete the Apple Silicon plugin import option before 2021.3 or not, since 2021.3 is LTS version I only do testing on 2021.3.

One other note, the ARM64 arch binary should import to your Unity before the Project is opened by Unity, or we should restart the Unity Editor after import the ARM64 binary.

That's because, Unity will try to load the plugin while starting, and once it is loaded, it will never unload(or load another one), so if the Unity has start before the ARM64 binary is import than Unity will load an incorrect binary, the official daily release grpc build set the x86 binary import setting as "Any CPU" and "mac OS", so the x86 one will be loaded if the Unity cannot find an ARM64 binary and which will cause "DllNotFoundException: grpc_csharp_ext".

**Comment by doctorpangloss** [comment]
I don't really have the bandwidth to litigate this, but I think if you have a resolution you should PR it.

**Comment by mandicLuka** [comment]
I was having a problem on Linux and following this [issue post](https://github.com/grpc/grpc/issues/22485#issuecomment-604502885) I have solved the problem. At the end I had to add grpc_csharp_ext_dummy_stubs.c as noted in this [post](https://github.com/grpc/grpc/issues/22485#issuecomment-933666885)

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).

**Comment by limdingwen** [comment]
> Hello guys,
> 
> I build a binary for the Apple Silicon Mac with native Unity Editor such as Unity 2021.2 2021.3.
> 
> You can get the binary on my Google Drive. https://drive.google.com/file/d/1wuJsiP-sxpD_4T_COzpRUjUwWDY0S-pJ/view?usp=sharing
> 
> And put the files into your Unity Project following the screenshot. (Including the .meta files) ![image](https://camo.githubusercontent.com/8cfa689e329413308987c1b9a35ff5cce45a7612e479fdc2efa25c2c574029a4/68747470733a2f2f692e696d6775722e636f6d2f7444726354374a2e706e67)
> 
> P.S. I'm not a expert for a cmake, so I'm not sure the reason that the built binary is quite larger than the x86 and x86_64 binary.

_Thank you so much_, it just works!!! Just had to drop it into the Plugins folder. May I know how you did it?

I'll reupload your zip here as a mirror, just in case your Google Drive disappears: [arm64_grpc_csharp_ext.zip](https://github.com/grpc/grpc/files/12541213/arm64_grpc_csharp_ext.zip)

**Comment by BoysheO** [comment]
It doesn't work in Unity runtime on M1 except when exported as x86. DLL not found is reported.
