### ISSUE TITLE
Fix test/cpp for compliance with MSVC 2010

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2898]
Use this issue to track compatibility.
For now, the obvious issues are use of std::unique_lock , std::mutex , and std::lock_guard . We should instead use the grpc:: versions of these in test just as they are used in src

**Comment by vjpai** [comment]
Update that this still has not been tested, with a particular focus on #2915 .

**Comment by ctiller** [comment]
Visual Studio 2010 is not supported.
