### ISSUE TITLE
What is the GRPC Trace Flag Enable API I/F ?

### ISSUE THREAD

**Issue by ashu-ciena** [grpc/grpc#28982]
I am running a C++ based grpc server 1.42 on linux target and want the ability to enable the GRPC logging /Trace at run time whenever we come across an issue/crash in grpc stack.

I am compiling the grpc stack as a library and linking this with a binary that implements grpc server.  The grpc code is downloaded at run time using a git hash and library is created at run time, so we don't have the opportunity to make any custom changes in grpc code.

I am not able to enable the logs under the MACRO **"GRPC_TRACE_FLAG_ENABLED"** !! However, I am able to capture the logs outside this flag ( a very few of them)

I am looking for an API which I can call to enable a specific trace category like **"grpc_api_trace"**, **"grpc_health_check_client_trace"**, **"grpc_server_channel_trace"** and **"grpc_connectivity_state_trace"** etc.

To make this happen, I tried to define **extern grpc_core::TraceFlag <trace type>** followed by a call to **grpc_tracer_enable_flag (<trace type>)**. But I am not able to compile, as the namespace grpc_core is not available it seems.  I am also trying to find a common header file where I can find the declaration of namespace grpc_core which I can copy to my build file system to be available to me for compilation. 

Please provide me some pointers to enable these logs from an application outside the grpc stack.

**Comment by drfloob** [comment]
Traces and verbosity changes are not modifiable at runtime after gRPC is initialized, you would need to start the processes with flags enabled. You could start your own processes with the gRPC environment variables set, and gRPC will pick them up on init.

**Comment by ashu-ciena** [comment]
> Traces and verbosity changes are not modifiable at runtime after gRPC is initialized, you would need to start the processes with flags enabled. You could start your own processes with the gRPC environment variables set, and gRPC will pick them up on init.

I am able to turn on the traces and verbosity environmental variables at the time of initialization with GRPC_TRACE and GRPC_VERBOSITY flags.  My concern is how to enable logs under the "GRPC_TRACE_FLAG_ENABLED" condition.  
In the class TraceFlag, we have a friend function grpc_tracer_enable_flag() which will allow us to set the "enabled" member of a specific trace category like grpc_api_trace. So, I was trying to explore this option to turn on the flags controlled GRPC_TRACE_FLAG_ENABLED macro.  

Is this possible?

**Comment by drfloob** [comment]
The `GRPC_TRACE_FLAG_ENABLED` macro uses the `GRPC_TRACE` environment variable. For example, if you have the environment variable `GRPC_TRACE=tcp` when gRPC is initialized, then `GRPC_TRACE_FLAG_ENABLED(grpc_tcp_trace)` will return `true` (which is usually used to enable logging). That's the only way to make `GRPC_TRACE_FLAG_ENABLED` return `true`. Does that answer your question, or do I still misunderstand your goal?
