### ISSUE TITLE
LB policies with multiple active children should delay picker updates while updating children

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#28984]
To allow localities moving priorities within xDS atomically, when processing a config update, the priority policy should inhibit upward picker updates of its own until it has provided the configs to all of its children. Children update their picker synchronously when receiving the config update, so after passing down the new configuration to all children the priority policy will have updated pickers for each and should at that point propagate its own picker update upward. This was decided in the cross-language TL discussion on 2022-02-11.

Java and Go will need to validate that all policies update their picker synchronously when receiving a config update, but this is the case already for C.

grpc/grpc-java#8952 grpc/grpc-go#5211

**Comment by markdroth** [comment]
Also done for weighted_target and xds_cluster_manager in #29313.

Still need this for RLS.
