### ISSUE TITLE
Receiving "Only one read can be pending at a time" when listening two+ streams simultaneously.

### ISSUE THREAD

**Issue by Venzz** [grpc/grpc#28990]
Hello,

I'm using C# Grpc.Core v2.44.0 NuGet package.
Windows 10 (10.0.19044.1526), .NET Framework 4.7.2

I'm creating two AsyncServerStreamingCall<T> streams which provide different data.
`            var grpcChannel = new Channel(endpoint, ChannelCredentials.SecureSsl);
            MarketDataStreamClient = new MarketDataStreamService.MarketDataStreamServiceClient(grpcChannel);
            MarketDataStream = MarketDataStreamClient.MarketDataStream(GrpcMetadata);
            OrderStreamClient = new OrdersStreamService.OrdersStreamServiceClient(grpcChannel);
            OrderStream = OrderStreamClient.TradesStream(new TradesStreamRequest(), GrpcMetadata);`

And I'm listening to two streams like that
`
                    var marketDataResponseTask = MarketDataStream.ResponseStream.MoveNext();
                    var orderResponseTask = OrderStream.ResponseStream.MoveNext();
                    await Task.WhenAny(marketDataResponseTask, orderResponseTask).ConfigureAwait(false);
`

Since marketDataResponseTask started first, I'm receving "Only one read can be pending at a time" on the second task (orderResponseTask) immediately. And while one of these task is waiting for a response, the other will be returning the error every time I call MoveNext();

**Comment by jtattermusch** [comment]
From the symptoms I'd say that your two streams are in fact somehow to the same grpc call (each for each gRPC call, you can only invoke MoveNext() once at a time).
I'd suspect there's a bug somewhere in your code that ends up invoking call.ResponseStream.MoveNext()  twice for the same call.
Please double check your code and if the problem persists, please provide a ready-to-run reproduction (e.g. as a github repo).

**Comment by Venzz** [comment]
I found the bug. Not an issue. Thanks!

**Comment by aaronhudon-ts** [comment]
@Venzz do you mind elaborating on your solution?  I am also looking to handle multiple streams from one thread.
