### ISSUE TITLE
which version grpc will be compatible with protobuf 3.18.0/3.18.1?

### ISSUE THREAD

**Issue by AlexLuya** [grpc/grpc#29022]
Hello,our client provides some generated protobuf API which has content like this:

```
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif
```
It seems like I need to install a grpc which is compatible with protobuf 3.18.0 or 3.18.1,and I found a compatibility table in this page:

`https://github.com/grpc/grpc/blob/master/src/php/README.md`

but it stoped in grpc v.1.3.0,and the .gitmodule file of grpc didn't tell much also,so would you please tell me:

`which version grpc will be compatible with protobuf 3.18.0/3.18.1?`

**Comment by nicolasnoble** [comment]
The compatibility table you're looking at is about the minimum feature set we, as the grpc library, require from protobuf, but it has nothing to do with the generated code.

You cannot ship generated C++ protobuf files. The protobuf library has no API/ABI guarantees for the generated code across versions. This usage case is unsupported by the protobuf library. You need to have people regenerate their source code with their protoc compiler and their protobuf libraries.

**Comment by yashykt** [comment]
Also, questions are better targetted to stack-overflow or the grpcio google group :)
