### ISSUE TITLE
go grpc and c++ grpc installed in same machine

### ISSUE THREAD

**Issue by babuveld** [grpc/grpc#29030]
Hi,

We have a ubuntu 20.04 based root file system and it already has grpc go 1.41.0 which used by go based apps. For one of the c++ libraries that we developed requires gRPC c++ source installation specifically 1.32.0 version.

Can different versions of go gRPC and c++ gRPC co-exist in machine? Does it cause an runtime issues for the go applications?

**Comment by veblush** [comment]
Short answer is yes. They should be able to coexist.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
