### ISSUE TITLE
Python: 3.6 EOL. Drop 3.6 support?

### ISSUE THREAD

**Issue by gitpushdashf** [grpc/grpc#29040]
Python 3.6 has been EOLed. Should we drop 3.6 support?

Thanks!

**Comment by lidizheng** [comment]
Thanks for the heads up. We probably can do it in the next release.

**Comment by gitpushdashf** [comment]
Thank you! If you've never seen it before, [pyupgrade](https://pypi.org/project/pyupgrade/) can be really handy to upgrade syntax automatically.

**Comment by gnossen** [comment]
3.6 support was dropped in release 1.49.
