### ISSUE TITLE
Fork support is only compatible with the epoll1 and poll polling strategies

### ISSUE THREAD

**Issue by jaxxstorm** [grpc/grpc#29044]
### What version of gRPC and what language are you using?

v1.44.0
Python

### What operating system (Linux, Windows,...) and version?

OS X

### What runtime / compiler are you using (e.g. python version or version of gcc)

3.9.2

### What did you do?

Since the release of `v1.44.0` we're getting errors thrown that says:

```
Fork support is only compatible with the epoll1 and poll polling strategies
```

We haven't made any other changes to our code, and this didn't happen beforehand. I looked through the changelog, and it's difficult to understand why these errors are now surfacing.

### What did you expect to see?

Not an error

### What did you see instead?

```
Fork support is only compatible with the epoll1 and poll polling strategies
```

**Comment by maxfirman** [comment]
Here is a minimal reproducible example of the hello world `greeter_client.py`:

```python
from __future__ import print_function

import logging
from concurrent.futures import ProcessPoolExecutor

import grpc

import helloworld_pb2
import helloworld_pb2_grpc

NUM_REQUESTS = 10
POOL_SIZE = 2


def worker(message):
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        response = stub.SayHello(helloworld_pb2.HelloRequest(name=str(message)))
        print("Greeter client received: " + response.message)


def run():
    with grpc.insecure_channel('localhost:50051') as channel:
        with ProcessPoolExecutor(POOL_SIZE) as p:
            p.map(worker, range(NUM_REQUESTS))


if __name__ == '__main__':
    logging.basicConfig()
    run()

```

**Comment by drfloob** [comment]
I can't reproduce this on my mac with the latest OS X, and grpcio v1.44.0. On Mac, gRPC defaults to use the `poll` polling engine. I'd be curious if your code worked if you ran the same process with the environment variables `GRPC_POLL_STRATEGY=poll`, which should be redundant on Mac, and `GRPC_VERBOSITY=debug`. The first few lines of output will show you which polling engine you're using.

```
(pr29044) my-machine::tmp/pr29044 » GRPC_VERBOSITY=debug python main.py
D0308 09:04:42.287589000 4498904576 ev_posix.cc:172]                   Using polling engine: poll
D0308 09:04:42.287663000 4498904576 lb_policy_registry.cc:42]          registering LB policy factory for "grpclb"
D0308 09:04:42.287674000 4498904576 lb_policy_registry.cc:42]          registering LB policy factory for "priority_experimental"
...
```

Please see https://github.com/grpc/grpc/pull/28566. Previously, gRPC issued an info-level log about fork not being supported for certain pollers, then continued allowing the fork to proceed with undefined behavior. Now, it emits and error and prevents the fork altogether.

**Comment by maxfirman** [comment]
@drfloob thanks for your reply. I tried your suggestion of setting `GRPC_POLL_STRATEGY=poll` and it resolved the error with v1.44.0. For reference my tests were run against the official Python 3.9 docker image (https://hub.docker.com/_/python/) which is based off Debian. 

I think that this change will have resulted in problems for many consumers of the grpc library, for example see this issue: https://github.com/ray-project/ray/issues/22518. That said, I understand the rationale if it prevents undefined behaviour. 

The default polling engines are in fact documented here: https://grpc.github.io/grpc/core/md_doc_core_grpc-polling-engines.html. On Mac systems it is defaulted to `poll` which would explain why you were unable to reproduce the issue, however linux defaults to `epollex`. Would it make sense to change the default polling strategy from `epollex` to `poll` on linux in order to resolve this issue?

**Comment by drfloob** [comment]
The poll strategy is generally less performant on linux than either of the epoll options, changing that default would hurt a lot of folks. I'll defer to @lidizheng and @gnossen on the best path forward for Python more generally.

**Comment by lidizheng** [comment]
@maxfirman Hi, in the snippet you provided above, I believe you are using an "after-fork" pattern, where all gRPC objects are created after the fork happen. More specifically, only logic in `worker` is invoking gRPC Python API, this means there won't be preexisting states or locks to complicate forking.

I would suggest to set the fork support to `False`, and try again.

**Comment by mwtian** [comment]
Would it be possible to resolve the inconsistency between Python and core GRPC, e.g. have default fork support in Python grpc set to `false`, or set the default fork support to `true` only when the default polling engine is `epoll1` or `poll`? Otherwise, it seems by default, error logs are printed. e.g. On Ubuntu 20.04, Python 3.8.12 and grpcio==1.44.0, the simplest script triggers the error logs mentioned earlier:
```
import grpc
chan = grpc.insecure_channel("localhost:6379")
```

**Comment by lidizheng** [comment]
I'm trying to replicate your result here. I'm using "ubuntu:20.04" Docker image, with Python 3.8.10, and grpcio==1.44.0.

Here is what I get:

```
root@3b561b81eb3d:/# export GRPC_VERBOSITY=debug
root@3b561b81eb3d:/# python3 -m pip install grpcio
Collecting grpcio
  Downloading grpcio-1.44.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 23.0 MB/s
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, grpcio
Successfully installed grpcio-1.44.0 six-1.16.0
root@3b561b81eb3d:/# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> grpc.insecure_channel("localhost:6379")
D0310 01:02:50.572391968    3746 ev_posix.cc:172]            Using polling engine: epollex
D0310 01:02:50.572546805    3746 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0310 01:02:50.572575096    3746 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0310 01:02:50.572593674    3746 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0310 01:02:50.572605540    3746 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0310 01:02:50.572627263    3746 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0310 01:02:50.572639637    3746 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D0310 01:02:50.572652040    3746 dns_resolver_ares.cc:624]   Using ares dns resolver
D0310 01:02:50.572718496    3746 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0310 01:02:50.572734106    3746 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0310 01:02:50.572754105    3746 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0310 01:02:50.572772589    3746 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0310 01:02:50.572789694    3746 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
<grpc._channel.Channel object at 0x7f1b509d1c10>
>>>
D0310 01:03:04.658495178    3746 init.cc:177]                grpc_shutdown starts clean-up now
```

I didn't see the error line. Emm... could it be a leaked environment variable entry?

**Comment by mwtian** [comment]
Sorry, the previous script was incomplete. How about this?
```
import grpc
import platform
chan = grpc.insecure_channel("localhost:6379")
platform.system()
```

**Comment by mwtian** [comment]
Here are the logs:
```
$ GRPC_VERBOSITY=debug python repro.py
D0310 01:13:44.913233593  139921 ev_posix.cc:172]            Using polling engine: epollex
D0310 01:13:44.913296771  139921 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0310 01:13:44.913312392  139921 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0310 01:13:44.913322880  139921 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0310 01:13:44.913329421  139921 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0310 01:13:44.913339131  139921 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0310 01:13:44.913345422  139921 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D0310 01:13:44.913351973  139921 dns_resolver_ares.cc:624]   Using ares dns resolver
D0310 01:13:44.913383714  139921 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0310 01:13:44.913391041  139921 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0310 01:13:44.913403689  139921 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0310 01:13:44.913413171  139921 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0310 01:13:44.913418354  139921 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
E0310 01:13:44.913706528  139921 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
D0310 01:13:44.918771644  139921 init.cc:177]                grpc_shutdown starts clean-up now
```

**Comment by hamx0r** [comment]
I had the same problem under Pop! OS 20.04 using the snap-based `gcloud` CLI tool.  Adding the env var `GRPC_POLL_STRATEGY=poll` made the messages go away.

**Comment by lidizheng** [comment]
Thanks for the reports. I think I found the root cause, fix posted at https://github.com/grpc/grpc/pull/29103.
