### ISSUE TITLE
PHP8 - StringValue throws exception when null  

### ISSUE THREAD

**Issue by route33** [grpc/grpc#29052]
### What version of gRPC and what language are you using?
gRPC 1.42.0
Protobuf 3.19.4
PHP 8.0.16

### What operating system (Linux, Windows,...) and version?
Alpine Linux 3.15 (docker image)

### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP 8.0.16, Zend Engine v4.0.16

### What did you do?
(new \Google\Protobuf\StringValue())->setValue(null)
PHP 8.0: Exception with message 'Cannot convert '' to string'
PHP 7.4: Google\Protobuf\StringValue {...}

### What did you expect to see?
The same behaviour as PHP7, an empty string as value

### What did you see instead?
 Exception

 Cannot convert '' to string

### Anything else we should know about your project / environment?
N/A

**Comment by stanley-cheung** [comment]
This is a protobuf issue. Please log an issue to https://github.com/protocolbuffers/protobuf
