### ISSUE TITLE
Shutting down Channel waits indefinitely

### ISSUE THREAD

**Issue by MaSven** [grpc/grpc#29056]
### What version of gRPC and what language are you using?
1.45-dev

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc: gcc (SUSE Linux) 11.2.1 20220103 [revision d4a1d3c4b377f1d4acb34fe1b55b5088a3f293f6]
Copyright (C) 2021 Free Software Foundation, Inc.

ruby: 2.7.4

### What did you do?
In a rspec test, the grpc client gets started. But after all test finish, the grpc client does not close the channel. The rspec process hangs indefinitely and waits for the grpc client to finish.

### What did you expect to see?
The channel to close and rspec to finish.

### What did you see instead?
A process that runs indefinitely.

[grpc_trace.txt](https://github.com/grpc/grpc/files/8216229/grpc_trace.txt)
[thread_dump.txt](https://github.com/grpc/grpc/files/8216243/thread_dump.txt)

### Anything else we should know about your project / environment?

We first encountered this in 1.42. After that we tried out the main branch. 
We also attempted to use poll instead of epoll with the same result. 
Last working version was 1.41

**Comment by alto-ruby** [comment]
What `rspec tes` were you referring to, can you provide more details on how to reproduce this issue?
Can you also try if it is still an issue with the latest release?

The attached grpc_trace.txt appeared to be truncated (or most components not enabled) as it contains basically only timer logs.

**Comment by alto-ruby** [comment]
Close due to inactive, feel free to reopen with more logs
