### ISSUE TITLE
Link error when building app with Xamarin.iOS

### ISSUE THREAD

**Issue by liuzhenLz** [grpc/grpc#29096]
/Users/liuzhen/Desktop/TronNet-main/test/Test2Xamarin.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -force_load /Users/liuzhen/.nuget/packages/grpc.core.xamarin/2.44.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -force_load /Users/liuzhen/.nuget/packages/grpc.core.xamarin/2.44.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a (MT5201) (Test2Xamarin.iOS)

**Comment by liuzhenLz** [comment]
This problem still exists in V2.44.0

**Comment by liuzhenLz** [comment]
<img width="1489" alt="截屏2022-03-15 下午2 05 04" src="https://user-images.githubusercontent.com/19431635/158317016-e637b0b6-f1fb-40a8-9745-b71208e7499b.png">

**Comment by donnadionne** [comment]
duplicating this to #29116
