### ISSUE TITLE
missing ruby gem for 1.44

### ISSUE THREAD

**Issue by gsar** [grpc/grpc#29097]
Is it in the works? The latest production gem that seems to be available is 1.43.1.

**Comment by toxoxi** [comment]
I am likewise waiting for latest release to be released as a ruby gem.

**Comment by gsar** [comment]
looks like a gem is now available for 1.45, though 1.45.1 is out but not available in rubygems. also the 1.45 gem doesn't include a binary build, so it takes literally an hour to install and results in huge disk space consumption. :(

**Comment by johnnyshields** [comment]
[Release v1.46.0-pre1](https://github.com/grpc/grpc/releases/tag/v1.46.0-pre1) also missing a gem @lidizheng

**Comment by lidizheng** [comment]
Sorry about the delay of uploading.

CC Ruby owners @apolcyn @murgatroid99 @stanley-cheung @nicolasnoble

**Comment by gsar** [comment]
thanks for adjusting the priority on this @lidizheng! ruby packaging seems lower down the priority list for this project, which is concerning for us, since grpc is a dependency for most things related to Google Cloud and blocks timely deployments when there are security updates and such.

increasing the ruby build availability to `release blocker` status would be great. thanks to all who work on this project!

**Comment by johnnyshields** [comment]
@lidizheng we're missing rubygems packages for 1.46.1 and 1.46.0 as well. Is this something that can be looked at with priority?

**Comment by mroach** [comment]
It'd be great to get 1.46 released since that provides prebuilt binaries for Ruby 3.1. Having to build gRPC from source is killing our build times and Docker image sizes. :pray:

**Comment by apolcyn** [comment]
1.46.2 was just released with prebuilt binaries for ruby 3.1

**Comment by johnnyshields** [comment]
@apolcyn can you double-check the builds for mingw? When I try to install them on Windows using Ruby 3.1 my machine is trying to build from source. Mingw gem size is at ~3.5 MB which seems significantly smaller than the linux and darwin builds ~12 MB, so possibly missing the binaries?

**Comment by johnnyshields** [comment]
Huh strange... when I install as `gem install --local grpc-1.46.2-x64-mingw32.gem` it works fine. `gem install grpc` tries to build from source. Possibly not detecting platform correctly?

**Comment by nicolasnoble** [comment]
FWIW, the platform detection is done by `gem` itself, and it's a fairly undocumented and obscure process.

**Comment by johnnyshields** [comment]
OK, I think I found the issue:

```
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x64-mingw32]

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
```

Notice the `ucrt` in the latter. This is plausible as to why it wouldn't be picking up the `x64-mingw32` binary. Seems to be related to this in Ruby Windows Installer: https://github.com/ruby/setup-ruby/issues/193.

Nokogiri is providing an `x64-mingw-ucrt` build. Will raise a ticket for GRPC to do the same.
https://rubygems.org/gems/nokogiri/versions/1.13.6-x64-mingw-ucrt

**Comment by johnnyshields** [comment]
Ok, raised https://github.com/grpc/grpc/issues/29666

**Comment by nicolasnoble** [comment]
Yup, thanks for the investigation.
