### ISSUE TITLE
Error compiling grpc (make: *** [Makefile:810: /root/grpc/objs/opt/src/core/ext/filters/client_channel/channel_connectivity.o] Error 1)

### ISSUE THREAD

**Issue by iqbalme** [grpc/grpc#29092]
### What version of gRPC and what language are you using?
gRPC v1.44.0 and PHP 8.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc v9.4.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I did this command
"EXTRA_DEFINES=GRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK make"

### What did you expect to see?
I want to see free error instalation

### What did you see instead?
`a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/err_data.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_bitstr.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_bool.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_d2i_fp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_dup.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_enum.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_gentm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_i2d_fp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_int.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_mbstr.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_object.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_octet.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_print.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_strex.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_strnid.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_time.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_type.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_utctm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/a_utf8.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/asn1_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/asn1_par.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/asn_pack.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/f_int.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/f_string.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/tasn_dec.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/tasn_enc.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/tasn_fre.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/tasn_new.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/tasn_typ.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/tasn_utl.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/asn1/time_support.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/base64/base64.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/bio.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/bio_mem.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/connect.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/fd.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/file.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/hexdump.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/pair.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/printf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/socket.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/socket_helper.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/blake2/blake2.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bn_extra/bn_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bn_extra/convert.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/buf/buf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bytestring/asn1_compat.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bytestring/ber.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bytestring/cbb.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bytestring/cbs.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bytestring/unicode.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/chacha/chacha.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/cipher_extra.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/derive_key.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_aesccm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_aesctrhmac.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_aesgcmsiv.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_chacha20poly1305.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_null.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_rc2.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_rc4.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/e_tls.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cipher_extra/tls_cbc.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cmac/cmac.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/conf/conf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-aarch64-fuchsia.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-aarch64-linux.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-aarch64-win.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-arm-linux.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-arm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-intel.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/cpu-ppc64le.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/crypto.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/curve25519/curve25519.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/curve25519/spake25519.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/dh_extra/dh_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/dh_extra/params.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/digest_extra/digest_extra.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/dsa/dsa.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/dsa/dsa_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/ec_extra/ec_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/ec_extra/ec_derive.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/ec_extra/hash_to_curve.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/ecdh_extra/ecdh_extra.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/ecdsa_extra/ecdsa_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/engine/engine.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/err/err.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/digestsign.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/evp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/evp_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/evp_ctx.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_dsa_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_ec.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_ec_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_ed25519.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_ed25519_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_rsa.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_rsa_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_x25519.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/p_x25519_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/pbkdf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/print.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/scrypt.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/evp/sign.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/ex_data.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/fipsmodule/bcm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/fipsmodule/fips_shared_support.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/hkdf/hkdf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/hpke/hpke.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/hrss/hrss.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/lhash/lhash.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/mem.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/obj/obj.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/obj/obj_xref.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_all.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_info.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_oth.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_pk8.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_pkey.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pem/pem_xaux.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pkcs7/pkcs7.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pkcs7/pkcs7_x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pkcs8/p5_pbev2.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pkcs8/pkcs8.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pkcs8/pkcs8_x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/poly1305/poly1305.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/poly1305/poly1305_arm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/poly1305/poly1305_vec.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/pool/pool.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rand_extra/deterministic.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rand_extra/forkunsafe.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rand_extra/fuchsia.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rand_extra/passive.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rand_extra/rand_extra.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rand_extra/windows.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rc4/rc4.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/refcount_c11.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/refcount_lock.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rsa_extra/rsa_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/rsa_extra/rsa_print.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/siphash/siphash.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/stack/stack.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/thread.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/thread_none.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/thread_pthread.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/thread_win.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/trust_token/pmbtoken.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/trust_token/trust_token.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/trust_token/voprf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/a_digest.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/a_sign.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/a_verify.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/algorithm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/asn1_gen.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/by_dir.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/by_file.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/i2d_pr.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/name_print.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/rsa_pss.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/t_crl.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/t_req.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/t_x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/t_x509a.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_att.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_cmp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_d2.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_def.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_ext.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_lu.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_obj.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_req.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_set.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_trs.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_txt.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_v3.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_vfy.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509_vpm.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509cset.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509name.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509rset.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x509spki.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_algor.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_all.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_attrib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_crl.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_exten.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_info.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_name.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_pkey.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_pubkey.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_req.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_sig.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_spki.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_val.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509/x_x509a.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/pcy_cache.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/pcy_data.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/pcy_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/pcy_map.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/pcy_node.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/pcy_tree.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_akey.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_akeya.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_alt.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_bcons.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_bitst.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_conf.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_cpols.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_crld.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_enum.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_extku.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_genn.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_ia5.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_info.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_int.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_ncons.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_ocsp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_pci.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_pcia.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_pcons.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_pmaps.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_prn.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_purp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_skey.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/x509v3/v3_utl.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/bio_ssl.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/d1_both.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/d1_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/d1_pkt.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/d1_srtp.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/dtls_method.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/dtls_record.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/encrypted_client_hello.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/extensions.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/handoff.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/handshake.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/handshake_client.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/handshake_server.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/s3_both.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/s3_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/s3_pkt.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_aead_ctx.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_asn1.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_buffer.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_cert.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_cipher.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_file.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_key_share.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_lib.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_privkey.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_session.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_stat.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_transcript.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_versions.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/ssl_x509.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/t1_enc.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/tls13_both.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/tls13_client.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/tls13_enc.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/tls13_server.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/tls_method.o
a - /root/grpc/objs/opt/third_party/boringssl-with-bazel/src/ssl/tls_record.o
[CXX]     Compiling src/core/ext/filters/census/grpc_context.cc
[CXX]     Compiling src/core/ext/filters/client_channel/backend_metric.cc
[CXX]     Compiling src/core/ext/filters/client_channel/backup_poller.cc
[CXX]     Compiling src/core/ext/filters/client_channel/channel_connectivity.cc
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [Makefile:810: /root/grpc/objs/opt/src/core/ext/filters/client_channel/channel_connectivity.o] Error 1`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by stanley-cheung** [comment]
We have tests running for PHP 8.0 and this doesn't seem like an issue anymore.
