### ISSUE TITLE
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) on apple M1 chip

### ISSUE THREAD

**Issue by vikrampunchh** [grpc/grpc#29100]
`dlopen(/Users/vikram/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.6/grpc_c.bundle, 0x0009): tried: '/Users/vikram/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.6/grpc_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/grpc_c.bundle' (no such file), '/usr/lib/grpc_c.bundle' (no such file) - /Users/vikram/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/2.6/grpc_c.bundle (LoadError)
`

Ruby version: 2.6.5

**Comment by vikrampunchh** [comment]
**Thanks @JamesHageman** 

But it's not working for me.

**Comment by jpfourny** [comment]
Try this:

1. Uninstall existing grpc GEM
2. `bundle config set force_ruby_platform true`
3. `bundle install` *should* build locally now (assuming with have clang toolchain and everything)

**Comment by jjworren** [comment]
@vikrampunchh afaik you need 2.6.9, but it does not work at least up to 2.6.6 (I did not test 2.6.7 & 2.6.8)

**Comment by myatsuphyo** [comment]
Thank you @JamesHageman  Your solution works with ruby 2.6.8 and macOS Monterey version 12.2.1. After running `bundle config set force_ruby_platform true`, it was necessary to run `bundle install` again for me.

**Comment by patrickbadleyupstart** [comment]
While this workaround does seem to work, are their plans to fix this in the near future?  Uninstalling, changing a config, and reinstalling isn't ideal especially for larger teams.

**Comment by LeviLong01** [comment]
The steps listed do not work for me. Bundler is on latest version as well.

**Comment by haines** [comment]
This is fixed in v1.46.2 🎉

**Comment by Piyush-Chaudhary** [comment]
Finally running below resolves

1. `arch -arm64e gem install nokogiri -v '1.13.6' --platform=ruby -- --use-system-libraries`
2. `bundle`

**Comment by jigarbhatt271** [comment]
> 1. gem install nokogiri

its not working for me.

**Comment by VishakhaOhal31** [comment]
My ruby version 2.7.4

But it's not working for me.

Even if bundle install is successful, it keep getting below error:
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by alto-ruby** [comment]
This should not happen with the latest release any more, though the installation will take some time as the extension needs to be compiled.
We cannot distribute pre-built extensions for mac arm yet because signature is required.
