### ISSUE TITLE
Make sure the way we construct URI used for JWT access token is consistent across languages.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2911]
# STATUS: don't implement the functionality yet, needs more thought. 

We should have a unified way authUri (the Audience field) for JWT access token is created from channel target:

-- remove optional "dns:///" prefix
-- remove optional ":number" port suffix
-- add "https://" prefix   
-- add fully qualified service name

Please follow reference implementation in Node:
https://github.com/grpc/grpc/pull/2901/files#diff-e5ada239817cf2b845febcf5c7be68f0R552

The resulting URI should be in form: 
https://grpc-test.sandbox.google.com/grpc.testing.TestService
any different form will be rejected by ESF.

**Comment by jtattermusch** [comment]
@jboeuf  for C++  and to bless this approach.

@nathanielmanistaatgoogle , @stanley-cheung, @tbetbetbe for their languages.

**Comment by jtattermusch** [comment]
@ejona86  FYI

**Comment by jtattermusch** [comment]
For Node this was implemented by #2901

**Comment by jtattermusch** [comment]
@iamqizhao (Go) FYI

**Comment by ejona86** [comment]
Shouldn't we only remove the port number if it is 443?

**Comment by ctiller** [comment]
Let's make this part of core, to centralize how this gets implemented a
little. Zookeeper targets (for example) will likely have a different
algorithm than is presented here.

**Comment by jtattermusch** [comment]
@ctiller, zookeeper is not going to be used for google APIs which is what we mostly care about for now, right?
What you're saying is worth considering, but implementing at least this basic approach with makes sure that user will be able to access google apis without problems sounds like a good idea to me.

**Comment by ctiller** [comment]
The approach is unmaintainable for the same reasons as we introduced code
to supply the default host to calls... any work in this direction is going
to need to be ripped out and replaced in short order. dns:/// really is
just one way that targets are named with grpc (and may not even end up
being the most common way) - cementing it as the only way within our
wrapped languages seems like a losing move.

Could someone perhaps stub out a function in C89 that does this, and we can
work on the integration and full design later?

**Comment by jboeuf** [comment]
I think that we should have a short meeting on the issue early next week. I'll schedule something.

**Comment by jtattermusch** [comment]
Ok, looks like this is a much bigger issue than I originally thought. Thanks for the pushback guys and let's try to figure out what exactly the behavior around auth_uri should be in the meeting next week.

**Comment by ctiller** [comment]
Taking this one today.

**Comment by tbetbetbe** [comment]
Closing, as been superceded by #3826
