### ISSUE TITLE
Disable protobuf and protoc installation from libgrpc

### ISSUE THREAD

**Issue by babuveld** [grpc/grpc#29129]
Hi,

Am doing source install of libgrpc-1.32.0 on ubuntu-20.04. It already has the right protoc(3.13.0) and libprotobuf-3.13.0 versions installed on the system.

Is there a way to disable the compilation/install of protobuf and protoc libraries so I don't overwrite those existing libraries when libgrpc is installed?

**Comment by donnadionne** [comment]
For the future, please direct general question like this one to  https://stackoverflow.com/search?tab=newest&q=grpc%20is%3aquestion

**Comment by babuveld** [comment]
I figured out myself. All I needed was this https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.sh updating it here so it would be useful for someone.

<Snip from code>

# Providers for third-party dependencies (gRPC_*_PROVIDER properties):
# "module": build the dependency using sources from git submodule (under third_party)
# "package": use cmake's find_package functionality to locate a pre-installed dependency

</Snip>
