### ISSUE TITLE
Loading DLL within a Callback call, breaks callback functionality

### ISSUE THREAD

**Issue by ikaryoti** [grpc/grpc#29135]
### What version of gRPC and what language are you using?

C++, grpc 1.43.0

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC

### What did you do?

1. Created a service that capitalizes a string, this service implements grpc::Service
2. Created a callback service method as follows
        extension7::stringValue request;
        extension7::stringValue response1, response2;
        request.set_stringcontent("helloworld");

        ::grpc::internal::CallbackUnaryHandler< ::extension7::stringValue, ::extension7::stringValue>* callbackHandler 
            = new grpc::internal::CallbackUnaryHandler< ::extension7::stringValue, ::extension7::stringValue>
            ([service](::grpc::CallbackServerContext* context, const ::extension7::stringValue* request, ::extension7::stringValue* response) { return service->Capitalize(context, request, response); });
        grpc::internal::RpcServiceMethod* serviceMethod = new grpc::internal::RpcServiceMethod("/extension7.ExtensionDll/Capitalize", grpc::internal::RpcMethod::RpcType::NORMAL_RPC, callbackHandler);
        serviceMethod->SetServerApiType(grpc::internal::RpcServiceMethod::ApiType::CALL_BACK);
        service->AddServiceMethod(serviceMethod);
3. Registered service as an 'inproc' service
       grpc::ServerBuilder builder;
       builder.RegisterService("inproc", service); 
4. Created an 'inproc' channel
5. Created a client unary reactor for the service, the client reactor uses a TemplatedGenericStub and runs the following code
        stub->PrepareUnaryCall(context, methodName, grpc::StubOptions(), request, response, this);
        StartCall();
Its OnDone callback, prints out a success or failure message based on the obtained Status

The service implementation loads a DLL that exports a factory to create an object that implements the method.

The callback is successfully called on the completion of the call, only if the DLL is loaded before the actual call and not within the call.

### What did you expect to see?

The callback to get successfully invoked upon completion of the service call.

### What did you see instead?

The callback is invoked before the actual call gets completed, with a 'Transport Closed' status error.

**Comment by nicolasnoble** [comment]
I understand the concept of what you're trying to do, but unfortunately, our codebase is really not very tuned for this. DLLs on Windows have issues with regards to how memory is allocated and how global objects are accessed, and we take really no care in our C++ surface API to cater for this specific usage case. I doubt this is something we'll ever be able to fix properly, yet alone maintain.

This should work if everything is built statically. Please re-open a new issue if this isn't the case.
