### ISSUE TITLE
Conceptual mismatch on service-side message reading

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#2916]
At this time the grpc._adapter._intermediary_low API for service-side reads is "always be reading, and when a read comes back empty that indicates the invocation-side having finished its writes". That API interferes with the "only read when the application has granted allowance to read" semantics of how we're doing flow control at the links layer, and I'm resolving it for now by introducing capacity for a stored read ("early_read") inside the grpc._links.service._RPCState object. Doing so solves the problem for now, but is a convolution, and it would be nice to come along later and align the lower-level API with the semantics of the higher-level API so that the code in between were simpler and more direct.

**Comment by soltanmm** [comment]
This will be nice-er-ish once the adapter-of-adapter-of-adapter layers are squashed together.

**Comment by nathanielmanistaatgoogle** [comment]
Obviated by GA changes.
