### ISSUE TITLE
Memory leak in upb in master

### ISSUE THREAD

**Issue by AustinSchuhBRT** [grpc/grpc#29193]
https://github.com/protocolbuffers/upb/commit/aa779cd779b660e3e4f6560519827bfb15a7b488 fixes a memory leak in upb.  Master (as of today, as well as 1.45.0) depends on an older version without this fix.

We are using Bazel to build gRPC and caught this using our asan build.  We were successfully able to update upb locally to get it to work again, but would appreciate not carrying that patch long term.

**Comment by markdroth** [comment]
Esun, can we upgrade upb to pick up this fix?

**Comment by veblush** [comment]
Sure! I'm going to upgrade upb.
