### ISSUE TITLE
Is gRPC impacted by recent OpenSSL vulnerability ?

### ISSUE THREAD

**Issue by etiennearnal** [grpc/grpc#29211]
I know that gRPC is based on [boringssl](https://boringssl.googlesource.com/boringssl/), a fork of OpenSSL by Google. 
I'm using gRPC 1.42 and I just want to know if I am impacted by recent OpenSSL [vulnerabilities](https://www.openssl.org/news/vulnerabilities.html).

**Comment by ZhenLian** [comment]
Hi, thanks for bringing up this question.
gRPC is based on either BoringSSL or OpenSSL, depending on how you build your system. If your gRPC uses BoringSSL, then it is not impacted by this vulnerability, as we just confirmed by the BoringSSL team; if you depend on OpenSSL, then you will need to upgrade your OpenSSL version to at least 1.1.1n or 3.0.2, released on the 15th March 2022 - as these are the two versions in which they fixed that problem. 
Feel free to let me know any other questions you might have. Thank you so much!

**Comment by etiennearnal** [comment]
Thanks a lot @ZhenLian for this clear and detailed explanation. Fortunately I rely on BoringSSL.
