### ISSUE TITLE
GRPC call fails when the code is generated with protobuf==3.17.3

### ISSUE THREAD

**Issue by wanjuntham** [grpc/grpc#29223]
### What version of gRPC and what language are you using?
gRPC v1.44.0 Python

### What operating system (Linux, Windows,...) and version?

Linux Debian 11

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.10.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

1. Update `grpcio-tools` from v1.43.0 to v1.44.0.
2. Install `protobuf` version `3.17.3`.
3. Generate code with `grpc_tools.protoc`.
4. Make gRPC client calls.

### What did you expect to see?

It should not throw any error since in grpcio-tools, it is specified with `protobuf [required: >=3.5.0.post1,<4.0dev]`

### What did you see instead?

Error when making gRPC calls as a client.
```
GETCONFIGREQUEST = DESCRIPTOR.message_types_by_name['GetConfigRequest']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
n/a

**Comment by gnossen** [comment]
Thanks for pointing this out! https://github.com/grpc/grpc/pull/29257 should resolve this.
