### ISSUE TITLE
When CancelledError is raised during request handling, the requesting client hangs indefinitely

### ISSUE THREAD

**Issue by libka-b** [grpc/grpc#29248]
### What version of gRPC and what language are you using?

Python
grpcio == 1.45.0

### What operating system (Linux, Windows,...) and version?

Linux - Fedora 35

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.9.10

### What did you do?

Cancel server request handling using `asyncio.CancelledError` while processing a request results in not processing the request in any way - no notice for the client either connection close, some error sent over wire, nothing.

Minimal reproduction steps:
proto:
```
syntax = "proto3";

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

Server code:
```
import asyncio
from typing import Any

from grpc.aio import server

from greeter_pb2_grpc import GreeterServicer, add_GreeterServicer_to_server
from greeter_pb2 import HelloReply, HelloRequest


class Service(GreeterServicer):

    async def SayHello(self, request: HelloRequest, context: Any) -> HelloReply:
        raise asyncio.exceptions.CancelledError("whatever")


async def main() -> None:
    grpc_server = server()
    add_GreeterServicer_to_server(Service(), grpc_server)
    grpc_server.add_insecure_port("0.0.0.0:8080")
    await grpc_server.start()
    await grpc_server.wait_for_termination()


if __name__ == "__main__":
    asyncio.run(main())

```

Client code:
```
import asyncio

from grpc.aio import insecure_channel

from greeter_pb2_grpc import GreeterStub
from greeter_pb2 import HelloReply, HelloRequest


async def main() -> None:
    channel = insecure_channel("127.0.0.1:8080")
    stub = GreeterStub(channel)
    response: HelloReply = await stub.SayHello(HelloRequest(name="ferda"))
    print(response)


if __name__ == "__main__":
    asyncio.run(main())

```

First run server, then run client

### What did you expect to see?

`StreamTerminatedError` on client side

### What did you see instead?

Client hangs indefinitely waiting for response

### Anything else we should know about your project / environment?

This is just a minimal example of a code where this happens, that's why I'm raising the `CancelledError` there. In our production service the `CancelledError` seems to be raised by server request handler, but the result is the same

**Comment by lidizheng** [comment]
@libka-b Thanks for the repro case, I can reproduce the exactly same behavior. This is one of the corner cases where native AsyncIO API semantic conflicts with gRPC's API semantic. The AsyncIO `CancelledError` can be generated when the coroutine is cancelled by event loop, in events like event loop shutdown. At that stage, it's unsafe to perform other IO operations, e.g. sending trailers down to wire. You can find the processing logic here:

https://github.com/grpc/grpc/blob/f7d4f8e13cf80b22355169d69838d13ecb146214/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi#L696-L698

gRPC AsyncIO API provides the `abort` function on the servicer context: https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.ServicerContext.abort. This API allows the method handler to abort current execution with non-OK RPC status code.

```
    async def SayHello(self, request: HelloRequest, context: Any) -> HelloReply:
        await context.abort(grpc.StatusCode.CANCELLED)
```

**Comment by libka-b** [comment]
So if I get this right, the correct way to target this would be to set some timeouts on the client side, as it can happen that no response will arrive to client, as handling `CancelledError` in the method might lead to trying to send a response (even in case of `abort`) on closing event loop. Is that correct?

**Comment by lidizheng** [comment]
It depends on the use cases. If the intention is asking the server to return a `CANCELLED` status code, you can use the abort API. If the raise of `CancelledError` is not controlled by the application, the server might need to process it (selecting the user generated ones, then abort, like the [guide](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError) suggested).

Timeout on client side works. Handling the application raised `CancelledError` is technically the method handler's job.
