### ISSUE TITLE
Looking for c++ example of custom token based authentication with grpc?

### ISSUE THREAD

**Issue by MouniK19** [grpc/grpc#29260]
I am looking for a C++ server/client example using custom token based authentication. So far my search does not return useful results yet. Preferably, I would like to have more concrete example with enough details that is ready to build and test. For example, something like this one https://github.com/grpc/grpc/issues/9593. I wonder if you have something similar but only with SSL/TLS authentication replaced with token authentication.

**Comment by nicolasnoble** [comment]
This is an advanced topic, so we don't necessarily have an example on-hand. However, https://grpc.io/docs/guides/auth/#extending-grpc-to-support-other-authentication-mechanisms has some code snippets, and we have [test code](https://github.com/grpc/grpc/blob/master/test/cpp/end2end/end2end_test.cc#L136-L185) that exercises the feature, if this of help to you.
