### ISSUE TITLE
Symlinks in the repository to share `*.proto`s

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#2929]
Specifically to address concerns first raised in #526.

Yay, nay, reasons for, reasons against? Questions raised?

**Comment by nathanielmanistaatgoogle** [comment]
Yay. Alternative means to accomplish the same task would be... duplicated resources in source control? Or convoluted make/other-build-tool rules to create copies at build-time?

**Comment by murgatroid99** [comment]
[This StackOverflow question](http://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows) indicates that symlinks do not download as such on Windows.

**Comment by nicolasnoble** [comment]
Yes, please do not use symlinks.

**Comment by nicolasnoble** [comment]
Also, I'd rather have the proto files in src/proto for instance.

**Comment by soltanmm** [comment]
If we put everything in a centralized location, we'd need to have build tool support *anyway* for languages that require in-tree and directory-structured `.proto` files (e.g. Python). At that point, what's keeping us from using solutions akin to e.g. [this](http://stackoverflow.com/a/16754068/1467466) on Windows?

**Comment by nicolasnoble** [comment]
What's preventing us is indeed custom git stuff. The problem is that we are a public repository, and we can't force everyone who's going to clone from us to tweak / mangle their git installation.

**Comment by soltanmm** [comment]
Works for me.
