### ISSUE TITLE
grpc keepalive watchdog timeout

### ISSUE THREAD

**Issue by shuimu13** [grpc/grpc#29300]
### What version of gRPC and what language are you using?
v1.45.1

### What operating system (Linux, Windows,...) and version?
ubuntu:18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC

### What did you do?
After the gRPC times out, no operation is seen to start ping. As a result, the program exits.

### What did you expect to see?
After the gRPC times out, no operation is seen to start ping. As a result, the program exits.

GRPC_ARG_KEEPALIVE_TIME_MS = 60s

GRPC_ARG_KEEPALIVE_TIMEOUT_MS = 20s ( The default value )

After the 80s, there was no ping alive operation, resulting in the program quitting.

### Anything else we should know about your project / environment?
This is my test code:

https://github.com/shuimu13/grpc-keepalive-watchdog-timeout

**Comment by yashykt** [comment]
so, some comments based on the reproduction -
`GRPC_TRACE` is what needs to be set, and not `GRPC_TRACES`. That is the reason why you are not seeing the proof of the ping being sent/received. 
Also, I noticed that you are using C++ sync API on the client with keepalive pings being sent from the server too. The sync based API on the client side does not deal with keepalive pings very well, since we do not guarantee that there are always threads polling the underlying file descriptors. Please try using the callback api instead.

**Comment by yashykt** [comment]
After running your example, I noticed that the client does receive and respond to the pings, but the server does not read anything. Turns out that the CQ driver thread in your example goes into a loop where it sleeps for 5 seconds, writes a message, gets a notification for the write completion and then sleeps again.. It doesn't seem to be getting the opportunity to read.

I would suggest separating the threads performing the sleep/write and the one driving the completion queue. That should fix the issue that you are seeing.

**Comment by shuimu13** [comment]
@yashykt 

Thanks for your advice. I have tried as follows:

**(1) When I remove the sleep time, I can actually see the client ping every 10 seconds.**
root@c1d141b2db7e:/data# ./client
I0406 03:36:18.524983093     581 ev_epoll1_linux.cc:121]     grpc epoll fd: 3
D0406 03:36:18.525089879     581 ev_posix.cc:172]            Using polling engine: epoll1
D0406 03:36:18.525122632     581 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0406 03:36:18.525147178     581 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0406 03:36:18.525155603     581 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0406 03:36:18.525158105     581 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0406 03:36:18.525160117     581 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0406 03:36:18.525171840     581 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D0406 03:36:18.525179834     581 dns_resolver_ares.cc:619]   Using ares dns resolver
D0406 03:36:18.525206213     581 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0406 03:36:18.525221998     581 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0406 03:36:18.525226300     581 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0406 03:36:18.525243662     581 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0406 03:36:18.525258949     581 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
I0406 03:36:18.525754484     581 socket_utils_common_posix.cc:429] Disabling AF_INET6 sockets because ::1 is not available.
I0406 03:36:18.526611426     581 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:20.062828017     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:20.162897717     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:21.563618538     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:23.669631616     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:26.718590540     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:31.494579175     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:39.164547000     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:47.981703555     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:36:55.502587197     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2
I0406 03:37:04.782840403     584 writing.cc:131]             CLIENT: Ping sent [ipv4:127.0.0.1:50055]: 2/2


**(2) When I tried to change the sleep time to 1us, the program still quit after 80s.**
This means that if I want to maintain a long connection, the client and server have to keep sending data, with no sleep in between.

**Comment by yashykt** [comment]
As I said previously, on the server side, if you use a dedicated thread that drives the completion queue and use a separate thread for performing work such as sleep, it should solve your immediate problem. You shouldn't need to continuously send data.

I would also recommend trying out the callback API which might make the implementation simpler and easier to understand.
