### ISSUE TITLE
Cannot check peer: missing selected ALPN property in Grpc Core client

### ISSUE THREAD

**Issue by benfranklin79** [grpc/grpc#29331]
### What version of gRPC and what language are you using?

Grpc Core 2.41.0

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

netcoreapp3.1

### What did you do?

See description in https://github.com/googleapis/google-cloud-dotnet/issues/8315 for what I ran. I ran a version of this in a simplified console application. I'm working behind a company VPN Zscaler and I have setup the environment variable `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` as was suggested in the above issue.

### What did you expect to see?

I expected to retrieve the secrets 

### What did you see instead?

I got the exception described in https://github.com/googleapis/google-cloud-dotnet/issues/8315. Then I setup the debug variables as recommended:

```
GRPC_TRACE=all
GRPC_VERBOSITY=DEBUG
```

I re-ran the application and got the following output

```
I0406 11:52:40.189461 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_hello_retr  - !!!!!!
I0406 11:52:40.189570 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_server_hel  - !!!!!!
I0406 11:52:40.189833 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_encrypted_  - !!!!!!
I0406 11:52:40.189903 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_certificat  - !!!!!!
I0406 11:52:40.190047 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_server_cer  - !!!!!!
I0406 11:52:40.190361 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_server_cer  - !!!!!!
I0406 11:52:40.190751 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client read_server_fin  - !!!!!!
I0406 11:52:40.190854 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client send_end_of_ear  - !!!!!!
I0406 11:52:40.190995 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client send_client_enc  - !!!!!!
I0406 11:52:40.191134 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client send_client_cer  - !!!!!!
I0406 11:52:40.191281 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS 1.3 client complete_second  - !!!!!!
I0406 11:52:40.191448 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP -            TLS 1.3 client done  - !!!!!!
I0406 11:52:40.191846 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP - TLS client finish_client_hands  - !!!!!!
I0406 11:52:40.193175 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:                 LOOP -                TLS client done  - !!!!!!
I0406 11:52:40.193332 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:223:       HANDSHAKE DONE -                TLS client done  - !!!!!!
I0406 11:52:40.193552 0 ..\..\..\src\core\lib\iomgr\tcp_windows.cc:363: WRITE
000002374C08AE60 (peer=ipv4:XXXXX): XXXXX
D0406 11:52:40.194096 0 ..\..\..\src\core\lib\security\transport\security_handshaker.cc:184: Security handshake failed: {"created":"@1649242360.194000000","description":"Cannot check peer: missing selected ALPN property.","file":"..\..\..\src\core\lib\security\security_connector\ssl_utils.cc","file_line":162}

I0406 11:52:40.194405 0 ..\..\..\src\core\lib\channel\handshaker.cc:89: handshake_manager 000002374C0841E0: error={"created":"@1649242360.194000000","description":"Cannot check peer: missing selected ALPN property.","file":"..\..\..\src\core\lib\security\security_connector\ssl_utils.cc","file_line":162} shutd
own=0 index=2, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0406 11:52:40.194771 0 ..\..\..\src\core\lib\channel\handshaker.cc:122: handshake_manager 000002374C0841E0: handshaking complete -- scheduling on_handshake_done with error={"created":"@1649242360.194000000","description":"Cannot check peer: missing selected ALPN property.","file":"..\..\..\src\core\lib\secur
ity\security_connector\ssl_utils.cc","file_line":162}
I0406 11:52:40.195076 0 ..\..\..\src\core\lib\iomgr\timer_generic.cc:450: TIMER 000002374C084248: CANCEL pending=true
I0406 11:52:40.195417 0 ..\..\..\src\core\lib\iomgr\resource_quota.cc:840: RU '142.251.39.106:443' (000002374C0EAE80) unreffing: 1 -> 0
I0406 11:52:40.195588 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:1012: Connect failed: {"created":"@1649242360.194000000","description":"Cannot check peer: missing selected ALPN property.","file":"..\..\..\src\core\lib\security\security_connector\ssl_utils.cc","file_line":162}
I0406 11:52:40.195955 0 ..\..\..\src\core\ext\filters\client_channel\client_channel.cc:626: chand=000002374C083CF0: connectivity change for subchannel wrapper 000002374C1F1AE0 subchannel 000002374C12FC50; hopping into work_serializer
I0406 11:52:40.196144 0 ..\..\..\src\core\ext\filters\client_channel\client_channel.cc:661: chand=000002374C083CF0: processing connectivity change in work serializer for subchannel wrapper 000002374C1F1AE0 subchannel 000002374C12FC50 watcher=000002374C6DFE10
I0406 11:52:40.196322 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:243: [pick_first 000002374C085720] subchannel list 000002374C1F6E90 index 0 of 2 (subchannel 000002374C1F1AE0): connectivity changed: state=TRANSIENT_FAILURE, shutting_do

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by benfranklin79** [comment]
Hi @jtattermusch , any idea when this will get looked at?

**Comment by jtattermusch** [comment]
CC @gnossen @lidizheng

**Comment by jtattermusch** [comment]
FTR The error basically says that the `ssl_alpn_selected_protocol` property is missing:
https://github.com/grpc/grpc/blob/93d47104daa789046b1d79db23faf52747450f58/src/core/tsi/ssl_transport_security.h#L44
https://github.com/grpc/grpc/blob/659a02aba06f5ef7f0d1eab8da64bcce60d85f30/src/core/lib/security/security_connector/ssl_utils.cc#L135

@yihuazhang  as the code was last modified here: https://github.com/grpc/grpc/commit/b017c801b683d47160bdb3f98c19124fcbd1fc0a#diff-9d5817eec5e34f707b945d95165801ec616aeb5893fc15233a77470b68e9720fR119

**Comment by jtattermusch** [comment]
At this point it's unclear whether this is actually a problem in gRPC. It could simply be that ZScaler basically does MITM (since it terminates the TLS connection and has a proxy connect to the actual backend) which then leads to TLS/ALPN issues with grpc.
It would be worth checking if your ZScaler setup actually support HTTP/2 with TLS and gRPC with TLS.

Conversations [here](https://github.com/grpc/grpc/issues/23172#issuecomment-909355285) might indicate that you may need to fine tune the certificates you're using (have you tried that?).

**Comment by jtattermusch** [comment]
@benfranklin79  can you share some details on what's the origin of the CA roots file you used for `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH`? Is that a CA roots file provided by the admins of your ZScaler instance?

**Comment by benfranklin79** [comment]
@jtattermusch Thanks for the response on this. Next week I will discuss this with our secops team and see what they say.

**Comment by benfranklin79** [comment]
@jtattermusch the CA roots file is provided by the admins of the Zscaler instance

**Comment by benfranklin79** [comment]
@jtattermusch I've confirmed with the admins that Zscaler does support HTTP2 and does MITM the traffic

**Comment by benfranklin79** [comment]
@jtattermusch Zscaler admins have confirmed that what I'm using for GRPC_DEFAULT_SSL_ROOTS_FILE_PATH is the CA roots file

**Comment by benfranklin79** [comment]
@jtattermusch For details on origin of roots file:

![ca_root](https://user-images.githubusercontent.com/3197935/165720239-1615c1c6-13cb-4822-a11b-275bc7fdcf9b.png)

**Comment by jtattermusch** [comment]
@benfranklin79  thanks for the update. As posted above, conversations [here](https://github.com/grpc/grpc/issues/23172#issuecomment-909355285) might indicate that you may need to fine tune the certificates you're using (have you tried that?).
Also, did you verify that Zscaler supports ALPN?

**Comment by benfranklin79** [comment]
@jtattermusch fine tunning the certificate is something the admin team seems reluctant to do right now, but we did find the following line in the debug logs:

```
I0428 09:14:54.291050 0 ..\..\..\src\core\lib\security\credentials\ssl\ssl_credentials.cc:140: grpc_ssl_credentials_create(pem_root_certs=(null), pem_key_cert_pair=00000000000
00000, verify_options=0000000000000000, reserved=0000000000000000)
```

I can't send the whole debug file over because there might be sensitive info in there but this is currently making Zscaler admins think that the cert file is not being picked up which is baffling because I've definitely setup `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH`

I've asked about ALPN

**Comment by benfranklin79** [comment]
@jtattermusch yes ALPN is supported

**Comment by jtattermusch** [comment]
@benfranklin79 that log line doesn't necessarily indicate a problem, since C# can create the "default" credentials via grpc_ssl_credentials_create() with the default null args and then C-core should pick up the "default" roots.pem, but you've overridden it via "GRPC_DEFAULT_SSL_ROOTS_FILE_PATH", so you should still end up with the roots. pem you configured.

How exactly did you setup the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH variable?
Note that setting via `Environment.SetEnvironmentVariable` might not work (e.g. see https://github.com/grpc/grpc/issues/14963).

Also, you can explicitly use your custom ssl roots through 

`new SslCredentials(pathToYourCustomRoots)`
https://github.com/grpc/grpc/blob/730599bd5b68f12436907cd96ab3fb20579734e7/src/csharp/Grpc.IntegrationTesting/TestCredentials.cs#L65
and then using those `sslCredentials` when creating a channel.

**Comment by jtattermusch** [comment]
@ZhenLian  can you please provide some insight on what could be wrong when the "ssl_alpn_selected_protocol" property is missing after a handshake? `Cannot check peer: missing selected ALPN property.","file":"..\..\..\src\core\lib\security\security_connector\ssl_utils.cc","file_line":162}`.
Could it be that the custom roots.pem is misconfigured?
It may be that the error produced just isn't helpful enough to identify the rootcause.

**Comment by benfranklin79** [comment]
> @benfranklin79 that log line doesn't necessarily indicate a problem, since C# can create the "default" credentials via grpc_ssl_credentials_create() with the default null args and then C-core should pick up the "default" roots.pem, but you've overridden it via "GRPC_DEFAULT_SSL_ROOTS_FILE_PATH", so you should still end up with the roots. pem you configured.
> 
> How exactly did you setup the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH variable? Note that setting via `Environment.SetEnvironmentVariable` might not work (e.g. see #14963).
> 
> Also, you can explicitly use your custom ssl roots through
> 
> `new SslCredentials(File.ReadAllText(pathToYourCustomRoots))`
> 
> https://github.com/grpc/grpc/blob/730599bd5b68f12436907cd96ab3fb20579734e7/src/csharp/Grpc.IntegrationTesting/TestCredentials.cs#L65
> 
> 
> and then using those `sslCredentials` when creating a channel.

I set the variable in windows via `Environment Variables` dialog box.

**Comment by benfranklin79** [comment]
> @benfranklin79 that log line doesn't necessarily indicate a problem, since C# can create the "default" credentials via grpc_ssl_credentials_create() with the default null args and then C-core should pick up the "default" roots.pem, but you've overridden it via "GRPC_DEFAULT_SSL_ROOTS_FILE_PATH", so you should still end up with the roots. pem you configured.
> 
> How exactly did you setup the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH variable? Note that setting via `Environment.SetEnvironmentVariable` might not work (e.g. see #14963).
> 
> Also, you can explicitly use your custom ssl roots through
> 
> `new SslCredentials(File.ReadAllText(pathToYourCustomRoots))`
> 
> https://github.com/grpc/grpc/blob/730599bd5b68f12436907cd96ab3fb20579734e7/src/csharp/Grpc.IntegrationTesting/TestCredentials.cs#L65
> 
> 
> and then using those `sslCredentials` when creating a channel.

Not sure how useful this is going to be since I'm using this library via the library: https://github.com/googleapis/google-cloud-dotnet

**Comment by benfranklin79** [comment]
> @ZhenLian can you please provide some insight on what could be wrong when the "ssl_alpn_selected_protocol" property is missing after a handshake? `Cannot check peer: missing selected ALPN property.","file":"..\..\..\src\core\lib\security\security_connector\ssl_utils.cc","file_line":162}`. Could it be that the custom roots.pem is misconfigured? It may be that the error produced just isn't helpful enough to identify the rootcause.

@ZhenLian @jtattermusch any progress on this? I think an answer to this would be useful

**Comment by ZhenLian** [comment]
Sorry for the delay. I am just back from vacation.
ALPN missing is considered as a severe failing: if the ALPN fails, the handshake would be considered not successful, and the connection would fail.
I would suggest to check your OpenSSL/BoringSSL versions used on both the client and the server, to make sure they both support ALPN.

**Comment by ZhenLian** [comment]
Or could it be cloud-dot-net is building against a OpenSSL/BoringSSL  version that doesn't support ALPN?

**Comment by benfranklin79** [comment]
> Or could it be cloud-dot-net is building against a OpenSSL/BoringSSL  version that doesn't support ALPN?

This I doubt because we have been able to run an application using the cloud-dot-net library in an instance not using Zscaler.

**Comment by jtattermusch** [comment]
> 2.41.0

This bug is for gRPC C# 2.41.0 and so it's based on C-core from the v1.41.x release branch and has boringssl embedded. So I think it's clear that the client does support ALPN. Whether the Zscaler proxy does really support ALPN or not (or if there's some other problem with Zscaler) I'm not sure. Can you tell us under which circumstances C-core would report the "missing selected ALPN property" error? Is it consistent with the server not supporting ALPN or with some other common handshake problem you can think of?

**Comment by benfranklin79** [comment]
> > Or could it be cloud-dot-net is building against a OpenSSL/BoringSSL version that doesn't support ALPN?
> 
> This bug is for gRPC C# 2.41.0 and so it's based on C-core from the v1.41.x release branch and has boringssl embedded (at the right version). So I think it's clear that the client does support ALPN. Whether the Zscaler proxy does really support ALPN or not (or if there's some other problem with Zscaler) I'm not sure. Can you tell us under which circumstances C-core would report the "missing selected ALPN property" error? Is it consistent with the server not supporting ALPN or with some other common handshake problem you can think of?

@ZhenLian you have any thoughts on this?

**Comment by ZhenLian** [comment]
ALPN is a mechanism for client and server to agree upon a right transport protocol. The reason why we need ALPN is that different clients want different protocols(HTTP vs. HTTP2), and different servers may support different protocols. So the client will embed an ALPN info in the extension of ClientHello info, and the server will choose one and return the current protocol in the ServerHello info.
To make it work, we will need both the client and server to understand the ALPN message. Since the error happens on the client side, I think it could be the case when the client is expecting ALPN in the ServerHello, while not provided by the server?

**Comment by tonydnewell** [comment]
@benfranklin79 I'm just checking on the status of this issue. Is this still a problem? You said that you managed to get it working on another box unrestricted by zscaler.

**Comment by benfranklin79** [comment]
@tonydnewell Yes still a problem. Further investigation by another developer in the same company revealed a similar problem running the same code on a Macbook. We are starting wonder if it's still a problem to do with Zscaler. We are currently speculating that even though the Zscaler rules were switched off when we tested that it is still interferring with the traffic in some way.

**Comment by tonydnewell** [comment]
@benfranklin79 Is this discussion relevant? Fourth comment suggests configuring an SSL exception in Zscaler.
https://community.zscaler.com/t/using-zscaler-with-http-2/12291/3
