### ISSUE TITLE
Unbounded memory usage increase when running on older kernels only?

### ISSUE THREAD

**Issue by twisteroidambassador** [grpc/grpc#29388]
### What version of gRPC and what language are you using?
v1.43.2 C++

### What operating system (Linux, Windows,...) and version?
`nvidia/cuda:10.2-base-ubuntu18.04` docker image, running on a CentOS 7 host (kernel `3.10.0-1062.9.1.el7.x86_64`)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### What did you do?
We implemented a stream-stream server in C++ and packaged it in a docker image. During stress testing, we could see the memory usage of the container rising and eventually reaching the memory limit, resulting in OOM kill.

I have prepared a minimal reproduction case:
[docker_repro.zip](https://github.com/grpc/grpc/files/8471724/docker_repro.zip)

Note that the server code uses a ResourceQuota with size 100MiB.

#### Steps to reproduce:

    # build server image
    docker build -t server .

    # build client image
    docker build -f Dockerfile_client -t client .

    # run server in one terminal
    docker run --rm -it -p 50015:50015 --init server 0.0.0.0:50015

    # run client in another terminal, which makes 800 concurrent stream requests to the server continuously
    docker run --rm -it --add-host=host.docker.internal:host-gateway --init client host.docker.internal:50015 800

    # monitor memory usage in a third terminal
    docker stats

### What did you expect to see?
The amount of memory used by the server image should be stable around a certain value.

### What did you see instead?

When the server image is run on a CentOS 7 host (kernel `3.10.0-1062.9.1.el7.x86_64`), the amount of memory used by the server image climbs slowly.

Just after starting the client, the server consumes ~ 120MiB memory. After 30 minutes or so it has climbed to ~230MiB, and in 1 hour it reached ~260MiB, after 2 hours ~290MiB, 4 hours ~420MiB.

When running on a Debian 11 host (kernel `5.10.0-13-amd64`), the memory usage is stable at ~120MiB even after a few hours.

(My guess is this could be related to the polling engine being used. On Debian 11 it would be `epollex`; on CentOS 7 it would be `epoll1` since the kernel is older.)

### Anything else we should know about your project / environment?

Our actual server's memory usage grows more quickly than the reproduction case here, at a rate of ~4GiB per hour. I have not determined why, although stress testing server code other than gRPC has not produced any memory usage increase.

**Comment by yashykt** [comment]
The epollex polling engine has been deleted and epoll1 is now the default. Could you please verify this on head?

**Comment by yashykt** [comment]
I will also note that the ResourceQuota does not take into account writes at present. So, unfinished might also be a reason for the increase especially given that this is a server streaming RPC.

**Comment by twisteroidambassador** [comment]
Tested commit 5850cba2957cc894477e735a74aa6c246b499ff4. Running on Debian 11, memory usage is ~320MiB after 5 minutes, ~350MiB after 18 hours. On CentOS 7, it's 1.1 GiB (!!!) after 5 minutes, ~1.4GiB after 2 hours, ~1.5GiB after 14 hours.

**Comment by yashykt** [comment]
Could I ask you to collect some memory profiles (for example, with the google heap profiler tool) to see where the memory increase is coming from?

**Comment by yashykt** [comment]
Some additional notes -
Assuming that ResourceQuota is working correctly here and the buffered writes are an issue, we would suspect the HTTP layer as the major suspect point where the bytes are being buffered. (There would also be some buffering in the tcp layer and on the socket which you can tune.) 

The default way that writes work in gRPC C++ is that, the API can accept more writes as soon as the previous write passes flow control. The thing is that if the bytes pass flow control but the TCP layer is not yet ready to send more bytes, those bytes would be buffered. With enough messages and available flow control, it is possible to overwhelm the memory required. 

Using `set_write_through()` would alleviate the problem slightly. What this does is that it only allows the next write after previous write has gone done to the TCP layer. You can further control the memory by accepting only a limited number of RPCs on the server and writing smaller messages (the resource quota will make this more simple in the future, but for now, the application is on the hook for this.)

**Comment by yashykt** [comment]
Please comment or open a new issue if the issue still persists.
