### ISSUE TITLE
Cross-compiling for QNX-710 failing with aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/chacha/chacha-armv8.S.o' is incompatible with aarch64 output

### ISSUE THREAD

**Issue by tongtongdi** [grpc/grpc#29439]
### What version of gRPC and what language are you using?
Using gRPC:1.46.0-dev
Langeuage:c++

### What operating system (Linux, Windows,...) and version?
Target platform: QNX-710 64Bit(aarch64)
Host platform: Ubuntu 20.04(x86_64)
### What runtime / compiler are you using (e.g. python version or version of gcc)
Cross-compiler QCC 8.3.0 (gcc_ntoaarch64le)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Cloned gRPC @ v1.46.0-dev (with submodules)
Used the QNX-710 SDP, a tpplchain file for cross-compilation 
Created a build directory (grpc-1.46.0-qnx)
Inside the build directory, ran the following command: cmake -DCMAKE_TOOLCHAIN_FILE=/qnx_toolchain.cmake ../grpc-1.46.0
inside the build directory, ran make -j8
i update boringssl_with_bazel/CMakeLists.txt77: 'elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")' to 'elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64le")'
### What did you expect to see?
build success

### What did you see instead?
`stderr: grpc                             
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/chacha/chacha-armv8.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/aesv8-armx64.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/armv8-mont.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/ghash-neon-armv8.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/ghashv8-armx64.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/sha1-armv8.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/sha256-armv8.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/sha512-armv8.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/fipsmodule/vpaes-armv8.S.o' is incompatible with aarch64 output
/home/mi/qnx710/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-ld: unknown architecture of input file `CMakeFiles/crypto.dir/linux-aarch64/crypto/test/trampoline-armv8.S.o' is incompatible with aarch64 output
make[2]: *** [third_party/boringssl-with-bazel/libcrypto.so] Error 1
make[1]: *** [third_party/boringssl-with-bazel/CMakeFiles/crypto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
mak```
e: *** [all] Error 2
Failed   <<< grpc [1.49s, exited with code 2]
`

**Comment by tongtongdi** [comment]
i add "-DOPENSSL_CRYPTO_LIBRARY=$QNX_TARGET/aarch64le/usr/lib/libcrypto.a" , this problem is solved.
but the new error is :
`In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/atm.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/alloc.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_iphone.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_posix.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/env_posix.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_posix.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/env_posix.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/env_linux.cc:24:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/alloc.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_linux.cc:23:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/env_posix.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/atm.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/env_linux.cc:24:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_iphone.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_posix.cc.o] Error 1
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/atm.h:24,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/atm.cc:21:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/atm.h:81:2: error: #error could not determine platform for atm
 #error could not determine platform for atm
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/env_linux.cc.o] Error 1
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_linux.cc:23:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/atm.h:90:1: error: 'gpr_atm' does not name a type
 gpr_atm gpr_atm_no_barrier_clamped_add(gpr_atm* value, gpr_atm delta,
 ^~~~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_iphone.cc.o] Error 1
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/atm.cc:25:1: error: 'gpr_atm' does not name a type
 gpr_atm gpr_atm_no_barrier_clamped_add(gpr_atm* value, gpr_atm delta,
 ^~~~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_linux.cc.o] Error 1
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/atm.cc.o] Error 1
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_windows.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:408:2: error: #error "Could not auto-detect platform"
 #error "Could not auto-detect platform"
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:431:2: warning: #warning "GPR_PLATFORM_STRING not auto-detected" [-Wcpp]
 #warning "GPR_PLATFORM_STRING not auto-detected"
  ^~~~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/alloc.cc.o] Error 1
In file included from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/support/port_platform.h:22,
                 from /data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/src/core/lib/gpr/cpu_windows.cc:19:
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:498:2: error: #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
 #error Must define exactly one of GPR_GCC_ATOMIC, GPR_GCC_SYNC, GPR_WINDOWS_ATOMIC
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:502:2: error: #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
 #error Must define exactly one of GPR_ARCH_32, GPR_ARCH_64
  ^~~~~
/data/cross_com/micar_os_alphatrion_qnx_ws/src/cockpit/core/platform/external/grpc/include/grpc/impl/codegen/port_platform.h:508:2: error: #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
 #error Must define exactly one of GPR_CPU_LINUX, GPR_CPU_POSIX, GPR_WINDOWS, GPR_CPU_IPHONE, GPR_CPU_CUSTOM
  ^~~~~
make[2]: *** [CMakeFiles/gpr.dir/src/core/lib/gpr/cpu_windows.cc.o] Error 1
make[1]: *** [CMakeFiles/gpr.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
`

**Comment by nicolasnoble** [comment]
Sorry, but we are very unlikely to be able to help directly on this one. QNX isn't even listed in our list of supported platforms: https://github.com/grpc/grpc/blob/master/src/cpp/README.md#supported-platforms

I won't close this one in case somebody else from the community has an answer for you, but we don't have the knowledge to help directly.
