### ISSUE TITLE
Is there a way to statically link in those submodule libraries in libgrpc.a

### ISSUE THREAD

**Issue by jzcq89** [grpc/grpc#29441]
For the version of grpc (1.38) we are using, there are a bunch of submodule libraries like libabsl*.a,  libgpr.a, libupb.a, libaddress_sorting.a etc...
We are trying to create a static linked libgrpc.a and have all needed submodule libraries in it.
Is there an easy way to do it? Like some sort of hidden flag?

Looks like by default, none of the needed submodule libraries are in the libgrpc.a.

Thank you!

**Comment by drfloob** [comment]
The issue tracker is for bugs and feature requests, not general questions such as this one. Please consider reaching out on Stackoverflow or the gRPC mailing list instead. You'll want to list your build environment (bazel or cmake, likely), and your current build command.
