### ISSUE TITLE
grpcio-tools.protoc python import paths should be relative to a specified root directory

### ISSUE THREAD

**Issue by illeatmyhat** [grpc/grpc#29459]
`grpcio-tools==1.44.0`
Given the generated directory structure, where `baz.proto` imports `bar.proto`
```
.
├── setup.py
└── foo
    ├── __init__.py
    ├── bar_pb2.py
    ├── bar_pb2_grpc.py
    ├── baz_pb2.py
    └── baz_pb2_grpc.py
```
According to https://github.com/grpc/grpc/issues/9575#issuecomment-293934506, what we have is currently
`import bar_pb2 as bar__pb2`
but what we want is
`import foo.bar_pb2 as bar__pb2` or `from foo import bar_pb2 as bar__pb2`
the solution is to place the proto files into a subdirectory `proto/foo/*.proto`, and change the .proto imports to be relative to the root directory `import "foo/bar.proto"`
i.e. `sed -i'.bak' -e 's!import "!import "foo/!g' ./proto/foo/*`
finally: `python -m grpc_tools.protoc --proto_path=proto --python_out=. --grpc_python_out=. proto/foo/*.proto`

This is an unsatisfactory solution, because sometimes you don't own the proto files, and editing them is hacky. It's not as if you can expect the authors to be aware of the protoc conventions of every obscure language ever, either.
The simplest solution would be to set the root package, and all proto imports to be relative to that root.
i.e. take `--python_out=.` and turn it into `from . import ...`

**Comment by markdoerr** [comment]
Dear @gnossen  and @illeatmyhat ,

I have the same issue as @illeatmyhat for years.
Out of frustration that this is not solved in the first place, there is even a hacky tool, called [protoletariat](https://github.com/cpcloud/protoletariat). But this bug should be solved in the first place by the code generation of protoc, not by an external tool, with an additional dependency to fix an easy fixable bug.

Who would be able to fix the import generation of the python protoc ?
And why is this not solved for years ?

**Comment by markdoerr** [comment]
Protoc just needs to generate

 `from . import my_pb2 as ... `
instead of:
`import my_pb2 as ...  `

That would simply solve the issue.

**Comment by markdoerr** [comment]
There are many other's having this issue,
I just found:

https://github.com/ElDavoo/wa-crypt-tools/issues/63

**Comment by ElDavoo** [comment]
> But this bug should be solved in the first place by the code generation of protoc

In fact I think the relevant issue/discussion should be [here](https://github.com/protocolbuffers/protobuf/issues/5374) and not in this issue.

**Comment by tomatac** [comment]
A workaround that worked for me was to add the folder where the python files are generated to the python path:
```
add_to_python_path("./protos_built")

def add_to_python_path(new_path):
    existing_path = sys.path
    absolute_path = os.path.abspath(new_path)
    if absolute_path not in existing_path:
        sys.path.append(absolute_path)
    return sys.path
```

**Comment by gnossen** [comment]
I believe this is fundamentally the same issue as [this one](https://github.com/protocolbuffers/protobuf/issues/1491) on the protobuf repo. We really have no choice but to align with protobuf itself on this. If/when there's a change from the protobuf project, we'll be happy to make the necessary changes here.

In the meantime, using `sys.path` / `PYTHONPATH` as @tomatac recommended is absolutely preferred to doing string substitution in your generated files.
