### ISSUE TITLE
Make sure the Node server doesn't lock up when shutting down

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2946]
When the Node server shuts down, it waits for all calls to finish. If some calls are still pending and don't have a timeout, the shutdown may never finish.

**Comment by soltanmm** [comment]
Is this behavior something all languages should have?

**Comment by murgatroid99** [comment]
I think that we should try to make sure that when we shut down a server, it finishes shutting down.

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: Python servers will have two shutdown methods, one for "graceful" shutdown (stop accepting new RPCs but complete those already being serviced) and one for immediate shutdown. Both methods will be idempotent, meaning that a server owner can indicate graceful shutdown, wait five minutes, decide to be done with waiting, and immediately shut down the server.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle A'ight.
