### ISSUE TITLE
Could we please add a c++ streaming example?

### ISSUE THREAD

**Issue by liuzhen2008** [grpc/grpc#29479]
### Is your feature request related to a problem? Please describe.
I am looking over the cpp examples, i see unary call examples, however I don't see any streaming examples.

### Describe the solution you'd like
I see there exists a proto file for hellostreamingworld.proto, but I am not seeing how it can be used in c++

### Describe alternatives you've considered
I tried looking into python examples, but they are not directly transferable.

### Additional context
Please add a c++ streaming example. I am trying to see if it is feasible to use grpc instead of websocket for my application.

**Comment by liuzhen2008** [comment]
Actually im very dumb. The route_guide cpp example has all the 4 types of rpc.

**Comment by ctiller** [comment]
There's a lot of stuff and even we forget what's there from time to time.

**Comment by liuzhen2008** [comment]
Hi @ctiller. So the example in route_guide is synchronous call. Should I leave this open to ask for an async streaming example?
