### ISSUE TITLE
Create GRPC channel stuck while App Domain unload

### ISSUE THREAD

**Issue by qifzhou** [grpc/grpc#29480]
### What version of gRPC and what language are you using?
Grpc.Core Version="2.30.0"

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
This is something I spot in our prod, that there's a IIS config change while process start, triggering a app domain unload, while I think the GRPC channel is under initialization that time. then something stuck there.

### What did you expect to see?
GRPC channel created

### What did you see instead?
From dump file captured, the domain unload trigger the unload event in GRPCEnvironment, here's the callstack
`Call Site
ntdll!ZwWaitForMultipleObjects+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 907] 
KERNELBASE!WaitForMultipleObjectsEx+0xfe [minkernel\kernelbase\synch.c @ 1551] 
clr!WaitForMultipleObjectsEx_SO_TOLERANT+0x62 [f:\dd\ndp\clr\src\vm\threads.cpp @ 4302] 
clr!Thread::DoAppropriateAptStateWait+0x36 [f:\dd\ndp\clr\src\vm\threads.cpp @ 4336] 
clr!Thread::DoAppropriateWaitWorker+0x205 [f:\dd\ndp\clr\src\vm\threads.cpp @ 4476] 
clr!Thread::DoAppropriateWait+0x7d [f:\dd\ndp\clr\src\vm\threads.cpp @ 4143] 
clr!CLREventBase::WaitEx+0xb6 [f:\dd\ndp\clr\src\vm\synch.cpp @ 850] 
clr!AwareLock::EnterEpilogHelper+0x104 [f:\dd\ndp\clr\src\vm\syncblk.cpp @ 3118] 
clr!AwareLock::EnterEpilog+0x62 [f:\dd\ndp\clr\src\vm\syncblk.cpp @ 3063] 
clr!SyncBlock::EnterMonitor+0x8 [f:\dd\ndp\clr\src\vm\syncblk.h @ 776] 
clr!ObjHeader::EnterObjMonitor+0xd [f:\dd\ndp\clr\src\vm\syncblk.cpp @ 1901] 
clr!Object::EnterObjMonitor+0x16 [f:\dd\ndp\clr\src\vm\object.h @ 484] 
clr!JITutil_MonEnterWorker+0x132 [f:\dd\ndp\clr\src\vm\jithelpers.cpp @ 4799] 
Grpc_Core!Grpc.Core.GrpcEnvironment.ShutdownChannelsAsync()+0x4e [/var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs @ 159] 
Grpc_Core!Grpc.Core.GrpcEnvironment+ShutdownHooks.HandleShutdown()+0x21 [/var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs @ 486] 
clr!CallDescrWorkerInternal+0x83 [f:\dd\ndp\clr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 97] 
clr!CallDescrWorkerWithHandler+0x4e [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 89] 
clr!DispatchCallSimple+0x67 [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 243] 
clr!InvokeNotifyInner+0x5d [f:\dd\ndp\clr\src\vm\comdelegate.cpp @ 4038] 
clr!InvokeNotify+0x62 [f:\dd\ndp\clr\src\vm\comdelegate.cpp @ 4079] 
clr!DistributeEventReliably+0x174 [f:\dd\ndp\clr\src\vm\comdelegate.cpp @ 4148] 
clr!AppDomain::RaiseUnloadDomainEvent+0xefc3f [f:\dd\ndp\clr\src\vm\appdomain.cpp @ 9738] 
clr!Thread::DoADCallBack+0x211 [f:\dd\ndp\clr\src\vm\threads.cpp @ 8836] 
clr!AppDomain::RaiseUnloadDomainEvent+0x66 [f:\dd\ndp\clr\src\vm\appdomain.cpp @ 9721] 
clr!AppDomain::ProcessUnloadDomainEventOnFinalizeThread+0x43 [f:\dd\ndp\clr\src\vm\appdomain.cpp @ 9693] 
clr!Thread::DoExtraWorkForFinalizer+0x1e8 [f:\dd\ndp\clr\src\vm\threads.cpp @ 10016] 
clr!FinalizerThread::FinalizerThreadWorker+0x90 [f:\dd\ndp\clr\src\vm\finalizerthread.cpp @ 685] 
clr!ManagedThreadBase_DispatchInner+0x40 [f:\dd\ndp\clr\src\vm\threads.cpp @ 10296] 
clr!ManagedThreadBase_DispatchMiddle+0x6c [f:\dd\ndp\clr\src\vm\threads.cpp @ 10345] 
clr!ManagedThreadBase_DispatchOuter+0x4c [f:\dd\ndp\clr\src\vm\threads.cpp @ 10600] 
clr!ManagedThreadBase_NoADTransition+0x3b [f:\dd\ndp\clr\src\vm\threads.cpp @ 10687] 
clr!ManagedThreadBase::FinalizerBase+0x3b [f:\dd\ndp\clr\src\vm\threads.cpp @ 10713] 
clr!FinalizerThread::FinalizerThreadStart+0x116 [f:\dd\ndp\clr\src\vm\finalizerthread.cpp @ 841] 
clr!Thread::intermediateThreadProc+0x8b [f:\dd\ndp\clr\src\vm\threads.cpp @ 2882] 
kernel32!BaseThreadInitThunk+0x14 [base\win32\client\thread.c @ 64] 
ntdll!RtlUserThreadStart+0x21 [minkernel\ntdll\rtlstrt.c @ 1163] 
`

While I also found some threads undergoing the channel creation :
`Call Site
ntdll!ZwWaitForAlertByThreadId+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 3835] 
ntdll!RtlSleepConditionVariableSRW+0x109 [minkernel\ntos\rtl\condition.c @ 1109] 
KERNELBASE!SleepConditionVariableSRW+0x2d [minkernel\kernelbase\synch.c @ 2038] 
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x43bd60
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x43b9da
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x437a36
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x4370a5
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x439173
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x439497
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x438dbb
grpc_csharp_ext_x64!grpcsharp_slice_buffer_reset_and_unref+0x51385
Microsoft_M365_Core_Diagnostics!DomainBoundILStubClass.IL_STUB_PInvoke()+0x73
Grpc_Core!Grpc.Core.GrpcEnvironment.GrpcNativeInit()+0x4a [/var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs @ 374] 
Grpc_Core!Grpc.Core.GrpcEnvironment..ctor()+0x57 [/var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs @ 303] 
Grpc_Core!Grpc.Core.GrpcEnvironment.AddRef()+0x82 [/var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs @ 78] 
Grpc_Core!Grpc.Core.Channel..ctor(System.String, Grpc.Core.ChannelCredentials, System.Collections.Generic.IEnumerable`1<Grpc.Core.ChannelOption>)+0xc7 [/var/local/git/grpc/src/csharp/Grpc.Core/Channel.cs @ 70] `

**Comment by tonydnewell** [comment]
@qifzhou Is this still a problem?
Are you able to give more details - e.g. version of IIS, version of .NET
