### ISSUE TITLE
GRPC .net client slower then GRPC core in .NET 5.0 framework

### ISSUE THREAD

**Issue by CosbyBs86** [grpc/grpc#29490]
Hello all
 I'm facing a very weird behavior. I'm using GRPC .net client package (version 2.45.0) on .NET framework 5 as a very stupid client for a grpc server written in Golang. The client -> server communication is in streaming. With GRPC core package the client/server communication run about 15000 operations per second. With GRPC .net client package the communication is about 1200 ops/s. 

Please find here below the cliente code:

GRPC core code:
`
var chanel = new Channel("172.25.0.100", 4424, ChannelCredentials.Insecure);
var service = new GrpcService.GrpcServiceClient(chanel);
var call = service.AppendItems();

foreach (var i in grpcItems)
{
    await call.RequestStream.WriteAsync(r).ConfigureAwait(false);
}
await call.RequestStream.CompleteAsync();
`

GRPC .net client code:
`
var chanel = GrpcChannel.ForAddress("http://172.25.0.100:4424", new GrpcChannelOptions
{
    HttpHandler = new SocketsHttpHandler
    {
        EnableMultipleHttp2Connections = true,
        PreAuthenticate = false,
        UseCookies = false,
        PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
    },
});
var service = new GrpcService.GrpcServiceClient(chanel);
var call = service.AppendItems();

foreach (var i in grpcItems)
{
    await call.RequestStream.WriteAsync(r).ConfigureAwait(false);
}
await call.RequestStream.CompleteAsync();
`

Using .net 6 frameworks times are almost the same but I was expecting something faster. Can you kindly point me out on how to improve performances.

Thank you

**Comment by drfloob** [comment]
Hi @CosbyBs86. It sounds like you have general questions about a different project, gRPC .Net is not related to gRPC core. Please see their repo, and follow their policies for asking general questions.

CC @jtattermusch.

**Comment by jtattermusch** [comment]
Note that the official performance benchmarks (https://grpc.io/docs/guides/benchmarking/, https://grafana-dot-grpc-testing.appspot.com/) now has comparison of Grpc.Core with grpc-dotnet. You can use that for the reference.
