### ISSUE TITLE
Why the question template contains a warning saying DO NOT POST A QUESTION?

### ISSUE THREAD

**Issue by ysk24ok** [grpc/grpc#29506]
https://github.com/grpc/grpc/blob/d2ff2bb75e6a3f14a30a021e4576fc35ae68d85f/.github/ISSUE_TEMPLATE/question.md

Maybe you want to delete this remark?

**Comment by nicolasnoble** [comment]
No, that's the intended comment. The rest of the file describes that this isn't the proper venue to ask questions, but rather the mailing list. Do not ask questions here.
