### ISSUE TITLE
compile grpc with protoc 3.9.1

### ISSUE THREAD

**Issue by wolegeyun** [grpc/grpc#29511]
### What version of gRPC and what language are you using?
1.46.0-dev

### What operating system (Linux, Windows,...) and version?
ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

error:::
**_In file included from /tmp/grpc/src/compiler/python_generator.cc:19:0:
/tmp/grpc/src/compiler/python_generator.h:47:12: error: ‘uint64_t grpc_python_generator::PythonGrpcGenerator::GetSupportedFeatures() const’ marked ‘override’, but does not override
   uint64_t GetSupportedFeatures() const override;
            ^
/tmp/grpc/src/compiler/python_generator.cc: In member function ‘uint64_t grpc_python_generator::PythonGrpcGenerator::GetSupportedFeatures() const’:
/tmp/grpc/src/compiler/python_generator.cc:883:10: error: ‘FEATURE_PROTO3_OPTIONAL’ was not declared in this scope
   return FEATURE_PROTO3_OPTIONAL;_**

**Comment by donnadionne** [comment]
There is not enough info here to conclude this is a GRPC issue.
