### ISSUE TITLE
gRPC C++ Compile on wsl2 docker environment

### ISSUE THREAD

**Issue by tensmyo** [grpc/grpc#29510]
Environment: 
- Windows 11 Pro + WSL2(Ubuntu20.04) + Docker
- 32GB memory DDR4

Build gRPC in docker 

Get Error: 
`[ 76%] Building CXX object CMakeFiles/grpc_unsecure.dir/src/core/lib/surface/call_details.cc.o
c++: fatal error: Killed signal terminated program cc1plus`

VM memory usage: from 5GB -> 16.28GB  and fatal out
Do compile gRPC really need so many memory?
Can we do something smart way to compile this?

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by tensmyo** [comment]
Thank you @markdroth will do some research
