### ISSUE TITLE
Messages' sizes are not consistent with docs what leads to errors

### ISSUE THREAD

**Issue by karol-bisztyga** [grpc/grpc#29520]
### What version of gRPC and what language are you using?

C++
grpc v1.39.1

### What operating system (Linux, Windows,...) and version?

I spotted similar behavior on 2 types of OS
Linux ubuntu 20.04/mac os 12.3.1

### What runtime / compiler are you using (e.g. python version or version of GCC)

```
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
On linux
```
g++ (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
```

### What did you do?

Here is a repo+branch I use for the tests: https://github.com/karol-bisztyga/grpc-playground/tree/repeated-field

Basically, what I do is, I use `repeated` field on a nested `message` in the `proto` file. This nestes `message` also includes `oneof`.

You can see these two commits:
With a `repeated` field: https://github.com/karol-bisztyga/grpc-playground/commit/af90854a6416585e8d3f0f41b3ebce9164b6c9b4
Without it: https://github.com/karol-bisztyga/grpc-playground/commit/ddf1e53aafad6273af2c78a3e424f2a4911f7d4a

If you want to run this locally, you can do:
```
git clone https://github.com/karol-bisztyga/grpc-playground.git
cd grpc-playground
git checkout repeated-field
./build.sh client && ./cmake/build/bin/client
```

### What did you expect to see?

Running examples from both commits I provided above I got the following results:
- with `repeated`
```
req size 0: 0
req size with name: 9 // plus maybe some bytes for repeated but I don't know the rules for this
req size with data chunk: 1: 24 // plus maybe some bytes for repeated but I don't know the rules for this
req size with data chunk: 2: 39 // plus maybe some bytes for repeated but I don't know the rules for this
req size with data chunk: 3: 54 // plus maybe some bytes for repeated but I don't know the rules for this
```
- without `repeated`
```
req size 0: 0
req size with name: 9
req size with data chunk: 1: 15
req size with data chunk: 2: 15
req size with data chunk: 3: 15
```

### What did you see instead?

Running examples from both commits I provided above I got the following results:
- with `repeated`
```
req size 0: 0
req size with name: 8
req size with data chunk: 1: 22
req size with data chunk: 2: 36
req size with data chunk: 3: 50
```
- without `repeated`
```
req size 0: 0
req size with name: 6
req size with data chunk: 1: 12
req size with data chunk: 2: 12
req size with data chunk: 3: 12
```

I set the name to `name` (4 bytes) and data chunks to 10 bytes of `a` for both cases.
So what happens is that with repeated, there are "inner" messages being added to the "parent" message. Therefore the parent message size grows.

I don't understand why grpc adds only 2 bytes of data to a message without `repeated` and 4 bytes of data for messages with `repeated`. I thought grpc would add 5 bytes of data to **every** message, based on [this](https://github.com/grpc/grpc/issues/15734#issuecomment-396962671).

How I understand this:

> so the message that actually is being sent over the network looks like this
> [Compressed-Flag] [Message-Length] [Message]
>   [Compressed-Flag]   1 byte  - added by grpc
>   [Message-Length]    4 bytes - added by grpc
>   [Message]           N bytes - actual data
> so for every message we get 5 additional bytes of data

I have not found anything that would answer my doubts on the Internet.

Options I see:
- I don't understand something here/I missed something
- the docs lie
- I'm using the wrong method to measure the size of the message sent over the network by grpc: `ByteSizeLong()`

There are a few separate issues at this point:
- how many bytes exactly the grpc adds to every message?
- how exactly does it work with the `repeated` field?
- If we have a nested message, why doesn't grpc add bytes for both outer and inner messages? (because it apparently doesn't)

As for the message sizes, I also confirmed the sizes are the same on the other side (the server) by using the same method: `ByteSizeLong()`.

The reason I'm putting this up is, I have to be very precise in my project using grpc because we want to send data chunks that will often reach the upper limit and we have to have full control over how many bytes exactly are going to be added to grpc to send the biggest chunks of data in one message but at the same size not exceeding the upper limit.

Thanks in advance for any help,
best regards!

**Comment by donnadionne** [comment]
Asking the question to Craig

**Comment by yashykt** [comment]
You seem to be printing the size of the proto message. How protobuf chooses to serialize the data is something that's upto protobuf and not really something gRPC has control over. gRPC when sending the message over the wire with HTTP2 will add some framing bytes, but that doesn't seem to be what you are asking.
