### ISSUE TITLE
infrequent requests slow response

### ISSUE THREAD

**Issue by juliays** [grpc/grpc#29530]
We have an application that expects fairly infrequent incoming calls - about 4 every minute. But each call would invoke about 150 gRPC calls in parallel to the gRPC server. When we ran load testing, we found that the system works much better when there are about 20 - 40 calls per minute. But when there is only 4 calls per minute, response time could go as high as 15-20 seconds. Is there any parameter that we can adjust or what's the cause of this slowness with low volume?

**Comment by markdroth** [comment]
This form is for bug reports and feature requests only.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by juliays** [comment]
This should be considered either a bug or a feature request - why is it that when there is a few request per minute or one request every 10 seconds get processed slower than if there are 100 request per second? Keepalive doesn’t come into play here.

**Comment by markdroth** [comment]
It's not clear to me from the small amount of information that you provided that this is actually a bug.  Most of the problems we see like this are actually incorrect use of our API (e.g., creating a new channel for each RPC instead of creating a single channel and reusing it for all RPCs), which is why I suggested that you take this to a forum like stackoverflow or the mailing list.

If you are confident that you are using our API correctly and have a concrete bug to report, please include the code you're using so that we can reproduce the problem.

**Comment by ctiller** [comment]
(drive-by comment with no offer to pick this up)

We diagnosed a similar problem in a different RPC system some years ago - low QPS servers were slower than high QPS servers. It ended up being the machine going into one of its sleep states (slowing down the CPU to conserve energy).

Does your performance go up if you spin up a few side threads doing `while (true) {}`?

**Comment by juliays** [comment]
Thank you for your response. How did u check server CPU? I was running a test case on my Mac. I can’t tell real difference for CPU or memory usage in both cases. We are not talking about large quantities of data - in one case, I have 4 users spawn off randomly between 1-5 seconds. In another case, I have 20 users spawn off on the same 1-5 seconds interval. Once started, each thread would create the channel and client, then enter a loop to send about 150 requests to the fro server in a parallel call. After completion, it would wait for a random number between 10-60 seconds before sending next round of parallel 150 requests. Each request is about 1.5K json. 

For the 4 user case, I am seeing numbers consistently in the seconds range if not more. For the 20 user case, after initial round of requests (20-25) taking long time to process, subsequent ones takes about 30 milliseconds. It is consistent.

I can’t quite figure out what would cause this. I can try adding the while true {} in test, but I don’t think it is acceptable in prod. Also, it would make spike situation hard to predict and this not desirable. 

Could you shed some light on this? How do I upload a test case? Thanks!

**Comment by markdroth** [comment]
> Could you shed some light on this? How do I upload a test case?

It would probably help a lot to post the relevant portion of your code.

**Comment by juliays** [comment]
Here is my server code, which doesn't do much of anything other than logging the incoming request. 
===========================================================================
        public override Task<TimeSeriesResponse> UpdateTimeSeries(TimeSeriesRequest request, ServerCallContext context)
        {
            _logger.LogInformation(" received incoming request {0}", request);
            return Task.FromResult(new TimeSeriesResponse
            {
                Count = (uint)request.Items.Count,
                StatusCode = 200
            });
        }
=================================================
Here is my client app
=================================================
        public static void Main(string[] args)
        {
            int user = 20;
            if (args.Length == 1)
            {
                user = int.Parse(args[0]);
            }
            Console.WriteLine(user +" user test");
            for (var i = 0; i < user; i++)
            {
                Thread newThread = new(Program.InvokeGrpcServer);
                newThread.Start();
                Thread.Sleep(rnd.Next(1000, 5000));
            }
            
        }

        public static void InvokeGrpcServer()
        {
            using var channel = GrpcChannel.ForAddress("http://localhost:5000");

            var client = new TestClient((GrpcChannel)channel);

            TimeSeriesRequest request = TimeSeriesRequest.Parser.ParseJson(Record.OneRecord);
            List<TimeSeriesRequest> requests = new();
            for (int i = 0; i < 146; i++)
            {
                requests.Add(request);
            }
            while (true)
            {
                
                var sw = new Stopwatch();
                sw.Start();
                ConcurrentBag<TimeSeriesResponse> list = new();
                Parallel.ForEach(requests, r =>
                   list.Add(((TestClient)client).UpdateTimeSeries(r))
                );
                sw.Stop();
                Console.WriteLine("{2} - call successful {0} : {1}", !list.Any(p => p.StatusCode != 200), sw.ElapsedMilliseconds, DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss.ffffffK"));
                Thread.Sleep(rnd.Next(10000, 60000));
            }
        }
======================
Here is my proto 
======================
syntax = "proto3";

option csharp_namespace = "messages";

package grpctest;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

service TimeSeriesService
{
	rpc UpdateTimeSeries(TimeSeriesRequest) returns (TimeSeriesResponse) {};
}

message TimeSeriesItem
{
	google.protobuf.Timestamp TimeStamp = 1;
	string Tag = 2;
	oneof numeric_or_text {
		float NumericValue = 3;
		string TextValue = 4;
	}
}
message TimeSeriesRequest
{
	//batch items
	repeated TimeSeriesItem Items = 1;
	string DataPathKey = 4;
	map<string, google.protobuf.Value> Metadata = 5; // https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Value
}
message TimeSeriesResponse
{
	uint32 StatusCode = 1;
	uint32 count = 2;
}

**Comment by markdroth** [comment]
Okay.  In that case, @jtattermusch, can you take a look?

**Comment by juliays** [comment]
Hi, we figured out the issue is with the client implementation - if we change the call to grpc server method to async, the performance bottleneck is gone. 

This call is where the change is 

Parallel.ForEach(requests, await r =>
               list.Add(async ((TestClient)client).UpdateTimeSeriesAsync(r))
            );
