### ISSUE TITLE
When communicating 2 gRPC in keepAliveTime, 1 gRPC does not work

### ISSUE THREAD

**Issue by hyeokyoon-chang** [grpc/grpc#29552]
### What version of gRPC and what language are you using?
gRPC ver: 1.37.0
language: JAVA

### What operating system (Linux, Windows,...) and version?
Linux ubuntu 18.04

### What did you do?
I have defined two gRPC messages in the proto file as follows.

```protobuf
message StatusManagerConfig {
  int64 interval_in_ms = 1;
  enum StatusCommandType {
    STATUS_COMMAND_TYPE_INVALID = 0;
    STATUS_COMMAND_TYPE_STOP_REPORTING = 1;
    STATUS_COMMAND_TYPE_START_REPORTING = 2;
  }
  StatusCommandType status_command_type = 2;
}

message CollectorConfigInfo {
  string collector_id = 1;
  CollectorExecutorConfig collector_executor_config = 2;
  DataSourceConfig data_source_config = 3;
}
```

and, Also, the keepAliveTime of the gRPC channel was defined as 1 minute.

Speaking of the background first, the client is always alive like the server,
StatusManagerConfig and collectorConfigInfo each communicate with the server periodically.

However, there is no problem during the first communication, but after time passes and these two gRPCs communicate together within one keep alive time (1 minute), collectorConfigInfo does not work after that.

It works well at first, but after that, 
when two gRPCs communicate within one keep alive time, I wonder why one doesn't work.

I would really appreciate it if you could guide me on how to solve it.

**Comment by temawi** [comment]
Sorry for the late reply. What is the problem you see? Do you get an exception you could share? Or does your application hang? If so, how long did you wait before you gave up on it working.

Is your client connecting to the server over the Internet? Or are they both running in the same data center? Any proxies in use?

Also, you could also try with the latest gRPC version.

**Comment by temawi** [comment]
It's been a while without a response, so closing. If more information is provided the bug can be reopened.
