### ISSUE TITLE
UDS support for Python

### ISSUE THREAD

**Issue by oliverhamilton7915** [grpc/grpc#29557]
### Is your feature request related to a problem? Please describe.
I would like to be able to bind my Python grpc server to a unix domain socket. Currently, the python grpc library only supports binding to a `(host, port)` tuple (formatted as `host:port`) through using `server.add_insecure_port(...)`. 

### Describe the solution you'd like
I would like to be able to pass something like `unix:///tmp/test.sock` to `server.add_insecure_port(...)` to bind to a unix socket. Other users seem interested in the same functionality. Examples here: https://stackoverflow.com/questions/54844882/grpc-server-in-python-with-unix-domain-socket, https://stackoverflow.com/questions/71571059/how-exactly-does-grpc-for-python-handles-unix-domain-sockets

### Describe alternatives you've considered
Downloading the repo from source, modifying it, and implementing this myself. Attempting to get the server to bind to a file descriptor.

**Comment by oliverhamilton7915** [comment]
This still doesnt work for me. I am trying to same line as @sebastianhillig-db did above. Anything look wrong from the DEBUG logs?
`D0505 18:47:12.082779699   27510 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0505 18:47:12.082813678   27510 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0505 18:47:12.082824161   27510 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0505 18:47:12.082831057   27510 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0505 18:47:12.082836864   27510 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0505 18:47:12.082842846   27510 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D0505 18:47:12.082849825   27510 dns_resolver.cc:333]        Using native dns resolver
D0505 18:47:12.082887945   27510 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0505 18:47:12.082898586   27510 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0505 18:47:12.082908015   27510 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0505 18:47:12.082914134   27510 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0505 18:47:12.082920671   27510 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
E0505 18:47:12.106848707   27510 server_chttp2.cc:48]        {"created":"@1651776432.106816661","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":935,"referenced_errors":[{"created":"@1651776432.106809162","description":"Failed to add port to server","file":"src/core/lib/iomgr/tcp_server_custom.cc","file_line":391,"referenced_errors":[{"created":"@1651776432.106791700","description":"bind failed: [Errno -3] Temporary failure in name resolution","file":"./src/core/lib/iomgr/python_util.h","file_line":34,"grpc_status":14}]}]}
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wmouse/wmouse/wmouse/services/exchanges/apis/tunnel/server.py", line 169, in <module>
    run_child=main
  File "/home/wmouse/wmouse/wmouse/tools/process_management/process_sharder.py", line 31, in shard_process
    run_child(*sys.argv[1:])
  File "/home/wmouse/wmouse/wmouse/services/exchanges/apis/tunnel/server.py", line 153, in main
    asyncio.get_event_loop().run_until_complete(serve())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/wmouse/wmouse/wmouse/services/exchanges/apis/tunnel/server.py", line 152, in serve
    await serve_grpc_app(server, '/tmp/test')
  File "/home/wmouse/wmouse/wmouse/utils/grpc.py", line 21, in serve_grpc_app
    port = server.add_insecure_port(f'unix://{sockname}')
  File "/home/wmouse/wmouse/env/lib/python3.6/site-packages/grpc/aio/_server.py", line 85, in add_insecure_port
    address, self._server.add_insecure_port(_common.encode(address)))
  File "/home/wmouse/wmouse/env/lib/python3.6/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address unix:///tmp/test.sock; set GRPC_VERBOSITY=debug environment variable to see detailed error message.`

**Comment by lidizheng** [comment]
@oliverhamilton7915 PTAL at https://github.com/grpc/grpc/pull/29592 and https://github.com/grpc/grpc/blob/master/doc/naming.md. I created an example using UDS as the address for client/server and normal/asyncio API. I guess the problem you see above is whether the process has access to `/tmp` directory. Feel free to try out the example code, see if it works in your environment.

**Comment by oliverhamilton7915** [comment]
Interesting. Importing and running that example works. I now can see the error is because of the `gevent` monkey patching in my environment. For example, pasting the following at the following after the imports in `/examples/python/uds/async_greeter_server.py` should allow you reproduce my error:
```
from gevent import monkey
monkey.patch_all()
import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()
```
Is it possible for you all to fix the gevent patching on your end?

**Comment by oliverhamilton7915** [comment]
Separately, [this post](https://stackoverflow.com/questions/51006950/scaling-issues-using-gevent-and-grpc) seems to indicate that the gevent patching degrades grpc python's performance. Can you confirm?

**Comment by lidizheng** [comment]
Can you upgrade to the latest `grpcio` release and try again? We refactored our gevent integration in v1.45.x.

I might not have cycles to produce the benchmark number.

**Comment by oliverhamilton7915** [comment]
I upgraded the `grpcio` package version to 1.46.0 and it is still unable to bind to the unix sockets. I included the imports + patching from above, and when I started up the server using `python async_greeter_server.py`, I failed to see the expected logging:
`Server listening on: unix:helloworld.sock`
`Server listening on: unix:///tmp/helloworld.sock`
I dont believe the refactored gevent integration helped this UDS issue.

**Comment by lidizheng** [comment]
Thanks for checking the asyncio implementation with gevent. Can you also check if the standard gRPC Python example with gevent works in your case?
