### ISSUE TITLE
Difference in the grpc status structure in grpc-c vs definition in status.proto

### ISSUE THREAD

**Issue by amanand** [grpc/grpc#29576]
### What version of gRPC and what language are you using?
1.31

### What operating system (Linux, Windows,...) and version?
Linux, Freebsd

### What runtime / compiler are you using (e.g. python version or version of gcc)
llvm 3.0

### Problem statement
There are few differences in the definition of status between grpc-c and other language bindings.
In case of other bindings as seen in the status.proto file(https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto#L80), there is a message field and details field of repeated Any type.
However in case of grpc-c, status is  packed in the following structure
    struct grpc_op_send_status_from_server {
      size_t trailing_metadata_count;
      grpc_metadata* trailing_metadata;
      grpc_status_code status;
      /** optional: set to NULL if no details need sending, non-NULL if they do
       * pointer will not be retained past the start_batch call
       */
      grpc_slice* status_details;
    } send_status_from_server;

So, is there a way to pack the message field as well? 
For gribi, implementation, we need to provide the status code and status details (repeated Any proto type) to the client.
So for a server to send the following to meet the requirements in the gribi.proto:(https://github.com/openconfig/gribi/blob/master/v1/proto/service/gribi.proto#L75)
status code = FAILED_PRECONDITION
details = repeated type Any.proto (type_url = "type.googleapis.com/gribi.ModifyRPCErrorDetails", value=[])

Can you please help in providing an example of how to encode the details field in the grpc_slice structure and if possible the status message in grpc-c?

**Comment by amanand** [comment]
gentle reminder on this one.. @yashykt any clues about this one?

**Comment by yashykt** [comment]
Note that gRPC Core is not public API, and it's not intended for public consumption.

**Comment by nicolasnoble** [comment]
@amanand: what are you trying to achieve exactly? It's not immediately clear to us here.

**Comment by amanand** [comment]
hey @nicolasnoble - In order to comply our gribi implementation with the [specification](https://github.com/openconfig/gribi/blob/2aaba323cde619765adcb25aae1855b962a4f667/v1/proto/service/gribi.proto#L312) , we need to populate error details as any.proto encoded binary data in the status.details and send over to the client.
Due to internal dependencies, we had to use grpc-c as well as the core APIs for sending out these error messages. My main request is whether we can populate a binary data (any.proto encoded data) in [status.details](https://github.com/grpc/grpc/search?p=3&q=send_status_from_server), I tried to look for any implementation in the test code but couldn't find one. In almost all the cases, we are populating status_details using the slice created out of a static string. For example - this one [  grpc_slice status_details = grpc_slice_from_static_string("xyz");](url)
Appreciate any links or suggestions on this one.

**Comment by yashykt** [comment]
Sorry, that is not something we support right now. The HTTP2 wire protocol does not support that out of the box. As an alternative, you could add it as a binary metadata in trailing metadata.

**Comment by amanand** [comment]
![Screen Shot 2022-05-18 at 11 12 05 AM](https://user-images.githubusercontent.com/9928244/169075824-ed7529e3-d244-43b5-9260-acac599d0117.png)
Thanks Yash for the information. I need to insert the status details as i had mentioned earlier, so if we can do it by inserting trailing metadata, that should be fine as well. I have couple of questions on how to implement it:
1. what should be the key for the trailing-metadata, i am assuming it wont be received as part of the status structure by the clients as shown in the screenshot, instead they will need to add an additional step to extract the trailing metadata from the server response with they key name known in advance?
2. Regarding the actual value to be encoded, the suffix has be part of the actual data or the metadata name? please let me know if my understanding is correct: payload = "-bin"+any.proto serialized object, like below:
    AddTrailingMetadata("status-details-bin",  "-bin"+ ModifyRpcErrorDetails.SerializeAsString());

**Comment by yashykt** [comment]
> what should be the key for the trailing-metadata, i am assuming it wont be received as part of the status structure by the clients as shown in the screenshot, instead they will need to add an additional step to extract the trailing metadata from the server response with they key name known in advance?

Yes, it won't be available as part of the status, but as part of the trailing metadata. The key name should have a "-bin" suffix. 

> Regarding the actual value to be encoded, the suffix has be part of the actual data or the metadata name? please let me know if my understanding is correct: payload = "-bin"+any.proto serialized object, like below:
AddTrailingMetadata("status-details-bin", "-bin"+ ModifyRpcErrorDetails.SerializeAsString());

The suffix would be part of the key and not the value.


Refer https://github.com/grpc/grpc/blob/4976933e6b09706ccc542b7c9c7221cd6c50bd32/include/grpcpp/impl/codegen/server_context.h#L181

**Comment by amanand** [comment]
@yashykt  thanks for the prompt response. Much appreciated.
