### ISSUE TITLE
"No thread quota available" when only very few threads are running

### ISSUE THREAD

**Issue by kipply** [grpc/grpc#29570]
### What version of gRPC and what language are you using?
C++ 17 (also tried 14), gRPC pinned at https://github.com/grpc/grpc/commit/dc78581af30da834b7b95572f109bf6c708686e0

### What operating system (Linux, Windows,...) and version?
`5.8.0-1035-gcp` (tpu v4 vm)

### What runtime / compiler are you using (e.g. python version or version of gcc)
bazel 5.1.1

### What did you do?
I think a fairly standard setup of a grpc server in c++ should replicate this, though I specifically could only replicate it on my tpu vm (where the same code runs fine anywhere else). 

### What did you expect to see?
Server started 

### What did you see instead?
`E0504 00:23:09.795318416 1205520 thread_manager.cc:128]      No thread quota available to even create the minimum required polling threads (i.e 1). Unable to start the thread manager
Aborted (core dumped)`

```
#0  grpc::ThreadManager::Initialize (this=0x555556fae240)
    at external/com_github_grpc_grpc/src/cpp/thread_manager/thread_manager.cc:127
#1  0x0000555555d35a62 in grpc_impl::Server::SyncRequestThreadManager::Start (
    this=0x555556fae240) at external/com_github_grpc_grpc/src/cpp/server/server_cc.cc:953
#2  0x0000555555d31770 in grpc_impl::Server::Start (this=0x555556f9e200, cqs=0x0, num_cqs=0)
    at external/com_github_grpc_grpc/src/cpp/server/server_cc.cc:1270
#3  0x0000555555d1da8a in grpc_impl::ServerBuilder::BuildAndStart (this=0x7fffffffde60)
    at external/com_github_grpc_grpc/src/cpp/server/server_builder.cc:423
#4  0x00005555556373d3 in aurora::Server::RunServer (this=0x7fffffffe000, server_opts=...)
    at server.cc:60
#5  0x000055555561ad60 in main (argc=2, argv=0x7fffffffe208) at main.cc:30
```

**Comment by veblush** [comment]
Would you share the minimal repro with us?
