### ISSUE TITLE
Upgrading to grpc 1.45.0 from 1.40.1 causes too much time for the server to start

### ISSUE THREAD

**Issue by vvenka57** [grpc/grpc#29584]
### What version of gRPC and what language are you using?
Upgraded to 1.45.0 from 1.40.1. 
Java/Kotlin

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
We upgraded our grpc version from 1.40.1 to 1.45.0

### What did you expect to see?
Our server starts in approximately 2 minutes after grpc 1.45.0 upgrade without any exceptions.

### What did you see instead?
After upgrade, it takes more than 3 minutes for some pods to start and eventually tries restarting multiple times and ends up in backoff state. This also happens with our liveliness probe eventually causing our apps to get restarted in PROD.

Also getting BouncyCastle ALPN class not found exception. This error did not occur with 1.40.1 version.

Reverting back to 1.40.1 solves the problem in lower environment.

**Comment by vvenka57** [comment]
@markdroth Can you please help with this?

**Comment by markdroth** [comment]
If you're using grpc-java, please file this issue in the grpc/grpc-java repo.  Thanks!
