### ISSUE TITLE
"protoc" does not recognize `--pyi_out` when invoked via `grpc_tools.protoc.main`

### ISSUE THREAD

**Issue by zbentley** [grpc/grpc#29650]
### What version of gRPC and what language are you using?

```
(chariot) zac.bentley@ZacBentleyMBP ~ ∴ python --version
Python 3.7.13
(chariot) zac.bentley@ZacBentleyMBP ~ ∴ pip list | grep grpc
grpcio                    1.46.0
grpcio-tools              1.46.0
grpclib                   0.4.2
(chariot) zac.bentley@ZacBentleyMBP ~ ∴ pip list | grep protobuf
protobuf                  3.20.1
(chariot) zac.bentley@ZacBentleyMBP ~ ∴ sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
(chariot) zac.bentley@ZacBentleyMBP ~ ∴ arch
i386
```

### What operating system (Linux, Windows,...) and version?

MacOS 12, Intel

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7.13 via pyenv

### What did you do?

Attempted to compile a `.proto` file with `grpc_tools.protoc.main`, while supplying the `--pyi_out` flag.

### What did you expect to see?

`.pyi` files written to the filesystem.

### What did you see instead?

An error:
```
Invoking protoc with arguments: ('--include_imports',
 '-I/Users/zac.bentley/.venv/lib/python3.7/site-packages/grpc_tools/_proto',
 '-I/Users/zac.bentley/protos',
 '-I.',
 '--python_out',
 '/var/folders/yf/kxq3d44d35s9f3hpsj_899dm0000gp/T/compile_protobuf_file_scratchlboxrung',
 '--pyi_out',
 '/var/folders/yf/kxq3d44d35s9f3hpsj_899dm0000gp/T/compile_protobuf_file_scratchlboxrung',
 '--descriptor_set_out',
 '/var/folders/yf/kxq3d44d35s9f3hpsj_899dm0000gp/T/compile_protobuf_file_scratchlboxrung/descriptor',
 'my_test_protobuf.proto')
protoc-gen-pyi: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--pyi_out: protoc-gen-pyi: Plugin failed with status code 1.
```

**Comment by gnossen** [comment]
It looks like this capability was added in [protobuf `3.20.0`](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0), which we have not yet pulled into a released gRPC version. We're currently working through some incompatibilities with this version. It should be included in either `1.47.0` within the next couple of weeks. If not, it will make it into the following release.

**Comment by gnossen** [comment]
In the meantime, you can directly download the `protoc` binary from the protobuf release indicated to separately generate your `pyi` files.

**Comment by lesam** [comment]
Still seeing this on version `1.48.2` .

**Comment by XuanWang-Amos** [comment]
```
$ python3 -m grpc_tools.protoc --help | grep pyi_out
  --pyi_out=OUT_DIR           Generate Python pyi stub.
```

It's included in 1.48.2, please check if you're set up is correct.

Closing this one for now, feel free to reopen if you're seeing other issues.

**Comment by EByrdS** [comment]
I have version `libprotoc 3.18.1` but it seems I can't use `pyi_out`. The error thrown is:

```
protoc-gen-pyi: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--pyi_out: protoc-gen-pyi: Plugin failed with status code 1.
```

Using `grep` yields no results, so there is nothing in `--help` with regards to it. Is this related?

**Comment by lesam** [comment]
Update: my setup was incorrect, 1.48.2 was fine. Sorry for the noise!

**Comment by Code-Destiny** [comment]
> Update: my setup was incorrect, 1.48.2 was fine. Sorry for the noise!

May I ask how you got the setup right? I'm using 1.48.2 too and still having this issue.

**Comment by jeffpicard** [comment]
@lesam any gotchas you found that might be happening to others? I'm on 1.48.2 and get the error in the top comment about not supporting `--pyi_out` as well. We have dependencies on packages that are pinned to `protobuf<4` (tensorflow-metadata). Which means grpcio-tools `1.48.2` is the highest we can use.
