### ISSUE TITLE
C# .NET Framework (WinHttpHandler) client vs. Python3 server, unsupported protocol issue

### ISSUE THREAD

**Issue by Livius90** [grpc/grpc#29659]
### What version of gRPC and what language are you using?
python3-grpcio 1.46.0, Grpc.Net.Client 2.45.0 in C# .NET Framework 4.7.2

### What operating system (Linux, Windows,...) and version?
Windows 10 21H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.10

### What did you do?
I implemented a simple gRPC client in C# .NET Framework  4.7.2 (WinHttpHandler) and a gRPC server in Python3 (grpcio 1.46.0) for testing.

### What did you expect to see?
A returned string value from my gRPC method call.

### What did you see instead?
In C# .NET Framework i can use only client and it is mandantory to using TLS with WinHttpHandler. When i test it with my gRPC Python server and try to call a gRPC method, i got an "A connection with the server could not be established" exception in C# then i also got an "UNSUPPORTED_PROTOCOL" error in Python server log. Can you help what is this issue?

It seems to me gRPC Python server requires an other cryptographic protocol for example TLS v1.3 maybe, but in C# .NET Framework for WinHttpHandler i can use only TLS v1.0, v1.1, v1.2. Can you help how can i change TLS version of my gRPC Python server to any older version? By the way, if i test it in a Python client and Python server everything is working well.

gRPC Python server error:
```console
E0511 17:55:18.799000000 14676 src/core/tsi/ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL.
D0511 17:55:18.802000000 14676 src/core/lib/security/transport/security_handshaker.cc:181] Security handshake failed: {"created":"@1652284518.802000000","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":377,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
D0511 17:55:18.806000000 14676 src/core/ext/transport/chttp2/server/chttp2_server.cc:427] Handshaking failed: {"created":"@1652284518.802000000","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":377,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

C# .NET Framework client exception:
```console
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__122.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__73.MoveNext() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 493")
```

Issue was mentioned also here: https://github.com/grpc/grpc-dotnet/issues/1733

**Comment by Livius90** [comment]
I found that grpc-dotnet require a [Windows 10 Build 19622 or later](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework) which is available only from Windows Insider. So this is the reason why not work on Windows 10 21H2 for me. Only the [gRPC C# core-library](https://grpc.io/docs/languages/csharp/quickstart/) works well on current Windows 10 21H2 build.
https://en.wikipedia.org/wiki/Windows_10_version_history

**Comment by p1x31** [comment]
if anyone will meet the same problem again here is a [solution](https://github.com/dotnet/runtime/issues/102452#issuecomment-2126770795)
