### ISSUE TITLE
A custom field of protobuf message

### ISSUE THREAD

**Issue by Closius** [grpc/grpc#29677]
### Is your feature request related to a problem? Please describe.
An ability to have a custom field of protobuf message. For example: I want to send numpy array via gRPC. This is not a good idea because this array might be very big. 

### Describe the solution you'd like
The idea is to dump numpy array into file and put a link to this file into the field of protobuf message. On the client side the process goes backwards.

The abstract classes for a custom field might be added for any languages. Then users can implement this abstract classes and use a custom fields

### Describe alternatives you've considered
The handler function for substituting numpy array by the file can be implemented. It should be implemented in different languages, Manually

**Comment by nicolasnoble** [comment]
What you're requesting isn't a grpc change, but a protobuf change. The proper avenue for this discussion is at https://github.com/protocolbuffers/protobuf
