### ISSUE TITLE
How often are the interop tests run from scratch?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#2967]
@soltanmm and I were just alerted by @ejona86 to a problem in the Python Dockerfile - we had forgotten to update a path following a big source reorganization a few weeks ago.

How often are the Dockerfiles used in interop testing, and the Docker images rebuilt from scratch? We had thought this was something that happened every day, at least, but our Dockerfile has been broken for at least the last two weeks.

**Comment by ejona86** [comment]
I do see that build 671 has the failure in the logs:
```
Step 3 : RUN cd /var/local/git/grpc   && pip install src/python/src   && pip install src/python/interop
 ---> Running in 0d888593d6cb
[91mYou are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[0m[91mException:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/basecommand.py", line 246, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/commands/install.py", line 308, in run
    name, None, isolated=options.isolated_mode,
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/req/req_install.py", line 220, in from_line
    isolated=isolated)
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/req/req_install.py", line 79, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'src/python/src', 'at', '/python/src')

[0m2015/08/17 21:30:04 The command [/bin/sh -c cd /var/local/git/grpc   && pip install src/python/src   && pip install src/python/interop] returned a non-zero code: 2
grpc_dockerfile_install:: build of grpc/python <- /var/local/dockerfile/grpc_python
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
Mon Aug 17 21:30:04 UTC 2015
image_args go
```

You can see at the end it moves on to the next image (go). The build overall was considered a success. It seems we may not be error-handling appropriately, or at least making it obvious when an error occurs.

**Comment by ejona86** [comment]
Also, I did check, the latest interop results showed passing with Python, even though we know it wasn't able to build the docker image.

**Comment by soltanmm** [comment]
It turns out that we've just not yet moved Python's interop tests to Jenkins to be automagically tested and whatnot. That'll happen... at some point.

**Comment by ejona86** [comment]
Python is being tested with Jenkins, but with the old infrastructure. The old infrastructure does not detect when building the Docker image fails, and ends up just using the previously-built image.

**Comment by jtattermusch** [comment]
We're in the process of dropping the old interop tests infrastructure (stoked-keyword-656), as run_interop_tests.py offers most of the functionality and is more flexible (and faster).

I'm closing this as this is effectively replaced by https://github.com/grpc/grpc/issues/3632
