### ISSUE TITLE
activity.h:154]             assertion failed: g_current_activity_ == nullptr

### ISSUE THREAD

**Issue by waxxmaster** [grpc/grpc#29675]
### What version of gRPC and what language are you using?

gRPC => 1.45.0 installed via pecl

composer package :

"grpc/grpc": "^1.42"

### What operating system (Linux, Windows,...) and version?

Debian GNU/Linux 11 (bullseye)

### What runtime / compiler are you using (e.g. python version or version of gcc)

PHP Version => 7.4.22

phpinfo dump :

grpc support => enabled
grpc module version => 1.45.0

Directive => Local Value => Master Value
grpc.enable_fork_support => 1 => 1
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => epoll1 => epoll1

used trough openswoole php server

openswoole

Open Swoole => enabled
Author => Open Swoole Group <hello@openswoole.com>
Version => 4.11.0
Built => May 11 2022 15:24:32
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Using the official php firestore library :
"google/cloud-firestore": "^1.22"

i'm updating an existing document 
$firestore->update()

Behind that the firestore library uses grpc to communicate with google servers.

### What did you expect to see?
It should not crash the openswoole PHP server

### What did you see instead?
activity.h:154]             assertion failed: g_current_activity_ == nullptr

The openswoole thread is killed right after this log

### Anything else we should know about your project / environment?

This bug occurs randomly, i'm using this server in production, sometime i didn't get any error for days, and sometime i get this errors multiples times in a day

You have to know that openswoole is a multi threaded PHP server forked from a main thread and this is possible that concurrent firestore calls are done on different threads. It is started with this configuration ( https://openswoole.com/docs/modules/swoole-server/configuration ) :

        "worker_num": 4,
        "task_worker_num": 0,
        "dispatch_mode": 2,
        "task_enable_coroutine" : false
        
Let me now if you need further informations

**Comment by waxxmaster** [comment]
Any news on this ? Any way to prevent this kind of error ?

**Comment by espdev** [comment]
We have got the same issue while using [Google Speech API in Python](https://github.com/googleapis/python-speech).

We use Python 3.8.10 and the following dependency package versions:
```
google-api-core           2.8.2                  Google API client core library
google-auth               2.8.0                  Google Authentication Library
google-cloud-speech       2.14.1                 Google Cloud Speech API client library
google-cloud-texttospeech 2.11.1                 Google Cloud Text-to-Speech API client library
googleapis-common-protos  1.56.3                 Common protobufs used in Google APIs
grpcio                    1.46.3                 HTTP/2-based RPC framework
grpcio-status             1.46.3                 Status proto mapping for gRPC
```

**Comment by alto-php** [comment]
Appeared fixed in https://github.com/grpc/grpc/pull/29513

**Comment by alto-php** [comment]
Close due to inactive and assumed fixed.
