### ISSUE TITLE
Grpc.Tools: Warnings from generated code in .NET 7

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#29672]
.NET 7 is adding a build warning for type names with all lowercase characters. This is impacting code generated from Grpc.Tools which aliases namespaces with all lowercase characters, e.g. pb, pbc, grpc, etc

Log output:

> /Users/vstester/GrpcGreeterClient/obj/Debug/net7.0/Protos/Greet.cs(8,7): warning CS8981: The type name 'pb' only contains lower-cased ascii characters. Such names may become reserved for the language. [/Users/vstester/GrpcGreeterClient/GrpcGreeterClient.csproj]
> 
> /Users/vstester/GrpcGreeterClient/obj/Debug/net7.0/Protos/Greet.cs(9,7): warning CS8981: The type name 'pbc' only contains lower-cased ascii characters. Such names may become reserved for the language. [/Users/vstester/GrpcGreeterClient/GrpcGreeterClient.csproj]
> 
> /Users/vstester/GrpcGreeterClient/obj/Debug/net7.0/Protos/Greet.cs(10,7): warning CS8981: The type name 'pbr' only contains lower-cased ascii characters. Such names may become reserved for the language. [/Users/vstester/GrpcGreeterClient/GrpcGreeterClient.csproj]
> 
> /Users/vstester/GrpcGreeterClient/obj/Debug/net7.0/Protos/Greet.cs(11,7): warning CS8981: The type name 'scg' only contains lower-cased ascii characters. Such names may become reserved for the language. [/Users/vstester/GrpcGreeterClient/GrpcGreeterClient.csproj]
> 
> /Users/vstester/GrpcGreeterClient/obj/Debug/net7.0/Protos/GreetGrpc.cs(8,7): warning CS8981: The type name 'grpc' only contains lower-cased ascii characters. Such names may become reserved for the language. [/Users/vstester/GrpcGreeterClient/GrpcGreeterClient.csproj]

Options are to either:
- Update code generation to alias using pascal case. There is no chance these names are ever used by C# and break generated code. However, there is a chance the alias name could conflict with other types names in the app. Probably shouldn't do this.
- Add a pragma suppression. Simplest, easiest. It's unlikely that pb, pbc, pbr, scg, grpc are used by C# in the future.
- Remove aliases and use full namespaces instead. More complicated but safest. There is a mix between aliases and full namespaces so this would make generated code files larger, but more consistent.

**Comment by aateeque** [comment]
Weirdly I am getting this error in a net6.0 project; I've got:

csproj:
```
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>preview</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>
```

global.json:
```
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestMinor"
  }
}
```

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Adding a `<NoWarn>8981</NoWarn>` gets rid of it; but I wanted to flag that this is happening in net6.0 (which I don't get why! don't even have net7-previews installed on my machine as you can see)

**Comment by JamesNK** [comment]
That's odd. Do you get warnings when building in VS only? Are you using a preview?

The warning is part of C# 11, which perhaps you're using because of `<LangVersion>latest</LangVersion>`, but I don't understand how C# 11 is available without a new SDK. Changing it to `<LangVersion>10</LangVersion>` might fix it.

**Comment by aateeque** [comment]
@JamesNK nope - `<LangVersion>10.0</LangVersion>` did not fix it; I got around it with a `<NoWarn>8981</NoWarn>` though

However quite curious how c#11 feature is causing break on a machine without 11 or net7? Where's a better place to open this issue? Happy to help bottom this out

**Comment by aateeque** [comment]
Is it weirdly possible that this is shipped with Visual Studio? I have got:

```
Microsoft Visual Studio Enterprise 2022
Version 17.1.6
VisualStudio.17.Release/17.1.6+32421.90
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00476-80000-00000-AA347
Microsoft Architecture Diagrams and Analysis Tools

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.1.363.30963
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.1.363.30963
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.1.363.30963
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.1.363.30963
Azure Functions and Web Jobs Tools

C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.161+abc97ecc7d.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft SARIF Viewer   3.0.66.61165
Visual Studio Static Analysis Results Interchange Format (SARIF) log file viewer

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Node.js Tools   1.5.40105.1 Commit Hash:1822ee94b29c6cf748a19825f14cc26d30b0b871
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62203.25080
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   17.0.1229.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by aateeque** [comment]
Actually ignore that; just tried running a `dotnet build` on the sln & it fails similarly with:

```
 error CS8981: The type name 'pbc' only contains lower-cased ascii characters. Such names may become reserved for the language.
```

**Comment by wrkntwrkn** [comment]
Also getting these.

` <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>`

Version: `7.0.100-rc.1.22431.12`

For now went with:
`<PropertyGroup>
        <NoWarn>CS8981</NoWarn>
    </PropertyGroup>`

**Comment by vpekarek** [comment]
Hi.
Updating `Grpc.AspNetCore` to version 2.49.0 help me with this problem.
