### ISSUE TITLE
Python gRPC client could not connect to server with a proxy through gateway

### ISSUE THREAD

**Issue by Litchilitchy** [grpc/grpc#29718]
### What version of gRPC and what language are you using?
grpcio 1.44.0 installed by pip

### What operating system (Linux, Windows,...) and version?
Linux, kernal 5.16

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6

### What did you do?
I start a gRPC server by `add_insecure_port('[::]:8980')` and use gRPC client with `grpc.insecure_channel("localhost:8980")`

On my PC, I have set `http_proxy` and `https_proxy`, the code works.

But on company server (connect should be performed through gateway), the client could not connect to server and error message is `failed to connect to all addresses`. And the proxy environment variable is also set. And after I unset them by `export http_proxy=` the code works.

However, the Java gRPC does not has this issue.

### What did you expect to see?
I think the proxy has nothing to do with the gRPC connection through localhost? The gRPC Python should work with or without the proxy setting, or gateway config. And Java gRPC works well, Python behavior should be the same?

Also, there is an issue almost the same with mine: https://github.com/grpc/grpc/issues/15942

**Comment by gnossen** [comment]
@yashykt Can you please take a look?

**Comment by yashykt** [comment]
I'm not sure what Java is doing here but it looks like all you want here is to set `no_proxy` or `no_grpc_proxy` to include `localhost` so that the proxy is not used there.
