### ISSUE TITLE
build grpc third_party boringssl-with-bazel error?

### ISSUE THREAD

**Issue by OverCookkk** [grpc/grpc#29729]
Compiling third_party/boringssl-with-bazel/err_data.c   has a error

third_party/boringssl-with-bazel/err_data.c:22: error: expected ‘)’ before ‘==’ token

err_data.c  code as below
#define OPENSSL_STATIC_ASSERT(cond, msg) static_assert(cond, msg)
OPENSSL_STATIC_ASSERT(ERR_LIB_NONE == 1, "library value changed");
OPENSSL_STATIC_ASSERT(ERR_LIB_SYS == 2, "library value changed");

my compiler version gcc (GCC) 6.3.0

who knows what the problem is？

**Comment by yashykt** [comment]
From @veblush - We've got continuous integration tests running with gcc 6.3. Please provide more information about the environment/commands used.

**Comment by yashykt** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
