### ISSUE TITLE
Call to grpc_server_destroy will nulled server instance

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#2974]
In src/node/ext/server.cc:162, `this->wrapped_server` is made NULL. However, `grpc_server_destroy` is called upon it on line 123 (there's also a naming inconsistency regarding the use of "this->"), most likely resulting in the crash reported at https://github.com/grpc/grpc/issues/2859#issuecomment-131183232

**Comment by murgatroid99** [comment]
I'm pretty sure this was fixed in #2993.
