### ISSUE TITLE
Grpc.Tools handles paths differently than other protoc generators

### ISSUE THREAD

**Issue by danielleiszen** [grpc/grpc#29761]
This is a followup of [this issue](https://github.com/dotnet/aspnetcore/issues/17059). The C# specific details can be found there. 

Environment

OS: Windows 11
IDE: Visual Studio 2020 (64 bit) 17.2.1

Generators:
libprotoc 3.19.4
Grpc.Tools 2.45.0

Problem

When a .proto file is compiled, Grpc.Tools requires the import paths to be relative to the project root folder. If the .proto file is in a folder hierarchy (per convention it is /Protos) the whole folder structure from the project root should be included in the import path. When there are multiple files refering to each other in the same folder, those files will not compile in other languages using the language specific protoc compiler because that treats import paths to be relative to the file.

Setup and arrangement

I usually use .Net on server side and Flutter on client side. As I split my business logic into thematic units, the same is done with the .proto files. So I usually have a bunch of .proto files in the same directory. I need them to refer to each other, so I use the #import directive. The files do not have circular dependencies. I put my .proto files into the `Protos `folder as it is generated by Visual Studio as a default.

Result and Errors

When I import a file in another .proto I have to include the `Protos `folder in the path. Otherwise, the generator gives an error saying:

`Import "REFERENCED.proto" was not found or had errors. File not found.`'

When the `Protos` folder is included in the path, the generator is capable of generating the C# files without an error. However, if I use an other compiler to generate into a different language - Dart in my case. I get the same error.

```
Protos/REFERENCED.proto: File not found.
Import "Protos/REFERENCED.proto" was not found or had errors.
```

Workaround

I also have two workarounds for those who face the same issue. However, I do not think any of these should be treated as permanent solution.

Workaround 1

If all the .proto files for the whole solution is put into the same directory (directly under the solution directory). This way they can import each other without having the directory in the import path. Then when these should be used in one or more projects of a Visual Studio solution, instead of adding them directly to the solution I add  them using the Add / Existing item... / Add as Link command. This way the files are generated properly.

Workaround 2

When the files are used for generation directly in a protoc compiler (Dart in my case), the include directories should be extended with the directory above the Protos directory. This way the compiler would be able to import the file that is under the Protos directory as well.

None of these workarounds are ideal, however I hope it helps in the meantime while this issue is fixed.

Thank you.

**Comment by tonydnewell** [comment]
@danielleiszen 
Use the ProtoRoot attribute to set the root directory for your proto files.  It will then behave as you are expecting.
See https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md

E.g. in the examples that you give in [the original issue](https://github.com/dotnet/aspnetcore/issues/17059) you can do:

```XML
<Protobuf Include="Protos/greet.proto" GrpcServices="Server" ProtoRoot="Protos" />
<Protobuf Include="Protos/messages.proto" GrpcServices="None" />
```

or even

```XML
<Protobuf Include="*/*.proto" ProtoRoot="Protos" />
```
