### ISSUE TITLE
ruby interop test (cloud to prod) failing in load_prod_cert

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#2980]
+ gcloud compute --project stoked-keyword-656 ssh --zone asia-east1-a grpc-docker-testclients --command 'sudo docker run grpc/ruby bin/bash -l -c '\''SSL_CERT_FILE=/cacerts/roots.pem ruby /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb --use_tls --server_port=443 --server_host=grpc-test.sandbox.google.com --server_host_override=grpc-test.sandbox.google.com --test_case=large_unary'\'''
Warning: Permanently added '104.199.168.64' (ECDSA) to the list of known hosts.
Using /usr/local/rvm/gems/ruby-2.1.5
+ for x in '{0..5}'
+ ps -p 10039
  PID TTY          TIME CMD
10039 ?        00:00:00 gcloud
+ sleep 10
stdin: is not a tty
/var/local/git/grpc/src/ruby/pb/test/client.rb:82:in `load_prod_cert': undefined method `logger' for GRPC:Module (NoMethodError)
	from /var/local/git/grpc/src/ruby/pb/test/client.rb:94:in `prod_creds'
	from /var/local/git/grpc/src/ruby/pb/test/client.rb:101:in `ssl_creds'
	from /var/local/git/grpc/src/ruby/pb/test/client.rb:109:in `create_stub'
	from /var/local/git/grpc/src/ruby/pb/test/client.rb:449:in `main'
	from /var/local/git/grpc/src/ruby/pb/test/client.rb:453:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:51:in `<main>'
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
+ for x in '{0..5}'

**Comment by tbetbetbe** [comment]
This should have been fixed by #2982, submitted earlier today.
@donnadionne  can you confirm that this is resolved and close the bug if it is ?

**Comment by donnadionne** [comment]
fixed as of aug 24 2015 test results
