### ISSUE TITLE
Segmentation fault when using stub created from SSL channel credentials

### ISSUE THREAD

**Issue by octaviansima** [grpc/grpc#29828]
### What version of gRPC and what language are you using?

C++, error found in gRPC 1.45.0 and 1.46.3.

### What operating system (Linux, Windows,...) and version?

Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc/g++ version 11.1.0 (Ubuntu 11.1.0-1ubuntu1~18.04.1)

### What did you do?

I created a channel as follows, according to the tutorial:
```cpp
auto channel = grpc::CreateChannel(
  "localhost:50053", grpc::SslCredentials(grpc::SslCredentialsOptions()));
```

The server address did not matter, the segfault occured regardless of that value and before any connection was attempted. Using a client stub that was instantiated with this channel resulted in a segfault. I was able to reproduce with a variety of different credentials, each resulting in the same issue:

```cpp
// Create SSL channel credentials
grpc::SslCredentialsOptions ssl_opts = {read_file(root_ca_location), "", ""};
auto channel_creds = grpc::SslCredentials(ssl_opts);

auto channel = grpc::CreateChannel("localhost:50053", channel_creds);
```

```cpp
// Create TLS channel credentials
grpc::experimental::TlsChannelCredentialsOptions options;
auto channel_creds = grpc::experimental::TlsCredentials(options);

auto channel = grpc::CreateChannel("localhost:50053", channel_creds);
```

### What did you expect to see?

An attempt at a connection to a secure server located on port 50053 of the same machine, written in Golang.

### What did you see instead?

I observed a segfault.

Stack trace:
[stack-trace.txt](https://github.com/grpc/grpc/files/8789621/stack-trace.txt)

gRPC Debugging logs:
[grpc-debug.txt](https://github.com/grpc/grpc/files/8789648/grpc-debug.txt)

### Anything else we should know about your project / environment?

When I switched from BoringSSL to a system installed version of OpenSSL (`1.1.1-1ubuntu2.1~18.04.17`) using `set(gRPC_SSL_PROVIDER package)` in CMake, this error went away. Previously, I added BoringSSL to the CMake using `set(gRPC_deps third_party/boringssl-with-bazel ...)`.

**Comment by drfloob** [comment]
@ZhenLian can you take a look at this? There appears to be a crash in loading the certificates.

**Comment by ZhenLian** [comment]
I suspect this might due to different string interpretations of OpenSSL/BoringSSL versions. Try adding a terminating NULL("\0") to your root certificate string?
It seems the error comes from the function PEM_ASN1_read_bio(https://man.openbsd.org/PEM_ASN1_read.3). You can also try loading your root certs into a string and read that string with this function, to see if that would cause a crash.

**Comment by vmendiratta** [comment]
This appears to affect the python package too. Traceback when code encounters a seg fault:

**Environment**
python version - 3.8.7, grpc version - 1.45.0, os - Debian GNU/Linux 10 (buster)

File "/usr/local/lib/python3.8/threading.py", line 890 in _bootstrap
File "/usr/local/lib/python3.8/threading.py", line 932 in _bootstrap_inner
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67 in run
File "/usr/local/lib/python3.8/threading.py", line 870 in run
File "/usr/local/lib/python3.8/site-packages/grpc/_plugin_wrapping.py", line 89 in __call__
File "/usr/local/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 101 in __call__
File "/usr/local/lib/python3.8/site-packages/grpc/_plugin_wrapping.py", line 61 in __call__

**Comment by octaviansima** [comment]
@ZhenLian 

> I suspect this might due to different string interpretations of OpenSSL/BoringSSL versions. Try adding a terminating NULL("\0") to your root certificate string?

The string is null terminated. Confirmed that by printing and inspecting the last byte as well

**Comment by ZhenLian** [comment]
@octaviansima @vmendiratta 
Sorry I was just back from a long vacation. Does this still happen now? 
We have a bunch of test certs stored in https://github.com/grpc/grpc/tree/master/src/core/tsi/test_creds, that are proven to work. Maybe you can trying replacing your own certs with ours, and see if the segmentation fault still persists?
Let me know how it goes!

**Comment by ZhenLian** [comment]
Adding @erm-g in case there is any further investigation that's needed.

**Comment by edipascale** [comment]
I'm having the same issue on gRPC v1.56.0 and 1.58.0. I've tried using the test certificates shipped with the source but the result is identical. All cert strings are null-terinated as double-checked with gdb. Here is the relevant part of the backtrace:
```
#0  0x00007ffff7b089b9 in BIO_gets () from /lib/x86_64-linux-gnu/libcrypto.so.3
#1  0x00007ffff7c528a8 in PEM_read_bio_ex () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007ffff7c5353f in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007ffff7c53a1f in PEM_bytes_read_bio () from /lib/x86_64-linux-gnu/libcrypto.so.3
#4  0x00007ffff7c53ac0 in PEM_ASN1_read_bio () from /lib/x86_64-linux-gnu/libcrypto.so.3
#5  0x0000555555b66722 in ssl_ctx_use_certificate_chain(ssl_ctx_st*, char const*, unsigned long) ()
#6  0x0000555555b66c94 in populate_ssl_context(ssl_ctx_st*, tsi_ssl_pem_key_cert_pair const*, char const*) ()
#7  0x0000555555b6a284 in tsi_create_ssl_server_handshaker_factory_with_options(tsi_ssl_server_handshaker_options const*, tsi_ssl_server_handshaker_factory**) ()
#8  0x0000555555ac0487 in (anonymous namespace)::grpc_ssl_server_security_connector::InitializeHandshakerFactory() ()
#9  0x0000555555ac0ca6 in grpc_ssl_server_security_connector_create(grpc_core::RefCountedPtr<grpc_server_credentials>) ()
#10 0x0000555555ab8c2b in grpc_ssl_server_credentials::create_security_connector(grpc_core::ChannelArgs const&) ()
#11 0x000055555597e50b in grpc_server_add_http2_port ()
#12 0x00005555556410cc in grpc::SecureServerCredentials::AddPortToServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, grpc_server*) ()
#13 0x00005555556540b1 in grpc::Server::AddListeningPort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, grpc::ServerCredentials*) ()
#14 0x0000555555646ece in grpc::ServerBuilder::BuildAndStart() ()
```

Relevant bits of the code:
```
auto read_file(std::string path) -> std::string
{
    std::ifstream ifs(path);
    if (!ifs) {
        exit(1);
    }

    std::string content((std::istreambuf_iterator<char>(ifs)),
                        (std::istreambuf_iterator<char>()));

    ifs.close();

    /* remove trailing newline */
    if (content.at(content.length() - 1) == '\n') {
        content.pop_back();
    }
    /* ensure null-termination */
    if (content.at(content.length()-1 != '\0')) {
        content.push_back('\0');
    }

    return content;
}

int runGrpcServer(...) {
    [...]

    const std::string key_path("grpc/src/core/tsi/test_creds/server0.key");
    const std::string cert_path("grpc/src/core/tsi/test_creds/server0.pem");
    const std::string root_path("grpc/src/core/tsi/test_creds/ca.pem");

    auto ssl_server_cred_opts = grpc::SslServerCredentialsOptions();
    auto ssl_root_cert_pair = grpc::SslServerCredentialsOptions::PemKeyCertPair();
    ssl_root_cert_pair.private_key = read_file(key_path);
    ssl_root_cert_pair.cert_chain = read_file(cert_path);
    ssl_server_cred_opts.pem_key_cert_pairs.push_back(ssl_root_cert_pair);
    ssl_server_cred_opts.pem_root_certs = read_file(root_path);
    ssl_server_cred_opts.client_certificate_request = GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE;
    auto channel_creds = grpc::SslServerCredentials(ssl_server_cred_opts);
    ServerBuilder builder;
    builder.AddListeningPort(server_address, channel_creds);
    builder.RegisterService(&service);
    server = builder.BuildAndStart();
```

**Comment by edipascale** [comment]
I created a standalone test case with just the gRPC code above and it works normally, so the problem appears to be when gRPC is built using boringSSL and the application it is being used from is linking against openSSL for its own functionality, like in our case.

**Comment by matthewstevenson88** [comment]
Closing based on the most recent comment.
