### ISSUE TITLE
how to distinguish WriteDone and AsyncNotifyWhenDone called?

### ISSUE THREAD

**Issue by xiedeacc** [grpc/grpc#29865]
client WriteDone and AsyncNotifyWhenDone all will caused Next function returned a false ok, so how to distinguish it, pass different tags is ugly, for my process logic in a same class

**Comment by markdroth** [comment]
You should definitely pass different tags for different completions.  That's the intended way to tell which event is completed when the completion is delivered from the completion queue.

Many operations can complete with ok=false (e.g., a read or write operation can complete with ok=false if the connection is broken), so you can't use that to tell which operation was completed.

**Comment by xiedeacc** [comment]
can add a function to server context to distinguish?
