### ISSUE TITLE
grpc_tools.protoc has inconsistent descriptor_set_out depending on locale LANG setting

### ISSUE THREAD

**Issue by jonyscathe** [grpc/grpc#29930]
### What version of gRPC and what language are you using?
grpcio-tools==1.46.3

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.4 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10.4

### What did you do?
Ran following in two separate environments (one virtualenv, one docker devcontainer).
Eventually tracked down that the important difference between the two is that one's locale had LANG set to "C.UTF-8" and the other had LANG set to "en_AU.UTF-8"
```
python3 -m grpc_tools.protoc \
    --include_imports \
    --include_source_info \
    --proto_path="$DIR" \
    --python_out="$DST_DIR" \
    --grpc_python_out="$DST_DIR" \
    --mypy_out="quiet:$DST_DIR" \
    --mypy_grpc_out="quiet:$DST_DIR" \
    --descriptor_set_out="${SRC_DIR}/api_descriptor.pb" \
    "$SRC_DIR"/*.proto "$SRC_DIR"/lookup/*.proto
```
Importantly two of the protofiles were named similarly, eg example.proto and example_old_format.proto

### What did you expect to see?
api_descriptor.pb to be the same being run in both environments

### What did you see instead?
When built in the environment with LANG="en_AU.UTF-8" the block in api_descriptor.pb describing example_old_format.proto came **before** the block describing example.proto.
When built in the environment with LANG= "C.UTF-8"  the block in api_descriptor.pb describing example_old_format.proto came **after** the block describing example.proto.

It appears to me that the sections describing each proto file are sorted by the proto filenames.
With LANG="C.UTF-8" then example_old_format.proto > example.proto
With LANG="en_AU.UTF-8" then example_old_format.proto < example.proto
Seems a bit odd that ordering in a binary file would depend on the locale LANG setting for the OS.

### Anything else we should know about your project / environment?
I have fixed this for now by setting LC_ALL="C.UTF-8" within the bash script we use to compile the proto files. This way any sorting done will always be the same. 
This became an issue for us because we run the compile script as part of our CI pipeline to check that the compiled files are up to date - so we do need consistent output for this to make sense.

I have only tested this in Python which is why I raised this against gRPC Python, though this may not be a Python specific issue.

**Comment by gnossen** [comment]
`grpcio-tools` is a thin wrapper over `protoc` itself, along with the gRPC Python `protoc` plugin. The behavior that your'e describing seems to be coming from the protobuf codebase. I think this issue belongs there.

Feel free to reopen if you have reason to believe otherwise.
