### ISSUE TITLE
PROTOBUF_NAMESPACE_OPEN

### ISSUE THREAD

**Issue by Greendomisi** [grpc/grpc#29931]
### What version of gRPC and what language are you using?
1.46.3
### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04
### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC

### What did you do?
Commented out the lines:
#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protocol which is
#error incompatible with your Protocol Buffer headers. Please update
#error headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of the protocol which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protocol.
#endif

#include <google/protobuf/port_undef.inc>

### What did you expect to see?
A success fulcompilation

### What did you see instead?
error: ‘PROTOBUF_NAMESPACE_OPEN’ does not name a type

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
After commented project is ok.

**Comment by yashykt** [comment]
This seems to belong to the protobuf repository
