### ISSUE TITLE
Please provide protoc --csharp_out=grpc:<...> command for manual invocation

### ISSUE THREAD

**Issue by jhlgns** [grpc/grpc#29932]
### Is your feature request related to a problem? Please describe.
It would be very helpful if there was a way to compile gRPC from command line without the `<ItemGroup>`-Stuff.
This does not work with my approach of generating proto-files with a code-first approach since the ItemGroup/Protobuf stuff is evalutated before the proto file was generated.

### Describe the solution you'd like
`protoc --csharp_out=grpc:<whatever> ...`
Simply protoc for Asp.NET Core without the .csproj file. Please remove this constraint, thank you!
If there currently is a way to do this I would be happy about pointers how to do this!

### Describe alternatives you've considered
* Creating my own RPC framework because it is so frustrating working with gRPC in general (must create a two messages for every endpoint instead of just specifying the arguments and return type directly and then needing to generate the ServiceBase and then overriding the method, it's just too much friction for what it does) 
* Also another alternative would be to use my custom proto-Parser that can take RPC parameters directly without needing to declare messages for Request and Response but that still encompasses that I must implemented a generated interface instead of  just generating the proto file from Reflection (which I'm trying to do right now)

### Additional context
If anybody is interested in the proto-Parser/Preprocessor I might publish it

**Comment by jtattermusch** [comment]
You don't have to use the `Grpc.Tools` build integration with gRPC C#.
If directly invoking `protoc` (and `grpc_csharp_plugin`) from the command line is what you want, you can certainly do that (many projects do).
See documentation for the protocol buffer compiler (protoc) and example of how "manual" invocation can look like:
https://github.com/grpc/grpc/blob/v1.46.x/src/csharp/generate_proto_csharp.sh
