### ISSUE TITLE
memory leak in grpc async server cq write

### ISSUE THREAD

**Issue by FAKERINHEART** [grpc/grpc#30009]
### What version of gRPC and what language are you using?
1.44.0

### What operating system (Linux, Windows,...) and version?
linux
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Linux 5.10.75-79.358.amzn2.x86_64 #1 SMP Thu Nov 4 21:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 8.5.0 (GCC)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I started a async_server and async_client processes which are both based on cq. 
async_client is dead loop and sends requests to async_server

some client codes:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/13352188/173595017-95f67ca4-0b9c-42aa-8897-751fb9adadb3.png">

some server codes:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/13352188/173595187-2d2de1a9-10e9-4b4d-988d-9e7fbcaa13a9.png">

When the requests tps of async_client exceeds the ability of async_server's cq or channel, the async_server's unary Finish() that writes response bytes or unary read channel bytes will heap up in memory. Like the picture:

![IGCldxZQGB](https://user-images.githubusercontent.com/13352188/174791305-a85b7842-92f8-42b3-bdaf-2e5bfb9d7a24.jpg)

However when I stop the async_client, the memory in async_server still not released forever. As the picture:

This memory leak is only in the linux system, while mac OS is ok.

![14rXnYDOyy](https://user-images.githubusercontent.com/13352188/174791321-8d672ed7-ac6c-48e3-abeb-a1dc4b16b070.jpg)

### What did you expect to see?
grpc async server memory can be released

### What did you see instead?
grpc async server memory can not released
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by FAKERINHEART** [comment]
I have used valgrind to test the async_server, which no memory leak has been found and all response written in async_server are used with shared_prt. So I think that it may be memory leak underneath the grpc core or c++ codes.

**Comment by FAKERINHEART** [comment]
There are some channel of grpc trace log:

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/13352188/173611778-a924d0e3-5b54-4369-9133-227fdb276213.png">

**Comment by drfloob** [comment]
Especially given that this is not happening in your Mac OS environment using the same code, this may just be the way your platform/malloc implementation manages memory. Often times, freed memory is not immediately returned to the OS. See https://stackoverflow.com/questions/45538993/why-dont-memory-allocators-actively-return-freed-memory-to-the-os. If valgrind is happy, I'm guessing there's no leak.

**Comment by FAKERINHEART** [comment]
> Especially given that this is not happening in your Mac OS environment using the same code, this may just be the way your platform/malloc implementation manages memory. Often times, freed memory is not immediately returned to the OS. See https://stackoverflow.com/questions/45538993/why-dont-memory-allocators-actively-return-freed-memory-to-the-os. If valgrind is happy, I'm guessing there's no leak.

I think that it is not related to OS origin malloc, because when I replace it with tcmalloc, the result on linux is same.
Futhermore, as I mentioned above, the **RES memory** of async_server is not released **forever**, after the async_client was stopped or killed.

**Comment by drfloob** [comment]
It's difficult to determine what exactly is happening here. Parroting @yashykt 's request on that other thread:

> Could I ask you to collect some memory profiles (for example, with the google heap profiler tool) to see where the memory increase is coming from?

**Comment by FAKERINHEART** [comment]
I used gdb to dump these ~21g heap memory 
and use `strings -10 ` to show the content of it:
I found:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/13352188/174065863-82535651-22aa-4bba-bb29-c26867c9eae7.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/13352188/174065928-cfc83747-a127-4752-80d9-41778f8d235d.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/13352188/174065978-d1a468a0-5346-4228-8f7f-4e9187530cbd.png">

**Comment by FAKERINHEART** [comment]
@drfloob @yashykt

**Comment by FAKERINHEART** [comment]
@drfloob Hi, I have given my process's profile and log partially, and it seems like it leaks memory when watch dog fired, and its channel write buffer is not released correctly. Could you help to analyze it?

**Comment by FAKERINHEART** [comment]
update more profile for memory that grpc not released:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/13352188/174791505-6a1bb403-e523-4c60-b62f-91baf9eff70c.png">

**Comment by drfloob** [comment]
If this last profile the result of pprof? If so, I think you'll want to exclude pprof's own use of tcmalloc from the heap results, see https://gperftools.github.io/gperftools/heapprofile.html. And it may be useful to use `gv` to see which objects are actually taking up the bulk of the space.

Again, on linux, freed memory may not show up in RSS in a timely manner, so being concerned about RSS alone may be a red herring. I don't see anything obvious here that would differ between platforms, but you could try running your process using `GRPC_POLL_STRATEGY=poll` on Linux to rule that difference out. It will be slower, and I doubt that will fix anything.

We may be able to help further if you could produce a runnable minrepro.

**Comment by FAKERINHEART** [comment]
> If this last profile the result of pprof? If so, I think you'll want to exclude pprof's own use of tcmalloc from the heap results, see https://gperftools.github.io/gperftools/heapprofile.html. And it may be useful to use `gv` to see which objects are actually taking up the bulk of the space.
> 
> Again, on linux, freed memory may not show up in RSS in a timely manner, so being concerned about RSS alone may be a red herring. I don't see anything obvious here that would differ between platforms, but you could try running your process using `GRPC_POLL_STRATEGY=poll` on Linux to rule that difference out. It will be slower, and I doubt that will fix anything.
> 
> We may be able to help further if you could produce a runnable minrepro.

First of all, I've tried changing GRPC_POLL_STRATEGY but not take effect, and I've tried using tcmalloc instead of ptmalloc which have the same problem.

Whats more, I consider it is ordinary, as you said, that malloc system can retain the real physic memory(rss) immediately(not give back to system), when I call free() in my code, however, is it normal that it does not give back memory to system when it has occupied almost 35% percent physical memory of linux? As I mentioned above, I have freed all my memory in my codes in user space, but the server always retains its physical memory more and more to **OOM** not released. I think that you may explain what may have happened underneath the grpc codes? Is it a bug or a optimized point for grpc?
