### ISSUE TITLE
module @com_github_grpc_grpc//:grpc_lb_policy_ring_hash does not depend on a module exporting 'xxhash.h'

### ISSUE THREAD

**Issue by xlla** [grpc/grpc#30018]
### What version of gRPC and what language are you using?
v1.45.2
C++

### What operating system (Linux, Windows,...) and version?
macos 10.13.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
bazel 4.2.2
python 3.9.13

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

 git clone https://github.com/ray-project/ray
cd python
./build-wheel-macos.sh

or skip dependencies install, 

python3 setup.py bdist_wheel

or skip python wheel's files preparation, 

bazel build com_github_grpc_grpc//:grpc_lb_policy_ring_hash

### What did you expect to see?
build successful

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

<pre>
ERROR: /private/var/tmp/_bazel_xlla/3de94cb9ccb1129acaa2e0e472023d42/external/com_github_grpc_grpc/BUILD:3192:16: Compiling src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_xlla/3de94cb9ccb1129acaa2e0e472023d42/sandbox/darwin-sandbox/1684/execroot/com_github_ray_project_ray && \
  exec env - \
    PATH='/usr/local/opt/curl/bin:/usr/local/cuda/bin:/Users/xlla/.rvm/gems/ruby-2.2.3/bin:/Users/xlla/.cargo/env:/Users/xlla/.rustup/toolchains/stable-x86_64-apple-darwin/bin:/Users/xlla/.cargo/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/qt@5/bin/:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/tcl-tk/bin:/Users/xlla/.cargo/bin:/Users/xlla/opt/gnu-mcu-eclipse/arm-none-eabi-gcc/8.2.1-1.7-20190524-0603/bin:/Users/xlla/.rvm/gems/ruby-2.2.3/bin:/Users/xlla/.rvm/gems/ruby-2.2.3@global/bin:/Users/xlla/.rvm/rubies/ruby-2.2.3/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/CrossPack-AVR/bin:/Users/xlla/.rvm/bin:/opt/crosstool-ng/bin:/usr/local/cuda/bin:/usr/local/opt/python3/bin' \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/_objs/grpc_lb_policy_ring_hash/ring_hash.pic.d '-frandom-seed=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/_objs/grpc_lb_policy_ring_hash/ring_hash.pic.o' -fPIC -iquote external/com_github_grpc_grpc -iquote bazel-out/darwin-opt/bin/external/com_github_grpc_grpc -iquote external/com_google_googleapis -iquote bazel-out/darwin-opt/bin/external/com_google_googleapis -iquote external/upb -iquote bazel-out/darwin-opt/bin/external/upb -iquote external/com_google_protobuf -iquote bazel-out/darwin-opt/bin/external/com_google_protobuf -iquote external/com_google_absl -iquote bazel-out/darwin-opt/bin/external/com_google_absl -iquote external/zlib -iquote bazel-out/darwin-opt/bin/external/zlib -iquote external/com_github_cncf_udpa -iquote bazel-out/darwin-opt/bin/external/com_github_cncf_udpa -iquote external/com_envoyproxy_protoc_gen_validate -iquote bazel-out/darwin-opt/bin/external/com_envoyproxy_protoc_gen_validate -isystem external/com_github_grpc_grpc/include -isystem bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem external/zlib -isystem bazel-out/darwin-opt/bin/external/zlib -isystem external/com_github_grpc_grpc/third_party/xxhash -isystem bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/third_party/xxhash '-std=c++17' -Werror -w -DGRPC_BAZEL_BUILD -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-fmodule-name=@com_github_grpc_grpc//:grpc_lb_policy_ring_hash' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/grpc_lb_policy_ring_hash.cppmap' -fmodules-strict-decluse -Wprivate-header '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/gpr_base.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/grpc_base.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/grpc_client_channel.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/grpc_lb_subchannel_list.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/grpc_trace.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/ref_counted_ptr.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/sockaddr_utils.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_google_absl/absl/strings/strings.cppmap' '-fmodule-map-file=bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/third_party/xxhash/xxhash.cppmap' '-fmodule-map-file=external/local_config_cc/module.modulemap' -c external/com_github_grpc_grpc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc -o bazel-out/darwin-opt/bin/external/com_github_grpc_grpc/_objs/grpc_lb_policy_ring_hash/ring_hash.pic.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_grpc_grpc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc:25:10: error: module @com_github_grpc_grpc//:grpc_lb_policy_ring_hash does not depend on a module exporting 'xxhash.h'
#include "xxhash.h"
         ^
1 error generated.
INFO: Elapsed time: 35.198s, Critical Path: 14.58s
INFO: 205 processes: 9 internal, 196 darwin-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/xlla/git/ray/python/setup.py", line 723, in <module>
    setuptools.setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/Users/xlla/git/ray/python/setup.py", line 711, in run
    return pip_run(self)
  File "/Users/xlla/git/ray/python/setup.py", line 612, in pip_run
    build(True, BUILD_JAVA, True)
  File "/Users/xlla/git/ray/python/setup.py", line 560, in build
    return bazel_invoke(
  File "/Users/xlla/git/ray/python/setup.py", line 327, in bazel_invoke
    result = invoker([cmd] + cmdline, *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/bazel', 'build', '--verbose_failures', '--', '//:ray_pkg', '//cpp:ray_cpp_pkg']' returned non-zero exit status 1.
</pre>

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
@xlla Do you encounter this problem even when building `//:grpc`?

**Comment by gnossen** [comment]
@yashykt This doesn't seem to actually be Python-specific. Can you please take a look?

**Comment by yashykt** [comment]
we remain unable to reproduce this

**Comment by yashykt** [comment]
we do use bazel version 5.3.0, so maybe that's the reason?

**Comment by yashykt** [comment]
since this library does depend on `xxhash` which exports `xxhash.h`

https://github.com/grpc/grpc/blob/e59a3e25caa392634ec4b44d5eb1f308d16688e2/src/core/BUILD#L4473
