### ISSUE TITLE
Possible bug in server-side secure transport setup

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#3003]
In case of an error, we're using the wrapped_endpoint here:
https://github.com/grpc/grpc/blob/master/src/core/security/server_secure_chttp2.c#L149

Which at this point, is already destroyed by:
https://github.com/grpc/grpc/blob/master/src/core/security/secure_transport_setup.c#L74

Am I missing something?

**Comment by ctiller** [comment]
Yang's going to address this as part of the handshake work he's doing.

**Comment by yang-g** [comment]
I think this is fixed.
