### ISSUE TITLE
which api should call on server when client suddenly gone?

### ISSUE THREAD

**Issue by xiedeacc** [grpc/grpc#30062]
when server read from client, but client suddenly gone, server reader's tag like ServerAsyncReader will be returned with a false ok, then I tried use ServerAsyncReader::FinishWithError to tell client finish, but will core in call_op_set.h: ContinueFillOpsAfterInterception:if (err != GRPC_CALL_OK) {GPR_CODEGEN_ASSERT(false);}, so I guess I shoudn't call FinishWithError, should I use ServerContext::TryCancel instead?

**Comment by veblush** [comment]
The "new issue" form clearly asks users not to post questions as github issues. Next time please follow the instructions and use the channels mentioned below to ask questions.

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
>
