### ISSUE TITLE
Grpc.Core.Xamarin NuGet packages missing starting from v2.45.x

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#30071]
### What version of gRPC and what language are you using?
Grpc.Core 2.46

### What operating system (Linux, Windows,...) and version?
Android

### What runtime / compiler are you using (e.g. python version or version of gcc)
net6-android

### What did you do?
I tried to update my Android project.

### What did you expect to see?
Grpc.Core.Xamarin having packages for 2.45 and 2.46 on nuget.org

### What did you see instead?
The last package is 2.44 from 4 months ago.

**Comment by Falco20019** [comment]
I'm aware of https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ but it would be great if these could be added since they are basically the only ones missing until support was dropped and the library was frozen. I was able to import them without any issue in .NET 6 for Android, but to be safe, I would prefer having the correct `.so` files to not being stuck with 2.44 for all platforms.

This was the workaround BTW since the builds file is only checking for `MonoAndroid`. I totally understand that this won't be addressed anymore due to the freeze, so I will just leave it here in case someone else needs it:
```xml
<!-- Workaround for Grpc.Core.Xamarin -->
<PropertyGroup>
  <Grpc_SkipNativeLibsCopy>true</Grpc_SkipNativeLibsCopy>
</PropertyGroup>
<ItemGroup>
  <!-- TODO: Use $(GrpcVersion) once latest builds are available! -->
  <PackageReference Include="Grpc.Core.Xamarin" Version="2.44.0" GeneratePathProperty="true" />
  <AndroidNativeLibrary Include="$(PkgGrpc_Core_Xamarin)\native\android\arm64-v8a\libgrpc_csharp_ext.so" />
  <AndroidNativeLibrary Include="$(PkgGrpc_Core_Xamarin)\native\android\armeabi-v7a\libgrpc_csharp_ext.so" />
  <AndroidNativeLibrary Include="$(PkgGrpc_Core_Xamarin)\native\android\x86\libgrpc_csharp_ext.so" />
</ItemGroup>
```

**Comment by jtattermusch** [comment]
I investigated a little bit.
The problem with the more recent Grpc.Core.Xamarin nuget packages is their size.
Starting from 2.45.x, the size of the nuget package got slightly bigger and it crossed the maximum package size threshold accepted by nuget.org.
So the Grpc.Core.Xamarin nugets up to version 2.46.x still exist and they were built correctly as part of the release, but it seems that can't be uploaded to nuget.org anymore (= too big filesize).

**Comment by jtattermusch** [comment]
If it helps, https://storage.googleapis.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/linux/grpc_build_packages/20006/20220520-030337/github/grpc/artifacts/Grpc.Core.Xamarin.2.46.3.nupkg is the latest build of Grpc.Core.Xamarin nuget - the link should be publicly accessible (and the nuget is too big to upload to nuget.org).

**Comment by Falco20019** [comment]
Thank you very much. This indeed does help. I will upload it on our Artifactory.
