### ISSUE TITLE
how cross compile for armv8 use bazel

### ISSUE THREAD

**Issue by xiedeacc** [grpc/grpc#30085]
I need cross compile grpc for openwrt armv8, use --incompatible_enable_cc_toolchain_resolution will cause fail, error log:
```
ERROR: /root/.cache/bazel/_bazel_root/18af67323127713f38ae23b76a85b492/external/com_google_protobuf/BUILD:387:15: Generating Descriptor Set proto_library @com_google_protobuf//:any_proto failed: (Exit 2): protoc failed: error executing command bazel-out/k8-opt-exec-A048C86A/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/any_proto' ... (remaining 6 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
bazel-out/k8-opt-exec-A048C86A/bin/external/com_google_protobuf/protoc: 1: Syntax error: word unexpected (expecting ")")

```

**so how to cross compile grpc for armv8 use bazel?**

 here is some info:
bazel version: 5.2.0
build command:
```
clear && bazel-5.2 build --copt=-O0 --copt=-g3 --strip=never --incompatible_enable_cc_toolchain_resolution --platforms=@bazel_build_file//platforms:linux_gcc11_aarch64_none_musleabi -s //:grpc
```
a grpc fork demo:
[https://github.com/xiedeacc/grpc.git](https://github.com/xiedeacc/grpc.git)

FYI, my toolchains do not have any problem, I have test it by compiled a hello world and executed it on openwrt armv8 platform

demo just only add toolchains to WORKSPACE file, no anyother diff with original grpc repo

**Comment by xiedeacc** [comment]
FYI, my toolchains do not have any problem, I have test it by compiled a hello world and executed it on openwrt armv8 platform

**Comment by yashykt** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
