### ISSUE TITLE
Failed to pick subchannel for CallbackService 

### ISSUE THREAD

**Issue by choufler** [grpc/grpc#30106]
### What version of gRPC and what language are you using?
1.36.0

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc v 8.3.1

### What did you do?
implemented a CallbackService (as descirbed in)
https://github.com/grpc/proposal/blob/master/L67-cpp-callback-api.md

on a server side, started the server on 0.0.0.0, also tried 127.0.0.1

### What did you expect to see?
client being able to connect and get dat

### What did you see instead?
same issue has here: client is getting an error 'Failed to pick up subchannel'
https://github.com/grpc/grpc/issues/23340

experimented with different clients: python, c++ async, python async - same issue.
experimented with different version of addreses.

as long as I change the server implementation back to synchronous service,
I get a service method call immediately.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

### Anything else we should know about your project / environment?
when I enable trace and debug I see the CQ is being polled every second or so until the time out reached.

The first error I get is ```'connection attempt timed out before receiving SETTINGS' in chttp2_connector.cc, line 237```

**Comment by yashykt** [comment]
The gRPC version you are using is too old. Please try it with the latest one. 1.36 does not have the polling required for the callback API.

**Comment by choufler** [comment]
thanks, 
I am not in a full control to install a newewst version.
Which is the lowest one that  does have polling, please?
