### ISSUE TITLE
Posix poll is continuously sending POLLHUP event, resulting more CPU utilization

### ISSUE THREAD

**Issue by darsh-b88** [grpc/grpc#30100]
### What version of gRPC and what language are you using?
v1.27.3

### What operating system (Linux, Windows,...) and version?
QNX

### What runtime / compiler are you using (e.g. python version or version of gcc)
CPP

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
We are using POSIX POLLING.
1. Run the gRPC server with Async as well as Sync channel
2. Create a new client, which will create one more Async channel
3. The client will shutdown, after his work is done
4. But we are getting continuous POLLHUP event and the timer is coming out of poll(), which results in looping(more CPU Consumption)
This can be seen at ev_poll_posix.cc line 1024, where the r=1, and somehow the watchers[i].fd = nullptr
This POLLHUP event is not passed to server, which can remove the link or clear the client data

### What did you expect to see?
Either POLLHUP event should be passed to application layer, so that OK flag (false) can be handled
Or handle the POLLHUP event before poling starts

### What did you see instead?
More CPU utilization due to for loop

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by darsh-b88** [comment]
`More logs attached--
D0101 12:46:45.144997891      16 tcp_posix.cc:689]                     DATA: <----SOME--DATA---->
I0101 12:46:45.144997891      15 completion_queue.cc:1319]             RETURN_EVENT[1114b390]: OP_COMPLETE: tag:fcf1938 OK
I0101 12:46:45.144997891      16 call.cc:1565]                         ops[0]: RECV_INITIAL_METADATA ptr=11180f48
I0101 12:46:45.144997891      15 completion_queue.cc:1419]             grpc_completion_queue_shutdown(cq=1114b390)
I0101 12:46:45.144997891      16 parsing.cc:681]                       parsing initial_metadata
I0101 12:46:45.144997891      15 completion_queue.cc:1226]             grpc_completion_queue_pluck(cq=1114b390, tag=111ce920, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0)
I0101 12:46:45.144997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: :scheme: 68 74 74 70 'http'
I0101 12:46:45.144997891      15 completion_queue.cc:1319]             RETURN_EVENT[1114b390]: OP_COMPLETE: tag:111ce920 OK
I0101 12:46:45.144997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: :method: 50 4f 53 54 'POST'
I0101 12:46:45.145997891      15 completion_queue.cc:1226]             grpc_completion_queue_pluck(cq=1114b390, tag=fcf1b98, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0)
I0101 12:46:45.145997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: :authority: 31 32 37 2e 30 2e 30 2e 31 3a 36 32 34 37 32 '127.0.0.1:62472'
I0101 12:46:45.145997891      15 completion_queue.cc:1319]             RETURN_EVENT[1114b390]: QUEUE_SHUTDOWN
I0101 12:46:45.145997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: :path: <----SOME--DATA---->
I0101 12:46:45.145997891      15 metadata_array.cc:34]                 grpc_metadata_array_destroy(array=111cbfe8)
I0101 12:46:45.145997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: te: 74 72 61 69 6c 65 72 73 'trailers'
I0101 12:46:45.145997891      15 call.cc:573]                          grpc_call_unref(c=111cc520)
I0101 12:46:45.145997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
I0101 12:46:45.145997891      15 metadata_array.cc:34]                 grpc_metadata_array_destroy(array=111ccf88)
I0101 12:46:45.145997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: user-agent: <----SOME--DATA---->
I0101 12:46:45.146997891      15 metadata_array.cc:34]                 grpc_metadata_array_destroy(array=111cbfe8)
I0101 12:46:45.146997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: grpc-accept-encoding: 69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'
I0101 12:46:45.146997891      15 completion_queue.cc:1425]             grpc_completion_queue_destroy(cq=1114b390)
I0101 12:46:45.146997891      16 parsing.cc:430]                       HTTP:3:HDR:SVR: accept-encoding: 69 64 65 6e 74 69 74 79 2c 67 7a 69 70 'identity,gzip'
I0101 12:46:45.146997891      15 completion_queue.cc:1419]             grpc_completion_queue_shutdown(cq=1114b390)
D0101 12:46:45.146997891      16 flow_control.cc:113]                  11192cc0[3][svr] |   data recv | trw:                       4194302, tlw:                       4194304, taw:            4194304 -> 4194284, srw:                       4194304, slw:            4194304 -> 4194284, saw:            4194304 -> 4194284
I0101 12:46:45.146997891      15 completion_queue.cc:982]              grpc_completion_queue_next(cq=11179ae0, deadline=gpr_timespec { tv_sec: 46013, tv_nsec: 211172136, clock_type: 0 }, reserved=0)
D0101 12:46:45.146997891      16 flow_control.cc:113]                  11192cc0[0][svr] | t updt recv | trw:            4194302 -> 4194304, tlw:                       4194304, taw:                       4194284, srw:                              , slw:                              , saw:
I0101 12:46:45.146997891      16 timer_generic.cc:468]                 TIMER 11192f50: CANCEL pending=true
I0101 12:46:45.146997891      16 tcp_posix.cc:887]                     TCP:1117ef90 got_read: "No Error"
I0101 12:46:45.146997891      16 tcp_posix.cc:879]                     TCP:1117ef90 do_read
I0101 12:46:45.146997891      16 tcp_posix.cc:541]                     TCP:1117ef90 notify_on_read
I0101 12:46:45.147997891      16 call.cc:626]                          OP[server:11180e40]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 channel_stack.cc:226]                 OP[message_size:11180e58]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 channel_stack.cc:226]                 OP[deadline:11180e70]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 channel_stack.cc:226]                 OP[http-server:11180e88]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 channel_stack.cc:226]                 OP[message_compress:11180ea0]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 channel_stack.cc:226]                 OP[connected:11180eb8]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 chttp2_transport.cc:1658]             perform_stream_op[s=11181960]:  RECV_INITIAL_METADATA
I0101 12:46:45.147997891      16 chttp2_transport.cc:1360]             perform_stream_op_locked:  RECV_INITIAL_METADATA; on_complete = 0
I0101 12:46:45.147997891      16 call.cc:1565]                         ops[0]: RECV_MESSAGE ptr=11180f68
I0101 12:46:45.148997891      16 call.cc:626]                          OP[server:11180e40]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 channel_stack.cc:226]                 OP[message_size:11180e58]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 channel_stack.cc:226]                 OP[deadline:11180e70]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 channel_stack.cc:226]                 OP[http-server:11180e88]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 channel_stack.cc:226]                 OP[message_compress:11180ea0]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 channel_stack.cc:226]                 OP[connected:11180eb8]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 chttp2_transport.cc:1658]             perform_stream_op[s=11181960]:  RECV_MESSAGE
I0101 12:46:45.148997891      16 timer_generic.cc:365]                 TIMER 11192f50: SET 7216191 now 16191 call 11192ed0[78a63228]
I0101 12:46:45.148997891      16 timer_generic.cc:402]                   .. add to shard 6 with queue_deadline_cap=17011 => is_first_timer=false
I0101 12:46:45.148997891      16 chttp2_transport.cc:1360]             perform_stream_op_locked:  RECV_MESSAGE; on_complete = 0
I0101 12:46:45.149997891      16 completion_queue.cc:706]Darsh: at pollset_work line 1057 pfd_count=3, pfds[1].revents=0, watchers[1].fd=11152400
             Darsh: at pollset_work line 1057 pfd_count=3, pfds[2].revents=0, watchers[2].fd=1114e500
 cq_end_op_for_next(cq=11152ec0, tag=1114ff60, error="No Error", done=789eae24, done_arg=1114b550, storage=1114b588)Darsh: at pollset_work line 1001 pfd_count=1, i=0

Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
I0101 12:46:45.149997891      16 completion_queue.cc:1083]Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
            Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
 Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
RETURN_EVENT[11152ec0]: OP_COMPLETE: tag:1114ff60 OK
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
I0101 12:46:45.149997891      16 call.cc:1967]Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
                        Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
 Darsh: at pollset_work line 1001 pfd_count=1, i=0
grpc_call_start_batch(call=111804e0, ops=fcb0838, nops=1, tag=111828c0, reserved=0)Darsh: at pollset_work line 1001 pfd_count=2, i=1

Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
I0101 12:46:45.149997891      16 call.cc:1565]Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
                        Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
 ops[0]: RECV_CLOSE_ON_SERVER cancelled=1118292c
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
I0101 12:46:45.149997891      16 call.cc:626]Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
                         Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
 Darsh: at pollset_work line 1001 pfd_count=1, i=0
OP[server:11180e40]:  RECV_TRAILING_METADATADarsh: at pollset_work line 1001 pfd_count=2, i=1

Darsh: at pollset_work line 1001 pfd_count=3, i=2
I0101 12:46:45.149997891      16 channel_stack.cc:226]Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
                Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
 Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
OP[message_size:11180e58]:  RECV_TRAILING_METADATA
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
I0101 12:46:45.149997891      16 channel_stack.cc:226]Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
                 Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
OP[deadline:11180e70]:  RECV_TRAILING_METADATADarsh: at pollset_work line 1001 pfd_count=1, i=0

Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
I0101 12:46:45.150997891      16 channel_stack.cc:226]Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
                Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
 Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
OP[http-server:11180e88]:  RECV_TRAILING_METADATA
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
I0101 12:46:45.150997891      16 channel_stack.cc:226]Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
                Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
 Darsh: at pollset_work line 1001 pfd_count=1, i=0
OP[message_compress:11180ea0]:  RECV_TRAILING_METADATADarsh: at pollset_work line 1001 pfd_count=2, i=1

Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
I0101 12:46:45.150997891      16 channel_stack.cc:226]Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
                Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
 OP[connected:11180eb8]:  RECV_TRAILING_METADATA
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
I0101 12:46:45.150997891      16 chttp2_transport.cc:1658]Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
            Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
 Darsh: at pollset_work line 1001 pfd_count=1, i=0
perform_stream_op[s=11181960]:  RECV_TRAILING_METADATADarsh: at pollset_work line 1001 pfd_count=2, i=1

Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
I0101 12:46:45.150997891      16 chttp2_transport.cc:1360]            Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
 perform_stream_op_locked:  RECV_TRAILING_METADATA; on_complete = 0Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750

Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
I0101 12:46:45.150997891      16 server.cc:1532]Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
                      Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
 Darsh: at pollset_work line 1001 pfd_count=1, i=0
grpc_server_request_registered_call(server=111529d0, rmp=1112c3b0, call=111d06f0, deadline=111c0720, initial_metadata=111c0760, optional_payload=111d0830, cq_bound_to_call=1114b040, cq_for_notification=11152ec0, tag=111d06b0)Darsh: at pollset_work line 1001 pfd_count=2, i=1

Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
I0101 12:46:45.151997891      16 completion_queue.cc:982]Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
             Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
 grpc_completion_queue_next(cq=11152ec0, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0)Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400

Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1013 pfd_count=3, i=1 watchers[1].fd=11151b60
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1013 pfd_count=3, i=2 watchers[2].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750
Darsh: at pollset_work line 1057 pfd_count=4, pfds[1].revents=0, watchers[1].fd=11152400
Darsh: at pollset_work line 1057 pfd_count=4, pfds[2].revents=64, watchers[2].fd=0
Darsh: at pollset_work line 1057 pfd_count=4, pfds[3].revents=0, watchers[3].fd=1114d750
Darsh: at pollset_work line 1001 pfd_count=1, i=0
Darsh: at pollset_work line 1001 pfd_count=2, i=1
Darsh: at pollset_work line 1001 pfd_count=3, i=2
Darsh: at pollset_work line 1013 pfd_count=4, i=1 watchers[1].fd=11152400
Darsh: at pollset_work line 1013 pfd_count=4, i=2 watchers[2].fd=1114e500
Darsh: at pollset_work line 1013 pfd_count=4, i=3 watchers[3].fd=1114d750`

**Comment by darsh-b88** [comment]
I am not sure what is the right way. But I can suggest one change which is working, its as below:
In file https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/ev_poll_posix.cc
line 1058
          if (watchers[i].fd == nullptr) {
            fd_end_poll(&watchers[i], 0, 0);
            gpr_atm_no_barrier_store(&pollset->fds[i-1]->pollhup, 1);
          } 

Can somebody check if I am doing it correct, because I am changing the pollset variable.

**Comment by darsh-b88** [comment]
@kpayson64 what is you opinion on my above suggestion?

**Comment by markdroth** [comment]
Version 1.27 is really ancient, and there have been a huge amount of code changes since then.  Please try upgrading to the current version and see if the problem is still happening.  If it is, please file a new issue.  Thanks!
