### ISSUE TITLE
Error happens when grpc client running in a container

### ISSUE THREAD

**Issue by Eileen-Yu** [grpc/grpc#30127]
Hi, folks. I got a similar case happens in: https://github.com/grpc/grpc/issues/4689

What occurs to me is my nodejs grpc client running in my localhost (`macos`) can access to my remote grpc server successfully.

However, when I containerized the client app and run it either in docker runtime or k8s, it failed with errors logs as follow:
```
E0627 23:14:02.620652415     751 ssl_transport_security.cc:682] Invalid cert chain file.
E0627 23:14:02.620756726     751 ssl_security_connector.cc:112] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0627 23:14:02.620890860     751 secure_channel_create.cc:132] Failed to create secure subchannel for secure name 'host.docker.internal:5060'
E0627 23:14:02.621037765     751 secure_channel_create.cc:50] Failed to create channel args during subchannel creation.
  pkgs:server falco client encountered an error: Error: 14 UNAVAILABLE: Empty update +5ms
  pkgs:server falco status: {
  pkgs:server   code: 14,
  pkgs:server   details: 'Empty update',
  pkgs:server   metadata: Metadata { _internal_repr: {}, flags: 0 }
  pkgs:server } +1ms
```

What I'm pretty sure is this is not an error of human operation such as invalid cert or dns resolution. Because the connection can be successfully setup in the host machine. Also, when the failure happens, the server side never received any package.

So I guess this happens at the client side in its very beginning period to setup the request.

It looks like a relative case to https://stackoverflow.com/questions/66965898/grpc-c-handshaker-factory-creation-failed-with-tsi-invalid-argument

However, intalling `libssl` and `openssl` in the container did not resolve the issue.

Wondering if someone have any suggestions on how we can go over this? Thx! 🙏

**Comment by yashykt** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
