### ISSUE TITLE
Difference between grpc.tools protoc & official protoc?

### ISSUE THREAD

**Issue by derekantrican** [grpc/grpc#30120]
### What version of gRPC and what language are you using?

2.47.0 C#

### What operating system (Linux, Windows,...) and version?

Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)

.NET

### What did you do?

1. I downloaded the grpc.tools 2.47.0 package via https://www.nuget.org/api/v2/package/Grpc.Tools/2.47.0 & unzipped to get the contents
2. I ran the following: `...\grpc.tools.2.47.0\tools\windows_x64\protoc.exe --csharp_out Output Messages.proto`. Note that Messages.proto has the following first couple lines:
```proto
syntax = "proto3";
import "google/protobuf/wrappers.proto";
```
3. I got the following output:
```
google/protobuf/wrappers.proto: File not found.
Messages.proto:3:1: Import "google/protobuf/wrappers.proto" was not found or had errors.
Messages.proto:39:5: "google.protobuf.Int32Value" is not defined.
```
4. I noted that the version of protoc in this package (at least according to file properties) is 3.19.4, so I downloaded the official version from https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.4 and ran the same command as above (and in the same directory). **There were no issues**

### What did you expect to see?

I expected to see the same results from each.

**Comment by derekantrican** [comment]
As a side question: how is the version of protoc determined for the grpc.tools package?

**Comment by derekantrican** [comment]
Ah, I'm realizing that the official protoc package has the ...\protoc-3.19.4-win64\include\google\protobuf directory - that's probably what's missing, not an actual difference in the protoc compiler. Where can I find these includes in the grpc.tools package?

**Comment by jtattermusch** [comment]
> As a side question: how is the version of protoc determined for the grpc.tools package?

It is based on the version of the protobuf in the third_party/protobuf git submodule (we regularly update the submodule to the newest released version of protobuf).
