### ISSUE TITLE
Multiprocessing example client fails

### ISSUE THREAD

**Issue by niquepolice** [grpc/grpc#30133]
Running directly server and client as described in https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing results in an exception in client:

`multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7ff058f1c490>'. Reason: 'TypeError("cannot pickle '_thread.RLock' object")'`

### What version of gRPC and what language are you using?
grpcio                 1.46.3
grpcio-tools           1.46.3
Python 3.10.4

### What operating system (Linux, Windows,...) and version?
Linux fedora 5.16.18-200.fc35.x86_64

There are some answers on StackOverflow about this error, but I didn't realize how to apply them to that issue.

**Comment by gnossen** [comment]
@niquepolice Can you please include the full logs?

**Comment by niquepolice** [comment]
@gnossen Yes, please see the attachment

[mp_logs.txt](https://github.com/grpc/grpc/files/9014814/mp_logs.txt)

**Comment by XuanWang-Amos** [comment]
Tried it locally and able to reproduce it.

After enabled core logs, I can see it's complaining about domain name not found:
`D0112 00:22:48.243769069  239419 dns_resolver_ares.cc:326]             (c-ares resolver) resolver:0x55a61e884f10 dns resolution failed: UNKNOWN:C-ares status is not ARES_SUCCESS qtype=AAAA name=51951 is_balancer=0: Domain name not found {created_time:"2024-01-12T00:22:48.243555102+00:00", children:[UNKNOWN:C-ares status is not ARES_SUCCESS qtype=A name=51951 is_balancer=0: Domain name not found {created_time:"2024-01-12T00:22:48.24203175+00:00"}]}`

After checking the code, looks like you're not using the correct server address, you should use `localhost:38247` when start client like we mentioned in `client.py`: https://github.com/grpc/grpc/blob/acc1ad1b2b64139eec06e2803f4d2fa06ab546d2/examples/python/multiprocessing/client.py#L84-L86
