### ISSUE TITLE
Interprocess (shm or pipe) transport

### ISSUE THREAD

**Issue by jgcodes2020** [grpc/grpc#30131]
### Is your feature request related to a problem? Please describe.
I'm new to this library and I'm looking to use it as an IPC mechanism between two processes. However, it seems that all currently available transports revolve around networks, sockets, and network protocols (I'm not sure if there is support for Windows AF_UNIX sockets).

### Describe the solution you'd like
I'd like there to be a shared-memory or pipe-based transport that doesn't depend on sockets or networks.

### Describe alternatives you've considered
The alternatives to using this library include:
- Rolling my own RPC using message queues (Boost IPC)
- Rolling my own transport, though the documentation is not exactly good

### Additional context
If rolling my own transport is the best option here, how should I look at the documentation?

**Comment by bbsclient** [comment]
Supporting AF_UNIX on Windows has been asked for before but has not yet been implemented: https://github.com/grpc/grpc/issues/22285
