### ISSUE TITLE
Metadata validation/key transformation in wrapping languages

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#3016]
Languages wrapping the C core should do the following:

 - Verify that keys ending with '-bin' have binary value types and keys not ending in '-bin' have string value types **and/or** that keys not ending in '-bin' have values that are in the restricted character set of printable ASCII characters + space. This check can be done after the core indicates that there was an error with the metadata.

 - Restrict the character set of metadata keys to lowercase alphanumeric characters, hyphen, and underscore. This can be done in part by normalizing keys by downcasing them. Otherwise, this check can also be deferred until after receiving an error from the core.

**Comment by ctiller** [comment]
Please make sure there's a bug per-language and someone assigned.

**Comment by nathanielmanistaatgoogle** [comment]
I think I said this in conversation last week, but just to repeat in writing: Python doesn't plan to do any data-massaging. We'll pass what we get from applications to the core, which will either accept it or not, and we'll communicate any error back to the application.

Shout at me if we're wrong about that? I have an aversion to magic data massaging, and I don't think I'm yet aware of the use case for "application, more than simply can't be bothered to pass valid data, is not able to pass valid data, and needs this transformation done for it".

**Comment by nathanielmanistaatgoogle** [comment]
After meatspace discussion our Python sub-bug is #3042. 

(Dropping the Python label from this bug.)

**Comment by jayantkolhe** [comment]
Dropping ObjC Label as it is covered by #2761

**Comment by jtattermusch** [comment]
"lowercase alphanumeric characters and hyphen" - does that mean no underscore allowed? just checking.

**Comment by ctiller** [comment]
We added underscore as a late change - to avoid changing node's unit tests
:)

**Comment by murgatroid99** [comment]
Ironically, I removed the underscores from those tests as part of my change to resolve this issue in Node.

**Comment by nathanielmanistaatgoogle** [comment]
The Force is in balance: I replaced spaces in my test metadata keys with underscores. :-)

**Comment by tbetbetbe** [comment]
> I think I said this in conversation last week, but just to repeat in writing: Python doesn't plan to do any data-massaging. We'll pass what we get from applications to the core, which will either accept it or not, and we'll communicate any error back to the application.

Same for ruby: #3154, dropping ruby from this issue

**Comment by tbetbetbe** [comment]
@jayantkolhe: Removing the Beta milestone.

Rationale:
In call cases, this behaviour does not require a surface API change, and if not present in the beta release can be rolled-out as a point upgrade

**Comment by murgatroid99** [comment]
I don't think there's anything left to be done on this bug. All of the languages have either done this or opened their own issue for it.
