### ISSUE TITLE
Stateful session affinity for stateful services

### ISSUE THREAD

**Issue by sanjaypujare** [grpc/grpc#30171]
### Is your feature request related to a problem? Please describe.
In stateful services, once a particular "session" is assigned by a load-balancer to a particular service backend, all future activity on that session must be routed to the same service backend. With consistent hash based implementation, any time the set of backend servers changes (hosts are removed or added), the hash mapping of 1/N client sessions gets affected which would lead to dropped requests in case of stateful services. To address this issue it will be good to have "stateful session affinity" implemented in gRPC.

### Describe the solution you'd like
Envoy has recently added stateful session affinity extension through the use of cookies that store the “mapping state” and enables the extension to override the load-balancing decision if such state information is available. The way this would work is the application (client) would send the first request in a session without the cookie. gRPC would include a Cookie in the response and the client would use that Cookie value in all the subsequent requests in that session. gRPC will use the Cookie to route the request as described above.

### Describe alternatives you've considered
Consistent hash based load balancing has the issue described above.

### Additional context
Envoy implementation references:
https://github.com/envoyproxy/envoy/issues/16698
https://github.com/envoyproxy/envoy/pull/17848
https://github.com/envoyproxy/envoy/pull/18207

Protos:
https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/stateful_session/v3/stateful_session.proto
https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/http/stateful_session/cookie/v3/cookie.proto

Doc:
https://docs.google.com/document/d/1IU4b76AgOXijNa4sew1gfBfSiOMbZNiEt5Dhis8QpYg/edit#

**Comment by sanjaypujare** [comment]
CC @louiscryan @costinm

**Comment by markdroth** [comment]
This has been implemented in C-core.  See [gRFC A55](https://github.com/grpc/proposal/blob/master/A55-xds-stateful-session-affinity.md).

**Comment by cvigo** [comment]
[A55](https://github.com/grpc/proposal/blob/master/A55-xds-stateful-session-affinity.md) says _there are no current plans to implement in any other language_, which is a real shame!!

**Comment by markdroth** [comment]
That's correct.  If you'd like to see this in other languages, please file a feature request in the repos for those languages.
