### ISSUE TITLE
Posix poll is continuously sending POLLHUP event, resulting more CPU utilization

### ISSUE THREAD

**Issue by darsh-b88** [grpc/grpc#30190]
### What version of gRPC and what language are you using?
v1.47.0, the tip of master

### What operating system (Linux, Windows,...) and version?
POSIX version

### What runtime / compiler are you using (e.g. python version or version of gcc)
CPP

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

We are using POSIX POLLING.

Run the gRPC server with Async as well as Sync channel
Create a new client, which will create one more Async channel
The client will shutdown, after his work is done
But we are getting continuous POLLHUP event and the timer is coming out of poll(), which results in looping(more CPU Consumption)
This can be seen at ev_poll_posix.cc line 1024, where the r=1, and somehow the watchers[i].fd = nullptr

we need to have a correct handling if the watchers[i].fd = nullptr, then add this watcher as POLLHUP
This continuous loop will increase the CPU consumption.

### What did you expect to see?
POLLHUP event should be handled properly. The CPU consumption should be minimal.

### What did you see instead?
More CPU utilization due to for loop

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I have a fix which is working fine, but I am using the pollset variable, which I am not sure is good to use it or not.
In file https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/ev_poll_posix.cc
line 1058
if (watchers[i].fd == nullptr) {
    fd_end_poll(&watchers[i], 0, 0);
    gpr_atm_no_barrier_store(&pollset->fds[i-1]->pollhup, 1);
}
[Logs.txt](https://github.com/grpc/grpc/files/9036865/Logs.txt)

**Comment by darsh-b88** [comment]
[markdroth](https://github.com/markdroth) please help to check this. We are blocked with this.

**Comment by darsh-b88** [comment]
@kpayson64 what is your opinion on above suggestion/solution for POLLHUP?

**Comment by darsh-b88** [comment]
@markdroth please help us.

**Comment by darsh-b88** [comment]
@drfloob can you please help to check this ticket

**Comment by darsh-b88** [comment]
Is there anyone who can help on this?

**Comment by drfloob** [comment]
@Vignesh2208 can you take a look at this one? I believe you're most familiar with the poll poller's inner-workings at this point.

@darsh-b88 please provide a running minrepro to help debug this. Do I understand correctly that the server is seeing continuous POLLHUP (not the client)? And can this behavior be reliably reproduced, or does it happen intermittently? And what platform and operating system are you running this on?

**Comment by darsh-b88** [comment]
Do I understand correctly that the server is seeing continuous POLLHUP (not the client)?
**_YES_**
And can this behavior be reliably reproduced, or does it happen intermittently?
**_Reliably reproduced_**
And what platform and operating system are you running this on?
**_POSIX, we are using QNX OS_**

Did you agree with the logic which I shared?

**Comment by darsh-b88** [comment]
@Vignesh2208 do you have any comments?

**Comment by Vignesh2208** [comment]
> https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/ev_poll_posix.cc

I dont think we should be indexing directly into the pollset variable. It requires acquiring/releasing pollset mutex which can be expensive. 

I think https://github.com/grpc/grpc/pull/30421 might be a cleaner fix. Can you check if it works with your setup ?

**Comment by darsh-b88** [comment]
Thank you @Vignesh2208 , its working good. Please help to merge the change.

**Comment by darsh-b88** [comment]
@Vignesh2208 any update?

**Comment by Vignesh2208** [comment]
Sorry the original PR caused TSAN failures. I made some updates. Can you try now ?

**Comment by darsh-b88** [comment]
Hi Vignesh the latest changes are working fine. Please help to merge.
