### ISSUE TITLE
 unrecognized command line option '-std=c++14'

### ISSUE THREAD

**Issue by basbroens** [grpc/grpc#30260]
When i try to install grpc with pecl i keep getting:

g++: error: unrecognized command line option '-std=c++14'

But my gcc version is: 

g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

I guess pecl uses the wrong gcc or something. But i cant specify it.

What im a missing?

**Comment by drfloob** [comment]
My guess is also that pecl is not using that compiler, gcc 9.3 supports `-std=c++14`. https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc/C-Dialect-Options.html#C-Dialect-Options.

@stanley-cheung please take a look.

**Comment by basbroens** [comment]
Yes.. that was the issue. Default PECL used the wrong gcc. Used PECL from other php folder and installation worked. Thanks

**Comment by omaradey** [comment]
I'm getting the same issue, how did you change pecl to use the right gcc? @basbroens Thanks

**Comment by basbroens** [comment]
@omaradey  I just ended up with reinstalling everything and it started working.
