### ISSUE TITLE
Extremely slow (>30 seconds) responses for Python examples

### ISSUE THREAD

**Issue by alielbashir** [grpc/grpc#30282]
### What version of gRPC and what language are you using?
grpcio: 1.47.0
grpcio-tools: 1.47.0
Python: 3.10.4

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10.4

### What did you do?
Follow the instructions on the gRPC Python quickstart https://grpc.io/docs/languages/python/quickstart/

1. Download the example
```
# Clone the repository to get the example code:
git clone -b v1.46.3 --depth 1 --shallow-submodules https://github.com/grpc/grpc
# Navigate to the "hello, world" Python example:
cd grpc/examples/python/helloworld
```

2. Run a gRPC application
Run the server
```
python greeter_server.py
```
From another terminal, run the client:
```
python greeter_client.py
```
### What did you expect to see?
A quick response message `Greeter client received: Hello, you!` from the server within less than a second

### What did you see instead?
A very slow response message that responds after more than 30 seconds.

### Possible fix
The problem appears to be with the client which connects to  `localhost:50051` as it takes too long to resolve. When I change it to `127.0.0.1:50051` the response is near instant as expected. 
https://github.com/grpc/grpc/blob/24171b3b57e9453c9d91f249eecf3cccd4000d95/examples/python/helloworld/greeter_client.py#L25-L32

### Anything else we should know about your project / environment?

I have tested with other examples as well and I'm facing the same issue there too.

I have tested with both v.1.46.3 and with the latest commit as of writing this issue -> 24171b3b57e9453c9d91f249eecf3cccd4000d95

**Comment by gnossen** [comment]
Based on the PR, this sounds like an issue with name resolution in your environment. Can you please confirm?
