### ISSUE TITLE
Undefined symbols on macOS x86_64 and arm64

### ISSUE THREAD

**Issue by bjason** [grpc/grpc#30299]
### What version of gRPC and what language are you using?

v1.45.2, also on v1.49.0

### What operating system (Linux, Windows,...) and version?

macOS 11.6.6 (20G624), x86_64 and also on arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)

Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

cmake version 3.22.2

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?

build successfully

### What did you see instead?

I'm trying to build gRPC on macOS following https://github.com/grpc/grpc/blob/master/BUILDING.md.

I hit the error when running `make`, with and without passing `-DBUILD_SHARED_LIBS=ON` to `cmake`:

```
      ...
  "_sk_set", referenced from:
      _sk_CRYPTO_BUFFER_set in ssl_cert.cc.o
  "_sk_set_cmp_func", referenced from:
      _sk_X509_NAME_set_cmp_func in ssl_file.cc.o
  "_sk_shift", referenced from:
      _sk_X509_shift in ssl_x509.cc.o
  "_sk_sort", referenced from:
      _sk_X509_NAME_sort in ssl_file.cc.o
  "_sk_value", referenced from:
      bssl::internal::StackIteratorImpl<stack_st_SRTP_PROTECTION_PROFILE>::operator*() const in extensions.cc.o
      bssl::internal::StackIteratorImpl<stack_st_SSL_CIPHER>::operator*() const in handoff.cc.o
      _sk_CRYPTO_BUFFER_value in handshake.cc.o
      bssl::internal::StackIteratorImpl<stack_st_SSL_CIPHER>::operator*() const in handshake_client.cc.o
      _sk_CRYPTO_BUFFER_value in handshake_client.cc.o
      _sk_SSL_CIPHER_value in handshake_server.cc.o
      _sk_CRYPTO_BUFFER_value in handshake_server.cc.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [third_party/boringssl-with-bazel/libssl.dylib] Error 1
make[1]: *** [third_party/boringssl-with-bazel/CMakeFiles/ssl.dir/all] Error 2
make: *** [all] Error 2
```

in arm64, I got similar error:

```
bssl::internal::StackIteratorImpl<stack_st_SRTP_PROTECTION_PROFILE>::operator*() const in extensions.cc.o
   bssl::internal::StackIteratorImpl<stack_st_SSL_CIPHER>::operator*() const in handoff.cc.o
   _sk_CRYPTO_BUFFER_value in handshake.cc.o
   bssl::internal::StackIteratorImpl<stack_st_SSL_CIPHER>::operator*() const in handshake_client.cc.o
   _sk_CRYPTO_BUFFER_value in handshake_client.cc.o
   _sk_SSL_CIPHER_value in handshake_server.cc.o
   _sk_CRYPTO_BUFFER_value in handshake_server.cc.o
   ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [third_party/boringssl-with-bazel/libssl.dylib] Error 1
make[1]: *** [third_party/boringssl-with-bazel/CMakeFiles/ssl.dir/all] Error 2
make: *** [all] Error 2
```

I also tried earlier version, 1.24.3, which I did not use `cmake` to build but building was fine.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
We do have CI tests on MacOS which makes me think that there is something unique about the ecosystem.

The error also seems to originate from boringssl 
```
make[2]: *** [third_party/boringssl-with-bazel/libssl.dylib] Error 1
```

I would suggest two things - 
1) Make sure that checked out repository is clean.
2) Just try building boringssl and see if it works. If it doesn't, maybe we can raise the issue with boringssl.

**Comment by veblush** [comment]
Would you mind sharing the exact commands you ran?
