### ISSUE TITLE
context.abort is not raising an error as the docs suggest. It will send error to client but server will continue execution as normal

### ISSUE THREAD

**Issue by jahamilton12121** [grpc/grpc#30306]
### What version of gRPC and what language are you using?
python  1.40.0,  using aio.server() 
also yes I am using an await command on the abort, also I have sync functions where this issue also occurs.

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
```
def Status(self, request, context):
        logger.info("4444444444")
        context.abort(grpc.StatusCode.UNKNOWN, 'aborted')
        logger.info('aaaaaaaaaaaaaaa')
```

### What did you expect to see?
4444444444

### What did you see instead?
4444444444
aaaaaaaaaaaaaaa

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by XuanWang-Amos** [comment]
Hi, you mentioned you're `using an await command on the abort`, but looks like you're not actually `await` in your example, does this issue still exist if you actually await on abort?

**Comment by jahamilton12121** [comment]
@XuanWang-Amos  so for using an async function with grpc aio, awaiting the abort does work as intended.

However, using an normal synchronous function will result in what I have above.

**Comment by XuanWang-Amos** [comment]
We do have tests to make sure nothing will be executed after `abort`: https://github.com/grpc/grpc/blob/5c9e4050c1e8c66b1b8b4e93d48b8e23ff1ea818/src/python/grpcio_tests/tests/unit/_abort_test.py#L52-L58

The test is passing right now, can you share more information about your test setup? A reproducible example will be great.
