### ISSUE TITLE
Compile Time Errors for GetCachedSize() and _internal_symbol()

### ISSUE THREAD

**Issue by J-B-Blankenship** [grpc/grpc#30323]
Bug/Solution:
The following two methods provide errors about lack of conversions when building: `inline const std::string& Stock::_internal_symbol() const` and `int GetCachedSize() const final`. I had to go into the files and add `.Get()` to the variables in the functions for both to compile correctly. This is the first time I am seeing the issue.

The first has the same name as a field I defined. It is a string field. 

### What version of gRPC and what language are you using?
v1.47.1

### What operating system (Linux, Windows,...) and version?
Windows 11 (latest as of 07/18/2022)
Ubuntu 22.04 LTS (latest as of 07/18/2022)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Windows - Latest msvc available with Visual Studio
Ubuntu - gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

### What did you do?
Cloned the latest version of gRPC (1.47.1).
CMake installation
Ran the following command: protoc -I=. --grpc_out=Generated --plugin=protoc-gen-grpc=[absolute_path_to_my_grpc_cpp_plugin_under_the_build_folder] --cpp_out=Generated AProtoFileWithGrpcStuff.proto
Compiled source code that used said `.proto` file with server code implemented.

Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
No build errors from gRPC's end similar to about 6 months ago when I last used it.

### What did you see instead?
Compile-time errors.

```
---Insert traceback through files via the includes---
./Interface/Protobuf/Generated/Extensions.pb.h: In member function 'virtual int Rogue::Interface::CodeGenerationMarkings::GetCachedSize() const':
./Interface/Protobuf/Generated/Extensions.pb.h:164:44: error: cannot convert 'google::protobuf::internal::CachedSize' to 'int' in return
  164 |   int GetCachedSize() const final { return _cached_size_; }
      |                                            ^~~~~~~~~~~~~
      |                                            |
      |                                            google::protobuf::internal::CachedSize

---Insert traceback through files via the includes---
./Interface/Protobuf/Generated/Stock.pb.h: In member function 'const string& MarketData::Stock::_internal_symbol() const':
./Interface/Protobuf/Generated/Stock.pb.h:654:10: error: invalid initialization of reference of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} from expression of type 'const google::protobuf::internal::ArenaStringPtr'
  654 |   return symbol_;
      |          ^~~~~~~
```

I am using custom extensions. This is the only notable difference besides the version of gRPC that I can think of since last using and building my source code.

### Anything else we should know about your project / environment?
Not that I know of. There are some compile errors I am working through currently that were hidden by the above compile errors, so I will post an update if the resolution of those affect the resolution of this.

**Comment by yashykt** [comment]
What do you mean by `custom extensions`? Did you mean to raise an issue in the protobuf repository?

**Comment by markdroth** [comment]
This does seem like a protobuf issue, not a gRPC issue.  Also, you did not include your code in the bug report, so there's not enough info here to reproduce the problem.

One thing you may want to check is whether you are running protoc from the same version of the protobuf library as the headers that you're compiling against.  Protobuf does not guarantee that its generated code is compatible across versions.

**Comment by J-B-Blankenship** [comment]
I am not seeing the error anymore. gRPC and protobuf are at the same version. The reason I tagged gRPC for the issue is because it was only with the above command for generating gRPC files that I ran into this issue. The regular protoc command for C++ files worked just fine. 

Now that I look back through the generated files, the issue has resolved itself. If I can figure out how to replicate or the source cause, I will reopen the issue. Maybe someone else who knows and comes across this post will know in the future.

Here is the code though (fairly vanilla gRPC) of the gRPC service data schema:

```
syntax = "proto3";

import "Account.proto";
import "Stock.proto";
import "Trade.proto";

package Trading;

message Response
{

}

service TradeAnalysis
{
	//All things market
	rpc sendStocks(stream Stock) returns (Response) {}

	rpc sendStockHistory(StockHistory) returns (Response) {}

	rpc sendStockHistories(stream StockHistory) returns (Response) {}

	rpc sendLiveAggregatedData(StockHistory) returns (Trades) {}

	rpc sendMarketHistory(MarketHistory) returns (Response) {}

	rpc availableStrategies(Account) returns (Strategies) {}

	//TODO: Separate the below calls for account info
	rpc validateAccount(Account) returns (Account) {}

	rpc createAccount(Account) returns(Response) {}

	rpc updateAccount(Account) returns(Response) {}

	rpc updateAccountBalance(Account) returns(Response) {}
}
```
