### ISSUE TITLE
Publish prebuilt compiler plugins

### ISSUE THREAD

**Issue by anuraaga** [grpc/grpc#30369]
Currently, the source for protoc compiler plugins for several languages lives together in this repo

https://github.com/grpc/grpc/tree/master/src/compiler

However, the plugins are published to language-specific repositories as listed here

https://github.com/grpc/grpc#to-start-using-grpc

In some cases, for example python, it is not actually a protoc compiler plugin that is published but everything bundled into a CPython version-specific shared library.

Publishing to the language repos makes things very easy for single-language users, but it can be unwieldy setting up the environment just to generate code in a multi-language setup. There is a significant hurdle in a `pip install` vs just downloading a binary, for example.

The plugins are already published to the master builds page (gRPC protoc Plugins)

https://packages.grpc.io/archive/2022/07/0aba64fa077ee9e9c2762b883e1c8935c2d0b0a4-d4c05fc7-3960-48e0-aec0-8dfaa8f5016a/index.xml

Some releases have objective c plugins attached

https://github.com/grpc/grpc/releases/tag/v1.48.0

It would be nice if every release could have the gRPC protoc plugins attached to them. The current format of the master builds page (zip file for each platform containing every language) would work fine. This would match how protoc itself and Go publish plugins as GitHub release artifacts. Java only publishes to Maven Central, but it's OK since those files can also be easily downloaded with HTTP.

If making these binaries more readily available, it would also be good to publish arm64 versions, the masters build only contains amd64 and 386 right now. Some distros like Python and Ruby do publish arm versions.

In the meantime, it's possible to use the master builds page, but because artifacts are published from release branches that diverge a bit, it doesn't seem to be possible to get an exact released binary from there.

**Comment by veblush** [comment]
At this point, we don't want to do this because each language has its own recommended way to generate the code and we're not sure its benefit exceeds the cost of making the release process complicated.

**Comment by anuraaga** [comment]
The language-specific guides can help when writing an app that uses gRPC but they are not very helpful in a polyglot scenario. An example is when developing an external API for customers with gRPC - to make it easier for the customers you need to publish in many different languages, but requiring a Python, Ruby, etc environment for each language to generate for a team that maintains their logic only in Go, for example, is a nightmare. It also seems unnecessary given that protoc and its plugins are self-sufficient binaries that do not actually use those language environments. If this isn't a use case the team is looking at, then it seems like gRPC is not the right tool for external APIs.

`protoc` already publishing binaries to releases seems to indicate there is some value in doing this though. If the repos have different builds, perhaps now is the time to unify them by cribbing from the protobuf repo (/cc @deannagarcia)? I suppose that would reduce overall complexity :)

**Comment by rdesgroppes** [comment]
What would it take to augment https://packages.grpc.io/ with a new `Release Builds` section?

**Comment by XuanWang-Amos** [comment]
@ejona86 can you help with the most recent comment?

**Comment by ejona86** [comment]
@XuanWang-Amos, no, I don't know anything about how any of that is set up.

**Comment by markdroth** [comment]
I think @veblush probably has the most context on this.

**Comment by Fleshgrinder** [comment]
Another issue with the many different packaging systems is that the versions are different everywhere. It's very hard to verify if things are compatible. We just saw a release of 1.59.0 followed quickly by a bugfix in form of 1.59.1 and now we have different versions available all over. The availability of gRPC in standard OS package managers is very nice for humans, but for build systems it's a nightmare, because it's not possible to get any gRPC version, and pinning isn't available either. I hope something can be done about this.

**Comment by anuraaga** [comment]
I have gone ahead and created a project that publishes prebuilt gRPC compiler binaries

https://github.com/wasilibs/go-protoc-gen-grpc/releases

It works around the difficulty of cross-compiling C codebases across many platforms by only compiling once to WebAssembly and loading it with Go. Using Go then allows trivial cross-compilation.

Naturally some acceptance of adventure would be needed to use a new project, but as there's now a workaround and I haven't seen any indication from maintainers here that they would help us, I will go ahead and close this issue.
