### ISSUE TITLE
gRPC Client streaming rate drops from 380 Mbps to 26 Mbps when TLS is enabled over high latency connections

### ISSUE THREAD

**Issue by gerhardmatzen** [grpc/grpc#30368]
Hi, we have been measuring the rate of gRPC client streaming in C# using gRPC .Net.  When TLS is not enabled, we see very high data rates of 380 Mbps (megabits per second when the client is in an Oakland datacenter and the server is in a Philadelphia datacenter (73ms pings times between client and server).  However, when TLS is enabled, the rate drops to about 26 Mbps. 

When the client and server are closer together (in the same datacenter with 1ms ping times), we see 860 Mbps with TLS disabled and 320 Mbps with TLS enabled.  So, for low latency connections, the drop off is not as drastic, but the effect of TLS is still significant.

Each individual message sent by the client is about 50KB (well below the large block heap limit) and on the server side server side we set InitialConnectionWindowSize = InitialStreamWindowSize = 33,554,432 bytes (32 MB).

We are having a hard time understanding why TLS is causing such a sharp drop off in performance.  Any ideas?

**Comment by yashykt** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
