### ISSUE TITLE
Release 1.48.0 for Ruby

### ISSUE THREAD

**Issue by johnnyshields** [grpc/grpc#30375]
There doesn't appear to be a 1.48.0 release for Ruby here: https://rubygems.org/gems/grpc/

(Please also double-check that the `x64-mingw-ucrt` gem platform build is released correctly.)

Is there some way that the gem releases for Ruby can be automated? Seems that gem releases are often missing.

**Comment by apolcyn** [comment]
1.48 was just pushed.

See https://github.com/grpc/grpc/pull/30081#issuecomment-1192728660 about the ucrt gem, though.

> Is there some way that the gem releases for Ruby can be automated? Seems that gem releases are often missing.

Most of the build is automated (and we do have automated, experimental nightly packages built off head of the master branch in https://packages.grpc.io/). There's some final manual steps needed to actually push the release packages, though, which would be tricky to get rid of. So depending on engineering availability there can sometimes be couple of days delay between tagging the release and making gems available on rubygems (more than that is unintended, though). I know it has slipped more than that in the past on some releases - we're trying to prevent that from happening again.

**Comment by johnnyshields** [comment]
OK, good enough for me, thanks! Perhaps the good folks at Rubygems could help automate it if you need?

Closing issue. 🙇‍♂️
