### ISSUE TITLE
CMake: Config Step unconditionally downloading 3rd party APIs

### ISSUE THREAD

**Issue by heinemml** [grpc/grpc#30385]
Since Commit 99752b173cfa2f the CMake build is unconditionally downloading different 3rd party APIs during configuration if their submodule was not initialized. They are not needed for the actual build. Is this really desired?

Details:

The mentioned commit added the `download_archive` cmake-function and downloads envoy-api, googleapis, opencensus-proto and xds if the respective submodules have not been initialized.
From my understanding those packages are only needed when you want to generate/consume certain proto files for the mentioned APIs.

I'm asking because in the buildroot package we only generate the cpp libraries and those downloaded packages are never used. Further the download is (for some reason) failing in our build infrastructure which eventually breaks the package build.

Would it make sense to add a CMake Switch to disable this download?

**Comment by matthewjmiller1** [comment]
In our case, we build without Internet access so these download attempts break our build.

Currently, we just add empty directories in the source tree for these four directories to workaround this and everything builds fine after that.

But, it would be nice to have a switch to control this so we don't have to modify the source tree each version to workaround this.
