### ISSUE TITLE
Python gRPC client - request streaming documentation

### ISSUE THREAD

**Issue by amitsaha** [grpc/grpc#30400]
### What version of gRPC and what language are you using?

Python, `grpc-python/1.47.0 grpc-c/25.0.0`

### What operating system (Linux, Windows,...) and version?

MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.10

### What did you do?

As per the [tutorial](https://grpc.io/docs/languages/python/basics/#bidirectional-streaming-rpc-1) for writing client code for bi-directional streaming RPC, the client code should pass the requests as an iterator.

Hence, I do this:

```python
tokens = [
            identity_pb2.ExpireTokenRequest(token="a-token"), 
            identity_pb2.ExpireTokenRequest(token="b-token"),
            identity_pb2.ExpireTokenRequest(token="c-token")
        ]
for resp in stub.ExpireToken(tokens):
    print("Status of token expiry: ", resp.result)
```

### What did you expect to see?

Client code executed without any issues.

### What did you see instead?

```
Traceback (most recent call last):
  File "/Users/echorand/work/github.com/prod-python/code/grpc-bidi-streaming-interceptors/client/client.py", line 34, in <module>
    run()
  File "/Users/echorand/work/github.com/prod-python/code/grpc-bidi-streaming-interceptors/client/client.py", line 30, in run
    for resp in responses:
  File "/Users/echorand/Library/Caches/pypoetry/virtualenvs/user-sessions-bidi-streaming-yYaJjT1H-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/Users/echorand/Library/Caches/pypoetry/virtualenvs/user-sessions-bidi-streaming-yYaJjT1H-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
>
```

### Anything else we should know about your project / environment?

This works as expected:

```
 tokens = [
            identity_pb2.ExpireTokenRequest(token="a-token"), 
            identity_pb2.ExpireTokenRequest(token="b-token"),
            identity_pb2.ExpireTokenRequest(token="c-token")
        ]
def tokens_to_expire():
        for t in tokens:
            print("Expiring: ", t.token)
            yield t
for resp in stub.ExpireToken(tokens_to_expire()):
    print("Status of token expiry: ", resp.result)
```

So, I believe, the documentation needs to be updated to specify that the client must pass a generator instead?

**Comment by gnossen** [comment]
I think this is actually correct, though the terminology is a bit technical here. The word Iterator here is referring to [this CPython protocol](https://docs.python.org/3/c-api/iter.html), which requires only a single method: `__next__`, which `list` does not implement and is therefore not an Iterator:

```
>>> a = [1, 2, 3]
>>> a.__next__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute '__next__'
```

Agreed that we should make this a bit clearer in the documentation though.
