### ISSUE TITLE
Error reporting: invalid metadata

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#3042]
When we accept invalid metadata from an application and pass it to the core, the core gives us an error. It would be helpful of us to scan over the metadata, determine what was invalid about it, and raise into the application an exception with informative detailed text about the metadata invalidity.

**Comment by nathanielmanistaatgoogle** [comment]
After [issue 8814](https://github.com/grpc/grpc/issues/8814) and [pull request 8995](https://github.com/grpc/grpc/pull/8995) what's left here is the debugging enhancement request "be more helpful to applications that make mistakes". A good thing to do, but not a priority and not something that has to be in any particular release.

**Comment by nathanielmanistaatgoogle** [comment]
The more I think about this... the less urgent it seems like a thing to need to do. There's also a relationship between this and [issue 13782](https://github.com/grpc/grpc/issues/13782).

But I wouldn't yet say "no" to this or close the issue...

**Comment by alexkarim** [comment]
Hi @nathanielmanistaatgoogle I've ran into this problem, specifically with an integer value and key that contained an uppercase letter. What's the status of this issue and are there any blockers?

**Comment by nathanielmanistaatgoogle** [comment]
@alexkarim: I don't think there are any blockers; I think it's just not prioritized at the moment. It would take some (a day's worth?) thought and care and work, and I think everyone's just working on higher-priority things.
