### ISSUE TITLE
Running setup.py bdist_wheel for grpcio: still running...

### ISSUE THREAD

**Issue by adamcunnington-mlg** [grpc/grpc#30447]
Iniside of a debian buster-slim image, I am using the python version that ships (3.7.3-1) and I am using the shipped pip version (18.1-5) to upgrade pip (22.2.1) and then install grpcio (1.48.0)

... and it takes 17 minutes to complete setup.py bdist_wheel for grpcio.

Why is it taking so long? What can I do to speed it up? All historic posts I read seem to imply this issue was supposed to go away with some change that pip shipped around about v19.

**Comment by adamcunnington-mlg** [comment]
If I add `--prefer-binary`, I collect the wheel rather than the source and it solves the issue.

The question is, why is pip defaulting to the source tarball over the wheel? I guess the source tarball must be "newer" even though it's for the same version? Maybe there was some quirk with the release order specifically for the most recent 1.48.0?

**Comment by bhavyasriy** [comment]
Thank you. Working
