### ISSUE TITLE
AuthMetadataPluginCallback raises exception

### ISSUE THREAD

**Issue by ns-dzhang** [grpc/grpc#30460]
### What version of gRPC and what language are you using?
grpc-google-iam-v1       0.12.3
grpcio                   1.44.0
grpcio-status            1.44.0
google-cloud-pubsub      2.12.0
google-cloud-pubsublite  1.4.2
I am using Python 3.8.7

### What operating system (Linux, Windows,...) and version?
Linux 4.15.0-136-generic #140~16.04.1-Ubuntu SMP Wed Feb 3 18:51:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
I am using Python 3.8.7

### What did you do?
I am using google pubsublite in my application which needs an underlay grpc. When I run my application to publish messages using pubsublite, I can see the below error randomly though it didn't affect the publishing. The frequency is not high, and there is nothing special happened in our running environment when this error appeared, just publishing the message. Not sure if it will cause some other issues.

```
2022-07-29 20:57:46,343 ERROR           _plugin_wrapping        __call__:92     26807   140157405644544 Thread-482      AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f7950829d90>" raised exception!
Traceback (most recent call last):
  File "python3.8/site-packages/grpc/_plugin_wrapping.py", line 89, in __call__
    self._metadata_plugin(
  File "python3.8/site-packages/google/auth/transport/grpc.py", line 101, in __call__
    callback(self._get_authorization_headers(context), None)
  File "python3.8/site-packages/google/auth/transport/grpc.py", line 87, in _get_authorization_headers
    self._credentials.before_request(
  File "python3.8/site-packages/google/auth/credentials.py", line 134, in before_request
    self.apply(headers)
  File "python3.8/site-packages/google/auth/credentials.py", line 110, in apply
    _helpers.from_bytes(token or self.token)
  File "python3.8/site-packages/google/auth/_helpers.py", line 130, in from_bytes
    raise ValueError("{0!r} could not be converted to unicode".format(value))
ValueError: None could not be converted to unicode
```

### What did you expect to see?
No exception raised

### What did you see instead?
exception rasied

### Anything else we should know about your project / environment?
N/A

**Comment by ns-dzhang** [comment]
@dpcollins-google @ns-xliu @ns-zquan

**Comment by gnossen** [comment]
This doesn't appear to be a gRPC issue. The stack trace above indicates that a token (presumably supplied by the client) [was expected to be unicode, but it actually wasn't](https://github.com/googleapis/google-auth-library-python/blob/b2a901b91b4e5ba3a1b4a079655b39dce55710c5/google/auth/credentials.py#L110). I think you should probably reopen this issue on the [google-auth-library-python](https://github.com/googleapis/google-auth-library-python) repo. Closing for now. Feel free to reopen if you disagree.

**Comment by ns-dzhang** [comment]
Found similar issue on 
https://github.com/googleapis/google-auth-library-python/issues/276
https://github.com/googleapis/google-auth-library-python/issues/927
