### ISSUE TITLE
Possible Memory leak on GRPC server.

### ISSUE THREAD

**Issue by smartnik83** [grpc/grpc#30463]
### What version of gRPC and what language are you using?
c# 
GRPC 2.34.0
Google.Protobuf 3.17.3

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
.net 5

### What did you do?
I have a c# GRPC service self hosted as Windows service. It gets loaded with 2.5 GB of data when it starts. After running a small load test we could see memory increasing and eventually giving out of memory error.

### What did you expect to see?
No out of memory error.

### What did you see instead?
out of memory error.

**Comment by tonydnewell** [comment]
@smartnik83 Are you able to provide example code that reproduces the problem? Eg. creating a github repository with a small example would be helpful.

Could you give more details and an indication of what gRPC calls your application is make (e.g. unary synchronous or asynchronous, streaming, duplex).

**Comment by smartnik83** [comment]
Hi @tonydnewell , Thanks for your reply.
i have kept sample code at https://github.com/smartnik83/LeakSimulation , please refer ReadMe file.

-@smartnik83

**Comment by tonydnewell** [comment]
@smartnik83 You appear to be using the grpc-dotnet implementation of gRPC. You need to report this bug there: https://github.com/grpc/grpc-dotnet

(This list of issues is for the old C# version based on grpc core)

CC: @JamesNK

**Comment by smartnik83** [comment]
Thanks @tonydnewell , You can close this issue here.
