### ISSUE TITLE
Mutual TLS on grpc secure channel doesnt work and throws errors

### ISSUE THREAD

**Issue by dineshR478** [grpc/grpc#30488]
### What version of gRPC and what language are you using?
GRPC server : c++, GRPC client: golang
Version: 1.45

### What operating system (Linux, Windows,...) and version?
Linux (both client & server)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5

### What did you do?

enable mutual TLS on server side to validate client cert and establish TLS channel. Used GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY in server side ssl options.

### What did you expect to see?
TLS Channel  should have been established.

### What did you see instead?
Errors.  Note: IP addresses are removed for security purposes.

> I0804 05:00:51.681003976   26541 timer_generic.cc:719]       TIMER CHECK BEGIN: now=2021 next=9223372036854775807 tls_min=1020 glob_min=2021
I0804 05:00:51.681012150   26541 timer_generic.cc:614]         .. shard[0]->min_deadline = 2021
I0804 05:00:51.681018355   26541 timer_generic.cc:537]         .. shard[0]: heap_empty=true
I0804 05:00:51.681023001   26541 timer_generic.cc:512]         .. shard[0]->queue_deadline_cap --> 3020
I0804 05:00:51.681027437   26541 timer_generic.cc:577]         .. shard[0] popped 0
I0804 05:00:51.681050480   26541 timer_generic.cc:632]         .. result --> 1, shard[0]->min_deadline 2021 --> 3021, now=2021
I0804 05:00:51.681056656   26541 timer_generic.cc:537]         .. shard[1]: heap_empty=true
I0804 05:00:51.681060864   26541 timer_generic.cc:512]         .. shard[1]->queue_deadline_cap --> 3020
I0804 05:00:51.681065348   26541 timer_generic.cc:577]         .. shard[1] popped 0
I0804 05:00:51.681069504   26541 timer_generic.cc:632]         .. result --> 1, shard[1]->min_deadline 2021 --> 3021, now=2021
I0804 05:00:51.681074679   26541 timer_generic.cc:741]       TIMER CHECK END: r=1; next=3021
I0804 05:00:51.681079199   26541 timer_manager.cc:188]       sleep for a 1000 milliseconds
I0804 05:00:52.011692730   26544 tcp_server_posix.cc:243]    SERVER_CONNECT: incoming connection: ipv4:**IP**:37720
D0804 05:00:52.011801873   26544 tcp_posix.cc:1830]          cannot set inq fd=25 errno=92
I0804 05:00:52.011933330   26544 handshaker.cc:99]           handshake_manager 0x7fffc8002df0: adding handshaker security [0x7fffc800d050] at index 0
I0804 05:00:52.011993974   26544 timer_generic.cc:367]       TIMER 0x7fffc8002e58: SET 122351 now 2351 call 0x7fffc8002e88[0x7ffff001f790]
I0804 05:00:52.012016028   26544 timer_generic.cc:404]         .. add to shard 0 with queue_deadline_cap=3020 => is_first_timer=false
I0804 05:00:52.012072871   26544 handshaker.cc:129]          handshake_manager 0x7fffc8002df0: error="No Error" shutdown=0 index=0, args={endpoint=0x7fffc8002230, args=0x7fffc800d440 {size=4: grpc.primary_user_agent=grpc-c++/1.33.2, grpc.compression_enabled_algorithms_bitset=15, grpc.server_credentials=0x7fffe0135690, grpc.security_connector=0x7fffe01ef6d0}, read_buffer=0x7fffc800d5b0 (length=0), exit_early=0}
I0804 05:00:52.012083877   26544 handshaker.cc:176]          handshake_manager 0x7fffc8002df0: calling handshaker security [0x7fffc800d050] at index 0
I0804 05:00:52.012108703   26544 tcp_posix.cc:545]           TCP:0x7fffc8002230 notify_on_read
I0804 05:00:52.012133285   26544 tcp_posix.cc:890]           TCP:0x7fffc8002230 got_read: "No Error"
I0804 05:00:52.012147310   26544 tcp_posix.cc:872]           TCP:0x7fffc8002230 alloc_slices
I0804 05:00:52.012157514   26544 resource_quota.cc:892]      RQ anonymous_pool_140736548839600 ipv4:**IP**:37720: alloc 8192; free_pool -> -8192
I0804 05:00:52.012175876   26544 resource_quota.cc:324]      RQ: check allocation for user 0x7fffc8002b80 shutdown=0 free_pool=-8192 outstanding_allocations=8192
I0804 05:00:52.012181953   26544 resource_quota.cc:352]      RQ anonymous_pool_140736548839600 ipv4:**IP**:37720: grant alloc 8192 bytes; rq_free_pool -> 9223372036854767615
I0804 05:00:52.012197113   26544 tcp_posix.cc:853]           TCP:0x7fffc8002230 read_allocation_done: "No Error"
I0804 05:00:52.012212889   26544 resource_quota.cc:953]      RQ anonymous_pool_140736548839600 ipv4:**IP**:37720: free 8192; free_pool -> 8192
I0804 05:00:52.012226264   26544 tcp_posix.cc:682]           TCP:0x7fffc8002230 call_cb 0x7fffc800d1f8 0x7ffff0082a50:0x7fffc800d050
I0804 05:00:52.012241985   26544 tcp_posix.cc:685]           READ 0x7fffc8002230 (peer=ipv4:1**IP**:37720) error={"created":"@1659589252.012220070","description":"Socket closed","fd":25,"file":"/../grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:**IP**:37720"}
D0804 05:00:52.012269272   26544 security_handshaker.cc:184] Security handshake failed: {"created":"@1659589252.012252790","description":"Handshake read failed","file":"/.../grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1659589252.012220070","description":"Socket closed","fd":25,"file":"/../grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:**IP**:37720"}]}
I0804 05:00:52.012331849   26544 handshaker.cc:129]          handshake_manager 0x7fffc8002df0: error={"created":"@1659589252.012252790","description":"Handshake read failed","file":"/../grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1659589252.012220070","description":"Socket closed","fd":25,"file":"/../grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:**IP**:37720"}]} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0804 05:00:52.012342681   26544 handshaker.cc:162]          handshake_manager 0x7fffc8002df0: handshaking complete -- scheduling on_handshake_done with error={"created":"@1659589252.012252790","description":"Handshake read failed","file":"/.../grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1659589252.012220070","description":"Socket closed","fd":25,"file":"/../grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:**IP**:37720"}]}
I0804 05:00:52.012353053   26544 timer_generic.cc:470]       TIMER 0x7fffc8002e58: CANCEL pending=true
D0804 05:00:52.012359979   26544 chttp2_server.cc:200]       Handshaking failed: {"created":"@1659589252.012252790","description":"Handshake read failed","file":"/.../grpc/src/core/lib/security/transport/security_handshaker.cc","file_line":397,"referenced_errors":[{"created":"@1659589252.012220070","description":"Socket closed","fd":25,"file":"/.../grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":784,"grpc_status":14,"target_address":"ipv4:**IP**:37720"}]}
I0804 05:00:52.012455561   26544 resource_quota.cc:553]      RU shutdown 0x7fffc8002b80
I0804 05:00:52.680992154   26541 timer_manager.cc:204]     

ssl_transport_security.cc:1439] Handshake failed with fatal error SSL_ERROR_WANT_WRITE: error:00000000:lib(0):func(0):reason(0).

**Comment by drfloob** [comment]
Thanks for the trace-enabled log, that's helpful. Based on the `Socket closed` error on the first attempt at a read, have you ruled out network errors, and confirmed that your client & server can communicate without mTLS enabled? Do you have logs to see if the Go client closing the connection early?

CC @ZhenLian

**Comment by dineshR478** [comment]
@drfloob We are able to connect successfully without mTLS. We don't have the GO client logs.

**Comment by drfloob** [comment]
> Do you think its a bad/invalid certificate issue?

I'm not sure, the client logs might be informative there. Can you run a client locally and reproduce the issue?

**Comment by yashykt** [comment]
>  Do you think its a bad/invalid certificate issue?

It is possible. Can you verify that please? Go client logs would also be helpful.

**Comment by dineshR478** [comment]
we are not able to generate trace logs in Go Client. Do you have any idea to enable debug logs?

**Comment by dineshR478** [comment]
@yashykt By the way,  I could not connect to go lang server running without grpc from golang client(obviously without grpc) though the certs are created locally on the same machine where client and servers are running.
getting below error.
>2022/08/10 05:58:56 Handshake error: tls: failed to verify client certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate

**Comment by ZhenLian** [comment]
I am not quite sure about what might be the cause here. Handing this off to @erm-g for further investigation...
