### ISSUE TITLE
gRPC: A client spawned inside the server causes threads to block each other

### ISSUE THREAD

**Issue by karol-bisztyga** [grpc/grpc#30510]
### What version of gRPC and what language are you using?

- `brew info grpc` => `grpc: stable 1.47.1 (bottled)`
- c++17
- proto3

### What operating system (Linux, Windows,...) and version?

mac os 12.4

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
$ gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
```
```
$ cmake --version
cmake version 3.23.3
```
Not sure what else I could provide, if you need more info - let me know.

### What did you do?

I prepared a reproducing repository: https://github.com/karol-bisztyga/grpc-playground/tree/performance-problems-repro
So you'd go:
```
git clone https://github.com/karol-bisztyga/grpc-playground.git
git cd grpc-playground
git checkout performance-problems-repro
```
And then you can follow the [instructions from the readme](https://github.com/karol-bisztyga/grpc-playground/blob/performance-problems-repro/README.md) to launch the services and the client.

Note: This branch contains logs, if you want more readable code I've prepared a branch that doesn't have the logs: https://github.com/karol-bisztyga/grpc-playground/tree/performance-problems-repro-nologs

A little bit of description what is going on here. There are 3 "components":
- client - a gRPC client which connects to the outer service (as a client)
- outer service - a gRPC server that connects with the client (as a server) and with the inner service (as a client)
- inner service - a gRPC server that connects with the outer service (as a server)

What happens is:
- `client` sends a message to the `outer service`
- `outer service` receives a message from `client`
- `outer service` spawns a gRPC client that will connect to the `inner service` (if it is not already spawned)
- `outer service` passes the message to the `inner service` via spawned gRPC client
- `inner service` receives a message (and does nothing with it)

That goes in a loop (for example client sends `X` messages - 5, 10, 15, whatever).

This works when there is one `client`.

The problem is when I spawn multiple `client`s - each of them in a separate thread - and do the requests to the `outer service` simultaneously. When I ran the client setting the number of threads to `4+` like `./run.sh client 4`, the `inner service` hangs - for every request it processes only the first message and then just hangs forever.

### What did you expect to see?

All messages processed.

### What did you see instead?

Hanging server for multiple requests.
```
[11851940350522247373]server listening at :localhost:50051
[3738854739723053058][TalkReactor::handleRequest] processING msg 20
[14353947235243368295][TalkReactor::handleRequest] processING msg 20
[18437551388941743491][TalkReactor::handleRequest] processING msg 20
[15739255737399969683][TalkReactor::handleRequest] processING msg 20
[[14353947235243368295][TalkReactor::handleRequest] processED msg 20[18437551388941743491]
[TalkReactor::handleRequest] processED msg 20
[15739255737399969683][TalkReactor::handleRequest] processED msg 20
3738854739723053058][TalkReactor::handleRequest] processED msg 20
```
(There should be further messages processed on the `inner service`)

### Anything else we should know about your project / environment?

If I forgot about anything, please, let me know and I will provide more info.

Note: My suspicion is that there's something wrong with how I spawn the gRPC client on the `outer service` (that is supposed to connect to the `inner service`). There are two places where this happens: [here](https://github.com/karol-bisztyga/grpc-playground/blob/1479fb531cb8e000d7f28c1f43a1047006f17134/src/outer_server/TalkWithClientReactor.h#L35) and [here](https://github.com/karol-bisztyga/grpc-playground/blob/1479fb531cb8e000d7f28c1f43a1047006f17134/src/outer_server/ServiceClient.h#L30). I tried to play with it a bit (to recreate channel, stub every time, etc., to manually spawn it on a separate thread) but nothing really helped.

Could you please take a look at how the client is spawned inside of the server? Maybe I missed something (maybe there's some configuration I never provided)?

Also, if there's any example of such a architecture like presented here, where can I find it? (I've been looking but with no success).

A thing worth noticing is that the `inner service` itself is working without problems when I connect to it from the standalone client (that means a gRPC client as a separate program, not spawned in the `outer service`).

Thank you!

**Comment by karol-bisztyga** [comment]
I also created [another test](https://github.com/karol-bisztyga/grpc-playground/tree/performance-problems-repro-artif-threads) in which I got rid of spawning the client inside of the server. Instead, I manually spawned threads (that are later awaited) that just do some waiting "simulating" connection with another server.

Everything worked fine even for a large number of threads. This pushes me further toward the assumption that the problem lies in the gRPC and spawning the client on the server. This is because most probably there's no problem in all the synchronization and all the multithreading operations that my c++ code performs. There was one problem - I didn't use a predicate for the condition variable. [I fixed that](https://github.com/karol-bisztyga/grpc-playground/commit/03d7f239f59f9a0b2e4cec1521564447948d58fd) but that didn't solve the problem, the server still hangs.

**Comment by yashykt** [comment]
A drive-by comment without looking at the code in detail -
I did notice that you are performing blocking I/O operations inside callbacks that are invoked from gRPC such as sleeps and waits. That's not good use of the API since if you block the threads in the callbacks, gRPC won't have threads to poll the fds leading to possible "hangs"

**Comment by karol-bisztyga** [comment]
Yes, I do that.
This stands for simulating any operations that would take some time and also I use timeouts to make sure that certain operations will run at the very same time. Shouldn't gRPC wait for threads to be available and properly pull them once they are?
Let's assume there is some processing I have to perform after receiving data from gRPC and it takes some time (for example disk ops, cloud ops, DB ops). What should I do in such a case? Should I spawn a worker thread manually and schedule tasks on that thread to unblock the poll? Scheduling itself also takes time (very little, but still). What is the limit of a single callback in terms of the time of execution? I'm aiming at the limit that will guarantee (100%) that there will be no hangs ever.
Sorry, but I find it all a bit strange and I'm not really sure this is the case. Are 4 simultaneous threads enough to cause gRPC to hang? That would mean the lib is extremely inefficient and I'd write a better thread model in one day probably.

Thanks for the reply BTW.

**Comment by yashykt** [comment]
As I said earlier, I haven't looked at the code to verify that there are no correctness issues. If after those operations are done, the threads are given back to gRPC for polling, I would expect there to still be progress made, unless there is a deadlock where the threads performing the blocking IO operations are waiting for gRPC to make progress but there are no more threads polling. 

We do have ongoing development in the poller code (EventEngine) that allows applications to plug-in their own threading model. For the time being, if the callback API is not working for your needs, I would suggest using the CQ-based async API that leaves the threading model to the application.

**Comment by nicolasnoble** [comment]
> Sorry, but I find it all a bit strange and I'm not really sure this is the case. Are 4 simultaneous threads enough to cause gRPC to hang? That would mean the lib is extremely inefficient and I'd write a better thread model in one day probably.

Your code is using the reactor model. A reactor model _is_ intended to be used in a way where callbacks return as fast as possible. If you follow the model of other reactor systems, like node.js, you will have the same constraint.

Using a reactor pattern properly means that callbacks need to immediately delegate work elsewhere, like a threadpool, and then resume operation upon completion of the work.

I would suggest reading the original paper describing the pattern in order to familiarize yourself properly with the corresponding threading model, and properly using it: http://www.dre.vanderbilt.edu/~schmidt/PDF/reactor-siemens.pdf

**Comment by vjpai** [comment]
This is also documented all over the place. Like this comment on the ClientReactor structures:
```cpp
// The following classes are the reactor interfaces that are to be implemented
// by the user. They are passed in to the library as an argument to a call on a
// stub (either a codegen-ed call or a generic call). The streaming RPC is
// activated by calling StartCall, possibly after initiating StartRead,
// StartWrite, or AddHold operations on the streaming object. Note that none of
// the classes are pure; all reactions have a default empty reaction so that the
// user class only needs to override those reactions that it cares about.
// The reactor must be passed to the stub invocation before any of the below
// operations can be called and its reactions will be invoked by the library in
// response to the completion of various operations. Reactions must not include
// blocking operations (such as blocking I/O, starting synchronous RPCs, or
// waiting on condition variables). Reactions may be invoked concurrently,
// except that OnDone is called after all others (assuming proper API usage).
// The reactor may not be deleted until OnDone is called.
```

or the original gRFC for this API:
```
- Library directly calls user-specified code at the completion of RPC actions.
  This user code is run from the library's own threads, so it is very important
  that it must not wait for completion of any blocking operations (e.g.,  
  condition variable waits, invoking synchronous RPCs, blocking file I/O).
```

Suggestion for those who have to maintain this code now: Consider switching the code in https://grpc.io/docs/languages/cpp/async/ to the callback model, akin to how this is presented in the internal codelab (assuming that that hasn't changed in a few years). Maybe leave the CQ-based model around as "special topics" just like it is in the internal codelab?

**Comment by karol-bisztyga** [comment]
Thank you for your help, I [implemented](https://github.com/karol-bisztyga/grpc-playground/commit/217303194b7f54190c21ea3cd8786381f0671f18) sending blocking work to separate threads and it works 🎉 🚀  (this is a quick dirty solution just to check if this works).

Very cool of you guys, thanks a lot!! :) All the best!
