### ISSUE TITLE
g++: error: unrecognized command line option '-std=c++14'

### ISSUE THREAD

**Issue by omaradey** [grpc/grpc#30543]
I'm getting the above error when installing with pecl on centos 7

if I use the command `/opt/cpanel/ea-php80/root/usr/bin/pecl install grpc` , I get an issue, but when using `/opt/cpanel/ea-php74/root/usr/bin/pecl install grpc` it will install, what am I doing wrong?

my development environment is php 8.0, and installing it with the 7.4 pecl wont allow me to use it from 8.0 cli

I've got g++ 7.3.1, and installed devtoolset 7.

Can someone please advise/help, I've been trying to do this now for the last 3 days.

**Comment by omaradey** [comment]
I'm on CentOS 7.9 with WHM/cPanel

**Comment by omaradey** [comment]
When building from source using [https://github.com/grpc/grpc/tree/master/src/php#build-from-source](https://github.com/grpc/grpc/tree/master/src/php#build-from-source) < this guide, the same issue `c++: error: unrecognized command line option ‘-std=c++14’` upon attempting the make command

**Comment by omaradey** [comment]
I'm trying to use the PHP client library for the Google Ads API

**Comment by yashykt** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
