### ISSUE TITLE
Should use getpeername instead of getsockname for unix domain client address

### ISSUE THREAD

**Issue by nickylba** [grpc/grpc#30581]
### What version of gRPC and what language are you using?
v1.39.0

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.3.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

1. create a grpc server listen on unix domain address unix:/home/grpc_svr_addr
2. create a grpc client on unix domain address unix:/home/grpc_clt_addr
     Note: What I really do is create raw unix domain fd and then bind path unix:/home/grpc_clt_addr to that fd.  Then I can use this fd to proxy outter HTTP2 data to the server listening on unix:/home/grpc_svr_addr. But I think directly use domain-fd client is same.
3. after server get some rpc call, when try to read the peer address from the ServerContext with method peer(), it give the wrong result

### What did you expect to see?
The peer address  should be unix:/home/grpc_clt_addr

### What did you see instead?
The peer address is equal to unix:/home/grpc_svr_addr, after some debugging of the code, I found that:

1. in the src/core/lib/iomgr/tcp_server_posix.cc, the call to grpc_accept4 already give the correct address of client
2. however later call of grpc_is_unix_socket check this address is unix address, and then try to call **getsockname** to fix some special scenario, this logic overwrite the client address with wrong value
3. I think the API is not correct bcz **getpeername** should be used to read the client address instead of **getsockname**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
No

**Comment by drfloob** [comment]
Sorry it took me a while to get time to research this. It doesn't appear as if the peer name is used in any critical way within gRPC (it is parsed, but used primarily for logging and naming things), so it seems fine to change this behavior. If you'd like to submit a PR that makes the change, we can try integrating it and see if anything breaks.

**Comment by diurnalist** [comment]
I suspect this might have caused this issue (due to some bounds checking that is overly-optimistic): https://github.com/open-telemetry/opentelemetry-python-contrib/issues/3393

However, I have noticed that grpc versions past 1.50.0 just return `unix:` as the peer address, at least when using the Python library's `context.peer()` accessor function.
