### ISSUE TITLE
Python channel destruction on Windows

### ISSUE THREAD

**Issue by andrusenko-ag** [grpc/grpc#30592]
[grpc_python.log](https://github.com/grpc/grpc/files/9349908/grpc_python.log)
Having a trouble with python client on Windows(client and server are on the same machine), on Linux the same code works just fine. Though Grpc.Core.Xamarin(uses HTTP 1.1) client works just fine on Windows.
Attaching logs, please have a look. What I tried is to switch firewall off for all networks but that does not help.

BTW I'm also not able to establish connection on WSL(both server and client are there) with the same reason.
-----------------------------
Windows 11 Pro
Python 3.8.0
libprotoc 3.19.4
-----------------------------
Python packages:

behave             1.2.6
certifi            2022.6.15
charset-normalizer 2.1.0
docker             5.0.3
docker-py          1.10.6
docker-pycreds     0.4.0
grpcio             1.47.0
grpcio-tools       1.47.0
grpclib            0.4.3
h2                 4.1.0
hpack              4.0.0
hyperframe         6.0.1
idna               3.3
multidict          6.0.2
numpy              1.21.5
parse              1.19.0
parse-type         0.6.0
pip                22.2.2
protobuf           3.20.1
PyHamcrest         2.0.4
pywin32            227
requests           2.28.1
setuptools         41.2.0
six                1.16.0
urllib3            1.26.11
websocket-client   1.3.3
wheel              0.37.0

**Comment by gnossen** [comment]
```
I0816 11:13:53.227000000 52976 src/core/ext/transport/chttp2/client/chttp2_connector.cc:371] grpc_secure_channel_create(target=0.0.0.0:8084, creds=00000193DBB0BA40, args=00000193DC9DF610)
I0816 11:13:53.231000000 52976 src/core/lib/channel/channel_stack.cc:111] CHANNEL_STACK: init CLIENT_CHANNEL
I0816 11:13:53.233000000 52976 src/core/lib/channel/channel_stack.cc:113] CHANNEL_STACK:   filter client-channel
I0816 11:13:53.236000000 52976 src/core/ext/filters/client_channel/client_channel.cc:1071] chand=00000193D8B65020: creating client_channel for channel stack 00000193D8B64F90
I0816 11:13:53.239000000 52976 src/core/lib/surface/init.cc:169] grpc_init(void)
I0816 11:13:53.241000000 52976 src/core/lib/security/credentials/credentials.cc:41] grpc_channel_credentials_release(creds=00000193DBB0BA40)
I0816 11:13:53.351000000 52976 src/core/lib/surface/completion_queue.cc:1419] grpc_completion_queue_shutdown(cq=00000193DBC22AF0)
I0816 11:13:53.354000000 52976 src/core/lib/surface/completion_queue.cc:1425] grpc_completion_queue_destroy(cq=00000193DBC22AF0)
I0816 11:13:53.356000000 52976 src/core/lib/surface/completion_queue.cc:1419] grpc_completion_queue_shutdown(cq=00000193DBC22AF0)
I0816 11:13:53.358000000 52976 src/core/lib/surface/completion_queue.cc:1419] grpc_completion_queue_shutdown(cq=00000193DBBFF2E0)
I0816 11:13:53.361000000 52976 src/core/lib/surface/completion_queue.cc:1425] grpc_completion_queue_destroy(cq=00000193DBBFF2E0)
I0816 11:13:53.363000000 52976 src/core/lib/surface/completion_queue.cc:1419] grpc_completion_queue_shutdown(cq=00000193DBBFF2E0)
I0816 11:13:53.366000000 52976 src/core/lib/surface/channel.cc:430] grpc_channel_destroy(channel=00000193DBBAC160)
I0816 11:13:53.368000000 52976 src/core/ext/filters/client_channel/client_channel.cc:1763] chand=00000193D8B65020: disconnect_with_error: {"created":"@1660637633.368000000","description":"Channel Destroyed","file":"src/core/lib/surface/channel.cc","file_line":432}
```

This looks a lot like the channel destructor was called. Can you share any code that might shed light on what's going on here?
