### ISSUE TITLE
ruby: 1.49.0 pre-release candidates not installing when new mingw-ucrt package is present in the same local directory

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#30630]
Getting an error when attempting to manually install 1.49 pre-release candidates:

E.g.:

```
$ gem install ./grpc-1.49.0.pre1-x86_64-linux.gem 
ERROR:  While executing gem ... (Gem::Exception)
    Unable to find spec for #<Gem::NameTuple grpc, 1.49.0.pre1, x64-unknown>
```

Turns out, this `gem install` error only happens when the `mingw-ucrt` release candidate (`grpc-1.49.0.pre1-x64-mingw-ucrt.gem`) is in the same local directory as the gem I'm trying to install.

**Comment by apolcyn** [comment]
This is reproducible with the nightly packages in https://packages.grpc.io/, using the latest build: https://packages.grpc.io/archive/2022/08/8a091d1888c9232ff961cba413ee1e2b6fa9fe80-bb9c96aa-cf0b-4136-8b2b-8eba83976add/index.xml/.

Notice how the presence of the `ucrt` gem in the same local directory prevents installation:

```
$ curl -L https://packages.grpc.io/archive/2022/08/8a091d1888c9232ff961cba413ee1e2b6fa9fe80-bb9c96aa-cf0b-4136-8b2b-8eba83976add/ruby/grpc-1.50.0.dev-x86_64-linux.gem -o grpc-1.50.0.dev-x86_64-linux.gem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.5M  100 23.5M    0     0  43.4M      0 --:--:-- --:--:-- --:--:-- 43.5M
$ curl -L https://packages.grpc.io/archive/2022/08/8a091d1888c9232ff961cba413ee1e2b6fa9fe80-bb9c96aa-cf0b-4136-8b2b-8eba83976add/ruby/grpc-1.50.0.dev-x64-mingw-ucrt.gem -o grpc-1.50.0.dev-x64-mingw-ucrt.gem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3689k  100 3689k    0     0  3767k      0 --:--:-- --:--:-- --:--:-- 3764k
$ gem install grpc-1.50.0.dev-x86_64-linux.gem 
ERROR:  While executing gem ... (Gem::Exception)
    Unable to find spec for #<Gem::NameTuple grpc, 1.50.0.dev, x64-unknown>
$ rm grpc-1.50.0.dev-x64-mingw-ucrt.gem 
$ gem install grpc-1.50.0.dev-x86_64-linux.gem 
Successfully installed grpc-1.50.0.dev-x86_64-linux
Parsing documentation for grpc-1.50.0.dev-x86_64-linux
Installing ri documentation for grpc-1.50.0.dev-x86_64-linux
Done installing documentation for grpc after 0 seconds
1 gem installed
```

**Comment by apolcyn** [comment]
@johnnyshields any clue what's going on here?

Something seems funny with the new `mingw-ucrt` package

**Comment by apolcyn** [comment]
Related: https://github.com/grpc/grpc/pull/30081

**Comment by johnnyshields** [comment]
@apolcyn are you using the latest Rubygems?

**Comment by apolcyn** [comment]
@apolcyn are you using the latest Rubygems?

Ah, no I wasn't. I updated to `3.3.20` and now it works.

> Also, does deleting the local gem file grpc-1.49.0.pre1-x64-mingw-ucrt.gem resolve the issue?

Yes, installation succeeded or failed based on presence or absence of that file (see sequence of commands in https://github.com/grpc/grpc/issues/30630#issuecomment-1219885646)

**Comment by johnnyshields** [comment]
OK, glad to hear Rubygems upgrade fixes it 🎉

**Comment by apolcyn** [comment]
Closing, thanks for the pointer.
