### ISSUE TITLE
Python tests should run in parallel

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#3069]
[I want it all, I want it all, I want it all, and I want it sometime after Beta.](https://www.youtube.com/watch?v=lYFGTf3M3Sc)

The [load_tests protocol](https://docs.python.org/2/library/unittest.html#load-tests-protocol) is part of the Python standard library; using it shouldn't be a liability for us the way it is today.

**Comment by nathanielmanistaatgoogle** [comment]
Timely and related to what we're doing here: https://mail.python.org/pipermail/distutils-sig/2015-October/027003.html.

**Comment by soltanmm** [comment]
Thanks to @jtattermusch.
