### ISSUE TITLE
GRPC.Core.Xamarin android emulator x86_64 channel not created

### ISSUE THREAD

**Issue by andrusenko-ag** [grpc/grpc#30772]
Creating channel on x86_64 android emulator returns null, x86 works fine.

new Channel("localhost:8081", ChannelCredentials.Insecure);

**Comment by tonydnewell** [comment]
Grpc.Core Xamarin / Android is no longer actively supported.
 
 - The Grpc.Core implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
 - Supporting Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
 - The Xamarin support has always been classified as "experimental", see https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental

See the recent update on gRPC C# for more details. https://grpc.io/blog/grpc-csharp-future/

Note that in practice, running Grpc.Core on Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as Grpc.Core on Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
