### ISSUE TITLE
grpcio-health-checking release candidate requires protobuf 3.20 or more

### ISSUE THREAD

**Issue by alaeddine-13** [grpc/grpc#30783]
### What version of gRPC and what language are you using?
grpcio-health-checking==1.49.0rc1

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.2 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.10

### What did you do?
pip install protobuf==3.19.1 grpcio-health-checking==1.49.0rc1
python -c 'from grpc_health.v1 import health_pb2, health_pb2_grpc'

### What did you expect to see?
no import error or dependency resolution conflict

### What did you see instead?
ImportError: cannot import name 'builder' from 'google.protobuf.internal'

### Anything else we should know about your project / environment?
I think it makes sense to increase minimum protobuf version for grpcio-health-checking before releasing 1.49.0 or fix incompatibility:
https://github.com/grpc/grpc/blob/master/src/python/grpcio_health_checking/setup.py#L65

**Comment by gnossen** [comment]
CC @apolcyn
