### ISSUE TITLE
GPR_ASSERT failed when client writes to their stream after server finished it

### ISSUE THREAD

**Issue by subbota-a** [grpc/grpc#30791]
### What version of gRPC and what language are you using?
gRPC v1.45.2 C++

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 19.29.30143 for x64, /MT or /MD runtime flags, Debug and Release builds

### What did you do?
See unit test at [https://github.com/subbota-a/grpc-tests/blob/unit_test_for_issue/test/client_stream.cpp#L135](https://github.com/subbota-a/grpc-tests/blob/unit_test_for_issue/test/client_stream.cpp#L135)

The short scenario:
A RPC is `rpc ClientStream(stream StringMsg) returns (CountMsg) {}`
Client establishes rpc and writes a message.
Server reads one message and finishes rpc
Client doesn't know about it and goes on writing until ok is true.
GRPC_ASSERT failes

### What did you expect to see?
I expect that client can write to stream until it gets ok!=true (in call `cq->Next(&tag, &ok)`) after server finished the stream.

### What did you see instead?
The test crashes on GRPC_ASSERT.
In Debug build the output is 
`E0830 09:24:39.968000000  7536 byte_stream.cc:62] assertion failed: backing_buffer_.count > 0`
In Release build the output is
`E0830 09:26:08.990000000  6896 slice_buffer.cc:384] assertion failed: sb->count > 0`

### Anything else we should know about your project / environment?
In my CMakeLists.txt I use conan 1.50 as package manages but you can use any.

**Comment by subbota-a** [comment]
I want to add that the issue doesn't occur in v1.44.0 but it occurs since v1.45.2 up to the latest release.

**Comment by eugeneo** [comment]
Please provide a self-contained repro without external dependencies or isolated to a Docker file. Thank you in advance!

**Comment by subbota-a** [comment]
2 years passed, nobody waits for you any more!
If you were interested in quality of your product you got use of everything I provided.
