### ISSUE TITLE
UnknownMap cannot be exported when trying to build windows dlls

### ISSUE THREAD

**Issue by wsbrenk** [grpc/grpc#30827]
### What version of gRPC and what language are you using?

1.48.1, c++

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

Visual Studio 2022, Version 17.3.2

### What did you do?

I'm trying to build grpc dlls from a fork of your repo (tag 1.48.1)
CMAKE Args: -GNinja -DBUILD_SHARED_LIBS=ON -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_CXX_STANDARD=17

I added some "__declspec(dllexport)" to the sources to get rid of a bunch of unresolved symbols

one single symbol was left at the end: unresolved external symbol "public: void __cdecl grpc_core::metadata_detail::UnknownMap::Append..."

UnknownMap contains a ChunkedVector<pair<Slice, Slice>, 10> 

when i dllexport the class UnknownMap i get compile errors:

~~~
C:\git\grpc\src\core\lib\gprpp\construct_destruct.h(35): error C2280: 'std::pair<grpc_core::Slice,grpc_core::Slice>::pair(const std::pair<grpc_core::Slice,grpc_core::Slice> &)': attempting to reference a deleted function
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include\utility(210): note: see declaration of 'std::pair<grpc_core::Slice,grpc_core::Slice>::pair'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include\utility(210): note: 'std::pair<grpc_core::Slice,grpc_core::Slice>::pair(const std::pair<grpc_core::Slice,grpc_core::Slice> &)': function was implicitly deleted because a data member invokes a deleted or inaccessible function 'grpc_core::Slice::Slice(const grpc_core::Slice &)'
C:\git\grpc\src/core/lib/slice/slice.h(294): note: 'grpc_core::Slice::Slice(const grpc_core::Slice &)': function was explicitly deleted
  ...
~~~

### What did you expect to see?

grpc.dll 

### What did you see instead?

linker or compiler errors shown above.

### Anything else we should know about your project / environment?

i read your warnings concerning windows dlls and agree with your point of view - but i want to replace old corba dlls with grpc which is part of a bigger system of services using this dlls.
so i planned to build those dlls with unique compiler settings.

if you would like to reproduce what i'm describing, i could push my branch.

**Comment by markdroth** [comment]
I doubt we're really going to be able to help you with this, since we don't support DLLs under Windows.  But @ctiller might know some quick way to help with this.

**Comment by ctiller** [comment]
Sorry, I don't know of any quick path, and I wouldn't have a chance to iterate on this for at least a month.
