### ISSUE TITLE
Memory leak in `grpc::GenericStub::UnaryCall()`

### ISSUE THREAD

**Issue by daniel-eiband-snkeos** [grpc/grpc#30848]
### What version of gRPC and what language are you using?
1.43.0

### What operating system (Linux, Windows,...) and version?
Windows 10 20H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC x64 build tools v14.29

### What did you do?
We call `grpc::GenericStub::UnaryCall()` with Visual Leak Detector and a remote server, which returns a non-ok status code including a status message. The test program is compiled in debug mode with iterator debugging turned on.

### What did you expect to see?
No memory leak.

### What did you see instead?
The `std::string` member of the `grpc::Status` class leaks the iterator debugging proxy helper object. The call stack of the allocation which is not freed is:
```
ucrtbased.dll!malloc()
d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp (35): operator new() + 0xA bytes
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory (86): std::_Default_allocate_traits::_Allocate()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory (244): std::_Allocate<16,std::_Default_allocate_traits,0>() + 0xA bytes
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory (840): std::allocator<std::_Container_proxy>::allocate()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory (1074): std::_Container_base12::_Alloc_proxy<std::allocator<std::_Container_proxy> >() + 0xF bytes
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xstring (2469): std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> >()
C:\.conan\984ad9\1\include\grpcpp\impl\codegen\status.h (36): grpc::Status::Status() + 0x26 bytes
C:\.conan\984ad9\1\include\grpcpp\impl\codegen\callback_common.h (87): grpc::internal::CallbackWithStatusTag::CallbackWithStatusTag() + 0x53 bytes
C:\.conan\984ad9\1\include\grpcpp\impl\codegen\client_callback.h (93): grpc::internal::CallbackUnaryCallImpl<grpc::ByteBuffer,grpc::ByteBuffer>::CallbackUnaryCallImpl<grpc::ByteBuffer,grpc::ByteBuffer>() + 0xA7 bytes
C:\.conan\984ad9\1\include\grpcpp\impl\codegen\client_callback.h (60): grpc::internal::CallbackUnaryCall<grpc::ByteBuffer,grpc::ByteBuffer,grpc::ByteBuffer,grpc::ByteBuffer>() + 0x73 bytes
C:\.conan\984ad9\1\include\grpcpp\generic\generic_stub.h (127): grpc::TemplatedGenericStub<grpc::ByteBuffer,grpc::ByteBuffer>::UnaryCallInternal() + 0xF2 bytes
C:\.conan\984ad9\1\include\grpcpp\generic\generic_stub.h (96): grpc::TemplatedGenericStub<grpc::ByteBuffer,grpc::ByteBuffer>::UnaryCall() + 0x7E bytes
```

It seems like the destructor of the tag object of type `CallbackWithStatusTag` is (intentionally?) not being called, which nevertheless is undefined behavior. The leak originates from the additional allocation for iterator debugging in Microsoft's implementation of the standard library.

**Comment by drfloob** [comment]
> It seems like the destructor of the tag object of type CallbackWithStatusTag is (intentionally?) not being called, which nevertheless is undefined behavior. The leak originates from the additional allocation for iterator debugging in Microsoft's implementation of the standard library.

I'd be a bit surprised if that's true. `CallbackWithStatusTag` is arena-allocated, and its owned memory is freed as part of arena destruction. But std::string's character data is almost certainly on the heap, so the string destructor must be called in any case.I imagine leak detectors would have found this already if it weren't being freed. To test your non-destruction hypothesis in your environment, you could add a log statement to gRPC and run your tests against that locally-built library https://github.com/grpc/grpc/blob/8996233989a84bf2f7441e728c9b101d45e904ee/include/grpcpp/impl/codegen/callback_common.h#L95

I do wonder if the leak detector itself is getting confused while tracking destruction through the arena. I don't have a great answer for you if that's the case.

**Comment by hitesh-kumain** [comment]
I would like to contribute on resolving this issue!

**Comment by drfloob** [comment]
I don't have access to an environment I can test this in, there's not much I can do here. If you'd like to move this forward, please feel free to produce a minrepro that proves the leak (and that the destructor is not being called).
