### ISSUE TITLE
gRPC 1.20.1 example build fail in yocto

### ISSUE THREAD

**Issue by bogdanikos** [grpc/grpc#30850]
### What version of gRPC and what language are you using?

gRPC v.1.20.1, c++

### What operating system (Linux, Windows,...) and version?

Ubuntu 20.04 host, ARM target, yocto 2.6.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 9.4

### What did you do?

I want to cross-compile helloworld cpp example for my target device. In order to do that I added `+add_subdirectory(examples/cpp/helloworld)` to CMakeLists.txt. After running bitbake grpc, I got this error message:

CMake Error at examples/cpp/helloworld/CMakeLists.txt:65 (find_package):
|   Could not find a package configuration file provided by "Protobuf" with any
|   of the following names:
| 
|     ProtobufConfig.cmake
|     protobuf-config.cmake
| 
|   Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
|   "Protobuf_DIR" to a directory containing one of the above files.  If
|   "Protobuf" provides a separate development package or SDK, be sure it has
|   been installed.

After removing CONFIG from `find_package(Protobuf CONFIG REQUIRED)` and `find_package(gRPC CONFIG REQUIRED)` in CMakeLists.txt, I am getting the same error, just for gRPC and I am stuck there:

CMake Error at examples/cpp/helloworld/CMakeLists.txt:73 (find_package):
|   By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
|   asked CMake to find a package configuration file provided by "gRPC", but
|   CMake did not find one.
| 
|   Could not find a package configuration file provided by "gRPC" with any of
|   the following names:
| 
|     gRPCConfig.cmake
|     grpc-config.cmake
| 
|   Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
|   "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
|   provides a separate development package or SDK, be sure it has been
|   installed.
| 

I patched the project so gRPC is compiling successfully without examples. Is there maybe some different way to include examples?

### What did you expect to see?
I expected to get executable for my target for helloworld example

### What did you see instead?
Just errors like described beyond.

### Anything else we should know about your project / environment?
Nothing for now

**Comment by veblush** [comment]
First of all, please use the latest version of gRPC since we kept fixing and improving the build issue. And you can use [script](https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.sh) as a reference to build an example using cmake.
