### ISSUE TITLE
Provide a debian package for grpc_csharp_ext.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3087]
Because C# has no support for building native extensions (unlike other wrapped languages) and the native code interop works differently in C#, the native extension for C# needs to be shipped as a debian package.

The layout of the `grpc_csharp_ext` package is simple:
-- the package only needs to contain libgrpc_csharp_ext.so shared library (C#/mono process will load it dynamically and invoke the functions in it using P/Invoke). No other files like headers are needed.
-- The library depends on libgrpc and libgpr.
-- The library is currently built and installed using the "make grpc_csharp_ext; make install_grpc_csharp_ext" commands.

**Comment by andrewpollock** [comment]
I have something that is ready, I'll send a PR shortly. Just something I noticed in the build output that may be fixable in a future release:

~~~
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0/usr/lib/libgrpc.so.0.10.1.0 was not linked against libdl.so.2 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0/usr/lib/libgpr.so.0.10.1.0 debian/libgrpc0/usr/lib/libgrpc.so.0.10.1.0 were not linked against libprofiler.so.0 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0-cil/usr/lib/libgrpc_csharp_ext.so.0.10.1.0 was not linked against libz.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0-cil/usr/lib/libgrpc_csharp_ext.so.0.10.1.0 was not linked against libm.so.6 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0-cil/usr/lib/libgrpc_csharp_ext.so.0.10.1.0 was not linked against libprofiler.so.0 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0-cil/usr/lib/libgrpc_csharp_ext.so.0.10.1.0 was not linked against libpthread.so.0 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libgrpc0-cil/usr/lib/libgrpc_csharp_ext.so.0.10.1.0 was not linked against librt.so.1 (it uses none of the library's symbols)
~~~

**Comment by andrewpollock** [comment]
I had a lengthy chat in #debian-cli today, and I think the way I've prepared the packaging so far is completely wrong :-)

http://pkg-mono.alioth.debian.org/cli-policy/ch-packaging.html covers how such packages should be made. I've been told that libglib2.0-cil is a good example to crib from.

**Comment by jtattermusch** [comment]
This is now obsolete. gRPC C# nugets work on windows, linux and mac without any extra steps needed.
