### ISSUE TITLE
BUG: unable to install gRPC 1.48 with Ruby 3.1.2

### ISSUE THREAD

**Issue by danielfromCL** [grpc/grpc#30947]
### What version of gRPC and what language are you using?
Ruby 3.1.2
gRPC 1.48.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What did you do?
Tried to run bundle install on a project that had been upgraded from Ruby 3.0.3 to 3.1.2 on a new clean Ruby installation, however the installation fails when installing grpc, showing the errors that are described on the gem_make.out file.

### What did you expect to see?
Correct installation of gem.

### What did you see instead?
Error in it's installation

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

[gem_make.txt](https://github.com/grpc/grpc/files/9552164/gem_make.txt)

**Comment by danielfromCL** [comment]
UPDATE: after trying to install it with version 1.49.1 (which could possibly fix the error), the error still happens 😔

**Comment by rara73** [comment]
I had the same issue when I switched to rbenv.

My config: ruby 3.1.2, grpc 1.49 or 1.48, mac M1 macOS Monterey

**Quick fix until grpc comes with a fix on a new version: use grpc 1.47 (works for me):**

`gem 'grpc', '1.47.0'`

**Comment by hankhng** [comment]
> I had the same issue when I switched to rbenv.
> 
> My config: ruby 3.1.2, grpc 1.49 or 1.48, mac M1 macOS Monterey
> 
> **Quick fix until grpc comes with a fix on a new version: use grpc 1.47 (works for me):**
> 
> `gem 'grpc', '1.47.0'`

Having the exact same issue. Getting this error message: 

`An error occurred while installing grpc (1.50.0), and Bundler cannot continue.` 

Moving down to grpc 1.47 for now works.

**Comment by maxmillssb** [comment]
You can try `bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup"` and then `bundle install`

**Comment by alto-ruby** [comment]
Can you try grpc 1.52.0 or later?
I have verified they can installed successfully with ruby 3.2.2 and 3.1.4 (using ruby installer)

**Comment by glaucocustodio** [comment]
> You can try `bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup"` and then `bundle install`

that worked for me on apple m1 (I was unable to install grpc 1.56.0 on ruby 3.1.0)

**Comment by alto-ruby** [comment]
M1 build failure tracked in #33613, fix PR #33538 had merged, will release in next version.

gettimeofday error in the original post no longer happens in latest versions.

**Comment by vertex-viet** [comment]
> You can try `bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup"` and then `bundle install`

It worked on my Macbook M1. Thanks for your answer.

**Comment by somethvictory** [comment]
> You can try bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup" and then bundle install

Worked on Macbook Pro M1 - macOS Monterey 12.4 using RVM for ruby 3.1.4 Thanks for the answer.

**Comment by AdamAjour** [comment]
`bundle clean --force`
Worked with ruby 3.1.4
