### ISSUE TITLE
`descriptor.proto` is missing from python grpcio 1.49.0

### ISSUE THREAD

**Issue by zsimic** [grpc/grpc#31020]
### What version of gRPC and what language are you using?

Python grpcio 1.49.0

### What operating system (Linux, Windows,...) and version?

Macos M1 12.6 (bug seems platform agnostic, can be observed in released source tarball as well)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.9 (bug also seems python version agnostic)

### What did you do?

`pip install grpcio` (or `grpcio-tools`, same thing).
This can be observed like so in a temp sandbox folder:

```
python3 -mvenv g48
python3 -mvenv g49
./g48/bin/pip install grpcio==1.48.1
./g49/bin/pip install grpcio==1.49.0
ls -l g*/lib/python*/site-packages/grpc*/_proto/google/protobuf/
```

You will notice that `descriptor.proto` is not in 1.49.0 (all other `.proto`-s are, except for `compiler/` subfolder missing too...)

### What did you expect to see?

File `_proto/google/protobuf/descriptor.proto`

### What did you see instead?

Missing file.

**Comment by gnossen** [comment]
CC @yashykt i believe this is related to https://github.com/grpc/grpc/pull/30377. `well_known_type_protos` does not include everything that `well_known_protos` did.

**Comment by gnossen** [comment]
@zsimic I'd recommend that you start running a test for your project that pulls in our prereleases. (run `pip install --pre grpcio-tools`). This will help us catch this sort of thing before final releases in the future.

**Comment by zsimic** [comment]
Will you yank 1.49.0? This is not from a particular project of mine, this breaks all projects that do this in one of their protos:

```
import "google/protobuf/descriptor.proto"
```

**Comment by gnossen** [comment]
So far, this is the only complaint we've heard. While we'll certainly work on releasing a 1.49.1 patch soon with the fix, I'd like to understand the impact better before making the decision to yank.

> I don't have control other those projects

Can you be more specific? Which projects? Can you provide any links?

**Comment by zsimic** [comment]
It's internal projects, sorry I'm not super familiar with grpc per se, just investigated a large set of similar build failures.

You can find such repos on github for example I'm guessing: https://github.com/search?q=google%2Fprotobuf%2Fdescriptor.proto+extension%3Aproto&type=Code&ref=advsearch&l=&l= (the subset of repos that use python grpcio with such an import should be failing right now, if they're not pinning grpcio)

**Comment by gnossen** [comment]
> Perhaps the grpc unit tests can include such an import and verify it keeps working?

Absolutely. And that will be part of the fix. But we can't predict every use case that our users will have for the code. That's why we publish pre-releases. The more tests we have running the better.

**Comment by zsimic** [comment]
Agreed.

I don't know any python projects that do this import in one of their protos off the top of my head (and can't tell github search to show only subset of "mostly python" repos), but my guess is this will impact such projects.

Not sure how many that is, I'm debating whether to wait for fix, or to recommend pinning to affected repos (internally).

**Comment by gnossen** [comment]
The patch will not be until Monday, 19 September at the earliest. In the meantime, I will keep an eye on GitHub issues. If enough users run into this issue before the patch goes out, I will yank 1.49.0.

**Comment by gnossen** [comment]
Thanks, everyone who added their reaction to this issue. I have yanked 'grpcio' 1.49.0 and all ancillary packages from PyPi. 1.49.1 will likely be published tomorrow.

To everyone who was affected by this issue, _please_ consider adding a test to your CI where you pull in our release candidates. This will help us perform our final releases with less disruption in the future. Feel free to contact me directly if you need guidance on how to do this.
