### ISSUE TITLE
Update from 1.48.1 to 1.49.0 generate 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by AMontagu** [grpc/grpc#31044]
### What version of gRPC and what language are you using?
grpcio 1.49.0
Python 3.8
protobuf 4.21.6 (seem the issue come from passing form protobuf 3.20.1 to 4.21.6 -> not done manually by me. Seem the requirements of grpcio changed)

### What operating system (Linux, Windows,...) and version?
Debian -> Python 3.8 docker image

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8

### What did you do?

- Run poetry update that make grpcio passing from 1.45.0 to 1.49.0. (tested with 1.48.1 and work fine)
- Error happen on descriptor
- Update proto. (docker-compose exec django-socio-grpc python test_utils/generateproto.py)

 Since then 'NoneType' object has no attribute 'message_types_by_name' happen.

To reproduce:
On https://github.com/socotecio/django-socio-grpc/tree/grpcUpdateError.

```
docker-compose build
docker-compose exec django-socio-grpc poetry run tests django_socio_grpc/tests/test_async_model_service_in_async.py::TestAsyncModelService::test_async_list -s
```

### What did you expect to see?

Test passed

### What did you see instead?

Error stacktrace:
```
__________________________________________ ERROR collecting django_socio_grpc/tests/test_async_model_service_in_async.py __________________________________________
django_socio_grpc/tests/test_async_model_service_in_async.py:7: in <module>
    from fakeapp.grpc.fakeapp_pb2_grpc import (
django_socio_grpc/tests/fakeapp/grpc/fakeapp_pb2_grpc.py:5: in <module>
    from django_socio_grpc.tests.fakeapp.grpc import fakeapp_pb2 as django__socio__grpc_dot_tests_dot_fakeapp_dot_grpc_dot_fakeapp__pb2
django_socio_grpc/tests/fakeapp/grpc/fakeapp_pb2.py:20: in <module>
    _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
/usr/local/lib/python3.8/site-packages/google/protobuf/internal/builder.py:64: in BuildMessageAndEnumDescriptors
    for (name, msg_des) in file_des.message_types_by_name.items():
E   AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

**Comment by gnossen** [comment]
This seems like it's probably the same as [this](https://github.com/protocolbuffers/protobuf/issues/10075#issuecomment-1205784577). Can you please confirm that you're not loading the `fake_app_pb2` module into the same process multiple times?

**Comment by snorrwe** [comment]
I have the same issue. Also using Poetry.
 Version 1.48.1 works as expected, using 1.49 results in
 ` AttributeError: 'NoneType' object has no attribute 'message_types_by_name''`

**Comment by renevall** [comment]
> This seems like it's probably the same as [this](https://github.com/protocolbuffers/protobuf/issues/10075#issuecomment-1205784577). Can you please confirm that you're not loading the `fake_app_pb2` module into the same process multiple times?

@gnossen can you clarify what does this mean? If I have a single process(say a django app) and a _pb2 file, I can't import it elsewhere?

Would this trigger if I have a messages and an events packages(where events imports messages), then my code imports both events and messages to build the event. Would this trigger what you are mentioning?

**Comment by gnossen** [comment]
> can you clarify what does this mean? If I have a single process(say a django app) and a _pb2 file, I can't import it elsewhere?

The simplest example would be copying a pb2 file to two different directories and importing both of them into the same process. A simple way to check this is running `dir()`. Alternatively, add some code in the _pb2.py file to figure out which 2 files are importing it.

**Comment by AMontagu** [comment]
Hello @gnossen 

Sorry I didn't see your response 13 days ago.

To answer your question I think I am not importing it twice in the same process as I launch a single test file. 
But indeed the import is declared multiple time in different tests file and once dynamically for the server running.

I actually do an import like:
```
from fakeapp.grpc.fakeapp_pb2_grpc import (
    UnitTestModelControllerStub,
    add_UnitTestModelControllerServicer_to_server,
)
```
in the tests.

So the questions is: How I am supposed to run my tests if I can import the same file once for the server and one for the client ?

And it's possible this is not the same issue because when I launch the serveur without the tests I have the same issue.

You have reproduction repo with step to reproduce in first message. If you want me to tests some tricks to verify your hyopthesis do not hesitate.

**Comment by gnossen** [comment]
> So the questions is: How I am supposed to run my tests if I can't import the same file once for the server and one for the client ?

You should be able to do do this so long as the `_pb2.py` file is imported from the same module path, which should be the case if there is only one `_pb2.py` file and there is nothing odd with your `sys.path`. This is the normal case for Python module loading and it's idempotent. For example, 

```
import helloworld_pb2
import helloworld_pb2
```

will only actually run the module-level code for `helloworld_pb2` once. However, if you have

```
import a.b.c.helloworld_pb2
import x.y.z.helloworld_pb2
```

this _will_ cause the module-level code to be run twice, triggering this problem. If you look closely, I expect you'll find that the second import is happening at a different import path, as in the above example.

Do note that [a fix for this has made it into the protobuf repo](https://github.com/protocolbuffers/protobuf/issues/10075#issuecomment-1260261754) and should be released fairly soon. (it may actually already be in [4.21.7](https://pypi.org/project/protobuf/4.21.7/) --  you may want to give that a shot)

**Comment by AMontagu** [comment]
I confirm you that all the import are from the same module path:

![Capture d’écran de 2022-10-05 20-09-58](https://user-images.githubusercontent.com/11883225/194131610-de57bdf1-fbcc-4513-bdc8-0e29c0fd6a03.png)

**Comment by gnossen** [comment]
I'd suggest that you add some code to the `_pb2.py` file to log a stack trace to figure out why the module-level code is being run twice then. The usage of `importlib` sounds like it's quite likely the culprit.

**Comment by AMontagu** [comment]
closing this as we never figured out but we may have change something that fixed it.
