### ISSUE TITLE
After "Failed accept4: Too many open files file", gRPC cannot continue to work after the socket file handle is released

### ISSUE THREAD

**Issue by fananchong** [grpc/grpc#31080]
When gRPC error log : message=Failed accept4: Too many open files file=/tmp1/grpc/src/core/lib/iomgr/tcp_server_posix.cc:216 ,
after a while, file handle is released , but the process can new tcp connect request, but stream event lost

**Comment by yashykt** [comment]
closing in favor of existing issue https://github.com/grpc/grpc/issues/20418

**Comment by HHDSG** [comment]
> closing in favor of existing issue #20418

Is there a time to resolve this issue? The grpc version I am using is 1.36.1 and I have the same problem
