### ISSUE TITLE
High CPU usage is found 

### ISSUE THREAD

**Issue by silverwingbug** [grpc/grpc#31082]
### What version of gRPC and what language are you using?
Grpc: 1.47.0
Python: 3.8.8

### What operating system (Linux, Windows,...) and version?
We met this issue on ESXi 7.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python: 3.8.8

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Just create MetricsMgrGrpcStub object to prepare for future message transmission.

### What did you see instead?
After the GRPC stub is created, the CPU usage would increment quickly. Besides of the significant CPU usage, the other functionality.
Unfortunately, we could not make profiling for the service.
After we change the log level to verbose, we saw the log like this:

E0907 13:38:45.642869000 1362536 cpu_linux.cc:41]            Error determining current CPU: Function not implemented

I0907 13:38:45.643461636 1362536 ev_epoll1_linux.cc:121]     grpc epoll fd: 24
D0907 13:38:45.643489872 1362536 ev_posix.cc:171]            Using polling engine: epoll1
D0907 13:38:45.643633329 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "grpclb"
D0907 13:38:45.643668661 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "rls_experimental"
D0907 13:38:45.643706812 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "priority_experimental"
D0907 13:38:45.643737389 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "weighted_target_experimental"
D0907 13:38:45.643759922 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "pick_first"
D0907 13:38:45.643781868 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "round_robin"
D0907 13:38:45.643803793 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "ring_hash_experimental"
D0907 13:38:45.643904101 1362536 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0907 13:38:45.643939429 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "cds_experimental"
D0907 13:38:45.643964352 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "xds_cluster_impl_experimental"
D0907 13:38:45.643985186 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0907 13:38:45.644007839 1362536 lb_policy_registry.cc:49]   registering LB policy factory for "xds_cluster_manager_experimental"
I0907 13:38:45.644024449 1362536 timer_manager.cc:88]        Spawn timer thread
I0907 13:38:45.644127151 1362536 init.cc:169]                grpc_init(void)
I0907 13:38:45.644175090 1362536 completion_queue.cc:520]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0907 13:38:45.644201554 1362536 completion_queue.cc:520]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0907 13:38:45.644198716 1362626 timer_generic.cc:705]       TIMER CHECK BEGIN: now=1666 next=9223372036854775807 tls_min=0 glob_min=1665
I0907 13:38:45.644240838 1362626 timer_generic.cc:603]         .. shard[0]->min_deadline = 1666
I0907 13:38:45.644251638 1362626 timer_generic.cc:518]         .. shard[0]: heap_empty=true
I0907 13:38:45.644256303 1362626 timer_generic.cc:489]         .. shard[0]->queue_deadline_cap --> 2666
I0907 13:38:45.644260164 1362626 timer_generic.cc:563]         .. shard[0] popped 0
I0907 13:38:45.644264066 1362626 timer_generic.cc:622]         .. result --> 1, shard[0]->min_deadline 1666 --> 2667, now=1666
I0907 13:38:45.644268510 1362626 timer_generic.cc:518]         .. shard[1]: heap_empty=true
I0907 13:38:45.644272275 1362626 timer_generic.cc:489]         .. shard[1]->queue_deadline_cap --> 2666
I0907 13:38:45.644365693 1362626 timer_generic.cc:563]         .. shard[1] popped 0
I0907 13:38:45.644300929 1362536 chttp2_connector.cc:370]    grpc_secure_channel_create(target=10.161.83.25:5129, creds=0x14dd22da40, args=0x15296bf340)
I0907 13:38:45.644377687 1362626 timer_generic.cc:622]         .. result --> 1, shard[1]->min_deadline 1666 --> 2667, now=1666
I0907 13:38:45.644389468 1362626 timer_generic.cc:730]       TIMER CHECK END: r=1; next=2667
I0907 13:38:45.644397620 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644453001 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644462996 1362626 timer_generic.cc:705]       TIMER CHECK BEGIN: now=1666 next=9223372036854775807 tls_min=1665 glob_min=2667
I0907 13:38:45.644467786 1362626 timer_generic.cc:730]       TIMER CHECK END: r=1; next=2667
I0907 13:38:45.644471936 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644480403 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644485702 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644489495 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644497570 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644502529 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644506396 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644515822 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644520874 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644524743 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644532606 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644537865 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644541597 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644550371 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644555756 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644559596 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644570348 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644575585 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644579325 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644587405 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644593696 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644598126 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644606032 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644610998 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644614839 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644622471 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
D0907 13:38:45.644627925 1362536 dns_resolver.cc:180]        Using native dns resolver
I0907 13:38:45.644629787 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644648850 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644658412 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644664386 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644668805 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644681981 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644690626 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644697534 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644710270 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644718353 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644725415 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644738185 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644746713 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644753199 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644767033 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644774936 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644780100 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644788837 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0
I0907 13:38:45.644796333 1362626 timer_generic.cc:683]       TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644839895 1362626 timer_manager.cc:189]       sleep for a 1001 milliseconds
I0907 13:38:45.644863047 1362626 timer_manager.cc:205]       wait ended: was_timed:1 kicked:0

The log was overwhelmed with TIMER CHECK SKIP.
It seems timer always expire quickly, not on the expected time.
To be honest, we did same operation on ubuntu, but did not run into same issue, which used the total same grpc build.
We do not know the real reason causing the timer thread to be super busy,  but have several questions about the timer operations, may the experts enlighten us on the confuse:
1. 
https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/time.cc#L35
std::atomic<int64_t> g_process_epoch_seconds;
https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/time.cc#L61
int64_t expected = 0;
if (!g_process_epoch_seconds.compare_exchange_strong(
           expected, process_epoch_seconds, std::memory_order_relaxed,
           std::memory_order_relaxed))
https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/time.cc#L77
gpr_timespec StartTime() {
  int64_t sec = g_process_epoch_seconds.load(std::memory_order_relaxed);
  if (GPR_UNLIKELY(sec == 0)) sec = InitTime().first;
  return {sec, 0, GPR_CLOCK_MONOTONIC};
}
Once the g_process_epoch_seconds is set as process_epoch_seconds for the 1st time, then it would be used directly in InitTime(), question is when it would be refreshed again?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
AJ, this looks like a timer problem.  Can you please take a look?  Thanks!

**Comment by mtwebster** [comment]
Maybe related to https://github.com/grpc/grpc/issues/30428 -  polling as of 1.45+ is 2ms instead of 200ms.

In light of https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf this becomes more urgent because the recommended versions there are unusable currently.

**Comment by silverwingbug** [comment]
> Maybe related to #30428 - polling as of 1.45+ is 2ms instead of 200ms.
> 
> In light of [GHSA-8gq9-2x98-w8hf](https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf) this becomes more urgent for our users because the recommended versions there are unusable currently.

Hi Expert,

I0907 13:38:45.644774936 1362626 timer_generic.cc:683] TIMER CHECK SKIP: now=1666 min_timer=2667
I0907 13:38:45.644780100 1362626 timer_manager.cc:189] sleep for a 1001 milliseconds
I0907 13:38:45.644788837 1362626 timer_manager.cc:205] wait ended: was_timed:1 kicked:0

From the timestamp, we could see the timer should  wake up 1001 ms later, but actually it wake up 10us later.
May I ask if there is anything we could do to verify it?

Another ask is why the seconds would minus 1 here?
https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/time.cc#L58
process_epoch_seconds = now.tv_sec - 1;

BR/Amber

**Comment by silverwingbug** [comment]
We tried to downgrade to 1.43.0, still found the CPU usage increase quickly:

275933  275821  grpc_global_tim                                         275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3      27.595116  /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275948  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UPOL    0-3       0.8913    /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275949  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UPOL    0-3       0.4602    /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275950  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.40      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275951  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.32      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275952  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.25      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275953  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.34      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275954  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.24      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275955  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.22      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275956  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.21      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275957  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.33      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275958  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.25      /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275959  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.125     /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275960  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UPOL    0-3       0.6368    /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275961  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UPOL    0-3       0.12172   /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275962  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UFUTEX  0-3       0.934     /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
275963  275821  nsx-sha                                                 275821  275806  275806  262299  UX      WAIT    UPOL    0-3       0.4374    /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py
276000  275821  grpc_global_tim                                         275821  275806  275806  262299  UX      READY   NONE    0-3      56.111662  /usr/lib/vmware/netopa/bin/nsx-sha-python /usr/lib/vmware/netopa/bin/agent.py


BR/Amber

**Comment by silverwingbug** [comment]
Hi Experts,
Two questions about the expire time calculation logics:

why the seconds would minus 1 here?
https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/time.cc#L58
process_epoch_seconds = now.tv_sec - 1;

When would g_process_epoch_seconds be updated for a second time?
https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/time.cc#L77
gpr_timespec StartTime() {
int64_t sec = g_process_epoch_seconds.load(std::memory_order_relaxed);
if (GPR_UNLIKELY(sec == 0)) sec = InitTime().first;
return {sec, 0, GPR_CLOCK_MONOTONIC};
}

Thanks for your time.
BR/Amber

**Comment by yashykt** [comment]
Echoing Esun's comment from the other issue - 
```
Yeah this could be caused by dropping epollex happened in the past but it's not clear whether it actually introduced 17% overhead on the client (surprisingly your perf data showed that server load decreased) Anyway we're going to revamp this system by introducing this new [EventEngine](https://github.com/grpc/proposal/search?q=Event+Engine&type=issues). In the meantime, would you check whether this is caused by epoll1? you can switch to epoll1 by setting GRPC_POLL_STRATEGY=epoll1 for the old versions such as 1.43.
```
We are not yet sure if the two issues are related, but it is worth a shot.
