### ISSUE TITLE
Crash on client when server shut down

### ISSUE THREAD

**Issue by backni** [grpc/grpc#31123]
### What version of gRPC and what language are you using?
grpc : 1.48.1
language : C++

### What operating system (Linux, Windows,...) and version?
Windows 10, Version 20H2(OS Build 19042.1889)

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS 2017, cl 19.16.27048 

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
1. Run the helloworld server.
2. Run the the below that just added for loop from sample.
--------------------------------------------------
int main(int argc, char** argv) {
	// Instantiate the client. It requires a channel, out of which the actual RPCs
	// are created. This channel models a connection to an endpoint specified by
	// the argument "--target=" which is the only expected argument.
	// We indicate that the channel isn't authenticated (use of
	// InsecureChannelCredentials()).
	std::string target_str;
	std::string arg_str("--target");
	if (argc > 1) {
		std::string arg_val = argv[1];
		size_t start_pos = arg_val.find(arg_str);
		if (start_pos != std::string::npos) {
			start_pos += arg_str.size();
			if (arg_val[start_pos] == '=') {
				target_str = arg_val.substr(start_pos + 1);
			}
			else {
				std::cout << "The only correct argument syntax is --target="
					<< std::endl;
				return 0;
			}
		}
		else {
			std::cout << "The only acceptable argument is --target=" << std::endl;
			return 0;
		}
	}
	else {
		target_str = "localhost:50051";
	}

	GreeterClient greeter(
		grpc::CreateChannel(target_str, grpc::InsecureChannelCredentials()));
	for (;;)
	{
		std::string user("world");
		std::string reply = greeter.SayHello(user);
		std::cout << "Greeter received: " << reply << std::endl;
		
		Sleep(3000);
	}

	return 0;
}
--------------------------------------------------
3. Exit server by Ctrl+c in powershell.

4. Then I got runtime error in client like below.

![image](https://user-images.githubusercontent.com/9497594/192213981-34f1f383-fbaf-4491-b0c5-79cc941025ed.png)

### What did you expect to see?
The application is crashed.

### What did you see instead?
The application should not crash.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
Closing in favor of https://github.com/grpc/grpc/issues/29185
