### ISSUE TITLE
gRPC crash when TLS enabled

### ISSUE THREAD

**Issue by lidezhu** [grpc/grpc#31122]
### What version of gRPC and what language are you using?
grpc 1.44.0 C++
openssl 1.1.1o

### What operating system (Linux, Windows,...) and version?
CentOS 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang 13.0.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Enable TLS.

### What did you expect to see?
gRPC works correctly.

### What did you see instead?
gRPC crash with the following stack:
[2022/09/22 16:53:09.301 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=201]
[2022/09/22 16:53:09.302 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 200) Received signal Segmentation fault(11)."] [thread_id=201]
[2022/09/22 16:53:09.302 +08:00] [ERROR] [BaseDaemon.cpp:408] ["BaseDaemon:Address: 0x10"] [thread_id=201]
[2022/09/22 16:53:09.302 +08:00] [ERROR] [BaseDaemon.cpp:412] ["BaseDaemon:Access: write."] [thread_id=201]
[2022/09/22 16:53:09.302 +08:00] [ERROR] [BaseDaemon.cpp:423] ["BaseDaemon:Address not mapped to object."] [thread_id=201]
[2022/09/22 16:53:12.400 +08:00] [ERROR] [BaseDaemon.cpp:570] ["BaseDaemon:^@
       0x6718361\tfaultSignalHandler(int, siginfo_t*, void*) [+108102497]^@
                \tlibs/libdaemon/src/BaseDaemon.cpp:221^@
  0x7f9e52d24630\t<unknown symbol> [libpthread.so.0+63024]^@
       0x1ac346a\t__folly_memcpy [+28062826]^@
                \tlibs/libmemcpy/folly/memcpy.S:176^@
       0x1d2f063\trand_pool_add [+30601315]^@
       0x1d3025e\trand_pool_add_additional_data [+30605918]^@
       0x1d2f09f\trand_drbg_get_additional_data [+30601375]^@
       0x1d2b3cd\tRAND_DRBG_bytes [+30585805]^@
       0x1d3e775\tRSA_padding_add_PKCS1_PSS_mgf1 [+30664565]^@
       0x1d3c3e3\tpkey_rsa_sign [+30655459]^@
       0x1cec5d4\tEVP_DigestSignFinal [+30328276]^@
       0x1c097da\ttls_construct_cert_verify [+29399002]^@
       0x1c00671\tstate_machine [+29361777]^@
       0x7be6b75\tssl_handshaker_next(tsi_handshaker*, unsigned char const*, unsigned long, unsigned char const**, unsigned long*, tsi_handshaker_result**, void (*)(tsi_result, void*, unsigned char const*, unsigned long, tsi_handshaker_result*), void*) [tiflash+129919861]^@
                \tcontrib/grpc/src/core/tsi/ssl_transport_security.cc:1568^@
       0x7a927db\tgrpc_core::(anonymous namespace)::SecurityHandshaker::OnHandshakeDataReceivedFromPeerFn(void*, grpc_error*) [+128526299]^@
                \tcontrib/grpc/src/core/lib/security/transport/security_handshaker.cc:463^@
       0x7a2f1c1\tpollset_work(grpc_pollset*, grpc_pollset_worker**, long) [+128119233]^@
                \tcontrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1139^@
       0x7aadece\tcq_next(grpc_completion_queue*, gpr_timespec, void*) [

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
Please provide a way to reproduce this and re-open/create a new issue
