### ISSUE TITLE
How to use without the server?

### ISSUE THREAD

**Issue by paulocoutinhox** [grpc/grpc#31185]
Hi,

How to use without the server?

I want transfer the data to grpc thought a string, array of bytes, or something like this, like you receive from grpc server, but i will put it manually.

I need communicate from my mobile app without the server, so i will send from mobile a string or bytes, receive on cxx side, send/inject into grpc and grpc will work like it receive from grpc server.

How can i do this?

Thanks.

**Comment by drfloob** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.
