### ISSUE TITLE
grpc.io Not Core version not updated since v1.48.1

### ISSUE THREAD

**Issue by darkn3rd** [grpc/grpc#31206]
### What version of gRPC and what language are you using?

```
grpcio==1.49.1
```

### What operating system (Linux, Windows,...) and version?

```
Ubuntu 22.04 LTS
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
Python 3.10.4
```

### What did you do?

```bash
# instructions: https://grpc.io/docs/languages/python/quickstart/
git clone -b v1.48.1 --depth 1 --shallow-submodules https://github.com/grpc/grpc
cd grpc/examples/python/helloworld

# Requirements instructions: https://github.com/grpc/grpc/blob/master/doc/python/server_reflection.md
pip install grpcio-reflection

python greeter_server_with_reflection.py
```

### What did you expect to see?

The server would work and produce a Traceback.

### What did you see instead?

```
Traceback (most recent call last):
  File "/home/user/grpc_project/greeter_server_with_reflection.py", line 21, in <module>
    import helloworld_pb2
  File "/home/user/grpc_project/helloworld_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/home/joaquin/.pyenv/versions/greeter-3.10.4/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Anything else we should know about your project / environment?

There needs to be instructions that install the compatible versions of modules that work with existing code, and existing code needs to be brought up to date to work with current vresions of modules.  Need to know the correct version of `grpcio-reflection` to use.

**Comment by gnossen** [comment]
Yup. This is a docs bug. The latest release of grpc is compatible with protobuf 4.X and the generated code on the 1.49.x branch is only protobuf 4.X compatible.

Please try cloning with `-b v1.49.1` instead of `-b v1.49.1`

**Comment by gnossen** [comment]
The site has been updated, so this should no longer be an issue.
