### ISSUE TITLE
fling_stream_test fails on 32-bit architectures

### ISSUE THREAD

**Issue by andrewpollock** [grpc/grpc#3120]
Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797137 for the full context, but in a nutshell it looks like the fling_stream_test test fails on 32-bit architectures, as it prevented the 32-bit builds completing successfully.

https://buildd.debian.org/status/package.php?p=grpc&suite=sid shows all the architectures it failed on.

**Comment by andrewpollock** [comment]
@tbetbetbe can you assign this to someone?

**Comment by jtattermusch** [comment]
I suspect this one might be resolved. We are running continuous tests for 32bit jessie and the test is not failing there.

https://grpc-testing.appspot.com/job/gRPC_portability_master/381/language=c,scenario=linux_x86_default/
