### ISSUE TITLE
grpc/src/compiler/csharp_generator.h error

### ISSUE THREAD

**Issue by Hibbert-pku** [grpc/grpc#3122]
Hello,
  1. When I install grpc, there is an error: 

    ./src/compiler/csharp_generator.h:42:43: fatal error: google/protobuf/stubs/strutil.h: No such file or directory

 I check the .h files under google/protobuf/stubs/, and there is only a .h file called 'stl_util.h'. I use ubuntu 12.04

  2. By the way, should googler write code like "using namespace std;" in "grpc/src/compiler/csharp_generator.h" ?

@jtattermusch

**Comment by oije2333** [comment]
I receive same error on ubuntu 14.04.

**Comment by jtattermusch** [comment]
Most likely, you have an older version of protobufs installed.

Make sure pkg-config doesn't report protobuf being installed.

$ pkg-config --modversion protobuf

You may need to get rid of these files:
/usr/lib/pkgconfig/protobuf-lite.pc 
/usr/lib/pkgconfig/protobuf.pc

**Comment by yang-g** [comment]
Seems to be from #2863
