### ISSUE TITLE
default location for ssl_credentials is no good for windows.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3127]
grpc_ssl_credentials_create()  checks the "/usr/share/grpc/roots.pem" path as well known path for root certs. That's no use on Windows.

**Comment by jboeuf** [comment]
Can you provide me with the install path for windows?

**Comment by jboeuf** [comment]
As we discussed. Let's include etc/roots.pem in the NuGet and instruct our windows users to set the env var to it.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/3165
