### ISSUE TITLE
mock_stream.h is not externally visible when using Bazel 

### ISSUE THREAD

**Issue by smolkaj** [grpc/grpc#31296]
### What version of gRPC and what language are you using?
v1.49.1, C++ 

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
LLVM / gcc with Bazel

### What did you do?
Depend on the target `@com_github_grpc_grpc//:grpc++_test` in my `BUILD.bazel` file, see screenshot.

### What did you expect to see?
For things to compile.

### What did you see instead?
The following error message:
```
ERROR: /home/runner/work/pins-infra/pins-infra/p4_pdpi/BUILD.bazel:312:11: in cc_library rule //p4_pdpi:p4_runtime_session_mocking: target '@com_github_grpc_grpc//:grpc++_test' is not visible from target '//p4_pdpi:p4_runtime_session_mocking'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

### Anything else we should know about your project / environment?

I am a Google SWE working on a project that is used both internally and in open source.

This issue seems to be similar to https://github.com/grpc/grpc/issues/20208 and https://github.com/grpc/grpc/pull/20369.

### Screenshot

![image](https://user-images.githubusercontent.com/6642034/194686130-3dc80057-4492-4bd9-a6a8-6f9ce0653fda.png)

**Comment by smolkaj** [comment]
@jonathan-dilorenzo for visibility

**Comment by yashykt** [comment]
There seems to be some discussion around this on https://github.com/grpc/grpc/pull/26641

**Comment by rdesgroppes** [comment]
Is there a suggested way to overcome the visibility issue?

**Comment by smadhuk** [comment]
+1, I ran into this as well while trying to test streaming RPCs. Is there any way to include `mock_stream.h` in a bazel build?
