### ISSUE TITLE
Python tests shouldn't spam the log

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#3129]
It's great that we're testing how one part of the system under test behaves when another part of the system under test encounters a staged failure, but we should clean up our act by not allowing the test log to be spammed full of exception tracebacks.

**Comment by soltanmm** [comment]
I think that's just a py.test thing. Assign to me?

**Comment by nathanielmanistaatgoogle** [comment]
I don't think so; I think it's that we use a logging_pool._LoggingPool for the pool in which we run simulated application code, and when that simulated application code throws an exception, it gets logged. I think what I have in mind for this is another kind of pool on which you can do things like setting expectations of what exceptions tasks run within it are allowed to throw and asking it what exceptions tasks have thrown and that kind of thing.

**Comment by nathanielmanistaatgoogle** [comment]
Since this was filed we've changed the way test output is recorded and this is no longer a problem.
