### ISSUE TITLE
Shouldn't the pkg-config file list re2 and cares as dependencies?

### ISSUE THREAD

**Issue by mortie** [grpc/grpc#31336]
The pkg-config files generated by the build script (grpc.pc, grpc++.pc) don't list re2 and libcares as dependencies, even though they are. The pkg-config files only add `-lre2` and `-lcares` to LDFLAGS through `Libs`. On systems where libre2 and libcares happen to be in the default library search path, this happens to work, but on systems where they're anywhere else, it breaks.

### What version of gRPC and what language are you using?

1.49.1

### What operating system (Linux, Windows,...) and version?

macOS 13

### What runtime / compiler are you using (e.g. python version or version of gcc)

Apple clang version 14.0.0

### What did you do?

Ran `pkg-config --libs grpc`.

### What did you expect to see?

I expected to see `-L/opt/homebrew/Cellar/re2/20220601/lib` and `-L/opt/homebrew/Cellar/c-ares/1.18.1_1/lib` among the flags produced, since those flags are required to link against grpc's dependencies libcares and libre2 on my systems, as shown by `pkg-config --libs re2 libcares`.

### What did you see instead?

I saw an output which only contains `-lre2` and `-lcares` but not the necessary `-L` flags. This means linking with `cc myprogram.o $(pkg-config --libs grpc)` doesn't work.

**Comment by yashykt** [comment]
@veblush Can we close this now?

**Comment by veblush** [comment]
Sure!
