### ISSUE TITLE
SIGSEGV (null pointer dereference) when create channel with TLS on ARM server

### ISSUE THREAD

**Issue by Danliran** [grpc/grpc#31344]
### What version of gRPC and what language are you using?

1.36.1
### What operating system (Linux, Windows,...) and version?
linux 
ARM server

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.3.0

### What did you do?

we occur  Segmentation fault when we used grpc c++ with TLS.  I used  RPC call to send some messge to another server, at begining it work find, but several minute later, it`s  crashed.
```
std::shared_ptr<grpc::Channel> getSslChannel(string address)
{
     grpc::SslCredentialsOptions sslOptions;
    sslOptions.pem_root_certs = caFileContent;
    sslOptions.pem_cert_chain = agentCertContent;
    sslOptions.pem_private_key = priKey;

    std::shared_ptr<grpc::ChannelCredentials> creds = grpc::SslCredentials(sslOptions);
    grpc::ChannelArguments channel_args;
    channel_args.SetString("grpc.default_authority", "fds");
    channel_args.SetString("grpc.ssl_target_name_override", "fds");
    return grpc::CreateCustomChannel(address, creds, channel_args);
}
```

It seems grpc::CreateCustomChannel(address, creds, channel_args) function return 0x0 pointer.
![image](https://user-images.githubusercontent.com/38999651/195592528-5a082967-1d41-4fea-a3ef-843f412af79c.png)

### What did you see instead?
look like grpc::CreateCustomChannel(address, creds, channel_args) return 0x0 pointer.  I modify code refernce [issue 20377](https://github.com/grpc/grpc/issues/20377),but doesn`t work.
post some trace here

> 

>  1013 20:02:20.737834485 1857406 security_context.cc:249]    grpc_auth_context_add_property(ctx=0xffff8802c790, name=security_level, value=TSI_PRIVACY_AND_INTEGRITY, value_length=25)
I1013 20:02:20.737841055 1857406 security_context.cc:249]    grpc_auth_context_add_property(ctx=0xffff8802c790, name=ssl_session_reused, value=false, value_length=5)
I1013 20:02:20.737848445 1857406 security_context.cc:207]    grpc_auth_context_find_properties_by_name(ctx=0xffff8802c790, name=x509_common_name)
I1013 20:02:20.737855375 1857406 security_context.cc:180]    grpc_auth_property_iterator_next(it=0xffff8fffe2a8)
I1013 20:02:20.737861025 1857406 security_context.cc:154]    grpc_auth_context_set_peer_identity_property_name(ctx=0xffff8802c790, name=x509_common_name)
I1013 20:02:20.737885795 1857406 init.cc:168]                grpc_init(void)
I1013 20:02:20.738156805 1857406 call.cc:1569]               ops[0]: RECV_INITIAL_METADATA ptr=0xffff880083f8
I1013 20:02:20.738191515 1857406 call.cc:1569]               ops[0]: RECV_MESSAGE ptr=0xffff880083d0
I1013 20:02:20.738221875 1857406 completion_queue.cc:705]    cq_end_op_for_next(cq=0xffffa00d4bc0, tag=0xffffa00a7a10, error="No Error", done=0xfffff5941f48, done_arg=0xffff0c002700, storage=0xffff0c002728)
I1013 20:02:20.738238735 1857406 completion_queue.cc:1083]   RETURN_EVENT[0xffffa00d4bc0]: OP_COMPLETE: tag:0xffffa00a7a10 OK
I1013 20:02:20.738248175 1857406 completion_queue.cc:524]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I1013 20:02:20.738256255 1857406 server.cc:1578]             grpc_server_request_registered_call(server=0xffffa00d4f70, registered_method=0xffffa00d76b0, call=0xffffa00a7a30, deadline=0xffffa00a7a40, request_metadata=0xffffa00a7a50, optional_payload=0xffffa00a7a68, cq_bound_to_call=0xffff880142d0, cq_for_notification=0xffffa00d4bc0, tag=0xffffa00a7a10)
I1013 20:02:20.738279615 1857406 call.cc:1974]               grpc_call_start_batch(call=0xffff88007920, ops=0xffff8fffe520, nops=1, tag=0xffff8800a1b0, reserved=(nil))
I1013 20:02:20.738288195 1857406 call.cc:1569]               ops[0]: RECV_CLOSE_ON_SERVER cancelled=0xffff8800a21c
I1013 20:02:20.738330195 1857406 call.cc:1974]               grpc_call_start_batch(call=0xffff88007920, ops=0xffff8fffe008, nops=3, tag=0xffff8fffe288, reserved=(nil))
I1013 20:02:20.738340895 1857406 call.cc:1569]               ops[0]: SEND_INITIAL_METADATA(nil)
I1013 20:02:20.738348025 1857406 call.cc:1569]               ops[1]: SEND_MESSAGE ptr=0xffff0c011d80
I1013 20:02:20.738357575 1857406 call.cc:1569]               ops[2]: SEND_STATUS_FROM_SERVER status=0 details=(null)(nil)
I1013 20:02:20.738417945 1857406 completion_queue.cc:789]    cq_end_op_for_pluck(cq=0xffff880329f0, tag=0xffff8800a1b0, error="No Error", done=0xfffff59391a0, done_arg=0xffff8800a310, storage=0xffff8800a358)
I1013 20:02:20.738429795 1857406 completion_queue.cc:789]    cq_end_op_for_pluck(cq=0xffff880329f0, tag=0xffff8fffe288, error="No Error", done=0xfffff59391a0, done_arg=0xffff8800a420, storage=0xffff8800a468)
I1013 20:02:20.738442475 1857406 completion_queue.cc:1320]   RETURN_EVENT[0xffff880329f0]: OP_COMPLETE: tag:0xffff8fffe288 OK
I1013 20:02:20.738455575 1857406 completion_queue.cc:1420]   grpc_completion_queue_shutdown(cq=0xffff880329f0)
I1013 20:02:20.738466625 1857406 completion_queue.cc:1320]   RETURN_EVENT[0xffff880329f0]: OP_COMPLETE: tag:0xffff8800a1b0 OK
I1013 20:02:20.738474215 1857406 completion_queue.cc:1320]   RETURN_EVENT[0xffff880329f0]: QUEUE_SHUTDOWN
I1013 20:02:20.738481195 1857406 metadata_array.cc:34]       grpc_metadata_array_destroy(array=0xffff8802e8a0)
I1013 20:02:20.738487695 1857406 call.cc:586]                grpc_call_unref(c=0xffff88007920)
I1013 20:02:20.738494885 1857406 metadata_array.cc:34]       grpc_metadata_array_destroy(array=0xffff880083f8)
I1013 20:02:20.738501735 1857406 completion_queue.cc:1426]   grpc_completion_queue_destroy(cq=0xffff880329f0)
I1013 20:02:20.738507325 1857406 completion_queue.cc:1420]   grpc_completion_queue_shutdown(cq=0xffff880329f0)
I1013 20:02:20.738516755 1857406 completion_queue.cc:982]    grpc_completion_queue_next(cq=0xffffa00d4bc0, deadline=gpr_timespec { tv_sec: 91806, tv_nsec: 184530915, clock_type: 0 }, reserved=(nil))
I1013 20:02:20.738695905 1857406 init.cc:215]                grpc_shutdown(void)
[LWP 1858372 exited]
[LWP 1858374 exited]
Thread 110 ccm_main received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1858373]
0x0000fffff56ee414 in grpc::internal::RpcMethod::RpcMethod (this=0xfffebc026788, 
    name=0xfffff5acc238 "/globalcache.Globalcache/CcmEventCall", type=grpc::internal::RpcMethod::NORMAL_RPC, 
    channel=std::shared_ptr (empty) 0x0) at /usr/local/include/grpcpp/impl/codegen/rpc_method.h:45

 
--------
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
The code provided is not enough to reproduce this, nor does it provide enough information to help us reproduce this on our own. My initial gut instinct is that there is an API usage issue over here, but I don't have anything more to go on.

**Comment by Danliran** [comment]
> 

Hi  yashykt, which API usage issue?
