### ISSUE TITLE
Application stuck due to infinite loop in library

### ISSUE THREAD

**Issue by asthamohta** [grpc/grpc#31355]
### What version of gRPC and what language are you using?
1.47.0

### What operating system (Linux, Windows,...) and version?
macOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Our function gets stuck on the line:
for item in iterator: 
which tries to call the iterable.__next__ function in python grpc:
https://github.com/grpc/grpc/blob/2ffff621a46d04d5b29bb056ba7837789c0b52ba/src/python/grpcio/grpc/_channel.py#L817
If we go into the wait function we find an infinite loop as no timeout is provided: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_common.py#L139-L141

Because of this our long running functions are failing if connections break. 
### What did you expect to see?
function completed

### What did you see instead?
Application hanging

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
Can you please provide some more information on how to reproduce the issue? The `_common.wait` function is used pervasively throughout the stack. As you can see, the condition waited on is pluggable. Without knowing the condition that is never evaluating to `True`, we can't really come to any conclusions here.

**Comment by asthamohta** [comment]
We are actually directly using iterator functionality in python which causes the issue. 
When running a long running update function in Google Spanner, called using this function:
https://github.com/googleapis/python-spanner/blob/main/google/cloud/spanner_v1/database.py#L487
Code is stuck on this line: https://github.com/googleapis/python-spanner/blob/main/google/cloud/spanner_v1/snapshot.py#L62

To reproduce, create a spanner db with more than 2 million rows and call the execute_partitioned_dml function. The application will be stuck indefinitely.
