### ISSUE TITLE
Calling TryCancel of SrverContext causes Segment fault

### ISSUE THREAD

**Issue by springile** [grpc/grpc#31360]
### What version of gRPC and what language are you using?
1.47

### What operating system (Linux, Windows,...) and version?
CentOS 7.9

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.3

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Calling TryCancel of ServerContext crashes.

![image](https://user-images.githubusercontent.com/50204931/195879449-cf6aedc3-b95d-49da-b8cb-d87c3dbd71ce.png)

### What did you expect to see?
It should not crash

### What did you see instead?
Segment fault
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
Please re-open or create a new issue with a reproduction for this. (Can't do much without one)

**Comment by springile** [comment]
@yashykt ,

This is the simple unit test.

TEST(ServerContextTest, TryCancelTest) {
    grpc::ServerContext mock_context;

    mock_context.TryCancel();    
}
