### ISSUE TITLE
gRPC with HoloLens 2

### ISSUE THREAD

**Issue by HaiKonofanDesu** [grpc/grpc#31377]
Hey there,

I want to use grpc for a HoloLens app I'm currently developing. Sadly HoloLens 2 throws a lot of errors when I try to run it there

All tutorials like https://github.com/grpc/grpc/issues/20344#issuecomment-561559557 or https://github.com/grpc/grpc/issues/23488#issuecomment-690766560 say I need to build grpc_csharp_ext. which I can't find probably because of the split to grpc-dotnet. So I would like to ask if someone can let me know how I can actually recompile the dotnet Plugins or how to recompile the other plugins/ get the grpc_csharp_ext plugin back.

Here are my currently used .dll:

Google.Protobuf.3.21.5
Grpc.Core.Api.2.49.0
Grpc.Net.Client.2.49.0
Grpc.Net.Client.Web.2.49.0
Grpc.Net.Common.2.49.0
Microsoft.Logging.Abstractions.3.0.3
System.DiagnosticSource.4.5.1

I asked this question in grpc-dotnet as well (because I currently use the .net plugins) and they told me HoloLens 2 does not support HTTP/2 which probably means I need to use an older version of grpc?

I already tried the latest grpc for Unity package I could find. I got it running in Unity but when I try to build the Solution for HoloLens 2 I got an error and this was the Feedback from the Unity support:

------------------------------------

> I am the developer who investigated this bug report. Unfortunately, I don't think this is a bug in Unity. Let me elaborate.

> When you have C# code like this:

```
[DllImport("__Internal")]
static extern void SomeFunction();
```

>IL2CPP will translate that to a direct function call that the native code linker will have to resolve. If the linker fails to locate those function implementations, it will result in linker errors. In your case, there are a whole bunch of such functions in Grpc.Core.dll that is in your project (in the Assets\Plugins\Grpc.Core\lib\net45 folder):

```
class DllImportsFromSharedLib
{
    private const string ImportName = "grpc_csharp_ext";

    [DllImport("grpc_csharp_ext")]
    public static extern void grpcsharp_init();

    [DllImport("grpc_csharp_ext")]
    public static extern void grpcsharp_shutdown();

    [DllImport("grpc_csharp_ext")]
    public static extern IntPtr grpcsharp_version_string();

    [DllImport("grpc_csharp_ext")]
    public static extern BatchContextSafeHandle grpcsharp_batch_context_create();

    ...
```

>However, there is no implementation provided in terms of ".c" or ".cpp" files in the project. Due to that, the build fails as it is trying to call the functions that do not exist.

-----------------------

Anyway if anyone has an idea/ rebuild Plugins or anything that can help me out please let me know!

I appreciate any help!

**Comment by jtattermusch** [comment]
@tonydnewell

**Comment by tonydnewell** [comment]
@HaiKonofanDesu C# on Grpc.Core is currently in maintenance mode: https://grpc.io/blog/grpc-csharp-future/ thus the support for Unity (which was always experimental) has stopped.

You can find the old Grpc.Core implementation in the v1.46.x branch: https://github.com/grpc/grpc/tree/v1.46.x/src/csharp
and information for building Unity: https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental

In one of the comments you linked to (https://github.com/grpc/grpc/issues/20344#issuecomment-561559557) then line that builds the grpc_csharp_ext library is:
- build grpc_charp_ext: `python tools/run_tests/run_tests.py -l csharp -c opt --build_only`

I hope the above gives you some help. I'm afraid I don't have the infrastructure to build or maintain support for Unity.

**Comment by HaiKonofanDesu** [comment]
@tonydnewell I installed Ninja as needed to run 

> python tools/run_tests/run_tests.py -l csharp -c opt --build_only

But I get this error when I try it with the 1.46 branch. Any ideas?
```
c:\PDA\grpc\cmake\build>cmake -G Ninja -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" -DCMAKE_BUILD_TYPE=Release -DgRPC_BUILD_TESTS=OFF -DgRPC_MSVC_STATIC_RUNTIME=ON -DgRPC_XDS_USER_AGENT_IS_CSHARP=ON ../..   || goto :error
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:246 (include):
  include could not find requested file:
    cmake/msvc_static_runtime.cmake

CMake Error at CMakeLists.txt:311 (include):
  include could not find requested file:
    cmake/ccache.cmake

CMake Error at CMakeLists.txt:313 (include):
  include could not find requested file:
    cmake/abseil-cpp.cmake

CMake Error at CMakeLists.txt:314 (include):
  include could not find requested file:
    cmake/address_sorting.cmake

CMake Error at CMakeLists.txt:315 (include):
  include could not find requested file:
    cmake/benchmark.cmake

CMake Error at CMakeLists.txt:316 (include):
  include could not find requested file:
    cmake/cares.cmake

CMake Error at CMakeLists.txt:317 (include):
  include could not find requested file:
    cmake/protobuf.cmake

CMake Error at CMakeLists.txt:318 (include):
  include could not find requested file:
    cmake/re2.cmake

CMake Error at CMakeLists.txt:319 (include):
  include could not find requested file:
    cmake/ssl.cmake

CMake Error at CMakeLists.txt:320 (include):
  include could not find requested file:
    cmake/upb.cmake

CMake Error at CMakeLists.txt:321 (include):
  include could not find requested file:
    cmake/xxhash.cmake

CMake Error at CMakeLists.txt:322 (include):
  include could not find requested file:
    cmake/zlib.cmake

CMake Error: File C:/PDA/grpc/cmake/gRPCConfig.cmake.in does not exist.
CMake Error at CMakeLists.txt:17422 (configure_file):
  configure_file Problem configuring file

CMake Error: File C:/PDA/grpc/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:17451 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:17460 (generate_pkgconfig)

CMake Error: File C:/PDA/grpc/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:17451 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:17470 (generate_pkgconfig)

CMake Error: File C:/PDA/grpc/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:17451 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:17480 (generate_pkgconfig)

CMake Error: File C:/PDA/grpc/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:17451 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:17490 (generate_pkgconfig)

CMake Error: File C:/PDA/grpc/cmake/pkg-config-template.pc.in does not exist.
CMake Error at CMakeLists.txt:17451 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:17500 (generate_pkgconfig)

-- Configuring incomplete, errors occurred!
See also "C:/PDA/grpc/cmake/build/CMakeFiles/CMakeOutput.log".

c:\PDA\grpc\cmake\build>echo Failed!
Failed!

````

**Comment by HaiKonofanDesu** [comment]
> @HaiKonofanDesu C# on Grpc.Core is currently in maintenance mode: https://grpc.io/blog/grpc-csharp-future/ thus the support for Unity (which was always experimental) has stopped.
> 
> You can find the old Grpc.Core implementation in the v1.46.x branch: https://github.com/grpc/grpc/tree/v1.46.x/src/csharp and information for building Unity: https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental
> 
> In one of the comments you linked to ([#20344 (comment)](https://github.com/grpc/grpc/issues/20344#issuecomment-561559557)) then line that builds the grpc_csharp_ext library is:
> 
> * build grpc_charp_ext: `python tools/run_tests/run_tests.py -l csharp -c opt --build_only`
> 
> I hope the above gives you some help. I'm afraid I don't have the infrastructure to build or maintain support for Unity.

Thanks for the reply. I got to the point where I can now build my grpc.sln and get a  grpc_csharp_ext.dll but I don't understand how I can generate a new Grpc.Corde.dll
