### ISSUE TITLE
bazel-bin/external/com_google_protobuf/protoc: No such file or directory

### ISSUE THREAD

**Issue by skrypnik-dzencode** [grpc/grpc#31408]
The third step (run `./greeter_proto_gen.sh`) of the guide https://grpc.io/docs/languages/php/quickstart/ fails with error 
`./greeter_proto_gen.sh: line 25: bazel-bin/external/com_google_protobuf/protoc: No such file or directory`

gRPC v1.50.0

OS Ubuntu
- VERSION="21.04 (Hirsute Hippo)"

**Comment by skrypnik-dzencode** [comment]
Ok, we can separately install protobuf-compiler and protobuf-compiler-grpc, then we can change greeter_proto_gen.sh file like this:
`PROTOC=protoc`
`PLUGIN=protoc-gen-grpc=/usr/bin/grpc_php_plugin`
And after that, we still failed on the same third step by running `./greeter_proto_gen.sh`: `--grpc_out: helloworld.proto: unsupported options: generate_server`

**Comment by Eazybright** [comment]
you can follow this guide https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/src/php to install the `protoc` compiler and `grpc_php_plugin` protoc plugin 

you also need to install bazel https://bazel.build/install/
then run: 
```
bazel build @com_google_protobuf//:protoc //src/compiler:all
```
before proceeding to run `./greeter_proto_gen.sh`
