### ISSUE TITLE
grpc_message":"No module named 'concurrent.futures.thread'"

### ISSUE THREAD

**Issue by zizhong** [grpc/grpc#31427]
### What version of gRPC and what language are you using?
```
grpcio                          1.45.0
grpcio-tools                    1.45.0
```

### What operating system (Linux, Windows,...) and version?
```
Linux dev-2 5.15.0-1019-azure #24~20.04.1-Ubuntu SMP Tue Aug 23 15:52:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
python --version
Python 3.8.10
```

### What did you do?
Using a gRPC python client to call stub endpoint.
And got this gRPC error
```
2022-10-21 23:23:09 - ERROR - Unknown Error: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "No module named 'concurrent.futures.thread'"
	debug_error_string = "{"created":"@1666394589.340558094","description":"Error received from peer ipv4:127.0.0.1:50055","file":"src/core/lib/surface/call.cc","file_line":905,"grpc_message":"No module named 'concurrent.futures.thread'","grpc_status":2}"
```

I can find the module installed
```
Python 3.8.10 (default, Sep 22 2022, 23:15:12)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import concurrent.futures.thread
>>> concurrent.futures.thread
<module 'concurrent.futures.thread' from '/home/user/.pyenv/versions/3.8.10/lib/python3.8/concurrent/futures/thread.py'>
```

### What did you expect to see?
No error.

### What did you see instead?
This error.

**Comment by gnossen** [comment]
Would you care to share your server-side code?

**Comment by zizhong** [comment]
Actually figured out the issue.

Previously I upgraded python from 3.7 to 3.8, `concurrent.futures.thread` becomes a standard library. 
The grpc server I'm working with does file lock stuff preventing itself from being updated and still running with 3.7.
After restarting the server, the issue went away.
