### ISSUE TITLE
Crash in RunInterceptor when servicing 2 requests at the same time

### ISSUE THREAD

**Issue by christophe-calmejane** [grpc/grpc#31438]
### What version of gRPC and what language are you using?
c++ v1.41.0 (from vcpkg)

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS 17.3.5

### What did you do?
I managed to write a minimal client/server example that causes a crash in the client code in RunInterceptor, here are the files:
**Proto File**
```
syntax = "proto3";

package myService;

service MyService
{
  rpc Ping(EmptyMessage) returns (PongResponse) {}
  rpc StartStream(EmptyMessage) returns (stream StreamEvent) {}
}

message EmptyMessage
{
}

message PongResponse
{
  bool pong = 1;
}

message StreamEvent
{
  uint64 value = 1;
  uint32 otherValue = 2;
  bool yetAnotherValue = 3;
}
```

**Server File**
```#ifdef _WIN32
#    pragma warning(push)
#    pragma warning(disable : 4251) // Disable dll-class warning
#    pragma warning(disable : 4127) // Disable conditional expression is constant
#endif
#include "service.grpc.pb.h"
#include <grpcpp/grpcpp.h>
#ifdef _WIN32
#    pragma warning(pop)
#endif

#include <iostream>
#include <string>
#include <chrono>
#include <thread>
#include <memory>

class Service final : public myService::MyService::Service
{
public:
    Service(std::string const& uri)
    {
        _builder.AddListeningPort(uri, grpc::InsecureServerCredentials());
        _builder.RegisterService(this);
    }

    void start()
    {
        _server = _builder.BuildAndStart();
    }

    void stop()
    {
        if (_server != nullptr)
        {
            _server->Shutdown();
        }
    }

private:
    virtual ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::myService::EmptyMessage* /*request*/, ::myService::PongResponse* response) override
    {
        std::cout << "Ping request\n";
        response->set_pong(true);
        return grpc::Status::OK;
    }
    virtual ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::myService::EmptyMessage* /*request*/, ::grpc::ServerWriter<::myService::StreamEvent>* writer) override
    {
        {
            auto evt = myService::StreamEvent{};
            evt.set_value(0x1);
            evt.set_othervalue(0x2);
            evt.set_yetanothervalue(false);
            writer->Write(evt);
        }

        return grpc::Status::OK;
    }

    grpc::ServerBuilder _builder{ grpc::ServerBuilder{} };
    std::unique_ptr<grpc::Server> _server{ nullptr };
};


int main(int /*argc*/, char** /*argv*/)
{
    auto const ServerAddress = std::string{ "[0.0.0.0:50051](http://0.0.0.0:50051/)" };

    auto service = Service{ ServerAddress };

    service.start();
    std::cout << "Server listening on " << ServerAddress << std::endl;

    std::this_thread::sleep_for(std::chrono::seconds(3000));

    service.stop();

    return 0;
}
```

**Client File**
```
#ifdef _WIN32
#    pragma warning(push)
#    pragma warning(disable : 4251) // Disable dll-class warning
#    pragma warning(disable : 4127) // Disable conditional expression is constant
#    pragma warning(disable : 4702) // Disable unreachable code
#endif
#include "service.grpc.pb.h"
#include <grpcpp/grpcpp.h>
#ifdef _WIN32
#    pragma warning(pop)
#endif

#include <iostream>
#include <string>

class Observer : public grpc::ClientReadReactor<myService::StreamEvent>
{
public:
    Observer(myService::MyService::Stub* stub) noexcept
        : _stub{ stub }
    {
        auto context = grpc::ClientContext{};
        auto request = myService::EmptyMessage{};
        _stub->async()->StartStream(&context, &request, this);
        StartRead(&_event); // Start reading (actually postponed until StartCall is called)
        StartCall();
    }

private:
    virtual void OnReadDone(bool ok) override
    {
        if (ok)
        {
            std::cout << "StreamEvent: " << std::to_string(_event.value()) << " - " << std::to_string(_event.othervalue()) << " - " << (_event.yetanothervalue() ? "True" : "False") << std::endl;

            // Read next event
            StartRead(&_event);
        }
    }

    myService::MyService::Stub* _stub{ nullptr };
    myService::StreamEvent _event{};
};

int main(int /*argc*/, char** /*argv*/)
{
    auto const ServerAddress = std::string{ "[127.0.0.1:50051](http://127.0.0.1:50051/)" };

    auto channel = grpc::CreateChannel(ServerAddress, grpc::InsecureChannelCredentials());
    auto stub = myService::MyService::NewStub(channel);

    try
    {
        auto observer = Observer{ stub.get() };

        for (auto i = 0; i < 10000; ++i)
        {
            auto context = grpc::ClientContext{};
            auto request = myService::EmptyMessage{};
            auto response = myService::PongResponse{};
            stub->Ping(&context, request, &response);
            std::cout << "Ping? " << (response.pong() ? "Yes" : "No") << std::endl;
        }
    }
    catch (std::exception const& e)
    {
        std::cout << "RPC Failed: " << e.what() << std::endl;
    }
    return 0;
}
```

### What did you expect to see?
Program running without crashing.

### What did you see instead?
When running this, I always get a crash in the client code.
The crash occurs when the server writes the StreamEvent (inside the StartStream method) in one thread at the same time as a PongResponse (when returning from the Ping method) in another thread. But the crash occurs in the client code, in the RunInterceptor method.

**Comment by markdroth** [comment]
Without seeing the actual crash you're running into (i.e., the stack trace), it's hard to say for sure what's going on here.  But from looking at your code, there seems to be a fairly clear bug in it.  In the client's `main()` function, you are starting a streaming call with the `observer` object, but you have no guarantee that `observer` won't go out of scope before that call is actually complete.

I think you need to add a `Wait()` method to the `Observer` class that waits until the stream is complete (as signalled by the reactor `OnDone()` method being called), and then change `main()` to call `observer.Wait()` before `observer` goes out of scope.

**Comment by christophe-calmejane** [comment]
This example is merely the minimal I came up with that exposes the same bug I've with a fully running program I cannot share. My full program doesn't go out of scope as it's still running and doing other stuff while waiting for server response. My complete code do has synchronization with OnDone, and waits for completion. The crash has the exact same call stack, but I'm modify the sample to clearly _wait_ for completion as well (the crash occurs before even getting out of scope).

**Comment by markdroth** [comment]
Can you share the actual crash you're seeing, with stack trace?  That might help us see what's going on here.

**Comment by christophe-calmejane** [comment]
I quickly added a 5 seconds sleep in ~Observer (I don't have the time now to import my full synchronization code) to show it's now going out of scope.

Here is the crash I have by just compiling and running the server and client files I provided.
![image](https://user-images.githubusercontent.com/23314088/198065425-82ff43a8-f3b3-4030-a54e-cf551e7c4a8b.png)

**Comment by markdroth** [comment]
Yash, this looks like it has something to do with the interceptor API.  Can you please take a look?  Thanks!

**Comment by yashykt** [comment]
Adding a 5 second sleep in ~Observer will not help. Your context object is declared on the stack in the Observer constructor, and it is going out of scope.

As per the documentation for `ClientContext` - 
```
/// \warning The ClientContext instance used for creating an rpc must remain
///          alive and valid for the lifetime of the rpc.
```

I suggest using an AddressSanitizer to detect such issues.

**Comment by christophe-calmejane** [comment]
Hi, thanks for the heads up, I confirm it does solve the issue.

Just a few remarks if it can help:
* asan didn't catch anything
* most of the async tutorials create the ClientContext on the stack (although it doesn't go out of scope, it is misleading)
* would be nice to have a small note in the tutorials about the way to correctly use the ClientContext as we have to guess how to use it (there is no direct link to the documentation of the ClientContext, contrary to other important classes)

Thanks for your time.
