### ISSUE TITLE
Remove dead Grpc.Tools MSBuild target

### ISSUE THREAD

**Issue by jzabroski** [grpc/grpc#31458]
The target `_Protobuf_Compile_BeforeCsCompile` is not [referenced anywhere](https://github.com/grpc/grpc/search?q=_Protobuf_Compile_BeforeCsCompile), and has a 5 year old todo from "kkm", and does _nothing_:

https://github.com/grpc/grpc/blame/ab3d62ae8fc024867b4db85122cebfab56532871/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L110-L116

**Comment by jtattermusch** [comment]
CC @tonydnewell

**Comment by jzabroski** [comment]
Also note it does not show up in GitHub VSCode web editor search as used anywhere (since sometimes github.com search can be misleading):

![image](https://user-images.githubusercontent.com/447485/198051386-96bea9f0-1e27-45ef-9091-54c089ee70ac.png)

**Comment by tonydnewell** [comment]
My only hesitance in removing it is that the target may referenced in some third-party project. Unlikely but unknown. It is not causing a problem being there.

**Comment by jzabroski** [comment]
They can fix it on their side. MSBuild validates the build file so if they depend on a target that does not exist, it will be self explanatory

**Comment by tonydnewell** [comment]
Looking at this again, this target is required.

Although it appears not to do anything, it is in fact the glue inserting the Grpc.Tools build targets into the build.  It is doing so by specifying the `BeforeTargets` and `DependsOnTargets`.

It is inserting `Protobuf_Compile` into the build before the normal MSBuild target `BeforeCompile` - but only doing so if this is a C# project.

@jtattermusch can you close this as not an issue.

**Comment by jzabroski** [comment]
Sorry about that. You are right.

I guess a PR to support F# and a clean up of the comments would be nice.
