### ISSUE TITLE
Add ability to stop generate annotation `@javax.annotation.Generated` or move to `@jakarta.annotation.Generated`

### ISSUE THREAD

**Issue by altro3** [grpc/grpc#31459]
I think it's time to switch to a modern library, because modern frameworks have switched to jakarta packages . Now we have to constantly include javax.annotation to compile the generated GRPC classes. It's not critical, of course, but it's clearly inconvenient.

**Comment by drfloob** [comment]
This is not the gRPC-java issue tracker, if that's what you're looking for. The gRPC-core repository doesn't rely on java annotations. Some of our third-party dependencies may, but those are not under our control.
