### ISSUE TITLE
CMake can't find c-ares in some projects

### ISSUE THREAD

**Issue by MohammadArik** [grpc/grpc#31477]
### What version of gRPC and what language are you using?
I am using latest grpc for C++

### What operating system (Linux, Windows,...) and version?
Linux- Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
c++

### What did you do?
I use cmake for my drogon app as that is default for that. It all worked fine but when I gRPC, the problem started. As both use c-ares.

First when I added gRPC. This showed up..
```
CMake Error at CMakeLists.txt:21 (add_executable):
  Target "auth-api" links to target "c-ares::cares" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

So I added `find_package(c-ares)` before linking gRPC. Now this comes up...
```
CMake Error at /usr/local/lib/cmake/Trantor/Findc-ares.cmake:14 (add_library):
  add_library cannot create imported target "c-ares_lib" because another
  target with the same name already exists.
Call Stack (most recent call first):
  CMakeLists.txt:51 (find_package)
```

I tried adding gRPC at the top. But then it says,
```
CMake Error at /usr/lib/cmake/c-ares/c-ares-config.cmake:29 (add_library):
  add_library cannot create imported target "c-ares::cares_static" because
  another target with the same name already exists.
Call Stack (most recent call first):
  /usr/local/lib/cmake/grpc/modules/Findc-ares.cmake:18 (find_package)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/Trantor/TrantorConfig.cmake:41 (find_dependency)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/Drogon/DrogonConfig.cmake:40 (find_dependency)
  CMakeLists.txt:33 (find_package)
```

### What did you expect to see?
It should have compiled successfully like in other projects

### What did you see instead?
Shown Above

**Comment by MohammadArik** [comment]
@veblush @markdroth any updates?

**Comment by yashykt** [comment]
It's not exactly clear what you are trying to do here. Can you provide a reproduction please?

**Comment by MohammadArik** [comment]
@yashykt My issue is fixed now. Thanks

**Comment by mpv945** [comment]
> @yashykt My issue is fixed now. Thanks


How did you solve it? I am also just looking for the problem of drogon integrating grpc

**Comment by kosmonaffft** [comment]
Same problem with Drogon and gRPC.

**Comment by GordonSmith** [comment]
I am hitting this as well on OSX 12 (GH Action) - suspect its related to cmake 3.29.1
