### ISSUE TITLE
client meta_data elements of type grpc::string_ref end without '\0'

### ISSUE THREAD

**Issue by Luke20000429** [grpc/grpc#31488]
### What version of gRPC and what language are you using?
cpp-grpc - 1.50.0 

### What operating system (Linux, Windows,...) and version?

Linux Ubuntu 18.04 - 4.15.0-193-generic

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### What did you do?

I try to extract an element from client metadata on server side in GlobalCallbacks.

Client code:
````
void XXXClient::download(int dataframe) {
    .... (initialize context, request, ....) 
    std::string api(__func__); 
    std::cout << "Call API: " << api << std::endl; 
    context.AddMetadata("api_name", api); 
    status = stub_->download(&context, request, &response);
    .... 
}
````

Server code:
````
void PreSynchronousRequest (grpc::ServerContext *context) { 
   auto &md = context->client_metadata();
   std::string client(context->peer());
   auto it = md.find("api_name");
   std::string api(it->second.data());
   std::cout << "Client[" << client << "] API call " << api << " len " << api.length() << " vs. " << it->second.length() << std::endl; 
   assert(it->second.data()[it->second.length()] == '\0');
}
````

### What did you expect to see?
The server should print correct api name and pass assertion.
To elaborate,
Server's output 
````
Client[ipv4:XXXX] API call download len 8 vs. 8
````

### What did you see instead?

````
Client[ipv4:XXXX] API call download�N len 13 vs. 8
server: XXX/includes/server.hpp:44: virtual void UploadCallback::PreSynchronousRequest(grpc::ServerContext*): Assertion `it->second.data()[it->second.length()] == '\0'' failed.
Aborted (core dumped)
````

### Anything else we should know about your project / environment?

This test is made on loopback port of a single machine.
The problem only appears when the string is long, as far as I know, 6 characters string works.
And right now I deal with the problem by resize the string

````
void PreSynchronousRequest (grpc::ServerContext *context) { 
   auto &md = context->client_metadata();
   std::string client(context->peer());
   auto it = md.find("api_name");
   std::string api(it->second.data());
   api.resize(it->second.length());
   std::cout << "Client[" << client << "] API call " << api << " len " << api.length() << " vs. " << it->second.length() << std::endl; 
}
````
The output is correct.

**Comment by eugeneo** [comment]
I am confirming that I have reproduced the issue and actively looking into it.
