### ISSUE TITLE
Consider having separate timeout for wait_for_ready independent of RPC timeout

### ISSUE THREAD

**Issue by rlubke** [grpc/grpc#31483]
### Is your feature request related to a problem? Please describe.
I have a long lived bidirectional stream that ideally should have no timeout.   However, similarly, I don't want an indefinite wait_for_ready either. 

### Describe the solution you'd like
Ideally a timeout that can be applied to the wait_for_ready functionality that is independent of the RPC timeout.

**Comment by gnossen** [comment]
@ejona86 @markdroth  Is this something that any other language has?

**Comment by markdroth** [comment]
No, this is not something we support in any language, and we have no plans to do so.  I don't think this is a common enough use case that it makes sense to support this as a first-class citizen in our API.

The application can't *exactly* do this itself, but it can do things that are probably close enough for what it actually cares about.  For example, if what the application really cares about is whether the server has seen the start of the stream, if it can ensure that the server sends initial metadata as soon as the stream starts, and then the client can set a timer when it starts the stream, and if it does not receive initial metadata from the server by the time the timer fires, then it can cancel the call.

**Comment by XuanWang-Amos** [comment]
As Mark mentioned, we'll create an example for this use case too.
