### ISSUE TITLE
Unable to apply gzip compression when using the 'grpc' Ruby gem

### ISSUE THREAD

**Issue by fallwith** [grpc/grpc#31497]
### What version of gRPC and what language are you using?
Ruby gem [grpc](https://rubygems.org/gems/grpc) v1.50.0.

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby v3.1.2p20

### What did you do?
**reproduction gist:** [https://gist.github.com/fallwith/b0971d024f0ed671655cc40967f0c850](https://gist.github.com/fallwith/b0971d024f0ed671655cc40967f0c850)

The gist referenced above is a standalone Ruby script that can be used to spawn a server and a client, have the client request the use of gzip compression, and then have a message sent from the client to the server and another message sent back from the server to the client. Through the use of a proxy or other means of debugging, neither of these messages is observed to contain any gzip compression.

The instructions for using that standalone Ruby script are in a comment at the top of the file, and are reproduced here:

- Make sure Ruby 2.6+ (Ruby 3.1 tested with the most) is available
- Download this script somewhere as `grpc_ruby_gzip_repro.rb`
- In one terminal/shell session, run:
    `ruby grpc_ruby_gzip_repro.rb server`
- In another terminal/shell session, run:
    `ruby grpc_ruby_gzip_repro.rb client`

The script has the client specify a desire for gzip compression at channel creation time, stub creation time, and call time. But compression does not appear to be taking place. The script will automatically bundle the latest stable `gzip` gem, but can be pointed at a local directory or custom commitish value instead if desired by modifying the `gemfile do` block at the top of the script as one would do with a `Gemfile` file.

### What did you expect to see?
The message payloads being sent by both the client and the server should be compressed, and a simple byte size check should reveal a smaller size with compression than without.

### What did you see instead?
Currently no matter what the settings are that we apply to request gzip compression from the client, no compression appears to be getting applied by either the client or the server. Manual inspection of the payloads reveal base64 encoded plaintext without any gzipping, and network transfer inspections reveal identical byte sizes regardless of whether gzip compression was specified or not. A 12,000 byte text blob is being used to be lengthy enough to show a compression benefit.

We've done a few things to debug, including running the client and server with these environment variables:

```shell
export GRPC_VERBOSITY=debug
export GRPC_TRACE=all
```

We've set an `http_proxy` environment variable that routes traffic through [http-dump](https://github.com/bradleyjkemp/grpc-tools).

From metadata and response header inspection, gzip compression appears to be permitted by the server, but we are unable to determine how to cause a payload to be compressed.

The repro script uses a channel arguments hash that sets gzip as the default algorithm and sets the default compression level to `:high`. We have experimented with setting the compression level to `:none`, `:low`, `:medium`, and leaving the arg out entirely. We have experimented with adding an additional third argument that specifies all non-gzip algorithms as disabled.

We have tested with unary communication (as demonstrated by the reproduction gist) and bidirectional communication.

### Anything else we should know about your project / environment?

We have attempted to scour blogs and other internet sites, past issues on this repo, mailing lists, and the unit tests to better understand how to request gzip compression from the client side. We've mostly found results for non-Ruby languages and seen references to manually introducing a "compressor" object on the client side. We haven't seen references to anything like a "compressor" on the Ruby side of things.

Once we figure out if there is a bug in our reproduction code, the `grpc` gem's Ruby code, or the gRPC source code, we'd be happy to contribute sample code and/or documentation to help others learn how to apply gzip compression with the `grpc` gem.

Thanks very much for your in reviewing this, and of course for maintaining the project in the first place.

**Comment by CaptainCplus** [comment]
Is It Ok If You Can Help Me Be Popular.

**Comment by NivedhaSenthil** [comment]
Hi @fallwith, The channel arg thats been set in the gist ` 'grpc.minimal_stack' => 1` is reseting the default of [`per_message_compression`](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#gab195665836ae27c45748f5c4e5dc4057) to no, please [refer](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga17b79aacf3bbfb0bce6d29bf9867988b). And hence the message was not getting compressed, I see the payload getting compressed after removing that arg.

**Comment by fallwith** [comment]
Thank you very much, @NivedhaSenthil. I will remove the `minimal_stack` setting and test again when I next get a chance. I really appreciate your help. If you have any recommendations for tools to use to view the payload to confirm compression, please let me know.

**Comment by NivedhaSenthil** [comment]
I used wireshark to view them.

**Comment by fallwith** [comment]
I have tested with the removal of the `'grpc.minimal_stack' => 1` channel setting and am able to confirm that I now see the expected bandwidth savings provided by gzip compression.

Thank you very much for your help, @NivedhaSenthil!

**Comment by Tette69** [comment]
Jason call me 562.668.8678
