### ISSUE TITLE
grpc: received message larger than max (9014796 vs. 4194304)

### ISSUE THREAD

**Issue by Amit011121** [grpc/grpc#31506]
Help me with this -
grpc: received message larger than max (9014796 vs. 4194304).

--
iOS swift: which property should i use to set the (X * 1024 * 1024) message size.

Thanks

**Comment by markdroth** [comment]
You can set the [`GRPC_ARG_MAX_RECEIVE_MESSAGE_LENGTH` channel arg](https://github.com/grpc/grpc/blob/b8108132915d4db9ed3c1b9ecd7d31bb794fe06b/include/grpc/impl/codegen/grpc_types.h#L153) to set this value.
