### ISSUE TITLE
grpc client ctrl+c terminate, lead to  memory leak on grpc async server

### ISSUE THREAD

**Issue by guoxiangzhou** [grpc/grpc#31515]
### What version of gRPC and what language are you using?
grpc 1.47.1/1.50.1, c++

### What operating system (Linux, Windows,...) and version?
Linux and Macos

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
![image](https://user-images.githubusercontent.com/52496626/199177338-211752f7-d4a1-46cf-b248-b88dad5de5bf.png)

### What did you expect to see?
- don't return a invalid tag, maybe can return the error code of client shutdown
- CallData object can be delete

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by eugeneo** [comment]
If I understand it correctly, the issue with the demo code is that assertion crashes the server before the object is disposed. Swapping lines 21 and 22 should fix it. Please let me know if this is actually a different issue. Please let me know what you are using to debug the code (Valgrind, ASAN).

**Comment by guoxiangzhou** [comment]
Swapping lines 21 and 22 of code won't fix it. 
As shown in the picture, the problem is: the object(address:0x55e834f2fc30) is never deleted.  In the current test, the client frequently sends GRPC requests and terminating them with Ctrl+C, which will cause the memory to continuously increase. When the client terminates via ctrl+c, the server receives an object(address:0x7fc14800a4c0), which is not a valid CallData object.
btw，I use gdb to debug the program.

**Comment by guoxiangzhou** [comment]
> If I understand it correctly, the issue with the demo code is that assertion crashes the server before the object is disposed. Swapping lines 21 and 22 should fix it. Please let me know if this is actually a different issue. Please let me know what you are using to debug the code (Valgrind, ASAN).

Swapping lines 21 and 22 of code won't fix it.
As shown in the picture, the problem is: the object(address:0x55e834f2fc30) is never deleted. In the current test, the client frequently sends GRPC requests and terminating them with Ctrl+C, which will cause the memory to continuously increase. When the client terminates via ctrl+c, the server receives an object(address:0x7fc14800a4c0), which is not a valid CallData object.
btw，I use gdb to debug the program.
