### ISSUE TITLE
Ansiblize gRPC

### ISSUE THREAD

**Issue by SuitespaceDev** [grpc/grpc#31526]
### Is your feature request related to a problem? Please describe.
Given that the following are all deeply inter-dependent and even sensitive to minor version compatibility:
- protobuff
- protoc
- gRPC
- gRPC language runtimes
- stub generators and
- testers 

Installation can be rather cumbersome and small mistakes can cause compilation/runtime errors which force debugging the installation itself.

### Describe the solution you'd like
Creating an Ansible role for Ansible Galaxy would allow the whole ecosystem to be easily deployed to Windows, Mac, Linux, BSD and others. Even just creating a repo so others can go to town making the role/tasks/playbook and having gRPC officially sign off on it when mature enough -- would be a huge help. imo this will greatly improve adoption.

### Describe alternatives you've considered
Containers are another option. Docker Compose for instance could have a prepacked deployment, then an installation could perhaps alias it with some fancy workarounds. 

Of course ideally we could all just use 
[system package manager] install grpc 

and expect all dependencies to be sorted like any other --  but I don't think that is on the table.

**Comment by drfloob** [comment]
This is out of scope for the project. There are quite a few distributions and packages that are maintained by external parties, and we don't support them. It partially comes down to our team's bandwidth to maintain these packages, and the platform expertise in a lot of these situations. Sometimes these packages go against our suggested guidelines - for example, even the testing the debian packages have aged out of our maintenance window, and we have little recourse to help people other than to say "please use a recent, officially-released package from Github".

Given that third-party maintainers come and go, and really have no obligation to continue supporting their projects/packages for the long-term, we can't sign off on your work as "officially supported" unless we expect to own the maintenance ourselves.

**Comment by SuitespaceDev** [comment]
This conclusion is erroneous. A wide variety of current, past and future issues are addressed by this recommendation. The medium-term and long-term reality is one of freeing up vast quantities of the team's bandwidth. 

Per scope; perhaps though that is quite a stretch. Ansible itself is out of scope, certainly. Targeting a particular technology vs another is a reasonable concern. However, with Ansible playbooks, or similar tools, you are only making best practices which _**will be implemented somewhere**_ anyway. 

> Sometimes these packages go against our suggested guidelines - for example, even the testing-release of gRPC packages on debian have aged out of our maintenance window, and we have little recourse to help people other than to say "please use a recent, officially-released package from Github".

That's a perfect sample. With this recommendation, you would indeed have a recourse to help such people and would no longer deal with such support requests. 

Once a role exists, maintenance is trivial even for much larger projects.
This is akin to saying that using a make system is out of scope for a project. 
It makes little sense to target go get, npm, pecl, etc and not support at least one deployment tool. The project is most certainly bleeding bandwidth due to the lack of official support.

Finally, given the aims and goals of gRPC; team bandwidth is further increased by simply making it more feasible for potential contributors to get up, running and have the exact same build & test environment. Likely the internal team's process would be similarly enhanced by even the most mediocre of Ansible roles.

An unfortunate result which I implore you to think on.

**Comment by SuitespaceDev** [comment]
Alternatively, come up with a more sane versioning strategy and build process.
