### ISSUE TITLE
Error reporting: invalid metadata

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc#3154]
When we accept invalid metadata from an application and pass it to the core, the core gives us an error. It would be helpful of us to scan over the metadata, determine what was invalid about it, and raise into the application an exception with informative detailed text about the metadata invalidity.

Similar to #3042, the way ruby addresses #3016

**Comment by jtattermusch** [comment]
Bumping to P1 as this is blocking our progress with setting up interop tests.

**Comment by murgatroid99** [comment]
This seems like it was fixed by #4634
