### ISSUE TITLE
About Unity Support

### ISSUE THREAD

**Issue by k-takeuchi220** [grpc/grpc#31566]
I am considering using grpc with Unity.
It seems that "grpc_unity_package.xxxx-xxxxxxx.zip" has not been created since the following build.
Will Unity be supported in the future?

https://packages.grpc.io/archive/2022/04/67538122780f8a081c774b66884289335c290cbe-f15a2c1c-582b-4c51-acf2-ab6d711d2c59/index.xml

**Comment by drfloob** [comment]
C# development was frozen a while ago, please see https://grpc.io/blog/grpc-csharp-future/ for details. I'll defer to @jtattermusch on plans to release any more packages within the maintenance window, but I expect any subsequent packages would be comprised of bug fixes.
