### ISSUE TITLE
Failed parsing HTTP/2 calling .net server from python client

### ISSUE THREAD

**Issue by KlemensE** [grpc/grpc#31589]
### What version of gRPC and what language are you using?
Python
grpcio==1.50.0
grpcio-tools==1.50.0
protobuf==4.21.9

.NET 7
GRPC.AspNetCore 2.49.0
Grpc.Net.Client 2.49.0
Grpc.Tools 2.50.0
Microsoft.AspNetCore.Grpc.JsonTranscoding 7.0.0

### What operating system (Linux, Windows,...) and version?
Windows 11 22H2 22621.674

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10.1-3.11.0 Client
.NET 7 Server and Client

### What did you do?

```webBuilder.UseKestrel(kestrelOptions =>
{
    kestrelOptions.ListenAnyIP(5000, listenOptions =>
    {
        listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1;
    });
    kestrelOptions.ListenAnyIP(5001, listenOptions =>
    {
        listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2;
    });
    kestrelOptions.ListenAnyIP(5002, listenOptions =>
    {
        listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2;
    });
});
```

I am running a .net server which uses GrpcJsonTranscoding. From the .net client it is possible to call gRPC functions on port 5001 and 5002. From the python client it is only possible to call gRPC functions on port 5001. The call on port 5002 fails with following error:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:5002: Failed parsing HTTP/2"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:5002: Failed parsing HTTP/2 {created_time:"2022-11-09T08:52:29.4119764+00:00", grpc_status:14}"
>
```

### What did you expect to see?

It should be possible to call gRPC functions on a server which uses multiple HTTP protocol versions.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

python client code

```
import grpc

from greet_pb2 import HelloRequest
from greet_pb2_grpc import GreeterStub

channel = grpc.insecure_channel('localhost:5002')
stub = GreeterStub(channel)
response = stub.SayHello(HelloRequest(name='you'))
print(type(response))
print("Greeter client received: " + response.message)
```

.net client
```
var services = new ServiceCollection();
services
    .AddGrpcClient<Greeter.GreeterClient>(o =>
    {
        o.Address = new Uri("http://localhost:5001");
    });

IServiceProvider serviceProvider = services.BuildServiceProvider();

var client = serviceProvider.GetRequiredService<Greeter.GreeterClient>();

{
    var reply = await client.SayHelloAsync(
                    new HelloRequest { Name = Guid.NewGuid().ToString() });
    Console.WriteLine("Greeting: " + reply.Message);
}

Console.ReadLine();
```
[trace.txt](https://github.com/grpc/grpc/files/9969762/trace.txt)

**Comment by gnossen** [comment]
```
I1109 11:03:22.821000000 29344 src/core/ext/filters/client_channel/subchannel.cc:910] subchannel 000002BB1C9803A0 {address=ipv4:127.0.0.1:5002, args={grpc.client_channel_factory=0x2bb1c5a10f0, grpc.default_authority=localhost:5002, grpc.internal.channel_credentials=0x2bb1c823bd0, grpc.internal.security_connector=0x2bb1e7194f0, grpc.internal.subchannel_pool=0x2bb1c851040, grpc.primary_user_agent=grpc-python/1.50.0, grpc.resource_quota=0x2bb1c59e600, grpc.server_uri=dns:///localhost:5002}}: connect failed (UNKNOWN:Failed parsing HTTP/2 {grpc_status:14, created_time:"2022-11-09T10:03:22.820903+00:00", children:[UNKNOWN:Expected SETTINGS frame as the first frame, got frame type 7 {created_time:"2022-11-09T10:03:22.8208946+00:00"}]}), backing off for 961 ms
```

This seems like it might be the underlying problem. @yashykt Can you please take a look?

**Comment by gnossen** [comment]
@yashykt Ping

**Comment by yashykt** [comment]
That's right. The HTTP2 parser expects a SETTINGS frame to be the first frame received, but we are receiving a Type 7 frame which is a GOAWAY. 
(I'm just commenting on the question in https://github.com/grpc/grpc/issues/31589#issuecomment-1331393956. It's not clear to me what the end issue here is. To me, it looks like the server just rejected the client connection.)

**Comment by gnossen** [comment]
@KlemensE Are you able to provide a packet capture?

**Comment by zanseb** [comment]
I tried to reproduce this issue and could observe the same behaviour. Attached you will find the capture files of the tests I conducted. The capture file `port_5001` (http2) contains the capturing of the successful test, capture file `port_5002` (Http1AndHttp2) contains the recording of the faulty case.

[capture-31589.zip](https://github.com/grpc/grpc/files/10457211/capture-31589.zip)

**Comment by ghoodPC** [comment]
Was this ever resolved? I am also experiencing the same issue on CentOS

**Comment by gnossen** [comment]
CC @jtattermusch for .NET expertise. 

Still hoping to get a packet capture from anyone who's affected by this.

**Comment by ghoodPC** [comment]
@gnossen My issue was that I was using insecure_channel() in my client but I hadn't set the endpoint defaults in the .NET server to "Http2". See the "Protocol Negotiation" section of the following article: https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio

I guess if you are not using TLS then you need to specify that the endpoint is Http2 only otherwise all calls to the unsecured endpoint will default to Http 1.0 and the gRPC request fails.

**Comment by zanseb** [comment]
@gnossen is my packet capture not sufficient? Do you need something else?

**Comment by gnossen** [comment]
Sorry for the delay @zanseb. Based on your packet capture, @yashykt 's analysis is correct. The client received a GOAWAY. I think @ghoodPC 's explanation is likely correct. Please let us know if this does not resolve your issue.
