### ISSUE TITLE
Debian package build currently disables tests

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc#3159]
From #662

> FYI, I had to build with tests disabled because chttp2_socket_pair_with_grpc_trace_invoke_large_request_test kept failing. I'm not sure if the Debian autobuilders build with tests enabled or not, but this failing test will be a problem if they do and it fails there.

As of last week, this was still an issue, as @andrewpollock can confirm 

 Tagging it with Beta as there will be some lag after we cut the beta branch before we build the package, so hopefully we can get this fixed in time to build the beta debian package.

**Comment by jtattermusch** [comment]
Still an issue?
