### ISSUE TITLE
python: interop server image not build correctly

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#31644]
As seen at https://source.cloud.google.com/results/invocations/d9401d96-b2cb-4587-a171-81965b544af1 (grpc_interop_tocloud):

```
2022-11-14 18:27:08,029 invalid command name 'py39/bin/python'

2022-11-14 18:27:08,029 FAILED: interop_server_pythonasyncio [ret=1, pid=75143, time=362.5sec]
Server "pythonasyncio" has exited prematurely.
```

**Comment by gnossen** [comment]
@XuanWang-Amos This seems like it should be relatively simple and is probably a good way to get acquainted with the interop test framework. Would you mind taking a look?

**Comment by XuanWang-Amos** [comment]
Able to reproduce using this command:
`tools/run_tests/run_interop_tests.py -l python -s pythonasyncio --use_docker --http2_interop --internal_ci -t -j 8`

Looks like some issue with our docker set up.
