### ISSUE TITLE
Add support for associating completion queues with event FDs

### ISSUE THREAD

**Issue by va7ish** [grpc/grpc#31696]
### Is your feature request related to a problem? Please describe.
Currently gRPC threading model is such that asynchronous handling of gRPC events/work requires dedicated worker threads. Works/events are delivered using completion queues. Such completion queues only support polling (deadline timeout <= now) or waiting ; i.e. with a deadline greater than zero (future). A single worker thread can't handle other non-gRPC events or multiple completion queues.  

### Describe the solution you'd like
It would be very beneficial to support associating completion queues with event FDs. This would make the queue pollable by an event loop and would make it possible to use an event loop wrapper like [asio](https://think-async.com/Asio/boost_asio_1_24_0/doc/html/boost_asio.html) or [libevent](https://libevent.org). This will unleash application developers to build their own logic around thread pools and provide greater flexibility with regards to event handling by to worker threads.   

### Describe alternatives you've considered
Not aware of any other alternative options.

**Comment by veblush** [comment]
I added AJ here because it sounds like this is going to be resolved once we have an EventEngine API landed. AJ, would you share your thought on this issue?

**Comment by drfloob** [comment]
Thanks @veblush .

@va7ish we are preparing a public API that will give users the ability to control all aspects of polling, event handling, and thread management. It's called the [EventEngine](https://github.com/grpc/proposal/blob/ef3750466557545445714173ef07df5cdd4cf06a/L82-core-event-engine.md). Our team is hard at work writing the initial default implementations for all platforms, and integrating EventEngine API uses into the core library: about 20% of all timer execution uses the EventEngine today (no polling yet). We have plans next year to open the APIs which will allow users to provide their own engines per-channel and per-server.

The EventEngine API is still under active development (i.e., breaking changes are happening to the API without public notice as we find issues), but if you'd like to experiment with integrations, you can use [SetEventEngineFactory](https://github.com/grpc/grpc/blob/e69592d29ccc9c29bc1cd8d18882b0f5751ea4da/include/grpc/event_engine/event_engine.h#L428-L438) today.

**Comment by va7ish** [comment]
Thank you @veblush and @drfloob. The EventEngine approach looks very promising!
