### ISSUE TITLE
Add support for queuing arbitrary tags to completion queues 

### ISSUE THREAD

**Issue by va7ish** [grpc/grpc#31695]
### Is your feature request related to a problem? Please describe.
gRPC library threading model assumes that asynchronous handling of events and gRPC related work is handled through completion queues requiring dedicated application threads to process such events. Such worker threads also sometimes need to receive other notifications that are not generated by the gRPC traffic. The only mechanisms provided for the worker threads is through the use of Next() or AsyncNext() functions. It is not currently possible through the native APIs to inject any custom events to the worker threads through the completion queues.  

### Describe the solution you'd like
Provide a native API to queue arbitrary tags into the completion queue. 

### Describe alternatives you've considered
Currently the only workable workaround for injecting arbitrary events into the worker threads is through the use of immediately-firing gRPC alarms.

**Comment by drfloob** [comment]
This sounds very closely related to the issue you posted in #31696, and it will also be solved by the EventEngine project, which gives the application full ability to control threading and polling behaviors. This is a valid request, and I'm glad you're interested! Closing as a duplicate.
