### ISSUE TITLE
Hi, which python version should we install exactly? Can you post a link for that version?

### ISSUE THREAD

**Issue by Japan50079** [grpc/grpc#31715]
Hi, which python version should we install exactly? Can you post a link for that version?

__最初由 @Recklessxq 在 https://github.com/KSCHdsc/BlackCap-Grabber/issues/20 发布__

**Comment by gnossen** [comment]
Our supported CPython version range is 3.7 through 3.11, inclusive. The current supported range is available [on our pypi page.](https://pypi.org/project/grpcio)
