### ISSUE TITLE
TryCancel crashes with segment fault

### ISSUE THREAD

**Issue by springile** [grpc/grpc#31729]
### What version of gRPC and what language are you using?
1.47

### What operating system (Linux, Windows,...) and version?
CewntOS 7.9

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc7.3

### What did you do?

TEST(ServerContextTest, TryCancelTest) {
grpc::ServerContext mock_context;

mock_context.TryCancel();    
}

### What did you expect to see?
it should run normally.

### What did you see instead?

Segment fault

![image](https://user-images.githubusercontent.com/50204931/203158150-15a567aa-44f8-4e7d-848c-162fba72e4d8.png)

**Comment by springile** [comment]
As answered last time, 

![image](https://user-images.githubusercontent.com/50204931/203158326-434fc966-f815-4a45-833b-4762068bef0d.png)

**Comment by springile** [comment]
What should be called before TryCancel is called ?

Thanks.

**Comment by yashykt** [comment]
@springile You need to actually perform an RPC. https://grpc.io/docs/languages/cpp/quickstart/ might be a good resource to look at on how to perform an RPC.
