### ISSUE TITLE
Crash in grpc_core::ConnectivityStateTracker::RemoveWatcher

### ISSUE THREAD

**Issue by soumik0108** [grpc/grpc#31750]
### What version of gRPC and what language are you using?

1.39

### What operating system (Linux, Windows,...) and version?

BSD 12
### What runtime / compiler are you using (e.g. python version or version of gcc)

CLANG 10/llvm 10
### What did you do?
Connection flapping.

### What did you expect to see?
No Core/segmentation fault.

### What did you see instead?

Core/ segmentation fault

Backtrace:
 #0  std::__1::__tree<std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::__1::__map_value_compare<grpc_core::ConnectivityStateWatcherInterface*, std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::__1::less<grpc_core::ConnectivityStateWatcherInterface*>, true>, std::__1::allocator<std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::__root (this=<optimized out>) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/__tree:1085
 #1  std::__1::__tree<std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::__1::__map_value_compare<grpc_core::ConnectivityStateWatcherInterface*, std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::__1::less<grpc_core::ConnectivityStateWatcherInterface*>, true>, std::__1::allocator<std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::find<grpc_core::ConnectivityStateWatcherInterface*> (this=<optimized out>, __v=<optimized out>) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/__tree:2566
 #2  std::__1::__tree<std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::__1::__map_value_compare<grpc_core::ConnectivityStateWatcherInterface*, std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::__1::less<grpc_core::ConnectivityStateWatcherInterface*>, true>, std::__1::allocator<std::__1::__value_type<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::__erase_unique<grpc_core::ConnectivityStateWatcherInterface*> (this=<optimized out>, __k=<optimized out>) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/__tree:2542
 #3  std::__1::map<grpc_core::ConnectivityStateWatcherInterface*, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete>, std::__1::less<grpc_core::ConnectivityStateWatcherInterface*>, std::__1::allocator<std::__1::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::__1::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::erase (this=0x88, __k=<optimized out>) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/map:1304
 #4  grpc_core::ConnectivityStateTracker::RemoveWatcher (this=0x7c, watcher=<optimized out>) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/transport/connectivity_state.cc:147
 #5  0x01826ec3 in grpc_core::ClientChannel::ExternalConnectivityWatcher::RemoveWatcherLocked (this=0x1a2d4e0 <grpc_core::grpc_connectivity_state_trace>) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/ext/filters/client_channel/client_channel.cc:860
 #6  grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1::operator()() const (this=0x3c529cc) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/ext/filters/client_channel/client_channel.cc:831
 #7  std::__1::__invoke<grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1&>(grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1&) (__f=...) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/type_traits:3539
 #8  std::__1::__invoke_void_return_wrapper<void>::__call<grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1&>(grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1&) (__args=...) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/__functional_base:348
 #9  std::__1::__function::__alloc_func<grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1, std::__1::allocator<grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1>, void ()>::operator()() (this=0x3c529cc) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/functional:1540
 #10 std::__1::__function::__func<grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1, std::__1::allocator<grpc_core::ClientChannel::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_20210324::Status const&)::$_1>, void ()>::operator()() (this=0x3c529c8) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/functional:1714
 #11 0x0196f65f in std::__1::__function::__value_func<void ()>::operator()() const (this=0x3c529c8) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/functional:1867
 #12 std::__1::function<void ()>::operator()() const (this=0x3c529c8) at /volume/publish/dev/occam/llvm-10.0/sysroot/stable_12/20210907.jwlemke.247f38f32dc.20210907-freebsd.1/i386-unknown-freebsd12.0/usr/include/c++/v1/functional:2473
 #13 grpc_core::WorkSerializer::WorkSerializerImpl::DrainQueue (this=0x36ce500) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/work_serializer.cc:138
 #14 0x0196f3f1 in grpc_core::WorkSerializer::WorkSerializerImpl::Run(std::__1::function<void ()>, grpc_core::DebugLocation const&) (this=0x36ce500, callback=..., location=...) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/work_serializer.cc:69
 #15 0x0196f8e0 in grpc_core::WorkSerializer::Run(std::__1::function<void ()>, grpc_core::DebugLocation const&) (this=0x39fe05c, callback=..., location=...) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/work_serializer.cc:152
 #16 0x01827d57 in grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange (this=0x39ff600) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/ext/filters/client_channel/client_channel.cc:634
 #17 0x0192be1c in grpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_core::Subchannel*, grpc_connectivity_state, absl::lts_20210324::Status const&)::{lambda(void*, grpc_error*)#1}::operator()(void*, grpc_error*) const (this=<optimized out>, arg=0x3c516c0) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/ext/filters/client_channel/subchannel.cc:376
 #18 grpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_core::Subchannel*, grpc_connectivity_state, absl::lts_20210324::Status const&)::{lambda(void*, grpc_error*)#1}::__invoke(void*, grpc_error*) (arg=0x3c516c0) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/ext/filters/client_channel/subchannel.cc:376
 #19 0x0199f3b2 in exec_ctx_run (closure=0x1a2d4e0 <grpc_core::grpc_connectivity_state_trace>, error=0x0) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/exec_ctx.cc:43
 #20 grpc_core::ExecCtx::Flush (this=0x2990e68) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/exec_ctx.cc:165
 #21 0x01996d7e in pollset_work (pollset=0x2479440, worker_hdl=0x0, deadline=<optimized out>) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/ev_poll_posix.cc:1125
 #22 0x019954c5 in pollset_work (pollset=0x2479440, worker=0x0, deadline=9223372036854775807) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/ev_posix.cc:324
 #23 0x019a2947 in grpc_pollset_work (pollset=0x2479440, worker=0x0, deadline=9223372036854775807) at src___core___lib___iomgr___pollset.cc:56
 #24 0x018852ae in cq_next (cq=0x24793c0, deadline=..., reserved=0x0) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/surface/completion_queue.cc:1056
 #25 0x0188460e in grpc_completion_queue_next (cq=0x24793c0, deadline=..., reserved=0x0) at ../../../../../../../../src/external/apache2/grpc/dist/src/core/lib/surface/completion_queue.cc:1135
 #26 0x011a5395 in ConnectivityManager::Listen (this=0x21cc000) at ../../../../../../../src/junos/lib/libjsd/infra/ConnectivityManager.cc:354
 #27 0x0069f65e in jsd_daemon_conn_check_accept_worker (pvoid=<optimized out>) at ../../../../../../../src/junos/usr.sbin/jsd/server/Server.cc:17
 #28 0x01f233a2 in thread_start (curthread=0x2155f00) at /.amd/svl-engdata5vs2/occamdev/build/freebsd/stable_12/sandbox-stable-12-202211041206/freebsd/stable_12/20221104.180217__ci_fbsd_builder_stable_12.40b9faf/src/lib/libthr/thread/thr_create.c:292
 #29 0x00000000 in ?? ()
 Backtrace of all threads:

**Comment by veblush** [comment]
Thank you for the issue but would you try the latest version and provide a small repro if possible?
