### ISSUE TITLE
Tutorial for callback api in c++

### ISSUE THREAD

**Issue by elkanatovey** [grpc/grpc#31764]
I noticed that there is a tutorial for the sync api and the cq based async api but none for the callback api as described in the proposal here: https://github.com/grpc/proposal/blob/master/L67-cpp-callback-api.md. As a matter of fact it's existence isn't even mentioned as one of the existing api's  here https://grpc.io/docs/languages/cpp/.

I think that a tutorial for the callback api would be very useful, right now just reading the async-api tutorial one wouldn't know it exists.

**Comment by corbin-phipps** [comment]
Any update on this? A tutorial for the callback API in C++ would be very helpful for me as I'm running into issues and there is very limited documentation.

**Comment by eugeneo** [comment]
Please reference [greeter_callback_client.cc](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_callback_client.cc) for an example of callback-based gRPC service client or [greeter_callback_server.cc](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_callback_server.cc)

**Comment by elkanatovey** [comment]
What about a tutorial for the streaming callback api?

**Comment by eugeneo** [comment]
[route_guide_callback_client.cc](https://github.com/grpc/grpc/blob/master/examples/cpp/route_guide/route_guide_callback_client.cc) and [route_guide_callback_server.cc](https://github.com/grpc/grpc/blob/master/examples/cpp/route_guide/route_guide_callback_server.cc) showcase streaming callback API.

**Comment by jeannotlanglois** [comment]
@eugeneo :  The CMakeLists.txt does not reference route_guide_callback_client.cc and route_guide_callback_server.cc, therefore they are not currently being built by the example - is there an example of how to build both callback-API-based source files?

**Comment by eugeneo** [comment]
@jeannotlanglois I added it - https://github.com/grpc/grpc/pull/37369 - might take some time till I merge it and for it to make it into releases, if you're relying on packages. Feel free to manually apply to your local copy.
