### ISSUE TITLE
`PLATFORM.architecture` method returns wrong value when macOS is `Ventura`.

### ISSUE THREAD

**Issue by y-okamoto-1113** [grpc/grpc#31782]
I am not familiar with grpc and apologize if my answers to your questions are incorrect. 🙇 

### What version of gRPC and what language are you using?
- version: 1.50.0
- language: ruby(2.6.0)

### What operating system (Linux, Windows,...) and version?
- OS: MacOS Ventura (13.0.1)

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby(2.6.0),  grpc-tools (1.50.0)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
1. Use M1 macbook.
2. Update MacOS to Ventura(13.0.1)
3. run `PLATFORM.architecture`.
4. `PLATFORM.architecture` returns `x86`, not `x86_64`.
Because `RbConfig::CONFIG['host_cpu']` returns `aarch64`, not `arm`.

### What did you expect to see?
I expect that `PLATFORM.architecture` returns `x86_64`, not `x86`.

### What did you see instead?
I saw that `PLATFORM.architecture` returns `x86`, not `x86_64`.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by xiy** [comment]
I just encountered a build error that I think is related to this:
- macOS Ventura
- grpc v1.51.0


```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [grpc_c.bundle] Error 1
```

Luckily seems to be fixed by using v1.52.0.pre2.
