### ISSUE TITLE
Support gRPC via the Stream API in JS

### ISSUE THREAD

**Issue by 0xAlcibiades** [grpc/grpc#31798]
With some 90+% of browsers supporting the streams API now, it'd be nice to add native support for gRPC so that it can be used fully in browser applications.

**Comment by wenbozhu** [comment]
grpc-web supports fetch/streams (which is limited to download only).  Please check the roadmap doc on github.com/grpc/grpc-web

**Comment by Japan50079** [comment]
Сб, 3 дек. 2022 г. в 15:42, Alcibiades ***@***.***>:

**Comment by 0xAlcibiades** [comment]
> grpc-web supports fetch/streams (which is limited to download only). Please check the roadmap doc on github.com/grpc/grpc-web

My point is that we could probably implement the full gRPC protocol with the streams api and deprecate grpc-web entirely. Unless I'm missing something @wenbozhu.
