### ISSUE TITLE
installing gpcrio - calculate_macosx_platform_tag doesn't parse 'base_version' correctly

### ISSUE THREAD

**Issue by jasonhudgins** [grpc/grpc#31800]
### What version of gRPC and what language are you using?
1.51.1

### What operating system (Linux, Windows,...) and version?
Mac 12.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.15

### What did you do?
pip install grpcio

### What did you expect to see?
should install correctly

### What did you see instead?
    File "lib/python3.8/site-packages/wheel/macosx_libfile.py", line 360, in calculate_macosx_platform_tag
      assert len(base_version) == 2
      AssertionError
      ----------------------------------------
      ERROR: Failed building wheel for grpcio

This is happening because distutils.utils.get_platform is returning:
   macosx-12-x86_64 instead of macosx-12.6-x86_64 and the parsing code expects to see an 12.6 for the version and not 12, so the assert fails

**Comment by XuanWang-Amos** [comment]
Hi, can you provide more logs for this error?

**Comment by jasonhudgins** [comment]
The problem is, distutils is reporting my mac's version as macosx-12-x86_64, the code in calculate_macosx_platform_tag splits this string on the '-'' and grabs the middle segment '12', and then splits it again on '.' because it's expecting something in the format of X.X, but in this case, there is nothing to split.  There is an assert check that expects -exactly- 2 values here (a major and a minor version number), and it fails, so the install breaks.

My ugly workaround was just to hardcode it to 12.6 to get the install to pass.

**Comment by XuanWang-Amos** [comment]
Are you building `grpc` from source with an M1 Mac? If so this PR (https://github.com/grpc/grpc/pull/31747) will be helpful.

And also `distutils` is vendored by `setuptools`, can you try again with newer version of `setuptools`?
