### ISSUE TITLE
Life of grpc_op values

### ISSUE THREAD

**Issue by kolmodin** [grpc/grpc#3182]
I'd like to get a little bit more clear documentation on who owns the values in `grpc_op`, where it's not already stated.

`recv_initial_metadata`, for example, states that the caller owns the array, while the ownership of the elements stays with the `call` object. Great.

What about `grpc_byte_buffer *   send_message`? It looks like `grpc_call_start_batch` does not call `grpc_byte_buffer_copy`. Is the caller responsible for also calling `grpc_byte_buffer_destroy`, or does the call object take over ownership and will destroy the byte_buffer once the grpc_op has been completed?

Same question goes for most other fields in that struct.
If the caller still owns the values, when is it safe to destroy them? Is it safe directly after calling `grpc_call_start_batch`, or only after the op has finished and the completion_queue has been notified?

**Comment by ctiller** [comment]
Come talk to me about this if needed Sree, but I thought it might be a good place to solidify some understanding of the high level C API.

**Comment by kolmodin** [comment]
The reason I'm asking is because I'm writing a language binding for Haskell.
I could figure out the answers myself by reading the C code, trying what works and what (maybe) crashes, looking at other language bindings, but it'd be so much easier if it was documented.

Huge thanks for looking into this!
