### ISSUE TITLE
gRPC channel cannot be shutdown after calling ShutdownAsync() when the service side is closed/unreachable

### ISSUE THREAD

**Issue by jiankong-microsoft** [grpc/grpc#31828]
### What version of gRPC and what language are you using?
GRPC.core 2.42.0,  C#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET 4.7.2

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

The GRPC service is not enabled from the server side (device).  Then we try to create client via the channel (we didn't implement any Timeout / Retry for ChannelOption)

                client = new gNMI.gNMIClient(channel);
                clientCall = client.Subscribe(GetAuthMetadata(), null, cancellationToken); 

Due to the remote server is not reachable, so there is RPC exception thrown.  
Next step, we capture this exception, and try to shutdown the channel by calling:

               await channel.ShutdownAsync();

However, we can see the channel state is with "Connecting" instead of "Shutdown". 

### What did you expect to see?
We expect the channel can be shutdown completely when we call the "channel.ShutdownAsync();", and no more TCP session request sent out. 

### What did you see instead?
we can see the channel state is with "Connecting" instead of "Shutdown", and the client still resend TCP session to the server side. 

### Anything else we should know about your project / environment?
Right now our workaround is to call the "ConnectAsync" explicitly before create the gnmi client. It will throw "TaskCancellationException" and the channel state is "Shutdown". 

            int timeoutSeconds = 2;
            channel.ConnectAsync(DateTime.UtcNow.AddSeconds(timeoutSeconds)).Wait();

**Comment by tonydnewell** [comment]
@jiankong-microsoft Are you able to provide a gRPC trace from the client side?
See [TROUBLESHOOTING](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) and [environment_variables.md](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)

**Comment by jtattermusch** [comment]
We don't have enough info to actually debug this (e.g. see https://github.com/grpc/grpc/issues/31828#issuecomment-1348761724), so I'm going to close this as "not actionable".
