### ISSUE TITLE
ahost.c.obj : error LNK2019: unresolved external symbol win32_select referenced in function main

### ISSUE THREAD

**Issue by jiangjianshan** [grpc/grpc#31847]
### What version of gRPC and what language are you using?
v1.51.1

### What operating system (Linux, Windows,...) and version?
Windows 10 22H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual C++ Build Tools 2022 17.4.2

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
[buld-grpc-failed.txt](https://github.com/grpc/grpc/files/10191563/buld-grpc-failed.txt)
[build-grpc.bat.txt](https://github.com/grpc/grpc/files/10191564/build-grpc.bat.txt)
    I have use build-grpc.bat trying to compile grpc on Windows 10. If want to reproduce it, please change build-grpc.bat.txt to build-grpc.bat and run it on Windows.

### What did you expect to see?
   The correct result should be the compilation process can be passed.

### What did you see instead?
  I have got the unresolved external symbol issue which the whole build trace is in build-grpc-failed.txt.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by drfloob** [comment]
I'm not a windows build expert, but it looks like all the missing symbols should be in the linked ws2_32 library. Can your environment build anything (hello world) that uses `htonl` or `setsockopt`? I suggest trying to rule out an incomplete MSVC installation of some sort.

Have you tried with other versions of Visual Studio?

**Comment by jiangjianshan** [comment]
@drfloob , I don't have another version of Visual C++ Build Tools. But I can sucessful to build c-ares which version 1.18.1 from https://github.com/c-ares/c-ares. but the version using at grpc responsibility is older. Could you update the link of third party of c-cares to newest version?

**Comment by drfloob** [comment]
That is odd indeed. We have multiple Windows artifacts built continuously using our distribution tests. I'm still guessing this is related to your particular build environment. Have you tried building gRPC using one of the officially recommended methods? https://github.com/grpc/grpc/blob/master/BUILDING.md. If you want to provide a different version of ares (via a system-installed version), you can pass `-DgRPC_CARES_PROVIDER=package` to the cmake build.

**Comment by jiangjianshan** [comment]
@drfloob , thanks for you suggestion. The build script build-grpc.bat at 1st comment I have used are following the recommended method from https://github.com/grpc/grpc/blob/master/BUILDING.md but only missing to use '-DgRPC_CARES_PROVIDER=package'.  After I add this cmake option to my original script build-grpc.bat. Finally the build was sucessful. Thanks you very much.
