### ISSUE TITLE
gRPC server not able to handle special characters in ASCII set in the password string without escape character ('\') and quotes

### ISSUE THREAD

**Issue by ashu-ciena** [grpc/grpc#31840]
**What version of gRPC and what language are you using?**
grpc 1.22, C++

What operating system (Linux, Windows,...) and version?
Linux 5168 5.10.147-oneos-standard https://github.com/grpc/grpc/pull/1 SMP PREEMPT Mon Nov 21 04:26:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**What runtime / compiler are you using (e.g. python version or version of gcc)**
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)

**What did you do?**
Using a Go based gnmi client gnmi_cli, trying to subscribe to a Path to a C++ based grpc/gnmi server using a username/password string which contains special characters (one or more) from the ASCII character set.  
The password which goes in HTTP2 header is going with the original string without escape character before each special character in the password string.

We call the client_metadata() API to get the metadata from the grpc packet then search for "password" string in metadata to get the password in string format. 

**What did you expect to see?**

**I expected this to work as it was working in GRPC version 1.14 and before**. I upgraded last year to 1.22 and after deployment, a customer reported their passwords do not work anymore while doing gnmi subscription. The customer is using a CLI based tool to subscribe. The CLI command is running on a bash shell. 

**What did you see instead?**
The tcpdump taken for the HTTP2 packet just before GRPC consume the data, shows the string passed from the CLI tool is intact and reached safely to the GRPC server but the gnmi application running on top of the GRPC server receives it truncated at the location of the special character. 
If we escape the special character with a backward slash ('\') then the string password seems to be reach the gnmi application properly without truncation. But this change in behavior of GRPC has broken the field deployed gNMI solution by our customer and they expect a quick solution to this issue. 

I have attached the pcap files of the HTTP2 packet what reaches to GRPC in release 1.14 and 1.22  just to ensure that the CLIs and infra are not at fault in truncation. Both the strings with and without escape character reaches the GRPC server safely but GRPC server is only able to handle the one which has escape character before each special character in the string.
 We want to know which change has broken this and want a patch solution to unblock our customers.

**Anything else we should know about your project / environment?**
Go based gnmi_cli used as client to send subscription request - https://github.com/openconfig/gnmi/blob/master/cmd/gnmi_cli/gnmi_cli.go

1) **Using  “ < “ character as part of the password string along with backslash “ / ” character for bash to accept.**

Password string : abc\<123 passed as command line argument to gnmi cli. **The string is without quotes.**

GRPC logs: 
[hpack_parser.cc:650] Decode: 'password: abc<123', elem_interned=0 [2], k_interned=1, v_interned=0
[parsing.cc:414] HTTP:1:HDR:SVR: password: 61 62 63 3c 31 32 33 'abc<123'

Tcpdump:
 
![abclessthan123 pcap](https://user-images.githubusercontent.com/100347291/206415252-76939665-e280-47f5-9fb1-7825fa37001e.png)

We can see the bash perhaps parsed it correctly and sent it to gRPC as "abc<123" but after reaching to GRPC,  what application got after calling to metadata API is just "abc" and rest is truncated.

In the earlier version of the gRPC 1.14 , we did not face this issue and got the string as is from the metadata API. So something was changed between 1.14 and 1.22 which caused this regression at our customer end.

 2) 1) **Using  “ < “ character as part of the password string along with backslash “ / ” character for bash to accept** and enclosed in quoted string. 

Password string : "abc\<123" passed as command line argument to gnmi cli. **The string is with quotes.**

Tcpdump:
![abclessthan123InQuotes pcap](https://user-images.githubusercontent.com/100347291/206417573-b29b628a-4a61-43d2-bc1b-fd41fc29b044.png)

GRPC-LOG:

[hpack_parser.cc:650] Decode: 'password: abc\<123', elem_interned=0 [2], k_interned=1, v_interned=0
[parsing.cc:414] HTTP:1:HDR:SVR: password: 61 62 63 5c 3c 31 32 33 'abc\<123'

This worked in GRPC 1.22 server.  But the customer do not accept this solution and want to know why this behavior was changed.  The last I checked with GRPC 1.38 version and the behavior resembles with 1.22.

**Comment by ashu-ciena** [comment]
Hello @yashykt ,
This is a bit urgent for us to know what change made this break the gRPC 1.14 behavior. We have customers waiting for a fix and a solid reasoning for this change of behavior.  Appreciate, if you can look into this on priority.

**Comment by ashu-ciena** [comment]
https://github.com/grpc/grpc/labels/priority%2FP1

**Comment by yashykt** [comment]
Sorry for the delay, December is a weird time.

Firstly, I'll note that 1.14 and 1.22 are very old versions. I would highly recommend using one of the more recent versions. There have been a bunch of fixes that go in to our releases and we only backport any important fixes to some of the recent branches.

Secondly, I performed a quick experiment on head where I modified one of our tests to send "password" "abc<123" as the metadata and it was received successfully.

**Comment by yashykt** [comment]
Thirdly, I'm only speaking from gRPC C++'s perspective. I'm not familiar with how gnmi is interacting with grpc here.

If I'm missing something, please provide a reproduction (using just gRPC) which shows the bug and I'd be able to help further.

**Comment by ashu-ciena** [comment]
Thanks @yashykt for the response.  The problem persists on build 1.42.0 as well.  The head is I think 1.51.x.  Do you remember any check-in addressing this issue?

Is your test able to simulate the request where the grpc server receives a packet from a client with HTTP2 header which has user credential information with "abc<123" in password value field, followed by a read of metadata which retrieves the string successfully?

**Comment by ctiller** [comment]
Drive by: this looks to be a go issue, not a C++ one from the report?

**Comment by ctiller** [comment]
Sorry I was mistaken.

**Comment by yashykt** [comment]
> Is your test able to simulate the request where the grpc server receives a packet from a client with HTTP2 header which has user credential information with "abc<123" in password value field, followed by a read of metadata which retrieves the string successfully?

Yes, have a look at https://github.com/yashykt/grpc/tree/31840Proof

**Comment by yashykt** [comment]
> Thanks @yashykt for the response. The problem persists on build 1.38.0 as well. The head is I think 1.51.x. Do you remember any check-in addressing this issue?

I'm not yet sure if this was ever an issue, since I haven't been able to reproduce it. If you can prove the fault with just gRPC C++ without any other dependencies, I'd be grateful.

**Comment by ashu-ciena** [comment]
Hello @yashykt ,
You are right, this was not a gRPC issue.  The password got truncated just after it left the gRPC layer. We never print the password, so we missed to notice that gRPC passed the string transparently and it only got truncated next. 

**Learning from this issue:**
The linux system() API is normally passed a command string to execute. If the command string has any special characters like a $ or > or < character, then the subsequent word/character starts getting evaluated.

In case of $ as a shell variable, gets a redirect output meaning after encountering ">" character and  input meaning after encountering "<" character and the string gets truncated.
So, for passing these characters to string for system(), one needs to add escape character "\" in front of each special character, then the string is preserved.

Closing this issue. Thanks Yash for your time.
