### ISSUE TITLE
gRPC gem can't be built on aarch64 system

### ISSUE THREAD

**Issue by Danissss** [grpc/grpc#31855]
### What version of gRPC and what language are you using?
gPRC gem version: 1.48.0 and 1.50.0
Ruby version: 2.7.5

### What operating system (Linux, Windows,...) and version?
```
uname -a
Linux docker.ao.ubuntu 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
```

### What did you do?
1) create docker container from `arm64v8/ubuntu:20.04`
2) run `gem install grpc`

### What did you see instead?

```
gem install grpc -v '1.48.0' # 1.50.0 has the same error
...
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/root/.rbenv/versions/2.7.5/bin/$(RUBY_BASE_NAME)
```

**Comment by opt-liang** [comment]
1. Use the ARM version server of Alibaba Cloud service or Google Cloud service to compile.

**Comment by opt-liang** [comment]
root@iZwz9f60gpe469e2sv2bumZ:/tmp# uname -a
Linux iZwz9f60gpe469e2sv2bumZ 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:47:36 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by alto-ruby** [comment]
Most likely you are missing some dependencies.
Can you provide the `mkmf.log`?

Or you can try [build from source](https://github.com/grpc/grpc/tree/master/src/ruby#build-from-source) and upload the build logs
