### ISSUE TITLE
[Unity] Cannot receive any grpc messages after using the grpc server for a long time in unity

### ISSUE THREAD

**Issue by ssccinng** [grpc/grpc#31876]
### What version of gRPC and what language are you using?

2.47.0 unity
### What operating system (Linux, Windows,...) and version?

windows
### What runtime / compiler are you using (e.g. python version or version of gcc)
unity 2021.3.4f1c1 

### What did you do?
Unity acts as a grpc server and communicates with clients for a long time. Then, the connection succeeds but no message can be sent. The port is still occupied and the server cannot be shut down. Even if you listen on the new port again, you still cannot receive messages.

### What did you expect to see?
Normal listen or restart

### What did you see instead?
cannot receive messages.

### Anything else we should know about your project / environment?

There will be frequent sending and receiving of information

**Comment by ssccinng** [comment]
> It is not clear whether you are trying to use Grpc.Core or grpc-dotnet with Unity.
> 
> For Grpc.Core, the Unity support is only experimental ([see here](https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental)) and as now C# support for Grpc.Core is only in [maintenance ](https://grpc.io/blog/grpc-csharp-future/)no further work will be done to support Unity.
> 
> For grpc-dotnet - see this discussion: [grpc/grpc-dotnet#1309](https://github.com/grpc/grpc-dotnet/issues/1309)

Grpc.Core

**Comment by ssccinng** [comment]
> It is not clear whether you are trying to use Grpc.Core or grpc-dotnet with Unity.
> 
> For Grpc.Core, the Unity support is only experimental ([see here](https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental)) and as now C# support for Grpc.Core is only in [maintenance ](https://grpc.io/blog/grpc-csharp-future/)no further work will be done to support Unity.
> 
> For grpc-dotnet - see this discussion: [grpc/grpc-dotnet#1309](https://github.com/grpc/grpc-dotnet/issues/1309)

Thank you! i will try

**Comment by ssccinng** [comment]
> It is not clear whether you are trying to use Grpc.Core or grpc-dotnet with Unity.
> 
> For Grpc.Core, the Unity support is only experimental ([see here](https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental)) and as now C# support for Grpc.Core is only in [maintenance ](https://grpc.io/blog/grpc-csharp-future/)no further work will be done to support Unity.
> 
> For grpc-dotnet - see this discussion: [grpc/grpc-dotnet#1309](https://github.com/grpc/grpc-dotnet/issues/1309)

Is there a way to let grpc dotnet serve as the server in unity? I haven't succeeded and haven't found the tutorial

**Comment by tonydnewell** [comment]
For grpc-dotnet questions please ask in https://github.com/grpc/grpc-dotnet

Questions asked here are for report gRPC bugs not for general gRPC advice. For general questions about gRPC and Unity you could try asking in stackoverflow: https://stackoverflow.com/search?q=grpc+unity

As I said gRPC support for Unity is experimental and we don't have the resources to investigate and fix issues, and also Grpc.Core support of C# is in maintenance mode and we will fix critical bugs.
