### ISSUE TITLE
Add information about error to grpc_event when processing batch fails

### ISSUE THREAD

**Issue by bgaifullin** [grpc/grpc#31884]
### Is your feature request related to a problem? Please describe.
I am using `grpc_call_start_batch` and `grpc_completion_queue_next` to communicate with server.
In case if batch operation fail before sending to server, for example because the size of request body is greater than limit, there is no way to get 
this error in caller code (except enable tracing).
The grpc_event contains only flag, was operation successful or not.

### Describe the solution you'd like
It will be very helpful if there was option to get actual error instead of boolean flag in grpc_event, like a pointer to error, that user should clean by itself, or via callback where user should take ownership for the error.

At least just the grpc_status instead of bool flag succes will be more useful.

### Additional context
Add any other context about the feature request here.

**Comment by bgaifullin** [comment]
@yashykt, what do you think, the plan for adding error_status and error_description to grpc_event is ok?
I can prepare patch if there is no objections.

**Comment by yashykt** [comment]
Sorry, the Core API was not designed for public consumption. A lot of this stuff might go away in the future and we wouldn't folks depending on it.

**Comment by bgaifullin** [comment]
OK. 
Is there any way to get an error on using Core API ?
