### ISSUE TITLE
Windows 10 C++ grpc build output no grpc.lib

### ISSUE THREAD

**Issue by 155cannon** [grpc/grpc#31887]
cmake .. -G "Visual Studio 17 2022"
cmake --build . --config Release

release folder just has 4 libs :
address_sorting.lib 
gpr.lib 
grpc_plugin_support.lib 
upb.lib.  

No other lib files are generated.

What's wrong?

**Comment by 155cannon** [comment]
![捕获](https://user-images.githubusercontent.com/13818422/207507695-fac39c9a-f6f6-4ea0-8e43-6ded4f00c8de.JPG)

**Comment by oneengineer** [comment]
@155cannon 
I meet the same problem. How did you solve it
