### ISSUE TITLE
grpc interface performance

### ISSUE THREAD

**Issue by yc1037642433** [grpc/grpc#31907]
I test grpc stream with four situation：   
1. grpc sync stream   
2. grpc callback async stream  
3. grpc async stream with comletion queue  
4. boost socket

Every situation loop 10000 times, and each loop with 2 write or read; Test run with 127.0.0.1
I get result as follow:
1. 392ms
2. 1328ms
3. 372ms
4. 55ms

In test 3, I also test mutil stream which server stream use different ComletionQueue and use same ServerComletionQueue, the time it used increase to 926ms; (In my test function test_grpc_direct_async2(), use two thread to run test_grpc_direct_async2_mutil)

This is my test file, grpc_test.txt is the main test; grpc_chatter implement the grpc callback async stream;
[grpc_chatter.txt](https://github.com/grpc/grpc/files/10242202/grpc_chatter.txt)
[grpc_test.txt](https://github.com/grpc/grpc/files/10242204/grpc_test.txt)

**Comment by yashykt** [comment]
It's not clear what the motive of the issue here is. Please create a new issue with details on the issue.
