### ISSUE TITLE
CronetFramework build with arm64

### ISSUE THREAD

**Issue by HannahShiSFB** [grpc/grpc#31929]
### Problem
On Mac, we use [CronetFramework](https://cocoapods.org/pods/CronetFramework) if opt to use chrome network stack. It is a pre-built library with only x86 (32 and 64 bit) support, so it fails on M1 mac with:

```
file Cronet
Cronet: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386]
Cronet (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Cronet (for architecture i386):	Mach-O dynamically linked shared library i386
```

### Solution

Add arm64 to the pre-built `Cronet` binary.
@yulin-liang can you help on this since you [created version 0.0.5](https://github.com/CocoaPods/Specs/commit/144a0bac44ba9ffd122a337046c0699fc48316a5)?

### Alternative

Besides the arm64 binary of Cronet, we also use PodToBUILD as we are moving our build test flow from CocoaPods to Bazel. It also only provides x86_64 release, I have created issue https://github.com/pinterest/PodToBUILD/issues/230 but no response yet.

So do we know how many users actually using cronet? 
What's the benefit compare to the default or CFStream implementation?
Can we drop the support of cronet on Mac and iOS at least?

**Comment by HannahShiSFB** [comment]
Cronet on iOS is officially deprecated. need to find a work round.

**Comment by oleg-komaristov-mobiline** [comment]
> Cronet on iOS is officially deprecated. need to find a work around.
> 
> @sampajano

Hi.
Any news regarding the workaround?

**Comment by oleg-komaristov-mobiline** [comment]
@sampajano Hi.

Thank you for the update. We are looking forward to the new solution (using cronet for the QUIC support).

**Comment by HannahShiSFB** [comment]
Cronet will be deprecated after #37756
