### ISSUE TITLE
grpcio package for Python  crashes at runtime on import on Apple M1 - incompatible architecture 

### ISSUE THREAD

**Issue by dmfigol** [grpc/grpc#31931]
### What version of gRPC and what language are you using?
grpcio 1.51.1

### What operating system (Linux, Windows,...) and version?
macOS 12.6.1 M1

### What runtime / compiler are you using (e.g. python version or version of gcc)
3.7.16

### What did you do?
```
pip install grpcio
python
>>> import grpc
```

### What did you expect to see?
no crash on import

### What did you see instead?

```
>>> import grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./.venv/lib/python3.7/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "./.venv/lib/python3.7/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(//.venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-darwin.so, 0x0002): tried: '.venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

### Anything else we should know about your project / environment?
During the search I also stumbled upon #27506, but it seems to be resolved and also related to 3.10.
One or two weeks ago or so I installed grpc for the same python version and it was working fine.
I also tried `pip install --no-binary :all: grpcio --ignore-installed` as was suggested in the linked issue, but it didn't help.
I'd greatly appreciate any workaround, as it is blocking my development at the moment.

**Comment by gnossen** [comment]
```
ImportError: dlopen(/Users/dmfigol/projects/customers/technicolor/tcs-clearsky/.venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-darwin.so, 0x0002): tried: '/Users/dmfigol/projects/customers/technicolor/tcs-clearsky/.venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

This error indicates that you're running an artifact incompatible for your platform, which `pip` should have refused to install. Can you please include the exact command you used to install along with the full logs from the installation? My expectation  is that (at the present moment) pip would detect no published arm64 wheels and fall back to a from-source build.

> I also tried `pip install --no-binary :all: grpcio --ignore-installed` as was suggested in the linked issue, but it didn't help. 

This is a separate issue and likely indicates that your build environment is not fully set up. To diagnose this, I'd need to have the full logs from your build attempt.

Regardless, a simple `pip install grpcio` should work for M1 with the next release (1.52). For the moment, you can get the M1-compatible artifacts from our nightly builds at packages.grpc.io. For example, [here's a 3.7 universal2 wheel](https://packages.grpc.io/archive/2022/12/4d4fed1ef7784bfb919184e7ccb1487d69e5465c-7c2c3880-f29e-4387-b2f1-316274c6e2b3/python/grpcio/grpcio-1.52.0.dev0-cp37-cp37m-macosx_10_10_universal2.whl).

**Comment by dmfigol** [comment]
Thanks! Yeah, I've understood the nature of the problem was the incompatible architecture of that cython library with my processor arch, but I couldn't track how it appeared in the first place (e.g. why would pip install something incompatible). The problem was appearing even on a new virtual environment right after using `pip install grpcio` on python3.7. After spending hours yesterday, I wasn't able to find out the root cause.  
`pip install --no-binary :all: grpcio --ignore-installed` would build from source successfully, but on import it would still crash.  
What helped is `pip cache purge`. Then I installed the latest grpcio package with pip and it was working fine.
As of now I am not able to reproduce the issue. Because of this I think it makes sense to close this issue.
