### ISSUE TITLE
C# extension debian package lintian warnings

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3199]
#3121 added a deb package for C# native extension.

After building the package, I get these lintian warnings:

W: libgrpc0-cil: package-name-doesnt-match-sonames libgrpc-csharp-ext0

The problem is I can't really change the libgrpc_csharp_ext name at this point (C# code depends on it nontrivially). Would renaming the package to libgrpc_csharp_ext be an option?

W: libgrpc0-cil: non-dev-pkg-with-shlib-symlink usr/lib/libgrpc_csharp_ext.so.0.10.1.0 usr/lib/libgrpc_csharp_ext.s

I think the symlink is needed for C# to pickup the shared library. 

Will these warnings preventing us from publishing the package?

**Comment by andrewpollock** [comment]
Thanks for bringing this to my attention. I'm not sure how I overlooked the Lintian warnings. 

I'll send a PR to address the symlink being in the wrong package. The naming of the package, I'm going to have to take some guidance on from Debian folks who actually know something about packaging Mono-related stuff.

**Comment by jtattermusch** [comment]
Btw, I believe the next release is going to be version 0.11.0-1, so we might need to update the changelog.

**Comment by andrewpollock** [comment]
> Btw, I believe the next release is going to be version 0.11.0-1, so we might need to update the changelog.

the debian/sid branch is a snapshot of main, so I think we'll be okay to release what's there. Or I can refresh the debian/sid branch to 0.11.0-1 and release that.

I'm in #debian-cli on OFTC if you want to hang out in there to find out answers about SONAMEs vs package names.

**Comment by jtattermusch** [comment]
We are no longer distributing the C# extension as a debian package (the precompiled native binaries are now bundled with the nuget package).
