### ISSUE TITLE
iomgr doesn't properly recover from ENOBUFS

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#320]
The logic in iomgr's on_writable in tcp_client_posix.c doesn't properly recover from the ENOBUFS error, where it should schedule a retry, and rearm the deadline alarm.

**Comment by jtattermusch** [comment]
still an issue?

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.

**Comment by vjpai** [comment]
This is a theoretical issue, but it has not been seen in the wild. We'll call it a P3 and then see if anyone wants to pick it up.

**Comment by ncteisen** [comment]
My vote would be to close this theoretical issue, and then re investigate if it actually rears its head one day
