### ISSUE TITLE
Compile error: Linking CXX executable gen_hpack_tables undefined reference to `SSL_CTX_free'...

### ISSUE THREAD

**Issue by fandy-fan** [grpc/grpc#32002]
### What version of gRPC and what language are you using?
grpc-1.49.2

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-200-generic x86_64)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
g++ (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

openssl version, try
openssl-1.1.1g/ openssl-1.1.1s/openssl-3.1.0

mkdir -p build
cd build
cmake .. -DgRPC_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
make

then error. see below the log.

### What did you expect to see?
compile ok

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

$ ls -l /usr/local/lib/libssh.so*
lrwxrwxrwx 1 root root     11 Nov 26 16:22 /usr/local/lib/libssh.so -> libssh.so.4
lrwxrwxrwx 1 root root     15 Nov 26 16:22 /usr/local/lib/libssh.so.4 -> libssh.so.4.9.4
-rw-r--r-- 1 root root 639728 Nov 26 16:21 /usr/local/lib/libssh.so.4.9.4

Compile error log:
[ 89%] Linking CXX executable gen_hpack_tables
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_free'
libgrpc.so.27.0.0: undefined reference to `X509_NAME_get_index_by_NID'
libgrpc.so.27.0.0: undefined reference to `EC_KEY_free'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_up_ref'
libgrpc.so.27.0.0: undefined reference to `HMAC_Final'
libgrpc.so.27.0.0: undefined reference to `BIO_ctrl'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_keylog_callback'
libgrpc.so.27.0.0: undefined reference to `EVP_PKEY_cmp'
libgrpc.so.27.0.0: undefined reference to `EVP_CIPHER_CTX_new'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_get_cert_store'
libgrpc.so.27.0.0: undefined reference to `EVP_DigestVerifyInit'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_get_ex_data'
libgrpc.so.27.0.0: undefined reference to `BIO_puts'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_check_private_key'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_use_PrivateKey'
libgrpc.so.27.0.0: undefined reference to `RSA_set0_key'
libgrpc.so.27.0.0: undefined reference to `SSL_get0_next_proto_negotiated'
libgrpc.so.27.0.0: undefined reference to `SSL_get_error'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_sk_pop_free'
libgrpc.so.27.0.0: undefined reference to `ERR_print_errors'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_sk_value'
libgrpc.so.27.0.0: undefined reference to `EVP_PKEY_set1_RSA'
libgrpc.so.27.0.0: undefined reference to `ENGINE_init'
libgrpc.so.27.0.0: undefined reference to `SSL_state_string_long'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_ex_data'
libgrpc.so.27.0.0: undefined reference to `ASN1_STRING_to_UTF8'
libgrpc.so.27.0.0: undefined reference to `EVP_DecryptInit_ex'
libgrpc.so.27.0.0: undefined reference to `RSA_free'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_sk_new_null'
libgrpc.so.27.0.0: undefined reference to `SSL_SESSION_free'
libgrpc.so.27.0.0: undefined reference to `SSL_get_servername'
libgrpc.so.27.0.0: undefined reference to `SSL_state_string'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_sess_set_new_cb'
libgrpc.so.27.0.0: undefined reference to `BIO_free'
libgrpc.so.27.0.0: undefined reference to `SHA256_Final'
libgrpc.so.27.0.0: undefined reference to `EVP_DecryptFinal_ex'
libgrpc.so.27.0.0: undefined reference to `EVP_aes_256_gcm'
libgrpc.so.27.0.0: undefined reference to `SSL_set_SSL_CTX'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_load_locations'
libgrpc.so.27.0.0: undefined reference to `EVP_PKEY_free'
libgrpc.so.27.0.0: undefined reference to `X509_get_ext_d2i'
libgrpc.so.27.0.0: undefined reference to `d2i_SSL_SESSION'
libgrpc.so.27.0.0: undefined reference to `EVP_sha384'
libgrpc.so.27.0.0: undefined reference to `SSL_get0_alpn_selected'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_cipher_list'
libgrpc.so.27.0.0: undefined reference to `X509_get_subject_name'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_alpn_select_cb'
libgrpc.so.27.0.0: undefined reference to `X509_free'
libgrpc.so.27.0.0: undefined reference to `PEM_read_bio_PrivateKey'
libgrpc.so.27.0.0: undefined reference to `PEM_read_bio_X509'
libgrpc.so.27.0.0: undefined reference to `SHA256_Update'
libgrpc.so.27.0.0: undefined reference to `X509_NAME_free'
libgrpc.so.27.0.0: undefined reference to `EVP_CIPHER_CTX_ctrl'
libgrpc.so.27.0.0: undefined reference to `BIO_write'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_use_certificate'
libgrpc.so.27.0.0: undefined reference to `ERR_error_string_n'
libgrpc.so.27.0.0: undefined reference to `CRYPTO_free'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_sk_push'
libgrpc.so.27.0.0: undefined reference to `EVP_MD_CTX_new'
libgrpc.so.27.0.0: undefined reference to `BIO_new_bio_pair'
libgrpc.so.27.0.0: undefined reference to `SSL_set_bio'
libgrpc.so.27.0.0: undefined reference to `EVP_DecryptUpdate'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_cert_store'
libgrpc.so.27.0.0: undefined reference to `SSL_get_SSL_CTX'
libgrpc.so.27.0.0: undefined reference to `BN_bin2bn'
libgrpc.so.27.0.0: undefined reference to `SHA256_Init'
libgrpc.so.27.0.0: undefined reference to `PEM_read_bio_RSAPrivateKey'
libgrpc.so.27.0.0: undefined reference to `SSL_read'
libgrpc.so.27.0.0: undefined reference to `i2d_SSL_SESSION'
libgrpc.so.27.0.0: undefined reference to `X509_NAME_dup'
libgrpc.so.27.0.0: undefined reference to `X509_NAME_get_entry'
libgrpc.so.27.0.0: undefined reference to `X509_NAME_ENTRY_get_data'
libgrpc.so.27.0.0: undefined reference to `HMAC_CTX_free'
libgrpc.so.27.0.0: undefined reference to `PEM_write_bio_X509'
libgrpc.so.27.0.0: undefined reference to `ENGINE_ctrl_cmd_string'
libgrpc.so.27.0.0: undefined reference to `EVP_CIPHER_CTX_free'
libgrpc.so.27.0.0: undefined reference to `RSA_new'
libgrpc.so.27.0.0: undefined reference to `EVP_PKEY_new'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_session_id_context'
libgrpc.so.27.0.0: undefined reference to `SSL_ctrl'
libgrpc.so.27.0.0: undefined reference to `EVP_EncryptUpdate'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_sk_num'
libgrpc.so.27.0.0: undefined reference to `EVP_DigestVerifyFinal'
libgrpc.so.27.0.0: undefined reference to `SSL_is_init_finished'
libgrpc.so.27.0.0: undefined reference to `BIO_free_all'
libgrpc.so.27.0.0: undefined reference to `BIO_test_flags'
libgrpc.so.27.0.0: undefined reference to `EVP_DigestSignUpdate'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_init_ssl'
libgrpc.so.27.0.0: undefined reference to `BIO_s_mem'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_verify'
libgrpc.so.27.0.0: undefined reference to `ENGINE_free'
libgrpc.so.27.0.0: undefined reference to `SSL_get_peer_cert_chain'
libgrpc.so.27.0.0: undefined reference to `OPENSSL_init_crypto'
libgrpc.so.27.0.0: undefined reference to `BIO_read'
libgrpc.so.27.0.0: undefined reference to `HMAC'
libgrpc.so.27.0.0: undefined reference to `EVP_DigestSignFinal'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_set_flags'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_client_CA_list'
libgrpc.so.27.0.0: undefined reference to `SSL_set_session'
libgrpc.so.27.0.0: undefined reference to `EVP_DigestSignInit'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_new'
libgrpc.so.27.0.0: undefined reference to `HMAC_Update'
libgrpc.so.27.0.0: undefined reference to `TLS_method'
libgrpc.so.27.0.0: undefined reference to `HMAC_Init_ex'
libgrpc.so.27.0.0: undefined reference to `EVP_DigestVerifyUpdate'
libgrpc.so.27.0.0: undefined reference to `BIO_new'
libgrpc.so.27.0.0: undefined reference to `CRYPTO_get_ex_new_index'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_free'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_set_verify_cb'
libgrpc.so.27.0.0: undefined reference to `EVP_MD_CTX_free'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_alpn_protos'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_new'
libgrpc.so.27.0.0: undefined reference to `EVP_EncryptInit_ex'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_options'
libgrpc.so.27.0.0: undefined reference to `EVP_sha256'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_next_proto_select_cb'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_CTX_get_error'
libgrpc.so.27.0.0: undefined reference to `PEM_read_bio_X509_AUX'
libgrpc.so.27.0.0: undefined reference to `SSL_set_connect_state'
libgrpc.so.27.0.0: undefined reference to `EVP_aes_128_gcm'
libgrpc.so.27.0.0: undefined reference to `EVP_EncryptFinal_ex'
libgrpc.so.27.0.0: undefined reference to `ERR_clear_error'
libgrpc.so.27.0.0: undefined reference to `SSL_get1_peer_certificate'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_callback_ctrl'
libgrpc.so.27.0.0: undefined reference to `SSL_free'
libgrpc.so.27.0.0: undefined reference to `HMAC_CTX_new'
libgrpc.so.27.0.0: undefined reference to `ENGINE_by_id'
libgrpc.so.27.0.0: undefined reference to `SSL_write'
libgrpc.so.27.0.0: undefined reference to `X509_VERIFY_PARAM_set_flags'
libgrpc.so.27.0.0: undefined reference to `EVP_sha512'
libgrpc.so.27.0.0: undefined reference to `BIO_new_mem_buf'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_add_cert'
libgrpc.so.27.0.0: undefined reference to `X509_STORE_get0_param'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_ctrl'
libgrpc.so.27.0.0: undefined reference to `X509_NAME_print_ex'
libgrpc.so.27.0.0: undefined reference to `BN_free'
libgrpc.so.27.0.0: undefined reference to `GENERAL_NAME_free'
libgrpc.so.27.0.0: undefined reference to `SSL_set_accept_state'
libgrpc.so.27.0.0: undefined reference to `ERR_get_error'
libgrpc.so.27.0.0: undefined reference to `SSL_get_rbio'
libgrpc.so.27.0.0: undefined reference to `EC_KEY_new_by_curve_name'
libgrpc.so.27.0.0: undefined reference to `SSL_session_reused'
libgrpc.so.27.0.0: undefined reference to `ENGINE_set_default'
libgrpc.so.27.0.0: undefined reference to `SSL_new'
libgrpc.so.27.0.0: undefined reference to `ENGINE_load_private_key'
libgrpc.so.27.0.0: undefined reference to `SSL_do_handshake'
libgrpc.so.27.0.0: undefined reference to `SSL_CTX_set_next_protos_advertised_cb'
libgrpc.so.27.0.0: undefined reference to `X509_get_pubkey'
libgrpc.so.27.0.0: undefined reference to `SSL_set_info_callback'
collect2: error: ld returned 1 exit status
CMakeFiles/gen_hpack_tables.dir/build.make:149: recipe for target 'gen_hpack_tables' failed
make[2]: *** [gen_hpack_tables] Error 1
CMakeFiles/Makefile2:1781: recipe for target 'CMakeFiles/gen_hpack_tables.dir/all' failed
make[1]: *** [CMakeFiles/gen_hpack_tables.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment]
I don't get enough information from the description but I guess that you might use a different version for compiling gRPC and linking gRPC. It should use the same one otherwise it will get this kind of linker error.

If you can give us an exact list of commands you used when seeing this problem, it'd be helpful to investigate this.
