### ISSUE TITLE
Weighted round robin in xDS mode

### ISSUE THREAD

**Issue by zhm9484** [grpc/grpc#32004]
### Is your feature request related to a problem? Please describe.

With Envoy, weighted round robin could be done by setting `load_balancing_weight` in `lb_endpoints`. 

However, the gRPC xDS feature is ignoring this field. -- https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md#clusterloadassignment-proto

### Describe the solution you'd like

Support wrr by setting `load_balancing_weight` in `lb_endpoints`.

**Comment by markdroth** [comment]
We've discussed this feature before.  We don't currently have any plans to implement this, but there is a pending proposal from an OSS contributor to provide this functionality in https://github.com/grpc/proposal/pull/202.  It doesn't look like there's been much activity on that proposal for a while, but if you want to contribute, feel free to get involved in the discussion in that PR.

**Comment by zhm9484** [comment]
Thanks for reply! I will check on that proposal.
