### ISSUE TITLE
Add environment variables supported by Grpc.Tools to documentation

### ISSUE THREAD

**Issue by jameswoodley** [grpc/grpc#32006]
I am using a Macbook Pro M1, and the Grpc.Tools don't seem to support this, with the tooling going into the macos_x64 folder, and causing issues stating the CPU is invalid.

After many hours of digging, I found that the protoc and plugin location can be customised using environment variables, which then allowed me to install grpc via Homebrew, which works against ARM64 architectures.

The environment vars are (for my specific installation):
export PROTOBUF_PROTOC=/opt/homebrew/bin/protoc
export GRPC_PROTOC_PLUGIN=/opt/homebrew/bin/grpc_csharp_plugin

Which now creates successful builds. Could we add this to the documentation, or README files somewhere to save others the searching I went through?

**Comment by jtattermusch** [comment]
@tonydnewell  looks like the PROTOBUF_PROTOC and GRPC_PROTOC_PLUGIN env variables are mentioned in https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/implementation_notes.md#protobuf-compiler-and-c-grpc-plugin-binaries (the docs for contibutors), but they aren't mentioned anywhere in https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md (which is the user-facing documentation).
Seems like this is worth fixing?

I also wouldn't mind simplifying the existing BUILD-INTEGRATION.md a bit (the current version is quite chatty IMHO).

**Comment by jtattermusch** [comment]
So based on the original report, it seems that https://github.com/grpc/grpc/pull/26080 doesn't really work? (it does use x64 version of the binary, but that binary doesn't work or ARM64 macs)?
@jameswoodley do you have the Rosetta 2 emulator enabled? (it should handle x64 binaries running on M1 macs automatically).

**Comment by jameswoodley** [comment]
Hi [jtattermusch](https://github.com/jtattermusch) I can confirm Rosetta 2 is installed, in my instance it didn't seem to make a difference. I received messages stating that the CPU was incorrect

**Comment by jtattermusch** [comment]
> Hi [jtattermusch](https://github.com/jtattermusch) I can confirm Rosetta 2 is installed, in my instance it didn't seem to make a difference. I received messages stating that the CPU was incorrect

Can you copypaste / screenshot the exact message you got?

**Comment by jameswoodley** [comment]
> > Hi [jtattermusch](https://github.com/jtattermusch) I can confirm Rosetta 2 is installed, in my instance it didn't seem to make a difference. I received messages stating that the CPU was incorrect
> 
> Can you copypaste / screenshot the exact message you got?

So strangely, it does now seem to be working, and the path seems to be using the file from the macosx_x64. All I did here was remove my environment variables, so not sure whether something needed resetting in Rosetta 2, which has happened over the weeks naturally from rebooting etc, or if a new nuget package has made a difference?

Either way, I guess we could say the issue at hand is resolved here, but there's no reason to not include a pointer in the documentation to the environment variables as a way of using a different version of protoc perhaps?

**Comment by jtattermusch** [comment]
As mentioned [here](https://github.com/grpc/grpc/issues/32006#issuecomment-1369698808) - yes, let's improve the documentation.

**Comment by jtattermusch** [comment]
> > > Hi [jtattermusch](https://github.com/jtattermusch) I can confirm Rosetta 2 is installed, in my instance it didn't seem to make a difference. I received messages stating that the CPU was incorrect
> > 
> > 
> > Can you copypaste / screenshot the exact message you got?
> 
> So strangely, it does now seem to be working, and the path seems to be using the file from the macosx_x64. All I did here was remove my environment variables, so not sure whether something needed resetting in Rosetta 2, which has happened over the weeks naturally from rebooting etc, or if a new nuget package has made a difference?
> 
> Either way, I guess we could say the issue at hand is resolved here, but there's no reason to not include a pointer in the documentation to the environment variables as a way of using a different version of protoc perhaps?

Thanks for confirming that the current solution works.

**Comment by tonydnewell** [comment]
I could just add the missing information but I agree the documentation needs improving - so I'm currently reviewing and rewriting the documentation.

**Comment by tonydnewell** [comment]
PR for rewriting the docs here: https://github.com/grpc/grpc/pull/32075

**Comment by tonydnewell** [comment]
Documentation changes have now been merged to master.
@jtattermusch this issue can now be closed
