### ISSUE TITLE
Grpc.Tools: support for java_multiple_files for csharp

### ISSUE THREAD

**Issue by Jeevananthan-23** [grpc/grpc#32024]
`Java` has the `option java_multiple_files = true; ` for support to generate a separate Java file for each message. It could be great if we get the same in `dotnet` as well.

**Comment by Jeevananthan-23** [comment]
@jtattermusch sorry for the delayed reply. So the main moto of opening this issue we are totaly port project from the `Java` to `C#`. Client lib totaly responsible for handling the Marshall the protofile and @JamesNK Thanks for adding the JSONtranscoder feature we are utilising it. This lib only generates the a single class file for each protofile and it leads to more nested  in top-level message. i.e Greetbase.Greeter.Hello.HelloRequest to make this simple calling only the HelloRequest could be great. But how `Java` utilising `option java_multiple_files = true;` by adding only single package name to call the `import gRPC.Client.HelloRequest` but in `c#` `using grpc.client.Greetbase.Greeter.Hello.HelloRequest;`


*Maybe this could help you to make this change or correct me if i'm wrong.*

Thanks!

**Comment by jtattermusch** [comment]
While I appreciate that in Java you found an option that happens to add some convenience to your specific workflow, I don't think this is a good enough reason to outweigh the high implementation and maintenance cost your request would incur.
TBH I also don't see how needing to include one extra part (the top level class name) in your using clauses could cause problems in your workflow. FWIW, the using clauses will have similar structure as the "package" declarations in your .proto files - so if you have long multi-part package names in your .proto files, don't be surprised that the C# namespace name as also going to be long and heavily nested.

Btw, the `using grpc.client.Greetbase.Greeter.Hello.HelloRequest;` example seems odd - I don't know how you would end up with something like that other than "grpc.client.Greetbase.Greeter" being your package name in .proto (which is something that you control).
