### ISSUE TITLE
Write hangs forever

### ISSUE THREAD

**Issue by madi-nuralin** [grpc/grpc#32032]
### What version of gRPC and what language are you using?
gRPC v1.41.0, C++

### What operating system (Linux, Windows,...) and version?
Cent OS 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 11.2

### What did you do?
I established a client-server synchronous connection. Below I provided a code snippet that writess approximately ~10K requests.
```cpp
void SyncEncState2(){
    try{
        ClientContext context;
        context.AddMetadata("id", std::to_string(curid));
        std::shared_ptr<ClientReaderWriter<ClusterApi::EncData, ClusterApi::EncData> > stream(
                stub_->SyncEncState(&context));
        // ..
        for (it->SeekToFirst(); it->Valid(); it->Next()) {
             // Request data preparation
             if(!stream->Write(request)){
                 spdlog::get(LOGGER_CLUSTER)->error("Sync key enc broken stream sync end");
                 syncProcess = false;
                 break;
             }
```
The problem is that when I interrupt connection during write operation by disconnecting server from network (more precisely, I unplug the network cable) then stream->Write operation hangs forever.

### What did you expect to see?
As network remote host became unreachable, then I expected to see that client should close connection.

### What did you see instead?
Client continiously tries to restore connection.
![image](https://user-images.githubusercontent.com/77335604/210941950-7a0a4235-7f52-4e65-9a84-9011b85c7afe.png)
![image](https://user-images.githubusercontent.com/77335604/210943036-e004e683-3d58-4d45-8b24-ec9bb361cce5.png)

The situation which is provided above is repeated continuously:
IDLE->CONNECTING->TRANSIENT_FAILURE->SHUTDOWN -> .... IDLE -> ..

### Anything else we should know about your project / environment?
I'm building a long-living service and I suppose that grpc features as context deadline is not expected for the following case.

**Comment by yashykt** [comment]
Please enable keepalives. They are disabled by default on the client, but they would be incredibly useful for your usecase. https://github.com/grpc/grpc/blob/master/doc/keepalive.md for reference
