### ISSUE TITLE
Performance regression in #28750

### ISSUE THREAD

**Issue by drok** [grpc/grpc#32042]
### What version of gRPC and what language are you using?

master branch, C++

### What operating system (Linux, Windows,...) and version?

n/a

### What runtime / compiler are you using (e.g. python version or version of gcc)

n/a

### What did you do?

I'm looking to select an implementation of grpc for a new project. As an exercise in due diligence, I examine several aspects of the project, including performance metrics.

In this case, a [graphana segment dated March 22, 2022](https://grafana-dot-grpc-testing.appspot.com/?orgId=1&from=1647666000000&to=1648011600000) showed an anomaly, where C++ performance dropped by 10-20%

### What did you expect to see?

I expected performance to remain equal compared to previous versions, or an explanation given in case the performance change was expected. A significant performance change is often caused by an undetected functional regression.

### What did you see instead?

Performance in most metrics suffered a significant drop.

### Anything else we should know about your project / environment?

According to [this graphana segment](https://grafana-dot-grpc-testing.appspot.com/?orgId=1&from=1647666000000&to=1648011600000), the performance of the C++ runtime took a significant hit around 15-20%, along with some, not all metrics on PHP. Ruby, Python and C# (Grpc.Core), while the Go and Java counterparts saw no impact.

PR #28750 is the biggest change introduced around that time (77 commits), and reading through the PR comments, this performance hit does not appear to be expected.

The grpc-checks bot oscillated between the https://github.com/grpc/grpc/labels/perf-change%2Fnone and https://github.com/grpc/grpc/labels/perf-change%2Fhigh labels several times during the PR review process, though it finally landed on https://github.com/grpc/grpc/labels/perf-change%2Fnone

My interpretation is that #28750 either introduced a performance regression, or omitted to explain the drop. An alternate interpretation is that the apparent performance regression is a result of a new, but yet undetected bug introduced with the PR.

**Comment by markdroth** [comment]
This has nothing to do with #28750.  It was almost certainly caused by #29160.  See discussion in that PR for details.
