### ISSUE TITLE
How to set keepalive and test it correctly in python?

### ISSUE THREAD

**Issue by web4zn** [grpc/grpc#32095]
### What version of gRPC and what language are you using?
grpcio=1.49.1
python=3.10.3

### What operating system (Linux, Windows,...) and version?
win11 22621.963

### What runtime / compiler are you using (e.g. python version or version of gcc)
python=3.10.3

### What did you do?
I have a hyper-v virtual machine as server and local as client. 
The scenario is that there is a request which takes extremely long time maybe 10 to 20 minutes.
During the period that client waiting for response, the VM may BSOD and the sever down. But the client didn't know it and wait until 20min which is unacceptable.
So, I am trying to add keepalive option to channel, but it didn't work when I disconnect the network of VM.
```
#client code
CHANNEL_OPTIONS = [
    ("grpc.http2.max_pings_without_data", 0),
    ("grpc.keepalive_permit_without_calls", 1),
    ("grpc.keepalive_timeout_ms", 10000),
]


async def rpc(ip):
    async with grpc.aio.insecure_channel(
        target=f"{ip}:50051", options=CHANNEL_OPTIONS
    ) as channel:
        stub = vituralHW_pb2_grpc.VMStub(channel)
        response = await stub.DownloadPackages(
            vituralHW_pb2.DownloadRequest(taskid="abc"), timeout=240, wait_for_ready=True
        )
        print(response)
```
```
#server code
async def DownloadPackages(self, request: vituralHW_pb2.DownloadRequest, context: grpc.ServicerContext) -> vituralHW_pb2.DownloadReply:
    n=1
    while(n<60):
        print("waiting")
        await asyncio.sleep(1)
        n = n + 1
    taskid = request.taskid
    return vituralHW_pb2.DownloadReply(message=f"{taskid} package prepared")
```

### What did you expect to see?
I expect to see that the client will stop waiting for response when the server down.

### What did you see instead?
When I disconnect VM from network, client still waiting for response rather than close.

### Anything else we should know about your project / environment?
to be added

**Comment by web4zn** [comment]
After search a lot, I figure out that (grpc.keepalive_time_ms) option is missing causing this problem.
And I don't why async_greeter_client_with_options.py in python example only use (grpc.keepalive_timeout_ms) option rather than both.

**Comment by davendu** [comment]
@web4zn 

> I don't why async_greeter_client_with_options.py in python example only use (grpc.keepalive_timeout_ms) option

According to [document for keepalive](https://github.com/grpc/grpc/blob/master/doc/keepalive.md), most fields have default value, except for `keepalive_timeout_ms` which is set to `INT_MAX` at client side so the keepalive is disabled by default. Thus setting one field is enough if other values suits your need.

Sorry for bring up the old thread ;)
