### ISSUE TITLE
client implementation - socket mutator client impl try to bind the source IP address fails with "EINVAL The socket is already bound to an address"

### ISSUE THREAD

**Issue by mankhakb** [grpc/grpc#32109]
### What version of gRPC and what language are you using?
Version 1.3.8

### What operating system (Linux, Windows,...) and version?
Linux 4.19.8  x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
**Code Snippet** 
bool TcpInfoMutateFd(int fd, grpc_socket_mutator* pMutator) {
    CustomSocketMutator* pCustomSM = (CustomSocketMutator *)pMutator;
    return pCustomSM->MutateFd(fd);
}

bool CustomSocketMutator::MutateFd(const int fd)
{
    int type;
    socklen_t len = sizeof(type);

    if (0 != getsockopt( fd, SOL_SOCKET, SO_TYPE, &type, &len )) {
          printf("Unable to get the type");
    }

    //Below piece of code to BINDDEVICE with virtual interface is also not fruitful
    //if (0 != setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, <Virtual Device interface name>, strlen(Virtual Device interface name))) {
    //      **printf("Unable to bind with device <Virtual Device interface name>");**
    //}
    //else
    //{
    //    printf("Bind with device <Virtual Device interface name> success");
    //}

	struct sockaddr_in myaddr;
	memset((char *)&myaddr, 0, sizeof(myaddr));
	myaddr.sin_family = AF_INET;
	myaddr.sin_addr.s_addr = inet_addr("<Virtual Interface IP>");
	myaddr.sin_port = htons(0);

	if (bind(fd, (struct sockaddr *)&myaddr, sizeof(struct sockaddr_in)) < 0) {
		**printf("Bind failed " << strerror(errno) << errno);**
	}
	else
	{
		printf("Bind passed");
	}

    return true;
}

int TcpInfoCompare(grpc_socket_mutator* a,
                          grpc_socket_mutator* b) {
  return GPR_ICMP(a, b);
}

void TcpInfoDestroy(grpc_socket_mutator* mutator) 
{ 
    delete mutator;
}

const grpc_socket_mutator_vtable tcpInfoMutatorVtable =
    grpc_socket_mutator_vtable {TcpInfoMutateFd, TcpInfoCompare, TcpInfoDestroy};

/*
 brief - CreateMutatorCustomChannel method will create custom channel with custom channel 
                           Argument inclusive of socket option mutation
  target - target ip and port 
  creds - secure cred with cert and key 
  channelArgs - argument to set while creating custom channel 
  shared_ptr<grpc::Channel> - created custom channel */

std::shared_ptr<grpc::Channel> CreateMutatorCustomChannel(
    const grpc::string& target,
    const std::shared_ptr<grpc::ChannelCredentials>& creds,
    grpc::ChannelArguments& channelArgs)
{
    grpc_socket_mutator* tcpInfoMutator = new grpc_socket_mutator();
    grpc_socket_mutator_init(tcpInfoMutator, &tcpInfoMutatorVtable);
    channelArgs.SetSocketMutator(tcpInfoMutator);
    return grpc::CreateCustomChannel(target, creds, channelArgs);
}

channel_ = CreateMutatorCustomChannel(serverAddress_, channelCreds, channelArg);
Here channel_ is grpc channel, ServerAddress is serveraddress::port
**Issue: Bind is failing with errno 22 - EINVAL The socket is already bound to an address.**
Here trying to use socket mutator with bind to implement Client Source IP mangling with my virtual interface.

**ping -I "Virtual interface IP" "Actual Outbound interface ip"**
This is completely working fine at server end packet capture confirms the source IP as virtual interface IP.

### What did you expect to see?
Client source IP mangling will happen successfully. 
Outbound packet from client must show virtual interface IP instead of actual outbound IP 

### What did you see instead?
**Bind is failing with errno 22 - EINVAL The socket is already bound to an address.
This could be because channel creation internally uses bind already. So again doing bind is throwing error**

### Anything else we should know about your project / environment?
So here need help in:
1. Binding the virtual interface will be success and will not fail, Such that outbound packet will go via actual interface but source IP must be mangled with virtual interface IP.
2. Any other way to implement this?

**Comment by markdroth** [comment]
It's not clear from your description exactly what you're trying to do here, but the socket mutator is really intended to set socket options on a socket that is already bound; there is no way to bind the socket yourself from inside the socket mutator.

Also, more generally, grpc_socket_mutator is not a public API, and we don't support third-party plugins in the first place.  So I'm afraid that this isn't something we can help you with.
