### ISSUE TITLE
gRPC C# crashes with WSA 10047 code on Wine(Ubuntu)

### ISSUE THREAD

**Issue by TPapajCin** [grpc/grpc#32111]
I am getting problems with running grpc on Wine.

### What version of gRPC and what language are you using?
C#, target .NET Framework 4.7.2, Grpc.Core 2.46.3

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04 and Ubuntu 18.04 Docker
Wine version wine-7.0.1, IPv6 support disabled.

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet version 7.0.101

### What did you do?

Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?

 1. Install wine wine-7.0.1
  2. Install winetricks(https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks) and install dotnet472 `winetricks --unattended --force dotnet472`
  3. Try to run .NET Framework 4.7.2 application with included PubSub library(Google.Cloud.PubSub.V1 3.2.0, this uses gRPC). The error shows only when trying to do an action(not just creating a publisher but trying to publish or get topic metadata:

```
TopicName topicName = new TopicName(project,topic);
PublisherServiceApiClient.Create().GetTopic(topicName);
```
Because of the error message I was forwarded by Google guys to this repo because error is grpc specific and is not related too much to PubSub library itself. The error itself is below:

### What did you see instead?

```
00d0:fixme:path:parse_url failed to parse L"Google.Cloud.Iam.V1"

00d0:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm

00d0:fixme:iphlpapi:GetBestRoute2 (000000001FCEB480, 0, 0000000000000000, 000000001FCEB628, 0x00000000, 000000000041D3D0, 000000000041D3B0): stub

I0116 07:20:16.164736 0 ..\..\..\src\core\lib\iomgr\socket_windows.cc:164: Disabling AF_INET6 sockets because socket() failed.

I0116 07:20:16.282727 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:948: subchannel 000000001FE4D740 {address=ipv4:142.250.203.138:443, args=grpc.client_channel_factory=0x1fccc7c0, grpc.def
ault_authority=pubsub.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x1fccb0c0, grpc.internal.security_connector=0x1fe4be20, grpc.internal.subchannel_pool=0x1fcce460, grpc
.keepalive_time_ms=60000, grpc.max_receive_message_length=2147483647, grpc.primary_user_agent=grpc-csharp/2.46.3 (.NET Framework 4.7.3062.0; CLR 4.0.30319.42000; net45; x64), grpc.resource_quota=0x1fccb56
0, grpc.server_uri=dns:///pubsub.googleapis.com:443, grpc.service_config_disable_resolution=1}: connect failed: {"created":"@1673850016.282000000","description":"Failed to connect","file":"..\..\..\src\co
re\lib\iomgr\tcp_client_windows.cc","file_line":219,"referenced_errors":[{"created":"@1673850016.282000000","description":"OS Error","file":"..\..\..\src\core\lib\iomgr\tcp_client_windows.cc","file_line":
152,"grpc_status":14,"os_error":"Unable to retrieve error string","syscall":"WSASocket","wsa_error":10047}],"target_address":"ipv4:142.250.203.138:443"}

(... error from above shows multiple times)

07:20:16 fail: Application[0] Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":
"@1673850016.617000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1673850016.6170
00000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")    at System.Runtime.ExceptionServices.ExceptionDisp
atchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)    at Grpc.Core.DefaultCa
llInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest
,TResponse](TRequest req, ClientInterceptorContext`2 ctx)    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, Clie
ntInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallO
ptions options, TRequest request)    at Google.Cloud.PubSub.V1.Publisher.PublisherClient.GetTopic(GetTopicRequest request, CallOptions options)    at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync
(TRequest request, CallSettings callSettings)    at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)    at MT5EventConsumer.Pu
bSubClient..ctor(String project, String topic)    at MT5EventConsumer.Application.Main(String[] args)

D0116 07:20:16.723318 0 ..\..\..\src\core\lib\surface\init.cc:248: grpc_shutdown starts clean-up now
```

### Anything else we should know about your project / environment?

The `"wsa_error":10047` that shows in the first error menas `Address family not supported by protocol family.` I am making request in non-google library before trying to reach PubSub topic and it these requests works. My system has IPv6 disabled and I think it may be related to the error.

I also was told by Google guys that this repo is in maintenance mode. I would be really grateful if there would be a workaround or something like that for that problem or the system configuration option to be included to make that work.

**Comment by TPapajCin** [comment]
Just to add: it seems that on systems with enabled IPv6 gRPC works properly, I was able to test my application with IPv6 enabled. However on systems with IPv6 disabled it ends in the way above

**Comment by tonydnewell** [comment]
@TPapajCin We don't build or test gRPC in WINE but I've a look at the errors that you are seeing and it is probably because you have disabled IPv6.

The message
```cpp
I0116 07:20:16.164736 0 ..\..\..\src\core\lib\iomgr\socket_windows.cc:164: Disabling AF_INET6 sockets because socket() failed.
```
is informational from a probe checking whether the IPv6 loopback address is available. It seems to just disable the loopback address rather than all IPv6 addresses as the message suggests: 
```
static void probe_ipv6_once(void) {
  SOCKET s = socket(AF_INET6, SOCK_STREAM, 0);
  g_ipv6_loopback_available = 0;
  if (s == INVALID_SOCKET) {
    gpr_log(GPR_INFO, "Disabling AF_INET6 sockets because socket() failed.");
  } else {
```
[see socket_windows.cc](https://github.com/grpc/grpc/blob/9ad736c84ddcf95d56c3423e190b197f63be7c6a/src/core/lib/iomgr/socket_windows.cc#LL160-L165)

I thing the WSA 10047 error (Address family not supported by protocol family) is because the c-core code is still using AF_INET6 family even for an IPv4 address - it first tries to map the IPv4 address to an IPv6 formatted address - [see tcp_client_windows.cc](https://github.com/grpc/grpc/blob/9ad736c84ddcf95d56c3423e190b197f63be7c6a/src/core/lib/iomgr/tcp_client_windows.cc#L145) and then use that to create the connection with AF_INET6:
```cpp
if (grpc_sockaddr_to_v4mapped(addr, &addr6_v4mapped)) {
    addr = &addr6_v4mapped;
  }

  sock = WSASocket(AF_INET6, SOCK_STREAM, IPPROTO_TCP, NULL, 0,
                   grpc_get_default_wsa_socket_flags());
  if (sock == INVALID_SOCKET) {
    error = GRPC_WSA_ERROR(WSAGetLastError(), "WSASocket");
    goto failure;
  }
```
@jtattermusch I think someone with c-core knowledge needs to comment on this.

@TPapajCin Are you able to use the gRPC for .NET implementation instead of gRPC core? Do you need WINE or can you use native Linux versions of gRPC?

**Comment by tonydnewell** [comment]
I've also tested on Windows (not WINE) with IPv6 disabled and that works OK. So is probably a WINE issue.

**Comment by TPapajCin** [comment]
@tonydnewell About using gRPC for .NET instead of gRPC core, the `Google.Cloud.PubSub.V1` library I was using had gRPC core as a depepdency. I had to use Wine because the project was in .NET Framework.

**Comment by jtattermusch** [comment]
> @tonydnewell About using gRPC for .NET instead of gRPC core, the `Google.Cloud.PubSub.V1` library I was using had gRPC core as a depepdency. I had to use Wine because the project was in .NET Framework.

-  with `Google.Cloud.PubSub.V1` you can now choose which transport layer to use (Grpc.Core or grpc-dotnet).
- What I don't understand is why you're using WINE on Linux when  Grpc.Core has full native linux support (there might be other components in your app that really need to use WINE, but since Grpc.Core works supports running on Linux under Mono, it feels weird to run on on Linux under WINE. If you could run directly under Mono on linux, you'd probably have a much better experience with Grpc.Core.
- In fact I'm unsure whether `Google.Cloud.PubSub.V1` does support running under WINE officially (I really doubt that). So likely you're just running it on a platform that's supported on "best effort" basis (or not supported at all) which of course isn't guaranteed to work.

CC @jskeet  for using client libraries under WINE on linux.

**Comment by jskeet** [comment]
Indeed, I would regard running the Cloud Client Libraries under WINE in a similar way to running them in Unity etc - it's not a supported environment. If it works, that's great - but we're not resourced to look into every possible way of running .NET code. To be honest, I'd treat running .NET Framework code under Mono in the same category, but I think it's more likely to work than WINE. I'd strongly recommend porting the project to .NET 6 if at all possible - which in most cases it *really* should be. (And if that's not possible for the whole project, than ideally separating things out to have as much as possible running in .NET 6, and then using WINE just for the bit that really *needs* to be, would be best.)

**Comment by jtattermusch** [comment]
Closing this as running under WINE was never officially supported and Grpc.Core is close to being deprecated anyway.
