### ISSUE TITLE
can grpc build use openssl in bazel as cmake does

### ISSUE THREAD

**Issue by xiedeacc** [grpc/grpc#32129]
as title

**Comment by yashykt** [comment]
Some context in https://github.com/grpc/grpc/issues/32113

**Comment by yashykt** [comment]
Sounds like we would need to add our own bazel build rules for OpenSSL. We, as a team, do not have enough bandwidth to pick this up, but if someone from the community is interested in this, we'd be happy to review.

@jtattermusch Thoughts?
