### ISSUE TITLE
`from . ` is missing in generated python file

### ISSUE THREAD

**Issue by sumitsharansatsangi** [grpc/grpc#32177]
### What version of gRPC and what language are you using?
grpcio :- 1 51.1
grpcio-tools:- 1.51.1
language python

### What operating system (Linux, Windows,...) and version?
Linux :- Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.11

### What did you do?
I am generating python files using .proto files ,  
I am using my-protobuf package too.

### What did you expect to see?
In `user_pb2_grpc.py` file following is expected
`from . import user_pb2 as user__pb2`

### What did you see instead?
`import user_pb2 as user__pb2` 

### Anything else we should know about your project / environment?
Each time I edit proto file and then generate , I also have to do change in `user_pb2_grpc.py` file from 
`import user_pb2 as user__pb2` 
to 
`from . import user_pb2 as user__pb2`

**Comment by JeppeKlitgaard** [comment]
I am running into this as well (Python 3.12). The proposed fix of doing a relative import seems appropriate and works for me.

**Comment by gnossen** [comment]
[There's a lot of history here](https://github.com/protocolbuffers/protobuf/issues/1491), but we're more or less bound to follow the protobuf generated code's pattern here. At the moment, there isn't any movement on this issue. What you should do is set your `PYTHONPATH` / `sys.path` to point to the root of your generated code directory. This will ensure that you don't need to modify your generated code.
