### ISSUE TITLE
gRPC is blocking after system time changes

### ISSUE THREAD

**Issue by thomkopp** [grpc/grpc#32176]
### What version of gRPC and what language are you using?
1.36.4 (but seems to be the same in newer versions)

### What operating system (Linux, Windows,...) and version?
Linux (built with Yocto Hardknott)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
I created a channel state observer which should be called whenever the channel state changes or at least every two seconds. As my code is running on an embedded device changes of the system time - either by setting it hard or by drifting can occur. According to the proposition in https://github.com/grpc/grpc/issues/22955 I made sure to specify the deadline not in system time, but as a monotonic time.

Here's a snippet of the most important methods within the class `ChannelStateObserver`:
```cpp
/**
 * mState is an instance of type grpc_connectivity_state
 */
ChannelStateObserver::ChannelStateObserver(std::shared_ptr<grpc::Channel> channel, grpc::CompletionQueue& cq)
    : mChannel(channel)
    , mCompletionQueue(&cq)
    , mState(mChannel->GetState(true))
{
  registerStateChange();
}

void ChannelStateObserver::channelStateChanged()
{
  std::cout << "callback" << std::endl;
  auto state = mChannel->GetState(true);
  if (state != mState) {
    std::cout << "channel state changed to " << state << std::endl;    
    mState = state;
  }
  registerStateChange();
}

void ChannelStateObserver::registerStateChange()
{
  mChannel->NotifyOnStateChange(
      mState, GrpcTimeUtil::makeSteadyDeadline(std::chrono::seconds { 2 }), mCompletionQueue, static_cast<ITag*>(this));
}
```
And the class `GrpcTimeUtil`:
```cpp
/**
 * By default gRPC is based on the wall clock. This leads to the fact that timeouts don't work properly
 * in case the wall clock ist changed.
 * When specifing deadlines they should be based on the monotonic clock. Then gRPC will treat them the right way.
 *
 * see: https://github.com/grpc/grpc/issues/22955
 * @param timeoutDuration Duration to be set in the deadline
 * @return Deadline based on the monotonic clock
 */
template<class Rep, class Ratio>
inline gpr_timespec makeSteadyDeadline(std::chrono::duration<Rep, Ratio> timeoutDuration)
{
  using namespace std::chrono;
  nanoseconds timeoutAsNanoseconds = duration_cast<nanoseconds>(timeoutDuration);
  seconds timeoutAsSeconds = duration_cast<seconds>(timeoutAsNanoseconds);
  nanoseconds timeoutFractionalNanoseconds = timeoutAsNanoseconds - timeoutAsSeconds;
  gpr_timespec timeoutGpr = gpr_now(GPR_CLOCK_MONOTONIC);
  timeoutGpr.tv_sec += timeoutAsSeconds.count();
  timeoutGpr.tv_nsec += timeoutFractionalNanoseconds.count();
  return timeoutGpr;
}
```

In my main loop I'm blocking on the completion queue until I get any callback:
```cpp
void* tag = nullptr;
bool readSuccessful = false;
while (mCompletionQueue->Next(&tag, &readSuccessful)) {
  auto type = static_cast<ITag*>(tag)->getType();
  if (type == ITag::Type::CHANNEL_STATE_OBSERVER) {
    IChannelStateObserver* observer = static_cast<IChannelStateObserver*>(tag);
    observer->channelStateChanged();
  } else {
    // handle other tags
  }
}
```

### What did you expect to see?
I'm expecting to see the debug-output `callback` at least every two seconds or sooner, in case the channel state actually changes.

### What did you see instead?
Exactly what I expect - until the moment I start changing the system time. In case I set the system time back for 1 minute, I don't see any output for exactly 1 minute. If I set the system time back for 2 minutes, I don't see any output for 2 minutes....

Even if the channel state actually changes within that minute or two, I don't get any callback at all: gRPC seems to be completely blocked. Even if I set the environment variables `GRPC_VERBOSITY=debug GRPC_TRACE=all` I don't get any output until that minute or two are passed.
Afterwards everything works as expected again.

### Anything else we should know about your project / environment?
This seems to be quite a low level problem and I highly assume not necessarily related to my use case with the channel state observer.

**Comment by yashykt** [comment]
Adding @veblush as the assignee from https://github.com/grpc/grpc/issues/22955 and Yijie as someone who recently looked into a similar issue

**Comment by ctiller** [comment]
Do you have a callstack for the CondVar wait that's problematic?

**Comment by yijiem** [comment]
We have seen a similar issue before: https://github.com/grpc/grpc/issues/31738. The callstack that user saw was closed to https://gist.githubusercontent.com/yijiem/844ab252199d6d033b29a05c84c33b0f/raw/0c74bfb39da320afbc080cdf439d6321d5c3c1f7/gistfile1.txt.

**Comment by thomkopp** [comment]
> Do you have a callstack for the CondVar wait that's problematic?

Not yet, but I enabled gRPC's debug output which shows the problem very well.
https://gist.github.com/thomkopp/0e12656606e64ff625d1619e0f3249e8

You can see that the debug output before and after the system time change are both logged from timer_manager.cc.
The only call executed between lines 188 and 204 is [gpr_cv_wait()](https://github.com/grpc/grpc/blob/3e53dbe8213137d2c731ecd4d88ebd2948941d75/src/core/lib/iomgr/timer_manager.cc#L200)

In my example I set the system clock back for one minute - which leads in a blocking of 1 minute. If I set it back 5 minutes, it takes 5 minutes until I see the debug output indicating "wait ended". This clearly is wrong.

As I said this is due to the fact that Abseil's time implementation is based on the system clock.
When calling gpr_cv_wait() gRPC is doing the right thing and passing a timespec which is based on the monotonic clock. The problem is within [sync_abseil.cc](https://github.com/grpc/grpc/blob/3e53dbe8213137d2c731ecd4d88ebd2948941d75/src/core/lib/gpr/sync_abseil.cc#L89) where the timestamp is converted to a system clock value (which unfortunately is the only way how abseils condition variable handles times).
That then causes the initially described problem.

**Comment by thomkopp** [comment]
> We have seen a similar issue before: #31738. The callstack that user saw was closed to https://gist.githubusercontent.com/yijiem/844ab252199d6d033b29a05c84c33b0f/raw/0c74bfb39da320afbc080cdf439d6321d5c3c1f7/gistfile1.txt.

Yes, exactly: I went through that ticket and it seems to be exactly the same problem! Eventough the use case is a different one.

Like mentioned in my initial comment I'm seeing a similar effect like described here: https://github.com/grpc/grpc/issues/31738#issuecomment-1349078716: After the system time has been set back, I neither get notified on the completion queue that the timeout has occured nor if the channel state really has changed. It seems like all this get's queued up and then get's notified once the amount of time the system clock has been set back has passed.

**Comment by thomkopp** [comment]
https://github.com/grpc/grpc/issues/31738#issuecomment-1366298907
This describes the issue perfectly well.

It's not uncommon that the system-time get's changed (either by NTP or  with an embedded device also manually - for example when they are being taken into opration). A communication framework like gRPC should be able to handle it without hickups.

I'm worried about the last sentence of @yijiem comment here: https://github.com/grpc/grpc/issues/31738#issuecomment-1377664744 as using pthread based synchronisation solves this issue. As long as Abseil doesn't provide any other clock type I see this as a big problem on Linux based systems.

I also assume that this issue is slightly bigger than it looks in the first place. As the condition variable is a low level locking primitive which I'm sure is used in different parts of gRPC other problems may also arise. I'd strongly recommend rethinking the decision about moving away from pthread based synchronisation.

**Comment by veblush** [comment]
Abseil team is going to provide a way to use a monotonic clock for this particular case so it should be fixed when it's added. But it may take some time so I'll give an update once it's made.

**Comment by thomkopp** [comment]
> Abseil team is going to provide a way to use a monotonic clock for this particular case so it should be fixed when it's added. But it may take some time so I'll give an update once it's made.

Perfect. Thank you so much for taking care of this!

**Comment by sasreim** [comment]
Hi @veblush, is there any update on this issue available? 

we are currently facing the same issue on an embedded system which is synching the time using GPS. 
In case of time zone changes and if the system time jumps back we got stuck in WaitForConnected for quite a long time.

**Comment by yijiem** [comment]
gRPC v1.58 has upgraded its Abseil dependency version to [20230802](https://github.com/abseil/abseil-cpp/releases/tag/20230802.0) in https://github.com/grpc/grpc/commit/e04128ad1dce4575b69d9facf42c8750d620911f which should have addressed this issue. Please let us know if you are still having this issue after upgrading to v1.58+.

**Comment by guglielmomoretti** [comment]
Hi @yijiem 

I was just having the same issue using an old 1.38+ grpc lib. I recompiled version 1.67+ and the issue disappeared. So I can confirm that upgrading the library fixes the issue. 

Thanks
