### ISSUE TITLE
grpcio does not have ARM64 pre-built wheels

### ISSUE THREAD

**Issue by gitpushdashf** [grpc/grpc#32185]
There's no ARM64 wheels being built at the moment. While it can be installed through compiling, it's tedious. This affects Apple M1/M2, especially Docker builds on the platform.

Would be fantastic to have grpcio ARM64 wheels, for both musllinux and glibc.

**Comment by gnossen** [comment]
We do offer prebuilt arm64 manylinux wheels (for example 
[grpcio-1.51.1-cp310-cp310-manylinux_2_17_aarch64.whl](https://files.pythonhosted.org/packages/f1/3b/7f766f50d1455708722d1107880309eb676617317a0025cf5ed4f2deea9a/grpcio-1.51.1-cp310-cp310-manylinux_2_17_aarch64.whl)). With the release of 1.52.0, we'll also be offering universal2 wheels, which support both arm64 and x86-64 on Mac OS ([pre-release artifact](https://files.pythonhosted.org/packages/57/b5/9ad92194083d9e01c7fab5af955a8b0348f7bf2598921749ae96dfd0dd26/grpcio-1.52.0rc1-cp310-cp310-macosx_12_0_universal2.whl)). However, arm64 with musl libc is not currently on our road map.

**Comment by gitpushdashf** [comment]
Thank you for getting back to me! I guess I was testing on Python 3.11 with Docker on ARM64, which was having to compile the wheel. It looks like it works on 3.10.

For the pre-release, it looks like there's also no ARM64 wheels for 3.11. Do you know when we might see ARM64 glibc wheels for 3.11?

**Comment by gnossen** [comment]
Ah yes, you've reminded me of a piece of technical debt from months ago. We cannot support aarch64 + 3.11 + Linux without significant effort due to [this issue](https://github.com/dockcross/dockcross/issues/722), which it looks like you're already aware of.

**Comment by gitpushdashf** [comment]
Ah, that's right! I was looking through grpcio issues, thinking something might ring a bell.

I appreciate your help and work on this project.

**Comment by gitpushdashf** [comment]
Looks like that issue was taken care of!
