### ISSUE TITLE
Undefined reference to vtable for grpc::experimental when adding --coverage flag

### ISSUE THREAD

**Issue by mmerah** [grpc/grpc#32188]
### What version of gRPC and what language are you using?
C++ 17
gRPC v1.51.1

### What operating system (Linux, Windows,...) and version?
Ubuntu Linux 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ 11.3.0

### What did you do?
1. Use any sample/example using gRPC with a server (I used https://github.com/faaxm/exmpl-cmake-grpc) that can build normally
2. Add `--coverage` flag. As an example here is the part of a CMakePresets.json that does it in my project:
```json
{
      "name": "coverage-unix",
      "binaryDir": "${sourceDir}/build/coverage",
      "inherits": "ci-unix",
      "hidden": true,
      "cacheVariables": {
        "ENABLE_COVERAGE": "ON",
        "CMAKE_BUILD_TYPE": "Coverage",
        "CMAKE_CXX_FLAGS_COVERAGE": "-Og -g --coverage -fkeep-inline-functions -fkeep-static-functions",
        "CMAKE_EXE_LINKER_FLAGS_COVERAGE": "--coverage",
        "CMAKE_SHARED_LINKER_FLAGS_COVERAGE": "--coverage",
        "CMAKE_MAP_IMPORTED_CONFIG_COVERAGE": "Coverage;RelWithDebInfo;Release;Debug;"
      }
    },
```
3. Try to build
4. A linker error happens.

### What did you expect to see?
I expected no linker error

### What did you see instead?

A linker error as follows:
```
[build] /usr/bin/ld: ../CMakeFiles/demo_lib.dir/source/lib.cpp.o: in function `grpc::experimental::StaticDataAuthorizationPolicyProvider::StaticDataAuthorizationPolicyProvider(grpc_authorization_policy_provider*)':
[build] /home/toto/development/cmake-init-tuto/demo/build/coverage/vcpkg_installed/x64-linux/include/grpcpp/security/authorization_policy_provider.h:48: undefined reference to `vtable for grpc::experimental::StaticDataAuthorizationPolicyProvider'
[build] /usr/bin/ld: ../CMakeFiles/demo_lib.dir/source/lib.cpp.o: in function `grpc::experimental::FileWatcherAuthorizationPolicyProvider::FileWatcherAuthorizationPolicyProvider(grpc_authorization_policy_provider*)':
[build] /home/toto/development/cmake-init-tuto/demo/build/coverage/vcpkg_installed/x64-linux/include/grpcpp/security/authorization_policy_provider.h:73: undefined reference to `vtable for grpc::experimental::FileWatcherAuthorizationPolicyProvider'
[build] CMakeFiles/demo_lib.dir/source/lib.cpp.o: in function `grpc::experimental::StaticDataAuthorizationPolicyProvider::StaticDataAuthorizationPolicyProvider(grpc_authorization_policy_provider*)':
[build] /home/toto/development/cmake-init-tuto/demo/build/coverage/vcpkg_installed/x64-linux/include/grpcpp/security/authorization_policy_provider.h:48: undefined reference to `vtable for grpc::experimental::StaticDataAuthorizationPolicyProvider'
[build] /usr/bin/ld: CMakeFiles/demo_lib.dir/source/lib.cpp.o: in function `grpc::experimental::FileWatcherAuthorizationPolicyProvider::FileWatcherAuthorizationPolicyProvider(grpc_authorization_policy_provider*)':
[build] /home/toto/development/cmake-init-tuto/demo/build/coverage/vcpkg_installed/x64-linux/include/grpcpp/security/authorization_policy_provider.h:73: undefined reference to `vtable for grpc::experimental::FileWatcherAuthorizationPolicyProvider'
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

My project used CMake + vcpkg with a manifest file.

In grpcpp/security/authorization_policy_provider.h, I changed the desctructor of both implementations to have `default`:
```cpp
// ...
~StaticDataAuthorizationPolicyProvider() override = default;
// ...
~FileWatcherAuthorizationPolicyProvider() override = default;
```
And, the linker errors disappeared.
Am I wrong in doing this or is there an alternative I can use?

**Comment by drfloob** [comment]
The `grpc_authorization_provider` library is not linked into gRPC by default. It's interesting that the coverage flag hits this error, I've never tried it myself, but maybe linking against `grpc_authorization_provider` explicitly will solve the problem.

**Comment by mmerah** [comment]
> The `grpc_authorization_provider` library is not linked into gRPC by default. It's interesting that the coverage flag hits this error, I've never tried it myself, but maybe linking against `grpc_authorization_provider` explicitly will solve the problem.

Thank you for the quick feedback. I am sorry if this seems basic but how exactly would I go about doing this? 

The CMake for the libraries look like this:
```cmake
find_package(Protobuf REQUIRED)
find_package(gRPC CONFIG REQUIRED)

add_library(proto-objects STATIC ${PROTO_FILES})
target_link_libraries(proto-objects
    PUBLIC
        protobuf::libprotobuf
        gRPC::grpc
        gRPC::grpc++
)

# Use of protobuf_generate on the ${PROTO_FILES}
# ...

add_library(demo_lib source/lib.cpp)
target_link_libraries(demo_lib
    PRIVATE
        fmt::fmt
        proto-objects
)
```
The proto-objects contains the .c/.h generated from the .proto. And, demo_lib contains the sample gRPC server code. How would I explicitely not link agains `grpc_authorization_provider` ? It almost seem to me that I would need to do something before that, am I wrong?
Wouldn't the problem be more on the side of vcpkg then?

**Comment by drfloob** [comment]
I don't really work with cmake or vcpkg, you might have to experiment here. Adding the `-lgrpc_authorization_provider` flag to your build may work.

**Comment by mmerah** [comment]
> I don't really work with cmake or vcpkg, you might have to experiment here. Adding the `-lgrpc_authorization_provider` flag to your build may work.

Ok, this can be achieved on vcpkg by using a custom port instead of the default gRPC port. I can then either add a patch to the authorization_policy_provider.h or change the compilation flag of gRPC itself.
Thank you for the suggestions.
