### ISSUE TITLE
Python server "freezes" when exception causes exception

### ISSUE THREAD

**Issue by jshannon-tml** [grpc/grpc#32199]
Mac OS - Python 3.9.6 - gRPC 1.51.1 (whatever was installed via pip)

I find that the python server freezes when an exception occurs during an exception. By "freezes" I see that the client never gets a response, don't timeout, and the server doesn't provide any error messages.

**Result**
When an exceptions occurs while handling an exception, the server doesn't print any exception or error info and doesn't seem to send any exception info back to the client. The connection appears to stay open.

**Expectation**
In this case the server should print out both exceptions (as python normally would) and send some exception info to the client as a `_InactiveRpcError` response (just like with single exceptions). Sending this error to the client should close the connection. 

Not sure which exception text *should* be sent to the client. Probably the original?

**Reproduction**
I'm modifying the `helloworld_server.py` example file:

```
class MyException(Exception):
    def __str__(self) -> str:
        return self.args[0]

class Greeter(helloworld_pb2_grpc.GreeterServicer):

    def SayHello(self, request, context):
        raise MyException('valid exception')
        return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)

```

Specifically, before `SayHello` returns the reply, I raise an exception in which the string representation is the exception message. 

The result is that the server prints a traceback with the exception:
```
Server started, listening on 50051
ERROR:grpc._server:Exception calling application: valid exception
Traceback (most recent call last):
  File "/python3.9/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/grpc-master/examples/python/helloworld/greeter_server.py", line 33, in SayHello
    raise MyException('valid exception')
MyException: valid exception
```

And the client also raises an exception, which includes the exception message in the reply:
```
Will try to greet world ...
Traceback (most recent call last):
  File "/grpc-master/examples/python/helloworld/greeter_client.py", line 38, in <module>
    run()
  File "/grpc-master/examples/python/helloworld/greeter_client.py", line 32, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: valid exception"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {created_time:"2023-01-18T23:02:47.091232-08:00", grpc_status:2, grpc_message:"Exception calling application: valid exception"}"
>
```

However, if I modify the exception to cause another exception:
```
class MyException(Exception):
    def __str__(self) -> str:
        return self.args[10] # <<<<<<<<< This causes an index error
```

And then call the client again I get:
```
Will try to greet world ...
```

And no output from the server.

**Comment by XuanWang-Amos** [comment]
Thanks for brining this to our attention, this will happen if the exception thrown in application code is unprintable. I just raised a PR to fix this, should be fixed soon.
