### ISSUE TITLE
gRPC Python bug in data catalog update

### ISSUE THREAD

**Issue by bouziane-meed** [grpc/grpc#32197]
I get this error when I run thr update_tag function in purpose to udate the metadata in the datacatalog.

## This is my script :
```python 
........ 

tag = datacatalog_v1.Tag(
            name=f"table_{table_id}_tag",
            template=tag_template.name
        )

# add values in Sheets to tag
for column_name in df:
    tag.fields[column_name] = datacatalog_v1.types.TagField()
    tag.fields[column_name].string_value = df[column_name][index]

try:
    tag_created = datacatalog_client.create_tag(
        parent=table_entry.name,
        tag=tag
    )
    print(f"Created tag: {tag.name}")

except AlreadyExists:
    # Create a client
    request = datacatalog_v1.UpdateTagRequest(
        tag=tag,
    )
    # Make the request
    response = datacatalog_client.update_tag(request=request)

    print(f"Tag {tag.name} was Updated ")
    ...........
```

## the error I got :

```
E0124 16:13:49.199000000 17140 src/core/ext/transport/chttp2/transport/hpack_parser.cc:1218] Error parsing metadata: error=invalid value key=content-type value=text/html; charset=UTF-8

```

and it is the result of :     response = datacatalog_client.update_tag(request=request)

**Comment by XuanWang-Amos** [comment]
Hi, can you provide more logs for this issue? With current information our guess is your gRPC client hit a server which happens to be running on top of http2 but it's not a gRPC server.

**Comment by bouziane-meed** [comment]
Hello, 
This is the only log I get :

E0124 16:13:49.199000000 17140 src/core/ext/transport/chttp2/transport/hpack_parser.cc:1218] Error parsing metadata: error=invalid value key=content-type value=text/html; charset=UTF-8

yes, it is caused by the gRPC client, I tried many version of the grpcio but the doesn't solve the problem

**Comment by gnossen** [comment]
@bouziane-meed To be clear, it seems the issue that you're not actually hitting a gRPC server. Please confirm the target that  you're supplying to client is the intended server.
