### ISSUE TITLE
grpc_testing implementation of UnaryUnary does not conform to interface of UnaryUnaryMultiCallable

### ISSUE THREAD

**Issue by nicholasbailey** [grpc/grpc#32192]
### What version of gRPC and what language are you using?
1.48.2 Python, but I have confirmed the behavior is the same on latest

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.16

### What did you do?
Set up a simple test utlizing grpc_testing
```
import grpc_testing
test_channel = grpc_testing.channel(
        [],
        grpc_testing.strict_real_time()
)
stub = AnyGrpcStub(test_channel)
request = TheAppropriateRequestType()
stub.AGrpcCall(request, wait_for_ready=True)
```

### What did you expect to see?
A passing test

### What did you see instead?
The test ails with `TypeError: __call__() got an unexpected keyword argument 'wait_for_ready'`

The reason for this issue is pretty straightforward, the `wait_for_ready` and `compression` parameters have not been added to grpc_testing's fakes.

**Comment by XuanWang-Amos** [comment]
Yeah some of our new features are not implemented in grpc_testing yet (like the ones mentioned in https://github.com/grpc/grpc/issues/34734), we're actually considering alternatives to grpc_testing, please comment on the other issue so we know what our user needs.

In the meanwhile, I'll close this one as duplicate.
