### ISSUE TITLE
[tracking] gRPC Bazel Workspace fails to build due to SHA256 checksum mismatches

### ISSUE THREAD

**Issue by MattVitelliDDLabs** [grpc/grpc#32242]
### What version of gRPC and what language are you using?
I am attempting to build the `master` branch using Bazel 4.2.1. Upon attempting to build, I noticed that many of the dependencies seem to fail during the build due to mismatching sha256 checksums.

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel Version 4.2.1
GCC 5.4.0

### What did you do?
I performed the following commands:
```
git clone https://github.com/grpc/grpc.git
cd grpc
bazel build ...
```
Shortly after Bazel begins downloading the gRPC dependencies, it fails due to invalid sha256 signatures.
Note - to reproduce, you may need to remove your existing Bazel cache if you've already built gRPC previously since Bazel will cache previously downloaded files by sha. This should reproduce deterministically assuming your Bazel cache is clean.

### What did you expect to see?
I do not expect to see sha256 errors when building the gRPC workspace.

### What did you see instead?
As soon as I attempt to build gRPC, I immediately see issues where external dependencies fail to download due to sha256 mismatches. In this case, `com_envoyproxy_protoc_gen_validate` fails. If I manually update the sha256 for `com_envoyproxy_protoc_gen_validate`, I can get `com_envoyproxy_protoc_gen_validate` to successfully be pulled in, but `@xctestrunner//:ios_test_runner` seems to fail with a similar invalid sha256.

```
root@matt-Precision-7560:~/.cache/test_grpc2/grpc# bazel build ...
Starting local Bazel server and connecting to it...
INFO: Repository com_envoyproxy_protoc_gen_validate instantiated at:
  /root/.cache/test_grpc2/grpc/WORKSPACE:5:10: in <toplevel>
  /root/.cache/test_grpc2/grpc/bazel/grpc_deps.bzl:460:21: in grpc_deps
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/5897d3b5b48cb68dfe2e7d148e2cc4f3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 912a3f592d53edea301b31492b43f817ea17b6a7246ada9c2f73dfa1d714459d but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
ERROR: An error occurred during the fetch of repository 'com_envoyproxy_protoc_gen_validate':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/5897d3b5b48cb68dfe2e7d148e2cc4f3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz] to /root/.cache/bazel/_bazel_root/5897d3b5b48cb68dfe2e7d148e2cc4f3/external/com_envoyproxy_protoc_gen_validate/temp1803830372754587512/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz: Checksum was 912a3f592d53edea301b31492b43f817ea17b6a7246ada9c2f73dfa1d714459d but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/5897d3b5b48cb68dfe2e7d148e2cc4f3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz] to /root/.cache/bazel/_bazel_root/5897d3b5b48cb68dfe2e7d148e2cc4f3/external/com_envoyproxy_protoc_gen_validate/temp1803830372754587512/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz: Checksum was 912a3f592d53edea301b31492b43f817ea17b6a7246ada9c2f73dfa1d714459d but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
ERROR: no such package '@com_envoyproxy_protoc_gen_validate//': java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz] to /root/.cache/bazel/_bazel_root/5897d3b5b48cb68dfe2e7d148e2cc4f3/external/com_envoyproxy_protoc_gen_validate/temp1803830372754587512/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz: Checksum was 912a3f592d53edea301b31492b43f817ea17b6a7246ada9c2f73dfa1d714459d but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
INFO: Elapsed time: 2.503s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by philstahlfeld** [comment]
I'm seeing this as well.

**Comment by philstahlfeld** [comment]
Looks like this is a [Github issue](https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409438954)

**Comment by yijiem** [comment]
Yes, it's a Github issue, see here also: https://github.com/orgs/community/discussions/45830. It seems like the archives created by Github have changed due to a change in the compression level in git-archive. This results into the checksum mismatch and Github is reverting the change.

CC @drfloob who is our first responder.

**Comment by yijiem** [comment]
Seems like the issue has been resolved with Github rollback. @MattVitelliDDLabs please let us know if you are still seeing the issue. Thanks!

**Comment by MattVitelliDDLabs** [comment]
Looks good on my side - thanks for the quick response! I'll close this issue.
