### ISSUE TITLE
Support pre-built binaries for Ruby 3.2

### ISSUE THREAD

**Issue by scarroll32** [grpc/grpc#32258]
Is your feature request related to a problem? Please describe.
It seems grpc does not support pre-built binaries for Ruby 3.2. 

Describe the solution you'd like
Add pre-built binaries for Ruby 3.2

Describe alternatives you've considered
N/A

Additional context
- https://github.com/grpc/grpc/issues/28627
- [Ruby 3.1 release note: https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)

**Comment by apolcyn** [comment]
This is coming in the upcoming 1.52.0 release

You can use it already in the 1.52.0.pre2 packages

**Comment by knu** [comment]
Looks like the gem version 1.52.0 has not been released yet.
https://rubygems.org/gems/grpc/versions

**Comment by knu** [comment]
Version 1.52.0 seems to have been pushed. 👍
