### ISSUE TITLE
Pyi stubs are missing for protobuf types in `grpcio-health-checking` 

### ISSUE THREAD

**Issue by marcoferrer** [grpc/grpc#32264]
### What version of gRPC and what language are you using?
Python 3.11
grpcio-health-checking  1.51.1

### What operating system (Linux, Windows,...) and version?
Mac

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Protobuf types for health check API fail resolution due to `pyi` stubs missing in the wheel
![image](https://user-images.githubusercontent.com/35935108/216152811-d0b5f95e-682d-4e70-88fe-cb6d89c6ebf4.png)

### What did you expect to see?
Protobuf types resolve correctly

### What did you see instead?
My application still functions correctly, but ide intellisense is broken

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
@XuanWang-Amos This will be resolved by https://github.com/grpc/grpc/pull/31769, right?

**Comment by XuanWang-Amos** [comment]
> @XuanWang-Amos This will be resolved by #31769, right?

Not exactly, those are in `*_pb2` files, I think we need help from protobuf team to add types to generated files.

**Comment by marcoferrer** [comment]
So I noticed that the `pyi` files are only generated when the `pyi` protoc generator is enabled. Is that already the case and the files were just not being included in the final artifact?

**Comment by gnossen** [comment]
That was indeed the case. https://github.com/grpc/grpc/pull/32268 will fix it.
