### ISSUE TITLE
issue with "install", because zlib's cmake_install.cmake disrespects CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by z4v4l** [grpc/grpc#32296]
### What version of gRPC and what language are you using?
latest. C++.

### What operating system (Linux, Windows,...) and version?
Windows. cmake version 3.22.22040401-MSVC_2

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC!

### What did you do?
I built gprc. and then as per instructions, had to "install" it. which turned to be just copying 441MB from the build directory to another one. I, of course, didn't want it to end up in C:\Program Files, as recommended, before installing, I **_set CMAKE_INSTALL_PREFIX appropriately_**. everything was fine, but at the end of this huge copying the error about not being able to "install" zlib files into C:\Program Files popped up, guessing, that perhaps it's not enough of rights. of course, I asked to copy it in a different place. after examining the file:
`build\third_party\zlib\cmake_install.cmake` I found a several places, where instead of
`INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib"`,
as, for example is in `build\cmake_install.cmake`
there was such lines
`INSTALL DESTINATION "C:\Program Files (x86)/lib"`,

hardcoded. changing that to using CMAKE_INSTALL_PREFIX fixed it.

### What did you expect to see?
as described, I expected it to respect CMAKE_INSTALL_PREFIX. should I run as an administrator, it would litter Program Files.

### What did you see instead?
yeah.
### Anything else we should know about your project / environment?
it's just an incorrect cmake somewhere in your project. because, I see, these cmake_install.cmake files are only in the build directory, so they are generated from something. I am not that much into cmake, so can't say more.

**Comment by yashykt** [comment]
Is it reasonable to fix it in zlib's repo?

**Comment by veblush** [comment]
Would you show an exact command when seeing this problem? From what I read from [zlib cmakefile](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/CMakeLists.txt), it should respect that config. Another thing you can try is to install zlib first by yourself and install gRPC with -DgRPC_ZLIB_PROVIDER=package meaning that zlib is installed so gRPC shouldn't install it and just use the installed one.

**Comment by z4v4l** [comment]
> Would you show an exact command when seeing this problem? From what I read from [zlib cmakefile](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/CMakeLists.txt), it should respect that config. Another thing you can try is to install zlib first by yourself and install gRPC with -DgRPC_ZLIB_PROVIDER=package meaning that zlib is installed so gRPC shouldn't install it and just use the installed one.

I wish, I remembered. I followed the official "build gRPC from source" article. after all, there are 3rd party dependencies and all they were "installed" in the same process and didn't give such an error, only zlib did, so it's something with it. I saw, that in CmakeLists.txt everything looks fine, but in the zlib's generated install.cmake it isn't.

**Comment by veblush** [comment]
Would you reproduce it again and capture the exact commands?

**Comment by gdiazlo** [comment]
This happened to me to with v1.62.0 on macOS. A make install would fail with:

```
CMake Error at third_party/zlib/cmake_install.cmake:49 (file):
  file cannot create directory: /lib.  Maybe need administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:3054 (include)
```

With cmake 3.29.2
