### ISSUE TITLE
grpc is very bollshit

### ISSUE THREAD

**Issue by gitsupi** [grpc/grpc#32297]
plz listen to me reenginner grpc to creating complec seystem with easy interfaec

**Comment by gitsupi** [comment]
@markdroth plz come here to talk new revolution for rpc systems

**Comment by efriel94** [comment]
> @markdroth plz come here to talk new revolution for rpc systems if you ready send a reply

@markdroth I'm ready

**Comment by gitsupi** [comment]
i test grpc by quick start in go lang...
some lacks exist for this modeling..
some theme are the following:

1. always rpc is server methods that calls by clients so grpc should
generate server signature also but now grpc is not creating rpc server
methods and we have to write manually repeated works and it is not meeting
optimal system desigm reuirment

if u dont understand this lack
tell me to give u qn example
thanks

**Comment by markdroth** [comment]
This is not an actionable bug report.  If you have a question to ask, I suggest asking it on one of the following forums:

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by gitsupi** [comment]
I HAVE NO QUESTION 
I HAVE AN IDEA TO CREATE NEW PROJECT BASED GRPC
@markdroth
