### ISSUE TITLE
Python `grpcio` 1.52.0 is broken on Apple Silicon

### ISSUE THREAD

**Issue by danieljanes** [grpc/grpc#32306]
### What version of gRPC and what language are you using?

`grpcio` 1.52.0, installed via PyPI (using Poetry)
CPython 3.9.16

### What operating system (Linux, Windows,...) and version?

macOS 13.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

CPython 3.9.16, installed via pyenv, native Apple Silicon on an M1 MacBook

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Install a development build of the `flwr` library (Flower, flower.dev) and run one of our code examples (e.g. [quickstart_pytorch](https://github.com/adap/flower/tree/main/examples/quickstart_pytorch)). This should not be necessary though, I assume that the issue is reproducible in the same environment in other ways, too.

### What did you expect to see?

The example completes successfully.

### What did you see instead?

When running the Flower server (via `flower-server`), we get a repeated log output:

```bash
E0206 11:46:24.733515000 12999757824 thread_pool.cc:254]               Waiting for thread pool to idle before forking
```

This only happens with grpcio 1.52.0, not with grpcio 1.51.1, which is why we decided to disallow 1.52.0 in our next release (https://github.com/adap/flower/pull/1644).

Update: this blocks the process and the terminal session, the only way to kill it is to use `kill -9` in a different terminal window.

### Anything else we should know about your project / environment?

Native Apple Silicon, no Rosetta2 x86 emulation.

**Comment by gnossen** [comment]
This looks a lot like [this issue](https://github.com/grpc/grpc/issues/31885), which has (mostly) been resolved on the master branch. Can you please try [our nightly build](https://packages.grpc.io/archive/2023/02/860947605b98d5e4f1e3a52c140293279b1307ee-6999ae04-5ff0-42a5-b45d-a6dc2aa2b0a8/index.xml) and let us know if this resolves the issue?

**Comment by danieljanes** [comment]
Thanks for the fast reply. The log output looks the same, but I'm surprised they report 1.51.1, which works like a charm for us.

I just installed the nightly, but it raises a different issue that suggests that we have to recompile our ProtoBufs. We'll dig into it when we have more time.

Do you expect 1.52.0 to be janked or will it remain available? In the latter case, we'll have to continue to exclude it in our dependency spec.

**Comment by gnossen** [comment]
> but it raises a different issue that suggests that we have to recompile our ProtoBufs

This is very surprising. What version are you upgrading from? Can you please take a moment to upload the full logs?

> Do you expect 1.52.0 to be janked or will it remain available?

I would like to understand the scope the issue a bit better before making the decision to yank. This version introduces pre-built M1-compatible artifacts and should provide a lot of benefits to users. If it's clear that the scope is very large, we will of course yank this release and follow up shortly with a patch.

**Comment by danieljanes** [comment]
Now that I tried to reproduce the logs mentioning the ProtoBuf recompilation, they didn't show up again.

The good news: I can now confirm that the reported issue is fixed in 1.53 nightly.

**Comment by ayyoubelamrani4** [comment]
Hi there,

I have the same issue; `Waiting for thread pool to idle before forking` when deploying my Django app, this issue just appeared tonight.

Old builds seem to have grpc 1.51 and new ones that are failing the health check have 1.52.

- Not sure with what library this is being installed, is there a way to force the 1.51 regardless of the library using it?
- Is there a planned fix for this issue?

**Comment by gnossen** [comment]
> Not sure with what library this is being installed, is there a way to force the 1.51 regardless of the library using it?

Yes. Add `grpcio==1.51.1` to your `requirements.txt` file.

> Is there a planned fix for this issue?

Yes. This has been fixed on our master branch. To our knowledge, this issue should not have been introduced in 1.52.0, but it _does_ seem to be nondeterministic, so it may be that this release simply increased the rate of it happening.

We'll very shortly be making the decision on whether to yank `1.51.0`.

**Comment by ayyoubelamrani4** [comment]
Perfect, thanks @gnossen

**Comment by gnossen** [comment]
`1.52.0` has been yanked. We will follow up with a patched release in the next couple of days. Thank you everyone for reporting the issue.

**Comment by clarng** [comment]
fyi we also saw issues on linux per https://github.com/ray-project/ray/pull/32245

**Comment by pietrodn** [comment]
Maybe it could be a good idea to just release the Apple Silicon build for 1.51.1, without any code changes...?

**Comment by gnossen** [comment]
@pietrodn Agreed. We'll work on making this happen in the new few days.

**Comment by marns93** [comment]
@gnossen Any estimates when the new release will be published?

**Comment by gnossen** [comment]
The current estimate is Friday, February 15th.

**Comment by gnossen** [comment]
Due to an issue with the CI build, the estimate is now Tuesday, February 28th.

**Comment by gnossen** [comment]
[1.51.3](https://pypi.org/project/grpcio/1.51.3/) has now been released with universal2 artifacts.

**Comment by pietrodn** [comment]
The universal wheels for Python 3.7 to 3.11 are on PyPI and working. Great news for Apple Silicon users 🎉
