### ISSUE TITLE
is nodejs client working with .pem files? 

### ISSUE THREAD

**Issue by urko-b** [grpc/grpc#32312]
@blerest 
I tested your certs (in C++, not in nodejs) and it fails as well. It has to do with the fact that all your certs have the same subject which confuses the openssl cert chain builder (best guess).

If you change the lines in your script that assign identities to:
```
openssl req -passin pass:1111 -new -x509 -days 365 -key ca.key -out ca.crt -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Test/CN=ca"

openssl req -passin pass:1111 -new -key server.key -out server.csr -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Server/CN=localhost"

openssl req -passin pass:1111 -new -key client.key -out client.csr -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Client/CN=localhost"
```

And change your client code to really use the CA cert as the CA as opposed to the server cert:
```
let credentials = grpc.credentials.createSsl(fs.readFileSync('./ssl/ca.crt'), fs.readFileSync('./ssl/client.key'), fs.readFileSync('./ssl/client.crt'));
```

Things should work (at least they do in C++). Please let me know if that's not the case.

_Originally posted by @jboeuf in https://github.com/grpc/grpc/issues/6757#issuecomment-264617793_

**Comment by urko-b** [comment]
I've code a nodejs grpc client and is not working against a `go` grpc server  deployed on VPS accessed publicly through domain name. 
I've created a grpc `go` client to test if connection to server was fine and It works good.
Same certificates used, same domain name and port used... I don't know what is happening.

```
const server_cert = fs.readFileSync(process.env.SERVER_CERT);
		const client_key = fs.readFileSync(process.env.CLIENT_CERT_KEY);
		const client_cert = fs.readFileSync(process.env.CLIENT_CERT);

		const credentials = grpc.credentials.createSsl(
			server_cert,
			client_key,
			client_cert,
		);
		
		this.grpcClient = new downloadProto.DownloadService(
			`${GRPC_SERVER}:${GRPC_PORT}`,
			credentials,
			{
				"grpc.ssl_target_name_override": GRPC_SERVER,
				"grpc.default_authority": GRPC_SERVER,
			},
		);
		this.grpcClient.Read(
			{ id: "some_video_url" },
			(err, video) => {
				if (err) {
					console.error("error when read: ", err);
				}
			},
		);
```

No connection established is the output error displayed on consle

**Comment by yashykt** [comment]
https://github.com/grpc/grpc-node is what you want I think
