### ISSUE TITLE
Installation always get stuck at "client_channel"

### ISSUE THREAD

**Issue by 123pierre** [grpc/grpc#32310]
Hello,

I tried many times to install GRPC either via "pecl install grpc" or compling myself. Following the official https://cloud.google.com/php/grpc

Always same fatal error: c++: fatal error: Killed signal terminated program cc1plus

Any one can suggest a solution?

Thank you so much !!

### What version of gRPC and what language are you using?
I believe it's the latest since I am either:
pecl install grpc
or
git clone https://github.com/grpc/grpc

### What operating system (Linux, Windows,...) and version?
Plesk server Linux  4.19.0-21-cloud-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 8.3.0 (Debian 8.3.0-6) ( is that what you need? )
PHP 7.3.31-1~deb10u2 (cli)

### What did you do?
I tried either compiling my self or running the pecl installation.
I show you the result for PECL installation only

### What did you expect to see?
The modul to be correctly installed

### What did you see instead?
     -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1     -DGRPC_XDS_USER_AGENT_NAME_SUFFIX='"PHP"'     -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX='"1.51.1"' -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/include -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/main -I/tmp/pear/temp/grpc -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp
/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -I/tmp/pear/temp/grpc/third_party/xxhash  -DHAVE_CONFIG_H  -std=c++14 -fno-exceptions -fno-rtti -g -O2   -c /tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc -o src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.lo
libtool: compile:  g++ -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"PHP\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.51.1\" -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/include -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/main -I/tmp/pear/temp/grpc -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_part
y/re2 -I/tmp/pear/temp/grpc/third_party/upb -I/tmp/pear/temp/grpc/third_party/xxhash -DHAVE_CONFIG_H -std=c++14 -fno-exceptions -fno-rtti -g -O2 -c /tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc  -fPIC -DPIC -o src/core/ext/filters/client_channel/lb_policy/ring_hash/.libs/ring_hash.o
/bin/bash /tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/libtool --mode=compile g++ -fvisibility=hidden     -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0     -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1     -DGRPC_XDS_USER_AGENT_NAME_SUFFIX='"PHP"'     -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX='"1.51.1"' -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/include -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/main -I/tmp/pear/temp/grpc -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp
/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -I/tmp/pear/temp/grpc/third_party/xxhash  -DHAVE_CONFIG_H  -std=c++14 -fno-exceptions -fno-rtti -g -O2   -c /tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/rls/rls.cc -o src/core/ext/filters/client_channel/lb_policy/rls/rls.lo
libtool: compile:  g++ -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"PHP\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.51.1\" -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/include -I/tmp/pear/temp/pear-build-rootLJFVXn/grpc-1.51.1/main -I/tmp/pear/temp/grpc -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_part
y/re2 -I/tmp/pear/temp/grpc/third_party/upb -I/tmp/pear/temp/grpc/third_party/xxhash -DHAVE_CONFIG_H -std=c++14 -fno-exceptions -fno-rtti -g -O2 -c /tmp/pear/temp/grpc/src/core/ext/filters/client_channel/lb_policy/rls/rls.cc  -fPIC -DPIC -o src/core/ext/filters/client_channel/lb_policy/rls/.libs/rls.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [Makefile:250: src/core/ext/filters/client_channel/lb_policy/rls/rls.lo] Error 1
ERROR: `make' failed

### Anything else we should know about your project / environment?
I need this library to connect to my firestore base.

**Comment by alto-php** [comment]
I don't have the environment to reproduce issue. 
From the log, it appears that g++ had crashed when compiling `rls.cc`.
Can you enable core dump/stack traces so we know where the crash happened?
Is it possible that you upgrade your gcc version and see if it helps?
BTW, what's your hardware configuration, e.g. cores, ram, disk?
