### ISSUE TITLE
centos7 doesn't have sd_is_socket_sockaddr function

### ISSUE THREAD

**Issue by bxlxx** [grpc/grpc#32322]
### What version of gRPC and what language are you using?
v1.52.0

### What operating system (Linux, Windows,...) and version?
centos7

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc7.3

### What did you do?
![image](https://user-images.githubusercontent.com/34093828/217505742-1c7a92fe-e965-4dea-971e-2b3d3e968c20.png)
The sd_is_socket_sockaddr function doesn't exist in libsystemd in centos7

**Comment by yashykt** [comment]
cc @drfloob

**Comment by drfloob** [comment]
This code is intended to be guarded behind `--define=systemd` in bazel builds. Are you using cmake? gRPC is built with `-DHAVE_LIBSYSTEMD` if systemd libraries are found via cmake. If that's the case, our cmake configuration probably needs to check for a library version.

**Comment by xkszltl** [comment]
Regardless of bazel or cmake, CentOS 7 has systemd for sure and it's one of the initial adopter.

**Comment by drfloob** [comment]
`sd_is_socket_sockaddr` was added in [systemd release v233](https://github.com/systemd/systemd/commit/f6f372d2f46ac9be7cbb1ecd8f82f1b3ab669924). Centos7 distributes [libsystemd.so v229](https://centos.pkgs.org/7/centos-x86_64/systemd-libs-219-78.el7.x86_64.rpm.html). This should only be an issue for our cmake build, since bazel does not attempt library auto-detection.

**Comment by drfloob** [comment]
https://github.com/grpc/grpc/pull/32671 might fix it. I don't have a centos7 machine to test on, @bxlxx and @xkszltl would you mind testing the PR to see if it fixes your build?

**Comment by sancelot** [comment]
> #32671 might fix it. I don't have a centos7 machine to test on, @bxlxx and @xkszltl would you mind testing the PR to see if it fixes your build?

I had similar pb with v1.55.0 and systemd v228 (opensuse 42.3 system)  . The PR fixed the problem.

**Comment by shareefj** [comment]
Can also confirm the patch works for me on Centos.  Onto the next error, hey ho.

**Comment by drfloob** [comment]
Thanks for confirming, @shareefj & @sancelot . The fix is merged.
