### ISSUE TITLE
If a large amount of string data is sent over an encrypted connection crashs

### ISSUE THREAD

**Issue by funkelbach** [grpc/grpc#32332]
If a large amount of string data is sent over an encrypted connection from the server to the client, the program crashes when the operation is terminated. Without an encrypted channel, no crash occurs. 

### What version of gRPC and what language are you using?
v1.50.1

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
v141 / Microsoft 17 2022 

### What did you do?
I have modified the example https://github.com/faaxm/exmpl-cmake-grpc.git so that an encrypted connection with public key and private key is created and large string data is sent from the server to the client. When running the programs there is a crash at the end of the program execution. The error seems to occur only in release mode. To show this I attach the code here:

==== Server ====

#include <myproto/address.pb.h>
#include <myproto/addressbook.grpc.pb.h>

#include <grpc/grpc.h>
#include <grpcpp/server_builder.h>

#include <iostream>
#include <filesystem>

class AddressBookService final : public expcmake::AddressBook::Service {
    public:
        virtual ::grpc::Status GetAddress(::grpc::ServerContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response)
        {
            std::cout << "Server: GetAddress for \"" << request->name() << "\"." << std::endl;

            std::string text = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. \
                Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.\
                Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.\
                Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. \
                Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.";

            std::string acctext;
            for (int i = 0; i < 20; i++)
            {
                acctext += text + "\n";
            }

            response->set_name(acctext);

            response->set_zip("12345");
            response->set_country("Superland");
            
            return grpc::Status::OK;
        }
};

int main(int argc, char* argv[])
{
    grpc::ServerBuilder builder;

    std::string key;
    std::string cert;
    std::string root;

    std::filesystem::path cwd = std::filesystem::current_path();
    printf("current path: %s", cwd.string().c_str());
    

    auto f_crt = fopen("../../ssl/server.crt", "r");
    if (f_crt) {
        fseek(f_crt, 0L, SEEK_END);
        auto sz = ftell(f_crt);
        fseek(f_crt, 0L, SEEK_SET);

        std::string str_crt("\0", sz);
        fread_s(str_crt.data(), sz, sizeof(char), sz, f_crt);

        fclose(f_crt);
        cert = str_crt;
    }

    auto f_key = fopen("../../ssl/server.key", "r");
    if (f_key) {
        fseek(f_key, 0L, SEEK_END);
        auto sz = ftell(f_key);
        fseek(f_key, 0L, SEEK_SET);

        std::string str("\0", sz);
        fread_s(str.data(), sz, sizeof(char), sz, f_key);

        fclose(f_key);
        key = str;
    }

    auto f_ca_crt = fopen("../../ssl/ca.crt", "r");
    if (f_ca_crt) {
        fseek(f_ca_crt, 0L, SEEK_END);
        auto sz = ftell(f_ca_crt);
        fseek(f_ca_crt, 0L, SEEK_SET);

        std::string str("\0", sz);
        fread_s(str.data(), sz, sizeof(char), sz, f_ca_crt);

        fclose(f_ca_crt);
        root = str;
    }
	//read("server.key", key);
	//read("ca.crt", root);

    grpc::SslServerCredentialsOptions::PemKeyCertPair keycert =
    {
        key,
        cert
    };

    grpc::SslServerCredentialsOptions sslOps;
    sslOps.pem_root_certs = root;
    sslOps.pem_key_cert_pairs.push_back(keycert);

    builder.AddListeningPort("0.0.0.0:50051", grpc::SslServerCredentials(sslOps));
   // builder.AddListeningPort("0.0.0.0:50051", grpc::InsecureServerCredentials());

    AddressBookService my_service;
    builder.RegisterService(&my_service);

    std::unique_ptr<grpc::Server> server(builder.BuildAndStart());
    server->Wait();
    
    return 0;
}

==== Client ====

#include <myproto/address.pb.h>
#include <myproto/addressbook.grpc.pb.h>

#include <grpc/grpc.h>
#include <grpcpp/create_channel.h>

#include <iostream>

int main(int argc, char* argv[])
{
    std::string key;
    std::string cert;
    std::string root;

    auto f_crt = fopen("../../ssl/client.crt", "r");
    if (f_crt) {
        fseek(f_crt, 0L, SEEK_END);
        auto sz = ftell(f_crt);
        fseek(f_crt, 0L, SEEK_SET);

        std::string str_crt("\0", sz);
        fread_s(str_crt.data(), sz, sizeof(char), sz, f_crt);

        fclose(f_crt);
        cert = str_crt;
    }

    auto f_key = fopen("../../ssl/client.key", "r");
    if (f_key) {
        fseek(f_key, 0L, SEEK_END);
        auto sz = ftell(f_key);
        fseek(f_key, 0L, SEEK_SET);

        std::string str("\0", sz);
        fread_s(str.data(), sz, sizeof(char), sz, f_key);

        fclose(f_key);
        key = str;
    }

    auto f_ca_crt = fopen("../../ssl/ca.crt", "r");
    if (f_ca_crt) {
        fseek(f_ca_crt, 0L, SEEK_END);
        auto sz = ftell(f_ca_crt);
        fseek(f_ca_crt, 0L, SEEK_SET);

        std::string str("\0", sz);
        fread_s(str.data(), sz, sizeof(char), sz, f_ca_crt);

        fclose(f_ca_crt);
        root = str;
    }

    // Setup request
    expcmake::NameQuerry query;
    expcmake::Address result;
    query.set_name("John");

    grpc::SslCredentialsOptions opts =
    {
        root,
        key,
        cert
    };

    // Create a default SSL ChannelCredentials object.
    //auto channel_creds = grpc::SslCredentials(grpc::SslCredentialsOptions());
    auto channel_creds = grpc::SslCredentials(opts);

    // Call
    auto channel = grpc::CreateChannel("localhost:50051", channel_creds);
    std::unique_ptr<expcmake::AddressBook::Stub> stub = expcmake::AddressBook::NewStub(channel);
    
    for (int i = 0; i < 10000; i++)
    {
        grpc::ClientContext context;
        grpc::Status status = stub->GetAddress(&context, query, &result);

        // Output result
        std::cout << "I got:" << std::endl;
        std::cout << "Name: " << result.name() << std::endl;
        std::cout << "City: " << result.city() << std::endl;
        std::cout << "Zip:  " << result.zip() << std::endl;
        std::cout << "Street: " << result.street() << std::endl;
        std::cout << "Country: " << result.country() << std::endl;
    }
    return 0;
}

### What did you expect to see?
No crash!

### What did you see instead?

Ausgelöste Ausnahme: Schreibzugriffsverletzung
"**this**" war "nullptr".

>	[Inlineframe] client.exe!std::_Fetch_add_seq_cst_8(volatile unsigned __int64 *) Zeile 2074	C++
 	[Inlineframe] client.exe!std::_Atomic_fetch_add_8(volatile unsigned __int64 *) Zeile 2116	C++
 	[Inlineframe] client.exe!std::_Atomic_fetch_sub_8(volatile unsigned __int64 *) Zeile 2127	C++
 	[Inlineframe] client.exe!std::atomic_fetch_sub_explicit(std::_Atomic_llong *) Zeile 931	C++
 	[Inlineframe] client.exe!std::_Atomic_llong::fetch_sub(__int64) Zeile 1115	C++
 	[Inlineframe] client.exe!grpc_core::RefCount::Unref() Zeile 159	C++
 	[Inlineframe] client.exe!grpc_core::InternallyRefCounted<grpc_core::ReclaimerQueue::Handle,0>::Unref() Zeile 101	C++
 	client.exe!grpc_core::ReclaimerQueue::Handle::Orphan() Zeile 85	C++
 	[Externer Code]	
 	client.exe!grpc_core::GrpcMemoryAllocatorImpl::Shutdown() Zeile 183	C++
 	[Inlineframe] client.exe!grpc_event_engine::experimental::MemoryAllocator::Reset() Zeile 59	C++
 	client.exe!endpoint_destroy(grpc_endpoint * secure_ep) Zeile 505	C++
 	client.exe!grpc_chttp2_transport::~grpc_chttp2_transport() Zeile 232	C++
 	client.exe!read_action_locked(void * tp, absl::lts_20220623::Status error) Zeile 2450	C++
 	client.exe!grpc_combiner_continue_exec_ctx() Zeile 230	C++
 	client.exe!grpc_core::ExecCtx::Flush() Zeile 72	C++
 	client.exe!grpc_iocp_flush() Zeile 127	C++
 	client.exe!grpc_iomgr_shutdown() Zeile 104	C++
 	client.exe!grpc_shutdown_internal_locked() Zeile 189	C++
 	client.exe!grpc_shutdown() Zeile 222	C++
 	[Inlineframe] client.exe!grpc::GrpcLibraryCodegen::{dtor}() Zeile 57	C++
 	client.exe!grpc::ChannelCredentials::~ChannelCredentials() Zeile 27	C++
 	[Externer Code]	
 	[Inlineframe] client.exe!std::_Ref_count_base::_Decref() Zeile 847	C++
 	[Inlineframe] client.exe!std::_Ptr_base<grpc::ChannelCredentials>::_Decref() Zeile 1120	C++
 	[Inlineframe] client.exe!std::shared_ptr<grpc::ChannelCredentials>::{dtor}() Zeile 1403	C++
 	client.exe!main(int argc, char * * argv) Zeile 192	C++
 	[Externer Code]

**Comment by markdroth** [comment]
Duplicates #29185.
