### ISSUE TITLE
AddListeningPort blocking after update to 1.52.0

### ISSUE THREAD

**Issue by maxlein** [grpc/grpc#32374]
I just updated grpc from 1.41.0 to 1.52.0 and tried to start my software again, but it hangs indefinitely on the function `AddListeningPort` when starting the server at 0.0.0.0:50051.  

```c++
  std::string server_address(fmt::format("0.0.0.0:{}", serverPort));
  service = std::make_unique<grpc::station::StationServiceServer>(transferStationManager);

  grpc::ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  builder.RegisterService(service.get());
  server = builder.BuildAndStart();

  serviceServerActive = true;
```

### What version of gRPC and what language are you using?
1.52.0

### What operating system (Linux, Windows,...) and version?
ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 9.4.0

### What did you do?
I updated from 1.41.0 to 1.52.0.

### What did you expect to see?
The same running application as before.

### What did you see instead?

gRPC server is not starting up.

**Comment by yashykt** [comment]
We've got a bunch of tests that essentially do something very similar. I'm suspecting that there is something else going wrong over here. If you can provide a whole reproduction that we can run ourselves, we could help further.

**Comment by maxlein** [comment]
Looks like it's related to  
- https://github.com/microsoft/vcpkg/pull/12554  
- https://github.com/grpc/grpc/issues/21213  
- https://github.com/grpc/grpc/issues/20690  

I am also looping indefinitely in this tracelist

**Comment by maxlein** [comment]
So I could fix my problem:  
I build gRPC libraries STATICALLY from source, and somehow in version 1.52 this doesn't work anymore.  
Building shared libs solved my problem.

**Comment by b675987273** [comment]
I'm experiencing the same issue as described in this issue. 
run `builder.AddListeningPort`with `grpc::InsecureServerCredentials())` blocked.
```cpp
    ......
    ServerBuilder builder;
    std::cout << "Server builder " << server_address << std::endl;
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    std::cout << "Server listen " << server_address << std::endl;
    builder.RegisterService(&service);
    std::cout << "Server register " << server_address << std::endl;
    ......
```
```bash
$ ./bazel-bin/example/server/async_server
start server demo
Server builder 0.0.0.0:3453
```
but run with `builder.AddListeningPort(server_address, std::shared_ptr<grpc::ServerCredentials>());` 
```bash
$ ./bazel-bin/example/server/async_server
start server demo
Server builder 0.0.0.0:3453
Server listen 0.0.0.0:3453
Server register 0.0.0.0:3453
```

```bash
// WORKSPACE
http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "ec125d7fdb77ecc25b01050a0d5d32616594834d3fe163b016768e2ae42a2df6",
    strip_prefix = "grpc-1.52.1",
    urls = [
        "https://github.com/grpc/grpc/archive/refs/tags/v1.52.1.tar.gz",
    ],
)
```

**Comment by LightSun** [comment]
I met the same problem. and 
'builder.AddListeningPort(server_address, std::shared_ptr<grpc::ServerCredentials>());'  doesn't resolved it
