### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.94.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by mvinit008** [grpc/grpc#32403]
Error: Request cancelled
│
│ with module.log_analytics_workspace.azurerm_log_analytics_workspace.this,
│ on .terraform/modules/log_analytics_workspace/main.tf line 1, in resource "azurerm_log_analytics_workspace" "this":
│ 1: resource "azurerm_log_analytics_workspace" "this" {
│
│ *The plugin.(GRPCProvider).ApplyResourceChange request was cancelled.

Error: The terraform-provider-azurerm_v2.94.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

##[error]Bash exited with code '1'.
Finishing: Terraform Apply

i am facing this issue while executing terraform apply , i tried this terraform-provider-azurerm_v2.98.0_x5 and 2.94 also , means i tried upgrading version also but didnt help

since the error clearly says to reach out plugin's maintainers so i am reaching out

need your input and fix on this

**Comment by yijiem** [comment]
Seems like this is posted to the wrong repo. Closing.
