### ISSUE TITLE
Explicitly disallow nullptr as pointer to rpc response

### ISSUE THREAD

**Issue by Masrepus** [grpc/grpc#32412]
### What version of gRPC and what language are you using?
1.47.0, C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang 14

### What did you do?
Some of our rpcs are only meant for sending messages without receiving a meaningful response, which is why they are defined to return `Empty`. Because of this, when implementing the C++ client, I was not interested in the `Empty` response object and thought passing `nullptr` as the pointer to the response object to be filled would be fine.

### What did you expect to see?
The rpc request is executed as usual and the client call returns when it is complete. In case using `nullptr` for the response is not allowed, this will be indicated by any kind of error, log message or static assert failure.

### What did you see instead?
The request worked, so I thought passing `nullptr` here was indeed supported behavior, but a strange issue appeared: While the rpc arrived at the server, the client side call would hang forever. I initially thought it was some server related issue and thus added a timeout policy, but it then turned out that if instead of `stub->MyRequest(&context, msg, nullptr)` you do `stub->MyRequest(&context, msg, &response)` with `response` being a dummy `google::protobuf::Empty` object, the request works as expected.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
It's not safe to pass nullptr for the response message.  That's a misuse of the API.

**Comment by Masrepus** [comment]
I don't think it would need to be a runtime check. Sure, in more complex scenarios you could pass a pointer you got from somewhere else, where you can't know statically that it's non null, but what I did is really just passing `nullptr` straight to the method, because nothing indicated that would be an issue. And that's a situation that could definitely be detected statically. Or if anything you could add an explicit warning to the docs, if a dedicated check in code is not feasible.
