### ISSUE TITLE
gRPC cmake build fails with ndk

### ISSUE THREAD

**Issue by liyuenan2333** [grpc/grpc#32422]
### What version of gRPC and what language are you using?
gPRC version: v1.50.0
language: c++

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.2 x86_x64

### What runtime / compiler are you using (e.g. python version or version of gcc)
android-ndk-r25c

### What did you do?
build gprc with ndk

### What did you expect to see?
build successfully, because I'm doing a c++ project that need to run on android.

### What did you see instead?
[ 99%] Linking CXX static library libgrpc++.a
[ 99%] Built target grpc++
make[2]: *** No rule to make target '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc'.  Stop.
make[2]: *** No rule to make target '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'gens/src/proto/grpc/channelz/channelz.grpc.pb.cc'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1223: CMakeFiles/grpc++_reflection.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1305: CMakeFiles/grpcpp_channelz.dir/all] Error 2

### Anything else we should know about your project / environment?
my build instruction:
~/wksp/grpc/cmake/android_build$ cmake ../.. -DgRPC_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_TOOLCHAIN_FILE=/lhome/user/wksp/Android/android-ndk-r25c/build/cmake/android.toolchain.cmake  -DANDROID_ABI=arm64-v8a
BTW:
I used another ndk version(r23c), but got the same result. I also tried to build a shared library(-DBUILD_SHARED_LIBS=ON), but got another error.

**Comment by yashykt** [comment]
@wenbozhu Can you help redirect this please?

**Comment by yashykt** [comment]
Please take a look at https://github.com/grpc/grpc/tree/master/examples/android/helloworld in the mean time

**Comment by veblush** [comment]
I guess this is because Android cmake build cannot build protoc so building it first would solve the issue like [this](https://github.com/grpc/grpc/blob/58ea2e00fcc2502c06115f5d57c864c828826243/tools/internal_ci/linux/grpc_android_in_docker.sh#L24-L31).

**Comment by Nathan-M-code** [comment]
Hello @veblush ,
I am facing the same issue,
My first cmake command was:
```
cmake -S .. -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK="C:/Users/m/AppData/Local/Android/Sdk/ndk/25.2.9519653" -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="C:/Users/m/AppData/Local/Android/Sdk/ndk/25.2.9519653/sources/third_party/grpc" -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -G "MinGW Makefiles"
```
All is until:
```
[ 82%] Linking CXX executable protoc
[ 82%] Built target protoc
mingw32-make[2]: *** No rule to make target '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc'.  Stop.
mingw32-make[1]: *** [CMakeFiles\Makefile2:1802: CMakeFiles/grpc++_reflection.dir/all] Error 2
mingw32-make: *** [Makefile:155: all] Error 2
```

So I just compiled protoc and grpc_cpp_plugin first with succes like you said:
```
>cmake --build . --target protoc
...
[100%] Built target protoc
```
```
>cmake --build . --target grpc_cpp_plugin
...
[100%] Built target grpc_cpp_plugin
```
But I still have the same error with:
```
>cmake --build . --target install
...
[ 82%] Built target protoc
mingw32-make[2]: *** No rule to make target '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc'.  Stop.
mingw32-make[1]: *** [CMakeFiles\Makefile2:1802: CMakeFiles/grpc++_reflection.dir/all] Error 2
mingw32-make: *** [Makefile:155: all] Error 2
```

Do I need to change the cmake generation to let it know that it doesn't need to build protoc and grpc_cpp_plugin ?

**Comment by xuanvinh1997** [comment]
> Hello @veblush , I am facing the same issue, My first cmake command was:
> 
> ```
> cmake -S .. -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK="C:/Users/m/AppData/Local/Android/Sdk/ndk/25.2.9519653" -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="C:/Users/m/AppData/Local/Android/Sdk/ndk/25.2.9519653/sources/third_party/grpc" -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -G "MinGW Makefiles"
> ```
> 
> All is good until:
> 
> ```
> [ 82%] Linking CXX executable protoc
> [ 82%] Built target protoc
> mingw32-make[2]: *** No rule to make target '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc'.  Stop.
> mingw32-make[1]: *** [CMakeFiles\Makefile2:1802: CMakeFiles/grpc++_reflection.dir/all] Error 2
> mingw32-make: *** [Makefile:155: all] Error 2
> ```
> 
> So I just compiled protoc and grpc_cpp_plugin first with succes like you said:
> 
> ```
> >cmake --build . --target protoc
> ...
> [100%] Built target protoc
> ```
> 
> ```
> >cmake --build . --target grpc_cpp_plugin
> ...
> [100%] Built target grpc_cpp_plugin
> ```
> 
> But I still have the same error with:
> 
> ```
> >cmake --build . --target install
> ...
> [ 82%] Built target protoc
> mingw32-make[2]: *** No rule to make target '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc'.  Stop.
> mingw32-make[1]: *** [CMakeFiles\Makefile2:1802: CMakeFiles/grpc++_reflection.dir/all] Error 2
> mingw32-make: *** [Makefile:155: all] Error 2
> ```
> 
> Do I need to change the cmake generation to let it know that it doesn't need to build protoc and grpc_cpp_plugin ?

This might be late, but to cross-compile for Android, you need to compile grpc_cpp_plugin on the host machine (not for Android) first.

If you don't want to add it to the PATH, you can modify grpc/CMakeLists.txt as follows:

cmake
Copy code
if(CMAKE_CROSSCOMPILING)
  find_program(_gRPC_CPP_PLUGIN grpc_cpp_plugin PATHS ${_gRPC_CPP_PLUGIN_EXECUTABLE} NO_DEFAULT_PATH)
else()
Then, you can pass _gRPC_CPP_PLUGIN_EXECUTABLE into the build command with -D_gRPC_CPP_PLUGIN_EXECUTABLE=....
