### ISSUE TITLE
Alarm::Set, when call more than once successtively, it abort

### ISSUE THREAD

**Issue by Hankin-Liu** [grpc/grpc#32472]
### What version of gRPC and what language are you using?
1.28.1

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc g++ 4.8.5

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

#include <grpcpp/grpcpp.h>
#include <grpcpp/alarm.h>

class Test
{
public:
    void start()
    {
        ::grpc::CompletionQueue* cq = new ::grpc::CompletionQueue();
        ::grpc::Alarm alarm_{};
        alarm_.Set(cq, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
        alarm_.Set(cq, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
        alarm_.Set(cq, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
        alarm_.Set(cq, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
        alarm_.Set(cq, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
        alarm_.Set(cq, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
    }
};

int main()
{
Test t;
t.start()
return 0;
}

### What did you expect to see?
Alarm::Set is running without abort.
my purpose is pushing data into completion queue very fast.

### What did you see instead?
the second Set is abort. it failed in src/core/lib/iomgr/timer_generic.cc:132 in function add_to_ht, the error log is "Duplicate timer (%p) being added. Closure: (%p), created at: ............

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by drfloob** [comment]
Alarms can only be Set again after they have either fired or been cancelled, a single Alarm cannot be used multiple times concurrently. For valid usage examples, take a look at the alarm tests here: https://github.com/grpc/grpc/blob/a500d2448027fb31b0cb00110857655ea6f82ab6/test/cpp/common/alarm_test.cc
