### ISSUE TITLE
Status(StatusCode="Internal", Detail="Failed to deserialize response message.")

### ISSUE THREAD

**Issue by khteh** [grpc/grpc#32478]
### What version of gRPC and what language are you using?
C#
```
    <PackageReference Include="Google.Protobuf" Version="3.21.12" />
    <PackageReference Include="Grpc.Net.Client" Version="2.51.0" />
    <PackageReference Include="Grpc.Tools" Version="2.51.0">
```

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
No error

### What did you see instead?
`Status(StatusCode="Internal", Detail="Failed to deserialize response message.")`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by tonydnewell** [comment]
@khteh This needs to be asked in the grpc-dotnet repository as you are using Grpc.Net.Client: https://github.com/grpc/grpc-dotnet/issues

Also there isn't enough information to diagnose you problem. Please provide more details such as example code that reproduces your problem.
