### ISSUE TITLE
Support using client and server with existing FDs

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#3250]
When communicating with a child process, it can be really useful to setup the unix domain socket before forking(). It would be nice for C core to support providing existing FDs.

I understand that this was already planned. I'm aware of some users who would be eagerly awaiting the feature.

**Comment by gillwang** [comment]
Thanks for the post.

It would be really helpful to our project if this feature is supported in both C++ and Java.

**Comment by ctiller** [comment]
If anyone is looking for a self contained starter project in core I'd be happy to work with them to build this.

**Comment by xyzzyz** [comment]
Craig, could you outline the steps needed to implement this? I'm interested in what you think the API should look like, and how to plug it into existing framework.

**Comment by ctiller** [comment]
For API's, I'd suggest:

// mirroring grpc_insecure_channel_create -- target would be useful but not
necessary -- purely as an indication of a name for this channel
grpc_channel *grpc_insecure_channel_create_from_fd(const char *target, int
fd, const grpc_channel_args *args);

// add a new incoming connection to a server
void grpc_server_add_insecure_channel_from_fd(grpc_server *server, int fd);

The client side implementation would involve:
- create a tcp endpoint around the fd
- create a chttp2 transport around that endpoint
- create a channel via the internal create channel API around that
transport (of type GRPC_CLIENT_DIRECT_CHANNEL)
- return said channel

Server side would be similar:
- create a tcp endpoint around the fd
- create a chttp2 transport around that endpoint
- call grpc_server_setup_transport on that transport

**Comment by xyzzyz** [comment]
I think this can be closed now.
