### ISSUE TITLE
question about g_current_thread_worker

### ISSUE THREAD

**Issue by skyshaw** [grpc/grpc#3252]
I only see `g_current_thread_worker` in 2 places, one is https://github.com/grpc/grpc/blob/master/src/core/iomgr/pollset_posix.c#L57, another is https://github.com/grpc/grpc/blob/master/src/core/iomgr/pollset_posix.c#L102. So, It seems `gpr_tls_get(&g_current_thread_worker)` will always be zero since it's not assigned anywhere. 
Isn't `gpr_tls_get(&g_current_thread_worker) != (gpr_intptr)specific_worker` always true in the second place? Am I missing something?

**Comment by vjpai** [comment]
I think that you're right; it does seem like those two lines of code are vestiges now and are not actually used. I'll send in a PR to address this.

**Comment by vjpai** [comment]
After discussion with @ctiller , it was decided that this variable will indeed be set in the near future and that will soon become no longer vestigial. The point is to do nothing rather than kick oneself to wakeup.

**Comment by billidani7** [comment]
When I run the app I get this error

`subchannel_index.c:59] assertion failed: gpr_tls_get(&subchannel_index_exec_ctx) == 0`

**Comment by makdharma** [comment]
Should be fixed with Properly initialize TLS var #5390
<https://github.com/grpc/grpc/issues/5390>
