### ISSUE TITLE
Deprecate warnings from asyncio.get_running_loop in python 3.10+

### ISSUE THREAD

**Issue by rickyyx** [grpc/grpc#32526]
### What version of gRPC and what language are you using?
grpcio=1.50.0

### What operating system (Linux, Windows,...) and version?
Linux 

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10 

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Calling  `init_grpc_aio()` yields deprecation warnings. 

```python
from grpc import aio as aiogrpc
aiogrpc.init_grpc_aio()
```
yields
```
<stdin>:1: DeprecationWarning: There is no current event loop
```

### What did you expect to see?
No warnings 

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by XuanWang-Amos** [comment]
Thanks for bringing this to our attention, I'm able to see the warning in our unit test: `outside_init_test`, we'll fix this soon.
