### ISSUE TITLE
gRPC server sockets going into CLOSE_WAIT state forever on frequent connection/disconnection through gNMI sessions

### ISSUE THREAD

**Issue by ashu-ciena** [grpc/grpc#32538]
### What version of gRPC and what language are you using?
gRPC 1.51.1, C++

### What operating system (Linux, Windows,...) and version?
Linux 5168 5.10.147-oneos-standard https://github.com/grpc/grpc/pull/1 SMP PREEMPT Mon Nov 21 04:26:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)

### What did you do?
Steps:
1. Open 10 gRPC session by sending a gNMI subscription request from a gNMI client (like go based gnmi_cli, gnmic) 
2. Let the data flow between client and server for 10 sec (This step may not be required)
3. Terminate all the 10 gRPC sessions in one go like (killall gnmic) 
4. Repeat the step 1 to 3 for few hours. 

### What did you expect to see?
1. I expected all the sockets to get cleaned up everytime the connections are terminated. No residuals present and no socket in CLOSE_WAIT state.  
2. New gRPC sessions and in turn gNMI subscriptions should seemlessly work as it used to work in the beginning of this experiment.

### What did you see instead?
1. Initially the cleanup of server sockets was working fine at gRPC server side. I could only see a listening socket at gRPC server side waiting for new requests once all the previous requests were terminated as described in above steps.
2.  After running this in a script for few hours, the gRPC server stopped acknowledging requests and instead threw TCP accept failure log as below:

<155>1 2023-03-03T05:09:03.289565+00:00 telemetry [tcp_server_posix.cc:205] Failed accept4: Too many open files

3. All the subsequent connections started going into socket CLOSE_WAIT state. 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

### Anything else we should know about your project / environment?
Go based gnmi_cli used as client to send subscription request - https://github.com/openconfig/gnmi/blob/master/cmd/gnmi_cli/gnmi_cli.go

Alternatively, you can use gnmic tool from here - https://gnmic.kmrd.dev 

Sample gNMI subscription request is as below:
gnmic subscribe -e "proto" -a <Device IP>:9339 -u <username> -p <password> --tls-key <key.pem> --tls-cert <cert.pem> --skip-verify sub --path "<gNMI sensor Path>"

**Comment by drfloob** [comment]
I think we'd need to see a minimum reproducible example without gnmi involved to determine why the server is not closing the connections after the clients have left the conversation.

Regarding:
> Failed accept4: Too many open files

If this occurs after 1 to 3 hours, it may be interesting for you to see what `lsof` and `netstat` have to say about the state of the server during the first 30 minutes or so. You can try something like `watch -n 30 'netstat -ntlp <SERVER_PID>'` or maybe a command that produces something you can graph, like `while true; do sleep 10; netstat -ntlp <SERVER_PID> 2>/dev/null | wc -l >> /tmp/foo; done`

**Comment by drfloob** [comment]
Thank you for the data. I'm not sure the issues are the same, despite the similar symptoms. For example, earlier versions of gRPC had an fd leak with the `epollex` poller, which was removed in v1.46. It may be too late to diagnose some of those years-old issues.

Without a minimum reproduction case to look at for your instance, it might be hard to determine why there's an fd leak in your application. It could be a usage issue, something preventing endpoints from being properly destroyed, or possibly a new channel is being created every time (inadvisable, partially because of internal caching of established connections). It could also be a gRPC bug.

You may also want to consider a heap profile to see what objects are being leaked, and setting a lower fd limit on the process to trigger the problem sooner.

**Comment by ashu-ciena** [comment]
After lot of testing in different scenarios, found an issue in gnmi application code where sessions are leaking, in a race condition.  After fixing the same, not seeing this issue, so closing this issue now.
Thank you everyone for taking a look.
