### ISSUE TITLE
compile error using gcc5.2 in mingw

### ISSUE THREAD

**Issue by allspace** [grpc/grpc#3254]
Got the following compile error (workaround is to remove "-Werror" from Makefile)

[C]       Compiling src/core/support/string_win32.c
src/core/support/string_win32.c: In function 'gpr_tchar_to_char':
src/core/support/string_win32.c:103:10: error: implicit declaration of function 'gpr_strdup' [-Werror=implicit-function-declaration]
   return gpr_strdup(input);
          ^
src/core/support/string_win32.c:103:10: error: return makes pointer from integer without a cast [-Werror=int-conversion]
src/core/support/string_win32.c: In function 'gpr_char_to_tchar':
src/core/support/string_win32.c:107:10: error: return makes pointer from integer without a cast [-Werror=int-conversion]
   return gpr_strdup(input);
          ^
cc1.exe: all warnings being treated as errors
Makefile:2847: recipe for target 'objs/opt/src/core/support/string_win32.o' failed
make: **\* [objs/opt/src/core/support/string_win32.o] Error 1

**Comment by emmenlau** [comment]
Same here with updated MinGW64 gcc 5.3.0 on MSYS2 Windows 7.
