### ISSUE TITLE
Generate CLI client from GRPC protocol file

### ISSUE THREAD

**Issue by ningziwen** [grpc/grpc#32557]
### Is your feature request related to a problem? Please describe.
Hi. I’m new to GRPC and I’m trying to find a framework that can generate the SDK of multiple languages and the CLI from one protocol file, similar to AWS json protocol: https://smithy.io/1.0/spec/aws/aws-json-1_0-protocol.html. GRPC can only generate language specific client (similar to SDK) but not CLI today.

### Describe the solution you'd like
Generate CLI client from GRPC protocol file. For example, the hello-world protocol (https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.proto) can generate a CLI application that has this command support.

```
$ greeter say-hello --name “Ziwen"
```
There can be a global config or env var to point the server endpoint. The command will call the GRPC service running in the endpoint. If the service is running, it will return “Hello Ziwen”.

### Describe alternatives you've considered
I know there are multiple tools that can call the GRPC service in terminal, but they are different with generating an independent CLI tool, so can't support the same use cases.

### Additional context
Did GRPC community have this discussion before? Are there any blockers or scope concerns of having this feature in GRPC? I’m happy to contribute to it if GRPC has the interest, and also interested to learn the concern if not.

**Comment by yashykt** [comment]
I think https://github.com/fullstorydev/grpcurl is what you are looking for :)

**Comment by ningziwen** [comment]
@yashykt 
Looking into the [documentation](https://github.com/fullstorydev/grpcurl#invoking-rpcs), it is different with the request of this issue. 

Grpcurl still relies on a `grpcurl ` cli
```
grpcurl -d @ grpc.server.com:443 my.custom.server.Service/Method <<EOM
{
  "id": 1234,
  "tags": [
    "foor",
    "bar"
  ]
}
EOM
```

The issue requests generating a independent CLI
```
$ greeter say-hello --name “Ziwen"
```

Even if they both call GRPC service in terminal, the use cases can be much different. The service owner may directly distribute the generated **independent** CLI to users to let them use the service with seamless CLI experience. But it is not typical to ask their users to use a third party CLI to support it.
