### ISSUE TITLE
Grpc.Tools 2.52.0 nuget package is not working with MacOS 11

### ISSUE THREAD

**Issue by Kielek** [grpc/grpc#32558]
### What version of gRPC and what language are you using?

.NET/C# - Grpc.Tools nuget package 2.52.0.

### What operating system (Linux, Windows,...) and version?

MacOS 11 - GitHub runner image https://github.com/actions/runner-images/blob/ed49bcd54387141935c27c3350aafdb5ccfcf747/images/macos/macos-11-Readme.md

### What runtime / compiler are you using (e.g. python version or version of gcc)

See https://github.com/actions/runner-images/blob/ed49bcd54387141935c27c3350aafdb5ccfcf747/images/macos/macos-11-Readme.md

### What did you do?

Generate .NET classes while building project to be able to act as a GRPC server.

The easiest way to reproduce is to execute `nuke Workflow` on the MacOS system when you checkout https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/dependabot/nuget/test/Grpc.Tools-2.52.0

### What did you expect to see?

Compilation passed

### What did you see instead?

```log
  12:26:18 [INF] > /Users/runner/.dotnet/dotnet build /Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj --configuration Release --no-restore
  12:26:19 [DBG] MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
  12:26:20 [DBG]   OpenTelemetry.AutoInstrumentation -> /Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/bin/Release/net6.0/OpenTelemetry.AutoInstrumentation.dll
  Error: dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:20 [ERR] dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:20 [DBG]   Referenced from : error : /Users/runner/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc (which was built for Mac OS X 12.5) [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:20 [DBG]   Expected in : error : /usr/lib/libc++.1.dylib [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:20 [DBG]    in /Users/runner/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc
  Error: dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [ERR] dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [DBG]   Referenced from : error : /Users/runner/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc (which was built for Mac OS X 12.5) [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [DBG]   Expected in : error : /usr/lib/libc++.1.dylib [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [DBG]    in /Users/runner/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc
  12:26:21 [DBG] 
  12:26:21 [DBG] Build FAILED.
  12:26:21 [DBG] 
  Error: dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:21 [ERR] dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:21 [DBG]   Referenced from : error : /Users/runner/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc (which was built for Mac OS X 12.5) [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  12:26:21 [DBG]   Expected in : error : /usr/lib/libc++.1.dylib [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net6.0]
  Error: dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [ERR] dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [DBG]   Referenced from : error : /Users/runner/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc (which was built for Mac OS X 12.5) [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
  12:26:21 [DBG]   Expected in : error : /usr/lib/libc++.1.dylib [/Users/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/IntegrationTests.csproj::TargetFramework=net7.0]
```

Full log: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/4343269099/jobs/7585108122

### Anything else we should know about your project / environment?

Exactly the same code is working correctly with Grpc.Tools 2..51.0.
Changing system to MacOS 12 https://github.com/actions/runner-images/blob/ed49bcd54387141935c27c3350aafdb5ccfcf747/images/macos/macos-12-Readme.md also fix the issue. It is not an option for now, we need to support MacOS 11.

PR created by dependabot to update Grpc.Tools: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2279

**Comment by tonydnewell** [comment]
@jtattermusch Can you look at this MacOS error with `protoc` in Grpc.Tools 2.52.0

**Comment by JamesNK** [comment]
I have also since this error:

```
/Users/vs/GrpcGreeterClient/GrpcGreeterClient.csproj
dyld(0,0): Error: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from(0,0): Error: /Users/vs/.nuget/packages/grpc.tools/2.52.0/tools/macosx_x64/protoc (which was built for Mac OS X 12.5)
  Expected in(0,0): Error: /usr/lib/libc++.1.dylib
```

**Comment by jtattermusch** [comment]
I think this might be caused by our recent switch MacOS workers (which are used for building the artifacts) from MacOS Mojave (10.14) to MacOS Monterey (12).
Looks like the binaries produced by our build are missing the flags to provide binaries that are backward compatible with still-supported MacOS versions (e.g. Big Sur -> 11).
This is still a theory but it seems likely.

**Comment by jtattermusch** [comment]
This is how the macos protoc binaries get built:
https://github.com/grpc/grpc/blob/cd4154f21d80b278a08f5de2a3450a0150744c69/tools/run_tests/artifacts/artifact_targets.py#L316-L324

**Comment by Kielek** [comment]
@jtattermusch, do you need any additional information how to reproduce issue?

**Comment by MMtwo** [comment]
Grpc.Tools 2.53.0 nuget package is not working with MacOS 11.6 and MacOS 12.4, but working with MacOS 13.2.1.

**Comment by jtattermusch** [comment]
What's strange is that we apply `-mmacosx-version-min=10.10` when build protoc and grpc_csharp_plugin on Mac:

https://github.com/grpc/grpc/blob/f9085e4496eebf1bf1c4dfdcbf641d673c462c48/tools/run_tests/artifacts/artifact_targets.py#L96
https://github.com/grpc/grpc/blob/f9085e4496eebf1bf1c4dfdcbf641d673c462c48/tools/run_tests/artifacts/artifact_targets.py#L318

Perhaps we should try building with static libc++?

**Comment by jtattermusch** [comment]
I tried with a protoc binary builds at HEAD:
```
$ otool -L protoc 
protoc:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.32.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

**Comment by Kielek** [comment]
Version 2.56 - still the same issue.

**Comment by jtattermusch** [comment]
I think this boils down to statically linking libc++  into the protoc binary, which should make the binary more portable.

But I can't seem to be able to figure out the right build arguments to link libc++ statically in apple clang (see https://github.com/grpc/grpc/pull/33579 that still doesn't work). Any pointers would be welcome.

**Comment by hknielsen** [comment]
We are also hitting this issue after trying to update the Grpc.Tools package.

@jtattermusch - im no expert here, but did you also add `-Wunguarded-availability` so that your only using available api.
https://stackoverflow.com/questions/52977581/why-isnt-mmacosx-version-min-10-10-preventing-use-of-a-function-tagged-as-star

**Comment by hknielsen** [comment]
Alternatively, any chance we can roll back on the agents osx version?

**Comment by VitaliyPasko** [comment]
Hello! I don’t understand how to fix it? Help me please.

**Comment by tonydnewell** [comment]
@apolcyn @JamesNK @jtattermusch 
I've created a speculative fix in PR https://github.com/grpc/grpc/pull/34597

Caveat: I don't have access to MacOS computer so I cannot test. I'm relying on the CI build to do a certain level of testing, but that won't test running on an older OS version. Is anyone able to test this?

I've added the environment variable `MACOSX_DEPLOYMENT_TARGET` which some people say is more reliable than the `-mmacosx-version-min` option since it makes sure that the entire toolchain is aware of the target version. I don't know if this is true as I can't find any reliable and definitive documentation.

I've also added `-Wunguarded-availability` as suggested above so that we would get a compiler warning if using a newer API on an older target.

Also, @hknielsen suggests in https://github.com/grpc/grpc/pull/34366 that the lowest version to target should be 10.13. Is that correct? I've not made that change here.  What version should be support?

**Comment by tonydnewell** [comment]
Also, I've read that Apple discourage linking to static libc++ and don't ship a prebuilt static library.

**Comment by Kielek** [comment]
@tonydnewell, sorry for late response (I am checking the issue while closing dependabot information about new, failing version of GrpcTool), any chance to take final artifact including you fix as a nuget package?

With this I can test it in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation pipeline.

**Comment by mikhailshilkov** [comment]
Do we know if this is a build-time only problem (can't build anything referencing Grpc .net on macOS 11), or also a runtime problem (won't run on macOS 11 if built on macOS 12+)?

**Comment by Kielek** [comment]
MacOS11 is EOL and GitHub Actions will drop support, June 28. Closing this one.
