### ISSUE TITLE
Support .pyi generation in py_proto_library

### ISSUE THREAD

**Issue by ferstlf** [grpc/grpc#32564]
Hi!

### Is your feature request related to a problem? Please describe.
The general problem: When working with protos/gRPC and Bazel in an IDE i'd like to have proper language support, i.e. import resolution, auto-completion etc. should work for automatically generated proto classes. 

With Bazel, import resolution is a bit tricky, but essentially I can configure in my IDE/language server the relevant Python import paths inside Bazels temporary folders (e.g. `bazel-bin` or `bazel-bin/external/com_github_grpc_grpc`). However, the .py files generated by `protoc` use Metaclasses and language servers such as Pylance in VS Code do not understand these to offer proper auto-completion and more. 

Since [Protobuf v3.20.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0), `protoc` is natively able to generate python stubs (.pyi) with the `--pyi_out` flag. If one generates a *_pb2.pyi file for every *_pb2.py file this should be understood by most language servers automatically and things like auto-completion and static type-checking with proto classes should just work  (I can at least confirm for Pylance/VS Code).

### Describe the solution you'd like
We use [gRPC's `py_proto_libary` rule](https://github.com/grpc/grpc/blob/cd4154f21d80b278a08f5de2a3450a0150744c69/bazel/python_rules.bzl#L154) in our Bazel workspace and also expect our users to use it in their workspaces (which depend on our workspace). It would be great if the `py_proto_libary` rule would generate .pyi files in addition to .py files - either by default (since it is not very costly) or enabled via a boolean flag on the `py_proto_libary` rule.

It should be as simple as adding the `--pyi_out` flag to the `protoc` params [here](https://github.com/grpc/grpc/blob/cd4154f21d80b278a08f5de2a3450a0150744c69/bazel/python_rules.bzl#L67) and then making sure that `py_proto_libary` correctly includes or excludes the additionally generated .pyi files from the output files, runfiles and PyInfo which it declares as its output.

### Additional context

Let me know if this would make sense to you. I already have this working as a patch to our Bazel import of the gRPC workspace. I could try to turn this into a PR myself.

**Comment by XuanWang-Amos** [comment]
Thanks for raising this, we agree that this change make sense and actually there is already [a PR created for this](https://github.com/grpc/grpc/pull/31791/files) but tests [are still missing](https://github.com/grpc/grpc/pull/31791#issuecomment-1423245116). If anyone is able to create those tests we can get this unblocked.

**Comment by ferstlf** [comment]
Ah I missed that PR, thanks. I will see if I can get some tests for working and would then create a PR of my own.

**Comment by gnossen** [comment]
Fixed by https://github.com/grpc/grpc/pull/32872

**Comment by nioan-aux** [comment]
In case someone wants to try the current HEAD in main that seems to be supporting this already. You can override the current version with that using the following in MODULE.bazel:

```
bazel_dep(name = "rules_proto_grpc", version = "5.0.1")

git_override(
    module_name = "rules_proto_grpc",
    remote = "https://github.com/rules-proto-grpc/rules_proto_grpc.git",
    commit = "d17b5b16c8b12143c6f1b78dabd6bbc228e89b58",
    strip_prefix = "modules/core",
)


bazel_dep(name = "rules_proto_grpc_python", version = "5.0.1")

git_override(
    module_name = "rules_proto_grpc_python",
    remote = "https://github.com/rules-proto-grpc/rules_proto_grpc.git",
    commit = "d17b5b16c8b12143c6f1b78dabd6bbc228e89b58",
    strip_prefix = "modules/python",
)
```
