### ISSUE TITLE
gRPC 1.15.1: gRPC channels blocking indefinitely and not respecting deadlines on network disconnect

### ISSUE THREAD

**Issue by babuveld** [grpc/grpc#32562]
We are using grpc 1.15.1 and seeing the same issue as reported in https://github.com/grpc/grpc/pull/15983, we applied the patch from https://github.com/grpc/grpc/pull/15983/files and it didn't solve the issue, also when we checked the latest gRPC code, we didn't find the code from the patch.

Can you please help pointing the correct patch to apply for gRPC-1.15.1 to solve the issue reported in https://github.com/grpc/grpc/pull/15983

**Comment by yashykt** [comment]
https://github.com/grpc/grpc/pull/16419 was the real fix here
