### ISSUE TITLE
mac m1 build failed with src/core/lib/channel/channel_stack.cc:193:9

### ISSUE THREAD

**Issue by cgyFight** [grpc/grpc#32579]
### What version of gRPC and what language are you using?
v1.9.1

### What operating system (Linux, Windows,...) and version?
mac arm64  Apple M1 Pro 12.2 (21D49)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.3.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

brew install autoconf automake libtool shtool

LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make

### What did you expect to see?

build succe

### What did you see instead?
[MAKE]    Generating cache.mk
[CXX]     Compiling src/core/lib/channel/channel_stack.cc
src/core/lib/channel/channel_stack.cc:193:9: error: variable 'user_data' set but not used [-Werror,-Wunused-but-set-variable]
  char* user_data;
        ^

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by cgyFight** [comment]
when i use cmake, the err like this:

[ 87%] Built target grpc++_unsecure
[ 87%] Building C object CMakeFiles/grpc_csharp_ext.dir/src/csharp/ext/grpc_csharp_ext.c.o
[ 87%] Linking CXX shared library libgrpc_csharp_ext.dylib
ld: warning: pointer not aligned at address 0x236B86 (_grpc_lb_v1_ClientStats_fields + 6 from libgrpc.a(load_balancer.pb.c.o))
ld: warning: pointer not aligned at address 0x236BF6 (_grpc_lb_v1_LoadBalanceRequest_fields + 20 from libgrpc.a(load_balancer.pb.c.o))
ld: warning: pointer not aligned at address 0x236C66 (_grpc_lb_v1_LoadBalanceResponse_fields + 20 from libgrpc.a(load_balancer.pb.c.o))
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cgyFight** [comment]
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.3.0
Thread model: posix

**Comment by drfloob** [comment]
gRPC v1.9.1 was released in 2018, 2 years before the M1 was launched. Please try a modern gRPC release from https://github.com/grpc/grpc/releases
