### ISSUE TITLE
getStatus() function of ServerStreamingCall hangs until deadline

### ISSUE THREAD

**Issue by Matt-Woz** [grpc/grpc#32591]
### What version of gRPC and what language are you using?
GRPC 1.42 (And happens on 1.39 too), PHP 8.2.3

### What operating system (Linux, Windows,...) and version?
(M1) MacOS 12.5.1 Monterey

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0

### What did you do?
I ran into this problem on my own Client, but was able to reproduce it route-guide example, using a Go GRPC server and PHP client and:

adding a `$status = $call->getStatus()` [here](https://github.com/grpc/grpc/blob/v1.52.0/examples/php/route_guide/route_guide_client.php#L95), The same thing happens when I explicitly return an error by importing `google.golang.org/grpc/codes` and `google.golang.org/grpc/status`, and adding e.g.`return status.Errorf(codes.Canceled, "Cancelled")` [here](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/server/server.go#L76)

### What did you expect to see?
Either a STATUS_OK during a success, or another relevant error status when that is returned

### What did you see instead?

Nothing - It hangs infinitely/until it hits the deadline

**Comment by stanley-cheung** [comment]
gRPC version 1.42 was released 1.5 years ago. PHP 8.2 wasn't released then. Please try the latest version of the gRPC PECL extension 1.52.1 and see if the issue still persists?

**Comment by Matt-Woz** [comment]
Sadly the issue still persists with grpc extension 1.52.1:
```
Package   Version State
grpc      1.52.1  stable
```
And the latest release of the library on Packagist (1.52.0)

**Comment by alto-php** [comment]
Status only available after the streaming finished, can you try if it works by moving the getStatus call after the foreach?
