### ISSUE TITLE
Calling a service from another service in NodeJS crashes with segmentation fault

### ISSUE THREAD

**Issue by iam-johntan** [grpc/grpc#3259]
Hello,

I'm currently writing a NodeJS grpc service that calls into another grpc service.  The call to the other service results in a crash - a segmentation fault.  I'm assuming this is supposed to work.

I can reproduce this in the example code using the math_server and stock_server found here:
https://github.com/grpc/grpc/tree/release-0_10/src/node/examples

I modified mathDiv in math_server.js, so that it first calls getLastTradePrice on the stock service before returning the division result:

```
function mathDiv(call, cb) {
    var req = call.request;
    var StockClient = require('./stock_client');
    var stockClient = new StockClient('localhost:50051');

    stockClient.getLastTradePrice({symbol: 'GOOG'}, function (error, response) {
        console.log(error || response);

        // Unary + is explicit coersion to integer
        if (+req.divisor === 0) {
            cb(new Error('cannot divide by zero'));
        } else {
            cb(null, {
                quotient: req.dividend / req.divisor,
                remainder: req.dividend % req.divisor
            });
        }
    });
}
```

I then run the tests in math_client_test.js found here:
https://github.com/grpc/grpc/blob/release-0_10/src/node/test/math_client_test.js

The output looks like this:
```
> grpc@0.10.1 test /Users/johntan/Development/test-project/node_modules/grpc
> node ./node_modules/mocha/bin/mocha && npm run-script lint

child_process: customFds option is deprecated, use stdio instead.

  Math client

Server starting
Serving /math.Math/Div
Serving /math.Math/DivMany
Serving /math.Math/Fib
Serving /math.Math/Sum
{ price: 88, symbol: 'GOOG' }

sh: line 1: 75597 Segmentation fault: 11  node ./node_modules/mocha/bin/mocha
npm ERR! Test failed.  See above for more details.
```

This is not a practical example, but it demonstrates the issue.  I installed the grpc node package using the brew script as per the instructions here.  npm reports this version as <b>grpc 0.10.1.</b>

Has anyone else run into this problem?  Any ideas on how to debug or fix this?

Thanks!
John

PS.  I also posted this here (wasn't sure where to get help):
https://groups.google.com/forum/#!topic/grpc-io/6eBjSxsgQxM

**Comment by murgatroid99** [comment]
[This mailing list post](https://groups.google.com/forum/#!topic/grpc-io/6eBjSxsgQxM) about the same problem seems to indicate that newer version of the Node library did not have this problem.
