### ISSUE TITLE
API to allow setting socket options on the stream channel connections in the GRPC server side

### ISSUE THREAD

**Issue by prakashbadri-arista** [grpc/grpc#32611]
Currently there is no way for the C++ GRPC server side implementation to set a custom DSCP value for the stream channel connections.  There have been a lot of issues/pull requests created to track this requirement, but I do not see any progress on this.  

https://github.com/grpc/grpc/pull/28322 is one of the recent discussions on this. 

As documented previously,
grpc::ChannelArguments::SetSocketMutator (grpc_socket_mutator *mutator) is unusable since "grpc_socket_mutator" definition is not included in the libgrpc library. I don't see any other means by which a server implementation can override the socket options for the stream channel connections. 

Can someone please let me know if there is any active action item to help with this problem ?

**Comment by drfloob** [comment]
Closing as duplicate. I've responded on the other thread.
