### ISSUE TITLE
C core improperly forked testing.proto

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#32628]
The canonical testing.proto is in grpc-proto. It seems #32599 forked the proto. The [upstream grpc-proto](https://github.com/grpc/grpc-proto/blob/master/grpc/testing/messages.proto) should always be changed first.

When we added orca testing earlier, the orca dependency caused trouble so we purposefully avoided the orca dependency. That's why we added `TestOrcaReport` and avoided the dependency. I don't know why we thought this time it'd be less of a problem.

CC @markdroth

**Comment by ejona86** [comment]
It also seems that [orca_oob](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#orca_oob) would not be compatible with other languages. The grpc-proto version should be used; that's what the interop-test-descriptions is talking about.

**Comment by markdroth** [comment]
Yes, I agree, copying the grpc-proto version is the right thing to do.  I completely forgot about that when Eugene was doing this, so it's my bad.  Sorry for the oversight, and thanks for the correction!
