### ISSUE TITLE
when can develop grpc for vlang,thanks a lot

### ISSUE THREAD

**Issue by legendsf** [grpc/grpc#32644]
https://github.com/vlang/v

vlang is fast as clang，and is son of rust & golang,have simple and bu'tiful syntax

vlang's synatx is 80% similar of golang with better error handle and generics 

and without/within gc 

without borrow lifetime ownership rules rust does,and compile very fast than rust

who can help to develop a vlang grpc

thanks a lot !

**Comment by legendsf** [comment]
very very thanks a lot @markdroth ！

**Comment by markdroth** [comment]
We have no plans to develop a gRPC implementation for the V language.
