### ISSUE TITLE
php grpc client failed to connect to all addresses

### ISSUE THREAD

**Issue by dengao123** [grpc/grpc#32670]
#### What version of gRPC and what language are you using?
 laguage: PHP 
grpc verson 1.47.4 

#### What operating system (Linux, Windows,...) and version?
linux

#### What runtime / compiler are you using (e.g. python version or version of gcc)
php7.4

#### What did you do?
        $client = new AppServiceClient('192.168.10.1:9001', [
            'credentials' => Grpc\ChannelCredentials::createInsecure()
        ]);

        $req = new GetByAppRequest();
        $req->setApp("cms");
        list($reply, $status) = $client->GetByApp($req)->wait();
        dd($status);

### What did you expect to see?
$staus code is 200

### What did you see instead?
{#1410
  +"metadata": []
  +"code": 14
  +"details": "failed to connect to all addresses"
}

**Comment by alto-php** [comment]
Can you enable grpc traces and post the log here?
Please refer to this doc on how to enable logs: https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md
