### ISSUE TITLE
gRPC C++ server cannot handle as many concurreny client requests as is set by ResourceQuota

### ISSUE THREAD

**Issue by caopeng428** [grpc/grpc#32680]
While using `ResourceQuota::SetMaxThreads` to set thread num limit, the actual concurrency is smaller than this intended number.

lang: C++
gRPC version: v1.52.1

1. set the server thread limit using following code
```cpp
    grpc::ResourceQuota quota;
    quota.SetMaxThreads(4);
    builder.SetResourceQuota(quota);
```
2. request the server with a client of 4 threads
```cpp
    for (int i = 0; i != 4; ++i) {
        threads.emplace_back([&]() {
            while (true) {
                call_rpc(stub.get());
            }
        });
    }
```
3. We expected to see that all requests are successfullly returned. However, many of them will end up with "status: 8, msg: Server Threadpool Exhausted". In fact, the error occurs even if we use 3 client threads, which is fewer than server thread count. 
4. Since we have only 3 client threads triggerring requests, the number of server threads handling requests must be equal to or less than 3. We know that there is at least 1 thread which can poll. But the variable `num_pollers_` is sometimes less than the threads which are not doing work. Because the variable is not added as soon as `DoWork` finishes, and subtracted before actually starts `DoWork`.

cpp source:
[grpc_demo.zip](https://github.com/grpc/grpc/files/11040071/grpc_demo.zip)

**Comment by drfloob** [comment]
> Because the variable is not [incremented] as soon as DoWork finishes, and [decremented] before actually starts DoWork.

You probably identified the reason here. It's possible that the client received a response while the server's thread is still cleaning up after `DoWork` finishes. If this flood of sync client requests to a synchronous server is your actual use case, consider adding some buffer to the quota's thread count to account for this.
