### ISSUE TITLE
[Python] gRPC 1.53.0 release missing on pypi

### ISSUE THREAD

**Issue by matejsp** [grpc/grpc#32702]
### What version of gRPC and what language are you using?
gRPC 1.51.3 and trying to upgrade due to fork issues.

### What operating system (Linux, Windows,...) and version?
MacOS Ventura 13.2 and Linux (arm and intel)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8 and python 3.11

### What did you expect to see?
https://pypi.org/project/grpcio/ latest 1.53.0 released together with github release.

grpcio-1.53.0rc2.tar.gz

### What did you see instead?
The latest is still 1.51.3

**Comment by radekwlsk** [comment]
> ### What did you see instead?
> The latest is still 1.53.1

1.51.3* ;)

Also waiting for release on pypi. Isn't it automated in any way? Just curious, what causes the delay between Release on GH and pypi?

**Comment by gnossen** [comment]
1.53.0 is now pushed to PyPi.

> Isn't it automated in any way?

No, it is not automated. Uploading to individual package managers is a manual process. Also, not every patch release is meant for all languages. We'll often push a patch release to fix an issue in just a single language and only upload packages for that language. So, in general, it's not a good assumption that the latest Github tag is the right version to use as a PyPi download.

I delayed the upload of this particular release to investigate a potential issue with the release that we we were just recently able to verify should not cause issues.
