### ISSUE TITLE
Much CPU time consumed on LockedMultiProducerSingleConsumerQueue::TryPop. 

### ISSUE THREAD

**Issue by LeiW000** [grpc/grpc#32700]
Testing Environment
gRPC version: 1.52.1
[grpc_bench](https://github.com/LesnyRumcajs/grpc_bench)

Configs of grpc_bench:
GRPC_BENCHMARK_DURATION  120s     
GRPC_BENCHMARK_WARMUP 30s     
GRPC_SERVER_RAM 512m      
GRPC_CLIENT_CONNECTIONS 50     
GRPC_CLIENT_CONCURRENCY 1000      
GRPC_CLIENT_CPUS 10 
GPRC_SERVER_CPUS [40 | 150]   
GRPC_REQUEST_SCENARIO=complex_proto     

I run [cpp_grpc_mt_bench](https://github.com/LesnyRumcajs/grpc_bench/tree/master/cpp_grpc_mt_bench) of grpc_bench to benchmark the performance of gRPC multi-threads on a system. I saw that lots of CPU time were consumed on LockedMultiProducerSingleConsumerQueue::TryPop() with the thread increasing. Please see below. 
40 threads:   5.12%    
150 threads: 33.7% 

I generated the [FlameGraph](https://github.com/brendangregg/FlameGraph). Please see the attached files. It seems to me that there is a locking contention. If it can be reduced, the RPS could be improved. 

![perf-40-threads-cpp-mt](https://user-images.githubusercontent.com/51774176/227403340-4e5c75df-0095-4d1b-a2c2-4b44b06e0a45.svg)
![perf-150-threads-cpp-mt](https://user-images.githubusercontent.com/51774176/227403356-4b36193d-38f2-436c-8ee2-e71bfff2b62a.svg)

**Comment by LeiW000** [comment]
I suspect that the code below in MatchOrQueue() causes the lock contention. All threads try to call TryPop(), which calls mu_.TryLock().

```
     for (size_t i = 0; i < requests_per_cq_.size(); i++) {
       size_t cq_idx = (start_request_queue_index + i) % requests_per_cq_.size();
       RequestedCall* rc =
           reinterpret_cast<RequestedCall*>(requests_per_cq_[cq_idx].TryPop());
       if (rc != nullptr) {
         calld->SetState(CallData::CallState::ACTIVATED);
         calld->Publish(cq_idx, rc);
         return;
       }
     }
```

**Comment by LeiW000** [comment]
I'm looking into the issue. Any suggestion or comment is welcome. :).

**Comment by ctiller** [comment]
How many calls are you requesting?
There's a definite slow path if you're regularly running out of queued
requested calls.

**Comment by veblush** [comment]
@drfloob Assuming this is a known issue of current design of gRPC C++, I'm wondering whether this is going to be improved once EventEngine lands.

**Comment by drfloob** [comment]
@veblush no, not directly.

**Comment by LeiW000** [comment]
I decide to close the issue as it is not seen with the QPS tests.
