### ISSUE TITLE
Import Error for  grpc-google-iam-v1 ( 0.12.3 ) - from grpc._cython import cygrpc

### ISSUE THREAD

**Issue by rajk1729** [grpc/grpc#32717]
Import is failing as I see cygrpc.so file in grpc module. How it can be resolved ?

from grpc._cython import cygrpc
ImportError: dynamic module does not define init function (initcygrpc)

This error is coming when this import is called from google-cloud-secret-manager-1.0.2

### What version of gRPC and what language are you using?
grpc-google-iam-v1 ( 0.12.3 ) , python 2

### What operating system (Linux, Windows,...) and version?
Google app engine for deployment 

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python

### What did you do?

The issue is coming only in google app engine and not when it runs locally in mac on both python 2 and python 3 separately.

**Comment by XuanWang-Amos** [comment]
Hi, can you help provide some more information? Like what version of grpc was used and some error logs?

**Comment by gnossen** [comment]
Python 2 is no longer supported. The final release that supported Python 2 was [1.39.0](https://pypi.org/project/grpcio/1.39.0/).

**Comment by raj-zeni** [comment]
> Hi, can you help provide some more information? Like what version of grpc was used and some error logs?

I had installed google-cloud-secret-manager and gRPC is perhaps its dependency .. during import of from google.cloud import secretmanager => it falks at certain point  like during import of gRPC .. further to get rid of this error , I removed .so file and added binary skeletons to my third_party .. it worked till some next steps but it again failed during import of _compressorAlgorithm... in standalone python 2 project it works with dependency installed in default directory ... but if added to tgird_party, it starts failing for some or other errors.

**Comment by raj-zeni** [comment]
> Python 2 is no longer supported. The final release that supported Python 2 was [1.39.0](https://pypi.org/project/grpcio/1.39.0/).

Thanks.
