### ISSUE TITLE
Error upgrading protobuf version during release process

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#32722]
Ran into an error when trying to update the `third_party/protobuf` version during the next release process.

Currently we are at `v21.12` of protobuf. As of today, the latest stable version of protobuf is `v22.2`.

When running the release script to update the `third_party/protobuf` version, I ran into this error:

```
ERROR: no such target '//:built_in_runtime_protos': target 'built_in_runtime_protos' not declared in package '' defined by /tmp/grpc-release-tt4qdh_5/third_party/protobuf/BUILD.bazel
```

So I track it down to the the script `bazel_deps.sh`, which tries to run some `bazel query` command on some known bazel targets. But apparently the bazel target `built_in_runtime_protos` has been removed between `v21.12` and `v22.2` of protobuf.

- `v21.12`: https://github.com/protocolbuffers/protobuf/blob/v21.12/BUILD.bazel#L192
- `v22.2`: https://github.com/protocolbuffers/protobuf/blob/v22.2/BUILD.bazel

Here's our code trying to query `built_in_runtime_protos`: https://github.com/grpc/grpc/blob/master/tools/distrib/python/make_grpcio_tools.py#L91

So how should we proceed?

Option 1: Ask protobuf team if that target is removed intentionally?
Option 2: Remove querying `built_in_runtime_protos` in `make_grpcio_tools.py` - but I am not sure how we are depending on this target.
Option 3: Don't upgrade protobuf version for the release process?

Also of note that `v21.12` is also known as `v3.21.12`, while `v22.2` is also known as `v4.22.2` ___and___ `v3.22.2`, so I am not sure if some major version bump breakage is being expected here.

**Comment by jtattermusch** [comment]
I'll handle this, there's a lot of background info so for now don't worry about this.

**Comment by drfloob** [comment]
Master is now on protobuf 24.x
