### ISSUE TITLE
Registering callbacks on connect / disconnect success or failures

### ISSUE THREAD

**Issue by amitkg29** [grpc/grpc#3273]
Hello,

I am interested to know if it is possible to register callbacks which gets invoked on connect/disconnect success/failure?

I think that it could be done easily but i could not find any existing mechanism (looking at grpc_server structure)  as i do not want to duplicate the code.

Thanks

**Comment by amitkg29** [comment]
My current thoughts are:

a) extend the grpc_server structure to have connect_cb and disconnect_cb callbacks.
b) Allow the client/server to fill in those callback pointers.
c) Invoke these callbacks, say for server, invoke it when an incoming connection is received.

**Comment by ctiller** [comment]
We're thinking about this, but don't have a firm design yet. Our current
thinking is that we want to avoid callbacks and funnel these events through
the completion queue, in a similar style to request_call. This would give
us some good signal inside the library that applications are not keeping up
with incoming connections (allowing us to throttle work).

**Comment by amitkg29** [comment]
Thanks Craig for looking into it.

One subsequent question to this is - The reason to have connect callback was to provide the user-id string to the other side.

For example: a Network Configuration client sends NETCONF-CLIENT as User-Id string to Server. Server should see this in connect request and can take a specific action.

If we do connect callback via completion queue, Can the use-case i described above be achieved? Or if there is any other alternative?

**Comment by ctiller** [comment]
There probably won't be a surfaced api for directly reading bytes from
wire... Such a thing would be incredibly brittle. If there's a custom
handshake that needs to happen then it probably needs to be handled within
the library similarly to how we do the ssl integration.

**Comment by amitkg29** [comment]
Thanks craig again. 

Well, We do not want to read bytes from Wire directly.
Perhaps there could be a header like "User-Agent" used by httpcli which greeter_client can set and could be received by greeter_server. 

I thought this header could be available in service callback arguments (mostly in request). I was looking at Channel structure which has key/value pairs But i believe these are Local channel settings and does not go on wire to other side.

**Comment by zj8487** [comment]
+1 for get the connection/disconnection event on server side! 
There are so many reasonable scene. for example: clean the user struct in a chat server when the connection is disconnected!

@ctiller Is there a usable way to reach work in the example now?
