### ISSUE TITLE
grpc over vsock (2023)

### ISSUE THREAD

**Issue by maburlik** [grpc/grpc#32738]
### Is your feature request related to a problem? Please describe.
Vsockets are not currently supported in main line grpc.

I'm aware the ChromiumOS and Android projects are using forks of GRPC to enable vsockets aka AF_VSOCK sockets, based on the patch found here:
https://android.googlesource.com/platform/external/grpc-grpc/+/a0d43cf1a94bc5443ee8ee2499490f6af4da6272

It appears Android is referencing an old version of grpc:
```
version = "1.16.0-dev"
```
and I'd like to adopt a newer version. The version currently being used for my project is v1.48.1, and it's not really an option for me to go back to an earlier version.

Has there been any update since the discussion found here?
https://github.com/grpc/grpc/issues/25801

### Describe the solution you'd like
Either a port of the patch mentioned above for a newer version of grpc, or support for vsocks in the grpc main line.

### Describe alternatives you've considered
My other options are to use:
1. plain POSIX sockets,
2. implement a custom transport for grpc (may be out of scope for the goal),
3. or try to port the patch above to the new version of grpc.

### Additional context
I'd like to know whether the vsock support has been ported already to a newer version of grpc in any public fork, and/or whether the support for vsockets is planned. It seems multiple major projects would benefit from this, and support in the main line would reduce fragmentation in absorbing security updates.

**Comment by markdroth** [comment]
There is no vsock support in gRPC currently.  There was a previous attempt in https://github.com/grpc/grpc/pull/24551, but it was never finished by the contributor.  If you'd like to contribute a PR to add vsock support in a similar way, we'd be happy to review it.
