### ISSUE TITLE
Bugs when installing installing gRPC from console with PECL

### ISSUE THREAD

**Issue by RSY96** [grpc/grpc#32735]
Good afternoon, I am trying to install the library with the "pecl install grpc" command and it is returning the following error: "Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\php\pear \PEAR\Config.php on line 2095". I don't know why but it gives a PHP related syntax error.

![Captura de pantalla 2023-03-28 165117](https://user-images.githubusercontent.com/79986286/228281793-c47c98a8-661c-45d6-b3b5-52e4dc88cb19.png)

The PHP version I'm using is:
"PHP 8.2.0 (cli) (built: Dec 6 2022 15:31:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies"
Windows 11

And it is not only that file but many more with which it gives a syntax error.

How can this be fixed?

Thank you.

**Comment by stanley-cheung** [comment]
PECL stopped being able to pre-compiled extensions' DLL file: https://externals.io/message/117494

**Comment by RSY96** [comment]
In the link that you gave me from that thread, they have been trying to do something for 11 months but they have not made any progress yet. As the installation with PECL is broken I am following the steps for the installation in windows,

![Captura de pantalla 2023-03-29 111611](https://user-images.githubusercontent.com/79986286/228488098-6df8622e-d324-4733-9950-08c7be651a49.png)

but when executing the command "EXTRA_DEFINES=GRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK make" compiling the gRPC C core library I get this error in the console.

![Captura de pantalla 2023-03-29 111403](https://user-images.githubusercontent.com/79986286/228488023-7b4023cc-adca-4b55-bafe-bd5ef79e4745.png)

**Comment by stanley-cheung** [comment]
We had been relying on PECL's automated process to build pre-compiled DLL every time we push a general release. Currently there's no plan to support pre-compiled DLL ourselves.
