### ISSUE TITLE
Hitting problem with Windows greeter_async_client code

### ISSUE THREAD

**Issue by swingfield** [grpc/grpc#3274]
Hi there,

I'm trying out the C++ client and server code on Windows. But I'm getting an access violation when running the client code.

Quick rundown of what I've got and how I got there, in case I've missed something:

I have helloworld server & client projects in VS2013. I used info from the README.MD at

https://github.com/grpc/grpc/tree/master/vsprojects

and some additional hints from 

https://github.com/grpc/grpc-common/issues/173

to work towards getting the example over at

https://github.com/grpc/grpc/tree/master/examples/cpp

working.

At first I ended up with non-async versions of greeter_client.cc & greeter_server.cc.  This version of the server failed, complaining that the completion queue vector was empty.  Doing some looking around the code base, I now realize this is probably expected, and I soon found the pre-supplied greeter_async_client/server.cc files.  I swapped my two non-async versions of these files with the async versions, and the server then started fine.

However, when I run the client I get an access violation with a null pointer. 

Perhaps this is because I did not generate the greeter_async_client.cc file myself, but instead used the one I found in the code base as-is?  If this is the problem, could you tell me how to generate the async versions of the files via protoc.exe? 

If it's helpful, here's additional information on the access violation I received.  It stemmed from CallOpSendInitialMetadata::SendInitialMetadata.  I might be wrong, but It looks like the method is being passed metadata which is a std:_Tree with a null _Myhead, and when it begins traversing the tree it hits the access violation.

I'll add some screenshots here to hopefully give some context, along with the greeter_async_client.cc code.

Thanks in advance for any help.

![image](https://cloud.githubusercontent.com/assets/3903455/9723322/ea4bc01a-557b-11e5-944e-290dde45e5da.png)

![image](https://cloud.githubusercontent.com/assets/3903455/9723330/fd25def0-557b-11e5-8267-769a55bbb00f.png)

![image](https://cloud.githubusercontent.com/assets/3903455/9723332/0649800e-557c-11e5-9607-ab8bbefb97b5.png)

![image](https://cloud.githubusercontent.com/assets/3903455/9723335/0c522ba4-557c-11e5-9b46-23db2ac37e86.png)

```
class GreeterClient {
 public:
  explicit GreeterClient(std::shared_ptr<Channel> channel)
      : stub_(Greeter::NewStub(channel)) {}

  std::string SayHello(const std::string& user) {
    HelloRequest request;
    request.set_name(user);
    HelloReply reply;
    ClientContext context;
    CompletionQueue cq;
    Status status;

    std::unique_ptr<ClientAsyncResponseReader<HelloReply> > rpc(
        stub_->AsyncSayHello(&context, request, &cq));
    rpc->Finish(&reply, &status, (void*)1);
    void* got_tag;
    bool ok = false;
    cq.Next(&got_tag, &ok);
    GPR_ASSERT(ok);
    GPR_ASSERT(got_tag == (void*)1);

    if (status.ok()) {
      return reply.message();
    } else {
      return "Rpc failed";
    }
  }

 private:
  std::unique_ptr<Greeter::Stub> stub_;
};

int main(int argc, char** argv) {
  GreeterClient greeter(grpc::CreateChannel(
      "localhost:50051", grpc::InsecureCredentials()));
  std::string user("world");
  std::string reply = greeter.SayHello(user);
  std::cout << "Greeter received: " << reply << std::endl;

  return 0;
}
```

**Comment by larsonmpdx** [comment]
I haven't used the async stuff on windows but this could be a missing "D "_USE_32BIT_TIME_T"

see #2595

**Comment by swingfield** [comment]
You're a genius!  :) Thanks, that was it exactly.  Client/Server working great now.  Thanks again for your help.
