### ISSUE TITLE
Please upgrade NuGet package for gRPC with new version

### ISSUE THREAD

**Issue by nickdul** [grpc/grpc#3276]
current version (0.6.1) of gRPC available via NuGet is not compatible with Google Protocol Buffers C# 3.0.0-alpha4

gRPC 0.6.1 generates non-compiled service stub:
the trouble in ``Marshaller`` variable -  ``ParseFrom`` method is part of ``Parser`` property of message rather then message one: 
```
static readonly Marshaller<global::Mynamespace.MyMessage> __Marshaller_MyMessage = Marshallers.Create((arg) => arg.ToByteArray(), global::Mynamespace.MyMessage.ParseFrom);
```

**Comment by nickdul** [comment]
in addition cannot build ``RoutGuideServer`` example because it references on non-existing NuGet package:
https://github.com/grpc/grpc/blob/master/examples/csharp/route_guide/RouteGuideServer/packages.config

**Comment by jtattermusch** [comment]
The gRPC C# beta nuget packages have been pushed a few hours ago. Official announcement & docs are coming soon.
