### ISSUE TITLE
Set option csharp_namespace = $(RootNamespace) by default

### ISSUE THREAD

**Issue by eduard-bystrov** [grpc/grpc#32802]
Often the client and the service refer to the same proto file, but then it is difficult to use the client and the service at the same time, for example, in tests

Link in tests to the client and service will lead to an error when building:

```cmd
Error	CS0433	The type '{TypeName}' exists in both '{Client} and '{Service}'
```
_____________

P.S.
You can open any example here to play
https://github.com/grpc/grpc-dotnet/tree/master/examples/Aggregator

**Comment by eduard-bystrov** [comment]
Or is it a bad pattern to use one proto file for client and service?

**Comment by tonydnewell** [comment]
@eduard-bystrov It is common to use one proto file for both client and service.

When compiling the proto file you can specify if you want client, server (or both or none) code generated together with the code for the proto message definitions.

I'm not sure I understand your problem. Can you give an example where you are getting the error? The example you point to compiles OK.

**Comment by eduard-bystrov** [comment]
https://github.com/eduard-bystrov/gRPC-issues-32802-SampleError

**Comment by tonydnewell** [comment]
@eduard-bystrov I can see the problem.

You are building the proto files twice - once for server and once for client, which is fine except you then have a third project (your tests project) which is dependent on both those projects.

There is no way to compile the same proto file and specify different namespaces for each output. You have to either:
- compile proto files only once (see example below)
- use different proto files that differ only by the `option csharp_namespace`. Not recommended as it may lead to other issues and incompatibilities over time.

Normally having the server and clients each compile the same proto files would be OK. It is only your specific case that is causing the issue.

To only build the proto files once you can have a project that builds the proto files and the other projects reference that project. 
For example see: https://github.com/grpc/grpc/tree/02384e39185f109bd299eb8482306229967dc970/examples/csharp/Helloworld

**NOTE:** this example is a _grpc-core_ project not a _grpc-dotnet_ project, but the layout of the projects will be the same but the gRPC C# code will be slightly different.

In this example:

- `Greeter` compiles the proto files
- `GreeterClient` is the client, and depends on `Greeter`
- `GreeterServer` is the server, and depends on `Greeter`

**Comment by eduard-bystrov** [comment]
If anyone else encounters a similar problem, open the issue again
I solved my problem using the example above

**Comment by leidegre** [comment]
I'm just going to add to this that while at first, I might seem appealing to try to put the client and server code in different assemblies it's just not feasible due to how everything else works. At best you'll still have to deal with multiple types with the same name in the same namespace but from different assemblies and this isn't a particular happy situation to be in.

In summary, if you want to avoid code duplication and multiple definitions just do as @tonydnewell says and generate the message types and client/server stubs in one assembly. This is your service layer then just use this where you need to use it.
