### ISSUE TITLE
Grpc channel state going to ready state from transient failure state when trying to connect server of invalid ip address after few minutes.

### ISSUE THREAD

**Issue by Vireshf** [grpc/grpc#32838]
I have configured server of invalid ip address which client tries to connect. after creating the channel, state of grpc channel will be transient failure. but after few minutes(close to 7-8 mins). it goes to ready state from transient failure state.

Ideally the state of grpc channel should remain Transient failure.

grpc version used : 1.24.

**Comment by Vireshf** [comment]
Please help me with this issue. I am seeing this in 1.24 only. I can't see same issue in 1.46 version. but due some concerns, I can't upgrade  to 1.46 version.

**Comment by yashykt** [comment]
Hi, I'm not sure why you removed the default labels, but 1.24 is really old, and we don't backport fixes that far back. I'd have more concerns about using such an old version.
