### ISSUE TITLE
Python Server Reflection Response for "FileContainingSymbol" does not include any protobuf "import"

### ISSUE THREAD

**Issue by tomsoftware** [grpc/grpc#32899]
### What version of gRPC and what language are you using?
grpcio==1.54.0
grpcio-reflection==1.54.0
grpcio-tools==1.54.0
protobuf==4.22.3

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11.2

### What did you do?
1. using `greeter_server_with_reflection.py`
https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_server_with_reflection.py

2. split protos in two:

other_types.proto
```proto
syntax = "proto3";
message HelloRequest {
  string name = 1;
}
message HelloReply {
  string message = 1;
}
```

greet.proto
```proto
syntax = "proto3";
package greet;
import "other_types.proto";
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply);
}
```

3. running greeter_server_with_reflection.py

4. running client (in my case I use a C# client)

```csharp
var channel = GrpcChannel.ForAddress("https://localhost:50051");
var client = new ServerReflectionClient(channel);
var call = client.ServerReflectionInfo();
await call.RequestStream.WriteAsync(new ServerReflectionRequest
{ 
  FileContainingSymbol = "greet.Greeter"
});
Debug.Assert(await call.ResponseStream.MoveNext());
var descriptorResponse = call.ResponseStream.Current;
````

### What did you expect to see?
Server should return "greet.proto" and "other_types.proto" on reflection request. So `descriptorResponse.count > 1`

And therefore no error when calling

```csharp
FileDescriptor.BuildFromByteStrings(fileDescriptorProto.Reverse());
```

### What did you see instead?

`descriptorResponse.count == 1` (so only the "greet.proto" is in the array-response)
and Error in my C#-Client:
***System.ArgumentException: 'Dependency missing: other_types.proto'***

### Anything else we should know about your project / environment?
- Doing this with the C# Server (https://github.com/grpc/grpc-dotnet/tree/master/examples/Reflector)  I get `descriptorResponse.count == 2`and it works.
- Without splitting the proto everything is fine
- gRPC Reflection is so cool - thanks for this feature!!!

**Comment by tomsoftware** [comment]
OK, I tried to get more details:

The C# Server runs a `CollectTransitiveDependencies` before sending result:

https://github.com/grpc/grpc-dotnet/blob/6bf44820a2ef6af5845830728cd4b3d1a8053ed4/src/Grpc.Reflection/ReflectionServiceImpl.cs#L118

```csharp
        FileDescriptor file = symbolRegistry.FileContainingSymbol(symbol);
        ....
        CollectTransitiveDependencies(file, transitiveDependencies);
```

Python Server did not:

https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/python/grpcio_reflection/grpc_reflection/v1alpha/_base.py#L57

```python
    descriptor = self._pool.FindFileByName(filename)
    ...
    return _file_descriptor_response(descriptor)
```

Can someone tell me what the specification says? Does the Python server lack this function OR does the C# server just do too much "just for fun"?

**Comment by XuanWang-Amos** [comment]
Thanks for the PR! I think current behavior is expected:

[Protobuf doc](https://googleapis.dev/python/protobuf/latest/google/protobuf/descriptor_database.html#google.protobuf.descriptor_database.DescriptorDatabase.FindFileContainingSymbol) says: `The symbol should be a fully qualified name including the file descriptor’s package and any containing messages.`

And [from test](https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/descriptor_pool_test.py#L989-L990) looks like it's not recursive: `AddFileDescriptor is not recursive; messages and enums within files must be explicitly registered.`

**Comment by tomsoftware** [comment]
OK - thanks -> so the spec says: `Returns: The file descriptor proto containing the symbol.` So it does not say anything about it's dependencies.

From my side of view: 

> I'm as a grpc-client are unable to use just the one response descriptor proto cause I need all dependencies to understand the interface and querying them one by one is much more work.

vs.

> Sending all dependencies makes it impossible to just query exact one descriptor proto

- Do you have contact to the [grpc-dotnet](https://github.com/grpc/grpc-dotnet) team? Why did they add this feature/dependencies?
- How do other languages behave?

**Comment by tomsoftware** [comment]
OK... found the spec
https://github.com/grpc/grpc/blob/master/doc/server-reflection.md

> Because most usecases will require also requesting the transitive dependencies of requested files, the queries will also return all transitive dependencies of the returned file.

**Comment by tomsoftware** [comment]
Perfect - this helps me very much -> Thank you!
