### ISSUE TITLE
python2 run grpc demo get exit code  -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by Aoing** [grpc/grpc#32906]
python2 

futures       3.4.0
grpcio        1.39.0rc1
grpcio-tools  1.39.0rc1
mypy-protobuf 1.24
pip           20.3.4
protobuf      3.17.3
PyJWT         1.7.1
setuptools    44.1.1
six           1.16.0
style         1.1.0
wheel         0.37.1

run the server demo and i get error: Process finished with exit code -1073741819 (0xC0000005)

**Comment by XuanWang-Amos** [comment]
Hi, we're not supporting python2 anymore and the oldest version we support is v1.46.0, please upgrade to a newer version if possible.
