### ISSUE TITLE
ReadFile overlapped error: An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3290]
Virtually all C# tests finish with this message:
E9/8/2015 4:36:58 PM 108345464 c:\users\jtattermusch\github\grpc\src\core\iomgr\tcp_windows.c:150: ReadFile overlapped error: An operation was attempted on something that is not a socket.

The tests actually pass, but the error should finish with connection reset error (that has been silenced in the past) rather than this error. IIRC, in the past this error indicated a problem with our shutdown sequence.

**Comment by jtattermusch** [comment]
In helloworld example, I am also seeing this message (but the example finishes successfully):
E9/9/2015 9:04:00 AM 88670368 c:\users\jtattermusch\github\grpc\src\core\iomgr\t
cp_windows.c:150: ReadFile overlapped error: The I/O operation has been aborted
because of either a thread exit or an application request.

**Comment by nicolasnoble** [comment]
This one is fixed.
