### ISSUE TITLE
CompletionQueue::Next blocking for about 15 mins after call CompletionQueueGuard::Shutdown

### ISSUE THREAD

**Issue by Alchemist2077** [grpc/grpc#32925]
What version of gRPC and what language are you using?
1.54

What operating system (Linux, Windows,...) and version?
ubuntu

What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu

What did you do?
I use grpc to establish a bidistreame to a grpc server. here is part of my code .
```
void EISGrpcClient::dealing_interaction()
{
  gspeech_stub_ = eis::EIService::NewStub(channel_);

  grpc::ClientContext context;
  grpc::CompletionQueue completion_queue;
  auto streamer = gspeech_stub_->AsyncGetInteract(
      &context, &completion_queue,
      reinterpret_cast<void *>(stream_cq_seq_ = ++cq_seq_));
  GetInteractResponse response;
  streamer->Read(&response,
                 reinterpret_cast<void *>(last_read_seq_ = ++cq_seq_));
  // this two param order is fixed
  CompletionQueueGuard cqg(completion_queue);
  ContextGuard sg(context);

  while (running_)
  {
    // do some thing
  }
  LOG(INFO) << "dealing_interaction E";
}
```
I also design two gurad to protect "CompletionQueue"and "ClientContext"
```
class CompletionQueueGuard
{
public:
  CompletionQueueGuard(grpc::CompletionQueue &cq) : cq_(cq){};
  ~CompletionQueueGuard()
  {
    cq_.Shutdown();
    LOG(INFO) << "CompletionQueue not running start draining";
    void *tag;
    bool ok;
    // should drain completion_queue before delete completion_queue
    while (cq_.Next(&tag, &ok))
    {
      LOG(INFO) << "CompletionQueue drain";
    }
    LOG(INFO) << "CompletionQueue drain done";
  };
  grpc::CompletionQueue &cq_;
};

class ContextGuard
{
public:
  ContextGuard(grpc::ClientContext &context) : context_(context){};
  ~ContextGuard() { context_.TryCancel(); };
  grpc::ClientContext &context_;
};
```

so when interaction is finished ,i will call  "context_.TryCance" and  "cq_.Shutdown" then i will call cq_.Next to drain the CompletionQueue

My Problom:
sometimes, especially with bad network. "cq_.Next" may block about 15 mins even the network is back online.
```
CompletionQueue not running start draining
CompletionQueue drain
// after about 15 mins
CompletionQueue drain
CompletionQueue drain done
```

to simulate bad network i use "ifconfig wlan0 down". it is very easy to reproduce.

so. is this a bug? or i do something wrong? how can i let cq_.Next not bloking.
thanks

**Comment by veblush** [comment]
You may want to try `AsyncNext` function if you want to limit the timeout. Also I'd like to note that you may want to consider using [KeepAlive](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) feature to make gRPC notice this network issue.

**Comment by Alchemist2077** [comment]
AsyncNext do make draining unblock,but uncomplete draining seems like may  cause fd（file descriptor） leaking.
Setting GRPC_ARG_KEEPALIVE_TIME_MS do helps, cq_.Next will not blocking for suck long time after set this paramter to channel.
Just want other perple have same issue to see.
And thank you for your help!
