### ISSUE TITLE
Supports running on windows XP?

### ISSUE THREAD

**Issue by jixyang** [grpc/grpc#32926]
target  os :Windows XP
ide: vs2022
windowsdk:7.0 
platform toolset: Windows XP (v141_xp)

compile error likes this: (___dyn_tls_on_demand_init, __tls_guard)
grpc.lib(alts_zero_copy_grpc_protector.obj) : error LNK2001: unresolved external symbol  ___dyn_tls_on_demand_init
grpc.lib(jwt_credentials.obj) : error LNK2001:  unresolved external symbol ___tls_guard

How to solve these problems? Thanks

**Comment by markdroth** [comment]
The oldest version of Windows we support is Windows 10, as per:

https://github.com/grpc/grpc/tree/master/src/cpp#supported-platforms

**Comment by jixyang** [comment]
ok, thank you!
