### ISSUE TITLE
program with grpc shared libraries,sometimes the process hang forever

### ISSUE THREAD

**Issue by kiloyqp** [grpc/grpc#32942]
### What version of gRPC and what language are you using?
gRPC v1.53.0
c++

### What operating system (Linux, Windows,...) and version?
ubuntu18.04 aarch64

### What runtime / compiler are you using (e.g. python version or version of gcc)
cmake 3.23.0
g++7.5.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
1) complie grpc shared library;
`
cmake ../.. -DCMAKE_BUILD_TYPE=Release  -DBUILD_SHARED_LIBS=ON -DgRPC_SSL_PROVIDER=package -DgRPC_INSTALL=ON -DCMAKE_INSTALL_PREFIX=/opt/grpc -DCMAKE_CXX_STANDARD=14
` 
2) write a user.proto file with message and service,then use protoc generate 4 file(user.pb.h,user.pb.cc,user.grpc.pb.h,user.grpc.pb.cc);
3) main function like this:
```
int main()
{
    cout<<getpid()<<endl;
    cout<<"1"<<endl;
    grpc_init();
    cout<<"2"<<endl;
    auto ptr = grpc::InsecureServerCredentials();
    cout<<"3"<<endl;
    ServerBuilder builder;
    builder.AddListeningPort("127.0.0.1:10012", ptr);
    cout<<"4"<<endl;
    //UserServiceImpl user;
    //builder.RegisterService(&user);
    cout<<"5"<<endl;
    auto WebServer = builder.BuildAndStart();
    cout<<"6"<<endl;
    while(1) {
        this_thread::sleep_for(std::chrono::milliseconds(1000));
    }   
    return 0;
}
```
4) cmakelists.txt like this
```
...
file(GLOB TEST_SOURCE ${PROJECT_ROOT_DIR}/main.cpp)
file(GLOB PROTOBUF_SOURCE ${PROJECT_ROOT_DIR}/ProtoBufGen/user.pb.cc ${PROJECT_ROOT_DIR}/ProtoBufGen/user.grpc.pb.cc)
add_executable(${PROJECT_NAME} ${TEST_SOURCE} ${PROTOBUF_SOURCE})
target_link_libraries(${PROJECT_NAME}
	PUBLIC
	${GRPC_LIB}
	libdl.so
        libsystemd.so
	liblz4.so
        libpthread.so
	)
```
5) when i run the program,only  print "1",then hang forever;
6) if i delete the 
`${PROJECT_ROOT_DIR}/ProtoBufGen/user.grpc.pb.cc`
 in cmakelists.txt,then the program can print from 1 to 6,buf if i delete grpc_init() in main,it will also just print "1",then hang forever.
### What did you expect to see?
i expected to see program with grpc shared library run ok.

### What did you see instead?
the program hang forever.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
when i use grpc static library,the program run ok.

**Comment by yijiem** [comment]
1. Can you get the stacktrace of the process when it is hanging (using gdb for example)?
2. Can you create a project which contains a complete example that repros this issue (e.g. a github repo) and share it with us so that we can run it ourselves? It would be good to have the repro step in the README of that project.

**Comment by kiloyqp** [comment]
已收到
