### ISSUE TITLE
Bidirectional streaming with SSL starts crashing after some time

### ISSUE THREAD

**Issue by upcFrost** [grpc/grpc#32955]
### What version of gRPC and what language are you using?
grpcio versions 1.51 to 1.54
Python 3.9.16

### What operating system (Linux, Windows,...) and version?
Debian 10 with updates for April 27th, 2023
Kernel 4.19.0-23
OpenSSL 1.1.1n-0+deb11u4

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.16

### What did you do?
The client code is (simplified):
```python3
def _chunks(data: io.BytesIO):
    while content := data.read(4096):
        yield SvcRequest(data=content)

credentials = grpc.ssl_channel_credentials(...)
with grpc.secure_channel(target='server:33001', credentials=credentials) as channel:
    stub = SvcStub(channel)
    res = stub.Call(itertools.chain([SvcRequest(smth='string')], _chunks(data)))
    for chunk in res:   #  <---- Python stacktrace points on this line
        f.write(chunk.data)
```

This code is called in a multithreaded environment inside another grpc call. The file sent in chunks is not big, it's a relatively small HTML page (3-6kb), so usually the client makes 2 or 3 calls only. The request is consumed like this (also simplified, it doesn't keep things in memory):

```python3
for part in request_iterator:
    part_type = part.WhichOneof('msg')
    if part_type == 'smth':
        description = part.smth
    else:
        data += part.data

target: Path = do_smth(description, data)

with target.open(mode='rb') as f:
    while chunk := f.read(20480):
        yield SvcResponse(data=chunk)
```

Plz note that I was unable to reproduce this issue in any synthetic environment with this code alone, so I guess there's something related to multithreading and not cleaning up/freeing memory properly.

### What did you expect to see?
Stream working w/o crashing

### What did you see instead?

After some time it starts crashing with `grpc_message:"Stream removed"` and with additional SSL error (this is for 1.51, for 1.54 the file is different but the error is the same):
```
E0427 08:02:22.591486946    1145 ssl_transport_security.cc:556]        Corruption detected.
E0427 08:02:22.591548313    1145 ssl_transport_security.cc:532]        error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E0427 08:02:22.591556670    1145 ssl_transport_security.cc:532]        error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC
E0427 08:02:22.591563513    1145 secure_endpoint.cc:304]               Decryption error: TSI_DATA_CORRUPTED
E0427 08:02:22.591684789    1145 ssl_transport_security.cc:583]        SSL_write failed with error SSL_ERROR_SSL.


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/example.py", line 210, in generate
    for chunk in res:
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:10.0.2.215:33001 {created_time:"2023-04-27T08:02:22.591645594+00:00", grpc_status:2, grpc_message:"Stream removed"}"
>
```

### Anything else we should know about your project / environment?
All other call types incl Stream-Unary and Unary-Stream work fine, the only issue is with Stream-Stream. I was unable to reproduce this error in any non-production environment (with the same docker image, same libraries, same OS config etc).

After the request crashes once, all subsequent requests will also crash.

**Comment by XuanWang-Amos** [comment]
Hi, it's hard to tell what's wrong with existing information, can you help provide more logs with those environment vars added?
`GRPC_VERBOSITY=DEBUG GRPC_TRACE=all,-timer,-timer_check`

**Comment by XuanWang-Amos** [comment]
We do have lots of test for multi-threading, so it will be surprising if this issue was caused by multi-threading.

Can you share more information about your network setup? And also more information about the difference between the production environment and testing environment? This could also happen in case of network middleware doing incorrect deep packet inspection.
