### ISSUE TITLE
grpc objective-c client crash

### ISSUE THREAD

**Issue by FlyTengteng** [grpc/grpc#3299]
These days I have used the RouteGruide example of grpc objective-c. If i shutdown the server every 2 minutes, the client will crash, and the crashed point is 

sync_posix.c:53] assertion failed: ret == 0

Anyone have met this situation? How to fix this bug?

**Comment by hsaliak** [comment]
@sreecha do we have a stress test that checks for server shutdowns?

**Comment by sreecha** [comment]
@hsaliak : We do not have one for server shudown-and-restarts yet.  This is mainly because, most of our interop clients (and in this case, the client in the route guide example) are not written to handle server restarts..

**Comment by makdharma** [comment]
This looks like a duplicate of issue #2859. That issue was closed due to unable to reproduce. I'm closing this for the same reason. Please reopen if it still happens.
