### ISSUE TITLE
The NuGet package 'grpc.native.csharp_ext' contains invalid characters.

### ISSUE THREAD

**Issue by ivannaranjo** [grpc/grpc#3300]
When using this package from an Asp.Net app and trying to publish the app the DNU tool fails with the error message:
"The package ID 'grpc.native.csharp_ext' contains invalid characters."
And indeed according to the NuGet spec the character '_' is not valid in a package ID. Suggest removing the _ext portion, grpc.native.csharp is already descriptive enough.

**Comment by jtattermusch** [comment]
Thanks for reporting this! I will try to get this fixed in the next release. Alternatively, a minor 0.7.1 release could be done.
