### ISSUE TITLE
Grpc Conversion issue from RepeatedCompositeContainer to dict

### ISSUE THREAD

**Issue by Triptikothari** [grpc/grpc#33033]
Hi,  I have question to ask regarding grpc  about this RepeatedCompositeContainer

I have write this code
The user.result has the data in the format of  RepeatedCompositeContainer
convert_dict = MessageToDict(user.results, descriptor_pool=True)

This is throwing me error  "question google._upb._message.RepeatedCompositeContainer' object has no attribute 'file'"

I want to convert RepeatedCompositeContainer into the dict and this is throwing me error as you see
Please help me out with this.

**Comment by XuanWang-Amos** [comment]
I might be wrong, but this issue seems only related to Protobuf and upb, please add more details if you think it's related to grpc.
