### ISSUE TITLE
PHP: Deprecated Creation of dynamic property `Grpc\Call::$channel` is deprecated

### ISSUE THREAD

**Issue by nocive** [grpc/grpc#33066]
### What version of gRPC and what language are you using?
composer grpc/grpc 1.52 client library
pecl grpc php extension 1.50.0 (due to open bug https://github.com/grpc/grpc/issues/31772)
PHP 8.2.x

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
Make a gRPC call using the PHP protobuf generated code, client library and PHP extension.

### What did you expect to see?
Working application, no exceptions.

### What did you see instead?
An ErrorException resulting from the deprecation of dynamic property usage introduced with PHP 8.2.

```
ErrorException: Deprecated: Creation of dynamic property Grpc\Call::$channel is deprecated
#12 /vendor/grpc/grpc/src/lib/AbstractCall.php(60): Grpc\AbstractCall::__construct
#11 /vendor/grpc/grpc/src/lib/DefaultCallInvoker.php(31): Grpc\DefaultCallInvoker::UnaryCall
#10 /vendor/grpc/grpc/src/lib/BaseStub.php(278): Grpc\BaseStub::Grpc\{closure}
#9 /vendor/grpc/grpc/src/lib/BaseStub.php(545): Grpc\BaseStub::_simpleRequest
```

**Comment by TobiasGrether** [comment]
Yeah this is definitely an issue, it makes grpc unusable with newer php versions at the moment. Any clue when we can expect a fix for this?

**Comment by brettmc** [comment]
Fixed by #30997 which I believe went into v1.51.0 release.
Given the bug you referred to is still not fixed, I wonder if #30997 could be back-patched into an earlier version (eg 1.49.x or 1.50.x) ?

**Comment by TobiasGrether** [comment]
After recompiling with the latest version, this issue is resolved.

**Comment by nocive** [comment]
latest versions are not usable with php-fpm since 1.50.0, see https://github.com/grpc/grpc/issues/31772
