### ISSUE TITLE
Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.

### ISSUE THREAD

**Issue by ancalita** [grpc/grpc#33110]
### What version of gRPC and what language are you using?

gRPC version `1.54.0`
Issue seen across Python 3.8 / 3.9 / 3.10

### What operating system (Linux, Windows,...) and version?

Ubuntu-22.04, Windows 2019, macOS Ventura 13.3.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.8 / 3.9 / 3.10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

We implemented an Open Telemetry collector using TLS and the unit test for this component has started failing consistently in the CI and locally since Thu 11th May with the error named in the title.

We are using the following code to extract credentials from a self-signed certificate:
```
            with open(cfg.kwargs.get("root_certificates"), "rb") as f:
                root_cert = f.read()
            credentials = grpc.ssl_channel_credentials(root_certificates=root_cert)
```

Then these credentials are passed to an instance of `OTLPSpanExporter` imported from `opentelemetry.exporter.otlp.proto.grpc.trace_exporter`.

### What did you expect to see?

This unit test has been passing consistently for the past 1 year, it started failing at every run since Thu 11-May 2023.
Could this be related to the `grpcio` releases made on Wed 10th May? Any help is much appreciated!

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

In the captured stderr, we saw the following info:
```
2023-05-11 12:00:19 WARNING  opentelemetry.exporter.otlp.proto.grpc.exporter  - Transient error StatusCode.UNAVAILABLE encountered while exporting span batch, retrying in 2s.
E0511 12:00:21.547574805    2285 ssl_transport_security.cc:1420]       Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by XuanWang-Amos** [comment]
Can you try another version of gRPC and see if you still have the same issue? And also, can you provide more information on your certificate? Is it possible that the certificate expired?

**Comment by ancalita** [comment]
> can you provide more information on your certificate? Is it possible that the certificate expired?

We checked that using this command `cat <path-to-certificate> | openssl x509 -noout -enddate`and the result was `notAfter=May 10 10:31:00 2027 GMT`.

> Can you try another version of gRPC and see if you still have the same issue?

The issue is that grpc is not a direct dependency in our codebase, it gets installed with `opentelemetry` dependencies. Is there a particular version I should upgrade/downgrade to? I can look into upgrading the `opentelemetry` dependencies also.
