### ISSUE TITLE
[PHP] Slow extension installing time

### ISSUE THREAD

**Issue by shyim** [grpc/grpc#33112]
### Is your feature request related to a problem? Please describe.
GRPC extension installation takes 10-20 minutes. 
This is for me wasted time / wasted cpu cycles for every user.

### Describe the solution you'd like
Try to link possible libraries instead of compiling:
- re2
- boringssl
- abseil-cpp
- ...

So the compile time can be done faster.

### Describe alternatives you've considered
Caching the result for other people

**Comment by gplanchat** [comment]
The discussion has also taken place in #34278 and #23626

**Comment by alto-php** [comment]
For further discussion, please go to #34278
