### ISSUE TITLE
Number of concurrent streams are not increasing even after setting GRPC_ARG_MAX_CONCURRENT_STREAMS

### ISSUE THREAD

**Issue by karthik-kinara** [grpc/grpc#33111]
### What version of gRPC and what language are you using?
1.51.1

### What operating system (Linux, Windows,...) and version?
Linux, centos-8

### What runtime / compiler are you using (e.g. python version or version of gcc)
9.4.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Either with single client or multiple clients, the maximum number of streams that can server accept is 15.
Even when I tried to set the below arguments for client even then the max number of streams were 15.

```
grpc::ChannelArguments channel_args;
  channel_args.SetInt(GRPC_ARG_MAX_CONCURRENT_STREAMS, 30);
  std::shared_ptr<::grpc::Channel> channel = grpc::CreateCustomChannel(server_address,grpc::InsecureChannelCredentials(), channel_args);
```

  I have even tried to set on server as well but of no use.

```
builder.AddChannelArgument(GRPC_ARG_MAX_CONCURRENT_STREAMS,200);
```

### What did you expect to see?
to enable more streams between server and either single or multiple clients

### What did you see instead?
its always 15 streams either with one client or multiple clients and when i enable more streams the processes get stuck

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
MAX_CONCURRENT_STREAMS defaults to uint32 max (4294967295), so you should not need to set it.

Can you show your client code and server code?  If your server is using the C++ sync API, maybe you are running into some other limit, like a thread pool size.

**Comment by karthik-kinara** [comment]
@markdroth i am using bi-directional reactor apis on both side. 
I have attached the proto file, server transport header and one of the client's header file.
Please let me know if you need any other information. 

[transport_server.h.txt](https://github.com/grpc/grpc/files/11493872/transport_server.h.txt)
[inference_server.proto.txt](https://github.com/grpc/grpc/files/11493873/inference_server.proto.txt)
[client_server_configuration.h.txt](https://github.com/grpc/grpc/files/11493874/client_server_configuration.h.txt)

**Comment by karthik-kinara** [comment]
@markdroth  when i tried to build a simple example with single rpc to reproduce the error, it worked fine. so i will try out with multiple rpcs and multiple streams and will reach out if i see any issue.
thanks for help.

**Comment by markdroth** [comment]
Note that each RPC is a single stream, so if the problem you're trying to reproduce is a limit on the number of simultaneous streams, I don't think you'll be able to reproduce that with a single RPC.

**Comment by karthik-kinara** [comment]
@markdroth yeah each rpc is a single stream ans we have a use case where each rpc is invoked multiple times in parallel. so earlier when i mentioned i was trying with single rpc, i was invoking the same rpc multiple times in parallel

**Comment by markdroth** [comment]
Ah, okay -- I think I understand what you mean, but I think you're misusing terminology here in a way that confused me.  The term "RPC" is generally used to indicate an actual call that you are making, not for a specific RPC method definition.  So I think what you meant to say was that you are making multiple RPCs in parallel to the same method.

Anyway, please let us know if you're able to come up with a reproduction case that we can try out.
