### ISSUE TITLE
 gRPC C# Tools 0.7.0 nuget does not include protoc

### ISSUE THREAD

**Issue by diogojc** [grpc/grpc#3312]
The protoc executable seems to be missing in the [0.7.0 grpc c# tools nuget](https://www.nuget.org/api/v2/package/Grpc.Tools/0.7.0).

**Comment by jtattermusch** [comment]
protoc.exe is now part of the Google.Protobuf  package - which is where it is actually belongs. We used to ship protoc.exe with Grpc.Tools as a temporary measure before Google.Protobuf was officially released.

This has been reflected in updated version of route guide example https://github.com/grpc/grpc/tree/master/examples/csharp/route_guide (but we haven't published that howto on grpc.io yet).
