### ISSUE TITLE
Remove reference docs from master

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc#3313]
- [ ] add make rules for building the docs
  - this allows the docs to be regenerated at tags/releases (versioning)
   - enables the creation of grpc-xxx-docs debian packages
- [x] remove the reference docs on master; the generated docs will no longer need to be checked in, and so we should only have them on the gh-pages branch which github publishes

**Comment by jtattermusch** [comment]
Note that C# docs is generated on Windows with sandcastle tool. Thus, having a make rule to regenerate  for C# is unrealistic.

**Comment by ctiller** [comment]
There's a shell script (tools/doxygen/run_doxygen.sh) - is this sufficient?

**Comment by jtattermusch** [comment]
I think at least for now we have a sufficient story for regenerating the docs.
