### ISSUE TITLE
Avoid `AsyncAuthInterceptor` deadlock in blocking calls

### ISSUE THREAD

**Issue by coudy** [grpc/grpc#33142]
### Is your feature request related to a problem? Please describe.

I have a WPF app with async authentication code for refreshing tokens and re-authenticating, executed as an `AsyncAuthInterceptor` in a `CallCredentials` object. Essentially, it does `var token = await RefreshTokenAsync() ?? await AuthenticateInteractivelyAsync()` and adds this as a header. Note that the latter method needs to be called on the UI thread.

This approach works fine for async calls on the UI thread. However, due to various limitations I have a few gRPC calls that sometimes need to be invoked as blocking on the UI thread, and this deadlocks, because under the hood gRPC does `.GetAwaiter().GetResult()` on the auth interceptor in blocking calls.

If I could detect from the auth interceptor whether I'm in a blocking vs async gRPC call, I could run `RefreshTokenAsync` with `Task.Run` and avoid calling `AuthenticateInteractivelyAsync()`. This would be acceptable, since I have only a handful of blocking calls and interactive auth isn't requested very often. However, since I can't tell whether I'm in a blocking call, I can't see a way to support interactive authentication at all.

In other words, `AsyncAuthInterceptor` makes the implicit assumption that if you're in a single thread context (e.g. UI), either all your gRPC calls are async or your auth interceptor doesn't await.

### Describe the solution you'd like

One of the following:

1. Add a way to distinguish between blocking and async calls in `AsyncAuthInterceptor`, e.g. a `callType` argument or a separate method.
2. Allow running async code in `Interceptor.AsyncUnaryCall` implementations. `Interceptor` already knows about call types but I understand you can't execute async code before the continuation.

### Describe alternatives you've considered

None other than hacks like setting a `ThreadLocal` before a blocking call and detecting it in the auth interceptor.

### Additional context

I'm using the latest `Grpc.Net.Client` nuget package.

**Comment by tonydnewell** [comment]
Here is where issues relating to the `Grpc.Core` implementation are raised.  It looks like you are using `Grpc.Net.Client` which is part of _gprc/grpc-dotnet_ project therefore please ask this in https://github.com/grpc/grpc-dotnet/issues

**Comment by tonydnewell** [comment]
If you are using `Grpc.Net.Client` then yes I'm sure.  The namespace has been kept the same to allow migrating of apps from grpc/grpc to grpc/grpc-dotnet.  E.g. https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Core.Api/AsyncAuthInterceptor.cs is in the grpc-dotnet project.
