### ISSUE TITLE
how send content-type in header  use c++

### ISSUE THREAD

**Issue by rocheldebbrarmke** [grpc/grpc#33235]
i write c++/tls client use gprc , it work fine.  but when i use cdn, server can not recv request,

i found cf doc:
https://developers.cloudflare.com/support/network/understanding-cloudflare-grpc-support/

Requirements
Your gRPC endpoint must listen on port 443. 
Your gRPC endpoint must support TLS and HTTP/2.
HTTP/2 must be advertised over ALPN.
Use application/grpc or application/grpc+<message type (for example: application/grpc+proto) for the Content-Type header of gRPC requests.

----

it seem to use  Content-Type header  in client , but i use 

	grpc::ClientContext context;
	// Setting custom metadata to be sent to the server
	context.AddMetadata("content-type", "application/grpc");

it not work!!!

who can tell me, how to solve this question?

**Comment by markdroth** [comment]
gRPC automatically sends that content-type header, it's not something you need to do in your application.

I'm not sure why your CDN setup isn't working, but I don't think it's because of the content-type header.
