### ISSUE TITLE
Grpc PHP extension causing latency

### ISSUE THREAD

**Issue by vishwarajanand** [grpc/grpc#33259]
### What version of gRPC and what language are you using?
1.54.0 (occurs on other versions too)

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
php (installed using `pecl install grpc`)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

When I try to fetch large number of docs (20K) from Firestore server using a `Firestore::runQuery` or `Firestore::listDocuments`call, it takes unusually high amount of time (100+ seconds). nodejs performance for the same is `<10 seconds`.

<details>
<summary>Code to get time elapsed in seconds Firestore documents</summary>

```
require_once __DIR__ . '/vendor/autoload.php';

use Google\Cloud\Firestore\FirestoreClient;

$client = new FirestoreClient();
$collection = $client->collection(uniqid());

function insertDocuments($client, $collection, $count)
{
    $bulkwriter = $client->bulkWriter();
    for ($i = 0; $i < $count; $i++) {
        $newDoc = $collection->newDocument();
        $bulkwriter->create($newDoc, [
            'foo' => 'bar',
            'index' => "{$i}"
        ]);
    }
    $bulkwriter->flush();
}

// insert 20K docs
const DOCS_ADDED = 20000;
insertDocuments($client, $collection, DOCS_ADDED);

// validate count equals 20K
$count = $collection->count();
print ("{$count} documents found the collection.".PHP_EOL);

function calcTimeElapsedInMillis($callable)
{
    $startTime = microtime(true)*1000.0;
    $callable();
    $endTime = microtime(true)*1000.0;
    $timeElapsedInMillis = $endTime - $startTime;
    return $timeElapsedInMillis;
}

function callGetDocuments($collection, $expectedCount)
{
    $documents = $collection->limit($expectedCount)->documents();
    $actualCount = count(iterator_to_array($documents));
    if ($actualCount != $expectedCount) {
        print("Found {$actualCount} expected {$expectedCount}".PHP_EOL);
    }
}

function callListDocuments($collection, $expectedCount)
{
    $documents = $collection->listDocuments([
        'pageSize' => $expectedCount,
        'resultLimit' => $expectedCount
    ]);
    $actualCount = count(iterator_to_array($documents));
    if ($actualCount != $expectedCount) {
        print("Found {$actualCount} expected {$expectedCount}".PHP_EOL);
    }
}

function runTests($collection, $testCaseCount)
{
    echo "| Documents Count | Fetch Seconds in documents() | Fetch Seconds listDocuments() |".PHP_EOL;
    echo "|-------------|---------------------|--------------------|".PHP_EOL;
    $testCases = generateTestCases($testCaseCount);
    foreach ($testCases as $docCount) {
        $timeElapsedGetDocs = calcTimeElapsedInMillis(function () use ($collection, $docCount) {
            return callGetDocuments($collection, $docCount);
        });
        $timeElapsedGetDocs = ceil($timeElapsedGetDocs / 1000.0);
        $timeElapsedListDocs = calcTimeElapsedInMillis(function () use ($collection, $docCount) {
            return callGetDocuments($collection, $docCount);
        });
        $timeElapsedListDocs = ceil($timeElapsedListDocs / 1000.0);
        print ("|{$docCount}|{$timeElapsedGetDocs}|{$timeElapsedListDocs}|".PHP_EOL);
    }
    echo "Test completed successfully.".PHP_EOL;
}

function generateTestCases($testCase)
{
    $testCases = [];
    for ($i = 0; $i < $testCase; $i++) {
        $testCases[] = DOCS_ADDED / pow(10, $i);
    }
    return $testCases;
}
runTests($collection, 4);
```
</details>

It gives the following log:

| Documents Count | Fetch Seconds in documents() | Fetch Seconds listDocuments() |
|-------------|---------------------|--------------------|
|20000|106|104|
|2000|11|11|
|200|2|2|
|20|1|1|

### What did you expect to see?
The time range here should not linearly increase with doc count. It seems the grpc extension is not able to handle the large doc count properly.

### What did you see instead?
I expect the time for fetching 20K documents to be `<10 seconds`.

I profiled the php process running the above code and it showed this flame which shows that most of the time is spent in `Grpc\call::startBatch` and `Grpc\ServerStreamingCall::responses`(you need to download & open ![flame.svg](https://github.com/grpc/grpc/assets/7369612/65379014-4309-4138-a3a8-b8f53f1a8c10) file in chrome and hover over the largest bars in red. This was generated by a tool called phpspy.

### Anything else we should know about your project / environment?

This is actually a sub-issue that I am reporting on behalf of an external user who reported this issue on https://github.com/googleapis/google-cloud-php/issues/4429. Surprisingly, the user reported (and I validated) that a similar nodejs script fetches all 20K documents in under 10 seconds.

Let me know if I need to do further debugging, I dont know how to profile grpc or node.

**Comment by alto-php** [comment]
I couldn't reproduce this issue, using the same code, I got the following test results:

From GCP VM:
| Documents Count | Fetch Seconds in documents() | Fetch Seconds listDocuments() |
|-------------|---------------------|--------------------|
|20000|7|7|
|2000|1|1|
|200|1|1|
|20|1|1|

From my laptop:
| Documents Count | Fetch Seconds in documents() | Fetch Seconds listDocuments() |
|-------------|---------------------|--------------------|
|20000|4|4|
|2000|1|1|
|200|1|1|
|20|1|1|

**Comment by vishwarajanand** [comment]
Confirmed that this is indeed the timing that I can see on a clean setup.
Maybe it's a transient issue that i saw. 🥀
