### ISSUE TITLE
Update  Xcode GM  and Protobuf (3.0.0-alpha-4.1) I got some  Error.

### ISSUE THREAD

**Issue by sipdar** [grpc/grpc#3326]
<img width="757" alt="2015-09-11 5 55 12" src="https://cloud.githubusercontent.com/assets/1386469/9812202/49a08ae8-58ae-11e5-8f91-ce0ede1ba089.png">

<img width="912" alt="2015-09-11 5 45 25" src="https://cloud.githubusercontent.com/assets/1386469/9812230/7229c5c4-58ae-11e5-815f-d69cc4dfce38.png">

**Comment by jclardy** [comment]
Same here, it looks like the protobuf library was updated and changed the names of things. I tried specifying 3.0.0-alpha-3 but now I am having issues running protoc.

**Comment by jcanizales** [comment]
Hi @sipdar and @jclardy, sorry that this issue fell through the cracks.

As Jason said, this error showed up when the version of `protoc` used to generate the `.pbobjc.h/m` files was older than the latest Protobuf runtime library. The solution to it is to do `brew update` on the grpc and protobuf recipes. For some people, Homebrew has failed to update the recipes, and they've solved it by uninstalling them and reinstalling them with `curl -fsSL https://goo.gl/getgrpc | bash -`.

Please let me know if you were able to fix it, or if it's still causing you trouble.
Cheers,
Jorge

**Comment by hsaliak** [comment]
Closing stale issue.
