### ISSUE TITLE
GRPC compression hurting CPU performance.

### ISSUE THREAD

**Issue by yash30201** [grpc/grpc#33265]
### What version of gRPC and what language are you using?
Release Date          2023-04-17 18:46:47
Release Version       1.54.0 (stable)
API Version           1.54.0 (stable)

### What operating system (Linux, Windows,...) and version?
gLinux - 6.1.20-2rodete1-amd64

### What runtime / compiler are you using (e.g. python version or version of gcc)
php7.4

### What did you do?
* I tried to compress request messages in [example](https://github.com/grpc/grpc/tree/master/examples/php/Helloworld) php client side.
  * I compressed in per call basis by setting the `grpc-internal-encoding-request` header metadata to `gzip`.
  * Verified the compression by setting grpc debug flags: `GRPC_VERBOSITY=info` and `GRPC_TRACE=compression`.
  * Created a script to send multiple request in a loop with each request's size being ~1MB.
* For server, used the nodeJS example [server](https://github.com/grpc/grpc/tree/master/examples/node/dynamic_codegen).
* Ran the client in a docker container and observed it's performance and bandwidth using cAdvisor.

### What did you expect to see?
I expected to see ~47% bandwidth savings(shown in GRPC logs) and less than 2 times increase in CPU usage for realistic repeated twitter like data as this is the case in Java grpc.

### What did you see instead?
Bandwidth savings are more than expected but the cpu utilisation increases by 5 times atleast. Tried the same using PHP pub sub client and saw a cpu increase of 3 times with the slightly more than expected bandwidth savings.

### Anything else we should know about your project / environment?
No

**Comment by alto-php** [comment]
Was the CPU of node JS server increased 5x as well?
What's your hardware configuration?
Was client and server on the same host?
How much qps did you get with and without compression?
Can you share your test script?

**Comment by yash30201** [comment]
Thanks @alto-php for looking into this. Below are some more info regarding this as requested:-

**Hardware configuration**
It's a cloud machine with 48 CPUs with 2 cores each and 192 gb Ram. Debian OS.

**CPU for Node JS server**
I'm running the docker and the node js server on the same system. So it's hard to say how much CPU increase only for NodeJs server.

**Code to repro**
For NodeJS server
* I just ran the [example](https://github.com/grpc/grpc/tree/master/examples/node/dynamic_codegen) which is provided in the grpc repo.

For PHP Client
* Ran this client in a separate docker container.
* The container used this [php image](gcr.io/cloud-devrel-kokoro-resources/php74:latest)
* Used the [HelloWorld](https://github.com/grpc/grpc/tree/master/examples/php) example.
* I modified the `BaseStub.php > __simpleRequest()` method by adding the compression header to enable compression in per call basis as follows:
```php
protected function _simpleRequest(
        $method,
        $argument,
        $deserialize,
        array $metadata = [],
        array $options = []
 ) {
        // Added this line
        $metadata['grpc-internal-encoding-request'] = ['gzip'];
        // Rest of the code...
 }
```
* Modified the [greeter_client.php](https://github.com/grpc/grpc/blob/master/examples/php/greeter_client.php) so that it sends request in loop iterating 3 times and logs the QPS.
```php
    $starttime = microtime(true);
    $request = new Helloworld\HelloRequest();
    $request->setName($name);
    for ($x = 0 ; $x < 300 ; ++$x) {
        list($response, $status) = $client->SayHello($request)->wait();
    }
    $endtime = microtime(true);
    $timediff = $endtime - $starttime;
    printf('Time taken is: ' . $timediff . ' and QPS = ' . 1000 / $timediff . PHP_EOL);
```

**Exact CPU utilisation**
Got this from running `docker stats`. 100% => Full utilisation of 1 CPU I think because it shoots more than 10% when simultaneous scripts are run
Without compression: 
* CPU - ~12.5%
* QPS - ~356 queries per second

With Compression:
* CPU - ~97%
* QPS - ~71.5 queries per second

**Comment by alto-php** [comment]
Thanks for the detailed numbers.

First of all, you don't need to change BaseStub.php  to enable compression, you can just pass the metadata to `SayHello` for per-call compression. Alternatively you can also enable compression to the channel as documented [here](https://github.com/grpc/grpc/tree/master/src/php#compression).

Regarding the CPU utilization, sending requests in a loop should always get you close to 100% cpu utilization, you can try run the test longer so you will observe that CPU jumped to 100%.

Compression is done in c code where the overhead should be similar to all languages that use c-core. 
Following are my test resutls using cpp server (kept getting 'invalid wire type 7' errors with nodejs server) with 1MB payload, where the cpu usage is close to 100% with php, and with cpp it's like 2x CPU and half the QPS.

Given the test client/server basically does nothing but send and receive the data, it make sense that compress/decompress cost most of the CPU as it's mostly compression vs copying. For a production servers/clients that has other logics, the cost of compression should become less significant. If CPU utilization is an issue, you can also try different compression algorithms and levels to find the right balance for your use case.

Test results:

with compression:
client: 83%, server: 18%, QPS: 12

without compression:
client: 94%, server: 9%, QPS: 23

**Comment by yash30201** [comment]
@alto-php, thanks for all the insights.
> Regarding the CPU utilization, sending requests in a loop should always get you close to 100% cpu utilization, you can try run the test longer so you will observe that CPU jumped to 100%.

I increased the loop count to 10000 in without compression and still observe <15% utilisation.
