### ISSUE TITLE
Python gevent + gRPC server occurs spawn loop stacks, which eventually leads to 100% CPU usage of the process.

### ISSUE THREAD

**Issue by hirorogithub** [grpc/grpc#33354]
### What version of gRPC and what language are you using?
Python 2.7.13
grpcio                        1.41.1
grpcio-health-checking        1.33.2
grpcio-opentracing            1.1.4
grpcio-tools                  1.27.2
gevent                        1.4.0
greenlet                      1.1.3

### What operating system (Linux, Windows,...) and version?
k8s run on  debian 9

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.13

### What did you do?
We use gevent+grpc server to provide some string parsing service, which will read some data from mysql,hbase,redis,then run some thing like regular expression,json loads to parse.

### What did you see instead?
The CPU usage of my grpc service slowly goes from 50% to 100% over half an hour.
The average response time of the process gradually increases from 50ms, increasing by 50ms per day. As time goes on, this causes the health check to exceed the specified time, leading to the process being considered stuck by k8s and being  restarted.

When I try to debug and print the `gevent.util.format_run_info()`
I got a stack trace that indicates an almost infinite loop like:
```
+--- <Greenlet "Greenlet-2" at 0x7f371a81cdb8: socket_read_async(<grpc._cython.cygrpc.SocketWrapper object at 0x7f3)>
 :          Parent: <Hub '' at 0x7f372b17a940 epoll default pending=0 ref=16 fileno=10 resolver=<gevent.resolver_thread.Resolver at 0x7f3726b58710 pool=<ThreadPool at 0x7f3726b58750 0/2/10 hub=<Hub at 0x7f372b17a940 thread_ident=0x139875011044800>>> threadpool=<ThreadPool at 0x7f3726b58750 0/2/10 hub=<Hub at 0x7f372b17a940 thread_ident=0x139875011044800>> thread_ident=0x7f373058a5c0>
 :          Running:
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 300, in recv
 :              self._wait(self._read_event)
 :          Spawned at:
 :            File "/home/gpx/app/charon/service/grpc_server.py", line 2, in <module>
 :              import gevent
 :            File "/home/gpx/app/charon/service/grpc_server.py", line 1605, in main
 :              def main(host, port, worker):
 :            File "/home/gpx/app/charon/service/grpc_server.py", line 1540, in serve
 :              def serve(host, port, options):
 :            File "/usr/local/lib/python2.7/dist-packages/grpc_opentracing/grpcext/_interceptor.py", line 362, in start
 :              def start(self, *args, **kwargs):
 :            File "/usr/local/lib/python2.7/dist-packages/grpc_opentracing/grpcext/_interceptor.py", line 362, in start
 :              def start(self, *args, **kwargs):
 :            File "/usr/local/lib/python2.7/dist-packages/grpc/_server.py", line 978, in start
 :              def start(self):
 :            File "/usr/local/lib/python2.7/dist-packages/grpc/_server.py", line 925, in _start
 :              def _start(state):
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
 :              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
 :              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
 :              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
 :              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
 :              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
 :              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
 :            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
..... occurs many times!!
```
At the beginning of the process, the output is only 500KB, but after a few minutes, the output grows to 11.6MB. output is full of 
```
:            File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 382, in spawn
:              def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
```
 

May be some compatibility issue between my grpc and gevent?

**Comment by gnossen** [comment]
So I've got good news and I've got bad news. gRPC support for gevent was completely reimplemented in [1.45.0](https://github.com/grpc/grpc/releases/tag/v1.45.0), which should have resolved many issues with gRPC+gevent. Unfortunately, we haven't supported Python 2.X since `1.39`, so you'll likely have to jump to Python 3.X to take advantage of this.

**Comment by hirorogithub** [comment]
Thank you for your response. I will try to restart the processes regularly.

**Comment by hirorogithub** [comment]
> 
Thank you for your response. I will try to restart the processes regularly.

**Comment by hirorogithub** [comment]
@gnossen Fortunately, I solved this problem by just upgrading the version of gevent to 22.10.2( which is the last verison support py2.7). ^_^
