### ISSUE TITLE
grpc cpp 0_11_0 create stub error with msvc 2013 with preprocessor definition  _USE_32BIT_TIME_T

### ISSUE THREAD

**Issue by Zerqkboo** [grpc/grpc#3336]
I build my grpc 0_11_0 with default settings under `/vsprojects`, and get all the cpp libs. When I used it in my project with very simple rpc server and client, I found that `NewStub` will be created without any error messages, but afterwards I called a rpc method, the program crashed. I tested again without the preprocesser definition `_USE_32BIT_TIME_T` in all `/vsprojects`, then everything is ok.

My environment is msvc 2013 in windows 10.

**Comment by jtattermusch** [comment]
#4315
