### ISSUE TITLE
Update cAres dependency to 1.19.1 due to vulnerabilities

### ISSUE THREAD

**Issue by phallot** [grpc/grpc#33363]
### Is your feature request related to a problem? Please describe.
gRPC depends on the [cAres](https://github.com/c-ares/c-ares) lib. Currently, [gRPC uses version 1.17.2](https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L333) from 2021.  
Recently, [version 1.19.1 was released ](https://github.com/c-ares/c-ares/releases/tag/cares-1_19_1), which includes various security vulnerabilities fixes, including a CVE High.

### Describe the solution you'd like
Update gRPC to use cAres 1.19.1

### Describe alternatives you've considered
?

### Additional context
None.

**Comment by drfloob** [comment]
This was done in https://github.com/grpc/grpc/pull/33392
