### ISSUE TITLE
compiled gem is 1.6 Gigabytes

### ISSUE THREAD

**Issue by josh-m-sharpe** [grpc/grpc#33412]
### What version of gRPC and what language are you using?
ruby 3.2.3
grpc 1.55.0

### What operating system (Linux, Windows,...) and version?
amazonlinux:2
OSX 13.2.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
whatever bundler uses? gcc?

### What did you do?
```
mkdir grpcwut
cd grpcwut
echo "source 'https://rubygems.org'\ngem 'grpc'" > Gemfile
rvm use 3.2.2 # ruby version probably doesn't matter much
bundle
```

### What did you expect to see?
a reasonably sized gem

### What did you see instead?
1.0GB compiled in $GEM_HOME/ruby-3.2.2/gems/grpc-1.55.0
```
du -sh $GEM_HOME/gems/grpc-1.55.0
1.0G	$GEM_HOME/ruby-3.2.2/gems/grpc-1.55.0
```

### Anything else we should know about your project / environment?
On OSX I see 1.0GB (which is what the above code snippets are from)
On Amazonlinux:2 I see 1.6GB - not sure if that is filesystem or compiler. Not sure it matters.

For comparison's sake, the next biggest gem I see is google-api-client at 73M and google-ads-googleads at 27MB the overwhelming majority of gems in our very large project are under 10MB.  

1 Gigabyte is a few orders of magnitude beyond reasonability.  It makes containerizing an application with grpc unwieldy.

**Comment by russell** [comment]
Yep we saw the same

From our experiments, it looks like building the gem for source results in an unstripped library and all the object files being left in the gem directory resulting in ~1.7G of unnecessary files left lying around.

There is a stripped lib created, but the makefile fails to remove the `objs` and `libs` dir.

**Comment by josh-m-sharpe** [comment]
thanks @russell for the confirmation (and better analysis)

Commeting to keep this alive as aI saw a notice it would be closed

**Comment by josh-m-sharpe** [comment]
Hah - I definitely downloaded the 32-bit rasp pi OS.  oops.  Will rebuild everything and re-test.

**Comment by alto-ruby** [comment]
It's possible to remove the `objs` directory but not `libs`, which can save about half the space.
This is because they are grpc-core libraries that are built before making the ruby extension, cleaning them will cause link failure when making the extension.

**Comment by russell** [comment]
> It's possible to remove the `objs` directory but not `libs`, which can save about half the space. This is because they are grpc-core libraries that are built before making the ruby extension, cleaning them will cause link failure when making the extension.

Yep, but there is a command to strip the debugging symbols, which reduces the size from **814M** to **10M**.

The upstream gem distribution has no debugging symbols, so it would be nice if the stripping would also occur when the gem was built from source.

From what i can tell most of the issues occur because the makefile is copied to a different directory then run, so some commands in make are executed out of context.  I would think that the best way to fix this would be to create a toplevel make file that call's the correct make targets rather than copying the file then appending an extra step to it.

**Comment by alto-ruby** [comment]
@russell Yeah, stip the .a files make sense, updated the PR.
opt install now takes 67M on mac and 83M on linux.
