### ISSUE TITLE
GRPC C++ Ubuntu compilation failing with error "undefined reference to `std::__throw_bad_array_new_length()'"

### ISSUE THREAD

**Issue by varun-cohere** [grpc/grpc#33421]
### What version of gRPC and what language are you using?
1.55.0
libprotoc 23.1

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.03 (5.15.0-1038-realtime #41-Ubuntu SMP PREEMPT_RT)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

1) I compiled and installed the latest grpc and protoc
2) I compiled a few wrapper files under my project using grpc and it compiled successfully as follows:

gcc  -D_GLIBCXX_USECXX17_ABI=0 -I./include -I/home/yeturva/.local/include  `pkg-config --cflags protobuf grpc absl_flags absl_flags_parse` -fPIC -static-libstdc++ -static-libgcc -std=c++17  -c -o ric.pb.o ric.pb.cc
protoc -I . --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ric.proto
gcc  -D_GLIBCXX_USECXX17_ABI=0 -I./include -I/home/yeturva/.local/include  `pkg-config --cflags protobuf grpc absl_flags absl_flags_parse` -fPIC -static-libstdc++ -static-libgcc -std=c++17  -c -o ric.grpc.pb.o ric.grpc.pb.cc
gcc  -D_GLIBCXX_USECXX17_ABI=0 -I./include -I/home/yeturva/.local/include  `pkg-config --cflags protobuf grpc absl_flags absl_flags_parse` -fPIC -static-libstdc++ -static-libgcc -std=c++17  -c -o gRPC_client.o gRPC_client.cc
gcc  -D_GLIBCXX_USECXX17_ABI=0 -I./include -I/home/yeturva/.local/include  `pkg-config --cflags protobuf grpc absl_flags absl_flags_parse` -fPIC -static-libstdc++ -static-libgcc -std=c++17  -c -o gRPC_server.o gRPC_server.cc
gcc  -g ric.pb.o ric.grpc.pb.o gRPC_client.o gRPC_server.o -L/home/yeturva/.local/lib -L/home/yeturva/grpc_latest/grpc/third_party/re2/re2.pc `pkg-config --libs --static protobuf grpc++ absl_flags absl_flags_parse absl_absl_check absl_absl_log absl_algorithm absl_base absl_bind_front absl_bits absl_btree absl_cleanup absl_cord absl_core_headers absl_debugging absl_die_if_null absl_dynamic_annotations absl_flags absl_flat_hash_map absl_flat_hash_set absl_function_ref absl_hash absl_layout absl_log_initialize absl_log_severity absl_memory absl_node_hash_map absl_node_hash_set absl_optional absl_span absl_status absl_statusor absl_strings absl_synchronization absl_time absl_type_traits absl_utility absl_variant` -lutf8_validity -pthread -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -shared -lstdc++ -lstdc++fs
gcc  -fPIC -g -o gRPC_c_wrapper.o -L/home/yeturva/.local/lib -L/home/yeturva/grpc_latest/grpc/third_party/re2/re2.pc `pkg-config --libs --static protobuf grpc++ absl_flags absl_flags_parse absl_absl_check absl_absl_log absl_algorithm absl_base absl_bind_front absl_bits absl_btree absl_cleanup absl_cord absl_core_headers absl_debugging absl_die_if_null absl_dynamic_annotations absl_flags absl_flat_hash_map absl_flat_hash_set absl_function_ref absl_hash absl_layout absl_log_initialize absl_log_severity absl_memory absl_node_hash_map absl_node_hash_set absl_optional absl_span absl_status absl_statusor absl_strings absl_synchronization absl_time absl_type_traits absl_utility absl_variant` -lutf8_validity -pthread -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -shared -lstdc++ -lstdc++fs -c gRPC_c_wrapper.cc
gRPC_c_wrapper.cc: In function ‘void gRPC_free(void*)’:
gRPC_c_wrapper.cc:34:12: warning: deleting ‘void*’ is undefined [-Wdelete-incomplete]
   34 |     delete ptr;
      |            ^~~
gcc  -fPIC ric.pb.o ric.grpc.pb.o gRPC_client.o gRPC_server.o gRPC_c_wrapper.o -g -o test_gRPC -L/home/yeturva/.local/lib -L/home/yeturva/grpc_latest/grpc/third_party/re2/re2.pc `pkg-config --libs --static protobuf grpc++ absl_flags absl_flags_parse absl_absl_check absl_absl_log absl_algorithm absl_base absl_bind_front absl_bits absl_btree absl_cleanup absl_cord absl_core_headers absl_debugging absl_die_if_null absl_dynamic_annotations absl_flags absl_flat_hash_map absl_flat_hash_set absl_function_ref absl_hash absl_layout absl_log_initialize absl_log_severity absl_memory absl_node_hash_map absl_node_hash_set absl_optional absl_span absl_status absl_statusor absl_strings absl_synchronization absl_time absl_type_traits absl_utility absl_variant` -lutf8_validity -pthread -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -shared -lstdc++ -lstdc++fs -lstdc++ `pkg-config --libs protobuf grpc++` -lgrpc++_reflection test_gRPC.cc
mkdir -p /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/gRPC//../bin/gRPC
cp /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/gRPC//*.o /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/gRPC//../bin/gRPC
root@ran1311:/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/gRPC# ls ../bin/gRPC/
gRPC_client.o  gRPC_c_wrapper.o  gRPC_server.o  ric.grpc.pb.o  ric.pb.o

3) Once above object files are generated, I use them to compile a different binary, but it is yielding unresolved symbols in the linking stage as follows:
/usr/bin/ld: /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gRPC/ric.grpc.pb.o: in function `__gnu_cxx::new_allocator<std::unique_ptr<grpc::internal::RpcServiceMethod, std::default_delete<grpc::internal::RpcServiceMethod> > >::allocate(unsigned long, void const*)':
ric.grpc.pb.cc:(.text._ZN9__gnu_cxx13new_allocatorISt10unique_ptrIN4grpc8internal16RpcServiceMethodESt14default_deleteIS4_EEE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorISt10unique_ptrIN4grpc8internal16RpcServiceMethodESt14default_deleteIS4_EEE8allocateEmPKv]+0x49): **undefined reference to `std::__throw_bad_array_new_length()**

4) The compiler flags and libraries provided for compiling step 3 are as follows:

gcc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/../third_party/cohere/ -I/opt/dpdk-21.11//x86_64-native-linuxapp-gcc/include// -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/dpdk_int/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/porting/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/utility/inc/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/logging/inc/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/alarm/inc/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/common/inc/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/advLogger/src/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/cspl/inc/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_CU/interfaces/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/interfaces/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_CU/cu_up/common/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/common/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/common/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/interfaces/oam/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/interfaces/du_manager/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/interfaces/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/ssb_manager/inc  -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/common_port/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/utility/comm_mgr/framework/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/utility/comm_mgr/service/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/common/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/bwp_manager/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/utility/core/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/rach_manager/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/drx_manager/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/execution_scheduler/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/dlsch_manager/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/strategy/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/resource_manager/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/interfaces/phy/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/interfaces/phy/inc/astri/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/interfaces/phy/inc/itri/ -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/common/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gtpuPacketRelay/packetRelay/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gtpuPacketRelay/egtpu/shared/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gtpuPacketRelay/egtpu/stack/fsm/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/interfaces/inc -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/interfaces/phy/inc/intel/ -I/opt/dpdk-21.11//x86_64-native-linuxapp-gcc/include -I/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/scheduler/paging_manager/inc -I/opt/dpdk-21.11//build -I/opt/dpdk-21.11//lib/eal/include -I/opt/dpdk-21.11//lib/eal/linux/include -I/opt/dpdk-21.11//config /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gRPC/ric.grpc.pb.o /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gRPC/ric.pb.o /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gRPC/gRPC_c_wrapper.o /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gRPC/gRPC_server.o /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gRPC/gRPC_client.o mac_rlc_main.o -o /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/bin/gnb_du_layer2 -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/main/lib -lrlcmain -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gtpuPacketRelay/packetRelay/bin -lrelay -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gtpuPacketRelay/egtpu/stack/ -legtpu -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/lib -llogging -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/lib -lalarm -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/lib -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/interfaces/lib -lduintf -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/common/lib  -lrlccommon -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/interfaces/lib  -lrlcinterface -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/ammode/lib  -lrlcammode -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/ummode/lib  -lrlcummode -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/timer/lib   -lrlcTimer -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/core/common/lib  -lrlccommon -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/mac/lib -lmac -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/common/lib -lducommonutils -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/rlc/rlc_lower/lib -lrlcLibrary -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/gNB_DU/interfaces/lib -lduintf -L/home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/lib/ -lcommon -L/usr//lib -lm -lrt -lpthread -latomic                      -Wl,--whole-archive -Wl,/usr/lib64/libnuma.so -Wl,--whole-archive -L/usr/local/lib/x86_64-linux-gnu -l:librte_common_cpt.a -l:librte_common_dpaax.a -l:librte_common_iavf.a -l:librte_common_octeontx.a -l:librte_common_octeontx2.a -l:librte_bus_auxiliary.a -l:librte_bus_dpaa.a -l:librte_bus_fslmc.a -l:librte_bus_ifpga.a -l:librte_bus_pci.a -l:librte_bus_vdev.a -l:librte_bus_vmbus.a -l:librte_common_cnxk.a -l:librte_common_qat.a -l:librte_common_sfc_efx.a -l:librte_mempool_bucket.a -l:librte_mempool_cnxk.a -l:librte_mempool_dpaa.a -l:librte_mempool_dpaa2.a -l:librte_mempool_octeontx.a -l:librte_mempool_octeontx2.a -l:librte_mempool_ring.a -l:librte_mempool_stack.a -l:librte_dma_cnxk.a -l:librte_dma_dpaa.a -l:librte_dma_hisilicon.a -l:librte_dma_idxd.a -l:librte_dma_ioat.a -l:librte_dma_skeleton.a -l:librte_net_af_packet.a -l:librte_net_ark.a -l:librte_net_atlantic.a -l:librte_net_avp.a -l:librte_net_axgbe.a -l:librte_net_bnxt.a -l:librte_net_bond.a -l:librte_net_cnxk.a -l:librte_net_cxgbe.a -l:librte_net_dpaa.a -l:librte_net_dpaa2.a -l:librte_net_e1000.a -l:librte_net_ena.a -l:librte_net_enetc.a -l:librte_net_enetfec.a -l:librte_net_enic.a -l:librte_net_failsafe.a -l:librte_net_fm10k.a -l:librte_net_hinic.a -l:librte_net_hns3.a -l:librte_net_i40e.a -l:librte_net_iavf.a -l:librte_net_ice.a -l:librte_net_igc.a -l:librte_net_ionic.a -l:librte_net_ixgbe.a -l:librte_net_kni.a -l:librte_net_liquidio.a -l:librte_net_memif.a -l:librte_net_netvsc.a -l:librte_net_nfp.a -l:librte_net_ngbe.a -l:librte_net_null.a -l:librte_net_octeontx.a -l:librte_net_octeontx2.a -l:librte_net_octeontx_ep.a -l:librte_net_pfe.a -l:librte_net_qede.a -l:librte_net_ring.a -l:librte_net_sfc.a -l:librte_net_softnic.a -l:librte_net_tap.a -l:librte_net_thunderx.a -l:librte_net_txgbe.a -l:librte_net_vdev_netvsc.a -l:librte_net_vhost.a -l:librte_net_virtio.a -l:librte_net_vmxnet3.a -l:librte_raw_cnxk_bphy.a -l:librte_raw_dpaa2_cmdif.a -l:librte_raw_dpaa2_qdma.a -l:librte_raw_ntb.a -l:librte_raw_skeleton.a -l:librte_crypto_bcmfs.a -l:librte_crypto_caam_jr.a -l:librte_crypto_cnxk.a -l:librte_crypto_dpaa_sec.a -l:librte_crypto_dpaa2_sec.a -l:librte_crypto_nitrox.a -l:librte_crypto_null.a -l:librte_crypto_octeontx.a -l:librte_crypto_octeontx2.a -l:librte_crypto_scheduler.a -l:librte_crypto_virtio.a -l:librte_compress_octeontx.a -l:librte_regex_octeontx2.a -l:librte_vdpa_ifc.a -l:librte_vdpa_sfc.a -l:librte_event_cnxk.a -l:librte_event_dlb2.a -l:librte_event_dpaa.a -l:librte_event_dpaa2.a -l:librte_event_dsw.a -l:librte_event_octeontx2.a -l:librte_event_opdl.a -l:librte_event_skeleton.a -l:librte_event_sw.a -l:librte_event_octeontx.a -l:librte_baseband_acc.a -l:librte_baseband_agx100.a -l:librte_baseband_fpga_5gnr_fec.a -l:librte_baseband_fpga_lte_fec.a -l:librte_baseband_la12xx.a -l:librte_baseband_null.a -l:librte_baseband_turbo_sw.a -l:librte_node.a -l:librte_graph.a -l:librte_flow_classify.a -l:librte_pipeline.a -l:librte_table.a -l:librte_pdump.a -l:librte_port.a -l:librte_fib.a -l:librte_ipsec.a -l:librte_vhost.a -l:librte_stack.a -l:librte_security.a -l:librte_sched.a -l:librte_reorder.a -l:librte_rib.a -l:librte_dmadev.a -l:librte_regexdev.a -l:librte_rawdev.a -l:librte_power.a -l:librte_pcapng.a -l:librte_member.a -l:librte_lpm.a -l:librte_latencystats.a -l:librte_kni.a -l:librte_jobstats.a -l:librte_ip_frag.a -l:librte_gso.a -l:librte_gro.a -l:librte_gpudev.a -l:librte_eventdev.a -l:librte_efd.a -l:librte_distributor.a -l:librte_cryptodev.a -l:librte_compressdev.a -l:librte_cfgfile.a -l:librte_bpf.a -l:librte_bitratestats.a -l:librte_bbdev.a -l:librte_acl.a -l:librte_timer.a -l:librte_hash.a -l:librte_metrics.a -l:librte_cmdline.a -l:librte_pci.a -l:librte_ethdev.a -l:librte_meter.a -l:librte_net.a -l:librte_mbuf.a -l:librte_mempool.a -l:librte_rcu.a -l:librte_ring.a -l:librte_eal.a -l:librte_telemetry.a -l:librte_kvargs.a -Wl,--no-whole-archive -Wl,--export-dynamic -latomic -Wl,--as-needed -lrte_node -lrte_graph -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_pdump -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_dmadev -lrte_regexdev -lrte_rawdev -lrte_power -lrte_pcapng -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_gpudev -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bpf -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs -pthread -lm -ldl -lnuma -Wl,--no-whole-archive -lwls -lhugetlbfs  -Wl,-T /home/yeturva/workspace/merge_cohere_changes/CG_26May_2023/5G_IPR/gNB_SW/common/loggingFrameWork/logging/src/roStart.ld -L/home/yeturva/.local/lib `pkg-config --libs --static protobuf grpc++ absl_flags absl_flags_parse absl_absl_check absl_absl_log absl_algorithm absl_base absl_bind_front absl_bits absl_btree absl_cleanup absl_cord absl_core_headers absl_debugging absl_die_if_null absl_dynamic_annotations absl_flags absl_flat_hash_map absl_flat_hash_set absl_function_ref absl_hash absl_layout absl_log_initialize absl_log_severity absl_memory absl_node_hash_map absl_node_hash_set absl_optional absl_span absl_status absl_statusor absl_strings absl_synchronization absl_time absl_type_traits absl_utility absl_variant` -lutf8_validity -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -lstdc++ -lstdc++fs -L/usr/local/lib

### What did you expect to see?

I expect the compilation to be successful

### What did you see instead?
 I see compilation errors: *undefined reference to `std::__throw_bad_array_new_length()**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by eugeneo** [comment]
This seems like Ubuntu bug that was fixed: https://bugs.launchpad.net/votca/+bug/1956898

Please verify that all the dependencies are up to date.
