### ISSUE TITLE
cygrpc.InternalError not being logged

### ISSUE THREAD

**Issue by hpaul** [grpc/grpc#33438]
### What version of gRPC and what language are you using?
```grpcio [required: >=1.54.2, installed: 1.54.2] ```

### What operating system (Linux, Windows,...) and version?
```Fedora 37 (Kernel: Linux 6.1.7-200.fc37.x86_64)```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```python-3.11.1```

### What did you do?
I'm building a websocket which passes the received audio bytes from a device into a queue then a generator takes slices from that queue and sends them to the Google `SpeechAsyncClient`, which is using the gRPC protocol.

Because I never received a transcription response, I assumed there was a problem with the data format I was sending, but debugging and going further down the rabbit hole of gRPC, I just found out that the request silently fails and is never sent into the Google Speech-To-Text service. Or there is an error, but I can't really work out what it is because I get a generic error from the CPython code.

In this file: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_call.py#L481
Catching the error:
```python
        try:
            await self._cython_call.send_serialized_message(serialized_request)
        except cygrpc.InternalError as error:
            print(f"Internal error when sending the serialized message", error)
            await self._raise_for_status()
 ```
 It fails silently with this error message
```bash
E0614 12:55:18.808765880  158402 trace.cc:66]                          Unknown trace var: 'transport_security'
E0614 12:55:19.197828848  158402 compression_filter.cc:114]            CompressMessage: len=36 alg=0 flags=0
2023-06-14 12:55:19,198 app.recordings.entities.streams INFO Sending 3200 chunks for transcribing
E0614 12:55:42.199315481  158402 compression_filter.cc:114]            CompressMessage: len=3203 alg=0 flags=0
Internal error when sending the serialized message Failed "execute_batch": (<grpc._cython.cygrpc.SendMessageOperation object at 0x7ff3c6ec15b0>,)
``` 
 
And searching the web for similarities revealed that there have been a few issues in the past with the exact same error, but nothing that can solve my problem.
 
Tracing it further, I think it might have something to do with the Batch Operation flags, specifically [this line of code](https://github.com/grpc/grpc/blob/80dbe90c18f0a7d3da65bcac3f0e2eba7b74dc9e/src/core/lib/surface/call.cc#L1237) doesn't allow the request to be passed on, because the write_flag here [is `False`](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi#L139). Or I I could be completely wrong as my C++ skills are unfortunately not so developed.

Anything else you need to know, ask me and I'll be happy to answer here.
 
### What did you expect to see?
Response received from the Speech-To-Text service server.

### What did you see instead?
Errors. :smile: 

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by XuanWang-Amos** [comment]
Hi, in the line where we except `InternalError`, we should be raising an error, is there no error being raised?

For the `cygrpc.InternalError` itself, it usually raised when we have some unexpected errors in native/Core code so we'll need more information, can you help provide more logs by adding those environment variables: `GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`?

**Comment by hpaul** [comment]
Thank you for the fast response. After some more careful debugging, I discovered that the data was being sent in a different order to the way it was supposed to be sent. And also, I was resetting the gRPC session every 1s, so there was the real issue.

But I still think that silent errors from the C extension shouldn't be throw away, there have to be a way to get them, by an optional flag, or maybe I'm wrong?

**Comment by XuanWang-Amos** [comment]
I just created a PR, we'll have more logs after the PR merged: https://github.com/grpc/grpc/pull/34148
