### ISSUE TITLE
"Secure transport setup failed with error 2" when running C# interop tests.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3347]
I see some strange logs when running ping_pong and client_streaming interop tests. The interop test eventually passes, but hangs at shutdown (on one of the threads in the thread pool, I don't receive the stutdown event from completion queue).

GRPC_TRACE=surface SSL_CERT_FILE=$HOME/github/grpc/etc/roots.pem mono Grpc.IntegrationTesting.Client.exe --use_tls --server_port=443 --server_host=grpc-test.sandbox.google.com --server_host_override=grpc-test.sandbox.google.com --test_case=client_streaming
grpc-test.sandbox.google.com
443
running client_streaming
E9/16/2015 9:29:10 AM 139952491529984 src/core/security/secure_transport_setup.c:189: Read failed.
E9/16/2015 9:29:10 AM 139952491529984 src/core/surface/secure_channel_create.c:85: Secure transport setup failed with error 2.
D9/16/2015 9:29:10 AM 139952491529984 src/core/transport/chttp2/frame_settings.c:230: adding 983041 for initial_window change
I9/16/2015 9:29:10 AM 139952491529984 src/core/surface/completion_queue.c:212: RETURN_EVENT[0x1c733d0]: OP_COMPLETE: tag:0x1e36510 OK
D9/16/2015 9:29:10 AM 139952495732480 src/core/transport/chttp2/frame_settings.c:230: adding 983041 for initial_window change

When running on docker, I see this message (and get hanged upon shutdown).
E09/16/2015 16:25:37 140087774201600 src/core/iomgr/tcp_client_posix.c:174: on_writable failed during connect
E09/16/2015 16:25:37 140087774201600 src/core/iomgr/tcp_client_posix.c:247: connect error to 'ipv6:[2607:f8b0:400e:c04::451]:443': Network is unreachable
I09/16/2015 16:25:37 140087767897856 src/core/surface/completion_queue.c:212: RETURN_EVENT[0x2a41fb0]: OP_COMPLETE: tag:0x2c1b620 OK
D09/16/2015 16:25:37 140087774201600 src/core/transport/chttp2/frame_settings.c:230: adding 983041 for initial_window change

**Comment by nicolasnoble** [comment]
If this is fixed by #3354, can we close this one ?

**Comment by jtattermusch** [comment]
Interop tests have been partially fixed by #3354 and partially by other changes. Fine to close this one.
