### ISSUE TITLE
gem install error: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by andrisll** [grpc/grpc#33483]
### What version of gRPC and what language are you using?
grpc: 1.56.0
language: ruby 3.2.2

### What operating system (Linux, Windows,...) and version?
macOS 13.4
Apple M1 chip

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 14.0.3 (clang-1403.0.22.14.1)

### What did you do?
`gem install grpc -v 1.56.0`

### What did you expect to see?
Gem successfully installed.

### What did you see instead?
`
40 warnings generated.
compiling rb_enable_cpp.cc
linking shared-object grpc/grpc_c.bundle
Undefined symbols for architecture arm64:
  "_CFRelease", referenced from:
      absl::lts_20230125::time_internal::cctz::local_time_zone() in libgrpc.a(time_zone_lookup.o)
  "_CFStringGetCString", referenced from:
      absl::lts_20230125::time_internal::cctz::local_time_zone() in libgrpc.a(time_zone_lookup.o)
  "_CFStringGetLength", referenced from:
      absl::lts_20230125::time_internal::cctz::local_time_zone() in libgrpc.a(time_zone_lookup.o)
  "_CFStringGetMaximumSizeForEncoding", referenced from:
      absl::lts_20230125::time_internal::cctz::local_time_zone() in libgrpc.a(time_zone_lookup.o)
  "_CFTimeZoneCopyDefault", referenced from:
      absl::lts_20230125::time_internal::cctz::local_time_zone() in libgrpc.a(time_zone_lookup.o)
  "_CFTimeZoneGetName", referenced from:
      absl::lts_20230125::time_internal::cctz::local_time_zone() in libgrpc.a(time_zone_lookup.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [grpc_c.bundle] Error 1

make failed, exit code 2
`

**Comment by tdyas** [comment]
I am encountering this issue as well. The error seems like the CoreFoundation framework is not being linked in somehow?

**Comment by tdyas** [comment]
I was able to work around the issue with `bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup"`.

**Comment by michael-cybrid** [comment]
See this issue as well; moved past it with similar steps to @tdyas. Running with:
```
grpc: 1.56.0
ruby 3.2.2
macOs 12.6.6 (21G646)
Apple M1 Pro
```

**Comment by fabn** [comment]
> I was able to work around the issue with `bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup"`.

Solved my issue as well, thank you very much @tdyas

**Comment by stanhu** [comment]
This problem may not be limited to `arm64-darwin`. I had another person on my team run into this on `x86-darwin`, though using the precompiled gem is a workaround for now.
