### ISSUE TITLE
Parsed data lacks a field

### ISSUE THREAD

**Issue by tengerye** [grpc/grpc#33490]
### What version of gRPC and what language are you using?
I am using `grpcio=1.55.0` and `python=3.7.12`

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
python=3.7.12`

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Proto file `helloworld.proto`:
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package helloworld;

enum AnsType {
  OTHER = 0;
  YES = 1;
  NO = 2;
}

enum ErrorType {
  UNDEFINED = 0;
  OOM = 1;
}


// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}

  rpc SayHelloStreamReply (HelloRequest) returns (stream HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
  AnsType status = 2;
  ErrorType error = 3;
}

```

Server side code greeter_server.py:
```
from concurrent import futures
import logging

import grpc
import helloworld_pb2
import helloworld_pb2_grpc


class Greeter(helloworld_pb2_grpc.GreeterServicer):

    def SayHello(self, request, context):
        print(f'Receive {request}')
        return helloworld_pb2.HelloReply(
            message='Hello, %s!' % request.name,
            status=helloworld_pb2.AnsType.YES,
            error=helloworld_pb2.ErrorType.UNDEFINED,
            )


def serve():
    port = '50051'
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    server.add_insecure_port('[::]:' + port)
    server.start()
    print("Server started, listening on " + port)
    server.wait_for_termination()


if __name__ == '__main__':
    logging.basicConfig()
    serve()
```

Client side code `greeter_client.py`:
```
from __future__ import print_function
import sys

import logging

import grpc
import helloworld_pb2
import helloworld_pb2_grpc


def run():
    # NOTE(gRPC Python Team): .close() is possible on a channel and should be
    # used in circumstances in which the with statement does not fit the needs
    # of the code.
    print("Will try to greet world ...")
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
    print(response)
    print("Greeter client received: " + response.message)


if __name__ == '__main__':
    logging.basicConfig()
    run()
```

### What did you expect to see?
Will try to greet world ...
message: "Hello, you!"
status: YES
error: UNDEFINED

### What did you see instead?
Will try to greet world ...
message: "Hello, you!"
status: YES

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
This is working as intended, even though it's counterintuitive. The issue in general is called [field presence](https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md). If you really want to be able to distinguish between `UNDEFINED` having manually been set and no value having been set, you can add the `optional` keyword before the field definition for `error`.
