### ISSUE TITLE
undefined symbol: _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by yang7776** [grpc/grpc#33566]
centos7: Arm64
python3.8.12

[root@2810c1e55398 secker_agent]# python3 -c 'import grpc'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/local/python3/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: /usr/local/python3/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-aarch64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE

Please help me, what should I do about this error?

**Comment by XuanWang-Amos** [comment]
This looks like an issue with your libstdc++ version, it's possible that the version is not high enough, can you try update the version? In the meanwhile we'll try give you the lowest version we support.

**Comment by yang7776** [comment]
Thank you, that's all. We just need to upgrade libstdc++(libstdc++.so.6.0.25) and gcc(8.3.0).

**Comment by XuanWang-Amos** [comment]
Glad to hear that, we're closing this issue now, please open a new one if you need other help.
