### ISSUE TITLE
unrecognised emulation mode: elf_x86_64 for toolchain aarch64-linux when linking

### ISSUE THREAD

**Issue by yblin00** [grpc/grpc#33577]
### What version of gRPC and what language are you using?
Master version.

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.

### What runtime / compiler are you using (e.g. python version or version of gcc)
aarch64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### What did you do?
1. git clone https://github.com/grpc/grpc.git
2. GRPC_PATH=${PROJECT_PATH}/grpc
3. cd grpc
4. git submodule update --init
5. cd third_party/protobuf
6. git checkout remotes/origin/3.6.x
7. ./autogen.sh
8. ./configure --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu/
9. make && sudo make install && sudo ldconfig && export LDFLAGS="$LDFLAGS -lm"
10.  cd ${GRPC_PATH} && make clean
11. make CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ AR=/usr/bin/aarch64-linux-gnu-ar LD=/usr/bin/aarch64-linux-gnu-ld prefix=/usr/aarch64-linux-gnu

### What did you expect to see?
Compilation without errors.

### What did you see instead?
[HOSTLD]  Linking /home/yblin/assistant-sdk-cpp/grpc/bins/opt/grpc_cpp_plugin
/usr/aarch64-linux-gnu/bin/ld: unrecognised emulation mode: elf_x86_64
Supported emulations: aarch64linux aarch64elf aarch64elf32 aarch64elf32b aarch64elfb armelf armelfb aarch64linuxb aarch64linux32 aarch64linux32barmelfb_linux_eabi armelf_linux_eabi
collect2: error: ld returned 1 exit status

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment]
You can see https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake_aarch64_cross.sh on how to cross-build gRPC.
