### ISSUE TITLE
grpc.io: add fork me on github links to docs

### ISSUE THREAD

**Issue by philips** [grpc/grpc#3358]
One thing that has been really successful for us on https://coreos.com/docs is to add a "fork me on github link" so people can hack on the docs really quickly. For example see this page: https://coreos.com/os/docs/latest/booting-on-google-compute-engine.html

I would like to do something similar for grpc.io because it took me quite some time to figure out where the source was for http://www.grpc.io/docs/installation/go.html was and submit https://github.com/grpc/grpc-go/pull/343

I would be happy to do this but I can't figure out how grpc.io is built. Anyone have any pointers?

**Comment by soltanmm** [comment]
grpc.io is *currently* a private repository for the GRPC group.

@LisaFC Thoughts?

**Comment by LisaFC** [comment]
It's currently private while we put the initial docset together (including all the Jekyll infrastructure, Javascript, etc.) but my personal preference is to open it up for  general user pull requests as soon as possible so we can do things like the fork/edit button you suggested, probably after our next major update. I don't actually own the repo so can't change it myself yet...

**Comment by philips** [comment]
@LisaFC @soltanmm What is the next step here? I think it would really help increase a sense of community around the docs.

**Comment by LisaFC** [comment]
I'll talk to the other people with access to the repo.  We're currently working on a big-ish update on a branch to go with the next release, and I would suggest making the repo visible for users to send doc PRs after that.

**Comment by philips** [comment]
@LisaFC OK, when is that release going to happen so I can check back in?

**Comment by philips** [comment]
@LisaFC Ping

**Comment by LisaFC** [comment]
I promise I haven't forgotten! I am just off a plane and will be meeting with the relevant people tomorrow to sort out dates.

**Comment by philips** [comment]
@LisaFC no worries, with Google Inbox I can now easily set 7 day reminders for stuff like this! :)

**Comment by philips** [comment]
@LisaFC How is this looking? :)

**Comment by LisaFC** [comment]
Repo has literally just been made public :)

Voila! https://github.com/grpc/grpc.github.io

**Comment by LisaFC** [comment]
Let me know if you need any help with anything.
