### ISSUE TITLE
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by brennan-si** [grpc/grpc#3360]
I'm wanting to see about developing a plain JS version the grpc protocol without all the binary dependencies (they are not compatible, difficult to install, and give segfault / bus errors on OS X intermittently).

I'm trying to connect to a grpc server through HTTP2 directly.  I have tried a few methods:

Every time I get the error:

```
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

I have tried with `openssl s_client -connect`, `wget https://...`, and with node through the `node-http2` module.  They all give the same error.  Can someone provide some background as to what is going on here?  It seems to have something to do with there not being a valid cert on the grpc server side as far as I can tell but not sure how to get around that.

Here is the output from `openssl s_client -connect -debug`:

```
139641528207008:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:

---
no peer certificate available

---
No client certificate CA names sent

---
SSL handshake has read 7 bytes and written 295 bytes

---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE

---
```

**Comment by soltanmm** [comment]
How are you running the GRPC server (what implementing language, any particular example, etc.)?

**Comment by brennan-si** [comment]
It's a custom server.  I was reading that there are some options to pass in CERT info.  That was not happening and might be part of the problem.  If so, it can simply be an issue of hooking up the certs.  I haven't verified this yet.  It is a server written in node 0.10.40.  I was just launching the server using `node server.js`.  The server seems to work with the grpc client connecting to it, but I can't connect to it with openssl or the node-http2 library due to the problem mentioned in the title of the issue.

**Comment by nizsheanez** [comment]
Same for grpc-go: 
```
	bind := fmt.Sprintf("%s:%d", this.Config.Rpc.Host, this.Config.Rpc.Port)
	lis, err := net.Listen("tcp", bind)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	opts := []grpc.ServerOption{
	}
	grpcServer := grpc.NewServer(opts...)
	err = grpcServer.Serve(lis)
```

i installed curl with http2, and it works for google and other public http2 servers:
```
brew install nghttp2
brew install curl --with-nghttp2 --with-openssl

/usr/local/Cellar/curl/7.45.0/bin/curl --http2 -v -I https://google.com
* Rebuilt URL to: https://google.com/
*   Trying 216.58.221.46...
* Connected to google.com (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
* 	 subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=*.google.com
* 	 start date: Oct  7 10:26:52 2015 GMT
* 	 expire date: Jan  5 00:00:00 2016 GMT
* 	 subjectAltName: google.com matched
* 	 issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
* 	 SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fda53800000)
> HEAD / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.45.0
> Accept: */*
>
* http2_recv: 16384 bytes buffer at 0x7fda53800938 (stream 1)
* http2_recv: 16384 bytes buffer at 0x7fda53800938 (stream 1)
* http2_recv: 16384 bytes buffer at 0x7fda53800938 (stream 1)
* http2_recv: 16384 bytes buffer at 0x7fda53800938 (stream 1)
* http2_recv: returns 367 for stream 1
< HTTP/2.0 301
HTTP/2.0 301
< location:https://www.google.com/
location:https://www.google.com/
< content-type:text/html; charset=UTF-8
content-type:text/html; charset=UTF-8
< date:Tue, 20 Oct 2015 05:32:18 GMT
date:Tue, 20 Oct 2015 05:32:18 GMT
< expires:Thu, 19 Nov 2015 05:32:18 GMT
expires:Thu, 19 Nov 2015 05:32:18 GMT
< cache-control:public, max-age=2592000
cache-control:public, max-age=2592000
< server:gws
server:gws
< content-length:220
content-length:220
< x-xss-protection:1; mode=block
x-xss-protection:1; mode=block
< x-frame-options:SAMEORIGIN
x-frame-options:SAMEORIGIN
< alternate-protocol:443:quic,p=1
alternate-protocol:443:quic,p=1
< alt-svc:quic=":443"; p="1"; ma=604800
alt-svc:quic=":443"; p="1"; ma=604800

<
* Connection #0 to host google.com left intact
````

but can't access local server:
```
/usr/local/Cellar/curl/7.45.0/bin/curl --http2 -v https://localhost:8060                     
* Rebuilt URL to: https://localhost:8060/
*   Trying ::1...
* connect to ::1 port 8060 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8060 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Closing connection 0
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by jenevaL** [comment]
Same error appears when I try to connect with neo4j.
This is my code: 

var express = require ('express');
var path = require('path');
var logger = require('morgan');
var bodyParser = require('body-parser');
var neo4j =  require('neo4j-driver').v1;

var app = express();

//View Engine
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));


var driver=neo4j.driver("bolt://localhost:7474", neo4j.auth.basic("neo4j14", "neo4j"));
var session = driver.session();

app.get('/', function(req, res){

session
  .run("MATCH (snackhouse:Snackhouse) RETURN snackhouse LIMIT 25")
  .then(function(result){
      result.records.forEach(function(record){
        console.log(record); 
        });     
   })
  .catch(function(err){
      console.log(err);
  });
     res.send('It Works!');
});


app.listen(3000);
console.log('Server Started on port 3000');

module.exports = app;

And the error goes like this:
 Error: 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

    at Neo4jError.Error (native)
    at new Neo4jError (C:\neo4j\node_modules\neo4j-driver\lib\v1\error.js:65:132)
    at newError (C:\neo4j\node_modules\neo4j-driver\lib\v1\error.js:55:10)
    at NodeChannel._handleConnectionError (C:\neo4j\node_modules\neo4j-driver\lib\v1\internal\ch-node.js:322:41)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'SessionExpired' }

**Comment by leengine90** [comment]
hello neo4j user~
In bolt protocol, port number is not `7474` but `7687` as default.
so if you fix code like below, the problem may be resolve.

```
var driver=neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("neo4j14", "neo4j"));
```
good luck

**Comment by apolcyn** [comment]
Is this still an issue?
