### ISSUE TITLE
ClientReaderWriter constructor blocks forever

### ISSUE THREAD

**Issue by ohad7** [grpc/grpc#3361]
I'm using ClientReaderWriter and it is working well as long as the server is available on the first call to the constructor. If the server or network is down the call will is blocking and will never return (If the server comes back is sometimes returns, sometimes it doesn't).

I tried using ClientAsyncReaderWriter (which returns immediately) but there's no example so I'm shooting in the dark a little at the moment - If you can provide examples also how to use the async readerwriter that would be great.

Thanks!

**Comment by ohad7** [comment]
Is it possible to provide an example on how to use ClientAsyncReaderWriter in c++ ? In the meanwhile I'm using the sync client but handling failures is very messy (need to force reset the connection in all kinds of hacky ways).

Thanks in advance!

**Comment by ctiller** [comment]
You should probably just set a deadline for your RPC: if the server doesn't come up in a timely manner, the request will time out.

**Comment by btelles** [comment]
ohad7, I know this is late to the game, but perhaps this file gives you a rough idea?

https://github.com/grpc/grpc/blob/master/test/cpp/end2end/async_end2end_test.cc
