### ISSUE TITLE
gRPC v.1.56.0 does not build with Bazel

### ISSUE THREAD

**Issue by nichite** [grpc/grpc#33622]
### What version of gRPC and what language are you using?
gRPC v1.56.0, building a C++ application (though I believe the issue affects all languages, as the `gprc_plugin_support` target looks like it contains all languages' generators)

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04.2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel 6.1.2, gcc 11

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I included gRPC in my Bazel `WORKSPACE` file in the manner recommended in the doc. When building my test `grpc_cc_library` target, the build chokes while compiling the gRPC internals. 

### What did you expect to see?
"Build completed successfully."

### What did you see instead?

```
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_github_grpc_grpc/src/compiler/config_protobuf.h:22,
                 from external/com_github_grpc_grpc/src/compiler/config.h:24,
                 from external/com_github_grpc_grpc/src/compiler/csharp_generator.h:22,
                 from external/com_github_grpc_grpc/src/compiler/csharp_generator.cc:19:
external/com_github_grpc_grpc/include/grpcpp/impl/codegen/config_protobuf.h:74:10: fatal error: absl/status/status.h: No such file or directory
   74 | #include "absl/status/status.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target @com_github_grpc_grpc//src/compiler:grpc_plugin_support failed to build
INFO: Elapsed time: 15.280s, Critical Path: 3.74s
INFO: 86 processes: 23 internal, 63 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

I didn't include too much about my project files because the build clearly fails before getting to them, but I'm just trying to build a dummy Hello World app with gRPC as a dep to see if it builds. Simple proto with one service and one RPC. My only bazel flag in my `.bazelrc` sets the c++ version to c++std 17.

I believe this PR may be the culprit: https://github.com/grpc/grpc/commit/0f1afec5a8906ae3f00d58ff2499ad7e7cfb577e

It mentions that it adds a dependency on `absl` but does not add anything to `external_deps` in the `grpc_plugin_support` target to account for this in `/src/compiler/BUILD`. If I add `absl/status` in `external_deps`, this error goes away, replaced with a different error:

```
# Configuration: 9241a92507d3cd752e32a8415d9eab17a30bdcd7d1921e66de82b741cce682a3
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_github_grpc_grpc/src/compiler/config.h:24,
                 from external/com_github_grpc_grpc/src/compiler/node_generator.h:22,
                 from external/com_github_grpc_grpc/src/compiler/node_generator.cc:19:
external/com_github_grpc_grpc/src/compiler/config_protobuf.h:53:10: fatal error: google/protobuf/compiler/csharp/names.h: No such file or directory
   53 | #include <google/protobuf/compiler/csharp/names.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target @com_github_grpc_grpc//src/compiler:grpc_plugin_support failed to build
INFO: Elapsed time: 0.617s, Critical Path: 0.44s
INFO: 23 processes: 21 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Looks like another missing dep, but this one I'm not sure how to fix (I tried to add an external dep on `@com_google_protobuf//src/google/protobuf/compiler/csharp:names`, but the way the `_get_external_deps` macro works doesn't like it, and I'm not familiar enough with the gRPC internals to continue).

Anyway, **downgrading to gRPC v1.54.0 completely fixed the issue for me**. So it appears to be only 1.55.0 and 1.56.0 that don't work.

**Comment by drfloob** [comment]
I can't reproduce your build failure. See my barebones example here, pinned at gRPC v1.56.0: https://github.com/drfloob/tmp-33622. With no bazelrc, the build command is `bazel build --cxxopt='-std=c++17' --host_cxxopt='-std=c++17' :hi`

If you'd like to provide a minimum example that reproduces the problem, that'd give us more to investigate.

**Comment by sid1029** [comment]
+1.
Facing the same error when trying to build GRPC (1.56.2) from source using CMake as well.
Invoking the following shell script to build and install GRPC to a custom location :

```
ABSL_INSTALL_PATH=`(realpath ../abseil/lib/cmake/absl)`
PROTOBUF_INSTALL_PATH=`(realpath ../protobuf/lib/cmake/protobuf)`
GRPC_INSTALL_PATH=`(realpath .)`
git clone -j 16 --recurse-submodules -b v1.56.2 --depth 1 --shallow-submodules https://github.com/grpc/grpc grpc_src
cd grpc_src
rm -rf cmake/build
mkdir -p cmake/build
pushd cmake/build
cmake -DgRPC_INSTALL=ON \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DCMAKE_CXX_STANDARD=20 \
      -DCMAKE_INSTALL_PREFIX=$GRPC_INSTALL_PATH \
      -DCMAKE_BUILD_TYPE=Release \
      -DgRPC_ABSL_PROVIDER=package \
      -Dabsl_DIR=$ABSL_INSTALL_PATH \
      -DgRPC_PROTOBUF_PROVIDER=package \
      -DProtobuf_DIR=$PROTOBUF_INSTALL_PATH \
      -DgRPC_SSL_PROVIDER=package \
      -DgRPC_ZLIB_PROVIDER=package \
      -DgRPC_BUILD_TESTS=OFF \
      -DgRPC_BUILD_CODEGEN=ON \
      -DgRPC_BUILD_CSHARP_EXT=OFF \
      -DgRPC_BACKWARDS_COMPATIBILITY_MODE=OFF \
      -DgRPC_BUILD_GRPC_CPP_PLUGIN=ON \
      -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
      -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
      -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
      -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF \
      -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=ON \
      -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF \
      ../..
cmake --build . --target install -j 64
```

The CMake project generation succeeds. I verified it's able to find abseil and protobuf installations by printing out absl_VERSION and Protobuf_VERSION in cmake/abseil-cpp.cmake and cmake/protobuf.cmake respectively.

During the build stage it fails to build the `grpc_plugin_support` target with the errors like :

```
include/grpcpp/impl/codegen/config_protobuf.h:74:10: fatal error: 'absl/status/status.h' file not found
#include "absl/status/status.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/grpc_plugin_support.dir/build.make:132: CMakeFiles/grpc_plugin_support.dir/src/compiler/php_generator.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:645: CMakeFiles/grpc_plugin_support.dir/all] Error 2
```

Looking at the generated cmake/build/CMakeFiles/grpc_plugin_support.dir/flags.make the CXX_INCLUDES flag is missing the abseil includes path.

**Comment by drfloob** [comment]
> Facing the same error when trying to build GRPC (1.56.2) from source using CMake as well.

This issue is filed for the bazel build. Cmake often has unrelated problems, which may coincide with bazel build issues, but usually not. Please file a new issue, we can mark it as duplicate if investigation deems it has the same root cause.

**Comment by rohansingh** [comment]
I'm running into the exact same issue with Bazel. Unfortunately our repo is far from minimal so I can't provide an example to reproduce from.

@nichite I believe you were correct about which commit is the culprit. I'm able to workaround by reverting to v1.54.3, which doesn't include that commit.

**Comment by toandaominh1997** [comment]
@rohansingh I also faced the same problem with you when upgrading grpc to > 1.55.0. How do you fix that?

**Comment by adzenith** [comment]
I'm seeing this issue as well; I also unfortunately have quite a large repo and can't really produce a minimal example.
