### ISSUE TITLE
Error seen in getperrname() when starting server with active client

### ISSUE THREAD

**Issue by townsend2010** [grpc/grpc#33654]
### What version of gRPC and what language are you using?
1.52.1 and C++

### What operating system (Linux, Windows,...) and version?
macOS 13.4.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple Clang

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Updated [our project](https://github.com/canonical/multipass) to use gRPC v1.52.1.  We use Unix domain sockets on macOS and Linux for the client/server connection.

### What did you expect to see?
I don't expect to see an error and the client will connect successfully when the server is fully up and running.

### What did you see instead?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

When the server is starting and there is a client that is trying to connect to the server, the server will log the following error and then will no longer service any more requests:
```
E0627 10:12:08.657058000 6136393728 tcp_server_posix.cc:245]           Failed getpeername: Invalid argument
```

### Anything else we should know about your project / environment?
This **only** occurs on macOS and not on Linux.  I narrowed it down to https://github.com/grpc/grpc/commit/447bd664c0fa691f859501b7ee71da48de8b64c7 and it appears `getpeername()` is handled differently on macOS and this is a regression.  When I revert that commit, it works as expected again on macOS (and still works on Linux).

**Comment by yashykt** [comment]
@Vignesh2208 were you looking at this recently?

**Comment by yashykt** [comment]
@Vignesh2208 ping

**Comment by yashykt** [comment]
@Vignesh2208 ping

**Comment by Vignesh2208** [comment]
Closing this as it was already fixed through https://github.com/grpc/grpc/pull/35823
