### ISSUE TITLE
Swallow Content-Type when sent from server --> client

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3368]
Currently we hand this up to the application, but since it's really "protocol stuff" it should be consumed in the core library.

**Comment by nicolasnoble** [comment]
I think this also broke the C++ tests: in test/cpp/end2end/async_end2end_test.cc:

`EXPECT_EQ(static_cast<size_t>(2), server_initial_metadata.size());`

Needs to become 3. I guess this test needs to go ?
