### ISSUE TITLE
Build samples as part of automatic testing (WAS: Ensure samples work after being moved from grpc-common)

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#3371]
- [x] hellow world
- [x] route guide
- [x] auth sample
- [x] sample under `src/objective-c`
- [x] Swift sample (under `src/objective-c`)
- [ ] Build them as part of the automatic tests.
- [x] Point `/examples/README.md` > Objective-C to hellow world instead of route guide

**Comment by jcanizales** [comment]
https://github.com/grpc/grpc.github.io/pull/73 is blocked on this.

**Comment by jcanizales** [comment]
Also, build them as part of the automatic tests.

**Comment by jcanizales** [comment]
- [] Point `/examples/README.md` > Objective-C to hellow world instead of route guide

**Comment by makdharma** [comment]
Waiting on fix for issue #4518
