### ISSUE TITLE
Can utf8bom be used for the Character encoding format of c++ source code generated by proto file

### ISSUE THREAD

**Issue by ml232528** [grpc/grpc#33750]
### What version of gRPC and what language are you using?
grpc 1.56.1。c++

### What operating system (Linux, Windows,...) and version?
windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
Microsoft Visual Studio Community 2022 17.6.5

### What did you do?
Generate C++source code from the proto file
```
protoc.exe -I. --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe ./PositionSet.proto
protoc.exe -I. --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe ./PositionSetStruct.proto
```

### What did you expect to see?
Visual Studio can compile（VS can only compile utf8 source code with bom）。The proto file is with BOM, and the generated source code does not have it.

### What did you see instead?
Visual Studio  cannot be compiled because it is utf8 without bom。

**Comment by yashykt** [comment]
I think we've got CI tests working with visual studio. I'm not sure if this is a version issue. @veblush Do you know about this?

**Comment by ml232528** [comment]
The problem has always existed, regardless of the GRPC version.Visual Studio needs to be compiled into a utf8 file containing Chinese, with BOM。
If the proto file is gbk encoded, the source code generated by protoc.exe is also gbk. Visual Studio can compile.
If the proto file is utf8bom, the source code generated by protoc.exe is encoded as utf8. Bom is missing.Visual Studio cannot compile（The proto file contains Chinese annotations）。

**Comment by ml232528** [comment]
I believe that gprc generates source code using proto files. Just save the original encoding of the proto file. If the proto file is encoded in utf8bom, the generated source code wants to maintain utf8bom encoding.

**Comment by yashykt** [comment]
Does protoc provide a way to do this?
