### ISSUE TITLE
Composer packagist source to  https://github.com/grpc/grpc-php

### ISSUE THREAD

**Issue by sedovserge** [grpc/grpc#33751]
Please relocate In Packagist git source from https://github.com/grpc/grpc-php to https://github.com/grpc/grpc
last version is 1.52 here https://github.com/grpc/grpc-php

or update https://github.com/grpc/grpc-php to actual versions

**Comment by alto-php** [comment]
Updated to 1.57.0, @sedovserge could you verify?

**Comment by sedovserge** [comment]
> Updated to 1.57.0, @sedovserge could you verify?

Now is fine!

**Comment by AndrewCustomSumIT** [comment]
Please can the Packagist https://github.com/grpc/grpc-php be updated to the latest released versions?

Packagist is still sat on version 1.57.0.

Thank you.
