### ISSUE TITLE
how can I use libev with grpc together

### ISSUE THREAD

**Issue by echoma** [grpc/grpc#3379]
My applications is heavily using libev, how can I adapter grpc to work with libev?

**Comment by ctiller** [comment]
"It depends"

The easiest way would be to put grpc work on a separate thread.

Stepping up from there, you could have a different grpc_endpoint that uses libev... and every time there's IO on that endpoint follow up with a poll to a completion queue (the synchronous c++ api's won't work).

If you're ambitious, an iomgr port to libev ought to be possible. If you wanted to do that work, we'd probably take it as a contribution and make it an option for users.

**Comment by kpayson64** [comment]
cc @murgatroid99 
Has this become more feasible after the libuv abstractions?

**Comment by apolcyn** [comment]
does this need more documentation or feature support in grpc?
