### ISSUE TITLE
Windows build recommendation

### ISSUE THREAD

**Issue by PavelKsdnv** [grpc/grpc#33801]
I wanted to use gRPC on a Windows machine using C++. I also wanted to use VS22 for development.
1. I'd suggest to divide the different build guide per OS, having every OS one after the other in a single file is quite unreadable and gets confusing quickly. What I mean is to first have the section for Linux, then MacOS, Windows, etc.
2. Make it clear initially that you can either get the source code and build or you use say for example vcpkg to just get the finished builds. Most people would be perfectly fine to use the original code. Right now the option for a package manager is put dead last. Not as experienced people will struggle with pulling code, pulling dependencies,  building, and importing into their project. vcpkg Makes that much easier.

I spent three days banging my head against the wall why some of my dependencies weren't importing properly and saw that there was an issue open that two other people had the same problem with similar problems. Managed to do it properly in the end, but a friend of mine picked up gRPC but used vcpkg straight away and managed to get a hello world client/server scenario in the matter of 3-4 hours.

**Comment by yashykt** [comment]
vcpkg packages are community supported. The grpc team doesn't maintain them, and hence why it's mentioned at the bottom as a note. The feedback on the documentation is appreciated though.
