### ISSUE TITLE
Keep track of latency and throughput benchmarks in regards to compression

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#3385]
In order to check to see if optimizations actually provide the expected gain, there needs to be reliable and regular benchmarks.   Specifically, different compression and decompression techniques could speed up gRPC.  To evaluate these thoroughly, accurate benchmarks and their data is needed.

This may exist already today, in which case feel free to close this issue.

**Comment by sreecha** [comment]
I believe we have enough instrumentation in the code to get this information if we need it..
