### ISSUE TITLE
Can't get grpc_cli to communicate with my gRPC service. grpcurl works though.

### ISSUE THREAD

**Issue by ali-tahiri-pro** [grpc/grpc#33881]
### What version of gRPC and what language are you using?
1.34.0 on PHP

### What operating system (Linux, Windows,...) and version?
Linux Debian 11 Bullseye

### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP 7.4

### What did you do?
I have a EKS cluster on AWS that is reachable through an NLB. The traffic is routed to Ingress Controller Daemonset Listeners.
An Ingress object was created with the official documentation to expose a gRPC service through Ingress Controller.
When I test my gRPC service it works fine using grpcurl. HTTP2 is confirmed to be open and ALPN is activated and working fine. I tried also hand crafting requests using cURL and it also establishes the connection without any problems.

### What did you expect to see?
I expected that gRPC service to work with the grpc_cli and PHP gRPC. It doesn't.

### What did you see instead?
I get this error:
`D0726 15:56:04.290528000 8642665984 config.cc:131]                     gRPC EXPERIMENT tcp_frame_size_tuning               OFF (default:OFF)
D0726 15:56:04.290855000 8642665984 config.cc:131]                     gRPC EXPERIMENT tcp_rcv_lowat                       OFF (default:OFF)
D0726 15:56:04.290858000 8642665984 config.cc:131]                     gRPC EXPERIMENT peer_state_based_framing            OFF (default:OFF)
D0726 15:56:04.290860000 8642665984 config.cc:131]                     gRPC EXPERIMENT memory_pressure_controller          OFF (default:OFF)
D0726 15:56:04.290861000 8642665984 config.cc:131]                     gRPC EXPERIMENT unconstrained_max_quota_buffer_size OFF (default:OFF)
D0726 15:56:04.290863000 8642665984 config.cc:131]                     gRPC EXPERIMENT event_engine_client                 OFF (default:OFF)
D0726 15:56:04.290864000 8642665984 config.cc:131]                     gRPC EXPERIMENT monitoring_experiment               ON  (default:ON)
D0726 15:56:04.290866000 8642665984 config.cc:131]                     gRPC EXPERIMENT promise_based_client_call           OFF (default:OFF)
D0726 15:56:04.290868000 8642665984 config.cc:131]                     gRPC EXPERIMENT free_large_allocator                OFF (default:OFF)
D0726 15:56:04.290869000 8642665984 config.cc:131]                     gRPC EXPERIMENT promise_based_server_call           OFF (default:OFF)
D0726 15:56:04.290871000 8642665984 config.cc:131]                     gRPC EXPERIMENT transport_supplies_client_latency   OFF (default:OFF)
D0726 15:56:04.290872000 8642665984 config.cc:131]                     gRPC EXPERIMENT event_engine_listener               OFF (default:OFF)
D0726 15:56:04.290874000 8642665984 config.cc:131]                     gRPC EXPERIMENT schedule_cancellation_over_write    OFF (default:OFF)
D0726 15:56:04.290875000 8642665984 config.cc:131]                     gRPC EXPERIMENT trace_record_callops                OFF (default:OFF)
D0726 15:56:04.290877000 8642665984 config.cc:131]                     gRPC EXPERIMENT event_engine_dns                    OFF (default:OFF)
D0726 15:56:04.290903000 8642665984 config.cc:131]                     gRPC EXPERIMENT work_stealing                       OFF (default:OFF)
D0726 15:56:04.290910000 8642665984 config.cc:131]                     gRPC EXPERIMENT client_privacy                      OFF (default:OFF)
D0726 15:56:04.290913000 8642665984 config.cc:131]                     gRPC EXPERIMENT canary_client_privacy               OFF (default:OFF)
D0726 15:56:04.290914000 8642665984 config.cc:131]                     gRPC EXPERIMENT server_privacy                      OFF (default:OFF)
D0726 15:56:04.290964000 8642665984 ev_posix.cc:113]                   Using polling engine: poll
D0726 15:56:04.291705000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "priority_experimental"
D0726 15:56:04.291712000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "outlier_detection_experimental"
D0726 15:56:04.291730000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "weighted_target_experimental"
D0726 15:56:04.291732000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "pick_first"
D0726 15:56:04.291734000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "round_robin"
D0726 15:56:04.291736000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "weighted_round_robin"
D0726 15:56:04.291775000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "grpclb"
D0726 15:56:04.291780000 8642665984 dns_resolver_plugin.cc:44]         Using ares dns resolver
D0726 15:56:04.291803000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "rls_experimental"
D0726 15:56:04.291834000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "xds_cluster_manager_experimental"
D0726 15:56:04.291837000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "xds_cluster_impl_experimental"
D0726 15:56:04.291839000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "cds_experimental"
D0726 15:56:04.291841000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "xds_cluster_resolver_experimental"
D0726 15:56:04.291843000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "xds_override_host_experimental"
D0726 15:56:04.291845000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "xds_wrr_locality_experimental"
D0726 15:56:04.291847000 8642665984 lb_policy_registry.cc:47]          registering LB policy factory for "ring_hash_experimental"
D0726 15:56:04.291858000 8642665984 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
I0726 15:56:04.393550000 8642665984 subchannel.cc:707]                 subchannel 0x131f06fb0 {address=ipv4:13.39.239.255:443, args={grpc.client_channel_factory=0x6000026a01c0, grpc.default_authority=redacted:443, grpc.internal.channel_credentials=0x6000026a01b0, grpc.internal.event_engine=0x6000026ac3e0, grpc.internal.security_connector=0x6000031a0d00, grpc.internal.subchannel_pool=0x600000fa01c0, grpc.max_metadata_size=10485760, grpc.primary_user_agent=grpc-c++/1.56.2, grpc.resource_quota=0x600002aa0510, grpc.server_uri=dns:///redacted:443}}: connect failed (UNKNOWN:Failed parsing HTTP/2 {created_time:"2023-07-26T15:56:04.391582+02:00", children:[UNKNOWN:Expected SETTINGS frame as the first frame, got frame type 80 {created_time:"2023-07-26T15:56:04.391569+02:00"}, UNKNOWN:Trying to connect an http1.x server {grpc_status:13, http_status:400, created_time:"2023-07-26T15:56:04.391578+02:00"}]}), backing off for 966 ms
I0726 15:56:04.431637000 8642665984 subchannel.cc:707]                 subchannel 0x131f07370 {address=ipv4:13.39.237.173:443, args={grpc.client_channel_factory=0x6000026a01c0, grpc.default_authority=redacted:443, grpc.internal.channel_credentials=0x6000026a01b0, grpc.internal.event_engine=0x6000026ac3f0, grpc.internal.security_connector=0x6000031a0d40, grpc.internal.subchannel_pool=0x600000fa01c0, grpc.max_metadata_size=10485760, grpc.primary_user_agent=grpc-c++/1.56.2, grpc.resource_quota=0x600002aa0510, grpc.server_uri=dns:///redacted:443}}: connect failed (UNKNOWN:Failed parsing HTTP/2 {created_time:"2023-07-26T15:56:04.431595+02:00", children:[UNKNOWN:Expected SETTINGS frame as the first frame, got frame type 80 {created_time:"2023-07-26T15:56:04.431585+02:00"}, UNKNOWN:Trying to connect an http1.x server {created_time:"2023-07-26T15:56:04.431593+02:00", http_status:400, grpc_status:13}]}), backing off for 961 ms
Received an error when querying services endpoint.
ServerReflectionInfo rpc failed. Error code: 14, message: failed to connect to all addresses; last error: INTERNAL: ipv4:redacted:443: Trying to connect an http1.x server, debug info: UNKNOWN:failed to connect to all addresses; last error: INTERNAL: ipv4:redacted:443: Trying to connect an http1.x server {grpc_status:14, created_time:"2023-07-26T15:56:04.43166+02:00"}`

On the logs of Nginx Ingress Controller I have this:
`"PRI * HTTP/2.0" 400 150 "-" "-" 0 5.000 [] [] - - - - 9ed0bb403e8c1068e4ff9fbb940a14a8`

**Comment by yijiem** [comment]
The last part of the error log is probably relevant:

```I0726 15:56:04.393550000 8642665984 subchannel.cc:707]                 subchannel 0x131f06fb0 {address=ipv4:13.39.239.255:443, args={grpc.client_channel_factory=0x6000026a01c0, grpc.default_authority=redacted:443, grpc.internal.channel_credentials=0x6000026a01b0, grpc.internal.event_engine=0x6000026ac3e0, grpc.internal.security_connector=0x6000031a0d00, grpc.internal.subchannel_pool=0x600000fa01c0, grpc.max_metadata_size=10485760, grpc.primary_user_agent=grpc-c++/1.56.2, grpc.resource_quota=0x600002aa0510, grpc.server_uri=dns:///redacted:443}}: connect failed (UNKNOWN:Failed parsing HTTP/2 {created_time:"2023-07-26T15:56:04.391582+02:00", children:[UNKNOWN:Expected SETTINGS frame as the first frame, got frame type 80 {created_time:"2023-07-26T15:56:04.391569+02:00"}, UNKNOWN:Trying to connect an http1.x server {grpc_status:13, http_status:400, created_time:"2023-07-26T15:56:04.391578+02:00"}]}), backing off for 966 ms```

**Comment by yashykt** [comment]
I'll just note that `grpc_cli` is not actively maintained, and `grpcurl` seems to be in a better shape.

**Comment by yijiem** [comment]
Closing as the original issue has been resolved.
