### ISSUE TITLE
gRPC swallowing other exceptions after context is aborted

### ISSUE THREAD

**Issue by coryanderson-nomi** [grpc/grpc#33890]
### What version of gRPC and what language are you using?
Python, 1.56.2

### What operating system (Linux, Windows,...) and version?
Linux, MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
python:3.10.2

### What did you do?
This caused some problems in our project because we were unaware some cleanup code in a try/except block was failing after the context had aborted. Any exception that happens in higher-level code after `aborted` has been set on `_Context._state` never gets logged.

Something like this in an RPC method will hit the issue:
```python
        try:
            status = status_pb2.Status(
                code=code_pb2.ABORTED, message=""
            )
            context.abort_with_status(rpc_status.to_status(status))
        except Exception:
            pass
        finally:
            # This is swallowed because aborted is already set on _Context._state
            raise ValueError
```
This except Exception block here is not logging any exceptions that happen if `_Context._state.aborted` is set. 

https://github.com/grpc/grpc/blob/cad2255d8c01625e394fa997fb7dbdf1968b2d91/src/python/grpcio/grpc/_server.py#L445-L449

Should it not log exceptions regardless, so that other code doesn't fail silently?

### What did you expect to see?
Expected an exception/stacktrace from the code that executed after the context aborted.

### What did you see instead?
Nothing. No logging of errors. It failed silently.

**Comment by XuanWang-Amos** [comment]
Looks like it's a rare case where another exception happened in the `finally` block, you're right that we're not logging anything if it was already aborted, I'll create a PR to fix this shortly.
