### ISSUE TITLE
Does not build using VS2019 Toolset

### ISSUE THREAD

**Issue by janboelke** [grpc/grpc#33896]
Hello,

I want to reopen/follow up on https://github.com/grpc/grpc/issues/33689

We have the requirement to build gRPC with Toolset 14.2 (Compiler MSVC 19.24.28316.0).

To achieve this, I wanted to build an older version of gRPC which claims to be buildable with MSVS 2017 and newer (which includes VC 14.2)

What version of gRPC and what language are you using?
gRPC: 1.52.2
Language: C++

What operating system (Linux, Windows,...) and version?
Windows

What runtime / compiler are you using (e.g. python version or version of gcc)
(Compiler MSVC 19.24.28316.0).
VC Tools 14.24.28314
Visual Studio 2019

What did you do?
Followed the gRPC directions for[ building on Windows](https://github.com/grpc/grpc/blob/master/BUILDING.md#windows)

CMAKE v3.25.1
NASM: 2.14.02
Ninja: v1.10.12
Used x64 in call to vcvarsall.bat
What did you expect to see?
The build complete successfully

What did you see instead?
The build fails
absl/functional/internal/any_invocable.h(562): error C2672: 'absl::lts_20220623::internal_any_invocable::CoreImpl<false,ReturnType>::InitializeStorage': no matching overloaded function found 

Anything else we should know about your project / environment?
I can build gRPC v.1.56.0 with VC Tools 14.29.
This provides the same ABI, however I cannot link against the libraries when I build my application with 14.2, because there are unresolved symbols missing in the libraries provided by visual studio.
For example:
re2.lib(re2.cc.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
rpc.lib(call.cc.obj) : error LNK2001: unresolved external symbol __tls_guard

This means, I cannot rely on linking libraries built with a newer compiler/toolset in an application build with an older compiler/toolset.
My goal is to build gRPC (any version) with VC14.2 because I need to build an application with this toolset/compiler version.

Best regards,
Jan

**Comment by veblush** [comment]
I think this is related to https://github.com/microsoft/vcpkg/issues/11488 and if you want to make gRPC built with VS2019 work with VS2017, there is nothing gRPC can do about it.

**Comment by janboelke** [comment]
Hello,

Maybe there is a misunderstanding.

I am not using vcpkg, I am building from source with CMake.
I don't request that you support linking against grpc built with a newer toolchain when building an application with an older toolchain.

However, I need to build gRPC with the "older" toolchain to be able to build the complete application properly. From the documentation it should be possible to do that.

Please refer to my description, I honestly don't see why you would close this issue so quickly.

Please reopen.

**Comment by janboelke** [comment]
Hello, @veblush 

Any update on this one?
