### ISSUE TITLE
grpc._cython.cygrpc._SyncServicerContext doesn't have trailing_metadata

### ISSUE THREAD

**Issue by DarkMatter9309** [grpc/grpc#33902]
### What version of gRPC and what language are you using?
grpcio = "^1.51.1", Python

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
python = ">=3.8,<3.11"

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I am trying to use a decorator to authenticate before the func is called.  I want to pass information to the function once authenticated. 

```
def auth_decorator(func):
    @wraps(func)
    def wrapper(self, request, context):
        validation = validate_access_token("access token")
        if validation["statusCode"] == 200:
            print("*****************")
            print(type(context))
            print(dir(context))
            # I want to pass this information to function so I can access the value1, value 2 inside the fucntion
            context.set_trailing_metadata(
                (
                    ("key1", str("value1 that i get from validation message")),
                    ("key2", str("value2 similar")),
                )
            )
            return func(self, request, context)
        else:
            abort_msg = f"Insufficient permissions for access to {func.__name__}"
            log.debug(abort_msg)
            context.abort(grpc.StatusCode.PERMISSION_DENIED, abort_msg)

    return wrapper
```

using grpcaio, I've finally been able to get it working using set_trailing_metadata
for non asyncio, context.pass_to_func worked. 
https://stackoverflow.com/questions/75737633/asyncio-grpc-add-properties-to-context-from-decorator-or-server-interceptor

### What did you expect to see?
Below is the output from the print statements. I see that for _SyncServicerContext, there is a set_trailing_metadata but there is no trailing_metadata property to access it where as if you see in _ServicerContext there is. 
*****************
<class 'grpc._cython.cygrpc._SyncServicerContext'>
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'abort', 'add_callback', 'auth_context', 'disable_next_message_compression', 'invocation_metadata', 'peer', 'peer_identities', 'peer_identity_key', 'send_initial_metadata', 'set_code', 'set_compression', 'set_details', 'set_trailing_metadata', 'time_remaining']
*****************
<class 'grpc._cython.cygrpc._ServicerContext'>
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'abort', 'abort_with_status', 'add_done_callback', 'auth_context', 'cancelled', 'code', 'details', 'disable_next_message_compression', 'done', 'invocation_metadata', 'peer', 'peer_identities', 'peer_identity_key', 'read', 'send_initial_metadata', 'set_code', 'set_compression', 'set_details', 'set_trailing_metadata', 'time_remaining', '**trailing_metadata**', 'write']

### What did you see instead?
I am expecting to see trailing_metadata in _SyncServicerContext. I noticed that write is also missing. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
`_SyncServicerContext` and `_ServicerContext` are both private APIs of private modules, as indicated by the leading underscores. Is there an issue with the _public_ API that we can look at?

**Comment by DarkMatter9309** [comment]
No, this issue is regarding why _SyncServicerContext is missing trailing_metadata where as there is one in _ServicerContext
