### ISSUE TITLE
undefined symbol: grpc_google_iam_credentials_create

### ISSUE THREAD

**Issue by hhzzk** [grpc/grpc#3391]
Hi, when import the *_pb2.py which generated by run_codegen.sh, I got following ImportError:

```shell
Traceback (most recent call last):
  File "q_db_op.py", line 2, in <module>
    import db_op_pb2
  File "/data/server/grpc/db_op_pb2.py", line 331, in <module>
    from grpc.early_adopter import implementations
  File "/usr/local/lib/python2.7/dist-packages/grpc/early_adopter/implementations.py", line 34, in <module>
    from grpc._adapter import fore as _fore
  File "/usr/local/lib/python2.7/dist-packages/grpc/_adapter/fore.py", line 38, in <module>
    from grpc._adapter import _intermediary_low as _low
  File "/usr/local/lib/python2.7/dist-packages/grpc/_adapter/_intermediary_low.py", line 57, in <module>
    from grpc._adapter import _low
  File "/usr/local/lib/python2.7/dist-packages/grpc/_adapter/_low.py", line 31, in <module>
    from grpc._adapter import _c
ImportError: /usr/local/lib/python2.7/dist-packages/grpc/_adapter/_c.so: undefined symbol: grpc_google_iam_credentials_create

```

and the platform is ubuntu 14.04.
Any feedback will be appreciated.

**Comment by soltanmm** [comment]
Do you have an old system install of libgrpc?

**Comment by hhzzk** [comment]
I don't know whether I have an outdated system install of libgrpc, but I install grpc many times with different methods, and the issue still exists.
I want to know how to remove grpc compeletly? 
thanks...

**Comment by nathanielmanistaatgoogle** [comment]
Removal might depend on how you installed libgrpc in the first place. What problems are you having with uninstallation? Do you have "libgrpc" files under /usr/local/lib, and if so, is uninstalling gRPC more than just a matter of removing those files?

**Comment by soltanmm** [comment]
A good place to start to handle all possible installs on the command-line is

```
$ locate libgrpc
```

(you might need to `sudo updatedb` before that)

Determine the prefixes from there, e.g. you might see:

```
$ locate libgrpc
...
/usr/local/lib/libgrpc.so
...
```

The local prefix would mean you probably installed from source (or other manual non-packager means) at some point. Those will need to be removed manually. This includes headers under the prefix, e.g.:

```
/usr/local/include/grpc
```

If you already know POSIX root folder hierarchy and how package managers tend to work with them, feel free to ignore the following:

If the prefix looks like

```
/lib/...
/usr/lib/...
/usr/include/...
```

as opposed to

```
/usr/local/lib/...
```

(note the `local`)

Then that's likely a system install. You'll *want* to use your package manager to uninstall it. You could uninstall it manually be deleting those files, but then your package manager will hate you.

**Comment by hhzzk** [comment]
Thanks for everyone's replay.
Finally I use docker img to replace manually install.

**Comment by nathanielmanistaatgoogle** [comment]
Glad to hear that you're moving forward - feel free to contact us again if you encounter other obstacles.
