### ISSUE TITLE
Build fails when using bazel-buildfarm

### ISSUE THREAD

**Issue by grefab** [grpc/grpc#33950]
gRPC builds fine in a local bazel environment, but fails to build when being built distributedly using [bazel-buildfarm](https://github.com/bazelbuild/bazel-buildfarm).

### What version of gRPC and what language are you using?

gRPC 1.56.2, C++, Bazel 6.3.1, buildfarm 2.4.0

### What operating system (Linux, Windows,...) and version?

Linux Ubuntu 22.04, amd64

### What runtime / compiler are you using (e.g. python version or version of gcc)

clang-14

### What did you do?

I tried to build gRPC:
`bazel build --remote_executor=grpc://127.0.0.1:8980 @com_github_grpc_grpc//:grpc++`

You can find a reproducible docker setup here: https://github.com/grefab/grpc_buildfarm_issue/blob/main/run_example.sh#L39

### What did you expect to see?

Build succeeds, regardless of being built locally or via buildfarm.

### What did you see instead?

When using buildfarm:

```
Starting local Bazel server and connecting to it…
INFO: Invocation ID: bc257161-f8b1-465c-b210-d1069ec5ae83
Loading:
Loading:
Loading:
DEBUG: Rule ‘com_github_grpc_grpc’ indicated that a canonical reproducible form can be obtained by modifying arguments commit = “c0d1c393d9365664d47df41746e992ae97b651ef” and dropping [“tag”]
DEBUG: Repository com_github_grpc_grpc instantiated at:
/src/WORKSPACE:5:15: in <toplevel>
Repository rule git_repository defined at:
/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
Loading:
[...]
Analyzing: target //:grpc_buildfarm_issue (148 packages loaded, 4169 targets configured)
INFO: Analyzed target //:grpc_buildfarm_issue (149 packages loaded, 4818 targets configured).
checking cached actions
INFO: Found 1 target…
[0 / 1,671] [Prepa] BazelWorkspaceStatusAction stable-status.txt … (7 actions, 1 running)
[854 / 3,108] Copying files; 0s remote … (32 actions, 0 running)
[854 / 3,108] [Sched] Copying files … (32 actions, 0 running)
[861 / 3,108] [Sched] Compiling src/google/protobuf/extension_set_heavy.cc [for tool] … (32 actions, 19 running)
ERROR: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_github_grpc_grpc/BUILD:3824:16: Compiling src/core/ext/transport/chttp2/transport/varint.cc failed: (Exit 1): clang failed: error executing command (from target @com_github_grpc_grpc//:chttp2_varint) /usr/lib/llvm-14/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer … (remaining 55 arguments skipped)
external/com_github_grpc_grpc/src/core/ext/transport/chttp2/transport/varint.cc:23:10: error: module @com_github_grpc_grpc//:chttp2_varint does not depend on a module exporting ‘absl/base/attributes.h’
#include “absl/base/attributes.h”
^
1 error generated.
Target //:grpc_buildfarm_issue failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 34.827s, Critical Path: 3.37s
INFO: 897 processes: 886 internal, 11 remote.
FAILED: Build did NOT complete successfully
```

### Anything else we should know about your project / environment?

I posted this here and not in bazel-buildfarm, because everything else in our ~4k lines long workspace file builds fine. Please let me know if you think this issue is more suited there.

**Comment by drfloob** [comment]
This isn't something we have any expertise on, but your example was excellent, so out of curiosity I poked around for a while. As far as I can tell, the bazel configuration is correct. Take for example:

```
$ docker run --rm -v "$(pwd):/src" \
  grpc_buildfarm_issue-build \
  bazel cquery \
  --remote_executor=grpc://192.168.10.1:8980 \
  'somepath(@com_github_grpc_grpc//:chttp2_varint, @com_google_absl//absl/base:attributes.h)'

Starting local Bazel server and connecting to it...
...
INFO: Analyzed 2 targets (62 packages loaded, 866 targets configured).
INFO: Found 2 targets...
@com_github_grpc_grpc//:chttp2_varint (442d8db)
@com_google_absl//absl/base:core_headers (442d8db)
@com_google_absl//absl/base:attributes.h (null)
INFO: Elapsed time: 13.930s, Critical Path: 0.00s
```

(I'm not sure cquery is actually using the remote executor, it looks like it isn't, but it isn't obvious.)

You'll need to involve folks who work on bazel-buildfarm, I suggest filing a bug there, and referencing this one. If there is some problem in our build configuration, or in the way gRPC's build configuration is mutated (e.g., whatever buildfarm code translates `bazel build ... @com_github_grpc_grpc//:grpc++` to a build target of `//:grpc_buildfarm_issue`), they'll have an easier time pinpointing it. gRPC's build system is non-trivial, so I would not be surprised if bazel-buildfarm is having trouble with some piece or another.

**Comment by grefab** [comment]
Thanks for the analysis! I filed an [issue at bazel-buildfarm](https://github.com/bazelbuild/bazel-buildfarm/issues/1420). Please let me know if there is anything else I can do to help!
