### ISSUE TITLE
gRPC C++ installation has missing absl dependencies

### ISSUE THREAD

**Issue by Explorer001** [grpc/grpc#34046]
### What version of gRPC and what language are you using?

* gRPC v1.57.0
* C++

### What operating system (Linux, Windows,...) and version?

* Arch Linux 6.4.7

### What runtime / compiler are you using (e.g. python version or version of gcc)

* g++ (GCC) 13.2.1 20230801

### What did you do?

I build gRPC from source using the following commands:

```
cmake -DgRPC_INSTALL=ON -DCMAKE_CXX_STANDARD=20 -DABSL_PROPAGATE_CXX_STD=ON ../..
make
make install
```

This step works fine. I want to use gRPC in another project and link it like this:

```
cmake_minimum_required(VERSION 3.20.0)

include(FindProtobuf)

find_package(protobuf CONFIG REQUIRED)
find_package(gRPC CONFIG REQUIRED)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -Wall")

add_executable(target
    [...])

set_property(TARGET target PROPERTY CXX_STANDARD 20)

target_link_libraries(target PRIVATE 
    protobuf::libprotobuf
    gRPC::grpc
    gRPC::grpc++
    pthread)

target_include_directories(target PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
get_target_property(grpc_cpp_plugin_location gRPC::grpc_cpp_plugin LOCATION)
protobuf_generate(TARGET target LANGUAGE cpp PROTOS proto/filters.proto)
protobuf_generate(TARGET target LANGUAGE grpc PROTOS proto/filters.proto GENERATE_EXTENSIONS .grpc.pb.h .grpc.pb.cc PLUGIN "protoc-gen-grpc=${grpc_cpp_plugin_location}")
```

### What did you expect to see?

A working build.

### What did you see instead?

The build process fails with:

```
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): undefined reference to symbol '_ZN4absl12lts_2023012512log_internal21CheckOpMessageBuilder7ForVar2Ev'
/usr/bin/ld: /usr/lib/libabsl_log_internal_check_op.so.2301.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dpdk-idint-collector.dir/build.make:375: dpdk-idint-collector] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/dpdk-idint-collector.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by amorozov** [comment]
It looks like protobuf (in Arch) is the root of the problem, not grpc. I got the same problem without grpc at all

**Comment by amorozov** [comment]
n reported to [protobuf](https://github.com/protocolbuffers/protobuf/issues/12746)

The problem, as I understand, is that the part of absl library can't be loaded/correctly processed by the linker (hence the error `error adding symbols: DSO missing from command line`)

**Comment by amorozov** [comment]
Adding ` -labsl_log_internal_check_op -labsl_log_internal_message -labsl_raw_logging_internal -labsl_spinlock_wait` after `-l protobuf` solved the problem for me. The question is why these libs don't get loaded automatically.

**Comment by Explorer001** [comment]
Adding these flags solved it for me too. Thank you! But they should be added automatically

**Comment by veblush** [comment]
I think this is a problem of protobuf pkg-config (or Arch linux protobuf package) so I'm closing this. Please feel free to reopen if you think there is something gRPC should fix.

**Comment by 1292004560** [comment]
think you

**Comment by 1292004560** [comment]
cmake_minimum_required(VERSION 3.24)
project(GateServer)
set(CMAKE_CXX_STANDARD 17)
set(JSONCPP_INCLUDE_DIRS "/opt/homebrew/Cellar/jsoncpp/1.9.5/include")
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/config.ini ${CMAKE_CURRENT_BINARY_DIR}/config.ini COPYONLY)
find_package(Boost 1.86.0 REQUIRED COMPONENTS filesystem)
find_package(gRPC REQUIRED)
include_directories(${Boost_INCLUDE_DIRS} ${JSONCPP_INCLUDE_DIRS})
message(${JSONCPP_INCLUDE_DIRS})
add_executable(GateServer
                main.cpp
                CServer.cpp
                CServer.h
                const.h
                HttpConnection.cpp
                HttpConnection.h
                Sington.h
                LogicSystem.h
                LogicSystem.cpp
                VerifyGrpcClient.h
                message.grpc.pb.cc
                message.pb.cc
                message.pb.h
                message.grpc.pb.h
                ConfigManager.h
                ConfigManager.cpp )

# 查找jsoncpp库
find_library(JSONCPP_LIBRARY NAMES jsoncpp)
target_link_libraries(GateServer PRIVATE ${JSONCPP_LIBRARY} ${Boost_LIBRARIES} ${gRPC_LIBRARIES}  protobuf::libprotobuf
        gRPC::grpc
        gRPC::grpc++
        pthread)
