### ISSUE TITLE
Issue with Timeouts windows C++ client, linux python server

### ISSUE THREAD

**Issue by mdering** [grpc/grpc#3411]
I have a MSVC 2013 client written in c++ talking to a linux python server. The connection seems to work, the server gets the information, can display it, i verify that it's the same, etc. The server then replies with other information back to the client, which the client can properly display. In between those two steps though, the client reliably outputs

> ReadFile overlapped error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

which is strange because like I said, the reply comes back and is readable. This also reports WSA error 14 when I get the status error code. I've tried adjusting the deadline in the context. Is there something platform specific that is going wrong here? I'm happy to provide any other information that I can. 

The client code and server code aren't significantly different from the hello world example for their respective languages. The main difference is the client creates 1 client connection to the server and repeatedly uses the rpc service method it provides. Maybe this is an issue for a message board, if such a place exists

**Comment by yang-g** [comment]
Maybe a duplicate of #3290

**Comment by mdering** [comment]
I'm not sure, I'm getting a different error. I thought it might be a time issue but I added the time preprocessor directive to my project to no avail, and removed it from the library as well, which also didn't fix my problem. Either way it times out in 20 seconds and then outputs good output.

**Comment by mdering** [comment]
I did more digging, including trying a local python client for my server and a local c++ client for my server, I believe I have therefore eliminated the server as the culprit,  meaning this likely stems from a problem with MSVC 2013. Since a valid reply is being received, but only parsed once the process has timed out, the communication seems like its missing some final disconnect step. Can anyone direct me to how to fix this?

**Comment by mdering** [comment]
turns out this was a firewall issue on my network. An extremely awful one.
