### ISSUE TITLE
grpc does not use SOCK_CLOEXEC

### ISSUE THREAD

**Issue by rittneje** [grpc/grpc#34114]
I have been trying to read through the C++ code but it is very complicated. From what I can tell, this library does not use `SOCK_CLOEXEC` except as a parameter to `accept4`. I do see a reference to `FD_CLOEXEC`, but this is racy and should only be used on platforms that don't support `SOCK_CLOEXEC`.

See the description of `O_CLOEXEC` for why `SOCK_CLOEXEC` is needed instead of `FD_CLOEXEC`. https://man7.org/linux/man-pages/man2/open.2.html

Please fix all calls to `socket` to properly pass `SOCK_CLOEXEC` on platforms that support it (namely, Linux). (And conversely, don't bother with `FD_CLOEXEC` on such platforms.)

**Comment by eugeneo** [comment]
Please let us know if there are any specific issues you are having with the current codebase. Ideally, please provide a code example that showcases the problem.

**Comment by rittneje** [comment]
@eugeneo The issue is that by not following Linux best practices, if a long-lived child process is created between creating the socket and setting FD_CLOEXEC, then the field descriptor gets "leaked". Thus if the parent process exits/dies/closes, the server won't notice until the buffer fills or the HTTP2 pings time out or whatever.

**Comment by eugeneo** [comment]
Thanks for the report. We will look into using this flag. We will need to make sure it works on all supported platforms/toolchains.

**Comment by eugeneo** [comment]
Upon investigation, we found that this flag is not supported on all platforms gRPC is used. This diminishes the usefulness of using it. We decided not to use it at this time but we may reconsider later in the code on specific platforms.

**Comment by rittneje** [comment]
@eugeneo the industry standard is to conditionally use it on supported platforms via ifdef. Just because some platforms don’t support it doesn’t mean that everyone ought to be subject to the inherent race condition.

**Comment by eugeneo** [comment]
Here we are applying the "don't fix what is not broken". We would do this change if it fixed a bug in gRPC codebase.

**Comment by rittneje** [comment]
@eugeneo a race condition counts as a bug, even if it cannot be fixed across all your supported platforms

**Comment by eugeneo** [comment]
Do you have a code example how to reproduce this race condition?

**Comment by rittneje** [comment]
@eugeneo The gist of it is you need two threads. One thread creates a gRPC connection via this library. The other does a fork+exec. If the fork happens _after_ your library creates the socket and _before_ it marks it as close-on-exec, then the new child process will inherit the socket fd, which is clearly not the intention.

**Comment by eugeneo** [comment]
Please provide the code that reproduces the issue.

**Comment by rittneje** [comment]
@eugeneo To be honest, that would take me a while, and I see little point in doing so. The inherent race condition is quite apparent. It is even explained in the man page I have linked twice.
