### ISSUE TITLE
Error loading native library. Not found in any of the possible locations

### ISSUE THREAD

**Issue by hercul1017** [grpc/grpc#34153]
### What version of gRPC and what language are you using?
grpc.core 2.46.6

### What operating system (Linux, Windows,...) and version?
windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
vs 2022, .net 4.8.1 project

### What did you do?

Following line was working before. Long time we did not use this feature, when we did, possibly after updating related libraries, found following problem.

 TextToSpeechClient client = TextToSpeechClient.Create();

line fails. with  grpc_csharp_ext.x64.dll not found exception. When I manually copy the dll into bin directory it works. However when I publish the application grpc_csharp_ext.x64.dll won't get published and therefor published site won't work.

### What did you expect to see?
I expect required grpc_csharp_ext.x64.dll copied automatically.

### What did you see instead?
The dll won't get copied.

Publishing azure and also local don't copy the dll.

**Comment by hercul1017** [comment]
When published to azure, grpc_csharp_ext.x64.dll and x86 version get copied to azure web app root directory but not the bin directory.  That results in following error


Error loading native library. Not found in any of the possible locations: 
C:\home\site\wwwroot\bin\grpc_csharp_ext.x86.dll,
C:\home\site\wwwroot\bin\runtimes/win-x86/native\grpc_csharp_ext.x86.dll,
C:\home\site\wwwroot\bin\../..\runtimes/win-x86/native\grpc_csharp_ext.x86.dll

The same error also occurs for x64.dll version.

When both dlls manually copied to the bin folder then the website works.

**Comment by jtattermusch** [comment]
CC @tonydnewell
