### ISSUE TITLE
Illegal keepalive throttling value/crash

### ISSUE THREAD

**Issue by s22chan** [grpc/grpc#34173]
### What version of gRPC and what language are you using?

1.57.0

### What operating system (Linux, Windows,...) and version?

osx-64

### What runtime / compiler are you using (e.g. python version or version of gcc)

x86_64-apple-darwin13.4.0-clang++ (conda-forge)

### What did you do?
see https://github.com/conda-forge/grpc-cpp-feedstock/issues/281

### What did you expect to see?
No crashes or illegal accceses.

### What did you see instead?
segfaults and repeated warnings
see https://github.com/conda-forge/grpc-cpp-feedstock/issues/281 

The changes in 964f101b4bd5b7d49b816641d4ef23ecc701872d by @markdroth caused a reference to local copy, which gave garbage data/crashed on optimized builds.

a hotpatch at https://github.com/grpc/grpc/compare/master...s22chan:grpc:master didn't seem to work but:

1. I didn't check if this pattern exists anywhere else.
2. This likely isn't the correct fix because the mutex lock wouldn't be held and there can be a datarace on the status, but I don't see an easy fix other than using copy semantics on the watcher interface (not sure if that's too intrusive).

### Anything else we should know about your project / environment?
n/a

**Comment by s22chan** [comment]
On second thought, a copy should've been safe. I think I need to narrow this down a bit more

**Comment by h-vetinari** [comment]
@s22chan, could you reopen this issue?

I've now integrated a modified version of the helloworld [example](https://grpc.io/docs/languages/python/quickstart/#generate-grpc-code) as a test in https://github.com/conda-forge/grpc-cpp-feedstock/pull/312, and it fails with:
```
+ python test_grpcio_helloworld.py
Starting server...
Server started, listening on 50051
Running client...
E0830 01:04:35.825794000 4381519360 client_channel.cc:667]             chand=0x7fb61c456330: Illegal keepalive throttling value 
E0830 01:04:35.825858000 4381519360 client_channel.cc:667]             chand=0x7fb61c456330: Illegal keepalive throttling value 
E0830 01:04:35.826128000 4381519360 client_channel.cc:667]             chand=0x7fb61c456330: Illegal keepalive throttling value 
E0830 01:04:35.827035000 4381519360 client_channel.cc:667]             chand=0x7fb61c456330: Illegal keepalive throttling value 
Traceback (most recent call last):
  File "test_grpcio_helloworld.py", line 25, in <module>
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "$PREFIX/lib/python3.8/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "#PREFIX/lib/python3.8/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "UNKNOWN {grpc_message:"", grpc_status:0}"
	debug_error_string = "UNKNOWN {grpc_message:"", grpc_status:0}"
>
``` 

I've also tried this on a newer MACOSX_DEPLOYMENT_TARGET (given that conda-forge has a pretty old version that's due for an update), but the same error persists even then.

**Comment by s22chan** [comment]
@h-vetinari I'm pretty sure it's a linkage error in the conda-forge ecosystem: as `abseil` is returning a `nullopt` and `grpc` interpreting it as value holding `optional`.

I opened this issue late in the day and was not debugging clearly.

**Comment by h-vetinari** [comment]
> I'm pretty sure it's a linkage error in the conda-forge ecosystem: as `abseil` is returning a `nullopt` and `grpc` interpreting it as value holding `optional`.

But we're not touching the abseil types in a way that this should happen (or at least I don't know where that should occur). I think it's worth having a place to track this. Otherwise I'll just have to open my own issue.
