### ISSUE TITLE
ObjC - Create synchronous methods for service calls

### ISSUE THREAD

**Issue by EliSchleifer** [grpc/grpc#3421]
While the APM/callback model is super-duper-awesome there are times when it makes sense to make a sequence of serial calls to a service without creating a chained function behemoth. 

It would be great to have synchronous versions of the service methods generated. Perhaps this would be done with a flag or always by default depending on code bloat.

**Comment by jcanizales** [comment]
I'm not too worried about bloat, because that comes mostly from proto message fields, which are usually >> N(service methods).

**Comment by jcanizales** [comment]
Current plan is to generate something like:

```objective-c
#import <RxLibrary/GRXWriter+Blocking.h>
...
// non-streaming responses
- (Resp *)blockingMethodNameWithRequest:(Req *)request
                                  error:(NSError * __autoreleasing*)error {
  ProtoRPC *call = [self RPCToMethodNameWithRequest:request];
  NSEnumerator *responses = [NSEnumerator grx_blockingEnumeratorWithWriter:call];
  Resp *response = [responses next]; // blocks until next response or error.
  if (error) {
    *error = responses.error;
  }
  return response;
}
...
// streaming responses
- (NSEnumerator *)blockingMethodNameWithRequest:(Req *)request {
  ProtoRPC *call = [self RPCToMethodNameWithRequest:request];
  return [NSEnumerator grx_blockingEnumeratorWithWriter:call];
}
```

Note that this would currently prevent headers from being set - but we already plan to let set default headers at the service-object level. It also requires generating `- [ProtoService RPCToMethodNameWithRequest:]` (without handler), which isn't done currently.

The blocking enumerator can be implemented using a [semaphore](https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html#//apple_ref/doc/uid/TP40008091-CH102-SW24), which is +1'd when a new response arrives and -1'd when `-[next]` is called.

We could then also make it super fancy and let the user specify the max number of elements to buffer (throttling the server if it's full), and add a `count` property so one can check if `-[next]` would block.

**Comment by jcanizales** [comment]
Also, Eli: Because `ProtoRPC` (and `GRPCCall`) objects are instances of `GRXWriter`, they can be used as a request for a following RPC. And you can use `-[map:]` to transform values between calls. I know that in your specific case you don't care about blocking your thread, but how does the "chained function behemoth" look like if you leverage those things?

**Comment by bootstraponline** [comment]
Is there any update on a synchronous API for Objective C?
