### ISSUE TITLE
gRPC Async Server Stream API: set_buffer_hint() on the first message causes server hang

### ISSUE THREAD

**Issue by CloudBai1769** [grpc/grpc#34231]
### What version of gRPC and what language are you using?
1.55.0

### What operating system (Linux, Windows,...) and version?
Linux REHL7

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5

### What did you do?
I create a demo helloworld server stream RPC service:
```
  rpc SayHello ( HelloRequest) returns (stream HelloReply) {}
message HelloRequest {
  string name = 1;
  int32  myint = 2;
  string num_greetings = 3;
}

// A response message containing a greeting
message HelloReply {
  string message = 1;
  string num_greetings = 2;
}
```
I have set the grpc channel arguments to a small value by calling:
`
builder.AddChannelArgument("grpc.http2.write_buffer_size", 1024);
`
A Server side Async function Proceed to process the RPC and send back the same HelloReply infinitely:
```
       hellostreamingworld::HelloReply reply_;
       writeOpt.set_buffer_hint();
       responder_.Write(reply_,writeOpt, this);
```
When the first reply is sent out with buffer_hint(), the completion queue shall never return with the call object, causing a server side hang.
### What did you expect to see?
The client side can send out the message 
### What did you see instead?
The first message is not sent out, and the client receives nothing.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
If you share your code, it'll be easier for us to understand.

But, it sounds like you are registering the buffer size hint on the server builder. Did the CQ write event on the server return?

**Comment by CloudBai1769** [comment]
If I changed the code to the following, the ServerAsyncWrite can return
```
        if(firstmsg){
            firstmsg=false;
            writeOpt.clear_buffer_hint();
        }
        else
            writeOpt.set_buffer_hint();
        responder_.Write(reply_,writeOpt, this);
```
But if we set buffer hint on the first message, the ServerAsyncWrite write will not return.
I do registering the buffer size on the server side, does gRPC assume buffer size hint is no the client size only?
```
    std::string server_address("0.0.0.0:44444");
    ServerBuilder builder;
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    builder.AddChannelArgument("grpc.optimization_target", "throughput");
    builder.AddChannelArgument("grpc.minimal_stack", 1);
    builder.AddChannelArgument("grpc.http2.write_buffer_size", 1024);
    builder.RegisterService(&service_);
    cq_ = builder.AddCompletionQueue();
    server_ = builder.BuildAndStart(); 
```

**Comment by CloudBai1769** [comment]
Another thing in gRPC src code in `FlushInitialMetadata()`
When enabling buffer_hint on the first time write, this fucntion will not be triggered so that the closure `send_initial_metadata_finished` never triggered. Is this related to the hang issue? If so, what is the reason for this design?
`FlushInitialMetadata `in /src/core/ext/transport/chttp2/transport/writing.cc
```
 void FlushInitialMetadata() {
    // send initial metadata if it's available
    if (s_->sent_initial_metadata) return;
    if (s_->send_initial_metadata == nullptr) return;

    // We skip this on the server side if there is no custom initial
    // metadata, there are no messages to send, and we are also sending
    // trailing metadata.  This results in a Trailers-Only response,
    // which is required for retries, as per:
    // https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid
    if (!t_->is_client && s_->flow_controlled_buffer.length == 0 &&
        s_->send_trailing_metadata != nullptr &&
        is_default_initial_metadata(s_->send_initial_metadata)) {
      ConvertInitialMetadataToTrailingMetadata();
    } else {
      t_->hpack_compressor.EncodeHeaders(
          grpc_core::HPackCompressor::EncodeHeaderOptions{
              s_->id,  // stream_id
              false,   // is_eof
              t_->settings
                      [GRPC_PEER_SETTINGS]
                      [GRPC_CHTTP2_SETTINGS_GRPC_ALLOW_TRUE_BINARY_METADATA] !=
                  0,  // use_true_binary_metadata
              t_->settings
                  [GRPC_PEER_SETTINGS]
                  [GRPC_CHTTP2_SETTINGS_MAX_FRAME_SIZE],  // max_frame_size
              &s_->stats.outgoing                         // stats
          },
          *s_->send_initial_metadata, &t_->outbuf);
      grpc_chttp2_reset_ping_clock(t_);
      write_context_->IncInitialMetadataWrites();
    }

    s_->send_initial_metadata = nullptr;
    s_->sent_initial_metadata = true;
    write_context_->NoteScheduledResults();
    grpc_chttp2_complete_closure_step(
        t_, s_, &s_->send_initial_metadata_finished, absl::OkStatus(),
        "send_initial_metadata_finished");
  }
```

**Comment by yashykt** [comment]
Thanks for posting the code! We'll take a look at it @eugeneo

**Comment by eugeneo** [comment]
I believe the code works as it is supposed to. Nothing is sent until the buffer is filled or server signals it is done. This is the [example](https://gist.github.com/eugeneo/6d287de81f649244815dff0cee5c92c3) I wrote.

As you may see, it hangs because the message is smaller than the buffer set on line 75. To prevent it from hanging, either:
- Send a longer message, e.g. replace 10 with 1050 on line 42
- Replace `StartWrite` with `StartWriteAndFinish` on line 48.

Please reopen if you still believe there is a bug.
