### ISSUE TITLE
GetCpuStatsTest failed occasionally on arm

### ISSUE THREAD

**Issue by xiacunshun** [grpc/grpc#34249]
### What version of gRPC and what language are you using?
Version:        1.48.1

### What operating system (Linux, Windows,...) and version?
Linux VM-238-86-TS3 5.4.119-19-0011

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-12.3.0-2.ocs23.aarch64 1692234622 81807597 02207b4a09e21f1f6a0e9954c1c6d084 installed
gcc-c++-12.3.0-2.ocs23.aarch64 1692234622 31436460 ed9d6c915e891be70378a65ffbf511ed installed

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
compile the code and pack them into rpm.

### What did you expect to see?
success

### What did you see instead?
/builddir/build/BUILD/grpc-1.48.1/test/cpp/server/load_reporter/get_cpu_stats_test.cc:48: Failure
Expected: (prev.first) <= (cur.first), actual: 69428708 vs 69428707
[  FAILED  ] GetCpuStatsTest.Ascending (0 ms)
[----------] 3 tests from GetCpuStatsTest (0 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GetCpuStatsTest.Ascending
 1 FAILED TEST
error: Bad exit status from /var/tmp/rpm-tmp.JDvo8k (%check)
    Bad exit status from /var/tmp/rpm-tmp.JDvo8k (%check)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by xiacunshun** [comment]
I guess the compiler may have done some optimization that leads to this error?

**Comment by yashykt** [comment]
My first reaction looking at this test is that I don't understand why this has condition has to be true.

**Comment by xiacunshun** [comment]
> My first reaction looking at this test is that I don't understand why this has condition has to be true.
> 
> EDIT: Ah, ok. Looks like this is cumulative. In which case, I don't understand why it's not true on your environment.

I don’t know either.:( But with the patch above, this problem will never occur again.

**Comment by yashykt** [comment]
I don't think we want that patch. We really want to figure out the reason for this, instead of a patch to cover up the issues.

**Comment by veblush** [comment]
It's still puzzling to me how cpu aggregated time can go back in your case. As you suspected, this could be a combination of Linux Kernel and ARM issue. Although I couldn't find the authoritative source saying that this cpu time should be monotonic, I think there is nothing we can do about it until we have clear evidence that there is a problem with the test code.

**Comment by xiacunshun** [comment]
Okay. I run a demo with following code:
`#include <cstdio>
#include <cstdint>
#include <utility>
#include <cinttypes>
#include <unistd.h>

std::pair<uint64_t, uint64_t> GetCpuStatsImpl() {
  uint64_t busy = 0, total = 0;
  FILE* fp;
  fp = fopen("/proc/stat", "r");
  uint64_t user, nice, system, idle;
  if (fscanf(fp, "cpu %" PRIu64 " %" PRIu64 " %" PRIu64 " %" PRIu64, &user,
             &nice, &system, &idle) != 4) {
    // Something bad happened with the information, so assume it's all invalid
    user = nice = system = idle = 0;
  }
  fclose(fp);
  busy = user + nice + system;
  total = busy + idle;
  return std::make_pair(busy, total);
}

int main() {
  const size_t kRuns = 100;
  auto prev = GetCpuStatsImpl();
  for (size_t i = 0; i < kRuns; ++i) {
    // sleep(1);
    auto cur = GetCpuStatsImpl();
    if (prev.first > cur.first) {
        printf("got");
        printf("%d,%d", prev.first, cur.first);
    }
    prev = cur;
  }
  return 0;
}`
And I found that this problem has nothing to do with grpc indeed. It looks more like a 6.1 kernel problem, because it occured occasionally (about once thousands of times)  not only on ARM but also on x86.

**Comment by xiacunshun** [comment]
I will continuely work on this problem. But I will use the patch above to workaorund for the following release. 
Thanks a lot.

**Comment by xiacunshun** [comment]
> It's still puzzling to me how cpu aggregated time can go back in your case. As you suspected, this could be a combination of Linux Kernel and ARM issue. Although I couldn't find the authoritative source saying that this cpu time should be monotonic, I think there is nothing we can do about it until we have clear evidence that there is a problem with the test code.

I read the kernel code and the time is al `+=`, so it should be monotonic, I think.

**Comment by xiacunshun** [comment]
This problem occurs when kernel enables `CONFIG_CONTEXT_TRACKING_FORCE` and `CONFIG_VIRT_CPU_ACCOUNTING_GEN`.I am sure it's an upstream kernel issue. We will report and fix this soon.
Thanks a lot.

**Comment by xiacunshun** [comment]
https://lore.kernel.org/lkml/d41afbd5-6040-50ec-c0a5-c52ae48f6515@huawei.com/
This problem has been fix in newest upstream kernel. 
Close the issue.
