### ISSUE TITLE
Jenkins: git checkout fails with "reference is not a tree" error.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3428]
We've been seeing this problem for quite a while now, so I am adding a tracking issue for it.

Symptoms:
Generally, this happens when you have an open pull request and force-push the underlying branch (e.g. after you have consolidated/changed the history with `git rebase`). After that, github pull request builder will pick up the change to that branch and start a new build on jenkins. All configurations in that build will fail with the same message "Could not checkout" and "Reference is not a tree" - everything will be red.

Workaround:
Hit the Rebuild button on the failed build (if you don't see that button, make sure you're logged in: https://grpc-testing.appspot.com/manage). The new build should be able to checkout everything without problems and you will get your test results.

Cause:
Most likely cause of this problem is this:
https://issues.jenkins-ci.org/browse/JENKINS-10385

**Comment by jtattermusch** [comment]
FYI @nicolasnoble

**Comment by murgatroid99** [comment]
I have also seen this issue just from pushing multiple commits within a short time.

**Comment by jtattermusch** [comment]
Also, it looks like the parent job in matrix-project checks out the right revision (I think it's the right one) without problems:
```
git checkout -f 6c1b3afbda25c23d1c47890e629dfff6be64c481
git rev-list 68624b6c902cd780a909fd4744d18b057c999282 # timeout=10
```

The child job (one of the cells in the matrix) tries to check out a wrong revision:
```
git checkout -f 68624b6c902cd780a909fd4744d18b057c999282
FATAL: Could not checkout 68624b6c902cd780a909fd4744d18b057c999282
```

Parent job:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3235/console

Child job:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3235/config=dbg,language=sanity,platform=linux/console


Later,  once a new build has been started by the Rebuild button (https://grpc-testing.appspot.com/job/gRPC_pull_requests/3236/), this is what the parent job does instead:
```
git checkout -f 6c1b3afbda25c23d1c47890e629dfff6be64c481
git rev-list 6c1b3afbda25c23d1c47890e629dfff6be64c481 # timeout=10
```

and the child job does:
```
git checkout -f 6c1b3afbda25c23d1c47890e629dfff6be64c481
git rev-list 68624b6c902cd780a909fd4744d18b057c999282 # timeout=10
```

**Comment by jtattermusch** [comment]
Several folks seeing the same issue: https://github.com/janinko/ghprb/issues/148

**Comment by jtattermusch** [comment]
@nicolasnoble  perhaps we could experiment with some possible fixes using "the other" jenkins setup you brought up.

**Comment by jtattermusch** [comment]
I made an attempt to reproduce this after jenkins plugins were updated to
ghprb 1.29.2
git 2.4.0
git-client 1.19.0

I wasn't able to reproduce the issue.

Possible fix is https://github.com/jenkinsci/ghprb-plugin/pull/172 (It's more a guess).

Experimental jenkins builds: 
builds https://grpc-testing.appspot.com/job/gRPC_pull_requests/3864/
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3865/
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3866/

Closing the issue now, please reopen if seen again.

**Comment by murgatroid99** [comment]
I just saw this again at https://grpc-testing.appspot.com/job/gRPC_pull_requests/3929/config=dbg,language=c,platform=macos/console

**Comment by jtattermusch** [comment]
Looks like we started seeing this shortly after switching   pull request builder from  SCM polling to github webhooks. This might have to do with the fact that github webhooks  are delivered much faster. 
Maybe we should add a Quit period to our builds?

**Comment by jtattermusch** [comment]
I think we haven't seen this for a while. Closing.

**Comment by y-zeng** [comment]
It appeared again at https://grpc-testing.appspot.com/job/gRPC_pull_requests/9423/config=dbg,language=c,platform=linux/console
Two consecutive commits had this kind of test failure. But it did not appear in the following commits.

**Comment by trchakra** [comment]
I found same issue since today 13th Feb morning .
Commit or PR for the branch we are using happened 1 month ago and after that build was successful.
