### ISSUE TITLE
Access Violation in InsecureServerCredentials() when using C++20

### ISSUE THREAD

**Issue by DavidRobb** [grpc/grpc#34362]
With the current vcpkg version I get an access violation only in debug mode. It appears to be a problem with deallocating string resources from a gpr_log call (Maybe C++20 related in abseil library?)

### What version of gRPC and what language are you using?
latest vcpkg 
grpc:x64-windows-static -> 1.51.1

### What operating system (Linux, Windows,...) and version?
Windows 11 Pro

### What runtime / compiler are you using (e.g. python version or version of gcc)
[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -SC:/prog/TofVe/WinCaptureEngine -Bc:/prog/TofVe/WinCaptureEngine/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is MSVC 19.37.32822.0
[cmake] -- The CXX compiler identification is MSVC 19.37.32822.0

with 
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

### What did you do?
Can be repoduced by calling
`   auto serverCreds = grpc::InsecureServerCredentials();`

![image](https://github.com/grpc/grpc/assets/11753801/264b3024-b254-4cc2-aa11-f00a2918ce66)

CaptureEngine.exe!std::_Container_base12::_Orphan_all_unlocked_v3() Line 1372 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\xmemory:1372)
CaptureEngine.exe!std::_Container_base12::_Orphan_all_locked_v3() Line 1228 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\xmemory:1228)
CaptureEngine.exe!std::_Container_base12::_Orphan_all() Line 1387 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\xmemory:1387)
CaptureEngine.exe!std::string::_Tidy_deallocate() Line 4832 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\xstring:4832)
CaptureEngine.exe!std::string::~basic_string<char,std::char_traits<char>,std::allocator<char>>() Line 3121 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\xstring:3121)
CaptureEngine.exe!grpc_core::PrintExperimentsList() Line 113 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\src\core\lib\experiments\config.cc:113)
CaptureEngine.exe!do_basic_init() Line 126 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\src\core\lib\surface\init.cc:126)
CaptureEngine.exe!absl::lts_20230802::base_internal::Callable::Invoke<void (__cdecl*&)(void)>(void(*)() & f) Line 186 (c:\prog\vcpkg\installed\x64-windows\include\absl\base\internal\invoke.h:186)
CaptureEngine.exe!absl::lts_20230802::base_internal::invoke<void (__cdecl*&)(void)>(void(*)() & f) Line 214 (c:\prog\vcpkg\installed\x64-windows\include\absl\base\internal\invoke.h:214)
CaptureEngine.exe!absl::lts_20230802::base_internal::CallOnceImpl<void (__cdecl*&)(void)>(std::atomic<unsigned int> * control, absl::lts_20230802::base_internal::SchedulingMode scheduling_mode, void(*)() & fn) Line 180 (c:\prog\vcpkg\installed\x64-windows\include\absl\base\call_once.h:180)
CaptureEngine.exe!absl::lts_20230802::call_once<void (__cdecl*&)(void)>(absl::lts_20230802::once_flag & flag, void(*)() & fn) Line 214 (c:\prog\vcpkg\installed\x64-windows\include\absl\base\call_once.h:214)
CaptureEngine.exe!gpr_once_init(int * once, void(*)() init_function) Line 98 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\src\core\lib\gpr\sync_abseil.cc:98)
CaptureEngine.exe!grpc_init() Line 136 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\src\core\lib\surface\init.cc:136)
CaptureEngine.exe!grpc::internal::GrpcLibrary::init() Line 34 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\include\grpcpp\impl\grpc_library.h:34)
CaptureEngine.exe!grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool call_grpc_init) Line 49 (c:\prog\vcpkg\installed\x64-windows\include\grpcpp\impl\codegen\grpc_library.h:49)
CaptureEngine.exe!grpc::ServerCredentials::ServerCredentials() Line 25 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\src\cpp\server\server_credentials.cc:25)
CaptureEngine.exe!grpc::`anonymous namespace'::InsecureServerCredentialsImpl::InsecureServerCredentialsImpl() (Unknown Source:0)
CaptureEngine.exe!grpc::InsecureServerCredentials() Line 52 (c:\prog\vcpkg\buildtrees\grpc\src\v1.51.1-1066d25324.clean\src\cpp\server\insecure_server_credentials.cc:52)
CaptureEngine.exe!CEDiagnosticService::run() Line 228 (c:\prog\TofVe\WinCaptureEngine\CaptureEngine\CEDiagnosticService.cpp:228)
CaptureEngine.exe!std::invoke<void (__cdecl CEDiagnosticService::*)(void),CEDiagnosticService *>(void(CEDiagnosticService::*)() && _Obj, CEDiagnosticService * && _Arg1) Line 1777 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\type_traits:1777)

**Comment by yashykt** [comment]
I believe we've got C++20 tests that are compiled with clang, but not with VS 2022 yet. Just from the stacktrace, it's not obvious to me what the error is. I think we're eventually gonna get to this when we add C++20 tests with VS 2022, but till then please feel free to send a PR if you figure it out.

Do you perhaps know whether it works with C++14 or C++17?

**Comment by DavidRobb** [comment]
OK. I'm a bit further on now. I do get the same error with C++14 and C++17 but as with C++20, only when it is run in the debugger. Looks like the MS debugger is causing the issue here.

Running a debug build from the command line works fine. 

I've updated the issue title to reflect this
