### ISSUE TITLE
Exception Handling Guideline?

### ISSUE THREAD

**Issue by proteneer** [grpc/grpc#3436]
I have a python server and a Go client. When my python service code raises an exception, the exception isn't bubbled up. It simply fails the RPC call on the Go side with a cryptic message such as Error Detected: rpc error: code = 2 desc = "". The desc field is blank (ideally it'd be populated with an exception message).

How is everyone dealing with this? I'm open to creative ideas, etc.

**Comment by nathanielmanistaatgoogle** [comment]
I'm not sure whether or not @iamqizhao thinks that anything else should be done on the client side, but on the Python side you're right that *something* could probably be put in the description field. I doubt that it would be anything directly derived from the particular application raised by the exception, but it could be something bland such as "the server-side application failed".

**Comment by proteneer** [comment]
It looks like for Go servers, https://github.com/grpc/grpc-go/issues/92 , one can simply do:

```
nil, fmt.Errorf("too grumpy to greet")
```

I'm simply looking for a similar convention for the Python server

**Comment by nathanielmanistaatgoogle** [comment]
Hang on, the situation is not yet clear to me: is it that your service-side code is raising an exception that gRPC is catching and you'd like there to be a non-empty details string seen on the client, or is it that your service-side code is *handling* an exception, and you'd like to set the value of the details string yourself?

The latter is only possible with the Beta API - are you by any chance using the Beta API, or are you using the Early Adopter API?

**Comment by proteneer** [comment]
My service-side code, written in python, is raising an exception. The gRPC server is currently catching it, but it 

```
class Worker(worker_pb2.BetaWorkerServicer):

    def MyService(self, req, context):
        // do something

        return worker_pb2.Reply3D(resultMae=ligand_gz)
```

**Comment by proteneer** [comment]
and on the Go side:
```
result, err := app.RPC.MyService(context.Background(), req)
if err != nil {
	fmt.Println(err)
	// shows simply: rpc error: code = 2 desc = ""
	return err
}
```

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the clarification. What I will probably implement will be that the Go side would see the text "the service-side application failed" rather than the text "some Foo Error". You're right, of course, that having the text be completely empty is not as helpful as providing a message would be.

**Comment by proteneer** [comment]
So how does one send over "some Foo Error" to the client side? 

One option is to set the value of the desc string itself, which may be an overloaded to its original intent (eg. to simply diagnose transport errors and nothing else).

Another option is to define the services themselves to return optional error messages as well, eg:

```
service Worker {
	rpc MyService (SomeRequest) returns (SomeReply, SomeError) {}
}

message SomeError {
       string details = 1;
       string stacktrace = 2;
}
```

Is that how you guys are doing it?

**Comment by nathanielmanistaatgoogle** [comment]
Instead of
```
class Worker(worker_pb2.BetaWorkerServicer):

    def MyService(self, req, context):
          raise Exception('some Foo Error')
          // I want 'some Foo Error' to be sent to the Go side.
```
have you tried something like
```
class Worker(worker_pb2.BetaWorkerServicer):
    def MyService(self, req, context):
        try:
            raise Exception('some Foo Error')
        except Exception as e:
            context.details('An exception with message "%s" was raised!' % e.message)
            context.code(beta_interfaces.StatusCode.UNKNOWN)
            # If this is a response-unary method you'll have to return a value of the appropriate type:
            return worker_pb2.MyServiceResponseMessage()
```
?

We are not doing anything at all like adding optional error messages to RPC method definitions.

**Comment by proteneer** [comment]
That works! I was confused by Go's context.Background() and the Python context argument. It seems those two are unrelated.

**Comment by mihai-caraman-hs** [comment]
@proteneer @nathanielmanistaatgoogle it's still unclear to me how you access the context on the client. I'm especially interested how to access it by a python client. Thank you.

**Comment by mihai-caraman-hs** [comment]
ah, it just works. I thought i had to read the context in the client manually. Nevermind.

**Comment by zachizi** [comment]
This doesn't "just work" for me, though… what might I be missing?  To simplify for a test case I used the python helloworld examples.

server.py:
```
import time

import helloworld_pb2

_ONE_DAY_IN_SECONDS = 60 * 60 * 24


class Greeter(helloworld_pb2.BetaGreeterServicer):

  def SayHello(self, request, context):
    try:
      raise Exception('Some error!')
    except Exception as e:
      print(e.message)
      context.details('An exception with message "%s" was raised!', e.message)
      context.code(helloworld_pb2.beta_interfaces.StatusCode.INTERNAL)
      return helloworld_pb2.HelloReply()


def serve():
  server = helloworld_pb2.beta_create_Greeter_server(Greeter())
  server.add_insecure_port('[::]:50051')
  server.start()
  try:
    while True:
      time.sleep(_ONE_DAY_IN_SECONDS)
  except KeyboardInterrupt:
    server.stop(0)

if __name__ == '__main__':
  serve()
```
client.py:
```
from __future__ import print_function

from grpc.beta import implementations

import helloworld_pb2

_TIMEOUT_SECONDS = 10


def run():
  channel = implementations.insecure_channel('localhost', 50051)
  stub = helloworld_pb2.beta_create_Greeter_stub(channel)
  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  print("Greeter client received: " + response.message)


if __name__ == '__main__':
  run()
```
yet my client still gets the same somewhat meaningless error:
```
Traceback (most recent call last):
  File "greeter_client.py", line 49, in <module>
    run()
  File "greeter_client.py", line 44, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/Users/zjr/Projects/tg/api/py/env/lib/python2.7/site-packages/grpc/framework/crust/implementations.py", line 75, in __call__
    protocol_options, metadata, request)
  File "/Users/zjr/Projects/tg/api/py/env/lib/python2.7/site-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/Users/zjr/Projects/tg/api/py/env/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 415, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.RemoteError: RemoteError(code=StatusCode.UNKNOWN, details="")
```

**Comment by nathanielmanistaatgoogle** [comment]
@zachizi: what happens if you change `context.details('An exception with message "%s" was raised!', e.message)` to `context.details('An exception with message "%s" was raised!' % e.message)`?

**Comment by mbeachy** [comment]
@nathanielmanistaatgoogle, if you fix the string formatting error as you suggest, what you get is a default HelloReply with no error whatsoever.

I think the key is that the [example you gave on Sep 24, 2015](https://github.com/grpc/grpc/issues/3436#issuecomment-142953008) is incorrect and should return None when it handles the exception and not a MyServiceResponseMessage/HelloReply instance.

**Comment by nathanielmanistaatgoogle** [comment]
@mbeachy: in the last month we've replaced the code that handles status code and details specified by applications, so what problems you're seeing now (with grpcio 0.14.x) should go away soon (fixes are on master today and will be included in grpcio 0.15.x). And serendipitously enough [today's the day I'm writing test coverage for application-specified code and details](https://github.com/grpc/grpc/issues/4545#issuecomment-225757719).

**Comment by zachizi** [comment]
Oops I totally missed that message when it came through.  Hooray for fixes though and thanks for the response!  Hopefully I'll get some time in the next couple days to test that.

**Comment by wencan** [comment]
example:

`class SubjectRpcServicer(object):

  def FindSubject(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')`
