### ISSUE TITLE
Cannot pass `grpc.service_config` to channel builder in 1.53.2+

### ISSUE THREAD

**Issue by justincely** [grpc/grpc#34379]
### What version of gRPC and what language are you using?
Python grpcio 1.53.2-1.58.0

### What operating system (Linux, Windows,...) and version?
Linux Buster/Bullseye, M1 Osx Ventura

### What runtime / compiler are you using (e.g. python version or version of gcc)
Grpcio 1.52.3-1.58.0

### What did you do?
Since 1.51.1 i've been specifying the service config as a channel option `grpc.service_config`.  Trying to do this after upgrading to 1.53.2 (and beyond) has been erroring.  Other channel options are fine, i've narrowed it down to just this one causing the failure.  As an example, the code below recreates what i'm seeing.

```
import grpc
from grpc_health.v1 import health
from grpc_health.v1 import health_pb2
from grpc_health.v1 import health_pb2_grpc

options = [
    (
        "grpc.service_config",
        '{"methodConfig": [{"timeout": "5s", "name": [{}], "retryPolicy": {"maxAttempts": 3, "initialBackoff": "0.1s", "maxBackoff": "1s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}], "loadBalancingConfig": [{"round_robin": {}}], }',
    ),
]

channel = grpc.insecure_channel(
    target="dns:///localhost:8080",
    options=options,
)


stub = health_pb2_grpc.HealthStub(channel)
stub.Check(request=health_pb2.HealthCheckRequest())
```

### What did you expect to see?
This channel should build fine AFAIK, as this is one of the supported channel options.

### What did you see instead?
Just building the channel throws errors
```
E0915 15:40:01.472097000 8501911680 channel.cc:121]                    channel stack builder failed: INVALID_ARGUMENT: JSON parsing failed: [JSON parse error at index 244]
E0915 15:40:01.472747000 8501911680 channel.cc:121]                    channel stack builder failed: INVALID_ARGUMENT: JSON parsing failed: [JSON parse error at index 244]
```

And attempting to call the RPC:
```
Traceback (most recent call last):
  File "/test.py", line 32, in <module>
    stub.Check(request=health_pb2.HealthCheckRequest())
  File "/.pyenv/versions/3.11.4/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/3.11.4/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Failed to create secure client channel"
	debug_error_string = "INVALID_ARGUMENT:Failed to create secure client channel {grpc_status:3}"
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by XuanWang-Amos** [comment]
Sorry about the delay, the error indicates the JSON format is not correct, looks like you have an additional `,` near the end, can you try again and see if the error still exist using the correct JSON?
```
{"methodConfig": [{"timeout": "5s", "name": [{}], "retryPolicy": {"maxAttempts": 3, "initialBackoff": "0.1s", "maxBackoff": "1s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}], "loadBalancingConfig": [{"round_robin": {}}] }
```

**Comment by justincely** [comment]
Thanks @XuanWang-Amos, that does appear to be it.  Funny enough - this was added by the `black` formatter, so I need to turn off formatting around any of this to work well.  

I can definitely get around this now - but is this something that's intentional going forward?  I.e. will this likely be fixed to safely handle around a trailing comma, or should we expect this behavior to be present going forward?

**Comment by gnossen** [comment]
> this was added by the black formatter, so I need to turn off formatting around any of this to work well.

If `black` is adding a comma inside of a _JSON string_, that's a legitimate P0 bug within black. Strings are opaque bundles of data that can include anything. Trailing commas are simply invalid JSON and no JSON parser implementation should accept it.
