### ISSUE TITLE
Showing error in my cPanel

### ISSUE THREAD

**Issue by hiranmayroy183** [grpc/grpc#34383]
Whenever I am trying to install this in my cpanel account showing this type of errors: I am trying to install this for google-generativeai.:

Collecting grpcio<2.0dev,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-ai-generativelanguage==0.2.0->google-generativeai)
  Using cached grpcio-1.58.0.tar.gz (24.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      /tmp/pip-install-8pmd0554/grpcio_50d96ea90cc7408cad151c40138a44f8/setup.py:43: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8pmd0554/grpcio_50d96ea90cc7408cad151c40138a44f8/setup.py", line 292, in <module>
          if check_linker_need_libatomic():
        File "/tmp/pip-install-8pmd0554/grpcio_50d96ea90cc7408cad151c40138a44f8/setup.py", line 226, in check_linker_need_libatomic
          cpp_test = subprocess.Popen(
        File "/opt/alt/python39/lib64/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/alt/python39/lib64/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: 'c++'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yashykt** [comment]
It's not clear what the issue is but it looks like python?

**Comment by XuanWang-Amos** [comment]
Yeah it's related to Python.

I saw a PermissionError: `PermissionError: [Errno 13] Permission denied: 'c++'`

Can you share more info about the platform and the version of the platform you're using?

**Comment by hiranmayroy183** [comment]
It is! You got it right, whenever I am going to install in my cpanel. It is
showing me this c++ error.

How can you please tell me what is the solution for this issue?

**Comment by hiranmayroy183** [comment]
No, it has finished. I have solved the issue. Now you can close this as
solved.
