### ISSUE TITLE
Fails to autodetect QNX platform

### ISSUE THREAD

**Issue by Roman-Byshliaha-Bose** [grpc/grpc#34417]
### What version of gRPC and what language are you using?
gRPC version: v1.57.0
Language: C++

### What operating system (Linux, Windows,...) and version?
Cross-compiling on Linux for QNX (Neutrino 8.3.0 with SDP 7.1)

### What runtime / compiler are you using (e.g. python version or version of gcc)
qcc/q++ with support of C++14 standard.

### What did you do?
Cross-compile for QNX using official SDP.

### What did you expect to see?
QNX platform is correctly detected.

### What did you see instead?
error "Could not auto-detect platform"
error "Platform not recognized"

### Anything else we should know about your project / environment?
*toolchain.cmake*:
if(NOT DEFINED ENV{QNX_HOST})
    message(FATAL_ERROR "QNX_HOST env variable must be defined!")
endif()

set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_PROCESSOR aarch64 CACHE STRING "CMAKE_SYSTEM_PROCESSOR for qnx build")
set(CMAKE_C_COMPILER "qcc")
set(CMAKE_CXX_COMPILER "q++")
set(QNX_ARCH "aarch64le")
set(arch "gcc_nto${QNX_ARCH}")
set(CMAKE_C_COMPILER_TARGET ${arch})
set(CMAKE_CXX_COMPILER_TARGET ${arch})
set(CMAKE_SYSROOT $ENV{QNX_TARGET})

set(CMAKE_AR      "$ENV{QNX_HOST}/usr/bin/ntoaarch64-ar"      CACHE PATH "QNX ar Program")
set(CMAKE_RANLIB  "$ENV{QNX_HOST}/usr/bin/ntoaarch64-ranlib"  CACHE PATH "QNX ranlib Program")
set(CMAKE_NM      "$ENV{QNX_HOST}/usr/bin/ntoaarch64-nm"      CACHE PATH "QNX nm Program")
set(CMAKE_OBJCOPY "$ENV{QNX_HOST}/usr/bin/ntoaarch64-objcopy" CACHE PATH "QNX objcopy Program")
set(CMAKE_OBJDUMP "$ENV{QNX_HOST}/usr/bin/ntoaarch64-objdump" CACHE PATH "QNX objdump Program")
set(CMAKE_LINKER  "$ENV{QNX_HOST}/usr/bin/ntoaarch64-ld"      CACHE PATH "QNX Linker Program")
set(CMAKE_STRIP   "$ENV{QNX_HOST}/usr/bin/ntoaarch64-strip"   CACHE PATH "QNX Strip Program")

set(QNX_COMPILER_VERSION "8.3.0")
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}   -V${QNX_COMPILER_VERSION},${arch}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -V${QNX_COMPILER_VERSION},${arch} \
                                        -stdlib=libstdc++ \
                                        -D_QNX_SOURCE \
                                        -D_XOPEN_SOURCE=700 \
                                        -D_POSIX_C_SOURCE=200809")

list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{QNX_TARGET}"
                                 "$ENV{QNX_TARGET}/${QNX_ARCH}/usr")
message(STATUS "CMAKE_FIND_ROOT_PATH: ${CMAKE_FIND_ROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_HAVE_LIBC_PTHREAD YES)

*cmake command* (CMAKE_PROGRAM_PATH tells paths where to find protoc and grpc_cpp plugin built for host):
``cmake \
    -S/workspace \
    -B/workspace/build/${arch} \
    -DCMAKE_TOOLCHAIN_FILE="/workspace/tools/toolchains/toolchain.cmake" \
    -DCMAKE_MODULE_PATH="/workspace/tools/cmake" \
    -DCMAKE_PROGRAM_PATH="/workspace/build/grpc_gen;/workspace/build/grpc_gen/third_party/protobuf" \
    \
    -DBUILD_SHARED_LIBS=OFF \
    \
    -DgRPC_INSTALL_default=OFF \
    -DgRPC_INSTALL=OFF \
    -DgRPC_BUILD_TESTS=OFF \
    -DgRPC_BUILD_CODEGEN=OFF \
    -DgRPC_BUILD_GRPC_CPP_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF \
    \
    -Dprotobuf_INSTALL=OFF \
    -Dprotobuf_BUILD_TESTS=OFF \
    -Dprotobuf_BUILD_PROTOC_BINARIES=OFF \
    \
    -DABSL_PROPAGATE_CXX_STD=ON \
    \
    -DgRPC_ZLIB_PROVIDER=package \
    -DgRPC_SSL_PROVIDER=package``

**Comment by Roman-Byshliaha-Bose** [comment]
Add the following defines make it possible to build:
add_definitions(-DGPR_NO_AUTODETECT_PLATFORM)
add_definitions(-DGPR_PLATFORM_STRING="qnx")
add_definitions(-DGPR_ARCH_64)
add_definitions(-DGPR_CPU_POSIX)
add_definitions(-DGPR_GCC_ATOMIC)
add_definitions(-DGPR_GETPID_IN_UNISTD_H)
add_definitions(-DGPR_HAS_PTHREAD_H)
add_definitions(-DGPR_POSIX_ENV)
add_definitions(-DGPR_POSIX_LOG)
add_definitions(-DGPR_POSIX_STAT)
add_definitions(-DGPR_POSIX_STRING)
add_definitions(-DGPR_POSIX_SYNC)
add_definitions(-DGPR_POSIX_TIME)
add_definitions(-DGPR_POSIX_TMPFILE)
add_definitions(-DGRPC_HAVE_ARPA_NAMESER)
add_definitions(-DGRPC_HAVE_IFADDRS)
add_definitions(-DGRPC_HAVE_IP_PKTINFO)
add_definitions(-DGRPC_HAVE_MSG_NOSIGNAL)
add_definitions(-DGRPC_HAVE_UNIX_SOCKET)
add_definitions(-DGRPC_POSIX_NO_SPECIAL_WAKEUP_FD)
add_definitions(-DGRPC_POSIX_SOCKET)
add_definitions(-DGRPC_POSIX_SOCKETUTILS)
add_definitions(-DGRPC_POSIX_SYSCONF)
add_definitions(-DGRPC_POSIX_WAKEUP_FD)

https://github.com/grpc/grpc/pull/34418 as a suggested fix.

**Comment by eugeneo** [comment]
I am closing this issue. Discussions will resume on the pull request

**Comment by luominjie19981026** [comment]
Thank you for your great contribution and may I ask that did you successfully cross compile grpc for QNX using this cmake configuration?

**Comment by Roman-Byshliaha-Bose** [comment]
@luominjie19981026 yes, I did. And it proved working with one server app running on the HW and 2 client apps, both were able to connect and communicate.
Detection is only part of the problem, one more change should be done:
https://github.com/grpc/grpc/pull/34255.

You can see my toolchain file above, as well as a bunch of CMake keys to be passed during build.
Please pay special attention ssl and zlib is taken from QNX SDP instead of building 3d_party.

**Comment by luominjie19981026** [comment]
Thank you so much for your valuable information which is a great encouragement to me. And I am trying to cross compile this for QNX using the same keys of make as you and make them. But I came across this error:```
/usr/local/qnx710/qnx-sdp/target/qnx7/usr/include/c++/8.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
```
May I ask that is this happened to you too and how did you fix it?

**Comment by luominjie19981026** [comment]
> Thank you so much for your valuable information which is a great encouragement to me. And I am trying to cross compile this for QNX using the same keys of make as yours and make them. But I came across this error:
> 
> ```
> /usr/local/qnx710/qnx-sdp/target/qnx7/usr/include/c++/8.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
>  #include_next <stdlib.h>
> ```
> 
> May I ask that is this happened to you too and how did you fix it?

Update: I successfully complied it by changing all the "include_next" to "include" in qnx-sdp

**Comment by Roman-Byshliaha-Bose** [comment]
@luominjie19981026 not really, didn't have this kind of problem.

What comes to my mind:
1) Did you set up the env? (`source qnxsdp-env.sh` for example)
2) In you toolchain file - did you provide all the necessary information for C/CXX flags, QNX_COMPILER_VERSION? Those are crucial (of course you might have different architecture)? I am referring to the following block:
set(QNX_COMPILER_VERSION "8.3.0")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -V${QNX_COMPILER_VERSION},${arch}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -V${QNX_COMPILER_VERSION},${arch}
-stdlib=libstdc++
-D_QNX_SOURCE
-D_XOPEN_SOURCE=700
-D_POSIX_C_SOURCE=200809")

**Comment by PiterMa** [comment]
> > Thank you so much for your valuable information which is a great encouragement to me. And I am trying to cross compile this for QNX using the same keys of make as yours and make them. But I came across this error:
> > ```
> > /usr/local/qnx710/qnx-sdp/target/qnx7/usr/include/c++/8.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
> >  #include_next <stdlib.h>
> > ```
> > May I ask that is this happened to you too and how did you fix it?
> 
> Update: I successfully complied it by changing all the "include_next" to "include" in qnx-sdp

Modifying QNX-SDP is not a good idea. I encountered the same issue as you. Have you found a solution?

**Comment by luominjie19981026** [comment]
> > > Thank you so much for your valuable information which is a great encouragement to me. And I am trying to cross compile this for QNX using the same keys of make as yours and make them. But I came across this error:
> > > ```
> > > /usr/local/qnx710/qnx-sdp/target/qnx7/usr/include/c++/8.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
> > >  #include_next <stdlib.h>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > May I ask that is this happened to you too and how did you fix it?
> > 
> > 
> > Update: I successfully complied it by changing all the "include_next" to "include" in qnx-sdp
> 
> Modifying QNX-SDP is not a good idea. I encountered the same issue as you. Have you found a solution?

Sorry my solution to this issue still remains the same: modify all the "include_next" to "include", and this modification seems to have no side-effect to the environment so far. I successfully cross-compiled grpc for qnx and built the connection externally.
