### ISSUE TITLE
grpc_cli fails with opaque ASSERTION_FAILED: ok

### ISSUE THREAD

**Issue by dimo414** [grpc/grpc#34470]
### What version of gRPC and what language are you using?

```
$ grpc_cli --version
grpc_cli
Debug build (NDEBUG not #defined)
```

Womp womp... it was built against a recent checkout of the gRPC repo, but I don't know exactly which revision I had cloned at the time.

### What operating system (Linux, Windows,...) and version?

Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

N/A

### What did you do?

I am trying to send an RPC using `grpc_cli` to a server that is (probably) not yet correctly configured. When I do so I get an error back from `grpc_cli` but it just tells me _something_ is not `ok`, it doesn't give me any further information about what went wrong so I can't troubleshoot what's misconfigured on my server.

```
$ grpc_cli call --noremotedb --protofiles=path/to/my/service.proto my.envoy.frontend:443 service.path.MyService.MyRpc '...'
connecting to my.envoy.frontend:443
E0925 11:46:02.747800824  141835 cli_call.cc:84]                       ASSERTION FAILED: ok
Aborted (core dumped)
```

Here's the offending line: [cli_call.cc:84](https://github.com/grpc/grpc/blob/15a8aebc6d74fb2cf76fbeae9e6a7e153eb24bdd/test/cpp/util/cli_call.cc#L84)

### What did you expect to see?

I expected a more helpful error message, not an assertion+core dump. Presumably something is wrong with my server, or perhaps with the exact arguments I'm passing, but I can't tell because the program crashes.

### What did you see instead?

Process crash

**Comment by yashykt** [comment]
We've been recommending that people prefer `grpcurl` over `grpc_cli`. The support for `grpc_cli` at present is not up to par, and yes, this is not easy to use at the moment with the poor debug messages.

**Comment by dimo414** [comment]
Thanks @yashykt that's good to know. Could https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md be updated to recommend people use `grpcurl` in that case? I was intentionally not using it because it's third-party.

**Comment by yashykt** [comment]
will do

**Comment by dimo414** [comment]
Checking in here, https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md still doesn't mention `grpcurl`.

**Comment by dimo414** [comment]
@yashykt would it be possible for you to update the gRPC documentation to recommend `grpcurl`? This continues to be a source of confusion for people I support.

**Comment by yashykt** [comment]
Being done in https://github.com/grpc/grpc/pull/35675
