### ISSUE TITLE
Interop: use Go server in Go interop tests, not a Java server

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc#34504]
Go interop tests use a Java image as the server in interop tests, because Go did not have the interop spec implemented. Recently, a contributor added support for the interop spec server side for Go: https://github.com/grpc/grpc-go/pull/6575. Thus, the Go interop tests can now use Go server images in interop tests.

**Comment by eugeneo** [comment]
Moved to internal Bugtracker

**Comment by sergiitk** [comment]
This will be taken care of by https://github.com/grpc/psm-interop/pull/68.

**Comment by sergiitk** [comment]
@eugeneo - FYI if you for the internal bugtracker.
