### ISSUE TITLE
Server Wait With Timeout

### ISSUE THREAD

**Issue by kleblackford** [grpc/grpc#34545]
### Is your feature request related to a problem? Please describe.

In the tutorials, a blocking Wait function is often used with the server ([see here](https://github.com/grpc/grpc/blob/7b17e4aa928661e37775a823c9fb6937abfdb66f/examples/cpp/helloworld/greeter_server.cc#L75)). I have some c++ code wherein I am running a gRPC server in a thread and would like to poll a flag regularly to check whether to close down the server. For this I would expect a WaitWithTimeout function to be available.

### Describe the solution you'd like

I have already implemented a quick solution (for c++). For this I needed to define two methods: 

```
void Server::WaitWithTimeout(int MsTimeout) {
  grpc::internal::MutexLock lock(&mu_);
  absl::Duration timeout = absl::Milliseconds(MsTimeout);
  if (started_ && !shutdown_notified_) {
    shutdown_cv_.WaitWithTimeout(&mu_, timeout);
  }
}
```

in `src/cpp/server/server_cc.cc` and:

```
void WaitWithTimeout(int MsTimeout) ABSL_LOCKS_EXCLUDED(mu_);
```

in `include/grpcpp/server.h`. 

Is this an appropriate solution for the problem? If so, I would like to make a feature request that this functionality is supported in other languages.

**Comment by yashykt** [comment]
I don't understand the motivations. Why doesn't just `Wait()` work for you?

**Comment by kleblackford** [comment]
Because it blocks indefinitely. I need to check a flag regularly and if it is not set, continue waiting. For this, the normal wait function is not sufficient.
