### ISSUE TITLE
GRPC lib failed to verify a SSL certificate that is working with standard HttpClient

### ISSUE THREAD

**Issue by christopheblin** [grpc/grpc#34544]
Coming from https://github.com/grpc/grpc-dotnet/issues/2283

THe problem starts when using the lib from .NET but the logs show that the problem seems to be inisde GRPC Core

### What version of gRPC and what language are you using?
.NET 4.6.1

packages\Grpc.Core.2.41.0\lib\net45\Grpc.Core.dll

used by packages\Google.Cloud.PubSub.V1.2.9.0\lib\net461\Google.Cloud.PubSub.V1.dll

### What operating system (Linux, Windows,...) and version?
windows server 2012 R2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 4.6.1

### What did you do?
```
var _publisherClient = PublisherClient.Create(
        TopicName.FromProjectTopic(projectId, topicId),
        new PublisherClient.ClientCreationSettings(
            publisherServiceApiSettings: new PublisherServiceApiSettings{},
            serviceEndpoint: endpoint
            ).WithEmulatorDetection(EmulatorDetection.None), customSettings);           

var m = new PubsubMessage
{
    Data = ByteString.CopyFromUtf8(msg),    
};

var msgId = _publisherClient.PublishAsync(m).Result;
```

### What did you expect to see?
A successful published message

### What did you see instead?
`Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1695913720.195000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1695913720.195000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":147,"grpc_status":14}]}")`

I then do use set GRPC_VERBOSITY=DEBUG and I see` E0928 17:08:39.764952 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:1469: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.`

here is the full output
```
D0928 17:08:39.548181 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Users\xxx\Documents\Debug\Debug\grpc_csharp_ext.x86.dll"
D0928 17:08:39.575146 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "grpclb"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "priority_experimental"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "weighted_target_experimental"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "pick_first"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "round_robin"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "ring_hash_experimental"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc:489: Using ares dns resolver
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\xds\certificate_provider_registry.cc:33: registering certificate provider factory for "file_watcher"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "cds_experimental"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "xds_cluster_impl_experimental"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "xds_cluster_resolver_experimental"
D0928 17:08:39.575146 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy_registry.cc:42: registering LB policy factory for "xds_cluster_manager_experimental"
E0928 17:08:39.764952 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:1469: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0928 17:08:39.764952 0 ..\..\..\src\core\lib\security\transport\security_handshaker.cc:184: Security handshake failed: {"created":"@1695913719.774000000","description":"Handshake failed","file":"..\..\..\src\core\lib\security\transport\security_handshaker.cc","file_line":336,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0928 17:08:39.764952 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:1012: Connect failed: {"created":"@1695913719.774000000","description":"Handshake failed","file":"..\..\..\src\core\lib\security\transport\security_handshaker.cc","file_line":336,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0928 17:08:39.764952 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:957: Subchannel 05809E60: Retry in 952 milliseconds

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1695913720.195000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1695913720.195000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":147,"grpc_status":14}]}")

```

### Anything else we should know about your project / environment?

If I do an HTTPS request before on the same domain with the standard HTTP client, it works (meaning the SSL certificate is valid)

```
var tmp = new HttpClient().GetAsync("https://samedomain.net/hello/").Result;
tmp.EnsureSuccessStatusCode();
```

**Comment by apolcyn** [comment]
* What address are you trying to target?

* Have you tried using different root certificates? For example, you could point to `etc/roots.pem` in the grpc github repo by downloading that and setting env var `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` to it.

* Does this problem still happen with the 2.46 version of gRPC? If I'm correct you are using 2.41.

**Comment by christopheblin** [comment]
Hi @apolcyn 

Thanks for your answer

I'm trying to target an internal address with a certificate that is valid only inside our windows domain (i.e and it is correctly trusted by the windows machine because the httpClient is working fine)

I do not know about using differetn certificates root on windows only for GRPC but if I understand correctly I need to download the pem, add my root cetificate inside and change the env var => is that correct ?

For using the 2.46, not sure I can because I am stuck to .NET 4.6.1 and the latest PubSub nuget that supports it is the one I'm using...
Otherwise, I'd need to setup a test only about GRPC but I do not know anything about this (i.e we are only using GRPC through PubSub, not directly)

**Comment by tonydnewell** [comment]
@christopheblin have you been able to make any progress?

To use different root certs for gRPC you can set the environment variable `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` to point to a PEM file containing the root certs. See [environment_variables.md](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)

You should be able to use Grpc.Core 2.46.6 with Google.Cloud.PubSub.V1 2.9.0 as its dependencies are:
[Grpc.Core](https://www.nuget.org/packages/Grpc.Core/) (>= 2.41.0 && < 3.0.0)

**Comment by tonydnewell** [comment]
@christopheblin any update?

**Comment by apolcyn** [comment]
closing (suggestion made by @tonydnewell should resolve this)
