### ISSUE TITLE
Cannot build repo from source.

### ISSUE THREAD

**Issue by martin-pc** [grpc/grpc#3455]
When I follow the standard steps:
git clone https://github.com/grpc/grpc.git
cd grpc
git submodule update --init
make

I get the following message:
#####################################################################
In file included from src/core/transport/chttp2/frame_data.c:41:0:
src/core/transport/chttp2/frame_data.c: In function ‘grpc_chttp2_data_parser_parse’:
src/core/transport/chttp2/frame_data.c:164:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         GPR_ASSERT(end - cur <= p->frame_size);
                              ^
include/grpc/support/log.h:98:11: note: in definition of macro ‘GPR_ASSERT’
     if (!(x)) {                                       \
           ^
cc1: all warnings being treated as errors
make: *** [/home/martin/grpc/objs/opt/src/core/transport/chttp2/frame_data.o] Error 1
#####################################################################
I could remove the -Werror flag in the makefile, but I am unsure if this solves the actual problem!

**Comment by ctiller** [comment]
That'll work... The code is fine. We recently upped our warning levels and
I think we are going through a bit of a shake out with different compilers.
This one I fixed as part of another change and so it should be right at
head soon. Which compiler and version are you using so we can prioritize it
for our CI servers?

**Comment by martin-pc** [comment]
gcc --version
gcc (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1

Same problem with gcc 4.6

The last checkin to grpc seem to be:
git log

commit ee56eb60c8aa0e36ac33b00fbd4e70a61412d2e4
Merge: e5515d4 d09cce1
Author: Craig Tiller <ctiller@google.com>
Date:   Wed Sep 23 16:22:43 2015 -0700

    Merge pull request #3444 from dgquintas/lb_policies_test
    
    Improvements to lb_policies_test's rebirth testcase.

**Comment by martin-pc** [comment]
Okay, now I get a new error when I run the make command:

[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTLD]  Linking /home/martin/grpc/bins/opt/grpc_cpp_plugin
[HOSTCXX] Compiling src/compiler/csharp_plugin.cc
[HOSTLD]  Linking /home/martin/grpc/bins/opt/grpc_csharp_plugin
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GetMethodRequestParamMaybe':
/home/martin/grpc/src/compiler/csharp_generator.cc:115: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GetMethodReturnTypeClient':
/home/martin/grpc/src/compiler/csharp_generator.cc:130: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:130: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:127: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:121: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o):/home/martin/grpc/src/compiler/csharp_generator.cc:124: more undefined references to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)' follow
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `grpc_csharp_generator::GetServices(google::protobuf::FileDescriptor const*)':
/home/martin/grpc/src/compiler/csharp_generator.cc:527: undefined reference to `google::protobuf::compiler::csharp::GetFileNamespace(google::protobuf::FileDescriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateMarshallerFields':
/home/martin/grpc/src/compiler/csharp_generator.cc:203: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateStaticMethodField':
/home/martin/grpc/src/compiler/csharp_generator.cc:213: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:213: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateServiceDescriptorProperty':
/home/martin/grpc/src/compiler/csharp_generator.cc:238: undefined reference to `google::protobuf::compiler::csharp::GetUmbrellaClassName(google::protobuf::FileDescriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateClientInterface':
/home/martin/grpc/src/compiler/csharp_generator.cc:259: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:259: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:266: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:266: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GetMethodResponseStreamMaybe':
/home/martin/grpc/src/compiler/csharp_generator.cc:171: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o):/home/martin/grpc/src/compiler/csharp_generator.cc:144: more undefined references to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)' follow
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateServerInterface':
/home/martin/grpc/src/compiler/csharp_generator.cc:305: undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GetMethodRequestParamServer':
/home/martin/grpc/src/compiler/csharp_generator.cc:140: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GetMethodReturnTypeServer':
/home/martin/grpc/src/compiler/csharp_generator.cc:154: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateClientStub':
/home/martin/grpc/src/compiler/csharp_generator.cc:338: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:338: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/src/compiler/csharp_generator.cc:352: undefined reference to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)'
/home/martin/grpc/libs/opt/libgrpc_plugin_support.a(csharp_generator.o):/home/martin/grpc/src/compiler/csharp_generator.cc:352: more undefined references to `google::protobuf::compiler::csharp::GetClassName(google::protobuf::Descriptor const*)' follow
collect2: ld returned 1 exit status
make: *** [/home/martin/grpc/bins/opt/grpc_csharp_plugin] Error 1
