### ISSUE TITLE
Error importing a Well Known Type when using grpc.protos_and_services()

### ISSUE THREAD

**Issue by np-c0mp1ete** [grpc/grpc#34574]
### What version of gRPC and what language are you using?
python
grpcio==1.59.0
grpcio-tools==1.59.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I use [this proto file](https://github.com/grpc/grpc/blob/b9fbf41e3c0a240c1177345a4798325832f4641e/src/python/grpcio_tests/tests/unit/data/foo/bar_with_wkt.proto) and this unit test https://github.com/grpc/grpc/blob/b9fbf41e3c0a240c1177345a4798325832f4641e/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py#L115

### What did you expect to see?
I expect it to run without errors

### What did you see instead?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

```
Traceback (most recent call last):
  File "C:\test\test.py", line 3, in <module>
    protos, services = grpc.protos_and_services("test.proto")
  File "C:\test\venv\lib\site-packages\grpc\_runtime_protos.py", line 165, in protos_and_services
    return _call_with_lazy_import("protos_and_services", protobuf_path)
  File "C:\test\venv\lib\site-packages\grpc\_runtime_protos.py", line 68, in _call_with_lazy_import
    return fn(protobuf_path)
  File "C:\test\venv\lib\site-packages\grpc_tools\protoc.py", line 104, in _protos_and_services
    return (_protos(protobuf_path), _services(protobuf_path))
  File "C:\test\venv\lib\site-packages\grpc_tools\protoc.py", line 89, in _protos
    module = importlib.import_module(module_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\test\venv\lib\site-packages\grpc_tools\protoc.py", line 153, in exec_module
    exec(files[-1][1], module.__dict__)
  File "<string>", line 14, in <module>
  File "C:\test\venv\lib\site-packages\google\protobuf\any_pb2.py", line 16, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19google/protobuf/any.proto\x12\x0fgoogle.protobuf\"6\n\x03\x41ny\x12\x19\n\x08type_url\x18\x01 \x01(\tR\x07typeUrl\x12\x14\n\x05value\x18\x02 \x01(\x0cR\x05valueBv\n\x13\x63om.google.protobufB\x08\x41nyProtoP\x01Z,google.golang.org/protobuf/types/known/anypb\xa2\x02\x03GPB\xaa\x02\x1eGoogle.Protobuf.WellKnownTypesb\x06proto3')
TypeError: Couldn't build proto file into descriptor pool: duplicate file name google/protobuf/any.proto
```

### Anything else we should know about your project / environment?
`grpcio` and `grpcio-tools` were installed using `pip`

**Comment by gnossen** [comment]
A couple of questions:

- Is this issue unique to 1.59.0? That is, are you able to reproduce with grpcio-tools==1.58.0?
- What version of protobuf are you using? This error message looks very similar to [one that I believe should already have been resolved](https://github.com/protocolbuffers/protobuf/issues/10158).

**Comment by np-c0mp1ete** [comment]
The issue is also present with grpcio==1.58.0, grpcio-tools==1.58.0.
protobuf version that was fetched automatically is 4.24.3.

**Comment by XuanWang-Amos** [comment]
I tried locally in windows and able to reproduce using the following package versions:
* grpcio==1.59.0
* grpcio-tools==1.59.0
* protobuf==4.24.3 and protobuf==4.24.4


Maybe protobuf team forget to add this fix for windows wheels, I just created an issue here: https://github.com/protocolbuffers/protobuf/issues/14345
