### ISSUE TITLE
PHP grpc pecl install takes about 15 minutes to install

### ISSUE THREAD

**Issue by slnw** [grpc/grpc#34585]
PHP grpc pecl install takes about 15 minutes to install

Docker - ubuntu 14, in the docker file 
`RUN apt-get install -y zlib1g-dev
RUN pecl install grpc`

**Comment by alto-php** [comment]
You can try increase the parallel compile jobs using MAKEFLAGS, e.g. `MAKEFLAGS=" -j10"`.

**Comment by gplanchat** [comment]
The discussion has also taken place in #34278 and #23626

**Comment by alto-php** [comment]
For further discussion, please go to #34278
