### ISSUE TITLE
Mac Sonoma problem with Python and Node

### ISSUE THREAD

**Issue by aaltat** [grpc/grpc#34582]
### What version of gRPC and what language are you using?
I am using Python with 1.59.0/1.58.0 and Node  grpc-tools 1.12.4 

### What operating system (Linux, Windows,...) and version?
Mac Sonoma 14.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11.5 and 3.10.13, with gRPC 1.59.0/1.58.0 
Node v16.15.1 grpc-tools 1.12.4 

### What did you do?
After Mac update to Sonoma 14.0, running gRPC hangs with process starts. I can not reproduce the problem with older version of Mac and I can not reproduce the problem with other OS. We maintain project https://github.com/MarketSquare/robotframework-browser, which uses Python and Node with Playwright and we use gRPC to handle communication between Python and Node. When our library is used and other process is started example by `os.popen` the `os.popen` hangs. The best example to reproduce the problem, please follow these steps.

1) Create Python venv: `python -m venv .venv`
1) `pip install robotframework-browser` 
1) `rfbrowser init` 
1) run example in below with python:

```Python
import contextlib
import json
import os
import subprocess
import time
from pathlib import Path

import grpc
from Browser.generated import playwright_pb2_grpc
from Browser.generated.playwright_pb2 import Request


port = "53296"  # Make sure that port is free
print(port)
work_dir = Path(__file__).resolve().parent

def wait_until_server_up():
    for _ in range(50):
        with grpc.insecure_channel(f"127.0.0.1:{port}") as channel:
            try:
                stub = playwright_pb2_grpc.PlaywrightStub(channel)
                response = stub.Health(Request().Empty())
                print(
                    f"Connected to the playwright process at port {port}: {response}"
                )
                return
            except grpc.RpcError as err:
                print(err)
                time.sleep(0.1)


@contextlib.contextmanager
def process1():
    channel = grpc.insecure_channel(f"127.0.0.1:{port}")
    os.environ["DEBUG"] = "pw:api"
    os.environ["GRPC_VERBOSITY"] = "debug"
    log_file =  work_dir / "file.log"
    log_file = log_file.open("w")
    p1 = subprocess.Popen(
        [
            "node",
            work_dir / ".venv/lib/python3.11/site-packages/Browser/wrapper/index.js",
            port,
        ],
        shell=False,
        cwd=work_dir,
        env=os.environ,
        stdout=log_file,
        stderr=subprocess.STDOUT,
    )
    wait_until_server_up()
    print(p1.poll())
    yield playwright_pb2_grpc.PlaywrightStub(channel)


with process1() as stub:
    print("HERE 1")
    response = stub.GetBrowserCatalog(Request().Empty())
    print("HERE 2")
    parsed = json.loads(response.json)
    print(parsed)
    print("HERE 2")

print("KALA 1")
p2 = os.popen("pwd")
print("KALA 2")
p2.read()
print(p2)
```

### What did you expect to see?
I did expect to see all prints from the script and script should exit normally.

### What did you see instead?
Last print I see is `KALA 1` and script does not exit 

### Anything else we should know about your project / environment?
I tried with Python 3.11 and 3.10 and the problem persist.

**Comment by eugeneo** [comment]
This issue does not seem to be caused by gRPC.

**Comment by mattbirman** [comment]
> This issue does not seem to be caused by gRPC.
How did you determine that this issue not caused by gRPC?

My team is experiencing the same issues with a tool, specifically `gcloud` datastore emulator, which depends on gRPC on macOS Sonoma. Me and three other people in my team have the same issue.

**Comment by mattbirman** [comment]
>This issue does not seem to be caused by gRPC.

How did you determine that this issue is not caused by gRPC?

My team is experiencing the same issues with a tool on macOS Sonoma. Specifically, `gcloud` datastore emulator. Me and three other people in my team have the same issue.

**Comment by eugeneo** [comment]
It seems like your code hangs on os.popen.

**Comment by aaltat** [comment]
Yes, but if just run os.open it doesn’t hang. Also if do similar combination, by running multiple process, but don’t use GRPC I don’t see hang.
