### ISSUE TITLE
Why is the performance of the unary interface so low?

### ISSUE THREAD

**Issue by Huang-Hong** [grpc/grpc#34584]
### What version of gRPC and what language are you using?
version is  v1.58.1
language is c++

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I did some performance test for GRPC  c++
I use the demo code as the grpc server of my test：https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_server.cc

and I rewrite the client code with google benchmark as the client: https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_client.cc 

### What did you see instead?
I found that the performance of this unary interface is very low ,  the tps is about 1100(using 1cpu)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
my linux machine is : Intel(R) Xeon(R) CPU E5-4657L v2 @ 2.40GHz
                                   has 8 cpus

**Comment by yashykt** [comment]
https://grpc.io/docs/guides/performance/

Please follow this guide for some notes on getting high performance. The sync APIs are not really tuned for high performance, I would suggest using the callback API.
