### ISSUE TITLE
LoadLibrary failed with error 193

### ISSUE THREAD

**Issue by Taiizor** [grpc/grpc#34626]
### What version of gRPC and what language are you using?
Grpc" "2.46.6"
Grpc.Core "2.46.6"
Grpc.Core.Api "2.57.0"
Google.Protobuf "3.24.4"

C#

### What operating system (Linux, Windows,...) and version?
Windows 11 ARM64

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Framework 4.8

### What did you do?
I just run the application.

### What did you see instead?

`[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [DISPATCHER UNHANDLED EXCEPTION START]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [Application crashed: Error loading native library "C:\Users\user\AppData\Local\Sucrose\Sucrose.Launcher\grpc_csharp_ext.x64.dll". LoadLibrary failed with error 193.]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [Inner exception: .]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [Stack trace:    bei Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   bei Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   bei Grpc.Core.Internal.NativeExtension..ctor()
   bei Grpc.Core.Internal.NativeExtension.Get()
   bei Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   bei Grpc.Core.GrpcEnvironment..ctor()
   bei Grpc.Core.GrpcEnvironment.AddRef()
   bei Grpc.Core.Server..ctor(IEnumerable'1 options)
   bei Sucrose.Grpc.Services.GeneralServerService.ServerCreate(ServerServiceDefinition Services)
   bei Sucrose.Launcher.App.Configure()
   bei Sucrose.Launcher.App.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [DISPATCHER UNHANDLED EXCEPTION FINISH]`

### Anything else we should know about your project / environment?
No.

**Comment by tonydnewell** [comment]
The Grpc.Core implementation of gRPC C# won't work on Windows ARM, since we don't provide windows-ARM flavor of the underlying grpc_csharp_ext.dll native library that Grpc.Core depends on.

Since Grpc.Core is currently in maintenance mode, we don't plan to work on this and you should treat Windows-ARM as unsupported in Grpc.Core.

If you use .NET instead of .NET Framework the you can try grpc-dotnet (which is now the recommended implementation of gRPC C#) - it doesn't have a native component and it should work even on Windows ARM.

**Comment by Taiizor** [comment]
Does this package support creating a server for Console Application, or does it only support Asp.Net?

**Comment by tonydnewell** [comment]
You can run the Kestrel web server hosting the gRPC services from a command line app.
There gRPC tutorial from Microsoft does this:
https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-7.0&tabs=visual-studio-code

**Comment by Taiizor** [comment]
Can we create the server application I'm trying to explain as a simple console application instead of using Asp.Net?

I've looked at tutorials and sample projects, but I couldn't find any information about this. All the server applications seem to be created as Asp.Net projects.

**Comment by tonydnewell** [comment]
The fact that the console app created in the grpc-dotnet tutorial uses Asp.Net is probably irrelevant (apart from needing some config files alongside the executable).
Here is a modified version of the server in the above tutorial to demonstrate it is a console app:

```c#
using GrpcGreeter.Services;

Console.WriteLine("Starting...");
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddGrpc();

var app = builder.Build();

// Configure the HTTP request pipeline.
app.MapGrpcService<GreeterService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

Console.WriteLine("Before app.Run ...");
var t = Task.Run(()=>app.Run());

Console.WriteLine("Press ENTER to exit");
Console.ReadLine();

```

As this forum is for reporting issues with gRPC core I suggest that if you have further questions on how to use grpc-dotnet then you ask elsewhere, such as https://stackoverflow.com/
