### ISSUE TITLE
Publish the gRPC beta package for PHP

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc#3464]

**Comment by stanley-cheung** [comment]
* grpc repo helloworld and route guide code examples and readme have been updated with latest beta API changes
 * grpc.io website PHP route guide tutorial has been updated
 * Packagist have been updated: https://packagist.org/packages/grpc/grpc#dev-release-0_11
 * Pecl have been updated: https://pecl.php.net/package/gRPC/0.6.0
