### ISSUE TITLE
bug(python): Possible regression in `grpcio==1.59.0` related to grpc thread pool hanging

### ISSUE THREAD

**Issue by parthea** [grpc/grpc#34672]
### What version of gRPC and what language are you using?
grpcio==1.59.0
python

### What operating system (Linux, Windows,...) and version?
Linux (ubuntu, rodete)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.16 
gcc version 13.2.0 (Debian 13.2.0-4) 

### What did you do?
I ran the sample code in https://github.com/googleapis/python-aiplatform/issues/2805#issue-1939885329 provided by a user of `google-cloud-aiplatform`

1. Install `google-cloud-aiplatform`
```
pip install google-cloud-aiplatform
```
2. Run this code

```
from google.cloud import aiplatform_v1
from concurrent.futures import ThreadPoolExecutor

def init_model_gardern_service_client(_):
    # Create a client
    client = aiplatform_v1.ModelGardenServiceClient()

def parallel_execution():
    with ThreadPoolExecutor() as executor:
        results = list(executor.map(init_model_gardern_service_client, [None]*2))

if __name__ == "__main__":
    parallel_execution()
```

The code hangs with `grpcio==1.59.0` but not `grpcio==1.54.0`, `grpcio==1.56.0`, `grpcio==1.58.0` as an example

### What did you expect to see?
I expected the code to run successfully.

### What did you see instead?
Threads were hanging as reported in https://github.com/grpc/grpc/issues/31885

### Anything else we should know about your project / environment?
I'm not able to reproduce the issue with other versions of grpc such as `grpcio==1.54.0`, `grpcio==1.56.0`, `grpcio==1.58.0` so it's possible that there is a regression in `grpcio==1.59.0`

**Comment by XuanWang-Amos** [comment]
I don't think It's not related to the fork issue, I'm able to find the culprit: https://github.com/grpc/grpc/pull/34408

It's hanging while calling `grpc_ssl_credentials_create`:  https://gist.github.com/XuanWang-Amos/bb1b933126d0d6dd7015f14821a77dda

It's not reproducible 100% of the time, but it's high enough to caught it, @gtcooke94 can you help take a look?

**Comment by parthea** [comment]
Should this be marked as P1 since it appears to be easily reproducible and is a regression from previous versions?

**Comment by gtcooke94** [comment]
I'm not 100% sure what all this wrapping is doing.
I wrote a quick test that did thousands of concurrent calls to `grpc_ssl_credentials_create` and haven't been able to replicate a deadlock in the fn.
Can you link your minimal replication @XuanWang-Amos ? Ideally in just C/C++

**Comment by miketom2019** [comment]
i am sorry that i am a newer, but i love this project, i want to know how do i use or compile this porject in python(this is the only language i know).some one can give me a book about it ?thank you

**Comment by miketom2019** [comment]
i mean how i can use the gPRC in my python project??thank you

**Comment by XuanWang-Amos** [comment]
After some digging, I think I know why it's hanging and why it's only reproducible in Python:
* Like mentioned above, we're calling `grpc_ssl_credentials_create()` twice in different thread.
* In the PR, we moved the `GetPemRootCerts()` call to `grpc_ssl_credentials` so it will also be called twice in different thread.
* `GetPemRootCerts()` calls `InitRootStore()` which was guarded by `gpr_once_init` (If multiple threads call `gpr_once()` on the same gpr_once instance, one of them will call `(*init_function)()`, and the others will block until that call finishes.).
  * So one thread calls `init_function` and another thread blocks.
* In python we have [our own grpc_ssl_roots_override_callback](https://github.com/grpc/grpc/blob/5df9082f449319217bf0b10abeb66cd87dee928d/src/python/grpcio/grpc/_cython/cygrpc.pyx#L91-L92) which will be triggered by `InitRootStore()` and requires GIL lock:
https://github.com/grpc/grpc/blob/5df9082f449319217bf0b10abeb66cd87dee928d/src/python/grpcio/grpc/_cython/_cygrpc/security.pyx.pxi#L20-L33


This means after the code change, when `grpc_ssl_credentials_create()` called twice in different thread:
  * One thread will hold the `gpr_once` lock and block on GIL lock.
  * Another thread will hold the GIL lock and block on `gpr_once` lock.

**Comment by skraelings** [comment]
Run in a similar issue since 1.59.0 came out. Several of our cloud functions (gen2 with concurrency > 1) were timing out. After enabling GRPC traces in one of them we noticed the grpc initialization did not contain the grpc channel creation (to datastore) and it does hang at `grpc_ssl_credentials_create` as has been pointed out.

**Comment by miketom2019** [comment]
hello . I am really sorry, I am a Ubuntu new user, how can i compile the gRPC in my computer? thank you
