### ISSUE TITLE
Issue compiling grpc from source - _gRPC_CPP_PLUGIN-NOTFOUND

### ISSUE THREAD

**Issue by TusharJadhav** [grpc/grpc#34689]
### What version of gRPC and what language are you using?
1.59.1

### What operating system (Linux, Windows,...) and version?
Linux (Red Hat)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (ver 7.3.1-17)

### What did you do?
I am trying to use grpc in my C++ project and using Linux (Red Hat). I cloned the latest grpc (1.59.1) into my C++ project under third-party/grpc folder. In my projects root CMakeLists.txt file, I added the line `add_subdirectory(third-party/grpc)`.

When I compile my project, grpc source code compilation fails at the very end with the below error -

`gmake[2]: *** No rule to make target `third-party/grpc/_gRPC_CPP_PLUGIN-NOTFOUND', needed by `gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc'.  Stop.
gmake[2]: *** No rule to make target `third-party/grpc/_gRPC_CPP_PLUGIN-NOTFOUND', needed by `gens/src/proto/grpc/channelz/channelz.grpc.pb.cc'gmake[1]: .  Stop.
*** [third-party/grpc/CMakeFiles/grpc++_reflection.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [third-party/grpc/CMakeFiles/grpcpp_channelz.dir/all] Error 2
Consolidate compiler generated dependencies of target grpc++_error_details
Consolidate compiler generated dependencies of target grpc++_alts
[100%] Linking CXX shared library ../../app-bin/lib/x86_64/libgrpc++_error_details.so
[100%] Linking CXX shared library ../../app-bin/lib/x86_64/libgrpc++_alts.so
[100%] Built target grpc++_error_details
[100%] Built target grpc++_alts
gmake: *** [all] Error 2
`

### What did you expect to see?
Successful compilation of grpc

### What did you see instead?
Compilation failed

### Anything else we should know about your project / environment?
No

**Comment by TusharJadhav** [comment]
Am I missing grpc C++ plugin? How can I get it if the source is not automatically compiling it?

**Comment by Bat-Sheva-Sh** [comment]
i have the same issue too
any solution?

**Comment by veblush** [comment]
Would you provide a small repo? Note that we have https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake_as_submodule.sh that tests this use-case so you can take a look at this to figure out what's difference.
