### ISSUE TITLE
Schedulling/load balancing requests within conditional queues in async server

### ISSUE THREAD

**Issue by rgc183** [grpc/grpc#34682]
### What version of gRPC and what language are you using?
1.51

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Created async C++ server with 2 worker threads each having one conditional queue. Whenever new request is received, that same thread schedules new RPC on that conditional queue so new client requests can be served. I ran a stress test with the application. After about 4 hours one of the thread, say A, stops serving new requests and all the new requests are served by other thread, say B. Thread A is waiting on the conditional queue but not receiving any event. After sometime thread B gets stalled in the application. Now, if new client tries to connect, request is not served. 

```
void RegisterServer(){
 
  // Use separate completion queue for each serving thread.
  for (int i = 0; i < num_serving_threads; i++)
    completion_queues_.emplace_back(builder.AddCompletionQueue());

  server_ = builder.BuildAndStart();
  std::vector<std::thread> serving_threads;
  for (int i = 0; i < num_serving_threads; i++) {
    // Schedule outstanding RPCs equally on all the completion queues.
    for (auto &register_service : register_rpc_list) {
      for (int j = 0;
           j < (register_service.num_connections_ / num_serving_threads);
           j++)
        register_service.register_rpc_(completion_queues_[i].get());
    }

    serving_threads.emplace_back(&RegisterServer::HandleRpcs, this,
                                 completion_queues_[i].get());
  }
  
  }


void HandleRpcs(grpc::ServerCompletionQueue *cq) {
  VLOG(4) << __func__ << " + ";
  CQTag cq_tag;
  while (true) {
    // Block waiting to read the next event from the completion queue. The
    // event is uniquely identified by its tag, which in this case is the
    // memory address of a CallData instance.
    // The return value of Next should always be checked. This return value
    // tells us whether there is any kind of event or cq_ is shutting down.
    GPR_ASSERT(cq->Next((void **)&cq_tag.cq_tag_callback, &cq_tag.ok));
    (*cq_tag.cq_tag_callback)(cq_tag.ok);
  }
  VLOG(4) << __func__ << " - ";
}

  void RegisterRpc(grpc::ServerCompletionQueue *cq) override {
    new BidiState<typename Service::AsyncService, Request, Response>(
        this->GetService(), cq, service_request_, this);
  }
  
  
  BidiState(ServiceType *service, grpc::ServerCompletionQueue *cq,
            typename BidiCallbacksType::ServiceRequest serviceRequest,
            IServer<ServiceType, RequestType, ResponseType> *server) {
            
     // Some init code for initialization.
     
     /* 
     using ServiceRequest = std::function<void(
      ServiceType *, grpc::ServerContext *,
      grpc::ServerAsyncReaderWriter<ResponseType, RequestType> *,
      grpc::CompletionQueue *, grpc::ServerCompletionQueue *, void *)>; 
      ServiceRequest service_request;
     */
     callbacks_.service_request_(service, &grpc_context_, &streamer_, cq, cq,
                                &on_init_);
  }
```

Update:

In one of the tests, I found that when num_connections is 50, each queue will be scheduled with 25 each. When I start server, I tried to connect 10 clients. All of the requests went to first queue and second queue/thread was idle since beginning.

**Comment by markdroth** [comment]
It's not possible to tell from the information in this bug report whether the problem is in gRPC or in your application.  Can you share your code and a recipe to reproduce the problem?

**Comment by rgc183** [comment]
@markdroth  I have added code, which does setup of queues and initialization. Please let me know if you need any more information.

I also updated one more observation with different test.

**Comment by markdroth** [comment]
Can you please provide a complete runnable example that I can use to reproduce this?  I don't see anything obviously wrong with the code you pasted, but it's not a complete example that I can run.

**Comment by rgc183** [comment]
@markdroth I understand the concern let me find out how can I share the code with you since it is proprietary. 
Meanwhile would you please help me to understand if there are multiple CQs how scheduling is done between them if new client arrives?  Lets assume there are 2 CQs, 2 worker threads, 1 worker thread for 1 CQ, few scenarios:
1. If both queues schedule 100 RPCs each of them, so they have a capacity to accept new connection from 100 clients. Now, if there are n requests n<100 how it is decided, which queue will receive a new client request?
2. If both queues schedule 10 RPCs each of them, and there are total 20 new requests. Now both worker threads are busy in the application and haven't called "RegisterRPC" to accept new connection. Now, would it exactly load balance 10 on each of them? 
3.  If both queues schedule 10 RPCs each of them, and there are total 20 new requests. Now both worker threads are busy in the application and haven't called "RegisterRPC" to accept new connection. Now 2 more clients tries to connect, where would these request go? Let's assume after sometime, one of the worker thread calls "RegisterRPC", which will accept one new client request. How long would it wait before connection request is dropped or it will wait infinitely ?

Apart from this, who is putting requests into CQs?

**Comment by rgc183** [comment]
hi @markdroth Would you please mention explicitly what parts of code you are looking for?

Since requests are assigned as first-Fit policy, first CQ which has RequestCall() pending, this explains behavior what I have seen, where all client requests will go to only CQ since it has RequestCall() pending.

I still have question, if RequestCall() is not pending on any CQ, what happens to the new client request? Would it be dropped immediately? or there is timeout?

Thanks for pointers on Callback APIs, I will take a look.

**Comment by markdroth** [comment]
> Would you please mention explicitly what parts of code you are looking for?

I am asking for a complete standalone program that I can compile and run as-is that will demonstrate the problem.

> Since requests are assigned as first-Fit policy, first CQ which has RequestCall() pending, this explains behavior what I have seen, where all client requests will go to only CQ since it has RequestCall() pending.

If you have started only one RequestCall operation on only one CQ, then yes, that's the only CQ on which those ops will return.  But I think that's not what you want here.  If you want to spread the load of the incoming calls over the CQs, then you need to ensure that you always have a RequestCall op pending on every CQ.

> I still have question, if RequestCall() is not pending on any CQ, what happens to the new client request? Would it be dropped immediately? or there is timeout?

The request will be queued.

**Comment by rgc183** [comment]
> If there are multiple CQs on which there is a RequestCall() pending, the calls should be getting distributed over those CQs.
Sorry, I still have not understood the scheduling policy. can you explain how this distribution is done? Are the based on First-fit, round robin or what?

**Comment by markdroth** [comment]
There is no guarantee of how the calls are distributed across the CQs.  The CQ that picks up the event tends to get the call.  If there is no RequestCall() pending on the CQ that gets the event, then we search for the next CQ that does have a pending RequestCall().

So we don't guarantee exactly even distribution, but you also shouldn't be seeing all calls going to a single CQ unless there's something screwey with when each thread is polling the CQs.

Still waiting for a complete example that I can run to demonstrate this problem.
