### ISSUE TITLE
GRPC clien load balancing observability

### ISSUE THREAD

**Issue by cudothanh-Nhan** [grpc/grpc#34684]
### Is your feature request related to a problem? Please describe.
When I use grpc client load balancing feature in Java, I works perfectly when one of upstream server dies. However, as a client, it have no idea which upstream server died and when it restarted,...

### Describe the solution you'd like
So, I suggest adding observability feature in grpc

Thank team for revising my request.

**Comment by eugeneo** [comment]
There is a number of observability features in gRPC but it looks like what you need is outside the scope of gRPC. Please consult documentation of the platform you use to deploy your gRPC services for details on how to monitor their lifetime.
