### ISSUE TITLE
abseil patch branch 20230802.1 avaialble - build failed with grpcio-1.59.0 (Python 3.11) on FreeBSD 13.2

### ISSUE THREAD

**Issue by spchamp** [grpc/grpc#34698]
### What version of gRPC and what language are you using?

grpcio-1.59.0 (Python)

### What operating system (Linux, Windows,...) and version?

FreeBSD 13.2

trying to build the PyPI grpcio-1.59.0 distribution locally (not for ports) with pip

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.11.4

### What did you do?

I was trying to install the Python grpcio-1.59.0 build. There's no wheel for this on FreeBSD, so the build was from source.

### What did you expect to see?

Nothing expected

### What did you see instead?

build failure, under `third_party/abseil-cpp`, `static_cast from 'pthread_t' (aka 'pthread *') to 'pid_t' (aka 'int') is not allowed`
```
  /usr/local/libexec/ccache/clang -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -Wno-everything -Wno-thread-safety -fdebug-prefix-map=/wrkdirs/usr/ports/lang/py
thon311/work/Python-3.11.4=/usr/ports/lang/python311/work/Python-3.11.4 -Wno-everything -Wno-thread-safety -fno-strict-aliasing -isystem /usr/local/include -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_U
SER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.59.0\" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DGRPC_DO_
NOT_INSTANTIATE_POSIX_POLLER=1 -D__STDC_FORMAT_MACROS -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -I/usr/include -Ithird_party/re2 -I/usr/inc
lude/openssl -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/utf8_range -Ithird_party/xxhash -I/usr/include -I/env/include -I/usr/local/include/pyth
on3.11 -c third_party/upb/upb/hash/common.c -o python_build/temp.freebsd-13.2-STABLE-amd64-cpython-311/third_party/upb/upb/hash/common.o -pthread                                                 
  third_party/abseil-cpp/absl/base/internal/sysinfo.cc:450:10: error: static_cast from 'pthread_t' (aka 'pthread *') to 'pid_t' (aka 'int') is not allowed
    return static_cast<pid_t>(pthread_self());                                                                                                                                                    
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                     
  1 error generated.    
```

### Anything else we should know about your project / environment?

After a [bug report with abseil on OpenBSD](https://github.com/abseil/abseil-cpp/issues/1518) I believe this might be addressed in the Abseil release [Abseil LTS branch, Aug 2023, Patch 1](https://github.com/abseil/abseil-cpp/releases/tag/20230802.1) 

I'll try to test this locally, to update the abseil submodule ref then build from the source tree

This is for installing the [OpenBB terminal](https://github.com/OpenBB-finance/OpenBBTerminal). Albeit new to this codebase, I believe grpcio is used with [degiro-connector](https://pypi.org/project/degiro-connector/)

**Comment by spchamp** [comment]
After applying [an additional patch from FreeBSD ports](https://cgit.freebsd.org/ports/tree/devel/py-grpcio/files/patch-third__party_abseil-cpp_absl_time_internal_cctz_src_time__zone__format.cc) for the abseil sources under grpcio, I was able to build grpcio with the updated submodule ref for [Abseil LTS branch, Aug 2023, Patch 1](https://github.com/abseil/abseil-cpp/releases/tag/20230802.1) using Python 3.11.4 on FreeBSD 13.2.

I'll try to test out the build with OpenBB, just need to build pyarrow and one other thing for its dependencies lol

**Comment by ryanwinter** [comment]
> After applying [an additional patch from FreeBSD ports](https://cgit.freebsd.org/ports/tree/devel/py-grpcio/files/patch-third__party_abseil-cpp_absl_time_internal_cctz_src_time__zone__format.cc) for the abseil sources under grpcio, I was able to build grpcio with the updated submodule ref for [Abseil LTS branch, Aug 2023, Patch 1](https://github.com/abseil/abseil-cpp/releases/tag/20230802.1) using Python 3.11.4 on FreeBSD 13.2.
> 
> I'll try to test out the build with OpenBB, just need to build pyarrow and one other thing for its dependencies lol

This solved my compilation issue when using this dependency for the nest integration in Home Assistant

**Comment by XuanWang-Amos** [comment]
Thanks for the information, we'll be updating Abseil version in our next major release.

**Comment by ryanwinter** [comment]
Thanks @XuanWang-Amos

**Comment by XuanWang-Amos** [comment]
Closing this issue since [v1.60.0](https://pypi.org/project/grpcio/1.60.0/) was released on 12/07/2023, feel free to comment here if the issue still exist.
