### ISSUE TITLE
CMake build error on macOS

### ISSUE THREAD

**Issue by FloyzenCode** [grpc/grpc#34704]
What version of gRPC and what language are you using?

1.59.1

What operating system (Linux, Windows,...) and version?

MacOS Ventura 13.0

What did you do?

Followed the steps provided on https://grpc.io/docs/languages/cpp/quickstart/ to build grpc.
Get this warning "MACOSX_RPATH is not specified for the following targets: zlib" after running
       cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
      ../..
The build finally fails with: CMake Error at third_party/zlib/cmake_install.cmake:49 (file):
file cannot create directory: /lib. Maybe need administrative privileges.

Tried with sudo, still the same result.

What did you expect to see?

No errors

What did you see instead?

Build Failure

Anything else we should know about your project / environment?

Cmake version: 3.27.3

**Comment by eugeneo** [comment]
Please do not use `sudo`!

Our team will try to reproduce this issue.

**Comment by eugeneo** [comment]
I tried and had no issues building gRPC from a clean 1.59.1 checkout on Mac OS 13.6.

Some notes:
- I confirmed the `MACOSX_RPATH is not specified for the following targets: zlib` warning, it had no impact.
- I do not see `third_party/zlib/cmake_install.cmake` on my system.

**Comment by iriszhou320** [comment]
still seeing this error. anyone had a solution?

**Comment by FloyzenCode** [comment]
> still seeing this error. anyone had a solution?

nah, question close
