### ISSUE TITLE
Unable to use multiple root certificates to connect from client

### ISSUE THREAD

**Issue by Anam9** [grpc/grpc#34738]
### What version of gRPC and what language are you using?
C#, Grpc.Core.2.46.6-0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework

### What did you do?
I want to connect to multiple servers using TLS. The certificates on these servers are self-signed by different keys. I copied the root certificates to a single certificate file:

```
-----BEGIN CERTIFICATE-----
<RootCert0Pem>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<RootCert1Pem>
-----END CERTIFICATE-----
...
```

In my application, I read the file to pass it to the channel:
```
var cacert = File.ReadAllText(options.CaCertFile);
var ssl = new SslCredentials(cacert, new KeyCertificatePair(clientcert, clientkey));
```

### What did you expect to see?
The definition leads me to believe that the `cacert` parameter allows multiple certificates, so if I connect to servers where different roots apply it should all work,

```
   /// <summary>
   /// Creates client-side SSL credentials.
   /// </summary>
   /// <param name="rootCertificates">string containing PEM encoded server root certificates.</param>
   /// <param name="keyCertificatePair">a key certificate pair.</param>
   public SslCredentials(string rootCertificates, KeyCertificatePair keyCertificatePair) :
       this(rootCertificates, keyCertificatePair, null)
   {
   }

   /// <summary>
   /// Creates client-side SSL credentials.
   /// </summary>
   /// <param name="rootCertificates">string containing PEM encoded server root certificates.</param>
   /// <param name="keyCertificatePair">a key certificate pair.</param>
   /// <param name="verifyPeerCallback">a callback to verify peer's target name and certificate.</param>
   /// Note: experimental API that can change or be removed without any prior notice.
   public SslCredentials(string? rootCertificates, KeyCertificatePair? keyCertificatePair, VerifyPeerCallback? verifyPeerCallback)
   {
       this.rootCertificates = rootCertificates;
       this.keyCertificatePair = keyCertificatePair;
       this.verifyPeerCallback = verifyPeerCallback;
   }
```
### What did you see instead?

It does not connect, unless I move the root certificate to the top of the file. 

### Anything else we should know about your project / environment?
I see that a similar issue was reported for C++, but resolved with an environment variable workaround that is not feasible/applicable for my language/library: https://github.com/grpc/grpc/issues/18304

**Comment by tonydnewell** [comment]
@Anam9 I don't understand why you think you cannot set the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH environment variable as suggested in the other issue you have linked to.

To use different root certs for gRPC you should set the environment variable GRPC_DEFAULT_SSL_ROOTS_FILE_PATH to point to a PEM file containing the root certs. See [environment_variables.md](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)

**Comment by Anam9** [comment]
@tonydnewell I suppose I did not understand whether/how it will take effect from the client. For instance, environment_variables.md has variables to control logging like GRPC_VERBOSITY, but for my language/framework it appears Grpc.Core.Logging is used: https://grpc.github.io/grpc/csharp/api/Grpc.Core.Logging.html 

Since I did not find anything equivalent for SSL settings, hence my concern. Of course, trying to set the environment variable and see if it works regardless would be the best way to test it (which I will do once I can). I (re)opened this issue to confirm if environment variable workaround is going to be the final resolution.

**Comment by Anam9** [comment]
Follow up: setting the path of the pem file as GRPC_DEFAULT_SSL_ROOTS_FILE_PATH with all roots did not work. This is the exception I get: 

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception."))
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.")
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
```

Unless I move the root corresponding to this specific server I am trying to connect to at the top of the pem file.

**Comment by tonydnewell** [comment]
GRPC_VERBOSITY controls the level that is logged to the logger.

You can get the default logger from the `GrpcEnvironment`, for example:
```c#
static readonly ILogger Logger = GrpcEnvironment.Logger.ForType<ClientRunners>();
```
( see https://github.com/grpc/grpc/blob/17d9ce26e40ca13e96511eb9568d33ba5c7bc40d/src/csharp/Grpc.IntegrationTesting/ClientRunners.cs#L44C9-L45C1 )

or set a new logger:

```c#
GrpcEnvironment.SetLogger(new ConsoleLogger());
```
(see https://github.com/grpc/grpc/blob/17d9ce26e40ca13e96511eb9568d33ba5c7bc40d/src/csharp/Grpc.IntegrationTesting/InteropClient.cs#L84C13-L84C60)

**Comment by Anam9** [comment]
The GRPC_DEFAULT_SSL_ROOTS_FILE_PATH environment variable workaround works fine.
