### ISSUE TITLE
docgen.py fails with "error: invalid command 'build_data'"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#3473]
When I
```
<mint checkout>
make test_python
./tools/distrib/python/docgen.py --gh-user=nathanielmanistaatgoogle --doc-branch=0_11_0b1
```
I get
```
<lots of other stuff>
copying build/lib.linux-x86_64-2.7/grpc/_adapter/_c.so -> ./grpc/_adapter
running build_data
error: invalid command 'build_data'
Traceback (most recent call last):
  File "./tools/distrib/python/docgen.py", line 77, in <module>
    subprocess.check_call(**subprocess_arguments)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nathaniel/grpc/release/tools/distrib/python/distrib_virtualenv/bin/python', '/home/nathaniel/grpc/release/src/python/grpcio/setup.py', 'build']' returned non-zero exit status 1
```
. Is this expected? Can you reproduce? Have I missed something simple and trivial?

**Comment by soltanmm** [comment]
I can't replicate the issue.

Frankly, the `build_data` command shouldn't even be seen by *anything* in that script. As far as I know, only `grpcio_test` has anything semi-special to do with the `build_data` step. On what machine did you hit this issue?

**Comment by nathanielmanistaatgoogle** [comment]
A brand-spanking-new next-to-nothing-custom-configured Ubuntu 14.04 workstation.

Thanks for attempting to replicate it; since you haven't been able to I'll see if I can get more details on it, and if I'm able to reliably reproduce it we can pick a time to pair debug it when we're both at our desks.

**Comment by nathanielmanistaatgoogle** [comment]
I suspect that with both of us looking at the same screen the resolution will be that you'll notice something happening and say "oh that - that's user error; don't do that". :-)

**Comment by nathanielmanistaatgoogle** [comment]
Closing; I suspect the problem behind this is better identified and described in #4473.
