### ISSUE TITLE
Failed to create secure client channel

### ISSUE THREAD

**Issue by shishamo** [grpc/grpc#34754]
### What version of gRPC and what language are you using?
grpc: 1.58.0
php: 8.1

### What operating system (Linux, Windows,...) and version?
Linux container
Linux 4b7dafde69fb 6.4.16-linuxkit

### What runtime / compiler are you using (e.g. python version or version of gcc)
php: 8.1

### What did you do?
Try to call a grpc server (docker container) from a grpc php client (docker container, same network)
I tried to call the grpc server from the client using the server container name

### What did you expect to see?
A correct server response message

### What did you see instead?
Get the following error
`Failed to create secure client channel`

### Anything else we should know about your project / environment?
- I can call the grpc server from the client using curl without any error
- I can call the grpc server from the client using the server container ip address without any error
- I set the credentials option as below
`'credentials' => ChannelCredentials::createInsecure()`

**Comment by alto-php** [comment]
I am unable to reproduce this, could you provide a reproducible environment (e.g. docker file, github repo, or at least some code snippets)?

**Comment by shishamo** [comment]
i am sorry, it looks like it was my mistake, i wasn't using the good port...
i close that issue
