### ISSUE TITLE
Deprecation of distutils broke builds due to missing setuptools functionality

### ISSUE THREAD

**Issue by wbarnha** [grpc/grpc#34762]
### What version of gRPC and what language are you using?

grpcio 1.59.0, Python

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

pypy:3.9-slim-bullseye

### What did you do?
```bash
GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install grpcio==1.58.0 --no-build-isolation
```

### What did you expect to see?
The latest version of grpcio should be installing normally.

### What did you see instead?
```python
Collecting grpcio
Downloading grpcio-1.59.0.tar.gz (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 54.6 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [10 lines of output]
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/tmp/pip-install-gg89uq56/grpcio_4d964c91b8264148aa2045c1c603a51b/setup.py", line 95, in <module>
        import commands
      File "/tmp/pip-install-gg89uq56/grpcio_4d964c91b8264148aa2045c1c603a51b/src/python/grpcio/commands.py", line 31, in <module>
        import support
      File "/tmp/pip-install-gg89uq56/grpcio_4d964c91b8264148aa2045c1c603a51b/src/python/grpcio/support.py", line 111, in <module>
        errors.CompileError: diagnose_compile_error,
    AttributeError: module 'setuptools.errors' has no attribute 'CompileError'
    [end of output]
```

Looks like the commit in https://github.com/grpc/grpc/commit/c7a13365665ed9f716e799ffd57d8d2716b34775#diff-9288335e7515c44a17baffc87613618e665a3c4518ff8977981b4a350a7c2d8d introduced this bug. I dug around `setuptools` and I can't find anything that immediately resembles `CompileError`, so additional insights from the community would be appreciated as to how this functionality can be swapped over from `distutils`.

### Anything else we should know about your project / environment?

N/A

**Comment by XuanWang-Amos** [comment]
Hi, setuptools started expose those errors in v59.9.0, after that `CompileError` should be there:
https://github.com/pypa/setuptools/blame/2384d915088b960999ca74fb81ce70bffd17b082/setuptools/errors.py#L14

What's the version of setuptools you're using? Can you try upgrade it?
