### ISSUE TITLE
When calling endpoint from python (client) to dotnet (server) via unix-domain-socket I get `Received RST_STREAM with error code 1` 

### ISSUE THREAD

**Issue by astrema** [grpc/grpc#34760]
### What version of gRPC and what language are you using?
**dotnet**
- Grpc.AspNetCore.Server: 2.58.0
- Grpc.Core.Api: 2.58.0
- Grpc.Net.Common: 2.58.0
- Grpc.Tools: 2.59.0

**python3**
- grpcio: 1.59.0
- grpcio-tools: 1.59.0
- protobuf: 4.24.4

### What operating system (Linux, Windows,...) and version?
OS: Ubuntu 22.04.3 LTS
Kernel: 6.2.0-34-generic #34~22.04.1-Ubuntu

### What runtime / compiler are you using (e.g. python version or version of gcc)
- dotnet 7.0.402
- python 3.10.12

### What did you do?
- start grpc-server in dotnet, listening on a unix-domain-socket (works)
- start a python client, connecting to the dotnet-server via the unix-domain-socket (channel creation works)
- try to call a grpc-endpoint on the server (does not work)

I included a zip file with a small dotnet and python project, where the error is reproducible.
Both projects will need to have access to the same `/tmp`-folder in order to access the same unix-domain-socket.

1. start the dotnet project `GrpcServer`
2. execute the `main.py` from the python project

### What did you expect to see?
I expected that I can make a request from the python client to the dotnet server via the unix-domain-socket.

### What did you see instead?
When calling the method on the stub, I get the following exception:
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    information_response: InformationResponse = test_endpoint_stub.GetInformation(InformationQuery(
  File ".venv/lib/python3.10/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File ".venv/lib/python3.10/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 1"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-10-20T14:55:33.607722177+02:00", grpc_status:13, grpc_message:"Received RST_STREAM with error code 1"}"
>
```
I also executed the python script with  `GRPC_TRACE=all; GRPC_VERBOSITY=DEBUG`, the full log is attached.

### Anything else we should know about your project / environment?
- I tried to start the dotnet server with `GRPC_TRACE=all; GRPC_VERBOSITY=DEBUG` but nothing happened, any pointers?
- In the zip file included is also a small dotnet client, which connects via the same unix-domain-socket and can successfully execute the request.

[dotnet-projects.zip](https://github.com/grpc/grpc/files/13054720/dotnet-projects.zip)
[python.zip](https://github.com/grpc/grpc/files/13054637/python.zip)  
[full.log](https://github.com/grpc/grpc/files/13054643/full.log)

**Comment by apolcyn** [comment]
Please file grpc-dotnet issues on [grpc/grpc-dotnet repo](https://github.com/grpc/grpc-dotnet)
