### ISSUE TITLE
The latest v1.59.1, the protoc generated code is garbled.

### ISSUE THREAD

**Issue by mpv945** [grpc/grpc#34772]
helloworld.proto

syntax = "proto3";
package helloworld;
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc SayHelloStreamReply (HelloRequest) returns (stream HelloReply) {}
  rpc SayHelloBidiStream (stream HelloRequest) returns (stream HelloReply) {}
}
message HelloRequest {
  string name = 1;
}
message HelloReply {
  string message = 1;
}

-------------------------  Generate code -------------------------------
Helloworld.php

<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�
helloworld.proto
helloworld"
HelloRequest
name (	"

HelloReply
message (	2�
Greeter>
SayHello.helloworld.HelloRequest.helloworld.HelloReply" K
SayHelloStreamReply.helloworld.HelloRequest.helloworld.HelloReply" 0L
SayHelloBidiStream.helloworld.HelloRequest.helloworld.HelloReply" (0bproto3'
        , true);

        static::$is_initialized = true;
    }
}

**Comment by mpv945** [comment]
[Error picture description](url)
![截屏2023-10-23 00 53 13](https://github.com/grpc/grpc/assets/20806691/4dafc224-213f-449f-b692-ea3e26337a43)

**Comment by cleverlin** [comment]
I also encountered a garbled code problem, there is no solution? Is it OK to use the lower version?
```php
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�
hello.protomygrpcservices"#
HelloRequest
requestName (	"$

HelloResponse
responseMsg (	2V
	HelloTestI
SayHello.mygrpcservices.HelloRequest.mygrpcservices.HelloResponse"BZ	.;servicebproto3'
        , true);

        static::$is_initialized = true;
    }
}


```

**Comment by cleverlin** [comment]
I tried the v1.58.1 version, but it is also not working, is there a problem with my installation process?
```
$ git clone -b v1.58.1 https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ mkdir -p cmake/build
$ cd cmake/build
$ cmake ../..
$ make protoc grpc_php_plugin

$protoc --proto_path=./ --php_out=./ --grpc_out=./ --plugin=protoc-gen-grpc=/var/www/grpc/cmake/build/grpc_php_plugin hello.proto

``` 
Does anyone have a solution?

**Comment by cleverlin** [comment]
This is my proto file, and the generated client and request/reply
types is string

syntax = "proto3";

package mygrpcservices;

option go_package = ".;service";

service HelloTest {
  rpc SayHello(HelloRequest)returns(HelloResponse){}
}

message HelloRequest{
  string requestName = 1;
}

message HelloResponse{
  string responseMsg = 1;
}


alto-php ***@***.***> 于2023年10月26日周四 00:30写道：

**Comment by cleverlin** [comment]
report an error : Fatal error: Failed to parse binary descriptor，That's where the garbled code is

**Comment by mpv945** [comment]
> Solved, I can use grpc as long as I don't open the protoc generated (with binary) files

I have not set up the binary. Can you show me the generation command?
