### ISSUE TITLE
Web compilation with Emscripten

### ISSUE THREAD

**Issue by abdullahaygun** [grpc/grpc#34780]
**Can I compile gRPC to the Web with Emscripten?** 
NOTE: I'm trying to compile it but it keeps giving errors, please help, 
Thanks.

**Comment by drfloob** [comment]
The "new issue" form asks users not to post questions as Github issues. For general questions and troubleshooting, please ask/look for answers on StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc, or on the grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
