### ISSUE TITLE
There is no **Stub.php file in the PHP generated code?

### ISSUE THREAD

**Issue by mpv945** [grpc/grpc#34781]
https://github.com/grpc/grpc/tree/v1.58.0/examples/php/Helloworld
![Is there any example code on the official website?](https://github.com/grpc/grpc/assets/20806691/c8a6023d-e5f1-4856-b67f-0c4c3f6aa295)
![I used the latest tutorial from the official website and used the code generated by PHP8.2](https://github.com/grpc/grpc/assets/20806691/429dd177-e94a-4844-9498-249c907a5b76)

Is PHPer going to be abandoned by the community?

**Comment by alto-php** [comment]
**Stub.php files are for the experimental PHP server, they are only generated with `generate_server` option.

Here is how they are generated:
https://github.com/grpc/grpc/blob/v1.59.0/examples/php/greeter_proto_gen.sh#L27
