### ISSUE TITLE
Access to underlying Slices in C++ ByteBuffer without a copy

### ISSUE THREAD

**Issue by raakella1** [grpc/grpc#34792]
### Is your feature request related to a problem? Please describe.
I am using generic service to transfer bytes of data. On the receiver side, I want to directly access the ByteBuffer contents I get from the `GenericServerAsyncReaderWriter.Read()`. It is not guarentied that this ByteBuffer is made up of a single slice. When this ByteBuffer is made up of multiple Slices, I need a way to access the Slices without incurring a copy. The TrySingleSlice only works when the ByteBuffer has only one slice.

### Describe the solution you'd like
A new Dump method that returns a vector of Slices which reference the underlying slices rather than make a copy.

### Describe alternatives you've considered
One alternative is for me to use grpc_byte_buffer directly but this is clearly not recommended. 

### Additional context
N/A

**Comment by yijiem** [comment]
> A new Dump method that returns a vector of Slices which reference the underlying slices rather than make a copy.

Didn't the `Status ByteBuffer::Dump(std::vector<Slice>* slices) const` method already does that? https://github.com/grpc/grpc/blob/master/include/grpcpp/support/byte_buffer.h#L124-L125
