### ISSUE TITLE
Python asyncio servers don't terminate on SIGINT/SIGTERM when running multiple servers in the same event loop

### ISSUE THREAD

**Issue by yliang-cb** [grpc/grpc#34873]
### What version of gRPC and what language are you using?
Python, grpcio 1.59.2

### What operating system (Linux, Windows,...) and version?
Linux, MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

```python
import asyncio
import signal

# pip install grpcio==1.59.2 grpcio-health-checking==1.59.2
import grpc
from grpc_health.v1 import health, health_pb2_grpc


async def serve(port: int) -> None:
    server = grpc.aio.server()
    health_pb2_grpc.add_HealthServicer_to_server(health.HealthServicer(), server)
    server.add_insecure_port(f"[::]:{port}")

    for sig in (signal.SIGINT, signal.SIGTERM):
        asyncio.get_event_loop().add_signal_handler(
            sig, lambda: asyncio.ensure_future(server.stop(0))
        )
    await server.start()
    await server.wait_for_termination()

async def main() -> None:
    # If we run only one server instance, the main process is able to terminate on SIGINT/SIGTERM
    # await serve(8000)

    # If we run multiple server instances, the main process doesn't terminate on SIGINT/SIGTERM
    await asyncio.gather(serve(8000), serve(8001))

if __name__ == "__main__":
    asyncio.run(main())
```

### What did you expect to see?
The main process terminates on SIGINT/SIGTERM, even when multiple server instances are running

### What did you see instead?
The main process doesn't terminate on SIGINT/SIGTERM, when multiple server instances are running. It does terminate on SIGINT/SIGTERM when only one server instance is running.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
N/A

**Comment by XuanWang-Amos** [comment]
Hi. I don't think this is related to gRPC. If you add a log to the signal handlers, you'll see that you're overriding the same signal handler, which is why only one of the servers is terminating.
