### ISSUE TITLE
Add a GRPC_LOGS_LOCATION environment variable

### ISSUE THREAD

**Issue by MarCialRG** [grpc/grpc#34875]
In environments where the stack of tools that call each other is complex:
- it is not always obvious which tool is ultimately using the gRPC Library and/or
- a user might not be able to run that tool directly from the command line 
thus making it impossible for some users to gather the gRPC logs.

Just like GRPC_VERBOSITY and GRPC_TRACE [1] are available, having a 3rd variable (GRPC_LOGS_LOCATION) to specify where the log messages will be printed, can be a life savior while troubleshooting.

[1] https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by veblush** [comment]
I reopened this because it's a feature request not a question.

**Comment by yashykt** [comment]
gRPC logging has moved to absl logging as of https://github.com/grpc/proposal/blob/master/L117-core-replace-gpr-logging-with-abseil-logging.md :)
