### ISSUE TITLE
ObjC - Add better documentation to run tests

### ISSUE THREAD

**Issue by nkibler** [grpc/grpc#3492]
Currently, there is no documentation that describes how to run tests for the ObjC library.

The README should highlight the important bits from the main gRPC install document, plus any ObjC custom stuff, to get the tests running. This is what the process was for me:

1. Install Xcode command-line tools by running: `sudo xcode-select --install`
2. Install [MacPorts](https://www.macports.org/install.php).
3. Run the following command:

    ```
    sudo /opt/local/bin/port install autoconf automake libtool gflags cmake
    ```

4. Either restart your terminal window or run `source ~/.bash_profile` to pick up the new PATH changes.

    (The rest of this process is what I did, not necessarily what should be done. ~~The OpenSSL issue needs to be figured out in a cleaner way.~~)

5. ~~Run the following command to prevent a CocoaPods issue [described here](https://github.com/CocoaPods/CocoaPods/issues/3823):~~

    ```
    export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES
    ```
6. ~~Comment the following lines in `<path-to-grpc-repo>/src/objective-c/tests/Podfile` so they become:~~

    ```
    #pod 'RemoteTest', :path => "../generated_libraries/RemoteTestClient"
    #pod 'RouteGuide', :path => "../generated_libraries/RouteGuideClient"
    ```
7. ~~Run the following commands:~~

    ```
    cd <path-to-grpc-repo>/src/objective-c/tests
    pod install
    ```
8. ~~If you see the message `Installing OpenSSL (<version_num>)` followed by a dump of a bash script and it just quits out, run the following commands:~~

    ```
    rm -rf /tmp/openssl
    pod install
    ```
9. ~~Now that you have OpenSSL installed, go back to `<path-to-grpc-repo>/src/objective-c/tests/Podfile` and uncomment those lines from the earlier step.~~
10. ~~Remove all changes that were made from running `pod install` earlier. This can be done by using git to discard all uncommitted changes. This command can help achieve that:~~

    ```
    # git clean -fd
    ```

11. Run the following commands from the gRPC repository's root directory:

    ```
    make clean
    ./tools/run_tests/run_tests/py -l objc
    ```

It's a really messy process that @jcanizales helped me get through, but it should be documented somewhere if this is the current process to run the tests.

**Comment by jcanizales** [comment]
Nate, I'm going to scratch steps off your instructions as I eliminate them, so that we can track progress.

**Comment by nkibler** [comment]
Sounds good to me!

**Comment by jcanizales** [comment]
Much better after switching to BoringSSL! :tada: :santa:

**Comment by nkibler** [comment]
Very nice! I didn't even know that was in the works! I'm sure that solves quite a few issues.

**Comment by makdharma** [comment]
Running tests is now as simple as 'python tools/run_tests/run_tests.py -l objc' on a typical developer mac machine. Closing.

**Comment by jcanizales** [comment]
There's still a number of steps here that need to be either documented or removed https://github.com/grpc/grpc/issues/3492#issue-108413617

**Comment by hsaliak** [comment]
Marking further enhancements to this as P3 for the GA release. /cc @jcanizales

**Comment by makdharma** [comment]
We need to add a README.md targeted for contributors to ObjC on how to run ObjC tests.
