### ISSUE TITLE
Objective-C library broken

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#3496]
```
[tls_pthread.c:41] assertion failed: 0 == pthread_setspecific(tls->key, (void *)value)
```

Stack trace and local variables:
<img width="1412" alt="screen shot 2015-09-25 at 7 34 13 pm" src="https://cloud.githubusercontent.com/assets/5120183/10115445/9d98ba80-63bc-11e5-9e68-bdd65dba9ddf.png">

**Comment by jcanizales** [comment]
CC: @nkibler

**Comment by jcanizales** [comment]
It happens in the master branch, and not in release-0_11 (as of today), meaning the bug was introduced after commit e5515d4.

**Comment by nicolasnoble** [comment]
This is very likely to be caused by #3423.
