### ISSUE TITLE
Rust-gRPC

### ISSUE THREAD

**Issue by kehiy** [grpc/grpc#35014]
I think we need a rust gRPC support and implementation.

**Comment by eugeneo** [comment]
Please be advised that there are existing community-provided options for gRPC support for Rust. We do not have plans to provide Rust support but this may change in the future.

**Comment by bcmyers** [comment]
For others who come across this issue: https://groups.google.com/g/grpc-io/c/ExbWWLaGHjI/m/TJssglLiBgAJ
