### ISSUE TITLE
"dotnet new grpc" doesn't build on a macbook pro m3

### ISSUE THREAD

**Issue by push-22** [grpc/grpc#35016]
I'm trying to create a GRPC app, but not getting any further than the initial steps.

from a terminal:

**dotnet new grpc [return]**
```
The template "ASP.NET Core gRPC Service" was created successfully.

Processing post-creation actions...
Restoring /Users/barrie/Code/tmp/grpctester/grpctester.csproj:
Determining projects to restore...
Restored /Users/barrie/Code/tmp/grpctester/grpctester.csproj (in 105 ms).
Restore succeeded.
```

Then
**dotnet build [return]**
```
MSBuild version 17.8.3+195e7f5a3 for .NET
Determining projects to restore...
All projects are up-to-date for restore.
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: The specified task executable "/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc" could not be run. System.ComponentModel.Win32Exception (86): An error occurred trying to start process '/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc' with working directory '/Users/barrie/Code/tmp/grpctester'. Bad CPU type in executable [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: at Microsoft.Build.Utilities.ToolTask.Execute() [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]

Build FAILED.
```

Executing the afore mentioned executable (/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc) results in:
`zsh: bad CPU type in executable: ./protoc`

dotnet --version
8.0.100

file -b /Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc
Mach-O 64-bit executable **x86_64**

file -b /usr/local/share/dotnet/dotnet
Mach-O 64-bit executable **arm64**

I don't see why I should install have to install rosetta to run this, protoc is available for arm64:
**https://github.com/protocolbuffers/protobuf/releases**

**Comment by tonydnewell** [comment]
`Grpc.Tools` only ships with x86_64 binaries for MacOS. These should run on arm64 with Rosetta installed.

Can you try running the binary it's complaining about 
`/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc`
 under rosetta as a stand alone binary?

Although you can download `protoc` for arm64 from https://github.com/protocolbuffers/protobuf/releases that does not have the gRPC protocol buffers plugins needed for generating the gRPC service code. Those plugins are only available in `Grpc.Tools`.

**Comment by push-22** [comment]
As I said in the bug - I don't want to use rosetta. 

As you can't fix it, I'll have do it myself and use the protoc that google produce for macos arm64 and ignore the plugin.
