### ISSUE TITLE
gRPC service that returns Exception cannot restart

### ISSUE THREAD

**Issue by JoanFM** [grpc/grpc#35017]
### What version of gRPC and what language are you using?

Python, grpc 

Name: grpcio
Version: 1.47.5

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.10

### What did you do?
I have an example repo in https://github.com/JoanFM/grpc-error-show where u can reproduce the issue in an venv.

You can call `run.py` and u will see.

I start in a for loop grpc servers in a for loop, these servers will return an Exception, and these servers will be started in a subprocess. 
Once the server starts, a request will be sent that raises an Exception.

The problem I see is that from the 2nd server, it does not succeed to receive calls.

### What did you expect to see?

The servers should start smoothly and work fine and receive requests

### What did you see instead?

Blocking behavior. Also is worth noticing that there always appear this message:

```
E1118 11:44:10.225386085   25592 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
```

### Anything else we should know about your project / environment?
The repo I propose is a simplification of what is done in Jina project, and this is affecting our testing because we start a lot of grpc services constantly.

**Comment by XuanWang-Amos** [comment]
Hi, thanks for the reproduction code, we'll try reproduce it locally.

I also noticed you're using `1.47.5`, does this issue still exist in recent versions?

**Comment by JoanFM** [comment]
This does not happen with newest, but I see SegFaults that are hard to reprodue, I wonder if the source may be the same.

**Comment by gnossen** [comment]
> This does not happen with newest, but I see SegFaults that are hard to reprodue

Glad to hear that this particular issue has been resolved. If you're able to provide any info about segfaults you've encountered, please create a new issue with the information on it.
