### ISSUE TITLE
release 1.59.3 fails pip install on raspbian bullseye

### ISSUE THREAD

**Issue by maciek01** [grpc/grpc#35027]
### What version of gRPC and what language are you using?

1.59.3

python 3.9.2

### What operating system (Linux, Windows,...) and version?

Linux - raspberry pi zro w - raspberry pi os - bullseye

### What runtime / compiler are you using (e.g. python version or version of gcc)

python 3.9.2

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

i was in the process of installing mavsdk python module, this module depends on your grpc library

i executed the following command:

sudo pip3 install --upgrade --no-cache-dir mavsdk

5 days back i performed the same install and all worked well - at that time the grpc version was probably the previous one , 1.59.2, as i noticed that .3 was released just 2 days ago. 

### What did you expect to see?

i expected to see a clean installation

### What did you see instead?

instead i saw pip3 failure - details below

 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5jvqy26k/grpcio_90b923fe38084649aca68c47802549c2/setup.py", line 95, in <module>
          import commands
        File "/tmp/pip-install-5jvqy26k/grpcio_90b923fe38084649aca68c47802549c2/src/python/grpcio/commands.py", line 31, in <module>
          import support
        File "/tmp/pip-install-5jvqy26k/grpcio_90b923fe38084649aca68c47802549c2/src/python/grpcio/support.py", line 111, in <module>
          errors.CompileError: diagnose_compile_error,
      AttributeError: module 'setuptools.errors' has no attribute 'CompileError'
      [end of output]

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

here is the full error:

sudo pip3 install --upgrade --no-cache-dir mavsdk
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mavsdk
  Downloading mavsdk-1.4.9-py3-none-linux_armv6l.whl.metadata (6.6 kB)
Collecting aiogrpc>=1.8 (from mavsdk)
  Downloading https://www.piwheels.org/simple/aiogrpc/aiogrpc-1.8-py3-none-any.whl (10 kB)
Collecting grpcio>=1.50.0 (from mavsdk)
  Downloading grpcio-1.59.3.tar.gz (24.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5jvqy26k/grpcio_90b923fe38084649aca68c47802549c2/setup.py", line 95, in <module>
          import commands
        File "/tmp/pip-install-5jvqy26k/grpcio_90b923fe38084649aca68c47802549c2/src/python/grpcio/commands.py", line 31, in <module>
          import support
        File "/tmp/pip-install-5jvqy26k/grpcio_90b923fe38084649aca68c47802549c2/src/python/grpcio/support.py", line 111, in <module>
          errors.CompileError: diagnose_compile_error,
      AttributeError: module 'setuptools.errors' has no attribute 'CompileError'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by XuanWang-Amos** [comment]
Hi, I see this error: `AttributeError: module 'setuptools.errors' has no attribute 'CompileError'`, this means you don't have a higher enough version of setuptools, can you try update it first and try install again?

Most likely install will still fail, but we'll have a better idea why.

**Comment by maciek01** [comment]
looks like setuptool version 52.0.0 makes the issue go away - thanks
