### ISSUE TITLE
[grpc] Triggered assertion on `last & STATE_UNORPHANED` in combiner.cc

### ISSUE THREAD

**Issue by vitsai** [grpc/grpc#35044]
### What version of gRPC and what language are you using?

1.50.2, C++

### What operating system (Linux, Windows,...) and version?

Linux (6.2.0-1016-gcp)

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang-12

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?

No assertion

### What did you see instead?

```
E1120 03:02:24.017518323     264 combiner.cc:150]            assertion failed: last & STATE_UNORPHANED
*** SIGABRT received at time=1700478144 on cpu 2 ***
PC: @     0x7f2305f2400b  (unknown)  raise
    @     0x7f230643f420       3936  (unknown)
    @     0x5575fddf92f3         48  destroy_stream()
    @     0x5575fdfeca4d         80  grpc_call_stack_destroy()
    @     0x5575fdffb577         64  grpc_core::FilterStackCall::DestroyCall()
    @     0x5575fe0517b4         80  grpc_core::ExecCtx::Flush()
    @     0x5575fdfef7b8        304  cq_next()
    @     0x5575fdc9c6a5         48  grpc::(anonymous namespace)::CallbackAlternativeCQ::Ref()::{lambda()#1}::_FUN()
    @     0x5575fe0703b6        112  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::_FUN()
    @     0x7f2306433609  (unknown)  start_thread
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
That's surprising. The code in consideration hasn't changed in quite some time, and I don't think I've seen such a failure in any of our tests either. 

Could you provide some kind of repro please?
