### ISSUE TITLE
After "Failed getpeername: Bad file descriptor" the unix domain grpc server does not recover unless restarted

### ISSUE THREAD

**Issue by ssachinbharadwaj** [grpc/grpc#35076]
### What version of gRPC and what language are you using?
1.52.1

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++

### What did you do?
I have two c++ applications (grpc server and client) running on the same device. They both communicate over the Unix domain socket. Both are using same grpc library version 1.52.1.
Server listens on "unix:/var/run/server_uds"
The client keeps creating new channels, fires a unary RPC and closes the channel.
Occasionally the client is restarted

**In some extremely rare cases, I see the following error on server side:**
E1011 19:45:02.624072018    1864 tcp_server_posix.cc:245]              Failed getpeername: Bad file descriptor

Once the above error is seen, the server no longer accepts any new connections.

The issue was seen 3 times in the production environment and I was not able to reproduce the "Failed getpeername: Bad file descriptor" error myself. However, one correlating factor from the logs was the restart of the client.
Just after the restart of client, this error is seen on the server and the server goes to a bad state.
I tried restarting the client multiple times around the time of channel creation but getpeername always succeeded.

**However, I was able to enter the path of an "irrecoverable state" by making the below change to forcefully enter the failure path:**
https://github.com/grpc/grpc/blob/v1.52.1/src/core/lib/iomgr/tcp_server_posix.cc#L225

```
    if (sp->server->memory_quota->IsMemoryPressureHigh()) {
      int64_t dropped_connections_count =
          num_dropped_connections.fetch_add(1, std::memory_order_relaxed) + 1;
      if (dropped_connections_count % 1000 == 1) {
        gpr_log(GPR_INFO,
                "Dropped >= %" PRId64
                " new connection attempts due to high memory pressure",
                dropped_connections_count);
      }
      close(fd);
      continue;
    }

+ close(fd);   // <<<<<<<<< Faking the failure
+ goto error; // <<<<<<<<< Faking the failure

    // For UNIX sockets, the accept call might not fill up the member sun_path
    // of sockaddr_un, so explicitly call getpeername to get it.
    if (grpc_is_unix_socket(&addr)) {
      memset(&addr, 0, sizeof(addr));
      addr.len = static_cast<socklen_t>(sizeof(struct sockaddr_storage));
      if (getpeername(fd, reinterpret_cast<struct sockaddr*>(addr.addr),
                      &(addr.len)) < 0) {
        gpr_log(GPR_ERROR, "Failed getpeername: %s",
                grpc_core::StrError(errno).c_str());
        close(fd); // <<<<<<<<< Real failure place
        goto error; // <<<<<<<<< Real failure place
      }
    }
```

**Hacky fix (not well tested): If I change the same code to below, it keeps accepting new connections:**
```
    if (sp->server->memory_quota->IsMemoryPressureHigh()) {
      int64_t dropped_connections_count =
          num_dropped_connections.fetch_add(1, std::memory_order_relaxed) + 1;
      if (dropped_connections_count % 1000 == 1) {
        gpr_log(GPR_INFO,
                "Dropped >= %" PRId64
                " new connection attempts due to high memory pressure",
                dropped_connections_count);
      }
      close(fd);
      continue;
    }

+ close(fd);   // <<<<<<<<< Faking the failure
+ continue; // <<<<<<<<< Continuing

    // For UNIX sockets, the accept call might not fill up the member sun_path
    // of sockaddr_un, so explicitly call getpeername to get it.
    if (grpc_is_unix_socket(&addr)) {
      memset(&addr, 0, sizeof(addr));
      addr.len = static_cast<socklen_t>(sizeof(struct sockaddr_storage));
      if (getpeername(fd, reinterpret_cast<struct sockaddr*>(addr.addr),
                      &(addr.len)) < 0) {
        gpr_log(GPR_ERROR, "Failed getpeername: %s",
                grpc_core::StrError(errno).c_str());
        close(fd); // <<<<<<<<< Real failure place
        goto error; // <<<<<<<<< Real failure place
      }
    }
```

So, should the "goto error;" be replaced with "continue;"?

### What did you expect to see?
1. I expect to not see "Bad file descriptor" in the first place
2. Even if "Bad file descriptor" is seen, it should recover

### What did you see instead?
I see that after hitting the "Failed getpeername: Bad file descriptor", the server stops accepting any new connections.
In the netstat, the UDS socket is still in the LISTENING state and all the attempts made to connect will keep increasing as CONNECTING. The entries keep growing and even if the client is restarted, the entries won't go away.

$netstat -an | grep "server_uds"
26901:unix  2      [ ACC ]     STREAM     LISTENING     121121   11115/server         /var/run/server_uds
27009:unix  2      [ ]         STREAM     CONNECTING    0        -                   /var/run/server_uds
27023:unix  2      [ ]         STREAM     CONNECTING    0        -                   /var/run/server_uds
27024:unix  2      [ ]         STREAM     CONNECTING    0        -                   /var/run/server_uds
27034:unix  2      [ ]         STREAM     CONNECTING    0        -                   /var/run/server_uds
27035:unix  2      [ ]         STREAM     CONNECTING    0        -                   /var/run/server_uds

The only way to recover from the above state is to restart the server.

### What am I expecting from this github issue?
1. A fix which can recover the server even if "Failed getpeername: Bad file descriptor" is seen once
2. Any inputs on how to really reproduce "Failed getpeername: Bad file descriptor" naturally. What else can I try other than restarting the client?

**Comment by yashykt** [comment]
On a cursory look, it seems weird that `getpeername()` is failing. Do you know why that's happening?

**Comment by ssachinbharadwaj** [comment]
@yashykt the only correlating event from the logs is the restarts of the client. But I failed to reproduce it myself.
While the reason for getpeername() failure is unknown, the error handling should be such that grpc server recovers. The current code does not recover once it hits the issue and stops accepting further connections from all the clients.

**Comment by drfloob** [comment]
@ssachinbharadwaj I'm not sure how the server's `fd` could get corrupted in your case, there's almost nothing between `accept` and `getpeername`. Even if the client closes the connection in between these calls, or someone deletes the socket file, `getpeername` should succeed and have an empty string. By any chance is your server `fork`ing at this point?

What flavor of Linux are you running?

> 2. Even if "Bad file descriptor" is seen, it should recover

I'm not sure this is true. If there's a good explanation for how the fd could be corrupted, then it would make more sense to continue on with server operations.

**Comment by drfloob** [comment]
> I'm not sure [if the server should recover]. If there's a good explanation for how the fd could be corrupted, then it would make more sense to continue on with server operations.

But to your point @ssachinbharadwaj, if the server should stop accepting incoming connections due to inexplicable corruption of some kind, it should do so LOUDLY. Right now this is a silent failure.

**Comment by ssachinbharadwaj** [comment]
@drfloob Thank you for looking into this.

> By any chance is your server `fork`ing at this point?

No
> 
> What flavor of Linux are you running?

It is Juniper's Junos OS Evolved a.k.a "EVO"

> I'm not sure this is true. If there's a good explanation for how the fd could be corrupted, then it would make more sense to continue on with server operations.

At this point, we are not too sure of the reason of "Bad file descriptor"
While I agree that we need to identify the reason which lands up in this scenario. Should it be handled in such a way that the server does not give up listening
"Bad file descriptor" is one of the failure and there could be many other failure scenarios such as {EBADF, EFAULT, EINVAL, ENOBUFS, ENOTCONN, ENOTSOCK}
In any of the scenario, if the server stops listening completely, then it could be a problem (unless the reason is unrecoverable for example: ENOBUFS)

**Comment by drfloob** [comment]
@ssachinbharadwaj I've made the change, it should be in the 1.62 release. I still half suspect you're facing either (A) some kind of unstable system, or (B) an odd implementation of getpeername. But hopefully this helps.

**Comment by ssachinbharadwaj** [comment]
@drfloob
If A (and/or) B exists, we will come to know in some other place in some other form. And if the real root cause is investigated, I will be happy to share my learning here again.

Thank you very much for this fix! Yes this helps.

**Comment by ssachinbharadwaj** [comment]
@drfloob @yashykt We found the real root cause for EBADF. There was a bug in the server application (outside of grpc stack) in some other thread which was doing **double close** of the same ***fd*** in a very rare scenario.
If the grpc thread gets the same fd, it will be mistakenly closed by some other thread and it causes this problem for grpc thread.

**The sequence is something like this:**
Thread 1: open(fd)
Thread 1: use fd
Thread 1: close fd
Thread 2 (grpc thread): open fd <<<<< gets same fd because it is released above
Thread 1: close fd <<< BUG! (No EBADF reported here because it is opened by grpc thread)
Thread 2 (geetpeername): EBADF because it is closed by thread 1

Thank you very much for your support and handling this case as well in 1.62

**Comment by drfloob** [comment]
Thanks for reporting back @ssachinbharadwaj. Glad to have my systems understanding validated.

I still think this is a decent argument for having the server stop entirely (but loudly). If your application caused UB by invalidating assumptions gRPC holds about fd ownership, you probably don't want to trust your application at that point. For now, the logs will show `ERROR: Failed getpeername: <OS error info>. Dropping the connection, and continuing to listen on <ip>:<port>.`, and the server keeps going.

**Comment by ssachinbharadwaj** [comment]
> I still think this is a decent argument for having the server stop entirely (but loudly). 

@drfloob Agree. If your change https://github.com/grpc/grpc/pull/35823 is very safe, then you can keep it. But I don't mind if you revert https://github.com/grpc/grpc/pull/35823 and just report loudly.
