### ISSUE TITLE
Request processing stall after Error parsing ':method' metadata is logged

### ISSUE THREAD

**Issue by marcbak** [grpc/grpc#35170]
### What version of gRPC and what language are you using?
I'm using grpc v1.59.2.

### What operating system (Linux, Windows,...) and version?
Ubuntu 23.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++12

### What did you do?
I'm using grpc with envoy as a proxy for grpc-web requests. It seems that envoy has something called pseudoheaders (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#method) which forward the METHOD used in a weird format `:method`.
  When providing a method different than POST, such as DELETE or OPTIONS, I can see the following error in grpc logs:
`E1130 11:13:01.387222484     105 hpack_parser.cc:999]                  Error parsing ':method' metadata: invalid value
` which in turn completely stalls request processing.
I've tested it with grpc v1.54.0 and even though the same error is reported, it does not result in a stall, next requests are still processed. 

### What did you expect to see?
Error being logged, but the request handling still continuing.

### What did you see instead?
Request processing being stalled.

I'm not entirely sure if this should go to Core or C++ bugs, but the path to hpack_parser includes `core` in the name, so I went with Core.
Please let me know if you have any other questions, I'll be happy to provide more info as needed.

Thank you!

**Comment by VineethChinthirla** [comment]
@marcbak I am facing an similar issue where I have istio with envoy proxy stalling and not processing any requests. Was there any solution for this issue? currently it works for me after an rolling restart of pods
