### ISSUE TITLE
grpc c++ time sync thread is crashing the process on no memory error

### ISSUE THREAD

**Issue by tedjenneycsi** [grpc/grpc#35198]
### What version of gRPC and what language are you using?
grpc 1.58.1 in C++

### What operating system (Linux, Windows,...) and version?
Linux Rocky 9.2

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 13.2.0

### What did you do?
In our server application, we are using grpc and tcmalloc. In low memory situations (which are not easy to reproduce), the `grpcpp_sync_ser` thread is hitting an out of memory from `absl::lts_20230802:time_internal::cctz::TimeZoneInfo::ExtendTransitions()`. See the stack trace in the attached image.

![image](https://github.com/grpc/grpc/assets/152536119/187353fa-0f60-42ef-baf2-50f3aac3ff2a)

The problem is that when we run out of memory, the application is being terminated.

We have implemented our own system for avoiding linux's out of memory killer. When tcmalloc reports an out of memory, instead of terminating the application, we catch a std::bad_alloc exception, log the error, and return an actionable message to the user. We expect memory to be freed up as the system is used more.

If grpc is expecting to have the application crash when out of memory errors occur, we have a long term approach to solving this problem. However, if grpc is expecting to recover from an out of memory error, then please let us know how we can help you fix this issue.

### What did you expect to see?
We want to be able to recover from this out of memory condition. We were expecting to see grpc pre-allocate the resources it needs so that out of memory errors would not occur. 

### What did you see instead?
The application is crashing due to a call to std::terminate(). 
See the stack trace in the image attached to this ticket.

**Comment by tedjenneycsi** [comment]
Hi, is there any update on this ticket? Is there other info you need from me for your investigation? Thank you.

**Comment by markdroth** [comment]
We do not expect gRPC to continue working in the face of failed memory allocations.  An OOM there is the best we can do.

The one mechanism we have that might be useful to you is [ResourceQuota](https://github.com/grpc/grpc/blob/1a086609d7083b2e6413b397fc3239adea3d66f2/include/grpcpp/resource_quota.h#L34), which you can use to cap the memory used by gRPC.  However, note we don't do *all* of our memory allocation through ResourceQuota, so it's not a complete upper bound for everything.  But it does handle most of the connection and RPC memory allocation, which in most servers is the majority of gRPC's memory usage.

I hope this information is helpful.

**Comment by tedjenneycsi** [comment]
Thank you for your response. We have been looking at possibly using ResourceQuota to solve this.
