### ISSUE TITLE
Issue generating proto -> C# binaries when Grpc.Tools is included as an implicit dependency

### ISSUE THREAD

**Issue by kboniadi** [grpc/grpc#35237]
### What version of gRPC and what language are you using?
2.59.0/C#

### What operating system (Linux, Windows,...) and version?
Mac 13.6.2 

### What runtime / compiler are you using (e.g. python version or version of gcc)
.Net 6.0

### What did you do?
- I've installed a nuget which has Grpc.Tools as a dependency.
- Build project as normal following https://learn.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0

### What did you expect to see?
- Proto -> C# binaries created in obj/ folder

### What did you see instead?
- nothing. compiler is not running or generating binaries
- It would seem that Grpc.Tools msbuild scripts are in the build dir and NOT also in buildTransitive (See image below)
- Adding to **buildTransitive/** should solve this issue?

### Anything else we should know about your project / environment?
![image](https://github.com/grpc/grpc/assets/67992622/91dd88c5-53ce-4caf-862d-009df3d9368f)

![image](https://github.com/grpc/grpc/assets/67992622/5e15f34d-1a9c-410a-b543-153589f90143)

**Comment by kboniadi** [comment]
hi @tonydnewell. the NuGet package that has Grpc.Tools installed is a library application that I maintain as well. I use this library application to centralize core features/tools so that I can easily carry them to other application by just installing the NuGet of the library application. 

I totally get what you are saying about Grpc.Tools being a build time requirement only, I just don't want the versions of the runtime interpreter Grpc.AspNetCore--which is in the library application--and Grpc.Tools to diverge.

**Comment by kboniadi** [comment]
Right now I'm including the runtime dependencies--Grpc.AspNetCore--in the library app and then installing Gprc.Tools directly and  the library app's directly into what ever application needs Gprc. I'm just worried about diverging versions. 

I have Grpc.AspNetCore version set to [2.*], so I'm assuming as long as Grpc.Tools is also kept at 2.* things should be backwards compatible? Is this true?

**Comment by tonydnewell** [comment]
I can't give any guarantees but I can't think of a situation where Grpc.Tools would break compatibility. It is really just a wrapper for the protocol buffers compiler which is already a separate independent project, and is stable and mature.

I'll investigate whether we can add "buildTransitive" easily and without breaking anything. No promises when this can be done.

**Comment by tonydnewell** [comment]
Investigating further I think that it is best to not change the behaviour of the existing `Grpc.Tools` package.

1. It is more than just adding the `.props` and `.target` files to a `buildTransitive` folder. The assembly DLLs and the well-known protobuf types would also need to be duplicated, or the logic of the existing targets would need refactoring.
2. It will be difficult for applications using any meta nuget package that is including `Grpc.Tools` to exclude just the private assets that the `Grpc.Tools` provides while including others from other dependent packages provided by this meta nuget package.

**Comment by kboniadi** [comment]
@tonydnewell Ok. Unfortunate, but thanks for taking the time to investigate this.
