### ISSUE TITLE
Narrowing conversion warning in proto_buffer_reader.h

### ISSUE THREAD

**Issue by mmjkelso** [grpc/grpc#35268]
### What version of gRPC and what language are you using?
1.60.0

### What operating system (Linux, Windows,...) and version?
Windows 11 Pro 22H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 17.8.0 (build tools version 14.37.32822)

### What did you do?
Compile protobuf generated by gRPC C++ plugin , which eventually includes

`include\grpcpp\support\proto_buffer_reader.h`

### What did you expect to see?
Warning-free compilation

### What did you see instead?
Several warnings (for each file that includes protobuf generated .cc files) like:

`proto_buffer_reader.h(155,16): warning C4244: '-=': conversion from 'int64_t' to 'int', possible loss of data`

### Anything else we should know about your project / environment?

Lines 153 and 166 of `proto_buffer_reader.h` have respectively

`count -= take;`

and

`count -= slice_length;`

`count` is an `int` argument to `ReadCord()`, whereas `take` and `slice_length` are local `uint64_t` variables, which I guess is generating the warning ?

static casting `take` and `slice_length` to `int` fixes the warnings. But perhaps `ReadCord()` should take `count` as `uint64_t`, or the local vars should be `int` ?

**Comment by yashykt** [comment]
@veblush to check if sizes can be 4G+

**Comment by yashykt** [comment]
@veblush checked that sizes cannot be larger than 4G, so we should be fine to do an explicit cast here

**Comment by veblush** [comment]
I think we can add some casting to deal with this warning and we cannot change the prototype as it's part of protobuf public API.
