### ISSUE TITLE
Bad metadata value given PHP extension

### ISSUE THREAD

**Issue by dev-comrade** [grpc/grpc#35266]
### What version of gRPC and what language are you using?
grpc php ext 1.57
php 8.2.13
### What operating system (Linux, Windows,...) and version?
Linux x64, Linux arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)
protoc compiler 1.60

### What did you do?
When i call grpc server with metadata array which contains a references inside it is makes a error "Bad metadata value given". When i replace all references to direct values everything works fine.

References are produced after every call array_walk_recursive. For example i have config from file and configuration from consul, when i merge configs with array_walk_recursive all values are made references.

This method return false when array contains a references:
https://github.com/grpc/grpc/blob/v1.57.0/src/php/ext/grpc/call.c#L114

I think it is main reason.

How to reproduce: https://github.com/dev-comrade/grpc-php-example

**Comment by alto-php** [comment]
I have verified that I can reproduce it, will take a look
