### ISSUE TITLE
Please update PHP grpc/grpc to version 1.60.0

### ISSUE THREAD

**Issue by ScorNinja** [grpc/grpc#35324]
### What version of gRPC and what language are you using?
PHP 8.2
gRPC 1.60

### What did you do?
Composer 
require: {
    "grpc/grpc" : "1.60.0"
}

### What did you see instead?
Doesn't exist (last version 1.57.0)

### Anything else we should know about your project / environment?
Attempting to use Google Firestore, but it is throwing an error in PHP v8.2 about Abstract Calls.

**Comment by calsmith** [comment]
Google has deprecated PHP 7.4 for Google App Engine but hasn't updated their pre-installed grpc extension to support PHP 8.2. I believe this is the root issue. I'm not sure if this forum can fix the issue or if you will need to contact Google Cloud directly.

Using phpinfo() we can see that App Engine uses grpc.so version 1.43 which isn't compatible with PHP 8.2 throwing many deprecation warnings like "Deprecated: Creation of dynamic property Grpc\Call::$channel is deprecated in /workspace/vendor/grpc/grpc/src/lib/AbstractCall.php on line 60". Same issue with protobuf.so.

One workaround is simply remove GRPC and protobuf from your php.ini, but this may result in slower performance.

Related issue: https://github.com/grpc/grpc/issues/33066

**Comment by ScorNinja** [comment]
The issue is I am trying to use Firebase Firestore which has this dependency.

**Comment by nocive** [comment]
The grpc/grpc userland code (composer pkg) does not strictly follow all the versions that the php grpc/grpc extension does.
You want to install the php extension via pecl (for which you have version 1.60) and the composer package to its latest version. The versions of both **do not** need to match.
