### ISSUE TITLE
The current architecture supports okhttps and netty. I would like to know how to customize channels, such as channels implemented based on mqtt or DDS

### ISSUE THREAD

**Issue by SJLBenjamin** [grpc/grpc#35387]
The current architecture supports okhttps and netty. I would like to know how to customize channels, such as channels implemented based on mqtt or DDS

**Comment by eugeneo** [comment]
This repository is for reporting issues in gRPC Core/C++. Please use https://groups.google.com/g/grpc-io to ask questions. If you found an issue specific to gRPC Java, please report it to https://github.com/grpc/grpc-java
