### ISSUE TITLE
X509_NAME_oneline is not a stable format for CRL lookup

### ISSUE THREAD

**Issue by davidben** [grpc/grpc#35383]
Looking over the CRL provider logic added in https://github.com/grpc/grpc/pull/33786 (CC @gtcooke94), I've noticed a ton of problems. It probably needs to redesigned anew, with subject matter experts as reviewers (it implements all the various OpenSSL callbacks incorrectly), but I'm filing this issue standalone to capture the one of the more egregious problems, since it leaked into the public API:

`GetCrlFromProvider` uses `X509_NAME_oneline` to pass the issuer up to the caller. X.509 names are discussed in RFC 5280, in https://www.rfc-editor.org/rfc/rfc5280.html#section-4.1.2.4. They are fairly complex structures. The various `C=US/...` strings you've seen are merely ad-hoc, ill-defined "human-readable" outputs for debugging and logging.

As these human-readable strings are ad-hoc and ill-defined, they are *not stable*. They do not capture all aspects of the name, and may even change as we fix bugs in them. This is especially true as this is all ad-hoc string manipulation logic written a long time ago in OpenSSL. As [documented](https://boringssl.googlesource.com/boringssl/+/b6e0eba6e62333652290514e51b75b966b27b27c/include/openssl/x509.h#2383), BoringSSL does not support projects that use them programmatically like this. The one gRPC chose, `X509_NAME_oneline` is [particularly bad](https://boringssl.googlesource.com/boringssl/+/b6e0eba6e62333652290514e51b75b966b27b27c/crypto/x509/x509_obj.c). (The `gs_doit` thing is totally nonsense, use of OID string names inherently makes the output unstable, it's trivially injectable, doesn't handle ASCII-incompatible string encodings correctl, etc.) This is [also documented](https://boringssl.googlesource.com/boringssl/+/b6e0eba6e62333652290514e51b75b966b27b27c/include/openssl/x509.h#2582).

If you need to pass an `X509_NAME` up through a public API, you must use a stable, well-defined format, e.g. the DER serialization.

This problem is made worse by gRPC's incorrect use of the `check_crl` callback, which bypasses any CRL/issuer consistency checks. Contrary to the comment, the provider is incapable of performing those checks correctly because you all have passed an unusable representation of the issuer name.

**Comment by davidben** [comment]
Poking around some more and at the original motivation, the right fix for this is probably to scrap the CrlProvider interface entirely and replace it with one that just returns a list of CRLs.

Then, rather than messing with the callbacks, you could simply have called `X509_STORE_CTX_set0_crls` on a per-verification basis. Since that happens at the `X509_STORE_CTX` level, rather than `X509_STORE`, there's no caching or anything going on. (See #35369 for the callback you all should have used to be able to change the `X509_STORE_CTX` parameters.)

@gtcooke94 after the holidays, let's chat about the motivations behind the design.

**Comment by gtcooke94** [comment]
Fixed via https://github.com/grpc/grpc/pull/35641
