### ISSUE TITLE
client_channel connectivity state hangs for a period when resolver result changes.

### ISSUE THREAD

**Issue by haorenfsa** [grpc/grpc#35393]
### What version of gRPC and what language are you using?
v1.58.0, python

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Our service structure look like this:
The client use a hostname which resolves to a IP of Nginx. Nginx proxies the request to backend server.
<img width="156" alt="image" src="https://github.com/grpc/grpc/assets/15938850/3772c28e-c3c2-42c5-b45c-efe9ff936001">

1. Set debug log environment variables to output trace log:
```
export GRPC_TRACE=handshaker,connectivity_state,client_channel,call_error,subchannel
export GRPC_VERBOSITY=debug
```

2. Then use python interactive terminal to create python `client instance`, connect and send a gRPC request to hostname. It should succeed.

3. Don't stop your python terminal. wait for about 2 minutes. by default, nginx server sends a HTTP2 GOAWAY FRAME to the idle client. Which causes
the connectivity state of `client_transport` to change: `READY -> TRANSIENT_FAILURE`, then `TRANSIENT_FAILURE->SHUTDOWN`
and the connectivity state of `client_channel` to change `READY -> IDLE`

4. Then start nginx in another host,  change the dns record to the new nginx's host.

Wait for the DNS record TTL to end(until the `dig` result is always the new one)

5. Use your python terminal to send a new request through previously created `client instance`.

6. Use `netstat -netp |grep python` to check your python client connection state.

7. At first the client should try previous IP. 
The connectivity state of `client_channel` should change first from `IDLE` -> `CONNECTING`, then `CONNECTING` -> `TRANSIENT_FAILURE`
Then after reconnect backoff timeout, it should use the new IP to connect.

### What did you expect to see?
Before connect to the new IP, connectivity state should change to `CONNECTING` first.
After connected to the new IP. the client should be able receive response from server.

### What did you see instead?
The trace log shows the `client_channel` connectivity state is always `TRANSIENT_FAILURE`. 
The connectivity state of `client_channel` tries to change `TRANSIENT_FAILURE`->`IDLE` and `IDLE` -> `CONNECTING`, but ConnectivityStateTracker failed to track the actual state changes. The state stucks at `TRANSIENT_FAILURE`.

After connected to the new IP, all client request still failed. 
After about 2 minutes, the connectivity state recovered from  `TRANSIENT_FAILURE` -> `READY` directly.

Below are all the logs I got.
[grpc.log](https://github.com/grpc/grpc/files/13776511/pymilvus-grpc-http2.log)

**Comment by haorenfsa** [comment]
@yijiem please help take a look, thank you very much!

**Comment by markdroth** [comment]
@XuanWang-Amos, if you run an interactive python terminal like this, is there going to be a background thread doing polling for C-core, or is it starving the client of polling?

**Comment by XuanWang-Amos** [comment]
Assume this is not Async, Python client thread will be blocked waiting for next event from C-core.

**Comment by markdroth** [comment]
I'm not asking about whether the python API is async.  I'm asking whether there is some other thread polling a CQ or whether the python interpretter sitting at a prompt is going to starve the client of polling.

**Comment by XuanWang-Amos** [comment]
We do have a daemon thread polling for connectivity state:https://github.com/grpc/grpc/blob/a100e90f9760a115722cec072d518bef080971a9/src/python/grpcio/grpc/_channel.py#L1901-L1908

Also want to note that it's possible to skip some intermediate state, but 2 minutes sounds a long time.

**Comment by haorenfsa** [comment]
By the way, there's an interesting fact might help: We use TLS, but when client start using new IP for connection, after the tcp connection established, it won't lanch TLS handshake. No `client hello` is sent. It just waits and reports error of handshake timeout.

**Comment by haorenfsa** [comment]
> We do have a daemon thread polling for connectivity state:

@XuanWang-Amos It seems the `the daemon polling thread` is not started by default? It seems it will only be started when user calls the `channel.subscribe` to register a callback when connectivity changes?

**Comment by XuanWang-Amos** [comment]
Yeah if you're not calling `channel.subscribe` then we won't start the new thread.

We checked the log again, looks like we did resolve to the new IP address, but then the handshake failed with `Handshake timed out` error, it would be helpful if you can also provide some logs from the 2nd Nginx server. 


```
I1227 06:13:17.381883608   20404 client_channel.cc:1248]               chand=0x55b3e7d23070: got resolver result
I1227 06:13:17.381905693   20404 client_channel.cc:1310]               chand=0x55b3e7d23070: resolver returned no service config. Using default service config for channel.
I1227 06:13:17.381919588   20404 client_channel.cc:1347]               chand=0x55b3e7d23070: service config not changed
I1227 06:13:17.381928561   20404 client_channel.cc:1426]               chand=0x55b3e7d23070: Updating child policy 0x7fa2d0014d50
I1227 06:13:17.381938134   20404 child_policy_handler.cc:246]          [child_policy_handler 0x7fa2d0014d50] updating child policy 0x7fa2d0002840
I1227 06:13:17.382020267   20404 subchannel.cc:512]                    subchannel 0x7fa2d0119830 {address=ipv4:10.5.66.176:443, args={grpc.client_channel_factory=0x55b3e7a26e90, grpc.default_authority=in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x55b3e7bb6160, grpc.internal.event_engine=0x7fa300015ed0, grpc.internal.security_connector=0x7fa2d012fef0, grpc.internal.subchannel_pool=0x55b3e7c49bd0, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.min_reconnect_backoff_ms=5000, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x55b3e7c23a70, grpc.server_uri=dns:///in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443}}: throttling keepalive time to 55000
I1227 06:13:17.382030629   20404 client_channel.cc:499]                chand=0x55b3e7d23070: creating subchannel wrapper 0x55b3e78235c0 for subchannel 0x7fa2d0119830
I1227 06:13:17.382037561   20404 client_channel.cc:624]                chand=0x55b3e7d23070: connectivity change for subchannel wrapper 0x55b3e78235c0 subchannel 0x7fa2d0119830; hopping into work_serializer
I1227 06:13:17.382053081   20404 client_channel.cc:648]                chand=0x55b3e7d23070: processing connectivity change in work serializer for subchannel wrapper 0x55b3e78235c0 subchannel 0x7fa2d0119830 watcher=0x7fa300016100 state=IDLE status=OK
I1227 06:13:17.382072570   20404 handshaker.cc:75]                     handshake_manager 0x7fa3000011f0: adding handshaker tcp_connect [0x7fa2d0127350] at index 0
I1227 06:13:17.382081726   20404 handshaker.cc:75]                     handshake_manager 0x7fa3000011f0: adding handshaker http_connect [0x7fa300004030] at index 1
I1227 06:13:17.382156844   20404 handshaker.cc:75]                     handshake_manager 0x7fa3000011f0: adding handshaker security [0x7fa2d0130710] at index 2
I1227 06:13:17.382177579   20404 handshaker.cc:100]                    handshake_manager 0x7fa3000011f0: error=OK shutdown=0 index=0, args={endpoint=(nil), args={grpc.client_channel_factory=0x55b3e7a26e90, grpc.default_authority=in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x55b3e7bb6160, grpc.internal.event_engine=0x7fa300015ed0, grpc.internal.security_connector=0x7fa2d012fef0, grpc.internal.subchannel_pool=0x55b3e7c49bd0, grpc.internal.tcp_handshaker_bind_endpoint_to_pollset=1, grpc.internal.tcp_handshaker_resolved_address=ipv4:10.5.66.176:443, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.min_reconnect_backoff_ms=5000, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x55b3e7c23a70, grpc.server_uri=dns:///in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443}, read_buffer=0x7fa300001050 (length=0), exit_early=0}
I1227 06:13:17.382189579   20404 handshaker.cc:146]                    handshake_manager 0x7fa3000011f0: calling handshaker tcp_connect [0x7fa2d0127350] at index 0
I1227 06:13:17.382340062   20404 client_channel.cc:624]                chand=0x55b3e7d23070: connectivity change for subchannel wrapper 0x55b3e78235c0 subchannel 0x7fa2d0119830; hopping into work_serializer
I1227 06:13:17.382356819   20404 client_channel.cc:522]                chand=0x55b3e7d23070: destroying subchannel wrapper 0x55b3e79b9540 for subchannel 0x55b3e7d2e530
I1227 06:13:17.382375990   20404 client_channel.cc:648]                chand=0x55b3e7d23070: processing connectivity change in work serializer for subchannel wrapper 0x55b3e78235c0 subchannel 0x7fa2d0119830 watcher=0x7fa300016100 state=CONNECTING status=OK
I1227 06:13:17.382402920   20404 handshaker.cc:100]                    handshake_manager 0x55b3e79ab780: error=UNKNOWN:tcp handshaker shutdown {created_time:"2023-12-27T06:13:17.38237152+00:00"} shutdown=1 index=1, args={endpoint=(nil), args={}, read_buffer=(nil) (length=0), exit_early=0}
I1227 06:13:17.382416349   20404 handshaker.cc:132]                    handshake_manager 0x55b3e79ab780: handshaking complete -- scheduling on_handshake_done with error=UNKNOWN:tcp handshaker shutdown {created_time:"2023-12-27T06:13:17.38237152+00:00"}
I1227 06:13:20.282889129   20402 handshaker.cc:100]                    handshake_manager 0x7fa3000011f0: error=OK shutdown=0 index=1, args={endpoint=0x7fa2d01286d0, args={grpc.client_channel_factory=0x55b3e7a26e90, grpc.default_authority=in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x55b3e7bb6160, grpc.internal.event_engine=0x7fa300015ed0, grpc.internal.security_connector=0x7fa2d012fef0, grpc.internal.subchannel_pool=0x55b3e7c49bd0, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.min_reconnect_backoff_ms=5000, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x55b3e7c23a70, grpc.server_uri=dns:///in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443}, read_buffer=0x7fa300001050 (length=0), exit_early=0}
I1227 06:13:20.282918232   20402 handshaker.cc:146]                    handshake_manager 0x7fa3000011f0: calling handshaker http_connect [0x7fa300004030] at index 1
I1227 06:13:20.282929533   20402 handshaker.cc:100]                    handshake_manager 0x7fa3000011f0: error=OK shutdown=0 index=2, args={endpoint=0x7fa2d01286d0, args={grpc.client_channel_factory=0x55b3e7a26e90, grpc.default_authority=in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x55b3e7bb6160, grpc.internal.event_engine=0x7fa300015ed0, grpc.internal.security_connector=0x7fa2d012fef0, grpc.internal.subchannel_pool=0x55b3e7c49bd0, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.min_reconnect_backoff_ms=5000, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x55b3e7c23a70, grpc.server_uri=dns:///in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443}, read_buffer=0x7fa300001050 (length=0), exit_early=0}
I1227 06:13:20.282936944   20402 handshaker.cc:146]                    handshake_manager 0x7fa3000011f0: calling handshaker security [0x7fa2d0130710] at index 2

D1227 06:13:22.383410837   20411 security_handshaker.cc:208]           Security handshake failed: UNKNOWN:Handshake read failed {created_time:"2023-12-27T06:13:22.383367605+00:00", children:[UNKNOWN:FD Shutdown {created_time:"2023-12-27T06:13:22.383297727+00:00", children:[UNKNOWN:Handshake timed out {created_time:"2023-12-27T06:13:22.383285445+00:00"}]}]}
I1227 06:13:22.383452807   20411 handshaker.cc:100]                    handshake_manager 0x7fa3000011f0: error=UNKNOWN:Handshake read failed {created_time:"2023-12-27T06:13:22.383367605+00:00", children:[UNKNOWN:FD Shutdown {created_time:"2023-12-27T06:13:22.383297727+00:00", children:[UNKNOWN:Handshake timed out {created_time:"2023-12-27T06:13:22.383285445+00:00"}]}]} shutdown=1 index=3, args={endpoint=(nil), args={}, read_buffer=(nil) (length=0), exit_early=0}
I1227 06:13:22.383475866   20411 handshaker.cc:132]                    handshake_manager 0x7fa3000011f0: handshaking complete -- scheduling on_handshake_done with error=UNKNOWN:Handshake read failed {created_time:"2023-12-27T06:13:22.383367605+00:00", children:[UNKNOWN:FD Shutdown {created_time:"2023-12-27T06:13:22.383297727+00:00", children:[UNKNOWN:Handshake timed out {created_time:"2023-12-27T06:13:22.383285445+00:00"}]}]}
I1227 06:13:22.383589856   20411 subchannel.cc:711]                    subchannel 0x7fa2d0119830 {address=ipv4:10.5.66.176:443, args={grpc.client_channel_factory=0x55b3e7a26e90, grpc.default_authority=in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x55b3e7bb6160, grpc.internal.event_engine=0x7fa300015ed0, grpc.internal.security_connector=0x7fa2d012fef0, grpc.internal.subchannel_pool=0x55b3e7c49bd0, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.min_reconnect_backoff_ms=5000, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x55b3e7c23a70, grpc.server_uri=dns:///in01-shaoyue-test.az-westus3.vectordb-uat3.zillizcloud.com:443}}: connect failed (UNKNOWN:Handshake read failed {created_time:"2023-12-27T06:13:22.383367605+00:00", children:[UNKNOWN:FD Shutdown {created_time:"2023-12-27T06:13:22.383297727+00:00", children:[UNKNOWN:Handshake timed out 
```

**Comment by haorenfsa** [comment]
@XuanWang-Amos I didn't open the debug log for nginx. I'll reproduce it again.

**Comment by haorenfsa** [comment]
@XuanWang-Amos When I was reproducing it again I noticed that I used to the `grpc.min_reconnect_backoff_ms` from its default `20000` to `10000` to shorten recovery time.

This time I didn't set `grpc.min_reconnect_backoff_ms`, it looks much better, it took 38s to recover. better than last time, but still much longer than expected. Nginx's log seems not helpful, but I captured all traffics with tcpdump.

[timeout20s-cli.log](https://github.com/grpc/grpc/files/13827421/timeout20s-cli.log)
[timeout20s-grpc-client.pcap.tar.gz](https://github.com/grpc/grpc/files/13827426/timeout20s-grpc-client.pcap.tar.gz)

Let me describe this in detail using the timeline of timeout20s-grpc-client.pcap:
frame 0 is at about `D0104 06:34:12.003721114`

1. Frame 0-23: Client TLS handshake with old nginx `10.5.65.71:443`
<img width="1625" alt="image" src="https://github.com/grpc/grpc/assets/15938850/004f7535-af63-460f-9e1f-a86556a93700">
2. Frame 24-31: Client sends test grpc call, and receive response immediately  from sever.
<img width="1507" alt="image" src="https://github.com/grpc/grpc/assets/15938850/812c5c33-87ad-4496-8824-9517a1dc794c">

3. Frame 32-39: old nginx sends GOAWAY to client, connection is closed.
<img width="1522" alt="image" src="https://github.com/grpc/grpc/assets/15938850/1a0ac4fe-6004-480a-8da8-4c03bba93dbe">

4. Frame 40-47: client start another grpc call, the client_channel first trying old IP with a `20 seconds min backoff timeout`.
<img width="1615" alt="image" src="https://github.com/grpc/grpc/assets/15938850/9eabb6f9-6e34-4e76-95ed-108319196d07">

5. Frame 48-57: Client start trying new nginx `10.5.66.156:443`, establish a tcp connection and start cipher exchanging.
The`client hello` is sent `3.5 seconds` after tcp handshake finished. Which is very strange, because last time it was sent immediately.
<img width="1576" alt="image" src="https://github.com/grpc/grpc/assets/15938850/0ffb5884-cec3-44b8-941b-00729368dba4">

6.Frame 58-67: **Note** frame 58 `Change Cipher Spec` is also `5 seconds` later after client side received `server hello`. This is expected to happen immediately after `server hello` is received. Afterwards TLS handshake is finished successfully.
The `TCP transmission frame` shows the old socket for old nginx is still trying to reach it.
<img width="1596" alt="image" src="https://github.com/grpc/grpc/assets/15938850/f699569b-594c-4385-ba75-bbc98988c29c">


7.Frame 68-end: another `5 seconds` later the TLS handshake finished, the client channel is established. another `2 seconds` later the request is sent, and response is received.
<img width="1378" alt="image" src="https://github.com/grpc/grpc/assets/15938850/c3721c58-19ce-45e9-a0aa-03b016aaf443">

**Comment by gnossen** [comment]
@haorenfsa Thank you for the detailed timeline! I think we understand the issue quite a bit better now. It has to do with delays while establishing the second connection.

@yashykt Can you help delegate this to a C++ team member who can investigate?

**Comment by markdroth** [comment]
I just want to point out that the fact that we're seeing 5-second delays here reinforces my earlier guess that this is polling starvation.  If the application is not polling the CQ, then it will fall back on the client channel backup poller, which runs every 5 seconds by default.

You can try confirming this by running with the env var `GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS=1000`.  If that results in the 5-second delays getting replaced with 1-second delays, then that's pretty clear confirmation that there's a polling problem here.

**Comment by haorenfsa** [comment]
@makdharma Good to hear that! I'll test it later

**Comment by haorenfsa** [comment]
Haven’t got time to test it yet. How cloud I reopen this?
