### ISSUE TITLE
Potential GRPC-go deadlock between exit and enterIdleMode

### ISSUE THREAD

**Issue by sganapathy1312** [grpc/grpc#35398]
### What version of gRPC and what language are you using?

- golang
- v1.59.0

### What operating system (Linux, Windows,...) and version?

- Linux amd64 

### What runtime / compiler are you using (e.g. python version or version of gcc)

- go1.21.0

### What did you do?

Our backend entrypoint talks to several intra k8s grpc endpoints. Most of our clients are configured using these opts

```
		opts := []grpc.DialOption{
			withRoundRobinLoadBalancer(),
			grpc.WithKeepaliveParams(keepalive.ClientParameters{
				Time:                15 * time.Second,
				Timeout:             15 * time.Second,
				PermitWithoutStream: true,
			}),
			grpc.WithUnaryInterceptor(grpc_middleware.ChainUnaryClient(
				// custom open-telemetry based tracing interceptor,
			)),
		}

// some extra opts for injecting bearer auth tokens from vault.
```

### What did you expect to see?

We expect to see all backend interactions occur as expected:

- Succeed if all inputs are correct and all downstreams are up.
- Honor the ctx timeouts we set and timeout requests if downstream is unreachable.

### What did you see instead?

We're seeing a potential deadlock scenario. 

- The idler is trying to enter the idle mode.
   - It acquires `clientconn.mutex` and among others tries to close the resolver. This results in calling `serializeCancel` and awaiting the `CallbackSerializer` to quit. However it cannot do so because one of the callbacks is trying to update the resolver state by calling `clientconn.UpdateResolverState` which tries to reacquire the mutex `clientconn.mutex`
- In the meanwhile, when the next business logic call comes, it results in a call to `exitIdleMode`. This call hangs.

#### Evidence

**idler trying to enter idle mode**

```
goroutine 147521115 [chan receive, 474 minutes]:
google.golang.org/grpc.(*ccResolverWrapper).close(0xc02de6ec00)
	/root/XXXX/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:136 +0x13b
google.golang.org/grpc.(*ClientConn).enterIdleMode(0xc0003e3400)
	/root/XXXX/vendor/google.golang.org/grpc/clientconn.go:429 +0xf1
google.golang.org/grpc.(*idler).EnterIdleMode(0x0?)
```

**CallbackSerializer stuck trying to acquire client.conn mutex**

```
goroutine 147336224 [sync.Mutex.Lock, 474 minutes]:
sync.runtime_SemacquireMutex(0xe?, 0x0?, 0xc003081c78?)
	/usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc0003e3730)
	/usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xc0507fc210?)
	/usr/local/go/src/sync/rwmutex.go:147 +0x31
google.golang.org/grpc.(*ClientConn).updateResolverState(0xc0003e3400, {{0xc0527f0800, 0x2, 0x2}, {0x0, 0x0, 0x0}, 0x0, 0x0}, {0x0, ...})
	/root/XXXX/vendor/google.golang.org/grpc/clientconn.go:829 +0xd0
google.golang.org/grpc.(*ccResolverWrapper).NewAddress.func1({0xc020871da0?, 0xc003081f40?})
```

**New GRPC requests are stuck**

```
sync.runtime_SemacquireMutex(0xc04ea4fb30?, 0x30?, 0x30?)
	/usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc0007bd9a0)
	/usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xc0120a3760?)
	/usr/local/go/src/sync/rwmutex.go:147 +0x31
google.golang.org/grpc/internal/idle.(*manager).exitIdleMode(0xc0007bd960)
	/root/XXXX/vendor/google.golang.org/grpc/internal/idle/idle.go:245 +0x3f
```

### Anything else we should know about your project / environment?

We use sercand/kuberesolver/v5 to resolve in-cluster services to pod-ips.

**Comment by sganapathy1312** [comment]
More data.

- We use service mesh for intra cluster communication.
- we verified that the downstream dependency pods didn't restart in the last 13 days.

**Comment by sganapathy1312** [comment]
Another data point, our servers don't have keep-alive or enforcement policy configured. Thus they will send GOAWAY in a bit

**Comment by sganapathy1312** [comment]
Found the goroutine who's holding the lock but i'm unable to explain it

```
oroutine 147521115 [chan receive, 474 minutes]:
google.golang.org/grpc.(*ccResolverWrapper).close(0xc02de6ec00)
	/root/XXXX/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:136 +0x13b
google.golang.org/grpc.(*ClientConn).enterIdleMode(0xc0003e3400)
	/root/XXXX/vendor/google.golang.org/grpc/clientconn.go:429 +0xf1
google.golang.org/grpc.(*idler).EnterIdleMode(0x0?)
	/root/XXXX/vendor/google.golang.org/grpc/clientconn.go:324 +0x13
google.golang.org/grpc/internal/idle.(*manager).tryEnterIdleMode(0xc0007bd960)
	/root/XXX/vendor/google.golang.org/grpc/internal/idle/idle.go:206 +0x97
google.golang.org/grpc/internal/idle.(*manager).handleIdleTimeout(0xc0007bd960)
	/root/XXXX/vendor/google.golang.org/grpc/internal/idle/idle.go:169 +0x54
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x2d
```

**Comment by sganapathy1312** [comment]
cc: @dfawley

**Comment by sganapathy1312** [comment]
We use telepresence for resolving in-cluster service endpoints.

**Comment by sganapathy1312** [comment]
We have atleast 10k go routines like 

```
goroutine 135203526 [select, 2496 minutes]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc0145fc940, {0x57fc018, 0xc04123fea0})
	/root/XXXX/vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go:83 +0x112
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 771
	/root/XXXXX/vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go:55 +0x129
```

**Comment by sganapathy1312** [comment]
Ok upon more triaging, the CallbackSerializer isn't exitting and this is preventing the resolver from closing and this keeps the mutex locked and prevents leaving the idle mode when a new call comes. Now i'm unsure why the CallbackSerializer isn't exitting despite the call to serializeCancel happening

**Comment by sganapathy1312** [comment]
Hmm the plot thickens. Pretty certain this is what is preventing the callbackserializer from exitting.

```
goroutine 147336224 [sync.Mutex.Lock, 474 minutes]:
sync.runtime_SemacquireMutex(0xe?, 0x0?, 0xc003081c78?)
	/usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc0003e3730)
	/usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xc0507fc210?)
	/usr/local/go/src/sync/rwmutex.go:147 +0x31
google.golang.org/grpc.(*ClientConn).updateResolverState(0xc0003e3400, {{0xc0527f0800, 0x2, 0x2}, {0x0, 0x0, 0x0}, 0x0, 0x0}, {0x0, ...})
	/root/XXXXX/vendor/google.golang.org/grpc/clientconn.go:829 +0xd0
google.golang.org/grpc.(*ccResolverWrapper).NewAddress.func1({0xc020871da0?, 0xc003081f40?})
	/root/XXXX/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:196 +0x193
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc020871da0, {0x57fc018, 0xc051a405f0})
	/root/XXXXX/vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go:104 +0x242
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 818
	/root/XXXX/vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go:55 +0x129
```

**Comment by sganapathy1312** [comment]
Summarized the description above with all the findings added as comments.

**Comment by IvanLaktyunkin** [comment]
Looks similar to https://github.com/grpc/grpc-go/issues/6783
and was fixed by https://github.com/grpc/grpc-go/pull/6804

**Comment by yashykt** [comment]
From the last comment, it might have been fixed but the correct repository for this issue should be github.com/grpc/grpc-go
