### ISSUE TITLE
[BUG] async grpc *** was never awaited

### ISSUE THREAD

**Issue by yfismine** [grpc/grpc#35406]
### Describe the bug

The example comes from the official example of grpc.
``` shell
git clone https://github.com/grpc/grpc.git
cd grpc/examples/python/helloworld
python setup.py build_ext
cd build/lib*
python  asyncio_server.py
python asyncio_client.py
```
![image](https://github.com/cython/cython/assets/53209596/810c9819-46b2-4daf-8e1e-b2e6d32a316c)
![image](https://github.com/cython/cython/assets/53209596/a7515afd-7b8a-4e5d-bcdc-43ef4cc2093f)

### Code to reproduce the behaviour:

```python
# setup.py
from distutils.core import setup
from Cython.Build import cythonize
setup(
    name="pyos",
    ext_modules=cythonize("./*.py"),
)

```
``` python
# async_server.py
import asyncio
from async_greeter_server import serve
asyncio.run(serve())
```
``` python
# async_client.py
from async_greeter_client import run
import asyncio
asyncio.run(run())
```

### OS

Linux

### Python version

3.8

### Cython version

3.0.7

**Comment by XuanWang-Amos** [comment]
Currently, we do not support Cython 3.0. However, adding support for Cython 3.0 is on our roadmap.

For anyone who's interested in Cython 3.0 support, please comment on this issue so that we can prioritize it accordingly.

**Comment by XuanWang-Amos** [comment]
Re-opening this issue to track Cython 3.0 support

**Comment by XuanWang-Amos** [comment]
Looks like we already have one tracing PR: https://github.com/grpc/grpc/issues/33918, we'll use that to track Cython 3.0 support.
