### ISSUE TITLE
h2_ssl_proxy_cancel_after_client_done_test is flaky

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#3545]
D0928 09:45:01.107459335  713621 test_config.c:92]           test slowdown: machine=1.000000 build=1.000000 total=1.000000
I0928 09:45:01.108120881  713621 cancel_after_client_done.c:56] test_cancel_after_accept_and_writes_closed/chttp2/simple_ssl_fullstack
D0928 09:45:01.220469663  713628 proxy.c:159]                ref 0x7f9a58c92430: on_p2s_recv_initial_metadata 1 -> 2
D0928 09:45:01.220510284  713628 proxy.c:159]                ref 0x7f9a58c92430: on_p2s_sent_initial_metadata 2 -> 3
D0928 09:45:01.220638768  713628 proxy.c:159]                ref 0x7f9a58c92430: on_c2p_recv_msg 3 -> 4
D0928 09:45:01.220668049  713628 proxy.c:159]                ref 0x7f9a58c92430: on_p2s_recv_msg 4 -> 5
D0928 09:45:01.220689421  713628 proxy.c:159]                ref 0x7f9a58c92430: on_p2s_status 5 -> 6
D0928 09:45:01.220707367  713628 proxy.c:159]                ref 0x7f9a58c92430: on_c2p_closed 6 -> 7
D0928 09:45:01.220743559  713628 proxy.c:145]                unref 0x7f9a58c92430: init 7 -> 6
D0928 09:45:01.220774938  713628 proxy.c:159]                ref 0x7f9a58c92430: on_p2s_sent_message 6 -> 7
D0928 09:45:01.220799862  713628 proxy.c:145]                unref 0x7f9a58c92430: on_c2p_recv_msg 7 -> 6
D0928 09:45:01.319931029  713628 proxy.c:145]                unref 0x7f9a58c92430: on_p2s_sent_initial_metadata 6 -> 5
D0928 09:45:01.319989376  713628 proxy.c:159]                ref 0x7f9a58c92430: on_c2p_recv_msg 5 -> 6
D0928 09:45:01.320026783  713628 proxy.c:145]                unref 0x7f9a58c92430: on_p2s_sent_message 6 -> 5
D0928 09:45:01.320054726  713628 proxy.c:159]                ref 0x7f9a58c92430: on_p2s_sent_close 5 -> 6
D0928 09:45:01.320117534  713628 proxy.c:145]                unref 0x7f9a58c92430: on_c2p_recv_msg 6 -> 5
D0928 09:45:01.320143561  713628 proxy.c:145]                unref 0x7f9a58c92430: on_p2s_sent_close 5 -> 4
D0928 09:45:01.320472685  713628 proxy.c:145]                unref 0x7f9a58c92430: on_p2s_recv_msg 4 -> 3
D0928 09:45:01.320509213  713628 proxy.c:159]                ref 0x7f9a58c92430: on_c2p_sent_initial_metadata 3 -> 4
D0928 09:45:01.320552862  713628 proxy.c:145]                unref 0x7f9a58c92430: on_p2s_recv_initial_metadata 4 -> 3
D0928 09:45:01.320579860  713628 proxy.c:145]                unref 0x7f9a58c92430: on_c2p_closed 3 -> 2
D0928 09:45:01.320605015  713628 proxy.c:159]                ref 0x7f9a58c92430: on_c2p_sent_status 2 -> 3
E0928 09:45:01.320641706  713628 call.c:1042]                attempt to send invalid metadata key: :status
E0928 09:45:01.320688461  713628 proxy.c:314]                assertion failed: err == GRPC_CALL_OK

**Comment by ctiller** [comment]
Not seen for some time: closing.
