### ISSUE TITLE
--grpc_out: protoc-gen-grpc: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by swatisharma12345** [grpc/grpc#35473]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

**Comment by swatisharma12345** [comment]
how to generate grpc.pb.h and grpc.pb.cc files.
I tried below command:
protoc -I=C:\UAproto\Source\Self\Auth\proto\ --grpc_out=C:\UAproto\Source\Self\Auth\Common\ --plugin=protoc-gen-grpc=`C:\UAproto\Source\OSS\grpc\tools\grpc_cpp_plugin.exe` C:\UAproto\Source\Self\Auth\proto\hUSAuth.proto

but getting error as:
--grpc_out: protoc-gen-grpc: The filename, directory name, or volume label syntax is incorrect.

Can anyone suggest how to proceed?

**Comment by eugeneo** [comment]
This repository is only for reporting bugs and suggesting improvements to gRPC. Please follow links in the first post to ask questions.
