### ISSUE TITLE
Could not get pem root certs.

### ISSUE THREAD

**Issue by exstreme** [grpc/grpc#35511]
### What version of gRPC and what language are you using?
PHP 8.3 x64
gRPC 1.60.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual studio 2019 (vs16)

### What did you do?
After updating from 1.55 version all queries using https://github.com/googleads/google-ads-php failed:

E0111 16:24:53.434000000 13788 ssl_utils.cc:600] load_file: UNKNOWN:Failed to load file {filename:"/usr/share/grpc/roots.pem", created_time:"2024-01-11T13:24:53.4097796+00:00", children:[UNKNOWN:No such file or directory {created_time:"2024-01-11T13:24:53.4096704+00:00", errno:2, os_error:"No such file or directory", syscall:"fopen"}]}
E0111 16:24:53.434000000 13788 ssl_credentials.cc:57] Could not get default pem root certs.
E0111 16:24:53.434000000 13788 ssl_credentials.cc:200] Handshaker factory creation failed. pem_root_certs cannot be nullptr
E0111 16:24:53.438000000 13788 ssl_credentials.cc:57] Could not get default pem root certs.
E0111 16:24:53.438000000 13788 ssl_credentials.cc:200] Handshaker factory creation failed. pem_root_certs cannot be nullptr
E0111 16:24:56.421000000 11436 ssl_credentials.cc:88] No root certs in config. Client-side security connector must have root certs.
E0111 16:24:56.421000000 11436 chttp2_connector.cc:266] Failed to create channel args during subchannel creation: INTERNAL: Failed to create secure subchannel for secure name 'googleads.googleapis.com:443'; Got args: {grpc.client_channel_factory=0x1de33780220, grpc.default_authority=googleads.googleapis.com:443, grpc.internal.channel_credentials=0x1de35421f90, grpc.internal.event_engine=0x1de354d3810, grpc.internal.subchannel_pool=0x1de354b86b0, grpc.internal.transport=(nil), grpc.max_metadata_size=16777216, grpc.max_receive_message_length=67108864, grpc.primary_user_agent=gcloud-php-legacy/21.1.0, grpc.resource_quota=0x1de354b83f0, grpc.server_uri=dns:///googleads.googleapis.com:443, grpc.service_config_disable_resolution=1}
E0111 16:24:56.422000000 11436 ssl_credentials.cc:88] No root certs in config. Client-side security connector must have root certs.

### What did you expect to see?
Working queries

### What did you see instead?
error loading cert

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by kkuehl** [comment]
See: I had to implement something similar: https://github.com/grpc/grpc/issues/25533

**Comment by exstreme** [comment]
1.61 the problem is still actual

**Comment by alto-php** [comment]
#34874 should fix this.
Can you try 1.63 or later versions?

**Comment by exstreme** [comment]
> #34874 should fix this. Can you try 1.63 or later versions?

1.64.1 works fine, thanks!
