### ISSUE TITLE
Unable to install grpcio-tools on Python 3.11.5 (MacOS)

### ISSUE THREAD

**Issue by vancromy** [grpc/grpc#35556]
I know there are a few closed issues in this repo on this topic and some help in the Troubleshooting.MD but none of those helped me resolve my issue or were similar to the issues I experienced during install.

### What version of gRPC and what language are you using?
1.48.2 - Python

### What operating system (Linux, Windows,...) and version?
MacOS 14.2.1 (23C71) - (Intel Mac)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python version 3.11.5 and gcc installed by Homebrew (v13.2.0)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

1) Install Python 3.11.5 and gcc 13.2.0 gcc with brew
2) Create a virtualenv with the python executable
3) Activate and run: pip install grpcio-tools==1.48.2

### What did you expect to see?
Installs grpcio-tools without any issues

### What did you see instead?
Build failure with what seems to be issues related to changes made in Cython in Python 3.11 (https://github.com/python/cpython/issues/89874) 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Full install log:
[install.log](https://github.com/grpc/grpc/files/13951955/install.log)

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Note: I am also experiencing the same build issues in a kubeflow pipeline I am running on google-cloud which uses the python:3.11 docker base image.

**Comment by XuanWang-Amos** [comment]
Hi, we don't support Python 3.11 for 1.48.2, the oldest version should be 1.49.0 for Python 3.11 support.
