### ISSUE TITLE
gRPC release Release v1.60.0 fails to build

### ISSUE THREAD

**Issue by Thundercleez** [grpc/grpc#35554]
### What version of gRPC and what language are you using?
v1.60.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 8.4.0
cmake 3.19.6

### What did you do?
Download and unzip Release v1.60.0. cd to unzipped directory
mkdir -p cmake/build
cd cmake/build
cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TEST=OFF -DCMAKE_TOOLCHAIN_FILE=~/grpc_ubuntu.cmake -DCMAKE_INSTALL_PREFIX=/usr/local ../..

The contents of the .cmake file is
set(CMAKE_C_COMPILER /usr/bin/gcc-8)
set(CMAKE_CXX_COMPILER /usr/bin/g++-8)

### What did you expect to see?
A successful compile of gRPC

### What did you see instead?
CMake Error at CMakeLists.txt:5417 (add_library):
    Target "grpcpp_channelz" links to target "absl::cleanup" but the target was
    not found. Perhaps a find_package() call is missing for an IMPROTED
    target, or an ALIAS target is missing?

and many more similar errors.

### Anything else we should know about your project / environment?
The build is being done in a docker container

**Comment by eugeneo** [comment]
The recommended way to build gRPC would be by cloning the repository at the tag. This way all the necessary dependencies would be downloaded as Git submodules. You may find the directions here: https://github.com/grpc/grpc/blob/master/BUILDING.md

It should be possible to install dependencies using your package manager but it may prove challenging to find a correct version of specific dependencies for a particular gRPC release as they often times do not provide a stable API...
