### ISSUE TITLE
gRPC does not warn when the message size is exceeded

### ISSUE THREAD

**Issue by emiliogq** [grpc/grpc#35574]
### What version of gRPC and what language are you using?

1.44 and C++

### What operating system (Linux, Windows,...) and version?

AlmaLinux 8

### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC 10

### What did you do?

1. Allocate a structure that is higher than the send size limit on gRPC server side
2. Return this allocated structure to the client gRPC
3. On the client gRPC call the gRPC server stub and check if the data is received (size or content)

### What did you expect to see?

I would like to see some warning in the output or log.

### What did you see instead?

Nothing. I just realized because I'm using logs and the data is received from client is empty

**Comment by markdroth** [comment]
In this case, the RPC should fail with an appropriate error message.  If you check the status of the call, it should provide a helpful error message.

If that's not happening, then please share code that demonstrates the problem.

**Comment by emiliogq** [comment]
Thanks for pointing out how to do it.

I've done such check:

```cpp
    ::grpc::Status status = grpcMethod(&context, empty_param, response);
    
    if (!status.ok()){
        LOG_ERROR_FMT(logger, "gRPC [%d] : %s ",status.error_code(), status.error_message());
    }
``` 

And I've got in the client:

```
2024-01-24 08:41:57.708 [16868] ERROR loggerRTDBClient (rtdb_grpc_client.cpp:275) gRPC [8] : @3a! 
2024-01-24 08:41:57.708 [16868] ERROR loggerRTDBClient (rtdb_grpc_client.cpp:275) gRPC [8] : @3a! 
```

Indeed, the error message does not help much :smile: 

This is tested on gRPC 1.44

> In this case, the RPC should fail with an appropriate error message. If you check the status of the call, it should provide a helpful error message.
> 
> If that's not happening, then please share code that demonstrates the problem.

**Comment by emiliogq** [comment]
Update, I tried to print the error_message() with cout and it worked, so there is no issue with the gRPC error_message()

> Thanks for pointing out how to do it.
> 
> I've done such check:
> 
> ```c++
>     ::grpc::Status status = grpcMethod(&context, empty_param, response);
>     
>     if (!status.ok()){
>         LOG_ERROR_FMT(logger, "gRPC [%d] : %s ",status.error_code(), status.error_message());
>     }
> ```
> 
> And I've got in the client:
> 
> ```
> 2024-01-24 08:41:57.708 [16868] ERROR loggerRTDBClient (rtdb_grpc_client.cpp:275) gRPC [8] : @3a! 
> 2024-01-24 08:41:57.708 [16868] ERROR loggerRTDBClient (rtdb_grpc_client.cpp:275) gRPC [8] : @3a! 
> ```
> 
> Indeed, the error message does not help much 😄
> 
> This is tested on gRPC 1.44
> 
> > In this case, the RPC should fail with an appropriate error message. If you check the status of the call, it should provide a helpful error message.
> > If that's not happening, then please share code that demonstrates the problem.

**Comment by markdroth** [comment]
`error_message()` returns `std::string`, not `char *`.  To print it via a `printf`-like interface, you need to use `error_message().c_str()`.
