### ISSUE TITLE
Introduce non-blocking polls before blocking annotations

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#3559]
It may be beneficial to introduce non-blocking (0 timeout) polls before the blocking annotations introduced by PR #3476 , in case the overhead of a real annotation system is quite high.

**Comment by vjpai** [comment]
Removing any assignment. If this is done, we should also have a sanity check to make sure that it actually happens.

**Comment by ncteisen** [comment]
Let's either try this or close this
