### ISSUE TITLE
qps testing: use affinity to guarantee # of cores used in Linux

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#3561]
Support the ability to set affinity to certain core sets before kicking off the test so that we can truly report qps/core rather than just the proxy of qps/threads that we currently use

**Comment by vjpai** [comment]
PR #4690 addresses this for Linux.
I will create a separate (lower-priority) issue to address this on other platforms.

**Comment by ctiller** [comment]
Fixed for Linux is enough for GA

**Comment by vjpai** [comment]
This is fixed for Linux and infeasible for Mac using current APIs. Should be feasible for Windows but we'll have to create a new issue for that if it's needed.
