### ISSUE TITLE
Objective-C Library broken from sync_posix.c

### ISSUE THREAD

**Issue by nkibler** [grpc/grpc#3564]
#3496 brought this up, but it broke in a different location from testing. This is happening during normal usage of the gRPC library. See attached screenshot for info, I can provide more context if necessary.
![screen shot 2015-09-29 at 10 59 48 am](https://cloud.githubusercontent.com/assets/14352762/10174600/79f9d9d4-669f-11e5-8de1-a189b5fb2cad.png)

**Comment by jcanizales** [comment]
Looks like https://github.com/grpc/grpc/issues/3364 resurrected?

**Comment by nkibler** [comment]
I should mention this is building from google3. If this is indeed #3364, were the fixes ever applied to google3?

**Comment by nkibler** [comment]
Not reproducible on GitHub.
