### ISSUE TITLE
THis example not works at all -> https://github.com/grpc/grpc/tree/master/examples/python/xds

### ISSUE THREAD

**Issue by ChameleonRed** [grpc/grpc#35682]
### What version of gRPC and what language are you using?
1.60

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
12.1

### What did you do?
Just follow instruction from example - all command not works apart python server.py.
It is not possible to reproduce example at all.

### What did you expect to see?
Working example.

### What did you see instead?
```
E0126 19:17:05.078953408     339 xds_resolver.cc:921]                  Failed to create xds client -- channel will remain in TRANSIENT_FAILURE: UNKNOWN: Failed to load file
Traceback (most recent call last):
  File "/root/grpc/examples/python/xds/client.py", line 54, in <module>
    run(args.server, args.xds_creds)
  File "/root/grpc/examples/python/xds/client.py", line 38, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name="you"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Failed to create XdsClient: Failed to load file"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Failed to create XdsClient: Failed to load file", grpc_status:14, created_time:"2024-01-26T19:17:05.079030708+00:00"}"
        
        
 root@f1f21960b9cf:~/grpc/examples/python/xds# ./grpcurl --plaintext -d '{"name": "you"}' localhost:50051
Too few arguments.
Try './grpcurl -help' for more details.
```

### Anything else we should know about your project / environment?
it is just docker docker run -it python:12.1

**Comment by ChameleonRed** [comment]
I want to see example of python/xds (maybe +envoy +k8s).

**Comment by gnossen** [comment]
> Failed to create XdsClient: Failed to load file

Sounds like your client failed to load your xDS bootstrap file. Did you create one as described [here](https://github.com/grpc/grpc/tree/master/examples/python/xds#run-the-client) and point the env var `GRPC_XDS_BOOTSTRAP` at it?

Make sure you also have a control plane set up. The best supported one is [Traffic Director](https://cloud.google.com/traffic-director), but [Istio will also work with a few extra steps](https://istio.io/v1.15/blog/2021/proxyless-grpc/). The example file that you're point out here intentionally doesn't cover the steps to set up the control plane, as we want it to be control-plane-agnostic.

> I want to see example of python/xds (maybe +envoy +k8s).

In general, you don't want to mix gRPC proxyless and Envoy. The gRPC proxyless stack has all the functionality of Envoy, except without the hop between processes. But this all definitely works in Kubernetes.
