### ISSUE TITLE
C++ AddMetadata data transfer to server error

### ISSUE THREAD

**Issue by mengxinxiaoqiang** [grpc/grpc#35779]
### What version of gRPC and what language are you using?
grpc-v1.59.1，C++

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
![image](https://github.com/grpc/grpc/assets/56524631/1116665b-67ac-48c5-bdf0-84a05771dbbe)

### What did you expect to see?
I hope the client can correctly transmit data to the server for parsing

### What did you see instead?
![image](https://github.com/grpc/grpc/assets/56524631/9ba4316b-f2fc-444e-9dc9-feff87d79ebc)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
There's not enough information here to reproduce the problem.  The screenshot you shared from the client shows only a small snippet of the client code, and it's not clear exactly where you are seeing the data in the second screenshot.

If you can share a complete, standalone example of your client and server code that we can run, that will help us understand what's happening here.
