### ISSUE TITLE
thread_stress_test fails

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3579]
https://grpc-testing.appspot.com/job/gRPC_master/7727/config=opt,language=c++,platform=macos/console

**Comment by dgquintas** [comment]
Idem, still timing out.

**Comment by jtattermusch** [comment]
Seen again

https://grpc-testing.appspot.com/job/gRPC_master/7887/config=dbg,language=c++,platform=macos/console

```
D1005 13:17:24.531478000 140735213904640 test_config.c:155] test slowdown: machine=1.000000 build=1.000000 total=1.000000
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from End2endTest
[ RUN      ] End2endTest.ThreadStress
E1005 13:17:24.533657000 140735213904640 tcp_client_posix.c:169] socket error: connection refused

TIMEOUT: bins/dbg/thread_stress_test
```

**Comment by soltanmm** [comment]
Seen again here: https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=c++,platform=macos/7913/testReport/(root)/tests/bins_opt_thread_stress_test/ (but there's a fix coming it seems?)
