### ISSUE TITLE
Cross compiling grpc c++ for android is not working

### ISSUE THREAD

**Issue by TaherLkdw** [grpc/grpc#35853]
### What version of gRPC and what language are you using?
gRPC 1.60.0

### What operating system (Linux, Windows,...) and version?
Mac 12.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang 17.0.2 for android

### What did you do?
I am trying to cross compile grpc cpp for android. Below are the steps performed for comipilng:

>>mkdir -p "cmake/build"
    pushd "cmake/build"
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DgRPC_INSTALL=ON \
        -DgRPC_BUILD_TESTS=OFF \
        -DgRPC_SSL_PROVIDER=package \
        ../..
    make "-j4" install
    popd

Above steps installs protoc and grpc_cpp_plugin in /usr/local/bin.

After that, to compile for android below steps are performed:

>>mkdir -p "cmake/build-android"
    pushd "cmake/build-android"
    cmake -DCMAKE_TOOLCHAIN_FILE= ~ /Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake\
      -DCMAKE_CROSSCOMPILING=true\
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_INSTALL_PREFIX= ~ /.local/android \
      -DCMAKE_SYSTEM_NAME=Android \
      -DANDROID_PLATFORM=android-33 \
      -DCMAKE_BUILD_TYPE=Release \
      -DANDROID_STL=c++_shared \
      ../..
    make "-j4" install
    popd

After setting up for android on running `make "-j4" install` throws an error: 

`[ 99%] Linking C shared library libz.so
ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [third_party/zlib/libz.so] Error 1
make[1]: *** [third_party/zlib/CMakeFiles/zlib.dir/all] Error 2
make: *** [all] Error 2`

If i run `make "-j4" grpc++` then no errors are thrown. But this does not install libs in to the install location.

### What did you expect to see?
Compile and install grpc cpp for android using command `make "-j4" install`

### What did you see instead?
Error:
`[ 99%] Linking C shared library libz.so
ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [third_party/zlib/libz.so] Error 1
make[1]: *** [third_party/zlib/CMakeFiles/zlib.dir/all] Error 2
make: *** [all] Error 2`

**Comment by veblush** [comment]
Please take a look at our CI test for this; https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_android_in_docker.sh 

This is using Linux to cross-compile gRPC for Android.

**Comment by wges** [comment]
@TaherLkdw 
Have you tried to set following cmake option to use zlib from NDK instead of building it?
`-DgRPC_ZLIB_PROVIDER=package`
