### ISSUE TITLE
gem install grpc:1.61.0 takes lot of time to complete

### ISSUE THREAD

**Issue by baelter** [grpc/grpc#35874]
This issue seems to be back for 1.61 https://github.com/grpc/grpc/issues/29489

**Comment by chadlwilson** [comment]
Which ruby version and platform/arch are you installing on?

If its to do with building from source (and you expect to be building from source) perhaps to do with https://github.com/grpc/grpc/issues/35396#issuecomment-1888413021 which seemed to regress in 1.60?

**Comment by baelter** [comment]
```
bundle platform
Your platform is: x86_64-linux

Your app has gems that work on these platforms:
* ruby

Your Gemfile specifies a Ruby version requirement:
* ruby 3.2.3
```

**Comment by chadlwilson** [comment]
#29489 unfortunately is a variety of different issues over time which amount to "pre-compiled native gem variant was not available for the target combination of (Ruby version, OS, arch) --> so rubygems/bundler had to build/install from source (which is very slow)".

There shouldn't be any change for `x86_64-linux` and Ruby 3.2 in any case (native gem available [here](https://rubygems.org/gems/grpc/versions/1.61.0-x86_64-linux)).

I think you will probably need to share more specifics about exactly how you are installing, perhaps your `Gemfile`/`Gemfile.lock`, how to replicate and the logs from your install attempt (comparing the version that worked OK vs `1.61` where it is slow), similar to https://github.com/grpc/grpc/issues/29489#issuecomment-1120822860 ?

**Comment by baelter** [comment]
Ok thanks for the reply. I might reopen and add more logs if it happens for the next version bump as well.
