### ISSUE TITLE
Produce good error messages when connecting to an HTTP server via TLS

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#3587]
and vice versa.

The current error message is "on_writable failed during connect", which is a bit of a disgrace :)

**Comment by makdharma** [comment]
I just tried this - used the RouteGuide app to connect to a random http server and I get the following message. 
2016-05-03 09:55:31.188 RouteGuideClient[85373:3658883] RPC error: Error Domain=io.grpc Code=14 "" UserInfo={io.grpc.TrailersKey={
}, NSLocalizedDescription=, io.grpc.HeadersKey={
}}

Error code 14 corresponds to UNAVAILABLE. I think this is good enough. @jcanizales - OK to close this bug?

**Comment by jcanizales** [comment]
What about the other way around? (Try to connect without TLS to a TLS server)

**Comment by makdharma** [comment]
Same error the other way around as well. Closing.
