### ISSUE TITLE
Expose the functionality to parse the grpc peer and get the scheme, address, and port

### ISSUE THREAD

**Issue by alevenberg** [grpc/grpc#35885]
### Is your feature request related to a problem? Please describe.
For Open Telemetry tracing in C++, we want to add this metadata to our gRPC spans.

### Describe the solution you'd like

Using the [URI class](https://github.com/grpc/grpc/blob/3459e5c7b83574ad21c99f0df96dc1e1a7f04581/src/core/lib/uri/uri_parser.h) in the grpc library it, it would do something like:
```
auto uri = grpc_core::URI::Parse(local_addr);
auto scheme = uri->scheme(); 
auto host = uri->host(); // From uri->authority()
auto port = uri->port();  // From uri->authority()
```

### Describe alternatives you've considered
Implementing the parsing ourselves.

**Comment by yashykt** [comment]
I don't think we want to expose this API as a public surface.

**Comment by yashykt** [comment]
The main rationale being - the moment we expose a public library that does this, gRPC gets on the hook for any issues (potentially security issues) that come up from URI parsing. If we do decide to expose this API, I think we would prefer it to be in a different repo, not grpc/grpc. 

Maybe something like absl is better suited to supporting this.

**Comment by yashykt** [comment]
Keeping this open with "disposition/requires reporter action" to invite additional arguments incase I'm missing anything

**Comment by alevenberg** [comment]
That's fair. Closing the issue.
