### ISSUE TITLE
php-grpc exit timeout [php]

### ISSUE THREAD

**Issue by wq19901103wq** [grpc/grpc#3588]
Have you ever noticed this situation, if you use php-grpc , then when you exit, it will about last 5 seconds (both in console and brower). Both in the example helloword.php  and unit test. If send many requests, it response fast each time, but when scipt end, if will last many seconds. I try die() exit() set_timelimit() and all kinds of method, but not work.I guess its reason is the Call, not destruct, can any one help me?

**Comment by stanley-cheung** [comment]
Folding this into #4017
