### ISSUE TITLE
Ruby health checker failed on overall check

### ISSUE THREAD

**Issue by JohanSJA** [grpc/grpc#3590]
It is mentioned in the doc (https://github.com/grpc/grpc/blob/master/doc/health-checking.md) that 

> The server should use an empty string as the key for server’s overall health status, so that a client not interested in a specific service can query the server's status with an empty request

However, the Ruby checker (https://github.com/grpc/grpc/blob/master/src/ruby/pb/grpc/health/checker.rb#L50) will fails the empty check.

**Comment by tbetbetbe** [comment]
Can you clarify what's failing with an example ?

E.g, see the [success tests for checker](https://github.com/grpc/grpc/blob/master/src/ruby/spec/pb/health/checker_spec.rb#L87) and how they as used in the [add_status and check](https://github.com/grpc/grpc/blob/master/src/ruby/spec/pb/health/checker_spec.rb#L114)
test

Are you registering a status for the entire server ?
> The server should register all the services manually and set the individual status, including an empty service name and its status.

**Comment by JohanSJA** [comment]
Totally missed the line that you have pasted. I filed this issue when I was comparing the behavior between Go's health check and Ruby's. I don't have to set the overall (empty string) health check in Go and I thought that was the intended behavior. So Ruby should be doing the right thing anyway, thanks for pointing that out.

I'll close the issue as it has been clarified then. Thanks.
