### ISSUE TITLE
Incorrect XML documentation comment generation for unusual comments

### ISSUE THREAD

**Issue by AlphaGremlin** [grpc/grpc#35905]
### What version of gRPC and what language are you using?
C#, NuGet package 2.61.0

### What operating system (Linux, Windows,...) and version?
Windows 10 22H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
.Net 6.0

### What did you do?
Create a .proto file with a message and a field with a comment that inadvertently includes an additional leading slash.

```proto
syntax = "proto3";

message TestMessage {
    /// This has an extra leading slash, and breaks
    string BadField = 1;
    //This has the normal number of slashes, but no space
   string WeirdField = 2;
    // This has the normal number of slashes, and is fine
   string OkField = 3;
}
```

### What did you expect to see?
The generated C# code will have valid XML documentation comments, even with unusual but otherwise valid source comments.

### What did you see instead?
The commented text is placed straight into the raw output, resulting in a comment for `BadField` like:
```cs
/// <summary>
//// This has an extra leading slash, and breaks
/// </summary>
```

C# requires exactly three slashes for an XML documentation comment, so four is interpreted as a normal comment, resulting in some rather confusing warnings until you realise the cause.

```
warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.'
warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.'
warning CS1587: XML comment is not placed on a valid language element
```

Also, `WierdField` generates a comment like:
```cs
/// <summary>
///This has the normal number of slashes, but no space
/// </summary>
```

This suggests the text is taken directly after the `//` characters, with no whitespace added when generating a multi-line XML comment. The leading whitespace is not technically required, but it can result in this situation where the XML comment format gets broken.

### Anything else we should know about your project / environment?
This is a common typo, especially if your muscle memory is to type three slashes for field comments.

**Comment by tonydnewell** [comment]
@apolcyn I'll take a look

**Comment by tonydnewell** [comment]
I've just confirmed that this behaviour is the same in both the protocol buffers C# plugin and the gRPC C# plugin.

**Comment by tonydnewell** [comment]
Some details - there are two places a simple fix could be made, to check if the line starts with a '`/`' and if so insert a space:
- protocol buffers `WriteDocCommentBodyImpl` method - see [here](https://github.com/protocolbuffers/protobuf/blob/1f701a2ba9e069acead41ffd6071e6f0f00adb0e/src/google/protobuf/compiler/csharp/csharp_doc_comment.cc#L57 )
- grpc csharp plugin `GenerateDocCommentBodyImpl` method - see [here](https://github.com/grpc/grpc/blob/cfcbb0a535a190458384ec6718a496c5b54af9ec/src/compiler/csharp_generator.cc#L85)

Generally we don't check for well-formed doc comments - we just pass on the comments as-is. So whether these fixes should be done is up for debate.
