### ISSUE TITLE
HelloWorld example project build fails for Windows 11 and Visual Studio 2022

### ISSUE THREAD

**Issue by embeddetech** [grpc/grpc#35916]
The Hello World C++ CMake project does not build on Windows at gRPCtest\gRPC\grpc\examples\cpp\helloworld. To be more specific, build generation fails. 

To reproduce, on Windows 11, after cloning the repository in C;\gRPCtest:

cd C:\gRPCtest\gRPC\grpc\examples\cpp\helloworld
md .build
cd .build
cmake .. -G "Visual Studio 17 2022"

I was going to then attempt to build in Release mode with this command:
cmake --build . --config Release

as per the issue of building without explicitly configuring the build for Release mode as per this issue:
https://github.com/grpc/grpc/issues/35202

**Comment by yashykt** [comment]
If it's the same issue, maybe we can track it in the same issue?

**Comment by embeddetech** [comment]
Hello @yashykt ,
Actually, no it's not quite the same issue, but related. In the other issue, the problem is I can't build the main gRPC library using CMake with the Visual Studio 2022 build system generator, without specifying Release mode. (I would much prefer debug mode, but with that work around, the main library does at least both generate and build).

This issue is with the Hello World example project with CMake. It does not properly generate the project, I don't even get to the build stage. And this is important, because this example project helps me understand what my usage requirements are.

I will be using gRPC in an IDE project, not generated by CMake. But CMake is the only way to practically pull gRPC into my IDE project. I have built the libraries, so I have the binary outputs. But I need a working CMake Hello World example, generating and building in Visual Studio 2022, so that I have a working reference for understanding my usage requirements (what libraries to link to, what header file paths to include, etc...).

I'm actually needing this in two projects, a native Visual Studio 2022 project and a native Android Studio (CMake) project. So having a building example project that uses the library is important. Hope that clarifies.

Thanks!
