### ISSUE TITLE
Failed to launch C# gRPC with x64 arch on Windows

### ISSUE THREAD

**Issue by nickdul** [grpc/grpc#3591]
the underlying issue is that latest Grpc NuGet package (`0.7.1`) is shipped without 64-bit version of `grpc_csharp_ext.dll`
not sure why - maybe due to this reason: https://github.com/grpc/grpc/issues/1082#issuecomment-84752606 

i was tried to compile `grpc_csharp_ext.dll` for x64 arch manually
and everything is working fine for my x64 C# gRPC **Client**

unfortunately my very simple x64 C# gRPC **Server** is failed to start with the following error:
```
..\..\..\src\core\support\stack_lockfree.c:132: assertion failed: (old_val & (1UL << pushed_bit)) == 0
```

**NB:** x86 version of gRPC **Server** is started without problem 

does anybody know how to fix this issue?
any help is appreciated...

**Comment by zhengcai** [comment]
I have also seen this problem for my C++ Windows x64 gRPC server code. Even after I applied the patch of #1082, the problem still exists.

**Comment by jtattermusch** [comment]
Closing this as obsolete. 

In the next release, we will publish nuget packages that will fully support Win 32bit and Win 64bit (including autodetection). See #4820 for details.
