### ISSUE TITLE
I have the same problem with c++ on TryCancel() function

### ISSUE THREAD

**Issue by osivinyuk** [grpc/grpc#35920]
I am using GRPC C++ client with Java GRPC server.
I have multiple stream services.
When i am losing connection with server or recieving some errors i would like to reconnect.
For reconnection process I am using next code:

void ObjectSnapshot::OnDone(const grpc::Status& status)
{
SSF_CORE_NS::CriticalSection(_responce_lock);
++_error_count;
done_event.signal();
}

void ObjectSnapshot::cancel()
{
_client_context.TryCancel();
done_event.wait(-1);
}

On my "cancel" function process/thread is freezing. I was thinking that its the problem with specific service, but i see always the proble m with different services.

Maybe, its bad way for reconnection or the problem with gRPC lib.

### What version of gRPC and what language are you using?
C++ 1.53

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS 2019.161127

### What did you do?
We dont have any tests for this issue.

**Comment by yashykt** [comment]
I don't understand your code nor the problem that you are facing. Can you provide your code in a gist maybe?

Also, gRPC tries to abstract away connection semantics from the application as much as it can, so generally you don't need to worry about channel disconnects. On a new RPC, if the channel is not already connected, it will trigger a connect.

**Comment by osivinyuk** [comment]
we have C++ gRPC streams and sometimes we have errors in this streams. We are trying to reconnect all streams, with BackendControllerImpl::restart(). Each stream has ->cancel() function and its freezing on any cancel.

Cancel example
void GetProtect::cancel()

its the same for all services

we are waiting void GetProtect::OnDone(const grpc::Status& status)
but its doesnt calling
[backend_example.zip](https://github.com/grpc/grpc/files/14387141/backend_example.zip)
