### ISSUE TITLE
import grpc in a python file which imports a pybind11 shared object which has another set of grpc calls ( written in C++ ) causes a crash

### ISSUE THREAD

**Issue by amanmishra0211** [grpc/grpc#35947]
### What version of gRPC and what language are you using?
python, C++, pybind11, grpc version = 1.46.7, protobuf=3.19.6

### What operating system (Linux, Windows,...) and version?
Linux(Yocto kirkstone)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10

### What did you do?
import grpc
import my_bindings       ( this imports my shared object which has pybind11 successfully )

my_obj= my_bindings .MyClient("localhost:50051")   --> Creates the object only of my class
my_obj.create_channel() --> creates a channel to communicate with my server

### What did you expect to see?
Channel created successfully

### What did you see instead?
Segementation fault

**Objective:**
My objective is to have a shared library written in C++ which does a few grpc calls to the server.
So we created this shared library in C++, created python bindings and call the API's from a python file.

**Observations**
My bindings are created correctly. my shared library written in C++ has a set of grpc calls. If there is NO "import grpc" in python file then everything works fine inside the shared library and channels are created successfully. 

But I **ALSO** need to make a separate set of grpc calls in my python code as well, so i do need to "import grpc" in my python code. 
When i import grpc in python code, there is a segmentation fault inside my shared object while creating the channel.

Why does a import grpc cause a segmentation fault inside my library when it tries to create a channel ?

**Comment by yashykt** [comment]
@gnossen @XuanWang-Amos have y'all seen this pattern before?

**Comment by amanmishra0211** [comment]
This bug is very easily reproducible. If anyone needs anything from me please let me know.

**Comment by gnossen** [comment]
I think this is going to come down the visibility of the symbols exposed by the SO, which will ultimately come down to the linker invocation (in either or both of the SOs). [We've done something like this on MacOS already](https://github.com/grpc/grpc/blob/fbbdda4e519f9f62ad8d77d751fc6b807f3df57b/tools/distrib/python/grpcio_tools/setup.py#L172), but I don't believe we've done anything similar to this on Linux.

**Comment by amanmishra0211** [comment]
[grpc_bindings_test.zip](https://github.com/grpc/grpc/files/14374319/grpc_bindings_test.zip)
Note: I build for ARM aarch64, 
I have uploaded a sample source code with the issue reproducible.
![image](https://github.com/grpc/grpc/assets/159764715/91590866-0948-47c4-a6b6-e6a8ca94be78)

Just comment out "import grpc" in "test_bindings.py" and there will be no segmentation fault.(screenshot below)
![image](https://github.com/grpc/grpc/assets/159764715/4fca4c9e-81a1-4bf1-8e53-82a067ccaa5b)

Also note, i did not have to show any grpc calls in this sample code as "import grpc" is enough to reproduce the issue

**Comment by amanmishra0211** [comment]
@gnossen request for your thoughts on the issue

**Comment by XuanWang-Amos** [comment]
Hi, thanks for the additional info, we checked it out and didn't find much useful information from the `.so` file, can you do one of the following:
1. Attach gdb to the process and share the backtrace with us.
2. Provide a x86-64 build for reproduction (We don't have an easy access for an ARM aarch64 machine).
3. A hermetic reproduction case for x86-64.
