### ISSUE TITLE
tools/run_tests/run_ruby.sh timeouts

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#3598]
https://grpc-testing.appspot.com/job/gRPC_master/7774/config=dbg,language=ruby,platform=linux/console

**Comment by ctiller** [comment]
Raising to P0 as it was seen during a pull request here:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/config=opt,language=ruby,platform=linux/3506/console

**Comment by ctiller** [comment]
Any updates?

**Comment by ctiller** [comment]
Haven't seen this on recent pull requests. Lowering priority, will re-raise if seen again.

**Comment by jtattermusch** [comment]
I won't be able to look into this.

**Comment by dgquintas** [comment]
Seen again on macos: https://grpc-testing.appspot.com/job/gRPC_master/15215/config=opt,language=ruby,platform=macos/consoleText

**Comment by murgatroid99** [comment]
Actually, I'll reopen this until we verify that it's fixed.

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/15403/config=dbg,language=ruby,platform=macos/testReport/(root)/tests/tools_run_tests_run_ruby_sh/

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/15396/config=opt,language=ruby,platform=linux/testReport/junit/(root)/tests/tools_run_tests_run_ruby_sh/

**Comment by jtattermusch** [comment]
Doesn't look like we're seeing this anymore. Closing this as part of buildpony bankruptcy.
