### ISSUE TITLE
macos opt/tcp_client_posix_test fails

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#3599]
https://grpc-testing.appspot.com/job/gRPC_master/7774/config=opt,language=c,platform=macos/console
```
D1001 11:48:37.080791000 140735213904640 test_config.c:155] test slowdown: machine=1.000000 build=1.000000 total=1.000000
D1001 11:48:37.081419000 140735213904640 tcp_client_posix_test.c:90] test_succeeds
E1001 11:48:37.081796000 140735213904640 tcp_client_posix_test.c:274] End of first test
D1001 11:48:37.081807000 140735213904640 tcp_client_posix_test.c:142] test_fails
E1001 11:48:37.081840000 140735213904640 tcp_client_posix.c:261] connect error to 'ipv4:0.0.0.0:0': Can't assign requested address
D1001 11:48:38.089281000 140735213904640 tcp_client_posix_test.c:185] test_times_out
D1001 11:48:38.091947000 140735213904640 tcp_client_posix_test.c:237] now=1.010561550 connect_deadline=2.010502930
E1001 11:48:38.092143000 140735213904640 tcp_client_posix_test.c:76] assertion failed: g_connecting == NULL

*******************************
Caught signal 6
  no backtrace

FAILED: bins/opt/tcp_client_posix_test [ret=-6, pid=66205]
```

**Comment by murgatroid99** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_master/7965/config=opt,language=c,platform=macos/console

**Comment by dklempner** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_master/lastCompletedBuild/config=opt,language=c,platform=macos/console

**Comment by soltanmm** [comment]
Like a photogenic yeti: https://grpc-testing.appspot.com/job/gRPC_master/lastCompletedBuild/config=opt,language=c,platform=macos/testReport/(root)/tests/bins_opt_tcp_client_posix_test/

**Comment by murgatroid99** [comment]
And again: https://grpc-testing.appspot.com/job/gRPC_master/13042/config=opt,language=c,platform=macos/testReport/junit/(root)/tests/bins_opt_tcp_client_posix_test/

**Comment by adelez** [comment]
Another instance: https://grpc-testing.appspot.com/job/gRPC_master/13564/config=opt,language=c,platform=macos/testReport/junit/(root)/tests/bins_opt_tcp_client_posix_test/

**Comment by dgquintas** [comment]
And again: https://grpc-testing.appspot.com/job/gRPC_master/15215/config=dbg,language=c,platform=macos/consoleText

**Comment by sreecha** [comment]
Still happening..
https://grpc-testing.appspot.com/job/gRPC_master/15481/config=opt,language=c,platform=macos/
