### ISSUE TITLE
SIGBUS error in MIPS 64 platform when tcp_annotate_error is used with GRPC_OS_ERROR

### ISSUE THREAD

**Issue by sreelakshmi1608** [grpc/grpc#36018]
### What version of gRPC and what language are you using?
1.52

### What operating system (Linux, Windows,...) and version?
BSD12

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang 13

### What did you do?
In tcp_flush(), tcp_annotate_error() was called using GRPC_OS_ERROR when the errno was 32 (EPIPE)
grpc_os_error() creates absl::Status variable and sets the payloads of StatusRep structure with various properties and values.
When grpc_error_add_child() is called eventually,
it results in sigbus error on MIPS 64 platform.
we tried commenting out setting of few properties in grpc_os_error() which resulted in lesser size of payloads of StatusRep Structure and we have observed that if the payloads size of StatusRep structure is >4, it results in SIGBUS error on MIPS 64 platform

The same flow of code on x86 platform with payloads size same as 7 in grpc_os_error() doesn't have any issue.
The issue is seen only on MIPS 64 platform

### What did you expect to see?
No sigbus error

### What did you see instead?
SIGBUS error

Here is the core bt:

(gdb) bt
#0  upb_Message_GetUnknown (msg=msg@entry=0x0, len=0x7ffdda9c) at ../../../../../../../src/external/apache2/grpc/dist/third_party/upb/upb/msg.c:103
#1  0x0794a720 in encode_message (e=0x7ffddb90, msg=0x0, m=0x7a49cc0 <google_protobuf_Any_msginit>, size=0x7ffddaf8) at ../../../../../../../src/external/apache2/grpc/dist/third_party/upb/upb/encode.c:537
#2  0x0794b838 in encode_array (e=0x7ffddb90, msg=<optimized out>, subs=<optimized out>, f=0x75bbe44 <google_rpc_Status__fields+24>) at ../../../../../../../src/external/apache2/grpc/dist/third_party/upb/upb/encode.c:380
#3  0x0794aa2c in encode_field (e=0x7ffddb90, msg=0x9c08058, subs=0x7a49cc0 <google_protobuf_Any_msginit>, field=<optimized out>) at ../../../../../../../src/external/apache2/grpc/dist/third_party/upb/upb/encode.c:491
#4  encode_message (e=0x7ffddb90, msg=0x9c08058, m=0x7a49be8 <google_rpc_Status_msginit>, size=<optimized out>) at ../../../../../../../src/external/apache2/grpc/dist/third_party/upb/upb/encode.c:568
#5  0x0794a54c in upb_Encode (msg=0x9c08058, l=0x7a49be8 <google_rpc_Status_msginit>, options=<optimized out>, arena=<optimized out>, buf=0x7ffddd98, size=0x7ffdddb4) at ../../../../../../../src/external/apache2/grpc/dist/third_party/upb/upb/encode.c:597
#6  0x0793a0ec in google_rpc_Status_serialize (msg=0x0, arena=0x9c08154, len=0x7ffdddb4) at ../../../../../../../src/external/apache2/grpc/dist/src/core/ext/upb-generated/google/rpc/status.upb.h:57
#7  grpc_core::StatusAddChild (status=0x7ffdde38, child=...) at ../../../../../../../src/external/apache2/grpc/dist/src/core/lib/gprpp/status_helper.cc:263
#8  0x0792f7f4 in grpc_error_add_child (src=..., child=...) at ../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/error.cc:193
#9  0x0787d494 in close_transport_locked (t=0x95bfa04, error=...) at ../../../../../../../src/external/apache2/grpc/dist/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:592
#10 0x07884184 in write_action_end_locked (tp=0x95bfa04, error=...) at ../../../../../../../src/external/apache2/grpc/dist/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:920
#11 0x0791dd64 in grpc_combiner_continue_exec_ctx () at ../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/combiner.cc:231
#12 0x0791c1cc in grpc_core::ExecCtx::Flush (this=0x7ffde058) at ../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/exec_ctx.cc:75
#13 0x0766bda4 in grpc_core::ExecCtx::~ExecCtx (this=0x7ffde058) at ../../../../../../../src/external/apache2/grpc/dist/src/core/lib/iomgr/exec_ctx.h:117

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
we don't have any CI testing on MIPS 64 platforms. From the stacktrace, it looks like the source of the error is coming from upb. There is a chance that the error is due to unaligned memory accesses. Can you try using the latest version?
