### ISSUE TITLE
C#: tests.Grpc.Core.Tests timeout

### ISSUE THREAD

**Issue by dklempner** [grpc/grpc#3604]
https://gist.github.com/dklempner/35628ed027c9a5f424fc

It looks like there are about 4.5 minutes between
***** Grpc.Core.Tests.ClientServerTest.UnaryCallPerformance
and the end of the test.

**Comment by jtattermusch** [comment]
@dklempner  thanks for reporting this and finding the cause by taking time to analyze the log carefully.
