### ISSUE TITLE
Use go1.22 for go interop tests and for future interop_matrix tests

### ISSUE THREAD

**Issue by arvindbr8** [grpc/grpc#36060]
gRPC-Go [added support](https://github.com/grpc/grpc-go/pull/7005) for go v1.22. This issue is to track adding go1.22 for go interop tests and for future interop_matrix tests similar to https://github.com/grpc/grpc/pull/31732

**Comment by arjan-bal** [comment]
I have a PR to fix this: https://github.com/grpc/grpc/pull/36755

Will mark it as ready for review soon.

**Comment by arvindbr8** [comment]
Thanks for looking into this @arjan-bal. Assigning you to this issue.
