### ISSUE TITLE
Version 1.62.1 freeze google vision API credentials load.

### ISSUE THREAD

**Issue by jorgerodriguezsj** [grpc/grpc#36098]
In an app with horizontally scaled machines when all the machines start working together the client creation with `client = vision.ImageAnnotatorClient(credentials=credentials) `gets freeze.

Downgrade to and older version solves the problem.

**Comment by gnossen** [comment]
Can you please provide some more details? This doesn't seem actionable on our part at the moment. If you hit `ctrl-C` during the freeze, it should generate a stack trace. This would give us a lot of information about where the hang is happening.

**Comment by embray** [comment]
Also same as https://github.com/googleapis/google-cloud-python/issues/12423

And similar to https://github.com/googleapis/python-bigtable/issues/949
