### ISSUE TITLE
Sync call is blocking indefinitely

### ISSUE THREAD

**Issue by surajkottayi** [grpc/grpc#36109]
### What version of gRPC and what language are you using?
v1.37.1, C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
GNU 9.4.0

### What did you do?
Using gRPC api's for synchronous call
cloned the code => 
git clone --recurse-submodules -b v1.37.1 --depth 1 --shallow-submodules https://github.com/grpc/grpc
Installed in /usr/local

### What did you expect to see?
A quick handshake bw greeter_client and greeter_server Inside helloworld.

### What did you see instead?
The client call is blocking, and the response from the server is getting delayed
Everything work's fine, when i repeat the steps with gRPC package v1.59.0 or higher

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by surajkottayi** [comment]
Could u please help me out ?

**Comment by surajkottayi** [comment]
<img width="646" alt="image" src="https://github.com/grpc/grpc/assets/138424950/ec8b1e2b-3e67-4a27-b520-0b85a32bedfa">

**Comment by surajkottayi** [comment]
<img width="646" alt="image" src="https://github.com/grpc/grpc/assets/138424950/1ab6c8e4-9514-46ae-a283-abadd87b7998">

**Comment by drfloob** [comment]
v1.37 is 3 years old. Please upgrade to a newer version, you are missing years of fixes, features, and improvements.
