### ISSUE TITLE
Only include System.Memory when framework can not provide it

### ISSUE THREAD

**Issue by thompson-tomo** [grpc/grpc#36139]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
A new TFM is added to the nuget package -> net Standard 2.1 &/or NET 6
The system.Memory package becomes conditional so only added for the older frameworks

### Describe alternatives you've considered
Accept the additional dependency

### Additional context
n/a

**Comment by thompson-tomo** [comment]
Grpc.Core.Api has been done and released.

I looked at submitting a PR got Grpc.Core but couldn't succeed in checking out the branch

**Comment by apolcyn** [comment]
Closing since this is an enhancement. We are only providing bug and security fixes for Grpc.Core, at this point.
