### ISSUE TITLE
SSL fails with self-signed certificates in Ruby

### ISSUE THREAD

**Issue by marcinwyszynski** [grpc/grpc#3613]
Hey, I've been trying to set up SSL between server and client (without forcing client authentication) running in Docker containers and I just can't get it to work. I got as far as:

```
client_1 | E1003 19:25:38.817081462      11 handshake.c:212]            Handshake failed with error TSI_PROTOCOL_FAILURE
client_1 | E1003 19:25:38.817605097      11 secure_channel_create.c:98] Secure handshake failed with error 2.
server_1 | E1003 19:25:38.818217132       1 handshake.c:186]            Read failed.
server_1 | E1003 19:25:38.818701829       1 server_secure_chttp2.c:154] Secure transport failed with error 2
```

Here's what I'm doing on the server side:
```ruby
if __FILE__ == $PROGRAM_NAME
  credentials = GRPC::Core::ServerCredentials.new(
    File.read('/.keys/ca.crt'), # pem_root_certs
    [{
      private_key: File.read('/.keys/server.key'),
      cert_chain: File.read('/.keys/server.crt')
    }],
    false # force client authentication
  )
  server = GRPC::RpcServer.new
  address = '0.0.0.0:1983'
  server.add_http2_port(address, credentials)
  server.handle(FortuneServer.new)
  server.run
end
```

On the client side:
```ruby
credentials = GRPC::Core::Credentials.new(
  File.read('/.keys/ca.crt'),
  nil,
  nil
)
@client = FortuneService::Stub.new('server:1983', creds: credentials)
@cookie = @client.get_fortune(FortuneRequest.new).to_json
```

I took these steps to generate and self-sign certificate:
```
# Generate CA key:
openssl genrsa -des3 -out ca.key 4096

# Generate CA certificate:
openssl req -new -x509 -days 365 -key ca.key -out ca.crt

# Generate server key:
openssl genrsa -des3 -out server.key 4096

# Generate server signing request:
openssl req -new -key server.key -out server.csr

# Self-sign server certificate:
openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt

# Remove passphrase from server key:
openssl rsa -in server.key -out server.key
```

Server name in the certificate is set to the name of the Docker container in `docker-compose.yml` which is also how I'm addressing the server from the client. Please kindly help me understand if I'm doing something wrong (probably) or this is something unexpected in the gRPC library.

**Comment by marcinwyszynski** [comment]
Sorry please disregard it. That's just me being a retard.

**Comment by rafaelsales** [comment]
@marcinwyszynski I'm having some trouble to setup this.
My server is Ubuntu and I have installed the `ca-certificates` package. Do you think I can reuse the certificates contained on it?

**Comment by marcinwyszynski** [comment]
@rafaelsales If you need inspiration with SSL in grpc please have a look at [this repo](https://github.com/codequest-eu/grpc-demo) - the whole key and cert business is kind of tricky to get at first.

**Comment by rafaelsales** [comment]
@marcinwyszynski 

Really thanks for that, it was really helpful!

I was trying to have even smaller setup for these keys, and I was thinking that having only the server keys would be enough to achieve encryption. Do you think I'm losing anything with this only:

```
openssl genrsa -passout pass:1111 -des3 -out server.key 4096

openssl req -passin pass:1111 -new -x509 -days 3650 -key server.key -out ayla_server.crt -subj '/C=US/ST=NY/L=NYC/O=MyApp/CN=grpc_server/emailAddress=support@myapp.com'

openssl rsa -passin pass:1111 -in server.key -out server.key
```

and the Ruby code would be:

```
credentials = GRPC::Core::ServerCredentials.new(
  nil, # pem_root_certs
  [{
    private_key: File.read('server.key'),
    cert_chain: File.read('server.crt')
  }],
  true # force client authentication
)
server = GRPC::RpcServer.new
server.add_http2_port('0.0.0.0:1983', credentials)
```

On the client side:
```ruby
credentials = GRPC::Core::Credentials.new(File.read('server.crt'))
client = FortuneService::Stub.new('grpc_server:1983', creds: credentials)
```

**Comment by marcinwyszynski** [comment]
@rafaelsales You should be fine. I'm also using client authentication which is why this setup is more complex. But if you don't need that then by all means you should be fine.
