### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by Codiy-Huang** [grpc/grpc#36147]
Starting in spring 2024, SDKs that require a privacy manifest and signature, Is there a plan to update `!ProtoCompiler-gRPCPlugin` to the latest versions of all its dependency libraries, in order to meet this requirement? The current latest version of `CocoaPods` is `1.50.0-pre1`.

References
https://developer.apple.com/support/third-party-SDK-requirements/

Thanks!

**Comment by SlavomirDurta** [comment]
Hi, how does it look with this issue ? I am currently unable to update the gRPC-ProtoRPC objective c library with the privacy manifest. I don't know if I'm doing something wrong, but the latest version I have available is 1.49.

**Comment by Codiy-Huang** [comment]
> Hi, how does it look with this issue ? I am currently unable to update the gRPC-ProtoRPC objective c library with the privacy manifest. I don't know if I'm doing something wrong, but the latest version I have available is 1.49.

Hello, I have currently removed the dependency on !ProtoCompiler-gRPCPlugin and switched to locally compiling .m and .h files. By adding the latest versions of gRPC-ProtoRPC and abseil SDKs in the Podfile, I have resolved this issue.

**Comment by SlavomirDurta** [comment]
Thank you for your answer but it is still not clear to me, how you solved this problem. In my project I use this podspec https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Objective-C/Speech-gRPC-Streaming/googleapis.podspec, in which there is a dependency on "!ProtoCompiler-gRPCPlugin". Did you have a similar problem as me ? If so can you explain me more about your solution ?

**Comment by Codiy-Huang** [comment]
> Thank you for your answer but it is still not clear to me, how you solved this problem. In my project I use this podspec https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Objective-C/Speech-gRPC-Streaming/googleapis.podspec, in which there is a dependency on "!ProtoCompiler-gRPCPlugin". Did you have a similar problem as me ? If so can you explain me more about your solution ?

1. In the `googleapis.podspec` file, comment out `s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.0"`
2. Manually download `!ProtoCompiler-gRPCPlugin` to obtain the latest version of `grpc_objective_c_plugin`
3. Modify the `googleapis.podspec` file with the line` plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"` to point to the file path of the `grpc_objective_c_plugin` downloaded in the previous step
4. In the Podfile, add:
```
   pod '!ProtoCompiler'
   pod 'gRPC-ProtoRPC', '~> 1.62.1'
   pod 'abseil', '~> 1.20240116.1'
   pod 'Protobuf', '~> 3.26.1'
```
This will update all dependencies to the latest versions.

**Comment by SlavomirDurta** [comment]
Thank you for your answer. I managed to install it successfully according to the instructions. But I have one last question. Has the information from the privacy manifest file for the gRPC-core library been transferred to the privacy report?

**Comment by Gurpartap** [comment]
More precisely,

1. Install the replacements for !ProtoCompiler and !ProtoCompiler-gRPCPlugin on the system using brew.

```sh
$ brew install protoc grpc
```

Or update them to the latest version, if they're already installed.
```sh
$ brew update protoc grpc
```

2. Modify .podspec to implement the plan:

```podspec
# Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
# s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.0"

# Path where Cocoapods downloads protoc and the gRPC plugin.
# protoc_dir = "#{pods_root}/!ProtoCompiler"
# protoc = "#{protoc_dir}/protoc"
# plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

protoc = "/usr/local/bin/protoc"
plugin = "/usr/local/bin/grpc_objective_c_plugin"
```

3. Compare the versions and apply the update:
```sh
$ pod outdated
$ pod update
```

Done
