### ISSUE TITLE
mold linker symbol mismatch warning

### ISSUE THREAD

**Issue by d7d1cd** [grpc/grpc#36156]
### What version of gRPC and what language are you using?
v1.62.0, С++20

### What operating system (Linux, Windows,...) and version?
AlmaLinux 9

### What runtime / compiler are you using (e.g. python version or version of gcc)
$ g++ --version
g++ (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)

### What did you do?
When I try to link my application with the gRPC library using the [mold linker](https://github.com/rui314/mold), I receive warnings mold.

### What did you expect to see?
No errors or warnings

### What did you see instead?
```bash
mold: warning: symbol type mismatch: X509_it
>>> defined in /usr/etc/grpc_1_62_0/debug/lib/libcrypto.a(x_x509.c.o) as STT_OBJECT
>>> defined in /usr/lib64/libssl.so as STT_FUNC
mold: warning: symbol type mismatch: X509_it
>>> defined in /usr/etc/grpc_1_62_0/debug/lib/libcrypto.a(x_x509.c.o) as STT_OBJECT
>>> defined in /usr/lib64/libcrypto.so as STT_FUNC
mold: warning: symbol type mismatch: X509_CINF_it
>>> defined in /usr/etc/grpc_1_62_0/debug/lib/libcrypto.a(x_x509.c.o) as STT_OBJECT
>>> defined in /usr/lib64/libcrypto.so as STT_FUNC
```

### Anything else we should know about your project / environment?
This exact error was first reported to the [mold project](https://github.com/rui314/mold/issues/1093). But then it turned out that there was a problem in the [volk project](https://github.com/zeux/volk/issues/134).

**Comment by yashykt** [comment]
My first reaction is that this should be assigned to the mold project.  If there's something that gRPC is doing wrong, please recreate the issue with more details.

**Comment by veblush** [comment]
FYI, from the warning messages, it sounds like it's building gRPC with both boringssl and openssl, which shouldn't happen so it might be related to how you built gRPC. In this case, sharing a list of exact commands when buliding it would be useful.

**Comment by d7d1cd** [comment]
I created the grpc library exactly according to the instructions given [here](https://grpc.io/docs/languages/cpp/quickstart/#build-and-install-grpc-and-protocol-buffers). Or do I need the same commands that I use to create my application?
