### ISSUE TITLE
Code generation using cmake during configuration

### ISSUE THREAD

**Issue by surajkottayi** [grpc/grpc#36155]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

This issue will be closed down once seen by the repo managers.

How do i generate code using cmake, during configuration.??
The issue with cmake command execute_process() is that  the argument "--plugin=protoc-gen-grpc=/usr/local/grpc_cpp_plugin" 
has to be absolute, trying to change it into a variable is throwing =>

: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1

**Comment by eugeneo** [comment]
Please post the questions to https://groups.google.com/g/grpc-io discussion forum.
