### ISSUE TITLE
Error when running GRPC Python client on El Capitan

### ISSUE THREAD

**Issue by ochowie** [grpc/grpc#3616]
Getting the following error message when running the GRPC client on El Capitan:

ImportError: dlopen(/Library/Python/2.7/site-packages/grpc/_adapter/_c.so, 2): Library not loaded: libgrpc.dylib
  Referenced from: /Library/Python/2.7/site-packages/grpc/_adapter/_c.so
  Reason: unsafe use of relative rpath libgrpc.dylib in /Library/Python/2.7/site-packages/grpc/_adapter/_c.so with restricted binary

**Comment by soltanmm** [comment]
What were the steps you took to install the GRPC core package, and additionally what were the steps you took to install the GRPC Python package?

**Comment by ochowie** [comment]
It was all built from the GRPC repo including protobuf and the python library.



—

**Comment by soltanmm** [comment]
Was made irrelevant by core bundling a while back.
