### ISSUE TITLE
RegexMatchTimeoutException in Grpc.Tools.ProtoCompile.Execute when building proto files in csproj

### ISSUE THREAD

**Issue by kikcorp** [grpc/grpc#36162]
Dear team, do you have if there are any ways to set a timeout or avoid this error during the building process? 

In source code i can't see anything 

https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/ProtoCompile.cs#L129

> /root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018: The "ProtoCompile" task failed unexpectedly.
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018: System.Text.RegularExpressions.RegexMatchTimeoutException: The Regex engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at System.Text.RegularExpressions.RegexRunner.<CheckTimeout>g__ThrowRegexTimeout|25_0()
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Regex8_TryMatchAtCurrentPosition(RegexRunner, ReadOnlySpan`1)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Regex8_Scan(RegexRunner, ReadOnlySpan`1)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at System.Text.RegularExpressions.Regex.RunSingleMatch(RegexRunnerMode mode, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at System.Text.RegularExpressions.Regex.Match(String input)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Grpc.Tools.ProtoCompile.LogEventsFromTextOutput(String singleLine, MessageImportance messageImportance) in /var/local/git/grpc/src/csharp/Grpc.Tools/ProtoCompile.cs:line 594
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.LogMessagesFromStandardErrorOrOutput(Queue dataQueue, ManualResetEvent dataAvailableSignal, MessageImportance messageImportance, StandardOutputOrErrorQueueType queueType)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Grpc.Tools.ProtoCompile.Execute() in /var/local/git/grpc/src/csharp/Grpc.Tools/ProtoCompile.cs:line 611
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/root/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

**Comment by jzabroski** [comment]
The compiler uses regular expressions?

**Comment by tonydnewell** [comment]
There is no way to set the regex timeout. It is hard coded to 100 ms. 

https://github.com/grpc/grpc/blob/c54c69dcdd483eba78ed8dbc98c60a8c2d069758/src/csharp/Grpc.Tools/ProtoCompile.cs#L129

Regular expressions are used to parse error messages returned by the `protoc` compiler.

Is there a particular `.proto` file that is causing you problems?

**Comment by MitchDart** [comment]
We are facing this issue on our build pipelines. Any chance we can get that fix to 1s in?

**Comment by tonydnewell** [comment]
> We are facing this issue on our build pipelines. Any chance we can get that fix to 1s in?

The fix is in the release `Grpc.Tools` 2.63.0
