### ISSUE TITLE
Collision for Enums using underscores

### ISSUE THREAD

**Issue by shelilevine** [grpc/grpc#36175]
### What version of gRPC and what language are you using?
grpcio 1.55.0
grpcio-tools 1.55.0
protobuf 4.25.3

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

running grpc_tools.protoc on proto file with the below message type

`enum Category {
    CAT1_1 = 0;
    CAT1_2 = 1;
    CAT11 = 2;
    CAT11_1 = 3;
}
`

### What did you expect to see?
Proto is compiled successfully

### What did you see instead?
Proto compiling fails with error
`Enum name CAT11 has the same name as CAT1_1 if you ignore case and strip out the enum name prefix (if any). (If you are using allow_alias, please assign the same numeric value to both enums.)`

This is new behavior when upgrading to grpcio version 1.55.0 from 1.54.3.
Note this has appeared as a warning before, but never caused compiling to fail

**Comment by XuanWang-Amos** [comment]
Looks like this message comes from Protobuf: https://github.com/protocolbuffers/protobuf/blob/b497787aef641e52846514c1ec60be9a18805590/src/google/protobuf/descriptor.cc#L6698-L6701


We update Protobuf with our new release so this was picked up when we update from 1.54 to 1.55.

Since this is purely related to Protobuf, we suggest you open an issue on their repo.

**Comment by shelilevine** [comment]
I'm not sure this is a protobuf issue. 
The message was there prior to upgrading grpcio library versions but only after upgrading grpcio did compiling fail. 

The behavior is consistent without changing the protobuf version we are using and it looks like the protobuf version in your requirements.txt is the same for both v1.54.3 and v1.55.0.
