### ISSUE TITLE
Improve robustness against Python build failures on pull requests due to network flakiness

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3623]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3484/

**Comment by soltanmm** [comment]
Those are installation errors from upstream protobuf. It's bugging out on connection to the server.

**Comment by soltanmm** [comment]
Closing, given #3619 has already gone in and the prescription would be, "restart the tests and hope `pip` doesn't trip over itself trying to find `protobuf` next time."

**Comment by nathanielmanistaatgoogle** [comment]
In https://grpc-testing.appspot.com/job/gRPC_pull_requests/3484/ I'm seeing a tool failure during build. Looking at others...

**Comment by ctiller** [comment]
No.
Leave this open until we have a way of making this robust.

We can talk about changing the priority, but "just keep retrying until it works" is no longer ok.

**Comment by nathanielmanistaatgoogle** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3488/config=opt,language=python,platform=linux/console is another tool failure, but not in the same place and potentially not the same tool...

@ctiller, do you have a set of failures already collected or should we just be pulling recent results from gRPC_master and gRPC_pull_requests?

**Comment by ctiller** [comment]
I don't have any such collection currently.

**Comment by soltanmm** [comment]
@ctiller Alright.
@nathanielmanistaatgoogle Both of the failures you've linked so far are pip tripping over itself. Whatever is happening, the Jenkins machine has bad connectivity to the upstream distributions.

**Comment by nathanielmanistaatgoogle** [comment]
I agree with @ctiller that we can't just say "tool failure; won't fix". I'm loathe to contemplate checking all our dependencies into source control just so that we can avoid network use during build, but if we're not able to reliably download our dependencies from PyPI, we might have to. I'd like to think of other options, and it might be nice to have numbers on how often PyPI fails for us during builds.

**Comment by ctiller** [comment]
Is it possible to mirror the needed dependencies?

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: I believe so, but then it's one more part of build infrastructure to maintain. It's an option, it's unattractive, but I'm open to the possibility that it may be the least unattractive option and thus something we do.

**Comment by ctiller** [comment]
Let's brainstorm for at least a little while here.

Ideas I can think of:
- drop dependencies entirely
- mirror dependencies within our build environment
- mirror dependencies within our revision control

@nicolasnoble may have thoughts also.

**Comment by ctiller** [comment]
Re-opening since flaky downloads still needs some support.

**Comment by soltanmm** [comment]
@nicolasnoble Which of our downloads are still flaking, if any?

**Comment by soltanmm** [comment]
@ctiller @nicolasnoble What are the symptoms of this that we want to have fixed somewhere between now and soon?

**Comment by ctiller** [comment]
Stability seems good lately
