### ISSUE TITLE
Double free crash in grpc_byte_buffer_destroy

### ISSUE THREAD

**Issue by mayuehit** [grpc/grpc#36346]
### What version of gRPC and what language are you using?
C++  grpc-1.41 

### What operating system (Linux, Windows,...) and version?
Linux centos7

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc-9.3.0

### What did you do?
I use grpc stream:: grpc:: ServerReaderWriter, which acts as a server. The service logic is to invoke Read() in one thread to read the stream sent by the client and invoke Write() in another thread to write the stream to the client. For some reason, the client has an OOM (process hang). As a result, the server triggers the double-free coredump

### What did you expect to see?
After the client breaks down, the server does not trigger double free.

### What did you see instead?
Double free occurs on the server, which is rare and difficult to reproduce.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
#0  0x00007fda43013337 in raise () from /lib64/libc.so.6
#1  0x00007fda43014a28 in abort () from /lib64/libc.so.6
#2  0x00007fda43055e87 in __libc_message () from /lib64/libc.so.6
#3  0x00007fda4305e679 in _int_free () from /lib64/libc.so.6
#4  0x00007fda42a435f5 in grpc_byte_buffer_destroy () from libgrpc.so.19
#5  0x00007fda4471c421 in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallNoOp<3>, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::FinalizeResult(void**, bool*) ()
   from libgrpc++.so.1.41
#6  0x00007fda453b412b in grpc::CompletionQueue::Pluck(grpc::internal::CompletionQueueTag*) () from my.so
#7  0x00007fda4540c5a7 in ?? () from my.so
#8  0x00007fda4541dca8 in ThreadPool::Work() () from my.so
#9  0x00007fda439926c0 in execute_native_thread_routine () at /opt/gcc-9.3.0/libstdc++-v3/src/c++11/thread.cc:80
#10 0x00007fda454b4e65 in start_thread () from /lib64/libpthread.so.0
#11 0x00007fda430db88d in clone () from /lib64/libc.so.6
See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Not yet.

**Comment by eugeneo** [comment]
This does not seem to be easily reproducible, at least not with a recent gRPC version.

Please update to an actively maintained gRPC version to confirm the issue.

**Comment by mayuehit** [comment]
> This does not seem to be easily reproducible, at least not with a recent gRPC version.
> 
> Please update to an actively maintained gRPC version to confirm the issue.

Can you guess what's going on from the stack?

**Comment by eugeneo** [comment]
No, this requires debugging the running system.

**Comment by mayuehit** [comment]
Thanks, I have found the cause of the problem.

**Comment by mayuehit** [comment]
Close the issue because the issue has been resolved.
