### ISSUE TITLE
build failed in src/core/lib/surface/call.cc

### ISSUE THREAD

**Issue by willendzw** [grpc/grpc#36421]
[ 14%] Building CXX object CMakeFiles/grpc_unsecure.dir/src/core/lib/surface/call.cc.o
during RTL pass: expand
/home/bcmwrt/data/wd/tensorflow/grpc/src/core/lib/surface/call.cc: In constructor ‘grpc_core::{anonymous}::MaybeOpImpl<SetupFn>::MaybeOpImpl(grpc_core::{anonymous}::MaybeOpImpl<SetupFn>&&) [with SetupFn = grpc_core::ServerCallSpine::CommitBatch(const grpc_op*, size_t, void*, bool)::<lambda(const grpc_op&)>]’:
/home/bcmwrt/data/wd/tensorflow/grpc/src/core/lib/surface/call.cc:3871:55: internal compiler error: in assign_temp, at function.c:982
 3871 |       : state_(MoveState(other.state_)), op_(other.op_) {}
      |                                                       ^
0x7fd74ab1f082 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/grpc_unsecure.dir/build.make:4034: CMakeFiles/grpc_unsecure.dir/src/core/lib/surface/call.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1248: CMakeFiles/grpc_unsecure.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by willendzw** [comment]
latest code.

**Comment by eugeneo** [comment]
Please provide more information, including you OS, target platform and compiler. It looks like the problem is an internal compiler error and is caused with something on your machine.

**Comment by lansekuangxiang** [comment]
> [ 14%] Building CXX object CMakeFiles/grpc_unsecure.dir/src/core/lib/surface/call.cc.o during RTL pass: expand /home/bcmwrt/data/wd/tensorflow/grpc/src/core/lib/surface/call.cc: In constructor ‘grpc_core::{anonymous}::MaybeOpImpl::MaybeOpImpl(grpc_core::{anonymous}::MaybeOpImpl&&) [with SetupFn = grpc_core::ServerCallSpine::CommitBatch(const grpc_op*, size_t, void*, bool)::<lambda(const grpc_op&)>]’: /home/bcmwrt/data/wd/tensorflow/grpc/src/core/lib/surface/call.cc:3871:55: internal compiler error: in assign_temp, at function.c:982 3871 | : state_(MoveState(other.state_)), op_(other.op_) {} | ^ 0x7fd74ab1f082 __libc_start_main ../csu/libc-start.c:308 Please submit a full bug report, with preprocessed source if appropriate. Please include the complete backtrace with any bug report. See file:///usr/share/doc/gcc-9/README.Bugs for instructions. make[2]: *** [CMakeFiles/grpc_unsecure.dir/build.make:4034: CMakeFiles/grpc_unsecure.dir/src/core/lib/surface/call.cc.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:1248: CMakeFiles/grpc_unsecure.dir/all] Error 2 make: *** [Makefile:171: all] Error 2

I have got a simular error using gcc-9 compiler, but gcc-10 works. You should upgrade your gcc compiler.
