### ISSUE TITLE
Release grpc 1.63.0 on Rubygems 

### ISSUE THREAD

**Issue by ngan** [grpc/grpc#36464]
Hi, just in a polite request to please release [grpc 1.63.0](https://github.com/grpc/grpc/releases/tag/v1.63.0) on Rubygems. The Ruby fix in that version is required for us to upgrade to Ruby 3.3.1. 🙇 

- https://github.com/grpc/grpc/pull/36125

**Comment by stanhu** [comment]
@yijiem Do you know what's holding up the publishing of the Ruby gem for this release? I see this was tagged 3 days ago.

**Comment by technicalpickles** [comment]
Is the rubygem release automated? I tried looking for what triggers it, but failed to find it.

**Comment by jonyscathe** [comment]
1.63.0 was never published to PyPI either

**Comment by technicalpickles** [comment]
I checked on https://rubygems.org/gems/grpc/versions and there haven't been any ruby release since 1.62.0, so we are missing releases for:

- 1.61.2 
- 1.62.1
- 1.62.2
- 1.63.0

**Comment by stanhu** [comment]
@yashykt @veblush Could one of you help here? Thanks.

**Comment by technicalpickles** [comment]
I _think_ I've found where Ruby and Python packages are built:

- https://github.com/grpc/grpc/blob/0281c0a564a33fa2445724fee21a0f2634793051/tools/run_tests/artifacts/build_artifact_ruby.sh
- https://github.com/grpc/grpc/blob/0281c0a564a33fa2445724fee21a0f2634793051/tools/run_tests/artifacts/build_artifact_python.sh

I traced those to getting used by:

- https://github.com/grpc/grpc/blob/0281c0a564a33fa2445724fee21a0f2634793051/tools/run_tests/artifacts/artifact_targets.py#L110
- https://github.com/grpc/grpc/blob/0281c0a564a33fa2445724fee21a0f2634793051/tools/run_tests/artifacts/artifact_targets.py#L245
- https://github.com/grpc/grpc/blob/0281c0a564a33fa2445724fee21a0f2634793051/tools/run_tests/artifacts/artifact_targets.py#L390

I haven't found what uses these `targets` though, and I haven't found anything that publishes. For Ruby at least, I'd expect a `gem push` somewhere to publish to rubygems.org.

**Comment by Vagab** [comment]
> I haven't found what uses these targets though
seems to be called from [here](https://github.com/grpc/grpc/blob/76c93769e2fbf28ac8b7d9b4a69598691e396e53/tools/run_tests/task_runner.py#L23)

**Comment by ngan** [comment]
Good news, everyone! 1.63.0 was just released on Rubygems: https://rubygems.org/gems/grpc

I would awesome if we can automate the Ruby release process so that it just happens when a release is tagged on GitHub. 🙏
