### ISSUE TITLE
Ruby auth interop tests use illegal header key

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3648]
```
E1006 17:46:51.316293735       1 call.c:1036]                attempt to send invalid metadata key: Authorization
```

This is most likely because C core prohibits metadata keys with capital letters.  s/Authorization/authorization/

**Comment by jtattermusch** [comment]
Also see #3671

**Comment by murgatroid99** [comment]
It looks like the Ruby auth library emits metadata keys with capital letters. So the solution here is to either modify the auth library to not do that, or to normalize metadata keys in this library. @tbetbetbe, what do you think?

**Comment by jtattermusch** [comment]
I think we should normalize in gRPC ruby. While normalizing the key, we should also check for prohibited characters and provide a more user-friendly early failure (currently the rpc call gets stuck).

**Comment by murgatroid99** [comment]
Currently, the issue for dealing with that on the gRPC Ruby side is #3154.

**Comment by jtattermusch** [comment]
Still seeing the original issue for per_rpc_creds test.
```
E1006 17:46:51.316293735       1 call.c:1036]                attempt to send invalid metadata key: Authorization
```
