### ISSUE TITLE
deadlock in grpc c++ server

### ISSUE THREAD

**Issue by qnik2** [grpc/grpc#36609]
### What version of gRPC and what language are you using?
c++
abseil: 20230802.0
grpc: 1.56.2
protobuf-c: 1.4.1

### What operating system (Linux, Windows,...) and version?
Yocto Kirkstone / Linux Kernel 5.15

### What runtime / compiler are you using (e.g. python version or version of gcc)
aarch64-dey-linux-cpp (GCC) 11.4.0
Python 3.10.13

### What did you do?
```
service PowerButton {
  rpc listenForKeyEvents ( google.protobuf.Empty ) returns ( stream KeyEvent) {}
  rpc cancelPowerOff ( google.protobuf.Empty) returns ( google.protobuf.Empty) {}
}
```

I implemented a CallBack Service with a long lived stream rpc, listening for key events.
```
grpc::ServerWriteReactor<peripheral::KeyEvent>* McaPwrBtnService::listenForKeyEvents( ::grpc::CallbackServerContext* ctx, const ::google::protobuf::Empty*)
{

    static std::atomic_int s_listenerCnt = 0;

    class Listener : public grpc::ServerWriteReactor<peripheral::KeyEvent> {

        McaPwrBtnListener mcaPwrBtnListener_;
        ::peripheral::KeyEvent keyEvent_;
        McaPwrBtnService& owner_;
        ::grpc::CallbackServerContext* ctx_ = nullptr;

    public:
        Listener( McaPwrBtnService& o, ::grpc::CallbackServerContext* ctx)
            :owner_(o)
            ,ctx_( ctx)
        {
            ++s_listenerCnt;
            /*  s_listenerCnt:
                prevent more than 1 listenForKeyEvents rpc's since this, results in a broken server
                this is a workaround for: https://github.com/grpc/grpc/issues/36551
            */
            /* uncomment for now, since I still try to find the root cause of this issue
            if( s_listenerCnt > 1){
                DLOG(INFO) << "Listener::ctor(" << ctx_ << ") exceeded max count" << s_listenerCnt;
                Finish( grpc::Status::CANCELLED);
                return;
            }
            */
            DLOG(INFO) << "Listener::ctor(" << ctx_ << ")";
            NextWrite();
        }

        virtual ~Listener()
        {
            --s_listenerCnt;
            DLOG(INFO) << "Listener(" << ctx_ << ")::dtor";
        }
        virtual void OnWriteDone(bool ok) {
            DLOG(INFO) << "Listener(" << ctx_ << ")::OnWriteDone: " << ok;
            if( ok){
                NextWrite();
            }else{
                Finish( grpc::Status::CANCELLED);
            }
        }
        void OnDone() override {
            DLOG(INFO) << "Listener(" << ctx_ << ")::OnDone";
            delete this;
        }
        void OnCancel() override {
            DLOG(INFO) << "Listener(" << ctx_ << ")::OnCancel";
            Finish( grpc::Status::CANCELLED);
        }

    private:
        void NextWrite() {
            McaPwrBtnDev::KeyEvent evnt;
            for(;;){
                //DLOG(INFO) << "Listener::NextWrite ctx=" << ctx_;
                if( mcaPwrBtnListener_.waitKeyEvent( evnt, 333)){
                    switch( evnt.code_){
                        case 116:
                            keyEvent_.set_code( peripheral::KeyEvent::POWER );
                            break;
                        case 142:
                            keyEvent_.set_code( peripheral::KeyEvent::SLEEP );
                            break;
                        default:
                            break;
                    }
                    keyEvent_.set_value( evnt.value_ == 1 ? peripheral::KeyEvent::DOWN : peripheral::KeyEvent::UP);
                    StartWrite( &keyEvent_);
                    return;

                }else{

                    if( ctx_->IsCancelled()){
                        DLOG(INFO) << "Listener(" << ctx_ << ")::NextWrite Cancelled";
                        return;
                    }
                    if( owner_.finishStreams()){
                        DLOG(INFO) << "Listener(" << ctx_ << ")::NextWrite finishStreams";
                        Finish( grpc::Status::CANCELLED);
                        return;
                    }
                }
            }
        }
    };
    return new Listener( *this, ctx);
}
```

### What did you expect to see?
dynamic number of clients listening for key events (comming and going)

### What did you see instead?
When more then two clients call "listenForKeyEvents" the server is in kind of dead lock state.
He doesn't get notified on any incoming tcp data.

If the server is running on my PC (Windows/Linux) , up to 4 clients can simultaneously call "listenForKeyEvents"
On my target platform only up to 2 clients can simultaneously call "listenForKeyEvents"

### Reason 
Finally (took lots of investigation time) I found the reason for the different behavior, between the platforms:

grpc/src/cpp/common/completion_queue_cc.cc:56
```
      int num_nexting_threads =
          grpc_core::Clamp(gpr_cpu_num_cores() / 2, 2u, 16u);
```
The value of "num_nexting_threads" is related to number of CPU cores.
My PC has 8 Cores, but my aarm64 yocto target has only 4 cores.

The problem actually is, that each "listenForKeyEvents" rpc consumes one "nexting_thread"
```
class McaPwrBtnService final : public peripheral::PowerButton::CallbackService {
    virtual ::grpc::ServerWriteReactor< ::peripheral::KeyEvent>* listenForKeyEvents( ::grpc::CallbackServerContext*, const ::google::protobuf::Empty* ) override;
};
```

Once all nexting_threads are consumed, the grpc server doesn't react on tcp messages any more!

See also: #36551 and maybe #2423

### Solution ???
Is my implementation wrong? For me it looks more likely a bug...
Any help is very much appreciated

**Comment by yashykt** [comment]
With the callback API, it is illegal to do a blocking operation with the threads that the EventEngine is using to poll the fds. I took a quick look at the code and I did not immediately spot the blocking operation, but from your description, it sounds like that's the case.

**Comment by drfloob** [comment]
@yashykt To clarify (and for posterity), these aren't EventEngine threads, these are callback nexting threads (which are going away soon). Blocking is still the incorrect application behavior for performance reasons, but the thread starvation won't happen after the EE callback API migration is done.

**Comment by qnik2** [comment]
Thanks so much for your comments

@yashykt
You are correct, NextWrite is actually blocking, until the powerkey was pressed (can last forever) or the client was cancelled.
Are you telling me, that the correct API for this kind of application is the Async API?

Somehow I got the impression, that the Callback API is a more convenient/modern, but full replacement for the Async API.
Unfortunately, documentation is very poor.

@drfloob
Can you please explain "EE callback API" ?

**Comment by drfloob** [comment]
I mentioned the "EE callback API *_migration_*". It's not relevant for you in this problem, I commented more for other gRPC core maintainers who find this bug in the future. (In short, we're replacing low-level gRPC internals with something called the [EventEngine](https://github.com/grpc/grpc/blob/master/include/grpc/event_engine/event_engine.h). Unifying all internal thread pools will make the callback API more efficient. The callback API currently uses non-EventEngine threads, which behave differently.)

For your case, you're going to want to offload blocking work to some other thread.

**Comment by qnik2** [comment]
@drfloob Thank you very much. I did as you proposed and no deadlocks anymore.
I guess StartWrite is thread safe.

One last question: 
Am I right in assuming that the Callback interface is therefore preferable to the Async interface for my application?

**Comment by yashykt** [comment]
Yeah, we've been the recommending use of the callback API over the async cq based API
