### ISSUE TITLE
Python asyncio servicer context invocation_metadata returns a tuple instead of Metadata

### ISSUE THREAD

**Issue by artificial-aidan** [grpc/grpc#36613]
### What version of gRPC and what language are you using?

Python 3.11 grpcio 1.63.0

### What operating system (Linux, Windows,...) and version?

OSX 10.14

### What runtime / compiler are you using (e.g. python version or version of gcc)

3.11

### What did you do?

Created a python asyncio server. Called `invocation_metadata` and had a `tuple` returned

```
    async def UnaryUnary(self, request: Request, context: grpc.aio.ServicerContext) -> Response:  # noqa: N802
        md = context.invocation_metadata()
        if isinstance(md, grpc.aio.Metadata):
            print('hello')
        type(md) # returns tuple
```

### What did you expect to see?

`invocation_metadata` to return a `grpc.aio.Metadata` object like the type hint suggests

**Comment by gnossen** [comment]
Thanks for pointing this out! This does indeed seem to be an unintentional discrepancy. In order to minimize the impact of a fix here, I think the right thing to do is to change the _type_ to match the implementation rather than the other way around.

**Comment by artificial-aidan** [comment]
That's definitely a bit of a bummer. But makes sense. It would be quite the breaking change to change the return type. Is there any precedence for adding a differently named method that returns metadata, or as a fuction parameter.

**Comment by gnossen** [comment]
No precedent, but it's definitely something that could be discussed. We definitely verbally discussed something like `invocation_metadata2` when reviewing this issue. Though adding a whole new method would be a bit of a bigger effort (gRFC, implementation, testing, and documentation). I think we'd need someone to volunteer to pitch in to make something like that happen.

**Comment by artificial-aidan** [comment]
Its a lot of effort for something that can be fixed with a one-liner turning it into metadata again.

I think fixing the typing would solve 90% of the problem

**Comment by iamWing** [comment]
Was about to report this issue as well. Yes I agree with @gnossen that I wouldn't want to see a fix that changes the return type, as it'd break the current code base I have (which I do `dict(context.invocation_metadata())` to convert it to a dictionary to allow me using the `.get` function for getting a specific metadata). Something like `invocation_metadata2` would be welcome as it means that I can gradually migrate to the new function instead of having to deal with the breaking change all at once.

**Comment by sreenithi** [comment]
the above PR should have updated the invocation_metadata() return type. Hence closing the issue

**Comment by artificial-aidan** [comment]
This has now created another issue. Because `MetadataType` is not exported, it's impossible to type things that expect the return value of `invocation_metadata`, can we export `MetadataType`?
