### ISSUE TITLE
Wrong memory allocation size for string copy at load_balancer_api.cc

### ISSUE THREAD

**Issue by apach301** [grpc/grpc#36610]
Hi,
I found a wrong memory allocation during a string copy with Svace static analyzer.

During a string copy in `GrpcLbLoadReportRequestCreate()` the result of `strlen` is used to allocate memory, but it is not count a null terminating symbol:
https://github.com/grpc/grpc/blob/15850972ddba9c1262a9d51341da03bc607bd934/src/core/load_balancing/grpclb/load_balancer_api.cc#L107-L109

**Comment by markdroth** [comment]
The existing code is correct.  As you can see in your PR, the tests fail with the proposed change.
