### ISSUE TITLE
Getting unexpected string in grpc::Status error_message after broken Connection

### ISSUE THREAD

**Issue by Bernd-Tinkl-ASCONA** [grpc/grpc#36623]
### What version of gRPC and what language are you using?
grpc v1.46 with c++

### What operating system (Linux, Windows,...) and version?
windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019 with platform toolset v140

### What did you do?
I startet my client and server. I implemented a simple call which blocks for 5 minutes using a sleep() in the Server. When I see the outgoing and incomming call in the Server, I kill the Server.
After that the Call in the Server returns and Status is set tu UNKNOWN, but the error text contains an String which seems to be currupt.

![image](https://github.com/grpc/grpc/assets/169903800/720112fc-a02f-416a-9289-185a719c6460)

Code fragment in the Server:
![image](https://github.com/grpc/grpc/assets/169903800/25161877-3558-4fd8-adda-d735a6d6bb7c)

The makro TRACE_GRPC_CLIENT_RESULT_CYCLIC_EX prints out an error if the Status is not ok using folllowing code

![image](https://github.com/grpc/grpc/assets/169903800/777402dd-ba18-4624-a149-da7a63686229)

![image](https://github.com/grpc/grpc/assets/169903800/b99db8f3-32ff-4422-9922-c7fcee411728)

### What did you expect to see?
The error_message should contain a well formed string.

### What did you see instead?

![image](https://github.com/grpc/grpc/assets/169903800/720112fc-a02f-416a-9289-185a719c6460)

### Anything else we should know about your project / environment?
Is there any better way to detect and handle a broken connection? Up to now we test the returned grpc::Status of the called functions.

**Comment by drfloob** [comment]
I suspect memory corruption somewhere in your application. Consider building your binary with `/fsanitize=address` and see if that's more informative. This sort of thing is hard for others to debug without a minimal application that reproduces the problem, preferably uploaded to github somewhere. Often, when trying to create a min-repro, you'll find the bug that's causing your problem.

Also, v1.46 is 2 years old, please consider using a more up-to-date library.
