### ISSUE TITLE
fatal error C1090 : CMake build error on windows

### ISSUE THREAD

**Issue by sathishk-r** [grpc/grpc#36634]
### What version of gRPC and what language are you using?
using v1.60.0, C++ language

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC

### What did you do?
Building gRPC v#1.60.0 for windows using cmake. I am able to build for the release configuration, Debug configuration is failing.

### What did you expect to see?
expected debug libraries are built without any issue. 

### What did you see instead?
cmake build is failing, issue is not consistent with the same file, it is randomly happening at different files with the same error. 
third_party\re2\re2\regexp.cc : **fatal error C1090:** PDB API call failed, error code '5':
proto_parser_helper.cc : **fatal error C1090**: PDB API call failed, error code '5':

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
We've got debug builds on windows that are tested with CI.

In your specific case, it looks like an environment setup issue. I don't have a clear solution for you but you can try the steps at https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1090?view=msvc-170.

Previously I've also run into issues on windows with parallel builds, so removing the `-j` or equivalent option might do the trick for you.

Also, take a look at https://github.com/grpc/grpc/blob/master/tools/run_tests/helper_scripts/build_cxx.bat for how we setup our builds for windows.
