### ISSUE TITLE
Inconsistency between flag object and registration for flag 'grpc_experiments' due to config_vars.cc

### ISSUE THREAD

**Issue by mocsharp** [grpc/grpc#36648]
### What version of gRPC and what language are you using?
1.54.2, 1.63.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04.4 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
- cmake version 3.29.2
- gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
The application runs without any errors.

### What did you see instead?
```
ERROR: Inconsistency between flag object and registration for flag 'grpc_experiments', likely due to duplicate flags or an ODR violation. Relevant files: home/user/sc/github/grpc/src/core/lib/config/config_vars.cc and /opt/grpc/src/src/core/lib/config/config_vars.cc
```

### Anything else we should know about your project / environment?

My application links to another library that embeds a gRPC server; both the library and my application build the gRPC C++ library as part of the Cmake build process. 

I compared the two `config_vars.cc` files from the two builds (source of the other library is on Github) and they appeared to be the same. So am confused why the application crashes with the error.

**Comment by veblush** [comment]
> My application links to another library that embeds a gRPC server; both the library and my application build the gRPC C++ library as part of the Cmake build process.

This is an ODR violation so you may wan to fix that issue.

**Comment by mocsharp** [comment]
@veblush, would you be able to provide more insight? Thanks.

**Comment by GuangyunWang** [comment]
> @veblush, would you be able to provide more insight? Thanks.
> 
> Edit: is it impossible to have another gRPC server if a linked library already hosts a gRPC server? Is the workaround to have the existing library expose the gRPC libs so the users of that library can stand up another gRPC server?
> 
> Thanks.

I have been troubled with the same problem,  in the version 1.63.0,. Frist, I doubt that the installation is error, then I reinstalled it, the problem seams sloved, not crashed, but after few hours' program debug, the problem occurs again.  Have you solve the problem, Can you tell how to solve this problem?

**Comment by mocsharp** [comment]
No luck for us either.

We reconfigured our SDK to put the built gRPC headers and library as a third-party package and then rebuilt the client's application based on it, which resulted in a different error:

```
ERROR: Something is wrong with flag 'grpc_experiments' in file 'opt/grpc/src/src/core/lib/config/config_vars.cc'. One possibility: file 'opt/grpc/src/src/core/lib/config/config_vars.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.
```

We use cmake for the SDK and the client's application with the same instructions to link.

@markdroth @veblush, any advice would be greatly appreciated. Thanks.

**Comment by GuangyunWang** [comment]
> No luck for us either.
> 
> We reconfigured our SDK to put the built gRPC headers and library as a third-party package and then rebuilt the client's application based on it, which resulted in a different error:
> 
> ```
> ERROR: Something is wrong with flag 'grpc_experiments' in file 'opt/grpc/src/src/core/lib/config/config_vars.cc'. One possibility: file 'opt/grpc/src/src/core/lib/config/config_vars.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.
> ```
> 
> We use cmake for the SDK and the client's application with the same instructions to link.
> 
> @markdroth @veblush, any advice would be greatly appreciated. Thanks.

Hello guy,
   I try delete all compiler and link caches of my program(cmake and make  files) include local and remote meachine, then rebuild all program, the error is disappeared. I use CLion to remote debug my program to remote server, maybe some program compiler or link cache cause this error. If you still face this error, maybe you can try it.

**Comment by zihuyishi** [comment]
> No luck for us either.
> 
> We reconfigured our SDK to put the built gRPC headers and library as a third-party package and then rebuilt the client's application based on it, which resulted in a different error:
> 
> ```
> ERROR: Something is wrong with flag 'grpc_experiments' in file 'opt/grpc/src/src/core/lib/config/config_vars.cc'. One possibility: file 'opt/grpc/src/src/core/lib/config/config_vars.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.
> ```
> 
> We use cmake for the SDK and the client's application with the same instructions to link.
> 
> @markdroth @veblush, any advice would be greatly appreciated. Thanks.

so do your resolve it? I have same error.
compile grpc as static library and make is as a deb. 
compile and run, then got error: 
"Something is wrong with flag 'grpc_experiments' in file 'home/grpc/src/core/lib/config/config_vars.cc'. One possibility: file 'home/grpc/src/core/lib/config/config_vars.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test"

**Comment by JKRhb** [comment]
In my case, it helped to declare `grpc::GRPC++` and `protobuf::libprotobuf` as `PRIVATE` when referring to them within `target_link_libraries` in the `CMakeLists.txt` file they are being used as dependencies in. This way, they are excluded from the library's link interface, getting rid of the error.

**Comment by ko80** [comment]
I had this issue in a unit test app (gtest) which took all source files from the repo and linked them with gtest and gtest_main. The repo contained two different apps, both had gRPC lib linked. As a result, the unit test executable was linked to gRPC lib twice. That's the root cause.

The solution for that was to split unit tests into two parts, each dedicated to the particular app in the repo.
