### ISSUE TITLE
grpc 1.55 throughput drop when server saturated

### ISSUE THREAD

**Issue by yuanyuanJ** [grpc/grpc#36692]
### What version of gRPC and what language are you using?
grpc 1.55, C++

### What operating system (Linux, Windows,...) and version?
RHEL7

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc8

### What did you do?
We have been working on a pub/sub project using gRPC in C++, we are publish messages to gRPC server with unary RPC, and receive the message with server streaming RPC call. We implement the server with **cq-based async** way, just like the qps test server in grpc repo, and the client will issue the unary RPC with a fix interval. We run the test on a 48 core server machine with CPU E5-2650 2.20gHZ
The code I use is here:
[perf_test.zip](https://github.com/grpc/grpc/files/15397428/perf_test.zip)

### What did you expect to see?
The throughput should become flat when the server saturated.

### What did you see instead?
We have seen a wired performance result with throughput: there will be a performance drop when we increase the client RPC issue rate:
![图片1](https://github.com/grpc/grpc/assets/143795104/a30635e0-daad-4f8f-9ec1-0f1579e30ddb)

This drop happens with "default-executor" starts to occupy CPU time and make our cq processing thread CPU utilization down. Is it a problem in grpc/core with "default-executor" threads?
This is the CPU utils where no drop happens:
![rps_50k](https://github.com/grpc/grpc/assets/143795104/e67f9d45-1ce0-4610-b11c-145a6890332c)

This is the CPU utils where drop happens:
![rps_50k_2](https://github.com/grpc/grpc/assets/143795104/8d312f76-450c-422f-9afb-237666d569dc)

**P.S.** we are aware that gRPC has deco the "default-executor" and use "Event-Engine" in the latest version, but we cannot get the same performance result using the latest gRPC version with Event Engine.

**Comment by yashykt** [comment]
All our latest performance efforts are targeted towards the C++ callback API. Please try using that. Also, as a side-note, we are making some performance optimizations to our stack that is gonna result slightly worse performance in the short term, but we'll soon see much better performance.
