### ISSUE TITLE
Compilation errors when targeting C++23

### ISSUE THREAD

**Issue by rLinks234** [grpc/grpc#36804]
### What version of gRPC and what language are you using?

gRPC version `1.62.1`
C++, targeting `C++23`

### What operating system (Linux, Windows,...) and version?

Fedora 40

### What runtime / compiler are you using (e.g. python version or version of gcc)

`clang` that comes standard on Fedora 40 (18.1.6):

```sh
>>> clang --version
clang version 18.1.6 (Fedora 18.1.6-3.fc40)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang.cfg
```

### What did you do?

I imported `gRPC` targeting version `1.62.1` within a bazel project, which was the newest version available on Bazel Registry at the time of submitting this ticket. Compilation worked just fine until I targeted `c++23` instead of `c++20` within my toolchain (_e.g._, `-std=c++23`).

### What did you expect to see?

Working compilation

### What did you see instead?

Compilation error:

```
ERROR: <redacted>/external/grpc~/BUILD:1287:16: Compiling src/core/lib/surface/server.cc failed: (Exit 1): clang failed: error executing CppCompile command (from target @@grpc~//:grpc_base) <snip/>

In file included from external/grpc~/src/core/lib/surface/server.cc:19:
In file included from external/grpc~/src/core/lib/surface/server.h:29:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/memory:78:
/usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:91:16: error: invalid application of 'sizeof' to an incomplete type 'grpc_core::Server::RequestMatcherInterface'
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:398:4: note: in instantiation of member function 'std::default_delete<grpc_core::Server::RequestMatcherInterface>::operator()' requested here
  398 |           get_deleter()(std::move(__ptr));
      |           ^
external/grpc~/src/core/lib/surface/server.cc:93:3: note: in instantiation of member function 'std::unique_ptr<grpc_core::Server::RequestMatcherInterface>::~unique_ptr' requested here
   93 |   RegisteredMethod(
      |   ^
external/grpc~/src/core/lib/surface/server.h:214:9: note: forward declaration of 'grpc_core::Server::RequestMatcherInterface'
  214 |   class RequestMatcherInterface;
      |         ^
1 error generated.
```

### Anything else we should know about your project / environment?

This issue was discovered when using Clang - GCC works just fine.

A smaller reproducible example of this issue can be found at this godbolt link, showing how compiliation is fine with GCC irrespective of C++ version targeted and fine with clang targeting `c++20`: https://godbolt.org/z/Pc9rGfadn

It appears that the code fails to compile due to not being compliant with C++23 `std::unique_ptr`: https://github.com/llvm/llvm-project/issues/74963#issuecomment-1850834221

**Comment by rLinks234** [comment]
In particular, the inner struct `Server::RegisteredMethod` encapsulates a unique ptr to inner struct `Server::RequestMatcherInterface`, the latter of which is defined later in the translation unit:

The latter unique_ptr [is used here, line 109](https://github.com/grpc/grpc/blob/v1.62.x/src/core/lib/surface/server.cc#L109), whereas the actual inner class is defined [later here, line 125](https://github.com/grpc/grpc/blob/v1.62.x/src/core/lib/surface/server.cc#L125)

**Comment by cyaneous** [comment]
Seeing this as well.

**Comment by gorloffslava** [comment]
Observe the same with the forward declaration of `RegisteredMetricCallback` in https://github.com/grpc/grpc/blob/v1.65.0/src/core/telemetry/metrics.h:
1. Line 270: forward declaration https://github.com/grpc/grpc/blob/v1.65.0/src/core/telemetry/metrics.h#L270
2. Line 466: std::make_inique is called on incomplete type https://github.com/grpc/grpc/blob/v1.65.0/src/core/telemetry/metrics.h#L466
3. Line 530: actual definition https://github.com/grpc/grpc/blob/v1.65.0/src/core/telemetry/metrics.h#L530

**Comment by BwL1289** [comment]
Seeing this as well.

**Comment by yashykt** [comment]
This should be fixed in https://github.com/grpc/grpc/pull/35957
