### ISSUE TITLE
Sanity test fails on some builds

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3686]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/config=gcov,language=sanity,platform=linux/3550/console

I'm suspecting this is due to configuration on some workers - it's a shared library that docker uses that's failing to be loaded.

**Comment by nicolasnoble** [comment]
That's... odd ? Is this trying to do docker-on-docker by any chance ? I think it does. We shouldn't try running docker-in-a-docker.

**Comment by soltanmm** [comment]
[But it'd be hilarious.](https://blog.docker.com/2013/09/docker-can-now-run-within-docker/)

**Comment by ctiller** [comment]
Not docker-in-docker, but docker-from-docker. Different thing right.

Would prefer to keep it to decouple clang-format from what's in the Jenkins
docker image (changing clang-format versions is a big impactful event on
every source file we have).

**Comment by nicolasnoble** [comment]
So... I think what we want to do is to have two separate steps for sanity in run_tests.

The first one calls tools/run_tests/run_sanity.sh. And we remove ./tools/distrib/clang_format_code.sh from run_sanity.sh.

The second one is ./tools/distrib/clang_format_code.sh, and should have a flag or something that says to NOT run it from within Docker, even if the use_docker option is set.

Does that sound right ?

**Comment by ctiller** [comment]
Sounds like it'll probably work. We need the TEST env var set for
clang_format_code to do its thing.

**Comment by murgatroid99** [comment]
Continues to happen: https://grpc-testing.appspot.com/job/gRPC_master/7951/config=opt,language=sanity,platform=linux/console

**Comment by ctiller** [comment]
Closing due to the fix being in.
