### ISSUE TITLE
GRPC libraries compiled for android give undefined symbol stderr

### ISSUE THREAD

**Issue by RubenGarcia** [grpc/grpc#36882]
<!--
### What version of gRPC and what language are you using?
v1.64.0, C++

### What operating system (Linux, Windows,...) and version?
Android 31, ndk 23b

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang from Android SDK

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

- Compile grpc using the following github action (see grpc-workflow-unity.yaml, renamed to txt for upload)
- [grpc-workflow-unity.txt](https://github.com/user-attachments/files/15787592/grpc-workflow-unity.txt)
- Use the library in an unity project, see https://github.com/RubenGarcia/GRPCCPPAndroidIssue
- See specifically in grpc.cs
```
[DllImport("__Internal")]
private static extern void grpc_init();
```
- Compile for android ARM64
### What did you expect to see?
Unity compiles the program and generates an apk file.

### What did you see instead?
Building Library\Bee\artifacts\Android\d8kzr\libil2cpp.so failed with output:
ld.lld: error: undefined symbol: stderr
>>> referenced by re2.cc
>>>               re2.cc.o:(LogMessage::Flush()) in archive Assets/GRPC_CPP_Libraries/libre2.a
>>> referenced by re2.cc
>>>               re2.cc.o:(LogMessage::Flush()) in archive Assets/GRPC_CPP_Libraries/libre2.a
>>> referenced by bcm.c
>>>               bcm.c.o:(wait_for_entropy) in archive Assets/GRPC_CPP_Libraries/libcrypto.a
>>> referenced 11 more times

### Anything else we should know about your project / environment?
Unity 2022.3.23, Android ARM64

I have notified unity about the issue, but I wanted to notify grpc also in case assistance in finding the exact issue causing the error is needed.

**Comment by RubenGarcia** [comment]
Github deleted the description, so here it is again:



### What version of gRPC and what language are you using?


### What operating system (Linux, Windows,...) and version?


### What runtime / compiler are you using (e.g. python version or version of gcc)


### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?


### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

**Comment by veblush** [comment]
It appears that it lacks C/C++ builtin functions which should be available to gRPC. I think this is more of how build was done. So I'm closing this.
