### ISSUE TITLE
Update ruby google-protobuf gem dependency to >= 3.25

### ISSUE THREAD

**Issue by colinbendell** [grpc/grpc#36891]
The `grpc` [gem depends on](https://github.com/grpc/grpc/blob/master/grpc.gemspec#L33) `google-protobuf ~> 3.25`. This approximately equal dependency prohibits major version jumps and parent projects aren't able to add dependencies using the 4.x series of `google-protobuf `(v4.27.1 is the latest).

Can we update the dependency to: 
```
spec.add_dependency 'google-protobuf', '>= 3.25', '< 5.0'
```

**Comment by alto-ruby** [comment]
fixed with 
#36982
#37169
