### ISSUE TITLE
c++ client not support real async

### ISSUE THREAD

**Issue by wkj827270243** [grpc/grpc#36924]
![image](https://github.com/grpc/grpc/assets/16694597/4c77d4b1-36de-465d-a3fe-3114410e7721)
block to recv message and recv status

**Comment by wkj827270243** [comment]
use c++ client , what i can do , for use real async
the way of callback is also blocking to recv message and recv status

**Comment by ctiller** [comment]
This looks like a documentation bug. The tag passed in will be posted to the completion queue when the given conditions are met, but the function will return immediately.

**Comment by andersas** [comment]
I suspect it's just a documentation bug as well. I have not had time to test it or read into the code. But it struck me as odd when I first read about async grpc clients today.

**Comment by markdroth** [comment]
@veblush, can you please find someone to fix the documentation here?  Thanks!

**Comment by andersas** [comment]
You guys are awesome, thanks for the quick clarification!

**Comment by andersas** [comment]
By the way, this tag, is that the same as the http2 flow label? If so, you should be careful about encouraging people to use memory addresses as tags, because a malicious server or man in the middle can control those.

**Comment by ctiller** [comment]
The tag never makes it to the wire. It's purely for the application to
identify which operation is completing.

**Comment by wkj827270243** [comment]
> This looks like a documentation bug. The tag passed in will be posted to the completion queue when the given conditions are met, but the function will return immediately.

ok，i have a test, the async is work, thanks everyone
