### ISSUE TITLE
Windows add_insecure_port failed

### ISSUE THREAD

**Issue by coyzeng** [grpc/grpc#36936]
### What version of gRPC and what language are you using?
1.64.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
python3.11

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
![image](https://github.com/grpc/grpc/assets/15525280/2ed9db1b-7393-4cb2-9197-38888bc6969d)

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
Please give us more information on how to reproduce this.
