### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple for gRPC C#

### ISSUE THREAD

**Issue by baihao** [grpc/grpc#36976]
### Is your feature request related to a problem? Please describe.
Currently gRPC provided the privacy manifest file for objc implementation, please refer to https://github.com/grpc/grpc/blob/master/src/objective-c/PrivacyInfo.xcprivacy, but the gRPC for C# did not include such a file. We are using the gRPC for c# nuget package to develop macOS app, not sure if the privacy manifest for gRPC for objc can also apply for the gRPC for C#.

### Describe the solution you'd like
A `PrivacyInfo.xcprivacy` for gRPC for C#

### Describe alternatives you've considered
A declaration that `PrivacyInfo.xcprivacy` for gPRC objc is also suitable for gRPC C# if it is true.

### Additional context
No

**Comment by tonydnewell** [comment]
Which version of gRPC C# are you using:
- the legacy version based on the c-core - NuGet `Grpc.Core` v2.46.x
- the gRPC for .NET version (see https://github.com/grpc/grpc-dotnet) - NuGet `Grpc.AspNetCore` and `Grpc.Net.Client` etc?

Neither support iOS etc, and as far as I understand `PrivacyInfo.xcprivacy` is only required for iOS, iPadOS, tvOS, visionOS, and watchOS. 

gRPC does not collect any information, so the `PrivacyInfo.xcprivacy` for objc would be sufficient, if you need it.

**Comment by baihao** [comment]
> Which version of gRPC C# are you using:
> 
>     * the legacy version based on the c-core - NuGet `Grpc.Core` v2.46.x
> 
>     * the gRPC for .NET version (see https://github.com/grpc/grpc-dotnet) - NuGet `Grpc.AspNetCore` and `Grpc.Net.Client` etc?
> 
> 
> Neither support iOS etc, and as far as I understand `PrivacyInfo.xcprivacy` is only required for iOS, iPadOS, tvOS, visionOS, and watchOS.
> 
> gRPC does not collect any information, so the `PrivacyInfo.xcprivacy` for objc would be sufficient, if you need it.

Hi @tonydnewell 

Current we are using Grpc.Tools (2.59.0), could the `PrivacyInfo.xcprivacy` for objc is enough for this nuget package? Thank you.

**Comment by tonydnewell** [comment]
@baihao  `Grpc.Tools` is common for the legacy gRPC C# nuget and the gRPC for .NET version and would not be the right place for providing `PrivacyInfo.xcprivacy` (it is just a build tool)

Again, which version of gRPC C# are you using:
- the legacy version based on the c-core - NuGet Grpc.Core v2.46.x
- the gRPC for .NET version (see https://github.com/grpc/grpc-dotnet) - NuGet Grpc.AspNetCore and Grpc.Net.Client etc?

Also I don't know why you need `PrivacyInfo.xcprivacy` for a macOS application - it is just of iOS etc.
