### ISSUE TITLE
grpc c++ client ---- Is multithreading used for handling epoll events?

### ISSUE THREAD

**Issue by wkj827270243** [grpc/grpc#36988]
Is multithreading used for handling epoll events?
epoll events ：Including: HTTP message, sending data, receiving data, metadata, etc。
These operations require a lot of resources and require multithreading to improve performance。

Is there an implementation in the source code? Where is it?

**Comment by eugeneo** [comment]
Please refer to the Stackoverflow or [Google Group](https://groups.google.com/g/grpc-io) for questions about gRPC implementation or usage.
