### ISSUE TITLE
Using ParseDict when fails if python tuple is present

### ISSUE THREAD

**Issue by radovanZRasa** [grpc/grpc#37009]
### What version of gRPC and what language are you using?
grpcio=`1.59.3`
grpcio-tools=`1.56.2`
protobuf = `4.25.3`

or

grpcio=`1.64.0`
grpcio-tools=`1.64.0`
protobuf = `5.27.1`

### What operating system (Linux, Windows,...) and version?
Mac OS 14.5 arm64 M1 Max 32GB RAM

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python version `3.8.14`.

### What did you do?
I am trying to use `ParseDict` to parse simple python dictionary
```python
original = {
     "tracker": {
        "latest_message": {
              "coords": [(0,3)]
        }
    }
}
```

with following .proto definition:
```proto
syntax = "proto3";

package my_example;
import "google/protobuf/struct.proto";
import "google/protobuf/empty.proto";

message Tracker {
  google.protobuf.Struct latest_message = 1;
}

message ActionRequest {
  Tracker tracker = 1;
}

service ActionServerWebhook {
  rpc Handle(ActionRequest) returns (google.protobuf.Empty) {}
}
```

Code to generate data:
```bash
poetry run python -m grpc_tools.protoc \
	-Igrpc_test_app/grpc_py=./proto \
	--python_out=. \
	--grpc_python_out=. \
	--pyi_out=. \
	proto/webhook.proto
```

This simple parsing test fails:
```python
from google.protobuf.json_format import ParseDict

from grpc_test_app.grpc_py import webhook_pb2
import pytest


def test_my_example():
    original = {
        "tracker": {
            "latest_message": {
                "coords": [(0, 3)],
            }
        }
    }
    action_request = webhook_pb2.ActionRequest()
    result = ParseDict(js_dict=original, message=action_request, ignore_unknown_fields=True)
```

### What did you expect to see?
I expect for the parse to pass and for `coords` to be treated as list of lists `[[]]`.

### What did you see instead?
I saw an error:
```
 google.protobuf.json_format.ParseError: Failed to parse latest_message field: Value (0, 3) has unexpected type <class 'tuple'> at ActionRequest.tracker.latest_message.coords[0].
```

Instead I used:
```python
import json

from google.protobuf.json_format import Parse

from grpc_test_app.grpc_py import webhook_pb2
import pytest


def test_my_example():
    original = {
        "tracker": {
            "latest_message": {
                "coords": [(0, 3)],
            }
        }
    }
    action_request = webhook_pb2.ActionRequest()
    json_result = json.dumps(original)
    result = Parse(text=json_result, message=action_request, ignore_unknown_fields=True)
```

Note that when JSON parses `original` it will convert tuple to list. Resulting json will look like this:
```json
{"tracker": {"latest_message": {"text_tokens": [[0, 3]]}}}
```

Note:
It works if I convert python dictionary to `JSON` and then use `ParseJson`. Converting to JSON actually converts tuple to  list.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by sreenithi** [comment]
Hi @radovanZRasa, `ParseDict` takes the argument `js_dict` which is already expected to be a "Dict representation of a JSON message", i.e a valid JSON object with JSON supported types only. 
It doesn't explicitly handle converting Python dictionaries with other types to valid JSON objects, and hence raises a ParseError in that case.

**Comment by radovanZRasa** [comment]
@sreenithi 
This poses a trouble since that is not strongly implied by the API.
I took a few moments to looks at the code and believe that Parser which takes python data and goes recursively through it, could be improved to handle `Tuple` type. Parser already has code block which is handling Python maps etc. so it looks like it could be improved to add support for Tuple as well.

**Comment by sreenithi** [comment]
Hi @radovanZRasa, while gRPC uses protobuf, making changes to the protobuf specific methods is handled by the protobuf team and not the gRPC team. So please file this issue with the protobuf repo instead, and they may be in a better position to advise if this change is feasible or not.
