### ISSUE TITLE
grpco takes forever to install

### ISSUE THREAD

**Issue by mubashir2k17** [grpc/grpc#37008]
Here is my docker file:
```
# Base image
FROM python:3.11-alpine

RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    g++ \
    libffi-dev \
    openssl-dev \
    libstdc++ \
    build-base \
    linux-headers \
    make \
    postgresql-dev \
    python3-dev

RUN pip install --upgrade pip\
    && pip install --upgrade setuptools


COPY requirements.txt .
RUN pip install -r requirements.txt


COPY . ./web_backend


WORKDIR /web_backend

EXPOSE 8000

RUN chmod +x /web_backend/entrypoint.sh

ENTRYPOINT ["sh", "/web_backend/entrypoint.sh"]
```

In the requirements file:
```
grpcio==1.64.1
```

It takes forever to install
<img width="1277" alt="Screenshot 2024-06-21 at 8 38 24 PM" src="https://github.com/grpc/grpc/assets/29198046/46c42a77-7bbf-4156-91cc-27b5f36e294a">

**Comment by XuanWang-Amos** [comment]
Sorry we don't have musllinux wheels yet, we have another issue open to track this, feel free to leave a comment there so we can adjust priority accordingly: https://github.com/grpc/grpc/issues/34998

Closing this as duplicate.
