### ISSUE TITLE
ld: warning: direct access in function ... in GRPC build/link

### ISSUE THREAD

**Issue by kyuds** [grpc/grpc#37010]
Whenever I am trying to build/link programs to grpc C++, I get the following warning, or something similar:
```
ld: warning: direct access in function '_sk_X509_NAME_deep_copy' from file '/Users/kyuds/grpc/install/lib/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file '/Users/kyuds/grpc/install/lib/libgrpc.a(ssl_transport_security.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
I have tried uninstalling, then reinstalling grpc, which also produced the above error. I am confused because grpc was working before, but then suddenly I am receiving this error despite not having changed any C++, or other core libraries. 

### What version of gRPC and what language are you using?
1.64.0, C++

### What operating system (Linux, Windows,...) and version?
Mac OS Sonoma, M1 Chip

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang 13.0.0

**Comment by drfloob** [comment]
How are you building gRPC? Please add your command line invocation and any other build configurations you're using.

**Comment by kyuds** [comment]
exactly from the website, [building gRPC with CMAKE](https://grpc.io/docs/languages/cpp/quickstart/). I have not changed a single line of code from the example in the gRPC documentation website.

**Comment by drfloob** [comment]
Are you able to build the examples as indicated here? http://grpc.io/docs/languages/cpp/quickstart/#build-the-example. There's an auth example as well, which brings in SSL dependencies.
