### ISSUE TITLE
grpc 1.64.2 - pkg-config --libs grpcpp_otel_plugin gives error Package opentelemetry_api was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by RubenGarcia** [grpc/grpc#37046]
<!--

### What version of gRPC and what language are you using?

1.64.2, C
### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 2020.4

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### What did you do?
Compiled grpc 1.64.2 with
cmake ../..
make
sudo make install

Then ran
pkg-config --libs grpcpp_otel_plugin

### What did you expect to see?
A list of libraries 

### What did you see instead?
Package opentelemetry_api was not found in the pkg-config search path.
Perhaps you should add the directory containing `opentelemetry_api.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opentelemetry_api', required by 'grpcpp_otel_plugin', not found
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by yashykt** [comment]
The gRPC C++ OpenTelemetry plugin needs the OpenTelemetry C++ API library to be installed.
