### ISSUE TITLE
In Windows cmake 3.30.0-rc4 version, grpc does not seem to be installed properly.

### ISSUE THREAD

**Issue by ehdlsgur99** [grpc/grpc#37137]
It seems that vcpkg install grpc is not valid in cmake Release Candidate (3.30.0-rc4). I used that cmake version for a few days and couldn't resolve it. I checked the issue of cmake version in the issue report and it probably doesn't work well in 3.30.0-rc4.

This error could only happen to me, but I was able to install the cmake version down to 3.29.6.

As instructed by the error message, methods such as updating vcpkg to the latest version were not applied as a solution.

![e1](https://github.com/grpc/grpc/assets/12784218/8f677df1-d0d3-47b3-814c-1b6048a6efeb)

I use Visual Studio 2022 and Windows 11 to fix the above bug, and I also removed the Korean pack for the language pack and tried using it only as an English pack.

**Comment by yashykt** [comment]
Hi, vcpkg for grpc is maintained by the community at https://github.com/Microsoft/vcpkg. Please raise an issue/pull request there.
