### ISSUE TITLE
When the GRPC client requests the gateway and forwards it to the GRPC server, transcoding fails due to UTF8MB4

### ISSUE THREAD

**Issue by an15221315127** [grpc/grpc#37160]
gRPC Error (code: 13, codeName: INTERNAL, message: grpc: failed to unmarshal the received message: string field contains invalid UTF-8, details: [], rawResponse: null, trailers: {})

**Comment by veblush** [comment]
I'd ask you to fill in more information. Also I'm not sure whether this is relevant to gRPC so I'm closing this.
