### ISSUE TITLE
Incompability bug removed including_default_value_fields=False keyword without explanation (works in 1.62 but not in 1.64)

### ISSUE THREAD

**Issue by ChameleonRed** [grpc/grpc#37184]
### What version of gRPC and what language are you using?
1.64.1 (before 1.62.2)

### What operating system (Linux, Windows,...) and version?
Linux/Windos

### What runtime / compiler are you using (e.g. python version or version of gcc)
3.12.4

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?

This argument is missed in new version without any explanation:
    including_default_value_fields=True
Compability broken.

```
def MessageToJson(
    message,
    including_default_value_fields=False,
    preserving_proto_field_name=False,
    indent=2,
    sort_keys=False,
    use_integers_for_enums=False,
    descriptor_pool=None,
    float_precision=None,
    ensure_ascii=True):
```

### What did you see instead?

```
def MessageToJson(
    message,
    preserving_proto_field_name=False,
    indent=2,
    sort_keys=False,
    use_integers_for_enums=False,
    descriptor_pool=None,
    float_precision=None,
    ensure_ascii=True,
    always_print_fields_with_no_presence=False,
):

    reply_json = json_format.MessageToJson(reply, including_default_value_fields=True, preserving_proto_field_name=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
[MessageToJson is an API on the Protobuf library](https://github.com/protocolbuffers/protobuf/blob/8995b485b94cad63e5b02841e6c9d0bed4c2ffc2/python/google/protobuf/json_format.py#L79). Please file the issue [there](https://github.com/protocolbuffers/protobuf).

**Comment by ChameleonRed** [comment]
How it resolve problem with this library incompatibility can you explain - I see not solution?
