### ISSUE TITLE
An exception occurs when establishing SSL (te._Mypair._Myval2 is nullptr)

### ISSUE THREAD

**Issue by genesysvip** [grpc/grpc#37206]
### What version of gRPC and what language are you using?
gRPC version 1.37.0, Visual Studio 2015 C++

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2015 (v140) C++11

### What did you do?
Create gRPC server with SSL credentials. Below was my source code

1. Create service and run by thread
![image](https://github.com/user-attachments/assets/c2fdc438-d416-42de-a118-beff52a3fdec)

2. Create SSL and build and ->Wait()
![image](https://github.com/user-attachments/assets/2e4f0a85-2f22-4b0c-ab68-e78bae62edb8)

### What did you expect to see?
Proper work

### What did you see instead?

Exception error for std::unique_ptr<grpc::server> te and break

![image](https://github.com/user-attachments/assets/108fbe1d-2399-40b4-be30-e4f64b12f599)

![image](https://github.com/user-attachments/assets/504f8f56-3c09-4437-b33d-28324235b9a4)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
gRPC v1.37 is too old, please use a more recent version
