### ISSUE TITLE
No provider of 'grpc-cpp' found. while zypper install 

### ISSUE THREAD

**Issue by ajsmksja** [grpc/grpc#37203]
'grpc-cpp' not found in package names. Trying capabilities.
'libprotobuf' not found in package names. Trying capabilities.
No provider of 'grpc-cpp' found.
No provider of 'libprotobuf' found.
The command '/bin/sh -c zypper install -y  libyajl2 liblmdb-0_9_30 catatonit pcre zlib ca-certificates patch libxml2 shadow glibc grpc-cpp libprotobuf' returned a non-zero code: 104

**Comment by markdroth** [comment]
For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
