### ISSUE TITLE
upb_message_lib (message.c) cannot compile with VS: initializer is not a constant

### ISSUE THREAD

**Issue by kagancapar** [grpc/grpc#37210]
Hello, 

I am encountering a compilation issue with the upb_message_lib when building gRPC from source on Windows using Visual Studio. Despite following the instructions and adding the necessary preprocessor definitions, I am receiving errors related to floating-point constants not being constant expressions. I am not entirely sure if the issue is related to the preprocessor definitions or something else. I would appreciate any guidance on how to resolve these issues.

gRPC version: v1.65.0
Language: C++
Operating System: Windows 10
Compiler: MSVC v143
CMake version: cmake version 3.29.6 

### What did you do?

`git clone --recurse-submodules -b v1.65.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc`

I followed the instructions to build gRPC from source on Windows using Visual Studio. I cloned the repository and ran the following commands:

`configured (done), generated (done) and grpc.sln build solution.`

### What did you see instead?
I encountered the following errors during the build process:

**Full error message:**
`grpc\third_party\upb\upb\message\internal\message.c(22,14): error C2099: initializer is not a constant` 
`grpc\third_party\upb\upb\message\internal\message.c(24): error E0059: function call is not allowed in a constant expression`
`grpc\third_party\upb\upb\message\internal\message.c(22): error E0221: floating-point value does not fit in required floating-point type`
`grpc\third_party\upb\upb\message\internal\message.c(23): error E0221: floating-point value does not fit in required floating-point type`

message.c content:

`const float kUpb_FltInfinity = INFINITY;
const double kUpb_Infinity = INFINITY;
const double kUpb_NaN = NAN;`

[https://github.com/grpc/grpc/blob/master/third_party/upb/upb/message/internal/message.c](url)

**Important note:** Additionally, I previously encountered an error with GTest::gmock which was resolved by downgrading the CMake version. I would appreciate any guidance on how to resolve these issues. `CMake last version: 3.30.0`

`CMake Error at third_party/abseil-cpp/CMake/AbseilHelpers.cmake:317 (target_link_libraries): The link interface of target "test_allocator" contains: GTest::gmock but the target was not found.  Possible reasons include:`

**Important note:** When running the command **vcpkg install grpc**, I also encountered the following error:

`error: building upb:x64-windows failed with: BUILD_FAILED`

**Following the below commands does not resolve the issues.**
`git pull`
`vcpkg update`

Attach:

![001](https://github.com/user-attachments/assets/57f8ee50-c83e-4e1d-91de-4e4bfa9c6d1d)
I have attached a screenshot of the vcpkg error for further reference.

### Anything else we should know about your project / environment?

I have tried various methods to resolve the issue, such as adding the _CRT_DECLARE_NONSTDC_NAMES macro to the preprocessor definitions, and checking for INFINITY and NAN definitions. Despite these efforts, I am not sure if I fully understand the problem. Any guidance on how to proceed would be greatly appreciated.

Best regards,

**Comment by kagancapar** [comment]
It has been opened before and I did not see it. I apologize but the problem does not seem to be resolved.
[https://github.com/grpc/grpc/issues/37043](url)

**Comment by kagancapar** [comment]
Reference @haberman 

> Does it work to replace `NAN` with `0.0 / 0.0`?

old code:

`const float kUpb_FltInfinity = INFINITY;`
`const double kUpb_Infinity = INFINITY;`
`const double kUpb_NaN = NAN;`

new code:

`const float kUpb_FltInfinity = (float)(1.0 / 0.0);`
`const double kUpb_Infinity = 1.0 / 0.0;`
`const double kUpb_NaN = 0.0 / 0.0;`

I will try it and share the results. @yashykt

**Comment by kagancapar** [comment]
Problem is Solved.

In the Windows 11 SDK 10.0.26100.0, the NAN macro is no longer a compile-time constant, causing issues with certain code constructs like constexpr. This can lead to compilation failures in code relying on NAN being a constant expression.

I have added definitions for positive infinity and NaN constants as follows:

kUpb_FltInfinity as (float)(1.0 / 0.0)
kUpb_Infinity as 1.0 / 0.0
kUpb_NaN as 0.0 / 0.0

or

Use std::numeric_limits<double>::quiet_NaN() for a portable and standard-compliant NaN definition.
`const double kUpb_NaN = std::numeric_limits<double>::quiet_NaN();`

Thank you. @haberman

**Comment by nelsontang** [comment]
If the code is changed to the following:
const float kUpb_FltInfinity = (float)(1.0 / 0.0);
const double kUpb_Infinity = 1.0 / 0.0;
const double kUpb_NaN = 0.0 / 0.0;

Compile will prompt error:
a division by zero.

Has anyone solved it yet?

**Comment by icegull** [comment]
> If the code is changed to the following: const float kUpb_FltInfinity = (float)(1.0 / 0.0); const double kUpb_Infinity = 1.0 / 0.0; const double kUpb_NaN = 0.0 / 0.0;
> 
> Compile will prompt error: a division by zero.
> 
> Has anyone solved it yet?

The best fix should be:

//const double kUpb_NaN = NAN;

// change to:
static const union {
    unsigned long long bits;
    double value;
} kUpb_NaN_init = {0x7FF8000000000000ULL};
#define kUpb_NaN (kUpb_NaN_init.value)

**Comment by joschaschmiedt** [comment]
Why is this issue closed? I'm still not able to build gRPC on Windows 11 24H2 with VS2022.
