### ISSUE TITLE
Contract that includes IAsyncEnumerable<byte[]> type param gives 401 Unauthorized error. 

### ISSUE THREAD

**Issue by EunjeongChoi414** [grpc/grpc#37214]
### What version of gRPC and what language are you using?
- Grpc.AspNetCore 2.63.0
- C#

### What operating system (Linux, Windows,...) and version?
- mac OS 14.4.1

### What did you do?

```c#
[OperationContract]
    public Task RequestEnrollmentAsync(
        string nickname, string introduction, IAsyncEnumerable<byte[]> resources, 
        string voiceFormat, IEnumerable<string> colorCodes, CancellationToken cancel = default);
``` 
- I tried to call this code-first service model API as [this example](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/FileUploadDownload). My team needs to transfer file data from client to server. 

### What did you expect to see?
- data transfer from client to server with no error. 

### What did you see instead?
- calling the above API from client gives me 401 unauthorized error but this only happens with 'IAsyncEnumerable<byte[]>' type param included. If I take this param out then no exception occurs and data for the rest of the api is transferred as expected.

**Comment by tonydnewell** [comment]
@EunjeongChoi414  Please ask in https://github.com/grpc/grpc-dotnet/issues as this is a Grpc.AspNetCore issue, and close here.
This repository is for the legacy C# gRPC implementation.
