### ISSUE TITLE
context.is_active() not working

### ISSUE THREAD

**Issue by cadzchua** [grpc/grpc#37268]
### What version of gRPC and what language are you using?
grpcio==1.64.1
grpcio-tools==1.64.1

python

### What operating system (Linux, Windows,...) and version?
windows 11 home 23H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.12.4

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
```

import grpc
import data_pb2
import data_pb2_grpc

class datatransferServicer(data_pb2_grpc.datatransferServicer):
    
    def SendData(self, request, context):
        print("Client Request Made:")
        print(request)


        while context.is_active():
            hello_reply = data_pb2.DataResponse()
            message = input("Enter your message: ")
            hello_reply.message = message
            yield hello_reply

        print("Client disconnected.")
        
def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    data_pb2_grpc.add_datatransferServicer_to_server(datatransferServicer(), server)
    server.add_insecure_port("localhost:8080")
    server.start()
    print("server Started~~ Listening at port 8080.")
    server.wait_for_termination()

if __name__ == "__main__":
    serve()
```
### What did you expect to see?
server terminates connection with client when client disconnects and still listen on the port for more incoming request

### What did you see instead?
context.is_active() is always true despite me terminating the connection of the client (through keyboard interruption)

### Anything else we should know about your project / environment?
-

**Comment by sreenithi** [comment]
Hi @cadzchua, can you try using a signal handler on the Client, similar to [this test](https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/unit/_signal_client.py#L73) and see if the issue persists. If not, please provide the proto, server and client files necessary to help us reproduce this.
