### ISSUE TITLE
Add gRPC streaming for code first approach

### ISSUE THREAD

**Issue by vasylstrogushr** [grpc/grpc#37285]
There is no approach using gRPC streaming in .Net Code First approach. 
One of the solution is to use IAsyncEnumerable but it is not for a streaming but mostly about duplex connection.

P.S. If using protobuff first approach it works fine but in .Net ecosystem I would like rather use code first approach with Code First Grpc Reflection to provide contracts to other services that sending protofiles.

**Comment by tonydnewell** [comment]
@vasylstrogushr I suggest you add this feature request in https://github.com/grpc/grpc-dotnet which is for the active gRPC .NET development. This repository is the the legacy gRPC C# implementation based on the c-core implementation.
