### ISSUE TITLE
According to our testing, the single connection throughput of C++GRPC is very low. Why doesn't C++client use connection pooling?

### ISSUE THREAD

**Issue by wkj827270243** [grpc/grpc#37300]
According to our testing,
the single connection throughput of C++GRPC is very low.
Why doesn't C++client use connection pooling?
The load balancing function uses connection pooling, which is more valuable in the project

**Comment by eugeneo** [comment]
Please provide more details, including your testing approach, gRPC client implementation and what do you consider a "low connection throughput"
There is a number of ways your code may be limiting gRPC performance. Please make sure you use callback APIs - [server](https://github.com/grpc/grpc/blob/d43e35738ad9c624bd9eb2f9c56b93fb4cf849a7/examples/cpp/helloworld/greeter_callback_server.cc), [client](https://github.com/grpc/grpc/blob/d43e35738ad9c624bd9eb2f9c56b93fb4cf849a7/examples/cpp/helloworld/greeter_callback_client.cc)
