### ISSUE TITLE
Keepalive response takes 4 seconds to arrive to a client-side streamer.

### ISSUE THREAD

**Issue by Boronyak** [grpc/grpc#37313]
### What version of gRPC and what language are you using?
1.51.1 (from vcpkg package manager)
C++ (standard 17)

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 11.4.0
cmake 3.22.1

### What did you do?
First I create a channel with `CreateCustomChannel` method.

`CreateCustomChannel(host + ":" + to_string(port), InsecureChannelCredentials(), arguments);`

For arguments I set the followings:
```
arguments.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 1000);
arguments.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 5000);
arguments.SetInt(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 1);
arguments.SetInt(GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA, 0);
arguments.SetInt(GRPC_ARG_MAX_RECONNECT_BACKOFF_MS, 1000);
```
Then I create a `ClientWriter` object like this:

`MyService::NewStub(channel)->MyClientSideStream(context.get(), &response)`

After that I send messages to the server with the `Write` method:

`writer->Write(message);`

Lastly, when I want to finish streaming, I call the `WritesDone` and `Finish` methods:
```
writer->WritesDone();
writer->Finish();
```
During message streaming, I am watching the output of tcpdump and the keepalive trace with the following environment setup:
```
GRPC_VERBOSITY=DEBUG
GRPC_TRACE=http_keepalive
```

### What did you expect to see?
My client starts keepalive ping every second and the response takes about 1 millisecond.

### What did you see instead?
```
I0725 14:25:29.056641019   16708 writing.cc:178]                       CLIENT: Ping sent [ipv4:172.20.10.100:8090]: 0/0
I0725 14:25:29.056740851   16708 chttp2_transport.cc:2647]             ipv4:172.20.10.100:8090: Start keepalive ping
I0725 14:25:33.054559433   16708 chttp2_transport.cc:2671]             ipv4:172.20.10.100:8090: Finish keepalive ping
I0725 14:25:34.054522651   16708 writing.cc:178]                       CLIENT: Ping sent [ipv4:172.20.10.100:8090]: 0/0
I0725 14:25:34.054620441   16708 chttp2_transport.cc:2647]             ipv4:172.20.10.100:8090: Start keepalive ping
I0725 14:25:38.054595555   16719 chttp2_transport.cc:2671]             ipv4:172.20.10.100:8090: Finish keepalive ping
```
Every time it takes 4 second to finish keepalive ping, regardless of sending messages or not.
However in the output of tcpdump, I see the server's response immediately after the ping.
I could not figure out why my client finishes keepalive ping just after 4 second if the response comes instantly.
Can you tell me what can cause this unexpected behavior?

### Anything else we should know about your project / environment?
I have a server side streamer also, using similar methods from the sync API to create a `ClientReader`. With this reader everything works as expected, I see keepalive pings every second.

**Comment by yashykt** [comment]
The sync API has a threading model where we borrow the application thread when read/write operations are performed. These borrowed threads are what we use to actually poll fds and read/write. Outside of these threads, there is a background thread that helps perform some operations when application threads are not available. The downside is that this background thread is run every few seconds. Combining this with the keepalive ping results in unfortunate behavior where if the client/server is not actively performing an operation like read, we wouldn't be polling the fds in a timely manner.

Our recommendation is to use the callback API which doesn't suffer from such issues. (Alternatively, if using event engine which is rolling out as an experiment, that would be a way to deal with this issue while continuing with the sync API.)
