### ISSUE TITLE
grpc.tools fails RHEL 8 aarch64

### ISSUE THREAD

**Issue by omajid** [grpc/grpc#37340]
### What version of gRPC and what language are you using?

 Grpc.Tools version 2.64.0

### What operating system (Linux, Windows,...) and version?

RHEL 8

### What runtime / compiler are you using (e.g. python version or version of gcc)

.NET 9, but also affects older .NET versions.

### What did you do?

I tried building ASP.NET Core (https://github.com/dotnet/aspnetcore commit 06155c05af89c957de20d2c53cee0e37171b9a09) on RHEL 8 arm64/aarch64. It fails because grpc.tools needs a higher glibc version:

```
$ git clone https://github.com/dotnet/aspnetcore .git
$ cd aspnetcore
$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
$ git rev-parse HEAD
06155c05af89c957de20d2c53cee0e37171b9a09
$ git submodule init
Submodule 'src/submodules/MessagePack-CSharp' (https://github.com/aspnet/MessagePack-CSharp.git) registered for path 'src/submodules/MessagePack-CSharp'
Submodule 'src/submodules/googletest' (https://github.com/google/googletest) registered for path 'src/submodules/googletest'
$ git submodule update --recursive
$ eng/build.sh --ci --arch arm64 -c Release /p:IsPlaywrightAvailable=false --restore --build --pack
warning: No default group of projects was specified, so building the 'managed' and its dependent subset of projects. Run build.sh --help for more details.
warning: Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected on PATH.
warning: Note that if you are running Source Build, building NodeJS projects will be disabled later on.
##vso[task.setvariable variable=Artifacts;isSecret=false;isOutput=true]/home/tester/aspnetcore/artifacts
##vso[task.setvariable variable=Artifacts.Toolset;isSecret=false;isOutput=true]/home/tester/aspnetcore/artifacts/toolset
##vso[task.setvariable variable=Artifacts.Log;isSecret=false;isOutput=true]/home/tester/aspnetcore/artifacts/log/Release
##vso[task.setvariable variable=Temp;isSecret=false;isOutput=true]/home/tester/aspnetcore/artifacts/tmp/Release
##vso[task.setvariable variable=TMP;isSecret=false;isOutput=true]/home/tester/aspnetcore/artifacts/tmp/Release
Downloading 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh'
...
  Restored /home/tester/aspnetcore/src/Caching/SqlServer/src/Microsoft.Extensions.Caching.SqlServer.csproj (in 574 ms).
  Restored /home/tester/aspnetcore/src/Framework/Microsoft.Internal.Aspnetcore.DotNetApiDocs.Transport/src/Microsoft.Internal.Aspnetcore.DotNetApiDocs.Transport.csproj (in 1.47 sec).
  Microsoft.AspNetCore.Grpc.JsonTranscoding -> /home/tester/aspnetcore/artifacts/bin/Microsoft.AspNetCore.Grpc.JsonTranscoding/Release/net9.0/Microsoft.AspNetCore.Grpc.JsonTranscoding.dll
/home/tester/aspnetcore/.packages/grpc.tools/2.64.0/tools/linux_arm64/protoc : error : /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/tester/aspnetcore/.packages/grpc.tools/2.64.0/tools/linux_arm64/protoc) [/home/tester/aspnetcore/src/Grpc/JsonTranscoding/perf/Microsoft.AspNetCore.Grpc.Microbenchmarks/Microsoft.AspNetCore.Grpc.Microbenchmarks.csproj]
##vso[task.logissue type=error;sourcepath=/home/tester/aspnetcore/.packages/grpc.tools/2.64.0/tools/linux_arm64/protoc;linenumber=0;columnnumber=0;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/tester/aspnetcore/.packages/grpc.tools/2.64.0/tools/linux_arm64/protoc)
```

A simpler way to reproduce is this on RHEL 8 aarch64 machine directly. Or use a container + emulation:

```
$  podman run --pull=always --arch aarch64 -it ubi8
Resolved "ubi8" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 376a7503a7e3 done   |
Copying config 5d7f668aa7 done   |
Writing manifest to image destination
Storing signatures
[root@7fb493b706a2 /]# ls
bin  boot  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
[root@7fb493b706a2 /]# cd tmp/
[root@7fb493b706a2 tmp]# dnf install -yq curl unzip
[root@7fb493b706a2 tmp]# curl -sSLO https://www.nuget.org/api/v2/package/Grpc.Tools/2.65.0
[root@7fb493b706a2 tmp]# mkdir Grpc.Tools.2.65.0
[root@7fb493b706a2 tmp]# cd Grpc.Tools.2.65.0/
[root@7fb493b706a2 Grpc.Tools.2.65.0]# unzip ../2.65.0
...
[root@7fb493b706a2 Grpc.Tools.2.65.0]# ldd tools/linux_arm64/protoc
ldd: warning: you do not have execution permission for `tools/linux_arm64/protoc'
tools/linux_arm64/protoc: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by tools/linux_arm64/protoc)
tools/linux_arm64/protoc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by tools/linux_arm64/protoc)
tools/linux_arm64/protoc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by tools/linux_arm64/protoc)
tools/linux_arm64/protoc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by tools/linux_arm64/protoc)
        linux-vdso.so.1 (0x0000400000801000)
        libm.so.6 => /lib64/libm.so.6 (0x0000400000806000)
        libc.so.6 => /lib64/libc.so.6 (0x00004000008c7000)
        /lib/ld-linux-aarch64.so.1 (0x00007f3d30a3b000)
```

### What did you expect to see?

This is a platform supported for .NET 9, so I expected to be able to use common .NET tools with it too.

### What did you see instead?

Grpc.Tools include a native binary that requires a higher version of glibc than .NET 9 requires: https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.md#linux-compatibility

```
# ldd tools/linux_arm64/protoc
ldd: warning: you do not have execution permission for `tools/linux_arm64/protoc'
tools/linux_arm64/protoc: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by tools/linux_arm64/protoc)
tools/linux_arm64/protoc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by tools/linux_arm64/protoc)
tools/linux_arm64/protoc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by tools/linux_arm64/protoc)
tools/linux_arm64/protoc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by tools/linux_arm64/protoc)
        linux-vdso.so.1 (0x0000400000801000)
        libm.so.6 => /lib64/libm.so.6 (0x0000400000806000)
        libc.so.6 => /lib64/libc.so.6 (0x00004000008c7000)
        /lib/ld-linux-aarch64.so.1 (0x00007f3d30a3b000)
```

**Comment by tonydnewell** [comment]
The .NET version is irrelevant here.

A workaround is to find third party prebuilt images for `protoc` and `grpc_csharp_plugin` and then set the environment so that `grpc.tools` uses those images. See [Using Grpc.Tools with unsupported architectures](https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#unsupported-arch)

For example, https://rhel.pkgs.org/8/synergy-aarch64/grpc-plugins-1.17.1-3.el8.aarch64.rpm.html for the plugins, and elsewhere for `protoc` (do a search).  I'm not endorsing particular third party packages, you can decide what you are comfortable to use.

**Comment by tonydnewell** [comment]
I don't have access to RHEL 8 or an arm64 machine so I cannot verify what versions of glibc `protoc` requires. Is it possible for you to install a later version of glibc?

**Comment by omajid** [comment]
> I cannot verify what versions of glibc protoc require

Based on the ldd output above,  glibc 2.34?

> Is it possible for you to install a later version of glib

Techincally, yes, but not really in practical way. glibc is the c library. The lowest-level utilities in the system use it. Upgrading it will likely break everything.

There are some ways to compile and install an alternate version in an optional location and then try and use it explicitly, but that's not straightforward at all.

**Comment by veblush** [comment]
Note that RHEL 8 is out of support for protoc based on Google OSS C++ support [policy](https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md) but glibc requirement is still 2.27 or higher. So having dependencies to 2.34 looks a bit off. Maybe protoc artifact was built on a modern Linux, which can result in the binary relying on modern features available in the later glibc.

**Comment by veblush** [comment]
> 
I don't have access to RHEL 8 or an arm64 machine so I cannot verify what versions of glibc protoc requires. Is it possible for you to install a later version of glibc?

From https://distrowatch.com/table.php?distribution=redhat, RHEL 8 appears to have glibc 2.28.

**Comment by tonydnewell** [comment]
From looking at the build tools - the building of `protoc` and plugins for linux happens in different docker files depending on the architecture.
See https://github.com/grpc/grpc/blob/36123761a113541e9e279031b5347b44df23e448/tools/run_tests/artifacts/artifact_targets.py#L331-L342

For Intel x64 - https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_artifact_centos6_x64/Dockerfile
- based on `dockcross/manylinux2010-x64`

For arm64 - https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_artifact_protoc_aarch64/Dockerfile
- based on `dockcross/linux-arm64`

I don't know enough about these docker images to know what glibc is used in each.

**Comment by omajid** [comment]
Is switching to `dockcross/manylinux2014-aarch64` an option? It seems to have a version of glibc that's low enough.

```
$ podman run -it dockcross/linux-arm64 /bin/bash
[root:/work] # readelf -sW /usr/xcc/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot/lib/libc.so.6 | grep @GLIBC | sed -E 's/.*(@GLIBC.*)/\1/' | sort -u
@GLIBC_2.17
@GLIBC_2.17 (5)
@GLIBC_PRIVATE
@GLIBC_PRIVATE (4)
[root:/work] 130 # exit
$ podman run -it dockcross/linux-arm64 /bin/bash
[root:/work] # readelf -sW /usr/xcc/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot/lib/libc.so.6 | grep @GLIBC | sed -E 's/.*(@GLIBC.*)/\1/' | sort -u
@GLIBC_2.17
@GLIBC_2.17 (18)
@GLIBC_2.18
@GLIBC_2.22
@GLIBC_2.23
@GLIBC_2.24
@GLIBC_2.25
@GLIBC_2.26
@GLIBC_2.27
@GLIBC_2.28
@GLIBC_2.29
@GLIBC_2.30
@GLIBC_2.31
@GLIBC_2.32
@GLIBC_2.33
@GLIBC_2.34
@GLIBC_PRIVATE
@GLIBC_PRIVATE (19)
```

**Comment by omajid** [comment]
I have a PR for this here: https://github.com/grpc/grpc/pull/37440

**Comment by veblush** [comment]
https://github.com/grpc/grpc/pull/38084 fixed this.
