### ISSUE TITLE
[Ruby]the new versions of 1.65.x have not been released to rubygems

### ISSUE THREAD

**Issue by y-yagi** [grpc/grpc#37451]
### What version of gRPC and what language are you using?

Ruby

### What did you expect to see?

#37357 and #37378 have bumped the version of 1.65.x series. But, both new versions(v1.65.3 and v1.65.4) have not been released to rubygems.  The latest version of 1.65.x series is still v1.65.2.
https://rubygems.org/gems/grpc/versions

Is this intended? For example, grpcio v1.65.4 has been released correctly. https://pypi.org/project/grpcio/1.65.4/

**Comment by Linuus** [comment]
Now 1.66.0 was released. Will that end up in Rubygems? It's not there yet at least.

**Comment by Linuus** [comment]
1.66.0 is in Rubygems now so I think we can close this.
