### ISSUE TITLE
Configuration error with opentelemetry plugin + otel grpc exporter

### ISSUE THREAD

**Issue by chazov-ts** [grpc/grpc#37469]
### What version of gRPC and what language are you using?
C++, gRPC Release v1.65.4 

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang 17
CMake 3.22

### What did you do?
I am using grpc exporter in opentelemetry (WITH_OTLP_GRPC flag), gRPC is required.
But when building the opentelemetry plugin in grpc requires opentelemetry itself , a cyclic dependency appears which causes an error.
On HTTP exporter everything works fine.

### What did you expect to see?
Successful configuration and build.

### What did you see instead?
Build configuration error

```

set(WITH_OTLP_GRPC ON CACHE BOOL "Enable OTLP gRPC Exporters in OpenTelemetry" FORCE)
set(WITH_ABSEIL ON CACHE BOOL "Enable ABSEIL in OpenTelemetry" FORCE)
set(WITH_PROMETHEUS ON CACHE BOOL "Enable PROMETHEUS exporter in OpenTelemetry" FORCE)
set(gRPC_BUILD_GRPCPP_OTEL_PLUGIN ON CACHE BOOL "Enable Otel plugin in gRPC" FORCE)

include(FetchContent)

FetchContent_Declare(
  opentelemetry-cpp
  SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/opentelemetry-cpp"
)

FetchContent_Declare(
    gRPC
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/grpc"
)

//error here
FetchContent_MakeAvailable(opentelemetry-cpp gRPC)

```

**Comment by veblush** [comment]
Would you share the exact build command and the error message you got?
