### ISSUE TITLE
Memory leak in v1.65.x for C++

### ISSUE THREAD

**Issue by mark-dorrell** [grpc/grpc#37470]
There appears to be a memory leak introduced in v1.65.x with C++ and using Google Speech To Text v1p1beta1 and v2 StreamingRecognize. The same code does not leak with v1.64.1 and v1.64.3 (and none noticed in earlier versions).

### What version of gRPC and what language are you using?
v1.65.4 with C++

### What operating system (Linux, Windows,...) and version?
Window 2019 Server Datacenter build 17763

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2022 compiling to Release Win32

### What did you do?
Have been using grpc C++ successfully for several years now with busy systems using Google Speech To Text in an IVR context. I deployed an update containing v1.65.4 and noticed the process using the grpc library was using 1GB of memory in one day (when its usually static around 20MB).

### What did you expect to see?
Memory use with earlier versions of grpc (before v1.65.x) is usually less than 20MB (up to 60 concurrent channels).
Previous system build was using v1.64.1 with no memory leak at all.

### What did you see instead?
A load test containing 100 concurrent Google STT v1p1beta1 StreamingRecognize from 20s of LINEAR16 audio repeated 10 times used about 100MB memory. When repeated 20 times used about 200MB memory. Memory consumption appears linear with the number of streaming recognitions.

I just  rebuilt with v1.64.3 and repeated the same load test 100 concurrent channels repeated 50 times (basically the same test as above but 50 times = 5000 Google recognitions) and that stabilized at about 80MB-90MB (after initial fluctuations between 20MB and 90MB).

**Comment by markdroth** [comment]
I suspect this was the leak fixed in #37358.  I'm back-porting that fix to 1.65 in #37474.

**Comment by markdroth** [comment]
This fix will be in the upcoming 1.65.5 release.
