### ISSUE TITLE
ARM64 Support on Windows for Grpc.Tools

### ISSUE THREAD

**Issue by robertr-37** [grpc/grpc#37588]
Hello, are there any plans to add win-arm64 support for the Gprc.Tools package?
I'm specifically interested in a grpc_csharp_ext.arm64.dll that can run on ARM64 Windows 11.

**Comment by tonydnewell** [comment]
There are currently no plans to provide native arm64 dlls for Windows.

However see https://github.com/grpc/grpc/issues/31975 and https://github.com/grpc/grpc/pull/32017 for workarounds

**Comment by MichaMican** [comment]
Both workarrounds do not work... Still no intentions to bring grpc_csharp_ext.arm64.dll to life?
