### ISSUE TITLE
UserWarnings emitted from all protoc-generated _pb2 packages

### ISSUE THREAD

**Issue by mtnpke** [grpc/grpc#37609]
### What version of gRPC and what language are you using?
Python

Package versions:
* grpcio 1.66.1
* grpcio-tools 1.66.1

### What operating system (Linux, Windows,...) and version?
Windows 11 Version 23H2 (OS Build 22631.4037)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32

### What did you do?
* Create clean virtual environment with Python 3.12
* Run `pip install grpcio grpcio-tools` (as of today, this will install version 1.66.1)
* Create file `test.proto` that only contains `syntax = "proto3";`
* Run `python -m grpc_tools.protoc --python_out=. --pyi_out=. --grpc_python_out=. -I. test.proto`

### What did you expect to see?
I can import the generated Python files without issues and warnings.

### What did you see instead?
```
>>> import test_pb2
C:\temp\grpc-test\venv\Lib\site-packages\google\protobuf\runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.0 at test.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
>>>
```

### Anything else we should know about your project / environment?

Caused by this pull request: https://github.com/protocolbuffers/protobuf/pull/17241 that is present since protobuf 5.28.0

gprc protoc uses protobuf 5.27.2 for generation, but pip automatically pulls in the newest version (5.28.0), generating this warning.

**Comment by chrismiller** [comment]
Is this even a valid warning for this situation? From the [docs](https://protobuf.dev/support/cross-version-runtime-guarantee/#minor): "Within a single major runtime version, generated code from an older version of protoc will run on a newer runtime", so I believe it should be fine to use e.g. protoc 5.27.2 and runtime 5.28.0, despite what the warning says?

For context, we're seeing this warning being emitted a lot across our (Python) codebase because we need to use the 5.28.0 runtime (due to [a bugfix](https://github.com/protocolbuffers/protobuf/pull/16691) that's important to us but only present in 5.28.x), but we can only use the 5.27.2 compiler since that's the latest available to us in grpcio-tools (v1.66.1). We can't just call the protoc v28 binary directly since we also need grpc and mypy-protobuf codegen, which I believe are only available via a virtual env.

**Comment by chrismiller** [comment]
That's similar to what I've ended up going with, though I'm doing it via an `__init__.py` file in the same directory as the generated `_pb2.py` files so the `with warnings.catch_warnings()` block isn't required around any imports, i.e. `__init__.py` just contains the following:
```
import warnings
warnings.filterwarnings("ignore", ".*obsolete", UserWarning, "google.protobuf.runtime_version")
```
(Note in my case I chose to filter on `".*obsolete"` so only the minor warning gets filtered. Your example filters the major version warning too, which is presumably what you want but I'm just mentioning it here for other people to be aware of).

It's still a bit messy for my case because we generate protos into a half-dozen or so directories across multiple repos, so I need an `__init__.py` file for each directory to be sure the warning is suppressed, but it's still the cleanest workaround I've come up with so far.

**Comment by XuanWang-Amos** [comment]
Hi, thanks for reporting this, like you mentioned, `grpc_tools` have a fixed dependency on protobuf version, currently it's 5.27.2.

On our side, we can change protobuf version in `setup.py` to reflect the fixed version requirement, but the warning message itself comes from Protobuf library, which should be gone once we updated to 5.28.0.

**Comment by mtnpke** [comment]
Hi, thanks for the explanation @XuanWang-Amos. Unfortunately, I cannot say that it looks like there is a satisfactory solution to this as long as the protobuf stance on generated code is how you describe it.

All of what you have said may be useful solutions if you manage all dependencies yourself and only have generated code in your application package. However, I think it all falls apart in a packaging context. On PyPI, for example, there are [hundreds of packages depending on grpcio](https://www.wheelodex.org/projects/grpcio/rdepends/). Organization-internal repositories will be similar. We can assume that many of them contain generated grpc/protobuf code, since interacting with gRPC services (or providing them) is the typical use case of grpcio. Now suppose that they would all depend on a fixed version of protobuf, like you recommend. This will mean that the chances of any user being able to use a current version of more than one such library as dependency will be slim, since they will also not be released in sync with grpcio-tools (just like grpcio-tools with protobuf). Their dependency specifications will conflict. If, on the other hand, they do not depend on a fixed version of protobuf, users will randomly start getting warnings and errors depending on when exactly they try to install the package, what protobuf version was released last, and what protobuf version was used to generate the code in the package.

The way I see it, the way this is headed right now will result in a lot of pain for users.

About the change to `grpcio_tools`: You have now fixed the version to `==5.27.2`. Isn't this stricter than necessary? Does this not mean that users would be missing even compatible bug fixes from versions >5.27.2 but <5.28? In general, the stricter the dependency specification, the higher the chance that dependency resolution will ultimately fail due to unresolvable conflicts.

**Comment by nataliachodelski** [comment]
Hi @gnossen, are you going to review https://github.com/grpc/grpc/pull/37666 so it can get merged?

**Comment by ArdentLeKhey** [comment]
For me, it was a problem with protobuf. In my requirements.txt, I specified protobuf==5.27.2, and now the warning has disappeared.

**Comment by XuanWang-Amos** [comment]
> Hi @gnossen, are you going to review #37666 so it can get merged?

We discussed internally and no longer think that's the right fix, pasting the reasons here:
* Compatibility Guarantee: The Protobuf team has assured us of compatibility between generated code and a range of Protobuf runtime versions. Code generated by a particular version of grpcio-tools should work with the range of Protobuf runtimes listed in the requirement.
* Diamond Dependency Risk: Fixing the requirement to a single version increases the likelihood of introducing diamond dependency conflicts, and more likely to cause dependency resolution failures.

**Comment by mtnpke** [comment]
grpcio_tools now has a reasonable version requirement on protobuf. I have noticed that this did not help me, because my package was only depending on grpcio (plus protobuf separately) - as the .proto files are already compiled, the installed package does not need grpcio_tools. With the release of Python protobuf 6.30 a few days ago, I was getting warnings again, since the major version has changed.
I have now added `grpcio[protobuf]` as dependency to my package, which will pull in `grpcio_tools`. That or directly depending on `grpcio_tools` seem (to me) to be the only ways to get a compatible protobuf version. If I just depend on grpcio, the code will not work since it is missing protobuf. If I depend on grpcio and protobuf separately, pip/uv will of course just pick the latest protobuf.
So, is this how it is supposed to work? Is it the correct way to depend on grpcio_tools just to get a compatible protobuf version?

**Comment by mtnpke** [comment]
> Please feel free to re-open/create a new issue if this is still relevant.

Please reopen, as the issue is not resolved. It says that I don't have the permission to reopen myself.

On another note, the fix of using `grpcio[protobuf]` as dependency only works as long as you depend on an *exact* version, such as `grpcio[protobuf]==1.70.0`. Otherwise, there is the risk that a newer grpcio version bundles a newer protobuf (even at the same major version - see for example grpcio 1.73 vs. 1.70) that will make the generated code backward-incompatible again and/or give UserWarnings.

**Comment by sergiitk** [comment]
This warning was removed completely on the protobuf side in https://github.com/protocolbuffers/protobuf/issues/18096. It went in https://github.com/protocolbuffers/protobuf/commit/83569cff3de3b3641e0410479e61f13972c5d469, and they backported it as a patch release to `v5.28.3`: https://github.com/protocolbuffers/protobuf/releases/tag/v28.3

Using test_pb2.py generated with grpc_tools `1.66.1` (same as in the original post), which produces `5.27.2`.

**5.28.2:**
```sh-session
$ python -c 'import google.protobuf; print(google.protobuf.__version__); import test_pb2; print(test_pb2.__name__)'
5.28.2
/private/var/folders/y7/plw5m9fd645g16_3zg9d32zc00rg80/T/sergiitk-2026-07-08.ucErG87X8d/.venv-1-70-0/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at test.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
test_pb2
```

**5.28.3:**
```sh-session
$ python -c 'import google.protobuf; print(google.protobuf.__version__); import test_pb2; print(test_pb2.__name__)'
5.28.3
test_pb2
```

@mtnpke: I've confirmed there are no warnings when running with for grpcio `1.70.0` / protobuf `5.29.6`:

**5.29.6:**
```sh-session
$ python -c 'import google.protobuf; print(google.protobuf.__version__); import test_pb2; print(test_pb2.__name__)'
5.29.6
test_pb2
```

Same goes for the latest grpc `1.82.1` / protobuf `7.35.1`.

**7.35.1:**
```sh-session
$ python -c 'import google.protobuf; print(google.protobuf.__version__); import test_pb2; print(test_pb2.__name__)'
7.35.1
test_pb2
```
