### ISSUE TITLE
Unable to run Python example code acc. "quick start" due to version check

### ISSUE THREAD

**Issue by mtnpke** [grpc/grpc#37610]
### What version of gRPC and what language are you using?
Python

Package versions:
* grpcio 1.66.1
* grpcio-tools 1.66.1

### What operating system (Linux, Windows,...) and version?
Windows 11 Version 23H2 (OS Build 22631.4037)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32

### What did you do?
* Go to https://grpc.io/docs/languages/python/quickstart/
* Follow instructions to prepare Python and check out the example code
* Try to run examples/helloworld/greeter_server.py

### What did you expect to see?
The example runs.

### What did you see instead?
```
$ python greeter_server.py
C:\temp\grpc-test\venv\Lib\site-packages\google\protobuf\runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.0 at helloworld.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
Traceback (most recent call last):
  File "C:\temp\grpc-test\grpc\examples\python\helloworld\greeter_server.py", line 21, in <module>
    import helloworld_pb2_grpc
  File "C:\temp\grpc-test\grpc\examples\python\helloworld\helloworld_pb2_grpc.py", line 19, in <module>
    raise RuntimeError(
RuntimeError: The grpc package installed is at version 1.66.1, but the generated code in helloworld_pb2_grpc.py depends on grpcio>=1.67.0.dev0. Please upgrade your grpc module to grpcio>=1.67.0.dev0 or downgrade your generated code using grpcio-tools<=1.66.1.
```

### Anything else we should know about your project / environment?
no

**Comment by PythonCodeNemesis** [comment]
I am also facing the same issue.

**Comment by divmoh** [comment]
I am also facing the same issue.

**Comment by XuanWang-Amos** [comment]
Hi, thanks for reporting this, we checked in generated code using a development version, I'll create a PR to fix this soon.


Before the fix was released, you can try:
1. Manually change the version to the same or lower than grpcio (you can check the version use `python pip list | grep 'grpcio'`)
2. Regenerating the `helloworld_pb2_grpc.py` file by following this: https://grpc.io/docs/languages/python/quickstart/#generate-grpc-code

**Comment by jhabaa** [comment]
> Temporary solution: We can replace version as you can see in following image: <img alt="Screenshot 2024-09-10 at 7 09 30 PM" width="1066" src="https://private-user-images.githubusercontent.com/149954102/366123010-de943457-0ef1-46c4-b55f-7a51325d0149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODU2NTAsIm5iZiI6MTcyNjY4NTM1MCwicGF0aCI6Ii8xNDk5NTQxMDIvMzY2MTIzMDEwLWRlOTQzNDU3LTBlZjEtNDZjNC1iNTVmLTdhNTEzMjVkMDE0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxODQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDQwZWEyYTc2MjE2MmQ1NWYxZGRmYWZjOWM0MzQwODlhYmExMGJjNThiZjFkYTg5Yzg0MWIzNDY0ZDkxZGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nm9vsgMaMb7ZF5bgv7gcVHWwpwT6EjH2FTYuv9I66r8">

Good for the moment xD
