### ISSUE TITLE
error: module com_github_grpc_grpc//src/core:cf_event_engine does not depend on a module exporting 'absl/status/status.h'

### ISSUE THREAD

**Issue by xiedeacc** [grpc/grpc#37619]
grpc version:v1.65.1
bazel:7.2.0
abseil:20240116.2
os: macosx x86_64 Darwin Kernel Version 22.6.0
compiler:system installed gcc(it's clang truelly)

**Comment by eugeneo** [comment]
Please provide instruction on how to reproduce this problem, e.g. what build target are you trying to build.

**Comment by xiedeacc** [comment]
```
https://github.com/xiedeacc/bazel_template.git
cd bazel_template
clear && bazel build @com_github_grpc_grpc//:grpc_unsecure  -s
```
bazel version is 7.2.0

**Comment by xiedeacc** [comment]
doen't have such error use clang on linux, just occured on macosx

**Comment by xiedeacc** [comment]
on same system, built success on grpc own repo root,but grpc as an external repo in bazel_template will meet my issue's error

**Comment by xiedeacc** [comment]
use grpc branch pls

**Comment by xiedeacc** [comment]
it's bazel's problem, fixed by build --features=-module_maps
