### ISSUE TITLE
link error in msvc2022 project

### ISSUE THREAD

**Issue by zhccsd** [grpc/grpc#37624]
### What version of gRPC and what language are you using?
v1.66.1 and c++

### What operating system (Linux, Windows,...) and version?
windows10

### What runtime / compiler are you using (e.g. python version or version of gcc)
msvc2022 v14.41.34120

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
first build grpc like this:
cmake ..\.. -GNinja -DgRPC_MSVC_STATIC_RUNTIME=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="%~dp0grpc-1.66.1_%_MSVC_VERSION%_%_MSVC_ARCH%_%_MSVC_VER%_MT_Debug"
cmake --build . --parallel && ninja install
then link into a win32 desktop project

### What did you expect to see?
build win32 desktop project with no error

### What did you see instead?
a lot of link error, like these:
1>libprotobufd.lib(descriptor.pb.cc.obj) : error LNK2001: unresolved external symbol "public: class absl::lts_20240116::log_internal::LogMessage & __cdecl absl::lts_20240116::log_internal::LogMessage::operator<<<unsigned __int64,0>(unsigned __int64 const &)" (??$?6_K$0A@@LogMessage@log_internal@lts_20240116@absl@@QEAAAEAV0123@AEB_K@Z)
1>libprotobufd.lib(cpp_features.pb.cc.obj) : error LNK2001: unresolved external symbol "public: class absl::lts_20240116::log_internal::LogMessage & __cdecl absl::lts_20240116::log_internal::LogMessage::operator<<<unsigned __int64,0>(unsigned __int64 const &)" (??$?6_K$0A@@LogMessage@log_internal@lts_20240116@absl@@QEAAAEAV0123@AEB_K@Z)
1>libprotobufd.lib(feature_resolver.cc.obj) : error LNK2001: unresolved external symbol "public: class absl::lts_20240116::log_internal::LogMessage & __cdecl absl::lts_20240116::log_internal::LogMessage::operator<<<unsigned __int64,0>(unsigned __int64 const &)" (??$?6_K$0A@@LogMessage@log_internal@lts_20240116@absl@@QEAAAEAV0123@AEB_K@Z)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
project link list:
absl_base.lib
absl_synchronization.lib
absl_strings.lib
absl_str_format_internal.lib
absl_throw_delegate.lib
absl_raw_logging_internal.lib
absl_malloc_internal.lib
absl_time.lib
absl_log_severity.lib
gpr.lib
grpc.lib
grpc++.lib
libprotobufd.lib

**Comment by veblush** [comment]
I guess this is caused by missing linker targets. If you're using CMake to build your application, please share how you organize it. If you're using VC++ directly, you should specify a full list of libs required.
