### ISSUE TITLE
Priority Load Balancer failure

### ISSUE THREAD

**Issue by Boronyak** [grpc/grpc#37639]
### What version of gRPC and what language are you using?
1.51.1
C++ Standard 17

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 11.4.0
cmake 3.22.1

### What did you do?
I have a preferred and a fallback grpc server and I need a load balancer at client which sends messages to the preferred server until the connection breaks with it. After that the client should choose the fallback server until the reconnection will be successful with the preferred server.
For this purpose I think the priority load balancer would be the best option.
I create a service config json string like this:
```
string service_config = R"({
  "loadBalancingConfig": [ {
    "priority_experimental": {
      "children": {
        "high_priority": {
          "config": [
            {"round_robin": {}} 
          ]
        },
        "low_priority": {
          "config": [
            {"round_robin": {}}
          ]
        }
      },
      "priorities": ["high_priority", "low_priority"] 
    }
  } ] 
} )";
```

I set the service config in the ChannelArgument object:
`arguments.SetServiceConfigJSON(service_config);`

Finally I create a channel:
`std::shared_ptr<grpc::Channel> channel = grpc::CreateCustomChannel(host + ":" + to_string(port), grpc::InsecureChannelCredentials(), arguments);`

### What did you expect to see?
The addresses returned by DNS resolver will be assigned to the given priorities.

### What did you see instead?
I am watching grpc trace logs during running and I have noticed this failure:

> I0828 09:51:58.415278637   12579 priority.cc:765]            [priority_lb 0x608845e62a90]
> child high_priority (0x608845e61d30): state update: TRANSIENT_FAILURE
> (UNAVAILABLE: empty address list: ) picker 0x608845e65f40

### Anything else we should know about your project / environment?
I figured out that the dns resolver returns 2 addresses but they would not be added to the high and low priorities because in `MakeHierarchicalAddressMap` method called from `PriorityLb::UpdateLocked` in **priority.cc** tries to get an attribute from address object with a `hierarchical_path` key. The resolved does not add an attribute like this.

My question is that how can I add this path attribute to the resolver to be able to assign the resolved addresses to the given priorities? An example of how to use the priority load balancer correctly would be nice of course. The result is the same with python 1.64.1 so I think it is not a version problem, I am missing something.

**Comment by markdroth** [comment]
There is not really any way to use the priority LB policy with the DNS resolver, specifically because the DNS resolver does not provide any priority information with the endpoint addresses that it returns.  There is no way for the priority policy to know which addresses should go to which children.

The priority LB policy is really intended to be used only with custom resolvers or parent LB policies that do add this kind of information, such as the infrastructure that we have for xDS.

**Comment by Boronyak** [comment]
@markdroth Thank you for the explanation. Can you give me an example in python how to use the priority LB correctly with custom resolvers or with xDS?

**Comment by markdroth** [comment]
There is not currently any way to write a custom resolver in python.  That's definitely something we want to support, but unfortunately we can't do that until we make a bit more progress on the EventEngine migration.  You can track progress on this feature in #11685.

If you're using xDS, then all you need to do is have your control plane send an EDS resource that has each endpoint in its own locality and then set the priorities on those localities appropriately.
