### ISSUE TITLE
protobuf mismatch between C++/Python for 1.66.1

### ISSUE THREAD

**Issue by snps-jfaust** [grpc/grpc#37656]
### What version of gRPC and what language are you using?
1.66.1, C++ and Python

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 17.11, Python 3.12.4

### What did you do?
Our C++ build uses GRPC 1.66.1. The protobuf version for that tag is 5.27.2 (from third_party/protobuf/CMakeLists.txt -> protobuf_VERSION_STRING). 

pip install of grpcio and grpcio-tools version 1.66.1 will install protobuf version 5.28.0.

This results in the following Python warning:

[...\Lib\site-packages\google\protobuf\runtime_version.py:112](file:///.../Lib/site-packages/google/protobuf/runtime_version.py#line=111): UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.0 at Feature.proto. Please avoid checked-in Protobuf gencode that can be obsolete.

### What did you expect to see?
I would expect to see that these versions match and no warning is generated.

### What did you see instead?
The warning

**Comment by gnossen** [comment]
@XuanWang-Amos

**Comment by XuanWang-Amos** [comment]
Hi, `grpc_tools` have a fixed dependency on protobuf version, currently it's 5.27.2, we'll update Protobuf version in our next release.

You can also find more details and our recommendation here: https://github.com/grpc/grpc/issues/37609#issuecomment-2341657936
