### ISSUE TITLE
Support code coverage reports on Jenkins for Python.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#3769]
Following the example of the node, https://github.com/grpc/grpc/blob/master/tools/run_tests/run_node.sh, the coverage report needs to be an index.html file in a subdirectory of `reports`.

**Comment by nicolasnoble** [comment]
Any ETA on providing code coverage reports for Python ?

**Comment by soltanmm** [comment]
Fixed in #4281
