### ISSUE TITLE
Potential NULL dereference when MakeInjectionDecision()

### ISSUE THREAD

**Issue by leeriorio** [grpc/grpc#37698]
In results of static analyse I found error of null dereference cathegory here:
 https://github.com/grpc/grpc/blob/1f70b34fb15ffb409553c5f7055cfd5cca61e98e/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L171-L177
 
 If `method_params != nullptr` will be false, value `fi_policy` won't be defined, but in 177 will be derefenced

**Comment by markdroth** [comment]
In practice, it's not actually possible for `method_params` to be null, because the code that generates the filter config from the xDS resource ensures that it will be present.  But I agree that the code should be a little more defensive, just in case there's a bug somewhere.
