### ISSUE TITLE
Support code coverage reports on Jenkins for Ruby.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#3770]
Following the example of the node, https://github.com/grpc/grpc/blob/master/tools/run_tests/run_node.sh, the coverage report needs to be an index.html file in a subdirectory of `reports`.

**Comment by nicolasnoble** [comment]
Any ETA on providing code coverage reports for Ruby ?

**Comment by murgatroid99** [comment]
We currently have this only for the extension.
