### ISSUE TITLE
prove Metadata pointer in call_creds_util

### ISSUE THREAD

**Issue by leeriorio** [grpc/grpc#37701]
In results of static analyze of grpc sources I found that statistically returns of calling of `get_pointer()` function are usually checked to nullptr 

https://github.com/grpc/grpc/blob/1f70b34fb15ffb409553c5f7055cfd5cca61e98e/src/core/lib/transport/metadata_batch.h#L1380-L1387

There is function `MakeServiceUrlAndMethod()` in [call_creds_util.cc](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/call_creds_util.cc), where pointers to metadata are getting with `get_pointer()` function without this check. 

https://github.com/grpc/grpc/blob/1f70b34fb15ffb409553c5f7055cfd5cca61e98e/src/core/lib/security/credentials/call_creds_util.cc#L60
and
https://github.com/grpc/grpc/blob/1f70b34fb15ffb409553c5f7055cfd5cca61e98e/src/core/lib/security/credentials/call_creds_util.cc#L60

Is it absolutely correct?

**Comment by yashykt** [comment]
Yeah, I believe before we reach this point, we have code that verifies that this metadata exists, but yeah, I think a debug check that this metadata exists would be good
