### ISSUE TITLE
Support code coverage reports on Jenkins for ObjC.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#3771]
Following the example of the node, https://github.com/grpc/grpc/blob/master/tools/run_tests/run_node.sh, the coverage report needs to be an index.html file in a subdirectory of `reports`.

**Comment by jcanizales** [comment]
Note: tool for code coverage: https://code.google.com/p/coverstory/wiki/UsingCoverstory

**Comment by jcanizales** [comment]
Another one, that integrates with Travis: https://github.com/codecov/example-xcode
