### ISSUE TITLE
Pointial Memory Leak in `atls_frame_protector.cc::alts_create_frame_protector()`

### ISSUE THREAD

**Issue by hribz** [grpc/grpc#37727]
Similar to #37692 , there is a pointial memory leak in this code snippet:

https://github.com/grpc/grpc/blob/536bbbf18191d8e0659f8e414dbab10263ed1720/src/core/tsi/alts/frame_protector/alts_frame_protector.cc#L376-L384

The memory allocated at line 377 is lost if the function return at line 383.

**Comment by drfloob** [comment]
@yijiem Looks like you've got a handle on lifetimes and ownerships of these types in https://github.com/grpc/grpc/issues/37692. This one looks similar. Ass Matt said, please add tests that fail under ASAN if possible.

N.B., it's not a great API if we have to dig to figure out who owns the pointer, and is responsible for freeing the memory. What is responsible for it in the success case? This API can be improved.
