### ISSUE TITLE
Support code coverage reports on Jenkins for PHP.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#3772]
Following the example of the node, https://github.com/grpc/grpc/blob/master/tools/run_tests/run_node.sh, the coverage report needs to be an index.html file in a subdirectory of `reports`.

**Comment by stanley-cheung** [comment]
PHP extension coverage report is now running on Jenkins: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/config=gcov,language=php,platform=linux/
