### ISSUE TITLE
Similar branches at v3_ncons.c

### ISSUE THREAD

**Issue by AlekseiGalkin** [grpc/grpc#37720]
The condition argument in [line 524](https://github.com/google/boringssl/blob/b8b3e6e11166719a8ebfa43c0cde9ad7d57a84f6/src/crypto/x509/v3_ncons.c#L524) is meaningless because it completely duplicates the previous line

Found by Linux Verification Center (portal.linuxtesting.ru) with SVACE.
Author: Alexey Galkin.

**Comment by yijiem** [comment]
That code link points to the boringssl project. Please file the issue with that project.
