### ISSUE TITLE
Support code coverage reports on Jenkins for C#.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#3773]
Following the example of the node, https://github.com/grpc/grpc/blob/master/tools/run_tests/run_node.sh, the coverage report needs to be an index.html file in a subdirectory of `reports`.

**Comment by jtattermusch** [comment]
Code coverage is now visible on pull requests. Due to platform limitations,

coverage of grpc_csharp_ext is measured on linux and coverage of C# code is measured on windows.
