### ISSUE TITLE
How to use gRPC on Windows in multiple DLLs?

### ISSUE THREAD

**Issue by bebuch** [grpc/grpc#37760]
If I build gRPC as a static library, my application crashes as soon as I use it in two different DLLs and then use these in the same EXE. At some point within the DLLs, there is a null pointer access violation because the two static gRPC code duplications in the DLLs do not get along.

I can't build a SHARED DLL under Windows at the moment because of #35794.

The only way to use gRPC on Windows at the moment is to build a STATIC lib and then use that in exactly one DLL or EXE within the application. This is an extremely bad workaround. If I build all my libraries STATIC, then I can use gRPC in several libraries. That makes sense, because in the end it is only linked into the EXE once. Unfortunately, this breaks our DLL-based plug-in interface.

Is there a better method? Is support for SHARED gRPC planned on Windows? STATIC gRPC does not work in DLL-based applications, but these are the de facto standard.

**Comment by drfloob** [comment]
The current stance is "DLLs are not officially supported", for reasons outlined in https://github.com/grpc/grpc/blob/48aa0c85ff5282b0f918afd99f563d53cc542816/BUILDING.md#windows-a-note-on-building-shared-libs-dlls

Handing it over to @veblush in case there are any plans to change that, but I haven't heard of any such plans.

**Comment by drfloob** [comment]
This is a duplicate of a feature request: https://github.com/grpc/grpc/issues/33032
