### ISSUE TITLE
Ruby Request Object #to_h method skipped enum field when value index is 0

### ISSUE THREAD

**Issue by yakjuly** [grpc/grpc#37774]
### What version of gRPC and what language are you using?
grpc gem 1.65, ruby

### What operating system (Linux, Windows,...) and version?
Mac OS 14.6.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang-1500.3.9.4

### What did you do?

https://raw.githubusercontent.com/ganmacs/grpc_mock/210bb92533559b0409bf5db11f5e5ce0732cd986/spec/examples/request/request.proto
```
syntax = "proto3";

package request;

service request {
  rpc Hello(HelloRequest) returns (HelloResponse) {}

  rpc HelloServerStream(HelloRequest) returns (stream HelloStreamResponse) {}

  rpc HelloClientStream(stream HelloStreamRequest) returns (HelloResponse) {}

  rpc HelloStream(stream HelloStreamRequest) returns (stream HelloStreamResponse) {}
}

enum PhoneType {
  MOBILE = 0;
  HOME = 1;
  WORK = 2;
}

message HelloRequest {
  string msg = 1;
  InnerRequest inner = 2;
  int64 n = 3;
  PhoneType ptype = 4;
}

message InnerRequest {
  string msg = 1;
  int64 n = 2;
  PhoneType ptype = 3;
}

message HelloResponse {
  string msg = 1;
}

message HelloStreamRequest {
  string msg = 1;
}

message HelloStreamResponse {
  string msg = 1;
}
```

After I generated ruby client code with this proto file.
```
request = Request::HelloRequest.new(msg: "hello2!", inner: Request::InnerRequest.new(msg: "hello!", n: 11, ptype: :WORK), n: 10, ptype: :MOBILE)
request.to_h

# in grpc 1.64.0
{:msg=>"hello2!", :inner=>{:msg=>"hello!", :n=>11, :ptype=>:WORK}, :n=>10, :ptype=>:MOBILE}
# in grpc 1.65.2
{:msg=>"hello2!", :inner=>{:msg=>"hello!", :n=>11, :ptype=>:WORK}, :n=>10}
```

### What did you expect to see?
`{:msg=>"hello2!", :inner=>{:msg=>"hello!", :n=>11, :ptype=>:WORK}, :n=>10, :ptype=>:MOBILE}`
I expect `:ptype => :MOBILE` appears in `#to_h` output.

### What did you see instead?
`{:msg=>"hello2!", :inner=>{:msg=>"hello!", :n=>11, :ptype=>:WORK}, :n=>10}`
In grpc 1.65.2, If a enum field value index is 0, that field will be ignored in `to_h` method. In this case `:MOBILE` is options 0.

### Anything else we should know about your project / environment?
No

**Comment by apolcyn** [comment]
This issue looks like it belongs in the protobuf repo (you don't need grpc to repro this) - https://github.com/protocolbuffers/protobuf

It's worth noting that grpc's `google-protobuf` dependency was effectively upgraded between our 1.64 and 1.65 releases.

1.64 grpc has `google-protobuf ~> 3.25`

1.65 has `google-protobuf >= 3.25`

So what you're seeing here is probably a difference in protobuf versions (b/t a 3.x version and 4.x version)
