### ISSUE TITLE
CMake example projects preprending an extra `/usr` folder to paths

### ISSUE THREAD

**Issue by abramsba** [grpc/grpc#37798]
### What version of gRPC and what language are you using?
1.66.1, attempting to compile C++ hello world

### What operating system (Linux, Windows,...) and version?
Raspbian (Debian 12, Kernel 6.6)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
I simply followed the getting started guide. The prefix path was `/` to install system wide.

### What did you expect to see?
I would expect that the example cmake projects after installing grpc to system are able to be compiled as is without modification.

### What did you see instead?
CMake always reports back errors because all paths after installing are prepended with `/usr/usr` and thus the corresponding cmake files are not found.

```
root@runnerpi:~/grpc/examples/cpp/helloworld/cmake/build# cmake ../..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Using protobuf 27.2.0
-- Using gRPC 1.66.1
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "gRPC::grpc++_reflection" includes non-existent path

    "/usr/usr/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by yashykt** [comment]
I'm suspecting that something went wrong in the installation steps or in the environment which led to grpc being installed in `/usr/usr`. Can you post the steps you followed please? Since we are suspecting an environment issue, you can also try installing this in a fresh docker container.
