### ISSUE TITLE
grpc hits SIGILL on riscv64

### ISSUE THREAD

**Issue by nanonyme** [grpc/grpc#37791]
### What version of gRPC and what language are you using?
1.66.1

### What operating system (Linux, Windows,...) and version?
Linux riscv64

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 14.1

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
grpc works normally

### What did you see instead?
grpc randomly hits SIGILL

The problem is that grpc has quite old submodule of abseil-cpp which SIGILL's on riscv64. Please update. Specifically this change https://github.com/abseil/abseil-cpp/pull/1644 is needed.

**Comment by nanonyme** [comment]
So basically submodule version of abseil-cpp attempts to for certain time operations use instruction RDCYCLE on riscv64 which is no longer allowed by kernel.

**Comment by yashykt** [comment]
Is this fixed on the latest abseil version?

**Comment by nanonyme** [comment]
Yes, at least 20240722.0-0-g4447c7562e3bc702ade25105912dce503f0c4010 is a known-good version. The fix MR is in the description. It's not necessarily obvious since it says it drops support but in reality it just stops using unsupported syscall and switches to different implementation.

**Comment by yashykt** [comment]
Absl was upgraded in https://github.com/grpc/grpc/pull/37543. You should get this by default in the next grpc release, but also, you don't need to wait for that and simply update the absl dependency. For example, if you are using bazel, you could override the absl dependency with the latest version.
