### ISSUE TITLE
Required Metadata/HTTP Headers in .proto

### ISSUE THREAD

**Issue by WizMe-M** [grpc/grpc#37808]
### Is your feature request related to a problem? Please describe.
It's related to Swagger codegen from `.proto` files. 
In gRPC notation is not possible to specify required Metadata (HTTP request headers). 

Because of that generated swagger API description has no required header parameters and next codegen from that swagger description misses that required parameters!
Also it would be nice if server could check for required Metadata properties.

### Describe the solution you'd like
I want to have an option to configure `rpc` with headers/metadata like this:
```proto
service MyService {

  rpc RefreshToken(google.protobuf.Empty) returns (JwtTokensResponse) {
    option (google.api.http) = {
      get: '/v1/token/refresh'
      meta: [
       {
         name: 'Authorization
         required: true
       } 
      ]
    };
  }
```

**Comment by yashykt** [comment]
We haven't had much discussion around this yet, but in general, adding this to proto files would require rebuilding binaries. A nicer way to do this would be to do this more dynamically through something like service config or xDS.

**Comment by yashykt** [comment]
cc @markdroth @ejona86 @dfawley @ctiller

**Comment by ejona86** [comment]
"required" is an interesting choice for an example, as we don't generally do that even for protobuf (proto3)!

In Java you could do this today (with custom `option`) with a custom interceptor. I do think things get weird quick, as what should the error be? Clearly here it should be UNAUTHENTICATED, but gRPC wouldn't know what to do in each case. And having to define the status in each proto option also isn't all that great.

I'm also not sure what we gain by this. This is going to be a runtime failure, so why not just let the server fail the RPC? If you want to tell your users to use authentication, a comment is just as good as a machine-readable option.

**Comment by drfloob** [comment]
@ejona86 are you waiting for further discussion on this, or should it be closed?

**Comment by ejona86** [comment]
Actually, it seems this is about REST conversion. So this would be a feature added to github.com/googleapis/googleapis . You might have success talking with https://github.com/grpc-ecosystem/grpc-gateway folks, as they are much more aligned on this sort of thing.
