### ISSUE TITLE
Feature Request: Support for RPC method with two stream requests and one stream response

### ISSUE THREAD

**Issue by jasseur2017** [grpc/grpc#37818]
#### Overview
I'm proposing a new feature that allows the definition of gRPC methods where the server accepts multiple independent stream requests (e.g., two or more) and processes these streams concurrently, returning a single stream response.

#### Motivation
Currently, gRPC supports bidirectional streaming, where both client and server can stream data. However, it is limited to one request stream and one response stream. For some use cases, it would be useful for the server to handle multiple concurrent request streams (from the same client) while sending back a unified or processed stream as the response.

#### Use Cases
1. **File transfer and processing**: A client may stream two large files (or multiple files) concurrently to a server, which processes the data and streams back results in a single response stream.
2. **Multi-data source streaming**: Scenarios where a client needs to stream data from two independent sources (or more) and the server performs real-time merging or processing on those streams, then responds with a single stream of results.
3. **Real-time collaboration applications**: For applications requiring concurrent real-time input (e.g., from multiple sensors, cameras, or other data sources), the server can consume multiple streams of data, process them together, and return a single result.

#### Proposal
Introduce a new method signature in `.proto` files that allows for defining multiple request streams. For example:

```proto
service MultiStreamService {
  rpc MultiStream(stream Request1, stream Request2) returns (stream Response);
}

**Comment by yashykt** [comment]
how would that map to the transport HTTP2 protocol? Note that the current protocol is at https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

**Comment by jasseur2017** [comment]
I solved the issue with WebSocket
