### ISSUE TITLE
Threading issue when destroying channel object on gRPC thread

### ISSUE THREAD

**Issue by js-nano** [grpc/grpc#37858]
### What version of gRPC and what language are you using?
C++, 1.60.1

### What operating system (Linux, Windows,...) and version?
Linux -- Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 11.4.0

### What did you do?

We have a unary client RPC, using the async callback API.  We are storing the associated `grpc::Channel` in the callback -- we've got a long-running call, and we want a straightforward way to guarantee that the channel stays around until the call is complete.

Unfortunately, we get an error `pthread_join failed: Resource deadlock avoided`.  This appears to occur when the channel is the last channel, and it is destroyed in the gRPC callback thread.  In this case, it seems like:
- The channel destructor cleans up a gRPC thread
- The channel destructor therefore joins the thread that is being cleaned up
- However, the channel destructor is running on the thread that's being joined -- hence a deadlock and the error message
- The channel destructor is running on the thread that's being joined because it's running in a gRPC callback

We have worked around the problem for now by wrapping the `Channel` in a class that causes the destructor to be run on an application thread.  Ideally we wouldn't have to do that in user code.

I think that this problem likely affects all callback-based client APIs, since the callbacks run in the gRPC internal thread pool.

<details>
    <summary>Example code</summary>

The code looks something like:

```c++
std::shared_ptr<grpc::Channel> channel;  // Channel obtained from somewhere
std::unique_ptr<Test::Stub> stub = Test::NewStub(channel);

struct CallState {
    ClientContext context;
    Test::UnaryRequest request;
    Test::UnaryResponse response;
};

auto call_state = std::make_unique<CallState>();

stub->async()->UnaryCall(
    &call_state->context,
    &call_state->request,
    &call_state->response,
    [channel = std::move(channel), stub = std::move(stub), call_state = std::move(call_state)]
    (grpc::Status status) {
        std::cout << "Done";
        // Omitted code to allow main thread to wait for call completion
    }
);
```

The "code to allow main thread to wait for call completion" would be something like a `std::promise` that's set in the UnaryCall callback, with its `std::future` being waited on in the main thread.

</details>

### What did you expect to see?
The channel lifetime is managed by the callback successfully

### What did you see instead?
error `pthread_join failed: Resource deadlock avoided`

**Comment by yashykt** [comment]
If you can provide a reproduction, that would be helpful.

**Comment by drfloob** [comment]
@js-nano This is a known bug right now, and a longer-term fix is in progress, expected to land in H1 next year. When using the Callback API today, the callback thread pool can't be shut down from inside a callback. That pool implementation is being replaced, and the new implementation handles this edge case.

> We have worked around the problem for now by wrapping the Channel in a class that causes the destructor to be run on an application thread. Ideally we wouldn't have to do that in user code.

That's a decent workaround. If you can restructure your application so that the last ref is held by your main thread, that would work too.

**Comment by js-nano** [comment]
> Channels are ref-counted, and every call internally already holds a ref on the channel

This was interesting, so we looked deeper into not explicitly holding a `shared_ptr<grpc::Channel>` in the callback.  It seems that there's one held within the `grpc::ClientContext`, which we also kept alive in the callback, so we run into the same bug, just now going via the `grpc::ClientContext`.

According to the docs:
> The [ClientContext] https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_context.html) instance used for creating an rpc must remain alive and valid for the lifetime of the rpc.

So, it looks like we're back in the same boat.

**Comment by js-nano** [comment]
> This is a known bug right now, and a longer-term fix is in progress, expected to land in H1 next year.

Awesome, good to have this confirmed.

**Comment by garrettkajmowicz** [comment]
I'm running into the same issue. Is it possible to mark this as open to have a ticket to track? Or is there another ticket we can follow which will include the relevant fix?
