### ISSUE TITLE
https://github.com/grpc/grpc/issues/34721

### ISSUE THREAD

**Issue by logstashbugreporter** [grpc/grpc#37953]
### What version of gRPC and what language are you using?
1.64.0. python gRPC 

### What operating system (Linux, Windows,...) and version?
Linux:

```
NAME="Common Base Linux Mariner"
VERSION="2.0.20240829"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```

### What did you do?
We're encountering intermittent remote resets errors when using Envoy with Python gRPC services connected via UDS channels. Specifically, a client sending health check requests every 30 seconds consistently encounters this issue when creating a new channel for each request.
client side error observed:

```
728164723 {0.434192419052124} <Result port_grpc_21519 result=False service=<Service code-health-policy-engine-grpc+i001 1d6d126bf13db575dacd354b003cc6da5562e2f0> extra={"secure": "UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: remote reset", "insecure": "UNAVAILABLE: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:10.205.1.173:21519: Socket closed", "oor": false}>
```

Key Observations:

No errors with Rust services: We do not observe this issue with Rust gRPC services deployed with Envoy via UDS.
No errors if the client reuse the channel cross subsequent requests.
Error frequency: The error occurs once out of 30 requests.
Envoy trace logs: Envoy logs indicate a "remote reset" from the upstream server.
Error code: see gRPC service debug logs and envoy debug logs below.
Repro steps:
python gRPC service connected with envoy via UDS:
client request:

```
 while True:
    with grpc.secure_channel(url, cred) as channel:
        stub = HealthStub(channel)
        req = HealthCheckRequest(service='')
        try:
            res = stub.Check(req, timeout=timeout)
            success += 1
            counter += 1
            print(f'{counter=}, {success=}, {failure=}')
        except grpc.RpcError as ex:
            code, details = ex.code(), ex.details()
            failure += 1
            counter += 1
            print(f'{counter=}, {success=}, {failure=}, {code=}, {details=}')

class HealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/grpc.health.v1.Health/Check',
                request_serializer=obhc_dot_messages_dot_grpc__health__v1__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=obhc_dot_messages_dot_grpc__health__v1__pb2.HealthCheckResponse.FromString,
                )
```

### What did you expect to see?
All health check requests succeed 

### What did you see instead?
healthcheck requests fail occasionally (1 out of 30 requests) 

### Anything else we should know about your project / environment?
here are debug logs from python gRPC server side: 

```
`I1018 16:08:25.629690613   44342 parsing.cc:338]                       INCOMING[0x7c1100057710]: HEADERS:END_HEADERS len:61 id:0x000009c5
D1018 16:08:25.629709085   44342 chttp2_transport.cc:812]              HTTP:0x7c1100057710/0x7c11000e5e40 creating accept stream 2501 [from 0x9c5]
I1018 16:08:25.629721515   44342 call.cc:1458]                         ops[0]: RECV_INITIAL_METADATA ptr=0x7c11000e5578
D1018 16:08:25.629725739   44342 call.cc:1802]                         BATCH:0x7c11000e6d30 START:{kRecvInitialMetadata} BATCH: RECV_INITIAL_METADATA (tag:0x7c11000e5590)
I1018 16:08:25.629729450   44342 parsing.cc:720]                       [t:0x7c1100057710 fd:35 peer:unix:] Accepting new stream; num_incoming_streams_before_settings_ack=4294966045
I1018 16:08:25.629732383   44342 parsing.cc:761]                       parsing initial_metadata
D1018 16:08:25.629734760   44342 parsing.cc:892]                       INCOMING[0x7c1100057710;0x7c11000e5e40]: Parse 61b last frame fragment with header
D1018 16:08:25.629742673   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: :path: /grpc.health.v1.Health/Check
D1018 16:08:25.629746691   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: :authority: lca1-app38344.corp.linkedin.com:21519
D1018 16:08:25.629750324   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: :method: POST
D1018 16:08:25.629753773   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: :scheme: https
D1018 16:08:25.629770370   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: content-type: application/grpc
D1018 16:08:25.629773465   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: te: trailers
D1018 16:08:25.629775767   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: grpc-accept-encoding: identity, deflate, gzip
D1018 16:08:25.629779159   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: grpc-timeout: 9900ms
D1018 16:08:25.629782171   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: user-agent: grpc-python/1.66.2 grpc-c/43.0.0 (linux; chttp2)
D1018 16:08:25.629785212   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: x-forwarded-proto: https
D1018 16:08:25.629793626   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR: x-request-id: 5d26df4e-c270-43d7-9a89-a6dd3ba694ff (parse error: INTERNAL: Error parsing ':method' metadata [type.googleapis.com/grpc.status.int.stream_id='0'])
D1018 16:08:25.629801776   44342 hpack_parser.cc:706]                  HTTP:2501:HDR:SVR:x-forwarded-client-cert:By=.....;By=.....;Hash=.....;Cert="-----BEGIN%20CERTIFICATE-----.....-----END%20CERTIFICATE-----%0A";Subject="CN=....,OU=Tools,O=....,L=Mountain View,ST=California,C=US";URI=....;URI=...2.0.0) (parse error: INTERNAL: Error parsing ':method' metadata [type.googleapis.com/grpc.status.int.stream_id='0'])E1018 16:08:25.629810589   44342 parsing.cc:904]                       INCOMING[0x7c1100057710;0x7c11000e5e40]: Parse failed with INTERNAL: Error parsing ':method' metadata [type.googleapis.com/grpc.status.int.stream_id='0']
D1018 16:08:25.629817193   44342 chttp2_transport.cc:2304]             MARK_STREAM_CLOSED: t=0x7c1100057710 s=0x7c11000e5e40(id=2501) read+write [INTERNAL:Error parsing ':method' metadata {stream_id:0}]
D1018 16:08:25.629839861   44342 chttp2_transport.cc:2092]             maybe_complete_recv_trailing_metadata cli=0 s=0x7c11000e5e40 closure=(nil) read_closed=1 write_closed=1 0
D1018 16:08:25.629843338   44342 chttp2_transport.cc:2092]             maybe_complete_recv_trailing_metadata cli=0 s=0x7c11000e5e40 closure=(nil) read_closed=1 write_closed=1 0
`
```

Here are debug logs from the envoy side:

```
[2024-10-09 16:57:46.831][182][trace][connection] [source/common/network/connection_impl.cc:568] [C8] socket event: 3
[2024-10-09 16:57:46.831][182][trace][connection] [source/common/network/connection_impl.cc:679] [C8] write ready
[2024-10-09 16:57:46.831][182][trace][connection] [source/common/network/connection_impl.cc:608] [C8] read ready. dispatch_buffered_data=0
[2024-10-09 16:57:46.831][182][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C8] read returns: 26
[2024-10-09 16:57:46.831][182][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C8] read error: Resource temporarily unavailable
[2024-10-09 16:57:46.831][182][trace][http2] [source/common/http/http2/codec_impl.cc:969] [C8] dispatching 26 bytes
[2024-10-09 16:57:46.831][182][trace][http2] [source/common/http/http2/codec_impl.cc:1071] [C8] about to recv frame type=3, flags=0, stream_id=45913
[2024-10-09 16:57:46.831][182][trace][http2] [source/common/http/http2/codec_impl.cc:2024] [C8] track inbound frame type=3 flags=0 length=4 padding_length=0
[2024-10-09 16:57:46.831][182][trace][http2] [source/common/http/http2/codec_impl.cc:1097] [C8] recv frame type=3
[2024-10-09 16:57:46.831][182][trace][http2] [source/common/http/http2/codec_impl.cc:1202] [C8] remote reset: 2
[2024-10-09 16:57:46.831][182][debug][http2] [source/common/http/http2/codec_impl.cc:1363] [C8] stream 45913 closed: 2
[2024-10-09 16:57:46.831][182][debug][client] [source/common/http/codec_client.cc:156] [C8] request reset
[2024-10-09 16:57:46.831][182][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=1)
[2024-10-09 16:57:46.831][182][debug][pool] [source/common/conn_pool/conn_pool_base.cc:215] [C8] destroying stream: 0 remaining
[2024-10-09 16:57:46.831][182][debug][router] [source/common/router/router.cc:1208] [C1779151][S16507185947364583566] upstream reset: reset reason: remote reset, transport failure reason:
[2024-10-09 16:57:46.832][182][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=2)
[2024-10-09 16:57:46.832][182][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=3)
[2024-10-09 16:57:46.832][182][debug][http] [source/common/http/filter_manager.cc:967] [C1779151][S16507185947364583566] Sending local reply with details upstream_reset_before_response_started{remote_reset}
[2024-10-09 16:57:46.832][182][debug][http] [source/common/http/conn_manager_impl.cc:1596] [C1779151][S16507185947364583566] encoding headers via codec (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: remote reset'
'date', 'Wed, 09 Oct 2024 16:57:46 GMT'
'server', 'envoy'
```

**Comment by logstashbugreporter** [comment]
we submitted an envoy issue https://github.com/envoyproxy/envoy/issues/36552, where we were advised to submit an gRPC issue.

**Comment by logstashbugreporter** [comment]
I also read the previous issue https://github.com/grpc/grpc/issues/34721, not sure whether it is the same or related: 
The previous issue stated that "after a HEAD request, all valid messages going through the same HTTP/2 connection fail with a 503," and that "the server rejects all subsequent requests once a corrupted request comes in." In our case, normal requests only fail occasionally—about 1 in 30 to 40.
It also mentions that the previous problem was fixed in grpcio>=1.62.0, and we’re using 1.64.0.

**Comment by logstashbugreporter** [comment]
btw, this is blocking issue for us, I could not seem to change the bug priority though

**Comment by logstashbugreporter** [comment]
this can be repro by first running  curl  Rest OPTION requests, it seems like that python gRPC service is confused by this Rest request,  has this error "parse error: INTERNAL: Error parsing ':method' metadata [type.googleapis.com/grpc.status.int.s
tream_id='0'])"
once the server is in this state, legit gRPC health check requests also get this errors, maybe 10% of requests get this error.

**Comment by gnossen** [comment]
It took a stab at reproducing what you described and am not seeing the same issue. All successful. Can you [take a look](https://github.com/gnossen/repro-37953/tree/main) and see if any of this differs materially from your setup?

**Comment by logstashbugreporter** [comment]
@gnossen, thanks for looking into this! I’ll review your GitHub more closely tomorrow.
Quick note on the repro steps: Step 1 is necessary; without it, no errors occur in Step 2.

(1) Run a curl OPTIONS request (non-gRPC request):
curl -f ei-ltx1 -X OPTIONS "https://[yourhostname]:[your grpc port number]/" --insecure
This will show a "reset reason: remote reset" error.
(2) Then, run your health check gRPC requests. My test script sends gRPC health check requests back-to-back, and the health check request occasionally fails (about 1 in 20-40 requests).

**Comment by gnossen** [comment]
@logstashbugreporter Thanks for the pointer. I was indeed missing the `OPTIONS` request and with it, I can reproduce. Here's what I found:

||With Channel Sharing | Without Channel Sharing |
|--|--|--|
|Requests sent to Envoy|no errors|errors|
|Requests sent to gRPC UDS|no errors|no errors|

In all cases, the `OPTIONS` request was sent to the Envoy. When the `OPTIONS` request is sent to the gRPC server directly,  none of these combinations results in an error.

These results seem to suggest that this is an Envoy bug, but I'm definitely open to the possibility that gRPC is involved in it somehow.

**Comment by logstashbugreporter** [comment]
@gnossen Thanks for the followup and the update! While we’ve also noticed that this bug occurs only with Envoy, we believe it still originates in the Python gRPC layer (C++ gRPC library) for the following reasons:

1. We have the same Envoy setup with a Rust gRPC application, and using the same steps, we cannot reproduce the issue; it only arises with Python gRPC.
2. We think Envoy uncovers a corner case error in Python gRPC. Envoy adds headers to the original request, which may explain why the issue doesn’t occur without it. Additionally, the first packet during connection establishment may have longer or additional headers, potentially triggering this error in scenarios where we create a new channel for each subsequent request. We could not reproduce the issue with channel sharing (assuming you mean reusing the channel). This bug may relate to header length or count.
3. The gRPC debug trace error message states: "Parse failed with INTERNAL: Error parsing '
' metadata [type.googleapis.com/grpc.status.int.stream_id='0']." This error does not accurately reflect the situation (a non-gRPC request). This may indicate that gRPC is confused when parsing the headers, reinforcing that the root cause lies within gRPC itself.

please note that @dmmitiaev reported the same error in updated version of gRPC in https://github.com/grpc/grpc/issues/34721

**Comment by gnossen** [comment]
Thank you for the detailed response.

I'm still in the process of determining the root cause, but I _have_ found that this issue does not occur when the gRPC Python server is running the most recent release (v1.67.0). Can you please confirm?

**Comment by logstashbugreporter** [comment]
@gnossen, thanks for the pointer! We tried v1.67.0 on our test service and couldn’t reproduce the issue locally. Could we please keep this issue open for now while we verify it in production next week? Thanks, and have a great weekend!

**Comment by logstashbugreporter** [comment]
@gnossen thanks for all your help! we have verified in production that v 1.67.0 fixed the issue.

**Comment by sreenithi** [comment]
Thanks for verifying @logstashbugreporter. I'm hence marking this issue as fixed.
