### ISSUE TITLE
Protoc command doesn’t show dependencies properly in pipdeptree

### ISSUE THREAD

**Issue by sparky2708** [grpc/grpc#37964]
Environment: Using Python 3.12 and latest grpcio-tools library.

When running `pipdeptree` on grpcio-tools library:

1. shows incorrect dep to protobuf (related to previous issue I raised)
2. doesn’t show dependency on mypy package although it needs it when it runs with the mypy argument 
3. missing dependency on package used when using grpc_out argument

**Comment by sourabhsinghs** [comment]
@sparky2708  Please add more information regarding the issues. Add some sample code to repro the issues.
