### ISSUE TITLE
 ERROR: Failed building wheel for grpcio-tools

### ISSUE THREAD

**Issue by SD-13** [grpc/grpc#37963]
### What version of gRPC and what language are you using?
1.67.0

### What operating system (Linux, Windows,...) and version?
Arch Linux (6.10.6-arch1-1)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.12

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I included grpcio and grpcio-tools in `requirements.in` and when compiling (with below command) requirements.txt file I am getting the error.
`pip-compile --no-emit-index-url --generate-hashes requirements.in --output-file requirements.txt`

setuptools: 75.2.0
pip-tools: 7.4.1
pip: 24.2

### What did you expect to see?
I expected wheel package built for grpcio-tools without any error

### What did you see instead?
```
              g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DHAVE_PTHREAD=1 -I. -Igrpc_root -Igrpc_root/include -Ithird_party/protobuf/src -I/home/jack/.pyenv/versions/opp12/include -I/home/jack/.pyenv/versions/3.12.0/include/python3.12 -c third_party/protobuf/src/google/protobuf/empty.pb.cc -o build/temp.linux-x86_64-cpython-312/third_party/protobuf/src/google/protobuf/empty.pb.o -std=c++14 -fno-wrapv -frtti
              error: command '/usr/bin/g++' failed with exit code 1
              [end of output]

          note: This error originates from a subprocess, and is likely not a problem with pip.
          ERROR: Failed building wheel for grpcio-tools
          Running setup.py clean for grpcio-tools
        Failed to build grpcio-tools
        ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (grpcio-tools)
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by sourabhsinghs** [comment]
@SD-13  I was able to run the commands provided without any errors on my linux machine.
It seems like you have some dependency missing. Can you  try to use a docker container just to be sure issue is with the machine.

**Comment by SD-13** [comment]
Can't reproduce it. Closing this issue
