### ISSUE TITLE
grpc python service multiprocess cannot use the same UDS socket

### ISSUE THREAD

**Issue by gillmylady** [grpc/grpc#37984]
### What version of gRPC and what language are you using?
grpcio 1.64.0

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10

### What did you do?
Start multiprocess of UDS like example [here](https://github.com/grpc/grpc/blob/master/examples/python/uds/greeter_server.py), below is my script,
```
"""The gRPC AsyncIO server for the UDS example."""

import asyncio
import logging
import multiprocessing
import os

import grpc
import helloworld_pb2
import helloworld_pb2_grpc

log = logging.getLogger(__name__)


class Greeter(helloworld_pb2_grpc.GreeterServicer):
    async def SayHello(
        self,
        request: helloworld_pb2.HelloRequest,
        context: grpc.aio.ServicerContext,
    ) -> helloworld_pb2.HelloReply:
        log.info(f'request={request}, pid={os.getpid()}')
        del request
        return helloworld_pb2.HelloReply(message=f"Hello to {context.peer()}!")


async def serve() -> None:
    uds_addresses = ["unix:helloworld.sock", "unix:///tmp/helloworld.sock"]
    server = grpc.aio.server()
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    for uds_address in uds_addresses:
        server.add_insecure_port(uds_address)
        logging.info("Server listening on: %s", uds_address)
    await server.start()
    await server.wait_for_termination()


def start_worker():
    asyncio.run(serve())

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    workers = []

    def _start_worker():
        worker = multiprocessing.Process(target=start_worker)
        worker.start()
        log.info(f'start worker {worker.pid}')
        return worker

    for _ in range(3):
        workers.append(_start_worker())
``` 

Then start this server with multiple processes, and then run the client to send sample requests. 

### What did you expect to see?
All processes should be able to take requests, just like how multiprocessing is supported by grpc at [here](https://github.com/grpc/grpc/blob/master/examples/python/multiprocessing/server.py)

### What did you see instead?
Only one process takes request. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
We did some investigation that multiple process cannot reuse UDS file handler. We want to know whether the grpc team has some knowledge how this could be accomplished. Thank you!

**Comment by sourabhsinghs** [comment]
@gillmylady  Can you provide more details, sample client / server code . to repro the issue.

**Comment by gillmylady** [comment]
Hey, thank you for taking a look!
I provided the sample server code in the description to start 3 processes. You can use other existing greeter-client code to send requests.
Then, in the server code console, you should see the process ID for each request, and find the process ID the same no matter how many requests you send. Let me know if you need something else.

Best,
Han

On Oct 28, 2024, at 8:34 AM, Sourabh Singh ***@***.***> wrote:

﻿

@gillmylady<https://github.com/gillmylady> Can you provide more details, sample client / server code . to repro the issue.

**Comment by sreenithi** [comment]
Hi @gillmylady, like you rightly said, the UDS socket file handler does not support the `so.reuseport` option. It is only supported by TCP ports, and hence if you don't have any specific reason to use UDS sockets, you can try using TCP sockets.
If you do have to use a UDS socket, you will have to do something like use a UDP socket in the parent process, and a proxy TCP socket with `so.resuseport` enabled that the child processes can use.

**Comment by gillmylady** [comment]
Thank you! I can take a try. Do your team know whether this approach is stable and reliable for production usage? Are unary/stream, sync/async working normally?

Best,
Han

On Nov 5, 2024, at 9:22 AM, Sreenithi Sridharan ***@***.***> wrote:

﻿

Hi @gillmylady<https://github.com/gillmylady>, like you rightly said, the UDS socket file handler does not support the so.reuseport option. It is only supported by TCP ports, and hence if you don't have any specific reason to use UDS sockets, you can try using TCP sockets.
If you do have to use a UDS socket, you will have to do something like use a UDP socket in the parent process, and a proxy TCP socket with so.resuseport enabled that the child processes can use.

**Comment by sreenithi** [comment]
Hi @gillmylady, both TCP and UDS sockets are safe for production usage for all the use cases you mentioned. You can give it a try and see if it solves the problem
