### ISSUE TITLE
GRPC Python client sends an unexpected EOF after a streaming/polling subscription request is sent

### ISSUE THREAD

**Issue by saranya-satyavolu07** [grpc/grpc#37992]
### What version of gRPC and what language are you using?
1.56.0-dev, Python GRPC client, Go GRPC server

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
1) The server is implemented in golang (Using gnmi libraries). Subscription is implemented for the 3 methods (ONCE, SAMPLE, POLL). Fired a subscription request using a python client using the SAMPLE method, 

### What did you expect to see?
Subscription should work as expected. 

### What did you see instead?
The GRPC connection seems to close as the python client sends an EOF. The same is not seen with go clients

Python client grpc logs

**I1018 15:57:16.251571000 123145524658176 parsing.cc:697]               parsing trailing_metadata
D1018 15:57:16.251608000 123145524658176 parsing.cc:812]               INCOMING[0x7fc52e36ea00;0x7fc52e370280]: Parse 27b last frame fragment with header
D1018 15:57:16.251663000 123145524658176 chttp2_transport.cc:2040]     maybe_complete_recv_trailing_metadata cli=1 s=0x7fc52e370280 closure=0x7fc52e370248 read_closed=0 write_closed=1 7
D1018 15:57:16.251705000 123145524658176 chttp2_transport.cc:2206]     MARK_STREAM_CLOSED: t=0x7fc52e36ea00 s=0x7fc52e370280(id=1) read [OK]
D1018 15:57:16.251744000 123145524658176 chttp2_transport.cc:2040]     maybe_complete_recv_trailing_metadata cli=1 s=0x7fc52e370280 closure=0x7fc52e370248 read_closed=1 write_closed=1 7**

Go server grpc logs

[16119]2023/10/18 06:32:11 http2: Framer 0x40015201c0: read DATA flags=END_STREAM stream=1 len=0 data=""

Found a similar issue reported earlier, didn't help much though https://github.com/grpc/grpc/issues/7192

**Comment by sourabhsinghs** [comment]
@saranya-satyavolu07 Can you provide a sample client / server code to repro the issue. or a docker file.

**Comment by Raj998** [comment]
Keeping the connection open on the server side (even after client sending EOF) can resolve this issue.
