### ISSUE TITLE
Failure to wipe out existing repository on Windows

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3802]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3720/config=dbg,language=c,platform=windows/console

.... looks like there are still locks on built artifacts.

**Comment by ctiller** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/config=dbg,language=csharp,platform=windows/3729/console

**Comment by nicolasnoble** [comment]
Yeah... unfortunately, that's kind of very Windows-y specific...

Well, the exact title should probably be "Why are the tests that are timeouting not being killed under Windows ?" or something like this...

**Comment by jtattermusch** [comment]
Alright, so the latter (build 3729) is actually caused by port server - see #3813.

The cause of the occurrence is still unknown to me - but I found that the build artifacts (like h2_compress_trailing_metadata_test.exe) don't stay locked forever - eventually they can be deleted by hand. So perhaps this is a timing issue.

**Comment by ctiller** [comment]
Elevating to P0 on the basis that we haven't had a successful PR for a few days due to this.

**Comment by ctiller** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Locked+Files+Report+Plugin
Seems useful

**Comment by ctiller** [comment]
http://superuser.com/questions/335138/how-to-close-all-file-handles-under-a-given-folder-programatically

Seems like a nice hammer

**Comment by ctiller** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/13061/config=dbg,language=c,platform=windows/console

**Comment by jtattermusch** [comment]
I think we are over this.
