### ISSUE TITLE
Metadata plugins do not propagate the error_details to the status

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#3803]
I have a test with a metadata plugin that sets a non-OK status and sets `error_details` in the callback. The call correctly ends with a non-OK status and the expected status code, but it gets empty status details instead of the specified details string.

**Comment by jboeuf** [comment]
@ctiller, looks like we'll need to add a `gpr_slice *optional_message` parameter to `grpc_transport_stream_op_add_cancellation` in order to surface the status details from the client auth filter.

**Comment by jboeuf** [comment]
@ctiller, I'm happy to open an issue for that. Let me know.

**Comment by murgatroid99** [comment]
Ping

**Comment by jboeuf** [comment]
Assigning @ctiller since we need a slight API change on his part.

**Comment by ctiller** [comment]
API's should be in place

**Comment by murgatroid99** [comment]
Ping

**Comment by jboeuf** [comment]
@ctiller, I don't see an optional message in `grpc_transport_stream_op_add_cancellation`. Should I use `grpc_transport_stream_op_add_close` instead from the client auth filter?

**Comment by murgatroid99** [comment]
Ping @ctiller @jboeuf. Any progress?

**Comment by jboeuf** [comment]
Confirmed with @ctiller that I should use `grpc_transport_stream_op_add_close`. PR coming.

**Comment by jboeuf** [comment]
@ctiller, I get the following trace in the cpp end to end test when I replace the `grpc_transport_stream_op_add_cancellation` by a `grpc_transport_stream_op_add_close`:

```
FAILED: bins/opt/end2end_test:SecureEnd2end/SecureEnd2endTest.NonBlockingAuthMetadataPluginFailure/0  polling=legacy [ret=-6, pid=11698]

D0518 22:59:06.574469693   11971 test_config.c:278]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
Note: Google Test filter = SecureEnd2end/SecureEnd2endTest.NonBlockingAuthMetadataPluginFailure/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SecureEnd2end/SecureEnd2endTest
[ RUN      ] SecureEnd2end/SecureEnd2endTest.NonBlockingAuthMetadataPluginFailure/0
I0518 22:59:06.575717329   11971 end2end_test.cc:198]        Scenario: proxy 0, credentials ssl
D0518 22:59:06.575791137   11971 ev_posix.c:101]             Using polling engine: poll
D0518 22:59:06.577425740   11971 ev_posix.c:101]             Using polling engine: poll
E0518 22:59:06.583420687   11971 credentials.c:1180]         Getting metadata from plugin failed with error: Could not find plugin metadata.
E0518 22:59:06.583458901   11971 client_auth_filter.c:93]    Client side authentication failure: Could not find plugin metadata.
E0518 22:59:06.583467859   11971 chttp2_transport.c:1429]    assertion failed: stream_global->id != 0



*******************************
Caught signal 6
```

**Comment by jboeuf** [comment]
@ctiller, here's the code if you want to reproduce the issue:
https://github.com/jboeuf/grpc/tree/fix_3803
