### ISSUE TITLE
issue when upgrading from grpcio from 1.44.0 to 1.48.2

### ISSUE THREAD

**Issue by veron-eng** [grpc/grpc#38073]
I have this issue when upgrading grpcio from 1.44.0 to anything above that, the issue stops me from sending traces correctly to gcp, these are the current versions of the packages I am using:

```
grpcio-status~=1.48.2
grpcio~=1.48.2
google-api-core==2.10.1
python-json-logger~=2.0.5

# opentelemetry dependencies
google-cloud-trace~=1.7.1
opentelemetry-api~=1.9.1
opentelemetry-sdk~=1.9.1
opentelemetry-exporter-gcp-trace~=1.6.0
opentelemetry-instrumentation-flask~=0.28b1
opentelemetry-instrumentation-requests~=0.28b1
opentelemetry-propagator-gcp~=1.6.0
opentelemetry-resourcedetector-gcp~=1.6.0a0
```

and the only place I am using grpcio is here:

```

if environ.get("ENV", "dev").lower() == "prod":
    from gevent import monkey

    monkey.patch_all()

    import grpc.experimental.gevent as grpc_gevent

    grpc_gevent.init_gevent()
```

i am using python 3.8.13 by the way

**Comment by sreenithi** [comment]
Hi @veron-eng, there was an internal reimplementation of gevent in release v1.45.0, which is probably why you are facing problems with any version above 1.44.0. However I'm unable to understand the exact issue from your description. Can you provide additional logs or some code to reproduce the issue.
