### ISSUE TITLE
CPU usage high during synchronouse RPC call

### ISSUE THREAD

**Issue by surajkottayi** [grpc/grpc#38082]
### What version of gRPC and what language are you using?
gRPC : v1.37.1
protobuf : v3.15.2

### What operating system (Linux, Windows,...) and version?
Linu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gnu 9.3

### What did you do?

1) Called synchronous RPC call
2) The proto files are custom cannot be shared, but contains huge no of messages.

### What did you expect to see?
CPU usage to be same as that of connection with a local server.

### What did you see instead?
CPU usage when connecting to a local server is less, but with real server is high
![cpu_high](https://github.com/user-attachments/assets/b701284a-e886-4a68-a1a3-fb81c30bebf3)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by eugeneo** [comment]
gRPC team pays a lot of attention to ensure optimal performance of gRPC library. At this time we are not aware of any obvious performance issues.
Chances are there's some problems with the specific setup. This repository is for discussing issues and improvements for gRPC and is not a good place for troubleshooting specific gPRC usages. Please ask your questions on StackOverflow or grpc-io mailing list.

**Comment by surajkottayi** [comment]
@eugeneo  
That's not true. As there is no CPU spike when i try to connect to a local server.
 The CPU spike occurrs while connecting to real server through 
UDS, another app reads the UDS, enables TLS to connect to real server.

Something wrong with this approach ??
