### ISSUE TITLE
port_server's output file prevents wiping out workspace

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3813]
Jenkins is often failing not being able to wipe out workspace. It looks like temporary file used as port_server's output is located in the jenkins workspace - which prevents the workspace from being cleaned up because port server lives beyond the lifetime of a single test run.

https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/3773/config=opt,language=c,platform=windows/console

```
c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows
Wiping out workspace first.
java.io.IOException: remote file operation failed: c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows at hudson.remoting.Channel@6c9027f3:grpc-jenkins-windows-worker1: java.nio.file.FileSystemException: c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows\tmp_htaan: The process cannot access the file because it is being used by another process.

	at hudson.FilePath.act(FilePath.java:987)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.FilePath.deleteContents(FilePath.java:1184)
	at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:28)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1040)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
```

Contents of temporary file   tmp_htaan:
```
port server running on port 32767
127.0.0.1 - - [12/Oct/2015 20:28:04] "GET /get HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2015 20:28:04] found available port 1025
127.0.0.1 - - [12/Oct/2015 20:28:05] found available port 1026
127.0.0.1 - - [12/Oct/2015 20:28:05] found available port 1027
127.0.0.1 - - [12/Oct/2015 20:28:05] found available port 1028
127.0.0.1 - - [12/Oct/2015 20:28:05] found available port 1029
127.0.0.1 - - [12/Oct/2015 20:28:05] found available port 1030
...
```

**Comment by jtattermusch** [comment]
```
Wiping out workspace first.
java.io.IOException: remote file operation failed: c:\jenkins\workspace\gRPC_pull_requests\config\dbg\language\csharp\platform\windows at hudson.remoting.Channel@6ccda927:grpc-jenkins-windows-worker2: java.nio.file.FileSystemException: c:\jenkins\workspace\gRPC_pull_requests\config\dbg\language\csharp\platform\windows\tmpx1r0uk: The process cannot access the file because it is being used by another process.
```

**Comment by ctiller** [comment]
Let's use something other than mkstemp in run_tests.py to choose the temp file name then?

**Comment by jtattermusch** [comment]
Still looking into this. Interestingly, mkstemp should create a tempfile in temp directory if possible.

```
>>> import tempfile
>>> print tempfile.mkstemp()
(3, 'c:\\users\\grpc-t~1\\appdata\\local\\temp\\2\\tmpli6dnf')
```

On the other hand, I can see quite clearly that portserver gets invoked with -l parameter referring to tmpfile name is in the current directory:
```
C:\Python27\python.exe tools/run_tests/port_server.py -p 32767 -l c:\jenkins\wor                                                                                                         kspace\grpc_pull_requests\config\opt\language\c\platform\windows\tmp_htaan 
```

So I guess cygwin might be interfering with the environment settings and make msktemp work incorrectly.

**Comment by jtattermusch** [comment]
According to this listing, the "TEMP" variable is not set in the jenkins environment (I've verified that tempfile.mkstemp() depends on that variable on windows) 
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/3780/config=dbg,language=c,platform=windows/console

**Comment by jtattermusch** [comment]
As a quick solution, I created C:\Temp directory on each of the workers.  If this location exists, it is picked up by tempfile.mkstemp() and the temporary files are not put into cwd.

**Comment by mmdmeeran** [comment]
Could you elaborate how the issue has been solved.?

**Comment by jtattermusch** [comment]
@mmdmeeran  The solution is to create the temporary file to store the output outside of your workspace The port server's output file is created by tempfile.mkstemp(). Look at the source and make sure it generates a tempfile outside of your workspace (in our case, it goes to C:\Temp).
