### ISSUE TITLE
UDS paths result in invalid GRPC authority

### ISSUE THREAD

**Issue by vishaalram02** [grpc/grpc#38142]
### What version of gRPC and what language are you using?

Any version after `1.57.0`. 

### What operating system (Linux, Windows,...) and version?

MacOS and Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python `3.11.7`. 

### What did you do?
When using the client with a unix domain socket, the default `:authority` pseudo header is the %-encoding of the socket path. However, this results in a hostname that contains % characters which are invalid. (I'm using tonic + hyper in rust which rejects this request)
```python
with grpc.insecure_channel("unix:/run/sock.sock") as channel:
```

### What did you expect to see?
The authority in the case of a UDS should just be interpreted as `localhost` or something else without invalid characters. This was done until this commit: https://github.com/grpc/grpc/pull/33571. 

### What did you see instead?
My gRPC server rejects the request as malformed. I know that I can manually set the authority through channel options, but this is not always possible with libraries that use `grpc` and I believe the underlying issue is here. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
As discussed in #33571, this is working as intended.  If you are encountering a server that doesn't like the authority that we are sending, you can have the client explicit set the authority to "localhost" via the `GRPC_ARG_DEFAULT_AUTHORITY` channel arg.
