### ISSUE TITLE
How long is it allowed to block a grpc thread

### ISSUE THREAD

**Issue by d7d1cd** [grpc/grpc#38165]
I have implemented a server-streaming server based on grpc. The [grpc::ServerWriteReactor](https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_write_reactor.html) class is used as stream writers. When a remote procedure is called by a client, a reactor is created. The data for is retrieved from a thread-safe queue: in the OnWriteDone method, the next Response is retrieved and passed to the StartWrite method.

The queue is blocking. When there is no data in it, the reading thread (in my case it is the grpc library thread) blocks until data arrives in the queue.

Are there any restrictions on how long a grpc thread can be blocked? Is there some kind of liveness probe inside grpc that, seeing that the thread is blocked, will take some action?

**Comment by eugeneo** [comment]
Please do not use this repository for asking questions. This repository is for reporting issues with gRPC implementation. Use StackOverflow or grpc-io mailing list for for asking questions.

**Comment by d7d1cd** [comment]
I asked the question because the form on the Issue tab allows it. In that case, remove this item to avoid misleading anyone.
![image](https://github.com/user-attachments/assets/a1d3a5e6-6d37-4ae2-9a18-007389dc0d83)

Also, I asked this question [on SO](https://stackoverflow.com/questions/78510412/how-long-is-it-allowed-to-block-a-grpc-thread/). However, the answer provided there contradicts the information [here](https://grpc.io/docs/languages/cpp/best_practices/).
