### ISSUE TITLE
@com_github_grpc_grpc//src/core:envoy_extensions_load_balancing_policies_client_side_weighted_round_robin_upb build target too long, breaks build on Windows

### ISSUE THREAD

**Issue by korDen** [grpc/grpc#38188]
### What version of gRPC and what language are you using?
1.68.0

### What operating system (Linux, Windows,...) and version?
Windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
bazel with msvc

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
bazel build @com_github_grpc_grpc//src/core:envoy_extensions_load_balancing_policies_client_side_weighted_round_robin_upb

### What did you expect to see?
successful compilation

### What did you see instead?
build error:

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-fastbuild/bin/external/grpc~~grpc_repo_deps_ext~envoy_api/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/_objs/pkg.upb_minitable/client_side_weighted_round_robin.upb_minitable.obj.params
# Configuration: 5bfebdc9f3a8f089d6fffd2cfe2684d88c0fae86439d1f770b92e72244fef22c
# Execution platform: @@platforms//host:host
Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8022 : cannot open 'bazel-out/x64_windows-fastbuild/bin/external/grpc~~grpc_repo_deps_ext~envoy_api/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/_objs/pkg.upb_minitable/client_side_weighted_round_robin.upb_minitable.obj.params'

path too long, longer than MAX_PATH

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by korDen** [comment]
Note that pretty much any target depending on `@com_github_grpc_grpc//:grpc++` will depend on that, so basically grpc is not usable with bazel on windows.

**Comment by veblush** [comment]
This is more of Windows issue. Internally, we work around this by enabling long-path so you should be able to fix this by doing the same thing.
