### ISSUE TITLE
BlockingUnaryCall  crushes on Windows

### ISSUE THREAD

**Issue by IvaYan** [grpc/grpc#3821]
Hello!
I'm trying to make gRPC work under windows. Both server and client are on C++.

I have successfully compiled protoc, all plugins and gRPC libraries. I have generated C++ classes for my protocol. I have successfully implemented server and client then I compiled them. But when I run applications, the client crushes with Access Violation exception.

I managed to determine where this exception occurs. Method *BlockingUnaryCall* from grpc\include\grpc++\impl\client_unary_call.h has the following body:

```
CompletionQueue cq;
  Call call(channel->CreateCall(method, context, &cq));
  CallOpSet<CallOpSendInitialMetadata, CallOpSendMessage,
            CallOpRecvInitialMetadata, CallOpRecvMessage<OutputMessage>,
            CallOpClientSendClose, CallOpClientRecvStatus> ops;
  Status status = ops.SendMessage(request);
  if (!status.ok()) {
    return status;
  }
  ops.SendInitialMetadata(context->send_initial_metadata_);
  ops.RecvInitialMetadata(context);
  ops.RecvMessage(result);
  ops.ClientSendClose();
  ops.ClientRecvStatus(context, &status);
  call.PerformOps(&ops);
  GPR_ASSERT((cq.Pluck(&ops) && ops.got_message) || !status.ok());
  return status;
```

This method calls *ops.SendInitialMetadata* which manipulates context->send_initial_metadata_ field. But this filed is not valid! It says it has enormous size, something like 19500360. As a result, it tries to accesses elements that do not exist.

But I didn't manage to understand why this happens. When I create the context it is valid, but inside that function it is not, moreover it is not changed until the call to *ops.SendInitialMetadata*.

Have anyone faced this problem?

**Comment by larsonmpdx** [comment]
see

https://github.com/grpc/grpc/issues/3274

and

https://github.com/grpc/grpc/issues/2671

best practice currently is to remove _USE_32BIT_TIME_T from the grpc
libraries if you use std::chrono or to add it to your project if you don't

**Comment by larsonmpdx** [comment]
#3278 has some updated windows documentation as well, which addresses this problem (waiting on merge/comment)

**Comment by IvaYan** [comment]
Thanks for help! Removing _USE_32BIT_TIME_T from all of the gRPC libraries didn't solve the problem, because I'm not using std::chrono.
Problem was solved by adding this define to my client and server projects. Thanks!

**Comment by jtattermusch** [comment]
we are not longer using _USE_32BIT_TIME_T 
https://github.com/grpc/grpc/pull/4315
