### ISSUE TITLE
Adopt new credentials API for python

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#3827]
As part of having all the gRPC libraries be consistent, we would like to make a breaking change to the current credentials API.

# Motivation

The idea coming from @murgatroid99 is that there are now 2 credentials classes, one for channels (grpc_channel_credentials) to be set on a channel and the other one on calls (grpc_call_credentials). We still have composition functions that do:
`channel_creds <- compose(channel_creds, call_creds)`
`call_creds <- compose(call_creds, call_creds)`

This refactoring will achieve 2 main goals:

1. Add some type safety so that users of the API do not set call credentials only (without a channel one) when creating a channel. Likewise, this will make it impossible to set channel creds on a particular call which is currently just a runtime error.

2. This will also cleanup a lot of the implementation that basically had to provide at runtime for what the type safety was not enforcing.

**Comment by soltanmm** [comment]
#4228
