### ISSUE TITLE
The helloworld greeter_server.exe crashes on Windows VS2017

### ISSUE THREAD

**Issue by OliverF2022** [grpc/grpc#38275]
### What version of gRPC and what language are you using?
grpc 1.56.4 c++

### What operating system (Linux, Windows,...) and version?
Windows10

### What runtime / compiler are you using (e.g. python version or version of gcc)
visual studio 2017

### What did you do?
I build the 'Helloworld' example, and run the greeter_server.exe and the greeter_client.exe ,but greeter_server.exe crashed. 

### What did you expect to see?
The greeter_client.exe prints: Greeter received: Hello world

### What did you see instead?
It reports '[Run-Time Check Failure #2 - Stack around the variable 'true_factory' was corrupted]'
![e](https://github.com/user-attachments/assets/d743dbb0-3064-4e29-b6c9-c8a39af86377)

**Comment by OliverF2022** [comment]
Additional explanation, I am using version **1.57.1** ​​and the same problem occurs and the same error is reported. 
I switched to version **1.34.0** and the results were consistent with expectations. I have not tried the other versions in between

**Comment by veblush** [comment]
As we support MSVC 2022 or later (per https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md), please try using those versions instead. MSVC prior to 2022 apparently has a bug which can cause stack corruption.

**Comment by OliverF2022** [comment]
> As we support MSVC 2022 or later (per https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md), please try using those versions instead. MSVC prior to 2022 apparently has a bug which can cause stack corruption.

But I used the version 1.57.1 which support visual studio 2017 , the newer version which not support vs2017, it requires vs2019.
