### ISSUE TITLE
Gem won't build on amd64 arch under alpine Ruby v3.4 image

### ISSUE THREAD

**Issue by tcaddy** [grpc/grpc#38354]
### What version of gRPC and what language are you using?
Ruby is the language.  Version 3.4 (at least under the alpine container), which was released on Christmas is the culprit.

### What operating system (Linux, Windows,...) and version?
Linux AMD64 container building, Alpine Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby runtime.  Version 3.4 won't compile.  Downgrading to Ruby version 3.3 Alpine Linux image fixes the issue.

### What did you do?
A CI build failed when it had worked previously.  I tried older versions of the gem.  I tried building the container on my m-series macbook, which does ARM64 architecture by default (it works fine on arm64 for some reason).  Specified AMD64 platform on my macbook to reproduce the issue.

### What did you expect to see?
I expected `bundle install` to just install the gem within a few seconds.

### What did you see instead?
`bundle install` hangs on gem install.  If I try `gem install -V grpc`, I see errors about boringssl.

### Anything else we should know about your project / environment?
I don't think so

**Comment by alto-ruby** [comment]
Can you provide the docker file (or image)?
Can you paste the error logs?

**Comment by tcaddy** [comment]
Dockerfile:
```dockerfile
FROM ruby:alpine
RUN \
  apk update && \
  apk add --no-cache bash curl jq python3 ca-certificates build-base gcompat
RUN \
  curl https://sdk.cloud.google.com > install.sh && \
  bash install.sh --disable-prompts
WORKDIR /app
COPY Gemfile* .
RUN bundle install
COPY *.rb *.sh .
ENTRYPOINT [ "./entrypoint.sh" ]
```

Gemfile
```ruby
source "https://rubygems.org"

gem "base64"
gem "google-apis-sqladmin_v1beta4", ">= 0.65.0"
gem "mutex_m"
gem "google-cloud-run-v2", ">= 0.13.1"
gem "google-apis-run_v2"
```

The output from a `bundle install` is nothing.  It just hangs.  The output from `gem install -V gprc` is thousands of lines, which I don't think I have a copy of.  I'll check CI logs and post a followup if I see something.

**Comment by tcaddy** [comment]
This is what `bundle install` looks like in CI:
![image](https://github.com/user-attachments/assets/b0bacf6e-4d06-45e3-9423-3c1444d926f2)
---
I did a lot of debugging in CI from interactive SSH sessions and I don't have the logs from those.

**Comment by tcaddy** [comment]
OK, here's the output of building the container image from my macbook for the `linux/amd64` platform
[grpc_error.txt.zip](https://github.com/user-attachments/files/18264414/grpc_error.txt.zip)

**Comment by alto-ruby** [comment]
You build failed with "Illegal instruction" error, can you try update Docker, give it more resources and/or try different options?

I'm running M1 Max, MacOS 14.6.1, Docker desktop 4.37.1, configured with all 10 cores and 16G ram, using Apple Virtualization framework and Rosetta enabled, BTW.

My build (docker build --platform linux/amd64 -t ruby-38354-test .) succeeded with 512s, which is indeed slow, you can also try increase the no_output_timeout in your CI.

```
#10 35.92 make: *** [Makefile:618:
#10 35.92 /usr/local/bundle/gems/grpc-1.68.1/src/ruby/ext/grpc/objs/opt/third_party/boringssl-with-bazel/src/crypto/bio/socket.o]
#10 35.92 Illegal instruction
#10 35.92 make: *** Waiting for unfinished jobs....
```

**Comment by adomokos** [comment]
> This is what `bundle install` looks like in CI:
> 
> ## ![image](https://private-user-images.githubusercontent.com/280902/399024833-b0bacf6e-4d06-45e3-9423-3c1444d926f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MjkwOTYsIm5iZiI6MTczNTUyODc5NiwicGF0aCI6Ii8yODA5MDIvMzk5MDI0ODMzLWIwYmFjZjZlLTRkMDYtNDVlMy05NDIzLTNjMTQ0NGQ5MjZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQwMzE5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTQzNDRkNTlkNzcwNmNiODlkZWI3M2M2Y2E5MjZiMTZhNzJhMmNmODZiNzUxNmU3YTllMjU2NTFkZjljNjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b2TzqHC6RuP84Tk8Jwl4I2W4tSc8eTELjhpPlvBx1Gk)
> I did a lot of debugging in CI from interactive SSH sessions and I don't have the logs from those.

I am bumping into extended build time on GitHub CI with Ruby 3.4.1 with the same version of the grpc gem: `1.68.1`.
The build finishes for me, but it takes an extra 18 minutes to install this gem.

It's a blocker for me to upgrade to Ruby 3.4.

**Comment by tcaddy** [comment]
FWIW my docker desktop install on my macbook has 8 CPUs and 14GB RAM allocated.  I'm using CircleCI, where I was using the small docker resource class, which is 1 CPU and 2GB RAM: https://circleci.com/docs/configuration-reference/#docker-execution-environment

**Comment by alto-ruby** [comment]
Thanks for the feedback, it's expected as we are not releasing pre-compiled library for ruby 3.4 yet, as a result you'll have to build from source which takes a long time.

**Comment by alto-ruby** [comment]
Correct.

**Comment by alto-ruby** [comment]
Closing since it builds with ruby 3.4. 
Pre compiled library for 3.4 is being worked in [#38338](https://github.com/grpc/grpc/pull/38338)
