### ISSUE TITLE
cloud_to_cloud interop tests against ruby_server are flaky

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#3840]
Jenkins interop tests running on master:
https://grpc-testing.appspot.com/job/gRPC_interop_master/278/#showFailuresLink

Lots of cloud_to_cloud interop tests involving ruby_server seem to be failing intermittently. See link above. Many failures show up as "Timeout". Example: https://grpc-testing.appspot.com/job/gRPC_interop_master/278/testReport/junit/(root)/tests/cloud_to_cloud_c___ruby_server_empty_unary/

Here's one way to run all clients and all tests against the ruby server:
`~/grpc$ tools/run_tests/run_interop_tests.py -l all -s ruby --use_docker -t -j 8`

**Comment by jtattermusch** [comment]
@murgatroid99 , any ideas here?   Failures against ruby_server are more than > 50% interop test failures we are currently seeing.

**Comment by murgatroid99** [comment]
I'll take a look tomorrow.

**Comment by murgatroid99** [comment]
This appears to be caused by #3882.

**Comment by jtattermusch** [comment]
#3882 has been closed and looks like we are still seeing this.

**Comment by jtattermusch** [comment]
#4002, #4003 and #4004 are instances of this issue.

**Comment by murgatroid99** [comment]
Two of those look like they are not actually failures, and the other is not a timeout. I don't think we're seeing the same failures there.

**Comment by jtattermusch** [comment]
I think these were the same failures but we got bitten by the "lastCompletedBuild" link being ephemeral.

**Comment by jtattermusch** [comment]
I think this is worth escalating to P0 as in vast majority of cases , it is preventing interop tests suite from being green.
