### ISSUE TITLE
Use common location for health.proto and math.proto files.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3850]
There is a copy of health.proto and math.proto for each of C#, ruby, Node and python.
```
find -name 'math.proto'
./src/csharp/Grpc.Examples/proto/math.proto
./src/ruby/bin/math.proto
./src/node/test/math/math.proto
./src/php/tests/generated_code/math.proto
```

```
$ find -name 'health.proto'
./src/csharp/Grpc.HealthCheck/proto/health.proto
./src/ruby/pb/grpc/health/v1alpha/health.proto
./src/node/health_check/health.proto
./src/python/grpcio_health_checking/grpc/health/v1alpha/health.proto
```

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle , @soltanmm , @murgatroid99 , @tbetbetbe

**Comment by ctiller** [comment]
I nominate src/proto

**Comment by nicolasnoble** [comment]
My vote is cast for src/proto too.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle Pick your poison: rely on the user invoking `make`, or use environment variables at build time to determine from the setup.py whether or not to copy over proto files from some other location, or have yet another project with only the `.proto` files and accept all the awkwardness that comes with it.

**Comment by jtattermusch** [comment]
Related issue https://github.com/grpc/grpc/issues/4123

**Comment by ctiller** [comment]
Can we move setup.py a level or two up and alleviate all those problems?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: has this gotten any easier as a result of the other major changes to the Python build in the last month?

**Comment by soltanmm** [comment]
Yes, with a second set of choices:
* Use a custom command to copy the proto files to relevant package directories (or even temporary/build directories) and make setuptools aware of the directories prior to the underlying `build_py` implementation being invoked.
* Add `__init__.py`s to `src/proto`.

The second is easier, but messy. I imagine y'all'd want the first?

**Comment by ctiller** [comment]
I have no strong feelings

**Comment by nathanielmanistaatgoogle** [comment]
As of 7149ca6bd0ce73a08fa512415d3f64, PHP still has its own copy of math.proto; reapplied "php" label.

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: for Python, let's go with the first choice - you guessed correctly that I'd be reticent about "Pythoning up" non-Python parts of the codebase.

**Comment by jtattermusch** [comment]
For PHP this is not actionable as ./src/php/tests/generated_code/math.proto needs to be in proto2 syntax.  Official proto support for proto3 might be coming, at which point we can clean this up.

**Comment by jtattermusch** [comment]
Closing this after creating a python specific issue.

**Comment by jtattermusch** [comment]
CC @kpayson64
