### ISSUE TITLE
Add x64 support for C# on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3852]
Allow building grpc_csharp_ext.dll in 64bit mode and verify it works with x64 C# projects.

**Comment by nickdul** [comment]
looks like the issue #3591 is related to x64 support

**Comment by jtattermusch** [comment]
Related to #1082

**Comment by jtattermusch** [comment]
The work has been mostly done (and verified). In the next release, we will publish nuget packages that will fully support Win 32bit and Win 64bit (including autodetection).
