### ISSUE TITLE
Cross compiling to ARM under Linux

### ISSUE THREAD

**Issue by borud** [grpc/grpc#3865]
hi,  I have been trying to get GRPC to compile in my ARM cross compilation environment, and I am not having much luck.  I've tried to compile it with.

    make HAS_PKG_CONFIG=false CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ LD=arm-linux-gnueabi-gcc LDXX=arm-linux-gnueabi-g++ AR=arm-linux-gnueabi-ar CPPFLAGS=-I/usr/lib/gcc-cross/arm-linux-gnueabi/include:../include LDFLAGS=-L/usr/lib/gcc-cross/arm-linux-gnueabi

Which grinds to a halt when building `third_party/openssl`.

I've tried to compile openssl directly doing `./Configure linux-armv4 && make` -- which succeeds.  I then copied the resulting `libssl.a` and `libcrypto.a` to `lib/opt` since someone said that that would stop the build from trying to build openssl again, but alas, it runs off and tries to build it.

Any ideas what direction I need to go in in order to build GRPC for ARM on an x86?

*The build environment I've used is available from Docker hub: `docker pull borud/kerlink-build`.  The docker file is available from https://github.com/borud/kerlink-build.*

*If you are curious what I'm doing:  I'm trying to write a new packet forwarder that uses GRPC for the Kerlink Lora gateway, which uses a CPU identified as "ARM926EJ-S rev 4 (v5l)" in `/proc/cpuinfo`.

**Comment by ctiller** [comment]
First question: do you need to support SSL?

**Comment by borud** [comment]
@ctiller Having SSL support is a big part of why I'd like to use GRPC for this, but if it is a timing issue, I can wait for SSL support until January 2016.  If there is no hope that there'll be SSL support on that platform, then GRPC may not be the right choice for the project.

It has been a few weeks since last time I looked at this, but I *think* I managed to compile SSL manually, but not as part of the GRPC build (which seemed to insist on initiating the SSL build on its own and didn't care that I had already built the libraries manually in those directories).  When I say I think I managed to compile it, what I mean is that it did produce the (two?) needed *.a files -- I did not perform any tests to verify that the compiled code actually works correctly.

So I guess this boils down to two questions:
  - How do I compile it without SSL support
  - Is there any realistic hope for SSL-support within the next 3 months?

Thanks for your response.

**Comment by ctiller** [comment]
So GRPC definitely supports OpenSSL - there's totally hope that we can get
it working.
The problem seems to be some compiler configuration, and that seems
resolvable with some group banging on it.

+Nicolas Noble <nnoble@google.com> has had good success in the past.
Suggest finding a good time to chat and resolve this.

**Comment by nicolasnoble** [comment]
So, for these more exotic builds, I'd suggest to NOT recursively clone gRPC, and fill your environment with the necessary dependencies yourself.

Basically, cross-compile OpenSSL and protobuf individually and install them in your cross compilation environment. Then you can run your make command.

**Comment by borud** [comment]
@ctiller @nicolasnoble sorry about taking a few days to respond.   The environment I've been using for building software for the ARM platform that is the target is a Docker container.  The Docker file for which is here:

https://github.com/borud/kerlink-build

Eventually I hope to add the GRPC build stages to that container so that it has everything in it.  I'll start by adding the OpenSSL stuff (not sure where libraries and such should be installed, but I'll try one step at a time :-))

(If anyone else has something to contribute I'd be happy for any pull requests!)

**Comment by borud** [comment]
Okay, I got a little bit further today.  I pushed a new Dockerfile to Github that makes sure zlib and openssh are installed under `/usr/local/cross` (not sure if there is a convention for where you put libraries for cross compiling?)

I then set 

    LDFLAGS=-L/usr/local/cross/lib:/usr/lib/gcc-cross/arm-linux-gnueabi

and

    CPPFLAGS=-I/usr/local/cross/include:/usr/lib/gcc-cross/arm-linux-gnueabi/include

and ran `make` which complained about *DEPENDENCY ERROR*.   I'm probably missing something, but I'll have to continue on tomorrow.

**Comment by nicolasnoble** [comment]
Since there was no further update, I'm going to close that issue for now. We'll reopen if further updates are posted.
