### ISSUE TITLE
"qps_openloop_test" fails on C++ linux (opt, tsan) and macos with 

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#3869]
https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=c++,platform=linux/8345/console

```
I1016 03:47:32.080034723   13149 qps_openloop_test.cc:51]    Running QPS test, open-loop
D1016 03:47:32.080173289   13149 test_config.c:155]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
E1016 03:47:32.112118500   13149 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1016 03:47:32.113711375   13180 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1016 03:47:32.120335974   13190 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1016 03:47:32.135979342   13149 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1016 03:47:32.148374617   13210 grpc_profiler.c:48]         You do not have google-perftools installed, profiling is disabled [for qps_server.prof]
D1016 03:47:32.148403478   13210 grpc_profiler.c:52]         To install on ubuntu: sudo apt-get install google-perftools libgoogle-perftools-dev
I1016 03:47:32.383808084   13149 driver.cc:206]              Warming up
I1016 03:47:37.383936398   13149 driver.cc:212]              Starting
I1016 03:47:37.488023483   13149 driver.cc:233]              Running
...
...
Caught signal 11
bins/opt/qps_openloop_test[0x68ba13]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f5e1edc28d0]

FAILED: bins/opt/qps_openloop_test [ret=-11, pid=13149]
...
```

The test sometimes passes as well - which makes me think this is a flaky-test

**Comment by yang-g** [comment]
tsan failure seen again (linux dbg):
https://grpc-testing.appspot.com/job/gRPC_master/12020/config=tsan,language=c++,platform=linux/console

**Comment by a11r** [comment]
This is likely flaky .. the only failure I got in my run today was under gcov:
config=gcov,language=c++,platform=linux
https://grpc-testing.appspot.com/job/gRPC_master/12375/config=gcov,language=c++,platform=linux/testReport/(root)/tests/bins_gcov_qps_openloop_test/

**Comment by vjpai** [comment]
This flake is not related to the cases covered by #4018 . While all the other benchmarks were flopping in stats collection (sync streaming server), this is a different issue altogether.

**Comment by sreecha** [comment]
Still happening as of 2/29/2016
https://grpc-testing.appspot.com/job/gRPC_master/15479/config=dbg,language=c++,platform=macos/console

**Comment by jtattermusch** [comment]
still seen 2016/3/14
https://grpc-testing.appspot.com/job/gRPC_master/15790/#showFailuresLink

**Comment by vjpai** [comment]
This is different from the fixes that went in recently re the profiler,
since this is coming from the mac test. Is there any way to recover a
corefile here?

**Comment by jtattermusch** [comment]
Theoretically, yes. The easiest thing to do might actually be running the
test locally on a mac with -n 1000. It should be possible to reproduce this.

**Comment by jcanizales** [comment]
Seen Jan's reported failure again today, this time with a bit more of output: https://grpc-testing.appspot.com/job/gRPC_master/15854/config=dbg,language=c++,platform=macos/console

```
E0316 15:49:04.611127000 140735129694976 driver.cc:383] assertion failed: server->stream->Finish().ok()



*******************************
Caught signal 6
  no backtrace

FAILED: bins/dbg/qps_openloop_test [ret=-6, pid=28246]
```
