### ISSUE TITLE
gRPC master. Python tests 

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#3870]
1. dbg on linux
https://grpc-testing.appspot.com/job/gRPC_master/config=dbg,language=python,platform=linux/8345/consoleFull

2. dbg on macos

https://grpc-testing.appspot.com/job/gRPC_master/config=dbg,language=python,platform=macos/8345/consoleFul

```
[gw2] FAILED grpc_protoc_plugin/beta_python_plugin_test.py::PythonPluginTest::testStreamingOutputCallCancelled...
[gw5] FAILED grpc_test/_adapter/_event_invocation_synchronous_event_service_test.py::EventInvocationSynchronousEventServiceTest::testSuccessfulStreamRequestStreamResponse <- grpc_test/framework/face/testing/event_invocation_synchronous_event_service_test_case.py 
...
[gw5] FAILED grpc_test/_adapter/_event_invocation_synchronous_event_service_test.py::EventInvocationSynchronousEventServiceTest::testSuccessfulUnaryRequestStreamResponse <- grpc_test/framework/face/testing/event_invocation_synchronous_event_service_test_case.py 
...
[gw4] FAILED grpc_test/_adapter/_future_invocation_asynchronous_event_service_test.py::FutureInvocationAsynchronousEventServiceTest::testSuccessfulStreamRequestStreamResponse <- grpc_test/framework/face/testing/future_invocation_asynchronous_event_service_test_case.py 
...
[gw0] FAILED grpc_test/early_adopter/implementations_test.py::EarlyAdopterImplementationsTest::testStreamStream 
...

```
3. Opt test on macos
https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=python,platform=macos/8345/consoleFull

```
...
[gw7] FAILED grpc_test/_adapter/_future_invocation_asynchronous_event_service_test.py::FutureInvocationAsynchronousEventServiceTest::testSuccessfulStreamRequestStreamResponse <- grpc_test/framework/face/testing/future_invocation_asynchronous_event_service_test_case.py 
[gw6] FAILED grpc_test/_adapter/_event_invocation_synchronous_event_service_test.py::EventInvocationSynchronousEventServiceTest::testSuccessfulStreamRequestStreamResponse <- grpc_test/framework/face/testing/event_invocation_synchronous_event_service_test_case.py 
...
[gw1] FAILED grpc_test/early_adopter/implementations_test.py::EarlyAdopterImplementationsTest::testStreamStream 
...
=================================== FAILURES ===================================
 FutureInvocationAsynchronousEventServiceTest.testSuccessfulStreamRequestStreamResponse 
[gw7] darwin -- Python 2.7.6 /jenkins/workspace/gRPC_master/config/opt/language/python/platform/macos/python2.7_virtual_environment/bin/python2.7
self = <grpc_test._adapter._future_invocation_asynchronous_event_service_test.FutureI...nchronousEventServiceTest testMethod=testSuccessfulStreamRequestStreamResponse>

    def testSuccessfulStreamRequestStreamResponse(self):
      for name, test_messages_sequence in (
          self.digest.stream_stream_messages_sequences.iteritems()):
        for test_messages in test_messages_sequence:
          requests = test_messages.requests()
          request_iterator = _PauseableIterator(iter(requests))
    
          # Use of a paused iterator of requests allows us to test that control is
          # returned to calling code before the iterator yields any requests.
          with request_iterator.pause():
            response_iterator = self.stub.inline_stream_in_stream_out(
                name, request_iterator, test_constants.SHORT_TIMEOUT)
>         responses = list(response_iterator)

grpc_test/framework/face/testing/future_invocation_asynchronous_event_service_test_case.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../python2.7_virtual_environment/lib/python2.7/site-packages/grpc/framework/face/_calls.py:118: in next
    return next(self._rendezvous)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <grpc.framework.face._control.Rendezvous object at 0x110b8e710>

    def next(self):
      with self._condition:
        while ((self._abortion is None) and
               (not self._values) and
               (not self._values_completed)):
          self._condition.wait()
        if self._abortion is not None:
>         raise _abortion_outcome_to_exception(self._abortion)
E         ExpirationError
...


```

**Comment by vjpai** [comment]
Pinging this again. All Python MacOS tests are timing out.

https://grpc-testing.appspot.com/job/gRPC_master/11263/config=dbg,language=python,platform=macos/testReport/junit/(root)/tests/py_test/

**Comment by yang-g** [comment]
Pinging
https://grpc-testing.appspot.com/job/gRPC_master/12020/config=opt,language=python,platform=macos/testReport/junit/(root)/tests/py_test/

**Comment by vjpai** [comment]
Seeing this problem again on Linux, dbg

**Comment by ctiller** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/13729/config=opt,language=python,platform=linux/testReport/(root)/tests/py_test/

```
...
[0mTraceback (most recent call last):
  File "setup.py", line 176, in <module>
    test_runner=TEST_RUNNER,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/var/local/git/grpc/src/python/grpcio/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/var/local/git/grpc/src/python/grpcio/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/var/local/git/grpc/src/python/grpcio/tests/_runner.py", line 213, in run
    result.stopTestRun()
  File "/var/local/git/grpc/src/python/grpcio/tests/_result.py", line 291, in stopTestRun
    self.out.write(summary(self))
  File "/var/local/git/grpc/src/python/grpcio/tests/_result.py", line 419, in summary
    for result in itertools.chain(failures, errors)
TypeError: bad operand type for unary +: 'str'
ERROR: InvocationError: '/var/local/git/grpc/src/python/grpcio/.tox/py27/bin/python setup.py test'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
```

**Comment by ctiller** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/13729/config=dbg,language=python,platform=linux/testReport/(root)/tests/py_test/

**Comment by dgquintas** [comment]
Again

https://grpc-testing.appspot.com/job/gRPC_master/13753/config=opt,language=python,platform=linux/testReport/junit/(root)/tests/py_test/

**Comment by soltanmm** [comment]
The non-timeout one I'll get to tomorrow. The timeout ones still require digging into that I've still not yet gotten around to (Python debugger doesn't handle threads and haven't instrumented code, but that's next!). I have a few theories though.

@ctiller Is it well-defined that a server is ready and listening on a port the moment the `grpc_server_start` returns? Else is there any way in core to check whether or not a server has finished spinning up?

**Comment by ctiller** [comment]
We call listen() before grpc_server_start, and start waiting for it to turn
readable when grpc_server_start is called, so off the top of my head I can
think of no reason why it wouldn't be ready. You'd need to be blocking in a
completion queue to notice, of course.

**Comment by soltanmm** [comment]
That... could be it. Would it be sufficient to pluck a bogus tag with immediate deadline (or even a deadline in the past) to let the server finish its waiting?

Alternatively, if a server isn't ready, a call is made to the server, and later the server starts up while the call hasn't timed out yet (... somehow; the parameters for this aren't clear in my head), does the server manage to respond to the call or is it one of those situations where the message is very likely lost in the aether?

**Comment by ctiller** [comment]
The message won't be lost: the bytes for the request will be sitting in a
kernel buffer waiting to be picked up. If it's too long, what could happen
is that the client cancels its connection attempt, and then retries a few
seconds later (and repeat, with exponentially longer waits).

**Comment by soltanmm** [comment]
Hmm...
* Would it be sufficient to pluck a bogus tag with immediate deadline (or even a deadline in the past) to let the server finish its initial waiting?
* Does the server also retry if the client disappears before the timeout is up? If so, can a situation arise wherein the client calls (call 1), gives up, the server receives that call (call 1), and the client calls again (call 2), the server also receives that call (call 2), and the client and server talk over call 2 but the server is left hanging with call 1 until the deadline passes?

**Comment by ctiller** [comment]
Each call only ever* goes out on one TCP connection. A bogus pluck or next
will allow the connection to establish. I did exactly this in
https://github.com/grpc/grpc/pull/4482 for similar reasons.

* that might change one day, but I expect it'd be very opt in
