### ISSUE TITLE
Error codes not exposed in Python exceptions

### ISSUE THREAD

**Issue by kyleconroy** [grpc/grpc#3873]
I have a Go GRPC server that returns an error with an `Unauthorized` code.

```go
type BlobService struct {
}

func (bs *BlobService) Store(c context.Context, r *Request) (*Response, error) {
	return nil, grpc.Errorf(codes.PermissionDenied, "Not authorized")
}
```

When calling this server from Python, the client raises a `NetworkError` which doesn't have the error code attached.

```python
try:
    client.Store(blob_pb2.Request(), 1)
except:
    e = sys.exc_info()[0]
    print e.message
    print e.args
```

How do I access that error code?

All code is here https://gist.github.com/kyleconroy/9c2ba448d46f2ec93900#file-client-py

**Comment by nathanielmanistaatgoogle** [comment]
Are there not `e.code` and `e.details` available to you as well as `e.message` and `e.args`?

**Comment by kyleconroy** [comment]
`e.message` and `e.args` are both empty, but `e.code` and `e.details` are populated. Sorry for the report!

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle It's still perhaps odd that we're not filling in `e.message` and `e.args`, though, isn't it?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm it may or may not be odd but it's certainly a place where we aren't being as helpful as we could be. I'll try to get to this in the next few days; @dhermes just hit his head against it too.
