### ISSUE TITLE
Synchronous server nap

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#3882]
Synchronous servers sometimes take a nap on Mac (or on Linux without epoll). They have work to do but they're not doing it until another alarm times out. This issue has been observed in C++ but I believe that it stems from handling in core. This issue tracks the investigation and resolution of this nap problem.

**Comment by murgatroid99** [comment]
I believe I am seeing this same problem with the Ruby interop server on Linux. To reproduce it, run

```sh
ruby src/ruby/bin/interop/interop_server.rb --use_tls=true --port 7070
```

(port number arbitrarily chosen)

Then run the following command twice:

```sh
tools/run_tests/run_interop_tests.py -l node ruby c++ python csharp php --override_server ruby=localhost:7070 --use_docker -t -j 8
```

All or almost all of the tests pass in the first run, and all of the tests time out in the second run. Using `gdb`, I can confirm that after the first run, the server has a single thread blocked on `poll` with `grpc_completion_queue_pluck` in the stack trace, and that that instance of `grpc_completion_queue_pluck` never returns. In addition, at the end of the first run of tests, the server always outputs the following log lines:

```
E1021 13:35:46.125181984   29590 handshake.c:186]            Read failed.
E1021 13:35:46.125207022   29590 server_secure_chttp2.c:155] Secure transport failed with error 2
```

**Comment by vjpai** [comment]
I can now confirm that even in C++ we can sometimes trigger the behavior like Ruby where the test hangs forever rather than just napping.

**Comment by vjpai** [comment]
Escalating to P0.
