### ISSUE TITLE
There are no way to specify custom C++ compiler for gRPC

### ISSUE THREAD

**Issue by pavel-odintsov** [grpc/grpc#3893]
Hello, folks!

I have used custom gcc compiler because my system haven't modern compiler with C++ support.

So I could not find any correct way to specify custom path to gcc and use dirty hack:
```bash
sed -i '81i DEFAULT_CC=/opt/fastnetmon/libraries/gcc520/bin/gcc' Makefile
sed -i '82i DEFAULT_CXX=/opt/fastnetmon/libraries/gcc520/bin/g++' Makefile
```

**Comment by pavel-odintsov** [comment]
Any news folks? Current approach for build prepare is not flexible and bit complicated when I'm trying to build it wit custom paths to clang/gcc and with custom compilation options.

**Comment by nicolasnoble** [comment]
Yes, there is.

```
CC=my-custom-gcc CXX=my-custom-g++ LD=my-custom-gcc LDXX=my-custom-g++ AR=my-custom-ar make static_c
```
