### ISSUE TITLE
Exclude uninteresting directories from coverage reports

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3894]
The following should be excluded:

/usr/include
third_party/
test/

(basically, we want src/ and include/ from grpc root)

**Comment by murgatroid99** [comment]
There is [an example in `run_node.sh`](https://github.com/grpc/grpc/blob/master/tools/run_tests/run_node.sh#L47) of how extract coverage information for particular directories from the full coverage information.

**Comment by hsaliak** [comment]
@nicolasnoble is this still relevant?

**Comment by nicolasnoble** [comment]
It's still relevant, but probably not for GA actually.
