### ISSUE TITLE
tsan flake on timer_list_test

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#3895]
https://grpc-testing.appspot.com/job/gRPC_master/11263/config=tsan,language=c,platform=linux/testReport/junit/(root)/tests/bins_tsan_timer_list_test/

(timer_list_test+0x0000000bfd77)

SUMMARY: ThreadSanitizer: signal-unsafe call inside of a signal ??:0 write
==================

**Comment by dgquintas** [comment]
It seems this hasn't been seen for a while. Closing.
