### ISSUE TITLE
Provide access to protobuf type information on generated objects (via ".DESCRIPTOR" attributes?)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#3898]
Figure out how to and then implement provision of protobuf reflection objects (descriptors) to user code from the generated code via the protoc plugin.

cc @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
I don't think I understand this request - can you elaborate? Possibly with sample code?

**Comment by soltanmm** [comment]
The user currently doesn't have access to the request/response message descriptors directly from the stub interface provided by the autogenerated `*_pb2.py` files. This seems simple enough to add in, and it would mean that user code that doesn't know what stub object it's calling into (e.g. if the stub itself is being used as part of a callback mechanism of sorts) can perform type checking in advance of making a call instead of being forced to initiate the call before knowing what it's dealing with.

**Comment by nathanielmanistaatgoogle** [comment]
Okay. I'd like for this not to be necessary or for its cost to outweigh its benefit so that we decide not to do it, but I'm open to being wrong about those.

**Comment by ericgribkoff** [comment]
We have  now gone a long time without needing this access on our generated code, which seems like a good thing. It's related to potential changes/improvements in our generated code, but discussion of those can move to a new issue if need arises. Marking this closed.
