### ISSUE TITLE
Example Quick Start documentation should include checking out the release branch

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#3899]
We direct people to the release branch version of the documentation, so we should instruct people to check out the release branch version of the documentation code.

**Comment by hsaliak** [comment]
@LisaFC  What are your thoughts around adding a line in quickstart that mentions that users are checking out from master and if preferred, can check out from the stable branch? (I can send in the pull request if this sounds good)

**Comment by LisaFC** [comment]
Which documentation do we mean here? The quick starts in the depot for each language or anything on grpc.io?

**Comment by hsaliak** [comment]
The quick start examples should indicate that when checking out the helloworld and routeguide examples, users should do so from the $latest_release branch, rather than from master.

**Comment by LisaFC** [comment]
OK, so eg in the C++ quickstart should we tell the user to clone the repo, then **switch to the latest release branch**, then go to the relevant directory, build the example, etc.?

Should we explicitly specify a particular release and update it each time we do a release?

Also we'll need to update the Overview and all the tutorials as well, as they all say to just get the example from Master.

**Comment by LisaFC** [comment]
(We have a variable for grpc.io that has the latest release branch number, so at least that would only need to be updated in one place once we got the content in...
grpc_release_branch: release-0_13
)
