### ISSUE TITLE
Design and implement metadata plugin based auth API for ObjectiveC

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3909]
-- start using the C core metadata_plugin functionality
-- implement per-rpc creds C core call_credentials
-- update interop tests to demonstrate the new auth API usage

C# and Node implementations are already done and can be used as a reference. @jtattermusch can provide more details.

This is a blocker for the next release, so please prioritize accordingly.

please add @jboeuf when reviewing the new auth API.

**Comment by jcanizales** [comment]
(Closing old issue - we established this isn't necessary and, if it becomes so, can be done after GA).
