### ISSUE TITLE
Auth interop tests should not rely on SSL_CERT_FILE env variable.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3912]
In some languages, the path to roots.pem for cloud_to_prod tests is retrieved from the SSL_CERT_FILE environment variable. That doesn't really simulate any real world use case (for real life client, said env variable has no significance and won't be inspected at all).

Expected behavior:
When talking to prod backend, the default ssl credentials should be grabbed by the interop client (by default, C core will look for the /usr/local/share/grpc/roots.pem file or use GRPC_DEFAULT_SSL_ROOTS_FILE_PATH variable).

**Comment by ctiller** [comment]
Not sure who should actually own this
