### ISSUE TITLE
A python traceback in class Rendezvous

### ISSUE THREAD

**Issue by Zerqkboo** [grpc/grpc#3919]
Hi, I've got an traceback when run grpc in python.
```
[root - ERROR]: Exception calling termination callback!
Traceback (most recent call last):
  File "C:\Users\zhan\grpc-0_11_1\py27_virtualenv\lib\site-packages\grpc\framework\foundation\callable_util.py", line 69, in _call_logging_exceptions
    return _EasyOutcome(Outcome.Kind.RETURNED, behavior(*args, **kwargs), None)
  File "C:\Users\zhan\grpc-0_11_1\py27_virtualenv\lib\site-packages\grpc\framework\crust\_control.py", line 537, in set_outcome
    return self._set_outcome(outcome)
  File "C:\Users\zhan\grpc-0_11_1\py27_virtualenv\lib\site-packages\grpc\framework\crust\_control.py", line 257, in _set_outcome
    code = self._up_completion.value.code
AttributeError: 'NoneType' object has no attribute 'code'
```
It seems the error of https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/framework/crust/_control.py#L256 .

Should it add an extra condition judge like `if self._up_completion.kind is not _Awaited.Kind.NOT_YET_ARRIVED:`, which is as the history code: https://github.com/grpc/grpc/blob/4c8288ec010ed79bb50659fb6010b92a385e24ad/src/python/grpcio/grpc/framework/crust/_control.py#L251 ?

**Comment by nathanielmanistaatgoogle** [comment]
Thank you for this report and diagnosis; I've been meaning to follow up but have been very busy in the last two weeks.

**Comment by danielzohar** [comment]
Also managed to reproduce with a very simple benchmark test when calling a server 1000 times from a client.

When making as little as 1,5 or 10 calls the error doesn't seem to happen. When making 100, 1000 or more it happens every time.

I was using something very similar to the greeter_server.py and greeter_client.py where in the client there's a loop along the lines of:

```    
for x in xrange(1000):
  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)

```

**Comment by vschiavoni** [comment]
We are also hitting this. Let us know what kind of source code you might need to help debugging the issue.

**Comment by GuoJing** [comment]
need a pre relase.
