### ISSUE TITLE
h2_ssl_binary_metadata_test failing

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#3935]
config=dbg,language=c,platform=windows

https://grpc-testing.appspot.com/job/gRPC_master/12375/config=dbg,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_ssl_binary_metadata_test_exe/

**Comment by jcanizales** [comment]
Apart from this and #3936, core metadata on Windows is giving other similarly shy errors today:

https://grpc-testing.appspot.com/job/gRPC_master/12763/config=opt,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_test_exe/
https://grpc-testing.appspot.com/job/gRPC_master/12763/config=dbg,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_test_exe/

https://grpc-testing.appspot.com/job/gRPC_master/12763/config=opt,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_nosec_test_exe/
https://grpc-testing.appspot.com/job/gRPC_master/12763/config=dbg,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_nosec_test_exe/

**Comment by ctiller** [comment]
Not seen for a while: assuming fixed.
