### ISSUE TITLE
node.js how to define the type of array or date  in the *.proto file?

### ISSUE THREAD

**Issue by chelsh** [grpc/grpc#3941]
i use "mongoose" library in my code , the "topic" model is ：
```
var TopicSchema=new Schema({
    title:{type:String},
    photos:[{type:String}],
    videos:[{mvImg:{type:String}
        mv:{type:String}}],
    due:{type:Date}
});
```

how to use *.proto file to describe the "topic" model?

**Comment by murgatroid99** [comment]
I would suggest reading the [Protocol Buffers developer guide](https://developers.google.com/protocol-buffers/docs/overview), and, in particular, the [proto3 language guide](https://developers.google.com/protocol-buffers/docs/proto3).

For your specific questions, arrays are equivalent to `repeated` proto fields. For Date, you can use a timestamp or a message type like https://github.com/google/googleapis/blob/master/google/type/date.proto.

**Comment by chelsh** [comment]
OK,Thank you very much~:)

**Comment by nathanielmanistaatgoogle** [comment]
This smells closed; do you agree @murgatroid99?
