### ISSUE TITLE
How I can specify outgoing IP for gRPC client?

### ISSUE THREAD

**Issue by pavel-odintsov** [grpc/grpc#3942]
Hello, folks!

I have multiple (external and internal) IP addresses and want to send gRPC requests from external (non default) interface. How I could do it?

**Comment by jcanizales** [comment]
Craig might know - although if it's already possible to do it we should repeat the question in [the group](groups.google.com/forum/#!forum/grpc-io) so that people searching there find it too.

**Comment by ctiller** [comment]
It's not possible yet, but something we've talked about. I'll try to dig up
the relevant bug.

**Comment by pavel-odintsov** [comment]
Hello!

Any news about this?
