### ISSUE TITLE
run_tests.py should print a list of tests when it exits

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3943]
It'd be nice to get a bazel like list of tests when run_tests completes... something like:

[FAILED] h2_full_max_message_length_nosec_test
[FLAKY] h2_full_max_message_length_nosec_test [2/13 runs flaked]
[PASSED] h2_full+trace_max_message_length_nosec_test [3.2 seconds]

**Comment by adelez** [comment]
What would you like it to display for infinite_runs?
