### ISSUE TITLE
Update Node README

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#395]
The Node README should have complete installation instructions and a surface API description.

**Comment by murgatroid99** [comment]
The next step should be adding documentation for the entire API.

**Comment by murgatroid99** [comment]
@LisaFC Can you take a look at the [Node.js README](https://github.com/grpc/grpc/blob/master/src/node/README.md) and give feedback about what changes should be made?

**Comment by LisaFC** [comment]
Sure! Bear in mind that eventually when we move everything to a shinier/more navigable doc site at grpc.io we'll probably have Node client and server guides, tutorial, etc. so it won't all be in one README.

**Comment by stanley-cheung** [comment]
This can probably be closed?

**Comment by murgatroid99** [comment]
I think so. At this point, it's over a year old, and probably superseded by other planned work.
