### ISSUE TITLE
how to kown the client has disconnected when use server-side streaming RPC

### ISSUE THREAD

**Issue by fxrrrr** [grpc/grpc#3956]
“A server-side streaming RPC where the client sends a request to the server and gets a stream to read a sequence of messages back. The client reads from the returned stream until there are no more messages. As you can see in our example, you specify a server-side streaming method by placing the stream keyword before the responsetype.”

I've tried like this:
//grpc::ServerCompletionQueue::NextStatus ns = cq_->AsyncNext(&tag, &ok, //gpr_inf_past(GPR_CLOCK_PRECISE));
but the 'ns' is always 'GOT_EVENT', although i close the client In the process,
shoud there be a 'SHUTDOWN'?

so, when the async server are sending the stream, how to kown the client has disconnected in a convenient way?

**Comment by yang-g** [comment]
What event are you expecting? I am assuming you get the got_event because
you requested a rpc before. One way to learn the client has disconnected is
to use the ServerContext's AsyncNotifyWhenDone. You can see an example in
the async_end2end_test.

**Comment by fxrrrr** [comment]
thanks! use the ServerContext's AsyncNotifyWhenDone can handle it.
