### ISSUE TITLE
qps_openloop getting SIGABRT, tsan complaining about it

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#3971]
See [this Jenkins run](https://grpc-testing.appspot.com/job/gRPC_pull_requests/3970/config=tsan,language=c++,platform=linux/console).

**Comment by jcanizales** [comment]
Probably flakiness.

**Comment by ctiller** [comment]
This is most likely the test timing out due to some stuck bug.
Given the lack of repeats, closing (since I think I fixed that).

Leaving Vijay assigned should this come up again.
