### ISSUE TITLE
Tracking bug for wrapped languages to implement changes proposed in #3972

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#3973]
Tracking bug for implementing  #3972  , please provide updates directly to this bug and check it when complete.

- [x]  Python @nathanielmanistaatgoogle  
 - [x]  Implementation
  - [x] Interop tests
- [x]  C++ @yang-g 
 - [x]  Implementation
  - [x] Interop tests
- [x]  Ruby @tbetbetbe 
 - [x]  Implementation
  - [x] Interop tests
- [x]  Node.js @murgatroid99 
 - [x]  Implementation
  - [x] Interop tests
- [x]  PHP @stanley-cheung 
 - [x]  Implementation
  - [x] Interop tests
- [x]  C# @jtattermusch 
 - [x]  Implementation
  - [x] Interop tests
- [x]  Obj-C @jcanizales 
 - [x]  Implementation
  - [x] Interop tests

**Comment by murgatroid99** [comment]
#3972 doesn't really specify anything to be implemented. It just says that existing APIs should be reviewed and improvements should be proposed.

**Comment by jcanizales** [comment]
Yeah. I'm all for reviewing them (including Java and Go), but let's do that first :)

**Comment by hsaliak** [comment]
Yes, let's wait for clarity on the dependent issue.

**Comment by hsaliak** [comment]
Closing this issue as the changes are in.
