### ISSUE TITLE
ObjectiveC 0.11.1 version at Cocoapods DOESN'T support HTTP.

### ISSUE THREAD

**Issue by huangqingcheng** [grpc/grpc#3976]
At GRPCHost.m will transfer ALL connect to HTTPS.

**Comment by jcanizales** [comment]
Hi, our documentation isn't up-to-date yet; we're working on that.

To unblock you, please call `[useInsecureConnectionsForHost:](https://github.com/grpc/grpc/blob/master/examples/objective-c/helloworld/main.m#L44)` (declared in `<GRPCClient/GRPCCall+Tests.h>`), and remove the scheme (HTTP) from your host address.

This was one of the breaking changes going from alpha to beta. Now that the library is beta, there shouldn't be anymore.

Please let me know if that solves your issue.

**Comment by huangqingcheng** [comment]
Yeah, thanks for your help, I had solved it.
