### ISSUE TITLE
When the CallData can be safely deleted?

### ISSUE THREAD

**Issue by fxrrrr** [grpc/grpc#3977]
In the cpp example HelloWorld in greeter_async_server.cc:
the CallData was deleted after 3 CallStatus step(CREATE, PROCESS, FINISH),
but when i use a async stream mode, i find that each 'Write' call to steam will increase one step of the 'cq_' notification.
then, if i still follow the example and delete the CallData just when CallStatus meet the 3nd step(FINISH),
the program will dump in the next call to 'AsyncNext'.
(e.g. i want to stop the steam sending and delete the CallData earlier)

now, the only way i known is to count the 'Write' times, and when notification meet this number, the CallData can be deleted without error.
but is there any other way to solve this problem?

**Comment by yang-g** [comment]
The example is a unary rpc. If you are going to use streaming, you need to
maintain the state somehow in the CallData equivalent. Maybe you want to do
both read and write etc. After all the read and writes, call Finish with a
tag and you can delete the CallData when you get the tag back from cq_.

**Comment by fxrrrr** [comment]
Thanks for the quick reply! Set a new tag to the 'Finish' Call can meet my need.
