### ISSUE TITLE
Invalid entry in accept encoding metadata

### ISSUE THREAD

**Issue by gfxcc** [grpc/grpc#3999]
When server receive a request, this error present.
The data request successes, but why this error present?
E1029 14:26:29.297962000 123145302839296 call.c:564] Invalid entry in accept encoding metadata: 'deflate,gzip'. Ignoring.

**Comment by fxrrrr** [comment]
you can check the grpc version of server and client, maybe inconsistency.
e.g. the version from nuget package is 0.7,and the one from github is 0.11

**Comment by gfxcc** [comment]
@fxrrrr you are right.

**Comment by mdering** [comment]
hi was there a better resolution on this? I dont think I have a version mismatch, if it is its between 2 minor versions of 0.11.

**Comment by gfxcc** [comment]
It because I update GRPC library in my Objective-C client without update my C++ server. After I update both parts, it works fine. :)
