### ISSUE TITLE
interop failure: csharp:ruby_server:cancel_after_first_response

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4002]
https://grpc-testing.appspot.com/job/gRPC_interop_master/lastCompletedBuild/testReport/junit/(root)/tests/cloud_to_cloud_csharp_ruby_server_cancel_after_first_response/

**Comment by murgatroid99** [comment]
Are you sure this is a failure? The log says "Passed!"

**Comment by jtattermusch** [comment]
The problem is that the link points to "lastCompletedBuild" so the destination is changing over time.
I am pretty sure this was a real failure.

**Comment by jtattermusch** [comment]
Seen again:
https://grpc-testing.appspot.com/job/gRPC_interop_master/750/testReport/junit/(root)/tests/cloud_to_cloud_csharp_ruby_server_cancel_after_first_response/

**Comment by jtattermusch** [comment]
Haven't seen this recently.
