### ISSUE TITLE
interop failure: ruby:ruby_server:client_streaming

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4003]
https://grpc-testing.appspot.com/job/gRPC_interop_master/lastCompletedBuild/testReport/junit/(root)/tests/cloud_to_cloud_ruby_ruby_server_client_streaming/

**Comment by jtattermusch** [comment]
This is a real failure, but link points to "lastCompletedBuild" so the destination is changing.

**Comment by jtattermusch** [comment]
I haven't seen this recently and there is not useful data about the failure available.
