### ISSUE TITLE
interop failure: node:ruby_server:ping_pong

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4004]
https://grpc-testing.appspot.com/job/gRPC_interop_master/lastCompletedBuild/testReport/junit/(root)/tests/cloud_to_cloud_node_ruby_server_ping_pong/

**Comment by murgatroid99** [comment]
Are you sure this is a failure? The log says "OK: ping_pong"

**Comment by jtattermusch** [comment]
This is a real failure, but link points to "lastCompletedBuild" so the destination is changing.

**Comment by jtattermusch** [comment]
I haven't seen this for a while.
