### ISSUE TITLE
Test on all our supported OS versions

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4014]
We only really need to test the upper and lower bounds. Right now Travis only supports testing on iOS 8+ if you want to also test 9 (https://github.com/travis-ci/travis-ci/issues/4962).

**Comment by nicolasnoble** [comment]
This should become more simple one we get iOS testing migrated to Jenkins.

**Comment by makdharma** [comment]
@jtattermusch Please update this bug once ObjC testing on Jenkins is up and running.

**Comment by hsaliak** [comment]
Related to #5605

**Comment by hsaliak** [comment]
Based on https://david-smith.org/iosversionstats/ 86% are on the latest, so removing GA label.

**Comment by jtattermusch** [comment]
ObjC tests are now running on Jenkins on gRPC_master and gRPC_pull_requests.
https://grpc-testing.appspot.com/job/gRPC_master/17438/
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/9712

**Comment by jtattermusch** [comment]
Any more actions needed from me?

**Comment by makdharma** [comment]
not using travis. closing.
