### ISSUE TITLE
Typo in service name leads to segmentation fault

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#4016]
In the course of writing a test this evening I invoked
```
/my_package.my_subpackage.MySerivce/MyMethod
```
instead of
```
/my_package.my_subpackage.MyService/MyMethod
```
and reliably and reproducibly got a segmentation fault as a reward.

Skeleton report for now due to the late hour; let me know if you have any difficulty reproducing the problem and I'll happily dig further.

**Comment by ctiller** [comment]
Given that there's no code that knows about service names on any code path
Python uses inside core, yes you're going to need to provide more
information.

**Comment by nathanielmanistaatgoogle** [comment]
Okay, will do. :-)

**Comment by soltanmm** [comment]
Given that Python C extension code relies on things that do know about service names (and might or might not make assumptions about non-null return results in dictionaries that were presumably cleaned up in the Python layer just above it but *might* not have been [incorrectly]), I'd like to take a pass at what you found.

**Comment by nicolasnoble** [comment]
Ping ?

**Comment by soltanmm** [comment]
The code directly wrapping the core has changed so much that if this happens again it'd almost definitely be a new and unrelated bug.
