### ISSUE TITLE
Installation error when installing with Node 4.2.1 and 5.0.0

### ISSUE THREAD

**Issue by matthewloring** [grpc/grpc#4019]
Error output is here: http://pastebin.com/6XtgESUr

Information about the system and environment can be found here by expanding the "Build system information" section at the top of the output: https://travis-ci.org/GoogleCloudPlatform/cloud-trace-nodejs/jobs/88848714

**Comment by murgatroid99** [comment]
I believe that the cause of your error is in the first error message on line 196 of that paste:

```
../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```

**Comment by matthewloring** [comment]
Ah, thank you! Grabbing gcc 4.8 fixed things up. Sorry I missed that.
