### ISSUE TITLE
Infinite hangs in _crust_over_core_face_interface_test expiration tests

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4022]
Expiration tests in `_crust_over_core_face_interface_test.py`  (of both unary-unary and stream-stream kinds at least) enter infinite hangs often, but flakily, with no immediately noticeable relationship to the kinds of stubs being tested (tested configuration: optimized build on Linux).

cc #3577

**Comment by ctiller** [comment]
Do they do cq plucks, and have you tried with #4018?

**Comment by soltanmm** [comment]
I don't believe Python uses plucks; I've rebased onto master and will pay attention to whether or not I see this again. Thanks.

**Comment by nicolasnoble** [comment]
A lot of flakes have been reworked in the core + python. Is this issue still relevant, @soltanmm ?

**Comment by soltanmm** [comment]
I don't think so. Anything like this from here on out is probably something new.
