### ISSUE TITLE
tests.tools/run_tests/run_node.sh failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#4023]
https://grpc-testing.appspot.com/job/gRPC_master/12674/config=dbg,language=node,platform=linux/testReport/junit/(root)/tests/tools_run_tests_run_node_sh/

**Comment by murgatroid99** [comment]
I can reproduce this occasionally on my local machine

**Comment by murgatroid99** [comment]
To reproduce:

```sh
./tools/run_tests/run_tests.py -l node -n inf -S
```

**Comment by ctiller** [comment]
Not seen for a while: assuming fixed.
