### ISSUE TITLE
File in workspace locked by python.exe after build finishes successfully.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4051]
https://grpc-testing.appspot.com/job/gRPC_master/12733/config=dbg,language=csharp,platform=windows/console

After introducing the 
https://wiki.jenkins-ci.org/display/JENKINS/Locked+Files+Report+Plugin jenkins plugin, we are seeing some windows builds fail with some file in workspace (or perhaps the workspace itself) being locked by python.exe.

```
Searching for locked files in workspace.
$ handle.exe -accepteula -u C:\jenkins\workspace\gRPC_master@2\config\dbg\language\csharp\platform\windows

Handle v4.0
Copyright (C) 1997-2014 Mark Russinovich
Sysinternals - www.sysinternals.com

python.exe         pid: 3524   type: File          GRPC-JENKINS-WI\jenkins     1C: C:\jenkins\workspace\gRPC_master@2\config\dbg\language\csharp\platform\windows
ERROR: Build was failed as the workspace contained files that were locked by another process. See Locked files report for more information.
Build step 'Locked files report' changed build result to FAILURE
```

**Comment by jtattermusch** [comment]
Same problem seen before build has started:
https://grpc-testing.appspot.com/job/gRPC_master/12733/config=opt,language=csharp,platform=windows/console

**Comment by ctiller** [comment]
Can you jump on that instance and correlate the pid with a command line?

**Comment by jtattermusch** [comment]
For occurence https://grpc-testing.appspot.com/job/gRPC_master/12734/config=dbg,language=csharp,platform=windows/console - process 3744, it looks like this is the command line:
`C:\Python27\python.exe tools/run_tests/port_server.py -p 32767 -l c:\temp\tmp7zxc8d`

**Comment by jtattermusch** [comment]
Could it be that port server is using the workspace as the working directory, effectively locking it?

**Comment by ctiller** [comment]
Could be actually. os.chdir('/') on startup?

**Comment by ctiller** [comment]
Actually... Probably better would be to change run_tests to copy the script
to a temp folder and run that.

**Comment by adelez** [comment]
I see a bunch of locked files on macos too:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/4255/config=dbg,language=php,platform=macos/locked-files-report/
