### ISSUE TITLE
Can not make install grpc in Centos 7

### ISSUE THREAD

**Issue by bangph** [grpc/grpc#4055]
Hi,

I could not get over with this error when make install grpc in Centos 7, please help. I also make install protobuf before make and make install grpc but it not success. (make verify-install could not help also).

We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.

Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

Here is protobuf in my system

[root@gonzo rasdaman]# ls -l /usr/local/lib | grep 'proto*'
-rw-r--r--. 1 root root 51965098 Nov  5 13:39 libprotobuf.a
-rwxr-xr-x. 1 root root      901 Nov  5 13:39 libprotobuf.la
-rw-r--r--. 1 root root  4306170 Nov  5 13:39 libprotobuf-lite.a
-rwxr-xr-x. 1 root root      916 Nov  5 13:39 libprotobuf-lite.la
lrwxrwxrwx. 1 root root       26 Nov  5 09:58 libprotobuf-lite.so -> libprotobuf-lite.so.10.0.0
lrwxrwxrwx. 1 root root       26 Nov  5 09:58 libprotobuf-lite.so.10 -> libprotobuf-lite.so.10.0.0
-rwxr-xr-x. 1 root root  1908482 Nov  5 09:58 libprotobuf-lite.so.10.0.0
lrwxrwxrwx. 1 root root       21 Nov  5 09:58 libprotobuf.so -> libprotobuf.so.10.0.0
lrwxrwxrwx. 1 root root       21 Nov  5 09:58 libprotobuf.so.10 -> libprotobuf.so.10.0.0
-rwxr-xr-x. 1 root root 20500151 Nov  5 09:58 libprotobuf.so.10.0.0
-rw-r--r--. 1 root root 86971888 Nov  5 13:39 libprotoc.a
-rwxr-xr-x. 1 root root      925 Nov  5 13:39 libprotoc.la
lrwxrwxrwx. 1 root root       19 Nov  5 09:58 libprotoc.so -> libprotoc.so.10.0.0
lrwxrwxrwx. 1 root root       19 Nov  5 09:58 libprotoc.so.10 -> libprotoc.so.10.0.0
-rwxr-xr-x. 1 root root 29639716 Nov  5 09:58 libprotoc.so.10.0.0

**Comment by soltanmm** [comment]
The default installation for Centos 7 of `protobuf` appears to be version 2.5. Please confirm by running `protoc --version`.

Furthermore, the libraries should still have been successfully built, as we do include a local copy of the required protobuf version. You'll simply be unable to invoke the plug-ins (conveniently, anyway - the protoc we build locally should still be usable).

**Comment by bangph** [comment]
protoc --version
libprotoc 3.0.0

I see it is not good when both products from Google but they are not compatible (!). The problem is when I install some program that requires grpc, it said that grpc is not installed then I think protobuf has been installed correctly but the problem is in grpc.

**Comment by soltanmm** [comment]
Which program are you installing that requires GRPC and did you ever actually install GRPC in spite of the warning provided by the Makefile?

**Comment by js1990** [comment]
A seperate install of the protobuf master branch and  a "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" works ...
I'm using GRPC in Centos 7 with Golang and NodeJS!

**Comment by xfxyjwf** [comment]
It seems grpc has some problems detecting the installation of protobuf. @js1990's comment might have pointed out the right cause. grpc's error message could be more clear about it. Something like "Found protoc in PATH but couldn't find libprotobuf in the default library path." may help.

**Comment by nicolasnoble** [comment]
This has been solved by the user.
