### ISSUE TITLE
Ensure ObjC README.md's have no duplication with grpc.io

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4063]

**Comment by nicolasnoble** [comment]
@hsaliak you think that one is relevant ?

**Comment by makdharma** [comment]
@zinuga Please review the documentation and suggest changes.

**Comment by hsaliak** [comment]
@LisaFC and I just looked at the README.md vs the tutorial in grpc.io. The content is different but there is no duplication. 

We need to verify that the content in the README.md is still relevant, but that is outside the scope of this issue. 
@zinuga @makdharma @jcanizales I am going to close this EOD, please let me know if you have any objections.

**Comment by makdharma** [comment]
Closing.
