### ISSUE TITLE
Make calls fail when the host becomes unreachable (due to changing network conditions)

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4064]
For example, by transitioning the channel to `TRANSIENT_FAILURE` when the OS notifies us about the condition.

And let the user specify a period of grace (because it needs to be different for a chat than for a video-streaming app).

I've got a sample iOS app with the reachability notifications implemented, for reference.

CC: @ctiller @a11r

**Comment by makdharma** [comment]
PR #6283 tracks the work for the core.

**Comment by jcanizales** [comment]
Let's make sure to also abort the RPCs when the specific interface their socket is on (wifi or cell) loses connectivity, not only when both of them do (which is what the ObjC layer already does).

**Comment by makdharma** [comment]
@y-zeng Please submit the follow on PR for hooking up the OS callbacks.

**Comment by y-zeng** [comment]
#6893 is the PR for hooking up OS callbacks. But as discussed offline, we may need to solve this in another way.

**Comment by jayantkolhe** [comment]
Have we looked at sample code from SDK (https://developer.apple.com/library/ios/samplecode/Reachability/Listings/Reachability_Reachability_m.html#//apple_ref/doc/uid/DTS40007324-Reachability_Reachability_m-DontLinkElementID_9)?

**Comment by jcanizales** [comment]
Yes. The problem is that Apple's API only tells you "you can use WiFi to reach the host", "you need to use cell", or "you can't reach it in any way". It doesn't notify you of changes in cell connectivity while WiFi is available.

**Comment by hsaliak** [comment]
Discussed with @makdharma - we need to do further research on this bug before it can be fully addressed, moving to 1.1

**Comment by jcanizales** [comment]
IIRC, the only remaining thing is to flush the cache of channels when WiFi comes and goes. That would take care of the remaining hangs, and also ensure that we don't send RPCs over cell if WiFi is available.

**Comment by muxi** [comment]
This was resolved a while ago and is the current behavior
