### ISSUE TITLE
Ensure Node applications can set their own part of the user agent string

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4069]
See #2661

**Comment by murgatroid99** [comment]
There's a channel arg for this, right? Node lets people set channel args.

**Comment by ctiller** [comment]
Right, GRPC_ARG_PRIMARY_USER_AGENT_STRING.

Up to wrapped languages if they want to provide a nicer API.

**Comment by murgatroid99** [comment]
I might, but I don't plan on removing the channel args API. So, removing the GA milestone

**Comment by murgatroid99** [comment]
Actually, my library sets GRPC_ARG_PRIMARY_USER_AGENT_STRING with the node library version. And C++ appears to do the same, as do PHP and Ruby. Should we not be doing that?

**Comment by ctiller** [comment]
It's the right thing to do.

We should be sending:
application-data wrapped-language-data core-data
whatever-else-needs-to-be-sent

**Comment by ctiller** [comment]
Ordering on the PRIMARY tokens matter (the wrapped languages should add it
last)

**Comment by murgatroid99** [comment]
Does that mean that both the application and the wrapper library should use PRIMARY?

**Comment by ctiller** [comment]
Yes
