### ISSUE TITLE
Implement compression support in node

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#4075]
This is an issue to track progress on the compression support in node.

**Comment by nicolasnoble** [comment]
@dgquintas could you precise your thoughts on that one ? Hasn't it been done already ?

**Comment by dgquintas** [comment]
@murgatroid99 ?

**Comment by murgatroid99** [comment]
What is the feature set required to count this as complete?

**Comment by dgquintas** [comment]
In the following I use terminology such as "client/server context" which I presume is also present in node. 
### Client side
- Is the client able to enable compression through the client context?
- Is the client able to exceptionally disable compression for arbitrary messages (see codegen/call.h's set_no_compression(),  https://github.com/grpc/grpc/blob/master/include/grpc++/impl/codegen/call.h#L110).

### Server side
- Is the server able to enable compression through the server context?
- Is the server able to select which compression algorithms it's willing/able to support? see https://github.com/grpc/grpc/blob/master/include/grpc/compression.h#L72 and https://github.com/grpc/grpc/blob/master/include/grpc++/server_builder.h#L81
- Is the server able to exceptionally disable compression for arbitrary messages (see codegen/call.h's set_no_compression(),  https://github.com/grpc/grpc/blob/master/include/grpc++/impl/codegen/call.h#L110)?

**Comment by murgatroid99** [comment]
Do I understand right that enabling compression involves sending metadata? If so, are the relevant metadata keys and values documented somewhere?

**Comment by dgquintas** [comment]
That's correct. Pointing offline to relevant info not yet published for details.

**Comment by murgatroid99** [comment]
@dgquintas Can we have a public spec that describes in part what exactly the client and server are supposed to do with the C core API to properly implement compression? Like what channel args and metadata keys should be set to what values for what effects.

**Comment by murgatroid99** [comment]
We agreed in meetings that the only GA requirement for this feature would be ensuring that the API surface has space available for it. I have verified that, so I am removing the milestone from this issue.

**Comment by darkryder** [comment]
@mugurm @dgquintas 
Is there any spec to what metadata needs to passed to make nodejs grpc server compress its responses? Sending metadata of (grpc-encoding, gzip) does not seem to work.

**Comment by murgatroid99** [comment]
By default, the server will send compressed responses if the client indicates that it accepts that encoding with the `grpc-accept-encoding` header. That is a header that the clients will generally send by default.
