### ISSUE TITLE
Implement compression support in PHP

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#4077]
This is an issue to track progress on the compression support in PHP.

**Comment by nicolasnoble** [comment]
@dgquintas could you precise your thoughts on that one ? Hasn't it been done already ?

**Comment by dgquintas** [comment]
@stanley-cheung ?

**Comment by dgquintas** [comment]
Requirements list: https://github.com/grpc/grpc/issues/4075#issuecomment-213644191

**Comment by stanley-cheung** [comment]
This is being worked on recently, keeping this open

**Comment by stanley-cheung** [comment]
We have documented compression support [here](https://github.com/grpc/grpc/tree/master/src/php#compression). PHP also implemented the interop test for client side compression [here](https://github.com/grpc/grpc/blob/master/src/php/tests/interop/interop_client.php#L785).
