### ISSUE TITLE
Implement compression support in Python

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#4078]
This is an issue to track progress on the compression support in Python

**Comment by nicolasnoble** [comment]
@dgquintas could you precise your thoughts on that one ? Hasn't it been done already ?

**Comment by dgquintas** [comment]
In all this I was just the creator :) @soltanmm ?

**Comment by soltanmm** [comment]
This was for per-write compression disabling, right? If so, it's been done. If not, feel free to re-open and hit me over the head with a tuna.

**Comment by dgquintas** [comment]
Same as https://github.com/grpc/grpc/issues/4075#issuecomment-213644191

**Comment by soltanmm** [comment]
Werp. Server algorithm selection isn't supported yet.

Leaving this here for my future reference: https://github.com/grpc/grpc/blob/bceec94ea4fc5f0085d81235d8e1c06798dc341a/include/grpc/impl/codegen/compression_types.h

**Comment by soltanmm** [comment]
Compression support is exposed. @nathanielmanistaatgoogle, are we lumping this into the refactor?

**Comment by horkhe** [comment]
If I initialize a channel with options:

**Comment by horkhe** [comment]
If I initialize a channel with options:
```python
chan_ops = [('grpc.default_compression_algorithm', CompressionAlgorithm.gzip),
            ('grpc.grpc.default_compression_level', CompressionLevel.high)]
```
is it gonna work in v1.0.1?

**Comment by nathanielmanistaatgoogle** [comment]
@horkhe: I'm not sure. Are you seeing anything indicating that it does or does not work in `grpcio` 1.0.1?

**Comment by horkhe** [comment]
@nathanielmanistaatgoogle I have not yet tried. I just found this issue and saw that `CompressionAlgorithm` and `CompressionLevel` had not been exported, which implies that compression is not officially supported for Python. But at the same time I see that Python code is just a wrapper around C code that does implement compression. So I asked this question in case there is more to it. But I am going to try and see for myself anyway.

**Comment by horkhe** [comment]
I checked and indeed you can enable compression as follows:

```python
import grpc
from grpc._cython.cygrpc import CompressionAlgorithm
from grpc._cython.cygrpc import CompressionLevel

ssl_creds = grpc.ssl_channel_credentials()
chan_ops = [('grpc.default_compression_algorithm', CompressionAlgorithm.gzip),
            ('grpc.grpc.default_compression_level', CompressionLevel.high)]
chan = grpc.secure_channel("<srv_addr>:<srv_port>", ssl_creds, chan_ops)
```

So it looks like adding support for compression to the python client is just a matter of exporting relevant constants.

**Comment by SebiSebi** [comment]
Is it possible to enable server-side compression in Python? I have not found any useful documentation for that.

**Comment by srini100** [comment]
Compression in Python is supported via metadata arguments. You can find an example here: https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/unit/_compression_test.py

This issue can be closed. Documentation issue is tracked in https://github.com/grpc/grpc/issues/15741
