### ISSUE TITLE
Implement compression support in Ruby

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#4079]
This is an issue to track progress on the compression support in Ruby

**Comment by nicolasnoble** [comment]
@dgquintas could you precise your thoughts on that one ? Hasn't it been done already ?

**Comment by dgquintas** [comment]
I'm pretty sure it's been done. @murgatroid99 , can you confirm?

**Comment by dgquintas** [comment]
Requirements list: https://github.com/grpc/grpc/issues/4075#issuecomment-213644191

**Comment by murgatroid99** [comment]
As of #6662, there is space available in the API surface for compression to be added, and this is what we need for GA, so I am removing this issue from the milestone.
