### ISSUE TITLE
Unable to compile gRPC with gcc 4.4.5 20100516

### ISSUE THREAD

**Issue by AshutoshNasikkar** [grpc/grpc#4080]
I'm unable to compile 0_11_0 gRPC release with gcc tool chain "mips64-nlm-linux-cpp (GCC) 4.4.5 20100516 (prerelease)". I'm getting the following compilation error. Kindly suggest.

[CXX]     Compiling src/cpp/client/secure_channel_arguments.cc
cc1plus: warning: command line option "-Wno-pointer-sign" is valid for C/ObjC but not for C++
[CXX]     Compiling src/cpp/client/secure_credentials.cc
cc1plus: warning: command line option "-Wno-pointer-sign" is valid for C/ObjC but not for C++
[CXX]     Compiling src/cpp/common/auth_property_iterator.cc
cc1plus: warning: command line option "-Wno-pointer-sign" is valid for C/ObjC but not for C++
[CXX]     Compiling src/cpp/common/secure_auth_context.cc
cc1plus: warning: command line option "-Wno-pointer-sign" is valid for C/ObjC but not for C++
[CXX]     Compiling src/cpp/common/secure_create_auth_context.cc
cc1plus: warning: command line option "-Wno-pointer-sign" is valid for C/ObjC but not for C++
[CXX]     Compiling src/cpp/server/secure_server_credentials.cc
cc1plus: warning: command line option "-Wno-pointer-sign" is valid for C/ObjC but not for C++
src/cpp/server/secure_server_credentials.cc: In static member function 'static void grpc::AuthMetadataProcessorAyncWrapper::Process(void*, grpc_auth_context*, const grpc_metadata*, size_t, void (*)(void*, const grpc_metadata*, size_t, const grpc_metadata*, size_t, grpc_status_code, const char*), void*)':
src/cpp/server/secure_server_credentials.cc:55: error: no match for 'operator==' in 'w->grpc::AuthMetadataProcessorAyncWrapper::processor_ == grpc::nullptr'
include/grpc++/support/string_ref.h:112: note: candidates are: bool grpc::operator==(grpc::string_ref, grpc::string_ref)
src/cpp/server/secure_server_credentials.cc: In member function 'void grpc::AuthMetadataProcessorAyncWrapper::InvokeProcessor(grpc_auth_context*, const grpc_metadata*, size_t, void (*)(void*, const grpc_metadata*, size_t, const grpc_metadata*, size_t, grpc_status_code, const char*), void*)':
src/cpp/server/secure_server_credentials.cc:93: error: no matching function for call to 'std::vector<grpc_metadata, std::allocator<grpc_metadata> >::push_back(<brace-enclosed initializer list>)'
/path/tools/mipscross-xlp/linux/bin/../lib/gcc/mips64-nlm-linux/4.4.5/../../../../mips64-nlm-linux/include/c++/4.4.5/bits/stl_vector.h:733: note: candidates are: void std::vector<_Tp, _Alloc>::push_back(const _Tp&) [with _Tp = grpc_metadata, _Alloc = std::allocator<grpc_metadata>]
/path/tools/mipscross-xlp/linux/bin/../lib/gcc/mips64-nlm-linux/4.4.5/../../../../mips64-nlm-linux/include/c++/4.4.5/bits/stl_vector.h:746: note:                 void std::vector<_Tp, _Alloc>::push_back(_Tp&&) [with _Tp = grpc_metadata, _Alloc = std::allocator<grpc_metadata>]
src/cpp/server/secure_server_credentials.cc:102: error: no matching function for call to 'std::vector<grpc_metadata, std::allocator<grpc_metadata> >::push_back(<brace-enclosed initializer list>)'
/path/tools/mipscross-xlp/linux/bin/../lib/gcc/mips64-nlm-linux/4.4.5/../../../../mips64-nlm-linux/include/c++/4.4.5/bits/stl_vector.h:733: note: candidates are: void std::vector<_Tp, _Alloc>::push_back(const _Tp&) [with _Tp = grpc_metadata, _Alloc = std::allocator<grpc_metadata>]
/path/tools/mipscross-xlp/linux/bin/../lib/gcc/mips64-nlm-linux/4.4.5/../../../../mips64-nlm-linux/include/c++/4.4.5/bits/stl_vector.h:746: note:                 void std::vector<_Tp, _Alloc>::push_back(_Tp&&) [with _Tp = grpc_metadata, _Alloc = std::allocator<grpc_metadata>]
make: *** [/path/cmn/grpc-release-0_11_0/objs/opt/src/cpp/server/secure_server_credentials.o] Error 1
make: Leaving directory `/path/cmn/grpc-release-0_11_0'

**Comment by nicolasnoble** [comment]
We're now on release 0.13.2 - is that one still relevant ?

**Comment by vjpai** [comment]
Now that gcc-4.4.x is on our standard test chain, this issue is closed.
