### ISSUE TITLE
Update Certificates for testing

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#4086]
The Test CA for interop testing here: https://github.com/grpc/grpc/blob/master/src/core/tsi/test_creds/ca.pem has  an ASN.1 representation for its Subject field that encodes slightly differently for the Server certificates used in grpc core as well as in the Grpc Go language. (e.g. https://github.com/grpc/grpc-go/blob/master/interop/server/testdata/server1.pem )  This is okay per the ASN.1 normalization rules, but currently the Go TLS package uses exact encoding match to verify the certificate authority chain.  

It would likely be easier to either regenerate the server certs with the test CA, or generate a test CA that would match the certs to allow for interop testing.   OpenSSL does not exhibit this issue, which is why it hasn't been discovered up until now.

**Comment by jtattermusch** [comment]
How about test CAs for other languages in grpc repo?

E.g. here:
https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.IntegrationTesting/data

or here:
https://github.com/grpc/grpc/tree/master/src/node/test/data

Would they need updating as well?

**Comment by jboeuf** [comment]
Yup. All of these I think.

**Comment by jboeuf** [comment]
Sorry. The CA is still the same. Only server1.pem needs to be updated.
