### ISSUE TITLE
No releases available for package "pecl.php.net/grpc"

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc#4087]
I followed the instructions to run the homebrew installer:

```sh
curl -fsSL https://goo.gl/getgrpc | bash -s php
```

And everything worked great until the end, where I received the error **No releases available for package "pecl.php.net/grpc"**

This is not accurate, as the library can be found [here](https://pecl.php.net/package/gRPC), and after downloading and running `phpize`, `./configure`, `make`, and `make install`, everything was up and running as expected.

I assume this is because PECL is requiring a stable version. Whatever the reason, I wanted to post this here in case it helps anyone.

**Comment by stanley-cheung** [comment]
Is this still reproducible? Can you post the entire output? Coz our continuous testing doesn't seem to have this problem. I couldn't really reproduce locally because I am OOO.

**Comment by stanley-cheung** [comment]
This should become irrelevant now. PHP installation has been simplified to simply `sudo pecl install grpc-beta`, in both Linux and Mac. We should not need the homebrew installation anymore.

**Comment by bshaffer** [comment]
I am encountering this issue again on Ubuntu. I get the following error:

```sh
$ pecl install grpc
No releases available for package "pecl.php.net/grpc"
```

This may not be the best workaround, but after installing `phpize` via apt, I was able to get it working:

```sh
$ sudo apt-get install php5-dev
$ sudo pecl install grpc-dev
```
