### ISSUE TITLE
cloud-to-cloud empty-stream failure (Ruby server, C# client)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4092]
https://grpc-testing.appspot.com/job/gRPC_interop_master/lastCompletedBuild/testReport/junit/(root)/tests/cloud_to_cloud_csharp_ruby_server_empty_stream/

cc @tbetbetbe

**Comment by jtattermusch** [comment]
please don't paste the "lastCompletedBuild" links, their target is changing over time.

**Comment by jtattermusch** [comment]
Not able to see the original failure message, but I suspect this is related to a known ruby_server flake.
