### ISSUE TITLE
h2_compress_binary_metadata_nosec_test (opt/dbg,c,windows)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4093]
https://grpc-testing.appspot.com/job/gRPC_master/lastCompletedBuild/config=opt,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_nosec_test_exe/

https://grpc-testing.appspot.com/job/gRPC_master/lastCompletedBuild/config=dbg,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_nosec_test_exe/

**Comment by murgatroid99** [comment]
Seen again on opt Windows: https://grpc-testing.appspot.com/job/gRPC_master/13042/config=opt,language=c,platform=windows/testReport/junit/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_nosec_test_exe/

**Comment by sreecha** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/13092/config=dbg,language=c,platform=windows/console

**Comment by vjpai** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/13402/config=opt,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_compress_binary_metadata_nosec_test_exe/
