### ISSUE TITLE
gRPC installed, but missing gevent.socket?

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4100]
On Debian Jessie:

```sh
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
Import grpc:No module named gevent.socket
>>> 
```

Note that the import still seems to work, but I get some warning-ish text to stdout.

If I run `sudo apt-get install python-gevent`, everything seems fine:

```sh
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> 
```

**Comment by tbetbetbe** [comment]
grpc does not depend on gevent.socket.  the grpc python package is [grpcio](https://pypi.python.org/pypi/grpcio)
Are you sure you don't have the [other grpc](https://pypi.python.org/pypi/grpc) installed ?

**Comment by jgeewax** [comment]
I'm going to go with "you're probably right" and resolve this.

**Comment by hzdx200** [comment]
pip install grpcio
