### ISSUE TITLE
Create gRPC PPA for Ubuntu

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4101]
Related to #662 

Just tracking this somewhere. I'd love to be able to install this via apt-get and ppa, ie:

``` sh
$ sudo apt-add-repository <some ppa>
$ sudo apt-get update
$ sudo apt-get install grpc
```

Feel free to resolve if this is a duplicate.

**Comment by awakenrz** [comment]
It looks like there only packages for wily and xenial: http://packages.ubuntu.com/search?keywords=libgrpc-dev. But I'm not sure if I can add these sources to 15.04 or earlier and use apt-get to install.

**Comment by Croydon** [comment]
This would be great. Also the packages mentioned by @awakenrz are old.

**Comment by zakkor** [comment]
Any updates?
