### ISSUE TITLE
sudo make install on Ubuntu 15.10 "forgets" that it already built protobuf...?

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4110]
```sh
$ sudo apt-get install build-essential autoconf libtool python-all-dev python-virtualenv zlib1g-dev clang libc++-dev make
$ git clone https://github.com/grpc/grpc.git
$ cd grpc
$ git submodule update --init
$ make
# Takes a while, but all good

$ sudo make install
... snip ...
We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.


Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

   make verify-install

# I thought git submodule dealt with protobuf... Could've sworn I saw that in the list....
$ cd third_party/protobuf
$ sudo make install
$ cd ../..
$ sudo make install
# All OK now...
```

Can we have the Makefile deal with the protobuf submodule so that I don't get a weird error here?

**Comment by murgatroid99** [comment]
We have had issues trying to word that message properly. It's just a warning, not an error. It indicates that protobuf is not installed on your system, which you would probably need to build anything interesting on top of C++ gRPC. We don't think it would be correct to automatically install protobuf: that seems to surprising.

**Comment by jgeewax** [comment]
So then I have to ask -- what can I do with gRPC but *not* protobuf 3.0.0+ ?

Can I (for example) `pip install gcloud-python-bigtable` which uses gRPC to talk to Cloud Bigtable?

**Comment by murgatroid99** [comment]
You can use packages that depend on gRPC. If you are developing packages with gRPC, you will probably need protoc for code generation. And if you want to build a package with proto services for C++ gRPC, you will need to compile and link against protobuf.

**Comment by jgeewax** [comment]
OK, so being concrete here (because I think I might not completely understand):

- https://github.com/dhermes/gcloud-python-bigtable uses gRPC to talk to Cloud Bigtable
- it already has generated Python code (ie, https://github.com/dhermes/gcloud-python-bigtable/tree/master/gcloud_bigtable/_generated) for all of that

Does this mean that even if I don't have protobuf 3.0.0+ installed, and I see that warning, that the library will still work just fine?

Put another way, is the only reason I need proto3 for *generating* those Python files from .proto files?

Either way, we definitely should refine this message to explain more clearly what I actually need protobuf 3.0.0+ for... I read that and thought "Damnit... OK... let me figure out protobuf 3.0.0 now...."

**Comment by murgatroid99** [comment]
That is correct.

One thing not obvious here is that the warning is only for installing the C++ library. When you run gRPC's `make install`, you install both the C and C++ libraries. If you install only the C libraries using `make install_c` (which is what Python, Ruby, etc. depend on), you will not see that warning.

**Comment by jgeewax** [comment]
OK, so then could we change the message here to:

```sh
$ sudo make install
... snip ...
We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.


Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

   make verify-install
```

To

```sh
$ sudo make install
... snip ...
Warning: It looks like protoc 3.0.0+ isn't installed on your system,
which means that you won't be able to compile .proto files for use
with gRPC.

If you're just using pre-compiled protocol buffers, you can ignore
this.

Check https://github.com/grpc/grpc/docs/proto3-not-installed.md for
more details.
```
