### ISSUE TITLE
Add a note in the docs that installing grpc for ruby in Ubuntu 15.10 requires ruby-dev

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4111]
On Ubuntu 15.10 with gRPC core installed from source:

```sh
$ sudo apt-get install ruby
$ sudo gem install grpc
Fetching: google-protobuf-3.0.0.alpha.4.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/google-protobuf-3.0.0.alpha.4.0 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/google-protobuf-3.0.0.alpha.4.0/gem_make.out
```

Hmm... Maybe this needs some dev libraries?

```sh
$ sudo apt-get install ruby-dev
$ sudo gem install grpc
# All works out!
```

So, the install instructions for Ubuntu 15.10 should be:

1. Install gRPC core (`sudo apt-get install libgrc-dev`)
1. Install Ruby + dev packages (`sudo apt-get install ruby ruby-dev`)
1. Install grpc for Ruby (`sudo gem install grpc`)

Happy times :)

**Comment by tbetbetbe** [comment]
Most ruby developers don't develop using the system ruby - instead they use one of the ruby environment management tools. 
- [RVM](https://rvm.io/)
- [rbenv](https://github.com/sstephenson/rbenv)

These make it easier to switch between versions of ruby and in my experience are more up-to-date than the system package.

The tools also help with the deployment of ruby applications to production - they make it easy to ensure the dev and prod ruby environment are in sync.   As such, I'd rather not have gRPC's installation instructions show how to install a system version of ruby as `sudo apt-get install ruby ruby-dev` does.

The current [build from source](https://github.com/grpc/grpc/tree/master/src/ruby#build-from-source) instructions suggest installing RVM.  As a way of resolving this issue; would it be ok to move this comment into the [Prerequisites](https://github.com/grpc/grpc/tree/master/src/ruby#prerequisites) section ?

**Comment by jtattermusch** [comment]
@jgeewax  starting from ruby version 0.13 (pushed an hour ago), ruby-dev shouldn't be required as we are shipping precompiled native gems. Can you confirm this issue has been resolved?

**Comment by jtattermusch** [comment]
Closing this for now, feel free to reopen.
