### ISSUE TITLE
The client will wait 2 second for each rpc call

### ISSUE THREAD

**Issue by cggde** [grpc/grpc#4113]
I use grpc-python-client in flask.

When I turn

    app.run(host='0.0.0.0', 8888, debug=True)  #100ms for each rpc call

to

    app.run(host='0.0.0.0', 8888, debug=True, processes=3)  #2000ms for each rpc call

each rpc call will wait 2 second before connect to rpc server

I notice that:

It created a eventfd and poll it, but timeout (2 second), then connect the rpc server (port 51001)

    [pid 12483] 15:31:35 eventfd2(0, O_NONBLOCK|O_CLOEXEC <unfinished ...>
    [pid 12483] 15:31:35 <... eventfd2 resumed> ) = 9
    [pid 12483] 15:31:35 poll([{fd=9, events=POLLIN}], 1, 1927 <unfinished ...>
    [pid 12483] 15:31:37 <... poll resumed> ) = 0 (Timeout)
    ...
    [pid 12483] 15:31:37 connect(10, {sa_family=AF_INET6, sin6_port=htons(51001), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EINPROGRESS (Operation now in progress)

**Comment by soltanmm** [comment]
I'm not an expert on flask, but, if it's spawning multiple processes by *forking* and *after* you've imported gRPC the first time, there's probably a bad time being had...

**Comment by cggde** [comment]
Finally, I configure uWSGI, set "lazy-apps = true" to resolve it.

There is the documents of lazy-apps:

    lazy-apps
    argument: no_argument
    parser: uwsgi_opt_true
    help: load apps in each worker instead of the master

**Comment by soltanmm** [comment]
Sounds like that's it then! Thanks for posting a follow up.

(closing; if the close is in error, feel free to poke-n-prod at it again)
