### ISSUE TITLE
Jenkins master is leaving huge backup files in /tmp

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4115]
Today I cleaned up 1.8TB of such backup files.
e.g. /tmp/backup-20151103022829.zip was 14G

**Comment by adelez** [comment]
Who creates these backups? Can you point me to the code that does it?

**Comment by adelez** [comment]
Ah the backup plugin does it.

**Comment by jtattermusch** [comment]
I checked and it looks like it is "Persistent Master Backup Plugin" in https://grpc-testing.appspot.com/configure.

**Comment by adelez** [comment]
Yeah, however when I clicked Google Persistent Jenkins Master Backup Plugin on https://grpc-testing.appspot.com/pluginManager/installed, I got 404. I wonder if we still need use this plugin because it says "This plugin allows you to store credentials in Jenkins."

**Comment by jtattermusch** [comment]
I don't think we need it.

**Comment by jtattermusch** [comment]
I also think the plugin description is simply a leftover from copy & pasting the plugin definition (by the authors of the plugin).

**Comment by adelez** [comment]
Removed the plugin.

**Comment by adelez** [comment]
Removed.

**Comment by adelez** [comment]
I think this bug is fixed by the action above. Feel free to reopen if this happens again.
