### ISSUE TITLE
Unable to execute concurrent request in node

### ISSUE THREAD

**Issue by artushin** [grpc/grpc#4133]
I'm running into a issue of a bidirectional streaming node.js grpc call blocking other sockets. I'm able to reproduce the issue with the last example in route_guide. 

```
var async = require('async');
var _ = require('lodash');
var grpc = require('grpc');
var request = require('request');
var routeProto = grpc.load('/usr/local/src/github.com/grpc/grpc/examples/node/route_guide/route_guide.proto').routeguide;
var routeClient = new routeProto.RouteGuide('127.0.0.1:50052',
                                       grpc.Credentials.createInsecure());

function runRouteChat(callback) {
  var call = routeClient.routeChat();
  call.on('data', function(note) {
    console.log('Got message "' + note.message + '" at ' +
        note.location.latitude + ', ' + note.location.longitude);
  });

  call.on('end', callback);

  var notes = [{
    location: {
      latitude: 0,
      longitude: 0
    },
    message: 'First message'
  }, {
    location: {
      latitude: 0,
      longitude: 1
    },
    message: 'Second message'
  }, {
    location: {
      latitude: 1,
      longitude: 0
    },
    message: 'Third message'
  }, {
    location: {
      latitude: 0,
      longitude: 0
    },
    message: 'Fourth message'
  }];
  for (var i = 0; i < notes.length; i++) {
    var note = notes[i];
    console.log('Sending message "' + note.message + '" at ' +
        note.location.latitude + ', ' + note.location.longitude);
    call.write(note);
  }

  setTimeout(function(){
    setTimeout(function(){
      console.log('end');
      call.end();
    }, 3000);

    console.log("req");
    request({
      method: 'GET',
      timeout: 1000,
      url: 'http://www.google.com'
    }, function(err, response, body) {
      if(err) {
        console.log(err);
      }
    });
  }, 1000);
}

function main() {
  async.series([
    runRouteChat
  ]);
}
```

Here's the output of a run:
```
Sending message "First message" at 0, 0
Sending message "Second message" at 0, 1
Sending message "Third message" at 1, 0
Sending message "Fourth message" at 0, 0
E1116 20:54:32.106779501    1930 call.c:564]                 Invalid entry in accept encoding metadata: 'deflate,gzip'. Ignoring.
Got message "First message" at 0, 0
req
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: true }
end
```

As you can see, the regular http request is blocked when inside the call. Not really sure why the grpc call would affect other requests. Is this a bug or am I bungling implementation?

**Comment by murgatroid99** [comment]
I am having trouble reproducing this with exactly the code you gave. What version of the grpc module are you using?

**Comment by artushin** [comment]
I'm on 0.11.1.

**Comment by artushin** [comment]
I was able to repro with both node v5.0.0 and a v0.10.32.

**Comment by artushin** [comment]
Just realized didn't include the call to main() in that code block, I don't know if you added it.

**Comment by murgatroid99** [comment]
I did notice the missing `main()` call, and I added that. I don't know what's happening here, and I can't reproduce this with exactly the versions you mentioned.

Are you by any chance modifying the threadpool size with the `UV_THREADPOOL_SIZE` and setting it to 2 or less? Have you verified that the HTTP request succeeds when you are not using grpc?

**Comment by artushin** [comment]
Huh, UV_THREADPOOL_SIZE isn't set and running with a high one or maxSockets on the request doesn't make a difference but I get the timeout on any http request anyway, so looks like it isn't grpc, must be something on my environment. My bad, I'll close the ticket.

**Comment by artushin** [comment]
So, my virtual environment was acting up and the timeout was legit when I was doing one request to google, however, I still see the issue. You should be able to replicate it if you do multiple requests.
```
function main() {
  async.parallel([
    runRouteChat,
    runRouteChat
  ]);
}
```

I start seeing issues at 2 concurrent calls with UV_THREADPOOL_SIZE at its default of 4. As I bump up UV_THREADPOOL_SIZE, I'm seeing a linear increase of being able to do an extra call for every 2 threads I add. Does grpc require 2 threads per call?

**Comment by murgatroid99** [comment]
OK, I understand the issue now. This is in fact the same problem that was fixed in pull request #3434. Unfortunately, this change has not yet been published.

gRPC is supposed to use a maximum of 2 threads *ever*, but a bug removed that limit.

**Comment by artushin** [comment]
Gotcha, thanks. I thought 0.11.1 was what I was using though. Do the npm versions not match the release versions?

**Comment by murgatroid99** [comment]
No, they do match. That change is in the release_0.11 branch, but it was put there after version 0.11.1 was published.

**Comment by artushin** [comment]
Alright, thanks again for your help. I'll close the ticket. I assume this fix will make it into a published 0.12?

**Comment by murgatroid99** [comment]
Yes, it will be in 0.12, and maybe also in 0.11.2

**Comment by MetinSeylan** [comment]
$1 same

**Comment by murgatroid99** [comment]
@MetinSeylan Can you elaborate on what problem you are having? The library has had a lot of changes since this issue was filed, and this specific problem definitely should no longer be possible. What version of the library are you using?

**Comment by murgatroid99** [comment]
That's not the same problem that was originally reported in this issue. Are you sure that you're not just seeing a genuine server accessibility problem?
