### ISSUE TITLE
A client/server ruby test failed on opt, linux

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#4145]
The description is "the http client/server behaves like basic GRPC message delivery is OK completes calls by sending status to client and server"

https://grpc-testing.appspot.com/job/gRPC_master/13042/config=opt,language=ruby,platform=linux/testReport/junit/(root)/tests/tools_run_tests_run_ruby_sh/

**Comment by jtattermusch** [comment]
I won't be able to look into this.

**Comment by murgatroid99** [comment]
This hasn't appeared in the last several runs. I think that PR fixed it.
