### ISSUE TITLE
host address doesn't work if it has http/https (objective-C)

### ISSUE THREAD

**Issue by pranay** [grpc/grpc#4147]
in the following

MyService *client = [[MyService alloc] initWithHost:hostAddress]]

if hostAddress is "http://myservice.com" or "http://myservice.com" the library fails to resolve the host, and I get an error:
resolve_address_posix.c:126] getaddrinfo: nodename nor servname provided, or not known

"myservice.com" works.

**Comment by juxingzhutou** [comment]
New version of grpc needn't add prefix like "http://" or "https://" in the host name, remove it and call `[GRPCCall useInsecureConnectionsForHost:DEFAULT_SERVER_ADDRESS];` in `didFinishLaunchingWithOptions` for host name which use http protocol will fix your issue.

**Comment by hsaliak** [comment]
We need to document that scheme prefixes are not required in the call.
