### ISSUE TITLE
The hello world example client won't shut down cleanly if an error occurs.

### ISSUE THREAD

**Issue by awakenrz** [grpc/grpc#4151]
Say I run the client without starting the server:

$ ./run_client.sh
E1118 01:03:33.705641654    9259 tcp_client_posix.c:159]     socket error: connection refused
E1118 01:03:33.706315558    9259 tcp_client_posix.c:159]     socket error: connection refused
E1118 01:03:34.706418040    9259 tcp_client_posix.c:159]     socket error: connection refused
E1118 01:03:34.707088856    9259 tcp_client_posix.c:159]     socket error: connection refused
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CE1118 01:03:36.291572222    9259 tcp_client_posix.c:159]     socket error: connection refused
E1118 01:03:36.298550187    9259 tcp_client_posix.c:159]     socket error: connection refused
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CE1118 01:03:38.477734658    9259 tcp_client_posix.c:159]     socket error: connection refused
^CE1118 01:03:38.484619738    9259 tcp_client_posix.c:159]     socket error: connection refused
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CE1118 01:03:42.247927821    9259 tcp_client_posix.c:159]     socket error: connection refused
E1118 01:03:42.254760397    9259 tcp_client_posix.c:159]     socket error: connection refused
Traceback (most recent call last):
  File "greeter_client.py", line 47, in <module>
    run()
  File "greeter_client.py", line 42, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/crust/implementations.py", line 73, in __call__
    protocol_options, metadata, request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/crust/_control.py", line 422, in next
    self._condition.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CE1118 01:03:49.627032547    9259 tcp_client_posix.c:159]     socket error: connection refused
E1118 01:03:49.633911131    9259 tcp_client_posix.c:159]     socket error: connection refused

The client just won't shut down. I have to kill the process.

**Comment by glennmatthews** [comment]
Is this the same issue as #4148?

**Comment by soltanmm** [comment]
I'm pretty sure it is. Closing as a duplicate.
