### ISSUE TITLE
[NodeJS] Examples failing while using NPM "grpc" (details inside)

### ISSUE THREAD

**Issue by BrandKNY** [grpc/grpc#4152]
Have successfully got Greeter Client/Server working when using the cloned repository which uses
   `var grpc = require('../../');`
to reference the GRPC modules. However, in all scenarios where I have built/compiled from source and successfully run `npm install grpc` and then updated the Greeter example to instead import the module using 
    `var grpc = require('grpc');`
running the examples fails giving the following error on my system:
    `/usr/bin/node: symbol lookup error: /usr/bin/node: symbol lookup error: /home/brandon/WebstormProjects/grpc/examples/node/node_modules/grpc/build/Release/grpc.node: undefined symbol: grpc_insecure_channel_create`

This error thrown when running the following with node:
* [inside greeter_server.js:51] `var server = new grpc.Server();  `
* [inside greeter_client.js:40] `var client = new hello_proto.Greeter('localhost:50051', grpc.Credentials.createInsecure());`  

--------------------------------------------------------------------------------------------
[Additional Info]
* Ubuntu 14.04.2 LTS (trusty)
* NodeJS: v4.0.0
* NPM: 2.14.2
* GRPC: 0_11_1 (git branch)

--------------------------------------------------------------------------------------------
[Build Process]
 1. `git clone https://github.com/grpc/grpc.git`
 2. `cd grpc/`
 3. `git checkout release-0_11_1`
 4. `git submodule update --init`
 5. `make -j 7`
 6. `sudo checkinstall`
 7. (from the grpc/examples/node/ dir) `npm install` (succeeds)

**Comment by murgatroid99** [comment]
I think you missed a `sudo makeinstall` step in your build process.

**Comment by BrandKNY** [comment]
`sudo checkinstall` is the equivalent to `sudo make install` but helps keep things much more organized when it comes to removing packages. (see: https://help.ubuntu.com/community/CheckInstall for more info)

**Comment by murgatroid99** [comment]
The error you mention seems to indicate that you are linking against a slightly older version of the gRPC C core. To be clear, are you running this in the examples directory in the release-0_11_1 tag? I did that, and everything seems to work fine.

**Comment by BrandKNY** [comment]
Yes, I am running within the examples directory after checking out to "release-0_11_1". I check that out before even running the submodule update --init and running Make/Checkinstall. After building, i cd into the node examples directory and `npm install grpc`, then update the code in the example client and server so that it requires grpc using the node_modules/grpc NPM module rather than the source which it defaults to by using `require('../../')`

**Comment by murgatroid99** [comment]
> then update the code in the example client and server so that it requires grpc using the node_modules/grpc NPM module rather than the source which it defaults to by using `require('../../')`

This part is confusing me a little. In the examples directory in tag release-0_11_1, [greeter_client.js](https://github.com/grpc/grpc/blob/release-0_11_1/examples/node/greeter_client.js) and [greeter_server.js](https://github.com/grpc/grpc/blob/release-0_11_1/examples/node/greeter_server.js) *already* import grpc with `require('grpc')`. You should need to change anything there.

**Comment by BrandKNY** [comment]
So I don't currently have access to the machine I was initially having this issue with. No matter, I just attempted to redo the entire process from scratch on my home computer using the same versions of everything right down to the Ubuntu Linux version. During the `sudo make install` process (using checkinstall again) I am now failing with this error:

```
========================= Installation results ===========================
[INSTALL] Installing public C headers
[MAKE]    Generating cache.mk
[STRIP]   Stripping libgpr.a
[STRIP]   Stripping libgrpc.a
[STRIP]   Stripping libgrpc_unsecure.a
[INSTALL] Installing C pkg-config files
[INSTALL] Installing libgpr.a
[INSTALL] Installing libgrpc.a
[INSTALL] Installing libgrpc_unsecure.a
[STRIP]   Stripping libgpr.so
[STRIP]   Stripping libgrpc.so
[STRIP]   Stripping libgrpc_unsecure.so
[INSTALL] Installing libgpr.so.0.11.0.0
[INSTALL] Installing libgrpc.so.0.11.0.0
[INSTALL] Installing libgrpc_unsecure.so.0.11.0.0
[INSTALL] Installing public C++ headers
[AUTOGEN] Preparing protobuf
configure.ac:87: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
make: *** [third_party/protobuf/configure] Error 1

****  Installation failed. Aborting package creation.

Restoring overwritten files from backup...OK

Cleaning up...OK

Bye.

```

Note: I have not installed protobuf explicitly on this machine. If necessary I'd prefer to follow steps you might suggest that would allow me to have a close to a copy of your process as possible - any recommendations?

**Comment by murgatroid99** [comment]
I don't have protobuf installed either. I have never seen that error before. It looks like you built only the C code, and then tried to install both the C code and the C++ code, which triggered building the C++ code, which in turn triggered building protobuf, which failed for some reason.

I suggest building and installing only the C code (which is all you need anyway for the Node library) by running `make static_c shared_c` and `sudo checkinstall make install_c`.

**Comment by BrandKNY** [comment]
Got it working man - thanks for the help. Just to be clear I went back and essentially started from scratch because my first attempt using your recommendation failed with different errors. My replicated steps that worked in order (in case someone else stumbles on this issue):

```
sudo apt-get install libtool automake autoconf checkinstall
git clone --recursive https://github.com/grpc/grpc.git
cd grpc/
git checkout release-0_11_1
git submodule update --init
make static_c shared_c
sudo checkinstall
cd examples/node/
npm install
```
(that git submodule update --init was not needed I'm sure since I did a recursive clone initially but I'm keeping it in because I ran it)

Then ran`node greeter_server.js` in one terminal and `greeter_client.js` in another and everything was peachy.

You can mark this as closed now as you wish. Thanks again.

**Comment by murgatroid99** [comment]
As a note, for you or for posterity: `make` instructions should be used with the corresponding ``make install` instructions. If you just want to install the C code (which is used for other languages like Python, Ruby, etc.), then just do

```
make static_c shared_c
sudo make install_c # or sudo checkinstall make install_c
```

But if you also want the C++ code, then do

```
make
sudo make install # or sudo checkinstall
```
