### ISSUE TITLE
Temporary files left laying around

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#416]
In my working directory even (not /tmp)

	chttp2_simple_ssl_fullstack_test_6rk5iz
	chttp2_simple_ssl_fullstack_test_7JonIa
	chttp2_simple_ssl_fullstack_test_GqiLLb
	chttp2_simple_ssl_fullstack_test_KvvlAe
	chttp2_simple_ssl_fullstack_test_QCoNEd
	chttp2_simple_ssl_fullstack_test_REykLv
	chttp2_simple_ssl_fullstack_test_USw0U5
	chttp2_simple_ssl_fullstack_test_VGY4cJ
	chttp2_simple_ssl_fullstack_test_as8Ais
	chttp2_simple_ssl_fullstack_test_d5ZddE
	chttp2_simple_ssl_fullstack_test_pgZyK2
	chttp2_simple_ssl_fullstack_test_vL1mNf

**Comment by nicolasnoble** [comment]
Ping.
