### ISSUE TITLE
Locked files on mac worker.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4160]
Locked files plugin sees some files on mac worker as locked.

```
Searching for locked files in workspace.
$ lsof +D /jenkins/workspace/gRPC_pull_requests/config/opt/language/c/platform/macos
COMMAND    PID         USER   FD   TYPE DEVICE SIZE/OFF      NODE NAME
mdworker 25228 jenkinsnode2    4r   REG    1,2   104007 591883905 /jenkins/workspace/gRPC_pull_requests/config/opt/language/c/platform/macos/templates/tools/doxygen/Doxyfile.include
mdworker 25228 jenkinsnode2    5r   REG    1,2   104007 591883905 /jenkins/workspace/gRPC_pull_requests/config/opt/language/c/platform/macos/templates/tools/doxygen/Doxyfile.include
mdworker 25228 jenkinsnode2    7r   REG    1,2   104007 591883905 /jenkins/workspace/gRPC_pull_requests/config/opt/language/c/platform/macos/templates/tools/doxygen/Doxyfile.include
ERROR: Build was failed as the workspace contained files that were locked by another process. See Locked files report for more information.
```

https://grpc-testing.appspot.com/job/gRPC_pull_requests/4259/config=opt,language=c,platform=macos/locked-files-report/

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/4255/config=dbg,language=php,platform=macos/locked-files-report/

**Comment by adelez** [comment]
Marked it P0 and Buildpony as it break builds on macos.

**Comment by jtattermusch** [comment]
The common denominator seems to be the "mdworker" process - which is some disk indexing tool called Spotlight.

I disabled spotlight on grpc-mac-node2 by using instructions from:
http://osxdaily.com/2011/12/10/disable-or-enable-spotlight-in-mac-os-x-lion/

```
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
```

Was this seen on node1 as well?

**Comment by jtattermusch** [comment]
Yes it was seen on node1: https://grpc-testing.appspot.com/job/gRPC_master/13085/config=dbg,language=c,platform=macos/console

Spotlight has been disabled on grpc-mac-node1 as well.

**Comment by jtattermusch** [comment]
This should be resolved but the issue open for a while to see if that's the case.
