### ISSUE TITLE
On receiving an HTTP response, the status code should be internal.

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#4168]
When we receive a 404 or something similar in HTTP response, we should consistently fail the rpc with INTERNAL error. Currently sometimes it returns as CANCELLED and sometimes INTERNAL.

**Comment by y-zeng** [comment]
Looks like the current behavior is returning the status code as UNAVAILABLE. #6773 provides a status error_message when a call fails for receiving an unexpected response.

**Comment by y-zeng** [comment]
Solved in #6773

**Comment by ctiller** [comment]
See my comment on #6773. I don't think this is fixed.

**Comment by y-zeng** [comment]
#6893 resolved the remaining part.
