### ISSUE TITLE
Implement compression support in C#

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4170]
This is an issue to track progress on the compression support in C#.

**Comment by dgquintas** [comment]
Requirements list: https://github.com/grpc/grpc/issues/4075#issuecomment-213644191

**Comment by murgatroid99** [comment]
Do we have this yet?

**Comment by dgquintas** [comment]
I believe so. @jtattermusch ?

**Comment by jtattermusch** [comment]
Only partially. It can be done in C#, but it's definitely not user friendly (lacks appropriate APIs).

**Comment by jtattermusch** [comment]
No imminent plans to work on this.
