### ISSUE TITLE
"h2_proxy_registered_call_nosec_test" and "h2_proxy_simple_request_nosec_test" (c, dbg, linux)

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#4172]
https://grpc-testing.appspot.com/job/gRPC_master/13092/config=dbg,language=c,platform=linux/consoleFull

```
D1119 23:45:16.476175014   31273 test_config.c:155]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
I1119 23:45:16.476305492   31273 registered_call.c:57]       test_invoke_simple_request/chttp2/fullstack+proxy
E1119 23:45:16.476910023   31273 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1119 23:45:16.478241186   31273 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1119 23:45:16.479031110   31273 proxy.c:104]                PROXY ADDR:localhost:1038 BACKEND:localhost:1113
D1119 23:45:16.489182422   31294 chttp2_transport.c:666]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1119 23:45:16.489546879   31273 registered_call.c:57]       test_invoke_10_simple_requests/chttp2/fullstack+proxy
E1119 23:45:16.489815866   31273 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1119 23:45:16.493002089   31273 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1119 23:45:16.493897025   31273 proxy.c:104]                PROXY ADDR:localhost:1117 BACKEND:localhost:1212
I1119 23:45:16.499156957   31273 registered_call.c:224]      Passed simple request 0
I1119 23:45:16.499525876   31273 registered_call.c:224]      Passed simple request 1
I1119 23:45:16.499895572   31273 registered_call.c:224]      Passed simple request 2
I1119 23:45:16.500230919   31273 registered_call.c:224]      Passed simple request 3
I1119 23:45:16.501012807   31273 registered_call.c:224]      Passed simple request 4
I1119 23:45:16.501374472   31273 registered_call.c:224]      Passed simple request 5
I1119 23:45:16.501736857   31273 registered_call.c:224]      Passed simple request 6
I1119 23:45:16.502103798   31273 registered_call.c:224]      Passed simple request 7
I1119 23:45:16.502458913   31273 registered_call.c:224]      Passed simple request 8
I1119 23:45:16.502808201   31273 registered_call.c:224]      Passed simple request 9
D1119 23:45:16.503150493   31360 chttp2_transport.c:666]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
E1119 23:45:36.489646021   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1113': timeout occurred
E1119 23:45:36.503970769   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:45:56.505179881   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:46:16.506405637   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:46:36.508343045   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:46:56.509726023   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:47:17.658716615   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:47:51.946635087   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:48:42.065192173   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred
E1119 23:50:07.508084508   31360 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1212': timeout occurred

TIMEOUT: bins/dbg/h2_proxy_registered_call_nosec_test
D1119 23:45:16.683609877   32070 test_config.c:155]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
I1119 23:45:16.683710846   32070 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1119 23:45:16.684313142   32070 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1119 23:45:16.685355435   32104 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1119 23:45:16.686074396   32070 proxy.c:104]                PROXY ADDR:localhost:1164 BACKEND:localhost:1039
D1119 23:45:16.689650826   32070 simple_request.c:127]       client_peer_before_call=localhost:1164
D1119 23:45:16.691041381   32070 simple_request.c:170]       server_peer=ipv6:[::1]:34602
D1119 23:45:16.691057505   32070 simple_request.c:174]       client_peer=ipv6:[::1]:1164
D1119 23:45:16.691586786   32117 chttp2_transport.c:666]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
E1119 23:45:36.692541573   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:45:56.694608658   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:46:16.696638643   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:46:36.698152501   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:46:56.699379249   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:47:19.715181878   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:47:52.601909144   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:48:51.440608158   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
E1119 23:50:13.448042445   32117 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1039': timeout occurred
```

**Comment by vjpai** [comment]
Pinging. Issue also seen under opt
https://grpc-testing.appspot.com/job/gRPC_master/13402/config=opt,language=c,platform=linux/testReport/(root)/tests/bins_opt_h2_proxy_simple_request_nosec_test/

Error Message

Timeout
Standard Output

invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.276532265    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.277382145    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.278026614    6274 proxy.c:104]                PROXY ADDR:localhost:1078 BACKEND:localhost:1071
D1202 20:45:15.279861752    6274 simple_request.c:127]       client_peer_before_call=localhost:1078
D1202 20:45:15.280674366    6274 simple_request.c:170]       server_peer=ipv6:[::1]:45481
D1202 20:45:15.280693274    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1078
D1202 20:45:15.280923868    6381 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:45:15.281175084    6274 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.281395176    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.282308748    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.282928637    6274 proxy.c:104]                PROXY ADDR:localhost:1101 BACKEND:localhost:1080
D1202 20:45:15.284301654    6274 simple_request.c:127]       client_peer_before_call=localhost:1101
D1202 20:45:15.285082959    6274 simple_request.c:170]       server_peer=ipv6:[::1]:43642
D1202 20:45:15.285100398    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1101
D1202 20:45:15.285292477    6416 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:45:15.285476176    6274 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.285701304    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.286830188    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.287563029    6274 proxy.c:104]                PROXY ADDR:localhost:1147 BACKEND:localhost:1152
D1202 20:45:15.289246666    6274 simple_request.c:127]       client_peer_before_call=localhost:1147
D1202 20:45:15.291701444    6274 simple_request.c:170]       server_peer=ipv6:[::1]:49894
D1202 20:45:15.291720492    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1147
D1202 20:45:15.292028845    6451 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:45:15.292206475    6274 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.292433272    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.293251346    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.294134073    6274 proxy.c:104]                PROXY ADDR:localhost:1191 BACKEND:localhost:1181
D1202 20:45:15.295703046    6274 simple_request.c:127]       client_peer_before_call=localhost:1191
D1202 20:45:15.299073912    6274 simple_request.c:170]       server_peer=ipv6:[::1]:46079
D1202 20:45:15.299095660    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1191
D1202 20:45:15.299940324    6494 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:45:15.300139756    6274 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.300583845    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.302296644    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.303138407    6274 proxy.c:104]                PROXY ADDR:localhost:1068 BACKEND:localhost:1165
D1202 20:45:15.304677095    6274 simple_request.c:127]       client_peer_before_call=localhost:1068
D1202 20:45:15.305500888    6274 simple_request.c:170]       server_peer=ipv6:[::1]:40704
D1202 20:45:15.305516959    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1068
D1202 20:45:15.305732476    6530 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:45:15.305900323    6274 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.306445111    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.307882228    6559 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.308874671    6274 proxy.c:104]                PROXY ADDR:localhost:1122 BACKEND:localhost:1123
D1202 20:45:15.310630188    6274 simple_request.c:127]       client_peer_before_call=localhost:1122
D1202 20:45:15.311452487    6274 simple_request.c:170]       server_peer=ipv6:[::1]:47815
D1202 20:45:15.311468692    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1122
D1202 20:45:15.311663154    6574 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:45:15.311885676    6274 simple_request.c:57]        test_invoke_simple_request/chttp2/fullstack+proxy
E1202 20:45:15.312097550    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E1202 20:45:15.312890192    6274 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D1202 20:45:15.313452886    6274 proxy.c:104]                PROXY ADDR:localhost:1142 BACKEND:localhost:1224
D1202 20:45:15.315118729    6274 simple_request.c:127]       client_peer_before_call=localhost:1142
D1202 20:45:15.316000411    6274 simple_request.c:170]       server_peer=ipv6:[::1]:55825
D1202 20:45:15.316017858    6274 simple_request.c:174]       client_peer=ipv6:[::1]:1142
D1202 20:45:15.316332844    6593 chttp2_transport.c:667]     got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
E1202 20:45:35.277306426    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1125': timeout occurred
E1202 20:45:35.281457968    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1071': timeout occurred
E1202 20:45:35.285583236    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1080': timeout occurred
E1202 20:45:35.292708004    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1152': timeout occurred
E1202 20:45:35.300820177    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1181': timeout occurred
E1202 20:45:35.306010225    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1165': timeout occurred
E1202 20:45:35.312119545    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1123': timeout occurred
E1202 20:45:35.317315473    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:45:55.318365652    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:46:15.319949587    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:46:35.321600007    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:46:55.323533926    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:47:18.272718123    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:47:52.582689561    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:48:46.627014618    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
E1202 20:50:10.462624174    6593 tcp_client_posix.c:189]     failed to connect to 'ipv6:[::1]:1224': timeout occurred
