### ISSUE TITLE
gRPC stress:  interop_server crashes when repeatedly called with large_unary RPC calls

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#4180]
### Steps to reproduce

1) Go to grpc root directory

2) Compile stress_test and interop_server binaries (the issue repros even without CONFIG=dbg)
```
    (grpc_root)$ make CONFIG=dbg stress_test interop_server -j
```

3) Launch interop server on port 8080 (or any other port)
```
    (grpc_root)$ bins/dbg/interop_server --port=8080
```

4) Launch stress_test client. The following command launches stress test client that sends roughly equal number of 'large_unary' and 'empty_unary' requests to the server listening on port 8080. (--metrics_port=8081 means that the client exposes its qps metrics on port 8081).  num_stubs_per_channel=20 means that the stress test client makes 20 calls in parallel on the same channel.
```
    (grpc_root)$  bins/opt/stress_test --test_cases=large_unary:50,empty_unary:50 --server_addresses=localhost:8080 --num_stubs_per_channel=20 --metrics_port=8081
```

After a few seconds (unfortunately this is not deterministic. It can take anywhere from 10 seconds to a few minutes), the server will crash with the following error:

```
  I1119 14:54:09.619659573  142013 server.cc:258]              Server listening on 0.0.0.0:8080
  E1119 14:55:13.831885210  142020 chttp2_transport.c:523]     server stream 170083 still included in list 8
```

##### Here is the call stack of the failing thread

``` c++
(gdb) bt
#0  0x00007ffff66a4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff66a80d8 in __GI_abort () at abort.c:89
#2  0x000000000051541e in destroy_stream (exec_ctx=0x7ffff4b63bf0, gt=0x7fffe4000fe0, gs=0x7fffb810e938)
    at src/core/transport/chttp2_transport.c:525
#3  0x00000000004a0394 in grpc_call_stack_destroy (exec_ctx=exec_ctx@entry=0x7ffff4b63bf0, stack=stack@entry=0x7fffb810e540)
    at src/core/channel/channel_stack.c:222
#4  0x000000000049c742 in destroy_call (exec_ctx=0x7ffff4b63bf0, call=0x7fffb810e070, success=<optimized out>)
    at src/core/surface/call.c:372
#5  0x00000000004a605a in grpc_exec_ctx_flush (exec_ctx=exec_ctx@entry=0x7ffff4b63bf0) at src/core/iomgr/exec_ctx.c:51
#6  0x00000000004a6075 in grpc_exec_ctx_finish (exec_ctx=exec_ctx@entry=0x7ffff4b63bf0) at src/core/iomgr/exec_ctx.c:61
#7  0x000000000049e215 in grpc_call_destroy (c=0x7fffb810e070) at src/core/surface/call.c:659
#8  0x000000000049a177 in grpc::ServerContext::~ServerContext (this=0x7ffff4b63cd0, __in_chrg=<optimized out>)
    at src/cpp/server/server_context.cc:147
#9  0x0000000000496b24 in ~CallData (this=0x7ffff4b63ca0, __in_chrg=<optimized out>) at src/cpp/server/server.cc:215
#10 grpc::Server::RunRpc (this=0x933cb0) at src/cpp/server/server.cc:562
#11 0x0000000000493122 in operator() (this=0x7ffff4b63e20) at /usr/include/c++/4.8/functional:2471
#12 grpc::DynamicThreadPool::ThreadFunc (this=0x93aa10) at src/cpp/server/dynamic_thread_pool.cc:81
#13 0x0000000000493313 in grpc::DynamicThreadPool::DynamicThread::ThreadFunc (this=0x932810)
    at src/cpp/server/dynamic_thread_pool.cc:50
#14 0x00007ffff6cfaa40 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:84
#15 0x00007ffff779a182 in start_thread (arg=0x7ffff4b64700) at pthread_create.c:312
#16 0x00007ffff676847d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```c++
(gdb) info threads
  Id   Target Id         Frame 
  13   Thread 0x7ffff6367700 (LWP 142017) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7ffff5b66700 (LWP 142018) "interop_server" 0x00000000004768a3 in SetPayload (type=<optimized out>, 
    size=<optimized out>, payload=0x7fffe80b2e00) at test/cpp/interop/server.cc:94
  11   Thread 0x7ffff5365700 (LWP 142019) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 10   Thread 0x7ffff4b64700 (LWP 142020) "interop_server" 0x00007ffff66a4cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
  9    Thread 0x7ffff4363700 (LWP 142021) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7ffff3b62700 (LWP 142022) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7ffff3361700 (LWP 142023) "interop_server" 0x00007ffff675b12d in poll ()
    at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7ffff2b60700 (LWP 142024) "interop_server" 0x00007ffff675b12d in poll ()
    at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7ffff235f700 (LWP 142025) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7ffff1b5e700 (LWP 142026) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7ffff135d700 (LWP 142027) "interop_server" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff0b5c700 (LWP 142028) "interop_server" __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:79
  1    Thread 0x7ffff7fd5780 (LWP 142013) "interop_server" 0x00007ffff672ef3d in nanosleep ()
    at ../sysdeps/unix/syscall-template.S:81
```

**Comment by beibeiyhj** [comment]
I have the same question for some days.

#0  0x00007f1bbef6cf79 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f1bbef6cf79 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f1bbef70388 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f1bc03cbe1e in ?? () from /usr/local/lib/libgrpc.so.0
#3  0x00007f1bc03a5ae4 in grpc_call_stack_destroy () from /usr/local/lib/libgrpc.so.0
#4  0x00007f1bc03b9012 in ?? () from /usr/local/lib/libgrpc.so.0
#5  0x00007f1bc03afc5a in grpc_exec_ctx_flush () from /usr/local/lib/libgrpc.so.0
#6  0x00007f1bc03bd850 in grpc_completion_queue_next () from /usr/local/lib/libgrpc.so.0
#7  0x00007f1bc07e9ae8 in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) () from /usr/local/lib/libgrpc++_unsecure.so.0
#8  0x000000000042cfcb in grpc::CompletionQueue::Next (this=0x10becf0, tag=0x7f1bbd138de0, ok=0x7f1bbd138dde) at /usr/local/include/grpc++/completion_queue.h:127
#9  0x000000000042ccad in server_impl::ThreadFunc (this=0x10beb78, rank=0) at /data/hjyang/msp40/source/tools/pmac/pmacgs/grpc_server_impl.cpp:223
#10 0x000000000043ef74 in std::_Mem_fn<void (server_impl::*)(int)>::operator()<int, void>(server_impl*, int&&) const (this=0x1f6ac20, __object=0x10beb78)
    at /usr/include/c++/4.8/functional:601
#11 0x000000000043ee4d in std::_Bind_simple<std::_Mem_fn<void (server_impl::*)(int)> (server_impl*, int)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x1f6ac10)
    at /usr/include/c++/4.8/functional:1732
#12 0x000000000043ebdf in std::_Bind_simple<std::_Mem_fn<void (server_impl::*)(int)> (server_impl*, int)>::operator()() (this=0x1f6ac10) at /usr/include/c++/4.8/functional:1720
#13 0x000000000043dd9c in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (server_impl::*)(int)> (server_impl*, int)> >::_M_run() (this=0x1f6abf8) at /usr/include/c++/4.8/thread:115
#14 0x00007f1bbf5cb490 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007f1bbfaf6182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#16 0x00007f1bbf03130d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by beibeiyhj** [comment]
This issue has fixed now.

**Comment by sreecha** [comment]
Yes, this does seem to be fixed now.
