### ISSUE TITLE
tests timedout with messages like "failed to connect to 'ipv6:[::1]:1186': timeout occurred"

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#4185]
including #4182 #4183 #4184
dbg:
https://grpc-testing.appspot.com/job/gRPC_master/config=dbg,language=c,platform=linux/13111/consoleFull
opt:
https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=c,platform=linux/13111/

**Comment by a11r** [comment]
Another instance:
All test failures for C (dbg, opt etc) in this run were instances of this : https://grpc-testing.appspot.com/job/gRPC_master/13538/
 https://grpc-testing.appspot.com/job/gRPC_master/13538/config=dbg,language=c,platform=linux/

**Comment by adelez** [comment]
Same as #4257 and #4258
