### ISSUE TITLE
Source of payload size for SimpleResponse in unclear.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4191]
Currently, there it two possible sources for SimpleResponse's payload size:

-- SimpleRequest has field response_size, which should determine the payload size for corresponding SimpleResponse

-- at the same time, ServerConfig.payload_config (currently unused) field also could define what the size of response should be. 

We need to decide which info is authoritative and document accordingly. Changing the protos also might be an option.

**Comment by murgatroid99** [comment]
Also, the comments in services.proto say "The server returns the client payload as-is", which is different from either of those.

**Comment by vjpai** [comment]
This is now set in all languages. Authoritative information comes from ServerConfig.payload_config in the case of generic but from SimpleRequest::response_size otherwise
