### ISSUE TITLE
C++ Poisson might not be a poisson (under load)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4194]
In c++, generating calls with poisson load works like this:

```
while(true) {
  waitForExpDistributedTime()  
  unaryCall()
}
```

Technically, this won't result it poisson distribution if unaryCall latencies will start representing significant portion of the time compared to the amount of time spent waiting (if we start simulating "heavy load").

A more rigorous approach might be to:
```
lastEvent = get_now()
while(true) {
  unaryCall()
  deadline = generateNextExpDistributedTime(lastEvent);
  waitUntil(deadline);  
  lastEvent = deadline;
}
```

Alternatively, `deadline = generateNextExpDistributedTime(get_now());` is also an option.

But actually, what we are doing now might be what's intended, just wanted to point this out.

**Comment by vjpai** [comment]
This isn't how the timers work; we always wait for the next time but the next time is calculated based on the last value of next time plus the exp offset, not after the unary call.

**Comment by jtattermusch** [comment]
Thanks for the explanation!
