### ISSUE TITLE
Adopt changes from new version of protobuf C#.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4213]
protobuf C# recently introduced some changes that gRPC should adopt once protobuf C# gets released and we switch to it.
-- umbrella class has been renamed
-- fully qualified name of file descriptor property has changed
-- base namespace cmdline option argument has been introduced.
-- comments from .proto files are now copied to the generated code as pre-formatted comments.

**Comment by dejanbokan** [comment]
Is there any information when is this issue planned to be resolved?

**Comment by jtattermusch** [comment]
I plan to address this soon - probably next week.
Nevertheless, it will take a while before this change is released (as gRPC 0.12 got released yesterday)

**Comment by jtattermusch** [comment]
FTR, this is the protobuf PR that introduced the breaking change.

**Comment by jtattermusch** [comment]
#4793 and #4794 have been created for some followup work that would be nice to have but is not urgent.
