### ISSUE TITLE
run_tests/build_ruby.sh failed on gcov config

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4239]
While testing unrelated PR https://github.com/grpc/grpc/pull/4235, with `*** ../../../../ext/grpc/extconf.rb failed ***`; see [the console output](https://grpc-testing.appspot.com/job/gRPC_pull_requests/4346/config=gcov,language=ruby,platform=linux/console).

**Comment by murgatroid99** [comment]
This is most likely because it was run before #4229 was merged.

**Comment by murgatroid99** [comment]
Or because #4229 is only on master.

**Comment by murgatroid99** [comment]
This does not seem to have happened recently.
