### ISSUE TITLE
How to set thread local variables in c++?

### ISSUE THREAD

**Issue by caron-lee** [grpc/grpc#4240]
My Service Handler is not thread safe, So I need a Service Handler every processing thread. 
But I didn't find the way.

**Comment by caron-lee** [comment]
Does anybody use thread local variables?

**Comment by caron-lee** [comment]
Help!

**Comment by yang-g** [comment]
Could you elaborate what you want? I am not quite sure your question is about C++ or grpc, but I might not have understood it.
