### ISSUE TITLE
Auth basics doc duplication

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4242]
Currently two docs:

https://github.com/grpc/grpc.github.io/blob/master/docs/guides/auth.md
https://github.com/grpc/grpc/blob/master/doc/grpc-auth-support.md

We previously agreed that such redundancy is no good. Let's decide which one we should nuke (I vote for the one in gRPC repo).

@hsaliak @jboeuf @LisaFC

**Comment by jtattermusch** [comment]
On the other hand, it looks like https://github.com/grpc/grpc/blob/master/doc/grpc-auth-support.md  is more up-to-date.

**Comment by LisaFC** [comment]
I'd still go for updating the one in the actual doc site and nuking the one in the repo, as the doc site one is the one people are going to find from tutorials, etc.
