### ISSUE TITLE
Update auth.md

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4243]
Before releasing 0.12, auth doc needs to be updated to reflect changes in the auth API.

Document to be updated is either https://github.com/grpc/grpc/blob/master/doc/grpc-auth-support.md or https://github.com/grpc/grpc.github.io/blob/master/docs/guides/auth.md, depending on the outcome of #4242.

- [x] C# @jtattermusch
- [x] Node @murgatroid99 
- [x] Python @soltanmm
- [x] PHP @stanley-cheung 
- [x] Ruby @tbetbetbe / @murgatroid99
- [ ] iOS @jcanizales  (no changes expected but verifying everything's up to date would be good). 
- [x]  C++  @jboeuf 

After all languages have updated, let's have @jboeuf give the document a final pass for sanity and then we close this issue.

**Comment by jtattermusch** [comment]
All the changes should go to https://github.com/grpc/grpc.github.io/blob/master/docs/guides/auth.md as the other doc was removed in #4244

**Comment by jtattermusch** [comment]
Rather than in master, the docs need to be updated in the csharp_beta_update branch, from where it will get merged into master once the release is out.
https://github.com/jtattermusch/grpc.github.io/blob/csharp_beta_update/docs/guides/auth.md

@LisaFC to confirm.

**Comment by jboeuf** [comment]
csharp_beta_update looks very... C# specific... Should we cut another
branch?

**Comment by LisaFC** [comment]
It is indeed very C#-y. I'd make another branch for this update (I think we previously had a general beta_docs_update branch or similar but that got merged with Master and deleted aaaaaages ago).

**Comment by jtattermusch** [comment]
please ignore that comment, I just got confused and wrote a nonsense. I
deleted that comment from the issue.

**Comment by jtattermusch** [comment]
@LisaFC  feel free to create a new branch ("release_0_12_update"?) if you feel that's appropriate.

**Comment by jcanizales** [comment]
What section of the webpage corresponds to this `.md`? Objective-C should be mentioned somehow, at least to point to the OAuth2 tutorial.

**Comment by jtattermusch** [comment]
http://www.grpc.io/docs/guides/auth.html
Let's add a section on ObjectiveC, it seems it's missing.

**Comment by jboeuf** [comment]
sgtm.

**Comment by nathanielmanistaatgoogle** [comment]
The Python side of this is currently being led by @soltanmm in https://github.com/grpc/grpc.github.io/pull/135; we'll remove the Python label from this issue when that change gets integrated.

**Comment by jboeuf** [comment]
@jcanizales Can you add a section for iOS to https://github.com/grpc/grpc.github.io/blob/master/docs/guides/auth.md. Pointing on existing doc is fine with me for now. Thanks!

After this is done, please reassign to me and I'll reorganize the sections language per language (it's a bit all over the map for now) and will ask @LisaFC for a final review.

**Comment by LisaFC** [comment]
Realized when going through the doc requirements for our next release that we never actually did this reorg (and it's now got even more examples in it). @jboeuf, I'll add you to the relevant issue....

**Comment by jboeuf** [comment]
@LisaFC. Sounds good. thanks!

**Comment by hsaliak** [comment]
We have an entire tutorial on ObjC + OAuth 
http://www.grpc.io/docs/tutorials/auth/oauth2-objective-c.html 
we will reference that tutorial from auth.md  -- that work is tracked in https://github.com/grpc/grpc.github.io/issues/181 

Closing this issue.
