### ISSUE TITLE
grpc 0.11.1 gem release not published to rubygems

### ISSUE THREAD

**Issue by robert-w-gries** [grpc/grpc#4245]
I was hitting a build error while installing grpc gem version `0.11.0`.  Building from gemspec and installing gem version `0.11.1` fixed the build error for me.

However, version `0.11.1` is not published to [rubygems.org](https://rubygems.org/gems/grpc), which causes issues when trying to install grpc via bundler.

**Comment by murgatroid99** [comment]
Version 0.12.0 has now been published to rubygems. It has all of the changes in 0.11.1, plus several others (see [release notes](https://github.com/grpc/grpc/releases/tag/release-0_12_0) for details).

**Comment by murgatroid99** [comment]
Version 0.13.0 has also been published now. At this point, I think this issue is obsolete. Feel free to reopen if it's still a problem.
