### ISSUE TITLE
protobuf 2.6?

### ISSUE THREAD

**Issue by dongz9** [grpc/grpc#4246]
Does grpc work with protobuf 2.6?

**Comment by soltanmm** [comment]
Which part of gRPC? For which language?

The mechanism of gRPC is agnostic to whatever serialization/deserialization methodology is chosen; the protoc plugins and runtime support depend on language support at the protoc version (so e.g. [C# has limitations](https://github.com/google/protobuf/tree/master/csharp#status-alpha---ready-for-early-adopters)).

**Comment by nicolasnoble** [comment]
gRPC mainly works with protobuf 3. If you have more details to your question by answering @soltanmm's first, we'll re-open that issue appropriately.

**Comment by jupp0r** [comment]
@nicolasnoble We are targeting C++. Is it possible to use grpc both for serialization and for generating code using protoc with protobuf 2.4?
