### ISSUE TITLE
h2_oauth2_simple_delayed_request_test.exe fails under Windows

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#4253]
https://grpc-testing.appspot.com/job/gRPC_master/13402/config=opt,language=c,platform=windows/testReport/(root)/tests/vsprojects_Release_h2_oauth2_simple_delayed_request_test_exe/

Console output is not helpful - looks like it actually passed? May be a false failure?

**Comment by adelez** [comment]
Per discussion with @nicolasnoble, this may be caused by the same timeout problem that we see in this type of tests on Linux. Will be investigated together with the timeout failures.
