### ISSUE TITLE
lb_policies_test.exe fails under Windows, dbg

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#4255]
https://grpc-testing.appspot.com/job/gRPC_master/13402/config=dbg,language=c,platform=windows/testReport/(root)/tests/vsprojects_Debug_lb_policies_test_exe/

E1202 20:51:08.687000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:08.687000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:08.690000000 21248 lb_policies_test.c:326] s_idx=-1
E1202 20:51:09.688000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:09.689000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:09.690000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:09.690000000 21248 lb_policies_test.c:326] s_idx=-1
E1202 20:51:09.693000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:10.687000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:10.691000000 21248 lb_policies_test.c:326] s_idx=-1
E1202 20:51:10.691000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:10.692000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:10.694000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:11.689000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:11.692000000 21248 lb_policies_test.c:326] s_idx=-1
E1202 20:51:11.692000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:11.695000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:11.695000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

I1202 20:51:11.738000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 0
D1202 20:51:11.738000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2572
I1202 20:51:11.751000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 1
D1202 20:51:11.751000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2573
I1202 20:51:11.762000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 2
D1202 20:51:11.762000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2574
I1202 20:51:11.773000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 3
D1202 20:51:11.773000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2575
I1202 20:51:11.783000000 21248 lb_policies_test.c:477] Testing 'test_kill_all_server_after_1st_resurrect_at_3rd' with servers=127.0.0.1:2572,127.0.0.1:2573,127.0.0.1:2574,127.0.0.1:2575 client=ipv4:127.0.0.1:2572,127.0.0.1:2573,127.0.0.1:2574,127.0.0.1:2575?lb_policy=round_robin
D1202 20:51:11.784000000 21248 lb_policies_test.c:310] EVENT: success:1, type:2, tag:1000 iter:0
D1202 20:51:11.784000000 21248 lb_policies_test.c:326] s_idx=0
D1202 20:51:11.785000000 21248 lb_policies_test.c:357] status=12; xyz
I1202 20:51:11.785000000 21248 lb_policies_test.c:135] KILLING SERVER 0
I1202 20:51:11.785000000 21248 lb_policies_test.c:135] KILLING SERVER 1
D1202 20:51:11.785000000 21248 chttp2_transport.c:667] got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:51:11.786000000 21248 lb_policies_test.c:135] KILLING SERVER 2
D1202 20:51:11.786000000 21248 chttp2_transport.c:667] got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
I1202 20:51:11.786000000 21248 lb_policies_test.c:135] KILLING SERVER 3
D1202 20:51:11.786000000 21248 chttp2_transport.c:667] got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
D1202 20:51:11.787000000 21248 lb_policies_test.c:310] EVENT: success:0, type:2, tag:1000 iter:1
D1202 20:51:11.788000000 21248 lb_policies_test.c:310] EVENT: success:0, type:2, tag:1001 iter:1
D1202 20:51:11.788000000 21248 lb_policies_test.c:310] EVENT: success:0, type:2, tag:1002 iter:1
D1202 20:51:11.789000000 21248 lb_policies_test.c:310] EVENT: success:0, type:2, tag:1003 iter:1
D1202 20:51:11.789000000 21248 chttp2_transport.c:667] got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
E1202 20:51:11.789000000 21248 tcp_windows.c:155] ReadFile overlapped error: An established connection was aborted by the software in your host machine.

D1202 20:51:11.789000000 21248 lb_policies_test.c:310] EVENT: success:1, type:2, tag:1 iter:1
D1202 20:51:11.789000000 21248 lb_policies_test.c:320] client timed out
E1202 20:51:12.694000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:12.787000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:12.787000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:12.788000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:12.788000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:12.791000000 21248 lb_policies_test.c:326] s_idx=-1
E1202 20:51:13.792000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:13.792000000 21248 lb_policies_test.c:326] s_idx=-1
I1202 20:51:13.792000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 0
D1202 20:51:13.792000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2572
I1202 20:51:13.801000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 1
D1202 20:51:13.801000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2573
I1202 20:51:13.809000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 2
D1202 20:51:13.809000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2574
I1202 20:51:13.819000000 21248 lb_policies_test.c:156] RAISE AGAIN SERVER 3
D1202 20:51:13.820000000 21248 lb_policies_test.c:159] revive: 127.0.0.1:2575
E1202 20:51:13.829000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

E1202 20:51:13.830000000 21248 tcp_client_windows.c:106] on_connect error: No connection could be made because the target machine actively refused it.

D1202 20:51:13.831000000 21248 lb_policies_test.c:310] EVENT: success:1, type:2, tag:1001 iter:3
D1202 20:51:13.831000000 21248 lb_policies_test.c:326] s_idx=1
D1202 20:51:13.831000000 21248 lb_policies_test.c:357] status=12; xyz
D1202 20:51:13.832000000 21248 lb_policies_test.c:310] EVENT: success:1, type:2, tag:1003 iter:4
D1202 20:51:13.832000000 21248 lb_policies_test.c:326] s_idx=3
D1202 20:51:13.832000000 21248 lb_policies_test.c:357] status=12; xyz
D1202 20:51:13.832000000 21248 lb_policies_test.c:310] EVENT: success:1, type:2, tag:1002 iter:5
D1202 20:51:13.832000000 21248 lb_policies_test.c:326] s_idx=2
D1202 20:51:13.832000000 21248 lb_policies_test.c:357] status=12; xyz
D1202 20:51:13.832000000 21248 lb_policies_test.c:310] EVENT: success:1, type:2, tag:1001 iter:6
D1202 20:51:13.832000000 21248 lb_policies_test.c:326] s_idx=1
D1202 20:51:13.832000000 21248 lb_policies_test.c:357] status=12; xyz
D1202 20:51:13.833000000 21248 lb_policies_

**Comment by ctiller** [comment]
This time on Mac:

https://grpc-testing.appspot.com/job/gRPC_master/13729/config=opt,language=c,platform=macos/testReport/(root)/tests/bins_opt_lb_policies_test/

**Comment by ctiller** [comment]
Not seen for some time: closing.
