### ISSUE TITLE
Is the Python surface API *really* stable?

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4273]
This came up when I saw #4241. #4228 technically is breaking the surface API, and, moreover, we're probably going to be changing our import packages by deprecating and removing the `beta` package and using some other package for the final GA implementations and interfaces (likely by just renaming the beta package, but, still - that's a breaking change). What are we really saying when we say our surface API is stable?

cc @jboeuf @nathanielmanistaatgoogle

**Comment by jcanizales** [comment]
CC @mugurm as he's assigned to that PR.

**Comment by ctiller** [comment]
Bumping to P1 since this will be impacting to dependent libraries.

**Comment by soltanmm** [comment]
Effectively a duplicate of #5095, which is actually actionable.
