### ISSUE TITLE
C++ : creating a method 'delete' on a grpc signature fails compilation.

### ISSUE THREAD

**Issue by senior7515** [grpc/grpc#4279]
The compiler should prevent it. Here is the protobuf to repro the bug

```
message DeleteRequest {
  repeated bytes keys = 1;
}

message StateError {
  bool wut = 1; // here until i can figure out how to have void rpc
}

service State {
  rpc del(DeleteRequest) returns (StateError);
}
```

if you change the state service to delete, you can't compile the code. 

```
rpc delete(....)....
```

**Comment by pherl** [comment]
Hmm, I believe the protoc itself won't generate anything for services, all of which are generated by the grpc plugin. I will defer to the grpc codegen owners to add an escape function for this case.

**Comment by yang-g** [comment]
delete is a C++ keyword. It is not a good idea to use it as a function name.
