### ISSUE TITLE
Example code does not work when no IPv6 address is available

### ISSUE THREAD

**Issue by newsoft** [grpc/grpc#4284]
I tried to run greeter_server / greeter_client example code on Ubuntu 15.10 x64 on GCE. It crashes:

    I1203 16:57:05.100617195   15582 socket_utils_common_posix.c:148] Disabling AF_INET6 sockets because ::1 is not available.

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff78d8e71 in grpc_tcp_server_add_port (s=0x62aec0, addr=0x7fffffffe190, addr_len=28) at src/core/iomgr/tcp_server_posix.c:467
    467         allocated_port = sp->port;
    (gdb) bt
    #0  0x00007ffff78d8e71 in grpc_tcp_server_add_port (s=0x62aec0, addr=0x7fffffffe190, addr_len=28) at src/core/iomgr/tcp_server_posix.c:467
    #1  0x00007ffff78e9ddd in grpc_server_add_insecure_http2_port (server=0x6329a0, addr=0x62b890 "0.0.0.0:50051") at src/core/surface/server_chttp2.c:110
    #2  0x00007ffff7bac20e in grpc::(anonymous namespace)::InsecureServerCredentialsImpl::AddPortToServer (this=0x6328c0, addr="0.0.0.0:50051", server=0x6329a0)
    at src/cpp/server/insecure_server_credentials.cc:45
    #3  0x00007ffff7bacf3e in grpc::Server::AddListeningPort (this=0x632340, addr="0.0.0.0:50051", creds=0x6328c0) at src/cpp/server/server.cc:376
    #4  0x00007ffff7bb2b5e in grpc::ServerBuilder::BuildAndStart (this=0x7fffffffe3d0) at src/cpp/server/server_builder.cc:128
    #5  0x000000000040d73c in RunServer () at greeter_server.cc:71
    #6  0x000000000040d87d in main (argc=1, argv=0x7fffffffe5a8) at greeter_server.cc:80

GCE has no IPv6 support. No network interface has an IPv6 address ; not even ::1. Apparently this results in 'sp' being NULL within src/core/iomgr/tcp_server_posix.c!grpc_tcp_server_add_port().

**Comment by jtattermusch** [comment]
seems very similar to fixed issue https://github.com/grpc/grpc/issues/4340. Please reopen if still an issue.
