### ISSUE TITLE
Sync and async methods under a service

### ISSUE THREAD

**Issue by M-Vivek** [grpc/grpc#4285]
It makes sense to have a mix of sync and async methods under a service, depending upon the app's use cases. Currently it is possibly only by exposing sync methods under one service and async methods under another. This would require the server to open up 2 ports.

The discussion in grpc Google group's on this as below:
https://groups.google.com/forum/#!topic/grpc-io/xNGqD2aPwYw

**Comment by pszemus** [comment]
I am able to run (from examples) greeter_async_server and send requests from both greeter_client and greeter_async_client. That means you can connect using async- and synchronous client.

**Comment by M-Vivek** [comment]
Hi,

This is about having mix of sync and async call implementations in server.

Thanks,
Vivek

**Comment by yang-g** [comment]
Hi Vivek,

I am actively working on this feature. Thanks for asking.

**Comment by pszemus** [comment]
Should that issue be closed as PR #4714 is merged?
I am also interested in mixed methods under a service.

**Comment by yang-g** [comment]
Yes. Please take a look at hybrid_end2end_test for a simple example.

**Comment by M-Vivek** [comment]
Thanks yang. Will check and let know..

**Comment by lumpidu** [comment]
How is the instance "priority" of an rpc method achieved if you register two service instances of the same service in a server: one as sync and one as async service. Which one gets called? Has the async service higher priority over the synchronous ? Or are they handled one after the other in a round robin way ?

**Comment by yang-g** [comment]
You cannot register two instances of the same service in a server. The server will complain and crash.

**Comment by lumpidu** [comment]
Ah ok, so if I want to handle some methods of a service async and the others in a sync way, how do I do it ?

**Comment by yang-g** [comment]
In hybrid_end2end_test.cc, you can find some examples doing that.

**Comment by grpccpp** [comment]
hybrid_end2end_test.cc I am seeing duplicate services were used. Will it work with a single service definition?
service EchoTestService {
  rpc Echo(EchoRequest) returns (EchoResponse);   // sync
  rpc RequestStream(stream EchoRequest) returns (EchoResponse);  // async 
  rpc ResponseStream(EchoRequest) returns (stream EchoResponse); // sync
  rpc BidiStream(stream EchoRequest) returns (stream EchoResponse); // async
  rpc Unimplemented(EchoRequest) returns (EchoResponse);
}

**Comment by vjpai** [comment]
Yes, you can do a single service with sync and async methods. The AsyncEcho test in hybrid_end2end_test uses Async only on the Echo method but doesn't use any dup service.

**Comment by grpccpp** [comment]
Hi Vjpai,
It worked for me. But, I added another method as sync service, I received duplicate registration error.

Here is my scenario.

I used helloworld example,
service Greeter {
rpc SayAsyncHello(Request) returns (Reply);
rpc SaySyncHello(Request) returns (Reply);
}

I tested the SayAsyncHello based on your comment ( async) . That worked.
Now I want to add SaySyncHello to a sync service.
I received the duplicate registration for SayAsyncHello.

Could you tell me, how to add sync and async services for the above Greeter service too?

Thanks
