### ISSUE TITLE
GRPC PHP doesn't build with ZTS enabled

### ISSUE THREAD

**Issue by sayrer** [grpc/grpc#4288]
This error 

>>> /usr/include/php/Zend/../TSRM/TSRM.h:167:18: error: 'tsrm_ls' undeclared
>>> (first use in this function)
>>>  #define TSRMLS_C tsrm_ls

shows up in

 zend_object_value create_wrapped_grpc_call(zend_class_entry *class_type
                                                TSRMLS_DC) {		                                                TSRMLS_DC) {

**Comment by stanley-cheung** [comment]
I can't quite seem to be able to reproduce this. Can you give me more details on how to reproduce this? And on which platform did you run into this error?

Here's roughly what I did, in a Debian jessie VM:

```
$ mkdir /opt/php-5.6.0
$ cd /opt/php-5.6.0
$ wget http://de.php.net/get/php-5.6.0.tar.bz2/from/this/mirror -O php-5.6.0.tar.bz2
$ apt-get install -y bzip2
$ tar jxf php-5.6.0.tar.bz2
$ cd php-5.6.0
$ apt-get install build-essential
$ apt-get build-dep php5
$ apt-get install libfcgi-dev libfcgi0ldbl libjpeg62-turbo-dbg libmcrypt-dev libssl-dev libc-client2007e libc-client2007e-dev
$ ./configure --prefix=/opt/php-5.6.0 --with-pdo-pgsql --with-zlib-dir --with-freetype-dir --enable-mbstring --with-libxml-dir=/usr --enable-soap --enable-calendar --with-curl --with-mcrypt --with-zlib --with-gd --with-pgsql --disable-rpath --enable-inline-optimization --with-bz2 --with-zlib --enable-sockets --enable-sysvsem --enable-sysvshm --enable-pcntl --enable-mbregex --enable-exif --enable-bcmath --with-mhash --enable-zip --with-pcre-regex --with-mysql --with-pdo-mysql --with-mysqli --with-jpeg-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-openssl --with-fpm-user=www-data --with-fpm-group=www-data --with-libdir=/lib/x86_64-linux-gnu --enable-ftp --with-imap --with-imap-ssl --with-kerberos --with-gettext --with-xmlrpc --with-xsl --enable-opcache --enable-fpm --enable-maintainer-zts
$ make
$ make install
$ ln -s /opt/php-5.6.0/bin/php /usr/bin/php
$ apt-get install php5-dev php-pear phpunit emacs git
$ pecl install grpc-beta
$ git clone https://github.com/grpc/grpc
$ cd grpc
$ git checkout release-0_13
$ cd src/php
$ ./bin/run_tests.sh
```

And I got no error.

**Comment by wulinlw** [comment]
i got the same error in centos6.7, gcc version:4.8

> git clone https://github.com/grpc/grpc.git
cd grpc
git pull --recurse-submodules && git submodule update --init --recursive
make
sudo make install
cd src/php/ext/grpc/
phpize
./configure
make

error:
> /bin/sh /root/grpc/src/php/ext/grpc/libtool --mode=compile cc -Wall -Werror -std=c11 -I. -I/root/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/root/grpc/src/php/ext/grpc/include -I/root/grpc/src/php/ext/grpc/main -I/root/grpc/src/php/ext/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /root/grpc/src/php/ext/grpc/byte_buffer.c -o byte_buffer.lo 
mkdir .libs
 cc -Wall -Werror -std=c11 -I. -I/root/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/root/grpc/src/php/ext/grpc/include -I/root/grpc/src/php/ext/grpc/main -I/root/grpc/src/php/ext/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /root/grpc/src/php/ext/grpc/byte_buffer.c  -fPIC -DPIC -o .libs/byte_buffer.o
/bin/sh /root/grpc/src/php/ext/grpc/libtool --mode=compile cc -Wall -Werror -std=c11 -I. -I/root/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/root/grpc/src/php/ext/grpc/include -I/root/grpc/src/php/ext/grpc/main -I/root/grpc/src/php/ext/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /root/grpc/src/php/ext/grpc/call.c -o call.lo 
 cc -Wall -Werror -std=c11 -I. -I/root/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/root/grpc/src/php/ext/grpc/include -I/root/grpc/src/php/ext/grpc/main -I/root/grpc/src/php/ext/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /root/grpc/src/php/ext/grpc/call.c  -fPIC -DPIC -o .libs/call.o
In file included from /usr/local/php/include/php/Zend/zend_alloc.h:27:0,
                 from /usr/local/php/include/php/Zend/zend.h:252,
                 from /usr/local/php/include/php/main/php.h:34,
                 from /root/grpc/src/php/ext/grpc/call.h:41,
                 from /root/grpc/src/php/ext/grpc/call.c:34:
/root/grpc/src/php/ext/grpc/call.c: In function ?.rpc_php_wrap_call?.
/usr/local/php/include/php/Zend/../TSRM/TSRM.h:167:18: error: ?.srm_ls?.undeclared (first use in this function)
 #define TSRMLS_C tsrm_ls
                  ^
/usr/local/php/include/php/Zend/../TSRM/TSRM.h:168:21: note: in expansion of macro ?.SRMLS_C?
 #define TSRMLS_CC , TSRMLS_C
                     ^
/usr/local/php/include/php/Zend/zend_API.h:363:79: note: in expansion of macro ?.SRMLS_CC?
 #define object_init_ex(arg, ce) _object_init_ex((arg), (ce) ZEND_FILE_LINE_CC TSRMLS_CC)
                                                                               ^
/root/grpc/src/php/ext/grpc/call.c:95:3: note: in expansion of macro ?.bject_init_ex?
   object_init_ex(call_object, grpc_ce_call);
   ^
/usr/local/php/include/php/Zend/../TSRM/TSRM.h:167:18: note: each undeclared identifier is reported only once for each function it appears in
 #define TSRMLS_C tsrm_ls
                  ^
/usr/local/php/include/php/Zend/../TSRM/TSRM.h:168:21: note: in expansion of macro ?.SRMLS_C?
 #define TSRMLS_CC , TSRMLS_C
                     ^
/usr/local/php/include/php/Zend/zend_API.h:363:79: note: in expansion of macro ?.SRMLS_CC?
 #define object_init_ex(arg, ce) _object_init_ex((arg), (ce) ZEND_FILE_LINE_CC TSRMLS_CC)
                                                                               ^
/root/grpc/src/php/ext/grpc/call.c:95:3: note: in expansion of macro ?.bject_init_ex?
   object_init_ex(call_object, grpc_ce_call);
   ^
/root/grpc/src/php/ext/grpc/call.c: In function ?.rpc_parse_metadata_array?.
/root/grpc/src/php/ext/grpc/call.c:129:9: error: too few arguments to function ?.end_exception_get_default?
         zend_throw_exception(zend_exception_get_default(),
         ^
In file included from /root/grpc/src/php/ext/grpc/call.c:47:0:
/usr/local/php/include/php/Zend/zend_exceptions.h:37:28: note: declared here
 ZEND_API zend_class_entry *zend_exception_get_default(TSRMLS_D);
                            ^
In file included from /usr/local/php/include/php/Zend/zend_alloc.h:27:0,
                 from /usr/local/php/include/php/Zend/zend.h:252,
                 from /usr/local/php/include/php/main/php.h:34,
                 from /root/grpc/src/php/ext/grpc/call.h:41,
                 from /root/grpc/src/php/ext/grpc/call.c:34:
/usr/local/php/include/php/Zend/../TSRM/TSRM.h:167:18: error: ?.srm_ls?.undeclared (first use in this function)
 #define TSRMLS_C tsrm_ls
                  ^
/usr/local/php/include/php/Zend/../TSRM/TSRM.h:168:21: note: in expansion of macro ?.SRMLS_C?
 #define TSRMLS_CC , TSRMLS_C
                     ^
/root/grpc/src/php/ext/grpc/call.c:131:32: note: in expansion of macro ?.SRMLS_CC?
                              1 TSRMLS_CC);
                                ^
make: *** [call.lo] Error 1

**Comment by stanley-cheung** [comment]
hm, I am still struggling to reproduce this.

I am using CentOS 6.7, gcc 4.8.2
```
cat /etc/centos-release
CentOS release 6.7 (Final)

gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
```

I followed these as above:

```
git clone https://github.com/grpc/grpc.git
cd grpc
git pull --recurse-submodules && git submodule update --init --recursive
make
sudo make install
cd src/php/ext/grpc/
phpize
./configure
make
sudo make install
cd ../..
./bin/run_tests.sh
```

And did not run into errors.

Is there a dockerfile you can share that I can reproduce this?

**Comment by stanley-cheung** [comment]
To clarify: the above is done in a CentOS 6.7 VM, not in docker.

**Comment by stanley-cheung** [comment]
Just in case, which PHP version are you using? Only PHP 5.5 or above is supported.

**Comment by stanley-cheung** [comment]
Here's a log of what I did.

I started with a CentOS 6.7 VM on google cloud platform then run these commands:

```
sudo yum update

## update gcc to 4.8
sudo rpm --import http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/RPM-GPG-KEY-cern
sudo wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo
sudo yum install devtoolset-2
scl enable devtoolset-2 bash

## install PHP 5.5
sudo rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
sudo rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
sudo yum install php55w

## install pecl, and phpize
sudo rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
sudo yum --enablerepo=remi,remi-php55 install php-pear
sudo yum --enablerepo=remi,remi-php55 install php-devel

## install phpunit
sudo wget https://phar.phpunit.de/phpunit-old.phar -O phpunit.phar
sudo chmod +x phpunit.phar
sudo mv phpunit.phar /usr/local/bin/phpunit

## install git
sudo yum install git
```

Here are the relevant binaries version
```
[stanleycheung@stanleycheung-centos-test ~]$ cat /etc/centos-release
CentOS release 6.7 (Final)

[stanleycheung@stanleycheung-centos-test ~]$ gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[stanleycheung@stanleycheung-centos-test ~]$ libtool --version
ltmain.sh (GNU libtool) 2.2.6b
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[stanleycheung@stanleycheung-centos-test ~]$ php --version
PHP 5.5.33 (cli) (built: Mar  2 2016 14:43:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

[stanleycheung@stanleycheung-centos-test ~]$ pecl version
PEAR Version: 1.10.1
PHP Version: 5.5.33
Zend Engine Version: 2.5.0
Running on: Linux stanleycheung-centos-test 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64

[stanleycheung@stanleycheung-centos-test ~]$ phpunit --version
PHPUnit 4.8.23 by Sebastian Bergmann and contributors.

[stanleycheung@stanleycheung-centos-test ~]$ git --version
git version 1.8.4
```

Then try to install the gRPC PHP extension
```
git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init --recursive
make
sudo make install
cd src/php/ext/grpc
phpize
./configure
make
sudo make install
cd ../..
./bin/run_tests.sh
```

**Comment by wulinlw** [comment]
stanley-cheung is right, it's works on my new centos6.7 vm
