### ISSUE TITLE
grpc-jenkins-worker7 is down

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4291]
It went offline a while ago. If it's impossbile to SSH to it, the VM probably needs recreating (described in the jenkins document).

Please create an entry in the maintenance log afterwards.

https://grpc-testing.appspot.com/computer/

**Comment by adelez** [comment]
Log entered in https://docs.google.com/document/d/1t5zzwE95QGJs0GzUY9EMGl-ETToPDyhYtQ0v4f6y2gQ/edit#heading=h.mipcencx3yp7
