### ISSUE TITLE
Update Bazel rules and let specify GPB_OBJC_EXPECTED_PACKAGE_PREFIXES

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4309]
[`GPB_OBJC_EXPECTED_PACKAGE_PREFIXES`](https://github.com/google/protobuf/search?utf8=%E2%9C%93&q=GPB_OBJC_EXPECTED_PACKAGE_PREFIXES) is an env variable that points to a user-supplied file the protoc ObjC plugin optionally uses to verify that the prefixes of proto files match what the developer expects (given its proto package).

**Comment by nicolasnoble** [comment]
I'll need to discuss with @makdharma about that one.
