### ISSUE TITLE
Make sure gRPC PHP works with PHP 7

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#4337]

**Comment by tslater** [comment]
Does anyone know the status on this? We'd love to use php7 because it's done really well in benchmarks on our code, but we need gRPC.

**Comment by stanley-cheung** [comment]
The plan is to tackle this soon. Will give a better update in the next couple of weeks.

**Comment by stanley-cheung** [comment]
The plan is to tackle this soon. Will give a better update in the next couple of weeks.

**Comment by jmarchant** [comment]
I would love to have this too! I need php 7 support for grpc since my project is already on php7.

**Comment by thuey** [comment]
I really appreciate the work you've done. Can you give a better update now? We've been blocked by this for a while.

**Comment by tslater** [comment]
I'm wondering if this could help: `zephir build --backend=ZendEngine3`? It looks like they got the same error: `zend_object_value` in the phalcon project trying to build for php7 and had some success: https://github.com/phalcon/cphalcon/issues/11203. I don't have hardly any experience building php extensions, but does anyone with more understanding have any thoughts on that? Is it worth trying?

**Comment by joshuabird** [comment]
This is a huge deal for us too.  We have done a lot of testing ourselves, and we have seen major performance increases with PHP 7, but like others, we can't proceed without gRPC.

**Comment by tslater** [comment]
@stanley-cheung, is there any chance you have an update on this yet?

**Comment by janhalfar** [comment]
thanks a lot for all your work - php7 would be highly appreciated

**Comment by smolinari** [comment]
:+1: 

Looking forward to this.

Scott

**Comment by stanley-cheung** [comment]
Yes, sorry for the lack of update. This is very much in the radar. I am hoping to get to this this quarter.

**Comment by janhalfar** [comment]
cool!

**Comment by thinkerou** [comment]
I have forked code the grpc php extension, and upgraded grpc PHP extensions from PHP5 to PHP7. It may be have some problems,  but can right run example and unittest. links: https://github.com/thinkerou/grpc-php7

**Comment by tslater** [comment]
That's great news! Thanks so much.  Does that tag mean that this will go out in the next release?

**Comment by thinkerou** [comment]
I have updated but I don't know how commit `grpc-php7`to `grpc/src/php`, make new directory for saving `grpc-php7`? @stanley-cheung

**Comment by tslater** [comment]
@stanley-cheung, do you think @thinkerou's contributions will work?

**Comment by chriskite** [comment]
@stanley-cheung I'm also very interested in PHP 7 support. I'm waiting on this to be able to deploy a new microservice library.

**Comment by thinkerou** [comment]
If the directory `src/php/ext/` has two directories which are `grpc` and `grpc-php7`, this will need to maintain two codes when the code changed; I want to attempt to use `marco` to wrap function that can use in `php5` and `php7`, but the method make the code ugly.

**Comment by thinkerou** [comment]
@jtattermusch  thinks that gRPC will not officially support PHP7 for GA: https://github.com/grpc/grpc/issues/6366#issuecomment-227801621

**Comment by thinkerou** [comment]
Now the master branch and the v1.0.x have supported PHP7, congratulations!

**Comment by stanley-cheung** [comment]
Two things:
 - I'm going to release the `1.0.0RC2` pecl extension soon. That will install both on PHP5 and PHP7.
 - There is an issue with PHP7 and the Protobuf-PHP code generation. I am fixing it. Once that's fixed then PHP7 support is complete.

**Comment by stanley-cheung** [comment]
Final update:
 - The `1.0.0RC2` version of the PECL extension has been released. It will install both on PHP5 and PHP7.
 - The PHP7 Protobuf-PHP issue has been fixed. Code generation should work on PHP7.
 - Thanks [thinkerou](https://github.com/thinkerou) for his contribution to making this work!
