### ISSUE TITLE
Implementation pod generating an empty group (missing .h/.m files)

### ISSUE THREAD

**Issue by Gurpartap** [grpc/grpc#4350]
The grpc implementation pod (`GRPCAPI` in my case) is an empty group. It's a direct port of the route_guide example.

![screen shot 2015-12-09 at 6 26 43 am](https://cloud.githubusercontent.com/assets/39792/11673323/d716b62a-9e3d-11e5-97c6-2e0387d05f04.png)

```sh
$ bundle exec pod --version
0.39.0
```

```ruby
$ cat Podfile
source "https://github.com/CocoaPods/Specs.git"
platform :ios, "8.0"

use_frameworks!
inhibit_all_warnings!

pod "Protobuf"
pod "BoringSSL"
pod "gRPC", git: "https://github.com/grpc/grpc"
pod "GRPCAPI", path: "/path/to/GRPCAPI.podspec"
```

```ruby
$ cat /path/to/GRPCAPI.podspec
Pod::Spec.new do |s|
  s.name     = "GRPCAPI"
  s.version  = "0.0.1"
  s.license  = "New BSD"

  s.ios.deployment_target = "7.1"
  s.osx.deployment_target = "10.9"

  # Base directory where the .proto files are.
  src = "/path/to/protos"

  # Directory where the generated files will be placed.
  dir = "/path/to/Pods/" + s.name

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  s.prepare_command = <<-CMD
    mkdir -p #{dir}
    protoc -I #{src} --objc_out=#{dir} --objcgrpc_out=#{dir} #{src}/*.proto
  CMD

  s.subspec "Messages" do |ms|
    ms.source_files = "#{dir}/*.pbobjc.{h,m}", "#{dir}/**/*.pbobjc.{h,m}"
    ms.header_mappings_dir = dir
    ms.requires_arc = false
    ms.dependency "Protobuf", "~> 3.0.0-alpha-4"
  end

  s.subspec "Services" do |ss|
    ss.source_files = "#{dir}/*.pbrpc.{h,m}", "#{dir}/**/*.pbrpc.{h,m}"
    ss.header_mappings_dir = dir
    ss.requires_arc = true
    ss.dependency "gRPC", "~> 0.11"
    ss.dependency "#{s.name}/Messages"
  end
end
```

I can see the .pbobjc and .pbrpc files generated inside `Pods/GRPCAPI`. They're not included in the Pods Xcode project as in the screenshot above.

**Comment by Gurpartap** [comment]
I have this even without `use_frameworks!` in the Podfile and by using OpenSSL pod instead of BoringSSL (i.e. pod grpc ~> 0.11)

Maybe related: https://github.com/CocoaPods/CocoaPods/issues/4605

**Comment by Gurpartap** [comment]
No corresponding target is generated either...

![screen shot 2015-12-09 at 7 02 44 am](https://cloud.githubusercontent.com/assets/39792/11674017/e373c62e-9e42-11e5-872e-2e4bcd58e210.png)

**Comment by Gurpartap** [comment]
Here's a reference project reproducing the issue: https://github.com/Gurpartap/echo-grpc-swift

**Comment by jcanizales** [comment]
Can you paste the output of `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES pod install --verbose`, just in case there's a smoking gun there?

**Comment by Gurpartap** [comment]
https://gist.github.com/Gurpartap/a7e81972b130e24d5a58

**Comment by Gurpartap** [comment]
It might be the [podspec](https://github.com/Gurpartap/echo-grpc-swift/blob/master/proto/EchoSDK.podspec).

Files are generating though:

```
$ ls ios/Pods/EchoSDK/
Echo.pbobjc.h  Echo.pbobjc.m  Echo.pbrpc.h   Echo.pbrpc.m
```

Let me summon the cocoagods

**Comment by Gurpartap** [comment]
Apparently `source_files` and `header_mappings_dir` in podspec are unable to handle relative paths.

```diff
$ cat EchoSDK.podspec.patch
# Directory where the generated files will be placed.
--  dir = "../EchoClient/Pods/" + s.name
++  dir = "Pods/" + s.name
```

🙈

None of the podspec files in gRPC do this. All good.

**Comment by jcanizales** [comment]
> Also, since the value in these variables is expected to be relative to where `pod install` is run from and not where the podspec is located

This sounds weird to me, but I'm glad you solved it. I think the lesson for us is to try and simplify the sample podspec.
