### ISSUE TITLE
[Ruby] cpu 100% on run_till_terminated

### ISSUE THREAD

**Issue by yancl** [grpc/grpc#4354]
Hi, We recently use the `server.run_till_terminated` instead of `server.run` so that the server will exit when send ctrl+c and found that the cpu is near 100%,after some dig, we found the following code:
```
lib/grpc/generic/rpc_server.rb

    def run_till_terminated
      GRPC.trap_signals
      t = Thread.new { run }
      wait_till_running
      loop do
        sleep SIGNAL_CHECK_PERIOD
        break unless GRPC.handle_signals
      end
      stop
      t.join
    end

   def handle_signals
    loop do
      sig = $grpc_signals.shift
      case sig
      when 'INT'
        return false
      when 'TERM'
        return false
      end
    end
    true
  end
```

As you can see, the `$grpc_signals.shift` is not a **block** operation, so it will eat up cpu core it runs on.
will you please make it a block operation or just add a short sleep in it? thanks.

**Comment by murgatroid99** [comment]
That code you quoted is doing a `sleep` before each time it calls `handle_signals`. It may be using a lot of CPU time, but that code shouldn't be the problem.

**Comment by yancl** [comment]
Should it be like this?

```
def handle_signals
    loop do
      sig = $grpc_signals.shift
      case sig
      when 'INT'
        return false
      when 'TERM'
        return false
      when nil
        break
      end
    end
    true
  end
```

Add a **nil** case so that it can break the loop when the `$grpc_signals` is **empty**? or else it just **loop** when `$grpc_signals` is empty. thanks.

**Comment by murgatroid99** [comment]
You're right, I totally missed that. I should be able to get a fix for this into the next release.

**Comment by yancl** [comment]
Thanks:)
