### ISSUE TITLE
Document the allowable combinations of inputs to grpc_ssl_server_credentials_create

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#4375]
There are a couple of cases that currently work but seem like they shouldn't:

 - `pem_root_certs == NULL` and `num_key_cert_pairs == 0`. This means the cert doesn't do anything.

 - `pem_root_certs == NULL` and `force_client_auth == true`. This doesn't really make sense

**Comment by hsaliak** [comment]
@jboeuf any progress on this issue?

**Comment by jboeuf** [comment]
Nope sorry. We also had an API update (additional more flexible function
for this specific functionality) as well that we will need to wrap in
wrapped languages at some point (nothing urgent), we can go GA without it.

**Comment by jboeuf** [comment]
@hsaliak @nicolasnoble is this really a P1? 

This API has been deprecated in favor of `grpc_ssl_server_credentials_create_ex` which is clearly documented.

**Comment by hsaliak** [comment]
@jboeuf if this is a deprecated issue, then the issue can go away.
Closing the issue, please re-open if you have objections. /cc @murgatroid99
