### ISSUE TITLE
Will grpc work with openssl-1.0.1, if I disable TSI_OPENSSL_ALPN_SUPPORT in the src?

### ISSUE THREAD

**Issue by zhengcai** [grpc/grpc#4395]
Hi Everyone,

In our project we cannot upgrade to openssl-1.0.2 due to dependency issues, so we are stuck with 1.0.1. I found out that if I #define TSI_OPENSSL_ALPN_SUPPORT 0, everything compiles fine without the ALPN support. But obviously this is a hack.

I just wonder, will grpc work well with ALPN disabled, especially with the secure transport layer?

Thank you so much.

**Comment by jboeuf** [comment]
Yes it will. We have an NPN fallback for older versions of OpenSSL.

**Comment by zhengcai** [comment]
Thanks again, it really helps!
