### ISSUE TITLE
Can not return a standard GRPC error from a python-defined service

### ISSUE THREAD

**Issue by inconshreveable** [grpc/grpc#4417]
There is no facility that I can find (or documented anywhere) to return a standard GRPC error code from a python service. I expect something simple like:

```
class BooksService(BetaBooksServicer):
  def GetByName(self, msg, context):
    raise grpc.Error(StatusCode.NOT_FOUND, "No book with name {} was found".format(msg))
```

**Comment by nathanielmanistaatgoogle** [comment]
Do you see a `code` method on your `context` object, to which a value from `grpc.beta.interfaces.StatusCode` may be passed?

**Comment by inconshreveable** [comment]
I can confirm this works

**Comment by anentropic** [comment]
are there some more docs anywhere? there seems to be a big gap between the trivial tutorial and the auto-generated api docs at http://www.grpc.io/grpc/python/grpc.html

**Comment by nathanielmanistaatgoogle** [comment]
@anentropic: if by "the trivial tutorial" you mean [the "hello world" quick start](http://www.grpc.io/docs/quickstart/python.html), have you seen [the longer "route guide" tutorial](http://www.grpc.io/docs/tutorials/basic/python.html)?

**Comment by anentropic** [comment]
I mean the route guide... yes it helps get a client and server off the ground but it raises a bunch of questions, such as the above

eg I'm currently experimenting with converting our REST API over to grpc

in the route guide tutorial if you search for a Feature that doesn't exist they return an empty (i.e. all-default-values) Feature.  This seems an odd choice - is this idiomatic in grpc?  Won't that make things more complicated or hopelessly ambiguous for the clients?

In REST we'd return an Http 404

It's not clear what you're supposed to do in your servicer methods if you can't return a protobuf of the requested type.  You seem to imply above that you can do `context.set_code(grpc.StatusCode.NOT_FOUND)` and return None ?

Is all this spelled out somewhere that I've missed?

**Comment by anentropic** [comment]
that doesn't work anyway, I get:

```
TypeError: unbound method SerializeToString() must be called with PublicUser instance as first argument (got NoneType instance instead)
```

in the server, and:

```
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, Failed to serialize response!)>
```

in the client (which then exits)

So this raises more questions: am I supposed to set the status code _and_ return a dummy object?  And then... what exceptions should I be catching in the client?

Or more generally, how are you supposed to communicate error messages between the server and client?  Is there a general mechanism for this, analogous to http status codes, or I need to construct a response message protobuf that wraps my return type with extra fields for 'errors', the optional 'results' etc?

I'm sure I can work most of this out for myself with a few days effort, but this is the sort of elementary stuff people need to know when getting started which doesn't seem to be covered in the docs or tutorial (which is not a tutorial, it's just some example code and how to run it)

I mean, people are using this in production no? there must be an already established 'right way' to do all these things

**Comment by nathanielmanistaatgoogle** [comment]
Without right now answering:

* Is Route Guide's returning an empty `Feature` to indicate no-such-`Feature` idiomatic?
* To what extent are gRPC status codes supposed to correspond to HTTP status codes, and to what extend do they anyway?

I'll say:

* Even after setting a non-`OK` status code, service-side code must still return a value of the appropriate type (perhaps we should soften this to "may", but there's one edge-case use case that might get broken by that, so I'll have to think about it).
* [On the client you should be catching `grpc.RpcError`](http://www.grpc.io/grpc/python/grpc.html#grpc.UnaryUnaryMultiCallable.__call__). The `grpc.RpcError` instance raised to your code will also be instances of `grpc.Call` affording access to the metadata, status code, and status details of the RPC.
* The intended use case of the status details string is passing a simple message about the service-side failure to the client-side application. To pass more complex or structured information reporting service-side failure, trailing metadata is the intended use case.

**Comment by anentropic** [comment]
thanks very much for the info

'trailing metadata' is something distinct from the message body?

how do I return that from my servicer methods?

it needs documenting, all I found so far is this https://github.com/grpc/grpc/issues/6142 showing how to read it from the client

**Comment by nathanielmanistaatgoogle** [comment]
Yes, trailing metadata is distinct from the messages sent from the service-side application.

Service-side code sets it to be returned by calling the [`set_trailing_metadata`](https://github.com/grpc/grpc/blob/b2a9940465bf8faad648f06316e8b6400c10aa9e/src/python/grpcio/grpc/__init__.py#L735) method on the `ServicerContext` object passed to it. In lieu of a proper example, [here is use of the method in our test suite](https://github.com/grpc/grpc/blob/b2a9940465bf8faad648f06316e8b6400c10aa9e/src/python/grpcio_tests/tests/unit/_metadata_code_details_test.py#L89).

**Comment by murgatroid99** [comment]
I would like to note that in general (across languages), a non-OK status is not expected to be accompanied by a message.

**Comment by shaoweipng** [comment]
is there any update on this?  Is it still true that we must return a dummy value in addition to the error values? 

Just like the other users, I am seeing the SerializeToString() error on my server now.

It would be great to have a documented working pattern for this.

**Comment by nathanielmanistaatgoogle** [comment]
@shaoweipng: it is still the case that server-side implementations of response-unary methods must return a valid message object even after having set status to a non-`OK` value. Relaxing that restriction is still something about which I think from time to time but because it's not yet known to be a major problem for anyone it's not yet a high priority.

**Comment by LewisMcReu** [comment]
Am I correct in my assumption that when a not-OK status code is sent back to client, an error will be thrown?
Otherwise, how would I access that status code?

**Comment by nathanielmanistaatgoogle** [comment]
@LewisMcReu: you're correct in the case of a blocking call that an exception will be raised (this exception will be an instance of both `grpc.RpcError` and `grpc.Call`). In asynchronous and response-streaming cases the `grpc.Future` and iterator-of-responses objects will also be instances of `grpc.Call`. [Wherever you have a `grpc.Call`, you can get the status code.](http://www.grpc.io/grpc/python/grpc.html#grpc.Call.code)

**Comment by nathanielmanistaatgoogle** [comment]
Regarding ["Even after setting a non-OK status code, service-side code must still return a value of the appropriate type (perhaps we should soften this to 'may', but there's one edge-case use case that might get broken by that, so I'll have to think about it)"](https://github.com/grpc/grpc/issues/4417#issuecomment-242998794): we'll explore that over in [issue 12826](https://github.com/grpc/grpc/issues/12826).
