### ISSUE TITLE
Awkward to run multiple GRPC servicers on the same port in Python

### ISSUE THREAD

**Issue by inconshreveable** [grpc/grpc#4418]
In grpc's Go implementation, it is trivial to multiplex a single port with multiple GRPC services:

```
    srv := grpc.NewServer()
    rpxRegisterBooksServer(srv, booksSvc)
    rpx.RegisterMoviesServer(srv, mediaSvc)
    rpx.RegisterGamesServer(srv, mediaSvc)
```

No similar functionality existing in Python because creating a server is inextricably tied to the creation of a server:

```
server = rpx.beta_create_Books_server(Books())
```

This interface is unnecessarily ties together two separate concerns (creation of a server and the registration of a servicer on a server). A better API would be similar to Go's

```
server = grpc.new_server()
rpx.beta_add_Books_service(server, Books())
```

**Comment by soltanmm** [comment]
We can do this as an entirely additive change (whew); slating for post-GA.

**Comment by nathanielmanistaatgoogle** [comment]
I have a pretty strong idea of how I'd like to do this but may not get to it for a while. How pressing is the need for this on your side? How onerous is the workaround?

**Comment by inconshreveable** [comment]
It's not too onerous. It adds additional configuration complexity because now each logical service has to listen on a separate port. It's motivating moving as much functionality out of python as well, so that's not too bad either.

**Comment by nathanielmanistaatgoogle** [comment]
Actually, I meant the workaround that lets you run multiple servicers on the *same* port.

Something I wrote separately about this but might as well copy here:
```
You can create a server with grpc.beta.implementations.server,
which takes a dictionary of service implementations. Your code
would probably look something like:

def one_method(request_object, servicer_context):
  return <response expression>

def another_method(request_iterator, servicer_context):
  for request in request_iterator:
    yield <a response expression>
    yield <another response expression>

service_implementations = {
    ('/one_package.OneService', 'one_method'): utilities.unary_unary_inline(one_method),
    ('/another_package.AnotherService', 'another_method'): utilities.stream_stream_inline(another_method),
}

server = implementations.server(service_implementations, <possibly a ServerOptions object specifying protocol buffer serialization/deserialization behaviors>
```
. How does that look to you?

**Comment by inconshreveable** [comment]
Ah! I hadn't seen that. That looks pretty reasonable.

**Comment by therc** [comment]
Is this still low priority? We want to add a standard gGRPC health check to N different servers. We don't want to add the request to the existing services themselves, because then we'd need N different probers. As the original poster says, this is trivial in Go, but cumbersome in Python. Also, the workaround is messy, especially when serializers and deserializers get into the picture. (I mostly work on the Go stuff, so I can't recall with all that my colleague had to deal with.)

**Comment by AndrewIngram** [comment]
In evaluating whether to use gRPC or thrift (I much prefer the appearance of gRPC), the two biggest issues with gRPC right now are lack of Python 3 support, and lack of a trivial API for doing service multiplexing.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle i see that this is marked as "to close" and then GA. Do we have an updated workaround available that addresses the earlier concerns?

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: I intend to have it in place by tomorrow.

**Comment by nathanielmanistaatgoogle** [comment]
This will be fixed by [pull request 6874](https://github.com/grpc/grpc/pull/6874) which has passed review and is ready to merge.

**Comment by nathanielmanistaatgoogle** [comment]
Anyone else coming across this: we've added an example of multiple servicers in one server in [`examples/python/multiplex`](https://github.com/grpc/grpc/tree/7b104cd1c23a3e6ee3cb0809f39617ceda5e2575/examples/python/multiplex).

**Comment by amitsaha** [comment]
@AndrewIngram I am curious what you meant by "grpc's lack of Python 3 support"? I have been playing with Python 3 + gRPC and everything seems to be working?
