### ISSUE TITLE
Create a nuget package for gRPC C++

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4419]
This would allow adding gRPC C++ to your visual studio project with a single click. 

This package should work similarly as the existing grpc.dependencies.openssl and grpc.dependencies.zlib (with detection logic to pick the right libraries based on VS version, configuration and bitness).

**Comment by mrapavy** [comment]
+1

**Comment by andresiraola** [comment]
+1

**Comment by Retik** [comment]
There is already a nuget package grpc.cpp published by Google Inc. Howeveer, it is only version 1.0.1. Could it be updated to 1.2.x or a new package be published?

**Comment by jtattermusch** [comment]
The grpc.cpp is a contrib package (not an official package coming from gRPC team). @mrapavy  seems to be the author. @mrapavy, can you point us to the source code for nuget package?

**Comment by jozefizso** [comment]
We've switched from prebuilt grpc NuGet C++ packages to the [vcpkg](https://github.com/Microsoft/vcpkg) so we can build a release that better matches compiler settings with our other C++ projects.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/10699

**Comment by jtattermusch** [comment]
Closing in favor of #10699
