### ISSUE TITLE
StatusCodeAndMessage test client sometimes receives "Received RST_STREAM err=8"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4427]
In the status_code_and_message interop test, after server-side handler correctly sets
StatusCode = Unknown and StatusDetail = "test status message",  

client receives status code Unknown, but the message is sometimes set to "Received RST_STREAM err=8".

```
Test Failure : Grpc.IntegrationTesting.InteropClientServerTest.StatusCodeAndMessage
     Expected string length 19 but was 25. Strings differ at index 0.
  Expected: "test status message"
  But was:  "Received RST_STREAM err=8"
```

**Comment by jtattermusch** [comment]
@murgatroid99 , have you seen a similar problem for Node?

**Comment by murgatroid99** [comment]
Not that I can remember.

**Comment by jtattermusch** [comment]
Same thing happends for UnimplementedMethod test.

**Comment by jtattermusch** [comment]
node seems to have the same problem

https://grpc-testing.appspot.com/job/gRPC_interop_master/1614/testReport/junit/(root)/tests/cloud_to_cloud_node_csharp_server_status_code_and_message/

**Comment by jtattermusch** [comment]
FYI @ctiller, this has been seen in both node & c#, so it looks more like a C core issue.

**Comment by jtattermusch** [comment]
Reassigning to @murgatroid99 as I will be OOO for a while.

**Comment by murgatroid99** [comment]
Seen again at https://grpc-testing.appspot.com/job/gRPC_interop_master/2172/testReport/junit/(root)/tests/cloud_to_cloud_csharp_csharp_server_unimplemented_method/

**Comment by murgatroid99** [comment]
I am pretty sure this is a core bug. The bug is that this error is going on the wire, not that the libraries are reporting it.

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_interop_master/3143/testReport/junit/(root)/tests/cloud_to_cloud_node_csharp_server_status_code_and_message/

**Comment by jtattermusch** [comment]
Similar thing happens for UnimplementedMethod interop test: https://grpc-testing.appspot.com/job/gRPC_interop_master/3133/testReport/junit/(root)/tests/cloud_to_cloud_csharp_csharp_server_unimplemented_method/

**Comment by jtattermusch** [comment]
I will probably start looking into this.

**Comment by ctiller** [comment]
Yang might be able to help (depending on load)

**Comment by jtattermusch** [comment]
https://http2.github.io/http2-spec/#ErrorCodes 
CANCEL (0x8): Used by the endpoint to indicate that the stream is no longer needed.

**Comment by ctiller** [comment]
How are C# and Node reporting the status to core? With a batch containing
send status, or with a call_cancel_with_status?

**Comment by jtattermusch** [comment]
I do e.g.
`await responseStream.WriteStatusAsync(new Status(StatusCode.Unimplemented, ""), Metadata.Empty).ConfigureAwait(false);`

**Comment by jtattermusch** [comment]
I am actually invoking a "safety" call_cancel  in the serverside handler if the  "cancelled" flag is set when "recv_close_on_server" event is delivered. I recall this used to be necessary to correctly close the request stream if server wanted to just write the status and ignore all the requests.

**Comment by jtattermusch** [comment]
It looks like the issue is caused by C# server  (that's why we were seeing it with both node and C# clients). My apologies for thinking it's a C core bug.

On the other hand, there might be a C core bug that is more subtle - it looks like if you concurrently try to perform write status and cancel operations, on the client side you'll some something in between - the status message "Received RST_STREAM err=8".

**Comment by ctiller** [comment]
So that behavior is -kind of- expected: if a stream isn't fully closed, a
cancellation must put a RST_STREAM on the wire. There's no synchronization
mechanism that's low enough cost to allow anything other semantic (we don't
want to slow the write path to make allowances for cancellation). So... we
let the write status and the cancellation race down to the transport level,
and see which one arrives first to decide what we should do.

**Comment by bfrancojr** [comment]
Hi,

I'm getting similar error message from golang (server and client) as well:

```error code = 13 - stream terminated by RST_STREAM with error code: 1````

Any advise?

Thanks,
