### ISSUE TITLE
Compilation failure on Centos 6.5 32 bit

### ISSUE THREAD

**Issue by Zeks** [grpc/grpc#4462]
I am trying to compile grpc on Centos 6.5 32 bit and with both gcc 4.8.2. and gcc 4.9.1 I get the following error:

src/core/support/sync_posix.c: In function ‘gpr_cv_wait’:
src/core/support/sync_posix.c:84:30: error: conversion to ‘__time_t’ from ‘gpr_int64’ may alter its value [-Werror=conversion]
     abs_deadline_ts.tv_sec = abs_deadline.tv_sec;
                              ^
cc1: all warnings being treated as errors

Any idea on how to fix that?

**Comment by sofuckingnice** [comment]
+1 ubuntu 14.04 32  gcc 4.8.4

**Comment by QingLeiLi** [comment]
+1 ubuntu 12.04 32bit

**Comment by ctiller** [comment]
@jtattermusch can you ping this back to me once we have testing available for this.

**Comment by larsonmpdx** [comment]
issue is also mentioned in #4105.  workaround for now is turning off -Werror

**Comment by jtattermusch** [comment]
As of now, we have continuously running test for debian jessie 32bit, and C core is building (and I remember fixing the compilation error mentioned in this issue) and all the tests are passing (with the exception of gpr_thd_test, and we have an issue filed for that)

See our build and test result:
https://grpc-testing.appspot.com/job/gRPC_portability_master/340/

Based on that, I'll consider this resolved. Please reopen if you are still seeing issues.
