### ISSUE TITLE
Period needs to be permitted in header names

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc#4466]
@ctiller 
@tbetbetbe 

See https://github.com/grpc/grpc/pull/4465

**Comment by jcanizales** [comment]
I guess this is probably just a matter of adding a test for the C library.

**Comment by louiscryan** [comment]
Has already happened.

**Comment by ctiller** [comment]
Louis: we should probably have an interop test for this.

**Comment by louiscryan** [comment]
Agreed.
