### ISSUE TITLE
It's too easy to get a virtualenv and tox that don't work with gRPC Python

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#4473]
If one constructs a brand-new `Debian 8.2 (jessie)` instance and uses `sudo apt-get install` to install everything that gRPC Python requires _including_ `python-virtualenv` and `python-tox`, one winds up in a state in which gRPC Python will fail to build (with `error: invalid command 'build_data'`, likely because at least one of `virtualenv` 1.11.6 and `tox` 1.8.0 is too old) and `sudo pip install --upgrade` is not sufficient to remedy the problem.

When constructing a development environment for gRPC Python, it is apparently required to avoid `sudo apt-get install python-virtualenv` and `sudo apt-get install python-tox` and instead install these packages with `sudo pip install --upgrade virtualenv` and `sudo pip install --upgrade tox`. This will (as of the current moment) give the system `virtualenv` 13.1.2 and `tox` 2.3.1.

Fun but not immediately relevant fact: `sudo apt-get install python-virtualenv` followed by `sudo pip install --upgrade virtualenv` leaves one's machine in a state in which virtualenv is unusable because `/usr/local/bin/virtualenv` looks for `/usr/bin/virtualenv` and does not find it.

**Comment by soltanmm** [comment]
The fun fact derives from the usual using-multiple-package-managers problem (which I don't believe anyone's found a reasonable solution to yet beyond, "Don't do it.").

**Comment by soltanmm** [comment]
I don't have access to any work machines at the moment, but I found this: https://aur.archlinux.org/packages/python2-pyvisa/ . Maybe try installing docutils with sudo apt-get?

**Comment by carl-mastrangelo** [comment]
FTR this is still an issue on my workstation.  It would be nice if it was possible to build the docs locally without having to SSH into the cloud instances.

**Comment by nathanielmanistaatgoogle** [comment]
I strongly suspect that this is going to be one of those needs that we address by waving our hands and saying "Bazel will solve this along with all other build issues".

... but for the moment let's keep it open.

**Comment by mehrdada** [comment]
It's not clear what the concrete steps are that are in our hands and improve the situation and I have not encountered this myself recently. No user issues either. Bazel support is also out. Closing.
