### ISSUE TITLE
gprc dies on an assertion when calling Read on a finished stream

### ISSUE THREAD

**Issue by aisotton** [grpc/grpc#4475]
When calling Read again on a stream after a previous Read has returned false, grpc dies on an assertion.

e.g.

    auto reader = stub->Foo(...);
    while (reader->Read(...)) {
      // ...
    }
    reader->Read(...);  // <-- dies on assert

This is the error:

`E1215 12:39:49.606221062    2017 channel.cc:91]              assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)`

A patch to the end2end test for a reproduction is attached.
[readcrash.txt](https://github.com/grpc/grpc/files/63168/readcrash.txt)

**Comment by aisotton** [comment]
This was introduced sometime between 0.11 and now.

**Comment by ctiller** [comment]
Yep... can repro. Fix incoming.
