### ISSUE TITLE
gRPC Python streaming RPC connection issue

### ISSUE THREAD

**Issue by shuowusc** [grpc/grpc#4476]
Environment: gRPC beta (grpcio (0.11.0b1)) on Mac and Linux

We have the following setup: A client will try to "register" to a server by maintaining a long-lived bi-directional streaming RPC connection. The client will periodically (every 30 secs) send a status update and the server will immediately ack. If the client doesn't get the ack after 30 seconds, it will cancel the RPC connection (streaming iterator and stub) and try to re-connect on the same channel.

Here is what we observed from the client's logs:
1) The client connects successfully to the server initially, it maintains the expected pattern: send - recv immediate ack, wait for 30 seconds, send ...
2) After the server shutdown, we get the expected behavior: detected server go away -> network error -> send -> 30 seconds timeout -> CancellationError -> Reconnect -> send -> 30 secs timeout -> CancellationError -> Reconnect -> ...    
3) After the server restarts, the client channel successfully re-connects with the server. However, it now displays a weird pattern that it only receives a successful ack for EVERY OTHER update it sent: 
send -> immediate ack -> 30 secs -> send -> 30 seconds -> CancellationError -> send -> immediate ack. -> ...

Please help investigate why this channel now drops the request/ack for every other request sent. Thanks very much!

Logs:
MainProcess|Thread-10|I2015-12-15 13:00:33.345:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:00:33.349:registration_manager.py:90] Received server ack: response { success: true }
MainProcess|MainThread|I2015-12-15 13:01:03.312:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:01:03.313:server.py:42]
MainProcess|Thread-10|I2015-12-15 13:01:03.316:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:01:03.319:registration_manager.py:90] Received server ack: response { success: true }
MainProcess|MainThread|I2015-12-15 13:01:33.312:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:01:33.312:server.py:42]
MainProcess|Thread-10|I2015-12-15 13:01:33.332:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:01:33.336:registration_manager.py:90] Received server ack: response { success: true }
D1215 13:01:35.731992000 4512583680 chttp2_transport.c:579] got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
MainProcess|Registration|E2015-12-15 13:01:37.006:registration_manager.py:96] Received RPC error: NetworkError
E1215 13:01:55.732847000 4472827904 tcp_client_posix.c:174] on_writable failed during connect
MainProcess|MainThread|I2015-12-15 13:02:03.316:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:02:03.316:server.py:42]
MainProcess|Thread-10|I2015-12-15 13:02:03.349:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:02:07.009:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:02:07.011:registration_manager.py:86] Sending Register RPC...
E1215 13:02:07.013125000 4520996864 tcp_client_posix.c:159] socket error: connection refused
E1215 13:02:07.013304000 4520996864 tcp_client_posix.c:159] socket error: connection refused
MainProcess|Thread-16|I2015-12-15 13:02:07.016:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
E1215 13:02:09.404239000 4520996864 tcp_client_posix.c:159] socket error: connection refused
E1215 13:02:12.861608000 4520996864 tcp_client_posix.c:159] socket error: connection refused
E1215 13:02:19.872420000 4520996864 tcp_client_posix.c:159] socket error: connection refused
E1215 13:02:29.565287000 4520996864 tcp_client_posix.c:159] socket error: connection refused
MainProcess|MainThread|I2015-12-15 13:02:33.318:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:02:33.318:server.py:42]
MainProcess|Registration|E2015-12-15 13:02:38.114:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:02:38.114:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:02:38.115:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-22|I2015-12-15 13:02:38.117:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
E1215 13:02:45.958413000 4546772992 tcp_client_posix.c:159] socket error: connection refused
MainProcess|MainThread|I2015-12-15 13:03:03.317:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:03:03.317:server.py:42]
MainProcess|Registration|E2015-12-15 13:03:09.212:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:03:09.212:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:03:09.213:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-28|I2015-12-15 13:03:09.215:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
E1215 13:03:11.672256000 4525203456 tcp_client_posix.c:159] socket error: connection refused
MainProcess|MainThread|I2015-12-15 13:03:33.320:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:03:33.320:server.py:42]
MainProcess|Registration|E2015-12-15 13:03:40.301:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:03:40.301:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:03:40.304:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-35|I2015-12-15 13:03:40.306:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
E1215 13:04:00.848211000 4546772992 tcp_client_posix.c:159] socket error: connection refused
MainProcess|MainThread|I2015-12-15 13:04:03.319:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:04:03.319:server.py:42]
MainProcess|Registration|E2015-12-15 13:04:11.363:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:04:11.363:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:04:11.364:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-40|I2015-12-15 13:04:11.367:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:04:33.321:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:04:33.322:server.py:42]
MainProcess|Registration|E2015-12-15 13:04:42.379:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:04:42.379:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:04:42.381:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-47|I2015-12-15 13:04:42.383:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
E1215 13:04:56.763825000 4525203456 tcp_client_posix.c:159] socket error: connection refused
MainProcess|MainThread|I2015-12-15 13:05:03.325:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:05:03.325:server.py:42]
MainProcess|Registration|E2015-12-15 13:05:13.399:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:05:13.399:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:05:13.401:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-52|I2015-12-15 13:05:13.403:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:05:33.327:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:05:33.327:server.py:42]
MainProcess|Registration|E2015-12-15 13:05:44.401:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:05:44.401:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:05:44.403:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-59|I2015-12-15 13:05:44.406:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:06:03.331:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:06:03.331:server.py:42]
MainProcess|Registration|E2015-12-15 13:06:15.412:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:06:15.413:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:06:15.414:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-64|I2015-12-15 13:06:15.416:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:06:33.334:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:06:33.334:server.py:42]
MainProcess|Registration|I2015-12-15 13:06:35.334:registration_manager.py:90] Received server ack: response { success: true }
MainProcess|Thread-40|I2015-12-15 13:06:35.353:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:07:03.337:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:07:03.337:server.py:42]
MainProcess|Registration|E2015-12-15 13:07:06.007:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:07:06.007:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:07:06.008:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-71|I2015-12-15 13:07:06.011:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:07:06.013:registration_manager.py:90] Received server ack: response { success: true }
MainProcess|MainThread|I2015-12-15 13:07:33.340:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:07:33.340:server.py:42]
MainProcess|Thread-52|I2015-12-15 13:07:33.346:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:08:03.343:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:08:03.343:server.py:42]
MainProcess|Registration|E2015-12-15 13:08:04.049:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:08:04.050:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:08:04.052:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-76|I2015-12-15 13:08:04.055:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:08:04.058:registration_manager.py:90] Received server ack: response { success: true }
MainProcess|MainThread|I2015-12-15 13:08:33.343:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:08:33.343:server.py:42]
MainProcess|Thread-52|I2015-12-15 13:08:33.357:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|MainThread|I2015-12-15 13:09:03.345:server.py:41] Sleeping 30.0 seconds ...
MainProcess|MainThread|I2015-12-15 13:09:03.345:server.py:42]
MainProcess|Registration|E2015-12-15 13:09:04.066:registration_manager.py:96] Received RPC error: CancellationError
MainProcess|Registration|I2015-12-15 13:09:04.066:registration_manager.py:82] Connecting to TaskQueue...
MainProcess|Registration|I2015-12-15 13:09:04.067:registration_manager.py:86] Sending Register RPC...
MainProcess|Thread-82|I2015-12-15 13:09:04.069:registration_manager.py:125] Sending status update: executor_info { address: "192.168.99.1" task_regex_matcher: ".*" capacity: 4 free: 4 }
MainProcess|Registration|I2015-12-15 13:09:04.072:registration_manager.py:90] Received server ack: response { success: true }

**Comment by shuowusc** [comment]
@soltanmm

**Comment by soltanmm** [comment]
It would be oodles of help if you happen to have some demonstration code of the faulty behavior for us to oggle over. In particular, I can't determine when in your logs the server starts back up.

If that isn't possible, running the code with the `GRPC_TRACE` environment variable set to `api`, i.e. `GRPC_TRACE=api your_example_here` and providing those logs could help as well.

**Comment by shuowusc** [comment]
Thanks @soltanmm I've found a bug in our own code that caused this. However GRPC_TRACE=api didn't work. =batch works. Not sure if something has changed. Anyways, I'll close this bug now.

**Comment by soltanmm** [comment]
@shuowusc `batch` was changed to `api` a few months ago. The lag is from updated gRPC core libraries not yet being packaged with Python gRPC, which will be the case soon!
