### ISSUE TITLE
Is grpc::CompletionQueue and grpc async API thread safe(C++)?

### ISSUE THREAD

**Issue by zhengcai** [grpc/grpc#4486]
In our project, we are using multiple threads and the grpc async APIs to implement an async-callback framework. We have a common CompletionQueue, say cq_, and a polling thread for it to dispatch callbacks once the result is ready:

Thread 1, the polling thread: {
  while (true) {
    ...
    cq_.Next(&got_tag, &ok);
    std::function<void()> callback = reinterpret_cast<std::function<void()>>(got_tag);
    callback();
    ...
  }
}

Then in other threads, we send out the requests asynchronously:

Thread X: {
  ...
  std::unique_ptr<grpc::ClientAsyncResponseReader<ResultType> > rpc(
      stub_->AsyncRequestMethod(&context, request, &cq_));
  rpc->Finish(&result, &status, reinterpret_cast<void *>(callback));
  ...
}

I was just wondering, are these async and CompletionQueue operations, like Next() and Finish(), thread safe? Do we need to guard them by some exclusive lock?

If they are not, I wonder how could we guard Next(), since it is blocking if there is not pending request? Because in that situation, it will never have the chance to release the lock, thus no other thread could ever acquire the lock and send out requests.

Thanks in advance

**Comment by vjpai** [comment]
Thanks for your question. These functions are thread safe. You don't need to wrap them in an additional mutex.

**Comment by zhengcai** [comment]
Thank you so much for confirming on this!
