### ISSUE TITLE
QPS Server does not support TLS.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc#449]
The QPS server [1] does currently not support TLS.

I am currently working on a Java implementation of the QPS server / client and we would ideally like to run benchmarks of the Java client with and without TLS against the C++ server.

[1] https://github.com/grpc/grpc/blob/master/test/cpp/qps/server.cc

**Comment by jtattermusch** [comment]
@vjpai i believe this one has been addressed?

**Comment by vjpai** [comment]
Addressed
