### ISSUE TITLE
Python installation is too complex

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4516]
The installation notes should read:

pip install grpcio

And nothing more.

Remove:
- homebrew dependency
- apt-get install steps

These additionally make it hard for other eggs to depend on us.

**Comment by soltanmm** [comment]
Does this include protoc and its plugins?

**Comment by ctiller** [comment]
This bug does, yes.

**Comment by soltanmm** [comment]
Closing in favor of #5980.
