### ISSUE TITLE
PHP installation is too complex

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4517]
The installation notes should read:

pecl install grpc

And nothing more.

Remove:
- homebrew dependency
- apt-get install steps

These additionally make it hard for other libraries to depend on us.

**Comment by stanley-cheung** [comment]
This is all done now. 

 * The PHP Pecl package now includes gRPC Core, boringssl, etc
 * PHP installation now got reduced to a single line `pecl install grpc-beta`
 * Removed dependencies on `libgrpc-dev` and `homebrew-grpc`
 * Added `config.m4` and `package.xml` to the `templates` directory
 * The 0.8.0 version has been released on Pecl https://pecl.php.net/package/gRPC (corresponding to core release 0.13)
 * The next version will be 0.14 to sync up with core.
 * Updated `README.md`

**Comment by bidekani** [comment]
`pecl install grpc-beta`  is not working for me.

`downloading grpc-1.12.0.tgz ...
Starting to download grpc-1.12.0.tgz (2,459,288 bytes)
.............done: 2,459,288 bytes
1155 source files, building
WARNING: php_bin c:\php\php-cgi.exe appears to have a suffix -cgi.exe, but confi
g variable php_suffix does not match
ERROR: The DSP grpc.dsp does not exist.`

I am using windows 7 and PHP 5.6.

**Comment by stanley-cheung** [comment]
The grpc extension was not supported on Windows and PHP 5.6 unfortunately. Only PHP 7.0+ on Windows

**Comment by bidekani** [comment]
tried Php 7.0.18 with windows 7 the same error .

**Comment by stanley-cheung** [comment]
For Windows, you can download a precompiled .dll of the gRPC extension from here: https://pecl.php.net/package/gRPC/1.12.0/windows This should work for 7.0.18
