### ISSUE TITLE
C# linux installation is too complex

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4519]
We definitely don't want an apt-get install step followed by something else.
Prefer packaging everything as a nuget package.

**Comment by cj525** [comment]
I have made some changes that may be relevant #4522 
It had crossed my mind to hard-link the elf version of libgrpc_csharp_ext in the same way the 32 bit version was, and now, to follow suit, the 64 bit version is in the referenced pull-request.  The drawback is that hardlinks don't permit debug vs release versions.  For Bigtable.NET I created a targets file which selects the correct version from grpc as a submodule using scripts to get everything built.  A targets in the nuget of Groc.Core could relieve me of the excessive submodule build scripting prerequisites, and if this is merged, allow me to drop the submodule in favor of nuget.

**Comment by jtattermusch** [comment]
This is currently being worked on. The most important PR has already been merged: https://github.com/grpc/grpc/pull/4730.

**Comment by jtattermusch** [comment]
It is now possible to generate new nuget packages using jenkins. The new packages should work out of the box on Windows, Mac and Linux without a need to preinstall anything. Closing this umbrella issue and will track minor things that need to be finished separately.
