### ISSUE TITLE
Python implementation can't handle remote services using non-standard error codes

### ISSUE THREAD

**Issue by inconshreveable** [grpc/grpc#4528]
Repro:
1. Create a remote service that returns a non-standard GRPC error
2. Call that service with a python stub

Result:
Enum exception

Expected:
No exception, the error code is passed through to the application layer on the `face.AbortionError`. Without this, there is no forward compatibility for new error codes and no support for user-defined error codes.

Example traceback:
```
Traceback (most recent call last):
  File "/equinox/venv/local/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 43, in _wrapping
    return behavior(*args, **kwargs)
  File "/equinox/venv/local/lib/python2.7/site-packages/grpc/_links/invocation.py", line 207, in _spin
    event = completion_queue.get(None)
  File "/equinox/venv/local/lib/python2.7/site-packages/grpc/_adapter/_intermediary_low.py", line 195, in get 
    ev = self._internal.next()
  File "/equinox/venv/local/lib/python2.7/site-packages/grpc/_adapter/_low.py", line 56, in next
    new_results = [r if r.status is None else r._replace(status=_types.Status(_types.StatusCode(r.status[0]), r.status[1])) for r in new_results]
  File "/equinox/venv/local/lib/python2.7/site-packages/enum/__init__.py", line 330, in __call__
    return cls.__new__(cls, value)
  File "/equinox/venv/local/lib/python2.7/site-packages/enum/__init__.py", line 642, in __new__
    raise ValueError("%s is not a valid %s" % (value, cls.__name__))
ValueError: 100 is not a valid StatusCode
```

**Comment by jcanizales** [comment]
I agree that nothing a server returns should make the client library behave unexpectedly / crash / etc.

Once the client library complies with that, I don't think forwarding a new error codes is important: The client application using the library won't know what to do with the error anyway, so handling will default to the same as when receiving an `INTERNAL` error. "The server isn't speaking my protocol == `INTERNAL`" is a good generic translation of error conditions.

For user-defined error codes, my experience is most of them fit as `FAILED_PRECONDITION` + extra details. In fact, there's no generic way to handle a `FAILED_PRECONDITION` error, it is by definition service-specific. But I've been hunting for use cases that don't fit that for more than a year now, and I'm very happy to learn of them :)

**Comment by inconshreveable** [comment]
Yep, this is an instance of wanting to pass back a more specific `FailedPrecondition`.

Please do not change unexpected codes to `INTERNAL`. I would much rather pass back a specific user-defined code than to munge the error message string looking for something. In an ideal world, we would be able to return structured errors via separate protobuf message description of an error and we wouldn't need this kind of signaling.

**Comment by jcanizales** [comment]
> In an ideal world, we would be able to return structured errors via separate protobuf message description of an error and we wouldn't need this kind of signaling.

Agreed, and you're able to do that already :) It's what the new versions of the Google APIs, that accept gRPC, do (I'm not sure whether / how well they document it). What we're doing is we put a serialized proto as a response trailer, with the trailer name being the fully-qualified name of the type (with a "-bin" suffix to mark the value as binary).

Both the server and client libraries should help with this, and wherever things can be smoothed, we should open an issue to address it (https://github.com/grpc/grpc-java/issues/681 is one example). I know e.g. that the Java library lets you register "parsers" for specific response header keys, this being one use case.

[These](https://github.com/google/googleapis/blob/master/google/rpc/error_details.proto) are protos that Google APIs use for common scenarios that aren't service-specific. E.g. for a `ServiceUnavailable` response one of the trailers can be called `google.rpc.retryinfo-bin` and its value a serialized `RetryInfo`.

**Comment by inconshreveable** [comment]
Interesting, I hadn't even considered doing that. Are there any code examples or docs around putting protobuf messages in the trailers in both client and server side code?

Are there plans to define structured error behavior in the protobuf definition file? It's kind of unfortunate if it's not in the `.proto` definition, considering that the whole point of protobuf RPC definitions is to make sure all clients use a guaranteed schema.

In that light, I'm totally okay not exposing non-standard error codes. I would make two suggestions though:

1. Use the error code `UNKNOWN`, seems more appropriate than `INTERNAL`.
2. Make sure the client can still get access to the unknown error code somehow. (maybe modify the error details to include that? unsure) Debugging behavior where you the client magically returns an `UNKNOWN` error code that the service didn't respond with is bound to be frustrating for whoever will run into it.

**Comment by jcanizales** [comment]
> Are there any code examples or docs around putting protobuf messages in the trailers in both client and server side code?

Not that I know, but there should. Let me open issues. There are samples for setting and reading trailers, generically, which should help you get going. But writing samples for this specific case is the first step towards making it easier.

> Are there plans to define structured error behavior in the protobuf definition file?

The idea has been raised in the past :) But we first want to have more real-world sample code using proto error details to support the design. See, removing or changing parts of the proto IDL has been an enormous pain in the past, so the threshold to add stuff is high.

> Use the error code `UNKNOWN`, seems more appropriate than `INTERNAL`.

LGTM; I've never seen client code handling `UNKNOWN`, `INTERNAL`, or `DATA_LOSS` differently, so I'm fine with either.

> Make sure the client can still get access to the unknown error code somehow.

Yep, great idea!

**Comment by inconshreveable** [comment]
Awesome, thanks for the helpful responses!

**Comment by jcanizales** [comment]
No problem!

This issue still has to remain open, for the client library to turn non-standard error codes into `UNKNOWN`, with an error message along the lines of "Unknown error code ${code} with message: ${message}".

**Comment by hsaliak** [comment]
@inconshreveable this should be fixed by the recent refactoring changes, could you be able to check? 
/cc @kpayson64

**Comment by kpayson64** [comment]
This is now handled at the c layer:
https://github.com/grpc/grpc/blob/master/src/core/lib/surface/call.c#L514

We don't do any special message formatting as is suggested here, I'm creating a lower priority issue to address that, #6883.
