### ISSUE TITLE
Revisit %ll  (long long)  printing for 64bit values

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4530]
%ll  printf string seems to be no good for printing 64bit values on windows.

We should consider introducing GPR_PRIi64, GPR_PRIu64 and GPR_PRIx64 macros to address this in a really portable way.

The 32bit versions of the macros might also be useful at times.

cc @ctiller  @nicolasnoble

**Comment by jtattermusch** [comment]
I might have unknowingly done some printf evil in #4397.

**Comment by ctiller** [comment]
We can just use PRIi64 etc... now.
