### ISSUE TITLE
Ruby executable `grpc_ruby_plugin` isn't created when installing grpc

### ISSUE THREAD

**Issue by bobbytables** [grpc/grpc#4542]
I'm attempting to generate ruby source files using the instructions on this page: http://www.grpc.io/docs/tutorials/basic/ruby.html

I've installed grpc on debian jessie using `apt-get install`, which according to [these instructions](https://github.com/grpc/grpc/blob/release-0_11/INSTALL), should give me the executable `grpc_ruby_plugin`.

The example in the ruby basics page has this instruction:

```sh
protoc -I ../../protos --ruby_out=lib --grpc_out=lib --plugin=protoc-gen-grpc=`which grpc_ruby_plugin` ../../protos/route_guide.proto
```

This fails because the `grpc_ruby_plugin` doesn't actually exist.

I have done the instructions inside of a `debian:jessie` Docker container:

```sh
docker run -ti registry.namely.tech/namely/protoc-ruby bash
root@74d60de09aec:/defs# which grpc_ruby_plugin
root@74d60de09aec:/defs#
```

So my question is, is that executable right? Are the docs stale?

I found this, however, I'm not familiar with Bazel: https://github.com/grpc/grpc/blob/12fa8c83aff22c84ee92ea00c79b2f6236c93d26/BUILD#L1425

Thoughts?

**Comment by bobbytables** [comment]
Further, I do have an executable called `grpc_ruby_interop_server`. Not sure if that's relevant though. Thanks!

**Comment by murgatroid99** [comment]
Currently, if you want to get `grpc_ruby_plugin`, you have to build and install grpc from source.

**Comment by Integralist** [comment]
Note: I installed grpc from source on a Mac and that plugin still doesn't exist

**Comment by kerinin** [comment]
Is this by design?  This seems really awkward

**Comment by murgatroid99** [comment]
This process will be made easier when #5981 is complete and we do another release.

**Comment by ctiller** [comment]
Duplicates #5981

**Comment by bobbytables** [comment]
Thanks!

**Comment by arschles** [comment]
I noticed that 0.14.1 is out, and I'm seeing this still not work. The following logs are in a `ruby:2.1` Docker docker container, but I've noticed the same behavior on OS X:

```console:
ENG000656:/ aaronschlesinger$ docker run --rm -it ruby:2.1 bash
root@e0cd480feb33:/# gem install grpc
Fetching: google-protobuf-3.0.0.alpha.5.0.5.1-x86_64-linux.gem (100%)
Successfully installed google-protobuf-3.0.0.alpha.5.0.5.1-x86_64-linux
Fetching: multi_json-1.12.1.gem (100%)
Successfully installed multi_json-1.12.1
Fetching: jwt-1.5.4.gem (100%)
Successfully installed jwt-1.5.4
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.2.gem (100%)
Successfully installed faraday-0.9.2
Fetching: addressable-2.4.0.gem (100%)
Successfully installed addressable-2.4.0
Fetching: signet-0.7.2.gem (100%)
Successfully installed signet-0.7.2
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: memoist-0.14.0.gem (100%)
Successfully installed memoist-0.14.0
Fetching: little-plugger-1.1.4.gem (100%)
Successfully installed little-plugger-1.1.4
Fetching: logging-2.1.0.gem (100%)
Successfully installed logging-2.1.0
Fetching: googleauth-0.5.1.gem (100%)
Successfully installed googleauth-0.5.1
Fetching: grpc-0.14.1-x86_64-linux.gem (100%)
Successfully installed grpc-0.14.1-x86_64-linux
13 gems installed
root@e0cd480feb33:/# which grpc_ruby_plugin
root@e0cd480feb33:/# 
```

Is there possibly a detail I've missed?

**Comment by arschles** [comment]
Also note that the same behavior occurs with the `grpc-tools` gem

**Comment by murgatroid99** [comment]
When you install `grpc-tools`, you get an executable called `grpc_tools_ruby_protoc_plugin.rb`, which is functionally equivalent to `grpc_ruby_plugin`.

**Comment by arschles** [comment]
@murgatroid99 thanks for letting me know. So, instead of this `protoc` flag:

```console
--plugin=protoc-gen-grpc=`which grpc_ruby_plugin`
```

What should be there?

**Comment by palkan** [comment]
@arschles This works for me

```sh
--plugin=protoc-gen-grpc=`which grpc_tools_ruby_protoc_plugin.rb`
```

**Comment by lumpidu** [comment]
Or simply use ```grpc_tools_ruby_protoc``` instead of ```protoc``` then you don't need to add ```--plugin``` at all

**Comment by arschles** [comment]
That works, thanks @lumpidu !
