### ISSUE TITLE
Write sample code for setting and reading error details

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4543]
The pattern we recommend for a server to specify details about an RPC error is to send them as binary protos in the response trailers. The convention for Google APIs is to use the fully-qualified type name (+ "-bin") for the trailer name.

Each language should have server and client example code for this use case. It's a specific case of writing and reading trailers, but because it's a use case we're promoting, the libraries should simplify it where possible. Writing these samples, apart from helping users, is a way for us to discover unnecessary friction like grpc/grpc-java#681.

It seems appropriate to use one of the [standard error detail types](https://github.com/google/googleapis/blob/master/google/rpc/error_details.proto) for the samples.

For more context, see the thread at https://github.com/grpc/grpc/issues/4528#issuecomment-165912657.

Tracking:
- [x] C++
- [ ] Python
- [ ] Go
- [ ] Java
- [ ] PHP
- [ ] Ruby
- [ ] C#
- [ ] Objective-C
- [ ] Node.js

CC @inconshreveable FYI.

**Comment by avinassh** [comment]
Hi, I am maintaining a repo https://github.com/avinassh/grpc-errors where I have examples of error handling in gRPC. I have been using gRPC (at work) close to a year and error handling and the docs related to them were really confusing. So, I ended up writing examples and then put them in the repo. It has all the languages examples (except Java). 

There is also a web page for easy access and brevity - http://avi.im/grpc-errors/

Is there any way I can contribute this to gRPC? Maybe we can add the link to the web page (or repo) somewhere on the gRPC page? Under [guides](https://grpc.io/docs/guides/) or [tutorials](https://grpc.io/docs/tutorials)

**Comment by avinassh** [comment]
@jcanizales  @stanley-cheung @nicolasnoble @jayantkolhe guys, any response to my previous message?

**Comment by muxi** [comment]
Thanks @avinassh this looks great! @hsaliak it looks like a fit to [this page](https://grpc.io/docs/guides/error.html) on grpc.io.

**Comment by avinassh** [comment]
yes!

**Comment by avinassh** [comment]
@muxi @hsaliak can I send a PR on that page? I guess it can be put under `Related Guides` in siderbar

**Comment by srini100** [comment]
I will take care of that and will also link it from grpc-contrib. Thanks for the reminder!

**Comment by srini100** [comment]
Closing as examples repo is linked above.
