### ISSUE TITLE
Python - Write sample code for setting and reading error details

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4545]
Python issue for #4543.

**Comment by jtattermusch** [comment]
We discussed this with @nathanielmanistaatgoogle and it should be easily doable with the existing Python metadata API.  No need to do this as part of GA.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle do you want this issue for GA?

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: [only to match the documentation that other languages are providing](https://github.com/grpc/grpc/issues/4543). If we aren't providing these examples across languages, then mailing list archives and unit tests will count as examples enough for Python.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle i think unit tests should be sufficient, see the comments here:
https://github.com/grpc/grpc-java/issues/1295

**Comment by jcanizales** [comment]
Not really fixed I'm afraid - see comments at #6955

**Comment by nathanielmanistaatgoogle** [comment]
This issue probably deserves a fresh assessment and a more detailed description.

**Comment by hsaliak** [comment]
Example repo is linked into from https://grpc.io/docs/guides/error.html So closing this issue.
