### ISSUE TITLE
Linking error against QT executable on Windows (MS VS 2013)

### ISSUE THREAD

**Issue by sabbakumov** [grpc/grpc#4551]
Follow all the instruction and build Google Protobuf and gRPC on MS VS 2013 to create .lib files.
Add .lib files to QT application (MS VC 2013).

You get the error:
error: LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease'

**Comment by larsonmpdx** [comment]
change the runtime library to match:
project properties - configuration properties - C/C++ - code generation - runtime library

normally Qt uses /MD because of LGPL, you can switch GRPC to match with no issues (I use it this way)
