### ISSUE TITLE
Compile error with MSYS2

### ISSUE THREAD

**Issue by sabbakumov** [grpc/grpc#4552]
Download and install MSYS2 as it's said in the documentation.

Try to make the sources:
make

Result: the make command fails at the file
https://github.com/grpc/grpc/blob/master/include/grpc/support/port_platform.h

#error Could not auto-detect platform

**Comment by abelwang1979** [comment]
I have the same errors. Any guys can answer our questions?

**Comment by sabbakumov** [comment]
I just switched to MS VS2013 and it works well.
MSYS2 support is still raw.

**Comment by abelwang1979** [comment]
Thanks

**Comment by arsanious** [comment]
Running into the same issue with MSYS2. Any ideas on how to get past this?

**Comment by DVLP** [comment]
same problem
