### ISSUE TITLE
Complete compilation compatibility matrix

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4572]
Across languages, across compiler versions, and across operating systems. Getting good coverage will be key to finishing our install story.

**Comment by jtattermusch** [comment]
#6366, #6365

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/1928

**Comment by jtattermusch** [comment]
#1929

**Comment by jtattermusch** [comment]
C/C++ is done (we have the all the version of gcc and clang we wanted running on PRs and on master).

C# is done (we have tests on windows, linux and mac)

Node is done (#6365)

For PHP, we are done. (we are running tests for Linux and Mac  (windows not required for GA, PHP 7 not required for GA).

Python: windows test are failing (there's a separate issue)

Ruby: we are not running windows tests at all.

**Comment by jtattermusch** [comment]
Relevant issues exist for missing pieces, I'll close this tracking issue as it is no longer useful.
