### ISSUE TITLE
[Ruby] Build with custom location cannot load successfully

### ISSUE THREAD

**Issue by zhuochun** [grpc/grpc#4577]
I am following https://docs.travis-ci.com/user/migrating-from-legacy/ to build grpc to `$HOME/grpc_build` and then `bundle install` with `gem 'grpc', '~> 0.11'`

My grpc build script and I have set global variable `GRPC_ROOT="$HOME/grpc"`

```
#!/bin/sh
set -e

# check to see if grpc folder is empty
if [ ! -d "$HOME/grpc_build/lib" ]; then
    git clone --depth 1 -b release-0_11_0 https://github.com/grpc/grpc.git "$HOME/grpc"
    cd "$HOME/grpc" && git submodule update --init
    make && make install prefix="$HOME/grpc_build"
else
    echo 'Using cached grpc directory.';
fi
```

bundle install grpc is succeed. But load grpc result in error:

```
Installing google-protobuf 3.0.0.alpha.4.0
Installing grpc 0.11.0
Your bundle is complete!
It was installed into ./vendor/bundle
rake aborted!
LoadError: libgrpc.so.0: cannot open shared object file: No such file or directory - /home/travis/build/example/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/grpc-0.11.0/grpc/grpc.so
/home/travis/build/example/vendor/bundle/ruby/2.1.0/gems/grpc-0.11.0/lib/grpc.rb:31:in `require'
/home/travis/build/example/vendor/bundle/ruby/2.1.0/gems/grpc-0.11.0/lib/grpc.rb:31:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
/home/travis/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
```

Some error messages in grpc build

```
[INSTALL] Installing libgpr.so.0.11.0.0
[INSTALL] Installing libgrpc.so.0.11.0.0
[INSTALL] Installing libgrpc_unsecure.so.0.11.0.0
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
[INSTALL] Installing public C++ headers
[STRIP]   Stripping libgrpc++.a
[STRIP]   Stripping libgrpc++_unsecure.a
[INSTALL] Installing C++ pkg-config files
[INSTALL] Installing libgrpc++.a
[INSTALL] Installing libgrpc++_unsecure.a
[STRIP]   Stripping libgrpc++.so
[STRIP]   Stripping libgrpc++_unsecure.so
[INSTALL] Installing libgrpc++.so.0.11.0.0
[INSTALL] Installing libgrpc++_unsecure.so.0.11.0.0
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
[INSTALL] Installing grpc protoc plugins
[INSTALL] Installing root certificates
We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.


Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

   make verify-install
```

**Comment by robert-w-gries** [comment]
Try `sudo make install prefix="$HOME/grpc_build"`

**Comment by zhuochun** [comment]
My goal is to use travis container-based infrastructure, which doesn't allow `sudo`. Seems `make install` is not achievable without `sudo`.

**Comment by ctiller** [comment]
We'll be removing the need to install grpc core for Ruby shortly (most of
it is already there at head), which should alleviate this problem for you.

**Comment by robert-w-gries** [comment]
@zhuochun [Here is my travis script that uses the Docker infrastructure](https://github.com/cisco/cisco-network-node-utils/blob/feature/grpc/.travis.yml#L11-L20).  The `release-0_12` branch is stable and lets you install the grpc core through `gem install --local grpc-0.11.1.gem`.

**Comment by murgatroid99** [comment]
First, it looks like that grpc build actually succeeded. The message at the end is just a warning, and does not actually affect the Ruby library.

Second, you are installing the grpc core, so setting `GRPC_ROOT` is not only unnecessary, but actively harmful. You should instead set `PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/grpc_build/lib/pkgconfig"`.

When you set `GRPC_ROOT` to a grpc clone *and* `pkg-config` does not find the existing grpc installation (which it would not do by default because of the custom install location), the Ruby library links against `$GRPC_ROOT/libs/opt/libgrpc`. Because you already ran `make`, it links with `libgrpc.so`. Then, when you try to run it, it cannot find `libgrpc.so` in the default shared library search path.

As ctiller mentioned, we will eliminate this problem in the next release (0.12)

**Comment by zhuochun** [comment]
Thanks @robert-w-gries and @murgatroid99 for the help. I will try release 0.12 and see how things go.

**Comment by murgatroid99** [comment]
Version 0.12.0 has been released, so this should no longer be an issue.

**Comment by zhuochun** [comment]
Brilliant! Thanks.

**Comment by zhuochun** [comment]
Tested working correctly with 0.12.0 in Travis container-based infrastructure :tada: . Thanks again.
