### ISSUE TITLE
Add sanity check for BoringSSL generated files

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4581]

**Comment by matt-kwong** [comment]
@nicolasnoble, can you clarify this request?

**Comment by nicolasnoble** [comment]
Basically, making sure that the files here: https://github.com/grpc/grpc/tree/master/src/boringssl that are automatically generated by generate_projects.sh are properly up to date with whichever version of the submodule we have.

**Comment by matt-kwong** [comment]
Nico, can you reassign to Bill? I don't know his GitHub ID or if he even joined the org yet. I think this issue is simple enough for him and it's a good way to understand code generation.
