### ISSUE TITLE
how to get request details?

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [grpc/grpc#4583]
Is there any chance to get client request info, just like http. you can get client ip, user agent, method etc..

I am working on an api request log, and i don't want to written same log in different method...

so can i do that?

**Comment by soltanmm** [comment]
The answer is generally 'yes', usually from the initial metadata of a call (and the http method is always POST), but how depends on the GRPC API you're working against. Which language are you using? [This link may also be helpful.](http://www.grpc.io/docs/)

**Comment by Mint-Zhao-Chiu** [comment]
i am using go

**Comment by jcanizales** [comment]
@iamqizhao

**Comment by jcanizales** [comment]
@Mint-Zhao-Chiu did you get the information you needed via other means?
