### ISSUE TITLE
How to set timeout of objective rpc request?

### ISSUE THREAD

**Issue by huangqingcheng** [grpc/grpc#4585]
I need to set timeout of each request, how can i do this in objective-c?

**Comment by wkubiak** [comment]
I'm also curious as to how to best handle timeouts on the iOS port. By default it seems that it's indefinite and no error is sprung.

Or maybe should it be tackled from the other side, ie. the server?

**Comment by jcanizales** [comment]
Hi guys, sorry for the delay replying!

There's an unimplemented feature request (https://github.com/grpc/grpc/issues/2114) for setting timeouts easily. Until it's implemented, it has to be done "the hard way", i.e., start a timeout yourself when starting the call, and have it cancel the request when it triggers. Which is probably a bit of a PITA.

For things like Internet becoming unreachable, I'm working this week on implementing https://github.com/grpc/grpc/issues/4064, which will take care of those conditions better than setting timeouts.

As Wojtek says, implementing the timeout in the server is another possibility (and it's probably a good idea anyway, no matter what's done on the client).

**Comment by sp71** [comment]
I am facing the same issue regarding unable to set the timeout. You mentioned we can cancel the GRPC request. How can we do so?

**Comment by jcanizales** [comment]
You can see an example here: https://github.com/grpc/grpc/blob/master/src/objective-c/tests/InteropTests.m#L269
It uses an RPC object as described [here](http://www.grpc.io/docs/tutorials/auth/oauth2-objective-c.html#create-an-rpc-object).

**Comment by sp71** [comment]
I tried compiling that project; however, the pod install fails with the following error message: 

Installing BoringSSL (2.0)
Installing Protobuf (3.0.0-alpha-4.1)
Installing RemoteTest (0.0.1)
[!] /bin/bash -c 
set -e
BINDIR=../../../../bins/$CONFIG
PROTOC=$BINDIR/protobuf/protoc
PLUGIN=$BINDIR/grpc_objective_c_plugin
$PROTOC --plugin=protoc-gen-grpc=$PLUGIN --objc_out=. --grpc_out=. *.proto

/bin/bash: line 5: ../../../../bins//protobuf/protoc: No such file or directory

**Comment by wkubiak** [comment]
@sp71 That example project is a bit old, so the environment vars may have changed since then. If it can't find protoc, check if it's really there where it expects it (the PROTOC environment var in the script). If it's at a different location in your setup, change appropriately.

Ideally, I wouldn't try and compile that example project. I'd just take the code shown which enables using timeouts and place it into your working code.

**Comment by jcanizales** [comment]
Yeah, that project, specifically, is for testing, and the script to run the tests sets `$CONFIG` and `$BINDIR` after compiling `protoc` and the test server from source. Let me create an issue to make its podspec default to whatever is installed on the machine if those variables aren't set.

**Comment by makdharma** [comment]
We should support setting a deadline or timeout as part of objc API.

**Comment by jcanizales** [comment]
Closing this issue because it's tracked [somewhere else](https://github.com/grpc/grpc/issues/4585#issuecomment-173685355).

**Comment by pbatg** [comment]
@jcanizales, did you mean to link to #9555?

**Comment by jcanizales** [comment]
I think it was #2114 .
