### ISSUE TITLE
Is the version of grpc on npm behind?

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#4618]
Sorry if this was intentional, but I noticed there's a tag for 0.12.0, but npm is stuck on 0.11.1: https://www.npmjs.com/package/grpc.

**Comment by murgatroid99** [comment]
There is not yet a tag for 0.12.0. There is a branch for 0.12, where we are finalizing the 0.12.0 release. We intend to tag and publish 0.12.0 soon.

**Comment by stephenplusplus** [comment]
I was sloppy by saying tag, I meant the package.json showing 0.12.0 for the version. Every project has their own workflow, sometimes the tag doesn't make it to GitHub. Nevermind me, thanks for clarifying.

**Comment by murgatroid99** [comment]
Version 0.12.0 has now been published to NPM.
