### ISSUE TITLE
Can I send requests to a streaming method in Objective-C?

### ISSUE THREAD

**Issue by juxingzhutou** [grpc/grpc#4636]
I search for a long time to find a api to do this, but I can't find it in tutorials, examples and .h files.

The result which I want is like following code in node.js

```
var grpc = require('grpc');
var protoDescriptor = grpc.load(__dirname + '/xxxx.proto');
var packageHandler = protoDescriptor.example;
var client = new packageHandler.AService('localhost:8088', grpc.Credentials.createInsecure());

var call = client.aMethod();

call.on('data', function (response) {
  console.log(response);
});

call.on('end', function () {
  console.log('Receive a end message.');
});

call.write({
  param1: "param1",
  param2: "param2"
});
```

**Comment by jcanizales** [comment]
Hi @juxingzhutou, all gRPC tutorials can be found on grpc.io. For Objective-C, this one shows how to make streaming calls: http://www.grpc.io/docs/tutorials/basic/objective-c.html

Please let us know if you have any problems. I'll be closing this issue for now.
