### ISSUE TITLE
Cleanup Ruby Linking a little

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4646]
We currently -lgrpc with -Llibs/opt. This means that if any build has previously made shared objects for grpc, Ruby prefers to link to them.

Instead, let's make the process a little more hermetic:
1. run make
2. copy libs/opt/libgrpc.a to (say) libs/opt/ruby-build/libgrpc.a
3. use -Llibs/opt/ruby-build

We could even add a 1b. delete everything in libs/opt/ruby-build.

This would finally solve an issue we've had with Ruby on the coverage builds:
https://grpc-testing.appspot.com/job/gRPC_coverage/1902/testReport/junit/(root)/tests/tools_run_tests_run_ruby_sh/

**Comment by murgatroid99** [comment]
This has been fixed on release-0_12 as part of bundling the C core with the Ruby library.
