### ISSUE TITLE
Python tests timing out on master

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#4650]
Courtesy of Twilight Sparkle:
https://grpc-testing.appspot.com/job/gRPC_master/14294/config=dbg,language=python,platform=linux/testReport/(root)/tests/py_test/
https://grpc-testing.appspot.com/job/gRPC_master/14294/config=opt,language=python,platform=linux/testReport/(root)/tests/py_test/

Those logs aren't very helpful. Any ideas? Resource starvation?

**Comment by soltanmm** [comment]
\>:-|

`SuccessfulStreamRequestStreamResponse` was never one of the ones to flake before AFAIK (neither was `testUnaryCallFuture`), so, I'm leaning towards this being an out-of-the-blue-one-time-thing.

Which leaves me still baffled, the tests shouldn't lock up like that.

Would you be okay with us decreasing individual RPC timeout constants s.t. tests instead start failing before the day the test started is up (iirc that's how long the timeouts currently are for expected successful RPCs: a day)? It *might* cause spurious failures, but I think I'd rather see a few more tracebacks than a handful of harness timeouts.

**Comment by nathanielmanistaatgoogle** [comment]
Yes, that would be fine. Now that the build is stable (I think? At least I thought so a few days ago?) I'd also like to tackle the flakiness that we've been seeing directly.

**Comment by soltanmm** [comment]
Remilestoned because we're simply not going to get to this over the weekend...

**Comment by dgquintas** [comment]
Seen again https://grpc-testing.appspot.com/job/gRPC_master/15215/config=opt,language=python,platform=macos/consoleText

**Comment by jtattermusch** [comment]
Seen again. 3 builds out of 4 (opt-linux, dbg-mac, opt-mac) have timed out.
https://grpc-testing.appspot.com/job/gRPC_master/15327

This is really getting out of hand, and we need to address this quickly.
@nathanielmanistaatgoogle @soltanmm  is one of you working on this currently?

**Comment by jtattermusch** [comment]
Bumping this to P0.

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: I believe we're both going to be shifting our focus to easing Python testing this week.

**Comment by pgrosu** [comment]
This is very exciting, and many thanks for all the hard work in helping the community and keeping on top of it!  

Somehow the timeout culprit could be in this piece of code from [_future_invocation_asynchronous_event_service.py](https://github.com/grpc/grpc/blob/26e4f5b1b6478809edc576646d3b4cd24562d549/src/python/grpcio/tests/unit/framework/interfaces/face/_future_invocation_asynchronous_event_service.py#L330-L342):

```Python
  def testCancelledStreamRequestStreamResponse(self):
    for (group, method), test_messages_sequence in (
        self._digest.stream_stream_messages_sequences.iteritems()):
      for test_messages in test_messages_sequence:
        requests = test_messages.requests()

        with self._control.pause():
          response_iterator = self._invoker.future(group, method)(
              iter(requests), test_constants.LONG_TIMEOUT)
          response_iterator.cancel()

        with self.assertRaises(face.CancellationError):
          next(response_iterator)
```

Let me know if there is anything I can help out with.

Thanks,
~p

**Comment by murgatroid99** [comment]
Seen again in 3/4 tests at https://grpc-testing.appspot.com/job/gRPC_master/15408

**Comment by jtattermusch** [comment]
I believe this was resolved by https://github.com/grpc/grpc/pull/5541.
