### ISSUE TITLE
Enable Windows builds of Python on master, PR's

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4655]

**Comment by soltanmm** [comment]
It's been enabled on master for a while now, and can be manually redirected to arbitrary branches if need be. If I misunderstood what the purpose of this issue is, please re-open.

**Comment by soltanmm** [comment]
Oh, I remember what this was for. Testing, not package builds.

**Comment by soltanmm** [comment]
Enabled on gRPC_master (not pull requests yet); let's see what happens...

**Comment by soltanmm** [comment]
Let's not see what happens; there doesn't even exist hooks anymore to run the Windows tests... which effectively makes this a duplicate of #5163.
