### ISSUE TITLE
How to get the stream id in grpc++

### ISSUE THREAD

**Issue by yaomthu** [grpc/grpc#4663]
I notice that you have defined the stream id in project /grpc/src/core/transport/chttp2. However, how can I get the stream id when I receive a request? Can you give me an example?
If getting stream id is not supported, is there any identifier that can distinguish requests on the same connection?

**Comment by ctiller** [comment]
The http2 stream id is abstracted away very early to make future different
transports easy to integrate.

There are various things you can do here. What do you need to identify the
requests for?

**Comment by yaomthu** [comment]
Since I want to log each request and response for further debugging. In our log, the request and response are in separated log item, so I need a id to map the request and response on the same connection. Do you have some suggestion?

**Comment by pszemus** [comment]
I think each request is processed in seperate thread so you can make use of a thread id ```  std::this_thread::get_id(); ```

**Comment by yaomthu** [comment]
The thread id will be re-used after a request is processed. We can't just use the thread id to map the response with its request.

**Comment by ctiller** [comment]
There's no grpc-native id that would particularly help you here.

I'd recommend attaching some metadata to your requests:

uint64_t id = generate_somewhat_unique_id(); // <-- you'll need to supply
this
ClientContext c;
c.AddMetadata("my_trace_id", as_string(id));
stub->Call(&c, ...);
