### ISSUE TITLE
SPEC: Consider making grpc.message support percent-encoded utf8

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc#4672]
The current strict mapping to ASCII makes grpc.message less useful as a human-consumed error message. Switching servers to produce percent-encoded utf-8 resolves this issue and poses little risk during the transition as these values are for informational purposes only

(a) Presenting some users with percent encoded output
(b) Clients which were percent-decoding these already would now double-decode

**Comment by bradfitz** [comment]
I'm confused what's going on here. Has a spec decision been made yet? I'm confused whether (a) and (b) represent pros, cons, trade-offs, undecided options...?

And if this isn't decided yet, why are there Java and Go bugs open tracking this one?

**Comment by louiscryan** [comment]
We've had a number of folks express dissatisfaction with the fact that they were strictly limited to ascii in the error message. Of the people I've talked to there was consensus that this seems reasonable, if there are objections I'm certainly interested in them

(a)  & (b) are just a quick analysis of the cons if we took this approach.

Happy to change this bug to sound a little less like a binding decision has been made

**Comment by carl-mastrangelo** [comment]
@ctiller fyi.

**Comment by dsymonds** [comment]
The spec (https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) already dictates using base64 in a bunch of places when things are non-ASCII. Surely `grpc.message` should be consistent with that?

**Comment by bradfitz** [comment]
Indeed. The spec also defines a convention for keys with a `-bin` suffix. I think `grpc-message` should be ASCII when it's ASCII, else it should be sent as `grpc-message-bin` and encoded/decoded as base64. If both are present, capable clients should prefer the `grpc-message-bin` version. The legacy `grpc-message` one can be present for compatibility in some butchered formed perhaps. (maybe % encoded, maybe with all non-ASCII stripped, maybe with a message "your client library is old; see grpc-message-bin")

**Comment by carl-mastrangelo** [comment]
<notAddingAnythingNew> @bradfitz I believe the original intent was to have error messages be as human readable as possible.  I also had brought up reusing the existing -bin encoding, but I can't remember the reason why it wasn't chosen.  

@ejona86 FYI

**Comment by louiscryan** [comment]
Primarily because using % encoding allowed us to maintain some semblance of
human readability for the messages even if the receiver didn't properly
decode.

**Comment by ejona86** [comment]
I'm not really sure I follow what the argument is for using `-bin`. If `grpc-message` uses percent encoding then it is ASCII. `-bin` is used for things like proto which are nothing close to text. Keeping text as mostly text seems like a Good Thing™, especially for something as important as `grpc-message`.

Is the argument a sort of conceptual argument where anything that is not ASCII in its native form should be in `-bin`? Or is the argument more of a practical argument like why are we needing to write more code instead of just making grpc-message a `-bin`?

**Comment by bradfitz** [comment]
I don't mind a bit more code. I was reacting to the ad hoc escaping mechanism which felt out of place, I guess. If this is decided, can somebody update http://www.grpc.io/docs/guides/wire.html ?

**Comment by louiscryan** [comment]
Unless there are other remaining objections I think this is largely settled. If needed we can add support for a -bin flavor later. Will update the doc and the IETF draft

**Comment by ctiller** [comment]
Fixed for wrapped languages in #8630
