### ISSUE TITLE
Python build from source: protobuf configure fails

### ISSUE THREAD

**Issue by awan1** [grpc/grpc#4675]
On Linux (a Google Compute Engine instance), following [the tutorial](https://github.com/grpc/grpc/blob/master/src/python/README.md). 

- Cloned repository
- `sudo pip install tox`
- Initialized submodules
- When running `make` in the repository directory, get (after the first time):

[MAKE]    Generating cache.mk
make: Circular /home/adrianwan/grpc/libs/opt/libboringssl.a <- /home/adrianwan/grpc/libs/opt/libboringssl.a dependency dropped.
[AUTOGEN] Preparing protobuf
/bin/sh: 1: autoreconf: not found
Makefile:1036: recipe for target 'third_party/protobuf/configure' failed
make: *** [third_party/protobuf/configure] Error 127

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle Should we be adding the build-time-dependencies of our dependencies to our documentation, or linking to those dependencies' documentation?

(although, this particular dependency at build-time for gRPC core should become a non-issue due to #4457 soon)

**Comment by awan1** [comment]
#4457 was merged into master but grpc `make` still fails, with the same error. 

Any way to manually provide the protobuf autoreconf as a work-around for now?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: quite possibly. I suspect we'll wind up with something along the lines of "building gRPC Python from source requires all of gRPC Core's build dependencies + all of protobuf's build dependencies + this here list of Python dependencies". That would be workable, wouldn't it?

If the lay of the land for alpha was that we had very similar stories for working from source versus working from the distributed package but the same for GA was that working from source required a lot of tooling whereas working with the package is just a single `pip install`, that would be movement in the right direction, wouldn't it?

**Comment by ctiller** [comment]
@nathanielmanistaatgoogle: I think that list is what we end up with for working from source, and I think that's ok with me.

protoc is still ever so slightly problematic, but there is a plan for it. Let's sync up on execution this week.

The simple form of the plan is:

We build a new python module 'grpcio-protoc'.
Within the egg containing this module (the egg might just be grpcio) we include {protoc, grpc_python_plugin} binaries for {linux, mac, windows} x {32-bit, 64-bit}.
The module itself will look something like:

```python
import os
import platform
import sys

my_path = os.path.dirname(sys.argv[0])
system_name = platform.system() # Linux, Windows, etc
machine_name = platform.machine()
os.execv('%s/%s-%s/protoc" %  (my_path, system_name, machine_name), sys.argv[1:])
```

The extended form is:

As above, but with the protoc and grpc_python_plugin modules separated along the protobuf/grpc boundaries.

**Comment by soltanmm** [comment]
@awan1 Oh, I meant that it'd be fixed via invoking `make` no longer being necessary. Except that the aforementioned PR missed a spot (by failing instead of warning on a missing protobuf dependency), and *that*'ll be addressed in #4684. Sorry about the confusion!

Although, to be clearer still, none of that addresses the protoc plugin story, which we'll be addressing one way or another soon.

**Comment by soltanmm** [comment]
@ctiller @nathanielmanistaatgoogle Just a note: [we've considered adding protoc plugin stuff into a PyPI package before](https://github.com/grpc/grpc/issues/1149#issuecomment-126441367). I'm for it; it also gives us a meaningful place to provide an accessible custom `distutils`/`setuptools` command to generate gRPC `.py`s from `.proto`s.

That said, I'm a bit iffy on dropping in executables and circumventing the usual PyPI distribution of sources or wheels from `setuptools`<sup>1</sup>.

<sup>1</sup><sub><sup>Wheels replaced eggs as the preferred package format for binaries a while ago.</sup></sub>

**Comment by awan1** [comment]
Thanks to @soltanmm's advice, I fixed this by building autoconf from source, using [this gist comment](https://gist.github.com/jellybeansoup/4192307#gistcomment-957137):

```
curl -OL http://ftpmirror.gnu.org/autoconf/autoconf-latest.tar.gz
tar xzf autoconf-latest.tar.gz
cd autoconf-*
./configure --prefix=/usr/local
make
sudo make install
cd ..
rm -r autoconf-*
```

I didn't think to check until after but apparently `brew install autoconf automake` should've done the trick too. 

Either way, `make` in the `grpc` directory succeeds now. And when `protoc` and `protobuf` are included in core (did I get that right?), this won't be a problem, I believe. 

I'll close this for now, as `make` succeeds.

**Comment by soltanmm** [comment]
> And when protoc and protobuf are included in core (did I get that right?), this won't be a problem, I believe.

Well, not quite. We're thinking about including `protoc` and gRPC's `protoc` plugins in another Python package, and protobuf in Python may become an optional dependency to gRPC Python. The gRPC core is getting integrated into gRPC's Python package come 0.12.
