### ISSUE TITLE
Add support for abstract unix domain sockets

### ISSUE THREAD

**Issue by duggelz** [grpc/grpc#4677]
Unix domain sockets have a convention that a leading @ in the socket name denotes an address in the abstract namespace.  This doesn't seem to work in either client or server.

Example:

```
builder.AddListeningPort("unix:@foo", grpc::InsecureServerCredentials());
```

What should happen:

```
Server opens abstract unix domain socket with name 'foo'
```

What actually happens:

```
Server opens non-abstract unix domain socket with name '@foo' in current working directory
```

GRPC 0.11.1

**Comment by ctiller** [comment]
Interesting. Can you site any documentation describing this?

**Comment by duggelz** [comment]
This link gives a good overview:  http://unix.stackexchange.com/a/206395

Stubby 1 and 2 support this, and it's used internally quite a bit, because it's so handy.  Unfortunately, some digging reveals it to be non-portable - only Linux supports abstract unix domain sockets, not BSD, Windows or anything else.

**Comment by ctiller** [comment]
Seems worth supporting, though I wish there were a syntax that didn't
collide with standard filenames (unix:foo?abstract=1 maybe), though I could
be convinced that staying with convention is important enough.

It shouldn't be huge to do, but I'd like to cleanup our server name
resolution path a little first so that it this doesn't need to happen in
two different places.

**Comment by duggelz** [comment]
Great!

The non-colliding alternative to '@' is to natively support target names with embedded NUL characters.  The client code would pass in something like std::string{'\0', 'f', 'o', 'o'}.  But a brief look at the C core component shows that to be a non-starter: It uses NUL-terminated strings, rather than C++-style strings with explicit length.

**Comment by ctiller** [comment]
We also using uri syntax for names. So... %00?

**Comment by ctiller** [comment]
(We still need to get that the percent decoding written)

**Comment by duggelz** [comment]
"unix:%00foo" would be excellent.

**Comment by alexandnpu** [comment]
@duggelz @ctiller , for me, using "unix:%00foo" would not be good, which makes grpc inconsistent between different programming languages.

I have a task for java and python.
For java part, the grpc-java can use the abstract namespace in unix domain socket, thanks to netty.

I've tried grpc-python on

```
grpcio==1.3.5
grpcio-tools==1.3.5
protobuf==3.3.0
```

for

```
unix:%00foo
unix:\\0foo
unix:\0foo  # this one fails
```

They are not abstract namespace.

As the java world can support the abstract namesapce, python world can do it too!
(I haven't look into the golang world)

I haven't got the chance to look into the code in grpc for python. So sorry that if I miss something.
