### ISSUE TITLE
Error: Invalid cert chain file

### ISSUE THREAD

**Issue by zhengcai** [grpc/grpc#4689]
Hi,

I was trying to set up a secure connection between the client and server, by using the provided credential files (from src/core/tsi/test_creds/ and etc/roots.pem) in release 0.11.0:

Client:
```
grpc::SslCredentialsOptions ssl_opts = {"./root.pem", "./client.key", "./client.pem"};
shared_ptr<Channel> channel = grpc::CreateChannel("192.168.130.130", grpc::SslCredentials(ssl_opts));
```

Server:
```
grpc::SslServerCredentialsOptions::PemKeyCertPair pkcp = {"./server1.key", "./server1.pem"};
grpc::SslServerCredentialsOptions ssl_opts;
ssl_opts.pem_root_certs = "./roots.pem";
ssl_opts.pem_key_cert_pairs.push_back(pkcp);
builder.AddListeningPort(server_address, grpc::SslServerCredentials(ssl_opts));
```

However, on both sides, I am getting this error:

E0112 11:33:02.223279961   10320 ssl_transport_security.c:557] Invalid cert chain file.
E0112 11:33:02.223386003   10320 security_connector.c:610]   Handshaker factory creation failed with TSI_INVALID_ARGUMENT.

So I was just wondering, what did I do wrong using these credentials, and how should I fix this problem?

Thank you so much in advance,

**Comment by murgatroid99** [comment]
You have to provide the contents of the files, not the file names.

**Comment by zhengcai** [comment]
Great! After I using the contents, it did not generate invalid chain file error.

However, I start to get this error on my server:

No match found for server name: 192.168.130.134.

I have tried both server1.pem and badserver.pem, both with the same error. I have also tried regenerate badserver.pem with 192.168.130.134 as the common name, but still the same error.

Any clue on this?

Thanks

**Comment by Purveyor** [comment]
Hi zhengcai, 

Did you figure out a fix or reason for the issue? I have compiled the server and client yesterday and see the same error on server side console whenever client tried to communicate with the server.

Thanks!

**Comment by zhengcai** [comment]
Unfortunately no:( We decided to just establish the grpc connection within a vpn channel, to address the security concern.

**Comment by jboeuf** [comment]
We currently do not support IP addresses for SSL certs. You will need a DNS name in your CreateChannel call as well as having this DNS name being on the server cert.

Hope this helps.

**Comment by sururami** [comment]
I'm not sure but I thnik in order to communicate TLS, you should correct the word 'grpc' to 'grpcs'...maybe
