### ISSUE TITLE
Install friction log: Python, Linux

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4692]
@soltanmm - please a stage Python Linux package from master and reassign this (with instructions) to @hsaliak 

@hsaliak - please try out the instructions and produce a friction log that we can use for filing and prioritizing bugs

**Comment by soltanmm** [comment]
I'd like for #4684 to go through first, as it alleviates a few problems I'm already aware of.

**Comment by soltanmm** [comment]
@hsaliak 
[This](https://testpypi.python.org/pypi/grpcio/0.12.0b5) is the version we'd like to check.
Given that it's staged on TestPyPI, you *will* hit the following issues:
* `enum34` is NOT on TestPyPI; it will need to be `pip install`d from the PyPI
* `futures` is NOT on TestPyPI; it will need to be `pip install`d from PyPI

And miscellaneous:
* sundry known issues related to how we've not decided yet on how to package Python's `protoc` plugin and `protoc`
  * `protobuf` isn't currently listed as an `extra`, but this is more or less subsumed by the above point

Installation:
* `virtualenv env` provides a python virtual environment to use (unless you want to install to the system)
  * may require `pip install virtualenv`
    * may require installing `sudo apt-get install python-pip`
* `./env/bin/activate`
* `pip install -i https://testpypi.python.org/pypi grpcio` (the `-i ...` targets TestPyPI as opposed to PyPI)
  * if installing into a virtualenv, will require `pip install enum34 futures` (because those two aren't on TestPyPI)
* ... do whatever you need to do in the virtualenv?

**Comment by soltanmm** [comment]
Assuming you're doing system-wide changes (to make things simpler):
* `pip install enum34 futures` <-- to deal with TestPyPI absentees
* `pip install -i https://testpypi.python.org/pypi grpcio`

**Comment by ctiller** [comment]
@jgeewax

**Comment by ctiller** [comment]
@hsaliak - it'd be good to get some priority on this today, so that we can make cleanups tomorrow ready for Thursday's stand up.

**Comment by hsaliak** [comment]
@ctiller I plan to work on this issue today and will update the bug with my findings.

**Comment by soltanmm** [comment]
@hsaliak I messed up the instructions for older versions of `pip`. With version 1.5.6, one must specify the `--pre` flag to be able to catch alpha and beta versions of a release (those with an `aX` or `bX` suffices).

The revised instructions are:

* `pip install enum34 futures` <-- to deal with TestPyPI absentees
* `pip install -i https://testpypi.python.org/pypi --pre grpcio`

**Comment by jgeewax** [comment]
OK -- just gave this a try on Ubuntu 14.04 (LTS), which failed. The expected process I expected was:

```
# apt-get update
# apt-get upgrade
# apt-get install python-pip
# pip install enum34 futures
# pip install -i https://testpypi.python.org/pypi grpcio==0.12.0b6

... snip ...

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -I./src/python/grpcio/ -I./include -I./ -I./third_party/boringssl/include -I/usr/include/python2.7 -c ./src/python/grpcio/grpc/_cython/cygrpc.c -o build/temp.linux-x86_64-2.7/./src/python/grpcio/grpc/_cython/cygrpc.o -pthread -std=gnu99

./src/python/grpcio/grpc/_cython/cygrpc.c:36:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_jjg/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sRIQX4-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_jjg/grpcio
Storing debug log for failure in /home/jjg/.pip/pip.log
```

Tried installing `python-dev`, error'd again:

```
# apt-get install python-dev
... snip ...
In file included from ./src/core/client_config/resolver.h:37:0,

                 from ./src/core/channel/client_channel.h:38,

                 from src/core/client_config/subchannel.c:41:

./src/core/client_config/client_config.h:43:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 grpc_client_config *grpc_client_config_create();

 ^

src/core/client_config/subchannel.c:275:17: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 static uint32_t random_seed() {

                 ^

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -I./src/python/grpcio/ -I./include -I./ -I./third_party/boringssl/include -I/usr/include/python2.7 -c src/core/client_config/subchannel_factory.c -o build/temp.linux-x86_64-2.7/src/core/client_config/subchannel_factory.o -pthread -std=gnu99

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -I./src/python/grpcio/ -I./include -I./ -I./third_party/boringssl/include -I/usr/include/python2.7 -c src/core/client_config/uri_parser.c -o build/temp.linux-x86_64-2.7/src/core/client_config/uri_parser.o -pthread -std=gnu99

In file included from src/core/client_config/uri_parser.c:38:0:

./include/grpc/support/alloc.h:66:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 gpr_allocation_functions gpr_get_allocation_functions();

 ^

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -I./src/python/grpcio/ -I./include -I./ -I./third_party/boringssl/include -I/usr/include/python2.7 -c src/core/compression/algorithm.c -o build/temp.linux-x86_64-2.7/src/core/compression/algorithm.o -pthread -std=gnu99

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -I./src/python/grpcio/ -I./include -I./ -I./third_party/boringssl/include -I/usr/include/python2.7 -c src/core/compression/message_compress.c -o build/temp.linux-x86_64-2.7/src/core/compression/message_compress.o -pthread -std=gnu99

In file included from src/core/compression/message_compress.c:38:0:

./include/grpc/support/alloc.h:66:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 gpr_allocation_functions gpr_get_allocation_functions();

 ^

src/core/compression/message_compress.c:41:18: fatal error: zlib.h: No such file or directory

 #include <zlib.h>

                  ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_jjg/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t96u8J-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_jjg/grpcio
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 74: ordinal not in range(128)
```

Not entirely sure what's up here -- any thoughts?

**Comment by soltanmm** [comment]
Huh, I thought `python-pip` depended on `python-dev` (though to be fair that then would've left everyone who installed `pip` via `easy_install` instead out in the rain)... And I'd forgotten that zlib wasn't a totally ubiquitous thing existing everywhere. Amended:

* `apt-get install python-dev`
* `apt-get install zlib1g-dev`
* pip install enum34 futures
* pip install -i https://testpypi.python.org/pypi --pre grpcio

**Comment by hsaliak** [comment]
I tried this on a wheezy machine. 
Here are the abridged findings and steps I needed to do.
```
apt-get install zlib1g-dev (along with the rest of the deps outlined in our INSTALL file)
apt-get install python-dev
apt-get install zlib1g-dev
pip install enum34 futures
pip install -i https://testpypi.python.org/pypi --pre grpcio
```
Additional step, before client/server code can be run
```
pip install protobuf==3.0.0-alpha-2   
```

**Comment by cjrd** [comment]
I've followed these install instructions and I receive the following error when I run `from grpc.beta import implementations`

```bash
In [1]: from grpc.beta import implementations
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ead03b4d7be2> in <module>()
----> 1 from grpc.beta import implementations

/usr/local/lib/python2.7/dist-packages/grpc/beta/implementations.py in <module>()
     36 
     37 # cardinality and face are referenced from specification in this module.
---> 38 from grpc._adapter import _intermediary_low
     39 from grpc._adapter import _low
     40 from grpc._adapter import _types

/usr/local/lib/python2.7/dist-packages/grpc/_adapter/_intermediary_low.py in <module>()
     55 import enum
     56 
---> 57 from grpc._adapter import _low
     58 from grpc._adapter import _types
     59 

/usr/local/lib/python2.7/dist-packages/grpc/_adapter/_low.py in <module>()
     32 
     33 from grpc import _grpcio_metadata
---> 34 from grpc._cython import cygrpc
     35 from grpc._adapter import _implementations
     36 from grpc._adapter import _types

ImportError: cannot import name cygrpc
```


If I `ls /usr/local/lib/python2.7/dist-packages/grpc/_cython/`, I see
```bash
ls /usr/local/lib/python2.7/dist-packages/grpc/_cython/
_cygrpc  __init__.py  __init__.pyc
```

It looks like `cygrpc` is missing. Any ideas what went wrong?

**Comment by soltanmm** [comment]
@cjrd Aye, that was fixed on master in the last week or so. I'll update the package on testpypi tomorrow for ya.

**Comment by cjrd** [comment]
@soltanmm brilliant, thank you. I'll let you know if I can install

**Comment by soltanmm** [comment]
@cjrd Ah, totally forgot about this. Updating now...

**Comment by jgeewax** [comment]
OK, here's my latest status on Ubuntu 15.10

```
# apt-get update && apt-get upgrade
# apt-get install python-dev zlib1g-dev python-pip
# pip install --upgrade enum34 futures
```

I expect that's... "good enough" ?

I had some trouble with Type PyPI due to HTTPS stuff, but dropping to regular HTTP got things moving.

```
# pip install -i http://testpypi.python.org/pypi grpcio==0.12.0b7 
```

There's a ton of compiling (gcc stuff) which doesn't (to me) sound like "precompiled binaries"... but it ends successfully.

Then, sadness?

```
# python -c "import grpcio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named grpcio
```

And that's when I realize that we call the thing `grpcio` on PyPI, but importing it ... isn't the same...

```
# python -c "import grpc"
```

Can we consider calling this google.grpc, google-grpc, grpc-google, etc? So that the install is `pip install google-grpc` and then the import is (as one would expect) `import grpc` ?

**Comment by soltanmm** [comment]
An aside: the most recent uploaded distribution on testpypi (version 0.12.0b8) is broken (see #5072). Hiding it.

**Comment by soltanmm** [comment]
@jgeewax They're not precompiled because at *current time* (this will change in the future) getting the precompiled stuff requires passing a flag: `--use-grpc-custom-bdist`. So, for `pip`, that'd be:

`pip install grpcio --install-option="--use-grpc-custom-bdist"`

It'll be available as soon as we've uploaded again.

**Comment by jgeewax** [comment]
OK, but that won't be the actual install command right? It'll be just `pip install grpcio` and that magical command will be added auto-magically?

**Comment by soltanmm** [comment]
@jgeewax Yes; I guess the concern is that you'd want that switch ASAP while I'm holding out for the sake of making the development process a smidgen easier. You'd want this by the next minor release?

**Comment by ctiller** [comment]
I have a PR out that addresses this.

**Comment by soltanmm** [comment]
I believe that @ctiller, @hsaliak, @jtattermusch and I have gotten around to addressing all the concerns that have been raised for this pass. Anything further *probably* should be its own issue at this point.
