### ISSUE TITLE
Install friction log: Ruby, Linux

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4698]
@murgatroid99 - please a stage Python Linux package from master and reassign this (with instructions) to @rok987

@rok987 - please try out the instructions and produce a friction log that we can use for filing and prioritizing bugs

**Comment by murgatroid99** [comment]
@rok987 I emailed you the instructions

**Comment by ctiller** [comment]
@rok987 it'd be good to get some priority on this today, to allow the team to make adjustments tomorrow, ready for Thursdays stand up.

**Comment by rok987** [comment]
As a side note. Here is what I got from running this on Mac.

Result of running "sudo gem install grpc"
Fetching: google-protobuf-3.0.0.alpha.5.0.gem (100%)

Building native extensions.  This could take a while...

ERROR:  Error installing grpc:

ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb

creating Makefile

make "DESTDIR="

make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14/ruby/config.h', needed by `protobuf.o'.  Stop.


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/google-protobuf-3.0.0.alpha.5.0 for inspection.

Results logged to /Library/Ruby/Gems/2.0.0/gems/google-protobuf-3.0.0.alpha.5.0/ext/google/protobuf_c/gem_make.out

**Comment by rok987** [comment]
Output when installing on Ubuntu (no errors):

Fetching: google-protobuf-3.0.0.alpha.5.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed google-protobuf-3.0.0.alpha.5.0
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.2.gem (100%)
Successfully installed faraday-0.9.2
Fetching: jwt-1.5.2.gem (100%)
Successfully installed jwt-1.5.2
Fetching: little-plugger-1.1.4.gem (100%)
Successfully installed little-plugger-1.1.4
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: logging-2.0.0.gem (100%)
Successfully installed logging-2.0.0
Fetching: memoist-0.14.0.gem (100%)
Successfully installed memoist-0.14.0
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: addressable-2.4.0.gem (100%)
Successfully installed addressable-2.4.0
Fetching: signet-0.7.2.gem (100%)
Successfully installed signet-0.7.2
Fetching: googleauth-0.5.1.gem (100%)
Successfully installed googleauth-0.5.1
Building native extensions.  This could take a while...
Successfully installed grpc-0.12.0
Parsing documentation for google-protobuf-3.0.0.alpha.5.0
Installing ri documentation for google-protobuf-3.0.0.alpha.5.0
invalid options: -SHN
(invalid options are ignored)
Parsing documentation for multipart-post-2.0.0
Installing ri documentation for multipart-post-2.0.0
Parsing documentation for faraday-0.9.2
Installing ri documentation for faraday-0.9.2
Parsing documentation for jwt-1.5.2
Installing ri documentation for jwt-1.5.2
Parsing documentation for little-plugger-1.1.4
Installing ri documentation for little-plugger-1.1.4
Parsing documentation for multi_json-1.11.2
Installing ri documentation for multi_json-1.11.2
Parsing documentation for logging-2.0.0
Installing ri documentation for logging-2.0.0
Parsing documentation for memoist-0.14.0
Installing ri documentation for memoist-0.14.0
Parsing documentation for os-0.9.6
Installing ri documentation for os-0.9.6
Parsing documentation for addressable-2.4.0
Installing ri documentation for addressable-2.4.0
Parsing documentation for signet-0.7.2
Installing ri documentation for signet-0.7.2
Parsing documentation for googleauth-0.5.1
Installing ri documentation for googleauth-0.5.1
Parsing documentation for grpc-0.12.0
Installing ri documentation for grpc-0.12.0
Done installing documentation for google-protobuf, multipart-post, faraday, jwt, little-plugger, multi_json, logging, memoist, os, addressable, signet, googleauth, grpc after 4 seconds
13 gems installed

**Comment by murgatroid99** [comment]
That looks like success.

**Comment by hsaliak** [comment]
@rok987  Could we also verify that this results in a valid install that can run the helloworld sample?
I ran into some problems on the python that were only discovered when I ran the sample. 

https://github.com/grpc/grpc/tree/master/examples/ruby
