### ISSUE TITLE
Install friction log: Node, Linux

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4699]
@murgatroid99 - please a stage Node Linux package from master and reassign this (with instructions) to @Zinuga

@Zinuga - please try out the instructions and produce a friction log that we can use for filing and prioritizing bugs

**Comment by murgatroid99** [comment]
@Zinuga I emailed you the instructions

**Comment by ctiller** [comment]
@zinuga - it'd be good to get some priority on this today, to allow the team to make adjustments tomorrow, ready for Thursday's standup.

**Comment by zinuga** [comment]
@ctiller worked fine for me. Only issue was pointing node runtime to nodejs in debian linux.

**Comment by hsaliak** [comment]
@murgatroid99 could you please persist the instructions that were mailed into this bug?

@zinuga Could you confirm that you ran an example client/server? Also, exact steps you did to point the node runtime to nodejs?

**Comment by murgatroid99** [comment]
I only had to email special instructions because at the time, the new package with the relevant changes had not yet been published.
