### ISSUE TITLE
node.js grpc defaults to CamelCase with an initial capital for rpc calls

### ISSUE THREAD

**Issue by rcordeau** [grpc/grpc#4706]
I have a .proto file that defines a service as such:
service BoardManager {

    // Check whether a target board is available
    rpc boardAvailable (StandardRequest) returns (StandardResponse);

    // Find out the available device ids for this target board
    rpc GetState (StandardRequest) returns (StateResponse);
....
}
Other language implementation of grpc will allow for an rpc call of either boardAvailable() or GetState(), however, node.js returns an error on the call to boardAvailable saying "Method not found: BoardManager/BoardAvailable".  If I redefine the rpc as "BoardAvailable" in the .proto file, then node.js is happy.  I understand that the Google style guide calls out that there should be a beginning capital letter, but it isn't required and the other languages handle the case just fine.

**Comment by murgatroid99** [comment]
Thank you for your report. To be honest, I don't actually remember why I did that in the first place. It doesn't actually help anything.

**Comment by rcordeau** [comment]
No worries. The style guide does call out that methods and services should start with a capital letter, so I can understand if you were trying to enforce this.
