### ISSUE TITLE
Google gRPC (C++) building under VisualStudio 2013. Link errors (Fixed)

### ISSUE THREAD

**Issue by jackersson** [grpc/grpc#4707]
[Here](http://stackoverflow.com/questions/34748494/google-grpc-c-building-under-visualstudio-2013-link-errors) I had a problem with building HelloWord gRPC sample under VisualStudio 2013. 

The correct options to compile my project are:

(New project created in vsprojects/Solution gRPC (bad idea, but it easily can be moved)). All packages are restored with Nuget.

### Includes
$(SolutionDir)\..
$(SolutionDir)\..\include
$(SolutionDir)\..\third_party\protobuf\src
$(SolutionDir)\packages\grpc.dependencies.zlib.1.2.8.10\build\native\include
$(SolutionDir)\packages\grpc.dependencies.openssl.1.0.204.1\build\native\include
$(SolutionDir)\packages\gflags.2.1.2.1\build\native\include
$(SolutionDir)\packages\gtest.1.7.0.1\build\native\include

### Additional Library Directories
$(SolutionDir)\$(Configuration) // here I put libprotobuf.lib, grpc.lib, gpr.lib, grpc++.lib
$(SolutionDir)\packages\gflags.2.1.2.1\build\native\$(Platform)\$(PlatformToolset)\static\Lib
$(SolutionDir)\packages\gtest.1.7.0.1\build\native\lib\static\$(Configuration)
$(SolutionDir)\packages\grpc.dependencies.zlib.1.2.8.10\build\native\lib\$(PlatformToolset)\$(Platform)\$(Configuration)\static\cdecl
$(SolutionDir)\packages\grpc.dependencies.openssl.1.0.204.1\build\native\lib\$(PlatformToolset)\$(Platform)\$(Configuration)\static

### Additional Dependies
libeay32.lib
ssleay32.lib
zlib.lib
gflagsd.lib
gtestd.lib
libprotobuf.lib
ws2_32.lib
grpc.lib
gpr.lib
grpc++.lib

Notice that after adding grpc++.lib everything become great.

### Additional Info
Issue "Please compile grpc with _WIN32_WINNT of at least 0x600 (aka Windows Vista)"
Fix - Define _WIN32_WINNT with corresponding OS value (The value can be found [Here](https://msdn.microsoft.com/en-us/library/6sehtctf.aspx)

Issue " error C4996: 'std::_Copy_impl': Function call with parameters that may be unsafe...'"
Fix - Use _SCL_SECURE_NO_WARNINGS in Preprocessor

While compiling protobuf and grpc try to watch at corresponding valued for (MT - MT, MD-MD, MTd-MTd and so on)

**Comment by nicolasnoble** [comment]
So this is more of a guide to build the example under Visual Studio than anything else. I'll close this, hoping people googling for that will find that.
