### ISSUE TITLE
response time high on Node.js

### ISSUE THREAD

**Issue by jyang** [grpc/grpc#472]
Testing the plain http stack of Node.js, where client and server are on the same fast workstation, shows that average response time is <200us. Doing roughly the same through Node.js on gRPC has these numbers where N is the number of requests sent:

```
N=00001,    ~90ms
N=00010,    ~90ms
N=00100,   ~100ms
N=01000,   ~200ms
N=10000, ~1,700ms
```

**Comment by murgatroid99** [comment]
As of recent versions I see a consistent 200 us median latency on the performance test I added when I run very large numbers of tests. It seems to me that this issue is resolved.
