### ISSUE TITLE
pip install grpcio problem

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#4746]
I'm using brew to install grpc and this is my brew info:

    grpc/grpc/grpc: stable 0.11.1, HEAD
    gRPC is the next generation open source RPC library and framework
    http://www.grpc.io/
    /usr/local/Cellar/grpc/0.11.1 (101 files, 4.0M) *
      Built from source
    From: https://github.com/grpc/homebrew-grpc/blob/master/Formula/grpc.rb
    ==> Dependencies
    Build: pkg-config ✔
    Required: openssl ✔, google-protobuf ✔
    ==> Options
    --without-libgrpc
        Do not install gRPC C core library, only install gRPC protoc plugins.
    --HEAD
        Install HEAD version

Looks like grpc and protobuf is OK.

I'm using the script `curl -fsSL https://goo.gl/getgrpc | bash -s python`.

The brew check is ok, but install grpcio failed.

    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I. -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c grpc/_adapter/_c/module.c -o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/module.o

    grpc/_adapter/_c/module.c:38:10: fatal error: 'grpc/grpc.h' file not found

    #include <grpc/grpc.h>

             ^

    1 error generated.

    error: command 'cc' failed with exit status 1

I wrote a simple main.c and use gcc, grpc cannot be included.

I use pip install with global options like:

    pip install grpcio==0.11.0b1 --global-option=build_ext --global-option="-I/usr/local/Cellar/grpc/0.11.1/include"

This is ok, but another problem shown:

    creating build/lib.macosx-10.11-intel-2.7

    creating build/lib.macosx-10.11-intel-2.7/grpc

    creating build/lib.macosx-10.11-intel-2.7/grpc/_adapter

    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/module.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/utility.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types/client_credentials.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types/server_credentials.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types/completion_queue.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types/call.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types/channel.o build/temp.macosx-10.11-intel-2.7/grpc/_adapter/_c/types/server.o -lgrpc -lgpr -o build/lib.macosx-10.11-intel-2.7/grpc/_adapter/_c.so

    ld: library not found for -lgrpc

    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    error: command 'cc' failed with exit status 1

**Comment by soltanmm** [comment]
If your pure C file can't find grpc.h, then something went wrong in the environment; either the grpc install didn't include the headers+libs for core or somehow your env-vars are otherwise broken.

In the absence of a working environment, you need to specify both include flags (`-I`) and linker directory flags (`-L`) for everything to build successfully. Try adding the lib directory for grpc as a linker directory flag.

I promise that this will not be problem come next minor release. We'll be keeping the core and the Python package in lockstep from then on, and Mac OS will have wheels.

If you already have `enum34` and `futures` `pip install`ed, there's a [staged Mac OS wheel on TestPyPI](https://testpypi.python.org/pypi/grpcio/0.12.0b6) that we'd like to hear feedback on!

**Comment by GuoJing** [comment]
@soltanmm My env is working yesterday, I don't know what changed my env, I can't do it today.

Ok, anyway this fixed my problem, I add linker to PATH but not working, add global options is work for me.

    pip install grpcio==0.11.0b1 --global-option=build_ext --global-option="-I/usr/local/Cellar/grpc/0.11.1/include" --global-option="-L/usr/local/Cellar/grpc/0.11.1/lib"

Thanks anyway.
