### ISSUE TITLE
C++ bidirectional streaming: stream->write() doesn't appear to be thread-safe

### ISSUE THREAD

**Issue by larsonmpdx** [grpc/grpc#4751]
This is with release-0_12 built today.  I'm using a sync bidirectional streaming RPC.

Normally the server's outgoing stream is written from a queue in a writer thread.  Sometimes the server will insert control packets directly from its reader thread.  Under high load I'm sometimes getting an assert failure:

(server.cc:439)  GPR_ASSERT(GRPC_CALL_OK == result);

adding a mutex to my my stream->write() calls in each thread seems to prevent this

is stream->write() not intended to be thread-safe?  Is there a better way to handle this?

**Comment by yang-g** [comment]
This is working as intended. Using a mutex or something similar to synchronize the writes is the right thing to do.
