### ISSUE TITLE
Create binary artifacts for PHP distribution package

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4771]
Building of artifacts is triggered manually by jenkins job https://grpc-testing.appspot.com/view/All/job/gRPC_build_artifacts/.

Add support to tools/run_tests/build_artifacts.py.

**Comment by stanley-cheung** [comment]
PHP is now green on Jenkins Artifacts test for both Linux and Mac in x64. 
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/212/
