### ISSUE TITLE
Ability to disable load roots.pem by default in C++

### ISSUE THREAD

**Issue by pavel-odintsov** [grpc/grpc#4779]
Hello!

I'm developing application based on gRPC. But I do not want to offer to customer ability to put some keys to the default pem storage: /usr/local/share/grpc/roots.pem.

How I could disable this option completely?

**Comment by jiangtaoli2016** [comment]
Is this a concern?

**Comment by pavel-odintsov** [comment]
Yes, it's an issue for my case. I want to allow only our own CA and ban other.

**Comment by jiangtaoli2016** [comment]
In gRPC, you can pass environment var GRPC_DEFAULT_SSL_ROOTS_FILE_PATH = /etc/your_pem_file which only contains your CA public key. Does this address your concern?

**Comment by pavel-odintsov** [comment]
Hello!

Yes, that's fine! Thank you!

**Comment by jiangtaoli2016** [comment]
Great. Let me close this issue. Feel free to re-open if you still have questions.
