### ISSUE TITLE
Consider supporting base_namespace cmdline option for C# protobuf plugin.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4793]
Protobuf C# has recently introduced this: https://github.com/google/protobuf/pull/785. 
For now, this is low priority feature.

**Comment by Axiverse** [comment]
I can take a look at this. Any pointers on where to start looking?

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/5f5415eae3acb267155a22fa9b612d43c0659676/src/compiler/csharp_plugin.cc#L27

**Comment by jtattermusch** [comment]
This has fallen below the team’s cutoff, however we welcome contributions from the community. Closing.
