### ISSUE TITLE
Easy-to-install nuget package for C#

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4795]
Containing precompiled binary artifacts for windows mac and linux.

**Comment by goldenbull** [comment]
:+1: Great! Can't wait to have a try :)

**Comment by jtattermusch** [comment]
Most of the work is here #4820.

**Comment by jtattermusch** [comment]
Still some minor problems to address here, but most of the work has been done.

**Comment by jtattermusch** [comment]
Actually, since this has been mostly addressed, let's close this an track the remaining things to be fixed instead.
