### ISSUE TITLE
Enable NuGet package MsBuild integration

### ISSUE THREAD

**Issue by kkm000** [grpc/grpc#4805]
It is easy to include proto compile step into MsBuild build process, bit it is hard to get it right. Is there an interest in adding this support so it is available out of the box? I'd be happy to contribute, but it has to involve both grpc and protobuf projects.

I am currently including the following targets file from my projects:

``` xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <CompileDependsOn>ProtoCompile;$(CompileDependsOn)</CompileDependsOn>
  </PropertyGroup>
  <PropertyGroup>
    <ProtoCompilerPath>..\..\ext\usr\bin\</ProtoCompilerPath>
    <ProtoCsPluginPath>..\..\ext\usr\bin\</ProtoCsPluginPath>
  </PropertyGroup>
  <Target Name="ProtoCompile"  Condition=" '@(ProtoBuf)' != '' " Inputs="@(ProtoFiles)"
        Outputs="$(IntermediateOutputPath)Acme.cs;$(IntermediateOutputPath)AcmeGrpc.cs">
    <PropertyGroup>
      <ProtoCCommand>$(ProtoCompilerPath)protoc --csharp_out=$(ProjectDir)$(IntermediateOutputPath) --grpc_out=$(ProjectDir)$(IntermediateOutputPath) --plugin=protoc-gen-grpc=$(ProtoCsPluginPath)grpc_csharp_plugin.exe -I ..\..\src\acmeserver @(ProtoBuf)</ProtoCCommand>
    </PropertyGroup>
    <Message Importance="high" Text="$(ProtoCCommand)" />
    <Exec Command="$(ProtoCCommand)" />
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)Acme.cs;$(IntermediateOutputPath)AcmeGrpc.cs" />
      <FileWrites Include="$(IntermediateOutputPath)Acme.cs;$(IntermediateOutputPath)AcmeGrpc.cs" />
    </ItemGroup>
  </Target>
</Project>
```

This compiles `acme.proto` and adds generated files to C# compilation (and to future cleanup via `FileWrites`, adding to hermeticity). Since `ProtoCompile` target is declared dependency on `Compile` (via the `CompileDependsOn` property), and `Compile` is one of the targets invoked by VS on project load, compilation happens even when VS opens the project, and therefore IntelliSense is available for generated files immediately. The generated files are not shown in the project tree, which is also much better.

There are a few problems here though that I do not really know how to approach.
1. Note hardcoded paths to tools (lines 6 and 7). This is easy to obtain by including some well-scripted `.target` and/or `.prop` files into NuGet packages for the corresponding tools. The issue here (or a non-issue, may I hope) is that both `Google.protobuf` and `Grpc.Tools` must include them (On this note, `Grpc` also must declare an equal version dependency on `Grpc.Tools` or package the C# plugin with `Grpc.Core` and discard `Grpc.Tools` altogether. Either will do, but the plugin must be available for proto compilation).
2. Figuring out names of generated files from compiled `.proto`s. (Also note the hardcoded names of generated files). I kinda see a pattern, but an official word from project owners would be helpful :)

I would try to do as much as I can with this, including C++ integration as well, and I used to write quite complex build scripts (including coded MsBuild extensions, called Tasks); but this kind of cross-project coordination might be beyond my capabilities. Any implementation will be half-baked from either vantage point.

I am an ex-Google SWE, by the way--just for a fair mention of the fact.

**Comment by jskeet** [comment]
See also https://github.com/google/protobuf/issues/375

**Comment by kkm000** [comment]
@jskeet: Thanks for the x-ref. I believe that packaged MsBuild tooling is the way to go (.NET packaging already uses NuGet). 

The point #2 from my initial comment is the most complex. `foo.proto` is compiled into `Foo.cs`, but also optionally produces out `FooGrpc.cs` if a service has been defined in the proto file. It is hard to account for a dependency like this. The best idea I have so far is add a build task dependency only if `FooGrpc.cs` in fact exists (from a previous compilation), then add `FooGrpc.cs` to compile/cleanup target lists only if it exists after compile. This elaborate scheme breaks though if a service definition gets deleted from the `proto` file: unitl the full Clean target is ran, the stale `FooGrpc.cs` is going to sit there and, being older than the proto, force recompile on every run. Not ideal but would work on the first iteration, I believe, and can be clearly documented.

An alternative is to create a full-blown ProtoCompile task in code and use the tracker (underdocumented at best, but I had to learn it through some reverse-engineering of MS C++ build). The tracker actually intercepts file operations of a tool and reports files actually read written, so this is a significantly tighter solution. Unfortunately, much more complex too, so I'll reserve that for now if I may.

What are your thoughts?

**Comment by jtattermusch** [comment]
@kkm000, thanks for a very informative summary on the topic. In general, contributions in terms of simplifying the development workflow with .proto files are very welcome. Also, the msbuild snippet you posted seems to be fairly though out and is a step in the right direction.

I also have some questions/concerns:

1. the solution needs to work properly on linux and mac as well (it should work with mono's xbuild and also with monodevelop's/xamarin's mdtool).

2. Using this approach in the grpc repository is problematic. We could indeed pull the protoc binary from the Google.Protobuf nuget package (currently that one only contains the windows version, which might change soon), but the gRPC codegen plugin is part of the grpc repository, and that would mean requiring to build grpc_csharp_plugin (which in turn needs to build third_party_protobuf) in order to be able to compile the C# project.

3. Using this approach in the protobuf repository should be possible, but it would still require to prebuilding protoc before the C# build could start (C# builds in seconds, while C++ codegen takes ~5min). 

4. With the approach you described, do the .cs files get generated each time you build or do they get reused if they are newer than the source .proto file?

5. In a not very distant future, I plan to work on adding CoreCLR and DNX support for gRPC. At that point, we would likely need to have support for DNX-style project.json projects (that are not build using MSbuild).

6. I could imagine the proposed solution working quite well for projects that depend on Protobuf   or Protobuf & Grpc nuget packages. But for such projects, one still needs to manually edit their .csproj files to fill in the protoc command and names of the generated .cs files. So the approach you are suggesting would be helpful, but more in terms of providing a useful howto (documentation) rather than giving a solution for the problem that would work out of the box.

**Comment by kkm000** [comment]
@jtattermusch: Thanks for the very good summary of issues. Complex stuff indeed! I'll start with (6): the mechanism that solves this is a [set of `.target` and `.props` files packaged into the `build/` firectory of a NuGet package](http://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project). When first adding such a package to a project, NuGet (to be precise, NuGet plugin in Visual Studio) adds imports for these files into the project. [This is an example](https://github.com/grpc/grpc/blob/master/examples/csharp/helloworld/GreeterClient/GreeterClient.csproj#L59) of such an import added automatically; the import is created at the time the package is added to project, one for every .targets file found in the `build/` directory of a package, and  `.props` are imported very similarly but near the beginning of the project build file, not at end. This way, e. g. `ProtoCompilerPath` property that is set in my example would instead be set in the `.props` file coming with the Protobuf package (by simply resolving `../tools` relative to the `.props` file location). Similarly, the `<Target Name="ProtoCompile"` would be actually scripted in the `.targets` files, and operate on elements of the `@(ProtoBuf)` collection.

It plays nicely with Visual Studio project system as well; if you add a definition to the imported  `.props` file like the following
```xml
  <ItemGroup>
    <AvailableItemName Include="ProtoBuf" />
  </ItemGroup>
```
then "ProtoBuf" will be displayed as one of the options in the drop-down file type property in the property browser, so adding a new .proto file in UI is also easy.

![protobuf](https://cloud.githubusercontent.com/assets/8228229/12666681/f18d552c-c5f7-11e5-89c0-ed0352fdda14.png)

Just to set things straight, there is absolutely no manual `.csproj` editing involved.

As for mono build tools (addressing (1)), I am not really familiar with these, although, according to the documentation, xbuild should be very similar to MsBuild, and monodevelop does have a plugin for NuGet. Can we get all the automation that I described in monodevelop I do not really know, as it depends on NuGet plugin for adding imports (this I really expect to work in monodevelop) and IDE having a way to add files to a specific ItemGroup in project.

Under mono, we will have to properly locate native binaries (protoc and gRPC plugin) for the platform.

Regarding (2) and (3), there is a bit of misunderstanding; I am sorry for being unclear. I did not at any moment suggest _building_ gRPC or Protobuf from source, just using MsBuild with NuGet machinery to locate binaries for protoc and the gRPC plugin in the `tools/` subdirectories of their respective packages.

Regarding (4), as long as a <Target> defines Inputs="..." and Outputs="...", the target is not run by MsBuild if all outputs exist and are newer than all inputs. This is pretty much the behavior of good old make. The matter is complicated by the fact that I have no way of knowing _whether_ any given `x.proto` will in fact produce `XGrpc.cs` or not (if my understanding is correct, the file is generated only for a proto source with `service` definitions). Also, we should be careful here as Visual Studio should also actually _invoke_ MsBuild on the project if any "relevant" file in the project has changed, and it has pretty daunting rules that determine what is relevant (for example, if you have a README.txt in project and change only this file, the project will not be even considered for build by VS on solution build). For C# project, my snipped works, but for a C++ project it requires some additional tweaks to tell VS the .proto files are in fact sources to the build target.  Perhaps this issue may exist in some other form in monodevelop/xamarin as well.

All in all, I believe a good starting point would be getting all the steps supported for VS, and then base the support for monodevelop on this. My understanding is that monodevelop should support most of MsBuild and VS project system, so we'll need tweaking, not dismantling and rebuilding.

**Comment by jskeet** [comment]
A couple of extra complications in all of this:

- `foo.proto` may require other directories to be included in the proto path
- You may wish to specify a particular base namespace and target directory to use; I can imagine some users wanting to keep their protos in a separate directory from the target directory, but others wanting to keep them alongside each other

It's possible that these could all just be options that could be manually edited if necessary.
It definitely feels like the protobuf package should provide the base functionality here, and then ideally the GRPC enhance that (e.g. by setting extra properties that the base target knows about). I'm going to experiment a bit with this.

**Comment by jskeet** [comment]
Another note about the behaviour of the targets file given here - this assumes the generated code is *not* wanted. Personally I usually check in the generated proto code (as per the Protobuf project, for example) as that removes any concerns around protoc changes etc... we'd probably want an option for each way.

**Comment by jtattermusch** [comment]
@kkm000 , can you possibly take a look at PR #6085 that is supposed to bring some sort of msbuild protoc integration? I'd like to get a second opinion.

**Comment by kkm000** [comment]
@jtattermusch: Thanks for looping me in! I did.

**Comment by jtattermusch** [comment]
update: dotnet SDK now supports the new msbuild-based .csproj files.

**Comment by makdharma** [comment]
@jtattermusch - what if anything is left to do here? OK to close?

**Comment by hcoona** [comment]
I'm working on this issue in a separate repository: https://github.com/hcoona/Grpc.Tools.MsBuild.Unofficial
I'd like to merge it into grpc repo after made it fully tested & stable.

**Comment by kkm000** [comment]
Xref: #10699 #13098

I'll look into this again.

Another issue I noticed was standard protobuf includes (.proto files in the protobuf/include directory) were not packaged, only the compiler itself.

**Comment by kkm000** [comment]
@jtattermusch: I am going to rework and extend the Grpc.Tools package seriously. My goal is to make the .proto files part of the build process, and I think I can do it for all platforms. I am limiting the scope now to C# only; we can do C++ tooling next (not libraries yet), and maybe other .NET languages besides C# too (via a proto-only .dll assembly compiled with C#) if there is interest, The biggest change is the Tools package that has its internal directories wrong, the build tools should go into `/build`, not `/tools`. The spec is quite vague, but it states that ["Contents are copied to the project folder, and the tools folder is added to the PATH environment variable"](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory). The first part is not apparently true, at least for Visual Studio or for .NET Core; the second is (inside VS) but it does not help much because there are tools for different platforms. But generally '/tools' is reserved for scripts run by Visual Studio on install and uninstall; I would not put other stuff in there.

My question is how would you prefer to see the work delivered? I am thinking of a single PR here I would push initial changes for review and comments, and then can add the changes fixing the paths in examples and probably tests (I do not see overt tests for the Tools package, but perhaps there are indirect dependencies), and extending the documentation. But I can do a series of independent MRs as well, if you find it easier. I would prefer to do it in steps, in any case, not one big changeset, so I can get comments before proceeding to the next part.

**Comment by kkm000** [comment]
@ctiller, I am tracking it in the PR #13207. All important discussion has happened there, not in this ticket. Whether to keep this issue open is up to you.
