### ISSUE TITLE
OSX: PHP grpc Call::startBatch too slow

### ISSUE THREAD

**Issue by Rastusik** [grpc/grpc#4806]
I installed the newest grpc (with protobuf) using homebrew, but the grpc calls seem too slow to me. My PHP app communicates with vitess (vitess.io) using grpc and a regular request to the app which normally lasts 5s was prolonged to 20s. I think the problem is not with Vitess, because it's just a layer above the same mysql with which the requests takes the mentioned 5s.

I was also profiling the PHP app using blackfire.io and it showed me, that Grpc\Call::startBatch calls took 13s of the 20s of the whole request time.

I'm using the grpc 0.12 version, php 5.6

**Comment by Rastusik** [comment]
I also have some unit tests for my vitess library, an it takes 20 seconds to run them on the mac, and 1.2s to run them on linux

**Comment by Rastusik** [comment]
Btw I 'm not sure if this is grocery 0.12 related or php-grpc 0.7 related

**Comment by Rastusik** [comment]
Grpc 0.11 and php grpc 0.61 worked fine out of the box

**Comment by stanley-cheung** [comment]
Can you try with the latest 0.8.0 version? https://pecl.php.net/package/gRPC/0.8.0

This version eliminates the need for the core gRPC library separately, although I am not confident it will solve your performance issue because we had not put much effort on performance in the last couple of releases yet. 

What you run into may be related to #4017

**Comment by Rastusik** [comment]
I already tried it a couple of hours ago (with vitess), with no change... but on linux it seems to work with no slowdowns

**Comment by Rastusik** [comment]
Not sure if it is related but I also do experience the #4017 issue, but only in CLI and the hang takes always almost identical amount of time. Also, when the scripts are run from php-fpm, everything seems to be ok. 

My main issue occurs during running unit tests from CLI - on linux they take cca 3-5 seconds, on OSX it's about 22 seconds now and rising with new unit tests being added. Also when I run the PHP app from the web/php-fpm on OSX it takes much longer to run comapring to the linux build, I'm talking about 15 seconds vs. 3 seconds (tested with Vitess, but on the same Vitess build)

**Comment by stanley-cheung** [comment]
#4017 has been resolved. From my side, unit tests and some simple app are almost returning instantly. You may have to build from master or wait for a 0.15.1 release to verify. Please re-open if you still see slowdown.
