### ISSUE TITLE
interop test report is broken

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4810]
See https://grpc-testing.appspot.com/job/gRPC_interop_master/2506/HTML_Report/

The interop tests in this build seem to have passed, it's just the report that's broken.

**Comment by ejona86** [comment]
It looks to have broken some time between January 6th and 7th:
https://grpc-testing.appspot.com/job/gRPC_interop_master/2225/HTML_Report/
https://grpc-testing.appspot.com/job/gRPC_interop_master/2250/HTML_Report/

**Comment by adelez** [comment]
Last good one is #2248, so the only possible culprit is Commit db21899edcd663bf941b0c7ff07d5a3218908c9b. I'm currently stuck with "Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.19)" when I run the test. Will work on it asap once that's resolved.

**Comment by jtattermusch** [comment]
Interop tests seem to be passing again, but this issue is very annoying (and I am convinced it's an easy fix). Can we please fix the HTML report today? Thanks.

**Comment by adelez** [comment]
Sorry for the delay. I'll tackle it today.
