### ISSUE TITLE
ObjC: Feature Request to Fail Fast on No Connection

### ISSUE THREAD

**Issue by nkibler** [grpc/grpc#4811]
I noticed that if I switch off my internet connection and try to make a gRPC call, it spends a very long time retrying the requests at incrementally longer intervals. The logs continue to spit out "No route to host" errors coming from the C core (tcp_client_posix.c:246).

I would expect it to check if there's a connection in the first place, and if not, fail fast and immediately call the RPC's callback with the appropriate error.

**Comment by jcanizales** [comment]
I'm implementing it this week :) https://github.com/grpc/grpc/issues/4064 It's the top priority right now because many people are stumbling upon it.
