### ISSUE TITLE
Fail to build docker in grpc-interop2

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#4822]
https://grpc-testing.appspot.com/me/my-views/view/All/job/gRPC_interop_master/2509/console

I tried to upgrade docker after a restart:
adelez@grpc-interop2:~$ curl -sSL https://get.docker.com/ | sh
...
...
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
adelez@grpc-interop2:~$ sudo dpkg --configure -a
dpkg: error processing package docker-engine (--configure):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting configuration
Errors were encountered while processing:
 docker-engine

**Comment by ctiller** [comment]
@jtattermusch @nicolasnoble - I could use some help here - whomever gets to it first?

**Comment by jtattermusch** [comment]
we don't care about grpc-interop2 machine, we have grpc-canary-interop1 that seems to be doing fine (except #4831).
I brought grpc-interop2 offline for now, later we can just delete the VM and recreate it in 5 mins (investigating the dpkg problem is not worth the time.)

**Comment by jtattermusch** [comment]
Let's focus on the two actual problems:
https://github.com/grpc/grpc/issues/4831
https://github.com/grpc/grpc/issues/4835

**Comment by jtattermusch** [comment]
Closing this issue in favor of https://github.com/grpc/grpc/issues/4831, which is our real problem.
