### ISSUE TITLE
Python installation sometimes puts the extension library in the wrong place

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4829]
On a docker image I'm playing with, regardless of using sdist or bdist or whatever, the `.so` appears in all the wrong places. When installing from an `sdist`, in particular, it looks like setuptools (or cython, or *something*) ends up trying to place the file `./grpc/_cython/cygrpc.so` in `../ython/grpcio/grpc/_cython/cygrpc.so` (according to the `egg-info` directory contents), which is an utterly nonsensical path. I can replicate it sometimes in a `virtualenv`, and all the ways for which the installation succeeds in a `virtualenv` appear to fail in docker.

This smells like one of our tools (whether it's `distutils`, `setuptools`, or `cython`) being finicky about our `setup.py` file's relocation, but, I don't know for sure yet.

**Comment by soltanmm** [comment]
Actually, absolutely everything is broken about the distribution on master, and we missed it because I set up `tox` to build in-place when testing rather than install into the `virtualenv`.

**Comment by soltanmm** [comment]
cc #4808

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: was this issue incorrectly closed because GitHub saw "fixes" in the text of #4830 and didn't notice the word "almost" immediately before it?
