### ISSUE TITLE
Where would I start to implement a Named pipes-based transport?

### ISSUE THREAD

**Issue by aniongithub** [grpc/grpc#4832]
I have a project that already uses Protocol Buffers over Named Pipes for inter-process communication. It seems to me that gRPC would be perfect if it supported Named Pipes for transport.

Where would I start writing a transport layer for gRPC that uses Named Pipes?

Is this even possible (i.e., some sort of factory mechanism to plug in new transports)?

Thanks in advance!

**Comment by ananthonline** [comment]
*bump* ? Any pointers/help here?

**Comment by neundorf** [comment]
Did you make any progress with this ?

**Comment by neundorf** [comment]
This discussion here seems to be related:
https://groups.google.com/forum/#!topic/grpc-io/o9LZivNtpoU

**Comment by byronyi** [comment]
I am actually looking into the same problem, but with a different transport. I guess I could start with `src/core/ext/transport/chttp2/transport/chttp2_transport.h` and see if I can copycat one from that.

**Comment by aniongithub** [comment]
@neundorf No - I have since moved onto working on other things, sorry :)

**Comment by a11r** [comment]
Closing as obsolete. Please reopen if there is interest in this feature.
