### ISSUE TITLE
Come up with roots.pem story for distribution packages.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4834]
The new distributions packages don't depend on the grpc debian package (which is great), but one consequence of it is that the roots.pem won't be installed in the well known location once you install  gRPC node, ruby, C# and others. (We've had this problem for C# for Windows but we will now have it for all languages everywhere).

We need a story that is both user-friendly (in terms of making roots.pem discoverable easily) and secure.

**Comment by jtattermusch** [comment]
CC @jboeuf

**Comment by jtattermusch** [comment]
The pre-existing C# issue https://github.com/grpc/grpc/issues/3375

**Comment by jskeet** [comment]
Can a default roots.pem be embedded within the package, then read (e.g. out of a resource stream in .NET) and the contents passed down? That would seem the obvious solution within the .NET world (just like Noda Time allows you to load an arbitrary time zone database file, but contains one within the main assembly).

**Comment by jtattermusch** [comment]
@jskeet that actually sounds like a very good idea - and I am also fairly confident it would be secure enough - at least it is much more secure than fiddling with GRPC_DEFAULT_SSL_ROOTS_FILE_PATH env variable and getting it wrong one day.
@jboeuf opinions?

**Comment by jboeuf** [comment]
@ctiller may have some opinion on that as well but here's mine :)

Yes, I think that's a good option. The only thing though is that you should make sure that the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH has not been set before doing that as we should still allow the env var override. Makes sense?

**Comment by ctiller** [comment]
SGTM

**Comment by jtattermusch** [comment]
I've talked with @ctiller  and here's proposal for the solution:
1. roots.pem will be added as a resource or installed into a well discoverable path when installing the package. The runtime needs to be able to correctly locate it at all times when running gRPC.
2. to prevent reimplementing the GPRC_DEFAULT_SSL_ROOTS_FILE_PATH logic, we will define a new C core function grpc_ssl_credentials_override_default_roots (naming to discuss). After that function has been called, grpc_ssl_credentials_create(NULL, NULL) will return the roots provided instead of loading the roots.pem from the well known location (unless the env var is set, in which case it will be respected).
3. upon initialization, wrapped languages will load the roots.pem resource and call grpc_ssl_credentials_override_default_roots with the file contents
4. for the user, the experience is that loading the default roots just works, without the need to configure anything.

@jboeuf  opinions?

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle , @murgatroid99 , @stanley-cheung , @soltanmm  opinions?

**Comment by jtattermusch** [comment]
@jcanizales is this relevant for ObjC or not?

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: @soltanmm implemented this for Python #4224 (6d2ef17f30228e432).

**Comment by jboeuf** [comment]
LGTM. Thanks for drafting the plan.

**Comment by murgatroid99** [comment]
Why is this better than simply setting the environment variable if it is unset?

**Comment by jskeet** [comment]
@murgatroid99: It doesn't require roots.pem to exist as a file in the file system at all. It can exist within the packaging (e.g. a DLL in the .NET case). When using the bundled one, there's no *benefit* in having it as a separate file, so why require it?

**Comment by jcanizales** [comment]
As we discussed this morning, in Objective-C the current solution is analogous to what Jon Skeet described for .Net: The file goes with the library as a resource, and is read the first time it's needed. Client developers can then choose to override it on a per-host basis.

**Comment by jtattermusch** [comment]
@jboeuf  as introducing the grpc_ssl_credentials_override_default_roots function in core is a prerequisite for the implementation in all languages, could you create a PR for that? Once that function is available, implementing this feature in each language should be fairly trivial. Thanks!

**Comment by ctiller** [comment]
Seems like we've got the story.

**Comment by nathanielmanistaatgoogle** [comment]
Also there was work on this in #5100.

**Comment by nathanielmanistaatgoogle** [comment]
... and for completeness #5168 should be cited as part of this story too.

**Comment by bluecmd** [comment]
Just to clarify: In Debian the default trust store is /etc/ssl/certs/ca-certificates.crt. Many companies install their own CA there to allow things like wget / curl / etc. to automatically trust their internal CAs.

Will this file be read by default if i pass None? If not, IMO that's not the least surprising behavior when installed from a distribution package.
