### ISSUE TITLE
grpc.Errorf runs afoul of "go vet".

### ISSUE THREAD

**Issue by danjacques** [grpc/grpc#4840]
The `go vet` tool expects functions named "Errorf" to take a format string as a first argument. gRPC's version takes a `codes.Code`. Unfortunately, service implementations that use gRPC and `go vet` get bombarded with errors due to the perceived misuse of `Errorf`.

A solution would be to rename gRPC's `Errorf` function to something that doesn't collide with standard library expectations. Another solution would be to update `go vet` to probe the function signature that it's asserting and confirm that it matches expectations about format string placement.

**Comment by murgatroid99** [comment]
Are you asking specifically about the Go implementation of gRPC?

**Comment by iamqizhao** [comment]
This is an known issue. https://github.com/grpc/grpc-go/issues/90
