### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by harishabr** [grpc/grpc#4864]
Am trying to compile node example,but am getting below error.
Error: Could not locate the bindings file. Tried:

Thankyou you.

**Comment by murgatroid99** [comment]
Can you be more specific about what you did to get that failure?

**Comment by harishabr** [comment]
Thank you for replaying.
Actually i am trying to run grpc  node examples,when i try to run that examples am getting above error.

The secenerios is:
sudo node greeter_server.js 
/home/prasanna/prasanna/RPC/grpc/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/prasanna/prasanna/RPC/grpc/build/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/build/Debug/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/build/Release/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/out/Debug/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/Debug/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/out/Release/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/Release/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/build/default/grpc_node.node
 → /home/prasanna/prasanna/RPC/grpc/compiled/5.4.1/linux/ia32/grpc_node.node
    at bindings (/home/prasanna/prasanna/RPC/grpc/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/prasanna/prasanna/RPC/grpc/src/node/src/client.js:54:31)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/prasanna/prasanna/RPC/grpc/src/node/index.js:48:14)
    at Module._compile (module.js:397:26)

**Comment by murgatroid99** [comment]
You should run `npm install` first.

**Comment by harishabr** [comment]
yes i did that one,and  i installed all dependency library by using npm install.

**Comment by murgatroid99** [comment]
The example has been modified in a way that may fix this problem. If you run `npm install` in the `examples/node` directory, it should install everything properly.

**Comment by nicolasnoble** [comment]
@harishabr please let us know if that hasn't solved your issue so we can re-open accordingly.
