### ISSUE TITLE
malloc/delete [] mismatch in node/ext/byte_buffer.cc

### ISSUE THREAD

**Issue by wilhuff** [grpc/grpc#4867]
I have a proto that contains a `bytes` field that, when accessed via GRPC Node running under tcmalloc causes the following stack trace:

```
debugallocation.cc:361 RAW: memory allocation/deallocation mismatch at 0x7ffc36478840: allocated with malloc being deallocated with delete []
(anonymous namespace)::RawLogVA()
base_raw_logging::RawLog()
MallocBlock::CheckLocked()
MallocBlock::CheckAndClear()
tc_deletearray
Nan::FreeData()
node::Buffer::Replace()
node::Buffer::~Buffer()
v8::internal::GlobalHandles::Node::PostGarbageCollectionProcessing()
v8::internal::GlobalHandles::PostGarbageCollectionProcessing()
v8::internal::Heap::PerformGarbageCollection()
```

The problem seems to be that the backing array for the the buffer is allocated at [byte_buffer.cc:72](https://github.com/grpc/grpc/blob/master/src/node/ext/byte_buffer.cc#L72):
```cxx
char *result = reinterpret_cast<char *>(calloc(length, sizeof(char)));
```

and the `node::Buffer` is wrapped around it at [byte_buffer.cc:83](https://github.com/grpc/grpc/blob/master/src/node/ext/byte_buffer.cc#L83)
```cxx
Nan::NewBuffer(result, length)
```

The problem comes from the fact that the two-argument `Nan::NewBuffer` passes a `free_callback` of `Nan::FreeData` [nan.h:1105](https://github.com/nodejs/nan/blob/master/nan.h#L1105)
```cxx
node::Buffer::New(data, size, FreeData, NULL)
```

and `Nan::FreeData` calls `delete [] data;`.

So if I'm understanding this correctly I see two options for how to fix this:
   * Change `ByteBufferToBuffer` to allocate the backing array with `new char[size]`
   * Supply a callback to `Nan::NewBuffer` that performs the `free` to match the current call to `calloc`

I'm happy to supply a PR to do it but wasn't clear which way would be preferred: changing to using array new would certainly be the easier change but it seems like the current code is going out of its way to avoid `new` so maybe the latter would be preferred.

Of course the other possibility is that I've misunderstood what's going on here altogether in which case I'll be happy to take another path.

Thoughts?

**Comment by murgatroid99** [comment]
Changing the backing array to a `new char[length]` would be perfectly fine here.

**Comment by lepatryk** [comment]
This is still broken when compiled against new node versions. It seems that Nan is not doing a great job of being consistent with deallocating buffers across different node versions.

I'd suggest we go with option 2) i.e. providing an explicit buffer deallocation callback, so that we're resilient to any Nan/Node deallocation inconsistencies.
