### ISSUE TITLE
Set timeout/Close channel on server side?

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#4869]
Hi there

I'm using grpc because http2 is multiplexed. But I'm wondering how to use that (or best practice). Of course the code below reuse the connection.

```python
c = Channel()
s = Stub(c)
for i in range(10):
    # reuse
    s.do_something1()
    s.do_something2()
c.shutdown()
```

But I'm write a lib called SDK, I won't have main function everywhere you know.

```python
class SDK(object):
    c = Channel()
    s = Stub(c)

    def do_something1(self, params):
        self.s.do_something1(params)

    def do_something2(self, params):
        # totally different logic
        self.s.do_something2(params)

    def shutdown(self):
        self.c.shutdown()

# in file a
sdk = SDK()
sdk.do_something1()
# if shutdown here, file below may
# not reuse channel
# if not shutdown here
# connection will be always there

# in file b
sdk = SDK()
sdk.do_something2()
```

I want the one who use this SDK don't need to care about shutdown the channel, if everyone need to think about shutdown, multiplex may not work. But If no one cares about shutdown, there will be a lot of connection. (if process is dead, connection will not released).

So, maybe I could solve this problem.

One is create a singleton object manage only one channel, close the app, GC/System will call shutdown, Another is create a connection pool manage channels, close the app, GC/System will shutdown all channel connection.

Or another way is close the connection on the server side if I set a timeout, and client reconnect again, I think this one is better.

So, how to close a channel or set a timeout on server side? Or any other best practice?

Thanks

**Comment by killpanda** [comment]
:+1:

**Comment by ctiller** [comment]
Is this a GA blocker because we have a .shutdown() function?

**Comment by nathanielmanistaatgoogle** [comment]
@GuoJing: it's not clear to me what the `shutdown` method on channel objects is in your example code - I don't think such a method exists, or has ever existed, on gRPC Python channel objects?

Please tell us more about your specific use case, and the particular problem that you need to solve? gRPC Python channels don't offer an application-level "close" or "shutdown" but internally they do terminate their network connections and free other resources when garbage collected by the Python interpreter.

**Comment by GuoJing** [comment]
@nathanielmanistaatgoogle 

I wrote the shutdown method myself, here is my code

```python
def shutdown(self):
    del self.channel # del self.c
    del self.stub # del self.s
```

**Comment by nathanielmanistaatgoogle** [comment]
@GuoJing: when working with the master branch of gRPC Python (and not grpcio 0.14), is that `shutdown` method of yours still necessary? If you eliminate it and just allow the channel and stub to be garbage collected, does your application malfunction?

**Comment by GuoJing** [comment]
Looks like the problem solved, Thanks.

GuoJing
-----------------------------
http://guojing.me <http://guojing.me/> 
The one who love coding.
--> ret <--
echo null
rm -rf /

**Comment by nathanielmanistaatgoogle** [comment]
Closing; thank you!
