### ISSUE TITLE
C++ double free or corruption on return if field type of message is again a message

### ISSUE THREAD

**Issue by GrgrLmml** [grpc/grpc#4870]
In pre-release 0.12.0 (commit a9c61bc512758afab2fbc7c7635c8baf2f38a722 ):
If a field type of a message is again a message I get a ``double free or corruption'' on return. 
To reproduce edit grpc/examples/protos/helloworld.proto and change HelloRequest to this:

    // The request message containing the user's name.
    message HelloRequest {
      Name nameMsg = 1;
    }
    
    message Name {
      string name = 1;
    }

adapt grpc/examples/cpp/helloworld/greeter\*.cc accordingly. If I build and run, the server side runs fine but on the client side I get:
    *** Error in `./greeter_client': double free or corruption (out): 0x00007ffdaa451e00 ***
    [1]    26734 abort (core dumped)  ./greeter_client

 [Here](https://github.com/grpc/grpc/files/103321/examples.zip) are all modified files from the example in order to reproduce this issue.

**Comment by yang-g** [comment]
This is likely not related to grpc. I think the following should fix your
problem:

```
HelloRequest request;
request.mutable_nameMsg()->set_name("hello");
```
Please refer to the documents of protobuf here:
https://developers.google.com/protocol-buffers/docs/reference/cpp-generated?hl=en#embeddedmessage

**Comment by GrgrLmml** [comment]
Thank you so much! This fixes my problem indeed. Will read protobuf docs once more thoroughly :-)
