### ISSUE TITLE
C# nuget package doesn't work with DNX-based JSON projects.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4872]
```
System.IO.FileNotFoundException: Error loading native library. File does not exist.
File name: 'C:\Users\Jon\.dnx\packages\Grpc.Core\0.13.0\lib\net45\nativelibs\windows_x86\grpc_csharp_ext.dll'
```

If I copy the contents of the grpc.native.csharp package into the right place for that to be found, it works.

It's not clear to me where it's getting that path from to try to load it from... I'd have expected it to try to load it from

```
C:\Users\Jon\.dnx\packages\grpc.native.csharp\0.13.0\build\native\bin\windows_x86
```
(or the x64 equivalent).

**Comment by jtattermusch** [comment]
I think the problem is that the nuget package includes a .targets file that instructs the msbuild project to copy the nativelibs directory to the project's output directory - that works fine for .csproj   style solutions (the old way).

I suspect if you are using the json project approach, the .targets file provided by the nuget package is ignored (for obvious reasons). 

https://github.com/grpc/grpc/blob/master/src/csharp/grpc.native.csharp/grpc.native.csharp.targets

**Comment by jskeet** [comment]
See also: https://github.com/aspnet/dnx/issues/402

**Comment by jtattermusch** [comment]
This is how Kestrel package seems to achieve a similar purpose: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/project.json#L64

**Comment by jtattermusch** [comment]
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp.Abstractions/project.json#L21
