### ISSUE TITLE
Disable showing previous build status in matrix job cells.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4892]
Jenkins matrix job shows status of previous run as icons with opacity = 0.5. 
That can be very confusing at times:
-- for pull requests, this makes no sense at all (builds are unrelated)
-- if some configuration in the matrix get disabled, its last build status stays in the matrix of later builds forever
-- sometimes it's hard to distinguish between icons with opacity 0.5 and 1 and people mistakenly treat the build as failed (or passing) even if the build for given cell haven't even started yet.

Potential fix is to tweak the jelly template for matrix project plugin:

Here's the part that of the template that either displays a grey icon, an icon with opacity = 0.5 or an icon with opacity = 1.0
https://github.com/jenkinsci/matrix-project-plugin/blob/79ff52c13bd79ff32ac25d76a4fe96391a13b314/src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly#L34

**Comment by adelez** [comment]
Closing this as we don't use matrix anymore.
