### ISSUE TITLE
Review C core public API for use of type "long"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4915]
Long can be problematic, as it can have surprising bit width on some platforms (e.g. 32bit on Windows x64). It might be worth replacing it with e.g. gpr_int64 in some of our APIs.

A good candidate is https://github.com/grpc/grpc/blob/master/include/grpc/support/time.h

It would be good to make a full pass over the entire public API and evaluate the use of long.

**Comment by jtattermusch** [comment]
@dgquintas , would you be interested in having a look?

CC @ctiller, @murgatroid99

**Comment by murgatroid99** [comment]
This is pretty much the same issue as #4852.

And a small note: `gpr_int64` no longer exists since we switched to C99; we now use `int64_t` for that purpose.

**Comment by jtattermusch** [comment]
@murgatroid99  thanks for the update on int64_t.

**Comment by jtattermusch** [comment]
Closing this in favor of #4852
