### ISSUE TITLE
C# NewClient() method return type to be the client interface?

### ISSUE THREAD

**Issue by chrisdunelm** [grpc/grpc#4916]
Currently the C# code generator creates a public client interface and a public client implementation class that implements the interface. The NewClient() method has a return type of the Client implementation class.

Might it be better for the NewClient() method to instead have the client interface as its return type?
This would strongly encourage user code to use the interface rather than the concrete class, which is arguably better practice.
It allows simpler testing/mocking; and allows alternative implementations or higher-level abstractions to be built implementing the client interface, which will be easily usable if all existing user code has been encouraged to use the client interface rather than the client implementation class.

This may require the client interface to derive from a new IClientBase interface.

(Slightly related to #1999)

**Comment by jtattermusch** [comment]
After recent changes to the codegen (replacement of client and server-side interfaces by abstract classes), this issue becomes irrelevant.

Current signature of NewClient is:

`public static MathClient NewClient(Channel channel)`
