### ISSUE TITLE
C++ 0.12 release got server side assertion [urgent]

### ISSUE THREAD

**Issue by ncspirit** [grpc/grpc#4932]
Sync server and sync client. Around 15 threads send all kinds of RPCs (from 100+ bytes to 25MB or so). There will this assertion popped after minutes of running. It basically blocks any further work that can be done...

chttp2_transport.c:169]     assertion failed: t->lists[i].tail == NULL

Can anyone confirm if this is a known issue?

**Comment by ncspirit** [comment]
stack in core is like this:
#0  0x00007f87a314dcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f87a31510d8 in __GI_abort () at abort.c:89
#2  0x000000000048bd95 in ?? ()
#3  0x0000000000479194 in grpc_channel_stack_destroy ()
#4  0x00000000004784e2 in ?? ()
#5  0x000000000047c0aa in grpc_exec_ctx_flush ()
#6  0x0000000000477445 in grpc_call_destroy ()
#7  0x0000000000474557 in grpc::ServerContext::~ServerContext() ()
#8  0x000000000046f5f8 in grpc::Server::RunRpc() ()
#9  0x0000000000472a72 in grpc::DynamicThreadPool::ThreadFunc() ()
#10 0x0000000000472c43 in grpc::DynamicThreadPool::DynamicThread::ThreadFunc() ()
#11 0x00000000005d11d0 in execute_native_thread_routine ()
#12 0x00007f87a3e0c182 in start_thread (arg=0x7f878fff7700) at pthread_create.c:312
#13 0x00007f87a321147d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by ncspirit** [comment]
It can be recreated on the latest 0.12 code this afternoon.

**Comment by nathanielmanistaatgoogle** [comment]
Our apologies for not following up on your report when you made it.

Is this still an issue? Are you able to reproduce this problem with the current master or with the 0.13 branch?

**Comment by ctiller** [comment]
Closing stale bug
