### ISSUE TITLE
Can't build grpc plugin for Development Release 0.12.0 

### ISSUE THREAD

**Issue by wanghaiqing2015** [grpc/grpc#4937]
step1 and 2 is ok,  step 3 failed

“C:\Users\root\Desktop\grpc-release-0_12_0\vsprojects\grpc_protoc_plugins.sln”(默认目标) (1) ->
“C:\Users\root\Desktop\grpc-release-0_12_0\vsprojects\vcxproj\grpc_plugin_support\grpc_plugin_support.vcxproj”(默认目 标) (2
) ->
(ClCompile 目标) ->
  ......\src\compiler\csharp_generator.cc(47): error C2039: “GetUmbrellaClassName”: 不是“google::protobuf::compiler::cs
harp”的成员 [C:\Users\root\Desktop\grpc-release-0_12_0\vsprojects\vcxproj\grpc_plugin_support\grpc_plugin_support.vcxproj]
  ......\src\compiler\csharp_generator.cc(47): error C2873: “GetUmbrellaClassName”: 符号不能用在 using 声明中 [C:\Users\root\D
esktop\grpc-release-0_12_0\vsprojects\vcxproj\grpc_plugin_support\grpc_plugin_support.vcxproj]
  ......\src\compiler\csharp_generator.cc(237): error C3861: “GetUmbrellaClassName”:  找不到标识符 [C:\Users\root\Desktop\g
rpc-release-0_12_0\vsprojects\vcxproj\grpc_plugin_support\grpc_plugin_support.vcxproj]
.

---
1. Follow instructions in `third_party\protobuf\cmake\README.md` to create Visual Studio 2013 projects for protobuf.
2. Open solution `third_party\protobuf\cmake\protobuf.sln` and build it in Release mode. That will build libraries `libprotobuf.lib` and `libprotoc.lib` needed for the next step.
3. Open solution `vsprojects\grpc_protoc_plugins.sln` and build it in Release mode. As a result, you should obtain a set of gRPC protoc plugin binaries (`grpc_cpp_plugin.exe`, `grpc_csharp_plugin.exe`, ...)

**Comment by jtattermusch** [comment]
Building the plugins gets continously tested, so I am pretty sure this works. Maybe you didn't update the protobuf submodule?
Also 0.12 release is way too old, we strongly suggest you migrate to 1.3.x (1.4.x coming soon).

**Comment by wanghaiqing2015** [comment]
oh， no 。。。。
