### ISSUE TITLE
Cannot send multiple different values using binary metadata

### ISSUE THREAD

**Issue by bogdandrutu** [grpc/grpc#4943]
See this link:
https://github.com/bogdandrutu/grpc/blob/fix/test/cpp/end2end/end2end_test.cc#L454
where I add a random binary metadata with a different value for each call in the end2end test.

This causes the RPC to fail and returns unknown status.

**Comment by yang-g** [comment]
I can reproduce it.

**Comment by yang-g** [comment]
This has to do with some kind of global state since the failed test does not fail if run alone with gtest_filter.
