### ISSUE TITLE
Tests on MacOS failing to find commits on rebuild

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4964]
I don't know what that bug _is_, but there's definitely one there. It consistently fails to `git checkout` ~~the relevant~~ a commit with:

```
stderr: fatal: reference is not a tree: 924e35677c78b92046b0ab723c109c3e62f8befb
```

EDIT: Not just Python specific, see [here](https://grpc-testing.appspot.com/job/gRPC_pull_requests/5722/) (this link is alive for the next 400 builds, yes?)

EDIT EDIT: And indeed that commit doesn't exist. Uhm....

**Comment by adelez** [comment]
Obsolete.
