### ISSUE TITLE
Support connecting to Unix domain socket from Python

### ISSUE THREAD

**Issue by marienz** [grpc/grpc#4974]
gRPC channels can be created from a URI, not just a host:port pair. This is currently used for connecting to Unix domain sockets.

This feature is not usable from Python, because `grpc.beta.implementations.insecure_channel` (and `secure_channel`) take the host and port as separate arguments (with the port as a number), and that seems to be the only supported way of creating channels.

Both functions immediately combine the host/port into a single string, and passing a URI there seems to work as expected. So the real problem is deciding what the interface should look like.

**Comment by inconshreveable** [comment]
+1, also looking for this as well

**Comment by bluecmd** [comment]
+1. For now I'll just use port number "0" and construct my server with "unix:/tmp/socket:0" as socket path.
This discrepancy between the client and server APIs are quite annoying.

**Comment by nathanielmanistaatgoogle** [comment]
I believe that this has been fixed since the integration of [pull request 5701](https://github.com/grpc/grpc/pull/5701) - am I missing anything?
