### ISSUE TITLE
There are API entries that don't necessarily exist.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#4975]
Here's a quick list. We'll have to start filling the gaps, or clean them up. Some exist only on a certain platform, but not all. Some are just non-existent at all.

- [x] census_context_tag_set
- [x] census_get_trace_record
- [x] census_record_values
- [x] census_set_rpc_client_peer
- [x] census_trace_scan_end
- [x] census_trace_scan_start
- [x] census_view_aggregrations
- [x] census_view_create
- [x] census_view_delete
- [x] census_view_get_data
- [x] census_view_metric
- [x] census_view_naggregations
- [x] census_view_reset
- [x] census_view_tags
- [x] gpr_subprocess_binary_extension
- [x] gpr_subprocess_create
- [x] gpr_subprocess_destroy
- [x] gpr_subprocess_interrupt
- [x] gpr_subprocess_join
- [x] grpc_alarm_cancel
- [x] grpc_alarm_create
- [x] grpc_alarm_destroy

**Comment by larsonmpdx** [comment]
#2631 has a windows subprocess implementation

**Comment by nicolasnoble** [comment]
Covering alarms in #4978.

**Comment by nicolasnoble** [comment]
Covering gpr_subprocess* in #4979. Basically took #2631 and cleaned it up :-) Thanks @larsonmpdx !

**Comment by nicolasnoble** [comment]
Covering census* in #4982.
