### ISSUE TITLE
Update examples to exemplify use of GA API

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#4977]
The docs and scripts in `examples/python/` are out of date by two (going on three) minor version bumps.

**Comment by soltanmm** [comment]
It seems like this was partially fixed on release-0_13, and needs an upmerge.

**Comment by soltanmm** [comment]
Repurposing:
The examples in should reflect the new GA API.

**Comment by nathanielmanistaatgoogle** [comment]
Examples updated in [pull request 7419](https://github.com/grpc/grpc/pull/7419).
