### ISSUE TITLE
Census is defining externs in the public API.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#4980]
We can't have that if we want to create a DLL. We need accessors.

**Comment by nicolasnoble** [comment]
include/grpc/census.h:extern census_aggregation_ops census_agg_sum;
include/grpc/census.h:extern census_aggregation_ops census_agg_distribution;
include/grpc/census.h:extern census_aggregation_ops census_agg_histogram;
include/grpc/census.h:extern census_aggregation_ops census_agg_window;

**Comment by therc** [comment]
Isn't this done?

**Comment by nicolasnoble** [comment]
Yes, it was. The bug didn't automatically close.
