### ISSUE TITLE
Ruby does not support empty proto package name

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#4984]
From http://stackoverflow.com/questions/35114226/troubles-in-using-grpc-python-server-with-ruby-client

The error looks like it is assuming there is a package name (because of the leading period):
```
in `check_status': 12:Method "Serve" of service ".A" not implemented! (GRPC::BadStatus)
```

Related: #4824

**Comment by Dijkstra-ru** [comment]
That's ruby: adding explicit package name solves issue.
