### ISSUE TITLE
Docker running out of devicemapper space

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4988]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/5779/config=msan,language=c,platform=linux/console

`Error response from daemon: Error running deviceCreate (createSnapDevice) dm_task_run failed`

We've seen this problem before and it seems it is because we are running out of devicemapper space:

On grpc-jenkins-worker-9:
```
# ls -ahls /var/lib/docker/devicemapper/devicemapper/data
100G -rw------- 1 root root 100G Jan 31 10:03 /var/lib/docker/devicemapper/devicemapper/data
```
which means we are using 100G out of 100G available to devicemapper.

**Comment by jtattermusch** [comment]
@ctiller , @nicolasnoble , @adelez  FYI

**Comment by jtattermusch** [comment]
http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/

**Comment by nicolasnoble** [comment]
Let's go with overlayfs then :-)

**Comment by jtattermusch** [comment]
btw, easy way to diagnose:

```
# docker info
...
Data Space Used: 107.4 GB
Data Space Total: 107.4 GB
Data Space Available: 0 B
...
```

**Comment by jtattermusch** [comment]
Ok, will try to switch some workers to overlay.

**Comment by ctiller** [comment]
Might be worth switching them all over and doing your docker build trick
before folks start filing into the office.

**Comment by jtattermusch** [comment]
Will try :-)

**Comment by jtattermusch** [comment]
Ok, all machines have been updated, now trying to build the most needed base docker images on all the workers. Hopefully that will be done just before folks finish the breakfast.

**Comment by jtattermusch** [comment]
All workers are now using overlay storage option and the base docker images have been rebuild on most of the workers.
Things seem in good health, so closing this issue.
