### ISSUE TITLE
Portability suite failing - filename too long on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4990]
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/332/language=c,scenario=windows_x86_vs2015_bo/console

```
objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcbaselines/8BBEA4A5147C727100C4ADB7.xcbaseline/FFE465CA-0E74-40E8-9F09-500B66B7DCB2.plist (Filename too long)
```
(windows has a 256 character limit on path length).

jcanizales - any chance we could not check in that file or make its name shorter?

**Comment by jcanizales** [comment]
That file's inside the Protobuf submodule. We don't use it for anything, but I don't know if there are git commands to restrict what comes in when cloning a submodule. Maybe a `.gitignore` under `third_party/`?

What if we use FAT32 so it becomes less than 256 chars? :P
`third_~1/protobuf/object~1/Protoc~2.xcodeproj/xcshar~1/xcbase~1/8BBEA4~1.xcbaseline/FFE465~1.plist`

@TeBoring @thomasvl can this file be removed from the Protobuf repo?

**Comment by thomasvl** [comment]
Yea, we can trim it.

**Comment by jtattermusch** [comment]
Are we still seeing this?

**Comment by jcanizales** [comment]
The file's still there in the Protobuf repo, but I haven't seen the test fail for that reason in a while.
