### ISSUE TITLE
Node.js: Forced debug logging

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#5004]
The issue was caught in https://github.com/GoogleCloudPlatform/gcloud-node/pull/1070#issuecomment-176973224.

To summarize, without having set any logging env vars (`GRPC_TRACE`), excess output is still being printed, such as:

```
 pubsub
D0129 16:18:20.158068000 123145305219072 frame_settings.c:243] adding 983041 for initial_window change
D0129 16:18:20.311131000 123145305219072 frame_settings.c:243] adding 983041 for initial_window change
D0129 16:18:20.358417000 123145306292224 frame_settings.c:243] adding 983041 for initial_window change
    Topic
D0129 16:18:21.339030000 123145304682496 frame_settings.c:243] adding 983041 for initial_window change
D0129 16:18:22.832881000 123145305219072 frame_settings.c:243] adding 983041 for initial_window change
D0129 16:18:23.626765000 123145305755648 frame_settings.c:243] adding 983041 for initial_window change
```

**Comment by stephenplusplus** [comment]
@murgatroid99 can you think of anything I can do in the meantime to hide these logs?

**Comment by murgatroid99** [comment]
Sorry, but I don't know what's causing it, and I don't see it in my own tests.

**Comment by stephenplusplus** [comment]
Looks like the problem exists in 0.12, but not master, so I'll close this out.

**Comment by stephenplusplus** [comment]
@murgatroid99 Since 0.13, the output is mostly gone, however it's popped up a couple of times. Once, when failing to get credentials, it displays an "INVALID_GRANT" message. And here's an example of something that prints when we run our tests in Travis: https://travis-ci.org/GoogleCloudPlatform/gcloud-node/jobs/109695584#L2798

```
D0216 20:24:25.797641100    2853 chttp2_transport.c:683]     got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
```
