### ISSUE TITLE
gRPC Python protoc plugin should generate "massaged" function names that fit PEP8

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5014]
For the last year I've been thinking that this is cosmetic and not a big deal. I've now been persuaded that this is cosmetic and a big deal. Well that's a surprise.

**Comment by nathanielmanistaatgoogle** [comment]
A little more detail, since I totally forgot what was said in February.

**Reasons For:**
* Python programmers really like code elements used in the code they are writing to be PEP8-compliant. Almost as much as Java and C# folks, whereas Lua is more of an any-identifier-goes kind of community.
* If gRPC Python generated code were style compliant, static analysis tools that passed over it wouldn't complain about it.

**Reasons Against:**
* Treating user-supplied strings as anything other than sacrosanct immutable data feels like dark magic that invites non-one-to-one-mapping conflict generation, surprises, and bugs.
* Who would be running a linter over generated code anyway?

**Distractions:**
* Names needn't be massaged in order to allow linters to be used on application code that _uses_ gRPC Python generated code. No lint tool worth its salt complains about a style-noncompliant name where that name is merely used as opposed to where it is defined.

**Comment by soltanmm** [comment]
Discussion yesterday concluded with performing massaging with an escape-hatch provided by an option attached to the RPC method declarations. The specifics need to be discussed with both the rest of the gRPC team and with the protobuf team.

**Comment by nathanielmanistaatgoogle** [comment]
The more I meditate on this the less I think we should do it (for GA or at all). Now that the "early_adopter_" and "beta_" prefixes in generated code are respectively gone and obviated, do we actually know of any gRPC Python customers asking for this?

**Comment by kedare** [comment]
I confirm this would be a big plus.
Personally libraries or framework not enforcing PEP8 naming convention are a no-go.
For now I suppose the workaround would be to write a wrapper around around each generated code.

**Comment by nathanielmanistaatgoogle** [comment]
@kedare: can you tell us more about your use case? Is the issue purely cosmetic, or are there non-cosmetic consequences of the current behavior? A big part of the desire to avoid name-massaging is that service and method names as given in `.proto` files are application-specified strings, and we try very hard to keep application-specified values unmolested and sacrosanct. Also are you working only in Python or are you also working across languages? If gRPC's Python code generation looks at a method named `MyProblemSolvingMethod` in a `.proto` file and generates Python code with the name `my_problem_solving_method`, would you also suggest that gRPC's Java code generation, seeing in a `.proto` file a method named `my_problem_solving_method`, generate Java code with the name `myProblemSolvingMethod`?

**Comment by kedare** [comment]
We have a platform with may different environments (C#, Go and Python mostly), and each language stay strictly to its naming convention.
So I would prefer when using Grpc having on the C#/Go side MyMethod binding to the python's my_method, and I suppose this could be done transparently without much issues.

It's purely cosmetic but I think it's important for each language to stick with its own standard, I don't want to have to think that "Oh I am using library X that has a different naming convention, so what naming convention should I use on this part ? I should also exclude this file from PEP8 automatic check so code quality will fail". 
Also keep in ming that CamelCase is the convention for class names, so this could bring confusion when using it (As there's no "new" keyword, there would be no "automatic" way to know if I am creating a new instance or calling a method when using a gRPC method)

For me the best thing would be that gRPC would generate methods/classes/interfaces matching each language naming convention, after all the objective is to have something easy to use, mostly automated and that allows to call API's transparently, and not having something violating the naming convention and looking like an alien :)

**Comment by nathanielmanistaatgoogle** [comment]
@kedare: thank you for the very full answer. I think it's unlikely that we'll implement this ourselves, but thanks to what you've written it's likely that we'd accept a pull request from a contributor implementing it.

**Comment by richardasaurus** [comment]
+1 it's a bit of a joke the code isn't PEP8 valid (e.g. CapWords method names on the service code) and sets a bad example for users of it.

**Comment by nathanielmanistaatgoogle** [comment]
[Elsewhere a user writes](https://groups.google.com/forum/#!topic/protobuf/HeTwIRb7DCs) _"I am trying to migrate our project to protobuf and find one annoying feature in protobuf_ [...] _codegen. It will automatically rename the field name defined in proto during codgen to fit camel convention."_.

Now it happens to be the case that the content of "[...]" is "c#", but it is the kind of feedback that makes me skittish about moving forward with this Python enhancement request...

**Comment by tino** [comment]
I am surprised this didn’t get more comments. I would really like to start using gRPC and it not following the Python standards is quite a deal breaker. It is not so much the cosmetics (although I know I wouldn’t like adopting another style), it is more that going full-on auto formatting in the recent year (with black) made a big difference. And yes, the class setup and method names are auto generated, but the method implementations are not, so those files still need linting.

Let me flip the script: if the convention in Golang was different from what gRPC originally was, wouldn’t a Golang specific codegen already be available given how widely used gofmt has become?

I’d strongly advocate for a way to write or generate at least PEP8 compliant code.

**Comment by lidizheng** [comment]
@tino Thank you for voicing the need. This issue fail out of gRPC Python team's radar. We will raise the priority of this issue.

**Comment by naphta** [comment]
Using black formatter on all my projects has also slowed down my adoption of gRPC inside of Python. I tend to reach for Golang these days when gRPC is involved just because of simplicity. I'd love to cleanly use Python for a lot of those jobs.

**Comment by lidizheng** [comment]
To people we are watching this issue, unfortunately, the gRPC Python team doesn't have enough bandwidth to solve this issue, and we believe this should be done.

So, we're asking for helping hands for this issue, the change is limited in one cpp file [python_generator.cc](https://github.com/grpc/grpc/blob/master/src/compiler/python_generator.cc). Thanks ahead :)

**Comment by naphta** [comment]
> To people we are watching this issue, unfortunately, the gRPC Python team doesn't have enough bandwidth to solve this issue, and we believe this should be done.
> 
> So, we're asking for helping hands for this issue, the change is limited in one cpp file [python_generator.cc](https://github.com/grpc/grpc/blob/master/src/compiler/python_generator.cc). Thanks ahead :)

Happy to give it a whirl; how would I go about testing / generating a new proto file or would it be a case of building grpc_tools from scratch for each change I make?

**Comment by lidizheng** [comment]
@naphta Currently, yes. The easiest way to compile is using our tooling script

```shell
# Don't forget to init submodules
git submodule update --init
# A parallel compilation speed up, you can set to the number of cores on your machine.
export GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=4
# Compile both grpc and grpc_tools
tools/run_tests/run_tests.py -l python --compiler python3.7 --newline_on_success -j 8 --build_only
# It generates a virtualenv as output
source py37_native/bin/activate
```

Feel free to change those parameters, or build for different Python version. As for testing, we don't have testing for PEP8 compliance (unfortunately), but all of our tests will use generated file for the newly compiled version.

```shell
# Remove the --build_only from above command, it would run the tests for you.
tools/run_tests/run_tests.py -l python --compiler python3.7 --newline_on_success -j 8
```

or you can run specific test case without re-build:

```shell
source py37_native/bin/activate
# export GRPC_PYTHON_TESTRUNNER_FILTER="unit._exit_test.ExitTest.test_in_flight_unary_unary_call"
python src/python/grpcio_tests/setup.py test_lite
```

**Comment by 27149chen** [comment]
please re-open this issue
