### ISSUE TITLE
Please make vector I/O (readv/writev) optional

### ISSUE THREAD

**Issue by sbc100** [grpc/grpc#5026]
For the Native Client port this code either needs to be optional, or we need some kind of emulation code for these functions.

**Comment by ahedberg** [comment]
sendmsg and recvmsg will be implemented in nacl_io of the Native Client SDK (https://chromium.googlesource.com/chromium/src/+/master/native_client_sdk/src/libraries/nacl_io/), so additional changes to gRPC shouldn't be necessary.
