### ISSUE TITLE
channel connection never recovers if dns_on_resolved(addresses==nullptr)

### ISSUE THREAD

**Issue by ksophocleous** [grpc/grpc#5034]
we are on `release_0-12` (more specifically 2f0474075962e5cc43dd16882e2e7f272c6e6156) and we're experiencing what seems to be an issue on Windows.

If we disable our ethernet adapter, eventually we're getting `dns_on_resolved` with `addresses` being `nullptr`. When this happens, even if the ethernet is enabled again, the connection will never be reestablished. 

It appears that dns resolution is never happening again after this.

It should be noted that the channel state is still `GRPC_CHANNEL_TRANSIENT_FAILURE` so we don't know how to detect this.

Is there something we're doing wrong or is this an actual issue?

Is there a workaround for now?

**Comment by ctiller** [comment]
I believe this is fixed in 0.13 (or 13.1).
