### ISSUE TITLE
Generating Server's and Client's class

### ISSUE THREAD

**Issue by Mwea** [grpc/grpc#5035]
Hi ! 
I just tried to apply the "Hello World !" tutorial for cpp and was wondering, why protobuf is not generating two files like helloworld_server.h helloworld_client.h containing class with empty declarations of methods ? This could be very simple to make it automatic

I'm sure that I missed something..

**Comment by yang-g** [comment]
Hi,

Did you install gRPC? Are you saying when you ran make, no pb.h and pb.cc files were generated? Does it print out any error message?
