### ISSUE TITLE
RPC call blocks when returning medium amounts of data from the server

### ISSUE THREAD

**Issue by atoader** [grpc/grpc#5037]
I have modified the helloworld C++ example to reproduce the failure.
In a for loop, the client sends a standard HelloRequest message and waits for the reply from the server.
The server generates a large amount of data for each request and sends it back.
After a number of requests, the communication blocks.
server - [http://pastebin.com/WkigQv0L](http://pastebin.com/WkigQv0L)
client - [http://pastebin.com/5x91D2sB](http://pastebin.com/5x91D2sB)

If I terminate the client manually, CTRL+C, the server prints out the message below and dies.

>  E0203 17:06:51.760010922   27328 chttp2_transport.c:527]     server stream 7 still included in list 9
> Aborted

All the other files from examples/cpp/helloworld are untouched.

I am using release_0_12 : a9c61bc512758afab2fbc7c7635c8baf2f38a722

OS: Linux alex 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by woland84** [comment]
+1 I think the same problem affects my project as well.

**Comment by yang-g** [comment]
Thanks for reporting. This is likely the same issue as #5018. I will take a look tomorrow.

**Comment by yang-g** [comment]
Could you check whether #5114 fixes the problem? Thanks.

**Comment by atoader** [comment]
Looks like that did it. Thanks for the great work!
