### ISSUE TITLE
check_copyright.py is broken for existing files

### ISSUE THREAD

**Issue by dsymonds** [grpc/grpc#5051]
The general guidance I've always received from lawyers (and from places like http://www.copyright.gov/eco/help-publication.html) is that if you're updating a source file, don't increase the year of copyright notices, since the copyright applies to when the source file was first committed, and doesn't refresh/extend just because some minor change is made to it (which would permit indefinite copyright extension!).

check_copyright.py is demanding that copyright years cover the current year (e.g. #5041). It's fine for the year of the notice to be extended (e.g. `2015` -> `2015-2016`), but it's unnecessary, and leads people to change instead of extend it (e.g. `2015` -> `2016`), which is wrong.

@ejona86 @dberlin @ctiller

**Comment by nathanielmanistaatgoogle** [comment]
@dsymonds: have you verified that the tool does not catch mistakenly-changed-instead-of-extended bugs? If it lets such mistakes slip by, it certainly shouldn't and that's a bug that should be fixed no matter what the policy on extension is determined to be.

**Comment by ejona86** [comment]
It didn't stop me at the time and I don't think we have any reason to believe it has been fixed. That actually seems harder for the tool to implement since it has to compare history.

**Comment by dberlin** [comment]
Here's the short version:
Unless you plan on people using this code in 100+ years (literally), *and*
you want to sue someone *in 100* years over it, don't worry about updating
the copyright years.
