### ISSUE TITLE
C core sometimes returns error code = 1 (Cancelled) when the client hasn't cancelled

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5069]
I've seen it in two different scenarios when helping people debug failed RPCs. It confuses people trying to debug, and doesn't conform to https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by jcanizales** [comment]
Maybe it's the server setting the code, though. If the C library doesn't set "cancelled" except when the call is actually cancelled, I'll move the bug to the server devs.

**Comment by jcanizales** [comment]
CC @timburks

**Comment by ctiller** [comment]
Need more information

**Comment by jcanizales** [comment]
Does the C library ever set status to cancelled, other than when the call is explicitly cancelled by the caller?

**Comment by jayantkolhe** [comment]
Not seen in a while.. Is this still occuring/relevant? Please reopen if you still see it.
