### ISSUE TITLE
Add name of the error code to the error description

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5071]
When people log the `NSError` of a failed RPC, the error code is only present numerically. It'd be much better to add the code name to the description.

**Comment by jcanizales** [comment]
CC @timburks

**Comment by ctiller** [comment]
So the error code is present on the NSError, and the description is there too?
And this is just mutating what gets logged?

Not sure this is a GA blocker.

**Comment by jcanizales** [comment]
No, it's adding the name of the error code to the description when the NSError is created.

I wouldn't say it's a GA blocker either.

**Comment by ctiller** [comment]
Removing it from the milestone then.

**Comment by jtattermusch** [comment]
Reassigning and removing P1 label. Please close if appropriate.
