### ISSUE TITLE
Document Bazel build instructions for gRPC

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5082]

**Comment by photex** [comment]
o/

This would be so welcome. I've been banging my way through this and I have no idea what mistakes I've already made. :)

**Comment by hsaliak** [comment]
@jcanizales assigning this to you -- let me know if this not something you can take on.
/cc @nicolasnoble

**Comment by jcanizales** [comment]
I think the first logical step is to have Bazel build tests on Jenkins/Travis. That way I'm sure that what I document is (still) correct and complete, and we know that it'll stay that way. So I'll do that first.

**Comment by hsaliak** [comment]
Removing this as a GA launch blocker, please update the milestones if you have any objections @jcanizales
