### ISSUE TITLE
Python process hangs on exit

### ISSUE THREAD

**Issue by inconshreveable** [grpc/grpc#5084]
Sample code:

```python
import rpx
import sys
from grpc.beta import implementations

ch = implementations.insecure_channel("127.0.0.1", 2000)
svc = rpx.beta_create_Service_stub(ch)
resp = svc.Get(rpx.Req(), 1)
sys.exit(1)
```

#### Setup
You'll need a very simple proto file with one service having a single function call. You must implement and run the server portion.

#### Expected
The program runs a single request and then exits

#### Observed
The program runs a single request, successfully receives the response and then hangs when calling sys.exit.

#### Version
0.11.1-1~bpo8+1

The concurrent.futures module registers an atexit handler called `_python_exit` which prevents the program from terminating. I believe it's waiting for grpc worker threads to terminate, but didn't dig too much deeper.

**Comment by inconshreveable** [comment]
And for context on why this matters:

A python web application that is using grpc to communicate with backend services. The shutdown failure breaks the code reloading and ruins the fast dev iteration cycle.

**Comment by soltanmm** [comment]
I believe this is a duplicate of #4969, though I'd recommend not using version 0.11.x anymore.

**Comment by inconshreveable** [comment]
Yep, this a duplicate, we can close it out.
