### ISSUE TITLE
Node on Linux installation friction log

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5089]
To test installing the Node package on Linux, install Node.js and run the following command in the `examples/node` directory:

```sh
export MIRROR=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts/
npm install $MIRROR/grpc.tgz --grpc_node_binary_host_mirror=$MIRROR
```

Then run the Hello World example to verify that the library works.

This should work with Node 0.10.x, 0.12.x, 4.x, 5.x, and any version of io.js.

**Comment by hsaliak** [comment]
# Complete instructions
Clone gRPC and access the examples
```
git clone https://github.com/grpc/grpc
cd grpc/examples/node
```
Install gRPC Node
```
export MIRROR=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts/
npm install $MIRROR/grpc.tgz --grpc_node_binary_host_mirror=$MIRROR

```
Run the server from this directory (examples/node).
`$ node ./greeter_server.js &
`
Run the client
```
$ # from this directory
$ node ./greeter_client.js
```

**Comment by vivitas** [comment]
Commenting so issue can be assigned to me.

**Comment by hsaliak** [comment]
@vivitas  thanks!

**Comment by vivitas** [comment]
(working on instructions from first comment)
- As someone new to Mac, I have no idea if I should be in some special directory to create examples/node; I've decided to create this folder in my home directory

- When I try to run the commands specified:
`$ export MIRROR=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts/
$ npm install $MIRROR/grpc.tgz --grpc_node_binary_host_mirror=$MIRROR`
I get following error
`-bash: npm: command not found`

- Google search leads me to http://coolestguidesontheplanet.com/installing-node-js-on-osx-10-10-yosemite/ per instructions there downloaded and installed npm

- Running the command again, I get a bunch of errors:
`$ npm install $MIRROR/grpc.tgz --grpc_node_binary_host_mirror=$MIRROR

> grpc@0.12.0 preinstall /Users/zfilip/examples/node/node_modules/.staging/grpc-b6fabe4c
> npm install node-pre-gyp

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-pre-gyp"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zfilip/examples/node/node_modules/.staging/grpc-b6fabe4c/npm-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/Users/zfilip/examples/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts//grpc.tgz" "--grpc_node_binary_host_mirror=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts/"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.12.0 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.12.0 preinstall script 'npm install node-pre-gyp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc


npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zfilip/examples/node/npm-debug.log`

- [npm-debug.log.zip](https://github.com/grpc/grpc/files/123811/npm-debug.log.zip)

**Comment by murgatroid99** [comment]
@vivitas 

 1. The `examples/node` directory refers to the one in this repository. 

 2. Please run this on a Linux machine.

**Comment by vivitas** [comment]
- Working with complete instructions. Cloning was successful.

- Installation was successful. I was required to install developer tools so I clicked install now but that takes forever.

- Running command:
`$ ./greeter_server.js & 
[1] 76534
$ -bash: ./greeter_server.js: Permission denied
[1]+  Exit 126                ./greeter_server.js
`

-  After running chmod I get error again:
`$ ./greeter_server.js & 
[1] 76549
zfilip-macbookpro2:node zfilip$ ./greeter_server.js: line 1: /Applications: is a directory
./greeter_server.js: line 2: README.md: command not found
./greeter_server.js: line 3: README.md: command not found
./greeter_server.js: line 4: README.md: command not found
./greeter_server.js: line 5: README.md: command not found
./greeter_server.js: line 6: README.md: command not found
./greeter_server.js: line 7: README.md: command not found
./greeter_server.js: line 8: README.md: command not found
./greeter_server.js: line 9: README.md: command not found
./greeter_server.js: line 10: README.md: command not found
./greeter_server.js: line 11: README.md: command not found
./greeter_server.js: line 12: README.md: command not found
./greeter_server.js: line 13: README.md: command not found
./greeter_server.js: line 14: README.md: command not found
./greeter_server.js: line 15: README.md: command not found
./greeter_server.js: line 16: README.md: command not found
./greeter_server.js: line 17: README.md: command not found
./greeter_server.js: line 18: README.md: command not found
./greeter_server.js: line 19: README.md: command not found
./greeter_server.js: line 20: README.md: command not found
./greeter_server.js: line 21: README.md: command not found
./greeter_server.js: line 22: README.md: command not found
./greeter_server.js: line 23: README.md: command not found
./greeter_server.js: line 24: README.md: command not found
./greeter_server.js: line 25: syntax error near unexpected token `('
./greeter_server.js: line 25: ` * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT'

[1]+  Exit 2                  ./greeter_server.js
`

- I've only now noticed that I did not include `node` before running the command. Doing so results in following error:
`$ node ./greeter_server.js & 
[1] 77202
$ module.js:341
    throw err;
    ^

Error: Cannot find module 'grpc'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/zfilip/code/grpc/examples/node/greeter_server.js:36:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

[1]+  Exit 1                  node ./greeter_server.js`

**Comment by vivitas** [comment]
On Linux machine, installing Node.js was painful. Instructions provided are simply wrong. Anyway, I finally managed to get it installed.

- Running greeter_server.js gives following error:
`[1] 27074
$ 
module.js:340
    throw err;
          ^
Error: Cannot find module 'grpc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/google/home/zfilip/grpctest/grpc/examples/node/greeter_server.js:36:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

[1]+  Exit 8                  nodejs ./greeter_server.js`

**Comment by murgatroid99** [comment]
A few questions:

 1. What was your current directory when you ran the installation instructions?
 2. What was the error when you ran the installation instructions?
 3. What did you eventually have do to successfully install it?
 4. What version of node are you using? (the output of `node --version`)

**Comment by vivitas** [comment]
1. I started by creating a directory to hold all data I use for test in my home directory: ~/grpctest/
2. Installation of Node.js was the problematic one, before I started instructions from this issue.
  - After downloading file from https://nodejs.org/en/download/ I started reading README.MD and there were no information on installation, only on building. However, it was not specified where commands should be run.
  - I changed directory to /lib/node_modules/npm and this is how process went:
    ```
    $ ./configure 
    $ make
    make: Nothing to be done for `all'.
    $ sudo make install
    node cli.js install -g -f 
    make: *** [install] Error 1
    ````
  - That was the only configure file I could find in directory I downloaded so I gave up. I turned to instructions from web page (https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) 
```
$ curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
## Installing the NodeSource Node.js 5.x repo...


## Populating apt-get cache...

+ apt-get update
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@zfilip.mtv.corp.google.com InRelease
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@zfilip.mtv.corp.google.com InRelease
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons InRelease
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@zfilip.mtv.corp.google.com/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-desktop@zfilip.mtv.corp.google.com/main i386 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@zfilip.mtv.corp.google.com/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-trusty-stable-priority@zfilip.mtv.corp.google.com/main i386 Packages
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons/main amd64 Packages
Hit https://rapture-prod.corp.google.com goobuntu-puppet-addons/main i386 Packages
Ign https://deb.nodesource.com trusty InRelease
Ign https://deb.nodesource.com trusty Release.gpg
Ign https://deb.nodesource.com trusty Release
Err https://deb.nodesource.com trusty/main Sources
  Could not resolve proxy: apt-squid.corp.google.com
Err https://deb.nodesource.com trusty/main amd64 Packages
  Could not resolve proxy: apt-squid.corp.google.com
Err https://deb.nodesource.com trusty/main i386 Packages
  Could not resolve proxy: apt-squid.corp.google.com
W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/trusty/main/source/Sources  Could not resolve proxy: apt-squid.corp.google.com

W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/trusty/main/binary-amd64/Packages  Could not resolve proxy: apt-squid.corp.google.com

W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/trusty/main/binary-i386/Packages  Could not resolve proxy: apt-squid.corp.google.com

E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting

$ sudo apt-get install -y nodejs
```
The last command appeared to work.

3. Covered in previous answer.

4. v5.6.0

**Comment by murgatroid99** [comment]
OK, what about the gRPC problems? What happened when you ran the instructions in this issue?

**Comment by vivitas** [comment]
Everything was fine and straight-forward up to a point when I tried to start a server. At that moment, error happened which I included in a comment: https://github.com/grpc/grpc/issues/5089#issuecomment-182103384

**Comment by murgatroid99** [comment]
OK, thank you for your help. Would you mind pasting the full shell log of running those six commands, so that I can figure out what went wrong?

**Comment by ctiller** [comment]
Successful install on RHEL7.

Used instructions from Node website to install Node itself: https://nodejs.org/en/download/package-manager/

**Comment by murgatroid99** [comment]
I also successfully ran this on a clean install of Debian Jessie. I installed Node by copying from the tarball into /usr/local.

**Comment by vivitas** [comment]
Unfortunately I do not have log from the time I run commands.
