### ISSUE TITLE
Node on Mac installation friction log

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5090]
To test installing the Node package on Mac, install Node.js and run the following command in the `examples/node` directory:

```sh
export MIRROR=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts/
npm install $MIRROR/grpc.tgz --grpc_node_binary_host_mirror=$MIRROR
```

Then run the Hello World example to verify that the library works.

This should work with Node 0.10.x, 0.12.x, 4.x, 5.x, and any version of io.js.

**Comment by hsaliak** [comment]
# Complete instructions
Clone gRPC and access the examples
```
git clone https://github.com/grpc/grpc
cd grpc/examples/node
```
Install gRPC Node
```
export MIRROR=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/101/artifact/artifacts/
npm install $MIRROR/grpc.tgz --grpc_node_binary_host_mirror=$MIRROR

```
Run the server from this directory (examples/node).
`$ node ./greeter_server.js &
`
Run the client
```
$ # from this directory
$ node ./greeter_client.js
```

**Comment by rok987** [comment]
This has worked for me. I followed the exact steps mentioned in the Complete Instructions section. The actual installation of gRPC with the npm command took about 1 minute on my machine.

**Comment by murgatroid99** [comment]
I just realized that with the instructions I gave, you would have compiled the library from scratch on Mac, which is probably why it took so long. Would you mind running it again, replacing the export command with the following?

```sh
export MIRROR=https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=linux/123/artifact/artifacts/
```

**Comment by rok987** [comment]
Tried it again with the new MIRROR location and it also worked.
