### ISSUE TITLE
Dynamically navigable modules

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5094]
Right now a developer who uses gRPC Python's Beta API can't do very much with it at the Python read-eval-print loop. It would be nice for the GA API to have a better story:

```
>>> import grpc
>>> dir(grpc)
# Something helpful is printed
>>> help(grpc.channel.Channel)
# Documentation is printed
```

**Comment by ctiller** [comment]
WHEN we get to reflection (and protoc stuff, and...) I'd love to be able to do the following:

```python
import grpc
c = grpc.channel.Channel('bigtable.google.com')
dir(c)
```

and get a listing of methods defined by bigtable.google.com.

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm & @kpayson64: as of `0.15.0`, this issue cannot be resolved because interactions like `dir(grpc)` and `help(grpc.Channel)` show too much (private attributes and imported attributes, to be specific) rather than too little. Is that because of the way we're currently doing packaging?

**Comment by nathanielmanistaatgoogle** [comment]
I think this has been fixed since [pull request 6938](https://github.com/grpc/grpc/pull/6938).
