### ISSUE TITLE
HTTP2 interop test result aggregation is broken

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#5108]
aggregate_http2_results() in run_interop_test now returns None because stdout is empty. This change is caused by a PR for test stability improvement: #4619. 

We need to come up another way to aggregate the results.

**Comment by hsaliak** [comment]
@ctiller @carl-mastrangelo per #5145 it seems that we still need to fix this the right way, however, is this a blocker for GA?

**Comment by ctiller** [comment]
No

**Comment by srini100** [comment]
Please reopen if the issue still exists.
