### ISSUE TITLE
Python installation testing - Mac

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5112]
Requirements:

```
python 2.7
pip
```
Prerequisite steps:

```
pip install enum34 futures six
pip install --pre protobuf>=3.0.0a3
```
Note: unfortunately, being on TestPyPI requires that our dependencies be installed separately. This will not be the case once we get on PyPI.

Potential Pitfalls:
The --pre flag may not be necessary (or even available?) for some versions of pip. If pip whines about it, drop the flag.

Requirements:

- python 2.7

Steps:
 Ensure python 2.7 is the version of python used by running
```
python -V
```
 Install gRPC
```
pip install -i https://testpypi.python.org/simple grpcio 
```
 Test the installation - launch a python interpreter and run
```
>> import grpc
>> dir(grpc) 
>> Ctrl-D
```  
Next, try the hello world example.

```
git clone https://github.com/grpc/grpc
```
Navigate to the "hello, world" Python example:

```
$ cd grpc/examples/python/helloworld 
```
Run the server
```
$ python2.7 greeter_server.py & 
```
Run the client
```
$ python2.7 greeter_client.py
```
If all goes well, you will receive the message:

> Greeter client received: Hello, you!

**Comment by soltanmm** [comment]
This issue has done its part.
