### ISSUE TITLE
C++ oauth2_auth_token interop test: pthread_mutex_lock assertion failed

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5119]
The test seems to be failing very regularly, with an interesting error message:
```
I0207 03:00:13.009609588       1 client.cc:89]               Testing these cases: oauth2_auth_token
E0207 03:00:13.009827228       1 sync_posix.c:51]            assertion failed: pthread_mutex_lock(mu) == 0
```

This also seems to be preventing green on interop test suite, so fixing this soon would be really helpful.

https://grpc-testing.appspot.com/job/gRPC_interop_master/2747/testReport/(root)/tests/cloud_to_prod_auth_c___oauth2_auth_token/

https://grpc-testing.appspot.com/job/gRPC_interop_master/2748/testReport/(root)/tests/cloud_to_prod_auth_c___oauth2_auth_token/

**Comment by jtattermusch** [comment]
@adelez FYI

**Comment by yang-g** [comment]
This seems to be caused by the GrpcLibrary refactoring and we are missing a grpc_init somewhere. Still looking.

**Comment by yang-g** [comment]
Seems fixed.
