### ISSUE TITLE
Build binary protobuf runtime artifacts

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5135]
@jtattermusch - we'll need to expand things here

Especially Ruby needs a prebuilt protobuf

**Comment by ctiller** [comment]
(not P0)

**Comment by ctiller** [comment]
@murgatroid99: is this done?

**Comment by murgatroid99** [comment]
I guess so. We are distributing `protoc`, if that's what this is asking for.

**Comment by murgatroid99** [comment]
If I understand this issue correctly, it has been resolved. We can reopen if that is not the case.
