### ISSUE TITLE
Python packages broken in 0.13

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5152]
Trying to install python package from release-0_13 branch. All the distribtests seem to be failing.

```
+ pip install /var/local/jenkins/grpc/input_artifacts/grpcio-0.13.0rc1.tar.gz
Unpacking /var/local/jenkins/grpc/input_artifacts/grpcio-0.13.0rc1.tar.gz
  Running setup.py egg_info for package from file:///var/local/jenkins/grpc/input_artifacts/grpcio-0.13.0rc1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-a0xCXP-build/setup.py", line 57, in <module>
        import grpc_version
    ImportError: No module named grpc_version
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-a0xCXP-build/setup.py", line 57, in <module>

    import grpc_version

ImportError: No module named grpc_version
```

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/59/architecture=x64,language=python,platform=linux/console

**Comment by jtattermusch** [comment]
@ctiller  @nicolasnoble  heads up, this might have to do with our recent changes to versioning.

**Comment by soltanmm** [comment]
Is this the linux build using the binary on GCS?

**Comment by jtattermusch** [comment]
No, it's forcibly using whatever we've built in the build_artifacts step
previously (at least I hope so).

**Comment by soltanmm** [comment]
It's because `grpc_version` wasn't added to the PYTHON-MANIFEST. Fixin'...

**Comment by jtattermusch** [comment]
According to the last run on the release branch, this seems to be fixed. Thanks for quick action!

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/63/architecture=x64,language=python,platform=linux/console
