### ISSUE TITLE
Optimize generate_projects.sh

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5154]
This is taking longer than it needs to :)

Consider pre-merging build yaml files and running plugins, and then emitting the pickled result.

This would allow each template to quickly load it's input data, and turn one of the bulkier operations we do nearly 40 times into a once-off.

**Comment by ctiller** [comment]
@nicolasnoble @jtattermusch @adelez heads up

**Comment by soon** [comment]
Was the issue fixed with 560c9017c4ce73322cc541eef421e607bd1856a0 or still waiting for the help? :)
