### ISSUE TITLE
Fix ruby tests for upstream/master on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5160]
Currently this is making master build red.

If this is not doable in the foreseeable future, let's just disable the test to make master builds green once again.

**Comment by nicolasnoble** [comment]
Test has been disabled - making it work would take quite some engineering. Keeping it around, but not sure it'll ever get done.

**Comment by pbennett** [comment]
Considering the problems I'm seeing with my Ruby GRPC client under Windows (it seems completely broken with any kind of concurrency [#7663]) and seeing issues like this (disabling all Ruby/windows tests?) as well as grpc-tools being broken out of the box (#8301), it's kind of sounding like Windows really isn't much of a supported platform?
