### ISSUE TITLE
Fix C++ tests for upstream/master on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5161]
Currently this is making master build red.

@nicolasnoble  @ctiller is this actually feasible?

If C++11 is a problem, prehaps we could try with VS2015 that should be doing much better.
And we need protobuf for this, right? Can we just cmake build protobuf for this?

If not doable let's disable the tests on master so we see green again.

**Comment by larsonmpdx** [comment]
you need gtest, glfags, and protobuf (in addition to zlib and ssl, I assume you have those building fine already).  gflags and protobuf get set up with cmake and gtest has a solution file bundled with it.  see #3278 for possibly outdated build instructions

**Comment by ctiller** [comment]
Dup of #1934
