### ISSUE TITLE
Add PHP tests for upstream/master on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5162]
Currently this is making master build red.

If this is not currently feasible, let's disable the tests on windows so we see green again.

**Comment by stanley-cheung** [comment]
PHP hasn't been tested on Windows yet. I have disabled the build for now. Jenkins is still showing the red icon on those 2 cells in the configuration matrix but they haven't been run for a few runs. Will check back tomorrow if the icon will check to a dull gray circle.

**Comment by jtattermusch** [comment]
Let's leave this open because at some point we'll definitely need this.
Changing the milestone to GA.

**Comment by nathanielmanistaatgoogle** [comment]
Should this be retitled? Should this be closed? Can it be given a priority?

**Comment by ZhouyihaiDing** [comment]
Should this PR be retitled as "Add PHP tests for upstream/master on Windows"?
