### ISSUE TITLE
Fix Python tests for upstream/master on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5163]
Currently this is making master build red.

In terms of priorities, this should be done after we have the artifacts building on windows.

If this is not currently feasible, let's disable the tests on windows so we see green again.

**Comment by soltanmm** [comment]
Tests are getting runnable again via #6797... where they're still red. But, hey, at least we can get back to debugging.

**Comment by soltanmm** [comment]
The tests currently failing are:

- [ ] tests.py.test._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest
- [ ] tests.py.test._face_interface_test.DynamicInvokerFutureInvocationAsynchronousEventServiceTest
- [ ] tests.py.test._face_interface_test.DynamicInvokerBlockingInvocationInlineServiceTest
- [ ] tests.py.test._secure_interop_test.SecureInteropTest
- [ ] tests.py.test._insecure_interop_test.InsecureInteropTest
- [ ] tests.py.test._not_found_test.NotFoundTest
- [ ] tests.py.test._face_interface_test.MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest
- [ ] tests.py.test._beta_features_test.ContextManagementAndLifecycleTest
- [ ] tests.py.test.beta_python_plugin_test.PythonPluginTest
- [ ] tests.py.test._rpc_test.RPCTest
- [ ] tests.py.test._face_interface_test.GenericInvokerBlockingInvocationInlineServiceTest
- [ ] tests.py.test._face_interface_test.GenericInvokerFutureInvocationAsynchronousEventServiceTest
- [ ] tests.py.test._beta_features_test.BetaFeaturesTest

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: will this be fixed by the integration of [pull request 6797](https://github.com/grpc/grpc/pull/6797)?

**Comment by soltanmm** [comment]
That PR is necessary but its sufficiency is unknown due to recent changes. #6791 (what it's based on to get our tools package `protoc` to be available to the plugin tests) needs to get pulled out of rebase hell (the plugin got build-broken on at least one mac worker  [for tests not artifacts afaict] presumably because Apple removed a feature from Xcode [thread-local storage] for inexplicable reasons).
