### ISSUE TITLE
MacOS worker: Too many open files in system

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5166]
I started seeing these error messages on MacOS workers. It's failing many of the tests. Restarting the worker helps a little bit but then the problem comes back.

Possible options:
1. *We need to add more mac workers ASAP*, this is becoming critical. Then we can reduce number of executor threads on each worker
2. investigate whether we are leaking some file descriptors

```
Caused by: java.io.IOException: Cannot run program "git" (in directory "/jenkins/workspace/gRPC_master/config/dbg/language/csharp/platform/macos"): error=23, Too many open files in system
```

**Comment by jtattermusch** [comment]
@adelez  can you please give an update on where we are with the mac worker?

**Comment by jtattermusch** [comment]
@ctiller @a11r FYI

**Comment by jtattermusch** [comment]
seems like @nicolasnoble has tracked this down to python's tox process not exiting.

**Comment by adelez** [comment]
Looks like this is resolved. @nicolasnoble, thank you for tracking it down! I'm assigning it to you for adding an entry in the maintenance log. :)

**Comment by jtattermusch** [comment]
Saw this just now:

https://grpc-testing.appspot.com/job/gRPC_master/15407/config=dbg,language=c,platform=macos/console

**Comment by jtattermusch** [comment]
Doesn't look like we're seeing this anymore. Closing as part of buildpony bankruptcy.
