### ISSUE TITLE
NodeJS client fails to parse "repeated int32"

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc#5174]
I have a Java server with a response object containing a "repeated int32".  When the field is unset, NodeJS will parse the rest of the message just fine.  When the value is set the line here https://github.com/grpc/grpc/blob/release-0_11/src/node/src/client.js#L316 ends up throwing saying it encountered unexpected values.  I've confirmed that the Go and Java clients do properly parse the message.

**Comment by murgatroid99** [comment]
I am having trouble reproducing this. Can you provide a simple message that causes this error, and the binary encoding of that message?

**Comment by jhspaybar** [comment]
Sure, I have something minimally reproducible:

```
service APIMetadataService {
	rpc GetVideoMetadata(MetadataRequest) returns (VideoMetadata) {}
}

message MetadataRequest {}

message VideoMetadata {
  repeated int32 actors = 20;
}
```


Java implementation below

```
@Override
public void getVideoMetadata(final MetadataRequest request, final StreamObserver<VideoMetadata> responseObserver) {
  return VideoMetadata.newBuilder().addAllActors(Lists.newArrayList(10)).build();
}
```

Golang output logging response is "Response: actors:10"

I modified this file to get extra debug info here https://github.com/grpc/grpc/blob/master/src/node/src/client.js#L326 with
```
try{                                                                                                                                                          
  var data = response.read;
  console.log("Parsing data: ", data);
  deserialized = deserialize(data);
} catch (e) {
  console.log("Error: ", e);
   /* Change status to indicate bad server response. This will result
   * in passing an error to the callback */
   status = {
    code: grpc.status.INTERNAL,
    details: 'Failed to parse server response'
  };
}
```
The output is 
```
Parsing data:  <Buffer a2 01 01 0a>
Error:  [Error: Illegal wire type for field Message.Field .my.namespace.api.VideoMetadata.actors: 2 (0 expected)
```
Finally, if I change my implementation in to Java to just be `return VideoMetadata.newBuilder().build();`

The Node output becomes
```
Parsing data:  <Buffer >
Response:  { actors: [] }
```
(I have a console.log of the response in my code)

**Comment by murgatroid99** [comment]
It looks like your generated Java code has `[packed=true]` set on the `actors` field. If I modify the proto you provided with that option, the Node code serializes that proto to the same buffer and deserializes it correctly.

**Comment by jhspaybar** [comment]
Hmm, interesting.  So it seems like Go and Java are assuming packed=true, but that NodeJS isn't?  I'm using syntax=3 at the top of my file, maybe node doesn't understand this in it's parser or something?  I thought packed was default.

**Comment by murgatroid99** [comment]
The Node library uses Protobuf.js internally for protobufs, and it does understand `syntax = "proto3";`. The proto3 Language Guide specifically says

> For historical reasons, `repeated` fields of scalar numeric types aren't encoded as efficiently as they could be. New code should use the special option `[packed=true]` to get a more efficient encoding.

If the Go and Java protobuf runtimes are packing repeated fields by default, that is a bug on their end.

**Comment by jhspaybar** [comment]
Thanks for the help!  I just went with reporting the bug to the side that was different, but I suppose now that you've shown me that, I should go report the bugs over there and reference this :)  Feel free to close, and thanks for your help!

**Comment by dsymonds** [comment]
It doesn't really matter what the encoders are doing. The NodeJS proto parser is at fault. Compliant proto parsers are required to cope with both non-packed and packed repeated fields.

**Comment by dsymonds** [comment]
More pertinent is this comment in `descriptor.proto`:

```
  // The packed option can be enabled for repeated primitive fields to enable
  // a more efficient representation on the wire. Rather than repeatedly
  // writing the tag and type for each element, the entire array is encoded as
  // a single length-delimited blob. In proto3, only explicit setting it to
  // false will avoid using packed encoding.
  optional bool packed = 2;
```

So proto3 encoders are *meant* to default to packed=true.

**Comment by murgatroid99** [comment]
There's some inconsistency with the documentation here. The quote I mentioned above explicitly says that packed=true is *not* the default in proto3.

Packed repeated fields are encoded with a different wire type than non-packed repeated fields, and I can't find anything in the documentation that indicates that parsers should accept fields with known id numbers and incorrect wire types.

**Comment by dsymonds** [comment]
That document that you referenced needs fixing, probably just removing that sentence. I'll see if I can chase that up.

It looks like the public docs don't mention it, but it is definitely an expectation that parsers cope with differing wire types for specifically this case (packed vs. non-packed). That's been the case since late 2009.

**Comment by jhspaybar** [comment]
If that is the case, should this actually be pushed further upstream to Protobuf.js then?

**Comment by dsymonds** [comment]
I've got a couple of changes pending to update the docs to match what I'm saying.

If it's Protobuf.js that is doing the parsing, it's the one that needs fixing.

**Comment by murgatroid99** [comment]
gRPC now supports code statically generated by `protoc`, which uses the google-protobuf library instead of Protobuf.js for runtime proto handling. If you use that option, it should not have this problem.

**Comment by LiberiFatali** [comment]
I also encounter this error with `repeated float`, I solve it by adding `[packed=true]` to the `.proto` file.
