### ISSUE TITLE
High-level documentation for Deadlines/timeouts

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5177]
I've recently got some questions about the semantics of deadlines in gRPC. I think this is a topic that should be properly explained somewhere (grpc.io, the /doc directory or somewhere else).

People usually ask:
-- why is grpc using the concept of Deadlines (vs relative timeouts)  - (there've been lots of discussion about this, I think the main reason comes out as that deadlines are more convenient if you perform multiple requests to backends to satisfy a single request or if a backend needs to call out another backend).
-- how is the client/server clock skew handled (we convert to relative timeout on the wire).

**Comment by jtattermusch** [comment]
CC @a11r @ejona86

**Comment by hsaliak** [comment]
cc @stanley-cheung 
@jtattermusch an FAQ around deadlines will be really good to have, will you have the time to come up with answers to these questions and put it into a PR?

**Comment by jtattermusch** [comment]
Unfortunately, not anytime soon. I also don't feel that comfortable
describing what lead to some decisions around deadlines vs timeouts as I
wasn't involved in these discussions (they took place before I joined the
gRPC team ;-) ).
