### ISSUE TITLE
Service Descriptor not generated correctly in ***Grpc.cs (C#)

### ISSUE THREAD

**Issue by LeHerissonNinja** [grpc/grpc#5200]
Hi everyone,

we have a problem using the latest version of gRPC and the Protobuf compiler (Currently: Google.Protobuf.3.0.0-beta2 and Grpc.Tools.0.12.0).
We created a file called RawDataDemo.proto looking like this:

```
syntax="proto3";

package RawDataDemo;

service RawDataDemoService {
	rpc GetRawData (RawDataRequest) returns (stream RawDataReply) {}
}

message RawDataRequest {}

message RawDataReply {
	int64 DateTimeTicks = 1;
	repeated double ScanValues= 2;
}
```

We then generated code/files using this command: 
```
packages\Google.Protobuf.3.0.0-beta2\tools\protoc -I MyPath\InterfaceDefinition --csharp_out MyPath --grpc_out MyPath--plugin=protoc-gen-grpc=packages\Grpc.Tools.0.12.0\tools\grpc_csharp_plugin.exe MyPath\InterfaceDefinition\RawDataDemo.proto
```

Adding both new files (RawDataDemo.cs and RawDataDemoGrpc.cs) to our project, we get a compile error: "The type or namespace name 'RawDataDemo' does not exist in the namespace 'RawDataDemo'".

We observed that the service descriptor property in the RawDataDemoGrpc.cs file is not generated correctly.

Here the generated code:

```
// service descriptor
public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
{
    get { return global::RawDataDemo.RawDataDemo.Descriptor.Services[0]; }
}
```

We then compared it with an older demo we made (using Google.Protobuf.3.0.0-alpha4 and Grpc.Tools.0.7.1) and observed that the class RawDataDemo has been renamed in RawDataDemoReflection.
It should then generate this code:

```
// service descriptor
public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
{
    get { return global::RawDataDemo.RawDataDemoReflection.Descriptor.Services[0]; }
}
```

Changing it manually is working. 
We were able to reproduce this behavior multiple times with several proto files. We even tried to reproduce your "Math" example. However, the result remained the same.

Are we doing something wrong?

Thanks for your help.
Regards

**Comment by jtattermusch** [comment]
Google.Protobuf.3.0.0-beta2 and Grpc.Tools.0.12.0 are basically incompatible.

Grpc.Tools.0.12 contains grpc_csharp_plugin that is compiled against protobuf 3.0.0-alpha4 and there's been a breaking change in the API between protobuf alpha4 and beta2.

I just published Grpc.Tools.0.13.0 and hour ago. You should be able to use that package together with Google.Protobuf.3.0.0-beta2 to generate your protobufs code and grpc stubs.

I believe this has been resolved, so closing. Feel free to reopen if you are still having issues.
