### ISSUE TITLE
Ruby Installation Friction testing - Windows

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5204]
## System Requirements: Ruby, git
Ensure Ruby is installed. Note: this is installation of a pre-req and issues encountered are not in scope for the friction testing of gRPC.

A possible way of installing this is:
 http://rubyinstaller.org/downloads/  - make sure to check the checkbox that says "Add Ruby executables to your PATH"

Installing the gem, from a terminal

```
gem install --pre grpc 
```
Testing it:

Clone the gRPC repository
```
 git clone https://github.com/grpc/grpc
```
Navigate to the Ruby examples directory:
```
$ cd grpc/examples/ruby
```
Run the greeter server/ client. This is best done from 2 consoles, server in one, client in another.

- Run the server

  ```sh
  $ # from this directory
  $ bundle exec ./greeter_server.rb &
  ```

- Run the client

  ```sh
  $ # from this directory
  $ bundle exec ./greeter_client.rb
  ```

**Comment by murgatroid99** [comment]
I attempted to run this on a clean Windows VM. The gem install command worked without a problem. The command to run the server fails with this error:

```
bundler: not executable: ./greeter_server.rb
```

If git is not installed, the command instead fails attempting to read the gemspec.

If I instead attempt to just run `ruby ./greeter_server`, I get the following output:

```
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/protobuf_c
 (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/google-protobuf-3.0.0.alpha.5.0.3-x86-mingw32/lib/google/protobuf.rb:50:
in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/google-protobuf-3.0.0.alpha.5.0.3-x86-mingw32/lib/google/protobuf.rb:47:
in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/mlumish/grpc/examples/ruby/lib/helloworld.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/mlumish/grpc/examples/ruby/lib/helloworld_services.rb:5:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./greeter_server.rb:41:in `<main>'
```

I can run `irb`, do `require "grpc"`, and create a server with `GRPC::RpcServer::new`.
