### ISSUE TITLE
Failing to compile on Mac

### ISSUE THREAD

**Issue by kriswuollett** [grpc/grpc#5219]
Set up my project by running on a Mac v10.11.3, Xcode 7.2.1:

```
git clone https://github.com/grpc/grpc.git
# no protobuf/grpc/openssl installed via homebrew
cd grpc
git submodule update --init
make
# dependencies like boringssl and protobuf get compiled
```

But then make ends with failure with:

```
[LD]      Linking /Users/kris/workspace/grpc/libs/opt/libgrpc++.dylib
Undefined symbols for architecture x86_64:
  "_gpr_cpu_num_cores", referenced from:
      grpc::CreateDefaultThreadPool() in create_default_thread_pool.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/kris/workspace/grpc/libs/opt/libgrpc++.dylib] Error 1
```

**Comment by jcanizales** [comment]
For `gpr_cpu_num_cores` to exist, either `GPR_CPU_IPHONE`, `GPR_CPU_POSIX`, `GPR_WIN32`, or `GPR_CPU_LINUX` need to be defined by `grpc/impl/codegen/port_platform.h`. Because of [this check](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/port_platform.h#L305), it then seems that `GPR_CPU_CUSTOM` is being defined instead.

But `GPR_CPU_CUSTOM` isn't defined anywhere in the codebase, so :question::question::question:

**Comment by vjpai** [comment]
Mac is GPR_CPU_POSIX . I've not seen the particular issue brought up here
before.

#define GPR_PLATFORM_STRING "osx"
#define GPR_CPU_POSIX 1

**Comment by kriswuollett** [comment]
I don't think its an issue with the preprocessor.  See [the results from my build of gRPC](https://gist.github.com/kriswuollett/c17f1637305da62f2057).  Rather _gpr_cpu_num_cores is being stripped from the dynamic grpc libraries.

**Comment by kriswuollett** [comment]
Looks like we just need -force_load for libgpr.a when building libgrpc.dylib.  Confirming by rebuilding from scratch.  Will probably have a pull request shortly.

**Comment by nicolasnoble** [comment]
This is odd. Why would it be removed from the link ? Using force_load is technically more of a workaround. The reason would be we aren't constructing the link line properly.

**Comment by jdmiranda** [comment]
Did this get fixed? I'm still having the same problem.

**Comment by makdharma** [comment]
Closing. Mac builds have been working for quite some time. @jdmiranda Please create another issue with the proper bug template if this is still broken for you.
