### ISSUE TITLE
protoc fails when using grpc_python_plugin with hyphenated file names.

### ISSUE THREAD

**Issue by tobinthecloud** [grpc/grpc#5226]
This command works as expected:

```
protoc --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` helloworld.proto 
```

But:

```
mv helloworld.proto hello-world.proto
protoc --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` hello-world.proto 
```

...results in this cryptic error:

`hello-world_pb2.py: Tried to insert into file that doesn't exist.
`

If I look at the output of protoc without the grpc plugin, I see that the hyphen gets converted to an underscore in the output pb filename, e.g.:

`protoc --python_out=. hello-world.proto
`

produces a file named "hello_world_pb2.py"

I suspect perhaps the grpc_python_plugin is losing track of that s/-/_/g conversion.

**Comment by nathanielmanistaatgoogle** [comment]
@haberman: it's news to me that hyphens are even allowed in `.proto` file names. Is what @tobinthecloud is describing and recommending here the right thing to do?

**Comment by nathanielmanistaatgoogle** [comment]
@jayantkolhe: please assign this issue to @haberman after adding him to the `grpc` organization so that he can be named as an issue assignee.

**Comment by nathanielmanistaatgoogle** [comment]
Punting; I don't see anything here that needs to be addressed before `1.1.0` is released.

**Comment by macnibblet** [comment]
This happens for files without hyphens to

```
$ python -m grpc_tools.protoc -I . --grpc_python_out=infinity/ common.proto aphrodite.proto
common_pb2.py: Tried to insert into file that doesn't exist.
aphrodite_pb2.py: Tried to insert into file that doesn't exist.
```

**Comment by i-feofilaktov** [comment]
Got same issue here. The problem appears if path to the .proto file contains hyphens.
Renaming bad files and using some sed worked for me, but it still looks like dirty hack. Any progress at this issue?

Also I've got another problem with directories containing dots (e.g. "github.com"). If proto-file contains something like `import "github.com/grpc-ecosystem/grpc-gateway/third_party/..."` the generated file would contain `from github.com.grpc_ecosystem...`, and it breaks python import 'cause there is no github package in the pythonpath. Looks quite similar to current issue.

**Comment by Abdullah2993** [comment]
Facing the same issue

**Comment by remram44** [comment]
It seems that grpc_tools.protoc happily accepts different values for grpc_python_out and python_out, then spits out a nonsensical error. Would it be possible to have a meaningful output on that situation? This happens to people, and all that google.com returns on a search for "Tried to insert into file that doesn't exist" is this issue.

Why are there separate options in the first place? (and why oh why would you put underscores in flag names)
