### ISSUE TITLE
msys2 windows workers: "fatal error LNK1101: incorrect MSPDB120.DLL version"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5255]
Building some targets (e.g. grpc_csharp_ext.sln) only works on cygwin based windows workers (the ones without the "newwindows" label).

the build only fails when ssh-ed using a private key to the worker (which is what jenkins is doing).
Error message is:
`LINK : fatal error LNK1101: incorrect MSPDB120.DLL version; recheck installation of this product`

The reason is that windows authentication model has problems setting up user profile when  authenticating user without a password. For cygwin based Jenkins workers, this is solved by `cyglsa-config` (but killing Jenkins jobs under cygwin doesn't work properly).

**Comment by jtattermusch** [comment]
see https://cygwin.com/cygwin-ug-net/ntsec.html, section "Switching the user context without password, Method 2: LSA authentication package"

**Comment by nicolasnoble** [comment]
So I'm not convinced this is the rootcause, by the way. I think the investigation needs to go in a slightly different direction than user authentication. My gut feeling is that under cygwin using their SLA script is causing a side effect in the environment that eventually results in that DLL working properly.

**Comment by jtattermusch** [comment]
Yeah, might be. but the `cyglsa-config` script seem to be our biggest hint so far anyway.

**Comment by jtattermusch** [comment]
I think this really has to do with switching user profile:
when ssh'd through msys2 sshd the current username is `USERNAME=sshd_server'  but it should be `USERNAME=jenkins` (reported correctly by cygwin sshd).

**Comment by jtattermusch** [comment]
Quoting from https://cygwin.com/cygwin-ug-net/ntsec.html:

A more important problem is that using NtCreateToken is not sufficient to create a new logon session for the new user. What does that mean? Every logon usually creates a new logon session. A logon session has a couple of attributes which are unique to the session. One of these attributes is the fact, that Windows functions identify the user domain and user name not by the SID of the access token owner, but only by the logon session the process is running under.

*This has the following unfortunate consequence. Consider a service started under the SYSTEM account (up to Windows XP) switches the user context to DOMAIN\my_user using a token created directly by calling the NtCreateToken function. A process running under this new access token might want to know under which user account it's running. The corresponding SID is returned correctly, for instance S-1-5-21-1234-5678-9012-77777. However, if the same process asks the OS for the user name of this SID something wierd happens. For instance, the LookupAccountSid function will not return "DOMAIN\my_user", but "NT AUTHORITY\SYSTEM" as the user name.

You might ask "So what?" After all, this only looks bad, but functionality and permission-wise everything should be ok. And Cygwin knows about this shortcoming so it will return the correct Cygwin username when asked. Unfortunately this is more complicated. Some native, non-Cygwin Windows applications will misbehave badly in this situation. A well-known example are certain versions of Visual-C++.*

**Comment by jtattermusch** [comment]
http://stackoverflow.com/questions/17978984/running-msvc-via-cmake-using-ssh-to-cygwin-works-if-using-a-password-to-login-bu

**Comment by jtattermusch** [comment]
Eventually I used an ugly workaround and made user "jenkins" privileged user that is also running sshd.
That way, we are not switching user sessions without password and Visual Studio is not failing with the original error anymore.

ssh configure script is here: https://gist.github.com/jtattermusch/9c8d340120d820f482fa, all the necessary steps are documented in go/grpc-jenkins-setup

I create a new windows worker snaphot and recreated all workers using that snapshot.

Currently all jenkins windows workers should be identical and seem to be working fine (except missing APPDATA variable is breaking grpc_credentials_test, but I'm going to fix that).

**Comment by jtattermusch** [comment]
For now, I manually added APPDATA variable pointing to C:\Users\jenkins\AppData\Roaming in configuration for all workers (on Jenkins).

**Comment by jtattermusch** [comment]
Seems there are still issues with the new windows workers.

**Comment by jtattermusch** [comment]
The tweaks I tried to do didn't really help and windows workers were having weird issues (VS2015 not working, missing env variables, etc), so I switched all win workers to username and password authentication.

to allow properly switching the user session, I ran `passwd -R` on all workers, that has finally resolved the "incorrect MSPDB120.DLL" problem for C# builds.

**Comment by jtattermusch** [comment]
https://cygwin.com/cygwin-ug-net/ntsec.html: "Switching the user context without password, Method 3: With password"
