### ISSUE TITLE
async_streaming_ping_pong_test tsan failure

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#5259]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/6212/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_async_streaming_ping_pong_test/

I0212 23:10:54.088205800   14550 async_streaming_ping_pong_test.cc:49] Running Async Streaming Ping Pong
D0212 23:10:54.088602446   14550 test_config.c:159]          test slowdown: machine=1.000000 build=2.000000 total=2.000000
E0212 23:10:54.351948433   14550 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
E0212 23:10:55.924161968   14550 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
I0212 23:10:56.731382194   14550 driver.cc:210]              Starting server on localhost:1080 (worker #0)
D0212 23:10:56.792364558   14569 grpc_profiler.c:48]         You do not have google-perftools installed, profiling is disabled [for qps_server.prof]
D0212 23:10:56.792424503   14569 grpc_profiler.c:52]         To install on ubuntu: sudo apt-get install google-perftools libgoogle-perftools-dev
I0212 23:10:56.792819905   14569 qps_worker.cc:232]          RunServerBody: about to create server
I0212 23:10:56.830342270   14569 qps_worker.cc:88]           Starting server of type ASYNC_SERVER
E0212 23:10:56.848903923   14569 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
I0212 23:11:01.137127535   14569 qps_worker.cc:237]          RunServerBody: server created
I0212 23:11:01.139011599   14550 driver.cc:273]              Starting client on localhost:1079 (worker #1)
I0212 23:11:01.172280027   14569 qps_worker.cc:244]          RunServerBody: creation status reported
I0212 23:11:01.215309679   14556 qps_worker.cc:194]          RunClientBody: about to create client
I0212 23:11:01.215400612   14556 qps_worker.cc:65]           Starting client of type ASYNC_CLIENT STREAMING 0
I0212 23:11:01.231748508   14556 qps_worker.cc:199]          RunClientBody: client created
I0212 23:11:01.232367007   14556 qps_worker.cc:204]          RunClientBody: creation status reported
I0212 23:11:01.233220127   14550 driver.cc:316]              Warming up
I0212 23:11:06.233407894   14550 driver.cc:322]              Starting
I0212 23:11:06.234905915   14569 qps_worker.cc:246]          RunServerBody: Message read
I0212 23:11:06.235306132   14569 qps_worker.cc:253]          RunServerBody: Mark response given
I0212 23:11:06.236018199   14556 qps_worker.cc:206]          RunClientBody: Message read
I0212 23:11:06.270551590   14550 driver.cc:343]              Running
I0212 23:11:06.270941031   14556 qps_worker.cc:213]          RunClientBody: Mark response given
I0212 23:11:11.233512082   14550 driver.cc:353]              Finishing
I0212 23:11:11.234623571   14569 qps_worker.cc:246]          RunServerBody: Message read
I0212 23:11:11.234940584   14569 qps_worker.cc:253]          RunServerBody: Mark response given
I0212 23:11:11.235422058   14556 qps_worker.cc:206]          RunClientBody: Message read
I0212 23:11:11.254420913   14556 qps_worker.cc:213]          RunClientBody: Mark response given
I0212 23:11:11.254625880   14556 qps_worker.cc:216]          RunClientBody: Returning
I0212 23:11:11.258448525   14569 qps_worker.cc:256]          RunServerBody: Returning
E0212 23:11:31.734307561   14550 driver.cc:381]              assertion failed: server->stream->Finish().ok()

*******************************
Caught signal 6

**Comment by yang-g** [comment]
async_unary_ping_pong has a similar one: https://grpc-testing.appspot.com/job/gRPC_master/config=tsan,language=c++,platform=linux/lastCompletedBuild/testReport/(root)/tests/bins_tsan_async_unary_ping_pong_test/

**Comment by vjpai** [comment]
I believe this is addressed by some of the work in #5201 , as I cleaned up some bugs in that as well. Will check in again.
