### ISSUE TITLE
proto proliferation

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#526]
"protoliferation"?

As of this writing, the interoperability test suite's "messages.proto" file can be found in test/cpp/interop, src/csharp/GrpcApi/proto, and src/node/interop. While the versions in test/cpp/interop and src/csharp/GrpcApi/proto are identical, the version in src/node/interop differs slightly.

Ironically, this state of affairs is a step toward non-interoperability. We should fix it.

**Comment by ejona86** [comment]
I was pushing back on having them in a common repository between C-based, Java, and Go gRPC implementations. I support centralizing them within a particular repository.

The problem with using a submodule is that it doesn't actually solve the problem as it would in a monolithic repository. Submodules 1) are not always checked out and 2) must manually track newer versions. 1 is more severe than it seems as "go get" doesn't check out submodules, most people do "git clone" which doesn't check out submodules, and source downloads of releases wouldn't include them. 2 makes it little better than copying the protos.

**Comment by nathanielmanistaatgoogle** [comment]
As of this moment, `test.proto` can be found in `test/proto/` as well as:
* `src/csharp/Grpc.IntegrationTesting/proto/`
* `src/node/interop/`
* `src/objective-c/examples/RemoteTestClient/`
* `src/objective-c/generated_libraries/RemoteTestClient/`
* `src/php/tests/interop/`

. Reopening.

**Comment by murgatroid99** [comment]
I would like to note that at least in my case, I have a copy of those protos in `src/node` because I only distribute files from that directory. If we wanted to avoid that duplication, I would have to either

 - Put my `package.json` and `binding.gyp` in the root directory and distribute files relative to that
 - or remove the interop tests from the test suite I distribute
 - or make everyone else use the copy in `src/node`.

**Comment by nathanielmanistaatgoogle** [comment]
@murgatroid99: understood. I'm not sure there's an immediately available solution to this, or even a plausible one other than "wait long enough and Bazel will meet this need".

**Comment by murgatroid99** [comment]
For reference, Node is going with the first option I mentioned.

**Comment by jtattermusch** [comment]
For interop testing, C# no longer uses it's own copy of the protos. It's using protos from /test/proto,

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/6364

**Comment by jtattermusch** [comment]
I filed a set of per-language issues to make things more organized and I'm going to close this one finally.
