### ISSUE TITLE
grpc_coverage is not generating reports

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5265]
@nicolasnoble @jtattermusch any ideas?

**Comment by adelez** [comment]
Will investigate tomorrow.

**Comment by adelez** [comment]
[gRPC_coverage] $ /bin/sh -xe /tmp/hudson1678894184444982767.sh
+ platform=linux config=gcov language=all tools/jenkins/run_jenkins.sh
tools/jenkins/run_jenkins.sh: line 40: set: igncr: invalid option name

https://grpc-testing.appspot.com/job/gRPC_coverage/lastFailedBuild/console

**Comment by adelez** [comment]
1961a80e2810f9b778a81725a860eae31a994956 may be the PR that broke this since it's the only candidate between grpc_coverage builds 2388 (success) and 2389 (fail).

**Comment by adelez** [comment]
Further down the log I found: 
+ python tools/run_tests/run_tests.py --use_docker --measure_cpu_costs -t -l all -c gcov -x report.xml -j 2
Multi-language and multi-config testing is not supported.
