### ISSUE TITLE
Raise exception if serving server is garbage collected (or maybe just shut it down?)

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#529]
Right now there's no protection stopping the Python interpreter from garbage-collecting a serving server (and its completion queue). It's a great way to fail an assertion and crash the entire process. Probably the right thing to do is raise an exception indicating a programming defect if the garbage collector attempts to delete a serving server.

This came up in my recent testing and rather than code it up right away I want to take some time to think about it.

**Comment by nathanielmanistaatgoogle** [comment]
I'm not so sure about this any more - in the last few weeks I've started to think that maybe the right thing to do if a serving server is garbage collected is just cancel all its RPCs and shut it down cleanly. Retitling this issue.

@soltanmm have you any feelings one way or the other?

**Comment by ctiller** [comment]
Just shutting down seems like the most predictable thing to do.

**Comment by nathanielmanistaatgoogle** [comment]
This is implemented in GA.
