### ISSUE TITLE
PHP: improve autoloading of generated code

### ISSUE THREAD

**Issue by dstore-dbap** [grpc/grpc#5306]
When generating PHP/grpc stub-code via protoc-gen-php.php class names and file names for the classes differ, which makes PSR-4 autoloading impossible, example: The class `AbcClient extends \Grpc\BaseStub` is defined in a file `AbcStub.php`

@stanley-cheung: The class name should have the suffix `Stub` not `Client`

Code References:

- [filename generation](https://github.com/stanley-cheung/Protobuf-PHP/blob/master/library/DrSlump/Protobuf/Compiler/PhpGenerator.php#L87)
- [class name generation ](https://github.com/stanley-cheung/Protobuf-PHP/blob/master/library/DrSlump/Protobuf/Compiler/PhpGenerator.php#L430)

**Comment by stanley-cheung** [comment]
Sorry it took me so long to get to this. Got a question: how did you use the protoc-gen-php binary to generate the stub .php file? Coz when I do it, like let's say on `math.proto`, I got `math.php`, not `mathStub.php`. It still doesn't match the class name `MathClient` but I'd like to understand why the difference.

In particular, I am referring to this script that I used for testing: [`generate_proto_php.sh`](../tree/master/src/php/bin/generate_proto_php.sh). If I run this, I get `math.php` back.

**Comment by dstore-dbap** [comment]
I have to apologize. I should have mentioned that I used the php.multifile option.

Here is how to reproduce the behavior

```
linuxbrew@ffad1ab7a43d:~/grpc/src/php/bin$ ../vendor/datto/protobuf-php/protoc-gen-php.php --define=multifile -i ../tests/generated_code ../tests/generated_code/math.proto 
Protobuf-PHP @package_version@ by Ivan -DrSlump- Montes

NOTICE: Mapping math to math
NOTICE: Generating "math/DivArgs.php"
NOTICE: Generating "math/DivReply.php"
NOTICE: Generating "math/FibArgs.php"
NOTICE: Generating "math/Num.php"
NOTICE: Generating "math/FibReply.php"
NOTICE: Generating "math/MathStub.php"
```

**Comment by stanley-cheung** [comment]
This should be fixed now.

**Comment by dstore-dbap** [comment]
I can confirm it works. Thanks!
