### ISSUE TITLE
Build precompiled extension for Python on Linux w/ UCS2

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5310]
cc @jtattermusch @nathanielmanistaatgoogle 
cc #5280

**Comment by tseaver** [comment]
I don't know if it is relevant, but [PEP 513](https://www.python.org/dev/peps/pep-0513/) spells out how to build (and upload to PyPI) `manylinux1` wheels, including separate names for UCS-2 vs UCS-4 builds.

**Comment by soltanmm** [comment]
@tseaver Aye, relevant and something we'll get around to: #6036.

**Comment by soltanmm** [comment]
The only folks who I've seen have problems with this appear to have custom builds of Python, which implies that they have the necessary tools available to them to build gRPC Python from source. We can punt on this for now (and it will become easier to address following our use of `manylinux1`).

**Comment by soltanmm** [comment]
Fixed in #6280.
