### ISSUE TITLE
Consider making "flattened call options" overload call non-flattened

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#5323]
Currently the client implementation for each service operation has four methods, like this:

```csharp
public FooResponse Foo(FooRequest request, CallOptions options)
{
    var call = CreateCall(__Method_ListTopics, options);
    return Calls.BlockingUnaryCall(call, request);
}

public FooResponse Foo(FooRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
{
    var call = CreateCall(__Method_ListTopics, new CallOptions(headers, deadline, cancellationToken));
    return Calls.BlockingUnaryCall(call, request);
}

public AsyncUnaryCall<FooResponse> FooAsync(FooRequest request, CallOptions options)
{
    var call = CreateCall(__Method_ListTopics, options);
    return Calls.AsyncUnaryCall(call, request);
}

public AsyncUnaryCall<FooResponse> FooAsync(FooRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
{
    var call = CreateCall(__Method_ListTopics, new CallOptions(headers, deadline, cancellationToken));
    return Calls.AsyncUnaryCall(call, request);
}
```

This would be simpler to understand if the methods with more parameters just called the shorter ones:

```csharp
public FooResponse Foo(FooRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
{
    return Foo(request, new CallOptions(headers, deadline, cancellationToken));
}

public AsyncUnaryCall<FooResponse> FooAsync(FooRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
{
    return FooAsync(request, new CallOptions(headers, deadline, cancellationToken));
}
```

Once that is in place, it's obvious that that holds for *any* implementation... so we could *consider* making the "flattened" versions simply extension methods on the interface. The client interface would then halve in size.

It would be nice if we could halve it again by making the client interface just the async calls, and then write the sync calls as extension methods on top of those - but I don't think that's feasible at the moment.

There are questions around the discoverability of extension methods, admittedly, but it's at least worth considering.

I would personally like the implementation change even if we never go for the extension methods, as  the code is simply easier to understand. I realize many users won't read the generated code, but some will. I wouldn't expect there to be any performance issues from this - even if the JIT compiler can't inline the code, the extra call would be trivial compared with everything else that's going on.

**Comment by jskeet** [comment]
(This should have the C# label, and be assigned to @jtattermusch )

**Comment by jtattermusch** [comment]
I'll need to give more thought to the extensions approach, but we'll at least want to do what you suggested with flattening the call options.
