### ISSUE TITLE
Message-Length is big or little endian?

### ISSUE THREAD

**Issue by stepancheg** [grpc/grpc#5341]
[gRPC spec](http://www.grpc.io/docs/guides/wire.html#requests) tells that

> Message-Length → {length of Message} # encoded as 4 byte unsigned integer

It should tell whether message length is encoded as little or big endian.

AFAIU, it is big endian.

**Comment by y-zeng** [comment]
Stating the endianness of a numeric number might not be necessary, since "all numeric values are in network byte order" is a convention in [HTTP2 spec](https://http2.github.io/http2-spec/#rfc.section.2.2).

**Comment by stepancheg** [comment]
Well, HTTP/2 does not mandate that payload is encoded using network byte order. It is especially not obvious because protobuf uses little endian for 4-byte integers.
