### ISSUE TITLE
error: 'php.h' file not found on mac worker 3

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5342]
Seen python test fail:
https://grpc-testing.appspot.com/job/gRPC_master/15327/config=opt,language=php,platform=macos/console

Considering mac worker 3 is fairly new (and the test has passed on worker2), the best bet would be that PHP is not properly installed there (perhaps it's missing in the installation instructions in go/grpc-jenkins-setup?).

**Comment by jtattermusch** [comment]
CC @adelez

**Comment by stanley-cheung** [comment]
hm, there's no `/usr/include` in this machine. I wonder why. Still looking into it.

**Comment by stanley-cheung** [comment]
Fixed. https://grpc-testing.appspot.com/job/gRPC_master/15331/config=opt,language=php,platform=macos/console

I will add a step to go/grpc-jenkins-setup

**Comment by adelez** [comment]
Thanks for updating the doc, Stanley!
