### ISSUE TITLE
cloud_to_prod_auth:default:node:jwt_token_creds is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5344]
https://grpc-testing.appspot.com/job/gRPC_interop_master/3018/testReport/(root)/tests/cloud_to_prod_auth_default_node_jwt_token_creds/

```
I0220 18:08:35.653502294     199 socket_utils_common_posix.c:148] Disabling AF_INET6 sockets because ::1 is not available.

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: '' === '155450119199-vefjjaekcc6cmsd5914v6lqufunmh9ue@developer.gserviceaccount.com'
    at /var/local/git/grpc/src/node/interop/interop_client.js:406:12
    at /var/local/git/grpc/src/node/src/client.js:344:9
```

@murgatroid99, I know you were looking into this, but filing an issue for this for the record.

**Comment by murgatroid99** [comment]
This is the same as #5298, which was fixed by #5328. This test run if from before that PR was merged.
