### ISSUE TITLE
Reduce Python test suite runtime

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5357]
Ideally we'd see sub-20 minute test runs all the time. Currently we're seeing many taking more than an hour:

https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/config=opt,language=python,platform=linux/buildTimeTrend

I expect this is due to the flaky re-runs on pull requests forcing the entire suite to re-run.

This is significantly slowing folks checking build status before merging.

The flaky tests are also creating doubt in the Python test suites validity.

Happy to help brainstorm solutions, or organize any fixes for core problems (given reproductions).

**Comment by murgatroid99** [comment]
I'd like to point out that most, if not all, of the flakes appear to be timeout flakes, so increasing the allowed runtime should also fix this.

**Comment by soltanmm** [comment]
Reassigning to me because I'm signed up for re-parallelising the Python tests.

**Comment by ctiller** [comment]
Probably worth a peek at #5410 for trickery in the C++ suites

**Comment by jtattermusch** [comment]
After merging #5541 Python test runtime should be much better.
