### ISSUE TITLE
Objective C example errors

### ISSUE THREAD

**Issue by billidani7** [grpc/grpc#5367]
I am trying to test the grpc/examples/objective-c/helloworld

First of all I get this message when `pod install`  finishes

`[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target HelloWorld to Pods/Target Support Files/Pods/Pods.release.xcconfig or include the Pods/Target Support Files/Pods/Pods.release.xcconfig in your build configuration.`

I open the HelloWorld.xcworkspace and i get this error 

`Undefined symbols for architecture arm64:
  "_gpr_log_message", referenced from:
      _gpr_log in libgRPC.a(log_posix.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any ideas how to fix this error?

I have the latest CocoaPods. Xcode 7.2

**Comment by makdharma** [comment]
This bug was introduced recently and https://github.com/grpc/grpc/pull/5352
has a fix.

**Comment by billidani7** [comment]
@makdharma Thank you for the notice. The compilation error has been fixed.

I run the app and I get this error

`assertion failed: gpr_tls_get(&subchannel_index_exec_ctx) == 0`

**Comment by jcanizales** [comment]
Hi Vasilis, could you check for me which versions you're using of XCode (by running `xcodebuild -version`) and the iOS SDK (by running `xcrun --sdk iphoneos --show-sdk-version`)?

**Comment by jcanizales** [comment]
Actually, this is probably fixed by PR #5390. Please verify that it works for you (it does on Travis) and sorry for the trouble!

**Comment by billidani7** [comment]
Hi Jorge. Thank you very much for the info. It works!

**Comment by jcanizales** [comment]
Glad to hear it. Please keep us updated with how the library works for your project!
