### ISSUE TITLE
grpc_server_add_[secure_]http2_port takes an "addr" parameter, not a port

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#537]
The verb-object disagreement seems like it will lead users to type either the wrong function name or wrong argument name.

Also the documentation doesn't address why an address value is needed. Why isn't an integer indicating the port enough?

**Comment by jayantkolhe** [comment]
@a11r  is the doc updated? Closing this since this bug is more of a question...

**Comment by nathanielmanistaatgoogle** [comment]
This is a documentation bug; I've been excited about getting an answer for nearly six months and still consider the matter unresolved.

**Comment by a11r** [comment]
There is is no good answer here. Servers listen on specific ports, and sometimes servers listen on specific ports but only on specific addresses. To cover the most general case, we need to take an addr parameter, but conceptually, this is telling the server what to listen on, and calling that an addr would be worse than calling that a port. We could name it grpc_server_add_[secure_]http2_addr_and_port, but I am not sure if this is better than just relying on comments and type checking to ensure correct usage.

**Comment by a11r** [comment]
Marjking this closed. Please reopen if  further discussion is needed.
