### ISSUE TITLE
Produce HTML report for performance smoke test

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#5374]
This should be borrowed from HTML report generation used in interop test, but with numbers instead of "PASS/FAIL"

**Comment by hsaliak** [comment]
@adelez do you have an update on this issue? 
Also, should this be tracked in the current milestone?
/cc @nicolasnoble

**Comment by ctiller** [comment]
Not a GA blocker.

**Comment by ctiller** [comment]
(important though!)

**Comment by adelez** [comment]
Sorry for the delay. I will get it done asap.

**Comment by adelez** [comment]
Hi Vijay, can you please detail what data you would like to be displayed in each cell? You told me offline but I can't find it.

**Comment by adelez** [comment]
Does this one look ok? 
[Performance Test Result.pdf](https://github.com/grpc/grpc/files/319365/Performance.Test.Result.pdf)

**Comment by vjpai** [comment]
Latency measures make sense for a ping_pong test, but for unconstrained tests, it should show the QPS achieved, IMO.
