### ISSUE TITLE
Feature request: Allow tuning the reconnection backoff

### ISSUE THREAD

**Issue by aisotton** [grpc/grpc#5377]
When a grpc connection breaks, the client tries to reconnect periodically using an increasing backoff. Right now, the backoff seems to max out at about 1 minute.

This makes a lot of sense for setups with a large number of clients, to avoid overwhelming the servers. Our use case typically only has 1 or 2 clients (interactive desktop applications), and waiting for a minute after the server comes back up is excessive.

We would like to have the ability to set the maximum backoff value to a custom value to make the reconnections much more aggressive. We would set it to something in the order of 5 seconds.

Is this a feature you'd accept a patch for?

**Comment by ctiller** [comment]
I wouldn't be opposed. We need to give some thought to API.

@makdharma - assigning to you to figure out, as the default backoff algorithm seems like it'd be problematic for some mobile use cases also.

**Comment by aisotton** [comment]
For what it's worth, we don't care about how exactly the increasing backoff is calculated. We just want to be able to set a maximum value for the backoff. We also don't care about jittering (but it doesn't hurt either).

Having a hardcoded algorithm with the ability to set the maximum, or having the ability to plug in our own algorithm would work equally well for us. Just setting the maximum would require less coding from our side, but even if we had to write our own algorithm that wouldn't be a big deal.

A channel argument seems like it would work well to change the maximum. I'd be happy to add that. I don't know what the best way would be to plug in a custom algorithm.

**Comment by larsonmpdx** [comment]
I'd use this feature.  I have a desktop application where I want to give the user control over manual retries, and mobile clients where I want a little more control.  Currently I'm using a second thread that calls (in c++) TryCancel() in order to enforce a max limit, but I'd love to get rid of that code.

**Comment by larsonmpdx** [comment]
semi-related: for long-running streaming RPCs where there is an infinite timeout used, the second-thread approach is all but required if I want to be able to cancel during a connection attempt using the sync api.  If I could set a timeout on connecting, but still have an infinite timeout during the stream, that would let me remove the watchdog thread (and bring this complexity into grpc, nothing's free)

**Comment by makdharma** [comment]
The idea of exposing maximum backoff period through API seems OK to me, and
useful in mobile context also. Aaron, please go ahead and submit your patch
and we can debate on the mechanism.
