### ISSUE TITLE
RPC timeout consistency

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5378]
A few weeks ago when we had the Python idiomaticity review the question of "why do we require timeouts on every RPC call?" was raised, and the answer turned out to be "well historical reasons X and Y but now we don't really care so long as we do what everyone else does".

So let's push for uniformity (as much as possible) among the languages. Is timeout per-RPC optional or required? If optional and not supplied, is a default used? What variance is there among implementations? Is specifying timeout with a metadata value supported? If specified both as an argument and as metadata, which value wins?

**Comment by ctiller** [comment]
If optional and unspecified the default is infinite.
Ideally it's 'optional but encouraged'.
In the future I hope we'll have a mechanism in place to have services
override the default, at which time the default flips to encouraging not
overriding timeouts.

Specifying via metadata is not supported and will be silently dropped.

**Comment by pgrosu** [comment]
There are many options for distributed RPC where you can have a queue, a poll, a pub/sub, pipeline with fusion steps, and with some of these you don't need a timeout and just have an exponential retry if the message is not received based on the design topology.  For broker-less implementations of multiple directory-service registered queues among the clients that do the work to ensure the messages are properly received/sent.

**Comment by jcanizales** [comment]
As a datapoint, for the Objective-C client, timeouts are optional, and we want to discourage people from setting them (because the experience is they tend to set values that work great in the US, but are too low for slower networks in developing countries). The datacenter use case obviously differs.

**Comment by bryanschwerer** [comment]
In our case, we have a server streamed call that is being used as a pipeline for asynchronous events.  We already have expected variability in the delivery of events and a dedicated thread to handle them.  The timeout complicates the design somewhat.

**Comment by soltanmm** [comment]
I'm not against reasonable defaults, but...

@bryanschwerer I'm not sure what you mean by 'complicates the design'. What additional nontrivial design concerns are there with passing a `float('+inf')` everywhere (assuming you're using the Python API)?

**Comment by bryanschwerer** [comment]
> passing a float('+inf')

I didn't realize that worked.  That is adequate for us.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle will this behaviour be retained after the refactoring? Assigning this back to you.

**Comment by nathanielmanistaatgoogle** [comment]
Timeouts are optional in Python's GA API. They remain specified per-RPC.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle if unspecified (ie timeout defaults to None), it looks like methods would block until the computation has finished or is cancelled no matter how long that takes. Could you confirm? If so I think we can close this..

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: confirmed.

**Comment by jayantkolhe** [comment]
closing
