### ISSUE TITLE
Set __all__ consistently throughout the library

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5389]
According to [PEP8](https://www.python.org/dev/peps/pep-0008): ["To better support introspection, modules should explicitly declare the names in their public API using the `__all__` attribute. Setting `__all__` to an empty list indicates that the module has no public API."](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces).

**Comment by sahilshekhawat** [comment]
If you don't mind, can I work on it? Since, most of the issues are already assigned and I want to contribute.

**Comment by nathanielmanistaatgoogle** [comment]
@sahilshekhawat: I don't mind at all; feel free!

**Comment by sahilshekhawat** [comment]
Should I also add ``__all__`` attribute at the beginning of each module to define exact classes/functions included in the public API?

Right now, I have just added all the modules in the packages which are publicly available.

**Comment by nathanielmanistaatgoogle** [comment]
@sahilshekhawat: honestly I'm not sure; I've never before used `__all__`, and was thinking that I'd have to read up on it before drafting any code. But taking a guess about `__all__` in modules: I think so?

**Comment by sahilshekhawat** [comment]
If we don't add ``__all__`` in each module then all the interface in a public module I. e.  not starting with ``_`` are public by default. I think we comply to this, (correct me if I am wrong)  otherwise, we need to add it to each module

**Comment by nathanielmanistaatgoogle** [comment]
We do already use underscore-prefixing for privacy, but I think part of the motivation for `__all__` is to have `dir(<module object>)` and `help(<module object>)` be more user-friendly.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle @sahilshekhawat Sorry to chime in with my 2c *very* late but having looked at this and a lot of python modules in the standard library, using __all__ to define the public API does make sense for every module. 
This will lead to an API definition that's inclusive by default as @sahilshekhawat points out. Having __all__ will mean that our API is exclusive by default, unless it's explicitly added to the __all__ tuple.

https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces

Next question - should we do this in a separate PR? 
Given that adding __all__ to modules is less straightforward than packages, this would have to be done with a lot of scrutiny.  

My recommendation is to merge the related CL to add __all__ to packages and follow up with a related issue to add __all__ within modules. This will be the public API we ship with for 1.0.
