### ISSUE TITLE
Submodule nanopb has a -Wconversion build error under gcc 5.2 

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#5393]
This likely needs investigation. Has nanopb solved this?

third_party/nanopb/pb_decode.c: In function ‘pb_decode_noinit’:
third_party/nanopb/pb_decode.c:889:60: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
             fields_seen[iter.required_field_index >> 3] |= (uint8_t)(1 << (iter.required_field_index & 7));
                                                            ^

**Comment by ctiller** [comment]
Suggest lowering our warning levels for nanopb (like we do for boringssl
and zlib).

We'll kill ourselves if we insist that all dependencies meet our standards.

**Comment by vjpai** [comment]
One more point: this issue at least seems to be solved at master in nanopb . It looks like we're not pulling that, though.

**Comment by vjpai** [comment]
But I agree in general that we may not have dependences that meet our standards.

**Comment by dgquintas** [comment]
Please have a look at #5380, which updates the nanopb version

**Comment by dgquintas** [comment]
Now that #5396 has been merged, maybe the next iteration will pick up the latest nanopb version and the warning will be gone (which is orthogonal to introducing custom flags, yes)
