### ISSUE TITLE
Python Mac tests timing out on Jenkins

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5409]
I couldn't really spot if it's one specific test or what. Console logs [here](https://grpc-testing.appspot.com/job/gRPC_master/15383/config=opt,language=python,platform=macos/console) and [here](https://grpc-testing.appspot.com/job/gRPC_master/15383/config=dbg,language=python,platform=macos/console).

**Comment by soltanmm** [comment]
The logs are dupes of #4650 and in #5357 respectively AFAIK.

**Comment by jcanizales** [comment]
Agreed; sorry for not noticing it!
