### ISSUE TITLE
qps_worker segmentation fault while running performance tests

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5414]
See https://grpc-testing.appspot.com/job/gRPC_performance_master/1880/console :

```
I0225 07:22:37.470789641   25277 driver.cc:341]              Running
I0225 07:23:02.466412510   25277 driver.cc:351]              Finishing
E0225 07:23:02.466655382   25277 driver.cc:359]              assertion failed: server->stream->Read(&server_status)

tools/jenkins/run_performance.sh: line 72: 25215 Segmentation fault      (core dumped) bins/$config/qps_worker -driver_port 10000
tools/jenkins/run_performance.sh: line 72: 25216 Segmentation fault      (core dumped) bins/$config/qps_worker -driver_port 10010

+ bins/opt/qps_driver --rpc_type=STREAMING --client_type=ASYNC_CLIENT --server_type=ASYNC_GENERIC_SERVER --outstanding_rpcs_per_channel=100 --client_channels=64 --bbuf_req_size=0 --bbuf_resp_size=0 --async_client_threads=0 --async_server_threads=0 --secure_test=true --num_servers=1 --num_clients=0 --server_core_limit=1 --client_core_limit=0

I0225 07:23:02.566252614   25306 socket_utils_common_posix.c:148] Disabling AF_INET6 sockets because ::1 is not available.

E0225 07:23:02.566470316   25305 tcp_client_posix.c:171]     failed to connect to 'ipv4:127.0.0.1:10000': socket error: connection refused
...
```

**Comment by vjpai** [comment]
I believe this is related to another one of the stability issues that I have been tracking. This is not the timeout problem that we were seeing earlier.

**Comment by vjpai** [comment]
This is not related to #5385 .  It is another issue. It might be related to #5420, though.

**Comment by pgrosu** [comment]
My Spidey sense it giving me the feeling that the message is never received in line `ops.RecvMessage(msg)` of this portion of the code:

```C
bool Read(R* msg) GRPC_OVERRIDE {
    CallOpSet<CallOpRecvInitialMetadata, CallOpRecvMessage<R>> ops;
    if (!context_->initial_metadata_received_) {
      ops.RecvInitialMetadata(context_);
    }
    ops.RecvMessage(msg);
    call_.PerformOps(&ops);
    return cq_.Pluck(&ops) && ops.got_message;
}
```

Below is a link to the direct section of the code:

https://github.com/grpc/grpc/blob/3f19f427714c08d1fce449cf8904fa1494602285/include/grpc%2B%2B/impl/codegen/sync_stream.h#L282-L290

**Comment by vjpai** [comment]
I think that you're right. I'm watching the occasional seg faults in the workers that come just before this and thinking that the actual problem is in the implementation of Mark processing in the Client and Server - all that histogram swapping is a little tricky and could lead to a problem somewhere.

**Comment by pgrosu** [comment]
I recommend that you add a bunch of `gpr_log()` messages for yourself throughout the code, recompile it and run it to see what exactly happens by inspecting the output of these messages.

**Comment by jtattermusch** [comment]
Doesn't look like we're seeing this anymore. Closing as part of buildpony bankruptcy.
