### ISSUE TITLE
$ protoc -I ../../protos/ --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin ../../protos/helloworld.proto

### ISSUE THREAD

**Issue by skxiaoniao** [grpc/grpc#5415]
$ protoc -I ../../protos/ --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin ../../protos/helloworld.proto
hello .
I use grpc with windows os 
but i build it with protobuf helloworld  to make helloworld.grpc.pb.h failed
the command show message --grpc_out: protoc-gen-grpc:  not find
please tell me how to build it helloworld.grpc.pb.h
and I'm not find grpc github within grpc_cpp_plugin 
thanks

**Comment by skxiaoniao** [comment]
the environment with visual studio 2013

**Comment by fdefever** [comment]
Since Vista, there's a `where` command, equivalent to `which` on Linux. Use that to locate `grpc_cpp_plugin`, then use that value in your `protoc` command.
