### ISSUE TITLE
Improve documentation for C++ streaming API

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#5420]
The documentation is available through Doxygen but can be hard to find at times because it is often with the abstract interface class and not with the actual implementation class that users are constructing. A case in point is that Finish should not be called on a stream until its reads are all done. Some users have been confused by this.

**Comment by dgquintas** [comment]
@vjpai are we aiming at improving the Doxygen docs or at having some other form of docs? I presume the former, correct?

**Comment by vjpai** [comment]
This is double-assigned with a plan; I will take the first part of this and @dgquintas will take the second.

**Comment by vjpai** [comment]
CC @slash-lib on any documentation PRs.
