### ISSUE TITLE
Provide documentation/example how to run gRPC C# server as part of IIS/ASP.NET process.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5425]
gRPC C# currently is a standalone server, but .NET users have experienced trouble with deploying their services to IIS. Provide instructions/example how to expose a gRPC server (on a separate port) in an ASP.NET application environment.

http://stackoverflow.com/questions/35176091/how-should-a-grpc-service-be-hosted

**Comment by Sildra** [comment]
I ran into this trouble yesterday and this is the reason (and the workaround) https://github.com/Sildra/RPC-Test/blob/master/RPCServer/Global.asax.cs

**Comment by leshin** [comment]
+1

**Comment by jtattermusch** [comment]
A partial example is available in this demo: https://github.com/grpc-ecosystem/grpc-exchange-o-gram

**Comment by celindho** [comment]
Hi is there any documentation or examples available on how to build a grpc server in IIS? I’m interrested in hosting a grpc service (built in C#) in Azure so there migt be other options aprat from IIS for hosting also.

**Comment by jtattermusch** [comment]
No progress here for >1year. Closing for bankruptcy.
