### ISSUE TITLE
boringssl build error 

### ISSUE THREAD

**Issue by skxiaoniao** [grpc/grpc#5436]
hello 
author
boringssl build error 
i build boringssl with visual studio 2013  so many error
what'e the download link with boringssl with grpc version?
thanks

**Comment by polinzhuo** [comment]
i have the same errors

**Comment by soltanmm** [comment]
What were the steps you took that led to the build error? On which branch (and commit)?

**Comment by nicolasnoble** [comment]
Without further explanation or problem description, I am going to close that one. You don't need to build the boringssl project under Windows anyway, so this is irrelevant.
