### ISSUE TITLE
Load balance with DNS in grpc does not work?

### ISSUE THREAD

**Issue by yancl** [grpc/grpc#5437]
Hi,

  Today when i change the ip address of channel args in python to dns address according to the [document](https://github.com/grpc/grpc/blob/master/doc/naming.md). but it does not work as expected. 

for example:
from:
```
channel = implementations.insecure_channel('0.0.0.0', 50050)
    with hello_pb2.beta_create_Services_stub(channel) as stub:
```

to:
```
target = dns:///127.0.0.1:8600/hello.service.consul
channel = implementations.insecure_channel(target, 50050)
    with performance_pb2.beta_create_Services_stub(channel) as stub:
```

As you see, in the later case, i want to use the **DNS** resovler and the DNS server address is **127.0.0.1:8600**, then query the service addresses with the **hello.service.consul**.
but when i see the packets with tcpdump, i see gRPC send the ** 127.0.0.1:8600/hello.service.consul** to the default DNS at 53 port.

So i wonder whether i missunderstand the target's meaning of `scheme://authority/endpoint_name`?

thanks:)

**Comment by ctiller** [comment]
You're not missing anything: we just don't support authority based DNS
lookups yet.

**Comment by yancl** [comment]
Thanks for your reply:)

**Comment by tjb1216** [comment]
Has support authority based DNS lookups now? if not, what's your plan?

**Comment by tjb1216** [comment]
@ctiller

**Comment by dunkymole** [comment]
Hi,

I am also interested in this. Where is it on the roadmap?

Thanks
