### ISSUE TITLE
Feature Request: Support FlatBuffers

### ISSUE THREAD

**Issue by joelchen** [grpc/grpc#5438]
Very much appreciate gRPC supporting FlatBuffers for a slight trade-off in wire format size for better performance than Protocol Buffers as highlighted in http://google.github.io/flatbuffers/flatbuffers_benchmarks.html.

**Comment by ctiller** [comment]
It's something we've absolutely talked about.

We're a little busy getting a 1.0 ready right now, but after that I'm sure
we will.

If anyone has time before then, I'd absolutely be happy to guide them
through what's required to make this happen for C++.

**Comment by ctiller** [comment]
@gwvo is working on this

**Comment by gwvo** [comment]
This was the first change to grpc to allow us to share the grpc code generation between Protocol Buffers and FlatBuffers: https://github.com/grpc/grpc/pull/6130

Now working on integrating that with `flatc`.

**Comment by genexp** [comment]
Very nice!

**Comment by gwvo** [comment]
I have a pending commit that has initial `flatc` codegen integration, but I have not had time to return to it recently. Could benefit from some review/help from grpc team members.

**Comment by genexp** [comment]
Very nice y'all :)  We're really looking forward to this.  We're using
Flatbufs for file storage as well as our wire format.  We've been
developing using gRPC as our protocol, and had been planning to swap over
to Flatbuffs when ready.  This is really a killer stack at this point, hats
off!  Nice work!

On Thu, Jun 2, 2016 at 2:59 PM, Wouter van Oortmerssen <
notifications@github.com> wrote:

> I have a pending commit that has initial flatc codegen integration, but I
> have not had time to return to it recently. Could benefit from some
> review/help from grpc team members.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grpc/grpc/issues/5438#issuecomment-223388876>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAADMLmy5W6S4wpJowQktei8dH1p5mn8ks5qHygYgaJpZM4HjuG4>
> .
>



-- 

Brian Corrigan
518-867-1439http://oddnetworks.com <http://www.oddnetworks.com/>New York

**Comment by cw-gawdeprasad** [comment]
That seems to be a great news. We have been using proto3 with grpc. Having flatbuffer with Grpc would be awesome. Eagerly looking forward to it.

**Comment by gonzaloserrano** [comment]
Awesome, looking forward to integrate gRPC for mobile games, where flatbuffers shines :-)

**Comment by genexp** [comment]
Very true!

**Comment by gwvo** [comment]
Commit is in internal review, will soon have something for y'all to look at :)

**Comment by gwvo** [comment]
Ok, first commit with GRPC support has landed in FlatBuffers: https://github.com/google/flatbuffers/commit/48f37f9e0a04f2b60046dda7fef20a8b0ebc1a70

I wouldn't be surprised if this is still rough around the edges, and it certainly needs some improvements still (like making the GRPC path zero-copy).

I'd be grateful for anyone having a look and giving feedback, to see if anything else is needed for people to start using this.

**Comment by patrickToca** [comment]
How to start using/testing (experimentation) this grpc implementation? (we are using flatbuffers now and plan to use gRPC soon). Any guideline? Thanks.

**Comment by gwvo** [comment]
There is a simple test case here: https://github.com/google/flatbuffers/blob/master/grpc/tests/grpctest.cpp
Obviously, more thorough testing would be welcome, but I first wanted to get things out there for people to look at.

**Comment by patrickToca** [comment]
Thanks. Starting reviewing that.

**Comment by immesys** [comment]
It's not immediately clear to me how to do streams in gRPC with flatbuffers. Am I missing something?

**Comment by gwvo** [comment]
I would hope streaming is transparent to the serialization mechanism used, i.e. it will simply supply you multiple buffers, but I haven't looked into this myself.

**Comment by immesys** [comment]
I was attempting to use the Flatbuffers IDL (and flatc --grpc), but it does not appear to support describing streams. Is there a different approach I should use?

**Comment by gwvo** [comment]
The test example has:

```
rpc_service MonsterStorage {
  Store(Monster):Stat (streaming: "none");
  Retrieve(Stat):Monster (idempotent);
}
```

Instead of "none", you can use "client", "server" or "bidi". This may not be documented.

**Comment by immesys** [comment]
Ah, I totally missed that. I will give it a try. Thanks

**Comment by kas240sx89** [comment]
hey, it is awesome to see flatbuffers finally able to be sent with grpc. I am currently working with go and would like convert it from proto to flatbuffers. When i create a .fbs and run flatc --grpc I get a grpc.fb.cc and a grpc.fb.h, is there currently a way to got the golang equivalent to that?

**Comment by immesys** [comment]
+ 1 I was actually wanting Go support too, I ended up sticking with protobuf and hoping that go flatbuf grpc would arrive soon

**Comment by gwvo** [comment]
There's no Go support yet.

@royalharsh has been porting my changes for C++ to work with Python, and I suggested Java and Go be next, see here: https://github.com/grpc/grpc/pulls?utf8=%E2%9C%93&q=is%3Apr%20flatbuffers

(Also needs the corresponding work on the FlatBuffers side, see e.g. https://github.com/google/flatbuffers/commit/48f37f9e0a04f2b60046dda7fef20a8b0ebc1a70 )

**Comment by KrishnaPG** [comment]
Does this require any special flag while building the grpc code (so that we can use flatbuffers)? I am using Visual Studio solution files and looks like the code is linking with protobufs by default. 

How to make the grpc know that (while running) it should expect the data in flatbuffers format and not protobuf? or is grpc smart enough to figure out the format / does not really care about the format and format-neutral

**Comment by KrishnaPG** [comment]
Getting the below error while building the `grpctest` in the flatbuffer solution with visual studio.
````
1>------ Build started: Project: grpctest, Configuration: Debug Win32 ------
1>  grpctest.cpp
1>\tests\monster_test_generated.h(625): warning C4316: 'MyGame::Example::Vec3': object allocated on the heap may not be aligned 16
1>\grpc++/impl/codegen/call.h(308): error C2027: use of undefined type 'grpc::SerializationTraits<R,void>'
1>          with
1>          [
1>              R=flatbuffers::BufferRef<MyGame::Example::Stat>
1>          ]
1> \grpc++/impl/codegen/call.h(304): note: while compiling class template member function 'void grpc::CallOpRecvMessage<R>::FinishOp(bool *,int)'
1>          with
1>          [
1>              R=flatbuffers::BufferRef<MyGame::Example::Stat>
1>          ]
1>  \grpc++/impl/codegen/call.h(613): note: see reference to function template instantiation 'void grpc::CallOpRecvMessage<R>::FinishOp(bool *,int)' being compiled
1>          with
1>          [
1>              R=flatbuffers::BufferRef<MyGame::Example::Stat>
1>          ]
1>  \grpc++/impl/codegen/call.h(595): note: see reference to class template instantiation 'grpc::CallOpRecvMessage<R>' being compiled
1>          with
1>          [
1>              R=flatbuffers::BufferRef<MyGame::Example::Stat>
1>          ]
1>  \grpc++/impl/codegen/async_unary_call.h(111): note: see reference to class template instantiation 'grpc::CallOpSet<grpc::CallOpRecvInitialMetadata,grpc::CallOpRecvMessage<R>,grpc::CallOpClientRecvStatus,grpc::CallNoOp<4>,grpc::CallNoOp<5>,grpc::CallNoOp<6>>' being compiled
1>          with
1>          [
1>              R=flatbuffers::BufferRef<MyGame::Example::Stat>
1>          ]
1>  \grpc++/impl/codegen/async_unary_call.h(88): note: see reference to class template instantiation 'grpc::ClientAsyncResponseReader<flatbuffers::BufferRef<MyGame::Example::Stat>>::CallOpSetCollection' being compiled
1>  \grpc++/impl/codegen/async_unary_call.h(87): note: while compiling class template member function 'void grpc::ClientAsyncResponseReader<flatbuffers::BufferRef<MyGame::Example::Stat>>::Finish(R *,grpc::Status *,void *)'
1>          with
1>          [
1>              R=flatbuffers::BufferRef<MyGame::Example::Stat>
1>          ]
1>  \tests\monster_test.grpc.fb.h(64): note: see reference to class template instantiation 'grpc::ClientAsyncResponseReader<flatbuffers::BufferRef<MyGame::Example::Stat>>' being compiled
1>\grpc++/impl/codegen/call.h(308): error C3861: 'Deserialize': identifier not found
1>\grpc++/impl/codegen/call.h(310): error C2228: left of '.ok' must have class/struct/union
1>  \grpc++/impl/codegen/call.h(310): note: type is 'unknown-type'
````

**Comment by gwvo** [comment]
GRPC is still dependent on ProtoBuf in other places. Using it with FlatBuffers is largely driven from the generated code within the FlatBuffers project.

I have never compiled `grpctest` with Visual Studio, since at the time GRPC didn't support VS, but it looks like it does now?

`grpc::SerializationTraits` is defined in `flatbuffers/grpc.h`, so I'm not sure why that is an error here, but not in Linux.

**Comment by gwvo** [comment]
Also looks the CMake link library definition for `grpctest` may be *nix specific..

**Comment by rajc** [comment]
any ETA on when flatbuffers will be supported in Java?

**Comment by gwvo** [comment]
@rajc : Noone is actively working on Java support, as far as I know. Contributions welcome.

**Comment by ncteisen** [comment]
@ejona86 @iamqizhao This issue was cleaned up in today's bug scrub. Is this feature implemented in Java and/or Go? Should it be?

**Comment by ejona86** [comment]
It is not implemented in Java.

**Comment by gwvo** [comment]
Go support in progress here: https://github.com/google/flatbuffers/pull/4082 (please comment / participate).
Python appears stalled: https://github.com/google/flatbuffers/pull/4014

No progress on other languages that I know of.

**Comment by lbensaad** [comment]
@gwvo, What about grpc supporting Flatbuffers in Java? anyone working on this? when it will be ready?

**Comment by gwvo** [comment]
I haven't heard of anyone working on Java, contributions would be very welcome.
Can't make any promises when I will be able to get to it myself.

**Comment by gwvo** [comment]
Go support just landed in master: https://github.com/google/flatbuffers/pull/4082
Thanks, @JRonak !
Please go kick its tires :)

**Comment by nunofgs** [comment]
Any news on _node_ support?

**Comment by aardappel** [comment]
@nunofgs : I Haven't heard of anyone working on Node / JS.

**Comment by hsaliak** [comment]
Let's close this issue, there is work happening upstream and is tracked there.
