### ISSUE TITLE
Interop test timeout: tests.cloud_to_cloud:csharp:csharp_server:cancel_after_first_response

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5451]
https://grpc-testing.appspot.com/job/gRPC_interop_master/3106/testReport/junit/(root)/tests/cloud_to_cloud_csharp_csharp_server_cancel_after_first_response/

**Comment by jtattermusch** [comment]
Looks like this has been fixed sometime during the fixit.
