### ISSUE TITLE
Interop test timeout: tests.cloud_to_cloud:node:c++_server:ping_pong

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5452]
https://grpc-testing.appspot.com/job/gRPC_interop_master/3104/testReport/junit/(root)/tests/cloud_to_cloud_node_c___server_ping_pong/

**Comment by jcanizales** [comment]
Similarly here, with a Ruby server and "cancel after begin" test: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/2470/testReport/junit/(root)/tests/cloud_to_cloud_node_ruby_server_cancel_after_begin/

**Comment by jtattermusch** [comment]
Looks like this has been fixed sometime during the fixit.
