### ISSUE TITLE
clang3.4 and clang3.6 portability tests failed to build

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5455]
https://grpc-testing.appspot.com/job/gRPC_portability_master/481/language=c,scenario=linux_x64_clang3.4/console and https://grpc-testing.appspot.com/job/gRPC_portability_master/481/language=c,scenario=linux_x64_clang3.6/console

```
run_tests.py: error: argument --compiler: invalid choice: 'clang3.6' (choose from 'default', 'gcc4.4', 'gcc4.9', 'gcc5.3', 'vs2010', 'vs2013', 'vs2015')
```

**Comment by jtattermusch** [comment]
The support is still in a PR. https://github.com/grpc/grpc/pull/5381

**Comment by jtattermusch** [comment]
Feel free to merge it if you feel like reviewing. :)

**Comment by adelez** [comment]
Looks like @ctiller prefers to wait. Assigning to him to make the call.

**Comment by jtattermusch** [comment]
I've disabled the clang3.4 and clang3.6. Will re-enable once fixit is over and #5381 is merged.

**Comment by jtattermusch** [comment]
#5381 has been merged but we'll need to careful in re-enabling the tests, so this is not really actionable. Closing.
