### ISSUE TITLE
node test timeout "Cancelling surface client.Should correctly cancel a client stream call"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5457]
https://grpc-testing.appspot.com/job/gRPC_master/15409/config=asan,language=node,platform=linux/testReport/junit/(root)/Cancelling%20surface%20client/Should_correctly_cancel_a_client_stream_call/

**Comment by murgatroid99** [comment]
This probably has the same root cause as #5294.

**Comment by murgatroid99** [comment]
This was fixed by #5625.
