### ISSUE TITLE
node test timeout: "Client malformed response handling.should get an INTERNAL status with a server stream call"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5462]
https://grpc-testing.appspot.com/job/gRPC_master/15404/config=dbg,language=node,platform=macos/testReport/junit/(root)/Client%20malformed%20response%20handling/should_get_an_INTERNAL_status_with_a_server_stream_call/

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/15402/config=tsan,language=node,platform=linux/testReport/junit/(root)/Client%20malformed%20response%20handling/should_get_an_INTERNAL_status_with_a_server_stream_call/

**Comment by jtattermusch** [comment]
and possibly related: https://grpc-testing.appspot.com/job/gRPC_master/15402/config=tsan,language=node,platform=linux/testReport/junit/(root)/Client%20malformed%20response%20handling/should_get_an_INTERNAL_status_with_a_bidi_stream_call/

**Comment by murgatroid99** [comment]
This seems to have been fixed by #5610.
