### ISSUE TITLE
grpc-dev package in jessie-backports is still 0.11

### ISSUE THREAD

**Issue by sayrer** [grpc/grpc#5467]
Any chance this can be updated to 0.13?

**Comment by sayrer** [comment]
Ah, I see in #4910 the debian maintainer @andrewpollock is pretty active here. so cced.

**Comment by sayrer** [comment]
Any news on this?

**Comment by bjorndv** [comment]
I would also be very happy if the debian package would be updated.

**Comment by nicolasnoble** [comment]
Alright, we issued 0.13.1 yesterday, let's see about debian packages...

**Comment by sayrer** [comment]
@andrewpollock need any help with this?

**Comment by hsaliak** [comment]
The gRPC packaging has moved to the model of using completed language specific packages. Distro packages are not being maintained by this team any more, so I would defer this issue to the distro.

Closing the issue.
