### ISSUE TITLE
if no request for a long time, server died?

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#5468]
Hi

I run a server and found if no request for a long time, maybe 24 hours, then If I connect to server with same channel, will be a network error.

We use haproxy as load balance. How could client check health of the connection/channel? then how to fix channel and reconnect (with Python code and Java code)?

Thanks so much.

The error log in Java side below:

```
2016-02-27 15:24:29.786 [grpc-default-worker-ELG-3] ERROR io.netty.handler.codec.http2.Http2ConnectionHandler.error:181 - Sending GOAWAY failed: lastStreamId '0', errorCode '2', debugData 'connection timed out: internal-dev-internel-proxy-1365586739.cn-north-1.elb.amazonaws.com.cn/10.1.6.9:50052'. Forcing shutdown of the connection.
java.nio.channels.ClosedChannelException: null
2016-02-27 15:24:29.788 [http-bio-8080-exec-5] ERROR com.vipkid.security.impl.AuthorizeServiceImpl.getRoleList:55 - Server Error,User Token = 236d50b3-ea62-4174-ad65-c849166d14fa ,e={}
io.grpc.StatusRuntimeException: UNAVAILABLE
    at io.grpc.Status.asRuntimeException(Status.java:431) ~[grpc-core-0.13.1.jar:0.13.1]
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208) ~[grpc-stub-0.13.1.jar:0.13.1]
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141) ~[grpc-stub-0.13.1.jar:0.13.1]
    at com.vipkid.proto.service.AuthServiceGrpc$AuthServiceBlockingStub.getRoleList(AuthServiceGrpc.java:235) ~[auth-proto-1.1-20160226.061926-2.jar:na]
    at com.vipkid.client.service.AuthServiceClient.getRoleList(AuthServiceClient.java:68) ~[auth-client-1.1-20160226.071118-3.jar:na]
    at com.vipkid.security.impl.AuthorizeServiceImpl.getRoleList(AuthorizeServiceImpl.java:52) ~[AuthorizeServiceImpl.class:na]
    at sun.reflect.GeneratedMethodAccessor1046.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95) [spring-tx-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at com.sun.proxy.$Proxy35.getRoleList(Unknown Source) [na:na]
    at com.vipkid.service.StaffAuthService.login(StaffAuthService.java:64) [StaffAuthService.class:na]
    at com.vipkid.service.StaffAuthService$$FastClassBySpringCGLIB$$f265537e.invoke(<generated>) [spring-core-4.0.6.RELEASE.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.0.6.RELEASE.jar:4.0.6.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708) [spring-aop-4.0.6.RELEASE.jar:4.0.6.RELEASE]
```

**Comment by ejona86** [comment]
The Java client apparently received UNAVAILABLE from the server without any description. The Java implementation tries very hard to never generate a Status without a description, but the server can still reply without a description.

@GuoJing what language was the server implemented in?

**Comment by GuoJing** [comment]
@ejona86 hi, we using Python as server, Java as client. The solution we use right now is try to reconnect when channel is down.

**Comment by ejona86** [comment]
@GuoJing, so creating a new channel fixes the problem? That does sound more like a client-side issue. If you just retry on the same channel, does it work? The channel should auto-reconnect.

Are you using the OkHttp transport (for use on Android)? I just audited the Java code and found two places where UNAVAILABLE without a description could happen (grpc/grpc-java#1620), but only one was on client-side.

**Comment by giladwolff** [comment]
I believe I am hitting the same issue with a node js grpc client (0.14.1) and a java server (0.14.0). I create a client, and after a longish period of inactivity the first call on the client fails with UNAVAILABLE. If I retry I get a reply.

**Comment by dklempner** [comment]
This sounds to me a lot like a NAT or somesuch dropping idle connections. Depending on how exactly the router does this, the client may not notice anything is amiss until it tries to send an RPC.

**Comment by GuoJing** [comment]
Yep, We are using AWS ELB load balance, then IDLE connection will be
dropped in 1 mins.

The solution is try to reconnect the SHUTDOWN and TERMINATED channel before
we do something.

2016-05-26 9:58 GMT+08:00 David Klempner <notifications@github.com>:

> This sounds to me a lot like a NAT or somesuch dropping idle connections.
> Depending on how exactly the router does this, the client may not notice
> anything is amiss until it tries to send an RPC.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/issues/5468#issuecomment-221758080>
>



-- 
-----------------------
ありがとうございます。お邪魔しました。
http://www.guojing.me

**Comment by giladwolff** [comment]
So we are using aws elb as well, that is, the server is behind one of those. It seems though that the behavior of the java client is different than the behavior of the node js client. Anyway, recreating the client and retrying seems to work.

**Comment by ejona86** [comment]
@giladwolff, you should be able to reuse the same channel for the retry since the channel will reconnect.

**Comment by GuoJing** [comment]
I am using Python server implemented and Java Client.

It's really easy to find where the problem is. If I run the client and do
nothing, then in 30s or 1s which depends on AWS ELB setting, Client will
get the message (Channel has beed shutdown/terminated by another endpoint)
in log.

If we try to reuse channel this time, I will get the UNAVAILABLE.

In Java Client, I have to close channel and recreate a new channel object.
Looks like it won't reconnect.

But...

I have a Python client and Python server implemented, same on AWS ELB, if I
have a IDEL connection, the first try I will get UNAVAILABLE also, but the
second try will be ok. Just like what @wolff said.

And Yes. This is a client-side problem, but not that friendly.

Thanks and sorry for poor English. :)

2016-05-26 8:29 GMT+08:00 Gilad Wolff <notifications@github.com>:

> I believe I am hitting the same issue with a node js grpc client (0.14.1)
> and a java server (0.14.0). I create a client, and after a longish period
> of inactivity the first call on the client fails with UNAVAILABLE. If I
> retry I get a reply.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/issues/5468#issuecomment-221746675>
>



-- 
-----------------------
http://www.guojing.me

**Comment by GuoJing** [comment]
@giladwolff <https://github.com/giladwolff>

yes! If I am not getting wrong, both node js and Python implement are using
C Core code, the C core tcp listener will try to reconnect automatically,
but the first try is UNAVAILABLE. second try is ok.

But the Java implement has different behavior.

the fake code below:

```Java
public Stub getBlockingStub(){

    if(channel.isShutdown() and channel.isTerminated()){
        channel = newChannel();
    }
    return Stub(channel);
}

// every time I have to call this function to check if the channel is down
```

but the Python code which with C Core will not:

```python
channel = new_channel()
stub = new_stub(channel)
# wait here
stub.touch() # UNAVAILABLE
stub.touch() # return OK
```

We need to know, in Python implement, we don't have is_shutdown or
is_terminated interface.

2016-05-26 23:23 GMT+08:00 Gilad Wolff <notifications@github.com>:

> So we are using aws elb as well, that is, the server is behind one of
> those. It seems though that the behavior of the java client is different
> than the behavior of the node js client. Anyway, recreating the client and
> retrying seems to work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/issues/5468#issuecomment-221903723>
>



-- 
-----------------------
ret
http://www.guojing.me

**Comment by giladwolff** [comment]
I agree with GouJing that this is a client side bug in the way the channel notices/handles disconnections from the server.

**Comment by ejona86** [comment]
> // every time I have to call this function to check if the channel is down

@GuoJing, this doesn't really make sense, unless you are calling `channel.shutdown()` in your own code. The only way `channel.isShutdown()` or `channel.isTerminated()` will return true is if you have called `shutdown()` or `shutdownNow()`.

If you believe there is a bug in the Java client, could you provide the full Status, including the message for each of the RPC attempts?

**Comment by GuoJing** [comment]
@ejona86 Hi, I think the point is **AWS ELB**, ELB will terminate idle connection, I can't give a full status really, and I'm not the one who wrote the code, I'm write a gRPC server with Python (and gRPC python implement is still a lots of problem #6730 and #4969 )

here is our code:

```java
package com.vipkid.service.jedi.grpc;

import io.grpc.ManagedChannel;

public class ChannelNode{
	private ManagedChannel channel;
	private JediServiceGrpc.JediServiceBlockingStub blockingStub;
	
	public ChannelNode(ManagedChannel channel, JediServiceGrpc.JediServiceBlockingStub blockingStub){
		this.channel = channel;
		this.blockingStub = blockingStub;
	}
	
	public ManagedChannel getChannel() {
		return channel;
	}
	
	public JediServiceGrpc.JediServiceBlockingStub getBlockingStub() {
		return blockingStub;
	}
}
```

and

```java
package com.vipkid.service.jedi.grpc;

import io.grpc.ManagedChannel;
import io.grpc.netty.NettyChannelBuilder;

import org.apache.log4j.Logger;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.Random;

import static com.vipkid.service.jedi.grpc.JediServiceGrpc.JediServiceBlockingStub;


public class ChannelPool{
	private static final Logger logger = Logger.getLogger(ChannelPool.class);

   private static ChannelPool channelPool;
   private final List<ChannelNode> channelNodes = new CopyOnWriteArrayList<>();
   private String host;
   private int port;
   private int maxActive;

   private final static Object lock = new Object();
   private final Random random = new Random();

   private ChannelPool() {}

   public static ChannelPool getChannelPool(String host, int port, int maxActive){
	   if (channelPool != null) {
		   return channelPool;
	   }

	   synchronized (lock) {
		   if (channelPool != null) {
			   return channelPool;
		   }
		   channelPool = new ChannelPool();
		   channelPool.host = host;
		   channelPool.port = port;
		   channelPool.maxActive = maxActive;

		   //init  channelNodes
		   for (int i = 0; i < maxActive; i++) {
			   ChannelNode channelNode = channelPool.connect();
			   channelPool.channelNodes.add(channelNode);
		   }
	   }
	   return channelPool;
    }

   private ChannelNode connect(){
	   ManagedChannel channel = NettyChannelBuilder.forAddress(host, port)
			   .usePlaintext(true)
			   .build();
	   JediServiceBlockingStub blockingStub = JediServiceGrpc.newBlockingStub(channel);
	   return new ChannelNode(channel, blockingStub);
   }

   public void close() {
	   for(ChannelNode node : channelNodes) {
		   try {
			   node.getChannel().shutdownNow();
		   } catch (Exception e) {
			   logger.info("close channel error!");
		   }
	   }
   }

   public JediServiceBlockingStub getBlockingStub() {
	    int index = random.nextInt(maxActive);
	    ChannelNode channelNode = channelNodes.get(index);
	    ManagedChannel channel = channelNode.getChannel();
	    synchronized (lock) {
        // have to check connection status overtime
        // if we don't do this, we will get UNAVAILABLE
        // after this check, everything is OK
        if (channel.isShutdown() || channel.isTerminated()) {
                logger.error("RPC isShutdown, need reconnect and update channelList!");
                channelNode = connect();
                channelNodes.set(index, channelNode);
		    }
	    }
	    return channelNode.getBlockingStub();
    }

}
```

This is Java Client and Python Server.

If you think this is not a bug or this bug can not be reproduced, it ok to close this issue.

**Comment by GuoJing** [comment]
@ejona86 Hi, I think the point is **AWS ELB**, ELB will terminate idle connection, I can't give a full status really, and I'm not the one who wrote the code, I'm write a gRPC server with Python (and gRPC python implement is still a lots of problem #6730 and #4969 )

here is our code:

```java
package com.vipkid.service.jedi.grpc;

import io.grpc.ManagedChannel;

public class ChannelNode{
	private ManagedChannel channel;
	private JediServiceGrpc.JediServiceBlockingStub blockingStub;
	
	public ChannelNode(ManagedChannel channel, JediServiceGrpc.JediServiceBlockingStub blockingStub){
		this.channel = channel;
		this.blockingStub = blockingStub;
	}
	
	public ManagedChannel getChannel() {
		return channel;
	}
	
	public JediServiceGrpc.JediServiceBlockingStub getBlockingStub() {
		return blockingStub;
	}
}
```

and

```java
package com.vipkid.service.jedi.grpc;

import io.grpc.ManagedChannel;
import io.grpc.netty.NettyChannelBuilder;

import org.apache.log4j.Logger;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.Random;

import static com.vipkid.service.jedi.grpc.JediServiceGrpc.JediServiceBlockingStub;


public class ChannelPool{
	private static final Logger logger = Logger.getLogger(ChannelPool.class);

   private static ChannelPool channelPool;
   private final List<ChannelNode> channelNodes = new CopyOnWriteArrayList<>();
   private String host;
   private int port;
   private int maxActive;

   private final static Object lock = new Object();
   private final Random random = new Random();

   private ChannelPool() {}

   public static ChannelPool getChannelPool(String host, int port, int maxActive){
	   if (channelPool != null) {
		   return channelPool;
	   }

	   synchronized (lock) {
		   if (channelPool != null) {
			   return channelPool;
		   }
		   channelPool = new ChannelPool();
		   channelPool.host = host;
		   channelPool.port = port;
		   channelPool.maxActive = maxActive;

		   //init  channelNodes
		   for (int i = 0; i < maxActive; i++) {
			   ChannelNode channelNode = channelPool.connect();
			   channelPool.channelNodes.add(channelNode);
		   }
	   }
	   return channelPool;
    }

   private ChannelNode connect(){
	   ManagedChannel channel = NettyChannelBuilder.forAddress(host, port)
			   .usePlaintext(true)
			   .build();
	   JediServiceBlockingStub blockingStub = JediServiceGrpc.newBlockingStub(channel);
	   return new ChannelNode(channel, blockingStub);
   }

   public void close() {
	   for(ChannelNode node : channelNodes) {
		   try {
			   node.getChannel().shutdownNow();
		   } catch (Exception e) {
			   logger.info("close channel error!");
		   }
	   }
   }

   public JediServiceBlockingStub getBlockingStub() {
	    int index = random.nextInt(maxActive);
	    ChannelNode channelNode = channelNodes.get(index);
	    ManagedChannel channel = channelNode.getChannel();
	    synchronized (lock) {
        // have to check connection status overtime
        // if we don't do this, we will get UNAVAILABLE
        // after this check, everything is OK
        if (channel.isShutdown() || channel.isTerminated()) {
                logger.error("RPC isShutdown, need reconnect and update channelList!");
                channelNode = connect();
                channelNodes.set(index, channelNode);
		    }
	    }
	    return channelNode.getBlockingStub();
    }

}
```

This is Java Client and Python Server.

If you think this is not a bug or this bug can not be reproduced, it ok to close this issue.

**Comment by giladwolff** [comment]
I agree with GuoJing description - the ELB will close the connection after the idle connection timeout. This is not handled well in the grpc client code itself and forces callers, like GuoJing and myself to work around this. IMHO the grpc client code should notice that the channel was disconnected and try to reconnect.

**Comment by bobbytables** [comment]
We see this same problem with the Ruby client as well. Idle connection setting on AWS ELB is default 60s and once we increased it our calls stopped failing as frequently. We see a status 14 error happening in the client side.

**Comment by alamaison** [comment]
Does closing this ticket mean it's been fixed. Can you share any details of the fix?

**Comment by ejona86** [comment]
If the problem is just AWS ELB issues, then #7957 is a bit more refined issue to discuss on. I guess missing from that issue is keepalive support (grpc/grpc-java#1648 for java), which would cause gRPC to send PINGs after a configurable delay of inactivity (so you could configure it for 45s). Keepalive is scheduled to be complete for all implementations this quarter. Although the Java issue says keepalive won't go below one minute, there's some followup designs I need to publish that allow it to be much more aggressive if the service owner is willing to allow it.

**Comment by jiehu567** [comment]
Hi, I'm new user of gRPC, and I'm using python. can anyone tell me how to detect if the connection is shutdown from gRPC client side? and how to reconnect with a different channel? Better with example, I couldn't find in docs. And I've tried set futuer / describe etc. I'm using gRPC for a real-time service and any delay might lose users.  Tnx
