### ISSUE TITLE
There is no protoc 3.0.0+ yet make installs claims to need it

### ISSUE THREAD

**Issue by haisamido** [grpc/grpc#5469]
I successfully did the following (v3.0.0-beta2 is the highest version):

```
git clone https://github.com/google/protobuf.git
cd ./protobuf/
git checkout v3.0.0-beta-2
./autogen.sh
./configure
make
make check
sudo make install # installs in /usr/local/include/google/, /usr/local/bin/protoc
sudo ldconfig # refresh shared library cache
cd ..
```
and

```
git clone --recursive https://github.com/grpc/grpc.git
cd ./grpc/
git checkout release-0_13_0
git submodule update --init
make 
make test
```
but

`sudo make install
`

returns

```
We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.

Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

   make verify-install

```
There is no protoc 3.0.0+

**Comment by ctiller** [comment]
Protocol Buffers v3.0.0-beta-2 is what you want.

If you grab our submodules it's in third_party/protobuf.

**Comment by nicolasnoble** [comment]
So actually, I have seen that if you install protobuf 3, but still have
proto 2 on the system. Which will obviously create issues.

Please uninstall proto 2 from your system.

**Comment by haisamido** [comment]
I don't have proto 2.

How do I "grab" the submodules? I did git submodule update --init.  Do I need  to do something else.?

**Comment by sahilshekhawat** [comment]
@haisamido Yes, you grab submodules by ``git submodule update --init`` which contains ``third_party/protobuf`` which you need to compile yourself and install it (i.e. protobuf 3) since the official release is only at [2.6.1](https://developers.google.com/protocol-buffers/docs/downloads#release-packages). You can read the instructions to install it in the Readme (``third_party/protobuf/README.MD``)

**Comment by nathanielmanistaatgoogle** [comment]
Have all questions in this issue been answered? Should this issue be closed? What remains here?

**Comment by nathanielmanistaatgoogle** [comment]
Apparently nothing further is needed here; closing.
