### ISSUE TITLE
`gpr_getenv': env_linux.c:(.text+0x49): undefined reference to `dlsym'

### ISSUE THREAD

**Issue by dionescu** [grpc/grpc#5472]
In my bazel project I include grpc (tag = "release-0_13_0") and protobuf (tag = "v3.0.0-beta-2") via new_git_repository.  Trying to compile greeter_async_client, I got the error below. Adding linkopts "-ldl" to the grpc rule seems to fix the problem. Is this an issue with my specific configuration or is it a BUILD rule bug?

ERROR: /home/dragos/trunk/examples/rpc/helloworld/BUILD:31:1: Linking of rule '//examples/rpc/helloworld:greeter_async_client' failed: gcc failed: error executing command 
  (cd /home/dragos/.cache/bazel/_bazel_dragos/d6d537d024f15fe49a1f0b1df0136b24/trunk && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/examples/rpc/helloworld/greeter_async_client -pthread -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local_linux-fastbuild/bin/examples/rpc/helloworld/greeter_async_client-2.params): gcc failed: error executing command 
  (cd /home/dragos/.cache/bazel/_bazel_dragos/d6d537d024f15fe49a1f0b1df0136b24/trunk && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/examples/rpc/helloworld/greeter_async_client -pthread -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local_linux-fastbuild/bin/examples/rpc/helloworld/greeter_async_client-2.params).
bazel-out/local_linux-fastbuild/bin/external/grpc/libgrpc.a(env_linux.pic.o): In function `gpr_getenv':
env_linux.c:(.text+0x49): undefined reference to `dlsym'

**Comment by nicolasnoble** [comment]
Ah, yes. We need to update the build file.

**Comment by ctiller** [comment]
Odd... you should need to do -DGPR_BACKWARDS_COMPATIBILITY_MODE to get that code path looking at the code here: https://github.com/grpc/grpc/blob/release-0_13/src/core/support/env_linux.c

**Comment by ctiller** [comment]
I think this is stale. If it is not, it'll be caught and fixed with #1951
