### ISSUE TITLE
Interesting libtool warnings - sanity issue?

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#5473]
This doesn't seem to break anything, but maybe is a sanity issue to consider? I saw this on my ancient home desktop iMac.

/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (slice.o) in output file used for input files: /Users/vpai/Code/Git/grpc/objs/dbg/src/core/support/slice.o and: /Users/vpai/Code/Git/grpc/objs/dbg/src/cpp/util/slice.o (due to use of basename, truncation, blank padding or duplicate input files)
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (time.o) in output file used for input files: /Users/vpai/Code/Git/grpc/objs/dbg/src/cpp/util/time.o and: /Users/vpai/Code/Git/grpc/objs/dbg/src/core/support/time.o (due to use of basename, truncation, blank padding or duplicate input files)

**Comment by ctiller** [comment]
Yeah. I did some cleanup recently to get conflicts between core & boringssl
cleaned up. We need to do another pass on c++ and core, but I haven't found
the time yet.

If there's any interest in cleaning it up, I'd be happy to post a tweaked
sanity test as a PR for someone to make it pass (it's mostly going to be
about renaming some files).

**Comment by ctiller** [comment]
Like you mention, it doesn't hurt us yet, but it's certainly going to bite
at an unwanted point.

**Comment by y-zeng** [comment]
Do we still have this issue?

**Comment by vjpai** [comment]
This issue has been resolved  by #7828
