### ISSUE TITLE
[Ruby] Memory Leak in GRPC

### ISSUE THREAD

**Issue by zhuochun** [grpc/grpc#5476]
The same issue as reported in https://github.com/grpc/grpc/issues/4211

The original reporter listed ruby and php have the same problem at the end of the issue. But Ruby/PHP are not fixed by the fix.

https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_byte_buffer.c#L67
https://github.com/grpc/grpc/blob/release-0_11_1/src/php/ext/grpc/byte_buffer.c#L74 

I modified `examples/ruby/greeter` example script: https://gist.github.com/zhuochun/0b3bc724208559e1dca1

**Comment by murgatroid99** [comment]
@stanley-cheung Can you fix this for PHP?

**Comment by stanley-cheung** [comment]
I will take a look
