### ISSUE TITLE
(opt/c/windows) tests.vsprojects/Release/h2_fakesec_test.exe compressed_payload

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#5486]
https://grpc-testing.appspot.com/job/gRPC_master/15478/config=opt,language=c,platform=windows/

**Comment by nathanielmanistaatgoogle** [comment]
[gRPC_portability_master 1123.](https://grpc-testing.appspot.com/job/gRPC_portability_master/1123/language=c,scenario=windows_x64_vs2015/console)

**Comment by nicolasnoble** [comment]
The build has disappeared from Jenkins since then. Please copy the relevant logs to the issue comments, or hit the "Keep this build forever" button on Jenkins.
