### ISSUE TITLE
(dbg / c/ windows) tests.vsprojects/Debug/h2_proxy_nosec_test.exe payload

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#5487]
https://grpc-testing.appspot.com/job/gRPC_master/15478/config=dbg,language=c,platform=windows/

**Comment by soltanmm** [comment]
https://grpc-testing.appspot.com/job/gRPC_portability_master/977/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_proxy_nosec_test_exe_payload/

**Comment by murgatroid99** [comment]
https://grpc-testing.appspot.com/job/gRPC_portability_master/1054/language=c,scenario=windows_x86_vs2015/testReport/junit/(root)/tests/vsprojects_Debug_h2_proxy_nosec_test_exe_payload/

**Comment by nicolasnoble** [comment]
The build has disappeared from Jenkins since then. Please copy the relevant logs to the issue comments, or hit the "Keep this build forever" button on Jenkins.
