### ISSUE TITLE
Move Python to the new batch API

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#549]
This is a tracking bug so I know when things are done

**Comment by ctiller** [comment]
What's the status on this?

**Comment by nathanielmanistaatgoogle** [comment]
We'd like to do it sometime in the next six-week release cycle.

**Comment by ctiller** [comment]
Could we prioritize it earlier in the cycle, to give a chance to expunge
the old API's towards the end?

**Comment by nathanielmanistaatgoogle** [comment]
Fair question; I'll try to answer by the end of the day.

**Comment by nathanielmanistaatgoogle** [comment]
Yes, we'll try to have this done by 5 May.
