### ISSUE TITLE
Consider removing the flattened CallOptions overload from C# GRPC generated client service code?

### ISSUE THREAD

**Issue by chrisdunelm** [grpc/grpc#5498]
While considering altering the code structure of C# GRPC generated service code in #5371 might we also consider removing the flattened CallOptions overloads from the client code?
So instead of calling an RPC method like this:
```C#
client.Method1Async(request,
    cancellationToken: myCancellationToken,
    deadline: myDeadline);
```
The call would need to use the explicit CallOptions method like this, which is functionally equivalent:
```C#
client.Method1Async(request, new CallOptions(
    cancellationToken: myCancellationToken,
    deadline: myDeadline));
```
A few of reasons for suggesting this:
* GRPC-generated code is expected to be low-level and simple; providing functionally-equivalent overloads goes against this somewhat.
* For many APIs we would expect users to target a higher-level API than this, so providing simplicity at this level isn't required.
* Removing this overload reduces the API surface area, making client-side testing/mocking/faking simpler.

**Comment by jskeet** [comment]
Result of discussion: whether we move to abstract classes or not, extension methods would be better here, for both testing and simple expression of capabilities. So let's keep the overloads "logically", but express them via extension methods instead of being part of the interface/abstract-class.

**Comment by jtattermusch** [comment]
Isn't this one basically the same topic as https://github.com/grpc/grpc/issues/5323? Let's keep just one of these issues alive to track the progress.

**Comment by jtattermusch** [comment]
I think the resolution is the keep those overloads and make them call the CallOptions based overload (as described in #5323)
