### ISSUE TITLE
consolidate the base64 implementation

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#55]
We need base64 for both auth/security and chttp2 with different options. However the chttp2 code base currently does not support decoding (but this is coming soon) and not the options needed for encoding. 

The plan is as follows.
1 ctiller@ submits the base64 decode in chttp2
2 jboeuf@ moves it to support/base64 and adds the options needed for security/auth and adapts both the chttp2 and auth code.

Craig, your turn!

**Comment by vjpai** [comment]
I'm assigning this old bug, but feel free to close it if it is considered obsolete at this point.

**Comment by jboeuf** [comment]
I think that this is still a concern. @ctiller, I thought you were going to
have a look at this first? :).

**Comment by ctiller** [comment]
Hey - this is still on my plate. We should tackle it, but with appropriate priority.

**Comment by y-zeng** [comment]
The base64 decoder has been submitted in chttp2.

**Comment by yang-g** [comment]
Is this done?

**Comment by paralin** [comment]
Oldest issue! Looks done.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable address this issue with the current information (it might be already resolved). If you are still experiencing this issue, please re-open the issue with information on how to reproduce.

**Comment by jiangtaoli2016** [comment]
Is this still an issue? Shall we close if nobody care?

**Comment by sreecha** [comment]
This is done. i believe the code is in `src/lib/slice/b64.cc`
