### ISSUE TITLE
Building grpc++ failed on windows

### ISSUE THREAD

**Issue by LukeMauldin** [grpc/grpc#5507]
Attempting to build grpc++ in X64 mode using Visual Studio 2015 Service Pack 1 fails in Windows with the text below.  Building the grpc project in the solution compiled successfully but I need to use the grpc++ libraries in other C++ code which is why I need to build the grpc++ project.  I disabled the `boringssl` and `z` projects as recommended by other issues in this project. 

```
1>------ Build started: Project: grpc++, Configuration: Release-DLL x64 ------
1>  proto_utils.cc
1>C:\Users\mauldinl\Downloads\protobuf-3.0.0-beta-2\src\google/protobuf/io/coded_stream.h(1138): error C2220: warning treated as error - no 'object' file generated
1>C:\Users\mauldinl\Downloads\protobuf-3.0.0-beta-2\src\google/protobuf/io/coded_stream.h(1138): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by LukeMauldin** [comment]
Also, building the grpc++_unsecure project failed too:

```
Build started: Project: grpc++_unsecure, Configuration: Release-DLL x64 ------
1>  proto_utils.cc
1>C:\Users\mauldinl\Downloads\protobuf-3.0.0-beta-2\src\google/protobuf/io/coded_stream.h(1138): error C2220: warning treated as error - no 'object' file generated
1>C:\Users\mauldinl\Downloads\protobuf-3.0.0-beta-2\src\google/protobuf/io/coded_stream.h(1138): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by LukeMauldin** [comment]
FYI, removing the "Treat Warnings as Error Flag" worked and allow the project to compile.

**Comment by topillar** [comment]
modification of line 1138 ：int size = end - target;
to ==>
                 int size = int( end - target);

can remove the error.

**Comment by goldenbull** [comment]
when will the submodule protobuf be upgraded to a recent version?
