### ISSUE TITLE
(opt / c / windows) tests.vsprojects/Release/h2_fakesec_test.exe call_creds

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#5508]
https://grpc-testing.appspot.com/job/gRPC_master/15494/config=opt,language=c,platform=windows/

Also in the following builds:
https://grpc-testing.appspot.com/job/gRPC_master/15490
https://grpc-testing.appspot.com/job/gRPC_master/15462

**Comment by soltanmm** [comment]
On portability master:
https://grpc-testing.appspot.com/job/gRPC_portability_master/968/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_fakesec_test_exe_call_creds/

**Comment by nathanielmanistaatgoogle** [comment]
[Build 1123.](https://grpc-testing.appspot.com/job/gRPC_portability_master/1123/language=c,scenario=windows_x64_vs2015/console)

**Comment by nicolasnoble** [comment]
The build has disappeared from Jenkins since then. Please copy the relevant logs to the issue comments, or hit the "Keep this build forever" button on Jenkins.
