### ISSUE TITLE
"run_tests.py -n=<more than one> -j=<more than one>" fails for Python

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5522]
Looks like we're invoking `coverage` in a way that assumes it's the only invocation for the user at its particular moment in time:
```
py27 runtests: commands[2] | /home/nathaniel/grpc/.tox/py27/bin/coverage combine
Couldn't read data from '/home/nathaniel/grpc/.coverage': ValueError: Expecting , delimiter: line 1 column 8328 (char 8
327)
ERROR: InvocationError: '/home/nathaniel/grpc/.tox/py27/bin/coverage combine'
```

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: @makdharma asked for some way he might be able to assist us; I think this might be a good work item on which he might start. Do you agree? Do you already have the answer in your back pocket, or have recommendations for him?

**Comment by jtattermusch** [comment]
there are more problems with running python tests in parallel - tox basically cannot handle that because it tries to install missing dependencies after the tests start and clashes with other concurrent runs of tox.

PR https://github.com/grpc/grpc/pull/5541 might actually resolve this issue.

**Comment by makdharma** [comment]
Agreed, PR #5541 should fix this. Coverage file gets messed up when multiple runs are in flight.

**Comment by jtattermusch** [comment]
#5541 was merged.
