### ISSUE TITLE
Adopt node convention of having the callback be the last function argument for client requests

### ISSUE THREAD

**Issue by AndrewIngram** [grpc/grpc#5526]
In Client.js `makeUnaryRequest` and `makeClientStreamRequest` both ignore the node convention of having function callbacks be the last parameter. This means we can't use existing promisify or promisifyAll implementations to automatically build promise-returning versions of request functions.

It'd be nice to go one step further and actually return promises too.

Changing the method signature would be a breaking change, but grpc is still in beta, so it's plausible. I think returning promises could be done without breaking anything.

**Comment by murgatroid99** [comment]
This is a good point. Currently, required parameters are before the callbacks, and optional parameters are after them. This makes some simple usages of the API look a little cleaner, but I understand that that doesn't help if it breaks some tools. I think this changes is probably worth making.

I don't think that returning a promise is the correct thing to do here, though. Node currently does not have a single official promise API, and gRPC should not be dictating what kind of promises its users use.

**Comment by murgatroid99** [comment]
This has been resolved by #5900.
