### ISSUE TITLE
Use Protobuf Json for examples

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#5533]
In https://github.com/grpc/grpc-java/pull/1505  I changed java to use the json formatted protobuf rather than plain old JSON.  This cleans up a dependency (and shows off our cool protobuf json formatting!)

grpc core should make a similiar change to stay in sync.   I believe the files that need to be updated are 
- grpc/examples/cpp/route_guide/route_guide_db.json
- grpc/examples/csharp/route_guide/RouteGuide/route_guide_db.json
- grpc/examples/node/route_guide/route_guide_db.json
- grpc/examples/objective-c/route_guide/route_guide_db.json
- grpc/examples/python/route_guide/route_guide_db.json

**Comment by vjpai** [comment]
This is an excellent point; it's a question of a lot of interest based on
the community meetup yesterday.
