### ISSUE TITLE
python error on Travis CI because wrong python protobuf is installed (3.0.0-alpha-1 vs. 3.0.0a3)

### ISSUE THREAD

**Issue by michael-berlin** [grpc/grpc#5534]
We hit the following issue recently:

- the Python gRPC 0.13 stubs are generated with protobuf 3.0.0-beta2
(which is also the version you use as [submodule](https://github.com/grpc/grpc/blob/release-0_13/.gitmodules))

- the gRPC python 0.13 source install command [requires python protobuf >= 3.0.0-alpha3](https://github.com/grpc/grpc/blob/release-0_13/setup.py#L152). However, 3.0.0a3 is not compatible with the Python code generated by protobuf 3.0.0-beta2.

When we try to run the 3.0.0b2 generated code with the 3.0.0a3 library, we see this error:

```py
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

Usually, this is not a problem because ```pip install .``` installs the most recent version 3.0.0b2 by default. But we've hit certain cases where it installs 3.0.0a3 and the code fails to run.

Tagging @soltanmm to get his attention on this.

**Comment by soltanmm** [comment]
This doesn't sound like a protobuf 3.0.0b2 vs. 3.0.0a3 issue, it sounds like a protobuf 2.x vs protobuf 3.x issue. The stubs are generated from C++ code that has remained (w.r.t. the salient bits of this discussion) unchanged as we've upgraded protobuf versions AFAIK.

Are you 100% certain that the protobuf in your runtime environment is 3.x? Can you provide, for both your runtime and your build environments, the output of `pip show protobuf`?

**Comment by michael-berlin** [comment]
You're right. It seems to be a protobuf 2.x vs 3.x issue.

Initially, we thought the "syntax" parameter was not part of protobuf 3.x. But that's not the case.

The only thing we know so far is that:

```py
from google import protobuf
print protobuf.__version__
```

prints:

```
3.0.0-alpha-1
```

but:

```
from google.protobuf import descriptor as _descriptor
DESCRIPTOR = _descriptor.FileDescriptor(
  name='topodata.proto',
  package='topodata',
  syntax='proto3',
  serialized_pb=_b('\n\x...')
)
```

fails:

```
$ ./test/resharding.py
Traceback (most recent call last):
  File "./test/resharding.py", line 14, in <module>
    from vtproto import topodata_pb2
  File "/home/travis/gopath/py-vtdb/vtproto/topodata_pb2.py", line 23, in <module>
    ount\x18\x05 \x01(\x05\x1ar\n\x11KeyspacePartition\x12)\n\x0bserved_type\x18\x01 \x01(\x0e\x32\x14.topodata.TabletType\x12\x32\n\x10shard_references\x18\x02 \x03(\x0b\x32\x18.topodata.ShardReference\x1aI\n\nServedFrom\x12)\n\x0btablet_type\x18\x01 \x01(\x0e\x32\x14.topodata.TabletType\x12\x10\n\x08keyspace\x18\x02 \x01(\t*2\n\x0eKeyspaceIdType\x12\t\n\x05UNSET\x10\x00\x12\n\n\x06UINT64\x10\x01\x12\t\n\x05\x42YTES\x10\x02*\x8f\x01\n\nTabletType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06MASTER\x10\x01\x12\x0b\n\x07REPLICA\x10\x02\x12\n\n\x06RDONLY\x10\x03\x12\t\n\x05\x42\x41TCH\x10\x03\x12\t\n\x05SPARE\x10\x04\x12\x10\n\x0c\x45XPERIMENTAL\x10\x05\x12\n\n\x06\x42\x41\x43KUP\x10\x06\x12\x0b\n\x07RESTORE\x10\x07\x12\n\n\x06WORKER\x10\x08\x1a\x02\x10\x01\x42\x1a\n\x18\x63om.youtube.vitess.protob\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

See the full log here: https://travis-ci.org/youtube/vitess/builds/113076391

I also cannot reproduce the issue locally when I explicitly install protobuf=3.0.0a3. I'll do more debugging on Travis :(

**Comment by soltanmm** [comment]
When y'all are in your runtime environment, do you have multiple installations of `protobuf` across the system, a virtualenv, and/or any other configuration that results in multiple versions of `protobuf` existing on the same system? Even if you *think* they're not supposed to interact, are they there? This includes things like `*.egg` files that are installed when gathering dependencies via `setup.py` scripts et al.

**Comment by michael-berlin** [comment]
@soltanmm I found the issue now.

The clash is between protobuf 3.0.0 __-alpha-1__ and __a3__.

grpc python install triggers install of protobuf 3.0.0a3:

```
Downloading/unpacking protobuf>=3.0.0a3 (from grpcio==0.13.0)
  Downloading protobuf-3.0.0-alpha-1.tar.gz (193Kb): 193Kb downloaded
  Running setup.py egg_info for package protobuf

[...]

  Running setup.py install for protobuf
    Skipping installation of /home/travis/gopath/dist/grpc/usr/local/lib/python2.7/site-packages/google/__init__.py (namespace package)
    
    Installing /home/travis/gopath/dist/grpc/usr/local/lib/python2.7/site-packages/protobuf-3.0.0_alpha_1-py2.7-nspkg.pth
 ```

But as you can see it's installing the wrong version, namely 3.0.0-alpha-1.

I can reproduce the issue when I install __alpha-1__ locally.

The work-around is to manually install version __a3__ or higher:

```sh
$ pip install -U protobuf==3.0.0a3
```

The problem is probably that "-alpha-1" always wins over "a3" when pip compares the versions?

**Comment by michael-berlin** [comment]
Issue was already reported on the protobuf project: https://github.com/google/protobuf/issues/855

Nathaniel already ran into it last year :(

Given that Travis still has the package available, you should consider to pin gRPC Python to a specific version until protobuf 3.0.1 or higher is released ;-)

**Comment by soltanmm** [comment]
I'm gonna push back on that, please bear with me:
Have you tried clearing the `pip` cache on the target machine (or skipping it w/ `--no-cache-dir`)? It looks like Travis CI doesn't run its own PyPI mirror, so the package has to be coming from somewhere else (hopefully somewhere relatively ephemeral).

**Comment by michael-berlin** [comment]
I feel like Travis CI is caching the bad package somewhere on their side.

I am not familiar with Python/easy_install but this looks suspicious:

> Installed /tmp/easy_install-ov8mg_/**protobuf***-3.0.0-alpha-1/***google_apputils***-0.4.2-py2.7.egg

It looks like ```/tmp/easy_install-ov8mg_/protobuf-3.0.0-alpha-1/``` is a cache which contains multiple packages.

I'll file a bug with them.

For now, I'll probably just locally patch the >=3.0.0a3 to a == during our bootstrap phase as long as we are in this transition period.

Thanks for looking into it :)
