### ISSUE TITLE
Fill in bogus values for fields that should not be checked

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#5553]
For example, in the result of grpc_completion_queue_next, only the type is supposed to be valid on TIMEOUT or SHUTDOWN; the success and tag fields are not supposed to be checked and should maybe instead be assigned to 0xdeadbeef.

**Comment by ctiller** [comment]
Maybe it's an opportunity to use the build system for good... Return the
lower 4 or 8 bytes of md5(version)... To make sure it's absolutely not a
value people can hard code.

**Comment by vjpai** [comment]
Yes, excellent!

**Comment by vjpai** [comment]
We haven't justified the needed time expenditure for this yet, and all our *san make this less critical than it used to be.
