### ISSUE TITLE
GRPC fails to compile on Ubuntu 

### ISSUE THREAD

**Issue by raghu04012012** [grpc/grpc#5557]
Generating cache.mk
[C]       Compiling src/core/client_config/subchannel.c
src/core/client_config/subchannel.c: In function ‘disconnect’:
src/core/client_config/subchannel.c:272:5: error: conversion of unsigned constant value to negative integer [-Werror=sign-conversion]
cc1: all warnings being treated as errors
make: *** [/home/developer/grpc-master/objs/opt/src/core/client_config/subchannel.o] Error 1

**Comment by sahilshekhawat** [comment]
I just compiled for the first time and there is no error.

**Comment by ctiller** [comment]
Which version of Ubuntu?

**Comment by sahilshekhawat** [comment]
I tested it on 14.04 with GCC 4.8.4 and it is compiling fine.

**Comment by raghu04012012** [comment]
Ubuntu 12.04

**Comment by raghu04012012** [comment]
The function takes int pointer as argument but inside subchannel.c file constant is being passed gpr_atm_no_barrier_store(&c->connected_subchannel, 0xdeadbeef);

**Comment by lisroach** [comment]
I ran into the same problem on 12.04, switched to 14.04 and it ran fine
