### ISSUE TITLE
Doc Fixit: cpp example section slightly confusing

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#5559]
This section: https://github.com/grpc/grpc/tree/master/examples/cpp#generating-grpc-code

listed a command: `make helloworld.grpc.pb.cc helloworld.pb.cc` but it appears to be not something to be executed by the user following the guide. It appears that the `make` command listed in the section below will eventually trigger that.

So perhaps we can remove that command, or show it in a way that is not guiding the user to execute it?

**Comment by LisaFC** [comment]
I think I'd remove it, given that it doesn't add anything useful for the user to do, and the relevant information (the actual command to invoke protoc) is in the tutorial.
