### ISSUE TITLE
python test timeout: _face_interface_test.DynamicInvokerBlockingInvocationInlineServiceTest

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5563]
https://grpc-testing.appspot.com/job/gRPC_master/15549/config=dbg,language=python,platform=linux/testReport/junit/(root)/tests/py_test__face_interface_test_DynamicInvokerBlockingInvocationInlineServiceTest/

**Comment by makdharma** [comment]
Not able to reproduce timeout (on Mac OSx) but running into this -
	/Users/makarandd/Work/gitx/grpc/src/python/grpcio/grpc/_cython/cygrpc.so: truncated fat file.  file length=892928, but needed slice goes to 2603860

My command line is -
python run_tests.py -l python -r DynamicInvokerEventInvocationSynchronousEventServiceTest -n 100 -t

**Comment by soltanmm** [comment]
@makdharma Looks like the same error as #5568. Would you mind commenting in that bug at which commit number you encountered that? We supposedly addressed it with #5569.

**Comment by makdharma** [comment]
I am exactly at that commit, yet I see this. My git log is -

bash-3.2$ git log | head
commit 66a6d014a4b2afec45906ff803e31dd89e82e22a
Author: Jan Tattermusch <jtattermusch@google.com>
Date:   Thu Mar 3 12:35:08 2016 -0800

    run build_ext in build_python step

commit 4473dd5b88bf18c51f7574bc835c4c74c08ecc80
Merge: 40d27ba 072ebaa
Author: Jan Tattermusch <jtattermusch@users.noreply.github.com>
Date:   Thu Mar 3 11:16:42 2016 -0800
bash-3.2$

**Comment by soltanmm** [comment]
That's actually expected at that commit; the command needs to run to know it has nothing to do (and then do nothing). That you still see that error *is* weird though, and we'll look into it.

**Comment by nathanielmanistaatgoogle** [comment]
Buildpony seeing this still.

**Comment by jtattermusch** [comment]
The problematic testcase seems to be almost always testParallelInvocations or testWaitingForSomeButNotAllParallelInvocations

**Comment by jtattermusch** [comment]
This seem to be fixed by #5763
