### ISSUE TITLE
python test timeout: _face_interface_test.MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5566]
https://grpc-testing.appspot.com/job/gRPC_master/15549/config=dbg,language=python,platform=macos/testReport/junit/(root)/tests/py_test__face_interface_test_MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest/

**Comment by jcanizales** [comment]
Seen again [here](https://grpc-testing.appspot.com/job/gRPC_pull_requests/6931/), along with three more friends.

**Comment by jtattermusch** [comment]
This seem to be fixed by #5763
