### ISSUE TITLE
python test timeout: _face_interface_test.DynamicInvokerEventInvocationSynchronousEventServiceTest

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5567]
https://grpc-testing.appspot.com/job/gRPC_master/15549/config=dbg,language=python,platform=macos/testReport/junit/(root)/tests/py_test__face_interface_test_DynamicInvokerEventInvocationSynchronousEventServiceTest/

**Comment by jtattermusch** [comment]
Similar for asynchronous as well.
https://grpc-testing.appspot.com/job/gRPC_master/15549/config=opt,language=python,platform=macos/testReport/junit/(root)/tests/py_test__face_interface_test_DynamicInvokerFutureInvocationAsynchronousEventServiceTest/

**Comment by soltanmm** [comment]
Same problem as #5568.

**Comment by soltanmm** [comment]
I closed this prematurely.

**Comment by nathanielmanistaatgoogle** [comment]
Seen again.

**Comment by jtattermusch** [comment]
Interesting observation is that the _crust_over_core_face_interface_test.GenericInvokerEventInvocationSynchronousEventServiceTest is also flaky, while not touching C core at all - "_crust_over_core_face_interface_test" only tests python code. (locally I got 4 timeouts out of 1000 runs).

**Comment by jtattermusch** [comment]
if I skip all the other tests, and only run _crust_over_core_face_interface_test.GenericInvokerEventInvocationSynchronousEventServiceTest.testFailedUnaryRequestStreamResponse, I can still observe some timeout flakes.

**Comment by jtattermusch** [comment]
I attached to a test run that was hanging and this is what I saw:

```
  5    Thread 0x7f44eb852700 (LWP 2282) "python" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  4    Thread 0x7f44ea810700 (LWP 2325) "python" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  3    Thread 0x7f44e980e700 (LWP 2328) "python" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  2    Thread 0x7f44e900d700 (LWP 2329) "python" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
* 1    Thread 0x7f44f2a90740 (LWP 1306) "python" 0x0000000000499837 in PyEval_EvalFrameEx ()



thread 1
 waiting for test to finish - not interesting

thread 2 

waiting in Queue.get()
work_item = work_queue.get(block=True)
(probably use-spawned thread)

thread 3 

waiting in Queue.get()
work_item = work_queue.get(block=True)
(probably use-spawned thread)

thread 4 

waiting in Queue.get()
(probably use-spawned thread)

thread 5 

/usr/local/google/home/jtattermusch/github/grpc/src/python/grpcio/tests/unit/framework/interfaces/face/_receiver.py, line 74, in block_until_terminated: self._condition.wait()

/usr/local/google/home/jtattermusch/github/grpc/src/python/grpcio/tests/unit/framework/interfaces/face/_event_invocation_synchronous_event_service.py, line 357, in testFailedUnaryRequestStreamResponse
receiver.block_until_terminated()
```

**Comment by jtattermusch** [comment]
Test was removed in #5728 (but we are still seeing a similar deadlock in other tests).
