### ISSUE TITLE
Python tests cannot load cygrpc.so during run_tests.py invocation w/ 'no suitable image found' error

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5568]
https://grpc-testing.appspot.com/job/gRPC_master/15549/config=dbg,language=python,platform=macos/testReport/junit/(root)/tests/py_test__crust_over_core_over_links_face_interface_test_GenericInvokerEventInvocationSynchronousEventServiceTest/

**Comment by soltanmm** [comment]
Just a hunch, but the error on this one looks like it was a race condition on the file system wherein someone was trying to load the shared object while someone else was rewriting it.

**Comment by jtattermusch** [comment]
Agreed. I think it has to do with 
```
running build_ext
copying python_build/lib.macosx-10.10-intel-2.7/grpc/_cython/cygrpc.so -> ./src/python/grpcio/grpc/_cython
```

**Comment by soltanmm** [comment]
Weirder than that: those `running build_ext` bits are in the logs *after* the tests have started. They should very much be *before*...

**Comment by soltanmm** [comment]
Oh, haha, I got jumbled up. Didn't realize that we hadn't merged #5569 yet. That should help, yes.

**Comment by jtattermusch** [comment]
I think even with #5569 we might see this problem (is there a way to disable running build_ext in the test fully?).

**Comment by soltanmm** [comment]
Not without making a custom command for testing, AFAIK. But if it's already built once the system *should* detect it and realize not to rebuild. I don't see any signs of the contrary on #5569.

**Comment by jtattermusch** [comment]
I think basically the same problem can also show up as this:
```
ImportError: dlopen(/jenkins/workspace/gRPC_master/config/opt/language/python/platform/macos/src/python/grpcio/grpc/_cython/cygrpc.so, 2): no suitable image found.  Did find:
	/jenkins/workspace/gRPC_master/config/opt/language/python/platform/macos/src/python/grpcio/grpc/_cython/cygrpc.so: truncated fat file.  file length=315392, but needed slice goes to 2629896
```
https://grpc-testing.appspot.com/job/gRPC_master/15639/config=opt,language=python,platform=macos/testReport/junit/(root)/tests/py_test__base_interface_test_SyncEasyTest/

**Comment by jtattermusch** [comment]
Also, this could exhibit as: 
`ImportError: /var/local/git/grpc/src/python/grpcio/grpc/_cython/cygrpc.so: cannot open shared object file: No such file or directory`

**Comment by soltanmm** [comment]
Yeah, all sounds like the same problem.
