### ISSUE TITLE
huge amount of TIME_WAIT tcp connections on windows

### ISSUE THREAD

**Issue by goldenbull** [grpc/grpc#5582]
When there are many connections and each connection is established and closed frequently, the TCP ports will be exhausted and `netstat -an` reports a lot of `TIME_WAIT` connections. Seems one peer doesn't close the socket gracefully.

```
  TCP    [::1]:50515            [::1]:50051            TIME_WAIT
  TCP    [::1]:50529            [::1]:50051            TIME_WAIT
  TCP    [::1]:50532            [::1]:50051            TIME_WAIT
  TCP    [::1]:50535            [::1]:50051            TIME_WAIT
  TCP    [::1]:50539            [::1]:50051            TIME_WAIT
  TCP    [::1]:50545            [::1]:50051            TIME_WAIT
```

**Comment by goldenbull** [comment]
more info:
same huge amount of TIME_WAIT on ubuntu.

**Comment by dklempner** [comment]
This is normal behavior for TCP. When you close a TCP connection, the connection moves to a special state (TIME_WAIT) for a while to account for packets that might arrive out of order, so they don't interfere with a later connection. Typically this lasts for about 30-120 seconds.

With respect to port exhaustion: The only (fundamental) restriction is that 5-tuples (source IP, source port, destination IP, destination port, protocol=TCP) must be unique. The reason you're observing ports being exhausted is that your source IP and destination IP and destination port are all fixed.

If you restrict yourself to ephemeral ports (typically at least 49152-65535) you get 16K source ports. This means with a 120 second TIME_WAIT you can churn 130 connections per second without running out.

Importantly, someone trying to connect from a different IP would have no problem. The only bad thing you can accomplish is prevent yourself (and other processes on the same machine) from connecting to a particular destination IP:port.

**Comment by goldenbull** [comment]
thanks @dklempner , I got it :+1:
