### ISSUE TITLE
Enable remote interop tests in Travis (or Jenkins)

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5605]
`xctool` won't do networking (except localhost) for library tests, as it won't start up the simulator for them. They have no intention of changing that (per https://github.com/facebook/xctool/issues/553#issuecomment-131918393 and https://github.com/facebook/xctool/issues/579#issuecomment-141249669 ), so to get C.I. testing for the remote tests we'll have to change our tests project to be an app (instead of a library project).

CC: @makdharma

**Comment by makdharma** [comment]
@jtattermusch - Can we turn on Jenkins ObjC tests yet?

**Comment by jtattermusch** [comment]
ObjC tests are now running on Jenkins on gRPC_master and gRPC_pull_requests.
https://grpc-testing.appspot.com/job/gRPC_master/17438/
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/9712

**Comment by jtattermusch** [comment]
Let me know if there's any more actions expected from me.

**Comment by makdharma** [comment]
Nothing more needs to be done. Jenkins tests include remote interop tests. closing.,
