### ISSUE TITLE
make failed on Ubuntu 14.04 complaining error: GetUmbrellaClassName was not declared in this scope

### ISSUE THREAD

**Issue by coconut73** [grpc/grpc#5612]
Python 2.7, gpb 3.0 have been installed successfully.

follow the steps git clone and submodule --init, then make.

Error in make:

HOSTCXX] Compiling src/compiler/csharp_generator.cc
src/compiler/csharp_generator.cc:47:43: error: â€google::protobuf::compiler::csharp::GetUmbrellaClassNameâ€ has not been declared
 using google::protobuf::compiler::csharp::GetUmbrellaClassName;
                                           ^
src/compiler/csharp_generator.cc: In function â€void grpc_csharp_generator::{anonymous}::GenerateServiceDescriptorProperty(grpc::protobuf::io::Printer*, const ServiceDescriptor*)â€:
src/compiler/csharp_generator.cc:237:62: error: â€GetUmbrellaClassNameâ€ was not declared in this scope
              "umbrella", GetUmbrellaClassName(service->file()), "index",
                                                              ^
make: *** [/opt/jvision/grpc/objs/opt/src/compiler/csharp_generator.o] Error 1
root@rpt-reg-grpc-ubuntu02:/opt/jvision/grpc# ^C

**Comment by jtattermusch** [comment]
You need to have protobuf 3.0.0beta2.

Check that your third_party/protobuf submodule is up to date and that you don't have older version of protobuf installed on your system.

**Comment by jtattermusch** [comment]
Closing for now, feel free to reopen if you still have issues.
