### ISSUE TITLE
mac-node-3 not able to compile protobuf

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5613]
missing autosomething?

CC @jtattermusch @nicolasnoble 

https://grpc-testing.appspot.com/job/gRPC_master/15577/config=dbg,language=c++,platform=macos/console

**Comment by jtattermusch** [comment]
Hm, yeah I'm on it.

It looks like it might be the new https://wiki.jenkins-ci.org/display/JENKINS/pre-scm-buildstep plugin.

autoconf and xbuild are /usr/local/bin   so perhaps the PATH is set incorrectly.

**Comment by jtattermusch** [comment]
And i've verified that the tools are actually installed properly (by sshing to the workers).

**Comment by jtattermusch** [comment]
From a job run on jenkins:
`PATH=/Users/jenkinsnode2/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin`

when SSH'd
`PATH=Users/jenkinsnode2/.nvm/versions/node/v4.2.6/bin:/usr/local/rvm/gems/ruby-2.1.5/bin:/usr/local/rvm/gems/ruby-2.1.5
@global/bin:/usr/local/rvm/rubies/ruby-2.1.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/rvm/bin`

**Comment by jtattermusch** [comment]
This could also be the https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin   that I installed in the morning (but we are not using it, it was a dead end, uninstallation pending)

**Comment by jtattermusch** [comment]
Ah stupid EnvInject:
`[EnvInject] - Loading node environment variables.` - despite the plugin not being used anywhere in the project!

**Comment by jtattermusch** [comment]
Scheduled restart of jenkins master. After the EnvInject plugin is uninstalled, thing shoud be fine.

**Comment by jtattermusch** [comment]
Jenkins restarted, mac builds seem to be fine again.
