### ISSUE TITLE
Provide centralized server authentication against metadata

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5615]
There's been a request that we provide hooks for this.

**Comment by jcanizales** [comment]
Can you explain briefly what does it mean? :)

**Comment by soltanmm** [comment]
Currently a user of gRPC Python must, per service method, write some code to accept/reject the call based on the initial metadata. Someone's requested a server-side hook to intercept requests in one place per server.

Whether or not we actually do this, I'unno.
