### ISSUE TITLE
pre_build_node.sh failure on for dbg configuration on macos

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5621]
`FAILED: tools/run_tests/pre_build_node.sh [ret=3, pid=1855]`

I've seen this several times, it seems to always happen on mac, with dbg configuration.

https://grpc-testing.appspot.com/job/gRPC_master/15614/config=dbg,language=node,platform=macos/console

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/15617/config=dbg,language=node,platform=macos/console

**Comment by murgatroid99** [comment]
It looks like this was caused by mac_node_4 not having Node 0.12 installed in nvm. I have installed it there, so this should no longer happen.
