### ISSUE TITLE
segfault in client side CompletionQueue.Next() function in async multi-threaded mode

### ISSUE THREAD

**Issue by zhengcai** [grpc/grpc#5634]
Hi All,

In our project(using release 0.11.0), because we need asynchronous gRPC calls, we are designing our threading model in this way:

One polling thread that dispatches results from completion queue:

```
while(true) {
  void *tag = 0;
  bool ok = false;
  completion_queue.Next(&tag, &ok);
  // Dispatch the callback function in tag.
  ...
}
```

Other worker threads that initiate gRPC calls:
```
client_context = std::make_shared<grpc::ClientContext>();
status = std::make_shared<grpc::Status>();
std::unique_ptr<grpc::ClientAsyncResponseReader<ResultTypeName>>
  rpc(stub->AsyncCallName(client_context.get(), request, params_.cq));
rpc->Finish(&result, status.get(), reinterpret_cast<void *>(callback));
```

Then the code sometimes crashes with segfault in "completion_queue.Next(&tag, &ok);". Since the failure is intermittent, my guess is that it is related to multi-threading. However, even after I protect the critical lines (completion_queue.Next(), creation of "rpc", and rpc->Finish()) in bold with a semaphore, the failure still happens.

So I was just wondering, is there anything that we did wrong that could cause the segfault? If so, how should we fix the issue?

Thanks a lot in advance.

PS:

I am also attaching the core stack for the segfault, just in case it might help:

#0  0x00007ffcfc6bbad0 in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) () from /.../software/toolchain/x86_64-linux/2.7/lib/libgrpc++.so.0
#1  0x00007ffcfc93cbdc in Next (this=0x1bdd620, tag=<optimized out>, ok=<optimized out>) at /.../software/toolchain/x86_64-linux/2.7/usr/include/grpc++/completion_queue.h:127
#2  GrpcMessageManager::PollingLoop (this=0x1bdd618) at /.../grpc_message_manager.cc:73

**Comment by vjpai** [comment]
Can you mention the grpc version number that you are using? There was a
previously-discovered issue about this in grpc 0.12 and below (
https://github.com/grpc/grpc/issues/5263) but it has been resolved since
then.
Regards,
Vijay

**Comment by zhengcai** [comment]
We are using 0.11.0. I will try to upgrade to 0.13.0 to see whether this problem still occurs, and update here.

Thanks a lot for the help

**Comment by zhengcai** [comment]
Great, upgrading to 0.13.0 fixed this issue. Thanks a lot for the help!
