### ISSUE TITLE
get stuck in python app like iPython

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#5640]
Hi

#### PROBLEM 1

If I write code like this below:

```python
class SomeClient(object):
    def __init__(self):
        # get host port from config
        r = dsnparse.parse(GRPC_DSN)
        self.host = r.host
        self.port = r.port
        self.channel = implementations.insecure_channel(self.host, self.port)
        self.stub = jedi_pb2.beta_create_SomeService_stub(self.channel)

    def touch(self):
        request = some_pb2.Empty()
        response = self.stub.Touch(request, _TIMEOUT_SECONDS)
        return response
```

And if I run this class in iPython or something, It will get stuck, and could not exit.

```python
client = SomeClient()
client.touch()
```

But If I do like this, it will not get stuck.

```python
client = SomeClient()
client.touch()
del client
```

So I have to import `atexit`, and add client to a global list. Before my app exit, I have to del client objects. This may work.

#### Problem 2

**BUT**

If I subscribe a channel like this:

 ```python
channel = implementations.insecure_channel(self.host, self.port)
channel.subscribe(callback, try_to_connect=True)
```

Registed atexit function will not be called. and app will be stuck also.

Because here [grpc/beta/_connectivity_channel.py](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/_connectivity_channel.py#L129), we using multi thread then atexit will not called, so, will get stuck.

**AND**

If the program closed by signal, atexit will not be called also.

SO, how to fix that problem?

THANKS SO MUCH!

**Comment by alamaison** [comment]
We've noticed this too.  Using the stub in a context manager makes the problem go away in 0.12.  I.e.
```
with jedi_pb2.beta_create_SomeService_stub(self.channel) as stub:
    request = some_pb2.Empty()
    response = self.stub.Touch(request, _TIMEOUT_SECONDS)
```

**Comment by GuoJing** [comment]
@alamaison thanks so much, but looks like subscribe a channel still have the problem. I think the problem comes from the `channel`, not stub. looks like stub is a simple wrapper. (anyway I'm not really sure for that)

I change the code like you said, still same problem.

```
D0308 21:01:27.089218000 140735146815488 iomgr.c:96] Waiting for 1 iomgr objects to be destroyed
D0308 21:01:28.112088000 140735146815488 iomgr.c:96] Waiting for 1 iomgr objects to be destroyed
D0308 21:01:29.141451000 140735146815488 iomgr.c:96] Waiting for 1 iomgr objects to be destroyed
D0308 21:01:30.167761000 140735146815488 iomgr.c:96] Waiting for 1 iomgr objects to be destroyed
D0308 21:01:31.198725000 140735146815488 iomgr.c:96] Waiting for 1 iomgr objects to be destroyed
D0308 21:01:36.104577000 140735146815488 iomgr.c:114] Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0308 21:01:36.104618000 140735146815488 iomgr.c:77] LEAKED OBJECT: tcp-client:ipv4:0.0.0.0:50051 fd=8 0x7fb57ac42db8
D0308 21:01:36.104659000 140735146815488 metadata.c:228] WARNING: 1 metadata elements were leaked
D0308 21:01:36.104670000 140735146815488 metadata.c:228] WARNING: 3 metadata elements were leaked
D0308 21:01:36.104679000 140735146815488 metadata.c:228] WARNING: 1 metadata elements were leaked
D0308 21:01:36.104688000 140735146815488 metadata.c:228] WARNING: 1 metadata elements were leaked
```

**Comment by alamaison** [comment]
We also see code refuse to exit if subscribing to a channel.  Unfortunately I don't know a solution yet.

**Comment by alamaison** [comment]
I've found a solution that works for us.  Our callback contained a reference to an object that contained a reference to the channel.  I.e. a circular reference.   gRPC objects aren't garbage-collected because they override `__del__` (see #5644) so this prevents either the channel or the callback being destroyed.  I guess this does something like keeping the polling thread alive and therefore the process never exits.

The solution was, as suggested in #5644, to use a Python weakref.  Then channel.unsubscribe() really works.

**Comment by GuoJing** [comment]
@alamaison hi, I tried weakref(channel) but not working, could you show me the code? many thanks!

**Comment by alamaison** [comment]
I don't have the code in front of me but it would look something like this:
```python
import weakref

def callback(weak_self, connectivity):
    self = weak_self()
    if self:
        self.do_something_to_react_to_callback()

class ChannelUser(object):
    def __init__(self):
        self._channel = <create channel>
        weak_self = weakref.ref(self)
        self._callback = lambda connectivity: callback(weak_self, connectivity)
        self._channel.subscribe(self._callback)

    def __del__(self):
        self._channel.unsubscribe(self._callback)
```

The important points are:

- The exact same callback function instance must be used in `unsubscribe`, so keep a reference to the closure you make from the callback function
- The callback function must _not_ be a method of an object that has a channel reference (directly or transitively).  Methods have a strong reference to self, even if they don't use it.
- The weak ref must be constructed _outside_ the closure so that only the weak reference id captured, not `self`

**Comment by GuoJing** [comment]
@alamaison Hi thanks, let me try, thank you very much.

**Comment by GuoJing** [comment]
@alamaison 

Hi I found we are not the same problem, **Problem 1**, I'm not using subscribe and unsubscribe, I'm just write a simple code -> A wrapped channel Class. It get stuck.

**Problem 2**, Channel subscribe will create a new thread, and if they overwrite `__del__`, then you don't delete the object, this thread will not close, I think maybe.. this is why the application stuck.. waiting for thread stop.

**Comment by nathanielmanistaatgoogle** [comment]
**Problem 1**: I'm aware of it and have changes planned to fix it.

**Problem 2**: When do you call `unsubscribe`?

**Comment by GuoJing** [comment]
@nathanielmanistaatgoogle 

hi ! Thanks for reply !

I don't know when to unsubscribe, right now, I have two function called 'connect' and 'shutdown' in wrapper Class. Connect is to create channel and subscribe it. Shutdown is del channel and unsubscribe. 

But is not working. Shutdown is registed to atexit. If program exit, shutdown will be called. 

Subscribe will create new thread so atexit is not working. Right now I'm not using subscribe and unsubscribe.

**Comment by nathanielmanistaatgoogle** [comment]
@GuoJing: in the last few weeks we've made several fixes to object lifecycle. Are you still seeing the problems you've described here? Would you be able to write a unit test that replicates your problems and fails against source control master?

**Comment by GuoJing** [comment]
hi

sorry. I have a quick test here and after install the code from master I got the error:

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from r2d2.grpc.entrypoint import create_app
  File "entrypoint.py", line 7, in <module>
    from grpc.beta import implementations
  File "lib/python2.7/site-packages/grpc/beta/implementations.py", line 39, in <module>
    from grpc import _auth
  File "lib/python2.7/site-packages/grpc/_auth.py", line 43, in <module>
    class GoogleCallCredentials(grpc.AuthMetadataPlugin):
AttributeError: 'module' object has no attribute 'AuthMetadataPlugin'

GuoJing
-----------------------------
http://guojing.me <http://guojing.me/> 
The one who love coding.
--> ret <--
echo null
rm -rf /

**Comment by nathanielmanistaatgoogle** [comment]
@GuoJing: [that's something else and it's not good; our apologies for the obstacle](https://github.com/grpc/grpc/issues/6935).

**Comment by nathanielmanistaatgoogle** [comment]
@GuoJing: how about now? Does this issue still describe an active problem for you?

**Comment by nathanielmanistaatgoogle** [comment]
Closing; this appears to no longer track an active defect. (@GuoJing: let me know if I'm mistaken?)
