### ISSUE TITLE
generated python code not compatible with python3

### ISSUE THREAD

**Issue by leifurhauks** [grpc/grpc#5654]
The code generated by `grpc_python_plugin` uses the python2 `__metaclass__` syntax which is not compatible with python3.

**Comment by leifurhauks** [comment]
One possibility could be to use `six.with_metaclass(abc.ABCMeta)`; however that would mean importing the external package `six` in the pb2 files. If that's not an option, we could write our own helper function that creates stubs and servicers with the `ABCMeta` metaclass.

**Comment by nathanielmanistaatgoogle** [comment]
I'm a fan of orthodoxy and staying on the beaten path; I think what's emerged as the de facto consensus for writing 2/3 code is `import`ing `six` in modules that need it. That these particular modules that need it are generated doesn't strike me as a reason to change that.

**Comment by leifurhauks** [comment]
Sounds good to me. I'll make the change in the morning.
Le 2016-03-10 22:27, "Nathaniel Manista" <notifications@github.com> a
écrit :

**Comment by leifurhauks** [comment]
This should be resolved by #5657
