### ISSUE TITLE
Doc Fixit: src/cpp/README need more information

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#5661]
[src/cpp/README.md](https://github.com/grpc/grpc/tree/master/src/cpp) needs more information, e.g. pre-requisites, installation, compile from source, protoc plugins, etc.

**Comment by stanley-cheung** [comment]
* We probably need a "Compile from Source" section like https://github.com/grpc/grpc/blob/master/INSTALL.md, because the instructions for the base directory also applies here for C++
 * We probably need a section for the protoc protobuf compiler like https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld#generating-grpc-code

Yes this will be a duplicate of information but I think it's better than leaving this doc mostly empty

**Comment by stanley-cheung** [comment]
@LisaFC Any advice here?

**Comment by LisaFC** [comment]
Yes, adding some more info seems helpful (even though it's currently essentially the same as the base install/will duplicate contents). I can try putting something together if you like?

**Comment by y-zeng** [comment]
There's an issue #5469 about installing protoc. I'm not sure if it will be resolved soon (after the official release of protobuf comes to 3.0.0). Should we mention it in this file and https://github.com/grpc/grpc/blob/master/INSTALL.md ?

**Comment by stanley-cheung** [comment]
No need.
