### ISSUE TITLE
c core destroy stream: chttp2_transport.c exception server stream 295 still included in list 4

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#5675]
hi

I'm testing the performance and pressure of gRPC server, if I have 2 process with each 500 thread, server will raise a exception and abort.

I look into the code looks like get something wrong when destroy stream...

[https://github.com/grpc/grpc/blob/master/src/core/transport/chttp2_transport.c#L540](https://github.com/grpc/grpc/blob/master/src/core/transport/chttp2_transport.c#L540)

My exception code is:

**chttp2_transport.c exception server stream 295 still included in list 4**

How could it be?

My service will abort immediately, this is not good.

**Comment by ctiller** [comment]
Which version of grpc are you testing against?

**Comment by GuoJing** [comment]
@ctiller grpcio 0.13.0

**Comment by ctiller** [comment]
I think it's fixed on master. We'll likely wrap that up into a 13.1 soon.

**Comment by GuoJing** [comment]
@ctiller ok thanks, this is important, we are going to release.

**Comment by dekumar23** [comment]
I am seeing the same issue with v1.0.0, 
17483 chttp2_transport.c:527]     client stream 1 still included in list 9
23334 chttp2_transport.c:527]     client stream 1 still included in list 9
