### ISSUE TITLE
Enable treating warnings as errors in our tests.

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5684]
So we can have the test fail when warnings we're interested in occur. E.g. https://github.com/grpc/grpc/issues/5683

We'll need to disable it for the warnings in our dependencies (Protobuf and BoringSSL).

**Comment by hsaliak** [comment]
Removed from 5/21 milestone during objc triage. @nicolasnoble let me or @jayantkolhe know if there's any issues.

**Comment by makdharma** [comment]
@jcanizales - what is the list of warnings you are interested in?

**Comment by jcanizales** [comment]
I rather enable erroring for all warnings, and disable the checks we decide not to care about. Otherwise we'll need to play catch-up with the compilers adding new checks we do care about.

**Comment by makdharma** [comment]
@y-zeng Please modify the Tests.xcodeproj to treat warnings as errors and disable specific ones that are failing.

**Comment by y-zeng** [comment]
Enabled in #6922

**Comment by makdharma** [comment]
@y-zeng Please wait for the PR to merge before closing.

**Comment by jcanizales** [comment]
And actually one can just forget about closing issues if the PR description says something like "Fixes #number" or "Closes #number" :)

**Comment by y-zeng** [comment]
Thanks for the reminder! The PR has been merged.
