### ISSUE TITLE
Investigate Cython linetracing causing segfaults

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5689]
Currently enabling linetracing causes segfaults in Cython code when creating and destroying objects in parallel.

**Comment by soltanmm** [comment]
This doesn't need to be prioritized; it's only useful for measuring code coverage and end-users will never, ever see this enabled unless they know **exactly** what they're doing.

**Comment by mehrdada** [comment]
Not sure if there's anything here that's not captured by #6894. Closing
