### ISSUE TITLE
Service implementation catches all exceptions (python)

### ISSUE THREAD

**Issue by bluecmd** [grpc/grpc#5695]
Using gRPC python I had something like:
```
class MyServer(pb.MyService):
  def MyMethod(self, request, context):
    some_method_that_raised_an_exception()
    return pb.MyReply()
```
The output of the server is completely blank, the client reports a remote error.

I'm not able to provide exact output right now, but it should be easy enough to reproduce.

**Comment by nathanielmanistaatgoogle** [comment]
I believe this is fixed as of the integration of [pull request 6787](https://github.com/grpc/grpc/pull/6787) - please reopen if I'm mistaken?
