### ISSUE TITLE
Load default roots.pem in Node via grpc_set_ssl_roots_override_callback

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5709]
This is required to not depend on user manually setting GRPC_DEFAULT_SSL_ROOTS_FILE_PATH env variable to get access to default roots. See https://github.com/grpc/grpc/issues/4834

C# implementation (for reference)
https://github.com/grpc/grpc/pull/5011

**Comment by jtattermusch** [comment]
After this is implemented, the `make install-certs` should be removed:
https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_interop_node/build_interop.sh#L44

**Comment by murgatroid99** [comment]
That `make install-certs` already doesn't need to be there. It doesn't use the installed certs anyway.

**Comment by jtattermusch** [comment]
What does it use then?

**Comment by murgatroid99** [comment]
The certs are distributed in the package, and GRPC_DEFAULT_SSL_ROOTS_FILE_PATH points at them.

**Comment by jtattermusch** [comment]
Alright, we shouldn't use GRPC_DEFAULT_SSL_ROOTS_FILE_PATH in the interop test. We should test the functionality to load default roots via grpc_set_ssl_roots_override_callback instead (as in real life, users shouldn't need to be required to the the environment variable, it's clumsy and error prone.

**Comment by jtattermusch** [comment]
Ah, I see what the trick is:
https://github.com/grpc/grpc/blob/1fd052f43c6d12fa451309264dc7fec2e4faccd7/src/node/index.js#L41

I guess that would do for now, but eventually we do the the right thing and use grpc_set_ssl_roots_override_callback.

**Comment by murgatroid99** [comment]
Right, I don't disagree with this change. The Dockerfile change just doesn't depend on this one.

**Comment by jtattermusch** [comment]
Understood.
