### ISSUE TITLE
Load default roots.pem in Ruby via grpc_set_ssl_roots_override_callback

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5710]
This is required to not depend on user manually setting GRPC_DEFAULT_SSL_ROOTS_FILE_PATH env variable to get access to default roots. See #4834

C# implementation (for reference)
#5011

**Comment by jtattermusch** [comment]
After this is implemented, the `make install-certs` should be removed:
https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_interop_ruby/build_interop.sh#L43

**Comment by murgatroid99** [comment]
That `make install-certs` already doesn't need to be there. It doesn't use the installed certs anyway.

**Comment by murgatroid99** [comment]
Fixes by #6351.
