### ISSUE TITLE
Load default roots.pem in PHP via grpc_set_ssl_roots_override_callback

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5711]
This is required to not depend on user manually setting GRPC_DEFAULT_SSL_ROOTS_FILE_PATH env variable to get access to default roots. See #4834

C# implementation (for reference)
#5011

**Comment by jtattermusch** [comment]
After this is implemented, the `make install-certs` should be removed:
https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_interop_php/build_interop.sh#L43

**Comment by stanley-cheung** [comment]
Can close this?
