### ISSUE TITLE
(dbg, c, windows) failure: tests.vsprojects/Debug/h2_proxy_nosec_test.exe disappearing_server

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5714]
```
E0311 14:04:14.080000000  6844 disappearing_server.c:174] assertion failed: status == GRPC_STATUS_UNIMPLEMENTED
D0311 14:04:14.081000000  6844 test_config.c:73] Abort handler called.
```

https://grpc-testing.appspot.com/job/gRPC_master/15723/config=dbg,language=c,platform=windows/testReport/junit/(root)/tests/vsprojects_Debug_h2_proxy_nosec_test_exe_disappearing_server/

**Comment by jtattermusch** [comment]
Same for h2_full_test 

https://grpc-testing.appspot.com/job/gRPC_portability_master/916/language=c,scenario=windows_x86_vs2013/testReport/junit/(root)/tests/vsprojects_Debug_h2_full_test_exe_disappearing_server/

**Comment by murgatroid99** [comment]
Seen again at https://grpc-testing.appspot.com/job/gRPC_master/15931/config=opt,language=c,platform=windows/testReport/junit/(root)/tests/vsprojects_Release_h2_proxy_nosec_test_exe_disappearing_server/
