### ISSUE TITLE
Common Ruby Errors

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#5721]
We have a large number of acceptance tests that run against live Google Cloud services, using service account credentials. The tests take on average 10 minutes to run. We have seen many errors using GRPC/protobuf in this environment. 

When we create a new protobuf service (e.g. Pub/Sub Publisher or Subscriber) for every api call, the tests will run for a few minutes, but it is very common for an getaddrinfo error to be raised from within grpc causing the tests to hang.

```
E0311 10:06:34.633032000 123145306050560 resolve_address_posix.c:126] getaddrinfo: nodename nor servname provided, or not known
```

When we don't create a new protobuf service for every api call, but instead memoize the protobuf service, we can run our acceptance Pub/Sub tests to completion. However, when we run all the acceptance tests for all the services, we will eventually see a "Getting metadata from plugin failed with error" error.

```
E0310 09:04:41.211931000 123145303392256 credentials.c:1155] Getting metadata from plugin failed with error: NoMethodError
E0310 09:04:41.211990000 123145303392256 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get meta
```

This metadata error is because the `updater_proc` object the ruby code gives to `GRPC::Core::CallCredentials` to sign the HTTP request is being replaced with a different object that doesn't have the `call` method. So the NoMethodError happens because new object (that is not the `updater_proc` object) does not have the `call` method. This behavior is very surprising. The objects we've been able to observe that have replaced our `updater_proc` object are the strings "DATASTORE_BACKUP" and "path". Both those strings are in our code, but nowhere near the proximity of any GRPC calls. I've looked extensively into this but have not yet found where this object is being replaced.

We are also increasingly seeing a "goaway" error. Sometimes this error will even create a segfault. The goaway error looks to be originating from the server. When this happens in our acceptance tests hang indefinitely, similar to the getaddrinfo error.

```
D0311 12:01:56.431449000 140735138045952 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
```

These issues are becoming a real blocker for us adding GRPC as a dependency.

/cc @jgeewax @quartzmo

**Comment by jcanizales** [comment]
I have the suspicion https://github.com/grpc/grpc/pull/5718 will solve this.

**Comment by blowmage** [comment]
I pulled the branch and run our acceptance tests multiple times, but now they are hung on the following error, repeated every 15 seconds:

```
E0311 15:52:24.737155000 123145306050560 resolve_address_posix.c:126] getaddrinfo: nodename nor servname provided, or not known
D0311 15:52:24.737179000 123145306050560 dns_resolver.c:189] dns resolution failed: retrying in 15 seconds
```

**Comment by ctiller** [comment]
That's ... not promising. What host name are you passing in?

**Comment by blowmage** [comment]
We are setting the hosts "pubsub.googleapis.com" and "logging.googleapis.com". But I wonder if the same bug that is swapping out the updater_proc object is also swapping out the host object. I'll try to add some debugging statements to the code and retry tonight.

**Comment by blowmage** [comment]
I've reproduced several times and grpc is trying to resolve "pubsub.googleapis.com" when the errors start, so the host value is not changing.

**Comment by blowmage** [comment]
I do suspect that the issue with the `updater_proc` object might have something to do with ruby's GC and the location of the object being moved in memory. That issue doesn't show up when we create a new service and `updater_proc` object for every API request made. But it does when we when we hold on to those object for several minutes, enough time for the GC to sweep marked objects and consolidate memory. I'll continue trying to verify if this is the case or not.

**Comment by blowmage** [comment]
I am certain that I can prove that the issue with the `updater_proc` on long running ruby processes is because the location of the proc object is moved during GC, and GRPC is holding on to the pointer to the original location. The actual ruby error is swallowed by GRPC, and a `GRPC::BadStatus` error with code 16 is raised instead. This happens in `src/ruby/ext/grpc/rb_call_credentials.c`, where the `updater_proc` object is called.

The original rescue function is:

```c
static VALUE grpc_rb_call_credentials_callback_rescue(VALUE args,
                                                      VALUE exception_object) {
  VALUE result = rb_hash_new();
  (void)args;
  rb_hash_aset(result, rb_str_new2("metadata"), Qnil);
  /* Currently only gives the exception class name. It should be possible get
     more details */
  rb_hash_aset(result, rb_str_new2("status"),
               INT2NUM(GRPC_STATUS_PERMISSION_DENIED));
  rb_hash_aset(result, rb_str_new2("details"),
               rb_str_new2(rb_obj_classname(exception_object)));
  return result;
}
```

Of we change the code to print the error object as a string instead of showing the error object's class, we will show the object that we are invoking the `call` method on:

```c
static VALUE grpc_rb_call_credentials_callback_rescue(VALUE args,
                                                      VALUE exception_object) {
  VALUE result = rb_hash_new();
  (void)args;
  rb_hash_aset(result, rb_str_new2("metadata"), Qnil);
  /* Currently only gives the exception class name. It should be possible get
     more details */
  rb_hash_aset(result, rb_str_new2("status"),
               INT2NUM(GRPC_STATUS_PERMISSION_DENIED));
  rb_hash_aset(result, rb_str_new2("details"),
               rb_funcall(exception_object, rb_intern("to_s"), 0));
  return result;
}
```

With that change we will see the object we are trying to invoke. The original debugging message printed to stdout shows only that a NoMethodError was raised:

```
E0313 15:11:08.914634000 123145303392256 credentials.c:1162] Getting metadata from plugin failed with error: NoMethodError
E0313 15:11:08.914648000 123145303392256 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.
```

But with the change the new debugging messages are show what object raised the NoMethodError. Here are some of the messages I've gotten:

```
E0311 11:33:36.352378000 123145303392256 credentials.c:1155] Getting metadata from plugin failed with error: undefined method `call' for ["Content-Type", "application/x-protobuf"]:Array
E0311 11:33:36.352391000 123145303392256 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.

E0313 15:18:01.248642000 123145303392256 credentials.c:1162] Getting metadata from plugin failed with error: undefined method `call' for "int32":String
E0313 15:18:01.248665000 123145303392256 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.

E0313 17:48:06.941755000 123145303392256 credentials.c:1162] Getting metadata from plugin failed with error: undefined method `call' for #<HTTP::CookieJar:0x007feb84330e88>
E0313 17:48:06.941769000 123145303392256 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.


E0313 17:59:42.872134000 123145303392256 credentials.c:1162] Getting metadata from plugin failed with error: undefined method `call' for "selfLink":String
E0313 17:59:42.872146000 123145303392256 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.
```

This establishes that the object is changed, but it doesn't prove that the GC is the cause of the change. To prove that I've run our tests a couple dozen times, the first dozen unchanged, and the second dozen with the following code added:

```ruby
GC.disable
```

The first dozen consumes ~225 MB of memory while the tests are run, and spikes up to ~300 MB during the cleanup process post-tests, and the second dozen consumes ~425 MB of memory while the tests are run, and spikes up to ~600 MB during the cleanup process post-tests. Every single run of the first dozen failed with several "Getting metadata from plugin failed with error" messages printed and GRPC::BadStatus errors (with a code of 16) raised. Some even raised a segfault during the post-test cleanup. And every single run of the second dozen with `GC.disable` passed without any messages printed or any errors raised or segfaults.

**Comment by blowmage** [comment]
Also, I ran my tests against the master branch, because the 0.13.0 release was causing too many other problems. The `goaway` errors I mentioned in the issue description still happens, but it properly raises a GRPC::BadStatus error with code 14 now. So on master the goaway error no longer blocks indefinitely, which is super great. :+1:

I have also not seen a `getaddrinfo` error since switching to the master branch. Double :+1:

**Comment by murgatroid99** [comment]
I opened https://github.com/grpc/grpc/pull/5744, can you verify that this
fixes the problem?

**Comment by blowmage** [comment]
@murgatroid99 Thank you for the PR! Moving the discussion there.
