### ISSUE TITLE
Node test doesn't have code coverage report

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#5760]
https://grpc-testing.appspot.com/job/gRPC_coverage/3850/HTML_Report/
Click on Node Coverage. It's an empty page.

**Comment by murgatroid99** [comment]
It looks like the index page for the node coverage report has the content

```html
<html><head><meta http-equiv="refresh" content="0;URL=lcov-report/index.html"></head></html>
```

And that correctly redirects when I access the file on my local machine, but not when I access it on Jeknins.
