### ISSUE TITLE
Proposal: allow Python service-side application functions to raise an exception containing a Future instead of returning?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5762]
@leifurhauks is running into problems with the fact that on the server an entire thread is consumed for the duration of the execution of an application function even if the application function spends most of its execution in a `return my_future.result()` statement.

On [Gitter](https://gitter.im/grpc/grpc) I wrote: _But... it doesn't take too much imagination to conceive of an exception class that could be raised, so that server-side-code can be written as `raise ResponseFuture(my_response_future)` which would return from the application function early in the lifetime of the RPC, thus returning the thread..._

**Comment by nathanielmanistaatgoogle** [comment]
If [a new API using `async` and `await`](https://github.com/grpc/grpc/issues/6046) were added, would this feature request be entirely unnecessary?

**Comment by leifurhauks** [comment]
I believe so, yes!

**Comment by mehrdada** [comment]
I don't find this actionable anytime soon given the current status of gRPC Python API. Perhaps future support of asyncio will help resolve the underlying matter. Closing.
