### ISSUE TITLE
windows_x86_vs2013: tests.vsprojects/Debug/h2_proxy_test.exe disappearing_server

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5773]
https://grpc-testing.appspot.com/job/gRPC_portability_master/915/language=c,scenario=windows_x86_vs2013/testReport/junit/(root)/tests/vsprojects_Debug_h2_proxy_test_exe_disappearing_server/

```
D0316 02:05:22.020000000  8584 test_config.c:159] test slowdown: machine=1.000000 build=1.000000 total=1.000000
D0316 02:05:22.027000000  8584 proxy.c:104] PROXY ADDR:localhost:2129 BACKEND:localhost:2130
I0316 02:05:22.036000000  8584 disappearing_server.c:194] disappearing_server_test/chttp2/fullstack+proxy
D0316 02:05:22.048000000  5356 chttp2_transport.c:698] got goaway [0]: 53 65 72 76 65 72 20 73 68 75 74 64 6f 77 6e 'Server shutdown'
E0316 02:05:22.060000000  5356 tcp_windows.c:311] WSASend error: An established connection was aborted by the software in your host machine.


E0316 02:05:22.060000000  5356 tcp_windows.c:152] ReadFile overlapped error: An established connection was aborted by the software in your host machine.


E0316 02:05:22.060000000  8584 disappearing_server.c:174] assertion failed: status == GRPC_STATUS_UNIMPLEMENTED
D0316 02:05:22.060000000  8584 test_config.c:73] Abort handler called.
```

**Comment by jtattermusch** [comment]
Again here: https://grpc-testing.appspot.com/job/gRPC_portability_master/923/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_proxy_test_exe_disappearing_server/

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_portability_master/925/language=c,scenario=windows_x86_vs2013/testReport/junit/(root)/tests/vsprojects_Debug_h2_proxy_test_exe_disappearing_server/

**Comment by jtattermusch** [comment]
Looks like there's a the same flake for h2_census_test https://grpc-testing.appspot.com/job/gRPC_portability_master/929/language=c,scenario=windows_x86_vs2015/testReport/junit/(root)/tests/vsprojects_Debug_h2_census_test_exe_disappearing_server/

**Comment by jtattermusch** [comment]
And a same thing for h2_full_test https://grpc-testing.appspot.com/job/gRPC_portability_master/932/language=c,scenario=windows_x86_vs2013/testReport/junit/(root)/tests/vsprojects_Debug_h2_full_test_exe_disappearing_server/

**Comment by jcanizales** [comment]
Again today: https://grpc-testing.appspot.com/job/gRPC_master/15856/config=dbg,language=c,platform=windows/testReport/junit/(root)/tests/vsprojects_Debug_h2_proxy_nosec_test_exe_disappearing_server/

**Comment by jcanizales** [comment]
And on interop tests too https://grpc-testing.appspot.com/job/gRPC_portability_master/938/language=c,scenario=windows_x86_vs2013/testReport/junit/(root)/tests/vsprojects_Debug_h2_full_test_exe_disappearing_server/

**Comment by murgatroid99** [comment]
Again: https://grpc-testing.appspot.com/job/gRPC_portability_master/1035/language=c,scenario=windows_x86_vs2013/testReport/junit/(root)/tests/vsprojects_Debug_h2_proxy_test_exe_disappearing_server/
