### ISSUE TITLE
windows_x64_vs2015: tests.vsprojects/x64/Debug/h2_proxy_nosec_test.exe binary_metadata

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5777]
```
D0316 11:07:52.904000000 12180 test_config.c:159] test slowdown: machine=1.000000 build=1.000000 total=1.000000
I0316 11:07:52.905000000 12180 binary_metadata.c:55] test_request_response_with_metadata_and_payload/chttp2/fullstack+proxy
D0316 11:07:58.283000000 12180 proxy.c:104] PROXY ADDR:localhost:1900 BACKEND:localhost:1902
E0316 11:07:59.033000000 12180 cq_verifier.c:248] event not found: OP_COMPLETE: tag:0000000000000001 OK
E0316 11:07:59.033000000 12180 cq_verifier.c:251] have tags: 0000000000000065
D0316 11:07:59.033000000 12180 test_config.c:73] Abort handler called.
```

https://grpc-testing.appspot.com/job/gRPC_portability_master/924/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_proxy_nosec_test_exe_binary_metadata/

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_portability_master/933/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_proxy_nosec_test_exe_binary_metadata/

**Comment by jcanizales** [comment]
Again today: https://grpc-testing.appspot.com/job/gRPC_master/15871/config=dbg,language=c,platform=windows/testReport/junit/(root)/tests/vsprojects_Debug_h2_compress_nosec_test_exe_binary_metadata/

**Comment by murgatroid99** [comment]
And again https://grpc-testing.appspot.com/job/gRPC_portability_master/1000/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_proxy_nosec_test_exe_binary_metadata/

**Comment by nathanielmanistaatgoogle** [comment]
[Build 1126.](https://grpc-testing.appspot.com/job/gRPC_portability_master/1126/language=c,scenario=windows_x64_vs2015/consoleFull)
