### ISSUE TITLE
Investigate Python deadlocking on pipes

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5787]
This is a weird place to file the issue, as this is totally doable without any reference to gRPC... HOWEVER, I'm rate-limiting my investigation of this based on gRPC work, and I don't yet have enough information to file a bug against Python 3.x (where this issue would be most relevant if it still applies there), so, this is being filed _here for now_ until I get a chance to dive into trying to manufacture a minimal repro.

For details, see this commit's message: cd861aa755da2f2ef5b96af56382634cf4dc9267. Note that it requires some native code being on the stack if the offending thread is daemonic.

**Comment by soltanmm-google** [comment]
This doesn't matter anymore given changes in the testing infrastructure.
