### ISSUE TITLE
Currently published Nuget package ver 0.13.0 doesn't contain all the platform-specific binaries

### ISSUE THREAD

**Issue by ananthonline** [grpc/grpc#5789]
Currently published [Nuget package ver 0.13.0](https://www.nuget.org/packages/Grpc.Tools/0.13.0) doesn't contain all the platform-specific binaries, unlike the version of the nuspec in https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Google.Protobuf.nuspec

I'm contemplating providing a pull request for a Grpc.Tools nuget package that makes it easy to generate C# wrappers for grpc, but can't do so in a cross platform manner until this is pushed to nuget.org.

Is there a reason this is in, but not pushed yet?

**Comment by jtattermusch** [comment]
Nuget package 0.13.1-pre1  contains the precompiled protoc and grpc_csharp_plugin binaries for all supported platforms, if that is what you are asking about. (Google.Protobuf.nuspec only contains protoc.exe though, so I am not sure if that answers your question).

We will publish Grpc.Tools.0.13.1 soon.

**Comment by ananthonline** [comment]
Thanks, I hadn't tried the 0.13.1-pre1 package. If that has all the platform specific binaries (protoc + csharp plugin), I should be good to go. Thanks!

**Comment by jtattermusch** [comment]
FYI I just pushed 0.13.1 version of gRPC to nuget an hour ago.
