### ISSUE TITLE
Update Nuget package for C# to non pre-release status

### ISSUE THREAD

**Issue by ananthonline** [grpc/grpc#5796]
Are there plans to bump Grpc for C# to non pre-release status? If yes, when? Do we have any timelines for this?

Being conservative is fine, but this issue prevents prevents consumers from using Grpc Nuget packages in other packages due to [this](https://github.com/NuGet/Home/issues/1365) Nuget issue.

**Comment by ananthonline** [comment]
*bump* Is no one else trying to use the Grpc C# nuget packages for production?

**Comment by jtattermusch** [comment]
Yes, we will publish nuget packages for 0.13.1 as soon as we actually tag that release.

**Comment by jtattermusch** [comment]
(that should happen before the end of this week).

**Comment by ananthonline** [comment]
Awesome, exactly what I needed. I'll look forward to this!

**Comment by jtattermusch** [comment]
0.13.1 has been pushed!
