### ISSUE TITLE
Find and document the true minimum setuptools version required for Python gRPC installation

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5807]
Currently I think it's `>=19.4`, but it might be less than that.

**Comment by soltanmm** [comment]
`setuptools>=12.0.5` and `pip>=6.0.8` works. *Probably* not worth going any further back.

**Comment by vjpai** [comment]
Is this done?

**Comment by soltanmm** [comment]
I don't think we actually care about this; our known minima are sufficiently low AFAICT.
