### ISSUE TITLE
Specify global timeout for all methods of API

### ISSUE THREAD

**Issue by pavel-odintsov** [grpc/grpc#5825]
Hello!

I'm using gRPC with C++. I'm working with remote service and should care about timeouts.

So I have this in each method which calls remote API:
```bash
// Connection timeout in seconds
unsigned int client_connection_timeout = 5;

ClientContext context;

// Set timeout for API
std::chrono::system_clock::time_point deadline =
    std::chrono::system_clock::now() + std::chrono::seconds(client_connection_timeout);

context.set_deadline(deadline);
```

But actually I have about 50 method and I should put this code about set_deadline in this methods. That's actually boilerplate code and if I miss timeout on one place I could broke my app.

I suggest to have single timeout value for whole API class object which could be handled by all methods (or overriden with mentioned below method).

**Comment by vjpai** [comment]
I'm marking this one ready to close as this functionality can be created by putting an additional layer on top of our structs (like having a user-defined class that includes a ClientContext and sets a deadline as part of its initializer).
