### ISSUE TITLE
tests.bins/dbg/qps_openloop_test (dbg,c++,macos)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5833]
https://grpc-testing.appspot.com/job/gRPC_master/15884/config=dbg,language=c++,platform=macos/testReport/junit/(root)/tests/bins_dbg_qps_openloop_test/

Related to #3869?

**Comment by jtattermusch** [comment]
Are we seeing this after https://github.com/grpc/grpc/pull/5752?

**Comment by soltanmm** [comment]
@jtattermusch I don't think so. Then again, the PR's only been landed in master for about a few hours...

**Comment by vjpai** [comment]
Although reported now, this test took place before that merge. I'm tempted to close this unless we see otherwise.

**Comment by soltanmm** [comment]
Sounds okay to me.
