### ISSUE TITLE
(opt, c, linux) lb_policies_test failure

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5836]
I think we started seeing this from today on. It is possible we've introduced a new issue by merging some PR?

```
0x1ef2d60 (SC 0x1ef2830)
E0318 20:25:20.567119699    7202 tcp_client_posix.c:191]     failed to connect to 'ipv4:127.0.0.1:1124': timeout occurred
E0318 20:25:20.567206521    7202 tcp_client_posix.c:191]     failed to connect to 'ipv4:127.0.0.1:1100': timeout occurred
D0318 20:25:20.567707936    7202 lb_policies_test.c:310]     EVENT: success:1, type:2, tag:1001 iter:9
D0318 20:25:20.567785565    7202 lb_policies_test.c:355]     status=12; xyz
E0318 20:25:20.667502175    7202 tcp_client_posix.c:191]     failed to connect to 'ipv4:127.0.0.1:1124': timeout occurred
E0318 20:25:20.667653722    7202 tcp_client_posix.c:191]     failed to connect to 'ipv4:127.0.0.1:1100': timeout occurred
D0318 20:25:20.767955443    7202 lb_policies_test.c:790]     actual_connection_sequence: 0 -1 -1 1 0 1 0 1 0 1
D0318 20:25:20.768001918    7202 lb_policies_test.c:790]     seen_elements: 0 1 0 0
E0318 20:25:20.768010020    7202 lb_policies_test.c:833]     assertion failed: seen_elements[j] != 0
```

https://grpc-testing.appspot.com/job/gRPC_master/15898/config=opt,language=c,platform=linux/testReport/junit/(root)/tests/bins_opt_lb_policies_test/

**Comment by dgquintas** [comment]
Yeah, this is new. It must have been caused by a new merge...

**Comment by dgquintas** [comment]
I'm running a git bisect to find out which one...

**Comment by jtattermusch** [comment]
Great, thanks. Let's revert the bad guy!

**Comment by dgquintas** [comment]
The culprit:

commit 536fc539cc36be41a1db2d16458a00d2e5df1c55
Author: Craig Tiller <ctiller@google.com>
Date:   Fri Mar 11 12:36:56 2016 -0800

    Integrate backoff library with subchannel

**Comment by dgquintas** [comment]
Which makes sense, given how intertwined that is with load balancing...

**Comment by vjpai** [comment]
Also saw it on a dbg test today for a PR

**Comment by dgquintas** [comment]
All I have to say is, for anyone who didn't know about git bisect already, go read about it: https://git-scm.com/docs/git-bisect

**Comment by jtattermusch** [comment]
thanks @dgquintas  for quick action!
