### ISSUE TITLE
tests.vsprojects/x64/Debug/h2_census_nosec_test.exe binary_metadata (c,windows_x64_vs2015)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5839]
https://grpc-testing.appspot.com/job/gRPC_portability_master/974/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_census_nosec_test_exe_binary_metadata/

**Comment by nicolasnoble** [comment]
The build has disappeared from Jenkins since then. Please copy the relevant logs to the issue comments, or hit the "Keep this build forever" button on Jenkins.
