### ISSUE TITLE
tests.vsprojects/x64/Debug/h2_ssl_proxy_test.exe call_creds (c,windows_x64_vs2015)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5845]
https://grpc-testing.appspot.com/job/gRPC_portability_master/968/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_ssl_proxy_test_exe_call_creds/

**Comment by murgatroid99** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_portability_master/1000/language=c,scenario=windows_x64_vs2015/testReport/junit/(root)/tests/vsprojects_x64_Debug_h2_ssl_proxy_test_exe_call_creds/
