### ISSUE TITLE
Better documentation for payloads.proto

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5858]
Important for consistency of QpsWorker implementations in different languages.

https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/payloads.proto is pretty short on documentation, and some key questions are unanswered:
- does driver send req_size  to qps clients   or resp_size to qps server or does client receive both arguments and it is responsible for communicating the resp_size to the server?  That can be rather easily done for SimpleProtoParams (as resp_size is part of the simple request proto, so server can unpack that field and find out what response size to send).  How the same thing can be achieved for ByteBufferParams is unclear to me.  Also, if we rely on sending resp_size with each request, we can't really have a scenario where payload size = 0.   Based on looking at commands qps_driver is sending out, it looks like the req_size and resp_size are only sent to client.

See e.g. ServerConfig and ClientConfig for scenario 5:

```
ServerConfig: { "securityParams": { "useTestCa": true, "serverHostOverride": "foo.test.google.fr" }, "asyncServerThreads": 1, "coreLimit": 6, "coreList": [ 0, 1, 2, 3, 4, 5 ] }

ClientConfig: { "serverTargets": [ "localhost:49392" ], "securityParams": { "useTestCa": true, "serverHostOverride": "foo.test.google.fr" }, "outstandingRpcsPerChannel": 1, "clientChannels": 1, "asyncClientThreads": 1, "loadParams": { "closedLoop": { } }, "payloadConfig": { "simpleParams": { } }, "histogramParams": { "resolution": 0.01, "maxPossible": 60000000000 }, "coreList": [ 6, 7, 8, 9, 10, 11 ] }
```

**Comment by jtattermusch** [comment]
Also, let's talk, I'm a bit blocked by this.

**Comment by ctiller** [comment]
Important, but not GA blocking
