### ISSUE TITLE
Mac: tests.py.test._crust_over_core_over_links_face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5862]
https://grpc-testing.appspot.com/job/gRPC_master/15919/config=opt,language=python,platform=macos/testReport/junit/(root)/tests/py_test__crust_over_core_over_links_face_interface_test_MultiCallableInvokerBlockingInvocationInlineServiceTest/

**Comment by murgatroid99** [comment]
Also seen at https://grpc-testing.appspot.com/job/gRPC_master/15925/config=dbg,language=python,platform=macos/testReport/junit/(root)/tests/py_test__crust_over_core_over_links_face_interface_test_MultiCallableInvokerBlockingInvocationInlineServiceTest/

**Comment by stanley-cheung** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/16229/config=dbg,language=python,platform=macos/

**Comment by nathanielmanistaatgoogle** [comment]
Obviated by the integration of [pull request 6962](https://github.com/grpc/grpc/pull/6962).
