### ISSUE TITLE
linux_x64_gcc5.3: gpr_thd_test

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#5883]
https://grpc-testing.appspot.com/job/gRPC_portability_master/1022/language=c,scenario=linux_x64_gcc5.3/testReport/junit/(root)/tests/bins_dbg_gpr_thd_test/

**Comment by adelez** [comment]
This test has been green for a while: https://grpc-testing.appspot.com/job/gRPC_portability_master/language=c,scenario=linux_x64_gcc5.3/
