### ISSUE TITLE
Menu of improvements to benchmarking control APIs

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc#5919]
@vjpai 

This is a suggested set of improvements to the benchmarking control API:
- Any elapsed time value should be expressed in integer microseconds [minor]
- HistogramParams needs to document that the expected units are microseconds
- HistogramParams.resolution: probably does not need to be in the API, a resolution of 0.001 is almost certainly overkill for all expected cases. Just use a constant. Do we need HistogramParams at all?
- HistogramData all values should be integers unless we are measuring partial microseconds when recording data. If that is the case why not just switch everything over to integer nanoseconds
- SecurityParams.use_test_ca when would this value be false? Doc says to check for presence of SecurityParams to enable TLS. Are we expecting more options here going forward?
- SecurityParams.server_host_override if we're using test_ca, and we always are, then the host override is required and is a constant so it's not clear what value this adds
- The ServerType enum is C runtime specific. Consider having the driver choose variants 1-n and the server return a label identifying what the variant actually does. May need to add API to ask what variants the worker can support
- Need to implement more realistic compressable and uncompressable data. Suggest we share a common corpus that is compressable and have the uncomressable flavor just be the already compressed corpus.

**Comment by louiscryan** [comment]
... and

- PayloadConfig specifies bot the request and the response size but it is passed to both the client and the server workers

**Comment by murgatroid99** [comment]
Also, we need a specification for the generic benchmark service (the one that uses pure byte strings and is not defined in services.proto).

**Comment by louiscryan** [comment]
.... and

the driver should send a scenario name to the workers so they can tag it in their logs when errors occur. Will make debugging much easier

**Comment by louiscryan** [comment]
... and

the current histogram resolution mechanism might be hard to replicate in languages which don't support standard double precision math (ruby & js). It might be better to use something more like what 
https://github.com/HdrHistogram/HdrHistogram does or have the driver provide the bucketing distribution directly

**Comment by louiscryan** [comment]
... and 

Java will need a longer warmup phase and a pause to allow the JIT to kick in. Ideally this would be done by running the scenario, stopping it and the starting it again after a brief pause.

While it would be nice to think that we could wait for the mean latencies to stabilize before we start recording this would probably be unstable

**Comment by vjpai** [comment]
@jtattermusch please review this also when you get a chance

**Comment by vjpai** [comment]
In the driver, using the environment variable QPSWORKERS could get confusing over time, especially as we add heterogeneity to the machines.  The point is that right now we all remember that servers come first and then clients, but we might forget that in the future. We can continue to allow that, but also allow explicitly setting the names of the servers and clients (either as command line options or as 2 other environment variables).

**Comment by jtattermusch** [comment]
On Tue, Mar 22, 2016 at 2:39 PM, Louis Ryan <notifications@github.com>
wrote:

> @vjpai <https://github.com/vjpai>
>
> This is a suggested set of improvements to the benchmarking control API:
>
>    - Any elapsed time value should be expressed in integer microseconds
>    [minor]
>
> If I am not mistaken the same histogram the same histogram is used in C
core for profiling the code path. For that use case, microseconds don't
seem to be sufficient (some internal function call definitely take way less
than a microsecond).


>
>    - HistogramParams needs to document that the expected units are
>    microseconds
>    - HistogramParams.resolution: probably does not need to be in the API,
>    a resolution of 0.001 is almost certainly overkill for all expected cases.
>    Just use a constant. Do we need HistogramParams at all?
>
> I think having a constant that needs to be the same in 5+ languages and
making sure that it is the case is a bigger burden than qps driver simply
specifying what the histogram param is (regardless of the unit).


>
>    - HistogramData all values should be integers unless we are measuring
>    partial microseconds when recording data. If that is the case why not just
>    switch everything over to integer nanoseconds
>
>
As mentioned elsewhere integers nanoseconds can easily overflow for values
like sum_of_squares.

>
>    - SecurityParams.use_test_ca when would this value be false? Doc says
>    to check for presence of SecurityParams to enable TLS. Are we expecting
>    more options here going forward?
>
> This can be false if you want to enable secure connections, but you test
against real prod backends (which we want to do at some point, right?). But
agreed that this needs to be better documented).


>
>    - SecurityParams.server_host_override if we're using test_ca, and we
>    always are, then the host override is required and is a constant so it's
>    not clear what value this adds
>
> use_test_ca and server_host_override are params we are using for our
interop tests already and we are fairly happy with these, so why not stay
consistent - one advantage is that implementors will be already familiar
with these.

**Comment by jtattermusch** [comment]
On Fri, Mar 25, 2016 at 9:41 AM, Louis Ryan <notifications@github.com>
wrote:

> ... and
>
> the current histogram resolution mechanism might be hard to replicate in
> languages which don't support standard double precision math (ruby & js).
> It might be better to use something more like what
> https://github.com/HdrHistogram/HdrHistogram does or have the driver
> provide the bucketing distribution directly
>

What exactly is the problem with ruby & js?   They don't have an equivalent
of the double type of computing the bucket sizes is not easy?

**Comment by vjpai** [comment]
I have just wrapped the Ruby performance workers (everything except generic server). I can now confirm that Ruby uses double-precision floating point (and is specified to do so), so we can still kick the histogram issue down the can. This will become an issue for some language at some point, but Ruby at least uses the system's IEEE double-precision type.

**Comment by vjpai** [comment]
The JS documentation also says that objects of type Number are IEEE 64-bit FP. So no problem there either. Can, meet foot.

**Comment by vjpai** [comment]
Louis, can you point me to the corpus that you've been using?

**Comment by louiscryan** [comment]
Looks like were doing all zeros for compressable. For uncompressable we use 

https://github.com/grpc/grpc-java/tree/6e04c3100e143a5792bb98efb0d5a5755324bd7d/interop-testing/src/main/resources/io/grpc/testing/integration/testdata

**Comment by louiscryan** [comment]
... and the Java workers reject SYNC_CLIENT for streaming calls as we don't have APIs for this. The driver doesn't output the GRPC status message returned indicating that this is not supported making diagnosis harder. The driver should recognize UNIMPLEMENTED from the workers and log that the scenario is being intentionally skipped

**Comment by louiscryan** [comment]
After chatting with @ejona86 I suggest we use geo.protodata in

https://github.com/cockroachdb/c-snappy/tree/master/internal/testdata

Should be a reasonably representative dataset for any structured encoding

**Comment by vjpai** [comment]
We need to make the driver skip an UNIMPLEMENTED scenario response and also clean up the clients and servers appropriately. Will add.

**Comment by vjpai** [comment]
Folks, should we add any other language-specific fields to the enums before sticking in numbered variants?

**Comment by jtattermusch** [comment]
one more item to address: LoadParams.OfferedLoad comment should document the expected units (from the code it looks like that the exp distribution with given lambda generates time to next event in *nanoseconds* and that should be documented properly)

**Comment by vjpai** [comment]
Post-GA cleanup issue: Instead of giving the PayloadConfig to the servers to give the response_size to use in the generic case, we should make that part of the generic request sent from the client.

**Comment by vjpai** [comment]
For the QPS report, we currently use the total histogram count as the numerator and the average of the client wall clock times as the denominator. This is not really accurate. We should use the elapsed wall-clock time as seen at the driver from one mark to the next. This is a post-GA cleanup issue that should go in with the overall histogram cleanup.

**Comment by vjpai** [comment]
This has been implemented piecemeal over the past few years.
