### ISSUE TITLE
Incorrect code comment

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#5930]
https://github.com/grpc/grpc/blob/master/tools/buildgen/plugins/expand_version.py#L30

**Comment by yang-g** [comment]
Is this resolved?

**Comment by stanley-cheung** [comment]
No, the code comment refers to protos but this file is about versions, and has nothing to do with protos. Probably a copy/paste error but need to fix.

**Comment by stanley-cheung** [comment]
Seems like this incorrect comment was copied from the file `list_protos.py` in the same directory
