### ISSUE TITLE
node asan flaky failure

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5938]
[From the master build history. I'm not actually sure what parts of this log are the most illustrative.](https://grpc-testing.appspot.com/job/gRPC_master/config=asan,language=node,platform=linux/15595/consoleFull)

**Comment by murgatroid99** [comment]
This test was last run 18 days ago, and the failure was the same as #5294, which has since been fixed.

**Comment by nathanielmanistaatgoogle** [comment]
I hadn't noticed that all the log lines say "0305" as month and date indicators. Huh. How about that.

What's the process failure that has an old test run causing non-green-ness in fresh master test results? What's... supposed to happen here?

**Comment by murgatroid99** [comment]
If you look at any individual test run, the tooltip labels that test as "Unstable - Skipped" and it displays with a faded icon. It only still displays anything because we don't know how to make it no do that.

**Comment by nathanielmanistaatgoogle** [comment]
Right you are - the icon fading was subtle enough that I completely missed it.
