### ISSUE TITLE
Implement grpc_create_sockpair_if_unix  in unix_sockets_posix_noop.c

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#5946]
This is a followup of #5943 . For now this function is stubbed out with an assert. It should actually have an implementation of some kind if that is appropriate (such as creating a client->server socket requesting the server to create a server->client socket). It should  not be left empty as in #5755, as this was silently leaving the fd[] input uninitialized and could result in dependent functions doing bad stuff on random fd's.

**Comment by ncteisen** [comment]
Let's close until someone brings up the need for non `GRPC_HAVE_UNIX_SOCKET` environment
