### ISSUE TITLE
Manual copy needed when getting nuspec packages for the first time

### ISSUE THREAD

**Issue by ornatwork** [grpc/grpc#5952]
The user has to manually copy a file to be able to run after getting the grpc nuget packages .

To reproduce on Windows, follow the steps below

// Remove the grpc packages from 
C:\Users\\[username]\\.dnx\packages\

// Clone test project 
git clone https://github.com/ornatwork/HelloWorldTest.git

// Update packages 
cd HelloWorldTest
dnu restore 

// Run the UnitTests
cd test
cd HelloWorldTest.Test
dnx test 

Tests fail with error about the dll that is not in the right location  
```
System.IO.FileNotFoundException: Error loading native library. File does not exist. 
File name: 'C:\Users\[user]\.dnx\packages\Grpc.Core\0.13.0\lib\net45\nativelibs\windows_x86\grpc_csharp_ext.dll'

```

// Manual copy, by running nant script
nant

// Run the tests again
dnx test 

Tests run fine after the copy step has been run

**Comment by jtattermusch** [comment]
So we don't support DNX yet (but we are working on that). What you are reporting looks as a duplicate  https://github.com/grpc/grpc/issues/4872, so closing this one.
