### ISSUE TITLE
patch location is gone.

### ISSUE THREAD

**Issue by eraye1** [grpc/grpc#5956]
Demos-MacBook-Pro:dns-lookups-microservice user$ brew install grpc
==> Installing grpc from grpc/grpc
==> Installing dependencies for grpc/grpc/grpc: google-protobuf
==> Installing grpc/grpc/grpc dependency: google-protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-beta-1.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/google-protobuf-3.0.0-beta-1.tar.gz
==> Downloading https://raw.githubusercontent.com/grpc/homebrew-grpc/master/patches/google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "google-protobuf--patch"
Download failed: https://raw.githubusercontent.com/grpc/homebrew-grpc/master/patches/google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch

**Comment by nathanielmanistaatgoogle** [comment]
You may be working with some out-of-date installation instructions. What's the larger task you're trying to accomplish? In what programming language are you seeking to work with gRPC?

**Comment by jcanizales** [comment]
@murgatroid99 are you familiar with Homebrew?

**Comment by murgatroid99** [comment]
Not really

**Comment by jcanizales** [comment]
I can reproduce this locally. @tbetbetbe do you know what can this mean?

**Comment by soltanmm-google** [comment]
This should be filed [in the homebrew repository](https://github.com/grpc/homebrew-grpc).
