### ISSUE TITLE
Add knob for default core output verbosity

### ISSUE THREAD

**Issue by lafama** [grpc/grpc#5967]
Am using the pub/sub example code but after afew idle minutes the process starts logging this on the console
```
D0326 20:35:23.510143000 123145308205056 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0326 20:35:24.358179000 123145308205056 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0326 20:35:26.633089000 123145308205056 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
```
Any Ideas why
Question moved from : 
https://github.com/GoogleCloudPlatform/gcloud-node/issues/1187#issuecomment-201906588

**Comment by stephenplusplus** [comment]
Related: 5004

**Comment by soltanmm** [comment]
@lafama or @stephenplusplus: Those are messages from the gRPC core. Do y'all have the `GRPC_TRACE` environment variable set anywhere?

@ctiller For my own edification, would those kinds of logs appear even if the user hasn't set any logging variables?

**Comment by stephenplusplus** [comment]
Thanks for checking into this @soltanmm! When this came up with me before (in #5004), I made sure that wasn't set.

**Comment by soltanmm** [comment]
@ctiller Nevermind, found [this](https://github.com/grpc/grpc/blob/release-0_13_0/src/core/transport/chttp2_transport.c#L683).

So, yes, it turns out that in 0.13.0 there's some logging done that is unconditional w.r.t. environment variables. I'll poke around and see if we do that kind of thing still on `master` or our `release-0_13` branches.

**Comment by soltanmm** [comment]
So, we still do, and we do want to eventually add a knob for controlling output verbosity.

**Comment by ctiller** [comment]
Yuchen - we likely want to add two things here:
a public API `gpr_set_log_verbosity(gpr_log_severity min_severity_to_print);`
with an implementation in `gpr_log_message()`

and an environment variable that's parsed in init.c `GRPC_VERBOSITY`, taking the values of (DEBUG, INFO, ERROR) and calling the API function iff it hasn't been called by anyone else.

Care will need to be taken wrt threading... recommend using atomics for the global verbosity variable.

**Comment by stephenplusplus** [comment]
0.13.1 introduced a new type of output as well, for each call:

```
Service URL: https://datastore.googleapis.com/google.datastore.v1beta3.Datastore
Bearer ya29...
Service URL: https://datastore.googleapis.com/google.datastore.v1beta3.Datastore
Bearer ya29...
Service URL: https://datastore.googleapis.com/google.datastore.v1beta3.Datastore
Bearer ya29...
...
```

**Comment by murgatroid99** [comment]
It looks like that's a bit of debug logging that I accidentally left in the Node code in the 0.13 branch.

**Comment by jgeewax** [comment]
Can we get this merged in? It's affecting gcloud-node's production version.

**Comment by murgatroid99** [comment]
@stephenplusplus @jgeewax The npm package grpc@0.13.2-pre1 has been published with that fix.

**Comment by stephenplusplus** [comment]
When can we expect 0.13.2?

**Comment by y-zeng** [comment]
Added in #6189

**Comment by stephenplusplus** [comment]
@murgatroid99 are there any plans for releasing 0.13.2? gcloud users are still seeing the excess logging, since npm pre-releases have to be explicitly installed.

**Comment by murgatroid99** [comment]
We are planning to release 0.14.0 soon, and that will have the same fix.

**Comment by stephenplusplus** [comment]
Okay, any breaking changes I should get gcloud prepared for?

**Comment by murgatroid99** [comment]
We changed the argument order for method calls. Now the callback always comes last, and the metadata and options argument come before it, but are still optional.

**Comment by stephenplusplus** [comment]
Thanks!
