### ISSUE TITLE
vsprojects/vcxproj/grpc++/grpc++.vcxproj

### ISSUE THREAD

**Issue by HNoreick** [grpc/grpc#5968]
the file **\src\cpp\common\core_codegen.h** is embedded twice in the grpc++.vcproj. This causes an error with visual studio 2015 when the project will be reloaded.

Here is the snippet from the current projectfile where the the two lines with core_codegen.h are embedded. In he original file it matters the lines 339 and 343. line 343 should be deleted..
`  <ItemGroup>
    <ClInclude Include="$(SolutionDir)\..\src\cpp\client\secure_credentials.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\common\core_codegen.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\common\secure_auth_context.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\server\secure_server_credentials.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\client\create_channel_internal.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\common\core_codegen.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\common\create_auth_context.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\server\dynamic_thread_pool.h" />
    <ClInclude Include="$(SolutionDir)\..\src\cpp\server\thread_pool_interface.h" />
  </ItemGroup>`

**Comment by nicolasnoble** [comment]
We fixed this one, I believe.
