### ISSUE TITLE
[Node.js] Memory leak

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#5970]
There appears to be a memory leak when using this library with Node.js. When a Service object is instantiated (I believe this is also creating a "Channel"), memory usage goes up around 1 MB. Even if we don't retain a reference to the created service object or make a call on that channel, the memory doesn't appear to be collected-- confirmed using [Passenger](https://www.phusionpassenger.com/library/walkthroughs/start/nodejs.html) and monitoring the memory usage after up to 20 minutes, as well as by [forcing garbage collection](https://simonmcmanus.wordpress.com/2013/01/03/forcing-garbage-collection-with-node-js-and-v8/).

See the [original report on gcloud-node by @pierre-b](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1164) (gRPC-related conversation [starts here](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1164#issuecomment-198052306)).

**Comment by murgatroid99** [comment]
I don't think this is an actual memory leak. I set up a loop that creates these Client objects and then discards the reference. If some of the memory involved in the construction of those objects was leaking, I would expect unbounded memory usage growth, but `top` indicates that memory usage actually quickly levels off. I actually see the resident memory grow slowly and then drop when garbage is collected, all within fixed bounds, which is exactly what I would expect to see if everything is getting cleaned up correctly.

What you are seeing may simply be an artifact of the C or C++ level memory allocator.

**Comment by stephenplusplus** [comment]
Sounds good to me. I haven't been able to reproduce outside of the sample repo.

@pierre-b, I'll close this issue, but if you can track this down in a grpc-only environment, feel free to reply and we'll keep working on it. And thank you for the report to begin with. It led to some great discussions!

**Comment by pierre-b** [comment]
@stephenplusplus thanks for your time!
