### ISSUE TITLE
[Node.js] fatal error: third_party/nanopb/pb.h: No such file or directory

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#5972]
Travis is failing to install grpc@master correctly: https://travis-ci.org/GoogleCloudPlatform/gcloud-node/jobs/118542656#L316

```
make: Entering directory `/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/grpc/build'
  CC(target) Release/obj.target/grpc/src/core/census/grpc_context.o
  CC(target) Release/obj.target/grpc/src/core/census/grpc_filter.o
  CC(target) Release/obj.target/grpc/src/core/census/grpc_plugin.o
  CC(target) Release/obj.target/grpc/src/core/channel/channel_args.o
  CC(target) Release/obj.target/grpc/src/core/channel/channel_stack.o
  CC(target) Release/obj.target/grpc/src/core/channel/channel_stack_builder.o
  CC(target) Release/obj.target/grpc/src/core/channel/client_channel.o
  CC(target) Release/obj.target/grpc/src/core/channel/compress_filter.o
  CC(target) Release/obj.target/grpc/src/core/channel/connected_channel.o
  CC(target) Release/obj.target/grpc/src/core/channel/http_client_filter.o
  CC(target) Release/obj.target/grpc/src/core/channel/http_server_filter.o
  CC(target) Release/obj.target/grpc/src/core/channel/subchannel_call_holder.o
  CC(target) Release/obj.target/grpc/src/core/client_config/client_config.o
  CC(target) Release/obj.target/grpc/src/core/client_config/connector.o
  CC(target) Release/obj.target/grpc/src/core/client_config/default_initial_connect_string.o
  CC(target) Release/obj.target/grpc/src/core/client_config/initial_connect_string.o
  CC(target) Release/obj.target/grpc/src/core/client_config/lb_policies/load_balancer_api.o
In file included from .././src/core/client_config/lb_policies/load_balancer_api.h:40:0,
                 from ../src/core/client_config/lb_policies/load_balancer_api.c:34:
.././src/core/proto/grpc/lb/v0/load_balancer.pb.h:38:35: fatal error: third_party/nanopb/pb.h: No such file or directory
compilation terminated.
```

**Comment by murgatroid99** [comment]
The direct cause of this failure is that the `third_party/nanopb` is a git submodule, and npm does not clone submodules when installing a package from GitHub. More generally, we use submodules to track dependencies that are commonly not already installed on users' machines. Nanopb will be the first such submodule that the Node package depends on unconditionally, and that currently means that you cannot have an npm dependency on the master branch of the GitHub repository.

In the future, if there is a significant need to have that dependency, it may be possible to make it work.

**Comment by stephenplusplus** [comment]
Okay, thanks for the info. We've been using v0.13, but in implementing support for the upcoming Datastore v1beta3 API ([pr](https://github.com/GoogleCloudPlatform/gcloud-node/pull/897)), we need some of the changes that have been merged since (namely, #5005 & #5006).

I saw that v0.13.1-pre is available on npm, and it seemed to work locally with the changes we need for the Datastore PR. However, it has some unwanted logging output that must have since been corrected (related: #5967), because installing from master did not output the same logs.

Are there plans for cutting a new release in the near future?

**Comment by murgatroid99** [comment]
0.13.1 has now been released

**Comment by stephenplusplus** [comment]
Thanks!

**Comment by perone** [comment]
I'm facing this issue when using Bazel build for Android x86 on GRPC 1.0.0

**Comment by rkrten** [comment]
I have the same issue when I grab the zip file for grpc 1.0.0 -- the nanopb directory there is empty, but I'm not sure which version of nanopb corresponds to the grpc 1.0.0 file... ?
