### ISSUE TITLE
Throw RpcException from RequestStream.WriteAsync() on call failure

### ISSUE THREAD

**Issue by kkm000** [grpc/grpc#5975]
This is a follow-up feature request after a conversation with @jtattermusch  in https://groups.google.com/forum/#!topic/grpc-io/XFJTNnDsnDI. In short, the request is to change the C# client code such that if `RequestStream.WriteAsync()` fails because the call has completed, an `RpcException` with call's gRPC status is thrown. Currently, the same condition causes a generic `InvalidOperationExceprtion` be thrown.

Consider a server with a bidirectional stream. The client sends multiple messages to the server, then closes its stream, indicating that the data is complete and the client wants it processed. The processing may take a really long time, and result(s) are delivered upon completion as a single or multiple response messages.

The server indeed validates every data message sent by the client, and, should the data be hopelessly invalid, closes the call and reports a Status that the client must be able to receive. It appears that obtaining this status value in a C# client _correctly_ is not an easy task. While the current recommended patter is to allow `ResponseStream.MoveNext()` to fail with an `RpcException`, it is not an *easy and automatic* decision to somehow attempt to call `ResponseStream.MoveNext()` upon a failure at the sending end, and at the same time not to lose the gRPC Status information.

In an ideal world (well, ok, ok, _my_ ideal world), I would receive the RPC status from an exception thrown if the call is in a failed state:

```C#
  try {
    await call.RequestStream.WriteAsync(req);
  } catch (RpcException ex) {
    . . . use ex.Status() . . 
  }
```

However, currently `RequestStream.WriteAsync()` fails with a generic `InvalidOperationExceprtion` in such a case. This is a problem, because _it is impossible to know whether the  `InvalidOperationExceprtion` was thrown because the call has completed, or for any other reason_.

```C#
  try {
    await call.RequestStream.WriteAsync(req);
  } catch (InvalidOperationExceprtion ex) {
    ? ? ? what can I do here ? ? ?
  }
```
This is not a good state to be. If the call has ended, then some logic to fall through to `ResponseStream.MoveNext()` (which will throw the `RpcException` with the status) is recommended to be followed. If, however, the call has not completed, and the  `InvalidOperationExceprtion` was thrown by some system method call (and this is hard to control in .NET), then waiting on `ResponseStream.MoveNext()` is a deadlock. A timeout is of no help, because the server can legitimately process data for a very log time (and also because relying on timeouts is arguably not a good idea in general). So, before proceeding, I will have to attempt to check if the call has indeed completed, and then *assume*  that the `InvalidOperationExceprtion` was thrown because of it (ah, another assumption!). Unfortunately, the attempt to receive status from the call that has not completed results in another `InvalidOperationExceprtion`. All in all, the handler that seems to pull the trick looks too complicated:

```C#
  try {
    await call.RequestStream.WriteAsync(req);
  } catch (InvalidOperationException) {
    try {
      Status status = call.GetStatus();
      if (status.StatusCode != StatusCode.OK)
        throw new RpcException(status);
    } catch (InvalidOperationException) { }
    throw;
  }
```
This is almost an exercise in that "figure out what this code is doing" game. Naturally it synthesizes an `RpcException` if the call's status is available and indeed failed, or otherwise rethrows the original `InvalidOperationException` (so that no status will be returned to the caller).

Note that it appears that I do not even need to plumb a call to `ResponseStream.MoveNext()` in this case--it would not simplify the handler. The catch 22 here is that making the decision to proceed with the recommended pattern of obtaining the status requires that the very same status is in your possession--before the decision can be made!

It would be much more correct, I believe, to simply throw the `RpcException` from `WriteAsync()` in the first place.

**Comment by jtattermusch** [comment]
Thanks for filing this, your explanation makes sense. Here's a few followup questions:

1. What should WriteAsync(msg) throw if the call has already finished with StatusCode.OK?   One option is to throw new RpcException(new Status(StatusCode.OK, "")), that's a bit counterintuitive, because we are throwing for StatusCode.OK. On the other hand, this approach is consistent with throwing RpcException whenever we try to write to a call that has already finished. Another options is to throw just InvalidOperationException  (and throw RpcException of all non-ok status codes) - which actually sounds even more odd.

2. Another thing that can happen is that the call has been canceled (that's either initiated by user calling call.Cancel() or internally when we e.g. fail to parse the incoming protobuf message).  Currently, we are throwing OperationCanceledException after Cancel() has been invoked (both explicitly or implicitly). We can't really throw RpcException immediately after cancel has been requested, because it can take a bit before the call completion with StatusCode.Cancelled is delivered (and in the meantime we would be making up the resulting StatusCode without actually knowing it).  I'm not sure if switching from WriteAsync() throwing OperationCanceledException into throwing RpcException later on makes sense.

**Comment by jtattermusch** [comment]
@jskeet  @chrisdunelm   your opinions are more than welcome!

**Comment by jskeet** [comment]
Hmm. I'm afraid I don't have any easy answers here. 

One question though - in the case of:

> The server indeed validates every data message sent by the client, and, should the data be hopelessly invalid, closes the call and reports a Status that the client must be able to receive. 

That wouldn't be a status of OK anyway, would it?

When are we expecting to:

- Have a status of OK
- Have the client continue writing to the stream realistically expecting to still be able to write more data

? Might a client not know how much data it needs to send, and just keep sending things, and eventually the server decide it's got enough? I could see how that could just about make sense in some cases...

**Comment by kkm000** [comment]
@jtattermusch: Regarding item 2, that makes total sense. Call cancellation is client's business, and client's writing to the stream after the very same client has requested cancellation looks like an incorrect behavior to me. `OperationCanceledException` is quite warranted here.

As for #1, this is rather tough. I think that the scenario (the server interrupts the client's stream and reports `Status.OK`) should be rare; I'm with @jskeet here wondering what would that mean. Maybe the client does not understand the data, but server does? And then the stream is produced on the client that consists of multiple contiguous data items, but the server is interested only in the first one, while the client does not know where the first one ends? That looks like an odd corner case. I would say that throwing an `RpcException` with `Status.OK` is _not more odd_ than the case itself, and would not count as violation of the Principle of Least Surprise.
