### ISSUE TITLE
Simplify development environment for Python - package protoc and grpc protoc plugin.

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5980]
Package and ship protoc and gprc plugin for python.

- Figure out if it will be bundled with the grpc-python package or if it is going to be shipped separately. 
- Figure out for Mac/Linux/Windows.

On resolution of this issue, we should have 1 line install, via packages, for installing protoc, its plugins and the language runtime.

**Comment by soltanmm** [comment]
Fixed in #6280.

**Comment by psankar** [comment]
I ran `pip install grpcio` but I do not get `grpc_python_plugin` installed. What should I do to get this installed ? I see that this issue is closed but I am still running into the issue.

```
(venv)➜  venv pip show grpcio
---
Metadata-Version: 2.0
Name: grpcio
Version: 0.14.0
```

**Comment by soltanmm** [comment]
The tools are distributed separately: `pip install grpcio-tools`.
They're invoked, e.g., by: `python -m grpc.tools.protoc --help`.

**Comment by tseaver** [comment]
@soltanmm I have installed `grpcio` and `grpccio-tools`:  is the `python -m grpc.tools.protoc`command the `grpc_python_plugin`, or is it `protoc` itself?

**Comment by soltanmm** [comment]
@tseaver It's both (the plugin is compiled into the protoc source; n.b. the tools package is *not* a proper replacement for a proper future Python `protoc` tooling package [though it may obviously be abused as one]). The relevant command line flags should be available to you via the `help` output. Due to things not being wrapped 100% perfectly, however, it still requires as before the specification of `--python_out=$OUT` and `--grpc_python_out=$OUT` separately but with identical `$OUT`s.

Documentation will be available... soon-ish.

**Comment by tseaver** [comment]
@soltanmm can you give me even a crude example?  I'm guessing something like:
```bash
$ python2.7 -m virtualenv /tmp/grpc_python
$ /tmp/grpc_python/bin/pip install grcpio grpcio-tools
$ git clone https://github.com/google/googleapis/
$ mkdir generated
$ /tmp/grpc_python/bin/python -m grpc.tools.protoc \
  --proto_path=googleapis --python_out=xxx --grpc_python_out=xxx \
  googleapis/google/<package>/<versoin>/<file>.proto
```

**Comment by tseaver** [comment]
@soltanmm That [almost works](https://github.com/grpc/grpc/issues/7101).

**Comment by tseaver** [comment]
BTW, why doesn't the Python generator create `__init__.py` files in the package directories?

**Comment by soltanmm** [comment]
@tseaver My gut reaction is to punt the `__init__.py` question upstream to github.com/google/protobuf (we just inject code into whatever files they create), and to respond to #7101 with a woah-what-just-happened.
