### ISSUE TITLE
Simplify development environment for Ruby - package protoc and grpc protoc plugin.

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5981]
Package and ship protoc and gprc plugin for ruby.

- Figure out if it will be bundled with the grpc-ruby package or if it is going to be shipped separately. 
- Figure out for Mac/Linux/Windows.

On resolution of this issue, we should have 1 line install, via packages, for installing protoc, its plugins and the language runtime.

**Comment by ctiller** [comment]
Trying to free up some of Nico's time: he's got some urgent tasks right now.

**Comment by joelnn** [comment]
Is the intention to publish grpc-tools to rubygems?

**Comment by murgatroid99** [comment]
Yes, it will be published along with the 0.14 grpc release.
