### ISSUE TITLE
Ensure that gRPC Python implementation conforms to standard status codes in gRPC

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5992]
Error code specification here - https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by nathanielmanistaatgoogle** [comment]
@a11r: what's the status code to use for a cardinality violation (i.e. the server-side application has provided a function from exactly one request message to exactly one response message, but the data arriving from the client is a zero-length stream)?

**Comment by a11r** [comment]
UNIMPLEMENTED

**Comment by nathanielmanistaatgoogle** [comment]
This will finally be able to be closed after a small change following the merge of [pull request 6852](https://github.com/grpc/grpc/pull/6852).

**Comment by nathanielmanistaatgoogle** [comment]
Closing this issue is now blocked on (very small and very easy to review) [pull request 6904](https://github.com/grpc/grpc/pull/6904).
