### ISSUE TITLE
Ensure that gRPC ObjC implementation conforms to standard status codes in gRPC

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5994]
Error code specification here - https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by jcanizales** [comment]
The specification means a client has to generate:
- [ ] Client Application cancelled the request: CANCELLED
- [ ] Deadline expires before server returns status: DEADLINE_EXCEEDED
- [ ] No response received before Deadline expires. This may occur either when the client is unable to send the request to the server or when the server fails to respond in time.: DEADLINE_EXCEEDED
- [ ] Some data transmitted (e.g., request metadata written to TCP connection) before connection breaks: UNAVAILABLE
- [ ] Could not decompress, but compression algorithm supported (Server -> Client): INTERNAL
- [ ] Flow-control protocol violation: INTERNAL
- [ ] Error parsing returned status: UNKNOWN
- [ ] Incorrect Auth metadata ( Credentials failed to get metadata, Incompatible credentials set on channel and call, Invalid host set in `:authority` metadata, etc.): UNAUTHENTICATED
- [ ] Error parsing response proto: INTERNAL

And not generate any of:
- [ ] INVALID_ARGUMENT
- [ ] NOT_FOUND
- [ ] ALREADY_EXISTS
- [ ] FAILED_PRECONDITION
- [ ] ABORTED
- [ ] OUT_OF_RANGE
- [ ] DATA_LOSS

**Comment by makdharma** [comment]
@muxi - Please paste code snippet links that show the error generation for each of these.

**Comment by muxi** [comment]
Here is a checklist of current status of this issue. Will keep it updated as each of them get fixed

- [ ] Client Application Cancelled the request: CANCELLED [https://github.com/grpc/grpc/blob/a9df5d1029b303a305481c4bb765c6bed2e8ebbb/src/objective-c/GRPCClient/GRPCCall.m#L164](link)
- [ ] Deadline expires before server returns status: DEADLINE_EXCEEDED
- [ ] No response received before Deadline expires. This may occur either when the client is unable to send the request to the server or when the server fails to respond in time.: DEADLINE_EXCEEDED
- [ ] Some data transmitted (e.g., request metadata written to TCP connection) before connection breaks: UNAVAILABLE [https://github.com/grpc/grpc/blob/a9df5d1029b303a305481c4bb765c6bed2e8ebbb/src/objective-c/GRPCClient/GRPCCall.m#L378](link)
- [ ] Could not decompress, but compression algorithm supported (Server -> Client): INTERNAL
- [ ] Flow-control protocol violation: INTERNAL
- [ ] Error parsing returned status: UNKNOWN
- [ ] Incorrect Auth metadata ( Credentials failed to get metadata, Incompatible credentials set on channel and call, Invalid host set in :authority metadata, etc.): UNAUTHENTICATED
- [ ] Error parsing response proto: INTERNAL

The following error codes are currently generated under certain cases not captured by the document

- [ ] The app does not have enough memory to hold the server response: INTERNAL [https://github.com/grpc/grpc/blob/a9df5d1029b303a305481c4bb765c6bed2e8ebbb/src/objective-c/GRPCClient/GRPCCall.m#L215-L217](link)

The following error codes are supposed not to be generated:
- [ ]  INVALID_ARGUMENT
- [ ]  NOT_FOUND
- [ ]  ALREADY_EXISTS
- [ ]  FAILED_PRECONDITION
- [ ]  ABORTED
- [ ]  OUT_OF_RANGE
- [ ]  DATA_LOSS
