### ISSUE TITLE
Incorrect work streams in C++

### ISSUE THREAD

**Issue by ChuiIsLive** [grpc/grpc#5999]
When working with synchronous streaming RPCs i found that if you shutting down server, client will be write next message successfully with method 'Write', but in console will be written error. All future call of method 'Write' return false. This means that the client is sure that a message is sent, but in reality it is not.

**Comment by yang-g** [comment]
I am not sure I understand the problem, especially the part about " in console will be written error". Could you clarify?

**Comment by ChuiIsLive** [comment]
What have I done:
1. Open synchronous stream from client to server
2. Write 1 message by client-side, function return true result
3. Shutdown server
4. Write 1 message by client-side, function return true result, but in console-output error will be written(some a service error). In fact server did not receive a message from a client.
5. Write 1 message by client-side, function return false result

In step 4 function Write must be return result false, but returns true.

**Comment by sreecha** [comment]
The write path has changed considerably in the past 2 years. I am sure this is obsolote. @ChuiIsLive , please reopen the issue if you are seeing this in the current version of grpc.
