### ISSUE TITLE
linker error grpc_unsecure.def missing on MinGW64 / MSYS2 build of grpc 0.13.0

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#6019]
I'm trying to compile grpc 0.13.0 on Windows with MinGW64 (gcc 5.3.0 as of now). It fails with a linker error that grpc_unsecure.def would be missing:

```
[...]
[LD]      Linking /c/thirdparty/grpc-release-0_13_0/libs/opt/grpc_unsecure-0.dll
cc.exe: error: grpc_unsecure.def: No such file or directory
```

**Comment by soltanmm-google** [comment]
Half a pound of tuppenny rice /
Half a pound of treacle /
That's the way the numbers go /
Up goes the version
