### ISSUE TITLE
Drop precompiled hackery in favor of manylinux

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#6036]
Because apparently [it's a thing now](https://github.com/pypa/manylinux/issues/27).

**Comment by nathanielmanistaatgoogle** [comment]
:+1:

**Comment by tseaver** [comment]
https://github.com/pypa/python-manylinux-demo demonstrates building `manylinux` wheels on Travis.  The demo even including bundling the external `libatlas` shared library using `auditwheel repair`.

**Comment by soltanmm** [comment]
Fixed in #6280 and #6464.
