### ISSUE TITLE
Ruby has too many outstanding calls to grpc_completion_queue_pluck

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6045]
When running the Ruby performance worker ( #6010  ) with 5 threads outstanding, I was able to get the following error

$ bins/opt/qps_driver --rpc_type=STREAMING --outstanding_rpcs_per_channel=5 --client_channels=1 --simple_req_size=65536 --simple_resp_size=65536 --secure_test=false --num_servers=1 --num_clients=1
I0331 14:27:33.133510202   27613 driver.cc:204]              Starting server on localhost:10000 (worker #0)
I0331 14:27:33.135349558   27613 driver.cc:267]              Starting client on localhost:10001 (worker #1)
I0331 14:27:33.139190059   27613 driver.cc:310]              Warming up
D0331 14:27:33.140736737   27649 completion_queue.c:411]     Too many outstanding grpc_completion_queue_pluck calls: maximum is 6
I0331 14:27:38.139277211   27613 driver.cc:316]              Starting
I0331 14:27:38.145050465   27613 driver.cc:337]              Running
D0331 14:27:42.929758663   27639 completion_queue.c:411]     Too many outstanding grpc_completion_queue_pluck calls: maximum is 6

Note that the test ran to completion.

I can get more of these errors if I run with 40 threads outstanding by changing client_channels to 8. In this case, the test makes progress but eventually dies with a stack trace and a note:
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

@ctiller what does this suggest?

**Comment by murgatroid99** [comment]
One fix that I see for this is to have a dedicated thread just to run `grpc_completion_queue_next`, and then dispatch the events back to the thread that created them using condition variables.

**Comment by vjpai** [comment]
Hi Michael, let's discuss concurrency improvements in #6047 . I think that sounds great, but we have a short-term problem to deal with as well.

**Comment by ctiller** [comment]
Guessing: Ruby is multiplexing all calls onto one CQ and calling pluck() on
it.
We *could* make that work, but it could make ordinary plucks very slow -
which is a no.
Or it could complicate completion_queue.c further, which is also
undesirable - but I could be convinced.

Otherwise, we need to either do what Michael suggested, or change the Ruby
implementation to create a CQ-per-request.

**Comment by vjpai** [comment]
Ah yes, that last one is probably what we should do: change the Ruby implementation to one CQ per request, just like sync C++. That would be a first step. Then on to the async core interactions.

**Comment by vjpai** [comment]
Confirming that Ruby uses one CQ per client stub and one CQ per server

**Comment by ctiller** [comment]
So we either fix ruby, or fix C (the change I'm thinking about would be to
switch to an AVL if num_pluckers ever exceeds 6 on a cq)

**Comment by vjpai** [comment]
I think it makes sense to fix Ruby for the reason that the closer it is to sync C++, the more our performance improvement insights from sync C++ will apply to it.
