### ISSUE TITLE
Disable compression option

### ISSUE THREAD

**Issue by LukeMauldin** [grpc/grpc#6055]
Is there an option to disable ZLIB compression on Windows builds in GRPC?  For example, protocol buffers allows passing: " -Dprotobuf_WITH_ZLIB=OFF" to cmake and then the builds do not include zlib compression.

**Comment by jtattermusch** [comment]
Currently you need zlib to compile gRPC. We don't believe that's a limitation so there's no plan to change that.
Btw, an official way to build grpc on windows is now cmake. You should be able to build on windows (including zlib) seamlessly.
https://github.com/grpc/grpc/blob/master/INSTALL.md#windows
