### ISSUE TITLE
Visual Studio 2015 Debug-DLL Build Fails

### ISSUE THREAD

**Issue by LukeMauldin** [grpc/grpc#6058]
In Visual Studio 2015 Update 2, using GRPC 0.13.1, the Debug-DLL build for the project grpc_unsecure fails with this error:
`1>LINK : fatal error LNK1104: cannot open file 'C:\Users\mauldinl\Downloads\grpc-release-0_13_1\vsprojects\x64\Debug\gpr.lib'`
I have verified these files exist in the directory `C:\Users\mauldinl\Downloads\grpc-release-0_13_1\vsprojects\x64\Debug`

```
gpr.dll
gpr.ilk
gpr.pdb
```

The `gpr.lib` file does not exist.  I followed the Visual Studio installation instructions.

**Comment by soltanmm-google** [comment]
Version number: up it goes!
