### ISSUE TITLE
Deduplicate health.proto for python

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6060]
Use `src/proto/grpc/health/v1/health.proto` and remove `src/python/grpcio_health_checking/grpc/health/v1alpha/health.proto`.

See #3850 for context (this is the last actionable item from that issue, so filing a python specific issue and closing the generic one).

**Comment by jtattermusch** [comment]
FYI @kpayson64

**Comment by kpayson64** [comment]
Addressed in #6439
