### ISSUE TITLE
Make fuzzer_output/* available from Jenkins

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#6061]

**Comment by ctiller** [comment]
uri_fuzzer at least is generating new corpus entries right now, it'd be nice to be able to grab them.

**Comment by nicolasnoble** [comment]
Wasn't that done ? They should be artifacts available in Jenkins.

**Comment by nicolasnoble** [comment]
Yep, there are: https://grpc-testing.appspot.com/view/Fuzzers/job/gRPC_fuzzer_client/
