### ISSUE TITLE
gRPC 0.13.0 compile expects protobuf to use pkgconfig, but with cmake it does not

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#6074]
There are platforms (like MinGW64 / MSYS2) where currently the cmake-build of protobuf works better than the autotools build. But when using cmake with protobuf, then gRPC will not find protobuf due to cmake's lack of pkgconfig-support. It would be good if gRPC would recover from this lack, by falling back to testing for protobuf. The test exists already in the Makefile, but is not used if pkgconfig is available.

See also https://github.com/google/protobuf/issues/1384

**Comment by nicolasnoble** [comment]
You can disable pkg-config tests by doing:

```
HAS_PKG_CONFIG=false make
```
