### ISSUE TITLE
java.lang.NoSuchMethodError: No static method directExecutor() at io.grpc.internal.ClientCallImpl

### ISSUE THREAD

**Issue by mickykebe** [grpc/grpc#6076]
It compiles just fine, but that error keeps popping up when my android app makes a blocking call to the server.

> No static method directExecutor()Ljava/util/concurrent/Executor; in class Lcom/google/common/util/concurrent/MoreExecutors; or its super classes (declaration of 'com.google.common.util.concurrent.MoreExecutors' appears in /data/data/com.fentale.dalol/files/instant-run/dex/slice-guava-jdk5-17.0_a8ada10dcaf113cb6e3b4d3e5b46975833f8ae8f-classes.dex)
                                                           java.lang.NoSuchMethodError: No static method directExecutor()Ljava/util/concurrent/Executor; in class Lcom/google/common/util/concurrent/MoreExecutors; or its super classes (declaration of 'com.google.common.util.concurrent.MoreExecutors' appears in /data/data/com.fentale.dalol/files/instant-run/dex/slice-guava-jdk5-17.0_a8ada10dcaf113cb6e3b4d3e5b46975833f8ae8f-classes.dex)
                                                               at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:100)
                                                               at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:320)
                                                               at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:299)
                                                               at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)

**Comment by mickykebe** [comment]
>C:\<path>\.gradle\caches\modules-2\files-2.1\com.google.guava\guava-jdk5\17.0\cc6729ce0bc6cc29441cb3a04acad02aeeebb26e\guava-jdk5-17.0-sources.jar!\com\google\common\util\concurrent\MoreExecutors.java

Inside this file, the method 'directExecutor' isn't there.

But it is imported in:
>C:\<path>\.gradle\caches\modules-2\files-2.1\io.grpc\grpc-core\0.13.2\6c4634cb7df8d2f02e5fd83e72510af44881a82f\grpc-core-0.13.2-sources.jar!\io\grpc\internal\ClientCallImpl.java

Is this possibly a build error? I checked guava's source on github and there the MoreExecutors file did in fact have the 'directExecutor' method. Why is my version of this file different?

**Comment by mickykebe** [comment]
I've been looking into the guava jar:

>http://grepcode.com/file/repo1.maven.org/maven2/com.google.guava/guava-jdk5/17.0/com/google/common/util/concurrent/MoreExecutors.java?av=f

And there appears to be no static method called 'directExecutor.' inside the class MoreExecutors. Yet inside:

>grpc-core-0.13.2-sources.jar!\io\grpc\internal\ClientCallImpl.java

exists the statement:

>import static com.google.common.util.concurrent.MoreExecutors.directExecutor;

And other statements calling 'directExecutor.' Surely this is a bug. My code won't work unless it's fixed.

**Comment by BelfodilAimene** [comment]
Is there any solution (I have the same problem when i use Spark)

**Comment by mickykebe** [comment]
@BelfodilAimene My app had a dependency on the youtube library which inturn depended on guava. However youtube's guava dependency is from a different source than grpc's and using an older version. Two versions of the guava jar existed in the app and grpc was accessing youtube's older guava version rather than its own, which caused the problem.
Solution: 
  compile('com.google.apis:google-api-services-youtube:v3-rev164-1.21.0') {
        exclude module: 'guava-jdk5'
    }

See if there's a library dependent on guava in your project.

**Comment by BelfodilAimene** [comment]
Thank you, I have used relocation (of maven) for : 
com.google.common.util.concurrent.MoreExecutors
com.google.common.base.Stopwatch
