### ISSUE TITLE
grpc shouldn't dictate where to put source code of nanopb

### ISSUE THREAD

**Issue by mzhaom** [grpc/grpc#6083]
third_party/grpc/upstream/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v0/load_balancer.pb.h:38:35: fatal error: third_party/nanopb/pb.h: No such file or directory
 #include "third_party/nanopb/pb.h"

Since pb.h's path is put into include path, this line should be changed to `#include <pb.h>`

Thanks1

**Comment by twprzybysz** [comment]
+1

**Comment by soltanmm** [comment]
I believe you're looking for `git submodule --init`.

`nanopb` is submoduled in the git repository to avoid an unnecessary dependence on the user's environment.

Or is this a general stance against git submodules?

**Comment by ctiller** [comment]
bazel has a unique stance on submodules... we have a rough plan to address
this, but the infrastructure is not there yet.
@nicolasnoble is planning on addressing it soon.

**Comment by jcanizales** [comment]
Is the plan to just depend on nanopb as any other library, instead of compiling it together with the C gRPC sources?

As it is now, users can't depend on gRPC _and_ nanopb, as they'll get duplicate symbols errors.

**Comment by soltanmm-google** [comment]
`nanopb` is vendored now.
