### ISSUE TITLE
(dbg, c++, linux) End2endTest.MultipleRpcs/1 flake

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#6097]
https://grpc-testing.appspot.com/job/gRPC_master/16288/config=dbg,language=c++,platform=linux/console

probably a flake, green build before and after

```
PASSED: bins/dbg/boringssl_bytestring_test
PASSED: bins/dbg/end2end_test:End2end/End2endTest.MultipleRpcs/0
FAILED: bins/dbg/end2end_test:End2end/End2endTest.MultipleRpcs/1
PASSED: bins/dbg/end2end_test:ProxyEnd2end/ProxyEnd2endTest.MultipleRpcs/2
PASSED: bins/dbg/cxx_string_ref_test:StringRefTest.CopyConstructor
PASSED: bins/dbg/end2end_test:ProxyEnd2end/ProxyEnd2endTest.MultipleRpcs/0
```

**Comment by stanley-cheung** [comment]
Looks like this is passing consistently now

**Comment by apolcyn** [comment]
might not be the exact same test but `ProxyEnd2endTest.MultipleRpcs/2` failed with log in https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/3000/testReport/junit/(root)/c++_linux_tsan_native/bins_tsan_end2end_test___gtest_filter_ProxyEnd2end_ProxyEnd2endTest_MultipleRpcs_2__GRPC_POLL_STRATEGY_epoll/

notably:
```
SUMMARY: ThreadSanitizer: data race /var/local/git/grpc/src/core/lib/iomgr/closure.c:60:29 in grpc_closure_list_append
```

pr https://github.com/grpc/grpc/pull/10230 against v1.2.x

**Comment by apolcyn** [comment]
seen again on v1.2.x  branch pr: https://github.com/grpc/grpc/pull/10306

log in https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/3152/
