### ISSUE TITLE
grpc_ruby_plugin doesn't generate the correct type name when an external proto is returned

### ISSUE THREAD

**Issue by jmuk** [grpc/grpc#6102]
Think that common types are defined in a different package and the service definition uses it. grpc_ruby_plugin generates non-qualified type name for the external types, which causes an error loading the generated ruby files.

For example, think that the package contains two directories -- common/ for common types, and api/ for the service.

common/types.proto

```
syntax = "proto3";
package common;
message Response {
  string msg = 1;
}
```

api/api.proto

```
syntax = "proto3";
package api;
import "common/types.proto";
service FooService {
  rpc foo(FooRequest) returns (common.Response);
}
message FooRequest {
  int32 foo = 1;
}
```

Then, the generated api_services.rb contains a line of `rpc :foo, FooRequest, Response`.  This is wrong because Response is in a different package, it should be fully-qualified as Common::Response.

**Comment by apolcyn** [comment]
I think this has since been fixed?

Used a directory structure of:
`<base>/protos/common/types.proto`
`<base>/protos/api/api.proto`

and those examples above copied into the files.

Generated the ruby code from the `<base>/ruby` directory with:
```
> protoc=../../bins/opt/protobuf/protoc
> plugin=../../bins/opt/grpc_ruby_plugin

> $protoc -I ../protos --ruby_out=lib --grpc_out=lib ../protos/common/types.proto --plugin=protoc-gen-grpc=$plugin
> $protoc -I ../protos --ruby_out=lib --grpc_out=lib ../protos/api/api.proto --plugin=protoc-gen-grpc=$plugin
```

The service class ends up in `<base>/ruby/lib/api_services_pb.rb`, looking like:

```
require 'grpc'
require 'api/api_pb'

module Api
  module FooService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.FooService'

      rpc :foo, FooRequest, Common::Response
    end

    Stub = Service.rpc_stub_class
  end
end
```

The reference to `Common::Response` here seems to be ok.

**Comment by apolcyn** [comment]
Generating the ruby protobuf code also seems to give the same result with `grpc-tools.1.0.1` gem.

Closing as I think this has been fixed.
