### ISSUE TITLE
gpr_histogram provides no facility to output buckets

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#611]

**Comment by vjpai** [comment]
Revisiting this old issue: The title suggests that this should be in the C core, though I don't know if any wrapped language besides C++ uses the gpr_histogram feature. I don't mind putting it in either C or C++, depending on how it will be used.

Also, any opinions what the output format should be? I can think of 2:

1. A CSV that's dumped to a std::ostream (or FILE * if this is for C also) specified in an argument, so that it's easy to import into a spreadsheet. The columns could be something like bucket lower bound, bucket upper bound, count. Synchronization mechanism may be needed, or perhaps the user of the histogram is responsible for this.

2. Output should be as a protobuf. But I find this undesirable since we don't want any dependence on protobuf for the libraries themselves (tests are another matter, of course).

**Comment by ctiller** [comment]
I'd lean towards having a protobuf based histogram format for communication
between various processes, and a library that can dump said protobuf into
CSV (or similar formats).

**Comment by ctiller** [comment]
Not GA blocking

**Comment by vjpai** [comment]
No longer relevant
