### ISSUE TITLE
GPR_UNREACHABLE_CODE causes compile warnings in XCode

### ISSUE THREAD

**Issue by tkchin** [grpc/grpc#6118]
channel_init.c:123:1: Control may reach end of non-void function
channel_stack_type.c:54:1: Control may reach end of non-void function

@jcanizales

**Comment by jcanizales** [comment]
Weird, unless you're targeting OS X instead of iOS which I don't think it's the case?

What version of XCode and clang are you using?

**Comment by tkchin** [comment]
XCode 7.3, and the clang that comes with that. iOS.

**Comment by jcanizales** [comment]
@yang-g, I have no idea of what's broken with that macro. Please reassign to someone of the C team that might know how to fix it.

**Comment by jcanizales** [comment]
The warnings are in `src/core/lib/surface/channel_init.c:123` and `src/core/lib/surface/channel_stack_type.c:54`.

**Comment by jcanizales** [comment]
@nicolasnoble FYI

**Comment by sibinlutoken** [comment]
Is there any update on this issue? Im still seeing the same problem.

**Comment by muxi** [comment]
@sibinlutoken we are not seeing it on our side at this moment... could you specify how you are reproducing it?

Also, you could try to inhibit the warning by using the macro `GPR_FORBID_UNREACHABLE_CODE = 0`.

**Comment by sibinlutoken** [comment]
Im using Xcode 8.3.3 and working on a iOS sdk with grpc. I find the "Control may reach of non-void function" warning in channel_stack-type.c near GPR_UNREACHABLE_CODE in gRPC-Core. 

I can see some dependency analysis warnings "Multiple build commands for output file ..../gRPC-Core/atm.h". Not sure if it is related.

Please let me know if you need more info on the issue

**Comment by muxi** [comment]
Could you please give the macro `GPR_FORBID_UNREACHABLE_CODE ` a try?

**Comment by sibinlutoken** [comment]
I add "GPR_FORBID_UNREACHABLE_CODE=0" in preprocessor macros then clean and build. The warnings are still there. Please let me know if Im looking into the wrong place.
