### ISSUE TITLE
Second blocking call in an ASP.NET request fails with odd exception

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#6119]
I can put fuller sample code in tomorrow, but basically I have a minimal MVC app which makes two blocking gRPC calls in the same request. The second fails, claiming to be Unauthenticated, but actually what's happening is more subtle:

- NativeMetadataCredentialsPlugin.NativeMetadataInterceptorHandler is throwing an InvalidOperationException
- I believe this means we don't get a payload
- Google.Protobuf.MessageParser.Parse throws an ArgumentNullException (because the payload is null)
- The exception is caught and somehow a status of Unauthenticated is returned

The original `InvalidOperationException` is:

> An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.

I believe in this case it's because StartGetMetadata is an async void method, although we'd need to do some digging to check.

Note that the client code is only making _synchronous_ calls. It feels unreasonable to prohibit those.

**Comment by jtattermusch** [comment]
This is the relevant code:

https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/NativeMetadataCredentialsPlugin.cs#L90

And yes, `StartGetMetadata` returning void seems it could be the problem.

**Comment by jtattermusch** [comment]
I think I'll just try changing the method signature to async Task . Will you be able to test the fix if I give you a set of testing nugets?

**Comment by jskeet** [comment]
Yup, that should be reasonably straightforward, I think.

The alternative is to leave it as a void method, but make it no longer async, and instead use ContinueWith inside the method.

**Comment by jtattermusch** [comment]
@jskeet , can you please test if you are still seeing the issue with nuget packages from this build (built from #6127's branch):
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/505/platform=windows/

Btw, these packages already contain the recent changes to the gRPC codegen (generated interfaces -> abstract classes).

**Comment by jskeet** [comment]
Yup, will test now.

**Comment by jskeet** [comment]
Certainly fixes my particular test repro. I'm not sure whether it's the best way of doing it - the fact that we've got an async method that we're not awaiting is at least a little troubling - but I can't immediately see any better approach.
