### ISSUE TITLE
run_tests.py not properly cleaning up failed tests?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#6120]
In the course of investigating [issue 5817](https://github.com/grpc/grpc/issues/5817) I today executed in series

```
$ time ./tools/run_tests/run_tests.py --language=python --regex=plugin --runs_per_test=250 --jobs=500
$ time ./tools/run_tests/run_tests.py --language=python --regex=plugin --runs_per_test=125 --jobs=500
$ time ./tools/run_tests/run_tests.py --language=python --regex=plugin --runs_per_test=125 --jobs=500
```

. It didn't go well. I didn't expect it to go well. The tests failed in spectacular ways. But what's strange is that it's left a large number of test processes still running on my system - 251 immediately after the last run finished and 238 now around thirty minutes later. My expectation was that run_tests.py wouldn't exit without having cleaned up everything it launched. According to `top` the Python test processes are still consuming memory and processor cycles, and sure enough a "sane" test run is longer than it was immediately after a fresh boot (ninety seconds compared to thirty). And the GCE CPU usage graph shows the VM consuming 100% CPU since the start of the test, with no downturn when run_tests.py exited.

Anyone else seeing behavior like this? This is on a GCE VM running Debian 8.2.

Is this a defect in run_tests.py, or am I doing something wrong?

**Comment by ctiller** [comment]
Relevant code is in jobset.py. unassigning myself though: it's unlikely I'll look at this in the next quarter or two, and run_tests.py is community owned at this point. Perhaps @adelez might have some time?

**Comment by adelez** [comment]
I'll take a look.

**Comment by soltanmm-google** [comment]
Is this still a problem?

**Comment by nathanielmanistaatgoogle** [comment]
As of today I am still able to reproduce this issue... more or less as described. After
```
time ./tools/run_tests/run_tests.py --language=python --regex=plugin --runs_per_test=80 --jobs=500 --newline_on_success
```
I see three processes each consuming around 100% CPU:
```
<path to repository>/py34/bin/python <path to repository>/src/python/grpcio_tests/setup.py test_lite
<path to repository>/py27/bin/python <path to repository>/src/python/grpcio_tests/setup.py test_lite
<path to repository>/py34/bin/python <path to repository>/src/python/grpcio_tests/setup.py test_lite
```
.

So still an issue... but not a priority for now.

**Comment by adelez** [comment]
Sorry for the delay. I'll start looking tomorrow.

**Comment by nathanielmanistaatgoogle** [comment]
@adelez: well, do take note of the `P3` label, so feel free to let "tomorrow" slide into ["when the sleeper wakes"](https://en.wikipedia.org/wiki/The_Sleeper_Awakes). 😛
