### ISSUE TITLE
PHP module unusable on OS X El Capitan

### ISSUE THREAD

**Issue by annismckenzie** [grpc/grpc#6129]
Building the PHP module on OS X El Capitan (10.11.4) per the instructions for both 0.13 and master results in Apache failing to load the module with:

```bash
<b>Warning</b>:  PHP Startup: Unable to load dynamic library '/Users/annismckenzie/git/GitHub/grpc/src/php/ext/grpc/modules/grpc.so' - dlopen(/Users/annismckenzie/git/GitHub/grpc/src/php/ext/grpc/modules/grpc.so, 9): Library not loaded: libgrpc.dylib
  Referenced from: /Users/annismckenzie/git/GitHub/grpc/src/php/ext/grpc/modules/grpc.so
  Reason: unsafe use of relative rpath libgrpc.dylib in /Users/annismckenzie/git/GitHub/grpc/src/php/ext/grpc/modules/grpc.so with restricted binary in <b>Unknown</b> on line <b>0</b><br />
```

After some googling around I got it work after running the following commands:
```
$ install_name_tool -change libgrpc.dylib /usr/local/lib/libgrpc.dylib /usr/local/Cellar/php56/5.6.17/lib/php/extensions/no-debug-non-zts-20131226/grpc.so
$ install_name_tool -change libgpr.dylib /usr/local/lib/libgpr.dylib /usr/local/Cellar/php56/5.6.17/lib/php/extensions/no-debug-non-zts-20131226/grpc.so
```

It seems the build process references the dynamic libraries directly from the gRPC core C part and not the ones installed in `/usr/local/lib/`. Did I make a mistake along the way? I've been building gRPC locally for the better part of a year now so this wasn't my first time (but I just upgraded to El Capitan last week).

Both the C core as well as the PHP extension were built with `make` and installed with `make install`.

**Comment by stanley-cheung** [comment]
Since 0.13, the PHP extension is packaged with the C core in one single package. There is no need to build the C core separately first. The PHP extension can be installed via `sudo pecl install grpc-beta`. Can you try that please?

**Comment by annismckenzie** [comment]
Oh wow.

Seems like that that should work – still, is there a way to build the working packaged extension for myself off of the master branch? I'd rather stay on the/a release branch / master branch. However, if that makes your life harder and is considered `well, you're not using the packaged version so deal with any breakage yourself` then you may close this issue.
