### ISSUE TITLE
NetworkError not surfaced during bidirectional streaming

### ISSUE THREAD

**Issue by jerjou** [grpc/grpc#6131]
Hello-

I'm using the python grpc lib in [this code](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/726e6736104dea2880419b85f08d462253b42ebb/speech/api/speech_streaming.py) to stream audio to the Google Cloud Speech API. The audio streams from the attached microphone, so effectively never ends.

If I run that script without setting up my [auth credentials](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/726e6736104dea2880419b85f08d462253b42ebb/speech/api/README.md#set-up-to-authenticate-with-your-projects-credentials), it hangs. If I modify the script slightly by adding a `return` statement [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/726e6736104dea2880419b85f08d462253b42ebb/speech/api/speech_streaming.py#L79), the `grpc.framework.interfaces.face.face.NetworkError` is raised as expected.

Somehow the [audio stream loop thread](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/726e6736104dea2880419b85f08d462253b42ebb/speech/api/speech_streaming.py#L80) is keeping the network error from being raised.

**Comment by soltanmm** [comment]
Which version of gRPC Python are you using?

**Comment by jerjou** [comment]
Oh, I see - I was using 0.14.0. Upgrading to 0.15.0 fixes it. Thanks.

**Comment by jerjou** [comment]
Whoops - posted this on the wrong bug. This one still occurs using 0.15.0.

**Comment by soltanmm-google** [comment]
(please reopen if this is still a problem in 1.x)
