### ISSUE TITLE
Archive has no index: grpc 0.13.1 static libs stripped too much on MSYS2 / MinGW64?

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#6136]
I have compiled grpc 0.13.1 on Windows 7 with MinGW64 on MSYS2. So far my mileage is quite good, but when I try to link against the static libs, I get the following error for _all_ libraries:

```
C:/msys2/mingw64/lib/libgrpc++_unsecure.a: error adding symbols: Archive has no index; run ranlib to add one
```

Making an explicit call to "ranlib" for every lib fixes the issue. I found that the problem seems to come from "strip" which cleans too much. So this helps:

```
make STRIP="strip --strip-unneeded" ...
```

**Comment by jtattermusch** [comment]
Fixed in #9307.
