### ISSUE TITLE
question on response-streaming RPC in Python

### ISSUE THREAD

**Issue by coconut6711** [grpc/grpc#6142]
Hi, 
In the Python example code, for response-streaming RPC, it says

  for feature in stub.ListFeatures(rectangle, timeout_in_seconds):

Does it mean the stream will be always up, and in a waiting-data status?

The reason I am asking is, in order to get metadata, I have to first assign RPC call to an iterator and call initial_metadata(), then loop thru the iterator for each data it has.

And if I assume the stream is already up and the server sends the data after some time, say 1 second, how do I get the second data?
Calling stub.ListFeatures(rectangle, timeout_in_seconds) multiple times may not be an expected behavior from grpc server perspective.

I found out in the cpp version client, it creates a Reader object and you can continuously poll this reader to see if there is new data.

e.g. 
while (reader->Read(&feature)) {
      std::cout << "Found feature called "
                << feature.name() << " at "
                << feature.location().latitude()/kCoordFactor_ << ", "
                << feature.location().longitude()/kCoordFactor_ << std::endl;
    }

So, for python, it seems not the case, how do I do the similar for streaming type RPC?
 i.e. call streaming RPC once, get the metadata,  then keep checking data buffer and read the data out when available.

Thanks,
Weiyu

**Comment by soltanmm** [comment]
The value returned from a streaming response call is an iterator that iterates over the streamed responses. That same object should also provide the methods `initial_metadata` and `terminal_metadata` that you may invoke to get the metadata sent by the server.

**Comment by nathanielmanistaatgoogle** [comment]
Are you looking for code like
```
my_response_iterator = my_stub.ListFeatures(rectangle, timeout_in_seconds)
my_initial_metadata = my_response_iterator.initial_metadata()
for feature in my_response_iterator:
  <something involving feature>
my_terminal_metadata = my_response_iterator.terminal_metadata()
```
?

What's not possible is querying the iterator about whether or not it has a response value immediately available.
