### ISSUE TITLE
DocFixit: Setup instructions incorrect/incomplete at GRPC C# Web tutorials page

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#6151]
I see the following issues when following instructions: http://www.grpc.io/docs/tutorials/basic/csharp.html on WINDOWS platform.
Note: I am using VS 2015 community edition

- 1) In the first secion `Example code and setup`, we need to write instructions on how to get `Grpc` NuGet package (perhaps we can just point to the setup instructions at: https://github.com/grpc/grpc/blob/master/src/csharp/README.md)

-  2) In the `Generating client and server code` section, the protoc version is out dated
The instructions on the page are the following:
```
  > packages\Google.Protobuf.3.0.0-alpha4\tools\protoc.exe -I../../protos --csharp_out RouteGuide --grpc_out RouteGuide --plugin=protoc-gen-grpc=packages\Grpc.Tools.0.7.0\tools\grpc_csharp_plugin.exe ../../protos/route_guide.proto
```
When I followed the instructions, the protobuf directory on my machine is `Google.Protobuf.3.0.0-beta2`. 

- 3) I was able to open `RouteGuide.sln` in visual studio  and build it without any errors. 

- 4) However, when I try to generate the server code with the protoc, I get the following error:
```
C:\Users\sreek\workspace\grpc\examples\csharp\route_guide>packages\Google.Protobuf.3.0.0-beta2\tools\protoc.exe -I../../
protos --csharp_out RouteGuide --grpc_out RouteGuide --plugin=protoc-gen-grpc=packages\Grpc.Tools.0.7.0\tools\grpc_cshar
p_plugin.exe ../../protos/route_guide.proto
--grpc_out: protoc-gen-grpc: The system cannot find the path specified.
```

- 5) When I try to run RouteGuideServer.exe, I get the following error:
```
C:\Users\sreek\workspace\grpc\examples\csharp\route_guide\RouteGuideServer\bin\Debug>RouteGuideServer.exe
D4/12/2016 5:22:56 PM Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Users\sreek\workspace\grpc\examples\csharp\route_guide\RouteGuideServer\bin\Debug\nativelibs\windows_x86\grpc_csharp_ext.dll"
D4/12/2016 5:22:56 PM Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Users\sreek\workspace\gr
pc\examples\csharp\route_guide\RouteGuideServer\bin\Debug\nativelibs\windows_x86\grpc_csharp_ext.dll"

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'grpcsharp_override_default
_ssl_roots' in DLL 'grpc_csharp_ext.dll'.
   at Grpc.Core.Internal.NativeMethods.PInvokeMethods.grpcsharp_override_default_ssl_roots(String pemRootCerts)
   at Grpc.Core.Internal.DefaultSslRootsOverride.Override(NativeMethods native)
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Routeguide.Program.Main(String[] args) in C:\Users\sreek\workspace\grpc\examples\csharp\route_guide\RouteGuideServ
er\Program.cs:line 47
```

**Comment by manigandham** [comment]
The main "getting started" guide is the best to follow: http://www.grpc.io/docs/ 

It has tabs that show the instructions/code for each specific language and does a great job of walking through all the instructions. The current "basics" tutorials are largely redundant and perhaps better if removed. Tutorials are better suited for showing specific examples or more advanced topics.

There's also an installation section for each language but it's been removed from the sidebar. I believe that section is being redone to point to the example folders in the main grpc project.

Regarding (4), you need to make sure `[Grpc.Tools](https://www.nuget.org/packages/Grpc.Tools/)` is installed via Nuget to download the protobuf and grpc compilers.

**Comment by jtattermusch** [comment]
@sreecha    the problem 5) seems to be unrelated to  the documentation and looks like you VS solution got into a weird state. Perhaps cleaning and rebuilding would help? I am reasonably sure that things actually work (it looks like you're stuck with too old version of grpc.native.csharp for some reason). If the problem persists, please file a separate issue.
