### ISSUE TITLE
Why gRPC server CPU 100% usage

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#6159]
hi guys:

I have a simple stub and a simple server, I test on my server with lots of requests. I found the CPU usage of server easily goes to 100%.

Here is my code, and I'm using Python.

client

```python
while True:
    stub.Touch()
```

server

```python
def Touch(request, context):
    return 'OK'
```

Thanks all.

**Comment by stanley-cheung** [comment]
You are sending 100% as fast as you can. I'd say this is expected
