### ISSUE TITLE
only BUILD file is supplied, but no WORKSPACE file

### ISSUE THREAD

**Issue by chenkan1994** [grpc/grpc#6161]
Hi all:

I've seen that BUILD file has been added to this project, with which bazel can execute compile tasks, but I've not seen any WORKSPACE file, so actually the build will fail because there are some //external targets in BUILD file.

Is there anybody who can add WORKSPACE file and I'll appreciate it!

And by the way, only `objc_grpc_library` was implemented, but I guess lots of people are depending on cc_grpc_library and java_grpc_library. Will you guys please support more languages officially? 

Thanks!

**Comment by chenkan1994** [comment]
@nicolasnoble @jtattermusch Hello everybody! Any updates?

**Comment by chenkan1994** [comment]
@nicolasnoble @jtattermusch 

Could you guys please put WORKSPACE file in? Just like protobuf did.

I'll appreciate it.

**Comment by nicolasnoble** [comment]
I am currently heavily refactoring the build file from the ground up, and I
am adding a workspace for. It just takes some time :-)

**Comment by chenkan1994** [comment]
Any updates buddy? @nicolasnoble

**Comment by jtattermusch** [comment]
no updates here for >1 year. Closing for bankruptcy.

**Comment by chenkan1994** [comment]
Yes, WORKSPACE file is now supplied in this project. Thank you all guys. @jtattermusch
