### ISSUE TITLE
Core data race exposed by tsan/qps_test

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6197]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/7973/config=tsan,language=c++,platform=linux/console

WARNING: ThreadSanitizer: data race (pid=16724)
  Write of size 8 at 0x7d1c0014ffa8 by thread T32 (mutexes: write M50777, write M785):
    #0 free /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:638 (qps_test+0x000000452dd6)
    #1 gpr_free /var/local/git/grpc/src/core/lib/support/alloc.c:68:3 (qps_test+0x00000061fe44)
    #2 internal_destroy_string /var/local/git/grpc/src/core/lib/transport/metadata.c:332:3 (qps_test+0x00000065ac4b)
    #3 grpc_mdstr_unref /var/local/git/grpc/src/core/lib/transport/metadata.c:690:7 (qps_test+0x000000659d08)
    #4 destroy_call /var/local/git/grpc/src/core/lib/surface/call.c:383:7 (qps_test+0x00000063ef97)
    #5 grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:54:7 (qps_test+0x000000633fbd)
    #6 grpc_exec_ctx_finish /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:64:3 (qps_test+0x000000634038)
    #7 grpc_call_destroy /var/local/git/grpc/src/core/lib/surface/call.c:668:3 (qps_test+0x00000063fc01)
    #8 grpc::ClientContext::~ClientContext() /var/local/git/grpc/src/cpp/client/client_context.cc:74:5 (qps_test+0x0000005f3d22)
    #9 grpc::testing::ClientRpcContextStreamingImpl<grpc::testing::SimpleRequest, grpc::testing::SimpleResponse>::~ClientRpcContextStreamingImpl() /var/local/git/grpc/test/cpp/qps/client_async.cc:292:46 (qps_test+0x0000005cda4f)
    #10 grpc::testing::ClientRpcContextStreamingImpl<grpc::testing::SimpleRequest, grpc::testing::SimpleResponse>::~ClientRpcContextStreamingImpl() /var/local/git/grpc/test/cpp/qps/client_async.cc:292:45 (qps_test+0x0000005cda9c)
    #11 grpc::testing::AsyncClient<grpc::testing::BenchmarkService::Stub, grpc::testing::SimpleRequest>::ThreadFunc(grpc::testing::Histogram*, unsigned long) /var/local/git/grpc/test/cpp/qps/client_async.cc:217:9 (qps_test+0x0000005b2e47)
    #12 grpc::testing::Client::Thread::ThreadFunc() /var/local/git/grpc/./test/cpp/qps/client.h:259:38 (qps_test+0x0000005c99b6)
    #13 void std::_Mem_fn<void (grpc::testing::Client::Thread::*)()>::operator()<, void>(grpc::testing::Client::Thread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x0000005cb53b)
    #14 void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_test+0x0000005cb425)
    #15 std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_test+0x0000005cb3a8)
    #16 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_test+0x0000005caefc)
    #17 <null> <null> (libstdc++.so.6+0x0000000b696f)

  Previous read of size 4 at 0x7d1c0014ffa8 by thread T37 (mutexes: write M51452):
    #0 grpc_mdstr_unref /var/local/git/grpc/src/core/lib/transport/metadata.c:687:30 (qps_test+0x000000659cab)
    #1 destroy_call /var/local/git/grpc/src/core/lib/surface/call.c:383:7 (qps_test+0x00000063ef97)
    #2 grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:54:7 (qps_test+0x000000633fbd)
    #3 grpc_exec_ctx_finish /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:64:3 (qps_test+0x000000634038)
    #4 grpc_call_destroy /var/local/git/grpc/src/core/lib/surface/call.c:668:3 (qps_test+0x00000063fc01)
    #5 grpc::ClientContext::~ClientContext() /var/local/git/grpc/src/cpp/client/client_context.cc:74:5 (qps_test+0x0000005f3d22)
    #6 grpc::testing::ClientRpcContextStreamingImpl<grpc::testing::SimpleRequest, grpc::testing::SimpleResponse>::~ClientRpcContextStreamingImpl() /var/local/git/grpc/test/cpp/qps/client_async.cc:292:46 (qps_test+0x0000005cda4f)
    #7 grpc::testing::ClientRpcContextStreamingImpl<grpc::testing::SimpleRequest, grpc::testing::SimpleResponse>::~ClientRpcContextStreamingImpl() /var/local/git/grpc/test/cpp/qps/client_async.cc:292:45 (qps_test+0x0000005cda9c)
    #8 grpc::testing::AsyncClient<grpc::testing::BenchmarkService::Stub, grpc::testing::SimpleRequest>::ThreadFunc(grpc::testing::Histogram*, unsigned long) /var/local/git/grpc/test/cpp/qps/client_async.cc:217:9 (qps_test+0x0000005b2e47)
    #9 grpc::testing::Client::Thread::ThreadFunc() /var/local/git/grpc/./test/cpp/qps/client.h:259:38 (qps_test+0x0000005c99b6)
    #10 void std::_Mem_fn<void (grpc::testing::Client::Thread::*)()>::operator()<, void>(grpc::testing::Client::Thread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x0000005cb53b)
    #11 void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_test+0x0000005cb425)
    #12 std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_test+0x0000005cb3a8)
    #13 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_test+0x0000005caefc)
    #14 <null> <null> (libstdc++.so.6+0x0000000b696f)

  Mutex M50777 (0x7d140019c490) created at:
    #0 pthread_mutex_lock /llvm/projects/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:3319 (qps_test+0x00000043e820)
    #1 __gthread_mutex_lock(pthread_mutex_t*) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9/bits/gthr-default.h:748:12 (qps_test+0x0000005215a6)
    #2 std::mutex::lock() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/mutex:135:17 (qps_test+0x000000523798)
    #3 std::lock_guard<std::mutex>::lock_guard(std::mutex&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/mutex:377:9 (qps_test+0x0000005236f5)
    #4 grpc::testing::Client::Thread::ThreadFunc() /var/local/git/grpc/./test/cpp/qps/client.h:257:37 (qps_test+0x0000005c9954)
    #5 void std::_Mem_fn<void (grpc::testing::Client::Thread::*)()>::operator()<, void>(grpc::testing::Client::Thread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x0000005cb53b)
    #6 void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_test+0x0000005cb425)
    #7 std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_test+0x0000005cb3a8)
    #8 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_test+0x0000005caefc)
    #9 <null> <null> (libstdc++.so.6+0x0000000b696f)

  Mutex M785 (0x000001cf8dc0) created at:
    #0 pthread_mutex_init /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1169 (qps_test+0x000000441a25)
    #1 gpr_mu_init /var/local/git/grpc/src/core/lib/support/sync_posix.c:45:43 (qps_test+0x000000628ecc)
    #2 grpc_mdctx_global_init /var/local/git/grpc/src/core/lib/transport/metadata.c:210:5 (qps_test+0x0000006577d4)
    #3 grpc_init /var/local/git/grpc/src/core/lib/surface/init.c:156:5 (qps_test+0x00000064c9f6)
    #4 grpc_pick_port_using_server /var/local/git/grpc/test/core/util/port_server_client.c:179:3 (qps_test+0x0000005e0f0d)
    #5 grpc_pick_unused_port /var/local/git/grpc/test/core/util/port_posix.c:163:16 (qps_test+0x0000005dff22)
    #6 grpc_pick_unused_port_or_die /var/local/git/grpc/test/core/util/port_posix.c:208:14 (qps_test+0x0000005e0825)
    #7 grpc::testing::RunScenario(grpc::testing::ClientConfig const&, unsigned long, grpc::testing::ServerConfig const&, unsigned long, int, int, int) /var/local/git/grpc/test/cpp/qps/driver.cc:212:23 (qps_test+0x0000004fe17d)
    #8 grpc::testing::RunQPS() /var/local/git/grpc/test/cpp/qps/qps_test.cc:64:7 (qps_test+0x0000004baf96)
    #9 main /var/local/git/grpc/test/cpp/qps/qps_test.cc:76:3 (qps_test+0x0000004bae1e)

  Mutex M51452 (0x7d140019c170) created at:
    #0 pthread_mutex_lock /llvm/projects/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:3319 (qps_test+0x00000043e820)
    #1 __gthread_mutex_lock(pthread_mutex_t*) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9/bits/gthr-default.h:748:12 (qps_test+0x0000005215a6)
    #2 std::mutex::lock() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/mutex:135:17 (qps_test+0x000000523798)
    #3 std::lock_guard<std::mutex>::lock_guard(std::mutex&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/mutex:377:9 (qps_test+0x0000005236f5)
    #4 grpc::testing::Client::Thread::ThreadFunc() /var/local/git/grpc/./test/cpp/qps/client.h:257:37 (qps_test+0x0000005c9954)
    #5 void std::_Mem_fn<void (grpc::testing::Client::Thread::*)()>::operator()<, void>(grpc::testing::Client::Thread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x0000005cb53b)
    #6 void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_test+0x0000005cb425)
    #7 std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_test+0x0000005cb3a8)
    #8 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_test+0x0000005caefc)
    #9 <null> <null> (libstdc++.so.6+0x0000000b696f)

  Thread T32 (tid=16757, running) created by thread T2 at:
    #0 pthread_create /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:954 (qps_test+0x000000457bd3)
    #1 std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) <null> (libstdc++.so.6+0x0000000b6a90)
    #2 grpc::testing::Client::Thread::Thread(grpc::testing::Client*, unsigned long) /var/local/git/grpc/./test/cpp/qps/client.h:230:11 (qps_test+0x0000005c8263)
    #3 grpc::testing::Client::StartThreads(unsigned long) /var/local/git/grpc/./test/cpp/qps/client.h:155:33 (qps_test+0x0000005b2b6d)
    #4 grpc::testing::AsyncStreamingClient::AsyncStreamingClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_async.cc:378:5 (qps_test+0x0000005b1fa8)
    #5 grpc::testing::CreateAsyncStreamingClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_async.cc:538:38 (qps_test+0x0000005b170b)
    #6 grpc::testing::CreateClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:80:27 (qps_test+0x000000521a09)
    #7 grpc::testing::WorkerServiceImpl::RunClientBody(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:206:19 (qps_test+0x000000525df6)
    #8 grpc::testing::WorkerServiceImpl::RunClient(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:131:18 (qps_test+0x00000052264f)
    #9 grpc::Status std::_Mem_fn<grpc::Status (grpc::testing::WorkerService::Service::*)(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()<grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*, void>(grpc::testing::WorkerService::Service*, grpc::ServerContext*&&, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*&&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x0000005adf59)
    #10 std::_Function_handler<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*), std::_Mem_fn<grpc::Status (grpc::testing::WorkerService::Service::*)(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)> >::_M_invoke(std::_Any_data const&, grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2024:9 (qps_test+0x0000005adbe0)
    #11 std::function<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()(grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14 (qps_test+0x0000005ae942)
    #12 grpc::BidiStreamingHandler<grpc::testing::WorkerService::Service, grpc::testing::ClientArgs, grpc::testing::ClientStatus>::RunHandler(grpc::MethodHandler::HandlerParameter const&) /var/local/git/grpc/include/grpc++/impl/codegen/method_handler_impl.h:172:21 (qps_test+0x0000005ae457)
    #13 grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks>) /var/local/git/grpc/src/cpp/server/server.cc:243:7 (qps_test+0x00000060dc13)
    #14 grpc::Server::RunRpc() /var/local/git/grpc/src/cpp/server/server.cc:588:7 (qps_test+0x00000060b44c)
    #15 void std::_Mem_fn<void (grpc::Server::*)()>::operator()<, void>(grpc::Server*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x000000611c3b)
    #16 void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11 (qps_test+0x000000611b71)
    #17 void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::operator()<, void>() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:11 (qps_test+0x000000611aa9)
    #18 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)> >::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2039:2 (qps_test+0x0000006115f0)
    #19 std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14 (qps_test+0x000000601719)
    #20 grpc::DynamicThreadPool::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:81:7 (qps_test+0x0000006005fc)
    #21 grpc::DynamicThreadPool::DynamicThread::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:50:3 (qps_test+0x00000060020b)
    #22 void std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x000000603a1b)
    #23 void std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_test+0x000000603905)
    #24 std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_test+0x000000603888)
    #25 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_test+0x0000006033dc)
    #26 <null> <null> (libstdc++.so.6+0x0000000b696f)

  Thread T37 (tid=16762, running) created by thread T2 at:
    #0 pthread_create /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:954 (qps_test+0x000000457bd3)
    #1 std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) <null> (libstdc++.so.6+0x0000000b6a90)
    #2 grpc::testing::Client::Thread::Thread(grpc::testing::Client*, unsigned long) /var/local/git/grpc/./test/cpp/qps/client.h:230:11 (qps_test+0x0000005c8263)
    #3 grpc::testing::Client::StartThreads(unsigned long) /var/local/git/grpc/./test/cpp/qps/client.h:155:33 (qps_test+0x0000005b2b6d)
    #4 grpc::testing::AsyncStreamingClient::AsyncStreamingClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_async.cc:378:5 (qps_test+0x0000005b1fa8)
    #5 grpc::testing::CreateAsyncStreamingClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_async.cc:538:38 (qps_test+0x0000005b170b)
    #6 grpc::testing::CreateClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:80:27 (qps_test+0x000000521a09)
    #7 grpc::testing::WorkerServiceImpl::RunClientBody(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:206:19 (qps_test+0x000000525df6)
    #8 grpc::testing::WorkerServiceImpl::RunClient(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:131:18 (qps_test+0x00000052264f)
    #9 grpc::Status std::_Mem_fn<grpc::Status (grpc::testing::WorkerService::Service::*)(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()<grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*, void>(grpc::testing::WorkerService::Service*, grpc::ServerContext*&&, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*&&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x0000005adf59)
    #10 std::_Function_handler<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*), std::_Mem_fn<grpc::Status (grpc::testing::WorkerService::Service::*)(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)> >::_M_invoke(std::_Any_data const&, grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2024:9 (qps_test+0x0000005adbe0)
    #11 std::function<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()(grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14 (qps_test+0x0000005ae942)
    #12 grpc::BidiStreamingHandler<grpc::testing::WorkerService::Service, grpc::testing::ClientArgs, grpc::testing::ClientStatus>::RunHandler(grpc::MethodHandler::HandlerParameter const&) /var/local/git/grpc/include/grpc++/impl/codegen/method_handler_impl.h:172:21 (qps_test+0x0000005ae457)
    #13 grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks>) /var/local/git/grpc/src/cpp/server/server.cc:243:7 (qps_test+0x00000060dc13)
    #14 grpc::Server::RunRpc() /var/local/git/grpc/src/cpp/server/server.cc:588:7 (qps_test+0x00000060b44c)
    #15 void std::_Mem_fn<void (grpc::Server::*)()>::operator()<, void>(grpc::Server*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x000000611c3b)
    #16 void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11 (qps_test+0x000000611b71)
    #17 void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::operator()<, void>() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:11 (qps_test+0x000000611aa9)
    #18 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)> >::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2039:2 (qps_test+0x0000006115f0)
    #19 std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14 (qps_test+0x000000601719)
    #20 grpc::DynamicThreadPool::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:81:7 (qps_test+0x0000006005fc)
    #21 grpc::DynamicThreadPool::DynamicThread::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:50:3 (qps_test+0x00000060020b)
    #22 void std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_test+0x000000603a1b)
    #23 void std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_test+0x000000603905)
    #24 std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_test+0x000000603888)
    #25 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_test+0x0000006033dc)
    #26 <null> <null> (libstdc++.so.6+0x0000000b696f)

SUMMARY: ThreadSanitizer: data race /var/local/git/grpc/src/core/lib/support/alloc.c:68:3 in gpr_free

**Comment by vjpai** [comment]
I can look at this after 4/20 if it's still around then.

**Comment by ctiller** [comment]
I just saw this independently. I understand the bug and think I have a plan to fix it.
