### ISSUE TITLE
Memory Leak from gRPC client to disconnected Server

### ISSUE THREAD

**Issue by johnco3** [grpc/grpc#6234]
I tried sending an RPC request from a grpc client to a powered off server from localhost->localhost on a Windows environment (I did not test this on another environment).  The output from the console is shown below.

Note I am using the latest master branch code as or April-15th, and I am not sure whether it is relevant, but I also set a 5 second timeout in the ClientContext. 

E0415 12:42:11.471000000 15916 tcp_client_windows.c:106] on_connect error connecting to 'ipv6:[::1]:50051': No connection could be made because the target machine actively refused it.

E0415 12:42:12.472000000 15916 tcp_client_windows.c:106] on_connect error connecting to 'ipv4:127.0.0.1:50051': No connection could be made because the target machine actively refused it, however it loo

```
D0415 12:42:13.503000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:14.503000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:15.503000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:16.504000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:17.504000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:18.505000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:19.505000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:20.505000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:21.505000000 15916 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0415 12:42:22.505000000 15916 iomgr.c:117] Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0415 12:42:22.505000000 15916 iomgr.c:80] LEAKED OBJECT: client:socket=0x000000
00002B0160 00000000002B0228
```

Client code as follows:

```
std::unique_ptr<ca::Response>
CAClient::getMaintenanceOTPMessage() const
{
    ClientContext context;
    context.set_deadline(
        system_clock::now() +
        milliseconds(5000));
    google::protobuf::Empty empty;
    ca::Response message;
    std::unique_ptr<ca::Response> result;
    auto status = stub_->GetMaintenanceOTPMessage(&context, empty, &message); 

```

**Comment by sunwangme** [comment]
nobody want to fix it?

**Comment by ctiller** [comment]
I believe this was fixed recently.

**Comment by johnco3** [comment]
Thanks, I can confirm that the behavior that I was seeing before is no
longer present.

John
