### ISSUE TITLE
Performance testing: Revive 0.7x load and use all cores

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6237]
Dynamically decide how many cores are available and use all of them in the core limits
Revive a method for cleanly getting 0.7x load test that was lost in #6235 .

**Comment by vjpai** [comment]
This is now an issue on performance master because the tests are only using 4 cores but before they were using 8. This affects the reported QPS numbers.

**Comment by vjpai** [comment]
Current status is that the performance experiment now uses separate VMs for client and server, and we use different VMs for different core sizes rather than using the core limit option (since VM-level limits are more multilingual and reliable). Reviving the 0.7x load has not yet happened.

**Comment by jtattermusch** [comment]
this issue has been inactive for long time, closing for bankruptcy.
