### ISSUE TITLE
Python: Make adding a new RPC to .proto file non-breaking for client stub implementations (client-side)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6264]
Analogous to #6263, but for the client-side stubs (and somewhat more delicate).

The problem here could be that manual implementations (written by users e.g. for testing) of the client stub interface could break if a new methods gets added to a .proto file. Problematic if  .proto file (and the generated code) are shipped as a pip package.

Related C# issue: #5416

**Comment by soltanmm** [comment]
Fixed in #6330.
