### ISSUE TITLE
Remove legacy grpc.framework.face package

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6273]
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/framework/crust/implementations.py#L162
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/framework/interfaces/face/face.py#L672

If we decide not to change the public interface, we can remove this from GA milestone.

**Comment by kpayson64** [comment]
I was looking at an older version, this is a non-issue.

**Comment by kpayson64** [comment]
Found the source of the confusion:

https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/framework/face/interfaces.py

defines a different face.GenericStub

If this is legacy code, can it be removed?

**Comment by nathanielmanistaatgoogle** [comment]
It is legacy code; I want to remove it but since it's not actively hurting anything I've been slow to get around to it.

**Comment by nathanielmanistaatgoogle** [comment]
This was addressed in #6331.
