### ISSUE TITLE
how to get grpc method option

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#6276]
hi guys:

I have a simple grpc server called server.proto

code below:

```
extend google.protobuf.MethodOptions {
    Message msg = 50056;
}

message Message {
    string tool = 1;
}

service Hello {
    rpc Say(Request) returns (Response) {
        option (msg).tool = "telephone";
    }
}
```

This could genertate file called server_pb2.py

But how to get method Say Option "tool" ?

Thanks

**Comment by soltanmm** [comment]
I don't think we support this yet... It should be a purely additive change though AFAICT.

**Comment by GuoJing** [comment]
hi @soltanmm , I have simple but dirty way to get the option in Python.

```python
# pb2 is module object equals import server_pb2
# import server_pb2
# get_service_identify_from_pb_file(server_pb2)

def get_service_identify_from_pb_file(pb2):
    method_mapping = dict()
    p = descriptor_pb2.FileDescriptorProto()
    pb2.DESCRIPTOR.CopyToProto(p)
    for s in p.service:
        for m in s.method:
            if not method_mapping.get(m.name):
                method_mapping[m.name] = dict()
            for k, v in m.options._fields.items():
                if hasattr(v, '_fields'):
                    for i, j in v._fields.items():
                        method_mapping[m.name][i.name] = j
    return method_mapping

# returns {'Hello': {'method': 'GET'}}
```

**Comment by arthur-tacca** [comment]
Wow, that's really useful code @GuoJing. It's also possible to get the request/response types and streaming type for each RPC by using the other members of the method descriptor, which is the object in the variable "m".

My previous searches for "Python gRPC reflection" had led me to believe that getting that information was planned but not currently possible. (I now realize the other results were for the case you want to get information about a service without access to its .proto, unlike my situation.) Perhaps this code could be documented a bit more prominently?

**Comment by ryanchou1991** [comment]
+1 I have struggled on it for hours. The issue's answer help me figure it out. Is there any other pythonic way to support the custom method options? I thought the feature were so siginificant to use.

**Comment by jtattermusch** [comment]
Closing as this is more a question than an issue.
