### ISSUE TITLE
Please add important Makefile target (uninstall)

### ISSUE THREAD

**Issue by mtojek** [grpc/grpc#6288]
Hi,

I needed sources to build grpc project and unfortunately I noticed that there is no target supporting uninstallation.
Please add a `make uninstall` target to the project Makefile.

Kind regards,
Marcin

**Comment by aaronjheng** [comment]
There is a PR #4914 about this issue.

**Comment by nfultz** [comment]
I would also like this.

**Comment by jtattermusch** [comment]
This issue has been inactive for too long and we have no immediate plans for addressing this, so closing.
