### ISSUE TITLE
php cleanup fails if timeout is set

### ISSUE THREAD

**Issue by joyrex2001** [grpc/grpc#6293]
When a timeout is set on the Grpc\Call object, with a deadline configured, the cleanup of objects seem to fail. I don't know how to catch this in a unit-test, but consider the following code:

```php
class BaseStubTest extends PHPUnit_Framework_TestCase
{
    public function testTimeout()
    {
        $channel = new Grpc\Channel('localhost:56789',[]);
        $now = Grpc\Timeval::now();
        $delta = new Grpc\Timeval(10000);
        $deadline = $now->add($delta);
        $call = new Grpc\Call($channel, 'abc', $deadline);
        $event = $call->startBatch([
            Grpc\OP_SEND_INITIAL_METADATA => [],
            Grpc\OP_RECV_INITIAL_METADATA => true,
            Grpc\OP_SEND_MESSAGE => ['message' => ''],
            Grpc\OP_SEND_CLOSE_FROM_CLIENT => true,
        ]);
        // cleanup fails -> channel_destroy crashes?
    }
}
```

When this is ran with the GRPC_API=trace environment variable enabled, you will notice that the channel_destroy takes a more than average time to complete, and more interesting, this is also the last call logged. Even the grpc_shutdown(void) is missing.

**Comment by stanley-cheung** [comment]
This should be resolved by #7154. 

Note that `grpc_shutdown()` is indeed being called at shutdown by `PHP_MSHUTDOWN_FUNCTION`. It is just that any log somehow never made it out to stdout.

Please re-open if you still see issue. You may need to wait for a 0.15.1 release.
