### ISSUE TITLE
Write hello-world example for compression

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#6297]

**Comment by lumpidu** [comment]
ping :)

**Comment by dgquintas** [comment]
Pong :) Sorry. I'll try Very Hard (tm) to get this in this week.

**Comment by dgquintas** [comment]
I have *not* forgotten about this, despite all evidence to the contrary... >_<

**Comment by 24** [comment]
long long year go ..............

**Comment by dgquintas** [comment]
Good things come to those who wait. Fixed in #11402

**Comment by dgquintas** [comment]
Also, years are all the same length, except for leap years. Last year was one, so I guess you are technically correct in that it was "a long year ago"

**Comment by atomextranova** [comment]
@dgquintas I am sorry to bother you again, but in #11402 I only saw commits related to create new util functions for parsing strings to actual compression levels, Could you please show me a complete helloworld example, better with illustration about how to use ServerBuilder::SetDefaultCompressionAlgorithm or ServerBuilder::SetDefaultCompressionLevel?

**Comment by 24** [comment]
i found  solution ,  when go client  say hello  to  java server  used gizp compression

 lost this  

```
	md := metadata.Pairs("grpc-accept-encoding", "gzip", "grpc-encoding", "gzip")
	ctx := metadata.NewContext(context.Background(), md)
```

**Comment by 24** [comment]
@dgquintas    
 
```
long long year go
```

that's a funny  joke     :)

**Comment by atomextranova** [comment]
However I am trying to find a C++/python version of solution. They have totally different interface. Do you have any ideas? @24

**Comment by 24** [comment]
@atomextranova 
sorry ，I'm not use python or c++.   (我不用这两个，帮不了)     
:)

**Comment by 24** [comment]
@atomextranova  
when      200kb or 600 kb > body size >1kb   ,  used gizp 
i have pref test ,, compress is not better ( in spite of  network  IO  just 25%-40% , but cpu is very 
 hight)
so  i  not used compress 
but you can try do this
