### ISSUE TITLE
Channel should provide a CancellationToken

### ISSUE THREAD

**Issue by FrankGrossmann** [grpc/grpc#6311]
The Channel should provide a CancelationToken. (currently there is only a protected shutdownRequested field) For example the application requests a shut down and different requests and maybe also a stream is running I can pass the CancellationToken (may combined with another local CancelationToken) to the Method in order to cancel the current request or stream and unblock the Channel.ShutdownAsync method.

**Comment by jtattermusch** [comment]
Thanks for the suggestion, exposing a cancellation token seems like it can be useful in a number of cases.

(Btw, at this point ShutdownAsync doesn't really wait for outstanding calls to finish)
