### ISSUE TITLE
Provide NuGet packages with signed assemblies

### ISSUE THREAD

**Issue by FrankGrossmann** [grpc/grpc#6312]
In Enterprise environment assemblies are often signed and it is not possible to mix signed and unsigned assemblies. Please provide such a Package

**Comment by jtattermusch** [comment]
The assemblies in the current nuget package are supposed to be signed. Isn't that the case?

**Comment by FrankGrossmann** [comment]
I will check this again!

**Comment by jtattermusch** [comment]
Please reopen if you find out the assemblies aren't signed.
