### ISSUE TITLE
Deadline in Streaming request interrupts stream

### ISSUE THREAD

**Issue by FrankGrossmann** [grpc/grpc#6314]
If you call a method with a stream response and a deadline, the returned response will be interrupted when the deadline is exceeded. Is this a Bug or a Feature?

**Comment by jtattermusch** [comment]
What language are you using? Can you provide a snippet that demostrates this?

**Comment by FrankGrossmann** [comment]
We using c# with grpc 0.13 (latest from nuget)

**Comment by jtattermusch** [comment]
When the per-call deadline elapses, the call gets automatically cancelled (which obviously breaks the request/response stream). So from that perspective this is a feature.
