### ISSUE TITLE
General flakiness with Windows C tests

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#6319]

**Comment by yang-g** [comment]
concurrent_connectivity_test.exe is flaky: https://grpc-testing.appspot.com/job/gRPC_pull_requests/8739/config=dbg,language=c,platform=windows/

**Comment by a11r** [comment]
saw more instances of this failure:
https://grpc-testing.appspot.com/job/gRPC_master/config=dbg,language=python,platform=windows/

**Comment by a11r** [comment]
Also failing on portability_master: https://grpc-testing.appspot.com/job/gRPC_portability_master/2222/testReport/

**Comment by adelez** [comment]
h2_ssl_test.exe flakes on windows_x86_vs2015
https://grpc-testing.appspot.com/job/gRPC_portability_master/language=c,scenario=windows_x86_vs2015/2318/console
