### ISSUE TITLE
ios  grpc not support dynamic library 

### ISSUE THREAD

**Issue by izouxv** [grpc/grpc#6332]
# use_frameworks!
pod 'gRPC', '~> 0.12.0'
not work

my project is swift lang, i pod grpc and reactivecocoa, grpc not work. many header can't find

**Comment by BenchR267** [comment]
grpc does not have support for dynamic frameworks currently. But you can import it as a static library and use it in your swift project via the bridging header.

**Comment by jcanizales** [comment]
Closing as this got resolved for 1.0.0.
