### ISSUE TITLE
Many interop tests failing on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6337]
https://grpc-testing.appspot.com/job/gRPC_interop_master/4271/#showFailuresLink  since build 4256.

Majority of the tests involve Java, was there a change in grpc-java that introduced the breakage?

**Comment by nmittler** [comment]
Hmm ... looking over the commits from yesterday, https://github.com/grpc/grpc-java/commit/8825f355dfd9b72622769388500f71f8b472e57f looks suspicious.

@carl-mastrangelo can you take a look?

**Comment by jtattermusch** [comment]
Thanks Nathan! The Java PR might be https://github.com/grpc/grpc-java/pull/1726.  Our last green build was yesterday at 2:07PM and https://github.com/grpc/grpc-java/pull/1726 was merged at 2:17PM.

**Comment by jtattermusch** [comment]
We think we know the route cause and it will get fixed within the next few hours.

**Comment by jtattermusch** [comment]
Seems fixed now. Thanks java team for handling this quickly.
