### ISSUE TITLE
Unable to build npm package (Node 6.0.0, Windows 10 x64)

### ISSUE THREAD

**Issue by jrick** [grpc/grpc#6338]
Error output: http://sprunge.us/GWQC

**Comment by murgatroid99** [comment]
We have not yet published precompiled binary packages for Node 6, so for now you will need to compile the package. First you need to follow the setup instructions for `node-gyp`: https://github.com/nodejs/node-gyp#installation. If you get that working, you will probably get a lot of compiler errors the first time you try to build. If you do, one of the first messages will indicate that you need to delete a particular folder to make compilation work.

**Comment by cyrfer** [comment]
I am struggling to get [a project](https://cloud.google.com/nodejs/getting-started/using-cloud-datastore#download_and_run_the_app) to install  on Windows and I think I tracked it down to this issue. I posted [over there](https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/58) also.

**Comment by ace-n** [comment]
I believe the precompiled binary for Node 6 has been published - @murgatroid99 can you confirm/deny this?

**Comment by murgatroid99** [comment]
Yes, you're right. We have been publishing precompiled binaries for Node 6 since version 0.14.
