### ISSUE TITLE
Comments from .proto file should appear in the code generated by grpc_objc_plugin

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6344]
This should be easily done when utilizing the GetComment methods added in #6181.

**Comment by jayantkolhe** [comment]
We need to propogate comments from proto to generated Obj-C code and run Obj-C docgen of some kind on it.

**Comment by makdharma** [comment]
PR https://github.com/grpc/grpc/pull/6841

**Comment by jcanizales** [comment]
I think there's a duplicate of this issue somewhere.
