### ISSUE TITLE
linux_x64_gcc4.4: gpr_log_test is consistently failing.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6349]
https://grpc-testing.appspot.com/job/gRPC_portability_master/1896/language=c,scenario=linux_x64_gcc4.4/testReport/(root)/tests/bins_dbg_gpr_log_test/

```
D0428 19:20:26.882602819   13702 test_config.c:278]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
D0428 19:20:26.882701710   13702 log_test.c:73]              hello world
I0428 19:20:26.882708145   13702 log_test.c:74]              hello world
E0428 19:20:26.882712314   13702 log_test.c:75]              hello world
```

Reproduce 

`tools/run_tests/run_tests.py --use_docker -l c -c dbg --arch x64 --compiler gcc4.4`

**Comment by a11r** [comment]
Still failing: https://grpc-testing.appspot.com/job/gRPC_portability_master/2222/testReport/

**Comment by vjpai** [comment]
Subsumed by #6861.
