### ISSUE TITLE
Swift example app does not run

### ISSUE THREAD

**Issue by jorgeolivero** [grpc/grpc#6358]
The Swift example here does not run for me: https://github.com/grpc/grpc/tree/master/src/objective-c/examples/SwiftSample

Running:

``` bash
$ git clone https://github.com/grpc/grpc.git
$ cd grpc
$ git submodule update --init
$ cd src/objective-c/examples/SwiftSample
$ pod install
```

.. and then running the application on the simulator or a physical phone through xcode results in 999+ errors which look like this:

<img width="1552" alt="screen shot 2016-04-29 at 12 19 31 am" src="https://cloud.githubusercontent.com/assets/3119712/14908088/18907f7e-0da0-11e6-8150-74af767fdab4.png">

I stumbled upon this in an attempt to debug and handle the exact same set of errors in a personal swift app. Oddly enough, in my personal app the failure to run only occurs on a physical device -  when running through the simulator I am able to make connections/requests to my grpc server.

For context:

``` bash
$ protoc --version
libprotoc 3.0.0

$ brew install --without-libgrpc grpc
Warning: grpc/grpc/grpc-0.13.0 already installed
```

Xcode is v `7.3`

This is likely related to #4027

**Comment by jorgeolivero** [comment]
Another note that could help, the RouteGuideClient in the examples (which is objc based) runs for me on the simulator and physical device

**Comment by BenchR267** [comment]
Hey, I had the issues as well in my projects. I don't know where they are coming from, but I 'fixed' it by cleaning the project and making a pod install with version 0.39 like 'pod _0.39_ install'

**Comment by mehrdada** [comment]
This issue looks like it might be fixed. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
