### ISSUE TITLE
Run unit tests against alternative PHP versions.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6366]
This basically means adding `run_tests.py -l php --compiler phpX.X` suport for PHPLanguage in run_tests.py. We've done that for other languages already, so this should be pretty straightforward.

Once we have this, we can populate the portability matrix accordingly.

**Comment by jtattermusch** [comment]
Are we actually doing other PHP versions for GA?

**Comment by thinkerou** [comment]
Do gRPC need to use `PHP Version Management` like nvm of node? The tools have [php-version](https://github.com/wilmoore/php-version) and [phpbrew](https://github.com/phpbrew/phpbrew) and so on.

**Comment by jtattermusch** [comment]
Looks like we will not officially support PHP7 for GA, and we are already running php tests for PHP5, so I think we can remove the milestone.

**Comment by thinkerou** [comment]
OK, I have completed using PHP5.5 or PHP5.6, but if gRPC will not support PHP7, I think it supports PHP5.5 and PHP5.6 which will be usefulness.

**Comment by smolinari** [comment]
What is the reasoning behind not supporting php7, if I may ask?

Scott

**Comment by Rastusik** [comment]
AFAIK general PHP 5.5 support has already ended, or ends in a couple of days, so the only usable PHP version will be 5.6. Any plans on when the PHP 7 version might be supported eventually?

**Comment by thinkerou** [comment]
Will be supported if https://github.com/grpc/grpc/pull/7464 done.

**Comment by stanley-cheung** [comment]
php7 tests are now being run for
 - master
 - interop master
