### ISSUE TITLE
Can't build with msys on Windows

### ISSUE THREAD

**Issue by tomq42** [grpc/grpc#6367]
I don't know whether I'm supposed to be able to build using msys (commit comments appear to indicate that this might be possible), but with master as of 29/04/2016, I get:

makefile:3430: **\* multiple target patterns.  Stop.

Should it build with msys?

I can't build with msys OR visual studio on Windows.

**Comment by nicolasnoble** [comment]
The instructions / documentation / commits refer to msys2, and not msys. The Makefile should work with plain msys2 using the command `CPPFLAGS="-mwin32 -D_WIN32_WINNT=0x600" make static_c`, and with mingw64 under msys2 using the command `CPPFLAGS="-D_WIN32_WINNT=0x600" make static_c`.

**Comment by nicolasnoble** [comment]
Also, the tests currently won't build under msys2.

**Comment by tomq42** [comment]
I am using msys2 64 (version 20160205). With the command 
CPPFLAGS="-mwin32 -D_WIN32_WINNT=0x600" make static_c

I get the "multiple target patterns" error.

The experience of getting up and running with grpc on Windows is poor. I find it hard to believe that this is not a supported platform.

**Comment by tomq42** [comment]
This is caused by the BUILDDIR_ABSOLUTE variable containing a :, as a result of $(abspath) returning a windows style directory name. ("C:/blah")

I can get past this error if I modify the line:
BUILDDIR_ABSOLUTE = $(abspath $(BUILDDIR))
to read:
BUILDDIR_ABSOLUTE = $(BUILDDIR)

and pass on the command line
BUILDDIR=./

However it then fails during compilation, so I suspect that this is a dead end route anyway.

**Comment by zakkor** [comment]
More than 1 year later, still can't compile on windows.

**Comment by jtattermusch** [comment]
We will work on fixing msys build only after fixing the existing cmake issues as cmake is our primary way to build on windows.
