### ISSUE TITLE
Provide Access to inner Array of RepeatedField<T>

### ISSUE THREAD

**Issue by FrankGrossmann** [grpc/grpc#6390]
For performance reasons would be nice to have access to the underlying array when I receive it as a part of the response message.  Else I need to use copy to but this is made with Array.Copy instead Buffer.BlockCopy which is faster. Also it would be nice to initialize my RepeatedField<T> with a existing T[] instead of generating a inner copy.

The use case is some low level methods wants to have direct arrays or Array instead IList<T> or IList. Best example is Buffer.BlockCopy, Array.Copy or Stream.Read/Write  methods.

**Comment by hsaliak** [comment]
Is this an optimization intended for protobuf code or for gRPC code?

**Comment by jtattermusch** [comment]
I think it's intended for protobuf. Not gRPC related, so closing.
