### ISSUE TITLE
Obj-C swift example needs a README.md explaining its current status

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#6392]
https://github.com/grpc/grpc/tree/master/src/objective-c/examples/SwiftSample currently does not work.
We need a readme explaining it's current status.
- When it works
- Restrictions / Caveats

/cc @makdharma

**Comment by makdharma** [comment]
@y-zeng Please confirm the status with Xcode 7.2, 7.3 etc.

**Comment by y-zeng** [comment]
It works with Xcode 7.2.
In Xcode 7.3, it fails at `RPC.requestHeaders["My-Header"] = "My value"` with error `Cannot assign through subscript: subscript is get-only`

**Comment by jcanizales** [comment]
Yep. See https://github.com/grpc/grpc/pull/6346

**Comment by makdharma** [comment]
@y-zeng Can you just copy PR #6346 and resubmit it after adding the TODO that @jcanizales mentioned in the comment? For some reason I am not able to trigger testing on that PR, so hoping that your change will go through Jenkins testing instead.

**Comment by jcanizales** [comment]
No need to copy it, just add @ishkawa's grpc repo as a remote of yours, and you can work off his `fix-swift-sample-compile-error` branch. The nice thing about doing it that way is that his commit is still attributed to him, and your changes are commits on top of that.

**Comment by y-zeng** [comment]
Looks like I do not have the permission to push to @ishkawa's grpc repo. Should I create a new pull request from my repo? @ishkawa's commits will still credit to him in the new pull request.

**Comment by jcanizales** [comment]
Yes :)

**Comment by makdharma** [comment]
@y-zeng I merged PR #7029 . Can this bug be closed now?

**Comment by y-zeng** [comment]
Just confirmed swift sample in the master branch now works with Xcode 7.3
