### ISSUE TITLE
make verify-install doesn't think I have protobuf 3.0.0+, but I do

### ISSUE THREAD

**Issue by tomq42** [grpc/grpc#6408]
Trying to get grpc up and running on my machine (any way I can...).
I've cloned the git repo (6bac7d3467c99dccc30e8447bc84237bb54b99fe).
I've done:
git submodule update --init
make
make install

I get:
We couldn't find protoc 3.0.0+....

Since the grpc install instructions say it downloads and builds protobuf automatically, I thought this was odd.

I tried a few more things.
I tried manually running "make install" from within third-party/protobuf. Same result.
I tried cloning and building the latest master protobuf. Same result.

Investigating, the grpc Makefile runs "protoc --version", then looks  for "libprotoc.3". If I manually run "protoc --version" I get "libprotoc 3.0.0". So the Makefile seems to have a bug in it. Being only a grpc newbie I have no idea what the implications if this are. Maybe it hasn't built properly, who knows.

I don't understand what I'm doing wrong here. I am failing to get a copy of grpc built cleanly whichever way I turn.

**Comment by tomq42** [comment]
Apologies, it's not the protoc version check that's failing, it's the protobuf version check.
To be honest I'm jumping on anything because I have no confidence at all that what I've got is supposed to work.

It's attempting to run:
 pkg-config --atleast-version=3.0.0-alpha-3 protobuf

That produces no output for me. 

Investigating that, the version I have, the version that the build of grpc itself installed, is 
3.0.0-beta-2

I don't know what the pkg-config version comparison rules are, but I suspect that 
--atleast-version=3.0.0-alpha-3 
doesn't match 
3.0.0-beta-2

**Comment by sansna** [comment]
Agreed. Mine is cloned from github, and compiled version of protobuf is 3.0.0, which is failing, because of its mis-match to 3.0.0-alpha-3 version, which I think is bull-shit. It's 3.0.0-GA version I think. But changing the protobuf.pc file's Version key value (tried 3.0.0-alpha-3, 3.0.0-beta-4, 3.0.0-GA) doesn't get me anywhere..
Any guidance is appreciated.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.

**Comment by faizalkassamalisc** [comment]
Follow instructions here to curl and unzip protobuf: https://gist.github.com/rvegas/e312cb81bbb0b22285bc6238216b709b

Then run pkg-config to check for protobuf and it doesn't work. Need a better way to check for protobuf such as using which or 'protobuf --version'
