### ISSUE TITLE
(C#) Hard to tell that a channel has been shut down

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#6426]
I'm writing tests to make sure I'm shutting channels down properly. I'd expect the `State` enum to have a value for `Shutdown`, but I don't see one... but *requesting* the state after shutting the channel down throws an exception ("Safe handle has been closed").

**Comment by jskeet** [comment]
(Suggest assigning @jtattermusch)

**Comment by jtattermusch** [comment]
I think exposing a CancellationToken as suggested here might also be useful - as suggested here:  #6311
