### ISSUE TITLE
Can not install on Linux due to dependency

### ISSUE THREAD

**Issue by timanovsky** [grpc/grpc#6427]
Bundler says: `Could not find google-protobuf-3.0.0.alpha.5.0.5.1 in any of the sources`. If you check https://rubygems.org/gems/google-protobuf/versions it has only Mac version

**Comment by blowmage** [comment]
This looks to be fixed. I'm seeing version [3.0.0.alpha.5.0.5.1 available on all platforms](https://rubygems.org/gems/google-protobuf/versions).

**Comment by timanovsky** [comment]
Works for me too

Best regards,
Alexey Timanovsky.

**Comment by blowmage** [comment]
@timanovsky Great! Can you close this issue then?
