### ISSUE TITLE
Ruby buildartifacts on linux_x64 and mac_x64 is broken.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6432]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/706/architecture=x64,language=ruby,platform=linux/console

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/706/architecture=x64,language=ruby,platform=macos/console

**Comment by murgatroid99** [comment]
It looks like the Windows cross-compiler is failing to compile zlib, and the Mac compiler can't find `memset_s`.

**Comment by murgatroid99** [comment]
The Ruby build appears to be succeeding now
