### ISSUE TITLE
src/node/extension_binary/grpc_node.node does not exist / fails to compile

### ISSUE THREAD

**Issue by 1N50MN14** [grpc/grpc#6435]
grpc `0.13.2-pre1`
node `4.4.3`
OS `Ubuntu 14.04.3 LTS`

When using grpc as a sub-dependency of a dependency `grpc_node.node` fails to exit, whereas it compiles successfully when using grpc as a first level dependency.

**Comment by murgatroid99** [comment]
What do you mean by "fails to exit"?

**Comment by 1N50MN14** [comment]
When requiring grpc, node throws an error `"Cannot find module 'PATH_TO/grpc/src/node/extension_binary/grpc_node.node'"` because `extension_binary/grpc_node.node` does not exist

**Comment by murgatroid99** [comment]
What version of npm are you using (`npm -v`)?

**Comment by 1N50MN14** [comment]
2.15.1

**Comment by murgatroid99** [comment]
I am having trouble reproducing this problem with those exact versions. Do you do anything to disable scripts when installing? Do you get any output about grpc when you run `npm install`?

**Comment by 1N50MN14** [comment]
@murgatroid99 I'm running this inside a docker container, I'll create a gist with Dockerfile to reproduce this, few minutes

**Comment by 1N50MN14** [comment]
https://github.com/1N50MN14/gtest

`git clone`, chmod and `./build.sh`, `./run.sh` and you'll see the error

**Comment by murgatroid99** [comment]
The output from the docker build includes the following:

```
npm WARN cannot run in wd grpc@0.13.2-pre1 node-pre-gyp install --fallback-to-build (wd=/src/node_modules/grpc-dep/node_modules/grpc)
```

I don't know why that's just a warning, but that's where it's failing to create the `grpc_node.node` file.

You can fix this error by changing the `npm install` line in the Dockerfile to `npm install --unsafe-perm`.

npm dislikes running install scripts as root, and you need to pass that parameter to tell it that you definitely want it to do so.

**Comment by 1N50MN14** [comment]
Oh I see, this fixed the issue indeed. Ok then closing issue as this is npm/Docker specific, thanks for the help!

**Comment by AlphaNerd** [comment]
Definitely did the trick. Thanks @murgatroid99

**Comment by tuber** [comment]
npm -v
3.5.2
node -v
v4.2.6
cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

/home/tb/tbdown/grpc/examples/node/dynamic_codegen# node greeter_server.js 
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/tb/tbdown/grpc/examples/node/node_modules/grpc/src/node/extension_binary'
