### ISSUE TITLE
Fix Node server crash when echoing objects

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#644]
Currently, if a server tries to write an object that it has read, it crashes with an error about type mismatches from the ProtoBuf.js library. As far as I can tell, the root cause is dcodeIO/ProtoBuf.js#238.

**Comment by tbetbetbe** [comment]
<ping> I thought this got resolved ?

**Comment by murgatroid99** [comment]
No, this hasn't been fixed.

**Comment by murgatroid99** [comment]
This will be a lot easier to resolve when dcodeIO/Protobuf.js#248 is accepted and published.
