### ISSUE TITLE
Make sure the Node library works on AWS Lambda

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#6443]
Someone tried to do this, and it failed with a vague error (GoogleCloudPlatform/gcloud-node#1287). The [AWS documentation](https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/) indicates that this should work, and it probably just requires a little tweaking.

**Comment by ajagnanan** [comment]
any luck yet?

**Comment by murgatroid99** [comment]
I haven't really started investigating this yet. I have more pressing issues to handle. I expect to work on this after the 1.0 release.

**Comment by talolard** [comment]
Any news on this?

**Comment by jordanarseno** [comment]
:+1:

**Comment by JosephusYang** [comment]
I ran into the same problem and used a [docker image](https://github.com/lambci/docker-lambda) to install npm module, and it works now (at least for cloud storage), hope this workaround help someone with this problem

**Comment by ajagnanan** [comment]
Thats what i had to do also. Add a `package.json` file in a folder, then run ```
docker run --rm -it -v "$PWD":/worker -w /worker node:4.2 npm i --production --silent``` in that folder. You should see a node_modules folder when its finished with the dependencies.

**Comment by jpamorgan** [comment]
@murgatroid99 any luck on this yet?  I am trying to get Google Firestore running on lambda, but it craps out with this grpc issue.

**Comment by bradennapier** [comment]
The build for the next version appears to resolve this

https://storage.googleapis.com/firebase-admin-node/firebase-admin-5.4.3-rc0.tgz

**Comment by muxi** [comment]
@murgatroid99 is this resolved?

**Comment by murgatroid99** [comment]
No. I believe this works, but I haven't actually done the necessary tests.

**Comment by vespertilian** [comment]
I am also having trouble using GRPC on Lambda.

My issue, which I hope is the same/similar to others is that I am using a Mac and node v6.10.0. When I install GRPC with NPM it installs the "node-v48-darwin-x64-unkown" binary. It will install whatever node version and operating system combination you have. 

Lambda however wants the: "node-v48-linux-x64-glibc" binary. As lambda is built on Linux. 

As GRPC uses "node-pre-gyp" I believe it should be possible to force the installation of the Lambda, and the download of the compatible binary, which can then be deploy along side your lambda function. 

Something like this

`npm rebuild grpc --target=6.1.0 --target_arch=x64 --target_platform=linux`

Currently running this however does not seem to find a pre-built binary as it targets this url:

`https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v48-linux-x64-unknown.tar.gz`

not this url

`https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v48-linux-x64-glibc.tar.gz`

*note the -glibc in place of -unknown*

Manually copying the file from the second url into my:

`node_modules/grpc/src/node/extensions_binary/node-v48-linux-x64-gblibc`

Made GPRC work in Lambda upon deployment.

Kinda clunky however.

Not sure what a good long term solution is. Ideally you want the local binary and the lambda binary installed when you want to use GRPC on lambda. So you can test locally, and it will also work when deployed to Lambda.

**Comment by murgatroid99** [comment]
The `npm rebuild` command you have there should almost work. If you add `--target_libc=glibc`, that should do it.

**Comment by vespertilian** [comment]
@murgatroid99 Thanks that worked

`npm rebuild grpc --target=6.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc`

Will instal the correct binary for deployment. I think I will just try to run it automatically as a build step for my project before deployment.

**Comment by vespertilian** [comment]
This command seems to work well as a package.json post install step. 

```json
{
  "main": "index.js",
  "scripts": {
    "postinstall": "npm rebuild grpc --target=6.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc"
  },
}
`

**Comment by pflugs30** [comment]
@vespertilian I'm having the same problem you describe above.  I'm developing on an x64 Windows laptop.  I'm trying to build a Lambda function that pulls data from a Google Cloud PubSub topic.  I'm using [serverless](https://serverless.com) to build and deploy the Lambda function.

I was able to use the command you wrote to rebuild the gRPC binary in the node_modules folder.  The function also runs locally when I use `serverless-offline`.  When I run `serverless deploy` to push my function into the AWS Lambda, the deployment succeeds, but the gRPC binary deployed is *node-v48-win32-x64-unknown* not the required *node-v48-linux-x64-glibc*.  When I invoke the Lambda function, it understandably fails with the log:

> Unable to import module 'handler': Error
> Expected directory: node-v48-linux-x64-glibc
> Found: [node-v48-win32-x64-unknown]
> This problem can often be fixed by running "npm rebuild" on the current system
> Original error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'
>    at Object.<anonymous> (/var/task/node_modules/grpc/src/grpc_extension.js:53:17)


You mention above that you were able to automate the build before deployment.  Can you please tell me how you are doing the deployment to Lambda?  Thanks for your input.

**Comment by pflugs30** [comment]
@vespertilian Belay my request for help.  I was using serverless-webpack, and it was a limitation of that tool.

Fortunately, due to the remarkable help of @HyperBrain on [issue #342 of the serverless-webpack repo](https://github.com/serverless-heaven/serverless-webpack/issues/342), I was able to solve my issue when he added support for running custom scripts during the webpack process.  For more information for anyone arriving here from Google, please see that thread for my solution (and [issue #344](https://github.com/serverless-heaven/serverless-webpack/issues/344) there, too).

**Comment by corysimmons** [comment]
@vespertilian Thank you!!

**Comment by murgatroid99** [comment]
People have made comments indicating that this does work with the proper setup. That meets the original goal of this issue.

**Comment by matteobart** [comment]
@vespertilian 
Yeah so I still can't get it working! To recap: 
I created a folder
Installed firebase using the command:  `npm install firebase --prefix=./`
Then installed grpc using: `npm install grpc --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc`
Then: `npm install`
Went into the `package.json` file and added the line post-install command looks like this: 
![untitled 17](https://user-images.githubusercontent.com/23046212/42528282-fa479c10-8448-11e8-853f-da5cbb867ca9.png)
Zipped it up for the Lambda and I still get the error
I have some code in my index.js, but I'm sure that it isn't even looked at because of the errors
Thanks!

**Comment by murgatroid99** [comment]
If your goal is to use firebase, you don't want a direct dependency on `grpc`, and either way, your current postinstall script is rebuilding the instance of grpc that you are depending on directly, but probably not the instance that firebase depends on. So the solution is to remove "grpc" from that script. So it should just be `npm rebuild --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc`.

**Comment by matteobart** [comment]
So no luck! I have removed the `grpc` using `npm uninstall` as you suggested. My `package.json` looks like this:
```

{
  "name": "package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "npm rebuild --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc"
  },
  "dependencies": {
    "firebase": "^5.2.0"
  },
  "devDependencies": {},
  "author": "",
  "license": "ISC"
}

```

And I still get the error:
```

"errorMessage": "Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v48-linux-x64-glibc\nFound: [node-v57-linux-x64-glibc]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/var/task/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'",
  "errorType": "Error",
  "stackTrace": [
    "This problem can often be fixed by running \"npm rebuild\" on the current system",
    "Original error: Cannot find module '/var/task/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'",
    "Object.<anonymous> (/var/task/node_modules/@firebase/firestore/node_modules/grpc/src/grpc_extension.js:53:17)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/node_modules/@firebase/firestore/node_modules/grpc/src/client_interceptors.js:145:12)",
    "Module._compile (module.js:570:32)"
  ]
}
```

This error has been very frustrating! :/ 
And help would still be appreciated!

**Comment by morgs32** [comment]
Is there an issue to watch to see when grpc can get installed on a docker container with node 9/10?

**Comment by nicolasnoble** [comment]
No. If you are still experiencing issues, please open new issues about them specifically in https://github.com/grpc/grpc-node/issues

**Comment by murgatroid99** [comment]
It should currently be possible to install grpc on a docker container with node 9 or 10.
