### ISSUE TITLE
Server can crash client by sending compressed data when client isn't expecting it

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#6454]
DGQ to investigate crash reported.

**Comment by dgquintas** [comment]
I'm unable to reproduce. 

I have tried the following: 
1. reinforced the checks and failsafes in the core, as well as re-enabled the interop tests that check incoming compressed data to a client. (https://github.com/grpc/grpc/pull/6463). Interop tests work correctly, even under ASAN. In particular, clients are always ready to accept incoming compressed data (a client can't disable algorithms the way a server can). The interop tests exercise this path by asking the server to send back compressed data under all available algorithms. In some instances, the data is uncompressable, so the server will send it back uncompressed despite the client's request. 
2. faked the sending an unknown algorithm. This required changes in the server context that aren't possible from the application: it'd result firstly on a compile error if `ServerContext::set_compression_algorithm` is passed a value not in the `grpc_compression_algorithm` enum. Secondly, even then, the compression_filter would detect the outgoing algorithm to be invalid and simply send the data uncompressed (see `compress_filter.c:94`) The server detected this and falls back to not compressing.
3. faked the reception of an unknown algorithm by the client. There existed a path (now fixed [here](https://github.com/grpc/grpc/pull/6463/files#diff-cca1c9f1d0c2f99c06c000729d41005aR837)) that could result in empty data being returned by the client if the received compression algorithm is unknown by the client. Note that this, based on point 2, is currently only possible if there's been corruption on the wire.

**Comment by ctiller** [comment]
Oh I may have fixed something here when I was setting up the server
fuzzing. Would have to check commit logs. Just a sense I saw some code here
recently.

**Comment by dgquintas** [comment]
Yes, @jcanizales mentioned something along the lines of an unref. It's very likely the crash (which was an heisenbug and involved memory corruption) was unrelated to compression, but that use of compression somehow surfaced it.

**Comment by jcanizales** [comment]
Just a nit: the crash on the client was reproducible with every RPC sent to that server.

**Comment by jcanizales** [comment]
I think that, to be on the safe side, it's worth testing the current client against the specific server they used, even if just as a one-of.

**Comment by dgquintas** [comment]
and the crash happened _at the client_ upon receiving a response to that RPC from the server?

**Comment by dgquintas** [comment]
It'd be great if we could at least see the `GRPC_TRACE=all` for both parties.

**Comment by jcanizales** [comment]
Yes, the behavior upon receiving the response on the client was #6207, followed by a crash. The crash happened on malloc, IIRC, with a message talking of memory corruption. And @pranay saw an error mentioning an inappropriate `unref` (which could explain the memory corruption).

**Comment by ctiller** [comment]
I'd rather be getting reproductions than hearsay on both these bugs.

**Comment by dgquintas** [comment]
Just having runs with `GRPC_TRACE=channel` would be good to have, in order to look at the metadata/headers being sent around.

**Comment by jcanizales** [comment]
@ctiller, #6207 was making Jenkins flaky for days, @makdharma reproduced it locally by running the tests repeatedly and got the traces you asked for, which he attached to that issue.

For this bug, reproducing is a bit involved, but also doable: We have to run the faulty server and make RPCs with the version of the client @pranay had. Done that way, there's no flakiness; every RPC failed like #6027 and made the client crash immediately after that. I asked him to get traces for `"api"` and `"tcp"`, which he attached. Next time I know I'll better ask for `"all"`.

**Comment by pranay** [comment]
As @jcanizales said, it should be easy to reproduce, we just have to replicate the old setup (which should be easy too, we just need to turn compression back on).
You can find the stack traces I captured in the internal bug.

**Comment by dgquintas** [comment]
As discussed, can't repro locally. Closing this issue for now. Feel free to revive.
