### ISSUE TITLE
PHP distribtest fails on release-0_14 on mac

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6474]
Mac distribtest broken:
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/668/architecture=x64,language=php,platform=macos/

Linux seems to be working fine.

**Comment by stanley-cheung** [comment]
Yea I looked into this a while back. It seems to have to do with the version of `pear` being installed. There's a known bug for version 1.10 that I couldn't quite get the fix for. I will look more into this. It worked when `node1` has version 1.9

**Comment by stanley-cheung** [comment]
I applied a manual hack to all the jenkins macos instances and I believe the issue was fixed. The PHP distribtests are green now
