### ISSUE TITLE
Please add a command line tool for introspecting grpc servers

### ISSUE THREAD

**Issue by stapelberg** [grpc/grpc#648]
It’d be neat to be able to confirm that a server is working as expected and call its method from the command line.

If there was a “grpc” tool, I could run my server and then use `grpc ls localhost:10000` to see all the services it provides, followed by `grpc ls localhost:10000 HelloService` to see all the methods. With `echo 'greeting: "hey"' | grpc call localhost:10000 HelloService.Greet` I’d expect to call the `Greet` method with the request proto being initialized from the provided text input.

**Comment by yang-g** [comment]
The tool exists now: grpc_cli and the introspection part is covered by #1793
