### ISSUE TITLE
The protoc version in the submodule is too old to do Node code generation

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#6516]

**Comment by jtattermusch** [comment]
CC @hsaliak

**Comment by jtattermusch** [comment]
CC @pherl

**Comment by nicolasnoble** [comment]
As far as I understand, protobuf's latest release is v3.0.0-beta-2, from December 30: https://github.com/google/protobuf/releases - when exactly has the necessary support been introduced ?

**Comment by murgatroid99** [comment]
We need something at least as recent as [this commit](https://github.com/google/protobuf/commit/c9f8a1b00607be071d8be9e2bdc42ffcf97442aa#diff-32981a13284db7a021131df49e6cd203) from February 24.

**Comment by pherl** [comment]
I will try to push some release out in a week or two.
