### ISSUE TITLE
Python generic bidirectional streaming fails with empty requests

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6522]
If either the request or response is empty, it fails after exactly 3 requests.

**Comment by nathanielmanistaatgoogle** [comment]
Huh. Might I trouble you to write up a failing unit test?

**Comment by kpayson64** [comment]
Sure, this one fails deterministically

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: could you make a quick sanity check of this at the Cython layer and add a passing Cython-layer unit test?

**Comment by kpayson64** [comment]
Could be related to #6586

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle 9c372a6. Test code could use a little more clean-up (and I'll be writing up some more utilities to test for batch types and results and such), but it shows a passing Cython-layer test (... that GitHub has absolutely no idea how to show the diff of; also see the GitHub comment I've attached to it).

**Comment by jtattermusch** [comment]
@kpayson64, is this still an issue after changing python internals?

**Comment by kpayson64** [comment]
@jtattermusch Confirmed that this is no longer an issue after GA change.  I will add more test cases (not just bidirectional stream) to #6751, but I think we can close this one.
