### ISSUE TITLE
check_include_guards.py and clang_format conflict for long #ifdef guards.

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#6523]
Here's an example:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/8759/config=opt,language=sanity,platform=linux/testReport/junit/(root)/tests/tools_distrib_check_include_guards_py/

I *think* that clang_format format should be fixed.

**Comment by jboeuf** [comment]
@ctiller may be interested as well...

**Comment by jboeuf** [comment]
FYI, this is blocking https://github.com/grpc/grpc/pull/6436

**Comment by dgquintas** [comment]
hmm I don't think clang-format can be easily changed. I can just make check_include_guards more lenient.

**Comment by jboeuf** [comment]
whatever works :)

**Comment by dgquintas** [comment]
ok, this shouldn't take long. Fixing by EOD for sure.

**Comment by jboeuf** [comment]
awesome. thanks much!
