### ISSUE TITLE
src/boringssl/err_data.c missing in npm package 0.14.1-pre1

### ISSUE THREAD

**Issue by palortoff** [grpc/grpc#6531]
With src/boringssl/error_data.c missing the package cannot be built for use in electron.

When adding the file manually building is possible:

**Comment by murgatroid99** [comment]
Thank you for reporting this.

**Comment by palortoff** [comment]
Thanks for fixing with #6532 !
Building works again with 0.14.1

Closing this issue...

**Comment by murgatroid99** [comment]
Are you changing anything to make grpc build under electron? If so, can you share what those changes are?

**Comment by palortoff** [comment]
There are no specific changes made. I use tools made available by electron.

You can use electron-builder to build grpc under electron.
It uses electron-prebuilt to download the appropriate node headers to build grpc.

After deleting ``grpc/src/node/extension_binary/grpc_node.node`` the ``node_modules/.bin/build`` script that comes with electron-builder will build a new grpc_node.node that can be loaded within electron.

Note: As of the release of electron 1.0.1 today this does not work with the latest version of electron-prebuilt, but it does work with 0.37.8 ([electron-rebuild #66](https://github.com/electron/electron-rebuild/issues/66))

**Comment by rllola** [comment]
@palortoff Does it work with electron 1.4.1 and could explain a little how you made it work with electron-builder ?
