### ISSUE TITLE
Improve error reporting for qps_json_driver

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6540]
Qps driver currently asserts that calls to qps workers succeed and doesn't display any useful info at all if they fail.

```
E0511 18:02:42.689005516   29879 driver.cc:294]              assertion failed: servers[i].stream->Read(&init_status)
```

As the very minimum, the statuscode and error detail should be printed before aborting.

**Comment by vjpai** [comment]
Fixed by #7285
