### ISSUE TITLE
Generated C# code in master cannot be regenerated until Google.Protobuf.3.0.0-beta3 nuget is published.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6549]
We bumped third_party/protobuf  to beta3-pre-1 release, which brings some breaking changes to generated C# code (renaming of GeneratedCodeInfo to GeneratedClrTypeInfo etc.).

If I regenerate the checked-in C# code in our repository using src/csharp/generate_proto_csharp.sh,  the generated code doesn't compile because there is no nuget package for Google.Protobuf-3.0.0-beta3 yet.

So, our master currently builds, but I cannot regenerate the code.

Options: finish the release of protobuf  3.0.0-beta3 quickly or release Google.Protobuf.3.0.0-beta3-pre1 nuget package.

**Comment by jtattermusch** [comment]
@pherl   @jskeet   @nicolasnoble   FYI.

**Comment by nicolasnoble** [comment]
Let's keep 0.14.0 for C# and 0.14.1 for node. Other languages can do what they want in between :-)

We'll need a resolution quickly - hopefully, beta3 should be released within a couple of weeks tops.
