### ISSUE TITLE
NodeJS, ArgueJS Cannot read property 'name' of null

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#6557]
I switched from version 0.13.1 to 0.14.1 and I am receiving this error now:
```
TypeError: Cannot read property 'name' of null
    at __ (arguejs/argue.js:117:46)
    at Client.makeUnaryRequest [as get] (grpc/src/node/src/client.js:369:16)
```

**Comment by murgatroid99** [comment]
One thing that changed in 0.14.1 was how arguments are passed to method calls. Optional arguments now come before the callback, and instead of passing `null` for an argument you don't need to provide, just omit it.

**Comment by marshauf** [comment]
Yes, that is it. Thank you.

**Comment by tbranyen** [comment]
I'm hitting this problem on the latest gRPC (1.1.2).

My code:

``` js
const grpc = require('grpc');
const grpcproxy = require('./grpcproxy_grpc_pb');
const protobuf = require('google-protobuf');

const client = new grpcproxy.GrpcProxyServiceClient(
  '<private_url>:<port>',
  grpc.credentials.createInsecure()
);

client.sayHello({}, function() {
  console.log('Did it work?');
});
```

If  I use any kind of object or null or remove the first argument completely, I get errors. I cannot seem to satisfy the arguejs code path. It complains about missing google.protobuf.Empty, it complains about missing name from null, getting a lot of complaints from the lib and nothing useful to action on :-/


When passing `{}`, I get:

```
/home/tbranyen/Desktop/grpc/node-generated/node_modules/arguejs/argue.js:117
          plainSignature.push( signature[key].name );
                                             ^
TypeError: Cannot read property 'name' of null
```

When removing the first argument completely, I get:

```
/home/tbranyen/Desktop/grpc/node-generated/coeusgrpcproxy_grpc_pb.js:21
    throw new Error('Expected argument of type google.protobuf.Empty');
    ^

Error: Expected argument of type google.protobuf.Empty
```

**Comment by murgatroid99** [comment]
I'm not sure what's going on with the argueJS errors, but have you tried passing an argument of type `google.protobuf.Empty`, like the last error suggests? That error seems to imply that that is the argument type of GrpcProxyServiceClient.sayHello. For convenience, `GrpcProxyServiceClient.sayHello.requestType` should be a reference to the `google.protobuf.Empty` constructor.

**Comment by tbranyen** [comment]
Where would I find `google.protobuf.Empty`? I required `google-protobuf` package, but that doesn't have `Empty`. Is there a different package that would contain this?

**Comment by murgatroid99** [comment]
You should be able to get it with `require('google-protobuf/google/protobuf/empty_pb')`. I don't know if there's a better way to access it.

**Comment by tbranyen** [comment]
This got me so much further, thank you!

```
const { Empty } = require('google-protobuf/google/protobuf/empty_pb');
client.sayHello(new Empty());
```

This spits some output to stdout like:

``` json
{ wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: [],
  pivot_: 1.7976931348623157e+308,
  convertedFloatingPointFields_: {} }
```

However, I'm still unable to pass a callback. If I do:

```
client.sayHello(new Empty(), () => {

});
```

I see the `cannot read name of null`. Maybe this is because it's a streaming request? So instead I switched to using the event emitter approach:

```
client.sayHello(new Empty()).on('end', () => {
  console.log('end');
}).on('error', (ex) => {
  console.log('Error', ex);
});
```

This prints out the initial stdout, but is never completed or rejected. This is probably a separate issue, but not sure...

**Comment by murgatroid99** [comment]
If `sayHello` is a streaming call, that is very relevant. Unary and streaming calls have different APIs.

If it expects a stream of request messages, you should omit the argument, and the function returns a Writable stream, on which you can call `write` to send messages and `finish` to stop sending.

If you expect a stream of response messages, you should omit the callback, and the function returns a Readable stream, on which you should listen for the `data` event to get responses. Note that response streams will stall until you read the response messages.

**Comment by tbranyen** [comment]
@murgatroid99 perfect, thought so! This all makes sense, thank you for the help. Hopefully this conversation helps others stumbling on these errors in the future.
