### ISSUE TITLE
Support use from CMake applications

### ISSUE THREAD

**Issue by JamesOldfield** [grpc/grpc#6573]
CMake currently seems to be the least terrible way to build cross-platform native applications, so it would be good to be able to use gRPC directly from programs built with it. This would ideally involve three things:
1. The creation of a FindGRPC.cmake that sets GRPC_LIBRARIES and GRPC_INCLUDE_DIRS CMake cached variables.
2. The submission of that file to the CMake authors to include with their program. Unfortunately, there is nothing like a central repository of cmake modules, so this is the official distribution channel.
3. Ideally, FindGRPC.cmake would include extra CMake functions for running protoc, in the same way that FindProtobuf.cmake has a PROTOBUF_GENERATE_CPP function. 

Example implementations:
- It would probably do to slightly modifiy FindProtobuf.cmake module by the CMake developers: https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake
- An example FindGRPC.cmake can be found here (Apache licensed), complete with a PROTOBUF_GENERATE_GRPC_CPP function, but it does not set GRPC_INCLUDE_DIRS: https://github.com/wastl/cmarmotta/blob/master/cmake/FindGRPC.cmake 

This is different from issue #1096, which asks that gRPC be built with CMake. This issue is about programs being built with CMake that _use_ gRPC. I don't see why any application developer would care what gRPC's build process is. (Even if that issue were fixed, and CMake became the _only_ way to build and install gRPC, that would automatically solve point 1 but not 2 or 3 from the list above.)

**Comment by IvanSafonov** [comment]
I've made simple example with gRPC and cmake. There are two find modules for Protobuf and gRPC.
https://github.com/IvanSafonov/grpc-cmake-example

**Comment by jtattermusch** [comment]
Now that gRPC has it's own CMake buildfile (and so does Protobuf), it should be easy to use gRPC and protobuf in a CMake-built application.

Alternatively, @IvanSafonov  has an example https://github.com/IvanSafonov/grpc-cmake-example how to use gRPC with cmake (involves installing grpc and protobuf)
