### ISSUE TITLE
Extraneous printout when using posix polling engine

### ISSUE THREAD

**Issue by johnco3** [grpc/grpc#6584]
##It looks like the merge pull request #5456 causes some regression. When this latest change, I am getting the following code printed on the console 'Using polling engine: poll'  This seems to come from the following code in ev_posix.c - in order to work around this, I had to temporarily comment this log statement out.

```
static void try_engine(const char *engine) {
  for (size_t i = 0; i < GPR_ARRAY_SIZE(g_factories); i++) {
    if (is(engine, g_factories[i].name)) {
      if ((g_event_engine = g_factories[i].factory())) {
        gpr_log(GPR_DEBUG, "Using polling engine: %s", g_factories[i].name);
        return;
      }
    }
  }
}

```

**Comment by joostshao** [comment]
yes, i meet it too  !

**Comment by tonicbupt** [comment]
from [here](https://github.com/grpc/grpc/blob/master/src/core/lib/support/log.c#L80) I found that using env var `GRPC_VERBOSITY ` can filter these outputs ...

**Comment by tejasmanohar** [comment]
i think the default should be info

**Comment by sreecha** [comment]
If `GRPC_VERBOSITY` environment variable is not set, the default logging level is `ERROR`.

So this log statement will not be logged. 

I am closing the issue.
