### ISSUE TITLE
Include C dependencies in Node package

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#659]
We can move `package.json` and `binding.gyp` to the root directory to use this repository as the repository link in `package.json`. We can also include the C library in the `package.json` files and, if they have a gyp file (#658), then we could depend on it to build the C library as part of the Node package installation process.

This would eliminate the relatively painful step of installing the C library before the Node library can be installed.

**Comment by ofrobots** [comment]
+1. Being able to do npm install of the module would be great. Alternatively, could the node.js specific code be extracted into a separate repo and the C dependencies vendor-ed in as a submodule?

**Comment by murgatroid99** [comment]
This has been fixed by #3625.
