### ISSUE TITLE
node.js grpc extend trouble

### ISSUE THREAD

**Issue by zeqi** [grpc/grpc#6596]
# comm.proto -->The contents are as follows:

``` sh
syntax = "proto3";

//package node_mongo;

message Res {
    optional int32 status = 1;
    optional int32 code = 2;
    optional string msg = 3;
    extensions 4 to 100;
}
```
# user.proto -->The contents are as follows:

``` sh
syntax = "proto3";

import "comm.proto";
//package node_mongo;

extend Res {
    optional DocModel data = 4;
}

message Id {
    optional string id = 1;
}

service User {
    rpc findById (Id) returns (Res) {};
}
```
# Next with grpc.js parsing user.proto:

``` javascript
var grpc = require('grpc');

var PROTO_PATH = __dirname + '/../../../protos/user.proto';
var proto = grpc.load(PROTO_PATH);

console.log(new proto.Res());    
//Output result: { status: 0, code: 0, msg: '', '.data': null }
```

Why there is a comma in the front of the node("data"),I opened "package node_mongo" commente,  Output result: 

``` javascript
{ status: 0, code: 0, msg: '', '.node_mongo.data': null }
```

**Comment by murgatroid99** [comment]
What you are seeing is the output of the [Protobuf.js](https://github.com/dcodeIO/ProtoBuf.js/) serializer. In this case, it may be an internal representation that does not reflect how the data is actually accessed. Try `(new proto.Res()).toRaw()` and see if that outputs something more useful.

**Comment by murgatroid99** [comment]
This may have changed since it was reported, and it does not seem to be a gRPC-specific problem.
