### ISSUE TITLE
gRPCCertificates.bundle not found

### ISSUE THREAD

**Issue by spf2** [grpc/grpc#6598]
With objc cocoapods 0.12 and 0.13 I get an error like: 
`error: Resource "/Users/spf/Library/Developer/Xcode/DerivedData/[...]/Build/Products/Debug-iphonesimulator/gRPC/gRPCCertificates.bundle" not found. Run 'pod install' to update the copy resources script`

I've figured out I can fix this by editing `Pods/Target\ Support\ Files/Pods-Yarn/Pods-Yarn-resources.sh` and changing lines like: 
`install_resource "$CONFIGURATION_BUILD_DIR/gRPC/gRPCCertificates.bundle"` to 
`install_resource "$CONFIGURATION_BUILD_DIR/gRPC/gRPC/gRPCCertificates.bundle"`, but would be nice to have a better fix...

**Comment by jcanizales** [comment]
Hi @spf2, what version of Cocoapods are you using? Does this happen with gRPC 0.14 too?

**Comment by spf2** [comment]
@jcanizales i'm not able to check until maybe next week, sorry... my cocoapods is 1.0.0.beta.6

**Comment by jcanizales** [comment]
Hey @spf2, did you get this sorted out?

**Comment by spf2** [comment]
I'm currently on gRPC 1.0.0 and cocoapods 1.0.1 and not seeing this problem anymore. So, yes. Thanks.

**Comment by thijsw** [comment]
I'm experiencing this issue when I try to convert an existing project in Xcode 9.0 beta 5 to Swift 4 using the Swift Conversion tool that comes with Xcode.

The project builds fine, but when I start the Swift conversion tool that you see after clicking "Swift 4 conversion available" I experience this problem and the conversion is canceled.

```
CpResource /Users/thijs/Library/Developer/Xcode/DerivedData/[...]/Build/Intermediates.noindex/SwiftMigration/AppName/Products/Debug-iphonesimulator/gRPC/gRPCCertificates.bundle /Users/thijs/Library/Developer/Xcode/DerivedData/[...]/Build/Intermediates.noindex/SwiftMigration/AppName/Products/Debug-iphonesimulator/gRPC/GRPCClient.framework/gRPCCertificates.bundle
    cd /Users/thijs/Projects/AppName/Pods
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/thijs/Library/Developer/Xcode/DerivedData/[...]/Build/Intermediates.noindex/SwiftMigration/AppName/Products/Debug-iphonesimulator/gRPC/gRPCCertificates.bundle /Users/thijs/Library/Developer/Xcode/DerivedData/[...]/Build/Intermediates.noindex/SwiftMigration/AppName/Products/Debug-iphonesimulator/gRPC/GRPCClient.framework

error: /Users/thijs/Library/Developer/Xcode/DerivedData/[...]/Build/Intermediates.noindex/SwiftMigration/AppName/Products/Debug-iphonesimulator/gRPC/gRPCCertificates.bundle: No such file or directory
```

Any idea how I can resolve this issue?

**Versions**
Cocoapods 1.3.1
Xcode 9.0 beta 5
gRPC (1.4.2)
gRPC-Core (1.4.2)
gRPC-ProtoRPC (1.4.2)
gRPC-RxLibrary (1.4.2)

**Comment by begoat** [comment]
I came across the same problem. @thijsw Did you solve it?
