### ISSUE TITLE
Python tests fail to build on Windows

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#6604]
https://grpc-testing.appspot.com/job/gRPC_master/config=dbg,language=python,platform=windows/17001/console
+ python tools/run_tests/run_tests.py -t -l python -c dbg -x report.xml -j 2
START: vsprojects\build_vs2013.bat

c:\jenkins\workspace\gRPC_master\config\dbg\language\python\platform\windows>setlocal

Microsoft (R) Build Engine version 12.0.40629.0

[Microsoft .NET Framework, version 4.0.30319.42000]

Copyright (C) Microsoft Corporation. All rights reserved.

**MSBUILD : error MSB1009: Project file does not exist.**

Switch: vsprojects\shared_c.sln

FAILED: vsprojects\build_vs2013.bat [ret=1, pid=6680]
FAILED: Some tests failed
+ TESTS_FAILED=true
+ '[' '!' -e reports/index.html ']'
+ mkdir -p reports
+ echo 'No reports generated.'
+ '[' true '!=' '' ']'
+ exit 1
Build step 'Execute shell' marked build as failure
Started to fail with build #16913.

**Comment by nathanielmanistaatgoogle** [comment]
Is there any relationship between this issue and [issue 6565](https://github.com/grpc/grpc/issues/6565) which was active last week?

**Comment by adelez** [comment]
I think it's the same. Closing this one.
