### ISSUE TITLE
Latency profiling data is missing from grpc_performance_master

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#6615]
Looks like something got removed recently?

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/master/tools/profiling/latency_profile/run_latency_profile.sh

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_performance_profile/

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_performance_profile/1/console

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/view/Master%20health/job/gRPC_performance_profile_master/1/console

**Comment by dgquintas** [comment]
Done https://grpc-testing.appspot.com/job/gRPC_performance_profile_master/
