### ISSUE TITLE
NodeJS, internal error results in client channel closed

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#6618]
Hello,

when responding to a client call with an error message ```{ code: 13, details: 'internal' }``` the client channel gets closed and all ongoing calls are dropped, as in no callback gets called.
Calls after receiving the error message result in ``Call cannot be created from a closed channel`` error.

Returning an error code 1 instead of 13 does not close the channel. Is an internal error meant to close the client channel?

**Comment by murgatroid99** [comment]
I can't reproduce this. I put together a test with a server that responds with an internal error and a client that makes two consecutive requests to the server, and it worked exactly as expected.

Can you provide a small client and server pair that demonstrate the problem? What versions of Node and gRPC are you using?

**Comment by marshauf** [comment]
I will try to replicate it in a small example.
```
node --version
v5.9.1
```
```
grpc@0.14.1
```

**Comment by marshauf** [comment]
I found the problem. I am sorry, it is my fault. I called grpc.waitForClientReady without checking the callback error and just closed the channel as soon as the client was ready:
```
    grpc.waitForClientReady(conn, deadline, function(err) {
        let chan = grpc.getClientChannel(conn);
        chan.close();
    });
```
Some calls got through before the channel got closed. It just looked like the returned error code was the cause.
