### ISSUE TITLE
errors with no ipv6 connectivity

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#6623]
_From @chrishiestand on May 13, 2016 23:8_

While using gcloud v0.33.0 (thanks for all the grpc improvements so far) I'm still getting some additional output:

```
E0513 15:32:42.397461000 123145307668480 tcp_client_posix.c:191] failed to connect to 'ipv6:[2607:f8b0:400e:c00::ef]:443': timeout occurred
E0513 15:32:45.284575000 123145306595328 tcp_client_posix.c:191] failed to connect to 'ipv6:[2607:f8b0:400e:c00::ef]:443': timeout occurred
```

I don't have ipv6 WAN connectivity at the moment. This is not fatal since ipv4 is used successfully instead.

Is there anyway to disable ipv6 in gcloud-node/grpc to avoid these error messages (and possible additional latency?)?

You could argue this is an OS issue and that if a public ipv6 address is available it should be okay to assume it can be used. I do seem to be getting public `2602::` addresses even though I'm not using them WAN-wise (I am on a LAN where I don't control the router, and maybe this network is misconfigured). If my context is rare it's fine to simply close this issue.

If I disable ipv6 entirely in the OS the errors do disappear.

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1314_

**Comment by stephenplusplus** [comment]
Cc @murgatroid99 @ctiller

**Comment by ctiller** [comment]
I'm working on some better error reporting to allow us to make noise only when there's an actual problem.

**Comment by ctiller** [comment]
Which should make this a lot better!

**Comment by muxi** [comment]
Related to #12977
