### ISSUE TITLE
udp_server_test is #ifdef'd out

### ISSUE THREAD

**Issue by rjshade** [grpc/grpc#6624]
Body of test file is guarded by:

#ifdef GRPC_NEED_UDP
https://github.com/grpc/grpc/blob/master/test/core/iomgr/udp_server_test.c#L51

which does not appear to ever be defined. This should be fixed such that the tests are exercised in continuous builds.

**Comment by jcanizales** [comment]
Yep, was disabled half a year ago by https://github.com/grpc/grpc/pull/4406 and never brought back.

**Comment by rjshade** [comment]
This caused delays in the latest import: the grpc_error api changes could have been caught earlier if udp_server and udp_server_test were being built regularly.
