### ISSUE TITLE
Typescript Surface API Compiler?

### ISSUE THREAD

**Issue by chadbr** [grpc/grpc#6630]
Are there any plans to support generating Typescript for better interop with Angular2 (and nodejs in Typescript...)?

If not, any suggestions on how to start an external implementation? 

---

And if there's a better place to post this, please close this and point me in the right direction...

**Comment by xealot** [comment]
Our ecosystem is Python, Go and Javascript (Almost entirely Typescript + Angular2). GRPC seems like a breath of fresh air compared to say, JSONRPC.

How do we make this happen?

**Comment by bryanrideshark** [comment]
I also would be interested in contributing a solution to this problem. Likely, .d.ts files could be generated alongside any created JavaScript files?

**Comment by chadbr** [comment]
quick update - I spent a couple of days on this and really got nowhere.

From what I can tell by looking at a lot of the auto-gen'd libs, we should really be generating a set of .d.ts definitions from the .proto definitions for api/ver.

This is a little too much work for me at the moment.

As an aside -- I ran across this:

https://github.com/Microsoft/dts-gen

When I get some time in the next couple of weeks, I'll give it a go.

**Comment by chadbr** [comment]
maybe @murgatroid99 knows of a proto -> typescript generator?

**Comment by xogeny** [comment]
I've written a fair number of `.d.ts` files manually.  If anybody needs some help here, I'd be happy to lend a hand.  It seems to me that if you had an AST from the .proto file, it should be reasonably straightforward to generate a `.d.ts` file from that.  But I don't know how the internals of `gprc` work, so not sure if that is a possibility.

**Comment by kondi** [comment]
@chadbr see my project [rxjs-grpc](/kondi/rxjs-grpc)

**Comment by bryanrideshark** [comment]
@kondi - Oh snap! That looks great!

**Comment by muxi** [comment]
@murgatroid99 ping

**Comment by murgatroid99** [comment]
We are now distributing a `.d.ts` file with gRPC. It is relatively new and could probably be improved; contributions are welcome. We are not currently working on any support for generating `.d.ts` files from `.proto` files for use with gRPC.
