### ISSUE TITLE
Create special error code for gRPC internal errors that doesn't eclipse server error codes

### ISSUE THREAD

**Issue by gresrun** [grpc/grpc#6633]
Currently Objective-C gRPC internal errors utilize the `GRPCErrorCodeInterna`l code which is the same error code that is returned if the server responds with a `5XX` HTTP status code. It would be helpful if there was a separate error code for gRPC internal errors.

**Comment by jcanizales** [comment]
To clarify: this is in the context of this error https://github.com/grpc/grpc/blob/master/src/objective-c/RxLibrary/GRXWriteable.m#L60

The error condition it detects could be the server's fault. But for teams that develop both the app and the server, it's useful to make the distinction between "the server says error" and "there's something wrong in the server response, even though the server says it's fine".

One way to make that distinction is to add a field to the `userInfo` dictionary.
