### ISSUE TITLE
PHP protoc plugin

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#6637]
Implement the gRPC PHP protoc plugin, after Proto3 PHP support has been rolled out.

**Comment by thinkerou** [comment]
Hi, @stanley-cheung , your Protobuf-PHP branch has supported Proto3?

**Comment by stanley-cheung** [comment]
Not yet. This issue is a placeholder for future work, after there is official support from Proto3 for PHP.

**Comment by thinkerou** [comment]
OK, thanks.

**Comment by ckurz-va** [comment]
Hey @stanley-cheung 

We had chatted previously and we had made enough progress to get a php client for a grpc service running. We are trying to repeat that on a different grpc service, and it seems as though our previous efforts no longer work to recompile. 

we are currently making the proto from a clone of the https://github.com/stanley-cheung/Protobuf-PHP repo. We are trying to run it in a php5.5 docker image, using pecl install grpc-beta to get grpc, but also have it defined in our composer.json 
```
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/stanley-cheung/Protobuf-PHP"
    }
  ],
  "require-dev": {
    "pear/console_commandline": "*",
    "phpunit/phpunit": "4.8.*",
    "grpc/grpc": "v0.15.2"
  }
```

What versions should we currently be using of what libraries? Previous we had "dev-release-0_15" but it seems that version no longer exists. 

Thanks for your help!

**Comment by stanley-cheung** [comment]
We made a change recently. Check out the latest [example composer.json](https://github.com/grpc/grpc/blob/master/examples/php/composer.json). Basically, just take out that `"repositories"` block and it should work.

**Comment by ckurz-va** [comment]
That doesn't seem to make a difference. We removed the repositories section, and trashed the pecl install grpc-beta and that doesn't seem to have resolved it. We still see "Fatal error: Class 'Grpc\ChannelCredentials' not found in /citations-sdk/sdk.php on line 19" I'm pretty sure historically that was a version mismatch but can't figure out where the version mismatch is occurring.

**Comment by stanley-cheung** [comment]
You still need `pecl install grpc-beta`

**Comment by ckurz-va** [comment]
We are making progress!

Does the php implementation support the google/protobuf/timestamp? We seem to be getting an error when we use it. 

The interesting part is the error we get depends on the final digit of the timestamp. As it seems to be trying to read it as a wire type? 

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Groups are deprecated in Protocol Buffers and unsupported by this library' in /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php:322
Stack trace:
#0 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php(237): DrSlump\Protobuf\Codec\Binary->decodeUnknown(Object(DrSlump\Protobuf\Codec\Binary\Reader), 4)
#1 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php(65): DrSlump\Protobuf\Codec\Binary->decodeMessage(Object(DrSlump\Protobuf\Codec\Binary\Reader), Object(google\protobuf\Timestamp))
#2 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Message.php(107): DrSlump\Protobuf\Codec\Binary->decode(Object(google\protobuf\Timestamp), 1470857424)
#3 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Message.php(56): DrSlump\Protobuf\Message->parse(1470857424)
#4 /citations-sdk/test_client.php(12): DrSlu in /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php on line 322
```
```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unsupported wire type (7) while consuming unknown field' in /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php:324
Stack trace:
#0 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php(237): DrSlump\Protobuf\Codec\Binary->decodeUnknown(Object(DrSlump\Protobuf\Codec\Binary\Reader), 7)
#1 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php(65): DrSlump\Protobuf\Codec\Binary->decodeMessage(Object(DrSlump\Protobuf\Codec\Binary\Reader), Object(google\protobuf\Timestamp))
#2 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Message.php(107): DrSlump\Protobuf\Codec\Binary->decode(Object(google\protobuf\Timestamp), 1470857407)
#3 /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Message.php(56): DrSlump\Protobuf\Message->parse(1470857407)
#4 /citations-sdk/test_client.php(12): DrSlump\Protobuf\Messag in /citations-sdk/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php on line 324
```

**Comment by thinkerou** [comment]
Now the official protobuf have committed PHP code.
