### ISSUE TITLE
Installing Protobuf 3.0.0-beta-3 (was 3.0.0-beta-2)

### ISSUE THREAD

**Issue by namsoila** [grpc/grpc#6646]
There seems to be issues with the upgrade when generating files for objective-c. The podspec file given uses:
ms.dependency "Protobuf", "~> 3.0.0-alpha-4"
Thus, it defaults to the latest version. When you use the upgraded beta-3 release, it generates error:

#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.

I have confirmed since projects which were previously running without error are now having that error without any other changes.

If you go in and do a pod install on any projects previously using 3.0.0-beta-2, then the error results.

Changing podspec to ms.dependency "Protobuf", "3.0.0-beta-2" solves currently.

**Comment by namsoila** [comment]
Since the error is as below, does this mean that Protobuf 3.0.0-beta-3 is not generating for protobuf 3? My protobuf file starts with syntax = "proto3".

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

**Comment by jcanizales** [comment]
Hi,

the transition from Protobuf 3.0.0-beta-2 to beta-3 introduces changes that require a new version of the Protobuf compiler (`protoc`) to be used. Please install the new version from https://github.com/google/protobuf/releases/tag/v3.0.0-beta-3 (you have to scroll down almost to the end of that release section to find the `protoc-3.0.0-beta-3-osx-....zip` downloads) and try again.

I don't know if we've already uploaded it to homebrew, which makes installation easier. @murgatroid99, do you know?

> Changing podspec to ms.dependency "Protobuf", "3.0.0-beta-2" solves currently.

This is the right solution if you don't want to upgrade yet, and gRPC should be happy with it.

**Comment by namsoila** [comment]
Thanks.

I checked homebrew and it has the following versions:
protobuf: stable 2.6.1 (bottled), devel 3.0.0-alpha-3.1

The osx package just gives me the protoc file? I have tried using the source code to install but that gives the following error when I try and pod install:

[!] /bin/bash -c 
set -e
protoc --objc_out=. --objcgrpc_out=. *.proto

That occurs as follows:

Analyzing dependencies
Fetching podspec for `HelloWorld` from `.`
Downloading dependencies
Installing BoringSSL (3.0)
Installing HelloWorld (0.0.1)
[!] /bin/bash -c 
set -e
protoc --objc_out=. --objcgrpc_out=. *.proto

--objcgrpc_out: protoc-gen-objcgrpc: Plugin killed by signal 11.


How would I install from the osx .zip which only has the new protoc?

Tried reinstalling grpc but that uses:

https://github.com/google/protobuf/archive/v3.0.0-beta-1.tar.gz

So overall seems that I have differing versions of protoc in each case.

**Comment by aa57779111** [comment]
hi , I've had the same problem. solves follow
Changing podspec to ms.dependency "Protobuf", "3.0.0-beta-2" solves currently.
but ,How can I upgrade Protobuf 3.0.0-beta-2,
```
brew info google-protobuf
grpc/grpc/google-protobuf: stable 3.0.0-beta-2, HEAD
https://github.com/google/protobuf/
Conflicts with: protobuf
/usr/local/Cellar/google-protobuf/3.0.0-beta-2 (153 files, 13.0M)
  Built from source on 2016-05-23 at 11:47:01 with: --without-python
From: https://github.com/grpc/homebrew-grpc/blob/master/Formula/google-protobuf.rb
```
this is homebrew protobuf info, i can't upgrade;
How can I upgrade without homebrew?
Can you provide a correct step or feasible steps?
thanks

**Comment by namsoila** [comment]
@aa57779111 I was stating the version in the podspec file specifically. So here in the podspec template:
https://github.com/grpc/grpc/tree/master/src/objective-c
It uses ms.dependency "Protobuf", "~> 3.0.0-alpha-4".
I set that to use the specific version ms.dependency "Protobuf", "3.0.0-beta-2".
That will generate without the error even if you have a different version on your system.

**Comment by aa57779111** [comment]
@namsoila yep, I'm doing it in your way.also use 3.0.0-beta-2

**Comment by namsoila** [comment]
@jcanizales 

None of my podfiles will currently install and give the following:

[!] /bin/bash -c 
set -e
protoc --objc_out=. --objcgrpc_out=. *.proto

--objcgrpc_out: protoc-gen-objcgrpc: Plugin killed by signal 11.

Any suggestions? I have installed Protobuf 3.0.0-beta-3 by doing a manual build from the source file. The osx version only has a since protoc file? Not sure how to install with just that.

Here is the output from protoc --version:

libprotoc 3.0.0

Previous projects will build fine but not new ones.

**Comment by namsoila** [comment]
@jcanizales @aa57779111 I solved this by installing from source for everything.

Did brew rm for all protobuf and grpc elements.

Got the full 3.0.0-beta-3 source code file as a tar.gz file from https://github.com/google/protobuf/releases

Ran:

./autogen.sh
./configure --prefix=/usr/local
sudo make
sudo make install

Built grpc from source as here:

https://github.com/grpc/grpc/blob/master/INSTALL.md#build-from-source

Then removed the symbolic link that was pointing to the previous homebrew install

cd /usr/local/bin
rm protoc-gen-objcgrpc

Then within the install grpc folder followed this to set the new symbolic link:

https://github.com/grpc/grpc/tree/master/src/objective-c#no-homebrew

So

ln -s `pwd`/bins/opt/grpc_objective_c_plugin /usr/local/bin/protoc-gen-objcgrpc

Within the grpc folder from here: git clone https://github.com/grpc/grpc.git

Thanks.

**Comment by rsln-s** [comment]
Thanks, @namsoila , but one problem persists: after all fixes, the project still doesn't build with `ld: library not found for -lPods»` error
