### ISSUE TITLE
In some cases, the Ruby event loop thread is not correctly terminated

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#6650]
This happens with certain Rake test failures. So far, I have been unable to determine a cause, because this failure prevents test reports from being printed.

**Comment by murgatroid99** [comment]
My current best guess is that this happens when an exception is thrown in a different thread from the one running the test.

**Comment by murgatroid99** [comment]
One possible explanation for that failure mode: the child threads did not have `abort_on_exception` set. So any failure was not propagated to the main thread, and the main thread would begin waiting for a response that would never come, and the test would lock up.

**Comment by apolcyn** [comment]
I've noticed this in some unit tests, some of the unit tests have it turned `Thread.abort_on_exception` turned on but it's probably best to be for all of them

**Comment by apolcyn** [comment]
addressed by https://github.com/grpc/grpc/pull/8916
