### ISSUE TITLE
Fail-fast mode

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc#6678]
According to `doc/fail_fast.md`, fail-fast mode is enabled by default. But it didn't say how to disable it.
I couldn't find much resource for fail-fast mode other than the file. Can anyone link me to related example/code/documentation? Thanks!

**Comment by ctiller** [comment]
Which languages are you working in?

**Comment by biran0079** [comment]
I am using java. Should I move this issue to grpc-java repo instead?

**Comment by biran0079** [comment]
@ctiller ping?

**Comment by ctiller** [comment]
Thats probably a good idea.

**Comment by biran0079** [comment]
Moved to https://github.com/grpc/grpc-java/issues/1863
