### ISSUE TITLE
tests.unit._rpc_test.RPCTest shouldn't have to have a tearDown method

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#6680]
All it does is delete things that should be deleted anyway.

When I run the test without tearDown method on my terrestrial workstation, it passes, and when I run it without tearDown on my workstation in the cloud, it hangs.

**Comment by soltanmm** [comment]
Maybe a destruction order problem. Maybe.

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed in [pull request 6857](https://github.com/grpc/grpc/issues/6857).
