### ISSUE TITLE
Allow setting threads per cq for async benchmarks

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#6681]
I'm increasingly convinced that optimum performance for C core is going to be somewhere in the 2-4 threads per completion queue.

Our benchmarks are currently fixed to 1 thread per cq. Figure out some API to change this, and implement it.

**Comment by muxi** [comment]
Is this issue stale?

**Comment by ncteisen** [comment]
Yeah this is currently possible with QPS Driver
