### ISSUE TITLE
Sanity fails on new linux workers:  `error while loading shared library: libseccomp.so`

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#6685]
[link](https://grpc-testing.appspot.com/job/gRPC_pull_requests/9178/config=opt,language=sanity,platform=linux/testReport/(root)/tests/tools_distrib_clang_format_code_sh/)

Error Message

Failure
Standard Output

\++ dirname tools/distrib/clang_format_code.sh
\+ cd tools/distrib/../..
\+ docker build -t grpc_clang_format tools/dockerfile/grpc_clang_format
docker: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory
Command exited with non-zero status 127
real 0.00
user 0.00
sys 0.00

**Comment by jtattermusch** [comment]
Thanks for reporting this, this is happening since I switched the linux workers to ubuntu 15.10  (grpc-linux-X machines on jenkins).
