### ISSUE TITLE
Thousands of ubsan failures starting from build gRPC_master 17118

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6687]
https://grpc-testing.appspot.com/job/gRPC_master/17118/

New commits in this build:

Fix undefined behavior (commit: 525654a164a8862e14de913753100345932af2fc) (detail)
Fix some ubsan issues: I fear no bugs were harmed in the making of this (commit: 68897999237ab5d67278365b3bd444960fa3c4c0) (detail)
Refactoring the core security code. (commit: 8ca294e417217e1577609052f18df84be437c03c) (detail)
clang-format (commit: 19cd009ec14c1a759fe4d0ef79eb3fab738137ca) (detail)
Fixing headers. (commit: 2b2f414dd1cb3d1f72c8f2713e381f1bb260b3f7) (detail)
clang-format (commit: 93dd0470cf26aed445b40a8b9332e6b06f5e5514) (detail)
"taking a this" -> "taking this" typo correction (commit: 824ad2a5b9943c35933a675688634c2f152fd340) (detail)
Revive throughput tests . (commit: 3fe694fa35a35f753249ea55a43de3bd01c053d5) (detail)

**Comment by jtattermusch** [comment]
@yang-g

**Comment by jtattermusch** [comment]
#6423 seems to be related to ubsan?

**Comment by yang-g** [comment]
It is not clear to me why that PR triggers the failures,  maybe halt_on_error is enabled? I am looking at the failures and adding a ubsan_suppressions.txt.

**Comment by yang-g** [comment]
I just disabled the ubsan test on grpc_master.
