### ISSUE TITLE
get TSI_OPENSSL_ALPN_SUPPORT from env?

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#6691]
hi guys:

I want my server support NPN for **early** Android release, I'm using Python server and Android Client.

Looks like the old version does not support TLS 1.2, so we want to downgrade to NPN. 

I saw the code if TSI_OPENSSL_ALPN_SUPPORT is zero, then will try to use NPN, but I can't set outside.

Could we just use `gpc_getenv` to load this `TSI_OPENSSL_ALPN_SUPPORT` instead of hard code?

**Comment by ejona86** [comment]
For Android clients, you should be using Google Play Services Dynamic Security Provider. That provides an up-to-date TLS implementation even on old devices. Even on new devices, there are known bugs that are fixed if you use the dynamic security provider.

Even when TSI_OPENSSL_ALPN_SUPPORT is 1 it will still fallback to NPN if the client doesn't support ALPN. So there shouldn't be any need to change that value.
