### ISSUE TITLE
Async client interceptor

### ISSUE THREAD

**Issue by mofr** [grpc/grpc#6692]
**How to deal with async request preparations correctly?**

I'm using grpc 0.13.2 and Google Sign-In on android. Sign-In documentation says that it's good to check token (`silentSignIn`) before every API call. So I decided to use `ClientInterceptor` and faced problem that token update is async operation, however `ClientInterceptor` has blocking interface.

Currently I have solution to this problem, but it's verbose and ugly. I have something like stub-interceptor. So every request looks like this:

```
getStub(new StubReceiver() {
            @Override
            public void onStubReady(Stub stub) {
                // actual request is here
            }
        });
```

`getStub` method in this example doing all async work related to stub reconfiguring (updating tokens in my case).

_Off-topic: is it ok to post such questions here? If not, please, point me to right direction._

**Comment by cruvar** [comment]
really! I faced with this, but could not solve the problem

**Comment by ejona86** [comment]
I'm not quite sure what issue is being faced here. It seems you want to check that your auth token is not expired before each call? ClientInterceptor is asynchronous as well, but it is annoying when you need to do something asynchronous within an interceptor.

Now-a-days there is `CallCredentials`, which is easy to implement independent of whether getting a token is instantaneous (call apply() immediately), asynchronous (call apply() when done), or blocking (schedule on appExecutor, call apply() when done).
