### ISSUE TITLE
run 'make' error after 'pushd ../../cpp/helloworld'

### ISSUE THREAD

**Issue by l644676246hj** [grpc/grpc#6696]
im followIng the setp in [https://github.com/grpc/grpc/tree/master/examples/objective-c/helloworld](https://github.com/grpc/grpc/tree/master/examples/objective-c/helloworld)
and in trouble at run '**make**' error after '**pushd ../../cpp/helloworld**'.
my OS version is 10.11.1. Appreciate your help :)

error message as below:
> /bin/sh: pkg-config: command not found
Undefined symbols for architecture x86_64:
  "grpc::ClientContext::ClientContext()", referenced from:
      GreeterClient::SayHello(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in greeter_client.o
  "grpc::ClientContext::~ClientContext()", referenced from:
      GreeterClient::SayHello(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in greeter_client.o
  "grpc::CreateChannel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<grpc::ChannelCredentials> const&)", referenced from:
      _main in greeter_client.o
  "grpc::g_core_codegen_interface", referenced from:
      grpc::Status grpc::BlockingUnaryCall<helloworld::HelloRequest, helloworld::HelloReply>(grpc::ChannelInterface*, grpc::RpcMethod const&, grpc::ClientContext*, helloworld::HelloRequest const&, helloworld::HelloReply*) in helloworld.grpc.pb.o
      grpc::CompletionQueue::Pluck(grpc::CompletionQueueTag*) in helloworld.grpc.pb.o
      grpc::CompletionQueue::CompletionQueue() in helloworld.grpc.pb.o
      grpc::GrpcLibraryCodegen::GrpcLibraryCodegen() in helloworld.grpc.pb.o
      grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() in helloworld.grpc.pb.o
      grpc::CallOpSendInitialMetadata::FinishOp(bool*, int) in helloworld.grpc.pb.o
      grpc::CallOpSendMessage::FinishOp(bool*, int) in helloworld.grpc.pb.o
      ...
  "grpc::InsecureChannelCredentials()", referenced from:
      _main in greeter_client.o
  "grpc::g_glip", referenced from:
      grpc::GrpcLibraryCodegen::GrpcLibraryCodegen() in helloworld.grpc.pb.o
      grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() in helloworld.grpc.pb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [greeter_client] Error 1

**Comment by yang-g** [comment]
You can either install pkg-config following https://www.freedesktop.org/wiki/Software/pkg-config/

or change the Makefile part about pkg-config to -lgrpc++ -lgrpc -lgpr to see whether it works.
