### ISSUE TITLE
NodeJS logging

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#6697]
Hello,

gRPC seems to log directly to console and I can not find a way to set a logger or control it's level.
Is it possible to set a logger or a logging function?
There is also one direct call to console.log: https://github.com/grpc/grpc/blob/master/src/node/src/credentials.js#L123

**Comment by blerest** [comment]
a debug mode would be really useful too.

**Comment by murgatroid99** [comment]
This is a little tricky, because most of those log messages are generated by the underlying C code, and are never touched by JavaScript code. I could more easily make the change for that single `console.log` call in credentials.

**Comment by ctiller** [comment]
@murgatroid99: It's possible to hook the C logger to output somewhere other than stderr.

See https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/log.h#L98. At least C# does this currently.

**Comment by murgatroid99** [comment]
I did not know that. With that, I should be able to push that output through a JS-level logger.

**Comment by murgatroid99** [comment]
@ctiller What does `GPR_LOG_VERBOSITY_UNSET` mean? Is it a valid `gpr_log_severity` value?

**Comment by marshauf** [comment]
It does not look ``GPR_LOG_VERBOSITY_UNSET`` is a valid ``gpr_log_severity``. It would be an unreachable code here: https://github.com/grpc/grpc/blob/master/src/core/lib/support/log.c#L58
But other than that, it should just log everything when unset.
