### ISSUE TITLE
ruby linux artifact build broken on 0.14 release branch

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6700]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/879/architecture=x64,language=ruby,platform=linux/console

**Comment by jtattermusch** [comment]
cc @kpayson64

**Comment by murgatroid99** [comment]
Someone yanked google-protobuf 3.0.0.alpha.6.0.0 from the Ruby Gems
repository, and it looks like our build depends on that version.

**Comment by murgatroid99** [comment]
Actually, at the moment, it looks like it's simply impossible to `gem install google-protobuf`. We may have to publish 3.0.0-beta3 to get it working again.
