### ISSUE TITLE
bump minimum protobuf version or csharp plugin compilation fails when older protobuf system installation exists

### ISSUE THREAD

**Issue by michael-berlin** [grpc/grpc#6701]
If I understood it correctly, the C sharp plugin changes require a more recent protobuf version, namely 3.0.0-beta2: https://github.com/grpc/grpc/pull/4787

When no protobuf library is installed system wide, the copy from third_party/protobuf is used and everything is good because it's >= 3.0.0-beta2.

However, when a system installation exists, the Makefile (?) checks if the version is 3.0.0-alpha-3 or higher: https://github.com/grpc/grpc/blob/master/Makefile#L471

That's way too old for the C sharp plugin and therefore the gRPC compilation fails.

A user of us ran into this problem: https://github.com/youtube/vitess/issues/1721#issue-156117071
(We have gRPC 0.13 in our repository and he had 3.0.0-beta1 installed on his system.)

Therefore, older system wide installed protobuf libraries should be ignored if they don't match the gRPC requirements.

**Comment by jtattermusch** [comment]
Well, yes, if you have an older version of protobuf installed on your system and it's major version is 3.0.0-X or anything higher, makefile will pick it up and it's really hard to autodetect which version is acceptable / which is not anymore.

The way to avoid this is to never `make install` protobuf on the machine where you are developing/building gRPC. (actually, make install is problematic thing in general as there is no easy way to uninstall once a new version of protobuf in released - which is at least several times a year).

No action planned here.
