### ISSUE TITLE
Using same channel for issuing two different RPC calls results in cores !

### ISSUE THREAD

**Issue by abbassakar** [grpc/grpc#6709]
Hi,

I am writing a client and trying to do the following:
1. create a channel (ip:port) towards the server
2. Issue an RPC call from client to a service running on a device (login authentication)
3. Issue another RPC call from client to another service (served by the same server) (Management RPC)
Running on OS X Yosemite, GRPC 0.11 release

I am doing the above operation as a stress test and while performing this, it was noticed that my client program cores at random times due to 
    0x10007f266 <+86>:  callq  0x1001966a2               ; symbol stub for: grpc::Status grpc::BlockingUnaryCall<management::EditEphemeralConfigRequest, management::EditEphemeralConfigResponse>(grpc::Channel*, grpc::RpcMethod const&, grpc::ClientContext*, management::EditEphemeralConfigRequest const&, management::EditEphemeralConfigResponse*)
    0x10007f26b <+91>:  movq   -0x38(%rbp), %rax <<< Thread 2: EXC_BAD_ACCESS(code=1, address=0x0)

After commenting only the step 3 above, I was able to perform stress test for almost an hour without any issue. That is, if I call only one RPC service on that channel.
   
     // Create channel
    std::shared_ptr<grpc::Channel> channel = grpc::CreateChannel(
                                                   mgd_address,
                                                   grpc::InsecureCredentials());

	// Request authentication API
    _logger->log("Requesting login authentication from device");
    auth_stub_ = Login::NewStub(channel);

       // Now issue the config command — re-using the previous channel created
    stub_ = ManagementRpcApi::NewStub(channel);

Can you take a look at the attached code snippet and core backtrace? 
![grpc-client-core](https://cloud.githubusercontent.com/assets/17626332/15525147/52515e04-21dc-11e6-85cd-0de579408185.png)
[same_channel_used_for_two_different_rpc_call.cpp.pdf](https://github.com/grpc/grpc/files/280820/same_channel_used_for_two_different_rpc_call.cpp.pdf)

**Comment by abbassakar** [comment]
Hi,
Any updates ? Will appreciate some faster traction on this.

**Comment by yang-g** [comment]
It is hard to tell whether it is a grpc problem or where is the problem. Is
possible to get some repro?
Also your backtrace is server side code.

**Comment by ctiller** [comment]
At least the code in your back trace is not run anymore. Any chance you
could try a newer release? 0.11 is getting quite antiquated at this point.
