### ISSUE TITLE
//:third_party/objective_c/Cronet/cronet_c_for_grpc.h' crosses boundary of subpackage 

### ISSUE THREAD

**Issue by JaidenChiang** [grpc/grpc#6710]
I use the bazel to compile grpc,there are some problems,

_/home/jaiden/Workstation/bazel/output/bazel build //:grpc
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/jaiden/Workstation/grpc/BUILD:1517:10: Label '//:third_party/objective_c/Cronet/cronet_c_for_grpc.h' crosses boundary of subpackage 'third_party/objective_c' (perhaps you meant to put the colon here: '//third_party/objective_c:Cronet/cronet_c_for_grpc.h'?).
ERROR: error loading package '': Package '' contains errors._

Anyone knows how to resolve it?Thanks very much.

**Comment by jcanizales** [comment]
CC: @makdharma, who knows about Cronet and has been fighting Bazel recently.
