### ISSUE TITLE
grpc++ Windows DLL?

### ISSUE THREAD

**Issue by Kurtpenter** [grpc/grpc#6723]
Hi, does the current grpc (release-0_14_1) support building a grpc++ DLL?

I see a grpc_dll and Release-DLL/Debug-DLL configurations but it seems the generated DLL is just "grpc" for C.

I have a problem similar to the one described here: https://groups.google.com/forum/#!topic/grpc-io/0XReUAF2XXU

A program loads:
- my module (DLL) which uses grpc++
- other DLLs (for instance it may use a different OpenSSL or protobuf version)

So on one side I need to build a DLL because this is the only way to provide a plugin. On the other side I do not want to conflict with any library the program may have loaded.

I think the correct way to manage this would be to build a grpc++ DLL containing all dependencies (OpenSSL, zlib, ...) statically linked to avoid conflicting with other program libraries. I know this approach would be some drawbacks (for instance upgrading OpenSSL would require rebuilding the library) but this is something I can deal with.

Am I right or I'm missing something?
Thanks

**Comment by mgiaco** [comment]
@Kurtpenter I also have a similar problem. Did you found any solution for building the DLL. If so can you share it?

thx

**Comment by jtattermusch** [comment]
This issue is >1 year old, closing.
You can now use cmake to build C++ on Windows.
