### ISSUE TITLE
how do I could log the error with grpc-ruby?

### ISSUE THREAD

**Issue by xuxiangyang** [grpc/grpc#6727]
Hi, I am using grpc ruby server. How could I set the logger to log error?

I found that if one request is crash, server has no output except `GRPC::BadStatus (2:no reason given):` on the client.

But the message could not help me to find out what's wrong. Could I log the crash on the server side?

**Comment by lenage** [comment]
Hi @xuxiangyang 

You can use `logging` and just extend it in `GRPC` module, 

```
module GRPC
  extend Logging.globally
end
```

and then set log level for `GRPC` 

```
Logging.logger['GRPC'].level = :debug
```

or you can just create a Logger class and implement `logger` method for it.  for example

see more at  [https://github.com/grpc/grpc/blob/master/src/ruby/pb/test/server.rb#L95-L109)

**Comment by xuxiangyang** [comment]
thx
