### ISSUE TITLE
Include .proto files of well known types in grpc-tools package.

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#6740]
The grpc-tools package does not currently include common .proto files. These are needed when generating code for .proto files that import common .protos.
Protobuf's binary package include these files, so we should do the same

**Comment by murgatroid99** [comment]
Where can I find a list of the common .proto files?

**Comment by soltanmm** [comment]
Invoking `bazel query 'deps(//:well_known_protos)'` within the protobuf repo (post `git clean -xdf` or from a fresh clone) should give a list.

**Comment by murgatroid99** [comment]
OK, there seems to be a bigger problem here: the CommonJS (Node.js) protobuf generator does not seem to play well with well known types. It generates imports for the corresponding `pb.js` files, but it doesn't generate those files.

**Comment by murgatroid99** [comment]
Resolved by #6912.
