### ISSUE TITLE
Make python work correctly when receiving a compressed message

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6744]
See node's fix #6719.

**Comment by nathanielmanistaatgoogle** [comment]
Is there a test case demonstrating the incorrectness? If not, please include one with the fix.

**Comment by jtattermusch** [comment]
Possible way to reproduce:

Start a call with ("grpc-internal-encoding-request", "gzip") in initial metadata and with a big payload to make sure compression kicks in.

If that crashes the server when reading the request, things are broken.

Similar test:
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Tests/CompressionTest.cs#L143

**Comment by dgquintas** [comment]
Everything works. I manually modified `_rpc_test.py` to enforce compression and things worked. I'd have added a test to always exercise compression but the code wasn't too amenable to modification by outsiders :)

**Comment by nathanielmanistaatgoogle** [comment]
Test coverage added in [pull request 7063](https://github.com/grpc/grpc/pull/7063).
