### ISSUE TITLE
Make ruby work correctly when receiving a compressed message

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6745]
See node's fix #6719.

**Comment by murgatroid99** [comment]
We may already be OK here. At least part of the problem with Node is that it was allocating a buffer based on the size of the compressed data, and then trying to fill it with uncompressed data. Ruby just calls rb_str_cat repeatedly.

**Comment by hsaliak** [comment]
@murgatroid99 would you be able to pick this up? @kpayson64 has got a bunch of python issues assigned to him at the moment.

**Comment by yang-g** [comment]
This is verified to work via an interop test between ruby client and c++ server in #7039. Closing.
