### ISSUE TITLE
gRPC lib for embedded system

### ISSUE THREAD

**Issue by yookyoung89** [grpc/grpc#6756]
Hi, 
I want to apply google cloud speech API using gRPC to embedded system.(The system's source code language is C.)
So, i downloaded gRPC and tried cross-compiling..
Installed toolchain(arm-xxxx-linux-gnueabi-) for the system and modified some gRPC makefiles... but there have been error.

$ git clone https://github.com/grpc/grpc.git
$ cd grpc
$ git submodule update --init
$make HAS_PKG_CONFIG=false CC=arm-xxxx-linux-gnueabi-gcc CXX=arm-xxxx-linux-gnueabi-g++ RANLIB=arm-xxxx-linux-gnueabi-ranlib LD=arm-xxxx-linux-gnueabi-ld

[CXX]     Compiling src/cpp/util/time.cc
make: Circular /home/usergrpc/objs/opt/src/cpp/codegen/codegen_init.o <- /home/user/grpc/libs/opt/libgrpc++.a dependency dropped.
[HOSTCXX] Compiling src/compiler/cpp_generator.cc
[HOSTCXX] Compiling src/compiler/csharp_generator.cc
[HOSTCXX] Compiling src/compiler/node_generator.cc
[HOSTCXX] Compiling src/compiler/objective_c_generator.cc
[HOSTCXX] Compiling src/compiler/python_generator.cc
[HOSTCXX] Compiling src/compiler/ruby_generator.cc
[AR]      Creating /home/user/grpc/libs/opt/libgrpc_plugin_support.a
[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTLD]  Linking /home/user/grpc/bins/opt/grpc_cpp_plugin
/usr/bin/ld: /home/user/grpc/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
...
/usr/bin/ld: /home/user/grpc/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/home/user/grpc/objs/opt/src/compiler/cpp_plugin.o: could not read symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: **\* [/home/user/grpc/bins/opt/grpc_cpp_plugin] Error 1

**How can i resolve this error?**

**Comment by zinuga** [comment]
@vjpai any insights?

**Comment by yookyoung89** [comment]
Hi, i still have had this grpc_cpp_plugin error.
Before this problem, i had a error  libprotobuf.a .

**Comment by nicolasnoble** [comment]
So, first, you need to compile everything in two passes. Meaning you can't simply do `make` any longer, and you've got to identify the portions you actually want on either side. More on that in a moment.

Second, the Makefile isn't the appropriate location for trying to cross compile protobuf. In fact, special care has to be taken in order to properly cross compile protobuf, and doing these as separate steps is needed. We should rather disable compiling protobuf if we detect we are cross compiling, but that's not a straightforward test. See https://github.com/google/protobuf/tree/master/src for the "Note for cross-compiling" section.

And very much similar to what protobuf is doing, one needs to compile the plugins natively in one first pass:

`make plugins`

then cross compile the grpc library in a second pass. The exact target depends on what you actually want as a result, but I'm going to guess C++ static libraries, which is the reasonable choice for cross compiling:

`make HAS_PKG_CONFIG=false CC=arm-xxxx-linux-gnueabi-gcc CXX=arm-xxxx-linux-gnueabi-g++ RANLIB=arm-xxxx-linux-gnueabi-ranlib LD=arm-xxxx-linux-gnueabi-ld static`

The important change in there is the `static` keyword at the end.

**Comment by yookyoung89** [comment]
I already checked  https://github.com/google/protobuf/tree/master/src for the "Note for cross-compiling" section.
So, ptorobuf cross compiling is done. 
And then, I try to cross compile for grpc

> CPPFLAGS=-I/arm-xxxx-linux-gnueabi/include LDFLAGS=-//arm-xxxx-linux-gnueabi//lib 
> make HAS_PKG_CONFIG=false CC=arm-xxxx-linux-gnueabi-gcc CXX=arm-xxxx-linux-gnueabi-g++ LD=arm-xxxx-linux-gnueabi-ld LDXX=arm-xxxx-linux-gnueabi-ldd static

These are all pre-steps  about cpp_grpc_plugin error.

I have some questions about plugin compile.
- Where at ? grpc or protobuf
- Results about 'make plugins'.
- I would like to know reason of error exactly.

**Comment by seoz** [comment]
Hi yookyoung,

I haven't cross-compiled gRPC successfully yet due to the lack of time but can you also try with CMake?

Recently CMakeLists.txt were merged into the master branch for cross compile support.
https://github.com/grpc/grpc/pull/6997
https://github.com/grpc/grpc/blob/master/CMakeLists.txt

If you face any problems with CMake, please refer to the following issue report.
https://github.com/grpc/grpc/issues/7233

Thanks,
Daniel

**Comment by seoz** [comment]
Can you try with up-to-date CMakeLists.txt?
There was a patch to fix another issue which was reported in #7233

**Comment by yookyoung89** [comment]
Hi, 

I try compiling grpc source code.
 
1. release-0_14 branch
INSTALL.md file was updated. 

git  clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc

Branch is changed to release-0_14. 

```
> /home/.../grpc (release-0_14*):$ CPPFLAGS=-I/home/yookyoung.choi/arm-xxxx-linux-gnueabi-4.8-2016.03-x86_64/include LDFLAGS=-L/home/yookyoung.choi/arm-xxxx-linux-gnueabi-4.8-2016.03-x86_64/lib make HAS_PKG_CONFIG=false CC=arm-xxxx-linux-gnueabi-gcc CXX=arm-xxxx-linux-gnueabi-g++ LD=arm-xxxx-linux-gnueabi-ld LDXX=arm-xxxx-linux-gnueabi-ldd
[MAKE]    Generating /home/yookyoung.choi/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /home/yookyoung.choi/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling third_party/zlib/adler32.c
make: arm-lg115x-linux-gnueabi-gcc: Command not found
make: *** [/home/yookyoung.choi/grpc/objs/opt/third_party/zlib/adler32.o] Error 127
```

2. master branch 
i think #7235 issue was fixed in  master branch 9 hours ago. so i don't need to change some files.

```
[HOSTCXX] Compiling src/compiler/cpp_generator.cc
[HOSTCXX] Compiling src/compiler/csharp_generator.cc
[HOSTCXX] Compiling src/compiler/node_generator.cc
[HOSTCXX] Compiling src/compiler/objective_c_generator.cc
[HOSTCXX] Compiling src/compiler/python_generator.cc
[HOSTCXX] Compiling src/compiler/ruby_generator.cc
[AR]      Creating /home/yookyoung.choi/grpcgrcp/libs/opt/libgrpc_plugin_support.a
[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTLD]  Linking /home/yookyoung.choi/grpcgrcp/bins/opt/grpc_cpp_plugin
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)
/home/yookyoung.choi/grpcgrcp/objs/opt/src/compiler/cpp_plugin.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [/home/yookyoung.choi/grpcgrcp/bins/opt/grpc_cpp_plugin] Error 1
```

**Comment by seoz** [comment]
Did you get this error even though you used "cmake"? Then please report the issue to @tberghammer who is the author of CMakeLists.txt. It'll be great if you CC me to that thread.

**Comment by unicornmafia** [comment]
I am getting this same plugin error compiling for mipsle.   I would like to try with the cmake as suggested above.  Can anyone provide the correct syntax for doing this?

**Comment by tberghammer** [comment]
I haven't tried to cross compile grpc for a while but last time I tried these were the steps necessary:
* Create a cmake toolchain file for your toolchain and target platform (https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html#cross-compiling)
* git clone https://github.com/grpc/grpc && cd grpc && git submodule update --init
* mkdir build && cd build
* cmake .. -DCMAKE_TOOLCHAIN_FILE=<TOOLCHAIN-FILE> -Dprotobuf_BUILD_TESTS=Off -DgRPC_INSTALL=Off
* make

**Comment by jtattermusch** [comment]
There hasn't been any activity on this issue, so I am going to close it. Contributions/fixes are welcome.
