### ISSUE TITLE
TLS mutual authentication fails with Node.js

### ISSUE THREAD

**Issue by sadeghis** [grpc/grpc#6757]
Connecting to a Node.js based gRPC server fails if mutual authentication is enabled.

```
E0602 13:22:50.850699324   23219 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify failed.
E0602 13:22:50.850718905   23219 handshake.c:241]            Handshake failed with error TSI_PROTOCOL_FAILURE
E0602 13:22:50.850725277   23219 server_secure_chttp2.c:121] Secure transport failed with error 1
```

Authentication is configured as follows.

``` javascript
const serverCredentials = grpc.ServerCredentials.createSsl(
    fs.readFileSync('ca.pem'),
    [{
        private_key: fs.readFileSync('server.key'),
        cert_chain: fs.readFileSync('server.pem')
    }],
    true  // GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY
);
```

With an unspecified root certificate (as seen in the test cases), the handshake succeeds.

``` javascript
const serverCredentials = grpc.ServerCredentials.createSsl(
    null,
    [{
        private_key: fs.readFileSync('server.key'),
        cert_chain: fs.readFileSync('server.pem')
    }],
    true
);
```

However, this works only if both the client and server certificate were issued by the same CA. Otherwise, the handshake hangs indefinitely (instead of failing).

**Comment by murgatroid99** [comment]
@jboeuf Do you know what might cause this?

**Comment by jboeuf** [comment]
For your second snippet, I checked the code and what is happening is that if `null` (2nd block in the first comment) is passed for the client roots, client certificate check is not enforced: see:
https://github.com/grpc/grpc/blob/master/src/core/lib/tsi/ssl_transport_security.c#L1477

This is a bug we should enforce params checking. Also, some type of mutual auth does not require a root to be specified (e.g. `REQUEST_CLIENT_CERTIFICATE_BUT_DONT_VERIFY`). 

As to why your first snippet does not work, one explanation could be that your client certificate has a server-only bit set on its extended key usage extension (https://tools.ietf.org/html/rfc5280#page-44). Can you post the client cert here so that I can have a look?

**Comment by blerest** [comment]
@jboeuf @murgatroid99 I'm having the same issue. I'm working with nodejs client and server with TLS on both side.

Here how I generate the certificates:

```
openssl genrsa -passout pass:1111 -des3 -out ca.key 4096

openssl req -passin pass:1111 -new -x509 -days 365 -key ca.key -out ca.crt -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Test/CN=localhost"

openssl genrsa -passout pass:1111 -des3 -out server.key 4096

openssl req -passin pass:1111 -new -key server.key -out server.csr -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Test/CN=localhost"

openssl x509 -req -passin pass:1111 -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt

openssl rsa -passin pass:1111 -in server.key -out server.key

openssl genrsa -passout pass:1111 -des3 -out client.key 4096

openssl req -passin pass:1111 -new -key client.key -out client.csr -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Test/CN=localhost"

openssl x509 -passin pass:1111 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt

openssl rsa -passin pass:1111 -in client.key -out client.key
```

Here my server in nodejs:
```
const fs = require('fs');
const grpc = require('grpc');

let credentials = grpc.ServerCredentials.createSsl(fs.readFileSync('./ssl/ca.crt'), [{
	cert_chain: fs.readFileSync('./ssl/server.crt'),
	private_key: fs.readFileSync('./ssl/server.key')
}], true);
let server = new grpc.Server();
let helloWorld = grpc.load('./hello_world.proto');
server.addProtoService(helloWorld.HelloWorldGrpc.service, {
	helloWorld: (_context, _callback) => {
		_callback(null, null);
	}
});
server.bind('localhost:1983', credentials);
server.start();
```

Here my client in nodejs:
```
const fs = require('fs');
const grpc = require('grpc');

let credentials = grpc.credentials.createSsl(fs.readFileSync('./ssl/server.crt'), fs.readFileSync('./ssl/client.key'), fs.readFileSync('./ssl/client.crt'));
let helloWorld = grpc.load('./hello_world.proto');
let client = new helloWorld.HelloWorldGrpc('localhost:1983', credentials);
client.helloWorld(null, (_error, _response) => {
	if (_error) {
		return console.error(_error);
	}
});
```

And finally my proto:

```
syntax = "proto3";

service HelloWorldGrpc {
    rpc helloWorld(HelloWorldRequest) returns (HelloWorldResponse);
}

message HelloWorldRequest {
    HelloWorld hello_world = 1;
}

message HelloWorldResponse {
    HelloWorld hello_world = 2;
}

message HelloWorld {
    string message = 1;
}
```

**Comment by blerest** [comment]
do you have any news regarding this issue?

**Comment by jboeuf** [comment]
Sorry, I was on vacation, I'll have a look shortly.

**Comment by blerest** [comment]
hi @jboeuf, did you have a look? Thank you.

**Comment by jboeuf** [comment]
I've started to do so. I hope to be able to reply some time today with my findings.

**Comment by jboeuf** [comment]
@blerest 
I tested your certs (in C++, not in nodejs) and it fails as well. It has to do with the fact that all your certs have the same subject which confuses the openssl cert chain builder (best guess).

If you change the lines in your script that assign identities to:
```
openssl req -passin pass:1111 -new -x509 -days 365 -key ca.key -out ca.crt -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Test/CN=ca"

openssl req -passin pass:1111 -new -key server.key -out server.csr -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Server/CN=localhost"

openssl req -passin pass:1111 -new -key client.key -out client.csr -subj  "/C=FR/ST=Paris/L=Paris/O=Test/OU=Server/CN=localhost"
```

And change your client code to really use the CA cert as the CA as opposed to the server cert:
```
let credentials = grpc.credentials.createSsl(fs.readFileSync('./ssl/ca.crt'), fs.readFileSync('./ssl/client.key'), fs.readFileSync('./ssl/client.crt'));
```

Things should work (at least they do in C++). Please let me know if that's not the case.

**Comment by blerest** [comment]
@jboeuf thank you, it's working like a charm now.

**Comment by blerest** [comment]
Using a server on nodejs, does it possible to know which certificate (which client) is doing a request (like an access to the OU value)?

**Comment by jboeuf** [comment]
@blerest Thanks for the confirmation. The client certificate info has not been plugged in yet in the nodejs server (this is only available in C++). However, @jtattermusch are probably going to make a plan soon on how to support this in all wrapped languages. Stay tuned!

Should we close this specific issue now? (please feel free to open another one for the client info, server side in nodejs). Thanks!
