### ISSUE TITLE
Add C# API to disable fail fast mode

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6766]
As part of the 0.14 release, fail fast is now enabled by default.

In order to disable fail fast mode, a flag must be set on metadata requests.
https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L212

We need to ensure that there is some way a user can disable fail fast mode.

**Comment by jtattermusch** [comment]
Thanks for filing this.

**Comment by kpayson64** [comment]
The parameter should be called ```wait_for_ready``` and default to false.

**Comment by jtattermusch** [comment]
Is https://github.com/grpc/grpc/blob/405503be4322cb331c7ba300632a56c1f066281c/include/grpc/impl/codegen/grpc_types.h#L289

the right flag? The original link is out of date.

Is this a client-side only feature or should something be done on server-side as well?

**Comment by kpayson64** [comment]
Yes, that's the correct flag.  Its a client-side only feature.
