### ISSUE TITLE
Add Python API to disable fail fast mode

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6770]
As part of the 0.14 release, fail fast is now enabled by default.

In order to disable fail fast mode, a flag must be set on metadata requests.
https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L212

We need to ensure that there is some way a user can disable fail fast mode.

**Comment by kpayson64** [comment]
The parameter should be called ```wait_for_ready``` and default to false.

**Comment by alecthomas** [comment]
Ping. Is it possible to disable fail fast in Python?

**Comment by nathanielmanistaatgoogle** [comment]
Punting; there's no reason to block the `1.1.0` release for this.

**Comment by lidizheng** [comment]
Implemented in PR https://github.com/grpc/grpc/pull/16919
