### ISSUE TITLE
Add Objective-C API to disable fail fast mode

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6771]
As part of the 0.14 release, fail fast is now enabled by default.

In order to disable fail fast mode, a flag must be set on metadata requests.
https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L212

We need to ensure that there is some way a user can disable fail fast mode.

**Comment by kpayson64** [comment]
The parameter should be called ```wait_for_ready``` and default to false.

**Comment by YioMidd** [comment]
How to set the flag?....and the API is...??

**Comment by jcanizales** [comment]
@YioMidd this issue hasn't been addressed yet. Why do you want to disable fail-fast in a mobile app?

**Comment by YioMidd** [comment]
I need get ``response message`` continuously to update UI and do other things....Sorry, I don't know whether I describe it clearly.

**Comment by jcanizales** [comment]
Yeah I think that's unrelated to this issue.

**Comment by muxi** [comment]
@kpayson I think failfast (wait-for-ready as my understanding) is disabled by default now?

**Comment by kpayson64** [comment]
This is in reference to ```GRPC_INITIAL_METADATA_WAIT_FOR_READY``` flag, which I still believe is disabled by default (and has no API access to enable it from wrapped languages).

Feel free to close this issue if there are no plans to add this feature.

**Comment by muxi** [comment]
Hmm that is different from what I heard though... but I'll go ahead and close it since we do not have plan indeed.
