### ISSUE TITLE
Consider using IAsyncEnumerator instead of AsyncStreamReader.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6776]
Feedback from GA API review.

Should have just used IAsyncEnumerator: https://github.com/grpc/grpc/blob/bceec94ea4fc5f0085d81235d8e1c06798dc341a/src/csharp/Grpc.Core/IAsyncStreamReader.cs#L48

**Comment by jtattermusch** [comment]
To be honest, I'm not sure that this is worth doing.  My perception is that using IAsyncStreamReader doesn't really add any extra complexity (everyone can clearly see that it's basically an IAsyncEnumerator) and having custom type gives us a an option to add gRPC-specific xmldoc documentation to the IAsyncStreamReader type to clarify the usage (and we can also define a read-stream specific extension methods  (we actually already provide AsyncStreamExtensions.ForEachAsync and ToListAsync()).

I'd say it's worth keeping the IAsyncStreamReader type and adding more documentation (general use of read streams and  and add more info on edge cases - what happens if the calls fails on client side/server side), rather then causing more pre-GA code churn by removing it.

**Comment by jtattermusch** [comment]
@jskeet   @chrisdunelm  feel free to express your opinions.

**Comment by jskeet** [comment]
It adds extra complexity if there are (for example) extension methods in Ix-Async which know how to work with an `IAsyncEnumerator` but not an `IAsyncStreamReader`. If this were `IAsyncEnumerable`, that would be a bigger concern; it's at least somewhat less so for `IAsyncEnumerator`.

I think it may be useful to have conversion methods though:

- `ToIAsyncEnumerator`
- Maybe `ToIAsyncEnumerable` - where the second `GetEnumerator` call would throw; this would allow simple uses with all the various extension methods for transformation etc.

**Comment by jtattermusch** [comment]
On Tue, Jun 14, 2016 at 1:15 AM, Jon Skeet <notifications@github.com> wrote:

> It adds extra complexity if there are (for example) extension methods in
> Ix-Async which know how to work with an IAsyncEnumerator but not an
> IAsyncStreamReader.
>
I don't understand. IAsyncStreamReader extends IAsyncEnumerator so any
extension method defined for IAsyncEnumerator will work just fine. Besides
that, you have the ability to define a grpc-specific extensions by
referring to type IAsyncStreamReader (which is think is useful and prevents
the need to pollute the scope unless it's necessary). So what we currently
have is better than just using IAsyncEnumerator (IMHO).


> If this were IAsyncEnumerable, that would be a bigger concern; it's at
> least somewhat less so for IAsyncEnumerator.
>
> I think it may be useful to have conversion methods though:
>
>    - ToIAsyncEnumerator
>
>
IAsyncStreamReader already is IAsyncEnumerator.


>
>    - Maybe ToIAsyncEnumerable - where the second GetEnumerator call would
>    throw; this would allow simple uses with all the various extension methods
>    for transformation etc.
>
> Yes, this one might be useful. It's a purely additive change though (when
declaring this as as extension method), so it can be introduced anytime
after GA. (Feel free to file a github issue as a request for adding this).
Also, in this particular case, having a the type IAsyncStreamReader  is
useful, because you probably don't want ToIAsyncEnumerable(this
IAsyncEnumerator)    but ToIAsyncEnumerable(this IAsyncStreamReader) - as
the latter doesn't add the method to other IAsyncEnumerator instance where
you might not want this method (basically what I mentioned above).

**Comment by jskeet** [comment]
Aha, I hadn't spotted that it was already extending `IAsyncEnumerator`. That definitely reduces the benefits. I don't have strong opinions either way at this point. I can see some benefits in having the extra interface, but equally I can see it's redundant in other ways.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/6909
