### ISSUE TITLE
Python GA API check for grpc_call_errors

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6793]
In https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py, Call.start_batch() can return a non-zero error code, but we do not check for it.

**Comment by nathanielmanistaatgoogle** [comment]
What action should the software take if a non-zero error code is returned?

**Comment by ctiller** [comment]
Yeah throwing is probably appropriate here (or barfing in some other manner): if you get one, it's absolutely a wrapping bug, but there's going to be one right? And when it hits, better to get a stack trace than a stuck bug.

**Comment by nathanielmanistaatgoogle** [comment]
Punting; this will be nice to do at some point but it's not necessary for `1.1.0`.
