### ISSUE TITLE
Decide extent to which grpcio should depend on oauth2client

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#6799]
If we migrate `grpc.beta.implementations.google_call_credentials` to the GA API at `grpc` top-level, then [the orthodox thing to do](https://www.youtube.com/watch?v=AFhSWQYdjy4&t=21m10s) would be to add a dependency on `oauth2client` to `grpcio`. Is this something we really want to do, or should the function be provided in some sort of `grpcio-extras` package such that the core `grpcio` package can do without the dependency?

**Comment by soltanmm** [comment]
Casting my vote for a separate `grpcio-contrib`/`grpcio-extras`/*blahblahwhatever* package that we can put off making/stabilizing until after GA.

**Comment by kpayson64** [comment]
I don't have any strong feelings.  I would avoid adding oauth2client as a dependency, but I'm not opposed to having a soft dependency though.  I would just ask that this sits in the test package until it finds a home so we can use it for interop testing.

**Comment by kpayson64** [comment]
Disregard the part about putting it in test package for inteorp testing, we still have access to it through the beta API.

**Comment by hsaliak** [comment]
Nothing is going to break if we dont do this for GA. So moving it out.

**Comment by nathanielmanistaatgoogle** [comment]
Given that this is blocking [issue 7609](https://github.com/grpc/grpc/issues/7609), I think we should have this discussion sooner rather than later.

Making an assessment of this now: I think either `grpcio` has to take a dependency on `oauth2client`, or there needs to be some kind of `grpcio-auth` package that depends on `oauth2client`. The key bit of code is [`grpc._auth.GoogleCallCredentials`](https://github.com/grpc/grpc/blob/bdec15786226306fa56e15c7d95c389eb3d90810/src/python/grpcio/grpc/_auth.py#L43), which implements [a `grpcio` interface](https://github.com/grpc/grpc/blob/bdec15786226306fa56e15c7d95c389eb3d90810/src/python/grpcio/grpc/__init__.py#L403) and takes an instance of [an `oauth2client` class](https://github.com/google/oauth2client/blob/2e8d1bea6464476d4e34801e59695adc95fd6b9e/oauth2client/client.py#L1064) as a construction parameter. I hoped there might be some way to tease them apart, so that on the `grpcio` side there could be a function that takes as a parameter a function that does-thus-and-such in neutral non-`oauth2client` non-`grpcio` terms and on the `oauth2client` side there could be a function that does-thus-and-such in neutral non-`oauth2client` non-`grpcio` terms, but I just don't see a way to thread the needle.

Am I missing anything @jonparrott @dhermes @kpayson64 @soltanmm?

**Comment by kpayson64** [comment]
Makes sense.  I'm fine with having a grpcio-auth package.

**Comment by dhermes** [comment]
You should be :-1:  on depending on `oauth2client` in `grpcio` core since it's such a mess of a package. You could vendor in the crypto needed to create signed payloads for JWTs used as scopeless

**Comment by jonparrott** [comment]
I would also be -1 on taking on new downstream clients.

I've mentioned this before, but this library should really be re-organized into `google.auth` for server-to-server authentication (2lo) and `google.oauth2` for user credentials stuff (3lo).

**Comment by jonparrott** [comment]
Based on the gRPC support we just added to google-auth, I'm in favor of leaving auth out of gRPC altogether. The usage for google-auth is pretty straightforward:

```python
import google.auth
import google.auth.transport.grpc
import google.auth.transport.requests
from google.cloud.speech.v1 import cloud_speech_pb2

# Get credentials.
credentials, _ = google.auth.default()

# Get an HTTP request function to refresh credentials.
request = google.auth.transport.requests.Request()

# Create a channel.
channel = google.auth.transport.grpc.secure_authorized_channel(
    credentials, 'speech.googleapis.com:443', request)

# Use the channel to create a stub.
cloud_speech.create_Speech_stub(channel)
```

Considering google authentication isn't the exclusive way of providing authentication to gRPC services, I suggest we keep things separate.

**Comment by nathanielmanistaatgoogle** [comment]
I agree that the dependency relationship should be _application_ → `google-auth-library-python` → `grpcio`. This means that `grpcio` will not add to its final API code elements like [`google_call_credentials`](https://github.com/grpc/grpc/blob/aa3863b4b7e2f44d27a656caf98322389ac8a805/src/python/grpcio/grpc/beta/implementations.py#L53) that were present in its Beta API and that caused `grpcio` to depend upon `oauth2client`. It might also mean that [the code in `grpcio` implementing the `google_call_credentials` Beta API function](https://github.com/grpc/grpc/blob/aa3863b4b7e2f44d27a656caf98322389ac8a805/src/python/grpcio/grpc/_auth.py#L43) would need to be relocated from `grpcio` to `google-auth-library-python` (this may have already happened, in effect if not in specifically described action).

Is this assessment correct? Is this assessment agreeable to everyone in this conversation? (It's agreeable to me.)

**Comment by jonparrott** [comment]
That seems agreeable to me.

If you wanted to keep `google_call_credentials`, it could just alias [`google.auth.transport.grpc.AuthMetadataPlugin`](http://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.grpc.html#google.auth.transport.grpc.AuthMetadataPlugin). Or you can pull off the bandaid now and deprecate/remove it.

**Comment by nathanielmanistaatgoogle** [comment]
I want to avoid keeping `google_call_credentials` because I want to avoid `grpcio` having code elements that "point up" the layers of abstraction/"look back" against the direction of dependency relationships (and I also want to avoid `grpcio` having conditional imports and the other trickery that goes along with that).

"`grpcio` and `google-auth-library-python` interdepend!" would be live-withable but having the dependency unidirectional is preferable when delivering the exact same application-visible value.

`google_call_credentials`, being in the Beta API, is already deprecated. I'm not yet aware of a reason to kill it sooner or later than the rest of the Beta API.

Okay, [one reason](https://github.com/grpc/grpc/issues/8621).

**Comment by kpayson64** [comment]
I think the resolution here is to give examples using the google-auth-library-python directly.

**Comment by nathanielmanistaatgoogle** [comment]
I agree.
