### ISSUE TITLE
completion_queue.c:406]     assertion failed: !reserved

### ISSUE THREAD

**Issue by odiszapc** [grpc/grpc#6800]
When running samples I faced with:

    E0607 00:32:35.763355743   48739 completion_queue.c:406]     assertion failed: !reserved

Running on latest master I pulled today (see issue date)

**Comment by ctiller** [comment]
Which language are you using?

**Comment by odiszapc** [comment]
I'm using C++

**Comment by ctiller** [comment]
Can I get a call stack for this?

**Comment by odiszapc** [comment]
@ctiller What is the easiest way to get it? I'm not a senior C/C++ engineer

**Comment by yang-g** [comment]
This is likely because of memory corruption bug in application level code. If you can provide a minimal sample to reproduce, I can take a look.
