### ISSUE TITLE
grpc server won't shutdown in xunit.net

### ISSUE THREAD

**Issue by mocsharp** [grpc/grpc#6808]
We ran into CannotUnloadAppDomainException when running our integration test using xunit 2.x and grpc 0.14.  It looks like that the ShutdownAsync/KillAync calls are unable to release the threads.  

Exception Message	"Error while unloading appdomain. (Exception from HRESULT: 0x80131015)"	string

> If a thread does not abort, for example because it is executing unmanaged code, or because it is executing a finally block, then after a period of time a CannotUnloadAppDomainException is thrown in the thread that originally called Unload.

Edit: the exception can be seen by running xunit console runner in debug mode.

**Comment by jtattermusch** [comment]
You probably didn't shutdown all your channels/servers properly (which would make the gRPC thread pool threads to finish).

Also, for 0.15 release (coming soon), there'll be a change in the shutdown mechanism that will probably solve your problem: Please see https://github.com/grpc/grpc/pull/6754 for details.

**Comment by jtattermusch** [comment]
The change in #6754 has been released a long time ago already. Can you please confirm that the issue was solved or provide additional details if the problem persists?

**Comment by jtattermusch** [comment]
I'm going to close this now, feel free to reopen if still an issue after #6754.
