### ISSUE TITLE
Several python perftest scenarios failing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6810]
After migrating switching the perf worker to GA API, the performance has increased significantly, but some scenarios started failing:

https://grpc-testing.appspot.com/job/gRPC_performance_experiment/1208/

**Comment by jtattermusch** [comment]
The PR that made the switch https://github.com/grpc/grpc/pull/6787

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle @soltanmm  FYI

**Comment by nathanielmanistaatgoogle** [comment]
Failing how? Are there stack traces?

**Comment by kpayson64** [comment]
@nathanielmanistaatgoogle
Its related to the removal of the ```event()``` API.  Its my understanding now that there is no way to do async bidirectional streaming?

**Comment by nathanielmanistaatgoogle** [comment]
... except that the `event` API - at least the "event" part of the gRPC Python Beta API, hasn't yet been removed. To my knowledge it's as much present and working as it was yesterday.

I'm not sure what you mean by "no way to do async bidirectional streaming" - it's certainly the case that applications can do arbitrarily ordered completely random full-duplex streaming.

Nothing about today's code was expected to break anything at all - are you sure there aren't stack traces or anything else to describe the failures you're seeing?

**Comment by kpayson64** [comment]
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/_client_adaptations.py#L396

This is where the offending exception is getting thrown.  I was using the ```event()``` API to accept bidirectional responses in a non-blocking fashion.

**Comment by kpayson64** [comment]
It looks like this was a planned removal #5729.

**Comment by nathanielmanistaatgoogle** [comment]
Oh, the _client-side_ event API. Yeah, that would do it.

This is probably not that much of a big deal - we can either migrate the calling code to use `Future`s or provide the client-side event API in `_client_adaptations`. We have options. :-)

**Comment by jtattermusch** [comment]
Console log doesn't reveal much:

```
START: qps_json_driver.cpp_to_csharp_protobuf_async_unary_qps_unconstrained
WAITING: ETA 304.0 sec; 8 queued, 1 jobs running, 63 complete, 13 failed
++ dirname tools/run_tests/performance/run_qps_driver.sh
+ cd tools/run_tests/performance/../../..
+ bins/opt/qps_json_driver '--scenarios_json={"scenarios": [{"name": "cpp_to_csharp_protobuf_async_unary_qps_unconstrained", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"async_server_threads": 0, "core_limit": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "ASYNC_SERVER"}, "client_config": {"client_type": "ASYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "client_channels": 64, "async_client_threads": 0, "outstanding_rpcs_per_channel": 100, "rpc_type": "UNARY", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 0}]}' --scenario_result_file=scenario_result.json
RUNNING SCENARIO: cpp_to_csharp_protobuf_async_unary_qps_unconstrained
D0606 22:56:35.349912444   12241 ev_posix.c:101]             Using polling engine: poll
I0606 22:56:35.351263758   12242 socket_utils_common_posix.c:170] Disabling AF_INET6 sockets because ::1 is not available.
D0606 22:56:35.352100428   12241 ev_posix.c:101]             Using polling engine: poll
D0606 22:56:35.353742075   12241 ev_posix.c:101]             Using polling engine: poll
I0606 22:56:35.355624341   12241 driver.cc:247]              Starting server on grpc-performance-server-8core:10000 (worker #0)
D0606 22:56:35.355684165   12241 ev_posix.c:101]             Using polling engine: poll
E0606 22:56:35.357150469   12241 driver.cc:293]              assertion failed: servers[i].stream->Read(&init_status)
tools/run_tests/performance/run_qps_driver.sh: line 35: 12241 Aborted                 (core dumped) bins/opt/qps_json_driver "$@"

FAILED: qps_json_driver.cpp_to_csharp_protobuf_async_unary_qps_unconstrained [ret=134, pid=12238]
```

This is partially because error reporting from qps_driver is not so good (https://github.com/grpc/grpc/issues/6540)

I think running the benchmarks locally would reveal the issues.

**Comment by kpayson64** [comment]
I think we should just replace those tests with a synchronous streaming client version.  I want to update the qps tests to use the GA API anyways (#6817)

**Comment by nathanielmanistaatgoogle** [comment]
Oh yeah. Of course that's something I wanted to do in the next week or two anyways.

**Comment by kpayson64** [comment]
Python performance tests are passing after the merge.
