### ISSUE TITLE
Building master from source on OSX causes python import to fail

### ISSUE THREAD

**Issue by awan1** [grpc/grpc#6812]
After building grpc from source with 

    git -C $VENVDIR/repo clone https://github.com/grpc/grpc.git
    cd $VENVDIR/repo/grpc
    git submodule update --init
    make -j4
    make install prefix=$VENVDIR

and trying to run a client, we fail with this message:

    Traceback (most recent call last):
      File "client.py", line 22, in <module>
        from grpc.beta import implementations
      File ".../_venv/lib/python2.7/site-packages/grpc/beta/implementations.py", line 38, in <module>
        from grpc._adapter import _intermediary_low
      File ".../_venv/lib/python2.7/site-packages/grpc/_adapter/_intermediary_low.py", line 57, in <module>
        from grpc._adapter import _low
      File ".../_venv/lib/python2.7/site-packages/grpc/_adapter/_low.py", line 34, in <module>
        from grpc._cython import cygrpc
    ImportError: dlopen(.../_venv/lib/python2.7/site-packages/grpc/_cython/cygrpc.so, 2): no suitable image found.  Did find:
      .../_venv/lib/python2.7/site-packages/grpc/_cython/cygrpc.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

A Google search suggested that this might be due to a library being built in a way that works for Linux but not for OSX?

**Comment by murgatroid99** [comment]
It looks like you built the C++ client and server and then ran Python code. Can you be more specific about the steps you took after `make install`?

**Comment by soltanmm** [comment]
Huh. I didn't realize `make` for Python was still a thing... How does `pip install .` fare? `GRPC_PYTHON_BUILD_WITHCYTHON=1 pip install .`?

Will check out what's up with `make` later.

**Comment by awan1** [comment]
Here are the commands afterwards:

    # Install the requirements for the scripts
    pip install \
        googleapis-common-protos==1.1.0 \
        protobuf==3.0.0b2 \
        requests==2.9.1 \
        grpcio==0.13.0

    # Install the requirements for the web app
    pip install webapp2 webob jinja2 paste

And then we run the python client.

**Comment by murgatroid99** [comment]
I'm nearly positive that the `pip install grpcio` is what installed everything relevant for Python, and that whatever you built with `make` was not used.

**Comment by murgatroid99** [comment]
Unless the Python library attempts to link against an already installed copy of the C core if it is present. I don't know if it actually does that.

**Comment by awan1** [comment]
I believe when we just used pip install grpcio we didn't get the `which grpc_python_plugin` and maybe we didn't get `protoc` either. But we were installing 0.13.0, maybe this was addressed.

**Comment by awan1** [comment]
Things look good with `GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .`, @soltanmm . Thanks! Consider my concerns resolved. I'll leave the ticket to you in case you want to track `make` shenanigans.

**Comment by soltanmm** [comment]
@awan1 Good to hear! If you want `protoc` behavior, there's the package `grpcio-tools`, now up on PyPI.

After a brief survey of our `Makefile`, it looks like we don't actually have anything leftover for Python there save for the convenience target `test_python`.
