### ISSUE TITLE
how to set grpc serving options to improve performance (python)

### ISSUE THREAD

**Issue by runmouse** [grpc/grpc#6813]
I make a backend service by using grpc, and the programing language is python.
how to choice network module, blocking or non-blocking. 
usually, we can set thread num to get more qps. how can i do something like this with grpc + python.

**Comment by nathanielmanistaatgoogle** [comment]
What problems with performance are you seeing? And are you seeing performance problems with `grpcio` 0.14.x or are you working from source control head (there's currently a factor-of-ten difference between the two)?
