### ISSUE TITLE
How to connect to server using C-core API

### ISSUE THREAD

**Issue by yookyoung89** [grpc/grpc#6814]
I want to connect to google cloud server using c core APIs. ( I develop using C language) 
So, I need confirm about working steps. 
1. library and API
    - APIs in grpc/include/grpc
    - Libraries in grpc/libs/opt
      (libboringssl.a, libgpr.a, libgrpc.a, libgrpc_plugin_support.a, libgrpc_unsecure.a, libz.a, 
      libprotobuf.a, libprotoc.a)
1. Create client 
   (1) grpc_init()
   (2) grpc_secure_channel_create()
   (3) grpc_completion_queue_create()
   (4) grpc_channel_create_call()
   (5) grpc_call_start_batch() : add options
   (6) grpc_completion_queue_next()
   (7) grpc_call_destroy()
   (8)grpc_shutdown()

Confirm please.

**Comment by soltanmm** [comment]
IIRC the semi-official stance is: **the C core API is private and unstable** and *not* meant for use outside of being wrapped by higher-level languages within the gRPC project umbrella. A *supported* C API is slated for the post-GA future.

Having said that... you have the basic gist of the process down (missing a few destructor calls, though; [here's a relevant test](https://github.com/grpc/grpc/blob/master/test/core/end2end/no_server_test.c)). Just don't be surprised if/when your code suddenly doesn't work across a minor version bump even after we go GA with version 1.0.

**Comment by binodluitel** [comment]
Can someone from Google chime in to this question please?

**Comment by soltanmm** [comment]
Oof... Where's the nearest burn center? I might need a trip to one...
