### ISSUE TITLE
socket error: connection refused in iOS app

### ISSUE THREAD

**Issue by heisonyee** [grpc/grpc#6818]
I started my iOS app, and made request WITHOUT starting up the gRPC server(by Java)，and i got log like this:

0607 17:22:29.033707000 123145303453696 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:10010': socket error: connection refused

In this scenario,  my iOS client request without any response, throwing an error in handler block for handling "connection refused" would be a good idea?
Thank you for any help.

**Comment by makdharma** [comment]
https://github.com/grpc/grpc/blob/master/doc/statuscodes.md has the status and error codes. You should see a UNAVAILABLE status returned by the RPC in your error handler. Is that not happening?

**Comment by tonygoold** [comment]
@makdharma I am also seeing this issue on iOS. The handler block is never called because `grpc_completion_queue_next` (in `completion_queue.c`) never returns. It appears to be using an exponential back-off strategy with no deadline.

**Comment by jcanizales** [comment]
Can you guys still reproduce this with v1.0?
