### ISSUE TITLE
Provide more details (print error codes) when PHP interop tests fail

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6821]
Starting from build https://grpc-testing.appspot.com/job/gRPC_interop_master/5162/.

This effectively prevents merging pull requests as Interop tests are marked as "Required" for merging.

**Comment by jtattermusch** [comment]
@adelez  @murgatroid99   @stanley-cheung  @kpayson64  any volunteers to look into this?

**Comment by kpayson64** [comment]
The test is now passing.  
https://grpc-testing.appspot.com/job/gRPC_interop_master/5202/

We still probably want to print the error code on interop test failures in PHP.

**Comment by stanley-cheung** [comment]
Fixed by #7897
