### ISSUE TITLE
Provide std::chrono::steady_clock conversions to gpr_timespec

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#6824]
steady_clock represents the CLOCK_MONOTONIC clock. Provide conversion to the gpr_timespec GPR_CLOCK_MONOTONIC clock_type to allow its use in the C++ API.

**Comment by iancoolidge** [comment]
https://github.com/grpc/grpc/pull/6837

**Comment by ncteisen** [comment]
Closing. Hop in if this is still relevant @ctiller
