### ISSUE TITLE
Killing qps workers (qps_json_driver.quit) often fails in multi-machine setup.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6845]
I see this  in several runs. Perhaps the deadline to kill is too low? We really need better assertion messages from qps_driver (https://github.com/grpc/grpc/issues/6540) to know if this was timeout or something else.

```
START: qps_json_driver.quit
WAITING: ETA 38.3 sec; 0 queued, 1 jobs running, 71 complete, 0 failed
D0608 21:49:24.951746273   24414 ev_posix.c:101]             Using polling engine: poll
I0608 21:49:24.953904660   24415 socket_utils_common_posix.c:170] Disabling AF_INET6 sockets because ::1 is not available.
D0608 21:49:24.957329402   24414 ev_posix.c:101]             Using polling engine: poll
D0608 21:49:24.963397458   24414 ev_posix.c:101]             Using polling engine: poll
D0608 21:49:24.969719573   24414 ev_posix.c:101]             Using polling engine: poll
E0608 21:49:24.977848771   24414 driver.cc:440]              assertion failed: stub->QuitWorker(&ctx, dummy, &dummy).ok()
Aborted (core dumped)

FAILED: qps_json_driver.quit [ret=134, pid=24413]
```

https://grpc-testing.appspot.com/job/gRPC_performance_experiment/1254/consoleFull

**Comment by vjpai** [comment]
Currently investigating by adding logging to driver and worker processes, as asked in #6540 .

**Comment by vjpai** [comment]
Confirming that this still occasionally happens at performance master.
https://grpc-testing.appspot.com/job/gRPC_performance_master/6445/console

**Comment by jtattermusch** [comment]
Closing for bankruptcy.
