### ISSUE TITLE
`is` is not

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#6846]
In `_channel.py`, `_end_unary_response_blocking` may raise if `state.code` is not `grpc.StatusCode.OK`. When it does so, it's possible for `state.code` to be `None`. A few stack frames up, in `_client_adaptations.py`'s `_blocking_unary_unary` may catch this error, and then invoke code that waits on the state's condition variable for `code` to become not None. This results in a hang.

I have no minimal demonstration for this, as it's simply happening on Windows in my debugger, in `beta_python_plugin_test`'s `testUnaryCall`, without any further modification.

All other tests had to be skipped, as this appears to happen with all tests that attempt to make a connection.

Even if this is an environment problem with my Windows machine and its firewall (maybe, still unclear), we still shouldn't hang.

**Comment by soltanmm** [comment]
Ah, I did make a small modification; the timeout on the test was turned down from 3000 seconds to 10 seconds and to 1 second.

**Comment by nathanielmanistaatgoogle** [comment]
Tell me more about "it's possible for `state.code` to be `None`" at the time that `_end_unary_response_blocking` is called? Isn't it the case that the completion queue used for the call is drained by that point? And a `receive_status_on_client` operation is guaranteed to have been processed? Is there any circumstance by which that operation may complete with a `None` status code?

**Comment by soltanmm** [comment]
Bwahaha, you're right. Here's a bug:

```python
(Pdb) print 6 is 6
True
(Pdb) print event.batch_operations[5].type
6
(Pdb) print cygrpc.OperationType.receive_status_on_client
6
(Pdb) print cygrpc.OperationType.receive_status_on_client is event.batch_operations[5].type
False
```

And on `_channel.py:149`: [`elif operation_type is cygrpc.OperationType.receive_status_on_client`](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L149).

I see your reference types and raise you a *cloned* value type.

**Comment by soltanmm** [comment]
TIL:

```python
>>> (3L * 2L) is 6L
False
>>> (3 * 2) is 6
True
```

Guess what type `cygrpc.OperationType`. Guess how surprised at Python I am.
