### ISSUE TITLE
Python test always error on windows

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#6847]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/config=dbg,language=python,platform=windows/9653/
https://grpc-testing.appspot.com/job/gRPC_pull_requests/config=opt,language=python,platform=windows/9653/

**Comment by soltanmm** [comment]
Known; they were re-enabled for the sake of #6797 and will remain re-enabled until said PR goes in or someone decides to disable them until said PR is being actively reviewed.
