### ISSUE TITLE
Add example on how to use JWT credentials with python.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6860]
Update http://www.grpc.io/docs/guides/auth.html
https://github.com/grpc/grpc.github.io/blob/master/docs/guides/auth.md  to contain an example how to use JWT credentials.

Add @LisaFC for review.

**Comment by kpayson64** [comment]
@jtattermusch 
I got some push back in #6799 on adding google_call_credentials to the GA API.  I think the plan right now is to not add it to the GA API.  Is it worth adding documentation for the Beta API?

**Comment by jtattermusch** [comment]
Ok, it only makes sense to update the docs once this is part of the official API. Beta API is getting killed soon, so no point in updating that one.

Btw, what I've done for C# to not do depend on the C# auth library (Google.Apis.Auth which provides the JWT and oauth2 logic) is that there is two C# nuget packages  - Grpc.Core  (only exposes the metadata plugin API)   and Grpc.Auth  (that depends on the Google.Apis.Auth library and provides the integration of grpc and google app default credentials).

**Comment by ejona86** [comment]
This came up on SO:
http://stackoverflow.com/questions/39540731/how-do-i-use-jwt-with-grpc/39541040

**Comment by nathanielmanistaatgoogle** [comment]
This is blocked on / will be done as part of [issue 8621](https://github.com/grpc/grpc/issues/8621), which itself is blocked on production-readiness-certification of `google-auth-library-python`.
