### ISSUE TITLE
ServerBuilderOption::UpdatePlugins API is not compatible with gcc-4.4

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6866]
gcc-4.4 is one of gRPC's supported targets , but we have not been doing regular portability testing for it. However, because of [a bug in older versions of gcc] (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=44872) , gcc versions below 4.6 do not support the use of map with unique_ptr as its mapped type. There are also several other associative containers that are not supported in this way. I have attempted to clarify these issues in the C++ style guide in #6865 . There is no workaround to this problem.

There are a few possible solutions:

- Remove the existing API and replace it with something based on std::vector or some other non-associative type. **My preference since this is a relatively new API and most likely will not break existing users.**
- Remove the existing API and replace it with using dumb pointers rather than unique_ptr. Then just delete the pointers in the destructor. This is still API breaking, though, because it requires the user of the UpdatePlugins API to delete any pointers that are changed.
- Keep the existing API but wrap it in an appropriate `#ifdef` . Add a new API for users of older compilers.  This is potentially ugly for requiring us to permanently maintain both versions. 

@y-zeng @yang-g

**Comment by yang-g** [comment]
I think we should avoid ifdef unless it is necessary. Both the first two options look good to me.

**Comment by vjpai** [comment]
Is there any use of allowing the name argument to ever be anything different from plugin->name() ? I would like to disallow that for simplicity (otherwise it requires a vector of a new wrapping struct). Also, is the name-based order of plugins important? Right now, the map iterator will return the plugins in name-sorted order. Switching to vector will either require us to do a std::sort before iterating or return the plugins in insertion order.

**Comment by vjpai** [comment]
@ahedberg Do you have any comments on this? Thanks!

**Comment by y-zeng** [comment]
I think the order of plugins does not have any effects. They are supposed to work independently with each other.

**Comment by vjpai** [comment]
Fixed by #6863

**Comment by jcanizales** [comment]
Hi @vjpai and @dgquintas,

when making a breaking change to the public surface of the API, or reviewing a PR that does, please add a bug to the "import pony saddlebag" (per `go/grpc-import-pony`). This way the person doing the import can anticipate the breakage and the import isn't delayed unnecessarily.
