### ISSUE TITLE
gRPC takes a long time to recover after network issue

### ISSUE THREAD

**Issue by tkchin** [grpc/grpc#6889]
Repro steps:
1. Enter airplane mode
2. Exit airplane mode
3. Immediately send an RPC

Expected:
RPC succeeds or fails fast

Actual:
RPC fails with GRPCErrorCodeUnavailable after ~ 18s
Subsequent retry succeeds

@jcanizales @makdharma

**Comment by jcanizales** [comment]
Hi Zeke, was that with the Cronet networking layer, or without?

**Comment by makdharma** [comment]
Zeke just mentioned that this happens without Cronet. @jcanizales - isn't this the classic network status monitoring case you fixed?

**Comment by makdharma** [comment]
@tkchin I am not seeing this behavior with the RouteGuide sample app. When the phone enters airplane mode the RPCs fail immediately, and start working immediately after coming out of airplane mode. Same is true when wifi is disconnected/connected.

**Comment by jcanizales** [comment]
Maybe he's using an old commit?

**Comment by tkchin** [comment]
I can repro this fairly reliably with my own app on my iPhone 6S. Is there anything I can do to get more logs?

**Comment by jcanizales** [comment]
We should totally enable all core traces after we do `grpc_init()`. Surrounded by an `#ifdef` of some `GRPC_DEBUG` macro.

**Comment by makdharma** [comment]
@jcanizales Can you submit the fix that is already working for @tkchin ?

**Comment by makdharma** [comment]
@jcanizales Please also submit the PR for master branch.
