### ISSUE TITLE
Python DistribTests failing

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6892]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/architecture=x86,language=python,platform=linux/955/console

The __init__.py is not being installed as part of the source distribution, possibly also for binary distribution.

**Comment by soltanmm** [comment]
[I believe this is the fix you're looking for](https://github.com/grpc/grpc/pull/6791/commits/f10cbda5799f00dc8f76867614579b8433c09fa2). Cherry-pick?

**Comment by soltanmm** [comment]
And by 'believe' I mean 'very likely is but I don't remember the details so don't take my word for it'.
