### ISSUE TITLE
Fix coverage reporting for Python

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#6894]
It's been broken for a while.

Preemption: we haven't even looked at test coverage in the past few months, so by virtue of usage (or lack thereof) I'm not prioritizing this. Buut... it should get fixed soon-ish. Should be straightforward after a little bit of digging, keeping in mind the caveat that we decided to allow flakes in coverage testing due to #5689.

**Comment by dgquintas** [comment]
still a thing?

**Comment by nathanielmanistaatgoogle** [comment]
@dgquintas: very much still a thing.

**Comment by hsaliak** [comment]
Re-marking this as P1. Having good coverage is critical, especially for the implementation in dynamic languages.

**Comment by nathanielmanistaatgoogle** [comment]
I'd like for this to be high-priority, but in practice at the present moment it's just not.

**Comment by nathanielmanistaatgoogle** [comment]
To the best of my knowledge this should remain open.
