### ISSUE TITLE
C# Expose server side authentication API

### ISSUE THREAD

**Issue by mocsharp** [grpc/grpc#6907]
Trying to figure out a way to validate access tokens (out-of-band) without having to call the validation API inside each and every server side API implementation.   It would be nice to expose something similar to ASP.NET WebAPI:

E.g. [OnActionExecuting](https://msdn.microsoft.com/en-us/library/system.web.mvc.actionfilterattribute.aspx) or [OnAuthorization](https://msdn.microsoft.com/en-us/library/system.web.http.authorizeattribute.onauthorization%28v=vs.118%29.aspx#M:System.Web.Http.AuthorizeAttribute.OnAuthorization%28System.Web.Http.Controllers.HttpActionContext%29)

**Comment by jtattermusch** [comment]
gRPC C core and gRPC C++ provides hooks for server-side authentication validation, but we aren't exposing the validation hooks in other languages yet.

**Comment by jtattermusch** [comment]
So the feature that solves your problem is coming, but unfortunately there's no ETA currently.

**Comment by yvonguy** [comment]
Any update on ETA?

**Comment by jtattermusch** [comment]
Unfortunately, this likely won't be available before end of 2016. Hopefully in Q1 2017.

**Comment by jtattermusch** [comment]
See https://github.com/grpc/grpc/pull/9632

**Comment by jtattermusch** [comment]
This will be in 1.2 release (coming soon).
