### ISSUE TITLE
A `GRPC::BadStatus` exception is raised at a high degree of parallelism in Ruby

### ISSUE THREAD

**Issue by userlocalhost2000** [grpc/grpc#6910]
Thanks for writing this excellent software.
I report a problem which will occurr when the concurrency of client is increased.

Here is a script that may raise an exception of `GRPC::BadStatus`. This client script is customized one based on [greeter_client.rb](https://github.com/grpc/grpc/blob/release-0_14/examples/ruby/greeter_client.rb).
```Ruby
#!/usr/bin/env ruby

this_dir = File.expand_path(File.dirname(__FILE__))
lib_dir = File.join(this_dir, 'lib')
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'grpc'
require 'helloworld_services'

THREAD_NUM = 50

def main
  stub = Helloworld::Stub.new('localhost:50051', :this_channel_is_insecure)
  user = ARGV.size > 0 ?  ARGV[0] : 'world'
  message = stub.say_hello(Helloworld::HelloRequest.new(name: user)).message
  p "Greeting: #{message}"
end

threads = []
1.upto(THREAD_NUM).each do |_|
  threads << Thread.new do
    main
  end
end
threads.each(&:join)
```

The server script is same with [greeter_server.rb](https://github.com/grpc/grpc/blob/release-0_14/examples/ruby/greeter_server.rb).
When `greeter_client_custom.rb` which is previously shown executed, a `GRPC::BadStatus` will be raised as below.
```
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/grpc-0.14.1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:48:in `check_status': 8: (GRPC::BadStatus)
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/grpc-0.14.1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:197:in `finished'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/grpc-0.14.1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:330:in `request_response'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/grpc-0.14.1-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/grpc-0.14.1-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:184:in `block (3 levels) in rpc_stub_class'
        from greeter_client_concurrently.rb:15:in `main'
        from greeter_client_concurrently.rb:22:in `block (2 levels) in <main>'
```

When I reduce the `THREAD_NUM` that is hard-coded in `greeter_client_custom.rb` to `30` or less, this exception has never been occurred in my environment as below.

Ruby: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]`
gRPC (gem): `grpc (0.14.1 x86_64-linux)`
gRPC tools (gem): `grpc-tools (0.14.1)`

Thank you.

**Comment by murgatroid99** [comment]
The status code 8 indicates "Resource Exhausted". It means that the server rejected the call because it had too many outstanding calls, and that you should retry.

**Comment by userlocalhost2000** [comment]
Thank you for your reply.

I corrected [greeter_client_custom.rb](https://gist.github.com/userlocalhost2000/60fbaa03e95656410d7ef256fbe39ce4) based on your advise, wihch is customized from [greeter_client.rb](https://github.com/grpc/grpc/blob/release-0_14/examples/ruby/greeter_client.rb) example.

Then, I could get a desired result like following!
```Bash
vagrant@localhost:~/grpc/hello$ ruby greeter_client_custom.rb | uniq -c
     50 "Greeting: Hello world"
vagrant@localhost:~/grpc/hello$ 
```

Thank you so much!!
