### ISSUE TITLE
NodeJS protobuf server error freezes client

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#6927]
Hello,

when calling back with an illegal value the server throws an error but the client never gets an answer.
It waits forever or until deadline.

To test it, change the greeter_server.js sayHello function to this:
`
function sayHello(call, callback) {
  callback(null, []);
}
`

If this is per design, how can I send a response to the client after the callback failed?

**Comment by murgatroid99** [comment]
The first argument to the callback is the error argument. If you want to send an error to the client, call the callback with just an Error object.

**Comment by marshauf** [comment]
That I know.
Modify the greeter_server.js sayHello function
```js
/**
 * Implements the SayHello RPC method.
 */
function sayHello(call, callback) {
  try {
    callback(null, []); // throws "Illegal value for Message.Field .helloworld.HelloReply.message of type string: object (no array expected)"
  } catch(err) {
    // caught but callback with error does not reach client
    // clients waits on callback
    callback(err);  
  }
}
```

**Comment by murgatroid99** [comment]
I see now. Yes, we make that situation pass an INTERNAL error to the client.
