### ISSUE TITLE
C# GrpcEnvironment.ReleaseAsync hangs

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#6930]
Environment: C# with Windows 7

I have a console application which uses a windows form with ```Application.Run``` like in a WinForms application. As long as I don't create an instance of a form, everything works fine. As soon as I instantiate a form (even if I don't show it or call ```Application.Run```), the call to ```server.KillAsync().Wait()``` hangs.

I tracked the problem, and it looks like ```GrpcEnvironment.ShutdownAsync``` called on ```instanceToShutdown``` in ```GrpcEnvironment.ReleaseAsync``` (last call in ```Server.ShutdownInternalAsync```) is stuck in the await call. When I look into the ```ShutdownAsync``` processing, it get's through the complete method without problems and also the ```Task``` in ```GrpcThreadPool.StopAsync``` works where all the threads are joined and disposed. So I really don't understand why it hangs.

What I tried to fix it (what seems to work) is this:
```
diff --git a/src/csharp/Grpc.Core/GrpcEnvironment.cs b/src/csharp/Grpc.Core/GrpcEnvironment.cs
index e9e4cb4..58bb180 100644
--- a/src/csharp/Grpc.Core/GrpcEnvironment.cs
+++ b/src/csharp/Grpc.Core/GrpcEnvironment.cs
@@ -105,7 +105,7 @@ internal static GrpcEnvironment AddRef()
 
             if (instanceToShutdown != null)
             {
-                await instanceToShutdown.ShutdownAsync();
+                await instanceToShutdown.ShutdownAsync().ConfigureAwait(false);
             }
         }
```

I haven't really worked with ```ConfigureAwait``` yet and don't know the side effects of it. I just saw that every other method in the calling hierarchy also did it and only this call was missing it, so I gave it a try.

If you need a minified example I could extract you one. This is pretty deterministic and happens every time I execute it.

**Comment by jtattermusch** [comment]
I cannot be sure from the description itself, but it seems like you are facing a problem with winforms synchronization context.

This article should explain the deadlock:
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

From where exactly are you calling the `server.KillAsync().Wait()` line? (it that from the UI thread? looks like it is).

**Comment by jtattermusch** [comment]
Also, which version of Grpc are you using?

**Comment by Falco20019** [comment]
Thanks for the article and merging as #6984 . I was using the current master.

```KillAnync()``` was called from the console thread. I only have instantiated the form and have not even called ```Application.Run```, nor have I invoked it on the form or called ```Show()``` on it. Just creating an instance was enough to trigger the problem. This is what made me wonder.

I will continue my tests with the newest master and hope that everything works :) If not, I will write again.
