### ISSUE TITLE
Install broken at head?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#6935]
Inspired by [this comment](https://github.com/grpc/grpc/issues/5640#issuecomment-226540755), I just went and did a fresh install from master on a fresh virtual machine. Following installation of all dependencies and a `make test_python`, `GRPC_PYTHON_BUILD_WITH_CYTHON=1 venv/bin/pip install --upgrade .` completes successfully, but the `grpc` package is missing code elements:
```
nathaniel@instance-1:~/grpc$ venv/bin/python2.7 
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> from grpc import _auth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nathaniel/grpc/venv/local/lib/python2.7/site-packages/grpc/_auth.py", line 43, in <module>
    class GoogleCallCredentials(grpc.AuthMetadataPlugin):
AttributeError: 'module' object has no attribute 'AuthMetadataPlugin'
>>> dir(grpc)
['__doc__', '__name__', '__path__']
>>> 
```
. My guess would be that this comes from the packaging change of a few days ago? Please investigate.

**Comment by kpayson64** [comment]
Resolved by #6896.
