### ISSUE TITLE
Python: package with dependency on grpcio fails to install

### ISSUE THREAD

**Issue by geigerj** [grpc/grpc#6939]
I can't get packages that have a dependency on grpcio to install; they fail with the message

```
...
third_party/zlib/gzwrite.c: In function ‘gzclose_w’:                                                                                                                     
third_party/zlib/gzwrite.c:573:5: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]                                                    
     if (close(state->fd) == -1)                                                                                                                                         
     ^                                                                                                                                                                   
zip_safe flag not set; analyzing archive contents...                                                                                                                     
No eggs found in /tmp/easy_install-PByQ05/grpcio-0.14.0/egg-dist-tmp-qwx9F0 (setup script problem?)                                                                      
error: The 'grpcio>=0.14.0' distribution was not found and is required by [...] 
```

Strangely, it seems possible to work around this by installing grpcio explicitly using pip.

I am able to reproduce the error with a minimal Python package on a clean virtual machine. That package is available here, with steps to reproduce in the README: https://github.com/geigerj/temp-repo

The full error message is available here: https://gist.github.com/geigerj/951aa1db2fdd732f3feaa68549e83cfd

**Comment by geigerj** [comment]
@bjwatson

**Comment by daspecster** [comment]
Looks like this might be a key piece?
https://gist.github.com/geigerj/951aa1db2fdd732f3feaa68549e83cfd#file-install_output-txt-L43

**Comment by daspecster** [comment]
Looks like this might have been related?
https://github.com/grpc/grpc/issues/6075

**Comment by daspecster** [comment]
So I noticed that in the pre-release 0.14.1 that there are some updates for grpcio.
See: https://github.com/grpc/grpc/releases/tag/release-0_14_1

I haven't been able to get it to build the bdist_egg.

**Comment by soltanmm** [comment]
Note to self: set the `zip_safe` flag on distributions.

**Comment by kpayson64** [comment]
@soltanmm 
In #6439, we decided we did not want to support egg distributions.  I had a quick fix #6437 for this, but we decided to not integrate it.

In light of this use case, do we want to re-evaluate?

**Comment by jtattermusch** [comment]
Was this fixed by https://github.com/grpc/grpc/pull/6437?

**Comment by nathanielmanistaatgoogle** [comment]
Yes.

**Comment by bjwatson** [comment]
Is there an estimate for when `0.15.0` will be released?

**Comment by nathanielmanistaatgoogle** [comment]
@bjwatson: we think it will be in the next seven days.

**Comment by bjwatson** [comment]
Thanks.
