### ISSUE TITLE
Make grpc_clang_format not depend on current LLVM APT

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6946]
The LLVM Apt repo has been down since June 1, and the wget result from that page has now fallen out of our workers' caches. This will make all sanity checks fail because grpc_clang_format Dockerfile uses this in one of its setup stages.

**Comment by ctiller** [comment]
Can we build it from source?

**Comment by jtattermusch** [comment]
what version of clang do we need?

**Comment by dgquintas** [comment]
is this still a thing?

**Comment by vjpai** [comment]
It's working now.
