### ISSUE TITLE
Master tracking issue for cross-compilation support

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6956]
Recent cross-compiling issues:
- #6925 (x86/Ubuntu host, ARM target)
- #6756 (x86/Ubuntu host, ARM target)

There was some previous discussion of cross-compilation in grpc-io: https://groups.google.com/forum/#!msg/grpc-io/l8v12QEUmO0/iK9gYf_So1EJ

Besides the discussion given above, proper cross-compilation requires configuring protobuf with the --host=XXX parameter (such as --host=arm-linux ).

Assigning it to @zinuga so that he can track it

**Comment by tberghammer** [comment]
I created a cmake based build system with cross compiling support at https://github.com/tberghammer/grpc/commit/d798a7d80e80ad1e57b08baec81b860c7f136c47

After specifying the right cmake toolchain file I managed to use it for cross compiling from {Linux, OSX} -> Android {arm, aarch64, x86} as well as for Linux x86_64 -> Linux arm

(I am happy to create a pull request for it but it might need some cleanup first)

**Comment by vjpai** [comment]
@tberghammer , very good to know. Yes, we'd very much like to see it. 

Cc: @nicolasnoble

**Comment by tberghammer** [comment]
I created a pull request for it at https://github.com/grpc/grpc/pull/6997. It should be enough for get people going but I am pretty sure it will have to be fine tuned to support all required scenario
