### ISSUE TITLE
Python support grpico egg distributions

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6989]
There is some interest in using grpcio as a dependency in egg distributions: #6939.

#6437 was used as a workaround, but we are not sure if that is the best way to ensure that the .egg-info files get properly packaged.  The likely issue is that our setup.py is not contained in the root directory of our grpcio package, and setuptools gets confused, but this requires more investigation.

**Comment by soltanmm** [comment]
[Eggs are not standardized](https://packaging.python.org/en/latest/wheel_egg/) and for a long, long time the community's been trying to phase them out of existence. [A standard RFC](https://www.python.org/dev/peps/pep-0376/) they violate was spec'd in the days of Python 2.6 for Python 2.7. We've dropped support for Python 2.6 as a goal despite some people being stuck with ancient interpreters (e.g. as a default system installation on some 'Windows's).

My current inclination is thus towards burying this side-by-side with Python 2.6 support.

**Comment by kpayson64** [comment]
I'm fine closing this as a "No Plan To Fix" then.

**Comment by bjwatson** [comment]
IIUC, we'll have `egg-info` in `0.15.0`, per https://github.com/grpc/grpc/pull/6437, but there's no guarantee that it will work correctly, since this is something we should move away from anyway. Is this correct?

**Comment by soltanmm** [comment]
@bjwatson Yep.

**Comment by bjwatson** [comment]
Thanks @soltanmm
