### ISSUE TITLE
InvalidOperationException in GRPC SendStatusFromServerAsync [C#]

### ISSUE THREAD

**Issue by angshuman** [grpc/grpc#6990]
I am getting the following exception everytime I make a GRPC call. I am using both server side and client side streaming. This is not really affecting correctness of the communication but it is very annoying to get this all the time. I create a new stream for each call and close the stream when the response is received. The exception I get is the following - 

> W0621 17:29:07.808967 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Tuple`2 optionalWrite)
>    at Grpc.Core.Internal.DuplexStreamingServerCallHandler`2.<HandleCall>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Grpc.Core.Server.<HandleCallAsync>d__14.MoveNext()

PS: I upgraded to 0.14 but I still see the same thing.

**Comment by angshuman** [comment]
This issue seems to be related but I am not sure. https://github.com/grpc/grpc/issues/5977

**Comment by apolcyn** [comment]
If this is still happening with the latest versions (0.15 or 1.0.0), can you please provide how you're reading requests, writing responses, and closing the stream? Also I take it that this is happening on duplex streaming calls, and the exception is happening on the server side?

**Comment by gazialankus** [comment]
This may be helpful: https://github.com/grpc/grpc/issues/8277#issuecomment-276501032
