### ISSUE TITLE
Provide some basic testing for ruby on windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#7000]
This is hard to do as ruby in crosscompiled for windows. Our options:
1. figure out how to run windows tests despite the problems
2. enable and extend ruby distribtests on windows so that they offer better feature coverage and partially substitute for the lack of ruby unit tests on win.

**Comment by jtattermusch** [comment]
CC @murgatroid99

**Comment by nicolasnoble** [comment]
Honestly, this is pretty much a nightmare. We have two big possible solutions:

- Get the test to build from Linux, then cascade onto Windows for testing. This is something we'll eventually need to kind of do for cross-compilation testing anyway.
- Get the ruby "toolchain" to work on Windows.

**Comment by nicolasnoble** [comment]
Let's move that out of the GA milestone.

**Comment by jtattermusch** [comment]
I don't think anyone's going to work on this anytime soon. closing
