### ISSUE TITLE
Double-double-underscore methods not documented

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7015]
[This class](http://www.grpc.io/grpc/python/grpc.framework.interfaces.face.html#grpc.framework.interfaces.face.face.UnaryUnaryMultiCallable) defines a `__call__` method and is intended to be directly called by users, but the documentation for the `__call__` method is omitted from the class documentation as though the method were private or absent.

Perhaps there's a flag we're not yet passing to our documentation generation command, or perhaps the class doc string should be the place to document a class' implementation of double-double-underscore methods like `__call__`, `__iter__`, and the like?

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: this would be nice to have for GA but I think I can live with it landing soon after - do you feel similarly?

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle I think we can all live with this landing soon after. Moving it out.

**Comment by soltanmm** [comment]
There's now a simple PR that fixes this open, so, might as well stuff it back onto GA track.

**Comment by soltanmm** [comment]
Fixed in #7355. Will be fixed on master on upmerge.
