### ISSUE TITLE
Python documentation being omitted from release process

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7016]
[This page](http://www.grpc.io/grpc/python/index.html) is still serving 0.13.1rc1 documentation.

**Comment by soltanmm** [comment]
I'm not sure what's actionable about this beyond, "Remember to invoke `./tools/distrib/python/docgen` for each release!"

... Which I've admittedly forgotten to do several times.

@hsaliak Did you have anything specific in mind? Does this issue want process documentation?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm: what I had in mind in filing this was something toward push-button releasing. What would you think of a release script? Either executable or plain manual instructions?

**Comment by soltanmm** [comment]
I think I wish Jenkins wasn't such a black box to us. :-/

Are manual instructions satisfactory for now?

**Comment by nathanielmanistaatgoogle** [comment]
Very much!

**Comment by soltanmm** [comment]
Instructions are now linked to the internal release process docs (which I'd totally make open if internal docs allowed that...).
