### ISSUE TITLE
DNS resolving is too primitive.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#702]
We need to rewrite the async DNS resolver. Potentially using something c-ares-like.

**Comment by jtattermusch** [comment]
still an issue?

**Comment by dgquintas** [comment]
@y-zeng is this a duplicate of the work you've been doing lately?

**Comment by y-zeng** [comment]
Yes, let's use this issue to track the work.

**Comment by vjpai** [comment]
This issue is done now, right? Please close if so.

**Comment by y-zeng** [comment]
Implementation of the async DNS resolver is done, but it's still not the default DNS resolver.
