### ISSUE TITLE
Early OK

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7032]
It should not be required that the service-side application read all, or even any, messages from the client before concluding the RPC with OK status.

**Comment by kpayson64** [comment]
@nathanielmanistaatgoogle 
Thoughts on bumping this up to GA?  If we felt that Python being forced to iterate over all messages was a GA bug, aren't we in a strictly worse scenario if it applies to all the wrapped languages?

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: Note that [issue 6891](https://github.com/grpc/grpc/issues/6891) has been deferred to 1.1. I would love for this to happen for GA but note that there's no harm in it happening later other than having to wait however long is the delay.

**Comment by nathanielmanistaatgoogle** [comment]
Any news on this in the last seven months? Is this still something that might happen, or is it something that will happen or will never happen?

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: despite our exchange over lunch today I'm still not yet sure that this is resolved. As a demonstration, removing [these four lines](https://github.com/grpc/grpc/blob/c4a7f8dfe97c8fbc3b85d09cb2e92111d3a0014e/src/python/grpcio_tests/tests/unit/_metadata_code_details_test.py#L135-L138) causes the test to fail with code `UNKNOWN` and details `Error in HTTP transport completing operation`. Is there something I'm misunderstanding? Is this still an active issue in your judgement as well?

**Comment by nathanielmanistaatgoogle** [comment]
I stumbling across this and losing time to it - how hard would this be to just implement?

It doesn't seem to be the case that when a service-side application starts a batch that includes a status operation without first having exhausted the request stream that the Core fails the batch-starting with a `grpc_call_error` (right? I'm only mostly sure of this) - should it? Could it? Otherwise an application doing Early OK just sees their server stop responding to requests for no understood reason (right?).

**Comment by ctiller** [comment]
If there's a core end2end test written for this, I'll see to it sometime Q4

**Comment by nathanielmanistaatgoogle** [comment]
Won't be able to implement it soon but before it slips my mind: tests should probably cover something like the cross product of

* client sends no requests
* client sends (or at least attempts to send before the RPC is completed) well over a flow control window's worth of requests

,

* client doesn't ever attempt to read a response
* client attempts to read all responses

,

* server doesn't read requests
* server reads one request

, and

* server sends zero responses
* server sends one response
* server sends well over a flow control window's worth of responses

.

**Comment by Titanssword** [comment]
Hi, I am Sword, I read about this on GSOC'18 ideas page, and I think the "Early OK" idea sounds pretty cool. But the I am not sure how to define the OK status and in which situation should return "Early OK". Here just are my thinkings, firstly, "Early OK" should (could?, may?) be different from the real "OK", the client can distinguish them, and then set a trigger at the server side, for example, If the server side application has recevied more than 1000 requests or the memory usage is up to certain threshold, the trigger will remind the server side application to return "Early OK" to client, and free the memory. 
Another thinking, put the steam requests into chunks, when recevie one thunk, if it is OK, the server return "Early OK" with respect to this chunk. But I am still confused, if there are something wrong at the server side after sending the "Early OK", what should the server do? send another response to tell the client ? 
Would like to have some feedback.

**Comment by nathanielmanistaatgoogle** [comment]
@Titanssword: I think you may be overthinking it - check out the "two-by-two matrix" that I described [here](https://groups.google.com/d/msg/grpc-io/vkEsyzeSAoI/Gx01XZjOBwAJ). This issue isn't about changing or expanding the meaning of OK status to anything that it doesn't mean today (the RPC is over and it completed satisfactorily); this issue is just about making it possible for service-side applications to send it earlier in the RPC than they are currently able to send it.

**Comment by yang-g** [comment]
This looks like it is supported already. @nathanielmanistaatgoogle is adding a test in python and there is a test in C++ https://github.com/grpc/grpc/blob/master/test/cpp/end2end/server_early_return_test.cc. 

@Titanssword Sorry for the confusion. Please take on some other ideas!
