### ISSUE TITLE
node.js client in react-native

### ISSUE THREAD

**Issue by tcak76** [grpc/grpc#7038]
Can node.js javascript library be used on React-native application as pure javascript library? After installed it, following error occurred in runtime. Is this error is related with library or installation?

Error:
Unable to resolve module path from node_modules/grpc/src/node/index.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/path and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

**Comment by matryer** [comment]
Is it possible to import these packages or is there a fundamental reason why they won't run in react native?

**Comment by ambarc** [comment]
There's a fundamental issue. The way RN works is that it maps to iOS' JS runtime (JavascriptCore) and Android's (V8). Doing so means that libraries native to node (crypto) for example don't translate over. Other libs are solving this issue by providing polyfills (rn-nodeify is an attempt) and some are providing builds that don't depend on node js' core but instead rely on purer JS implementations. RN at 35k stars on Github is getting a lot of popularity. If grpc's goal is to be mobile first this might be a good direction to invest in.

**Comment by divsbhalala** [comment]
Is any update for this suggestion?

**Comment by ambarc** [comment]
@divsbhalala rn-nodeify is where you should start. However, grpc is fairly complex and you should take that as an alpha level suggestion.

**Comment by c100k** [comment]
So right now, what's the better way to implement gRPC in an iOS React Native app ?

I started a thread here : https://stackoverflow.com/questions/44962290/implement-grpc-in-an-ios-react-native-app

**Comment by divsbhalala** [comment]
From last one month, I am doing R&d for gRpcs to use into IOS and Android.
Does any one try to use common method that we can use in both

**Comment by JimmyMow** [comment]
any update or examples of success for gRPC in react native?

**Comment by ademcan** [comment]
Hi guys, any update on using gRPC in RN? thanks.

**Comment by wenbozhu** [comment]
@ademcan  Please have a look at https://github.com/grpc/grpc-web  (which shares the same API as grpc-node).

grpc-web uses google-closure, which is also used by Firebase/firestore web-sdk. We have recently submitted a patch to RN and believe any closure based libraries should be able to run from RN. So, please give it a try and let us know if you manage to get grpc-web clients work from RN.

**Comment by begoat** [comment]
@wenbozhu Hi, I tried grpc-web today. But unfortunately  errors occurred  when send request.
The error log is cannot resolve http module from node_module/grpc-web-client/dist/transports/nodeHttp.js. The version of grpc-web-client is 0.5.0 which is uploaded 3 days ago.

I try to install http nom package, but another error shows that the node_modules/http/package.json was successfully found but this package itself specifies a 'main' module field that couldn't be found.

I also try to install some browserified package instead for example stream-http and change the nodeHttp.js file's requirement, but seems that I will do many serious tweak.

Could someone give me some more suggestions? :)

**Comment by stanley-cheung** [comment]
@begoat The `grpc-web-client` npm package was not owned by us, but rather from the Improbable implementation of the gRPC-web protocol. For error specific to that package, please contact the owners. Thanks.

**Comment by begoat** [comment]
@stanley-cheung Ok, thank u:)

**Comment by richard-joseph-dunelm** [comment]
Please take a look at iImprobable Engineering;s own [grpc-web][1] (unfortunate naming, this appears to *not* be a fork of [the former/official grpc-web project][2]).

Quoting the project's own [][1] page:

> This library is intended for both JavaScript and TypeScript usage from either a browser or Node.js

The possible benefits of iImprobable's version  seem to be:
1. It doesn't appear to use native code (i.e. *no* C/C++/Java)
2. It can generate Typescript (therefore JavaScript) for Node.JS

So, maybe, we could get GRPC-on-RN working, when point No. 2 is coupled with a NodeJS-on-RN project such as [rn-nodeify][3].

Please feed back here if you have any success with this.

[1]: https://github.com/improbable-eng/grpc-web/tree/master/ts
[2]: https://github.com/grpc/grpc-web
[3]: https://github.com/tradle/rn-nodeify

**Comment by sixman9** [comment]
Please take a look at iImprobable Engineering;s own [grpc-web][1] (unfortunate naming, this appears to *not* be a fork of [the former/official grpc-web project][2]).

Quoting the project's own [][1] page:

> This library is intended for both JavaScript and TypeScript usage from either a browser or Node.js

The possible benefits of iImprobable's version  seem to be:
1. It doesn't appear to use native code (i.e. *no* C/C++/Java)
2. It can generate Typescript (therefore JavaScript) for Node.JS

So, maybe, we could get GRPC-on-RN working, when point No. 2 is coupled with a NodeJS-on-RN project such as [rn-nodeify][3].

Please feed back here if you have any success with this.

[1]: https://github.com/improbable-eng/grpc-web/tree/master/ts
[2]: https://github.com/grpc/grpc-web
[3]: https://github.com/tradle/rn-nodeify

**Comment by begoat** [comment]
@sixman9  [There is a discussion there](https://github.com/improbable-eng/grpc-web/issues/141)
and improbable-eng/grpc-web seems cannot work on RN currently.
Currently I use both grpc-java and grpc-objectiveC in my react-native project instead and it works well

**Comment by begoat** [comment]
the propject grpc/grpc-web isn't open source until 20 days ago i think.
Anyway it's great if there is support for RN from official grpc team :)
