### ISSUE TITLE
Python server send RESOURCE_EXHAUSTED when there are no available thread pools

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#7052]
Currently, when there are no available threads in the server thread pool, the server will queue the response until a thread becomes available.

Ruby sends RESOURCE_EXHAUSTED in this event, Python should probably do the same.

**Comment by nathanielmanistaatgoogle** [comment]
See also [issue 8616](https://github.com/grpc/grpc/issues/8616) (particularly ["The fact that gRPC Python accepts `futures.ThreadPoolExecutor objects` from applications may make this hard; we should sit down at some point and talk over how we might solve it."](https://github.com/grpc/grpc/issues/8616#issuecomment-273567713)) and [issue 8603](https://github.com/grpc/grpc/issues/8603).

Punting from `1.1.0`; while this is a priority it doesn't seem to be an urgent priority.

**Comment by vjpai** [comment]
Hi there, could I suggest something tighter than "Someday"? This is a bug, not a feature request, and it can lead to deadlock if a service implementation is particularly perverse. That said, I'm not familiar enough with futures to understand the impact of the previous comment. I'd be glad to have a discussion on this.

**Comment by vjpai** [comment]
@nathanielmanistaatgoogle and I discussed this. The AI is to add an optional argument to the server to specify maximum concurrent RPCs. If someone actually has a service with the requisite circular dependence, then they should specify correctly (no more than the thread limit) to make things not deadlock.

**Comment by nathanielmanistaatgoogle** [comment]
Yep - this is the right action for 1.x. I'm _slightly_ inclined to think about a better API for exposing the same capability in 2.0-and-beyond, but that's far enough away that I'm not yet thinking too hard about it. I do disfavor optional arguments though, so maybe I'll get worked up enough about it to plan something.

**Comment by therc** [comment]
This is problematic, as it can lead to a backlog of requests and prevents clients from retrying elsewhere.

**Comment by vjpai** [comment]
To follow up on my earlier message, an issue remains that it can be difficult for a service implementer to know for sure that his or her service doesn't involve a circular dependence somewhere down the chain of invocations.

**Comment by therc** [comment]
For anyone in the same boat, we tried to find the least invasive hack possible and ended up monkey patching `_handle_call()`. The gRPC thread pool has a special second pool attached to it. When the gRPC thread pool is full, we invoke `_handle_method_handler()` with a custom `RPCMethodHandler` (that returns `RESOURCE_EXHAUSTED` every time) and the second pool (since the gRPC one is full).

Hopefully, we can retire this hack with 1.2.

**Comment by kpayson64** [comment]
This will be fixed in the upcoming 1.2.0 release.
