### ISSUE TITLE
composite_call_credentials should be able to compose arbitrarily-many-more-than-one CallCredentials objects

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7056]
Right now it directly maps onto the core's `composite_call_credentials` function, which just takes two call credentials objects. It should instead take a sequence of `CallCredentials` of length at least one (or, to be really crazy, an iterable that yields at least one `CallCredentials`?).

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak, @kpayson64, @soltanmm, @jboeuf: if we were to change `composite_call_credentials` and `composite_channel_credentials` to take arbitrarily many `CallCredentials` objects, do we favor a single argument that is a sequence or iterable (so that calls look like `composite_channel_credentials(my_channel_credentials, my_list_of_many_call_credentialses)`) or do we favor `*call_credentialses` (so that calls look like `composite_channel_credentials(my_channel_credentials, my_first_call_credentials, my_second_call_credentials, my_third_call_credentials)`)? I could go either way.

Anyone have a better idea of what is the plural of "credentials"?

**Comment by kpayson64** [comment]
I'd go with the former, ```composite_channel_credentials(my_channel_credentials, my_first_call_credentials, my_second_call_credentials, my_third_call_credentials)```.  I think most channels will end up using a single call_credentials, and being force to create a singleton in the most common use case feels more awkward then potentially being forced to unroll a list.

**Comment by jboeuf** [comment]
I  think that this is a python style question for which I don't feel super qualified to answer...

The idea in core (and C++) is that you can call composite_core_credentials multiple times:
```
call_composite1 = composite_call_creds(creds0, creds1)
call_composite2 = composite_call_creds(call_composite1, creds2)
channel_creds = composite_channel_creds(channel_creds0, call_composite2)
```
But that may not be very pythonic....
I could picture something like:
```
composite_call_creds(*args) <- CallCreds
composite_channel_creds(channel_creds, call_creds) <- ChannelCreds
```
so that you could call `composite_channel_creds` like this:
```
my_channel_creds = composite_channel_creds(ssl_creds, composite_call_creds(call_creds1, call_creds2))
```

**Comment by nathanielmanistaatgoogle** [comment]
Fix drafted in [pull request 7163](https://github.com/grpc/grpc/pull/7163); dropping **API BREAKAGE** label as the drafted change is not API-breaking.

**Comment by nathanielmanistaatgoogle** [comment]
Fixed in [pull request 7163](https://github.com/grpc/grpc/pull/7163).
