### ISSUE TITLE
Think about chaining credentials calls

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7057]
An API reviewer invites us to consider code like `channel_credentials = foo.ssl_channel_credentials( ... ).compose(foo.metadata_call_credentials())`. Is this something we want to do?

(I suspect not.)

**Comment by kpayson64** [comment]
Call chaining feels more natural in Java than in Python to me.  I like the solution proposed in #7056 better, and I think it addresses the core issue the reviewer was facing.

**Comment by jayantkolhe** [comment]
Lets consolidate this with similar issue #7056

**Comment by nathanielmanistaatgoogle** [comment]
For anyone following along: we did think about this and we are not going to do it.
