### ISSUE TITLE
Provide example with more than one stub sharing a single channel

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7058]
With all of our examples just having channels used by one stub each it's not clear to all developers that channels are intended to be shared among stubs.

**Comment by kpayson64** [comment]
I'd like to bump this post GA, none of the other wrapped languages have a multiple stub/single channel example right now.

**Comment by nathanielmanistaatgoogle** [comment]
Fix coming in [pull request 7417](https://github.com/grpc/grpc/pull/7417).

**Comment by nathanielmanistaatgoogle** [comment]
Multiplex example added in [pull request 7417](https://github.com/grpc/grpc/pull/7417).
