### ISSUE TITLE
Provide example with more than one servicer sharing a server

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7059]
This is a key use case (and something that wasn't possible with the Beta API).

**Comment by kpayson64** [comment]
I'd like to bump this post GA, none of the other wrapped languages have a multiple servicer server example right now.

**Comment by nathanielmanistaatgoogle** [comment]
Fix coming in [pull request 7417](https://github.com/grpc/grpc/pull/7417).

**Comment by nathanielmanistaatgoogle** [comment]
Multiplex example added in [pull request 7417](https://github.com/grpc/grpc/pull/7417).
