### ISSUE TITLE
Add host parameter to stub constructor parameters and service registration parameters

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7060]
@ctiller, @jtattermusch: we talked about this briefly during the GA API pull request code review; has anything changed? Does `host` still work best for intended use cases as a per-stub value?

**Comment by nathanielmanistaatgoogle** [comment]
Also @ctiller how should `host` be documented? From the core API it kind of looks like a namespace-like thing that travels with the method name entering on the invocation side and emerging on the service side. Does its value alter the behavior of core in any way?

**Comment by jtattermusch** [comment]
1. I do not think we need `host` exposed for GA if there's a non-breaking way to add it later (I don't think it's exposed in all wrapped languages anyway - e.gg C# support it on the client side only and it can be added to the server side later).

2. setting host per-stub should be fully sufficient. "host" is a concept of virtual server and looks like it only makes sense to use it for a service as a whole (so stub should work fine), not per-method.

Ad documentation:
With using the host parameter, you can basically have several "virtual" host on the same server.
I THINK the "host" parameter basically gets translated into an "authority" HTTP2 header (which should be enough info for users that want to dig deeper").

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle  feel free to remove the milestone if you think we can add it in a non-breaking fashion later.

**Comment by nathanielmanistaatgoogle** [comment]
I think we're close to confirmation that on the client side `host` can be a post-GA addition of an optional parameter to stub construction, but I'm less clear on the server side. @ctiller: should `host` be an optional parameter added to [`add_generic_rpc_handlers`](https://github.com/grpc/grpc/blob/01d7dbac1f747ca45135f1d79c38656db0701ec6/src/python/grpcio/grpc/__init__.py#L846) (and also to generated methods like `add_MyServiceServicer_to_server`) or do we intend to support use cases such as server code sending five streaming responses, examining the host value, taking some action based on the host value, and then sending five more streaming responses than it would have sent had the host value been different?

**Comment by ctiller** [comment]
I think a per service registration scheme is sufficient (with a wildcard any host default)
