### ISSUE TITLE
Change list of handlers supplied at server construction time optional

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7062]
Many or most developers constructing servers will be using services defined in protocol buffers and won't have any `GenericRpcHandler`s to pass at server construction. The sequence of handlers passed at server construction time should be an optional keyword parameter rather than a required positional parameter.

**Comment by hsaliak** [comment]
One way of mitigating API breakage is also to provide a reasonable default for the thread pool so that we do not have to swap the order of the positional arguments?https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L1210

**Comment by nathanielmanistaatgoogle** [comment]
I don't think there's going to be a reasonable default for the thread pool (this was a lesson learned in alpha).

I think in order of preference:

1. Let's fix the API to what we really want it to be. We'd be breaking a pre-1.0 API, so we'd be technically allowed to do so, and we'd be breaking it in such a way that the incompatibility shows up at system construction time (as opposed to an incompatibility that allows the system to appear to function for some time and then only become apparent later) and in such a way that would be trivial to fix.
2. Let's keep it the way it is and live with applications passing empty lists.
3. Something in the middle.

**Comment by nathanielmanistaatgoogle** [comment]
So here's an idea of how we might get [(1)](https://github.com/grpc/grpc/issues/7062#issuecomment-228560383): [we haven't yet pushed a package for 0.15](https://pypi.python.org/pypi/grpcio). The content of 0.15 may be fixed, but since the GA API is new in 0.15, no one's actually yet using it. We could merge [commit f58ddf76d87](https://github.com/nathanielmanistaatgoogle/grpc/commit/f58ddf76d870590e077367b212b9b2be3f9ed3c9) into the 0.15 line, call it 0.15.1, and package that. Doing so wouldn't break anyone using the `grpcio` package for their dependency on gRPC Python, and it wouldn't hurt those using master all that much (no more than the churn for which they signed up anyway).

@soltanmm, @kpayson64, @hsaliak: what do you think?

**Comment by kpayson64** [comment]
I propose that we cut 0.15 ASAP and amend our release notes to say that we are releasing a final API preview* (*likely to change before 1.0).  We have other API breaking changes in the works, including the Python3 str->bytes, snake_case for generated code, and supporting many call credentials.

**Comment by nathanielmanistaatgoogle** [comment]
I like @kpayson64's [suggestion](https://github.com/grpc/grpc/issues/7062#issuecomment-228783088).
