### ISSUE TITLE
Investigate "pip install grpcio-tools" source install

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7074]
[In another issue](https://github.com/grpc/grpc/issues/5738#issuecomment-226558577) @parkan writes that `pip install grpcio-tools -I --no-binary grpcio-tools` fails with `grpc/tools/main.cc:33:10: fatal error: 'src/compiler/python_generator.h' file not found`.

I was able to reproduce this on a new machine with
```
$ sudo apt-get install libprotobuf-dev libprotoc-dev
$ virtualenv venv
$ venv/bin/pip install --upgrade pip
$ venv/bin/pip install --upgrade cython
$ venv/bin/pip install grpcio-tools -I --no-binary grpcio-tools
```
.

**Comment by hsaliak** [comment]
Pulled in at  
and needed for the compiler https://github.com/grpc/grpc/blob/master/tools/distrib/python/grpcio_tools/grpc/tools/main.cc#L33
but not included in the distribution..

**Comment by soltanmm** [comment]
Took a cursory glance. The weird thing is: it *is* in the source distribution when I generate it on my local machine.

**Comment by hsaliak** [comment]
I grabbed the source distribution from pypi, it was not present.

**Comment by kpayson64** [comment]
This may be an issue related to grpcio-tools 0.14.0,  I've built the 0.15 grpcio-tools, and the file is definitely present:

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/architecture=x64,language=python,platform=linux/

**Comment by kpayson64** [comment]
I'm closing this as a no-op, I was able to install the exact 0.15.0 sdist that was uploaded to PyPI.  I also verified that it contained src/compiler/python_generator.h

**Comment by nathanielmanistaatgoogle** [comment]
I confirm that the sequence of commands given in this issue's initial report no longer fails.
