### ISSUE TITLE
Performance Monitoring

### ISSUE THREAD

**Issue by laxderek** [grpc/grpc#7075]
I am interested in using some 3rd party software to gather performance metrics for a server application based around gRPC. I'm trying to instrument the application with new relic, and noticed that the server currently doesn't expose lifecycle events, or any other way of knowing when a request has started, and subsequently completed/aborted. Are there any plans to add this? I've noticed there is some metrics tracking infrastructure, but it's entirely internal and doesn't appear to be externally visible, so we're hesitant to make it public. I'm willing to develop this with guidance from the maintainers.

**Comment by nathanielmanistaatgoogle** [comment]
In what language are you working?

**Comment by laxderek** [comment]
I should've specified, sorry. Working in C#

**Comment by laxderek** [comment]
Just wanted to check in and make sure this hadn't fallen off the radar. Any updates on this?

**Comment by jtattermusch** [comment]
We are not planning to add any request interception API in C# in the nearest future. But depending on what you are benchmarking you instrument your code on the client/server side manually (not sure why that's not an option in your case). 

if by the "internal tracking infrastructure" you mean Census, I think that's been available in our repository for a while, but I am not sure in what state the support is. @a-veitch will probably know more.
In general, the plan is to provide a world-class tracing support by implementing it in C core and then all the wrapping languages (C#, Node, Ruby, Python, PHP, ...) will just reuse this builtin support.

@laxderek are you googler?

**Comment by laxderek** [comment]
@jtattermusch I am not a googler, no. I will keep an eye out for this then. If you release it in C we can use it that way. Thanks

**Comment by zinuga** [comment]
@a-veitch as fyi. request to have stats into apm systems like newrelic.

**Comment by LaiYao** [comment]
Why the interception is not support in C#? In my opnion, it's important to allow someone to extend the features or integrate with 3rd system as we support it.

**Comment by hsaliak** [comment]
Redirecting this to @a-veitch and @zinuga to prioritize and come back with some input on whether we are tackling this in the near term.

**Comment by komuW** [comment]
@a-veitch @zinuga 
what say you, RE: the comment by @hsaliak  `Redirecting this to @a-veitch and @zinuga to prioritize and come back with some input on whether we are tackling this in the near term.`?

**Comment by yang-g** [comment]
@hsaliak to triage, maybe...

**Comment by hsaliak** [comment]
@laxderek we have an interceptor API support in C# now, is that sufficient to address your concerns?

@vsubramani do you have an eta on when we might have C# opencensus API?

**Comment by laxderek** [comment]
Yes, that is sufficient. Thank you!
