### ISSUE TITLE
Need a logger controller to control the logging

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#7077]
When using grpc, couldn't find interface to change the behaviour of logging, which introduce some problems especially on the client side.
For example, a lot of unwanted logging will output to the terminal, like:
E0627 14:51:51.492383576   29469 tcp_client_posix.c:171]     failed to connect to 'ipv4:192.168.33.83:17799': socket error: connection refused
E0627 14:51:51.992594835   29471 tcp_client_posix.c:171]     failed to connect to 'ipv4:192.168.33.83:17799': socket error: connection refused

**Comment by thinkerou** [comment]
The `E` of `E0627` means `Error`, if `E` are `D` that means `Debug`.

**Comment by yyh-graphsql** [comment]
Thanks for remind me about this. But the thing I want is to control these logs by calling a grpc function.
The control I think need to include controlling the log level of logs that output to the terminal at least, just like glog does.

**Comment by thinkerou** [comment]
@yyh-graphsql You should set `GRPC_VERBOSITY` env to control log output.
`export GRPC_VERBOSITY=ERRO`: only output Error log
`export GRPC_VERBOSITY=INFO`: output Error and Info logs
`export GRPC_VERBOSITY=DEBUG`: output All class logs
If you not set `GRPC_VERBOSITY` env, the default value of env is `ERRO`.
You should read it #7438
