### ISSUE TITLE
Update homebrew formulas to 0.15.0

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#7083]

**Comment by jtattermusch** [comment]
CC @nicolasnoble  @stanley-cheung  @murgatroid99

**Comment by jtattermusch** [comment]
@jcanizales

**Comment by jtattermusch** [comment]
@y-zeng , once you have the PR, please add @stanley-cheung  as reviewer.

https://github.com/grpc/homebrew-grpc/pulls?q=is%3Apr+is%3Aclosed

**Comment by y-zeng** [comment]
Updated in https://github.com/grpc/homebrew-grpc/pull/82
