### ISSUE TITLE
Sending a Node Buffer as a field in a message in binary format.

### ISSUE THREAD

**Issue by aman-tiwari** [grpc/grpc#7084]
Is it possible to send a nodejs Buffer object without first base64 encoding it into a string?
If it is, it would be a helpful example to have, since binary data transmission isn't something JSON can do.

**Comment by murgatroid99** [comment]
Assuming that you are talking about protobuf messages, a `bytes` field can be used to send a `Buffer` object.

Our [interop tests](https://github.com/grpc/grpc/blob/master/src/node/interop/interop_client.js#L111) use this. The message definitions for those tests are [here](https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/messages.proto).

**Comment by aman-tiwari** [comment]
Oh, they do! It would be good to have the documentation link to those or to have a documented example of it.
