### ISSUE TITLE
`tools/run_tests/run_tests.py` does not work with Python 3

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#7094]
The `run_tests.py` script does not work with python 3 and throws the following error.
```
Password:
  File "run_tests.py", line 203
    print '\nWARNING: binary not found, skipping', binary
                                                ^
SyntaxError: Missing parentheses in call to 'print'
```
Hopefully, we can fix this incompatibility by moving the print statements to `print()` functions. This was one of the breaking changes in Python3. Most likely: Fixing `print` makes it Python3.x compatible. Worst case: There might be still be some incompatibilities but they should be easy enough to fix. 

As there's this whole move towards making grpc Python 3.x compliant, I highly suggest abstaining from writing scripts that only work with Python 2.x and not with Python 3.x. For all practical purposes, that requires using the `print()` function instead of the statements and using new style Classes (i.e. `class Foo(object):` instead of `class Foo:`) in python. I'll create a PR to solve the current issue with running tests with python3 in the meanwhile.

**Comment by nathanielmanistaatgoogle** [comment]
Just thinking about how to add regression test coverage for this problem makes my brain fold in upon itself.

**Comment by thunderboltsid** [comment]
Current status: Some of the internal libraries such as BaseHTTPServer (http.server in 3.x), urllib2 (urllib.request and urllib.error in 3.x) are preventing me from moving further. Any ideas about creating an isomorphic way of using this libs in both python 2.x and 3.x? A little research on the topic points to https://github.com/PythonCharmers/python-future @nathanielmanistaatgoogle what do you think about this?

**Comment by nathanielmanistaatgoogle** [comment]
@thunderboltsid: which of those renames are not covered by [`six.moves`](https://pythonhosted.org/six/#module-six.moves)? As far as I understand it, `six.moves` _is_ the isomorphism about which you ask.

I think I've heard the name `python-future` but am not familiar with it otherwise. If we're using `six`, what problems do we have that `six` doesn't cover but that `python-future` does?

**Comment by thunderboltsid** [comment]
Decided to roll with six. It does indeed provide exactly what I was looking for

**Comment by nathanielmanistaatgoogle** [comment]
This was addressed by [pull request 7265](https://github.com/grpc/grpc/pull/7265).
