### ISSUE TITLE
Eliminate everything having to do with code generation from examples/python/helloworld

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7096]
`helloworld` is supposed to be the "in three minutes" example and doesn't actually teach code generation. Having stuff related to code generation in that example clutters the contents and misleads users.

**Comment by hsaliak** [comment]
Moving this out of GA polish, to someday. We need to revisit examples that teach code generation separately. .

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak, @LisaFC: I think I heard sometime in the last two weeks that we want to keep code generation, even in helloworld, and [the revamped helloworld tutorial](https://github.com/grpc/grpc.github.io/pull/223) certainly includes running the code generator as a key lesson. Was I just off-target filing this, and should this issue just be closed?

**Comment by LisaFC** [comment]
Yes, user feedback was that code generation/using protoc was confusing and they would like to see how to do it even in a basic example - hence the new-style Quickstart where we get them to modify the service definition and run protoc.

We can possibly remove it from the more detailed walk-through text of Hello World (currently at http://www.grpc.io/docs/) and just specify what the generated classes are - given that at no point do we ask users in that doc to actually modify the proto - though that's probably a separate issue.
