### ISSUE TITLE
Eliminate cloning repository from example workflows

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7097]
... what we really want the user to achieve is ["having the contents of the example directory available locally"](http://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo). This may be as simple as a recursive `wget` or `curl` command.

**Comment by nathanielmanistaatgoogle** [comment]
(Responding to [this comment](https://github.com/grpc/grpc.github.io/pull/223/files/01124512b52a876bc2ca94dc01c0043e3fd069c2#r70895601)) @soltanmm: so let's think outside the space of `git` commands. The content is anonymously HTTP GETable; should we be looking at a `wget` or `curl` command? Might a `goo.gl` short link have some role to play?

**Comment by soltanmm** [comment]
> so let's think outside the space of git commands

![Too late!](http://66.media.tumblr.com/5b10b8cd729932c2314aa9db88434585/tumblr_n0lcbdYvD01sl21koo1_500.gif)

This can be brought down to a 4 MB download with:
```
git init $REPO
cd $REPO
git remote add origin git://github.com/grpc/grpc.git
git fetch --depth=1 origin v1.0.x
git checkout origin/v1.0.x examples
```

... Seriously, though, Github should just support flippin' archiving.

**Comment by soltanmm** [comment]
GitHub supports subversion.

```
svn checkout https://github.com/grpc/grpc/branches/v1.0.x/examples
```

Is a 2.3 MB directory, probably a 1.x MB download after the super slow execution of `svn` (at least on my Mac OS X).
