### ISSUE TITLE
(C#) Use the new System.Interactive.Async package

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#7103]
Ix-Async has been renamed to System.Interactive.Async, and version-bumped to 3.0 as part of moving to the .NET Foundation.

At some point gRPC should update its dependency accordingly - although it's a pain that it will break anyone still depending on Ix-Async. (At the moment it breaks anyone using the new package...)

**Comment by ThomasGrausgruber** [comment]
I think I have the same problem:

![image](https://cloud.githubusercontent.com/assets/17122560/17103368/49e05c52-527e-11e6-8f49-c2c3a9f521da.png)

**Comment by jskeet** [comment]
@ThomasGrausgruber: Could you post the error as *text* (with triple-backticks at the start and end for formatting) rather than as a screenshot? That'll make it a lot easier to read.

**Comment by ThomasGrausgruber** [comment]
sure :)

Greeter server listening on port 50051
Press any key to stop the server...
W0725 16:11:47.443288 Grpc.Core.Server Exception while handling RPC. System.IO.FileLoadException: Die Datei oder Assembly "System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
   bei Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__0.MoveNext()
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   bei Grpc.Core.Internal.UnaryServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq)
   bei Grpc.Core.Server.<HandleCallAsync>d__11.MoveNext()

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Thomas Grausgruber/Desktop/grpc-master/examples/csharp/helloworld/GreeterServer/bin/Debug/
LOG: Ursprünglicher PrivatePath = NULL
Aufruf von Assembly : Grpc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad.
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\Users\Thomas Grausgruber\Desktop\grpc-master\examples\csharp\helloworld\GreeterServer\bin\Debug\GreeterServer.vshost.exe.Config
LOG: Die Hostkonfigurationsdatei wird verwendet:
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config wird verwendet.
LOG: Verweis nach der Richtlinie: System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Download von neuem URL file:///C:/Users/Thomas Grausgruber/Desktop/grpc-master/examples/csharp/helloworld/GreeterServer/bin/Debug/System.Interactive.Async.DLL.
WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Hauptversion.
ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.

E0725 16:12:32.057930 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\chttp2_transport.c:1810: close_transport: {"created":"@1469455952.056000000","description":"Failed parsing HTTP/2","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1469455952.056000000","description":"Unable to retrieve error string","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":170}]}

**Comment by ThomasGrausgruber** [comment]
additional information:

Framwork for Greetings Server is 4..6.1 and Reference to the new using Microsoft.EntityFrameworkCore;

**Comment by jskeet** [comment]
Right. The fact that `Microsoft.EntityFrameworkCore` has a dependency on `System.Interactive.Async` 3.0 may well be a good signal that it's time to move. In particular, it would be better to move *before* 1.0 than after... moving in a point release (for 1.1 or 1.2) would be at least a "somewhat breaking" change, in that it would break some people.

**Comment by ThomasGrausgruber** [comment]
Great! When do you think you could move? Thank you!

**Comment by jskeet** [comment]
Me? It's not my call - I'm not in the gRPC team. Jan will have to weigh up the pros and cons. (And there are cons - anyone already depending on Ix-Async will be broken in the same way that anyone depending on System.Interactive.Async is broken now.)

**Comment by ThomasGrausgruber** [comment]
I understand you, but the new version is the future. Better break now than to late. Now are not so much developers. GRPC is very lightweight and also the new EF core is also very lightweight. Much more better.

**Comment by apolcyn** [comment]
cc @jtattermusch
Working on a change for this today

**Comment by apolcyn** [comment]
One other thing that System.Interactive.Async seems to break is the just the ability to use a Grpc nuget package from Xamarin Studio on mac or Monodevelop IDEs on linux. These IDEs use the 2.8.6 nuget client, but System.Interactive. needs the 2.12. version. One could get around this by updating their nuget client and then restoring packages from the command line though, also this seems to be a problem with these IDEs in general.

**Comment by jskeet** [comment]
@apolcyn: I would thoroughly expect both of them to receive updates that include 2.12, hopefully soon. It will become increasingly difficult to work in a way that *doesn't* support .NET Core.

**Comment by apolcyn** [comment]
the latest pre-release, 1.0.0-pre2, now uses this
