### ISSUE TITLE
src\csharp\Grpc.sln shows no NuGet packages in VS2015

### ISSUE THREAD

**Issue by dalebrubaker** [grpc/grpc#7106]
Windows 10. VS 2015. Latest master today.
Grpc.sln "Manage NuGet Packages for Solution" shows "No packages found"

**Comment by jtattermusch** [comment]
This might be related to recently adding Grpc.Core.project.json (and other) files, so it seems VS2015 is trying to get the list of dependencies from   the *.project.json files and not from packages.config files.

Is it that you just don't see the nuget packages in VS 2015 or the build is broken (nuget restore seems to work).
Also, in VS2013 everything seems to work.

**Comment by dalebrubaker** [comment]
I can't see the nuget packages in VS 2015 nor can I restore them. But you are correct, it works well in VS 2013. I see that the solution still uses the pre-2.7 package restore techniques with entries in each csproj file. https://docs.nuget.org/consume/package-restore 
Anyway, now I can proceed using VS 2013.
Thanks.

**Comment by jtattermusch** [comment]
I'll reopen this one because it is an issue. Not clear to me though what is the best way to fix (besides copying the list of dependencies into project.json files (and thus having two copies - one in *.project.json files and one in packages.config file.

**Comment by jtattermusch** [comment]
One way to work around this in VS2015 is to run `nuget restore Grpc.sln` manually. After doing that, the solution builds in VS2015 as without any problems.

I tried to experiment with techniques how to convince VS2015 to just ignore project.json file https://github.com/Microsoft/msbuild/issues/394,  but  none of the tricks has worked  (I tried <ResolveNuGetPackages>false</ResolveNuGetPackages>).

**Comment by dalebrubaker** [comment]
I submitted this pull request today for this issue. I don't know how to tie the PR to the issue.
 * Add project.json dependencies in Grpc.sln #7194

**Comment by dmitriyse** [comment]
Probably this solution from this issue will better fit to your requirements. https://github.com/NuGet/Home/issues/3207

**Comment by goldenbull** [comment]
@jtattermusch I run `nuget restore Grpc.sln` manually, a new file `Grpc.Core.project.lock.json` is created:
```
{
  "locked": false,
  "version": 2,
  "targets": {
    ".NETFramework,Version=v4.5": {},
    ".NETFramework,Version=v4.5/win": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    "": [],
    ".NETFramework,Version=v4.5": []
  }
}
```

But `msbuild Grpc.sln` failed as the same.

**Comment by apolcyn** [comment]
@dalebrubaker, on #7194, thanks, but I'm not sure if that would that work with dotnet cli tools as well as vs2015? Would we have to use both sets of project.json files?

Also, another way of restoring packages and building the solution from the command line is with `/path/to/repo/root/tools/run_tests/run_tests.py -l csharp -c <dbg,ops>`, which will work with the old and new nugets. (when building the solution form visual studio, I was having trouble earlier because the native lib wasn't built for the config i was building the solution for).

**Comment by dalebrubaker** [comment]
@apolcyn, on #7194 you are probably correct. I closed my PR for this issue. I don't know (or care) about dotnet cli or project.json files, especially now that Microsoft has told us that they will be going back to csproj files early next year. Until then, I suppose each grpc consumer can muddle through getting a build in whatever way makes sense for him. Thanks.
