### ISSUE TITLE
using grpc C++ without installing it

### ISSUE THREAD

**Issue by elazarl** [grpc/grpc#7107]
Sometimes, for example, when you do not have root access to a machine, one cannot `make install` grpc.

In those cases, when trying to compile the C++ examples compilation fails, as it assumes the library, include, and pkg-config files are installed to `/usr/local`.

I suggest to have a file, like `actviate.sh`, that users could source, and it would add all relevant libraries from the source tree to the relevant environment variables.

Here is the script I came up with:

``` bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH=$PATH:$DIR/bins/opt:$DIR/bins/opt/protobuf
export CPATH=$DIR/include:$DIR/third_party/protobuf/src
export LIBRARY_PATH=$DIR/libs/opt:$DIR/libs/opt/protobuf
export PKG_CONFIG_PATH=$DIR/libs/opt/pkgconfig:$DIR/third_party/protobuf
export LD_LIBRARY_PATH=$DIR/libs/opt
```

In the README one should addd, that to compile grpc without installation one would simply

```
$ source ~/grpc/activate.sh
$ cd ~/grpc/examples/cpp/helloworld
$ make
```

That would have been useful for me.
Do you think it would be a good idea?

**Comment by elazarl** [comment]
For future reference, zsh compatible `activate.sh` script

```bash
if [ -n "$ZSH_VERSION" ]; then
   DIR="$( cd "$( dirname "${(%):-%N}" )" && pwd )"
elif [ -n "$BASH_VERSION" ]; then
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi
export PATH=$PATH:$DIR/bins/opt:$DIR/bins/opt/protobuf
export CPATH=$DIR/include:$DIR/third_party/protobuf/src
export LIBRARY_PATH=$DIR/libs/opt:$DIR/libs/opt/protobuf
export PKG_CONFIG_PATH=$DIR/libs/opt/pkgconfig:$DIR/third_party/protobuf
export LD_LIBRARY_PATH=$DIR/libs/opt
```

**Comment by fedemengo** [comment]
Using the above method doesn't work for me, in particular the compiler cannot find the definition of `PROTOBUF_NAMESPACE_OPEN` and `PROTOBUF_NAMESPACE_CLOSE`

I tested on another machine in which I actually installed **grpc** and **protobuf** and the definition of those macros is in `/usr/local/include/google/protobuf/port_def.inc` but I cannot find it in `$DIR/third_party/protobuf/src/google/protobuf/port_def.inc` that, I assumed, should be the same file

**Comment by jtattermusch** [comment]
It is possible to use grpc C++ without needing to install to `/`, e.g.:
-  cmake offers several ways how to use gRPC, one of them is installing to a local subdirectory https://github.com/grpc/grpc/tree/master/src/cpp#cmake
- you could use bazel.
