### ISSUE TITLE
Maybe find a better place for the grpcio-tools directory

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#7108]
Hanging out in `tools/distrib/python` is a holdover from me not wanting to think very hard about what the 'right' home for a grab-bag of code vendored from the repository root directory _should_ be. I have no idea if folks think it's confusing or if it's just 'how things are', but if the past has anything to teach us it's that 'how things are' isn't necessarily 'how things should be' (... for some philosophy of 'should').

**Comment by nathanielmanistaatgoogle** [comment]
(To be clear: this is still "something we'd rather happen than not"; we just don't need an open issue for it.)
