### ISSUE TITLE
grpc does not run tests for python 3.5 and 3.6

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#7110]
PR Coming shortly. This was supposed to be solved by the [PR#6959](https://github.com/grpc/grpc/pull/6959) but I messed up by not using a separate branch for the PR which caused all sorts of issues. Did a reboot on my fork and will create a PR soon.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle This is marked `GA Polish`, but #7112 is marked `Someday...`. What's the current intent?

**Comment by nathanielmanistaatgoogle** [comment]
Aspirationally `GA Polish`. Let's make an assessment tomorrow with @thunderboltsid about whether this can land in the next two or three days.

**Comment by soltanmm** [comment]
Removed from GA Polish. The relevant fix was placed on `master` rather than `v1.0.x`, and we will not be moving to cherry-picking it immediately before 1.0.
