### ISSUE TITLE
Travis builds do lengthy operations that aren't needed for ObjC

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#7117]
- ~~It clones to a depth of 50 commits (fix: https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth ).~~ ~1min (Fixed in https://github.com/grpc/grpc/commit/1e6d1272df4c2ffb24e8ca3c7d5f875f7df87758)
- It inits all submodules (fix: https://gist.github.com/petrbel/c3bf7e0f59c22a52f534 ) ~1min
- Make might or might not be doing more than what's needed to compile protoc and the plugin? (This is the longest operation). ~10min
- The C++ interop server might not be the fastest to compile, and now plenty of other languages should work correctly on macOS. Try others? ~4min
- `make interop_server` compiles all gRPC protoc plugins. (part of the above ~4min)

**Comment by jcanizales** [comment]
From Travis' documentation, setting the depth to 1 will apparently make Travis only test the latest commit of every PR, which is great to reduce the time tests are just waiting queued.

**Comment by jcanizales** [comment]
@makdharma FYI - compiling the interop server is ~ 4min for each Travis task.

**Comment by jcanizales** [comment]
* `pod install` takes about 7min, which will probably be much less for the RxLibrary unit tests if we don't make it depend on all pods out there (it only needs to depend on gRPC-RxLibrary). We can check `ENV['SCHEME']` in the tests Podfile: If it's set, we know that (a) we're in Travis and (b) we can skip all targets that aren't called like `ENV['SCHEME']` (because we aren't going to build nor run them).

**Comment by jcanizales** [comment]
Also, ideally, the ObjC tests would run only for changes that affect the ObjC library. Ideally Bazel would give us its magic incremental builds and tests. But without Bazel, it shouldn't be hard to keep a blacklist of files that we know don't affect us: `*.md`, `*.py`, etc. etc. Then query git diff for the list of modified files, filter it with the blacklist, and only test if anything's left.

**Comment by jcanizales** [comment]
Makarand, Muxi; some of these things might be specific to Travis, but some might help speed up Jenkins too.

**Comment by muxi** [comment]
That is very helpful. I'm gonna make some heavy cleanup of Jenkins next week as it has been really messy these days.
