### ISSUE TITLE
Deprecate gRPC docker images

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#7127]
They are not needed anymore because we have one-line installs for all the languages (and currently they are also very out of date).
- [ ]   replace https://github.com/grpc/grpc-docker-library/blob/master/README.md with deprecation announcement.
- [ ]   deprecate the images on https://hub.docker.com/u/grpc/
- [ ]  _optional_ add a section about using gRPC under docker to grpc.io

**Comment by jtattermusch** [comment]
@hsaliak  please assign someone.

**Comment by jtattermusch** [comment]
CC @ejona86

**Comment by hsaliak** [comment]
Closing this old issue out. Since the discussion, @markmandel has taken over ownership and published new packages.
