### ISSUE TITLE
Patch-update Python grpcio-tools 0.15

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#7134]
Due to the package being broken (see #7101, #7119),  I've hidden 0.15.0. As soon as fixes for the relevant issues go in, we should cut a patch release.

**Comment by tseaver** [comment]
@soltanmm Just in case you weren't aware, hiding a release on PyPI only affects the browser UI:  pip will still (un)happily (try to) install the hidden distribution.

**Comment by soltanmm** [comment]
\*grumble grumble\*

The files are now removed.

**Comment by soltanmm** [comment]
(thanks for the heads up!)

**Comment by soltanmm** [comment]
Thanks goes to @kpayson64.

**Comment by tseaver** [comment]
Hmm, I don't see a new release on PyPI:  it still shows 0.15.0 from 2016-06-28.

**Comment by soltanmm** [comment]
Hm. I'm definitely seeing 0.15.1 up there for `grpcio-tools`. I hate to ask this, but, have you cleared your cache?

**Comment by tseaver** [comment]
Ugh, it was my brain that needed clearing:  I was looking at `grpcio`, not `grpcio-tools`.
