### ISSUE TITLE
python3 server responds with "unimplemented" to all rpcs.

### ISSUE THREAD

**Issue by ioctl0** [grpc/grpc#7139]
It looks like the issue is that the tables of methods maintained by the server are keyed with strings:
method_implementations = {
   ('tools.testing.TestService', 'Ping'): face_utilities.unary_unary_inline(servicer.Ping),
}   

Whereas when a request comes in, the method name is bytes. Hacking the generated code to add a bunch of 'b's makes everything work.

I'm using some custom bazel rules to build the python runtime, so maybe I got them wrong?

**Comment by ioctl0** [comment]
The exact error message is:

grpc.framework.interfaces.face.face.LocalError: LocalError(code=StatusCode.UNIMPLEMENTED, details="b'Method "b\'Ping\'" of service "b\'tools.testing.TestService\'" not implemented!'")

**Comment by kpayson64** [comment]
What version of grpcio are you using?  Python3 was not supported prior to 0.15.

Also, it looks like your generated proto files are still based on the Alpha API.  The Alpha API has been removed, so you may need to regenerate your proto files when upgrading grpcio.

**Comment by ioctl0** [comment]
Oops -- I thought I was at HEAD, but I wasn't. Works fine now. Thanks and sorry!
