### ISSUE TITLE
Error while compiling the source 

### ISSUE THREAD

**Issue by haripraveenrajt** [grpc/grpc#7168]
![screenshot from 2016-06-30 13 40 38](https://cloud.githubusercontent.com/assets/19606745/16488430/67ad59de-3ec8-11e6-9553-e5184798b2f1.png)
I followed the steps mentioned in this link
https://github.com/grpc/grpc/blob/master/INSTALL.md
when i compile the  source using make i keep getting an error ,i have attached a screenshot 
plz help me with this

**Comment by ctiller** [comment]
Which OS and compiler are you using?

**Comment by haripraveenrajt** [comment]
Im using Ubuntu 12.04 64 bit os and GCC

**Comment by soltanmm** [comment]
Which version of GCC?

**Comment by haripraveenrajt** [comment]
gcc version - 4.6.3
