### ISSUE TITLE
Add a new case to the document of status codes

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#7181]
Created from Issue #5994 

The following case is in the code base of Objective C and we think it should be in the Status Codes document:
Case: The app does not have enough memory to hold the server response
Code: RESOURCE_EXHAUSTED
Generated at: Client

-----
Code ref:
https://github.com/grpc/grpc/blob/a9df5d1029b303a305481c4bb765c6bed2e8ebbb/src/objective-c/GRPCClient/GRPCCall.m#L215-L217

**Comment by hsaliak** [comment]
@muxi Just want to confirm that you are suggesting we  update the Status Code document to capture this case? @a11r wdyt?

**Comment by a11r** [comment]
Did you consider returning RESOURCE_EXHAUSTED, with additional details indicating that the resource being exhausted is the memory at the client side ?

**Comment by muxi** [comment]
@hsaliak Yes you are right. Our code did this part; we think it should be captured by the doc and code of other languages.

@a11r that is an awesome suggestion; RESOURCE_EXHAUSTED does look like a better code for this case. I will discuss with team about this.

**Comment by a11r** [comment]
muxi has offered to edit the spec in a PR that I'll review. I do not see this as a GA blocker since this is a new addition to the spec for a case that is not necessarily universal across languages (some languages will handle this in flow control) . Assigning to muxi and removing milestones.
