### ISSUE TITLE
Disk Recycler on Jenkins causing test failures

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#7193]
e.g. https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/4359/language=python,scenario=linux_default_python3.4/console

**Comment by soltanmm** [comment]
Kinda dupe of #6677, but more general as I've been seeing this in other places beyond interop tests.

**Comment by soltanmm** [comment]
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/4359/language=c,scenario=linux_x64_gcc4.4_bo/console
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/4359/language=c++,scenario=linux_x64_clang3.7_bo/console

It may just be that grpc-jenkins-linux9 is configured incorrectly? Not sure how to check.

**Comment by soltanmm** [comment]
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/4478/console

\**whistles*\* Wow. Zero gigabytes available.

Wouldn't it have needed to get past the 37 GB threshold (at least... I think it's 37 GB) without triggering the Disk Recycler (which should've failed, thus not allowing it to continue and use more space and get past the 37 GB threshold)? Or does a small amount of space get used every time a test is started? Weird.

**Comment by jtattermusch** [comment]
I've seen several instances of this today:
```
Disk Recycler is Enabled so I am going to wipe off the workspace Directory Now 
[gRPC_portability_pull_requests_linux] $ /bin/sh -xe /tmp/jenkins5249274233334148604.sh
+ echo /home/jenkins/workspace/gRPC_portability_pull_requests_linux
/home/jenkins/workspace/gRPC_portability_pull_requests_linux
+ rm -rf /home/jenkins/workspace/gRPC_portability_pull_requests_linux/../
rm: refusing to remove ‘.’ or ‘..’ directory: skipping ‘/home/jenkins/workspace/gRPC_portability_pull_requests_linux/../’
```

https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/6330/console

**Comment by jtattermusch** [comment]
Some workers are running out of space. To free up some space, I'm running this:

see how much free space there is
```
for a in `seq 10 60`; do echo $a; gcloud compute ssh --project grpc-testing grpc-jenkins-linux$a --command 'df -h /dev/sda1'; done;
```

clean up old docker containers & images
```
gcloud compute ssh --project grpc-testing grpc-jenkins-linuxXX --command 'sudo docker rm $(sudo docker ps -aqf status=exited)'
gcloud compute ssh --project grpc-testing grpc-jenkins-linuxXX --command 'sudo docker rmi $(sudo docker images -qf dangling=true)'
```

**Comment by jtattermusch** [comment]
Closing in favor of https://github.com/grpc/grpc/issues/10512
