### ISSUE TITLE
node.js grpc doesn't handle oneof field properly

### ISSUE THREAD

**Issue by pmullaney** [grpc/grpc#7200]
I am having several issues with message types containing oneof fields. I have attached an example that is derived from the greeter example code. I have added a oneof field to the request that contains an A and a B message within the oneof. When I create the A message only(without enclosing it in a oneof of the HelloRequest) and send it, it works. However, I then send a B message in the same manner and it encounters an exception during serialization. The interesting thing to point out is that if I change the order of the elements of the oneof in the proto file to B and then A, the B request will be successful. 

[greeter_client.js.txt](https://github.com/grpc/grpc/files/343815/greeter_client.js.txt)
[greeter_server.js.txt](https://github.com/grpc/grpc/files/343816/greeter_server.js.txt)
[helloworld.proto.txt](https://github.com/grpc/grpc/files/343817/helloworld.proto.txt)

If I change the example such that I use the HelloRequest, I get another exception indicating the alt field is undefined. I am using grpc@0.14.1 and protobufjs@4.1.3 on ubuntu 14.04.

**Comment by murgatroid99** [comment]
It seems like the problem here is with protobuf serialization. I would suggest posting an issue at https://github.com/google/protobuf

**Comment by pmullaney** [comment]
Thanks - I will do that. The reason I posted here first is that encoding the messages via .encode() seems to work fine so perhaps its related to grpc method of using protobufjs.
\

**Comment by pmullaney** [comment]
Here is the example showing that protobuf seems to handle oneof properly.

[greeter_client.js.txt](https://github.com/grpc/grpc/files/348296/greeter_client.js.txt)

I think this is a valid grpc problem.

**Comment by murgatroid99** [comment]
It's interesting that the message's `.encode()` method works. What happens if you call the `.serializeBinary()` method? That's the one that gRPC uses in the serializer.

**Comment by murgatroid99** [comment]
@angrbrd Are you sure that the `msg` object you have is a protobuf message object of the type that the `google-protobuf` library exposes?

**Comment by pmullaney** [comment]
The crash I am seeing is in MessagePrototype.set. Here's the snippet causing it:

var field = T._fieldsByName[keyOrObj];
                    if (!noAssert) {
                       if (!field)
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");

The problem is either the oneof field should be mapped in the T._fieldsByName or there should be appropriate logic to avoid and skip the checks inside the !noAssert conditional. I hacked a version to avoid the checks and it works. Unfortunately, I can't seem to find a decent way to check that the field is a oneof.

**Comment by murgatroid99** [comment]
Are you seeing that crash when you call the message's `.serializeBinary()` method? If so, you should bring this issue to the [google/protobuf](https://github.com/google/protobuf) repo.

**Comment by pmullaney** [comment]
I'm having the same issues trying that as angrbrd, generally unfamiliar with using the serializeBinary and haven't been able to find a simple example of using it. Does it require me to statically generate the grpc code?

**Comment by murgatroid99** [comment]
I just realized that I missed something when I originally read your example code. You are using `grpc.load`, which means that you are using the built-in Protobuf.js code generation. But that also means that you don't need to (and shouldn't) explicitly construct message objects. You should just create regular objects with the right structure. For example, you can do

```js
var h = {a: {foo: user}};
var bh = {b: {bar: user}};
```

**Comment by pmullaney** [comment]
I have tried that as well and it still crashes - will post that crash next.

**Comment by angrbrd** [comment]
Hi @murgatroid99 

Thanks for your response. I am using the `.serializeBinary()` method on a protobuf message object. And when I do so, this is the crash that I observe. I am attaching both server and client code here as well as the .proto file.

[helloworld2.proto.txt](https://github.com/grpc/grpc/files/369863/helloworld2.proto.txt)
[greeter_client_v2.js.txt](https://github.com/grpc/grpc/files/369864/greeter_client_v2.js.txt)
[greeter_server_v2.js.txt](https://github.com/grpc/grpc/files/369865/greeter_server_v2.js.txt)

```
Initializing gRPC client...
empty request A = {"alt":null,"a":null,"b":null}
msgA = {"foo":"ANGRBRD"}
filled request A = {"alt":"a","a":{"foo":"ANGRBRD"},"b":null}
requestADecoded = {"alt":"a","a":{"foo":"ANGRBRD"},"b":null}
/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_client_v2.js:69
  var requestASerialized = requestA.serializeBinary();
                                    ^

TypeError: requestA.serializeBinary is not a function
    at main (/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_client_v2.js:69:37)
    at Object.<anonymous> (/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_client_v2.js:113:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by angrbrd** [comment]
If I comment out lines 69 and 70 of my greeter_client_v2.js file (attached above), which removes the usage of `.serializeBinary()` on the protobuf message, I do receive the same crash as @pmullaney.

```
Initializing gRPC client...
empty request A = {"alt":null,"a":null,"b":null}
msgA = {"foo":"ANGRBRD"}
filled request A = {"alt":"a","a":{"foo":"ANGRBRD"},"b":null}
requestADecoded = {"alt":"a","a":{"foo":"ANGRBRD"},"b":null}
/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .helloworld2.HelloRequest#alt is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2440:35)
    at MessagePrototype.set (/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
    at serialize (/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/src/node/src/common.js:87:23)
    at Client.makeUnaryRequest [as sayHello] (/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/src/node/src/client.js:381:19)
    at main (/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_client_v2.js:77:10)
    at Object.<anonymous> (/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_client_v2.js:113:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by angrbrd** [comment]
If I instead follow the approach that you described here by constructing regular objects:

```
var h = {a: {foo: user}};
var bh = {b: {bar: user}};
```

You may find that code in my greeter_client_v2.js file (attached above). You can comment out for request A lines 55-70 and 77. And uncomment liens 73-74 and 78. Similarly, you can comment/uncomment the appropriate lines for request be lower in the file. You will observe that request A succeeds on request/response, but request B causes the following problem on the server side. It receives request type B, but is trying to parse for `foo`, which appears in request type A.

```
request={"alt":"b","a":null,"b":{"bar":"SUNSHINE"}}
/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_server_v2.js:57
  callback(null, {message: 'Hello ' + call.request.a.foo});
                                                    ^

TypeError: Cannot read property 'foo' of null
    at Object.sayHello (/Users/anya/dev/node/grpc/examples/node/dynamic_codegen/greeter_server_v2.js:57:53)
    at Object.wrapper [as func] (/Users/anya/dev/node/grpc/examples/node/node_modules/grpc/node_modules/lodash/index.js:3095:19)
    at /Users/anya/dev/node/grpc/examples/node/node_modules/grpc/src/node/src/server.js:485:13
```

**Comment by angrbrd** [comment]
Hold on... nevermind the very last comment.

**Comment by angrbrd** [comment]
@murgatroid99 The usage you described below does work for me. My code is below. Could you please clarify why this is the proper usage, as opposed to creating a protobuf message first and filling in the fields? I do not understand the difference.

```
var h = {a: {foo: user}};
var bh = {b: {bar: user}};
```

```
  //
  // Construct a request
  //

  // Sample requests below
  var requestATEST = {a: {foo: "ANGRBRD"}};
  console.log("requestATEST = " + JSON.stringify(requestATEST));

  client.sayHello(requestATEST, function(err, response) {
     console.log("Response received!");
     console.log('Greeting: %j', response);
     console.log("\n\n\n");

     //
     // Construct another request
     //

     var requestBTEST = {b: {bar: "SUNSHINE"}};
     console.log("requestBTEST = " + JSON.stringify(requestBTEST));

     client.sayHello(requestBTEST, function(err, response) {
        console.log('Greeting:', response.message);
     });
  });
```

**Comment by murgatroid99** [comment]
@angrbrd The "dynamic codegen" usage pattern, using `grpc.load` and Protobuf.js, was intended to be easy to use and familiar, so it uses regular JavaScript objects. That's just how the API is designed.

**Comment by pmullaney** [comment]
Here is the example showing that protobuf seems to handle oneof properly.

[greeter_client.js.txt](https://github.com/grpc/grpc/files/348296/greeter_client.js.txt)

I think this is a valid grpc problem.

**Comment by pmullaney** [comment]
@murgatroid99: Thanks for pointing out that using javascripts objects in the form above works. It seems more than odd though with the examples using actual messages that the form I originally used doesn't work. I suspect others will run into this.
There is also another problem worth mentioning and it is the reason I used the method of constructing the entire message(setting the oneof field). Consider the example proto in the attached file:
[helloworld2.proto.txt](https://github.com/grpc/grpc/files/370107/helloworld2.proto.txt)

Wouldn't "var requestATEST = {a: {foo: "ANGRBRD"}};" be ambiguous as to the message to create?

**Comment by murgatroid99** [comment]
I'm not sure what examples you're referring to. The dynamic codegen examples don't use message objects, and the static codegen examples don't use `grpc.load`.

And you are correct that that line of code alone isn't completely specified. But if you're passing that object to `sayHello`, then we know what message to create based on the signature of that method.

**Comment by pmullaney** [comment]
@murgatroid99: Sorry you're right, the examples in the dynamic codegen don't use message objects. And thanks for the clarification on the how the ambiguity is resolved via the method signature. We may post some examples here run into the same confusion.

**Comment by angrbrd** [comment]
Hi @murgatroid99 Thanks a lot for your help with these explanations, that makes much more sense now. Specifically, the point on the "dynamic codegen" pattern which uses `grpc.load` and regular JavaScript objects. As opposed to the "static codegen" pattern which does not use `grpc.load` and instead uses protobuf message objects. 

I have modifying my files to have a usage example of each of the scenarios below. I am attaching here. Or if you think there's a better way to share these examples that might help others with the same issue? I could push them as .proto and .js to my own repo if that would help others. Just let me know.

[helloworld2.proto.txt](https://github.com/grpc/grpc/files/370338/helloworld2.proto.txt)
[greeter_client_v3.js.txt](https://github.com/grpc/grpc/files/370340/greeter_client_v3.js.txt)
[greeter_server_v3.js.txt](https://github.com/grpc/grpc/files/370341/greeter_server_v3.js.txt)

```
message HelloRequest {
    oneof alt {
        A a = 1;
        B b = 2;
    }
}
message HelloRequest2 {
    oneof alt {
        A a = 1;
        C c = 2;
    }
}
message HelloRequest3 {
   C c = 1;
   oneof alt {
       A a = 2;
       B b = 3;
   }
}
```

**Comment by pmullaney** [comment]
@murgatroid99 : thanks for the help. I have add another case for streaming messages containing oneof to the example above that I will include here for completeness and close the issue.


[greeter_client_v3.js.txt](https://github.com/grpc/grpc/files/374072/greeter_client_v3.js.txt)
[greeter_server_v3.js.txt](https://github.com/grpc/grpc/files/374073/greeter_server_v3.js.txt)
[helloworld2.proto.txt](https://github.com/grpc/grpc/files/374074/helloworld2.proto.txt)
