### ISSUE TITLE
windows x86 package for grpcio-tools/0.15.1 lost!

### ISSUE THREAD

**Issue by sunwangme** [grpc/grpc#7226]
https://pypi.python.org/pypi/grpcio-tools/0.15.1

**Comment by kpayson64** [comment]
grpcio-tools x86 was not included in the release because 32-bit Windows grpcio is not currently supported.  There is one known issue that prevents 32 bit windows from working, #6964.

**Comment by soltanmm** [comment]
Right, so, technically this specific issue as worded is unactionable. However, future versions will have such support once the DLL hack is removed in #7195, and those should end up with Windows 32 bit distributions.

**Comment by soltanmm** [comment]
Closing as this specific issue is unactionable, and we'll be up'n'about with working Windows 32 bit distributions Real Soon™.
