### ISSUE TITLE
HTTP (not HTTPS) URL used in curl command

### ISSUE THREAD

**Issue by mbrukman** [grpc/grpc#7227]
The [Objective-C tutorial](http://www.grpc.io/docs/tutorials/basic/objective-c.html) includes the following line of code:

``` bash
$ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
```

Note that it's reading from http://grpc.io/release which is HTTP, not HTTPS, and pasting that directly into the command line. This is dangerous, as a simple MITM attack can introduce a security issue by returning `; <arbitrary command here>` to cause users to execute it with their credentials.

That said, https://grpc.io does not appear to respond, so this would require first acquiring an SSL certificate, e.g., via [Let's Encrypt](https://letsencrypt.org/), enabling HTTPS on grpc.io, and then updating the instructions in the docs to use an HTTPS URL.

**Comment by nicolasnoble** [comment]
Unfortunately, this isn't as simple as flipping a switch. It depends on github's ability to support SSL for custom domains on github pages. See isaacs/github#156.

**Comment by murgatroid99** [comment]
What if we use `https://grpc.github.io/release`?

**Comment by nicolasnoble** [comment]
That won't change anything, this is a redirect to http://www.grpc.io/release.

```
$ curl --verbose -L https://grpc.github.io/release
[...]
< HTTP/1.1 301 Moved Permanently
< Location: http://www.grpc.io/release
```
