### ISSUE TITLE
NodeJS int64 is a string

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#7229]
Hello,

when defining an int64 in a protobuf file. The value is decoded as a String on the client side. Should it not be of type [Long](https://github.com/dcodeIO/long.js) according to this [article](https://github.com/dcodeIO/ProtoBuf.js/wiki/Long)?

**Comment by murgatroid99** [comment]
It seemed to me that using strings to represent `int64` would be more useful than that `Long` type, so I made that the default. But this is configurable. `grpc.load` accepts an optional object as the third argument, and passing `{longsAsStrings: false}` will switch to using `Long` objects instead.

**Comment by Crevil** [comment]
@murgatroid99  Is this documented any where? I just came to the same unexpected conclusion. 
In the sparse [documentation of the Node.js API](https://github.com/grpc/grpc/tree/master/src/node) this is not mentioned.

**Comment by murgatroid99** [comment]
It is documented here: http://www.grpc.io/grpc/node/global.html#load. The formatting is a little messed up, but I'm working on improving that.
