### ISSUE TITLE
cmake compilation issue

### ISSUE THREAD

**Issue by seoz** [grpc/grpc#7233]
Hi,

I tried to build grpc using cmake and got the following error.
Why don't we build gmock from third_party/googletest?
I attached log files, so PTAL.

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /usr/bin/perl (found version "5.18.2")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
CMake Error at third_party/protobuf/cmake/tests.cmake:2 (message):
  Cannot find gmock directory.
Call Stack (most recent call first):
  third_party/protobuf/cmake/CMakeLists.txt:150 (include)

-- Configuring incomplete, errors occurred!
See also "/home/seoz/grpc/build/CMakeFiles/CMakeOutput.log".
See also "/home/seoz/grpc/build/CMakeFiles/CMakeError.log".

[CMakeError.log.txt](https://github.com/grpc/grpc/files/348732/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/grpc/grpc/files/348733/CMakeOutput.log.txt)

Thanks,
Daniel

**Comment by seoz** [comment]
Ping @tberghammer

**Comment by ericjang** [comment]
I had a similar problem (cannot find gmock directory) while attempting to compile third_party/protobuf https://github.com/grpc/grpc/blob/master/vsprojects/README.md via CMake, on Windows.

**Comment by tberghammer** [comment]
I created a pull request for fixing this issue (https://github.com/grpc/grpc/pull/7235).

Until it is merged there are a few possible workaround (any of them should work):
* Specify "-Dprotobuf_BUILD_TESTS=OFF" to the cmake command line
* or
* Download a released version of protobuf and specify it using "-DPROTOBUF_ROOT_DIR=<dir>" (e.g. from https://github.com/google/protobuf/releases/download/v3.0.0-beta-3/protobuf-cpp-3.0.0-beta-3.zip)
* or
* Run ./autogen.sh inside third_party/protobuf (will download gmock)

**Comment by seoz** [comment]
Thanks, I will try it with your workaround OR by manually merging your patch.
