### ISSUE TITLE
C# RpcException is missing a recommended constructor overload setting InnerException

### ISSUE THREAD

**Issue by kkm000** [grpc/grpc#7234]
All publicly consrtructible BCL exceptions provide a constructor overload that sets the `InnerException` property (through a base constructor invocation). `RpcException` must be augmented with such an overload:

``` c#
  public RpcException(Status status, string message, Exception innerException) : base(message, innerException) { ... }
```

The recommendations is mentioned, albeit non-literally, in [Best Practices for Exceptions](https://msdn.microsoft.com/en-us/library/seyhszts%28v=vs.110%29.aspx) and [How to: Create User-Defined Exceptions](https://msdn.microsoft.com/en-us/library/87cdya3t%28v=vs.110%29.aspx). In practice, it really helps to construct a different exception when converging multiple possible errors that have the same semantics, and it is very important not to lose the backtrace information in such a case.

**Comment by jtattermusch** [comment]
Is there some practical use case where exposing this overload would matter? The thing with RpcException is that it is only thrown by gRPC as a result of a remote call, in which case the Status and message are exactly what you need as there is no exception information transferred from the remote side besides  status, message and optionally the trailing metadata.

I can only imagine that you could use the InnerException if something went wrong in gRPC implementation itself - but I am not sure if the user should care. Also, the RpcException can only be constructed if the status code is obtained successfully (and C core guarantees that obtaining it will always succeed), so I am not quite sure where the inner exception would come from.

**Comment by kkm000** [comment]
You are right, this is rather a matter of convenience, when it is seems natural to reuse RPCException to report the error _as if_ it originated in the remoting layer. This is kind of borderline-legit, to my reckoning:

    public static async Task<T> ReadNext<T>(this IAsyncStreamReader<T> stream) {
      if (!await stream.MoveNext())
        throw new RpcException(new Status(StatusCode.Internal,
          "Server did not respond with required protocol message"));

      return stream.Current;
    }

**Comment by jtattermusch** [comment]
I see. IMHO, your use case is fairly controversial and you seem to have a reasonable workaround, so I'd need to see at least a few more other users asking for this in order to consider actually adding the constructor. Leaving this issue open for others to chime in.

**Comment by hsaliak** [comment]
@jtattermusch do we want to add the constructor for 1.1 or close the discussion?

**Comment by jtattermusch** [comment]
No action planned here. Closing this issue as part of issue bankruptcy.
