### ISSUE TITLE
Objective-C : GRPC and Protobuf compatibility mapping

### ISSUE THREAD

**Issue by underscoretang** [grpc/grpc#7238]
Is there a mapping of which versions are compatible with each other? I've used the configuration that has been provided but GPRC 0.14 got pushed to cocoapods. 

Right now the latest edge of what's available via pods and brew are these:

gRPC : 0.14.0
Protobufs: beta-3.1

for protoc, the install script [here](https://raw.githubusercontent.com/grpc/homebrew-grpc/master/scripts/install) downloads gRPC 0.15.0

which seems to generate objc files that aren't compatible with 0.14.0

**Comment by jcanizales** [comment]
Hi @underscoretang , sorry for the silence; I was waiting to have PR #7313 ready to break the good news: The correct version of `protoc` and the gRPC plugin to use are now resolved by Cocoapods (if one writes his local podspec as it's done in that PR) :)

**Comment by jcanizales** [comment]
This shouldn't be an issue anymore.
