### ISSUE TITLE
GRPC php extension outputting debug info

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#7252]
How can I disable the info that is now being logged because the grpc extension is enabled? Even scripts that don't use it are getting the output.

    D0706 08:01:35.428226606   28702 ev_posix.c:101]             Using polling engine: poll
    D0706 08:01:35.531626182   28702 channel.c:175]              Initialized secure channel

**Comment by thinkerou** [comment]
I only run `php -v`, it also prints debug info:

    ➜  ~ php -v
    D0707 09:49:58.902670000 140735179587584 ev_posix.c:101] Using polling engine: poll
    PHP 5.6.16 (cli) (built: Dec 22 2015 11:00:39)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
    ➜  ~

**Comment by stanley-cheung** [comment]
So the first line is coming from the gRPC C core library. That will probably be cleaned up as we move towards GA release. That I don't have direct control over.

The second line is coming from the PHP extension. I can probably remove it as it's not needed anymore.
