### ISSUE TITLE
Improve Ruby API documentation based on API review

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#7255]
The Ruby API review indicated some areas where documentation can be improved:
- Note that `ClientStub` creates a channel if one is not provided, and that the args hash is ignored if one is provided.
- Explain `:this_channel_is_insecure`.
- Improve wording of `ClientStub` class description.
- Verify that for public APIs, documented parameter order matches actual parameter order.

**Comment by hsaliak** [comment]
Closed per merged PR.
