### ISSUE TITLE
Update grpc to 0.14.0, The BoringSSL not found openssl/arm_arch.h

### ISSUE THREAD

**Issue by aa57779111** [grpc/grpc#7262]
I upgraded grpc to 0.14.0, but there is an error about BoringSSL, 
`openssl/arm_arch.h` file not found

this is the podfile
`platform :ios, '8.0'
#use_frameworks!

target 'vipkid-parent' do
    pod 'vipkid', :path => '.'
    pod 'SDWebImage','~>3.7'
    pod 'MBProgressHUD','~> 0.9.2'
end
`
vipkid.podspec

`Pod::Spec.new do |s|
  s.name     = 'vipkid'
  s.version  = '0.0.50'
  s.license  = '...'
  s.authors  = { 'fuyujia' => 'fuyujia@vipkid.com.cn' }
  s.homepage = 'www.vipkid.com.cn'
  s.summary = 'VIPKID ios parent grpc'
  s.source = { :git => 'https://github.com/...' }

  s.ios.deployment_target = '7.1'
  s.osx.deployment_target = '10.9'

  # Base directory where the .proto files are.
  src = "proto"

  # Directory where the generated files will be placed.
  dir = "Pods/" + s.name

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  # You can run this command manually if you later change your protos and need to regenerate.
  #s.prepare_command = "protoc --objc_out=. --objcgrpc_out=proto/*.proto"
  #s.prepare_command = "protoc --objc_out=. --objcgrpc_out=#{dir} #{src}/*.proto **/*.proto"

  s.prepare_command = <<-CMD
  mkdir -p #{dir}
  protoc -I #{src} --objc_out=#{dir} --objcgrpc_out=#{dir} #{src}/*.proto
  protoc -I #{src} --objc_out=#{dir} --objcgrpc_out=#{dir} #{src}/*/*.proto
  protoc -I #{src} --objc_out=#{dir} --objcgrpc_out=#{dir} #{src}/*/*/*.proto
  protoc -I #{src} --objc_out=#{dir} --objcgrpc_out=#{dir} #{src}/*/*/*/*.proto
  CMD

  # The --objc_out plugin generates a pair of .pbobjc.h/.pbobjc.m files for each .proto file.
  s.subspec "Messages" do |ms|
    ms.source_files = "#{dir}/*.pbobjc.{h,m}", "#{dir}/**/*.pbobjc.{h,m}"
    ms.header_mappings_dir = dir
    ms.requires_arc = false
    ms.dependency "Protobuf", "~> 3.0.0-beta-2"
    # This is needed by all pods that depend on Protobuf:
    ms.pod_target_xcconfig = {
      'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    }
  end

  # The --objcgrpc_out plugin generates a pair of .pbrpc.h/.pbrpc.m files for each .proto file with
  # a service defined.
  s.subspec "Services" do |ss|
    ss.source_files = "#{dir}/*.pbrpc.{h,m}", "#{dir}/**/*.pbrpc.{h,m}"
    ss.header_mappings_dir = dir
    ss.requires_arc = true
    ss.dependency "gRPC-ProtoRPC", "~> 0.14"
    ss.dependency "#{s.name}/Messages"
  end
end
`

**Comment by jcanizales** [comment]
PR #7264 fixes the problem :) I'm pushing the updated spec to Cocoapods.

**Comment by jcanizales** [comment]
Fixing broken versions of podspecs is not allowed anymore :( (see https://github.com/CocoaPods/Specs/pull/12199). So until the new release next week, you have to add this to your `Podfile` to get the fix:

```ruby
pod 'BoringSSL', :podspec => "https://raw.githubusercontent.com/grpc/grpc/release-0_14/src/objective-c/BoringSSL.podspec"
```

**Comment by makdharma** [comment]
Closing the bug since all code is checked in. @jcanizales still needs to push it to Cocoapods tho.
