### ISSUE TITLE
Error: Every time I update server file

### ISSUE THREAD

**Issue by sslgeorge** [grpc/grpc#7278]
When I update code on my GRPC server any first request made to it fails, it returns this error to the client: 

```
E0708 04:27:39.748702000 123145313406976 chttp2_transport.c:1810] close_transport: 
{
 "created":"@1467948459.748633000",
"description":"Failed parsing HTTP/2", 
"file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c", 
"file_line":1726,"referenced_errors":[{ "created":"@1467948459.748627000",
"description":"EOF",
"file":"../src/core/lib/iomgr/tcp_posix.c",
"file_line":233}]}
Error:  { Error
    at /Users/<user>/WorkSpace/personal/<project>/node_modules/grpc/src/node/src/client.js:417:17 code: 14, 
metadata: Metadata { _internal_repr: {} } }
```

**Comment by mike07026** [comment]
Platform : Windows 10 x64, VS2015 Update 2
Version  : grpc release-0_15
Language : C++

I modify helloworld example code ([greeter_client.cc](https://github.com/grpc/grpc/blob/release-0_15/examples/cpp/helloworld/greeter_client.cc) and [greeter_server.cc](https://github.com/grpc/grpc/blob/release-0_15/examples/cpp/helloworld/greeter_server.cc)) a bit to test, both server and client run in the same process（exe）, and got the same error E0708.

`int main(int argc, char* agrv[])
{
	std::thread thread(RunServer);
	std::this_thread::sleep_for(std::chrono::seconds(2));
	RunClient();
	thread.join();
	return 0;
}`

console output:

Server listening on 0.0.0.0:50051
reply : Hello world
E0708 13:04:47.923000000 17404 chttp2_transport.c:1810] close_transport: {"created":"@1467954287.923000000","description":"Failed parsing HTTP/2","file":"E:\LearnTest\repo_grpc_release_0_15\grpc\vsprojects\..\src\core\ext\transport\chttp2\transport\chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1467954287.923000000","description":"End of TCP stream","file":"E:\LearnTest\repo_grpc_release_0_15\grpc\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":179}]}
E0708 13:04:47.923000000 17404 chttp2_transport.c:1810] close_transport: {"created":"@1467954287.923000000","description":"End of TCP stream","file":"E:\LearnTest\repo_grpc_release_0_15\grpc\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":179}

I test the same code on grpc 0.14.1, and it runs just fine.
Is it a bug ? Or can i just ignore the error info ?

**Comment by ksmithut** [comment]
I've seen this same behavior using the node module. Errors on 0.15.1, No errors on 0.14.x

**Comment by paralin** [comment]
Getting this now, on linux, not windows.

**Comment by goru97** [comment]
Getting similar error all of a sudden:
```
{ Error: Unknown Error
    at /opt/ele/node_modules/grpc/src/node/src/client.js:417:17 code: 2, metadata: Metadata { _internal_repr: {} } }
```

**Comment by dgquintas** [comment]
Hi everyone, thanks for reporting this. Could anybody please provided the output of the server with tracing enabled? That is: `export GRPC_TRACE=all && ./greeter_server`.

**Comment by dgquintas** [comment]
Hi everyone again. It's likely that #7502 fixes this issue. It's just been merged into master and will also be merged into the v1.0.x branch shortly. Could you give it a try?

**Comment by mmende** [comment]
Hi everyone. I still get a similar error occasionally with the grpc node module v1.0.0 (when using it for the cloud speech api):

```
E0913 08:50:35.849495186   28798 chttp2_transport.c:1810]    close_transport:
{"created":"@1473749435.849355125",
"description":"Failed parsing HTTP/2",
"file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c",
"file_line":1726,
"referenced_errors":[
{"created":"@1473749435.849352701",
"description":"Secure read failed",
"file":"../src/core/lib/security/transport/secure_endpoint.c",
"file_line":157,
"referenced_errors":[
{"created":"@1473749435.849316032","description":
"EOF",
"file":"../src/core/lib/iomgr/tcp_posix.c","file_line":233}]
}]}
An uncaughtException occured { [Error] code: 14, metadata: Metadata { _internal_repr: {} } }
```

Any ideas what happens there and how to fix it? Kind regards.

**Comment by nemes1s** [comment]
Getting same errors while using it with hfc npm module

**Comment by zhagnsz** [comment]
I got the same error with npm module, more details below:

Error: {"created":"@1478070846.216783000","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
    at /Users/zhangsongzhou/Desktop/zhangsongzhou/projects/cms-api/node_modules/grpc/src/node/src/client.js:417:17

who can help me.....

**Comment by murgatroid99** [comment]
Nobody has reported a recurrence of this issue since 1.0.
