### ISSUE TITLE
*.orig files are unnecessary?

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#7280]
These files is generated for merge code?
https://github.com/grpc/grpc/blob/master/tools/doxygen/Doxyfile.c%2B%2B.internal.orig
https://github.com/grpc/grpc/blob/master/src/core/lib/http/parser.c.orig

**Comment by nathanielmanistaatgoogle** [comment]
Looks like they were erroneously introduced in dd385b6a19832992f130e55f33a02514b0bb4058.

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: what would you think of adding .orig-screening to the sanity tests?

**Comment by yang-g** [comment]
https://github.com/grpc/grpc/pull/7242 was trying to remove one. I just
added another one. THanks.

**Comment by dgquintas** [comment]
Uuuuuugh. Sorry about this. Mea culpa.

**Comment by thinkerou** [comment]
@nathanielmanistaatgoogle @ctiller I have added *.orig in .gitignore file, and added orig file screen, but the screening really needs? In fact, I think that it is OK for adding *.orig in .gitignore.

**Comment by thinkerou** [comment]
Fixed #7296
