### ISSUE TITLE
Objective-C: BoringSSL build error ('openssl/arm_arch.h' file not found)

### ISSUE THREAD

**Issue by timburks** [grpc/grpc#7299]
When I build a gRPC client for an iOS device, I get the following build error:

Lexical or Preprocessor Issue 
 'openssl/arm_arch.h' file not found' 
crypto.c

This error does not occur for simulator builds.

**Comment by makdharma** [comment]
Do you have https://github.com/grpc/grpc/pull/7264 ?

**Comment by timburks** [comment]
I don't think so.

I was pulling from your protobuf_import_issue7219 branch, which doesn't appear to have @jcanizales'  commit: https://github.com/grpc/grpc/pull/7264/commits/ccb184068d21758f905ecc3bfd42a2f9626dd5ee

**Comment by jcanizales** [comment]
Yeah you'll need to add this to your `Podfile` for the moment :( https://github.com/grpc/grpc/issues/7262#issuecomment-231508328

**Comment by jcanizales** [comment]
BoringSSL 5.0 is pushed now with the fix.
