### ISSUE TITLE
Protobuf 3, Python.  `ListFields` method doesn't return field if it has value equaled default value

### ISSUE THREAD

**Issue by ve-i-uj** [grpc/grpc#7301]
In protobuf 3 I can't get the fields in the message which are not empty. `ListFields` method doesn't work like it is described in the documentation. This problem appears when value in field equals default value. So, for example, I can't get boolean field through `ListFields` method if the value of field is False or integer field is 0 and so on. In protobuf 2 `ListFields` method works correct. Following example illustrates problem:

Proto file:

	syntax = "proto3";
	
	service EchoService {
	    rpc TestMethod    (TestMethodRequest)    returns (TestMethodResponse);
	}
	
	
	message TestMethodRequest {
	    int32 integer = 1;
	    string string = 2;
	    bool boolean = 3;
	}
	
	message TestMethodResponse{
	    int32 integer = 1;
	    string string = 2;
	    bool boolean = 3;
	    string empty = 4;
	    string nonempty = 5;	
	}

Test script:

    #!/usr/bin/env python
    # encoding: utf8
    
    """???."""
    
    import signal
    import threading
    import time
    
    from grpc.beta import implementations
    
    import testservice_pb2
    
    HOST = '127.0.0.1'
    PORT = 12345
    TIMEOUT = 3
    
    
    class EchoService(testservice_pb2.BetaEchoServiceServicer):
        
        @staticmethod
        def TestMethod(request, context):
            return testservice_pb2.TestMethodResponse(
                integer=request.integer,
                string=request.string,
                boolean=request.boolean,
                empty='',
                nonempty='nonempty'
            )
    
    
    def send(integer, string, boolean):
        """Send request and print nonempty response fields."""
        channel = implementations.insecure_channel(HOST, PORT)
        stub = testservice_pb2.beta_create_EchoService_stub(channel)
        req = testservice_pb2.TestMethodRequest(
            integer=integer,
            string=string,
            boolean=boolean
        )
        resp = stub.TestMethod(req, TIMEOUT)
        # get all fields in the message which are not empty
        print 'Returned values which are not empty:'
        for fdesc, value in resp.ListFields():
            print '%s: %s' % (fdesc.name, value)
    
    
    class ServiceThread(threading.Thread):
        
        def __init__(self):
            self.stoped = False
            super(ServiceThread, self).__init__()
            
        def run(self):        
            server = testservice_pb2.beta_create_EchoService_server(EchoService)
            server.add_insecure_port('%s:%s' % (HOST, PORT))
            server.start()
            while not self.stoped:
                time.sleep(0.1)
            server.stop(0)
        
    
    if __name__ == '__main__':
        service_thr = ServiceThread()
        service_thr.start()
         
        time.sleep(1)
          
        print 'Send values which are not equal default values and print response fields'
        send(integer=1, string='a string', boolean=True)
      
        print 'Send values which are EQUAL default values'
        send(integer=0, string='', boolean=False)
        
        service_thr.stoped = True
        service_thr.join()

**Comment by soltanmm** [comment]
Is this replicable without bringing in gRPC? If so, would you mind filing with [google/protobuf](https://www.github.com/google/protobuf)?

**Comment by ve-i-uj** [comment]
Yes, I can replicate it without bringing in gRPC. Thank you for advice.
