### ISSUE TITLE
Compilation failure - Visual Studio 2013

### ISSUE THREAD

**Issue by JamesSmaldon** [grpc/grpc#7337]
I am encountering a compilation error when building grpc for windows using VS Pro 2013 (Version 12.0.30723.00 Update 3).

I am doing the following:
1. Clone the repo
2. Load vsprojects\grpc.sln in visual studio
3. Right click on the grpc project and click build.

The compilation fails with the following error:
`[...]\grpc\cpp\lib\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.c(2011): error C2440: 'initializing' : cannot convert from 'gpr_slice' to 'gpr_slice_refcount *'`

If I change line 2011 in chttp2_transport.c to initialise the struct as follows, the compilation succeeds:

```
incoming_byte_stream_push_arg arg; 
arg.byte_stream = bs;
arg.slice = slice;
```

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
