### ISSUE TITLE
Set up interop tests between the v1.0.x branch and HEAD

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#7344]
The creation of the v1.0.x branch is expected to be a stable branch and hence, we need to set up interop tests with HEAD so that we catch any incompatibility or "drift" early.

/cc @nicolasnoble

**Comment by soltanmm** [comment]
Just out of curiosity, if there's a test that somehow breaks due to what is ostensibly a bug fix, will we consider that a broken test, or semantic baggage to carry until the next major version number?

**Comment by jcanizales** [comment]
I guess it'll depend on the specifics :)

**Comment by hsaliak** [comment]
@adelez ping on this, do you have an ETA on when we can have this?

**Comment by adelez** [comment]
ETA 8/17. :)

**Comment by adelez** [comment]
It's now up and running https://grpc-testing.appspot.com/job/gRPC_interop_GA/. Go is not included as it doesn't have a separate GA branch.
