### ISSUE TITLE
Node: Memory leak

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#7349]
Through an issue filed on gcloud-node (https://github.com/GoogleCloudPlatform/gcloud-node/issues/1414), it was reported that after making several thousand requests with the gcloud-node library, memory usage steadily grew, but wasn't being released, even after forcing garbage collection.

I've put a sample repo together, removing gcloud-node from the picture, and make the same API calls with just gRPC. That repo is here: https://github.com/stephenplusplus/grpc-memory-leak -- instructions on how to run is in the readme.

The results I saw confirmed the same; after 50,000 requests, the memory usage rises to around 100mb above where the usage started when the script was run. Periodically, as the memory rises, it will take a 7-15 MB dip. After all of those 50,000 requests, I call the garbage collector manually, which forces a dip of around the same amount.

Is there anything you can think of that might free up more memory?

A few quick notes:

- If you change the number of 50,000 to around 500,000, the memory used will go past 1GB.
- Making calls as rapidly as this script does is just for the sake of sane testing. The high memory usage was originally observed over 3 hours.
- I tested the same script using the example "hello world" dynamic greeter script, and did not experience the same memory usage.

**Comment by murgatroid99** [comment]
Regarding your last bullet, does that mean that you performed functionally the same test with a different service definition and server, and the memory leak did not occur?

Can you try logging the number of pending requests along with memory usage? A large number of pending requests would explain the memory usage. I suspect that's not the problem though, if making the requests over a longer timespan has the same result.

I'll look into it, but it's hard to tell from this information where the leak might be.

**Comment by stephenplusplus** [comment]
Yes, using a copy and paste of the https://github.com/grpc/grpc/blob/6b8a8e4a74fc83153a6fd3fbb7ec1ed2b288b4b4/examples/node/dynamic_codegen/greeter_client.js and https://github.com/grpc/grpc/blob/6b8a8e4a74fc83153a6fd3fbb7ec1ed2b288b4b4/examples/node/dynamic_codegen/greeter_server.js, with the helloworld.proto file, the memory did not exceed normal usage during the test, and flattened back down to 0 at the end of it.

I'm not sure how to log the number of pending requests, so feel free to modify the code in the test to make it give more useful information.

**Comment by stephenplusplus** [comment]
Works!
