### ISSUE TITLE
GPRC Python- Dictionary Response, not Attributes

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#7360]
Is there a function in the grpc python lib to transform GRPC response payload to dictionary in python so that you can do `response['users']`, not `response.users`?

**Comment by nathanielmanistaatgoogle** [comment]
The best way to achieve this would be to supply your own `response_deserializer` function when constructing your `MultiCallable` objects. If you're working with generated code, it's constructing your `MultiCallable` objects for you and you'll have to either edit your generated code or do something outside of gRPC Python (like writing a `response_as_dict(response)` function or something like that).

Is there more you can say about your use case and what it is that has you interested in seeing your responses as dictionaries?

**Comment by nathanielmanistaatgoogle** [comment]
I suppose not? Closing.

**Comment by bidossessi** [comment]
Hi, we have a use case for this scenario: 
We have a JSON service that makes a gRPC request, makes a list of a specific sub-messages in the response list, and send that back as a JSON response.
Our aim is for our service to dynamically handle additions/deletions to the message we're turning to a dict. 
Currently, we're using `protobuf_to_dict` in a list comprehension. If the grpcio library were to have such a method, it would mean one less dep in our project.
