### ISSUE TITLE
LocalError hides details of what exactly the error is

### ISSUE THREAD

**Issue by jerjou** [grpc/grpc#7367]
I'm using the grpc python with the Google Cloud Speech streaming API, which appears to spin up a thread to do streaming. However, if there's ever an error in the code run in the thread, I get a traceback with a `LocalError`, with no details filled out. ie the `LocalError` hides what the actual error is, making debugging pretty difficult.

See [python-docs-samples#374](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/374), and [python-docs-samples/speech/api/speech_streaming.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/api/speech_streaming.py) for the code. If you add `assert True is False` to the top of the `request_stream` function, you can see it happen.

**Comment by nathanielmanistaatgoogle** [comment]
With what version of `grpcio` are you working?

Does the `LocalError` have `code` and `details` attributes that tell you the status code and details of the failure?

Also consider upgrading from the Beta API (`from grpc.beta import implementations`, `implementations.server(<arguments>)`) to the GA API (`import grpc`, `grpc.server(<arguments>)`).

**Comment by jerjou** [comment]
Oh, I see - I was using 0.14.0. Upgrading to 0.15.0 fixes it. Thanks.

(FWIW, the `LocalError` did have `code` and `details`, but they were both set to `None`.
