### ISSUE TITLE
ruby to cloud using service acount  or compute engine creds fails

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#738]
+ gcloud compute --project stoked-keyword-656 ssh --zone asia-east1-a grpc-docker-testclients --command 'sudo docker run grpc/ruby bin/bash -l -c '\''SSL_CERT_FILE=/cacerts/roots.pem ruby /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb --use_tls --server_port=443 --server_host=grpc-test.sandbox.google.com --server_host_override=grpc-test.sandbox.google.com --test_case=service_account_creds'\'''
Warning: Permanently added '130.211.249.213' (ECDSA) to the list of known hosts.
Using /usr/local/rvm/gems/ruby-2.1.5
stdin: is not a tty
I0224 02:41:41.487513533       1 census_init.c:41] Initialize census library.
I0224 02:41:41.487673058       1 census_tracing.c:157] Initialize census trace store.
I0224 02:41:41.488210531       1 census_rpc_stats.c:225] Initialize census stats store.
 INFO  Object : loading prod certs from /cacerts/roots.pem
 INFO  Object : ... connecting securely to grpc-test.sandbox.google.com:443
"NOT RUN: service_account_creds; no service_account settings"
I0224 02:41:41.748968918       1 census_init.c:47] Shutdown census library.
I0224 02:41:41.749091397       1 census_rpc_stats.c:238] Shutdown census stats store.
I0224 02:41:41.749550788       1 census_tracing.c:170] Shutdown census trace store.

+ gcloud compute --project stoked-keyword-656 ssh --zone asia-east1-a grpc-docker-testclients --command 'sudo docker run grpc/ruby bin/bash -l -c '\''SSL_CERT_FILE=/cacerts/roots.pem ruby /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb --use_tls --server_port=443 --server_host=grpc-test.sandbox.google.com --server_host_override=grpc-test.sandbox.google.com --test_case=compute_engine_creds'\'''
Warning: Permanently added '130.211.249.213' (ECDSA) to the list of known hosts.
Using /usr/local/rvm/gems/ruby-2.1.5
stdin: is not a tty
I0224 02:40:39.378966895       1 census_init.c:41] Initialize census library.
I0224 02:40:39.379333158       1 census_tracing.c:157] Initialize census trace store.
I0224 02:40:39.379938754       1 census_rpc_stats.c:225] Initialize census stats store.
 INFO  Object : loading prod certs from /cacerts/roots.pem
 INFO  Object : ... connecting securely to grpc-test.sandbox.google.com:443
I0224 02:40:39.748807324     396 resolve_address_posix.c:129] logspam: getaddrinfo(grpc-test.sandbox.google.com, 443) resolved 2 addrs in 75ms:
I0224 02:40:39.749052628     396 resolve_address_posix.c:135] logspam:   [0] 64.233.187.81:443
I0224 02:40:39.749546122     396 resolve_address_posix.c:135] logspam:   [1] [2404:6800:4008:c05::451]:443
I0224 02:40:39.755485868     394 ssl_transport_security.c:166]      HANDSHAKE START -  before/connect initialization  - UNKWN 
I0224 02:40:39.755590285     394 ssl_transport_security.c:166]                 LOOP -  before/connect initialization  - UNKWN 
I0224 02:40:39.756004275     394 ssl_transport_security.c:166]                 LOOP -     SSLv3 write client hello A  - 3WCH_A
I0224 02:40:39.765240847     394 ssl_transport_security.c:166]                 LOOP -      SSLv3 read server hello A  - 3RSH_A
I0224 02:40:39.766469914     394 ssl_transport_security.c:166]                 LOOP - SSLv3 read server certificate   - 3RSC_A
I0224 02:40:39.766970467     394 ssl_transport_security.c:166]                 LOOP - SSLv3 read server key exchange  - 3RSKEA
I0224 02:40:39.767068196     394 ssl_transport_security.c:166]                 LOOP -       SSLv3 read server done A  - 3RSD_A
I0224 02:40:39.768701338     394 ssl_transport_security.c:166]                 LOOP - SSLv3 write client key exchang  - 3WCKEA
I0224 02:40:39.768936608     394 ssl_transport_security.c:166]                 LOOP - SSLv3 write change cipher spec  - 3WCCSA
I0224 02:40:39.769050905     394 ssl_transport_security.c:166]                 LOOP -         SSLv3 write finished A  - 3WFINA
I0224 02:40:39.769283618     394 ssl_transport_security.c:166]                 LOOP -               SSLv3 flush data  - 3FLUSH
I0224 02:40:39.774972966     394 ssl_transport_security.c:166]                 LOOP - SSLv3 read server session tick  - UNKWN 
I0224 02:40:39.775085347     394 ssl_transport_security.c:166]                 LOOP -          SSLv3 read finished A  - 3RFINA
I0224 02:40:39.775362234     394 ssl_transport_security.c:166]       HANDSHAKE DONE - SSL negotiation finished succe  - SSLOK 
D0224 02:40:39.781277112       1 frame_settings.c:219] CHTTP2: got setting 3 = 100
D0224 02:40:39.781344103       1 frame_settings.c:219] CHTTP2: got setting 4 = 65535
D0224 02:40:39.781450624       1 frame_settings.c:219] CHTTP2: got setting 5 = 16384
/usr/local/rvm/gems/ruby-2.1.5/gems/minitest-5.5.1/lib/minitest/assertions.rb:130:in `assert': compute_engine_creds: incorrect username. (Minitest::Assertion)
Expected: nil
  Actual: ""
	from /usr/local/rvm/gems/ruby-2.1.5/gems/minitest-5.5.1/lib/minitest/assertions.rb:164:in `assert_equal'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:214:in `compute_engine_creds'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:346:in `call'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:346:in `main'
	from /var/local/git/grpc/src/ruby/bin/interop/interop_client.rb:349:in `<main>'
I0224 02:40:43.421578000       1 census_init.c:47] Shutdown census library.
I0224 02:40:43.421683366       1 census_rpc_stats.c:238] Shutdown census stats store.
I0224 02:40:43.421837996       1 census_tracing.c:170] Shutdown census trace store.
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].

**Comment by tbetbetbe** [comment]
@donnadionne can you confirm that this is still the case or close this ?
