### ISSUE TITLE
building with new podspec file format

### ISSUE THREAD

**Issue by namsoila** [grpc/grpc#7396]
Building with the new podspec file format shown here:

https://github.com/grpc/grpc/tree/master/src/objective-c#integrate-a-proto-library-in-your-project

I have built grpc from source using this:

https://github.com/grpc/grpc/blob/master/INSTALL.md#build-from-source

Results in the following error:

[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 0.14)` depended upon by `HelloWorld`

**Comment by namsoila** [comment]
@jcanizales

**Comment by namsoila** [comment]
Here is the Podfile:

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'grpc_sample_071416_01' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'HelloWorld', :path => '.'

  # Pods for grpc_sample_071416_01

end

**Comment by namsoila** [comment]
Here is the podspec:

Pod::Spec.new do |s|
  s.name     = 'HelloWorld'
  s.version  = '0.0.1'
  s.license  = '...'
  s.authors  = { '<your name>' => '<your email>' }
  s.homepage = '...'
  s.summary = '...'
  s.source = { :git => 'https://github.com/grpc/grpc.git' }

  s.ios.deployment_target = '7.1'
  s.osx.deployment_target = '10.9'

  # Base directory where the .proto files are.
  src = '.'

  # We'll use protoc with the gRPC plugin.
  s.dependency '!ProtoCompiler-gRPCPlugin', '~> 0.14'

  # Pods directory corresponding to this app's Podfile, relative to the location of this podspec.
  pods_root = './Pods'

  # Path where Cocoapods downloads protoc and the gRPC plugin.
  protoc_dir = "#{pods_root}/!ProtoCompiler"
  protoc = "#{protoc_dir}/protoc"
  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

  # Directory where you want the generated files to be placed. This is an example.
  dir = "#{pods_root}/#{s.name}"

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  # You can run this command manually if you later change your protos and need to regenerate.
  # Alternatively, you can advance the version of this podspec and run `pod update`.
  s.prepare_command = <<-CMD
    mkdir -p #{dir}
    #{protoc} \
        --plugin=protoc-gen-grpc=#{plugin} \
        --objc_out=#{dir} \
        --grpc_out=#{dir} \
        -I #{src} \
        -I #{protoc_dir} \
        #{src}/*.proto
  CMD

  # The --objc_out plugin generates a pair of .pbobjc.h/.pbobjc.m files for each .proto file.
  s.subspec 'Messages' do |ms|
    ms.source_files = "#{dir}/*.pbobjc.{h,m}"
    ms.header_mappings_dir = dir
    ms.requires_arc = false
    # The generated files depend on the protobuf runtime.
    ms.dependency 'Protobuf'
    # This is needed by all pods that depend on Protobuf:
    ms.pod_target_xcconfig = {
      'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    }
  end

  # The --objcgrpc_out plugin generates a pair of .pbrpc.h/.pbrpc.m files for each .proto file with
  # a service defined.
  s.subspec 'Services' do |ss|
    ss.source_files = "#{dir}/*.pbrpc.{h,m}"
    ss.header_mappings_dir = dir
    ss.requires_arc = true
    # The generated files depend on the gRPC runtime, and on the files generated by `--objc_out`.
    ss.dependency 'gRPC-ProtoRPC'
    ss.dependency "#{s.name}/Messages"
  end
end

**Comment by namsoila** [comment]
Are we still supposed to use the setup shown here if utilizing frameworks?

https://github.com/grpc/grpc/pull/6849

**Comment by namsoila** [comment]
I just tried the pod with just:

pod '!ProtoCompiler-gRPCPlugin'

And still received the same error:

[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin`

**Comment by jcanizales** [comment]
> [!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 0.14)` depended upon by `HelloWorld`

Hi Osman,

I had Travis puzzle me with this for a while, because the podspec is totally there: http://cocoapods.org/pods/!ProtoCompiler-gRPCPlugin

I found that telling it to `pod repo update` made it behave (https://github.com/grpc/grpc/pull/7359/commits/76628706ac688a02efd4dcf74cff8ebfc2c925ab). Could you try that on your machine?

**Comment by namsoila** [comment]
Trying

**Comment by namsoila** [comment]
Great! Installing.

Thanks Jorge.

**Comment by jcanizales** [comment]
No problem! Glad that it worked for you too. I wish the Cocoapods error message said "try pod repo update?"; it would have saved me plenty of time :)
