### ISSUE TITLE
Python: need to delete unused import lib?

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#7408]
Such as: https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/setup.py
These libs are not used:
    
    import shutil

    from distutils import core as _core
    from distutils import extension as _extension

    from setuptools.command import egg_info

**Comment by thinkerou** [comment]
But, it use `pylint: disable=unused-import` to ignore warning of pylint:
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/implementations.py#L35
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/implementations.py#L43
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/implementations.py#L44
This why?

**Comment by thinkerou** [comment]
If delete-unused-import is needed, I think we should use `pyflakes` and `autoflake`.
But I'm not sure whether need to delete these unused imports.

**Comment by soltanmm** [comment]
W.r.t. https://github.com/grpc/grpc/issues/7408#issuecomment-233173286, some of the imports are used for record-keeping purposes in files as a note to developers reading over the code, saying, "We don't necessarily use this module directly, but objects from this module are used by the specification." (as noted [here](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/implementations.py#L32) and [here](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/beta/implementations.py#L37)). Unused import libs in `setup.py` are discardable, though; there's no such reason for them being in the setup scripts.

**Comment by nicolasnoble** [comment]
Do we have a resolution for that one ?

**Comment by nathanielmanistaatgoogle** [comment]
Resolved in [pull request 7820](https://github.com/grpc/grpc/pull/7820).
