### ISSUE TITLE
grpc_cpp_plugin doesn't seem to be working

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc#741]
Have installed according to instructions but when I try to use it I'm getting back:
--grpc_out: protoc-gen-grpc: Plugin killed by signal 11

**Comment by wilsonwen** [comment]
btw, how you avoid this error ?

**Comment by wilsonwen** [comment]
I figured it out, by recompiling the whole grpc project.
As you mention, it's the version problem.

**Comment by tangjiaxi** [comment]
@LisaFC @wilsonwen Excuse me,  I met this error,too.  recompiling the whole grpc project did not slove it. What's the other possible reason ?
