### ISSUE TITLE
protoc version detection problem

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#742]
I have protoc 3.0.0 in the system but when I make install under grpc. It still says I do not have it. On the other hand, building and running examples under grpc-common are just fine.

yangg@dualface:~/github/grpc$ protoc --version
libprotoc 3.0.0

angg@dualface:~/github/grpc$ sudo make install
[sudo] password for yangg: 
[INSTALL] Installing public C headers
[STRIP]   Stripping libgpr.a
[STRIP]   Stripping libgrpc.a
[STRIP]   Stripping libgrpc_unsecure.a
[INSTALL] Installing libgpr.a
[INSTALL] Installing libgrpc.a
[INSTALL] Installing libgrpc_unsecure.a
[STRIP]   Stripping libgpr.so
[STRIP]   Stripping libgrpc.so
[STRIP]   Stripping libgrpc_unsecure.so
[INSTALL] Installing libgpr.so.0.8.0.0
[INSTALL] Installing libgrpc.so.0.8.0.0
[INSTALL] Installing libgrpc_unsecure.so.0.8.0.0
[INSTALL] Installing public C++ headers
[STRIP]   Stripping libgrpc++.a
[INSTALL] Installing libgrpc++.a
[STRIP]   Stripping libgrpc++.so
[INSTALL] Installing libgrpc++.so.0.8.0.0
[INSTALL] Installing grpc protoc plugins
[INSTALL] Installing root certificates
Your system doesn't have protoc 3.0.0+ installed. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.

Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, you can re-run this check by doing:

   make verify-install

**Comment by x1957** [comment]
I still have this problem.

**Comment by nicolasnoble** [comment]
Could you please try sudo protoc --version and tell what happens then ? I've seen sometimes people with a broken sudo environment that wouldn't actually find the protoc binary, which is why sudo make install wouldn't find it either.

**Comment by x1957** [comment]
APTX4869:cc x1957$ sudo protoc --version
libprotoc 3.0.0
