### ISSUE TITLE
PHP: output logs when call createDefault of CallCredentials

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#7422]
Test code:

    ➜  unit_tests git:(phpt) ✗ cat cc.php
    <?php
    class ChanellCredentialsTest extends PHPUnit_Framework_TestCase
    { 
        public function testCreateDefault()
        {
            $channel_credentials = Grpc\ChannelCredentials::createDefault();
            $this->assertSame('Grpc\ChannelCredentials', get_class($channel_credentials));
        }
    }

Then run it using `phpunit cc.php`, the result:
    
    D0716 08:45:23.929155000 140735164002304 ev_posix.c:106] Using polling engine: poll
    PHPUnit 5.3.2 by Sebastian Bergmann and contributors.

    E0716 08:45:24.016781000 140735164002304 json_token.c:115] Could not deserialize private key.
    .                                                                   1 / 1 (100%)

    Time: 87 ms, Memory: 12.00Mb

    OK (1 test, 1 assertion)

So, this maybe not set google_default auth, but I should how to do?

**Comment by stanley-cheung** [comment]
The code is expecting either the env variable `GOOGLE_APPLICATION_CREDENTIALS` to be set to point to the gcp credentials file, or the file `.config/gcloud/application_default_credentials.json` be there.

On second thought, we shouldn't be including this in the unit test. User testing grpc does not need to use google credentials.

**Comment by thinkerou** [comment]
Fixed https://github.com/grpc/grpc/pull/7464
