### ISSUE TITLE
iOS bulid static library error

### ISSUE THREAD

**Issue by hucool** [grpc/grpc#7435]
i want bulid private static lib for grpc

s.dependency 'Protobuf', '~> 3.0.0-alpha-4'
s.dependency 'gRPC', '~> 0.14'
s.dependency 'gRPC-ProtoRPC', '~> 0.14'
s.dependency 'BoringSSL', :podspec => "https://raw.githubusercontent.com/grpc/grpc/release-0_14/src/objective-c/BoringSSL.podspec"

s.dependency 'BoringSSL' ...  line   error

**Comment by jcanizales** [comment]
Hi @hucool , what is the error you get?

**Comment by jcanizales** [comment]
And does it also happen if you use `s.dependency 'gRPC-ProtoRPC', '~> 1.0.0-pre1'` and remove the other lines?

**Comment by jayantkolhe** [comment]
seems fixed.
