### ISSUE TITLE
Node: passing a Namespace reflection to loadObject fails

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#7436]
I can't seem to get the node client working properly. I always get the error "this.rpcImpl is not a function" when trying to call functions.

Looking at the actual object itself, it seems rpcImpl is a string, but the rpc function is trying to call it like a function. `this.rpcImpl(method.fqn(), req, function(err, res) { // Assumes...`

**Comment by paralin** [comment]
I can now confirm that this happens when you pass a namespace into the loadObject function. GRPC does not properly load all of the services underneath the namespace as expected.

**Comment by murgatroid99** [comment]
Can you provide a proto file and the corresponding JavaScript code to reproduce this?

**Comment by paralin** [comment]
Welll now I can't reproduce it, will reopen if I can. Thanks.
