### ISSUE TITLE
Write a pretty-printer for errors

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#7439]
Now that we're collating awesome error information, write a module that can take a grpc_error and produce a nicely readable (likely multi-line) error message.

This will likely need to include some heuristics for display based on the information that's contained in the error object itself. We may want to expand what's recorded to make display easier. We'll definitely want to be a little recursive to explain how nested errors _may have_ led to the problematic outcome.

**Comment by yang-g** [comment]
@ncteisen should we mark this done?

**Comment by ncteisen** [comment]
I can take a really pass at this this week. Would be nice to have

**Comment by ncteisen** [comment]
I don't think we need to pursue this
