### ISSUE TITLE
Optimize common cases for pollset_add_fd with epoll

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#7442]
There are two common cases in a warmed up system:
pollset.pi == NULL, fd.pi != NULL
pollset.pi == fd.pi, fd.pi != NULL

For the former, we currently acquire three mutexes.
For the latter, we acquire two.

My (unconfirmed) suspicion is that we could reduce the latter to zero by making pi atomic (we'd just do two no-barrier loads outside the locks and compare). My way more out there suspicion is that similar tricks would work for the former case also.

**Comment by yang-g** [comment]
Assume stale, closing
