### ISSUE TITLE
Ban std::thread (etc) in test/cpp and in C++ style guide

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#7445]
For consistency between test/cpp and src/cpp , we need to be using grpc::{thread, mutex, unique_lock, ...} in both test/cpp and src/cpp . We are currently only consistently using these in src/cpp and often using std::thread etc in test.

We need to clean these up from test and explicitly mention this in the style guide

**Comment by yang-g** [comment]
:)

**Comment by yang-g** [comment]
There are about 100 std::thread in the codebase. Do we give up on this?
