### ISSUE TITLE
grpcio-tools should have a more idiomatic Python API

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7456]
@kpayson64 [separately wrote](https://github.com/grpc/grpc/pull/7419#discussion_r71220781): "I'm still not in love with [this](https://github.com/grpc/grpc/blob/7c467547ba988ae56e05b02220143f4ea6930b91/tools/distrib/python/grpcio_tools/grpc/tools/protoc.py#L37) as a public API though, it seems awkward to have a python function that takes a series of shell style argument strings. If we are going to vend a way to generate protos in python code, I would much rather see explicit arguments for each property.".

Yep, we should put a proper function, with a better name than "main", and with properly typed parameters, in there somewhere.

**Comment by soltanmm** [comment]
Sure, [then](https://github.com/pypa/pip/blob/master/pip/__init__.py#L197) [you](https://github.com/pypa/pip/blob/master/pip/__init__.py#L318) [look](https://github.com/pypa/pip/blob/master/pip/__main__.py) [at](http://www.programcreek.com/python/example/8110/pip.main) `pip`. Sort of drives me towards ambivalence.

**Comment by nathanielmanistaatgoogle** [comment]
[Just because an entire programming language community jumps off a bridge should we as well](https://xkcd.com/1170/)?

**Comment by soltanmm** [comment]
Arguably that's what we've been doing this whole time with `distutils` and `setuptools` and and and... :laughing: But, sure, I never said I'm against it. Just ambivalent.

**Comment by nathanielmanistaatgoogle** [comment]
Punting; the resolution of this issue will be ultimately tied up with the resolution of the work item for the protocol buffers maintainers to release a "`protobuf-tools`" Python package of their own exposing a Python API to vanilla `protoc`.
