### ISSUE TITLE
Document useful grpc_channel_args

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#7458]
/cc @nathanielmanistaatgoogle @ctiller 

We need a simple document discussing channel args and potentially useful one for advance cases. Wrapped languages pass these args to core but they are currently not documented. 

Either a markdown or doxygen comments that can be referenced would be a good starting point. 

Ref: http://www.grpc.io/grpc/core/structgrpc__channel__args.html

**Comment by dgquintas** [comment]
The list is basically here: https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L115

On top of the two methods in `ChannelArguments`, `SetCompressionAlgorithm` and `SetUserAgentPrefix`, already doxygen-documented at https://github.com/grpc/grpc/blob/master/include/grpc++/support/channel_arguments.h

If the comments from grpc_types.h look good enough, I can put together a small PR updating the comments on the  `grpc_channel_args` struct to reference them.
