### ISSUE TITLE
Node: timeout / deadline on calls

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#7472]
Is it possible to set a timeout / deadline on calls in Node?

```
Failed to connect to channel, retrying
Retry in 119.933478284 seconds
```

I read through the code and found some references to a deadline but couldn't figure out how to set it.

**Comment by murgatroid99** [comment]
When you make a call, you can pass the deadline as an optional parameter before the callback. The deadline should just be a date object.

**Comment by paralin** [comment]
Am I blind or are there no docs on this?

**Comment by murgatroid99** [comment]
No, you're right. At the moment, the only documentation for this is in the source files themselves.

**Comment by murgatroid99** [comment]
The API for setting deadlines on calls has been documented as part of the [`CallOptions` type](https://grpc.io/grpc/node/grpc.Client.html#~CallOptions).
