### ISSUE TITLE
C-core assumes a deterministic garbage collector is present

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#7478]
The current C-core requires that all memory must be collected before the shutdown is initiated else it starts printing error messages about potential memory leaks. 
This is of course coming from good intentions, however, it relies on a deterministic garbage collector being present. When using the C-core with a [language that uses a non-deterministic garbage collector](https://morepypy.blogspot.de/2013/10/incremental-garbage-collector-in-pypy.html) (i.e. PyPy), there is a certain time frame between when the object has been marked for deletion and when the object is actually deleted. This results in warnings of potential memory leaks and logs about the leaked objects. 

Now, I'm not asking for a rework of the software design, but, is it possible to indicate to the core that we're using a non-deterministic GC and the the collection would happen at some point so it should stop printing those statements?

**Comment by dgquintas** [comment]
Are you referring to messages of the form `Failed to free X iomgr objects before shutdown deadline: memory leaks are likely`?

**Comment by thunderboltsid** [comment]
@dgquintas Yes. Here's a [paste](http://pastebin.com/LnxWxF1u) from the run of the route_guide example using PyPy with the incminimark GC. Scroll to the end to see the messages I'm talking about.

**Comment by ctiller** [comment]
The right thing to do here is ensure the last grpc_shutdown is not called
until after all such objects have been destroyed by the environment. C++
achieves this by doing an init/shutdown pair for each object that could
cause a leak.

We guarantee that after the final grpc_shutdown no allocations are
outstanding and no threads are executing: it's safe to dlclose the gRPC C
code. In many cases it would be unsafe to do any deallocations later as
internal control structures have disappeared.

**Comment by soltanmm** [comment]
We might need to refactor Python to keep track of Cython->Core objects with weak references and then maybe wrap our `Py_AtExit`-registered shutdown with a block on the weak references (unless that deadlocks because of `Py_AtExit`, in which case we should still be able to get the desired effect with a daemonic thread and weak references).

**Comment by dgquintas** [comment]
As @ctiller has said, this is not an issue with the core but rather with the current way Python performs shutdown. Reassigning (semi randomly) to @soltanmm

**Comment by soltanmm** [comment]
Ah I misunderstood what @ctiller had said; the `grpc_init`/`grpc_shutdown` pair thing sounds much, much better.

**Comment by nathanielmanistaatgoogle** [comment]
One question I have that I don't think has found an answer: does the core have any semantics around not returning objects ever? As in, we call `grpc_init`, then `grpc_insecure_channel_create`, and then attempt to exit the wrapped language interpreter - does the core have any guaranteed behavior in that case? Might it crash the process, or block, or hang, or...? I mean, we _would be_ obeying the rule about not calling `grpc_shutdown` while still holding the allocated `grpc_channel`.

**Comment by nathanielmanistaatgoogle** [comment]
To put in writing an exchange I had with @ctiller: so long as the "active use" invariant of "all core memory object lifetimes (started and ended by `create` and `destroy` function calls) must take place during a time when the number of `grpc_init` function calls exceeds the number of `grpc_shutdown` function calls" is maintained, the core doesn't care how exiting is handled, and if a nondeterministic garbage collector doesn't clean up all objects before exiting, that's fine.

**Comment by soltanmm-google** [comment]
I believe then that with @thunderboltsid's change we're fine for this; please reopen if I'm wrong.
