### ISSUE TITLE
Question/idea: Is there a hook to validate a certificate for a host?

### ISSUE THREAD

**Issue by bennyscetbun** [grpc/grpc#7506]
Hi,
First Thanks for your awesome work :)
We have a small problem in my company.
We are using a proxy to debug our application with our own root certificate.
Usually we just add the root certificate to the device and everything is working.
But on IOS(and maybe other devices/os) grpc isnt using the root certificates from the device.

We dont want to set the certificate manually in the code... (we want to be able to use our tool even on store version and we dont want to ship the certificate, even if it s only the public part)

Is there a Hook for a callback to validate a certificate for grpc only if grpc fail to validate a certificate with its own ways? 
Something like(go style)

``` go
var certificateCallBack func (certificate string, host string) bool
```

if there is, can you tell me where?

That way i would be able to check the os root certificates or use any certificate check i want.
without the callback normal behaviors occurs and certificate is rejected as normal.

if there is not, What do you think of adding this ?

Thanks.

**Comment by jcanizales** [comment]
@jboeuf I don't know if the C library has such a hook; do you?

I know that the ObjC layer isn't currently exposing anything like it.

**Comment by jboeuf** [comment]
There's no currently such hook for validating certs in grpc indeed.

However there are a few things you can do modify the TLS root.
1. Use the `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` environment variable to point to your root (don't know if this works on iOS).
2. you can also use `grpc_set_ssl_roots_override_callback` function to serve a root for all ssl connections.
3. you can of course specify your own custom root when creating ssl credentials.

We *could* add a new function like the one that you're proposing but at this point, it looks like we have sufficient flexibility to take care of this particular problem and I would be worried about exposing another function in the API that we will have to support.

Makes sense?

**Comment by bennyscetbun** [comment]
Thanks JBoeuf , it does make sense
We ve already overlooked this solution. But on IOS i cant access the os certificates.
Right now we are registering our certificates in GRPC but we would like to test our store version (that wont own this certificate inside the application).
That s why a hook would solve all our problems.
Thanks for the answer :)
