### ISSUE TITLE
Node.js grpc does not have close function for connection?

### ISSUE THREAD

**Issue by ychen11** [grpc/grpc#7513]
Cannot find any method to close the client connection from node grpc.

**Comment by edvinerikson** [comment]
Would be nice with an answer. The `close` method on the Channel class don't seem to be closing the connection right away.

**Comment by ychen11** [comment]
@edvinerikson Actually there is only a getClientChannel method in client class, I don't see any method about closing connection anyway.

**Comment by edvinerikson** [comment]
`getClientChannel(client).close();` works for me. Some docs about it would be nice though

**Comment by tejasmanohar** [comment]
+1

**Comment by murgatroid99** [comment]
As of grpc@1.2.0, you can now use the function `grpc.closeClient(client)` to close a client connection.

**Comment by tejasmanohar** [comment]
wooohoo!

**Comment by gih2yun** [comment]
@murgatroid99 can i see code example `grpc.closeClient`?

**Comment by tejasmanohar** [comment]
@gih2yun What's confusing (not mocking, actual question)? `grpc` is the module, and `client` is the client GRPC has generated with your custom functions.

**Comment by gih2yun** [comment]
@tejasmanohar Thanks for response.

My code calling `grpc.closeClient` failed  intermittently.
```
  var client = new my.GrpcService('127.0.0.1:1234', grpc.credentials.createInsecure());
  var request = new my.RequestObject();
  request.name = req.body.name;
  request.exec_cmd = req.body.exec_cmd;
  client.someGrpcMethod(request, function(err, r) {
   grpc.closeClient(client); // <======== this line
   // blah
   // blah
  });
```

I think above code is not correct.
Where is the best position to call `grpc.closeClient()`?
I'll test to call in proess.nextTick at the end of callback function.
How do you think about?

**Comment by tejasmanohar** [comment]
Haven't used the method yet. Looks ok if you want to close the client right after a single call. This looks _ok_ to me. What was the error?

**Comment by murgatroid99** [comment]
That should work just fine. What failure are you seeing?
