### ISSUE TITLE
Introspecting server proto

### ISSUE THREAD

**Issue by sheerun** [grpc/grpc#7516]
Hey,

I wonder if similarly to [graphql](http://graphql.org/docs/introspection/) it's possible to introspect grpc server by fetching fetching .proto file it uses (and then dynamically instantiate grpc client on the client). 

Of course I could implement it with custom remote method and opening second grpc session, but I believe such functionality should be available by default, standardized, and without need to create second grpc session (e.g. custom HTTP2 call).

Use case: dynamically connecting javascript client without needing to attach .proto file on frontend.

**Comment by y-zeng** [comment]
Hi @sheerun, I think server reflection might be a choice to implement this. 
- [Enable server reflection](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/Makefile#L36)
- [Create client messages using server reflection](https://github.com/grpc/grpc/blob/master/test/cpp/util/proto_file_parser.cc#L105)

But it still creates new HTTP2 calls to fetch server protos. And it's only available in C++ and go servers currently. Other languages may have it later.

**Comment by sheerun** [comment]
That's it, thanks :) JS implementation would be even better, but no hurry for me
