### ISSUE TITLE
Installing grpcio (Python) 1.0rc1 fails to install in Python 3.4 on Windows

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#7528]
See [another issue with failed Windows build][1]

/cc @tseaver @jgeewax @bjwatson @soltanmm @daspecster

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/2001#issuecomment-234655366

**Comment by bjwatson** [comment]
@dhermes @soltanmm Do you think this has anything to do with https://github.com/grpc/grpc/issues/7485?

**Comment by kpayson64** [comment]
@dhermes @tseaver @bjwatson 
I've added binary Windows packages for Python3.4/3.5.  Could you verify that the windows build now passes?

**Comment by daspecster** [comment]
@kpayson64, this is building off `master`.
https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn

**Comment by daspecster** [comment]
Looks green to me!
![screen shot 2016-08-16 at 1 07 04 pm](https://cloud.githubusercontent.com/assets/192456/17708300/6843126c-63b2-11e6-988e-d4778b294af4.png)

**Comment by dhermes** [comment]
Ditto on an actual merge to master: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.557.master

/cc @omaray

**Comment by omaray** [comment]
sweet
