### ISSUE TITLE
allow changing of GRPC logger while running

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#7529]
Currently, it looks like a lot of classes that log in the c# GRPC wrapper fetch their loggers from the Grpc.Environment on startup, but are unaffected by future changes to that global logger. 

It looks like logging is only done on errors and warnings, so changing these classes to always use the global logger shouldn't cause a performance hit.

**Comment by hsaliak** [comment]
@jtattermusch do we want to do this for 1.1 or can we close the issue?
