### ISSUE TITLE
error when pod package grpc framework   ObjC

### ISSUE THREAD

**Issue by lswhcmcc** [grpc/grpc#7544]
I want to package static framework for grpc
through  pod lib create BZLib then pod lib lint BZLib.podspec -only -errors --verbose

errors:

1.#import <ProtoRPC/ProtoService.h>
BZLib/Chat.pbrpc.h:3:9: fatal error: 'ProtoRPC/ProtoService.h' file not found
but, #import "ProtoService.h" can find

BZLib.podspec: 
s.subspec 'ProtoRPC' do |ss|
src_dir = "ProtoRPC"
ss.source_files = "#{src_dir}/*.{h,m}"
ss.header_mappings_dir = "."
1. pod lib lint BZLib.podspec -only -errors --verbose
   - ERROR | [BZLib/Messages, BZLib/Services, BZLib/ProtoRPC, and more...] xcodebuild: Returned an unsuccessful exit code.

**Comment by jcanizales** [comment]
Hi, can you try again with the latest version of gRPC? Framework support was one of the latest things we managed to solve before 1.0.

**Comment by muxi** [comment]
Closed due to no response and activity
