### ISSUE TITLE
Dynamic frameworks don't work when protos are in nested directories

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#7563]
This blocks Swift clients of [Google APIs](https://github.com/googleapis/googleapis/tree/master/google).

Problem:

Imports of files generated by `protoc` needs to be of the form:

``` objective-c
#ifdef ...
  #import <FrameworkName/MyProto.pbobjc.h>
#else
  #import "nested/dir/MyPorot.pbobjc.h"
#endif
```

Right now we only output `#import "nested/dir/MyPorot.pbobjc.h"`, which conveniently works when the protos are all in the same directory, as in our tests :) Notice that we output the correct thing for the well-known types that come in the runtime, but it needs to be done for all imports.

The `FrameworkName` is to be obtained from a helper function in `libprotoc`, as the logic to derive it is complex and shouldn't be duplicated.

@thomasvl / @sergiocampama: Is there such a helper function? If not, can we have one? In the ideal world, the function would get a proto file (as a descriptor or as a path) and return a string with the whole snippet above.

**Comment by jcanizales** [comment]
CC @timburks

**Comment by timburks** [comment]
This surfaced as a problem with Cloud Speech samples: https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/4

**Comment by sergiocampama** [comment]
What would the ifdef symbol be in your case?

We do have the named_framework_to_proto_path_mappings_path option as described here:

https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/objectivec/objectivec_generator.cc#L90

But that only adds the import as either Framework style or relative style, not with an ifdef as in your example... Does this work for your use case?

**Comment by jcanizales** [comment]
Well the preprocessor macro `GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS` so far is just letting us distinguish Cocoapods use from Bazel use, when importing the well-known types, as Bazel requires imports to be real paths.

But it's true that Bazel use can be distinguished further by just not passing the framework options to `protoc`, so I guess the `#ifdef` isn't really needed there. But we need to be sure that our imports look the same as what `protoc` generates for messages.

**Comment by jcanizales** [comment]
The `named_framework_to_proto_path_mappings_path` option to `protoc` is what @timburks is using, but in our plugin we rather not duplicate the logic that combines that and `generate_for_named_framework` to create the correct import.

**Comment by thomasvl** [comment]
Is there a request for the protobuf library here?  WKTs does the can do the two import styles because we only support one framework name for those protos.  But since anyone can package the grpc protos as they see fit, any number of names could be used and a simple #if/#else pattern won't handle everything.

**Comment by jcanizales** [comment]
Hey @makdharma, can you implement the fix in the code generator?

**Comment by hsaliak** [comment]
@makdharma is this issue still relevant?

**Comment by jcanizales** [comment]
It is. All our APIs under https://github.com/googleapis/googleapis/ have this problem preventing them to be used from iOS without painful manual hacks.

**Comment by yang-g** [comment]
Adding @muxi, not sure whether this is still an issue.
