### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#757]
This probably isn't that hard.

**Comment by nathanielmanistaatgoogle** [comment]
As much as this probably isn't that hard, it's probably not something to which we're going to get any time soon, and with each passing day 2.6, which is already really old, gets even older.

We likely will not do this. Speak up and make a counterargument if you really want Python 2.6 support?

**Comment by methane** [comment]
No. And I don't need Python 2.7 too. We don't use Python 2 for new project anymore.

**Comment by nathanielmanistaatgoogle** [comment]
That's ten months of crickets chirping. Okay, we are never supporting Python 2.6.

[And you shouldn't either!](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html)
