### ISSUE TITLE
boringssl failed to build with MS Visual Studio 2015 on Windows 10 due to X509_NAME macro conflict

### ISSUE THREAD

**Issue by 0xAAE** [grpc/grpc#7573]
Hi! Some files that #include "internal.h" (from ssl/) failed to compile due to indirect include of wincrypt.h. Those file define X509_NAME conflicting with <x509.h> and breaks building boringssl project. As for me, I add preprocessor definition __WINCRYPT_H__ to whole project to prevent including <wincrypt.h> at all.
There is exact list of injured files from boringssl: ssl_file.c ssl_lib.c s3_srvr.c s3_lib.c s3_clnt.c ssl_cert.c v3_purp.c x_x509.c x_crl.c x509cset.c x509_vfy.c x509_lu.c by_dir.c

**Comment by gggin** [comment]
it's easy to define define `WIN32_LEAN_AND_MEAN` in boringssl's gyp
