### ISSUE TITLE
grpc-tools (NodeJS) has an old protoc

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc#7599]
The 1.0.0-pre1 version in npm of grpc-tools does not have the 3.0.0 protoc binary.  As a result, map types do not generate properly and are instead lists.  Would it even make sense to package protoc as a standalone npm package that versions/releases with the protobuf libraries instead of gRPC?  If not, an ETA on re-release would be appreciated :)

Thanks!
@murgatroid99

**Comment by murgatroid99** [comment]
The 1.0.0-pre2 version of grpc-tools will have protoc 3.0.0, and we should be publishing that any day now. And we do intend to package protoc as its own package at some point.

**Comment by jhspaybar** [comment]
Thanks!  I'll wait patiently then :)
