### ISSUE TITLE
Windows linking C++ with grpc libs

### ISSUE THREAD

**Issue by jawadkho** [grpc/grpc#7607]
I have a C++ Visual Studio 2015 project. I've generated the the protos output as well as attached grpc.lib, grpc++.lib and gpr.lib to _Additional Dependencies_. However when compiling I get the following and the build fails:

`1>main.obj : error LNK2001: unresolved external symbol "public: void __thiscall grpc::ServerBuilder::RegisterService(class grpc::Service *)" (?RegisterService@ServerBuilder@grpc@@QAEXPAVService@2@@Z)`
Full output: http://pastebin.com/4DSPfnrn

I've been stuck at this issue for a few days now and at this point I don't remember all the things I've tried.

**Comment by plasticbox** [comment]
In my opinion, you need openssl or boringssl libs. 

1. Install grpc.dependencies nuget packages
grpc.dependencies.openssl
grpc.dependencies.openssl.redist
grpc.dependencies.zlib
grpc.dependencies.zlib.redist

ref : https://github.com/plasticbox/grpc-windows

2. Just run
use grpc_unsecure.lib, grpc++_unsecure.lib

**Comment by jawadkho** [comment]
To be clear, do you mean I should add the grpc dependencies when compiling the grpc lib files or when compiling my project which uses the libs?

**Comment by plasticbox** [comment]
use gpr.lib, grpc.lib, grpc++.lib, then required openssl, and zlib
or
use gpr.lib, grpc_unsecure.lib, grpc++_unsecure.lib, then required only zlib
unsecure libs are not use openssl so if you are want to just compile and run test, then its more comfort.

**Comment by iain17** [comment]
Could we just have these .lib files as a download?

**Comment by jtattermusch** [comment]
Issue >9 months old. Closing. 
Please use cmake to build on C++ on Windows.
