### ISSUE TITLE
Unwanted logging statements when using the ruby gem

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#7620]
One of the glcloud-ruby users opened GoogleCloudPlatform/gcloud-ruby#814 for unwanted logging statements being printed to stdout when the grpc gem is first required.

```
I0802 05:08:16.217477358   23373 ev_epoll_linux.c:84]        epoll engine will be using signal: 36
D0802 05:08:16.217850760   23373 ev_posix.c:106]             Using polling engine: epoll
```

Can these logging statements be directed somewhere other than stdout?

**Comment by thinkerou** [comment]
Fixed #7438 , so you should re-build grpc c core.

**Comment by murgatroid99** [comment]
That change thinkerou linked will be in versions 1.0.0.pre2 and 1.0.0 when they are published (which should be soon).

**Comment by blowmage** [comment]
Great! Looking forward to it!
