### ISSUE TITLE
NPM GRPC 1.0.0-pre is marked as 'latest'

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#7621]
https://www.npmjs.com/package/grpc has 1.0.0-pre as 'latest'. is this intentional? means that when you `npm install grpc`, you get this by default.

**Comment by murgatroid99** [comment]
It is the latest version, and apparently it is npm's default behavior to label any new package as 'latest', whether or not it is a prerelease package. I will change that.

**Comment by tejasmanohar** [comment]
indeed. "latest" is usually supposed to be used for stable packages. is 1.0.0-pre recommended for everyone right now? if not, it shouldnt' be latest.

**Comment by murgatroid99** [comment]
As I said, I changed it. "latest" now points to 0.15.0, the latest stable package

**Comment by tejasmanohar** [comment]
awesome

**Comment by tejasmanohar** [comment]
thanks
