### ISSUE TITLE
GRPC_EXECUTION_CONTEXT_SANITIZER is dead code.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#7624]
Defining GRPC_EXECUTION_CONTEXT_SANITIZER won't compile exec_ctx.c anymore, as enough changed in the closure structure that it won't compile anymore.

Suggest moving that define to CONFIG=dbg so we can make sure this code isn't left dead.

**Comment by ctiller** [comment]
I have a fix somewhere. We'd need significant work to get the code correct
under that sanitizer, and I'm not convinced it's worth a concentrated
effort just yet.
