### ISSUE TITLE
Weaken parameter type of server constructor from futures.ThreadPoolExecutor to futures.Executor

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7632]
The gRPC Python runtime shouldn't care whether or not [the object passed to it for it to use executing user code](https://github.com/grpc/grpc/blob/c41f81aeeb054ec436934c7cc1afeb1dee0a8581/src/python/grpcio/grpc/__init__.py#L1215) is backed by threads; it should only care that when it submits a `callable` and some arguments that the `callable` gets called on the arguments. A `futures.Executor` should be fine for that [so long as it isn't a `futures.ProcessPoolExecutor` (or anything else with weird restrictions like requiring picklability of what gets passed to it)](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor).

Implementing this (and it would be a specification-only change) may obviate [issue 6046](https://github.com/grpc/grpc/issues/6046).

**Comment by nathanielmanistaatgoogle** [comment]
After further investigation: the relaxation would need to be to a `futures.Executor` that calls the behaviors submitted to it on some thread other than the thread from which the behaviors were submitted. It doesn't have to be thread-per-RPC or thread-per-anything, but for the time being it can't be something that for example calls the submitted behavior in the body of its `submit` method.

Maybe that could change after a dramatic enough change to the server implementation, but that would be quite a ways out.

**Comment by nathanielmanistaatgoogle** [comment]
Punting; this would be nice to do at some point but there's no need for it to happen in `1.1.0`.

**Comment by eaglo** [comment]
Hi @nathanielmanistaatgoogle - whats the current state of this? Is it now actually possible to use a `futures.Executor` with the gRPC server?

**Comment by nathanielmanistaatgoogle** [comment]
@eaglo: Maybe. Notice that this isn't a code objective; this is a "test if our system happens to work this way and then make a decision to formally support working that way" objective. We haven't yet gone through that investigation and exercise, but that's no reason why you shouldn't do so! :-)
