### ISSUE TITLE
python helloworld example not work

### ISSUE THREAD

**Issue by allenlulu** [grpc/grpc#7635]
luke-ludeiMac:helloworld luke_lu$ python greeter_server.py 
D0804 13:59:37.396168000 140735216345088 ev_posix.c:101] Using polling engine: poll
Traceback (most recent call last):
  File "greeter_server.py", line 60, in <module>
    serve()
  File "greeter_server.py", line 49, in serve
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
TypeError: server() takes at least 2 arguments (1 given)

my python version is 2.7, and I see the gprc.server src is 
class Server(grpc.Server): 
   def __init__(self, generic_handlers, thread_pool):
any one can help me?

**Comment by kpayson64** [comment]
It looks like you have grpcio 0.15.0 installed, but the examples have been updated to the repository head.

Can you try upgrading grpcio with the pip ```--pre``` flag?

**Comment by cangus** [comment]
Had the same issue, upgraded grpcio from 0.15 to grpcio-1.0.0rc1 using:
`pip install --upgrade --pre grpcio`

Works fine.

**Comment by nathanielmanistaatgoogle** [comment]
Glad to hear it!
