### ISSUE TITLE
Improve developer docs

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#7636]
Craig will put together a spreadsheet of files and directories that need to be documented.  Myself, @dgquintas, and @sreecha will assist in writing documentation.

I will also work on putting together a high-level overview of the C-core code.

**Comment by pgrosu** [comment]
Many, many thanks guys for doing this!!!

**Comment by hsaliak** [comment]
@markdroth assigning with P3, given the age of the issue, please feel free to close if this is not something that's still on your TODOs
