### ISSUE TITLE
[objective-C] WatchOS support

### ISSUE THREAD

**Issue by SimpleApp** [grpc/grpc#7638]
gRPC podspec only mentions iOS and OSX as supported OS. Is watchOS going to be a target for this project ?

**Comment by jcanizales** [comment]
I don't see a reason why not allow it in the podspec, with the caveat that we don't have any test for watchOS, so it's up to the users to report broken things. We allow macOS under the same conditions.

**Comment by SimpleApp** [comment]
Another reason i was asking is that native socket on watchOS isn't documented as being supported or not.

**Comment by makdharma** [comment]
Use of anything but  native socket is not supported yet.

**Comment by muxi** [comment]
Had experiment support in #19787. Please file new issue if any bug is found
