### ISSUE TITLE
GRPC Python Plugin Installation?

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#7641]
Is `pip install grpcio-tools` supposed to setup GRPC Python Plugin, or are you supposed to clone this repo and run `make grpc_python_plugin`?

```
Tejass-MacBook-Pro:python-source tejas$ pip install grpcio-tools==1.0.0rc1
# ...
Successfully installed grpcio-tools-1.0.0rc1
Tejass-MacBook-Pro:python-source tejas$ grpc_python_plugin
-bash: grpc_python_plugin: command not found
```

**Comment by tejasmanohar** [comment]
Also, is the Python plugin ready for 1.0.0-pre? I don't see that in releases tab of this repo.

**Comment by pgrosu** [comment]
Hi Tejas,

You will need to first run:

 `pip install --pre grpcio` 

before you run:

`pip install --pre  grpcio-tools`

Give it a try and let me know if it worked.

Thanks,
Paul

**Comment by tejasmanohar** [comment]
```
$ pip install --pre grpcio
Requirement already satisfied (use --upgrade to upgrade): grpcio in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.10 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from protobuf>=3.0.0a3->grpcio)
$ pip install --pre grpcio-tools
Requirement already satisfied (use --upgrade to upgrade): grpcio-tools in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio-tools)
Requirement already satisfied (use --upgrade to upgrade): grpcio>=0.15.0 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio-tools)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from protobuf>=3.0.0a3->grpcio-tools)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from protobuf>=3.0.0a3->grpcio-tools)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio>=0.15.0->grpcio-tools)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages (from grpcio>=0.15.0->grpcio-tools)
$ grpc_python_plugin
-bash: grpc_python_plugin: command not found
```

@pgrosu no luck. that said, when i run `make grpc_python_plugin` in this repo, the command becomes available FYI.

**Comment by minhaz1** [comment]
@tejasmanohar grpc_python_plugin will not be installed to your path. `protoc` and and the plugin are bundled with the tools. So you can do:

``` bash
# source your env first
OUT=./generated
PROTO_PATH=.
PROTO_FILE= my_proto.proto
python -m grpc.tools.protoc --python_out=$OUT --grpc_python_out=$OUT --proto_path=$PROTO_PATH $PROTO_FILE
```

**Comment by tejasmanohar** [comment]
gotcha, and does this fully support py3 or is py2 a must?

**Comment by minhaz1** [comment]
There's no reason it shouldn't work with python3.x.

**Comment by nathanielmanistaatgoogle** [comment]
Closing as it appears that all questions asked in this issue have been answered.

**Comment by tejasmanohar** [comment]
yep! thx

**Comment by mkobit** [comment]
Reading through this, it doesn't seem like there is a way to use the `grpc_python_plugin` as a plugin to `protoc`? The Python distribution is its own fully container `protoc` + Python plugin? 

I'm trying to use the Python plugin with the [Gradle Protobuf plugin](https://github.com/google/protobuf-gradle-plugin) but not having much luck because `pip install` does not seem to create a `grpc_python_plugin` executable that I can reference. I'm still new to the Protobuf and gRPC tooling, so I am probably missing something.

**Comment by mehrdada** [comment]
The Python `grpcio-tools` package fuses and compiles `protoc` and the gRPC Python `protoc` plugin logic into a single Python extension, loadable from Python code, unlike most other language packages that ship a precompiled binary for `protoc` and `grpc_LANG_plugin` for a specific architecture.  This has some advantages, like the whole thing being installable via `pip install` even for esoteric architectures that we do not have precompiled binaries for.  We still do have the Python plugin available if you need it.  The way to get the plugin binaries for all languages is to manually checkout the gRPC source tree and run `make plugins -j12` to build them.

(I already answered this on https://github.com/google/protobuf-gradle-plugin/issues/52#issuecomment-383257169. Reposting here for future users)
