### ISSUE TITLE
php grpc ext fails to compile (php 7.0.8, ubuntu 16.04)

### ISSUE THREAD

**Issue by andboson** [grpc/grpc#7642]
>  `$
> 
>  make       
> /bin/bash /var/www/grpc/src/php/ext/grpc/libtool --mode=compile cc -Wall -Werror -std=c11 -I. -I/var/www/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/var/www/grpc/src/php/ext/grpc/include -I/var/www/grpc/src/php/ext/grpc/main -I/var/www/grpc/src/php/ext/grpc -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /var/www/grpc/src/php/ext/grpc/call.c -o call.lo 
> libtool: compile:  cc -Wall -Werror -std=c11 -I. -I/var/www/grpc/src/php/ext/grpc -DPHP_ATOM_INC -I/var/www/grpc/src/php/ext/grpc/include -I/var/www/grpc/src/php/ext/grpc/main -I/var/www/grpc/src/php/ext/grpc -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /var/www/grpc/src/php/ext/grpc/call.c  -fPIC -DPIC -o .libs/call.o
> /var/www/grpc/src/php/ext/grpc/call.c: In function ‘grpc_parse_metadata_array’:
> cc1: error: function may return address of local variable [-Werror=return-local-addr]
> In file included from /var/www/grpc/src/php/ext/grpc/php_grpc.h:60:0,
>                  from /var/www/grpc/src/php/ext/grpc/call.h:44,
>                  from /var/www/grpc/src/php/ext/grpc/call.c:34:
> /var/www/grpc/src/php/ext/grpc/php7_wrapper.h:146:8: note: declared here
>    zval _stack_zval_##pzv; \
>         ^
> /var/www/grpc/src/php/ext/grpc/call.c:89:3: note: in expansion of macro ‘PHP_GRPC_MAKE_STD_ZVAL’
>    PHP_GRPC_MAKE_STD_ZVAL(array);
>    ^
> cc1: error: function may return address of local variable [-Werror=return-local-addr]
> /var/www/grpc/src/php/ext/grpc/php7_wrapper.h:146:8: note: declared here
>    zval _stack_zval_##pzv; \
>         ^
> /var/www/grpc/src/php/ext/grpc/call.c:89:3: note: in expansion of macro ‘PHP_GRPC_MAKE_STD_ZVAL’
>    PHP_GRPC_MAKE_STD_ZVAL(array);
>    ^
> /var/www/grpc/src/php/ext/grpc/call.c: In function ‘grpc_php_wrap_call’:
> /var/www/grpc/src/php/ext/grpc/call.c:190:10: error: function returns address of local variable [-Werror=return-local-addr]
>    return call_object;
>           ^
> In file included from /var/www/grpc/src/php/ext/grpc/php_grpc.h:60:0,
>                  from /var/www/grpc/src/php/ext/grpc/call.h:44,
>                  from /var/www/grpc/src/php/ext/grpc/call.c:34:
> /var/www/grpc/src/php/ext/grpc/php7_wrapper.h:146:8: note: declared here
>    zval _stack_zval_##pzv; \
>         ^
> /var/www/grpc/src/php/ext/grpc/call.c:185:3: note: in expansion of macro ‘PHP_GRPC_MAKE_STD_ZVAL’
>    PHP_GRPC_MAKE_STD_ZVAL(call_object);
>    ^
> cc1: all warnings being treated as errors
> Makefile:196: recipe for target 'call.lo' failed
> make: *** [call.lo] Error 1
> 
> `

I tried `v1.0.x`, same result

**Comment by thinkerou** [comment]
The reasons have two points:

1. gcc have warning about `function returns address of local variable` on ubuntu

2. warning is treated as error

So, I will attempt to fix with `void grpc_php_wrap_call(..., zval*)` replace `zval* grpc_php_wrap_call(...)`.

**Comment by andboson** [comment]
> /* Wraps a grpc_call struct in a PHP object. Owned indicates whether the
>    struct should be destroyed at the end of the object's lifecycle */
> zval *grpc_php_wrap_call(grpc_call *wrapped, bool owned TSRMLS_DC) {
>   zval *call_object;
>   PHP_GRPC_MAKE_STD_ZVAL(call_object);
>   object_init_ex(call_object, grpc_ce_call);
>   wrapped_grpc_call *call = Z_WRAPPED_GRPC_CALL_P(call_object);
>   call->wrapped = wrapped;
>   call->owned = owned;
>   return call_object;
> }
> 

it is in call.c

**Comment by stanley-cheung** [comment]
I can reproduce this in Ubuntu 16.04 with PHP 7.0.8. @thinkerou Any idea?

**Comment by pgrosu** [comment]
@stanley-cheung Can you try to force the Makefile to use g++ instead of cc by default.  I do that all the time to make it work when compiling gRPC from scratch.

**Comment by stanley-cheung** [comment]
The problem is that for PECL extension, the Makefile is generated by a `./configure` script which in turn was generated by the `config.m4` file. Unclear how we can specify (or whether we could/want to) in the `config.m4` file.

**Comment by pgrosu** [comment]
Well, you can specify it outside, to be available in the local environment.  So here is something that can be tried from the command line (the `$` just denotes the command prompt):

```Bash
$ CC=gcc ./configure
```

**Comment by thinkerou** [comment]
We try to use the command `-Wno-return-local-addr` to resolve it temporary, but the method have terrible whether? So I thank that we should rewrite the function, right?

**Comment by stanley-cheung** [comment]
Yes I think so. Even if we do -Wno-return-local-addr, I find that there will be plenty of other segfault at PHP_GRPC_MAKE_STD_ZVAL and RETURN_DESTROY_ZVAL when I run unit tests

**Comment by pgrosu** [comment]
`-Wno-return-local-addr` only blocks the warning, but the underlying logic will still occur.

**Comment by andboson** [comment]
big thanks, guys!
