### ISSUE TITLE
Update Google.Apis.Auth dependency to 1.15+

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#7649]
Google.Apis.Auth now has .NET core support, which will allow us to get rid of some TODOs in the code and make Grpc auth work when on .NET core.

**Comment by jskeet** [comment]
//cc @chrisdunelm 

Updating issue title as it should be 1.15+ :)

**Comment by jtattermusch** [comment]
@jskeet  title was updated.

**Comment by jtattermusch** [comment]
This was fixed by #7660
