### ISSUE TITLE
GRPC: Node <> Go - "context canceled"

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#7666]
```
# client is killed?
transport: http2Server.HandleStreams failed to read frame: read tcp [::1]:4000->[::1]:33176: read: connection reset by peer
accept tcp [::]:4000: use of closed network connection
# but why does it error afterwards? incomplete message maybe?
grpc: Server.processUnaryRPC failed to write status stream error: code = 1 desc = "context canceled"
grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
grpc: Server.processUnaryRPC failed to write status stream error: code = 1 desc = "context canceled"
grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
grpc: Server.processUnaryRPC failed to write status stream error: code = 1 desc = "context canceled"
grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport: write tcp [::1]:4000->[::1]:33176: use of closed network connection"
grpc: Server.processUnaryRPC failed to write status stream error: code = 1 desc = "context canceled"
# ...
```

Any idea what could cause these errors? It comes after many successful requests. Looks like these logs are from the Go GRPC server. We have a Node GRPC client. I saw a similar thing here- https://github.com/coreos/etcd/issues/5213, but it doesn't look like they ever came to a clear resolution.

We're seeing Docker agent kill our Node client process for OOM'ing right before this error comes about if that helps; Could these logged errors be due to an unexpected exit?

PS: We weren't seeing the OOMs when using JSON over WebSockets before but are seeing them with GRPC- could be request flush / buffer rate though that's a tough one to debug since there are a number of factors. This happens on GRPC both 1.x.x and 2.x.x. We have other clients written in Node to the same GRPC server (well, another instance of it but same code) that are not facing this issue.

**Comment by tejasmanohar** [comment]
I also don't see a way to close the GRPC connection from the Node client, which is concerning.

**Comment by blerest** [comment]
> I also don't see a way to close the GRPC connection from the Node client.

+1

`.end()` doesn't seem to work because the client throw some errors after that like:
```

error: GRPC error Error: {"created":"@1471447726.110497709","description":"Secure read failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1471447726.110413414","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235}]}
    at ClientDuplexStream._emitStatusIfDone (/root/asr.rogervoice.com/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._receiveStatus (/root/XXX/node_modules/grpc/src/node/src/client.js:169:8)
    at /root/XXX/node_modules/grpc/src/node/src/client.js:634:14
```

`.close()` throw an error just after the call:

```
error: GRPC error Error: Cancelled
    at ClientDuplexStream._emitStatusIfDone (/root/XXX/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._receiveStatus (/root/XXX/node_modules/grpc/src/node/src/client.js:169:8)
    at /root/XXX/node_modules/grpc/src/node/src/client.js:634:14
```

**Comment by murgatroid99** [comment]
To disconnect a client connection, you can call `grpc.getClientChannel(client).close()`.

@tejasmanohar What is different about the Node client that is going OOM vs the other ones that aren't? Also, what do you mean by "GRPC both 1.x.x and 2.x.x"? We haven't even published grpc 1.0.0 yet. For the errors in the Go server, I would recommend asking in the gRPC Go repository: https://github.com/grpc/grpc-go.

@blerest What objects are you calling those methods on? The first one looks like you just dropped the connection or something, and the second one should only be caused by an actual explicit cancellation from the client.

**Comment by tejasmanohar** [comment]
I meant GRPC 0.x.x and 1.0-pre. Also, I'm not sure about why the Node
client is OOMing and thus opened an issue.

**Comment by murgatroid99** [comment]
We need more information to determine why the Node client is running out of memory. Do you have a reproduction case that causes this?

**Comment by tejasmanohar** [comment]
Not at the moment, sorry :( - Service is not in-use.
