### ISSUE TITLE
Add a test verifying that no grpc_error instances are created during a typical request

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#7687]
Use the same approach as in #246.

**Comment by ctiller** [comment]
(will likely need a hook in the grpc_error module to verify this).

**Comment by y-zeng** [comment]
@ctiller There are some grpc_error instances that are created but might not be used, like
 https://github.com/grpc/grpc/blob/master/src/core/lib/surface/server.c#L1243
and
https://github.com/grpc/grpc/blob/master/src/core/ext/client_config/client_channel.c#L187

Should we prevent using grpc_error instances in such ways?

**Comment by ncteisen** [comment]
This one is not a bad idea.... I am going to stop my issue closing rampage and do this one
