### ISSUE TITLE
generating protos for c# through IDE project builds.

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#7693]
We might be able to simlify the way that CSharp protos code is generated, (e.g., build solution in Visual Studio might be able to find protos files and regenerate code from them.

cc @nathanielmanistaatgoogle

**Comment by jtattermusch** [comment]
some work towards this is being worked on in https://github.com/grpc/grpc/pull/13207

**Comment by jtattermusch** [comment]
We currently have #13207 which might or might not land, but besides it we don't have any plans to look into this. Closing.
