### ISSUE TITLE
How to make gRPC being adapt to use the other protocol stack ?

### ISSUE THREAD

**Issue by gclouding** [grpc/grpc#7695]
Now, gRPC is based on TCP/IP stack in transport layer, right? How could we make it adapt to use other protocol stack, such as mTCP (http://shader.kaist.edu/mtcp/) which looks better than TCP/IP?

**Comment by srini100** [comment]
gRPC already works on other transports like in-process transport. Adopting to a new transport requires good understand of gRPC transport layer abstraction. It is doable if someone is willing to put the effort.
