### ISSUE TITLE
HalfDuplexCall exists in the interop test service but isn't used in interop tests (right?)

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7701]
Is it just leftover cruft from earlier drafts of the interop tests? Are it and its unexecuted implementations just dead code?

**Comment by adelez** [comment]
A test is implemented in C++, but not executed and not implemented in other languages. I'll enable it for C++.

**Comment by ejona86** [comment]
What is the test name, as [defined in the descriptions](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md)?

**Comment by adelez** [comment]
In C++ it's just called 'half_duplex', https://github.com/grpc/grpc/blob/5253c8f9a899450397a5e46e4923d01ac9a66a27/test/cpp/interop/client.cc#L55. It needs to be defined in the descriptions. @yang-g

**Comment by ejona86** [comment]
> It needs to be defined in the descriptions.

Why?

It seems like the answer to "Is it just leftover cruft from earlier drafts of the interop tests?" is simply, "yes."

Based on the title of this issue, it seems @nathanielmanistaatgoogle was not talking about a particular interop test (it seems he didn't know of a test), but instead talking about the [HalfDuplexCall service method](https://github.com/grpc/grpc/blob/7897ae9/src/proto/grpc/testing/test.proto#L60). And yes, that method is left over from the days before the interop tests were defined.

**Comment by srini100** [comment]
Closing this. If the test needs to be implemented in all langs lets open a separate issue.
