### ISSUE TITLE
grpc-node doesn't surface error from bidirectional stream.

### ISSUE THREAD

**Issue by mikelehen** [grpc/grpc#7705]
My code is set up as follows below and after sending a bad request on a bidi stream, the stream ends, but I'm not notified of the error in any way (there's no 'error' or 'status' event; just an 'end' event).  If you need more details, please contact me directly (mikelehen@google.com).

```
var grpc = require('grpc');

var proto = grpc.load({root:"...", file: "..."})

var service = new proto.blah.Service('localhost:8080', grpc.credentials.createInsecure());
var stream = service['streamingAPI']();

stream.on('error', (error) => {
    console.log('ERROR:', error);
});

stream.on('status', (status) => {
    console.log('STATUS:', status);
});

stream.on('end', () => {
    console.log('ENDED!');
});

stream.on('data', (data) => {
    console.log('DATA:', data);
});

var BAD_REQUEST = { ... };
stream.write(BAD_REQUEST);
```

**Comment by murgatroid99** [comment]
Some relevant parts of the trace (omitting potentially sensitive details):

```
I0810 16:55:57.951353128   10462 call.c:1690]                grpc_call_start_batch(call=0x1b483b0, ops=0x1b490a0, nops=1, tag=0x1b5ba60, reserved=(nil))
I0810 16:55:57.951373206   10462 call.c:1366]                ops[0]: RECV_STATUS_ON_CLIENT metadata=0x1b5dca8 status=0x1b5dcc0 details=0x1b5dcc8
...
I0810 16:55:57.977201666   10462 call.c:1690]                grpc_call_start_batch(call=0x1b483b0, ops=0x1b5ba90, nops=1, tag=0x1b7c5b0, reserved=(nil))
I0810 16:55:57.977214537   10462 call.c:1366]                ops[0]: RECV_MESSAGE ptr=0x1b5bb18
...
I0810 16:55:57.980176907   10470 parsing.c:723]              HTTP:1:TRL:CLI: grpc-status: [redacted]
I0810 16:55:57.980185245   10470 parsing.c:723]              HTTP:1:TRL:CLI: grpc-message: [redacted]
I0810 16:55:57.980205481   10470 completion_queue.c:252]     grpc_cq_end_op(exec_ctx=0x7fa9d640de10, cc=0x1b4a390, tag=0x1b7c5b0, error=null, done=0x7fa9d7c595e0, done_arg=0x1b48418, storage=0x1b48420)
I0810 16:55:57.980214680   10470 completion_queue.c:394]     RETURN_EVENT[0x1b4a390]: OP_COMPLETE: tag:0x1b7c5b0 OK
```

**Comment by murgatroid99** [comment]
When you're done writing, you have to say so with `stream.end()`.

**Comment by mikelehen** [comment]
Hrm.  FWIW, I did not have to (or want to) call stream.end() in my repro (I would have ideally kept sending more requests to the stream had there not been an error).

**Comment by murgatroid99** [comment]
I'm not sure what you mean. You have to call `stream.end()` when you're done writing in general. That is not the only thing that will cause a status to be surfaced, but it guarantees that the call will complete.

**Comment by mikelehen** [comment]
I don't understand.  Isn't the point of a bidi stream that you can keep sending data back/forth without ending the stream?

**Comment by murgatroid99** [comment]
When I said "when you're done writing", I mean for the stream as a whole. The problem in the reproduction case happens because you don't write any more messages *and* you don't call `stream.end()`. If this is happening, for example, because you're waiting for further reads to do more writes, then you probably want to either write something else or end the stream when you get the `end` event.

**Comment by mikelehen** [comment]
Oh, wow.  Interesting.  Sure enough, if I call stream.end() in response to the 'end' event, then I get 'finish', 'status', and 'error' events, in that order.

Is this expected / correct behavior?  I am surprised that you're supposed to call stream.end() in response to an 'end' event.  Surely it is already "ended" at that point?  And in general, I'm not sure why errors would not just be surfaced immediately upon being received...

**Comment by murgatroid99** [comment]
The 'end' event means "There are no more messages to *read*". The `stream.end()` function call means "I have no more messages to *write*". In a bidi call, those conditions are independent. The 'finish' event is just a listener for `stream.end()`.

As for errors not being surfaced immediately, I think that's kind of an optimization. We intentionally don't provide a lot of guarantees about errors because they're supposed to be unusual, and they interrupt the normal flow of a call.

It's possible that that will change, but in any case, I think that for any bidi call you can make, you should be able to find some scenario or event where you know that you will not send any more messages, and at that point, you should call `stream.end()`.

**Comment by mikelehen** [comment]
Hrm.  That's definitely not the case for us.  We leave the stream open indefinitely but need errors as soon as they happen.

**Comment by mikelehen** [comment]
Can we get this scheduled to a milestone?  we have some pretty hacky code to work around it.

**Comment by paralin** [comment]
@mikelehen How did you work around it? I'm facing this now with http://github.com/paralin/grpc-bus

**Comment by paralin** [comment]
Also, is there any kind of documentation on these events? ...

**Comment by mikelehen** [comment]
My workaround is to make sure that I call stream.end() if I receive an 'end' event on the stream, and then when I get the subsequent 'finish' event, I wait an additional 2 seconds before completely cleaning up, because I may finally get an 'error' event for the error during that time period.  It's a big hack. :-(

**Comment by murgatroid99** [comment]
Someone had a similar problem in #8134, and the solution is to basically do this:

```js
stream.on('end', function() {
  stream.end()
});
stream.on('status', function(status) {
  if (status.code != grpc.status.OK) {
    // Do error handling
  }
  // Do cleanup
});
stream.on('error', function() {});
```

In addition, I may have been wrong about when errors are surfaced, and it may actually be a bug that you need the `end` handler at all.

**Comment by paralin** [comment]
This is some seriously clunky stuff.

**Comment by murgatroid99** [comment]
The `end` event has existing meaning in Node streams, and we're not going to change that. But I think I can make the `status` event always be last, to serve basically the same purpose.
