### ISSUE TITLE
google/protobuf/empty is unusable in php

### ISSUE THREAD

**Issue by ckurz-va** [grpc/grpc#7708]
Compiling a proto that uses `import "google/protobuf/empty.proto";` when compiled for php5.5, creates unusable classes. Due to Empty being a reserved keyword in php, it has issues trying to reference the Empty class. 

We have done a workaround, by renaming the class, and that seems to give the behaviour expected. 

Error we saw was
`PHP Parse error:  syntax error, unexpected 'Empty' (T_EMPTY), expecting identifier (T_STRING) in /datariver/empty.php on line 8`

Workaround is to modify the generated php code for empty, to change the classname, but leave the descriptor to google.protobuf.Empty, then adjusting our php generated from our proto to reference the new class (`\google\protobuf\RealEmpty`)

**Comment by stanley-cheung** [comment]
Yes that is a known issue. I myself have been doing that workaround in the [PHP Pubsub example](https://github.com/stanley-cheung/grpc-php-pubsub/blob/master/empty.php)

**Comment by stanley-cheung** [comment]
I have talked with the protobuf team. They will make a special case for this in the upcoming proto3 support for PHP.
