### ISSUE TITLE
Expose client authentication details to server-side application?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7710]
[A user writes](https://groups.google.com/d/msg/grpc-io/By4dwnaGAws/jgQF5YZ6BQAJ):

_Consider a simple RPC setup protected with http/2, such as https://github.com/jayeye/grpc/tree/ji/secure-hello/examples/python/helloworld_

_The server will know that the client was properly authenticated, but if it wants to know which of its zillion clients it was, how does it access the contents of the cert that was used by the client? I would have assumed_ **`context.auth_context()`** _would be the answer, but there is no such method for context._

This seems currently to be only supported in C++ - is server-side application visibility of these client details something we want to support in Python?

**Comment by hstefan** [comment]
I came across this issue after attempting to implement something very similar to the example given by @nathanielmanistaatgoogle. For our service it would be convenient and sufficent to map TLS certificates to client-specific data, and I believe that may be useful for other B2B applications where the deployment is controlled.

Are there any updates on whether it would be interesting to support this or not? If there's interest, I'm willing to try to implement it and submit a PR.

**Comment by hstefan** [comment]
I wrote a python version of the AuthContext and other helper classes and I want to submit a patch, but I'm unsure about how to about writing testings for it. Any suggestions on where these _Context related tests should be kept, or perhaps any example of a relevant testing approach?

**Comment by nathanielmanistaatgoogle** [comment]
@hstefan: are you able to run the existing tests as part of your development process? If so, what about your patch doesn't fit into those tests? (Feel free to open a pull request.)

**Comment by hstefan** [comment]
@nathanielmanistaatgoogle yes, I'm still able to run the existing tests. However, they currently don't cover the methods and classes introduced by my changes, and I'm unsure about how to implement that in a way that resonates well with the rest of the test suite.

I'll make a PR soon, which I think will help with the discussion on what kind of coverability is necessary.

**Comment by jboeuf** [comment]
Thanks for the help on this @hstefan!
@jtattermusch, @nathanielmanistaatgoogle and I should probably be on the list of reviewers for your PR.

**Comment by hstefan** [comment]
Ok, the checks seem to be alright now. I didn't find a way to neither label the PR nor assign the reviewers, am I failing at GitHubing or do I need permissions for that?

I've kept #10677 as WIP because I'm unsure about the testing part, so I'd really like a few comments about that if possible.

**Comment by kpayson64** [comment]
@hstefan 
Looks like we had similar ideas:
https://github.com/grpc/grpc/pull/10993

Feel free to use the test there as an example of how we can test.  I'll let you finish the feature, unless you would prefer that I did it.

**Comment by hstefan** [comment]
@kpayson64 Thanks for reaching out, I'm having a look right now at how you implemented your tests and see if I can apply it on my own branch.

Our implementation seems pretty similar, so I'll try to address  any equivalent issue pointed out by @nathanielmanistaatgoogle on your PR.

**Comment by hstefan** [comment]
I read through @kpayson64 PR and it seems to resonate better with the codebase. Anything I'd write with that knowledge would now be very similar, so honestly I believe it would be best I we just reused his commit and I could help addressing the issues pointed out on the PR.

Does that make sense to you?

**Comment by kpayson64** [comment]
@hstefan 
If you are happy with my implementation, it might be easier for me to finish the PR.  Does that work?

**Comment by hstefan** [comment]
@kpayson64 I think so. Feel free to reuse this patch if you desire, it should apply cleanly on your branch.

[0001-Fixing-issues-in-python-s-auth-context-tests.txt](https://github.com/grpc/grpc/files/986572/0001-Fixing-issues-in-python-s-auth-context-tests.txt)
