### ISSUE TITLE
Expected SETTINGS frame as the first frame, got frame type 80

### ISSUE THREAD

**Issue by zenbuilder** [grpc/grpc#7726]
Expected SETTINGS frame as the first frame. Full error:

E0813 21:58:50.338374 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\ext\transport\chttp2\transport\chttp2_transport.c:1810: close_transport: {"created":"@1471139930.336000000","description":"Failed parsing HTTP/2","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\ext\transport\chttp2\transport\chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1471139930.336000000","description":"Expected SETTINGS frame as the first frame, got frame type 80","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\ext\transport\chttp2\transport\parsing.c","file_line":477}]}
Status(StatusCode=Unavailable, Detail="")

**Comment by ctiller** [comment]
How does this come about?

**Comment by zenbuilder** [comment]
After more research on this, it is caused by a NullReferenceException when the response is returned to the client.  I now believe it is a bug in the server side code (therefore not your bug) where they are not sending a HTTP/2 SETTINGS frame in the response, which is making Google.Protobuf.dll choke. I believe it’s throwing the error back to gRPC and that’s where the error then bubbles up to my client.

 

I turned on “break on all exceptions” and isolated it to this error:

 

System.ArgumentNullException occurred

Message: Exception thrown: 'System.ArgumentNullException' in Google.Protobuf.dll

Additional information: Value cannot be null.

 

I apologize for the trouble… I’m working to integrate PB’s for our company with a new partner that requires them. (http://www.index.com <http://www.index.com/> )  

They are in the process of migrating from Proto v2 to Proto v3 and I think their server code is missing this detail. 

 

Thanks much for the quick response, I think you have a great thing going!

 

Brian Manlove

Dumac Business Systems

http://www.dumac.com <http://www.dumac.com/>

**Comment by zhanif3** [comment]
Getting same error message when attempting to place a GRPC server behind an AWS Application Load Balancer.

**Comment by tejasmanohar** [comment]
I actually get the same error locally on OS X when running Node client against Go server. It's weird because I don't have any sort of proxy. I can see how it'd happen on AWS ALB though.

**Comment by yashykt** [comment]
looks like this was fixed.
