### ISSUE TITLE
NodeJS map is an object

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#7731]
Hello,

when receiving a map<string,string> field the value is an Object. If I convert a map back and forth with protobufs I get a custom protobufjs [Map](https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Map.js) object. Is this something I can control or where can I find the implementation for this?

**Comment by murgatroid99** [comment]
Can you be more specific about how you "convert a map back and forth with protobufs"? Are you describing a gRPC operation or a Protobuf.js operation?
