### ISSUE TITLE
grpc++_unsecure target depends on both grpc and grpc_unsecure

### ISSUE THREAD

**Issue by xyzzyz** [grpc/grpc#7739]
See https://github.com/grpc/grpc/blob/master/BUILD#L1627-L1628 . I'm not sure why it doesn't lead to compilation errors with Bazel (maybe it does), but when I try to generate GN build files for gRPC, it properly separates grpc and grpc_unsecure targets, so that linker fails because it finds multiple definitions of symbols. 

This was introduced in this change: https://github.com/grpc/grpc/commit/f0ec5b673cc525502bec1c945d514b7f021d799c

**Comment by y-zeng** [comment]
It should be fixed in #7752

**Comment by xyzzyz** [comment]
Great! Thanks.

**Comment by mehrdada** [comment]
Looks like this issue has been resolved. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
