### ISSUE TITLE
ServerBuilder::BuildAndStart not work as expected in docker

### ISSUE THREAD

**Issue by YueHonghui** [grpc/grpc#7747]
language: c++
env: linux amd64, docker
We use grpc++ in docker and found that grpc creating more than 24 threads in a 24 cores machine even though the container limited to use 8 cores using cpuset. After reading the code, I found that `CreateDefaultThreadPool` in `ServerBuilder::BuildAndStart` use `sysconf(_SC_NPROCESSORS_ONLN)` to get num of cpus available. But _SC_NPROCESSORS_ONLN not work as expected in docker according to google search.

We need to limit the num of threads correctly. What about to change `ServerBuilder::BuildAndStart()` to `ServerBuilder::BuildAndStart(ThreadPoolInterface* pool)` to support customized thread pool?

**Comment by vjpai** [comment]
Hello there,
Sorry for the delayed response. Indeed, it does seem to be the case that docker is not currently handling that sysconf call as we expect, according to docker/docker#20770 , and there does not seem to be a resolution at hand.

Note that you can customize the thread pool if you want. ThreadPoolInterface is an abstract class that is defined in [src/cpp/server/thread_pool_interface.h](https://github.com/grpc/grpc/blob/master/src/cpp/server/thread_pool_interface.h) and only has to support 1 method. We currently don't support overriding the thread-pool in server builder but could consider adding that feature. (I think we used to have it at one point but it was never used so we removed it.) I will investigate.

**Comment by vjpai** [comment]
I should add @sreecha to this discussion before going any further on it.

**Comment by sreecha** [comment]
Thanks for CC'ing me @vjpai. 

I am working on somewhat a major change to our sync server and would be removing the "threadpool" from the sync-server. 

Instead, each server can have a configurable number of completion queues (which is set to the number of CPUs by default) and each completion queue will have a configurable number of polling threads (both minimum and maximum per completion queue which would be set to 1 and infinity respectively).

In your case you would then be setting the number of completion queues via server builder .

I am planning to have this change merged in the next one month or so..

**Comment by yang-g** [comment]
Sree's change has been in for a long time. Assume this is not an issue any more.
