### ISSUE TITLE
Change beta to 1.0 in readme doc

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc#7750]
Change API reference to all languages to 1.0 in readme.doc

**Comment by hsaliak** [comment]
Please send this against the 1.0 branch

**Comment by dgquintas** [comment]
Is this referring to the `git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc` line? If so, all we need to do is to merge the GA branch into master in the grpc.io repo.

**Comment by hsaliak** [comment]
This references the table that talks about the status of the gRPC API as well.
https://github.com/grpc/grpc/#repository-structure--status

**Comment by nicolasnoble** [comment]
More specifically:
https://github.com/grpc/grpc/tree/v1.0.x#repository-structure--status
