### ISSUE TITLE
Error output when client terminates

### ISSUE THREAD

**Issue by Rittel** [grpc/grpc#7761]
I have a python server and client.

When my python grpc client terminates sucessfully i get the following output in the console.

In the client console:
`E0817 10:19:06.363000000  6492 chttp2_transport.c:1810] close_transport: {"created":"@1471421946.363000000","description":"End of TCP stream","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\python\platform\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":179}`

In the server console:
`E0817 10:19:06.353000000  6644 chttp2_transport.c:1810] close_transport: {"created":"@1471421946.353000000","description":"Failed parsing HTTP/2","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\python\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1471421946.353000000","description":"End of TCP stream","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\python\platform\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":179}]}`

The error does not cause the server to close and i can run a new client without restarting the server.

**Comment by nathanielmanistaatgoogle** [comment]
With what version of gRPC Python are you working?

**Comment by Rittel** [comment]
My current version is 0.15.0

**Comment by Rittel** [comment]
Upgraded to the prerelease 1.0.0rc2 and it seems to have stopped outputting the error

**Comment by nathanielmanistaatgoogle** [comment]
Glad to hear it and please let us know if you see any other unexpected output in 1.0.0rc2 or later.

**Comment by Rittel** [comment]
Will do!
