### ISSUE TITLE
grift (thrift marshalling over grpc) is experimental

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#7770]
Tracking issue for tasks necessary before considering grift (thrift marshalling over grpc) API stable.
- [ ] hear about some usage, to make sure it is satisfactory to users familiar with thrift marshalling
- [ ]  codegen'd method signatures should have multiple arguments instead of the single wrapping message (this is probably cross-language)
- [ ] Make installation process as seamless as possible
- [ ] Code generation for Async Unary messages
- [ ] Upstream codegen to Apache Thrift project

This is a superset of grpc/grpc-java#2170

**Comment by vjpai** [comment]
Cc @chedeti

**Comment by chedeti** [comment]
- [ ]  generate code to send Async Unary Messages

- [ ]  Streaming Thrift messages over gRPC

**Comment by vjpai** [comment]
Let's not include streaming thrift as a checklist item for calling this stable. IMO, that's another wishlist experimental feature since it doesn't exist upstream even otherwise. We can stick to the stability features only for now.

**Comment by vjpai** [comment]
Now that we have time to think about packaging, I'm beginning to think that @chedeti was right all along - rather than the patch, we should use our own fork of thrift and do the changes there. Something like grpc/grift . That would be the home of all the compiler changes. We can pull down changes from Apache Thrift on an as-needed basis. I think this merits discussion before deciding, but it seems to me like a cleaner solution until we can get everything purely upstreamed.

**Comment by chedeti** [comment]
we need only thrift compiler. I think the better way is to separate thrift compiler and rename it as grift and build whatever required on top of it. This will help us not to depend on thrift for compiler changes and also we can add our own features for grift.

**Comment by vjpai** [comment]
Cc @nicolasnoble @a11r

**Comment by vjpai** [comment]
Cc: @hsaliak @zinuga @ejona86

**Comment by vjpai** [comment]
Cc: @louiscryan

**Comment by vjpai** [comment]
This issue is now moved to grpc-ecosystem/grift#6 . Closing it from main repo.
