### ISSUE TITLE
Symbol not found on ruby 2.1

### ISSUE THREAD

**Issue by Draiken** [grpc/grpc#7792]
Ruby version: ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
OS: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
grpc version: 1.0.0.pre-1
gcloud version: 0.12.2
How the error happens:
```
Gcloud.new.pubsub
```
This is the stacktrace:
```
LoadError: Error relocating /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/grpc_c.so: __strcat_chk: symbol not found - /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/grpc_c.so
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/grpc.rb:33:in `require_relative'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/grpc.rb:33:in `rescue in <top (required)>'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/grpc.rb:30:in `<top (required)>'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/errors.rb:30:in `require_relative'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/errors.rb:30:in `<top (required)>'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc.rb:32:in `require_relative'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc.rb:32:in `<top (required)>'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/gcloud-0.12.2/lib/google/pubsub/v1/pubsub_services.rb:4:in `<top (required)>'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
... 11 levels...
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /replaypoker/vendor/bundle/ruby/2.1.0/gems/gcloud-0.12.2/lib/gcloud.rb:202:in `pubsub'
```

We've been testing the gem locally on ubuntu dev machines and they worked fine. Now we're deploying to production and this happened

The gem installs fine, the error only happens at runtime, which makes it hard to understand what's missing from us.

Edit: Fixed how the error showed up

**Comment by nicolasnoble** [comment]
I have never seen that one before. Care to share details about your
production environment? Distribution versions, etc.

**Comment by nicolasnoble** [comment]
Digging a bit, this missing symbol seems pretty common in any glibc. From the kernel version you're giving us, it seems you're on Debian jessie, and we're properly loading the extension under that platform: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/1504/architecture=x64,language=ruby,platform=linux/console

```
PASSED: distribtest.ruby_linux_x64_jessie [time=16.9sec; retries=0:0]
```

The corresponding Dockerfile for this test is this:

https://github.com/grpc/grpc/blob/master/tools/dockerfile/distribtest/ruby_jessie_x64/Dockerfile

Inside that Dockerfile, we try running this Ruby file for exercising the loading of the library, which is what's currently failing for you:

https://github.com/grpc/grpc/blob/master/test/distrib/ruby/distribtest.rb

It'd really help at that point if you could describe your production environment a bit more, if it's a modified Debian, which version, etc.

**Comment by Draiken** [comment]
It's mostly pretty standard stuff:

- Dockerized rails application
- Using ruby's official image for `2.1.10`. Tested on version `2.2` and `2.3` but all gave errors.
- We basically take the ruby image, add our `Gemfile` and `Gemfile.lock`, run `bundle install` and then put the application on top of a webserver. The base ruby image is absurdly big, they include a TON of packages just for convenience, which is why I'm really not sure how there can be any library missing here.
- We're hitting this error using the rails console, so it shouldn't be specific to any app server.

**Comment by Draiken** [comment]
Also, the container is running on GKE. At first I thought it might be a problem of not providing the keyfile or something like that, but I ensured we had valid project ids, credentials and it still didn't work

**Comment by Draiken** [comment]
I added a simple reproducible test here: https://github.com/Draiken/grpc-7792-error-test

Please tell me if I can do anything else to help. This is currently blocking us from moving to PubSub and honestly, it's a bit worrying for us as the first experience with it.

We had an alpine linux based build and got a similar error on alpine (might have been the same, but we didn't look enough). We immediately assumed it was alpine's fault because of musl and moved back to the official ruby image, to then hit another similar error.

**Comment by Draiken** [comment]
Tested with `gcloud` version `0.11` (that uses `grpc 0.13.1` too, same error:
```
ruby: symbol lookup error: /usr/local/bundle/gems/grpc-0.13.1-x86_64-linux/src/ruby/lib/grpc/grpc_c.so: undefined symbol: rb_id2sym
```

**Comment by apolcyn** [comment]
I tried this and did get the same error rb_id2sym. Just for a test, the linking seems to work when using ruby versions 2.2.5 or 2.3.1 in the Dockerfile

**Comment by Draiken** [comment]
@apolcyn true... first two lines I don't understand, but the rest look fine

This was running ruby 2.2.5
```
I0819 20:06:21.900879386       7 ev_epoll_linux.c:84]        epoll engine will be using signal: 36
D0819 20:06:21.900908821       7 ev_posix.c:106]             Using polling engine: epoll
/usr/local/bundle/gems/googleauth-0.5.1/lib/googleauth.rb:119:in `get_application_default': Could not load the default credentials. Browse to (RuntimeError)
https://developers.google.com/accounts/docs/application-default-credentials
for more information
	from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/credentials.rb:83:in `default'
	from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/pubsub.rb:62:in `pubsub'
	from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud.rb:203:in `pubsub'
	from test.rb:3:in `<main>'
```

**Comment by nicolasnoble** [comment]
Alright, so let's break that down a bit.

There's currently a problem in the loading code which seems to be kind of a widespread problem to people who just copy/pasted that loading code without trying to verify it. Meaning that the current precompiled gRPC Ruby gem won't load properly in 2.1.10. https://github.com/grpc/grpc/pull/7796 is fixing this. We'll publish this for 1.0.1 a bit later.

If you try using another version of Ruby, this should work.

The latest 2.2.5 error you're showing isn't related to grpc. You're missing the default gcloud credentials.

**Comment by nicolasnoble** [comment]
#7800 should fix the rootcause of that.
