### ISSUE TITLE
Secure read failed

### ISSUE THREAD

**Issue by blerest** [grpc/grpc#7804]
Hi,

Using GRPC (v1.0.0) with Node.JS (v4.4.7) on Debian (v8.5), this error is throw a lot of time (we are using GRPC with Google Speech API):

```
{
    "message": "GRPC error",
    "stack":
        "Error: {
            "created":"@1471638519.122408754",
            "description":"Secure read failed",
            "file": "../src/core/lib/security/transport/secure_endpoint.c",
            "file_line": 157,
            "grpc_status": 14,
            "referenced_errors": [
                {
                    "created": "@1471638519.122285940",
                    "description": "EOF",
                    "file": "../src/core/lib/iomgr/tcp_posix.c",
                    "file_line":235
                }
            ]
        }
    at ClientDuplexStream._emitStatusIfDone (/root/XXX/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._receiveStatus (/root/XXX/node_modules/grpc/src/node/src/client.js:169:8)
    at /root/XXX/node_modules/grpc/src/node/src/client.js:634:14", "code": 14, "metadata": {
        "_internal_repr":{}
    }, "level": "error", "timestamp": "2016-08-19T20:28:39.125Z"
}
```

**Comment by murgatroid99** [comment]
The gRPC error code in that error is 14, which means "Unavailable". This is a response from the server indicating that the service was unavailable when you made the request, and that you should wait a little and then try again.

**Comment by ariolaclint** [comment]
Please help us to resolve this error in Bluemix.Thank you....
Enrolled admin user sucecssfully
Enrolled and registered test_user successfully
Deploying chaincode ...
Container became healthy
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: {"created":"@1490927907.173064824","description":"Secure read failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1490927907.173053129","description":"OS Error","errno":104,"file":"../src/core/lib/iomgr/tcp_posix.c","file_line":229,"os_error":"Connection reset by peer","syscall":"recvmsg"}]}

**Comment by balakrishnaITPC** [comment]
Even i'm facing the same error. Is this issue still open ?
