### ISSUE TITLE
_Rendezvous with no details hangs forever on access

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#7807]
To repro

``` python
>>> from grpc._channel import _Rendezvous
>>> from grpc._channel import _RPCState
>>> from grpc import StatusCode
>>> exc_state = _RPCState((), None, None, StatusCode.NOT_FOUND, None)
>>> exc = _Rendezvous(exc_state, None, None, None)
>>> exc.code()
<StatusCode.NOT_FOUND: (5, 'not found')>
>>> exc.details()
```

/cc @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
Are you able to hit this using only the public API?

Is it a problem to include a details string instead of `None` as the last argument to `_RPCState`?

**Comment by dhermes** [comment]
The point is that the access should just fail instead of hang forever. I don't know enough about your API to say, but if using the public API the following occurred

```python
try:
    foo()
except grpc.RpcError as grpc_error:
    print(grpc_error.details())
```

bad things could happen

**Comment by nathanielmanistaatgoogle** [comment]
Closing because I don't believe that there's a problem here - using only the public API, I don't believe that it's possible for `.details()` to hang _after the RPC has concluded_. As for the `_Rendezvous` class: not only is it internal but I'd also like it to be not long for this world. :-)
