### ISSUE TITLE
C++ Visual Studio projects can't link with GRPC++ code on v1.0.0 and master

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#7814]
grpc++.lib doesn't export Channel class methods.
grpc++.vcxproj compiles both cpp/client/channel.cc and core/lib/surface/channel.c, which means the .obj file compiled from channel.cc is overridden by the .obj compiled from channel.c - and the .lib exports the overridden .obj file.
The bug was added on commit a469e5d42e58032294c2c11ea72cec7a0a3718bb by @nicolasnoble and is part of the v1.0.0 tag (and the 1.0.x branch) - which means c++ projects can't be built under this tag/branch.

**Comment by amitwaisel** [comment]
This issue also affects the master branch due to commit e3e17d3f6bf3ecb402486553cd1a7f99e6c9ecc2 by @nicolasnoble.
Is there any progress with this issue?

**Comment by nicolasnoble** [comment]
#7828 fixes this.

**Comment by xyzzyz** [comment]
It is still a problem in master.
