### ISSUE TITLE
Support true C++11 on master

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#7824]
Essentially, every word in the Portability Restrictions section of https://github.com/grpc/grpc/blob/b8916aa22fe1d2c1163986b834f5bd0543476573/doc/cpp-style-guide.md should cause consternation, but these were necessary to make sure that we can support critical gRPC C++ use cases. Among those, the most problematic (IMO) are:
- All `nullptr`-related restrictions. Some very standard uses of `nullptr` fail at compile time on gcc4.4, but some fail insidiously: such as assigning static lifetime variables to `nullptr`. Additionally, it is not good coding practice to force people to implicitly typecast pointers to `bool` for comparisons rather than the more common route of explicitly comparing against `nullptr`.
- Restrictions on the use of `unique_ptr` in collections. This often forces us to do manual `new` and `delete` (and `delete []`), which is error-prone.

Additionally, several features like the lack of lambdas, range-based `for`, and brace initializers lead to code that can be overly convoluted to achieve the same objectives.

Now that users restricted to outdated compilers can be supported using the v1.0.x branch, I suggest that in the very near future, we ease off the restrictions on development at master and eventually adopt a more standard coding style at master.

If we decide that this is a go, I'll send in a PR changing the style guide, removing our ersatz `nullptr`, and removing portability checks against the oldest of compilers at master. Other stuff will fall in place after that.

Cc: @ctiller @yang-g @markdroth @y-zeng @dgquintas @sreecha @hsaliak

**Comment by markdroth** [comment]
Can we make a similar change to support true C99 for the C-core code?

**Comment by vjpai** [comment]
Mark, except for variable-sized arrays, I think we do for the source anyway (though not the headers). As for variable-sized arrays, they wouldn't fly with the Google C++ style guide because of likelihood of trashing the stack nondeterministically: https://google.github.io/styleguide/cppguide.html#Variable-Length_Arrays_and_alloca__

**Comment by markdroth** [comment]
Got it.  Thanks.
