### ISSUE TITLE
[PHP] Fatal error: Class 'Grpc\ChannelCredentials' not found

### ISSUE THREAD

**Issue by mcos** [grpc/grpc#7825]
After installing using `composer` (via `composer require grpc/grpc`), I get the following error when trying to create channel credentials:

```
Fatal error: Class 'Grpc\ChannelCredentials' not found in vendor/grpc/grpc/src/php/lib/Grpc/BaseStub.php on line 61
```

The offending line:
```php
$channel_credentials = \Grpc\ChannelCredentials::createInsecure();
```

My PHP version:

```
PHP 5.6.24 (cli) (built: Jul 22 2016 02:41:22) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

Is there any guidance for this? I also get this line after installing the `PECL` extension.

cc/ @stanley-cheung for his support on this.

**Comment by stanley-cheung** [comment]
You will need to add `extension=grpc.so` into your `php.ini` file. Or add `-d extension=grpc.so` to your command line.

**Comment by mcos** [comment]
Oh nice, that worked. Thanks very much.

Any thoughts on whether that step could be included as part of the `pecl` installation? Or adding some extra guidance when doing `composer require grpc/grpc`? It's kinda confusing to do the composer install and still be left needing to do the `pecl install grpc` step

**Comment by fr05t1k** [comment]
@mcos grpc have 2 part of library. One part it's a php extension and another path it is php library. Its work together. Composer can't install extensions in php and Pecl can't install libraries in your project. That's why you need to use pecl and composer.

**Comment by mcos** [comment]
@stanley-cheung Would it be possible for you to enable issues on https://github.com/stanley-cheung/Protobuf-PHP/?

**Comment by stanley-cheung** [comment]
Oh I wasn't aware issues weren't enabled. Just did. But please understand that the official Proto3 support from google/protobuf for PHP will be ready very soon so my Protobuf-PHP fork will be going away soon.

**Comment by mcos** [comment]
Oh Brilliant, thanks! I actually just wanted to mention a workaround I used to get proto3 timestamps working and whether it would be a good idea to PR it in to the repo?

**Comment by NicklasWallgren** [comment]
@stanley-cheung How soon?, do you have any source?

**Comment by stanley-cheung** [comment]
@TeBoring should be a better person to provide that estimate in google/protobuf#1936

**Comment by stanley-cheung** [comment]
@mcos, what's the timestamp issue?

**Comment by stanley-cheung** [comment]
Closing this issue now as it's no longer about the Fatal Error. Please raise the timestamp issue over at stanley-cheung/Protobuf-PHP. Thanks.

**Comment by mcos** [comment]
Thanks @stanley-cheung, I'll add the issue over there.

**Comment by night5talker** [comment]
@stanley-cheung I have same issue, my GRPC worked 2 days ago, after that I received update on my Ubuntu, after that always same error on same page that worked (ps on my server things are still working)

since quotes are not most frinedly here here is [stakoverflow](https://stackoverflow.com/questions/47772998/after-updating-protolib-and-protoc-grpc-doesnt-work-anymore) with more details
