### ISSUE TITLE
Compile time error referencing google::protobuf::compiler::objectivec::ProtobufLibraryFrameworkName

### ISSUE THREAD

**Issue by bdnett** [grpc/grpc#7835]
I just downloaded Release 1.0.0 and trying to build it and getting a compiler error.  I've got the protobufs binaries installed on my machine but I don't have source installed.  The compiler errors are:

[HOSTCXX] Compiling src/compiler/objective_c_plugin.cc
src/compiler/objective_c_plugin.cc:44:49: error: ‘google::protobuf::compiler::objectivec::ProtobufLibraryFrameworkName’ has not been declared
 using ::google::protobuf::compiler::objectivec::ProtobufLibraryFrameworkName;
                                                 ^
src/compiler/objective_c_plugin.cc:45:49: error: ‘google::protobuf::compiler::objectivec::IsProtobufLibraryBundledProtoFile’ has not been declared
 using ::google::protobuf::compiler::objectivec::IsProtobufLibraryBundledProtoFile;
                                                 ^
src/compiler/objective_c_plugin.cc: In member function ‘virtual bool ObjectiveCGrpcGenerator::Generate(const FileDescriptor*, const string&, grpc::protobuf::compiler::GeneratorContext*, grpc::string*) const’:
src/compiler/objective_c_plugin.cc:81:57: error: ‘IsProtobufLibraryBundledProtoFile’ was not declared in this scope
         if (IsProtobufLibraryBundledProtoFile(dependency)) {
                                                         ^
src/compiler/objective_c_plugin.cc:87:44: error: ‘ProtobufLibraryFrameworkName’ was not declared in this scope
             "  #import <" + ::grpc::string(ProtobufLibraryFrameworkName) +
                                            ^
make: *** [/home/bn/grpc/grpc/objs/opt/src/compiler/objective_c_plugin.o] Error 1

**Comment by bdnett** [comment]
Argh!  I found that I do have an older copy of google/protobufs installed on my machine in /usr/local/include.

**Comment by helloBingGeGe** [comment]
hi~ which header file should to be included to solve this problem ?
