### ISSUE TITLE
Ruby implementation is slower than casual rest json

### ISSUE THREAD

**Issue by w00lf** [grpc/grpc#7852]
Hi, I have been researching GRPC gem for the past month. I have created test stand where I tested different cases with object serialization, in short, I created simple service that returns complex object, here is my PROTO: https://github.com/w00lf/grpc/blob/master/protos/overhead.proto#L9
I have tested it with a simple setup: client requests size, server returns the array of objects of requested size and time for generating test data. Server and client use the insecure channel. All worked fine until I tried to test the same setup against REST JSON, REST implementation uses the same GRPC`s objects to pack and unpack on client and server but the difference in speed(pack on the server, transmit and unpack on the client) was more than 1.5 times in favor of REST. Is it normal behavior or am I missed some setup steps?

**Comment by apolcyn** [comment]
So you are a comparing the time for a single request and response with the same proto objects, done with grpc vs. JSON REST? 

Curious how you're benchmark test is set up. Are you making many of these calls in a row, one after the other, and measuring average latency? If so, are you using the same client stub for all of your grpc calls? 

Would you be able to share more of your benchmarking setup, e.g., platform, ruby http client and server?

By the way, there are links to grpc client and server performance benchmarks on the grpc website http://www.grpc.io/docs/guides/benchmarking.html.

**Comment by w00lf** [comment]
Thank you for your reply. 

> So you are a comparing the time for a single request and response with the same proto objects, done with grpc vs. JSON REST?

Yes, that is correct.
My test stand:

```
$: bundle show grpc
/usr/local/bundle/gems/grpc-0.15.0-x86_64-linux
$: cat Gemfile.lock:
......
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    google-protobuf (3.0.0)
    googleauth (0.5.1)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    grpc (0.15.0)
      google-protobuf (~> 3.0.0.alpha.5.0.3)
      googleauth (~> 0.5.1)
......
$: ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$:  uname -a
Linux mik-mainframe 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$: lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

> Are you making many of these calls in a row, one after the other, and measuring average latency? If so, are you using the same client stub for all of your grpc calls?

Yes, the same stub for each client call, synchronic calls, on the client i subtracted the time, needed to generate test objects, only serialization, transport and depacking are measured. By looking in the server`s logs I can tell that he uses the same connection for the duration of the test, e.g. no messages of the disconnected client.  My server code:

```
.......
 def create_object(size)
    result = nil
    time_spend = (Benchmark.measure { result = Array.new(size){ create_topic } }.real * 1000).to_i
    ::Overhead::TopicsResponse.new(time_spend: time_spend, topics: result, response_bytes: TOPIC_WEIGTH_BYTES * size)
  end

  def get_topics(size_request, _unused_call)
    create_object(size_request.size)
  end
end

s = GRPC::RpcServer.new
s.add_http2_port('0.0.0.0:50051', :this_port_is_insecure)
s.handle(OverheadRpcServer)
s.run_till_terminated
```

And the client:

```
kind = "topics_request#{suffix}"
  stub = Overhead::Collection::Stub.new('grpc:50051', :this_channel_is_insecure)
  n.times do |i|
    size = (i + 1)
    p "Starting iteration for size: #{size}"
    2.times do |j|
      message = nil
      measure = Benchmark.measure { message = stub.get_topics(::Overhead::SizeRequest.new(size: size)) }
      begin
        Log.create(created_at: Time.now.utc.iso8601, message_size: message.response_bytes, time_spend: ((measure.real * 1000) - message.time_spend).to_i, kind: kind)
      rescue
        retry
      end
    end
  end
```

For the REST JSON test i use sinatra(1.4.7). Server code:

```
class ComplexResponseSerializer < ActiveModel::Serializer
  attributes :time_spend, :response_bytes
  has_many :topics
end

class TopicSerializer < ActiveModel::Serializer
  attributes :id, :headline, :alternative_headline, :announce, :content_type, :dispatched_at, :is_visible, :partner_related, :preview_token, :published_at
  has_many :widgets
end

class WidgetSerializer < ActiveModel::Serializer
  attributes :id, :type, :data, :created_at, :updated_at, :position
end

get '/utf8' do
  content_type :json

  random_utf_string(params[:size].to_i)
end

get '/topics' do
  content_type :json
  ComplexResponseSerializer.new(create_object(params[:size].to_i)).as_json.to_json

```

"create_object" is the same for grps test and rest, here it is: https://github.com/w00lf/grpc/blob/master/lib/content_generator.rb#L10

And the REST client:

```
def rest_objects_satble_connection_test(n, suffix = '')
  kind = "rest_topics_request#{suffix}"
  n.times do |i|
    size = (i + 1)
    p "Starting iteration for size: #{size}"
    10.times do |j|
      message = nil
      measure = Benchmark.measure do
	      response = JSON.load(Net::HTTP.get(URI("http://web:50051/topics?size=#{size}&rand#{rand(1..10000)}=#{rand(1..10000)}")))
        topics = response['topics'].map do |topic|
          widget_attr = topic.delete('widgets')
          ::Overhead::Topic.new(symb_keys(topic).merge(widgets: widget_attr.map {|n| ::Overhead::Widget.new(symb_keys(n)) }))
        end
        message = ::Overhead::TopicsResponse.new(time_spend: response['time_spend'], topics: topics, response_bytes: response['response_bytes'])
      end
      p "real: #{(measure.real * 1000)}"
      p "minus: #{message.time_spend}"
      begin
        Log.create(created_at: Time.now.utc.iso8601, message_size: message.response_bytes, time_spend: ((measure.real * 1000) - message.time_spend).to_i, kind: kind)
      rescue => e
        p e
        p 'Cannot connect to elastic'
        retry
      end
    end
  end
end

def symb_keys(hash)
  hash.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}
end
```

**Comment by apolcyn** [comment]
I cloned the master branch of the https://github.com/w00lf/grpc/blob/master/lib/content_generator.rb#L10 repo to look into this.

For the plain http/json test, I ran the `lib/json_server.rb` for the http server, and ran the `rest_objects_satble_connection_test` method from `lib/overhead_client.rb` for the client.

For the grpc test, I ran the `lib/overhead_server.rb` for the grpc server, and the `objects_stable_connection_test` method from `lib/overhead_client.rb` for the client.

I made a couple of tweaks to get things to work, and for each client, I removed logging, and instead just took a sum and the mean of the real times, measured by ruby `Benchmark`, of 1000 calls.

In both cases I ran the client and server on the same machine. This probably does a bad job of simulating real latency, but I'm guessing that if anything the localhost connections would be in favor of http/json for this comparison.

With this, my results were actually about flipped. I was getting mean real times of about 6.5ms for json/http, and about 4.1ms for grpc.  

A couple of things I was unsure about:
1. When running you're benchmarks, are you running them between different machines?
2. In my tests, the times taken to construct response messages on the server were submillisecond, and I'm not sure if `Benchmark` can measure them well.
4. As `Benchmark.real` is time in seconds, unclear on all of the multiplies by 1000.
3. I took out the fo<random_number> query parameters on the http request, as they didn't seem to be getting used.
4. The gemspec is depending on grpc ~> 0.11, for me it was actually pulling down 0.15, but 1.0.0 has been released. There's continuing performance improvements on grpc (although for this test, I didn't see much of a difference between 0.15 and 1.0.0).

Anyways it seems like it could be useful to get more benchmarks of this type, comparing http/json and grpc for something like unary calls. cc @murgatroid99 @vjpai @ctiller

**Comment by w00lf** [comment]
> 1. When running you're benchmarks, are you running them between different machines?

First I have tested both benchmarks on docker-compose claster(see docker-compose.yml). Then i thought that docker causes this weird behavior, so i tested it locally on my machine - results were the same.

> 2. In my tests, the times taken to construct response messages on the server were submillisecond, and I'm not sure if Benchmark can measure them well.

How many iterations have you run? Overhead_client has argument n that denotes a maximum requested size of topics array, on 30 and more time for generation mock objects was more than 30 ms. Usually i tried n == 200.

> 4. As Benchmark.real is time in seconds, unclear on all of the multiplies by 1000.

Hm, did not think about that, but in both cases measurements have been done by the same method and the test data looks pretty smooth: https://docs.google.com/spreadsheets/d/1gq5MG5n1gROt1AVAajRGqjAypzFE0-grKfFgmUjnPBY/edit?usp=sharing

> 3. I took out the fo query parameters on the http request, as they didn't seem to be getting used.

My first guess was that sinatra uses some caching technique, so i added random parameter to exclude this hypothesis 

> 4. The gemspec is depending on grpc ~> 0.11, for me it was actually pulling down 0.15, but 1.0.0 has been released. There's continuing performance improvements on grpc (although for this test, I didn't see much of a difference between 0.15 and 1.0.0).

Did not noticed that, probably because i copied the example from docs. I will try to test with the new version tomorrow and notice you about the results.

**Comment by w00lf** [comment]
I have managed to pinpoint the root of those slow requests! As it turns out the main reason of slow downs were those lines:
https://github.com/grpc/grpc/blob/v1.0.0/src/ruby/lib/grpc/generic/active_call.rb#L228
https://github.com/grpc/grpc/blob/v1.0.0/src/ruby/lib/grpc/generic/active_call.rb#L230
https://github.com/grpc/grpc/blob/v1.0.0/src/ruby/lib/grpc/generic/active_call.rb#L232

In a small volume of data, this has little impact, but with the growth of data volume grows and latency. Remote_read`s passes the entire request to the logging. That on moderate data volume leads to a large latency. I have made new test without those 3 lines and increase in speed was tremendous(more than 10 times).

**Comment by apolcyn** [comment]
@w00lf thanks for looking into this and sharing this! It's interesting how much of an effect these logging statements have with larger messages. This helps a lot, we will soon take these out.

**Comment by w00lf** [comment]
No problem) I think the simple check for message size and truncation if it large can do the trick or checking what log level is. I can do pull request if you accept them. It is funny how simple method calls can affect so strongly the application. When i made new tests the latency was 8 ms vs 250ms with logging!

**Comment by apolcyn** [comment]
@w00lf thanks but made the PR that makes this change in https://github.com/grpc/grpc/pull/7885. It will be included in the next release of gRPC, in version 1.0.1, (also in 1.0.1-pre1). 

Really appreciated anyways for pointing out this problem with larger messages!

**Comment by w00lf** [comment]
I really impressed with the new benchmarks, I will definitely try out this gem in production. Can you advise production's setup for this service? Do I need some proxy/balancing server before RpcServer? Did not find this information in the official documents.

**Comment by apolcyn** [comment]
@w00lf It wouldn't be completely necessary in general to put a proxy or load balancer in front of a gRPC server, but you could proxy or load balance at the TCP or http2 layer if you'd like. The article, https://movinggauteng.co.za/blog/2016/08/03/grpc-with-nghttp2/, provides an example of setting up a gRPC server behind an http2 proxy load-balancer. 

cc @louiscryan

**Comment by apolcyn** [comment]
By the way there is also a grpc-users forum that might be also be helfpul. https://groups.google.com/forum/#!topic/grpc-io/whu5d8K0QvM

**Comment by w00lf** [comment]
Thanks a lot for the links!

**Comment by apolcyn** [comment]
closing this as I believe the main bottleneck in this case has been fixed here.
