### ISSUE TITLE
GRPC/protobuf should not misuse folder names where namespace names are expected

### ISSUE THREAD

**Issue by Zeks** [grpc/grpc#7855]
This produces all kinda of problems for automatic generation and human readability.
Why does grpc even try to mangle folder structure into variable names? Shouldnt package structure be enough?

For example:
void protobuf_AddDesc_AirSpace_2fAltitude_2eproto();

here Altitude already knows it's a member of Airspace because it was declared as 
package "airspace"
but protoc on generation will not insert Airspace into the mix unless it's specifically invoked as:
protoc proto.... cpp_out... Airspace/filename.proto

this folder dependency is extremely strange when package spaces are already explicitly named in proto files.

**Comment by nicolasnoble** [comment]
This issue and the discussion around it belongs in the protobuf project, sorry. Please use https://github.com/google/protobuf for discussing this issue.
