### ISSUE TITLE
grpcio-tools proto compilation fails

### ISSUE THREAD

**Issue by geigerj** [grpc/grpc#7857]
### Expected behavior:

grpcio-tools install automatically includes all dependencies
### Observed behavior:

grpcio-tools complains about missing "protoc-gen-grpc" when trying to compile protos
### Steps to reproduce

Clone the googleapis repo: https://github.com/googleapis/googleapis

```
jgeiger@jgeiger:~/repos/gapi-dev/googleapis$ virtualenv venv
New python executable in /usr/local/google/home/jgeiger/repos/gapi-dev/googleapis/venv/bin/python
Installing setuptools, pip, wheel...done.

jgeiger@jgeiger:~/repos/gapi-dev/googleapis$ . venv/bin/activate

(venv) jgeiger@jgeiger:~/repos/gapi-dev/googleapis$ pip install grpcio-tools
Collecting grpcio-tools
  Using cached grpcio_tools-1.0.0-cp27-cp27m-manylinux1_x86_64.whl
Collecting grpcio>=1.0.0 (from grpcio-tools)
  Using cached grpcio-1.0.0-cp27-cp27m-manylinux1_x86_64.whl
Collecting protobuf>=3.0.0 (from grpcio-tools)
  Using cached protobuf-3.0.0-py2.py3-none-any.whl
Collecting futures>=2.2.0 (from grpcio>=1.0.0->grpcio-tools)
  Using cached futures-3.0.5-py2-none-any.whl
Collecting enum34>=1.0.4 (from grpcio>=1.0.0->grpcio-tools)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting six>=1.5.2 (from grpcio>=1.0.0->grpcio-tools)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages (from protobuf>=3.0.0->grpcio-tools)
Installing collected packages: futures, enum34, six, protobuf, grpcio, grpcio-tools
Successfully installed enum34-1.1.6 futures-3.0.5 grpcio-1.0.0 grpcio-tools-1.0.0 protobuf-3.0.0 six-1.10.0

(venv) jgeiger@jgeiger:~/repos/gapi-dev/googleapis$ python -m grpc.tools.protoc --python_out=tmp --grpc_out=tmp -I. -I/usr/local/google/home/jgeiger/repos/gapi-dev/googleapis google/logging/v2/log_entry.proto
protoc-gen-grpc: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1
```

**Comment by nathanielmanistaatgoogle** [comment]
What you describe as expected behavior is what we describe as expected behavior. Do you happen to know what version of `pip` is getting used to install `grpcio-tools`? What happens if you `pip install --upgrade pip` immediately after creating your virtual environment?

What else can you tell us about the platform on which you're seeing this problem?

**Comment by soltanmm-google** [comment]
`s/--grpc_out/--grpc_python_out/`

Does that fix your problem, @geigerj?

**Comment by bjwatson** [comment]
@soltanmm-google I was encountering the same error, and your change appears to work.

**Comment by bjwatson** [comment]
@nathanielmanistaatgoogle My versions are as follows:

(venv5) brianwatson@brianwatson0:~/src/gapi-dev/googleapis$ python --version
Python 2.7.12
(venv5) brianwatson@brianwatson0:~/src/gapi-dev/googleapis$ pip --version
pip 8.1.2 from /usr/local/google/home/brianwatson/src/gapi-dev/googleapis/venv5/lib/python2.7/site-packages (python 2.7)

**Comment by soltanmm-google** [comment]
@bjwatson Any chance y'all remember where you might've read that flag being `grpc_out` as opposed to `grpc_python_out` (so we can fix it)?

**Comment by bjwatson** [comment]
@soltanmm-google I think that pre-dates my time at Google. We've been using `grpc_out` for all languages, and just now are starting to change it for certain languages (Python, PHP, and Go).

@garrettjonesgoogle Any idea?

**Comment by garrettjonesgoogle** [comment]
@bjwatson no idea, I haven't really dealt with Python codegen.

**Comment by bjwatson** [comment]
@garrettjonesgoogle It was more of a question about using `--grpc_out` across the board for all languages, but maybe that's a better questions for @ethanbao or @geigerj when they return from vacation.

**Comment by soltanmm-google** [comment]
If there's no documentation mismatch then the question of normalizing all grpc plugin output directory names is kinda out of scope until 2.0...
