### ISSUE TITLE
GRPC C# Library For a Windows 8.1 Phone App

### ISSUE THREAD

**Issue by cjrd** [grpc/grpc#7859]
Is it possible to use GRPC with a Windows Phone App? 
When I try to install GRPC through NuGet I receive the following error:

> Error Could not install package 'Grpc.Core 1.0.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 

Has anyone had any luck installing GRPC for a windows phone app? Is it possible to build the C# GRPC from source and target a windows phone app? 

Related Issue: #1620

**Comment by apolcyn** [comment]
@cjrd the gRPC experimental netstandard target might be hopeful, but from what I can see Windows Phone 8.1 implements netstandard 1.2, while gRPC's netstandard target is at netstandard 1.5 (and depends on the NETStandard1.6 library), off the bat I don't think that Windows Phone 8.1 implements enough of netstandard to use gRPC.

cc @jtattermusch, @jskeet if there's more context on this.

**Comment by jskeet** [comment]
That sounds about right, yes. I can't remember what the dependency was that forced netstandard1.5, but I think it was pretty compelling (hard to work around).

**Comment by apolcyn** [comment]
thanks @jskeet. @cjrd closing this as I don't think there aren't any plans that I know of for support of Windows Phone 8.1. I think the easiest way for gRPC support platforms like that in the future is the gRPC netstandard target, but again it will only work if they implement a high enough version of it.

**Comment by cjrd** [comment]
Thanks for the follow-up @jskeet and @apolcyn 

Do either of you know if installing an updated .NET framework, e.g. via the (4.6.2 installer)[https://support.microsoft.com/en-us/kb/3120737] would solve this issue -- or am I misinterpreting something?

Thanks!

**Comment by apolcyn** [comment]
@cjrd yes, the "official" release target of gRPC targets the .NET 4.5 framework. With the back-compatibility between 4.6.2, and 4.5, this should work!

**Comment by jskeet** [comment]
Hang on - I don't think that installing a new version of the *desktop* framework is going to help the *Windows Phone* compatibility.

Basically, unless we could make gRPC either target netstandard1.2 (seems unlikely) or use the PCL moniker (also seems unlikely), I can't see this working on Windows Phone 8.1.

**Comment by apolcyn** [comment]
apologies, my reply wasn't in context, meant to say that the net45 gRPC target should run on 4.6.2 in general, did not mean to say that this will fix the Windows Phone 8.1 issue :)

**Comment by jtattermusch** [comment]
Another challenge in supporting Windows Phone 8.1 apps is that the native dependencies (gRPC C core) would need to be compiler for windows phones. Technically, this should be possible but would require a bit of experimenting. In terms of mobile support for gRPC C#, I think supporting Xamarin first would be easier and would also be beneficial to more users.
