### ISSUE TITLE
C# Server native memory leaks due to GZIP usage

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#7873]
A major memory leak on **server** side (written in C#) occurs when calling RPC functions.
After calling a function 3000 times, while passing 2KB of serialized data in each call, the process got up to 200MB+ of memory usage. According to profiling tools, the leak is from the **Unmanaged Heap** and originated mainly from Grpc.Core.Internal.GrpcThreadPool+<>c__DisplayClass6::<CreateAndStartThread>b__5 (located in Grpc.Core.dll).
The project uses the GRPC 1.0.0 version published in Nuget.

This is the relevant call stack:
 - **Grpc.Core.Internal.GrpcThreadPool+<>c__DisplayClass6::<CreateAndStartThread>b__5**	_Grpc.Core.dll_
   - **Grpc.Core.Internal.CompletionRegistry+<>c__DisplayClass1::<RegisterBatchCompletion>b__0**	_Grpc.Core.dll_
     - **Grpc.Core.Internal.CompletionRegistry::HandleBatchCompletion**	_Grpc.Core.dll_
       - **Grpc.Core.Internal.CallSafeHandle+<>c__DisplayClass1e::<StartReceiveMessage>b__1c**	_Grpc.Core.dll_
         - **Grpc.Core.Internal.BatchContextSafeHandle::GetReceivedMessage**	_Grpc.Core.dll_
           - **dynamicClass::IL_STUB_PInvoke**	_Grpc.Core.dll_
             - **[Unknown frame from grpc_csharp_ext.x86.dll]**	_grpc_csharp_ext.x86.dll_

**Comment by apolcyn** [comment]
So this was noticed when running a gRPC server and calling rpcs's with messages from some other client? Wondering if this resulted in a crash or an out of memory error?

**Comment by amitwaisel** [comment]
@apolcyn Indeed, the client is C++ and ran flawlessly. The C# server was running for a few hours and crashed with OutOfMemoryException.

**Comment by apolcyn** [comment]
Wondering what platform this on? Are these unary sync/async calls? Is this using protobuf messages?

**Comment by amitwaisel** [comment]
Everything runs on Windows (10 x64 to be precise, compiled for x86 platform).
The "flooded" RPC is a simple function (without streams) that is called thousands of times - and even shutting down the server doesn't free the majority of the native memory allocated (around 8MB is freed successfully)
My server's RPC function has the following signature:
**public override async Task<MyResponse> RpcFunc(MyRequest request)**
The function does nothing beside allocating MyResponse and return it from the function.
Do you need any other diagnosis information?

**Comment by amitwaisel** [comment]
After some debugging, I figured out that the majority of the leaked memory in the server is originated from using GZIP compression in the client.
Disabling the GZIP on client side has reduced the server's memory usage significantly (the server code is not aware that the grpc messages are compressed)

**Comment by apolcyn** [comment]
@amitwaisel sorry but I've had trouble reproducing the initial error. E.g., a simple test involving running a series of synchronous blocking unary calls against a local grpc server, with message sizes of 2KB, for a two hour time period (makes about 25,000,000 requests), doesn't seem to be having issues.

Are these calls possibly being made simultaneously rather than sequentially? Are messages being stored somewhere by the app on the server side?

**Comment by amitwaisel** [comment]
@apolcyn The leak occurs even when the server RPC callback ignores the incoming message, and just returns a small message containing a status code.
It happens only when compressing the traffic using GZIP or DEFLATE. Have you tried to compress the messages in your tests?
The traffic is also encrypted and authenticated using client/server certificates

**Comment by apolcyn** [comment]
ah I think I see. Currently, support for compression isn't even across all languages; it's actually not expected that the C++ client compression to C# server would work with the 1.0 versions, as C# doesn't have official support for compression AFAIK. cc @dgquintas @jtattermusch 

This might be a documentation issue. Maybe an exception issue?

**Comment by apolcyn** [comment]
reproduced this with a lot of large sync calls (started to bog down and crash after running ~50k 1MB compressed messages) from cpp client to c# server.

repro went away after #7963

**Comment by apolcyn** [comment]
@amitwaisel thanks for bringing this up and looking into this. It should be fixed in #7963 and included in the next release at 1.0.1, (or 1.0.1-pre1)

**Comment by amitwaisel** [comment]
@apolcyn Is there any ETA for the fix release? And for 1.0.1 release?

**Comment by jtattermusch** [comment]
I believe the fix has already been released as part of 1.0.1-pre1 nuget.
The 1.0.1 release should be out during the next week.
