### ISSUE TITLE
Release 1.0.0 Source code (tar.gz) can not compile

### ISSUE THREAD

**Issue by ml232528** [grpc/grpc#7879]
cmake 3.6.1 error：

The C compiler identification is MSVC 19.0.24210.0
The CXX compiler identification is MSVC 19.0.24210.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at CMakeLists.txt:68 (add_subdirectory):
  The source directory

```
D:/grpc/grpc-1.0.0/third_party/boringssl
```

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:69 (add_subdirectory):
  add_subdirectory given source
  "D:/grpc/grpc-1.0.0/third_party/protobuf/cmake"
  which is not an existing directory.

CMake Error at CMakeLists.txt:70 (add_subdirectory):
  The source directory

```
D:/grpc/grpc-1.0.0/third_party/zlib
```

  does not contain a CMakeLists.txt file.

Configuring incomplete, errors occurred!
See also "D:/grpc/grpc-1.0.0/CMakeFiles/CMakeOutput.log".

**Comment by vjpai** [comment]
Have you tried regular make? Our support for cmake is only early experimental. We're glad to get feedback and bug fixes for it but can't help very much. Maybe a community member could help?

**Comment by jtattermusch** [comment]
Our cmake support is not in much better shape. We strongly suggest migrating to the latest version.
https://github.com/grpc/grpc/blob/master/INSTALL.md#windows
