### ISSUE TITLE
/usr/local/include/google/protobuf/wire_format_lite_inl.h:352:17: error: comparison of integers of different signs: 'const uint32' (aka 'const unsigned int') and 'int'

### ISSUE THREAD

**Issue by swimmingsand** [grpc/grpc#7884]
/usr/local/include/google/protobuf/wire_format_lite_inl.h:352:17: error: comparison of integers of different signs: 'const uint32' (aka 'const unsigned int') and 'int'
      [-Werror,-Wsign-compare]
  if (new_bytes != length) return false;
      ~~~~~~~~~ ^  ~~~~~~
/usr/local/include/google/protobuf/wire_format_lite_inl.h:420:1: note: in instantiation of function template specialization
      'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<double, google::protobuf::internal::WireFormatLite::FieldType::TYPE_DOUBLE>' requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(double, TYPE_DOUBLE)
^
/usr/local/include/google/protobuf/wire_format_lite_inl.h:411:10: note: expanded from macro 'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive<                                         \
         ^

**Comment by swimmingsand** [comment]
git tag : v1.0.0

git commit: 2a69139aa7f609e439c24a46754252a5f9d37500

**Comment by nicolasnoble** [comment]
I'm sorry, but that error is a protobuf one, not a gRPC one. Please file a bug on the appropriate repository instead: https://github.com/google/protobuf

Thanks!

**Comment by yang-g** [comment]
Updating to the most recent protobuf version should fix it.
https://github.com/google/protobuf/issues/1813
