### ISSUE TITLE
Fail to build Python for interop tests

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#7888]
https://grpc-testing.appspot.com/job/gRPC_interop_experiments/3028/console

Also creating executable in /var/local/git/grpc/py27/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /var/local/git/grpc/py27/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/**init**.py", line 215, in main
  File "/var/local/git/grpc/py27/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by nathanielmanistaatgoogle** [comment]
@adelez: how persistent/reproducible is this?

**Comment by adelez** [comment]
Consistently. Strangely, this project uses the same machine as the master interop tests which doesn't have this problem.

**Comment by soltanmm-google** [comment]
It's a problem with the environment, either in Docker or in the way the interop invoker script sets `LANG=en_US.UTF-8`. Because the Docker image automatically sets the locale to `POSIX` for everything, the set `LANG` is, as best as I can guess, unknown, or incompatible, or something to that extent. Whenever I run `virtualenv` without setting `LANG` explicitly, everything flows dandily on through. Alternatively, setting all of `LANG`, `LANGUAGE`, `LC_CTYPE`, `LC_NUMERIC`, `LC_TIME`, `LC_COLLATE`, `LC_THE_KITCHEN_SINK`\*, etc. to `en_US.UTF-8` (instead of just `LANG`) couuuld work? Maybe?

\* not actually a locale setting; just use `LC_ALL`?

**Comment by soltanmm-google** [comment]
Then again, like you said, interop tests haven't exactly been failing non-stop from locale errors, so... that is strange.

**Comment by adelez** [comment]
I added export LANG=en_US.UTF-8, the missing piece between my setup and the master interop tests, but it's still failing: https://grpc-testing.appspot.com/job/gRPC_interop_experiments/3132/console.

**Comment by adelez** [comment]
Setting LC_ALL doesn't help either.

**Comment by soltanmm-google** [comment]
I meant remove `LANG=*`, or set both `LANGUAGE` and `LC_ALL` (I only know of the former working thus far).

**Comment by soltanmm-google** [comment]
Oh, right: and these need to be set before the shell is invoked.

**Comment by adelez** [comment]
export LANG=en_US.UTF-8 was added to build_python.sh to fix a Jenkins python error: https://github.com/grpc/grpc/commit/6f7489373558d932558db24369b205601556061f. 
@muxi, could you please take a look at this?

**Comment by soltanmm-google** [comment]
Oh great. I guess the question now is: *why* is there a difference between the environments on the interop experiments machines and on the regular interop machines when all that should ostensibly be subsumed by docker...

**Comment by adelez** [comment]
Looks like it'll be fixed in pip8.1.2? https://github.com/pypa/pip/pull/3598/files

**Comment by adelez** [comment]
pip 2.1.8 has a fix for it: https://pip.pypa.io/en/stable/news/.
However, we are using setuptools and I'm not sure which version of pip we are using and how to upgrade to 2.1.8. Still looking.

**Comment by soltanmm-google** [comment]
@adelez Is this still a problem?

**Comment by adelez** [comment]
Yes: https://grpc-testing.appspot.com/job/gRPC_interop_experiments2/1491/console

**Comment by nathanielmanistaatgoogle** [comment]
@adelez, @matt-kwong, @ncteisen: if this issue were current one of you would have complained to me about it some time in the last two months, right? Can this be closed or has it silently been a problem still for the last two months? If it's still open, let's make an assessment of its priority and a reassessment of its milestone.

**Comment by adelez** [comment]
I was just gonna update: I found that this only happens to machines labeled "interop", not the "interopnew" ones. @jtattermusch, @matt-kwong , do you know any missing settings may cause this issue? Assigning to myself.

**Comment by nathanielmanistaatgoogle** [comment]
@adelez: thanks much.

Since this is a team-internal matter concerning our own test infrastructure I see no reason for it to be assigned to the `1.1.0` release; punting.

**Comment by nathanielmanistaatgoogle** [comment]
(This could use a priority if someone wants to assess one.)

**Comment by adelez** [comment]
Fixed when moved to "interopnew" machines. Was running on "interop" machines.
