### ISSUE TITLE
SIG36 while debugging with gdb

### ISSUE THREAD

**Issue by schoenenberg** [grpc/grpc#7906]
Hi,
while debugging with gdb I got this:

`Program received signal SIG36, Real-time event 36.
[Switching to Thread 0x7ffff18b4700 (LWP 3654)]
0x00007ffff60915b7 in __GI_epoll_pwait (epfd=9, events=0x7ffff18b0970, maxevents=1000, timeout=-1, set=0x7ffff18b4620) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:48
48      ../sysdeps/unix/sysv/linux/epoll_pwait.c: No such file or directory.`

It seems like I have a missing source file. Where do I get this file?

**Comment by schoenenberg** [comment]
In gdb this signal can be suppressed with `handle SIG36 noprint nostop`, but this isn't the solution to this, is it?

**Comment by ctiller** [comment]
grpc uses a signal internally for some wakeups it needs to do. It's defaulted to SIGRT2 (SIG36 to gdb).

The signal used can be overridden with the grpc_use_signal() API:

```
/** GRPC Core POSIX library may internally use signals to optimize some work.
   The library uses (SIGRTMIN + 2) signal by default. Use this API to instruct
   the library to use a different signal i.e 'signum' instead.
   Note:
   - To prevent GRPC library from using any signals, pass a 'signum' of -1
   - This API is optional but if called, it MUST be called before grpc_init() */
GRPCAPI void grpc_use_signal(int signum);
```

Note that disabling it comes with a significant performance penalty.
