### ISSUE TITLE
What is the current protoc-php plugin people use for protobuf3?

### ISSUE THREAD

**Issue by Zeks** [grpc/grpc#7908]
Given that grpc/php is in GA state it seems that proto3 support should be enabled, but I wasnt able to find any official proto-php generator plugin and every unofficial one seems to be in varios state of disrepair. What should I use if I want to use proto3 syntax with grpc/PHP ?

**Comment by thinkerou** [comment]
Now the protobuf3 not support PHP, please read it: https://github.com/google/protobuf/issues/358

**Comment by Zeks** [comment]
Thx for the link, So we need to wait for approx a month then, this is ok.

**Comment by stanley-cheung** [comment]
That's correct. Official Proto3 support for PHP is expected very soon.
