### ISSUE TITLE
Can't find information about building a static version of the library

### ISSUE THREAD

**Issue by arhuaco** [grpc/grpc#7917]
Where can I find it? I've tried tweaking the Makefile without success and cmake doesn't work with the lib.

Thanks.

**Comment by thinkerou** [comment]
`make static` or `make static_c`, right?

**Comment by arhuaco** [comment]
Hi there. Thanks for the reply.

I think I should have said "static only". With static and static_c I get:

libgrpc.a
libgrpc++.a
libgrpc_cronet.a
libgrpc_cronet.so
libgrpc_cronet.so.1
libgrpc_cronet.so.1.1.0-dev
libgrpc++_reflection.a
libgrpc++_reflection.so
libgrpc++_reflection.so.1
libgrpc++_reflection.so.1.1.0-dev
libgrpc.so
libgrpc++.so
libgrpc.so.1
libgrpc++.so.1
libgrpc.so.1.1.0-dev
libgrpc++.so.1.1.0-dev
libgrpc_unsecure.a
libgrpc++_unsecure.a
libgrpc_unsecure.so
libgrpc++_unsecure.so
libgrpc_unsecure.so.1
libgrpc++_unsecure.so.1
libgrpc_unsecure.so.1.1.0-dev
libgrpc++_unsecure.so.1.1.0-dev

**Comment by vjpai** [comment]
Hi there,
I can't reproduce the problem. For me, "make static" only produces the ".a" files on Linux and Mac. Can you mention what is your platform? I'm working on standard Makefile at master.
Thanks!

**Comment by arhuaco** [comment]
Ubuntu 15.10. Desktop. 64 bits. Thanks.

**Comment by vjpai** [comment]
And to clarify, are you having this issue with make or cmake? Because I ran
those tests with make as distributed. Cmake support is still experimental,
so I don't have any suggestions in that case.

**Comment by arhuaco** [comment]
With make, cmake doesn't work for me.
What kind of detailed feeback would be useful to you? I can generate a log.

**Comment by vjpai** [comment]
Sure, a log would be very helpful.

**Comment by arhuaco** [comment]
Log attached.
[log.txt](https://github.com/grpc/grpc/files/446181/log.txt)

**Comment by arhuaco** [comment]
I tried "sudo make static install" instead of "make install" because I thought it was the problem, but I still get the shared libs.

**Comment by nicolasnoble** [comment]
Right, the install target will build the shared libraries.

**Comment by nicolasnoble** [comment]
So we don't specifically have any target to install the static libraries
only, because our users who want static libraries only will use the
BUILDDIR variable to drop the files elsewhere during compilation.

```
BUILDDIR=/tmp/grpc make static
ls -la /tmp/grpc/libs/opt
```

**Comment by arhuaco** [comment]
I wasn't aware of BUILDDIR.

    ls /tmp/grpc/libs/opt/ -1
    libboringssl.a
    libgpr.a
    libgrpc++.a
    libgrpc++_reflection.a
    libgrpc++_unsecure.a
    libgrpc.a
    libgrpc_cronet.a
    libgrpc_plugin_support.a
    libgrpc_unsecure.a
    pkgconfig

Thanks a lot for the tip. Not obvious IMHO :-)

**Comment by arhuaco** [comment]
How shall I get the .h's in this case?

**Comment by soltanmm-google** [comment]
They're under the top-level `include/` directory.
