### ISSUE TITLE
gRPC is there a way to change transport

### ISSUE THREAD

**Issue by arun0009** [grpc/grpc#7931]
gRPC uses http2 as transport protocol. Is there a way to change or override the default http2 protocol to MQ or NATS as the transport protocol?

**Comment by louiscryan** [comment]
Currently and for the immediate future the answer is no. We have been
careful with internal API layering to allow for this possibility in the
future it's not work we anticipate doing ourselves right now. As has been
mentioned on some other recent threads there's a lot of performance fruit
that remains to be picked and we're going to focus on that.

Specifically for MQ and NATS what do you perceive as their advantages vs
using HTTP2. It's my working assumption that since HTTP2 will have standard
internet infrastructure support that messaging systems will move to using
HTTP2 over time since it gives them streaming & flow-control support at the
transport layer and that they would layer message reliability semantics
over that.

**Comment by arun0009** [comment]
Looking for pub/sub implementation and features like at-least-once-delivery, fanout, topic identification or ACLs that a pub/sub broker implementation would provide like e.g. NATS. 

Just want to use NATS only for inter service communication and http2 of external facing gRPC services.

**Comment by louiscryan** [comment]
These are apples and oranges.

NATS provides a brokered (i.e hub & spoke) pub-sub system, GRPC is
primarily designed for peer-to-peer communications between services and
generally sits at a lower level in the stack. We would not consider adding
messaging semantics like at-least-once-delivery to GRPC as it would be
layering violation.

These technologies can be complimentary as GRPC streaming support gives a
way for pubsub systems with proprietary wire formats like NATS to bridge to
the internet at large. Google's Cloud PubSub API does this for example. It
shouldn't be hard to write these bridges yourself

**Comment by arun0009** [comment]
Thanks @louiscryan . I will go with the route of adding a bridge instead of trying to find ways to override the transport layer.

**Comment by louiscryan** [comment]
@derekcollison

FWIW I think NATS is pretty awesome. If I had time I'd be interested in
trying to hack GRPC+Proto as the transport mechanism into NATS to see if we
could get it close to the performance of it's native protocol.

Derek's talk on doing transport optimizations in Go is a great listen ...

https://www.youtube.com/watch?v=ylRKac5kSOk&feature=youtu.be

... and GRPC Go has not gotten that far yet in its optimization work.

**Comment by joeblew99** [comment]
@arun0009 

It might work using grpc-gateway..

SO instead of changing NATS, you can possibly layer GRPC.gateway on top
Because GRPC IS a DSL, its easy to code gen, so you could probably code gen a layer to put the GRPC data onto the NATS message bus.
You would get all the nice things about GRPC and NATS without forking or messing wth either.

Not saying this is the way, but just thinking out loud about it.

**Comment by arun0009** [comment]
Thanks @joeblew99 We did end up doing the exact same thing you mentioned above - adding https://github.com/mwitkow/grpc-proxy and passing data over NATS and a hook on the server side to take data and call the server implementation. It might not be the best solution but it works without any framework changes like you mentioned.

**Comment by joeblew99** [comment]
@arun0009 
Sweet - thanks for letting me know it worked. I checked out the repo but there are no references to NATS.
Also the GRPC-Gateway was not good enough ?

**Comment by AlecZadikian9001** [comment]
More on allowing the option to swap out HTTP/2: Maybe you have clients like IoT devices with high packet loss and/or latency that HTTP/2 (or rather the TCP it runs on) won't handle well. There are protocols designed to handle this with preemptive retransmission, for one. Also, you need in-order messages for gRPC streaming methods but not for regular method calls, so using TCP for everything introduces unnecessary slowdowns when high packet loss is involved.

**Comment by Timmmm** [comment]
I'm writing a program that works over SSH (like VSCode's recent remote editing support). It would be nice to be able to use gRPC over SSH but it's not really possible with the hard dependency on HTTP2. I would use Thrift, which has really not support for different transports, including user-defined ones, but unfortunately it doesn't support server-sent events / streams, which is a pretty critical feature.

**Comment by joeblew99** [comment]
My understanding is:
http 3 Web Transports will allow network transports using modern P2P style topologies.

https://tools.ietf.org/html/draft-vvv-webtransport-http3-00#page-6

This means that websockets is redundant.
Also Webrtc data channels are redundant I am pretty sure.

It will be here soon in many 6 months to a year.

**Comment by Timmmm** [comment]
@joeblew99 That's not what this bug is about. People want to be able to specify the transport layer themselves, like you can with Thrift.

**Comment by yashykt** [comment]
gRPC C++ now has the interception API which on hijacking allows you enough control on the RPC to allow a switch of transport. This would basically prevent the RPC going down the gRPC Core stack and the user can instead redirect the data to a different transport.

**Comment by wallyqs** [comment]
thanks @yashykt, for those not aware could you share a link about the interceptor API? Sounds interesting

**Comment by yashykt** [comment]
Pleae refer 
https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/interceptor.h for more information.

https://github.com/grpc/grpc/tree/master/examples/cpp/keyvaluestore is an example of how one might be able to use the API.

**Comment by deanorderly** [comment]
I am confused reading https://github.com/grpc/grpc-java/blob/master/README.md which says you can swap in the transport.  I am trying to swap in webpieces http client and I am trying to swap in http webpieces server as well.  With that, we are probably going to do http2 and may do 'some' http1.1 but not supporting streaming in http1.1.

Is there a good document for java swapping in transports?

**Comment by yashykt** [comment]
@deanorderly grpc-java is covered in a different repository, but overall, please redirect questions to https://groups.google.com/forum/#!forum/grpc-io

**Comment by deanorderly** [comment]
ah, ok, thanks @yashykt
