### ISSUE TITLE
Testing infrastructure does not provide a provision for different configuration for different branches

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#7934]
For example, The branch `1.0.x` and `master` have different testing requirements i.e. more "compilers" are supported in master than in `1.0.x`. Now if these "compilers" are to make it to the testing suite, they are required to be passing on `1.0.x` which doesn't always happen leading to workarounds such as #7933. It's in the best interest of the project to work on making our test infrastructure account for such cases.

**Comment by jtattermusch** [comment]
This has been addressed by #8141 and by changing the layout of our jenkins jobs.
Now, you can change the configurations run in a given branch by updating https://github.com/grpc/grpc/blob/602edbba8cf03279b3dc2e027ea07660332f806e/tools/run_tests/run_tests_matrix.py#L183.
