### ISSUE TITLE
Ruby Interop build failures

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#7935]
I've been seeing this a bunch on recent interop tests.  Is it just a dependency outage?

Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://rubygems.org/gems/powerpack-0.1.1.gem)

**Comment by murgatroid99** [comment]
This doesn't seem to still be happening.
