### ISSUE TITLE
c#: add remaining missing channel options

### ISSUE THREAD

**Issue by imiuka** [grpc/grpc#7941]
Heya,

ChannelOptions currently doesn't implement the following options that are available in the native library:

```
- grpc.loadreporting
- grpc.http2.lookahead_bytes
- grpc.http2.hpack_table_size.decoder
- grpc.http2.hpack_table_size.encoder
- grpc.max_reconnect_backoff_ms
- grpc.max_metadata_size
- grpc.so_reuseport
```

I care most about `grpc.max_reconnect_backoff_ms` to reduce the reconnect backoff delay, which currently defaults to a maximum of 120s. I'm unsure how important the other options are, or if they were previously left out for a reaso, but some people might have a need to change them away from their defaults.

**Comment by apolcyn** [comment]
You should actually be able to currently use "grpc.max_reconnect_backoff_ms" channel arg, among others, by just passing the argument as a raw string. 

E.g.,
```
new ChannelOption("grpc.max_reconnect_backoff_ms", 100)
```

The existing ChannelOption constants are just for convenience for using the strings like above AFAIK.

cc @jtattermusch, should the ChannelOption constants be kept up to date to match core?

**Comment by imiuka** [comment]
Oh, can't believe I missed that. Thanks so much.

**Comment by jtattermusch** [comment]
@apolcyn , yes we can add constants for channel options that C# users are likely to use. In general, the channel options are intented to be something that 99% of users should need to touch and gRPC should come with reasonable presets.
