### ISSUE TITLE
link errors building grpc_protoc_plugins.sln

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#7944]
There seems to be a mismatch between what vsprojects/grpc_protoc_plugins.sln expects from the output of building the protobuf.sln, and what the steps in protobuf/cmake/README.md creates. Might need a documentation change, or protobuf.sln change to fix.

**Comment by jtattermusch** [comment]
Mismatch in what sense?

**Comment by apolcyn** [comment]
Sorry this is probably mostly some minor doc confusion.

If the lines given in the `vsprojects/README` are followed:
```
$ cd third_party/protobuf/cmake
$ cmake -G "Visual Studio 12 2013"
```
then everything works.

The issue is just the README in https://github.com/grpc/grpc/blob/master/vsprojects/README.md says to follow the protobuf README in https://github.com/google/protobuf/blob/a428e42072765993ff674fda72863c9f1aa2d268/cmake/README.md, to build protobuf libraries, but the protobuf README ends up with a `protobuf.sln` under `third_party/protobuf/cmake/solution`, and then and there's trouble finding and linking the resulting libraries built from it when later building `vsprojects/grpc_protoc_plugins.sln`. 

E.g., `libprotoc.lib` fails to link, as its under the `third_party/grpc/cmake/solution/Release` directory.

But it seems like the grpc_protoc_plugins.sln just expects the built protobuf libs to be under `third_party/grpc/cmake/Release`?
