### ISSUE TITLE
Unable to make a connection to gRPC Server (C++)

### ISSUE THREAD

**Issue by smruthiEJ** [grpc/grpc#7956]
Hi, 

I am starting a gRPC server on [::]:<PortNum>, I can see from the logs that AddListeningPort  and BuildAndStart() is not returning any error, However, while a client sends a request I see connection refused message. 

netstat shows the port in LISTEN state, no iptables configured. 

Tested basic TCP client- server socket example which works fine. 

Steps to Repro:

1. Just compile greeter_Server and greeter_client. 
2. Copy the server on to a different machine. 
3. Start the server which starts saying listening on 0.0.0.0:50051
4. Try making a client request from a different machine, I get connection refused. 

Logs:

Setting the environment variables GRPC_TRACE=all, and GRPC_VERBOSITY=DEBUG

```
bash-4.2# GRPC_TRACE=all GRPC_VERBOSITY=DEBUG ./greeter_server 
I0829 20:05:43.125104331    6649 init.c:135]                 grpc_init(void)
I0829 20:05:43.125196942    6649 init.c:135]                 grpc_init(void)
I0829 20:05:43.125211755    6649 completion_queue.c:121]     grpc_completion_queue_create(reserved=(nil))
I0829 20:05:43.125236822    6649 server_create.c:49]         grpc_server_create(0xffb32f78, (nil))
I0829 20:05:43.126028040    6649 server.c:765]               grpc_server_register_completion_queue(server=0x8cf89e0, cq=0x8cfa860, reserved=(nil))
I0829 20:05:43.126049323    6649 server.c:845]               grpc_server_register_method(server=0x8cf89e0, method=/helloworld.Greeter/SayHello, host=(null))
I0829 20:05:43.126182870    6649 metadata_array.c:42]        grpc_metadata_array_init(array=0x8cf9260)
I0829 20:05:43.126205796    6649 server_chttp2.c:96]         grpc_server_add_insecure_http2_port(server=0x8cf89e0, addr=0.0.0.0:50051)
I0829 20:05:43.126393889    6649 server.c:873]               grpc_server_start(server=0x8cf89e0)
I0829 20:05:43.126416952    6649 metadata_array.c:42]        grpc_metadata_array_init(array=0xffb32f6c)
I0829 20:05:43.126436863    6649 metadata_array.c:47]        grpc_metadata_array_destroy(array=0xffb32f6c)
I0829 20:05:43.126455003    6649 completion_queue.c:121]     grpc_completion_queue_create(reserved=(nil))
I0829 20:05:43.126472738    6649 server.c:1210]              grpc_server_request_registered_call(server=0x8cf89e0, rmp=0x8cfe340, call=0x8cf9248, deadline=0x8cf9250, initial_metadata=0x8cf9260, optional_payload=0x8cf926c, cq_bound_to_call=0x8cfd850, cq_for_notification=0x8cfa860, tag=0x8cf9238)
I0829 20:05:43.126493297    6649 completion_queue.c:121]     grpc_completion_queue_create(reserved=(nil))
I0829 20:05:43.126515110    6649 call_details.c:42]          grpc_call_details_init(cd=0x8cfed00)
I0829 20:05:43.126535189    6649 server.c:1173]              grpc_server_request_call(server=0x8cf89e0, call=0x8cff028, details=0x8cfed00, initial_metadata=0x8cff040, cq_bound_to_call=0x8cfa068, cq_for_notification=0x8cfa860, tag=0x8cff018)
Server listening on 0.0.0.0:50051
I0829 20:05:43.126687151    6651 completion_queue.c:291]     grpc_completion_queue_next(cc=0x8cfa860, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
```

Running TCPdump, I see that [RST] packets are sent for an [SYN] request. 

Using Synchronous mode, C++ server and C++ client.

**Comment by nicolasnoble** [comment]
This seems a very typical firewalling or routing issue to me, nothing really special in the logs are showing anything out of the ordinary.

Could you check basic connectivity between the two machines using something along these lines:

```
machine1:~$ nc -l 50051
machine2:~$ nc machine1 50051
```

**Comment by smruthiEJ** [comment]
Started nc on a port and this is the output of

netstat -na | grep 50051
tcp        0      0 0.0.0.0:50051               0.0.0.0:*                   LISTEN      
tcp        0      0 171.70.58.90:50051          10.104.99.89:15859          ESTABLISHED 
tcp        0      0 171.70.58.90:50051          172.23.167.150:21114        ESTABLISHED 

we can see that the connection is Established

**Comment by smruthiEJ** [comment]
Hi, from the suggestion, I tried running nc as a server on the machine its not working, while I am trying to do nc <IP> 50051 from the client, I see that its not able to make a connection. 

Having said that, I am able to get basic TCP client- Server work. How would those both differ as netcat also makes a TCP connection??

**Comment by nicolasnoble** [comment]
Different port maybe ? What kind of basic tcp client-server you managed to get working ? Each network is different, firewalling rules within the network may apply for some ports and not others.

If a simple netcat on port 50051 doesn't work for you, this clearly indicates that this isn't a grpc-related issue. Try probing which ports are available for you to use using the same methodology, then change your example to use usable ports instead.

**Comment by smruthiEJ** [comment]
Hi Nicolas, 

It was the port range in proc/sys/net/ipv4/ip_local_port_range  that was the culprit. 

Do you think it would be nice, if it has a check to see the range of ephemeral ports and then return either success or failure for AddListeningPort to save the effort ??

**Comment by nicolasnoble** [comment]
I don't believe this would be appropriate. This is way too specific of a feature to provide, for such a low level library that gRPC is. Each operating system is going to have a different mechanism, and potentially each machine even might have different permission sets that would make such heuristic not work. Providing something so specific wouldn't be a good developer experience, because what may magically work on one system would fail on another.

My response would be that this ought to be the responsibility of the API caller to check for such limitation, and call our API accordingly.

I will close this issue as you've solved it on your end. If you want to continue the discussion on the topic of port heuristic, feel free to open a new one dedicated to that purpose.
