### ISSUE TITLE
node: protobuf Maps are converted to javascript arrays

### ISSUE THREAD

**Issue by drobertduke** [grpc/grpc#7958]
Calling toObject() on a Result that includes a map will express the map as an array of arrays. I have to include additional client-side code to make a useful object out of this.

proto definition: `map<string,string> definedscopes = 1;`

client code: `result.toObject();`

result: `{ definedscopesMap: [ [ "key1", "value1" ], [ "key2", "value2" ] ] }`

desired result: `{ definedscopesMap: { "key1": "value1", "key2", "value2" } }`

Since protofbuf map keys are [limited to types](https://developers.google.com/protocol-buffers/docs/proto#maps) that can be converted to valid javascript object keys (strings), it should be feasible to express protobuf maps as javascript objects.

**Comment by murgatroid99** [comment]
Are you loading the proto files at runtime with `grpc.load`, or are you using the `google-protobuf` library and generated files?

**Comment by drobertduke** [comment]
google-protobuf and generated files.

**Comment by murgatroid99** [comment]
In that case, you should file the issue in the [google/protobuf repo](https://github.com/google/protobuf/issues).

**Comment by drobertduke** [comment]
Thanks, will do
