### ISSUE TITLE
ruby build readme for mac

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#796]
Ruby 2.1 is needed; however installing 2.1 could encounter some problems.  More details will be included to address this issue.

**Comment by tbetbetbe** [comment]
@donnadionne, PTAL
This is fixed.   Please try to install grpc ruby by following the instructions at https://github.com/grpc/homebrew-grpc

**Comment by tbetbetbe** [comment]
@stanley-cheung - can you do a quick pass to confirm this works,  and then close this issue please ?

**Comment by stanley-cheung** [comment]
Yes, confirmed again that I can install ruby grpc using homebrew on mac with ruby 2.1.5.
