### ISSUE TITLE
C++ Grpc server (version 0_11_1) core due to the assert in pipe() call after 36 hours of run. Probably fd leak?

### ISSUE THREAD

**Issue by M-Vivek** [grpc/grpc#7965]
We are running longevity test for our C++ gRPC server. The server provides an RPC to subscribe for streaming and also an RPC to unsubcribe. We are calling subscribe()/unsubscribe() in a loop. This pair is called every 50 secs. And we see that the server cores after around 36 hours of run. The core happens due to assert in pipe() call. We suspect this might be due to fd leak.

Is there any known issue that would have fixed this that we can cherry pick for 0_11_1. Could this be a c-core issue or c++ plugin issue? At this stage, we are not ready to move to new version of the gRPC stack as it would require a re-qualification by our test folks and we will not be able to meet our timelines.

It would be nice if someone takes a quick look.

The backtrace looks like below:

(gdb) bt
#0  0xc8677fbb in thr_kill () at thr_kill.S:3
#1  0xc8677f67 in __raise (s=6) at /.amd/svl-engdata1vs1/occamdev/build/freebsd/stable_10/20160723.171211_fbsd-builder_10.331042/src/lib/libc/gen/raise.c:51
#2  0xc8676977 in abort () at /.amd/svl-engdata1vs1/occamdev/build/freebsd/stable_10/20160723.171211_fbsd-builder_10.331042/src/lib/libc/stdlib/abort.c:65
#3  0x081518ab in pipe_init (fd_info=<optimized out>) at ../../../../../../src/junos/lib/libgrpc/src/core/iomgr/wakeup_fd_pipe.c:50
#4  0x08150c40 in grpc_pollset_work (pollset=0x8c1321c, worker=0xfebf8de8, now=..., deadline=<error reading variable: Cannot access memory at address 0x0>) at ../../../../../../src/junos/lib/libgrpc/src/core/iomgr/pollset_posix.c:180
#5  0x0814e9fd in grpc_completion_queue_next (cc=<optimized out>, deadline=..., reserved=0x0) at ../../../../../../src/junos/lib/libgrpc/src/core/surface/completion_queue.c:210
#6  0x0813e612 in grpc::CompletionQueue::AsyncNextInternal (this=<optimized out>, tag=0xfebf8ef8, ok=0xfebf8ef7, deadline=...) at ../../../../../../src/junos/lib/libgrpc/src/cpp/common/completion_queue_cpp.cc:56
#7  0x08133248 in Next (this=0x8c0cf8c, tag=<error reading variable: Cannot access memory at address 0x0>, ok=<optimized out>) at ../../../../../../src/junos/lib/libgrpc/include/grpc++/completion_queue.h:127
#8  Wait (cq=0x8c0cf8c, ok=<optimized out>) at ../../../../../../src/junos/lib/libgrpc/src/cpp/server/server_cpp.cc:133
#9  grpc::Server::RunRpc (this=0x8c0cf80) at ../../../../../../src/junos/lib/libgrpc/src/cpp/server/server_cpp.cc:548
#10 0x08133e6f in __invoke<void (grpc::Server::*&)(), grpc::Server*&, void> (__f=<optimized out>, __a0=<optimized out>)

```
at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/__functional_base:380
```
#11 __apply_functor<void (grpc::Server::*)(), std::__1::tuple<grpc::Server *>, 0, std::__1::tuple<> > (__f=<optimized out>, __bound_args=..., __args=<optimized out>)

```
at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/functional:2023
```
#12 operator()<> (this=<optimized out>) at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/functional:2086
#13 __invoke<std::__1::__bind<void (grpc::Server::*)(), grpc::Server*>&> (__f=...) at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/__functional_base:413
#14 std::__1::__function::__func<std::__1::__bind<void (grpc::Server::*)(), grpc::Server*>, std::__1::allocator<std::__1::__bind<void (grpc::Server::*)(), grpc::Server*> >, void ()>::operator()() (this=0xfebf8f38)

```
at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/functional:1370
```
#15 0x081397f1 in operator() (this=<optimized out>) at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/functional:1756
#16 grpc::FixedSizeThreadPool::ThreadFunc (this=0x8c0c840) at ../../../../../../src/junos/lib/libgrpc/src/cpp/server/fixed_size_thread_pool.cc:53
#17 0x0813a74e in __invoke<void (grpc::FixedSizeThreadPool::*)(), grpc::FixedSizeThreadPool*, void> (

```
__f=<unknown type in /.amd/svl-engdata1vs1/vol/eabu_jenkins/jvision/development/20160830.0/grpc_build/obj/bsd10/i386/junos/usr.sbin/server/na-grpcd, CU 0xc86b1a, DIE 0xc9086b>, __a0=<optimized out>)
at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/__functional_base:380
```
#18 __thread_execute<void (grpc::FixedSizeThreadPool::*)(), grpc::FixedSizeThreadPool*, 1> (__t=...) at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/thread:332
#19 std::__1::__thread_proxy<std::__1::tuple<void (grpc::FixedSizeThreadPool::*)(), grpc::FixedSizeThreadPool*> > (__vp=0x8c0d940)

```
at /volume/publish/dev/occam/llvm-3.5/sysroot/stable_10/current/i386-unknown-freebsd10.1/usr/include/c++/v1/thread:342
```
#20 0xc86f7dfb in thread_start (curthread=0x8c04480) at /.amd/svl-engdata1vs1/occamdev/build/freebsd/stable_10/20160723.171211_fbsd-builder_10.331042/src/lib/libthr/thread/thr_create.c:288
#21 0x00000000 in ?? ()

**Comment by nathanielmanistaatgoogle** [comment]
[gRPC 0.11.1 was nearly a year ago](https://github.com/grpc/grpc/releases/tag/release-0_11_1) - what is it that has you using such old code and how hard would it be for you to upgrade to 1.0.0?

**Comment by nicolasnoble** [comment]
Well, he said it ;-) That version was vetted by their company, and vetting a new version would take too much time.

Unfortunately, however, as @nathanielmanistaatgoogle points out, this beta version was over a year ago, and a huge lot of things changed in the meantime. There is a boatload of bugs that were fixed between 0.11 and 1.0, so remembering and finding the exact cause of what you're experiencing here isn't going to be possible for us. Sorry, but we won't be able to provide support for past beta releases of gRPC. Or was it even alpha ? I don't remember...

**Comment by nathanielmanistaatgoogle** [comment]
D'oh! @M-Vivek, I apologize for not fully reading your report.

@nicolasnoble: I believe 0.11 was the first beta release.

**Comment by M-Vivek** [comment]
Hi nathaniel, nicolas, I understand that there should have been lots of bug fixes. Hence I tried to categorize the issue as probable fd leak. 

Is it possible, at the least, to get the list of issues that was due to fd leak?

**Comment by soltanmm-google** [comment]
It's unclear what we can do on our end for this; it's unsupported now, and the bug tracker is publicly available data.
