### ISSUE TITLE
grpc-node doesn't work on raspberry pi.

### ISSUE THREAD

**Issue by mikelehen** [grpc/grpc#7968]
grpc-node doesn't have a pre-built ARMv7 library, and it fails to build with GYP.

**Comment by murgatroid99** [comment]
What failure do you see when building with gyp?

**Comment by lawrence79** [comment]
@mikelehen Did you end up finding a solution for this?

**Comment by mikelehen** [comment]
No.  This was reported by a hackathon participant.  I don't have more details and haven't attempted to reproduce it myself...

**Comment by mikelehen** [comment]
I played with this over the weekend and was able to install grpc on my raspberry pi, so perhaps whatever the issue was has been fixed in grpc or the raspbian tools...  Anyway, closing for now without more concrete info about what went wrong.

**Comment by jayhill365** [comment]
Can you tell me how you got grpc to install? Having issues getting it install on my pi thanks !

**Comment by mikelehen** [comment]
Hrm.  I don't remember anything tricky.  I think I basically just did a normal "npm install grpc-node" or similar.  Probably best to open a new issue with your symptoms if you're having problems.
