### ISSUE TITLE
Can't assign requested address when connect IPv4 address on IPv6 network

### ISSUE THREAD

**Issue by gfxcc** [grpc/grpc#7978]
connect error to 'ipv4:xxx.xxxx.xxxx.xxxx': Can't assign requested address

It works fine on ipv4 network. How to fix it?

**Comment by gfxcc** [comment]
Using gRPC (0.12.0)
Using Protobuf (3.0.0-beta-2)
Using BoringSSL (2.0)

Is there anyone have the same problem? Help pls

**Comment by thinkerou** [comment]
You should use `grpc 1.0.0`?

**Comment by gfxcc** [comment]
Fixed after update server to 1.0.0 cpp
