### ISSUE TITLE
How do you get the network latency value tested by netperf

### ISSUE THREAD

**Issue by swimmingsand** [grpc/grpc#7988]
According to you document, I used netperf to do network performance benchmark test

below is command

```
netperf -H xxx.xxx.xxx.xxx -t TCP_RR
```

below is test result

```
MIGRATED TCP REQUEST/RESPONSE TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.126.81.104 () port 0 AF_INET : demo : first burst 0
Local /Remote
Socket Size   Request  Resp.   Elapsed  Trans.
Send   Recv   Size     Size    Time     Rate
bytes  Bytes  bytes    bytes   secs.    per sec

65536  87380  1        1       10.00    12507.44
65536  87380
```

When I read your dashboard, I found latency value required by netperl as is shown in below, but I can't found this value in netperf test result. Could you explain this? Thank you very much!

![6bf8461c-4328-4f06-aac4-8f5a42c32222](https://cloud.githubusercontent.com/assets/2804153/18260256/95382a88-741e-11e6-9166-df2c0816e80b.png)

**Comment by vjpai** [comment]
So the actual command is a little more subtle. You can find it in [run_netperf.sh](https://github.com/grpc/grpc/blob/master/tools/run_tests/performance/run_netperf.sh) : 
`netperf -P 0 -t TCP_RR -H "$NETPERF_SERVER_HOST" -- -r 1,1 -o P50_LATENCY,P90_LATENCY,P99_LATENCY`

This is what actually provides the information that we display on the dashboard.
