### ISSUE TITLE
A curious phenomenon in testing gRPC

### ISSUE THREAD

**Issue by psnbbgy** [grpc/grpc#7989]
I found a curious result when I test gRPC:
I send package(21KB) with client using one thread, and when I send 100000 packages without stop, I get the latency 4.4ms, and when I use sleep() function everytime I send a package, I get latency larger than 10ms. And sometimes the higer QPS environment get lower latency too(QPS controlled by thread num).
And I have calculate one call time, it is 13ms. Is the gRPC have any optimization for high qps or consecutive call?
or my statistical method is wrong? my client code is like this:

start_time = gpr_now(GPR_CLOCK_REALTIME);
Status status = stub_->GetFeature(&context, point, feature);
tmp = gpr_time_sub(gpr_now(GPR_CLOCK_REALTIME),start_time);

and I will add all the tmp and calculate average value.

**Comment by vjpai** [comment]
This may have nothing to do with gRPC. In particular, it is a known
phenomenon that processors may slow their clocks down if the load is very
low, and this may have a negative effect on latency. As load increases a
little bit, latency is likely to actually improve as processors ramp their
clocks up. However, beyond a certain point, latency will degrade as load
continues to increase. The only way to rule out this effect is to peg your
clock at the maximum speed.

**Comment by psnbbgy** [comment]
OK, I know it, Thank you very much.
