### ISSUE TITLE
PHP and PHP7 cloud-to-prod auth interop tests are still failing on jwt_token_creds

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#7999]
https://grpc-testing.appspot.com/job/gRPC_interop_master/7229 and numerous other builds

Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.1.8/bin' is not available,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.1.8'.
Using /usr/local/rvm/gems/ruby-2.1.8
stdin: is not a tty
Running test case jwt_token_creds

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /var/local/git/grpc/src/php/lib/Grpc/AbstractCall.php on line 67

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /var/local/git/grpc/src/php/lib/Grpc/AbstractCall.php on line 80
Call did not complete successfully. Status object:
object(stdClass)#26 (3) {
  ["metadata"]=>
  array(1) {
    ["www-authenticate"]=>
    array(1) {
      [0]=>
      string(66) "Bearer realm="https://accounts.google.com/", error="invalid_token""
    }
  }
  ["code"]=>
  int(16)
  ["details"]=>
  string(47) "Request had invalid authentication credentials."
}

FAILED: cloud_to_prod_auth:default:php7:jwt_token_creds [ret=1, pid=13994]

**Comment by stanley-cheung** [comment]
I just merged #7959 about an hour ago.

interop master is green since: https://grpc-testing.appspot.com/job/gRPC_interop_master/7232/

Here's my interop pull request green build: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/7976/ Any new pull requests need to rebase off the latest master I suppose.

**Comment by vjpai** [comment]
Sg. Marking as resolved.
