### ISSUE TITLE
Node client with server-only stream doesn't seem to work properly

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#8001]
First, the server-sided stream request from the node.js client requires a callback function. This doesn't make sense as there's no single error or result callback. As far as I can tell, this is never called with anything but an error.

If I return an error from the server side, metadata, "status", and the error callback provided in the function call get called. If I return a single message and then hold the stream open, I don't get anything over the data event, nor over the regular callback.

Golang clients work fine for the golang grpc server I'm testing against.

**Comment by murgatroid99** [comment]
If you are seeing a server streaming method that requires a callback on the client, then something is set up incorrectly. That's not what is supposed to happen.

Can you make sure that the .proto file is identical on the client and server, and provide the contents of the .proto file?

**Comment by paralin** [comment]
Yes, I'll try to get a reproduce for you here. Thanks for the response.

**Comment by paralin** [comment]
@murgatroid99 Okay I think I know the problem. I use the `pbjs` binary from Protobuf.JS to compile a lot of proto files together into a single Javascript object (using the JSON output). I then use `ProtoBuf.loadJson(definitions)`. I load this into grpc by doing `grpc.loadObject(builder.lookup('mynamespace.MyService'))`.

This works fine for regular protobufs, as well as non-streaming grpc calls. I think the streaming information is lost somewhere in the mix.

**Comment by paralin** [comment]
This also relates to: https://github.com/dcodeIO/protobuf.js/issues/468

**Comment by murgatroid99** [comment]
You're right. I totally missed this in my tests, but it looks like Protobuf.js does in fact drop the streaming information when it converts to JSON. The funny thing is that grpc can actually load those JSON files directly with `grpc.load(json_filename, 'json')`, but it just calls `ProtoBuf.loadJson` anyway, so that wouldn't help.

Why don't you want to load the proto files at runtime? It isn't really much different from loading JSON files at runtime.

And yes, this is a bug in Protobuf.js, and it needs to be fixed there. That `pbjs` tool is discarding information, and it should not be doing that.

**Comment by paralin** [comment]
@murgatroid99 the proto files are scattered all over the place in a number of different projects, for example, the codebases for each of the services I call. I have a build step that collects these with pbjs into a single definitions file, and also builds Typescript definitions for all the messages. 

I'll have a look at fixing the pbjs implementation.

**Comment by paralin** [comment]
@murgatroid99 PR sent to Protobuf.JS

**Comment by paralin** [comment]
As this is a Protobuf.JS issue and not a GRPC issue (just confirmed it works great now that I've fixed the pbjs bug) I'll close this. Thanks!
