### ISSUE TITLE
ObjC tests failing at master with iPhone simulator launch issue

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8002]
https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=objc,platform=macos/18513/testReport/junit/(root)/tests/objc_tests/

(and several others)

...
set -o pipefail
XCODEBUILD_FILTER='(^===|^\*\*|\bfatal\b|\berror\b|\bwarning\b|\bfail)'
xcodebuild \
    -workspace Tests.xcworkspace \
    -scheme AllTests \
    -destination name="iPhone 6" \
    test \
    | egrep "$XCODEBUILD_FILTER" \
    | egrep -v "(GPBDictionary|GPBArray)" -
2016-09-06 13:35:01.485 xcodebuild[98517:33907786] [MT] iPhoneSimulator: Could not launch simulator: -600

**Comment by makdharma** [comment]
@muxi any ideas?

**Comment by muxi** [comment]
Not immediately. Looking on it

**Comment by muxi** [comment]
Should be resolved
