### ISSUE TITLE
grpc master tests: python, dbg/opt, windows unrun in 3 months

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8003]
Problem here with this test not running in a long time. Not sure why - C is running.

**Comment by nathanielmanistaatgoogle** [comment]
@vjpai, @nicolasnoble: does [this test result](https://grpc-testing.appspot.com/job/gRPC_master_windows/1290/) ([dbg](https://grpc-testing.appspot.com/job/gRPC_master_windows/1290/testReport/(root)/python_windows_dbg/), [opt](https://grpc-testing.appspot.com/job/gRPC_master_windows/1290/testReport/(root)/python_windows_opt/)) indicate that this issue has been resolved?

**Comment by vjpai** [comment]
Fixed.
