### ISSUE TITLE
AttributeError: Extension instance has no attribute '_needs_stub' if setuptools is out-of-date

### ISSUE THREAD

**Issue by jayeye** [grpc/grpc#8004]
If an old version of setuptools is installed (e.g., Ubuntu has v20.7 in the apt repositories, whereas the current version in pypi is 26. This causes the following failure:

```
We could not diagnose your build failure. Please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title.

Traceback (most recent call last):
  File "/home/ji/grpc/src/python/grpcio/commands.py", line 272, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 175, in build_extension
    if ext._needs_stub:
AttributeError: Extension instance has no attribute '_needs_stub'
```

While this is obviously not a bug in grpc, it _is_ a bug in the diagnosis; can the diagnostic be amended to say something along the lines of "make sure you have version X or newer of setuptools?

**Comment by nathanielmanistaatgoogle** [comment]
We've tried to ensure that we say ["ensure that you have `pip` 8 or later"](http://www.grpc.io/docs/quickstart/python.html#prerequisites) in all our installation instructions - have you found a place where we've missed this?
