### ISSUE TITLE
asan/c/linux tests.bins/asan/h2_proxy_test streaming_error_response GRPC_POLL_STRATEGY=legacy flakes

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#8006]
https://grpc-testing.appspot.com/job/gRPC_master/config=asan,language=c,platform=linux/18504/consoleFull

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [gRPC_master_asanitizer_c #1707](https://grpc-testing.appspot.com/job/gRPC_master_asanitizer_c/1707/) but with `GRPC_POLL_STRATEGY=poll`.
