### ISSUE TITLE
Output error log when run phpunit

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#8011]
Will output the follow error log:

	➜  unit_tests git:(master) ✗ phpunit .
	PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

	.E0907 19:54:15.778663000 140735130034176 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.
	.E0907 19:54:15.783962000 140735130034176 client_auth_filter.c:93] Client side authentication failure: Credentials failed to get metadata.
	............................................................... 65 / 96 ( 67%)
	...............................                                   96 / 96 (100%)

	Time: 974 ms, Memory: 15.25MB

	OK (96 tests, 233 assertions)

**Comment by stanley-cheung** [comment]
Are you running the unit tests off master?

**Comment by thinkerou** [comment]
Yea

**Comment by stanley-cheung** [comment]
So there's a mismatch right now. You need to run the unit tests off the v1.0.x branch. master has gone ahead with new feature and won't work with the v1.0.0 extension.

**Comment by stanley-cheung** [comment]
To be exact, you need to run the unit test off the v1.0.0 tag. Even the v1.0.x branch head has gone ahead with some fixes that we haven't released yet.

**Comment by thinkerou** [comment]
Oh, got it, thanks stanley.
