### ISSUE TITLE
Test that both 'dotnet publish' and 'dotnet run' work well for users targeting netcoreapp.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8012]
For dotnet cli projects that are using the experimental Grpc nugets with support for coreclr (netcoreapp1.0 target).

At least one of the approaches is probably broken.

**Comment by jtattermusch** [comment]
I am testing `dotnet run -f net45` and `dotnet publish -f net45` now and it seems that the native dependencies are not getting copied to the output directory.
https://github.com/dotnet/cli/issues/710

**Comment by apolcyn** [comment]
@jtattermusch, for net45 with dotnet, retried on the examples in https://github.com/grpc/grpc/tree/master/examples/csharp/helloworld-from-cli, and it still seems to work. 
From what I've seen, it only stops copying the native libs when the Microsoft.NETCore.Platforms gets completely taken out of the final dependency graph (same situation it seems as in https://github.com/grpc/grpc/pull/7401). With the Microsoft.NETCore.Platforms though, it seems to be copying on dotnet run and dotnet publish.

**Comment by jtattermusch** [comment]
Ah, I completely forgot about Microsoft.NETCore.Platforms, thanks for reminding me.

**Comment by apolcyn** [comment]
No problem, by the way I tried modifying the example in https://github.com/grpc/grpc/tree/master/examples/csharp/helloworld-from-cli to use the netstandard grpc target of a locally created package, but strangely it seems to stop copying the native library at all when both net45 and netstandard targets are there. Though this might just be a strange issue with my local environment.

**Comment by apolcyn** [comment]
Scratch my above comment, the problem looks like it was with building the local package.

**Comment by jtattermusch** [comment]
So far I've been pretty successful with running distribtests locally:
What works:
-- for `net45` target, both `dotnet build` and `dotnet publish` work correctly and the resulting app works fine.
-- for `netcoreapp1.0` target,  `dotnet build` gives runnable application. For `dotnet publish`, the `runtimes` directory is copied to the output, but we need to update NativeExtension.cs to search in that path as well.
