### ISSUE TITLE
Enable running C# qps worker under CoreCLR

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8015]
To be able to run C# performance tests with the new dotnet.
It probably makes sense to do optimizations on a platform where future of .NET lies.

**Comment by soltanmm-google** [comment]
For discussion on whether or not this is something we care about for 1.1.

**Comment by jtattermusch** [comment]
This is actually already in place for a few weeks now - and coreclr is the default for C# benchmarks. Forgot to close the issue.
