### ISSUE TITLE
Figure out C# shutdown hooks under CoreCLR

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8016]
In .NET45 we use appdomain events to cleanup on shutdown properly. Investigate what is the right thing to do on CoreCLR (where appdomains are not a thing).

**Comment by ysiw** [comment]
System.Runtime.Loader.AssemblyLoadContext has an event named Unloading. Please visit https://github.com/dotnet/corefx/issues/5205 for more information
