### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by markdyousef** [grpc/grpc#8017]
Hi,

I'm trying to a Nodejs app in Docker using the google-cloud module. I keep getting the following error on build:

Error: /usr/src/app/node_modules/grpc/src/node/extension_binary/grpc_node.node: invalid ELF header

Info:
Linux 4.4.19-moby
node v6.4.0
npm  v3.10.3

**Comment by murgatroid99** [comment]
Can you show the log output from installing the npm module in the docker image?

**Comment by markdyousef** [comment]
Sure @murgatroid99 
<img width="592" alt="screen shot 2016-09-12 at 07 12 49" src="https://cloud.githubusercontent.com/assets/9863332/18425270/5d301be8-78b8-11e6-91db-c5870cf7d12b.png">

**Comment by wolmi** [comment]
Any solution?

Same situation I'm trying to execute simple nodejs app in Docker and get this error only by make
`const gcloud = require('google-cloud');`

**Comment by andrewconnell** [comment]
+1 here... I'm using GRPC module, not withing the google-cloud module. Also installed from running `npm install` from within the container to ensure native build on Linux... not using the host's (OSX) version.

**Comment by murgatroid99** [comment]
Those logs don't seem to include `npm install` output. Are you installing the npm package and then copying it into the docker image?

When you install gRPC, it builds or downloads the native extension binary for the current system. If you then take the installed package and move it to a different system or even a different node version, it won't work. I think that running `npm install` in the dockerfile should fix that.

**Comment by wolmi** [comment]
Yes I run `npm install` the problem was to mount current app folder to docker working dir, because of that the node_modules folder was my local folder with modules compiled for OSX.

The solution was unmount the working dir and re-build the image.

**Comment by vjpai** [comment]
Closing as there was a solution that didn't involve gRPC.

**Comment by andela-jmuli** [comment]
I was facing a similar issue but with `npm install` included as a step on my Dockerfile. My issue was fixed after I deleted my node_modules folder and built the image again. A conditional statement on my docker-compose was causing docker to build the image using the node_modules built on my Mac

**Comment by edsonhor** [comment]
Great, This works for mee too

**Comment by edsonhor** [comment]
had this issue in pcf cloud foundry and I deleted my node_module package
