### ISSUE TITLE
python: grpc.secure_channel "Creates an insecure Channel to a server."

### ISSUE THREAD

**Issue by jerjou** [grpc/grpc#8020]
Documentation for the `secure_channel` method is [incorrect](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L1196)

**Comment by nathanielmanistaatgoogle** [comment]
Thank you for the report! This was also reported in [issue 7791](https://github.com/grpc/grpc/issues/7791) and has been fixed.
