### ISSUE TITLE
grpc-tools package is missing a README

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#8025]
https://www.npmjs.com/package/grpc-tools is missing a README file. 
We should add a readme that explains how to use this package and generate .js files from proto definitions. 

This needs to be applied to 1.0.x branch,
Related to  grpc/grpc.github.io#376
/cc @LisaFC

**Comment by LisaFC** [comment]
How substantial does this need to be? Can we just give a short description, example of a command line generating code, and then point the users at our Quickstart?

**Comment by markmandel** [comment]
I personally feel that this would be sufficient

**Comment by AspirinSJL** [comment]
This one is really an old one. Do we still want it?

**Comment by hsaliak** [comment]
The readme is still missing, and the package is regularly updated, so I would say that it's still valuable to do.

**Comment by AspirinSJL** [comment]
@murgatroid99 Please try to fix this, thanks!
