### ISSUE TITLE
PHP cc1: 错误：无法识别的命令行选项“-std=c11” cc1: warnings being treated as errors cc1: 错误：无法识别的命令行选项“-Wno-parentheses-equality”

### ISSUE THREAD

**Issue by tianye** [grpc/grpc#8032]
[root@vagrant-centos6 ~]# pecl install grpc
downloading grpc-1.0.0.tgz ...
Starting to download grpc-1.0.0.tgz (1,909,997 bytes)
.....................................done: 1,909,997 bytes
884 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /tmp/pear/install/pear-build-rootibEBJe/grpc-1.0.0
running: /tmp/pear/install/grpc/configure --with-php-config=/usr/local/php/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable grpc support... yes, shared
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /tmp/pear/install/pear-build-rootibEBJe/grpc-1.0.0/libtool --mode=compile cc -Wall -Werror     -Wno-parentheses-equality -Wno-unused-value -std=c11     -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/tmp/pear/install/grpc -DPHP_ATOM_INC -I/tmp/pear/install/pear-build-rootibEBJe/grpc-1.0.0/include -I/tmp/pear/install/pear-build-rootibEBJe/grpc-1.0.0/main -I/tmp/pear/install/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/tmp/pear/install/grpc/include -I/tmp/pear/install/grpc/src/php/ext/grpc -I/tmp/pear/install/grpc/third_party/boringssl/include  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/install/grpc/src/php/ext/grpc/byte_buffer.c -o src/php/ext/grpc/byte_buffer.lo
mkdir src/php/ext/grpc/.libs
 cc -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/tmp/pear/install/grpc -DPHP_ATOM_INC -I/tmp/pear/install/pear-build-rootibEBJe/grpc-1.0.0/include -I/tmp/pear/install/pear-build-rootibEBJe/grpc-1.0.0/main -I/tmp/pear/install/grpc -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/tmp/pear/install/grpc/include -I/tmp/pear/install/grpc/src/php/ext/grpc -I/tmp/pear/install/grpc/third_party/boringssl/include -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/install/grpc/src/php/ext/grpc/byte_buffer.c  -fPIC -DPIC -o src/php/ext/grpc/.libs/byte_buffer.o
cc1: 错误：无法识别的命令行选项“-std=c11”
cc1: warnings being treated as errors
cc1: 错误：无法识别的命令行选项“-Wno-parentheses-equality”
make: *** [src/php/ext/grpc/byte_buffer.lo] 错误 1
ERROR: `make' failed
[root@vagrant-centos6 ~]#

**Comment by thinkerou** [comment]
Please tell the version of your gcc, maybe you should upgrade gcc.

**Comment by stanley-cheung** [comment]
Yes CentOS6 is not well supported without any upgrades. PHP is stuck at 5.3.3, which has long been unsupported. gcc is at 4.4 and libtool is at 2.2. All of which have been pretty old. 

I managed to upgrade PHP to 5.5, gcc to 4.8 and libtool to 2.4 in CentOS6 and I am able to compile the grpc extension from source (by cloning this repo). 

```
libtool: install: cp ./.libs/grpc.so /home/stanleycheung/grpc/src/php/ext/grpc/modules/grpc.so
libtool: install: cp ./.libs/grpc.lai /home/stanleycheung/grpc/src/php/ext/grpc/modules/grpc.la
libtool: finish: PATH="/opt/rh/devtoolset-2/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/stanleycheung/bin:/sbin" ldconfig -n /home/stanleycheung/grpc/src/php/ext/grpc/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /home/stanleycheung/grpc/src/php/ext/grpc/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
oDon't forget to run 'make test'.

[stanleycheung@stanleycheung-centos6 grpc]$ sudo make install
Installing shared extensions:     /usr/lib64/php/modules/

[stanleycheung@stanleycheung-centos6 grpc]$ rpm --query centos-release
centos-release-6-8.el6.centos.12.3.x86_64

[stanleycheung@stanleycheung-centos6 grpc]$ gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


[stanleycheung@stanleycheung-centos6 grpc]$ libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[stanleycheung@stanleycheung-centos6 grpc]$ php -d extension=grpc.so -r "echo Grpc\STATUS_CANCELLED.\"\n\";"
1
```
