### ISSUE TITLE
Problems with nuget 2.8, 2.12, 3.x

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8034]
Recently we started using the command `nuget update -Self` to be able to properly restore System.Interactive.Async (which requires nuget 2.12). The problem with that:

Currently `nuget update -self` actually updates all the ways to nuget 3.4.4.1321, and that one is broken when used on Linux (and probably on Mac) with mono.

when trying to do `nuget restore Grpc.sln` with the newest nuget, one gets an error:

```
MSBuild auto-detection: using msbuild version '4.0' from '/usr/lib/mono/4.5'.
MsBuild.exe does not exist at '/usr/lib/mono/4.5/msbuild.exe'.
```

See issue https://github.com/NuGet/Home/issues/3085

If one installs mono from the latest debian packages, it already contains nuget 2.12, so no update step is necessary. One other hand, some users might have a pre 2.12 version of nuget installed and then they won't  be able to restore System.Interactive.Async.

So ideally, we would need a command that updates nuget to 2.12 version but doesn't pick up the 3.x. AFAIK, no such command exists.

**Comment by jtattermusch** [comment]
FYI @apolcyn

**Comment by apolcyn** [comment]
For the Grpc.sln restore failure, it looks like the nuget 3.4 drops support for solution restore, and I guess things just have to be restored project by project. Changed tests to do this in `pre_build_csharp.sh` and the bat file (which will work old and new versions).

If we can just get 2.12 through mono though, I think changing to upgrade mono rather than `nuget update -self` would be better (but last I saw, the latest nugets available via apt-get gave 2.8).

Unfortunately I'm unaware of any way to upgrade just to 2.12, or even a place to curl it from. But I do think this would be best if possible.

**Comment by apolcyn** [comment]
Unfortunately there is also a problem with nuget 2.12 though, in that for some reason, when installing the `Grpc.Tools` package with it, the resulting package only contains the `tools/windows_x64` and tools/windows_x86` folders, no matter which OS is in use. This problem doesn't appear when installing with the 3.4 nuget client though.

**Comment by jtattermusch** [comment]
ok, so we can't use 2.12 nor 3.4 :-) I think for now 2.12 is lesser of two evils because it at least lets us restore the solution and build.

Would nuget 3.2 work?

**Comment by apolcyn** [comment]
I think we can download nuget 3.2 for windows from the distributions page, but I'm unaware of any way to get it on OS X or linux - I haven't tried 3.2 though this could be best.

**Comment by jtattermusch** [comment]
Downloaded nuget.exe file works on all platforms - it's a .NET assembly.
`mono nuget.exe` just works on both linux and mac.

The problem with 2.12 is that it is not available for download (or I wasn't able to find it at least).

**Comment by vjpai** [comment]
@apolcyn and @jtattermusch can this bug be closed?

**Comment by jtattermusch** [comment]
Fixed by migrating to new .csproj projects: https://github.com/grpc/grpc/pull/10480
