### ISSUE TITLE
Have grpc_python_plugin place generated code elements inside try/except blocks?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#8056]
A use case of @bjwatson and @geigerj has them editing the `_pb2.py` files generated for gRPC and placing the gRPC-bits inside `try`/`except` blocks so that the code can be imported and the message classes used in contexts in which gRPC is unavailable.

We could simplify their process by altering our plugin to put its code elements inside `try`/`except` blocks. Is this something we want to do? It would raise our system complexity, and I do so love code that either fails on import or, if import of it succeeded, can be counted upon to work.

@haberman, @soltanmm-google, @kpayson64: any thoughts?

**Comment by kpayson64** [comment]
In my opinion, the cleanest way to solve this problem in the long term is to support code generation that splits protobuf code and grpc code into separate files.  I think ruby does something like that, but I'm not sure.

In the short term, I agree with your second point, and would avoid introducing non-fail-fast behavior.

**Comment by bjwatson** [comment]
@kpayson64 You're correct. That is the way that Ruby works.

**Comment by soltanmm-google** [comment]
I believe I'm to blame for this; I'd originally thought it cleaner to enforce a 1:1 relationship between `.proto` and generated code file. The 1:N relationship of other languages broke the spirit, in my opinion, of what a single code unit in a language *is*. So, my stance is basically that languages are special, and, "If you want to use a proto for multiple things that don't compile and run together where you want to compile and run them, then they shouldn't be in the same proto file."

But if that's not how the zeitgeist goes then it's not how the zeitgeist goes.

**Comment by nathanielmanistaatgoogle** [comment]
This was recently done in [pull request 8246](https://github.com/grpc/grpc/pull/8246) and will be included in gRPC Python 1.1 and later.

**Comment by bjwatson** [comment]
Great! Thanks.
