### ISSUE TITLE
How to close the SSL/TLS ---objective-c?

### ISSUE THREAD

**Issue by YioMidd** [grpc/grpc#8057]
I got the error like this:

```
E0910 10:06:54.927303000 6142160896 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0910 10:06:54.927560000 6142160896 handshake.c:128] Security handshake failed: {"created":"@1473473214.927514000","description":"Handshake failed","file":"/Users/xxxx/xxxxx/xxxx/Pods/gRPC-Core/src/core/lib/security/transport/handshake.c","file_line":264,"tsi_code":
```

then use the following code before connecting, is useful?

```
[GRPCCall useInsecureConnectionsForHost:kHostAddress];
Connector *clientConnector = [Connector serviceWithHost:kHostAddress];
```

**Comment by YioMidd** [comment]
@jcanizales

**Comment by jcanizales** [comment]
Craig / Julien:
* What does that error mean? (`Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.`)
* How can the message be reworded so it's actionable?

**Comment by jboeuf** [comment]
I'm a bit confused by this:

[GRPCCall useInsecureConnectionsForHost:kHostAddress];

Are we using an insecure connection here instead of SSL? How does the
SSL code get triggered?

**Comment by YioMidd** [comment]
@jcanizales I can't also understand.  Our server does not support https, so i use the above API try to close the SSL.
When add that code, non the above error, but print a another error, like this:
```
error :Error Domain=io.grpc Code=1 "context canceled" UserInfo={io.grpc.TrailersKey={
}, NSLocalizedDescription=context canceled, io.grpc.HeadersKey={
}}
```
so, use the ``useInsecureConnectionsForHost:`` is right? If not, has any API or properties to set insecure?

**Comment by jcanizales** [comment]
@YioMidd if your server doesn't support SSL, then the code you pasted above is correct:

```objective-c
[GRPCCall useInsecureConnectionsForHost:kHostAddress];
Connector *clientConnector = [Connector serviceWithHost:kHostAddress];
```

Make sure to call `useInsecureConnectionsForHost:kHostAddress` *before* making any RPC to `kHostAddress` (because you don't want a secure connection to be opened by default).

I tried searching for the `"context canceled"` error message in the gRPC repository, but GitHub search can't find that message. I suspect it might come from the server. What language is your server written in, and what version of gRPC?

@jboeuf - I understand then that the `Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.` error message is printed when an SSL connection is attempted on a non-SSL server?

**Comment by YioMidd** [comment]
@jcanizales You're right, the ``"context canceled"``error message come from our server.  Then there is a problem I confused. ``context canceled``means the client cancel the connection, but I didn't call any cancel the connection API, and then sometimes client received a successful response message before ``context canceled`` error message.  The console printed like this:
```
2016-09-10 13:51:20.003 MyProject[5025:1913758] rank:0  length:1  // response data
2016-09-10 13:51:20.007 MyProject[5025:1913758] error :Error Domain=io.grpc Code=1 "context canceled" UserInfo={io.grpc.TrailersKey={
}, NSLocalizedDescription=context canceled, io.grpc.HeadersKey={
}}
```

**Comment by jcanizales** [comment]
Is your server written in Go? I found someone getting the same error message when calling the Go gRPC server: https://github.com/grpc/grpc/issues/7666

**Comment by vjpai** [comment]
I don't see any discussion in 2 months; has this been solved or worked-around? Is there any reason that the issue is still needed?

**Comment by YioMidd** [comment]
Oh, has been solved...I'll close it.   thx

**Comment by acoroian** [comment]
How was this solved? im getting this with version 1.0.2 objcective c  with 1.0.5 on go server

**Comment by KanybekMomukeyev** [comment]
@YioMidd Same here, go 1.7.1 and swift 3, what is the solution???

**Comment by jcanizales** [comment]
@iamqizhao are you still Go-gRPC-guy?

**Comment by muxi** [comment]
gRPC ObjectiveC v1.1.0 has been released. Could you please give that a try?

**Comment by jcanizales** [comment]
The common denominator in these reports is the Go server, from which the error message is coming (see https://github.com/grpc/grpc/issues/8057#issuecomment-246786026 ).

**Comment by muxi** [comment]
I see. @menghanl is handling Go server now. He is going to take a look.

**Comment by menghanl** [comment]
gRPC-go uses the go official tls package: https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go#L172

Could there be a mistake in the config?

**Comment by jcanizales** [comment]
@acoroian , @KanybekMomukeyev , do you have a way for @menghanl to reproduce and investigate? Neither https://github.com/grpc/grpc/issues/7666 nor https://github.com/coreos/etcd/issues/5213 do.

**Comment by acoroian** [comment]
@jcanizales on my side the issue was that the server was using a new eliptical curve certificate instead of using rsa. as soon as we used an rsa cert things started working correctly. Did not have to do anything on the client side.

**Comment by KanybekMomukeyev** [comment]
@jcanizales , @menghanl , @muxi , @acoroian 
// This is how i generate key and certificate

```
openssl genrsa -out ssl.key 2048
openssl req -new -key ssl.key -out ssl.csr -subj "/CN=localhost"
openssl x509 -req -days 365 -in ssl.csr -signkey ssl.key -out ssl.crt
```


// ------- STARTING GRPC SERVER -------

```
certFile   = flag.String("cert_file", "certfiles/ssl.crt", "The TLS cert file")
keyFile    = flag.String("key_file", "certfiles/ssl.key", "The TLS key file")

creds, err := credentials.NewServerTLSFromFile(*certFile, *keyFile)
lis, err = net.Listen("tcp", port)
if err != nil {
	log.Fatalf("failed to listen: %v", err)
}
grpcServer = grpc.NewServer(grpc.Creds(creds))
println("Listen on " + port + " with TLS")
```


// ------- TESTED WITH GOLANG GRPC CLIENT, EVERYTHING IS OK -------
```
creds, err := credentials.NewClientTLSFromFile("../certfiles/ssl.crt", "localhost")
if err != nil {
	println("Failed to create TLS credentials %v", err)
}

conn, err := grpc.Dial(address, grpc.WithTransportCredentials(creds))
if err != nil {
	println("did not connect: %v", err)
}

defer conn.Close()
// Creates a new CustomerClient
client := pb.NewRentautomationServiceClient(conn)
```


// ------ NOW TRYING WITH SWIFT/OBJECTIVE 1.0.2 CLIENT -------
ERROR ON IOS CLIENT SIDE:

> error ==> Optional(Error Domain=io.grpc Code=14 "{"created":"@1486449289.295385000","description":"EOF","file":"/Users/kanybek/Desktop/rentautomation/Pods/gRPC-Core/src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}" UserInfo={io.grpc.TrailersKey={
> }, io.grpc.HeadersKey={
> }, NSLocalizedDescription={"created":"@1486449289.295385000","description":"EOF","file":"/Users/kanybek/Desktop/rentautomation/Pods/gRPC-Core/src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}})

ERROR ON SERVER GRPC SIDE:

> grpc: Server.Serve failed to complete security handshake from "192.168.0.22:50885": tls: first record does not look like a TLS handshake

**Comment by jboeuf** [comment]
Re @acoroian 
Thanks for the report. Yes, by default we don't support non-RSA cipher suites on the C core side. We should probably add ECDHE_ECDSA support for this stack.

**Comment by jcanizales** [comment]
@KanybekMomukeyev that looks like a different error than what @YioMidd was getting.

**Comment by Jose-CF** [comment]
I am experiencing this problem with Nuget.exe trying to establish an ssl connection from Linux, apparently using mono. Any ideas?

**Comment by jcanizales** [comment]
Hey @jboeuf, will #9630 fix this?

**Comment by jboeuf** [comment]
I don't know about the specific problem from @Jose-CF (I have no indication that it is the same lack of ECDSA certs support) but yes, #9630 will fix the issue for @acoroian.

**Comment by nsucsd** [comment]
@jcanizales  I am also getting the same error with gRPC (Release 1.8.2).

`E1228 09:48:55.611283000 123145401966592 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.`

My server is written in Java and Client is in Objective-C.

I am using Xcode, Objective-C and gRPC to make an RPC call to an AWS EC2 server. 
I am not sure what is causing this error.
-  Do I need some kind of SSL certificate in my Xcode Project to talk to a remote server?

**Comment by muxi** [comment]
Is the issue above still active? The problem is usually observed when you are not using the newest release.

**Comment by kevin-zhaotk** [comment]
@muxi I still have this issue. the error message is: Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Environment:
    Client: Xcode, Objective-C and gRPC 1.11.0, BoringSSL 10.0.2
    Server: Java with OpenSSL 1.0.1e-15.el6.x86_64

I tried to replace BoringSSL with OpenSSL at client side, but failed in compile stage;
so how can I fix this issue?

**Comment by muxi** [comment]
The error message is a bit misleading; from my experience quite a few issues end up showing this message. The best thing to do is to get some grpc trace logs (with [environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)) and analyze some more verbose error messages in there.

**Comment by mushtaque87** [comment]
Took the latest  
 pod 'SwiftGRPC' 
 pod 'SwiftProtobuf'
version using pod update and it got fixed .

Installing BoringSSL 10.0.6 (was 10.0.5 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing SwiftGRPC 0.5.1 (was 0.4.3 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing gRPC-Core 1.12.0 (was 1.11.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing Realm 3.7.6 (was 3.7.4 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing RealmSwift 3.7.6 (was 3.7.4 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)

Then all i need was create the session/service with my certificate.

let certPath = Bundle.main.url(forResource: "XYZ", withExtension: "pem")!
        let certificate = try! String(contentsOf: certPath)
        service = Pronounce_PronounceServiceClient(address: Constants.ServerApi.grpcBaseUrl, certificates: certificate)
