### ISSUE TITLE
C# centos7 distrib test fails

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#8070]
Tried looking into the centos7 distrib test issue. I think that it's an issue with the latest nuget 2.12 not being signed, and so not being able to connect to the secured nuget feed, as it complains about not being able to connect to the https nuget feed when running `nuget update`, for example.

Have not had any success as of yet in obtaining a signed/recognized nuget on centos7 though.

**Comment by jtattermusch** [comment]
I have no idea why signedness/unsignedness or an rpm package would be related to nuget not being able to connect to a secure feed. Perhaps some certificates are missing in the centos7 installation?

**Comment by apolcyn** [comment]
Yeah from https://github.com/mono/website/blob/gh-pages/docs/getting-started/install/linux/index.md, saw that it suggests installing the "ca-certificates-mono" package to get missing certs, which unfortunately doesn't seem to be available on centos7. Their other suggestions, including the `mozroots --import --sync` for older mono, didn't seem to work either

**Comment by jtattermusch** [comment]
It turns out that something is wrong with mono installation on centos7 (unrelated to gRPC).

Issues https://bugzilla.xamarin.com/show_bug.cgi?id=42820 redirects to https://bugzilla.xamarin.com/show_bug.cgi?id=41953, which suggests a workaround. 
Create PR #8157 to fix the test.

**Comment by vjpai** [comment]
Closing as there is a workaround and the PR to fix the test has been merged.
