### ISSUE TITLE
Enable building of Python gRPC library with Bazel.

### ISSUE THREAD

**Issue by adarob** [grpc/grpc#8079]
This is currently made difficult by the fact that there is not a Bazel build rule for compiling the Cython code.

**Comment by adarob** [comment]
@curtishawthorne

**Comment by robertwb** [comment]
Or filing C extension code of any kind. The closest advice I've been able to find is 

https://github.com/bazelbuild/bazel/issues/1475

**Comment by jackwootton** [comment]
This Issue remains open, but it's unclear what the status is. Is Bazel going to get it's own py_proto_library? Currently, what is the recommended way to gRPC and Python with Bazel?

**Comment by pcj** [comment]
We have this at least preliminarily working recently and a few people using it, welcome to try it out.

https://github.com/pubref/rules_protobuf/tree/master/python

**Comment by jackwootton** [comment]
Thanks @pcj ...I have used that, but was looking for official support from either GRPC or Bazel.

**Comment by nathanielmanistaatgoogle** [comment]
@jackwootton: I _think_ Bazel will be getting its own `py_proto_library`? Or if it does, one provided by [google/protobuf](https://github.com/google/protobuf) will be the official one? And there is no current recommended way to use gRPC Python with Bazel; while we're excited about fixing this issue, serious work on our part addressing it has not yet even begun. (Of course we're happy to hear about success that others are having.)

**Comment by nathanielmanistaatgoogle** [comment]
Followers and fans of this issue who may not have heard through any other channel: [@ghostwriternr is actively working on building gRPC Python with Bazel](https://summerofcode.withgoogle.com/projects/#6482576244473856).

**Comment by samuela** [comment]
Any update on this line of work?

**Comment by srini100** [comment]
@ghostwriternr, is this [document](https://github.com/grpc/grpc/blob/master/summerofcode/2018/naresh.md) up to date with the current state of your project?

**Comment by ghostwriternr** [comment]
@samuela e1210f7 introduced most of the changes needed to build the 'grpcio' package, but I haven't been able to add all the tests in place right now yet. I have added some changes to #16335 today, which if merged, should cover a good majority of them. This project is still a WIP and is yet to cover gRPC testing, health checking, reflection and tools. Bazel still has a lot of issues with Python 2 vs 3 as well that need to be ironed out.

@srini100 It is! I'll keep updating the '[Pending PRs](https://github.com/grpc/grpc/blob/master/summerofcode/2018/naresh.md#pending-prs)' and '[Known issues](https://github.com/grpc/grpc/blob/master/summerofcode/2018/naresh.md#known-issues)' section as and when they are resolved.

**Comment by samuela** [comment]
@ghostwriternr Ah yes... I pulled out quite a bit of hair this summer over blaze's python 2 vs 3 issues. My understanding is that @brandjon has been working on this: https://github.com/bazelbuild/bazel/issues/3871

**Comment by variantf** [comment]
Any update for this? I have been waiting for this for about one year

**Comment by nicolasnoble** [comment]
You need to realize that you are asking for a feature depending on another project that does not have a stable release yet. Until bazel is released as a stable 1.0 version, using it is basically targeting a fast moving target. Bazel might be public since a long time now, but until it gets to the point where it stops making breaking changes every few weeks, its support from us can only be best effort.

**Comment by vlasenkoalexey** [comment]
Spent few hours trying to make py_proto_library and py_grpc_library rules work for https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/storage/v1beta1/BUILD.bazel without much success. I can generate python using commands bazel is running manually, but for some reason build fails. Would appreciate if this was fixed.

**Comment by gnossen** [comment]
@vlasenkoalexey Do you have any error logs? There's a test of those rules with its own `WORKSPACE` [here](https://github.com/grpc/grpc/blob/master/bazel/test/python_test_repo/BUILD).

**Comment by gnossen** [comment]
Quite a bit of work has gone into Bazel support for gRPC Python over the past few months, so this thread is in need of an update. As of this moment, I believe we have all of the components necessary for "Bazel support." What I'd like before closing out this issue is validation from an external user. If, for example, we clear up @vlasenkoalexey 's issue and verify that their use cases are well served, I would feel comfortable closing out.

**Comment by vlasenkoalexey** [comment]
Sure, here is what I see when trying to refer bigquerystorage_py_grpc rule defined in remote repository:
INFO: Analyzed 83 targets (0 packages loaded, 0 targets configured).
INFO: Found 83 targets...
SUBCOMMAND: # //tensorflow_io/bigquery:_bigquerystorage_py_proto_codegen [action 'ProtocInvocation tensorflow_io/bigquery/arrow_pb2.py']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/k8-opt/bin' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' tensorflow_io/bigquery/arrow.proto tensorflow_io/bigquery/avro.proto tensorflow_io/bigquery/read_options.proto tensorflow_io/bigquery/storage.proto tensorflow_io/bigquery/table_reference.proto)
SUBCOMMAND: # //tensorflow_io/bigquery:_bigquerystorage_py_grpc_grpc_codegen [action 'ProtocInvocation tensorflow_io/bigquery/arrow_pb2_grpc.py']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--plugin=protoc-gen-PLUGIN=bazel-out/host/bin/external/com_github_grpc_grpc/src/compiler/grpc_python_plugin' '--PLUGIN_out=grpc_2_0:bazel-out/k8-opt/bin' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' tensorflow_io/bigquery/arrow.proto tensorflow_io/bigquery/avro.proto tensorflow_io/bigquery/read_options.proto tensorflow_io/bigquery/storage.proto tensorflow_io/bigquery/table_reference.proto)
ERROR: /v/tensorflow_io/bigquery/BUILD:38:1: ProtocInvocation tensorflow_io/bigquery/arrow_pb2_grpc.py failed (Exit 1) protoc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/sandbox/processwrapper-sandbox/23/execroot/org_tensorflow_io && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--plugin=protoc-gen-PLUGIN=bazel-out/host/bin/external/com_github_grpc_grpc/src/compiler/grpc_python_plugin' '--PLUGIN_out=grpc_2_0:bazel-out/k8-opt/bin' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' tensorflow_io/bigquery/arrow.proto tensorflow_io/bigquery/avro.proto tensorflow_io/bigquery/read_options.proto tensorflow_io/bigquery/storage.proto tensorflow_io/bigquery/table_reference.proto)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
google/cloud/bigquery/storage/v1beta1/arrow.proto:27:9: "google.cloud.bigquery.storage.v1beta1.ArrowSchema.serialized_schema" is already defined in file "tensorflow_io/bigquery/arrow.proto".
google/cloud/bigquery/storage/v1beta1/arrow.proto:25:9: "google.cloud.bigquery.storage.v1beta1.ArrowSchema" is already defined in file "tensorflow_io/bigquery/arrow.proto".
google/cloud/bigquery/storage/v1beta1/arrow.proto:33:9: "google.cloud.bigquery.storage.v1beta1.ArrowRecordBatch.serialized_record_batch" is already defined in file "tensorflow_io/bigquery/arrow.proto".
google/cloud/bigquery/storage/v1beta1/arrow.proto:36:9: "google.cloud.bigquery.storage.v1beta1.ArrowRecordBatch.row_count" is already defined in file "tensorflow_io/bigquery/arrow.proto".
google/cloud/bigquery/storage/v1beta1/arrow.proto:31:9: "google.cloud.bigquery.storage.v1beta1.ArrowRecordBatch" is already defined in file "tensorflow_io/bigquery/arrow.proto".
google/cloud/bigquery/storage/v1beta1/avro.proto:28:10: "google.cloud.bigquery.storage.v1beta1.AvroSchema.schema" is already defined in file "tensorflow_io/bigquery/avro.proto".
google/cloud/bigquery/storage/v1beta1/avro.proto:25:9: "google.cloud.bigquery.storage.v1beta1.AvroSchema" is already defined in file "tensorflow_io/bigquery/avro.proto".
google/cloud/bigquery/storage/v1beta1/avro.proto:34:9: "google.cloud.bigquery.storage.v1beta1.AvroRows.serialized_binary_rows" is already defined in file "tensorflow_io/bigquery/avro.proto".
google/cloud/bigquery/storage/v1beta1/avro.proto:37:9: "google.cloud.bigquery.storage.v1beta1.AvroRows.row_count" is already defined in file "tensorflow_io/bigquery/avro.proto".
google/cloud/bigquery/storage/v1beta1/avro.proto:32:9: "google.cloud.bigquery.storage.v1beta1.AvroRows" is already defined in file "tensorflow_io/bigquery/avro.proto".
google/cloud/bigquery/storage/v1beta1/read_options.proto:29:19: "google.cloud.bigquery.storage.v1beta1.TableReadOptions.selected_fields" is already defined in file "tensorflow_io/bigquery/read_options.proto".
google/cloud/bigquery/storage/v1beta1/read_options.proto:40:10: "google.cloud.bigquery.storage.v1beta1.TableReadOptions.row_restriction" is already defined in file "tensorflow_io/bigquery/read_options.proto".
google/cloud/bigquery/storage/v1beta1/read_options.proto:24:9: "google.cloud.bigquery.storage.v1beta1.TableReadOptions" is already defined in file "tensorflow_io/bigquery/read_options.proto".
tensorflow_io/bigquery/storage.proto:21:1: Import "google/cloud/bigquery/storage/v1beta1/arrow.proto" was not found or had errors.
tensorflow_io/bigquery/storage.proto:22:1: Import "google/cloud/bigquery/storage/v1beta1/avro.proto" was not found or had errors.
tensorflow_io/bigquery/storage.proto:23:1: Import "google/cloud/bigquery/storage/v1beta1/read_options.proto" was not found or had errors.
tensorflow_io/bigquery/storage.proto:161:5: "google.cloud.bigquery.storage.v1beta1.AvroSchema" seems to be defined in "tensorflow_io/bigquery/avro.proto", which is not imported by "tensorflow_io/bigquery/storage.proto".  To use it here, please add the necessary import.
tensorflow_io/bigquery/storage.proto:164:5: "google.cloud.bigquery.storage.v1beta1.ArrowSchema" seems to be defined in "tensorflow_io/bigquery/arrow.proto", which is not imported by "tensorflow_io/bigquery/storage.proto".  To use it here, please add the necessary import.
tensorflow_io/bigquery/storage.proto:204:3: "google.cloud.bigquery.storage.v1beta1.TableReadOptions" seems to be defined in "tensorflow_io/bigquery/read_options.proto", which is not imported by "tensorflow_io/bigquery/storage.proto".  To use it here, please add the necessary import.
tensorflow_io/bigquery/storage.proto:291:5: "google.cloud.bigquery.storage.v1beta1.AvroRows" seems to be defined in "tensorflow_io/bigquery/avro.proto", which is not imported by "tensorflow_io/bigquery/storage.proto".  To use it here, please add the necessary import.
tensorflow_io/bigquery/storage.proto:294:5: "google.cloud.bigquery.storage.v1beta1.ArrowRecordBatch" seems to be defined in "tensorflow_io/bigquery/arrow.proto", which is not imported by "tensorflow_io/bigquery/storage.proto".  To use it here, please add the necessary import.
INFO: Elapsed time: 0.488s, Critical Path: 0.03s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

Here is a build log file for use case when I refer to remote proto:
INFO: Found 79 targets...
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_grpc_grpc_codegen [action 'CopySourceProto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow.proto']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  /bin/bash -c 'cp external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow.proto bazel-out/k8-opt/bin/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow.proto')
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_grpc_grpc_codegen [action 'CopySourceProto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage.proto']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  /bin/bash -c 'cp external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage.proto bazel-out/k8-opt/bin/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage.proto')
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_grpc_grpc_codegen [action 'CopySourceProto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro.proto']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  /bin/bash -c 'cp external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro.proto bazel-out/k8-opt/bin/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro.proto')
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_grpc_grpc_codegen [action 'CopySourceProto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options.proto']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  /bin/bash -c 'cp external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options.proto bazel-out/k8-opt/bin/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options.proto')
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_grpc_grpc_codegen [action 'CopySourceProto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference.proto']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  /bin/bash -c 'cp external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference.proto bazel-out/k8-opt/bin/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference.proto')
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_proto_codegen [action 'ProtocInvocation external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow_pb2.py']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/k8-opt/bin' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference.proto)
SUBCOMMAND: # @com_google_googleapis//google/cloud/bigquery/storage/v1beta1:_bigquerystorage_py_grpc_grpc_codegen [action 'ProtocInvocation external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow_pb2_grpc.py']
(cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--plugin=protoc-gen-PLUGIN=bazel-out/host/bin/external/com_github_grpc_grpc/src/compiler/grpc_python_plugin' '--PLUGIN_out=grpc_2_0:bazel-out/k8-opt/bin' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=external/com_google_googleapis' '--proto_path=external/com_google_googleapis' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin/external/com_google_protobuf' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' '--proto_path=bazel-out/k8-opt/bin' external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage.proto external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference.proto)
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:182:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow_pb2.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:182:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro_pb2.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:182:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options_pb2.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:182:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage_pb2.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:182:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference_pb2.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:182:1: not all outputs were created or valid
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:187:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/arrow_pb2_grpc.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:187:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/avro_pb2_grpc.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:187:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/read_options_pb2_grpc.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:187:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/storage_pb2_grpc.py' was not created
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/BUILD.bazel:187:1: output 'external/com_google_googleapis/google/cloud/bigquery/storage/v1beta1/table_reference_pb2_grpc.py' was not created
INFO: Elapsed time: 8.047s, Critical Path: 0.07s
INFO: 7 processes: 7 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

I applied my changes to this repository: https://github.com/vlasenkoalexey/io/tree/py_grpc_library_issue
Specifically see this commit: https://github.com/vlasenkoalexey/io/commit/c62f754c206c26836d54755a10a6e551fb9facf2

Build instructions are here: https://github.com/vlasenkoalexey/io/tree/py_grpc_library_issue#python
Hope this helps.

**Comment by nicmcd** [comment]
I'm not seeing very much consistency across languages. In C++, you define a proto_library, then pass that as a dependency to cc_grpc_library. In the linked Python example, you define a proto_library, then create a py_proto_library, then create a py_grpc_library. Furthermore, the py_grpc_library requires a "srcs" attribute of which it is taking the name of the proto_library and in deps it takes the py_proto_library.

What is going on here? Why so convoluted? 

The whole purpose of protobufs and gRPC is to create language agnostic interfaces that have language specific instantiations.

As for it being usable, I can't get the python example working. Here is a link to a very simple project: https://github.com/nicmcd/py_grpc_bazel_test

Building the proto_library works fine. Here is the output of building the py_proto_library:
```
grpc_py_cc_test$ bazel build :helloworld_py_pb2                                                                                                                                               
INFO: Analyzed target //:helloworld_py_pb2 (2 packages loaded, 87 targets configured).                                                                                                                        
INFO: Found 1 target...                                                                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/empty_pb2.py:                                                                                                                     
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/compiler/plugin_pb2.py:                                                                                                           
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/source_context_pb2.py:                                                                                                            
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/field_mask_pb2.py:                                                                                                                
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/descriptor_pb2.py:                                                                                                                
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py:                                                                                                                       
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/duration_pb2.py:                                                                                                                  
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/api_pb2.py:                                                                                                                       
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/wrappers_pb2.py:                                                                                                                  
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/struct_pb2.py:                                                                                                                    
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/timestamp_pb2.py:                                                                                                                 
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/type_pb2.py:                                                                                                                      
external/com_google_protobuf/python: warning: directory does not exist.                                                                                                                                       
Target //:helloworld_py_pb2 up-to-date:                                                                                                                                                                       
  bazel-bin/helloworld_pb2.py                                                                                                                                                                                 
INFO: Elapsed time: 0.446s, Critical Path: 0.20s                                                                                                                                                              
INFO: 15 processes: 15 linux-sandbox.                                                                                                                                                                         
INFO: Build completed successfully, 16 total actions
```
As you can see, it builds successfully but there are a tons of "does not exist" warnings. Very weird.

Here is the output of building the py_grpc_library:
```
grpc_py_cc_test$ bazel build :helloworld_py_pb2_grpc
ERROR: /home/nic/dev/py_grpc_bazel_test/BUILD:16:1: every rule of type _generate_pb2_grpc_src implicitly depends upon the target '@com_github_grpc_grpc//src/compiler:grpc_python_plugin', but this target could not be found because of: error loading package '@com_github_grpc_grpc//src/compiler': in /home/nic/.cache/bazel/_bazel_nic/c021d5a0979ecd2e72d53218a83e1189/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/nic/.cache/bazel/_bazel_nic/c021d5a0979ecd2e72d53218a83e1189/external/upb/bazel/upb_proto_library.bzl: Unable to find package for @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved.
ERROR: Analysis of target '//:helloworld_py_pb2_grpc' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.168s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: @com_github_grpc_grpc// ... (2 packages)
    Fetching @build_bazel_rules_apple; fetching
```
This just fails after the upb library can't resolve the "bazel_version" library.

One more nit-picky critique. For C++ we load "cc_grpc_library". For Python we load "python_rules". Please standardize this. For example all of them should be "<lang>_rules".

**Comment by gnossen** [comment]
@vlasenkoalexey Sorry for the long pause. I just got around to pulling down your repro and messing around with it. The good news is that it's working on master of gRPC, probably due to https://github.com/grpc/grpc/pull/20150. The only changes I made were:

 - Updating your gRPC dependency to master
 - Deleting `//tensorflow_io/bigquery:storage_py_pb2` and `//tensorflow_io/bigquery:storage_py_pb2_grpc` in favor of the versions you patched into `googleapis`. As you surmised, those targets should be in the same package as the `proto_library` target itself.

Also, please take note of the new `grpc_extra_deps()` rule. Using it should clean up your `WORKSPACE` considerably.

Please let me know if there are any other issues.

**Comment by gnossen** [comment]
@nicmcd 

### Inconsistency Between C++ and Python Bazel Rules
In this case, C++ is the odd one out. Take a look at [Go](https://github.com/bazelbuild/rules_go/blob/01c7b1ba59c7a1819f1003cf58400cb3d4f7d22e/tests/legacy/examples/proto/grpc/BUILD.bazel) and [Java](https://github.com/grpc/grpc-java/blob/024a46bd11120e706f2ee8fb10d1cbefc9be9b5a/examples/BUILD.bazel). This pattern is how proto codegen and gRPC codegen rules look in the Google internal codebase. My understanding is that C++ is kept the way it is currently for backward compatibility reasons. I'll let @nicolasnoble speak to that.

It might be feasible to add a C++ rule that mirrors the other languages.

### `py_proto_library` Warnings
[Issue filed.](https://github.com/grpc/grpc/issues/20851) [Potentially related.](https://github.com/protocolbuffers/protobuf/issues/6049)

### `py_grpc_library` Build Failure

Yes, [this is a wart in Bazel](https://github.com/bazelbuild/bazel/issues/1550). When a Bazel project uses a [repository rule](https://docs.bazel.build/versions/master/skylark/repository_rules.html), it forces all of its *transitive* dependents, not just direct dependents to also load that rule. So when one of *our* dependencies adds a repository rule, it forces all of *our* dependents to also use that rule. And it can't be done all in a single macro invocation. There's [a design doc](https://github.com/bazelbuild/bazel/issues/1943) for a feature that will mitigate this problem, [but it appears to currently be on ice](https://github.com/bazelbuild/bazel/issues/1943#issuecomment-522488997).

This was (very) recently [made dramatically cleaner](https://github.com/grpc/grpc/pull/20586) by an external contributor. Try calling `grpc_extra_deps()` in your `WORKSPACE`. I've verified that this fixes your minimal repo example. Note that this change is so recent that it's not in any gRPC release yet.

### Rules Filename
I believe that file was written before the `_rules` pattern was even established. gRPC was a *very* early adopter of Bazel. But I think this one can be fixed in a backwards-compatible manner.

**Comment by samuela** [comment]
Bump

**Comment by poweic** [comment]
Any update on this?

**Comment by RicCu** [comment]
Any updates?
