### ISSUE TITLE
Can gRPC support two sockets in a single server ?

### ISSUE THREAD

**Issue by gclouding** [grpc/grpc#8092]
I would like to establish two sockets, using different protocols (for example, one is TCP, and another is UDP ) in a single gRPC server. And I want to select either one for data communication between server and client. 

For example, the client sends a message using the first socket based on TCP protocol, and the server receives the same message using the same socket, and sends it back after processing it.  Then, the client sends another message using the second socket based on UDP protocol, and the server receives the same message using the same socket, and sends if back after processing it. 

Does gRPC support this by slight modification ?  And how ?

**Comment by vjpai** [comment]
Marking this to close since there has been no discussion, but feel free to fix if needed.
