### ISSUE TITLE
gRPC multiple servers

### ISSUE THREAD

**Issue by akamos** [grpc/grpc#8093]
Hi,
we try to find out if gRPC is right for our future development and can't figure out how to use multiple server instances in one client without much overwriting the core library (especially for C++, Python and Java) and without changing the client request system. (maybe to use hooks/interceptors)
How can I add another ip adresses that on failure (server not answer or cancel while request) it tries to connect to the another server automatically? The document about load balancing not really helps or can we cache in a proxy streamed requests?

How Google handle it when a server gets unavailable or a server dies while executing request?

**Comment by nevi-me** [comment]
Hi @akamos, I have a JS and Java implementation of my GRPC server. I use nghttpx to load balance the servers. I don't know if this is what you're looking for? It would be similar to using nginx or haproxy as a load balancer.

**Comment by akamos** [comment]
Hi @nevi-me, 
we already use nghttpx on server side to have only one port open and route the requests to correct grpc server.

Problem:
We would like to have several grpc servers with the same interface. That in a failed request we can use simply another. As failed request I see, 1. a grpc server absolutely not answer, because he is not alive or 2. a grpc server that dies while request.

We don't want to try/catch each made request in client. We would like to have some own wrapper/interceptor that hooks into the request and on fail sends it to the another server. Like a stub with several channels.

How to do that correctly? Like to make something looking like this (python example): 
```python
channel = grpc.insecure_channel('172.10.100.1:50051')
channel2 = grpc.insecure_channel('172.10.100.2:50051')
stub = helloworld_pb2.GreeterStub(channel, channel2)
```

**Comment by ryanchou1991** [comment]
+1 Yeah. Could anyone provide some solutions or best practices on running multiple servers? I have met the same case which was required to run multiple server instances to serve increase scale client–requests?

**Comment by alileza** [comment]
@akamos didn't sure if this fix your problem or not, but i'm using `nginx stream` module. it's automatically reconnect to another server in the upstream whenever connection broken, and it works well for me. i wrote blog post of how i implement it here http://alileza.xyz/grpc-load-balancing-using-nginx/

**Comment by ryanchou1991** [comment]
@alileza could nginx be the load-balancer for the gRPC servers ?

**Comment by alileza** [comment]
@ryanchou1991 it seems so, using at least version 1.9.0 along with `ngx_stream_core_module`

**Comment by ryanchou1991** [comment]
@alileza cool, Thanks for your solution. I have searched for a long time. The nghttp2 could support gRPC. I have no idea nginx could also be the load-balancer for gRPC-servers with the module you mention above.

**Comment by amitripshtos** [comment]
I created an example for server side automatic load balancing using docker:
https://github.com/amitripshtos/grpc-docker-lb

Hope it will help you guys to figure out how it works using nghttp2!

**Comment by ryanchou1991** [comment]
@amitripshtos Awesome Job 👍
