### ISSUE TITLE
grpc c++ as a project dependency

### ISSUE THREAD

**Issue by noahdesu** [grpc/grpc#8097]
What is the recommended approach for handling grpc c++ as a project dependency? Such as building and linking grpc directly into the target application, or using distribution package managers that currently seem to not have up-to-date grpc packages (ie >= 1.0.0).

Are there any examples of existing applications using grpc c++ as a dependency as a guide?

**Comment by nicolasnoble** [comment]
We will have Debian packages published Soon(tm). What is the platform you're looking for ?

**Comment by davehorton** [comment]
I'd like to use those Debian packages.  Any ETA on availability?

**Comment by noahdesu** [comment]
Any guidance on this? The basic thing I'm faced with is how users of my project can deal with the grpc dependency easily. Ideally the development packages would be available with yum/dnf/apt-get/etc. The second option is to use grpc as a submodule, build grpc as a dependency and statically link it. The second is acceptable. Does anyone know of an existing project that is doing this that I could use as an example?

**Comment by sreecha** [comment]
@noahdesu: Sorry that you could not get any help here. Did you find a way to address this ? 
(I am closing this issue as it has been ~1.5 yrs since this was opened)
