### ISSUE TITLE
How to set SetMaxMessageSize / frame size in node.js?

### ISSUE THREAD

**Issue by 1N50MN14** [grpc/grpc#8098]
I'm trying to send about 2MB of binary data but I keep getting the error RESOURCE_EXHAUSTED, when I lower the size of the message to few hundred kb's it works just fine (I'm 100% sure this is what's causing it).

I went through `server.js` line by line - not a single reference on how to accomplish that. 

Help? ;)

**Comment by 1N50MN14** [comment]
any feedback on this issue...?

**Comment by murgatroid99** [comment]
It looks like you can increase the max size of messages that you send by setting the option `"grpc.max_send_message_length"`. That takes an integer value indicating the number of bytes. There is a similar option `"grpc.max_receive_message_length"` for receiving messages.

**Comment by 1N50MN14** [comment]
Thanks @murgatroid99, is that a global setting? as in

```javascript
var grpc = require('grpc');
grpc.max_send_message_length = 1024*1024*1024; //assuming server
```

**Comment by murgatroid99** [comment]
No, it's a server option. So, you would do

```
var server = new grpc.Server({'grpc.max_send_message_length': 1024*1024*1024})
```

I know that looks kind of weird. It's an unfortunate result of how the different parts of gRPC are layered together.

**Comment by 1N50MN14** [comment]
@murgatroid99 Got it, thank you, just glad it can be accomplished alltogether ;) 

Closing issue for now will reopen should I encounter any problems.

**Comment by 1N50MN14** [comment]
closing

**Comment by 1N50MN14** [comment]
@murgatroid99 Sorry how do I pass the client setting given

```javascript
var client = new proto.Service(uri, grpc.credentials.createInsecure())
```
Is that a third argument?

**Comment by murgatroid99** [comment]
Yes, the same options map should be the third argument there.
