### ISSUE TITLE
insecure environment read function 'getenv' used

### ISSUE THREAD

**Issue by eltoro** [grpc/grpc#8104]
I'm using an alpine-node image and libc6-compat to install the grpc node module. It installs fine but when I run my node app I get this:

`D0915 10:27:21.359363112      31 env_linux.c:66]             Warning: insecure environment read function 'getenv' used`

Is there a fix for this?

**Comment by nicolasnoble** [comment]
Not really - the core is warning you that your libc environment doesn't have the GNU extensions for securely reading environment variables: http://man7.org/linux/man-pages/man3/getenv.3.html

At least one of our environment variables is pointing to the list of the root certificates used by gRPC, so being able to read that with the assurance it hasn't been altered is a good thing, hence the warning.


Also, this is a DEBUG-level message. If you have verbosity to that kind of level turned on, you're bound to see a lot of messages.

**Comment by vjpai** [comment]
Marking to close as this is a platform issue.

**Comment by Binarytales** [comment]
I'm seeing this message in my logs even with `GRPC_VERBOSITY="ERROR"`

Let me know if there is anything I can do to help debug this issues for you. This is being set in a Dockerfile for a image that is run on:
- Docker 1.13.
- Node 6.9.5
- Alpine with libc6-compat

**Comment by kaiwu** [comment]
@Binarytales given environmental instructions to an function handling environment is itself contradictory, check `src/core/lib/support/env_linux.c` for the warning

**Comment by lnshi** [comment]
@nicolasnoble  So for Alpine image, what do I need to install?
