### ISSUE TITLE
fatal: repository 'v1.0.0' does not exist

### ISSUE THREAD

**Issue by Zeks** [grpc/grpc#8106]
This error now appears if you try to clone grpc repository with --recursive flag to get it to auto compile protobuf.
Just a couple days ago it worked. Can someone look into it please?

**Comment by nicolasnoble** [comment]
What command are you trying to do exactly ? The v1.0.0 _tag_ definitely exists.

**Comment by nicolasnoble** [comment]
https://github.com/grpc/grpc/tree/v1.0.0

**Comment by Zeks** [comment]
git clone -b --recursive $(curl -L http://grpc.io/release) https://github.com/grpc/grpc

**Comment by Zeks** [comment]
Never mind, I displaced --recursive tag it seems
