### ISSUE TITLE
node: client events for connect/disconnect

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#8117]
Are there any events i can tap into for connection established / dropped on the Node.js GRPC client? Is there a good doc on what's happening under the hood (heartbeats, keep alives, etc.) and how the Node.js client (or a general doc if they're all the same) handles the situation when you call a GRPC method but the connection has been dropped (maybe killed via ELB idle timeout)- does it try to reconnect, does it error, etc.?

**Comment by gazickil** [comment]
Any progress on this one?

**Comment by mostafaeweda** [comment]
The go-away connection semantics is not clear on the client & server - doesn't seem there's any way to resume the calls (unlike https://github.com/rsocket/rsocket/ for example).

**Comment by dtassone** [comment]
What's the status on this issue? How can we monitor the connection state? 
If I stop the server, I'm getting the following exception

```
Error: Endpoint read failed
    at ClientReadableStream._emitStatusIfDone (<my_project>\node_modules\grpc\src\client.js:255:19)
    at ClientReadableStream._receiveStatus (<my_project>\node_modules\grpc\src\client.js:233:8)
    at <my_project>\node_modules\grpc\src\client.js:705:12

```

**Comment by mostr** [comment]
Any updates on that? I'm using node client and when connection gets dropped while streaming from server, I don't see any event I can react to in order to finish/clean up resources no matter how long I keep this running. This seems to be pretty serious as this causes serious memory leaks :/

**Comment by zz85** [comment]
seems like `call.on('cancelled', callback)` works
