### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by gfxcc** [grpc/grpc#8119]
`Undefined symbols for architecture x86_64:
  "_CRYPTO_free", referenced from:
      _peer_property_from_x509_common_name in libgRPC.a(ssl_transport_security.o)
      _add_subject_alt_names_properties_to_peer in libgRPC.a(ssl_transport_security.o)
     (maybe you meant: _CRYPTO_free_ex_data)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      _init_openssl in libgRPC.a(ssl_transport_security.o)
  "_SSL_CTX_callback_ctrl", referenced from:
      _tsi_create_ssl_server_handshaker_factory in libgRPC.a(ssl_transport_security.o)
  "_SSL_CTX_ctrl", referenced from:
      _populate_ssl_context in libgRPC.a(ssl_transport_security.o)
      _tsi_create_ssl_server_handshaker_factory in libgRPC.a(ssl_transport_security.o)
      _ssl_ctx_use_certificate_chain in libgRPC.a(ssl_transport_security.o)
  "_SSL_ctrl", referenced from:
      _create_tsi_ssl_handshaker in libgRPC.a(ssl_transport_security.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I have already install grpc 1.0.0, libprotoc 3.0.0. 
When I try to compile examples in grpc/grpc/example/object-c/helloworld, i met this problem.
Help pls, thanks a lot.

**Comment by nicolasnoble** [comment]
Can you describe the situation a little more? What are the various commands you ran before this, what is your platform, etc?

**Comment by apolcyn** [comment]
cc @jcanizales ?

**Comment by nicolasnoble** [comment]
Bah! Sorry, I read "CSharp" instead of the word "object-c". My bad...

**Comment by jcanizales** [comment]
Hi @gfxcc, as @nicolasnoble said, to be able and help we definitely need the context: What steps did you follow to setup the example, and how did you get to this error (hitting Run in XCode? compiling from the command line? ...)?

**Comment by gfxcc** [comment]
@jcanizales 
I did this on my macbook pro 10.11.6
1. 
I try to run 
$ curl -fsSL https://goo.gl/getgrpc | bash -s -- --with-plugins
but, it told me i have already install 0.14.0
so I uninstall grpc and protoc  , untap grpc/grpc  and run it again, all good.
$ brew uninstall grpc      $brew uninstall google-protobuf
$ brew untap grpc/grpc
(maybe you can modified this script to avoid untap grpc/grpc manually.
I have to do it because https://github.com/grpc/homebrew-grpc/issues/86)

2. I download grpc-master
$ cd ~/Download/grpc-master/example/objective-c/helloworld
$ pod install
it told me "[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 1.0)` depended upon by `HelloWorld`"
so i ran
$ sudo rm -fr ~/.cocoapods/repos/master
$ pod setup
$ pod install
it works~

3.
open HelloWorld.xcworkspace with Xcode (8.0) on mac 10.11.6
hitting run in xocde, it reports those error message.

!!!!!!!!
I follow the same processes on my iMac, it works fine without error. I get confused.
I tried to compile my previous project with grpc 0.14.0 on macbook pro, it works fine.

any hints?

**Comment by muxi** [comment]
Tested on mac 10.11.6 with grpc:master and Xcode 8.0 GM (8A218a) just now and I did not get this error. Try clean up and again?
`$ rm -rf Pods`
`$ rm -rf HelloWorld.xcworkspace`
`$ rm -f Podfile.lock`
`$ pod install`

**Comment by jcanizales** [comment]
It's not a version mismatch with BoringSSL, because e.g. `CRYPTO_free` has been there forever. So for some reason Cocoapods didn't configure your XCode project properly, to tell the linker that gRPC depends on BoringSSL.

**Comment by gfxcc** [comment]
I found something I cannot believe..........

1.
Download grpc/grpc
`
cd ~/Download/grpc-master/example/objc/helloworld
pod install
`
run HelloWorld.xcworkspace by Xcode. try to compile, went to the same errro

2. (follow the previous steps)
`
cp ~/Download/grpc-master/example/objc/helloworld ~/god_knows_where/
`
run `HelloWorld.xcworkspce` in` ~/god_knows_where/helloworld`

everything works fine TOTOTOTTOTOT
I cannot understand why ....
