### ISSUE TITLE
npm install grpc fails with errors building boringssl on Windows 7

### ISSUE THREAD

**Issue by cdaughtr** [grpc/grpc#8121]
Using latest node.js, npm and windows-build-tools using:
install --global --production windows-build-tools

node-pre-gyp ERR! cwd C:\Users\IBM_ADMIN\code\go\src\github.com\jimthematrix\fabric-sdk-nodejs\node_modules\grpc
node-pre-gyp ERR! node -v v6.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\IBM_ADMIN\code\go\src\github.com\jimthematri
x\fabric-sdk-nodejs\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\
Users\IBM_ADMIN\code\go\src\github.com\jimthematrix\fabric-sdk-nodejs\node_modules\grpc\src\node\extension_binary' (1)
npm WARN hfc@0.0.2 No repository field.
npm WARN hfc@0.0.2 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "grpc"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.13.2-pre1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.13.2-pre1 install script 'node-pre-gyp install --fallback-to-build'.

sample WindowsPowerShell output:
C:\Users\IBM_ADMIN\code\go\src\github.com\jimthematrix\fabric-sdk-nodejs\node_modules\grpc\third_party\boringssl\includ
e\openssl/mem.h(85): warning C4028: formal parameter 3 different from declaration (compiling source file ..\third_party
\boringssl\crypto\asn1\t_pkey.c) [C:\Users\IBM_ADMIN\code\go\src\github.com\jimthematrix\fabric-sdk-nodejs\node_modules
\grpc\build\boringssl.vcxproj]
[npm-debug.log.txt](https://github.com/grpc/grpc/files/477101/npm-debug.log.txt)
[WindowsPowerShell-log.txt](https://github.com/grpc/grpc/files/477105/WindowsPowerShell-log.txt)

C:\Users\IBM_ADMIN\code\go\src\github.com\jimthematrix\fabric-sdk-nodejs\node_modules\grpc\third_party\boringssl\includ
e\openssl/mem.h(85): error C2059: syntax error: 'string' (compiling source file ..\third_party\boringssl\crypto\asn1\ta
sn_dec.c) [C:\Users\IBM_ADMIN\code\go\src\github.com\jimthematrix\fabric-sdk-nodejs\node_modules\grpc\build\boringssl.v
cxproj]

**Comment by nicolasnoble** [comment]
The interesting question is why it didn't grab the pre compiled binaries?

**Comment by murgatroid99** [comment]
You are trying to install grpc version 0.13.2-pre1. This is a fairly old pre-release, and we were not publishing precompiled binaries for Node 6 until 0.14.

I would strongly recommend upgrading to our 1.0 release of grpc.

**Comment by cdaughtr** [comment]
I tried 1.0 and it works for me.  We will upgrade to 1.0.

Thank you!
