### ISSUE TITLE
can't install grpcio

### ISSUE THREAD

**Issue by aaron315** [grpc/grpc#8132]
i tried install `sudo pip install grpcio` in ubuntu 14.04;
but     

src/python/grpcio/grpc/_cython/cygrpc.c:10786:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static PyObject *__pyx_pf_4grpc_7_cython_6cygrpc_8Timespec_6infinite_past() {

can't continue ~

**Comment by nathanielmanistaatgoogle** [comment]
`grpcio` is supported to be installable with `pip` 8.0 and later - with what version of `pip` are you working?

**Comment by soltanmm-google** [comment]
That's a compiler warning. That should not cause installation to fail. What is your full failure output?

**Comment by nathanielmanistaatgoogle** [comment]
Closing; this has gone long enough without a response.
