### ISSUE TITLE
Generated code for python is broken if .proto file has package specified in its header.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#814]
Generated code (e.g. for route guide) contains in
protobuf messages in "examples.route_guide_pb2"  and grpc stubs in "route_guide_pb2". That breaks all the code that's trying to use route_guide_pb2.

Workaround is to comment out the "package example;" declaration in the .proto file and then things seem to work.

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed in 40e8cbd1ee57d43755c.
