### ISSUE TITLE
Precompiled cronet framework does not contain armv7 and arm64 architectures

### ISSUE THREAD

**Issue by sercand** [grpc/grpc#8144]
I used [CronetFramework.podspec](https://github.com/grpc/grpc/blob/bb160258407289e9ab0dbb60c7d369c801bb3311/src/objective-c/CronetFramework.podspec) at master branch but it includes only i386 and x86_64 architectures.

```
$ file Cronet 
Cronet: Mach-O universal binary with 2 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64]
Cronet (for architecture i386): Mach-O dynamically linked shared library i386
Cronet (for architecture x86_64):   Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by muxi** [comment]
Hi sercand, CronetFramework is right now for internal test only and not ready for public production. We are working towards that direction but we do not have a timeline right now. Thanks for asking.
