### ISSUE TITLE
gRPC currently insane at head of v1.0.x

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#8150]
At current HEAD of v1.0.x (10c57a03ef939668dc4e0a4ad17e095), I observe the following:
1. Clean `git pull --recurse-submodules upstream v1.0.x`; `git submodule update --init`; `git clean -xdf` to get a nice pristine environment.
2. `make test_python` passes.
3. `./tools/run_tests/run_tests.py --language=python --newline_on_success` passes.
4. `git status` shows no changed files.
5. `./tools/run_tests/run_tests.py --language=sanity --newline_on_success` **fails**.
6. `git status` shows changes to `src/boringssl/err_data.c` and `third_party/protobuf`.
7. `./tools/run_tests/run_tests.py --language=python` **fails**.

Five reactions:
1. It is surprising to me that any invocation of `run_tests.py` has the capacity to alter content under source control; I would expect that `git status` after any `run_tests.py` invocation would display exactly what it displayed before that invocation.
2. This problem seems technically independent of Jenkins but practically compounds the pain we're feeling from Jenkins.
3. This is slowing my getting @thunderboltsid's changes merged; I am going to proceed with my own best judgement and merge what I am confident is safe.
4. I think this problem is happening exactly as described on master as well but I have not independently verified that suspicion.
5. This is release blocking and release blocks scare me.

**Comment by nicolasnoble** [comment]
So, I strongly suggest doing --use_docker when running these tests.

**Comment by jtattermusch** [comment]
Closing for bankruptcy.
