### ISSUE TITLE
carthage support [objective-c]

### ISSUE THREAD

**Issue by SimpleApp** [grpc/grpc#8155]
gRPC has files for cocoapods deployment. Is Carthage deployment in the pipe ?

**Comment by makdharma** [comment]
Carthage support is not in the plan. Are there arguments for/against this?
What is the use case that is not met by Cocoapods?

**Comment by SimpleApp** [comment]
The usual argument for it is that it doesn't affect the project structure using the lib. It's more lightweight. The future system for iOS development should probably be Swift Package Manager though.

**Comment by jcanizales** [comment]
Would a Carthage config be easy to generate automatically from the podspecs?

Are there plans for the Swift PM to support ObjC apps using ObjC libraries?

**Comment by SimpleApp** [comment]
Swift PM does support objective-c and C libraries : https://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/

No idea for generating carthage config from podspecs.

**Comment by jcanizales** [comment]
Is it an acceptable replacement of Cocoapods, for people writing apps solely in ObjC? As in, does it integrate nicely with XCode, etc.

**Comment by sercand** [comment]
[Realm](https://github.com/realm/realm-cocoa/releases) for iOS is written in c++, ObjC and Swift and it does support Carthage. For the Carthage support, just put frameworks into `Carthage.framework.zip` file and attach it to github release.

**Comment by jcanizales** [comment]
I meant SwiftPM in my question, sorry for the confusion.

**Comment by johndpope** [comment]
Going to open a new enhancement ticket to provide a Package.swift
swift package manager to support server side swift development.

**Comment by samskiter** [comment]
Any news on this?

**Comment by muxi** [comment]
We are considering this. No timeline for now though.

**Comment by SebastianThiebaud** [comment]
Hello. I believe this isn't happening then?

**Comment by muxi** [comment]
That is correct. Contribution is welcomed.
