### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by damleak** [grpc/grpc#8162]
Build is failing on fresh clone in Ubuntu

```
[HOSTCXX] Compiling src/compiler/csharp_generator.cc
In file included from ./src/compiler/config.h:37:0,
                 from ./src/compiler/csharp_generator.h:37,
                 from src/compiler/csharp_generator.cc:39:
include/grpc++/impl/codegen/config_protobuf.h:38:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
 #include <google/protobuf/stubs/common.h>
```

**Comment by soltanmm-google** [comment]
Did you `git submodule update --init`?
If no, please try it. If yes, what are the commands you used starting from the clone and ending in the failure?

**Comment by damleak** [comment]
Issued the standard commands mentioned in instructions. Following is the sequence of commands.

```
$ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ make
```
The make fails with protobuf related error.

**Comment by thinkerou** [comment]
You should make protobuf manual firstly.

**Comment by damleak** [comment]
It was working two weeks back. Now it doesn't. The following paragraph in INSTALL.md does not make sense. It is completely misleading.

> ##Protoc
> 
> By default gRPC uses [protocol buffers](https://github.com/google/protobuf),
> you will need the `protoc` compiler to generate stub server and client code.
> 
> If you compile gRPC from source, as described below, the Makefile will
> automatically try and compile the `protoc` in third_party if you cloned the 
> repository recursively and it detects that you don't already have it
> installed.

**Comment by thinkerou** [comment]
When you run `git submodule update --init` after that it will update `protobuffer`, so you need re-compile `protobuffer`. Maybe you should try it. Thanks.

**Comment by damleak** [comment]
I have successfully built ```gRPC``` and ```brotobuf``` individually (after downloading sources separately). But the option of building both from source using ```gRPC```'s ```Makefile``` does not seem to work (for me). 

As per **thinkerou**'s suggestion, when I try to re-compile ```protobuf``` in ```third_party``` folder it fails with ```gmock``` error

```
$ ./autogen.sh 
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1582  100  1582    0     0   3481      0 --:--:-- --:--:-- --:--:--  3484
[gmock-1.7.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gmock-1.7.0.zip or
        gmock-1.7.0.zip.zip, and cannot find gmock-1.7.0.zip.ZIP, period.
```
Probably this error message is not related to gRPC development team.

**Comment by thinkerou** [comment]
It have the contents about `gmock` in `autogen.sh`

https://github.com/google/protobuf/blob/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0/autogen.sh#L34

**Comment by soltanmm-google** [comment]
You shouldn't need to re-compile `protobuf` in the `third_party` folder.

Do you have protobuf installed elsewhere on your system? Specifically a version lower than that pulled by gRPC's reference to the protobuf repository (`3.0.x`)?

**Comment by damleak** [comment]
The latest clone seems to be building fine.
