### ISSUE TITLE
How do I install grpc python if no Internet access?

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#8164]
I want to deploy grpc python lib for those cluster without outside internet access. What should I do, Is there any package I can download for manual installation to some specific local path?

**Comment by soltanmm-google** [comment]
Manually download the package(s) relevant to your cluster OS from this page: https://pypi.python.org/pypi/grpcio/. Then `pip install $DOWNLOADED_FILE` on all systems.

**Comment by yyh-graphsql** [comment]
$ ll grpc*
-rw-r--r--. 1 root root  299 Sep  5 16:31 grpcio_tools-1.0.0-py2.7-nspkg.pth

grpc:
total 300K
-rw-r--r--. 1 root root 3.3K Sep  5 16:32 _auth.py
-rw-r--r--. 1 root root 2.9K Sep  5 16:32 _auth.pyc
drwxr-xr-x. 2 root root 4.0K Sep  5 16:32 beta
-rw-r--r--. 1 root root  33K Sep  5 16:32 _channel.py
-rw-r--r--. 1 root root  31K Sep  5 16:32 _channel.pyc
-rw-r--r--. 1 root root 6.4K Sep  5 16:32 _common.py
-rw-r--r--. 1 root root 6.3K Sep  5 16:32 _common.pyc
-rw-r--r--. 1 root root 2.1K Sep  5 16:32 _credential_composition.py
-rw-r--r--. 1 root root 1002 Sep  5 16:32 _credential_composition.pyc
drwxr-xr-x. 4 root root   92 Sep  5 16:32 _cython
drwxr-xr-x. 5 root root   90 Sep  5 16:32 framework
-rw-r--r--. 1 root root   25 Sep  5 16:32 _grpcio_metadata.py
-rw-r--r--. 1 root root  172 Sep  5 16:32 _grpcio_metadata.pyc
-rw-r--r--. 1 root root  44K Sep  5 16:32 __init__.py
-rw-r--r--. 1 root root  49K Sep  5 16:32 __init__.pyc
-rw-r--r--. 1 root root 4.2K Sep  5 16:32 _plugin_wrapping.py
-rw-r--r--. 1 root root 4.3K Sep  5 16:32 _plugin_wrapping.pyc
-rw-r--r--. 1 root root  25K Sep  5 16:32 _server.py
-rw-r--r--. 1 root root  26K Sep  5 16:32 _server.pyc
drwxr-xr-x. 3 root root 4.0K Sep  5 16:32 tools
-rw-r--r--. 1 root root 5.3K Sep  5 16:32 _utilities.py
-rw-r--r--. 1 root root 5.9K Sep  5 16:32 _utilities.pyc

grpcio-1.0.0.dist-info:
total 32K
-rw-r--r--. 1 root root   10 Sep  5 16:32 DESCRIPTION.rst
-rw-r--r--. 1 root root    4 Sep  5 16:32 INSTALLER
-rw-r--r--. 1 root root  303 Sep  5 16:32 METADATA
-rw-r--r--. 1 root root  369 Sep  5 16:32 metadata.json
-rw-r--r--. 1 root root 5.1K Sep  5 16:32 RECORD
-rw-r--r--. 1 root root    5 Sep  5 16:32 top_level.txt
-rw-r--r--. 1 root root  110 Sep  5 16:32 WHEEL

grpcio_tools-1.0.0.dist-info:
total 32K
-rw-r--r--. 1 root root   10 Sep  5 16:31 DESCRIPTION.rst
-rw-r--r--. 1 root root    4 Sep  5 16:32 INSTALLER
-rw-r--r--. 1 root root  247 Sep  5 16:31 METADATA
-rw-r--r--. 1 root root  337 Sep  5 16:31 metadata.json
-rw-r--r--. 1 root root    5 Sep  5 16:31 namespace_packages.txt
-rw-r--r--. 1 root root 2.5K Sep  5 16:32 RECORD
-rw-r--r--. 1 root root    5 Sep  5 16:31 top_level.txt
-rw-r--r--. 1 root root  110 Sep  5 16:31 WHEEL

**Comment by yyh-graphsql** [comment]
When I finish installing the grpc, there are 3 directories generated:

- grpc:

- grpcio-1.0.0.dist-info:

- grpcio_tools-1.0.0.dist-info:

If I want to use grpc in another machine, besides platform differences, can I just copy the grpc directory directly to the other machine?

**Comment by nathanielmanistaatgoogle** [comment]
gRPC Python is designed for use with [`pip`](https://en.wikipedia.org/wiki/Pip_(package_manager)) - can you share with us with what version of `pip` you are working and the exact commands you are passing to `pip`?

**Comment by soltanmm-google** [comment]
**1)** Copying directories is not a supported use-case, neither by us nor by the general Python ecosystem AFAIK. It might work for you initially but something will probably go wrong in the future and if you're confused about how Python packaging works you will be in pain (e.g. the `*.pth` files that were installed are a messy ordeal handled on a per-system basis by the system's Python).

**2)** *Why* do you want to copy directories? Is `pip` not available on your machines? What's deficient about distributing a file and running a standard command on that file on each machine?
