### ISSUE TITLE
Intermittent issues with PHP gRPC extension SSL handshake

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#8165]
Sometimes when making gRPC ssl requests this error occurs. Usually a retry fixes this but we have not experienced this from our go client, only the php client.

`E0922 14:47:30.983447000 140735182512128 handshake.c:128] Security handshake failed: {"created":"@1474519650.983401000","description":"Handshake read failed","file":"/private/tmp/pear/temp/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1474519650.983379000","description":"FD shutdown","file":"/private/tmp/pear/temp/grpc/src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}`

**Comment by tbillington** [comment]
Hi, just wondering if anyone has experienced this or if it's fixed in a newer version?

Sometimes 3-4 requests or more will fail in a row, then for 3-4 requests it will be successful.

**Comment by stanley-cheung** [comment]
Can you try to gather more logs when this happens? Adding GRPC_VERBOSITY=DEBUG environment variable might help

**Comment by tbillington** [comment]
Just some feedback after cursory testing, after moving to the newest grpc version this issue seems to have gone away.

**Comment by stanley-cheung** [comment]
Thanks, great to know! Please re-open the issues if this happens again.
