### ISSUE TITLE
Building grpc 1.0.0 under electron 1.4.0

### ISSUE THREAD

**Issue by boodyvo** [grpc/grpc#8166]
I cannot build grpc 1.0.0 with node 4.5.0 under electron 1.4.0. I use this guide https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
and always get ms errors:
C:\Users\BoOdya.node-gyp\iojs-1.4.0\deps\v8\include\v8.h(3283) : see declaration of 'v8::Function::NewInstance'
..\src\node\ext\call.cc(616): error C2039: 'SetHiddenValue' : is not a member o
f 'v8::Object' [D:\WEB\WebStorm\Bitfury\electron-grpc\node_modules\grpc\build\g
rpc_node.vcxproj]
I've also instaled ms-tools as read here: https://github.com/nodejs/node-gyp#installation

**Comment by murgatroid99** [comment]
Which part of that guide did you follow? What command line exactly did you use?

**Comment by BoOdya** [comment]
npm install --global --production windows-build-tools 
I have Windows 8.1. I also tried on Windows 10 (there weren't any VS and VS tools and it also didn't work)

**Comment by murgatroid99** [comment]
What part of the electron guide did you follow? What command line commands did you use to install the package that depended on gRPC?

**Comment by murgatroid99** [comment]
The npm module grpc@1.1.0-pre1 should now work on electron. Make sure that you follow the instructions in the electron docs for [installing native modules](http://electron.atom.io/docs/tutorial/using-native-node-modules/). You should be able to omit the line `export npm_config_build_from_source=true` to install the precompiled binary file for electron.
