### ISSUE TITLE
Possible race condition in Channel.ConnectAsync 

### ISSUE THREAD

**Issue by jhickson** [grpc/grpc#8167]
[NB: I'm working in C# but suspect the issue below might lie in the native code; I'm using GRPC v1.0.0.]

Consider this scenario (all done in a the same process using local loopback):
1. I open a listening socket on some port and explicitly connect a Channel to it using Channel.ConnectAsync. 
2. Once all is connected I then close the remote (accepted) socket and the listening socket, simulating a server going down.
3. I then prompt the channel to connect by calling Channel.ConnectAsync.

What I would expect is that the channel's state would flip between Connecting and TransientFailure as it attempts to reconnect. However, I am finding that is not always the case and that sometimes after step (2) the channel goes to Transient then Idle and just stays there apparently ignoring the request to attempt to connect again in (3).

If I sleep the thread between (2) and (3) then this doesn't happen. It also doesn't happen if I trigger a connection attempt by invoking a call on the channel rather than explicitly calling ConnectAsync.

The NUnit unit test below reproduces this. The test monitors for a certain number of TransientFailure states before shutting the channel down. Note that there are two test cases: if you run both then the first will usually complete but the second very rarely completes. Occasionally the first doesn't complete. The logging showing state changes from a typical run is below.

> I0922 15:31:10.544000 ---------------- Open ------------------------
> I0922 15:31:10.557000 START
> D0922 15:31:10.599000 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "?????\GrpcExperiments\GrpcExperiments\bin\Debug\grpc_csharp_ext.x64.dll"
> D0922 15:31:10.646000 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
> I0922 15:31:10.680000 close remote
> I0922 15:31:10.686000 State is Connecting
> I0922 15:31:12.686000 State is Connecting
> I0922 15:31:13.684000 State is Connecting
> I0922 15:31:15.020000 State is TransientFailure
> I0922 15:31:15.297000 State is Connecting
> I0922 15:31:17.312000 shutdown done
> I0922 15:31:17.316000 END
> I0922 15:31:17.324000 START
> I0922 15:31:17.327000 close remote
> I0922 15:31:17.328000 State is TransientFailure
> I0922 15:31:17.328000 State is Idle

``` C#
using System;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;
using Grpc.Core;
using Grpc.Core.Logging;
using NUnit.Framework;

namespace GrpcExperiments.Code
{
    [TestFixture]
    internal sealed class ChannelTests
    {
        private TextWriterLogger _logger;
        private StreamWriter _textWriter;

        [Test]
        public async Task Break([Values(1, 2)] int maxFailures)
        {
            _logger.Info("START");

            try
            {
                GrpcEnvironment.SetLogger(_logger);
                var tcpListener = new TcpListener(IPAddress.Loopback, 9001);
                tcpListener.Start();

                var channel = new Channel("localhost", 9001, ChannelCredentials.Insecure);
                var acceptTask = tcpListener.AcceptTcpClientAsync();

                Task.WaitAll(channel.ConnectAsync(), acceptTask);

                var remoteTcpClient = acceptTask.Result;

                _logger.Info("close remote");
                remoteTcpClient.Close();
                tcpListener.Stop();

                // uncomment this and it works
                //Thread.Sleep(500);
                var task = channel.ConnectAsync();

                var state = channel.State;
                var count = 0;

                while (state != ChannelState.Shutdown)
                {
                    _logger.Info($"State is {state}");
                    _textWriter.Flush();
                    await channel.WaitForStateChangedAsync(state).ConfigureAwait(false);
                    state = channel.State;

                    if (state == ChannelState.TransientFailure)
                    {
                        ++count;

                        if (count > maxFailures)
                        {
                            await channel.ShutdownAsync();
                            _logger.Info("shutdown done");
                            _textWriter.Flush();
                            state = ChannelState.Shutdown;
                        }
                    }
                }

                remoteTcpClient.Close();
                tcpListener.Stop();
                GrpcEnvironment.ShutdownChannelsAsync().Wait();
            }
            catch (Exception exception)
            {
                _logger.Error(exception, "Error in test.");
            }
            finally
            {
                _logger.Info("END");
                _textWriter.Flush();
            }
        }

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _textWriter = new StreamWriter(new FileStream(Path.Combine(TestContext.CurrentContext.TestDirectory, "test_log.txt"), FileMode.Append, FileAccess.Write, FileShare.Read, 1), Encoding.UTF8, 1);
            _logger = new TextWriterLogger(_textWriter);

            _logger.Info("---------------- Open ------------------------");
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            _textWriter.Close();
        }
    }
}
```

**Comment by jhickson** [comment]
**Update**: I said above that this doesn't happen if I trigger a connect by invoking call but it turns out that's not true but it happens less often.

**Comment by apolcyn** [comment]
I think this behavior is actually expected. The channel state API is documented in https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md. But basically from the descriptions here, what appears to be happening is:

At the beginning, the channel attempts to connect. It successfully makes the TCP handshake and then transitions to READY. The `Thread.Sleep(500)` actually makes a significant difference after shutting down the TCP server and trying to call `Channel.ConnectAsync` again, because after no RPC activity has occurred on the channel for IDLE_TIMEOUT (default at 300 seconds), the channel transitions to "idle" state. Without the timeout, the channel probably thinks it's still in "ready" state just after closing the server, and so the subsequent state polling in the loop should have differing results.

When trying to connect to the closed TCP server, it flips between "transient failure" and "connecting" states as it goes through its retry logic. Eventually, it looks like the IDLE_TIMEOUT occurs while in one of the retried "connecting" states, and the channel state transitions to "idle". Once in the "idle" state, it stays there for as long as it's not explicitly shut down and there aren't any RPC attempts on it.

The exact difference that the initial states make before the state-polling loop should come down to timing, and the time taken between retries, and is probably a bit hard to trace down. But just note that the reconnect attempts and the time taken here is expected to be influenced by the time-without-RPCs - so there doesn't look to be a race here.

**Comment by apolcyn** [comment]
closing as I think this is ok by the channel state API

**Comment by apolcyn** [comment]
update: so @jhickson this looks like it brings up a documentation issue. I guess the state diagram in https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md isn't 100% true at this point, as it is expected that the transition to idle can actually happen earlier than the 300 seconds mentioned in the doc, if the channel finds out that it would be more efficient to do so. And I guess this transition to idle is actually a bit unspecified at this point anyways.

I should add that with gRPC being over HTTP2/TCP, the attempts to connect to the raw TCP server I suspect would give some somewhat unspecified behavior around the channel state API. The docs currently only mention completion of TCP handshakes, but there's probably also some failures to recognize HTTP2 going on, but again this is probably a doc issue.

Still for most cases though, I would think the Channel API should be able to abstract these states and transitions. Wondering are you examining these states in the application?

**Comment by jhickson** [comment]
@apolcyn: you'll be pleased to know that I'm no longer examining these states. I thought I needed to but I was just over-complicating matters. So whether this is purely a documentation issue or something more sinister is of less relevance to me now. However, it would be good to get clarification.

By the way, if I'm not supposed to be examining these states then should the means of doing so be in the surface API at all? Or is it useful to have them there for diagnostics?

**Comment by apolcyn** [comment]
@jhickson thanks for bringing this to attention anyways. AFAIK the behavior around the Channel connectivity states and transitions is probably not *stable* at this point, at least from a timing perspective, though it is accessible. Basically, being IO/timing sensitive, I think it would be difficult to set hard expectations against. And there are complexities like, for example, polling `channel.state` might actually give a different result than the state just arrived at in `WaitForStateChangeAsync`, as it should be valid for the state to change in the time between.

**Comment by apolcyn** [comment]
@jtattermusch I would think that the methods like `WaitForStateChangeAsync` are probably more internal, but maybe there's more to the intended usage of these?

**Comment by apolcyn** [comment]
Looking more into this, I think there are multiple things going on here, but the most basic problem actually seems to be just that the `ConnectAsync` method will stall when it reaches the terminal "idle" state - sorry I had overlooked this earlier. I think that the most simple fix to this is to just attempt to reconnect when it does do this. This seems to fix the repro case here - both test cases finish succesfully.

**Comment by apolcyn** [comment]
the above comment appears incorrect, this still needs more investigation

**Comment by jtattermusch** [comment]
Last update on this issue from Mar 2017, closing.
