### ISSUE TITLE
gRPC_master tsan/c++/linux didn't finish in 10 hours

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#8169]
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5642906408845312

At this point, it's very likely to be a real thread contention bug in gRPC.

**Comment by adelez** [comment]
CC @vjpai @nicolasnoble

**Comment by adelez** [comment]
The test output itself looks fine. Maybe just need to break up the test? https://grpc-testing.appspot.com/job/gRPC_master/config=tsan,language=c++,platform=linux/18625/consoleFull

**Comment by adelez** [comment]
CC @ctiller @jtattermusch

**Comment by adelez** [comment]
Last successful build is 18527 (14 days ago) and the duration was 5678 s.

**Comment by jtattermusch** [comment]
Does it pass when run locally on a machine when nothing else runs?

**Comment by matt-kwong** [comment]
Last week, C++ tsan tests were finishing in an appropriate amount of time, but it seems like it broke again around sometime late last week. 
https://grpc-testing.appspot.com/job/gRPC_master_tsan_c++/35/consoleFull - this is a timestamped log of C++ tsan tests running without other sanitizers tests and it finishes in just under 4 hours while maxing out CPU usage on a 16 core VM. Other sanitizer tests take 30 minutes or less and don't max out the CPU, so I think there is an issue with threads.

**Comment by matt-kwong** [comment]
CC @ctiller 

https://grpc-testing.appspot.com/job/gRPC_master_tsan_c++/35/testReport/(root)/c++_linux_tsan/
This should give a good idea which tests are causing the test suite to not finish in time.

**Comment by jtattermusch** [comment]
This issue is way too old, closing.
