### ISSUE TITLE
data race /var/local/git/grpc/gens/src/proto/grpc/testing/messages.pb.cc:858:17 in grpc::testing::Payload::ByteSize() const

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#8174]
https://grpc-testing.appspot.com/job/gRPC_master/18624/config=tsan,language=c++,platform=linux/console

**Comment by vjpai** [comment]
I just discussed this issue with @ctiller and @haberman . We need to either make the relevant annotation mean something to tsan in OSS, or we need to add it to [the TSAN suppression file](https://github.com/grpc/grpc/blob/master/tools/tsan_suppressions.txt) . I will go with the latter route for now and send a PR for this soon.
