### ISSUE TITLE
 nodejs metadata?  how use??? 

### ISSUE THREAD

**Issue by shenggen1987** [grpc/grpc#8186]
var messages = require('./hello_pb');
var services = require('./hello_grpc_pb');

var grpc = require('grpc');

function main() {
  var metadata = new grpc.Metadata();
  metadata.set('passport', 'lishenggen_passport');
  var client = new services.GreeterClient('192.168.8.206:8000',
                                          grpc.credentials.createInsecure());

  metadata.set('passport', 'lishenggen_passport');
  var user;
  if (process.argv.length >= 3) {
    user = process.argv[2];
  } else {
    user = 'world';
  }
  var request = new messages.HelloRequest();
  request.setName(user);
  client.sayHello(request, function(err, response) {
    console.log(response.status);
    console.log('Greeting:', response.getMessage());
  });

}

main();

**Comment by nathanielmanistaatgoogle** [comment]
(Possibly overlaps with [grpc.github.io issue 368](https://github.com/grpc/grpc.github.io/issues/368).)

**Comment by murgatroid99** [comment]
The metadata object should be passed as a parameter to the client method, after the argument and before the callback. For example:

```js
//--------------------------v
client.sayHello(request, metadata, function(err, response) {
  console.log(response.status);
  console.log('Greeting:', response.getMessage());
});
```
