### ISSUE TITLE
Memory-based server flow control

### ISSUE THREAD

**Issue by therc** [grpc/grpc#8187]
It would be great for a server to throttle the processing incoming requests once the heap/process exceeds a threshold specified by the application. Using a thread pool of fixed size only helps in cases where RAM consumption is directly proportional to the in-flight RPC count (and the pool size will need adjusting every time a new binary release changes the multiplier in a significant manner). For environments where resource reservation is more strictly controlled, such as containers, it's vital to avoid OOMs as much possible, especially because it might lead to cascading failures.

See e.g. RabbitMQ's approach:
http://www.rabbitmq.com/memory.html

For bonus points, this could be extended to CPU pressure as well, but, since that's a compressible resource, it is not as important.

cc @ctiller since he's apparently working on related machinery.

**Comment by therc** [comment]
See also #8363 to allow a server to manually enter/exit lameduck state.

**Comment by ctiller** [comment]
#8239 is the first piece of the implementation, whereby we'll limit gross buffer usage - but only crudely by either delaying allocations or cancelling requests when overflow memory.

I'll be following up in the coming months with additional smarts to reduce flow control windows dynamically based on memory pressure.

User control will be available by declaring pools and attaching them to servers or client channels at creation time. Pools will be dynamically resizable, with the guarantee that if the pool is resized there'll be a monotonic decrease in memory until the new size is reached.

**Comment by ncteisen** [comment]
This goal has been accomplished
