### ISSUE TITLE
nw.js can't use grpc

### ISSUE THREAD

**Issue by TigerLau1985** [grpc/grpc#8193]
OS:                          Windows 10
Complier:                MSVS 2015
Node Version:         6.6
NW.js Version:        0.17.4

When install gRPC in project use this command:
`npm install grpc --build-from-source --runtime=node-webkit --target=0.15.4 --target_arch=x64`

I got error like this:
`..\src\node\ext\call.cc(616): error C2039: “SetHiddenValue”: is not “v8::Object” member`

Any suggest for this problem?

**Comment by TigerLau1985** [comment]
Well，It can work with nw.js ver0.15.4

**Comment by murgatroid99** [comment]
gRPC version 1.0.1 may now work with the latest version of nw.js. If anyone could confirm that, that would be great.
