### ISSUE TITLE
license unclear: Can binaries which statically link this library be commercially distributed?

### ISSUE THREAD

**Issue by DanPallas** [grpc/grpc#8194]
Hi,

Can binaries which statically link this library be commercially distributed? More specifically, I'm interested in distributing an SDK which communicates with a commercial hosted service via grpc and protobuffs. I'd like to distribute the SDK as binary without external dependencies. Does the license of grpc allow for this? What requirements should I be aware of?

**Comment by DanPallas** [comment]
What concerns me about copy and pasting is that it will make versioning the protobuffs more difficult, unless each sdk depends on the entire gamelocker service.

**Comment by dklempner** [comment]
The license is bog standard 3-clause BSD. It's one of the most common licenses out there.

If you think it is unclear, you probably know nothing about open source licenses.

That's perfectly OK!

If the text of the license is unclear (and really even if you think it is clear) you should speak to your employer's lawyers and/or follow any existing process for open source licenses. They can explain/confirm what you need to do.

**Comment by DanPallas** [comment]
Thanks for getting back to me. I am familiar with the BSD license. I didn't realize that grpc was licensed under BSD because the license file doesn't say that. https://github.com/grpc/grpc/blob/master/LICENSE

**Comment by DanPallas** [comment]
While I'm somewhat familiar with the BSD license, I didn't recognize it by its text. It does seem quite vague to my non lawyer self. Thanks for your response.
