### ISSUE TITLE
grpc_cli compilation error

### ISSUE THREAD

**Issue by maheshps-huawei** [grpc/grpc#8200]
Hi, Would you please let me know how to solve this compilation issue in today's build?

root1@root1-Latitude-E7450:~/grpc$ make grpc_cli
..
[AR]      Creating /home/root1/grpc/libs/opt/libgpr.a
[CXX]     Compiling test/cpp/util/test_config.cc
test/cpp/util/test_config.cc:35:27: fatal error: gflags/gflags.h: No such file or directory
 #include <gflags/gflags.h>
                           ^
compilation terminated.
make: **\* [/home/root1/grpc/objs/opt/test/cpp/util/test_config.o] Error 1

-Mahesh

**Comment by drigz** [comment]
I was able resolve the issue with:
```shell
sudo apt-get install libgflags-dev
```

Is this the right solution, or should it be able to build from the copy in third_party?

If the former, should there be a [dep check in Makefile.template](https://github.com/grpc/grpc/blob/062ba7b8baefdc76f74fffb9aa3e2134ba047ea6/templates/Makefile.template#L745)?
