### ISSUE TITLE
Should node-pre-gyp be an install dependency?

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#8206]
I noticed that our dependency on `node-pre-gyp` passed along when downstream libraries depend on `grpc` in Node. Is this really required?

The library says it's for binary deployment, so I'm curious if it needs to be installed downstream...?

**Comment by murgatroid99** [comment]
We use `node-pre-gyp` for three different tasks. It's used to build the binary packages, which we need during development, to install the binary packages, which we need at installation time, and to load the binary packages, which we need at run time.

It is true that the runtime use only uses a very small part of the library, and we could probably duplicate the logic and dispose of the dependency there, but we still need it when installing the package, and I don't know of a way to have a dependency only during installation.
