### ISSUE TITLE
httpcli crashes at grpc_endpoint_destroy when ssl handshake fails

### ISSUE THREAD

**Issue by umegaya** [grpc/grpc#8207]
I encounter this in current Pod version, provided from https://github.com/GoogleCloudPlatform/ios-docs-samples. endpoint->vtable seems to have invalid value.

I think this problem occured by following steps:
1. request endpoint (req->ep) passed into ssl_handshake(httpcli_security_connector.c)
2. handshake fails
3. security_handshake_done(handshake.c) called with error != GRPC_ERROR_NONE. here, req->ep  seems to be destroyed through h->wrapped_endpoint but req->ep still have non-null address
4. on_secure_transport_setup_done(httpcli_security_connector.c) called back with status != GRPC_SECURITY_OK
5. on_handshake_done(httpcli.c) called with ep == NULL
6. next_address(httpcli.c) called, and when req->next_address == req->addresses->naddrs, finish(httpcli.c) called
7. finish(httpcli.c) try to destroy endpoint again, because req->ep still has non-null address

my workaround is set NULL to req->ep when on_handshake_done(httpcli.c) called with ep == NULL.
is this bug or am I missing something to work httpcli correctly?

**Comment by dgquintas** [comment]
Several bugfixes around that part of the code have happened in the last month. Closing for now. Please re-open if this is still an issue.
