### ISSUE TITLE
How to archive grpc libs into a shared library?

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#8211]
I want to archive multiple libraries into one shared library. When it comes to grpc, some bad things happened. I cannot archive grpc libraries together. Here is my question:
- Why grpc has seperated libraries for user to link, such as libgrpc++_unsecure.a', 'libgrpc_unsecure.a', 'libgpr.a'
- When I use 'g++ -fpic -shared -Wl,--whole-archive libgrpc++.a libgpr.a -o liball.so', I got  a lot of errmsg like follows:
  (.text+0x100): multiple definition of `gpr_malloc'
  .//libgrpc++.a(alloc.o):(.text+0x100): first defined here
  .//libgpr.a(alloc.o): In function`gpr_free':
  What can I do to work around this?
- Is grpc has a monolithic library for user to link?

**Comment by nicolasnoble** [comment]
When using static libraries, they are already monolithic.
