### ISSUE TITLE
HP-UX 11.31 port of the grpc

### ISSUE THREAD

**Issue by malexzx** [grpc/grpc#8212]
While porting GRPC on hpux-ia64 target, I hits a few test failed problem.
One issue is a murmurhash3 incompatibility with big-endian (result hash number is differ). 
Does this issue sensitive while GRPC interoperating with these two different platforms (ie: linux and big-endian HPUX) , or I'm need to implement (find) it for this platform? 
Does this patch (My port GRPC to HPUX) might interested to integrate into GRPC master branch?

**Comment by malexzx** [comment]
EDIT: two WORD swaps, handle my issue with murmurhash3

**Comment by swingfield** [comment]
Hi @malexzx,

I was wondering how your HP port was coming along. I am considering looking into the effort for AIX  and Solaris in addition to HP, and was curious if you were finding success.

**Comment by malexzx** [comment]
Hi @swingfield,

My port completely done, working and most tests are passed (but outdated in integration queue).
Maybe it required additional work with grpc requirements.
You can base your work on my (https://github.com/grpc/grpc/pull/8572). But I dont known, when it integrated into grpc source.

**Comment by c-bb** [comment]
Hi @swingfield, I would be quite interested in a port to Solaris and AIX as well. Did you make any progress on this? Thanks!
