### ISSUE TITLE
python client read data from c++ version server failed with "StatusCode.INTERNAL, Max message size exceeded"

### ISSUE THREAD

**Issue by Jianfei1** [grpc/grpc#8213]
Hi,
version info:
platform: CentOS Linux release 7.2.1511 (Core)
libprotoc 3.0.0
grpc 1.0.0
grpcio 1.0.0

I wrote a first version with python server + python client it work well. When I created another c++ server version and use python client to read same data, python client reported below error code:  
Traceback (most recent call last):
  File "test_performance_specific_client.py", line 74, in <module>
    i = test_multi_tick_stock_data_no_print()
  File "test_performance_specific_client.py", line 34, in test_multi_tick_stock_data_no_print
    start_date="2016-03-07 00:00:00", end_date="2016-06-09 10:01:00")
  File "../client.py", line 25, in read_hist_data
    return stub.ReadStockTick(data_type)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, Max message size exceeded)>

The message is repeated structure, the total message size if about 25M(the original size, not after serialized), if I reduced the number of repeated filed(by specified a smaller range of data), it can work.  Seems root cause is the repeated amount is too large. But I want to know why python version server can work without this problem.  
I try to increase the message size number in server code by builder.SetMaxMessageSize(1024*1024*1024);
seems it doesn't work. 
could someone help it? Thank you!

**Comment by Jianfei1** [comment]
I found one closed issue:"Reduce default max message size #1676"
https://github.com/grpc/grpc-java/issues/1676
although it talked about java.grpc, but I think this reduce message size to 4M apply to c++.grpc as well. It match my testing result: "when message size exceed 4M client report 'Max message size exceeded' ", now still the question:
How to increase the maximum message size?  I used 
"  ServerBuilder builder;
  builder.SetMaxMessageSize(100*1024*1024);"
But it doesn't work.

**Comment by Jianfei1** [comment]
Now I solve the problem:
In server side(C++):
  ServerBuilder builder;
  builder.SetMaxMessageSize(100*1024*1024);

If use C++ client:
  grpc::ChannelArguments channel_args;
  channel_args.SetInt("grpc.max_message_length",100*1024*1024);
  ReadDataClient readdata(
      grpc::CreateCustomChannel("localhost:50051",
                          grpc::InsecureChannelCredentials(),channel_args));

If use python client:
  channel = grpc.insecure_channel("localhost:50051",\
                                    options = [('grpc.max_message_length', 100*1024*1024)])

**Comment by bitkevin** [comment]
should use `grpc.max_receive_message_length`  instead of `grpc.max_message_length` now.
