### ISSUE TITLE
Cross Compiling GRPC for armhf

### ISSUE THREAD

**Issue by Gary4444** [grpc/grpc#8214]
Hi,

Im trying to build grpc for an arm hf target.

I have been following the instructions I found on an older thread :
https://github.com/grpc/grpc/issues/6756#issuecomment-228479843

I believe that I have successfully cross compiled protobuf:

$./configure --host=arm-linux-gnueabihf CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ --with-protoc=/usr/local/bin/protoc
$make

produces :-
0 lrwxrwxrwx 1 root root 26 Sep 27 15:28 libprotobuf-lite.so -> libprotobuf-lite.so.10.0.0
0 lrwxrwxrwx 1 root root 21 Sep 27 15:30 libprotobuf.so -> libprotobuf.so.10.0.0
0 lrwxrwxrwx 1 root root 19 Sep 27 15:33 libprotoc.so -> libprotoc.so.10.0.0

I didnt run:
$ make check
$ sudo make install
$ sudo ldconfig # refresh shared library cache.

As I know that gprc make will attempt to use the native protoc + pluggins need to be compiled natively.

$make plugins runs fine.

I the tried to build grpc

$make HAS_PKG_CONFIG=false CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ RANLIB=arm-linux-gnueabihf-ranlib LD=arm-linux-gnueabihf-gcc LDXX=arm-linux-gnueabihf-g++ static

This appears to run until it attempts to rebuild protobuf at which point toys are thrown out of the pram:

[MAKE]    Building protobuf
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for gcc... arm-linux-gnueabihf-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/home/gnewman/CWork/grpc/grpc/third_party/protobuf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use`--host'.
See `config.log' for more details
make: **\* [/home/gnewman/CWork/grpc/grpc/libs/opt/protobuf/libprotobuf.a] Error 1

So I'm assuming rebuilding protobuf  is not desirable.

Ultimately Im attempting to rebuild the HelloWorld example on the target.

I appear to have built :
libboringssl.a  libgpr.a  libgrpc.a  libgrpc_cronet.a  libgrpc_plugin_support.a  libgrpc_unsecure.a  libz.a

But the Makefile for HelloWorld appears to need to link -lgrpc++_reflection which hasn't been built?

Any help/pointers would be gratefully appreciated, I seem to have been going round in circles for days.

Thanks

Gary

**Comment by Gary4444** [comment]
Ok I got around this in the end.

Im not sure why after cross compiling protobuf that grpc make decided that it wanted to recompile it.

So what I ended up doing was natively compiling plugins as suggested (these are required as part of the protobuf build).  

I ended up hacking the makefile as follows:
changed the protobuf configure to the cross compiled version -

./configure --host=arm-linux-gnueabihf CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ --with-protoc=/usr/local/bin/protoc

This allows protobuf to build.

I also then immediately deleted the native pluggins after the protobuf build so that make would be forced to cross compile them (this is required for libgrpc_plugin_support.a)

I then hacked all further uses of protoc in order that the natively installed protoc was used rather than the cross compiled version.

This finally got me a full set of static libraries & I have them working on the target.

It's far from pretty & I'm sure not the recommended solution.  
But hey it worked!

**Comment by manikandan83** [comment]
I did cross compile for ARM architecture. When running the greeter_server, I am getting the following error

./greeter_server: error while loading shared libraries: read: cannot open shared object file: No such file or directory".

I dont want to have static linking.

If anybody has solved this issue. Please share your thoughts.

/Br
Mani. C

**Comment by nicolasnoble** [comment]
You need to run `ldconfig` after installing shared libraries.
