### ISSUE TITLE
Feature request: Multiple bi-directional gRPC calls over single pre-established TCP connection

### ISSUE THREAD

**Issue by capablegh** [grpc/grpc#8217]
See [this Stackoverflow Q/A](http://stackoverflow.com/questions/39677772/multiple-bi-directional-grpc-calls-over-single-pre-established-tcp-connection) that lead to opening this feature request issue. 

Summarizing the desirable features below:
- gRPC API user is given control over the TCP connection and it's socket abstractions. In this, gRPC should be able to accept a given socket representation (e.g. file descriptor in C/C++) of a TCP connection that the user has already established between the two ends hosts where the server/client with execute.
- allow using the same TCP connection simultaneously by each of the gRPC server and client.
- allow using of raw TCP connection, i.e. not have HTTP/2 or another protocol as a dependency.
- allow the user to have gRPC release the socket back to the user so that the user can close the socket or do whatever the user intends with it.

The above is desirable in some scenarios where performance is a criteria, so establishing and tearing down a TCP connection for every gRPC call is avoided, and the raw TCP API will not require any other protocol's header overhead.  Using a pre-connected socket will allow the user to establish socket connection between two hosts that may be inside different firewalls, and where only a custom means of establishing the TCP connection may be available.

**Comment by murgatroid99** [comment]
A few things to be aware of:

 - The gRPC protocol is currently only defined on top of HTTP/2 or a functionally equivalent protocol. gRPC over raw TCP would require a new protocol specification, and getting it to have the same semantics as gRPC over HTTP/2 would probably require reimplementing most of the relevant HTTP/2 functionality anyway.

 - Current gRPC implementations do not establish and tear down a TCP connection for every gRPC call. By default, they use a single persistent connection for all calls from a client to a single server. This is one of the benefits of using HTTP/2.

 - The [grpc_posix.h](https://github.com/grpc/grpc/blob/master/include/grpc/grpc_posix.h) header currently has support adding file descriptors to servers and creating channels from file descriptors. That functionality is also exposed in the C++ library in [create_channel_posix.h](https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/create_channel_posix.h) and [server_posix.h](https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/server_posix.h).

**Comment by capablegh** [comment]
Thanks, your comments are helpful in improving my understanding of the constraints of gRPC and available capabilities in the context.
