### ISSUE TITLE
Python future raises deadline exceeded after a disconnect

### ISSUE THREAD

**Issue by croachrose** [grpc/grpc#8229]
I discovered an interesting edge case when using python futures. If a future is used successfully but the remote server connection terminates, the next future call can raise a deadline exceeded exception (or hang forever without a deadline) instead of raising unavailable. I was able to write a small test using the helloworld service.

```
from concurrent import futures                                                                       
import grpc                                                                                          

import helloworld_pb2                                                                                


class Greeter(helloworld_pb2.GreeterServicer):                                                       

    def SayHello(self, request, context):                                                            
        return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)                        


def main1():                                                                                         
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))                                 
    helloworld_pb2.add_GreeterServicer_to_server(Greeter(), server)                                  
    server.add_insecure_port('[::]:50051')                                                           
    server.start()                                                                                   

    channel = grpc.insecure_channel('127.0.0.1:50051')                                               
    client = helloworld_pb2.GreeterStub(channel)                                                     
    print client.SayHello.future(                                                                    
        helloworld_pb2.HelloRequest(name='this works'), 10).result()                                 

    server.stop(None)                                                                                

    try:                                                                                             
        client.SayHello.future(                                                                      
            helloworld_pb2.HelloRequest(name='deadline exceeded'), 2).result()                       
    except grpc.RpcError as e:                                                                       
        print e.code()                                                                               


def main2():                                                                                         
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))                                 
    helloworld_pb2.add_GreeterServicer_to_server(Greeter(), server)                                  
    server.add_insecure_port('[::]:50052')                                                           
    server.start()                                                                                   

    channel = grpc.insecure_channel('127.0.0.1:50052')                                               
    channel.subscribe(lambda s: s)                                                                   
    client = helloworld_pb2.GreeterStub(channel)                                                     
    print client.SayHello.future(                                                                    
        helloworld_pb2.HelloRequest(name='this works'), 10).result()                                 

    server.stop(None)                                                                                

    try:                                                                                             
        client.SayHello.future(                                                                      
            helloworld_pb2.HelloRequest(name='unavailable'), 2).result()                             
    except grpc.RpcError as e:                                                                       
        print e.code()                                                                               


if __name__ == '__main__':                                                                           
    main1()                                                                                          
    main2()
```

main1 demonstrates the bug. The server disconnects after a successful call to SayHello.future. The next call times out after 2 seconds. If I do not supply a timeout, the method never returns.

main2 demonstrates a weird "fix". If I subscribe to channel state changes, the second call to SayHello.future immediately notices the connection has died and raises unavailable. My guess is that watching the channel state causes some change in timing.

This was tested against the v1.0.0 release.

**Comment by mehrdada** [comment]
I tried and failed to reproduce the bug on Python 2.7.10 on macOS Sierra 10.12.2 (using virtual environments). It outputs UNAVAILABLE right away in both cases. What's the OS/python/gRPC versions you use?

**Comment by croachrose** [comment]
Linux 4.2.0-19
Python 2.7.10
gRPC 1.0.0

**Comment by mehrdada** [comment]
I am unable to reproduce the problem. I installed the exact ubuntu/python version (15.10) and unable to reproduce on gRPC 1.0.0 (or the latest version on pip).

**Comment by nathanielmanistaatgoogle** [comment]
@croachrose: is this still reproducible for you? Perfectly, or intermittently, or nondeterministically? (I also attempted to reproduce the problem by running your code and was not able to do so.)

**Comment by croachrose** [comment]
I can still reproduce perfectly. main1 completes with DEADLINE_EXCEEDED instead of detecting the server disconnect.

**Comment by croachrose** [comment]
```message: "Hello, this works!"

StatusCode.DEADLINE_EXCEEDED
message: "Hello, this works!"

StatusCode.UNAVAILABLE```

**Comment by nathanielmanistaatgoogle** [comment]
This is still a headscratcher for us. What are the chances that you could share a VM image with us that we could simply run?

**Comment by croachrose** [comment]
Let me see if I can reproduce in a docker container. Would that work?

**Comment by mehrdada** [comment]
That would be much appreciated!

**Comment by croachrose** [comment]
I have reproduced the issue using a docker container. I have attached all the files needed to reproduce (I had to add .txt for github to attach them). Place them in a directory together and run the following sequence:

```
docker build -t grpcrepro .
docker run --rm -it grpcrepro python repro.py
```

Let me know if I can help more

[Dockerfile.txt](https://github.com/grpc/grpc/files/766966/Dockerfile.txt)
[helloworld.proto.txt](https://github.com/grpc/grpc/files/766968/helloworld.proto.txt)
[repro.py.txt](https://github.com/grpc/grpc/files/766967/repro.py.txt)

**Comment by mehrdada** [comment]
Thanks! I was able to repro the issue with the Docker container (even on a newer Ubuntu). Have you ever encountered this issue outside Docker? I'm trying to investigate if the issue is a result of an interaction with Docker as I have been unable to observe it outside the container.

**Comment by croachrose** [comment]
This happens on my laptop 100% of the time.

**Comment by mehrdada** [comment]
We just released v1.2.1 which fixed an issue with orphaned file descriptors. I suspect this might have been related to this issue as well. I am unable to repro the bug on 1.2.1 available on pip. Can you still try and see if you can reproduce the issue on 1.2.1? 

[I basically changed the Dockerfile provided to grpcio==1.2.1 grpcio-tools==1.2.1:]

```
from ubuntu:15.10

run apt-get update && apt-get upgrade -y && apt-get install -y python curl
run curl -sL https://bootstrap.pypa.io/get-pip.py | python
run pip install grpcio==1.2.1 grpcio-tools==1.2.1
copy . /

run python -m grpc.tools.protoc -I . --python_out . --grpc_python_out . helloworld.proto
```

**Comment by croachrose** [comment]
Works for me! Thanks for the update!

**Comment by mehrdada** [comment]
Great! Please do let us know if you re-encountered the issue on the new version!
