### ISSUE TITLE
Typescript typings for node package

### ISSUE THREAD

**Issue by pocesar** [grpc/grpc#8233]
I've written this in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11264, but it would be best for the node package to come with it's own typings, since Typescript 2.0 got officially released. 

It's not that the grpc is overly complicated, but there's a lot of moving parts, and keeping the jsdoc in sync with the typings can be frustrating when doing from the outside (maintained by the DT community)

there's some initial work using a jsdoc plugin in https://github.com/jumpinjackie/jsdoc-typescript-plugin that might make it easier for it. also, AVA has an automated way to generate their typings as well https://github.com/avajs/ava/blob/master/types/make.js

**Comment by sergeyzenchenko** [comment]
It will be very cool to have typescript support. But not only for actual grpc api, but also for dts generation based on messages and services defenitions.

**Comment by paralin** [comment]
@sergeyzenchenko I have something like that written up, it's a protobuf.js question actually.

**Comment by sergeyzenchenko** [comment]
hey @paralin can you give me the link to it? I can't find it in your repo.

**Comment by kondi** [comment]
@sergeyzenchenko see my project [rxjs-grpc](/kondi/rxjs-grpc)

**Comment by paralin** [comment]
@kondi nice work. @sergeyzenchenko you can see most of it here: https://github.com/rgraphql/rgraphql/tree/master/scripts

The scripts generate these files:

https://github.com/rgraphql/rgraphql/tree/master/src/proto

See interfaces and definitions.

**Comment by eXeDK** [comment]
Any progress on this?

**Comment by LouiseBC** [comment]
I may be mistaken, but the type for `server.addService` doesn't seem to be correct.
It's typed as `addService(service: Service, implementation: { [name: string]: handleCall })`, whereby `Service` has a methods like `toJson` and `create` (defined [here](https://github.com/dcodeIO/protobuf.js/blob/952c7d1b478cc7c6de82475a17a1387992e8651f/index.d.ts#L1293)).

If you look at the example [here](https://github.com/grpc/grpc/blob/v1.7.x/examples/node/static_codegen/greeter_server.js) using [this](https://github.com/grpc/grpc/blob/v1.7.x/examples/node/static_codegen/helloworld_grpc_pb.js) generated code, you will see that `services.GreeterService` doesn't actually implement the `Services` class, but I'm assuming that this example contains valid code.
