### ISSUE TITLE
ruby grpc stream stops sending messages after a long silence

### ISSUE THREAD

**Issue by amohamedali** [grpc/grpc#8244]
Hi guys, I am kind of new to all grpc concepts so I don't really get if this is a normal behavior or not.

I have a GRPC server developed in ruby, that opens a stream for a client in java, and sends events based on my database events. This works quite well, it's fairly stable.

The only problem is that my server potentially doesn't send any messages for a while (for at least 5 minutes if not more, I wasn't able to determine the exact time that it takes to reproduce the issue).
The connection then seems to drop with no error, at this point the client doesn't receive any new messages, even if I stop my server the client doesn't receive any information about that.

I am working on a mini-project to demonstrate the issue to you.

edit: [here](https://github.com/amohamedali/grpc_db_notifier_example) is my example, thank you for taking time to watch it.

**Comment by amohamedali** [comment]
Hi guys i have run this example for the whole week-end with 12 hours maximum between each event. But it seems that in a local environment the connection is actually never dropped. I think it may be related to network issues. 

Do you have any idea where this may come from ?

**Comment by apolcyn** [comment]
@amohamedali so when this reproduces, the server has message that is should be sending, i.e. stream should have messages getting sent to it? One guess is that the background thread that fills in the responses stream could be dying silently?

But the client not seeing any failure when the ruby server is shut down seems strange here, AFAIK there should be some sort of error here.

**Comment by amohamedali** [comment]
@apolcyn when the error happens, my client doesn't receive any more messages. But if I connect another client it will receive messages normally, and if the server shuts down receives the error. Even so, my first client won't receive anything.

**Comment by apolcyn** [comment]
@amohamedali correct me if I'm wrong but a main issue here is that the connection from client to server will die, sometimes with the server being shut down, but the client isn't notified?

@ejona could something be going on here with the client?

**Comment by amohamedali** [comment]
@apolcyn yes the main issue (for me at least) is that it s totally silent, btw the server shut downs are done manually and only for testing purpose it never happened that the server closes on his own.

**Comment by apolcyn** [comment]
@amohamedali when attempting to repro on linux: Using a java client talking to a local ruby server, and a ruby server shutdown in the middle of the inactive part of a bidi call (during a 30-second to 1 minute gap between messages in a bidi call), the java client does seem to get notified of an end to the connection, as expected. 

Is it possible that there is another grpc server listening on the same port, on the same machine (which one the client gets connected to would be determined by the server's OS)? If this were the case, then shutting down the server that the client *wasn't* connected to wouldn't cause any errors.

**Comment by amohamedali** [comment]
@apolcyn No there was no other GRPC server on the machine, and yeah I have run several times the example I've sent locally and I can't reproduce the issue either. That makes me think that the problem has to do with network fluctuation.

I will try to build a supervisor app that restarts the server randomly, and deploy the example on different machines to try to reproduce the problematic network conditions.

**Comment by amohamedali** [comment]
Hi sorry for being late to answer I really wanted to test things in different conditions to check when it really does fails, and this issue actually doesn't happen in a local environment, or if the client and the server are on a private network.
This makes me think that it's most likely a router in between the server and the client that closes the connection if nothing happens when there is no communication for too long.
I have looked into issues on the grpc-java side and found out that it is missing a "keep-alive" option on the tcp socket and that there is an issue to fix that, so I will wait until this is validated and if it still doesn't help I will come back here to keep you informed.Btw the grpc-java issue I am talking about is this one : https://github.com/grpc/grpc-java/pull/2366

**Comment by apolcyn** [comment]
@amohamedali thanks for looking into this. Not conclusive as of now, AFAIK what you're describing here could be the issue.
