### ISSUE TITLE
Randomly reorder completion queue events in debug

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#8252]
People are writing code that depends on a particular ordering, and we don't guarantee that.

At least in debug builds, shuffle the order a little to stop bad assumptions from being made.

**Comment by sreecha** [comment]
I think this would be good for @lyuxuan to start getting familiar with grpc core...

**Comment by vjpai** [comment]
But do people in the world ever link with our dbg version, or only with opt?

**Comment by ctiller** [comment]
We're not taking any overhead for opt.

**Comment by vjpai** [comment]
Sure, I agree with not adding overhead to opt. Never mind, I wasn't considering that this is primarily for the context of folks that build from scratch and not just link with pre-installed libraries.
