### ISSUE TITLE
Jenkins end point with Visual studio online

### ISSUE THREAD

**Issue by jk1510karti** [grpc/grpc#8262]
Hi Team,

I am creating new Service end point with jenkins from Visual Studio online. I have installed jenkins on my windows server. I can able to access the jenkins URL from remote machine(which is in same network). But when I try to make connection from visual studio online i'm getting timeout issues.

You can find the error screenshot here.
https://ufile.io/f5f

its quite urgent issues.~!!

**Comment by jtattermusch** [comment]
This doesn't look like something gRPC related. Sorry.
