### ISSUE TITLE
Objective-C : backoff.c vs GRPCConnectivityMonitor stream reconnection issue

### ISSUE THREAD

**Issue by SimpleApp** [grpc/grpc#8272]
I'm trying to understand the reconnection algorithms for gRPC stream, and don't understand something : 

There seems to be an automatic retry mechanism in place at the gRPC-Core implementation, like the "backoff.c" file suggest. This mechanism suggests that loss of connectivity will be automatically resumed once the connectivity is restored (or at least that the first time connection phase may succeed after some time).

BUT, the gRPC objective-c layer monitors each GRPCCalls using a GRPCConnectivityMonitor, with the following handler :  

```
[_connectivityMonitor handleLossWithHandler:^{
    typeof(self) strongSelf = weakSelf;
    if (strongSelf) {
      [strongSelf finishWithError:[NSError errorWithDomain:kGRPCErrorDomain
                                                      code:GRPCErrorCodeUnavailable
                                                  userInfo:@{NSLocalizedDescriptionKey: @"Connectivity lost."}]];
      [[GRPCHost hostWithAddress:strongSelf->_host] disconnect];
    }
  }];
```

Which makes me wonder : how are we supposed to handle automatic reconnection of gRPC streams ?

EDIT: i'm not even sure the backoff mechanism is used once the connection is established to handle disconnections, but in any case, i don't understand how the two mechanisms can work together, even for a first time connection.

**Comment by ctiller** [comment]
Streams in gRPC are tightly bound to the connection they're initiated on, with no built in support for resumption or migrating them to a different backend. If you need this you'll need to provide some application level logic to cover it.
