### ISSUE TITLE
Objective-c: secure connection & retry mechanism

### ISSUE THREAD

**Issue by SimpleApp** [grpc/grpc#8273]
While trying gRPC connexion over poor network conditions , it seemed that GRPCCalls made over tls were not retried (i kept having "Handshake read failed" errors immediatley followed by a code 14 error).

Is there any retry mechanism in place over secure connections ?

**Comment by jcanizales** [comment]
Craig and Muxi recently landed a fix for this. I don't know when it's planned to be released though.

**Comment by SimpleApp** [comment]
Thanks a lot ! 
Have any idea what the ETA could be (min / max) ? i've built a custom retry mechanism on top of the lib, and wonder if i should keep it or just wait for you guys to release the fix.

**Comment by muxi** [comment]
This fix should have already been merged into master branch. The upcoming v1.0.1 should also include this fix; the release process is kicking off on Monday. Feel free to choose any one of them. :)

**Comment by fabware** [comment]
Great to hear that.

**Comment by SimpleApp** [comment]
Great news, thanks. Did anyone had the chance to look at my other question regarding grpc streams ? ( https://github.com/grpc/grpc/issues/8272 )

I'm asking, because it is related in a way. Basically the question was if gRPC streams were supposed to be auto-reconnecting after a network disconnection, or not.
