### ISSUE TITLE
Building ruby is broken on MacOS: "Could not verify the SSL cert"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8294]
https://grpc-testing.appspot.com/job/gRPC_master_macos/41/console

```
Could not verify the SSL certificate for
https://rubygems.org/quick/Marshal.4.8/facter-2.4.6.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.

FLAKE: tools/run_tests/pre_build_ruby.sh [ret=17, pid=34647]
```

**Comment by apolcyn** [comment]
Waiting to see if the error continues after updating ssl certs with rvm, as suggested in http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by jtattermusch** [comment]
Definitely still an issue
https://grpc-testing.appspot.com/job/gRPC_master_macos/53/#showFailuresLink

**Comment by apolcyn** [comment]
update: updated ruby to 2.3 on mac workers.

Now seeing the error:
```
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff7d5c21ae8 cocoapods-1.0.1> (NoMethodError)
```

**Comment by jtattermusch** [comment]
Lifting this to P0. This issue is a week old and we can't afford not to run all ruby tests broken for that long (build is broken -> we aren't running any tests). If you have trouble solving this on your own, I'd suggest pulling in someone to help you.

**Comment by apolcyn** [comment]
It's currently is a 1.0.1 on mac workers, could this be a problem? As seen in https://github.com/grpc/grpc/pull/6884, about to begin downgrading cocoapods to 1.0.0. 
From what I can see, the missing SSL certs error isn't happening anymore, but after attempting to fix this by reinstalling/updating ruby deps on mac workers, something that's using cocoapods is now broken

**Comment by apolcyn** [comment]
watching https://grpc-testing.appspot.com/job/gRPC_master_macos/119/ after reverting cocoapods to 1.0.0

**Comment by jtattermusch** [comment]
@apolcyn  heads up, there's a stealth jenkins job that runs on mac workers sometimes and tries to update cocoapods (@jcanizales  or @makdharma might know more).
https://grpc-testing.appspot.com/view/All/job/MacOS-pod-periodic-update/

**Comment by apolcyn** [comment]
cc @jcanizales @makdharma, from https://grpc-testing.appspot.com/job/gRPC_master_macos/119/consoleFull, there is a different error with the objective-c build using cocoapods.

seeing:
```
XCODEBUILD_FILTER='(^===|^\*\*|\bfatal\b|\berror\b|\bwarning\b|\bfail)'
xcodebuild \
    build \
    -workspace *.xcworkspace \
    -scheme $SCHEME \
    -destination name="iPhone 6" \
    | egrep "$XCODEBUILD_FILTER" \
    | egrep -v "(GPBDictionary|GPBArray)" -
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/AuthSample-bueyxgfbdzvldffsmnhulvqnantb/Build/Intermediates/AuthSample.build/Debug-iphonesimulator/AuthSample.build/Objects-normal/x86_64/SelectUserViewController.o 
``` 

later down, what seems to be the issue is:
```
/jenkins/workspace/gRPC_master_macos/workspace_objc_macos_dbg/examples/objective-c/auth_sample/Pods/Headers/Public/Google/Google/SignIn.h:4:9: fatal error: 'GoogleSignIn/GoogleSignIn.h' file not found
```

**Comment by makdharma** [comment]
@muxi FYI..

**Comment by muxi** [comment]
I can confirm that we have a job running once a day to update the CocoaPods repo (not CocoaPods version) as we met problems before with CocoaPods not up to date.

**Comment by muxi** [comment]
I'm gonna take a look at the 'file not found' problem later today

**Comment by muxi** [comment]
The 'file not found' problem seems not to be consistent as later tests are not showing the same error. udp_server_test seems to be failing consistently though...

**Comment by muxi** [comment]
For record, the `method_missing' problem in objc test is due to a rubygem bug confirmed in https://github.com/rubygems/rubygems/issues/1420. Shall we update rubygems?

**Comment by apolcyn** [comment]
@muxi I think that sounds good. I just updated rubygems to 2.6.7 (it was at 2.5.1, with the fix mentioned to be in 2.6.3), with the 'rubygems-update' gem.

**Comment by muxi** [comment]
Awesome thanks! I'll check if it uses the right version.

**Comment by jtattermusch** [comment]
Looks like this is not an issue anymore. Please close if so.
