### ISSUE TITLE
grpc-tools is broken with Windows Rubyinstaller version

### ISSUE THREAD

**Issue by pbennett** [grpc/grpc#8301]
Using fresh ruby-2.2.5 extraction (32-bit) from http://rubyinstaller.org/, groc-tools can't find the embedded protoc binary.

The file /lib/ruby/gems/2.2.0/gems/grpc-tools-1.0.0/bin/grpc_tools_ruby_protoc has this code:

```
protoc_dir = File.join(File.dirname(__FILE__),
                       RbConfig::CONFIG['host_cpu'] + '-' + OS.os_name)
```

For the RubyInstaller Windows version (what everyone uses for Windows), host_cpu returns 'i686', yet the protoc.exe as created by installing the grpc-tools gem is in the directory:
lib\ruby\gems\2.2.0\gems\grpc-tools-1.0.0\bin\x86-windows
so it will only work if it's in the i686 directory, not x86.

**Comment by apolcyn** [comment]
fixed in https://github.com/grpc/grpc/pull/8304, will be in next release
