### ISSUE TITLE
requirements.txt incomplete

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#8308]
The requirements.txt file does not include all requirements that are necessary for the test infrastructure to run. Two cases that I am familiar with:
- virtualenv (required for run_tests.py)
- pyyaml (required for sanity tests)

**Comment by soltanmm-google** [comment]
@nathanielmanistaatgoogle @kpayson64 I'm not sure we want this... Do we want this?

I can see arguments in both directions:
* For adding: `requirements.txt` isn't used except from the repository source, and we don't expect normal users to ever touch the repository source (even if they build from source, they're building from the source we've packaged up and dumped on PyPI).
* Against: neither `pyyaml` nor `virtualenv` are requirements of the `grpcio` distribution, which the `requirements.txt` is supposed to be for.

**Comment by nathanielmanistaatgoogle** [comment]
Well before we can find an answer we have to agree on the question: what's the purpose or missing statement of `requirements.txt` anyway? Is it _supposed_ to be just what `grpcio` depends on? Is it _supposed_ to be everything necessary to build, test, package, and deploy `grpcio`? Or something else?

I thought I might find the answer [here](https://pip.pypa.io/en/stable/user_guide/#requirements-files) or [here](https://pip.readthedocs.io/en/1.1/requirements.html) but neither seems to come out and say.

**Comment by thunderboltsid** [comment]
I'd argue that the requirements.txt should contain everything that is required for a developer to develop for grpc and that would include everything required to build and test.
