### ISSUE TITLE
Don't try to compile msan, asan, tsan in parallel

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#8309]
The new matrix tests try to compile all sanitizers in parallel. 

This is unsafe: protobuf will only build in tree, so we'll end up with the potential to mix builds from different sanitizers, invalidating any findings we get from them.

**Comment by jtattermusch** [comment]
What we are doing is safe. Every configuration is running in a separate docker container (and thus has a completely different workspace).
 
Btw, on mac and windows we obviously don't have the luxury of separating with docker, but the parallel builds are isolated by running them in a different workspace
(see https://github.com/grpc/grpc/blob/master/tools/run_tests/run_tests_in_workspace.sh if curious).

Thanks for being vigilant and pointing out potential issue!
