### ISSUE TITLE
Avoid copying the full grpc_byte_buffer into NSData

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#8315]
When receiving a message from the C layer, a byte_buffer is read in its entirety and copied into a newly allocated `char` array, with which a `NSData` is initialized (in `NSData+GRPC.m`).

This copy can be avoided by using `grpc_byte_buffer_reader_next` instead of `grpc_byte_buffer_reader_readall`. In combination with `GPR_SLICE_START_PTR` and `GPR_SLICE_START_PTR`, each of the slices can be passed to [`dispatch_data_create`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/dispatch_data_create.3.html) to get a `dispatch_data_t` object that points to the `gpr_slice`. The chain of `dispatch_data_t`'s such created can be linked together with `dispatch_data_create_concat`, and the result can be transparently cast as `NSData *` and returned to the app.

Alternatively, the copy _and_ the traversal can be avoided by creating a subclass of `NSData` to wrap the `grpc_byte_buffer`. `NSData` subclasses have to implement `length` and `bytes`. But importantly we can also override `enumerateByteRangesUsingBlock:`, with which the user of the `NSData` can read the contents _in the same iteration in which we read and decompress the `grpc_byte_buffer` for the first time_. Protobuf parsing can leverage that (even though I think it currently doesn't - @ThomasVL to confirm for ObjC protos).

This goes the other way too: When receiving a `NSData` to pass to the C layer as a `grpc_byte_buffer`, creating `gpr_slice`s by iterating the data with `enumerateByteRangesUsingBlock:` will potentially eliminate one copy. Further, all copies whatsoever can be eliminated if instead of using `gpr_slice_from_copied_buffer` to create each slice, we use:

``` objective-c
[data enumerateByteRangesUsingBlock:^(const void *bytes, NSRange range, BOOL *stop) {
  // ...
  // (bytes is a valid pointer until data is dealloc'd)
  gpr_slice new_slice = gpr_slice_new_with_user_data(bytes,
                                                     range.length,
                                                     // Release data when the slice is released.
                                                     CFRelease,
                                                     // Retain data now.
                                                     (__bridge_retained void *)data);
  // ...
}];
```

This should be done once performance measurements are in place, so we can speak of specific numbers.

**Comment by thomasvl** [comment]
I don't believe you need to make an `NSData` subclass (and it likely wouldn't hurt to avoid it), instead you can create a composite out of the chunks.  We explicitly did this in some of [our tests](https://github.com/google/gtm-session-fetcher/blob/master/Source/UnitTests/GTMMIMEDocumentTest.m#L741-L756) to ensure we got parsing with `enumerateByteRangesUsingBlock` correct.  The only catch is making sure your pointers stay valid as long as the data does.

Those tests also show casting to an NSData to take advantage of the toll free bridging.

To your questions - no, the ObjC protobuf code would end up causing NSData to auto merge this, but we can revisit seeing if we could use `enumerateByteRangesUsingBlock`.  Even without the protobuf code being changed, it seems like it might be worth doing in grpc just so anyone using it has the option of doing better code.

**Comment by jcanizales** [comment]
To create a composite of `dispatch_data_t` out of the chunks, we need to traverse the whole `grpc_byte_buffer`. Which is cheaper than a copy (O(num of chunks) instead of O(num of bytes)), but is avoidable. C gRPC's interface for reading `grpc_byte_buffer`'s  is similar to `NSData`'s `enumerateByteRangesUsingBlock:` but, conveniently, uses an external iterator. So implementing the internal iteration of `enumerateByteRangesUsingBlock` with it might end up being pretty simple (famous last words).
