### ISSUE TITLE
Unable to make rpc calls within Electron

### ISSUE THREAD

**Issue by Roasbeef** [grpc/grpc#8319]
After pinning my Electron build against `1.2.8` and manually recompiling the node module to match the version of node that Electron uses within it's runtime, I'm unable to make any calls at all. 

Any attempted RPC calls result in the following error message: 

```
Uncaught Exception:
TypeError: Call's fifth argument must be another call, if provided
    at TypeError (native)
    at getCall (.../node_modules/grpc/src/node/src/client.js:334:14)
    at Client.makeUnaryRequest [as walletBalance] (.../node_modules/grpc/src/node/src/client.js:372:16)
    at EventEmitter.<anonymous> (/Users/
```

gRPC version: 
- 1.0.0 GA

It looks like these additional checks were added in #2942

**Comment by casesandberg** [comment]
We are recompiling with: 
```
./node_modules/.bin/node-pre-gyp --target=6.7.0 --runtime=electron --fallback-to-build --directory ./node_modules/grpc reinstall
```
And it errors when running a basic call such as:
```
client.method({}, (err, res) => {})
```

**Comment by murgatroid99** [comment]
I honestly have no idea how you triggered that error. With those method arguments, that constructor argument should be `undefined`. Can you use a debugger to see exactly what arguments are being passed to that constructor?

Have you tried passing a regular function expression (`function(err, res) {}`) instead of the arrow function? That shouldn't cause a problem, but it's the only part of your code I can see that's different from my tests.

**Comment by Roasbeef** [comment]
Passing a regular function expression yields the same.

Adding some `console.log`'s shows that all the variables (`parent`, `propagate`, etc) are `undefined` leading into the call to `grpc.Call`.

**Comment by murgatroid99** [comment]
Well, I would hope they're not all undefined. If `channel` or `method` are undefined, that should cause some other problems. But if the last 4 arguments are undefined and that check is still triggering, I don't know what's going on.

Can you put together a simple test case that triggers this behavior?

**Comment by murgatroid99** [comment]
The npm module grpc@1.1.0-pre1 should now work on electron. Make sure that you follow the instructions in the electron docs for [installing native modules](http://electron.atom.io/docs/tutorial/using-native-node-modules/). You should be able to omit the line `export npm_config_build_from_source=true` to install the precompiled binary file for electron.

It may be that you will no longer see this problem with the new version.

**Comment by murgatroid99** [comment]
This should now work. This issue can be reopened if this is still a problem.

**Comment by casesandberg** [comment]
Works now, can confirm.
