### ISSUE TITLE
Fine tune rebooting of Jenkins workers

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8321]
The reboot procedure at the end of the builds is not 100%. Sometimes the reboot happens to early and fails the current job. 
Possibly (unconfirmed) the reboot might happen too late and a fail the next job that is scheduled to run on the same worker immediately afterwards.

**Comment by jtattermusch** [comment]
FYI @markdroth

**Comment by matt-kwong** [comment]
I made a job specifically to reboot workers safely when a job is done that also blocks other jobs from building until after the worker reboots. After monitoring Jenkins for a few days, I don't see any issues related to a worker going offline during a job.
