### ISSUE TITLE
Doing a async callback in a sync call

### ISSUE THREAD

**Issue by rllola** [grpc/grpc#8331]
I am trying to use an async service to create a callback to an action. The thing is that I want the async method to be call for every client connected.
Here some code : 
```
  Status AddTask(ServerContext* context, const Task* request,
                    Void* reply) override {

    std::cout << "A Task is being add" << std::endl;

    //Call async service here now
    std::cout << "Before RequestOnTask" << std::endl;
    service_->RequestOnTask(&ctx_, &request_, &responder_, cq_, cq_,(void*)1);
    std::cout << "After RequestOnTask" << std::endl;
    reply_.set_name("Go to the gym");
    std::cout << "AddTask : " << tag << std::endl;
    responder_.Finish(reply_, Status::OK, (void*)2);

    return Status::OK;
  }
...
  void HandleRpcs(TodoListServiceImpl *service2_) {
    void* tag;
    bool ok;
    while (true) {
      GPR_ASSERT(cq_->Next(&tag, &ok));
      GPR_ASSERT(ok);
      //static_cast<CallData*>(tag)->Proceed();
    }
  }
```
It works if I launch the main.js example once but on the second time it fails.

Here a link to the github : https://github.com/rllola/gRPC-test

I am not sure this is the way to do it. If other solution are possible I will be interested in them.

Thanks,

**Comment by yang-g** [comment]
It is really hard to understand what you are trying to do. You have a sync service and an async service and they change the status of each other, which is confusing to me.

That being said, I think the reason of your failure of the second test is that in your Announce() function you bypassed the creation of a new CallData as in the Proceed(). So a new CallData is never created and no one is fetching the next RPC. I guess adding a "new CallData(service_, cq_);" in Announce() will make the sequential calls work.

**Comment by rllola** [comment]
@yang-g Thanks for your answer. Actually the code on the repo is working now.

I am going to try to explain better what I am trying to do : 
What I want to do is to send the result of the task being added or not to an async method. In my original code (that I can't show) this part : 
```
    reply_.set_name("Go to the gym");
    std::cout << "AddTask : " << tag << std::endl;

    if(tag)
static_cast<CallData*>(tag)->Announce(reply_);
```
is being executed in a callback so I will send the asnwer of the task being add in a async method.

Then I wanted to notify all other client connected to the application that a new task has been added but I figure out that a rpc method which return a stream of `Event` would be the best way to do it. 

 I will try to rewrite this complete example. It is suppose to be a ToDo List app.

**Comment by yang-g** [comment]
Good to know it is working. Streaming events sounds like the right thing to do. It seems you want something like an AddTask() unary rpc and a Listen() server streaming call. Each Listen call will add itself to a container and each AddTask callback will get the container and write an event to all of them. If you have many listeners, using async API sounds like a right thing to do.
