### ISSUE TITLE
Cannot import predefined google/protobuf/*.proto in node environment.

### ISSUE THREAD

**Issue by ldshi** [grpc/grpc#8339]
import "google/protobuf/empty.proto";
import "google/protobuf/any.proto";

will try to find the file with path: **__dirname + google/protobuf/empty.proto**, also tried to search the whole grpc node_module, cannot find the corresponding files.

what should I do?

**Comment by thinkerou** [comment]
You should use the follow code?

    import "src/proto/grpc/testing/empty.proto"

**Comment by leonard-sxy** [comment]
For the 'empty.proto' i can see the file is there, but for the 'any.proto' totally no that file.

And also in node environment with dynamic mode, no idea how to control the path.

**Comment by thinkerou** [comment]
➜  grpc git:(master) pwd
    /Users/thinkerou/Documents/opensource/grpc
    ➜  grpc git:(master) find . -name "any.proto"
    ./third_party/protobuf/src/google/protobuf/any.proto
    ➜  grpc git:(master)

**Comment by leonard-sxy** [comment]
In node environment, all modules supposed to be maintained by npm, so did u try to search int he node_module installed by 'npm install grpc'? i mentioned this very clearly in the issue description.

Apparently u should not download all the source then search there.

**Comment by dehypnosis** [comment]
same issue..

**Comment by HTChang** [comment]
@nathanielmanistaatgoogle  so what is the best practice to include the predefined proto like empty?
the path we use is
```
 import "google/protobuf/empty.proto";
```
the proto was used for multiple language like go, java which is not just for JS.

**Comment by zhangtaodeveloper** [comment]
This question is not answered, many people have this doubt

**Comment by thedodd** [comment]
Would definitely be nice to see a resolution to this issue. Else, workaround seems to be: drop use of `google/protobuf` types, and implement your own types as somewhat close replacements.

In rust, golang and other languages where code generation is used for protobuf/grpc, this is not an issue.

**Comment by murgatroid99** [comment]
We have now published the `@grpc/proto-loader` package, which allows for loading `google/protobuf/*.proto` files. If you have this problem, please try that package out.
