### ISSUE TITLE
udp_server_test fails with "assertion failed: g_number_of_orphan_calls == 1"

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#8341]
At current master HEAD ([fbfb05acc8c97487d75404afe92661d1e6384dd7](https://github.com/grpc/grpc/tree/fbfb05acc8c97487d75404afe92661d1e6384dd7))

See https://gist.github.com/dgquintas/39ab2635a475a1627e737f1cbed3561f

**Comment by rjshade** [comment]
This will be fixed by https://github.com/grpc/grpc/pull/8333

**Comment by vjpai** [comment]
Fixed by #8333 , rebroken afterward.
