### ISSUE TITLE
NodeJS Callback Functions

### ISSUE THREAD

**Issue by vish74** [grpc/grpc#8357]
I am creating RPC service with Empty response parameter.
`rpc Disconnect (getDisconnect) returns (Empty) {}`

Client code is in Javascript. Why do I need to write return callback function?

`client.disconnect({status:0});` 
throws 
`Error: parameter 'callback' waiting for Function argument but received Undefined`

As far I know, gRPC or protobuf documents don't mention anywhere that callback functions are mandatory. Is there any workaround?

I am trying to understand, do gRPC server care for client's response messages?

From: [2237](https://github.com/google/protobuf/issues/2237)

**Comment by murgatroid99** [comment]
Node gRPC is asynchronous. The callback you provide is called asynchronously when the call completes with an error if the call failed, and the response message. An empty callback should work just fine, though I would generally recommend at least checking the response status.

**Comment by vish74** [comment]
Agree to asynchronous behavior of NodeJS but from my understanding of server client design, client callbacks or its definition should be optional. Some of the end of execution API/functions may not require any status acknowledgment.

**Comment by murgatroid99** [comment]
The situation you are describing is just as well handled by providing a no-op function. Making the parameter optional just to avoid passing no-op functions is not worth the cost of the additional complexity.

Plus, if we decide now to make it optional and treat the absence as a no-op, that precludes some other possible expansions in the future, like treating the absence as indicating that a Promise should be returned.

**Comment by kinghadi** [comment]
it doesn't work with `async/await` syntax in `ES7`. I mean the following:

```js
let err, reply = await client.createUser(userCreateRequest)
```
how to handle these situations?

**Comment by murgatroid99** [comment]
It's a regular asynchronous function; it doesn't return a promise. You may be able to use `util.promisify`, but keep in mind that this will probably discard the returned call object, which gives you the response metadata and the ability to cancel the call.
