### ISSUE TITLE
Allow servers to enter lameduck state

### ISSUE THREAD

**Issue by therc** [grpc/grpc#8363]
Overloaded servers should have a way to signal clients that they can't process any further requests temporarily. That could be done by sending them a GOAWAY/NO_ERROR. Conversely, it should be possible to resume normal operation, but I'm not sure how that would be signaled to the client, especially if they disconnect upon detecting lameduck mode...

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: this would be implemented as a Core feature, right? Is this something we've thought about doing and rejected, thought about doing and rejected, or not yet thought about doing?

**Comment by ejona86** [comment]
GOAWAY prevents any new RPCs from ever occurring on the connection. You can't re-enable RPCs on the connection after GOAWAY.

**Comment by therc** [comment]
@ejona86 thanks, I suspected as much, but wasn't sure. Perhaps a grpc-lameduck trailer in a response or a special ping if no RPCs are in flight?

Stubby has such a feature (see pg. 234 of http://shop.oreilly.com/product/0636920041528.do). The even big question is how to detect that a backend is ready again. It could be a) in-band with pings, if a connection is open, b) out of band through UDP like Stubby does for inactive connections, c) through the grpclb protocol if you're using it or d) a mix of those.

**Comment by ejona86** [comment]
@therc, I think we'd push for c. When a server goes down it informs the LB and then does GOAWAY and graceful shutdown. Clients reconnect to a new address as guided by LB. We are going to use PINGs, but for TCP-level checking, not service-level checking. There's no plan to do UDP health checking, as we want to rely on centralized health checking instead for reduced waste and less DDoS risk.

You can see our planned use of PING in [a comment of mine](https://github.com/grpc/grpc-java/issues/1648#issuecomment-207581337). I'm now working on a design to allow doing PING even if there are no outstanding RPCs, which can be used as a poor man's health checking.

**Comment by therc** [comment]
Thanks. Is the plan still not to provide an "official" implementation of the load balancer?

I see also that the grpclb v1 proto doesn't seem to have any way yet for servers to report their load.

**Comment by ejona86** [comment]
The plan is still not to have an open source LB implementation. I'm not sure what the plan is for load reporting service.

**Comment by therc** [comment]
Any comments on load reporting for servers? If Google does not plan to open source the message definitions for server<->LB communications, let alone a GSLB clone, perhaps `load_balancer.proto` should mention that. I understand that the original messages might be too tied to the minutiae of Borg or other Google internal infrastructure. 

Right now the comment for `load_balance_token` is confusing or even misleading, especially if you have never worked at Google. :-) It also uses frontend/backend instead of client/server as the rest of the file does, which probably makes the reader wonder if it's a reference to two additional and separate entities.

**Comment by ejona86** [comment]
CC @zhangkun83, for the `load_balance_token` comment in `load_balancer.proto`.

**Comment by AspirinSJL** [comment]
@therc We plan to open source the server-side load reporting *soon*.

**Comment by therc** [comment]
@AspirinSJL that's great, thanks. Looking forward to it.

**Comment by AspirinSJL** [comment]
1. The `load_balance_token` comment will be improved in #15811. 
2. We're actively working on server-side load reporting. It's actually under review now. 

I'm closing this issue because the questions have been answered as I read. @therc Please feel free to re-open it if you have any further question or want a callback from me when the server load reporting feature is fully done. Thanks!
