### ISSUE TITLE
Need to commit modified-codes after git-submodule-update

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#8374]
branch: `master`
steps:

1. git submodule update --init
2. git status

It will have the follow informations:

	➜  grpc git:(php_grpc_add_property_zval) ✗ git status
	On branch php_grpc_add_property_zval
	Changes not staged for commit:
	  (use "git add <file>..." to update what will be committed)
	  (use "git checkout -- <file>..." to discard changes in working directory)

		modified:   third_party/nanopb/CHANGELOG.txt
		modified:   third_party/nanopb/docs/concepts.rst
		modified:   third_party/nanopb/docs/index.rst
		modified:   third_party/nanopb/docs/migration.rst
		modified:   third_party/nanopb/docs/reference.rst
		modified:   third_party/nanopb/docs/security.rst
		modified:   third_party/nanopb/extra/pb_syshdr.h
		modified:   third_party/nanopb/generator/nanopb_generator.py
		modified:   third_party/nanopb/generator/proto/nanopb.proto
		modified:   third_party/nanopb/pb.h
		modified:   third_party/nanopb/pb_decode.c
		modified:   third_party/nanopb/pb_decode.h
		modified:   third_party/nanopb/pb_encode.c
		modified:   third_party/nanopb/pb_encode.h
		modified:   third_party/nanopb/tests/fuzztest/fuzztest.c
		modified:   third_party/nanopb/tests/mem_release/mem_release.c
		modified:   third_party/nanopb/tests/mem_release/mem_release.proto
		modified:   third_party/nanopb/tests/multiple_files/SConscript
		modified:   third_party/nanopb/tests/multiple_files/test_multiple_files.c
		modified:   third_party/nanopb/tests/site_scons/site_tools/nanopb.py

	no changes added to commit (use "git add" and/or "git commit -a")

**Comment by vjpai** [comment]
Our inclusion of nanopb changed recently. It used to be a submodule but is now integrated into the grpc repo.
