### ISSUE TITLE
Individual Test Timeouts

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#8379]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_sanitizers_linux/197/testReport/junit/(root)/aggregate_tests/run_tests_c_linux_msan/

It looks like only aggregate tests are timing out, making it difficult to determine the culprit.

Possibly related:
https://github.com/grpc/grpc/pull/8352

**Comment by jtattermusch** [comment]
It looks like this might be timing out since we removed the --force_default_pollers and more tests are being run by sanitizers.
I'll look into increasing the timeout.

**Comment by jtattermusch** [comment]
Timeout already increased by #7664.
