### ISSUE TITLE
building python benchmark workers requires python3.4 (not available on current ubuntu)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8383]
and python3.4 is not available on ubuntu 16.04LTS. That leads to ugly hacks.

See 
https://github.com/jtattermusch/grpc/blob/ab0a72765588009b5dd840f7bef8d0738310ad53/tools/gce/linux_performance_worker_init.sh#L95

in https://github.com/grpc/grpc/pull/8375

**Comment by nathanielmanistaatgoogle** [comment]
This is a team-only team-internal issue; I don't see any reason for it to block the `1.1.0` release. Punting (please correct me if there's something I'm missing!).

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch, @kpayson64: please assess a priority for this issue?

**Comment by kpayson64** [comment]
I'm not sure what the desired outcome is, if we want to test against Python3.4, then we need Python3.4 installed.  Is this issue suggesting that we test against an arbitrary python 3 version, whatever happens to be on the system?
