### ISSUE TITLE
Performance sweep suite takes 18 hours, blocks other jobs

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8384]
the suite takes extremely long to finish and it's blocking other performance related jobs from running (actually I think that's the reason why the performance dashboard has become sparse recently 
- see https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968)

Do we really need to run all the configurations that are currently in the sweep suite? If so, please get a dedicated set of VMs for the sweep suite to run on (grpc-benchmark-sweep, driver, server, client1 and client2).

**Comment by jtattermusch** [comment]
CC @matt-kwong

**Comment by ctiller** [comment]
Yeah, I'd prefer to set up some new vms for this. I expect the set to grow,
not shrink. They're really useful.

**Comment by jtattermusch** [comment]
@matt-kwong , do you want get some practice in setting up the workers? Benchmarks are an important part of our infrastructure, so it's good to understand how it works.

You can use the create-linux-performance-worker script from my PR https://github.com/grpc/grpc/pull/8375. You can ask me or Nico if you get stuck.

**Comment by matt-kwong** [comment]
Yeah, I'll take care of it.

**Comment by matt-kwong** [comment]
A new set of VMs dedicated to running performance sweep suite was set up and successfully ran its first job on Jenkins.
