### ISSUE TITLE
udp_server_test consistently fails on Mac

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8386]
https://grpc-testing.appspot.com/job/gRPC_master_macos/167/#showFailuresLink

```
D1016 07:34:52.594965000 140735232365312 test_config.c:277] test slowdown: machine=1.000000 build=1.000000 total=1.000000
D1016 07:34:52.597706000 140735232365312 ev_posix.c:106] Using polling engine: poll
I1016 07:34:52.598032000 140735232365312 udp_server_test.c:92] "test_no_op_with_start"
I1016 07:34:52.598048000 140735232365312 udp_server_test.c:103] "test_no_op_with_port"
E1016 07:34:52.598164000 140735232365312 udp_server.c:238] Unable to set ip_pktinfo.
E1016 07:34:52.598179000 140735232365312 udp_server_test.c:114] assertion failed: g_number_of_orphan_calls == 1



*******************************
Caught signal 6
  no backtrace
```

**Comment by jtattermusch** [comment]
@ctiller , please reassign accordingly. Can @rjshade  take a look?

**Comment by jtattermusch** [comment]
This actually prevents green color of tests most of the times and green tick makes things so much more easier.

**Comment by rjshade** [comment]
The problem is that the attempt to set the IP_PKTINFO sockopt fails on Mac, here:

https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/udp_server.c#L238

Is this sockopt (or equivalent) available on Mac?

The simplest fix for now is to disable udp_server_test, on Mac only.
