### ISSUE TITLE
How to test grpc apis built on NodeJS?

### ISSUE THREAD

**Issue by VikramTiwari** [grpc/grpc#8390]
The current approach that I am following is based upon testing the services that are exposed with the grpc. But how do I check if grpc part (aka networking) is working fine itself?

Ref: https://github.com/VikramTiwari/webstack/issues/6

**Comment by sreecha** [comment]
@VikramTiwari : Sorry, this has been unanswered for so long.  Is your question still relevant ? or did you find other alternatives?

**Comment by VikramTiwari** [comment]
Hey this has been solved. Please feel free to close this. Thanks!
