### ISSUE TITLE
Is gRPC service thread safe?

### ISSUE THREAD

**Issue by yufeiren** [grpc/grpc#8391]
Since there is a pool of threads running on grpc server, will the grpc service be thread-safe? For example, if I define a shared data structure in a ServiceImpl that would be modified by a service function. Should I protect the shared data structure explicitly by using locking/mutex?

**Comment by yang-g** [comment]
You will need to protect the shared data in your implementation.

**Comment by yufeiren** [comment]
I didn't find documentation that mentioned this explicitly. It might be good to have it in the grpc documentation/tutorial.
