### ISSUE TITLE
grpc SSL -> load default system wide bundled certificate

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#8393]
Hello,

If not providing the **root CA.crt** to the grpc client, is grpc going to check at the OS level for the **main bundled** root CA.crt?

For example `/etc/ssl/certs/ca-certificates.crt` for Debian distributions.

Or do I need to implement this logic myself into my client app?

many thanks!

**Comment by a11r** [comment]
grpc does check at the OS level for the main bundled root CA.crt but not sure if it looks in the debian specific location you pointed to.

**Comment by jboeuf** [comment]
Unfortunately, we don't have per-platform magic that informs gRPC on how to use the platforms roots.
If you install gRPC, it will use by default the roots shipped with gRPC (they come from Mozilla and are updated about every month): see https://github.com/grpc/grpc/blob/master/etc/roots.pem

If you want to use the debian ones, I suggest that you set the `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` env variable to `/etc/ssl/certs/ca-certificates.crt`. Does that make sense?

**Comment by sulliwane** [comment]
Many thanks, that looks fine for me.

@murgatroid99, One practical question then: On the node grpc client side, here is how I load the **root CA.crt**:
```javascript
sslCaCrt = fs.readFileSync(sslCaCrtPath);
const sslCreds = grpc.credentials.createSsl(sslCaCrt);
const grpcClient = new myProto.myPackage.myService(serverURL, sslCreds, clientOptions);
```
But in case I want my client to use **the bundled root CA.crt from Mozilla** without me telling him the path, what the code will looks like? Thanks

**Comment by jboeuf** [comment]
If you just call `grpc.credentials.createSsl()` without a parameter, it will just use the default which are the roots from Mozilla (assuming that you have installed gRPC). Otherwise, the env var above works as well.

**Comment by sulliwane** [comment]
Ok, thanks!
