### ISSUE TITLE
How to write middleware for grpc (node.js)

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#8394]
I'm attaching a metadata to each client grpc service call (containing a jwt token), and I'd like to validate this token on the server, once globally (instead of repeating the validation code in each server service definition).

From my understanding, there is something called "Interceptor" for grpc, which is somewhat similar to http middleware.

Any example for Nodejs grpc interceptor? (or any other way to achieve something similar with http middleware?)

Many thanks!

**Comment by murgatroid99** [comment]
This functionality is not currently available in Node.

**Comment by jhspaybar** [comment]
@murgatroid99 We're deep into gRPC on the Java side ourselves and this is becoming very important for us to have NodeJS client interceptors as we have in the Java world.  We are happy to get involved and contribute if that's the proper path, how can we get involved?

**Comment by murgatroid99** [comment]
Currently, we don't even have a design for that feature. If you propose a design, that is the most likely thing to push this feature forward.

**Comment by jhspaybar** [comment]
@murgatroid99 Is this still not designed and seeking input?  I saw a couple days ago someone sent out a link to this https://github.com/malijs/mali which is a separate project and provides middleware support.

Would it be appropriate still to contribute a design and then start work on an implementation for NodeJS, or is there work being done at Google or elsewhere we'd be conflicting with?

**Comment by goodmind** [comment]
Is there any updates?

**Comment by jhspaybar** [comment]
A proposal is here https://github.com/grpc/proposal/pull/14

And the implementation is here https://github.com/grpc/grpc/pull/9842

**Comment by c3s4r** [comment]
The proposal only includes interceptors on the client side, not on the server side, right?

My team has been working on a framework to support middleware on the server side (along with other features). It's still alpha, but we are using it for a large project (not on production yet).

For anyone interested:

- https://github.com/devsu/condor-framework
- http://condorjs.com/

We have our own implementation, but planning to use the official implementation when available. Any feedback is welcome.
