### ISSUE TITLE
gRPC C++ support on iOS and Android

### ISSUE THREAD

**Issue by andrewheard** [grpc/grpc#8398]
C++ is more commonly being used for cross-platform mobile (Android and iOS) development. It would be nice if gRPC could officially support these platforms in C++.

Currently developers would either need to:
- Write a C++ wrapper around the ObjC and Java APIs.
- Rely on the C++ generated stubs which are not officially supported on both platforms.

**Comment by staypufd** [comment]
Any timeline on adding support for C++ on Android?

**Comment by fileoffset** [comment]
Please merge those changes in! I managed to build native c++ android libraries that actually work using Slonegg's changes and instructions, hand-merged into grpc and protobuf 3.3.0.

**Comment by lumpidu** [comment]
We are using C++ already successfully in production on iOS11, but we are stuck with a hand-crafted version of 1.0.1 and really would like to upgrade to a more recent version. We need C++ on iOS because we provide a C-SDK on different platforms for communication to devices and internally use C++ inside the SDK. It would be highly appreciated if C++ would be a first class citizen on iOS. Any hint about what to do for recent gRPC versions to compile for iOS besides manually maintaining a private CMakeLists.txt ?

**Comment by ericgribkoff** [comment]
cc @muxi for status on the iOS side

Regarding C++ builds for Android, I've just started looking into this and expect it to be supported sometime this quarter.

**Comment by lumpidu** [comment]
We ported ourselves gRPC to Android already. We could trade this in against the C++ iOS support :D

**Comment by muxi** [comment]
We have started this work on iOS. The tracking issue is #13582. An initial PR in review at #13935

**Comment by lumpidu** [comment]
That is great to see!

**Comment by ericgribkoff** [comment]
@lumpidu Do you have any interest in making your port of gRPC C++ to Android public? Either as a PR here to directly add Android support to our build system, or as a stand-alone example in another repository?

**Comment by lumpidu** [comment]
@ericgribkoff : we are interested and just have to prepare a gist/repository for it

**Comment by ngriffiths** [comment]
I worked with @lumpidu to build gRPC C++ for Android. Here is a script that clones, patches where necessary for Android and builds most of gRPC, together with the patches:

https://gist.github.com/ngriffiths/0125eb574354e40fe6f12de1ce2f4713

**Caveat:** This is very hacky. My understanding of gRPC and building C++ code is very limited. My sole focus at the time I wrote it was producing the binaries for @lumpidu and his team. I was largely following the cross-compilation instructions buried in the Makefile, which I've copied into the header of the script for reference.

**Comment by ericgribkoff** [comment]
@lumpidu @ngriffiths That's great, thank you for sharing that! I also went through the process of getting the build working with CMake (which I believe is the current recommended native build method in Android Studio, and has some pretty nice integration with Android Studio and gradle) in https://github.com/grpc/grpc/pull/14193

**Comment by JonasVautherin** [comment]
@ericgribkoff @muxi I don't know if it is relevant or not, but using the CMakeLists.txt patch in #14193 and setting `third_party/boringssl` to `56d5d7085dd1beea9af220678091fc51e4b50d3e`, I managed to build for iOS using the following cmake arguments (and [this iOS toolchain](https://github.com/leetal/ios-cmake)):

> cmake -DCMAKE_TOOLCHAIN_FILE=iOS.cmake -DIOS_PLATFORM=OS -DRUN_HAVE_POSIX_REGEX=0 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_STEADY_CLOCK=0 -Dprotobuf_BUILD_PROTOC_BINARIES=off -DgRPC_BUILD_CODEGEN=off ..

I understand that some people want to use CocoaPods, but in my situation, I prefer building with CMake.

**Comment by muxi** [comment]
Thanks a lot Jonas. We will put cmake after Cocoapods, but I'll definitely give a try.

**Comment by lumpidu** [comment]
what about iOS?

**Comment by muxi** [comment]
We have [podspec](https://github.com/grpc/grpc/blob/master/gRPC-C%2B%2B.podspec) now. Give a try.
