### ISSUE TITLE
clang-format versions produce different results

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#84]
Let's choose a version, tweak its parameters, and settle on it for this project.

**Comment by murgatroid99** [comment]
Is this still an issue? Or did that last pull request resolve it?

**Comment by yang-g** [comment]
That last pull request is using clang-format-3.5 to format all the c++ code only. That said, we are not tweaking any parameters anyway but just using style=google. I am not sure how much difference different clang-format versions will make here. We do not have a clang-format script under tools anymore.

**Comment by murgatroid99** [comment]
What I'm trying to get at is this: is this issue resolved? If not, what else do we need to do?

**Comment by yang-g** [comment]
I think we can mark it obsolete now.
