### ISSUE TITLE
GRPC segfault for the example (Greeter)

### ISSUE THREAD

**Issue by manavgarg** [grpc/grpc#8400]
I am getting GRPC segfault for the Greeter example on running the client:
Here is the trace:
#0  0x00007fffec003910 in ?? ()
#1  0x00007ffff661f71a in grpc_combiner_execute () from /usr/local/lib/libgrpc.so.1
#2  0x00007ffff6644332 in grpc_create_chttp2_transport () from /usr/local/lib/libgrpc.so.1
#3  0x00007ffff66658ad in ?? () from /usr/local/lib/libgrpc.so.1
#4  0x00007ffff66657ec in ?? () from /usr/local/lib/libgrpc.so.1
#5  0x00007ffff7b9a131 in ?? () from /usr/local/lib/libgrpc++.so.1
#6  0x00007ffff7b95ff7 in grpc_exec_ctx_flush () from /usr/local/lib/libgrpc++.so.1
#7  0x00007ffff7b90f23 in ?? () from /usr/local/lib/libgrpc++.so.1
#8  0x00007ffff7ba375d in grpc_completion_queue_next () from /usr/local/lib/libgrpc++.so.1
#9  0x00007ffff7b7b208 in grpc::CompletionQueue::AsyncNextInternal(void*_, bool_, gpr_timespec) () from /usr/local/lib/libgrpc++.so.1
#10 0x00007ffff7b7e9a6 in grpc::Server::RunRpc() () from /usr/local/lib/libgrpc++.so.1
#11 0x00007ffff7b7b662 in grpc::DynamicThreadPool::ThreadFunc() () from /usr/local/lib/libgrpc++.so.1
#12 0x00007ffff7b7b853 in grpc::DynamicThreadPool::DynamicThread::ThreadFunc() () from /usr/local/lib/libgrpc++.so.1
#13 0x00007ffff7264a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff69c2184 in start_thread (arg=0x7ffff5ad4700) at pthread_create.c:312
#15 0x00007ffff6cd237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Any clue as to where I am going wrong ?

**Comment by vjpai** [comment]
Can you describe your platform and your compilation type? We could probably get more info from a debug build.
