### ISSUE TITLE
php extension failed to build with gcc

### ISSUE THREAD

**Issue by 0x1997** [grpc/grpc#8408]
`-Wno-parentheses-equality` at [L42 of config.m4.template](https://github.com/grpc/grpc/blob/master/templates/config.m4.template#L42) is not available in gcc.

**Comment by thinkerou** [comment]
Your version of gcc?

**Comment by 0x1997** [comment]
@thinkerou `gcc (GCC) 6.2.1 20160830`

**Comment by stanley-cheung** [comment]
Can you give a little more info on how to reproduce this? I just tried Ubuntu 16.10 that come standard with gcc 6.2.0 and I can install the extension with `sudo pecl install grpc` with no problem.

**Comment by 0x1997** [comment]
@stanley-cheung Thanks. Not sure why but it works now. I'll close this.
