### ISSUE TITLE
golden_file_test not very helpful

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8428]
golden_file_test has two kinds of problems:

1. It's a change detector test. Any change to the codegen, including new comments, will break the test since it just diffs the C++ codegen result with the committed test content. When adding new features to generated code, it's just easier to ignore this test and copy the newly generated code to  be the new golden file. After all, any real breakages in the codegen will get detected by the extensive end2end test suites.

2. It's not sufficient. Why just check C++ code generation? Why not Ruby, Node, etc? All of these languages also have codegen plugins that we provide, and they're just as likely to run into codegen issues. Arguably a codegen test is even more important for some of those languages since their test suites are generally less extensive than that used in C++.

I propose eliminating golden_file_test and the concept of golden files, and I'll send in a PR along these lines shortly. We can decide there if that's important. Feel free to LBTM it if it's a terrible idea.

**Comment by ctiller** [comment]
They do have one important advantage: they provide a diff in code review on
the actual generated changes.
Without such, code review of generator changes relies on mental gymnastics
for the reviewer to figure out what's going to really change.

Copying the newly generated code is indeed the right thing to do (and then
reviewing that those changes are indeed what's intended).

... I'd vote to extend coverage to the other languages.

**Comment by vjpai** [comment]
Ok, I'll take that as a reasonable answer. I'll file issues for the other languages in the near future then.

**Comment by vjpai** [comment]
https://github.com/vjpai/grpc/tree/pyrite @ e32b5d3 if anyone thinks elimination is the right approach.
