### ISSUE TITLE
iOS gRPC SSL

### ISSUE THREAD

**Issue by Vincent-rc** [grpc/grpc#8433]
## Hi, I want to enable https in my project,but I can't find  an Objective-C demo.

Here is My codes:

```
    NSString *certsPath = [[NSBundle mainBundle] pathForResource:@"cacert_product" ofType:@"pem"];
    NSError *error;
    NSString *contentInUTF8 = [NSString stringWithContentsOfFile:certsPath
                                                        encoding:NSUTF8StringEncoding
                                                           error:&error];
    [GRPCCall setTLSPEMRootCerts:contentInUTF8
                         forHost:sharedInstance.hostAddress
                           error:nil];
```

Debug window shows error as below:

Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E1020 10:30:42.316105000 123145515057152 handshake.c:128] Security handshake failed: {"created":"@1476930642.316073000","description":"Handshake failed","file":"/Users/rc/Documents/PPMoneyPro/Pods/gRPC-Core/src/core/lib/security/transport/handshake.c","file_line":264,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}

Anyone help?3Q!

**Comment by freeman22** [comment]
Has the problem been solved yet?

**Comment by freeman22** [comment]
I've had the same problem.

**Comment by muxi** [comment]
Hi! Your code seems okay. The error shown on your debug window seems to be a TLS version mismatch. Could you please let us know which versions of gRPC client and server are you using?

**Comment by Vincent-rc** [comment]
Problem solved.The client was gRPC 1.0.0,but server side was 1.0.0-pre1. When pod update,everything went ok >.<

**Comment by muxi** [comment]
Got it. Thanks for the update!

**Comment by acoroian** [comment]
It is still happening to me with gRPC 1.0.2

**Comment by muxi** [comment]
Hi @acoroian, could you please paste your error message here and confirm which versions of client/server are you using please? I am unable to reproduce this problem right now.

**Comment by acoroian** [comment]
@muxi the certificate i was using was bad so it ended up giving me that a SSL Version error when trying to connect. We used a different ssl certificate and made it work.

**Comment by muxi** [comment]
@acoroian OK thanks for letting us know.

**Comment by zingwin** [comment]
Hi 
i use grpc 1.2.0-pre2, the same error
`NSString *certsPath = [[NSBundle mainBundle] pathForResource:@"babystory" ofType:@"pem"];
    NSError *error;
    NSString *contentInUTF8 = [NSString stringWithContentsOfFile:certsPath
                                                        encoding:NSUTF8StringEncoding
                                                           error:&error];
    [GRPCCall setTLSPEMRootCerts:contentInUTF8 withPrivateKey:nil withCertChain:nil forHost:@"myhost.com:50052" error:nil];`

` ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
`
