### ISSUE TITLE
C++ tests failing on Mac Yosemite with "Too many open files"

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#8436]
FAILED: bins/opt/thread_stress_test --gtest_filter=End2endTest/0.ThreadStress 
FAILED: bins/opt/thread_stress_test --gtest_filter=End2endTest/1.ThreadStress 

Error message:
E1020 10:33:33.039445000 123145373667328 completion_queue.c:646] Completion queue next failed: {"created":"@1476984813.039266000","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":53,"os_error":"Too many open files","syscall":"pipe"}

We should do one of the following:
1. modify the test so it fits with open FD limit on a typical high end Mac
2. Not run the test
3. Provide a way to modify system's open FD limit.

**Comment by ctiller** [comment]
Ruling out 1 & 2.

**Comment by nicolasnoble** [comment]
http://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

Here's how to reconfigure the systems to allow for higher ulimit values.

**Comment by makdharma** [comment]
I think it is bad user experience for devs to have to do a google search
for fixing something that can be easily fixed in scripts.
