### ISSUE TITLE
If exception occurs in server-side Python handler, report it to the user

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#844]
When working on the route guide, any exceptions thrown by the servicer's methods were hidden from me. This makes development of python server very painful, because if things don't work, you have to basically guess what's wrong and fix it.

**Comment by nathanielmanistaatgoogle** [comment]
This is fixed (through status code conformance) as of 1d750d6ca2d878385e. Status code conformance is as good as we're going to get; I don't think we'll ever serialize stack traces and propagate them through the details string or anything. That wouldn't be crazy; it just doesn't seem generally applicable.
