### ISSUE TITLE
grpc::CompletionQueue needs method to notify a custom operation has completed.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [grpc/grpc#8442]
Let's say I have one thread and one loop that looks something like this:

```
  do {
    bool ok;
    Tag* tag;
    // Wait for a pending operation to complete.  Identify the operation that
    // completed by examining tag.
    switch (cq.AsyncNext((void**)&tag, &ok, next_write_time_point)) {
      case grpc::CompletionQueue::SHUTDOWN:
        std::cerr << "The completion queue unexpectedly shutdown." << std::endl;
        return -1;
      case grpc::CompletionQueue::GOT_EVENT:
        std::cout << tag->name << " completed." << std::endl;
        ....
    }
  } while (true);
```

And I'm calling same third-party library that invokes my callback when that third-party library completes a task.  I want to act on the third-party libraries task completion in my same `do { } while;` loop.

To synchronize, I need a thread-safe method on `CompletionQueue` called something like `Notify(void* tag)`.  Then my callback can look like this:

```
  third_party_library.SomeLongRunningTask(args..., [] {
    cq.Notify((void*)LONG_RUNNING_TASK_COMPLETE)
  });
```

And I can handle everything in **one thread**, so I don't need mutexes or locks.

**Comment by mike07026** [comment]
same requirement in #7305

**Comment by ctiller** [comment]
I wholeheartedly agree we should have such an API.

The thing I don't know: the CQ keeps track of the number of items it will
eventually complete, to give the nice shutdown semantics it has (and
fulfill the guarantee that you put a tag in you get a tag out).

To export that we'd probably want a PrepareNotify()/FinishNotify() pair,
but I've always considered that too tricky to explain. Without it though
we've undone some important semantics.

**Comment by ctiller** [comment]
Any thoughts on the proposed semantics?

**Comment by SurferJeffAtGoogle** [comment]
I don't know if we can save the user from shooting off their own foot, and I see the same potential race conditions around PrepareNotify() as would exist for FinishNotify().  So actually, PrepareNotify() only seems to add complexity, not reduce it.

**Comment by arthur-tacca** [comment]
I notice that a [`grpc::Alarm`](https://grpc.io/grpc/cpp/classgrpc_1_1_alarm.html) with timeout of `gpr_timespec{0, 0, GPR_TIMESPAN}` would effectively fulfill this role, albeit in a terribly hacky way. Presumably the constructor and destructor correspond to the hypothetical `PrepareNotify` and `FinishNotify` methods mentioned in this thread? 

Does anyone have any comments on using `Alarm` until an official `post()` API becomes available? Except perhaps for abject horror :-) I guess it does not hold the ordered delivery guarantee I would expect from a dedicated API (assuming one thread reading from the CQ). And could there be performance problems from (ab)using the `Alarm` API like this?

**Comment by arthur-tacca** [comment]
This is still of interest, at least to me and probably many others. Hopefully it is also on some Googler's radar.

**Comment by jacobsa** [comment]
I also would still like this...

**Comment by arthur-tacca** [comment]
Just a quick note that there is a surprisingly simple workaround for this issue.

Rather than: having a thread for pumping and handling gRPC completion queue, and somehow inserting your own custom events into the completion queue..

You could instead have two threads for processing:

* completion queue thread: just pumps messages off of the completion queue and immediately puts them onto a thread-safe queue.
* message handling queue: handle the messages coming off of the thread queue

That way you can put messages onto the thread queue because you have complete control over it. It is a pity to have to do this though - after all, the gRPC completion queue already is a thread safe queue internally!
