### ISSUE TITLE
Error after enabling trace logs and redirecting logs to log4net (completion_queue.c:333)

### ISSUE THREAD

**Issue by y-skindersky** [grpc/grpc#8452]
```
Environment.SetEnvironmentVariable("GRPC_TRACE", "all");
Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");

SetLogger(new MyLogger());
```

`2016-10-21 11:17:25,580,INFO,grpc 1 (cq 1),<log4net.Error>Exception during StringFormat: Input string was not in a correct format. <format>0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\lib\surface\completion_queue.c:333: grpc_completion_queue_next(cc=000000F49F361D90, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0000000000000000)</format><args>{}</args></log4net.Error>`

**Comment by apolcyn** [comment]
@y-skindersky so this error is coming from the `new MyLogger()`, passed to `SetLogger`? And MyLogger is a `log4net` logger?

**Comment by apolcyn** [comment]
@y-skindersky just missed that this was closed, assuming it's fixed
