### ISSUE TITLE
Python - string representation of objects should be `unicode`s, not `str`s

### ISSUE THREAD

**Issue by jerjou** [grpc/grpc#8459]
I have a script that makes grpc calls, that return text that's potentially in a different language. In the code, I [print out the list of objects](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/41277848de6498aa52fc50a7d6cee66dec55fd49/speech/grpc/transcribe_streaming.py#L172) who have the attribute `transcript`, that is the `unicode` with the text. However, if the text is in fact a double-byte character, it's printed out [as escape sequences](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/487). Printing out the `transcript` attribute directly correctly prints out the desired character.

I suspect this is because the `__str__` of the grpc-generated response objects are `str` objects instead of `unicode` objects. Given that in python3, all string objects default to `unicode` objects, it might be prudent for the string representations of grpc-generated objects also be `unicode` objects.

**Comment by soltanmm-google** [comment]
gRPC just passes around bytes and the proto-generated code just allows for proto messages. I think you meant to file against [google/protobuf](https://github.com/google/protobuf)?

**Comment by jerjou** [comment]
Oh - [yup](https://github.com/google/protobuf/issues/2277). Thanks!
