### ISSUE TITLE
Enhancement - swift3 server side sample code via swift package manager

### ISSUE THREAD

**Issue by johndpope** [grpc/grpc#8470]
It's now possible to package objective-c and c++ into swift package manager.
https://medium.com/@petrpavlik/contributing-to-the-server-side-swift-world-936155e4c812#.csaknkiur

While it's possible to spit out a simple swift implementation of messages suitable for libraries on ios using Apple's handy work
https://github.com/apple/swift-protobuf

generating the corresponding ProtoService is something else
https://github.com/apple/swift-protobuf/issues/118

In other words - given the sample swift code in this repo- 
https://github.com/grpc/grpc/tree/master/src/objective-c/examples/SwiftSample

can we package this up into SPM (decoupling ios stuff) to provide a hello world for server side swift? 

To explore this further (for anyone wanting to attempt this) - I've patched a Dockerfile for swift3 local development https://gist.github.com/johndpope/01a74ffb93921df48e334097117be1b3

This was to interface to https://github.com/johndpope/DockerParseyMcParsefaceAPI
that runs parsey mcparseface using gprc + protobuffers.

I will attempt to port this over and update this ticket if I make any progress.

**Comment by jcanizales** [comment]
CC @muxi @timburks

**Comment by johndpope** [comment]
I found this https://github.com/Huawei-PTLab/SwiftGRPC
https://github.com/Huawei-PTLab/CGRPC
but couldn't get grpc patched. https://github.com/Huawei-PTLab/CGRPC/issues/2

**Comment by johndpope** [comment]
Yielding to google dedicated swift grpc repo. 🙌 
toodles https://github.com/grpc/grpc-swift
