### ISSUE TITLE
Enable missing python interop tests

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8478]
the "advanced" tests:
custom_metadata, unimplemented_method, status_code_and_message

**Comment by jtattermusch** [comment]
CC @kpayson64

**Comment by kpayson64** [comment]
status_code_and_message is implemented, but not active right now.

I'm not sure about the rest.

**Comment by ncteisen** [comment]
They are actually all done! Just waiting on #8449 to get approved and merged in.

**Comment by ncteisen** [comment]
Closed by #8449
