### ISSUE TITLE
Add test coverage for grpc._server._Context.time_remaining

### ISSUE THREAD

**Issue by isaacdd** [grpc/grpc#8483]
```
class Service(service_pb2.ServiceServicer):
    def Method(self, request, context):
        log.info('%s', context.time_remaining())
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grpc/_server.py", line 364, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_server_adaptations.py", line 100, in adaptation
    return unary_request_inline(request, _FaceServicerContext(servicer_context))
  File "/usr/local/lib/python2.7/dist-packages/prozess/alerting_metric_query/core.py", line 40, in Evaluate
    log.info('%s', context.time_remaining())
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_server_adaptations.py", line 69, in time_remaining
    return self._servicer_context.time_remaining()
  File "/usr/local/lib/python2.7/dist-packages/grpc/_server.py", line 229, in time_remaining
    return max(self._rpc_event.request_call_details.deadline - time.time(), 0)
TypeError: unsupported operand type(s) for -: 'grpc._cython.cygrpc.Timespec' and 'float'
```

```
protobuf==3.0.2
grpcio==1.0.0
```

Workaround:

```
def time_remaining(context):
    deadline = context._servicer_context._rpc_event.request_call_details.deadline
    return (deadline.seconds + deadline.nanoseconds / 10**9) - time.time()
```

Update:
In 1.0.1, context object was refactored. This will work:

```
def time_remaining(context):
    deadline = context._rpc_event.request_call_details.deadline
    return (deadline.seconds + deadline.nanoseconds / 10**9) - time.time()
```

**Comment by gfernandessc** [comment]
Was this closed because there was a fix? time_remaining() is still part of the API and this is still broken on 1.0.4.

**Comment by jayantkolhe** [comment]
what error do you get if you use time_remaining()?

**Comment by gfernandessc** [comment]
The same one:

```
ERROR:root:Exception calling application: unsupported operand type(s) for -: 'grpc._cython.cygrpc.Timespec' and 'float'
Traceback (most recent call last):
  File "/Users/guilherme.fernandesraphanelli/miniconda2/lib/python2.7/site-packages/grpc/_server.py", line 364, in _call_behavior
    return behavior(argument, context), True
  File "greeter_server.py", line 45, in SayHello
    print "time {}".format(context.time_remaining())
  File "/Users/guilherme.fernandesraphanelli/miniconda2/lib/python2.7/site-packages/grpc/_server.py", line 229, in time_remaining
    return max(self._rpc_event.request_call_details.deadline - time.time(), 0)
TypeError: unsupported operand type(s) for -: 'grpc._cython.cygrpc.Timespec' and 'float'
```

(This is reproduced by accessing context.time_remaining() on the helloworld example.)

**Comment by nathanielmanistaatgoogle** [comment]
I'm having a hard time reading this issue's history. @ctiller: is there a record of why it got the `to close` label? @hsaliak: is there a record of why it was closed?

I am working on a fix...

**Comment by nathanielmanistaatgoogle** [comment]
([... and this bug likely wouldn't have happened if our coverage story were better...](https://github.com/grpc/grpc/issues/6894))

**Comment by hsaliak** [comment]
Yes - this was marked as `` to close `` during our semi-regular bug scrub where we triage all issues. However, I think this particular issue was a false positive, especially due to the existence of the workaround. 
We expected a few false positives when we did the scrub and unfortunately this is an important issue that we tagged wrong.

As an aside: This is a clear indicator for us to focus on improving the process - for example, we should stage the issues marked for closure ensure that they get the appropriate labels and close them pending a closer look, with a smaller group.

**Comment by nathanielmanistaatgoogle** [comment]
Following the integration of [pull request 9420](https://github.com/grpc/grpc/pull/9420) all that's left to do here is replace the smoke test with a real test.

**Comment by jtattermusch** [comment]
No action here for 9+ months. Remove P1 label?

**Comment by nathanielmanistaatgoogle** [comment]
Fair enough. It felt important at the time...
