### ISSUE TITLE
fail: naddrs may be used uninitialized in this function

### ISSUE THREAD

**Issue by yizhiren** [grpc/grpc#8488]
hi,
i met a issue when compile grpc as doc said:

```
 $ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init
 $ make
 $ [sudo] make install
```

and fail at command make:

```
[C]       Compiling src/core/ext/transport/chttp2/server/insecure/server_chttp2.c
cc1: warnings being treated as errors
src/core/ext/transport/chttp2/server/insecure/server_chttp2.c: In function ‘grpc_server_add_insecure_http2_port’:
src/core/ext/transport/chttp2/server/insecure/server_chttp2.c:148: error: ‘naddrs’ may be used uninitialized in this function
make: *** [/data/code/rpc/grpc/objs/opt/src/core/ext/transport/chttp2/server/insecure/server_chttp2.o] Error 1
```

 then i fixed it by edit Makefile , I change 

```
CPPFLAGS_opt = -O2
```

to

```
CPPFLAGS_opt = -O0
```

**do you think this fix should be merged to master?**

my env is centos6.7, and i have tried in my centos6.7 machine and docker of centos6.7 based on centos7 machine. and below info is from docker of centos6.7  

```
[root@6fc2d0f80ac3 grpc]# g++ -v
Using built-in specs.
Target: i686-redhat-linux
Configured with: ............
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
[root@6fc2d0f80ac3 grpc]#
[root@6fc2d0f80ac3 grpc]# uname -a
Linux 6fc2d0f80ac3 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 i686 i686 i386 GNU/Linux
[root@6fc2d0f80ac3 grpc]# cat /etc/redhat-release
CentOS release 6.7 (Final)
[root@6fc2d0f80ac3 grpc]#

```

besides, i execute the tools/openssl/use_openssl.sh, since default boringssl raise some failue.

**Comment by hisammy** [comment]
help!
I also encountered this problem

**Comment by mikewang2016** [comment]
The same problem for me. my env is CentOS 6.6.

Suggest fix this issue.

**Comment by yizhiren** [comment]
@hisammy   @mikewang2016  try to workaround , change  "CPPFLAGS_opt = -O2" to "CPPFLAGS_opt = -O0" in Makefile.

since no official member reply this issue, i guess , they don't consider fix it.

**Comment by haorenfsa** [comment]
seems all CentOS issue, mine env is CentOS6.7 x64.

**Comment by kpayson64** [comment]
naddrs is no longer in this function.
