### ISSUE TITLE
Python protoc plugin test does not perform dynamic port allocation

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#849]
The Python protoc plugin test under `test/compiler/python_plugin_test.py` should dynamically allocate its ports per unittest instead of using the static value 40987.

**Comment by nathanielmanistaatgoogle** [comment]
#855 addresses this.

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed in 732cf09a938b52f1803b4.
