### ISSUE TITLE
Feature request: ability to specify output package name

### ISSUE THREAD

**Issue by geigerj** [grpc/grpc#8492]
Context: googleapis/artman#97. This only impacts us in Python currently.

### What
We'd like the ability to specify the output package name in calls to `protoc` (or the equivalent language wrapper -- `grpc.tools.protoc` in the Python case).

### Why
Sometimes the default output package is not acceptable. (In our case, [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python) often needs to declare a non-namespace package of the same name as the generated proto package.) We're working around by ~~editing the generated output directly (described [here](https://github.com/googleapis/artman/issues/97)), but it's ugly needing to edit generated files.~~ EDIT: moving the source files temporarily. This is OK but breaks the convention that the proto package corresponds to the proto directory structure.

Note: I wasn't sure whether this should be placed here or in https://github.com/google/protobuf. I guess it depends on whether this is better addressed for Python specifically in `grpcio-tools`, or in `protoc` itself.

cc: @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
What different kinds of values are you passing for the `--python_out` command-line option? If you were able to specify different values for `--python_out` and `--python_grpc_out`, would that address this need?

**Comment by geigerj** [comment]
> What different kinds of values are you passing for the --python_out command-line option? 

`--python_out` is currently the top-level directory containing the output, e.g., `python -m grpc.tools.protoc -I. --python_out=output --grpc_python_out=output google/cloud/grpc/vision/v1/geometry.proto`.

> If you were able to specify different values for --python_out and --python_grpc_out, would that address this need?

No, we need to be able to customize the Python package name. For example, if `library.proto` has package name `google.example.library.v1`, we'd like to be able to produce the package name `foo.bar.library_pb2` independently of the proto package name. Currently that's doesn't seem to be possible.

**Comment by nathanielmanistaatgoogle** [comment]
Isn't the `package` line in a `.proto` file completely ignored by `protoc` for Python code generation? Isn't the Python package of generated code determined by directory structure of the input you pass to `protoc`?

**Comment by geigerj** [comment]
Ah, I think you're right -- our workaround actually involves moving the protos in googleapis/googleapis around and then putting them back. It would still be nice to be able to get the right output without needing to do that, but that's not as bad as I had remembered.

**Comment by nathanielmanistaatgoogle** [comment]
In that case I'm nearly certain that [what you've got is a feature request for `protobuf`](https://github.com/google/protobuf/issues/new). Closing this issue for now; reopen when it becomes actionable on our part?
