### ISSUE TITLE
Optimize running time for run_test_matrix.py suites.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8493]
There's two params:  `--jobs X`  and _INNER_JOBS.
I strongly suspect that these can be fine-tuned to reduce total running time of our test suites (but not overloading the worker)

(e.g. increasing _INNER_JOBS seems to decrease the overall time C and C++ have by far the greatest number of tests, so for good portion of time, the worker only runs C and C++ tests among which many are long-running and could benefit from higher parallelism).

This is not urgent, but decreasing the total time needed for all tests to finish improves developer experience a lot (and indirectly also leads to better health status of the project) and it's a key metric we are trying to improve.

**Comment by jtattermusch** [comment]
Btw, these are current running times:
https://grpc-testing.appspot.com/job/gRPC_master_linux/241/testReport/(root)/aggregate_tests/

**Comment by matt-kwong** [comment]
A lot of jobs have been optimized and are now running much faster.
