### ISSUE TITLE
Generate partial classes for C#

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#8506]
We've run into scenarios where it would be really helpful to be able to inject new code into generated classes for C# - our particular scenario is creating a new client B with the same call invoker as client A, but there could be other scenarios.

For the moment we're going to hand-patch the generated source, but if we had partial classes, we wouldn't need to do this. Both the outer class and the nested classes would need to be partial.

**Comment by apolcyn** [comment]
addressed by https://github.com/grpc/grpc/pull/8619. This will be in the next release, forgot to close
