### ISSUE TITLE
PHP code style

### ISSUE THREAD

**Issue by Rican7** [grpc/grpc#851]
I noticed a quite unique style in the PHP language wrapper.

For ease of external contribution, testing (formatting), and consistency with other projects, I recommend switching the PHP wrapper to comply to the [PSR-2 style guide](http://www.php-fig.org/psr/psr-2/).

You can then (initially or eventually) implement [a format checker](https://github.com/squizlabs/PHP_CodeSniffer) in the tests/CI to make sure that contributions comply with the standard.

I'd be happy to make a pull-request with the changes, if the idea is accepted.

**Comment by murgatroid99** [comment]
I would be happy to take a pull request with those changes, but the PHP code is a little out of date, and I'd prefer to wait until we get the PHP tests running and passing on travis-ci before taking external changes to the code.

**Comment by Rican7** [comment]
Yea, that's fair. If the tests are something you're taking care of, feel free to ping me here when you'd like a code-style PR. :+1:
