### ISSUE TITLE
Stubbing out synchronization functions when not using threads

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#8530]
When working with code that only runs gRPC with one thread, it would be a nice optimization to take the minimum possible action at all synchronization points. To that end, we would `#define` most of the sync API to either nothing or simple arithmetic and pointer operations.

@nicolasnoble has suggested the following solution: Leave gpr (functionally) unchanged, add grpc sync functions that are directly `#define`d to the corresponding gpr sync functions (e.g. `#define grpc_mu_init(mu) gpr_mu_init((mu))`).

@ctiller (or anyone else) What do you think of this solution?

**Comment by ctiller** [comment]
What do we gain besides complexity?

**Comment by murgatroid99** [comment]
If you consider GPR as an independent library, then it doesn't really make sense to be able to build it in such a way that it exports do-nothing synchronization functions. It makes more sense to build gRPC so that it simply doesn't use those synchronization functions.
