### ISSUE TITLE
Handle more rpc request in async server.

### ISSUE THREAD

**Issue by pengweichu** [grpc/grpc#8533]
Hi all, I would like to create a asyn GRPC server, I'm leaning example **greeter_async_server.cc** today, but I have a question:

As example code, in the `Proceed`function there called   `service_->RequestSayHello` to expect receive "Hello" request since in example the service only define one request.

But if there has another requests defined such as "SayHi", "SayX", "SaySomething", then we have to new more `CallData`in `HandleRpcs`function in order to call
  `service_->RequestSayHi`, `service_->RequestSayX`,  `service_->RequestSaySomthing` to expect receive these request from clients, right ?

Thanks in advance.

**Comment by legendlin** [comment]
I have the same question with you. I think the async server demo is so stupid for Application.

**Comment by pengweichu** [comment]
@legendlin I have make a wrapper to do that: https://github.com/pengweichu/async_grpc_wrapper

**Comment by legendlin** [comment]
@pengweichu thank you.
I have visited your homepage yesterday and your wrapper worked.
But I still think grpc should supports async way more naturally in the future.

**Comment by pengweichu** [comment]
@legendlin yes, totally agree.

**Comment by dutor** [comment]
The whole implementation of gRPC is bullshit. The authors are quite alien from the way of human thinking.

**Comment by mehrdada** [comment]
We are constantly thinking about improving gRPC usability and will take this feedback into account. I am closing this issue as this falls into the general usability/API experience work that we do as we improve gRPC. Thanks!
