### ISSUE TITLE
using PHP with grpc and protocbuf

### ISSUE THREAD

**Issue by nevernet** [grpc/grpc#8547]
there is some problems when i follow the current documents from official site, so i am trying to write down my steps, hope it will help you who want to use PHP with grpc.

environment

``` bash
mac OS sierra 10.12
PHP 5.6
```

install Protocbuf

``` bash
download 3.0.2(latest version of 3.0.x, and must be version v3.0.x, DO NOT use version 3.1.x now)
https://github.com/google/protobuf/releases
(protoc-3.0.2-osx-x86_64.zip)

```

unzip `protoc-3.0.2-osx-x86_64.zip` to folder `/Users/daniel/github/protoc/3.0.2/` and create link in `/usr/local/bin/`

``` bash
ln -s /Users/daniel/github/protoc/3.0.2/bin/protoc /usr/local/bin/protoc
protoc --version
//ouputs
libprotoc 3.0.0
```

install grpc php extension

``` bash
git clone -b v1.0.0 --depth=1 git@github.com:grpc/grpc.git
cd grpc
git checkout -b v1.0.0
cd src/php/ext
phpize
./configure
make && make install
```

install protocbuf-php plugin

```
git clone https://github.com/stanley-cheung/Protobuf-PHP --depth=1
cd Protobuf-PHP
rake pear:package version=1.0
[sudo] pear install Protobuf-1.0.tgz
```

pear installation will install `protoc-gen-php` command into php bin folder
use `which php` to find out the real folder.
than you can use `protoc-gen-php` anywhere.

back to folder grpc, and

```
cd examples/php
protoc-gen-php -i . -o . helloword.proto
```

it will generate helloworld.php with `request`, `response` and `client` classes

the full documentation  is here: http://www.grpc.io/docs/quickstart/php.html

the origin issue is : #8502 

enjoy it

**Comment by zorrocaesar** [comment]
The documentation is indeed confusing.
But actually, you don't need to use the protocbuf-php plugin anymore if you use the protoc compiler v3.1.0. This new version already includes a code generator for PHP. You just need to specify --php_out=OUT_DIR as a flag.

The generated code is much cleaner BUT is also incomplete, because it's missing the service class. I have already opened an issue for this [here](https://github.com/google/protobuf/issues/2334).

**Comment by nevernet** [comment]
@zorrocaesar  i will try v3.1.0 with integrated php plugin. 
thanks, usually we will not use PHP as service, the client is enough.

**Comment by zorrocaesar** [comment]
You still need the client stub in order to use the service. That is what I am referring to.

**Comment by nevernet** [comment]
@zorrocaesar Yes, there is no server and client stub :)
