### ISSUE TITLE
grpc write no data to client

### ISSUE THREAD

**Issue by poponion** [grpc/grpc#8550]
Hi 
   I have met a problem that server can not write data to client, I have dump packets between client/server
I tried to debug this problem, I guess this may be due to flow control (stream->outgoing_window<=0), but I am not sure about that, does anyone have any idea about this?
This situation happened occasionally when my system was quite stressed, and some inter server requests timeout.   Once the situation happened, it would not disappear, no matter the system is stressed or not there

![lalpawnfen0hmi7mks0dqg_938_146](https://cloud.githubusercontent.com/assets/756591/19799109/718acc26-9d27-11e6-9562-1b177a2cbb68.png)
server not reply data frame
I am using async mode, and timeout is 600ms

![lalpawnfen0idunml80e4q_1249_151](https://cloud.githubusercontent.com/assets/756591/19799209/fe04a744-9d27-11e6-9d6b-cb1e349ef2e9.png)
server reply data frame

**Comment by soltanmm-google** [comment]
Which language are you using?

**Comment by poponion** [comment]
c++

**Comment by vjpai** [comment]
I haven't seen any followup in a year, but in that time a lot has changed wrt flow control/request matching/etc that might have triggered the issue.
