### ISSUE TITLE
Ruby benchmark scenarios are failing often

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8551]
After enabling report.xml in benchmarks, this is now much easier to spot:

https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_master/7581/#showFailuresLink

In this instance, these scenarios have failed:
benchmarks.qps_json_driver.ruby_to_cpp_protobuf_sync_streaming_ping_pong
benchmarks.qps_json_driver.ruby_protobuf_sync_streaming_qps_unconstrained
benchmarks.qps_json_driver.ruby_to_cpp_protobuf_sync_unary_ping_pong

**Comment by jtattermusch** [comment]
Same scenarios failing in the previous build as well.
https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_master/7580/

**Comment by apolcyn** [comment]
FTR, it looks like there is a race happening between GC shutting down the server and it being explicitly shut down by the app (from a separate thread from the main thread). One fix is to protect the internal destroy server function from the race. But I'm still not sure why GC is running on the ruby server while it's still being shut down (ref to it is still alive) - more investigation needed to find that out.

**Comment by apolcyn** [comment]
To update, I guess that actually the child thread (that's shutting down the server) is just not waited for and cleaned up once the main thread completes. This should probably be ok though - protecting the destroy function should fix.

**Comment by apolcyn** [comment]
Looking at recent failures reports and logs from `performance_master` and `performance_experiment` jobs, it looks like these are now passing.

(looked at jobs in https://grpc-testing.appspot.com/job/gRPC_performance_master/ and https://grpc-testing.appspot.com/job/gRPC_performance_experiment/)

I think this has been fixed, closing for now.
