### ISSUE TITLE
Compiling from clean repo fails

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#8556]
The docs [here](https://github.com/grpc/grpc/blob/master/INSTALL.md#build-from-source)  say that `make` should work, but compilation fails:

```
[AR]      Creating /home/notcarl/git/grpc/libs/opt/libboringssl.a
src/compiler/csharp_generator.cc:46:43: error: ‘google::protobuf::compiler::csharp::GetReflectionClassName’ has not been declared
 using google::protobuf::compiler::csharp::GetReflectionClassName;
                                           ^
src/compiler/csharp_generator.cc: In function ‘void grpc_csharp_generator::{anonymous}::GenerateServiceDescriptorProperty(grpc::protobuf::io::Printer*, const ServiceDescriptor*)’:
src/compiler/csharp_generator.cc:305:64: error: ‘GetReflectionClassName’ was not declared in this scope
              "umbrella", GetReflectionClassName(service->file()), "index",
                                                                ^
[AR]      Creating /home/notcarl/git/grpc/libs/opt/libgrpc_unsecure.a
[CXX]     Compiling src/cpp/client/secure_credentials.cc
[CXX]     Compiling src/cpp/common/auth_property_iterator.cc
make: *** [/home/notcarl/git/grpc/objs/opt/src/compiler/csharp_generator.o] Error 1
```

**Comment by nicolasnoble** [comment]
Can you check if you have protobuf installed on your system ? Compare version in repo with version installed ?

**Comment by murgatroid99** [comment]
If you have protobuf installed, you should be able to override it and force make to use the protobuf in the submodule with `make HAS_SYSTEM_PROTOBUF=false`

**Comment by carl-mastrangelo** [comment]
@murgatroid99 Yep that works.  Is there any reason the repo's Protobuf shouldn't be preferred over the system?  It would make for a more hermetic build.

**Comment by arhuaco** [comment]
Hi there. There should be a note about this in the INSTALL.md file. Perhaps in the ##Protoc section. ATM the most recent release of grpc doesn't like the most recent release of protobuf.

**Comment by nicolasnoble** [comment]
The reason the system's protobuf is preferred is because there's no strong semantic versioning for protobuf C++. So if we compile gRPC with protobuf version X internally, but the end user will use version Y externally, this will fail.
