### ISSUE TITLE
Trim Ruby dependencies

### ISSUE THREAD

**Issue by mperham** [grpc/grpc#857]
Yikes, this is a long list of dependencies: https://github.com/grpc/grpc/blob/master/src/ruby/grpc.gemspec#L23

Can that list be trimmed so it's not pulling in dozens of gems?

**Comment by tbetbetbe** [comment]
Thanks for the reminder !
I missed removing some of these dependencies in a recent switch to depending on googleauth in #783.  This should be fixed shortly.
