### ISSUE TITLE
'node-pre-gyp install --fallback-to-build' fails when running 'npm install --save google-cloud'

### ISSUE THREAD

**Issue by Andrewjeska** [grpc/grpc#8570]
npm WARN enoent ENOENT: no such file or directory, open '/Users/michaelanderjaska/Documents/FelineFelicity/node_modules/@google-cloud/vision/package.json'

npm ERR! Darwin 15.4.0
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.14.1 install: `node-pre-gyp install --fallback-to-build`

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.14.1 install script 'node-pre-gyp install --fallback-to-build'.

**Comment by murgatroid99** [comment]
Do you have any other logs? This just says that the installation of the native extension failed in some way.

**Comment by murgatroid99** [comment]
Also, version 0.14.1 is pretty old, and was considered beta quality. I would strongly recommend upgrading to 1.x.

**Comment by Andrewjeska** [comment]
Apparently I was supposed to use v6.2.0, while I was using v7.0.0. Switching to 6.2.0 fixed it.

**Comment by murgatroid99** [comment]
That makes sense. Version 0.14.1 is from long before Node 7 was released, and some functions we used have since been deprecated.

I'm surprised you get that version of grpc. When I run `npm install google-cloud`, I get grpc@1.0.0.

**Comment by Andrewjeska** [comment]
Yea I don't know why I'm getting the old grpc. I tried updating npm but that didn't do very much :/.

**Comment by Andrewjeska** [comment]
I tried to replicate the error again. Still had a similar error. When I try to run my app I get this:

module.js:474
    throw err;
    ^

Error: Cannot find module '/Users/michaelanderjaska/Documents/FelineFelicity/node_modules/@google-cloud/vision/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michaelanderjaska/Documents/FelineFelicity/node_modules/@google-cloud/vision/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/michaelanderjaska/Documents/FelineFelicity/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by murgatroid99** [comment]
And that's under node 6.2? What version of `google-cloud` do you have? Do you still have version `0.14.1` of grpc? Did you get any errors or warnings during the install process?

**Comment by Andrewjeska** [comment]
Sorry I wasn't clear. It works fine when I use 6.2., this error is happening for 7 (but I get the same thing if it's above 6.2).  I don't know the version I'm just running `npm --save install google-cloud`. 

During install, it gives an error, much like the one in the first comment, then it prints a bunch of lines like these:

./Release/.deps/Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_linux.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 30092039,
  size: 205,
  blocks: 8,
  atime: 2016-10-31T17:34:55.000Z,
  mtime: 2016-10-31T17:34:55.000Z,
  ctime: 2016-10-31T17:34:55.000Z,
  birthtime: 2016-10-31T17:34:54.000Z }
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_posix.o

Sorry I can't more technical answers I'm just using the vision api for a side-project.

**Comment by murgatroid99** [comment]
To get the version, just do `npm ls google-cloud`. Without the logs, I can't tell you exactly what's going wrong, but I think you're simply getting a version of gRPC that's too old for the version of Node you're using.

**Comment by Andrewjeska** [comment]
Looks like I'm on 0.40.0

**Comment by murgatroid99** [comment]
OK, for some reason you're a few versions behind. Can you see what happens if you do `npm install google-cloud@0.43`?

**Comment by Andrewjeska** [comment]
So I get a lot of output right before this:

project@1.0.0 /Users/michaelanderjaska/Documents/project
└─┬ google-cloud@0.43.0  invalid
  ├── @google-cloud/bigquery@0.4.0
  ├── @google-cloud/bigtable@0.5.0
...and so on

**Comment by murgatroid99** [comment]
That's just the output telling you that it installed `google-cloud@0.43.0`, and all of its dependencies. It's just saying "invalid" because earlier you saved the dependency as version 0.40.0. But once you do that, does it work?

**Comment by Andrewjeska** [comment]
So when I downloaded it, it had an error like this:

> grpc@1.0.0 install /Users/michaelanderjaska/Documents/FelineFelicity/node_modules/google-cloud/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.0/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.0 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

Now when I run my app, it doesn't seem to find the module:

rror: Cannot find module '@google-cloud/vision'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michaelanderjaska/Documents/FelineFelicity/src/image_analysis/cat_attr.js:4:1)
    at Module._compile (module.js:573:32)
    at loader (/Users/michaelanderjaska/Documents/FelineFelicity/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/michaelanderjaska/Documents/FelineFelicity/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

Am I not supposed to use the @ symbol? Thanks for spending the time to help, btw.

**Comment by Andrewjeska** [comment]
After doing 'npm install --save @google-cloud/vision', it works. All I needed was the vision library anyways. grpc is the most recent one.

**Comment by wahengchang** [comment]
do u guys get any solution ?
