### ISSUE TITLE
Protobuf 3.1.0 required

### ISSUE THREAD

**Issue by oriolorra** [grpc/grpc#8574]
Hi,

I have installed Protobuf 3.1.0 on Ubuntu 14.04 and when I write _'protoc --version'_, I get this version. 
Then I compile Helloworld example, and when I execute it as _'./greeter_server'_. I get this error:

`[libprotobuf FATAL google/protobuf/stubs/common.cc:67] This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "external/com_github_google_protobuf/src/google/protobuf/any.pb.cc".)`

Could someone give me a tip, the solution or tell me why?

Thanks in advance,

**Comment by pvallem** [comment]
I am also facing the same issue.

This is due to file: https://github.com/grpc/grpc/blob/v1.0.1/include/grpc%2B%2B/ext/reflection.pb.h
This file is pre generated using protoc 3.0.0 and since i have installed protoc3.1.0, i could not install grpc

**Comment by nicolasnoble** [comment]
Protobuf doesn't follow semantic versioning for C++, so the correlation between headers and libraries has to be fully identical. We can't really do much here.
