### ISSUE TITLE
grpc_cpp_plugin rpath missing

### ISSUE THREAD

**Issue by gazickil** [grpc/grpc#8576]
Hi, i try to compile C++ grpc project on linux machine. I cloned main repo and load subproject (basically as written in manual). I use not standard LD_LIBRARY_PATH and compiler path. All libs and paths I have in my specific project path. I end up having following problem during compilation:

`grpc/grpc/bins/opt/grpc_cpp_plugin: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by grpc/grpc/bins/opt/grpc_cpp_plugin)`

Basically it means that grpc_cpp_plugin can not find proper libstdc++ which were used during it compilation. Here is ldd output:

`./grpc_cpp_plugin: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by ./grpc_cpp_plugin)`
`        linux-vdso.so.1 =>  (0x00007fff5ce70000)`
`        libdl.so.2 => /lib64/libdl.so.2 (0x0000003858a00000)`
`        librt.so.1 => /lib64/librt.so.1 (0x0000003859600000)`
`        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003859200000)`
`        libz.so.1 => /lib64/libz.so.1 (0x0000003859e00000)`
`        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00000039d1600000)`
`        libm.so.6 => /lib64/libm.so.6 (0x0000003859a00000)`
`        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00000039d1200000)`
`        libc.so.6 => /lib64/libc.so.6 (0x0000003858e00000)`
`        /lib64/ld-linux-x86-64.so.2 (0x0000003858600000)`

The thing is that libstdc++.so.6 should point to different location. I suspect it is because this execautable do not have rpath tag (which you can verify using chrpath).

However when I do ldd on protoc executable I get this:
`        linux-vdso.so.1 =>  (0x00007fff98993000)`
`        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003859200000)`
`        libstdc++.so.6 => /proj/copyleft/linux/gcc-4.9.2/lib/../lib64/libstdc++.so.6 (0x00007fd4df85d000)`
`        libz.so.1 => /lib64/libz.so.1 (0x0000003859e00000)`
`        libm.so.6 => /lib64/libm.so.6 (0x0000003859a00000)`
`        libgcc_s.so.1 => /proj/copyleft/linux/gcc-4.9.2/lib/../lib64/libgcc_s.so.1 (0x00007fd4df646000)`
`        libc.so.6 => /lib64/libc.so.6 (0x0000003858e00000)`
`        /lib64/ld-linux-x86-64.so.2 (0x0000003858600000)`

I verified that linker added rpath tag and that libstdc++/so.c points to proper lib.

My question is why main Makefile do not add rpath and how I add it? Maybe I'm missing sth?

**Comment by sreecha** [comment]
@nicolasnoble : Not sure if we should consider this relevant (the issue is ~2 yrs old). Should we close it ?
