### ISSUE TITLE
gflags dependency missing 

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#8582]
Trying to build performance tests, it looks like a missing dependency on gflags causes it to fail.
```
$ tools/run_tests/performance/build_performance.sh


test/cpp/util/cli_credentials.cc:36:27: fatal error: gflags/gflags.h: No such file or directory
compilation terminated.
Makefile:2215: recipe for target '/home/jenkins/grpc/objs/opt/test/cpp/util/cli_credentials.o' failed
make: *** [/home/jenkins/grpc/objs/opt/test/cpp/util/cli_credentials.o] Error 1
make: *** Waiting for unfinished jobs....
test/cpp/util/grpc_tool.cc:43:27: fatal error: gflags/gflags.h: No such file or directory
compilation terminated.
Makefile:2215: recipe for target '/home/jenkins/grpc/objs/opt/test/cpp/util/grpc_tool.o' failed
make: *** [/home/jenkins/grpc/objs/opt/test/cpp/util/grpc_tool.o] Error 1
```

This is easy to miss, because if gflags is installed on the system the error doesn't show up.

**Comment by ncteisen** [comment]
Could you clarify the problem here? Would this be fixed wth [sudo] apt-get install libgflags-dev

**Comment by carl-mastrangelo** [comment]
Either it needs to be pulled into the third_party directory, or explicitly listed on the Docs describing how to run the test.

**Comment by ncteisen** [comment]
https://github.com/grpc/grpc/blob/master/CONTRIBUTING.md has all of the info on how to install the requirements for the tests. Would adding a link to that page from the test's page be enough to resolve this issue?

**Comment by soltanmm-google** [comment]
> Either it needs to be pulled into the third_party directory, or explicitly listed on the Docs describing how to run the test.

It's *in* the third party directory. @ncteisen I'm still confused from last time why it is that we need to have the user running tests install a requirement for tests when we have it already included as a submodule and all it takes is a `git submodule update --init` and a change to a few include flags.

**Comment by carl-mastrangelo** [comment]
@ncteisen The first README people see (including me) is: https://github.com/grpc/grpc/blob/master/README.md 

Look at the section named "Installation & Testing".  Neither of the links there points out that the gflags lib needs to be present.  

@soltanmm-google: I encourage you to create a blank VM and actually try to run the tests rather than using your own machine, or a prebuilt image.  It is not straight forward, thus this bug report.

**Comment by apolcyn** [comment]
I'm pretty sure the main thing btw is that the performance tests expect for `tools/gce/linux_performance_worker_init.sh` to have been ran.

**Comment by ncteisen** [comment]
That would also accomplish this, bc line 88 is
`sudo apt-get install -y libgflags-dev libgtest-dev libc++-dev clang`

I agree with Carl that the initial documentation is not totally straight forward. I remember this gave me a headache when I was first getting everything installed a few months ago.

I will put in a PR with some documentation clarifications

**Comment by ncteisen** [comment]
Do you guys think that my PR closes this problem? I figure it makes it way harder to miss installing the gflags lib

**Comment by carl-mastrangelo** [comment]
@ncteisen Only weekly so.  It is not uncommon to clone a project, build it, run all the tests and then install it.  Contribution doesn't really play a role in that flow, but the gflags library is still needed.

**Comment by ncteisen** [comment]
Ok, I moved the section for installing the test deps to INSTALL.md
