### ISSUE TITLE
Client should send RST_STREAM when it receives nonzero grpc-status

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#8585]
When the gRPC server sends a non-zero grpc-status to actively ends a call without sending a following RST_STREAM, the gRPC client should 1) closes its write stream and 2) sends out RST_STREAM. Current behavior of gRPC does not have these two actions, causing gRPC client to hang.

**Comment by lizan** [comment]
This should also resolve #8563

**Comment by muxi** [comment]
@ctiller Would appreciate a lot if you can backport this to v1.0.x  in the next week. Firestore is in need of a new release including this fix by 11/14.

**Comment by muxi** [comment]
Gentle ping :)
