### ISSUE TITLE
gRPC_interop_experiments and gRPC_interop_experiments fail to build for node since 10/28

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#8590]
https://grpc-testing.appspot.com/job/gRPC_interop_experiments/4635/console

Failed to execute '/root/.nvm/versions/node/v4.5.0/bin/node /root/.nvm/versions/node/v4.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/local/git/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/var/local/git/grpc/src/node/extension_binary' (1)
../src/core/lib/iomgr/tcp_client_uv.c:144:6: error: conflicting types for 'grpc_tcp_client_connect'
 void grpc_tcp_client_connect(grpc_exec_ctx *exec_ctx, grpc_closure *closure,
      ^
In file included from ../src/core/lib/iomgr/tcp_client_uv.c:45:0:
.././src/core/lib/iomgr/tcp_client.h:51:6: note: previous declaration of 'grpc_tcp_client_connect' was here
 void grpc_tcp_client_connect(grpc_exec_ctx *exec_ctx, grpc_closure *on_connect,
      ^
make: *** [Release/obj.target/grpc/src/core/lib/iomgr/tcp_client_uv.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by murgatroid99** [comment]
The fix for this is pending in #8588, and as you can see, the interop tests are passing there.
