### ISSUE TITLE
[Features] Node client support Promise

### ISSUE THREAD

**Issue by leaves4j** [grpc/grpc#8592]
Can we support client return a Promise?
```js
client.sayHello({name: user})
.then(res => {
  console.log('Greeting:', res.message);
})
.catch(err => throw err);
```

**Comment by sulliwane** [comment]
The Node API for GRPC is only callback based. But you can use [promisifyAll()](bluebirdjs.com/docs/api/promise.promisifyall.html) from [bluebird library](https://www.npmjs.com/package/bluebird) to create a promised based version of your grpc methods:
```javascript
client.sayHelloAsync().then()
```

**Comment by leaves4j** [comment]
@sulliwane Thanks, I write a simple module that support both callback based and Promise,  [grpc-promisify](https://www.npmjs.com/package/grpc-promisify)

**Comment by murgatroid99** [comment]
I want to note that your grpc-promisify only works with single request/single response methods. With other types of methods, it will pass the wrong arguments and overwrite important information in the return value.

**Comment by leaves4j** [comment]
@murgatroid99 tks
