### ISSUE TITLE
Ruby: bounded server thread pools considered harmful

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8603]
This is an issue for Ruby at least. Not sure if it is present in other languages. We must avoid the use of bounded thread pool classes like `Concurrent::ThreadPoolExecutor`. I believe this is worth backporting to v1.0.x as well as this issue is a bug that may not yet have occurred in the wild.

There are three conditions for deadlock:

1. cyclic dependence
2. finite resources
3. non-preempted. Note that I just changed the statement of conditions from the canonical "non-preemptible". The important thing is that the particular items are not pre-empted, not that they're non-preemptible in some abstract sense.

The deadlock arises if you have a backup queue that requests can go into if they don't get a thread right away. Since servers can call other servers (e.g., in proxies), you can run into a cyclic dependence. To make matters simpler, let's just say your pool allows 4 threads max at server A and server B, along with a backup queue at each. Suppose that A::foo calls B::foo and B::bar calls A::bar.
- 4 clients hit A::foo at the same time and hit B::bar at the same time.
  * All thread slots get taken
  * Each server starts a call into the other side. 
  * All those calls get put in the backup queue on the other side but never get serviced.
- Deadlock has arisen.

There are ways out: 
- don't have a finite resource (unbound the thread pool)
- pre-empt (have no backup queue and immediately return RESOURCE_EXHAUSTED if no thread available). This would cause unnecessary rejections in this example (since all 8 requests would get errored even though only 4 need to be) but that's still better than deadlock.

I believe that there is a straightforward solution for Ruby - use CachedThreadPool rather than ThreadPoolExecutor.

**Comment by murgatroid99** [comment]
For the record, Ruby currently uses the second solution that you list. If the thread pool is full, the server responds with RESOURCE_EXHAUSTED.

**Comment by vjpai** [comment]
@murgatroid99 - only if the queue is full too in the current version.

**Comment by vjpai** [comment]
I have just confirmed that the v1.0.x pool, though very different, also has the same issue. If each side has all of its worker threads processing RPCs that call into the other side, those RPCs get queued on the other side and don't get out.

**Comment by vjpai** [comment]
Additionally, CachedThreadPool won't do the job because even that has a mandatory waiting queue associated with it. Even a waiting queue of 1 can lead to a deadlock if the cyclic dependence spans multiple servers.

**Comment by soltanmm-google** [comment]
@nathanielmanistaatgoogle We don't appear to use `RESOURCE_EXHAUSTED` in the suggested way. Do we?

**Comment by vjpai** [comment]
There might be other meaningful status response codes on a fail. The
important thing, though, is not to have a queue backing up a bounded
threadpool that executes application service code.

**Comment by vjpai** [comment]
Ok, I looked over the issue in Python and I'm tagging the issue for Python as well then. futures.ThreadPoolExecutor has no way of being unbounded in worker count and, I think, always allows a new submit - there certainly isn't any error case being handled on submit.

**Comment by vjpai** [comment]
This does not affect C# or Node because the thread pools there are not executing application code.

**Comment by vjpai** [comment]
Just to show that even a waiting queue of 1 can cause deadlock.
Server A and B proxy method foo/bar to each other, respectively, as in my earlier comment - but only sometimes. In non-language-specific pseudocode:

```
A::foo(x, y) {
  A_mu.lock_guard
    A_shared_state_1 += f(A_shared_ctr)
    if (x)
       A_shared_ctr += B::foo(A_shared_ctr, y)
    else
       A_shared_ctr += y
}

B::bar(x, y) {
  B_mu.lock_guard
    B_shared_state_1 += f(B_shared_ctr)
    if (x)
       B_shared_ctr += A::bar(B_shared_ctr, y)
    else
       B_shared_ctr += y
}

```

Again, as in the previous example, 4 simultaneous A::foos show up at A and 4 simultaneous B::bar show up at B. 1 of those RPCs at each side has boolean variable x set, and it gets the shared state mutex first. It has to hold on to the mutex while calling the other side since it has also used the current value one of its shared variables that is being updated as a result of this call. The queuing of the 5th request causes the lock to never be released, and deadlock has arisen.

**Comment by vjpai** [comment]
Separating this out into python and ruby issues so that they can be tracked and closed separately.

**Comment by jacobvosmaer** [comment]
I'm also submitting a PR to put a better message in the error. https://github.com/grpc/grpc/pull/15249
