### ISSUE TITLE
failed compile with google.api.http extension, "google/api/Annotations.pbobjc.h" file not found

### ISSUE THREAD

**Issue by fabware** [grpc/grpc#8615]
gRPC 1.0, "pod install" a proto with following google.api extension, failed to build in xcode. 

```
import "google/api/annotations.proto";

    rpc Login(LoginArg) returns(LoginResponse) {
        option (google.api.http) = {
            post: "/user/login"
            body: "*"
        };
    }
```

It works correctly before I add google.api.http thing into it. Any clue to make it work?

**Comment by jcanizales** [comment]
@fabware how did you bring the `annotations.proto` file into your setup?

**Comment by fabware** [comment]
It exactly my problem is, since I don't have any clue how to craft a podspec for it.

Use sed comment out #import "google/api/Annotations.pbobjc.h", works temporarily but awkward.

**Comment by jcanizales** [comment]
Did you follow [these instructions](https://github.com/grpc/grpc/blob/master/src/objective-c/README.md#cocoapods)?

**Comment by fabware** [comment]
Thanks for your reply.

Yes, I have a working MyProject.podspec in my swift project. 

In my proto definition, I have to use google/api/annotations.proto, which gives me compile error: google/api/Annotations.pbobjc.h header file not found. 

It works before without including google/api/annotations.proto.

**Comment by jcanizales** [comment]
Did you make sure that the `prepare_command` of your podspec is passing `google/api/annotations.proto` to `protoc`, alongside your other proto files?

**Comment by fabware** [comment]
Thanks for your reply. I placed "google/api/annotations.proto"(with folders) into ../../proto, I assume it would be included.

`
  s.prepare_command = <<-CMD
    #{protoc} \
        --plugin=protoc-gen-grpc=#{plugin} \
        --objc_out=. \
        --grpc_out=. \
        -I . \
        -I #{protoc_dir} \
        -I ../../proto \
        -I #{protobuf_dir} \
        ../../proto/*.proto
  CMD`

**Comment by jcanizales** [comment]
Oh, I think I know what's up. The last argument to `protoc` is which proto files to generate code for. You have `../../proto/*.proto`, which will miss the subfolders. Try `../../proto/**/*.proto` so it's recursive? A way to confirm this is to check if the files `google/api/Annotations.pbobjc.h` and `google/api/Annotations.pbobjc.m` were actually been generated.

**Comment by fabware** [comment]
../../proto/**/*.proto gives me error:

```
[!] /bin/bash -c 
set -e
../Pods/!ProtoCompiler/protoc         --plugin=protoc-gen-grpc=../Pods/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin         --objc_out=.         --grpc_out=.         -I .         -I ../Pods/!ProtoCompiler         -I ../../proto         ../../proto/**/*.proto

../../proto/**/*.proto: No such file or directory
```

hardcode folder as ../../*.proto ../../proto/google/api/*.proto compiles, but google/api/Annotations.pbobjc.h cannot be found anywhere.

After minor changes with 

```
 s.subspec 'Messages' do |ms|
    ms.source_files = '**/*.pbobjc.{h,m}'
```

I can see google/api/Annotations.pbobj.h and other files under "Development pods", still it won't compile.

**Comment by Saurman** [comment]
@fabware did u manage to solve this?

**Comment by fabware** [comment]
Yes, comment the headers works with the following scripts (replace FlashService with your own generated directory). Haven't touch it for months, don't if it still works.

```
pod install
sed -i '' -e 's/#import "google\/api\/Annotations.pbobjc.h"/\/\/ #import\ "google\/api\/Annotations.pbobjc.h" \/\/ automatically comment by grpc gen.sh/g ' ./FlashService/*.*
sed -i '' -e 's/    \[registry addExtensions:\[AnnotationsRoot extensionRegistry\]\];/\/\/     \[registry addExtensions:\[AnnotationsRoot extensionRegistry\]\]; \/\/ automatically comment by grpc gen.sh/g' FlashService/*.*
```

**Comment by Xzya** [comment]
The above script + the following line fixed it for me (GAPIAnnotationsRoot instead of AnnotationsRoot):
`sed -i '' -e 's/    \[registry addExtensions:\[GAPIAnnotationsRoot extensionRegistry\]\];/\/\/     \[registry addExtensions:\[GAPIAnnotationsRoot extensionRegistry\]\]; \/\/ automatically comment by grpc gen.sh/g' FlashService/*.*`
