### ISSUE TITLE
Python: bounded server thread pools considered harmful

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8616]
Everything in #8603 applies to Python as well because of the boundedness and queueing of futures.ThreadPoolExecutor

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm-google: in response to [your question](https://github.com/grpc/grpc/issues/8603#issuecomment-258039278), I don't think that we do, but I feel like @kpayson64 has looked at this more recently than I have (and he may have taken action about it but I don't recall that with certainty either).

**Comment by nathanielmanistaatgoogle** [comment]
The fact that gRPC Python accepts `futures.ThreadPoolExecutor` objects from applications may make this hard; we should sit down at some point and talk over how we might solve it.

**Comment by nathanielmanistaatgoogle** [comment]
Marking as a duplicate of [issue 7052](https://github.com/grpc/grpc/issues/7052).
