### ISSUE TITLE
Update examples and tests from oauth2client to google-auth-library-python

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#8621]
Following [this discussion](https://github.com/grpc/grpc/issues/6799), `grpcio` should itself depend on neither `oauth2client` nor `google-auth-library-python`. A `grpcio_tests` → `google-auth-library-python` dependency is just fine, and necessary, and we should put it in place and update all our tests to use `google-auth-library-python` and not `oauth2client` as soon as @jonparrott and @dhermes warrant that `google-auth-library-python` has reached an appropriate level of maturity.

... and then we should do the same for all our example application code.

**Comment by nathanielmanistaatgoogle** [comment]
@jonparrott and @dhermes: [I see that `google-auth-library-python` hit 0.5](https://github.com/GoogleCloudPlatform/google-auth-library-python/commit/90c1c1b5c8f4eda71240b96d671976d289ca6e04); congratulations! Would the two of you now say that `google-auth-library-python` has reached the point at which gRPC Python's documentation, samples, and tests should switch from `oauth2client` to `google-auth-library-python`? Does `google-auth-library-python` have the right functionality in place and in a way that you'd be comfortable supporting? Or should we still be waiting?

**Comment by dhermes** [comment]
I'll defer to @jonparrott

**Comment by jonparrott** [comment]
I would say at this point it's probably okay. 1.0.0 won't change the current API surface at all and I plan to release that as soon as we've got a release of google-api-python-client that supports google-auth.
