### ISSUE TITLE
Kill off the Beta API

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#8622]
It should at least emit warnings when used in 1.1. Could it be killed off in 1.1? 1.2?

I expect that there will be many prerequisites to this; [issue 8621](https://github.com/grpc/grpc/issues/8621) is at least one of them.

**Comment by nathanielmanistaatgoogle** [comment]
Remilestoning; a more realistic target for this issue is "six months after the resolution of [issue 8621](https://github.com/grpc/grpc/issues/8621)".

**Comment by therc** [comment]
Could protoc add a flag to either stop generating beta code or to set a non-standard beta_package_root, which is currently hardcoded to `grpc.beta`? Either way could allow people to start preparing for 1.5 or whichever release kills Beta.

**Comment by nathanielmanistaatgoogle** [comment]
@therc: is [`grpc_2_0`](https://github.com/grpc/grpc/blob/1ba000e1e217410e556ff3a5fa0cb10799e6d289/src/compiler/python_generator.cc#L770) the flag that you have in mind? Or close enough to it?

**Comment by therc** [comment]
@nathanielmanistaatgoogle thanks for the pointer. I guess it's not documented for a reason. :smile: 
I tried it and it seems to work for proto files that define services, but for those that have none, the pb2_grpc.py files are empty (just an `import grpc`) and don't import the pb2 module (not they include it inline).

Is that a bug or are developers expect to compile such protocol buffer definitions without the grpc plugin?

**Comment by nathanielmanistaatgoogle** [comment]
@therc: there's no _good_ reason why it's not documented; maybe at the time we thought Bazel-integrated code generation would arrive much sooner and users wouldn't be using it directly? For the time being we'd certainly rather users use it than not. Empty _pb2_grpc files are not a bug (because they're completely harmless if ignored, right?) and they do exactly fit the definition of "the gRPC-related code elements consequent to a `.proto` that defines no services". If you have an empty-of-both-messages-and-services `.proto` file and run the code generator, does anything complain or do you just get containing-only-trivial-imports `_pb2_grpc.py` _and_ `_pb2.py` files?

**Comment by therc** [comment]
That makes sense. It's just that the pb2.py file says

`  # Please use the generated *_pb2_grpc.py files instead.`

So I used a very low-tech Rosie (a bunch of sed commands) to fix our hundreds of imports. On one hand, it's true that it's not unreasonable for the pb2_grpc file to only have anything related actual gRPC services, but on the other hand, there's probably a lot of code out there like ours that imports the pb2 module (and only that), module which never really cared about whether services were defined or not. Making the migration will now require more manual editing, or at least more careful automated edits. You need to touch actual code, too, not just imports: e.g., at call sites, you need to replace `foo_pb2` with `foo_pb2_grpc` (I had tried avoiding that by importing `foo_pb2_grpc as foo_pb2`).

**Comment by nathanielmanistaatgoogle** [comment]
It is definitely the case that when we became aware that putting the gRPC-related code elements in the `_pb2.py` file was a mistake and that those code elements belonged in a separate `_pb2_grpc.py` file we anticipated that there would be user discomfort in getting to the eventual "future of separate files". It sounds like you're experiencing discomfort, but are you experiencing too much? You're certainly able to hold off on passing the flag until after migrating all use sites, right? It's not like you have to do it all in one atomic operation, right?

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle can we target killing this off for 1.10?

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: @kpayson64 is working on this slowly in between more pressing tasks. The current state is that we'd like to assist some of our early adopters/complex use-case users in migrating to the final API before declaring the Beta API formally deprecated.

Of course it's been _informally_ deprecated for a long time...

**Comment by hsaliak** [comment]
Do we know for sure of people using the beta API? What will happen if we just kill it?

**Comment by kpayson64** [comment]
We will break a litany of projects internally.

**Comment by nathanielmanistaatgoogle** [comment]
[We have now announced that we are dropping support for the Beta API on 2018-07-01.](https://groups.google.com/d/msg/grpc-io/SMwQSF0BAcs/Tqiwi-NHAgAJ)

**Comment by nathanielmanistaatgoogle** [comment]
Huh. It's still there in the code. How about that.
