### ISSUE TITLE
client send malformed HEADER frame when there is a empty binary header

### ISSUE THREAD

**Issue by lizan** [grpc/grpc#8624]
To reproduce:
`client_context.AddMetadata("header-bin", "");`
on any RPC call would result GOAWAY frame from server.

<img width="1455" alt="screen shot 2016-11-03 at 12 29 42 pm" src="https://cloud.githubusercontent.com/assets/1016047/19982029/9639af30-a1c1-11e6-8ce2-ab0aff30978c.png">
The value of header-bin in the frame is malformed as it is shown above.

**Comment by ncteisen** [comment]
What is your use case for sending true binary metadata with empty value?

The binary metadata extension was introduced for a very specific, performance critical, internal use case. I don't see a use case in which the value is empty

**Comment by lizan** [comment]
In Cloud Endpoints we provide gRPC proxy with transcoding from JSON/REST, I don't know what is the particular use case of the case of actually setting a binary header to empty since it is customer traffic, but it happens when the proxy receives such requests either in gRPC or REST. In such case gRPC client library shouldn't produce an invalid HTTP/2 frame which results GOAWAY, and cause other requests in same connection fail.

**Comment by ncteisen** [comment]
I cannot reproduce this. See a test I added in #17951, which passes as is

**Comment by ncteisen** [comment]
Closing for now, please leave a comment if you can repro and we will re open
