### ISSUE TITLE
gRPC C# doesn't support Universal Windows Applications

### ISSUE THREAD

**Issue by butterklopsi** [grpc/grpc#8636]
when i try to install grpc via NuGet into a Windows 10 / UWP Project it always says 
`Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).`
and below
`+ Install-Package Grpc
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand`
it would be good to be able to use grpc in modern universal windows application

**Comment by hsaliak** [comment]
@jtattermusch do we want to do this for 1.1?

**Comment by jtattermusch** [comment]
Currently we are supporting .NET4.5+ and netstandard1.5+.

**Comment by jtattermusch** [comment]
We currently don't have any plan to support Universal Windows Apps, but technically this should be feasible. More investigation in terms of what would that require is needed though. Feel free to contribute.

**Comment by jtattermusch** [comment]
This has fallen below the team’s cutoff, however we welcome contributions from the community. Closing.

**Comment by AtosNicoS** [comment]
UWP apps now support .NET Standard 2.0:
https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/

If I understand correct, this means there is a chance to use GRPC within UWP applications. However when I am using GRPC with UWP I get the following exception:
```csharp
Channel channel = new Channel(host, port, credentials);
//System.TypeLoadException: 'Could not load type 'System.Runtime.Loader.AssemblyLoadContext' 
//from assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, 
//PublicKeyToken=b03f5f7f11d50a3a'.'
```

Was anyone able to get GRPC running in UWP Apps?

**Comment by jtattermusch** [comment]
@AtosNicoS  I believe the only place where we are using AssemblyLoadContext is https://github.com/grpc/grpc/blob/33e57824e01d664b520252a09c92ce397cca5e56/src/csharp/Grpc.Core/GrpcEnvironment.cs#L426.

I am not sure what your mileage is, but as an experiment, you could try re-building gRPC after commenting out that line and see if things work afterwards.

**Comment by AtosNicoS** [comment]
@jtattermusch I still got problems rebuilding GRPC. I would like to kindly ask if you could [help me with the build](https://github.com/grpc/grpc/issues/15100) or provide me a testbuild with the suggested change above.

**Comment by jtattermusch** [comment]
@AtosNicoS  please see https://github.com/grpc/grpc/issues/15100#issuecomment-384210397 which should make you all set.

**Comment by lhecker** [comment]
@jtattermusch I'm _extremely_ unfamiliar with C#, but I believe this might the proper fix right?
```diff
diff --git a/src/csharp/Grpc.Core/GrpcEnvironment.cs b/src/csharp/Grpc.Core/GrpcEnvironment.cs
index 6bb2f6c3e5..2c7b02daa0 100644
--- a/src/csharp/Grpc.Core/GrpcEnvironment.cs
+++ b/src/csharp/Grpc.Core/GrpcEnvironment.cs
@@ -422,9 +422,9 @@ namespace Grpc.Core
                 {
                     if (!hooksRegistered)
                     {
-#if NETSTANDARD1_5
+#if NETCOREAPP1_0
                         System.Runtime.Loader.AssemblyLoadContext.Default.Unloading += (assemblyLoadContext) => { HandleShutdown(); };
-#else
+#elif
                         AppDomain.CurrentDomain.ProcessExit += (sender, eventArgs) => { HandleShutdown(); };
                         AppDomain.CurrentDomain.DomainUnload += (sender, eventArgs) => { HandleShutdown(); };
 #endif
```
(Because `AssemblyLoadContext` is a .NET-Core and not -Standard class?)

Now if we additionally had a fix to replace `cares`, since it doesn't support UWP... That'd be great. 😅🙂

**Comment by AtosNicoS** [comment]
@lhecker Your patch has an `elif` part without if statement. I guess that is wrong. If I revert to a normal `else` I get the error: `The name 'AppDomain' does not exist in the current context`.

I am currently testing commenting out the suggested line.

**Comment by lhecker** [comment]
@AtosNicoS Thanks for testing this. 🙂 I had some condition at the `#elif` previously, but I sadly forgot what it was. Too bad it doesn't work though. 😕

**Comment by AtosNicoS** [comment]
@jtattermusch I gave your patch finally a try and it works! If I comment the suggested line GRPC (client) is working properly inside my UWP app.  Now we have two questions:

* Are there any negative side effects this patch can cause? Or is it safe to use in general?
* Are you going to include this patch in the next pre-release? We really need UWP support for Grpc.

**Comment by AtosNicoS** [comment]
@jtattermusch Any updates on this?

**Comment by AtosNicoS** [comment]
I even tested GRPC with the Hololens and it is working fine. In standard and in streaming mode. Any chance to see this fix merged soon?

**Comment by jtattermusch** [comment]
@AtosNicoS if by "fix" you mean commenting out grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs - that's not a proper fix IMHO - it's just an experiment that the grpc stack can work for UWA. We only want to disable that line for universal windows apps, not for other platforms, because the that line is there for a good reason.
So the "fix" won't get merged, but feel free to contribute a PR that has an actual fix.

**Comment by AtosNicoS** [comment]
@jtattermusch Correct, it is not a proper fix to just comment that line for non-uwp apps. 

> because the that line is there for a good reason.

Sure, but what about UWP Apps? Isnt that line required for UWP or will we possibly run into other issues when its left out?

In the case we can just comment it for UWP apps, a small ifdef-like surrounding (as @lhecker suggested) could be enough. However that fix did not work. I found [this](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) page that lists some preprocessor symbols, but non for UWP. But maybe this will help:

![grafik](https://user-images.githubusercontent.com/37442184/41228673-70d1ec78-6d79-11e8-933c-74c3360dbdc4.png)

I will try and report if it works.

**Comment by VladimirAkopyan** [comment]
any updates on this? we develop UWP apps and it's key for us to know whether we can use grpc for our next project

**Comment by nicolasnoble** [comment]
Did you see Jan's latest comment and tried it out?

**Comment by AtosNicoS** [comment]
It looks like Grpc is now working properly with UWP. If I find any issues, I will report. @jtattermusch thank you very much for the support and updates!

**Comment by MohsenneChaverdie** [comment]
Unfortunately, it cannot get compiled for me. I am using 1.16. I described it as much as I could in this [post](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend). Let me know if I need to provide more info.

**Comment by MohsenneChaverdie** [comment]
My Problem [solved](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402).

**Comment by tylersouthard** [comment]
I'm curious if anyone using gRPC for UWP is actually creating a store app (compiling with the .NET Native tool chain)? See #18188.
