### ISSUE TITLE
gpr_log_func_args can not be forward declaration

### ISSUE THREAD

**Issue by Dustskyfield** [grpc/grpc#8637]
In grpc/impl/codegen/log.h, the struct gpr_log_func_args declaration like below:
```
typedef struct {
  const char *file;
  int line;
  gpr_log_severity severity;
  const char *message;
} gpr_log_func_args;

typedef void (*gpr_log_func)(gpr_log_func_args *args);
```

When users want to use a customized log function, they can't must include file grpc/impl/codegen/log.h in theirs .h.

The better way is using forward declaration in header file, and including log.h in cpp file.

**Comment by ctiller** [comment]
Do you have some example code that doesn't work?

**Comment by Dustskyfield** [comment]
for example, I have an implemented logger, I want logs of gRPC are printed into a some log file. 

so write codes as below:
logger.h
```
#include "grpc/impl/codegen/log.h"
class logger {
    void logger_init();
    void  WriteGRPCLog(gpr_log_func_args* args);
}
```

logger.cpp
```
#include "logger.h"
void logger::logger_init()
{
    gpr_set_log_function(WriteGRPCLog);
    gpr_set_log_verbosity(GPR_LOG_SEVERITY_DEBUG);
    gpr_log_verbosity_init();
}

void  WriteGRPCLog(gpr_log_func_args* args)
{
    // write log into files...
}
```


and then there another module wants to use logger too.
but when that module include logger.h, it include "grpc/impl/codegen/log.h" too.
this module doesn't use grpc, so this is unless.
The logger is so common to my application, so I have to change all moudle's makefile to include grpc's log.h

I exactly want GRPC to do a little change in log.h as below:
now:
```
typedef struct {
  const char *file;
  int line;
  gpr_log_severity severity;
  const char *message;
} gpr_log_func_args;
```

wanted:
```
struct gpr_log_func_args {
  const char *file;
  int line;
  gpr_log_severity severity;
  const char *message;
};
```

then I can take forward declaration instead of include in my logger.h:
new logger.h
```
// #include "grpc/impl/codegen/log.h"
struct gpr_log_func_args;
class logger {
    void logger_init();
    void  WriteGRPCLog(gpr_log_func_args* args);
}
```

I think this little change will be really convenient for grpc users.
