### ISSUE TITLE
Proposal: Extension point for TCP implementations

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#8639]
# Problem

Endpoints are the lowest-level networking layer in the gRPC core. The most commonly used endpoint is the TCP implementation. We have seen increasing demand for different endpoint implementations, including alternate TCP stacks and TCP-like protocols. Some of these would be too special-case to support within the gRPC core itself.

# Solution

Our solution to this is to add add public APIs (with respect to the C core) that allow the existing endpoint implementations to be modified or replaced.

# Proposed Implementation

We will make the header files `src/core/lib/iomgr/tcp_client.h` and `src/core/lib/iomgr/tcp_server.h` public, with vtable definitions in place of function definitions to allow for extensibility. They would look something like this:

## `tcp_client.h`

```c
typedef struct grpc_tcp_client grpc_tcp_client;
typedef struct grpc_tcp_client_vtable {
  void (*connect)(grpc_exec_ctx *exec_ctx, grpc_closure *on_connect,
                  grpc_endpoint **endpoint,
                  grpc_pollset_set *interested_parties,
                  const grpc_channel_args *channel_args,
                  const grpc_resolved_address *addr,
                  gpr_timespec deadline);
  void (*ref)(grpc_tcp_client *client);
  void (*unref)(grpc_exec_ctx *exec_ctx, grpc_tcp_client *client);
} grpc_tcp_client_vtable;


struct grpc_tcp_client {
  const grpc_tcp_client_vtable *vtable;
};
```

## `tcp_server.h`

```c
typedef struct grpc_tcp_server_acceptor // as currently defined;
typedef void (*grpc_tcp_server_cb) // as currently defined;
typedef struct grpc_tcp_server grpc_tcp_server;


typedef struct grpc_tcp_server_vtable {
  void (*start)(grpc_exec_ctx *exec_ctx, grpc_tcp_server *server,
                grpc_pollset **pollsets, size_t pollset_count,
                grpc_tcp_server_cb on_accept_cb, void *cb_arg);
  void (*add_port)(grpc_tcp_server *s,
                   const grpc_resolved_address *addr,
                   int *out_port);
  void (*ref)(grpc_tcp_server *s);
  void (*unref)(grpc_exec_ctx *exec_ctx, grpc_tcp_server *s);
  void (*shutdown_starting_add)(grpc_tcp_server *s,
                                grpc_closure *shutdown_starting);
} grpc_tcp_server_vtable;


struct grpc_tcp_server {
  const grpc_tcp_server_vtable *vtable;
};


typedef struct grpc_tcp_server_factory grpc_tcp_server_factory;


typedef struct grpc_tcp_server_factory_vtable {
  void (*create_server)(grpc_exec_ctx *exec_ctx,
                        grpc_closure *shutdown_complete,
                        const grpc_channel_args *args,
                        grpc_tcp_server **server);
  void (*ref)(grpc_tcp_server_factory *f);
  void (*unref)(grpc_exec_ctx *exec_ctx, grpc_tcp_server_factory *f);
} grpc_tcp_server_factory_vtable;


struct grpc_tcp_server_factory {
  const grpc_tcp_server_factory_vtable *vtable;
};
```

The existing headers with function declarations will stay internal, and `src/core/lib/iomgr/endpoint.h` will be split, with the vtable and struct definitions moved to an external header, and the function declarations staying in an internal header. Like with the endpoint code, the only explicit implementations of the client and server interfaces will be vtable calls, and the existing implementations will change to define vtables.

We will also add two channel arg keys to allow API users to use their TCP implementations with their channel or server. I propose `"grpc.tcp.client"`, which will have a pointer value of type `grpc_tcp_client*` and `"grpc.tcp.server_factory"`, which will have a pointer value of type `grpc_tcp_server_factory*`.

These interfaces use types from other iomgr headers, so the following headers from `src/core/iomgr/` will also need to become public:

 - `closure.h`
 - `error.h`
 - `exec_ctx.h`
 - `pollset.h`
 - `pollset_set.h`
 - `resolve_address.h`
 - `resource_quota.h`

plus `src/core/lib/support/mpscq.h`

**Comment by shssf** [comment]
@murgatroid99 
It looks promising but may I ask you for a usage model for this?
As I understand, the `channel` will have additional keys to expose the endpoint type to other side. What endpoint is planned to use to transmit this information?
The gRPC server have to support different clients at the same time. How it should switch endpoint from default (tcp) to user requested?
I thought the workflow looks like:
- client: creates alternative endpoint and a channel based on it.
- client: send handshake request with special endpoint information to the server using default, tcp based gRPC endpoint, connection.
- server: if server doesn't support alternative endpoint, it reject this connection.
- server: if server supports this type of endpoint, it send server side alternative endpoint information to the client.
- server: creates alternative endpoint, change current endpoint (tcp based) to alternative communication way and wait for an events on new file descriptor.
- client: receive handshake information from the server via default channel (tcp). Change current connection method to alternative.
- client and server: Do RPC via alternative endpoints
- Shutdown procedure should destroy alternative endpoints and fallback into default gRPC tcp based endpoints. gRPC finishes the channel shutdown using default procedures.

One more question if you don't mind.
What is deadline/time shedule for implementation of the proposed changes?

@miked-mellanox FYI

**Comment by murgatroid99** [comment]
Using this API would be a lot simpler than all that. The client and server would each be initialized with compatible endpoints using the channel arguments, then they would communicate using those endpoints. The `"grpc.tcp.client"` argument would only be used on the client side, and the `"grpc.tcp.server_factory"` argument would only be used on the server side.

We plan to get this done this quarter, assuming there are no major issues.

**Comment by nikhilkalige** [comment]
@murgatroid99 If there has been any work done in this regard, can you please share the branch. I was looking to do some work with regards to moving to a different low level transport system for our embedded systems.

**Comment by murgatroid99** [comment]
I haven't started implementation work on this yet. But I have created a more formal proposal at grpc/proposal#8 to solidify the design.

**Comment by zxtwonder** [comment]
It looks like the referenced proposal has been dropped. Is there any progress on this feature? Thanks.

**Comment by murgatroid99** [comment]
There has been no progress, and it is likely that if something like this ever happens, it won't be in this form.
