### ISSUE TITLE
objective-c - Examples

### ISSUE THREAD

**Issue by johndpope** [grpc/grpc#8645]
@muxi 

<img width="1078" alt="screen shot 2016-11-04 at 20 06 59" src="https://cloud.githubusercontent.com/assets/289994/20025919/2a09516c-a2ca-11e6-94da-a6fa5e26a624.png">
<img width="1057" alt="screen shot 2016-11-04 at 20 07 02" src="https://cloud.githubusercontent.com/assets/289994/20025920/2c61a4aa-a2ca-11e6-8f7a-529ff82744fa.png">

you do realise that this repo contains examples for objective-c in different places?
https://github.com/grpc/grpc/tree/master/src/objective-c/example
https://github.com/grpc/grpc/tree/master/examples/objective-c

I'm most interested in the services class generated by objective-c and ultimately porting this code to swift services generator. Could use extra help here
https://github.com/grpc/grpc-swift/issues/2

Probably would be better to differ users to offical grpc-swift repo.

**Comment by muxi** [comment]
Yep we do understand that the examples are in different places. We have not started cleaning it up but thanks for bringing it up.

**Comment by johndpope** [comment]
hey @muxi  - I'm closing this out as I'm doing some spring cleaning.
