### ISSUE TITLE
Accessing metadata in Python

### ISSUE THREAD

**Issue by Lars-H** [grpc/grpc#8655]
Hi,

I am trying to send metadata from the server to client. 
If my service responds with a stream, I can simply call the `initial_metadata()` from the response and get the metadata provided by the server. However, for a service that does not return a stream, but a single response, I can't seem to be able to access the metadata provided by the server.
Is it possible to send metadata from the server to the client for a service that does not respond with a stream?
Thanks!

**Comment by soltanmm-google** [comment]
If I'm combo-remembering/reading-the-code right, you're going to want to call the [`future()`](https://github.com/grpc/grpc/blob/v1.0.1/src/python/grpcio_tests/tests/protoc_plugin/_python_plugin_test.py#L275) method on your stub invocation to get a [`grpc.Call`](https://github.com/grpc/grpc/blob/v1.0.1/src/python/grpcio/grpc/__init__.py#L305) object back. That object should then provide you the metadata for non-streaming calls.

**Comment by Lars-H** [comment]
Hi,
thanks! This works. The `future()` method returns a `grpc._channel._Rendezvous` object, from which I can then call `initial_metadata()`.
