### ISSUE TITLE
C#: Update System.Interactive.Async to v3.1

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#8656]
I found an [odd bug](https://github.com/Reactive-Extensions/Rx.NET/issues/290) with System.Interactive.Async 3.0 which is fixed in 3.1.

I can upgrade my dependencies myself of course, but for the sake of other users it's probably worth updating to 3.1 in Grpc.Core as well.

**Comment by jtattermusch** [comment]
@jskeet  it seems that upgrading to 3.1 seems problematic, as 3.1 doesn't define dependencies per-framework and rather depends on netstandard.Library even when on net45. I really don't what to mess up everyone's project with ~20 useless dependencies pulled by Netstandard.Library.

**Comment by jskeet** [comment]
// cc @onovotny to comment on this...

**Comment by jskeet** [comment]
Given https://github.com/aspnet/EntityFramework/issues/6328#issuecomment-261957881 it sounds like 3.1.1 fixes this.

**Comment by jtattermusch** [comment]
@jskeet   thanks for the tip, a PR is out.
