### ISSUE TITLE
FW: Unable to do "npm install" for Speech on MacOS #248

### ISSUE THREAD

**Issue by jcastill0** [grpc/grpc#8657]
Originally posted on GoogleCloudPlatform/nodejs-docs-samples
I was asked to reference this issue:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/248

Basic problem is with grpc@1.0.1 install

**Comment by murgatroid99** [comment]
You said that you also tried installing under Node versions 4, 5, and 6. What errors did you get when you did that?

**Comment by jcastill0** [comment]
Yes, although I don't remember anymore the combinations I tried, but I tried both on Linux and MacOS.

**Comment by jcastill0** [comment]
I guess this is a duplicate of https://github.com/grpc/grpc/issues/8649

**Comment by murgatroid99** [comment]
That other issue only mentions a failure to install on Node 7. Failure to install on different versions is a different problem.

**Comment by hsaliak** [comment]
@jcastill0 could you please clarify the errors you got?

**Comment by jcastill0** [comment]
@hsaliak, please see the stack below. I understand that node v7 is not supported, so I downgraded the version that I am running on Ubuntu16.

vagrant@ubuntu16:~/speech/node$ npm install grpc

> grpc@1.0.1 install /home/vagrant/speech/node/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Linux 4.4.0-47-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/vagrant/speech/node/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/vagrant/speech/node/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /home/vagrant/speech/node/node_modules/grpc
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/vagrant/speech/node/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/vagrant/speech/node/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vagrant/speech/node/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-47-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/vagrant/speech/node/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vagrant/speech/node/node_modules/grpc
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/vagrant/speech/node/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/vagrant/speech/node/node_modules/grpc/src/node/extension_binary' (1)
npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/speech/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grpc"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/speech/node/npm-debug.log

**Comment by murgatroid99** [comment]
I think you mentioned something similar in your other issue. The beginning of that error output shows that it tried to download a file and failed. But that file definitely exists, and I can download it. I don't know why you might be getting an error like that.
