### ISSUE TITLE
[Python install] Unable to build the library under Alpine linux

### ISSUE THREAD

**Issue by evmin** [grpc/grpc#8671]
The error is:

`No symbol version section for versioned symbol `memcpy@GLIBC_2.2.5'`

Dockerfile to reproduce:

`
FROM alpine:3.4

RUN apk update
RUN apk add --no-cache --virtual=build-dependencies tzdata ca-certificates curl gcc py-cffi py-cryptography python-dev libffi-dev openssl-dev build-base libc6-compat linux-headers
RUN apk add openssl py-cffi py-cryptography git
RUN apk add py-pip
RUN pip install 'grpcio==1.0.1'
`

**Comment by soltanmm-google** [comment]
I believe this coincides with #8658, so closing as a duplicate, but thanks much for the dockerfile!

**Comment by evmin** [comment]
Yes, the same.

BTW, libc6-compat is not required - I was just trying out.
