### ISSUE TITLE
PHP error installing grpc from pecl CentOS7.2 x86_64

### ISSUE THREAD

**Issue by edoger** [grpc/grpc#8690]
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... gawk
checking whether to enable grpc support... yes, shared
./configure: line 4112: cd: ../../grpc: No such file or directory
./configure: line 4143: cd: ../../grpc/src/php/ext: No such file or directory
./configure: line 4174: cd: ../../grpc/third_party/boringssl: No such file or directory
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h

make
... ...

/bin/sh /usr/local/src/grpc-1.0.1/libtool --mode=compile cc -Wall -Werror     -Wno-parentheses-equality -Wno-unused-value -std=c11     -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/usr/local/src/grpc-1.0.1 -DPHP_ATOM_INC -I/usr/local/src/grpc-1.0.1/include -I/usr/local/src/grpc-1.0.1/main -I/usr/local/src/grpc-1.0.1 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/include -I/grpc  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c -o src/core/lib/tsi/ssl_transport_security.lo 
 cc -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/usr/local/src/grpc-1.0.1 -DPHP_ATOM_INC -I/usr/local/src/grpc-1.0.1/include -I/usr/local/src/grpc-1.0.1/main -I/usr/local/src/grpc-1.0.1 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/include -I/grpc -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c  -fPIC -DPIC -o src/core/lib/tsi/.libs/ssl_transport_security.o
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c: 在函数‘ssl_handshaker_extract_peer’中:
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c:967:3: 错误：隐式声明函数‘SSL_get0_alpn_selected’ [-Werror=implicit-function-declaration]
   SSL_get0_alpn_selected(impl->ssl, &alpn_selected, &alpn_selected_len);
   ^
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c: 在函数‘tsi_create_ssl_client_handshaker_factory’中:
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c:1366:7: 错误：隐式声明函数‘SSL_CTX_set_alpn_protos’ [-Werror=implicit-function-declaration]
       if (SSL_CTX_set_alpn_protos(
       ^
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c: 在函数‘tsi_create_ssl_server_handshaker_factory_ex’中:
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c:1521:7: 错误：隐式声明函数‘SSL_CTX_set_alpn_select_cb’ [-Werror=implicit-function-declaration]
       SSL_CTX_set_alpn_select_cb(impl->ssl_contexts[i],
       ^
/usr/local/src/grpc-1.0.1/src/core/lib/tsi/ssl_transport_security.c: 在文件作用域：
cc1: 错误：无法识别的命令行选项“-Wno-parentheses-equality” [-Werror]
cc1: all warnings being treated as errors
make: *** [src/core/lib/tsi/ssl_transport_security.lo] 错误 1

**Comment by stanley-cheung** [comment]
Ah, did you try to install this by doing this?
```
pecl download grpc
pecl install grpc-1.0.1.tgz
```

If so, then that should have been fixed in version `1.1.0`.

**Comment by edoger** [comment]
I have tried, grpc-1.1.0 has no problem.
