### ISSUE TITLE
C++ compile error for HelloWorld with VS2015

### ISSUE THREAD

**Issue by prasdeva** [grpc/grpc#8691]
Hello,

I am a newbie to gRPC. I got hold of the master(24e5f37) to try play with HelloWorld C++ example on windows but having compile error. I have compiled gRPC using provided solution files with in vsprojects folder. For HelloWorld test I have included below to client and server projects.

- helloworld.grpc.pb.*
- helloworld.pb.*
- greeter_*.cc

I hit below error while compiling helloworld.grpc.pb.cc

error C2079: 'GRPC_FINAL' uses undefined class 'helloworld::Greeter'

followed by 28 related errors, I think.

Looks like compiler can't find definition for GRPC_FINAL. However If I switch back to gRPC v1.0.0, GRPC_FINAL and other 2 macros are defined at include\grpc++\impl\codegen\config.h. I started with v1.0.0 but forced to move over to master due to #7828

Going through the recent changes, I see that GRPC_FINAL and others were removed from that header but 'protoc' still generates them. 

I have refined those to get my test working, however it needs a proper fix I think!

**Comment by murgatroid99** [comment]
Try using v1.0.1. That is the latest release version, and it includes #7828.
