### ISSUE TITLE
GOAWAY from intermediary

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#8695]
Under large parallel load where some operations are cancelled, a channel can drop into transient failure and then hang due to a GOAWAY from an intermediary.

{"created":"@1478653741.518110796","description":"GOAWAY received","file":"third_party/apphosting/python/grpcio/v1_0_0/src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":770,"http2_error":1,"raw_bytes":"77 72 6f 6e 67 5f 66 72 61 6d 65 5f 73 65 71 75 65 6e 63 65 'wrong_frame_sequence'"}

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: how do we determine whether or not this is still happening? Is there a test drafted somewhere that demonstrates it (or verifies that it no longer happens)? If it is still happening; please assign a priority and decide whether or not this should be punted from `1.1` to a later milestone.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks; punting.

**Comment by kpayson64** [comment]
I don't think this is an issue anymore.
