### ISSUE TITLE
Detect the close of http2 connection [node.js]

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#8709]
I know how to detect the closing event of an **http2 stream**, by listening to ```stream.on('cancelled')``` event. Now I'd like to detect when the **whole HTTP2 connection** has been closed. Is that possible in **node.js**?

I'm looking at the [node.js API,](http://www.grpc.io/grpc/node/index.html) and these methods:
- http://www.grpc.io/grpc/node/global.html#waitForClientReady
- http://www.grpc.io/grpc/node/module-src_server.html (**waitForCancel()**)

But don't know which one is suitable and how to use them...?!

Many thanks for any help!

**Comment by sulliwane** [comment]
@murgatroid99 any idea on this one? Many thanks :)

**Comment by murgatroid99** [comment]
There isn't currently an API to do this. `waitForClientReady` just waits (on the client side) for a client to successfully connect, and `waitForCancel` is mainly an internal function, and its primary purpose is to emit that `'cancelled'` event you mentioned.

You seem to be talking about the server side, but the Node server doesn't expose any information about HTTP2/TCP connections, just individual streams.

On the client side, it may be possible to add a function to do this using the same internal API that `waitForClientReady` uses, but it would be subject to stuff like TCP timeouts and any internal reconnect attempts that might take place.

**Comment by sulliwane** [comment]
thanks for your feedback.

I just tried ```waitForClientReady``` on the client side: ```grpc.waitForClientReady(client, 0, () => console.log('connected'));```and it works.

For the informations about **HTTP2/TCP** connections, is it specific to **Node server**, or has the **c++ grpc server** the same limitation? If this information is available, it can help the node server on taking the decision to free ressources (associated with a client that completely disconnected the whole HTTP2 connection). But maybe there is no such information...I'm not very familiar with HTTP2.

**Comment by murgatroid99** [comment]
I think all of the servers (at least the ones in this repository) have that same property. Information about connections is not exposed in the API, so you should not have any resources associated with an entire connection. Even if you identify your clients somehow and allocate a resource for a client, there's no guarantee that all ongoing calls from that client use the same connection.

**Comment by sulliwane** [comment]
I see. Indeed every client generates a ```uuid``` and place it in a metadata, so that the server knows to which client (uuid) is allocated a resource. So you are saying I should handle de-allocation of resources based on stream connection only (```cancelled``` event) right?

**Comment by murgatroid99** [comment]
To be clear, the `cancelled` event generally indicates that something went wrong with the stream. If you just want to know if the stream has finished, one way or another, you're better off listening for the `end` event.

Otherwise, yes, you should deallocate resources associated with a stream when that stream finishes, and you should deallocate resources associated with a client when you know that that client is no longer connected (e.g. when there are no more streams with that UUID).

**Comment by sulliwane** [comment]
Got it. Many thanks!
