### ISSUE TITLE
How to use the certificate adaptation iOS9.0 HTTPS version

### ISSUE THREAD

**Issue by zhl778899** [grpc/grpc#8711]
I use which method
useInsecureConnectionsForHost:
or
setTLSPEMRootCerts: forHost: error:

**Comment by muxi** [comment]
Hi, can you elaborate your question please? We are not quite sure what you mean by "certificate adaptation" and what you would like to achieve.

For those two mechods, if you want to use gRPC without TLS security, you can use useInsecureConnectionsForHost. If you do want TLS you use setTLSPEMRootCerts.
