### ISSUE TITLE
RST_STREAM under heavy load

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#8712]
@jtattermusch Using a C# server listening to receive SSL conections from C++/C# clients, a RpcException is raised under heavy load (hundreds of active connections to the same server). Some encrypted **client** connections start to fail after a while (over a minute) with the following RpcException:
> Status(StatusCode=Cancelled, Detail="{"created":"@1478759465.033000000","description":"RST_STREAM","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\ext\transport\chttp2\transport\frame_rst_stream.c","file_line":107,"http2_error":8}")

Which means some connection got RST packets from the server.
May be related to #8382?

**Comment by jtattermusch** [comment]
Does it also happen C# client to C# server?
Can it happen with insecure connections?

**Comment by amitwaisel** [comment]
It happens in the examples I sent you (for convenience, I attach links to the examples) when running with 200 clients in parallel. They are all C#.

Please add the following line to the `Client`'s `Reconnect()` function, inside the `List<ChannelOption>`, before running the examples:
```C#
new ChannelOption("grpc.initial_reconnect_backoff_ms", (int)TimeSpan.FromMinutes(1).TotalMilliseconds)
```

1. The secure connection fail quite rarely with RST error. Sometimes it takes some time for the tester to reach this state.
2. The insecure connection scenario runs with 200 clients without any noticeable problems. I stopped it after 12 minutes (maybe it will happen later? maybe it is a rare case like the encrypted scenario?)
3. Running **over 205** clients with secure connections (on my windows machine) resulted some `RpcException`s on connection initialization, with status `Status(StatusCode=Unavailable, Detail="")`

links to examples:
[GrpcTest_Insecure.rar](https://www.dropbox.com/s/5g6ea6p0hddfo3b/GrpcTest_Insecure.rar?dl=0)
[GrpcTest_SSL.rar](https://www.dropbox.com/s/pzfearzpje85juw/GrpcTest_SSL.rar?dl=0)

**Comment by jtattermusch** [comment]
There's been no update on this in the last 4 months, please reopen if you are still seeing issues.
