### ISSUE TITLE
JWT access to google APIs doesn't work?

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8717]
Has anyone been able to get this working? Perhaps a problem with google APIs backend settings?

Context #8573

**Comment by jtattermusch** [comment]
@adelez, @ncteisen  can you take a look?

CC @jboeuf

**Comment by adelez** [comment]
Are they referring to the service yaml config 
authentication:
oauth:
      canonical_scopes:?

**Comment by ncteisen** [comment]
Open for over a year with no comments. Closing
