### ISSUE TITLE
AbortionError: StatusCode.INTERNAL from Python GRPC client library

### ISSUE THREAD

**Issue by gguuss** [grpc/grpc#8722]
I'm running the [Google Cloud Speech sample](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/grpc) and am occasionally encountering a very strange crash from the client library:

    Traceback (most recent call last):
      File "speech_to_search.py", line 287, in <module>
        main()
      File "speech_to_search.py", line 279, in main
        listen_print_loop(recognize_stream, stoprequest)
      File "speech_to_search.py", line 191, in listen_print_loop
        for resp in recognize_stream:
      File "/Users/class/code/cloud/samples/python-docs-samples/speech/grpc/env/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 153, in next
        return self._next()
      File "/Users/class/code/cloud/samples/python-docs-samples/speech/grpc/env/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 147, in _next
        raise _abortion_error(rpc_error_call)
    grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INTERNAL, details="{"created":"@1478802146.356202000","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken  #pipe","syscall":"sendmsg"}")

I'm using the client library from OSX version 10.11.6 (El Capitan) with Python 2.7.10 invoked from a virtualenv.

**Comment by nathanielmanistaatgoogle** [comment]
@dgquintas and/or @ctiller: what might the details string `{"created":"@1478802146.356202000","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken  #pipe","syscall":"sendmsg"}` be indicating here?

**Comment by kpayson64** [comment]
I think this is the same as #7663, and should be fixed by  #8745

**Comment by nathanielmanistaatgoogle** [comment]
Given that [pull request 8745](https://github.com/grpc/grpc/pull/8745) was integrated into `master` on 9 December 2016 we believe that this issue will be fixed in release `1.1.0`. Please verify when the first `1.1.0` release candidate becomes available, which should be... in the next seven days?

**Comment by nathanielmanistaatgoogle** [comment]
Closing; apparently our current development practice is to represent "fixed in source but not yet released" with the closed issue state rather than some combination of labels on an open issue. I think we should change this practice but will conform to it until after I've persuaded the rest of the team and effected a practice change. 😄

@gguuss: it remains the case that this issue is fixed-in-source-and-will-be-fixed-in-the-`1.1.0`-release; again please verify when a `1.1.0` release candidate becomes available real soon now.

**Comment by gguuss** [comment]
@nathanielmanistaatgoogle Thanks for the heads up, I'll try and check it again once the new version releases.
