### ISSUE TITLE
node: enum values come in as strings

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#8726]
Due to this line:

https://github.com/grpc/grpc/blob/master/src/node/src/common.js#L69

`toRaw` converts enums to strings as well: https://github.com/dcodeIO/ProtoBuf.js/issues/97

This is a bit annoying as strings are not efficient at all on the wire and are harder to compare than ints. I would prefer to have the protos as integers.

**Comment by murgatroid99** [comment]
Well, it looks like you're going to fix this in #9004, assuming that works out.

**Comment by murgatroid99** [comment]
There are now options for changing this behavior in the new package `@grpc/proto-loader`.
