### ISSUE TITLE
node: add option to skip data deserialization

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#8727]
I would like to be able to optionally skip the deserialize step in the 'data' event from a streaming call and in the callbacks from non-streaming calls. Instead, a binary buffer would be given. This is useful if the server is not actually doing anything with the data, but is just passing it onward down the wire (like in a proxy).

Data validation can be deferred to downstream.

**Comment by murgatroid99** [comment]
You can do that by defining a generic service, and then using `grpc.makeClientConstructor` and `server.addService`. Those both accept service objects of the following form:

```js
{
  methodName: {
   path: '/ServiceName/MethodName',
   requestStream: true, //or false
   responseStream: true, //or false
   requestSerialize: requestSerializeFunction,
   requestDeserialize: requestDeserializeFunction,
   responseSerialize: responseSerializeFunction,
   responseDeserialize: responseDeserializeFunction
  },
  ...
}
```

In this case, `methodName` is the name you would use to access the method on the client, and the `path` value is used on the wire.

For your use case, you would set the serialize and deserialize functions to the identity function, which will just give you the raw buffer.

**Comment by paralin** [comment]
@murgatroid99 Thanks. This seems like a good middle ground. I'll do some work on this tonight and write here if anything comes up.

**Comment by paralin** [comment]
Some clarification: `requestType` and `responseType` should also be in that object.

**Comment by paralin** [comment]
Implemented, thanks!

**Comment by murgatroid99** [comment]
Regarding your clarification: `requestType` and `responseType` are not required. Existing code provides them primarily because they can be useful for debugging

**Comment by paralin** [comment]
Heh, alright. Thanks for the correction.
