### ISSUE TITLE
cmake compile error

### ISSUE THREAD

**Issue by jefby** [grpc/grpc#8729]
Hi, I want to use cmake to compile grpc, but this will failed in aaefa958d796e8f9ec1fe48df61ca0fd9425be48 

```
mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCMAKE_INSTALL_PREFIX=${PREFIX} .. -DCMAKE_CXX_FLAGS="-g -O2 -fPIC" -DCMAKE_C_FLAGS="-g -O2 -fPIC" && make -j24
```

error log

>CMake Error: install(EXPORT "gRPCTargets" ...) includes target "grpc" which requires target "ssl" that is not in the export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "grpc" which requires target "zlibstatic" that is not in the export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "grpc_cronet" which requires target "ssl" that is not in the export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "grpc++" which requires target "ssl" that is not in the export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "grpc++_cronet" which requires target "ssl" that is not in the export set.

**Comment by timotheecour** [comment]
I also can't use cmake to compile grpc

```
cmake -DCMAKE_INSTALL_PREFIX=/tmp/grpc/
make -j8
make install
```

fails

**Comment by mbrucher** [comment]
I have the same issue here :/
Deactivating ssl (by removing the boring ssl module) doesn't change the problem, although only the zlibstatic error remains. BAd sync between submodules and the root tree?

**Comment by dzenanz** [comment]
The same error happens in Windows when using `ninja` as generator with VS2015 compiler. Option `gRPC_INSTALL` needs to be enabled for this error to appear. Otherwise gRPC libs are not copied to install location, only zlib and protobuf.

**Comment by mbrucher** [comment]
Can someone from the core team have a look at this? I think we all followed the tutorial from the website (we have to build the library by hand), but it fails for no obvious reason.
Wrong CMake version/bad CMake usage? GCC version (I can't see why it would be a gcc version error)? bad dependencies?
