### ISSUE TITLE
iOS: FD shutdown causes handshake errors

### ISSUE THREAD

**Issue by rmartin7c** [grpc/grpc#8732]
We're experiencing "Security handshake failed" errors in an iOS ObjC gRPC client. It happens intermittently, but always either on initial app startup and connection to the gRPC server, or else after the app resumes from background. It seems that once the channel is successfully initiated, this won't happen until/unless it times out from inactivity and needs to be rebuilt.

> E1109 11:47:53.498008000 123145302917120 handshake.c:128] Security handshake failed: {"created":"@1478710073.497969000","description":"Handshake read failed","file":"/Users/rmartin/src/POM-Chewy-iOS/Pods/gRPC-Core/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1478710073.497965000","description":"FD shutdown","file":"/Users/rmartin/src/POM-Chewy-iOS/Pods/gRPC-Core/src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}

Sometimes the error will keep happening and affect more than one call in the sequence, but once one succeeds, they all succeed after that.

Per @jtattermusch we have been experimenting with increasing "grpc.initial_reconnect_backoff_ms" to a larger number than the default 1000ms. At 8000ms we're have not yet been able to reproduce the error, but we're going to put that build in the hands of a lot more testers and see what happens.

**Comment by muxi** [comment]
This week's greenness fixit session addressed the handshake problem that seems to be the same as this one. Could you please try again with master branch and let us know if it works?
