### ISSUE TITLE
Bazel BUILD rule grpc++_reflection is broken (invalid srcs input file reflection.proto)

### ISSUE THREAD

**Issue by pcj** [grpc/grpc#8736]
Commit 169c985f676f634c33318b9748086f25478ddd9f removed generated pb files from a number of build-related files and replaced it with the protobuf source file.  Unfortunately, the bazel build rule `cc_library` does not accept filetype `*.proto`, so this is invalid.

Offending line: https://github.com/grpc/grpc/blob/169c985f676f634c33318b9748086f25478ddd9f/BUILD#L1426

```sh
BUILD:1662:10: in srcs attribute of cc_library rule @com_github_grpc_grpc//:grpc++_reflection: file '@com_github_grpc_grpc//:src/proto/grpc/reflection/v1alpha/reflection.proto' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .hxx, .inc, .S, .s, .asm, .a, .pic.a, .lo, .pic.lo, .so, .dylib, .dll, .o or .pic.o)
```

Perhaps there's something I'm missing related to an internal google procedure.  If not, I can PR a fix.

**Comment by kangjoni76** [comment]
this is same happen if you build from source using cmake based project. I just simply commenting grpc++_reflection target build in cmake template and the build will work fine. If you intent try to build command line grpc_cli , then you need manually generate from invoking  protoc compiler right at folder src/proto/grpc/reflection/v1alpha for either protobuf interface class and generic grpc base class interface in c++ target.

**Comment by pcj** [comment]
The utility of the BUILD file is so that it can be used as an external workspace dependency in another bazel repository, for example:

```python
git_repository(
   name = "com_github_grpc_grpc",
   remote = "https://github.com/grpc/grpc.git",
   init_submodules = True,
   commit = "83f8bc5b807b717c2eb018fcb0874444843e25fb",
)
```

So, manually tweaking is not an acceptable workaround.  The file just needs to be fixed.
