### ISSUE TITLE
Python Quickstart fails at last step

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#8738]
The output message says:
```
Greeter client received: Hello, you!
Traceback (most recent call last):
  File "greeter_client.py", line 48, in <module>
    run()
  File "greeter_client.py", line 44, in run
    response = stub.SayHelloAgain(helloworld_pb2.HelloRequest(name='you'))
AttributeError: 'GreeterStub' object has no attribute 'SayHelloAgain'
```

**Comment by nathanielmanistaatgoogle** [comment]
How certain are you that you completed all the steps, in particular [_Update a gRPC Service_](http://www.grpc.io/docs/quickstart/python.html#update-a-grpc-service) and _[Generate gRPC Code](http://www.grpc.io/docs/quickstart/python.html#generate-grpc-code)_?

**Comment by muxi** [comment]
Certain.

**Comment by muxi** [comment]
And I think the problem is:
```
$ python -m grpc.tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/route_guide.proto
```
The last param should be helloworld.proto

This is on http://www.grpc.io/docs/quickstart/python.html

**Comment by nathanielmanistaatgoogle** [comment]
Looks like the problem was introduced in [this commit](https://github.com/grpc/grpc.github.io/commit/a76bd39060551789eafadf979df90df843a08c98). @markmandel, would you mind making the fix?

**Comment by markmandel** [comment]
Apologies for the confusion, and done. @nathanielmanistaatgoogle please review at your earliest convenience.

**Comment by nathanielmanistaatgoogle** [comment]
[Closing](https://github.com/grpc/grpc.github.io/pull/408) [as](https://github.com/grpc/grpc.github.io/pull/410) [this](https://github.com/grpc/grpc.github.io/pull/417) [was](https://github.com/grpc/grpc.github.io/pull/419) [fixed](https://github.com/grpc/grpc.github.io/pull/421) [several](https://github.com/grpc/grpc.github.io/pull/422) [times](https://github.com/grpc/grpc.github.io/pull/423) [over](https://github.com/grpc/grpc.github.io/pull/424).
