### ISSUE TITLE
Build failure because third_party/zlib references system wide zlib when building examples

### ISSUE THREAD

**Issue by aurelienrb** [grpc/grpc#8739]
Hello again :)

When writing a script to [automate the build of gRPC](https://github.com/aurelienrb/build-grpc) via Travis-CI, I discovered that cmake references the **system wide zlib** to build **third_party/zlib** examples rather than the lib itlself. Here's how to reproduce the issue:
```
sudo apt-get remove zlib1g-dev
git clone -b v1.0.1 --depth 1 --recursive https://github.com/grpc/grpc.git
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug ../grpc
make -j 4
```

```
Scanning dependencies of target minigzip
[ 46%] Building C object third_party/zlib/CMakeFiles/minigzip.dir/test/minigzip.o
/home/aurelien/test/grpc/third_party/zlib/test/minigzip.c:18:18: fatal error: zlib.h: No such file or directory
compilation terminated.
third_party/zlib/CMakeFiles/minigzip.dir/build.make:62: recipe for target 'third_party/zlib/CMakeFiles/minigzip.dir/test/minigzip.o' failed
```

If the system wide version of zlib is the same than third_party/zlib (1.2.8), then it's fine. Otherwise (like on Travis) we get an error.

For some reasons, it works fine when calling cmake directly on third_party/zlib, but it fails when invoking it from grpc/CMakeFiles.txt.

As I failed to force the use of third_party/zlib rather than the system wide one, I fixed the issue by removing the last lines of third_party/zlib/CMakeFiles.txt that want to build the examples.

**Comment by osechet** [comment]
The problem is due to an `include_directories()` call in the zlib's `CMakeLists.txt`. It does:
```
include_directories(${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_SOURCE_DIR})
```
When building zlib alone, we get:
```
-I/path/to/build-zlib -I/path/to/grpc/third_party/zlib
```
But when building grpc, it gives:
```
-I/path/to/build-grpc/third_party/zlib -I/path/to/grpc
```

Thus it cannot find the `zlib.h` file.

To fix the issue, the `include_directories` should be changed to:
```
include_directories(${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
```

This issue is described in madler/zlib#218.
