### ISSUE TITLE
cross compile issue2

### ISSUE THREAD

**Issue by enjoydiy** [grpc/grpc#8754]
`protoc -Ithird_party/protobuf/src -I. --cpp_out=/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens src/proto/grpc/reflection/v1alpha/reflection.proto
mkdir -p `dirname /home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc`
protoc -Ithird_party/protobuf/src -I. --grpc_out=/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin src/proto/grpc/reflection/v1alpha/reflection.proto
mkdir -p `dirname /home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.o`
/home/wzj/openwrt/sdk_x1000/toolchain/bin/mips-linux-gnu-g++ -Ithird_party/protobuf/src -Ithird_party/googletest/include -Ithird_party/boringssl/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -O2 -fPIC -I. -Iinclude -I/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens -DNDEBUG -DINSTALL_PREFIX=\"/home/wzj/openwrt/sdk_x1000/sys_root\"   -std=c++11   -MMD -MF /home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.dep -c -o /home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.o src/cpp/ext/proto_server_reflection.cc
In file included from ./src/cpp/ext/proto_server_reflection.h:41:0,
                 from src/cpp/ext/proto_server_reflection.cc:39:
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:62:24: error: variable 'grpc::reflection::v1alpha::ServerReflection grpc::reflection::v1alpha::GRPC_FINAL' has initializer but incomplete type
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected primary-expression before 'public'
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected '}' before 'public'
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected ',' or ';' before 'public'
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
make: *** [/home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.o] Error 1
wzj@mylab:~/openwrt/sdk_x1000/depends$ `

**Comment by vjpai** [comment]
Hi, can I ask you rebuild and reinstall the protoc plugins? It looks like you're using old protoc plugins (that say things like GRPC_FINAL) which we've since deprecated at master. Please let me know what happens after that.

**Comment by enjoydiy** [comment]
@vjpai I have pulled the new source. compile again show the error:

> /home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:62:24: error: variable 'grpc::reflection::v1alpha::ServerReflection grpc::reflection::v1alpha::GRPC_FINAL' has initializer but incomplete type
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected primary-expression before 'public'
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected '}' before 'public'
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected ',' or ';' before 'public'
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
make: *** [/home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.o] Error 1

**Comment by enjoydiy** [comment]
@vjpai 
I check the source files. And add the codes to the config.h:
`#define GRPC_OVERRIDE override
#define GRPC_FINAL final`
Thus, compile successfully. The codes are still there on 1.0.1, Why do the newest not contains ?

**Comment by vjpai** [comment]
We have switched to true C++11. The issue in your case is that your
installed protoc plugins are outdated relative to your gRPC version. I
would recommend re-installing gRPC from source (rather than just
rebuilding). I am going to leave this open to decide if we should consider
continuing to support those older macros for users that might have older
versions of the plugins installed.

**Comment by enjoydiy** [comment]
@vjpai , Thank you, I have tried reinstalled. Finally, successfully cross compile the grpc. The issue can be closed.

**Comment by thevamad** [comment]
@enjoydiy: Is it possible to build only the CPP flavor of GRPC ? I'm also trying to cross compile for OpenWRT. Do you have a makefile you can share with me ? Thanks!
