### ISSUE TITLE
Support of Dart language

### ISSUE THREAD

**Issue by olostan** [grpc/grpc#8757]
There is an issue in Dart SDK https://github.com/dart-lang/sdk/issues/22655 

But may be gRPC team can help to add gRPC support

**Comment by mit-mit** [comment]
@jakobr-google is making good progress on this over in https://github.com/dart-lang/grpc-dart

**Comment by hsaliak** [comment]
As it currently stands, we do not have plans of introducing dart support in the grpc/ repo. As such the ongoing work in the dart repo is the one to follow for this.Given that progress is made elsewhere, I am going to close this issue.
