### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by enjoydiy** [grpc/grpc#8762]
> /home/wzj/openwrt/sdk_x1000/toolchain/bin/mips-linux-gnu-g++ -Ithird_party/protobuf/src -Ithird_party/googletest/include -Ithird_party/boringssl/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -O2 -fPIC -I. -Iinclude -I/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\"   -std=c++11   -MMD -MF /home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.dep -c -o /home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.o src/cpp/ext/proto_server_reflection.cc
In file included from ./src/cpp/ext/proto_server_reflection.h:41:0,
                 from src/cpp/ext/proto_server_reflection.cc:39:
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:62:24: error: variable 'grpc::reflection::v1alpha::ServerReflection grpc::reflection::v1alpha::GRPC_FINAL' has initializer but incomplete type
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected primary-expression before 'public'
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected '}' before 'public'
/home/wzj/openwrt/sdk_x1000/depends/grpcgit/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h:63:2: error: expected ',' or ';' before 'public'
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
src/cpp/ext/proto_server_reflection.cc:227:1: error: expected '}' at end of input
make: *** [/home/wzj/openwrt/sdk_x1000/depends/grpcgit/objs/opt/src/cpp/ext/proto_server_reflection.o] Error 1

**Comment by soltanmm-google** [comment]
We've recently updated the code to use C++11's `final` as opposed to `GRPC_FINAL`. Do all of your versions match (e.g. generated code to runtime code)?

**Comment by enjoydiy** [comment]
I cross compile the grpc target on mips32 cpu hosted by ubuntu 14.04 64bit.  The g++ version is 4.7.2. What do you mean by "versions match" ?

**Comment by vjpai** [comment]
Was this resolved by fixing #8754 ? (re-installing grpc to avoid a conflict between protoc plugins and grpc headers)
