### ISSUE TITLE
Error by create secure_channel

### ISSUE THREAD

**Issue by jaeseunglee** [grpc/grpc#8763]
Hi,
grpc was installed using pip. I tried to use it and I got an error. I looked for errors, but I could not find a solution.
The environment through uname is as follows.
```python
uname -s -> Linux
uname -r -> 3.10.65
uname -m -> aarch64
```

code
```python
import grpc

creds = grpc.ssl_channel_credentials(open('roots.pem').read())
channel = grpc.secure_channel('myservice.example.com:443', creds)
```
log
```python
24061 ssl_transport_security.c:655] Could not set ephemeral ECDH key.
24061 security_connector.c:774]   Handshaker factory creation failed with TSI_INTERNAL_ERROR.
```

**Comment by soltanmm-google** [comment]
@jaeseunglee Do you see more errors than just those lines? What's the whole output?
@jboeuf Is this a problem?

**Comment by jboeuf** [comment]
Looks like the call to openssl/boringssl fails. Which distrib are you using?
@soltanmm-google do you know which version of open/boringSSL we're linking with when installing the package with pip?

**Comment by jaeseunglee** [comment]
@soltanmm-google That line is all. However, I tried with an address other than that address. The address is 'speech.googleapis.com:443'

@jboeuf Used Debian. However, use chroot in an environment where packages are manually built. Is there a missing package called openssl / boringssl? I installed openssl and pyopenssl.

**Comment by soltanmm-google** [comment]
@jboeuf Whatever version of BoringSSL is under `$GIT_REPO/third_party/boringssl` when we compile the distributions on Jenkins is statically linked in.

**Comment by jboeuf** [comment]
@jaeseunglee 
BoringSSL is actually linked statically as indicated by @soltanmm-google so the version of open/boringSSL that you have on your system does not matter. 

This is the first time I see this error and I'm not quite sure what the error is here. We could try to add some debug logging (e.g. call `log_ssl_error_stack` after the failure in `ssl_transport_security.c`).

@jaeseunglee, is it easy for you to compile from source and see if you get the same behavior? If so, I can send you a patch that will include more debugging info.

**Comment by jaeseunglee** [comment]
@jboeuf It is a difficult environment to compile. Because I installed it using pip.
I installed gcloud using pip.  The output at the time of installation is as follows.

root@pst-2593-234:/# pip install gcloud
Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454kB)
    100% |################################| 460kB 488kB/s 
Collecting httplib2>=0.9.1 (from gcloud)
  Downloading httplib2-0.9.2.zip (210kB)
    100% |################################| 215kB 639kB/s 
Collecting googleapis-common-protos (from gcloud)
  Downloading googleapis-common-protos-1.5.0.tar.gz
Collecting oauth2client>=2.0.1 (from gcloud)
  Downloading oauth2client-4.0.0-py2.py3-none-any.whl (184kB)
    100% |################################| 194kB 620kB/s 
Collecting protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud)
  Downloading protobuf-3.1.0.post1-py2.py3-none-any.whl (347kB)
    100% |################################| 348kB 348kB/s 
Collecting six (from gcloud)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting grpcio>=1.0rc1 (from gcloud)
  Downloading grpcio-1.0.1.tar.gz (5.2MB)
    100% |################################| 5.2MB 33kB/s 
Collecting google-gax<0.13dev,>=0.12.3 (from gcloud)
  Downloading google-gax-0.12.5.tar.gz
Collecting gax-google-pubsub-v1<0.9dev,>=0.8.0 (from gcloud)
  Downloading gax-google-pubsub-v1-0.8.3.tar.gz
Collecting grpc-google-pubsub-v1<0.9dev,>=0.8.0 (from gcloud)
  Downloading grpc-google-pubsub-v1-0.8.1.tar.gz
Collecting gax-google-logging-v2<0.9dev,>=0.8.0 (from gcloud)
  Downloading gax-google-logging-v2-0.8.3.tar.gz
Collecting grpc-google-logging-v2<0.9dev,>=0.8.0 (from gcloud)
  Downloading grpc-google-logging-v2-0.8.1.tar.gz
Collecting pyasn1>=0.1.7 (from oauth2client>=2.0.1->gcloud)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=2.0.1->gcloud)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=2.0.1->gcloud)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |################################| 51kB 1.7MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf!=3.0.0.b2.post1,>=3.0.0b2->gcloud)
Collecting enum34>=1.0.4 (from grpcio>=1.0rc1->gcloud)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting futures>=2.2.0 (from grpcio>=1.0rc1->gcloud)
  Downloading futures-3.0.5-py2-none-any.whl
Collecting future>=0.15.2 (from google-gax<0.13dev,>=0.12.3->gcloud)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |################################| 829kB 286kB/s 
Collecting ply==3.8 (from google-gax<0.13dev,>=0.12.3->gcloud)
  Downloading ply-3.8.tar.gz (157kB)
    100% |################################| 163kB 1.0MB/s 
Building wheels for collected packages: gcloud, httplib2, googleapis-common-protos, grpcio, google-gax, gax-google-pubsub-v1, grpc-google-pubsub-v1, gax-google-logging-v2, grpc-google-logging-v2, future, ply
  Running setup.py bdist_wheel for gcloud ... done
  Stored in directory: /root/.cache/pip/wheels/b4/fa/9b/4ff892d4e86379687c4f8eecec35d1af156608a8a8852b00df
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /root/.cache/pip/wheels/c7/67/60/e0be8ccfc1e08f8ff1f50d99ea5378e204580ea77b0169fb55
  Running setup.py bdist_wheel for googleapis-common-protos ... done
  Stored in directory: /root/.cache/pip/wheels/77/81/54/a4dddb37bebde387e463d3f53ef347be1c2259ca3f37750858
  Running setup.py bdist_wheel for grpcio ... done
  Stored in directory: /root/.cache/pip/wheels/35/25/0d/f473989f922ed7074c1e1cc19f06077a3eca4abbd53ac365b2
  Running setup.py bdist_wheel for google-gax ... done
  Stored in directory: /root/.cache/pip/wheels/f5/ce/96/7e1afb870a0de69d037749d835c9aacc32601961f96dbf02d3
  Running setup.py bdist_wheel for gax-google-pubsub-v1 ... done
  Stored in directory: /root/.cache/pip/wheels/59/c1/65/e72a7764a997dc8806a7a02e78b62d51886769dfb3d5e96307
  Running setup.py bdist_wheel for grpc-google-pubsub-v1 ... done
  Stored in directory: /root/.cache/pip/wheels/87/db/e8/29f82f7a2b98301b6085d0122b9c2cc7794133fdf30bd9e924
  Running setup.py bdist_wheel for gax-google-logging-v2 ... done
  Stored in directory: /root/.cache/pip/wheels/96/6b/ea/10e3cda68dba5249dfb84864f5fc1624d7ab6a846033957888
  Running setup.py bdist_wheel for grpc-google-logging-v2 ... done
  Stored in directory: /root/.cache/pip/wheels/53/f3/4a/dcfbde3116bf4825c9eb38b88b61b1981afb7d9fcdcbf321e6
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: /root/.cache/pip/wheels/6f/23/3c/7055bf8004cee3c7d06c46318014e0374539094c4e36246e9a
Successfully built gcloud httplib2 googleapis-common-protos grpcio google-gax gax-google-pubsub-v1 grpc-google-pubsub-v1 gax-google-logging-v2 grpc-google-logging-v2 future ply
Installing collected packages: httplib2, six, protobuf, googleapis-common-protos, pyasn1, pyasn1-modules, rsa, oauth2client, enum34, futures, grpcio, future, ply, google-gax, grpc-google-pubsub-v1, gax-google-pubsub-v1, grpc-google-logging-v2, gax-google-logging-v2, gcloud
Successfully installed enum34-1.1.6 future-0.16.0 futures-3.0.5 gax-google-logging-v2-0.8.3 gax-google-pubsub-v1-0.8.3 gcloud-0.18.3 google-gax-0.12.5 googleapis-common-protos-1.5.0 grpc-google-logging-v2-0.8.1 grpc-google-pubsub-v1-0.8.1 grpcio-1.0.1 httplib2-0.9.2 oauth2client-4.0.0 ply-3.8 protobuf-3.1.0.post1 pyasn1-0.1.9 pyasn1-modules-0.0.8 rsa-3.4.2 six-1.10.0

Do I need to compile instead of installing using pip?

**Comment by jaeseunglee** [comment]
@jboeuf add some logging to ssl_transport_security.c, and compiled output

```
E1121 07:21:12.473892878   16238 ssl_transport_security.c:655] Could not set ephemeral ECDH key. context : ??x
E1121 07:21:12.474165164   16238 ssl_transport_security.c:656] Could not set ephemeral ECDH key. ecdh : (null)
E1121 07:21:12.474372117   16238 security_connector.c:774]   Handshaker factory creation failed with TSI_INTERNAL_ERROR.
```
I want patch file. Can you send it to me?

**Comment by jaeseunglee** [comment]
@soltanmm-google @jboeuf 

I found an error while checking EC_POINT_is_on_curve in the EC_POINT_set_affine_coordinates_GFp function of the /grpc/third_party/boringssl/crypto/ec/ec.c file.

Why did not pass the EC_POINT_is_on_curve check?

**Comment by jaeseunglee** [comment]
@soltanmm-google  @jboeuf 
Is this something you can not fix? Please answer.

**Comment by jboeuf** [comment]
Just back from vacation. Thanks for the new logs. It looks like `EC_KEY_new_by_curve_name(NID_X9_62_prime256v1)` returns `NULL` and I have no idea why... This is the first time that such an error is reported to us and this code gets *a lot* of mileage...

Can you try to put the `log_ssl_error_stack` just after this line?
`EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);`

**Comment by jaeseunglee** [comment]
@jboeuf  Thank you for answer.
This is the result of adding log_ssl_error_stack
```python
E1129 06:42:46.512766419    9441 ssl_transport_security.c:425] error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE
E1129 06:42:46.512928166    9441 ssl_transport_security.c:425] error:0f00000f:elliptic curve routines:OPENSSL_internal:elliptic curve routines
E1129 06:42:46.513031788    9441 ssl_transport_security.c:425] error:0f00007b:elliptic curve routines:OPENSSL_internal:UNKNOWN_GROUP
```

**Comment by jboeuf** [comment]
Thanks... This is very strange and it looks like it's happening just for you :(.

What happens if you install the same pip in a classic linux environment (e.g. ubuntu 16.04)? Do you get the same error as well?

**Comment by jaeseunglee** [comment]
It is installed well in other environments.

But I have to minimize the capacity of Linux. So I installed a minimum of packages.

My guess is that the necessary libraries are missing. Please suggest which library to add.

**Comment by jboeuf** [comment]
I'm sorry, I really don't know how to help you. My only suggestion would be to create a simple C program that just does something like this (linked with boringssl) and run it in your environment. If that fails (as I expect it to), you should probably ask the boringssl/openssl mailing lists to help you understanding what's wrong.

```c
int main(void) {
  SSL_library_init();
  SSL_load_error_strings();
  OpenSSL_add_all_algorithms();
  EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
  if (ecdh == NULL) {
    unsigned long err;
    fprintf(stderr, "FAILED: \n");
    while ((err = ERR_get_error()) != 0) {
      char details[256];
      ERR_error_string_n((uint32_t)err, details, sizeof(details));
      fprintf(stderr, "%s\n", details);
    }
    return 1;
  }
  return 0;
}
```

**Comment by rshriram** [comment]
@jboeuf could you point me to the boringssl mailing list? I am having a similar issue on the Raspberry Pi 3, with 64-bit kernel.

**Comment by rradar** [comment]
Can confirm for error for **arm**64

Mono Version: 5.4.1.6 (latest stable)
OS Version: Debian 8.10, kernel 4.14.4-sunxi64 (arm64)

**Comment by alex-the-man** [comment]
We see this issue on mips64 as well.
