### ISSUE TITLE
Create an "interceptor" mechanism for GRPC Python

### ISSUE THREAD

**Issue by joeblubaugh** [grpc/grpc#8767]
We're building OpenTracing integrations for GRPC over at [grpc-opentracing](https://github.com/grpc-ecosystem/grpc-opentracing). After spending some time looking into how to do this in the Python client and server libs, I think that adding an Interceptor abstraction to the Python library would be the easiest way for various kinds of middleware to hook into GRPC.

This abstraction already exists in the Java and Go implementations (and may exist in other language implementations as well).

I was thinking of adding a new Channel class InterceptorChannel to grpc-opentracing that people could use to add tracers to their channel:

```(python)
tracer = # Some Tracer impl
channel = grpc.insecure_channel("[::]:5005")
intercepted = otgrpc.InterceptorChannel(channel, tracer)

# Create you stub ...
```

I realized then that this is almost exactly what the Java implementation does internally and it probably makes more sense to have a system like this in GRPC itself.

**Comment by nathanielmanistaatgoogle** [comment]
@joeblubaugh: [`grpc.Channel` is an interface that may be implemented by anyone](https://github.com/grpc/grpc/blob/8a4ac886e4da6b278f30115431f090661bd1576b/src/python/grpcio/grpc/__init__.py#L616); what's stopping you from writing the code in your aspirational code sample?

**Comment by joeblubaugh** [comment]
@nathanielmanistaatgoogle right - there's nothing that would prevent writing a `grpc.Channel` implementation for the client, or a similar wrapper for the server. 

However, whatever implementation we write for OpenTracing may not play well with a model that some other middleware author creates for another system. In the Java library, it's handy to have an abstraction that's blessed by GRPC. As a GRPC user, you can combine arbitrary groups of Interceptors without worrying about whether their models for interacting with Channels are compatible.

```java
{
  Channel channel = ...
  ClientInterceptor openTracingInterceptor = ...
  ClientInterceptor someOtherInterceptor = ...
  Channel finalChannel = ChannelInterceptors.intercept(channel, openTracingInterceptor, someOtherInterceptor);
}
```
[Util Class](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ClientInterceptors.java)

I'm proposing that GRPC python support a similar abstraction - probably separate ones for client and server - that middleware authors can implement.

**Comment by bensigelman** [comment]
@nathanielmanistaatgoogle this has come up a bunch of times now w.r.t. OpenTracing... another example (one of many, some of which are not on github): https://github.com/grpc-ecosystem/grpc-opentracing/issues/11#issuecomment-272371195

I mean, from http://www.grpc.io/about/ itself:

> **Core Features that make it awesome:**
>
> - Idiomatic client libraries in 10 languages
> - Highly efficient on wire and with a simple service definition framework
> - Bi-directional streaming with http/2 based transport
> - Pluggable auth, tracing, load balancing and health checking

It doesn't seem like the "tracing" part is pluggable at all right now, which is a problem as I keep on recommending GRPC to people because it has pluggable tracing. :)  Which is true in Go and Java, of course.

**Comment by bensigelman** [comment]
Also, I propose we rename this issue so I don't have to file another one about Javascript et al: `s/GRPC python/all supported GRPC languages/`

**Comment by rnburn** [comment]
I'm looking into adding this interceptor functionality. I'm only focusing on the client-side, Python interceptors for now. I'm planing to add an InterceptorChannel class similar to what's in the [Java version](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ClientInterceptors.java#L107). For each of the member functions of the channel that return a callable object (i.e. unary_unary, unary_stream, etc), I'm going to return a decorated version of original callable. It would look something like this:
```python
class InterceptorChannel(grpc.Channel):
  def __init__(self, channel, interceptor):
    self.channel = channel
    self.interceptor = interceptor

  def unary_unary(self, *args, **kwargs):
    base_callable = self.channel.unary_unary(*args, **kwargs)
    return InterceptorUnaryUnaryMultiCallable(base_callable, self.interceptor)
...
```
The decorated callables would then call the interceptor with an invoker argument that forwards to the original callable.
```python
class InterceptorUnaryUnaryMultiCallable(grpc.UnaryUnaryMultiCallable):
  def __init__(self, base_callable, interceptor):
    self.base_callable = base_callable
    self.interceptor = interceptor

  def __call__(self, request, timeout=None, metadata=None, credentials=None):
    def invoker(request, metadata):
      return self.base_callable(request, metadata, invoker)
    return self.interceptor(request, metadata, invoker)
...
```
And you could implement tracing or other such functionality with interceptors like
```python
def TracerInterceptor(object):
  def __init__(self, tracer):
    self.tracer = tracer

  def __call__(self, request, metadata, invoker):
    # start a new span
    # inject the span's context into metadata
    response = invoker(request, metadata)
    # finish the span
    return response
```
Does this seem like a reasonable approach? Or anything you think I should be doing differently?

**Comment by joeblubaugh** [comment]
I don't quite understand this syntax in the decorated callable definition:
```
class InterceptorUnaryUnaryMultiCallable(grpc.UnaryUnaryMultiCallable):
  def __init__(self, base_callable, interceptor):
    self.base_callable = base_callable
    self.interceptor = interceptor

  def __call__(self, request, timeout=None, metadata=None, credentials=None):
    return self.interceptor(request, metadata, invoker)
```

Should the invoker definition look like this instead?
```
def invoker(request, metadata):
  return self.base_callable(request, metadata)
```


I might also suggest reordering the syntax for InterceptorChannel construction, or creating a utility method for interceptor channels. The interceptor chaining syntax in your example would look like
```
channel = grpc.insecure_channel("[::]:5005")
myChannel = InterceptorChannel(
    InterceptorChannel(
        InterceptorChannel(channel, LastInterceptor()),
        SecondInterceptor()),
    FirstInterceptor())
```
but if we reorder the constructor:
```
myChannel = InterceptorChannel(FirstInterceptor(), 
        InterceptorChannel(SecondInterceptor(), 
                InterceptorChannel(ThirdInterceptor(), channel)))
```

I think that this would be really helpful for Python client users overall. Thank you!

**Comment by rnburn** [comment]
@joeblubaugh I made a mistake in the invoker definition. Thanks for point that out. I just updated it. I was planning on exposing the functionality via something like an intercept_channel function that does the chaining for you like the [Java version](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ClientInterceptors.java#L86). I put the channel argument first because that's what's done in the [Java channel](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ClientInterceptors.java#L111), but I can change that. It probably won't matter so much with the utility function.

**Comment by joeblubaugh** [comment]
I totally agree. If there's a util function where the chaining definition
is ergonomic it won't make much of a difference. Overall I like the look of
it.

**Comment by rnburn** [comment]
I've made some progress towards implementing the interceptor [functionality](https://github.com/rnburn/grpc-opentracing/tree/master/py/grpcext). I set up interfaces that can be used along with the functions [intercept_channel](https://github.com/rnburn/grpc-opentracing/blob/master/py/grpcext/__init__.py#L65) and [intercept_server](https://github.com/rnburn/grpc-opentracing/blob/master/py/grpcext/__init__.py#L152) to call custom code when either unary or stream RPCs are invoked. I tried to match the Go interceptors as much as I could. Here's a side-by-side comparison:

| Type  | Side |                |       |
| ------ | ------ | -------- |----|
| Unary  | Client | [Python](https://github.com/rnburn/grpc-opentracing/blob/master/py/grpcext/__init__.py#L12)  | [Go](https://github.com/grpc/grpc-go/blob/master/interceptor.go#L46) |
| Stream  | Client | [Python](https://github.com/rnburn/grpc-opentracing/blob/master/py/grpcext/__init__.py#L47)  | [Go](https://github.com/grpc/grpc-go/blob/master/interceptor.go#L54)  |
| Unary  | Server | [Python](https://github.com/rnburn/grpc-opentracing/blob/master/py/grpcext/__init__.py#L111)  | [Go](https://github.com/grpc/grpc-go/blob/master/interceptor.go#L73) |
| Stream  | Server | [Python](https://github.com/rnburn/grpc-opentracing/blob/master/py/grpcext/__init__.py#L135)  | [Go](https://github.com/grpc/grpc-go/blob/master/interceptor.go#L90)  |

And this is an example of how it can be used to add tracing information on the [client-side](https://github.com/rnburn/grpc-opentracing/blob/master/py/otgrpc/_client.py#L27) and the [server-side](https://github.com/rnburn/grpc-opentracing/blob/master/py/otgrpc/_server.py#L49). Let me know if you have any feedback.

**Comment by tedsuo** [comment]
@nathanielmanistaatgoogle does this approach look acceptable to you? Should we go ahead and make a PR?

**Comment by nathanielmanistaatgoogle** [comment]
My apologies for the delay on this; will take a look at [the pull request](https://github.com/grpc/grpc/pull/10256) after it gets its "cla: yes" label.

Thank you for recognizing that we'd want to add interceptors to Python in a way that's consistent with Go. Have you also looked at Java and whichever other gRPC languages have interceptors (C++ maybe?)? Maintaining as much conceptual consistency across the languages has been and remains a priority for the gRPC project.

**Comment by rnburn** [comment]
@nathanielmanistaatgoogle The CLA should be in order now.

I don't believe C++ has interceptors ([#9035](https://github.com/grpc/grpc/issues/9035)), but I did look at the Java interceptors also. There are some differences in that Java interceptors allows you to return listener objects [ClientCall](http://www.grpc.io/grpc-java/javadoc/io/grpc/ClientCall.html) and [ServerCall.Listener](http://www.grpc.io/grpc-java/javadoc/io/grpc/ServerCall.Listener.html). It wasn't clear to me how those would fit into the Python API.

And some difference arise from how the streaming RPCs are implemented. For example, Go stream [interceptors](https://godoc.org/google.golang.org/grpc#StreamClientInterceptor) return an [interface](https://godoc.org/google.golang.org/grpc#ClientStream) that has calls you can override to intercept the requests and responses; whereas since Python streaming is built on iterators and generators, to intercept requests you can decorate the request_iterator [passed in](https://github.com/rnburn/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L406) or to intercept responses you can decorate the returned generator.

**Comment by rnburn** [comment]
I also found this [proposal](https://github.com/drobertduke/proposal/blob/522370e2412e6e1df32c620fe4a1797d2dbe17e6/NODEJS-CLIENT-INTERCEPTORS.md) that was recently written to add interceptors to JavaScript. It, instead, uses more of an event-driven approach and implements interception at the Call::start_batch method. I imagine something similar could be done in Python. Let me know if you want me to pursue an alternative design more aligned with that approach.

**Comment by rnburn** [comment]
Hey @nathanielmanistaatgoogle, any feedback for the Python interceptors?

**Comment by tedsuo** [comment]
@nathanielmanistaatgoogle checking in on the status of this PR.

Since it's holding up python support for gRPC OpenTracing, we are baking the interceptors in as a submodule for the time being: https://github.com/grpc-ecosystem/grpc-opentracing/pull/32

**Comment by evanj** [comment]
I just "borrowed" the server interceptor from grpc-ecosystem/grpc-opentracing#32 and it worked like a charm. Looking forward to something like this landing in grpc proper.

**Comment by amitsaha** [comment]
@rnburn @tedsuo thanks for this! Like @evanj I dropped this in, and it just worked. 

I had a query regarding the interceptor implementation. The `intercept_unary()` method takes in a `request` object as the first argument, but the `intercept_stream()` doesn't. Looking at `grpcext/_intercetor.py`, i can see that the `handler()` function in all cases does have access to the outer `request` object in `adaptation()`. Why aren't we using this object in case of `intercept_unary()` as well?

**Comment by mehrdada** [comment]
Please take a look at the related gRFC https://github.com/grpc/proposal/pull/39 and its implementation https://github.com/grpc/grpc/pull/12778.

**Comment by mehrdada** [comment]
Fixed by https://github.com/grpc/grpc/pull/13722

**Comment by aamitdb** [comment]
@mehrdada is there a process to promote these APIs from experimental to stable? I'd like to start using the interceptor API and can deal with the API details changing, but I'd prefer that the overall concept didn't disappear from python. Both the client and server ones are marked as experimental here.

**Comment by mehrdada** [comment]
@aamitdb The intent here is to let us have some design flexibility if some minor, but not completely backward-compatible API change (mostly behavior change) occurs for two or three more releases (I don't know about Go and Java, as they have had interceptors for a long time--I'd file an issue requesting stabilization in their respective issue trackers), but it is highly unlikely that they will go away. As long as you can keep up with the future changes, you should be fine relying on them (I recommend pinning your dependencies or at least keeping a close eye on the release candidates if you do so though).
