### ISSUE TITLE
Using empty_pb2 and Empty field within proto buffer causes serializing exception to be thrown

### ISSUE THREAD

**Issue by jolac78** [grpc/grpc#8769]
I was previously using the Empty field in the proto file along with the empty_pb2 module for passing around Empty fields.  This was previously working and since I have upgraded grpcio, grpcio-tools, and protobuf I haven't been able to get this to work again.  I keep getting this SerializeToString Error.  Perhaps something else in my env changed but I can't for the life of me figure out why this is suddently failing.  I modified the helloworld example from the website to replicate the issue.  If this is something in my environment, please advise on how to fix it.

I am running on windows 8.1 Pro

protobuf==3.1.0.post1
grpcio==1.0.1
grpcio-tools==1.0.1

[helloworld.zip](https://github.com/grpc/grpc/files/595694/helloworld.zip)

C:\Users\jsmith\Desktop\sandbox\python\grpc\examples\python\helloworld>python greeter_client.py
ERROR:root:Exception serializing message!
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\grpc\_common.py", line 117, in _transform
    return transformer(message)
TypeError: unbound method SerializeToString() must be called with Empty instance as first argument (got Empty instance instea
Traceback (most recent call last):
  File "greeter_client.py", line 49, in <module>
    run()
  File "greeter_client.py", line 44, in run
    response = stub.SayHello(e)#helloworld_pb2.HelloRequest(name='you'))
  File "C:\Python27\lib\site-packages\grpc\_channel.py", line 480, in __call__
    state, deadline, = self._blocking(request, timeout, metadata, credentials)
  File "C:\Python27\lib\site-packages\grpc\_channel.py", line 468, in _blocking
    raise rendezvous
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, Exception serializing request!)>

**Comment by soltanmm-google** [comment]
The long and short of it is that you're using the wrong `Empty`, and Python isn't telling you that what it actually expects is `helloworld_pb2.Empty`, not `empty_pb2.Empty`, because Python is silly like that.

**Comment by jolac78** [comment]
Excellent!  Thank you!
