### ISSUE TITLE
Update example protos to match proto3 style guide

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc#877]
We've already fixed this on the Java side.  See:

https://github.com/grpc/grpc-java/pull/149
https://github.com/grpc/grpc-java/pull/151

**Comment by nmittler** [comment]
FYI these changes were made after discussions with @wora (Hong)

**Comment by nicolasnoble** [comment]
This is documentation, and needs to be ready for beta.

**Comment by yang-g** [comment]
Our example protos in grpc-common are using proto3, though we do have
proto2 proto files under grpc/test/.
I think we can close this now?

**Comment by yang-g** [comment]
For interop protos, some wrapped languages have their own copies of files with proto2 syntax since the proto3 support is not there yet. I will file separate issues to resolve some of those.
