### ISSUE TITLE
Move to C++11 and outdated protoc plugins

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8772]
So issue #8754 (which I've closed since that reporter is now ok) brings up the issue that people with protoc plugins installed before #8602 but more recent gRPC headers are in a pickle - namely that the current headers no longer recognize GRPC_OVERRIDE and GRPC_FINAL generated by the old plugins. The solution is to fully reinstall gRPC, which will automatically reset the plugins. Is there any desire to allow users to keep their outdated protoc plugins? If so, we should add those macros back to our headers but keep in mind that they are deprecated so that we never generate any new code that uses them. In my view, we should not do this as it leaves scope for error, and the better option is to just tell users to reinstall the plugins if they update gRPC. We should either fix this for 1.1 or decide that the current behavior is WAI and leave it alone. I vote for the latter, but let's see what the electoral college decides.

**Comment by soltanmm-google** [comment]
The power of semver compels you! The power of semver compels you!

... etc.

**Comment by vjpai** [comment]
But this is hairy, isn't it? By semver we're compelled to keep it until 2.0, but the workaround is trivial and this only affects people that have a mismatched set of plugins and headers, which I didn't even think was possible under normal circumstances (those are installed together, AFAIK)

**Comment by vjpai** [comment]
I'm calling this a real issue since there may be people out there with pre-generated PB files that we need to support.
