### ISSUE TITLE
Make grpc build agnostic to the protobuf version

### ISSUE THREAD

**Issue by hillzeta** [grpc/grpc#8773]
Presently grpc does not build with protobuf 3.10 because the source tree already has headers precompiled with a different version of protobuf. Here is part of email conversation on the subject a month ago:

Nicolas Noble <notifications@github.com>
Oct 13

to google/protobuf, me, Mention 
So, the presence of pre-generated files into our repository is a mistake. We'll be discussing to replace this. That's the crux of the problem, really.

**Comment by hillzeta** [comment]
Protobuf now is at 3.20. Any plans to resolve this issue?

**Comment by nicolasnoble** [comment]
We've fixed this one a while back, I think.
