### ISSUE TITLE
grpc-1.0.1 Makefile simple issue breaks MSYS2 execution

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#8774]
The Makefile of grpc-1.0.1 executes protoc with argument:
```
--plugin=protoc-gen-grpc=$(BINDIR)/$(CONFIG)/grpc_cpp_plugin
```
However when used on Windows with MSYS2, the correct name of grpc_cpp_plugin is `grpc_cpp_plugin.exe`. Without the exe-suffix, the plugin fails. With the exe-suffix, everything works as expected. Would it be possible to add a target-specific suffix for Windows?

**Comment by jtattermusch** [comment]
Fixed in #9307.
