### ISSUE TITLE
Python server 4x slower than C++ async one?

### ISSUE THREAD

**Issue by abcdabcd987** [grpc/grpc#8780]
Hi, I ran two greeter server examples: one uses [python](https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_server.py), and the other uses [c++ async](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_server.cc). And I slightly modified the [c++ async client](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_client.cc) to say hello for 10000 times:

```cpp
// ...
  GreeterClient greeter(grpc::CreateChannel(
      "localhost:50051", grpc::InsecureChannelCredentials()));
  const int T = 10000;
  long st = gettime();  // calls gettimeofday(&ts,NULL), return ms
  std::string user("world");
  for (int i = 0; i < T; ++i) {
    greeter.SayHello(user);
  }
  long ed = gettime();
  long d = ed-st;
  printf("tested %d times\ntotal %ldms\naverage %.6fms\n", T, d, static_cast<double>(d) / T);
// ...
```

The c++ async server and client were compiled with `-O2`. I ran tests on macOS and Ubuntu 14.04, both with grpc 1.0. On macOS, grpc is installed using brew. On Ubuntu, grpc is installed from the source code. On both platform, the python binding is installed using pip. And here is the result:

OS | server | total time | average time per rpc
---|---|---|---
macOS | c++ async | 1202ms | 0.1202ms
macOS | python | 4445ms | 0.4445ms
Ubuntu | c++ async | 933ms | 0.0933ms
Ubuntu | python | 4340ms | 0.4340ms

It seems that python server is 4x slower than c++ async one. Is it really true, or just for me? Will this be fixed?

**Comment by soltanmm-google** [comment]
Oh, hey, cool, Python's *only* 4x slower than C++.

I'm going to assume that you were running this all locally and that there was no network variability. Then you have a loop going, wherein Python is going to increment reference counts, decrement reference counts, allocate, deallocate, hash-lookup, acquire/release the GIL, and error check, again and again and again (and that's all in the language runtime, outside anything gRPC can do without becoming an even thinner wrapper around the core and telling users to not implement their servers in pure Python), things that C++ as a language doesn't do without the developer's explicit instruction (and thus things that C++ devs can avoid). So, Python's going to be slower, and for idiomatic implementations of the same algorithm vanilla-Python will almost always (I'd even say 'always') be slower.

I can't specifically point at anything without running profiles, but it's unreasonable to expect Python implementations to be competitive performance-wise with tuned C/C++, even if it's only a thin-wrapper.
