### ISSUE TITLE
gRPC C++ faulting on OS X

### ISSUE THREAD

**Issue by tjac** [grpc/grpc#8794]
gRPC isn't functioning on OS X. The c++ examples in hello_world compile, but immediately fails upon execution with the following error:
> E1116 19:34:21.882897000 140735092297728 sync_posix.c:51] assertion failed: pthread_mutex_lock(mu) == 0
> Abort trap: 6

I did the following to compile gRPC and the example code on my mac using the Xcode command line tools:

1.  git clone -b v1.0.0 https://github.com/grpc/grpc
2.  cd grpc
3.  git submodule update --init
4.  cd src/proto/grpc/reflection/v1alpha
5.  protoc --cpp_out=. reflection.proto
6.  cp reflection.pb.h ../../../../../include/grpc++/ext
7.  cp reflection.pb.* ../../../../../src/cpp/ext
8.  make
9.  sudo make install
10.  cd ../../../../../examples/cpp/helloworld
11.  (fix Makefile to remove --as-needed args since Xcode doesn't recognize the arg)
12.  make

steps 1-3 and 8-9 are from the install.md file of gRPC. Steps 4-7 are the result of the latest version (v1.0.0) of gRPC having .proto file generated with a version of protoc earlier than the version that it generates as part of the submodule update (3.1.0). This had to be addressed when I compiled my code on linux as well and worked. To that point, the helloword examples run fine on Linux using the above steps.

For whats its worth, I'm running the latest version of Xcode. I'm a bit of a novice when it comes to Mac programming, but since its *nix under the hood in this case, I also assume that I'm doing the basic things right here. If i'm not feel free to tell me :)

**Comment by sab24** [comment]
This was fixed in a newer commit of grpc, but the current head is no longer working after 439440.

This worked for me:
git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
rm -r ./third_party/nanopb
git checkout f89a4a1
cd third_party
cd protobuf
git checkout master
cd ../..
make
su
make install
cd third_party/protobuf
make install
exit
cd examples/cpp/helloworld
make

**Comment by sab24** [comment]
This is a duplicate of #7830?

**Comment by tjac** [comment]
it is. sorry about that. thanks for the solution to get this working!
