### ISSUE TITLE
Tarball does not compile due to missing nanopb

### ISSUE THREAD

**Issue by sesse** [grpc/grpc#8802]
Hi,

Seemingly gRPC 1.0 from the tarball does not compile:

```
[C]       Compiling src/core/ext/lb_policy/grpclb/load_balancer_api.c
In file included from ./src/core/ext/lb_policy/grpclb/load_balancer_api.h:40:0,
                 from src/core/ext/lb_policy/grpclb/load_balancer_api.c:34:
./src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.h:38:35: fatal error: third_party/nanopb/pb.h: No such file or directory
 #include "third_party/nanopb/pb.h"
                                   ^
```

I assume this was supposed to come from a git submodule, but the released tarball seemingly does not include git submodules. Nor is it possible to install nanopb separately (like a distribution would probably want to do), due to the use of "third_party/nanopb" instead of just <pb.h>.

**Comment by nicolasnoble** [comment]
We did move nanopb into the repo instead of being a submodule.
