### ISSUE TITLE
@google-cloud/translate doesn't work on windows

### ISSUE THREAD

**Issue by siluri** [grpc/grpc#8805]
Have already open a issue with google translate, these have referred me to you.
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1809

after npm install --save @google-cloud/translate

->

node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@7.1.0 (no de-v51 ABI) (falling back to source compile with node-gyp)

....

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\XXXXX\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "--save" "@google-clou d/translate"
npm ERR! node v7.1.0
npm ERR! npm v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.1 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\XXXXX\npm-debug.log

**Comment by murgatroid99** [comment]
This seems to be similar to other reports we've received recently: we haven't yet published the precompiled native extension for Node 7, and it would be pretty difficult to compile it on Windows yourself. You should be able to get it to work simply by downgrading to Node 6.

Since we have now received a few complaints about this, I'll look into publishing Node 7 binaries for gRPC 1.0.1. Otherwise, they will definitely be in gRPC 1.0.2.

**Comment by murgatroid99** [comment]
Precompiled binaries for Node 7 on all platforms, including Windows, are now available with grpc@1.1.0. This exact error should no longer occur with that version.
