### ISSUE TITLE
PHP gRPC plugin not included on make

### ISSUE THREAD

**Issue by twoism** [grpc/grpc#8809]
According to the docs found [here](https://github.com/grpc/grpc/tree/master/src/php#php-protoc-plugin), the PHP gRPC plugin should be created in `bins/opt` after running `make` in the root of `grpc`. From what I can tell this does not seem to be the case.

```bash
$ ls bins/opt
grpc_cpp_plugin
grpc_csharp_plugin
grpc_node_plugin
grpc_objective_c_plugin
grpc_python_plugin
grpc_ruby_plugin
protobuf
```
I put together the following `Dockerfile` for the build process that I am using.

```Dockerfile
FROM ubuntu:trusty

ENV INSTALL wget \
  php5-cli \
  php5-dev \
  php-pear \
  git \
  python-pip \
  python-dev \
  build-essential \
  unzip \
  curl
RUN apt-get -y update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --force-yes $INSTALL

# gRPC & Protoc
ENV PROTOC_VER 3.1.0
RUN wget https://github.com/google/protobuf/releases/download/v$PROTOC_VER/protoc-$PROTOC_VER-linux-x86_64.zip
RUN unzip protoc-$PROTOC_VER-linux-x86_64.zip -d protoc
RUN cp protoc/bin/protoc /usr/local/bin && rm -rf protoc

ENV BINPATH /usr/local/bin
ENV PROTO_PATH /var/lib/protobuf
ENV GRPC_WORK_DIR /grpc
ENV GRPC_VER v1.0.1
RUN git clone -b $GRPC_VER https://github.com/grpc/grpc $GRPC_WORK_DIR
RUN cd $GRPC_WORK_DIR && git pull origin $GRPC_VER --recurse-submodules && git submodule update --init --recursive
RUN cd $GRPC_WORK_DIR && make && ls bins/opt
```

Maybe I am missing something? Any help would be appreciated, thanks!

**Comment by twoism** [comment]
Figured it out. Seems the gRPC plugin is only available in master and not included in any release yet.

You may want to update the docs to use `master` in this section.

https://github.com/grpc/grpc/tree/master/src/php#grpc-c-core-library

```
git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
```
Will clone `v1.0.0` which does not include the plugin.

**Comment by stanley-cheung** [comment]
gRPC 1.1.0 has been released. This marks the switch to use the official google/protobuf Proto3 implementation. Please install protoc 3.1.0+ (even better with 3.2.0+) to use the new code generator.

For the gRPC PHP Plugin, you can either use the `master` branch or the `v1.1.x` branch and run `make grpc_php_plugin`. In the future, we will be looking for a better mechanism to distribute this protoc plugin.
