### ISSUE TITLE
Provide a way to get a notification on inability to start a node gRPC server

### ISSUE THREAD

**Issue by denis-zhdanov** [grpc/grpc#8823]
Hello,

Please add an ability to be notified about errors on gRPC server start under node.js.

I created a [small project](https://github.com/denis-zhdanov/samples/tree/master/node/grpc-port-conflict) which illustrates the problem:

1. We can run _./src/grpc.js_ and ensure that gRPC is configured properly
2. gRPC startup fails if target port is already occupied - run _grpc-port-conflict.js_ where target port is bound to a node http server, then try to start gRPC server at the same port

The following in printed to the console:
```javascript
E1122 08:53:29.221790000 140736378774464 server_chttp2.c:159] {"created":"@1479794009.221737000","description":"No address added out of total 1 resolved","file":"../src/core/ext/transport/chttp2/server/insecure/server_chttp2.c","file_line":125,"referenced_errors":[{"created":"@1479794009.221733000","description":"Failed to add port to server","file":"../src/core/lib/iomgr/tcp_server_posix.c","file_line":634,"referenced_errors":[{"created":"@1479794009.221723000","description":"Unable to configure socket","fd":22,"file":"../src/core/lib/iomgr/tcp_server_posix.c","file_line":355,"referenced_errors":[{"created":"@1479794009.221703000","description":"OS Error","errno":48,"file":"../src/core/lib/iomgr/tcp_server_posix.c","file_line":331,"os_error":"Address already in use","syscall":"bind"}]}],"target_address":"ipv6:[::]:50051"}]}
```

I'd expect one of the following:

- allow to provide a callback to _server.bind()_ and propagate the error there
- throw an exception from _server.bind()_ in order for clients to be able to catch and report it

**Comment by murgatroid99** [comment]
Currently, that information is available, just not in the format you describe. `server.bind` returns the port number that was bound (useful if you're binding to port 0), and it returns 0 if the operation failed.

**Comment by RodionGork** [comment]
@murgatroid99 thanks for answer.

I'checked this and see that if I run two instances of the gRPC server, than for both the `Server.bind('0.0.0.0:50051', ...)` returns the value `50051`. It does not return `0` for the instance which was started second (as I naively expect). Is it correct behavior?

**Comment by murgatroid99** [comment]
Unless there's a major bug somewhere, that output is correct, and both servers are bound to that port. gRPC automatically binds ports with SO_REUSEPORT, so multiple gRPC servers can actually successfully bind the same port at the same time.

**Comment by RodionGork** [comment]
Thanks, I'm sorry to say I never heard of SO_REUSEPORT, though it obviously makes sense for node app.

I've just checked and found you are pretty correct - multiple server instances will serve grpc calls listening to the same port.

Also, if the port is taken by other appliction, the `Server.bind` returns `0` as you've described. Thank you very much! The only thing to regret is that documentation is lacking these details :)
