### ISSUE TITLE
Is there some way to make grpc use third_party force when compile

### ISSUE THREAD

**Issue by YuleiXiao** [grpc/grpc#8837]
There are other version openssl,protobuf or other third party in OS. When I compile grpc, grpc use the ```/usr/local``` file but not in ```third_party```. Is there any way to force grpc use ```third_party```?

**Comment by soltanmm-google** [comment]
That shouldn't happen... did you `git submodule update --init`? What did you do, and what was the output?

**Comment by YuleiXiao** [comment]
@soltanmm-google I do not use ```git submodule```, but I download all ```third_party``` package and extract them into ```third_party```. I see ```Makefile``` that there is code like below, it will check if OS has these library.

```
ifeq ($(EMBED_ZLIB),true)
ZLIB_DEP = $(LIBDIR)/$(CONFIG)/libz.a
ZLIB_MERGE_LIBS = $(LIBDIR)/$(CONFIG)/libz.a
ZLIB_MERGE_OBJS = $(LIBZ_OBJS)
CPPFLAGS += -Ithird_party/zlib
LDFLAGS += -L$(LIBDIR)/$(CONFIG)/zlib
else
ifeq ($(HAS_PKG_CONFIG),true)
CPPFLAGS += $(shell $(PKG_CONFIG) --cflags zlib)
LDFLAGS += $(shell $(PKG_CONFIG) --libs-only-L zlib)
LIBS += $(patsubst -l%,%,$(shell $(PKG_CONFIG) --libs-only-l zlib))
PC_REQUIRES_GRPC += zlib
else
PC_LIBS_GRPC += -lz
LIBS += z
endif
endif
```

**Comment by soltanmm-google** [comment]
Is there any particular reason why you're avoiding using `git submodule --init`? The versions it retrieves are specified in the `.gitmodules` file and it retrieves specifically those versions for source compatibility and directory-finding reasons. In the event the libraries aren't found where and how the gRPC build system wants to find them you may encounter such behavior as a form of fallback IIRC.

**Comment by nicolasnoble** [comment]
No reply for a while - also there's now an EMBED_OPENSSL flag for this.
