### ISSUE TITLE
"End of TCP stream" error on grpc node sdk

### ISSUE THREAD

**Issue by smartheye** [grpc/grpc#8839]
I am using hfc@0.6.5
node@4.2.6
npm@4.0.2
Win7
grpc was compiled by VS2015.3 community edition

the following error occasionally happened at the grpcs connection by grpc nodejs.
It could happen at any grpcs connection. 
It seems likely to be same error as #8382. But I am not sure.
Is there any workaround for nodejs?

handshake.c:128] Security handshake failed: {"created":"@1479878572.454000000","description":"Handshake read failed","file":"..\src\core\lib\security\transport\handshake.c","file_line":237,"referenced_errors":[{"created":"@1479878572.454000000","description":"End of TCP stream","file":"..\src\core\lib\iomgr\tcp_windows.c","file_line":180}]}

THANKS for your kind advice.

**Comment by murgatroid99** [comment]
You could try a Node variant of the same workaround mentioned in that other issue. The Client constructor in the Node library accepts channel arguments as its third argument, so you may have some luck with something like this:

```js
client = new Client(address, credentials, {"grpc.initial_reconnect_backoff_ms": 10000});
```
