### ISSUE TITLE
C# codegen commandline options (no_server and no_client)

### ISSUE THREAD

**Issue by tanordheim** [grpc/grpc#8840]
In #6284, new C# codegen options were merged into the code base - but I'm having some issues getting this working. I'm not familiar with the compiler side of protobuf here so I'm a bit on thin ground debugging the issue.

As far as I can tell, the intent here is for these options to be passed in as `protoc --csharp_out=path --csharp_opt=no_server`, but invoking the compiler with any of these new options (`no_server` or `no_client`) yields the following error message:

```
--csharp_out: test.proto: Unknown generator option: no_client
```

The `internal_access` flag added in the same merge seems to work as intended though, adding that as `csharp_opt` flags causes models to generated as internal instead of public.

Am I using this wrong? I'm on OSX 10.12.1, invoking the plugin `tools/macosx_x64/grpc_csharp_plugin` from the 1.0.1 version of Grpc.Tools from NuGet.

**Comment by jtattermusch** [comment]
the no_server and no_client options are part of the grpc plugin ("csharp" plugin is what generates code for C# protobuf messages and is embedded in the protoc binary), so you need to rather do --grpc_opt I believe.

**Comment by tanordheim** [comment]
`--grpc_opt` is not a valid flag as far as I can tell, at least protoc is spitting out an `Unknown flag: --grpc_opt` error when I try to invoke it here.

**Comment by jtattermusch** [comment]
Alright, so the right syntax to use for plugins  is --grpc_out=no_client:YOUR_OUTPUT_PATH

**Comment by jtattermusch** [comment]
You can specify the options for given plugin as a prefix for the `*_out` path.  `option=val:PATH` or `option:PATH`. Just verified that it works.

**Comment by tanordheim** [comment]
Ah, allright - then feel free to close this issue :)

Thanks for the help!
