### ISSUE TITLE
Leading whitespace formatting in generated c# doc comments

### ISSUE THREAD

**Issue by W1zb1t** [grpc/grpc#8856]
If I have the following in my proto:
```
  // This allows access to fascinating stuff.
  rpc BlowMyMind(FascinationRequest) returns (AstoundingResult) {}
```

then I get the following c#:
```
      /// <summary>
      ///   This allows access to fascinating stuff.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::MyNamespace.WonderApi.AstoundingResult> BlowMyMind(global::MyNamespace.WonderApi.FascinationRequest request, ServerCallContext context)
```
Note that the summary comment has an extra space after the '///' that precedes the comment body.
If I remove the space between the '//' and the comment body in the proto then it disappears.

This is obviously of a totally trivial nature; but the fix is a simple trim of any leading spaces on each comment line. Ie no rush... just thought I'd note it

**Comment by jtattermusch** [comment]
Does this only happen with code generated by gRPC C# plugin (the FooGrpc.cs file) or also with code generated by protobuf C# itself (in the Foo.cs file containing the protobuf messages)? If in both, this issue should be also filed in google/protobuf  repository.

**Comment by W1zb1t** [comment]
Sorry for my absence. Thanks and I'll review the impact on Foo.cs as soon as I get some space and raise to the google/protobuf repository if relevant.
