### ISSUE TITLE
grpc@1.0.0 install: `node-pre-gyp install --fallback-to-build` fails when running npm install hfs

### ISSUE THREAD

**Issue by shaggykp** [grpc/grpc#8858]
I'm trying to build the base fabric-starter-kit image for the hyperledger fabric on my Mac OS.  When running the following to build it fails:
>docker build -t hyperledger/fabric-starter-kit:latest .

I get the following error:
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "hfc"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

I checked to makes sure I have the latest version of node and npm.  Any help in understanding how to resolve this would be appreciated.

**Comment by shaggykp** [comment]
debug log is attached
[npm-debug.txt](https://github.com/grpc/grpc/files/613642/npm-debug.txt)

**Comment by murgatroid99** [comment]
I can't tell from the log why you are seeing a failure, but it may be related to the fact that we have not yet published binary packages for Node 7. I would recommend trying again with Node 6.

**Comment by murgatroid99** [comment]
Note: this is no longer the case. We have since published packages for Node 7.
