### ISSUE TITLE
Lack of document for php extension of grpc

### ISSUE THREAD

**Issue by wangming1993** [grpc/grpc#8859]
Hi,

I'm working with grpc, when I write client code with PHP, I found little document about grpc php extension.

I only found: http://www.grpc.io/grpc/php/namespaces/Grpc.html.

I'm really need some document about what is **`Grpc\ChannelCredentials`**, **`Grpc\\ServerCredentials`**, etc, and the methods, properties is has.

Because I am not familiar with `c`, so it is hard to read the source code under **grpc/grpc/src/php/ext**.

Really need some help from grpc php group!!!

Thanks

**Comment by wangming1993** [comment]
@stanley-cheung

**Comment by wangming1993** [comment]
@stanley-cheung any progress? thx

**Comment by ZhouyihaiDing** [comment]
I'll start writing docs about the class like Channel and error codes which implement in c extension, or extract the comment from codes directly and update into [grpc.io php API](https://grpc.io/grpc/php/namespace-Grpc.html).

**Comment by ZhouyihaiDing** [comment]
I didn't find a good tool to generate API document automatically from C extension. However, I noticed that someone has already make the document as [`grpc.php`](https://github.com/iMega/grpc-phpdoc/blob/master/grpc.php). With the same idea, we can do the same thing -- upload such file into packagist named as `grpc-ext-for-api-doc`, and then there are tools generating the document like `apigen`.

**Comment by stanley-cheung** [comment]
This has been updated.

grpc.io (main website) -> Docs -> Languages -> PHP -> API Reference, which will land you to https://grpc.github.io/grpc/php/namespace_grpc.

We have updated the generated documentation to include both the .c|.h classes from the PECL extension, as well as the .php classes from our composer package.
