### ISSUE TITLE
CMake: Erroneous compile flag for Visual C++ builds (-std=c11)

### ISSUE THREAD

**Issue by robiwano** [grpc/grpc#8861]
-std=c11 should only be added for clang and gcc. Visual studio complains with:

Warning	D9002	ignoring unknown option '-std=c11'

```
if(NOT MSVC)
  target_compile_options(<targets> PRIVATE "-std=c11")
endif()

```

**Comment by robiwano** [comment]
-std=c++11 is also set for the C++ targets: 

 cl : Command line warning D9002: ignoring unknown option '-std=c++11'

**Comment by jtattermusch** [comment]
Looks like this has been fixed: https://github.com/grpc/grpc/blob/6beba3c50e2ac9032da196b9bbf8b2f5484cb924/CMakeLists.txt#L272

**Comment by robiwano** [comment]
Hmm, yes, but it should have been fixed by adding CXX_STANDARD 11 to the relevant targets like so:

`set_target_properties(<target> PROPERTIES CXX_STANDARD 11)`

as opposed to adding it to CMAKE_CXX_FLAGS which is global.

**Comment by jtattermusch** [comment]
@robiwano, pull requests are welcome.
