### ISSUE TITLE
gRPC node client - no way to close the connection from client side

### ISSUE THREAD

**Issue by assaf-xm** [grpc/grpc#8881]
There is no way to terminate the client object (/close the gRPC client connection) from node js code.
This is needed in order to close the HTTP connection to the server and clear server resources without the need to wait for the garbage collector.

**Comment by murgatroid99** [comment]
It's a little hidden, but you can close a client with `grpc.getClientChannel(client).close()`. Version 1.1 will also have the simpler `grpc.closeClient(client)`.

**Comment by murgatroid99** [comment]
As of 1.4.1, the simplest API is now `Client.prototype.close`, which can usually be called as `client.close()`, unless the service that the client was generated for has a `close` method.
