### ISSUE TITLE
after stream.write() throw once, following correct stream.write() get buffered.

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#8882]
Hello,

from **nodejs** grpc server, if I write to a stream with **BAD** data, it will throw an error:
```javascript
stream.on('error', console.log('nothing catched here');

function writeToStream(data) {
  try {
    stream.write(data)
  } catch (error) {
    console.log('catched the error here');
  }
}
writeToStream(correctData) // grpc client receive
writeToStream(badData); // grpc client NEVER receive
writeToStream(correctData); // grpc client NEVER receive
```
my problem is that the next time I write to this stream, with **correct** data, the grpc client never receives the **correct** data written to the stream...

@murgatroid99 Any idea on this one?

Many thanks!

**Comment by murgatroid99** [comment]
It looks like the code simply does not properly handle the case where unserializable data is written to the stream. I'm sure we can fix that in the next release, but for now, just try not to write any unserializable data.

**Comment by murgatroid99** [comment]
To be clear, the best "fix" may be to have the whole call fail when bad data is sent. I'm not sure that we should just ignore errors like that. Serialization success usually depends only on the type and structure of the provide object, so a failure there indicates a serious error in program logic.

**Comment by sulliwane** [comment]
In case of a simple **unary call**, I handle bad data with the callback in catch statement (so nothing to fix there I think...unless node grpc wants to make this behaviour the default one).
```javascript
function grpcMethod(call, callback) {
  try {
    const data = getMyData();
    callback(null, data);
  } catch (error) {
    debug('callback throw because bad data');
    callback(error);
  }
}
```


**In case of a stream**, after writing bad data to the stream, the stream is not errored, but still malfunction for successive calls (so my point is that I have no way to close the stream -server side-, or let the client know this stream is errored/dead).

It throws correctly
```javascript
function writeToStream(data) {
  try {
    stream.write(data)
  } catch (error) {
    console.log('catched the error here, throwing because bad data');
  }
}
```
but then -if I understand the situation correctly- two options should be considered:

**1-** after throwing on ```stream.write()``` call, **the stream should still be operational** for following stream.write() calls. (this is not the case right now).

**2-** after throwing on ```stream.write()```, the stream should not be operational anymore,  and so it should emit an error event, send the error to the client and disconnect the client. As the client receive the error, it can then decide how to handle the error (it may decide to open a new stream for example).

I personally prefer the first option, as the server can decide if bad data should close/error the stream and disconnect the client, **or not**. In my case and for this project, I'd prefer to just discard bad data (catch the error and ignore it) and continue to write to stream the following call (with correct of bad data).

Thanks for your answer!

**Comment by murgatroid99** [comment]
I'm assuming that in the unary example, `getMyData()` calls a gRPC method.

I think you are missing something here. The error you are seeing happens when the object provided cannot be serialized. The server never has a chance to decide how to handle this case because there was nothing to send. So the option 1 that you seem to be visualizing is simply not possible.

It's true that we could simply discard unserializable data on the client side without errors, but the fact is that passing objects that cannot be serialized is a misuse of the API, and should be an error. Serialization of objects generally depends only on the type and structure of the provided object, so it should be easy to ensure that any objects you try to write can be serialized.

**Comment by sulliwane** [comment]
I'm not sure I explain clearly my meaning, here is the full code for unary call, and server stream call:

# Unary
## Client side
```javascript
const serviceProto = grpc.load(protoFile);
const client = new serviceProto(clientOptions);

client.grpcMethodGetAString({}, (error, result) => {
  if (error) console.log(error); // no error, even if grpcMethodGetAString() on the server throw, see below
});
```
## Server side:
```javascript
function grpcMethodGetAString(call, callback) {
  try {
    const badData = 12345; // this is not a string
    callback(null, data);
  } catch (error) {
    console.log('callback(null, 12345) will throw, and is catched here');
    callback(error); // I want to let the client know there was an error with this call
    // but this callback(error) doesn't work after I call callback(null, 12345) with bad data.
  }
}
```
# Stream
server continually pushes to client, stream never ends.
## Client side
```javascript
const serviceProto = grpc.load(protoFile);
const client = new serviceProto(clientOptions);

const aStreamOfStrings = client.grpcMethodGetStreamOfStrings({});
aStreamOfStrings.on('error', console.log(error)); // no error, I'm ok with it
```
## Server side:
```javascript
import integerEvent from 'somewhere';

function grpcMethodGetStreamOfStrings(stream) {
  try {
    stream.on('cancelled', () => integerEvent.removeListener('integer');
    stream.on('error', () => integerEvent.removeListener('integer');

    integerEvent.on('integer', (badData) => {
      stream.write(badData);
    }
  } catch (error) {
    console.log('stream.write(badData) throwed and catched here');
    // I want my next stream.write(correctData) to succeed
    // I don't want this stream to be closed, or errored

   // OR, In case I want to close the stream, I could do this:
   stream.emit('error', error); // right ?
   // but if I do this AFTER I called stream.write(badData), the client never receive the error I try to push to him.
  }
}
```

So I totally agree that the badData will never get through the network and reach the client (and it should not) as the server will throw an error, when using ```callback(null, badData)``` or ```stream.write(badData)```.

**But the point I don't understand is:** why AFTER I did call once  ```callback(null, badData)``` or ```stream.write(badData)```, the **callback()** function or the **stream.write()** function are UNUSABLE.

### I'd like to be able to do this
```javascript
// server side
// successive calls
// 1
stream.write(correctData) // client receives correctData

// 2
try {
  stream.write(badData); // client receives nothing, no data, no error. Yes, it will throw on the server, but I catch the error and ignore it.
} catch (error) {
  // do nothing, swallow the error
}

// 3
stream.write(correctData); // client receives correctData
```

Thank you for bearing with me ;)

**Comment by murgatroid99** [comment]
I see what you're saying now. The simple answer to your question is that (currently) passing non-serializable data to the callback or write method is an improper use of the API, and puts the call in an invalid state. The fact that the error bubbles up out of the `stream.write` call is not guaranteed, and is basically an implementation detail.

I think the only reasonable solution is to have this be a stream error, and have it result in the call ending with an error status.

**Comment by sulliwane** [comment]
Yep, you got my point.

Any idea about how other languages handle this case? (go-grpc, java-grpc...). Do they all **close/end the call** in the case bad data is written to the stream?

I can edit the title if you think of a better issue description.

**Comment by sulliwane** [comment]
@murgatroid99  Looking at the commits, seems like the grpc writable stream will now comply with node writable stream implementation [described here](https://nodejs.org/api/stream.html#stream_errors_while_writing)

Especially: 

> It is recommended that errors occurring during the processing of the writable._write() and writable._writev() methods are reported by invoking the callback and passing the error as the first argument. This will cause an 'error' event to be emitted by the Writable. Throwing an Error from within writable._write() can result in expected and inconsistent behavior depending on how the stream is being used. Using the callback ensures consistent and predictable handling of errors.

Because I want to make sure that with the new version of node-grpc I'll be able to catch serialization errors by listening to the **error** event, **especially when using .pipe()** (see below example):
```
function grpcMethodGetMongodbStream(grpcStream) {
  try {
    mongodb.getStream().pipe(grpcStream).on('error', () => console.log('serialization error catched'));
  } catch (error) {
    console.log('other errors catched', error);
  }
}
```
Many thanks for your answer!
