### ISSUE TITLE
completion_queue.c:303 assertion failed: !cc->shutdown triggered when calling CompletionQueue::Next

### ISSUE THREAD

**Issue by athei** [grpc/grpc#8883]
Sometimes my Async client crashes with `completion_queue.c:303 assertion failed: !cc->shutdown` when calling CompletionQueue::Next. I have a dedicated thread that runs the follwing code:
```
void Client::run() {
	void* tag;
	bool ok;
	bool running;
	while (true) {
		running = completionQueue_.Next(&tag, &ok);
		if (ok && running) {
			static_cast<CallData*>(tag)->Finish();
		} else {
			break;
		}
	}
}
```
I stop this thread by calling
```
void Client::Shutdown()
{
	completionQueue_.Shutdown();
} 
```

from another thread.

Is there something wrong with this approach? Why could this assertion be triggered? Is it a problem to add requests to a shutted down queue or does it just silently discards them?

**Comment by vjpai** [comment]
It's not allowed to add a request or perform an operation on a queue that has been shutdown. If you your shutdown and operations are in different threads, you need to have some synchronization variable to make sure that you don't add anything to a queue that has been shutdown.
