### ISSUE TITLE
IoT devices data transfer uses SSL/TLS to encrypt or plaintext?

### ISSUE THREAD

**Issue by leopeng1995** [grpc/grpc#8885]
Does anybody knows IoT devices uses grpc to transfer with encrypted data or plaintext? I heard somebody says if there are **massive** IoT devices it would uses plaintext rather than encrypted data to transfer. Is that true?

**Comment by vjpai** [comment]
The gRPC code and protocol (which applies from IoT up to DCs) supports either encrypted data or plaintext. It is possible that some platforms do not support the needed encryption libraries, but that would be platform specific, not part of the protocol.
