### ISSUE TITLE
How to cross-compiling

### ISSUE THREAD

**Issue by hhy156kk** [grpc/grpc#8886]
I want to compile to powerpc-linux ,Now I am use x86_64,how to change Makefile?

**Comment by vjpai** [comment]
We don't officially support cross-compiling but we do have many users doing cross compilation.  If you see https://github.com/grpc/grpc/pull/7476/files , you'll see a list of instructions for how to do your cross compilation. In the near future, there will be a better solution - once #7631 is merged. In the meanwhile, please follow the instructions in templates/Makefile.template
