### ISSUE TITLE
Does grpc/csharp work in unity3d-ios AOT mode?

### ISSUE THREAD

**Issue by w359405949** [grpc/grpc#890]

**Comment by nicolasnoble** [comment]
That one's going to be fun to test :-)

**Comment by jtattermusch** [comment]
No, it does not work. In theory, I don't see why it wouldn't work, once you manage to compile the gRPC C core library on iOS and if P/Invoke works under unity (which I think it should). But this is something we definitely haven't tested yet.

**Comment by w359405949** [comment]
as far as i know, ios-mono only works on .net 2.0 subset mode, many features are unvaliable.

**Comment by jtattermusch** [comment]
gRPC c# uses async/await feature from c# 5 (and requires .NET 4.5 +)

**Comment by Thaina** [comment]
As of now unity3D recent version already support dotnet framework 4.6 as experimental feature. It soon be stable

Would you pleased to test and make a package for unity3D too?

**Comment by Thaina** [comment]
@jtattermusch I have seen working example here https://github.com/ahakits/unity-grpc-sample

Is it already just worked? Are there anyway we could ensure it perfectly work in everything?
