### ISSUE TITLE
Current grpc ruby gem not working with ruby versions with more than 1 patch digit

### ISSUE THREAD

**Issue by dcadenas** [grpc/grpc#8905]
grpc will fail with a ruby version with more than one patch digit as in ruby `2.1.10`. This comes from a bug fixed in [protobuf 3.1.0](https://github.com/google/protobuf/commit/866d3e5327d11b6846edb1b65f73673008a43ed2)

**Comment by murgatroid99** [comment]
What version of the Ruby gem are you using? We made a change that should have fixed that (#7800) around the same time that we contributed that fix to protobuf. The fix should definitely be in the gRPC 1.0.1 gem.

**Comment by dcadenas** [comment]
I'm using latest grpc 1.0.1 but it is still pointing to protobuf 3.0.2 which contains the [bug](https://github.com/google/protobuf/blob/v3.0.2/ruby/lib/google/protobuf.rb#L48) :(

```
$ gem dependency grpc
Gem grpc-1.0.1-universal-darwin
  bundler (~> 1.9, development)
  facter (~> 2.4, development)
  google-protobuf (~> 3.0.2)
  googleauth (~> 0.5.1)
  logging (~> 2.0, development)
  rake (~> 10.4, development)
  rake-compiler (~> 0.9, development)
  rake-compiler-dock (~> 0.5.1, development)
  rspec (~> 3.2, development)
  rubocop (~> 0.30.0, development)
  signet (~> 0.7.0, development)
  simplecov (~> 0.9, development)

Gem grpc-tools-1.0.1
```

**Comment by apolcyn** [comment]
addressed by https://github.com/grpc/grpc/pull/8914, this will be in the next release
