### ISSUE TITLE
NASM support lacking in CMake for Visual Studio generators, making BoringSSL fail in 64 bit builds.

### ISSUE THREAD

**Issue by robiwano** [grpc/grpc#8910]
On the other hand, MASM support is available, and as I found out, boringssl has a MASM asm style!! (but it doesn't work 100%, see other issue related to that)

**Comment by jtattermusch** [comment]
Compilation with asm currently works when using ninja & yasm (see https://github.com/grpc/grpc/blob/master/INSTALL.md#windows).

What you are describing seems more like OpenSSL/boringssl issue.
