### ISSUE TITLE
CMake: Using MASM perl asm style on Visual Studio (64 bit) yield assembler error

### ISSUE THREAD

**Issue by robiwano** [grpc/grpc#8911]
Trying MASM (instead of non-functioning NASM) on Windows, all ASM files but one assemble:

C:\binaries\boringssl\crypto\rand\rdrand-x86_64.asm(69): fatal error A1010: unmatched block nes

The asm file looks like follows:
```
OPTION	DOTNAME
.text$	SEGMENT ALIGN(256) 'CODE'




PUBLIC	CRYPTO_rdrand

ALIGN	16
CRYPTO_rdrand	PROC PUBLIC
	mov	QWORD PTR[8+rsp],rdi	;WIN64 prologue
	mov	QWORD PTR[16+rsp],rsi
	mov	rax,rsp
$L$SEH_begin_CRYPTO_rdrand::
	mov	rdi,rcx


	xor	rax,rax


DB	048h,00fh,0c7h,0f1h

	adc	rax,rax
	mov	QWORD PTR[rdi],rcx
	mov	rdi,QWORD PTR[8+rsp]	;WIN64 epilogue
	mov	rsi,QWORD PTR[16+rsp]
	DB	0F3h,0C3h		;repret





PUBLIC	CRYPTO_rdrand_multiple8_buf

ALIGN	16
CRYPTO_rdrand_multiple8_buf	PROC PUBLIC
	mov	QWORD PTR[8+rsp],rdi	;WIN64 prologue
	mov	QWORD PTR[16+rsp],rsi
	mov	rax,rsp
$L$SEH_begin_CRYPTO_rdrand_multiple8_buf::
	mov	rdi,rcx
	mov	rsi,rdx


	test	rsi,rsi
	jz	$L$out
	mov	rdx,8
$L$loop::


DB	048h,00fh,0c7h,0f1h
	jnc	$L$err
	mov	QWORD PTR[rdi],rcx
	add	rdi,rdx
	sub	rsi,rdx
	jnz	$L$loop
$L$out::
	mov	rax,1
	mov	rdi,QWORD PTR[8+rsp]	;WIN64 epilogue
	mov	rsi,QWORD PTR[16+rsp]
	DB	0F3h,0C3h		;repret
$L$err::
	xor	rax,rax
	mov	rdi,QWORD PTR[8+rsp]	;WIN64 epilogue
	mov	rsi,QWORD PTR[16+rsp]
	DB	0F3h,0C3h		;repret

.text$	ENDS
END    <<< A1010 error here!

```

**Comment by robiwano** [comment]
I note now that there is no ENDP terminating the PROC procedures. Once added, the asm file assembles nicely. So there must be a problem generating MASM flavor from the perl file.

**Comment by robiwano** [comment]
The rdrand-x86_64.pl seems to be lacking the following rows:

`.size CRYPTO_rdrand,.-CRYPTO_rdrand`

and

`.size	CRYPTO_rdrand_multiple8_buf,.-CRYPTO_rdrand_multiple8_buf`

When I add those, MASM generation and assembly works and crypto target links.

**Comment by jtattermusch** [comment]
Compilation with asm currently works when using ninja & yasm (see https://github.com/grpc/grpc/blob/master/INSTALL.md#windows).  

What you are describing seems more like OpenSSL/boringssl issue.
