### ISSUE TITLE
SHARED_VERSION is used but not defined in master's Makefile.template

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#8918]
It looks like SHARED_VERSION was renamed to SHARED_VERSION_CORE in master branch's Makefile.template, but there are still a few Makefile targets that try to use the old SHARED_VERSION

This seems to be one of the main problems in https://github.com/grpc/grpc/issues/8124 - the ruby `opt/linux` package build tries to use one of those bad Makefile targets.

I'm not sure how the rest of the targets that still use SHARED_VERSION should be changed though.

**Comment by nicolasnoble** [comment]
Ruby is probably what has to change there.

**Comment by murgatroid99** [comment]
This is specifically a Makefile problem. There are variables in the Makefile that are used but not defined.

**Comment by apolcyn** [comment]
Just for clarity adding this to 1.1 release pre-reqs. 

At least for ruby package builds though, this is fixed by #8957.
