### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [grpc/grpc#893]
I would like to point out that identifiers like "[`__GRPC_BYTE_BUFFER_H__`](https://github.com/grpc/grpc/blob/190d360defe58eec0540d50cbb5d4a8f4878c4f1/include/grpc/byte_buffer.h#L34)" and "[`__GRPCPP_SERVER_H__`](https://github.com/grpc/grpc/blob/cf133f41f84c6c8d306293a5dc8f81fbd9aed1a1/include/grpc%2B%2B/server.h#L34)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ctiller** [comment]
I'm good with that.

Propose: GRPC(PP)?_+full path name

Nico - suggest a script :)

**Comment by nicolasnoble** [comment]
Yeah, I noticed that one. Note how this is in conflict with internal codestyle ;-)

**Comment by elfring** [comment]
Thanks for your improvement of the affected include guards.
