### ISSUE TITLE
Cannot find module grpc_node.node

### ISSUE THREAD

**Issue by matthewbschneider** [grpc/grpc#8941]
```
$ npm install google-cloud
```
Run node app...

Error:

2016-12-03T19:23:07.361Z - error: uncaughtException: Cannot find module '/opt/app/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.$
Error: Cannot find module '/opt/app/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/app/node_modules/google-cloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```
$ ls /opt/app/node_modules/google-cloud/node_modules/grpc/src/node
ext  index.js  README.md  src
```

Environment: Linux Debian 3.16.7

**Comment by murgatroid99** [comment]
Do you have any output from `npm install`? Specifically, anything related to `node-pre-gyp` or "Pre-built binaries"?

**Comment by hristo-vrigazov** [comment]
I am experiencing the same issue, running grpc from inside Docker container (in Cloud9 IDE)

**Comment by xuqingsz** [comment]
Hi @murgatroid99 

This thread seems to be quiet for some time. I am still having this problem, and none of the posts out there were able to resolve the issue.

In case you are wondering, I have the node-pre-gyp results here:

> grpc@1.0.0 install /usr/src/app/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.29
node-pre-gyp info using node@4.8.0 | linux | x64
node-pre-gyp info validate Running test command: '/usr/local/bin/node --eval 'require(\'/usr/src/app/node_modules/grpc/src/node/extension_binary/grpc_node.node\')''
[grpc] Success: "/usr/src/app/node_modules/grpc/src/node/extension_binary/grpc_node.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
node-pre-gyp info ok 

Ended with an OK. I am not sure what else to try.
Please advise. Thanks.

**Comment by murgatroid99** [comment]
To be clear, are you saying that even though you are getting installation output indicating that `/usr/src/app/node_modules/grpc/src/node/extension_binary/grpc_node.node` exists, you are also getting a message saying that that module cannot be found? Can you check whether the file does actually exist?

**Comment by xuqingsz** [comment]
Yes, that is the confusing part to start with. It says _grpc_node.node_ was already installed, yet node <app.js> could not find it. Nor does _grpc_node.node_ show up on 'ls' command. 
Thanks.

**Comment by murgatroid99** [comment]
Do you have a Dockerfile that I could use to reproduce this?

**Comment by walshe** [comment]
also getting this issue

**Comment by murgatroid99** [comment]
How did you install gRPC? Did you get any installation output related to gRPC?

**Comment by walshe** [comment]
this fixed it:  npm install --unsafe-perm

**Comment by vasiliyb** [comment]
Unfortunately, running into the same issue in Docker on mac.

Dockerfile
```
FROM node:6.10.3

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY lib/ /usr/src/app/lib/
COPY config/ /usr/src/app/config

RUN cd /usr/src/app
RUN npm install --unsafe-perm

EXPOSE 3000

CMD ["node","lib/server.js"]
```

package.json
```
"@google-cloud/datastore": "^1.0.3",
"@google-cloud/pubsub": "^0.14.0"
```

Error
```
error:  event=server, err=Error: Cannot find module '/usr/src/app/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64/grpc_node.node'
```

However, in the container itself, I see darwin!
```
root@5ac5b4fc2d06:/usr/src/app# ls /usr/src/app/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64/
```

Any suggestions welcome!  THANKS!

**Comment by vmeng** [comment]
@vasiliyb I have the same problem with you
Here is how i fix it. In Dockerfile, add 
```
FROM node:latest
USER root
```
Also add .dockerignore same level as package.json
in .dockerignore, just add one line
```
node_modules
```

**Comment by bganov** [comment]
@vmeng, 'node:latest' is not a solution for my use case. I need to use node 6.11.0 and that won't cope with the latest flag. Is there an alternative solution?

**Comment by murgatroid99** [comment]
It might help to add `RUN npm rebuild` after the `npm install` line.

**Comment by lukesneeringer** [comment]
`npm install --unsafe-perm` worked for my use case.

**Comment by igor-yamshchykov** [comment]
@vasiliyb 
`npm rebuild grpc` helped in my case, had same issue within docker

**Comment by npHavens** [comment]
I'm also using Docker. Just adding node_modules to the .dockerignore file worked for me.

**Comment by giwiro** [comment]
`npm rebuild grpc --force` did the trick for me.

Node v9.4.0
npm v5.6.0

**Comment by richtera** [comment]
Still having this problem but I am using yarn. Since my dependencies usually get corrupted when using npm install I am not quite sure what to do here.

**Comment by richtera** [comment]
I think I found a workaround. I cleared most references to grpc and common-grpc from my yarn lock and had it re-resolve them to be latest. Seems some of the google components pull in older versions and somehow those don't get built correctly. For example @google-cloud/logging-winston.
