### ISSUE TITLE
This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0

### ISSUE THREAD

**Issue by huangyingqiu** [grpc/grpc#8943]
I want ro run hello world example,but get some problem,

Try it!
To try the sample app, we need a gRPC server running locally. Let's compile and run, for example, the C++ server in this repository:
$ pushd ../../cpp/helloworld
$ make
$ ./greeter_server &
$ pops

when i do $./greeter_server &   ,it get some problem as follow

This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "helloworld.pb.cc".)
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "helloworld.pb.cc".)

I don't know how to resolve it.Ask for help!

**Comment by ncteisen** [comment]
I have been able to repro this on MacOS and Linux. In both cases I made sure to clean, rebuild, and reinstall the protobuf lib. Interestingly, on MacOS, the error inducing file is helloworld.pb.cc, and on Linux it is google/protobuf/any.pb.cc. 

And in both cases, the line that causes the error is [here](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/common.cc#L65). For some reason GOOGLE_PROTOBUF_VERSION contains 3.0.0 even though 3.1.0 is installed on the system.

**Comment by ncteisen** [comment]
Well after a little more poking around, I solved my problem here. Try running these from grpc repository:
```
make clean
make
sudo make install
cd examples/cpp/helloworld
make clean
make
./greeter_client
```
That worked for me.

**Comment by huangyingqiu** [comment]
@ncteisen Thanks,But It don't help me and report another error on my macOS10.12!

**Comment by jaimemartinez88** [comment]
@ncteisen solution doesn't work for me. I've uninstalled protoc and tried again but I still get the same error with a bunch of warnings.
```
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
[HOSTLD]  Linking /home/jaime/go/src/git.clinicloud.com/embed/grpc/bins/opt/grpc_objective_c_plugin
[HOSTLD]  Linking /home/jaime/go/src/git.clinicloud.com/embed/grpc/bins/opt/grpc_php_plugin
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
[HOSTLD]  Linking /home/jaime/go/src/git.clinicloud.com/embed/grpc/bins/opt/grpc_python_plugin
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
[HOSTLD]  Linking /home/jaime/go/src/git.clinicloud.com/embed/grpc/bins/opt/grpc_ruby_plugin
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
[HOSTLD]  Linking /home/jaime/go/src/git.clinicloud.com/embed/grpc/bins/opt/grpc_cpp_plugin
/usr/bin/ld: warning: libprotobuf.so.12, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.10
[PROTOC]  Generating protobuf CC file from src/proto/grpc/health/v1/health.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/health/v1/health.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/echo_messages.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/testing/echo_messages.proto
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/payloads.proto
[libprotobuf FATAL google/protobuf/stubs/common.cc:67] **This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/any.pb.cc".)**
```

**Comment by jtattermusch** [comment]
@ncteisen,  we should have a distribtest for C++ that makes sure our examples (or a simplified version of them) work. We have something similar in place for other languages already.

**Comment by ncteisen** [comment]
Good idea, just filed #10788. I'll get to it on a slow day.

**Comment by ncteisen** [comment]
As a solution for @huangyingqiu and @jaimemartinez88, I would try re installing everything to be safe. Here are the steps I just took (caveat, they might not be the safest):
* I nuked my /usr/local/lib/ and cleared out all proto and grpc libs
  * `rm -f /usr/local/lib/libproto* /usr/local/lib/libgrpc*`
* Cleaned everything
  * `git submodule foreach git clean -xfd`
  * `git clean -xfd`
* Ensured that I was at head (or you could pick any previous version)
  * `git pull upstream master`
  * `git submodule update init`
* Reinstalled everything
  * `cd third_party/protobuf`
  * `./autogen.sh`
  * `./configure`
  * `make`
  * `sudo make install`
  * `cd ../../` [back to the gRPC root]
  * `make`
  * `sudo make install`

After all that, the examples built. Hope this helps!

**Comment by jaimemartinez88** [comment]
I figured out what was happening on my end. For some reason I had an old library installed using apt-get, it was under
```
/usr/lib/x86_64-linux-gnu/libproto*
```
When I uninstalled the libprotobuf10 and libprotobuf-dev libraries then the example finally compiled!
 ```
sudo apt-get remove --purge libprotobuf10 libprotobuf-dev 
```
