### ISSUE TITLE
CompletionQueue Next return true but ok is false

### ISSUE THREAD

**Issue by Dustskyfield** [grpc/grpc#8947]
Change greeter_async_server.cc code, before CompletionQueue Next, I run method
`  service_->RequestSayHello(&ctx_, &request_, &responder_, cq_, cq_, this);` 
32768 times. client is not start, but Next can return true,and ok is false.

**Comment by ZTJiu** [comment]
I also encountered same return on CompletionQueue::AsyncNext.

**Comment by ncteisen** [comment]
See #13019 for ongoing doc work
