### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by yoavniran** [grpc/grpc#8972]
Hi,
im working on a (meteor) project and keep getting this error: %1 is not a valid Win32 application

windows 10 64bit
node v4.6.2

it depends on google-cloud ^0.44.2

When the app starts i get the following error:

W20161206-10:47:00.920(2)? (STDERR) C:\Users\yoav\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20161206-10:47:00.921(2)? (STDERR)                                             throw(ex);
W20161206-10:47:00.921(2)? (STDERR)                                             ^
W20161206-10:47:00.923(2)? (STDERR)
W20161206-10:47:00.923(2)? (STDERR) **Error: %1 is not a valid Win32 application.**
W20161206-10:47:00.925(2)? (STDERR)
W20161206-10:47:00.925(2)? (STDERR) **\\?\c:\my-app\node_modules\google-cloud\node_modules\grpc\src\node\extension_binary\grpc_node.node**
W20161206-10:47:00.926(2)? (STDERR)     at Error (native)
W20161206-10:47:00.926(2)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20161206-10:47:00.927(2)? (STDERR)     at Module.load (module.js:343:32)
W20161206-10:47:00.927(2)? (STDERR)     at Function.Module._load (module.js:300:12)
W20161206-10:47:00.927(2)? (STDERR)     at Module.require (module.js:353:17)
W20161206-10:47:00.928(2)? (STDERR)     at require (internal/module.js:12:17)
W20161206-10:47:00.928(2)? (STDERR)     at Object.<anonymous> (c:\my-app\node_modules\google-cloud\node_modules\grpc\src\node\src\grpc_extension.js:38:15)
W20161206-10:47:00.929(2)? (STDERR)     at Module._compile (module.js:409:26)
W20161206-10:47:00.930(2)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20161206-10:47:00.930(2)? (STDERR)     at Module.load (module.js:343:32) 

there are barely any mentions of a problem such as this anywhere but i did find this thread - https://groups.google.com/forum/#!topic/grpc-io/ORodkdIZbVk
and a link to this  #3922 but it has been closed.

is there anything else i should be doing to avoid this issue?

thanks

**Comment by murgatroid99** [comment]
I notice that in the email thread you linked, the person got that error after copying the installed node modules from a non-Windows computer. If that's what happened here, then gRPC simply does not support that, and you should be able to fix it by running `npm rebuild --update-binary=grpc`.

If you did run the installation on Windows, the output from `npm install` would help determine what caused this problem.

**Comment by yoavniran** [comment]
thanks @murgatroid99 

I've installed the node modules only on Windows. using npm install

nevertheless, i did try the rebuild command you suggested with no luck.

Here's a link to my npm install output: https://drive.google.com/open?id=0B7X_fQwbj6SJQWVhaHk4ZWh5a1E

**Comment by murgatroid99** [comment]
OK, I have one more thing that might help figure out what's going on here: what output do you get if you run `npm install --update-binary=grpc -dd`?

**Comment by yoavniran** [comment]
think you meant: npm **rebuild** --update-binary=grpc -dd

here's the result: https://drive.google.com/open?id=0B7X_fQwbj6SJUm5zVVVVaWFaLWM

thanks!

**Comment by murgatroid99** [comment]
I can't reproduce the problem with Node using the same versions of everything. Maybe the problem is related to the fact that you're using Meteor. I don't really understand what Meteor is, internally, or how it's different from Node. But one thing I notice from the guide is that it expects you to use `meteor npm install ...`. I'm assuming that's what you did originally; what is the output when you do `meteor npm install --update-binary=grpc -dd`?

**Comment by yoavniran** [comment]
Meteor lets you develop hybrid apps for web/desktop/mobile
i dont really like how it overtakes everything the way it does but it wasnt my choice either (inherited this project) 😄 

In any case, heres the build log with running meteor npm...

https://drive.google.com/open?id=0B7X_fQwbj6SJQmNGQnZuS2RocWM

**Comment by murgatroid99** [comment]
The output in that log looks proper to me. Interestingly, one of the log lines says

> Running test command: `C:\Users\yoav\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin\node.exe --eval 'require(\'c:/Dropbox/my-app/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node\')'`

That should have verified that the binary you got was working correctly on your machine. If that command really does succeed, then it looks like Meteor fails to load the file, but its underlying Node executable succeeds at doing so.
