### ISSUE TITLE
grpc raise StatusCode.UNAVAILABLE while invoke a service with the same connection twice.

### ISSUE THREAD

**Issue by sc-syf** [grpc/grpc#8973]
I wrote a grpc service with python. I can get the correct result on the first invoke.

However,  while invoke the same grpc service twice,  I will get an exception:
> <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, {"created":"@1481021223.548072702","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14})>

system: ubuntu 14.04
python version: 2.7.6
grpcio version: 1.0.1

I used nghttpx for the proxy of grpc service. This is the config file of nghttpx:
`
http2-proxy=yes
frontend=0.0.0.0,6000;no-tls

backend=10.10.10.9,30401;;proto=h2;no-tls;
backend=10.10.10.9,30402;;proto=h2;no-tls;
backend=10.10.10.9,30403;;proto=h2;no-tls;
backend=10.10.10.9,30404;;proto=h2;no-tls;
`

while I start the server with debug log using "GRPC_TRACE=all GRPC_VERBOSITY=DEBUG",
after few seconds, I saw the fllowing debug info:
`
D1206 10:41:36.947737420   24342 tcp_posix.c:168]            read: error={"created":"@1481020896.947716810","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}
D1206 10:41:36.947769942   24342 parsing.c:98]               FLOW    parse: server stream[3] MOVE                                 parsing.incoming_window(65510) <-          global.unannounced_incoming_window_for_parse(65560) giving 131070
D1206 10:41:36.947783515   24342 chttp2_transport.c:459]     W:0x7fdb7c001240 close transport
D1206 10:41:36.947788092   24342 chttp2_transport.c:2127]    set connectivity_state=4
D1206 10:41:36.947798455   24342 connectivity_state.c:156]   SET: 0x7fdb7c003590 server_transport: READY --> SHUTDOWN [close_transport] error=0x7fdb7c006280 {"created":"@1481020896.947716810","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
D1206 10:41:36.947804297   24342 connectivity_state.c:183]   NOTIFY: 0x7fdb7c003e50
D1206 10:41:36.947840406   24342 chttp2_transport.c:2096]    R:0x7fdb7c001240 -> 0 ws=INACTIVE
`
Does this cause the problem ?   How can I fix it?  
Thanks for your reply.

p.s.  I've noticed that this problem is familar with  #7804 and #7278. But I wonder if they are the same problem.

**Comment by nathanielmanistaatgoogle** [comment]
I'm curious too. Are you able to share what code you have that reproduces this problem?

**Comment by sc-syf** [comment]
It's just some normal code.

the client snippet:
client.py
```
class EventClient:                                                               
    def __init__(self, host=''10.10.10.5', port=6000):                   
        """                                                                      
        init connection.                                                                     
        """                                                                      
        conn_str = '{}:{}'.format(host, port)                                    
        self.channel = grpc.insecure_channel(conn_str)                           
        self.stub = event_pb2.EventHandlerStub(self.channel)                     
                                                                                 
    def get_event(self, event_id):                                        
        event_resp = self.stub.get_event(event_pb2.EventRequest(event_id=event_id))
        return event_resp

```


the server side snippet:
server.py
```
from .imp_event import Event
from tornado.options import define, options
                                                                                                                                                    
define(type=int, default=50054, name="port")

class EventHandler(event_pb2.EventHandlerServicer):                              
    __metaclass__ = DecoMeta                                                                                  
                                                                                 
    def get_event(self, request, context):                                    
        '''                                                                      
        format all of event info.
        '''                                                                      
        self.imp_handler = Event()                                                   
        return self.imp_handler.get_event(request.event_id)

def serve():                                                                  
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))          
                                                                              
    event_pb2.add_EventHandlerServicer_to_server(EventHandler(), server) 
                                                                              
    options.parse_command_line()                                              
    server.add_insecure_port('[::]:{}'.format(options.port))                  
    server.start()                                                            
    try:                                                                      
      while True:                                                             
        time.sleep(186400)                                                    
    except KeyboardInterrupt:                                                 
      server.stop(0)                                                          
                                                                              
serve()
```

implement class: imp_event.py:
```
class Event:
    def __init__(self):
        pass

    def get_event(event_id):
    '''
    implement details, get event info.
    '''
        response = event_pb2.EventResponse()
        # do something right here.
        return response
```


put the client.py and event_pb2.py to client side.

the client side invoke snippet is:
views.py
```
from .client import EventClient

ec = EventClient()


def detail(request):
     # Here is the very invocation. while invoke this method twice, it will cause that exception.
     ec.get_event(requet.GET.get('event_id', 1))
```

some code is not posted cause it is not important.

@nathanielmanistaatgoogle  thanks.

**Comment by tatsuhiro-t** [comment]
As far as I know, "http2-proxy=yes" should not be used if nghttpx is used as a reverse proxy.

**Comment by nathanielmanistaatgoogle** [comment]
Is that as reduced as you are able to make the reproduction?

Are you able to reproduce the problem without the proxy in the middle?

**Comment by sc-syf** [comment]
@tatsuhiro-t  oh , you are right, "http2-proxy=yes" should only be used while backend is HTTP proxy server.  just as [nghttpx docs](https://www.nghttp2.org/documentation/nghttpx-howto.html?highlight=proxy#http-2-proxy-mode) said.

 Howerver, after I removed that line from config file of nghttpx and tested it again, the problem still exsits.

**Comment by sc-syf** [comment]
@nathanielmanistaatgoogle That is the point! It won't print any exception if I connect the service without the proxy.

I'm curious about the reason why the nghttpx proxy will cause that exception.

Is it a bug? or, I didn't  use the nghttpx as a grpc proxy correctly?

**Comment by tatsuhiro-t** [comment]
@sc-syf Could you provide us INFO level log of nghttpx  (-LINFO option will do) and its version?
And if this is purely nghttpx issue, it might be better to discuss it at https://github.com/nghttp2/nghttp2/issues

**Comment by sc-syf** [comment]
@tatsuhiro-t   I didn't see any info while use INFO level of nghttpx. 
the nghttpx version is nghttp2/1.17.0.
and I asked it again at https://github.com/nghttp2/nghttp2/issues/739
thanks.

**Comment by sc-syf** [comment]
as the discussion at https://github.com/nghttp2/nghttp2/issues/739 , there is no problem between nhgttpx and gRPC. I should not use a global gRPC connection which may cause problem after few minutes.
