### ISSUE TITLE
Requests are failing with status UNAVAILABLE

### ISSUE THREAD

**Issue by athei** [grpc/grpc#8974]
I am writing a p2p software using grpc. When testing I start all nodes in the same process. Therefore a lot of channels (sockets) are opened in the same process. Under some circumstances a lot of requests fail with status code UNAVAILABLE. 

I guess this happens because some system resource is exhausted (open files/sockets?). Is there a way to get more information whether this is some grpc internal limitation or some operating system limitation that prevents the successful request?

There should be a detail text in the grpc::Status object that provides me with more information (at least in debug mode).

This is with version 1.0.1 on macOS 10.12.1.

**Comment by nathanielmanistaatgoogle** [comment]
Are you able to run with `GRPC_VERBOSITY=DEBUG` and `GRPC_TRACE=ALL`?

**Comment by athei** [comment]
I did run it with `GRPC_VERBOSITY=DEBUG`. This is the sequence that pops up before a request fails:
```
I1207 10:57:18.575999000 123145534390272 subchannel.c:642] Connect failed: {"created":"@1481104638.575942000","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427,"os_error":"Timeout occurred","target_address":"ipv4:127.0.0.1:50051"}
I1207 10:57:18.576049000 123145534390272 subchannel.c:645] Retry immediately
I1207 10:57:18.576091000 123145534390272 subchannel.c:642] Connect failed: {"created":"@1481104638.575950000","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427,"os_error":"Timeout occurred","target_address":"ipv4:127.0.0.1:50051"}
I1207 10:57:18.576101000 123145534390272 subchannel.c:645] Retry immediately
I1207 10:57:18.576109000 123145534390272 subchannel.c:609] Failed to connect to channel, retrying
I1207 10:57:18.576203000 123145534390272 subchannel.c:609] Failed to connect to channel, retrying
```

All the nodes share one server with the IP `127.0.0.1:50051`. So the server is there. It may be overloaded or something?

I also ran the test program with tracing enabled. This yields a massive log file (35MB). I have attached it in compressed form. In my code I print out failed client requests with the error number. So grep for `(14)` to get to the places where the request failed.

I use the sync API for the server and the async API for the client. Currently I use 4 client threads each with their own completion queue. Thread sanitizer does not report any issues.

The trace file (1,5MB compressed):
https://cloud.theissen.io:14101/f/8e7e7ce024/?raw=1

**Comment by dgquintas** [comment]
Looking at the logs, it seems your intuition is correct: the system resources are exhausted. Look at log messages from "connectivity_state.c:156", eg (formatted for readability):
```
D1207 11:19:34.926607000 123145478201344 connectivity_state.c:156] 
SET: 0x10554a9d0 subchannel: CONNECTING --> TRANSIENT_FAILURE [connect_failed] 
error=0x1056473b0 
{
    "created": "@1481105974.926567000",
    "description": "Connect Failed",
    "file": "src/core/ext/client_config/subchannel.c",
    "file_line": 638,
    "referenced_errors": [
        {
            "created": "@1481105974.858292000",
            "description": "Failed to connect to remote host",
            "errno": 35,
            "file": "src/core/lib/iomgr/tcp_client_posix.c",
            "file_line": 186,
            "os_error": "Resource temporarily unavailable",
            "syscall": "getsockopt(SO_ERROR)",
            "target_address": "ipv4:127.0.0.1:50051"
        }
    ]
}
```
(btw, you can get traces of this kind by only specifying "connectivity_state" in the `GRPC_TRACE` env var. Using `all` is usually overkill, see [here](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)).

There's another issue at play here: Retries happen too eagerly. This has been recently fixed [see this PR](https://github.com/grpc/grpc/pull/8854). By waiting longer we prevent the avalanche effect that only compounds the problem of not having resources available.

The problem with appending the info you see in the traces to the Status is that it may get too verbose. Imagine a connection goes over 10 retries, succeeds, fails again and then the call times out. You then get a Status indicating the deadline exceeded failure (the higher level cause of the failure after all). Which information should be included? all 10+1+1 transitions of the connectivity? That being said, I believe @ncteisen is working on something that'd actually make it possible to fully trace the cause of a failure. For now though, there's the traces. 

@ncteisen is there an issue/description of the error tracing feature somewhere?

**Comment by ncteisen** [comment]
The channel tracing internal design doc is WIP, and should be done by the end of this quarter. Once it is finalized, I will publish it to Github. The implementation is going to occur next quarter.

**Comment by rajnkamr** [comment]
I got exactly same error for a single client ( not multi threaded).
what could be the issue?

GRPC:INFO [socket_utils_common_posix.c:<unk>:205] Disabling AF_INET6 sockets because ::1 is not available.
Mar 28 15:13:26 MaestrOS SysRepoSync.elf: 27266:GRPC:INFO [subchannel.c:<unk>:642] Connect failed: {"created":"@1490732006.164787096","description":"Failed to connect to remote host","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427,"os_error":"Timeout occurred","target_address":"ipv4:10.64.156.72:35128"}

**Comment by dgquintas** [comment]
@rajnkamr is there a (responsive) server listening at 10.64.156.72:35128?

**Comment by rajnkamr** [comment]
Yes server is listening on 35128.I got another error with loopback and 35128
GRPC:INFO [socket_utils_common_posix.c:<unk>:205] Disabling AF_INET6 sockets because ::1 is not available.

GRPC:ERRO [chttp2_transport.c:<u[DBG] Thread id=140737308677888 signaled.490924672.415574602","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}

**Comment by ncteisen** [comment]
Is this still relevant?
