### ISSUE TITLE
Bad performance for large message transter

### ISSUE THREAD

**Issue by llhe** [grpc/grpc#8975]
TensorFlow use gRPC to [transfer tensor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/worker_service.proto#L58), and the tensor can be very large (over 100MB or even GB). One performance bottleneck is found in this RPC call with large tensors, see https://github.com/tensorflow/tensorflow/issues/6116.

Since gRPC is designed mainly for latency and qps (and also multi-tenancy fairness since just one slice is processed each time?), is there an approach to optimize the throughput? If I understand the code correctly, changing  'gpr_slice_buffer_take_first' to 'gpr_slice_buffer_take_all' in [slice_buffer.c](https://github.com/grpc/grpc/blob/d7ff4ff40071d2b486a052183e3e9f9382afb745/src/core/lib/support/slice_buffer.c#L274) and increase the slice size can improve the throughput?

**Comment by ctiller** [comment]
I left a comment on https://github.com/tensorflow/tensorflow/issues/6116.

I think the right approach is to keep track of the next slice to return in `grpc_chttp2_incoming_byte_stream`, and have that code cope with having some invalid elements at the head of the array... changing:

```c
*bs->next_action.slice = grpc_slice_buffer_take_first(&bs->slices);
```

into something more like:

```c
*bs->next_action.slice = bs->slices[bs->next_slice_to_take];
bs->slices[bs->next_slice_to_take] = grpc_empty_slice();
bs->next_slice_to_take++;
```

@sreecha @lyuxuan - do either of you want to take a stab at this?

**Comment by ctiller** [comment]
@sreecha has an experimental fix with #9102

**Comment by sreecha** [comment]
@llhe , Would you be able to test this again with my fix at #9102  ?

**Comment by llhe** [comment]
@sreecha Thanks for the fix!
I integrated this fix to the latest tensorflow code here: https://github.com/llhe/tensorflow/tree/grpc-fix. And make the same profiling, the issue is gone.

**Comment by sreecha** [comment]
@llhe , Thank you for testing with the patch. I will be merging my change soon.

**Comment by ctiller** [comment]
I believe this has been fixed?
