### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ustime** [grpc/grpc#8976]
using openssl, not boringssl

src/core/lib/security/credentials/jwt/jwt_verifier.c: In function ‘pkey_from_jwk’:
src/core/lib/security/credentials/jwt/jwt_verifier.c:483:10: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
       rsa->n = bignum_from_base64(validate_string_field(key_prop, "n"));
          ^~
Makefile:2254: recipe for target '/home/grpc/objs/opt/src/core/lib/security/credentials/jwt/jwt_verifier.o' failed
make: *** [/home/grpc/objs/opt/src/core/lib/security/credentials/jwt/jwt_verifier.o] Error 1

**Comment by sgleizes** [comment]
This seems to be a duplicate of #8801.

Looking forward to this issue being fixed. Is there any way to force grpc to use the bundled version (1.0.2f) of openssl?

**Comment by ustime** [comment]
should use getter/setter interface instead of direct member refs. anyone can fix it?

**Comment by sgleizes** [comment]
If that can help anyone, on our side we ended up falling back to using `libssl1.0-dev` (on debian) so that grpc would compile.
However it is meant as a transition package and supporting openssl 1.1.x is still an open issue.

**Comment by mehrdada** [comment]
Closing as a duplicate of issues 8801 and 10589.
