### ISSUE TITLE
ruby client, node server timeout on sleeping server, 

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#8989]
In the ruby client to node server "timeout_on_sleeping_server" interop test, the client sometimes receives a `Cancelled` status instead of `DeadlineExceeded` status. 

This happens frequently on jenkins interop tests. (one log in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/9915/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/)

It seems related to https://github.com/grpc/grpc/issues/53

So far this seems to only be reproducible when running interop tests similarly to how they're run on jenkins, e.g.: `tools/run_tests/run_interop_tests.py -l ruby -s node --cloud_to_prod --cloud_to_prod_auth --use_docker --http2_interop -t -j 12`

**Comment by dgquintas** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_interop_master/9444/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by ericgribkoff** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_interop_master/lastCompletedBuild/testReport/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by jtattermusch** [comment]
Seen again:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10072/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by apolcyn** [comment]
another failure in:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/9984/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by dgquintas** [comment]
@ctiller is there a story for fixing this?

**Comment by y-zeng** [comment]
Seen again:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10150/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by soltanmm-google** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_interop_master/9619/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

Ain't this buildpony thing fun?

**Comment by matt-kwong** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_interop_master/9636/testReport/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10267/

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/9984/testReport/junit/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by apolcyn** [comment]
also seen in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10279/testReport/(root)/tests/cloud_to_cloud_ruby_node_server_timeout_on_sleeping_server/

**Comment by nathanielmanistaatgoogle** [comment]
Seen in `gRPC_interop_master` builds

* [10097](https://grpc-testing.appspot.com/job/gRPC_interop_master/10097/)
* [10107](https://grpc-testing.appspot.com/job/gRPC_interop_master/10107/)
* [10108](https://grpc-testing.appspot.com/job/gRPC_interop_master/10108/testReport/)
* [10111](https://grpc-testing.appspot.com/job/gRPC_interop_master/10111/)

**Comment by ctiller** [comment]
I have some error handling cleanup work in #9111 that I'd like to land before starting to address this.

**Comment by apolcyn** [comment]
seen again in https://github.com/grpc/grpc/pull/9322

**Comment by makdharma** [comment]
Seen again in #9458
