### ISSUE TITLE
node: update to protobufjs 6

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#8991]
Protobufjs 6.0 has been released, and GRPC needs to be updated.

cc @murgatroid99

**Comment by paralin** [comment]
Major changes relevant to grpc:

 - No constructors anymore for messages, instead there are static `encode` and `decode` functions.
 - loadObject and build do not work the same way. We can't do a `loadObject` tree anymore. I looked into writing a compatibility layer for it but implementing all of the encode and decode functions seems like an unnecessary overhead.

I think some redesign decisions might need to be made here to make the switch sucessfully.

**Comment by paralin** [comment]
@murgatroid99

**Comment by pcarrier** [comment]
There's loads of code to support protobufjs 6 but it is broken today. Figured I'd save others a lot of time, so here goes:

If you see this error:
```
Error: Failed to parse server response
```

You might find that `deserializeCls` in `protobuf_js_6_common.js` calls `toObject` which does not exist on the value returned by `cls.decode(arg_buf)`.

**Comment by paralin** [comment]
@pcarrier afaik this issue should be closed, support was merged: https://github.com/grpc/grpc/pull/10204

Can you please open a new issue @pcarrier and cc @murgatroid99 and me? Thanks!
