### ISSUE TITLE
panic: interface conversion: *flatbuffers.Builder is not proto.Message: missing method ProtoMessage

### ISSUE THREAD

**Issue by zplzpl** [grpc/grpc#8992]
I was using flatbuffers as a serialization mode, but this exception occurred while compiling.

`

panic: interface conversion: *flatbuffers.Builder is not proto.Message: missing method ProtoMessage

goroutine 1 [running]:
panic(0x89bc80, 0xc08218e0c0)
	E:/Go1.6.2/src/runtime/panic.go:481 +0x3f4
google.golang.org/grpc.protoCodec.Marshal(0x92e2c0, 0xc0820fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	E:/goapp/src/google.golang.org/grpc/rpc_util.go:70 +0x78
google.golang.org/grpc.(*protoCodec).Marshal(0xbd43c8, 0x92e2c0, 0xc0820fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:34 +0xc5
google.golang.org/grpc.encode(0x3a0268, 0xbd43c8, 0x92e2c0, 0xc0820fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	E:/goapp/src/google.golang.org/grpc/rpc_util.go:268 +0xbb
google.golang.org/grpc.sendRequest(0x3a01b8, 0xc08200a278, 0x3a0268, 0xbd43c8, 0x0, 0x0, 0xc0820f34a0, 0x3a1670, 0xc0821583c0, 0x92e2c0, ...)
	E:/goapp/src/google.golang.org/grpc/call.go:117 +0x232
google.golang.org/grpc.invoke(0x3a01b8, 0xc08200a278, 0x99f660, 0x1c, 0x92e2c0, 0xc0820fc4e0, 0x8c8740, 0xc08214ee00, 0xc0821066c0, 0x0, ...)
	E:/goapp/src/google.golang.org/grpc/call.go:235 +0xd81
google.golang.org/grpc.Invoke(0x3a01b8, 0xc08200a278, 0x99f660, 0x1c, 0x92e2c0, 0xc0820fc4e0, 0x8c8740, 0xc08214ee00, 0xc0821066c0, 0x0, ...)
	E:/goapp/src/google.golang.org/grpc/call.go:143 +0x14a
_/e_/goproject/rpc-test-client/src/message.(*messageServiceClient).Send(0xc0820f4220, 0x3a01b8, 0xc08200a278, 0xc0820fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	e:/goproject/rpc-test-client/src/message/MessageService_grpc.go:31 +0x17b
main.main()
	e:/goproject/rpc-test-client/src/app.go:67 +0x3cc
`

**Comment by pavamana1123** [comment]
Found answer for this? Me to having similar problem with protoBuffers.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please open the issue under `grpc-go` repository as it only affects the Go implementation with information on how to reproduce. Thanks!

**Comment by CMajeri** [comment]
We hit the same issue as @zplzpl @pavamana1123. Our problem was with the flatbuffer codec, or rather, the fact that we didn't instantiate the server with it.

When creating our server and connections, we switched to 
```go
var server = grpc.NewServer(grpc.CustomCodec(flatbuffers.FlatbuffersCodec{}))
var conn, err = grpc.Dial(addr, grpc.WithInsecure(), grpc.WithCodec(flatbuffers.FlatbuffersCodec{}))
```
I recommend going through the flatbuffers grpc go test.
The master's head test doesn't build at the time of writing, so you should checkout an earlier commit like  https://github.com/google/flatbuffers/commit/cc8424009853447b209c5d3ccb12c23a2f134fa4

In hope that this helps. 
It should at least provide some reference for anyone searching for this issue.
