### ISSUE TITLE
Instructions for building from source (PHP) fail. 

### ISSUE THREAD

**Issue by EwanValentine** [grpc/grpc#8993]
I'm running the build from source instructions in Docker (Alpine), clone, clones the repo in a detached head state. If I alter the command to checkout master, that works. However I get an error on build... 

```
src/core/lib/support/cpu_linux.c: In function 'gpr_cpu_current_cpu':
src/core/lib/support/cpu_linux.c:70:13: error: implicit declaration of function 'sched_getcpu' [-Werror=implicit-function-declaration]
   int cpu = sched_getcpu();
             ^
cc1: all warnings being treated as errors
Makefile:2079: recipe for target '/defs/grpc/objs/opt/src/core/lib/support/cpu_linux.o' failed
make: *** [/defs/grpc/objs/opt/src/core/lib/support/cpu_linux.o] Error 1
```

**Comment by murgatroid99** [comment]
I'm sorry, but the gRPC C core, and libraries build on it (including the PHP library) currently do not support Alpine Linux. See #8899.

**Comment by EwanValentine** [comment]
Gotcha! Will try a different container, cheers!
