### ISSUE TITLE
Why does gRPC ignore exceptions raised by metadata plugins?

### ISSUE THREAD

**Issue by theacodes** [grpc/grpc#8994]
Encountered this issue when accidentally using `google.oauth2.service_account.Credentials` without specifying scopes. The auth metadata plugin raises a `RefreshError` and seemingly catches it and then ignores it. The application then hangs.

```
Exception ignored in: 'grpc._cython.cygrpc.plugin_get_metadata'
Traceback (most recent call last):
  File ".../python3.5/site-packages/grpc/_plugin_wrapping.py", line 107, in __call__
    wrapped_context, AuthMetadataPluginCallback(wrapped_cygrpc_callback))
  File ".../python3.5/site-packages/google/auth/transport/grpc.py", line 61, in __call__
    callback(self._get_authorization_headers(), None)
  File ".../python3.5/site-packages/google/auth/transport/grpc.py", line 47, in _get_authorization_headers
    self._credentials.refresh(self._request)
  File ".../python3.5/site-packages/google/oauth2/service_account.py", line 313, in refresh
    request, self._token_uri, assertion)
  File ".../python3.5/site-packages/google/oauth2/_client.py", line 143, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File ".../python3.5/site-packages/google/oauth2/_client.py", line 109, in _token_endpoint_request
    _handle_error_response(response_body)
  File ".../python3.5/site-packages/google/oauth2/_client.py", line 59, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Empty or missing scope not allowed.', '{\n  "error" : "invalid_scope",\n  "error_description" : "Empty or missing scope not allowed.",\n')
```

**Comment by nathanielmanistaatgoogle** [comment]
Good question and definitely worth looking into. How would you describe this issue's severity? This is a case of "gRPC Python can more helpfully handle the application having made a programming mistake", isn't it? If so this issue isn't blocking any principal work on your part, right?

**Comment by jonparrott** [comment]
I'd say it's pretty serious since the exception doesn't bubble and the application hangs indefinitely.

**Comment by soltanmm-google** [comment]
If I recall correctly, metadata plugins end up called by the C core, potentially asynchronously.

It's possible that we could wrap the metadata plugins with a fresh object + try/except that sets a stateful flag and pedantically check that flag for every object that transitively touches that wrapper.

**Comment by soltanmm-google** [comment]
Alternatively we can document that users should do that themselves and do failure-callbacks of some kind. But then I don't know how able they'd be to kill off gRPC resources from outside of the library proper.

**Comment by apolcyn** [comment]
Linking this to https://github.com/grpc/grpc/issues/8110 as it looks like the same issue

**Comment by jonparrott** [comment]
> Alternatively we can document that users should do that themselves and do failure-callbacks of some kind. But then I don't know how able they'd be to kill off gRPC resources from outside of the library proper.

I'm not intimately familiar with gRPC's implementation or error handling, but I don't feel like users should need to do anything else for errors from metadata plugins to propagate.

Even if gRPC raises a *different* error when making an RPC where the metadata plugin raises an error that's still better than what happens now (the application hangs).
