### ISSUE TITLE
Performance test failing for no obvious reason

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#8997]
Jenkins output shows "SUCCESS: all tests passed" followed by "FAILED: local_build". Does not make sense.

ref:
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/7844/consoleFull

**Comment by matt-kwong** [comment]
It looks like #8969 might fix this issue. I'll look into this issue if this PR doesn't resolve it.

**Comment by matt-kwong** [comment]
https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_master/8430/ - one build passing :). I'll watch over performance tests for a while before closing this issue.

**Comment by muxi** [comment]
Cool thanks.

**Comment by vjpai** [comment]
This shouldn't be related to #8969. It's a Jenkins issue. @nicolasnoble had some comments about this in our chat yesterday.

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [pull request 9156](https://github.com/grpc/grpc/pull/9156) against `v1.0.x`.

**Comment by apolcyn** [comment]
seen again in PR  https://github.com/grpc/grpc/pull/8304
log in https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/8458/console
