### ISSUE TITLE
Make grpc_http2_(encode|decode)_timeout string safe

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#9000]
src/core/lib/transport/timeout_encoding.c

For encoding, nothing ensures the buffer has enough space. The spec says that there need be only 10 bytes, since 8 digits + unit specifier + NUL = 10. Instead, take a `size_t *` argument taking the buffer initial size and returning the used quantity. This ensures you don't write off the end of the world.

For decoding, the source data may simply be a buffer and size, and may contain `NUL`s and other garbage. If you passed both arguments, you could early out if the size > 11, else correctly handle said embedded `NUL`s without requiring the caller to do an explicit `strlen` vs size check.

**Comment by ctiller** [comment]
I've got some changes in flight that turn decode into taking a grpc_slice, which should improve that part of the path.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are it looks like this might be fixed already (or have a fix in flight). Please re-open the issue if you continue to experience this—with information on how to reproduce.
