### ISSUE TITLE
Infrastructure flake on asan master

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9001]
https://grpc-testing.appspot.com/job/gRPC_master_asanitizer_c/338/console

**Comment by matt-kwong** [comment]
This was an issue where the repo cache wasn't updated to reflect the change in name of google_benchmark to benchmark. I updated the repo cache on all the workers yesterday afternoon and I don't see any flakes since then on any of the masters, so this shouldn't happen again.
