### ISSUE TITLE
linux/dbg: json_run_localhost timeout

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9007]
`c++_linux_dbg.bins/dbg/json_run_localhost --scenarios_json '{"scenarios": [{"name": "cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure", "warmup_seconds": 0, "benchmark_seconds": 1, "num_servers": 1, "server_config": {"async_server_threads": 0, "core_limit": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "SYNC_SERVER"}, "num_clients": 0, "client_config": {"client_type": "ASYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "client_channels": 64, "async_client_threads": 0, "outstanding_rpcs_per_channel": 100, "rpc_type": "STREAMING", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}}]}' GRPC_POLL_STRATEGY=poll-cv`

https://gist.githubusercontent.com/dgquintas/81d81ad215048fe43a473ed7434b9c76/raw/7fa9401c238c1d1f9ba2b5f913e4784b3fbf0199/gistfile1.txt

**Comment by ericgribkoff** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_master_linux/739/testReport/junit/(root)/aggregate_tests/run_tests_c___linux_dbg/

**Comment by jtattermusch** [comment]
Seen again:
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1399/

**Comment by y-zeng** [comment]
Seen again:
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1501/testReport/

**Comment by markdroth** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1523/

**Comment by dgquintas** [comment]
Duplicate of #9150
