### ISSUE TITLE
c_macos_dbg.bins/dbg/h2_census_nosec_test shutdown_finishes_calls

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#9012]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/1260/testReport/junit/(root)/c_macos_dbg/bins_dbg_h2_census_nosec_test_shutdown_finishes_calls/

**Comment by dgquintas** [comment]
Hasn't happened in a while, closing
