### ISSUE TITLE
protoc-gen-php version

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#9017]
Following the directions here http://www.grpc.io/docs/quickstart/php.html#install-protobuf-php the output of protoc-gen-php is

```
Protobuf-PHP 1.0 by Ivan -DrSlump- Montes
```

Is this correct?

I'm asking because I ran `protoc-gen-php -i . -o . myservice.proto` on a proto3 file with a service definition and message definition but the output `.php` file only had the message, not the service code.

**Comment by jrots** [comment]
I'm also experiencing this issue.. + following documentation and  trying to run examples you'll get errors of outdated proto files.. 
https://github.com/grpc/grpc/tree/v1.0.0/src/php
/opt/code/rpc_examples/grpc/src/php/bin# ./generate_proto_php.sh
Protobuf-PHP 1.0 by Ivan -DrSlump- Montes

--php_out: math.proto: Can only generate PHP code for proto3 .proto files.
Please add 'syntax = "proto3";' to the top of your .proto file.

.proto: Can only generate PHP code for proto3 .proto files.
Please add 'syntax = "proto3";' to the top of your .proto file.

**Comment by jrots** [comment]
after further looking, looks like 3.1 of protoc is incompatible with protoc-gen-php. https://github.com/grpc/grpc/issues/8502#issuecomment-256231119.. will try do downgrade to 3.0 and run it again.

**Comment by jrots** [comment]
tested and fixes the issue : protoc --version
libprotoc 3.0.0
I get a generated file now with client/ request/ response classes in it.

**Comment by stanley-cheung** [comment]
Sorry this is a confusing time period where we are switching between proto implementation

Current state: v1.0.1 is released. It uses the DrSlump fork. It only works for proto2 files.

Future (hopefully not long) state: v1.1 is going to be released (hopefully) soon. That is going to use the official google/protobuf proto3 implementation. That is what you will find on the `master` (but unreleased) branch.

**Comment by stanley-cheung** [comment]
gRPC 1.1.0 has been released and so is the PHP PECL extension and composer package. This release marks our switch to use the official google/protobuf Proto3 implementation, and hence the use of the Drslump fork (stanley-cheung/Protobuf-PHP) will soon be deprecated and no longer supported. 

Please install protoc 3.1.0+ (even better with 3.2.0+) to use the new code generator to generate stub classes.
