### ISSUE TITLE
GRPC C++ Unary Async performance

### ISSUE THREAD

**Issue by Dustskyfield** [grpc/grpc#9021]
Hi,

I am measuring GRPC (C++) performance to consider it for a heavily chatty application.

My environment is something like this:

Both Client and Server are processes running on a 1.2GHz server with 24 cores.
Client and Server talk asynchronously over Unix Domain sockets
I measured the performance using  qps async calls, where Client sends 1000 rpcs before waiting for  response to send rpc again. 

I measured the tps only 50k in grpc server when i send 1000 bytes and reply 1000 bytes.

Is 50K/sec the max I can get? Do we have any performance data for GRPC?

I am looking for atleast 150K  unary  rpcs per second in the environment described above.

Thanks,
Surya

**Comment by Dustskyfield** [comment]
Attaching the snippets of server and client used to test the performance.
by the way, we use gprc 3.0.1 version.
[grpc_benchmark_client.cc.txt](https://github.com/grpc/grpc/files/641188/grpc_benchmark_client.cc.txt)
[grpc_benchmark_server.cc.txt](https://github.com/grpc/grpc/files/641189/grpc_benchmark_server.cc.txt)
[client.h.txt](https://github.com/grpc/grpc/files/641190/client.h.txt)

**Comment by tbillington** [comment]
Have you tried streaming?

Also https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5685265389584384 from http://www.grpc.io/docs/guides/benchmarking.html.

**Comment by ctiller** [comment]
We measure about 50kqps per core currently: to get more, you need more than one completion queue in the server (and more than one channel). With one CQ per thread (and one thread per core) we see linear scaling.

A large focus for us this year will be trying to push per-core performance higher: I've a strong belief that we'll see 150-200kqps/core by EOY.
