### ISSUE TITLE
Php: Documentation for errors

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#9023]
Where can I find documentation for php grpc?

Information like the errors, grpc constants etc.

The grpc.io reference page here http://www.grpc.io/docs/reference/ points to php docs that are nearly empty, no info on errors/constants/services or anything. Seems to be missing a lot of things that are probably implemented in the c extension?

**Comment by ZhouyihaiDing** [comment]
I'll start writing docs about the class like Channel and error codes which implement in c extension, or extract the comment from codes directly and update into [grpc.io php API](https://grpc.io/grpc/php/namespace-Grpc.html).

**Comment by ZhouyihaiDing** [comment]
dup of #8859.
