### ISSUE TITLE
can i get channel/stub from ServerContext if i want to make a reverse(server->client) call?

### ISSUE THREAD

**Issue by w359405949** [grpc/grpc#903]
pubsub server or chatroom need this.

**Comment by ctiller** [comment]
Calls are only made from client to server. The way to get the behavior you
want is to make a server streaming or bidi streaming call from the client
and send messages from the server.

**Comment by w359405949** [comment]
ok, how to "make a server streaming or bidi streaming call from the client and send messages from the server".
examples could be better.

**Comment by ctiller** [comment]
Take a look at ListFeatures and RouteChat in the C++ tutorial on grpc/grpc-common: https://github.com/grpc/grpc-common/blob/master/cpp/cpptutorial.md.

ListFeatures is a server side stream, and RouteChat is a bidi stream.
