### ISSUE TITLE
Unable to compile proto: cpp grpc proto compiler plugin does not work with generic services.

### ISSUE THREAD

**Issue by clu-pei-dae** [grpc/grpc#9032]
Hi,

I'm trying to compile my proto files (which used to compiled without any error 2 weeks before). Now I'm getting the following error message:

`PS C:\Users\MyUser\Documents\git\protobuf\vsproject\Release> protoc -I src --cpp_out=out/ --grpc_out=out/ --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe .\src\TestService.proto`
`--grpc_out: TestService.proto: cpp grpc proto compiler plugin does not work with generic services. To generate cpp grpc APIs, please set "cc_generic_service = false".
`

I actually set the 
` option cc_generic_services = false;`
line, but it's being ignored.

I compiled protobuf and grpc with Visual Studio 2015 @ Windows Server 2012 R2.
Is this a bug or was there any change in the grpc protoc-plugin that leads to this error message?

**Comment by boschb** [comment]
I am also getting this.  have you found a solution?

**Comment by Rikorose** [comment]
I get this error following the [compile instructions](https://github.com/grpc/grpc/blob/master/INSTALL.md) for linux.

**Comment by patricia93sousa** [comment]
I solve this problem installing [protobuffers](https://github.com/google/protobuf/blob/master/src/README.md) . I use the folder grpc/third-party/protobuf.

Hope this helps.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to reproduce this issue with the current information. If you are still experiencing this issue on current versions of `protoc` and `grpc`, please re-open the issue with information on how to reproduce.

**Comment by huuson235** [comment]
Have anyone solved this problem? I can not install gRPC.
```bash
[PROTOC]  Generating protobuf CC file from src/proto/grpc/health/v1/health.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/health/v1/health.proto
--grpc_out: src/proto/grpc/health/v1/health.proto: cpp grpc proto compiler plugin does not work with generic services. To generate cpp grpc APIs, please set "cc_generic_service = false".
Makefile:2266: recipe for target '/home/huuson235/lib-src/grpc/gens/src/proto/grpc/health/v1/health.grpc.pb.cc' failed
make: *** [/home/huuson235/lib-src/grpc/gens/src/proto/grpc/health/v1/health.grpc.pb.cc] Error 1
```

**Comment by tunnuz** [comment]
Same here.

**Comment by huuson235** [comment]
I've just solved this problem. Deleting all libprotobuf and then re-install protobuf. I think the reason that there is 2 or more versions of libprotobuf in my computer.
```bash
sudo rm -rf /usr/local/lib/libprotobuf*
sudo rm -rf /usr/lib/libprotobuf*
sudo rm -rf /usr/local/bin/protoc
sudo rm -rf /usr/bin/protoc
```
After cleaning, reinstall protobuf and install gRPC.
**If you were not sure, let rename or move old libprotobuf* to backup folder**
Good luck
