### ISSUE TITLE
Generated default handlers in Ruby services have the wrong names

### ISSUE THREAD

**Issue by igorpeshansky** [grpc/grpc#9033]
Default handlers in Ruby are added with the verbatim rpc name (*CamelCase*), which is not what the code in `grpc/rpc_server.rb` (`add_rpc_descs_for`) expects (i.e., *snake_case*). This means that when implementing a test service stub, one has to provide all of the *snake_case* rpc method implementations, instead of being able to rely on the default `UNIMPLEMENTED` failure.

**Comment by apolcyn** [comment]
Thanks for the fix.

Just to be clear on the issue, the method names in the base class, which were to be overridden by the generated stub or by the service implementation, were created with their camel case names rather than snake case.

**Comment by igorpeshansky** [comment]
Hi. Has this been released? If not, is there an ETA? Thanks.
