### ISSUE TITLE
Question: C++ server interceptor

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#9035]
Hi,

Are there any plans to support interceptors in C++? It looks like they are supported in GO. 

On a related noted, does the server support rate limiting support per IP or is this functionality expected to be built at application level? If application level, interceptors would be handy here.

Thanks
Arpit

**Comment by distributed** [comment]
Are there any news on this?

I'm looking to trace/log all API calls to a C++ gRPC server, and I haven't found out how to do it, lacking interceptors, c.f. http://stackoverflow.com/questions/42345694/trace-all-rpc-calls-in-c-grpc-server

**Comment by sgleizes** [comment]
I haven't found any way of properly intercepting the method, latency, request/response of each RPC with the C++ API.

This feature would be highly useful for logging, monitoring, automatic retry on client-side, you name it.

**Comment by tudor** [comment]
Is there an update on this? I (and presumably many more people interested in the OpenTracing ecosystem) are looking forward to this (and client interceptors as well).

**Comment by gleocadie** [comment]
Hello there, I'm also interested in that feature. Do you have any info ?

**Comment by AndreFrelicot** [comment]
It seems that it is implemented in the experimental namespace :

https://github.com/grpc/grpc/blob/7bf82de9eda0aa8fecfe5edb33834f1b272be30b/test/cpp/end2end/server_interceptors_end2end_test.cc

Why not close this issue ?

**Comment by vjpai** [comment]
It is indeed implemented under experimental with a hope of moving this to non-experimental in the near future. @yashykt - can you give any further input on this?

**Comment by yashykt** [comment]
Yes, it is implemented under experimental. Currently, we are still in the phase of receiving feedback so the API might see some change.

But, this issue should be closed
