### ISSUE TITLE
c_windows_opt.vsprojects/Release/h2_http_proxy_nosec_test.exe hpack_size

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9037]
https://grpc-testing.appspot.com/job/gRPC_pr_win/1228/testReport/junit/(root)/c_windows_opt/vsprojects_Release_h2_http_proxy_nosec_test_exe_hpack_size/

D1206 07:24:50.103000000 10888 test_config.c:290] test slowdown: machine=1.000000 build=1.000000 poll=1.000000 total=1.000000

I1206 07:24:50.104000000 10888 hpack_size.c:197] test_size:e=4096:d=4096/chttp2/fullstack

I1206 07:24:50.113000000 10888 http_proxy.c:428] Proxy address: localhost:2514

I1206 07:24:50.118000000 14724 http_connect_handshaker.c:273] Connecting to server localhost:2513 via HTTP proxy localhost:2514

I1206 07:24:50.174000000 14724 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009090.174000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.175000000 10888 hpack_size.c:197] test_size:e=4096:d=0/chttp2/fullstack

I1206 07:24:50.175000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009090.175000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.179000000 10888 http_proxy.c:428] Proxy address: localhost:2516

I1206 07:24:50.183000000 13020 http_connect_handshaker.c:273] Connecting to server localhost:2515 via HTTP proxy localhost:2516

I1206 07:24:50.248000000 13020 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009090.248000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.248000000 10888 hpack_size.c:197] test_size:e=4096:d=100/chttp2/fullstack

I1206 07:24:50.248000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009090.248000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.252000000 10888 http_proxy.c:428] Proxy address: localhost:2520

I1206 07:24:50.256000000 11104 http_connect_handshaker.c:273] Connecting to server localhost:2519 via HTTP proxy localhost:2520

I1206 07:24:50.339000000 11104 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009090.339000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.339000000 10888 hpack_size.c:197] test_size:e=4096:d=1000/chttp2/fullstack

I1206 07:24:50.340000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009090.340000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.344000000 10888 http_proxy.c:428] Proxy address: localhost:2528

I1206 07:24:50.350000000 14664 http_connect_handshaker.c:273] Connecting to server localhost:2527 via HTTP proxy localhost:2528

I1206 07:24:50.438000000 14664 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009090.438000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.439000000 10888 hpack_size.c:197] test_size:e=4096:d=32768/chttp2/fullstack

I1206 07:24:50.439000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009090.439000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.458000000 10888 http_proxy.c:428] Proxy address: localhost:2542

I1206 07:24:50.462000000 10236 http_connect_handshaker.c:273] Connecting to server localhost:2541 via HTTP proxy localhost:2542

I1206 07:24:50.556000000 10236 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009090.556000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.557000000 10888 hpack_size.c:197] test_size:e=4096:d=4194304/chttp2/fullstack

I1206 07:24:50.557000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009090.557000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.562000000 10888 http_proxy.c:428] Proxy address: localhost:2550

I1206 07:24:50.567000000  9388 http_connect_handshaker.c:273] Connecting to server localhost:2549 via HTTP proxy localhost:2550

I1206 07:24:50.653000000  9388 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009090.653000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:50.653000000  9388 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009090.653000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:51.653000000 10888 hpack_size.c:197] test_size:e=0:d=4096/chttp2/fullstack

I1206 07:24:51.656000000 10888 http_proxy.c:428] Proxy address: localhost:2576

I1206 07:24:51.661000000  6896 http_connect_handshaker.c:273] Connecting to server localhost:2575 via HTTP proxy localhost:2576

I1206 07:24:51.753000000  5188 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009091.753000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:51.754000000  5188 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009091.754000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:52.754000000 10888 hpack_size.c:197] test_size:e=0:d=0/chttp2/fullstack

I1206 07:24:52.758000000 10888 http_proxy.c:428] Proxy address: localhost:2615

I1206 07:24:52.765000000 14792 http_connect_handshaker.c:273] Connecting to server localhost:2614 via HTTP proxy localhost:2615

I1206 07:24:52.838000000 18224 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009092.838000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:52.838000000 10888 hpack_size.c:197] test_size:e=0:d=100/chttp2/fullstack

I1206 07:24:52.838000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009092.838000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:52.844000000 10888 http_proxy.c:428] Proxy address: localhost:2617

I1206 07:24:52.850000000 12464 http_connect_handshaker.c:273] Connecting to server localhost:2616 via HTTP proxy localhost:2617

I1206 07:24:52.941000000 12464 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009092.941000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:52.941000000 10888 hpack_size.c:197] test_size:e=0:d=1000/chttp2/fullstack

I1206 07:24:52.941000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009092.941000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:52.944000000 10888 http_proxy.c:428] Proxy address: localhost:2619

I1206 07:24:52.949000000 15512 http_connect_handshaker.c:273] Connecting to server localhost:2618 via HTTP proxy localhost:2619

I1206 07:24:53.036000000 15512 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009093.036000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:53.036000000 10888 hpack_size.c:197] test_size:e=0:d=32768/chttp2/fullstack

I1206 07:24:53.036000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009093.036000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:53.040000000 10888 http_proxy.c:428] Proxy address: localhost:2621

I1206 07:24:53.045000000  6468 http_connect_handshaker.c:273] Connecting to server localhost:2620 via HTTP proxy localhost:2621

I1206 07:24:53.121000000  6468 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009093.121000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:53.121000000  6468 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009093.121000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:54.121000000 10888 hpack_size.c:197] test_size:e=0:d=4194304/chttp2/fullstack

I1206 07:24:54.125000000 10888 http_proxy.c:428] Proxy address: localhost:2627

I1206 07:24:54.132000000 13396 http_connect_handshaker.c:273] Connecting to server localhost:2626 via HTTP proxy localhost:2627

I1206 07:24:54.212000000 18692 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009094.212000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:54.212000000 18692 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009094.212000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:55.212000000 10888 hpack_size.c:197] test_size:e=100:d=4096/chttp2/fullstack

I1206 07:24:55.224000000 10888 http_proxy.c:428] Proxy address: localhost:2645

I1206 07:24:55.230000000  9896 http_connect_handshaker.c:273] Connecting to server localhost:2644 via HTTP proxy localhost:2645

I1206 07:24:55.304000000 11772 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009095.304000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:55.304000000 10888 hpack_size.c:197] test_size:e=100:d=0/chttp2/fullstack

I1206 07:24:55.304000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009095.304000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:55.308000000 10888 http_proxy.c:428] Proxy address: localhost:2647

I1206 07:24:55.312000000  4400 http_connect_handshaker.c:273] Connecting to server localhost:2646 via HTTP proxy localhost:2647

I1206 07:24:55.373000000  4400 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009095.373000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:55.373000000  4400 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009095.373000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.373000000 10888 hpack_size.c:197] test_size:e=100:d=100/chttp2/fullstack

I1206 07:24:56.377000000 10888 http_proxy.c:428] Proxy address: localhost:2653

I1206 07:24:56.384000000 19964 http_connect_handshaker.c:273] Connecting to server localhost:2652 via HTTP proxy localhost:2653

I1206 07:24:56.471000000 15716 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009096.471000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.472000000 10888 hpack_size.c:197] test_size:e=100:d=1000/chttp2/fullstack

I1206 07:24:56.472000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009096.472000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.476000000 10888 http_proxy.c:428] Proxy address: localhost:2655

I1206 07:24:56.481000000  4624 http_connect_handshaker.c:273] Connecting to server localhost:2654 via HTTP proxy localhost:2655

I1206 07:24:56.563000000  4624 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009096.563000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.563000000 10888 hpack_size.c:197] test_size:e=100:d=32768/chttp2/fullstack

I1206 07:24:56.564000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009096.564000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.569000000 10888 http_proxy.c:428] Proxy address: localhost:2659

I1206 07:24:56.574000000 19164 http_connect_handshaker.c:273] Connecting to server localhost:2658 via HTTP proxy localhost:2659

I1206 07:24:56.660000000 19164 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009096.659000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.660000000 10888 hpack_size.c:197] test_size:e=100:d=4194304/chttp2/fullstack

I1206 07:24:56.660000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009096.660000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.663000000 10888 http_proxy.c:428] Proxy address: localhost:2669

I1206 07:24:56.668000000 12296 http_connect_handshaker.c:273] Connecting to server localhost:2668 via HTTP proxy localhost:2669

I1206 07:24:56.744000000 12296 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009096.744000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.745000000 10888 hpack_size.c:197] test_size:e=1000:d=4096/chttp2/fullstack

I1206 07:24:56.745000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009096.745000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.752000000 10888 http_proxy.c:428] Proxy address: localhost:2671

I1206 07:24:56.757000000 16548 http_connect_handshaker.c:273] Connecting to server localhost:2670 via HTTP proxy localhost:2671

I1206 07:24:56.854000000 16548 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009096.854000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.854000000 10888 hpack_size.c:197] test_size:e=1000:d=0/chttp2/fullstack

I1206 07:24:56.855000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009096.854000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.858000000 10888 http_proxy.c:428] Proxy address: localhost:2673

I1206 07:24:56.862000000 20416 http_connect_handshaker.c:273] Connecting to server localhost:2672 via HTTP proxy localhost:2673

I1206 07:24:56.924000000 20416 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009096.924000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:56.925000000 20416 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009096.925000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:57.925000000 10888 hpack_size.c:197] test_size:e=1000:d=100/chttp2/fullstack

I1206 07:24:57.930000000 10888 http_proxy.c:428] Proxy address: localhost:2693

I1206 07:24:57.938000000 14204 http_connect_handshaker.c:273] Connecting to server localhost:2692 via HTTP proxy localhost:2693

I1206 07:24:58.066000000 14204 http_proxy.c:131] HTTP proxy server read: {"created":"@1481009098.066000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:58.067000000 10888 hpack_size.c:197] test_size:e=1000:d=1000/chttp2/fullstack

I1206 07:24:58.068000000 10888 http_proxy.c:131] HTTP proxy client read: {"created":"@1481009098.068000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}

I1206 07:24:58.075000000 10888 http_proxy.c:428] Proxy address: localhost:2707

I1206 07:24:58.079000000 18380 http_connect_handshaker.c:273] Connecting to server localhost:2706 via HTTP proxy localhost:2707

E1206 07:25:03.094000000 10888 cq_verifier.c:257] cq returned unexpected event: OP_COMPLETE: tag:00000001 OK

E1206 07:25:03.094000000 10888 cq_verifier.c:264] expected tags:

00000065 GRPC_OP_COMPLETE result=1 C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt\vsprojects\..\test\core\end2end\tests\hpack_size.c:315

Abort handler called.

*** 0: 0000000001202A8E  - 0000000000000000

*** 1: 0000000001202D7A  - 0000000000000000

*** 2: 000000000127238B  - 0000000000000000

*** 3: 000000000125708A  - 0000000000000000

*** 4: 00000000012574D8  - 0000000000000000

*** 5: 000000000124AABA  - 0000000000000000

*** 6: 0000000001201239  - 0000000000000000

*** 7: 00000000012724BC  - 0000000000000000

*** 8: 0000000074DB336A BaseThreadInitThunk - 0000000074DB3358

*** 9: 0000000076ED9902 RtlInitializeExceptionChain - 0000000076ED989F

*** 10: 0000000076ED98D5 RtlInitializeExceptionChain - 0000000076ED989F

**Comment by markdroth** [comment]
See also #8996.

I have seen a lot of spurious failures of both the h2_http_proxy_test and h2_http_proxy_nosec_test fixtures on Windows, both in Debug and Release, and with various different test cases.

**Comment by apolcyn** [comment]
reopening as what looks like the same failure is in https://sponge.corp.google.com/target?id=38620b33-73b5-409b-a09c-738bd62fd7e9&target=github/grpc/c_windows_opt_native&searchFor=&show=FAILED&sortBy=STATUS
