### ISSUE TITLE
c_macos_opt.bins/opt/dualstack_socket_test

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#9040]
https://grpc-testing.appspot.com/job/gRPC_master_macos/800/testReport/junit/(root)/c_macos_opt/bins_opt_dualstack_socket_test/

https://grpc-testing.appspot.com/job/gRPC_master_macos/800/console

**Comment by nathanielmanistaatgoogle** [comment]
Seen again in builds [1104](https://grpc-testing.appspot.com/job/gRPC_master_macos/1104/testReport/junit/(root)/c_macos_dbg/bins_dbg_dualstack_socket_test/) and [1111](https://grpc-testing.appspot.com/job/gRPC_master_macos/1111/testReport/junit/(root)/c_macos_dbg/bins_dbg_dualstack_socket_test/).

**Comment by dgquintas** [comment]
When reporting a bug, please include at least the relevant text in the issue itself: Jenkins links expire after a while (there's a way to make them stay, but for the complete log, I'd recommend using gist.github.com).

**Comment by dgquintas** [comment]
Not seen for a while, closing.
