### ISSUE TITLE
qps_openloop_test failing on tsan on v1.0.x

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#9046]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/676/#showFailuresLink

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/793/

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [pull request 9156](https://github.com/grpc/grpc/pull/9156) against `v1.0.x`.

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [pull request 8686](https://github.com/grpc/grpc/pull/8686) against `v1.0.x`.

**Comment by apolcyn** [comment]
failures on poll, epoll, and legacy seen in https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/1226/#showFailuresLink

from PR: https://github.com/grpc/grpc/pull/8304

**Comment by dgquintas** [comment]
Not seen for a while, closing.
