### ISSUE TITLE
tests.cloud_to_cloud:node:node_server:unimplemented_method 

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9049]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10012/testReport/junit/(root)/tests/cloud_to_cloud_node_node_server_unimplemented_method/

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: 14 === 12
    at Object.callback (/var/local/git/grpc/src/node/interop/interop_client.js:391:12)
    at /var/local/git/grpc/src/node/src/client.js:421:14

**Comment by dgquintas** [comment]
It seems we haven't seen this in a while. Closing.
