### ISSUE TITLE
could not find out "grpc_csharp_ext.dll"

### ISSUE THREAD

**Issue by zeroxenof** [grpc/grpc#905]
<Content Include="..\..\..\vsprojects\vs2013\Debug\grpc_csharp_ext.dll">

**Comment by jtattermusch** [comment]
More details?

**Comment by zeroxenof** [comment]
I was built it on windows pc.
it seems to depends on opensll(for windows version).but vsproject file includes "grpc_csharp_ext.dll".
you can check it "\src\csharp\Grpc.Core\Grpc.Core.csproj".

**Comment by jtattermusch** [comment]
As mentioned in the readme, Windows version is work-in-progress. You can
build OpenSSL and grpc_csharp_ext.dll using  OpenSSL.mak and Grpc.sln under
vsproject in the project root.

**Comment by jrick** [comment]
I noticed the readme was updated with the ok for early adopters to begin trying this out.  I'm currently hitting the same issue (an exception for not being able to load this dll) with the latest nuget packages (Grpc.Core 0.5.0, grpc.native.csharp_ext 0.9.0).

**Comment by jtattermusch** [comment]
@jrick , what is your setup?  
What exact error message are you getting?
Are you working with the Grpc.sln directly or you are trying to build some of the examples (Greeter & Helloworld).

**Comment by jrick** [comment]
Sorry should have said before, this is my first time using visual studio (2015 preview) so it's not unlikely I have something misconfigured.

I haven't yet tried the examples but was about to before I got your reply. I'll give that a try after.

I'm working on a new project, and installed those nuget packages.  The except is thrown when calling GrpcEnvironment.Intialize:

```
An exception of type 'System.DllNotFoundException' occurred in Grpc.Core.dll but was not handled in user code

Additional information: Unable to load DLL 'grpc_csharp_ext.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by jrick** [comment]
I see the same error after building and running the examples:

```

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'grpc_cshar
p_ext.dll': The specified module could not be found. (Exception from HRESULT: 0x
8007007E)
   at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)

   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.Initialize()
   at GreeterServer.ServerMainClass.Main(String[] args) in C:\Users\jrick\src\gr
pc-common\csharp\GreeterServer\Program.cs:line 22
```

**Comment by jtattermusch** [comment]
Ok, is there a grpc_csharp_ext.dll file in your build directory (bin/Debug or bin/Release)?

The way providing the native dll works is through grpc.native.csharp_ext.props and grpc.native.csharp_ext.targets files in package grpc.native.csharp_ext 0.9.0, that get imported into your project when installing the package.

Perhaps you want to inspect them and find out what's wrong?
(Btw, I haven't tested with VS2015 - it doesn't have an official release yet)

**Comment by jrick** [comment]
Yes, the dll get copied to both the debug and release target dirs.

```
C:\Users\jrick\src\grpc-common\csharp\GreeterServer\bin\Debug>dir
 Volume in drive C is Solid-State Drive
 Volume Serial Number is 70C7-A9DE

 Directory of C:\Users\jrick\src\grpc-common\csharp\GreeterServer\bin\Debug

06/01/2015  07:46 PM    <DIR>          .
06/01/2015  07:46 PM    <DIR>          ..
06/01/2015  07:45 PM           323,072 Google.ProtocolBuffers.dll
06/01/2015  07:45 PM            57,856 Google.ProtocolBuffers.Serialization.dll
06/01/2015  07:45 PM            71,034 Google.ProtocolBuffers.Serialization.xml
06/01/2015  07:45 PM           282,553 Google.ProtocolBuffers.xml
06/01/2015  07:45 PM            16,896 Greeter.dll
06/01/2015  07:45 PM            50,688 Greeter.pdb
06/01/2015  07:46 PM             5,632 GreeterServer.exe
06/01/2015  07:46 PM            11,776 GreeterServer.pdb
06/01/2015  07:45 PM            64,000 Grpc.Core.dll
06/01/2015  07:45 PM            33,260 Grpc.Core.xml
06/01/2015  07:45 PM           481,792 grpc_csharp_ext.dll
06/01/2015  07:45 PM         2,139,136 libeay32.dll
06/01/2015  07:45 PM           533,504 ssleay32.dll
06/01/2015  07:45 PM           149,752 System.Collections.Immutable.dll
06/01/2015  07:45 PM           655,884 System.Collections.Immutable.xml
06/01/2015  07:45 PM           185,552 System.Interactive.Async.dll
06/01/2015  07:45 PM             2,571 System.Interactive.Async.xml
06/01/2015  07:45 PM           207,360 zlib.dll
              18 File(s)      5,272,318 bytes
               2 Dir(s)  17,190,141,952 bytes free
```

Any other packaging errors to look for besides not copying the dll?

**Comment by jtattermusch** [comment]
Ah, I think I got it.
The "Unable to load DLL 'grpc_csharp_ext.dll': The specified module could not be found. (Exception from HRESULT: 0x
8007007E)" basically says  you are having wrong version of the .dll.   This can be because of bitness (are you by chance building 64-bit?) or that the dll is otherwise incompatible.

**Comment by jrick** [comment]
My windows install is 64-bit, and I was building it "Any CPU".  If I explicitly target x86, I get the same exception:

```
C:\Users\jrick\src\grpc-common\csharp\GreeterServer\bin\x86\Debug>GreeterServer.
exe

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'grpc_cshar
p_ext.dll': The specified module could not be found. (Exception from HRESULT: 0x
8007007E)
   at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)

   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.Initialize()
   at GreeterServer.ServerMainClass.Main(String[] args) in C:\Users\jrick\src\gr
pc-common\csharp\GreeterServer\Program.cs:line 22
```

Targeting x64 results in a different exception:

```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load
 a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)

   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.Initialize()
   at GreeterServer.ServerMainClass.Main(String[] args) in C:\Users\jrick\src\gr
pc-common\csharp\GreeterServer\Program.cs:line 22
```

**Comment by jtattermusch** [comment]
Ok, thanks for the info. Do you have a VS2013 installations that you can try it with?

**Comment by jrick** [comment]
I don't, but it looks like there's a 90-day trial I could download.  I'll give that a shot and report back.

**Comment by nicolasnoble** [comment]
You can get the community edition which is free.

**Comment by nicolasnoble** [comment]
Available on that link:
https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by jrick** [comment]
@nicolasnoble even better. thanks!

**Comment by nicolasnoble** [comment]
You can also use http://www.dependencywalker.com/ on the DLL that's causing
trouble to see which import is actually failing for which reason.

**Comment by jrick** [comment]
That tool says I'm missing these three libraries:

```
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
```

**Comment by nicolasnoble** [comment]
Please try installing
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by jrick** [comment]
Installed, but still won't load (and dependency walker fails finding those same three dlls).

2013 is taking its sweet time to install but if this is due to a ABI break between the two VS C++ versions than that would certainly explain the errors loading the dll.

**Comment by jrick** [comment]
Oops, it does load.  I just had to restart cmd.exe.

Thanks for all the help!

**Comment by nicolasnoble** [comment]
Cool! Just so we know, did installing the VS2013 redistributable actually
help ? Which would make sense, but we need to update our installation
instructions accordingly.

**Comment by jrick** [comment]
Seems so, or it was some other thing while 2013 was installing in the background.  If I would have started out with 2013 instead of 2015 preview I bet it would have worked.

**Comment by nicolasnoble** [comment]
Installing VS2013 implicitly installs the redistributable anyway. But yeah,
I think that was the problem.

We'll do some changes on our side accordingly. Thanks for your time and
patience!

**Comment by degloff** [comment]
I faced the same issue and I can also confirm that installing  VS2013 fixes the problem. It would be good to have the dependencies properly resolved.

**Comment by jtattermusch** [comment]
@degloff what version of visual studio are you using?

**Comment by degloff** [comment]
Hi, I use VS 2013 update 5.

**Comment by jtattermusch** [comment]
Ah, so when you said you installed VS 2013, it was on a different machine than where you develop and you were just trying to run the resulting app?

**Comment by degloff** [comment]
yes exactly, so eventually also the VS redistributable would do the job. I am not sure though because I did not test that.

**Comment by nickdul** [comment]
Getting `BadImageFormatException` exception trying to run program built against AnyCPU platform: 
```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)
   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment.Initialize()
   at GreeterClient.ClientMainClass.Main(String[] args) in c:\projects\grpcdemo\csharp\GreeterClient\Program.cs:line 13
```

Configuration:
`Grpc 0.6.1` (installed via NuGet)
Visual Studio 2013 Update 5
Windows 8.1 Pro 64-bit
(VS2013 redistributable were installed as well)

__The only way to make it working - switch solution platform to x86.__

**Comment by sawdiggy** [comment]
I am trying to deploy this on a Windows Server 2012 R2 x64, and after running the VC++ resdistribution, I still get the error:

Unable to load DLL 'grpc_csharp_ext.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) -    at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)
   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.Initialize()

Any ideas what I might be missing?

**Comment by nickdul** [comment]
>I am trying to deploy this on a Windows Server 2012 R2 x64, and after running the VC++ redistribution, I still get the error:

take a look at these instructions: https://github.com/grpc/grpc/tree/master/src/csharp#problem-unable-to-load-dll-grpc_csharp_extdll

especially at the last point:
```
Possible cause for the problem is that the grpc_csharp_ext library is installed, but it has different bitness (32/64bit) than your C# runtime
```

**Comment by sawdiggy** [comment]
Which version of the toolset/platform should I use to run on x64?  When I build my project for x64, I get this error:

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) -    at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)
   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.Initialize()

I assume this is b/c I need to set the toolset/platform (NativeDependenciesToolset, NativeDependenciesPlatform), but not sure which is which.

Thanks

**Comment by nickdul** [comment]
>Which version of the toolset/platform should I use to run on x64?

__The only way to make it working - switch solution platform to x86.__

see more info here #2505

**Comment by sawdiggy** [comment]
When I switch x86, I still get 

Unable to load DLL 'grpc_csharp_ext.dll': The specified module could not be found.

Whats the difference between v100 and v120?  

Is the issue possibly the release vs debug builds?  I've noticed on my server, I'm missing MSVCP120d.dll, which I believe contains the debug symbols.

**Comment by sawdiggy** [comment]
Also, this works fine on my developer workstation

**Comment by sawdiggy** [comment]
That was the issue, I was not running the release build on a machine that did not have the VC++ debug symbols (msvcr120d.dll)

**Comment by jtattermusch** [comment]
On Tue, Oct 6, 2015 at 6:41 AM, sawdiggy <notifications@github.com> wrote:

> When I switch x86, I still get
>
> Unable to load DLL 'grpc_csharp_ext.dll': The specified module could not
> be found.
>
> Whats the difference between v100 and v120?
>

v100 stands for Visual Studio 2010 (= version 10)
v10 stands for Visual Studio 2013 (=version 12)
