### ISSUE TITLE
tests.cloud_to_cloud:node:node_server:unimplemented_service

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9050]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10012/testReport/junit/(root)/tests/cloud_to_cloud_node_node_server_unimplemented_service/

tools/run_tests/interop/with_nvm.sh: line 34:   193 Segmentation fault      (core dumped) $@

**Comment by adelez** [comment]
The new error is 
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: 14 === 12
    at Object.callback (/var/local/git/grpc/src/node/interop/interop_client.js:391:12)
    at /var/local/git/grpc/src/node/src/client.js:426:14

https://grpc-testing.appspot.com/job/gRPC_interop_master/9712/testReport/junit/(root)/tests/cloud_to_cloud_node_node_server_unimplemented_method/

**Comment by dgquintas** [comment]
It seems we haven't seen this in a while. Closing.
