### ISSUE TITLE
Linkage spaghetti in GRPC/OpenSSL/zlib

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#9085]
As far as I can tell, it seems that the prebuilt OpenSSL (built by @jtattermusch and uploaded to NuGet) that GRPC uses is trying to link against the import library for Zlib. Using dumpbin on the **static** library of openssl (`libeay32.lib`) clearly shows several `__imp__XXXX` functions (one such example is `__imp__deflateInit_`).
GRPC itself contains the code for and links statically with zlib. As such, every application that links with GRPC needs to link to `zlib.lib` and `libeay32.lib`. ZLIB is also acquired using NuGet packages and contains the required symbols but **without** the `__imp__` prefix. Under normal circumstances, the linker should fail, but in our case it somehow detects the duplicity in symbols and generates linker-defined stub which connects the two (very weird and undocumented).
This situation can sometimes trigger unexpected behavior. In our case, for some utility project, we wanted to use several functions from libeay32. This utility does not use GRPC at all, but our main project does. In order to avoid confusion with different versions of libeay32, we wanted to use the same lib file. However, This time, even though we instructed the linker to link our utility to both libeay32 and zlib, we had unresolved externals (for those `__imp__XXXX` symbols). 
After some investigation we found out that when the linker is not forced to link zlib into our project, it may omit it and cause those reported errors. When we forced the linker (by referencing symbols from zlib) everything worked fine. 
This is not a GRPC error per-se, but currently GRPC does rely on some unexpected (and undocumented) linker behavior, and I guess I'm not the only one to break my head around this issue.

**Comment by jtattermusch** [comment]
I suspect the right thing for us to do is to compile everything from scratch (using cmake or ninja) - including zlib, boringssl, protobuf etc.
That will fix the issue you are mentioning and will also enable us to provide a better story for compiling gRPC C++ on windows.

**Comment by jtattermusch** [comment]
gRPC C++ can now be compiled using CMake on windows, and it uses  boringssl instead of openssl.
I believe that the linkage should be now much cleaner, as we depend directly on official boringssl's and zlib's cmake files.
Feel free to reopen if you still think there are issues.
