### ISSUE TITLE
c++_linux_opt.bins/opt/end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/0 GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9086]
https://grpc-testing.appspot.com/job/gRPC_master_linux/778/testReport/junit/(root)/c++_linux_opt/bins_opt_end2end_test___gtest_filter_ProxyEnd2end_ProxyEnd2endTest_RpcDeadlineExpires_0__GRPC_POLL_STRATEGY_poll/

D1213 17:39:55.687339205    7030 test_config.c:290]          test slowdown: machine=1.000000 build=1.000000 poll=1.000000 total=1.000000
Note: Google Test filter = ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/0
I1213 17:39:55.688844925    7030 end2end_test.cc:213]        Scenario: proxy 0, credentials ssl
D1213 17:39:55.688967439    7030 ev_posix.c:105]             Using polling engine: poll
I1213 17:39:55.695225900    7030 server_builder.cc:247]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 10
D1213 17:39:55.697376176    7030 ev_posix.c:105]             Using polling engine: poll
test/cpp/end2end/end2end_test.cc:1081: Failure
Value of: s.error_code()
  Actual: 2
Expected: StatusCode::DEADLINE_EXCEEDED
Which is: 4
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/0, where GetParam() = 16-byte object <00-0A 0D-02 00-00 00-00 48-05 0D-02 00-00 00-00> (61 ms)
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest (61 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (61 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires/0, where GetParam() = 16-byte object <00-0A 0D-02 00-00 00-00 48-05 0D-02 00-00 00-00>

 1 FAILED TEST
D1213 17:39:55.749474285    7030 ev_posix.c:105]             Using polling engine: poll

**Comment by dgquintas** [comment]
It seems we haven't seen this in a while. Closing.
