### ISSUE TITLE
cloud_to_cloud:ruby:node_server:timeout_on_sleeping_server

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9093]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/9971/consoleFull

/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:41:in `check_status': GRPC::Cancelled (GRPC::Cancelled)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:203:in `block in read_loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:191:in `loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:191:in `read_loop'
	from src/ruby/pb/test/client.rb:461:in `each'
	from src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
	from src/ruby/pb/test/client.rb:617:in `call'
	from src/ruby/pb/test/client.rb:617:in `main'
	from src/ruby/pb/test/client.rb:622:in `<main>'
I, [2016-12-08T20:41:48.460120 #68]  INFO -- : ... connecting securely to localhost:33638
W, [2016-12-08T20:41:49.460616 #68]  WARN -- : bidi: read-loop failed
W, [2016-12-08T20:41:49.460712 #68]  WARN -- : GRPC::Cancelled (GRPC::Cancelled)
/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:41:in `check_status'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:203:in `block in read_loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:191:in `loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:191:in `read_loop'
src/ruby/pb/test/client.rb:461:in `each'
src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
src/ruby/pb/test/client.rb:617:in `call'
src/ruby/pb/test/client.rb:617:in `main'
src/ruby/pb/test/client.rb:622:in `<main>'

FAILED: cloud_to_cloud:ruby:node_server:timeout_on_sleeping_server [ret=1, pid=31550]

**Comment by murgatroid99** [comment]
This is the same problem as #8989.
