### ISSUE TITLE
cannot build helloworld example in C++, error about ssl unresolved, with VS2015

### ISSUE THREAD

**Issue by cpzhang** [grpc/grpc#9104]
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_CTX_set_options
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_CTX_set_tlsext_servername_arg
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _BIO_get_mem_data
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _BIO_should_retry
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_CTX_set_tlsext_servername_callback
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_CTX_add_extra_chain_cert
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_CTX_set_tmp_ecdh
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_set_tlsext_host_name
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _SSL_is_init_finished
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _BIO_pending
1>grpc.lib(ssl_transport_security.obj) : error LNK2001: unresolved external symbol _OpenSSL_add_all_algorithms

**Comment by allquixotic** [comment]
So you're trying to build without having previously compiled either OpenSSL or BoringSSL and put the libraries and headers in a path where the compiler/linker can find them. That's basically what these errors are saying. You can solve this (and then be stuck with the next build problem, then the next, then the next...) by making sure your build environment can locate the OpenSSL libraries (static .libs appears to be the preferred way) and headers.

But...

grpc is so difficult to build on Windows that someone has created a repo specifically to ease the building process: https://github.com/plasticbox/grpc-windows

It worked for me; I highly recommend you check out the grpc-windows repo. I am not optimistic that efforts in upstream grpc will yield anywhere _near_ as easy of a build on Windows in the near future.

**Comment by cpzhang** [comment]
@allquixotic
 Thanks for your reply. 
The problem has been solved. Just change STATIC to DYNAMIC link to openssl. The helloworld example works well!

**Comment by lemaxw** [comment]
I have same issue. Compiling on windows.
Compiled gprc 1.4.0 (including boringssl) with CMakeList
Now, trying compile helloworld, but CmakeList compilation fails due to various issues.
So created solution manually, found correct includes and libraries. However getting above errors.
@cpzhang, could you advise how to fix it? Where should I change the link from static to dynamic?
