### ISSUE TITLE
How to close GRPCCall channel?   IOS

### ISSUE THREAD

**Issue by lswhcmcc** [grpc/grpc#9105]
Use the following code:

[GRPCCall useInsecureConnectionsForHost:kHostAddress];
Connector *clientConnector = [Connector serviceWithHost:kHostAddress];

GRXBufferedPipe *writer = [[GRXBufferedPipe alloc] init];
    [clientConnector sendSessionRequestWithRequestsWriter:writer eventHandler:^(BOOL done, SessionNotify * _Nullable response, NSError * _Nullable error){
 SessionRequest *sessionRequest = [SessionRequest message];
   ...................
[writer writeValue:sessionRequest];
}

How to close the connection to avoid duplicate logins.

I try this: 
 [_writer writesFinishedWithError:nil];
 [GRPCCall closeOpenConnections];//DEPRECATED_MSG_ATTRIBUTE
 [GRPCCall resetHostSettings];

It does not work.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
