### ISSUE TITLE
Add QUIC backend to accommodate peer to peer applications 

### ISSUE THREAD

**Issue by athei** [grpc/grpc#9107]
For now grpc seems to target classical server / client applications. When used for other purposes like p2p applications we can quickly hit the socket limit #8974  (we need an ephemeral port number for each connection) when communicating with many other clients. With QUIC we do the demultiplexing in user space and are not subject to such limitations. In addition we have a faster connection establishment that constitutes a substantial overhead in p2p applications.

**Comment by joeblew99** [comment]
+1

**Comment by yelcat** [comment]
+1

**Comment by hsaliak** [comment]
We have no plans to support quic backends at the moment, so closing this issue.
