### ISSUE TITLE
Support for setting default timeout in GRPC clients

### ISSUE THREAD

**Issue by mightyguava** [grpc/grpc#9110]
It would be nice if there was consistent default timeout support (be able to set a default timeout) across the GRPC clients. Default timeouts are really useful and part of basically every networking-related library. One advantage in a production scenario would be not having to worry about people forgetting to set timeouts on individual requests and saturating client resources when the server's slow to respond or not responding.

It seems like support for default timeouts in GRPC is currently implementation-dependent, and supported in only the [Ruby library](http://www.rubydoc.info/gems/grpc/0.9.2/GRPC/ClientStub) and [Go library](https://godoc.org/google.golang.org/grpc#WithTimeout)?

I found a couple issues that indicate interest in having default timeouts across languages:
https://github.com/grpc/grpc-haskell/issues/4
https://github.com/grpc/grpc/issues/2114
https://github.com/grpc/grpc-java/issues/1495

Maybe it would be nice to build the functionality into core and expose it into the individual languages?

**Comment by murgatroid99** [comment]
That Ruby documentation link corresponds to a *really* old version of the library, and Ruby is currently consistent with other languages in having no finite timeout.

**Comment by mightyguava** [comment]
It looks like the ability to set a default timeout on a client stub is still available: https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/client_stub.rb#L109

I think my original comment may have been confusing. I was not hoping that GRPC would have a default timeout. I was hoping that it would be possible for users to specify a default timeout either on the channel or on the client, in a consistent manner across languages. Edited the original comment

**Comment by markdroth** [comment]
The forthcoming service config functionality (which we plan to make available by the end of Q1) will provide a way for service owners to publish default timeouts on a per-method basis (including setting a default for all methods of a given service).  That's not exactly the same thing as allowing the client to specify a default timeout for all RPCs, but I think it's actually a bit better suited to real-life use, since it's hard to imagine the same default timeout being appropriate for every single RPC.

**Comment by kraghu** [comment]
@markdroth How do we add timeouts in android grpc ?

**Comment by markdroth** [comment]
Keeping this open, since we still haven't enabled service config functionality by default in OSS.

**Comment by HunterLarco** [comment]
Is there a current roadmap for this feature?

**Comment by markdroth** [comment]
We need to finish the service config error handling work and then enable the TXT lookups by default.  Hopefully, we'll be able to do this over the next couple of quarters.

**Comment by hcoona** [comment]
We are still wanting this feature, so keep it open now.

**Comment by nocive** [comment]
bump
