### ISSUE TITLE
Support for HTTP1.1 in gRPC or AppEngine should upgrade to support HTTP2

### ISSUE THREAD

**Issue by tjerkw** [grpc/grpc#9113]
Google is advocating the use of gRPC:
https://cloud.google.com/solutions/mobile/mobile-compute-engine-grpc

But gRPC is NOT supported on appengine standard environment! It requires http2.
This seems kind a stupid.

Maybe it would be nice to support non-streaming gRPC for http1.1. 
Somebody already tried it:
https://gist.github.com/nodirt/bce25f976675ff3f2c27

**Comment by tbillington** [comment]
You can make grpc calls from appengine, you need to do a few things manually though and it's not so great because you must make a new connection for every appengine request.

**Comment by tjerkw** [comment]
@tbillington I can live with the new-connection per request for now. I need the fast development cycles that gRPC gives me. Could you give me a hint of howto support gRPC on http1.1 appengine... I tought about creating a fake HTTP2 request from an HTTP1 request and then call ServeHTTP on the grpc server. But i dont know where to start.

Note: I do understand this this issue, is not really a gRPC issue, but more an appengine issue.
However support HTTP1.1 for gRPC would be usefull it hink. And it theory its not that difficult for the non-streaming API.

**Comment by tjerkw** [comment]
Related issue: https://github.com/grpc/grpc-go/issues/805

**Comment by tbillington** [comment]
I've used this before to make a connection with https://godoc.org/google.golang.org/grpc#Dial and https://godoc.org/google.golang.org/appengine/socket#DialTimeout.

**Comment by public** [comment]
@tbillington What about those of us who aren't writing services or clients in Go?

**Comment by tbillington** [comment]
@public Sorry mate, I've only got experience with go appengine, no idea about the others! I assume they have some way in their standard libraries to make raw sockets, maybe try starting there?

Good luck :)

**Comment by Jonathan34** [comment]
I am confused, it seem app engine supports http/2 already. From: https://cloudplatform.googleblog.com/2015/10/Full-Speed-Ahead-with-HTTP2-on-Google-Cloud-Platform.html

`Google App Engine
Both in its original incarnation and Managed VM configurations, Google App Engine servers are responsible for negotiating and terminating the TLS tunnel. As long as your application is being served over HTTPS, the Google servers automatically negotiate HTTP/2 on your behalf.
Each HTTP/2 stream is then translated into an HTTP/1.1 request and routed to your application. As a result, no modifications are required within your application to enable HTTP/2. Simply direct your traffic through HTTPS and all capable visitors will be automatically served over HTTP/2.`

So as long as the server uses the port 8080, we should be good? I do not think this will allow to use grpc along with asp.net routes though...

**Comment by tjerkw** [comment]
No: appengine does use HTTP 2 to the outside world. But internally, all
APIs are only supporting HTTP 1.1

You can't open a port en start doing htttp2... Are stuck to http1.1

**Comment by kpayson64** [comment]
gRPC Clients should now work on all appengine standard runtimes.

**Comment by leighmcculloch** [comment]
AppEngine still does not have support for GRPC servers.

**Comment by tjerkw** [comment]
gRPC client work, but im talking about making an gRPC server in Appengine Standard Environment.
This is not possible. Please re-open.

**Comment by kpayson64** [comment]
@tjerkw 
There are no plans for gRPC servers to support HTTP 1.1.

The current plan for gRPC servers on App Engine is for App Engine to support HTTP/2.

I think that work is better tracked on App Engines public bug tracker, rather than the gRPC repository.

**Comment by leighmcculloch** [comment]
@kpayson64 Could you provide a link to where that is being tracked?

**Comment by kpayson64** [comment]
https://issuetracker.google.com/35898954

**Comment by tjerkw** [comment]
Maybe I'm wrong but it feels like Google is spending less time and effort on Appengine Standard environment. And more on the Flexible environment and other similar product like Kubernetes on Google Cloud.

Appengine Standard environment runs http 1.1, python 2.7 etc. It's getting old. 

Also I understand that http 2.0 streaming is (more) difficult todo on the Standard Environment. But it is not impossible.

What's Google stand on this? If I start a new startup, should I use Appengine at all? Or is Kubernetes and docker recommended (which comes close to what Appengine provides).

I know this comment is a bit out of scope, but still interesting to see Google's answer on this.

**Comment by nicolasnoble** [comment]
I am a Google employee, and I do not feel like it's appropriate for any of us here to respond to this last question. I would rather direct you to the GCP's support, who I know have support engineer for the customers who have design decisions like these to make.

**Comment by tbillington** [comment]
@tjerkw nodejs on Appengine standard was released just a few weeks ago.
