### ISSUE TITLE
build_python.sh script is downloading packages from PyPI

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9116]
seen in https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1453/testReport/junit/(root)/aggregate_tests/run_tests_python_linux_opt/

copy of log in https://gist.github.com/apolcyn/4a2d83fd7880f04f3e57856e522b0add

**Comment by apolcyn** [comment]
note the PR where this failed was on v1.0.x branch

**Comment by soltanmm-google** [comment]
The weirdness about this is that it isn't just an ephemeral network failure; it's downloading things it absolutely shouldn't be downloading.
