### ISSUE TITLE
Can grpc stream be used as frequent tiny messages transport?

### ISSUE THREAD

**Issue by k8w** [grpc/grpc#9121]
We use grpc to send stream data from java to nodejs.

**Proto**
```proto
syntax = "proto3";

service DataService{
    rpc getData (stream dataReq) returns (stream dataRes) {}
}

message dataReq {
    string dataId = 1; 
}

message dataRes {
    string dataId = 1;
    double time = 2;
    double value = 3;
}
```

Once the stream is connected, there is about **10000** `dataRes` message per second is sended from java.
But it seems can not receive enough 10000 message at nodejs every second, so the messages are pilling up... (maybe 1000 per second is okay)
So whether grpc is not good at transport frequent tiny messages?

**Comment by ctiller** [comment]
Currently there's going to be one write syscall per send, and that's going end up being the bottleneck (though there may be others above the transport layer - especially in the node/c interface).

We do have a buffering option in C (GRPC_WRITE_BUFFER_HINT): I'm not sure if it's exposed from Node.

**Comment by murgatroid99** [comment]
Sorry it took so long to respond to this. You can set the write buffer hint on a streaming write by passing `grpc.writeFlags.BUFFER_HINT` as the second argument to the `write` method. I think you want to omit that whenever you want it to actually send over the wire.

**Comment by tbillington** [comment]
Why don't you make it the messages able to batch.. ? You could still ask for a single thing at a time, but when you can ask for more, do it all at once. That will cut down a lot of per message overhead.

**Comment by murgatroid99** [comment]
I do see a useful possibility here: Node writable streams allow for a `_writev` method to handle multiple writes that have backed up in the stream buffer. We could use that to apply the write buffer hint to all messages but the last whenever multiple messages build up in the stream buffer.

Another possibly parallel improvement could be to do a quick poll on `completion_queue_next` every time we start a batch to more quickly handle batches that complete immediately and require no network interaction.

**Comment by slumbi** [comment]
@murgatroid99  I have tried setting BUFFER_HINT for `write `method, but now messages are never sent. 
Do I need sg else apart from call.end() ?

**Comment by murgatroid99** [comment]
The BUFFER_HINT flag means that the message shouldn't be sent yet. If you want the message to be sent, you have to either end the call or write a message without the BUFFER_HINT flag.

**Comment by ctiller** [comment]
(Note: BUFFER_HINT will *eventually* send once buffers are sufficiently
large... I think this defaults to 64kb)

**Comment by slumbi** [comment]
Hmm, weird. My client receives everything nicely without the BUFFER_HINT  flag, but when the flag is set, no messages arrive to the client . Even after calling `end()` on the server. I am sending several dozen megabytes in ~20k messages..

**Comment by slumbi** [comment]
It seems I have hit this  https://github.com/grpc/grpc/issues/12975

**Comment by devinrsmith** [comment]
It would be nice to know which implementations support buffered writing. I'm specifically interested in having the java server side calls to onNext be buffered in some fashion.
