### ISSUE TITLE
multiple check_copyright failures on Jenkins Linux master-branch CI builds

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#9133]
https://grpc-testing.appspot.com/job/gRPC_master_linux/798/#showFailuresLink
https://grpc-testing.appspot.com/job/gRPC_master_linux/797/#showFailuresLink

**Comment by nathanielmanistaatgoogle** [comment]
Consider changing this issue's title? [I just saw it](https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1571/) on [a `v1.0.x` pull request](https://github.com/grpc/grpc/pull/8686).

**Comment by soltanmm-google** [comment]
Oh hm those are slightly different errors and probably come from a `.gitignore` not excluding `*_pb2_grpc.py` files somewhere.

**Comment by soltanmm-google** [comment]
Actually, those are coming from a folder that shouldn't even exist on `v1.0.x` (`grpcio-reflection`). What's up with that...?

**Comment by dgquintas** [comment]
Problem seems to be gone. Closing.
