### ISSUE TITLE
unit._metadata_code_details_test.MetadataCodeDetailsTest.testCustomCodeExceptionStreamUnary

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#9134]
Timeout in unit._metadata_code_details_test.MetadataCodeDetailsTest.testCustomCodeExceptionStreamUnary.

https://grpc-testing.appspot.com/job/gRPC_master_macos/868/testReport/junit/(root)/python_macos_dbg/py27_test_unit__metadata_code_details_test_MetadataCodeDetailsTest/

**Comment by nathanielmanistaatgoogle** [comment]
[In build 1091 the timeout is reported in `testSuccessfulStreamStream`](https://grpc-testing.appspot.com/job/gRPC_master_macos/1091/testReport/junit/(root)/python_macos_opt/py27_test_unit__metadata_code_details_test_MetadataCodeDetailsTest/).

**Comment by dgquintas** [comment]
Hasn't happened in a while. ok to close?
