### ISSUE TITLE
Jenkins Mac workers failing builds

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#9151]
`Server aborted the SSL handshake` when trying to clone submodules as seen in https://grpc-testing.appspot.com/job/gRPC_master_macos/878/testReport/junit/(root)/aggregate_tests/run_tests_php_macos_opt/ and https://grpc-testing.appspot.com/job/gRPC_master_macos/880/testReport/junit/(root)/aggregate_tests/run_tests_python_macos_opt/

**Comment by stanley-cheung** [comment]
Is this still an issue? It seems to be occasionally green now, like this: https://grpc-testing.appspot.com/job/gRPC_master_macos/1162/

**Comment by matt-kwong** [comment]
I created this issue as per the BUILDPONY rules to keep track of how frequent an issue is. I do not think the issue is common and it might have been a flake for that one day it happened twice, but I'll keep this issue open for a little while longer to see if it happens again.

**Comment by dgquintas** [comment]
@matt-kwong has it recurred?

**Comment by matt-kwong** [comment]
Doesn't look like it has. Closing the issue since it doesn't happen frequently and it seems to be out of our control.

**Comment by matt-kwong** [comment]
Happening again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/4476/#showFailuresLink
```
Cloning into 'third_party/googletest'...
Submodule path 'third_party/googletest': checked out 'ec44c6c1675c25b9827aacd08c02433cccde7780'
Entering 'third_party/protobuf'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Cloning into 'third_party/protobuf'...
fatal: unable to access 'https://github.com/google/protobuf.git/': Server aborted the SSL handshake
Clone of 'https://github.com/google/protobuf.git' into submodule path 'third_party/protobuf' failed
Stopping at 'third_party/protobuf'; script returned non-zero status.
```

**Comment by jtattermusch** [comment]
Seen similar issue here: https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/5106/console

```
Disk space threshold is set to :50Gb
Checking disk space Now 
FATAL: null
java.lang.NullPointerException
	at org.jenkinsci.plugin.Diskcheck.preCheckout(Diskcheck.java:118)
	at jenkins.scm.SCMCheckoutStrategy.preCheckout(SCMCheckoutStrategy.java:76)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
ERROR: [GitHub Commit Status Setter] - Cannot retrieve Git metadata for the build, setting build result to FAILURE
```

**Comment by murgatroid99** [comment]
Seen again on MacOS master: https://grpc-testing.appspot.com/job/gRPC_master_macos/2358/console
