### ISSUE TITLE
Put extern "C" incantations in non-public core headers

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#9162]
We follow this format in all public core headers:

```
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
}
#endif
```

but we don't do this for non-public headers. We should do so as we do have users who are creating new transports and want to call directly into sub-surface core layers from C++.

**Comment by vjpai** [comment]
Cc: @wcevans

**Comment by vjpai** [comment]
Hard to call this important or not. Maybe the number of users with this issue is so small that we should just leave it alone and expect them to do extern "C" in their source files, though that's ugly.

**Comment by ctiller** [comment]
We'd be going with doing the extern "C" in source files. Both ways are
ugly, but we have less C++ using the core internals.

Whichever way we go, someone should write a linter.

**Comment by vjpai** [comment]
I'm going to close this issue and propose doing this on an as-needed basis as usage becomes visible to us. Feel free to reopen if you disagree.
