### ISSUE TITLE
grpc Ruby gem depends on older version of google-protobuf

### ISSUE THREAD

**Issue by hxiong388** [grpc/grpc#9163]
The current 1.0.1 version of grpc Ruby gem pings its google-protobuf dependency on version 3.0.2. This prevents other Google gems that are built on top of grpc to upgrade to later google-protobuf 3.1. E.g. [gax-ruby](https://github.com/googleapis/gax-ruby)

Is there a plan to release newer version of grpc to either upgrade dependency on google-protobuf or loosen up the restriction?

/cc @omaray, @swcloud

**Comment by apolcyn** [comment]
closing as fixed by https://github.com/grpc/grpc/pull/8914
