### ISSUE TITLE
How to fire an acknowledgement callback to notify the client that the stream is well opened? [Node]

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#9170]
Hello,

When making a call that **returns a stream** on **node grpc client**, is it possible to know when my stream call has been correctly processed by the server?

Because my client needs to make sure that the stream is well registered on the server, before calling another rpc method (that requires the previous stream is open) ? Ex:
```proto
service myService {
  rpc GetServerStream(Empty) returns (stream aStream) {}
  rpc GetSmthOnlyIfOpenedStream(Empty) return (Something) {}
}
```
and on the client side, this produces an **ERROR**:
```javascript
grpcClient.getServerStream().on('data', data => console.log(data));
grpcClient.getSmthOnlyIfOpenedStream({}, (err, result) => console.log(result)); // ERROR
// this call will hit the server before the above stream is opened/registered
```
Is it possible to await on the stream creation like this (or is there some callback that could be fired by the server to acknowledge the opening of the stream) ? :
```javascript
await grpcClient.getServerStream().on('data', data => console.log(data));
grpcClient.getSmthOnlyIfOpenedStream({}, (err, result) => console.log(result)); // OK
// [EDIT] this is actually NOT OK. Cannot await on getServerStream()
```
@murgatroid99 Any idea on this one? Many thanks!

**Comment by sulliwane** [comment]
My use case is:
1. The client open many streams of different dataType responses (one stream per **dataType**) by calling ```getServerStreamForDataTypeX()```.
2. When Server receives a ```getServerStreamForDataTypeX()``` call, Server push the stream object in an array (and will write data to it later).
3. Then Client subscribes to some data by calling another rpc unary call (```subscribeData(dataType)```) 
4. Server check if client has an opened stream for the dataType requested in the ```subscribeData(dataType)``` call. If not, Server throws an error saying: **client needs to open related dataType stream before**.

That's why Client needs a way to know if his call to  ```getServerStream()``` was handled successfully by Server, so that only then, Client can p proceed with his next rpc call, which will be ```subscribeData(dataType)```.

**Comment by sulliwane** [comment]
I decoupled the **subscription method** from the **stream to write** the data subscribed to. I believe this was a bad design choice and that I should be using a **bidir stream** for my use case, with the client directly writing its subscriptions to each of the bidir streams, depending on the type of the data it needs to subscribe to (instead of using a common ```subscribeData()``` method). Like so, the Server is sure that the stream is opened when receiving a subscription.

Is my conclusion correct?

Many thanks :)

**Comment by sulliwane** [comment]
Another way to do this would be for the server to first write a  **"OK message"** to the stream just opened by the client to notify him that the stream is well registered on the server side (and after receiving this message, the client can then proceed with a call to ```grpcClient.getSmthOnlyIfOpenedStream()```. 

That will need some wrap on the client side though, to get something like this:
```js
grpcClient.getServerStream({}, (err, ok) => { 
// This callback is fired when the "stream is opened/registered/functional", which is when receiving the first OK message from the server
// Inside this cb, I can proceed with other rpc calls that NEED the stream to be opened first
   grpcClient.getSmthOnlyIfOpenedStream({}, (err, result) => console.log(result)); // OK
})
 // the "OK message" is passed to above callback, and here I handle the real data streamed from the server.
.on('streamedData', streamedData => console.log(streamedData))
```
My question is:

1. Can somebody confirm me that this logic (**stream with acknowledgement cb**) doesn't exist already in Node GRPC, and that I should implement it myself?
2. If so, what is the best way to add this logic? Use the first message written to the stream for the acknowledgement? On the protobuf side, using a **oneOf** field ? Other suggestions ?

Many thanks!!

**Comment by sulliwane** [comment]
@murgatroid99 Any advice on this one? (best way to acknowledge the stream request is successful / opened) thanks

**Comment by murgatroid99** [comment]
You could use the `"metadata"` event that client streams emit. This is automatically sent when the server sends the first response message, but you can also manually send it from the server with `stream.sendMetadata(metadataObject)`.

**Comment by sulliwane** [comment]
This mechanism fits perfectly my needs. Thanks!
