### ISSUE TITLE
not installing protoc on make install

### ISSUE THREAD

**Issue by bloodcarter** [grpc/grpc#9175]
it installs protoc grpc plugins, but not protoc itself when running make install

**Comment by mehrdada** [comment]
Thanks for the feedback! Protobuf (including `protoc`) is really a separate package that is separately distributed and should be installed by the user as they see fit. The plugins are, however, gRPC specific and are part of the gRPC project and that is why they are installed.

We are always trying to improve the gRPC user experience and may consider exploring different packaging strategies to simplify things for the user.
