### ISSUE TITLE
c_windows_dbg.vsprojects/Debug/connection_refused_test

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#9186]
https://grpc-testing.appspot.com/job/gRPC_pr_win/1570/testReport/junit/(root)/c_windows_dbg/vsprojects_Debug_connection_refused_test_exe/

**Comment by nathanielmanistaatgoogle** [comment]
Seen in [build 1126](https://grpc-testing.appspot.com/job/gRPC_master_windows/1126/testReport/junit/(root)/c_windows_dbg/vsprojects_Debug_connection_refused_test_exe/).
