### ISSUE TITLE
Compiling for NodeJS with import_style=commonjs does not create commonjs modules for messages

### ISSUE THREAD

**Issue by drobertduke** [grpc/grpc#9189]
grpc_tools_node_protoc with `--js_out=import_style=commonjs` produces a *_pb.js file which does not export commonjs modules, it attaches the message functions directly to the global NodeJS namespace.

The code produced resembles this:
```
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.example.myservice.Mymessage', null, global);
```

The exportSymbol() calls write directly to a global 'this'.

I ran into this in a project with multiple instances of the same package at different versions, one direct and one transitive. Calls to deserializeBinary() in the direct dependency were calling deserializeBinaryFromReader() in the transitive dependency because the transitive dependency overwrote the global '.proto' member. Since the direct dependency was using gRPC 1.0.1 and the transitive was using gRPC 1.0.0, the object I was getting back was incompatible because the interface changed between those versions (protobuf maps were transformed into Lists in gRPC 1.0.0, gRPC 1.0.1 deserializes maps into Maps).

**Comment by drobertduke** [comment]
@murgatroid99

**Comment by murgatroid99** [comment]
`grpc_tools_node_protoc` just runs the base `protoc` with the gRPC plugin. So this is actually a bug with protobuf (https://github.com/google.protobuf).

**Comment by paralin** [comment]
I vote to close this one, especially after Protobuf.JS 6 is in. Either way, as @murgatroid99 says, it's an upstream bug.

**Comment by murgatroid99** [comment]
@paralin This is about the official protobuf compiler, not Protobuf.js.
