### ISSUE TITLE
CMake build system - can't build grpc++_reflection library

### ISSUE THREAD

**Issue by ppietrasa** [grpc/grpc#9192]
During the Windows build the compiler complains about the "reflection.grpc.pb.h" not being there:
```
[896/955] Building CXX object CMakeFiles\grpc++_reflection.dir\src\cpp\ext\proto_server_reflection.cc.obj
FAILED: D:\PROGRA~4\MICROS~1.0\VC\bin\amd64\cl.exe   /nologo /TP -D_WIN32_WINNT=0x600 -I. -Iinclude -I\include -I\src -IE:\dev\mkbpkgs.
tk\build\zlib-1.2.8-tpjgkkay.x86_64_win32_msvc2015_rel\include -Ithird_party\zlib -IE:\dev\mkbpkgs.tk\build\openssl-1.0.2h-cbkkoy5y.x86
_64_win32_msvc2015_rel\include -IE:\dev\mkbpkgs.tk\build\protobuf-3.1.0-occeobto.x86_64_win32_msvc2015_rel\include /DWIN32 /D_WINDOWS /
W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG /showIncludes /FoCMakeFiles\grpc++_reflection.dir\src\cpp\ext\proto_server_reflection.cc.obj /Fd
CMakeFiles\grpc++_reflection.dir\ /FS -c E:\dev\mkbpkgs.tk\.builds\grpc-1.0.0-imu4ty5n.x86_64_win32_msvc2015_rel\grpc-master\src\cpp\ex
t\proto_server_reflection.cc
E:\dev\mkbpkgs.tk\.builds\grpc-1.0.0-imu4ty5n.x86_64_win32_msvc2015_rel\grpc-master\src/cpp/ext/proto_server_reflection.h(41): fatal er
ror C1083: Datei (Include) kann nicht geöffnet werden: "src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h": No such file or direct
ory
ninja: build stopped: subcommand failed.
```

And indeed these and other needed files have been removed with this commit:
```
commit 169c985f676f634c33318b9748086f25478ddd9f
Author: Yuchen Zeng <zyc@google.com>
Date:   Fri Oct 14 15:58:09 2016 -0700

    Remove generated pb files

 [..]
 include/grpc++/ext/reflection.grpc.pb.h                                  |  186 --
 include/grpc++/ext/reflection.pb.h                                       | 2125 -----------------
 src/cpp/ext/proto_server_reflection.h                                    |   17 -
 src/cpp/ext/reflection.grpc.pb.cc                                        |   97 -
 src/cpp/ext/reflection.pb.cc                                             | 4045 ---------------------------------
 [..]
  26 files changed, 643 insertions(+), 7465 deletions(-)
```
The problem is there's nothing in the CMakeLists.txt that would generate these files. It may well be that other build systems that gRPC is equipped with do that.  But not CMake! 

It's a pity.  Apart from this issue the CMake stuff looks pretty solid.

**Comment by prateekr** [comment]
Also occurs on Centos 7.  I'd imagine this happens on all platforms using cmake from https://github.com/grpc/grpc/blob/master/CMakeLists.txt#L1573.  Both `src/cpp/ext/proto_server_reflection.cc` and `src/cpp/ext/proto_server_reflection_plugin.cc` require `src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h` to exist (i.e. to be generated from `src/proto/grpc/reflection/v1alpha/reflection.proto`) to compile successfully, yet there doesn't like to be anything indicating this dependency for the grpc++_reflection target.

**Comment by kskalski** [comment]
I tried to fix it by adding
`protobuf_generate_cpp(ReflectionProtoSources ReflectionProtoHeaders src/proto/grpc/reflection/v1alpha/reflection.proto)`

but it has two problems with built-in protobuf_generate_cpp from cmake's FindProtobuf:
- it doesn't allow specifying output directory for generated files, so they all land in the root build dir (I kind of managed to work around it with `file(RENAME ${ReflectionProtoHeaders} src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h)`)
- it doesn't allow using the grpc's cpp plugin, so service definition is ignored and the generated files won't be of much use

It seems that we need a custom / extended version of protobuf_generate_cpp, which gives ability to customize those two aspects

**Comment by ppietrasa** [comment]
FYI, I created a pull request  #9221 .  It addresses this issue by providing a custom protobuf_generate_grpc_cpp() as kskalski suggested + some more small annoyances I encountered.

**Comment by jtattermusch** [comment]
CC @jtattermusch
