### ISSUE TITLE
version mismatch between grpc and protobufjs

### ISSUE THREAD

**Issue by Arun-KumarH** [grpc/grpc#9196]
We are having issues loading grpc objects from protobuf builder objects.

prtobufjs : 6.0.2
grpc: 1.0.1

Below is the source code and I get an error when loading grpc objects 
`grpc.loadObject(this.$builder.ns)`

TypeError: Cannot read property 'className' of undefined
at Object.loadObject (node_modules/grpc/src/node/index.js:65:12)

Protobufjs suggested that this is due to mismatch of versions between grpc and protobufjs (i.e. grpc is still using protobuf 5).

https://github.com/dcodeIO/protobuf.js/issues/533

Could you please let us know when the fix for this would be available in grpc ?

Thank you.

**Comment by vanthome** [comment]
This is a really pressing point, can you given an ETA for this?

**Comment by murgatroid99** [comment]
As soon as #9004 works, the following release with use Protobuf.js 6 instead of Protobuf.js 5.

**Comment by Arun-KumarH** [comment]
We tried with grpc 1.1.0-pre1 version but it still seems to be using pbjs 5.0v - https://github.com/grpc/grpc/issues/9500 Could you please let us know when this will be available ?

**Comment by Arun-KumarH** [comment]
Could you please provide an ETA for this ?

**Comment by paralin** [comment]
You should use protobuf.js 5 until 6 is complete. I am completing the 6 PR today and hopefully it will be in soon.

**Comment by murgatroid99** [comment]
Protobuf.js 6 support is now in master, and will be available in gRPC 1.3.0.

**Comment by murgatroid99** [comment]
It is now possible to load a Protobuf.js 6 object using `grpc.loadObject`.
