### ISSUE TITLE
How to host grpc services in a c# windows service

### ISSUE THREAD

**Issue by raaghu16** [grpc/grpc#9197]
Can we host grpc services in a c# windows service? Currently we used a console application and it didn't work when we convert this console application to a windows service.

**Comment by jtattermusch** [comment]
There are no restrictions on the gRPC C# side in terms of what application type you have to use. If you cannot run console applications as a windows service, use some other application type (which you can).

**Comment by jtattermusch** [comment]
Please reopen if you still have issues.
