### ISSUE TITLE
UDS connect error with node.js

### ISSUE THREAD

**Issue by cyberflohr** [grpc/grpc#9198]
A GRPC node client which is using UDS for communication with the GRPC server, will use a HTTP proxy if the environment variable http_proxy is set. This is not correct, UDS must not use a HTTP proxy.

Below you can see the program output   (GRPC_TRACE=all GRPC_VERBOSITY=DEBUG) - the first line is is the important one. 

To reproduce the problem you can use the greeter client & server from the grpc/examples/node/dynamic_codegen directory and change the TCP endpoint to UDS e.g. /tmp/test.sock. Before starting the client make sure the http_proxy env variable is set. 

`I1225 09:06:05.005114486    6037 http_connect_handshaker.c:209] Connecting to server /tmp/test.sock via HTTP proxy localhost:8080
D1225 09:06:05.005125689    6037 tcp_posix.c:440]            WRITE 0x2658a8552d40 (peer=unix:/tmp/test.sock): 43 4f 4e 4e 45 43 54 20 2f 74 6d 70 2f 74 65 73 74 2e 73 6f 63 6b 20 48 54 54 50 2f 31 2e 30 0d 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 3a 38 30 38 30 0d 0a 55 73 65 72 2d 41 67 65 6e 74 3a 20 67 72 70 63 2d 68 74 74 70 63 6c 69 2f 30 2e 30 0d 0a 0d 0a 'CONNECT /tmp/test.sock HTTP/1.0..Host: localhost:8080..User-Agent: grpc-httpcli/0.0....'`

`D1225 09:06:05.005142817    6037 connectivity_state.c:156]   SET: 0x2658a86b1bd8 client_channel: IDLE --> CONNECTING [lb_changed] error=(nil) "No Error"
D1225 09:06:05.005146384    6037 connectivity_state.c:109]   CONWATCH: 0x2658a8651998 (null): from CONNECTING [cur=CONNECTING] notify=0x2658a864ef08`

`D1225 09:06:06.005774154    6045 tcp_posix.c:176]            read: error={"created":"@1482653166.005708271","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}`

`D1225 09:06:06.005820710    6045 connectivity_state.c:156]   SET: 0x2658a86b1d00 subchannel: CONNECTING --> TRANSIENT_FAILURE [connect_failed] error=0x2658a8ac5460 {"created":"@1482653166.005788374","description":"Connect Failed","file":"../src/core/ext/client_channel/subchannel.c","file_line":635,"grpc_status":14,"referenced_errors":[{"created":"@1482653166.005708271","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}`

**Comment by markdroth** [comment]
We can probably change the code that looks at the http_proxy environment variable skip what it's doing if the target is a UDS.
