### ISSUE TITLE
Client authentication in Ruby

### ISSUE THREAD

**Issue by aaron-lim** [grpc/grpc#9200]
Is there any way for an RPC method to authenticate a client based on a TLS certificate (in Ruby)
An example of how I can get the **Common Names** value would be great.

**Comment by apolcyn** [comment]
@aaron-lim though there's no API for examining the client cert in the server app's code, SSL/TLS client auth is supported.

This can be done by creating the proper `GRPC::Core::Credentials` object and passing it to your client stub's constructor.

http://www.grpc.io/docs/guides/auth.html gives some example usage of the `GRPC::Core::Credentials` object for server auth.

For client auth, e.g. you could pass not only the root certs pem string to the constructor but also a private key and cert chain for the client to use.

Some documentation pulled from the comment above the `Credentials`  (native) constructor implementation:
```
/*
  call-seq:
    creds1 = Credentials.new()
    ...
    creds2 = Credentials.new(pem_root_certs)
    ...
    creds3 = Credentials.new(pem_root_certs, pem_private_key,
                             pem_cert_chain)
    pem_root_certs: (optional) PEM encoding of the server root certificate
    pem_private_key: (optional) PEM encoding of the client's private key
    pem_cert_chain: (optional) PEM encoding of the client's cert chain
```

does this fit your use case?
