### ISSUE TITLE
goaway_server_test flakes under asan 

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#9204]
D1222 06:12:04.050713024   26413 dns_resolver.c:197]         retrying in 1.000000000 seconds
E1222 06:12:05.054518783   26286 goaway_server_test.c:191]   assertion failed: GRPC_CHANNEL_READY == grpc_channel_check_connectivity_state(chan, 0)

**Comment by dgquintas** [comment]
It seems we haven't seen this in a while. Closing.

**Comment by dgquintas** [comment]
Seen again. Reopening. https://grpc-testing.appspot.com/job/gRPC_master_tsanitizer_c/780/testReport/junit/(root)/c_linux_tsan/bins_tsan_goaway_server_test_GRPC_POLL_STRATEGY_poll/

easy to reproduce locally: `./tools/run_tests/run_tests.py -l c -c tsan -r goaway_server_test -n inf -S -a 10`

**Comment by dgquintas** [comment]
This also happens for regular builds such as `opt`
