### ISSUE TITLE
Move PHP to the new secure server API

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#921]
This is part of addressing #135. This change eliminates grpc_secure_server_create() and has credentials passed instead to grpc_server_add_secure_http2_port.

Please prepare a pull request against ctiller/grpc:credit

**Comment by ctiller** [comment]
Hey - just wanted to ping this and get an estimate as to when it'll be done.

**Comment by ctiller** [comment]
(Recreated pull request is #835)

**Comment by murgatroid99** [comment]
I'm planning to work on this over the next couple of days. I definitely think I can get it done before Friday.

**Comment by ctiller** [comment]
Fixed, yes?
