### ISSUE TITLE
the problem about cpp GRPC TLS

### ISSUE THREAD

**Issue by Dustskyfield** [grpc/grpc#9210]
Dear,
When I use TLS channel between grpc server and client, there are error info as follows:
1. Use the test cert support by grpc example. it gives error "No match found for server name: 10.120.100.185".  I think it may be not inclue my IP in test cert, right? what should I do for it?

2. I produce the cert file by myself. command is as follows.
openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.pem -days 365 -nodes -config /etc/ssl/openssl.cnf
openssl req -new -x509 -in server.pem -key server.key -out ca.pem -days 3650

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
IP.1 = "10.120.100.185"
[ v3_ca ]
subjectAltName = IP:10.120.100.185

 However, it give me error:
Security handshake failed: {"created":"@1483000856.994115906","description":"Handshake read failed","file":"src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1483000856.994109110","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}

How do I produce the cert file? Or I use the cert file unrightly ? Could some expert give help? Thanks

**Comment by yang-g** [comment]
When you use the test cert in grpc, you will need something like (C++):
```
channel_args.SetSslTargetNameOverride("foo.test.google.fr");
channel  = CreateCustomChannel(target, creds, channel_args);
```
You can find examples in create_test_channel.cc.

**Comment by Dustskyfield** [comment]
OK, I have resolved it by referring another case.
And, I have another doubt about it.  The server would check the subject_alt_name IP address and I must add IP during producing certificate files.  I hope to know whether the subject_alt_name IP must be checked when handshake ? could I use a default cert file for all hosts ?

thanks

**Comment by yang-g** [comment]
I guess you can use a name in your server cert, say foo.com and then connect to the server ip with the ssl target name override set to foo.com (see above comment for api). 

I do not think you can disable name checking entirely.
