### ISSUE TITLE
Mixing authenticated and unauthenticated RPC methods in the same service

### ISSUE THREAD

**Issue by NGNeer** [grpc/grpc#9211]
I reviewed all open issues (714 at the time of this writing) and searched for pertinent keywords in the repository, but was unable to find a reference or a solution to the issue described below.

The scenario is the trivial one of a login call (over an SSL channel) returning a token for future use by the calling client. In order to avoid littering application code on the server with token verification, the gRPC architecture wisely offers interception capabilities. At least in C++ server code, these are in the form of a subclassed AuthMetadataProcessor, receiving the token and being responsible for validating it.

How can the interceptor be made to distinguish between calls requiring use of the token and calls that do not require it, such as the login call (which by definition cannot require a token)?

In the standard usage model, the code implementing the service method is only called after the interceptor code is, meaning that conveying the call information to the interceptor is not a viable option.

If the interceptor cannot be made to distinguish between calls, then a chicken-and-egg scenario arises whereby the login call for producing the token must be made with the token to begin with. This can be resolved by having separate services for authenticated and unauthenticated methods, or by having each service method perform or not perform token verification on its own -- both suboptimal solutions.

Three avenues of investigation thus far:

1. The closest reference I could find is an old [authentication discussion](https://groups.google.com/forum/#!msg/grpc-io/iLHgWC8o8UM/VW4WVghtUOcJ), where it is mentioned that "on the server-side you cannot discriminate between connections because the ServerContext does not give you access to this information." This may or may not be pertinent to the question above.

2. Independent debugging of the C++ server reveals that in the AuthMetadataProcessor implementation, the 'auth_metadata' parameter contains a ':path' key whose value indicates the called method. Can this value be trusted? Can it be tampered with? Or is it safe for an AuthMetadataProcessor to rely on it for distinguishing between calls requiring authentication and calls that do not?

3. The only usage of an AuthMetadataProcessor in the source tree is at:
grpc\test\cpp\end2end\end2end_test.cc
However, the tests only implement a single service method, and in the secure case (SecureEnd2endTest), the client sets the token as metadata directly, and the token is assumed to be present by the server.

**Comment by jboeuf** [comment]
Hello.

You can use the `:path` metadata indeed if you want to distinguish between services/methods. It is trusted by virtue of the fact that it is protected on the channel by TLS and is used on the server side to dispatch the call to the right handler.

Cheers!

**Comment by NGNeer** [comment]
Yay! Thank you Julien so much for confirming!
