### ISSUE TITLE
Secure read failed. Cloud logging error

### ISSUE THREAD

**Issue by kamal8** [grpc/grpc#9217]
GaxError: GaxError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, {"created":"@1483127097.850480734","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1483127097.850427988","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}]})>)

**Comment by umairda** [comment]
Probably similar to this: https://github.com/grpc/grpc/issues/7804

**Comment by jtattermusch** [comment]
What language is this?

**Comment by kpayson64** [comment]
Fixed by #11154
