### ISSUE TITLE
Don't send SNI warning alerts

### ISSUE THREAD

**Issue by davidben** [grpc/grpc#9219]
gRPC currently sends a warning alert on SNI mismatch:
https://github.com/grpc/grpc/blob/0fa0f38449c394e24fc9d336a39c0cda5aae1108/src/core/lib/tsi/ssl_transport_security.c#L1273

Per RFC 6066:
>   If the server understood the ClientHello extension but
>   does not recognize the server name, the server SHOULD take one of two
>   actions: either abort the handshake by sending a fatal-level
>   unrecognized_name(112) alert or continue the handshake.  It is NOT
>   RECOMMENDED to send a warning-level unrecognized_name(112) alert,
>   because the client's behavior in response to warning-level alerts is
>   unpredictable.

This is referring to the fact that some clients treat warning alerts as fatal and while others completely ignore them. Warning alerts are rather pointless. In TLS 1.3, they have been removed and treated as fatal.

Was there a particular reason for sending it? If not, probably best not to. `SSL_TLSEXT_ERR_NOACK`? (Although whether the server ACKs the SNI or not also basically doesn't do anything. :-) )

**Comment by jboeuf** [comment]
@justinburke can you have a look at this too? Thanks!

**Comment by jiangtaoli2016** [comment]
fixed at https://github.com/grpc/grpc/pull/22332
