### ISSUE TITLE
grpc issue with mod_wsgi restricted mode

### ISSUE THREAD

**Issue by hir3npatel** [grpc/grpc#9223]
I use apache2 and mod_wsgi with django. I pip install google-cloud and use the datastore python library from there. I use grpcio (1.0.4) and grpc-google-cloud-datastore-v1 (0.14.0).

I am getting the following error from mod_wsgi on apache2.

> [wsgi:error] [pid 10] Exception IOError: 'file() constructor not accessible in restricted mode' in 'grpc._cython.cygrpc.ssl_roots_override_callback' ignored

That seems to then cause this error from apache

> security_connector.c:656] assertion failed: pem_root_certs != NULL

And the apache child process then aborts. This issue appears on GKE but not locally using the datastore emulator with no authentication.

**Comment by hir3npatel** [comment]
This WSGI config for apache seems to get around the issue:

WSGIApplicationGroup %{GLOBAL}

**Comment by nathanielmanistaatgoogle** [comment]
Are you able to share with us sample code that reproduces the issue?

**Comment by speedplane** [comment]
I'm using the same setup (apache2, mod_wsgi, django, pip install google-cloud, datastore library). Got the same error:

```
>tail -f /var/log/apache2/error.log
[Thu Feb 16 02:27:00.951292 2017] [core:notice] [pid 2045:tid 140530328823680] AH00052: child pid 2048 exit signal Aborted (6)
[Thu Feb 16 02:27:00.951349 2017] [core:notice] [pid 2045:tid 140530328823680] AH00052: child pid 2049 exit signal Aborted (6)
[Wed Feb 15 20:27:02.359045 2017] [:error] [pid 2106:tid 140530200073984] Exception IOError: 'file() constructor not accessible in restricted mode' in 'grpc._cython.cygrpc.ssl_roots_override_callback' ignored
E0215 20:27:02.359092916    2112 security_connector.c:621]   assertion failed: pem_root_certs != NULL
[Thu Feb 16 02:27:02.957575 2017] [core:notice] [pid 2045:tid 140530328823680] AH00052: child pid 2106 exit signal Aborted (6)
[Wed Feb 15 20:27:07.786208 2017] [:error] [pid 2143:tid 140530113570560] Exception IOError: 'file() constructor not accessible in restricted mode' in 'grpc._cython.cygrpc.ssl_roots_override_callback' ignored
E0215 20:27:07.786246016    2178 security_connector.c:621]   assertion failed: pem_root_certs != NULL
[Thu Feb 16 02:27:07.965492 2017] [core:notice] [pid 2045:tid 140530328823680] AH00052: child pid 2143 exit signal Aborted (6)
[Wed Feb 15 20:27:08.164238 2017] [:error] [pid 2142:tid 140530200073984] Exception IOError: 'file() constructor not accessible in restricted mode' in 'grpc._cython.cygrpc.ssl_roots_override_callback' ignored
```

**Comment by hir3npatel** [comment]
Hi @nathanielmanistaatgoogle I don't think code samples matter, it isn't stack tracing at any specific line in the app code, it looks like it fails on library init, somewhere in the library that tries to do auto auth of system creds on GCP. Locally when I use the datastore emulator with no auth, I have no such issues, the library init's fine locally. As per my first post, the error seems to be that the auth code of the library is using file() constructor which isn't allowed in python restricted mode, which mod_wsgi seems to default to. Using the setting in my second post seems to disable python restricted mode, and then the library init works again.

**Comment by nathanielmanistaatgoogle** [comment]
I'm not sure that there's anything we can do here - we don't use `file` in our code (we use `pkg_resources`, which may use `file` or may use something else that may use `file` or...).

Does restricted mode have a supported story for how Python code is supposed to load data assets from its own package?

**Comment by hir3npatel** [comment]
Yeah I agree, file is deprecated in python 3, it's just an issue with python 2. Given that the workaround works, you could perhaps just document it and close this issue. I guess this won't be relevant with python 3 going forward anyway. googling suggests that file should be replaced with open, but if it's not in your code I don't expect you to go hunt it down and fix it. Thanks though!
