### ISSUE TITLE
csharp_macos_opt.csharp.Grpc.Core.Tests.AppDomainUnloadTest

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#9225]
https://grpc-testing.appspot.com/job/gRPC_master_macos/1090/testReport/junit/(root)/csharp_macos_opt/csharp_Grpc_Core_Tests_AppDomainUnloadTest/

**Comment by dgquintas** [comment]
@jtattermusch ping

**Comment by jtattermusch** [comment]
the job with log has been deleted - without access to logs this is not actionable.
