### ISSUE TITLE
Objective C example build failed

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#9227]
https://grpc-testing.appspot.com/job/gRPC_master_macos/1090/testReport/junit/(root)/aggregate_tests/run_tests_objc_macos_opt/

**Comment by muxi** [comment]
Should be fixed. Wait for a few days to close.

**Comment by nathanielmanistaatgoogle** [comment]
Agreed that this appears fixed as of [`gRPC_master_macos` build 1103](https://grpc-testing.appspot.com/job/gRPC_master_macos/1103/).
