### ISSUE TITLE
VS build scripts don't work

### ISSUE THREAD

**Issue by aardappel** [grpc/grpc#9231]
```
C:\dev\grpc-master\vsprojects\build_vs2010.bat

setlocal
Setting environment for using Microsoft Visual Studio 2010 x86 tools.
Microsoft (R) Build Engine version 4.6.1087.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```
This does work `C:\dev\grpc-master\vsprojects\build_vs2010.bat grpc.sln`, but unlike what @jtattermusch suggests here: https://github.com/grpc/grpc-experiments/issues/173 it still fails on openssl & zlib dependencies. It also complains about more basic stuff like missing `inttypes.h`.

**Comment by ctiller** [comment]
I'm surprised we still have tooling laying around for vs2010, it's highly unlikely that we'll build there at this point (we piled our chips heavily into C99 for C core, and pre-2013 msvc's don't play well there).

**Comment by aardappel** [comment]
Then maybe delete the 2010 related build files, to not give the impression that they're supported :)

**Comment by ctiller** [comment]
https://github.com/grpc/grpc/pull/9238

**Comment by aardappel** [comment]
Now made sure to clone --recursive, building with 2015, but SSL still doesn't find its own headers:

`c:\dev\grpc\third_party\boringssl\crypto\asn1\tasn_enc.c(57): fatal error C1083: Cannot open include file: 'openssl/asn1.h': No such file or directory [C:\dev\grpc\vsprojec ts\vcxproj\boringssl\boringssl.vcxproj]`

**Comment by aardappel** [comment]
Opening the boringssl project in VS to try and fix the issue causes:

```
Unable to read the project file "boringssl.vcxproj".

C:\dev\grpc\vsprojects\vcxproj\boringssl\boringssl.vcxproj(55,5): The imported project "C:\dev\grpc\vsprojects\vcxproj\vsprojects\global.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and we think your issue might be fixed. If you are still experiencing this issue with Windows builds, please re-open the issue with information on how to reproduce.

**Comment by aardappel** [comment]
@mehrdada if it is fixed, maybe link to the commit where it was fixed?

**Comment by mehrdada** [comment]
@aardappel Sorry for the confusion. I meant we expect Windows build to work fine; I did not mean building via VSProjects in particular. That said, there is a pull request in flight to mark pre-generated VSProjects as deprecated and make CMake the recommended solution on Windows (https://github.com/grpc/grpc/pull/11462).

In any case, if you feel this issue should remain open (in light of the pull request I linked it), please let me know and I'll reopen it.
