### ISSUE TITLE
Unable to write to response stream

### ISSUE THREAD

**Issue by granthobbs** [grpc/grpc#9233]
Hi,

Could you tell me why I am unable to write to the response stream from an event?

See below, the line //This works is working fine for multiple writes, but the one at the bottom //This doesn't fails with a halfclose error. It successfully writes once but then fails on subsequent attempts.

Thanks

Grant

` public override async Task PlaceOrder(TtGrpcProto.Order request, IServerStreamWriter<TtGrpcProto.Fill> responseStream, ServerCallContext context)
        {

            List<Fill> test = new List<Fill>();

            TtGrpcProto.Fill f1 = new Fill();
            f1.Instrument = new Instrument();
            f1.Instrument.Asset = "one";

            TtGrpcProto.Fill f2 = new Fill();
            f2.Instrument = new TtGrpcProto.Instrument();
            f2.Instrument.Asset = "two";

            TtGrpcProto.Fill f3 = new Fill();
            f3.Instrument = new Instrument();
            f3.Instrument.Asset = "three";

            test.Add(f1);
            test.Add(f2);
            test.Add(f3);

            //This works
            foreach (var fill in test)
            {
                System.Threading.Thread.Sleep(2000);
                await responseStream.WriteAsync(fill);
            }

            try
            {
                var tcsFilled = new TaskCompletionSource<TaskResult>();
                AutoResetEvent queueResetEvent = new AutoResetEvent(true);
                Task.Run(() =>
                {
                    var ins = _tt.GetInstrument(request.Instrument);
                    //Inline event
                    _tt.OnPlaceOrderFilled += (async delegate(Object oOrder, TtRpcPlaceOrderEventArgs argOrder)
                    {
                        TaskResult resultOrder = new TaskResult();
                        resultOrder.Value = argOrder.Fill;
                        resultOrder.Result = argOrder.IsOk;

                        //This doesn't
                        foreach (var fill in test)
                        {
                            await responseStream.WriteAsync(fill);
                        }`

**Comment by MatthiasWeiser** [comment]
I have had similar issues. I think that the responseStream is tied to the Task 'PlaceOrder'.
For my personal code usage it is best to use the Bufferblock from the Dataflow TPL as a sync mechanism at it allows async queue processing fitting to the gRPC style.

**Comment by granthobbs** [comment]
Cool thanks
