### ISSUE TITLE
Can't receive detail message when server's codepage is different and message is Japanese in C#

### ISSUE THREAD

**Issue by neuecc** [grpc/grpc#9235]
If gRPC's Server returns error code and `Status.Detail` include language specific character(e.g. `あいうえお` in Japanese)
gRPC's Client can't decode detail message(the result is null).
This problem happens on each server and client have different codepage.
for example Server's CodePage is 437(default of GCP's Windows Server) and Client's CodePage is 932(default of Japanese Windows)

This occurs from `Marshal.PtrToStringAnsi`
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/BatchContextSafeHandle.cs#L74

Marshal.PtrToStringAnsi's encoding is environment dependent.
(and our gRPC client run on mono(Unity), mono's encoding is only supports UTF8 http://www.mono-project.com/docs/advanced/pinvoke/#strings )

Does gRPC support language specific string in status.detail?
Otherwise should this implementation be fixed it?

We try to send error details in Metadata for workaround,
But we can't get metadata in `RpcException`.
It is closed https://github.com/grpc/grpc/issues/8042 but useful...
We want to receive `GetTrailers` from `RpcException`.

**Comment by ctiller** [comment]
Which version of gRPC are you using?

**Comment by neuecc** [comment]
sorry, I've using `Grpc.Core 1.0.1`.

**Comment by apolcyn** [comment]
@neuecc just for the Metadata workaround, is the problem here of not being able to access trailers only for blocking unary calls? Just as mentioned in #8042, the trailers are available on the call object, which is accessible on all calls besides blocking-unary.

**Comment by neuecc** [comment]
@apolcyn Yes, trailers can be taken from the call object.
However, it is not possible to take a call object from outside the scope, for example, if you want to implement common processing in all methods.
Normally, we will take such exception and do common processing, in that case we should get the necessary information from Exception.
For example, `WebException` can take a response body to get error details.

**Comment by carl-mastrangelo** [comment]
This should have been fixed by https://github.com/grpc/grpc/issues/4672  which handles unicode characters properly. I believe Java and Go already handle this properly.
