### ISSUE TITLE
Objective C build failing with linker error

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#9241]
https://grpc-testing.appspot.com/job/gRPC_master_macos/1103/testReport/junit/(root)/objc_macos_dbg/objc_tests/

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2446/testReport/junit/(root)/objc_macos_opt/objc_tests/

pr #9580 against master

**Comment by muxi** [comment]
no longer appearing
