### ISSUE TITLE
Terminology for failed/cancelled RPCs in early adopter Python interface

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc#926]
https://github.com/grpc/grpc/blob/2e165e34010e44f20c6ecea63b20a6996810313f/src/python/src/grpc/early_adopter/interfaces.py

...uses terminology like:

"abortion_callback: A callable to be called and passed an Abortion value
        in the event of RPC abortion."

I know what it *means*, but "abortion" is a very loaded term and may not read well in some cultures. A Google search for "RPC Abortion" gives two pages of results about legislation for termination of pregnancy in the Phillipines...

**Comment by nathanielmanistaatgoogle** [comment]
So this was something I tried to address back in the autumn and was never actually able to drive to completion: what is one single word that should cover all the unsuccessful cases of RPC termination? One umbrella term for all of cancelled, expired, client-did-something-illegal, server-did-something-illegal, connection-was-severed, and so on? "abortion" always seemed to me the most technically precise.

**Comment by LisaFC** [comment]
Off the top of my head, "termination" works better. I'll see if I can come up with anything else.

**Comment by nathanielmanistaatgoogle** [comment]
Yeah, "termination" already means "the end of the RPC whether it was successful or unsuccessful", and that meaning comes naturally from the established use of "termination" elsewhere in software engineering.

**Comment by LisaFC** [comment]
Hmm, I'd have thought of an RPC that's finished with no errors etc. as "completed", "termination" has more connotations of "someone has actively stopped this".

**Comment by LisaFC** [comment]
How about AbnormalTermination?

**Comment by soltanmm** [comment]
Is this something we still care about?

**Comment by LisaFC** [comment]
I think so, unless it's already been changed.

**Comment by jcanizales** [comment]
As this is still open, my 2c: wherever I've had to write it, I've always used "succeeded", "failed", "completed successfully" and "completed with a failure".

**Comment by nathanielmanistaatgoogle** [comment]
Closing; the term "abortion" does not appear in the gRPC Python GA API.
