### ISSUE TITLE
Unable to build grpc for c++

### ISSUE THREAD

**Issue by anilmaddala** [grpc/grpc#9260]
I am following the instuctions from [grpc/cpp](https://github.com/grpc/grpc/tree/master/src/cpp) build grpc on my local machine.

I am getting the following error:
`In file included from ./src/compiler/config.h:37:0,
                 from ./src/compiler/csharp_generator.h:37,
                 from src/compiler/csharp_generator.cc:39:
include/grpc++/impl/codegen/config_protobuf.h:38:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
 #include <google/protobuf/stubs/common.h>
                                          ^
compilation terminated.
`
Can you point to me what I am missing?

**Comment by ncteisen** [comment]
Have you installed protobuf onto your system? Just running `git submodule update --init`
Try doing this
```
cd third_party/protobuf
./autogen.sh
./configure
make
make check
sudo make install
```

**Comment by anilmaddala** [comment]
@ncteisen Thank you. yes that worked.

For anyone running into missing gmock-1.7.0.zip please refer to [https://github.com/grpc/grpc/issues/7952](url)
