### ISSUE TITLE
python grpc: confusion with grpc._channel._Rendezvous

### ISSUE THREAD

**Issue by timfeirg** [grpc/grpc#9270]
I have a golang server and a python client, communicating using grpc, when the remote server returns an error, a `grpc._channel._Rendezvous` will raise on the python end.

Should I capture this exception? I mean, it's prefixed with underscore, and the exception class resides in `grpc._channel`, which in the python world means it's not meant to be used by clients.

Also, I noticed this has something to do with stub initializations, if I initialize the grpc stubs using the beta methods provided in the `grpc` package:

```python
            channel = grpc.beta.implementations.insecure_channel(self.grpc_host, self.grpc_port)
            return core_pb2.beta_create_CoreRPC_stub(channel)
```

A golang error will cause python to raise a `grpc.framework.interfaces.face.face.AbortionError`.

But if I do this:

```python
            channel = grpc.insecure_channel(self.grpc_address)
            return core_pb2.CoreRPCStub(channel)
```

Then any golang error from the remote grpc server will raise in the form of `grpc._channel._Rendezvous`

In the end I'm asking the same question as https://github.com/grpc/grpc/issues/3436, but the main question here is I guess, **what the heck is this `_Rendezvous`?**

**Comment by tonicbupt** [comment]
same problem, used to be `AbortionError`, now it's `_Rendezvous`.
the error was that `err` returned by golang server

**Comment by kpayson64** [comment]
The exception API changed between the beta and GA API.

In the GA API, clients should catch ```grpc.RpcError```s.  ```_Rendezvous``` is the underlying internal type, and is subject to change so you should avoid catching this type directly.

**Comment by tonicbupt** [comment]
🙀 so exceptions like `AbortionError` are replaced by `grpc.RpcError` ... got ...

**Comment by tonicbupt** [comment]
but as I see, `NoStubError` and `AbortionError` has no inherited relationship with `RpcError` ... does this mean that in GA API, only `RpcError` will be raised and no more exceptions in `framework/interfaces/face/face.py` will be raised?

**Comment by kpayson64** [comment]
Correct.  The old exception types are not part of the GA API.

**Comment by timfeirg** [comment]
closing this issue now, however I think it's best to reflect this conclusion somewhere in the documents.

**Comment by genericmoniker** [comment]
I'm still confused. In #3436, there is the suggestion to call `context.set_details` on the server side, but on the client side, the only way I see to access the details is through `_Rendezvous._state.details`. `RpcError` doesn't have `_state` itself, and even if it did it is "private".  

Is there up-to-date guidance somewhere about how to send application errors over gRPC?

**Comment by eaglo** [comment]
Was the above question ever answered?

**Comment by timfeirg** [comment]
see https://github.com/grpc/grpc/issues/9270#issuecomment-270991114 @eaglo ?

**Comment by eaglo** [comment]
thanks, but i was referring to this comment here:

> I'm still confused. In #3436, there is the suggestion to call context.set_details on the server side, but on the client side, the only way I see to access the details is through _Rendezvous._state.details. RpcError doesn't have _state itself, and even if it did it is "private".
> Is there up-to-date guidance somewhere about how to send application errors over gRPC?

**Comment by genericmoniker** [comment]
If an `RpcError` happens to be a `_Rendezvous`, it will have a `details` method, so I ended up doing something like:

``` 
    try:
        message = rpc_error.details()
    except AttributeError:
        message = str(rpc_error)
```
I'm open to better guidance, though.

**Comment by eaglo** [comment]
yeah i think i'm going to do the same ... thats very unsatisfying ... i wonder how other people solve it

**Comment by nathanielmanistaatgoogle** [comment]
This part of the API hinges on the fact that where `grpc.RpcError`s are raised on the invocation-side of an RPC, the object that is raised is never _solely_ a `grpc.RpcError`. See [the `Raises` section of `grpc.UnaryUnaryMultiCallable.__call__`: "The raised RpcError will also be a Call for the RPC affording the RPC’s metadata, status code, and details.".](https://grpc.io/grpc/python/grpc.html#grpc.UnaryUnaryMultiCallable.__call__) So invocation-side code that needs to handle errors (probably all but the simplest code) should look like
```python
try:
  my_response = my_stub.MyMethod(my_request)
except grpc.RpcError as rpc_error_call:  # Since this object is guaranteed to be a grpc.Call, might as well include that in its name.
  my_code = rpc_error_call.code()
  my_details = rpc_error_call.details()
```
. Yes, you should not write abstraction-violating code that accesses underscore-prefixed private code elements of another system. We are going to get rid of `grpc._channel._Rendezvous` at some point...

**Comment by eaglo** [comment]
Hi @nathanielmanistaatgoogle thanks thats actually very helpful. Would be nice if this snippet and the mention of the grpc.Call was part of the python grpc introduction as well - it is kind of hard imo to find that out from the API reference. 

Are there any plans to extend the interface of an RpcError as well?

I only know of this page atm http://avi.im/grpc-errors/ and the handling they present on the python client isn't really reassuring. If i would have known that the error is guaranteed to be an grpc.Call it would have been more obvious that i can use these methods. 

Additionally i was wondering if there is some kind of specification of what an error has to conform to or how it is transmitted and which fields it should have. If you take a look at Node at the website i mentioned earlier: they use 'code' and 'message' instead of 'code' and 'details'. The 'code' field seems to be the only constant thing.

Would it be allowed (or even possible) to use for example a custom error code and a protobuf message as details?

**Comment by hozn** [comment]
This is kinda terrible ... 

If the RpcError have these attributes/methods, they should be defined on that class.  Or create multiple concrete RpcError subclasses that mixin the appropriate "parent" Call etc. classes that define these methods.

**Comment by eaglo** [comment]
any more information on this? :/
