### ISSUE TITLE
Are there plans to bring gRPC to .NET Core?

### ISSUE THREAD

**Issue by SamuelCox** [grpc/grpc#9277]
From what I've looked up on google, currently gRPC isn't compatible with .net core. Are there plans to bring it over? Would be a great addition.

**Comment by apolcyn** [comment]
yes the 1.0.1 release supports .net core - it has a `netstandard1.5` target. It also supports the previously supported .NET 4.5. (see https://www.nuget.org/packages/Grpc.Core/)
