### ISSUE TITLE
Setting php namespace in proto fails

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#9278]
Setting the option `php.namespace` in proto files fails with `Option "php_package" unknown`. The option is described in the repo [here](https://github.com/stanley-cheung/Protobuf-PHP#generating-php-classes). I'm using protoc-gen-php to generate the proto files.

I have tried these as the name of the option, all of them get similar error messages though.
- `php.namespace`
- `php_namespace`
- `namespace`
- `php.package`
- `php_package`
- `package`

I'm trying to achieve the same result as the java option https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.proto#L33 here.

**Comment by stanley-cheung** [comment]
gRPC has switched to use the official Google protobuf implementation since v1.1.0 has been released. Please check whether this option is supported there. If you need this option, please file an enhancement request to that repo.

**Comment by tbillington** [comment]
Implemented in https://github.com/grpc/grpc/pull/11886.
