### ISSUE TITLE
Receive Metadata from Go Client

### ISSUE THREAD

**Issue by rogerza** [grpc/grpc#9292]
I have a Go client and a Python server. When I send metadata from the client to the server, the metadata is not present on the server side

Client:
	md := metadata.Pairs("foo", "val")
	ctx := metadata.NewContext(context.Background(), md)
        client.MyCall(ctx, &message)

Server:
       context.invocation_metadata()   # all I get from this is (('user-agent', 'grpc-go/1.0'),)

Is there a way to send metadata from a Go client to the server?

**Comment by menghanl** [comment]
What you did seems correct.
Can you provide a small test to reproduce?

**Comment by rogerza** [comment]
well, this may actually be a local application issue. I made a basic test repo and when I run the python server and GO client, the metadata is there, as expected. I will keep testing.

https://github.com/rogerza/grpc_hello

**Comment by srini100** [comment]
If this issue still exists please open in grpc/grpc-go repo.
