### ISSUE TITLE
gRPC Master Linux has Been Failing

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#9293]
sanity_linux_opt.tools/buildgen/generate_projects.sh has been failing on Master Linux for a few days now. See [here](https://grpc-testing.appspot.com/job/gRPC_master_linux/) The failure was introduced when now files were added to the Doxygen files. The PR was #9273.

#9285 did not fix this issue. It turns out that running generate_projects.sh has different effects if you run on MacOS vs Linux. It changes the order of the files listed in the tools/doxygen/* files

**Comment by ericgribkoff** [comment]
It might be the use of `glob`, which seems to return an unsorted result: https://github.com/grpc/grpc/blob/master/templates/tools/doxygen/Doxyfile.include#L798

**Comment by ctiller** [comment]
Fix incoming
