### ISSUE TITLE
Do better write-coalescing for WINDOW_UPDATE writes

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#9306]
When running grpc streaming benchmarks, I noticed that the grpc client is almost doing one tcp `write` per `WINDOW_UPDATE` frame (in some cases it gets coalesced with other writes but I noticed that in most of the cases it doesnt).

This can be observed by turning the `flowctl`, `http` and 'tcp` traces and on DEBUG builds
i.e 
```
$ # Start a streaming benchmark server in a different window
$ export GRPC_VERBOSITY=DEBUG 
$ export GRPC_TRACE=flowctl,http,tcp
$ # Run the streaming client
```

**Comment by ctiller** [comment]
Done!
