### ISSUE TITLE
error on grpc install

### ISSUE THREAD

**Issue by justbill2020** [grpc/grpc#9312]
Hi Guys, doing an npm install. during the install and I got this message. Is this OK?
node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v48-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@6.9.4 (node-v48 ABI) (falling back to source compile with node-gyp)

it seems like this happens during the install of electron... figured i would start here...

**Comment by murgatroid99** [comment]
When you say "the install *of* electron", do you mean that you are trying to install electron itself, or that you are trying to install some library to use with electron?

If you're trying to install something to use with electron, we don't have precompiled binaries for ARM. We also don't yet support electron, and when we do, you will have to follow [electron's instructions for installing native node modules](http://electron.atom.io/docs/tutorial/using-native-node-modules/).

**Comment by Martin-Pitt** [comment]
You should have an Electron setup configured to handle native node_modules, e.g. with https://github.com/electron/electron-rebuild

I personally use a simplified version of the https://github.com/BZCoding/SkelEktron boilerplate.

I'll be testing this with GRPC myself soon, but right now that's the most I can contribute/help with.

**Comment by murgatroid99** [comment]
The npm module grpc@1.1.0-pre1 should now work on electron. Make sure that you follow the instructions in the electron docs for [installing native modules](http://electron.atom.io/docs/tutorial/using-native-node-modules/). You should be able to omit the line `export npm_config_build_from_source=true` to install the precompiled binary file for electron.

**Comment by paralin** [comment]
I'd recommend closing this, either way this is a warning and not a error. You should have gotten the from-source version of GRPC. It takes a bit longer to install, but might even work better on your platform than the pre-compiled binaries.
