### ISSUE TITLE
Gmock links for protobuf have moved

### ISSUE THREAD

**Issue by chrisbaume** [grpc/grpc#9313]
gRPC depends on protobuf v3.0.0. In protobuf's autogen.sh it downloads gmock, but the links in v3.0.0 are broken.

The solution is to apply this patch in third_party/protobuf after updating the submodules:
https://github.com/google/protobuf/commit/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0.patch

Alternatively, add something to the README to make sure gmock is installed first.

**Comment by AspirinSJL** [comment]
We are using v3.5.2 now.
