### ISSUE TITLE
Document that grpc.Channels provided by gRPC Python are thread-safe and that stubs provided by gRPC Python are thread-safe when used with thread-safe grpc.Channels

### ISSUE THREAD

**Issue by AA33** [grpc/grpc#9320]
We are using Go for our gRPC server and Python for the clients. Can a client stub created at startup be safely shared across threads/processes?

**Comment by nathanielmanistaatgoogle** [comment]
Yes.

Retitling issue to reflect that we should make this clear in gRPC Python's documentation.

**Comment by dvaldivia** [comment]
Is there anything that needs to be configured to achieve this? I'm running into a problem with `grpc 1.7.0` for python where concurrent access to a grpc stub causes all processes to hang

**Comment by nathanielmanistaatgoogle** [comment]
@dvaldivia: no, that's weird and strange and shouldn't be happening. Are you able to share with us a demonstration (code to run and description of environment in which to run it) of that problem?

**Comment by dvaldivia** [comment]
@nathanielmanistaatgoogle yes, I created a sample project with https://github.com/dvaldivia/grpc-celery-fork-bug also I raised issue #13464
