### ISSUE TITLE
test failure on 'GRPCClientTests testMetadata]'

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9349]
seen in PR: https://github.com/grpc/grpc/pull/8304 against `v1.0.x`

log in: https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/1859/testReport/junit/(root)/objc_macos_dbg/objc_tests/

error message:
```
Test Case '-[GRPCClientTests testMetadata]' failed (4.256 seconds).
```

**Comment by muxi** [comment]
Stale
