### ISSUE TITLE
memory_profile_test flaky on Linux

### ISSUE THREAD

**Issue by rjshade** [grpc/grpc#9363]
$ git clone https://github.com/grpc/grpc.git
$ cd grpc 
$ git submodule update --init
$ ./tools/run_tests/run_tests.py --language c --config dbg --regex "memory_profile_test"  --runs_per_test 100

Approximately 10% of test runs fail (with TCP connection refused, see logs below).

D0117 11:13:55.779366510    8434 ev_posix.c:105]             Using polling engine: poll-cv
D0117 11:13:55.781495143    8514 ev_posix.c:105]             Using polling engine: poll-cv
D0117 11:13:55.781607952    8514 test_config.c:290]          test slowdown: machine=1.000000 build=1.000000 poll=5.000000 total=5.000000
D0117 11:13:55.781889968    8512 test_config.c:290]          test slowdown: machine=1.000000 build=1.000000 poll=5.000000 total=5.000000
D0117 11:13:55.782029793    8512 ev_posix.c:105]             Using polling engine: poll-cv
I0117 11:13:55.782084062    8512 server.c:187]               creating server on: [::]:1115
I0117 11:13:55.782294744    8514 subchannel.c:689]           Connect failed: {"created":"@1484669635.782236283","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":237,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:1115"}
I0117 11:13:55.782317751    8514 subchannel.c:486]           Retry in 19.999731172 seconds

*******************************
Caught signal 11
bins/dbg/memory_profile_client[0x5715b4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7f40ddb6b330]
bins/dbg/memory_profile_client[0x405927]
bins/dbg/memory_profile_client[0x403a13]
bins/dbg/memory_profile_client[0x403ea0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f40dd7b7f45]
bins/dbg/memory_profile_client[0x403099]
D0117 11:13:55.889740291    8434 ev_posix.c:105]             Using polling engine: poll-cv
waiting for client
FAILED: bins/dbg/memory_profile_test GRPC_POLL_STRATEGY=poll-cv [ret=139, pid=8434]
FLAKE: bins/dbg/memory_profile_test GRPC_POLL_STRATEGY=epoll [12/100 runs flaked]
FLAKE: bins/dbg/memory_profile_test GRPC_POLL_STRATEGY=poll [7/100 runs flaked]
FLAKE: bins/dbg/memory_profile_test GRPC_POLL_STRATEGY=poll-cv [8/100 runs flaked]
FAILED: Some tests failed

**Comment by rjshade** [comment]
Adding a sleep(1) between starting the server subprocess, and starting the client subprocess seems to fix it, but there may be a better fix than simply waiting for a second.

With the following patch, 100% of test runs pass:
$ ./tools/run_tests/run_tests.py --language c --config dbg --regex "memory_profile_test"  --runs_per_test 100
PASSED: make [time=1.4sec; retries=0:0]detected port server running version 9
my port server is version 9
SUCCESS: All tests passed


diff --git a/test/core/memory_usage/memory_usage_test.c b/test/core/memory_usage/memory_usage_test.c
index 7e7a9d050..2486d2010 100644
--- a/test/core/memory_usage/memory_usage_test.c
+++ b/test/core/memory_usage/memory_usage_test.c
@@ -33,6 +33,7 @@
 
 #include <stdio.h>
 #include <string.h>
+#include <unistd.h>
 
 #include <grpc/support/alloc.h>
 #include <grpc/support/host_port.h>
@@ -66,6 +67,9 @@ int main(int argc, char **argv) {
   gpr_free(args[0]);
   gpr_free(args[2]);
 
+  /* Give the server time to start. */
+  sleep(1);
+
   /* start the client */
   gpr_asprintf(&args[0], "%s/memory_profile_client%s", root,
                gpr_subprocess_binary_extension());

**Comment by ctiller** [comment]
Suspect the write fix is to add GRPC_INITIAL_METADATA_WAIT_FOR_READY_EXPLICITLY_SET to the initial metadata op flags for requests sent from the client (to force waiting for the server to start).
