### ISSUE TITLE
Add options to c++ plugin to generate dllexport macros

### ISSUE THREAD

**Issue by sarum9in** [grpc/grpc#937]
Similar to original protoc it would be very useful to specify export macro.
$ protoc --cpp_out=dllexport_decl=MY_EXPORT_MACRO:output/direcotry

Command below generates MYEXPORT for protobuf code, not for gRPC code.
$ /usr/bin/protoc --cpp_out=dllexport_decl=MYEXPORT:output --plugin=protoc-gen-grpc_cpp=/usr/bin/grpc_cpp_plugin --grpc_cpp_out=dllexport_decl=MYEXPORT:output -- *.proto

**Comment by mingyue-aai** [comment]
+1

**Comment by jvmlet** [comment]
Hello
Is this feature scheduled to be released ?  Are there workarounds available meanwhile ?

**Comment by dsazonoff** [comment]
Hello, any progress on this?

**Comment by santoch** [comment]
Hello, any progress on this?

**Comment by fraeu** [comment]
Maybe this issue can be linked to this https://github.com/grpc/grpc/issues/15653
and to its PR https://github.com/grpc/grpc/pull/16848

**Comment by santoch** [comment]
Any progress on this?
It is a huge blocker for windows dll development

**Comment by pm-energid** [comment]
It seems that the grpc developers do not wish to support building grpc or plugins as DLLs on windows at all. See https://github.com/grpc/grpc/issues/15333 for details. If you really want your customers to be able to create pluggable user-defined components as shared libraries, either everyone to use non-windows platforms or switch to another RPC framework. We have the same requirement and we haven't been able to figure out a good solution even after banging our heads on it for days.
