### ISSUE TITLE
python_macos_opt.py34.test.unit._cython._channel_test.ChannelTest fails

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9385]
python_macos_opt.py34.test.unit._cython._channel_test.ChannelTest (from grpc.python_macos_opt)

Failing for the past 1 build (Since Failed#1932 )
Took 24 sec.
Error Message

Failure
Standard Output

++ dirname /jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt/tools/run_tests/helper_scripts/run_python.sh
+ cd /jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt/tools/run_tests/helper_scripts/../../..
++ realpath -s py34/bin/python
+ PYTHON=/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt/py34/bin/python
++ pwd
+ ROOT=/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt
+ /jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt/py34/bin/python /jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       unit._cython._channel_test.ChannelTest.test_multiple_channels_lonely_connectivity
/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt/tools/run_tests/helper_scripts/run_python.sh: line 40: 20895 Abort trap: 6           $PYTHON $ROOT/src/python/grpcio_tests/setup.py test_lite

https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/1932/testReport/junit/(root)/python_macos_opt/py34_test_unit__cython__channel_test_ChannelTest/

**Comment by markdroth** [comment]
I'm seeing the same problem in a python 2.7 test:

https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2438/testReport/junit/(root)/python_macos_dbg/py27_test_unit__cython__channel_test_ChannelTest/

**Comment by dgquintas** [comment]
I've just seen this again on #9739. Do we have any clues?

**Comment by mehrdada** [comment]
Looks like this have not been seen in a long time and through a bunch of releases, and the log data is inaccessible due to migration to Kokoro, so no point in keeping this issue around. We can file a new one should we see it again.
