### ISSUE TITLE
tests.cloud_to_cloud:go:python_server:timeout_on_sleeping_server fails for insecure channel

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9387]
https://grpc-testing.appspot.com/job/gRPC_interop_insecure/2/testReport/junit/(root)/tests/cloud_to_cloud_go_python_server_timeout_on_sleeping_server/

Error Message

Failure
Standard Output

2017/01/18 18:56:12 &{0xc8200a0a00}.Recv() = _, rpc error: code = 1 desc = stream terminated by RST_STREAM with error code: 8, want error code 4
exit status 1

For an insecure channel, the server shouldn't return UNAUTHENTICATED.

**Comment by adelez** [comment]
As more runs were executed, it turns out this failure randomly happen to other servers Csharp server and Ruby server. But the interesting part is that in all failures, the client is always Go. For all results, go to https://grpc-testing.appspot.com/job/gRPC_interop_insecure/.

**Comment by menghanl** [comment]
The logs are gone in this issue, and looking at the latest cloud-to-cloud tests, this is not happening. Closing this issue now, will investigate more if it happens again.
