### ISSUE TITLE
c_macos_dbg.bins/dbg/h2_compress_nosec_test resource_quota_server is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9398]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/1985/#showFailuresLink

```
D0119 04:14:36.256847000 140735272424192 test_config.c:290] test slowdown: machine=1.000000 build=1.000000 poll=1.000000 total=1.000000
D0119 04:14:36.257715000 140735272424192 ev_posix.c:105] Using polling engine: poll
I0119 04:14:36.258013000 140735272424192 resource_quota_server.c:53] resource_quota_server/chttp2/fullstack_compression
I0119 04:15:57.623142000 140735272424192 subchannel.c:694] Connect failed: {"created":"@1484828157.622501000","description":"Failed to connect to remote host: FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":453,"os_error":"Timeout occurred","target_address":"ipv6:[::1]:1245"}
E0119 04:15:57.623328000 140735272424192 resource_quota_server.c:255] Unexpected status code: 4
```

**Comment by jtattermusch** [comment]
Actually, seeing this failing (almost) always now.

**Comment by dgquintas** [comment]
Seen again in #9453

**Comment by dgquintas** [comment]
I haven't been able to reproduce this after a long time of running the offending test manually on the mac jenkins workers. Closing for now.

**Comment by markdroth** [comment]
Just saw this again:

https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2438/testReport/junit/(root)/c_macos_dbg/bins_dbg_h2_compress_test_resource_quota_server/

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2446/#showFailuresLink (also `sec` version failing)

pr https://github.com/grpc/grpc/pull/9580 against master
