### ISSUE TITLE
TIMEOUT: qps_json_driver.cpp_protobuf_sync_unary_qps_unconstrained_secure_500kib_resource_quota 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9399]
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/8581/consoleFull

**Comment by jtattermusch** [comment]
Might be related to https://github.com/grpc/grpc/issues/9398 (and perhaps not a flake).

**Comment by apolcyn** [comment]
seen again: https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/9895/testReport/junit/(root)/benchmarks/qps_json_driver_cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota/

pr https://github.com/grpc/grpc/pull/9986 against v1.2.x

**Comment by apolcyn** [comment]
seeing same error with streaming version of this benchmark too:
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/10236/testReport/junit/(root)/benchmarks/qps_json_driver_cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota/

pr https://github.com/grpc/grpc/pull/10019#issuecomment-289529134 against v1.2.x

**Comment by dgquintas** [comment]
Not referenced in a while, and links are dead anyway. Possibly covered by similar issues if still relevant. Closing.

**Comment by vjpai** [comment]
This test was disabled and not ever looked at for reenabling.

**Comment by ctiller** [comment]
Can we file a bug somewhere to bring it back
