### ISSUE TITLE
C++ grpc codegen: services with no methods generate code that doesn't compile under Visual Studio

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9401]
Example: NoRpcService in echo.proto has no methods and generates C++ code (from  echo.grpc.pb.cc)

```
static const char* NoRpcService_method_names[] = {
};
```

Under Visual Studio, that emits compiler error:
```
Error	C2466	cannot allocate an array of constant size 0	grpc++_test_util	C:\Users\jtattermusch\github\grpc\.vsbuild\gens\src\proto\grpc\testing\echo.grpc.pb.cc	189	
```

**Comment by jtattermusch** [comment]
@yang-g  any suggestions?

**Comment by ctiller** [comment]
Drop a NULL at the end of the array (in all cases)?

**Comment by jtattermusch** [comment]
@ctiller  so obvious, thanks for the nudge ;-)

**Comment by yang-g** [comment]
Either that or we can stop generating that array at all :)
