### ISSUE TITLE
Flame graph reports for sweeps are empty

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9402]
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_performance_sweep/133/flame_graphs_HTML_Report/

Each svg is just an empty file

**Comment by apolcyn** [comment]
one of the benchmark clients seems to run out of memory while collecting perf events on about every run.

#9391

probably could increase allowed memory for the perf workers or decrease sampling.

**Comment by apolcyn** [comment]
I think the problem is above perf actually.

It's looking like there are workers ran under perf which time out and get kill signal sent, which kills ssh on the driver but leaves the remote qps_worker and perf alive indefinitely.

**Comment by apolcyn** [comment]
It looks like reports were partially created https://grpc-testing.appspot.com/job/gRPC_performance_sweep/140/.

Looks like perf reports aren't being created for scenarios with channels >= 1000, but seems these sweep scenarios were also failing without perf. 

From the logs, the first failures are normal timeouts, perf mmap errors happen a couple of failures later - not certain appears to happen multiple perf/worker process alive at same time

**Comment by AspirinSJL** [comment]
Looks stale?
