### ISSUE TITLE
How to make grpc._server._Context.time_remaining return None when an RPC was invoked with no deadline?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#9423]
According to its spec `time_remaining` can return `None` but the core only ever passes _really really long_ deadlines; it doesn't formally specify how to identify that an RPC has no deadline.

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: is there any way at the level of the core API to distinguish server-side between no timestamp and a really long timestamp?

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: will the Core API ever distinguish between "no deadline" and "a really long deadline"? I'm not sure that it should bother, but feel free to say that it will?

**Comment by kpayson64** [comment]
@nathanielmanistaatgoogle 
There are no plans to add such a feature.  Internally, no deadline is just handled as INT64_MAX, so this would require considerable plumbing.

I'm in favor of closing this issue unless there is significant user demand for this functionality.

**Comment by nathanielmanistaatgoogle** [comment]
I agree.
