### ISSUE TITLE
Add Python test coverage.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#943]
This is twofold:

1) The C bindings need to be able to compile properly with the "gcov" configuration.
2) The Python code needs to have coverage tests enabled: https://coveralls.zendesk.com/hc/en-us/articles/201342869-Python

**Comment by murgatroid99** [comment]
This depends on issue #970

**Comment by soltanmm** [comment]
`cpp-coveralls` has a conflicting binary name with `coveralls-python` (they both claim `coveralls` as their own binary). How should we go about resolving this in the `.travis.yml` file?

**Comment by soltanmm** [comment]
#4281 handled this.
