### ISSUE TITLE
I met ' undefined: metadata.Join 'while cross compiling 

### ISSUE THREAD

**Issue by Wang-Kai** [grpc/grpc#9433]
Common` go build `
OK 

`GOOS=linux GOARCH=amd64 go build`

```
# google.golang.org/grpc/transport
../../google.golang.org/grpc/transport/http2_server.go:514: undefined: metadata.Join
../../google.golang.org/grpc/transport/transport.go:300: undefined: metadata.Join
../../google.golang.org/grpc/transport/transport.go:312: undefined: metadata.Join
```

How can i solve this bug .

**Comment by mehrdada** [comment]
We are not seeing a build issue in gRPC Go at the moment. If you are still facing this issue, please file an issue on grpc/grpc-go issue tracker where it can be best addressed, with instructions on how to reproduce. Thanks!
