### ISSUE TITLE
[Ruby] raise more info when error happens

### ISSUE THREAD

**Issue by yancl** [grpc/grpc#9434]
Hi, Recently we saw some exceptions in our log when using grpc ruby, but the reason why it is failed
is ignored, just `call#run_batch failed somehow`, will you please expose the event string of `ev`?

Thanks.

```
//grpc/src/ruby/ext/grpc/rb_call.c
 820   ev = rb_completion_queue_pluck(call->queue, tag,
 821                                  gpr_inf_future(GPR_CLOCK_REALTIME), NULL);
 822   if (!ev.success) {
 823     rb_raise(grpc_rb_eCallError, "call#run_batch failed somehow");
 824   }
```

**Comment by murgatroid99** [comment]
That `ev` variable has type `grpc_event`, which is defined in [grpc_types.h](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h). It only contains the completion type, the success/failure boolean, and the tag. There is no "event string". In this case, success is `false`, the completion type must be `GRPC_OP_COMPLETE`, and the tag is the same as the `tag` argument to the pluck call. At that point, we have no additional information to provide more precise error information.

**Comment by yancl** [comment]
Yes, I got it, thank you @murgatroid99. but will you give some advise on how to diagnose it according to the exception? thank you:)

**Comment by bobbytables** [comment]
We see this a decent amount in our error catching service and really have no idea what causes it. Would love to have some more introspection into the error.

**Comment by apolcyn** [comment]
AFAIK this indicates a sort of internal error. It might be interesting to take a look at the logs from the c library with environment variables like `export GRPC_VERBOSITY=DEBUG GRPCC_TRACE=all,-queue_pluck,-queue_timeout`. Also I'd wonder under what circumstances these errors are happening.

**Comment by apolcyn** [comment]
No action planned to change the error message, unable to do this per reasons listed by @murgatroid99.

As noted, `CallError` is a sort of internal/bad-state error, feel free to open a new issue for that error.
