### ISSUE TITLE
OpenSSL too old and outdated

### ISSUE THREAD

**Issue by mastergberry** [grpc/grpc#9436]
Hey. Been trying to get grpc to build for Windows and using some scripts and such found here: https://github.com/jozefizso/grpc-windows was able to do so successfully. Problem is that the NuGet packages that grpc and this system are using an old outdated openssl library which is not working with some other parts of the system we are trying to use it with.

This is all C++ based by the way.

Is there anyway to get a newer updated openssl dependency? Is there a way to link our own static libraries against the project instead?

**Comment by mastergberry** [comment]
Ok i see there were some updates recently to https://github.com/grpc/grpc/blob/master/INSTALL.md and that there are some new steps for building on windows.

I am having issues though with the following log:

```
C:\Users\adam\Development\badlionclient\thirdparty\grpc\.build>cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/amd64/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/adam/Development/badlionclient/thirdparty/grpc/.build/CMakeFiles/CMakeTmp



  Run Build Command:"C:/Users/adam/Development/tools/ninja.exe" "cmTC_87477"

  [1/2] Building C object CMakeFiles\cmTC_87477.dir\testCCompiler.c.obj

  [2/2] Linking C executable cmTC_87477.exe

  FAILED: cmTC_87477.exe

  cmd.exe /C "cd .  && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe
  --intdir=CMakeFiles\cmTC_87477.dir --manifests --
  C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo
  CMakeFiles\cmTC_87477.dir\testCCompiler.c.obj /out:cmTC_87477.exe
  /implib:cmTC_87477.lib /pdb:cmTC_87477.pdb /version:0.0 /machine:x64 /debug
  /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib
  winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
  advapi32.lib && cd ."

  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'

  LINK Pass 1 failed.  with 1104

  ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:49 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/adam/Development/badlionclient/thirdparty/grpc/.build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/adam/Development/badlionclient/thirdparty/grpc/.build/CMakeFiles/CMakeError.log".
```

**Comment by mastergberry** [comment]
Tagging @jtattermusch since he wrote the latest documentation on the windows building.

**Comment by mastergberry** [comment]
Seemed to have gotten the files to build using the mingw approach...got my dll's and now i can't get visual studios to read them properly :(

Total windows noob in terms of development. Think someone can lend me a hand and explain to me what things i need to include in the includes/linkers to get this new grpc to work? Most importantly will this new grpc have a newer version of openssl versus the old nuget packages?

**Comment by jtattermusch** [comment]
The error
```
C:\Users\adam\Development\badlionclient\thirdparty\grpc\.build>cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/amd64/cl.exe" is not able to compile a simple test program.
```
looks more like an issue with your setup rather than a problem with our buildfiles (do you really have VS2015 installed on your machine?)

To respond to the general question:
Our windows build is definitely suboptimal right now and there is several issues with it (even though I think you particular issue is a red herring) and we are working towards fixing that.
Currently it looks that the best way to build C++ on Windows is the cmake based approach (I've already made several improvements during the last week so be sure to use the lates version in your experiments).

**Comment by mastergberry** [comment]
I definitely have VS2015 installed on my machine. I'm not sure if all of the PATH variables and such are setup properly though. I feel that is an environmental variable issue more than anything and I just don't know which ones I need to get set/fixed.

I also have both the Windows SDK for 8.1 and 10 installed on my machine as well. They are both in Program Files.

The overall issue we are having is the openssl and is the reason we are having to try and do all of these custom builds from scratch instead of just using the already working solutions with nuget. We are using openssl 1.1.0c on our server now with Node.js and have no issues getting java or python to work with gRPC and SSL. C++ is failing though specifically with errors such as the following:

```
E0122 19:18:55.649645915   29577 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0122 19:18:55.649689944   29577 handshake.c:128]            Security handshake failed: {"created":"@1485112735.649673737","description":"Handshake failed","file":"../src/core/lib/security/transport/handshake.c","file_line":264,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
E0122 19:18:55.649717943   29577 server_secure_chttp2.c:119] Secure transport failed with error 1
```

Please note the above error is from node.js.

The below error is from the C++ side of things:

````
{"created":"@1485112363.100000000","description":"End of TCP stream","file":"C:\Users\adam\Development\badlionclient\thirdparty\grpc-windows\grpc\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":180,"grpc_status":14}
```

When doing my research online it looked like the issue was indeed out of date OpenSSL stuff trying to be used by the C++ side of things which was not being accepted by the Node.js side of things.

Maybe you can tell me this assumption/conclusion I reached through the online resources is wrong. We really need to get this C++ gRPC windows SSL stuff working though, some of our build heavily depends on it.

**Comment by jtattermusch** [comment]
have you run 
`call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x64`  as suggested in the howto?  does  cl and msbuild work from the same command shell after running that dommand?

**Comment by jtattermusch** [comment]
@mastergberry  I think our long-term plan is to move windows build to boringssl to make windows build consistent with build on linux (and other operating systems). Would such solution work well for you (it should)?
Btw, the current cmake build in upstream/master already utilizes boringssl

**Comment by mastergberry** [comment]
Yes I had run the batch script above already. It gave me no output though.

At the moment I am modifying my Visual Studios installation to include the Windows SDK since I guess when I originally installed it the support was not built in. I installed the SDK myself from the Microsoft website which I guess was not completely integrated properly. I needed the SDK for something else. Hoping that after I install it with Visual Studios my environment and PATH variables will be fixed.

And yes I believe using boringssl will work for us properly as it is more up to date and how the other modules we are using were built.

I will update again as soon as Visual Studios finishes it's upgrade.

**Comment by mastergberry** [comment]
Ok now the command above for `ninja` worked properly. I am trying to run the build now completely.

Should state in the documentation that the Windows SDK needs to be installed via Visual Studios's installer to avoid any conflicting environment problems.

**Comment by mastergberry** [comment]
Failed to build with a nasm.exe error:

```
C:\Users\adam\Development\experiments\thirdparty\grpc\.build>cmake --build .
[172/1689] Building RC object third_party\zlib\CMakeFiles\zlib.dir\win32\zlib1.res
Microsoft (R) Windows (R) Resource Compiler Version 6.3.9600.17336
Copyright (C) Microsoft Corporation.  All rights reserved.

[184/1689] Linking C shared library third_party\zlib\zlib.dll
   Creating library third_party\zlib\zlib.lib and object third_party\zlib\zlib.exp
[396/1689] Building ASM_NASM object third_party\boringssl\crypto\rand\CMakeFiles\rand.dir\rdrand-x86_64.asm.obj
FAILED: third_party/boringssl/crypto/rand/CMakeFiles/rand.dir/rdrand-x86_64.asm.obj
C:\Users\adam\Development\tools\nasm.exe  -I..\third_party\boringssl\crypto\..\include -I..\third_party\boringssl\crypto\rand\..\..\include /wd4464 /wd4623 /wd4668 /wd4701 /wd4702 /wd4777 /wd5027 /wd4065 /wd4506 /wd4267 -f win64 -o third_party\boringssl\crypto\rand\CMakeFiles\rand.dir\rdrand-x86_64.asm.obj C:\Users\adam\Development\experiments\thirdparty\grpc\.build\third_party\boringssl\crypto\rand\rdrand-x86_64.asm
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
type `nasm -h' for help
[409/1689] Building CXX object third_party\protobuf\CMakeF...dir\__\src\google\protobuf\util\message_differencer.cc.obj
ninja: build stopped: subcommand failed.
```

**Comment by mastergberry** [comment]
Note: I installed nasm.exe myself using a direct download from http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win64/

**Comment by mastergberry** [comment]
The first time I had downloaded the zip, this time i did it with the installer and fixed my system PATH variables just to make sure there were no issues. Ran the build again and got some different errors this time i guess. The part of the build number wise changed at least.

```
C:\Users\adam\Development\experiments\thirdparty\grpc\.build>cmake --build .
[102/1689] Building RC object third_party\zlib\CMakeFiles\zlib.dir\win32\zlib1.res
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

[137/1689] Linking C shared library third_party\zlib\zlib.dll
   Creating library third_party\zlib\zlib.lib and object third_party\zlib\zlib.exp
[392/1689] Building ASM_NASM object third_party\boringssl\crypto\md5\CMakeFiles\md5.dir\md5-x86_64.asm.obj
FAILED: third_party/boringssl/crypto/md5/CMakeFiles/md5.dir/md5-x86_64.asm.obj
C:\Users\adam\AppData\Local\NASM\nasm.exe  -I..\third_party\boringssl\crypto\..\include -I..\third_party\boringssl\crypto\md5\..\..\include /wd4464 /wd4623 /wd4668 /wd4701 /wd4702 /wd4777 /wd5027 /wd4065 /wd4506 /wd4267 -f win64 -o third_party\boringssl\crypto\md5\CMakeFiles\md5.dir\md5-x86_64.asm.obj C:\Users\adam\Development\experiments\thirdparty\grpc\.build\third_party\boringssl\crypto\md5\md5-x86_64.asm
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
nasm: error: more than one input file specified
type `nasm -h' for help
[405/1689] Generating err_data.c
ninja: build stopped: subcommand failed.
```

**Comment by mastergberry** [comment]
Any updates as to why the nasm command is failing for my system?

**Comment by jtattermusch** [comment]
Have you tried yasm?  Both https://github.com/grpc/grpc/blob/master/INSTALL.md and boringssl's documentation https://github.com/google/boringssl/blob/master/BUILDING.md state that you should use yasm.

**Comment by mastergberry** [comment]
I don't even know how i got nasm onto my system but i switched to yasm now.

Getting a different error, i checked the paths and they both just lead to an openssl directory and don't seem to include actual file contents unless it looks recursively

```
FAILED: third_party/boringssl/crypto/md5/CMakeFiles/md5.dir/md5-x86_64.asm.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\vsyasm.exe  -I..\third_party\boringssl\crypto\..\include -I..\third_party\boringssl\crypto\md5\..\..\include -g cv8   /wd4464 /wd4623 /wd4668 /wd4701 /wd4702 /wd4777 /wd5027 /wd4065 /wd4506 /wd4267 -f win64 -o third_party\boringssl\crypto\md5\CMakeFiles\md5.dir\md5-x86_64.asm.obj C:\Users\adam\Development\experiemnts\thirdparty\grpc\.build\third_party\boringssl\crypto\md5\md5-x86_64.asm
vsyasm: FATAL: Could not open input file
```

**Comment by jtattermusch** [comment]
IMHO the executable name should be yasm, not vsyasm?

**Comment by mastergberry** [comment]
@jtattermusch so I tried using the visual studios installation which is why it was vsyasm but that did not seem to work. The default yasm seemed to have worked and I finally got everything to build. Thanks :)

Now my next issue is I am getting back a `Error 2 lame client channel` from the system. Do you know why it's returning the `lame client channel` when using default SSL? Once again no issues with Java or Python.

**Comment by mastergberry** [comment]
Ok i got the logger stuff to work...it seems like it's not generating something in one of the Windows files properly.

```
GRPC LOG: load_file: {"created":"@1485450279.476000000","description":"Failed to load file","file":"C:\Users\adam\Development\experiments\thirdparty\grpc\src\core\lib\iomgr\load_file.c","file_line":82,"filename":"/usr/share/grpc/roots.pem","referenced_errors":[{"created":"@1485450279.476000000","description":"OS Error","errno":2,"file":"C:\Users\adam\Development\experiments\thirdparty\grpc\src\core\lib\iomgr\load_file.c","file_line":58,"os_error":"No such file or directory","syscall":"fopen"}]}
```

Notice how it's trying to use a linux path.

**Comment by jtattermusch** [comment]
You need to set 
GRPC_DEFAULT_SSL_ROOTS_FILE_PATH to point to the location of roots.pem
(see https://github.com/grpc/grpc/blob/master/doc/environment_variables.md)

There's no reasonable standard path for roots.pem on Windows, so you need to set the env variable yourself.

**Comment by mastergberry** [comment]
Gotcha. Well that is resolved now too and this is all setup and working. I would adjust the documentation to state that the Windows SDK needs to be installed through Visual Studios (not downloaded separately) and that this stuff should be ran through a developer console on MSVS as well.

Thanks for all the help.

**Comment by jtattermusch** [comment]
gRPC C++ can now be built on Windows using CMake  and uses the same boringssl version as on Linux.
