### ISSUE TITLE
yapf_code.sh failing

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9437]
Failed in test https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2123/consoleFull
and Linux master

**Comment by dgquintas** [comment]
@nathanielmanistaatgoogle is there a way to quickly fix this? Or disable this check: it's making jenkins fail at master.

**Comment by nathanielmanistaatgoogle** [comment]
Discussed with @dgquintas in meatspace but here in writing for everyone else: I think the timeline relevant to this was

* [pull request 8842](https://github.com/grpc/grpc/pull/8842) branched off of `master`
* [`yapf`](https://github.com/grpc/grpc/pull/9276) introduced on `master`
* [pull request 8842](https://github.com/grpc/grpc/pull/8842) integrated into `master`

. If so, then did `yapf` fail when [8842](https://github.com/grpc/grpc/pull/8842) was integrated into `master`? And will `yapf` pass following [the disintegration of 8842](https://github.com/grpc/grpc/pull/9428)?

Looking...

**Comment by dgquintas** [comment]
@nathanielmanistaatgoogle it seems things have gone back to normal after the rollback of #8842 was picked up. Closing this for now.

**Comment by muxi** [comment]
It seems that this failure is coming again. See master failed at 
https://grpc-testing.appspot.com/job/gRPC_master_linux/1285/consoleFull

**Comment by muxi** [comment]
Seems like it is happening again since yesterday night.
https://grpc-testing.appspot.com/job/gRPC_master_linux/

**Comment by dgquintas** [comment]
Yes, I noticed this morning. https://github.com/grpc/grpc/pull/9598 addresses it.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; this was fixed in [pull request 9598](https://github.com/grpc/grpc/pull/9598).
