### ISSUE TITLE
Add node.js test coverage.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#944]
This is twofold:

1) The C bindings need to be able to compile properly with the "gcov" configuration.
2) The node.js code needs to have coverage tests enabled: https://coveralls.zendesk.com/hc/en-us/articles/201769715-Javascript-Node

**Comment by murgatroid99** [comment]
This depends on issue #970

**Comment by ctiller** [comment]
Good to have before we start moving towards GA, just to know where our testing hole are. Shouldn't necessarily block beta, but that's the only tool we currently have.

**Comment by murgatroid99** [comment]
I'm going to move this to GA. It has external dependencies and is unlikely to be doable before Beta is due.

**Comment by ctiller** [comment]
This is totally GA work (for all wrapped languages).
