### ISSUE TITLE
boringssl: Compiling with OPENSSL_NO_ASM harms throughput of secure connections significantly

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9440]
Filing for the record.

It seems that currently, we are compiling boringssl with -DOPENSSL_NO_ASM, so for some crypto functions, more efficient assembler implementations won't be used. More investigation is needed to evaluate if this actually represents a performance penalty (is asm useful for the ciphers we are using?)

**Comment by ctiller** [comment]
It's probably providing a hit, but I'd hazard not as much of a hit as all the other things we do. We'd need a large message benchmark comparing secure & insecure and showing a large difference before spending significant time here.

**Comment by jtattermusch** [comment]
I have some indication that this might actually make a big difference:

The scenario is the client making one RPC at a time ("ping-pong"), where request size is 1MB and response size is also 1MB.

C++:
insecure connection:  cca 300 QPS
secure connection: cca 20QPS  (encryption overhead tends to be large)

Node:
secure connection:  60 QPS (more than C++!!  and node doesn't use BoringSSL, but openssl that's built into node.js runtime).

**Comment by jtattermusch** [comment]
CC @murgatroid99

**Comment by jtattermusch** [comment]
**This is now confirmed and makes a HUGE difference** Tested with 1MB secure ping pong:
73 QPS  when built using cmake (where OPENSSL_NO_ASM was manually disabled)
15 QPS when build using make (where we default to OPENSSL_NO_ASM and it's not easy to change this).
15 QPS  when built using cmake (and used OPENSSL_NO_ASM)

cmake build without OPENSSL_NO_ASM
```
+ bins/opt/qps_json_driver '--scenarios_json={"scenarios": [{"name": "cpp_protobuf_async_unary_ping_pong_secure_1mb", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"async_server_threads": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "ASYNC_SERVER"}, "client_config": {"client_type": "ASYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 1048576, "req_size": 1048576}}, "client_channels": 1, "async_client_threads": 1, "outstanding_rpcs_per_channel": 1, "rpc_type": "UNARY", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 1}]}' --scenario_result_file=scenario_result.json
RUNNING SCENARIO: cpp_protobuf_async_unary_ping_pong_secure_1mb
I0407 11:10:53.270965731  185818 driver.cc:259]              Starting server on localhost:10000 (worker #0)
I0407 11:10:53.271058403  185818 ev_epoll_linux.c:94]        epoll engine will be using signal: 40
D0407 11:10:53.271066731  185818 ev_posix.c:107]             Using polling engine: epoll
D0407 11:10:53.271088444  185818 dns_resolver.c:316]         Using native dns resolver
I0407 11:10:53.644629882  185818 driver.cc:306]              Starting client on localhost:10010 (worker #1)
D0407 11:10:53.644689746  185818 driver.cc:322]              Client 0 gets 1 channels
I0407 11:10:53.648990412  185818 driver.cc:343]              Initiating
I0407 11:10:53.649578009  185818 driver.cc:364]              Warming up
I0407 11:10:58.649660442  185818 driver.cc:370]              Starting
I0407 11:10:58.653892337  185818 driver.cc:397]              Running
I0407 11:11:28.649679572  185818 driver.cc:411]              Finishing clients
I0407 11:11:28.651353582  185818 driver.cc:425]              Received final status from client 0
I0407 11:11:28.660373059  185818 driver.cc:457]              Finishing servers
I0407 11:11:28.662421518  185818 driver.cc:471]              Received final status from server 0
I0407 11:11:28.887607321  185818 report.cc:81]               QPS: 73.2
I0407 11:11:28.889742192  185818 report.cc:91]               QPS: 73.2 (6.1/server core)
I0407 11:11:28.889773230  185818 report.cc:96]               Latencies (50/90/95/99/99.9%-ile): 13705.8/16592.1/17377.8/19378.4/22156.2 us
I0407 11:11:28.889785886  185818 report.cc:106]              Server system time: 9.23%
I0407 11:11:28.889796785  185818 report.cc:108]              Server user time:   42.21%
I0407 11:11:28.889806611  185818 report.cc:110]              Client system time: 8.56%
I0407 11:11:28.889816527  185818 report.cc:112]              Client user time:   45.24%
I0407 11:11:28.889826734  185818 report.cc:117]              Server CPU usage: 11.55%
+ '[' '' '!=' '' ']'
PASSED: qps_json_driver.cpp_protobuf_async_unary_ping_pong_secure_1mb [time=35.6sec; retries=0:0]
```

make build with OPENSSL_NO_ASM
```
+ bins/opt/qps_json_driver '--scenarios_json={"scenarios": [{"name": "cpp_protobuf_async_unary_ping_pong_secure_1mb", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"async_server_threads": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "ASYNC_SERVER"}, "client_config": {"client_type": "ASYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 1048576, "req_size": 1048576}}, "client_channels": 1, "async_client_threads": 1, "outstanding_rpcs_per_channel": 1, "rpc_type": "UNARY", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 1}]}' --scenario_result_file=scenario_result.json
RUNNING SCENARIO: cpp_protobuf_async_unary_ping_pong_secure_1mb
I0407 11:09:45.333565977  184641 driver.cc:259]              Starting server on localhost:10000 (worker #0)
I0407 11:09:45.333655376  184641 ev_epoll_linux.c:94]        epoll engine will be using signal: 40
D0407 11:09:45.333663427  184641 ev_posix.c:107]             Using polling engine: epoll
D0407 11:09:45.333685901  184641 dns_resolver.c:316]         Using native dns resolver
I0407 11:09:45.681645639  184641 driver.cc:306]              Starting client on localhost:10010 (worker #1)
D0407 11:09:45.681759829  184641 driver.cc:322]              Client 0 gets 1 channels
I0407 11:09:45.689479083  184641 driver.cc:343]              Initiating
I0407 11:09:45.690082600  184641 driver.cc:364]              Warming up
I0407 11:09:50.690174147  184641 driver.cc:370]              Starting
I0407 11:09:50.694057668  184641 driver.cc:397]              Running
I0407 11:10:20.690356634  184641 driver.cc:411]              Finishing clients
I0407 11:10:20.692604021  184641 driver.cc:425]              Received final status from client 0
I0407 11:10:20.736844565  184641 driver.cc:457]              Finishing servers
I0407 11:10:20.737670349  184641 driver.cc:471]              Received final status from server 0
I0407 11:10:20.969215202  184641 report.cc:81]               QPS: 15.6
I0407 11:10:20.971394555  184641 report.cc:91]               QPS: 15.6 (1.3/server core)
I0407 11:10:20.971413872  184641 report.cc:96]               Latencies (50/90/95/99/99.9%-ile): 62809.1/72715.2/75027.9/86042.9/95401.7 us
I0407 11:10:20.971420917  184641 report.cc:106]              Server system time: 1.67%
I0407 11:10:20.971427069  184641 report.cc:108]              Server user time:   48.33%
I0407 11:10:20.971432667  184641 report.cc:110]              Client system time: 1.56%
I0407 11:10:20.971438379  184641 report.cc:112]              Client user time:   47.61%
I0407 11:10:20.971444468  184641 report.cc:117]              Server CPU usage: 19.88%
+ '[' '' '!=' '' ']'
PASSED: qps_json_driver.cpp_protobuf_async_unary_ping_pong_secure_1mb [time=35.7sec; retries=0:0]
```

cmake build with OPENSSL_NO_ASM enabled (the default).
```
+ bins/opt/qps_json_driver '--scenarios_json={"scenarios": [{"name": "cpp_protobuf_async_unary_ping_pong_secure_1mb", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"async_server_threads": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "ASYNC_SERVER"}, "client_config": {"client_type": "ASYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 1048576, "req_size": 1048576}}, "client_channels": 1, "async_client_threads": 1, "outstanding_rpcs_per_channel": 1, "rpc_type": "UNARY", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 1}]}' --scenario_result_file=scenario_result.json
RUNNING SCENARIO: cpp_protobuf_async_unary_ping_pong_secure_1mb
I0407 11:19:01.207599929  194429 driver.cc:259]              Starting server on localhost:10000 (worker #0)
I0407 11:19:01.207711923  194429 ev_epoll_linux.c:94]        epoll engine will be using signal: 40
D0407 11:19:01.207723044  194429 ev_posix.c:107]             Using polling engine: epoll
D0407 11:19:01.207749731  194429 dns_resolver.c:316]         Using native dns resolver
I0407 11:19:01.582985687  194429 driver.cc:306]              Starting client on localhost:10010 (worker #1)
D0407 11:19:01.583044933  194429 driver.cc:322]              Client 0 gets 1 channels
I0407 11:19:01.591580621  194429 driver.cc:343]              Initiating
I0407 11:19:01.592290625  194429 driver.cc:364]              Warming up
I0407 11:19:06.592378504  194429 driver.cc:370]              Starting
I0407 11:19:06.595768290  194429 driver.cc:397]              Running
I0407 11:19:36.592418507  194429 driver.cc:411]              Finishing clients
I0407 11:19:36.593886594  194429 driver.cc:425]              Received final status from client 0
I0407 11:19:36.654945442  194429 driver.cc:457]              Finishing servers
I0407 11:19:36.655896670  194429 driver.cc:471]              Received final status from server 0
I0407 11:19:36.890679043  194429 report.cc:81]               QPS: 15.6
I0407 11:19:36.891996396  194429 report.cc:91]               QPS: 15.6 (1.3/server core)
I0407 11:19:36.892013367  194429 report.cc:96]               Latencies (50/90/95/99/99.9%-ile): 63049.5/71694.9/72485.4/74636.2/80408.1 us
I0407 11:19:36.892046201  194429 report.cc:106]              Server system time: 1.57%
I0407 11:19:36.892053024  194429 report.cc:108]              Server user time:   49.12%
I0407 11:19:36.892058117  194429 report.cc:110]              Client system time: 1.66%
I0407 11:19:36.892063296  194429 report.cc:112]              Client user time:   48.12%
I0407 11:19:36.892068779  194429 report.cc:117]              Server CPU usage: 10.95%
+ '[' '' '!=' '' ']'
PASSED: qps_json_driver.cpp_protobuf_async_unary_ping_pong_secure_1mb [time=35.7sec; retries=0:0]
```

**Comment by jtattermusch** [comment]
Some followup questions:

Makefile:
OPENSSL_NO_ASM could be removed, but this would probably make things more complex as we'd need to replicate the way boringssl builds from asm files (IMHO we are replicating boringssl build based on list of .c files extracted)

BUILD file:
Are we relying on boringssl's BUILD file or are we replicating their build? Does boringssl's blaze build support using .asm files?

Distribution packages (node seems not to be affected as it uses node's builtin openssl)
- This is tricky for the build in some languages (like python - we don't have a good way to include the .asm files in our language specific builds)
- We might need to be more architecture specific when building artifacts for distribution packages. Having different artifacts for different architecture might bloat the monolithic packages (like C# nugets) or there'll just be more arch-specific packages. It would be good to investigate if switching the architecture to i586 would be sufficient or if some more advanced instructions are being relied upon.

CC @nicolasnoble

**Comment by nicolasnoble** [comment]
I'm not surprised at all with this finding. Assembly optimizations are there for a reason.

Originally we provided the building of OpenSSL through the Makefile in order to help with interoperability while system's OpenSSL was still lagging behind with regards to NPN/ALPN. Building OpenSSL or BoringSSL with assembly optimization is a real pain, as the number of dependencies would drastically increase, and we can't just have a "dumb" list of .c files anymore, we need to really generate the build files for BoringSSL using perl and assemble using nasm. You wouldn't be able to "just" list the list of .s files to build, a lot more needs to happen. Some of these assembly file get generated on the fly during the build, using perl scripts. More on that later.

But I'm going to stress that out: we provided the OpenSSL embedding that as a convenience for mitigating the lack of system's OpenSSL. And then we leaked that interoperability convenience into the artifacts build system since, well, it's convenient there too, for lots of reasons. MacOS doesn't have OpenSSL by default, and its SSL layer doesn't support NPN or ALPN. Microsoft's SSL layer only supports NPN/ALPN since way too recently. There's just not a good way to do that other than using OpenSSL or BoringSSL embedded with it. And embedding with assembly would be a big drag, so, convenience won there.

As for Bazel, yes, the BoringSSL BUILD file does handle building with assembly supported, but that file only works for Linux. Also note that the Bazel file exists only in a special branch of BoringSSL, that has all of the assembly file already generated and ready, but only for gcc. Try a `find . -name *.S` in both the `boringssl` and `boringssl-with-bazel`. You'll see that the boringssl-with-bazel submodule has everything tailored for a very specific version of the cpu and compiler, and wouldn't be usable in a more generic build system. And while Bazel supports Windows, BoringSSL's BUILD file doesn't. See https://github.com/google/boringssl/blob/master-with-bazel/BUILD#L69 that demonstates that assembly code is also disabled in BoringSSL for anything that's not Linux or MacOS, with very specific versions of CPUs. Also the copts are gcc only. Trying to run that BUILD file with MSVC as a compiler would fail, since these compiler flags just don't exist.


At the end of the day, the "right" way to handle this is to rely on pre-compiled versions of OpenSSL / BoringSSL. For example, for Windows, getting https://slproweb.com/products/Win32OpenSSL.html installed onto the build machines and making use of it. For Linux it'd means starting to use the system's OpenSSL. If we want to be nice, we could try still shipping embedded-SSL code, and fallbacking to it if the system's SSL isn't supporting what we need, but I'm not even sure we'd want to do through the extend of convoluted code needed to do this.

But I'm against getting the build system to handle SSL assembly. This convenience trick we provided to bootstrap gRPC got already overly abused, is overcomplicated, and needs to be winded down. We need to start more relying on external SSL libraries, be it through Bazel, or tailoring the build machines to have a static version of SSL we'd want to ship with at all times. Calling through BoringSSL's build system from within the Makefile to have assembly code isn't going to be working fine, as we already walked out of that trap long ago to move to BoringSSL and simplify and streamline our build. And the Bazel version wouldn't be generic enough for what we'd like to achieve.

**Comment by jtattermusch** [comment]
I agree that adding assembly support to our Makefile would be overly complicated (and I wasn't implying we should do so).

I am not really that worried about C/C++, because one can use system's OpenSSL if one chooses to and there is currently an easy way to build with asm optimizations - by using Cmake. So only a few relatively minor adjustments are needed here.

For distributions packages in wrapped langs, we have a problem though. I don't think it's acceptable to sacrifice 66% of the performance for secure scenarios just because we are including embedding a non-asm optimized boringssl. At the same time, I don't think relying on system's OpenSSL is an option here - it's too much of a hit for usability. 

I am not yet sure what we should do, but we could experiment with building the artifacts using Cmake (actually we do that for C# on Windows already) - that way we would prevent the need to add asm support to our Makefiles. And at least some languages' packaging systems have support for choosing binaries with the right architecture (will need to investigate what asm instructions are actually being used and on which processors they are available).

**Comment by nicolasnoble** [comment]
I'm not against the idea that there's a Jenkins-specific flag during package building time that says "don't build embedded version of BoringSSL, use that provided .a file instead". This way the binary packages we distribute are optimized, and people still have the ability to build from source, albeit at a perf cost during runtime.

**Comment by nicolasnoble** [comment]
These files you're listing don't actually exist now, do they ? At least I don't see them in my tree for boringssl...

**Comment by jtattermusch** [comment]
They are all generated, I just thought I would list them all and scanned through them to look for anything that's not supported on vanilla x86_64.   maybe AVX2?

**Comment by jtattermusch** [comment]
As an overview of the current situation, we added this doc: https://github.com/grpc/grpc/blob/master/doc/ssl-performance.md. Please report if you notice any inaccuracies.

**Comment by jtattermusch** [comment]
Closing this with a note:
- The overview when we disable/enable boringssl assembly optimizations is here: https://github.com/grpc/grpc/blob/master/doc/ssl-performance.md
- specifically, when building on linux with `make` and embedded boringssl library, the ASM optimizations are disabled, which can result in poor reformance with secure channels. Nevertheless, there are several solutions available: 1. build with cmake (where ASM optimizations work fine), 2. build with bazel (asm optimizations will be enabled), 3. build with system-installed openssl  (=don't embed boringssl when building).
