### ISSUE TITLE
Check C# code compatibility with netstandard2.0

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#9441]
While netstandard1.4 was runnable from .NET 4.6.1, netstandard1.5 targeted 4.6.2. Now netstandard2.0 is targeting the .NET 4.6.1 API surface again, which I suspect means *some* APIs from netstandard1.5 may be missing in netstandard2.0. Unfortunately, netstandard1.5 is what gRPC targets :(

It looks like there are only two parts of netstandard1.5 we need: `AssemblyInfo.Location`, and `System.Runtime.Loader.AssemblyLoadContext`. With any luck, those will either already be present in netstandard2.0 or will have alternatives. We may need to explicitly target netstandard2.0 though.

Not a lot can be done about this right now as netstandard2.0 isn't fully baked, but this is a reminder to revisit it and test it when it *is* out.

**Comment by adamhathcock** [comment]
Hopefully easy to fix the path errors :)

```
Failed   Proto.Remote.Tests.RemoteTests.CanSpawnRemoteActor
Error Message:
 System.AggregateException : One or more errors occurred. (Error loading native library. Not found in any of the possible locations: /Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib) (The following constructorparameters did not have matching fixture data: RemoteManager remoteManager)
---- System.IO.FileNotFoundException : Error loading native library. Not found in any of the possible locations: /Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
---- The following constructor parameters did not have matching fixture data: RemoteManager remoteManager
Stack Trace:

----- Inner Stack Trace #1 (System.IO.FileNotFoundException) -----
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Proto.Remote.Remote.Start(String hostname, Int32 port, RemoteConfig config) in /Users/adam/git/personal/protoactor-dotnet/src/Proto.Remote/Remote.cs:line 58
   at Proto.Remote.Remote.Start(String hostname, Int32 port) in /Users/adam/git/personal/protoactor-dotnet/src/Proto.Remote/Remote.cs:line 50
   at Proto.Remote.Tests.RemoteManager..ctor() in /Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/RemoteManager.cs:line 20
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by jskeet** [comment]
@adamhathcock: The xunit issue is tracked separately in the xunit repo. I can't link to it right now but it should be easy to find :)

**Comment by adamhathcock** [comment]
Is this it? https://github.com/grpc/grpc/issues/12154

So this is xunit specific not netstandard specific?

**Comment by adamhathcock** [comment]
Yup: https://github.com/xunit/xunit/issues/1363

Hopefully new public xunit beta soon

**Comment by HideDev** [comment]
Hi, any news?

**Comment by jskeet** [comment]
@HideDev: The news would really be on xunit/xunit#1363

**Comment by jtattermusch** [comment]
I've came up with experimental support of netstandard2.0 here: https://github.com/grpc/grpc/pull/13492.
Can someone test it fixes their netstandard2.0 usage scenario?

**Comment by jtattermusch** [comment]
I just tested and I was able to use gRPC from netcoreapp2.0 without any problems. Therefore, I'm closing this issue.

**Comment by thangchung** [comment]
.NET Core 2.1 is stable at the moment. Do you guys have any plan to work on it?

**Comment by jskeet** [comment]
@thangchung: There should be no change required - have you seen problems using gRPC from .NET Core 2.1?
