### ISSUE TITLE
Create Python 3.6 Wheels

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9445]
Python 3.6 Release is now official, we should start packaging wheels that support it.

**Comment by jonparrott** [comment]
Bump - both google-auth and google-cloud-python would love to have this wheel so we can run 3.6 on Travis.

**Comment by lukesneeringer** [comment]
Bump - is this something we can reasonably help with? Basically no projects depending on GRPC can test in Travis (for Python 3.6) right now, and we really want to officially declare Python 3.6 support.

**Comment by kpayson64** [comment]
@lukesneeringer I was waiting on PyPI to allow specifying a package as Python 3.6 (via the web UI).  It wasn't an option at the time of the 1.1 release, but it looks like its supported now.

Its probably something we need to do, it requires installing Python3.6 on hosts and modifying some build systems that are somewhat inaccessible.

**Comment by lukesneeringer** [comment]
@kpayson64 Understood. Let me know if I can help in any way, as I have several projects waiting on this. Thank you so much!

**Comment by kpayson64** [comment]
We will have Python3.6 wheels in our next release.

**Comment by jonparrott** [comment]
@kpayson64 when's the next release? Can you leave this open until then as a signal that the wheels are available?

**Comment by hsaliak** [comment]
Hi @jonparrott  we are shooting for a 20th March release date.

**Comment by jonparrott** [comment]
@hsaliak that's a long way off, we'd really like to test against 3.6 sooner rather than later. Plus, it would be great if ya'll could backfill 3.6 wheels for every version post 1.0.

**Comment by hsaliak** [comment]
@kpayson64 @nathanielmanistaatgoogle will it be possible for us to release a 1.0.x based wheel?
We can release this sooner than the Mar 20th date..

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak we've talked about it with exactly this customer scenario in mind and we're pretty sure it's something we want to do in the next few days.

**Comment by kpayson64** [comment]
I'm working on cutting a release now, but I'm pretty strongly against back-filling Python3.6 wheels against older versions.

**Comment by jonparrott** [comment]
> I'm working on cutting a release now, but I'm pretty strongly against back-filling Python3.6 wheels against older versions.

Curious as to why you're against this? Many libraries did this once manylinux wheels became available.

**Comment by kpayson64** [comment]
@jonparrott 
It plays fast and loose with our versioning.  We will end up publishing wheels for the same version that point to different points in the repository.

I think its reasonable that anyone hoping to use gRPC with Python3.6 needs to get the latest version.

**Comment by jonparrott** [comment]
> It plays fast and loose with our versioning. We will end up publishing wheels for the same version that point to different points in the repository.

Why would that be the case? Would you not backfill the wheels for old versions from their respective git tags?

> I think its reasonable that anyone hoping to use gRPC with Python3.6 needs to get the latest version.

I disagree, especially when the latest version is a month out and downstream clients haven't upgraded to it yet.

**Comment by kpayson64** [comment]
To make sure we are on the same page, you are suggesting that we create Python3.6 wheels for:

grpcio-1.0.0
grpcio-1.0.1
grpcio-1.0.2
grpcio-1.0.3
grpcio-1.0.4
grpcio-1.1.0


Is there a case where a user wants to start using Python3.6, but refuses to upgrade their gRPC version?

**Comment by jonparrott** [comment]
> To make sure we are on the same page, you are suggesting that we create Python3.6 wheels for:

Yes.

> Is there a case where a user wants to start using Python3.6, but refuses to upgrade their gRPC version?

It's not really about users, it's about gRPC's downstream clients (notably google-auth and google-cloud-python). We want to declare support for 3.6 and we declare minimum gRPC version (1.0.2 right now, I believe). We'd prefer not to bump that minimum version unless we need to.

So, the question is does does grpc >= 1.0.0 support 3.6? If so, there should be 3.6 wheels for all those versions. If not, what's the minimum version that does support 3.6 so we can update our dependency ranges? If the answer is `1.2.0` on March 20, that's fine.

**Comment by hsaliak** [comment]
@kpayson64 to clarify my earlier comment, it was a typo. I only meant 1.1.x. 
I think it is OK to have _a_ version available for 3.6 out quickly and have the next version onward support it.

**Comment by lukesneeringer** [comment]
For my part, it would be okay for me to require the current version of `grpc`, although obviously I would slightly prefer a lower bound. It is not ideal, but it is acceptable.

Can the wheel for the current version be released soon, though? I really want to be able to officially support Python 3.6. (If in rainbow and unicorn world it could be done tomorrow, then I could add it into our release, but I recognize that might not be feasible for you.)

**Comment by kpayson64** [comment]
I've just upload grpcio/grpcio-tools 1.1.3, which has binary packages for Python 3.6.

**Comment by lukesneeringer** [comment]
:tada: _Thank you so much!!!_ :-)

**Comment by jonparrott** [comment]
Awesome, can confirm - builds using grpcio with 3.6 on travis are passing. https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/102

Thanks!
