### ISSUE TITLE
Add Ruby test coverage

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#945]
This is twofold:

1) The C bindings need to be able to compile properly with the "gcov" configuration.
2) The Ruby code needs to have coverage tests enabled: https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails

**Comment by murgatroid99** [comment]
This depends on issue #970

**Comment by ctiller** [comment]
Good to have before we start moving towards GA, just to know where our testing hole are. Shouldn't necessarily block beta, but that's the only tool we currently have.

**Comment by ctiller** [comment]
Good to have before we start moving towards GA, just to know where our testing hole are. Shouldn't necessarily block beta, but that's the only tool we currently have.

**Comment by tbetbetbe** [comment]
Moved from Beta to GA - there's already a coverage report for the Ruby code.

The work to produce a combined coverage report needs the tools defined #970, which is on the GA milestone

**Comment by tbetbetbe** [comment]
Closing, has been replaced by #3778
