### ISSUE TITLE
Problems with one generated module importing another generated module

### ISSUE THREAD

**Issue by macnibblet** [grpc/grpc#9450]

**Comment by macnibblet** [comment]
I just noticed the reason for this, the plugin does not handle empty services. If you remove the service it works fine.

**Comment by nathanielmanistaatgoogle** [comment]
That's strange. With what version of `grpcio` and `grpcio-tools` are you working?

**Comment by nathanielmanistaatgoogle** [comment]
Ahh! I should have seen that.

**Comment by macnibblet** [comment]
It's still not working tho, I'm not sure if what I have done is bad practice but I have a common.proto that has a bunch of messages & enums that I re-use in my Requests/Responses. But i'm getting an error that it cannot import `common_pb2` and for some reason, it's also importing it ten times. 

```python

import common_pb2 as common__pb2
import aphrodite_pb2 as aphrodite__pb2
import aphrodite_pb2 as aphrodite__pb2
import aphrodite_pb2 as aphrodite__pb2
import aphrodite_pb2 as aphrodite__pb2
import aphrodite_pb2 as aphrodite__pb2
import aphrodite_pb2 as aphrodite__pb2
import aphrodite_pb2 as aphrodite__pb2
import common_pb2 as common__pb2
import aphrodite_pb2 as aphrodite__pb2
```

the file `common_pb2.py` is in the same folder ?

**Comment by nathanielmanistaatgoogle** [comment]
I think you're seeing multiple imports because [pull request 9100](https://github.com/grpc/grpc/pull/9100) has not yet been included in a release (it will be included in our upcoming `1.1.0`).

As to the `ImportError` that you're seeing (it is an `ImportError`, right?): how certain are you that your `PYTHONPATH` includes the directories in which your generated code resides? If you were to write a completely hand-authored module in that directory that imported another hand-authored module in that directory, would the same `ImportError` arise?

**Comment by macnibblet** [comment]
I have installed the generate code into my python path by using setuptools and ` setup.py` in my protobuf repository. So it's import the initial files, but subsequent imports fails because it's trying to import the other files as a module and not a file in the same directory.

I would expect to see `from . import common_pb2 as common__pb2` 

It's also very possible i'm doing something really stupid :crying_cat_face:

**Comment by nathanielmanistaatgoogle** [comment]
I've filed "it would be a kindness to our developer-users if valid code were produced even when the input `.proto` file contains empty services" as [issue 9451](https://github.com/grpc/grpc/issues/9451).

**Comment by macnibblet** [comment]
Thanks

**Comment by nathanielmanistaatgoogle** [comment]
One of the things `grpc_python_plugin` does is delegate to `protoc` for how one generated Python module should import another generated Python module. Maybe `protoc` has a defect in the way that it generates these imports? Or maybe `grpc_python_plugin` has a bug in the way that it tells `protoc` to create imports.

We have tests that cover what we think are a few different likely ways of writing `.proto` files, but perhaps you're falling in a gap somewhere.

Apologies for asking for legwork, but can you boil this down to a small reproduction? Sharing with us your `.proto` files and your generated code? I also want to look at this more but won't have time until late next week at the earliest.

**Comment by macnibblet** [comment]
Heya,

I'm not sure what the best way to do this is but I created a repo with a test case with reproducing case
https://github.com/macnibblet/grpc-bug-9450

**Comment by nathanielmanistaatgoogle** [comment]
@macnibblet: I see that you're using a "python/" target directory for your code generation - is that associated with this issue? If you use ".", is valid, runnable code generated for the otherwise-unaltered scenario?

**Comment by nathanielmanistaatgoogle** [comment]
@macnibblet: I've been thinking this over and looking sideways at it and it's occurred to me that we have test coverage of the scenario that I think is at play here. If I might trouble you for a little more investigation, could you take a look at `_split_definitions_test` and describe what's incomplete about it? What should be changed about it to cover the scenario that's failing for you?

**Comment by GeorgeDittmar** [comment]
Is there any new traction on this issue? our grpc services cant be migrated to python 3 due to the relative import issue. have tried most methods I can find around from googling but nothing has resolved our issue so far.

**Comment by nathanielmanistaatgoogle** [comment]
I don't have a timeline for it, but I suspect the resolution of this issue will be something along the lines of "gRPC Python Protoc Plug-In delegates all decision-making about module imports and uses in generated Python code to a part of Protoc exposed as a library". @acozzette and I started on that implementing just that more than a year ago and while I haven't finished what I drafted, I also haven't deleted it...

**Comment by tvalentyn** [comment]
See https://github.com/protocolbuffers/protobuf/issues/1491 for a discussion of this issue.
