### ISSUE TITLE
grpc_python_plugin should generate valid code even for empty services

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#9451]
I'm not sure that this is something we want to _promise_ or guarantee in our API, but it would be _a kindness to our users_ to generate valid Python code even when the user's `.proto` input to `protoc` contains an empty `Service`.

See [this report](https://github.com/grpc/grpc/issues/9450#issue-202645111) from a real user having been in this situation.

**Comment by nathanielmanistaatgoogle** [comment]
I _suspect_ that this defect is no longer present because the generated code is given a doc string on every code element. It would be nice to have a unit test running to confirm it though.

**Comment by jmillikin** [comment]
This defect is still present as of v1.1.2. The proto `service Echo { }` will generate the following Python code:

```python
  class EchoServicer(object):


  def add_EchoServicer_to_server(servicer, server):
    rpc_method_handlers = { 
    }   
    generic_handler = grpc.method_handlers_generic_handler(
        'Echo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
```

**Comment by nathanielmanistaatgoogle** [comment]
@jmillikin: thank you for looking into it. It should be the case that those two code elements have doc strings attached to them; we'll look into why that isn't happening.
