### ISSUE TITLE
Flaky aggregate_tests.run_tests_c_macos_dbg

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#9473]
Here is the log from jenkins: https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2154/testReport/junit/(root)/aggregate_tests/run_tests_c_macos_dbg/

Error Message

Failure
Standard Output

ED: bins/dbg/h2_uds_test no_op [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test payload
PASSED: bins/dbg/h2_uds_test hpack_size [time=6.9sec; retries=0:0]
START: bins/dbg/h2_uds_test ping
PASSED: bins/dbg/h2_uds_test ping [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test ping_pong_streaming
PASSED: bins/dbg/h2_uds_test ping_pong_streaming [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test registered_call
PASSED: bins/dbg/h2_uds_test registered_call [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test request_with_flags
PASSED: bins/dbg/h2_uds_test payload [time=1.9sec; retries=0:0]
START: bins/dbg/h2_uds_test request_with_payload
PASSED: bins/dbg/h2_uds_test request_with_payload [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test resource_quota_server
PASSED: bins/dbg/h2_uds_test resource_quota_server [time=1.7sec; retries=0:0]
START: bins/dbg/h2_uds_test server_finishes_request
PASSED: bins/dbg/h2_uds_test server_finishes_request [time=0.3sec; retries=0:0]
START: bins/dbg/h2_uds_test shutdown_finishes_calls
PASSED: bins/dbg/h2_uds_test shutdown_finishes_calls [time=0.3sec; retries=0:0]
START: bins/dbg/h2_uds_test shutdown_finishes_tags
PASSED: bins/dbg/h2_uds_test shutdown_finishes_tags [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test simple_cacheable_request
PASSED: bins/dbg/h2_uds_test simple_cacheable_request [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test simple_delayed_request
PASSED: bins/dbg/h2_uds_test simple_delayed_request [time=2.1sec; retries=0:0]
START: bins/dbg/h2_uds_test simple_metadata
PASSED: bins/dbg/h2_uds_test simple_metadata [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test simple_request
PASSED: bins/dbg/h2_uds_test simple_request [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test streaming_error_response
PASSED: bins/dbg/h2_uds_test streaming_error_response [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test trailing_metadata
PASSED: bins/dbg/h2_uds_test trailing_metadata [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test write_buffering
PASSED: bins/dbg/h2_uds_test write_buffering [time=0.0sec; retries=0:0]
START: bins/dbg/h2_uds_test write_buffering_at_end
PASSED: bins/dbg/h2_uds_test write_buffering_at_end [time=0.0sec; retries=0:0]
START: bins/dbg/head_of_line_blocking_bad_client_test
START: bins/dbg/headers_bad_client_test
PASSED: bins/dbg/head_of_line_blocking_bad_client_test [time=0.0sec; retries=0:0]
START: bins/dbg/hpack_parser_test
PASSED: bins/dbg/hpack_parser_test [time=0.0sec; retries=0:0]
START: bins/dbg/hpack_table_test
PASSED: bins/dbg/hpack_table_test [time=1.1sec; retries=0:0]
START: bins/dbg/http_parser_test
PASSED: bins/dbg/http_parser_test [time=0.0sec; retries=0:0]
START: bins/dbg/httpcli_format_request_test
START: bins/dbg/httpcli_test
PASSED: bins/dbg/httpcli_format_request_test [time=0.0sec; retries=0:0]
START: bins/dbg/init_test
START: bins/dbg/initial_settings_frame_bad_client_test
PASSED: bins/dbg/init_test [time=0.0sec; retries=0:0]
START: bins/dbg/invalid_call_argument_test
PASSED: bins/dbg/headers_bad_client_test [time=1.5sec; retries=0:0]
START: bins/dbg/json_rewrite_test
PASSED: bins/dbg/json_rewrite_test [time=0.0sec; retries=0:0]
START: bins/dbg/json_stream_error_test
PASSED: bins/dbg/json_stream_error_test [time=0.0sec; retries=0:0]
START: bins/dbg/json_test
PASSED: bins/dbg/json_test [time=0.0sec; retries=0:0]
START: bins/dbg/lame_client_test
PASSED: bins/dbg/lame_client_test [time=0.0sec; retries=0:0]
START: bins/dbg/large_metadata_bad_client_test
PASSED: bins/dbg/large_metadata_bad_client_test [time=0.0sec; retries=0:0]
START: bins/dbg/load_file_test
PASSED: bins/dbg/load_file_test [time=0.0sec; retries=0:0]
PASSED: bins/dbg/initial_settings_frame_bad_client_test [time=0.7sec; retries=0:0]
PASSED: bins/dbg/httpcli_test [time=5.0sec; retries=0:0]
START: bins/dbg/memory_profile_test
PASSED: bins/dbg/invalid_call_argument_test [time=6.1sec; retries=0:0]
PASSED: bins/dbg/memory_profile_test [time=3.0sec; retries=0:0]
START: bins/dbg/message_compress_test
PASSED: bins/dbg/h2_uds_test request_with_flags [time=15.0sec; retries=0:0]
START: bins/dbg/multiple_server_queues_test
PASSED: bins/dbg/multiple_server_queues_test [time=0.0sec; retries=0:0]
START: bins/dbg/murmur_hash_test
PASSED: bins/dbg/murmur_hash_test [time=0.0sec; retries=0:0]
START: bins/dbg/no_server_test
PASSED: bins/dbg/message_compress_test [time=2.4sec; retries=0:0]
START: bins/dbg/percent_encoding_test
PASSED: bins/dbg/percent_encoding_test [time=0.0sec; retries=0:0]
START: bins/dbg/resolve_address_test
PASSED: bins/dbg/no_server_test [time=2.0sec; retries=0:0]
PASSED: bins/dbg/resolve_address_test [time=15.3sec; retries=0:0]
START: bins/dbg/resource_quota_test
PASSED: bins/dbg/resource_quota_test [time=0.0sec; retries=0:0]
START: bins/dbg/secure_channel_create_test
START: bins/dbg/secure_endpoint_test
PASSED: bins/dbg/secure_channel_create_test [time=0.0sec; retries=0:0]
START: bins/dbg/sequential_connectivity_test
PASSED: bins/dbg/secure_endpoint_test [time=10.1sec; retries=0:0]
START: bins/dbg/server_chttp2_test
PASSED: bins/dbg/server_chttp2_test [time=0.0sec; retries=0:0]
START: bins/dbg/server_registered_method_bad_client_test
PASSED: bins/dbg/server_registered_method_bad_client_test [time=0.0sec; retries=0:0]
START: bins/dbg/server_test
PASSED: bins/dbg/server_test [time=0.1sec; retries=0:0]
START: bins/dbg/set_initial_connect_string_test
PASSED: bins/dbg/set_initial_connect_string_test [time=20.1sec; retries=0:0]
START: bins/dbg/simple_request_bad_client_test
PASSED: bins/dbg/simple_request_bad_client_test [time=0.2sec; retries=0:0]
START: bins/dbg/slice_buffer_test
PASSED: bins/dbg/slice_buffer_test [time=0.0sec; retries=0:0]
START: bins/dbg/slice_string_helpers_test
PASSED: bins/dbg/slice_string_helpers_test [time=0.0sec; retries=0:0]
START: bins/dbg/slice_test
PASSED: bins/dbg/slice_test [time=0.5sec; retries=0:0]
START: bins/dbg/sockaddr_resolver_test
PASSED: bins/dbg/sockaddr_resolver_test [time=0.0sec; retries=0:0]
START: bins/dbg/sockaddr_utils_test
PASSED: bins/dbg/sockaddr_utils_test [time=0.0sec; retries=0:0]
START: bins/dbg/socket_utils_test
PASSED: bins/dbg/socket_utils_test [time=0.0sec; retries=0:0]
START: bins/dbg/tcp_client_posix_test
START: bins/dbg/tcp_posix_test
PASSED: bins/dbg/tcp_client_posix_test [time=1.0sec; retries=0:0]
PASSED: bins/dbg/tcp_posix_test [time=6.6sec; retries=0:0]
START: bins/dbg/tcp_server_posix_test
PASSED: bins/dbg/tcp_server_posix_test [time=0.0sec; retries=0:0]
START: bins/dbg/time_averaged_stats_test
PASSED: bins/dbg/time_averaged_stats_test [time=0.0sec; retries=0:0]
START: bins/dbg/timeout_encoding_test
PASSED: bins/dbg/timeout_encoding_test [time=0.0sec; retries=0:0]
START: bins/dbg/timer_heap_test
PASSED: bins/dbg/timer_heap_test [time=0.3sec; retries=0:0]
START: bins/dbg/timer_list_test
PASSED: bins/dbg/timer_list_test [time=0.0sec; retries=0:0]
START: bins/dbg/transport_connectivity_state_test
PASSED: bins/dbg/transport_connectivity_state_test [time=0.0sec; retries=0:0]
START: bins/dbg/transport_metadata_test
PASSED: bins/dbg/transport_metadata_test [time=1.6sec; retries=0:0]
START: bins/dbg/transport_pid_controller_test
PASSED: bins/dbg/transport_pid_controller_test [time=0.0sec; retries=0:0]
START: bins/dbg/transport_security_test
PASSED: bins/dbg/transport_security_test [time=0.0sec; retries=0:0]
START: bins/dbg/udp_server_test
PASSED: bins/dbg/udp_server_test [time=0.0sec; retries=0:0]
START: bins/dbg/unknown_frame_bad_client_test
PASSED: bins/dbg/unknown_frame_bad_client_test [time=0.1sec; retries=0:0]
START: bins/dbg/uri_parser_test
PASSED: bins/dbg/uri_parser_test [time=0.0sec; retries=0:0]
START: bins/dbg/wakeup_fd_cv_test
PASSED: bins/dbg/sequential_connectivity_test [time=42.0sec; retries=0:0]
START: bins/dbg/window_overflow_bad_client_test
PASSED: bins/dbg/wakeup_fd_cv_test [time=2.1sec; retries=0:0]
PASSED: bins/dbg/window_overflow_bad_client_test [time=0.1sec; retries=0:0]
FAILED: bins/dbg/h2_compress_nosec_test resource_quota_server
START: tools/run_tests/helper_scripts/post_tests_c.sh
PASSED: tools/run_tests/helper_scripts/post_tests_c.sh [time=0.0sec; retries=0:0]
FAILED: Some tests failed

**Comment by muxi** [comment]
Known issue as #9398, @vjpai is looking on it
