### ISSUE TITLE
gRPC proto files should be in a central repository

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#9475]
Many proto files for gRPC are duplicated across [`grpc/grpc`](https://github.com/grpc/grpc), [`grpc/grpc-go`](https://github.com/grpc/grpc-go), and [`grpc/grpc-java`](https://github.com/grpc/grpc-java). For example:

- [reflection.proto in gRPC](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto)
- [reflection.proto in gRPC-Go](https://github.com/grpc/grpc-go/blob/master/reflection/grpc_reflection_v1alpha/reflection.proto)
- [reflection.proto in gRPC-Java](https://github.com/grpc/grpc-java/blob/master/services/src/main/proto/io/grpc/reflection/v1alpha/reflection.proto)

These should either be moved into a new repository (such as `grpc/grpc-proto`) or some other mechanism introduced to make sure the proto files are standardized across locations.

**Comment by jtattermusch** [comment]
For the C core repo, having some proto files in a submodule might be complicated from the point of view of different build systems (they might expect proto files in specific locations in our repo and it's easier to build proto files that are directly checked into the main repo). One solution that might work for C core repo:
- add all the shared protos to grpc/grpc-proto
- have copies of shared protoc directly in grpc/grpc
- add a sanity test to check that protos in grpc/grpc are the same as the reference ones in grpc/grpc-proto (easy to add to our existing sanity suite).

**Comment by markdroth** [comment]
@jboeuf will be interested in this.  The security folks will soon need to add a proto file for their handshaker API, which will want to use the same solution that we wind up choosing for the rest of these files.

**Comment by markdroth** [comment]
We do now have the grpc/grpc-proto repo, but the grpc/grpc repo still has its own copies of most of these proto files.  We should replace those copies with use of the canonical files via a submodule.
