### ISSUE TITLE
NuGet Package Dependency Problem

### ISSUE THREAD

**Issue by tuxagon** [grpc/grpc#9484]
I'm encountering an interesting issue and it could be due to lack of experience, but I am creating a NuGet package that has a dependency on `Grpc.Core`. Everything works fine in the project that will be turned into a NuGet package; however, any other project that uses my package has the binaries from `Grpc.Core`'s NuGet `runtimes` folder installed at the project's root. I don't want the binaries installed at the project root and it begs the question on whether this is a problem with the gRPC NuGet package since it does this by default. 

Also it should be noted that when I build, those binaries are appropriately copied to the bin folder from `runtimes` through the provided targets file. The binaries are unnecessarily installed at the project root.

When I run `nuget pack`, this is the warning I receive, which can help explain why the binaries are being added to the project root; however, I don't know why they are being considered `content`

```
Issue: Assembly outside lib folder.
Description: The assembly 'content\grpc_csharp_ext.x64.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
Solution: Move it into the 'lib' folder if it should be referenced.

Issue: Assembly outside lib folder.
Description: The assembly 'content\grpc_csharp_ext.x86.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
Solution: Move it into the 'lib' folder if it should be referenced.
```

**Comment by jtattermusch** [comment]
I assume you are using desktop .NET (as opposed to coreCLR). What you are describing seems like things behaving as expected. The native DLLs are added to your project by Grpc.Core nuget so that they can be copied to the output directory after building your project. gRPC C# depends on the grpc_csharp_ext library (gRPC C# is a wrapper around a gRPC C core library).

**Comment by jtattermusch** [comment]
Unless something is broken for you, I'll close this issue now (feel free to reopen if needed).

**Comment by tuxagon** [comment]
I know the binaries are needed, but it's the location at which it places them that is the problem. See http://stackoverflow.com/questions/41941588/binaries-are-added-to-project-when-nuget-package-has-grpc-core-as-a-dependency

**Comment by tuxagon** [comment]
I did figure this out. Solution will be posted to the previous stackoverflow link

**Comment by sunsided** [comment]
Related: #11279
