### ISSUE TITLE
Unreliable Socket Communication (UDP)

### ISSUE THREAD

**Issue by Disturbing** [grpc/grpc#9493]
Requesting support for unreliable packets. This use case goes for most real time games and think it would greatly benefit the www.unity3d.community.  Example implementation use case is the standard interpolation/extropolation requirements for FPS: https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking

I've been looking at the repro for a while, and would love to help make this feature happen.

Overall, my suggestion is to be able to enable multiple sockets (similar to #8639).  The problem here is that in most real time games, you wish to have reliable and unreliable, thus you need to either create your own protocol and create reliable UDP or have a reliable (http2/tcp) + udp connections.  To make this easier, being able to abstract out the socket itself so you can register socket handlers as "channel types" would allow people to implement their own as they see fit and hopefully create standardized sockets to be used across the board.

As per implementation, I'd imagine something along the lines of:

- **Option 1: ** Function level definitions would have an optional 'preferred channel type'. By default, this could be reliable HTTP2.
- **Option 2: **Service level definition would allow you to register a service to a particular channel.

**Comment by g-ericso** [comment]
+1

**Comment by Blanen** [comment]
I'd like this as well.

But there's this old issue that was denied:

https://github.com/grpc/grpc-go/issues/241

**Comment by Disturbing** [comment]
Well we must rock the boat! For real time gaming, this is a huge plus to get.  If we come up with a specification/standard and get this accepted, I'm committed to writing the .NET and Java versions.

**Comment by Blanen** [comment]
Might require a change in protocol if I read the gRPC stuff correctly, right? Since it basically always waits for a response, whether that's sync or async. So either you extent gRPC to allow no-response messages, or make something on top of UDP to reliably get responses, at which point you might as well use TCP...

This might be completely wrong since I have only done reading about gRPC for now.

**Comment by Disturbing** [comment]
Correct, we would have to implement a UDP protocol.

I'd want to leave everything in gRPC the same, no need to define anything as 'reliable or unreliable' in terms of defining your services.

When a client requests to use a service via "Channel" - I'd propose Unreliable options:

```
//C# Modified Example from - http://www.grpc.io/docs/tutorials/basic/csharp.html
// I suggest adding A protocol option to the Channel, by default being HTTP/2. Later (As people have also proposed) adding TCP, websockets and then as we're proposing - adding UDP.

Channel channel = new Channel("127.0.0.1:50052", ChannelCredentials.Insecure, ChannelProtocol.UDP)
var client = new RouteGuide.RouteGuideClient(channel);

// YOUR CODE GOES HERE

channel.ShutdownAsync().Wait();
```

Server wise, people can enable/disable the Protocol options they want on their server. Maybe all 4 will be enabled so that clients can decide at will.

I have not spent too much time thinking of a great way to do this - but the optimal use case is if we can specifiy exact methods on a gRPC service to be reliable / unreliable. A simple use case being:

reliable - GameWorldService#FireWeapon 
unreliable - GameWorldService#OnMovementUpdatedStream

May sound crazy, but maybe this can be configured via:


```
Channel channel = new Channel("127.0.0.1:50052", ChannelCredentials.Insecure);

// This is a nice way to do it in C#, but doubt it would be nice across all languages?
var client = new GameWorldService.GameWorldClientClient(channel)
    // This function would ensure the protocol that
    .ConfigureMethodProtocol(client => client.GetFeature, ChannelProtocol.UDP)
    .Build();

// YOUR CODE GOES HERE

channel.ShutdownAsync().Wait();
```

**Comment by bkeys** [comment]
Has there been any updates on this? I would love to have UDP on gRPC for my game servers

**Comment by ahundt** [comment]
Rather than a simple reliable/unreliable binary split, a limited selection of algorithms with clear known applications, such as smooth performance degradation for real time games and and for robotics (which has many similarities to real time games) may be a better option. One example algorithm would be unreliable transport and another example could be prioritized channels with deadlines.

Libraries that could be used for informative reference:
https://github.com/lcm-proj/lcm
http://www.spines.org/

**Comment by vjpai** [comment]
@Blanen : there is no need that every message has to have a response; in particular, streaming RPCs can have an unbalanced number of Writes and Reads. If you want a no-response message, you can use a bidirectional streaming RPC and then have the receiving side not send anything back (and I know of at least 1 user doing that for their use case). That is a discussion topic distinct from the general theme of this feature request, getting back to general usage (and for which grpc-io mailing list is the best forum).

**Comment by bhkeys** [comment]
@Disturbing Is there a place where we can start to write down some kind of spec for this thing? I have a lot of interest in making gRPC somehow appropriate for games. @vjpai Also seemed to have some good ideas on how to get this done. The talking part is over we need to get this done! c:

**Comment by Disturbing** [comment]
@ahundt - Agreed, but correct my if I'm wrong - maybe there could be some sort of 'addon' system for this? Build this out as a standard for the 10+ languages that gRPC supports will be tough.  Doing a quick unreliable channel would be helpful and quick IMO.

@bhkeys 
Not sure what the proposal process is for creating a pull request or proposal.  I think I can come up with one but again, would like some feedback before starting because it's quite crucial.

Is it important to:

1) Have a method level reliable/unreliable support
2) Have channel level reliable/unreliable support.

The problem with doing channel level is that you'd have to deal with two different services and calling them appropriately, thus I'm in favor of (1). But would love feedback.

Once hearing feedback, I can then draft a proposal and prototype it on C# first to see how people like it.  Then can discuss getting it standardized.

**Comment by Disturbing** [comment]
Another thought, what if we do something similar to gRPC Websockets proxy: 

https://github.com/tmc/grpc-websocket-proxy

What if the grpc gateway simply handles HTTP/1 -> gRPC conversion, Websockets, UDP and TCP protocols for conversion?  Would need to look into this more and figure out a good standardization, but I think this would be the best way to support all 10 languages at once.

**Comment by ahundt** [comment]
@disturbing Unfortunately that wouldn't meet requirements for applications that need UDP because the guarantees and performance degradation properties of TCP would still be required. Here is a 2017 paper that won a best paper award that serves as an example of what should be possible to implement:

http://www.dsn.jhu.edu/papers/dissemination_graphs_icdcs2017.pdf 

In other words it is okay if UDP grpc doesn't actually implement this but it should provide the necessary building blocks to make it possible and simpler.

**Comment by Disturbing** [comment]
Roger!

**Comment by Disturbing** [comment]
Alright, bounty is up.

Anyone who's an expect in **any** of the grpc languages and would like to work on a UDP implementation - I'd like to make this happen by Summer 2018 and willing to pay some chump change for it.

I'm creating a community where open source initiatives will be able to make some mad cash.  If interested, I'll be organizing a meeting and proposal by October 15th, 2017 to make the UDP happen in the gRPC ecosystem.

Feel free to contact us at www.kintohub.com if you're interested in joining the first meeting.

**Comment by aep** [comment]
is an implementation over quic (https://en.wikipedia.org/wiki/QUIC) an acceptable alternative? We're thinking of doing that

**Comment by ahundt** [comment]
quic looks like it didn't make progress towards being a standard and google's implementations don't seem to be updated anymore

**Comment by zefyrr** [comment]
Would it be possible to leverage cronet on the cpp side for this?

**Comment by evbarnett** [comment]
+1 for UDP- but it would also be great if there are open protocol abstractions in case the user wants to use *any* protocol; the user would just provide the implementation themselves. (I'd like to use raw sockets!)

**Comment by VMatrix1900** [comment]
@aep QUIC currently does not support unreliable transport.

**Comment by hsaliak** [comment]
Closing this - we have no plan to support unreliable packets at the moment. If we have any particular protocol that can fit the use cases listed above, we will probably do a grfc first..
