### ISSUE TITLE
Controlling PHP-ext log verbosity

### ISSUE THREAD

**Issue by jstruzik** [grpc/grpc#9509]
Following the [install instructions](https://github.com/grpc/grpc/tree/master/src/php#quick-install) for the GRPC PHP-ext via Pecl, on Linux environments with a glibc < 2.17 I get the following info log:

```
env_linux.c:77] Warning: insecure environment read function 'getenv' used
```

Default log verbosity should have been changed to `ERROR` in > 1.0.0 according to https://github.com/grpc/grpc/pull/7438. Setting the `GRPC_VERBOSITY` environment variable doesn't seem to have an impact with the compiled Pecl extension.

Related to https://github.com/grpc/grpc/issues/8104 and https://github.com/grpc/grpc/issues/7620.

**Comment by Binarytales** [comment]
I'm seeing this same issue with the Node library.

**Comment by sagikazarmark** [comment]
Are there any news regarding this issue?

**Comment by Tyrael** [comment]
any chance that 79764a3bfbdec89b93b2f4a52b73e4b2ec275226 is supposed to fix this just @ncteisen forgot to link this issue?
based on that commit, this should be fixed in grpc 1.6.0-pre1 unfortunalley the 1.6.0 version doesn't have a stable release on https://pecl.php.net/package/grpc

**Comment by ncteisen** [comment]
Yep, that should fix it! (It's from pull req #11770
<https://github.com/grpc/grpc/pull/11770>).

 Could you verify that by running at head? Or if that is not easy to do,
will you verify the fix once we release a version with the fix included?

**Comment by Tyrael** [comment]
I would prefer to have an 1.6.0(or 1.6.1) stable on pecl, but I can compile from source (but a bit messy because you package different config.m4 for pecl what you have under src/php/ext/grpc/config.m4)

**Comment by ncteisen** [comment]
Let me know if you verify the fix from source. Thanks!

**Comment by Tyrael** [comment]
with 1.6.0 stable I don't get the "Warning: insecure environment read function 'getenv' used" message

**Comment by ncteisen** [comment]
Great! Let's close this once a stable version with my fix is in

**Comment by Tyrael** [comment]
@stanley-cheung made a stable pecl release for 1.6.0 six days ago, I was testing with that, so you should be fine to close this right now.
