### ISSUE TITLE
synchronous service functions in NodeJS

### ISSUE THREAD

**Issue by ramirezd42** [grpc/grpc#9517]
Sorry if this has been discussed already, but is there a means of calling service functions in a synchronous way as there is in other languages? If so, I can't find it documented anywhere.

I KNOW this is an uncommon use case in node. But a library i'm trying to write has a need for it.

Something like the following:

```
var PROTO_PATH = __dirname + '/../../protos/helloworld.proto';

var grpc = require('grpc');
var hello_proto = grpc.load(PROTO_PATH).helloworld;

function main() {
  var client = new hello_proto.Greeter('localhost:50051',
                                       grpc.credentials.createInsecure());
  var user;
  if (process.argv.length >= 3) {
    user = process.argv[2];
  } else {
    user = 'world';
  }
  var response = client.sayHello({name: user});
  console.log('Greeting:', response.message);
}

main();
```

**Comment by murgatroid99** [comment]
No, you cannot call gRPC service methods in a synchronous manner. They are fundamentally asynchronous. You may be able to force an apparently synchronous control flow with a library like [deasync](https://www.npmjs.com/package/deasync), but I would strongly recommend trying first to express what you want to do in an asnyc manner.

**Comment by ramirezd42** [comment]
Yeah, as a general rule I agree. For the record deasync, did the trick!

Closing this.
