### ISSUE TITLE
Error compiling the cpp helloworld (master)

### ISSUE THREAD

**Issue by AngryLemonn** [grpc/grpc#9520]
Hello there,

I am working in a project where I need one rpc server in C++ and one rpc client in php. I tried to use the grpc v1.0.0 and v1.0.1, but compiling the php extension I got some errors that couldn't solve by myself.

Triying the last grpc version ( master ), the compilation of the grpc core and grpc php extension was good, but trying the examples I got this error during the compilation of the helloworld package in the cpp tests.

```
protoc -I ../../protos --cpp_out=. ../../protos/helloworld.proto
g++ -std=c++11 -I/usr/local/include -pthread  -c -o helloworld.pb.o helloworld.pb.cc
protoc -I ../../protos --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ../../protos/helloworld.proto
g++ -std=c++11 -I/usr/local/include -pthread  -c -o helloworld.grpc.pb.o helloworld.grpc.pb.cc
In file included from /usr/local/include/grpc++/impl/codegen/call.h:43:0,
                 from /usr/local/include/grpc++/impl/codegen/async_stream.h:37,
                 from helloworld.grpc.pb.h:39,
                 from helloworld.grpc.pb.cc:6:
/usr/local/include/grpc++/impl/codegen/client_context.h:60:46: fatal error: grpc++/impl/codegen/metadata_map.h: No existe el fichero o el directorio
 #include <grpc++/impl/codegen/metadata_map.h>
                                              ^
compilation terminated.
<builtin>: recipe for target 'helloworld.grpc.pb.o' failed
make: *** [helloworld.grpc.pb.o] Error 1
```

After search a little, I see that the file metadata_map.h doesn't exists in **_/usr/local/include/grpc++/impl/codegen_**

What happend guys?? The master is not stable?? Any idea to solve this error??

Regards,
J. A

**Comment by ncteisen** [comment]
Looks like the file is still there to me: https://github.com/grpc/grpc/tree/master/include/grpc%2B%2B/impl/codegen

Please ensure that you have installed the most current version, then run:
```
make
[sudo] make install
```

**Comment by AngryLemonn** [comment]
I did the **_make_** and the **_sudo make install_** before create the issue. Even so, I repeat the installation of the latest version of grpc (and protobuf) and these are the files that the make install in **_/usr/local/include/grpc_**:

```
async_stream.h            rpc_method.h
async_unary_call.h        rpc_service_method.h
call.h                    security
call_hook.h               serialization_traits.h
channel_interface.h       server_context.h
client_context.h          server_interface.h
client_unary_call.h       service_type.h
completion_queue.h        slice.h
completion_queue_tag.h    status_code_enum.h
config.h                  status.h
config_protobuf.h         status_helper.h
core_codegen.h            string_ref.h
core_codegen_interface.h  stub_options.h
create_auth_context.h     sync_stream.h
grpc_library.h            thrift_serializer.h
method_handler_impl.h     thrift_utils.h
proto_utils.h             time.h

```

There are no file named metadata_map.h :(

**Comment by yang-g** [comment]
I think there is a small bug. I will send a PR to fix it soon. Thanks for reporting.

**Comment by yang-g** [comment]
I just merged the fix. Please let me know if you still have issues building the example. Thanks.
