### ISSUE TITLE
Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9538]
Failed in this test:https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2401/console
```
[1mstderr:[0m
E0201 05:36:40.466630118    7952 ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0201 05:36:40.468019862    7952 ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.


Unexpected successes: []
Test failure
```

**Comment by nathanielmanistaatgoogle** [comment]
@dgquintas: any idea what would need to happen within the core for a test to fail this way? What _might_ gRPC Python be doing wrong to get `ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.`?

**Comment by dgquintas** [comment]
No idea. @jboeuf , @nicolasnoble , any clues?

**Comment by jboeuf** [comment]
what is the client and what is the server here? Any idea about which
openssl/boringssl stack is used on both?
In core, we are forcing TLS 1.2 (as per http2 spec, section 9.2
https://tools.ietf.org/html/rfc7540). If the other party does not support
that, then we will get this error.

**Comment by nathanielmanistaatgoogle** [comment]
@jboeuf: this was a failure in a mostly-not-flaky, definitely-not-deterministically-failing unit test, at commit bb2e8af0b003cc0e583fc7978dba3a55c125cc13 in [pull request 9532](https://github.com/grpc/grpc/pull/9532). Whatever the openssl/boringssl stack used we were in full control of both sides the whole time. [The call was coming from inside the house!](http://tvtropes.org/pmwiki/pmwiki.php/Main/TheCallsAreComingFromInsideTheHouse)

**Comment by jboeuf** [comment]
That is very strange. The thing that could have happened is a byte
corruption on the wire. If the handshake fails at this stage (very early
in), it will not verify go through the authenticator phase that
cryptographically verify the bytes of the handshake.

**Comment by apolcyn** [comment]
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/3362/testReport/junit/(root)/python_linux_dbg_native/py27_test_unit_beta__face_interface_test_GenericInvokerFutureInvocationAsynchronousEventServiceTest/

pr https://github.com/grpc/grpc/pull/9986 against v1.2.x

**Comment by jboeuf** [comment]
+ @ctiller 
It smells like something more than a byte corruption on the wire... Could it be that some data is left in a buffer on the client stack and sent to the server before the proper SSL ClientInit handshake when the client reconnects? A bad first SSL Client Init message would explain the `WRONG_VERSION_NUMBER` error.

**Comment by BusyJay** [comment]
Is this issue fixed by any commit? I can't find any clues here.

**Comment by dgquintas** [comment]
@BusyJay are you still seeing the issue? It was closed for lack of updates in a while.

**Comment by BusyJay** [comment]
Yes. I can see the error in [Travis CI](https://travis-ci.org/pingcap/grpc-rs/jobs/301305987) with grpc core v1.6.2.

**Comment by dgquintas** [comment]
This issue has to do with the code at HEAD, not for any particular version.

**Comment by zaneclaes** [comment]
This is still happening with C# on 1.7.1.

**Comment by davidraleigh** [comment]
Using `pip3 install grpcio-tools==1.9.0` and `pip3 install grpcio==1.9.0` on both client and server and seeing the error:
```bash 
ssl_transport_security.cc:979] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```

When I run `openssl s_client -connect google.com:443 -tls1_2` ([serverfault suggestion](https://serverfault.com/a/638692/390998)) on both client and server I get back the expected print out of certificates that confirms TLS 1.2 is available on both.

Is there a grpc version we can roll back to for a temporary workaround?

**Comment by nathanielmanistaatgoogle** [comment]
@davidraleigh: does that mean you have a deterministic reproduction case? Are you able to share it? How reduced can you make it?

**Comment by davidraleigh** [comment]
@nathanielmanistaatgoogle I'm wondering if my creation of certificates for testing is the problem. My guess is that this isn't an error in the library except that maybe the exception message is misleading. I'll throw a test case together.

**Comment by davidraleigh** [comment]
Hey @nathanielmanistaatgoogle I have a test case. Again, I don't know if this is just user error.

I made a branch of grpc to change the route_guide example so that the server adds a secure port using `add_secure_port` instead of `add_insecure_port`. You can see the changes here https://github.com/EchoParkLabs/grpc/commit/5c060584260633235959dfedbcb45992d2aabcc0

```python
    #server.add_insecure_port('[::]:50051')
    with open('server.key') as f:
        private_key = f.read()
    with open('server.crt') as f:
        certificate_chain = f.read()

    server_credentials = grpc.ssl_server_credentials(
      ((private_key, certificate_chain,),))

    server.add_secure_port('[::]:50051', server_credentials)
```

Then use the following Dockerfile to build the test case: https://gist.github.com/davidraleigh/08acc72495922dc149a86e004f435492
```Dockerfile
FROM python:2.7

RUN pip install grpcio
RUN pip install grpcio-tools

WORKDIR /opt

RUN git clone https://github.com/EchoParkLabs/grpc.git --branch wrong-version-number --depth 1

WORKDIR /opt/grpc/examples/python/route_guide

RUN openssl req -nodes -newkey rsa:2048 -x509 -days 365 -keyout server.key -out server.crt -subj "/C=US/ST=California/L=Los Angeles/O=Echo Park Labs/OU=Software/CN=echoparklabs.io"

CMD python route_guide_server.py

```

To run the test you'll need to run the following command in two terminals.
terminal 1:
```bash
sudo docker build -t test .
sudo docker run -it --name=wrong-version-c test
```

terminal 2:
```bash
sudo docker exec -it wrong-version-number /bin/bash -c 'python route_guide_client.py'
```

You will see the 'WRONG_VERSION_NUMBER' error in terminal 1:
```bash
Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```

**Comment by davidraleigh** [comment]
I find that the same error occurs if I use key and chain created with `letsencrypt-auto`

**Comment by davidraleigh** [comment]
And just for proof that the certificates aren't the problem here's an example of the same exact certificate working with Java:

```Dockerfile
FROM openjdk:8-jdk

WORKDIR /opt

RUN git clone https://github.com/EchoParkLabs/grpc-java.git --branch lets-e --depth 1

WORKDIR /opt/grpc-java/examples

RUN ./gradlew installDist

RUN openssl req -nodes -newkey rsa:2048 -x509 -days 365 -keyout server.key -out server.crt -subj "/C=US/ST=California/L=Los Angeles/O=Echo Park Labs/OU=Software/CN=echoparklabs.io"

ENV GRPC_KEY /opt/grpc-java/examples/server.key
ENV GRPC_CHAIN /opt/grpc-java/examples/server.crt

CMD ./build/install/examples/bin/route-guide-server
```

To test the above:
```bash
sudo docker build --no-cache -t test-java .
sudo docker run -it --name="test-container" test-java
```

From second terminal:
``bash
sudo docker exec -it test-container /bin/bash -c "./build/install/examples/bin/route-guide-client"
```

**Comment by frankang** [comment]
got the same error when using grpc behind a https proxy.

**Comment by tweenietomatoes** [comment]
same

**Comment by guyluz11** [comment]
Getting this error all the time in my dart client implementation of ESPHome.
On the existing python client implementation this **does not** happen.
Both were tested with the same server that run c++ code on esp device.
If you need more information about it I will be glad to add.

**Comment by JeroenBos** [comment]
I got this error even though I was providing certificates on both client and server side, but I used `location="grpc://{host}:{port}"` instead of `grpc+tls://{host}:{port}`.
