### ISSUE TITLE
Ruby cloud to prod test failure: empty_unary

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#9543]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11060/testReport/junit/(root)/tests/cloud_to_prod_default_ruby_empty_unary/

It's a connectivity failure, so it may not be ruby-specific

**Comment by jtattermusch** [comment]
I think this is just dupe of https://github.com/grpc/grpc/issues/10763.
