### ISSUE TITLE
objc_macos_opt.objc-examples-build failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9551]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2376/testReport/junit/(root)/objc_macos_opt/objc_examples_build/

**Comment by muxi** [comment]
same nature as #9550

**Comment by makdharma** [comment]
@muxi any idea why this keeps failing? The latest log says that it just timed out. Is the fix as simple as increasing timeout?
