### ISSUE TITLE
cmake: Support Offline Builds (w/o submodules)

### ISSUE THREAD

**Issue by tkohlman** [grpc/grpc#9569]
Consider an application that already has dependencies on zlib and protobuf, which now wants to add gRPC interfaces. It would be nice if the gRPC CMake build would take paths to prebuilt libraries for each of its dependencies (zlib, protobuf, boringssl, etc).

gRPC would be added to the application's build using CMake's ExternalProject_Add, given only an archive containing the source of a gRPC release. Something similar to this:

    set(ARGUMENTS -DCMAKE_BUILD_TYPE=Release
            -DPROTOBUF_LIBRARIES=${DEPENDENCY_DIR}/protobuf/lib
            -DPROTOBUF_INCLUDE_DIR=${DEPENDENCY_DIR}/protobuf/include
            -DZLIB_LIBRARY=${DEPENDENCY_DIR}/zlib/lib/libz.a
            -DZLIB_INCLUDE_DIR=${DEPENDENCY_DIR}/zlib/include)

    ExternalProject_Add(
            grpc
            URL file://${PROJECT_SOURCE_DIR}/offline/grpc-1.1.0-pre1.tar.gz
            URL_HASH SHA1=31c7613f7c53b809d3dce4c663997c1d2fc7c5cd
            PREFIX ${DEPENDENCY_DIR}/grpc
            CMAKE_ARGS ${ARGUMENTS}
    )

This allows repeatable, offline builds that do not require a clone of the repo or the fetching and building of (potentially redundant) submodule dependencies.

The existing CMake build seems to have something along these lines. It contains conditionals that would allow locating dependencies outside of the third_party directory:

    if("${gRPC_ZLIB_PROVIDER}" STREQUAL "module")
      if(NOT ZLIB_ROOT_DIR)
        set(ZLIB_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/third_party/zlib)
      endif()
      set(ZLIB_INCLUDE_DIR "${ZLIB_ROOT_DIR}")
      if(EXISTS "${ZLIB_ROOT_DIR}/CMakeLists.txt")
          add_subdirectory(${ZLIB_ROOT_DIR} third_party/zlib)
          if(TARGET zlibstatic)
              set(_gRPC_ZLIB_LIBRARIES zlibstatic)
          endif()
      else()
          message(WARNING "gRPC_ZLIB_PROVIDER is \"module\" but ZLIB_ROOT_DIR is wrong")
      endif()
    elseif("${gRPC_ZLIB_PROVIDER}" STREQUAL "package")
      find_package(ZLIB)
      if(TARGET ZLIB::ZLIB)
        set(_gRPC_ZLIB_LIBRARIES ZLIB::ZLIB)
      endif()
      set(_gRPC_FIND_ZLIB "if(NOT ZLIB_FOUND)\n  find_package(ZLIB)\nendif()")
    endif()

However, only the module path ever seems to be selected:

    set(gRPC_ZLIB_PROVIDER "module" CACHE STRING "Provider of zlib library")
    set_property(CACHE gRPC_ZLIB_PROVIDER PROPERTY STRINGS "module" "package")

Proposed change:

1. "module" resolution relies on submodule dependencies (current scheme)
2. "package" resolution uses CMake's built-in find_package
3. "manual" resolution allows an external build to explicitly tell gRPC where to find it's dependencies

**Comment by jtattermusch** [comment]
Building gRPC using `ExternalProject_Add` should now be possible without actually needing any submodules.
In https://github.com/grpc/grpc/pull/14822, I am adding a cmake "superbuild" example that demonstrates that (and there's a distribtest that verifies it works). The only difference between the superbuild example and what you are suggesting is the example takes the sources from locally-checked out working copy (but that's mostly for our convenience and making it more maintainable), but it should work equally well when URL, URL_HASH (or GIT_REPO and GIT_TAG) are being specified.
