### ISSUE TITLE
objc "ProtoRPC/ProtoService.h not found" build failure on mac

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9573]
```
/jenkins/workspace/gRPC_pull_requests_macos/workspace_objc_macos_dbg/examples/objective-c/helloworld/Pods/HelloWorld/Helloworld.pbrpc.h:3:9: fatal error: 'ProtoRPC/ProtoService.h' file not found
1 error generated.
```

this caused failures on:
- objc_macos_dbg.objc-examples-build
- objc_macos_opt.objc-examples-build

log in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2422/testReport/junit/(root)/objc_macos_dbg/objc_examples_build/

seen in PR: https://github.com/grpc/grpc/pull/9553 against v1.1.x

**Comment by muxi** [comment]
Processed. Should be solved.
