### ISSUE TITLE
Response-streaming RPCs don't force activity on the wire until the application pulls responses from the response iterator

### ISSUE THREAD

**Issue by bentucker** [grpc/grpc#9581]
Calling a UnaryStreamMultiCallable returns a _Rendezvous object, but the underlying http request is not made until the calling code tries to iterate over the _Rendezvous object. Asynchronous calls appear to only be available for UnaryUnary and StreamUnary endpoints, by using the .future call. Please add some way to run the underlying http request asynchronously.

**Comment by nathanielmanistaatgoogle** [comment]
I think I see what you're describing. Can you tell us more about your use case and how this aspect of gRPC Python is impeding your work?

Efficiency was one of the central forces shaping the design of the gRPC Python API. I think I see a way to add the capability you're describing as an optional add-on that would cost an additional background thread. Any thoughts on that as a cost to your RPCs?

**Comment by bentucker** [comment]
The idea here was to fire off a grpc request, do some processing while waiting for the response, and then have the response available when the processing completes.  The background thread would just be a client thread, right? I don't think that would be very expensive for my use case.

With that being said, my work is not exactly being impeded by the current functionality, and if you'd rather close this issue, that's fine with me :)

**Comment by nathanielmanistaatgoogle** [comment]
Actually, now that I take another look I no longer see how the code could behave as you're describing ([I think activity on the wire is forced on RPC invocation](https://github.com/grpc/grpc/blob/4d0ee2a56b71b3eae4865c6440362daebba0b5f7/src/python/grpcio/grpc/_channel.py#L577)). Are you able to share with us code that demonstrates the problem you're seeing?

**Comment by bentucker** [comment]
Sure, I'll try to put something together this weekend.

**Comment by bentucker** [comment]
I haven't been able to reproduce this behavior, so I'm closing the issue.

**Comment by nathanielmanistaatgoogle** [comment]
Glad to hear it and thanks for the follow-up!

**Comment by bentucker** [comment]
Hi Kailash,

What action is required of me?

Thanks,
Ben

**Comment by nathanielmanistaatgoogle** [comment]
@bentucker: GitHub is lying to you when it says "@hsaliak added the disposition/requires reporter action label on Jun 20". What actually happened at that time was that @hsaliak renamed the "requires reporter clarification" label to "disposition/requires reporter action". There's no action required of you at this time (if there were any action required of anyone, the issue would not be in the closed state).
