### ISSUE TITLE
nodejs: import path resolution

### ISSUE THREAD

**Issue by konsumer** [grpc/grpc#9591]
I am making a Docker image for spinning up a dynamic nodejs-server based on a proto file, and it's not finding things like `google/api/annotations.proto`. If I comment out the import, it works fine. If I download [googleapis](https://github.com/googleapis/googleapis) it resolves it fine, but the include paths get weird after the first import. I have this issue if it's not in Docker, but I thought it might be easiest to reproduce that way.

I'd prefer to not do anything hacky that would mess with protoc (like an empty file or commenting the import, because it is actually being used elsewhere.)

You can download a complete docker project [here](https://gist.github.com/konsumer/bdfc1608f48c4154946705bbb6f5f107)

I get this error:

```
Error: failed to import '/usr/src/app/google/api/google/api/http.proto' in '/usr/src/app/google/api/annotations.proto': file not found
```

Note the repeated directory `google/api`.

Possible fixes for my usecase:

* ability to set include dirs like protoc with `-I`
* proper resolution of paths (which I think will be hard without the includes, but maybe not)
* ability to just ignore annotations import, and inline the [Well Known Types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)

**Comment by pollen8** [comment]
I'm a grpc n00b but try,....
```
  const proto = grpc.load({root: __dirname, file: 'test.proto'});
```

**Comment by konsumer** [comment]
@pollen8 that still doesn't resolve the issue that I can't include my system-wide copy of googleapis, but if I put it in the same dir as __dirname & test.proto, it does work, which is a great workaround, even if it is a bit of a compromise.

Is it not desired for it to work like protoc? For reference, to generate javascript with protoc, I can do this without issue:

```
protoc -I/protobuf -I$(pwd) $(pwd)/test.proto --js_out=import_style=commonjs,binary:generated
```

**Comment by konsumer** [comment]
For now, I can just have a single include dir that has all the google stuff in it, too, and use that as `root`. I guess it's not a huge deal, and it will work in protoc and grpc.

**Comment by pollen8** [comment]
yes, that's what I ended up doing as well.
It looks like in protobuf6 you can do this

```
const protoFile = path.join(__dirname, '/protos/myproto.proto');
const root = new protobuf.Root();

root.resolvePath = function(origin, target) {
    return path/to/protofile
};

protobuf.load(protoFile, root, function(err, root) {
....
})
```

but grpc is currently on protobuf5 and I'm not sure if the grpc.load method will be updated to allow the injection of the root object.

**Comment by konsumer** [comment]
Yeh, we explored some of that [here](https://github.com/dcodeIO/protobuf.js/issues/368). SO maybe the better question is "How can I help upgrade the dependency version of protobuffjs?"

**Comment by konsumer** [comment]
Actually, I spoke too soon. I made a minimal example that better illustrates what I am trying to accomplish [here](https://github.com/konsumer/grpc_issue_9591).

I want to keep my definitions in a namespaced directory, and import them from each other.


When I run it, I get this:

```
> grpc_issue@0.0.1 start /Users/konsumer/Desktop/grpc_issue
> node index.js

/Users/konsumer/Desktop/grpc_issue/node_modules/grpc/src/node/index.js:124
  return loadObject(builder.ns, options);
                           ^

TypeError: Cannot read property 'ns' of null
    at Object.load (/Users/konsumer/Desktop/grpc_issue/node_modules/grpc/src/node/index.js:124:28)
    at Object.<anonymous> (/Users/konsumer/Desktop/grpc_issue/index.js:5:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

Which is grpc's way of saying "couldn't find a proto file" (see #9652)

No probs if I run protoc like this:

```
protoc -I$(pwd)/proto/ $(pwd)/proto/demo/rpc/helloworld.proto --js_out=import_style=commonjs,binary:generated
```

**Comment by murgatroid99** [comment]
Did you try the above suggestion with `{root: 'path/to/proto/', file: 'demo/rpc/helloworld.proto'}`? I think that should be functionally equivalent to that protoc command. Alternatively, you could just use protoc. You can get a copy of protoc that comes with the JavaScript gRPC code generator by installing the npm package `grpc-tools`, and that just requires an extra parameter `--grpc_out=out_path` to get service files for gRPC.

**Comment by konsumer** [comment]
Aha!

In [the example](https://github.com/konsumer/grpc_issue_9591) I had this:

```js
const proto = grpc.load({
  file: resolve(__dirname, 'proto/demo/rpc/helloworld.proto'),
  root: resolve(__dirname, 'proto')
})
```

If I strip off the path for `file`, it actually works fine. Sort of confusing, because it's not exactly equivalent to protoc command (with full path.) So I ended up with this:

```js
const proto = grpc.load({
  file: 'demo/rpc/helloworld.proto',
  root: resolve(__dirname, 'proto')
})
```

**Comment by konsumer** [comment]
@murgatroid99 Re: using protoc, I am trying to make dynamic tools that use the proto files directly, so I can generate a client & server from a minimal server implementation + proto file. I want to not have to keep generated stuff in sync with the proto file, and just use the definition directly.

**Comment by jamezmoran** [comment]
Where did you guys file the documentation for that object you're passing into .load? The official gRPC docs for node.js simply state you can pass an 'Object' in but with no elaboration on the fields that are checked.

**Comment by tomoat** [comment]
This is a very similar problem to #7524

**Comment by murgatroid99** [comment]
The `@grpc/proto-loader` package now supports an `includeDirs` parameter that solves this problem.
