### ISSUE TITLE
GRPC Secure [ C++ ]

### ISSUE THREAD

**Issue by AngryLemonn** [grpc/grpc#9593]
Hi,

I am trying to implement my services under SSL but I am getting this error following the grpc examples:

```
E0206 11:12:41.638275163  9660 ssl_transport_security.c:947] Handshake failed wih fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```

I know that my certs are OK because these certs are working with ZeroC Ice. Using Node.js code as client, the error still appear.

In https://github.com/grpc/grpc/issues/8057 happends the same...

Any idea?

EDIT:

After search a little, this error comes from the mismatch of SSL versions between the client and the server, but both are using the same version of the grpc...

**Comment by tuxagon** [comment]
I actually encountered this exact same error using C# and the documentation is pitiful regarding how gRPC handles authentication with SSL/TLS. It is due to this error, the lack of care from the community/creators and the poor documentation that I am completely abandoning the use of gRPC for the foreseeable future.

**Comment by jcanizales** [comment]
> the lack of care from the community/creators and the poor documentation

Sorry to hear that, Kenneth. Would you share with us specific places in the documentation that could be improved (I'm CC'ing @jboeuf for TLS errors)? And situations in which the community and the authors should have cared more?

**Comment by tuxagon** [comment]
Sure, I can provide several examples
1) [Grpc Auth](http://www.grpc.io/docs/guides/auth.html). This page does not follow standard terminology regarding certificates (like what is "roots.pem", does that mean CA?)? I see nothing regarding client vs server certificate setup (there is only a unhelpful client setup, if you even call that a code example), which, from my experimentation, is required on both sides, not just the client. The code examples are very minimal and what is there wasn't helpful, in my experience. I have never been able to get it working with certificates and nothing on that page provides any help to approaching issues like the one for which this issue is created. In addition, the approach to certificates for Windows seems very non-standard, so it will be harder to get a company to consider it as a viable solution due to the extra maintenance of dealing with certificates vs leveraging the certificate store.

2. Health-checking and production readiness are both articles I would expect (and I understand they might not be written yet), but there is nothing I have seen on either, especially since, for Windows, there seems to be some non-standard ways of things being done.

3. I, and several others, have asked questions via gitter and there is never a reply. The community there is just not active, like at all. Stackoverflow is very hit-or-miss and a lot of times it isn't even someone who knows the tech, they are just guessing. GitHub Issues seem to be the best, but are very quickly disregarded if the assignee doesn't believe you.

I really wanted to like gRPC because of the proto language's basis in protocol buffers, but the authentication with certificates not working put me over the edge where I couldn't trust the technology.

It's for these reasons that I had to abandon gRPC. If I have misunderstood any of this, I would love to be corrected, but nothing I've seen provides anything to contradict my observations.

**Comment by jboeuf** [comment]
@AngryLemonn can you please confirm that you are using gRPC node both on the client and on the server. Assuming that this is the case, can you please share the code that you're using to create the channel on the client side and the secure port on the server side (bind call)?

**Comment by AngryLemonn** [comment]
Sorry, I could not reply until now,

The problem was solved, I made a mistake with my C++ server implementation... The solution was make again the server, following the SSL examples under other languages...

Sorry again...

**Comment by jcanizales** [comment]
Thanks for the specifics Kenneth. I'll be forwarding that to the relevant folks for each piece.

**Comment by jboeuf** [comment]
@AngryLemonn thanks for the feedback. Can you please explain the mistake that made so that it could be more useful to the community? It could be that the SSL message is a bit misleading and that we could improve the content of the logs to guide our users in the right direction.

**Comment by AngryLemonn** [comment]
These are my own greeter examples in C++ working under SSL:

greeter_secure_server.cc
```
#include <memory>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <grpc++/grpc++.h>

#include "helloworld.grpc.pb.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

using helloworld::HelloRequest;
using helloworld::HelloReply;
using helloworld::Greeter;

class GreeterServiceImpl final : public Greeter::Service
{
	Status SayHello ( ServerContext* context,
                      const HelloRequest* request,
                      HelloReply* reply ) override
	{
		std::string prefix ( "Hello " );

		reply->set_message ( prefix + request->name () );

		return Status::OK;
	}
};

void
read ( const std::string& filename, std::string& data )
{
        std::ifstream file ( filename.c_str (), std::ios::in );

	if ( file.is_open () )
	{
		std::stringstream ss;
		ss << file.rdbuf ();

		file.close ();

		data = ss.str ();
	}

	return;
}


void
runServer()
{
	/**
	 * [!] Be carefull here using one cert with the CN =! localhost. [!]
	 **/
	std::string server_address ( "localhost:50051" );

	std::string key;
	std::string cert;
	std::string root;

	read ( "server.crt", cert );
	read ( "server.key", key );
	read ( "ca.crt", root );

	ServerBuilder builder;

	grpc::SslServerCredentialsOptions::PemKeyCertPair keycert =
	{
		key,
		cert
	};

	grpc::SslServerCredentialsOptions sslOps;
	sslOps.pem_root_certs = root;
	sslOps.pem_key_cert_pairs.push_back ( keycert );

	builder.AddListeningPort(server_address, grpc::SslServerCredentials( sslOps ));

	GreeterServiceImpl service;
	builder.RegisterService(&service);

	std::unique_ptr < Server > server ( builder.BuildAndStart () );
	std::cout << "Server listening on " << server_address << std::endl;

	server->Wait ();
}

int
main ( int argc, char** argv )
{
	runServer();

	return 0;
}
```

greeter_secure_client.cc
```
#include <memory>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <grpc++/grpc++.h>

#include "helloworld.grpc.pb.h"

using grpc::Channel;
using grpc::ClientContext;
using grpc::Status;

using helloworld::HelloRequest;
using helloworld::HelloReply;
using helloworld::Greeter;

class GreeterClient
{
public:
  	GreeterClient ( const std::string& cert,
	                const std::string& key,
                        const std::string& root,
                        const std::string& server )
	{
		grpc::SslCredentialsOptions opts =
		{
			root,
			key,
			cert
		};

		stub_ = Greeter::NewStub ( grpc::CreateChannel (
			server, grpc::SslCredentials ( opts ) ) );
	}

  	std::string
	SayHello ( const std::string& user )
	{
		HelloRequest request;
		request.set_name(user);

		HelloReply reply;

		ClientContext context;

		Status status = stub_->SayHello ( &context, request, &reply );

		if ( status.ok () )
		{
			return reply.message ();
		}
		else
		{
			std::cout << status.error_code () << ": "
			          << status.error_message () << std::endl;
			return "RPC failed";
		}
  	}

private:
  	std::unique_ptr<Greeter::Stub> stub_;
};

void
read ( const std::string& filename, std::string& data )
{
	std::ifstream file ( filename.c_str (), std::ios::in );

	if ( file.is_open () )
	{
		std::stringstream ss;
		ss << file.rdbuf ();

		file.close ();

		data = ss.str ();
	}

	return;
}

int
main ( int argc, char** argv )
{
	std::string cert;
	std::string key;
	std::string root;
	std::string server { "localhost:50051" };

	read ( "client.crt", cert );
	read ( "client.key", key );
	read ( "ca.crt", root );

  	GreeterClient greeter ( cert, key, root, server );

	std::string user ( "world" );
  	std::string reply = greeter.SayHello ( user );

  	std::cout << "Greeter received: " << reply << std::endl;

  	return 0;
}
```

gen-certs.sh
```
#!/bin/bash

# Generate valid CA
openssl genrsa -passout pass:1234 -des3 -out ca.key 4096
openssl req -passin pass:1234 -new -x509 -days 365 -key ca.key -out ca.crt -subj  "/C=SP/ST=Spain/L=Valdepenias/O=Test/OU=Test/CN=Root CA"

# Generate valid Server Key/Cert
openssl genrsa -passout pass:1234 -des3 -out server.key 4096
openssl req -passin pass:1234 -new -key server.key -out server.csr -subj  "/C=SP/ST=Spain/L=Valdepenias/O=Test/OU=Server/CN=localhost"
openssl x509 -req -passin pass:1234 -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt

# Remove passphrase from the Server Key
openssl rsa -passin pass:1234 -in server.key -out server.key

# Generate valid Client Key/Cert
openssl genrsa -passout pass:1234 -des3 -out client.key 4096
openssl req -passin pass:1234 -new -key client.key -out client.csr -subj  "/C=SP/ST=Spain/L=Valdepenias/O=Test/OU=Client/CN=localhost"
openssl x509 -passin pass:1111 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt

# Remove passphrase from Client Key
openssl rsa -passin pass:1234 -in client.key -out client.key
```

The problems that I had securing with SSL comes from mix secure and insecure client/server (SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER) and from the bad use certifies for grpc (SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED), certifies that works with other libs (ZeroC Ice for example). 

The _**gen-certs.sh**_ script generates valid certifiers. Be carefull changin the OU and CN from the subject. I recommend not use IP addresses in CN because I got some error doing that, is better use hostnames like localhost. Use or set names to the IP that you want to use in /etc/hosts.

Regards,
J. A

**Comment by jboeuf** [comment]
OK thanks much. So it looks like the WRONG_VERSION_NUMBER is symptomatic of
an SSL client talking to a plain text server or vice-versa. I'll see if I
can catch this error and change the error log so that it says something
like: "Please make sure that the peer is also an SSL endpoint.".

Cheers,

     Julien.

**Comment by patricia93sousa** [comment]
@AngryLemonn  your example works for a true CA?

**Comment by AngryLemonn** [comment]
I don't know what you mean with a "_true CA_", but with certificates signed by a CA created with OpenSSL, it works. 

This examples was made for the Grpc version 1.1. I tested the examples again with the currently master branch and still works. Can you be more specific with your problem?

**Comment by patricia93sousa** [comment]
@AngryLemonn , first let'm say thanks for the fast reply.
What I mean by a true CA is a CA that is not in the localhost(a self-signed CA).

**Comment by AngryLemonn** [comment]
@patricia93sousa,

In this case, I don't know if Grpc allow you to use a remote file as CA. The documentation say this:

> **grpc::SslCredentialsOptions::pem_root_certs**
> The buffer containing the PEM encoding of the server root certificates.
> If this parameter is empty, the default roots will be used. The default roots can be overridden using the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH environment variable pointing to a file on the file system containing the roots.

If is your client who doesn't have access to the root CA, you should try connect to the server whitout this file. The client certificates must be signed with the server CA, and the handsake should not cause problems. Maybe the client will say you that can not connect with an untrusted server, and this is because Grpc will use the default roots and your root CA is not there...Sorry if this doesn't help you a lot, but I don't have had to deal with this problem yet...

If you need to connect to a remote server, the common name (CN) of the client and server certificates must have the server's name (ex: www.github.com). In Linux, Grpc will checks this name in the **/etc/hosts**, and will use the associated IP to connect the client with the server. In Windows and Mac, I don't know how this works, sorry...

Regards,
J. A.

**Comment by sihussain2** [comment]
I have tried the solution mentioned by AngryLemon, but i get this error. 
./greeter_secure_server
E1220 00:01:46.818535379   31190 ssl_transport_security.cc:621] Invalid cert chain file.
E1220 00:01:46.818590151   31190 security_connector.cc:1108] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1220 00:01:46.818608706   31190 server_secure_chttp2.cc:83] {"created":"@1513746106.818598472","description":"Unable to create secure server with credentials of type Ssl.","file":"src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc","file_line":62,"security_status":1}
Server listening on localhost:50051
Segmentation fault (core dumped)

Basicaly, i am trying to implement grpc with TLS support. When i run the server, it gives the above error. The client hasnt even started yet. Any help would be deeply appreciated. I have everything, but couldnt resolve the problem.

**Comment by muxi** [comment]
Is the issue above still active?

**Comment by sihussain2** [comment]
Hi. No. It is resolved. Thanks

**Comment by muxi** [comment]
Cool thanks!

**Comment by rahul217** [comment]
@sihussain2, I am facing the same error for Invalid cert chain file.
How did you resolve it? Do you mind letting us know?
Thanks!

**Comment by sihussain2** [comment]
Sorry for the late reply. I actually did couple of things. Not sure which
one actually solved the problem
 1. cn name in the generate certificate.
2. Override of the server name in the client code.  Although this is
specific to my setup due to proxy settings
3. Just double check the certificate creation technique. It's tricky to get
it right

On Mar 27, 2018 12:47 PM, "rahul217" <notifications@github.com> wrote:

@sihussain2 <https://github.com/sihussain2>, I am facing the same error for
Invalid cert chain file.
How did you resolve it? Do you mind letting us know?
Thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/grpc/grpc/issues/9593#issuecomment-376594949>, or mute
the thread

**Comment by pcj** [comment]
This ended up working for me to connect to a public grpc endpoint :443

First, bundle up all the system certs into a single `roots.pem` file:

```python
genrule(
    name = "roots_pem",
    outs = ["roots.pem"],
    cmd = " && ".join([
        "OUT=$$(pwd)/$@",
        "TMP=$$(mktemp -d $${TMPDIR:-/tmp}/genrule.XXXXXXXXXX)",
        "cd $$TMP",
        "cat /etc/ssl/certs/*.pem > $$OUT",
        "rm -rf $$TMP",
    ]),
    executable = True,
)
```

Next, assign the name of that file to this magic environment variable:

```
export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=./bazel-genfiles/client/cpp/roots.pem
```

Lastly, invoke the client:

```c++
  auto options = grpc::SslCredentialsOptions();
  auto creds = grpc::SslCredentials(options);
  auto channel = grpc::CreateChannel("fortune.stack.build:443", creds);
  std::unique_ptr<FortuneTeller::Stub> stub(FortuneTeller::NewStub(channel));
  FortuneTellerClient FortuneTeller(channel);
  std::string reply = FortuneTeller.Predict();
  std::cout << "FortuneTeller received: " << reply << std::endl;
```

```
$ ./bazel-bin/client/cpp/fortune
FortuneTeller received: All generalizations are false, including this one.
```

This example assumes that fortune.stack.build is first hitting a load balancer or something that can terminate TLS and forward the request to an internal gRPC server implementation running in insecure mode.
