### ISSUE TITLE
Version 1.1.0 is not on RubyGems.org

### ISSUE THREAD

**Issue by palkan** [grpc/grpc#9594]
Version 1.1.0 has been released a few days ago, but it hasn't been push to [rubygems.org](https://rubygems.org/gems/grpc) yet. Could you, please, do that?
Thanx

**Comment by apolcyn** [comment]
Unfortunately Version 1.1.0 has been released for other languages but the grpc-ruby 1.1.0 release is still in progress. It isn't ready yet but it will be uploaded once it is.

**Comment by apolcyn** [comment]
The 1.1.2 release was just published. This replaces the would -be 1.1.0 and 1.1.1 versions
