### ISSUE TITLE
FAILED: vsprojects/Debug/h2_ssl_proxy_test.exe invoke_large_request

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9620]
Failed in https://grpc-testing.appspot.com/job/gRPC_pr_win/2485/consoleFull
```
E0207 07:13:37.078000000 16124 invoke_large_request.c:246] assertion failed: status == GRPC_STATUS_UNIMPLEMENTED
```

**Comment by dgquintas** [comment]
Seen also for `streaming_error_response`: https://grpc-testing.appspot.com/job/gRPC_pr_win/2656/testReport/junit/(root)/c_windows_dbg/vsprojects_Debug_h2_ssl_proxy_test_exe_streaming_error_response/

**Comment by makdharma** [comment]
Seen again on #11224
