### ISSUE TITLE
Core stack should support ECDHE-ECDSA cipher suite

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc#9630]
Currently the stack only supports RSA based cipher suites. Problem reported in #8057.

**Comment by mandelmonkey** [comment]
is there a plan to support the ECDHE-ECDSA cipher suite in the future?

**Comment by jboeuf** [comment]
There's a ongoing PR for this: https://github.com/grpc/grpc/pull/11699

**Comment by jiangtaoli2016** [comment]
#15404 merged. We can close this one.
