### ISSUE TITLE
Add error handler with meaningful error message on grpc.load

### ISSUE THREAD

**Issue by piotrwitek** [grpc/grpc#9652]
grpc for node, v1.1.2
Add error handler with meaningful error message on grpc.load method

Current behaviour:
when path to proto file is wrong program breaks with following exception: `TypeError: Cannot read property 'ns' of null`
This error message does not help to figure out what went wrong.
Related issue: https://github.com/grpc/grpc/issues/7524

Expected behaviour: 
check if proto file exist, if not then throw exception with meaningful error like:
 `Error: ENOENT: no such file or directory, open '/Users/piotrek/.../service.proto'`

**Comment by murgatroid99** [comment]
This has been fixed by grpc/grpc-node#228.
