### ISSUE TITLE
Jenkins skips other tests when yapf_code.sh fails

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9657]
When yapf_code.sh test fails, Jenkins stops running all Linux tests and the rest of sanity checks. Not sure if it is supposed to happen or not, but it made some test failures missed.

For an example, see https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2535/console

cc: @makdharma @dgquintas @nicolasnoble

**Comment by dgquintas** [comment]
Ah, nice catch! We should definitely fix that. I'll try to have a go at it later today.

**Comment by dgquintas** [comment]
Actually, after discussing offline, this was a red herring: other sanity checks are _not_ skipped. Closing.
