### ISSUE TITLE
grpc needs to upgrade python protobuf package

### ISSUE THREAD

**Issue by sahlberg** [grpc/grpc#966]
protobuf-3.0.0-alpha-1.tar.gz is too old and is not compatible with the new version of
protoc or the python examples in grpc-common.

I downloaded and installed compiler and runtime from master at https://github.com/google/protobuf
This compiler generates 'syntax=...' in the calls to the Descriptor constructors since the example contain this in the proto file.

For example:
DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='',
  syntax='proto2',

But in the grpc repo when you run tools/run_tests/build_python.sh it downloads and installs
protobuf-3.0.0_alpha_1-py2.7.egg-info
in the virtual environment.

That version has an older runtime that does not have the syntax argument to the [File]Descriptor constructors.

Thus the python helloworld example only works as long as you do not regenerate helloworld_pb2.py

If you regenerate the code  using
./rpc_codegen.sh 
then the examples will not work.

This is the error:

./run_client.sh 
Traceback (most recent call last):
  File "greeter_client.py", line 32, in <module>
    import helloworld_pb2
  File "/data/sahlberg/grpc-common/python/helloworld/helloworld_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x10helloworld.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t23\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by sahlberg** [comment]
I replaced the protobuf module in the virtual environment that tools/run_tests/build_python.sh creates with the python protobuf module from master (88eda4d7760e43 at the time) of https://github.com/google/protobuf.git
and that seems to work.

So as far as I can tell, I think we only need a new version of 
protobuf-3.0.0-alpha-?.tar.gz and use that instead from tools/run_tests/build_python.sh then all should be fine.

**Comment by nathanielmanistaatgoogle** [comment]
I don't know that I'll be able to act on this in the next few days but thanks for digging into this. :-)

**Comment by sahlberg** [comment]
No worries, and no hurry.

I think this cause my unrelated pull request to fail travis:
https://github.com/grpc/grpc/pull/977

**Comment by nicolasnoble** [comment]
No; your pull request is trying to update grpc's protobuf library. Which is why we haven't yet, it needs to happens both at the same time :-)

**Comment by nathanielmanistaatgoogle** [comment]
(This is an earlier report of what is going on in #1455.)

**Comment by soltanmm** [comment]
I believe this was addressed a while back. Feel free to re-open if there're still problems.
