### ISSUE TITLE
Deleting a channel attempts to free an active critical section

### ISSUE THREAD

**Issue by napcode** [grpc/grpc#9671]
According to the MS Application Verifier, at least grpc 1.0.1 on Windows 10 x86 frees an active critical section in the following minimal example:
```
#include <grpc++/grpc++.h>

int main(int argc, char* argv[]) {
    std::shared_ptr<::grpc::Channel> grpcChannel = ::grpc::CreateChannel("127.0.0.1:500", grpc::InsecureChannelCredentials());
    return 0;
}

```
```

grpcbug_d.exe!grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() Line 65	C++
[External Code]	
grpcbug_d.exe!grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() Line 65	C++
grpcbug_d.exe!grpc::Channel::~Channel() Line 62	C++
[External Code]	
grpcbug_d.exe!main(int argc, char * * argv) Line 20	C++
[External Code]	
```

```

=======================================
VERIFIER STOP 00000202: pid 0xB1AC: Freeing heap block containing an active critical section. 

	0BB24FD4 : Critical section address. Run !cs -s <address> to get more information.
	04FD2514 : Critical section initialization stack trace. Run dps <address> to dump the stack trace.
	0BB24FA8 : Heap block address.
	00000058 : Heap block size.

 =======================================
```

This problem is most likely causing a crash I'm seeing in my larger application. Maybe it is also connected to [this one](https://github.com/grpc/grpc/issues/9670).

**Comment by yang-g** [comment]
I created the same test (under both head and 1.0.1) and run it with asan and normal builds under linux. It does not to fail in anyway.

I am closing it for now considering the age of 1.0.1. But feel free to reopen if you still see this issue.

**Comment by napcode** [comment]
The problem was only reported on Windows and App Verifier. Linux and asan did not show this.
