### ISSUE TITLE
gRPC_portability_pull_requests_linux borked

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#9689]
It's failed for me in the same weird way twice this morning: [2731](https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/2731) and [2732](https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/2732).

**Comment by matt-kwong** [comment]
This was the unfortunate result of the Jenkins meltdown yesterday morning. Rebuilding will cause the same failure; it seems like all tests have to be rebuilt from scratch in PR comments.
