### ISSUE TITLE
Multiple Python protoc plug-in tests are flakily failing/hanging indefinitely

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#969]
In `test/compiler/python_plugin_test.py`, tests that used to pass consistently have been failing/hanging flakily some time after we moved to GitHub. The ones currently marked `skip` are:

- [ ] `testUnaryCallAsyncCancelled`
- [ ] `testStreamingOutputCallExpired`
- [ ] `testStreamingOutputCallCancelled`
- [ ] `testStreamingOutputCallFailed`
- [ ] `testStreamingInputCall`
- [ ] `testFullDuplexCallExpired`
- [ ] `testFullDuplexCallCancelled`
- [ ] `testFullDuplexCallFailed`
- [ ] `testHalfDuplexCall`

Details for each test are provided in their skip messages (in code). Note that most of these are hangs post-error-handling.

At least one of the tests flakily results in a strange low-level POSIX mutex assertion failing (which is baffling given that we're up at the level of Python). I've been unable to duplicate the failure.

cc @nathanielmanistaatgoogle

**Comment by ctiller** [comment]
If these are reproducible, we should try to fix them. Step one would be re-enabling the tests?

**Comment by soltanmm** [comment]
(note that these tests are all still based on the alpha API)

**Comment by soltanmm** [comment]
The beta API's equivalent tests appear to be passing just fine. Closing as fixed against beta and won't-fix against alpha.
