### ISSUE TITLE
Improve coveralls tool for use with scripting languages

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#970]
The `coveralls` command line tool has some flaws that prevent us from using it with wrapped languages:

 - Sends useless information for paths not relative to repository root
 - Does not correctly check file existence
 - Can not merge other coverage reports
 - Does not support multiple base paths

**Comment by murgatroid99** [comment]
Since we're trying to use Jenkins instead of Travis, does Jenkins have a plugin to handle coverage information? If so, we can avoid having to do this.

**Comment by nicolasnoble** [comment]
Unfortunately, that's going to be the same thing :-)

**Comment by soltanmm** [comment]
We've stopped using coveralls, right?

**Comment by nicolasnoble** [comment]
Yes.
