### ISSUE TITLE
chttp2_transport.c:527]     client stream 1 still included in list 9 (Core)

### ISSUE THREAD

**Issue by dekumar23** [grpc/grpc#9701]
I am seeing client side grpc crash due to follow function (using grpc 1.0.0 - cpp based)

17483 chttp2_transport.c:527]     client stream 1 still included in list 9
23334 chttp2_transport.c:527]     client stream 1 still included in list 9
24814 chttp2_transport.c:527]     client stream 1 still included in list 9
26001 chttp2_transport.c:527]     client stream 1 still included in list 9
26995 chttp2_transport.c:527]     client stream 507 still included in list 9

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce.
