### ISSUE TITLE
Cleanup remaining references to Node.js 0.12

### ISSUE THREAD

**Issue by jcking** [grpc/grpc#9707]
Suppport for Node.js 0.12 has been dropped. However a few files in the repository, including the README, still mentioned Node.js 0.12. We should update these files. To clarify, is the minimum version supported Node.js 4? Basically are we ignoring io.js 1, 2, and 3? Once the new minimum is clarified I will go about updating the references and documentation.

**Comment by murgatroid99** [comment]
If you look at the package.json, you can see that the lowest version we currently support is io.js 1.1. I don't actually know if io.js is still maintained, but we have not yet had a reason to drop support for it.

**Comment by jcking** [comment]
io.js is no longer maintained as it was merged back into Node.js in version 4, which is why I asked. I'll re-write it according to package.json dependencies.
