### ISSUE TITLE
:grpc++_unsecure doesn't build

### ISSUE THREAD

**Issue by jhseu** [grpc/grpc#9714]
We've been using custom BUILD files in TensorFlow to fix the gRPC BUILD file because this target doesn't build.

To reproduce, add the following to `grpc/BUILD`:
```
cc_binary(
    name = "foo.so",
    srcs = [],
    deps = [":grpc++_unsecure"],
    linkshared = 1,
)
```

Then run `bazel build foo.so`. It happens for shared libraries (but not binaries) because it requires that all symbol conflicts are resolved. Basically the issue is that certain .cc files are included multiple times.

To see the example of the workarounds we do for TensorFlow, see the commented out srcs and deps from:
https://github.com/llhe/tensorflow/blob/24c5907b3d1c012773912d6381c185a10bf93bc9/third_party/grpc.BUILD

@llhe @ctiller fyi

**Comment by jhseu** [comment]
Friendly ping. Hopefully a fix can make it into the next release. This is an inconvenience on our side, and makes the target unusable for most, but is an easy fix for gRPC.

**Comment by vjpai** [comment]
Looking at this now; the plan is to fix up the build file as indicated above and add at least 1 test that depends on this target to make sure that the binary works properly.

**Comment by jhseu** [comment]
Thanks!
