### ISSUE TITLE
Limit thread count of the sync server thread pool

### ISSUE THREAD

**Issue by 0x1997** [grpc/grpc#9716]
gRPC currently uses a [dynamic_thread_pool](https://github.com/grpc/grpc/blob/master/src/cpp/server/dynamic_thread_pool.h) for the sync server. But the thread count will increase without bound under load. There was once a [fixed_size_thread_pool]() implementation in the repo but it was removed in fd307efbd121f994ded0450ffe2a38e38d4e9130.
What's the reason behind this decision? What am I missing here? Thanks.

**Comment by vjpai** [comment]
So the reason for this is that fixed-size thread pool without any rejection can deadlock (I documented a related problem in ruby in #8604 ). The thread count does indeed increase with load, though it will decrease again when load is relieved. Version 1.1 does things a little differently, though it also is not a fixed-size thread pool.

**Comment by 0x1997** [comment]
@vjpai I see, thanks. I think some simple way to apply backpressure downstream instead of creating more threads would be nice to have if users can make sure there are no cyclic dependencies between services. For example, a `max_threads` option can be added to [ThreadManager](https://github.com/grpc/grpc/blob/master/src/cpp/thread_manager/thread_manager.h) so it can stop creating new poller threads when `num_threads_` exceeds the limit? Will the completion queues continue to grow without bound?

**Comment by ctiller** [comment]
The correct place for such an API going forward is in ResourceQuota. I've
had vague ideas around tracking thread stack size against the memory
limits: it opens up some interesting implementation options, especially for
phased workloads.

**Comment by tjb1216** [comment]
I have tested on sync server, the number of threads rose sharply, could be more than 4000, it's horrible for a online server when each thread hold some instance.

**Comment by sreecha** [comment]
There was a bug in sync server that we recently fixed https://github.com/grpc/grpc/pull/12139 . With that fix, you shouldn't have seen 4000 threads. Can you please double check with the latest head ?

**Comment by tjb1216** [comment]
Yes, it's does, will it release at 1.6?

**Comment by sreecha** [comment]
Yep, the fix is in 1.6 release

**Comment by tjb1216** [comment]
OK, Thanks!
