### ISSUE TITLE
GRPC Cross Compilation [ARM]

### ISSUE THREAD

**Issue by AngryLemonn** [grpc/grpc#9719]
Hi,

I am trying to execute one sync server under ARM. For do this, I compiled GRPC for ARM following these steps:

```
# Protobuf installation [ HOST ]
cd grpc/third-party/protobuf
./autogen.sh
./configure
make && make check && sudo make install && sudo ldconfig

# Grpc installation [ HOST ]
cd grpc
make && sudo make install && sudo ldconfig

# Grpc compile for ARM-XILINX (Clean build)
cd grpc
make plugins

export GRPC_CROSS_COMPILE=true
export GRPC_CROSS_AROPTS="cr --target=elf32-little"

make HAS_PKG_CONFIG=false \
    CC=arm-xilinx-linux-gnueabi-gcc \
    CXX=arm-xilinx-linux-gnueabi-g++ \
    RANLIB=arm-xilinx-linux-gnueabi-ranlib \
    LD=arm-xilinx-linux-gnueabi-ld \
    LDXX=arm-xilinx-linux-gnueabi-g++ \
    AR=arm-xilinx-linux-gnueabi-ar \
    PROTOBUF_CONFIG_OPTS="--host=arm-xilinx-linux-gnueabi --with-protoc=/usr/local/bin/protoc"
```

**Problems:**
1. Doing this, the make instruction for cross compilation fails during the shared part of the compilation. _**Solution**_: Remove -Wl from arm-xilinx-linux-gnueabi-ld commands, because arm-xilinx-linux-gnueabi-ld not recognize -Wl option.
2. For only compile the Grpc lib as static, I put static at the end of the cross make. Doing this, all work fine. The server build was ok and runs under ARM XILINX. The problem here happends when I call this server from my host client. The server crash with segmentation fault before serve the client request. Debugging this, the segmentation fault comes from the reception of the request, before enter in the function requested from the client. These server and client are the helloworld sync examples, with the different that the server was compiled for ARM and the client for my HOST. I think that the segmentation comes from the grpc core...
3. Trying to use the shared libraries, the compilation of the server was ok but didn't work on ARM. The last error message that I can't solve was: 

```
"./greeter_server: error while loading shared libraries: read: cannot open shared object file: No such file or directory".
```

 I know that the problem comes from shared library missing, but "read" lib??? what library is "read"??

**Questions:**
1. Someone can compile and run grpc examples using cross compilation?
2. Why the documentation of the Grpc cross compilation is only the Makefile?

**EDIT1:**
This is the segmentation call stack in the case of compile with Grpc libs as static. This segmentation violation comes from the helloword server when the client request SayHello...

```
Siganl: Segmentation Violation.

0x36cb1018 [libstdc++.so.6.0.19] _ZNSsC1ERKSs()
0x0006572c [greeter_server] Status (): status.h, line 45
0x000a1370 [greeter_server] Deserialize(): proto_utils.h, line 210
0x0009bf34 [greeter_server] RunHandler(): method_handler_impl.h, line 56
0x00110160 [greeter_server] DoWork(): src/cpp/server/server_cc.cc, line 212
0x001126b0 [greeter_server] MainWorkLoop(): ...thread_manager/thread_manager.cc, line 172
0x0011270c [greeter_server] Run(): ...thread_manager/thread_manager.cc, line 48
0x00112808 [greeter_server] _M_run(): functional, line 601
0x36ca7b90 [libstdc++.so.6.0.19]
0x36f99060 [libpthread-2.18.so]
0x36ca7b90 [libstdc++.so.6.0.19]
0x00000000
```

**EDIT2:**
Searching a little with the debbuger, I found that the segmentation fault comes from the file _grpc/include/grpc++/impl/codegen/proto_utils.h_:

```
static Status Serialize(const grpc::protobuf::Message& msg,
                          grpc_byte_buffer** bp, bool* own_buffer) {
    *own_buffer = true;
    int byte_size = msg.ByteSize();
    if (byte_size <= internal::kGrpcBufferWriterMaxBufferLength) {
      grpc_slice slice = g_core_codegen_interface->grpc_slice_malloc(byte_size);
      GPR_CODEGEN_ASSERT(
          GRPC_SLICE_END_PTR(slice) ==
          msg.SerializeWithCachedSizesToArray(GRPC_SLICE_START_PTR(slice)));
      *bp = g_core_codegen_interface->grpc_raw_byte_buffer_create(&slice, 1);
      g_core_codegen_interface->grpc_slice_unref(slice);

      return g_core_codegen_interface->ok();
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    } else {
      internal::GrpcBufferWriter writer(
          bp, internal::kGrpcBufferWriterMaxBufferLength);
      return msg.SerializeToZeroCopyStream(&writer)
                 ? g_core_codegen_interface->ok()
                 : Status(StatusCode::INTERNAL, "Failed to serialize message");
    }
  }

static Status Deserialize(grpc_byte_buffer* buffer,
                            grpc::protobuf::Message* msg) {
    if (buffer == nullptr) {
      return Status(StatusCode::INTERNAL, "No payload");
    }

    Status result = g_core_codegen_interface->ok();
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    {
      internal::GrpcBufferReader reader(buffer);
      if (!reader.status().ok()) {
        return reader.status();
      }
      ::grpc::protobuf::io::CodedInputStream decoder(&reader);
      decoder.SetTotalBytesLimit(INT_MAX, INT_MAX);
      if (!msg->ParseFromCodedStream(&decoder)) {
        result = Status(StatusCode::INTERNAL, msg->InitializationErrorString());
      }
      if (!decoder.ConsumedEntireMessage()) {
        result = Status(StatusCode::INTERNAL, "Did not read entire message");
      }
    }
    g_core_codegen_interface->grpc_byte_buffer_destroy(buffer);
    return result;
  }
};
```

At lines where **g_core_codegen_interface->ok()** is used, the server crash. Any idea??

**EDIT3: SOLUTION**

Grpc cross compilation as **_static_** and helloworld examples with **_-static_** flag at compilation time. All is working now, sorry :P 

Regards,
J. A.

**Comment by vish74** [comment]
@AngryLemonn Are you able to generate "libgrpc++.a" file? cause I am following the steps and getting few errors like these,
`/usr/bin/ld: /home/grpc/objs/opt/src/compiler/cpp_plugin.o: Relocations in generic ELF (EM: 40)`
`/home/grpc/objs/opt/src/compiler/cpp_plugin.o: error adding symbols: File in wrong format`

(mentioned here as well,  https://github.com/grpc/grpc/issues/6756)

Also, can you share your Makefile or gRPC release version you are trying? Thanks.

**Comment by AngryLemonn** [comment]
The release that I used was the 1.1.0.

I think that your error comes from use **/usr/bin/ld** to link objects that were compilated to ARM. To link these objects, you need to use the ARM linkers ( **LD=arm-xilinx-linux-gnueabi-ld** and **LDXX=arm-xilinx-linux-gnueabi-g++** ). If your make command have these params and still not working, the problem maybe comes from this:

```
export GRPC_CROSS_COMPILATION=true
export GRPC_CROSS_AROPTS="cr --target=elf32-little"
```

If **GRPC_CROSS_COMPILATION** is set, the makefile use the command parammeters to compile and link grpc. If not, the default compiler and linker is used.

The steps that I finally followed were this:
* Compile and install protobuf.
```
cd grpc
git submodule update --init
cd third_party/protobuf
./autogen.sh
./configure
make && make check && sudo make install && sudo ldconfig
```
* Compile and install grpc.
```
cd -
make && sudo make install && sudo ldconfig
```
* Clean the current build.
```
make clean
```
* Make grpc plugins.
```
make plugins
```
* Set environment variables for cross compilation.
```
export GRPC_CROSS_COMPILATION=true
export GRPC_CROSS_AROPTS="cr --target=elf32-little"
```
* Compile grpc as static with this command:

```
make HAS_PKG_CONFIG=false \
    CC=arm-xilinx-linux-gnueabi-gcc \
    CXX=arm-xilinx-linux-gnueabi-g++ \
    RANLIB=arm-xilinx-linux-gnueabi-ranlib \
    LD=arm-xilinx-linux-gnueabi-ld \
    LDXX=arm-xilinx-linux-gnueabi-g++ \
    AR=arm-xilinx-linux-gnueabi-ar \
    PROTOBUF_CONFIG_OPTS="--host=arm-xilinx-linux-gnueabi --with-protoc=/usr/local/bin/protoc" static
```

I hope this help you a little :)

Regards,
J. A.

**Comment by vish74** [comment]
@AngryLemonn , thanks for the quick reply.
So I tried the same steps, and all env variables are set properly. 
I am trying this on debian, with "arm-linux-gnueabi" toolchain. And not sure why I am getting this error, 

`[AR]      Creating /home/grpc/libs/opt/libgpr.a
arm-linux-gnueabi-ar: invalid option -- '/'
`
I saw that error previously, and I unset that env variable and it compiled fine. It builds protobuf properly and I can test it too. But still not able to compile "libgrpc++.a" due to those same linker errors. Next I can try using same xilinx toolchain too.

**Comment by AngryLemonn** [comment]
Use GRPC_CROSS_COMPILE=true instead of GRPC_CROSS_COMPILATION=true and try again, I took a mistake copying the environment variables.... Sorry.

**Comment by vish74** [comment]
@AngryLemonn It worked, I could compile it without any error. (except protobuf version conflict for one file, but no big issue there.)

Thanks a lot. :)

**Comment by vish74** [comment]
@AngryLemonn I am trying to build example code with same toolchain and gRPC static libs (using -static flag), and I think I am missing some parameters. I am getting these errors, which I believe some linking errors only.

Can you share your make steps for building any of the example code? Thanks.

`/home/grpc/libs/opt/libgrpc++_cronet.a(resolve_address_posix.o): In function `blocking_resolve_address_impl':
/home/grpc/src/core/lib/iomgr/resolve_address_posix.c:96: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/grpc/libs/opt/libgrpc++_cronet.a(message_compress.o): In function `zlib_compress':
/home/grpc/src/core/lib/compression/message_compress.c:112: undefined reference to `deflateInit2_'
/home/grpc/src/core/lib/compression/message_compress.c:124: undefined reference to `deflateEnd'
/home/grpc/src/core/lib/compression/message_compress.c:126: undefined reference to `deflate'
/home/grpc/libs/opt/libgrpc++_cronet.a(message_compress.o): In function `zlib_decompress':
/home/grpc/src/core/lib/compression/message_compress.c:138: undefined reference to `inflateInit2_'
/home/grpc/src/core/lib/compression/message_compress.c:148: undefined reference to `inflateEnd'
/home/grpc/src/core/lib/compression/message_compress.c:150: undefined reference to `inflate'
collect2: error: ld returned 1 exit status`

**Comment by AngryLemonn** [comment]
According to "**error: ld returned 1 exit status**", I think you still using the default linker to link ARM objects. Can you show me your makefile?

**Comment by vish74** [comment]
@AngryLemonn In my Makefile these are variables,

CPPFLAGS = -I/usr/local/include -pthread
CXXFLAGS = -std=gnu++11
CROSS_TRIPLE=arm-linux-gnueabi
CROSS_ROOT=/usr/bin
AS=/usr/bin/${CROSS_TRIPLE}-as
AR=/usr/bin/${CROSS_TRIPLE}-ar
CC=/usr/bin/${CROSS_TRIPLE}-gcc
CPP=/usr/bin/${CROSS_TRIPLE}-cpp
CXX=/usr/bin/${CROSS_TRIPLE}-g++
LD=/usr/bin/${CROSS_TRIPLE}-ld
LDXX =/usr/bin/${CROSS_TRIPLE}-g++

And with LDFLAGS, it is calling like this as I am statically linking.

arm-linux-gnueabi-g++ -std=c++11 -I/usr/local/include helloworld.pb.cc helloworld.grpc.pb.cc greeter_server.cc -o greeter_server -static /home/grpc/libs/opt/libgrpc_cronet.a /home/grpc/libs/opt/libgrpc++_reflection.a /home/grpc/libs/opt/libgpr.a /home/grpc/libs/opt/libgrpc++_unsecure.a /home/grpc/libs/opt/libgrpc++_cronet.a /home/grpc/libs/opt/libgrpc_plugin_support.a /home/grpc/libs/opt/libgrpc.a /home/grpc/libs/opt/libgrpc_unsecure.a /home/grpc/libs/opt/libgrpc++.a /home/grpc/libs/opt/protobuf/libprotobuf.a -lpthread

**Comment by AngryLemonn** [comment]
Following the hello world Makefile, this could be an example for cross compile with grpc libs as static:
```
CXX = arm-linux-gnueabi-g++
CPPFLAGS += -I/usr/local/include -pthread -static
CXXFLAGS += -std=c++11
LDFLAGS += -L/path/to/cross/lib -L/path/to/cross/lib/probuf \
           -grpc++ -grpc       \
           -lgrpc++_reflection \
           -lprotobuf -lpthread -ldl

.PHONY: all

all: greeter_client greeter_server

greeter_client: helloworld.pb.o helloworld.grpc.pb.o greeter_client.o
	$(CXX) $^ $(LDFLAGS) -o $@

greeter_server: helloworld.pb.o helloworld.grpc.pb.o greeter_server.o
	$(CXX) $^ $(LDFLAGS) -o $@
clean:
        rm -f greeter_client greeter_server
```
I don't know if this can help you, but something is something...

Regards,
J. A.

**Comment by vish74** [comment]
So, I was stuck with same errors (`zlib_compress`) with this Makefile as I was doing same thing with or without example Makefile.

But I figured out that there is some issue with `third_party/zlib` and don't know why it didn't detect anything during gRPC build !

I downloaded zlib v1.2.8 again and cross compile that library. [Info](https://how-to-build-for-arm.wikispaces.com/zlib)
Added falgs in CPPFLAGS and LDFLAGS, and that could compile the server code. :)

Thanks.

**Comment by bharathsjois** [comment]
I face the same below problem as @AngryLemonn did when I build the examples with shared libraries for an ARM target. And I don't see this problem when I build it (using shared libraries) for the x86_64 host. Everything works on the target device when I use static linking, but it is not a preferred method for me.

`error while loading shared libraries: read: cannot open shared object file: No such file or directory`

`readelf` also shows that a "read" is one of the shared objects required by the binary compiled for the target, but I have no idea what this is.

Any hints? Directions?

//Bharath

**Comment by victorlin0** [comment]
I'm trying to follow the process but cross compile to a webos environment ( it is on ARM linux eabi environment) However, when I try to run sudo make install for gRPC, I got

strip: Unable to recognise the format of the input file `/home/vlin/src/webos1/grpc/libs/opt/libgrpc_unsecure.a(ares_strerror.o)'
..

I also got 
strip: Unable to recognise the format of the input file `/home/vlin/src/webos1/grpc/libs/opt/libgpr.so.3.0.0'
Makefile:2162: recipe for target 'strip-shared_c' failed

Any suggestion on how to debug the issue?

**Comment by manikandan83** [comment]
I did cross compile for ARM architecture. When running the greeter_server, I am getting the following error

./greeter_server: error while loading shared libraries: read: cannot open shared object file: No such file or directory".

I dont want to have static linking.  

If anybody has solved this issue. Please share your thoughts.

/Br
Mani. C

**Comment by Rohit3649** [comment]
@vish74  Are you able to generate plugins ?
when i am trying  "make plugins" its giving below error

[AR]      Creating /home/rohit/work/rohit_grpc/grpc/libs/opt/libares.a
ar: /home/rohit/work/rohit_grpc/grpc/libs/opt/libares.a: No such file or directory
make: *** [/home/rohit/work/rohit_grpc/grpc/libs/opt/libares.a] Error 1

can you please help in this ?
i am using release version 2.0.
