### ISSUE TITLE
How to process the request with multi threading?

### ISSUE THREAD

**Issue by targetnull** [grpc/grpc#9728]
Currently the [async_server](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_server.cc) example is still running a main loop `HandleRpcs`, which might be time consuming when several peers trying to connect at the same time. I guess I could use a thread pool when using raw socket, but I'm not sure whether this would work with grpc. Is there any function that I could use? Thanks.

**Comment by sreecha** [comment]
Hi @targetnull , 
There are two ways you can scale your server

1. Add more completion queues (created by calling `builder.AddCompletionQueue()` as it is shown in the example) and have different `HandleRpc` type loops for each completion queue (Note that all HandleRpc is doing is calling `CompletionQueue::Next()` method and processing the event)
2. Have more than one thread call `CompletionQueue::Next()` at the same time. CompletionQueue::Next()` is thread safe and can have multiple threads call this (and in case of an event on the queue, we guarantee that only one thread returns from that function)

Hope this helps

**Comment by dgquintas** [comment]
To complete @sreecha's answer, [here](https://github.com/grpc/grpc/blob/master/include/grpc++/impl/codegen/completion_queue.h#L40) is where the Completion Queue's thread-safe guarantee is given.

**Comment by feverzsj** [comment]
I think the greeter_server.cc already does what you want. Although it is called "sync", which is kinda confusing, it actually dispatches rpcs from the CompletionQueue to a thread pool.

**Comment by sreecha** [comment]
@feverzsj , If you are talking about the greeter_server.cc [here](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_server.cc), then it is infact a *sync* server. As a sync server api user, you don't have to write a threadpool to handle the RPCs
(gRPC _internally_ creates a threadpool to handle RPCs if you use the sync API and perhaps this is what you were referring to)

**Comment by targetnull** [comment]
Thanks to you all! You've been very helpful
