### ISSUE TITLE
Python gRPC client gets stuck if you hit process limits

### ISSUE THREAD

**Issue by public** [grpc/grpc#9743]
When running Python gRPC client's we've noticed that in some conditions our clients will get stuck and every request through them will always timeout. Restarting them sometimes solves this.

After some debugging it seems like this is due to hitting process number limits can cause gRPC to get in a state where no RPCs will ever succeed until you restart the process again once the resource contention has stopped.

Specifically it seems like the `clone` syscall to create a new thread fails with EAGAIN, but gRPC doesn't seem to handle this case well and ends up not working anymore.

Obviously the system is not in a great state if you can't start threads but I would expect the gRPC call to fail with `INTERNAL` or something like that.

**Comment by public** [comment]
Reading the source code it seems like while `gpr_thread_new` does return whether or not it managed to make a thread or not, basically none of the call sites outside of the test suite actually check it.

e.g.

https://github.com/grpc/grpc/blob/46357c882df1afc28f7a5228c40fde522093fa32/src/core/lib/iomgr/executor.c#L118

https://github.com/grpc/grpc/blob/7dd42bf3d8fefd00603d6f6e502fc286ac721f81/src/core/lib/profiling/basic_timers.c#L221

https://github.com/grpc/grpc/blob/49c44f53709936abc9aa014ee1173552b630b920/src/core/lib/iomgr/ev_poll_posix.c#L1386

**Comment by public** [comment]
@ctiller Would a simple demo reproduction be useful for you in resolving this?

**Comment by kpayson64** [comment]
@public 
What is causing the thread exhaustion?  Is it gRPC? Or are there a lot of threads in your program?

**Comment by public** [comment]
@kpayson64 The thread exhaustion is caused by non-gRPC related pressure on the machine. It's just when we hit that situation gRPC clients behave badly. I would expect them to return some kind of sensible error even if it was just "INTERNAL_ERROR" rather than getting stuck like this.

**Comment by public** [comment]
Happy to help out solving this issue but since this would be my first contribution some communication would help me be certain I'm doing the right thing.

Is it intentional that these errors are never checked?

**Comment by jonparrott** [comment]
@kpayson64 @ctiller friendly ping, users are running into this during resource exhaustion, which is surprisingly easy to hit in docker environments. Considering @public has volunteered to help fix this, can we at least point them in the right direction?

**Comment by kpayson64** [comment]
We could have a thread creation failure result in a failed RPC, but I'd prefer to go the route of just hitting a ```GPR_ASSERT()``` that causes the program to die on thread creation failure (rather than hang with undefined behavior).

@ctiller thoughts?

**Comment by public** [comment]
Having it assert and crashing the process would have probably been a reasonable outcome in our situation. It would have aided in debugging the root cause (badly configured user limits) in fact.
