### ISSUE TITLE
Using ServerBuilder in async mode, how do I tell that the port is in use?

### ISSUE THREAD

**Issue by zhengcai** [grpc/grpc#9749]
Hello,

Currently we are using gRPC-1.0.0, and our server is using gRPC in async mode, and our code is doing the following:

builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
builder.RegisterService(agent_service_.get());
cq_ = builder.AddCompletionQueue();
server_ = builder.BuildAndStart();
...
agent_service_->RequestFoo(...)

If the specified port is not in use, then everything works just fine. But if it is already in use, then both 'AddListeningPort' and 'BuildAndStart' didn't return any error. We will only an exception when later on calling 'agent_service_->RequestFoo(...)', which will crash the program.

So I was wondering, is there any elegant way of checking whether the server build has successfully or unsuccessfully bind the port? Or we have to do it in our own way (like using 'connect()') before actually starting the async services, in order to prevent the program crash?

Thanks a lot in advance.

**Comment by y-skindersky** [comment]
I am using the code like below and have the same issue:
```
_rpcServer = new Grpc.Core.Server(channelOptions)
{
  Services ={ Service.BindService(new ServerRpcImpl()) },
  Ports ={{ host, port, ServerCredentials.Insecure }}
};
_rpcServer.Start();
```

**Comment by mehrdada** [comment]
You can pass an `int*` to `AddListeningPort` which after `BuildAndStart` is called, is populated with the port number it binds to, or 0 if unsuccessful. Checking that value should give you the information you need. Please re-open the issue if that does not resolve the problem. 

```c++
int bound_port = 0;
builder.AddListeningPort(server_address, grpc::InsecureServerCredentials(), &bound_port);
builder.RegisterService(agent_service_.get());
cq_ = builder.AddCompletionQueue();
server_ = builder.BuildAndStart();
if (bound_port == 0) { /* unsuccessful binding */ }
...
agent_service_->RequestFoo(...)
```
