### ISSUE TITLE
Deflake tsan core tests

### ISSUE THREAD

**Issue by dklempner** [grpc/grpc#975]
Running tests under tsan mode is (still) substantially flakier than other modes, due to a combination of timing issues and actual tsan failures.

As a general target, we should be able to run the full suite of tests O(100) times under tsan without running into issues.

**Comment by dklempner** [comment]
The only failures I'm seeing at --runs_per_test 10 and slowdown factor of 2 are in the cancel_after_invoke tests.

Or at least, I'd like to say that, but run_tests.py seems to think tests are failing but isn't printing any output for some of them.

**Comment by ctiller** [comment]
Are they running over 300 seconds? There's a hard coded constant in
jobset.py.

If someone wants to make it not hard coded, that'd be good.

**Comment by dklempner** [comment]
I see, the issue with the mysterious test failures without output may be that we only add a newline if we're running on Travis.

**Comment by dklempner** [comment]
Current update:

I believe the cause is that we don't properly handle the case where the client disconnects at the same time the transport detects an error. The client_channel.c code handles GRPC_CHANNEL_DISCONNECT by sending down grpc_client_channel_destroy() and then synthesizing a GRPC_TRANSPORT_CLOSED message up the stack (which will ultimately release a refcount in channel.c, which will likely asynchronously destroy_channel()).

Meanwhile, the transport layer detects an error and tries to report a GRPC_TRANSPORT_CLOSED, but the channel may have already gone away.

**Comment by dklempner** [comment]
If I remove the synthesized GRPC_TRANSPORT_CLOSED, chttp2_fullstack_cancel_after_invoke passes 9996/10000, with all four failures being bad luck with picking a port.

Obviously other tests fail if I do that, but it seems to confirm the theory.

**Comment by jayantkolhe** [comment]
Closing since this is fairly old.. Please file another bug if jenkins tsan is flaky..
