### ISSUE TITLE
NextMessageSize is not tested

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#9758]

**Comment by vjpai** [comment]
This is a little tricky. It's tested right now in the sense that it is being called, but the value is not checked. That said, remember that NMS gives the wire-size of the message, which may not correspond to the proto size of the Read that comes out. We don't currently have an API-level way of seeing the serialized size of the Read, afaik.

**Comment by vjpai** [comment]
This will become real when NextMessageSize is implemented for real (as opposed to being conservative)
