### ISSUE TITLE
How to run GRPC c++ compiled code on google cloud server

### ISSUE THREAD

**Issue by rajeevinimekumar008** [grpc/grpc#9791]
I have been trying running `GRPC` application on google cloud server but it gives me error

error while loading shared libraries: `libgrpc++.so.3 : cannot open shared object file:No such directory/file exist`

I have made this example run on `local linux server` where i have installed `protoc and protoc c++ plugin`. From this local server i have compiled the code and trying to make it run on `google cloud server` which does not have this installed packages i.e. `protoc and protoc c++ plugin`.

Do i need to install `protoc and protoc c++ plugin` on google cloud server also.

Or i just need to put the required libs somewhere in google cloud server machine ?
![error](https://cloud.githubusercontent.com/assets/25894833/23115297/f0b97848-f769-11e6-82f6-62280457c7a7.png)

**Comment by yang-g** [comment]
As mentioned in https://github.com/grpc/grpc/blob/master/INSTALL.md, you should build and install grpc from source to use grpc C++ at the GCE instance.
