### ISSUE TITLE
CSharp plugin

### ISSUE THREAD

**Issue by cosaques** [grpc/grpc#9792]
Hi there, please advise, how can I develop a GRPC plugin that handles the transmission of request ID through c# generated code ?

**Comment by jtattermusch** [comment]
To be honest, I am not sure I understand the question, can you elaborate.

Also, this is not an issue, so I'll close it. For gRPC related usage question, use our user forum https://groups.google.com/forum/#!forum/grpc-io or ask on stackoverflow.com
