### ISSUE TITLE
Google speech recogntion API grpc.framework.interfaces.face.face.AbortionErro ?

### ISSUE THREAD

**Issue by mohamed-ryan** [grpc/grpc#9793]
i use google speech streaming 6 months ago in my laptop (ubuntu os)  using python when i but the code on ARM architecture and install dependencies i get the following error 
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAUTHENTICATED, details="Illegal metadata")
how can i solve this problem

**Comment by nathanielmanistaatgoogle** [comment]
Can you tell us a lot more about how you are constructing your channels and stubs? How are you making your RPCs? What metadata are you passing?

**Comment by nathanielmanistaatgoogle** [comment]
Closing but happy to take another look if you're able to share those extra details with us.
