### ISSUE TITLE
Sync C++ server should catch exceptions thrown by RPC methods

### ISSUE THREAD

**Issue by tudor** [grpc/grpc#9795]
While gRPC itself doesn't use exceptions, code written by users of gRPC often does.

It would be nice if the C++ server code caught exceptions that propagate into gRPC from method implementations. This could be done either in generated code, or in  `RpcMethodHandler::RunHandler`.

I resorted to something like

```
Status myMethod(ServerContext* ctx, const MyRequest* req, MyResponse* resp) {
    try {
        // code here
    } catch (const std::exception& e) {
        return Status(INTERNAL, e.what());
    }
}
```

but that ends up having to be replicated in every method implementation (using preprocessor macros) which is ugly and error-prone.

**Comment by tudor** [comment]
This is understandably difficult to do for async methods: the user usually has work to do after sending the response (cleanup, calling `RequestMyMethod` again, etc), and there's more state to keep track of (has the response already been sent?), so I'm only suggesting doing this for sync methods.

Async programming and exceptions really don't play well with each other, anyway.

**Comment by ctiller** [comment]
Hey, this would be good to do, and I've been meaning to get there but have
not yet.  Hopefully it's a relatively simple change to server code (and of
course an additional test).

**Comment by vjpai** [comment]
So, as a matter of pushback: my concern is that we can't know what the user wants. We could catch and exception and give some kind of status code, but it's not likely that it's what the user actually wants. For example, I think that INTERNAL is likely not appropriate in the above; maybe it should really be RESOURCE_EXHAUSTED or UNAVAILABLE or something else depending on what the user code is actually trying to do when it has its exception. And the latter is something that the user knows far better than we ever will. So I'm going to suggest leaving this behavior as is in the stock gRPC C++ sync server implementation.

**Comment by vjpai** [comment]
After that comment, which really comes from @yang-g and which I've discussed with @ctiller , I'm going to close the issue. Please reopen if there's an unavoidable need for it.

**Comment by vjpai** [comment]
Further discussion of this topic can take place in #13706. It may be justified to do _something_ (which the user can then override) since doing something would at least keep the server alive.
