### ISSUE TITLE
Inconsistent rewriting of Empty to GPBEmpty with PHP

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#9796]
Using the recommended protoc invocation from [here](http://www.grpc.io/docs/quickstart/php.html#generate-grpc-code), a proto message of name `Empty` is generated as `GPBEmpty` under the `GPBMetadata` directory, but under the non-metadata directory it is still generated as `Empty` causing errors in PHP.

You can see in the generated non-metadata files that it knows about the `GPBEmpty` name from the metadata, but it still has the class name `Empty`.

```php
class Empty extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\MyProject\Rpc\GPBEmpty::initOnce();
        parent::__construct();
    }

}
```

protoc version: `libprotoc 3.2.0`

**Comment by tbillington** [comment]
I tried to manually rewrite the `Empty` class to `GPBEmpty` but it doesn't work, error:

```
Notice: Undefined index: MyProject\Rpc\GPBEmpty in /Users/trent/src/github.com/myproject/phptest/vendor/google/protobuf/php/src/Google/Protobuf/Internal/DescriptorPool.php on line 109
```

I assume the name `Empty` is included in the metadata description, so when I manually renamed it to `GPBEmpty` it now can't find it ?

**Comment by tbillington** [comment]
The service that uses `Empty` is using what would be the correct version `MyFunction(\MyProject\Rpc\GPBEmpty $argument, ...`.

**Comment by tbillington** [comment]
Related to https://github.com/google/protobuf/commit/99564c3347223b92e49bd40f37b8c0d6fc6a3971 ?.

**Comment by stanley-cheung** [comment]
This is a protobuf issue

**Comment by tbillington** [comment]
I also posted it there, I guess it can be closed here if it's not a grpc issue.

Also I was incorrect in saying it produced an error when I rewrote.. It does work but produces a notice.
