### ISSUE TITLE
Inconsistent protobuf versions in PHP code + README.

### ISSUE THREAD

**Issue by dhowden** [grpc/grpc#9799]
The README insists on protobuf 3.2.0+ (https://github.com/grpc/grpc/tree/master/src/php#protobuf-compiler), but the `composer.json` uses 3.1.0 (https://github.com/grpc/grpc/blob/master/src/php/composer.json#L8)?

**Comment by stanley-cheung** [comment]
Thanks for pointing out the discrepancies. It should really read 3.1.0+ (but better with 3.2.0+ because of various improvements).

I will fix the documentation shortly.
