### ISSUE TITLE
Steps for Change of license

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc#9828]
Issue to track the following changes
- [ ] change `LICENSE` file to Apache v2. 
- [ ] change license text in all source files.
- [ ] change license type in `BUILD` files.
- [ ] change copyright text from "Google Inc" to "gRPC Authors" in all files.
- [ ] Add a `AUTHORS` file

**Comment by zinuga** [comment]
Another item we should add is removing PATENTS file which is redundant with the Apache license. We can explain clearly why it's no longer needed in that the Apache license provides a functionally identical patent grant.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/11438
https://github.com/grpc/grpc-java/pull/3078

**Comment by yurishkuro** [comment]
Q: what about CLA? The [CONTRIBUTING.md](https://github.com/grpc/grpc-go/blob/master/CONTRIBUTING.md) refer to a CLA that says all copyright is assigned to Google.
