### ISSUE TITLE
Use more standard Git tag names

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#984]
The v0.5.0 release was tagged as "release-0_5_0". This should instead just be "v0.5.0".

The v0.5.0 format is the standard for git projects, as can be seen by [Git](https://github.com/git/git) and [Linux](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/). GitHub actually has customizations for that version format and produces more standard tarballs.

As things are now, if you download the [version 0.5.0](https://github.com/grpc/grpc/archive/release-0_5_0.zip) the download will be named grpc-release-0_5_0.zip and the folder inside will be grpc-release-0_5_0. If instead the tag was v0.5.0, the download and folder would be named grpc-0.5.0 (notice how GitHub removes the leading 'v'), which is the normal name for most open source releases.

**Comment by murgatroid99** [comment]
I agree with this. @a11r, what do you think of switching to this naming convention?

**Comment by ejona86** [comment]
This is now being done, from v1.0.0 forward.
