### ISSUE TITLE
Benchmarks on Windows miss data since 1/27

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9854]
http://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

@nicolasnoble @dgquintas @matt-kwong

**Comment by jtattermusch** [comment]
Ok, I think I know what's broken. Thanks for noticing this.

**Comment by jtattermusch** [comment]
I installed some newly required prerequisites to the windows perf workers and things should be fine now.

**Comment by asgerhallas** [comment]
I don't know how it's supposed to look, but there seems to be a problem still?

**Comment by jtattermusch** [comment]
@matt-kwong  can you take a look?

**Comment by matt-kwong** [comment]
Thanks for letting us know. The issue should be resolved. I'm not sure why, but our dashboards are sometimes bugged and say they can't run queries, and the solution is to refresh the dashbaords with a no-op save.
