### ISSUE TITLE
Unable to send metadata with keys having uppercase characters

### ISSUE THREAD

**Issue by vinvinod** [grpc/grpc#9863]
While trying to add metadata during rpc call, exception occurs.

```
E0224 12:16:17.340946000 140737070224320 call.c:614] attempt to send invalid metadata key: X-B3-Sampled
metadata was invalid: [('X-B3-Sampled', '1')]
```
There are no problems when there are no uppercase characters in the key.
I am using the python api.  `pip freeze` says my grpc version is `1.1.0`

I see that there was this issue earlier and it has been closed in https://github.com/grpc/grpc/issues/4389

**Comment by ncteisen** [comment]
All metadata keys must be lowercase.

For more info, check out [validate_metadata.c](https://github.com/grpc/grpc/blob/master/src/core/lib/surface/validate_metadata.c)

**Comment by vinvinod** [comment]
Thanks
