### ISSUE TITLE
support Trailers-Only responses in C-core

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#9883]
As we discussed last week, we need to change the transport code such that if the server sends initial metadata and status without doing anything else, the status should be sent as part of the initial metadata, and the stream should be closed after initial metadata is sent (i.e., there is no need to send trailing metadata).  This will ensure that in the retry code (which I'm currently working on), we can consider the call to be committed (i.e., no longer retryable) when we receive initial metadata that either (a) does not include status information or (b) contains a non-retryable status code.

Also, since the above behavior is now required for retry support, is there any wire-spec documentation that needs to be updated for this change?

**Comment by markdroth** [comment]
As part of this, we also need to make sure that when the server sends a Trailers-Only response, the transport returns that as trailing metadata instead of as initial metadata (i.e., it should invoke the on_complete callback from the recv_trailing_metadata op instead of invoking the recv_initial_metadata_ready callback).

**Comment by wenbozhu** [comment]
> is there any wire-spec documentation that needs to be updated for this change?

I believe so. We had similar discussion when implementing grpc-web in Nginx. @fengli79 

Specifically, the spec should clarify that:
1. a failure response may contain no message or trailer;
2. status related metadata may be sent as part of response headers; 
3. for #2, the grpc wire spec doesn't distinguish between initial headers and status metadata, should duplicated keys exist.

**Comment by markdroth** [comment]
The [wire spec](http://www.grpc.io/docs/guides/wire.html) already documents the Trailers-Only response.  All that's happening here is that we are adding support for this type of response to C-core.
