### ISSUE TITLE
plumb "not yet seen by server" bit up from transport layer

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#9884]
Specifically, this includes (a) if we have not yet put the request on the wire or (b) the server has sent a GOAWAY indicating that it has not (and will not) process the stream.

**Comment by markdroth** [comment]
We will probably want to indicate this by attaching a new attribute to the grpc_error that gets returned by the transport layer.

**Comment by markdroth** [comment]
Note that, as per recent changes to the retry design, we need to be able to differentiate between these two cases:

- The bytes were never sent on the wire.
- The bytes were sent on the wire but the server told us (either via a GOAWAY or a REFUSED_STREAM) that the stream was not processed.

**Comment by markdroth** [comment]
This is still needed.

**Comment by markdroth** [comment]
We're going to need to do this in Q3.

**Comment by yashykt** [comment]
done in https://github.com/grpc/grpc/pull/28668
