### ISSUE TITLE
undefined symbol: SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by farhan3** [grpc/grpc#9887]
I generated a certificate using cfssl and I'm using it for TLS, but I get the following error:

`node: symbol lookup error: ./node_modules/hfc/node_modules/grpc/src/node/extension_binary/grpc_node.node: undefined symbol: SSL_CTX_set_alpn_protos
`

It seems that the certificate has a field that is only found in newer versions.

**Comment by murgatroid99** [comment]
That's actually an error you're seeing when loading gRPC. The error indicates that gRPC was built with the expectation that Node's copy of OpenSSL has ALPN support, but that is not true of the node binary that you are using. What operating system and version of Node are you using? Did you install Node using nvm, or from source, or using an installer?

**Comment by farhan3** [comment]
OS: RHEL 7.2
Node: v6.9.4

Installed it using yum.

**Comment by murgatroid99** [comment]
OK, it looks like Node on Red Hat uses the system OpenSSL. Can you try updating your system OpenSSL to at least version 1.0.2? If that doesn't work, we may have to make some changes on our end to get it to work.

**Comment by farhan3** [comment]
Upgrading to OpenSSL 1.0.2 on RHEL doesn't seem to be easy since it's not officially supported. I think changes are required on grpc side.

There is no official OpenSSL 1.0.2+ pkg and building from source and replacing the existing version may break other parts of the OS.

**Comment by farhan3** [comment]
I tried OpenSSL 1.0.2k-fips in a Fedora container and that works. But RHEL 7.3 and CentOS ship with 1.0.1e-fips, and that doesn't work.

**Comment by murgatroid99** [comment]
This error can now be resolved by reinstalling gRPC with different options: `npm install --build-from-source --grpc_alpn=false`.
