### ISSUE TITLE
c_linux_dbg_native.bins/dbg/h2_proxy_nosec_test no_logging fails (it's logging)

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9903]
https://grpc-testing.appspot.com/job/gRPC_master_linux/1606/testReport/junit/(root)/c_linux_dbg_native/bins_dbg_h2_proxy_nosec_test_no_logging_GRPC_POLL_STRATEGY_epoll/

**Comment by yang-g** [comment]
Dup of #9976. Fixed by #10018.
