### ISSUE TITLE
tests.cloud_to_cloud:ruby:c++_server:ping_pong segfault in Ruby client

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#9911]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11738/

This is from #9888, which is based on v1.1.x

**Comment by apolcyn** [comment]
closing, not looking into this now since it hasn't been seen in a while, and the log is inaccessible. this might have been fixed along with e.g. https://github.com/grpc/grpc/issues/12698
