### ISSUE TITLE
csharp_linux_opt_native.csharp.Grpc.Core.Tests.ShutdownHookServerTest regression

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9914]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/3077/testReport/junit/(root)/csharp_linux_opt_native/csharp_Grpc_Core_Tests_ShutdownHookServerTest/

**Comment by jtattermusch** [comment]
Test log not available anymore, not actionable, closing.
