### ISSUE TITLE
cloud_to_cloud:node:java_server:custom_metadata fails

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9915]
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11757/consoleFull

```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: [] deepEqual [ 'test_initial_metadata_value' ]
    at ClientDuplexStream.<anonymous> (/var/local/git/grpc/src/node/interop/interop_client.js:339:12)
    at emitOne (events.js:77:13)
    at ClientDuplexStream.emit (events.js:169:7)
    at /var/local/git/grpc/src/node/src/client.js:637:14

FAILED: cloud_to_cloud:node:java_server:custom_metadata [ret=1, pid=32611]
```

**Comment by dgquintas** [comment]
Perhaps related to https://github.com/grpc/grpc/issues/9762

**Comment by murgatroid99** [comment]
Has this failure been seen anywhere else? I'm not yet sure if it's an existing failure or it was caused by the changes in that PR

**Comment by dgquintas** [comment]
I haven't seen it anywhere else after a 5 minute search. I'll keep this open for a bit just in case.

**Comment by murgatroid99** [comment]
OK, I have confirmed that this failure was caused by that PR, and is not in master.

**Comment by murgatroid99** [comment]
However, it's worth noting that it was partially caused by grpc/grpc-java#2770.

**Comment by dgquintas** [comment]
Thanks for looking into this.

**Comment by ericgribkoff** [comment]
For posterity: There is no interop test that requests metadata without specifying a payload, so the discussion in https://github.com/grpc/grpc-java/issues/2770 shouldn't impact these tests. https://github.com/grpc/grpc-java/issues/2770 is not a bug, but a discussion of a (possible) gray area in the gRPC spec about expectations of initial metadata versus an appropriate Trailers-Only response.

**Comment by murgatroid99** [comment]
That java issue was causing this problem *because* of a bug in that PR that was causing it to not request any response payload for that test.
