### ISSUE TITLE
C++ async API: add ordering guarantee for AsyncNotifyWhenDone?

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#9918]
Consider adding an ordering guarantee that AsyncNotifyWhenDone will be the last completion queued for a particular stream. Item for discussion.

Argument for: makes it easier to know when all work associated with a stream is done

Argument against: it's safer and saner to provide no ordering guarantees for concurrent completions on the same stream, putting this in once will mean it has to be supported forever, and this issue can be worked around easily in an application by just watching the tags associated with a stream.

**Comment by ctiller** [comment]
It's important to note that grpc_completion_queue (and therefore CompletionQueue) isn't strictly FIFO here, and so to implement this we'd have to:
1. change the grpc_call logic to insert this guarantee (likely minimally adding another atomic in the path)
2. change the grpc_completion_queue semantics to preserve order, or minimally partial order

The latter will have some reasonably severe performance impacts that I'm not certain we could live with.

**Comment by vjpai** [comment]
Good point, and I think that's another strong argument against: nothing at all currently guarantees a FIFO completion queue, nor should there be (since concurrent completion events are, by nature, independent). This was a user feature request, and I think it's best to close it after documenting these as issues.
