### ISSUE TITLE
source build fails with ‘readdir_r’ is deprecated in boringssl on Ubuntu 16.10

### ISSUE THREAD

**Issue by mandeepshetty** [grpc/grpc#9923]
GCC version
`gcc (Ubuntu 4.8.5-4ubuntu4) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
`

glibc version
`ldd --version
ldd (Ubuntu GLIBC 2.24-3ubuntu1) 2.24
`

Ubuntu version 16.10

Stack trace:
`[C]       Compiling third_party/boringssl/crypto/dh/dh_asn1.c
[C]       Compiling third_party/boringssl/crypto/dh/params.c
[C]       Compiling third_party/boringssl/crypto/digest/digest.c
[C]       Compiling third_party/boringssl/crypto/digest/digests.c
[C]       Compiling third_party/boringssl/crypto/directory_posix.c
third_party/boringssl/crypto/directory_posix.c: In function ‘OPENSSL_DIR_read’:
third_party/boringssl/crypto/directory_posix.c:88:3: error: ‘readdir_r’ is deprecated (declared at /usr/include/dirent.h:183) [-Werror=deprecated-declarations]
   if (readdir_r((*ctx)->dir, &(*ctx)->dirent, &dirent) != 0 ||
   ^
cc1: all warnings being treated as errors
Makefile:2079: recipe for target '/root/rpc-test/grpc/objs/opt/third_party/boringssl/crypto/directory_posix.o' failed
make: *** [/root/rpc-test/grpc/objs/opt/third_party/boringssl/crypto/directory_posix.o] Error 1`

grpc on cloning is on commit ID 2a69139aa7f609e439c24a46754252a5f9d37500
After running git submodule update --init, boringssl is on commit ID c880e42ba1c8032d4cdde2aba0541d8a9d9fa2e9

**Comment by stanley-cheung** [comment]
This has been fixed in the 1.1.0 release. #9340
