### ISSUE TITLE
grpc_http_parser should return an error if the current line buffer runs out

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#9925]
Currently returning ERROR_NONE, which does not seem to make sense.
https://github.com/grpc/grpc/blob/master/src/core/lib/http/parser.c#L289

**Comment by jtattermusch** [comment]
Originally, this was seen in #9797

So this is likely root cause for #9762 (C#) and possibly also for #9865 (ruby) #9878 (node). Once fixed, it will hopefully make the flake happen with a more descriptive error message.

**Comment by yang-g** [comment]
Right. This will likely make the log spam disappear but I do not think it will fix the above issues.
