### ISSUE TITLE
Dualstack code isn't robust enough.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#9929]
It happened that on a system where IPv6 is enabled for unavailable that using `connect` will fail with a 'forbidden' error. This is using [Tizen OS](https://www.tizen.org/) on one of the development boards available at Samsung.

The workaround was to do the following on the machine:

```
echo 0 > /proc/sys/net/ipv6/conf/all/autoconf
echo 0 > /proc/sys/net/ipv6/conf/all/accept_ra
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
```

But it means we need a better detection of platforms where IPv6 might not be available even though the `setsockopt` call works.

**Comment by pmarks-net** [comment]
This bug is rather lacking in data, but do I understand correctly that this is a platform where `setsockopt(IPV6_V6ONLY=0)` succeeds, but `connect(::ffff:a.b.c.d)` always fails?

Or, are you actually connecting to an IPv6 address?

**Comment by nicolasnoble** [comment]
On that specific occurrence, connection was made to localhost. Full log is
available at http://pastebin.com/kZKbGc06 - unfortunately it doesn't say
whether or not localhost was resolved to ::1, but my guess says "yes",
since telnet localhost was working properly in that instance.

**Comment by pmarks-net** [comment]
How can I test arbitrary C programs in this environment?

If we find sufficient evidence that the OS is broken, would "fix the OS" be a valid way to resolve this bug?

**Comment by nicolasnoble** [comment]
I think TizenOS is fully open source, and they even have an [SDK](https://developer.tizen.org/development/tools/download) which may contain an emulator exhibiting the problem.

I don't think saying "your OS is broken, request a fix from your manufacturer" is going to help us in the long run. When a customer comes and says "your application isn't able to do a simple connect while telnet can", he really is going to expect the software to work as simply as telnet, and finding every misconfigured OS in the world is going to be an exhausting task. I believe we need better fallbacks in our code to make it robust transparently to the end user, even when facing misconfigured OSes.

**Comment by ctiller** [comment]
I think Nicolas is right here: if we can reasonably proceed to create a
connection we should. I'm fine with a well placed gpr_log or two to suggest
corrective actions (we can try to move the industry forward), but refusing
to work because we are stubborn punishes users.
