### ISSUE TITLE
chrono not found

### ISSUE THREAD

**Issue by vnitinv** [grpc/grpc#994]
In file included from src/cpp/client/secure_credentials.cc:41:
include/grpc++/credentials.h:37:10: fatal error: 'chrono' file not found
#include <chrono>
         ^
1 error generated.
make: *** [objs/opt/src/cpp/client/secure_credentials.o] Error 1

compiling on mac os. 

followed the steps:
 $ git clone https://github.com/grpc/grpc.git
 $ cd grpc
 $ git submodule update --init
 $ make

**Comment by nicolasnoble** [comment]
So... that's weird. We're able to build under Mac. Which version of mac / Xcode do you have ?

**Comment by vnitinv** [comment]
xcode: Version 5.1.1

OS X 10.8.5
