### ISSUE TITLE
Infrequent reads of an operation causing transport closed error.

### ISSUE THREAD

**Issue by landrito** [grpc/grpc#9941]
This is a bug that is blocking https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/899.

For users that are using Datastore#query, if they are not making other kind of datastore operations, the transport will be closed before the operation completes, throwing a GRPC::Internal  / 13 / "Transport closed" error. This is a major bug for datastore. Somehow the user needs to be able to keep the connection alive for operations that are infrequently used.

**Comment by apolcyn** [comment]
this is fixed by https://github.com/grpc/grpc/pull/11054, which is in the latest 1.3.4 release
