### ISSUE TITLE
mach-o, but wrong filetype

### ISSUE THREAD

**Issue by vnitinv** [grpc/grpc#995]
I have installed grpc successfully. But when I try running client get below error. Even if i try importing "from grpc._adapter import _c" directly same issue.

nitinkr-mba13:helloworld nitinkr$ python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 32, in <module>
    import helloworld_pb2
  File "/Users/nitinkr/Coding/grpc-common/python/helloworld/helloworld_pb2.py", line 106, in <module>
    from grpc._adapter import fore
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grpc/_adapter/fore.py", line 38, in <module>
    from grpc._adapter import _low
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grpc/_adapter/_low.py", line 35, in <module>
    from grpc._adapter import _c
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grpc/_adapter/_c.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grpc/_adapter/_c.so: mach-o, but wrong filetype
nitinkr-mba13:helloworld nitinkr$ python
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> grpc._adapter import _c
  File "<stdin>", line 1
    grpc._adapter import _c
                       ^
SyntaxError: invalid syntax
>>> from grpc._adapter import _c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grpc/_adapter/_c.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grpc/_adapter/_c.so: mach-o, but wrong filetype

**Comment by nathanielmanistaatgoogle** [comment]
That is very curious. Could it be something specific to the MacOS platform?

What steps did you take to install Python gRPC into your Python environment?

**Comment by vnitinv** [comment]
i followed below link:
https://github.com/grpc/grpc/blob/master/INSTALL

Mac-specific notes:
-------------------

For a Mac system, git is not available by default. You will first need to
install Xcode from the Mac AppStore and then run the following command from a
terminal:

  $ sudo xcode-select --install

You should also install "port" following the instructions at
https://www.macports.org . This will reside in /opt/local/bin/port for
most Mac installations. Do the "git submodule" command listed above.

Then execute the following for all the needed build dependencies

  $ sudo /opt/local/bin/port install autoconf automake libtool gflags cmake
  $ mkdir ~/gtest
  $ svn checkout http://googletest.googlecode.com/svn/trunk/ gtest-svn
  $ mkdir mybuild
  $ cd mybuild
  $ cmake ../gtest-svn
  $ make
  $ make gtest.a gtest_main.a
  $ sudo cp libgtest.a libgtest_main.a /opt/local/lib
  $ sudo mkdir /opt/local/include/gtest
  $ sudo cp -pr ../gtest-svn/include/gtest /opt/local/include/gtest 

We will also need to make openssl and install it appropriately

  $ cd <git directory>
  $ cd third_party/openssl
  $ sudo make install
  $ cd ../../

If you are going to make changes and need to regenerate the projects file,
you will need to install certain modules for python.

  $ sudo easy_install simplejson mako

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the report. I don't think that this is something that we'll be able to tackle in the next few days but I believe that Mac support for Python gRPC will happen somewhere in the alpha or beta timeline.

**Comment by nathanielmanistaatgoogle** [comment]
Remilestoning - we'd like to support gRPC-Python-on-MacOS shortly after Beta and long before General Availability but aren't considering it a hard Beta requirement.

**Comment by nathanielmanistaatgoogle** [comment]
gRPC Python has come a long way in the year since this was filed - we now support MacOS, but the codebase has changed significantly from what it was. Is this issue still actionable or should it be closed?

**Comment by soltanmm** [comment]
I can't see this being actionable anymore. Our wheels work fine AFAICT (well, as long as pip and/or setuptools are recent enough).
