### ISSUE TITLE
C++ reconnect with backoff when server crashes

### ISSUE THREAD

**Issue by anilmaddala** [grpc/grpc#9959]
Is there a mechanism in C++ to try auto reconnect with backoff, when the server crashes?

Thanks

**Comment by ncteisen** [comment]
Take a look at wait for ready behavior:

API usage: [client_context.h](https://github.com/grpc/grpc/blob/46357c882df1afc28f7a5228c40fde522093fa32/include/grpc%2B%2B/impl/codegen/client_context.h#L232)
Documentation: [wait-for-ready.md](https://github.com/grpc/grpc/blob/5098508d2d41a116113f7e333c516cd9ef34a943/doc/wait-for-ready.md)
