### ISSUE TITLE
How to add custom encryption to gRPC?

### ISSUE THREAD

**Issue by kinghadi** [grpc/grpc#9985]
I have a nodejs server and two android and ios clients. I want to use my own encryption method to encrypt data at clients and decrypt it at the server? I mean this [picture](https://www.dropbox.com/s/q9mv6j6wdmhwyaj/Untitled%20Diagram.png?dl=0)

**Comment by kinghadi** [comment]
[In this post](https://groups.google.com/d/msg/grpc-io/SeD6KjU5yhE/nGA55G7WAQAJ) said that I have to implement an interface in the gRPC core and it requires a good knowledge of gRPC. I think it would be good if gRPC could add a higher layer for custom encryption. In some applications it is needed to do some custom encryption.

**Comment by mehrdada** [comment]
Depending on the gRPC language in use, it might be possible to accomplish that by writing and registering a custom codec that handles the encryption.  Considering gRPC is able to leverage TLS which in most cases is what users want and the versatility of the codec and compression APIs, it is not a high priority for us to add a dedicated custom encryption API with increased complexity.

**Comment by qinyeli** [comment]
Hello. I was wandering if there is a similar interface for Python. I've looked into [StreamStreamClientInterceptor](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L474), but does not look exactly what I need. I am trying to make a custom serializer.
