### ISSUE TITLE
TLS Golang Server with Python client not working

### ISSUE THREAD

**Issue by lunemec** [grpc/grpc#9988]
Hello,

I've come across strange issue. I have Golang grpc server and python client. I have tested these together in insecure mode, which works perfectly. I'd like to add TLS, but for some reason python client can't connect to the server and server only returns these cryptic messages:

```
2017/03/06 14:56:14 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp [::1]:8002->[::1]:47542: write: broken pipe"
2017/03/06 14:56:14 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 127.0.0.1:8002->127.0.0.1:50096: write: broken pipe"
2017/03/06 15:06:25 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
```

Server:
```go
port := 8002
addr := fmt.Sprintf("0.0.0.0:%d", port)
lis, err := net.Listen("tcp", addr)
if err != nil {
	grpclog.Fatalf("failed to listen: %v", err)
}

creds, err := credentials.NewServerTLSFromFile("../cert/out/127.0.0.1.crt", "../cert/out/127.0.0.1.key")
if err != nil {
	grpclog.Fatalf("failed to create credentials: %v", err)
}
opts := []grpc.ServerOption{
	grpc.Creds(creds),
}
grpcServer := grpc.NewServer(opts...)

// regiser + Serve omitted
```

Client:
```python
ca_cert = open('../cert/out/CA.crt').read()
creds = grpc.ssl_channel_credentials(root_certificates=ca_cert)
channel = grpc.secure_channel("127.0.0.1:8002", creds)
```

The certificates were generated with certstrap.

The strange thing is, when I create Golang client, it works perfectly (even with mutual TLS), but never when using Go server and Python client.

Any ideas what should I try?

Thank you.

**Comment by lunemec** [comment]
/cc jtattermusch

Hi, I got your contact information from my coleague. I understand you did a presentation in our company about gRPC. Do you know of anyone running into similar issue?

The problem is only when using Python client. When Server+Client are Go, it works.

Thanks!

**Comment by jtattermusch** [comment]
CC @jboeuf

**Comment by jtattermusch** [comment]
have you tried setting GRPC_VERBOSITY=debug  and GRPC_TRACE=all on the client? That could tell you more about why the secure connection is failing (see https://github.com/grpc/grpc/blob/master/doc/environment_variables.md).

**Comment by jtattermusch** [comment]
GRPC_TRACE=transport_security might be your best bet.

**Comment by lunemec** [comment]
Thank you for the quick response! I just tried again to replicate the issue, but it works now ... with the same code. I created the certificates again, so maybe that was the problem.

Thank you for the link to ENV variables, that will certainly help in the future.
I'll close this issue for now, it seems to be working now.

**Comment by uguessmyid** [comment]
Hi @lunemec I am Also facing the Same issue. It works perfectly fine when both the Server and Clients are in Go, and also with tls=false it works with python client also. 
But When TLS is enabled it is throwing the same error as you have mentioned above.
Can you tell us how you have solved the issue?
The Same is happening when i try with node js client also

**Comment by lunemec** [comment]
Well, the problem kinda solved itself, I deleted the code responsible for TLS in server and client, then I wrote it again and it worked.
Hovewer I have a similar issue now, but since I used GRPC_VERBOSITY=debug, I know the problem is in certificate. Try to use this, there should be openssl error messages pointing you to the problem.

**Comment by lunemec** [comment]
Be careful how you created the certificate. If you created it for IP 127.0.0.1, be *sure* to use "127.0.0.1:PORT" in your client config! I think the problem was I used "localhost:PORT" which is *not* the same. 

When you use GRPC_VERBOSITY=debug, you'll see something like this:
```
D0313 12:35:18.933762442    2371 security_handshaker.c:126]  Security handshake failed: {"created":"@1489404918.933746359","description":"Peer name localhost is not in peer certificate","file":"src/core/lib/security/transport/security_connector.c","file_line":501}
```

Which means you should use 127.0.0.1 instead of localhost. Or you may have problem with certificate.
